### ISSUE TITLE
exponnorm.pdf returns NAN for small K

### ISSUE THREAD

**Issue by s04lg934jkg** [scipy/scipy#10003]
For small values of K exponnorm.pdf returns nan. 

### Reproducing code example:
```
from scipy.stats import exponnorm
exponnorm.pdf(1, K=0.01)
Out[3]: nan
```

### Error message:
```
...\Anaconda3\lib\site-packages\scipy\stats\_continuous_distns.py:1410: RuntimeWarning: overflow encountered in multiply
  return 0.5 * invK * expval * sc.erfc(-(x - invK) / np.sqrt(2))
...\Anaconda3\lib\site-packages\scipy\stats\_continuous_distns.py:1410: RuntimeWarning: invalid value encountered in multiply
  return 0.5 * invK * expval * sc.erfc(-(x - invK) / np.sqrt(2))
```

### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.1 1.16.2 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```

**Comment by ev-br** [comment]
It's interesting. It does try to avoid this overflow,
https://github.com/scipy/scipy/blob/v1.2.1/scipy/stats/_continuous_distns.py#L1410

```
# Avoid overflows; setting np.exp(exparg) to the max float works
#  all right here
expval = _lazywhere(exparg < _LOGXMAX, (exparg,), np.exp, _XMAX)
return 0.5 * invK * expval * sc.erfc(-(x - invK) / np.sqrt(2))
```

*but* when `expval` equals `_XMAX`, the result of multiplying it by `invK` overflows. The resulting `inf` is multiplied by the zero value of `erfc`, which results in a nan. The simplest fix seems to be to fix the order of multiplications by bracketing the product,  `(expval * sc.erfc(-(x - invK))`. 

Would you be interested in sending a pull request, @s04lg934jkg ? This would need a test, too https://github.com/scipy/scipy/blob/v1.2.1/scipy/stats/tests/test_distributions.py#L1272

**Comment by 7vikpeculiar** [comment]
Hi, can I work on this ?
