### ISSUE TITLE
Poisson documentation issue 

### ISSUE THREAD

**Issue by SubutaiBogatur** [scipy/scipy#10001]
https://github.com/scipy/scipy/blob/14142ff70d84a6ce74044a27919c850e893648f7/scipy/stats/_discrete_distns.py#L479

Before "mu" in nominator should have backslash: "\mu". Else it's weird in documentation page: https://docs.scipy.org/doc/scipy-1.1.0/reference/generated/scipy.stats.poisson.html

**Comment by ilayn** [comment]
Thanks @SubutaiBogatur for taking the to report this. It is already fixed in the latest docs (you are looking at v1.1.0). Here is the newest one:

http://scipy.github.io/devdocs/generated/scipy.stats.poisson.html
