### ISSUE TITLE
scipy installation problem via seaborn

### ISSUE THREAD

**Issue by cedricgrimault** [scipy/scipy#10013]
My problem is related to the installation of scipy on a raspberry pi 3.
more precisely when I install the module seaborn.

### Reproducing code example:

```
pip install seaborn
```

### Error message:

```
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_UbIfb/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i8fh3k-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-_UbIfb/scipy/

```

### Scipy/Numpy/Python version information:

Python 3.4.3 :: Continuum Analytics, Inc.
conda 3.16.0 (Miniconda 3)

Thanks for your help

**Comment by ilayn** [comment]
This looks like a python clash. If you are using *conda environments, avoid using `pip` but instead use `conda` commands. When you mix the two there is almost always problems.
