### ISSUE TITLE
Distribution names `weibull_min`and `weibull_max` should be explained

### ISSUE THREAD

**Issue by chrisb83** [scipy/scipy#10014]
No error, I just noted that `weibull_min` is usually called Weibull distribution and it arises as the limiting distribution of the rescaled minimum of iid random variables (https://en.wikipedia.org/wiki/Fisher–Tippett–Gnedenko_theorem)

`weibull_max` is just the distribution of -X if X is `weibull_min`, and therefore, the limiting distribution of the rescaled maximum of iid random variables. (so if negative scale parameters  were possible, one could go from one distribution to the other with `scale = -1`)

I think it would be nice to explain this in the docstring since the distribution names are not standard.

**Comment by WarrenWeckesser** [comment]
I made some relevant [comments on the scipy-dev mailing list](https://mail.python.org/pipermail/scipy-dev/2019-January/023298.html) back in January, including

> So I think we are better off *not* picking one to be called the
"usual" Weibull distribution.  The current names accurately describe
the basis of the two flavors of the distribution.  However, we should
improve the documentation to include this information about the
min/max distinction in their docstrings.  We should do the same for
gumbel_l and gumbel_r.  I'd be happy to make this change, but I
probably won't get to it in the near future, so I'd be even happier if
someone created a pull request that added this information to the
docstrings of weibull_min and weibull_max.  Similar updates for
gumbel_l and gumber_r could be made at the same time or in a separate
pull request.

So I agree that better documentation of the `weibull_min` and `weibull_max` distributions would be a great improvement.
