### ISSUE TITLE
The python `input` built in function is used as argument name in multiple functions

### ISSUE THREAD

**Issue by rfezzani** [scipy/scipy#10010]
While reviewing some code, I noticed that `input` is used as argument name in multiple functions in the following modules:

* scipy.ndimage.morphology
* scipy.ndimage._ni_support
* scipy.ndimage.measurements
* scipy.ndimage.interpolation
* scipy.ndimage.fourrier
* scipy.ndimage.filters
* scipy.signal.signaltools

`input` being a python built-in function, a more appropriate argument name should be used (arr, in_arr, arr_in or what ever...).

I would be happy to  contribute on this if you think that it is a real issue.

### Scipy/Numpy/Python version information:

```
1.3.0.dev0+41f26a2 1.16.2 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
Hi @rfezzani, thanks for the suggestion. We have discussed this before and decided not to change the use of `input`, because changing the name would be a backwards compatibility break for very little real-world gain.

**Comment by rfezzani** [comment]
Thank you for your quick answer. I really appreciate. I don't think that an argument name modification can introduce backward compatibility issue.
Can I fix this by my side in my personal fork and submit it if I observe no backward compatibility break?
Thanks again.

**Comment by ilayn** [comment]
Backwards compatibility break meaning, if somebody already used in their project with the current function and then we change it, their code will not function anymore.

**Comment by rfezzani** [comment]
I fully agree. This issue is not about changing the behavior of the function, or its interface, it is only a matter of argument naming in the source code and its documentation.

**Comment by ilayn** [comment]
Same issue. If they already used that keyword `input=.....` their code will stop working because `input` will cause an error.

**Comment by rfezzani** [comment]
I am sorry, but I don't get your point here.

If an argument name is modified in the definition of a function, it only affects its scope. So the proposed modifications should only affect the definition blocks of the modified functions.
And if `input` is assigned in the users code, this doesn't affects scipy code neither.

I can't figure out how this modification can introduce backward incompatibility.

Can you please elaborate more on this to explain me if there is any side effect that I don't see.
Thanks again for your time.

**Comment by ilayn** [comment]
If somebody wrote via keywords which is the way to go in any python function for better readability

```python
a = np.array([...])
zzz = ndimage.measurements.histogram(input=a, min=0, max=1, bin=10)
...
```
and we change the input argument name to `input_arr` this breaks the given code.

**Comment by rfezzani** [comment]
OK, now I see :-)
Thx.

**Comment by rfezzani** [comment]
Just a suggestion:
What about adding `**kwargs` to the definition of the refactored functions, checking if `'input'` is in `kwargs`, and if it is the case assign `kwargs['input']` to `input_arr` and finally warn the user that using `input` as argument name will be deprecated?

for example, in scipy/measurements.py:
```
def histogram(input_arr, min, max, bins, labels=None, index=None, **kwargs):
    """
    DOCSTRING
    """
    if 'input' in kwargs:
        input_arr = kwargs['input']
        warnings.warn("The use of 'input' as argument is deprecated",
                      DeprecationWarning)
    ...
```

I think that backward compatibility is maintained here. What do you think?

**Comment by rfezzani** [comment]
I think that a decorator can be the solution to satisfy the backward compatibility.

I wrote this code sample demonstrating what I mean:

```
import warnings


class arg_fix:
    """Decorator fixing function calls with explicit old arguments name.

    """

    def __init__(self, arg_mapping):
        """

        Args:
            arg_mapping (dict): mapping between the function's old argument
                names and the new ones.

        """
        self.arg_mapping = arg_mapping

    def __call__(self, f):
        def fixed_f(*args, **kwargs):
            for old_arg, new_arg in self.arg_mapping.items():
                if old_arg in kwargs:
                    # If the user is explicitely calling the function
                    # with an old argument name, warn him that the
                    # function interface has changed.
                    warnings.warn((
                        "'%s' is a deprecated argument name " +
                        "for the function '%s', use '%s' instead.") %
                        (old_arg, f.__name__, new_arg), DeprecationWarning)
                    kwargs[new_arg] = kwargs.pop(old_arg)

            # Call the function with the new arguments
            f(*args, **kwargs)
        return fixed_f


@arg_fix(arg_mapping={'input': 'arg1'})
def func(arg1, arg2=0):
    print(arg1, arg2)


# Call the function with old argument name
func(input=1, arg2=0)

# The output is:
# fix.py:33: DeprecationWarning: 'input' is a deprecated argument name for the function 'func', use 'arg1' instead.
#  (old_arg, f.__name__, new_arg), DeprecationWarning)
# 1 0

```

What do you think of this solution?

I also noticed the use of 'min' and 'max' as argument names (in `ndimage.measurements.histogram` for example :-)) that are also python built in function and should not be used as argument names...

Thank you again for your time.

**Comment by larsoner** [comment]
I think that this effort is not worth the small gain we get from not shadowing a builtin. There are problems with these solutions in terms of how the mangle the docs, hurting readability and discoverability, increasing maintenance overhead by complicating code, etc. (In particular decorators are bad for this sort of thing, and though this can be overcome e.g. by using the `decorator` library, this is a lot of extra "stuff" to add again for minor gains.) So I don't think these sorts of solutions will end up being worth the effort in this case.

**Comment by rfezzani** [comment]
As @rgommers mentioned, this issue was already discussed before, so I assume that I am not the only one that feels uncomfortable with it. I understand the need for backward compatibility  and that's why I came with this solution.

The proposed decorator is not that complicated. All what it does is taking a dictionary as argument for mapping between old argument names and new ones, and check if the patched function is called with an old argument name as keyword argument. In this case, a deprecation warning is thrown and the old argument name is replaced with the new one.

This proposition is designed to be temporary as it throws a deprecation warning, this means that it can be removed at a following major release introducing backward incompatibilities.

I see also that decorators are already used in different places, in particular the `@docfiller` decorator that is used in some functions concerned by the builtin functions shadowing issue. `@docfiller` is used to document the `input` argument, isn't it ironic?..
So why does decorators are acceptable in this case and not for the proposed solution?

Scipy is incontestably a great success and it is a beautiful showcase for the opensource. Good variable naming is in my opinion necessary to ensure code readability and maintainability, and respecting best coding practices should always be promoted.

I don't really consider that fixing this issue would be only a minor gain. Code should not only "work" (PEP20 first aphorism "Beautiful is better than ugly"). This is even more true for scipy that is widely used in the scientific community, and in the universities for educational purpose.

I am a happy user of scipy since years now, and I would be very happy to contribute to make it even more beautiful :-).

If you give me the go, I would be happy to implement this solution and see if there is any trouble with it.
Thank you again for your time.

**Comment by ilayn** [comment]
The problem has many aspects. Indeed you can solve this various ways you can inspect the inputs you can also keep the variables etc. But trust when we say this is going to be a bad thing 3 years down the line because we have many cases like this which has been the case 3 years ago. So for the long game these become really obstacles in the long run because they become the exceptions for other fixes to be taken care of. 

It is not optimal indeed and we could have picked better keywords but it is what it is and fortunately these keywords don't leak out. Thus it would only be a cosmetic change which is what is argued above by other members too.

Hence I hope you don't take it in a negative way but from a complete library perspective this solution actually then becomes _the ugly_ compared to the situation we have because it increases the burden of maintenance and only changes some keyword names that don't hurt or improve any user code.

**Comment by rgommers** [comment]
@rfezzani the issue with maintainability is not unique to shadowing builtins. To give you another example that comes up way more often: fixing PEP8 issues is not something we accept anymore, except if the code is already being worked on for other reasons. The code churn and loss of history (e.g. when using `git blame`) is not worth it for us.

We're not going to change our minds on this one I'm afraid. Thanks so much for your kind words about SciPy and desire to help though. Your decorator is nice work - we would love your help on things that are actual bugs (we have many hundreds) or new features.

**Comment by rfezzani** [comment]
I fully agree with you, this is only a cosmetic change, and I feel a little bit like I am a code-style fanatic now, but well... I still believe in PEP20 :-)

I am sorry to hear that this will never be fixed . Is scipy supposed to be always backward compatible? Is its API supposed to be fixed?

If no, and if backward compatibility breaks are planned to be introduced in future major version, it would be very cool to reopen this issue and add this variable names modification to the backlog, just to satisfy the sleeping code-style fanatics like me :-)

I would for sure be happy to contribute to fix any actual bug, I already filled a really basic bug report #10011 and I am still looking for any issue for which I can be of any help.

Thanks again.

**Comment by rgommers** [comment]
> I am sorry to hear that this will never be fixed . Is scipy supposed to be always backward compatible? Is its API supposed to be fixed?

Not "always", but we measure the benefit of breaking changes against their cost. So if we have to make a breaking change to fix a bug, a trap that users regularly fall into, or add an important new feature, then we do. But as a rule we do not break backwards compatibility for stylistic changes. 

> I would for sure be happy to contribute to fix any actual bug, I already filled a really basic bug report #10011 and I am still looking for any issue for which I can be of any help.

awesome:) I made a suggestion on gh-10011, would be great to have your help
