### ISSUE TITLE
Incorrect check for invalid rotation plane in scipy.ndimage.rotate

### ISSUE THREAD

**Issue by rfezzani** [scipy/scipy#10011]
The case where one of the axes defining the rotation plane is equal to input number of dimensions is not covered: an `IndexError: tuple index out of range` is thrown instead of the expected `RuntimeError: invalid rotation plane specified`.

### Reproducing code example:

```
import numpy as np
from scipy.ndimage import rotate

arr = np.random.rand(10, 10)
rot_arr = rotate(arr, 45, axes=(0, 2))

```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rfez/.conda/envs/SLIDE/lib/python3.6/site-packages/scipy/ndimage/interpolation.py", line 686, in rotate
    ix = input.shape[axes[1]]
IndexError: tuple index out of range
```

### Scipy/Numpy/Python version information:

```
1.2.1 1.16.2 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
thanks for the report @rfezzani. this should be easy to fix with a check for the contents of `axes`. valid values should be in the range `[-2, 1]` it looks like.

**Comment by rgommers** [comment]
should raise a `ValueError` with a sensible exception message

**Comment by rfezzani** [comment]
Hi @rgommers,
I agree, raised error should be a `ValueError` instead of a `RuntimeError`.

In the actual code, a valid axes value is supposed to be in the range `(0, input.ndim)`. A simple fix would be to add the upper bound to the rejection condition: `(0, input.ndim]`.

**Comment by rgommers** [comment]
I think negative axes should keep working, it's fairly normal for users to say `axis=-1` for the last axis.  From a quick read of the code, that does the right thing (but didn't test, `(0, -1)` and `(0, 1)` should be equivalent)

**Comment by rfezzani** [comment]
True, the actual code handles negative axis values by adding input array `ndim` to the input axis value before  validating it.

**Comment by rfezzani** [comment]
I also have some remarks concerning the `rotate` function:

-  `math` module is imported only to compute `sin` an `cos` of the rotation angle. Using  the `numpy` version of these function can avoid this extra module import.
- the `_minmax` function is defined and used but the `numpy.minimum` and `numpy.maximum` functions do the job. Even more, the `numpy.ptp` function can be called, because the computed min is afterward subtracted to the computed max. We can thus get rid of the definition of  `_minmax` (I checked using grep that is not called elsewhere).
- the array `mtrx` is equal to `matrix` (because it is anti-symmetric), so it doesn't need to be defined.
- the three dot products by `mtrx` can be merged in only one call.

What about a refactoring of the `rotate` function?

**Comment by rgommers** [comment]
> math module is imported only to compute sin an cos of the rotation angle. Using the numpy version of these function can avoid this extra module import.

this was probably done because for scalar input `math` is 10x faster than `numpy`. that said, performance is quite irrelevant there - it's 100ns vs 1us.

> We can thus get rid of the definition of _minmax

that looks useful, that sequence of `_minmax` calls is just weird

> the array mtrx is equal to matrix (because it is anti-symmetric), so it doesn't need to be defined.

good catch, that wasn't obvious

> What about a refactoring of the rotate function?

That would be nice. Adding an example to the docstring would also be useful.

**Comment by rgommers** [comment]
addressed in gh-10028, closing
