### ISSUE TITLE
Excessive function calls in scipy.misc.derivative

### ISSUE THREAD

**Issue by PavelStishenko** [scipy/scipy#10012]
For example, if you try to compute first order derivative with first order finite difference formula. To do it you need function values only in two points: ``f(x-dx)`` and ``f(x+dx)``. But ``scipy.misc.derivative`` calculates it three times because of this line: https://github.com/scipy/scipy/blob/c3fa90dcfcaef71658744c73578e9e7d915c81e9/scipy/misc/common.py#L94 
Zero in the middle of ``weights`` list causes computations of ``f(x)`` that is actually not used.
To me  it seems like completely unnecessary 50% slowdown.

**Comment by ilayn** [comment]
@Mazay0 Thank you for taking the time to report this. I agree it can be accelerated as such. In the meantime, here is the relevant part of the roadmap https://docs.scipy.org/doc/scipy/reference/roadmap.html#misc

**Comment by Mazay0** [comment]
I have submitted a PR. Please, review it.

**Comment by andyfaff** [comment]
I think this issue can be closed. `misc.derivative` has been deprecated since 1.10 and `optimize.approx_fprime` does not have this issue.
