### ISSUE TITLE
Fails to build from git

### ISSUE THREAD

**Issue by beojan** [scipy/scipy#10024]
Scipy fails to build when installing from Git.

### Reproducing code example:

```sh
git clone gh:scipy/scipy # gh is an alias for github
cd scipy
pip install --upgrade .
```

### Error message:

```
gcc: numpy/random/mtrand/mtrand.c
      numpy/random/mtrand/mtrand.c: In function ‘__Pyx__ExceptionSave’:
      numpy/random/mtrand/mtrand.c:45208:21: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
           *type = tstate->exc_type;
                           ^~~~~~~~
                           curexc_type
```

### Scipy/Numpy/Python version information:

```
Numpy: 1.17.0.dev0+4a33963
Python: 3.7.3
```

**Comment by WarrenWeckesser** [comment]
That looks like the problem occurs when building *numpy*, not scipy.
 
Either way, I suspect you need to upgrade cython to a newer version. Which version do you have installed?

See, for example, https://github.com/cython/cython/issues/1955 and https://github.com/cython/cython/issues/1978

**Comment by rgommers** [comment]
This is https://github.com/scipy/scipy/pull/9924#issuecomment-478444654

For now, just delete `pyproject.toml` from your local git repo and try again. I'm in the process of fixing this.

**Comment by beojan** [comment]
@rgommers That worked, thanks.

**Comment by tacaswell** [comment]
You can also use `--no-use-pep517` flag to `pip`.
