### ISSUE TITLE
scipy.linalg.svd may give wrong result or raise "SVD did not converge" error

### ISSUE THREAD

**Issue by Yue-Zhengyuan** [scipy/scipy#10032]
My issue is about possible faults in the SVD function. 

## lapack_driver = 'gesvd' may give wrong result

When I try the following code, the numpy.linalg.svd and the "gesdd" method of scipy.linalg.svd can give right result, but the "gesvd" does not work correctly.

### Reproducing code example:

```
import numpy as np
import scipy.linalg as LA

mat = np.array([[-1.,  0.     ],
                [ 0., -1.0-1.j]], dtype=complex)
u1,s1,b1 = LA.svd(mat, full_matrices=False, lapack_driver='gesdd')
u2,s2,b2 = np.linalg.svd(mat, full_matrices=False)
u3,s3,b3 = LA.svd(mat, full_matrices=False, lapack_driver='gesvd')
print(s1, s2, s3, sep='\n')
```

### Output:

```
[1.41421356 1.        ]
[1.41421356 1.        ]
[1. 1.]
```
## lapack_driver = 'gesdd' may raise "SVD did not converge" error

Using the matrix file attached to this issue, 
[matexample.txt](https://github.com/scipy/scipy/files/3055009/matexample.txt)
the 'gesdd' method will raise "SVD did not converge" error
### Reproducing code example:
```
import numpy as np
import scipy.linalg as LA

mat = np.loadtxt('matexample.txt', dtype=complex)
# 'gesvd' works well
u,s,v = LA.svd(mat, full_matrices=False, lapack_driver='gesvd')
# 'gesdd' will raise error
u,s,v = LA.svd(mat, full_matrices=False, lapack_driver='gesdd')
```

### Error message:
```
LinAlgError                               Traceback (most recent call last)
<ipython-input-7-289ffcf3deb3> in <module>()
----> 1 u,s,v = LA.svd(mat, full_matrices=False, lapack_driver='gesdd')

~/anaconda3/lib/python3.7/site-packages/scipy/linalg/decomp_svd.py in svd(a, full_matrices, compute_uv, overwrite_a, check_finite, lapack_driver)
    130 
    131     if info > 0:
--> 132         raise LinAlgError("SVD did not converge")
    133     if info < 0:
    134         raise ValueError('illegal value in %d-th argument of internal gesdd'

LinAlgError: SVD did not converge
```
However, if multiplying the matrix by any number greater than 5, 'gesdd' will work properly.

### Scipy/Numpy/Python version information:
`1.2.1 1.16.2 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)`

**Comment by larsoner** [comment]
Are you using MKL? If so, see:

https://software.intel.com/en-us/forums/intel-distribution-for-python/topic/628049

Due to this error I've been using OpenBLAS for a year or so now. FWIW on my OpenBLAS build I can't reproduce either error you've posted. You will probably/hopefully also find the error goes away if you use something like `MKL_NUM_THREADS=1` when running your examples.

If you are on MKL, over on that issue, feel free to post these examples, try the existing examples I and others have posted, and report your results in testing the existing cases (while making a note of your CPU model, since it seems to matter).

**Comment by ilayn** [comment]
On my system Win10, Python 3.7.1 , SciPy 1.2.0 NumPy 1.16.0 I get no errors however from `LA.lapack.ilaver()` gives me `(3, 8, 0)`.

**Comment by Yue-Zhengyuan** [comment]
For your reference, I put some details of my system here:
OS: macOS 10.14.4 (18E226)
CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz

I am not sure whether I am using MKL. I simply obtained Python and SciPy from the Anaconda distribution (and updated scipy via `conda update`). But it seems that MKL is now used by Anaconda by default. By the way, how (and where) can I set the parameter `MKL_NUM_THREADS=1`?  (I am quite unfamiliar with these technical details...)

Results of `LA.lapack.ilaver()` on my system is `(3, 7, 0)` but I do not understand what they mean...

**Comment by ilayn** [comment]
3.7.0 is the version of your LAPACK used internally.

**Comment by larsoner** [comment]
>  By the way, how (and where) can I set the parameter MKL_NUM_THREADS=1? (I am quite unfamiliar with these technical details...)

You can set it as an env var before running Python like `MKL_NUM_THREADS=1 python`, or at the very top of your script before importing NumPy or SciPy like:
```
import os
os.environ['MKL_NUM_THREADS'] = 1
import numpy
...
```
If this does not change anything you can also try setting `OMP_NUM_THREADS` but I think they are supposed to do the same thing.

**Comment by Yue-Zhengyuan** [comment]
I forgot to mention that I have installed the Intel Distribution for Python, but I put it in another environment (`idp`) to separate it from the default `base` environment. (I checked through `conda list`, and I find that scipy in the two environment are of different channel, so I think they are indeed separated). 

`MKL_NUM_THREADS=1 python` does not have any effect. 

If I use `os.environ['MKL_NUM_THREADS'] = 1` I will get the following error

```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    os.environ['MKL_NUM_THREADS'] = 1
  File "/Users/zhengyuanyue/anaconda3/lib/python3.7/os.py", line 683, in __setitem__
    value = self.encodevalue(value)
  File "/Users/zhengyuanyue/anaconda3/lib/python3.7/os.py", line 753, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not int
```

**Comment by Yue-Zhengyuan** [comment]
I tried later setting **_compute_uv = False_** then the 'gesvd' method can give the correct singular values. 

Code:
```
import scipy.linalg as LA

mat = np.array([[-1,0], [0,-1-1j]], dtype=complex)
s = LA.svd(mat, full_matrices=False, lapack_driver='gesvd', compute_uv=False)
print(s)
```
Output:
```
[1.41421356 1.        ]
```

Besides, for the gesdd "SVD did not converge" issue, for the matrix given above [matexample.txt](https://github.com/scipy/scipy/files/3055009/matexample.txt), setting **_compute_uv=False_** also works. This is quite strange for me.

About the possible problems related to MKL, I tried Eric's bad matrix examples [bad_avx.npy](https://staff.washington.edu/larsoner/bad_avx.npy), [bad.npy](https://staff.washington.edu/larsoner/bad.npy), but both 'gesdd' and 'gesvd' worked and did not raise "did not converge" error. 

For your reference, I give my numpy MKL configurations here:

Code: 

```
import numpy as np
np.__config__.show()
```

Output:

```
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/zhengyuanyue/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/zhengyuanyue/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/zhengyuanyue/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/zhengyuanyue/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/zhengyuanyue/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/zhengyuanyue/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/zhengyuanyue/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/zhengyuanyue/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/zhengyuanyue/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/zhengyuanyue/anaconda3/include']

```

**Comment by Yue-Zhengyuan** [comment]
I reinstalled the SciPy package without MKL and now the svd function is working correctly. So this issue is indeed related to the MKL library. But I still do not understand why this issue cannot be reproduced on some of my classmates Windows computer, since they have MKL enabled too.

For reference, I give here the way to opt out MKL using Anaconda (2019.03 version): 

1. run command `conda remove mkl mkl-service`

2. run command `python -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose`

NOTE: do not use `condo install` since it seems that `conda` will force you to install SciPy with MKL

My current NumPy configuration (`numpy.show_config()`):

```
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
```

**Comment by larsoner** [comment]
The bug is at the very least CPU hardware dependent based on the test results from various people in the linked Intel issue. I'm not very surprised you could not reproduce in another computer, unless it has an identical CPU and possibly OS / configuration.

**Comment by Yue-Zhengyuan** [comment]
I notice that the path to OpenBLAS used by my current numpy is 
```
library_dirs = ['/usr/local/lib']
```

Which seems like it is using something that comes along with macOS. However, OpenBLAS is not shipped with macOS. So I want to know whether the command
```
python -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose
```
installs a pre-compiled (linking to OpenBLAS) version of the scipy package.

**Comment by ilayn** [comment]
Yes NumPy wheel on PyPi bundles a copy of OpenBLAS if it can't detect any. If you build from the source you can link to whichever you want.

**Comment by matthew-brett** [comment]
Specifically, the wheel always uses its own bundled OpenBLAS.  The path is recorded as `/usr/local/lib` as you see it, because that was the path when the wheel was compiled, but in fact the wheel building process moves the OpenBLAS library into a subdirectory of Numpy, and rewrites the Numpy files accordingly, so it is no longer expecting an OpenBLAS in `/usr/local/lib`.

**Comment by Yue-Zhengyuan** [comment]
I discovered another matrix that can raise "SVD did not converge" error if gesdd is used even if I am using OpenBLAS now.
[bad_matrix.txt](https://github.com/scipy/scipy/files/3063512/bad_matrix.txt)
Matrix dimension (44, 38) (not very large). However, gesvd and gesdd with `compute_uv=False` can both handle it. Could you please try this on your computers?

**Comment by ilayn** [comment]
@Yue-Zhengyuan This is also known. We are simply wrapping the LAPACK routines so you might want to take this to them, here is some more information https://github.com/Reference-LAPACK/lapack/issues/316

**Comment by Yue-Zhengyuan** [comment]
@ilayn The matrix is in fact _**expected**_ (it is produced by some algorithm from physics) to have a singular value spectrum that will drop drastically. Now I know that matrices with vastly different singular values are likely to cause GESDD to fail. Thanks!

**Comment by ilayn** [comment]
What I mean is that if your matrix entries are completely off by order of magnitude for example you have a lot of 1e-18 entries which are practically zero for machine precision they end up confusing the matrix balancing algorithm and causing the ?GESDD driver to get confused. 

I don't have computer access now but if you multiply your matrix by 1e5 or something you will not get any errors (hopefully).

**Comment by Yue-Zhengyuan** [comment]
@ilayn Yes indeed. In fact, I don't need such a big factor; multiplying it by 3 is sufficient. I have already mentioned this phenomenon in my initial comment.
