### ISSUE TITLE
Problem with ks_2samp p-value calculation?

### ISSUE THREAD

**Issue by croth1** [scipy/scipy#10033]
p-values are uniformly distributed between 0 and 1 when the null hypothesis is true.

Here I test this using scipy's ks_2samp test. The docstring says: 

> This is a two-sided test for the null hypothesis that 2 independent
> samples are drawn from the same continuous distribution.

Therefore I ...
 - draw two independent samples `s1` and `s2` of length 1000 each, from the same continuous distribution.
 - calculate a p-value with `ks_2samp`.
 - Use the KS test (again!) to check whether the p-values are likely a sample from the uniform distribution.

This is the p-value distribution I get for the 200k ks_2samp comparisons:
![image](https://user-images.githubusercontent.com/15384900/55736015-cf035200-5a22-11e9-9f50-c12ae24a3cca.png)

With a crazily significant p-value that the ks_2samp p-value distribution is not uniform. Am I overlooking something, or is there a bug somewhere in the p-value calculations?

```
    import matplotlib.pyplot as plt
    from scipy.stats.distributions import norm
    from scipy.stats import ks_2samp
    from scipy.stats import kstest
    from scipy.stats.distributions import uniform
    import numpy as np
    np.random.seed(42)
    
    mu = 12
    sigma = 23
    target_dist = norm(mu, sigma)
    
    N_pvals = 200000
    
    pvals = []
    for i in range(N_pvals):
        s1 = target_dist.rvs(1000)
        s2 = target_dist.rvs(1000)
        _, ks_pval = ks_2samp(s1, s2)
        pvals.append(ks_pval)


    kstest(pvals, uniform.cdf)
    # KstestResult(statistic=0.031679471825802774, pvalue=9.115391786202152e-175)

**Comment by chrisb83** [comment]
Hi,

thanks for reporting this, see #8748 for the one-sample test. 

I wonder if this is due to the small-sample correction used in `stats.ks_2samp`. Could you try the version in mstats (`scipy.mstats.ks_twosamp`) that does not use this correction (see #8977) if you reject again with the same seed (probably even smaller N_pvals will show this effect in case your simulation takes a while)?

**Comment by croth1** [comment]
Ah I think I got it now. The p-value distribution of the ks-test is actually discrete. If you look at the ECDF you can see that everything is actually fine: 
![image](https://user-images.githubusercontent.com/15384900/55751354-bfe1cb80-5a45-11e9-9515-e847bc0dae0f.png)

In the last line I therefore used `kstest(pvals, uniform.cdf)` on a non-continuous variable.

Sorry for the noise.
