### ISSUE TITLE
[feature request] Add Cython Bindings for scipy.special.erfinv?

### ISSUE THREAD

**Issue by jertubiana** [scipy/scipy#10030]
Dear Scipy developers,

I would like to use scipy.special.erfinv in a trivially parallelizable scenario. For most special functions, this can be done using Cython (or Numba) as explained in https://docs.scipy.org/doc/scipy/reference/tutorial/special.html.

However, there is currently no Cython Binding for erfinv. Is there any specific reason for that?Maybe the finite domain of definition [-1,1] is problematic? Any idea on how this could be done?

**Comment by person142** [comment]
Hey @jertubiana, the reason that you can't find `erfinv` in `cython_special` is that it is actually implemented in Python here:

https://github.com/scipy/scipy/blob/master/scipy/special/basic.py#L756

However, it basically just calls `ndtri`, which *is* available in`cython_special`, so you should still be able to get what you want.

**Comment by person142** [comment]
If, in the future, we wanted to make `erfinv` itself is available in `cython_special` then someone just needs to take that simple Python implementation, port it to Cython, and then hook it into the `_generate_pyx.py` machinery.

**Comment by jertubiana** [comment]
Thank you very much! ndtri is indeed enough for my purpose; I will try to build the Cython binding for erfinv and update the post soon.

**Comment by person142** [comment]
p.s. @jertubiana if you want a Numba implementation of `erfinv` you can find one here:

https://github.com/person142/spycial/blob/master/spycial/erfinv.py

**Comment by jertubiana** [comment]
Thank you very much! I will have take a look and compare both approaches.

Best,
Jerome

Le mer. 10 avr. 2019 à 08:33, Josh Wilson <notifications@github.com> a
écrit :

**Comment by rgommers** [comment]
The question is answered, so closing. PR still welcome of course!
