### ISSUE TITLE
[Feature Request] Marginalize over parameters in gaussian_kde

### ISSUE THREAD

**Issue by lzkelley** [scipy/scipy#10049]
`scipy.stats.gaussian_kde` provides excellent tools for performing single- or multi- dimensional KDEs.  With a given guassian_kde instance, it would be nice to be able to calculate properties on a single parameter/dimension, marginalizing over the others, as if a 1D KDE had been constructed.   If this sounds like a useful feature, I'm happy to try to put together a PR.

**Comment by rgommers** [comment]
@lzkelley you're the second person that had this idea recently:) This is already in progress in gh-9932. It would be great if you could review that PR and help get it merged.

**Comment by lzkelley** [comment]
I'm going to close this issue and defer discussion to the other thread: https://github.com/scipy/scipy/pull/9932
