### ISSUE TITLE
Trouble importing scipy.spacial.transform

### ISSUE THREAD

**Issue by HBuenoo** [scipy/scipy#10043]
I do have scipy installed, but when I need it in another package, I cant get over this error, says cant find module from scipy

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-44-1a07added972> in <module>
      4 import astropy.units as u
      5 from astropy.time import Time
----> 6 from gala import coordinates as gc
      7 from astropy.table import QTable, Column

~/anaconda3/lib/python3.7/site-packages/gala-1.0.dev2456-py3.7-linux-x86_64.egg/gala/__init__.py in <module>
     24 if not _ASTROPY_SETUP_:
     25     from . import coordinates
---> 26     from . import dynamics
     27     from . import integrate
     28     from . import potential

~/anaconda3/lib/python3.7/site-packages/gala-1.0.dev2456-py3.7-linux-x86_64.egg/gala/dynamics/__init__.py in <module>
      1 from .core import PhaseSpacePosition, CartesianPhaseSpacePosition
      2 from .orbit import Orbit, CartesianOrbit
----> 3 from .analyticactionangle import *
      4 from .actionangle import *
      5 from .nonlinear import *

~/anaconda3/lib/python3.7/site-packages/gala-1.0.dev2456-py3.7-linux-x86_64.egg/gala/dynamics/analyticactionangle.py in <module>
     11 
     12 # Project
---> 13 from ..potential import (Hamiltonian, PotentialBase,
     14                          IsochronePotential, HarmonicOscillatorPotential)
     15 from ..util import atleast_2d

~/anaconda3/lib/python3.7/site-packages/gala-1.0.dev2456-py3.7-linux-x86_64.egg/gala/potential/__init__.py in <module>
----> 1 from .potential import *
      2 from .hamiltonian import *
      3 from .frame import *
      4 from .scf import SCFPotential

~/anaconda3/lib/python3.7/site-packages/gala-1.0.dev2456-py3.7-linux-x86_64.egg/gala/potential/potential/__init__.py in <module>
----> 1 from .core import *
      2 from .cpotential import *
      3 from .ccompositepotential import *
      4 from .builtin import *
      5 from .io import *

~/anaconda3/lib/python3.7/site-packages/gala-1.0.dev2456-py3.7-linux-x86_64.egg/gala/potential/potential/core.py in <module>
     10 import astropy.units as u
     11 from astropy.utils import isiterable
---> 12 from scipy.spatial.transform import Rotation
     13 
     14 # Project

ModuleNotFoundError: No module named 'scipy.spatial.transform'

**Comment by rgommers** [comment]
`Rotation` was added in the latest release (1.2.0). You didn't say what scipy version you have installed, but most likely you just need to upgrade.

**Comment by HBuenoo** [comment]
wow...that was simple hahah

thank you so much!
