### ISSUE TITLE
[Bug] inconsistent canonical format for coo_matrix

### ISSUE THREAD

**Issue by xtracko** [scipy/scipy#10050]
When creating an instance of `scipy.sparse.coo_matrix` from `numpy.ndarray` the constructor sets the flag `has_canonical_format` to `True` assuming that `numpy.nonzero` return indices in canonical order. But, the canonical order defined in `coo_matrix._sum_duplicates` method is `np.lexsort((row, col))` which sorts primarily by columns.

Also, running manually `sum_dumpicates()` on such matrix has no effect, even though the array is not in canonical order due to the preemptive check of `coo_matrix.has_canonical_format` flag.

The `coo_matrix.__init__` implementation:
https://github.com/scipy/scipy/blob/c3fa90dcfcaef71658744c73578e9e7d915c81e9/scipy/sparse/coo.py#L177-L187

The `coo_matrix._sum_duplicates` implentation:
https://github.com/scipy/scipy/blob/c3fa90dcfcaef71658744c73578e9e7d915c81e9/scipy/sparse/coo.py#L522-L548

### Reproducing code example:
```py
>>> import numpy as np
>>> from scipy.sparse import coo_matrix
>>> a = coo_matrix(np.arange(9).reshape(3,3))
>>> b = a.copy()
>>> b.sum_duplicates()
>>> assert a.has_canonical_format == b.has_canonical_format == True
>>> assert np.array_equal(a.row, b.row)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AssertionError
>>> assert np.array_equal(a.col, b.col)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AssertionError
```

### Scipy/Numpy/Python version information:
```py
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.1 1.16.2 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)
```

**Comment by fuglede** [comment]
The issue also appears during conversion: `dia_matrix.tocoo` and `dok_matrix.to_coo` produce different sortings but both set `has_canonical_format` to `True`.

```python
In [165]: dia_matrix([[1, 2], [3, 4]]).tocoo().row
Out[165]: array([1, 0, 1, 0], dtype=int32)

In [166]: a = dok_matrix([[1, 2], [3, 4]]).tocoo()

In [167]: a.row, a.has_canonical_format
Out[167]: (array([0, 0, 1, 1], dtype=int32), True)

In [168]: a = dia_matrix([[1, 2], [3, 4]]).tocoo()

In [169]: a.row, a.has_canonical_format
Out[169]: (array([1, 0, 1, 0], dtype=int32), True)
```
The latter is particularly interesting as the rows for a single column are in reverse order. Other than that, `sum_duplicates` and `has_canonical_format` are mostly used within the class itself and going through the usages, I couldn't come up with an example where simply swapping `row` and `col` in the `np.lexsort` (which would be what I would have expected it to do) isn't safe.

**Comment by perimosocordiae** [comment]
As of gh-16936, COO's `sum_duplicates()` now does the lexsort in the "correct" order. It also means we now rely on this ordering, so the DIA -> COO conversion that @fuglede demonstrated should definitely _not_ be setting `has_canonical_format=True` anymore. I'll open a PR to fix that shortly.
