### ISSUE TITLE
scipy.ndimage.watershed_ift regression in 1.0.0

### ISSUE THREAD

**Issue by SimonSegerblomRex** [scipy/scipy#10069]
The following line
```
_nd_image.watershed_ift(input, markers, structure, output)
```
in `scipy/ndimage/measurements.py` (`watershed_ift`) produces different result before and after `scipy=1.0.0` with the input attached. I guess this might just be an example of a corner case using bad inputs, but it would be nice to know why the results differ.

### Reproducing code example:
```python
import numpy as np
from scipy.ndimage import watershed_ift

image = np.loadtxt('image.txt', dtype=np.uint16)

markers = np.zeros(image.shape, dtype=np.int16)
markers[0, 0] = 1
markers[image.shape[0] / 2, image.shape[1] / 2] = 2

print("Same input:")
print(hash(image.tostring()))
print(hash(markers.tostring()))

output = watershed_ift(image, markers)

print("Different output:")
print(hash(output.tostring()))

import matplotlib.pyplot as plt
plt.imshow(output, cmap='jet')
plt.show()
```
Inputs:
[image.txt](https://github.com/scipy/scipy/files/3085325/image.txt)

### Scipy/Numpy/Python version information:
Example of "good" output:
```
'0.15.1', '1.15.1', sys.version_info(major=2, minor=7, micro=10, releaselevel='final', serial=0)
```
```
Same input:
2134465424452735359
3894358299218458450
Different output:
-3225594274849803831
```
![output-0 15 1](https://user-images.githubusercontent.com/8997425/56265103-ee684200-60e8-11e9-94da-eafdfb067c14.png)

Example of "bad" output:
```
'1.1.0', '1.12.1', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0)
```
```
Same input:
2134465424452735359
3894358299218458450
Different output:
6558824525946414866
```
![output-1 1 0](https://user-images.githubusercontent.com/8997425/56265104-ee684200-60e8-11e9-905d-1c60e1865c3b.png)

The breaking change seems to have occurred in `scipy=1.0.0`. The result looks just as bad for:
```
1.2.1 1.16.2 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
@SimonSegerblomRex thanks for the report. Any chance you can demonstrate the issue on a self-contained example (i.e. with an array generated by code  rather than needing to load it from an attached file)? That would make confirming the bug and fixing it a lot easier.

**Comment by SimonSegerblomRex** [comment]
> @SimonSegerblomRex thanks for the report. Any chance you can demonstrate the issue on a self-contained example (i.e. with an array generated by code rather than needing to load it from an attached file)? That would make confirming the bug and fixing it a lot easier.

By downsampling the image provided in the original message with
```
image = np.loadtxt('image.txt', dtype=np.uint16)
image = image[::16, ::16]
```
I got this:
```python
import numpy as np
from scipy.ndimage import watershed_ift

image = np.array([
    [1072, 1061, 1072, 1070, 1055, 1060, 1056, 1044, 1053, 1054, 1067, 1075, 1072],
    [1028, 1025, 1021, 1026, 1002, 1018, 1021, 1023, 1030, 1044, 1043, 1035, 1046],
    [1005, 1001, 1004,  916,  527,  525,  582,  729,  890,  967,  982,  979,  987],
    [ 982,  993,  983,  748,  491,  483,  482,  478,  479,  486,  493,  877,  969],
    [ 937,  916,  930,  596,  469,  458,  456,  455,  454,  456,  470,  898,  938],
    [ 906,  903,  927,  508,  450,  437,  433,  435,  431,  440,  452,  874,  877],
    [ 921,  916,  919,  476,  441,  430,  431,  420,  413,  418,  455,  826,  827],
    [ 903,  886,  880,  456,  429,  425,  422,  417,  410,  416,  515,  815,  803],
    [ 872,  863,  860,  788,  641,  499,  439,  423,  414,  412,  662,  802,  841],
    [ 845,  839,  841,  840,  837,  825,  827,  808,  788,  776,  791,  859,  984],
    [ 826,  830,  830,  835,  832,  821,  827,  806,  807,  820,  866, 1034,  512],
    [ 573,  903,  729,  714,  916,  899,  850,  837,  855,  910,  720,  511,  507],
    [ 608,  919,  982,  755, 1013, 1119,  666,  555, 1034,  319,  558,  550,  526]],
    dtype=np.uint16)

markers = np.zeros(image.shape, dtype=np.int16)
markers[0, 0] = 1
markers[image.shape[0] / 2, image.shape[1] / 2] = 2

print("Same input:")
print(hash(image.tostring()))
print(hash(markers.tostring()))

output = watershed_ift(image, markers)
output[output == 1] = 0

print("Different output:")
print(hash(output.tostring()))

import matplotlib.pyplot as plt
plt.imshow(output, cmap='jet')
plt.show()
```
which produces slightly different results in scipy=0.15.1 vs 1.1.0. (Using factor 2, 4, or 8 for the downsampling produces the same result with both versions!)

**Comment by rgommers** [comment]
hmm, it is a little different, but it's not obvious that the current behavior is worse. would be nice to get to the bottom of this, but I don't have time to investigate in detail now.

**Comment by thezoat** [comment]
I also ran into this converting a project from python 2 to 3. It seems there is a bug that prevents watershed_ift from visiting all nodes, leaving some pixels at 0 (no label) after the watershed.

Any help with this issue would be appreciated!

Minimal example based on the one above:

```
image = np.array([
    [1072, 1056],
    [ 921,  431]],
    dtype=np.uint16)

markers = np.zeros(image.shape, dtype=np.int16)
markers[0, 0] = 1

print (image)
print (markers)

output = watershed_ift(image, markers)

print(output)
```

This example has a single marker, so I would expect the algo to assign that marker to all pixels. With Python 2 that is what I get, but with Python 3 it is not. 

Results with python 2.7.10 (scipy 0.15.1):

```
[[1072 1056]
 [ 921  431]]

[[1 0]
 [0 0]]

[[1 1]
 [1 1]]
```

Results with python 3.7 (scipy 1.1.0):

```
[[1072 1056]
 [ 921  431]]

[[1 0]
 [0 0]]

[[1 1]
 [0 0]]
```

**Comment by SimonSegerblomRex** [comment]
> hmm, it is a little different, but it's not obvious that the current behavior is worse.

Here's a more obvious example:
![watershed](https://user-images.githubusercontent.com/8997425/92955213-0e7a6d00-f465-11ea-86ef-8ec44522b85a.png)
(Fixed version to the left.)
