### ISSUE TITLE
dual_annealing import error

### ISSUE THREAD

**Issue by Lisenndre** [scipy/scipy#10060]
Hi all, 
I got anaconda 3.7 and trying to import dual_annealing and getting attribure error:
module 'scipy.optimize' has no attribute 'dual_annealing'. 
It works with the other algorithms (differential_evolution, Nelder-Mead...), but I really prefer this one in my case, so are there any options to handle it?

**Comment by rgommers** [comment]
`dual_annealing` was introduced in scipy 1.2.0. you can check what version you have installed via `$ conda list scipy` or `>>> scipy.__version__`. You probably just have to upgrade

**Comment by rgommers** [comment]
I'm closing this because it's not a bug in scipy. Feel free to ask more questions of course.
