### ISSUE TITLE
Consider adding support for LU decomposition without pivoting 

### ISSUE THREAD

**Issue by GiilDe** [scipy/scipy#10063]
There is no option to LU decompose a matrix without pivoting at all, this is sometimes demanded in academic context, consider adding such option.

**Comment by ev-br** [comment]
ISTM this would have a very limited use. If all you need is a quick exercise (introductory teaching, is it?), then it's not hard to DIY:


```
# generate a full rank matrix
from scipy.stats import ortho_group  
N = 7
np.random.seed(1234)
a = ortho_group.rvs(N) @ ortho_group.rvs(N)

# naive LU decomp
u = a.copy()                                               
L = np.eye(N)
for j in range(N-1):
    lam = np.eye(N)
    gamma = u[j+1:, j] / u[j, j]
    lam[j+1:, j] = -gamma
    u = lam @ u
    
    lam[j+1:, j] = gamma
    L = L @ lam

print(L)
print(u)
print(L@u - a)

```

I'm -1 for adding as a library function.

**Comment by ilayn** [comment]
In addition to its limited use, without pivoting such decomposition might not even exist and it is quite tedious to take care of all the possible corner cases for production code; zero diagonals so on. 

If you only need academic (lately this term is started to mean bad code) use of Gaussian elimination machinery, such code is practically everywhere online (including above). I am also -1 on this.

**Comment by mdhaber** [comment]
If you need sparse LU without pivoting:
https://github.com/scipy/scipy/issues/7700
There is a workaround at the bottom that achieves it.

@ilayn @ev-br I need(ed) it for a `linprog` redundancy removal routine because I already knew that my columns were appropriately ordered

**Comment by ilayn** [comment]
> I need(ed) it for a linprog redundancy removal routine because I already knew that my columns were appropriately ordered

You would get the same result from LU in that case anyways. But I'm not sure how you detect that they are properly ordered. Because that would be a massive speedup had we known that beforehand in the regular LU.

**Comment by mdhaber** [comment]
@ilayn https://www.tandfonline.com/doi/abs/10.1080/10556789508805634

**Comment by ilayn** [comment]
This is a bit more special than what is being discussed though. Basically we have Gaussian elimination vs. a very specific matrix structure (as the paper mentions they are artificial columns with specific entries that cannot have pivot issues)).

**Comment by rgommers** [comment]
It seems we tend to -1 for adding this. The specific `linprog` case is handled now, and for the rest this may not be such a good idea. So let's close the issue. If it still makes sense to do some refactoring so the `linprog` code can depend on `sparse.linalg` code, PR welcome I guess, but it seems clear that that should stay private.
