### ISSUE TITLE
Time evolution with scipy.integrate.solve_ivp continuously leaks memory

### ISSUE THREAD

**Issue by laplacesdemon64** [scipy/scipy#10070]
I am working on a project where I want to evolve a quantum mechanical state vector in time according to Schroedinger's equation. The Hamiltonian is a sparse matrix (in the example below, I chose a random matrix for simplicity).

I noticed that for large, but not insanely huge systems (vector and matrix are on the order of 10 - 100 MB), the function `scipy.integrate.solve_ivp` is continuously leaking memory when evolving the system to late times. This behavior makes the integrator useless for my problem because it will inevitably result in a `MemoryError`. Since I'm not interested in the state at intermediate times, but only at the final evolution time, I would have expected that the memory cost is constant in time because the solution should be overwritten during the evolution.

The old API `scipy.integrate.ode` behaves as expected with constant memory consumption. Therefore, I consider the fact that `scipy.integrate.solve_ivp` is leaking memory a bug, which should be fixed.

### Reproducing code example:
```Python
import numpy as np
from scipy.sparse import coo_matrix, csr_matrix
from scipy.integrate import solve_ivp

np.random.seed(0)

dim = 2000000  # something big
nnz = 3 * dim  # something bigger

# random sparse matrix
rows = np.random.choice(dim, size=nnz)
cols = np.random.choice(dim, size=nnz)
data = np.zeros(nnz, dtype=np.complex)
data.real = np.random.normal(size=nnz)
data.imag = np.random.normal(size=nnz)

h = coo_matrix((data, (rows, cols)), shape=(dim, dim))
h = h.tocsr()
h = h + h.H  # make matrix Hermitian

# RHS of Schroedinger's equation
def fun(t, y):
    return -1j * h.dot(y)

y = np.zeros(dim, dtype=np.complex)
y.real = np.random.normal(size=dim)
y.imag = np.random.normal(size=dim)

tspan = (0.0, 1000.0)  # evolve to late times

print("Solving system...")
# this leaks memory
result = solve_ivp(fun, tspan, y)
print("Done!")
```

### Error message:

```
Solving system...
Killed

$ cat /var/log/syslog
Apr 16 19:17:54 node01 kernel: [439260.323684] [ 2931]  1001  2931  2576965  2460605 19988480        0             0 python
Apr 16 19:17:54 node01 kernel: [439260.323685] Out of memory: Kill process 2931 (python) score 573 or sacrifice child
Apr 16 19:17:54 node01 kernel: [439260.323695] Killed process 2931 (python) total-vm:10307860kB, anon-rss:9842420kB, file-rss:0kB, shmem-rss:0kB
```

### Scipy/Numpy/Python version information:

```
$ python -c "import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)"
1.2.1 1.16.2 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by nmayorov** [comment]
Well, it should not be called "memory leakage", it's just memory consumption according to how the code is supposed to work. And there is no bug here, please take time to study the docstring.

Specifically, look at `t_eval` argument --- it allows you to specify at which times to store the solution and it should solve your problem. You can also consider using `OdeSolver` classes and their `step` method. 

If my explanation is clear, I will close the issue.

**Comment by laplacesdemon64** [comment]
Thank you for your reply!
Indeed, including the `t_eval` argument as
```Python
result = solve_ivp(fun, tspan, y, t_eval=[tspan[1]])
```
solves the memory consumption problem of the above code.

However, it does not solve my original problem. Here is what I've been trying to do in the first place. Instead of running the time evolution until `tspan[1]` all the way, I want to evaluate the solution at intermediate times:
```Python
import numpy as np
from scipy.sparse import coo_matrix, csr_matrix
from scipy.integrate import solve_ivp

np.random.seed(0)

dim = 2000000  # something big
nnz = 3 * dim  # something bigger

# random sparse matrix
rows = np.random.choice(dim, size=nnz)
cols = np.random.choice(dim, size=nnz)
data = np.zeros(nnz, dtype=np.complex)
data.real = np.random.normal(size=nnz)
data.imag = np.random.normal(size=nnz)

h = coo_matrix((data, (rows, cols)), shape=(dim, dim))
h = h.tocsr()
h = h + h.H  # make matrix Hermitian

# RHS of Schroedinger's equation
def fun(t, y):
    return -1j * h.dot(y)

y = np.zeros(dim, dtype=np.complex)
y.real = np.random.normal(size=dim)
y.imag = np.random.normal(size=dim)

tspan = (0.0, 100.0)  # evolve to late times

def evaluate(t, y):
    print("Evaluate solution at time t = {:.2f}".format(t))

t_eval = np.linspace(tspan[0], tspan[1], 1000)  # evaluate at intermediate times

print("Solving system...")
t = tspan[0]
for ts in t_eval:
    if ts != t:
        result = solve_ivp(fun, (t, ts), y, t_eval=[ts])
        y = result.y[:, -1]
        t = result.t[-1]
    evaluate(t, y)
print("Done!")
```
This code suffers from a similar memory consumption issue and I thought I would have tracked the problem down to SciPy with my original example (I omitted the `t_eval`-argument for brevity, which I shouldn't have).

It seems to me that in the second example, garbage collection is not working properly. Do you see where the problem with the above code is and if it might still be attributed to SciPy?

**Comment by nmayorov** [comment]
Hmm, I confirm that the code you posted actually creates memory build-up which causes problems for OS eventually. For some reasons the memory is not being freed. I suspect that it might something to do with sparse matrices. 

I will try to investigate, but not sure if I can actually determine what is going on. Perhaps we need someone else to look.

**Comment by nmayorov** [comment]
So, I figured that it comes down to Python garbage collector. After I had added `gc.collect()` after the line with `evaluate` the memory build-up disappeared.

Here is the plot created by `memory_profiler`:

![solve_ipv_memory](https://user-images.githubusercontent.com/7074023/56389578-93426680-6232-11e9-8b1c-dd6bab8506d7.png)

As for Python gc, I don't know why it is working like this. But I think we can conclude that everything is fine on scipy's side.

Please check whether manual `gc.collect()` helps.

**Comment by laplacesdemon64** [comment]
Thank you, invoking garbage collection manually, as you suggested, indeed prevents the memory build-up. For my application, this workaround should be sufficient.

However, I am curious why the problem appears in the first place. Do you think it might be worthwhile reporting this issue elsewhere?

**Comment by MatthewFlamm** [comment]
I'm not convinced the latest implementation is actually causing a long-term memory build-up.  I didn't test the exact implementation since I'm impatient but set tspan = (0.0, 0.1) and only generated 300 intermediate solutions.  Memory usage does build up temporarily, but then Python does a garbage collection and memory use goes back down.  Manually garbage collecting after each iteration in the loop simply eliminates the slow-build prior to collection.

![image](https://user-images.githubusercontent.com/39341281/56614623-681b9680-65e7-11e9-8474-174e4206fd75.png)


It is entirely possible that for large memory consumption that you might run out of memory before the garbage collection occurs.  In that case, the solution by @nmayorov works.

**Comment by nmayorov** [comment]
I think this was discussed enough, closing.
