### ISSUE TITLE
Define __round__ for sparse matrices

### ISSUE THREAD

**Issue by MichalKononenko** [scipy/scipy#10073]
My issue is about using ``assertAlmostEqual`` with sparse matrices. [``assertAlmostEqual``](https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertAlmostEqual) requires the types being compared to implement [``__round__``](https://docs.python.org/3/library/functions.html#round). Defining this, possibly by calling [``numpy.round``](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.round_.html) on the ``data`` attribute, following [this thread](https://stackoverflow.com/questions/51476588/how-do-round-off-the-elements-of-scipy-sparse-csr-matrix-to-2-decimal-places), would be useful.

### Reproducing code example:

```python
from scipy.sparse import csr_matrix

a = csr_matrix((3, 4))

round(a)
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: type csr_matrix doesn't define __round__ method
```

### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)

1.1.0 1.14.3 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', s
erial=0)
```

**Comment by perimosocordiae** [comment]
Seems like a good feature to add. It would look very similar to the existing `__abs__` implementation: https://github.com/scipy/scipy/blob/f992ba979227044fbd11da648d339c8026de91a1/scipy/sparse/data.py#L37
