### ISSUE TITLE
How to return mean and variance of a distribution estimated via KernelDensity of sklearn, in python?

### ISSUE THREAD

**Issue by suzyi** [scipy/scipy#10082]
My issue is, how to return mean value and variance of the probability distribution function "kde" estimated via KernelDensity?

### code:

```
import numpy as np
from scipy.stats import norm
from sklearn.neighbors import KernelDensity

N = 100
np.random.seed(1)
X = np.concatenate((np.random.normal(0, 1, int(0.3 * N)),np.random.normal(5, 1, int(0.7 * N))))[:, np.newaxis]

X_plot = np.linspace(-5, 10, 1000)[:, np.newaxis]
kde = KernelDensity(kernel='gaussian', bandwidth=0.5).fit(X)
```

**Comment by ilayn** [comment]
Hi @suzyi For such questions best places are Stackoverflow,  Cross Validated, and the resources given in https://scikit-learn.org/stable/faq.html#what-s-the-best-way-to-get-help-on-scikit-learn-usage or on various reddit channels.

GitHub repos are reserved for issues and fixes about the code but not how to use them.
