### ISSUE TITLE
Add literature reference for circstd (and circvar?)

### ISSUE THREAD

**Issue by JoKeyser** [scipy/scipy#10096]
I'm trying to figure out what reference to cite, should I use Scipy's `circstd()` function. Unfortunately, no reference is currently given, which renders it unusable for me to use in research.

As far as I could find, the closest formulation of the [current implementation  of `circstd`](https://github.com/scipy/scipy/blob/c42462ab9c697d3e14a7cc232b967c50886438a9/scipy/stats/morestats.py#L3281) is Mardia (1972). Although it's not a literal translation into Python, I think it is equivalent, and the only source I found that *scales* the result according to the range of input values. (I can unpack this in detail, if somebody wants me to; note that e.g. Zar (2010) omits the scaling, although referring to Mardia, weirdly enough).

While I'm trying to focus on the circular standard deviation here, note that if `circstd()` was indeed based on Mardia, a secondary issue might arise regarding `circvar()`: The [current implementation of `circvar`](https://github.com/scipy/scipy/blob/c42462ab9c697d3e14a7cc232b967c50886438a9/scipy/stats/morestats.py#L3239) is a scaling of `2 * log(1/R)`, which is *inconsistent* with both Mardia and Zar (who define it as `1 - R`), and further authors (and thus software packages), as pointed out in https://github.com/scipy/scipy/pull/5747.

@teoliphant, the current implementation of both functions goes back to your PR https://github.com/scipy/scipy/pull/140, maybe you remember the reference you based them on?

References  
Mardia, K. V. (1972). *Statistics of directional data (Z. W. Birnbaum & E. Lukacs, Eds.)*. London: Academic Press.  
Zar, J. H. (2010). *Biostatistical analysis (5. ed).* Upper Saddle River, NJ: Prentice Hall.

**Comment by rgommers** [comment]
IIRC @josef-pkt investigated the circular statistics functions in detail, hopefully he can comment.

**Comment by mdhaber** [comment]
@josef-pkt do you know what reference should be cited in `circstd` and `circvar`? If you can point me in the right direction, i can add it.

**Comment by rkern** [comment]
[Moving discussion back here.](https://github.com/scipy/scipy/issues/13457#issuecomment-770141005)

@mdhaber 
> Do you think it is something we will be able to resolve without the original author's answer, a lot of research comparing algorithms, or a rewrite? I have been wondering lately what to do with old issues that aren't really actionable (besides letting them sit indefinitely - and maybe that's the right thing to do?).

As I said, I think `circvar` is just wrong. I'm willing to bet that no-one has a reference to the contrary.

The question then is where to put the correct implementation, if you feel like you want to have one. I'm personally happy with just [putting it back in](https://github.com/scipy/scipy/pull/140/files#diff-2234ce15dc46f3d7cf770fe99c2dc75ef5594828f0f0422e1aea8a78d3e161acL1372) because that's how we "fixed it" the last time, but I am not a user of these functions and won't be affected by the change.

**Comment by mdhaber** [comment]
I also have no experience with these functions. It sounds like this is a complex issue, if we're considering reversing "fixes", so maybe I'll leave this to someone with particular interest. Thanks @rkern!

**Comment by mdhaber** [comment]
@JoKeyser I checked the code for `circstd` against Mardia 1972. The definition of `circstd`, including scaling based on `(high-low)/2/pi`, looks equivalent to me. I'll add it as a reference.

**Comment by JoKeyser** [comment]
@mdhaber , great to hear, I think this is progress in the right direction.
The secondary issue about `circvar()` can then be adressed elsewhere, e.g. #5747.
I think many users would expect consistency between the `circstd()` and `circvar()` functions.

**Comment by mdhaber** [comment]
I plan to address that, too. 

> I think many users would expect consistency between the `circstd()` and `circvar()` functions.

In this context, I've to seen the word "consistent" used to mean "related by a square root". That is not what you mean, though, right? I planned to do `1-R` in `circvar` if the mailing list is OK with the sudden backyard incompatibly. Nobody has been able to find a reference for the current definition.

**Comment by JoKeyser** [comment]
> In this context, I've to seen the word "consistent" used to mean "related by a square root". That is not what you mean, though, right? I planned to do `1-R` in `circvar` if the mailing list is OK with the sudden backward incompatibly. Nobody has been able to find a reference for the current definition.

Sorry for the imprecision. Indeed, with "consistent" I mean "as defined in literature that defines both functions". The `circvar()` definition `1-R` is consistent in that sense.

I think for research contexts, the grounding of implementations in the literature is much more important than (relatively temporary) backwards compatibility. I hope the mailing list agrees.
