### ISSUE TITLE
document how to run tests in parallel

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#10101]
The full test suite takes a long time, and running tests in parallel is very handy but completely undocumented. The way to do it:

- first install `pytest-xdist`
- then run one of
```
python runtests.py -- -n 4  # for 4 CPUs
```
or
```
pytest -n 4   # add --pyargs scipy for testing an installed scipy
```
For the first option, `--` means end of parameters (`-n` option goes to pytest not runtests.py, for the latter it would mean `--no-build`).

**Comment by mdhaber** [comment]
I can do this when I get to the NumFOCUS grant work.

**Comment by pvanmulbregt** [comment]
Does this Issue mean that `python runtests.py --parallel 4` doesn't actually run the tests in parallel?

**Comment by rgommers** [comment]
No it only builds in parallel. I'd be fine with changing that though - if one can build on 4 cores one can test on 4 cores presumably.

**Comment by rgommers** [comment]
That's actually much nicer than ` -- -n 4`, many people may not even know what `--` does.

**Comment by mdhaber** [comment]
Documented this at the end of:
https://github.com/scipy/scipy/wiki/Running-SciPy-Tests-Locally

**Comment by rgommers** [comment]
> I'm not sure if that closes this issue, though.

Yeah I think we want this in the docs not on the wiki.

> Sounds like we'd like --parallel to test in parallel? Note that right now --parallel doesn't require pytest-xdist; sounds like that would change.

I think that's fine, `pytest-xdist` is easy to install. And doing everything in parallel is what one would expect I think.

> One idea is to separate --parallel-build from --parallel-test.

That's also fine. For me not necessary though, let's see if anyone would like this option.

**Comment by peterbell10** [comment]
>I think that's fine, `pytest-xdist` is easy to install.

One problem with that is that the error message isn't very useful:
```sh
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n
```

Do you object to #10172?

**Comment by rgommers** [comment]
> Do you object to #10172?

No, just had managed to miss that. Will have a closer look now, thanks!

**Comment by mdhaber** [comment]
Updated documentation considering #10172.

**Comment by sethtroisi** [comment]
@rgommers can this be closed after #10172? (If not what would you like to see and I'm happy to improve that documentation)

This is documented in `--help` and [Running SciPy Tests Locally](https://scipy.github.io/devdocs/dev/contributor/runtests.html)
```
$ python runtests.py  -h
usage: runtests.py [OPTIONS] [-- ARGS]

Run tests, building the project first.

Examples::

    $ python runtests.py
    $ python runtests.py -s optimize

... (~50 lines) ...
  --parallel PARALLEL, -j PARALLEL
                        Number of parallel jobs for build and testing
```

**Comment by rgommers** [comment]
One other thing that would be useful is to put the option into the `scipy.test` docstring, or better adding a `parallel` keyword there. The invokation now is hard to get right: `scipy.test(extra_argv=['-n2'])`.

I personally use `runtests.py` rarely, and it doesn't help at all when running tests on installed scipy versions.

**Comment by peterbell10** [comment]
#10172 builds on `PytestTester` which is also what `scipy.test` uses. So, in actual fact you can already do `scipy.test(parallel=4)`.

**Comment by rgommers** [comment]
I have no idea how I managed to overlook that, thanks @peterbell10. 

We're all good here then, closing.
