### ISSUE TITLE
scipy.stats.binned_statistic_dd sample and values dims mismatch

### ISSUE THREAD

**Issue by Mulan-94** [scipy/scipy#10113]
Hi, I'm getting this error
```
AttributeError: The number of `values` elements must match the length of each `sample` dimension.
```
while using `binned_statistic_2d` function as in  this example
```
import numpy as np
from scipy import stats

data  = np.random.randn(1000, 119)
stats.binned_statistic_dd(data, data, statistic='mean', bins=(2, 2, 1))
```
I took a small peak at the code and noticed that the dimensions for the `values` and `sample` are stored in values that are reversed i.e
https://github.com/scipy/scipy/blob/b4bfa9de3e838122d31722194dc273fffeabadf0/scipy/stats/_binned_statistic.py#L472
and
https://github.com/scipy/scipy/blob/b4bfa9de3e838122d31722194dc273fffeabadf0/scipy/stats/_binned_statistic.py#L483
while this is being done
https://github.com/scipy/scipy/blob/b4bfa9de3e838122d31722194dc273fffeabadf0/scipy/stats/_binned_statistic.py#L486
Could this be a bug ?
Also is it possible to have an example for this function included in the docs? There seems to be none.
Thanks

**Comment by rgommers** [comment]
This is not a bug. The first argument is coordinates at which to sample, documented as `(N, D)` - numbers of elements, number of dimensions. You're asking for a 119-dimensional histogram here.

This works:
```
data = np.random.randn(1000, 3)
stats.binned_statistic_dd(data, np.arange(1000), statistic='mean')
```

That said, the documentation is indeed pretty confusing, and this needs a good example. For now look at the example in `binned_statistic_2d`.

**Comment by Mulan-94** [comment]
@rgommers thanks! this works

**Comment by rgommers** [comment]
fixed in gh-10392, thanks all
