### ISSUE TITLE
Documentation of return value of scipy.special.comb is not accurate

### ISSUE THREAD

**Issue by katastrofa999** [scipy/scipy#10117]
https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.comb.html#scipy.special.comb says: 

> If k > N, N < 0, or k < 0, then a 0 is returned.

This is not fully accurate.

```
In [12]: scipy.special.comb(N=2, k=5, repetition=True)
Out[12]: 6.0
```

6 is the correct result when calculating the number of combinations WITH repetitions.

**Comment by ilayn** [comment]
I am not sure but I think the first two conditions need to be satisfied together. Nevertheless indeed this can be clarified better.

**Comment by ilayn** [comment]
The relevant condition is here.

https://github.com/scipy/scipy/blob/v1.2.1/scipy/special/_comb.pyx#L20

**Comment by katastrofa999** [comment]
See https://github.com/scipy/scipy/blob/v1.2.1/scipy/special/basic.py#L1937

`_comb_int` is only called for `repetitions=False`.

**Comment by ilayn** [comment]
if repetition is true comb is recalled with exact and that branch goes into the pyx file.

**Comment by katastrofa999** [comment]
Yes, but the recursive called is with a new value for `N`, equal to `N + k - 1`. The documentation should refer to the value of `N` supplied by the user.

**Comment by WarrenWeckesser** [comment]
@katastrofa999, thanks for reporting this.

It looks like when the `repetition` argument was added in https://github.com/scipy/scipy/pull/3097, the docstring wasn't updated to reflect the behavior when `repitition=True`.

**Comment by rgommers** [comment]
fixed in gh-10142
