### ISSUE TITLE
Why does scipy.stats.ncx2.cdf return nan if noncentrality parameter is zero?

### ISSUE THREAD

**Issue by rhstanton** [scipy/scipy#10120]
If I try to calculate a noncentral chi-square cdf with a noncentrality parameter of zero, I get a nan returned. A non-centrality parameter of zero yields a perfectly well-defined (central) chi-squared distribution, so why not just return a value? I.e., implement internally the test that I currently have to perform:

c = ncx2.cdf(x, df, nonCent) if nonCent > 0 else chi2.cdf(x, df)

**Comment by WarrenWeckesser** [comment]
@rhstanton, thanks for reporting this.

I agree, `ncx2` should handle `nc=0`.

**Comment by ev-br** [comment]
Duplicate of https://github.com/scipy/scipy/issues/5441

**Comment by sethtroisi** [comment]
Fixed by https://github.com/numpy/numpy/pull/6613 (also a duplicate)
