### ISSUE TITLE
inaccurate std implementation in binned_statistic

### ISSUE THREAD

**Issue by tukiains** [scipy/scipy#10126]
stats/_binned_statistic_dd.py uses numerically unstable method for calculating standard deviation:
```
flatsum = np.bincount(binnumbers, values[vv])
flatsum2 = np.bincount(binnumbers, values[vv] ** 2)
result[vv, a] = np.sqrt(flatsum2[a] / flatcount[a] -
                        (flatsum[a] / flatcount[a]) ** 2)
```
If the input data contains large numbers, the squared numbers in the subtraction are very large. As the result precision can be lost - a well known problem in numerical computing.

The effect can be shown by increasing the input data values in the unit tests, for example:
```
cls.v = np.random.random(100) + 1e4
```
instead of the default
```
cls.v = np.random.random(100)
```
and all std-related unit tests will fail.

A better implementation would first calculate the means of the bins and then square (data-mean). Another safe option is just to use np.std but this could be slow.

**Comment by rlucas7** [comment]
I just looked at this on my dev box and not sure the example illustrates the issue:

```
(scipy-dev) Lucass-MacBook:stats rlucas$ python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.stats as ss
>>> import numpy as np
>>> cls = np.random.random(100) + 1e4
>>> np.std(cls)
0.2854385260083998
>>> flatsum = np.sum(cls)
>>> flatsum
1000055.4102408785
>>> flatsum2 = np.sum(cls**2)
>>> flatsum
1000055.4102408785
>>> flatsum2
10001108243.668032
>>> flatcount=len(cls)
>>> np.sqrt(flatsum2 / flatcount - (flatsum / flatcount) ** 2)
0.285438502420829
>>> np.sqrt(flatsum2 / flatcount - (flatsum / flatcount) ** 2) - np.std(cls)
-2.3587570785466028e-08
```

**Comment by rlucas7** [comment]
looks like `numpy.std` has something like the Welform algorithm (accounting for large numbers) built in:
https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/calculation.c#L360-L513

I'll look a little closer at the supported uses for the `binned_statistic` method and see if the numpy method can solve the problem.

**Comment by pvanmulbregt** [comment]
Welford's algorithm appears to be an online algorithm used when computing the variance in a single pass.  Here the data is being traversed twice already, so the simplest approach may just be
to first subtract the mean before squaring.  Continuing the example from https://github.com/scipy/scipy/issues/10126#issuecomment-489867040

```
flatcount = len(cls)
flatsum = np.sum(cls)
flatsum2 = np.sum((cls-flatsum/flatcount)**2)
std = np.sqrt(flatsum2a/flatcount)
```

**Comment by rlucas7** [comment]
@pvanmulbregt  that is a good idea on the way to proceed, I will write the unit test with the example above and try the 2 pass approach.  What precisely constitutes Welford and what constitutes something else is fuzzy to mean.

**Comment by rlucas7** [comment]
Looked into this over the weekend. There is a quick workaround, use a callable rather than the string literal `'std'` as the argument. If you use a callable that does the standard deviation in a numerically stable way, i.e. `numpy.std()` will work fine.

**Comment by rlucas7** [comment]
I wont be able to look at this again until Thursday this week at the earliest. Writing my notes here:

The function call: 

https://github.com/scipy/scipy/blob/master/scipy/stats/_binned_statistic.py#L17

ultimately calls: 
https://github.com/scipy/scipy/blob/master/scipy/stats/_binned_statistic.py#L180-L181

which calls:

https://github.com/scipy/scipy/blob/master/scipy/stats/_binned_statistic.py#L358

i.e. the `binned_statistic_dd` definition. The `binned_statistic_dd` method contains logic to construct the bins (something I'm still working to understand) and then executes the statistical calculation on the data in each bin (in this case calculates sums and sums of squares). 

The offending code is here:
https://github.com/scipy/scipy/blob/master/scipy/stats/_binned_statistic.py#L566-L569

but a change isn't quite as simple as adding in a mean as a difference (I tried that and there are some broadcasting issues). Will pick this back up after Thursday.
