### ISSUE TITLE
A little spelling mistake 

### ISSUE THREAD

**Issue by XtremeGood** [scipy/scipy#10121]
My issue is about ...
Docs
https://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html

Just above 
Trust-Region Newton-Conjugate-Gradient Algorithm (method='trust-ncg')
"the work ill-conditioned"
### Reproducing code example:

```
Sample code to reproduce the problem
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

**Comment by XtremeGood** [comment]
I can fix it if you want since I know a little bit of web dev. But I don't know where is the HTML code located.

**Comment by ilayn** [comment]
@XtremeGood Thanks for the offer. You are of course welcome to fix it. The way to fix it is to fork the project make a separate branch and fix it in this document

https://github.com/scipy/scipy/blob/master/doc/source/tutorial/optimize.rst

**Comment by ev-br** [comment]
Fixed in https://github.com/scipy/scipy/pull/10176, closing.
Thanks for reporting it @XtremeGood
