### ISSUE TITLE
Typo in documentation for scipy.linalg.solve_discrete_are

### ISSUE THREAD

**Issue by billtubbs** [scipy/scipy#10123]
There appears to be a typo on the [documentation page for `scipy.linalg.solve_discrete_are`](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.linalg.solve_discrete_are.html).

### Current text:
> Solves the disctrete algebraic Riccati equation...

### Expected text:

> Solves the discrete algebraic Riccati equation...

**Comment by WarrenWeckesser** [comment]
@billtubbs, thanks for reporting the issue.  You are looking at documentation for SciPy version 0.14.0.  That mistake in the documentation was fixed in 2015.  You can find the documentation for the latest released version (1.2.1) at https://docs.scipy.org/doc/scipy/reference/

**Comment by billtubbs** [comment]
Ah right sorry.  Didn’t check where google sent me...
