### ISSUE TITLE
gausshyper distribution accepts invalid parameters

### ISSUE THREAD

**Issue by chrisb83** [scipy/scipy#10134]
gausshyper distribution accepts invalid parameters:

```
import numpy as np
from scipy Import stats

x = np.linspace(0, 0.5, 10)
stats.gausshyper(1, 1, -1, -5).pdf(x)
array([-0.66666667, -0.48148148, -0.2962963 , -0.11111111,  0.07407407,
        0.25925926,  0.44444444,  0.62962963,  0.81481481,  1.        ])
```

Current `_argcheck` method is:
```
def _argcheck(self, a, b, c, z):
        return (a > 0) & (b > 0) & (c == c) & (z == z)
```
Look like the last parameter z needs to be in (-1, 1) as it enters `special.hyp2f1`. Not sure about `c`

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gausshyper.html

### Scipy/Numpy/Python version information:

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.1 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
```

**Comment by kaushik-p9** [comment]
@chrisb83 parameter 'z' corresponds to kurtosis which can take any value in the range [1, infinity). Please correct me if I'm wrong.

**Comment by kaushik-p9** [comment]
@chrisb83 do you suggest that we add an extra condition (z < 1 and z > -1)? 
Can I submit a PR if that is the case?

**Comment by chrisb83** [comment]
I would first like to clarify which values are admissible. Maybe you know a reference that uses the distribution? Then one can update _argcheck.

**Comment by lhilt** [comment]
Looking at the introduction of [this reference](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/F70C844CD9055E401B57EA833ED844E6/S1446788712000353a.pdf/matrixvariate_gauss_hypergeometric_distribution.pdf) on the Gauss hypergeometric distribution, it seems `c` is any real number and `z > -1`. I haven't had any luck finding other refs to confirm this.

As for `special.hyp2f1`, the series definition applies only to `|z| < 1` but the function is defined on all complex `z` by analytic continuation.

**Comment by pvanmulbregt** [comment]
`gausshyper` first appeared as a SciPy class in 2002, though the functionality may have existed before that.

The distribution itself appears to have been introduced in `Armero, C., and M. J. Bayarri. "Prior Assessments for Prediction in Queues." Journal of the Royal Statistical Society. Series D (The Statistician) 43, no. 1 (1994): 139-53. doi:10.2307/2348939`.
The range of `z` is not made explicit, but certainly `a>0` and `b>0`. `c` can be any real number --- it is just the exponent of `(1+zx)` appearing in the denominator of the PDF.  `z` needs to be any real greater than  `-1` for the PDF to be defined for `0<=x<=1`.

**Comment by chrisb83** [comment]
Thanks for the references, I will take a look.

**Comment by mdhaber** [comment]
@chrisb83 I wondered if you had a chance to check the references? 

The reference from @lhilt does state:
![image](https://user-images.githubusercontent.com/6570539/100279072-b78c1c00-2f1a-11eb-8438-1b609732ef5b.png)

and the same author gives the same information in [another paper](http://www.scielo.org.co/scielo.php?script=sci_arttext&pid=S1794-91652011000200002).

Another author mentions the case z>=1 (pg 17 [here](https://idp.springer.com/authorize/casa?redirect_uri=https://link.springer.com/content/pdf/10.1007/BF02717169.pdf&casa_token=vUNltFEkFa8AAAAA:GQzme8vLh-_0NoLQaq5zhUCf_FOSSuX_RJxEYXEAYT5kbd_3FYfK6-W11TAQTyL4rXjhllcq1mNH-fozSg).)

**Comment by chrisb83** [comment]
I had a look a while ago, z > -1 should be correct. I think one should not allow the edge case z = -1 since the pdf will be 
`C * x**(a-1) * (1-x)**(b-c-1)`, i.e. a beta density. This is only integrable if a > 0 and b - c > 0, so we get another condition to check. Even if b > c, we just get a beta distribution and there is no need to cover this special case here.

**Comment by mdhaber** [comment]
OK, I can add this condition. I'll ping you as a reviewer?
