### ISSUE TITLE
Docs: Description of nnz attribute of sparse.csc_matrix misleading

### ISSUE THREAD

**Issue by SorteKanin** [scipy/scipy#10132]
Hello

On [the docs page for the sparse.csc_matrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html), the nnz attribute is described as:

"Number of stored values, including explicit zeros."

However, [the source](https://github.com/scipy/scipy/blob/v1.2.1/scipy/sparse/csc.py) describes it as:

"Number of nonzero elements"

These are clearly contradictory. The behaviour seems to be in line with the source description, indicating that the documentation is misleading. Perhaps the docs description meant "excluding" instead of "including"?

**Comment by spaceman-codes** [comment]
I can fix this to better reflect the source, however I am not sure how to go about actually editing the document.

**Comment by jaimefrio** [comment]
It is the documentation, not the source, that is correct, e.g.:

```
>>> from scipy import sparse
>>> matrix = sparse.csc_matrix(([0.0, 0.0], ([1, 2], [3, 4])), shape=(5, 5))
>>> matrix.nnz
2
>>> matrix.toarray()
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])
```

**Comment by perimosocordiae** [comment]
Fixed by gh-10141
