### ISSUE TITLE
Kuramoto oscillators with real parameter coupling c not working

### ISSUE THREAD

**Issue by erik-stormy** [scipy/scipy#10147]
I tried code of Kuramotos oscillators from paper "Efficiently and easily integrating differential equations with JiTCODE, JiTCDDE, and JiTCSDE" and it worked quite well. 
Though when I turned parameter c=3 to any real values "Generating, compiling, and loading C code." takes much time (it never get to end, I let it say 2 minutes). At least some other integer values of c (20, 0) works fast (few seconds). Though, when I plot them, solutions looked rather similar, as c have no effect on result.
I am noob in python (using 2.7.12) also in jitcode, so my mistake can be really silly.

### Reproducing code example:

```
# -- coding: utf-8 --

print 'JiTCODE: Kuramoto, NETWORK'
n = 50 # 
cas = 2001

# !! PROBLEM!!
c = 3.2
q = 0.2

from numpy.random import choice
A = choice( [1,0], size=(n,n), p=[q,1-q] )

from numpy.random import uniform
omega = uniform(-0.5,0.5,n)
omega.sort()
from jitcode import y
from symengine import sin

def kuramotos_f():
   for i in range(n):
      coupling_sum = sum( 
         sin(y(j)-y(i)) 
         for j in range(n) 
         if A[j,i]
         )
      yield omega[i] + c/(n-1)*coupling_sum

from jitcode import jitcode

I = jitcode(kuramotos_f, n=n)
I.set_integrator("dopri5", atol=1e-6, rtol=0)
   
from numpy import pi
initial_state = uniform(0,2*pi,n)
I.set_initial_value(initial_state,time=0.0)
times = range(0, cas)

for time in times:
   print(I.integrate(time) % (2*pi) )

```

### Scipy/Numpy/Python version information:
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
('1.1.0', '1.14.5', sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0))

**Comment by ilayn** [comment]
Hi @erik-stormy This looks like it is related to jitcode but not scipy. You might want to report this to [`jitcode` repository](https://github.com/neurophysik/jitcode)

**Comment by erik-stormy** [comment]
Thank you, I thought I wrote to jitcode... You can probably delete it. I post it to jitcode now.
