### ISSUE TITLE
NumFOCUS donation link

### ISSUE THREAD

**Issue by lisamartin72** [scipy/scipy#10144]
My issue is about ...

### Reproducing code example:

```
Sample code to reproduce the problem
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

**Comment by lisamartin72** [comment]
Here is the new donate link for you from NumFOCUS, as requested. 
Have a great day!

https://numfocus.salsalabs.org/donate-to-scipy

**Comment by rgommers** [comment]
Thanks @lisamartin72. I've updated the button in https://github.com/scipy/scipy.org/pull/293. Will close this; the change should be live in a day or so.
