### ISSUE TITLE
Excessive RAMusage for matvec

### ISSUE THREAD

**Issue by TomDeWeer** [scipy/scipy#10163]
Hi all,

I'm trying to compute a matrix vector product of a sparse matrix (see dAiRdb.npz) and a vector (see lambdai.npz). My matrix has ~6.5 billion rows but it's size is only ~100MB. However, when running 
>> dAiRdb.dot(lambdai)

The RAM usage goes up to over 30GB before crashing with MemoryError: std::bad_alloc. I debugged and it's due to the C routines matmat_pass1 and matmat_pass2 routines. Do these routines convert to dense format? Or what's wrong with them?

Kind regards,
Tom
[mats.zip](https://github.com/scipy/scipy/files/3165746/mats.zip)

**Comment by pv** [comment]
CSC format multiplication needs O(n_rows) memory. That's 30GB+ for your matrix.

**Comment by TomDeWeer** [comment]
That's too bad, because converting to csr also costs 30GB+. I have split the matrix up in parts for now, which works reasonably well. I still feel like there should exist a more memory efficient way though.
