### ISSUE TITLE
SciPy 1.3.0rc2 Release Note Edits

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#10160]
@tylerjereddy suggested opening an issue for release note edits.

For addition to "Backwards incompatible changes":

`scipy.optimize` changes
- ----------------------

The default method for `linprog` is now `'interior-point'`. The method's robustness and speed come at cost: solutions may not be accurate to machine precision or correspond with a vertex of the polytope defined by the constraints. To revert to the original simplex method, include the argument `method='simplex'`.

**Comment by tylerjereddy** [comment]
Thanks Matt -- a pure release note edit should be safe to do when I'm preparing `1.3.0` "final" in the coming days.

**Comment by tylerjereddy** [comment]
I guess merges to maintenance branches with "Fixes" directives don't close open issues automatically. I can see why it might be designed that way, but anyway this is done now.
