### ISSUE TITLE
str+bytes concatenation error in test_lapack.py

### ISSUE THREAD

**Issue by dhomeier** [scipy/scipy#10179]
Running the full tests including all marked `xslow` on 1.2.1 (and 1.3.0rc2) on Python 3 (Mac OS X 12.7) fails due to adding bytes to a string in the `test_sgesdd_lwork_bug_workaround`  message:
```
SCIPY_XSLOW=1 python3.7 -c "import scipy, sys; scipy.test(extra_argv=['-v', '-k test_sgesdd'])"
```
### 
```
    @pytest.mark.xslow
    def test_sgesdd_lwork_bug_workaround():
        # Test that SGESDD lwork is sufficiently large for LAPACK.
        #
        # This checks that workaround around an apparent LAPACK bug
        # actually works. cf. gh-5401
        #
        # xslow: requires 1GB+ of memory
    
        p = subprocess.Popen([sys.executable, '-c',
                              'import numpy as np; '
                              'from scipy.linalg import svd; '
                              'a = np.zeros([9537, 9537], dtype=np.float32); '
                              'svd(a)'],
                             stdout=subprocess.PIPE,
                             stderr=subprocess.STDOUT)
    
        # Check if it an error occurred within 5 sec; the computation can
        # take substantially longer, and we will not wait for it to finish
        for j in range(50):
            time.sleep(0.1)
            if p.poll() is not None:
                returncode = p.returncode
                break
        else:
            # Didn't exit in time -- probably entered computation.  The
            # error is raised before entering computation, so things are
            # probably OK.
            returncode = 0
            p.terminate()
    
E       TypeError: can only concatenate str (not "bytes") to str

j          = 49
p          = <subprocess.Popen object at 0x1211fe588>
returncode = 0
```
The actual test succeeds for scipy built with `clang-900.0.39.2` against OpenBLAS 0.3.6.

The issue seems trivially fixed by changing the assert message to
```
        assert_equal(returncode, 0,
                 "Code apparently failed: " + p.stdout.read().decode())
```

### Scipy/Numpy/Python version information:
```
1.2.1 1.14.5 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by tylerjereddy** [comment]
Correct me if I'm wrong, but I'm currently thinking this doesn't look critical so perhaps nice to fix for a future SciPy version /master branch soon, while less worth taking a risk on for a backport at this late stage for `1.3.0`.

For 1.2.x LTS branch, we'd have to worry about Python 2 as well for string vs. bytes stuff I think. We'd have to be careful backporting there, which may not be worth the effort if this is only for a single `XSLOW` test.

**Comment by dhomeier** [comment]
Agreed. The fix looks simple enough, but I don't know enough about the working of `.decode()` to foretell how it will behave without specifying an encoding, in particular within different language settings.
For Python 2 the issue does not come up in the first place because there `p.stdout.read()` does not return a bytes object, which might make it less urgent for 1.2.x.
