### ISSUE TITLE
Peaks not plotting when using seaborn styles with matplotlib

### ISSUE THREAD

**Issue by Rich2020** [scipy/scipy#10188]
### Description

When using some plot styles such as:

`plt.style.use(['seaborn-paper', 'seaborn'])`

No peaks appear in plots when using `find_peaks`.

### Sample code to reproduce the problem

```
import matplotlib.pyplot as plt
import numpy as np
from scipy.signal import find_peaks
from scipy.misc import electrocardiogram

plt.style.use(['seaborn-paper', 'seaborn'])
x = electrocardiogram()[2000:4000]
peaks, _ = find_peaks(x, height=0)
plt.plot(x)
plt.plot(peaks, x[peaks], "x")
plt.plot(np.zeros_like(x), "--", color="gray")
plt.show()
```

No error messages are produced.

### Scipy/Numpy/Python version information:
1.1.0 1.15.4 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)

**Comment by ilayn** [comment]
Hi @Rich2020 

I can't reproduce this as I get this 

![image](https://user-images.githubusercontent.com/1303842/57923990-155e9300-78a4-11e9-9c84-b9db7a9f57e0.png)

with latest versions. But regardless, you might want to ask about this in [matplotlib repo](https://github.com/matplotlib/matplotlib).

**Comment by Rich2020** [comment]
HI @ilayn Yes, that is what I get too. In the code snippet I provided, you should see the peaks clearly marked in the plot, as described in the find_peaks documentation: https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html

**Comment by ilayn** [comment]
![image](https://user-images.githubusercontent.com/1303842/57924180-bd745c00-78a4-11e9-9ec5-0889ecca59fe.png)

It is the marker type

**Comment by Rich2020** [comment]
Right'o, thanks.
