### ISSUE TITLE
Unexpected behaviour in normaltest (bug?)

### ISSUE THREAD

**Issue by giocolangelo** [scipy/scipy#10183]
Hi all, 
I get an unexpected behaviour when running normaltest.
In order to check it working I generate a normal distribution and I apply normaltest. What I see is distinct normaltest result for every new normal distribution.

Shapiro test, very similar test to check normality, indeed gives high p values.

I understand that pvalues higher than 0.05 reject the null hypotesis that the test distribution is different by a normal distribution, but I was not expecting that with the same distribution I get so high volatility of p values.

how is possible that normaltest gives different results (and low p-values) for normal distributions? 
I am on v. 1.1.0
Best
![output](https://user-images.githubusercontent.com/50669961/58087991-04729200-7bc2-11e9-99fe-922d9d959906.jpg)

### Reproducing code example:
import scipy.stats as stats
import numpy as np

[stats.normaltest(np.random.normal(0, 1, 10**6)) for i in range(10)]

[stats.shapiro(np.random.normal(0, 1, 10**6)) for i in range(10)]

 
### Scipy/Numpy/Python version information:
<!-- You can simply run the following and paste the result in a code block
```
import scipy.stats as stats
import numpy as np 

[stats.normaltest(np.random.normal(0, 1, 10**6)) for i in range(10)]

[stats.shapiro(np.random.normal(0, 1, 10**6)) for i in range(10)]```
-->

**Comment by sethtroisi** [comment]
This is expected. P value should be uniformly distributed between 0 and 1 and it is

![Screenshot from 2020-05-23 02-19-42](https://user-images.githubusercontent.com/10172976/82726900-f86d5480-9c9b-11ea-8fa9-9d6d5fb089f2.png)
