### ISSUE TITLE
Derivative of spline with 'const' extrapolation is also extrapolted with 'const' instead of zero

### ISSUE THREAD

**Issue by mirkoruether** [scipy/scipy#10195]
Please label as: scipy.interpolate (I can't figure out how to do it...)

When using scipy.interpolate.InterpolatedUnivariateSpline with option ext='const' to extrapolate values with the boundry value, the derivative also is extrapolated with its boundry values, instead of zero. Please see figure below:

![Figure_1](https://user-images.githubusercontent.com/10485596/58005445-4dafdc80-7b03-11e9-9503-915c061b2ae4.png)

### Reproducing code example:

```
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import InterpolatedUnivariateSpline

x_values = [1, 2, 4, 6, 8.5]
y_values = [0.5, 0.8, 1.3, 2.5, 5]

f = InterpolatedUnivariateSpline(x_values, y_values, ext='const', k=3)

x = np.linspace(0, 10, 1000)
y = f(x)

plt.scatter(x_values, y_values)
plt.plot(x, y, label = 'f(x)')
plt.plot(x, f.derivative()(x), label = 'df(x)/dx')
plt.plot(x[1:], np.diff(y)/np.diff(x), label = 'actual df(x)/dx')
plt.legend()
plt.grid()
plt.show()

```

### Scipy/Numpy/Python version information:
('1.2.1', '1.16.2', sys.version_info(major=2, minor=7, micro=16, releaselevel='final', serial=0))

**Comment by ev-br** [comment]
Indeed, could be fixed rather easily. Would you be intetested in sending a PR?

https://github.com/scipy/scipy/blob/v1.3.0/scipy/interpolate/fitpack2.py#L464

**Comment by mirkoruether** [comment]
Just had a look at the code, you are right, a fix is quite trivial. I will prepare a pull request :)
