### ISSUE TITLE
scipy.sparse.linalg.eigs fails to find right generalized eigenvalue and eigenvector

### ISSUE THREAD

**Issue by yuanzid** [scipy/scipy#10194]
My issue is about solve generalized eigenvalue problem with eigs in module scipy.sparse.linalg.

### Reproducing code example:

```
import numpy as np
from scipy.sparse.linalg import eigs
A = np.random.rand(100,100)-0.5 + np.random.rand(100,100)*1j-0.5j
b =  np.diag(np.random.rand(100)*2-1)
k,v = eigs(A,6,b)
np.allclose(v,0)==True
```
eigs just fail to get right eigenvalue,converge to zero eigen vectors. 
BTW scipy.linalg.eig works well in this case, but it's impossible to apply it to a large sparse problem, which i just want to solve with function scipy.sparse.linalg.eigs.  As [docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigs.html#scipy.sparse.linalg.eigs) mentioned b must be a complex, hermitian, here b is diagonal with zero imaginary part, definitely a complex, hermitian.
while change the generalize eigenvalue problem to standard problem, eigs works well. 
```
A = np.random.rand(100,100)-0.5 + np.random.rand(100,100)*1j-0.5j
b =  np.diag(np.diag(np.random.rand(100)*2-1)
invb = np.linalg.inv(b)
k,v = eigs(invb.dot(A),6)
# this works well
```

I'm not sure if I am in the right hands or there is a bug behind the funtion eigs facing generalized eigenvalue problem.

### Scipy/Numpy/Python version information:
```
 import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.1 1.16.3 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
The documentation also says b has to be positive (semi-)definite.
