### ISSUE TITLE
sparse matrices indexing with scipy 1.3

### ISSUE THREAD

**Issue by Ericgig** [scipy/scipy#10206]
Indexing csr or csc sparce matrix return an array of one element with scipy 1.3, With previous version it returned a scalar. I believe it is an oversight since lil_matrix indexing still return a scalar.

```
import scipy
import numpy as np
print(type(scipy.sparse.csr_matrix(np.eye(3))[0,0]))
print(type(scipy.sparse.csc_matrix(np.eye(3))[0,0]))
print(type(scipy.sparse.lil_matrix(np.eye(3))[0,0]))
```
```
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
```

### Scipy/Numpy/Python version information:
scipy 1.3.0
numpy 1.16.3
python 3.7.0

**Comment by tylerjereddy** [comment]
@perimosocordiae 

Possibly related to CSR and CSC sparse matrix indexing performance improvements in 1.3.0 release?

**Comment by perimosocordiae** [comment]
Yeah, this appears to be a real bug. Thanks for the quick fix @peterbell10 !
