### ISSUE TITLE
Issue when compiling 

### ISSUE THREAD

**Issue by joshuayuny** [scipy/scipy#10224]
Sample code to reproduce the problem
```

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from loader.model_loader import loadmodel
  File "/home/joshuayun/Desktop/IBD/loader/model_loader.py", line 5, in <module>
    from util.feature_operation import hook_feature, hook_grad
  File "/home/joshuayun/Desktop/IBD/util/feature_operation.py", line 6, in <module>
    from scipy.misc import imresize, imread, imsave
ImportError: cannot import name 'imresize'

**Comment by rgommers** [comment]
`imresize` has been removed in 1.3.0. It was deprecated for a long time already. The [1.2.1 docs](https://docs.scipy.org/doc/scipy-1.2.1/reference/generated/scipy.misc.imresize.html#scipy.misc.imresize) say:

Use Pillow instead: `numpy.array(Image.fromarray(arr).resize())`.

**Comment by rgommers** [comment]
There's other options as well (e.g. scikit-image). Just not in SciPy.

**Comment by joshuayuny** [comment]
Okay thank you
