### ISSUE TITLE
Build failures after (re)moving a package

### ISSUE THREAD

**Issue by peterbell10** [scipy/scipy#10222]
I'm working on #10175 and need to move the fttpack c/fortran sources as part of the transition from `scipy.fftpack` to `scipy.fft`. However, whenever I try to do this, the build always fails; even for packages unrelated to fftpack.

I think this is related to the build definitions for native extensions. Are these declared somewhere seperately from `setup.py`?

### Minimum example:
Comment out this line:
https://github.com/scipy/scipy/blob/be97f1a038ef6e3055cfbc83b9550492052ba76b/scipy/setup.py#L11

### Error message:

```
building 'scipy.spatial.qhull' extension
compiling C sources
C compiler: x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC

compile options: '-DHAVE_CBLAS -I/usr/include/python3.6m -I/home/peter/.local/lib/python3.6/site-packages/numpy/core/include -Iscipy/_lib -I/home/peter/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c'
x86_64-linux-gnu-gcc: scipy/spatial/qhull_src/src/mem_r.c
x86_64-linux-gnu-gcc: scipy/spatial/qhull_src/src/qset_r.c
x86_64-linux-gnu-gcc: scipy/spatial/qhull_src/src/random_r.c
x86_64-linux-gnu-gcc: scipy/spatial/qhull_src/src/rboxlib_r.c
scipy/spatial/qhull_src/src/qset_r.c: In function ‘qh_setfree’:
scipy/spatial/qhull_src/src/qset_r.c:718:10: warning: variable ‘freelistp’ set but not used [-Wunused-but-set-variable]
   void **freelistp;  /* used if !qh_NOmem by qh_memfree_() */
          ^~~~~~~~~
scipy/spatial/qhull_src/src/qset_r.c: In function ‘qh_setnew’:
scipy/spatial/qhull_src/src/qset_r.c:928:10: warning: variable ‘freelistp’ set but not used [-Wunused-but-set-variable]
   void **freelistp; /* used if !qh_NOmem by qh_memalloc_() */
          ^~~~~~~~~
x86_64-linux-gnu-gcc: scipy/spatial/qhull_src/src/usermem_r.c
scipy/spatial/qhull_src/src/random_r.c: In function ‘qh_argv_to_command’:
scipy/spatial/qhull_src/src/random_r.c:84:6: warning: this ‘else’ clause does not guard... [-Wmisleading-indentation]
     }else
      ^~~~
scipy/spatial/qhull_src/src/random_r.c:86:7: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘else’
       strcat(command, s);
       ^~~~~~
x86_64-linux-gnu-gcc: scipy/spatial/qhull_src/src/userprintf_r.c
x86_64-linux-gnu-gcc: scipy/spatial/qhull_src/src/userprintf_rbox_r.c
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/scipy/spatial/qhull.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/geom2_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/geom_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/global_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/io_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/libqhull_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/mem_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/merge_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/poly2_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/poly_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/qset_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/random_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/rboxlib_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/stat_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/user_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/usermem_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/userprintf_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/userprintf_rbox_r.o -Lbuild/temp.linux-x86_64-3.6 -lopenblas -lopenblas -o build/lib.linux-x86_64-3.6/scipy/spatial/qhull.cpython-36m-x86_64-linux-gnu.so -Wl,--version-script=build/temp.linux-x86_64-3.6/link-version-scipy.spatial.qhull.map
build/temp.linux-x86_64-3.6/scipy/spatial/qhull.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Running from scipy source directory.
/home/peter/.local/lib/python3.6/site-packages/numpy/distutils/system_info.py:730: UserWarning: Specified path /usr/local/include/python3.6m is invalid.
  return self.get_paths(self.section, key)
error: Command "x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/scipy/spatial/qhull.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/geom2_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/geom_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/global_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/io_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/libqhull_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/mem_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/merge_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/poly2_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/poly_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/qset_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/random_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/rboxlib_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/stat_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/user_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/usermem_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/userprintf_r.o build/temp.linux-x86_64-3.6/scipy/spatial/qhull_src/src/userprintf_rbox_r.o -Lbuild/temp.linux-x86_64-3.6 -lopenblas -lopenblas -o build/lib.linux-x86_64-3.6/scipy/spatial/qhull.cpython-36m-x86_64-linux-gnu.so -Wl,--version-script=build/temp.linux-x86_64-3.6/link-version-scipy.spatial.qhull.map" failed with exit status 1
```
Important parts:
```
qhull.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Running from scipy source directory.
/home/peter/.local/lib/python3.6/site-packages/numpy/distutils/system_info.py:730: UserWarning: Specified path /usr/local/include/python3.6m is invalid.
  return self.get_paths(self.section, key)
```

This message is for qhull but if I build in parallel, every extention will fail to build with similar "File format not recognized" errors.

**Comment by rgommers** [comment]
> I'm working on #10175 and need to move the fttpack c/fortran sources as part of the transition from `scipy.fftpack` to `scipy.fft`. 

Given that `scipy.fftpack` needs to stay working, I don't think you should move the fftpack sources. Just import the parts that are needed (i.e. the ones not in Pocketfft) from `scipy.fftpack`.

> However, whenever I try to do this, the build always fails; even for packages unrelated to fftpack.
> 
> I think this is related to the build definitions for native extensions. Are these declared somewhere seperately from `setup.py`?

Each submodule has its own `setup.py`. All the extension build config is in those files, there's nothing else.

**Comment by peterbell10** [comment]
>Given that scipy.fftpack needs to stay working, I don't think you should move the fftpack sources. Just import the parts that are needed (i.e. the ones not in Pocketfft) from `scipy.fftpack`.

The plan is to eventually remove the fortran code entirely so that `scipy.fftpack` use the same implementation as `scipy.fft`.  But for the time being, `scipy.fft` needs to used to fortran code for DST, DCT and other functionality.  To avoid a cyclic dependency, I move everything into `scipy.fft` and `scipy.fftpack` calls into `scipy.fft`. Does that make sense?

**Comment by rgommers** [comment]
Okay, it could make sense. You may avoid indeed a cyclic dependency if `scipy.fftpack` is halfway through a transition to Pocketfft. I was more thinking the plan was to leave `scipy.fftpack` completely alone though. I'm not remembering a particular reason for _not_ moving it to Pocketfft right now. And deleting Fortran code would be quite nice:)

For moving the code, think about how to preserve git history. The easiest would probably be to (starting from master) rename `fftpack` to `fft` in the source in a single commit (should just have to touch 2 `setup.py` files and one directory name), and then add back a new `fftpack` module in following commits.

**Comment by peterbell10** [comment]
>For moving the code, think about how to preserve git history.

:+1: that's exactly what I'm trying to do.

**Comment by rgommers** [comment]
Great. Also, this is a good opportunity to put underscores in all the names that are nonpublic for `scipy.fft`. Which is pretty much everything. So all Python file names - `scipy.fftpack.realtransforms` should become `scipy.fft._realtransforms` (if you're moving that file).

**Comment by peterbell10** [comment]
I was actually thinking that (in anticipation of backend support) it would be better to put everything in a subpackage `scipy.fft._fftpack` and setup `__all__` as if they were directly in `scipy.fft`.  Doing it this way I shouldn't need undersores, correct?

**Comment by rgommers** [comment]
Oh yes, that works too. No need for underscores inside `_fftpack` then.

**Comment by peterbell10** [comment]
I managed to get scipy to build again after uninstalling python and reinstalling with the latest version. Not sure what went wrong but I it seems the issue wasn't with scipy itself.
