### ISSUE TITLE
scipy installation hang if pip install at embed 1GiB RAM system

### ISSUE THREAD

**Issue by Haffon** [scipy/scipy#10234]
I have an development board with armv7 cpu and 1GiB RAM, when install it with
pip install scipy
the pip download "scipy-1.2.1.tar.gz (23.1MB)" file and try to install it, but the installation will hang as no more memory to finish the scipy source code compilation, because there is 4 cc1plus process exist in top command cosumed all RAM.

Can I disable the scipy parallel(multicore) compile?

**Comment by rgommers** [comment]
The default build method is single core not parallel. We have a `-j N` flag so you can set `N` to an integer >1 to do a parallel build, this isn't invoked by `pip` normally though. So you'll have to check what is happening on your system. Perhaps your `pip` is somehow modified?

**Comment by Haffon** [comment]
The most steps of building is single core, but sometimes there is 4 cc1plus process, I think I need to find out which step launch multiply cc.

**Comment by Haffon** [comment]
After open the verbose mode of pip, there is many compiler processes when it doing:
f951
gfortran:f77:scipy/optimize/minpack/lmpar.f

cc1
arm-linux-gnueabi-gcc: scipy/special/cephes/round.c

cc1plus
arm-linux-gnueabi-g++: scipy/sparse/sparsetools/sparsetools.cxx

It is only out of memory after the output show "compiling C++ sources", may be it is the same problem when I compile other library with "make -f", it only works compile without "f"options.

**Comment by Haffon** [comment]
Is there any one can tell me how to configure the "compiling C++ sources" phase which building launched by pip?

**Comment by rgommers** [comment]
It's invoked by the `build_ext` command of `numpy.distutils`. That goes via https://github.com/numpy/numpy/blob/master/numpy/distutils/ccompiler.py#L694, that particular line monkeypatches Python `distutils`. I don't see anything in `numpy.distutils` that parallelizes anything, so either it's in Python distutils or it's how your compiler is configured.

**Comment by Haffon** [comment]
I checked the scipy and numpy code and document with the notice of @rgommers , and fixed it with "export NPY_NUM_BUILD_JOBS=1" with lucky. The building phase consume 900MiB RAM at most, the corresponding code is https://github.com/numpy/numpy/blob/e21d2cbdf15a86e16ef4877a42ed98d97ea296d3/numpy/distutils/misc_util.py#L102.

**Comment by rgommers** [comment]
Thanks for the update @Haffon. If that fixed it, I do consider it a bug (likely in `numpy.distutils`). It seems like the C++ build step calls `get_num_build_jobs` in the absence of a `--parallel` flag, which is wrong.

**Comment by Haffon** [comment]
It is fixed with setting NPY_NUM_BUILD_JOBS environment variable to 1.

**Comment by rgommers** [comment]
I investigated a little. There's two forms of parallelism:
- building multiple extensions in parallel (controlled by the `--parallel` (or equivalent `-j`) flag)
- parallel building within a single extension (enabled by default)

You're running into the second form. It happens to be controllable by `NPY_NUM_BUILD_JOBS`, perhaps not entirely by design.

The default is sensible I think, because it speeds up the build considerably, it's robust, and it's not common anymore that there's not enough memory.

So I think I'll leave it at that for now. Better documentation would be nice, but that's true of everything `distutils`-related.

**Comment by Haffon** [comment]
Thanks for your explanation, so I can find the correct location to configure the compile options. There is still a long call stack I need to check to make sure I don't miss something.
