### ISSUE TITLE
Typo in scipy.stats.nct documentation

### ISSUE THREAD

**Issue by sparrigan** [scipy/scipy#10244]
Keen to be corrected on this, but I think there's a typo in the documentation at https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.nct.html

The sentence after the first equation reads

 _"(denoted nct in the implementation)"_

But should, I believe,  read:

_"(denoted **nc** in the implementation)"_

**Comment by ev-br** [comment]
Definitely a typo, PR welcome
