### ISSUE TITLE
Response when number of workers cannot be satisfied

### ISSUE THREAD

**Issue by peterbell10** [scipy/scipy#10242]
[`differential_evolution`][1] has support for multithreading via a `workers` argument (added in #8259) which is handled at the python level. The new pocketfft code (#10238) relies on OpenMP being available and so depending on platform, using the requested number of workers might not be possible.

How should this be reported to the user:
 - Silently ignore it
 - Issue a warning
 - Raise an error

@rgommers has expressed interest in raising an error. I think that this could be problematic since it will likely make the user's code less portable.

We could also make this configurable either globally in scipy or at the level of `scipy.fft`, similar to what was suggested in [#10175][2].

[1]: https://docs.scipy.org/doc/scipy-1.3.0/reference/generated/scipy.optimize.differential_evolution.html?highlight=differential%20evolution#scipy.optimize.differential_evolution
[2]: https://github.com/scipy/scipy/issues/10175#issuecomment-492299942

**Comment by rgommers** [comment]
I'm just thinking: both `multiprocessing` and `threading` (as well as threading in C/C++) will give you as many processes/threads as you ask for, independent of hardware. So an error will never be raised. I'm not too familiar with OpenMP, how does it handle this?

**Comment by peterbell10** [comment]
I'm seeing that their's an environment variable `OMP_THREAD_LIMIT`. I don't know exactly what the behavor is though.

**Comment by peterbell10** [comment]
Actually, is sounds like `omp_get_max_threads` and `OMP_THREAD_LIMIT` aren't hard limits [1][1].  It would still be the case though that if pocketfft is compiled without OpenMP, it will always be single threaded.

[1]: https://www.ibm.com/support/knowledgecenter/SSGH4D_15.1.0/com.ibm.xlf151.aix.doc/proguide/ompgetmaxthreads.html

**Comment by rgommers** [comment]
Just came across this. @peterbell10 implemented a custom threadpool, there's no OpenMP in SciPy - so I think this can be closed.
