### ISSUE TITLE
pip3 installation error

### ISSUE THREAD

**Issue by rpotter12** [scipy/scipy#10245]
My issue is about ...
I have installed scipy using command `pip3 install scipy`. But when I run a command `from scipy import stats`, it was giving an error. 

Screenshot:
![Screenshot from 2019-06-02 06-31-15](https://user-images.githubusercontent.com/34352567/58755399-006b3c00-8501-11e9-83c7-4c76de204f07.png)

**Comment by ilayn** [comment]
Hi @rpotter12. Make sure you don't have any other Python 3 versions, say 3.7,  installed that pip3 points to.

**Comment by jakevdp** [comment]
In general, it's better practice to install packages like this:
```
python -m pip install scipy
```
Then you'll be certain you're installing it in the site packages of the python executable you're using.

**Comment by rpotter12** [comment]
@ilayn @jakevdp thanks for the information :)
