### ISSUE TITLE
scipy.fft: What functions should be included

### ISSUE THREAD

**Issue by peterbell10** [scipy/scipy#10240]
Related to #10238 

As well as the functions in `fftpack`, `numpy.fft` also has transforms for hermitian signals with real frequency space representations (`hfft` and `ihfft`). A notable omission is n-dimensional variants; there are no `hfftn` and `ihfftn`. Should we include these in `scipy.fft`?

There are also the pseudo-differential operators from  `scipy.fftpack` which aren't conceptually related to FFTs, they just happen to use it as an implementation detail.  So I would be in favour of leaving them out, at least for now.

### Currently Included
- `fft(n)`
- `ifft(n)`
- `rfft(n)`
- `irfft(n)`
- `(i)fftshift`
- `(r)fftfreq`
- `next_fast_len`

### Needs decision
- `hfft(n?)`
- `ihfft(n?)`

**Comment by larsoner** [comment]
Since the n-dimensional variants are missing, and because it's much easier to add something later than it is to remove something already in the namespace (from a deprecation / API perspective), I'd say let's leave them out for now / in the first implementation. Basically start with some minimal set of functions in `scipy.fft` that are uncontroversial, and go from there. So that would be something like:

- `fft`(n)
- `ifft`(n)
- `rfft`(n)
- `irfft`(n)

@peterbell10 feel free to list here others that should be in there. If you agree with this approach, feel free to start editing the top comment to list the functions that should exist in the first PR that actually adds the `scipy.fft` module.

**Comment by rgommers** [comment]
> There are also the pseudo-differential operators from scipy.fftpack which aren't conceptually related to FFTs, they just happen to use it as an implementation detail. So I would be in favour of leaving them out, at least for now.

+1

**Comment by rgommers** [comment]
> Since the n-dimensional variants are missing

**Comment by peterbell10** [comment]
They are missing from numpy:
https://docs.scipy.org/doc/numpy/reference/routines.fft.html#hermitian-ffts

**Comment by rgommers** [comment]
Oh sorry, I misread. Looking at Eric's bullet list, I thought me meant `fftn` rather than `hfftn`. 

So yes, I agree with the suggestion - leaving the n-dim versions out now, can be added for completeness later on (it would make sense to have them).

**Comment by rgommers** [comment]
Other ones to decide are the helper functions: `fftshift`, `ifftshift`, `fftfreq` and `rfftfreq` all make sense. Less sure about `next_fast_len`; unclear how it should behave if it's included.

**Comment by peterbell10** [comment]
A few things worth noting about `next_fast_len`:
 - PocketFFT adds a new prime factor of 11, but only for complex ffts. So, that means `next_fast_len` will be inaccurate for at least one of these.
 - `next_fast_len` is used in scipy itself in a few places
https://github.com/scipy/scipy/blob/90534919e139d2a81c24bf08341734ff41a3db12/scipy/signal/windows/windows.py#L1976
https://github.com/scipy/scipy/blob/e42b2d1480161d30a744dec3eab6702aa16b940c/scipy/signal/signaltools.py#L406-L407

**Comment by rgommers** [comment]
Perhaps the right thing to do is to include it, but clearly document that the length it returns is implementation-dependent and may change without warning. So code using it should only use it to pad, transform, and then unpad back to the same length.

And after I've written the above I'm then thinking: that would really benefit from a utility function to do those 3 steps, or a keyword in all fft functions that enables using it under the hood.

**Comment by peterbell10** [comment]
I think the problem is that you usually want to perform some convolution-theorem type operation so it's more like
```python
N = next_fast_len(len(x))
x_f = fft(x, N)
y = ifft(x_f * x_f.conj(), len(x)) # Or some other operation in fourier-space
```
Which can't be made into one step since we don't know what they want to do in the fourier domain.

However, I agree that something like
```python
x_f = fft(x, pad_fast_len=True)
```
does make a lot of sense. But it might be harder to generalize to n-dimensions.

**Comment by larsoner** [comment]
> Perhaps the right thing to do is to include it, but clearly document that the length it returns is implementation-dependent and may change without warning.

Sounds good to me. Agreed it should be implementation-dependent and noted in the docs that this is the case. 

To deal with the real/complex issue, we can add and argument for the `dtype` that will be used for the `fft` operation. For `pocketfft` it can vary depending on whether this is complex or real. For other backends it probably won't.

**Comment by peterbell10** [comment]
>As well as the functions in `fftpack`, `numpy.fft` also has transforms for hermitian signals with real frequency space representations (`hfft` and `ihfft`).

As an update to this, @mreineck is adding a [`forwards` argument][1] to `r2c` and `c2r` that would support this directly in pocketfft.

>A notable omission is n-dimensional variants; there are no hfftn and ihfftn.

I would speculate that the reason NumPy has avoided this is that once the transform is over more than one axis, it's no longer strictly hermitian, because of the mirroring that appears in my `xfftn_real` function
https://github.com/scipy/scipy/blob/5153c454d938f7c237496a7025f6a8c9c59f3641/scipy/fft/_pocketfft/scipy_features.h#L211-L212

So, the concept of a real-in-frequency-space transform is valid. However, calling it `hfftn` may be misleading.

[1]: https://gitlab.mpcdf.mpg.de/mtr/pypocketfft/issues/2#note_41639
