### ISSUE TITLE
NumPy symbols imported into scipy namespace

### ISSUE THREAD

**Issue by peterbell10** [scipy/scipy#10253]
I was getting some strange errors while using the `scipy.fft` module in #10238.
```
>>> scipy.fft.fft
Traceback (most recent call last):
File "<console>", line 1, in <module>
AttributeError: 'function' object has no attribute 'fft'
```

I have now found out that most of NumPy's symbols are exported into the `scipy` base module. This is all done from within `scipy/__init__.py`

https://github.com/scipy/scipy/blob/1169d27ad47a29abafa8a3d2cb5b67ff0df80a8f/scipy/__init__.py#L68-L74

Is there any possibility of removing this behavior?

**Comment by WarrenWeckesser** [comment]
Ugh, that's definitely a nuisance if we want to create a new `scipy.fft` subpackage.  The history of importing the numpy names into the `scipy` namespace goes way back, and I'm pretty sure most would agree that, in hindsight, it was a mistake.   Using the numpy names in the `scipy` namespace is certainly discouraged these days.  I wish we could remove those imports completely, but such a change creates a backwards incompatibility that could break user's code. Even if we are not promoting the usage, and even if we discourage it when we see it, folks still manage to find and use those numpy names in `scipy`.

I don't have a good recommendation at the moment.  Anyone have any bright ideas for handling this?

We could consider different names, e.g. `scipy.spectral`, `scipy.dft`, `scipy.fourier`, etc.  I'm not too excited about any of those, to be honest.

Also, can we consider doing some deprecation magic to deprecate the use of all those numpy names in `scipy`?  That won't help us with `fft` right now, but it would eventually free up the name `scipy.fft` once the deprecation has been in place long enough that the names can be removed.

**Comment by larsoner** [comment]
> I don't have a good recommendation at the moment. Anyone have any bright ideas for handling this?

Do `__call__ = np.fft` in `scipy/fft.py` (or `scipy/fft/__init__.py`). It should work I think.

**Comment by larsoner** [comment]
... and +1 for deprecating these NumPy functions, probably using some magical decorating-as-deprecated loop.

**Comment by peterbell10** [comment]
Apparently callable modules are impossible.
https://stackoverflow.com/questions/1060796/callable-modules

**Comment by larsoner** [comment]
Argh, I thought I had "solved" this problem once before and `__call__` was the solution. Apparently not, sorry for the noise!

I'll think a bit more, but that StackOverflow makes it sound impossible :(

**Comment by WarrenWeckesser** [comment]
> Apparently callable modules are impossible.

That's OK.  It was an interesting idea, but I would not have supported actually implementing it.  It feels like an API hack that we would later regret.

**Comment by larsoner** [comment]
... actually, since we require 3.5+ now, it looks like there [is a solution that should work in that thread](https://stackoverflow.com/questions/1060796/callable-modules#answer-48100440) by hacking `sys.modules`:
```
import sys

class MyModule(sys.modules[__name__].__class__):
    def __call__(self):  # module callable
        return 42

sys.modules[__name__].__class__ = MyModule
```
It's not pretty, but we'd only have to live with it for a few cycles until the NumPy functions are removed anyway.

**Comment by rgommers** [comment]
Ouch, that's a problem.

> We could consider different names, e.g. scipy.spectral, scipy.dft, scipy.fourier, etc. I'm not too excited about any of those, to be honest.

We've talked about `scipy.transforms` before, and that's a name that could make sense. IIRC we discussed it when someone wanted to add a Hankel transform, and when we still wanted to integrate PyWavelets into SciPy.

**Comment by larsoner** [comment]
Closing since this should work now, and we have a plan for deprecation in #10290
