### ISSUE TITLE
imsave not found despite pillow install

### ISSUE THREAD

**Issue by themightyoarfish** [scipy/scipy#10250]
So far as I remember, one always had ti install `Pillow` in order for `imsave` to work. But in my current environment, it does not work.

### How to Reproduce:
```
$> python3.7 -m venv test_env
$> source test_env/bin/activate
$> pip install Pillow scipy
$> python -c "import scipy.misc; scipy.misc.imsave"
```

### Error message:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'scipy.misc' has no attribute 'imsave'
```

### Scipy/Numpy/Python version information:

OS is macOS 10.14.5.

**Comment by rgommers** [comment]
It was removed in 1.3.0. See the deprecation message for an alternative: https://docs.scipy.org/doc/scipy-1.1.0/reference/generated/scipy.misc.imsave.html#scipy.misc.imsave
