### ISSUE TITLE
Typo in scipy.stats.t documentation

### ISSUE THREAD

**Issue by vp-code** [scipy/scipy#10260]
It looks like the t distribution documentation  at https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.t.html#scipy.stats.t has a typo in the formula for the probability density function. The normalization constant should have 
Gamma(nu/2) in the denominator, not Gamma(nu) , as currently displayed.

**Comment by ev-br** [comment]
Yup, a typo. Care to submit a PR with the fix?

**Comment by vp-code** [comment]
Sorry, I am not a developer and am particularly unfamiliar with GitHub - I wouldn't know what to do :-)
