### ISSUE TITLE
CircleCI Merge PRs Failing

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#10261]
The past few merge PR workflows have failed on CircleCI:

```
build finished with problems, 248 warnings.
Makefile:115: recipe for target 'html-scipyorg' failed
make: *** [html-scipyorg] Error 1
make: Leaving directory '/home/circleci/repo/doc'
Exited with code 2
```

**Comment by larsoner** [comment]
The nitpicky mode + treat-warnings-as-errors seems to have become problematic. I assume it's due to a sphinx version bump making the nitpicking more accurate. The best thing to do would be to fix the warnings, but I'm not sure how easy that will be.
