### ISSUE TITLE
Documentation error for K-sample Anderson test

### ISSUE THREAD

**Issue by amulliner-dstl** [scipy/scipy#10263]
The[ documentation for the k sample Anderson test](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.anderson_ksamp.html) has incorrect values for the significance levels associated with the returned critical values.

Currently the documentaion shows:
`    critical_values : array
        The critical values for significance levels 25%, 10%, 5%, 2.5%, 1%.`

Where as the the code in morestats.py on line 2039 shows:
`sig = np.array([0.25, 0.1, 0.05, 0.025, 0.01, 0.005, 0.001])`

There is also an issue with the signifance_level as the value is not floored at 1%, but at 0.1% as outlined in the notes.

I am using scipy version 1.2. However these errors are present in the version 1.3 docs as well.

**Comment by chrisb83** [comment]
Yes, that is an error in the documentation.
