### ISSUE TITLE
ttest_from_stats warning dependent on size of passed array

### ISSUE THREAD

**Issue by ivirshup** [scipy/scipy#10269]
This is a fairly specific bug. If you pass `scipy.stats.ttest_ind_from_stats` a sample with equal mean and zero s.d. in an array of length > 1, it will throw warnings. If you pass a sample with equal mean and zero s.d. by itself, you won't get a warning. The warning comes from operations in `stats.distributions.t.sf`.

### Reproducing code example:

```python
from scipy import stats
import numpy as np

# This does not throw an warning
stats.ttest_ind_from_stats(
    mean1=np.ones(1), std1=np.zeros(1), nobs1=10,
    mean2=np.ones(1), std2=np.zeros(1), nobs2=10,
)

# This throws a warning
scores, pvals = stats.ttest_ind_from_stats(
    mean1=np.ones(2), std1=np.zeros(2), nobs1=10,
    mean2=np.ones(2), std2=np.zeros(2), nobs2=10,
)
```

### Warning

```python
/usr/local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
/usr/local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
/usr/local/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py:1892: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)
```

### What I think should happen

I think that this behaviour should be consistent, an not depend on the size of the passed array. I also think this probably shouldn't throw a warning. There's already handling done to not warn the user if equal s.d.s are passed in `scipy.stats.stats._equal_var_ttest_denom` and  `scipy.stats.stats._unequal_var_ttest_denom`.

### Scipy/Numpy/Python version information:

This also occurs in the `v1.2.1` releases of scipy.
```
scipy==1.3.0 numpy==1.16.4 
sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment]
Neither of these raise a warning for me.
@swallan can you test this? 
If it's OK for you, I think we can close.

**Comment by swallan** [comment]
They seem to run just fine for me as well.

I'll close as a result.
