### ISSUE TITLE
New doc build warnings, causing CI to fail

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#10270]
We have a check in CI that the html doc build is warning-free. This recently started to fail. There are now 248 warnings like:
```
/home/circleci/repo/build/testenv/lib/python3.7/site-packages/scipy/interpolate/_bsplines.py:docstring of scipy.interpolate.BSpline:143: WARNING: py:obj reference target not found: tck
```
This is likely due to some change in Sphinx or another library we use. If anyone could investigate (check for new releases first, that will point to the likely suspect), that would be very helpful.

**Comment by larsoner** [comment]
Closing as dup of #10261
