### ISSUE TITLE
error: Error -3 while decompressing data: invalid code lengths set

### ISSUE THREAD

**Issue by KarthikMgk** [scipy/scipy#10282]
I tried to load a simple 2.7 GB .npz file on notebook that is running on cloud and I'm getting the above error. My scipy version is 1.1.0 which I verified from both terminal and jupyter notebook.

### Reproducing code example:
m_m_sim_sparse = sparse.load_npz("m_m_sim_sparse.npz")

### Error message:
 1 m_m_sim_sparse = sparse.load_npz("m_m_sim_sparse.npz")

/usr/local/lib/python3.5/site-packages/scipy/sparse/_matrix_io.py in load_npz(file)
    148 
    149         if matrix_format in ('csc', 'csr', 'bsr'):
--> 150             return cls((loaded['data'], loaded['indices'], loaded['indptr']), shape=loaded['shape'])
    151         elif matrix_format == 'dia':
    152             return cls((loaded['data'], loaded['offsets']), shape=loaded['shape'])

~/.local/lib/python3.5/site-packages/numpy/lib/npyio.py in __getitem__(self, key)
    260                 return format.read_array(bytes,
    261                                          allow_pickle=self.allow_pickle,
--> 262                                          pickle_kwargs=self.pickle_kwargs)
    263             else:
    264                 return self.zip.read(key)

~/.local/lib/python3.5/site-packages/numpy/lib/format.py in read_array(fp, allow_pickle, pickle_kwargs)
    732                     read_count = min(max_read_count, count - i)
    733                     read_size = int(read_count * dtype.itemsize)
--> 734                     data = _read_bytes(fp, read_size, "array data")
    735                     array[i:i+read_count] = numpy.frombuffer(data, dtype=dtype,
    736                                                              count=read_count)

~/.local/lib/python3.5/site-packages/numpy/lib/format.py in _read_bytes(fp, size, error_template)
    871         # done about that.  note that regular files can't be non-blocking
    872         try:
--> 873             r = fp.read(size - len(data))
    874             data += r
    875             if len(r) == 0 or len(data) == size:

/usr/lib/python3.5/zipfile.py in read(self, n)
    842         self._offset = 0
    843         while n > 0 and not self._eof:
--> 844             data = self._read1(n)
    845             if n < len(data):
    846                 self._readbuffer = data

/usr/lib/python3.5/zipfile.py in _read1(self, n)
    918         elif self._compress_type == ZIP_DEFLATED:
    919             n = max(n, self.MIN_READ_SIZE)
--> 920             data = self._decompressor.decompress(data, n)
    921             self._eof = (self._decompressor.eof or
    922                          self._compress_left <= 0 and

error: Error -3 while decompressing data: invalid code lengths set
-->

### Scipy/Numpy/Python version information:
>>> scipy.__version__
'1.1.0'
>>> numpy.__version__
'1.16.4'

>>>Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux

**Comment by jwd0023** [comment]
What does your "m_m_sim_sparse.npz" look like?

**Comment by KarthikMgk** [comment]
It is a sparse matrix.

**Comment by jwd0023** [comment]
It looks like something is wrong with the content of your file. Can you reproduce the error for any other file that you can share?

I can't help unless you give actual details.

**Comment by sethtroisi** [comment]
No follow up on generic issue.
