### ISSUE TITLE
Issue when building OpenBLAS

### ISSUE THREAD

**Issue by dan-elk** [scipy/scipy#10297]
I am following the instructions to build OpenBLAS before building SciPy. I am only doing this in the first place because the pip SciPy installer in anaconda was insufficient and has left me with several DLL load errors.

Instructions for reference: (http://scipy.github.io/devdocs/building/windows.html)

I have successfully followed the instructions up to the point where I download the build-openblas folder into my GitHub repository on my computer. I even checked to see that the commands
```
make
gfortran
gcc
```
were installed like the directions said to do. Once I am in the directory in my MSYS2 command prompt, I run

```
git submodule update --init --recursive
```
and receive no indication of any kind that any task was performed. Is this normal?

Also, the next steps say to perform the following commands:
```
export OPENBLAS_COMMIT=5f998ef
export OPENBLAS_ROOT="C:\\opt"
export BUILD_BITS=64
```
When I do this, I get no response as before.

Finally, I run 
```
./build_openblas.sh
```
and receive the following:

### Error message:

```
bash: ./build_openblas.sh: No such file or directory
```
Any help at all would be greatly appreciated..

**Comment by tylerjereddy** [comment]
> I am only doing this in the first place because the pip SciPy installer in anaconda was insufficient and has left me with several DLL load errors.

I think we generally discourage mixing `pip` and `conda`. Might be worth trying the pip install inside a [virtualenv](https://virtualenv.pypa.io/en/latest/userguide/) if that's an option? Which versions of Python and SciPy are you interested in?

**Comment by dan-elk** [comment]
@tylerjereddy I am using Python 3.6.8, and I have the most recent version of SciPy installed. To further assist in helping me, I'll post my original error message that I am trying to fix.

``
Traceback (most recent call last):

  File "190422_ML_algorithm_prediction.py", line 14, in <module>
    from sklearn.metrics import mean_squared_error

  File "C:\Users\Daniel\Anaconda3\lib\site-packages\sklearn\__init__.py", line 64, in <module>
    from .base import clone

  File "C:\Users\Daniel\Anaconda3\lib\site-packages\sklearn\base.py", line 13, in <module>
    from .utils.fixes import signature

  File "C:\Users\Daniel\Anaconda3\lib\site-packages\sklearn\utils\__init__.py", line 16, in <module>
    from .fixes import _Sequence as Sequence

  File "C:\Users\Daniel\Anaconda3\lib\site-packages\sklearn\utils\fixes.py", line 85, in <module>
    from scipy.special import boxcox  # noqa

  File "C:\Users\Daniel\Anaconda3\lib\site-packages\scipy\special\__init__.py", line 640, in <module>
    from ._ufuncs import *

ImportError: DLL load failed: The specified module could not be found.
``
I am using Scikit-learn for a machine learning project.

**Comment by dan-elk** [comment]
I was not able to solve this issue, but it doesn't matter because I fixed the original issue by finding the correct DLLs and downloading them.
