### ISSUE TITLE
scipy.stats.nbinom.interval returns wrong result for p=1

### ISSUE THREAD

**Issue by IdrissAlaoui** [scipy/scipy#10317]
When computing confidence intervals with probability of success equals to 1. The function `scipy.stats.nbinom.interval()` doesn't return the expected result.

### Reproducing code example:

```
>>> scipy.stats.nbinom.interval(alpha=0.9, n=10, p=1)
(1e+100, 0.0)
```

### Expected result:

This is what is expected !
```
>>> scipy.stats.nbinom.interval(alpha=0.9, n=10, p=1)
(0.0, 0.0)
```
For instance with Poisson distribution
```
>>> scipy.stats.poisson.interval(alpha=0.9, mu=0)
(0.0, 0.0)
```

### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.1 1.16.3 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

**Comment by AlexisMignon** [comment]
The problem seems to come from the `special.nbdtrik` function which is itself a wrapper for a function from the cdflib.

More precisely

`special.nbdtrik(y, n, p)` returns `1e+100` when `p=1` and `y <= 0.5`

the output if nbdtrik is supposed to be (from the scipy documentation)

> The maximum number of allowed failures such that `nbdtr(k, n, p) = y`. However, for p=1.0, `nbdtr(k, n, p) = 1.0, for all k (k=0, 1, 2, ...)

So:
1. The actual definition from the documentation is probably not accurate for a discrete distribution (`nbdtr(k, n, p) <= y` ?) 
2. The result for all values of q < 1.0 should probably be 0 or a sentinel value -1 but not 1e+100 which violates the non-decreasing constraint on  cdf functions.

What is the best way to work around this ?

**Comment by rlucas7** [comment]
Not sure if this is a defect or just a floating point equality issue (you shouldn't really test for equals in floating point). I looked at this one for a bit, documenting my findings in case someone wants to pick it up or I come back to it later. 

in the `binom_gen` class here:
https://github.com/scipy/scipy/blob/master/scipy/stats/_discrete_distns.py#L62

the calls to `_pdf` and similar call underlying `scipy.special` cephes functions, `_pdf` goes here:

https://github.com/scipy/scipy/blob/master/scipy/special/cephes/bdtr.c#L191-L217

now in there I was able to reproduce and trace the call to line:

https://github.com/scipy/scipy/blob/master/scipy/special/cephes/bdtr.c#L214

e.g. using 
```
from scipy import special
p=1.0
k=0.5
n=10
special.bdtr(k, n, p) #throws a runtime warning on first call 
```
Worth noting this throws a warning on the first call. 

some closer inspection shows:

```
>>> scipy.stats.nbinom.interval(alpha=0.9, n=10, p=0.9999999999999999)
(0.0, 0.0)
>>> scipy.stats.nbinom.interval(alpha=0.9, n=10, p=0.99999999999999999)
(1e+100, 0.0)
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.4.0.dev0+a54f392 1.16.4 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
```

I'm a bit behind master but I don't think I saw anything that should affect `special.bdtr` function. 
Ideally we'd put fix in the `cephes/bdtr.c` code. I'm not sure if there is a built in c function to measure closeness. If there is and someone can point me I can hack at a fix. 

An alternate solution is adding a check in the `special.bdtr` (and related) functions for something sufficiently close to 1.0 (and 0.0) and then use a stable approximation. 
Not pretty but it would work.

**Comment by mdhaber** [comment]
@mckib2 Boostinator?

**Comment by mckib2** [comment]
@mdhaber Boost does the right thing here:
```
nbinom interval should be (0, 0):
    scipy_nbinom: (1e+100, 0.0)
    boost_nbinom: (0.0, 0.0)
```

**Comment by mdhaber** [comment]
This issue was solved for scipy.stats by gh-13328. We might consider replacing `special.nbdtrik` with the Boost implementation, too.
