### ISSUE TITLE
Feature request: Add exact distribution to Wilcoxon test

### ISSUE THREAD

**Issue by HeikoSchuett** [scipy/scipy#10321]
The Wilcoxon-test currently reacts to small sample sizes by throwing the warning

```
Warning: sample size too small for normal approximation.
```

and then proceeds running the normal approximation anyway. 

As the distribution of the test-statistic is not very complicated and the number of alternatives is bearable for less than 20 samples, one could enumerate all possibilities and use the exact distribution for those cases instead, which would yield a correct test for these cases.

### Scipy/Numpy/Python version information:
```
1.2.0 1.15.4 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
referenced explicitly in the "stats roadmap" meta issue gh-10577. so yes good idea, thanks for the suggestion @HeikoSchuett. PR welcome, or otherwise maybe one of us will get to it.

I'll close this since it's captured elsewhere.
