### ISSUE TITLE
Error importing SciPy modules

### ISSUE THREAD

**Issue by dan-elk** [scipy/scipy#10326]
Using Anaconda, I am unable to import SciPy. The simple command

```
from scipy import stats
```
gives me the following:

### Error message:

```
Traceback (most recent call last):
    File "test_f8.py", line 15, in <module>
    import preprocessing_f3 as pp
  File "C:\Users\Daniel\Desktop\Side Projects\Research\Dr. Zheng\Python\super_cubic_cyclic\preprocessing_f3.py", line 11, in <module>
    from scipy import stats
  File "C:\Users\Daniel\Anaconda3\lib\site-packages\scipy\stats\__init__.py", line 367, in <module>
    from .stats import *
  File "C:\Users\Daniel\Anaconda3\lib\site-packages\scipy\stats\stats.py", line 172, in <module>
    import scipy.special as special
  File "C:\Users\Daniel\Anaconda3\lib\site-packages\scipy\special\__init__.py", line 641, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: The specified module could not be found.
  ...
```

Do I need to uninstall and reinstall SciPy? If so, any recommendations on how I should install it through anaconda? I have seen conflicting information online. Some people say to use pip, some people say not to.

### Scipy/Numpy/Python version information:

I am using SciPy 1.2.1 with Python 3.6.8 : : Anaconda Custom (64-bit).
-->

**Comment by ilayn** [comment]
If you are using *conda (which looks like you use Anaconda3) then it is best to avoid `pip` and use its own pip-like command `conda`. If you have more than one installation of scipy on your system (sometimes happen) then import mechanism gets confused and starts importing different scipy installations on the system. To avoid this it is best to remove all instances and contain all environments mutually exclusive.

**Comment by dan-elk** [comment]
@ilayn How do you recommend I remedy this? I tried using conda to uninstall and reinstall scipy by typing

`conda uninstall scipy`
then
`conda install scipy`

but this did not solve the original issue.

**Comment by dan-elk** [comment]
https://stackoverflow.com/questions/39020361/python-scipy-module-import-error-due-to-missing-ufuncs-dll

For anyone with this issue, I followed these steps and was able to solve it by downloading the package that had the correct DLLs.
