### ISSUE TITLE
Adding more low-level LAPACK wrappers

### ISSUE THREAD

**Issue by AidanGG** [scipy/scipy#10323]
I would like to be able to make use of the following LAPACK routines from `scipy.linalg.lapack` (which currently have Cython wrappers provided in `scipy.linalg.cython_lapack`): `geqrt`, `gemqrt`, `tpqrt` and `tpmqrt` for tiled QR factorisation. I suggest the following signatures (with work and info as necessary):

```
?geqrt(nb, a, overwrite_a) -> (a, t)
?gemqrt(side, trans, v, t, c, overwrite_c) -> (c)
?tpqrt(l, nb, a, b, overwrite_a, overwrite_b) -> (a, b, t)
?tpmqrt(side, trans, v, t, a, b, overwrite_a, overwrite_b) -> (a, b)
```

Since QR on F-contiguous is equivalent to LQ on C-contiguous, in principle the LQ factorisation equivalents `gelqt`, `gemlqt`, `tplqt`, `tpmlqt` could be called on C-contiguous arrays to avoid a transposition at the high level. However, these routines do not have the Cython wrappers, which I assume is due to their relatively recent introduction to LAPACK.

I am happy to work on a PR for getting at least the four tiled QR routines going, but I will need some guidance with what's involved to do so.

**Comment by ilayn** [comment]
@AidanGG Thanks for taking the time. 

These routines came with Lapack 3.4 which we only recently assumed as the minimum version to support hence their absence.

For getting acquainted with the wrappers gou can check, say, #8965 on what is involved and which files are needed.

Please let me know if you need any more information.

**Comment by AidanGG** [comment]
Hi @ilayn, that is very helpful. I will try my hand at writing a PR.
