### ISSUE TITLE
Error in truncnorm implementation

### ISSUE THREAD

**Issue by stokhos** [scipy/scipy#10342]
My issue is about ...
rv = scipy.stats.truncnorm(a=-0., b=0.2, loc=6, scale=2) 
rv.logpdf(0.19) gives -inf, shuold be 1.1835079
### Reproducing code example:

```
rv = scipy.stats.truncnorm(a=-0., b=0.2, loc=6, scale=2) 
rv.logpdf(0.19)
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

**Comment by andyfaff** [comment]
The help for `truncnorm` [says](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.truncnorm.html):

> The standard form of this distribution is a standard normal truncated to the range [a, b] — **notice that a and b are defined over the domain of the standard normal**. To convert clip values for a specific mean and standard deviation, use:
`a, b = (myclip_a - my_mean) / my_std, (myclip_b - my_mean) / my_std`

```
>>> from scipy.stats import truncnorm, norm
>>> myclip_a, myclip_b, my_mean, my_std = 0, 0.2, 6, 2
>>> a, b = (myclip_a - my_mean) / my_std, (myclip_b - my_mean) / my_std
>>> print(a, b)
-3.0 -2.9
>>> rv = truncnorm(a, b, my_mean, my_std)
>>> print(rv.logpdf(0.19), rv.pdf(0.19))
1.7379698000428698 5.685788409761759

>>> # now check that the values calculated by truncnorm are correct
>>> print(norm.cdf([0, 0.2], loc=6, scale=2))
[0.0013499  0.00186581]
>>> print(norm.pdf(0.19, loc=6, scale=2) / (0.00186581 - 0.0013499))
5.685846476130137
>>> print(np.log(norm.pdf(0.19, loc=6, scale=2) / (0.00186581 - 0.0013499)))
1.7379698000428698
```
So the values are being calculated correctly by `truncnorm` as well.
