### ISSUE TITLE
scipy.misc.bytescale is missing

### ISSUE THREAD

**Issue by simonrp84** [scipy/scipy#10346]
I have code that makes use of the `scipy.misc.bytescale` function, which no longer appears to be present in recent versions of scipy.
Looking through the documentation I see that `bytescale` is deprecated.
Why is this so? Is there a replacement available and, if so, where can I find it?

**Comment by ilayn** [comment]
Yes it has been emitting warnings since version 1.0 until 1.2 and removed in 1.3. In general we are trying to deprecate the misc module completely since its usage is not generic enough and there are much more comprehensive libs for image manipulations. You can use scikit-image utils instead.

**Comment by simonrp84** [comment]
> Yes it has been emitting warnings since version 1.0 until 1.2 and removed in 1.3. In general we are trying to deprecate the misc module completely since its usage is not generic enough and there are much more comprehensive libs for image manipulations. You can use scikit-image utils instead.

In that case it would be nice if the documentation contained more information, rather than just saying "depreciated". Google suggests a lot of other users have had similar issues.

**Comment by rgommers** [comment]
agreed, for `bytescale` we seem to have forgotten to include a note about what the recommended alternative is. Using `scikit-image` instead would be a sensible way to go, its `util` module has good data rescaling functions: https://scikit-image.org/docs/stable/api/skimage.util.html
