### ISSUE TITLE
DeprecationWarning: elementwise == comparison failed

### ISSUE THREAD

**Issue by Make42** [scipy/scipy#10356]
I am using scipy 1.1.0 and I am trying to use 'trust-constr' for optimization of my function `self.cost_fct` constrained with the function `self.nonlinear_constraint` - both of which return a numpy one-dimensional numpy array.

            cons = scipy.optimize.NonlinearConstraint(fun=self.nonlinear_constraint,
                                                      lb=0,
                                                      ub=np.inf,
                                                      keep_feasible=True,
                                                      jac='3-point',
                                                      hess=scipy.optimize.BFGS())
            res = scipy.optimize.minimize(fun=self.cost_fct,
                                          x0=init,
                                          method='trust-constr',
                                          constraints=cons,
                                          jac='3-point',
                                          options={'disp': False, 'maxiter': 8}
                                          )

I get the error

```
FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
The above exception was the direct cause of the following exception:
Traceback (most recent call last):

  File "~/myproject/gauss_fitting_BFGS.py", line 290, in fit
    options={'disp': False, 'maxiter': 8}
  File "~/miniconda3/envs/myenv/lib/python3.5/site-packages/scipy/optimize/_minimize.py", line 615, in minimize
    callback=callback, **options)
  File "~/miniconda3/envs/myenv/lib/python3.5/site-packages/scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py", line 323, in _minimize_trustregion_constr
    finite_diff_rel_step, finite_diff_bounds)
  File "~/miniconda3/envs/myenv/lib/python3.5/site-packages/scipy/optimize/_differentiable_functions.py", line 98, in __init__
    self.H = hess(x0, *args)
  File "~/miniconda3/envs/myenv/lib/python3.5/site-packages/scipy/optimize/_hessian_update_strategy.py", line 277, in __init__
    if exception_strategy == 'skip_update':
DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
```

I would think, that even if this was a warning, I should not get a lethal exception, but just a warning.

Btw, I am not able to update my python 3.5, because of dependencies.

**Comment by Kai-Striega** [comment]
@Make42 Thanks for taking the time to raise an issue and apologies in the delay.

Firstly could you include a [minimum working example](https://stackoverflow.com/help/minimal-reproducible-example)?

The original ``FutureWarning`` comes from NumPy's array comparison. I'm not sure if we can fix those at the SciPy level. Either way, if it's causing a fatal error, we should handle it better. Could you let me know your numpy version using ``import numpy as np; print(np.__version__)``? 

> I would think, that even if this was a warning, I should not get a lethal exception, but just a warning.

Are you *currently* getting an exception or do you think that *in the future* this should not be an exception?

> Btw, I am not able to update my python 3.5, because of dependencies.

That shouldn't matter. SciPy 1.1.0 supports Python3.5 (and still does in 1.3).

**Comment by rgommers** [comment]
No further follow-up, I don't think there is a bug here, and we can't do anything with a reproducing example. So closing this issue.
