### ISSUE TITLE
DOC: linprog and linear_sum_assignment tutorials needed

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#10358]
SciPy's linear optimization functions are not even mentioned in the `scipy.optimize` tutorial.  I thought adding these tutorials might be a good topic for someone at the upcoming SciPy conference sprint.

**Comment by Kai-Striega** [comment]
@mdhaber I've started working on a linear programming example (the diet problem) for #10136. I've been flat out at work and haven't made much progress on it (yet).

**Comment by mdhaber** [comment]
Ok, great. I was thinking it would be a good thing for SciPy conference sprint attendees to do, but I can direct them to linear sum assignment if you're already on it?

**Comment by Kai-Striega** [comment]
At the moment my stuff is only notes and sketches.

The sprints are on the 13th/14th right? I am happy to leave it until the
sprint. If someone else wants to do it, great! If not, I'll finish my
version off.

I would appreciate if the sprint example includes a callback interface,
that way it covers my PR too.

**Comment by mdhaber** [comment]
I don't think anyone worked on this for the sprint, btw.

**Comment by tapaswenipathak** [comment]
Hi folks, I am adding few linear_sum_assignment tutorials.

**Comment by tapaswenipathak** [comment]
Hi folks, I am adding few for linear_sum_assignment tutorials.
