### ISSUE TITLE
https://docs.scipy.org/doc/scipy/reference/fftpack.html text crashing into each other

### ISSUE THREAD

**Issue by anoetzli** [scipy/scipy#10369]
My issue is about ...

### HTML Documentation not displayed correctly
HTML documentation for https://docs.scipy.org/doc/scipy/reference/fftpack.html is not displayed correctly - the text is crashing into each other. Tested on Chrome, Brave and Safari.

**Comment by ilayn** [comment]
Hi @anoetzli, thank you for reporting. I don't see anything peculiar on Firefox 67.0.4. Can you please include a screenshot?

**Comment by anoetzli** [comment]
Hi Ilhan,

Thank you for your quick reply - below is a screenshot from Brave, which looks the same in Chrome v 75.0.3770.100. Safari isn’t quite so bad. It only affects the FFT section.

Kind regards,

Adrian

**Comment by ilayn** [comment]
I think email replies don't carry over the attachments apparently. Do you mind adding it on the GitHub website by editing the response?

**Comment by anoetzli** [comment]
Of course - please give me a few minutes.

**Comment by anoetzli** [comment]
![image](https://user-images.githubusercontent.com/32256358/60325150-2fb68100-99b9-11e9-9dfc-461001d118f6.png)
Screenshot attached.

**Comment by ilayn** [comment]
Hmm, that's weird indeed. Somehow the tab stop got confused

**Comment by anoetzli** [comment]
Further down the page, the first column text is also quite long but it seems to wrap correctly, though it also looks a bit strange.

![image](https://user-images.githubusercontent.com/32256358/60325337-a5bae800-99b9-11e9-9966-511fe0c25e33.png)

**Comment by ilayn** [comment]
Do you also see it on the devdocs version of the docs ? 

http://scipy.github.io/devdocs/fftpack.html

**Comment by anoetzli** [comment]
Yes I do.

**Comment by pv** [comment]
Displays correctly in firefox and chrome. Afaik, there's no very complicated CSS work going on either.

**Comment by sethtroisi** [comment]
I tested a year later in Safari, Chrome, and Firefox with a variety of zoom levels and didn't see this.

Closing for now. If anyone can repro reply with a browser and version number and I'll investigate

**Comment by anoetzli** [comment]
Confirm that I don’t see the issue anymore - tested on Brave 1.8.86 on MacOS 10.14.6.

Thanks,
Adrian
