### ISSUE TITLE
DOC: Developer Documentation Refactoring Suggestions

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#10366]
Some unresolved behind-the-scenes issues from #10286.

@larsoner suggested replacing hyperlinks with interlinks where possible:

>This can be linked directly via `intersphinx` as:
>```
>:doc:`numpy:reference/distutils_guide`
>```
>In general you can find this sort of thing by doing e.g.:
>```
>python -msphinx.ext.intersphinx https://www.numpy.org/devdocs/objects.inv > numpy.txt
>```
>and inspecting the content for links of interest. It's probably worth checking to see if others can be linked similarly.

Some of these were fixed in #10286, but a more thorough search would probably reveal other places where this is possible.

@larsoner also suggest that we might be able to remove `'dev/core-dev/` documents from the `exclude_patterns` from `conf.py`:

> Maybe the thing to do would be to rename the files with `.rst.inc` extension to make it clear that they are just meant to be included and not rendered/used on their own. Then they don't even need to be in this list because they won't match the doc extension (rst)

I tried in #10286 but had trouble. *Update: this is done.*

**Comment by mdhaber** [comment]
@larsoner Should I keep this open? I don't think this is really restricted to the new developer documentation or even developer documentation in general, so I don't really want to take this on myself. If you think it's important enough, we could see if Season of Docs contributors are interested? Or do you think it is easy enough to be labeled Good First Issue?

**Comment by brandondavid** [comment]
@mdhaber I can take this on, unless you'd rather reserve it for a Good First Issue.

In the meantime, I'll crosspost it in the numpy-team Slack where many of the GSoD writers are.

**Comment by mdhaber** [comment]
Thanks @brandondavid! That would be terrific, although I admit this is a lower-priority item as it will be invisible to users. @larsoner had some ideas above for how to do this automatically, though, so hopefully it's not a huge undertaking.

**Comment by brandondavid** [comment]
1. I wrote a script that looks through all the reST files in `/doc` and its subdirectories, finding every numpy.org and scipy.org hyperlink and comparing each one to its respective intersphinx map.  The NumPy map was generated as described above and the SciPy map was generated with 
`python -msphinx.ext.intersphinx https://docs.scipy.org/doc/scipy/reference/objects.inv`.

    Of the 19 such hyperlinks found, there were 6 matches:
    ```
    ./scipy/doc/release/1.2.0-notes.rst
        FOUND https://docs.scipy.org/doc/scipy/reference/tutorial/stats/discrete_poisson.html
        MAYBE :doc:`scipy:tutorial/stats/discrete_poisson`

    ./scipy/doc/release/1.3.0-notes.rst
        FOUND https://docs.scipy.org/doc/scipy-1.1.0/reference/misc.html
        MAYBE :doc:`scipy:misc`

    ./scipy/doc/source/toolchain.rst
        FOUND https://docs.scipy.org/doc/scipy/reference/release.1.2.0.html
        MAYBE :doc:`scipy:release.1.2.0`

        FOUND https://docs.scipy.org/doc/numpy/release.html
        MAYBE :doc:`scipy:release`

    ./scipy/doc/source/tutorial/io.rst
        FOUND https://www.numpy.org/devdocs/reference/routines.io.html
        MAYBE :doc:`numpy:reference/routines.io`

    ./scipy/doc/source/tutorial/linalg.rst
        FOUND https://www.numpy.org/devdocs/reference/routines.linalg.html
        MAYBE :doc:`numpy:reference/routines.linalg`
    ```
    gh-11129 fixes the last 4 listed, as I assume it's best to leave the release notes untouched.


2. Looking at the [full output](https://gist.githubusercontent.com/brandondavid/1654cdd9b5c1bbfe2836bdbda8909fbd/raw/ba73b34b5ea936715a86033bc47f0b5fab48b0c5/interlinks.txt), I wonder if some of the unmatched hyperlinks might be worth adding to the intersphinx map.  Here is a partial list:
    ```
    docs.scipy.org/doc/numpy/reference/distutils.html
    docs.scipy.org/doc/numpy/reference/testing.html
    docs.scipy.org/doc/scipy/reference/tutorial/stats/discrete.html#percent-point-function-inverse-cdf
    numpy.org/devdocs/reference/routines.random.html
    scipy.org/install.html
    scipy.org/scipylib/mailing-lists.html
    ```

**Comment by mdhaber** [comment]
Yes, I think that @larsoner was suggesting adding to the map when necessary. I think the idea was to use intersphinx where possible, and including for other projects like asv and matplotlib.

**Comment by brandondavid** [comment]
Unfortunately, I don't have a good sense of what "necessary" looks like for the map.  Would all six of the above links be okay to add?

**Comment by mdhaber** [comment]
Hi @brandondavid, I don't know much about using Intersphinx; everything I know is from the [documentation](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) (which isn't supremely helpful) and feeling around in the dark during gh-10286. Hopefully @larsoner can chime in here as he seems to know more about this. 

If you mean adding those URLs to the "Intersphinx Configuration" in [doc/source/conf.py](https://github.com/scipy/scipy/blob/master/doc/source/conf.py):
```
# -----------------------------------------------------------------------------
# Intersphinx configuration
# -----------------------------------------------------------------------------
intersphinx_mapping = {
    'python': ('https://docs.python.org/dev', None),
    'numpy': ('https://docs.scipy.org/doc/numpy', None),
    'matplotlib': ('https://matplotlib.org', None),
    'asv': ('https://asv.readthedocs.io/en/stable/', None),
}
```
then no, I don't believe it is necessary to add all of those links.

For instance, I see that I added that last line to the list:
```
'asv': ('https://asv.readthedocs.io/en/stable/', None),
```
in gh-10286 and I used that definition in [doc/source/dev/contributor/benchmarking.rst](https://github.com/scipy/scipy/blob/master/doc/source/dev/contributor/benchmarking.rst):
```
The :ref:`Writing benchmarks <asv:writing-benchmarks>` section of the airspeed velocity documentation
```
, which renders as:
> The [Writing benchmarks](https://asv.readthedocs.io/en/stable/writing_benchmarks.html#writing-benchmarks) section of the airspeed velocity documentation

in the [online documentation for benchmarking](http://scipy.github.io/devdocs/dev/contributor/benchmarking.html#benchmarking-with-asv).

So I think you only need to put the top level domain in `conf.py`. If the documentation aT that domain was created with Sphinx, then after the prefix (e.g. `asv:`) you would just need whatever you would write as an reference from within the project (e.g. `writing-benchmarks`), which you can generally figure out from the URL (e.g. `https://asv.readthedocs.io/en/stable/writing_benchmarks.html#writing-benchmarks`). If there's a better way - and I really, really hope there is - I don't know it!
