### ISSUE TITLE
python-scipy cross compilation fail

### ISSUE THREAD

**Issue by hinar24** [scipy/scipy#10365]
I am trying to corss-compile scipy for open-embedded but the bitbake build failed with error
i have also added recipe for distutils-extra and change in local.conf as IMAGE_INSTALL += "python-scipy python-distutils-extra"

### Recipe for Scipy
SUMMARY = "Scientific Library for Python"
SECTION = "devel/python"
HOMEPAGE = "https://pypi.python.org/pypi/scipy"

LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=d0db8f4148a3d5534cfb93be78f9287c"

PYPI_PACKAGE="scipy"

SRC_URI[md5sum] = "53fa34bd3733a9a4216842b6000f7316"
SRC_URI[sha256sum] = "87ea1f11a0e9ec08c264dc64551d501fa307289460705f6fccd84cbfc7926d10"

inherit pypi setuptools distutils

RDEPENDS_${PN} += "python-core python-numpy python-distutils"
DEPENDS += "python-numpy"

### Error message:
DEBUG: Executing shell function do_compile
Traceback (most recent call last):
  File "setup.py", line 418, in <module>
    setup_package()
  File "setup.py", line 398, in setup_package
    from numpy.distutils.core import setup
ImportError: No module named numpy.distutils.core
ERROR: python setup.py build execution failed.

### Scipy/Numpy/Python version information:
 scipy version 1.0.0
       python vesion 2.7
       numpy 1.7.0

**Comment by rgommers** [comment]
please search for other cross compile issues, there are some with more detail

**Comment by rgommers** [comment]
The conda compilers are cross-compilers, and I believe we've got the issues ironed out building with numpy 1.17.x and those compilers. See https://github.com/numpy/numpy/issues/13280

This isn't actionable for us, so I'll close it. Thanks for the report though @hinar24. If there's specific things we can fix in SciPy, please let us know.
