### ISSUE TITLE
TST: Travis CI fails (with pytest 5.0 ?)

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#10376]
Example logs: https://travis-ci.org/scipy/scipy/jobs/552251037

Perhaps this is because of the recent pytest release.

Potentially relevant snippet of error output:

```
E   _pytest.config.ConftestImportFailure: (local('/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/scipy/conftest.py'), (<class 'DeprecationWarning'>, DeprecationWarning("the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses",), <traceback object at 0x7f335c515748>))
```

Probably less relevant, but perhaps useful to fix while we're at it:
```
/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/_pytest/config/__init__.py:297: PytestConfigWarning: pytest-faulthandler plugin has been merged into the core, please remove it from your requirements.
  name.replace("_", "-")

```

I tried to reproduce locally on my Mac without much success and indeed some other CI services do also seem to pass when picking up pytest 5.0. Maybe there's a warning flag or env variable I'm missing to trigger it. It looks like an older pytest gets installed & then removed in the full log, but the runner seems to properly use pytest 5.0, so not sure that's an issue.

**Comment by charris** [comment]
Sebastian fixed those problems for NumPy: https://github.com/numpy/numpy/pull/13864

**Comment by tylerjereddy** [comment]
I suppose we could try adding the warning filter before `import imp` in our source, but I'm not sure we have a good reason to continue using that over `importlib` on master branch at this point.

**Comment by pv** [comment]
The "import imp" in this case turned out to be in the system python stdlib on Travis-CI.
I guess they're not at the latest micro release, or the installation is modified somehow.

**Comment by tylerjereddy** [comment]
Thanks for cleaning up my mess :)
