### ISSUE TITLE
Question about mannwhitneyu

### ISSUE THREAD

**Issue by kleintt** [scipy/scipy#10394]
My issue is about mannwhitneyu. Not about code's bug, but about caculation problem. I wanted to compare two independent samples with mannwhitneyu and did this test with scipy.stats.mannwhitneyu and SPSS Statistic 25. Then i found i return same p value but different u value. After i check the scipy code, i found it use different equation with Wikipedia. In Wikipedia: u1 =np.sum(rankx, axis=0)-(n1*(n1+1))/2.0 
and as we all know u1+u2=n1*n2,so, "Wikipedia u1"= "scipscipy.stats.mannwhitneyu u2".

### Reproducing code example:

```
    u1 = n1*n2 + (n1*(n1+1))/2.0 - np.sum(rankx, axis=0)  # calc U for x
    u2 = n1*n2 - u1  # remainder is U for y
```

### Error message:

```
 "Wikipedia u1"= "scipscipy.stats.mannwhitneyu u2"
```

### Scipy/Numpy/Python version information:

scipy                              1.2.1

**Comment by chrisb83** [comment]
I think this is already raised in Issue #9184. I close this Issue, feel free to reopen If 9184 does not cover your question.
