### ISSUE TITLE
DOC: scipy.signal.resample ignores t parameter

### ISSUE THREAD

**Issue by 30blay** [scipy/scipy#10403]
The resample function does not take into account the t optional parameter during the Fourier transform, as if it assumed that t is evenly spaced. When this is not the case, the returned resampled_t is erroneous.

If t must be evenly spaced, this should be checked by the function or written in the documentation.

### Reproducing code example:

```python
import numpy as np
from scipy import signal
import matplotlib.pyplot as plt

rate = 100
t = np.arange(rate) / float(rate)
t[1] = t[1]/4
x = np.sin(2 * np.pi * t)
resampled_x, resampled_t = signal.resample(x, rate, t=t)
fig, ax = plt.subplots()
plt.plot(t, x)
plt.plot(resampled_t, resampled_x)
plt.show()
```

### Scipy/Numpy/Python version information:

```
1.3.0 1.16.4 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
> The resample function does not take into account the t optional parameter during the Fourier transform, as if it assumed that t is evenly spaced.

It *is* assumed that `t` is evenly spaced. 

> If t must be evenly spaced, this should be checked by the function or writen in the documentation.

Yes, this could be made clearer in the docstring.

**Comment by larsoner** [comment]
@30blay would you be up for making a pull request to update the documentation to make it clearer how `t` is used?

**Comment by 30blay** [comment]
Yes!
