### ISSUE TITLE
Intersphinx for special not working

### ISSUE THREAD

**Issue by person142** [scipy/scipy#10406]
Warning: this could be due to my own lack of understanding of Sphinx.

If you check e.g. SciPy lectures:

https://scipy-lectures.org/intro/scipy.html#special-functions-scipy-special

the intersphinx links for `scipy.special` aren't working. But the links for e.g. `scipy.linalg` are working:

https://scipy-lectures.org/intro/scipy.html#linear-algebra-operations-scipy-linalg

and they are doing the same thing in the source:

https://raw.githubusercontent.com/scipy-lectures/scipy-lecture-notes/ddfda4ca06df2e40f1053bde97124025956e1101/intro/scipy.rst

which makes me suspect that there is an issue on our end. Anybody have ideas about what's wrong?

**Comment by larsoner** [comment]
I would dump the intersphinx objects.inv to a text file to see if the special entries are there first

https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#showing-all-links-of-an-intersphinx-mapping-file

**Comment by person142** [comment]
> I would dump the intersphinx objects.inv to a text file to see if the special entries are there first

Right, when I do that I get:

```
$ python3 -m sphinx.ext.intersphinx 'http://docs.scipy.org/doc/scipy/reference/objects.inv' | grep scipy.linalg.det
	scipy.linalg.det                         generated/scipy.linalg.det.html#scipy.linalg.det
	generated/scipy.linalg.det               scipy.linalg.det                        : generated/scipy.linalg.det.html
```

and

```
$ python3 -m sphinx.ext.intersphinx 'http://docs.scipy.org/doc/scipy/reference/objects.inv' | grep scipy.special.erf
	scipy.special.erf                        generated/scipy.special.erf.html#scipy.special.erf
	scipy.special.erfc                       generated/scipy.special.erfc.html#scipy.special.erfc
	scipy.special.erfcx                      generated/scipy.special.erfcx.html#scipy.special.erfcx
	scipy.special.erfi                       generated/scipy.special.erfi.html#scipy.special.erfi
	scipy.special.erf_zeros                  generated/scipy.special.erf_zeros.html#scipy.special.erf_zeros
	scipy.special.erfcinv                    generated/scipy.special.erfcinv.html#scipy.special.erfcinv
	scipy.special.erfinv                     generated/scipy.special.erfinv.html#scipy.special.erfinv
	generated/scipy.special.erf              scipy.special.erf                       : generated/scipy.special.erf.html
	generated/scipy.special.erf_zeros        scipy.special.erf_zeros                 : generated/scipy.special.erf_zeros.html
	generated/scipy.special.erfc             scipy.special.erfc                      : generated/scipy.special.erfc.html
	generated/scipy.special.erfcinv          scipy.special.erfcinv                   : generated/scipy.special.erfcinv.html
	generated/scipy.special.erfcx            scipy.special.erfcx                     : generated/scipy.special.erfcx.html
	generated/scipy.special.erfi             scipy.special.erfi                      : generated/scipy.special.erfi.html
	generated/scipy.special.erfinv           scipy.special.erfinv                    : generated/scipy.special.erfinv.html
	r02786d0e1498-1                          generated/scipy.special.erfc.html#r02786d0e1498-1
	r2fcfb47718d8-1                          generated/scipy.special.erf_zeros.html#r2fcfb47718d8-1
	r372a81c02b65-1                          generated/scipy.special.erfcx.html#r372a81c02b65-1
	r4fd20f32d9c4-1                          generated/scipy.special.erf.html#r4fd20f32d9c4-1
	r4fd20f32d9c4-2                          generated/scipy.special.erf.html#r4fd20f32d9c4-2
	r4fd20f32d9c4-3                          generated/scipy.special.erf.html#r4fd20f32d9c4-3
	r86377c029376-1                          generated/scipy.special.erfi.html#r86377c029376-1
```

which look about the same to me (but, as mentioned I don't know Sphinx very well).

**Comment by larsoner** [comment]
A critical part is actually missing from the above due to the `grep`, which is which category they are part of. `func` is what you (reasonably) assume in your links above, but in the inventory you'll see:
```
py:data
	...
	scipy.special.erf                        generated/scipy.special.erf.html#scipy.special.erf
```
So if you want to refer to these, you have to counter-intuitively do it as:
```
blah blah :data:`scipy.special.erf`.
```
or so. You might also be able to just do:
```
blah blah :obj:`scipy.special.erf`
```
or you might be able to let `autolink` do a bit more work for you, too, by setting `default_role = 'autolink'` in `conf.py` then just doing:
```
blah blah `scipy.special.erf`.
```

Perhaps we should fix our doc building to properly link to these as `:func:` rather than `:data:`, but I'm not sure how difficult this would be. FWIW the LAPACK wrappers like `scipy.linalg.lapack.zgesdd` are also in the `py:data` category, too.

**Comment by person142** [comment]
Thanks for the Sphinx lesson Eric!

Ok, glancing through the inventory it looks like ufuncs are `:data:` and non-ufuncs are `:function:`. Guessing that this has something to do with autodoc not being able to introspect on ufuncs? Anyway, doesn't appear to be a SciPy issue at heart, so closing this.
