### ISSUE TITLE
Find number of iterations for Arpack wrapper scipy.sparse.linalg.eigsh

### ISSUE THREAD

**Issue by m-schillinger** [scipy/scipy#10418]
I am working with the eigsh function from scipy.sparse.linalg. I am wondering how to find the number of iterations that is needed until convergence? Is there any way to find this?

I have troubles with runtime and would like to find out if the problem is a large number of iterations or the time each single iteration takes.

Thank you!

Scipy/Numpy/Python version information:
```
1.1.0 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
I don't think this is known with Krylov methods, especially if you don't know the eigenvalue structure beforehand.

**Comment by m-schillinger** [comment]
Sorry, I think I didn't phrase this clearly. I am not trying to find this theoretically, I wish to get this information from eigsh.

**Comment by pv** [comment]
The number of iterations actually taken to get the result?
It does not return it as such, but you can count the number of matrix-vector products yourself:
```
A = np.random.rand(6,6)  # or any other matrix 

from scipy.sparse.linalg import LinearOperator
count = [0]
def matvec(x): 
    count[0] += 1 
    return A.dot(x) 
def rmatvec(x): 
    count[0] += 1 
    return A.T.dot(x) 
A_op = LinearOperator(matvec=matvec, rmatvec=rmatvec, shape=A.shape, dtype=A.dtype)   
eigsh(A_op, ...)
```
