### ISSUE TITLE
opposite to stats.chi2.ppf

### ISSUE THREAD

**Issue by rvallari1** [scipy/scipy#10428]
Mine is a question.

I am trying to find chi-square of two columns[categorical], hence therefore relativity between them. Also, after finding chi-sqaure value.. I want to use it as critical value and find the confidence level(just opposite what .chi2.ppf does)..! Can you tell me what is just opposite to stats.chi2.ppf(q = 0.95, df = 4)

Also, the crosstabs value are very large. Will it affect the results of chi-square value?
cross_tab=pd.crosstab(dataframe['Wdft_IsGamer'],dataframe['HasDetections'] , rownames=['a'], colnames=['b'])
chivalue,_,df,_=scs.chi2_contingency(cross_tab)
print(scs.chi2.cdf(chivalue, df))--> 1.0
--cross_tab--
b          0        1
a                    
0.0  3197504  2976639
1.0  1119559  1324330

**Comment by pvanmulbregt** [comment]
By `opposite` do you mean `inverse function`? If so, the cumulative distribution function, or`cdf` is the inverse function of the `ppf`.  E.g.

```
In [3]: scipy.stats.chi2.ppf(0.95, df=4)
Out[3]: 9.487729036781154

In [4]: scipy.stats.chi2.cdf(9.487729036781154, df=4)
Out[4]: 0.95
```

**Comment by chrisb83** [comment]
I close this since there is no issue with the functionality. As Paul pointed out, most likely `cdf` is the method that is needed.

Note that there is also a `chisquare` test:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chisquare.html#scipy.stats.chisquare

**Comment by rvallari1** [comment]
Sorry being late! 
so just consider this case.
The crosstab I have 
b          0        1
a
0.0  3197504  2976639
1.0  1119559  1324330
I intend to find chi-square statistic and hence the p-value.
The result of :

chivalue,p,df,ex=scs.chi2_contingency(ch_test)
print("{},{},{},{}".format(chivalue,p,df,ex))
 
is:

25028.258980134848,0.0,1,[[3092836.54342534 3081306.45657466]
 [1224226.45657466 1219662.54342534]]
1.0

For furthur clarification:

>>> import scipy.stats as scs
>>> scs.distributions.chi2.sf(33818.38656256124,33818)
0.49838436837459354
>>> scs.distributions.chi2.sf(33818.38656256124,3381)
0.0

My query is to seek out another method for finding probability (p-value) where the observed values are high as compared to degrees of freedom.!
:)
