### ISSUE TITLE
the results of cholesky decomposition are inconsistent

### ISSUE THREAD

**Issue by shouxi** [scipy/scipy#10420]
The results of cholesky decomposition are inconsistent.  
It seems that this is not caused by scipy, but hope to find a scipy fix.  

### Reproducing code example:

```
import numpy as np
import scipy.linalg

M = np.array(
[[5.5654993001885755e-01, 7.2616964513613487e-17, 1.7019601057878163e-17, 1.7019601057878163e-17], 
 [7.2616964513613500e-17, 2.5275262999398207e-05, 2.1274501322347702e-17, 2.1274501322347702e-17],
 [1.7019601057878163e-17, 2.1274501322347702e-17, 5.5654993430722788e-01, 4.9862112474252427e-18],
 [1.7019601057878163e-17, 2.1274501322347702e-17, 4.9862112474252427e-18, 5.5654993430722788e-01]]
)

L1 = scipy.linalg.cholesky(M, lower=True)[:2,:2]
L2 = scipy.linalg.cholesky(M[:2, :2], lower=True)

print(L1 - L2)

L3 = np.linalg.cholesky(M)[:2,:2]
L4 = np.linalg.cholesky(M[:2,:2])

print(L3 - L4)

```

output:
```
[[ 0.00000000e+00  0.00000000e+00]
 [-1.23259516e-32  0.00000000e+00]]
[[ 0.00000000e+00  0.00000000e+00]
 [-1.23259516e-32  0.00000000e+00]]

```

### Scipy/Numpy/Python version information:
```
1.2.1 1.16.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment]
What is the inconsistency here?

**Comment by shouxi** [comment]
Hi ilayn, 
The result of L1 - L2 should be [[0, 0], [0,0]] (so does L3 - L4).

**Comment by ilayn** [comment]
Numerically they are. The machine epsilon `eps` is  ~1e-16 and the remainders are in the order of `O(eps^2)` hence numerically zero. That is how floating point systems work.

Nevertheless on my machine I get exact zeros with the current dev version of scipy and numpy. It can change from machine to machine or LAPACK version to LAPACK version.

**Comment by shouxi** [comment]
Thank you so much. Regarding this, is there any suggestion on how to write a platform-independent code?  This inconsistency causes bugs in my code.

**Comment by ilayn** [comment]
This gives me the impression that you are checking for exact zeros. When dealing with floats you must always compare the result to a neighborhood of the result. All the assertions in the numpy suite such as [`numpy.allclose`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html) and alike are specifically provided for this purpose.

**Comment by shouxi** [comment]
Indeed, I am trying to solve a problem which is made of a series of linear equation systems. seems that such inconsistency would lead to different results after several iterations.
