### ISSUE TITLE
numpy.irr calculates the same value if cash flows are reversed

### ISSUE THREAD

**Issue by RoyLarson** [scipy/scipy#10432]
I am using numpy 1.16.2 installed through Conda, and I found that if I take the negative of the cash flows I end up with the same value  
`
    import numpy  
  
    cash_flow = numpy.array([-900, -500,  400,  400,  400,  400,  400,  400,  400,  400,  400])    

    irr=numpy.irr(cash_flow)    

    print(irr)    

    negatitve_irr = numpy.irr(-1*cash_flow)    

    print(negative_irr)    

    print(irr == negative_irr)    

`
The first and second print statements print   
0.20541421256305714   
The third prints    
True

**Comment by WarrenWeckesser** [comment]
@RoyLarson, this is the issue tracker for the `scipy` package.  Your question is about `numpy.irr`, so you should raise this issue at https://github.com/numpy/numpy

**Comment by WarrenWeckesser** [comment]
I just noticed the "transfer issue" link here on github.  Let's give that a shot...
