### ISSUE TITLE
scipy.optimize.dual_annealing always rejects non-improving state

### ISSUE THREAD

**Issue by hogloid** [scipy/scipy#10437]
scipy.optimize.dual_annealing does not actually accept a state if the improvement is negative, which makes this algorithm not behave in a desired way.

Here is the section to determine whether it accepts a new state with greater function value.
https://github.com/scipy/scipy/blob/master/scipy/optimize/_dual_annealing.py#L260-L271
```
        pqv_temp = (self.acceptance_param - 1.0) * (
            e - self.energy_state.current_energy) / (
                self.temperature_step + 1.)
        if pqv_temp <= 0.:
            pqv = 0.
        else:
            pqv = np.exp(np.log(pqv_temp) / (
                1. - self.acceptance_param))
        if r <= pqv:
            # We accept the new location and update state
            self.energy_state.update_current(e, x_visit)
            self.xmin = np.copy(self.energy_state.current_location)
```
Here, `self.acceptance_param` directly comes from `accept` parameter with a range (-1e4, -5], `e - self.energy_state.current_energy` is positive since in this step the function value is greater than current state, and self.temperature_step + 1 is also positive.
In the end, `pqv_temp` is negative and the state is accepted with zero probability.

According to the tutorial page and the paper it refers, it can be
`pqv_temp = (self.acceptance_param - 1.0) * (
            e - self.energy_state.current_energy) / 
                self.temperature_step + 1.`, but I am not familiar with the notation and did not open a pull-request.

I inserted a debug message when it moves to a state with greater value, and found that it is never called, regardless of the temperature.

Could somebody check this and fix?

### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.3.0 1.15.4 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment]
@sgubianpm thanks for contributing `dual_annealing` to SciPy. Do you have a moment to take a look at this bug report? Could be a very simple fix!

**Comment by mdhaber** [comment]
This was reported again in gh-10892, and that was fixed by gh-12266.
