### ISSUE TITLE
Remove uses of `numpy.dual`?

### ISSUE THREAD

**Issue by person142** [scipy/scipy#10441]
This is possibly equally a NumPy issue. `numpy.dual` allows registering SciPy functions to overload NumPy functions. From the docstring of `numpy.dual` here:

https://github.com/numpy/numpy/blob/master/numpy/dual.py

```
Aliases for functions which may be accelerated by Scipy.

Scipy_ can be built to use accelerated or otherwise improved libraries
for FFTs, linear algebra, and special functions. This module allows
developers to transparently support these accelerated functions when
scipy is available but still support users who have only installed
NumPy.
```

Uses of dual still exist in SciPy:

```
$ git grep register_func
scipy/fft/__init__.py:from numpy.dual import register_func
scipy/fft/__init__.py:    register_func(k, eval(k))
scipy/fft/__init__.py:del k, register_func
scipy/linalg/__init__.py:from numpy.dual import register_func
scipy/linalg/__init__.py:        register_func(k, eval(k))
scipy/linalg/__init__.py:    register_func('pinv', pinv2)
scipy/linalg/__init__.py:del k, register_func
scipy/special/__init__.py:from numpy.dual import register_func
scipy/special/__init__.py:register_func('i0',i0)
scipy/special/__init__.py:del register_func
```

Is this something we want to continue supporting? From the git history it looks like dual hasn't had any real development since 2006:

https://github.com/numpy/numpy/commits/master/numpy/dual.py

**Comment by rgommers** [comment]
I think we should indeed get rid of that. I wasn't aware we did that at all, thought it was just `numpy.dual`.

Definitely shouldn't be in `scipy.fft`; the other ones need a quick check of what could break.

**Comment by peterbell10** [comment]
> Definitely shouldn't be in `scipy.fft`

I thought that it made sense to register the `scipy.fft` functions since:
- They match `numpy.fft`'s interface better than `fftpack`
- They are often more performant than `fftpack`

**Comment by rgommers** [comment]
Yes they do match, but I think if we want to get rid of `dual` completely, and there's little use of it anyway, then adding new usage of it doesn't seem to be helpful.

**Comment by person142** [comment]
(Not thinking through the details, but wouldn't it also break `__array_function__` since the SciPy functions won't have the right dispatches?)

**Comment by person142** [comment]
We are now down to:

```
$ git grep register_func
scipy/fft/__init__.py:from numpy.dual import register_func
scipy/fft/__init__.py:    register_func(k, eval(k))
scipy/fft/__init__.py:del k, register_func
scipy/linalg/__init__.py:from numpy.dual import register_func
scipy/linalg/__init__.py:        register_func(k, eval(k))
scipy/linalg/__init__.py:    register_func('pinv', pinv2)
scipy/linalg/__init__.py:del k, register_func
```

**Comment by peterbell10** [comment]
Should this be deprecated in numpy before removing SciPy's support for it?

**Comment by ilayn** [comment]
I did a very quick check for linalg parts and I didn't see any issues since the signatures mostly matched. We can cut the ties with `numpy.dual` without waiting for NumPy deprecation.

**Comment by rgommers** [comment]
+1 for doing this now. once NumPy deprecates it, our released versions start spewing deprecation warnings, so better sooner than later to minimize that.
