### ISSUE TITLE
BUG: scipy.spatial.transform.Rotation.match_vectors returns improper rotation matrix

### ISSUE THREAD

**Issue by sinanus** [scipy/scipy#10444]
Using `scipy.spatial.transform.Rotation.match_vectors` to find the rotation matrix between two sets of vectors, one occasionally gets an incorrect rotation matrix.

The reason is that `match_vectors` uses SVD to find the rotation matrix but does not check if the solution is proper right-handed coordinate system rotation. (see https://en.wikipedia.org/wiki/Kabsch_algorithm and references there in)

The problem can be fixed by applying the correction detailed in the wiki article. It is also implemented correctly in this package https://github.com/charnley/rmsd

The necessary correction can be done by inserting the following code snippet from RMSD package after line 1622 in scipy.spatial.transform.rotation.py

```python
    d = (np.linalg.det(u) * np.linalg.det(vh)) < 0.0

    if d:
        s[-1] = -s[-1]
        u[:, -1] = -u[:, -1]
```
I have confirmed that the above correction does work.

### Reproducing code example:

```python
In [2]: Vset1 = np.array([[ 0.02386536, -0.82176463,  0.5693271 ], 
   ...:        [-0.27654929, -0.95191427, -0.13183212]]) 
   ...:  
   ...: Vset2 = np.array([[ 0.89299824, -0.44372674,  0.07523779], 
   ...:        [ 0.60221789, -0.47564102, -0.64117021]])                        

In [3]: Rtruth = scipy.spatial.transform.Rotation.from_dcm(np.array([[ 0.4438560
   ...: 7, -0.81359972,  0.37556263], 
   ...:        [ 0.87343213,  0.29913243, -0.38423443], 
   ...:        [ 0.20027007,  0.49857325,  0.84339588]])) 
   ...:  
   ...: RSStruth = np.sum( (Vset2 - Rtruth.apply(Vset1))**2) 
   ...: print(RSStruth) 
   ...: print("Correct rotation maps the two sets of vectors on top of each othe
   ...: r")                                                                     
3.09512805474665e-16
Correct rotation maps the two sets of vectors on top of each other

In [4]: Rfit,_ = scipy.spatial.transform.Rotation.match_vectors(Vset2,Vset1) 
   ...: RSSfit = np.sum( (Vset2 - Rfit.apply(Vset1))**2) 
   ...: print(RSSfit) 
   ...: print("This is clearly incorrect")                                      
2.4009221108645833
This is clearly incorrect

```

### Scipy/Numpy/Python version information:

1.3.0 1.16.4 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

**Comment by pmla** [comment]
Thanks @sinanus.  I put your code into PR in #10531, which has now been merged.  I think this issue can be closed now.
