### ISSUE TITLE
SciPy GitHub Community Profile Checklist Incomplete

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#10453]
SciPy's [community profile](https://github.com/scipy/scipy/community) checklist on GitHub is incomplete. I was hoping we can get this completed before we submit the CZI grant, but I thought I should put up an issue before I start messing around.

- We already have a code of conduct, but GitHub sees it as incomplete. Would it help to embed the text of [`code_of_conduct.rst`](https://github.com/scipy/scipy/blob/master/doc/source/dev/conduct/code_of_conduct.rst) directly in [`CODE_OF_CONDUCT.md`](https://github.com/scipy/scipy/edit/master/.github/CODE_OF_CONDUCT.md) or otherwise direct GitHub to the full text? @ilayn, I see you worked on #8117 originally - thoughts?
- When I create a new issue on GitHub, the form is already populated with a template, yet GitHub thinks our issue template is incomplete. Perhaps that is because we only have a single issue template, but GitHub now asks for an `ISSUE_TEMPLATE` folder. If you have thoughts on what different templates we might want, please let me know.
- I don't think we have a PR template right now. What should go on one?

**Comment by larsoner** [comment]
For CoC the lowest maintenance solution is probably to create a minimal MD document containing a link to the SciPy dev doc URL.

For issue templates, I've found it useful to have a "blank" for experts, so whatever we have now plus blank is a low effort solution that is still useful.

For a PR template this one has been okay so far:

https://github.com/mne-tools/mne-python/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by mdhaber** [comment]
@larsoner we have a minimial MD document with a link; apparently it's not satisfying GitHub.
I will add a blank issue template.
The PR template looks good; I'll adapt it for SciPy.

**Comment by person142** [comment]
> If you have thoughts on what different templates we might want, please let me know.

A pretty typical split is "bug" vs. "feature request", which I've found to be pretty handy.

**Comment by mdhaber** [comment]
@person142 Thanks, yes - those are actually the two that GitHub recommends which I click "Add" next to the Issue Template item.

**Comment by larsoner** [comment]
> @larsoner we have a minimial MD document with a link; apparently it's not satisfying GitHub.

Maybe we should just 1) Add a comment to the top of the RST saying the RST is the one to edit, and then 2) use `pandoc` to convert the RST to MD. I don't anticipate the CoC having a lot of edits so hopefully the need to use `pandoc` to convert after any changes to the RST is not too onerous.

**Comment by ilayn** [comment]
This is really weird. I thought this has been fixed but apparently not. I'll also take a look if I can see any issues.

**Comment by pv** [comment]
It says somewhere Github only recognizes the exact texts of the few choices they offer as templates. So we can't do anything to it.

**Comment by mdhaber** [comment]
@larsoner Let's try that. 
@pv maybe since our language was adapted from some standard documents, it will recognize it?  The [pandas CoC](https://github.com/pandas-dev/pandas/community) is not one of the templates verbatim, but it is [marked as complete](https://github.com/pandas-dev/pandas/community).

**Comment by ilayn** [comment]
https://github.community/t5/How-to-use-Git-and-GitHub/Code-of-Conduct-is-present-in-repo-but-Insights-gt-Community-tab/td-p/15496

I think this is along the same lines what Pauli remembers. There is a pattern that GitHub specifically looks out for apparently.

**Comment by mdhaber** [comment]
Yeah, it didn't work. Oh well.
