### ISSUE TITLE
filter_design.py - iirfilter

### ISSUE THREAD

**Issue by RafaelsRamos** [scipy/scipy#10452]
I applied a Butter High Pass filter to my samples, if my sampling frequency was set to a 1000ish the results were wierd. So after some investigation, i think there might be something inconsistent in filter_design.py.
In iirfilter method, if variable the analog is set to false, we are redirected to bilinear_zpk
if not analog:
        z, p, k = bilinear_zpk(z, p, k, fs=fs)
but according to bilinear_zpk documentation, we should go there otherwise:
"Return a digital IIR filter from an analog one using a bilinear transform."

Thank you for your time!

**Comment by WarrenWeckesser** [comment]
That code *always* designs an analog filter.  Then, if the argument `analog` is False, it transforms the analog filter to a digital filter using the [bilinear transformation](https://en.wikipedia.org/wiki/Bilinear_transform).

> I applied a Butter High Pass filter to my samples, if my sampling frequency was set to a 1000ish the results were wierd.

If you can post a minimal, reproducible example, we can take a look at it and try to figure out what causes the unexpected results.

**Comment by WarrenWeckesser** [comment]
No response for a month, so closing.  @RafaelsRamos, if you still believe there is a problem, please let us know.
