### ISSUE TITLE
Unexpected divergence of solve_ivp in simple 2 nodes spring problem in 3D

### ISSUE THREAD

**Issue by AymericFerreira** [scipy/scipy#10468]
I want to model a mass-spring system with lot of nodes. 
My issue is about a divergence of all solvers (RK23, RK45, Radau, BDF and basic ODE) in a very simple case.

I model two nodes, one with infinite mass and another with a mass of 1kg and apply a force similar to gravity (9.81) on the node of mass 1kg.

When my node 0 (with infinite mass) is in position [0., 0., 0.] and my node 1 (with mass 1) is in position [0., 1., 0.] I got attended behavior of the springs.

When my node 0 (with infinite mass) is in position [0., 1., 0.] and my node 1 (with mass 1) is in position [0., 0., 0.] I got unexpected behavior of the springs and the mass 1 diverge to infinity.

I tried other cases like :
node 0 at [0., 0., 0.] and node 1 at [0., -1., 0.] and it works as attended.

I thought that the problem could be the solver as mentioned in the doc : 

> You should use the ‘RK45’ or ‘RK23’ method for non-stiff problems and ‘Radau’ or ‘BDF’ for stiff problems [9]. If not sure, first try to run ‘RK45’. If needs unusually many iterations, diverges, or fails, your problem is likely to be stiff and you should use ‘Radau’ or ‘BDF’. ‘

But it doesn't work with any solver I tried, am I using the solvers wrong ?

### Reproducing code example:

The code is a bit messy, I tried to isolate each functions.
y contains the position of the two nodes (one on each line) with columns corresponding to x, y, z.

y0 is just a copy for initial parameters.

W correspond to connectivity matrix, 1 if the two nodes are connected and 0 if not.

di correspond to the distance between each nodes at the beginning of the simulation, I assumed it was the stable state.

```
from matplotlib import pyplot as plt
import numpy as np
from scipy.integrate import solve_ivp, ode

from scipy.spatial.distance import cdist

# Common Parameters
T = 20
dt = 0.0001
k = 5

# Working parameters

y = np.array([[0., 0., 0.],  # 0
              [0., 1, 0.]])  # 1

y0 = y.copy().ravel()


W = np.array([[0, 1],
             [1, 0]])

di = cdist(y, y, "euclidean")

mass = 1 * np.ones(y.shape[0])
mass[0] = np.inf
mass[1] = 1



def calculate_a(y):
    global mass
    y = y.reshape((int(y.shape[0]/3), 3))
    return calculate_force(y) / mass[:, np.newaxis]


def calculate_force(y):
    global W
    global di
    global y0

    Force = np.zeros(y.shape)
    Force[1, 1] = 9.81

    return Force + compute_F_spring_vec(y)


def compute_F_spring_vec(y):
    global k
    global W
    global di

    d_inv = np.reciprocal(cdist(y, y, "euclidean"))
    d_inv[np.arange(np.shape(d_inv)[0]), np.arange(np.shape(d_inv)[0])] = 0
    op1 = np.dot(W, y)
    op2 = y * np.repeat(np.sum(W, axis=1), 3).reshape(y.shape)
    op3 = np.dot(W * di * d_inv, y)
    op4 = y * np.repeat(np.sum(W * di * d_inv, axis=1), 3).reshape(y.shape)
    F_spring = - k * (-op1 + op2 + op3 - op4)

    return F_spring

f = lambda t,y: (y.reshape(int(y.shape[0]/3), 3) + calculate_a(y) * t).ravel()

# Solve IVP
for method in ["RK23", "RK45", "Radau", "BDF"]:
    sol = solve_ivp(fun=f, t_span=(0, T), y0=y0, method=method, max_step=dt)
    plt.plot(sol.t, sol.y.T[:, 4], label=method)

# ODE for comparison

ODE = ode(f)
ODE.set_initial_value(y0)
ODE.set_integrator("dopri5", atol=1e-3, rtol=1e-6)
times = np.arange(dt, T, dt)
sol = np.hstack([ODE.integrate(time) for time in times])
sol = sol.reshape(int(sol.shape[0]/6), 6)
plt.plot(times, sol[:, 4], label="dopri5")

plt.legend()
plt.show()

```

Quick parameter tests and results :
Working parameters
```
y = np.array([[0., 0., 0.],  # 0
              [0., 1., 0.]])  # 1
```

![working1](https://user-images.githubusercontent.com/26620341/61252226-d6757e00-a72a-11e9-8c2f-b50e13311d2e.png)

```
y = np.array([[0., 0., 0.],  # 0
              [0., -1., 0.]])  # 1
```

![working2](https://user-images.githubusercontent.com/26620341/61252223-d5dce780-a72a-11e9-91d8-ded0a421faa0.png)

Non-Working parameters
```
y = np.array([[0., 1., 0.],  # 0
              [0., 0., 0.]])  # 1
```

![non-working1](https://user-images.githubusercontent.com/26620341/61252225-d6757e00-a72a-11e9-9d7a-ad6286baba05.png)

```
y = np.array([[0., -1., 0.],  # 0
              [0., 0., 0.]])  # 1
```
![non-Working2](https://user-images.githubusercontent.com/26620341/61252222-d5dce780-a72a-11e9-8cee-bcc14711ec0d.png)

```
y = np.array([[0., 1., 0.],  # 0
              [0., 2, 0.]])  # 1
```

![non-Working3](https://user-images.githubusercontent.com/26620341/61252601-0cffc880-a72c-11e9-98ca-a00d034e2b2c.png)

The problem seems to happen only when node 0 is not in position [0., 0., 0.]

I also tried to calculate the force of the spring with a non-vectorized version but the results are the same.

```
def compute_F_spring(X, W, d):
    F_spring = []
    for i in range(X.shape[0]):
        F_i = np.zeros(3)
        for j in range(X.shape[0]):
            if W[i, j]:
                F_i += -k * (np.linalg.norm(X[i, :] - X[j, :]) - d[i, j]) * (X[i, :] - X[j, :]) / np.linalg.norm(
                    X[i, :] - X[j, :])

        F_spring.append(F_i)

    return F_spring
```

### Error message:

No error messages

### Scipy/Numpy/Python version information:

1.3.0 1.16.4 sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)

**Comment by pv** [comment]
Based on the above, I don't see anything wrong with the solvers.

On the other hand, if you are trying to solve Newtonian mechanics, your problem formulation seems wrong.
