### ISSUE TITLE
Scaling of PSD calculated with signal.welch

### ISSUE THREAD

**Issue by sondrevf** [scipy/scipy#10471]
My issue is about the scaling of the PSD which is output from signal.welch and signal.periodogram (as the latter is using the former), when using scaling='density' (by default).
The PSD of a signal x(t) should be equal to |X(f)|^2, where X(f) is the fourier transform of x(t).

I believe that signal.welch adds a factor 2, compared to what it should be. But it is possible that it includes some extra though (only real frequencies, etc.) which is not described in enough detail for me in the documentation.

### Reproducing code example:

```
import numpy as np
from scipy import signal
Nt = 1024*2
x = np.random.normal(0,1,Nt)
f1 = np.fft.rfft(x,norm='ortho')
_,PSD1 = signal.welch(x)
print("OBS: Welch is normalized wrong, PSD must be divided by 2: %.2e , %.2e"%(
        np.mean(np.abs(f1)**2),np.mean(PSD1)))
```

### Scipy/Numpy/Python version information:
```
1.1.0 1.14.6 sys.version_info(major=3, minor=5, micro=6, releaselevel='final', serial=0)
```

**Comment by ewmoore** [comment]
`welch` and co return a onesided result when you provide a real valued time series.  If you want a two sided result, you'll want to set `return_onesided=False`.  For a one sided periodogram, the factor of 2 you have found is necessary to get the power correct.  This is demoed in the found in the docstring.

I'm going to close this, but conversation can certainly continue.
