### ISSUE TITLE
Phylogenetic Trees

### ISSUE THREAD

**Issue by martchellop** [scipy/scipy#10483]
### Phylogenetic Tree

Hello

I was researching Phylogenetic Trees as my undergraduate thesis and discovered that there are a lot of material and people wanting to use it for their projects but there isn't a good implementation in Python. Since Scipy has the implementation for Dendrogramas (which are similar) I thought it would be a good idea to propose it here. In my thesis I also discovered that people prefer the phylogenetic tree with more points than the Dendrograma, so there's a good opportunity here.

I have implemented the original algorithm for the tree for my college project and it's available in my [github](https://github.com/martchellop/Phylogenetic-Tree). Here are some screenshots of it's output given a distance matrix with increasing number of points. 

I would like some feedback about my work and what would have to improved in order for it to me submitted for Scipy

![1_B](https://user-images.githubusercontent.com/20330434/61501601-522f2f00-a9a6-11e9-94e4-9a4260ddd379.png)
_Tree with 5 points_ 

![2_B](https://user-images.githubusercontent.com/20330434/61501628-6d9a3a00-a9a6-11e9-8e2b-606af85f1dcb.png)
_Tree with 25 points_ 

![3_B](https://user-images.githubusercontent.com/20330434/61501629-71c65780-a9a6-11e9-921e-2b8f9419fbba.png)
_Tree with 100 points_

**Comment by rgommers** [comment]
Hi @martchellop, thanks for asking. Phylogenetic trees are too biology-specific to be considered for inclusion in SciPy I'm afraid. It would fit much better in http://etetoolkit.org/ or in biopython.

Both seem to have extensive material on this topic: 
http://etetoolkit.org/docs/latest/tutorial/tutorial_phylogeny.html?highlight=phylogenetic%20tree
https://biopython.org/wiki/Phylo
