### ISSUE TITLE
ENH: DCTs/DSTs for scipy.fft

### ISSUE THREAD

**Issue by mreineck** [scipy/scipy#10488]
Currently, `scipy.fft` falls back to `scipy.fftpack` for discrete sine and cosine transforms. This is problematic for performance reasons, but even more for accuracy reasons:
1) `scipy.fftpack`'s real-valued FFT (which is used internally by the DCTs/DSTs) tends to be very inaccurate for lengths containing large prime factors.
2) DCTs/DSTs of type I and IV use recurrences which further reduce accuracy (see, e.g. footnote 4 at http://www.fftw.org/fftw3_doc/Real-even_002fodd-DFTs-_0028cosine_002fsine-transforms_0029.html for further information)

I have added experimental support for DCTs/DSTs to `pypocketfft` (see the `sincos` branch at https://gitlab.mpcdf.mpg.de/mtr/pypocketfft). Switching to this implementation fixes issue 1) (and improves performance), but issue 2) is only addressed partially so far:
- transforms of type I are now very accurate, but use a double-length FFT internally, which makes them slower.
- transforms of type IV still use the recurrence since I have not found an alternative algorithm yet.

I'd be happy about feedback how to proceed: does it make sense to switch `scipy.fft` to the new implementation now, or should this wait until `pypocketfft`'s sine and cosine transforms are finalized?

The longer term goal (in my view) would be that `scipy.fftpack` can use `scipy.fft` internally. This would give a performance/accuracy benefit to all `scipy` users who are not actively switching from `scipy.fftpack` to `scipy.fft` for their existing codes (probably the vast majority).

**Comment by larsoner** [comment]
> does it make sense to switch scipy.fft to the new implementation now, or should this wait until pypocketfft's sine and cosine transforms are finalized?

I think it makes sense to switch once (ideally) the implementation is at least as fast and at least as accurate as what `fftpack` does. If it's a little bit slower (20%?) but more accurate, it's probably still worth it.

> The longer term goal (in my view) would be that scipy.fftpack can use scipy.fft internally. This would give a performance/accuracy benefit to all scipy users who are not actively switching from scipy.fftpack to scipy.fft for their existing codes (probably the vast majority).

Agreed that this would be nice. Also from a SciPy maintainer's perspective, getting rid of the Fortran code from `fftpack` would be good.

@peterbell10 has been talking about potentially working on some of these aspects, too. It looks like he has self-assigned this issue, so that might mean he's interested in porting those changes...?

**Comment by peterbell10** [comment]
> @peterbell10 has been talking about potentially working on some of these aspects, too. It looks like he has self-assigned this issue, so that might mean he's interested in porting those changes...?

First I plan on adding `dct`/`dst` to `_pocketfft` for benchmarking and comparing accuracy to `fftpack`.  If there's no significant trade off then it should be straight forward to remove most of `fftpack` and have it just call into `_pocketfft`.

I also had a look at the pseudo-differentials and convolutions. It looks like they only use the complex FFT so at the very least we could remove the real FFT, DCT and DST from the fortran code.

**Comment by mreineck** [comment]
> I think it makes sense to switch once (ideally) the implementation is at least as fast and at least as accurate as what fftpack does. If it's a little bit slower (20%?) but more accurate, it's probably still worth it.

The current situation is:
- all DCTs/DSTs are much more accurate than in `fftpack`, but type 4 transforms not quite as much as the others.
- all transforms benefit from the `pypocketfft` speedups for multi-D transforms and near-prime-size transforms. So for multi-D and weird sizes, the new transforms win.
- "smooth-sized" (i.e. length is a product of small primes) type I transforms are slower by a factor of roughly 2. I don't expect this to be fixable with reasonable effort (FFTW introduces extra codelets for this, but for pocketfft this is a bit over the top).

**Comment by mreineck** [comment]
So, to be clear: my plan is to provide type I transforms which are slower, but more accurate than the `fftpack` ones. For type IV I still hope that I can find an algorithm which is both accurate and as fast as `fftpack`, but if that is not the case I'd still prefer accuracy over speed.

**Comment by mreineck** [comment]
Section VIII B in http://www.fftw.org/fftw-paper-ieee.pdf seems to have helpful links. Unfortunately it may be necessary to use different algorithms for even- and odd-sized type IV transforms.

**Comment by mreineck** [comment]
Even-sized type IV transforms are now both fast and accurate.

**Comment by mreineck** [comment]
I have a working implementation for odd-sized transforms as well now. However this is not committed yet since it is derived from FFTW code. I asked the FFTW people if they are OK with me releasing the snippet under BSD (it is fairly small). If not, I'll work together with someone else to produce a clean-room reimplementation.

**Comment by mreineck** [comment]
Just got permission to use the code; we should be good to go!

**Comment by mreineck** [comment]
I think we can close this now, correct?
Should I open a new issue requesting removal of the `scipy.fftpack` Fortran code, or is it too early for such a change?

**Comment by peterbell10** [comment]
>Should I open a new issue requesting removal of the scipy.fftpack Fortran code, or is it too early for such a change?

I was considering it as part of this issue. I plan to open a PR relatively soon (maybe this week).

**Comment by mreineck** [comment]
Great! Let's do it this way then.
