### ISSUE TITLE
scipy.sparse.csc_matrix.toarray docstring is wrong

### ISSUE THREAD

**Issue by dwtang** [scipy/scipy#10497]
The docstring of `scipy.sparse.csc_matrix.toarray` indicates that the output array is default to be C-ordered. However specifying `order=C` gives a different result.

e.g.
```
In [8]: csc_matrix((2, 4)).toarray().strides
Out[8]: (8, 16)

In [9]: csc_matrix((2, 4)).toarray(order="C").strides
Out[9]: (32, 8)
```

**Comment by OmarMerghany** [comment]
> The docstring of `scipy.sparse.csc_matrix.toarray` indicates that the output array is default to be C-ordered. However specifying `order=C` gives a different result.
> 
> e.g.
> 
> ```
> In [8]: csc_matrix((2, 4)).toarray().strides
> Out[8]: (8, 16)
> 
> In [9]: csc_matrix((2, 4)).toarray(order="C").strides
> Out[9]: (32, 8)
> ```

I couldn't reproduce your case, it worked fine with me
![image](https://user-images.githubusercontent.com/13571281/64011226-8f491e00-cb1b-11e9-8c00-3ede5e0b9b1e.png)

**Comment by dwtang** [comment]
![Capture](https://user-images.githubusercontent.com/9681594/64038028-12bb3d00-cb25-11e9-9f99-65ea1c4d5fee.PNG)
It doesn't work on my python3.7 either, I guess it has something to do with the system.

**Comment by perimosocordiae** [comment]
This appears to be tied to the scipy version. I can reproduce @dwtang's results with scipy 1.3.1.

**Comment by perimosocordiae** [comment]
The real issue here is that the docstring is defined on the base class of both CSC and CSR formats, despite the default behavior being different for each: CSC -> fortran order, CSR -> C order.

We should update the docstring to either:

1. show the right default depending on the subclass
2. say that `order=None` makes no guarantee on the order of the result

I'm leaning toward the second option, personally.

**Comment by ewmoore** [comment]
I bet this came with #7081.  I'd say go with option 2.

**Comment by robroooh** [comment]
Is someone currently working on this issue? I would like to contribute :smile:

**Comment by rgommers** [comment]
@robroooh please go for it!
