### ISSUE TITLE
Spherical harmonics can be off by a sign

### ISSUE THREAD

**Issue by vyasr** [scipy/scipy#10499]
Under certain circumstances, the spherical harmonics in SciPy can be off by a sign. The sign flip affects both the real and imaginary components.

#### Reproducing code example:
```
import numpy as np
# Using the explicit formula shown in the documentation for `l` = 1, `m` = -1.
(1/2)*np.sqrt(3/np.pi/2)*np.exp(-1j*1.423931)*np.sin(-1.584277)
# (-0.05055430443675647+0.34174373247809015j)

from scipy.special import sph_harm
sph_harm(-1, 1, 1.423931, -1.584277)
# (0.05055430443675647-0.34174373247809015j)
```

#### Scipy/Numpy/Python version information:

1.3.0 1.16.4 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)

I also tested this on scipy 1.2.0 and received the same result.

**Comment by larsoner** [comment]
From the doc:

> Note that SciPy’s spherical harmonics include the Condon-Shortley phase [2] because it is part of lpmv.

I suspect we could just have a documentation problem where we don't write out the first few terms properly. Can you cross-check with standard definitions and confirm that it's a documentation problem as opposed to actually incorrect wrong values?

**Comment by vyasr** [comment]
That seems plausible, but it's not quite consistent with what I'm finding when I try and explicitly apply the expected correction. While it fixes cases when m < 0, it starts causing failures when m > 0. 

I think that you're definitely pointing to the right thing, though. My recollection is that the Condon-Shortley phase applies whether m is positive or negative; however, looking at the [code](https://github.com/scipy/scipy/blob/master/scipy/special/sph_harm.pxd), the `prefactor` that contains that phase is only being applied when m < 0. I'm not sure if the factorial terms should just exist in the negative case, that part seems likely to be correct, but I think that the `(-1)^m` should still be included when m > 0. 

Does that sound familiar to you, or am I forgetting something? It seems consistent with what I find [here](https://en.wikipedia.org/wiki/Associated_Legendre_polynomials) and [here](https://en.wikipedia.org/wiki/Spherical_harmonics#Condon%E2%80%93Shortley_phase), but I haven't looked at the exact derivations in a while so I may have forgotten something.

**Comment by larsoner** [comment]
Looking at the Wikipedia table the `-` signs only appear for `m > 0` terms:

https://en.wikipedia.org/wiki/Table_of_spherical_harmonics

It always takes me a long time to figure this stuff out.

I also thought it might be that we define the coordinate frames differently beyond just swapping the two variables, i.e. in terms of [colatitudinal angle vs elevation angle](https://en.wikipedia.org/wiki/Spherical_coordinate_system), but I don't think that's it.

**Comment by vyasr** [comment]
It seems likely that this is a convention issue, then. I can make the sign issues go away when I multiply only the positive m terms by (-1)^m, so that seems to address the discrepancy.  Also, my example was flawed because I was using an angle phi < 0, which is explicitly proscribed by the documentation and is probably introducing additional problems with respect to the signs that made it harder to debug. Sorry for the false alarm, I think this is just a misunderstanding w.r.t. the function conventions. Thanks for the help!

**Comment by larsoner** [comment]
Thanks for figuring it out!
