### ISSUE TITLE
Documentation of laplacian normalization unclear. 

### ISSUE THREAD

**Issue by benbo** [scipy/scipy#10505]
Documentation of laplacian normalization unclear. 

There are two common ways to normalize the Laplacian. Symmetric and random Walk normalization. 
L_sym = D^-1/2 L D^-1/2
L_rw = D^-1 L 

Neither the documentation nor the comments in the code indicate which normalization is used (L_sym according to the code).

https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.sparse.csgraph.laplacian.html

**Comment by pv** [comment]
#10526
