### ISSUE TITLE
BUG: scipy.stats RuntimeWarnings are platform dependent

### ISSUE THREAD

**Issue by bashtage** [scipy/scipy#10502]
RuntimeWarnings when encountering NaN are platform and possibly compiler dependent. 

#### Reproducing code example:
On Windows/ Python 3.7/conda/SciPy 1.3
```
$  python -c "import numpy;import scipy.stats;scipy.stats.norm.cdf(numpy.array([numpy.nan]));print('done')"
C:\Anaconda\lib\site-packages\scipy\stats\_distn_infrastructure.py:877: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
C:\Anaconda\lib\site-packages\scipy\stats\_distn_infrastructure.py:877: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
C:\Anaconda\lib\site-packages\scipy\stats\_distn_infrastructure.py:1748: RuntimeWarning: invalid value encountered in greater_equal
  cond2 = (x >= self.b) & cond0
done
```

On Linux (Ubuntu 18.04/WSL),Python 3.7/conda/SciPy 1.3

```
python -c "import numpy;import scipy.stats;scipy.stats.norm.cdf(numpy.array([numpy.nan]));print('done')"
done
```

#### Scipy/Numpy/Python version information:

```
1.3.0 1.16.4 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0) 
```

**Comment by rgommers** [comment]
Pretty sure that that's NumPy's behavior. Similar to https://github.com/numpy/numpy/issues/9568

**Comment by rgommers** [comment]
We've been solving or silencing these as we're encountering them. I don't think this issue is needed still. We're turning warnings into exceptions in CI, so they will be acted on when we see them. So I'll close this.
