### ISSUE TITLE
cKDTree GIL handling is incorrect

### ISSUE THREAD

**Issue by sturlamolden** [scipy/scipy#10514]
I believe #9915 has introduced errors in ```cKDTree``` GIL handling.

Declaring a C++ function ```nogil``` in Cython does not ensure that the GIL is automatically released and reaquired. It only declares that it is allowed to call the function in a nogil context.

Releasing the GIL in Cython is accomplished with a ```with nogil:``` statement. There is no such statement in ```ckdtree.pyx```. Therefore, ```cKDTree``` does not release the GIL and all multithreading code is now defective.

We must either revert #9915 to keep GIL release and exception translation in C++ or fix ```ckdtree.pyx``` to actually release the gil.

**Comment by sturlamolden** [comment]
ping @rainwoodman @rgommers

**Comment by sturlamolden** [comment]
Fortunately, fixing ckdtree.pyx is easy. I will take care of it.

**Comment by sturlamolden** [comment]
This is now fixed in #10516

**Comment by rainwoodman** [comment]
Ah. Yes there needs to be an explicit release! Totally forgot about that.

cython claims memoryviews do not need gil. Are you sure you need to
introduce new named variables in those cdefs in and around the thread
handler function?

**Comment by sturlamolden** [comment]
I am not sure. We do no use ```@boundscheck(False)``` so those indexing can raise exceptions. Maybe Cython will translate them? I do not get errors when those new pointers are not used, but I do get warnings about performence when memoryviews are indexed in the nogil context. Those warnings are silencenced by the new pointer variables, and that is good too, perhaps.

**Comment by sturlamolden** [comment]
I also took liberty to put the STL ```std::sort``` calls into ```nogil```. But here I am wondering about performance and #10216. We use quicksort. Is there any chance that we can get O(Nˆ2) here? Maybe we should use heapsort instead, i.e. ```std::make_heap``` and ```std::sort_heap?```?  

And following this line of thought, do we really a custom C++ heap in ```query.cxx```? Maybe we can just use STL?

**Comment by sturlamolden** [comment]
But that is for another PR :)

**Comment by peterbell10** [comment]
>We use quicksort. Is there any chance that we can get O(Nˆ2) here? Maybe we should use heapsort instead, i.e. `std::make_heap` and `std::sort_heap`??

You shouldn't be worried, `std::sort` is mandated by the standard to have O(N logN) complexity. Implementations will use some hybrid algorithm such as [introsort] that handles the degenerate cases gracefully and never falls back to O(N^2).

[introsort]: https://en.wikipedia.org/wiki/Introsort

**Comment by sturlamolden** [comment]
Good to know, one thing less to worry about :)
