### ISSUE TITLE
Total refcount issue in pypocketfft

### ISSUE THREAD

**Issue by pv** [scipy/scipy#10530]
`scipy.fft.fft` appears to increase total reference count, probably that of some global singleton.
It's not a memory leak, so low priority issue.

#### Steps to reproduce
Requirements: Python debug build, pybind11 (with this patch https://github.com/pybind/pybind11/pull/1860 to fix a different refcount issue):
```
>>> import sys, numpy as np, scipy.fft; x = np.array([1,2,3,4+1j,1,2,3,4+2j], dtype=complex)
>>> before = sys.gettotalrefcount(); y=scipy.fft.fft(x); after = sys.gettotalrefcount(); print(after-before)
8
>>> before = sys.gettotalrefcount(); y=scipy.fft.fft(x); after = sys.gettotalrefcount(); print(after-before)
3
>>> before = sys.gettotalrefcount(); y=scipy.fft.fft(x); after = sys.gettotalrefcount(); print(after-before)
3
```
However, what is strange is that if I move the `pocketfft_hdronly.h` include before `pybind11` here https://github.com/scipy/scipy/blob/310f562e58ca4bba72ed6068d7c12bd865d33607/scipy/fft/_pocketfft/pypocketfft.cxx#L15-L19 and recompile, I see
```
>>> import sys, numpy as np, scipy.fft; x = np.array([1,2,3,4+1j,1,2,3,4+2j], dtype=complex)
>>> before = sys.gettotalrefcount(); y=scipy.fft.fft(x); after = sys.gettotalrefcount(); print(after-before)
5
>>> before = sys.gettotalrefcount(); y=scipy.fft.fft(x); after = sys.gettotalrefcount(); print(after-before)
0
>>> before = sys.gettotalrefcount(); y=scipy.fft.fft(x); after = sys.gettotalrefcount(); print(after-before)
0
```
I don't understand at the moment why the refcount leak stops when changing the order of headers.
It also goes away if I comment out the `py::gil_scoped_release release` in `c2c_internal`. pybind11 bugs are possible, so not clear it's any issue here.

**Comment by peterbell10** [comment]
>I don't understand at the moment why the refcount leak stops when changing the order of headers. It also goes away if I comment out the py::gil_scoped_release release in c2c_internal. pybind11 bugs are possible, so not clear it's any issue here.

It sounds like this is definitely a `pybind11` issue. The include order dependency suggests that macros are probably involved. Looking at `py::gil_scoped_release`, I think that `pybind11::detail::get_internals` is probably a good place to start looking. Perhaps they leak a reference to their "internals" which appears to be a `PyCapsule` object.

**Comment by pv** [comment]
Never mind, the issue went away with `ccache --clear`, so probably some problem in it picking up the pybind11 headers were changed. Closing.
