### ISSUE TITLE
scipy.odr covx & covy / we & wd as matrices, don't work

### ISSUE THREAD

**Issue by jfy4** [scipy/scipy#10548]
My issue is about supplying a covariance matrix for the x and y data during fitting with scipy.odr.  For x and y data of length n, I should be able to supply two nxn matrices for both the x and y data, representing the covariance matrices for both, whose diagonal is the square of the standard deviation.  Supplying these matrices results in an error.

If instead a simple 1d-array of errors is supplied, the code fits fine.  It would be nice to have the ability to pass in 2d-arrays of covariance matrices for both x and y data.

#### Reproducing code example:

```
import numpy as np
import scipy.odr as spodr

x = np.linspace(0, 2*np.pi, 100) + np.random.normal(size=100, scale=0.25)
y = np.sin(x) + np.random.normal(size=len(x),  scale=0.25)

def fit(beta, x):
    return beta[0]*np.sin(beta[1]*x) + beta[2]
well_model = spodr.Model(fit)
x = np.linspace(0, 2*np.pi, 100) + np.random.normal(size=100, scale=0.25)
y = np.sin(x) + np.random.normal(size=len(x),  scale=0.25)

err = np.eye(100) # the simplest possible cov matrix
# err = np.diag(err) # too try the 1d case

data = spodr.Data(x, y, we=err, wd=err)
odr = spodr.ODR(data, well_model, beta0=[1,1,1])
out = odr.run()
```

#### Error message:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-78-2c562360d2a9> in <module>()
     16 data = spodr.Data(x, y, we=err, wd=err)
     17 odr = spodr.ODR(data, well_model, beta0=[1,1,1])
---> 18 out = odr.run()

/Users/judahunmuth-yockey/anaconda/lib/python2.7/site-packages/scipy/odr/odrpack.pyc in run(self)
   1101                 kwds[attr] = obj
   1102 
-> 1103         self.output = Output(odr(*args, **kwds))
   1104 
   1105         return self.output

ValueError: could not convert we to a suitable array
```

#### Scipy/Numpy/Python version information:
```
('1.2.1', '1.16.2', sys.version_info(major=2, minor=7, micro=15, releaselevel='final', serial=0))
```

**Comment by jfy4** [comment]
This didn't show up:
('1.2.1', '1.16.2', sys.version_info(major=2, minor=7, micro=15, releaselevel='final', serial=0))

**Comment by rkern** [comment]
The ODR algorithm in ODRPACK does not permit covariances _between_ measurements. The covariance matrices are for the cases of vector `x` and `y`. That is, if I were fitting `y = f(x[0], x[1])`, for `n_obs` points, then I could pass in `wd` of shape `(2, 2, n_obs)`; that is, `n_obs` number of `(2, 2)` (inverse) covariance matrices for each `x` 2-vector.

For this example, you want `we=np.ones(100)` and `wd=np.ones(100)`.

[Here's an example translated from the ODRPACK User's Guide that uses full covariance matrices](https://github.com/scipy/scipy/blob/master/scipy/odr/tests/test_odr.py#L179-L204). [Here's a more typical example with scalar `x` and `y` and just standard deviations like your example](https://github.com/scipy/scipy/blob/master/scipy/odr/tests/test_odr.py#L240-L249).

**Comment by jfy4** [comment]
Thanks for clarifying this for me.  That's too bad, since there are many cases where one's measurements are correlated, and it would be nice to take those into account during fits.
