### ISSUE TITLE
explicit references to numpy.random.mtrand.RandomState in the docs

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#10545]
numpy 1.17.0 changed their random module docs, which lead our doc build fails. Those were fixed in gh-10540 by linking directly to `numpy.random.mtrand.RandomState`, which is probably undesired (note the `mtrand`, which is an implementation detail). Apparently, this is a numpy intersphinx regression, which is hopefully fixed on the numpy end at some point. When it is, we should roll back and link to `numpy.random.RandomState`

cf https://github.com/scipy/scipy/pull/10540#issuecomment-515786196

**Comment by tylerjereddy** [comment]
Is our interim fix sufficiently bad that I shouldn't backport it to 1.3.x?

**Comment by ev-br** [comment]
IMO, the whole issue is relatively minor. So it's up to RM's convenience. If backporting it (or not backporting it) makes your job easier, it's fine either way.

**Comment by andyfaff** [comment]
@rgommers is this rollback-able now?

**Comment by larsoner** [comment]
It looks like if we switch to using numpy.org/devdocs it should be

**Comment by rgommers** [comment]
Indeed. And switching the intersphinx mapping in `doc/source/conf.py` is a useful change anyway

**Comment by j-bowhay** [comment]
close by #11396
