### ISSUE TITLE
Document implicit sum in csr_matrix() constructor

### ISSUE THREAD

**Issue by aikho** [scipy/scipy#10558]
My issue is about csr_matrix().

#### Reproducing code example:

```
from scipy.sparse import csr_matrix
csr_matrix(([1,1,1],([0,0,0],[0,0,0])), shape=(1,1)).todense()
```
Result: matrix([[3]])
Expected: matrix([[1]])
This is an implicit behaviour. I can not find anything about this in the documentation.
I assume, there are 3 options:
1. Raise a error.
2. Use only last value in the list.
3. Document current behaviour.

**Comment by perimosocordiae** [comment]
This is indeed the intended behavior, and it's documented (albeit not very prominently) here:
https://docs.scipy.org/doc/scipy/reference/sparse.html#example-2

I agree that we should make this more prominent in the docs.

**Comment by aikho** [comment]
I think, it will be ok if you add notice right to https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html

**Comment by sameshl** [comment]
@aikho I would love to work on this. Do you want me to add the above example as a notice to https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html

**Comment by aikho** [comment]
@sameshl would be great to add something similar to example 2 from https://docs.scipy.org/doc/scipy/reference/sparse.html#example-2 right to https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html

**Comment by erheron** [comment]
Hi! My guess is that @sameshl is not working on this, and wouldn't be angry if I'll make the PR

**Comment by rgommers** [comment]
@erheron please go ahead!
