### ISSUE TITLE
Issue upgrading scipy

### ISSUE THREAD

**Issue by lmartins30** [scipy/scipy#10565]
I'm trying to upgrade scipy using 'pip install --upgrade scipy' but the error in the pciture is the output.

Already tried things as 'trusted host' but they didn't work as well.
![67439489_457668465070279_2636665467938275328_n](https://user-images.githubusercontent.com/52186112/62236820-32d0d280-b3a6-11e9-926b-cd06abb81b32.jpg)

**Comment by pv** [comment]
There's an issue either in your network connection or SSL configuration.
(Not a scipy issue --- closing since this is not the right forum for this discussion.)

**Comment by lmartins30** [comment]
When I run 'pip install --upgrade scipy --trusted-host pypi.org --trusted-host files.pythonhosted.org' it downloads the files of scipy 1.3.0 - 23.6MB. But it stucks at 'Installing build dependencies.../', It's on this line for about 30 minutes.
