### ISSUE TITLE
Need help upgrading SciPy

### ISSUE THREAD

**Issue by lmartins30** [scipy/scipy#10578]
I'm trying to upgrade my SciPy but i'm having some issue. Now, apparently my Ubuntu doesn't have lapack and blas. How can I do this upgrade then?

Thanks in advance.

**Comment by ev-br** [comment]
There is lots of info on how to install blas/lapack on ubuntu, e.g. https://askubuntu.com/questions/623578/installing-blas-and-lapack-packages

You're welcome to use this tracker for reporting scipy bugs or filing enhancement requests. Since this is not one of those, I'm going to close it.
