### ISSUE TITLE
check assumptions before running statistical tests?

### ISSUE THREAD

**Issue by mathematicalmichael** [scipy/scipy#10579]
**Is your feature request related to a problem? Please describe.**
Problem with code? No. Problem with how people might use it? Maybe.
Right now, you can call `scipy.stats.ttest_ind` (for example) on two samples with different sample/population variances, violating the assumption stated in the documentation: 
> This test assumes that the populations have identical variances by default

**Describe the solution you'd like**
Check the assumption and raise a warning if violated, so the user knows to _not take the test result seriously_. 

**Describe alternatives you've considered**
Doing this for other tests. Then again, people could just read the documentation. But let's face it... most will find a solution to "two-sample t-test scipy" online, run their samples through there, see `p<0.05` and call it a day. 

**Additional context (e.g. screenshots)**
Math person here... helped someone revisit results from a statistics project. Everything seemed to imply a lack of significant differences, except the results received from the t-test that the textbook said was useful in situations like this one. 

If it's not the place of the developers to make sure the code is being used correctly, so be it, I understand. Feel free to close the issue in that case, but I couldn't find a discussion along these lines so I thought I would start one. =D

**Comment by josef-pkt** [comment]
> If it's not the place of the developers to make sure the code is being used correctly

I think that's up to the user for subject issues, i.e. is the test and the underlying assumptions appropriate for the specific case.

The main problem here is how to evaluate that the variances are the same. They will never be exactly the same. Using a equality of variance hypothesis test to decide, turns this into a pre-test estimator with different statistical properties. In many cases they don't have good properties. Test on equality of variances are not very powerful in small samples and depend even more on the underlying assumptions, i.e. are less robust to violating these assumptions than the t-test itself.

A better recommendation is that if the user is not sure that the variances are the same, then go for the version of the test that is robust to different variances. It might loose some power, but will still be correct if variances differ.

(In the more general case for OLS, hypothesis tests can be made robust to differences in variances by using sandwich, heteroscedasticity robust standard errors. Some econometrics textbooks recommend to always use those. However, in small samples, they can be worse than using the usual nonrobust standard errors even if those are "wrong", they can just be less wrong in small samples.)

**Comment by mathematicalmichael** [comment]
oh that's a very good point... the threshold would be tricky to define, if possible at all. 5% relative difference? In any case, I think it ultimately is probably up to the user to figure this out and use the `equal_var=False` flag on their own. Just seems like maybe the `False` option would be a more reasonable default... but then again, standardizing data is common... (in which case, running the test would still be a wrong thing to do since the means have been set to zero). 
Thanks!

**Comment by josef-pkt** [comment]
>  Just seems like maybe the False option would be a more reasonable default

I agree with this, however it would require a break with backwards compatibility and it would be less traditional, i.e. users are likely less familiar with it and complain that they don't get the "standard" t-test.

Another problem is that there are many directions in which assumptions could be violated and it is not clear what the appropriate more robust version should be for the default.

(same reasons that statsmodels uses the `nonrobust` version by default, and has various robust versions for standard errors as option.)
