### ISSUE TITLE
scipy.fft and numpy.fft inconsistency when axes=None and shape is specified

### ISSUE THREAD

**Issue by grlee77** [scipy/scipy#10588]
My issue is about ...

The following corner case came up when I was testing Peter's CuPy PR for `scipy.fft`. Currently, n-dimensional transforms in `scipy.fft`do not allow the following use case that is supported by `numpy.fft`.

#### Reproducing code example:

```Python
scipy.fft.ifftn(np.ones((2, 3, 4)), s=(1, 5), axes=None)
```
I.e. specifying a `shape` when `axes=None` causes the following error:

```ValueError: when given, axes and shape arguments have to be of the same length```

In NumPy, however, `axes` gets set to the last `len(s)` axes and the transform proceeds without error.

#### Error message:

```
----> 1 scipy.fft.ifftn(np.ones((2, 3, 4)), s=(1, 5), axes=None)

~/my_git/scipy/scipy/fft/_backend.py in __ua_function__(method, args, kwargs)
     21         if fn is None:
     22             return NotImplemented
---> 23         return fn(*args, **kwargs)
     24 
     25 

~/my_git/scipy/scipy/fft/_pocketfft/basic.py in c2cn(forward, x, s, axes, norm, overwrite_x)
    139     tmp = _asfarray(x)
    140 
--> 141     shape, axes = _init_nd_shape_and_axes(tmp, s, axes)
    142     overwrite_x = overwrite_x or _datacopied(tmp, x)
    143 

~/my_git/scipy/scipy/fft/_pocketfft/helper.py in _init_nd_shape_and_axes(x, shape, axes)
     57 
     58         if len(axes) != len(shape):
---> 59             raise ValueError("when given, axes and shape arguments"
     60                              " have to be of the same length")
     61 

  ...
```

**Comment by peterbell10** [comment]
I think this should be safe to add since it's just removing an error. I'll make a PR for it.
