### ISSUE TITLE
No warning on PchipInterpolator changing from bernstein base to local power base

### ISSUE THREAD

**Issue by Croxa** [scipy/scipy#10597]
This change improves usability, so thank you for making it. However it broke my code and finding the root cause wasn't easy for me, which is why I've started this issue.

In version 1.2 if a "local power basis" representation of the results from a PchipInterpolator were needed the following code worked:
```
CubicSpline.from_bernstein_basis(PchipInterpolator(x, y)).coefficients
```
As of 1.3 this will not raise an error or a warning but it will give nonsense results. So maybe a warning would be nice if from_bernstein_basis is called on a PchipInterpolator? I don't know if that's good coding practice.

Also I didn't find anything on the basis-change on the PchipInterpolator documentation site. I guess I could have inferred it from the release notes because PchipInterpolator is now a subclass of CubicHermiteSpline, but I didn't catch that before finding the relevant info in the source code. 

#### Scipy/Numpy/Python version information:
change from 
```
1.2.1 1.16.3 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```
to
```
1.3.0 1.16.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
```

Thank you for your great work!

**Comment by ev-br** [comment]
Thanks for the report.
This all was meant to be an implementation detail, as BPoly was meant to be a drop-in replacement. Obviously, that did not work, and implementation details leaked. 

A warning is not really appropriate, it should just fail: https://github.com/scipy/scipy/pull/10600
On the user side, conversions should then be wrapped into a try-except clause:

```
pch = PchipInterpolator(...)
try:
    spl = CubicSpline.from_bernstein_basis(pch)
except TypeError:
    # already a PPoly instance, nothing to do
    pass
```

**Comment by Croxa** [comment]
Ah, very informative. Thank you!
