### ISSUE TITLE
scipy.stats.ttest_1samp should support alternative hypothesis

### ISSUE THREAD

**Issue by emilmirzayev** [scipy/scipy#10595]
**Is your feature request related to a problem? Please describe.**
In R one can use alternative hypothesis when using ttest. Example:
```r
b=data.frame(iris)
t.test(b$Sepal.Length, mu=5.6, alternative="greater")
```
However, it is not possible with `scipy.stats.ttest_1samp:
```python
import seaborn as sns
from scipy import stats

df = sns.load_dataset("iris")
stats.ttest_1samp(df.sepal_length, popmean= 5.6, alternative = "greater")
TypeError: ttest_1samp() got an unexpected keyword argument 'alternative'
```

**Describe the solution you'd like**
It should support alternative hypothesis via `alternative` keyword as it does in `scipy.stats.binom_test`

**Comment by pvanmulbregt** [comment]
Looking at your R example, it appears that  two-sided probability is just twice the one-sided upper-tail probability:
```
> b=data.frame(iris)
> t.test(b$Sepal.Length, mu=5.6, alternative="greater")

	One Sample t-test

data:  b$Sepal.Length
t = 3.599, df = 149, p-value = 0.0002171
alternative hypothesis: true mean is greater than 5.6
95 percent confidence interval:
 5.731427      Inf
sample estimates:
mean of x 
 5.843333 

> t.test(b$Sepal.Length, mu=5.6)

	One Sample t-test

data:  b$Sepal.Length
t = 3.599, df = 149, p-value = 0.0004342
alternative hypothesis: true mean is not equal to 5.6
95 percent confidence interval:
 5.709732 5.976934
sample estimates:
mean of x 
 5.843333 
```

The code in https://github.com/scipy/scipy/blob/09feb51dede02257cc0cdee2b39b0786fd1c0ab5/scipy/stats/stats.py#L4318 just doubles the  one-sided upper-tail probability.
Is your request to return just the upper-tail probability for `alternative="greater"`?

**Comment by emilmirzayev** [comment]
Not only, but yes. R supports also `less` option.
What I propose is to make it similar to R's.

I see from your reference code that it can be easy to implement. If so, I think I can do that  and make a PR

**Comment by pvanmulbregt** [comment]
@emilmirzayev  That would be great!  There are several examples of functions in `stats.py` (`brunnermunzel`, `fisher_exact`, `kstest`) which take the `alternative` keyword, so any of their implementations/docstrings can be used as guidance.

**Comment by emilmirzayev** [comment]
@pvanmulbregt , I just got time to come back to this.

I will see what I can do in upcoming days :)

**Comment by farmeh** [comment]
I'm following .
