### ISSUE TITLE
Replacing `input` parameter in ndimage functions

### ISSUE THREAD

**Issue by jakirkham** [scipy/scipy#10592]
The [`scipy.ndimage` functions]( https://docs.scipy.org/doc/scipy/reference/ndimage.html ) frequently use `input` as an argument to functions. In addition to this being a vague descriptor (what kind of input?), it also overlaps with [the builtin `input` function]( https://docs.python.org/3/library/functions.html#input ). It would be preferable to rename this parameter to something that is clearer and does not overlap with Python builtins.

cc @jni @GenevieveBuckley

**Comment by larsoner** [comment]
Same feeling here as for sum in #10593

**Comment by jakirkham** [comment]
I'm less clear on how that approach applies here (given we are talking about argument names). Would you be able to clarify things a bit more?

**Comment by larsoner** [comment]
Oh I missed that this had to do with arguments rather than a function name like in #10593.

Sadly there are a lot of instances of overwriting builtins with `kwarg` names in SciPy. I'm not convinced it's worth the deprecation pain to rename them. We could for example rename them in a backward compatible way like:
```
def func(x, input_clearer, ..., input=None):
    ...
    if input is not None:
        input_clearer = input
```
The downside is that it makes the signature a bit uglier.

**Comment by jni** [comment]
I'd be :+1: on deprecating these signatures as you suggest, @larsoner. It's nice and pain-free. (iirc SciPy is Py3+ now, which means you could make it a keyword-only argument, which I think is important in this case.)

**Comment by rgommers** [comment]
No, as @larsoner says, this is a common issue in many places. This particular one has been proposed and rejected multiple times. It isn't worth breaking backwards compatibility here, and I definitely would not like to see it done everywhere in scipy, numpy and the wider ecosystem - that'd be a _lot_ of churn for little real-world benefit.

**Comment by rfezzani** [comment]
See  #10010.

**Comment by jni** [comment]
Good link, @rfezzani. @rgommers et al, I guess this can be closed. I myself have come to accept that this won't be fixed, and that the value of it being fixed is small anyway. =)

**Comment by rgommers** [comment]
Thanks for the input all. Closing.
