### ISSUE TITLE
Why M > 4

### ISSUE THREAD

**Issue by Skillnter** [scipy/scipy#10590]
https://github.com/scipy/scipy/blob/master/scipy/optimize/_differentialevolution.py

> ("The population supplied needs to have shape" (M, len(x)), where M > 4.")

I am just wondering why the value of M is supposed to be more than 4? I tried to figure out the details but I Kinda failed to get the explanation. Can anyone be kind enough to explain why the lower limit to be around 5?

**Comment by andyfaff** [comment]
What is this question related to?

**Comment by Skillnter** [comment]
> What is this question related to?

https://github.com/scipy/scipy/blob/master/scipy/optimize/_differentialevolution.py

**Comment by andyfaff** [comment]
The reason why M has to be greater than 4 is because the `Rand2` evolution strategy needs at least 5 population members.
