### ISSUE TITLE
SLSQP optimization variables limit

### ISSUE THREAD

**Issue by subodhkalia** [scipy/scipy#10607]
Hello all,

I am trying to optimize a problem with ~30,000 variables using scipy optimize SLSQP. I get the maximum allowed dimension error from the SLSQP python code. I suspect that it is some sort of workspace memory allocation related error. The screenshot is attached below.

When I reduced the variables to ~4000, SLSQP works.

As per the original paper, there is no such limit on the optimization variables. SLSQP might be slow for a large number of variables but it should work ideally. I don't want to change the optimizer at this stage. Is there any way to make SLSQP work with 30,000+ variables.

Thanks,

Subodh.

![image](https://user-images.githubusercontent.com/12223074/62641108-e9860300-b910-11e9-80a9-361dedd991bf.png)

**Comment by peterbell10** [comment]
`len_w` is probably > 2**32 and the `site-packaged` path suggests you're using 32-bit python. Perhaps try again with 64-bit python.

**Comment by subodhkalia** [comment]
Using 64-bit python, this error goes away.

Thank you so much!!

**Comment by raulqf** [comment]
Which amount of memory do you need for processing 30K variables? I am trying ~25000 variables and it crashes because cannot allocate 42GB but I guess is more than that, after reading the code.
