### ISSUE TITLE
Minor documentation addition/update

### ISSUE THREAD

**Issue by RowandV** [scipy/scipy#10605]
Hope this is the rigth place. In "https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.interface.html#arrays-interface" type 'd' double is missing. Could that be added to the 'typestr' list?

**Comment by rgommers** [comment]
not really, that would be the numpy issues tracker. the current version looks correct to me though, it matches `np.dtype.kind`. `'d'` is covered by `'f'`, there's only one letter for floating-point types.
