### ISSUE TITLE
Reference for scipy.stats.alpha

### ISSUE THREAD

**Issue by thuster** [scipy/scipy#10619]
The "alpha" distribution in scipy.stats does not have a reference, and I was not able to find any such distribution (either by name or pdf) in searches in, e.g., 
Google, Wikipedia (https://en.wikipedia.org/wiki/List_of_probability_distributions), or the Zwillinger & Kokoska book.  

It appears to be heavy-tailed, but not any specific instance of a Levy alpha-stable I could find.  It would be helpful to have a reference to its theoretical underpinnings.  

Thanks!

**Comment by WarrenWeckesser** [comment]
Thanks for looking into this.  SciPy's alpha distribution is the same as the one described at https://itl.nist.gov/div898/software/dataplot/refman2/auxillar/alppdf.htm.  That page gives these references:

*  Johnson, Kotz, and Balakrishnan (1994), "Continuous Univariate Distributions--Volume 1", Second Edition, John Wiley and Sons, p. 173.
* Salvia (1985), "Reliability applications of the Alpha Distribution", IEEE Transactions on Reliability, Vol. R-34, No. 3, pp. 251-252.

I don't have access to those, so I can't verify that the references are correct.

**Comment by WarrenWeckesser** [comment]
@thuster, it looks like the references that I gave above are good.  Would you be interested in creating a pull request to add those to the documentation of `alpha`?

**Comment by thuster** [comment]
I'm not set up at the moment to quickly do the pull request, but I appreciate you tracking down the sources.  Thanks!

**Comment by WarrenWeckesser** [comment]
OK, I'll get the references into the docstring.  Thanks again for looking into this.
