### ISSUE TITLE
Scipy python>3.6 Windows wheels don't ship msvcp*.dll

### ISSUE THREAD

**Issue by pv** [scipy/scipy#10628]
Scipy wheels for Python > 3.6 don't ship `msvcp*.dll`:

https://github.com/MacPython/scipy-wheels/blob/925d24f0ce5a86dd1452afefbce2263866f3d1fa/appveyor.yml#L169-L185

This is the C++ part of the msvc runtime. Python.org python ships the `vcruntime140.dll` (C runtime), but not the C++ one. I guess in most cases on desktop machines, the c++ runtime is already installed as many software probably needs it.

I think the omission may have been accidental --- if so, here's an issue ticket. I'm not sure whether the DLL should be shipped in the end, given that this is a corner case.

#### Reproducing code example:

E.g. new windows VM, install Python from Python.org, and install scipy via `pip install scipy`.
Then, `import scipy.sparse` fails with DLL error. This is fixed by downloading and installing the latest msvcrt package.

#### Scipy/Numpy/Python version information:

Scipy Python Windows wheels for Python > 3.6

**Comment by tylerjereddy** [comment]
I wonder if the language of the wheels PEP(s) would guide us in deciding on this.

**Comment by pv** [comment]
Another case of this issue: https://github.com/scipy/scipy/issues/9230#issuecomment-540477379

**Comment by rgommers** [comment]
> I think the omission may have been accidental --- if so, here's an issue ticket. 

You mean on our side, or on Python's side?

If we should be shipping it, that means that all projects using C++ should be shipping it right?

**Comment by pv** [comment]
On our side, yes. I think pypi binaries should target the minimal Python.org Windows installation, which means no MSVCRT installed apart from what Python brings with it.

**Comment by pv** [comment]
... implying they should ship whatever compiler RT libraries relevant. We did this up to py3.6, and I think just forgot to update that part of the appveyor build script for 3.7.

**Comment by rgommers** [comment]
Ah, I didn't realize/remember that we did that. Makes sense now, thanks @pv
