### ISSUE TITLE
CircleCI Error

### ISSUE THREAD

**Issue by jwd0023** [scipy/scipy#10626]
Currently getting a CircleCI error that I don't think is related to my changes in #10625. 

Am I wrong, or is there an issue with CircleCI?

Error is `scipy/fft/_pocketfft/pypocketfft.cxx:15:31: fatal error: pybind11/pybind11.h: No such file or directory`.

**Comment by peterbell10** [comment]
Your pull request is based on an old commit from before pybind11 was added as a dependency. Rebase your branch on the latest master the error will be fixed.
