### ISSUE TITLE
Travis does not pick up wheel for scipy 1.3.1 for Python 3.7

### ISSUE THREAD

**Issue by jorisvandenbossche** [scipy/scipy#10637]
Not really sure what is going on, but CI on the geopandas project started to fail since scipy 1.3.1 release. 

We are creating a conda environment (based on this yaml file: https://github.com/geopandas/geopandas/blob/master/ci/travis/37-latest-defaults.yaml), where `mapclassify` is installed via pip, and this requires scipy. 

In the travis log (https://travis-ci.org/geopandas/geopandas/jobs/570422723), there is:

```
Collecting scipy>=0.11 (from mapclassify->-r /home/travis/build/geopandas/geopandas/ci/travis/condaenv.553d61zw.requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/ee/5b/5afcd1c46f97b3c2ac3489dbc95d6ca28eacf8e3634e51f495da68d97f0f/scipy-1.3.1.tar.gz (23.6MB)
```

so for some reason it is downloading the source release (scipy-1.3.1.targ.gz), while there clearly are already wheels uploaded on pypi (manylinux wheels for python 3.7: https://pypi.org/project/scipy/1.3.1/#files)

This only seems to happen for python 3.7, as one of the other environments with python 3.6 which also tries to install scipy using pip correctly gets the wheel (eg https://travis-ci.org/geopandas/geopandas/jobs/570422722#L490)

**Comment by andyfaff** [comment]
Looking at the yaml file there's no entries for numpy or scipy. From the logfile numpy gets installed in the conda environment but something seems to go wrong in the install, because it's not importable. It might be worth explicitly using both scipy and numpy in the environment file.

I don't think this is an issue with scipy per-se, but an issue with the CI setup that's being used.  As such, I'm going to close the issue.
One way of investigating further (apart from hammering the CI with trying things) is to use Docker and a Xenial image to try and repeat the problems you're seeing. Also, try and install scipy directly with pip and see if there's an issue.

**Comment by jorisvandenbossche** [comment]
> From the logfile numpy gets installed in the conda environment but something seems to go wrong in the install, because it's not importable

AFAIK, this is not the numpy from conda, it is the numpy installed in the temporary build environment of pip when trying to build a wheel for scipy.

> It might be worth explicitly using both scipy and numpy in the environment file.

Yes, sure, that is a solution to fix *our* CI problem (ensuring conda already installed it, so the pip install of mapclassify does not need to install scipy). 

But this still seems like a general problem to me?

**Comment by jorisvandenbossche** [comment]
I can reproduce this locally on Ubuntu 18.04, in a new conda environment.

Recreating the environment as done on travis (but without the pip install of scipy step within the creation of the conda environment):

```
$ conda env create --file=ci/travis/37-latest-defaults.yaml
....
$ conda activate test2
$ which pip
/home/joris/miniconda3/envs/test2/bin/pip
$ pip install scipy
7.4.0
Collecting scipy
  Downloading https://files.pythonhosted.org/packages/ee/5b/5afcd1c46f97b3c2ac3489dbc95d6ca28eacf8e3634e51f495da68d97f0f/scipy-1.3.1.tar.gz (23.6MB)
     |████████████▍                   | 9.1MB 2.2MB/s eta 0:00:07^C
ERROR: Operation cancelled by user
```

so also here it tried to download the source archive and not the wheel.

Is there a way to check manylinux compatibility of a system (in this specific environment) ?

**Comment by matthew-brett** [comment]
What do you get for `python -c "import distutils.util; print(distutils.util.get_platform())"` ?

**Comment by jorisvandenbossche** [comment]
(`test2` is the name of the conda env that recreated the travis one)

```
(test2) joris@joris-XPS-13-9380:~/scipy$ which python
/home/joris/miniconda3/envs/test2/bin/python
(test2) joris@joris-XPS-13-9380:~/scipy$ python -c "import distutils.util; print(distutils.util.get_platform())" 
linux-x86_64
```

**Comment by jorisvandenbossche** [comment]
Creating a minimal conda env with just python 3.7 and pip (`conda create -n test-scipy-wheel python=3.7 pip`) works fine, doing a `pip install scipy` gets the wheel. So something in the other environment somehow influences that pip does not want to install a wheel for scipy .. Any idea how another installed package can influence this?

**Comment by matthew-brett** [comment]
I noticed this warning in your log file : https://travis-ci.org/geopandas/geopandas/jobs/570422723#L378 - is it relevant?

**Comment by jorisvandenbossche** [comment]
> I noticed this warning in your log file : https://travis-ci.org/geopandas/geopandas/jobs/570422723#L378 - is it relevant?

Normally not, it's something I should solve, but it is just conda saying that you should add pip explicitly instead of relying on conda doing it for you.

But I pinned it down further to a difference between defaults and conda-forge ...

Creating a minimal env with defaults, then installing scipy with pip gets the source tar.gz:

```
(base) joris@joris-XPS-13-9380:~/scipy$ conda create -n test-scipy-wheel2 python=3.7 pip -c defaults
...
(base) joris@joris-XPS-13-9380:~/scipy$ conda activate test-scipy-wheel2
(test-scipy-wheel2) joris@joris-XPS-13-9380:~/scipy$ conda list
# packages in environment at /home/joris/miniconda3/envs/test-scipy-wheel2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
ca-certificates           2019.5.15                     1  
certifi                   2019.6.16                py37_1  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
ncurses                   6.1                  he6710b0_1  
openssl                   1.1.1c               h7b6447c_1  
pip                       19.1.1                   py37_0  
python                    3.7.4                h265db76_0  
readline                  7.0                  h7b6447c_5  
setuptools                41.0.1                   py37_0  
sqlite                    3.29.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
wheel                     0.33.4                   py37_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
(test-scipy-wheel2) joris@joris-XPS-13-9380:~/scipy$ which pip
/home/joris/miniconda3/envs/test-scipy-wheel2/bin/pip
(test-scipy-wheel2) joris@joris-XPS-13-9380:~/scipy$ pip install scipy
7.4.0
Collecting scipy
  Downloading https://files.pythonhosted.org/packages/ee/5b/5afcd1c46f97b3c2ac3489dbc95d6ca28eacf8e3634e51f495da68d97f0f/scipy-1.3.1.tar.gz (23.6MB)
     |█████▎                          | 3.9MB 425kB/s eta 0:00:47^C
ERROR: Operation cancelled by user
```

Doing exactly the same with conda-forge gets the wheel:

```
(base) joris@joris-XPS-13-9380:~/scipy$ conda create -n test-scipy-wheel3 python=3.7 pip -c conda-forge
...
(base) joris@joris-XPS-13-9380:~/scipy$ conda activate test-scipy-wheel3
(test-scipy-wheel3) joris@joris-XPS-13-9380:~/scipy$ conda list
# packages in environment at /home/joris/miniconda3/envs/test-scipy-wheel3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
bzip2                     1.0.8                h516909a_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
pip                       19.2.1                   py37_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
sqlite                    3.29.0               hcee41ef_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1005    conda-forge
(test-scipy-wheel3) joris@joris-XPS-13-9380:~/scipy$ which pip
/home/joris/miniconda3/envs/test-scipy-wheel3/bin/pip
(test-scipy-wheel3) joris@joris-XPS-13-9380:~/scipy$ pip install scipy
Collecting scipy
  Downloading https://files.pythonhosted.org/packages/94/7f/b535ec711cbcc3246abea4385d17e1b325d4c3404dd86f15fc4f3dba1dbb/scipy-1.3.1-cp37-cp37m-manylinux1_x86_64.whl (25.2MB)
     |███▉                            | 3.0MB 3.4MB/s eta 0:00:07^C
ERROR: Operation cancelled by user
```

**Comment by jorisvandenbossche** [comment]
OK, and I see, the main difference between both envs is probably the difference in pip version: 19.1.1 (on defaults, where it fails) vs 19.2.1 (on conda-forge, where it succeeds)

**Comment by jorisvandenbossche** [comment]
So it is probably not related to the scipy 1.3.1 release, as with the older pip also installing older scipy downloads the source (it just coincidentally started being a problem for some reason at the same moment that scipy 1.3.1 was out). Sorry for the noise!

**Comment by jorisvandenbossche** [comment]
So apparently this is due to Python 3.7.3 -> 3.7.4 update (and conda-forge is still at 3.7.3): https://github.com/conda/conda/issues/9084, https://github.com/tensorflow/tensorflow/issues/31523

Not sure if this is an issue with the Python provided by Anaconda or with Python 3.7.4 itself
