### ISSUE TITLE
incomplete doc build instructions

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#10646]
On https://scipy.github.io/devdocs/dev/contributor/rendering_documentation.html, a critical step is missing. The description assumes you've done something like `python setup.py develop` already. I.e. before `make html` or `make html-scipyorg`, make sure that `>>> import scipy` works and picks up the scipy build you are working on. This is confusing, so clearly note this in the docs.

Also, it may be useful to take over the recent change to the numpy doc Makefile that compares git hashes and refuses to build if they don't match. That ensures you pick up the right version.

**Comment by fuglede** [comment]
I tried running `python setup.py develop` and in particular, I see a

> building 'scipy._lib._uarray._uarray' extension

along the way, yet `make html-scipyorg` gives me the same error as above.

I can run `import scipy` without getting the warning about doing so from within the repository, yet the one it picks up is the one from conda.

**Comment by rgommers** [comment]
It could be that you have `sphinx` on your path but in a different environment as you use to build scipy. you can check where things are with, e.g., `scipy.__file__` and `which sphinx-build`.

**Comment by fuglede** [comment]
Thanks. In my case, it seems the issue was that the installed conda SciPy package took precedence when inside `doc` (which is where the current tutorial wants one to be); let me just record a solution to that here in case anyone else runs into the same problem:

Running `python setup.py develop` and creating an environment with only sphinx, NumPy, matplotlib, and their dependencies was enough to get the build up and running here, but only after specifically adding the root of the SciPy source to `PYTHONPATH`:

```
~/repos/scipy/doc$ which sphinx-build
/home/user/miniconda3/bin/sphinx-build
~/repos/scipy/doc$ python -c "import scipy; print(scipy.__file__)"
/home/user/miniconda3/lib/python3.7/site-packages/scipy/__init__.py
~/repos/scipy/doc$ cd ..
~/repos/scipy$ python -c "import scipy; print(scipy.__file__)"
/home/user/repos/scipy/scipy/__init__.py
~/repos/scipy$ cd doc
~/repos/scipy/doc$ export PYTHONPATH=/home/user/repos/scipy
~/repos/scipy/doc$ make html
```

Including a few words on this potential problem in the docs would also be nice; I at least found it a bit confusing this first time around.

**Comment by mdhaber** [comment]
So add a step 0 to remind users to set up a development environment according to the [instructions for their platform](http://scipy.github.io/devdocs/dev/contributor/contributor_toc.html#development-environment)?

That way all the other missing steps - install Python on your computer, download the SciPy source code (with git), etc are taken care of, too.

**Comment by rgommers** [comment]
> So add a step 0 to remind users to set up a development environment according to the instructions for their platform?

yes indeed

**Comment by rgommers** [comment]
> Including a few words on this potential problem in the docs would also be nice

I'd rather fix it like numpy:
```
$ make html
installed numpy 7ebbc2ed3b != current repo git version 'ddb4a68ba6'
use "make dist" or "GITVER=7ebbc2ed3b make html ..."
make: *** [Makefile:94: version-check] Error 1
```
we just need to copy the numpy Makefile changes.

**Comment by sethtroisi** [comment]
https://github.com/scipy/scipy/pull/10715 includes the version check.

@rgommers  Is there any remaining work here?

**Comment by rgommers** [comment]
thanks, indeed all good here.
