### ISSUE TITLE
scipy.optimize benchmark improvements

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#10647]
Although #2421 has been closed, we should probably collect thoughts on improvements to `scipy.optimize` benchmarks somewhere.

For `linprog`:

- [x] I'd suggest removing benchmarks for `method='simplex'` (sound good @Kai-Striega?) 
- [x] Add benchmarking for `method='revised simplex'`
- [x] Add moderate-size NETLIB problems (files already available in [`/benchmarks/benchmarks/linprog_benchmark_files`](https://github.com/scipy/scipy/tree/master/benchmarks/benchmarks/linprog_benchmark_files)). Current choices `BLEND` and `AFIRO` were chosen because `simplex` couldn't handle many others, but removing it from the benchmarks gives more flexibility.
- [x] Add some [infeasible problems](https://www.netlib.org/lp/infeas/index.html) (done in #11729)
- [x] Adding separate redundancy removal benchmarks

**Comment by Kai-Striega** [comment]
> I'd suggest removing benchmarks for method='simplex' (sound good @Kai-Striega?)

We chose not to deprecate `simplex` to have it remain largely for educational use (+ legacy code). For educational use, the dimensions are likely to be small anyway and the performance won't matter too much. 

The other points all look good to me. Just as an aside, did you avoid adding the infeasible problems because ``simplex`` couldn't handle it?

**Comment by mdhaber** [comment]
> We chose not to deprecate `simplex` to have it remain largely for educational use (+ legacy code). For educational use, the dimensions are likely to be small anyway and the performance won't matter too much.

I can't tell - do you mean that you agree we should remove the benchmarks because the performance doesn't matter, or that we shouldn't remove the benchmarks because we did not deprecate `simplex`?

>Did you avoid adding the infeasible problems because simplex couldn't handle it?

Nope. I just didn't include them. They are a different set of problems, and I didn't download them.

**Comment by Kai-Striega** [comment]
@mdhaber with #11729 done are you happy to mark this as done?

**Comment by mdhaber** [comment]
Close, but I think we could use unbounded benchmarks.
