### ISSUE TITLE
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 800.

### ISSUE THREAD

**Issue by zysNLP** [scipy/scipy#10652]
When I fit the exponential function, my data X from [0-1],Y from [0,1086];
The fitting function is:
def func(x, a, b, c):
    return a * np.exp(-b * x) + c

Then raise RuntimeError, why?

**Comment by ev-br** [comment]
These sorts of usage questions are best asked on Stackoverflow.
