### ISSUE TITLE
Scipy zeros

### ISSUE THREAD

**Issue by Abolfazlmsl** [scipy/scipy#10659]
Hi,
I wanted to build scipy.zeros((70000,70000)) matrix but i got a memory error. Why i got this error and is there any way to build that huge matrix?

**Comment by peterbell10** [comment]
A 70000x70000 matrix of `float64` requires 36 GB of memory. If most of the values are going to be 0 you could use a [sparse matrix](https://docs.scipy.org/doc/scipy-1.3.0/reference/sparse.html) instead. 

This isn't a bug in SciPy so closing.
