### ISSUE TITLE
test_nan_inputs hangs on some architectures (hppa, riscv64, sparc64)

### ISSUE THREAD

**Issue by RizzerOnGitHub** [scipy/scipy#10656]
Three alternative non-intel cip architectures are hanging on the same test in Debian builts of scipy 1.3.1.  The arches are hppa, riscv64, sparc64.  Build logs [1] show the tests are stopping at test_nan_inputs[iv]:
```
../../debian/python3-scipy/usr/lib/python3.7/dist-packages/scipy/special/tests/test_nan_inputs.py::test_nan_inputs[itmodstruve0]` PASSED [ 89%]
../../debian/python3-scipy/usr/lib/python3.7/dist-packages/scipy/special/tests/test_nan_inputs.py::test_nan_inputs[itstruve0] PASSED [ 89%]
../../debian/python3-scipy/usr/lib/python3.7/dist-packages/scipy/special/tests/test_nan_inputs.py::test_nan_inputs[iv] 
E: Build killed with signal TERM after 600 minutes of inactivity
```

Since the failing test is the same on each architrecture, it suggests this might be a scipy bug which is fixable.

[1] hppa: https://buildd.debian.org/status/fetch.php?pkg=python-scipy&arch=hppa&ver=1.3.1-1exp2&stamp=1565725887&raw=0
 riscv64: https://buildd.debian.org/status/fetch.php?pkg=python-scipy&arch=riscv64&ver=1.3.1-1exp2&stamp=1565756576&raw=0
sparc64: https://buildd.debian.org/status/fetch.php?pkg=python-scipy&arch=sparc64&ver=1.3.1-1exp2&stamp=1565756799&raw=0

**Comment by person142** [comment]
The simplest way to fix this is to add an explicit NaN check of the arguments to `iv`, which doesn't have one currently:

https://github.com/scipy/scipy/blob/master/scipy/special/cephes/scipy_iv.c#L80

It's a reasonable thing to do anyway, and it's probably going to be much easier than tracking down what's going wrong on those architectures.

**Comment by akesandgren** [comment]
For the record, although it's an old version, this happens with scipy 1.2.3 on Skylakes too using Python 2.7.18
