### ISSUE TITLE
Error in linprog with simplex method

### ISSUE THREAD

**Issue by BinglePan** [scipy/scipy#10666]
My issue is about Error in scipy.optimize.linprog with simplex method. Mostly it works well. But I've found more than 15 cases that are soluble in matlab and can't be solved by linprog with the default "method=simplex". I first found this problem in scipy 0.19 and now it is updated to 1.2.1 but the problem remains the same. This problem can also be solved by passing "method=interior-point". But usually simplex method is more popular. Hope fix it.

#### Reproducing code example:

```
from scipy.optimize import linprog

effective_A_ub = [[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                  [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0],
                  [7.800000190734863, 15.699999809265137, 15.09999942779541, 44.20000076293945, 0, 0, 0, 0, 0, 0, 0, 0],
                  [-7.800000190734863, -15.699999809265137, -15.09999942779541, -44.20000076293945, 0, 0, 0, 0, 0, 0, 0, 0],
                  [-1.6000001430511475, -6.5, -7.499999523162842, -5.900000095367432, 0, 0, 0, 0, 0, 0, 0, 0],
                  [0.019999999552965164, 0.10999999940395355, 0.15000000596046448, 0.33000001311302185, 23.290000915527344, 35.84000015258789, 0.30000001192092896, 0, 0, 0, 0, 0],
                  [-0.019999999552965164, -0.10999999940395355, -0.15000000596046448, -0.33000001311302185, -23.290000915527344, -35.84000015258789, -0.30000001192092896, 0, 0, 0, 0, 0],
                  [0.05000000447034836, 0.3199999928474426, 0.25, 0.1599999964237213, 17.0, 0, 0, 0, 0, 0, 0, 0],
                  [-0.05000000447034836, -0.3199999928474426, -0.25, -0.1599999964237213, -17.0, 0, 0, 0, 0, 0, 0, 0],
                  [0.05000000447034836, 0.14000000059604645, 0.1899999976158142, 0.07999999821186066, 0, 0.07999999821186066, 98.5, 0, 0, 0, 0, 0],
                  [-0.05000000447034836, -0.14000000059604645, -0.1899999976158142, -0.07999999821186066, 0, -0.07999999821186066, -98.5, 0, 0, 0, 0, 0],
                  [3390.0, 2240.0, 2760.0, 3370.0, 0, 0, 0, 0, 0, 0, 8750.0, 0],
                  [-3390.0, -2240.0, -2760.0, -3370.0, 0, 0, 0, 0, 0, 0, -8750.0, 0],
                  [0.17020000517368317, 0.45989999175071716, 0, 2.3584001064300537, 0, 0, 0, 0, 0, 0, 0, 78.80000305175781],
                  [-0.17020000517368317, -0.45989999175071716, 0, -2.3584001064300537, 0, 0, 0, 0, 0, 0, 0, -78.80000305175781],
                  [-0.055499997735023496, 0.023399996757507313, 0.00040000975131987415, 0.27890002727508545, 0.0, 0.0, 0.0, -98.0, 0.0, 0.0, 0.0, 23.64000091552734],
                  [-0.10650000870227813, -0.03399997353553774, -0.0011999845504760964, 0.5369000434875488, 0.0, 0.0, 0.0, -98.0, 0.0, 0.0, 0.0, 47.28000183105468],
                  [-0.07380000725388527, 0.08950000405311587, 0.4680000185966492, 0.3227000832557678, 0.0, 0.0, 0.0, 0.0, -98.0, 0.0, 0.0, 51.22000198364258]]
effective_b_ub = [1.0, -1.0, 19.0, -18.0, -3.5, 0.9, -0.7, 0.5, -0.4, 0.6, -0.4, 2950.0, -2900.0, 0.7, -0.6, 0, 0, 0]
adjusted_rm_prices = [2100.0, 1800.0, 1750.0, 2750.0, 1900.0, 300.0, 700.0, 20000.0, 7000.0, 25000.0, 6000.0, 8000.0]
adjusted_rm_bounds = [(0, 1), (0, 0.3), (0, 0.2), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0.01, 0.01), (0, 0.02), (0, 1)]
A_eq = [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
b_eq = [1]
res = linprog(c=adjusted_rm_prices, A_ub=effective_A_ub, b_ub=effective_b_ub, A_eq=A_eq, b_eq=b_eq, bounds=adjusted_rm_bounds)
print(res)
```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 35, in <module>
      res = linprog(c=adjusted_rm_prices, A_ub=effective_A_ub, b_ub=effective_b_ub, A_eq=A_eq, b_eq=b_eq, bounds=adjusted_rm_bounds)
  File "D:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\_linprog.py", line 478, in linprog
    complete, undo, status, message, tol, iteration, disp)
  File "D:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\_linprog_util.py", line 1322, in _postprocess
    lb, ub, tol, message
  File "D:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\_linprog_util.py", line 1235, in _check_result
    raise ValueError(message)
ValueError: Phase 1 of the simplex method failed to find a feasible solution. The pseudo-objective function evaluates to 3.6e-11 which exceeds the required tolerance of 1e-12 for a solution to be considered 'close enough' to zero to be a basic solution. Consider increasing the tolerance to be greater than 3.6e-11. If this tolerance is unacceptably  large the problem may be infeasible.

Process finished with exit code 1
```

**Comment by BinglePan** [comment]
By passing interior-point method like

`res = linprog(c=adjusted_rm_prices, A_ub=effective_A_ub, b_ub=effective_b_ub, A_eq=A_eq, b_eq=b_eq, bounds=adjusted_rm_bounds, method="interior-point")
`

the same linear programming model will get the right result like
`
     con: array([-4.40365522e-10])
     fun: 2327.322802149588
 message: 'Optimization terminated successfully.'
     nit: 13
   slack: array([-4.40365522e-10,  4.40365522e-10,  9.99999997e-01,  3.45359652e-09,
        1.03759942e+00,  3.79482135e-09,  1.99999996e-01,  9.99999992e-02,
        8.47321935e-10,  1.99999993e-01,  7.09075654e-09,  4.99999992e+01,
        8.02438990e-07,  6.11495764e-02,  3.88504236e-02,  2.40102579e-02,
        2.17166942e-09,  2.11602705e-09])
  status: 0
 success: True
       x: array([3.60521051e-01, 1.89936950e-01, 2.00000000e-01, 2.07826372e-01,
       1.39965827e-02, 1.24559265e-02, 3.04325073e-03, 6.78455584e-04,
       1.54141322e-03, 1.00000000e-02, 3.54832532e-12, 7.66234981e-12])

Process finished with exit code 0
`

**Comment by BinglePan** [comment]
@mdhaber @minho42 @Kai-Striega  Thanks

**Comment by mdhaber** [comment]
@BinglePan thanks for bringing up the issue with `simplex`. I'll take a look. In the meantime, you might like to try method `revised simplex` available in SciPy 1.3.

**Comment by BinglePan** [comment]
@mdhaber Thanks for solving my problem. And I've investigated the reference for linprog finding that the default value for tolerance is `options={'tol': 1e-12}`. This time my case can be solved by loosening the tolerance. Maybe so can the other 14 cases I encountered. But now my question is when I should use the default value for `tol` and if not what value for it should be set. Do you have any suggestion or reference for that?

**Comment by Kai-Striega** [comment]
@BinglePan thanks for taking the time to submit an issue and offering to help.

>  I first found this problem in scipy 0.19 and now it is updated to 1.2.1 but the problem remains the same. This problem can also be solved by passing "method=interior-point". But usually simplex method is more popular. 

As @mdhaber said, from 1.3 onwards the interior-point and revised simplex are the default solvers with the original simplex being maintained for legacy or educational use.

> I've investigated the reference for linprog finding that the default value for tolerance is options={'tol': 1e-12}. This time my case can be solved by loosening the tolerance. Maybe so can the other 14 cases I encountered.

We've raised the tolerance to 1e-9 in 1.4 (see: #10143) making many of the existing tolerance issues pass (but still fail with 1e-12) without any failures on our existing tests. Maybe try it with the 

> But now my question is when I should use the default value for tol and if not what value for it should be set.

The error message prints the value of the phase one objective function (in your example 3.6e-11). That would be a good start. The issue with a default tolerance is that for any tolerance a problem could be constructed to make it fail.

@mdhaber I won't have time to take an in-depth look at it, the error looks related to the tolerance value (as changing from 1e-12 to 1e-11 fixes the issue) which will be updated in 1.4 and occurs for the simplex method only, which is no longer the default, nor recommended.

**Comment by BinglePan** [comment]
Thank @Kai-Striega for the detailed explanation. As a teacher, I still prefer the simplex method due to its tableau, obvious geometric means and advantage in sensitivity analysis. If the new default tolerance value can fix this problem, it's OK since it's already precise enough.

**Comment by mdhaber** [comment]
@BinglePan I had written:
> We consider simplex to be a legacy method that is retained only for backwards compatibility.

The other reason we have discussed for keeping `simplex` is educational purposes. Glad to know it's getting used for that!

**Comment by Kai-Striega** [comment]
@BinglePan could you run your other problems to confirm that they pass with a higher tolerance?

**Comment by BinglePan** [comment]
> @BinglePan could you run your other problems to confirm that they pass with a higher tolerance?

@Kai-Striega I've done this with `options={"tol": 1e-9}` on the other 14 cases. It works.

**Comment by BinglePan** [comment]
@mdhaber @Kai-Striega Recently I've tested `linprog` with `method='simplex', options={"tol": 1e-9}` on nearly 100 similar cases (My Scipy version is 1.2.1). It worked for almost all occasions except for one. The result said `ValueError: Phase 1 of the simplex method failed to find a feasible solution. The pseudo-objective function evaluates to 1.2e-09 which exceeds the required tolerance of 1e-09 for a solution to be considered 'close enough' to zero to be a basic solution.`  Then I increased the tolerance to `1e-8`. It worked again and I got the desired result. So after this round of testing, my problem is how to choose an appropriate tolerance.

**Comment by mdhaber** [comment]
Good to hear that it works almost all the time. I'd be curious whether the new equilibriation procedure fixes that one problem; if you can post it I'd appreciate it!

**Comment by BinglePan** [comment]
> Good to hear that it works almost all the time. I'd be curious whether the new equilibriation procedure fixes that one problem; if you can post it I'd appreciate it!

Below is the linprog code with ` method='simplex', options={"tol": 1e-9}`

`from scipy.optimize import linprog

A_ub = [[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
        [-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0],
        [11.0, 15.09999942779541, 44.20000076293945, 0, 0, 0, 0, 0, 0, 13.399999618530273, 9.0, 7.800000190734863, 15.699999809265137, 0, 0],
        [-11.0, -15.09999942779541, -44.20000076293945, 0, 0, 0, 0, 0, 0, -13.399999618530273, -9.0, -7.800000190734863, -15.699999809265137, 0, 0],
        [-4.800000190734863, -7.499999523162842, -5.900000095367432, 0, 0, 0, 0, 0, 0, -1.899999976158142, -1.399999976158142, -1.6000001430511475, -6.5, 0, 0],
        [0.09000000357627869, 0.15000000596046448, 0.33000001311302185, 23.290000915527344, 35.84000015258789, 0.30000001192092896, 0, 0, 0, 0.17000000178813934, 0.12999999523162842, 0.019999999552965164, 0.10999999940395355, 0, 0],
        [-0.09000000357627869, -0.15000000596046448, -0.33000001311302185, -23.290000915527344, -35.84000015258789, -0.30000001192092896, 0, 0, 0, -0.17000000178813934, -0.12999999523162842, -0.019999999552965164, -0.10999999940395355, 0, 0],
        [0.10000000894069672, 0.25, 0.1599999964237213, 17.0, 0, 0, 0, 0, 0, 0.20999999344348907, 0.09000000357627869, 0.05000000447034836, 0.3199999928474426, 0, 0],
        [-0.10000000894069672, -0.25, -0.1599999964237213, -17.0, 0, 0, 0, 0, 0, -0.20999999344348907, -0.09000000357627869, -0.05000000447034836, -0.3199999928474426, 0, 0],
        [-0.11000001430511475, -0.3499999940395355, 0.010000020265579224, -10.709999084472656, 35.84000015258789, 0.30000001192092896, 0.0, 0.0, 0.0, -0.2499999850988388, -0.050000011920928955, -0.08000000938773155, -0.5299999862909317, 0.0, 0.0],
        [0.24718309938907623, 0.16478873789310455, 0.08239436894655228, 0, 0.03295774757862091, 97.22534942626953, 0, 0, 0, 0.115352101624012, 0.1483098566532135, 0.06591549515724182, 0.115352101624012, 0, 0],
        [-0.24718309938907623, -0.16478873789310455, -0.08239436894655228, 0, -0.03295774757862091, -97.22534942626953, 0, 0, 0, -0.115352101624012, -0.1483098566532135, -0.06591549515724182, -0.115352101624012, 0, 0],
        [3020.0, 2760.0, 3370.0, 0, 0, 0, 0, 0, 0, 3390.0, 3150.0, 3390.0, 2240.0, 8750.0, 0],
        [-3020.0, -2760.0, -3370.0, 0, 0, 0, 0, 0, 0, -3390.0, -3150.0, -3390.0, -2240.0, -8750.0, 0],
        [0.3149999976158142, 0, 2.3584001064300537, 0, 0, 0, 78.80000305175781, 0, 0, 0.28700000047683716, 0.133200004696846, 0.17020000517368317, 0.45989999175071716, 0, 0],
        [-0.3149999976158142, 0, -2.3584001064300537, 0, 0, 0, -78.80000305175781, 0, 0, -0.28700000047683716, -0.133200004696846, -0.17020000517368317, -0.45989999175071716, 0, 0],
        [-130.0, 2760.0, -20214.0, 0.0, 0.0, 0.0, -788000.0, 0.0, 0.0, 520.0, 1818.0, 1688.0, -2359.0, 8750.0, 0.0],
        [-0.009900003671646118, 0.21559999883174896, -0.6541000604629517, 0.0, 0.0, 0.0, -39.400001525878906, 0.0, 0.0, 0.04129999876022339, 0.06769999116659164, 0.039399996399879456, -0.06434999406337738, 0.0, 98.0],
        [0.10619999170303346, 0.43320000171661377, -0.3439400672912598, 0.0, 0.0, 0.0, -47.28000183105468, 0.0, 0.0, 0.2796000182628632, 0.13478001058101655, 0.14238000810146334, 0.1360599756240845, 0.0, 98.0],
        [-0.10685000121593474, 0.0, 0.1136601090431213, 0.0, 0.0, 0.0, 51.22000198364258, -98.0, 0.0, -0.13265000879764557, -0.10841998979449272, -0.11267000660300254, -0.021064998209476438, 0.0, 0.0],
        [-0.0668999969959259, 0.0, -0.2771600008010864, 0.0, 0.0, 0.0, 7.880000305175781, 0.0, 0.0, -0.10329999923706054, -0.04587999582290649, -0.030979999899864195, -0.13651000559329987, 0.0, 0.0]]
b_ub = [1.0, -1.0, 15.0, -13.0, -3.5, 0.9, -0.7, 0.5, -0.4, 0, 0.6, -0.4, 2950.0, -2900.0, 0.7, -0.6, 0, 0, 0, 0, 0]
c = [1800.0, 1750.0, 2750.0, 1900.0, 300.0, 700.0, 8000.0, 7000.0, 25000.0, 2000.0, 1800.0, 2100.0, 1800.0, 6000.0, 20000.0]
bounds = [(0, 1), (0, 0.2), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0, 1), (0.01, 0.01), (0, 1), (0, 1), (0, 1), (0, 0.3), (0, 1), (0, 1)]
A_eq = [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
b_eq = [1]
res = linprog(c=c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bounds, method='simplex', options={"tol": 1e-9})
print(res)`

And it gave the following warning message
`ValueError: Phase 1 of the simplex method failed to find a feasible solution. The pseudo-objective function evaluates to 1.2e-09 which exceeds the required tolerance of 1e-09 for a solution to be considered 'close enough' to zero to be a basic solution. Consider increasing the tolerance to be greater than 1.2e-09. If this tolerance is unacceptably  large the problem may be infeasible.
`
This problem can be fixed by using the tolerance '1e-8'.

**Comment by BinglePan** [comment]
I'm also curious whether the tolerance in linprog for simplex needs to be increased to 1e-8 in the new version. : )

**Comment by mdhaber** [comment]
I don't think we would change the tolerance based on this one example. We need to about false successes while minimizing false failures. The balance seems pretty good otherwise, so we'd need more evidence before changing again.

**Comment by mdhaber** [comment]
Where do these examples come from, by the way?

**Comment by Kai-Striega** [comment]
I agree with Matt. There will always be some problems where the tolerance
is only slightly too low.

1e-9 seems to strike a good balance with most, in your case 113 out of 114,
cases passing. Even when it does fail, linprog returns a clear (I hope)
error message telling you the user the required tolerance.

**Comment by BinglePan** [comment]
> Where do these examples come from, by the way?

@mdhaber These examples come from my project consisting of some synthetic data but very close to the real cases.
