### ISSUE TITLE
scipy.signal.butter: "Must specify a single critical frequency Wn"

### ISSUE THREAD

**Issue by TheGreatCabbage** [scipy/scipy#10668]
According to the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.butter.html) for scipy.signal.butter:

_Wn : array_like_
        A scalar or **length-2 sequence** giving the critical frequencies.
        (...)

However, only a **single critical frequency** is accepted. Passing `Wn` as an array, list or tuple containing two critical frequencies produces `ValueError: Must specify a single critical frequency Wn`.

#### Reproducing code example:

```
"""
Tests butter by passing N=2, Wn=[0.1, 0.9] to the function.
Raises ValueError.
"""
from scipy.signal import butter
b, a = butter(2, [0.1, 0.9])
```
Matlab is able to produce a result from the equivalent code, `[b, a] = butter(2, [0.1, 0.9])`.

#### Error message:

The `ValueError` is raised from precisely [this line](https://github.com/scipy/scipy/blob/b1bcb1226cc120f707fba3d0fa377120a60cff8d/scipy/signal/filter_design.py#L2353).
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<...>/venv/lib/python3.6/site-packages/scipy/signal/filter_design.py", line 2858, in butter
    output=output, ftype='butter', fs=fs)
  File "<...>/venv/lib/python3.6/site-packages/scipy/signal/filter_design.py", line 2351, in iirfilter
    raise ValueError('Must specify a single critical frequency Wn')
ValueError: Must specify a single critical frequency Wn
```

#### Scipy/Numpy/Python version information:

`1.3.1 1.16.4 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)`

**Comment by larsoner** [comment]
I think this is probably a documentation bug, because whether it takes a single value or two values depends on the filter type (lowpass/highpass vs bandstop/bandpass).

@TheGreatCabbage can you (check that my understanding is correct and if so) make a PR to clarify the docs?
