### ISSUE TITLE
rv_continuous assumes shape parameters are scalars and this is not documented

### ISSUE THREAD

**Issue by dfoxfranke** [scipy/scipy#10661]
I'm trying to implement the distribution described in [Moschopoulos 1985](https://www.researchgate.net/profile/Panagis_Moschopoulos/publication/225242960_The_Distribution_of_the_Sum_of_Independent_Gamma_Random_Variables/links/542746830cf2e4ce940a2ed5.pdf) (but instead see section 2 of [Barnabani 2015](https://www.researchgate.net/profile/Marco_Barnabani/publication/277625958_An_approximation_to_the_convolution_of_Gamma_Distributions/links/5c0f7eb3a6fdcc494feb4245/An-approximation-to-the-convolution-of-Gamma-Distributions.pdf) for a clearer specification): a convolution of N gamma distributions whose scale parameters differ. A couple observations about this distribution:

1. Its shape parameters are *vectors* of alpha and beta values.
2. The PDF and CDF are expensive to compute but the expensive part depends only on the shape parameters and not on the argument, so it's highly beneficial to memoize that part.

My first implementation attempt involved creating a `moschopoulos_omega` class whose constructor takes the shape parameters and performs the memoized part of the computation, and then having the shape parameter to my `compound_gamma_gen` subclass of `rv_continuous` be a `moschopoulos_omega` instance. That didn't work: lots of code in `rv_continuous` makes assumptions that shape parameters are just `int`s or `float`s and does things with them that other classes can't be expected to support, like multiplying them by a boolean at https://github.com/scipy/scipy/blob/e1e44d12637997606b1bcc0c6de232349e11eee0/scipy/stats/_distn_infrastructure.py#L545. My next try was to have the shape parameters be lists of floats, and handle memoization through hidden state inside `compound_gamma._pdf`. That didn't error out, but neither did it work: I found that the lists were getting silently truncated to just their first element.

The assumption that shape parameters are scalars seems to pretty pervasive throughout the implementation of `rv_continuous`, but this is not mentioned anywhere in the documentation. Furthermore. because of this, I can't seem to find any reasonable way to use `rv_continuous` to do what I'm trying to do.

**Comment by josef-pkt** [comment]
shape parameters are fully vectorized (maybe still with some exceptions when support depends on parameters)

My guess would be that your problem is in the memoization and how that affects the shape handling in the generic code for the distribution methods.
scipy distributions are essentially supposed to be stateless and there are problems getting memoization to work outside of frozen distributions.

**Comment by dfoxfranke** [comment]
The problem is definitely with the type of the shape arguments, not with the memoization. I get different behavior depending on what I return from `_argcheck`, but I can't find any way to produce the *right* behavior. Here's a trivial example where the _pdf method just prints its arguments and returns 0. I want to compute the PDF at x=10, for the convolution of three gamma distributions whose (alpha, beta) parameters are (1,1), (2,2), and (3,3) respectively. I expect `_pdf` to get called with the same `x`, `alphas`, and `betas` that I passed to `pdf`, and the call to `pdf` to return `0.`. But no matter how I write `_argcheck`, I either get an exception or the arguments and/or return value get mangled somehow. 

```python
import numpy as np
from scipy.stats import rv_continuous

class compound_gamma_gen(rv_continuous):
    def _pdf(self, x, alphas, betas):
        print((x, alphas, betas))
        return 0.
    
    def _argcheck(self, alphas, betas):
        #return True #prints (array([10.]), array([1.]), array([1.])), returns 0.
        return (True,True) #ValueError: operands could not be broadcast together with shapes (3,) (2,) 
        #return [True, True, True] #prints (array([10., 10., 10.]), array([1., 2., 3.]), array([1., 2., 3.])), returns array([0., 0., 0.])
        #return ([True, True, True], [True, True, True]) #prints (array([10., 10., 10., 10., 10., 10.]), array([1., 2., 3., 1., 2., 3.]), array([1., 2., 3., 1., 2., 3.])),
                                                         #returns array([[0., 0., 0.], [0., 0., 0.]])
    
compound_gamma = compound_gamma_gen(name='compound_gamma')
compound_gamma.pdf(10., [1., 2., 3], [1., 2., 3.])
```

**Comment by chrisb83** [comment]
I think you need to write sth like

```
def _argcheck(self, alphas, betas):
        return (alphas == alphas) & (betas > 0)
```

**Comment by dfoxfranke** [comment]
In the example that leads to a return of `[True, True, True]` from `_argcheck`, which is one of the things I already tried that leads to wrong behavior.

**Comment by chrisb83** [comment]
I still do not understand the issue. What is the return value you expect from `compound_gamma.pdf(10., [1., 2., 3.], [1., 2., 3.])`?

**Comment by dfoxfranke** [comment]
I expect the return value to be `0.` When I use the definition of `_argcheck` that you suggested, I get `array([0., 0., 0.])`.

**Comment by WarrenWeckesser** [comment]
We do, in fact, have distributions with parameters that are not scalars: the multivariate distributions.  For example, the multivariate normal distribution has two parameters: a vector of length `n` that holds the mean, and a 2-d array with shape `(n, n)` that holds the covariance matrix.  Unfortunately, we have not implemented broadcasting for the multivariate distributions.  (That's one of the items on my SciPy "to-do/wish list".)

For the univariate distributions, it is true that we assume that the parameters are scalars.  I don't know if we can extend the current API to handle parameters that are vectors.  You said

>  I can't seem to find any reasonable way to use rv_continuous to do what I'm trying to do.

and that might turn out to be the final conclusion.  Instead of trying to make a subclass do something that is wasn't designed for, you might find it easier to create your own class, borrowing any bits of code from `rv_continuous` are useful without actually subclassing it.

**Comment by mdhaber** [comment]
@dfoxfranke were you able to work something out? In any case, it sounds like you'd like the docs to be more explicit about the shape parameters needing to be scalars?

**Comment by mdhaber** [comment]
@dfoxfranke I don't think we can modify `rv_continuous` to accept vector parameters right now. Please let us know how we can update the documentation to make the difference between "arrays of scalar parameters" and "vector parameters" more clear. In the meantime, I'll go ahead and close this, but please reopen if you have a suggestion for the documentation.
