### ISSUE TITLE
Error building doc: sphinx.util.inspect has no attribute isattributedescriptor

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#10685]
Locally building the doc fails due to missing attribute `isattributedescriptor` in `sphinx.util.inspect`.  

gh-10383 added a workaround for https://github.com/sphinx-doc/sphinx/issues/6573, and introduced a reference to `inspect.isattributedescriptor`.  That doesn't exist in my sphinx v2.01, and `doc/source/conf.py` only requires sphinx 1.6. 

#### Reproducing code example:
```
pushed doc;  make clean; PYTHON_PATH=/Users/Paul/src/python/scipy make html
```

#### Error message:
```
$ make clean; PYTHON_PATH=/Users/Paul/src/python/scipy make html
rm -rf build/* source/generated
mkdir -p build/html build/doctrees
LANG=C python3.6 /Users/Paul/anaconda/envs/py36scipydev2/bin/sphinx-build -b html -d build/doctrees   source build/html 
Running Sphinx v2.0.1

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/Paul/anaconda/envs/py36scipydev2/lib/python3.6/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/Users/Paul/anaconda/envs/py36scipydev2/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 86, in execfile_
    exec(code, _globals)
  File "/Users/Paul/src/python/scipy/doc/source/conf.py", line 24, in <module>
    old_isattrdesc = inspect.isattributedescriptor
AttributeError: module 'sphinx.util.inspect' has no attribute 'isattributedescriptor'

make: *** [html] Error 2
```

#### Scipy/Numpy/Python version information:
```
1.4.0.dev0+4ed8b10 1.16.0 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

**Comment by pvanmulbregt** [comment]
After looking in the source:
- The toolchain roadmap lists Sphinx 2.0 as a requirement. https://github.com/scipy/scipy/blob/master/doc/source/toolchain.rst#building-the-documentation
- I found 5 references to `sphinx.__version__` : 0.6, 1.0.1 (twice), 1.5 and 1.6.
`doc/source/conf.py` presumably gates the 4 requirements in the doc tree, and that leaves one independent check in `tools/refguide_check.py`.

Is 2.1 actually the current minimum version?

**Comment by peterbell10** [comment]
I see from the sphinx history that this function was indeed only added in version 2.1 ([see commit](https://github.com/sphinx-doc/sphinx/commit/d41cae328ec139b4d65b60041f561657cfef86ab#diff-84bfd2ad46b7c8e97e5a06abb886c065)). I think that patching `inspect.isdescriptor` should do the same job without breaking compatibility. PR incomping.

**Comment by pvanmulbregt** [comment]
Confirming that after upgrading to sphinx 2.1 I was able to build the doc.
