### ISSUE TITLE
BUG: Assignation issues in csr_matrix with fancy indexing

### ISSUE THREAD

**Issue by nphilou** [scipy/scipy#10695]
In scipy 1.3.1, setting values in a csr_matrix using fancy indexing returns `ValueError: shape mismatch in assignment` from  `scipy.sparse._index.IndexMixin.__setitem__` method. It doesn't happen in 1.2.1.

This issue seems to come from the `_broadcast_arrays` method in [v1.3.1/scipy/sparse/_index.py#L15](https://github.com/scipy/scipy/blob/v1.3.1/scipy/sparse/_index.py#L15) which returns 1-D array instead of 2-D array: [v1.2.1/scipy/sparse/sputils.py#L467](https://github.com/scipy/scipy/blob/v1.2.1/scipy/sparse/sputils.py#L467)

#### Reproducing code example:

In scipy 1.2.1:
```python
>>> import numpy as np
>>> from scipy.sparse import csr_matrix
>>> x = csr_matrix((np.array([1, 2, 3]), (np.array([0, 1, 1]), np.array([0, 0, 1]))), shape=(2, 2))
>>> x.toarray()
array([[1, 0],
       [2, 3]], dtype=int64)
>>> x[[0, 1], [1, 1]] = x[[1, 0], [0, 0]]
__main__:1: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
>>> x.toarray()
array([[1, 2],
       [2, 1]], dtype=int64)
```

In scipy 1.3.1:
```python
>>> import numpy as np
>>> from scipy.sparse import csr_matrix
>>> x = csr_matrix((np.array([1, 2, 3]), (np.array([0, 1, 1]), np.array([0, 0, 1]))), shape=(2, 2))
>>> x.toarray()
array([[1, 0],
       [2, 3]], dtype=int64)
>>> x[[0, 1], [1, 1]] = x[[1, 0], [0, 0]]
```
#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/philippe/anaconda3/envs/venv/lib/python3.7/site-packages/scipy/sparse/_index.py", line 146, in __setitem__
    raise ValueError("shape mismatch in assignment")
ValueError: shape mismatch in assignment
```

#### Scipy/Numpy/Python version information:
```
1.3.1 1.16.4 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
```

#### Simple fix that can break everything:

Add: 
```python
        if x.ndim == 1:
            # return column vectors for 1-D indexing
            x = x[None, :]
            y = y[None, :]
        elif x.ndim > 2:
            raise IndexError("Index dimension must be <= 2")
```
to `scipy.sparse._index._broadcast_arrays` method.

**Comment by tylerjereddy** [comment]
Tentatively labeling as a defect pending input from @perimosocordiae

**Comment by perimosocordiae** [comment]
Yup, this is a bug. I don't think we should touch the `_broadcast_arrays` function, but rather we can remove the check here:
https://github.com/scipy/scipy/blob/4bfc152f6ee1ca48c73c06e27f7ef021d729f496/scipy/sparse/_index.py#L123

The call to `_broadcast_arrays(x, i)` will already fail if the shapes are incompatible. I'll see about sending a PR soon.

**Comment by pv** [comment]
The issue is fixed, but I think some more discussion is warranted:

Reshaping does fix the above mentioned thing, but I guess it's more liberal than what ndarray itself does. Also, what was the precise scipy.sparse behavior prior to 1.2.1 --- did it just reshape? 

The ndarray rules seem to be to try to broadcast lhs and rhs to same shape, 
```
In [14]: x = np.array([[1,2],[3,4]])
In [15]: x[[0,1],[0,1]] = np.array([3])  # ok (broadcasting size-1 case)
In [16]: x[[0,1],[0,1]] = np.array([3,1])  # ok
In [17]: x[[0,1],[0,1]] = np.array([3,1,2]) # not ok
Traceback (most recent call last):
  File "<ipython-input-17-b65148a562f7>", line 1, in <module>
    x[[0,1],[0,1]] = np.array([3,1,2])
ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (2,)
In [19]: x[[0,1],[0,1]] = np.array([[3],[1]]) # not ok
Traceback (most recent call last):
  File "<ipython-input-19-d8ed57d202e6>", line 1, in <module>
    x[[0,1],[0,1]] = np.array([[3],[1]])
ValueError: shape mismatch: value array of shape (2,1) could not be broadcast to indexing result of shape (2,)
```

**Comment by pv** [comment]
Sorry, I missed the comment above about broadcast_arrays.
