### ISSUE TITLE
Array Shapes Not Aligned Bug in scipy.optimize._lsq.lsq_linear.py

### ISSUE THREAD

**Issue by rahulk64** [scipy/scipy#10711]
The issue is in regards to the file: [scipy.optimize._lsq.lsq_linear.py](https://github.com/scipy/scipy/blob/master/scipy/optimize/_lsq/lsq_linear.py)

On line 284:
```
cost = 0.5 * np.dot(r, r)
```

You can get a ValueError where trying to take the dot product of r with itself results in shapes not being aligned such as the following:

```
File "/usr/local/lib/python3.7/site-packages/scipy/optimize/_lsq/lsq_linear.py", line 284, in lsq_linear
    cost = 0.5 * np.dot(r, r)
  File "<__array_function__ internals>", line 6, in dot
ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)
```

Here is the code I used to replicate the bug:
```
import numpy as np
from scipy.optimize import lsq_linear

def getSt(A, b):
    Ast = np.sign(b)
    ones = np.ones(A.shape[1], )
    neg_ones = -1 * np.ones(A.shape[1],)
    s_t = lsq_linear(A, Ast, bounds=(neg_ones, ones), lsq_solver='lsmr', lsmr_tol='auto', verbose=2)
    return s_t

A = np.matrix("20 -4 0 2 3 ; 10 -2 1 0 -1")
k = np.matrix("20 ; 15")
k = np.resize(k, (k.shape[0],))

getSt(A, -1*k)
```

I think what fixes it is taking the transpose (r.T) as the first argument to the dot product or changing np.dot to np.vdot.

Bug produced on:
Scipy 1.3.1 
Numpy 1.17.0

**Comment by sethtroisi** [comment]
Changing `np.matrix` to `np.array` makes this code work.

**Comment by sethtroisi** [comment]
The problem is here
```
        r = A.dot(x_lsq) - b
```
if `type(A) == np.matrix` `r.shape => (1, m)`
if `type(A) == np.array` `r.shape => (m,)`

@rgommers can you advise on what is best with respect to accepting a matrix?

**Comment by rgommers** [comment]
Keeping `matrix` instances around wasn't intended here it looks like. Changing the `A = np.atleast_2d(A)` like to `A = np.atleast_2d(np.asarray(A))` should fix it.

The `atleast_2d` docstring is even misleading, it says arrays are returned, but it uses `asanyarray` so the `matrix` survives.

**Comment by sethtroisi** [comment]
@rgommers thanks for the advice here. In general do SciPy functions support np.matrix? Is it documented what does and doesn't?

**Comment by ilayn** [comment]
I don't why but `numpy.dot()` is defined differently nd vs. 1d arrays. This better converted to a matmul @ so that we don't fall for this again.

**Comment by sethtroisi** [comment]
@ilayn I believe I have added this change to the PR.

**Comment by rgommers** [comment]
> In general do SciPy functions support np.matrix?

Yes. However the vast majority of functions use `asarray`, so `matrix` input is accepted but immediate converted to `ndarray` so there's no issues with the different semantics that `matrix` has.
