### ISSUE TITLE
[Build] Build 32bit arm based version of Scipy

### ISSUE THREAD

**Issue by EdwinTsai69** [scipy/scipy#10727]
I have downloaded the Scipy source code and built it successfully.
My downloaded Spicy version is 1.2.3

After executing below command:
python setup.py build
sudo python setup.py install --prefix=/usr

I get the output folder named "scipy-1.2.3.dev0_Unknown-py2.7-linux-x86_64.egg"
When I try to import and execute in my system, I got below error log:
Traceback (most recent call last):
  File "final_to.py", line 12, in <module>
    from scipy.signal import medfilt
  File "/opt/miis_Python-2.7.3/_install/lib/python2.7/site-packages/scipy/__init__.py", line 119, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/opt/miis_Python-2.7.3/_install/lib/python2.7/site-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: /opt/miis_Python-2.7.3/_install/lib/python2.7/site-packages/scipy/_lib/_ccallback_c.so: wrong ELF class: ELFCLASS64

It seems that I'm executing a 64bit version with 32bit CPU.
However, I'm not sure if I can config that.

So, the question is -
How to config the settings?
What I need is 32bit, and ARM based config
It seems that the default config is x86 and 64bit as it shows in the folder name
Thanks for kindly help

**Comment by EdwinTsai69** [comment]
It seems that we should config the GCC as ours
but we don't know how to config it in setup.py or any other way
Does anyone know how to assign a particular GCC to build?

**Comment by EdwinTsai69** [comment]
I think the config of cross compiler is form this file:
/usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.py
 'CC': 'x86_64-linux-gnu-gcc -pthread',
It is the data from sysconfig

However, we are still not sure how to replace it us our prticular corss compiler
Does scipy source package support to config it?

**Comment by EdwinTsai69** [comment]
I think the config of cross compiler is form this file:
 /usr/lib/python2.7/plat-x86_64-linux-gnu/_sysconfigdata_nd.py
 'CC': 'x86_64-linux-gnu-gcc -pthread',
 It is the data from sysconfig

However, we are still not sure how to replace it as our prticular corss compiler
 Does scipy source package support to config it?

**Comment by rgommers** [comment]
Cross-compiling is very problematic with `distutils`. I think your best bet is to see how it's done for `conda` / `conda-forge`. Berryconda supports ARMv7I (32-bit): https://github.com/jjhelmus/berryconda

This is not something that's actionable for SciPy. `numpy.distutils` is picking up some cross-compiling fixes over time, and it works with the conda compilers now (which is a cross-compiler to the same system). More fixes should go there. So I'll close this issue. Would be great to hear if Berryconda or something else works for you in the end though.

**Comment by EdwinTsai69** [comment]
Hi @rgommers ,

Thanks for your reply.
I think we may understand what you mean.
We will try to evaluate the risk to decide to go on or not.

We got a final question to consult with your professional knowledge.
We have checked the official document:
https://scipy.github.io/devdocs/building/linux.html

And we notice this:
python setup.py config --compiler=intel build_clib --compiler=intel build_ext --compiler=intel install

Is it a way to config cross-compile?
What's the source of keyword "intel" in it?
Can we just replace it as a absolute path of our cross-compile?
Thanks for your kindly and helpful support.


Best regards,
Edwin

**Comment by rgommers** [comment]
> Is it a way to config cross-compile?

no, it's simply a way to select the compiler to use.

> What's the source of keyword "intel" in it?

The Intel compilers (ICC, IFort). E.g. https://github.com/numpy/numpy/blob/master/numpy/distutils/intelccompiler.py

> Can we just replace it with the absolute path of our cross-compile?

no, that won't work

**Comment by EdwinTsai69** [comment]
@rgommers , 
Got it and we will update the result if we still decide to go on.
Anyway, thanks for your kindly and helpful reply again.
Have a good day to you.
