### ISSUE TITLE
dll load error scipy\special\__init__.py  Line 641 from ._ufuncs import *

### ISSUE THREAD

**Issue by mldavis99** [scipy/scipy#10721]
My issue is about ...

While running the Winpython Default checker this DLL Load Error Occurred

#### Reproducing code example:

```
C:\Program Files\WPy64-3740\python-3.7.4.amd64\lib\site-packages\scipy\special\__init__.py in <module>
    639 from .sf_error import SpecialFunctionWarning, SpecialFunctionError
    640 
--> 641 from ._ufuncs import *
    642 
    643 from .basic import *

ImportError: DLL load failed: The specified module could not be found.
```

Sample code to reproduce the problem:

![image](https://user-images.githubusercontent.com/4325699/63646679-c2cb1900-c6d3-11e9-9b91-0c87a7e9c2f6.png)

#### Error message:

```
ImportError                               Traceback (most recent call last)


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

#### Scipy/Numpy/Python version information:

```
1.3.0 1.16.4 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
```

**Comment by person142** [comment]
Hey @mldavis99; hope you don't mind but I edited your markdown a bit; a lot of important bits had been left between `<!-- -->`, which won't show up in the compiled text.

**Comment by rlucas7** [comment]
@mldavis99 are you using the dev setup for scipy? I usually get a similar message when I pull from upstream master into my local repo.  Fix for me is ‘git clean -xdf’ the. Rerun the inplace build from root of dev directory for scipy.

**Comment by person142** [comment]
Looks like this is a WinPython distribution, which we don't distribute, so this is likely better taken up with them. Also, based on the error it's likely that there are conflicting SciPy packages installed. Closing this since I don't think it's an issue on our side, but feel free to continue the discussion.
