### ISSUE TITLE
fftconvolve casts to float64

### ISSUE THREAD

**Issue by ajoan12** [scipy/scipy#10729]
My issue is about when using [scipy.signal.fftconvolve](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.fftconvolve.html), the result of the convolution does not respect the original type of the arrays if they are on np.float128, and casts down to np.float64. 

#### Reproducing code example:

```
import numpy as np
from scipy.signal import fftconvolve

a = np.array([[1,2,3],[4,5,6]]).astype(np.float128)
b = a.transpose()

print(type(a[0,0]))
# <class 'numpy.float128'>
print(type(b[0,0]))
# <class 'numpy.float128'>

c = fftconvolve(a,b)

print(type(c[0,0]))
# <class 'numpy.float64'>
```

#### What it might be:

In the case that the inputs are real, the output is returned to real by the method [np.array.real](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.real.html) on [line 428](https://github.com/scipy/scipy/blob/v1.3.0/scipy/signal/signaltools.py#L420-428). This method casts the result from complex to float: from the documentation:

> The real component of the complex argument. If val is real, the type of val is used for the output. If val has complex elements, the returned type is float.

I think that the input suffers the folloging transformations:

```
float128 -> [fftn] -> complex128 -> [ifftn] -> float64
```

and this is suported by the code:

```
a = np.array([[1,2,3],[4,5,6]]).astype(np.complex128)
print(type(a[0,0]))
#<class 'numpy.complex128'>

c = a.real
print(type(c[0,0]))
#<class 'numpy.float64'>
```

This should not happen as there is a loss of information that is not advertised anywhere.

**Comment by ajoan12** [comment]
It seems that the complex128 is done with [two float64](https://docs.scipy.org/doc/numpy/user/basics.types.html?highlight=complex128), meaning that the information is lost while doing the fastfourier transform, and this might not be salvageable.

**Comment by peterbell10** [comment]
>It seems that the complex128 is done with two float64, meaning that the information is lost while doing the fastfourier transform, and this might not be salvageable.

This happens because there are weren't any long double transforms. The result is cast instead of emmitting `ValueError` because it is using `np.fft.rfft` internally which has the policy to downcast long doubles, unlike `scipy.fftpack`.

This is fixed by gh-10361, on current master:
```python
In [7]: x = np.random.randn(1024, 10).astype(np.float128)
In [8]: fftconvolve(x, x).dtype
Out[8]: dtype('float128')
```

Thanks anyway @ajoan12
