### ISSUE TITLE
Goodness of fit tests for distributions with unknown parameters

### ISSUE THREAD

**Issue by lesshaste** [scipy/scipy#10737]
**Is your feature request related to a problem? Please describe.**

People often want goodness of fit tests where they don’t know the parameters of the relevant distribution. There are many methods available to do this, for example https://en.m.wikipedia.org/wiki/Lilliefors_test and from https://en.m.wikipedia.org/wiki/Anderson%E2%80%93Darling_test

 “The Anderson–Darling test is a statistical test of whether a given sample of data is drawn from a given probability distribution. In its basic form, the test assumes that there are no parameters to be estimated in the distribution being tested, in which case the test and its set of critical values is distribution-free. However, the test is most often used in contexts where a family of distributions is being tested, in which case the parameters of that family need to be estimated and account must be taken of this in adjusting either the test-statistic or its critical values”

However scipy currently has no goodness of fit tests when the parameters are unknown afaict.

**Describe the solution you'd like**

Is scipy.stats a good place to add such goodness of fit tests?

**Describe alternatives you've considered**

 In R there seem to be a number of packages to do this. E.g. https://cran.r-project.org/web/packages/KScorrect/index.html

**Additional context (e.g. screenshots)**

**Comment by ConorMcNamara** [comment]
Correct me if I'm wrong, but I believe statsmodels has (although limited) what you're looking for.

For example, https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.normal_ad.html has Anderson-Darling for unknown mean and variance, but only for a normal distribution. 

And https://www.statsmodels.org/stable/generated/statsmodels.stats.diagnostic.lilliefors.html is their implementation of lilliefors.

Again, they are quite limited and might not quite be what you're looking for.

**Comment by lesshaste** [comment]
Yes however statsmodels  has tests for normal and exponential random variables only.  This is quite limited. Ideally we would have tests for all the distributions that exist in scipy.

**Comment by OnlyBelter** [comment]
I am also looking for this Kolmogorov-Lilliefors Test (K-L test).

**Comment by mdhaber** [comment]
@lesshaste Doesn't [scipy.stats.anderson](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.anderson.html) do what you're looking for? In the codebase:

https://github.com/scipy/scipy/blob/b5d8bab88af61d61de09641243848df63380a67f/scipy/stats/_morestats.py#L1766-L1777

`_Avals_norm ` are the ones for from the Wikipedia article you linked for Case 3, when both mean and variance are unknown:
![image](https://user-images.githubusercontent.com/6570539/158518146-7cb565fc-40ed-4dfc-98f4-51e26790c349.png)

(last row)
There is a correction that adjusts for the number of samples, and interpolation is used to get a p-value. 

Of course, there are several things to be desired:
* Larger range of p-values, or on-the-fly calculation of p-values using a Monte Carlo test
* More distributions
* Other tests (e.g. KL)

But we do have some functionality for you.

w.r.t. the first point, I haven't researched this carefully, but it seems reasonable to me to use a simple Monte Carlo approach to get p-values that are probably more accurate than the ones currently returned by `anderson`.

```python3
import numpy as np
from scipy import stats

rng = np.random.default_rng(3)

size = 10000
sample = rng.normal(size=size)

def statistic(sample):
    return stats.anderson(sample, dist='norm')[0]

res = stats.monte_carlo_test(sample, rng.normal, statistic, n_resamples=9999)
alpha = np.array([0.5, 0.25, 0.15, 0.1, 0.05, 0.025, 0.01])  # 
percentile = (1 - alpha)*100
critical_values = stats.scoreatpercentile(res.null_distribution, percentile)
print(critical_values)
```
prints
```
[0.3392179  0.46656921 0.56401377 0.63282984 0.73645927 0.85842631
 1.03623988 1.18666595]
```
Compare against those in [D'Agostino](https://www.lexjansen.com/nesug/nesug91/NESUG91049.pdf), which are quite different from Stephens' above:

![image](https://user-images.githubusercontent.com/6570539/158522727-3eb9d5f2-ca61-4014-b604-e91c43c2ab9a.png)

So another simple thing we could do to improve this is to use D'Agostino's critical values.
