### ISSUE TITLE
Add loguniform distribution

### ISSUE THREAD

**Issue by rth** [scipy/scipy#10745]
**Is your feature request related to a problem? Please describe.**

When randomly sampling a variable over several orders of magnitude, it is often useful to sample uniformly on a log scale. This could be done with a `loguniform` distribution. 

For instance, 
 - this would be very useful when randomly sampling hyper-parameters in machine learning (https://github.com/scikit-learn/scikit-learn/issues/9919)
 - in science fields where variables can vary by several orders of magnitude (astrophysics, plasma physics to take a few), it is common to compute values on a `logspace` grid. `loguniform` would then be the equivalent in the randomized case.  

The [SO issue about it](https://stackoverflow.com/questions/43977717/how-do-i-generate-log-uniform-distribution-in-python) receives around 3k visits/ year.

**Describe the solution you'd like**

The solution is basically,
```
def loguniform(low=0, high=1, size=None):
    return np.exp(np.random.uniform(low, high, size))
```
but following the `scipy.stats` API. A partial implementation can be found in https://github.com/scikit-learn/scikit-learn/pull/11232 

**Describe alternatives you've considered**

Manually computing this distribution each time (or vendor it in  projects that need it) is also not ideal. 

There are already a number of distribution with an applied log function: `loggamma`, `loglaplace`, `lognorm`.

If an implementation for `scipy.stats.loguniform` was proposed, would it be accepted?

**Comment by rkern** [comment]
> If an implementation for `scipy.stats.loguniform` was proposed, would it be accepted?

Yes.

**Comment by astromancer** [comment]
@rth This is already implemented as `stats.reciprocal`.   I suspect the majority of the community would be in favour of renaming, (or at least making an alias) to `loguniform` to make this more discoverable.
```
from scipy import stats
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
a, b = 1, 4
x = np.linspace(a, b)
ax.plot(x, stats.reciprocal(a, b).pdf(x))
```
![logUniform](https://user-images.githubusercontent.com/5623552/64424117-7ce55c00-d0a8-11e9-8a39-ac2271ee7602.png)

**Comment by rth** [comment]
Indeed, thanks @astromancer !
