### ISSUE TITLE
Malformed documentation page for docs.scipy.org

### ISSUE THREAD

**Issue by steve-the-bayesian** [scipy/scipy#10748]
The documentation at https://docs.scipy.org/doc/scipy/reference/sparse.html has a spacing issue near the top of the page.  The signature for bsr_matrix extends into the next column.  Screen shot attached.

I'm reading this on a mac (Mojave 10.14.6) , with Google chrome (Version 76.0.3809.132 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/5853653/63981553-7a657f80-ca74-11e9-8295-16cdc20808c5.png)

**Comment by rgommers** [comment]
weird, works fine for me:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/98330/63988122-90346e00-ca8f-11e9-99e6-798f59851579.png">

does anyone else see this?

**Comment by mdhaber** [comment]
Ok on my Android phone using chrome.

**Comment by steve-the-bayesian** [comment]
A colleague sitting next to me saw the same error.  We have the same
hardware and chrome version, but I think that shows it isn't e.g. a weird
chrome plugin.

**Comment by tylerjereddy** [comment]
Yes, I reproduced the issue on MacBook:

macOS Mojave -- 10.14.5 (18F132)
Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)


![image](https://user-images.githubusercontent.com/7903078/64033542-e514ca80-cb09-11e9-8cc1-8afeef893738.png)

But not on Desktop Ubuntu 18.04.3 LTS with Chrome 76.0.3809.100 (Official Build) (64-bit)

**Comment by ilayn** [comment]
No issues on mobile 68.02 or desktop 68.02 Firefox  windows 10

**Comment by mkg33** [comment]
I also have this issue on a Mac with OS Yosemite (10.10.5) with Chrome Version 76.0.3809.100 (Official Build) (64-bit). 

![issue](https://user-images.githubusercontent.com/26354268/64491927-27f34280-d26e-11e9-8bf3-0118107d566f.jpg)

**Comment by ilayn** [comment]
Do you mind checking also with an alternative browser so we can triangulate the OS or Chrome? 

Probably related to this 10% - 90% business somehow

![image](https://user-images.githubusercontent.com/1303842/64491984-eca54380-d26e-11e9-9464-29b2e14170fa.png)

**Comment by mkg33** [comment]
Works totally fine in the very old Safari Version 8.0.8 (10600.8.9), so it must be a Chrome issue.
![issue2](https://user-images.githubusercontent.com/26354268/64492252-625ede80-d272-11e9-8a53-24b2f5acd1e4.jpg)

**Comment by WarrenWeckesser** [comment]
On Mac OS X 10.12.6, these browsers render correctly:
* Firefox, 69.0 (64-bit)
* Brave, Version 0.68.132 Chromium: 76.0.3809.132 (Official Build) (64-bit)

However, Safari (Version 12.1.1 (12607.2.6.1.2)) shows the glitch.

**Comment by rgommers** [comment]
We switched Sphinx themes, so this bug report no longer applies. Current rendering at http://scipy.github.io/devdocs/reference/sparse.html looks fine:

<img width="552" alt="image" src="https://user-images.githubusercontent.com/98330/118328969-bd94aa00-b506-11eb-9d21-4b809ca8226d.png">

So I'll close this issue. Thanks all.
