### ISSUE TITLE
Installing numpy==1.14.6 and scipy==1.0.1 at the same time now fails

### ISSUE THREAD

**Issue by 1fish2** [scipy/scipy#10749]
Installing numpy==1.14.6 and scipy==1.0.1 at the same time into a new pyenv virtualenv:

    pip install numpy==1.14.6 scipy==1.0.1 --no-binary numpy,scipy --force-reinstall

used to work but now it produces a weird error:

    RuntimeError: Python version >= 3.5 required.
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

The pip folks wrote, [details in Issue 6945](https://github.com/pypa/pip/issues/6945):

> You're hitting this issue, due to the use of setup_requires in scipy 1.0.1 -- it's trying to install numpy before allowing further execution, which doesn't work well with pip. The use of setup_requires is not compatible with pip.

Did the setup.py for SciPy 1.0.1 change recently?

**Comment by rgommers** [comment]
> Did the setup.py for SciPy 1.0.1 change recently?

No it didn't.

What changed here is very likely to be the `pip` version you're using. Can you downgrade `pip` and see if it goes away? Try going back one minor version at a time: 19.2 -> 18.1 -> 10.0.1 -> 9.0.3

**Comment by rgommers** [comment]
Not that it matters much by the way which `pip` version changed behavior (I'm guessing 10.0 or 18.0), it's not going to be fixed anyway. The workaround given on the pip issue you filed (first installing `numpy` then `scipy`) is basically permanent for SciPy < 1.3.0. For >= 1.3.0 SciPy ships a `pyproject.toml` which makes things work with recent `pip` versions.

I'll close this because there's nothing we can do about this. Please feel free to continue the conversation though, any conclusions you reach are interesting.

**Comment by 1fish2** [comment]
Good idea!

I tested versions of `pip` back to 8.1.2, then `pip` 9.0.3 with `wheel` back to 0.31.1, then `setuptools` back to 38.3.0, `six` back to 1.11.0, and `pbr` back to 4.0.2. In all cases it gets `RuntimeError: Python version >= 3.5 required.`

FYI, I'm OK with the workaround but that error message is misleading and I'm sure it used to work...

**Comment by rgommers** [comment]
yeah that error message is quite odd. the `numpy,scipy` after `--no-binary` seems odd. not likely, but it could also be related to PyPI getting versions wrong; we've gotten some odd bug reports for NumPy about 1.17.0 being picked up for `pip-2.7` even though that's no longer supported and the trove classifiers seem right.

if you want to put your full build log (add `-v`) in a gist and link it, I'm happy to have a look

**Comment by 1fish2** [comment]
Cool! Here's a [pip install -vvv](https://gist.github.com/1fish2/e7f7722c862ce98c79d611f469b66070) gist.

The `--no-binary numpy,scipy` is get the installer to read `~/.numpy-site.cfg` to link them to a specific OpenBLAS. Is there another way? Installing binaries would save considerable time.

**Comment by 1fish2** [comment]
Wait. `pip install numpy==1.14.6 scipy==1.0.1` successfully installs both, and they're linked to the correct openblas in `'/usr/local/opt/openblas/lib'` according to `np.show_config()` and `scipy.__config__.show()`. That's without `--no-binary` and `~/.numpy-site.cfg`.

Does it know to use brew's OpenBLAS over Mac's Accelerate framework? Have I been doing it the hard way all this time for no reason, or to make our setup instructions work on Linux where apt-get doesn't get a recent OpenBLAS?

**Comment by 1fish2** [comment]
[The pip folks figured out](https://github.com/pypa/pip/issues/6945#issuecomment-526479930) that

> What changed is the newest version of numpy no longer supports Python 2.
>
> scipy 1.0.1 likely has setup_requires="numpy" or something along those lines. Thus, when installing, easy_install will try to install the latest version that matches that requirement, which no longer supports Python 2, as the error message suggests.
>
> easy_install does not understand newer metadata (like python_requires) which means it chooses a version that is incompatible with the running interpreter.

**Comment by rgommers** [comment]
> Does it know to use brew's OpenBLAS over Mac's Accelerate framework?

no, without `--no-binary` you'll get the wheel, and that ships with OpenBLAS inside.

Yep, it's all `easy_install`'s fault:
```
      File "/var/folders/_b/q30qg_l50b5gvqd8y4_wb9h00000gn/T/easy_install-ptQ8A8/numpy-1.17.1/setup.py", line 31, in <module>
        if sys.version_info[0] < 3:
    RuntimeError: Python version >= 3.5 required.
```

**Comment by 1fish2** [comment]
That helps.

Would it be useful to file an issue for SciPy and Numpy to document how to install them linked to a specific BLAS library? (OpenBLAS 0.3.5 works well whereas 0.3.3, 0.3.6, and 0.3.7 have problems and 0.3.4 won't install on macOS.)

I discovered the `--no-binary` + `~/.numpy-site.cfg` technique from the [site.cfg.example file](https://github.com/numpy/numpy/blob/master/site.cfg.example).

**Comment by rgommers** [comment]
A PR would help, filing an issue not so much probably .... I know that the build docs need work, but there's limited energy for doing that. Where were you looking for it to begin with? https://numpy.org/devdocs/reference/distutils_guide.html ?

**Comment by 1fish2** [comment]
Sure. I can send PRs for the different repos, and happily tune them per feedback.

I'm not sure which are all the "install" pages to add to. There's

* https://scipy.org/install.html,
* the 3 sub-docs of https://docs.scipy.org/doc/scipy/reference/building/index.html,
* https://numpy.org/doc/1.17/user/building.html (and earlier versions if that makes sense?), and
* https://github.com/scipy/scipy/blob/master/INSTALL.rst.txt but Google doesn't find it on `site:scipy.org`.

**Comment by rgommers** [comment]
> https://numpy.org/doc/1.17/user/building.html

Yes, I think that's the right one to add more detail to for linking BLAS/LAPACK. The other pages you list above can link to that.

> (and earlier versions if that makes sense?)

No, we don't go back to update old versions. Please create a PR only against the `master` branch.
