### ISSUE TITLE
Scipy crashes with Illegal instruction

### ISSUE THREAD

**Issue by prakaashkpk** [scipy/scipy#10753]
Scipy is crashing in my Docker container.

```py
# test.py

initial_values = [0.1 0.1 0.1]

Y = [0.0, 0.6931471805599453, 1.0986122886681096, 1.3862943611198906, 1.6094379124341003, 1.791759469228055, 1.9459101490553132, 2.0794415416798357, 2.1972245773362196, 2.302585092994046, 2.3978952727983707, 2.4849066497880004, 2.5649493574615367] 
m = 1 
boundaries = [(0, 1), (0, 1), (0, 1)]

parameters = fmin_l_bfgs_b(RMSE, x0=initial_values, args=(Y, m), bounds=boundaries, approx_grad=True)
```

```
# python3 -q -X faulthandler test.py
Fatal Python error: Illegal instruction

Current thread 0x00007ffa1c076b68 (most recent call first):
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 328 in _minimize_lbfgsb
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 199 in fmin_l_bfgs_b
  File "test.py", line 75 in entry
  File "test.py", line 80 in <module>
Illegal instruction (core dumped)
```

#### Scipy/Numpy/Python version information:
```
scipy     1.2.2
numpy     1.16.0

# python --version
Python 3.7.4

```

**Comment by rth** [comment]
The code snipped is not valid because `RMSE` is not defined,  `initial_values` is not a valid list and imports are missing. Please edit it so it can be run as a standalone script.

**Comment by pv** [comment]
"Illegal instruction" generally means the executable is not compatible with the processor, e.g. scipy or linear algebra libraries compiled with incompatible processor arch or extensions (e.g. vectorized floating point).

**Comment by prakaashkpk** [comment]
Thanks for the quick response. The code is just the snippet. I can run the same code in other environment without problem.

I have problem when we upgrade openblas to `openblasp-r0.3.3`

**Comment by prakaashkpk** [comment]
I do understand why the code is crashing. The problem starts appearing only when we upgrade the alpine to `3.9` from `3.7` along with openblas  upgraded to `openblasp-r0.3.3` for the same set of inputs. 

Do we have any known issues in openblasp-r0.3.3 related to SIGLL if you remember any. Our container OS is `alpine 3.9` which runs on `Ubuntu 16.04, x86_64`

**Comment by pv** [comment]
SIGILL only appears if some component was compiled for incompatible architecture.
How did you install Scipy?

**Comment by prakaashkpk** [comment]
Okay, yeah I have checked the details of that bug, yet to try fix version mentioned in the report. 
Here is how I install scipy and numpy on my container. 

Numpy and Scipy get compiled/installed from the source. Alpine doesn't have prebuilt binaries yet. 

```Dockerfile
FROM python:3.7.4-alpine3.9

RUN apk add openblas-dev linux-headers gcc python3-dev \
 apk add --virtual build-dependencies build-base gcc libffi-dev libstdc++ \
 && pip install --no-cache-dir numpy==1.16.0 \
 && pip install --no-cache-dir scipy==1.2.2
```

**Comment by pv** [comment]
I'd suggest running numpy and scipy test suites to see if something else also fails.

**Comment by prakaashkpk** [comment]
Thanks @pv. I will try. 

We don't have a problem with `scipy` or `numpy` directly. The code hasn't changed at all. The problem started appearing when we upgraded to `alpine 3.9` which bundles `openblas 0.3.3-r2`. 

```
Current thread 0x00007ffa1c076b68 (most recent call first):
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 328 in _minimize_lbfgsb
  File "/usr/local/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 199 in fmin_l_bfgs_b
```

#### Similar bug reports
https://github.com/scipy/scipy/issues/5102
https://github.com/jupyter/notebook/issues/1082

**Comment by prakaashkpk** [comment]
Closing the issue. The crash is because of `openblas`.

**Comment by mbaudin47** [comment]
#21027 seems to be similar. Is there any workaround?
