### ISSUE TITLE
interpolative.estimate_rank precision?

### ISSUE THREAD

**Issue by stanleyjs** [scipy/scipy#10769]
Hi,

The function `interpolative.estimate_rank(A,eps)` requests an epsilon.  Is this akin to the threshold one would use when estimating the numerical rank using the singular values of a matrix(1)? Or is it more like a machine precision(2)?  In this case, is there an appropriate method for selecting the threshold?

Here is an example of what I mean in (1).
```
import numpy as np
from scipy.linalg import interpolative
M = np.random.randn(1000,200)
thresh = interpolative.estimate_spectral_norm(M)* np.finfo(M.dtype).eps*max(M.shape)
rank = interpolative.estimate_rank(M,thresh)//8
```

**Comment by ilayn** [comment]
Sorry for the ridiculous delay. The eps is used here 

https://github.com/scipy/scipy/blob/8dba340293fe20e62e173bdf2c10ae208286692f/scipy/linalg/src/id_dist/src/iddp_aid.f#L342

It's the scale that multiplies the nonzero entry of a Householder vector. A bit unorthodox use of eps but it is indeed closer to your second definition; machine-precision like.
