### ISSUE TITLE
scipy.signal.convolve2d produces incorrect values for large arrays

### ISSUE THREAD

**Issue by SamG97** [scipy/scipy#10761]
When calling `scipy.signal.convolve2d` on a large array, the values produced are incorrect for high indices in the large array.

#### Reproducing code example:
```python
import numpy as np
import scipy.signal

def conv(n):
    a = np.array([[(x + y) % 2 for x in range(1000)] for y in range(n)])
    count = scipy.signal.convolve2d(a, [[1, 1]])
    print(np.where(count == 2))

conv(1000)
conv(300000)
```

#### Error:

The matrix `a` above is a matrix of alternating 0s and 1s and so convolving it with a kernel of `[[1, 1]]` should produce a matrix of all 1s (apart from boundaries where it should be 0 at one edge). Hence, there should never be a value of 2 in the matrix and so the `where` function call should find no results and return empty arrays. The above code works as expected for a small 1000 x 1000 matrix but not for a 1000 x 300,000 matrix and gives the following output:
```
(array([], dtype=int64), array([], dtype=int64))
(array([268436, 268436, 268436, ..., 299999, 299999, 299999]), array([  1,   2,   3, ..., 997, 998, 999]))
```

#### Scipy/Numpy/Python version information:
```
1.3.1 1.16.4 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
```

**Comment by peterbell10** [comment]
Observation: `log2(300000 * 1000 * 8) = 31.160` (8 is `sizeof(int64_t)`)
This looks like an `int` is overflowing in the indexing calculation, that would explain why it only happens for large sizes.

As a test, 
```python
>>> n = 2**31 // (1000 * 8)
>>> conv(n)
(array([], dtype=int64), array([], dtype=int64))
>>> conv(n + 2)
(array([268436, 268436, 268436, 268436, 268436, 268436, 268436, 268436,
[...]
```

Also, note that `n + 1 = 268436` which is the first index that shows an error in the example.

**Comment by johnhcc** [comment]
I've just experienced this one too. I don't quite follow your example, @peterbell10; if you are correct about the ```int``` overflow, is it possible to predict the smallest array size where this error pops up?

**Comment by peterbell10** [comment]
>if you are correct about the `int` overflow, is it possible to predict the smallest array size where this error pops up?

That's what the example shows. `shape=(n + 2,1000)` should be the smallest array size that overflows. Where `n` is given in the first line.

**Comment by mcara** [comment]
I have encountered this error as well. In my case, an example would be:

```python
In [1]: import sys
   ...: import numpy as np
   ...: import scipy
   ...: from scipy import signal
   ...:
   ...: print(scipy.__version__, np.__version__, sys.version_info)
   ...: np.random.seed(1)
   ...: kern = np.ones((5, 5))
   ...: d = np.random.random((27000, 29833))
   ...: c = signal.convolve2d(d, kern, boundary='symm', mode='same')
   ...: print(np.all(np.isfinite(c)))
1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=7, releaselevel='final', serial=0)
False
```

Here is how convolved image looks like: 
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/5985250/82401767-aec90380-9a28-11ea-959e-0baf641d3109.png">
