### ISSUE TITLE
Back to old constraints format on scipy.optimze.minimize for custom optimizer

### ISSUE THREAD

**Issue by LouiseCannoni** [scipy/scipy#10771]
When using custom optimizer on scipy.optimize.minimize like that:
scipy.optimize.minimize(fun, x0, args=(), method='custom, jac=jac, hess=hess, bounds=bounds, constraints=([NonLinearConstraints, LinearConstraints]))
Scipy does not give to the custom optimizer the NonLinearConstraint and LinearConstraint scipy objects like in scipy version 1.1 but gives the old way of defining constraints and gives the same objects for linear and non linear. When going through the code source we can see that a function "new_to_old" is added. Is it possible to get back to the NonLinearConstraint and LinearConstraint objects for a custom optimizer ?

**Comment by mdhaber** [comment]
@antonior92 @andyfaff Thoughts on how this should be modified?
```
    if meth == 'trust-constr':
        for i, con in enumerate(constraints):
            if not isinstance(con, new_constraint_types):
                constraints[i] = old_constraint_to_new(i, con)
    else:
        # iterate over copy, changing original
        for i, con in enumerate(list(constraints)):
            if isinstance(con, new_constraint_types):
                old_constraints = new_constraint_to_old(con, x0)
                constraints[i] = old_constraints[0]
                constraints.extend(old_constraints[1:])  # appends 1 if present
```
Maybe add an option to minimize that would bypass constraint conversion or force it in one direction?

**Comment by andyfaff** [comment]
My preference is to pass unchanged bounds/constraints to the custom solver, and let it deal with them. Presumably if the user passes in their own bounds/constraints then the solver should be able to deal with them. Around L583:

```
   if meth == '_custom':
        return method(fun, x0, args=args, jac=jac, hess=hess, hessp=hessp,
                      bounds=bounds, constraints=constraints,
                      callback=callback, **options)

    if bounds is not None:
        bounds = standardize_bounds(bounds, x0, meth)

    if constraints is not None:
        constraints = standardize_constraints(constraints, x0, meth)

    if meth == 'nelder-mead':
```

It's either that, or make the custom solver take new-style everything.

**Comment by mdhaber** [comment]
> pass unchanged bounds/constraints to the custom solver,
That sounds good to me.
