### ISSUE TITLE
min_only=true djisktra infinite loop with duplicate indices

### ISSUE THREAD

**Issue by fcollman** [scipy/scipy#10774]
My issue is about scipy.sparse.csgraph.djisktra with the min_only=True option.

Seems that if you pass duplicate indices into this function you can induce an infinite loop. 

Solution would maybe be to raise an exception in this case?
Or is there a way to a handle it? Take the first unique index as the true target and throw out the others so that no paths lead to them?

#### Reproducing code example:

```
Sample code to reproduce the problem
```

#### Error message:
code never returns..

#### Scipy/Numpy/Python version information:
```
1.1.0 1.14.3 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
@fcollman thanks for the report. Can you add a self-contained code example to reproduce the issue you're seeing?

**Comment by fcollman** [comment]
sure working on it now... I think this is likely a bug with code i submitted so was going to follow it up with a PR that at least has a test with a failure, but hopefully a fix too.

**Comment by larsoner** [comment]
@fcollman that would be great, thanks for looking into it
