### ISSUE TITLE
scipy.special.hyperu broken

### ISSUE THREAD

**Issue by kylematoba** [scipy/scipy#10784]
My issue is about ...

`scipy.special.hyperu` giving bad values (wholly apart from its other problems, e.g. https://github.com/scipy/scipy/issues/10402, https://github.com/scipy/scipy/issues/2287)

#### Reproducing code example:

```
import numpy as np
import scipy.special


def _phi(a: float,
         b: float,
         x: np.ndarray) -> np.ndarray:
    return scipy.special.hyp1f1(a, b, x)


def _psi(a: float,
         b: float,
         x: np.ndarray) -> np.ndarray:
    return scipy.special.hyperu(a, b, x)


def _dn_phi(a: float,
            b: float,
            x: np.ndarray,
            n: int) -> np.ndarray:
    # from S.2.7.3 of Polyanin and Zaitsev, page 773
    return scipy.special.poch(a, n) / scipy.special.poch(b, n) * _phi(a + n, b + n, x)


def _dn_psi(a: float,
            b: float,
            x: np.ndarray,
            n: int) -> np.ndarray:
    # from S.2.7.3 of Polyanin and Zaitsev, page 773
    return (-1) ** n * scipy.special.poch(a, n) * _phi(a + n, b + n, x)


def _verify_solution_of_degenerate_hypergeometric_problem(a: float, b: float) -> None:
    x = np.linspace(.01, +3, 100)
    disc_1 = x * _dn_phi(a, b, x, 2) + (b - x) * _dn_phi(a, b, x, 1) - a * _phi(a, b, x)
    disc_2 = x * _dn_psi(a, b, x, 2) + (b - x) * _dn_psi(a, b, x, 1) - a * _psi(a, b, x)
    np.testing.assert_allclose(disc_1, 0, atol=1e-10)
    np.testing.assert_allclose(disc_2, 0, atol=1e-10)


if __name__ == "__main__":

    _verify_solution_of_degenerate_hypergeometric_problem(-1, +.5)
    _verify_solution_of_degenerate_hypergeometric_problem(+1, +.5)
    _verify_solution_of_degenerate_hypergeometric_problem(+.1, +.5)

```
No problems with the Kummer M function, but U is broken in a weird way -- it works for some, but not most, parameter values.

#### Scipy/Numpy/Python version information:

```

1.3.1 1.16.0 sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)

```

**Comment by person142** [comment]
Hey @kylematoba, would you mind making your reproducing example more minimal? In particular, it would be helpful if you could give

- A list of points where you're getting bad values
- The relative error at those points (you can use `mpmath.hyperu` to get a solution that's accurate to double precision after maybe fiddling with the `dps` a bit)

**Comment by kylematoba** [comment]
I apologise, the problem was pebkac. 

It _is_ possible to get fairly large errors, e.g.,

```
a, b, x = 1.12, -3.10, 4.14
scipy_value = scipy.special.hyperu(a, b, x)
mpmath_value = mpmath.hyperu(a, b, x)
rel_err = np.abs(scipy_value / mpmath_value - 1)
abs_err = np.abs(scipy_value - mpmath_value)
print(rel_err / 1e-7)
print(abs_err / 1e-7)
14.0768394585322
1.22837561164491
```
but not in a way that does not seem to be already known. I'd not have opened an issue on the basis of the above alone.

I see you've just added a proper docstring to this one, which would have helped me, so thanks for that!

**Comment by person142** [comment]
@kylematoba no problem-`hyperu` definitely needs more improvements. We're getting there, but it's a process.
