### ISSUE TITLE
LU with full pivoting

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#10788]
I'd like to add [`?getc2`](http://www.netlib.org/lapack/explore-html/de/d39/group__double_g_eauxiliary_ga2ecd51f7842c100d6b4ecc99119c012f.html) and [`?gesc2`](http://www.netlib.org/lapack/explore-html/de/d39/group__double_g_eauxiliary_gac6998d2ed1a92cc28708602db64f3db6.html) into `scipy.linalg.lapack`, perhaps also working them into `lu_factor` and `lu_solve` with an option like `complete_pivoting`.

Does this sound like a good idea?

This would be my first time wrapping low level code. I was thinking I could follow another PR like gh-10537 or gh-10741 as an example, and of course there is f2py documentation, but any tips you wish you knew before you started doing this sort of thing would be appreciated! I would like to add a bit about this to the developer documentation when I'm done.

**Comment by ilayn** [comment]
I started a very beginner like document in the wiki some time ago. Don't know if it is useful but has some basics in place. Maybe use it for a skeleton?

**Comment by ilayn** [comment]
https://github.com/scipy/scipy/wiki/WIP:-A-brief-How-to-for-wrapping-LAPACK-routines

The most obvious requirement is to find out when these are added. If it is past 3.4 we can't add them now

**Comment by mdhaber** [comment]
No later than 3.1, it looks like:
http://www.netlib.org/lapack/explore-3.1.1-html/zgetc2.f.html

**Comment by ilayn** [comment]
Indeed they are quite old so no problem there. 

> How much overhead would it add if I were to start from there, BTW? Just curious

I think I didn't get the question. You mean starting from cython_lapack? I don't think there is much there to start with.

**Comment by mdhaber** [comment]
I should try it; I'm sure I'll need your help to correct them!

**Comment by mdhaber** [comment]
@ilayn please check out gh-10797 when you get a chance.

**Comment by mdhaber** [comment]
Closed by gh-10797
