### ISSUE TITLE
Deprecate complex kernel for `expi`?

### ISSUE THREAD

**Issue by person142** [scipy/scipy#10786]
Typically the exponential integral `Ei` (`special.expi`; see https://dlmf.nist.gov/6.2#E5) is only defined for real values. This is because it doesn't have a proper analytic continuation around the negative real axis. If you want a complex version of `Ei`, then you should just use `E1` (`special.expi1`; see https://dlmf.nist.gov/6.2#E2), which has a branch cut on the negative real axis.

`specfun` however, defines a complex version of `Ei`, which we wrap. It just naively extends the relation `Ei(-x) = -E1(x)` to the complex plane. This leads to a discontinuity between the real/complex implementations around the negative real axis:

```
>>> import scipy.special as sc
>>> sc.expi(-1 + 1e-12j)
(-0.21938393439552062+3.1415926535894254j)
>>> sc.expi(-1 - 1e-12j)
(-0.21938393439552062-3.1415926535894254j)
>>> sc.expi(-1)
-0.21938393439552062
```

This is not how we typically handle things in special (e.g. `loggamma` and `gammaln` are distinct functions for exactly this reason). Can we get away with deprecating the complex variant of `expi` (`exp1` is a drop-in replacement), or at this point are we stuck with just documenting the strangeness?

**Comment by pv** [comment]
Not sure about this yet. Mathematica iirc does the same strange thing, so some people may expect it. OTOH, I don't think changes here would cause the same level of fallout as with gammaln, as it's a rarer function.

**Comment by person142** [comment]
> Mathematica iirc does the same strange thing

Oof, so it does.

**Comment by person142** [comment]
And so does Mpmath... I guess we're stuck with it.
