### ISSUE TITLE
Documentation version 1.3.1 not available.

### ISSUE THREAD

**Issue by MatthewFlamm** [scipy/scipy#10794]
https://docs.scipy.org/doc/scipy/reference/ points to version 1.3.0.  Other x.x.1 releases have documentation [here](https://docs.scipy.org/doc/).

**Comment by tylerjereddy** [comment]
I think we aren't too strict about uploading the x.x.1 point releases as long as the major release is linked, but yes that's likely my fault. I'm trying to help with the *Nature Methods* manuscript revisions & other things, but will aim to come back to this.

**Comment by MatthewFlamm** [comment]
I consider documentation to be as important as the code itself.  Here is one example of where there is a new feature in 1.3.1 that is totally opaque to most users because there is no published documentation.

https://github.com/scipy/scipy/blob/master/scipy/integrate/_ivp/ivp.py#L273

**Comment by MatthewFlamm** [comment]
My comment was intended as my 2 cents on the policy on documentation not being uploaded for all releases, not a personal comment on this release itself.  This is clearly not how I wrote it however, so I apologize.

I would like to amend my comment to:  "It should be considered to change the policy to upload documentation for all releases, as I consider the documentation to be as important as the code itself".

Also, thank you for keeping the comments civil.

**Comment by ev-br** [comment]
Tyler, do you need a hand on building/uploading the 1.3.1 docs?

**Comment by tylerjereddy** [comment]
I'll try to get it done shortly--`make dist` is a bit of pain from a portability / versatility / error handling standpoint--it failed on a mac and WSL in last two days on that branch. Actually, it failed for most of my recent uploads, I just worked around the failure by making a few targets separately.

**Comment by ev-br** [comment]
I still have my setup from pre-1.0 times, can check if it still works. DM me at gmail if that's helpful.

**Comment by tylerjereddy** [comment]
Alright, I think I've uploaded the stuff properly now & the cross-linked PR to adjust the main page is open. (Real) Ubuntu works a bit better for me..

**Comment by ev-br** [comment]
Thanks Tyler

**Comment by MatthewFlamm** [comment]
Thanks from me as well.  Sorry again for my poorly articulated comment.  I really appreciate the effort that goes into maintaining this wonderful package.  Keep up the good work!
