### ISSUE TITLE
In gaussian_kde(), the covariance matrix should be multiplied by kde.factor**2 rather than kde.factor.

### ISSUE THREAD

**Issue by Bai-Jiang** [scipy/scipy#10814]
In the current implementation, the kde.factor is computed as (1/n)^(1/(d+4)) if using Scott's method or (4/(d+2)/n)^(1/(d+4)) if using Silverman's method.

According to the theory of kernel density estimation, the covariance matrix should be multiplied by kde.factor ** 2 rather than kde.factor. See https://en.wikipedia.org/wiki/Multivariate_kernel_density_estimation

**Comment by tylerjereddy** [comment]
I'll tentatively label as a defect based on the description, but a stats guru may very well correct me on that.

**Comment by tillahoffmann** [comment]
Wouldn't go as far as a self-declared stats guru, but the current implementation seems to be correct (see below). Whilst the factor is evaluated in "standard deviation scale", the factor is correctly applied to the covariance matrix used to evaluate the kernel.

https://github.com/scipy/scipy/blob/bf3c6471aba06cf6a96843d62f5198ec90e15cf1/scipy/stats/kde.py#L579-L580
