### ISSUE TITLE
Errors with the Yeo-Johnson Transform that also Appear in Scikit-Learn

### ISSUE THREAD

**Issue by bcbrock** [scipy/scipy#10821]
My issue is about issues with the Yeo-Johnson transform that also appear in scikit-learn

#### Reproducing code example:

```
import numpy as np
import scipy
import sklearn
sklearn.show_versions()
a = np.array([
 3251637.22,620695.44,11642969.00,2223468.22,85307500.00,16494389.89,
  917215.88,11642969.00,2145773.87,4962000.00,620695.44,651234.50,
 1907876.71,4053297.88,3251637.22,3259103.08,9547969.00,20631286.23,
12807072.08,2383819.84,90114500.00,17209575.46,12852969.00,2414609.99,
 2170368.23])
scipy.stats.yeojohnson(a)
```

#### Error message:

```
System:
    python: 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
executable: /anaconda3/bin/python
   machine: Darwin-17.7.0-x86_64-i386-64bit

Python deps:
       pip: 19.2.3
setuptools: 38.4.0
   sklearn: 0.22.dev0
     numpy: 1.17.0
     scipy: 1.3.1
    Cython: 0.29.13
    pandas: 0.24.2
matplotlib: 2.1.2
    joblib: 0.13.2
/anaconda3/lib/python3.6/site-packages/scipy/stats/morestats.py:1465: RuntimeWarning: divide by zero encountered in log
  loglike = -n_samples / 2 * np.log(trans.var(axis=0))
/anaconda3/lib/python3.6/site-packages/scipy/optimize/optimize.py:1961: RuntimeWarning: invalid value encountered in double_scalars
  p = (x - v) * tmp2 - (x - w) * tmp1
/anaconda3/lib/python3.6/site-packages/scipy/optimize/optimize.py:1962: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = 2.0 * (tmp2 - tmp1)
/anaconda3/lib/python3.6/site-packages/scipy/optimize/optimize.py:1960: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/anaconda3/lib/python3.6/site-packages/scipy/optimize/optimize.py:1959: RuntimeWarning: invalid value encountered in double_scalars
  tmp1 = (x - w) * (fx - fv)
Out[7]:
(array([0.23389584, 0.23389584, 0.23389584, 0.23389584, 0.23389584,
        0.23389584, 0.23389584, 0.23389584, 0.23389584, 0.23389584,
        0.23389584, 0.23389584, 0.23389584, 0.23389584, 0.23389584,
        0.23389584, 0.23389584, 0.23389584, 0.23389584, 0.23389584,
        0.23389584, 0.23389584, 0.23389584, 0.23389584, 0.23389584]),
 -4.275407328878737)
```

#### Scipy/Numpy/Python version information:

Please see above

**Comment by NicolasHug** [comment]
The trick that is used in https://github.com/scipy/scipy/pull/10072 (fox BoxCox)  is that:

1. The loglikelihood only depends on the transformed values through their variance
2. Var(X) = Var(X + constant)
3. The numerical instability is caused by a constant offset = `1 / λ` in the transformed values. We can just remove it: the variance stays the same and the loglikelihood is still correct.

While that offset is constant for boxcox, in the yeo johnson transform the offset is different depending on the sign of the input (see [original paper](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C44&q=https%3A%2F%2Fwww.jstor.org%2Fstable%2Fpdf%2F2673623.pdf&btnG=): it's either `1 / λ` or `1/(2-λ)`

Since we wouldn't be offsetting the data with a constant offset, I don't think we can use the same trick here :/

@WarrenWeckesser any ideas?

**Comment by WarrenWeckesser** [comment]
@NicolasHug, I tried the same thing when I saw first saw this issue, but discovered like you did that the trick doesn't work for Yeo-Johnson.  I don't know of any other neat ways to avoid the problem.

The standard advice for a dataset such as the one given above is to rescale the data to avoid those huge values.  Also note that for such a dataset of positive, extremely large values, the Yeo-Johnson transform is very nearly the same as the Box-Cox transform.  So the practical advice I would give for handling such a dataset is to just use Box-Cox.

**Comment by WarrenWeckesser** [comment]
> ...just use Box-Cox

Here's a demonstration that shows Box-Cox works and is basically the same as Yeo-Johnson for this dataset:

```
In [51]: from scipy.stats import yeojohnson, boxcox                             

In [52]: a = np.array([ 
    ...:  3251637.22,620695.44,11642969.00,2223468.22,85307500.00,16494389.89, 
    ...:   917215.88,11642969.00,2145773.87,4962000.00,620695.44,651234.50, 
    ...:  1907876.71,4053297.88,3251637.22,3259103.08,9547969.00,20631286.23, 
    ...: 12807072.08,2383819.84,90114500.00,17209575.46,12852969.00,2414609.99, 
    ...:  2170368.23])                                                          
```
Compute the Box-Cox transform:
```
In [53]: t, lam = boxcox(a)                                                     

In [54]: t                                                                      
Out[54]: 
array([6.65422423, 6.38492396, 6.82594185, 6.5973772 , 7.0436898 ,
       6.86814926, 6.45367528, 6.82594185, 6.59191432, 6.71426406,
       6.38492396, 6.39356694, 6.57368775, 6.68593552, 6.65422423,
       6.65455889, 6.80104698, 6.89428799, 6.83767735, 6.60800064,
       7.04893154, 6.87316482, 6.83811511, 6.60994816, 6.59366744])

In [55]: lam                                                                    
Out[55]: -0.12834803147077975
```
Use `lam` as the parameter in the Yeo-Johnson transform.  Note that the transformed values agree with the Box-Cox values to 7 or more significant digits.
```
In [56]: yeojohnson(a, lam)                                                     
Out[56]: 
array([6.65422427, 6.38492425, 6.82594186, 6.59737727, 7.0436898 ,
       6.86814927, 6.45367547, 6.82594186, 6.59191439, 6.71426409,
       6.38492425, 6.39356721, 6.57368783, 6.68593556, 6.65422427,
       6.65455893, 6.80104699, 6.894288  , 6.83767736, 6.60800071,
       7.04893154, 6.87316483, 6.83811512, 6.60994822, 6.59366751])
```

**Comment by mdhaber** [comment]
@thomasjpfan would you be willing to submit the same fix as in scikit-learn/scikit-learn#20653 over here? Thanks for considering it!

**Comment by thomasjpfan** [comment]
> Curious if you know why scikit-learn and scipy don't just share an implementation for this one?

It was likely because scikit-learn supported an older minimum SciPy dependency that did not have yeojohnson.

>  would you be willing to submit the same fix as in 

I opened https://github.com/scipy/scipy/pull/15998 to try to fix the issue in SciPy.

**Comment by mdhaber** [comment]
Perhaps it is possible to do better with all-positive data or all-negative data (using [the trick](https://github.com/scipy/scipy/issues/10821#issuecomment-535235836) mentioned above), and maybe there is an extension that could improve precision in the general case, but I think gh-15998 is a good workaround for most practical cases.
