### ISSUE TITLE
Graph Laplacian sparse format change ruins the in-place calculation 

### ISSUE THREAD

**Issue by lobpcg** [scipy/scipy#10826]
**Is your feature request related to a problem? Please describe.**
Since https://github.com/scipy/scipy/pull/15251 the function https://docs.scipy.org/doc/scipy-1.3.0/reference/generated/scipy.sparse.csgraph.laplacian.html now support in-place calculation, without doubling the amount of memory on the output , cf. https://github.com/scikit-learn/scikit-learn/pull/14636

However, it appears that the code is not preserving the format other than COO of the graph sparse matrix - the implementation explicitly makes a copy unless the input format is COO, as at least now documented in https://github.com/scipy/scipy/pull/15251.  It's really unclear why. 

**Describe the solution you'd like**
In-place and strictly format- and type-preserving calculation with `copy=False` avoiding the memory usage spikes. Cf. https://github.com/scipy/scipy/issues/10827

**Comment by rgommers** [comment]
Seems reasonable. Can we combine gh-10827 and this? I think it's the same thing right?

**Comment by lobpcg** [comment]
> 
> 
> Seems reasonable. Can we combine [gh-10827](https://github.com/scipy/scipy/issues/10827) and this? I think it's the same thing right?

The same code and similar goals, but different and unrelated changes. May be better finish one and have it merged, then start the other, to simplify code writing and unit testing. This one would have immediate positive effects in scikit-learn with trivial changes in scikit-learn code base, so is more practically important.

**Comment by rgommers** [comment]
Makes sense. 

Looking at `_laplacian_sparse`, the implementation explicitly makes a copy unless the input format is COO, and this isn't documented. The scikit-learn PR seems to just add a `copy=True` keyword, but what seems to be needed first is an implementation that doesn't need conversion to COO. 

And then it's not 100% clear to me what the API request is: add `out=`, or really _overwrite_ the input matrix?

**Comment by lobpcg** [comment]
@rgommers  Whatever is the most memory efficient and without too much computing and coding.

**Comment by tupui** [comment]
Merged PR was said to partially address this issue.

**Comment by lobpcg** [comment]
#15391 provides a clean work-around, allowing for totally matrix-free construction of the Laplacian
