### ISSUE TITLE
Sum of a sparse matrix and an numpy.array is a numpy.matrix

### ISSUE THREAD

**Issue by homocomputeris** [scipy/scipy#10839]
`numpy.matrix` is deprecated but is returned in sparse–array operations

#### Reproducing code example:

```python
import scipy
import numpy
x = scipy.sparse.csr_matrix(np.random.rand(5,))
y = numpy.random.rand(5,)
print(x+y)
print(type(x-y))
```
gives
```
[[1.454 1.031 1.145 1.621 0.769]]
<class 'numpy.matrix'>
```

#### Scipy/Numpy/Python version information:
```
1.3.1 1.17.1 
sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
```

**Comment by perimosocordiae** [comment]
Unfortunately we're stuck with this API, as changing from matrix to array would break pretty much all existing users.

It's not feature-complete yet, but eventually we'll start directing users to https://github.com/pydata/sparse to avoid the issue altogether.

**Comment by homocomputeris** [comment]
Does it mean that SciPy will just drop `sparse`?

**Comment by perimosocordiae** [comment]
There's no current plan to stop supporting scipy.sparse as far as I'm aware of.

**Comment by homocomputeris** [comment]
I mean, it's strange that users will be derected to `pydata`, `scipy.sparse` is not getting fixed but still no dropped, and this increases the gap between NumPy, that dropped matrices, new `sparse` and the old one.

**Comment by pv** [comment]
It's not possible to "fix" the matrix semantics in scipy.sparse while maintaining backward compatibility.
So you anyway need new sparse matrix objects with numpy array-like semantics.
