### ISSUE TITLE
Error in documentation for scipy.linalg.lu_factor

### ISSUE THREAD

**Issue by mikeWShef** [scipy/scipy#10838]
Example in documentation is written as if numpy was imported as np but the import statement is from numpy import ...

https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu_factor.html#scipy.linalg.lu_factor

line 59 here:
https://github.com/scipy/scipy/blob/v1.3.0/scipy/linalg/decomp_lu.py#L59

**Comment by ilayn** [comment]
Throughout all documentation `import numpy as np` line is implied in all examples. You can still have extra imports while having np namespace

**Comment by mikeWShef** [comment]
But in this example, there are extra imports that are unused, like this:

from numpy import some_func

np.some_func(...)

**Comment by ilayn** [comment]
Yes I read a bit too quick you are right. Care to make a quick PR about it?

**Comment by mikeWShef** [comment]
will do
