### ISSUE TITLE
Unexpected behavior in linalg.blas.dtrmm wrapper

### ISSUE THREAD

**Issue by tmmsartor** [scipy/scipy#10841]
Me and @giaf observed a unexpected behavior of `scipy.linalg.blas.dtrmm(...)` with `side=1`
this assuming that:
* `side=0` means D=A*B
* `side=1` means D=B*A

### Simple example
```python
from scipy.linalg import blas
import numpy

A = numpy.array([
    [1,1],
    [0,1]
], order="f")
B = numpy.array([
    [1,4],
    [2,5],
    [3,6]
], order="f")

C1 = blas.dtrmm(1.0, A, B, side=1)
print("\nB*A:")
print(C1)
```

Wich prints:
```
B*A:
[[1. 5.]
 [2. 7.]
 [3. 6.]]
```
Instead of:
```
B*A:
[[1. 5.]
 [2. 7.]
 [3. 9.]]
```

NB: Using `order='c'` or `order='f'` when creating the numpy array does not change the result
FIY: Also `strmm` seems to be affected but I didn't investigate further.

### Environment
* scipy: 1.3.1 
* numpy: 1.17.2 
* python: sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

**Comment by EverLookNeverSee** [comment]
@tmmsartor @ilayn I would like to work on this issue.

**Comment by rgommers** [comment]
@EverLookNeverSee please go for it! There's no need to ask for permission, unless it's clear from open comments or open PR that someone is actively working on some issue, then you can just go ahead.

**Comment by ilayn** [comment]
@EverLookNeverSee Just in case you want to skip directly to the fix, it's this part 


https://github.com/scipy/scipy/blob/master/scipy/linalg/fblas_l3.pyf.src#L186

that needs a fix. But in general, better rewrite the checks more explicitly as in 

https://github.com/scipy/scipy/blob/master/scipy/linalg/fblas_l3.pyf.src#L191-L224

**Comment by bsxfan** [comment]
I am finding the same problem with `dtrmm`  with `side = 1` in scipy 1.4.1. In contrast, `dtrsm` works fine under the same circumstances.

**Comment by giaf** [comment]
IMO, the issue is that the scipy wrapper for `dtrmm` was written taking inspiration from the one for `dgemm`, i.e. assuming that general matrix multiplication and triangular matrix multiplication are similar.

However, in the BLAS API, they are quite different, while the BLAS API for `dtrmm` and `dtrsm` are fundamentally identical. So a better approach would be to take inspiration form the (working) scipy wrapper for `dtrsm` to implement the one for `dtrmm`.

**Comment by ilayn** [comment]
It's the k part in the line that I've marked above that needs a fix.

**Comment by EverLookNeverSee** [comment]
Hi @ilayn , I don't have enough experience in fortran language in order to fix this issue.
Feel free to fix it :)

**Comment by bsxfan** [comment]
While experimenting with `dtrmm`, I have discovered and logged another issue (https://github.com/scipy/scipy/issues/11606), which may have potentially wider implications in the BLAS/LAPACK interfaces.  @ilayn when you are busy with the `dtrmm` code, could you possibly check if the blas-compatibility checks there agree with what I have described in  (https://github.com/scipy/scipy/issues/11606)?

**Comment by ilayn** [comment]
These are all performed by f2py so we don't have too much control over these. But yes I will. However note that `is` operator does not check memory copies. So it needs a bit deeper investigation.

**Comment by bsxfan** [comment]
> These are all performed by f2py so we don't have too much control over these. But yes I will. However note that `is` operator does not check memory copies. So it needs a bit deeper investigation.

One can also check if the input argument (`S` or `D` in  https://github.com/scipy/scipy/issues/11606) was overwritten by `dtrmm`. I did and that supports my conclusion.

**Comment by ilayn** [comment]
@giaf @tmmsartor and others, if you have the possibility, it would be nice if you can test the fix. Otherwise I'll merge based on my own test results.

**Comment by EverLookNeverSee** [comment]
> @giaf @tmmsartor and others, if you have the possibility, it would be nice if you can test the fix. Otherwise I'll merge based on my own test results.

I am gonna test it.
