### ISSUE TITLE
BUG: special: don't warn on evaluation of `pdtr` for real inputs

### ISSUE THREAD

**Issue by person142** [scipy/scipy#10855]
`pdtr` (the Poisson CDF) is one of the "legacy cast" functions that used to take real arguments in the parameter `k` but then truncated them to integers. At some point we updated those functions to take integers but preserved the old functionality by having real arguments cast to integers and emit a warning:

```
>>> import scipy.special as sc
>>> sc.pdtr(1.5, 1)
__main__:1: RuntimeWarning: floating point number truncated to an integer
0.7357588823428847
```

The problem is that

- real arguments are a pretty reasonable input to the CDF, so the warning is unwarranted (It's pretty standard to treat the CDF as a piecewise constant function on the interval `[0, ∞)`. 
- casting doesn't work for large real arguments

So I would like to:

- Remove the legacy cast wrapper
- Add a real kernel for `pdtr`. This is pretty simple, you do `floor(k)` and then use the incomplete gamma function. (Importantly you do not cast to an integer type!)

This is backwards compatible and will also fix some frustrating quirks of the current implementation like:

```
>>> import numpy as np
>>> sc.pdtr(np.inf, 1)
nan
```

(should be 1).

**Comment by person142** [comment]
Added the "needs-decision" label to give people a chance to object.

**Comment by rlucas7** [comment]
+1 for this. Sounds reasonable and an improvement on existing behavior. 

Happy to review the PR, feel free to ping me (including via my email)

**Comment by person142** [comment]
Note: we should do this for `special.pdtrc` too. There are others too, but I don't want to muddy the waters too much in this issue.

**Comment by person142** [comment]
Haven't heard any objections, so removing the `needs-decision` label. We can move ahead once https://github.com/scipy/scipy/pull/10865 is merged.

**Comment by rlucas7** [comment]
@person142 it looks like pr #10865 is merged. 
Do you mind if I pick this one up? (unless you've already got the code sitting locally). 
I'd like to gain a little familiarity with the C code in `scipy.special` and this one seems like a good first issue for me. 

I was thinking to crib off:
https://github.com/scipy/scipy/pull/10752/files
and
https://github.com/scipy/scipy/pull/10865/files

which looks like they should fix the issue here.
Please let me know either way.

**Comment by person142** [comment]
@rlucas7 sure, go for it. Note that since the current implementation just casts to double in `igam` you can just change the signature from taking an int to taking a double with rounding while preserving back compatibility.

That plus removing the signature in the legacy wrappers and you’re done!

**Comment by rlucas7** [comment]
One thing to note I also needed to change:
`npy_double pdtr(npy_int, npy_double);`
to
`npy_double pdtr(npy_double, npy_double);`
in 
`scipy/special/_ufuncs_defs.h`
which it looks like is ignored in `.gitignore`
so I didn't commit the change to `scipy/special/_ufuncs_defs.h`
but line 183 is where the change from `npy_int` to `npy_double` needs to happen. 

`scipy/special/_ufuncs_defs.h`
isn't tracked in git. 

similarly I needed to get rid of an typdef unsafe in `scipy/special/cython_special.pyx`
which also wasn't tracked in VCS. 

Is there a reason why these files aren't in VCS?

**Comment by person142** [comment]
They are generated by the build, so you don't need to edit them by hand. Instead just build again.

**Comment by person142** [comment]
(In more detail, building runs the file `special/_generate_pyx.py`, which is what generates all those files.)

**Comment by rlucas7** [comment]
@person142 I'll open a PR with WIP, might be easier to have something to look at :)

**Comment by rlucas7** [comment]
>That plus removing the signature in the legacy wrappers and you’re done!

@person142 can you take a look at the linked PR and help me understand which parts I haven't changed/removed for legacy wrapper need to be removed?

removing:
https://github.com/scipy/scipy/blob/master/scipy/special/_legacy.pxd#L101-L105

causes a build fail, specifically, I tried deleting all the files that are calling the `pdtr_unsafe` and it broke my local build.

>(In more detail, building runs the file special/_generate_pyx.py, which is what generates all those 
> files.)

Do I understand correctly that changes to `_generate_pyx.py` file need to be made to remove the issues with the `pdtr()` function?

**Comment by person142** [comment]
> Do I understand correctly that changes to _generate_pyx.py file need to be made to remove the issues with the pdtr() function?

No, it does not need any changes.
