### ISSUE TITLE
ImportError: cannot import name spatial

### ISSUE THREAD

**Issue by Muhamadamani** [scipy/scipy#10853]
I'm using python in Abaqus, I already have scipy as same version in abaqus and I can also import scipy without any error but when I want to import spatial as: from scipy import spatial I got an error as below:
ImportError: cannot import name spatial
I wonder if someone can help me out.

**Comment by ilayn** [comment]
Can you try directly importing the library `import scipy.spatial` ?

Otherwise your installation is corrupted and/or trying to import from each other.

**Comment by amani-m** [comment]
Thanks for the reply. I tried and got this again:

>>> import scipy
>>> import scipy.spatial
ImportError: No module named spatial
>>>

**Comment by tupui** [comment]
@Muhamadamani did you solve your issue? If not could you try with the latest version of SciPy?
