### ISSUE TITLE
Statistics distribution of mannwhitneyu are not normal

### ISSUE THREAD

**Issue by AndrewUsoltsev** [scipy/scipy#10868]
When we modeling statistics mannwhitneyu using the Monte Carlo method with the number of tests N=16600 for normal samples of size 50, we obtain the following
![mannwhitney](https://user-images.githubusercontent.com/25631708/65530963-2048c480-df23-11e9-92d5-b5624ef6b101.png)
And this is not Normal distribution. 
If we use the formula from the paper https://projecteuclid.org/euclid.aoms/1177730491 then we get normal distribution of statistics

**Comment by josef-pkt** [comment]
What's the statistic in your histogram?

scipy returns some properties of the mannwhitneyu statistic but not the statistic that is used in the computation of the p-value under normality assumption

**Comment by rgommers** [comment]
Please note that `mannwhitneyu` is broken in various ways, search for open issues gives you several. It's one of the functions most in need of fixes (or more likely, deprecation and replacement).

**Comment by pv** [comment]
The other issues in mannwhitneyu probably are not relevant for this --- I don't believe (having written a different MW implementation from scratch) that there is issue in computing the `u` statistic.

**Comment by pv** [comment]
However, `alternative="two-sided"` may be necessary to make it return the expected statistic --- the default behavior seems to be a bit strange.

**Comment by AndrewUsoltsev** [comment]
Yes, `alternative="two-sided"` get normal distribution
