### ISSUE TITLE
Use keyword-only arguments in `fft`?

### ISSUE THREAD

**Issue by person142** [scipy/scipy#10874]
The new fft module has functions with a lot of keyword arguments, e.g.

https://scipy.github.io/devdocs/generated/scipy.fft.fft.html#scipy.fft.fft

Should we force these arguments to be keyword-only? The idea is that forcing keyword-only arguments allows you to more easily evolve the API because you don't have to preserve argument order. An example of where this ability would have been useful is `linalg.solve` (the deprecated `sym_pos` has to remain third and the new `assume_a` is stuck at the end):

https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve.html#scipy.linalg.solve

cc @peterbell10 @grlee77 @larsoner

**Comment by peterbell10** [comment]
Something to keep in mind is that while `scipy.fft` is new, it was also meant to maximise compatibility with both `np.fft` and `scipy.fftpack`. Ideally a simple find and replace would allow transitioning to it. So in that respect, this is sort of a breaking change.

As a compromise, we could make the arguments not in `np.fft` keyword-only:
- `workers` is completely new so no issue there
- I would hope that `overwrite_x` wasn't regularly used as a positional argument.

```python
def fft(x, n, axis, norm, *, overwrite_x, workers):
```

**Comment by grlee77** [comment]
I think Peter's proposed compromise is reasonable. I don't see any reason we would ever want to change the ordering or names of at least the first three arguments.  They have been that way for years and the position (if not the exact names (e.g. `s` vs `shape` for the 2nd argument in `fftn`) are consistent across libraries. I also suspect those three are commonly used positionally.

> I would hope that overwrite_x wasn't regularly used as a positional argument.

In `scipy.fftpack`, `overwrite_x` is the 4th argument, so by inserting `norm` in that position we have already introduced a difference for any users wanting to update legacy fftpack-based code that was specifying `overwrite_x` positionally. I think that is fine.

**Comment by larsoner** [comment]
Given the general stability of `fft` arguments over the years my sense is that it's not worth messing with the signature (slight readability loss) to preserve our ability to reorder arguments in the future.

**Comment by leofang** [comment]
Related: https://github.com/scipy/scipy/issues/10302#issuecomment-569302227

**Comment by j-bowhay** [comment]
Given this change can no longer be made in a backwards compatible way I think it is safe to close this issue
