### ISSUE TITLE
DOC: Graphical guides (using TikZ)

### ISSUE THREAD

**Issue by mkg33** [scipy/scipy#10875]
**Is your feature request related to a problem? Please describe.**
The graphical guides are part of the ongoing Google Season of Docs. 

**Describe the solution you'd like**
I propose to introduce graphical guides that would facilitate the navigation and exploration of the current documentation. They would not replace the textual guides but could serve as a visual navigational aid. I'd like to get feedback on the general look of the guides and, especially, on the colour scheme. I've already used the official colour scheme but it appears to be too dark. I then experimented with different saturation values (see screenshots below). I also have to consider accessibility issues (e.g., [here](https://accessible-colors.com)). The guides can be found [here](https://github.com/mkg33/GSoD).

**Describe alternatives you've considered**
So far, I have implemented the guides in TeX, using the TikZ package. I propose to integrate them with the main documentation using TeX4ht (I am prepared to consider other solutions if necessary).

**Additional context (e.g. screenshots)**

Update:

![hierarchy_WBS2](https://user-images.githubusercontent.com/26354268/65786946-1eb41200-e158-11e9-8583-ab0675d46d91.jpg)

Here is an example (prototype) of a graphical guide:

![hierarchy](https://user-images.githubusercontent.com/26354268/65713823-4c3a8600-e09a-11e9-921d-4db6cfa729fd.jpg)

Various saturation values:
![Screenshot 2019-09-24 at 16 53 45](https://user-images.githubusercontent.com/26354268/65707836-9832fe00-e08d-11e9-880f-86cbb11e50f2.jpg)
![Screenshot 2019-09-24 at 16 54 21](https://user-images.githubusercontent.com/26354268/65707845-9e28df00-e08d-11e9-9523-e5f894fcd746.jpg)
![hierarchy](https://user-images.githubusercontent.com/26354268/65707564-1642d500-e08d-11e9-8b65-214fae65f215.jpg)

**Comment by ilayn** [comment]
I also use TikZ extensively but from a UX perspective these images are a bit too cumbersome to make something out of it. The eyes have to "touch" almost all boxes to find the right one and that brings more difficulties, primarily creating visual burden and eventually falling back to the text list we already have. 

For mindmaps, this layout is pretty helpful but for indexing I think they are not the right one.

**Comment by larsoner** [comment]
> The eyes have to "touch" almost all boxes to find the right one and that brings more difficulties, primarily creating visual burden and eventually falling back to the text list we already have.

Perhaps if the colors were organized differently that might not be the case quite as much. Maybe if the innermost one were whiter, then the next level almost as light, then the last level darker (or invert the progression?) it would make the progression clearer. Basically give the eyes a luminance trail to follow.

But already with these colors personally I find this easier to parse than a text list would be. This might vary from person to person, but these are easy enough to ignore if people want, so +1 from me for including them (in addition to the existing text lists) in some form.

**Comment by mkg33** [comment]
@ilayn Thanks for the input. I totally see your point. But then, users differ and I think that it wouldn't do too much harm to have the visual guides (with more suitable colours) on top of the current documentation. The main motivation for the guides was that people expressed a wish to see the connections between functions, modules, etc. I suppose that experts will never need to consult a visual guides but it could be appreciated by beginners.

@larsoner Thanks! The colours will definitely be different. We could also consider splitting the guides to make them more readable. I suppose it will depend on a given references section that is to be visualised. I particularly like your idea with creating a trail. That could make it clearer.

**Comment by ilayn** [comment]
Just to clarify I'm not against having these (should have probably mentioned this first). I am only a bit concerned about the layout. In TikZ any layout is kind of easy to achieve (let me know if you need an extra hand. I was quite involved with TikZ in the past).

**Comment by mkg33** [comment]
I do like constructive criticism! Do you have any other alternative layouts in mind? I intended to create an easy 'quick reference' structure. That's why I arranged the functions (in an alphabetical order) anti-clockwise because I assumed that it would facilitate quicker reading. I'm open to suggestions.

**Comment by ilayn** [comment]
A simple tree would be much easier in my opinion, say, http://www.texample.net/tikz/examples/work-breakdown-structure/

But maybe can be a mix of both. Also if you use 

```latex
\usepackage{fontspec}
\setmonofont{Consolas}
 ```

it will use a better monospaced font (choose your own favorite) instead of that ugly typewriter font.

**Comment by mkg33** [comment]
Good idea, that was my initial approach but I thought it would be simply converting the text lists to graphical lists. We'll see what others prefer. The typewriter font is actually my favourite (:D) but I'll experiment with alternative fonts. Thanks again!

**Comment by rgommers** [comment]
I like the font too. WBS diagram makes sense I think; it'll also save space so for larger modules it's easier to make it fit.

**Comment by mkg33** [comment]
I'm more and more inclined to choose the WBS diagram. Saving space is another reasonable argument. I was actually concerned about that. IMHO the 'mind map' concept seems to be more visually appealing but the WBS solution is clearer and far more practical. Plus it really does save a lot of time and is more uniform in terms of future maintenance (i.e., I really can't write guidelines saying what angle to use between neighbouring arrows, etc.).

**Comment by mkg33** [comment]
@ilayn I've redesigned the guide following your tips. What do you think about the new version? I kept the ugly font for now ;-)

**Comment by larsoner** [comment]
The tree looks nice, it's fine by me.

FYI @mkg33 if you open a WIP PR for this, CircleCI will render the docs, and you can just paste a link to the latest rendering. It's a potentially nicer way to iterate than you having to paste, and people scroll up to the top comment, etc.

**Comment by mkg33** [comment]
@larsoner Glad to hear that! Thanks for the tip, I'll bear it in mind. Anyway, I guess we can close this issue very soon.

**Comment by rgommers** [comment]
I like the tree layout! Less artistic, but easier to read.

Also made me spot a content issue: I think the "plotting" and "visualizing flat clusters" headings should be merged. Perhaps simply "visualizing" or "visualizing clusters'?

**Comment by ilayn** [comment]
Tree is indeed prettier to my taste.

**Comment by mkg33** [comment]
@rgommers Thanks! The content issue: I thought about it but wanted the graphical guide to be a faithful representation of the textual guide, i.e., in the reference guide, the two categories (visualising flat clusters and plotting) are separate. Moreover, they are separated by a large chunk of text. I mean, semantically, they should fall under the same category but shall I distort the reflection of the text guide? It would make perfect sense, though.

![Screenshot 2019-09-28 at 14 21 59](https://user-images.githubusercontent.com/26354268/65816428-c0d90600-e1fb-11e9-8be6-b26bf1f47706.jpg)

 By the way, that rendering glitch shows up again on another Mac and a newer Safari version... I've updated my comment in issue #10748, hope that helps.

**Comment by rgommers** [comment]
Let's just fix that text version then. The way it's separated now is quite odd.
