### ISSUE TITLE
Check finite difference gradient approximation in a random direction

### ISSUE THREAD

**Issue by shoyer** [scipy/scipy#10888]
[`scipy.optimize.check_grad`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.check_grad.html) is very convenient for checking analytical gradient calculations.

Unfortunately, it's not really practical for even moderately large problems, because computing finite differences in every direction can be painfully slow.

One practical way to test such gradients, which I learned from the [autograd](https://github.com/HIPS/autograd) project, is calculate finite differences in a random direction instead, which can be compared to a projection of the analytical gradient. This isn't as thorough as `check_grad` but in practice seems to catch most of the same bugs, and runs way faster.

Would something like this be welcome in SciPy, maybe in the form of a `random_projection=True` keyword argument for `check_grads`?

**Comment by rgommers** [comment]
That seems like a good idea to me.

**Comment by Mau-dvr75** [comment]
Hi, shoyer. One question. 
Why should we need to compute finite differences in every direction to compare analytical gradients with numerical ones??

**Comment by czgdp1807** [comment]
I would like to work on it. Seems like instead of checking in all the directions we will randomly pick a direction and see if it works or not, right?

**Comment by czgdp1807** [comment]
@shoyer Is the above approach correct (roughly)? I can raise a PR and there we can discuss more on this.

**Comment by czgdp1807** [comment]
I looked into the code of `scipy.optimize.grad_check` and found out that, as of now only, (f(x + h) - f(x))/dx inside `approx_derivative` function in `_numdiff.py`. In other words, directional derivatives are not computed. So, in this issue, do we need to do that like picking a random direction and then comparing the projection of analytical derivative with the numerically approximated derivative in that random direction?

**Comment by shoyer** [comment]
Internally, `grad_check` calls `approx_fprime`, which in turns calls `approx_derivative` and ends up looping over dimensions, e.g., inside `_dense_difference`:
https://github.com/scipy/scipy/blob/44e31b1eb202ef91caad059952ba268d2610a60b/scipy/optimize/_numdiff.py#L553

Instead, we could have an option to pick a single _random_ direction to compute the gradient in, instead of checking [every one-hot vector](https://github.com/scipy/scipy/blob/44e31b1eb202ef91caad059952ba268d2610a60b/scipy/optimize/_numdiff.py#L551). Then the comparison is not to the full gradient vector, but rather the projection of the gradient in that direction.

Mathematically, instead of checking the function `f(x)` where `x` is a vector, we check finite differences on the formula `g(w) = f(x + w v)` where `w` is a scalar and `v` is a random vector, using `∂g/∂w = ∇f(x) · v` from the chain rule.

JAX has an implementation of this that might be a useful reference, though it's checking slightly more complex formulas for Jacobian-vector and vector-Jacobian products:
https://github.com/google/jax/blob/96575216a79e3f930b2624fe56d3bcf462b42e5a/jax/test_util.py#L250-L285

**Comment by czgdp1807** [comment]
Thanks @shoyer for the ideas and detailed explanation.

>  but it makes sense to pick something with a non-zero component in most directions in order to catch bugs (rather than using a one-hot vector).

I was thinking the same. Using one of all the one-hot vector might be beneficial in the sense that we won't be required to take the projection of analytical gradient, instead just indexing it will work. But yeah, bugs may escape. Using a fully random normalized vector would be much better.

I will raise a PR on Monday for this and we can implement and discuss different ways there. Thanks.
