### ISSUE TITLE
scipy.signal.signaltools._fftconv_faster has incorrect estimates

### ISSUE THREAD

**Issue by drorspei** [scipy/scipy#10887]
My issue is about the function `scipy.signal.signaltools._fftconv_faster`. The function has a logical error, causing most convolutions to use fft when the direct method would save a large factor.

Code example, showing that `_fftconv_faster` returns that fft is faster even when multiplying by a scalar kernel, when the signal is large enough.
```
>>> from scipy.signal.signaltools import _fftconv_faster
>>> _fftconv_faster(np.empty(1), np.empty(1000000), "full")
True
```

Here is the impact in timing on a lenovo yoga 920, intel core i7 8th gen, 16gb ram, running Ubuntu 18.04:
```
>>> import numpy as np
>>> from scipy.signal import convolve
>>> h = np.random.randn(1)
>>> x = np.random.randn(1000000)
>>> %timeit convolve(x, h, method="direct")
714 µs ± 14 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
>>> %timeit convolve(x, h)
70.2 ms ± 1.34 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

The automatic run, which chooses fft, is slower by a x100 factor.

The root cause for this is the incorrect estimate for the number of multiplications in the direct convolution algorithm. This is line 506 in v1.3.1, and 497 of the latest commit [8a3e9fa] as of writing this issue:
```
direct_time = (x.size * h.size * _prod(out_shape))
```

The correct direct computation time is actually:
```
direct_time = min(x.size, h.size) * _prod(out_shape)
```

The big oh constants, in the tens of thousands, were probably calculated as a ratio to the incorrect estimate. So a fix to the direct estimate will need to be accompanied by a recalculation to the constants.

**Comment by peterbell10** [comment]
Ref #10427 for recalculating the big O constants.

**Comment by stsievert** [comment]
Thanks for this issue – I'll likely use this over in [stsievert/scipy-convolve-timings][1]. 

> The correct direct computation time is actually: `direct_time = min(x.size, h.size) * _prod(out_shape)`

Why should it be `min(x.size, h.size)` instead of `x.size * h.size`? If correct I presume this will have to be the minima along each dimension.

[1]:https://github.com/stsievert/scipy-convolve-timings/

**Comment by peterbell10** [comment]
> Why should it be `min(x.size, h.size)` instead of `x.size * h.size`?

For each element in the output, you calculate `sum(a * b)` where `a` and `b` are the appropriately shifted input arrays. That operation has linear time complexity, not quadratic. 

> If correct I presume this will have to be the minima along each dimension.

In theory, I think that's right. However, thinking about this again, it's might actually be the maximum along each dimension because of https://github.com/scipy/scipy/issues/5967#issuecomment-519861440.

**Comment by drorspei** [comment]
Hej hej
Nah, it's not over each dimension. The formula I gave is based directly on the C code and is exactly the number the multiplications.

**Comment by peterbell10** [comment]
>The formula I gave is based directly on the C code and is exactly the number the multiplications.

How did you determine that?

**Comment by drorspei** [comment]
I created a class with mul and add and passed arrays of it on for all shapes with ndim in [1,4] and shapes in some ndim-cube. I'll look for the code to post it up here, but it wasn't anything complicated.

**Comment by stsievert** [comment]
The formula `min(x.size, h.size) * out.size` is right and has O(n<sup>2</sup>) time complexity, at least when in the 1D setting and `x` and `out` have `n` elements and the kernel has (say) `n // 10` elements. In the same case, the formula `x.size * h.size * out.size` has O(n<sup>3</sup>) time complexity which is clearly wrong.

And I suppose number of operations of `method="fft"` is actually
``` python
sum([n * log(n) for n in zip(x.shape, h.shape, out.shape)]) + out.size
```
which accounts for the multiplication in the Fourier domain. This would require two different big-oh constants, and the second one will be much smaller than the first (so I'll stick with only the first term).

**Comment by peterbell10** [comment]
As in #10904, the big O of the fft method is 
```python
full_out_shape = [n + k - 1 for n, k in zip(x.shape, h.shape)]
_prod(full_out_shape) * sum(math.log(n) for n in full_out_shape)
```

**Comment by peterbell10** [comment]
To explain: `x` and `h` are padded to `full_out_shape` before taking the FFT. The FFT has complexity `x0 * log(x0)` for a 1D array, in an ND array their are `_prod(full_out_shape) / x0` repetitions of the 1D transform.  Or `log(x0) * _prod(full_out_shape)` per axis.

**Comment by drorspei** [comment]
I've run all ffts of powers of two up to twenty on my lenovo yoga 920, and
the complexity looks more linear than nlogn. I think it would be
interesting to do this on a few cloud instances, say some EC2s, and see if
this replicates on other hardware with similar line fits.
What do you think?

**Comment by peterbell10** [comment]
> I've run all ffts of powers of two up to twenty on my lenovo yoga 920, and
the complexity looks more linear than nlogn.

Bear in mind that `O(n)` and `O(n log(n))` look almost identical on that scale:

![Figure_1](https://user-images.githubusercontent.com/13238737/68157559-c84fa580-ff45-11e9-9b1d-cbdd63f29db7.png)

And also that the reality is much more complicated than big O notation:

![TimingsBig-1](https://user-images.githubusercontent.com/13238737/68157899-78251300-ff46-11e9-9b8d-22f558cd8530.png)

**Comment by drorspei** [comment]
I totally agree about the reality part. Writing an automated script to test
it on multiple EC2 hardware might shine some light on this, and also, maybe
more importantly, give us a repeatable way to produce appropriate O
constants.

**Comment by stsievert** [comment]
> I've run all ffts of powers of two up to twenty on my lenovo yoga 920,

What version of SciPy? The FFT implementation will be improved in SciPy 1.4.

> a repeatable way to produce appropriate O constants.

Good point. I'm not sure how straightforward that'll be; FFT timing depends strongly on the base:

``` python
[ins] In [6]: %timeit np.fft.fft(np.arange(2**20))
8.35 ms ± 143 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

[ins] In [7]: %timeit np.fft.fft(np.arange(2**20 + 1))
42.7 ms ± 4.08 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

I'm using SciPy's `curve_fit` in [stsievert/scipy-convolve-timings][1] to determine the constant of `fft_time / direct_time`.

[1]:https://github.com/stsievert/scipy-convolve-timings/

**Comment by drorspei** [comment]
I'm on the latest pip, so you're right, not the latest.

Regarding the base, note that the ffts are on smooth numbers, while 2^20+1
is far from smooth.

**Comment by drorspei** [comment]
I've uploaded the code that checks the complexity of the direct method:
https://github.com/drorspei/misc/blob/master/notebooks/conv-complexity.ipynb

There isn't a nice formula once you include the other modes, e.g. valid and same. Even for full mode the formula is different for single dimension.

**Comment by drorspei** [comment]
@stsievert The fft improvements in scipy 1.4 are not included in numpy :)
So need to time the fft directly in scipy. Here it is on my laptop (unfortunately significantly slower), also with timings using `next_fast_len(2**20+1)` - coming up pretty much the same as `2*20`:
```
(scipy-3.8.0) ➜  sub git:(master) ipython
Python 3.8.0 (default, Nov  7 2019, 11:08:07) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.9.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from numpy.fft import rfft as npfft
In [2]: from scipy.fft import rfft as spfft
In [3]: import numpy as np

In [4]: %timeit npfft(np.arange(2**20))
31.8 ms ± 479 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [5]: %timeit npfft(np.arange(2**20))
31.4 ms ± 517 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [6]: %timeit spfft(np.arange(2**20))
21.8 ms ± 373 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [7]: %timeit npfft(np.arange(2**20+1))
325 ms ± 14.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [8]: %timeit spfft(np.arange(2**20+1))
172 ms ± 3.38 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [9]: from scipy.fftpack.helper import next_fast_len

In [10]: %timeit npfft(np.arange(next_fast_len(2**20+1)))
25.6 ms ± 369 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [11]: %timeit spfft(np.arange(next_fast_len(2**20+1)))
18 ms ± 55.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [12]: import scipy.version

In [13]: scipy.version.version
Out[13]: '1.4.0.dev0+5681835'

In [14]: np.version.version
Out[14]: '1.17.3'
```

**Comment by peterbell10** [comment]
>Even for full mode the formula is different for single dimension.

The 1d case uses `np.convolve` instead of `sigtools._correlateND`.

**Comment by drorspei** [comment]
> > Even for full mode the formula is different for single dimension.
> 
> The 1d case uses `np.convolve` instead of `sigtools._correlateND`.

Do you know why? They seem to require the same number of multiplications.

Another major thing to note is that the mode should really be taken into account in `_fftconv_faster`. For `direct` and `valid`, on equal shapes, there are `prod(shape)` multiplications, which is much smaller than for `direct` and `full` on the same shapes, which needs more than `prod(shape)^2` multiplications.
