### ISSUE TITLE
Highpass filters result in non-zero mean values using “scipy.signal.firwin”

### ISSUE THREAD

**Issue by LDuan3008** [scipy/scipy#10886]
Hi all,

I am learning to use filters provided by "Scipy" for analysis of some climate data. While the lowpass filters work good, I found that the highpass filters generated by "scipy.signal.firwin" produces non-zero mean values. The signal I created for testing is as follow:

```
fs = 1  # each data point represents one-year annual mean results
t = np.arange(300) / fs
comp1 = 1.5*np.sin(2*np.pi/50*t-20/180*np.pi)
comp2 = 2.3*np.sin(2*np.pi/ 8*t+18/180*np.pi)
comp3 = 20
wave = comp1+comp2+comp3
```
I created the filter with window type = "hamming" and calculated the highpass component as below:

```
win_size = 31
w_cutoff_period = 31
w_cutoff_freque = 1 / w_cutoff_period
w = w_cutoff_freque / (fs/2)
weights = signal.firwin(31, w, window='hamming', pass_zero='highpass')
output_high = np.convolve(wave, weights, 'same')
```
The returned time series "output_high" (after removing the first and last 30 data points) has a mean value of ~3.5, which is supposed to be zero.

I compared results with other highpass filters (FFT and "Butterworth") using the same data, both of which give me a mean value close to zero. It seems that the mean value produced using "scipy.signal.firwin" is related to the `comp3` in the signal function (which is 20 here) and will increase with a larger value of `comp3`.

I am a little confused here and am wondering why it happens? Any suggestions would be very appreciated. 

Thanks!

**Comment by rohitsanj** [comment]
Hey @starrystarrynightt,
I'd like to look into this issue. Please help me out with a couple of things. Could you please update your code snippets to include `import` statements so that it can be copy-pasted? 

> I compared results with other highpass filters (FFT and "Butterworth") using the same data, both of which give me a mean value close to zero.

Can you please provide code snippets for ^these cases as well? 

> The returned time series "output_high" (after removing the first and last 30 data points) has a
mean value of ~3.5, which is supposed to be zero.

I took a Digital Signal Processing class last semester. I have not come across computing mean of the filter output. Can you point me to resources that explain the significance of the mean value being close to zero?

Thanks!

**Comment by roryyorke** [comment]
The original example is missing an `fs=fs` in the `signal.firwin` call.  The issue can be closed.

With Scipy 1.7.1, this:

```python
import numpy as np
from scipy import signal

fs = 1  # each data point represents one-year annual mean results
t = np.arange(300) / fs
comp1 = 1.5*np.sin(2*np.pi/50*t-20/180*np.pi)
comp2 = 2.3*np.sin(2*np.pi/ 8*t+18/180*np.pi)
comp3 = 20
wave = comp1+comp2+comp3


win_size = 31
w_cutoff_period = 31
w_cutoff_freque = 1 / w_cutoff_period
w = w_cutoff_freque / (fs/2)
weights = signal.firwin(31, w, window='hamming', pass_zero='highpass', fs=1)
output_high = np.convolve(wave, weights, 'same')
print(f'{output_high[30:-30].mean() = }')
```

results in 

```
output_high[30:-30].mean() = -0.07073314021676408
```

**Comment by WarrenWeckesser** [comment]
Thanks for pointing out the correction, @roryyorke.  I'm closing the issue.
