### ISSUE TITLE
Default value of equal_var parameter should be False (scipy.stats.ttest_ind)

### ISSUE THREAD

**Issue by anandna123** [scipy/scipy#10889]
**Is your feature request related to a problem? Please describe.**
I was looking into the ttest_ind functionality and saw that the default value of equal_var parameter is True and this would be accurate/applicable only in cases where population variances are equal. 

**Describe the solution you'd like**
Considering the fact that most of the cases variance would be different, doesn't it make sense to change the default value of equal_var parameter to False in maybe next version? Many times the non-statistical/non-mathematical background users aren't aware that the value should be False if variances are different. 

**Describe alternatives you've considered**
Backward compatibility shouldn't be an issue for newer versions, is what I believe. Please let me know your thoughts...

**Additional context (e.g. screenshots)**

**Comment by tylerjereddy** [comment]
> Backward compatibility shouldn't be an issue for newer versions

It looks to me like changing the default value of that kwarg would break backward compatibility. Not saying it can't be done if `stats` people agree though. But it would typically have to be worth the disruption it might cause.

**Comment by anandna123** [comment]
Hey @tylerjereddy, thanks for the comment.

I said that the backward compatibility won't be affected because I believe these 2 settings (of equal_var = False or True) will lead to pretty much the same t-score (or very similar) if variances are actually equal. 

The only time student t-test (equal_var = True) value would differ from welch's t-test is if there are significant differences in variance and in that case Student’s t-test shouldn't be used. Anyway people who are aware of this would have set equal_var = False and if they weren't aware, they are using default setting which is wrong. So it's either backward compatible or it changes the result to correct result. Please correct me if my understanding is incorrect.

My 2 cents is that updating this default setting (equal_var = False) would probably get the results right in most of the future cases. This would be a step in the right direction and could be accomplished with clear notification in documentation. I would let the **stats** people decide which is best and the right thing to do...

Thanks,
Anand

**Comment by tylerjereddy** [comment]
>  I would let the **stats** people decide which is best and the right thing to do

sounds good

**Comment by mdhaber** [comment]
@josef-pkt I see you have worked with `ttest_ind` for a long time, so I thought you might be a good person to ask about this?

**Comment by mdhaber** [comment]
To maintain backwards compatibility, we can't really change this unless we were to create a new function, and I don't think that's warranted here. Thanks for the suggestion @anandna123. Do let us know if there's something we can do to make the documentation even clearer; we wouldn't want the existing default to cause users to make mistakes.
