### ISSUE TITLE
Unclear documentation for scipy.special.lpmn

### ISSUE THREAD

**Issue by thezoltan94** [scipy/scipy#10895]
There was an issue thread a few years ago about this same uncertainty with scipy.special.lpmv, as to whether or not the Condon-Shortley phase was included. The documentation only saying it calculates the associated Legendre polynomials and their derivatives, with no accompanying equation or note that the phase is included, is pretty unclear.

For the record, the specfun.lpmns code called in scipy.special.lpmn does appear to include the Condon-Shortley phase, and I think the documentation really would benefit from including this.

**Comment by rlucas7** [comment]
Hi @thezoltan94
It looks like the latest scipy release does indeed include a sentence in the notes: 
https://github.com/scipy/scipy/blob/1ff7107669f3f861197fe47354c3a320e68d0147/scipy/special/add_newdocs.py#L6693

you can check your scipy version by starting your python environment and running:
```
import scipy
print(scipy.__version__)
```
and check, if you have 1.4.0 you should see the sentence.
It looks like that line has been in the `special` package for a couple years based on this commit:
https://github.com/scipy/scipy/commit/ca9d7fca69a683b5394f27f86f43c7a6a535dd7a

Perhaps you have an older version prior to adding that into the docs?

**Comment by rgommers** [comment]
Question was answered and no further follow-up, so I'll close this. Thanks both.

**Comment by marc1701** [comment]
Reopening this as the question was not answered. The above reference to the docs is a note for lpmv() rather than lpnm()
