### ISSUE TITLE
Possible typo in the a equation of optimize/dual_annealing

### ISSUE THREAD

**Issue by deng-cy** [scipy/scipy#10892]
In the source code dual_annealing function, Line 260 writes
`pqv_temp = (self.acceptance_param - 1.0) * (
            e - self.energy_state.current_energy) / (
                self.temperature_step + 1.)`
I believe this is calculating the result of the brackets (from Ref. 4, Xiang Y, Gong XG. Efficiency of Generalized Simulated Annealing. Physical Review E, 62, 4473 (2000).):
![20191001140830](https://user-images.githubusercontent.com/40417707/65988152-4f948f80-e455-11e9-88fd-21247acf94ee.png)
where you have K=1.

If I am right, then the code should be
`pqv_temp = (self.acceptance_param - 1.0) * (
            e - self.energy_state.current_energy) / (
                self.temperature_step)+1.`

Can you please check whether the code is right here? Thanks.

**Comment by sgubianpm** [comment]
Yes, we checked with Yang, this is actually a typo. It can be corrected even though this typo will not affect the overall performance of dual annealing in terms of number of objective function call and success rate.

**Comment by sethtroisi** [comment]
@sgubianpm I'm surprised that you predict this will not affect number of objective calls or success rate. It seems like with this typo the function rarely (never?) accepts uphill energy jumps (see my tests in #12347 that show 0 accepts with positive delta energy)  so I believe the algorithm becomes ("recovers") a decent algorithm which I assume would have different number of function calls / success rate.

**Comment by deng-cy** [comment]
I tested with both cases. Not to much difference, but I still could feel them. With this typo, it will be slower.

**Comment by sgubianpm** [comment]
> I tested with both cases. Not too much difference, but I still feel it. With this typo, it will be slower.

I was not expecting much differences indeed but I think that was better to have this typo fixed. Thanks a lot!
