### ISSUE TITLE
optimize._lbfgsb setulb() function violates parameter bounds

### ISSUE THREAD

**Issue by hickmanw** [scipy/scipy#10919]
I'm using the L-BFGS-B optimizer for bounds constrained optimization. To step to a new point, it calls function setulb() inside the f2py module _lbfgsb. The evaluation point should always be within the closed interval defined by the bounds, which is important when the objective function is not defined for points outside of the bounds. I found an exception. To avoid all the code associated with my objective function, I packaged the the argument values for the iteration immediately before the algorithm violated the bounds into a json file [example_input.txt](https://github.com/scipy/scipy/files/3719746/example_input.txt) to demonstrate the issue. Please let me know if additional information would be helpful.

#### Reproducing code example:
In the example below, the bounds (l and u) are 0 and 1 (as floats, of course), respectively.
```python
import json
import numpy as np
from scipy.optimize._lbfgsb import setulb

with open('example_input.txt','r') as file:
    args = json.load(file)

m = np.int32(args['m'])
x = np.array(args['x'])
l = np.array(args['l'])
u = np.array(args['u'])
nbd = np.array(args['nbd'], dtype=np.int32)
f = args['f']
g = np.array(args['g'])
factr = args['factr']
pgtol = args['pgtol']
wa = np.array(args['wa'])
iwa = np.array(args['iwa'], dtype=np.int32)
task = args['task']
iprint = np.int32(args['iprint'])
csave = args['csave']
lsave = np.array(args['lsave'], dtype=np.int32)
isave = np.array(args['isave'], dtype=np.int32)
dsave = np.array(args['dsave'])
maxls = np.int32(args['maxls'])

print('prior to setulb(), "x" array respects the '
      'unit interval bounds:\n {}\n'.format(x))

setulb(m,x,l,u,nbd,f,g,factr,pgtol,
       wa,iwa,task,iprint,
       csave, lsave, 
       isave, dsave, 
       maxls)

print('after calling setulb(), last element of "x" array '
      'is below the lower bound of 0:\n {}'.format(x))
```
```
prior to setulb(), "x" array respects the unit interval bounds:
 [1.         0.         0.98899175 0.         0.02034203]

after calling setulb(), last element of "x" array is below the lower bound of 0:
 [ 1.00000000e+00  0.00000000e+00  9.89054179e-01  0.00000000e+00
 -3.46944695e-18]
```

#### Error message:
No error message was generated. The error occurs later in attempting to evaluate the objective function I provided, which is not defined outside of the unit-hypercube bounds.

#### Scipy/Numpy/Python version information:
```
1.3.1 1.17.0 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

#### Attempts to Find Cause
I tried the above example in pure Fortran (writing the example inputs to Fortran format files, and writing a Fortran program to read the values and then call setulb()), but was unable to reproduce the bound violation. However, this was my first exposure to Fortran, and I suspect I wasn't compiling with the same compiler options or blas and lapack libraries. Could the problem be due to f2py, rather than in the Fortran code?

**Comment by andyfaff** [comment]
My initial suspicion is that the forward difference derivative calculation done by scipy is going slightly outside the bounds. You could check if that's the case by looking at the parameter vector, and seeing how far outside the bounds it is.

**Comment by hickmanw** [comment]
@andyfaff  Thanks for chiming in. 

I didn't mention it initially, but I provide a function to calculate the gradient, so scipy wouldn't be using finite difference approximations of it. However, even if scipy were calculating numerical gradients, that calculation would be handled outside of the `setulb()`, which does not have direct access to the objective function, and `setulb()` should not ever request evaluation at a point outside of the bounds. 

After a bit more work, I can now reproduce the bound violation in Fortran alone using a simplified objective function.

**Cause of Error**
The problem is due to not accounting for floating point rounding error in  [lbfgsb.f](scipy/scipy/tree/master/scipy/optimize/lbfgsb_src/lbfgsb.f). In short, a maximum magnitude for a bound-respecting step is calculated based on the shortest distance (over all parameters) between a (scalar) parameter at its bound (in the direction of the step). In some circumstances, the magnitude of the step taken will be that maximum magnitude, but when that happens, rounding errors in the floating point arithmetic can result in the actual step violating the bound. 

**Code Where Error Occurs**
1. The maximum scalar multiple of proposed step `d` that will respect the bounds is calculated in the following snippet. `l` is an array of lower bounds, `u` contains corresponding upper bounds, `nbd` is a array of integers indicating whether the parameter indexed by `i` has no bounds, a lower bounds, both bounds, or just an upper bound, And in this first following snippet `x` contains the current parameter vector. The maximum safe magnitude is stored in `stpmx`

https://github.com/scipy/scipy/blob/4dcf6068fd49c356900550e02aa1b4e6e5b03cc1/scipy/optimize/lbfgsb_src/lbfgsb.f#L2497-L2522

2. Then a subroutine chooses a particular step magnitude `stp`, which is bounded by `stpmx`
https://github.com/scipy/scipy/blob/4dcf6068fd49c356900550e02aa1b4e6e5b03cc1/scipy/optimize/lbfgsb_src/lbfgsb.f#L2551

3. Finally, a step `d` scaled by `stp` is taken in the following (note that at this place in the code the current parameter vector is stored in array `t`, not `x`, hence the `t` on the RHS)
https://github.com/scipy/scipy/blob/4dcf6068fd49c356900550e02aa1b4e6e5b03cc1/scipy/optimize/lbfgsb_src/lbfgsb.f#L2562-L2564

**Reproducing Code Example: Fortran Only**

I've reproduced the error in Fortran alone on both 
  - an AWS environment running ubuntu, and
  - a windows machine via cygwin. 

In all cases I compile with gfortran. 
I've tried compiling using both
  - the lbfgsb.f file from  [lbfgsb_src](scipy/scipy/tree/master/scipy/optimize/lbfgsb_src), and 
  - the lbfgsb.f file from the [original authors](http://users.iems.northwestern.edu/~nocedal/lbfgsb.html) 

I've tried using the library files 
  - provided by the original authors (blas.f, linpack.f, timer.f), and
  - from [lbfgsb_src](scipy/scipy/tree/master/scipy/optimize/lbfgsb_src) (augmented with `-lblas -llapack`)

I was able to reproduce the bound violation in each permutation that I tried.

Here is the output generated by my reproducing code example (code to follow)
```
Parameter vector printed after each call to setulb()
  0.87500000000002776       0.75000000000001532       0.94999999999997220       0.82142857142859915       0.63636363636360849
   1.0000000000000000        0.0000000000000000        1.0000000000000000        0.0000000000000000        0.0000000000000000   
   1.0000000000000000        0.0000000000000000        1.0000000000000000        0.0000000000000000        0.0000000000000000
   1.0000000000000000        0.0000000000000000       0.98897330431493247        0.0000000000000000        2.6353554421041155E-002
   1.0000000000000000        0.0000000000000000       0.98897330431493247        0.0000000000000000        2.6353554421041155E-002
   1.0000000000000000        0.0000000000000000       0.98899174429155579        0.0000000000000000        2.0341986743231205E-002
   1.0000000000000000        0.0000000000000000       0.98905414161952765        0.0000000000000000       -3.4694469519536142E-018
 ERROR: Lower bound violation
 X at bound violation:
   1.0000000000000000        0.0000000000000000       0.98905414161952765        0.0000000000000000       -3.4694469519536142E-018

The following floating point arithmetic reproduces
the bound violation exactly. In real arithmetic, the
result of the following would be 0, but with floating point
arithmetic, at the last summation the two floats differ by the
last mantissa bit, and instead of 0 we obtain:
(0.0d0 -0.026353554421041155d0) / -0.0060115676778099494d0
* -0.0060115676778099494d0 + 0.026353554421041155d0 = -3.46944695195361419E-18
```
Finally, here's the reproducing code that generated the output above
```fortran
c    Demonstrate failure of setulb() to respect lower bound
c
      program mwe
c     ****************************
c     This program is a minimal working example of the failure of
c     subroutine setulb() (from lbfgsb.f) to respect a lower bound
c     respect the lower bound
c     ****************************
      implicit none
      
      character*60     task, csave, status
      logical          lsave(4)
      integer, parameter :: n = 5, m = 10
      integer          iprint, maxls
      integer          nbd(n), iwa(3*n), i, isave(44)
      
      double precision f, factr, pgtol,
     +                 x(n), l(n), u(n), g(n), dsave(29),
     +                 wa(2*m*n + 5*n + 11*m*m + 8*m)
     
c     With the exception of `status`, all of these variables
c     are needed by subroutine setulb.
c     `status` holds error messages from the objective function
c     subroutine objfun, and error messages about violations
c     of the bounds

      status = 'GOOD'

c     Define the tolerance for convergence
      factr = 1.0d+7
      pgtol = 1.0d-5
      
c     Define max line search steps per iteration
      maxls = 20
      
c     Suppress built-in output; We'll print our own
      iprint = -1
      
c     Define the bounds
      nbd = 2
      l = 0.0d0
      u = 1.0d0
      
c     Define the starting point
      x(1) = 0.8750000000000278d0
      x(2) = 0.7500000000000153d0
      x(3) = 0.9499999999999722d0
      x(4) = 0.8214285714285992d0
      x(5) = 0.6363636363636085d0

c     task must be 'START' to begin
      task = 'START'
      
c     Describe the problem
  100 format(/, 'The following floating point arithmetic reproduces',/,
     +'the bound violation exactly. In real arithmetic, the',/,
     +'result of the following would be 0, but with floating point',/,
     +'arithmetic, at the last summation the two floats differ by the',/,
     +'last mantissa bit, and instead of 0 we obtain: ',/,
     +'(0.0d0 -0.026353554421041155d0) / -0.0060115676778099494d0 ',/,
     +'* -0.0060115676778099494d0 + 0.026353554421041155d0 = ',
     +        ES24.17)
  
c     Explain the output
  200 format(/, 'Parameter vector printed after each call to setulb()')
      write(*,200)
      
c     Fewer than 10 iterations are needed to demonstrate the error
      do 10 i=1,10
      
         call setulb(n,m,x,l,u,nbd,f,g,factr,pgtol,wa,iwa,task,
     +               iprint,csave,lsave,isave,dsave,maxls)
             
         write(*,*) x

         if (x(5) .lt. l(5)) then 
c        check for the bound violation on the 5th parameter
            status = 'ERROR: Lower bound violation'
            write(*,*) status
            write(*,*) 'X at bound violation:'
            write(*,*) x
            
c        reproduce the exact calculation that violated the bound
            f = (0.0d0 -0.026353554421041155d0) 
            f = f / (-0.0060115676778099494d0)
            f = f * (-0.0060115676778099494d0) 
            f = f + 0.026353554421041155d0
            write(*,100) f
            return
         else if (task(1:2) .eq. 'FG') then
c        update f (function value) and g (gradient) 
            call objfun(n, x, f, g, status)
         endif
         
         if (status(1:5) .eq. 'ERROR') then
            write(*,*) status
            return
         endif
         
  10  continue    
         
      end program
c ========= End of the program =================      
      
      subroutine objfun(n, x, f, g, status)
      character*60     status
      integer          n
      double precision f, x(n), g(n)
      
c     ********************
c
c     Subroutine objfun
c       This subroutine returns values of the objective function
c       `f` and the gradient `g` for just the points `x` needed
c       to demonstrate the bound violation
c
c
      double precision x0(n), x1(n), x2(n), x3(n), f0, f1, f2, f3,
     +                 g0(n), g1(n), g2(n), g3(n),
     +                 bx2(n), bx3(n), bf2, bf3, bg2(n), bg3(n)
      
c     store literal values needed for demonstration. This is 
c     vastly simpler than reproducing the objective function
c     that was used when the bound violation was discovered

      x0(1) = 0.8750000000000278d0
      x0(2) = 0.7500000000000153d0
      x0(3) = 0.9499999999999722d0
      x0(4) = 0.8214285714285992d0
      x0(5) = 0.6363636363636085d0
      
      x1 = (/1.0d0, 0.0d0, 1.0d0, 0.0d0, 0.0d0/)
      
      x2 = 0.0d0
      x2(1) = 1.0d0
      x2(3) = 0.9889733043149325d0
      x2(5) = 0.026353554421041155d0
      
      x3 = x2
      x3(3) = 0.9889917442915558d0
      x3(5) = 0.020341986743231205d0
      
      f0 = 5163.647901211178d0
      f1 = 5149.8181642072905d0
      f2 = 5149.379332309634d0
      f3 = 5149.374490771297d0

      g0(1) = -0.5934820547965749d0
      g0(2) = 1.6251549718258351d0
      g0(3) = -71.99168459202559d0
      g0(4) = 5.346636965797545d0
      g0(5) = 37.10732723092604d0
      
      g1(1) = -0.43295349282641515d0
      g1(2) = 1.008607936794592d0
      g1(3) = 18.223666726602975d0
      g1(4) = 31.927010036981997d0
      g1(5) = -19.667512518739386d0
      
      g2(1) = -0.4699874455100256d0
      g2(2) = 0.9466285353668347d0
      g2(3) = -0.016874360242016825d0
      g2(4) = 48.44999161133457d0
      g2(5) = 5.819631620590712d0
      
      g3(1) = -0.46970678696829116d0
      g3(2) = 0.9612719312174818d0
      g3(3) = 0.006129809488833699d0
      g3(4) = 48.43557729419473d0
      g3(5) = 6.005481418498221d0
      
      
c     if x is one of x0, x1, x2, or x3, set the values accordingly
c     otherwise write an error message in status

      if (all(x .eq. x0)) then
         f = f0
         g = g0
      else if (all(x .eq. x1)) then
         f = f1
         g = g1
      else if (all(x .eq. x2)) then
         f = f2
         g = g2
      else if (all(x .eq. x3)) then
         f = f3
         g = g3
      else
         status = 'ERROR: Function not defined at point'
      endif
      
      return
      
      end
      
c ========= The end of subroutine objfun =================       
    
```
Compile with `gfortran mwe.f timer.f linpack.f lbfgsb.f -lblas -llapack -o mwe.exe`

I'll work on a PR for a fix.
