### ISSUE TITLE
Provide a crosspower spectrogram

### ISSUE THREAD

**Issue by lamorton** [scipy/scipy#10914]
The SciPy autopower spectrum `psd` has a crosspower spectrum `csd` counterpart, so it would make sense if the autopower `spectrogram` had a crosspower equivalent.

Our group has a prototype that is just a wrapper around `_spectral_helper.`  This seems cleaner than the alternative of iterating `csd` on a per-time-window basis.

**Comment by smithsp** [comment]
@lamorton should post the prototype here.

**Comment by lamorton** [comment]
@smithsp  Upon refreshing my memory, I think the best approach would be to generalize spectrogram to accept two signals of equal length, rather than create a separate function.  This would parallel the other periodogram functions. The `psd` function I was thinking of is part of pyplot, not SciPy.  

In order not to make breaking changes, the generalized spectrogram call signature could be designed to detect the case where only a single signal was supplied, & simply duplicate that signal as the second input.

**Comment by e-q** [comment]
This is possible via two calls to `stft`. `np.conj(stft_x) * stft_y` will give you the complex "cross_spectrogram," subject to the scaling/units that you're after.
