### ISSUE TITLE
linprog method='interior-point', disp: True fails to display alpha

### ISSUE THREAD

**Issue by garymm** [scipy/scipy#10915]
It seems that the `alpha` argument in `_linprog_ip._display_iter()` (which is executed transitively by `linprog(method='interior-point', options={'disp': True})`) is sometimes a float, and sometimes a 1-dimensional array containing a float.

When it's a 1-dimensional array, formatting it using a floating-point format string fails (see https://github.com/numpy/numpy/issues/12491 and https://github.com/numpy/numpy/issues/5543).

Note the exception is not raised in Python 2 because it seems to be less picky about formatting strings that don't apply to the arguments.

I haven't familiarized myself with the code enough to propose a solution, but it seems like the type of alpha should stay stable on each iteration, and then the `_display_iter()` code can expect either a float or a 1x1 array and format it appropriately.

#### Reproducing code example:

```
import numpy as np
from scipy.optimize import linprog

c = np.array([1., 1., 1., 1.])
A_ub = np.array([[-1.0e+00, -1.0e-02, -1.0e-02, -1.0e+01],
       [-1.0e-02, -1.0e+00, -1.0e-02, -1.1e+01],
       [-1.0e-02, -1.0e-02, -1.0e+00, -1.2e+01],
       [-0.0e+00, -0.0e+00, -0.0e+00, -0.0e+00],
       [ 1.0e+00,  1.0e+00,  1.0e+00, -0.0e+00]])
b_ub = np.array([-20., -20., -20.,  -0.,  27.])
A_eq = np.array([[0., 0., 0., 1.]])
b_eq = np.array([1.])
bounds = np.array([[ 0., np.nan],
       [ 0., np.nan],
       [ 0., np.nan],
       [ 1.,  1.]])
sln = linprog(
        c=c,
        A_ub=A_ub,
        b_ub=b_ub,
        A_eq=A_eq,
        b_eq=b_eq,
        options={
            'maxiter': 1e6,
            'tol': 1e-06,
            'disp': True,
            'sparse': True,
        },
        bounds=bounds,
        method='interior-point')
```

#### Error message:

```
/srv/conda/envs/notebook/lib/python3.7/site-packages/scipy/optimize/_linprog_util.py:653: RuntimeWarning: invalid value encountered in less
  i_f = np.abs(lb - ub) < tol   # indices of "fixed" variables
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-4ff943dd0818> in <module>
     12         },
     13         bounds=bounds,
---> 14         method='interior-point')

/srv/conda/envs/notebook/lib/python3.7/site-packages/scipy/optimize/_linprog.py in linprog(c, A_ub, b_ub, A_eq, b_eq, bounds, method, callback, options, x0)
    527         elif meth == 'interior-point':
    528             x, status, message, iteration = _linprog_ip(
--> 529                 c, c0=c0, A=A, b=b, callback=callback, _T_o=T_o, **solver_options)
    530         elif meth == 'revised simplex':
    531             x, status, message, iteration = _linprog_rs(

/srv/conda/envs/notebook/lib/python3.7/site-packages/scipy/optimize/_linprog_ip.py in _linprog_ip(c, c0, A, b, callback, _T_o, alpha0, beta, maxiter, disp, tol, sparse, lstsq, sym_pos, cholesky, pc, ip, permc_spec, **unknown_options)
   1143                                             lstsq, sym_pos, cholesky,
   1144                                             pc, ip, permc_spec, callback,
-> 1145                                             _T_o)
   1146 
   1147     return x, status, message, iteration

/srv/conda/envs/notebook/lib/python3.7/site-packages/scipy/optimize/_linprog_ip.py in _ip_hsd(A, b, c, c0, alpha0, beta, maxiter, disp, tol, sparse, lstsq, sym_pos, cholesky, pc, ip, permc_spec, callback, _T_o)
    804 
    805         if disp:
--> 806             _display_iter(rho_p, rho_d, rho_g, alpha, rho_mu, obj)
    807         if callback is not None:
    808             x_o, fun, slack, con, _, _ = _postsolve(x/tau, *_T_o,

/srv/conda/envs/notebook/lib/python3.7/site-packages/scipy/optimize/_linprog_ip.py in _display_iter(rho_p, rho_d, rho_g, alpha, rho_mu, obj, header)
    564         float(alpha) if isinstance(alpha, numbers.Number) else alpha,
    565         float(rho_mu),
--> 566         float(obj)))
    567 
    568 

TypeError: unsupported format string passed to numpy.ndarray.__format__
```

#### Scipy/Numpy/Python version information:

    1.3.1 1.17.0 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
Thanks for reporting this, but I believe this was fixed by gh-10498. I just tested it on the current master branch and there is no error because:
`float(alpha) if isinstance(alpha, numbers.Number) else alpha`
has been changed to 
`alpha if isinstance(alpha, str) else float(alpha)`, 
so even when `alpha` is a single-element array, it is converted to a `float` before being formatted,

I also added to a list of maintenance items for `linprog` to figure out what is really going on. The fact that we had this bug suggests that some of my underlying code was sloppy.

**Comment by garymm** [comment]
I also expect that change would fix the issue.
Any chance that fix could be back-ported to the 1.2 LTS branch?

**Comment by mdhaber** [comment]
I've added the backport-candidate label to gh-10498.

**Comment by mdhaber** [comment]
I'm curious - can you tell me where the example problem comes from / how you use `linprog`? Thanks!

**Comment by garymm** [comment]
Unfortunately I'm not at liberty to discuss the problem due to a non-disclosure agreement with my employer.
The larger context is that I am currently converting a lot of code from python 2 to python 3, and I hit this bug when doing that conversion.

Many thanks for your work on SciPy.

**Comment by mdhaber** [comment]
No problem. Thanks!
