### ISSUE TITLE
scipy.sparse.linalg.eigsh gets killed without error log

### ISSUE THREAD

**Issue by seralouk** [scipy/scipy#10913]
I am using `scipy.sparse.linalg.eigsh` to approximate the 1000 smallest algebraic eigenvalues and eigenvectors of a huge real symmetric matrix.

`scipy.sparse.linalg.eigsh(A  , k=1000 , which='SA')`

The process gets killed without any error log displayed.  I only see:

> Killed

Memory seems to be enough since the code is running for hours before it gets killed.

Any idea why this happens?

FYI: I am using a LinearOperator and I pass it in the `scipy.sparse.linalg.eigsh()` function but this should not make any difference.

**Comment by pv** [comment]
Quite difficult to say based on this information. OS/platform/scipy version/which scipy binaries are being used? How big is your matrix? Can you try to check how many iterations it took before it crashed (e.g. counting the number of matvecs in the operator code).

**Comment by seralouk** [comment]
My matrix is around 160000 by 160000. I have 500GB available so I guess this is fine.

Concerning the number of iterations (counting the number of matvecs in the operator code), I am not sure how I can have access to this information.

**Comment by lobpcg** [comment]
If you indeed have 500GB RAM you probably do not run out of memory, indeed. The eigsh code does increase the amount of RAM during the run. You may still want to do a quick memory profiling on smaller matrices and smaller k and check how the memory use increases with the matrix size and/or k.

tol=1e-10 is likely way too small for this setup. I would recommend trying something like tol=1e-6 unless you have a very special reason to push to 1e-10

If the matrix is symmetric, you can also try https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.lobpcg.html - It may be more stable in some cases and has some other advantages over eigsh.

**Comment by seralouk** [comment]
Right now I observe an increase of around 150GB in memory when the current code runs. It goes from ~150 to ~300. The code seems to be running fine for now. 

Concerning the tolerance, the default value of 0 implies machine precision. I use `tol=1e-10` to relax it more but I could also try `tol=1e-6`.

Finally, my matrix is symmetric and real. What is the difference of `eigsh` and `lobpcg` ? Why the second is more stable in some cases?

**Comment by lobpcg** [comment]
https://en.wikipedia.org/wiki/LOBPCG

**Comment by lobpcg** [comment]
If you already went from ~150 to ~300, you may be running out of memory eventually...

Try lobpcg - at least the memory usage is fixed during the run after the first iteration is passed. You should implement and use matmat in your LinearOperator - that makes lobpcg several times faster compared just to matvec use. I support it, so feel free to share if you run into issues.

**Comment by lobpcg** [comment]
Do not forget please to close this issue, if you simply run out of memory

**Comment by seralouk** [comment]
> Do not forget please to close this issue, if you simply run out of memory

I am going to close it but I am 100% sure that it is not a memory problem. The memory during the code execution ranges from 120 to 250GB. At each iteration it reaches 250 and then drops to 120 before the new one starts.

**Comment by lobpcg** [comment]
Since eigsh just calls ARPACK which is precompiled, if there is an issue like this one, related or not to memory, there is no practical easy fix anyway, unfortunately. 

Lobpcg is written fully in Python, so issues can be easily tracked and most of the time fixed, with a reasonable effort.

**Comment by seralouk** [comment]
> Since eigsh just calls ARPACK which is precompiled, if there is an issue like this one, related or not to memory, there is no practical easy fix anyway, unfortunately.
> 
> Lobpcg is written fully in Python, so issues can be easily tracked and most of the time fixed, with a reasonable effort.

I thought to try the `lobpcg` but it seems that it can only be used for large symmetric positive definite matrices. In my case, I do have a symmetric matrix but it might not be positive definite. So if i am not missing something, `lobpcg` cannot be used in my case.

**Comment by seralouk** [comment]
> Since eigsh just calls ARPACK which is precompiled, if there is an issue like this one, related or not to memory, there is no practical easy fix anyway, unfortunately.
> 
> Lobpcg is written fully in Python, so issues can be easily tracked and most of the time fixed, with a reasonable effort. lobpcg finds smallest or largest eigenvalues and eigenvectors of large symmetric matrices, does not matter if positive definite.

I am going to try `Lobpcg` since it supports verbosity. Should I expect a slower performance when using `Lobpcg` compared to `eigsh` ?
