### ISSUE TITLE
no simmetry in eigenvectors from tridiagonal matrix

### ISSUE THREAD

**Issue by jalfonsi** [scipy/scipy#10922]
When computing eigenpairs from tridiagonal matrices, the outcoming  eigenvectors from opposite eigenvalues show no symmetry unlike in Wolfram Mathematica. This does not occur if the non-zero bands have all the same elements.  

#### Reproducing code example:
import numpy as np
from scipy.linalg import eig, eigh, eigh_tridiagonal, eigvalsh_tridiagonal, eigvalsh
d = np.zeros(6) # diagonal filled with zeros
e = np.array([1.   , 2., 1.   , 1.   , 2.]) # off-diagonal hopping matrix elements
#e = np.ones(5)
A = np.diag(d) + np.diag(e, k=1) + np.diag(e, k=-1)

#w, v = eigh_tridiagonal(d, e)
w, v = eigh(A)

w # eigenvalues
array([-2.53646696, -2.10377251, -0.3748021 ,  0.3748021 ,  2.10377251,
        2.53646696])
v[0] # first eigenvector
array([ 0.20436012, -0.1973713 ,  0.64751951,  0.64751951, -0.1973713 ,
        0.20436012])
v[5] # symmetric of first eigenvector
array([-0.30536004, -0.55980393, -0.30557292,  0.30557292,  0.55980393,
        0.30536004])
#### Scipy/Numpy/Python version information:
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.3.1 1.16.2 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)

**Comment by ilayn** [comment]
Hi @jalfonsi Thank you for taking the time to report it. In numpy arrays you have to use a different indexing to look at the columns

If you instead type for the first and the last columns 

```python
>>> v[:, [0, -1]]  # v[:, [0, 5]] is also fine, -1 means the last one
array([[ 0.20436012,  0.20436012],
       [-0.5183527 ,  0.5183527 ],
       [ 0.55521219,  0.55521219],
       [-0.37157197,  0.37157197],
       [ 0.38726783,  0.38726783],
       [-0.30536004,  0.30536004]])
```

you will get the corresponding eigenvectors.
