### ISSUE TITLE
`solve_triangular` does not overwrite b when b has multiple columns

### ISSUE THREAD

**Issue by hongzhouye** [scipy/scipy#10923]
My issue is about `scipy.linalg.solve_triangular`. Specifically, when setting `overwrite_b=True`, it does overwrite `b` when `b` is a single column vector, but fails to do so when `b` has multiple columns.

#### Reproducing code example:

```python3
import scipy.linalg as slg
import numpy as np


def check_solve_triag(n, m):
    """ Solve L @ x = b, where L is n*n, and b is n*m.
    """
    # construct a random positive definite matrix, a
    u = slg.orth(np.random.rand(n,n))
    diag = np.random.rand(n)
    a = (u * diag) @ u.T
    # cholesky to get a lower triangular matrix
    low = slg.cholesky(a, lower=True)
    # get a random rhs matrix, b
    b = np.random.rand(n,m)
    # solve with overwrite_b = True
    bb = b.copy()
    slg.solve_triangular(low, bb, lower=True, overwrite_b=True)
    # check success
    solve_success = np.allclose(np.linalg.norm(low @ bb - b), 0.)
    overwrite_b = np.allclose(bb, b)
    print("solve success?", solve_success)
    print("overwrite_b?", overwrite_b)


if __name__ == "__main__":
    np.random.seed(17)

    check_solve_triag(5,1)
    # output:
    #   solve success? True
    #   overwrite_b? False
    check_solve_triag(5,2)
    # output:
    #   solve success? False
    #   overwrite_b? True
```

#### Error message:

The program runs with no error, but `b` is not overwritten when `m > 1`.

#### Scipy/Numpy/Python version information:
```
1.3.1 1.17.2 sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment]
According to the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve_triangular.html), the option is to "Allow overwriting data in b (may enhance performance". It does not guarantee that `b` will the overwritten, so I don't think this is a bug.

Does that resolve the issue?

**Comment by hongzhouye** [comment]
Thanks for your quick response!

where in the [document](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve_triangular.html) says *it does not guarantee that `b` will be overwritten*?

I think I can rephrase my question. Since `scipy.linalg.solve_triangular` is a wrapper for LAPACK's`trtrs`, I was wondering if a direct call of `trtrs` can guarantee that `b` is overwritten or not.

**Comment by hongzhouye** [comment]
Oh I see your point... @mdhaber 

**may** enhance performance <==> **may** overwrite `b`, right?

**Comment by ilayn** [comment]
The data type needs to be `float` and the array should be fortran ordered. Otherwise a temporary array is created in between while communicating with the low-level solver.

**Comment by mdhaber** [comment]
@hongzhouye that and I think "allow" means that you are giving permission, which may or may not be exercised.

**Comment by hongzhouye** [comment]
@mdhaber I see. Thanks!

@ilayn Thank you so much for the link! The problem with my sample code above is the C-ordering. So changing the line `bb = b.copy()` to
```python
bb = np.asarray(b.copy(), order="F")
```
solves the problem.

Thank you both again! This can be closed.
