### ISSUE TITLE
Add scaled inverse chi2 distribution

### ISSUE THREAD

**Issue by FlorianWilhelm** [scipy/scipy#10933]
**Is your feature request related to a problem? Please describe.**
Right now there is the [chi2](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.chi2.html) but the [scaled inverse chi2](https://en.wikipedia.org/wiki/Scaled_inverse_chi-squared_distribution) distribution seems to be missing. The scaled inverse chi2 has particular use in Bayesian statistics.

**Describe the solution you'd like**
Since the scaled inverse chi2 distribution equals the [inverse gamma](https://en.wikipedia.org/wiki/Inverse-gamma_distribution) distribution with another parametrization, one could easily add this for convenience. An alternative would be to implement it using the chi2 distribution directly.

**Describe alternatives you've considered**
Of course one can just implement the parametrization manually for a given use-case.

**Additional context (e.g. screenshots)**

**Comment by josef-pkt** [comment]
AFAICS it doesn't have a scale parameter and so doesn't fit into the generic distribution setup.
(It should have one shape and one scale parameter like invgamma to allow for the generic shape-loc-scale parameterization)

Aside from that, I think we still avoid adding distributions that are just a reparameterization

**Comment by FlorianWilhelm** [comment]
Okay, got it. To be honest, I look most distributions up depending on my use-cases on Wikipedia. Especially in some Bayesian use-cases, I often rely on this [page on conjugate priors](https://en.wikipedia.org/wiki/Conjugate_prior). For me, it feels that mapping these distributions on SciPy functionality (and having to do some reparametrizations) is more difficult than it needs to be.

**Comment by ev-br** [comment]
There is (was?) a small external project, `paramnormal` so something in that vein, which repametrized several scipy distributions. Maybe this can be contributed, or if the project is no longer active, you can revive and maintain it?

**Comment by mdhaber** [comment]
@FlorianWilhelm Would a compromise be add the alternative parameterization information to the documentation of inverse gamma?

**Comment by FlorianWilhelm** [comment]
@mdhaber: Fine for me. Still, I am convinced that from a users' perspective providing some common reparametrization might be really helpful. First of all, some parametrizations can be quite tricky, and finding them in the literature takes some time. From an implementation perspective, one could achieve this using static factory methods for each alternative parameterization.

**Comment by mdhaber** [comment]
Thanks @FlorianWilhelm. Adding reparameterizations is a larger issue than this, as it has come up many times. With enough issues like this one, perhaps it will be reconsidered. In the meantime, I think a doc enhancement would be uncontroversial and could partially address this issue now.

**Comment by mdhaber** [comment]
@FlorianWilhelm do you think that gh-13434 addresses the doc enhancement?

**Comment by FlorianWilhelm** [comment]
Thanks, @mdhaber. This additional documentation helps and would work from my point of you. This issue can be closed when #13434 is merged.
