### ISSUE TITLE
CI: Azure PR build retention times

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#10941]
I don't think this is easy to fix at the moment, but I've certainly noticed that the complete build logs for Azure PR runs disappear after ~10 days, which can be pretty short for volunteer reviewers, especially if you want to check the coverage on a more complex PR you've bookmarked for later.

Here's a screencap of some of the settings, which is also confusing!

![image](https://user-images.githubusercontent.com/7903078/67067361-4c76f000-f133-11e9-96d2-da5aff925e81.png)

It looks like even if we could change the 10 to 20 or so it would have no effect anyway.

See also: 

https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops

There are apparently ways to retain a given build by hand, but the confusion / request for more control seems to be an open issue: https://github.com/MicrosoftDocs/vsts-docs/issues/3822

**Comment by andyfaff** [comment]
Closing because there is probably going to be a move away from Azure.
