### ISSUE TITLE
Platform-dependent behavior in scipy.optimize.minimize

### ISSUE THREAD

**Issue by tuckerburgin** [scipy/scipy#10945]
I am getting very different values in the inverse Hessian calculated during identical optimizations depending on the platform on which I run my code. The short script that produces the output can be found [here](https://github.com/team-mayes/atesa_v2/blob/master/atesa_v2/lmax_temp.py).

This script uses scipy.optimize.minimize to optimize parameters that fit a hard-coded dataset to a model with the BFGS method, and then computes a desired parameter from the model based on the optimization's hess_inv attribute (the mean value of the diagonal terms, to be precise).

I have tested this script on the following platforms and with the following results, followed where available with the output from "import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)":

- OSX 10.13.3, Python 3.7.3: 0.209 (1.3.1 1.17.0 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0))
- OSX 10.13.3, Python 3.6.7 (Travis CI): 0.209
- OSX 10.13.3, Python 3.7.3 (Travis CI): 0.209
- Ubuntu version 16.04, Python 3.6.7 (Travis CI): 0.038
- Ubuntu version 16.04, Python 3.7.3 (Travis CI): 0.038
- Ubuntu version 18.04, Python 3.6.7 (Travis CI): 0.038
- Ubuntu version 18.04, Python 3.7.3 (Travis CI): 0.038
- CentOS 6.10 Python 3.6.9: 0.058 (1.3.1 1.16.5 sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0))
- Ubuntu 17.04, Python 2.7.13 (VirtualBox VM): 0.209 (1.2.2 1.16.5 sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0))
- Ubuntu 17.04, Python 3.5.3 (VirtualBox VM): 0.209 (1.3.1 1.17.3 sys.version_info(major=3, minor=5, micro=3, releaselevel='final', serial=0))

Any suggestions? Perhaps I'm reading too much into what could be considered fairly small differences?

Thank you!

**Comment by andyfaff** [comment]
I can no longer retrieve the script to investigate this further.
OP is welcome to reopen the issue if those details are available again.
