### ISSUE TITLE
typo 

### ISSUE THREAD

**Issue by alborji** [scipy/scipy#10953]
Dear
Please change '10' to '20' at line: 2843 

Design a digital high-pass filter at 15 Hz to remove the 10 Hz tone,

must change to :

Design a digital high-pass filter at 15 Hz to remove the 20 Hz tone,

**Comment by TheGreatCabbage** [comment]
Do you mean line 2852 in filter_design.py? [Here is a link to that line on GitHub.](https://github.com/scipy/scipy/blob/master/scipy/signal/filter_design.py#L2852)

**Comment by ilayn** [comment]
Hi @alborji. **High** pass filters attenuate the frequencies **lower than** the designated critical frequency `Wn`. Hence it is not a typo.

**Comment by alborji** [comment]
yeah, you correct.
