### ISSUE TITLE
Interval definition for brent optimization method

### ISSUE THREAD

**Issue by DirkDuschinger** [scipy/scipy#10969]
Hi,

I'm working on a project to calculate uncertainties on divisions of two numbers in python for two cases:
1. the numerator is a subset of the denominator, for example for efficiency calculations
2. numerator and denominator are means of poison distributions

There is already an implementation in c++ in the root library, which is commonly used in high energy physics. The code can be found here:
https://github.com/root-project/root/blob/v6-19-01/hist/hist/src/TGraphAsymmErrors.cxx#L499

I've adapted the code in python using the function optimize.brent, which runs this code:
https://github.com/scipy/scipy/blob/4bfc152f6ee1ca48c73c06e27f7ef021d729f496/scipy/optimize/optimize.py#L1922

My python implementation gets the same result as the original c++ code in the majority of the tests I've performed. However, in some cases I've got a ValueError, which I've tracked down is raised here: 
https://github.com/scipy/scipy/blob/4bfc152f6ee1ca48c73c06e27f7ef021d729f496/scipy/optimize/optimize.py#L1907

I've found that the exceptions where due to either `xb==xa` or  `xb==xc`. I've also checked the c++ code and found that such cases are accepted.

So I have locally changed the if statement to:
```
if not ((xa <= xb) and (xb <= xc)):
    raise ValueError("Not a bracketing interval.")
```

With this change I've got no exception in all my tests and also the same results as the c++ code. 

I'm aware that this case means that xb, the middle point, is the same as the bracket border, which contradicts the actual definition `xa<xb<xc` of the scipy bracket:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.bracket.html#scipy.optimize.bracket

However, I think the brent method does not strongly require this strict definition. Is there any chance to change the code to avoid such exceptions for my project?

**Comment by DirkDuschinger** [comment]
Hi @pvanmulbregt, 

it's been a while now, since I've created the issue. Do you know if someone has an opinion on this?

**Comment by pvanmulbregt** [comment]
Hi Dirk,
I'm not familiar with this function but looking at the code it appears that an Exception will be raised a few lines down if xb == xa?
https://github.com/scipy/scipy/blob/4bfc152f6ee1ca48c73c06e27f7ef021d729f496/scipy/optimize/optimize.py#L1912-L1913

**Comment by rlucas7** [comment]
> On Jan 13, 2020, at 6:14 PM, DirkDuschinger <notifications@github.com> wrote:
> 
> ﻿
> Hi @pvanmulbregt,
> 
> it's been a while now, since I've created the issue. Do you know if someone has an opinion on this?
> 
I’m not super familiar with the code in optimize sub package but the scenario described seems to has lowerbracket == upperbracket and IIUC the Brent algorithm is for root finding. The bracket denotes a lower and upper bound within which the root is expected to lie. If your bracket is a single point then you already know the root, it is that point. 

So why would you do root finding in that case?

**Comment by DirkDuschinger** [comment]
> Hi Dirk,
> I'm not familiar with this function but looking at the code it appears that an Exception will be raised a few lines down if xb == xa?
> 
> https://github.com/scipy/scipy/blob/4bfc152f6ee1ca48c73c06e27f7ef021d729f496/scipy/optimize/optimize.py#L1912-L1913

Hi @pvanmulbregt,

Sorry about the confusion. Of course, the suggested change mentioned in my first comment must be extended by the additional change in line https://github.com/scipy/scipy/blob/4bfc152f6ee1ca48c73c06e27f7ef021d729f496/scipy/optimize/optimize.py#L1912-L1913 to:
```
            if not ((fb <= fa) and (fb <= fc)):
                raise ValueError("Not a bracketing interval.")
```

**Comment by DirkDuschinger** [comment]
> On Jan 13, 2020, at 6:14 PM, DirkDuschinger ***@***.***> wrote: ﻿ Hi @pvanmulbregt, it's been a while now, since I've created the issue. Do you know if someone has an opinion on this?
> I’m not super familiar with the code in optimize sub package but the scenario described seems to has lowerbracket == upperbracket and IIUC the Brent algorithm is for root finding. The bracket denotes a lower and upper bound within which the root is expected to lie. If your bracket is a single point then you already know the root, it is that point. So why would you do root finding in that case?

Hi @rlucas7, the brent algorithm as implemented in scipy offers 3 methods, depending on the bracket. I.e. here is the implementation if no bracket has been passed:
https://github.com/scipy/scipy/blob/4bfc152f6ee1ca48c73c06e27f7ef021d729f496/scipy/optimize/optimize.py#L1898-L1899 
Here for a search with a minimum and a maximum:
https://github.com/scipy/scipy/blob/4bfc152f6ee1ca48c73c06e27f7ef021d729f496/scipy/optimize/optimize.py#L1900-L1902
and this block describes the case I'm referring to:
https://github.com/scipy/scipy/blob/4bfc152f6ee1ca48c73c06e27f7ef021d729f496/scipy/optimize/optimize.py#L1903-L1914
Now I have cases, where xb, the middle point, equals the minimum or the maximum. So for example `xa=2`, `xb=2`, `xc=3`. In such cases I got the described exceptions. But from my perspective the code delivers reasonable results when allowing such cases.

**Comment by rlucas7** [comment]
> Now I have cases, where xb, the middle point, equals the minimum or the maximum. So for 
> example xa=2, xb=2, xc=3. In such cases I got the described exceptions. But from my 
> perspective the code delivers reasonable results when allowing such cases.

Maybe I'm not understanding the issue correctly but if you have `xa, xb, xc` and `xb` is equal to one of the other 2 values, can't you check this on your end and pass in only a length 2 argument instead of a length 3?

**Comment by pvanmulbregt** [comment]
It appears that `get_bracket_info` is only called once, at the start. Adding the line
`brack = sorted(brack)`
before checking the length and extracting the values may be sufficient to meet your use case and still be safe/correct.
Would that be your understanding also?

**Comment by DirkDuschinger** [comment]
> > Now I have cases, where xb, the middle point, equals the minimum or the maximum. So for
> > example xa=2, xb=2, xc=3. In such cases I got the described exceptions. But from my
> > perspective the code delivers reasonable results when allowing such cases.
> 
> Maybe I'm not understanding the issue correctly but if you have `xa, xb, xc` and `xb` is equal to one of the other 2 values, can't you check this on your end and pass in only a length 2 argument instead of a length 3?

Good idea. Unfortunately it did not work.

**Comment by DirkDuschinger** [comment]
> It appears that `get_bracket_info` is only called once, at the start. Adding the line
> `brack = sorted(set(brack))`
> before checking the length and extracting the values may be sufficient to meet your use case and still be safe/correct.
> Would that be your understanding also?

Yes. The `len == 3` case basically only sorts the bracket values. It also calculates the return values of the function for those bracket values, but they are anyways ignored in the rest of the optimize function (it appears to me, that some code from the Brent class is a copy+paste from the _minimize_scalar_golden function).

**Comment by DirkDuschinger** [comment]
Hi all,

I had a read through the 1973 paper from Brent where he describes the functionality implemented in this method. First to mention, when the method for finding the local minimum of a function is only described for a bracket with a minimum and a maximum, so the `len==2` case. There is a chapter on global minima, which describes a third parameter as an "initial guess". I think this is what is implemented in scipy's brent optimization method for finding the local minimum as well. 

However, the description from the paper for global minima binds the "initial guess" between the minimum and maximum, excluding the boundaries explicitly. In python language this would be 
```
if xb <= xa or xb >= xc:
    xb = 0.5 * (xa + xc)
```
That said, I think the implementation in scipy follows the paper under the assumption, that the local minimum search also works with an "initial guess".

My guess is that the implementation in the root library does not strictly follow the paper, but seems to deliver reasonable results either way. However, this may not be part of this issue.

**Comment by DirkDuschinger** [comment]
I consider this issue as solved, i.e. there is no need to change anything in scipy. Thanks a lot for the discussion.
