### ISSUE TITLE
Update Avogadro's constant

### ISSUE THREAD

**Issue by artgoldberg** [scipy/scipy#10962]
**Is your feature request related to a problem? Please describe.**
In May the International Bureau of Weights and Measures defined the Avogadro number as the exact integer N = 6.02214076×10^23.

**Describe the solution you'd like**
Give the Avogadro number the correct value.

**Describe alternatives you've considered**
NA

**Additional context (e.g. screenshots)**
NA

**Comment by mdhaber** [comment]
@artgoldberg Will this be addressed if gh-9590 is resolved? I see there was some work towards that in gh-10197, and on quick read I can't quite tell why it was closed.

**Comment by dopplershift** [comment]
gh-10920 is open and trying to update the CODATA.

**Comment by artgoldberg** [comment]
Sounds good. Thanks guys!
FYI, my 'NA' in the original issue was a bad, obscure pun!

**Comment by jakobjakobson13** [comment]
Should be fixed by #10920.

**Comment by rgommers** [comment]
thanks @jakobjakobson13
