### ISSUE TITLE
Allow for fftd images to be passed to scipy.signal.fftconvolve

### ISSUE THREAD

**Issue by wevonosky** [scipy/scipy#10973]
**Is your feature request related to a problem? Please describe.**
In some circumstances, a user may be applying multiple filters to the same image. In the case when the image is large it would be advantageous for the user to perform a single FFT outside of the fftconvolve function and pass the spectrum to the function as an input. For large arrays this could significantly speed up the use of fftconvolve by skipping the internal FFT. 

**Describe the solution you'd like**
A solution might just look like an extra parameter flag that the user supplies that tells fftconvolve whether the input data are in Fourier space or not. If the user specifies the data are already in Fourier space, then FFT's are skipped. This would require downstream changes to the functions fftconvolve references as well.

For an example of where this has been implemented for similar reasons see:

https://scikit-image.org/docs/dev/api/skimage.feature.html#skimage.feature.register_translation

**Describe alternatives you've considered**
I have considered breaking out the scipy function myself, but this isn't an ideal solution.

**Comment by mckib2** [comment]
Two things I notice about this proposed enhancement:

1. The FFTs must have correct lengths to do the convolution.  It's simple to do, but letting scipy do it internally you know you'll always do the right thing.  If the caller supplies the FFT, you would have to make an agreement with the caller that they did indeed use the correctly padded FFT.  I can't think of way to check the input to verify this.  If the user does it wrong, this is a silent bug!  Probably not desired behavior. Thoughts?
2. Same kind of story for fftn vs rfftn.  If the user uses rfftn-like function, then how does fftconvolve know which inverse transform to use?  The shapes of the output could be nonsense.  Again, the only way I see around this is to have the user tell you what they did.

So the proposed function signature might look something like this:
`fftconvolve(in1, in2, mode="full", axes=None, do_fft=True, s=None, is_real=False)`
where `do_fft=False` is the proposed flag, `s` is the shape parameter (see numpy.fft.rfftn), and `is_real` tells us whether to use ifftn or rifftn.

In my opinion, that's a lot to assume the caller has done right and not enough safety if they've done something wrong.  Are there ways of validating the input that I'm not thinking of?

**Comment by wevonosky** [comment]
1) I agree with your points here. I don't think saving a little time would be worth causing the function to silently fail because the user provided incorrectly padded or shaped Fourier spectrum. 

2) Again I agree, I admittedly didn't think too long about how the internals of this function would have to change and what assumptions would need to be made in order to make it work. I have been working with Fourier spectrum a lot lately and really appreciated that skimage's register_translation allowed me to skip the FFT. However, doing so in this case clearly isn't ideal.

I don't think there are ways of evaluating the input for padding once it is in Fourier space besides some sort of comparison between the Fourier spectrum shape and the original shape of the image. However that is even more ambiguous because it can't verify how the pad was applied. 

Thanks for the feedback.
