### ISSUE TITLE
scipy doesn't recognize Cython, even though it's installed and works fine with other installations

### ISSUE THREAD

**Issue by PegasusMKD** [scipy/scipy#10982]
My issue is about SciPy not recognizing Cython even though it is installed.

#### Reproducing code example:

```
FROM iexechub/python-scone

RUN echo "http://dl-cdn.alpinelinux.org/alpine/v3.5/community" >> /etc/apk/repositories \
    && apk --no-cache --update-cache add python3 python3-dev py3-pip \
    && apk update \
    && apk add --no-cache --update-cache libgcc \
    && apk --no-cache --update-cache add gfortran build-base wget freetype-dev libpng-dev \
    && apk add --no-cache --virtual .build-deps gcc musl-dev

RUN apk --no-cache --update-cache add git

##########ADD PYTHON PACKAGES HERE:#######################
RUN SCONE_MODE=sim pip install --upgrade Cython

#RUN SCONE_MODE=sim pip install --upgrade git+git://github.com/cython/cython@master

#RUN SCONE_MODE=sim pip install --upgrade pip setuptools wheel

#RUN SCONE_MODE=sim pip3 install python-language-server

RUN SCONE_MODE=sim pip install attrdict python-gnupg web3

RUN SCONE_MODE=sim pip install numpy

RUN SCONE_MODE=sim pip install pandas

RUN SCONE_MODE=sim pip install geopy

#RUN apk --no-cache --update-cache add py3-cython

#RUN apk --no-cache --update-cache add scipy

#RUN SCONE_MODE=sim pip install Cython==0.29.12

#RUN SCONE_MODE=sim pip install --upgrade pip

#RUN apk add cython

RUN SCONE_MODE=sim pip3 install --user scipy

RUN SCONE_MODE=sim pip3 install sklearn

RUN SCONE_MODE=sim pip3 install keras
```

#### Error message:

```
Collecting scipy
  Downloading https://files.pythonhosted.org/packages/ee/5b/5afcd1c46f97b3c2ac3489dbc95d6ca28eacf8e3634e51f495da68d97f0f/scipy-1.3.1.tar.gz (23.6MB)
  Could not find a version that satisfies the requirement Cython>=0.29.2 (from versions: )
No matching distribution found for Cython>=0.29.2
You are using pip version 10.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

#### Scipy/Numpy/Python version information: Python 3.6.6

It installs NumPy and pandas without a problem. It recognizes Cython and everything. As soon as SciPy is supposed to get installed, it doesn't recognize it.

This is for iExec deployment, it uses Alpine Linux for the docker image.

Tried upgrading the pip, but that just breaks everything, it doesn't want to install any package whatsoever. So i need to use pip 10.0.1.

**Comment by jakevdp** [comment]
You installed cython with pip3, and scipy with pip, which suggests they were installed for separate python versions. Try installing both with the same pip command.

**Comment by PegasusMKD** [comment]
Changed it, same error. I changed it to pip3 because i searched around the net and there were people reporting this fixed the Cython issue with some other libraries. But I didn't find anything for SciPy.

But with just pip, same error.

**Comment by PegasusMKD** [comment]
By the way, I'm running this on an Ubuntu 18.04 LTS VM, with
...
sudo docker build --no-cache -t iexechub/transport_x:1.0.0 .
...

**Comment by ilayn** [comment]
Why are you pulling things from alpine linux? Is this a VM with Alpine or Ubuntu? In Alpine, we have some issues.

**Comment by PegasusMKD** [comment]
I'm using Ubuntu as a VM to use docker and other unix libraries, which are not really supported on Windows. 

The docker image is based on python-scone and Alpine Linux, apk is from Alpine Linux, base image is python-scone from iexechub.

**Comment by ilayn** [comment]
See #9481 and #9338 for example

**Comment by PegasusMKD** [comment]
Thanks, i'll try both threads solutions.

**Comment by rgommers** [comment]
> No matching distribution found for Cython>=0.29.2

The reason it can't find Cython `>=0.29.2` is because SciPy has a `pyproject.toml` file so `pip` tries to do an isolated build. Installing Cython beforehand doesn't make a difference.

> You are using pip version 10.0.1, however version 19.3.1 is available.

you should be upgrading indeed, `pip` 10 has incomplete support for `pyproject.toml`.

**Comment by PegasusMKD** [comment]
@rgommers  I know i should, but that just breaks the entire Dockerfile for some reason, i don't know if it's because of the Alpine or the Scone, but it keeps on spamming that i should use vfork/spawn which ( as i read )  is something that pip doesn't support anymore, and it breaks on any package installation with python setup.py egg_info not found. That is why i have to use pip 10, because the entire system which scone or alpine is based on is broken.

**Comment by rgommers** [comment]
Hmm well, that combo of Alpine, Docker, Scone, old `pip` and new packages with build isolation sounds like a recipe for disaster. 

How about just downloading the SciPy sdist in your Dockerfile and explicitly installing it with `python setup.py install`? That avoids the build isolation?

I'm closing the issue since this is not a SciPy bug. Feel free to continue the discussion of course.

**Comment by larsoner** [comment]
You can also use pip with `--no-use-pep517` to disable build isolation

**Comment by PegasusMKD** [comment]
Changed to an Ubuntu base image, works like a charm!
