### ISSUE TITLE
Memory leak in shgo triangulation

### ISSUE THREAD

**Issue by kmichel-sereema** [scipy/scipy#10987]
The Complex class in shgo triangulation uses an lru_cache with `max_size=None` :

https://github.com/scipy/scipy/blob/master/scipy/optimize/_shgo_lib/triangulation.py#L460
https://github.com/scipy/scipy/blob/master/scipy/optimize/_shgo_lib/triangulation.py#L482
https://github.com/scipy/scipy/blob/master/scipy/optimize/_shgo_lib/triangulation.py#L488

This infinite cache is a problem when using shgo in a long-running process.

I could detect it quickly because the minimized function was a bound method of an
object which itself was holding a reference to a large array :

```
class SomethingBig:
    def __init__(self):
        self.something = numpy.arange(500*1024*1024)

    def get_value(self, x):
        # The real calculation uses the large array
        return scipy.optimize.rosen(x)


def work():
    something_big = SomethingBig()
    # A large-enough iters is required to start using the cache
    scipy.optimize.shgo(something_big.get_value, ((-1, 1), (-1, 1)), iters=5)


for i in range(100):
    work()
    print(i)
```

The bug was confirmed when using the following workaround between calls to
`scipy.optimize.shgo` completely stopped the memory leak :

```
# 1: Confirm the evergrowing cache:
print(scipy.optimize._shgo_lib.triangulation.Complex.generate_sub_cell_t1.cache_info())
print(scipy.optimize._shgo_lib.triangulation.Complex.generate_sub_cell_t2.cache_info())
# 2: Clear it
scipy.optimize._shgo_lib.triangulation.Complex.generate_sub_cell_t1.cache_clear()
scipy.optimize._shgo_lib.triangulation.Complex.generate_sub_cell_t2.cache_clear()
```

A fixed-size cache would not really solve the problem, at least in my case :

The number of calls to `Complex.generate_sub_cell_t1` and `Complex.generate_sub_cell_t1`
during a single call to `scipy.optimize.shgo` is small (around 100) but the array held
by the cache is large and I can't afford to have more one of those arrays kept in memory.
In this situation I don't think there is a cache size which would be both useful and harmless.

If the cache is necessary, maybe it would be better to wrap the methods after the `__init__`
to make sure the cache is removed with the instance of Complex(), and never shared
between calls of shgo :

```
class Complex:
    def __init__(self, dim, func, func_args=(), symmetry=False, bounds=None,
                 g_cons=None, g_args=()):
        [...]
        self.generate_sub_cell_t1 = lru_cache(maxsize=None)(self.generate_sub_cell_t1)
        self.generate_sub_cell_t2 = lru_cache(maxsize=None)(self.generate_sub_cell_t2)
```

Instead of :
```
class Complex:
    @lru_cache(maxsize=None)
    def generate_sub_cell_t1(self, origin, v_x):
        [...]
    @lru_cache(maxsize=None)
    def generate_sub_cell_t2(self, origin, v_x):
        [...]
```

I can provide a patch if you think this is an acceptable solution.

#### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.3.1 1.17.2 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
Thanks for the report @kmichel-sereema.

@Stefan-Endres could you have a look at this?

**Comment by Stefan-Endres** [comment]
Hi @kmichel-sereema, thank you for the detailed report.

I agree with what you're saying, in addition the performance benefit for avoiding the vector computations is not that big so I don't think that this cache is necessary at all (these caches are of course different from the cache for the objective function itself, the latter being necessary for most applications). 

In fact I've been trying to get rid of both the cache and the need for the `generate_sub_cell_#` methods in the new sampling method (which produces the same distribution/complex, but different, faster algorithms to compute it).

A quick patch for the scipy version would be appreciated as I still have some ways to go in terms of validating the new sampling method with the old simplicial complex.
