### ISSUE TITLE
dual_annealing header clarification

### ISSUE THREAD

**Issue by meluso** [scipy/scipy#10994]
Suggest updating the comment sections of optimize.dual_annealing to include the following change for less-experienced users:

Starting Line 443:
        bounds : sequence, shape (n, 2)
            Bounds for variables.  ``(min, max)`` pairs for each element in ``x``,
            defining bounds for the objective function parameter. The input
            bounds must be a zipped list of the form "bounds = list(zip(min,max))"
            where min and max are both (n,1)-dimensional lists of their
            values for each dimension of each variable.

It took me a while to figure out what type the inputs for the bounds needed to be, even with the example. Thanks for your consideration!

**Comment by tupui** [comment]
Hi, I believe the current doc is enough? https://scipy.github.io/devdocs/reference/generated/scipy.optimize.dual_annealing.html?highlight=dual_annealing#scipy.optimize.dual_annealing

Or is there something still unclear?

**Comment by meluso** [comment]
Re-reading it today, it's clear to me now! (acknowledged, I have a lot more experience, but still seems sufficient). Thanks for your time!

**Comment by tupui** [comment]
Thank you for coming back and closing 👍
