### ISSUE TITLE
Suggestion: load single array from .mat file

### ISSUE THREAD

**Issue by TheGreatCabbage** [scipy/scipy#10995]
**Is your feature request related to a problem? Please describe.**

When loading a `.mat` file with `scipy.io.loadmat()`, a dictionary is returned. Unfortunately, the relatively common use-case of loading a single array from a `.mat` file requires code such as the following:

```python
data: dict = loadmat("test.mat")
arr: ndarray = [i for i in data.values() if isinstance(i, ndarray)][0]
```

This is error-prone and tedious, so I suggest adding a parameter to return a single array from a `.mat` file. 

If this seems sensible, I'll work on implementing it and make a pull request. I'd appreciate feedback/suggestions.

**Describe the solution you'd like**

Add a parameter, `single_array=False`, to `scipy.io.loadmat()`:
`scipy.io.loadmat(file_name, mdict=None, appendmat=True, single_array=False, **kwargs)`

When `single_array` is `True`:

- If there is only one `ndarray` in the dictionary, it returns the array.
- If there are no arrays in the dictionary, it returns `None`.
- If there are multiple arrays in the dictionary, it returns `None`.

**Describe alternatives you've considered**

Define a new method such as `loadmat_single_array(file_name, appendmat=True, **kwargs)`, which follows the same principles as the solution above.

**Comment by rlucas7** [comment]
@TheGreatCabbage I've labeled this issue w/'query' and and 'scipy.io' labels. I don't have much expertise in the `scipy.io` sub-package so I cannot really give you any guidance here. You might send the same enquiry to the scipy-dev mailing list. You might get more eyeballs on the query and some of the members with expertise or familiarity in this sub-package might be able to give you some guidance.

**Comment by skjerns** [comment]
a `.mat` file always contain the variable names and the corresponding ( amapping from key to item), therefore it does not make sense to return a single array.

Eg.

If in matlab you create an array and save it
```matlab
array1 = [1,2,3,4]
save('array.mat','array1' )
```
It will reconstruct the variable name exactly as given in the script, even when loaded with matlab.

```Python
array1 = scipy.io.loadmat('array.mat')['array1']
```

I get that your solution makes sense in some cases, however, this is just how the `.mat` structure is defined, so I'd argue that it also makes sense to implement it like that.

If you know already that there is only one array (which in your solution would be the case) you can just load the array with. This should be easy enough.

```Python
array1 = list(scipy.io.loadmat('array.mat').values())[3]
```

**Comment by TheGreatCabbage** [comment]
Thanks, I see and agree with your points.
