### ISSUE TITLE
Problem importing optimize module

### ISSUE THREAD

**Issue by nunomr** [scipy/scipy#10998]
I'm using Windows 10 and Python 3.7. 

I installed scipy through `pip install scipy` and it installed without a problem. However I can't seem to open the optimize module. Just `import scipy` works fine, but `import scipy.optimize` is met with the following problem:

`>>> import scipy`
`>>> import scipy.optimize`
`Traceback (most recent call last):`
`  File "<pyshell#1>", line 1, in <module>`
`    import scipy.optimize`
`  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\optimize\__init__.py", line 390, in <module>`
`    from .optimize import *`
`  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\optimize\optimize.py", line 37, in <module>`
`    from .linesearch import (line_search_wolfe1, line_search_wolfe2,`
`  File "C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\optimize\linesearch.py", line 18, in <module>`
`    from scipy.optimize import minpack2`
`ImportError: DLL load failed: Impossible to locate specified module.`

It appears that some files are missing. Any help solving this? Is there a workaround to be able to work with the module?

**Comment by PalAditya** [comment]
Interesting. This issue seems to be not related to scipy though, since I am running a similar setup (Windows 10, Python 3.7) and the import works just fine

You can possibly try the methods [here](https://stackoverflow.com/questions/22753695/dll-load-failed-with-scipy-optimize), especially the part about 32/64 bit Python.

**Comment by andyfaff** [comment]
@Nunomr is this still an issue, did you solve it?

**Comment by nunomr** [comment]
> @nunomr is this still an issue, did you solve it?

No I didn't. I ended up installing Anaconda and working with that.

**Comment by wonderlandpark** [comment]
Any Solution? I have this issue

**Comment by ev-br** [comment]
> Any Solution? I have this issue

Yes. Clean reinstall

**Comment by wonderlandpark** [comment]
> > Any Solution? I have this issue
> 
> Yes. Clean reinstall

Should I reinstall scipy or CUDA
