### ISSUE TITLE
Precondition does not provide any efficiency in cg

### ISSUE THREAD

**Issue by Laphet** [scipy/scipy#11007]
My issue is about precondition in the sparse solvers (cg, gmers). I tried an incomplete LU factorization as preconditioner. However, this does not provide any decrease in consuming time even greatly lags the program more than 10 times!

I am confused by this situation, my original problem is a Poisson equation defined on a square domain, and I discrete this problem with Q1 finite element method. The mesh size reaches 512*512.
#### Reproducing code example:

```
def _get_preconditioner(op: csr_matrix):
    M = spilu(op.tocsc())
    def Mx(x): return M.solve(x)
    return LinearOperator(op.shape, Mx)
```

#### Scipy/Numpy/Python version information: 
1.3.1 1.17.2 sys.version_info(major=3, minor=7, micro=5, releaselevel='final', serial=0)

**Comment by lambe** [comment]
Two things to check:
- Does the number of CG iterations go down with preconditioning? (In other words, check that the preconditioner is correct.)
- Are you recomputing the factorization with each iteration? You will have to trace the code to see if that is the case.

**Comment by ilayn** [comment]
We did not hear back for this elsewhere and seems like we don't have much to do with the issue hence closing.
