### ISSUE TITLE
ENH: Implement the Polya-Gamma distribution

### ISSUE THREAD

**Issue by zoj613** [scipy/scipy#11009]
Polya-gamma random variables are commonly used as auxiliary variables during data augmentation in Bayesian sampling algorithms, which have wide-spread usage in Statistics.

An implementation of the distribution such that one can sample random values from it would be a nice addition to scipy.stats

The paper: [Sampling Polya-Gamma random variates:  alternate andapproximate techniques](https://arxiv.org/pdf/1405.0506.pdf) seems to provide an alogrithm that allows one to sample from the distribution. The algorithm described in this paper uses partial sums, The inverse-Gaussian, Uniform and Exponential distributions, which I believe are already available in Scipy.

There currently is an [R implementation](http://www.rdocumentation.org/packages/BayesLogit/versions/2.1/topics/rpg) and another [python third party package](http://github.com/slinderman/pypolyagamma) but all seem to have non-compatible licences with Scipy.

I have learnt that there is a procedure that can be followed in order to implement such a distribution for scipy and it is available at: [Adding A New Statistics Distribution](http://scipy.github.io/devdocs/dev/contributor/adding_new.html#id1)

Refs:
https://arxiv.org/pdf/1405.0506.pdf
http://www.tandfonline.com/doi/pdf/10.1080/01621459.2013.829001
http://users.stat.ufl.edu/~jhobert/papers/polya-gamma_revision.pdf

**Comment by rlucas7** [comment]
>An implementation of the distribution such that one can sample random values from it would be a nice addition to scipy.stats

To implement a new distribution in stats requires more than solely sampler, there also need to be methods for calculation of the pdf, cdf, tail cdf (survival function), moments, etc. 

The linked arxiv paper refers to a paper which details multiple methods to sample from the distribution. In that paper there is an infinite series for the distribution. There would need to be some sort of truncation of the infinite sum to implement within a given tolerance. Given that the primary use case for this distribution would be to implement a Gibbs sampler for statsmodels, I'm wondering if the sampler should be directly implemented in statsmodels (if the package has support for that type of fitting) perhaps @josef-pkt would be the person to comment? 

I'm not aware of any other applications which use the Polya-Gamma distribution besides the Gibbs sampler for logistic regression.

**Comment by rlucas7** [comment]
There is this package which ports the sampler component already if you need to implement:

https://github.com/slinderman/pypolyagamma

Sincerely, 

-Lucas Roberts

**Comment by zoj613** [comment]
> There is this package which ports the sampler component already if you need to implement: https://github.com/slinderman/pypolyagamma Sincerely,
> 

I already linked that package in the initial post.

**Comment by zoj613** [comment]
> > An implementation of the distribution such that one can sample random values from it would be a nice addition to scipy.stats
> 
> To implement a new distribution in stats requires more than solely sampler, there also need to be methods for calculation of the pdf, cdf, tail cdf (survival function), moments, etc.
> 
> The linked arxiv paper refers to a paper which details multiple methods to sample from the distribution. In that paper there is an infinite series for the distribution. There would need to be some sort of truncation of the infinite sum to implement within a given tolerance. Given that the primary use case for this distribution would be to implement a Gibbs sampler for statsmodels, I'm wondering if the sampler should be directly implemented in statsmodels (if the package has support for that type of fitting) perhaps @josef-pkt would be the person to comment?
> 
> I'm not aware of any other applications which use the Polya-Gamma distribution besides the Gibbs sampler for logistic regression.
It still would be a big convenience to have it implemented in one of the big libraries like scipy or numpy so people dont have to search for different libraries that have possibly different APIs. If you read the paper you will notice that the partial sums dont ever get summed to infinity. There is a stopping run that ensures all sums taken are finite. And this is with one of the 4 methods proposed.

**Comment by rlucas7** [comment]
>It still would be a big convenience to have it implemented in one of the big libraries like scipy or >numpy so people dont have to search for different libraries that have possibly different APIs. If >you read the paper you will notice that the partial sums dont ever get summed to infinity. There is >a stopping rule that ensures all sums taken are finite. And i think this is with one of the 4 methods >proposed.

@zoj613 To be clear, I'm not opposed to implementing in SciPy, I'm pointing out what one would need to include to implement based on the distribution class structure in scipy. For continuous distributions there is also a `fit()` method to estimate the parameters that would need to be implemented. Given the representation that might be somewhat complicated and slow to implement, not sure if that would be a concern.

**Comment by zoj613** [comment]
> > It still would be a big convenience to have it implemented in one of the big libraries like scipy or >numpy so people dont have to search for different libraries that have possibly different APIs. If >you read the paper you will notice that the partial sums dont ever get summed to infinity. There is >a stopping rule that ensures all sums taken are finite. And i think this is with one of the 4 methods >proposed.
> 
> @zoj613 To be clear, I'm not opposed to implementing in SciPy, I'm pointing out what one would need to include to implement based on the distribution class structure in scipy. For continuous distributions there is also a `fit()` method to estimate the parameters that would need to be implemented. Given the representation that might be somewhat complicated and slow to implement, not sure if that would be a concern.

I understand your concern. I am still learning the `scipy.stats` API for distributions so maybe once I feel confident enough that I can do it maybe i'll submit a pull request....unless someone more capable does it before my attempt.

**Comment by rlucas7** [comment]
@zoj613 if you are looking to contribute to SciPy you can post a PR with work in progress WIP if you like. If you feel that a new distribution is a large undertaking, you can search the open issues on github repo for those with label `good first issue` of which there are several. If you want a less complicated distribution than the Polya-Gamma, there are several that have open issues (I'd check the linked issues for open PRs before you start working on any though): 

https://github.com/scipy/scipy/issues/7437
https://github.com/scipy/scipy/issues/7102 (I think Leo Singer has an open PR on this one though)
https://github.com/scipy/scipy/issues/6414
https://github.com/scipy/scipy/issues/6528
https://github.com/scipy/scipy/issues/6000
https://github.com/scipy/scipy/issues/10364

**Comment by rkern** [comment]
FWIW, as I mentioned in the comments of numpy/numpy#18076, I would support adding a function that implements Polya-Gamma sampling without implementing a whole `Distribution` for it.

**Comment by josef-pkt** [comment]
I just saw this issue.

statsmodels does not have any random sampling based Bayesian methods.
IIRC, someone from the nipy neighborhood looked at it around 10 years ago. When I looked at it then, it seemed to complicated and fragile to me.

a bit related
I was looking recently at generalized Tukey Lambda distributions, which are useful for flexible random number generation, but these distributions are not useful in a standard (MLE) model because there is no easy way to compute loglikelihood and similar.
https://github.com/statsmodels/statsmodels/issues/624#issuecomment-713253667

**Comment by zoj613** [comment]
> I just saw this issue.
> 
> statsmodels does not have any random sampling based Bayesian methods.
> IIRC, someone from the nipy neighborhood looked at it around 10 years ago. When I looked at it then, it seemed to complicated and fragile to me.
> 
> a bit related
> I was looking recently at generalized Tukey Lambda distributions, which are useful for flexible random number generation, but these distributions are not useful in a standard (MLE) model because there is no easy way to compute loglikelihood and similar.
> [statsmodels/statsmodels#624 (comment)](https://github.com/statsmodels/statsmodels/issues/624#issuecomment-713253667)

For the PolyaGamma, the pdf, cdf and their logarithms can be computed (at least numerically estimated) as shown in page 5 and 6 of https://arxiv.org/pdf/1205.0310.pdf. Since this issue did not spark much interest since I last created it, I went and wrote a reference implementation using a numpy/scipy API at https://github.com/zoj613/polyagamma . If there is any future interest to add the distribution to scipy, then that could be used as a reference. I'm closing this now.
