### ISSUE TITLE
Dual Annealing Algorithm evolution 

### ISSUE THREAD

**Issue by echo5india** [scipy/scipy#11002]
It is already possible to add a call back in the dual_annealing function to see how the optimization goes. But it is only possible to get minimum and function value at the minimum.

Would it be possible to add more parameters to the callback function, at least the iteration number in order to plot the evolution with respect to optimization time.

It would be really useful to get these informations to be able to plot the path taken  by the algorithm.

**Comment by rgommers** [comment]
Seems like a reasonable request, however the signature of `callable` isn't easily extensible without breaking backwards compatibility. Unfortunately this is also true for other optimizers - not sure we discussed that before somewhere.

In this case, you could keep track of the iteration number yourself, because there'll be exactly one call to `callback` each iteration so `callback` could increment some counter.

@sgubianpm any other thoughts?

**Comment by echo5india** [comment]
Thank you for the prompt answer.

Yes I thought about that but If I want to know if the new energy was accepted or not it would be easier since parameter calibration for this kind of algorithm is quite important.

Also something more important: I think the default parameter 'accept' should be above 1.0 and not negative. Otherwise the algorithm never choses states with a higher energy.

**Comment by rgommers** [comment]
> Also something more important: I think the default parameter 'accept' should be above 1.0 and not negative. Otherwise the algorithm never choses states with a higher energy.

This is unrelated to the `callback` request, and I'm not sure about what the right response is. Could you open a separate issue for this, with an example that shows the problem?

**Comment by sgubianpm** [comment]
> Seems like a reasonable request, however the signature of `callable` isn't easily extensible without breaking backwards compatibility. Unfortunately this is also true for other optimizers - not sure we discussed that before somewhere.
> 
> In this case, you could keep track of the iteration number yourself, because there'll be exactly one call to `callback` each iteration so `callback` could increment some counter.
> 
> @sgubianpm any other thoughts?

@echo5india, @rgommers 
The ``callback`` is not working the same way for each global optimisers (but is consistant for local minimisers). If I am not mistaken,  for ``minimize`` function, as @rgommers mentioned, it is called at the end of each iteration (as well as for global optim``shgo``). For other global optimisers, ``basin_hopping`` and ``dual_annealing``, ``callback`` will be called for a new minimum found (with 3d argument that as a different meaning), ``differential_evolution`` has a different signature.
So, maybe there would a need for aligning all signatures with more flexibility on the arguments (adding optional args or kargs?)

**Comment by andyfaff** [comment]
There's certainly scope for an improved callback system which, amongst other things, could return an intermediate result. THis intermediate result would contain iteration number, current best solution/energy, etc. However, it's difficult to do without breaking back compatibility, or increasing complexity. At the moment the best way to achieve what you want to do (and arguably cleaner as well) it to create something along these lines:

```
class Callback(object):
    def __init__(self, fun):
        self.x_history = []
        self.fun = fun

    def __call__(self, x):
        self.x_history.append(x)
        # unfortunately this calls the user function again
        self.fun_history = self.fun(x)
```
