### ISSUE TITLE
Barnard's Test for More Powerful Hypothesis Testing of 2x2 Contingency Tables

### ISSUE THREAD

**Issue by ntenenz** [scipy/scipy#11014]
While the rule of thumb for what constitutes "too small" may vary by source, it is largely understood that the chi-squared test and G-test are [often inappropriate](http://www.biostathandbook.com/small.html) when 2x2 contingency tables contain "small counts." Currently, `scipy.stats` contains `fisher_exact`, which can be used in these scenarios. However, this method can often be quite conservative as it is conditions the nuisance parameter such that combined response matches that observed in the data [1](https://www.researchgate.net/profile/Cyrus_Mehta/publication/242179503_Conditional_versus_Unconditional_Exact_Tests_for_Comparing_Two_Binomials/links/540721a30cf2bba34c1e8e22/Conditional-versus-Unconditional-Exact-Tests-for-Comparing-Two-Binomials.pdf), [2](https://www.tandfonline.com/doi/abs/10.1080/00031305.1993.10475946). 

[Barnard's Test](https://en.wikipedia.org/wiki/Barnard%27s_test) provides an alternative, which does **not** condition the nuisance parameter and is often more powerful for 2x2 contingency tables. I propose the addition of a `barnard_exact` function to the list of `scipy.stats` contingency table functions to address this gap.

**Comment by josef-pkt** [comment]
I tried to implement it for statsmodels.
The problem is that the naive implementation is computationally not very efficient and takes time for samples that are not tiny. I got stuck in implementing a more efficient algorithm.
(several years ago)

A good implementation would be good to have, it would fit in scipy.stats with the other related tests, (but statsmodels would be an alternative).

**Comment by ntenenz** [comment]
Thoughts on a PR which provides a naive/inefficient implementation? Given the primary value-add is in cases of small N, the poor scaling may not impact many potential applications.

**Comment by josef-pkt** [comment]
I'm not sure. I don't think I did much timing when I looked at this.
The main problem might be cases with unequal numbers, e.g. 100 in one cell and 4 in another cell

CORRECTION:
I don't find anything on Barnard on my computer, so I didn't look into the details for it.

What I tried to work on in 2015 or earlier is Blaker exact confidence intervals which is also a unconditional method similar to Barnard. (seems Blaker is for one sample)

**Comment by ntenenz** [comment]
I have a naive implementation (at home) that I could potentially clean up to contribute if there's interest. Working from memory, I believe the algorithm scales as `O(N_T1 * N_T2 * N_nuisance)` where `N_Tx` are the number of samples in a given treatment and `N_nuissance` is the number of discrete values of the nuisance parameter considered.

**Comment by josef-pkt** [comment]
Not Barnard but related
I was looking at exact tests for difference in binomial proportion, especially I like Berger/Boos
https://github.com/statsmodels/statsmodels/pull/2608/files#diff-26a83a395f464c482b7651425f0fa4f3R16

(My code. statsmodels PRs and issues are a mess, because I was jumping around between many different cases and methods instead of implementing one function.)

**Comment by MrTomRod** [comment]
I would like to request [Boschloo's test](https://en.wikipedia.org/wiki/Boschloo%27s_test), a variant of Barnard's. Should I create a new issue or should I just mention it here?

**Comment by V0lantis** [comment]
I am on it with @Carreau

**Comment by V0lantis** [comment]
@MrTomRod Do you have somewhere a paper describing how to implement Boschloo's test ? I have found [this](https://repository.lib.ncsu.edu/bitstream/handle/1840.4/237/psuper5.pdf?sequence=1&isAllowed=y) but I don't know if it will be enough

**Comment by MrTomRod** [comment]
@V0lantis I have no idea how to implement such algorithms efficiently. Maybe the following links help you:

[This](https://sci-hub.do/https://onlinelibrary.wiley.com/doi/epdf/10.1111/j.1467-9574.1970.tb00104.x) is the original paper. The [exact2x2 R docs](https://cran.r-project.org/web/packages/exact2x2/vignettes/unconditionalExact2x2Tests.pdf) make some sense to me. Here is the [exact2x2 source code](https://rdrr.io/cran/exact2x2/src/R/boschloo.R).

**Comment by V0lantis** [comment]
Thank you @MrTomRod. I'll look at it tomorrow then :-)

**Comment by mdhaber** [comment]
Please do not look at the R source code. It is not license compatible, and we don't want the possibility of infringing on the license.

**Comment by V0lantis** [comment]
> Please do not look at the R source code. It is not license compatible, and we don't want the possibility of infringing on the license.

Yes, don't worry I will not take a look to R's code. I am sorry, I didn't mention it in my previous message, but I have already been warned by @jb-leger :-)

**Comment by jdwinkler-lanzatech** [comment]
Just wanted to add that this test would be nice to have in scipy!

**Comment by V0lantis** [comment]
It is under development. The PR is nearly done. poke @mdhaber if you have time to review it

**Comment by MrTomRod** [comment]
Am I understanding this correctly, [the pull request](https://github.com/scipy/scipy/pull/13441) is done now and `barnard_exact` will be shipped with the next version of scipy?

Import will be as follows:
```python
from scipy.stats.contingency import barnard_exact
```

Looking forward to `boschloo_exact`!

**Comment by V0lantis** [comment]
> Am I understanding this correctly, [the pull request](https://github.com/scipy/scipy/pull/13441) is done now and `barnard_exact` will be shipped with the next version of scipy?


I believe so, yes 😀 

> Import will be as follows:
> 
> ```python
> 
> from scipy.stats.contingency import barnard_exact
> 
> ```

Not so sure actually, the matter is being discussed in the scipy-dev [mailing list](https://mail.python.org/pipermail/scipy-dev/2021-March/024611.html). 
@mdhaber, @jb-leger, do you have an opinion upon this ?
 
> Thanks for your work, looking forward to `boschloo_exact`!

No problem ! I have been thrilled to work on it 😁

**Comment by mdhaber** [comment]
Yes, that's what I expect.

**Comment by jdwinkler-lanzatech** [comment]
Great! Thanks to you all.
