### ISSUE TITLE
[Segfault] sp.interpolate.griddata crashes on specific input

### ISSUE THREAD

**Issue by shapovalov** [scipy/scipy#11019]
`sp.interpolate.griddata` gives segmentation fault on my input. This is quite a nasty bug since there is nothing obviously wrong with the input, so no way to catch this before calling the function or as an exception; the function crashes the whole process.

#### Reproducing code example:

Load [the file](https://drive.google.com/open?id=1MLxSZxKhGi_F9FTnFu74FSn7fDNXlxxK) with the input parameters and run the function:
```
import pickle
import scipy as sp
import scipy.interpolate

with open(FILE, 'rb') as f:
    inp = pickle.load(f)

## ATTENTION! Will crash your process / notebook kernel.
kps = sp.interpolate.griddata(**inp)
```

#### Error message:
Core dumped.

#### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.0.1 1.17.3 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
# also crashes on
1.3.1 1.17.2 sys.version_info(major=3, minor=7, micro=5, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
Seems to be qhull bug, fixed in 1.4.0
