### ISSUE TITLE
Unexpected Result in factorial function with NaN input

### ISSUE THREAD

**Issue by jacksonvanover** [scipy/scipy#11022]
When the argument to the factorial function is NaN, the result is
zero. Dropping the NaN seems strange. Perhaps it should be propagated instead?

#### Reproducing code example:

```
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy import special
>>> import numpy as np
>>> special.factorial(np.nan)
array(0.)
```

#### Scipy/Numpy/Python version information:
1.2.0 1.15.4 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)

**Comment by rlucas7** [comment]
@jacksonvanover Can you update your SciPy version to 1.3.1 and see if you still see this behavior? 

I reran your example on my dev branch and I see the `nan` propagate:
```
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy import special
>>> import numpy as np
>>> special.factorial(np.nan)
nan
>>> import scipy
>>> scipy.__version__
'1.4.0.dev0+f07eed9'
```

**Comment by WarrenWeckesser** [comment]
@rlucas7, that behavior appears to be a consequence of https://github.com/scipy/scipy/pull/10954, which changed how scalars are handled.  If you pass an array-like to `factorial`, `nan`s in the input result in 0 in the output:

```
In [7]: import scipy                                                                                                                  

In [8]: scipy.__version__                                                                                                             
Out[8]: '1.4.0.dev0+b40d93e'

In [9]: from scipy.special import factorial                                                                                           

In [10]: factorial([np.nan])                                                                                                          
Out[10]: array([0.])
```

**Comment by rlucas7** [comment]
@WarrenWeckesser thanks for pointing this out. Looks like I'm ahead of that commit (`558ec14`) too so the issue was transmogrified from scalar to array-likes :). Should the behavior here be to propogate? I'm less familiar with the behavior of `scipy.special` handling of `nan`. I'm not sure if there is a `nan_policy` concept similar to `scipy.stats`, if default behavior would be propagate, throw error, etc.

**Comment by person142** [comment]
No NaN policies-inputs in the array that enter as NaN should remain NaN.

**Comment by WarrenWeckesser** [comment]
I agree with @person142, just propagate the `nan`s.

**Comment by rlucas7** [comment]
Thanks for clarifying guys. I'm finishing up a patch to close:
https://github.com/scipy/scipy/issues/7058
after that is up I can take a look at a fix for this one. 

Unless @jacksonvanover is interested in opening a PR to fix?

**Comment by jacksonvanover** [comment]
Hi all! Thanks for the confirmation/discussion. If I find the time in the coming week, I will take a look.

**Comment by rlucas7** [comment]
I took a look at this one tonight, it looks pretty straightforward how to handle the scalar case. 
I'm less clear how to handle the numpy array case, a `np.nan` is float type and these arrays are going to be some flavor of `int` type. Typecasting back to `float` will break the behavior of existing tests.
