### ISSUE TITLE
Does not install under python 3.8.0

### ISSUE THREAD

**Issue by ZirconfleX** [scipy/scipy#11024]
Hi,

Tried to migrate ( using pip-migrate) scipy (1.3.1) from python version 3.7.4 to version 3.8.0.
The migrate operation error-ed out when it wanted to migrate scipy.

Removed scipy from the 3.7.4 installation and then ran the migrate operation again.
Everything worked fine, no errors nor warnings.

I then tried to install scipy (1.3.1) per pip into 3.8.0 and that error-ed out the same way as with the migrate operation.
I tried to install scipy on another PC running python 3.8.0 using pip and got the same effect. After a while the install errors out.

Using Linux - Ubuntu 18.04 and Mint 19 (also ubuntu 18.04).
Below the file with error messages:

[scipy_1.3.1_InstallFor_3.8.0_errors_07Nov19.txt](https://github.com/scipy/scipy/files/3819041/scipy_1.3.1_InstallFor_3.8.0_errors_07Nov19.txt)

**Comment by e-q** [comment]
Wheels for 3.8 will be released as part of scipy 1.3.2. See the discussion in #10927
