### ISSUE TITLE
Sparse data with mannwhitneyu

### ISSUE THREAD

**Issue by CooperData** [scipy/scipy#11035]
**Is your feature request related to a problem? Please describe.**
I have very sparse data for what I am testing. The current implementation does not take sparse data as it calls len of the sparse array.

**Describe the solution you'd like**
I dont know yet how to solve this, but I am guessing we could make a change to change the methods called when a sparse array is passed to the method.

**Describe alternatives you've considered**
Currently, I have a way to auto convert to dense the array, but this end up taking a lot of memory.

**Additional context (e.g. screenshots)**
I have not made any contribution on this project, but if I have enough guidelines, I'd love to send a PR with a potential solution.

**Comment by perimosocordiae** [comment]
In general, `scipy.stats` functions aren't designed with sparse matrix support in mind. For the specific case of `mannwhitneyu`, the problem arises here:

https://github.com/scipy/scipy/blob/a6bd0456cdf83c5804fea94144b3b7afac78c3d0/scipy/stats/mstats_basic.py#L1144

It's also worth noting that numpy masked arrays don't play well with scipy.sparse matrices.

I would start by trying to write a version of `mannwhitneyu` that explicitly takes sparse matrix inputs, and make sure that you can get something workable first. It may be the case that the algorithm can't take advantage of sparsity, in which case it's not worth the effort, but I'm not a stats expert so I won't speculate.

**Comment by rgommers** [comment]
@CooperData please have a look at open issues and PRs for `mannwhitneyu` before you try this. The current implementation is pretty badly broken and needs a complete rewrite I'm afraid. There's one PR that was pretty far along but stalled, gh-4933. 

If you'd be interested in tackling this, that would be awesome.

**Comment by CooperData** [comment]
Thanks @perimosocordiae and @rgommers - I will take a look at the current thread. My concern would be that it might not be a really good issue for a first time contributor given the history on that method. But I will give it a try. I am particularly interested as I am actually using that in prod code where I work.

**Comment by rgommers** [comment]
It might be a decent first issue actually - it's not small, but it's pure Python and there's already a lot of test cases (both in the PR, and in issues other people opened).

Thanks for trying, let us know if you need help!

**Comment by mdhaber** [comment]
@CooperData I've been working on gh-4933. Just to be sure I understand, do you want `mannwhitneyu` to work on sparse arrays and produce the same output as if the sparse arrays had first been converted to dense arrays and then passed into `mannwhitneyu`? Or did you want `mannwhitneyu` to ignore the implicit zeros?

**Comment by CooperData** [comment]
Thanks Matt, I believe zeros should be considered as part of the data and
not be removed.

*Cesar H.*

**Comment by mdhaber** [comment]
@CooperData OK. It seems to me that MWU could pretty easily take advantage of the sparsity, since the statistic is just based on the sum of the ranks. You would start by figuring out the ranks of the elements counting all the zeros as just one zero, then figure out how to adjust all the ranks. If the number of zeros is `n0` and the rank associated with a single zero is `r0`, then the adjustment is something like:

- all of the ranks greater than `r0` get increased by `n-1`
- the adjusted rank assigned to zero is `r0 + (n-1)/2`

Then you sum the adjusted ranks of the nonzero elements and `n` times the adjusted rank assigned to zero. The rest of the calculation doesn't care that you started with a sparse matrix.

When gh-4933 is merged, I'd be happy to help you create a PR with this change if other stats people think it's OK to do so.

**Comment by mdhaber** [comment]
@CooperData are you still interested in this? gh-4933 merged.

**Comment by mdhaber** [comment]
@CooperData I'm going to go ahead and close this one until we see some more demand for it. `mannwhitenyu` and other stats functions are being wrapped in a decorator to make their interfaces more consistent (e.g. `nan_policy`, vectorization, support for masked arrays, `axis` tuples, `keepdims`). We could begin to support sparse arrays in stats functions, but we should think about how this fits into the big picture and not just the one function.
