### ISSUE TITLE
deadlock on osx for python 3.8

### ISSUE THREAD

**Issue by beckermr** [scipy/scipy#11033]
We are still seeing something weird with a python 3.8 build on osx over on conda-forge

```
==== testing package: scipy-1.3.1-py38h82752d6_2 =====
running run_test.py
============================= test session starts ==============================
platform darwin -- Python 3.8.0, pytest-5.2.2, py-1.8.0, pluggy-0.12.0 -- $PREFIX/bin/python
cachedir: .pytest_cache
rootdir: $SRC_DIR
collecting ... collected 17186 items / 1225 deselected / 15961 selected

_lib/tests/test__gcutils.py::test_set_gc_state PASSED                    [  0%]
_lib/tests/test__gcutils.py::test_gc_state PASSED                        [  0%]
_lib/tests/test__gcutils.py::test_assert_deallocated PASSED              [  0%]
_lib/tests/test__gcutils.py::test_assert_deallocated_nodel PASSED        [  0%]
_lib/tests/test__gcutils.py::test_assert_deallocated_circular PASSED     [  0%]
_lib/tests/test__gcutils.py::test_assert_deallocated_circular2 PASSED    [  0%]
_lib/tests/test__testutils.py::test__parse_size PASSED                   [  0%]
_lib/tests/test__testutils.py::test__mem_available PASSED                [  0%]
_lib/tests/test__threadsafety.py::test_parallel_threads PASSED           [  0%]
_lib/tests/test__threadsafety.py::test_reentering PASSED                 [  0%]
_lib/tests/test__util.py::test__aligned_zeros PASSED                     [  0%]
_lib/tests/test__util.py::test_check_random_state PASSED                 [  0%]
_lib/tests/test__util.py::TestMapWrapper::test_serial PASSED             [  0%]
```

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=91407&view=logs

This is with a patch from the 1.3.x branch here 

https://github.com/conda-forge/scipy-feedstock/blob/02371e5393763b42fef7f50552829e57f2eb79f3/recipe/scipy1.3.2.patch

@rgommers  for viz

relates to https://github.com/conda-forge/scipy-feedstock/pull/114

**Comment by ilayn** [comment]
Could you please add which OpenBLAS lib you are linking to?

**Comment by beckermr** [comment]
For sure but it will be a while since I need to run to a kids birthday party. This is a conda forge build so we are linking to whatever openblas version is in the global pinnings.

**Comment by rgommers** [comment]
Thanks for the bug report @beckermr. 

This was also noticed and debugged at https://github.com/scipy/scipy/issues/10927#issuecomment-542365484. Short summary: it was caused by a Python bug (https://bugs.python.org/issue38501) without a response so far. 

Explicit `gc.collect()` was added in two places to work around this hang in https://github.com/scipy/scipy/pull/10930. Backported to `1.3.x` in commit 88024e7ca, so this should be fixed now.

**Comment by rgommers** [comment]
> We are seeing this also on Py3.7 runs now too. Hence there is more to it I guess.

Are we? Do you have a link?

**Comment by ilayn** [comment]
Our local runs for #11001 together with @mdhaber and the linked issue

**Comment by beckermr** [comment]
Ahhh so to be clear, I ran this build with a patch derived from the maintenance branch for 1.3.x. So I am pretty sure the commit you mentioned was already applied.

**Comment by rgommers** [comment]
Got it, so we do still have a real problem. Release is already tagged, and wheels are being built. I think it's best to continue with the release, and try to debug this problem asap and push out a 1.3.3 fix if needed. People are blocked upgrading to py38 by no SciPy release, so this seems better than delaying since we don't have a root cause or fix yet. @tylerjereddy FYI

**Comment by rgommers** [comment]
> So I am pretty sure the commit you mentioned was already applied.

yes, checked the diff and the patch was already applied

**Comment by ilayn** [comment]
OK here is the verbose version of the problem

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ilhan Polat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Ilhan Polat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Ilhan Polat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Ilhan Polat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Ilhan Polat\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Ilhan Polat\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Ilhan Polat\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ilhan Polat\Documents\pydump\testmapwrapper.py", line 28, in <module>
    with MapWrapper(2) as p:
  File "C:\Users\Ilhan Polat\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy-1.4.0.dev0+89286b9-py3.7-win-amd64.egg\scipy\_lib\_util.py", line 385, in __init__
    self.pool = Pool(processes=int(pool))
  File "C:\Users\Ilhan Polat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\Ilhan Polat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\Ilhan Polat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\Ilhan Polat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Ilhan Polat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Ilhan Polat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Ilhan Polat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Ilhan Polat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

```

I'll look into it right now but let me know if you see the problem right away.

**Comment by ilayn** [comment]
Looks like we are bitten by this recursive firing https://stackoverflow.com/questions/18204782/runtimeerror-on-windows-trying-python-multiprocessing

**Comment by ilayn** [comment]
@beckermr Could you please test the patch in the linked PR above please?

**Comment by WarrenWeckesser** [comment]
FWIW: I'm on OS X 10.12.6, and I installed Python 3.8 from https://www.python.org/, and used pip3 to install all the scipy dependencies.  I built scipy from the master branch (last commit 35fd20ec1aa05).  The test `../../tests/test__util.py::TestMapWrapper::test_parallel` hangs:

```
$ python3 runtests.py -n -s _lib -m full -v
===================================================================== test session starts =====================================================================
platform darwin -- Python 3.8.0, pytest-5.2.2, py-1.8.0, pluggy-0.13.0 -- /usr/local/bin/python3
cachedir: .pytest_cache
rootdir: /Users/warren/repos/git/forks/scipy, inifile: pytest.ini
collected 40 items                                                                                                                                            

../../tests/test__gcutils.py::test_set_gc_state PASSED                                                                                                  [  2%]
../../tests/test__gcutils.py::test_gc_state PASSED                                                                                                      [  5%]
../../tests/test__gcutils.py::test_assert_deallocated PASSED                                                                                            [  7%]
../../tests/test__gcutils.py::test_assert_deallocated_nodel PASSED                                                                                      [ 10%]
../../tests/test__gcutils.py::test_assert_deallocated_circular PASSED                                                                                   [ 12%]
../../tests/test__gcutils.py::test_assert_deallocated_circular2 PASSED                                                                                  [ 15%]
../../tests/test__testutils.py::test__parse_size PASSED                                                                                                 [ 17%]
../../tests/test__testutils.py::test__mem_available PASSED                                                                                              [ 20%]
../../tests/test__threadsafety.py::test_parallel_threads PASSED                                                                                         [ 22%]
../../tests/test__threadsafety.py::test_reentering PASSED                                                                                               [ 25%]
../../tests/test__util.py::test__aligned_zeros PASSED                                                                                                   [ 27%]
../../tests/test__util.py::test_check_random_state PASSED                                                                                               [ 30%]
../../tests/test__util.py::TestMapWrapper::test_serial PASSED                                                                                           [ 32%]
../../tests/test__util.py::TestMapWrapper::test_parallel 
```

**Comment by rgommers** [comment]
Ah, this is why macOS started failing for 3.8 (from [the docs](https://docs.python.org/3.8/library/multiprocessing.html#contexts-and-start-methods)):

_Changed in version 3.8: On macOS, the spawn start method is now the default._

Further down it states: _Functionality within this package requires that the `__main__` module be importable by the children._ That explains the infinite recursion probably, `__main__` is from pytest.

Reviewing the `MapWrapper` code again, I think it's fine as is. User code should have a `__main__` or they will trigger this issue, but that's unavoidable probably - IIRC joblib has this issue as well.

**Comment by ilayn** [comment]
Indeed, that's how I ended up with the fix. Looks like we are still OK sans the test fix.

**Comment by rgommers** [comment]
This is a known issue with `pytest` + `multiprocessing`: https://github.com/pytest-dev/pytest/issues/958

Suggested workaround is to run the tests with `python -m pytest ...`

**Comment by beckermr** [comment]
Hmmmmm. Do you have suggestions for this test script on the conda feedstock?

https://github.com/conda-forge/scipy-feedstock/blob/master/recipe/run_test.py

**Comment by ilayn** [comment]
> Suggested workaround is to run the tests with python -m pytest ...

I'd rather guard on SciPy side instead of hitting this again if something else changes on the pytest side.

**Comment by rgommers** [comment]
Yes, if the guard in gh-11034 is correct, that's definitely preferable.

**Comment by andyfaff** [comment]
I don't understand why tests have started failing on Python 3.7, they've been running ok up until now.

**Comment by andyfaff** [comment]
> This is a known issue with pytest + multiprocessing: pytest-dev/pytest#958
Suggested workaround is to run the tests with python -m pytest ...

See:
https://github.com/pypa/setuptools/issues/443

**Comment by ilayn** [comment]
I am using the latest setuptools and unfortunately it is not solved.

**Comment by beckermr** [comment]
Here are the rest of the tests that fail. Only 2

https://github.com/conda-forge/scipy-feedstock/blob/07c055613430e7cdfe9932caa410af5ca1fcd17e/recipe/scipy-1.3.2-bad-tests.patch

**Comment by ilayn** [comment]
I've added both to the linked PR as a skipif.
