### ISSUE TITLE
DOC: graphical guides font size

### ISSUE THREAD

**Issue by mkg33** [scipy/scipy#11047]
I'd like to know what you think about the adjusted font size in the graphical guides (see also #10875). I'm attaching two screenshots. The first one shows the original (unzoomed) website, the second one is a zoomed view (to be more precise: the generic zoom you get on macOS by a double click). Don't pay attention to the tree itself (and the sample 'getting started' page), it's a mess because I had to readjust the font. I only want to know if you think that this font size is acceptable and if I can proceed with it. I'd be grateful for your feedback!

![tree1](https://user-images.githubusercontent.com/26354268/68551498-d7cf6280-040d-11ea-925c-83b35c040742.jpg)
![tree2](https://user-images.githubusercontent.com/26354268/68551500-da31bc80-040d-11ea-9c01-56780d10afce.jpg)

**Comment by rgommers** [comment]
I think that's much better, should work. The font is still slightly smaller than the regular text font on the page, but that's fine I think. It'll be hard to make everything fit otherwise. This should be readable.

**Comment by mkg33** [comment]
Thanks, @rgommers. I'll now rearrange the nodes using the new font size.
