### ISSUE TITLE
scipy.stats: Allow specifying inverse-variance matrix to multivariate_normal

### ISSUE THREAD

**Issue by adrn** [scipy/scipy#11053]
**Describe the solution you'd like**

Currently, `scipy.stats.multivariate_normal` accepts a mean and covariance matrix, and computes the inverse variance matrix internally and explicitly. But I often have covariance matrices with inverses that can be computed through other linear algebra tricks, e.g., the woodbury matrix identity. It would therefore be great if `scipy.stats.multivariate_normal` would allow optionally passing in an inverse-variance matrix, which is sometimes useful for (a) performance, or (b) numerical precision issues with covariance matrices with large values. 

I thought I would raise an issue here to discuss before actually implementing anything, but I would be happy to work on a PR.

**Describe alternatives you've considered**

I have either implemented my own `custom_multivariate_normal` distribution, or used the [implementation in astroML](https://github.com/astroML/astroML/blob/master/astroML/utils/utils.py#L22) to compute the log-pdf, but it would be nice to have this included in scipy as well.

**Comment by rlucas7** [comment]
I am not opposed to this proposal. However, that would change things in many signatures so probably want to get a broad agreement. Usually these discussions happen on the dev mailing list, I recommend sending the proposal there with an idea of how you would implement. Not the whole code just something more specific than the proposal. 

To be clear, your proposal would *not* include SMW theorem type inversions inside the mVN methods, correct?

I understood that you would do the inversion on user side and pass the inverted matrix into the mVN method(s). 

-Lucas Roberts

**Comment by adrn** [comment]
That's right, I was imagining just adding a new argument to accept the inverted matrix into the mVN methods — it would be up to the user to do the inversion. I'll open a thread on the mailing list - thanks.

**Comment by rgommers** [comment]
So this would change
```
pdf(x, mean=None, cov=1, allow_singular=False)
```
to
```
pdf(x, mean=None, cov=1, allow_singular=False, inverse_cov=None)
```
and the same for `cdf`, `entropy`, `logcdf`, `logpdf` and `rvs`?

Seems reasonable.

**Comment by ljwolf** [comment]
Elsewhere in statistics, I think the inverse covariance matrix is usually called the ["precision" matrix.](https://en.wikipedia.org/wiki/Precision_(statistics)) Other packages use either "precision" ([stan](https://mc-stan.org/docs/2_20/functions-reference/multivariate-normal-distribution-precision-parameterization.html)) or "tau" ([PyMC3](https://docs.pymc.io/api/distributions/multivariate.html#pymc3.distributions.multivariate.MvNormal)) as a separate argument that supersedes the default cov. "Precision" might be the more generally used term?

**Comment by ilayn** [comment]
I would prefer the inverse instead of a domain specific terminology.

**Comment by rlucas7** [comment]
> So this would change
> 
> ```
> pdf(x, mean=None, cov=1, allow_singular=False)
> ```
> 
> to
> 
> ```
> pdf(x, mean=None, cov=1, allow_singular=False, inverse_cov=None)
> ```
> 
> and the same for `cdf`, `entropy`, `logcdf`, `logpdf` and `rvs`?
> 
> Seems reasonable.

I think entropy works with ***covariance*** matrix whereas the others work with inverse covariance matrix, so for `entropy` method you'd still need to invert if you passed in inverse covariance. 

Another thing to consider is a flag for removing PSD checks. I've found in simulations that PSD checks can take a fair bit of overhead, even if you pass in the same covariance (or inverse covariance) matrix every time, or are (say) drawing from a wishart/inverse wishart which is PSD by construction. 

It sounds like one of the goals here is speed/performance so wanted to point this out too.

**Comment by mdhaber** [comment]
@adrn thanks for this suggestion! What was the verdict of the mailing list discussion?

**Comment by adrn** [comment]
@rgommers expressed support, but I don't think anyone else chimed in! I forgot about this but could take another crack at it if you think it'd be useful :)

**Comment by rgommers** [comment]
Mailing list link: https://mail.python.org/pipermail/scipy-dev/2019-November/023843.html

> @rgommers expressed support, but I don't think anyone else chimed in! 

That's not uncommon. Discussion typically happens here, the mailing list message gets seen by many more people though so it's a good data point that no one was opposed.

**Comment by adrn** [comment]
Yes, makes sense - not a criticism, just reporting :)

**Comment by mdhaber** [comment]
Thanks @adrn. Based on what I see here and from the limited response on the mailing list, sounds like a PR would be welcomed. (How long it takes to get a full review depends on how complicated it is!)

**Comment by jsbryaniv** [comment]
I would like to see an inverse_cov option. In my MCMC algorithms I often have to compute the log probability many times using the same cov matrix. It does not make sense for me to recompute the inverse at each iteration if i am using the same cov matrix and therefore it would be convenient to have inverse_cov as an option. Until this becomes an option I have to define my own multivariate normal log pdf function that allows inverse_cov which is annoying

**Comment by zoj613** [comment]
Here is a similar discussion at numpy: https://github.com/numpy/numpy/issues/17158

For those interested, I wrote a cython function to do just this some time ago:
https://github.com/zoj613/OccuSpytial/blob/e599d515b5377cb8f7a16af828f39b115a04bc66/occuspytial/distributions.pyx#L42-L110

**Comment by siddhantwahal** [comment]
I was curious as to how this could be done and ended up making significant progress (branch: https://github.com/siddhantwahal/scipy/tree/enh/mvn-normal-inv-cov). The implementation rests on storing square roots of the covariance and the inverse covariance. This has two advantages:
1. It avoids repeated computation of the covariance square root in `multivariate_normal.rvs` (#11772)
2. It can be easily extended to allow the user to specify covariance square roots directly (through the `CovInfo` object). See #15675 for example.

Would a PR still be welcome?
