### ISSUE TITLE
optimize.dual_annealing does not pass arguments to jacobian.

### ISSUE THREAD

**Issue by juliusbierk** [scipy/scipy#11052]
`dual_annealing` does not work with extra arguments and provided jacobians:

Example:
```
from scipy.optimize import dual_annealing
import numpy as np

def f(x, power):
    return np.sum(np.exp(x**power))

def jac(x, power):
    return np.exp(x**power) * power * x**(power - 1)
```

Now this works fine:
```
res1 = dual_annealing(f, args=(2, ), bounds=[[0, 1], [0, 1]],
                      local_search_options=dict(method='L-BFGS-B'))
print("Works!", res1.x)
```

However, this doesn't work:
```
res2 = dual_annealing(f, args=(2, ), bounds=[[0, 1], [0, 1]],
                      local_search_options=dict(method='L-BFGS-B',
                                                jac=jac))
```
giving error `jac() missing 1 required positional argument: 'power'`.

This also doesn't work:
```
res3 = dual_annealing(f, args=(2, ), bounds=[[0, 1], [0, 1]],
                      local_search_options=dict(method='L-BFGS-B',
                                                jac=jac,
                                                args=(2, )))
```
giving error `fun() takes 2 positional arguments but 3 were given`.

It seems `args` are given to `fun` but not to `jac`. Trying to include them gives `fun` too many arguments.

#### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
>>> 1.3.1 1.17.3 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

**Comment by juliusbierk** [comment]
Related:

Custom minimizers cannot pass extra extra to function because it is wrapped.
I would suggest adding `kwargs` here (in _dual_annealing.py):

```
class ObjectiveFunWrapper(object):
...
    def fun(self, x, **kwargs):
        self.nfev += 1
        return self.func(x, *self.args, **kwargs)
```

**Comment by rgommers** [comment]
thanks for the report @juliusbierk. @sgubianpm any chance you could look at this?

**Comment by sgubianpm** [comment]
@juliusbierk, @rgommers 
Sure. I am fixing that and adding a unit test to make sure this works fine. PR to come today for it.

**Comment by andyfaff** [comment]
@sgubianpm, did you make a PR to close this?

**Comment by sgubianpm** [comment]
@andyfaff , sorry guys, completely forgot about it. Just sent the PR now.

**Comment by mdhaber** [comment]
Re: https://github.com/scipy/scipy/issues/11052#issuecomment-552822498, please open an enhancement request if this is still a concern. It is documented that `func`
> Must be in the form `f(x, *args)`

so it does not seem like a bug.
