### ISSUE TITLE
Feature request: Nelder-Mead with bounds

### ISSUE THREAD

**Issue by juliusbierk** [scipy/scipy#11050]
Currently `scipy.optimize.minimize` provides no gradient-free optimization schemes for bounded problems. Nelder-Mead is perhaps the most frequently used such algorithm, and it can work with bounds too:
At expansion or reflection steps, the variables need to be projected to be within bounds. For description see Appendix A of "A constrained, globalized, and bounded Nelder–Mead method
for engineering optimization".

**Comment by andyfaff** [comment]
While not `minimize` differential_evolutuin will do what you require.

**Comment by juliusbierk** [comment]
> While not `minimize` differential_evolutuin will do what you require.

True, but that's a global method... if only local minimization is required, this should converge much faster.

**Comment by andyfaff** [comment]
https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.emse.fr/~leriche/GBNM_SMO_1026_final.pdf&ved=2ahUKEwizuuntypPnAhW04HMBHd43B4YQFjABegQIBRAB&usg=AOvVaw0Ox-n6PW-v7Uq2OMUyXlYo&cshid=1579571904651

**Comment by andyfaff** [comment]
Sorry for the poor formatting. It's a link to the paper. As far as I can tell it's a simple clip to bounds.

**Comment by annehulsey** [comment]
What is the status on implementing the Globalized Bounded Nelder–Mead algorithm from the paper link above? I am at a deadend and hoping that this will be available soon.

**Comment by andyfaff** [comment]
As far as I know no one is currently working on this. Pull requests are welcomed.
