### ISSUE TITLE
Adding logsoftmax function

### ISSUE THREAD

**Issue by cycentum** [scipy/scipy#11058]
Hello,
 
I’m considering to send a PR to add logsoftmax function in scipy.special. Before that, I would like to hear your opinion (partly because it’s my first time to send a PR to scipy).
 
I would like to implement `logsoftmax(x)` as `x-logsumexp(x)`. Actually, `special.softmax(x) = np.exp(x-logsumexp(x))`, so it is trivial for those who read the source code of softmax, but I think including logsoftmax as a separate function will be useful for other users. Logsoftmax is more accurate with inputs that make softmax saturate, eg: When `x=[1000, 0]`, `np.log(softmax(x))=[0, -Inf]` (maybe depending on the floating point precision), while `logsoftmax(x)=[0, -1000]`.
 
I am planning to add the new function at the bottom of special/_logsumexp.py following the softmax function, and add some unit tests in special/test/test_logsumexp.py. If you have comments, I’d appreciate any.

**Comment by rgommers** [comment]
Hi @cycentum, thanks for asking. It sounds like a good idea to me. We normally propose and decide on new features on the `scipy-dev` mailing list (see https://scipy.org/scipylib/mailing-lists.html). Can you please propose it there as well?

**Comment by cycentum** [comment]
@rgommers Thank you. I posted it to scipy-dev.

**Comment by ricardoV94** [comment]
@cycentum any reason why the final implementation wasn't simply `x - logsumexp(x)`? I couldn't see why that's better than the current `x - max - logsumex(x - max)` (without repeating the logic in `logsumexp` of course)
