### ISSUE TITLE
CDF calculation at multivariate_normal is potentially wrong

### ISSUE THREAD

**Issue by reicherthannes** [scipy/scipy#11077]
The CDF calculation seems to be incorrect.
If you try to test the CDF calculation with a QQ plot, you will not get the expected result.
If this error is due to a fundamentally wrong understanding of statistics, I apologize for having  this issue opened. See code for more details.

```python
def test_quantiles(quantiles, theoretic_quantiles = np.arange(0.0, 1.01, 0.1)):
    occurences = []
    for q in theoretic_quantiles:
        occ = quantiles < q
        occurences.append(np.sum(occ, axis=0))
    occurences = np.array(np.array(occurences)) / np.float64(quantiles.shape[0])
    return occurences

if __name__ == '__main__':
    from scipy.stats import multivariate_normal

    mu_x = 0
    mu_y = 0
    sigma_x = 2
    sigma_y = 1
    rho = 0.5

    # build covariance matrix
    S = np.matrix([[np.square(sigma_x), rho * sigma_x * sigma_y], [rho * sigma_x * sigma_y, np.square(sigma_y)]])
    # build expectation vector
    mu = (mu_x, mu_y)

    # sample from multivariate normal
    samples = np.random.multivariate_normal(mu, S, 10000)

    # since we got a 2D CDF, we calculate the sqrt to obtain the quantiles
    quantiles = np.sqrt(multivariate_normal(mu, S).cdf(samples))

    # get theoretic quantiles
    theoretic_quantiles = np.arange(0.0, 1.01, 0.1)

    observed_quantiles = test_quantiles(quantiles, theoretic_quantiles)

    # plot the observed quantiles over the theoretic_quantiles,
    # in theory this should give a line with the slope of one.
    import matplotlib.pyplot as plt

    plt.figure()
    plt.plot([0.0, 1.0], [0.0, 1.0], '--', Linewidth=5)
    plt.plot(theoretic_quantiles, observed_quantiles, Linewidth=4)
    plt.title('test cdf')
    plt.show()
```

**Comment by josef-pkt** [comment]
I'm not sure what you are doing. But I'm pretty sure that you cannot do a qq-plot this way for a bivariate or multivariate distribution.

It might be possible to compute the cdf on a grid on a ray of values and compare it with the empirical frequences

**Comment by josef-pkt** [comment]
> quantiles = np.sqrt(multivariate_normal(mu, S).cdf(samples))

sqrt only makes sense if the correlation is zero and if the cdf value in each component is the same.
Otherwise, you cannot reduce the 2-dim cdf to a 1-dim variable

**Comment by reicherthannes** [comment]
Thank you for your fast response.
I'm trying to test a multivariate mixture density network for reliability which is quite difficult.
This has nothing to do with the issue, so I close it.
