### ISSUE TITLE
ValueError: Unknown wave file format

### ISSUE THREAD

**Issue by AIGyan** [scipy/scipy#11076]
Hello team I am trying to read a wave file and getting the following error. Please help.

`spy.io.wavfile.read('test.wav')`

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-65-0455a60cc045> in <module>()
> ----> 1 spy.io.wavfile.read('test.wav')
> 
> ~/anaconda3/lib/python3.6/site-packages/scipy/io/wavfile.py in read(filename, mmap)
>     250             if chunk_id == b'fmt ':
>     251                 fmt_chunk_received = True
> --> 252                 fmt_chunk = _read_fmt_chunk(fid, is_big_endian)
>     253                 format_tag, channels, fs = fmt_chunk[1:4]
>     254                 bit_depth = fmt_chunk[6]
> 
> ~/anaconda3/lib/python3.6/site-packages/scipy/io/wavfile.py in _read_fmt_chunk(fid, is_big_endian)
>      92 
>      93     if format_tag not in KNOWN_WAVE_FORMATS:
> ---> 94         raise ValueError("Unknown wave file format")
>      95 
>      96     # move file pointer to next chunk
> 
> ValueError: Unknown wave file format

**Comment by endolith** [comment]
As it says, the format of the WAV file is not supported.  The error should probably elaborate and say what format it is and what formats are supported?
