### ISSUE TITLE
Different formatting in documentation page

### ISSUE THREAD

**Issue by jakobjakobson13** [scipy/scipy#11074]
Hi,

the formatting of the `scipy.constants` documentation differs between the [current](https://docs.scipy.org/doc/scipy/reference/constants.html) and the [devel](http://scipy.github.io/devdocs/constants.html) version even though the file was not substantially altered during the last pull request.
It's not a critical bug report but the devel version looks kind of odd.

Regards

Jakob

PS: I used firefox 70 on a ubuntu 18.04 pc.

**Comment by rgommers** [comment]
Hmm odd, could be a Sphinx or numpydoc thing perhaps.

**Comment by jakobjakobson13** [comment]
Has been fixed.
