### ISSUE TITLE
scipy.stats.skew doesn't work correctly for float point numbers

### ISSUE THREAD

**Issue by kartikeyaSh** [scipy/scipy#11086]
https://github.com/scipy/scipy/blob/78904d646f6fea3736aa7698394aebd2872e2638/scipy/stats/stats.py#L1043-L1134

#### Reproducing code example:
`skew(np.array([14.3]*7))` gives `1` not `0`.
It turn out that
`np.mean([14.3]*7)` outputs: `14.299999999999999`
which i understand is a well known float point precision problem. But should the skew function take it into consideration? It can't work for float point numbers in the current form.

#### Scipy/Numpy/Python version information:
I don't think it has anything to do with version.
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.3.1 1.16.4 sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment]
I'm seeing a lot of zeros in the definition of skewness. Is skewness defined for the case in which all sample values are the same? Is there another case in which this function fails to produce the expected result?

**Comment by mdhaber** [comment]
@kartikeyaSh is the example above illustrate the precision loss due to cancellation error between the data and the mean? e.g.
```
import numpy as np
from scipy.stats import skew
d = 1e-16
x = 1 + np.arange(-3, 4)*d
print(skew(x))
```
prints
```
-0.5127964316525148
```
or would you consider this a different problem?

**Comment by kartikeyaSh** [comment]
@mdhaber 
The example that I gave above shows an array which is an array with uniform distribution (each value is 14.3).
So the skew is expected to be zero, but what ends up happening is the precision loss while calculating the mean( which becomes 14.299999999999999) due to which <img src="https://render.githubusercontent.com/render/math?math=x[n]-\bar{x}">  in the formula 
<img src="https://render.githubusercontent.com/render/math?math=m_i=\frac{1}{N}\sum_{n=1}^N(x[n]-\bar{x})^i"> becomes some non zero value, and the results after that show skew to be present, which will not exist if we didn't had precision loss while calculating mean. 

You created the precision loss using a very small `d` value but the error occurs because of the same reason. 
```
import numpy as np 
from scipy.stats import skew 
d = 1e-16 
x = 1 + np.arange(-3, 4)*d 
print(x) 
print(np.mean(x)) 
print(x - np.mean(x)) 
print(skew(x)) 
```
outputs:
```
[1. 1. 1. 1. 1. 1. 1.]
1.0
[-3.33066907e-16 -2.22044605e-16 -1.11022302e-16  0.00000000e+00
  0.00000000e+00  2.22044605e-16  2.22044605e-16]
-0.5127964316525148
```
whereas for d value `1`:
```
import numpy as np 
from scipy.stats import skew 
d = 1 
x = 1 + np.arange(-3, 4)*d 
print(x) 
print(np.mean(x)) 
print(x - np.mean(x)) 
print(skew(x))
```
outputs:
```
[-2 -1  0  1  2  3  4]
1.0
[-3. -2. -1.  0.  1.  2.  3.]
0.0
```
which is expected.
So I guess it can be considered same

**Comment by mdhaber** [comment]
@WarrenWeckesser I should have pinged you here, too. Thanks for fixing gh-12815 in gh-13154; can that approach be applied here? Is it enough to patch these for the specific case of all-inputs constant, or is there some way to also address the loss of precision for small differences from the mean?

**Comment by WarrenWeckesser** [comment]
We could check for the special case that the input is constant, but dealing with the loss of precision when the values are almost constant is a harder problem.

(If we do update `skew`, we should also fix it to not use the `mstats` function to handle `nan_policy='omit'`. )

**Comment by mdhaber** [comment]
OK. I'm not sure how much value there is in patching these for the case of exactly constant input if they're going to fail when the input is nearly constant. 

- Is the exactly constant case more likely than nearly constant?
- Is someone less likely to notice that their data is exactly constant than if it were nearly constant?

If no, then does it make sense to provide a relatively involved (e.g. gh-13154) partial fix, or would a warning in the docstring suffice?

**Comment by mdhaber** [comment]
This will be fixed by gh-13254
