### ISSUE TITLE
Inaccuracy in special.j1 function

### ISSUE THREAD

**Issue by jacksonvanover** [scipy/scipy#11084]
It appears that the scipy implementation of the j1 function gets more and more inaccurate as the input grows. This is based on a comparison to mpmath's arbitrary-precision and double-precision implementations (shown below) as well as GSL, all of which agree while scipy diverges further and further from the general consensus. If we treat the arbitrary-precision implementation as the ground truth, then the relative error between the mpmath double-precision output and the scipy output in the last example with an input of`999999999999999` is `0.05611426102699589`

#### Reproducing code example:

```
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mpmath import *
>>> from scipy import special
>>> x = 9999      
>>> (mp.j1(x),fp.j1(x),special.j1(x))
(mpf('0.0079424897098126258'), 0.007942489709812628, 0.007942489709812468)
>>> x = 99999999
>>> (mp.j1(x),fp.j1(x),special.j1(x))
(mpf('1.2498792106242295e-5'), 1.2498792106242292e-05, 1.2498791636381654e-05)
>>> x = 999999999999
>>> (mp.j1(x),fp.j1(x),special.j1(x))
(mpf('-5.1313799111280379e-7'), -5.131379911128037e-07, -5.131339086579077e-07)
>>> x = 9999999999999999
>>> (mp.j1(x),fp.j1(x),special.j1(x))
(mpf('3.556678693744154e-9'), 7.931694266803263e-09, 7.73585954284989e-09)
>>> x = 999999999999999 
>>> (mp.j1(x),fp.j1(x),special.j1(x))
(mpf('8.039843402588297e-9'), 8.0398434025883e-09, 7.58869353127929e-09)
```

#### Scipy/Numpy/Python version information:
1.3.1 1.17.2 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)

**Comment by person142** [comment]
Loss in relative precision is expected for floating-point implementations of oscillatory functions at large arguments. Even a function as simple as e.g. `sin` experiences loss of precision because the period is not exactly representable in double precision.

**Comment by jacksonvanover** [comment]
Perhaps this then would be better phrased as a feature request. GSL's implementation which is based on the SLATEC source is more stable at larger arguments than the cephes algorithm. Both use double precision. Perhaps worth looking into for someone who is interested? This is a bit outside of my wheelhouse at this point. Thanks!
