### ISSUE TITLE
ENH: stats.loggamma: improve for small values of c

### ISSUE THREAD

**Issue by remilepriol** [scipy/scipy#11094]
Loggamma takes the log of scipy.stats.gamma to sample. 

```python
def _rvs(self, c):
    return np.log(self._random_state.gamma(c, size=self._size))
```

When the shape parameter c is small, the loggamma has a large left tail. We cannot sample in there because the gamma draw samples which are smaller than what can be represented by float 64, so that the actual tail is truncated to values greater than -600. The code below illustrates this behavior.

It happens that for small values of c, the loggamma is well approximated by a negative exponential distribution. Does it seem reasonable to change the sampling procedure so that for smaller values of c, samples are drawn from an exponential, or to use some other sampling scheme that guarantee stability for small c ?

```python
import numpy as np
import matplotlib.pypot as plt
from scipy import stats

n = 1000
c = 1/1000
law = stats.loggamma(c)

# inverse transform samples
uu = np.random.rand(n)
samples = law.ppf(uu)
samples = samples[np.invert(np.isinf(samples))]
plt.hist(samples, bins=20, density=True)

# scipy sampling
samples2 = law.rvs(size=1000)
samples2 = samples2[np.invert(np.isinf(samples2))]
plt.hist(samples2, bins=20, density=True, alpha=.5)

# exponential sampling
samples3 = -stats.expon.rvs(scale=1/c, size=n)
plt.hist(samples3, bins=20, density=True, alpha=.5)

# density plot
xx = np.linspace(np.nanmin(samples3),2, 1000)
plt.plot(xx, law.pdf(xx))

print(len(samples), len(samples2), len(samples3))
pass
```

![image](https://user-images.githubusercontent.com/10254544/69189295-1ccd5600-0aec-11ea-91d7-9e3e68032205.png)

**Comment by mdhaber** [comment]
> It happens that for small values of c, the loggamma is well approximated by a negative exponential distribution.

Hi @remilepriol thanks for your patience on this. Can you provide a reference for this? 

Better yet, for a given threshold where we would switch loggamma sample to negative exponential sampling, can you bound the relative difference between the CDFs below the threshold?

**Comment by remilepriol** [comment]
Hello Matt,

I am not aware of any reference,  and could not bound the CDF difference myself. I simply looked at the log-pdf curves.

**Comment by mdhaber** [comment]
Ah, OK. I don't think we can do this without mathematical justification. I'll leave this open though, as the issue remains that sampling doesn't work well in the left tail for small `c`. Regarding your plot, though - I am not seeing good agreement from 0 to -600. Is the current sampling method working well there, and everything below that is just cut off, or is it sampling improperly from 0 to -600? Is it over-represented because samples are smaller values are not being drawn?

**Comment by mdhaber** [comment]
Really this isn't a `rvs` issue. The only thing that seems to work at this small `c` is the `pdf`. I was hoping gh-13319 would work, but even the CDF isn't working, because `scipy.special.gammainc` has trouble with these small arguments.

```python3
import numpy as np
import matplotlib.pyplot as plt
from scipy.special import gammainc
c = 1/1000
x = np.linspace(-1000, 0, 100)
plt.plot(x, gammainc(1/1000, np.exp(x)))
```
![image](https://user-images.githubusercontent.com/6570539/103585439-e4c3d680-4e97-11eb-8168-53a020102003.png)

**Comment by WarrenWeckesser** [comment]
There is a technique that we can use when the shape parameter is small.  The gamma distribution Gamma(c) has the property that

    Gamma(c) ~ Gamma(c + 1) * U**(1/c)

where Gamma(c) is the standard gamma distribution (loc=0, scale=1), and U is the uniform distribution on [0, 1].  Then

    log Gamma(c) ~ log(Gamma(c + 1)) + log(U)/c

The script below generates the following plot.  The top plot is a histogram of the variates generated by `loggamma.rvs` with c = 0.001, and the bottom plot is the histogram of a sample generated using the alternative formulation.  The black curve is the PDF, scaled to match the expected histogram values.
![Figure_1](https://user-images.githubusercontent.com/321463/103588104-878b4d80-4eb6-11eb-8eed-714add8220dc.png)

Other possible approaches can be found in Devroye's book "Non-Uniform Random Variate Generation", section IV.3.

Here's the script:
```
import numpy as np
from scipy.stats import loggamma
import matplotlib.pyplot as plt


rng = np.random.default_rng()

n = 10000000
c = 0.001
x = loggamma.rvs(c, size=n)
# Remove -inf from x
x = x[~np.isinf(x)]

# Use the property of the gamma distribution Gamma(c)
#    Gamma(c) ~ Gamma(c + 1)*U**(1/c),
# where U is uniform on [0, 1], so
#    log(Gamma(c)) ~ log(Gamma(c + 1)) + log(U)/c
w = np.log(rng.gamma(c + 1, size=n)) + np.log(rng.uniform(size=n))/c


hist_xmin = -5000
hist_xmax = 5

plt.subplot(2, 1, 1)

h1 = plt.hist(x, bins=500, range=(hist_xmin, hist_xmax), alpha=0.5)

dx1 = h1[1][1] - h1[1][0]
xx = np.linspace(hist_xmin, hist_xmax, 6000)
plt.plot(xx, n*loggamma.pdf(xx, c)*dx1, 'k')

plt.subplot(2, 1, 2)

h2 = plt.hist(w, bins=500, range=(hist_xmin, hist_xmax), alpha=0.5)

dx2 = h2[1][1] - h2[1][0]
plt.plot(xx, n*loggamma.pdf(xx, c)*dx2, 'k')

plt.show()
```

**Comment by WarrenWeckesser** [comment]
gh-13349 uses the alternative formulation for `loggamma._rvs`.

**Comment by remilepriol** [comment]
Interesting @WarrenWeckesser  ! This approach you suggest is similar to my initial guess, as `log(U)/c` is exactly an exponential variable with scale parameter `1/c`. The difference is that you add this `log(Gamma(c + 1))` which allows for positive values of `x`. However we still don't know an error bound on the difference, and it might be inappropriate to use it for _all_ values of c. Does Devroye provide any insights on this topic in his book ?

**Comment by WarrenWeckesser** [comment]
> However we still don't know an error bound on the difference, and it might be inappropriate to use it for all values of c

This is an exact relationship that is valid for any c > 0, i.e. the distribution of `Gamma(c)` is the same as the distribution of `Gamma(c + 1)*U**(1/c)`.  (I used the symbol `~` to mean "is distributed as", not "is approximately equal to".)  The relation is also noted in the last sentence of the section [Generating gamma-distributed random variables](https://en.wikipedia.org/wiki/Gamma_distribution#Generating_gamma-distributed_random_variables) of the wikipedia article on the gamma distribution.

**Comment by remilepriol** [comment]
I see ! When c is low, the exponential variable captures large negative values of x and compensates the faulty gamma(c+1) , while for larger c, this relationship is exact. That sounds like a great approach.

**Comment by WarrenWeckesser** [comment]
Here's a concrete example of the problem that @mdhaber referred to in https://github.com/scipy/scipy/issues/11094#issuecomment-754258491:

```
In [12]: loggamma.cdf(-800, 0.001)
Out[12]: 0.0
```
The true value is 0.44958802911019136 (computed with `mpmath`).  For any x < -745.2, the computed CDF is 0, because `exp(x)` underflows to 0 and the `cdf` method computes `gammainc(c, np.exp(x))`.
```
