### ISSUE TITLE
BUG: multiscale_graphcorr random state seeding and parallel use

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#11100]
Test failure observed in gh-11095:
```
scipy.stats.multiscale_graphcorr
--------------------------------
File "build/testenv/lib/python3.6/site-packages/scipy/stats/stats.py", line 4612, in multiscale_graphcorr
Failed example:
    '%.3f, %.2f' % (mgc.stat, mgc.pvalue)
Expected:
    '0.033, 0.02'
Got:
    '0.033, 0.03'
```

The issue is in the `_ParallelP` class, it uses `np.random.permutation` without the option of providing a `Generator` or `RandomState` object or a seed. This should be possible for reproducibility. The design pattern to use is a `random_state=None` keyword I think, just like the `rvs` method of all distributions, or `stats.rvs_ratio_uniforms`.

There's actually more to it than that - for parallel usage it's not clear that `_ParallelP` does the right thing. Looks like it should be using one of the parallel rng methods: https://numpy.org/devdocs/reference/random/index.html#parallel-generation
Those are not available in NumPy < 1.17 though. In the absence of that, we are likely to get issues with non-independent streams: https://github.com/numpy/numpy/issues/9650. Should either at least generate different seeds before spawning new processes, or disable the feature.

@sampan501 @jovo thoughts?

**Comment by jovo** [comment]
@rgommers i don't know enough about it to have an informed opinion.
maybe @randalburns or @disa-mhembere can opine?

**Comment by sampan501** [comment]
@rgommers Would it suffice doing something like this from scikit-learn's random forest:
```
seeds = [random_state.randint(MAX_INT, size=i) for i in n_trees]
```
where `random_state` is defined as
```
random_state : int, RandomState instance or None, optional (default=None)
        If int, random_state is the seed used by the random number generator;
        If RandomState instance, random_state is the random number generator;
        If None, the random number generator is the RandomState instance used
        by `np.random`.
```
and when `random_state` is passed it is checked via this function
```
def check_random_state(seed):
    """Turn seed into a np.random.RandomState instance
    If seed is None, return the RandomState singleton used by np.random.
    If seed is an int, return a new RandomState instance seeded with seed.
    If seed is already a RandomState instance, return it.
    Otherwise raise ValueError.
    """
    if seed is None or seed is np.random:
        return np.random.mtrand._rand
    if isinstance(seed, (numbers.Integral, np.integer)):
        return np.random.RandomState(seed)
    if isinstance(seed, np.random.RandomState):
        return seed
    raise ValueError('%r cannot be used to seed a numpy.random.RandomState'
                     ' instance' % seed)
```

**Comment by disa-mhembere** [comment]
@jovo, in the past as a quick and dirty way to deterministically obtain random numbers for a parallel workflow I have just pre-generated them as @rgommers suggested. It's a perfectly good solution especially if you know the # of variables required a priori and the generation is not the computational bottleneck. You can also seed a serial generator and serialize calls to it. If this isn't possible, there is a rich literature on DPRNGs -- some of which have packages.

**Comment by ev-br** [comment]
I think the right API would be the  `random_state` keyword which depends on the number of workers. If `workers=1`, then it's a scalar which is passed through check_random_state.
If workers !=1, then it should be an iterable with `len(random_state) == workers`, where each element is a seed for the corresponding worker (i.e., each element goes through `check_random_state`). If the number of seeds is smaller than `workers`, it's a hard error. To be forward-compatible, we can allow parallel Generators from numpy, too.

**Comment by tylerjereddy** [comment]
I took a look at this locally---seems tricky. Is this really likely to be properly fixed with forward-compatibility for new random features in place in two days? Maybe a temporary disable of the feature is  in order, short term?

**Comment by tylerjereddy** [comment]
If we go the temporary disable route, probably best if someone more familiar with `stats` submodule tackles that.

**Comment by rgommers** [comment]
I'll have a go at it on the weekend. Today is last day of Season of Docs, that has priority right now.

**Comment by sampan501** [comment]
> I think the right API would be the `random_state` keyword which depends on the number of workers. If `workers=1`, then it's a scalar which is passed through check_random_state.
> If workers !=1, then it should be an iterable with `len(random_state) == workers`, where each element is a seed for the corresponding worker (i.e., each element goes through `check_random_state`). If the number of seeds is smaller than `workers`, it's a hard error. To be forward-compatible, we can allow parallel Generators from numpy, too.

This makes sense in the case the ``workers`` is an int, but not sure what to do when ``workers`` is a map-like callable.
