### ISSUE TITLE
New warnings under gcc9

### ISSUE THREAD

**Issue by dmacks** [scipy/scipy#11118]
Building scipy-1.2.1 on OS X 10.13 with compilers and python supplied by fink:

```
 export CC=/sw/bin/gcc-fsf-9
 export CXX=/sw/bin/g++-fsf-9
 export FC=/sw/lib/gcc9/bin/gfortran
 export PATH="/sw/lib/gcc9/bin:$PATH"
 ATLAS=None /sw/bin/python27 setup.py build --fcompiler gnu95
```

gives

```
compiling Fortran sources                                                                                                                                                        
Fortran f77 compiler: /sw/lib/gcc9/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops                                                            
Fortran f90 compiler: /sw/lib/gcc9/bin/gfortran -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops                                                                         
Fortran fix compiler: /sw/lib/gcc9/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -fPIC -O3 -funroll-loops
creating build/temp.macosx-10.13-x86_64-2.7/scipy/integrate/odepack
compile options: '-I/sw/lib/python2.7/site-packages/numpy/core/include -c'
gfortran:f77: scipy/integrate/odepack/blkdta000.f
gfortran:f77: scipy/integrate/odepack/bnorm.f
scipy/integrate/odepack/bnorm.f:24:72:

   24 |  10       sum = sum + dabs(a(i1-j,j))/w(j)
      |                                                                        1
Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 10 at (1)
```

where the offending code in bnorm.f is:
```fortran
        do 10 j = jlo,jhi
 10       sum = sum + dabs(a(i1-j,j))/w(j)
        an = dmax1(an,sum*w(i))
```

Is the first of many such warnings I'm seeing that I did not see with gcc8.

It still compiles successfully, but it seems to be a valid warning about code that should be updated to comply with current standards. Newer versions of scipy seem to have the same code blocks.

**Comment by ilayn** [comment]
We can fix all those warnings however these are 3rd party libraries and if we bump the version of those libraries in the future all needs to be included once again. In some rare cases fixing these might also cause backwards incompatibilities since we would be fixing them without the context it is run and might change the behavior. 

Hence so far, if there is no functional breakage, we let those warning slide to avoid extra maintenance burden.

**Comment by rgommers** [comment]
If it becomes really annoying, the way to deal with it would be to add some compiler flags to silence the warnings.
