### ISSUE TITLE
Inconsistent warnings for correlation functions in scipy.stats

### ISSUE THREAD

**Issue by rlucas7** [scipy/scipy#11111]
My issue is about `scipy.stats.spearmanr()` function handling constant input(s). 

#### Reproducing code example:
```
from scipy import stats
sequence_1 = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
sequence_2 = [0, 0.009783728115345005, 0, 0, 0.0019759230121848587, 0.0007535430349118562, 0.0002661781514710257, 0, 0, 0.0007835762419683435]
myspearman = stats.spearmanr(sequence_1,sequence_2)
```
throws a `RuntimeWarning` but provides no informative output. While `pearsonr()` throws a 
`PearsonRConstantInputWarning` which was added in a PR of @WarrenWeckesser in the `1.3.X` release, here is the original PR:
https://github.com/scipy/scipy/pull/9562

#### Error message:
```
>>> myspearman = stats.spearmanr(sequence_1,sequence_2)
/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/numpy/lib/function_base.py:2530: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/numpy/lib/function_base.py:2531: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/rlucas/scipy-dev/scipy/scipy/stats/_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
/Users/rlucas/scipy-dev/scipy/scipy/stats/_distn_infrastructure.py:903: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
/Users/rlucas/scipy-dev/scipy/scipy/stats/_distn_infrastructure.py:1912: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)
# vs...
>>> myspearman = stats.pearsonr(sequence_1,sequence_2)
/Users/rlucas/scipy-dev/scipy/scipy/stats/stats.py:3508: PearsonRConstantInputWarning: An input array is constant; the correlation coefficent is not defined.
  warnings.warn(PearsonRConstantInputWarning())
```

#### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.5.0.dev0+634d0c0 1.16.4 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
```

I'm proposing to have a similar, informative warning message for `spearmanr()`. 

Interestingly, `kendalltau()` does not throw a warning or error on the input but does also produce `nan` in the `namedtuple` results. 

This was originally found by EmJ and asked about on stackoverflow, link: 
https://stackoverflow.com/questions/59002624/why-i-get-nan-in-spearman-correlation-in-python?noredirect=1#comment104258321_59002624

**Comment by rlucas7** [comment]
Reading back over the thread in #9562 now I see the response from @WarrenWeckesser 

>@chrisb83 wrote
>
>    should we replace PearsonRConstantInputWarning by ConstantInputWarning, I think this could >be a generic warning whereas PearsonRNearConstantInputWarning might be indeed a specific >warning for PearsonR

>There are probably other functions that could use a similar pattern, but currently, it is specific to >pearsonr. I'd rather not try to generalize this without concrete use-cases. And if/when we >implement a similar behavior for other functions, I don't think there would be anything wrong with >another function, say foo(), having its own FooConstantInputWarning.
>
>   do we want to show the warnings in the overview generated by init.py?
>
>I debated this, too. I figured they are part of the public API of scipy.stats, so they should be there. >But I don't mind taking them out. They are still documented in the pearsonr docstring, and maybe >that's enough. Any other opinions out there?

Based on that back and forth, provided we all still agree, I'd say the fix for this PR would be to have a separate constant input warning for the `spearmanr()` that provides a similar informative warning and is specialized to the function. 

The only open question that I'd have here is whether we want to have this warning in a hierarchy? I can see e.g. a `kendalltau` constant input warning potentially in the future and maybe something for the regression functions and other interpolations as well. Thoughts?

**Comment by chrisb83** [comment]
> Based on that back and forth, provided we all still agree, I'd say the fix for this PR would be to have a separate constant input warning for the spearmanr() that provides a similar informative warning and is specialized to the function.

Agree

> The only open question that I'd have here is whether we want to have this warning in a hierarchy?

Can you explain?

**Comment by rlucas7** [comment]
I meant if we wanted a parent warning class of constant input and have the different correlation warnings inherit.

Alternate approach would be separate warnings for each that are single inheritance. 

@chrisb83 Does that make sense?

**Comment by rlucas7** [comment]
So I thought about this a bit more and closely checked the source in warren’s PR. The Pearson warning inherits from a runtime warning. From rereading again the comments in the other PR, it sounds like the approach is to create a custom warning for spearman Have inherit from runtime. The benefit there is a simpler hierarchy and the trade off is you need to create a new warning class for each function.

I’ll create a new warning class following Warren’s approach, unless consensus changed.
