### ISSUE TITLE
OverflowError in resample_poly (upfirdn)

### ISSUE THREAD

**Issue by patrick984** [scipy/scipy#11128]
scipy.signal.resample_poly fails if the output vector length would be greater than 2^31-1.

```
Traceback (most recent call last):

  File "<ipython-input-1-ac5d2b0a1632>", line 11, in <module>
    yy = resample_poly(y, 128, 1)

  File "F:\Programs\Miniconda3\lib\site-packages\scipy\signal\signaltools.py", line 2424, in resample_poly
    y = upfirdn(h, x, up, down, axis=axis)

  File "F:\Programs\Miniconda3\lib\site-packages\scipy\signal\_upfirdn.py", line 183, in upfirdn
    return ufd.apply_filter(x, axis)

  File "F:\Programs\Miniconda3\lib\site-packages\scipy\signal\_upfirdn.py", line 82, in apply_filter
    output_shape[axis] = output_len

OverflowError: Python int too large to convert to C long
```

output_shape is created on the previous line (81):
`output_shape = np.asarray(x.shape)`

With an unspecified dtype it appears to get np.int32 by default, which is inadequate for specifying large array shapes.

This could be fixed by explicitly specifying the dtype:
`output_shape = np.asarray(x.shape, dtype=np.int64)`

**Comment by e-q** [comment]
Can you share some more information about your platform and python/NumPy/SciPy versions? I'm able to run the following without a problem both on Scipy 1.3.1 and `master`, with NumPy 1.17.3 and Python 3.7.5
```python
y = np.random.randn(2**25)
yy = sig.resample_poly(y, 2**7, 1)  # Results in yy.size = 2**32
```

**Comment by peterbell10** [comment]
They are on windows where a "C long" is 32 bits.

**Comment by e-q** [comment]
Got it. @patrick984, would you be willing to put together a PR with your suggested fix?

This looks like an occurrence of what is discussed in numpy/numpy#9464, there may be other such occurrences of 32 bit ints lurking around.

**Comment by peytondmurray** [comment]
I'm happy to pick this one up. Would a test be useful here? I don't actually have the RAM to try running `upfirdn` with an array larger than 2^32-1, and the test would be slow, so I'm not sure how useful it would be.
