### ISSUE TITLE
Welch ANOVA

### ISSUE THREAD

**Issue by duke08542** [scipy/scipy#11122]
Recently I have been tasked at doing oneway ANOVA on multiple sample where variance is not equal. For such situations, a Welch ANOVA test is required, but such a function is not included in scipy.stats

It looks to be very easy (about 10 lines of code) to get Welch ANOVA code up and running. I propose to add a var_equal = True default argument to f_oneway(), where when flagged as False will give the Welch ANOVA result instead.

Alternatively, we could have a small function in scipy.stats, to do just this 

--- sample code for anyone who's looking for Welch ANOVA in python  ---- 
<img width="582" alt="Screen Shot 2019-11-25 at 9 57 56 PM" src="https://user-images.githubusercontent.com/45447412/69546398-a5f1fa80-0fce-11ea-8d3d-1e6e52f4ecbf.png">

**Comment by josef-pkt** [comment]
A picture is not really helpful. We cannot copy-paste any code.

**Comment by duke08542** [comment]
def welch_anova_np(*args, var_equal=False):
    # https://svn.r-project.org/R/trunk/src/library/stats/R/oneway.test.R
    # translated from R Welch ANOVA (not assuming equal variance)
    
   F_onewayResult = namedtuple('F_onewayResult', ('statistic', 'pvalue'))

    args = [np.asarray(arg, dtype=float) for arg in args]
    k = len(args)
    ni =np.array([len(arg) for arg in args])
    mi =np.array([np.mean(arg) for arg in args])
    vi =np.array([np.var(arg,ddof=1) for arg in args])
    wi = ni/vi

    tmp =sum((1-wi/sum(wi))**2 / (ni-1))
    tmp /= (k**2 -1)

    dfbn = k - 1
    dfwn = 1 / (3 * tmp)

    m = sum(mi*wi) / sum(wi)
    f = sum(wi * (mi - m)**2) /((dfbn) * (1 + 2 * (dfbn - 1) * tmp))
    prob = special.fdtrc(dfbn, dfwn, f)   # equivalent to stats.f.sf
    return F_onewayResult(f, prob)

**Comment by josef-pkt** [comment]
translation from R is not license compatible, except for cases where we have permission or code that has a compatible license instead of GPL.
But the code is "obvious", so I don't think there can be much copyright on it.

I resurrected some work that I did in 2013 that has some overlap with scipy.stats, Welch and Yuen/Trimmed Anova, and methods that are also in scipy.stats.levene.
https://github.com/statsmodels/statsmodels/pull/6526

**Comment by WarrenWeckesser** [comment]
+1 for adding Welch's ANOVA to SciPy.  We'll be working on expanding the tools available in SciPy for analysis of variance, and we should include Welch's ANOVA in that work.   As @josef-pkt points out, we can't simply copy code that was derived from R code that has a GPL license.  Out of an abundance of caution, it will be best if we go back to the literature and work from original sources when preparing our implementation.  As you point out, though, the implementation might be fairly straightforward, and will likely be unavoidably similar to other implementations.

**Comment by josef-pkt** [comment]
I'm working on my statsmodels PR with several versions of Anova
The Welch version could be easily added with the equal var is False option

The computation just follow the formulas, so we always end up with something like the R derived code above, with maybe different names.

**Comment by josef-pkt** [comment]
I went through the docs of several R packages to see which anovas they have.
The core packages have standard f-oneway and the unequal var/welch option.
I think that would be a useful addition for scipy.

Different versions of anovas are spread out across R packages, Yuen for trimmed mean, and Brown-Forsythe and James for other ways to handle heteroscedasticity for oneway mean anova.

Similarly, there are several types of anova available for `Levene`, e.g. Levene-Welch with median as center would be the unequal variance (of the transformed variable) version.

I'm currently trying to get several of those versions into statsmodels.

**Comment by josef-pkt** [comment]
If there is a refactoring of anova in stats, then it would be useful to add a `oneway_fromstats` (or similarly named) function similar to what was added for t-test.

I started out with three anova functions, but will combine them and delegate to a "generic" from stats version (not properly unit tested yet)
https://github.com/statsmodels/statsmodels/pull/6526/files#diff-35bca0fba301134cbe2dfeb0f32bfd69R212

**Comment by sh-shahrokhi** [comment]
Hello, is there any chance that this could be done? I think it would be a very worthwhile addition.

**Comment by dschmitz89** [comment]
Pull request welcome :)

**Comment by josef-pkt** [comment]
related

I had added oneway anovas to statsmodels
Welch and Brown-Forsythe mean anovas plus trimmed version
https://www.statsmodels.org/dev/generated/statsmodels.stats.oneway.anova_oneway.html#statsmodels.stats.oneway.anova_oneway

with many variations and supporting functions, power, equivalence, variance/dispersion anova, ...
https://www.statsmodels.org/dev/stats.html#oneway-anova

**Comment by mdhaber** [comment]
No movement for five years but now available in statsmodels, so closing.

**Comment by ua-chjb** [comment]
Is there any plan to implement this in Scipy?

**Comment by josef-pkt** [comment]
games howell is still open #22185 

I'm still open to have this also in scipy.

One "mission" is to get users away from hypothesis test with very strong assumption

like equal variance assumption: 
standard t-test, anova versus e.g. their Welch alternatives, or
brunner_munzel instead of wilcoxon, mann, whiteney
games-howell instead of tukey-hsd
(and in statsmodels heteroscedasticity robust standard errors instead of nonrobust standard errors, and
many other cases where I try to favor misspecification robust methods, even though tradition often does not allow them to be the default methods)

target: in 5 to 10 years 80 to 90% of users should use the more robust methods
