### ISSUE TITLE
BUG: segfault when slicing a CSR or CSC sparse matrix with slice start index > stop index

### ISSUE THREAD

**Issue by grlee77** [scipy/scipy#11125]
I noticed a segfault in SciPy that occurs when running the CuPy test suite with 1.4.0rc1. This seems to occur when using a slice with a start index greater than the number of rows to index the matrix.

#### Reproducing code example:

```Python
import numpy as np
import scipy.sparse

data = np.array([0, 1, 2, 3], np.float32)
indices = np.array([0, 1, 3, 2], 'i')
indptr = np.array([0, 2, 3, 4], 'i')
m = scipy.sparse.csr_matrix((data, indices, indptr), shape=(3, 4))

# invalid index that exceeds size of the first axis causes a segfault!
z = m[3:2]

# z = m[3]  # this case raises an IndexError as expected

```

#### Error message:

```
Fatal Python error: Segmentation fault

Current thread 0x00007f28492c5700 (most recent call first):
  File "/home/lee8rx/miniconda3_new/envs/pyir/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 789 in _get_submatrix
  File "/home/lee8rx/miniconda3_new/envs/pyir/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 652 in _get_sliceXslice
  File "/home/lee8rx/miniconda3_new/envs/pyir/lib/python3.7/site-packages/scipy/sparse/_index.py", line 51 in __getitem__
```

#### Scipy/Numpy/Python version information:

```
1.4.0rc1 1.17.2 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by grlee77** [comment]
The same occurs for slices into the columns of CSC matrices. Specifically, this test case:
https://github.com/cupy/cupy/blob/4586fedac8254dcd71d97617f2f95f98254dbbcc/tests/cupyx_tests/scipy_tests/sparse_tests/test_csc.py#L1011-L1013

**Comment by grlee77** [comment]
I get the same fault for 1.3.0 and 1.3.3, but it does not segfault on 1.2.2:
```IndexError: index out of bounds: 0 <= 3 <= 3, 0 <= 2 <= 3, 3 <= 2```

**Comment by grlee77** [comment]
I think the issue was introduced with this fairly large commit: #7827. will take a look and see if I can find where the check should occur

**Comment by denis-bz** [comment]
This testcase on [SO](https://stackoverflow.com/questions/63848248/scipy-sparse-a-0-ndarray-valueerror) may be related:
setting the first row of a scipy sparse matrix A[0,:] = np.ones() works, \
but trying to set the first column with A[:,0] = np.ones() raises a ValueError
(numpy 1.19.2   scipy 1.5.2   python 3.7.6)
