### ISSUE TITLE
Add wrapper for ?gttrf/?gttrs

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#11123]
See [NumFOCUS Small Development Grant Proposal 2019 Round 3 proposal](https://www.dropbox.com/s/i24h3j2osol56uf/Small%20Development%20Grant%20-%20LAPACK%20%20%28Condensed%29.pdf?dl=0) for background.

Add wrapper for [?gttrf](http://www.netlib.org/lapack/explore-html/d1/d40/group__double_g_tcomputational_ga8ca64e542924cec56cbe9837b77d25b7.html)/[?gttrs](http://www.netlib.org/lapack/explore-html/d1/d40/group__double_g_tcomputational_ga887f9fe1a0c6a4aeac1752da5652014a.html).
(This looks like a pretty straightforward way to start.)

Existing [wrapper](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lapack.dgtsv.html#scipy.linalg.lapack.dgtsv) for [?gtsv](https://www.netlib.org/lapack/explore-html/d4/d62/group__double_g_tsolve_ga2bf93f2ddefa5e671866eb2191dc19d4.html) provides some guidance.

Suggested signatures:
```
! dl, d, du, du2, ipiv, info  = gttrf(dl, d, du, overwrite_dl=0, overwrite_d=0, overwrite_du=0)
```
```
! x, info  = gttrs(dl, d, du, du2, ipiv, b, trans="N", overwrite_b=0)
```

Test idea:

- Generate random matrix `A`
- Decompose `A` with `?gttrf`
- Multiply factors from `?gttrf` and compare with original `A`
- Generate random solutions `x` _*Update: should test for multiple RHS*_
- Generate `b` from `A@x`
- Solve using `?gttrs`
- Compare solution from `?gttrs` against known `x`

Be sure to perform similar tests for the different `trans` options.
_Update: Also test for singular matrix._
_Update: Also test for incorrect/incompatible array sizes._

Also: implement all examples from the [NAG manual](https://www.nag.com/numeric/fl/nagdoc_latest/html/f07/f07conts.html) as additional tests.

**Comment by ilayn** [comment]
Damn. This means I need to revisit `syevr`/`heevr` stuff very soon  😅

**Comment by mdhaber** [comment]
@ilayn we'd certainly appreciate your thoughts on that, but you'll have help! I'd appreciate your thoughts on the proposed signatures and tests for these, if you have a minute. For instance, I thought about renaming the outputs of `?gttrf` (e.g. `dl` -> `ll` for the subdiagonal of the lower triangular factor) but decided against it based on the names of inputs to `?gttrf` in the LAPACK documentation.

**Comment by ilayn** [comment]
The actual variable names are not so important since they have historically very little intuitiveness hence nobody would really care but following LAPACK official docs makes it helpful for newcomers in case of finding help outside SciPy circles. 

What I mean with syevr/heevr is that currently we have an MKL `lwork` bug and our old (current) wrapper intertwined hence some backwards compatibility issues await :) (always fun).

**Comment by Kai-Striega** [comment]
Regarding the tests, could we avoid generating random matrices? Otherwise, those all look good.  
Regarding the signatures I would prefer to be consistent with the LAPACK documentation.

I've created the branch ``lapack_support_gttrf_gttrs`` to which your student may add the tests once we are happy with them.

**Comment by mdhaber** [comment]
@Kai-Striega what's wrong with (psuedo)random matrices? Of course we'd fix the seed for repeatability.

**Comment by Kai-Striega** [comment]
Random matrices test one specific case, however, to me, unit tests verify some *specific* functionality with a clear pass or fail condition. e.g. does the function handle over/underflow correctly, does it overwrite the data, does it handle invalid values as we want it to?

E.g. there was a bug in numpy-financial due to a [denormal number](https://en.wikipedia.org/wiki/Denormal_number) being passed. Could that have been caught from a random matrix? Maybe. But I would prefer to have an extra case where we know that the expected outcome occurs.

**Comment by mdhaber** [comment]
I think we agree on the philosophy of unit tests, and I can write more about this if needed, but let's first make sure our goals are the same:

- We are testing for issues specific to the signature of the f2py wrappers for `?gttrf` and `?gttrs`.
- We are not testing the f2py system itself / checking for issues that might be shared with the wrappers for other routines.
- We are not testing the LAPACK routines `?gttrf` or `?gttrs` themselves.
- This is a relatively low-level interface, so the wrapper itself doesn't guarantee nice behavior in case of input type or value errors. That would happen in a function like `scipy.linalg.lu` or similar.

So the specific functionality I am testing is that Python and Fortran are talking to one another correctly, and the clear pass criterion is whether the result is correct for a typical, rather than pathological, test case. It might be nice to see what it does with a singular matrix, too, but IMO it could still be a random singular matrix.

Do the tests already in [test_lapack.py](https://github.com/scipy/scipy/blob/master/scipy/linalg/tests/test_lapack.py) go much further than this?

**Comment by ilayn** [comment]
> Random matrices test one specific case, however, to me, unit tests verify some specific functionality with a clear pass or fail condition. e.g. does the function handle over/underflow correctly, does it overwrite the data, does it handle invalid values as we want it to?

Same applies to the other way around. Sometimes deterministic tests miss the problems that only random big/small size tests can catch say workspace size or cache segfault limitations. Best is having all but trades off with the effort goes in. Hence there is nothing essentially wrong with random matrices but if you already know some corner cases the better it is.

**Comment by mdhaber** [comment]
Thanks @ilayn. I agree with that, too, but I don't know any corner cases that are within my goals. I could probably come up with corner cases designed to test, for example, the underlying LAPACK routine, but I don't know enough about how f2py works to design corner cases for _our wrapper_.

**Comment by ilayn** [comment]
The tests should generally cover basic functionality. Does it work with correct sizes? Is the result correct? If there are extra options, say, transpose etc. do they actually work? Does it reject wrong sizes? Does it handle empty matrices? etc. etc. All should gracefully error out instead of a segfault which is the common thing when you are trying to debug a mistake somewhere. 

We don't need to test f2py or the LAPACK routine itself

**Comment by Kai-Striega** [comment]
> Do the tests already in test_lapack.py go much further than this?

There are sometimes checked e.g. test_sytrd checks that a 0x0 array raises an error.  But yes I should have checked the existing tests first. Let's match those for scope plus the edge cases @Ilyan mentioned (rejects wrong sizes, handle empty matrices etc.)

>  Sometimes deterministic tests miss the problems that only random big/small size tests can catch say workspace size or cache segfault limitations.

:+1:  I think having the deterministic tests is just a personal preference.

**Comment by Kai-Striega** [comment]
@mdhaber should the second suggested signature be for ``?gttrs`` not ``?gttrf``?

**Comment by Kai-Striega** [comment]
@mdhaber I've had an attempt at this but I'm getting a strange error I can't seem to figure out. 

```python
>>> dl = np.array([2.1, -1.0, 1.9, 8.0], dtype=double)
>>> d = np.array([3.0, 2.3, -5.0, -0.9, 7.1], dtype=double)
>>> du = np.array([3.4, 3.6, 7.0, -6.0], dtype=double)
>>> gttrf = get_lapack_funcs('gttrf', dtype=dtype)
>>> gttrf(dl, d, du)
E ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (-1,)
```
Here's what I've added for the wrapper itself, could you see if there is anything "obvious" I'm missing?

```fortran
subroutine <prefix>gttrf(n, dl, d, du, du2, ipiv, info)
    ! dl, d, du, du2, ipiv, info  = gttrf(dl, d, du)
    ! ?GTTRF computes an LU factorization of a tridiagonal matrix A
    ! using elimination with partial pivoting and row interchanges.
    !
    ! The factorization has the form
    !    A = L * U
    !
    ! where L is a product of permutation and unit lower bidiagonal
    ! matrices and U is upper triangular with nonzeros in only the main
    ! diagonal and first two superdiagonals.
    callstatement (*f2py_func)(&n, dl, d, du, du2, ipiv, &info)
    callprotoargument int*, <ctype>*, <ctype>*, <ctype>*, <ctype>*, int*, int*

    integer intent(hide),   depend(d)                 :: n = len(d)
    <ftype> intent(in,out), depend(n), dimension(n-1) :: dl
    <ftype> intent(in,out), depend(n), dimension(n)   :: d
    <ftype> intent(in,out), depend(n), dimension(n-1) :: du
    <ftype> intent(out),    depend(n), dimension(n-2) :: du2
    integer intent(out),    depend(n), dimension(n)   :: ipiv
    integer intent(out)                               :: info

end subroutine <prefix>gttrf
```

**Comment by ilayn** [comment]
`d` does not depend on `n`. It's the other way around. But in any case this will need more guards against creating negative sized arrays when n is 2 or fewer.

**Comment by Kai-Striega** [comment]
Thanks, that's got it working now! And I am planning to add the checks, but I'd prefer to have a working example first.

**Comment by mdhaber** [comment]
@Kai-Striega Does your branch `lapack_support_gttrf_gttrs` have your wrapper? It looks like it's only behind master, no commits are ahead of master. Also, I checked it out and tried:
```
gttrf = get_lapack_funcs(('gttrf',), (A[0, 0],))
```
and that failed.

**Comment by Kai-Striega** [comment]
It doesn't have anything yet - I'm waiting on the tests to be added.

**Comment by mdhaber** [comment]
Ah. OK. I think in the future we can try to write the tests before you write the wrapper. In this case, though, can you add your wrappers first since you've already written them? I would like to work on the tests with @swallan, and it would be nice to be able to check that the test is executable for this first one.

**Comment by Kai-Striega** [comment]
Sure thing. I'm on my work computer, so I can't push them right now but I'll push them when I get home tonight.

**Comment by mdhaber** [comment]
The wrapper for `?dgtsv` has options for overwriting `dl`, `d`, `du`, and `b`. I think we should add these here for consistency, and I think all it takes it to add `copy` to the intent (e.g. `(in, out, copy)`).

**Comment by Kai-Striega** [comment]
There are two ways to specify the copying behaviour `copy` and `overwrite`. These add a keyword argument `overwrite_<argument_name>` to 0 or 1 respectively. Staying consistent with gtsv would be to use `copy` i.e. do not overwrite by default.

**Comment by mdhaber** [comment]
@ilayn I updated this so that we test `?gttrs` with multiple right hand sides.

I started looking into the difference between the order and the leading dimension of an array; I see that the leading dimension of an array may be different from the order when you are looking at a slice of an array.  I also understand that it can be very important to ensure that, e.g., `lda` is nonzero (or respects whatever condition is specified in documentation) to prevent crashes.

I'm confused about how some existing functions handle these leading dimension arguments, though, so I can't figure out how to test whether it's handled properly in our new wrappers. For instance, is it important to test whether the wrapper works properly with a slice of a matrix? 

Let's look at the example of `dgesv`. I tried this:
```
import numpy as np
import scipy.linalg
dgesv = scipy.linalg.lapack.dgesv
n = 10
a_big = np.random.rand(n+2, n+2)
a = a_big[1:-1, 1:-1]
x = np.random.rand(n)
b = a @ x
print(np.allclose(dgesv(a, b)[2], x))
```
If I understand [the documentation](http://www.netlib.org/lapack/explore-html/d7/d3b/group__double_g_esolve_ga5ee879032a8365897c3ba91e3dc8d512.html) correctly, `N` should be 10 and `LDA` should be 12. The wrapper for `?gesv` doesn't seem to define `LDA` at all, yet the code works (the  output is `True`). Is f2py figuring out `LDA` automatically?

I also tried something similar with `dgesvx`, except that the last line is:
```
print(np.allclose(dgesvx(a, b)[7].flatten(), x))
```
It was actually more surprising to me that this works, because in the wrapper for `dgesvx`, `n` and `lda` are the same:
```
integer depend(a),intent(hide):: n = shape(a,0)
...
integer depend(a),intent(hide):: lda = shape(a,0)
```

Since `overwrite_a=0` by default, when the data is copied it makes the array contiguous in memory. Is that why this works out? 

If we specify `overwrite_a=1`, might this code fail, or - since `overwrite_a = 1` does not _guarantee_ that the data will be overwritten - is it safe because (perhaps?) the data will always be copied if it is a slice? (Do you know under what conditions the data will actually be overwritten?)

**Comment by ilayn** [comment]
> If I understand the documentation correctly, N should be 10 and LDA should be 12. The wrapper for ?gesv doesn't seem to define LDA at all, yet the code works (the output is True). Is f2py figuring out LDA automatically?

Not really. This is the `f2py` magic that takes in place. It converts a view or a slice into a Fortran-passable mapping format and in it goes. You don't have a way of specifying LDA or n in our wrappers. In actual Fortran usage you can address different parts of the array at a low-level and LDA defines the memory range for that array. We have high level numpy indexing functionality for that and thus pass the data directly. 

> It was actually more surprising to me that this works, because in the wrapper for dgesvx, n and lda are the same:

That's a mistake on my part. LDA should be maxed with 1. 

>If we specify overwrite_a=1, might this code fail, or - since overwrite_a = 1 does not guarantee that the data will be overwritten - is it safe because (perhaps?) the data will always be copied if it is a slice? (Do you know under what conditions the data will actually be overwritten?)

I've added a note at the top of this page for overwrite conditions http://scipy.github.io/devdocs/linalg.lapack.html#module-scipy.linalg.lapack
