### ISSUE TITLE
Use of linprog 

### ISSUE THREAD

**Issue by AvivSham** [scipy/scipy#11120]
Let's say I have the following problem:
1) objective function `c1x1 + c2x2`  (we need to minimize it)
2) ` -x1 + x2 <= 0`
3) `0 <= x1 <= 3`
4) `0 <= x2 <= 2`

We also assume that `c1 = 1` and `c2 = -0.5`.
What is the right way to use `linprog` in order to solve this problem?
is `bounds` refer to lower bounds? 

Thanks  for helping.

**Comment by ilayn** [comment]
Hi @AvivSham. We use the issue tracker for problems regarding the scipy code itself but not how you can use it. For that we point users to sources like Stackoverflow, reddit etc. where more users can help you out. 

Nevertheless have a look at the example given in the docstring http://scipy.github.io/devdocs/generated/scipy.optimize.linprog.html#scipy.optimize.linprog
