### ISSUE TITLE
ImportError: cannot import name qr_insert

### ISSUE THREAD

**Issue by cbatu1** [scipy/scipy#11137]
I attempted to run the following import statement:

```
from sklearn.utils import resample
```

However I am receiving an error message below:
#### Error message:
```
 File "/Library/Python/2.7/site-packages/scipy/sparse/linalg/isolve/_gcrotmk.py", line 10, in <module>
    from scipy.linalg import (get_blas_funcs, qr, solve, svd, qr_insert, lstsq)
ImportError: cannot import name qr_insert
```

#### Scipy/Numpy/Python version information:
```
('1.2.2', '1.16.5', sys.version_info(major=2, minor=7, micro=16, releaselevel='final', serial=0))
```

Scipy: 1.2.2
Numpy: 1.16.5
Python: 2.7.16

**Comment by ilayn** [comment]
Does it work if you just type `from scipy.linalg import (get_blas_funcs, qr, solve, svd, qr_insert, lstsq)` in the python terminal?

**Comment by cbatu1** [comment]
I just tried that and I am getting the following error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name qr_insert
```

**Comment by cbatu1** [comment]
I switched from using python 2.7 to a virtual env using python 3.7 and I was able to import `resample`. The issue could have been from the `qr_insert` module not being supported by python 2.7 but I could be mistaken.

**Comment by rgommers** [comment]
This looks like a corrupted install. `qr_insert` is a public and tested function, so not a SciPy bug here. I'll close this, thanks all.
