### ISSUE TITLE
DOC: stats.fisher_exact does not match R functionality for `oddsratio` calculation

### ISSUE THREAD

**Issue by brandondavid** [scipy/scipy#11131]
This a known issue, mentioned in [gh-1483](https://github.com/scipy/scipy/issues/1483#issuecomment-17030569) and reflected by [the docstring for `stats.fisher_exact`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fisher_exact.html):
> The calculated odds ratio is different from the one R uses. This scipy implementation returns the (more common) “unconditional Maximum Likelihood Estimate”, while R uses the “conditional Maximum Likelihood Estimate”.

But despite that documentation, this discrepancy nevertheless still causes confusion.  There is also some strong disagreement (e.g. [this conversation on CrossValidated](https://stats.stackexchange.com/questions/288641/odds-ratio-mle-calculation-unconditional-vs-conditional)) with SciPy's choice to use an "unconditional" MLE (here, the sample odds ratio) in the first place.  I am not a statistician, but my research (some rough notes [here](https://hackmd.io/AAmCAcryRWu2BKGZfc9wew)) leads me to agree.  While the sample odds ratio is arguably "more common" throughout statistics, it seems that the literature for Fisher's exact test only supports the use of CMLE.

Are there any plans to match R functionality for `fisher_exact`?  This was recently done for `hmean` with gh-10899 by adding an optional parameter.  If not, I propose to correct and expand the docstring to better explain the issue, and would welcome any expert input to help me with my understanding of the issue.

**Comment by WarrenWeckesser** [comment]
> Are there any plans to match R functionality for fisher_exact? 

We will be working on `scipy.stats` next year pretty heavily as part of a grant that we received.  Adding conditional MLE to our implementation of Fisher's exact test is on the to-do list.

Not all the details of the proposed work are spelled out in the latest version of the [detailed roadmap](https://docs.scipy.org/doc/scipy/reference/roadmap-detailed.html).  I'll try to find a good site to make public the work to be funded by the grant.

Having said that, I'll also add that improvements to the documentation are always welcome, as are enhancements such as conditional MLE by any contributors.    Our goal will be to get conditional MLE for Fisher's exact test into SciPy.  There is *plenty* of work to do, and if someone implements conditional MLE before we get to it, that just means we'll have more time to work on other issues.

**Comment by WarrenWeckesser** [comment]
>  Not all the details of the proposed work are spelled out in the latest version of the detailed roadmap. I'll try to find a good site to make public the work to be funded by the grant.

A copy of the proposal that Matt and I submitted to CZI is at https://warrenweckesser.github.io/czi/scipy-2019-czi-proposal-revised.pdf

**Comment by rgommers** [comment]
Thanks @WarrenWeckesser. I suggest to send an update with that link to the scipy-dev mailing list, I'm sure more people will be interested.

**Comment by brandondavid** [comment]
Thanks for the update!  Should I close this issue now or wait until after implementation?

**Comment by WarrenWeckesser** [comment]
@brandondavid, let's keep the issue open as an enhancement request.

**Comment by WarrenWeckesser** [comment]
I have submitted a pull request that implements the conditional MLE odds ratio: https://github.com/scipy/scipy/pull/12288

E.g. in R:
```
> table <- matrix(c(8, 2, 1, 5), nrow=2, ncol=2)
> result <- fisher.test(table)
> result$estimate
odds ratio 
  15.46969
```
With the proposed code in https://github.com/scipy/scipy/pull/12288 (which is still a work-in-progress, and subject to change):

```
In [36]: table = np.array([[8, 2], [1, 5]])

In [37]: result = fisher_exact(table)
```
The `conditional_odds_ratio` attribute is the one that matches R:
```
In [38]: result.conditional_odds_ratio
Out[38]: 15.46581971692097
```
The original odds ratio returned by `fisher_exact` is still available as the `sample_odds_ratio` attribute:
```
In [39]: result.sample_odds_ratio                                                                                                            
Out[39]: 20.0
```

**Comment by WarrenWeckesser** [comment]
The PR to add the conditional odds ratio (and its confidence interval) is ready for review: https://github.com/scipy/scipy/pull/12288
