### ISSUE TITLE
unexpected SparseEfficiencyWarning at scipy.sparse.linalg.splu

### ISSUE THREAD

**Issue by CRFEM** [scipy/scipy#11145]
Hey
I get a warning for using CSR format in splu. This is a bit 
confusing because in the documentation it a permissible format. 

"Sparse matrix to factorize. Should be in CSR or CSC format."

#### Reproducing code example:
```
from scipy.sparse import csr_matrix
from scipy.sparse.linalg import splu
A = csr_matrix(([1,1,1],([0,1,2],[0,1,2])))
splu(A)
```

#### Error message:

SparseEfficiencyWarning: splu requires CSC matrix format
warn('splu requires CSC matrix format', SparseEfficiencyWarning)

#### Scipy/Numpy/Python version information:
Python 3.6.9
Scipy 1.33

**Comment by rgommers** [comment]
Agreed, if CSC is preferred then it needs a doc update. Alternatively, the warning isn't justified and needs to be removed.
