### ISSUE TITLE
too many critical values returned in documentation examples

### ISSUE THREAD

**Issue by sam-data-guy** [scipy/scipy#11140]
This relates to documentation of the following function: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.anderson_ksamp.html (may apply to other similar functions).  The "critical_values" returned attribute should only contain 5 values.   Indeed this is how the function works.  In the documented examples, however, seven critical values are printed.  Is this from an older version of the function?  May need to be corrected elsewhere as well.

**Comment by jmmanley** [comment]
Which version of scipy are you using? (You can check by running `scipy.__version__`).

The docs are for v1.4.1. The 0.1% and 0.5% critical values were added in #8990, and I updated the docs in #10301. So you are probably just using an older version of scipy.

The source code here shows how the 7 critical values are calculated: https://github.com/scipy/scipy/blob/eab70a880439180f0bffefd7bb53c436418248ed/scipy/stats/morestats.py#L2051-L2054

**Comment by mdhaber** [comment]
Thanks @jmmanley. I confirmed that the function returns 7 critical values in recent SciPy, so the documentation seems correct. @sam-data-guy thanks for looking out for this sort of thing. If you notice anything else, please let us know.
