### ISSUE TITLE
renaming function argument from grad to jac

### ISSUE THREAD

**Issue by Karrenbelt** [scipy/scipy#11141]
for the sake of consistency with the other optimisers it would be good if the argument for the gradient in _minimize_trustregion_constr would be called 'jac' instead of 'grad'

**Comment by andyfaff** [comment]
It'd say it's 50:50 here. It's in a private function, so it shouldn't matter if it's renamed. But then again I'm not 100% that it's worth the churn. @Karrenbelt would you be interested in making a PR?

**Comment by andyfaff** [comment]
Actually, I think there would be issues renaming it to jac because that's also used for the jacobian of the constraints. I'd say it's better to leave it as is.

**Comment by andyfaff** [comment]
Won't fix, in a private function.
