### ISSUE TITLE
Nelder-Mead: replace loop

### ISSUE THREAD

**Issue by nschloe** [scipy/scipy#11149]
In Nelder-Mead https://github.com/scipy/scipy/blob/master/scipy/optimize/optimize.py#L586, one finds for the evaluation of the goal functional
```python
for k in range(N + 1):
    fsim[k] = func(sim[k])
```
Why do we loop here? Something like
```
fsim[:] = func(sim)
```
would give the user the opportunity to vectorize the computation in `func`.

**Comment by pv** [comment]
Because API is that the user-provided function is not necessarily
vectorized, and that cannot be changed at this point.

One could envision adding support for vectorized optimizer function
calls, but that is a longer road, and it is not clear it would be worth
it.

**Comment by nschloe** [comment]
>  and that cannot be changed at this point.

You're probably right. Let's close this.
