### ISSUE TITLE
Enable LGTM for code analysis (Semmle)

### ISSUE THREAD

**Issue by XVilka** [scipy/scipy#11153]
Will help to eliminate obvious errors. For SciPy it is good that Python and C/C++ are supported. See:
- https://lgtm.com/
- https://github.com/marketplace/lgtm

NumPy, for example, uses it already: https://github.com/numpy/numpy/pull/15024#partial-pull-merging

![image](https://user-images.githubusercontent.com/203261/69871982-2f673c80-12ef-11ea-85bd-ff273782cf90.png)

**Comment by tupui** [comment]
If this is just for the CI part and not for the bot writing comments, why not. But I prefer classic tools like pep8 or opinionated ones like blake.

**Comment by rgommers** [comment]
I'm going to close this, since we have no need for this and would prefer to not have more CI jobs. Thanks for the suggestion though @XVilka
