### ISSUE TITLE
 Comparisons between scipy spmatrix and can sparse.SparseArray return scalar bool

### ISSUE THREAD

**Issue by ivirshup** [scipy/scipy#11163]
This issue is about interop with scipy sparse and pydata sparse. `scipy.sparse` doesn't let `pydata/sparse` overload `__eq__` according to https://github.com/pydata/sparse/issues/305#issuecomment-560317183 (I'm still a little fuzzy on when `__array_priority__` and `__array_ufunc__` get used). This ends up returning a scalar for `!=` or `==`.

#### Reproducing code example:

```python
In [1]: import sparse                                                                               
sra 
In [2]: import scipy                                                                                

In [3]: scipy.__version__                                                                           
Out[3]: '1.5.0.dev0+5958e9f'

In [4]: coo = sparse.random((10, 10))                                                               

In [5]: csr = coo.tocsr()                                                                           

In [6]: csr == coo                                                                                  
Out[6]: False
```

I'd expected this to broadcast and not be False, especially since interop seems to be a goal (#10901).

**Comment by hameerabbasi** [comment]
If someone can tell me where `scipy.sparse.spmatrix.__eq__` and so on are defined, I can try to make this change.

**Comment by pv** [comment]
I don't remember outright where it is, but I guess grep should point you to about the right place. The spmatrix comparisons are probably quite old code, and might not follow sane convention.

**Comment by ivirshup** [comment]
It looks like it's effectively under `sparse/compressed.py

https://github.com/scipy/scipy/blob/2ba80dc11ffe931495ec054070e601ae3d8edd03/scipy/sparse/base.py#L369-L373

https://github.com/scipy/scipy/blob/2ba80dc11ffe931495ec054070e601ae3d8edd03/scipy/sparse/compressed.py#L217

**Comment by hameerabbasi** [comment]
Looks like it's specialized to each format, which isn't surprising. I'll try to figure this out, but I might not get to it too soon.

**Comment by ivirshup** [comment]
I think I've got something working. It's not particularly elegant though.
