### ISSUE TITLE
MAINT: dealing with NumPy pre-release test failures

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#11172]
As you can see in Travis CI for recent PRs ( https://travis-ci.org/scipy/scipy/jobs/620455062?utm_medium=notification&utm_source=github_status ) we now get hundreds of test failures related to
NumPy deprecating the automatic creation of object arrays, with:

 `DeprecationWarning: Creating an ndarray with automatic object dtype is deprecated, use dtype=object if you intended it, otherwise specify an exact dtype`

While I was never a fan of the protections that enables vs. the disruption, I suspect we'll need a way to handle this gracefully moving forward. This is also making my life harder for `1.4.0` as noted in #11161.

See also: https://github.com/numpy/numpy/issues/15047

**Comment by pv** [comment]
For 1.4.0 probably add here https://github.com/scipy/scipy/blob/master/pytest.ini#L4
`once:Creating an ndarray with automatic object dtype.*:DeprecationWarning`

**Comment by rgommers** [comment]
Already reverted in numpy 1.18.x, and should be temporarily reverted in numpy master as well.

**Comment by rgommers** [comment]
So no need to filter for now, we have some time to investigate and fix up the cases where we didn't expect to see object arrays.

**Comment by mattip** [comment]
xref gh-11147 which will fix some of the warnings

**Comment by QuLogic** [comment]
These deprecations are back again for NumPy 1.19.

**Comment by tylerjereddy** [comment]
I'm pretty sure this has long since been dealt with. For example, trying to create a jagged array implicitly in our testsuite fails because of NumPy error, so we'd probably detect if any cases were left over at this point:

```diff
--- a/scipy/signal/tests/test_ltisys.py
+++ b/scipy/signal/tests/test_ltisys.py
@@ -352,7 +352,7 @@ class TestSS2TF:
         assert_allclose(num, [[0, 1], [2, 3]], rtol=1e-13)
         assert_allclose(den, [1, 6], rtol=1e-13)
 
-        tf = (np.array([[1, -3], [1, 2, 3]], dtype=object), [1, 6, 5])
+        tf = (np.array([[1, -3], [1, 2, 3]]), [1, 6, 5])
         A, B, C, D = tf2ss(*tf)
         assert_allclose(A, [[-6, -5], [1, 0]], rtol=1e-13)
         assert_allclose(B, [[1], [0]], rtol=1e-13)
```

so, closing
