### ISSUE TITLE
DOC: https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.qr.html

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#11178]
The docs say: "overwrite_a bool, optional. Whether data in a is overwritten (may improve performance)".

But it does not say whether the improved performance is for **overwrite_a=True** or **overwrite_a=False**!

**Comment by rgommers** [comment]
`False` is the default, `True` _may_ give improved performance by reusing an existing data structure (the input), rather than creating a new one.

**Comment by gaurav-1205** [comment]
I have updated in the decomp_qr file and committed. This was my first open source contribution. Please let me know if there is any issue.

**Comment by rgommers** [comment]
@gaurav-1205 you will need to open a pull request for us to see your change. I don't see one from you.
