### ISSUE TITLE
TST,  CI: Azure coverage issues

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#11174]
Probably low-priority, but if only a bookmark for myself... Azure coverage results are starting to look quite unreliable, with many `test_.py` modules showing extremely low % coverage (most test modules should be pretty close to full coverage).

Looking at a recent PR to master ~5 hours ago ( https://github.com/scipy/scipy/pull/11171 ), I see in the Azure logs output like:

```
============================== warnings summary ===============================
C:\hostedtoolcache\windows\Python\3.7.5\x64\lib\site-packages\_pytest\junitxml.py:436
  C:\hostedtoolcache\windows\Python\3.7.5\x64\lib\site-packages\_pytest\junitxml.py:436: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
  Add 'junit_family=legacy' to your pytest.ini file to silence this warning and make your suite compatible.
    _issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, config.hook, 2)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
------- generated xml file: D:\a\1\s\build\test\junit\test-results.xml --------

----------- coverage: platform win32, python 3.7.5-final-0 -----------
Coverage HTML written to dir htmlcov
Coverage XML written to file coverage.xml
```

and also:

```
Coverage.py warning: --include is ignored because --source is set (include-ignored)
Coverage.py warning: Module scipy was previously imported, but not measured (module-not-measured)
Coverage.py warning: No data was collected. (no-data-collected)
```

I think some of those have always been there, but others may be new/more problematic. Anyway, it is painful to debug and we don't rely on it too too much these days, but I do like having access to it, so good to fix eventually.

**Comment by rgommers** [comment]
@tylerjereddy can we close this?

**Comment by tylerjereddy** [comment]
Yeah, I think we're planning to get rid of Azure soon-ish, and I may have been the only actual consumer of the Azure-specific coverage stuff anyway.
