### ISSUE TITLE
DOC: twine upload hiccups

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#11189]
Hiccup I've never seen before while uploading wheels, for example:

`twine upload -s /mnt/c/Users/treddy/github_projects/scipy/release/installers/*.whl`

Runs into the issue described here: https://github.com/pypa/setuptools/issues/941

Circumvented by creating a `~/.pypirc` file as described therein, but I don't like that solution long-term because it stores credentials in plain text. This was observed on a WSL machine. Anyway, for now I'll just reset the credentials after I do a release, but long-term let's try to document/address, probably just by keeping an eye on upstream fixes/changes.

It looks like things are slowly changing with the PyPI infrastructure/pypa stuff too.

**Comment by charris** [comment]
Worked for the NumPy 1.18.0rc1 release, although the first attempt failed. I figured it was probably a faulty password...

**Comment by charris** [comment]
What version of Python/twine? I did need to reinstall twine after my system upgrade and was on Python 3.7.5 and twine 3.1.1.

**Comment by tylerjereddy** [comment]
Python `3.7.4` & and twine `2.0.0` according to `python -m pip list`. Maybe I need to upgrade `twine`? I suppose error messages on version mismatch/incompatibility issues might be optimistic.

**Comment by charris** [comment]
Is `python` 2.7 or 3.7 on your system? `python` was just switched to point to 3.7 in fedora 31, and that distro is more cutting edge than most.

**Comment by tylerjereddy** [comment]
I work in a virtualenv pointing to a `spack`-installed python `3.7`.

**Comment by rgommers** [comment]
No more issues in recent releases, `setuptools` issue referred to is closed. So let's close this too.
