### ISSUE TITLE
Return of pmf unclear

### ISSUE THREAD

**Issue by Mark531** [scipy/scipy#11183]
Hello,

I'm really confused with the way scipy works. In this simple example, I build a multinomial random variable with 1 trial and 3 possible outcomes per trial, each outcome being associated with a probability. If I now call pmf on this random variable on every possible outcome, I expect it to return the probability associated with each of them (hence my initial probability vector):

```
from scipy.stats import multinomial
rv = multinomial(n=1, p=[0.3, 0.2, 0.5])
rv.pmf([0, 1, 2])
```
But I get 0... What does that mean?

Mark

**Comment by pv** [comment]
This does not seem like a bug, so e.g. stackoverflow may be better place to ask.

It's a multivariate distribution. The probability that you draw `n=1` marbles from a box, and obtain 0 red marbles, 1 green marble, and 2 blue marbles, is zero.

**Comment by Mark531** [comment]
Mmm, at a minimum, you should improve the documentation. The documentation of pmf (https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_discrete.pmf.html#scipy.stats.rv_discrete.pmf) says that the first parameter is a list of quantiles, which is quite unusual for a probability mass function.

**Comment by WarrenWeckesser** [comment]
@Mark531, the link in your last comment is to the `pmf` method of `rv_discrete`, but the original issue is about `multinomial`.  When `n=1` is used, `multinomial` is, in effect, a different representation of a univariate discrete distribution.  The wikipedia article on the [multinomial distribution](https://en.wikipedia.org/wiki/Multinomial_distribution) calls this special case the [categorical distribution](https://en.wikipedia.org/wiki/Categorical_distribution).  `multinomial` with `n=1` is still multivariate, so its quantiles are 1-d arrays of length three (assuming `len(p) == 3`, as in your original example).  In effect, by using `multinomial` to represent your discrete distribution, you are using the "one hot" encoding as the quantiles.  The support (i.e. the quantiles where the probability is nonzero) for your multinomial example is {[1, 0, 0], [0, 1, 0], [0, 0, 1]}.   *Those* are the values that you would have to pass to `multinomial.pmf` to see the nonzero probabilities:

```
In [63]: from scipy.stats import multinomial

In [64]: rv = multinomial(n=1, p=[0.3, 0.2, 0.5])

In [65]: rv.pmf([1, 0, 0]) # Evaluate the PMF at *one* quantile.
Out[65]: 0.3

In [66]: rv.pmf([[1, 0, 0], [0, 1, 0], [0, 0, 1]])  # Evaluate the PMF at three quantiles.
Out[66]: array([0.3, 0.2, 0.5])
``` 

If you want the univariate discrete distribution, you can use `rv_discrete`:

```
In [70]: from scipy.stats import rv_discrete

In [71]: rv1 = rv_discrete(values=([0, 1, 2], [0.3, 0.2, 0.5]))

In [72]: rv1.pmf(0)
Out[72]: 0.3

In [73]: rv1.pmf([0, 1, 2])
Out[73]: array([0.3, 0.2, 0.5])
```

**Comment by Mark531** [comment]
@WarrenWeckesser Thanks for this precise answer, that's very appreciated. I suggest you to add the examples given to the documentation of scipy.stats.multinomial.
