### ISSUE TITLE
The .roots() or solve() function of scipy.interpolate.CubicHermiteSpline object is empty

### ISSUE THREAD

**Issue by mm-crj** [scipy/scipy#11185]
I am using Python 3.7 to write a program that requires me to calculate the root of the Hermite interpolating polynomial, given two points ϵ0
, ϵ1, the function (d(ϵ0),d(ϵ1)) and the derivative values (d′(ϵ1), d′(ϵ1)) at those points. I am using Scipy v1.3.0 and using the CubicHermiteSpline function from the scipy.interpolate library. The relevant extracts from the code are: 
#### Reproducing code example:

```
import numpy as np
from scipy.interpolate import BPoly,CubicHermiteSpline

#somewhere below inside a while loop with a counter variable k is this part

eps=np.array([0.001, 0.002])
l=np.array([1.66066935e-06, 1.10410807e-06])
d1=np.array([-1.60061854, -1.600619])

r=CubicHermiteSpline(eps[k-1:k+1],abs(l[k-1:k+1]), d1[k-1:k+1]).roots()
epsk=(np.abs(r - eps[k])).argmin()
```

#### Error message:

Now r is just
```
array([], dtype=float64)
```
although I have checked it has a root at 0.03053802. 
Some more info can be found at [StackExchange](https://scicomp.stackexchange.com/questions/33047/get-the-roots-of-a-hermite-interpolating-polynomial)

**Comment by pv** [comment]
I don't see any problem:
```
>>> CubicHermiteSpline(eps,l, d1).roots()
array([0.00100104, 0.00149827])
```

**Comment by pv** [comment]
Ok, you seem to be meaning that `extrapolate=True` is does not give the third root.
```
>>> CubicHermiteSpline(eps, l, d1).roots(extrapolate=True)
array([0.00100104, 0.00149827])
```

**Comment by ev-br** [comment]
Fixed by gh-11218, closing

**Comment by mm-crj** [comment]
> Ok, you seem to be meaning that `extrapolate=True` is does not give the third root.
> 
> ```
> >>> CubicHermiteSpline(eps, l, d1).roots(extrapolate=True)
> array([0.00100104, 0.00149827])
> ```

Yes this is true that it is not finding all the roots, but I was referring to another problem. Try this code:

```
import numpy as np
from scipy.interpolate import BPoly,CubicHermiteSpline

eps=np.array([0.5, 0.6 , 1.46868271])
l=np.array([5.21802150e-01+0.j, 4.68936311e-01+0.j, 1.09555951e-04+0.j])
d1=np.array([-0.52756352, -0.52975923, -0.67731627])
k=1

r=CubicHermiteSpline(eps[k-1:k+1],np.absolute(l[k-1:k+1]), d1[k-1:k+1]).roots()
print(r)
```
I am getting r as 
```
array([], dtype=float64)
```

**Comment by pv** [comment]
That has the same cause, and was also fixed.
