### ISSUE TITLE
BUG: stats: pearson3 CDF and SF functions incorrect when skew < 0.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#11186]
The `cdf` and `sf` methods of the distribution `pearson3` in `scipy.stats` give incorrect results when the shape parameter `skew` is negative.  For example,

```
In [253]: import scipy                                                                                                                                    

In [254]: scipy.__version__                                                                                                                               
Out[254]: '1.5.0.dev0+5421b30'

In [255]: from scipy.stats import pearson3                                                                                                                

In [256]: x = np.linspace(-2, 1.5, 5)                                                                                                                     
```

The following are obviously wrong, because the CDF should be an *increasing* function of x, and the survival function should be a *decreasing* function of x.  The following results show the opposite behavior for these two methods:

```
In [257]: pearson3.cdf(x, -0.5)                                                                                                                           
Out[257]: array([0.96559991, 0.86772622, 0.62854634, 0.2822072 , 0.0487404 ])

In [258]: pearson3.sf(x, -0.5)                                                                                                                            
Out[258]: array([0.03440009, 0.13227378, 0.37145366, 0.7177928 , 0.9512596 ])
```
This issue was first reported in a [stackoverflow question](https://stackoverflow.com/questions/59193566/cdf-in-scipy-pearson3-appears-to-be-miss-defined).

**Comment by chrisb83** [comment]
I am still confused about the implementation of pearson3, see #9168. It might be a special case of the generalized gamma ( Wikipedia +  https://link.springer.com/chapter/10.1007/978-94-017-1431-0_14).

**Comment by WarrenWeckesser** [comment]
>  I am still confused about the implementation of pearson3, ...

Heh, me too.  I haven't tried to decipher the implementation in SciPy, and I probably won't be able to spend time looking into the code in the immediate future.  I added a comment over in #9168 with some code showing that `pearson3` is just a reparameterized `gamma`.

**Comment by mdhaber** [comment]
I think the absolute value in the PDF screws up the relationship between `pearson3` and `gamma` for negative skew. But since negating the skew reflects the pdf about `x=0`:
`pearson3.cdf(x, -abs(skew)) = pearson3.sf(-x, abs(skew))`
And the right-hand side can be evaluated using the SF of `gamma` without any issues because the skew is positive.
