### ISSUE TITLE
Scipy integration inaccuracies with partially used domain

### ISSUE THREAD

**Issue by fkmart** [scipy/scipy#11197]
I noticed a particular error with some integration routines in scipy.integrate that leave some glaring problems with simple test cases with an analytically determinable solution. I'm nearing the end of my PhD and don't want to start changing Python installs but I'm using version 3.6.3 and scipy version 1.0.0 in VS Code. 

The following code produces erroneous results using both Simpson's and Romberg routines: 

`import numpy as np 
import scipy.integrate as spint 
import matplotlib.pyplot as plt

lx = 65
x = np.linspace(0.0, 64, lx)
y = np.zeros(lx)
y[0:17] = x[0:17]**2

I_simps = spint.simps(y,x,dx = x[1] - x[0])
I_romb = spint.romb(y,dx = x[1] - x[0])`

The analytical result is 1365.333 but Simpson and Romberg return 1450.666 and 1443.311 respectively which is significantly off the true result. There's a physics-based problem I'm using this for which is why the domain is only partially filled but this is necessary step and the source of the issue as I've performed the same result with only the relevant part of the domain and achieved acceptable accuracy. I've also shown a plot of y as defined above to illustrate the issue a little more clearly. I'm surprised a series of 0s in the sampled function is causing such trouble. Can anyone confirm this result in these Python and Scipy versions or provide a solution? 

I'm not against upgrading scipy in VS Code (I added the directory to my path variable yesterday but it seems VS Code needs a personal solution to get pip/conda working) but I'd rather change as little as possible. 
![scipy_error_pic](https://user-images.githubusercontent.com/48246829/70509322-d38a8800-1b26-11ea-8cda-a2c528b0fcd5.png)

**Comment by WarrenWeckesser** [comment]
There is no need to upgrade SciPy; the latest version will give the same answers.  I think you are expecting more accuracy from these numerical methods than is possible with the number of samples that you are using.

You say the theoretical value is 1365.333 (i.e. 4096/3).  That is the integral from 0 to 16 of x².  But look closely at the plot of your data.  In particular, zoom in on the interval 15 <= x <= 18, as in this plot:

![Figure_1](https://user-images.githubusercontent.com/321463/70513578-ea69b400-1aff-11ea-883b-d7c76233dd34.png)

Note that big triangle above the interval [16, 17].  That is not included in the exact integral.  The trapezoidal rule applied to that interval gives an area of 128.  That value plus the theoretically exact value on the interval [0, 16] gives a total of 1493.33.  The rules applied by `simps` and `romb` are more accurate than that, but given the coarseness of your sampling, the fact that they overestimate the theoretical value is not surprising.  If you need a more accurate result, use a finer grid, or some other method that is specific to your problem.

**Comment by fkmart** [comment]
I tested it with twice the resolution and the result improved as you might expect. I'm a little surprised I didn't catch that myself! I can see now how this might have been affecting some of my experimental results, not just this particular test case. Thank you
