### ISSUE TITLE
Batched linear programs

### ISSUE THREAD

**Issue by carlosgmartin** [scipy/scipy#11195]
**Is your feature request related to a problem? Please describe.**

Solving multiple linear programs requires calling [`scipy.optimize.linprog`](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.optimize.linprog.html) for each linear program separately and then combining the outputs. It is much slower to solve multiple linear programs separately than to solve them simultaneously (see papers below). This problem is especially prominent when the number of linear programs to be solved is large, but each individual linear program is small.

**Describe the solution you'd like**

Extend [`scipy.optimize.linprog`](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.optimize.linprog.html) to support batched inputs. For truly batched linear program solving, two relevant papers are

- [*Solving Batched Linear Programs on GPU and Multicore CPU*](https://arxiv.org/abs/1609.08114) (Sep 2016) by Amit Gurung, Rajarshi Ray.

- [*Two-dimensional batch linear programming on the GPU*](https://arxiv.org/abs/1902.04995) (April 2019) by John Charlton, Steve Maddock, Paul Richmond.

**Describe alternatives you've considered**

The slow alternative is flattening the inputs along the batch dimensions, `map`ping `linprog` over the flattened axis, and reshaping the outputs. Like any Python loop, `map` is slow for large arrays, so even handling this part of the problem at the lower-level would be an improvement.

**Comment by mdhaber** [comment]
Thanks @carlosgmartin. I added this idea to gh-9269. As you can see, there is quite a bit on this list. Is this something you'd be able to help with?

**Comment by carlosgmartin** [comment]
@mdhaber I'll take a look and see if there's something I can do.

**Comment by mdhaber** [comment]
Hey @carlosgmartin what do you think? Were you interested in helping with this? Also, thought you might be interested in gh-11759; we're adding support for the [HiGHS solvers](https://www.maths.ed.ac.uk/hall/HiGHS/).

**Comment by mdhaber** [comment]
This is tracked in gh-9269, so I don't think we need to keep this open anymore. Whether it is implemented really depends on HiGHS upstream.

**Comment by mdhaber** [comment]
I closed gh-9269, but I don't think this needs to be tracked in SciPy anymore. Consider adding a feature request to [HiGHS](https://github.com/ERGO-Code/HiGHS), and if it is added, perhaps we can wrap it.
