### ISSUE TITLE
sparse eigs (arpack) shift-invert drops the smallest eigenvalue for some k

### ISSUE THREAD

**Issue by denis-bz** [scipy/scipy#11198]
scipy.sparse.linalg.eigs shift-invert mode for the SM, smallest-magnitude eigenvalue
`( A=sparse.rand(), k=k, which='LM', sigma=0 )`
drops the smallest one for some k:

    k 1 shift: [ 17 +0j ]
    k 2 shift: [ 17 +0j   52 +0j ]
    k 3 shift: [ 52 +0j   -23 -47j   -23 +47j ]
    k 4 shift: [ 17 +0j   52 +0j   -23 -47j   -23 +47j ]
    k 5 shift: [ 17 +0j   52 +0j   -23 -47j   -23 +47j   71 +0j ]
    k 6 shift: [ 17 +0j   52 +0j   -23 -47j   -23 +47j   71 +0j   -1e+02 +0j ]
    k 7 shift: [ 52 +0j   -23 -47j   -23 +47j   71 +0j   -1e+02 +0j   1e+02 -36j   1e+02 +36j ]

It's hard to believe that this is an ARPACK bug; what else could be wrong ?

Versions: numpy 1.17.4  scipy 1.3.3   python 3.7.3   macos 10.10.5  
3581068 24 Nov 18:25 .../libopenblasp-r0.3.7.dev.dylib  
669500 24 Nov 18:25 .../_arpack.cpython-37m-darwin.so

Notes:
The sometimes-missing smallest eigenvalue from `sparse.rand` with various n, density, seed is, so far, real.
I take `v0=ones`, not random -- this should be the default.
The nice scipy arpack tutorial says "which = 'SM' may lead to slow execution time and/or anomalous results". That's too weak --in fact SM often fails on many `sparse.rand` matrices.

#### Reproducing code example:

    #!/usr/bin/env python
    """ test scipy.sparse.linalg.eigs LM shift-invert: some k drop the smallest real eigenvalue ? """
    # https://docs.scipy.org/doc/scipy/reference/tutorial/arpack.html  X.XT symmetric, easy
    #       which = 'SM' may lead to slow execution time and/or anomalous results
    # https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigs.html
    # denis 10 Dec 2019

    from __future__ import division, print_function
    import sys
    import numpy as np
    import scipy
    from scipy import sparse
    from scipy.sparse.linalg import eigs, ArpackError, ArpackNoConvergence
    try:
        import scikits.umfpack  # eigs -> splu spsolve ?
        print( "umfpack:", scikits.umfpack.__version__ )
    except ImportError:
        pass

    def randomsparse( n, density=0.1, seed=0 ):
        """ -> n x n scipy.sparse.rand csc, uniform -1 .. 1 """
        random = np.random.RandomState( seed=seed )
        A = sparse.rand( n, n, density, format="csc", random_state=random )  # uniform 0 .. 1
            # if distrib:
        A.data *= 2
        A.data -= 1
        print( "randomsparse: n %d  density %.2g  seed %d  A %.2g .. %.2g  nnz %d " % (
                n, density, seed, A.data.min(), A.data.max(), A.nnz ))
        return A

    def zsort( z ):
        """ sort z abs increasing, then imag """
        jsort = np.lexsort( [np.imag(z), np.abs(z)] )
        return z[jsort]

    np.set_printoptions( threshold=20, edgeitems=10, linewidth=140,
            formatter = dict( float = lambda x: "%.2g" % x,  # float arrays %.2g
                            complexfloat = " {0.real:.2g} {0.imag:+.2g}j " .format ))
    print( "\n" + 80 * "=" )
    print( "versions: numpy %s  scipy %s   python %s " % (
            np.__version__, scipy.__version__ , sys.version.split()[0] ))

    #...............................................................................
        # gen --
    gen = randomsparse
    n = 10
    density = .5
    seed = 0  # some -> LinAlgWarning singular, lu_factor
    dense = True  # test arpack dense first

        # eigs --
    kmax = 8
    sigma = 0
    tol = 0  # 0: machine precision, eps ?
    v0 = 1  # None: random, 1: ones
    SM = False

        # to change these params, run this.py  a=1  b=None  'c = expr' ... in sh or ipython --
    for arg in sys.argv[1:]:
        exec( arg )

    genparams = "%s  n %d  density %.2g  seed %d  dense %s " % (
            gen.__name__, n, density, seed, dense )
    eigsparams = "sigma %s  tol %g  v0 %s  SM %d " % (
            sigma, tol, v0, SM )
    print( "gen params:", genparams )
    print( "eigs params:", eigsparams )

    kmax = min( kmax, n - 2 )
    if v0 is not None:
        v0 = np.ones( n )

    #...............................................................................
        # generate a test matrix A --
        # may be singular for some seeds: arpack.py sometimes calls lu_factor, SM doesn't
    A = randomsparse( n, density=density, seed=seed )
    A *= 100
    if dense:  # test arpack dense first
        A = A.A

    #...............................................................................
    print( "\n# scipy.sparse.linalg.eigs (arpack) shift-invert vs. SM" )
    for k in range( 1, kmax+1 ):
        evals = eigs( A, k=k, which='LM', sigma=0, v0=v0, maxiter=None, tol=tol,
                    return_eigenvectors=False )
            # eigs(A, k=6, M=None, sigma=None, which='LM', v0=None, maxiter=None, tol=0,
            #   return_eigenvectors=True, Minv=None, OPinv=None, OPpart=None)
        print( "k %d shift: %s" % (k, zsort( evals )))

    if SM:
      for k in range( 1, kmax+1 ):
        try:
            evals = eigs( A, k=k, which='SM', v0=v0, maxiter=None, tol=tol,
                        return_eigenvectors=False )
            print( "k %d SM: %s" % (k, zsort( evals )[0] ))
        except (ArpackError, ArpackNoConvergence) as msg:
            print( "k %d SM: %s" % (k, msg) )

**Comment by denis-bz** [comment]
@tylerjereddy,
  yes, that checks for missing eigenvalues, good.
The above can also check SM, could you please try it in Ipython or shell --

    run eigstest.py SM=True n=30
    
k 1 SM: ARPACK error -1: No convergence ...

(The 2 lines in any test.py

    # default params ...
        # to change these params, run this.py  a=1  b=None  'c = expr' ... in sh or ipython --
    for arg in sys.argv[1:]:
        exec( arg )

make it easy to run with other params
or in a shell: `for n in 1 2 3; do python test.py n=$n`

**Comment by pv** [comment]
The changes in that PR don't affect SM convergence issues --- that's an ARPACK bug/problem afaics.

**Comment by denis-bz** [comment]
@pv, shall I file a new issue for SM ?
Running eigs on 100 x 100 density 0.1 sparse.rand matrices with seeds 0 .. 100,
essentially the above: SM never converges, shift-invert always --
 
    versions: numpy 1.17.4  scipy 1.3.3   python 3.7.3 

    -- n 100  density 0.1  seed 0:
    randomsparse: n 100  density 0.1  seed 0  A -1 .. 1  nnz 1000 
    shift-invert |eval|: [4.69 16.6 20 28.7 28.7 29.8 42.3 42.3 47.5 47.5]
    ARPACK error -1: No convergence (1001 iterations, 6/10 eigenvectors converged)

    -- n 100  density 0.1  seed 1:
    randomsparse: n 100  density 0.1  seed 1  A -1 .. 1  nnz 1000 
    shift-invert |eval|: [23.2 26.3 30.8 30.8 39.1 39.1 41.4 41.4 41.7 41.7]
    ARPACK error -1: No convergence (1001 iterations, 2/10 eigenvectors converged)

    -- n 100  density 0.1  seed 2:
    randomsparse: n 100  density 0.1  seed 2  A -1 .. 1  nnz 1000 
    shift-invert |eval|: [54.4 50.8 50.8 42.6 42.6 35 27.1 14.6 9.64 3.18]
    ARPACK error -1: No convergence (1001 iterations, 2/10 eigenvectors converged)

    -- n 100  density 0.1  seed 3:
    randomsparse: n 100  density 0.1  seed 3  A -1 .. 1  nnz 1000 
    shift-invert |eval|: [25 36.5 36.5 37.2 40.8 40.8 46.1 46.1 55.9 55.9]
    ARPACK error -1: No convergence (1001 iterations, 0/10 eigenvectors converged) [ARPACK error -14: DNAUPD  did not find any eigenvalues to sufficient accuracy.]
    ...

**Comment by pv** [comment]
New issue would be clearer. The convergence could also be precision-related issue --- you are asking it to compute down to machine precision.
