### ISSUE TITLE
Scipy.sparse.csgraph has no atribute reduce_cython

### ISSUE THREAD

**Issue by wallacez1** [scipy/scipy#11203]
Im bulding a tkinter app who is working fine, but when i try to run the executable version builded with cx_freeze, i get the following line

Error: **AtrributeError:Type object 'scipy.sparse.csgraphy' has no attribute 'reduce_cython'**

#### Error message:

![image](https://user-images.githubusercontent.com/37086969/70651711-16845280-1c30-11ea-857a-7f3b14a370a0.png)

Python Version: 3.7.3
Scipy: 1.3.2
Cython: 0.29.13

**Comment by perimosocordiae** [comment]
Looks similar to https://github.com/cython/cython/issues/1953, and likely not an issue with scipy itself. You may want to check if the installed scipy version in your site-packages was built with an older Cython verison (see https://github.com/cython/cython/issues/1953#issuecomment-398128940).

**Comment by wallacez1** [comment]
> Looks similar to [cython/cython#1953](https://github.com/cython/cython/issues/1953), and likely not an issue with scipy itself. You may want to check if the installed scipy version in your site-packages was built with an older Cython verison (see [cython/cython#1953 (comment)](https://github.com/cython/cython/issues/1953#issuecomment-398128940)).

following the traceback the problem start with the importk of nltk and then with scipy library but nltk doesnt have any information about cython version.

**Comment by rgommers** [comment]
This was an issue in Cython that has long since been fixed, so closing.
