### ISSUE TITLE
LSMR and LSQR strange performance for square matrices

### ISSUE THREAD

**Issue by lorentzenchr** [scipy/scipy#11204]
The iterative solvers for least squares, `scipy.sparse.linalg.lsqr` and `scipy.sparse.linalg.lsmr`, have a strange timing behaviour around square matrices (n, n), see peaks in plot below. It would be nice to know whether this is known (intended) behaviour or whether it could be improved (of whether I did something wrong).

#### Reproducing code example:
```python
from collections import OrderedDict
from functools import partial

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy
import scipy.sparse as sp
import scipy.sparse.linalg as sla
import seaborn as sns
import neurtu

plt.ion()

def bench_cases():
    p_list = [10, 100, 500, 1000]
    rng = np.random.RandomState(42)
    X = rng.randn(max(p_list) ** 2 * 2)
    y = rng.randn(max(p_list) * 2)
    for p in p_list:
        for n in np.arange(0.1, 2.1, 0.1):
            n = int(p*n)
            A = X[:n*p].reshape(n, p)
            b = y[:n]
            for solver in ['la.lstsq', 'spa.lsmr', 'spa.lsqr']:
                tags = OrderedDict(n=n, p=p, solver=solver)
                if solver == 'la.lstsq':
                    solve = neurtu.delayed(la.lstsq, tags=tags)
                elif solver == 'spa.lsmr':
                    solve = neurtu.delayed(
                        partial(sla.lsmr, atol=1e-10, btol=1e-10, maxiter=1e6),
                        tags=tags)
                if solver == 'spa.lsqr':
                    solve = neurtu.delayed(
                        partial(sla.lsqr, atol=1e-10, btol=1e-10, iter_lim=1e6),
                        tags=tags)

                yield solve(A, b)

bench = neurtu.Benchmark(wall_time=True)
df = bench(bench_cases())

g = sns.relplot(x='n', y='wall_time', hue='solver', col='p', col_wrap=2,
            kind='line', ci=None, facet_kws={'sharex': False, 'sharey': False},
            data=df.reset_index(), marker='o')
g.set_titles("{col_name} features")
g.set_axis_labels("samples", "Wall time (s)")
g.set(xscale="linear", yscale="log")

plt.subplots_adjust(top=0.95)
g.fig.suptitle('Benchmark LSMR, LSQR, LSTSQ')
g.fig.subplots_adjust(hspace=.2)
for ax in g.axes.flatten():
    ax.tick_params(labelbottom=True)
```

#### Benchmark plot:
![bench_lsmr](https://user-images.githubusercontent.com/15324633/70658132-a5f42a80-1c5d-11ea-9b4d-65de2f6c2ba9.png)
Produced on an Intel Core i7.

#### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
```
```
1.3.1 1.17.2 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)
```

**Comment by bnaul** [comment]
A bit late but I would say this peaking of runtime around n=p is not surprising. The covariance matrix of X is on average most ill-conditioned right at n=p: for both n>>p and n<<p the non-zero eigenvalues are likely to be close together, whereas at n=p you're more or less guaranteed to have 1 large and 1 very very small value. I don't have a reference for the condition number per se but the basic idea follows more or less immediately from the Marcenko-Pastur distribution https://en.wikipedia.org/wiki/Marchenko%E2%80%93Pastur_distribution.

Definitely an interesting phenomenon but not a SciPy issue IMO 🙂

**Comment by pv** [comment]
Thanks for looking at it, indeed seems to be a property of the test case picked.

**Comment by lorentzenchr** [comment]
@bnaul Thank you very much for your valuable insights!

For the interested reader: I get `(0.00013, 2036)` as smallest and largest eigenvlues of `A.T @ A`  for  n=p=500. And `(83.76, 2864)` for n=1000, p=500.

**Comment by lorentzenchr** [comment]
@bnaul I though I let you know that you inspired me to write a blog post about the Marchenko-Pastur distribution where you are mentioned. I hope that's fine.
https://lorentzen.ch/index.php/2022/05/22/from-least-squares-benchmarks-to-the-marchenko-pastur-distribution/
