### ISSUE TITLE
ConvexHull area is confusing

### ISSUE THREAD

**Issue by mccarthyryanc** [scipy/scipy#11217]
The area attribute for a convexhull is incorrect:

```python
from scipy.spatial import ConvexHull
points = np.array([[0,0],[1,0],[1,1],[0,1]]) # 1x1 square
hull = ConvexHull(points)
```

`hull.area` is equal to 4.0 instead of 1.0. Looks like it is returning the perimeter of the hull instead of the area.

#### Scipy/Numpy/Python version information:
```
1.3.1 1.17.2 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
The result is correct. The terminology here is dimension-independent, so "area" of the hull of a point set in d dimensions means the volume of the d-1 dimensional hull. In 3D it is area, in 2D perimeter.

**Comment by WarrenWeckesser** [comment]
For example, in 3D, the `area` attribute gives the expected value:

```
In [7]: points3d = np.array([ 
   ...:     [0, 0, 0], 
   ...:     [0, 0, 1], 
   ...:     [0, 1, 0], 
   ...:     [0, 1, 1],  
   ...:     [1, 0, 0], 
   ...:     [1, 0, 1], 
   ...:     [1, 1, 0], 
   ...:     [1, 1, 1]])

In [8]: hull3d = ConvexHull(points3d)

In [9]: print(hull3d.area)
6.0
```

**Comment by mccarthyryanc** [comment]
@pv Thanks for the clarification! This makes perfect sense now that I see the hull has both `area` and `volume` attributes.
