### ISSUE TITLE
linprog: interior-point: Cholmod reordering can be reused

### ISSUE THREAD

**Issue by hakeemo** [scipy/scipy#11216]
In the MOSEK paper, it states that the matrix M  has a fixed nonzero pattern throughout the solution. 
Scikit-sparse's interface to Cholmod can create a Factor object which stores the reordering information. .   From my tests on some large problems (> 1e6 variables), I am getting a 2-3X speedup by storing this reordering. I would be willing to implement this.

 A similar strategy can be used for the scikit-umfpack solver through the low-level interface.

**Comment by mdhaber** [comment]
This sounds great! I'd be happy to review the PR.
