### ISSUE TITLE
confidence interval of the `scipy.optim.minimize` results

### ISSUE THREAD

**Issue by eunjongkim** [scipy/scipy#11233]
Hi,

I've been trying to implement a least-squares fit using 'Nelder-Mead' method for minimizing the residual. The minimization works well. But the thing is, I don't have any idea of how to extract the variance and confidence interval for the parameters optimized. The OptimizeResult of this minimization gives a variable called `final_simplex`, which takes the form of (array_like of shape (N + 1, N), and array_like of shape(N+1, )) which I don't have a good idea to use.

Any idea about this? This would be very helpful.

Best,
Eunjong

**Comment by eunjongkim** [comment]
I found that I can use the version in 
https://github.com/andsor/notebooks/blob/master/src/nelder-mead.md
to do what I want. But, I don't understand why the scipy version is implemented this way? Would there be a specific reason?

**Comment by andyfaff** [comment]
I think there are probably more accurate ways of estimating parameter uncertainties than fitting a quadratic surface around the minimum. It would be a general benefit to `optimize` if there was a method for estimating parameter uncertainties for a generalised `f`/`x` system.

**Comment by andyfaff** [comment]
The uncertainty calculation as written is also not generic to any problem size, and will increase the number of function evaluations. It may be worth emailing the scipy-dev mailing list to see if there is general appetite for the error estimation as outlined in the paper.

**Comment by josef-pkt** [comment]
I don't know of a generic way of defining and estimating uncertainties in parameters that would work for general optimization problems.
All cases I know, are in the specific context of a statistical optimization problem, like least squares, maximum likelihood or M-estimators.

What's the uncertainty in `argmin(x**2)` ?

(aside: in statsmodels we use the inverse Hessian of the optimization problem for MLE which we compute separately and not during optimization with scipy optimizers.)

**Comment by andyfaff** [comment]
Going to close the issue here as there is no specific problem with scipy, but no "generic way of estimating uncertainties in parameters that work for general optimization problems" (as opposed to statistical optimisation problems").
