### ISSUE TITLE
Missleading Error Message for IIR Filter

### ISSUE THREAD

**Issue by AKuederle** [scipy/scipy#11235]
When using `scipy.singal.iirfilter` (or any other related filter design method), it is possible to trigger the error `Digital filter critical frequencies must be 0 < Wn < 1`:

```python
from scipy.signal import iirfilter
iirfilter(2, Wn=5, btype='low')
```
This error message is correct and helpful in the default case, but when the newish `fs` parameter is used, the error message is misleading/wrong:

```python
from scipy.signal import iirfilter
iirfilter(2, Wn=600, fs=1000, btype='low')   # Error message
iirfilter(2, Wn=300, fs=1000, btype='low')   # No Error message
```

This error message is generated in [this line](https://github.com/scipy/scipy/blob/b3a2071ce3952748c5e98ef7328d2b8eab77b2dc/scipy/signal/filter_design.py#L2346):
```py
if not analog:
    if numpy.any(Wn <= 0) or numpy.any(Wn >= 1):
        raise ValueError("Digital filter critical frequencies "
                                   "must be 0 < Wn < 1")
```

I would suggest to change it to:
```py
if not analog:
    if numpy.any(Wn <= 0) or numpy.any(Wn >= 1):
        if fs is not None:
            raise ValueError("Digital filter critical frequencies "
                                       "must be 0 < Wn < fs/2 (fs={})".format(fs))
        raise ValueError("Digital filter critical frequencies "
                           "must be 0 < Wn < 1")
```

If this is ok, I would start a pull request with this change

**Comment by ilayn** [comment]
This was indeed on my todo list then I forgot. Please go ahead @AKuederle. Thanks for raising the issue.

**Comment by AKuederle** [comment]
I opened a pull request. If you have time, please have a look
