### ISSUE TITLE
Unable to compile scipy 1.4 

### ISSUE THREAD

**Issue by winash12** [scipy/scipy#11241]
I am unable to compile scipy 1.4 on Ubuntu 18.04 LTS with python3.6 and I tried both with python3.6 -m pip install . and python3.6 setup.py install,

I want to point out that I have installed pybind11 as recently as today and that still does not resolve the issue. Where am I going wrong ? This has never happened before.

`creating /tmp/tmpespaluwr/tmp
creating /tmp/tmpespaluwr/tmp/tmpespaluwr
compile options: '-I/usr/include/python3.6m -c'
extra options: '-std=c++14 -fvisibility=hidden'
x86_64-linux-gnu-g++: /tmp/tmpespaluwr/main.c
C compiler: x86_64-linux-gnu-g++ -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC

creating /tmp/tmpnxdut7p6/tmp
creating /tmp/tmpnxdut7p6/tmp/tmpnxdut7p6
compile options: '-I/usr/include/python3.6m -c'
x86_64-linux-gnu-g++: /tmp/tmpnxdut7p6/main.c
building 'scipy.fft._pocketfft.pypocketfft' extension
compiling C++ sources
C compiler: x86_64-linux-gnu-g++ -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC

compile options: '-DPOCKETFFT_PTHREADS -I/root/.local/include/python3.6m -I/usr/local/include/python3.6 -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/include/python3.6m -c'
extra options: '-std=c++14 -fvisibility=hidden'
x86_64-linux-gnu-g++: scipy/fft/_pocketfft/pypocketfft.cxx
scipy/fft/_pocketfft/pypocketfft.cxx:15:10: fatal error: pybind11/pybind11.h: No such file or directory
 #include <pybind11/pybind11.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Running from scipy source directory.
/usr/local/lib/python3.6/dist-packages/numpy/distutils/system_info.py:782: UserWarning: Specified path /usr/local/include/python3.6m is invalid.
  return self.get_paths(self.section, key)
error: Command "x86_64-linux-gnu-g++ -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPOCKETFFT_PTHREADS -I/root/.local/include/python3.6m -I/usr/local/include/python3.6 -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/usr/include/python3.6m -c scipy/fft/_pocketfft/pypocketfft.cxx -o build/temp.linux-x86_64-3.6/scipy/fft/_pocketfft/pypocketfft.o -MMD -MF build/temp.linux-x86_64-3.6/scipy/fft/_pocketfft/pypocketfft.o.d -std=c++14 -fvisibility=hidden" failed with exit status 1 `

**Comment by andyfaff** [comment]
Are you sure that you have `pybind11` installed? Confusingly there is a `pybind` package out there that isn't the right one.

**Comment by winash12** [comment]
@andyfaff I never had to install pybind11 before and I never had a problem installing scipy before. My last successful install was scipy 1.3 but with 1.4 I am facing this issue. I went here https://pypi.org/project/pybind11/#files and downloaded that gz file and installed it using pip.

**Comment by andyfaff** [comment]
pybind11 is a new dependency for building scipy. From that error message it looks like it's not being picked up during the build. Do you have pybind11 in the same Python venv/environment as you're building scipy in?

**Comment by winash12** [comment]
@andyfaff Yes it is all in the same environment. I do not have venv. I am just putting all my egg files under /usr/local/lib/python3.6/dist-packages. Now I am running this on Ubuntu 18.04 LTS and I never installed pybind11 before today. I am unaware of any other installation.

**Comment by winash12** [comment]
So when I run **python3.6 -m site | grep pybind11** this is the only result I get

`'/usr/local/lib/python3.6/dist-packages/pybind11-2.4.3-py3.6.egg',`

**Comment by peterbell10** [comment]
>`-I/root/.local/include/python3.6m`

Is it possible you installed to your home directory and then run the build as root? You will probably find that `pybind11` isn't installed is any of these places:
```sh
ls /root/.local/include/python3.6m | grep pybind11
ls /usr/include/python3.6m | grep pybind11
```
But what about your home directory?
```sh
ls ~/.local/include/python3.6m | grep pybind11
```

**Comment by winash12** [comment]
@peterbell10 

I have a directory libPython under my home directory(/home/winash12) in which I unzipped the pybind11 file and then I did a pip install.

All of the greps you mention return null.

**Comment by peterbell10** [comment]
Could you figure out where the headers did get installed?

**Comment by winash12** [comment]
@peterbell10 You got that right. 
Right now the header files are not getting installed when I do` pip install pybindd11`

**Comment by ilayn** [comment]
just stating the obvious but do you need to write pip3 instead?

**Comment by winash12** [comment]
@ilayn I do it as` python3.6 -m pip install .`

**Comment by ilayn** [comment]
OK. Could you not do `python3.6 -m pip install pybind11 --user` ?

**Comment by winash12** [comment]
@ilayn I am confused as to how to install pybind11. 

According to this doc - https://buildmedia.readthedocs.org/media/pdf/pybind11/master/pybind11.pdf

I need to run cmake but that does not seem to work either. I think I will close this issue and raise an error on the pybind11 site.

**Comment by gaurs21** [comment]
Hi, We are facing same issue while installing scipy 1.4. We are using python 3.7. Can you please suggest if you were able to solve this issue? We have an off-line environment and using following command to install scipy:
python/3.7/bin/python3 setup.py install

Thanks,

**Comment by camelator** [comment]
Same issue here. Tring to build a jupyterlab docker image with scientist packages for ARM64. python package of scipy are not available for ARM and compilation fails.

**Comment by rgommers** [comment]
@camelator the original issue here was about Ubuntu, better not to mix a question about ARM64 into it. Right now there are no ARM64 wheels, however conda-forge has SciPy `aarch64` and many other PyData packages - I recommend using Miniforge installer + conda packages.

**Comment by camelator** [comment]
@rgommers many thanks for for really fast answer,
and sorry for my bad french english.
Please, I don't understand, how can it be a Ubuntu issue if I am trying to compile scipy by myself?
Do you have any links related to this issue?
Maybe I can use another linux image?

many thanks for your answer

**Comment by rgommers** [comment]
I mean the original bug here said `I am unable to compile scipy 1.4 on Ubuntu 18.04 LTS `. You have a different issue.

Here is an ARM64 installer: https://github.com/conda-forge/miniforge. And a Docker image at https://github.com/conda-forge/docker-images/pull/129 if you need it. Then you can simply `conda install scipy`.
