### ISSUE TITLE
Is it possible to make custom 2d probability density function?

### ISSUE THREAD

**Issue by SosUts** [scipy/scipy#11242]
I want to make custom 2d probability density function(e.g. gamma-vonmises distribution).
 ```scipy.stats.rv_continuous``` seems to support 1d pdf.
Is there any alternative to make 2d pdf?

Thank you in advance.

```
class 1d_pdf(stats.rv_continuous):
# a, b, c is the hyper-parameters of this distribution
    def _pdf(self, x, a, b, c):
        return mypdf 
    def _argcheck(self, a, b, c): 
        return argcheck
1d_pdf = 1d_pdf(name="1d_pdf")

pdf = 1d_pdf(a=1, b=1, c=1) # no error
```

However, custom 2d pdf will raise error.
```
# a, b, c is the hyper-parameters of this distribution
class 2d_pdf(stats.rv_continuous):
    def _pdf(self, x, y, a, b, c):
        return mypdf 
    def _argcheck(self, a, b, c): 
        return argcheck
2d_pdf = 2d_pdf(name="2d_pdf")

pdf = 2d_pdf(a=1, b=1, c=1)
```
returns,
```python
_parse_args() missing 1 required positional argument: 'y'
```
↑Maybe y is recognized as hyper parameter.

**Comment by ev-br** [comment]
stats.distributions framework only supports univariate distributions. Multivariate distributions you'll need to code yourself, similar to https://github.com/scipy/scipy/blob/master/scipy/stats/_multivariate.py
