### ISSUE TITLE
kendalltau: exact method is wrong for samples >= 171

### ISSUE THREAD

**Issue by chrisb83** [scipy/scipy#11246]
My issue is about ...

#### Reproducing code example:

Code in kendalltau in see stats.py returns pvalue of 0 if sample size is >= 171 (this was introduced as a fix in #10056):

```
if xtie == 0 and ytie == 0 and method == 'exact':
        # Exact p-value, see Maurice G. Kendall, "Rank Correlation Methods" (4th Edition), Charles Griffin & Co., 1970.
        c = min(dis, tot-dis)
        if size <= 0:
            raise ValueError
        elif c < 0 or 2*c > size*(size-1):
            raise ValueError
        elif size == 1:
            pvalue = 1.0
        elif size == 2:
            pvalue = 1.0
        elif c == 0:
            pvalue = 2.0/math.factorial(size) if size < 171 else 0.0
        elif c == 1:
            pvalue = 2.0/math.factorial(size-1) if (size-1) < 171 else 0.0
        else:
            new = [0.0]*(c+1)
            new[0] = 1.0
            new[1] = 1.0
            for j in range(3,size+1):
                old = new[:]
                for k in range(1,min(j,c+1)):
                    new[k] += new[k-1]
                for k in range(j,c+1):
                    new[k] += new[k-1] - old[k-j]
            pvalue = 2.0*sum(new)/math.factorial(size) if size < 171 else 0.0
```

However, the p-value should follow a uniform distribution under the null hypothesis.

#### Error message:

None

#### Scipy/Numpy/Python version information:

Scipy >= 1.3.0

**Comment by sturlamolden** [comment]
Clearly this is a bug/defect. For sample sizes 171 or lager, the p-value thus has the discrete sample space {0.0, 1.0} with the exact method, but as noted, it should be uniformly distributed on the interval (0, 1]. I understand it is done to prevent numerical instability, but it introduces a bug. The correct solution would be to raise an exception (e.g. FloatingPointError) for sample sizes 171 or larger, when the exact method is numerically unstable. 

That being said, as a Bayesian zealot I do not care much for p-values anyway.

**Comment by mdhaber** [comment]
I will take care of this in gh-9361

**Comment by chrisb83** [comment]
There is already a PR to fix this in #11563

**Comment by mdhaber** [comment]
Hah apparently I knew that last week. I've been a bit scattered...

**Comment by mdhaber** [comment]
Closed by gh-11563
