### ISSUE TITLE
diff_step in least_squares does absolute step while docs say relative step

### ISSUE THREAD

**Issue by mbakker7** [scipy/scipy#11258]
The `least_squares` method of `scipy.optimize` has a keyword argument `diff_step`, which allows the user to define the relative step size to be used in computing the numerical Jacobian. The doc strings says: The actual step is computed as ``x * diff_step``. But it, unfortunately, doesn't. It takes an absolute step. In example below the initial parameters are 1000 and 0.01. The `diff_step` is 1e-4, so the Jacobian should be computed with three parameter sets: (1000, 0.01), (1000.1, 0.01), and (1000, 0.010001). But it doesn't do a relative step, it simply adds 1e-4. 

#### Reproducing code example:
```
xobs = np.array([0, 1, 2, 3])
yobs = np.array([0.1, 1005, 1993, 3015])

def residuals(p, xobs=xobs, yobs=yobs):
    print(p)
    return yobs - (p[0] * xobs + p[1])

popt = so.least_squares(residuals, [1000, 0.01], diff_step=1e-4, 
        max_nfev=1)  # just 1 step to show the problem
```

Output (which is incorrect):
```
[1.e+03 1.e-02]
[1.0001e+03 1.0000e-02]
[1.00e+03 1.01e-02]
```

#### Scipy/Numpy/Python version information:
```
1.4.1 1.17.2 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
```

**Comment by andyfaff** [comment]
The finite difference is done here: https://github.com/scipy/scipy/blob/e291b10ec85378cf87afea03befb8a69d16e7ad6/scipy/optimize/_numdiff.py#L210. If the parameter is less than one then the step is calculated slightly differently. Perhaps the documentation could up updated slightly.

**Comment by mbakker7** [comment]
Thanks. That explains it. Not sure if that is desirable (at least not for my problem).
Turns out `diff_step` can also be an array, so you can trick the problem by specifying different values if you know the approximate parameter values. The following code does what I want to do (at least for the initial parameters)
```
popt = so.least_squares(residuals, [1000, 0.01], diff_step=[1e-4, 1e-6], max_nfev=1)
```
Output:
```
[1.e+03 1.e-02]
[1.0001e+03 1.0000e-02]
[1.0000e+03 1.0001e-02]
```

**Comment by mbakker7** [comment]
And in case the doc string gets updated. The description of `max_nfev` isn't quite accurate either. `max_nfev=1` does 1 iteration in the least_squares optimization, which for the case with 2 parameters and a 2-point Jacobian, equals 3 function evaluations. So something like

```Maximum number of iterations in the least_squares optimization before termination```.

No big deal probably, but may as well get it right.

**Comment by andyfaff** [comment]
I think that behaviour is chosen to balance formula and truncation errors. If X got really small should one still have a rel step?

**Comment by andyfaff** [comment]
When tracking function evaluations it's always going to be difficult to limit to the exact amount because of the problem you've just described. However the number of iterations and the number of function evaluations are two different things.

**Comment by mbakker7** [comment]
`rel_step * sign(x0) * max(1, abs(x0))` is not useful if the optimal value of x0 is small. 
My optimal value is around 1e-4, so `least_squares` can not compute a reasonable numerical derivative. I suggest to change the computation of the numerical derivative and/or make it an option not to do the multiplication with `max(1, abs(x0))` but just with `abs(x0)`

**Comment by mbakker7** [comment]
I understand that the number of iterations is different from the number of function evaluations.
As far as I can see, the maximum number of function evaluations is now used to set the maximum number of iterations. So I propose to change the doc string (although the name of the keyword argument would be a bit confusing).

**Comment by andyfaff** [comment]
The existing behaviour makes sure that the finite difference absolute step is scaled correctly for the default situation where no `rel_step` is specified, which is `sqrt(EPS) * np.abs(x0)` for `x0 >=1`, for 2-sided FD.  When `x0 < 1` then an absolute step of ~ `sqrt(EPS)` should be used because otherwise the step size is too small and runs into floating point issues.

The [absolute step size calculation](https://github.com/scipy/scipy/blob/master/scipy/optimize/_numdiff.py#L99) could possibly be changed to:

```
def _compute_absolute_step(rel_step, x0, method):
    sign_x0 = (x0 >= 0).astype(float) * 2 - 1
    if rel_step is None:
        rel_step = relative_step[method]
        abs_step = rel_step * sign_x0 * np.maximum(1.0, np.abs(x0))
    else:
        abs_step = rel_step * sign_x0
    return abs_step
```
which would ensure that the user-specified rel_step size was used.

**Comment by mbakker7** [comment]
I think you forgot the `np.abs(x0)` term. After the `else` it should be
```
        abs_step = rel_step * sign_x0 * np.abs(x0)
```  
This would surely help cases where the optimal value is small, for example, like my case, where it is between 1e-3 and 1e-5. 

Question: Why not simply `sign_x0 = np.sign(x0)`? Only diff I can see is if `x0=0`.

**Comment by andyfaff** [comment]
You're correct about my suggested change. From memory the calculation of `sign_x0` is necessary, but I cant immediately remember why. That could do with a comment.

**Comment by andyfaff** [comment]
> Why not simply sign_x0 = np.sign(x0)? Only diff I can see is if x0=0.

Thinking about it more, I think we want `sign_x0` to be 1 when `x0 == 0`, not 0.

**Comment by mbakker7** [comment]
Yeah, `np.sign(x0)` returns zero when `x0` is exactly zero. A corner case. 
I guess I am not quite sure why the sign needs to be determined at all, as the derivative is approximated as (f(x+ delta_x) - f(x)) / delta_x, where delta_x is a positive increment. I would think that abs_step must always be positive.
Thanks for your help and time.

**Comment by mbakker7** [comment]
Can this suggestion be included in the current development branch?
