### ISSUE TITLE
Sparse matrix constructor data type detection changes on Numpy 1.18.0

### ISSUE THREAD

**Issue by pv** [scipy/scipy#11266]
There is some change in Numpy 1.18.0 with regard to integer data type selection. (This is currently causing refguide-check failures on master.)

On Numpy 1.18.0 we get
```
>>> scipy.sparse.csc_matrix(np.array([[1]])).dtype.type
<class 'numpy.longlong'>
>>> scipy.sparse.csc_matrix(np.array([[0]])).dtype.type
<class 'numpy.int64'>
```
whereas on 1.17.4 both result to `<class 'numpy.int64'>`. The integer type sizes are the same (`sizeof(long long) == sizeof(npy_int64)`), so this is some subtlety about which one gets picked by the csc_matrix constructor. Interestingly, `np.array()` picks always the `numpy.int64` one, so this might more probably be issue in scipy.sparse.

**Comment by ananyashreyjain** [comment]
The upcast function which is there to avoid overflows is converting it from `numpy.int64` to`numpy.long.long` .
https://github.com/scipy/scipy/blob/76da841e41090c77f682afd77a951da455abed91/scipy/sparse/coo.py#L364

**Comment by ananyashreyjain** [comment]
On Numpy 1.18.0 `scipy.sparse.sputils.upcast()`  converts `numpy.int64` to `numpy.longlong` which is different from what happens in Numpy 1.17.4 where no conversion takes place.
