### ISSUE TITLE
Hermitian Eigenvalue Problem eigh() API and wrapper change proposal

### ISSUE THREAD

**Issue by ilayn** [scipy/scipy#11262]
Executive summary:  Current wrappers and `eigh`, `eigvalsh` routines lack the full functionality that underlying LAPACK routines capable of. Also [`scipy.linalg.eigh`](https://scipy.github.io/devdocs/generated/scipy.linalg.eigh.html) and [`scipy.linalg.eigvalsh`](https://scipy.github.io/devdocs/generated/scipy.linalg.eigvalsh.html) show its age a lot. In this issue and the related PR we would like to introduce the missing functionality and touch the API in a backwards incompatible way (as little as possible).

<hr> 

Related Issues : #11279, #9212, #8205, #8713, #6510, #6666, #1686,

The symmetric/hermitian eigenvalue problems in Scipy are solved via calling the underlying LAPACK routines, [`syevr`](http://www.netlib.org/lapack/explore-html/d2/d8a/group__double_s_yeigen_gaeed8a131adf56eaa2a9e5b1e0cce5718.html#gaeed8a131adf56eaa2a9e5b1e0cce5718), [`heevr`](http://www.netlib.org/lapack/explore-html/df/d9a/group__complex16_h_eeigen_ga60dd605c63d7183a4c289a4ab3df6df6.html#ga60dd605c63d7183a4c289a4ab3df6df6). The current functions return the full eigenvalue and if desired the full eigenvalue set. However, these routines also offer way more powerful functionalities such as return all eigenvalues between `(a, b]` and their eigenvectors if asked (currently not offered), or, return only the 2nd to 6th eigenvalues (currently offered via `eigh`). Main motivation for these choices are given [here](https://github.com/scipy/scipy/issues/6502#issuecomment-241437506) and we have actually went completely the other way and we expose all wrappers as much as possible. 

-  Unfortunately the sought-after interval computations are not only not available through the public API but also removed from the wrappers.

- `lwork` and `liwork` computations are also hidden from the user (and from us) hence it works with the absolute minimum workspace allocations hindering performance.

- On the API side, even the current functionalities are not exposed in a coherent way due to historical reasons. Moreover, our API to these functions involve keywords that are not up-to-par e.g. eigvals actually describe the latter mth to nth eigs functionality that is not informative and share the same name with `eigvals_only` keyword.  `turbo` keyword is simply unnecessary and a quirk compared to the rest. `type` is acceptable but ideally would have been named differently

- The `eigvalsh` sounds like a bypass to eigenvector computation but unfortunately the eigenvectors are always computed and discarded at the function exit. The turbo keyword overrides the interval and enumerated eigenvalue calls.

- The problem types are not uniformly handled there are keyword combinations that lead to corner-cases where the results is confusing to say the least. Because some features are not available to all types. 

Since these parts of the linalg library are used extensively, we have to thread lightly before introducing any major changes. Hence the following are the challanges.

1. The wrappers have to be modified from the current signature

        w,z,info = <s,d>syevr(a,[jobz,range,uplo,il,iu,lwork,overwrite_a])
        w,z,info = <c,z>heevr(a,[jobz,range,uplo,il,iu,lwork,overwrite_a])

    to the following 
    
         w,z,isuppz,info = <s,d>syevr(a,[jobz,range,uplo,vl,vu,il,iu,,abstol,lwork,liwork,overwrite_a])
         w,z,isuppz,info = <c,z>heevr(a,[jobz,range,uplo,vl,vu,il,iu,,abstol,lwork,liwork,lrwork,overwrite_a])

    notice the increase in `?work` variable declaration. Decision to make; do we monkeypatch existing wrappers for name clash avoidance or simply include in a backwards-incompatible way? 

2. The public API needs some changes. I am not sure how to go about this. We can leave this to a later time but once the wrappers are touched the `eigh` has to be touched to accommodate these changes anyhow. The main functionality addition is returning interval (or cluster) eigvals w/o eigvectors.

3. `turbo`, `type` keywords should have been a single `driver` keyword that points the user to different routines just like elsewhere in `scipy.linalg`. And conflicting choices should be obvious errors and not silent choices.

I already prepared the wrappers and will open a PR but a bit hesitant if this dies at the decision state. Hence I'll wait a bit to see what folks are thinking about it.

Mailing list is also informed.

**Comment by mdhaber** [comment]
1. 
> do we monkeypatch existing wrappers for name clash avoidance or simply include in a backwards-incompatible way?

I don't understand what the name clash is? Existing code that passes an `lwork` can go to `lwork` in the updated wrappers, right? And anyone wanting to take advantage of the updates can add `liwork` and `lrwork`.

1b. Is there no optimal `lwork` size that can be computed by the routine? 

3. I don't have a strong opinion about this, but if we want to maintain backwards compatibility we could leave `turbo`, `type` and indicate in the documentation that they are superseded by `driver`. Incompatible choices that may be used in existing code could be warnings, and explicit, incompatible choices involving new options could be errors?

**Comment by ilayn** [comment]
If we don't rewrap under the original name we will have two versions of `..evr` routines together with their lworks. If we wrap them with the same name we have to do decide on whether we try to accomodate for old behavior or not. See the extra parameters `vu, vl` in the signature.

> 3. I don't have a strong opinion about this, [...]

I think deprecating them will save us quite the headache later in the SciPy 2.0. There is a similar one waiting for decision in #8715. In my opinion, these haphazard keywords make these functions not-so-professional for the newcomers since they are central to linear algebra routines.

I'll send the PR as soon as I have time.

**Comment by mdhaber** [comment]
I see. I think we should rewrap under the original name. 
Deprecating those keyworks is fine with me. I was just suggesting a way around, but I agree that deprecating will save us the trouble of maintaining a past mistake.
