### ISSUE TITLE
Problem with finding eigenvectors of large matrices in Python's Scipy

### ISSUE THREAD

**Issue by QuestionPy** [scipy/scipy#11273]
I am working with Python and try to compute all eigenvectors of huge (20.000x20.000 and bigger) real symmetric matrices with scipy.sparse.linalg.eigsh (for sparse matrices). This works good for matrices up to 20.000 columns and rows. But for bigger matrices the entries of the calculated eigenvectors are all zero.

What is the problem here with python and how do I fix it without decreasing the number of eigenvectors which can be calculated?

**Comment by mdhaber** [comment]
@QuestionPy did you find a problem with your code? Is this not a SciPy issue?

**Comment by QuestionPy** [comment]
@mdhaber I am not sure anymore if it is a scipy problem or just a memory problem of my computer so I deleted my code and question.

**Comment by mdhaber** [comment]
@QuestionPy, if you're unsure, it would be great if you could leave your question do someone can try to reproduce it. That would help us know for sure.

**Comment by QuestionPy** [comment]
@mdhaber I reopened the question :)

**Comment by mdhaber** [comment]
I tried this test:
```
n = 25000
p = 0.001
A = scipy.sparse.random(n, n, density = p, format='csc', dtype=np.float64)
A = A + A.T
e, v = scipy.sparse.linalg.eigsh(A, k = 1)
print(v.T @ v)
```
You said:
> But for bigger matrices the entries of the calculated eigenvectors are all zero.

But for this first eigenvector, at least, the norm is 1. 

It does sound like you're interested in computing _all_ eigenvectors, so maybe you mean that all eigenvectors after the first "few" are zero? How should I modify the line:
```
e, v = scipy.sparse.linalg.eigsh(A, k = 1)
```
If I set `k=n`:
```
C:\Users\matth\Miniconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py:1572: RuntimeWarning: k >= N for N * N square matrix. Attempting to use scipy.linalg.eigh instead.
  RuntimeWarning)
Traceback (most recent call last):

  File "<ipython-input-21-997b2aad15dd>", line 1, in <module>
    e, v = scipy.sparse.linalg.eigsh(A, k = n)

  File "C:\Users\matth\Miniconda3\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 1575, in eigsh
    raise TypeError("Cannot use scipy.linalg.eigh for sparse A with "

TypeError: Cannot use scipy.linalg.eigh for sparse A with k >= N. Use scipy.linalg.eigh(A.toarray()) or reduce k.
```

**Comment by QuestionPy** [comment]
@mdhaber I am trying to calculate as many eigenvectors as possible.
So set

'''Python
e, v = scipy.sparse.linalg.eigsh(A, k= n-2)
'''

And I meant that all the computed eigenvectors are zero. If i set k=n-2.

**Comment by mdhaber** [comment]
So it only happens when `k` is large, too. Ok, I'll try when there is CPU time to spare. I think this will take a while as ARPACK is not really designed to find so many eigenvalues.

**Comment by QuestionPy** [comment]
Do you know if there is another way to compute that many eigenvectors, since  ARPACK is not designed for it?

For```n=20000``` the problem occurs the first time. So you could decrease ```n``` a little bit.
I noticed, by converting float64 to float32, Python is calculating all ```k=n-2``` correct eigenvectors.
I just changed your example to:
```A = scipy.sparse.random(n, n, density = p, format='csc', dtype=np.float32)```

**Comment by mdhaber** [comment]
I just checked this for `n=20001`, `dtype=np.float64`, `k = n-2` and the `v` returned seems reasonable; they are certainly not all zero.

**Comment by mdhaber** [comment]
@QuestionPy are you still concerned with this? I was not able to reproduce the problem.

**Comment by mdhaber** [comment]
@WarrenWeckesser if you have a minute to punch in:
```
import scipy.sparse
import numpy as np
n = 20001
p = 0.001
A = scipy.sparse.random(n, n, density = p, format='csc', dtype=np.float64)
A = A + A.T
e, v = scipy.sparse.linalg.eigsh(A, k= n-2)
assert(np.allclose(v.T @ v, np.eye(n-2)))
```
I'd appreciate it. If it runs successfully, I think this can be closed.

**Comment by WarrenWeckesser** [comment]
@mdhaber, how long is "a fair bit longer"?  That call to `eigsh` is still running after almost 2 hours.

**Comment by mdhaber** [comment]
Oops, maybe too long. Go ahead and abort if it's a problem. But I did it once before and it did finish eventually : ) Or, if you think it's OK to just test on one machine, then we're already done and we can close.

**Comment by mdhaber** [comment]
Just tested this again; no problem. @QuestionPy please open this again if you are able to reproduce it on another machine.
