### ISSUE TITLE
linalg.eigh checks whole array for finite values

### ISSUE THREAD

**Issue by h-larsson** [scipy/scipy#11279]
Hi,

As specified in the documentation, linalg.eigh(A) uses data only on the lower (upper) part of A. It does not check whether A actually is symmetric and the upper (lower) part of A can contain any data. However, check_finite seems to check the whole array of A, even though only the lower (upper) part actually is used for computation: 

```
scipy.linalg.eigh( [ [1,np.nan], [0,1] ] , lower=True , check_finite=True)   
```
leads to 

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-26-e4b5babe597f> in <module>
----> 1 scipy.linalg.eigh( [ [1,np.nan], [0,1] ] , lower=True , check_finite=True)

scipy/linalg/decomp.py in eigh(a, b, lower, eigvals_only, overwrite_a, overwrite_b, turbo, eigvals, type, check_finite)
    372 
    373     """
--> 374     a1 = _asarray_validated(a, check_finite=check_finite)
    375     if len(a1.shape) != 2 or a1.shape[0] != a1.shape[1]:
    376         raise ValueError('expected square matrix')

scipy/_lib/_util.py in _asarray_validated(a, check_finite, sparse_ok, objects_ok, mask_ok, as_inexact)
    237             raise ValueError('masked arrays are not supported')
    238     toarray = np.asarray_chkfinite if check_finite else np.asarray
--> 239     a = toarray(a)
    240     if not objects_ok:
    241         if a.dtype is np.dtype('O'):

numpy/lib/function_base.py in asarray_chkfinite(a, dtype, order)
    496     if a.dtype.char in typecodes['AllFloat'] and not np.isfinite(a).all():
    497         raise ValueError(
--> 498             "array must not contain infs or NaNs")
    499     return a
    500 

ValueError: array must not contain infs or NaNs
```

Since eigh, as emphasized in the documentation, only uses the lower (upper) part of A and does not even checks for symmetry in A, it does not make sense to me that the check_finite flag checks the other, unused part of A. 

With the current behavior, initializing A as uninitialized matrix (numpy.empty) and only writing on the appropriate lower (upper) part of A leads to "random" ValueErrors, depending on whether a part in memory is interpreted as inf or nan. 
Example:
```
A = numpy.empty( (2,2) )           
A[numpty.tril_indices_from(A)] = 1
scipy.linalg.eigh(A)
```
*May* work or may raise a ValueError, depending on the unused value A[0,1].

#### Scipy/Numpy/Python version information:

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
```
--> 1.3.1 1.16.4 sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)

**Comment by ilayn** [comment]
Hi @h-larsson . Thanks for the issue. It is indeed as you have written up. 

One thing to remark is that finiteness check is too cheap compared to the actual computation hence `n` or `2n` lookup complexity won't even make a dent compared to .

That brings us only using the good part of a freshly initialized part. If you have already the data then probably you can do a simple replacement `A[~np.isfinite] = ...`. Otherwise if your data is known to have no problems then you can turn the check off.

**Comment by h-larsson** [comment]
Hi @ilayn 
thanks for your remarks. I understand that the check is very cheep. My issue is more about consistency. If only one half of A is used, I don't understand why the whole A is checked. Also, the exception is hard to debug as a code using np.empty (or using A as provided by some third-party library) will work most of the time and crash only occasionally. 
Maybe, this could be documented? There is already a note in https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.eigh.html  that A is not checked for symmetry.

**Comment by ilayn** [comment]
> I don't understand why the whole A is checked

Because we use  `asarray_chkfinite()` from numpy as a off-the-shelf utility which doesn't offer such option and don't want to maintain another implementation that differs by a simple detail.

> Maybe, this could be documented?

Sounds good to me. We can mention that finiteness check applies to the whole array and unaffected by `lower` in the notes. Care to send a PR for it?

**Comment by ilayn** [comment]
Actually, I have a PR coming up tomorrow for `eigh` related to #11262. So let me squeeze this into that one.

**Comment by h-larsson** [comment]
Ok. Just let me know in case I still should submit a separate PR. 
Thanks.
