### ISSUE TITLE
ppc64le CI has been erroring a lot lately

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#11281]
Typically with
```
An error occurred while generating the build script.
```

The NumPy ppc64le CI has been working much better, so I'll try switching to an identical config.

**Comment by rgommers** [comment]
Actually, the OpenBLAS handling in `.travis.yml` handling is a bit of a mess. @tylerjereddy would you agree that copying https://github.com/numpy/numpy/blob/master/tools/openblas_support.py and mirror what numpy does is the way to go here?

**Comment by tylerjereddy** [comment]
Hmm, I thought NumPy was having the same issue on Travis CI recently. I tried to match Chuck's update to switch away from the "beta" ppc64le feature on Travis last week I think, but I'm almost certain I've seen this in NumPy CI too?

Does SciPy have equivalent hooks to OpenBLAS for this kind of stuff in `openblas_support.py`: 

`dll = ctypes.CDLL(numpy.core._multiarray_umath.__file__)`

I think we have even more object files produced, but I don't know what the appropriate hook is for making the low-level OpenBLAS call through SciPy?

**Comment by tylerjereddy** [comment]
Cross-ref: https://github.com/numpy/numpy/pull/15164

**Comment by charris** [comment]
The ppc64le CI has been down for the last week or so. I've been waiting for it to get fixed under the assumption -- which may be wrong -- that the maintainers must be aware of it. Then again, it is the Holiday season.

**Comment by tylerjereddy** [comment]
Yeah, my speculation was Winter Break as well---the ppc64le pool may be smaller and less robust to self-repair/disruption, etc.

**Comment by WarrenWeckesser** [comment]
We're getting the one-line failure message

    An error occurred while generating the build script.

frequently on the ppc64le platform.  I'm not sure if this is a recent resurgence of this particular issue, or if other CI issues were masking this one, and its been happening regularly since last December.

**Comment by charris** [comment]
@WarrenWeckesser I've seen that message for the NumPy tests on both s390 and ppc64le.

**Comment by rgommers** [comment]
This is outdated, closing.
