### ISSUE TITLE
CI: azure does not auto-cancel old jobs on pushes

### ISSUE THREAD

**Issue by pv** [scipy/scipy#11295]
Azure pipelines does not seem to cancel previously running PR jobs, when the PR is updated with pushing new commits. Autocanceling is on in Appveyor (rolling builds) and Travis, and probably would also make sense for Azure.

(I don't have permissions to the Azure control panel, so I don't know if there are settings related to this.)

**Comment by tylerjereddy** [comment]
I've added `pav@iki.fi` to the admin team on Azure.

https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml

> You can specify whether additional pushes to a PR should cancel in-progress runs for the same PR. The default is true.

We could try being explicit if we don't believe their default setting claim:

```yaml
# auto cancel true
pr:
  autoCancel: true
```

This assumes there's no conflict with our `trigger` section settings..

**Comment by pv** [comment]
I think the conditions should have `and(succeeded(), ...)` in them: https://github.com/scipy/scipy/pull/11301

**Comment by tylerjereddy** [comment]
If we can observe the improved cancelling behavior soon then we should close this given that #11301 is now merged. I'll leave it open until there is confirmation.

**Comment by pv** [comment]
Closing, seems to work reasonably now.
