### ISSUE TITLE
scipy.interpolate.interp2d yield different result using different input mode

### ISSUE THREAD

**Issue by liubenyuan** [scipy/scipy#11309]
scipy.interpolate.interp2d yield different result using different input mode, i.e., using the coordinate xi, yi format and the `meshgrid` xgrid, ygrid format. The interpolated values are different. Which one should I use?

#### Reproducing code example:

```python
# interpolate
import numpy as np
from scipy.interpolate import interp2d

b = np.arange(12).reshape(4, -1) + np.random.rand(4, 3)
print(b)
xv, yv = np.arange(3)+0.5, np.arange(4)
xx, yy = np.meshgrid(xv, yv)
xi, yi = np.arange(4), np.arange(4)

f1 = interp2d(xx, yy, b, kind='linear')
bi1 = f1(xi, yi)
print(bi1)

f2 = interp2d(xv, yv, b, kind='linear')
bi2 = f2(xi, yi)
print(bi2)

print(np.sum(bi1 - bi2))

```

#### Error message:

The matrix `bi1` and `bi2` are different:
```
[[ 0.73065429  1.0377662   1.77794008  2.23283968]
 [ 3.88839281  4.07755383  4.99582493  5.81855305]
 [ 6.04992033  6.70724932  7.79875565  8.19424226]
 [ 9.29611438 10.10679887 11.34816886 11.71296896]]
[[ 0.73065429  1.0377662   1.78885889  2.23283968]
 [ 3.88839281  4.07755383  5.04263395  5.81855305]
 [ 6.04992033  6.70724932  7.77941028  8.19424226]
 [ 9.29611438 10.10679887 11.31522616 11.71296896]]
-0.0054397651328284
```

Occasionally it yield an warning. But this warning message do not always appears.
```
/usr/share/miniconda3/lib/python3.7/site-packages/scipy/interpolate/_fitpack_impl.py:976: RuntimeWarning: No more knots can be added because the number of B-spline
coefficients already exceeds the number of data points m.
Probable causes: either s or m too small. (fp>s)
        kx,ky=1,1 nx,ny=7,5 m=12 fp=0.159433 s=0.000000
  warnings.warn(RuntimeWarning(_iermess2[ierm][0] + _mess))
```

#### Scipy/Numpy/Python version information:

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.3.2 1.17.4 sys.version_info(major=3, minor=7, micro=5, releaselevel='final', serial=0)
```

**Comment by ev-br** [comment]
Indeed, interp2d switches between two different interpolation modes depending on whether the size of the `z` array is the same as `len(x) == len(y)` or `z.size == x.size * y.size`; see 
https://gist.github.com/ev-br/8544371b40f414b7eaf3fe6217209bff

for a bare-bones illustration, and https://scipy.github.io/devdocs/tutorial/interpolate/smoothing_splines.html#d-smoothing-splines
for a discussion of the specific math formulations of these two behaviors.

Given that  it tacitly switches between quite different problems, and that it does *not* necessary interpolate the data, and other quirks, `interp2d` is deprecated starting from scipy 1.10. The notebook above gives recommendations for replacements. 

I'm going to close the issue, but feel free to continue discussing.
