### ISSUE TITLE
BUG: special: rgamma on negative integers smaller -34

### ISSUE THREAD

**Issue by lorentzenchr** [scipy/scipy#11315]
My issue is about the `scipy.special.rgamma` evaluated at negative integers, which should always be zero. For complex arguments, this is true due to this [code](https://github.com/scipy/scipy/blob/8e579ba23937d9e3e02b8d66c829745a8807376a/scipy/special/_loggamma.pxd#L163). For float or integer input, this starts to fail at `x=-35`.

#### Reproducing code example:
```python
from scipy.special import rgamma

rgamma(-35), rgamma(complex(-35))
```
which gives
`(-2.5783519091890812e+25, 0j)`

#### Scipy/Numpy/Python version information:
```python
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
```
scipy 1.4.1
numpy 1.18.0
sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)

**Comment by person142** [comment]
Hm yes there are several bad things in that branch of `rgamma`, such as this:

```
z = sin(NPY_PI * w);
```

which happens here:

https://github.com/scipy/scipy/blob/master/scipy/special/cephes/rgamma.c#L88

That's going to incur significant rounding errors for large negative arguments.

**Comment by person142** [comment]
So actually it looks like it has the logic to handle the zeros, but since it's doing `sin(NPY_PI * w)` instead of `sinpi(w)` the rounding errors make it fail to find them.
