### ISSUE TITLE
Issues installing Scipy

### ISSUE THREAD

**Issue by MishalJasmine** [scipy/scipy#11329]
I installed Scipy using the command `sudo apt-get install python-numpy python-scipy` and looks like the latest version of both are installed. But when I try to install a python package named `wfdb` using `pip install wfdb`, it get an error while `Building wheel for scipy (PEP 517)`.

    ERROR: Failed building wheel for scipy
    Running setup.py clean for scipy
    ERROR: Command errored out with exit status 1:
    command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install- 
    fhfmfpqi/scipy/setup.py'"'"'; __file__='"'"'/tmp/pip-install- 
    fhfmfpqi/scipy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open) 
    (__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, 
     '"'"'exec'"'"'))' clean --all
       cwd: /tmp/pip-install-fhfmfpqi/scipy
    Complete output (9 lines):
  
    `setup.py clean` is not supported, use one of the following instead:
  
     - `git clean -xdf` (cleans all files)
     - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)
  
     Add `--force` to your command to use it anyway if you must (unsupported).
  
    ----------------------------------------
     ERROR: Failed cleaning build dir for scipy
     Failed to build scipy
     ERROR: Could not build wheels for scipy which use PEP 517 and cannot be installed directly`

I upgraded `pip` using `pip install --upgrade pip`. 
python version used: 3.7
Operating System: Raspbian
Can I get some help on this?

**Comment by rgommers** [comment]
What is happening is that pip used build isolation to build a wheel for `wfdb`; it wants to install every dependency in that clean isolated env just for the wheel build. And there's no SciPy wheel for your platform, so a source build is attempted. Use `pip install --no-build-isolation wfdb` to avoid this.
