### ISSUE TITLE
Add axis parameter for scipy.spatial.distance.jensenshannon

### ISSUE THREAD

**Issue by AidanGG** [scipy/scipy#11325]
My suggestion is to add an axis parameter for `scipy.spatial.distance.jensenshannon`, to be consistent with `scipy.stats.entropy`, instead of assuming an axis of `0` as it currently does.

I'm happy to open a PR when I get time, if this is something that would be useful.

**Comment by rgommers** [comment]
`jensenshannon` docs say that only 1-D arrays are supported, which is the case for all metrics in `distance` - the only difference seems to be that the former doesn't raise.

adding an `axis` argument I'm not sure about. `stats.entropy` also doesn't have an `axis` keyword. 

do you have an actual problem? beyond input validation there doesn't seem much to do here

**Comment by AidanGG** [comment]
Does `stats.entropy` not have an `axis` parameter?

https://github.com/scipy/scipy/blob/977ee7ef558da28144722c4b07324395f3f226bb/scipy/stats/_distn_infrastructure.py#L2612-L2676

Of course I can transpose my arrays before and after running them through `jensenshannon`; I just wanted to be able to calculate multiple Jensen-Shannon divergences in the same way I could calculate multiple Kullback-Leibler divergences through `stats.entropy`.

**Comment by rgommers** [comment]
Ah yes it does have an `axis` keyword - I checked in my installed SciPy (1.3.2), which didn't have it yet. So yes, please ignore my objection - PR welcome
