### ISSUE TITLE
scipy.optimiza.minimize x0 Constraint Validation Uses Strict Inequality

### ISSUE THREAD

**Issue by arewellborn** [scipy/scipy#11321]
Currently the constraint validation for the initial guess checks against a strict inequality. I would assume we should adhere to the `<=` or `>=` for these checks so that the initial guess can be one of the bounds. In particular, I want to freeze one of the variables to a certain value, and this prevents me from doing that.

#### _constraints.py, line 244:
```
        if np.any(f0[mask] < lb[mask]) or np.any(f0[mask] > ub[mask]):
            raise ValueError("`x0` is infeasible with respect to some "
                             "inequality constraint with `keep_feasible` "
                             "set to True.")
```

#### _numdiff.py, line 361:
```
    if np.any((x0 < lb) | (x0 > ub)):
        raise ValueError("`x0` violates bound constraints.")
```

**Comment by pv** [comment]
Both of the examples quoted above allow x0 be equal to lb or ub? Did you mean to point to some other part of the code?

**Comment by arewellborn** [comment]
Oops, yeah sorry about that.
