### ISSUE TITLE
BUG: directed_hausdorff distance on sets u and v when u is a subset of v

### ISSUE THREAD

**Issue by anamamatelashvili** [scipy/scipy#11332]
When `u` and `v` are two sets with `u` being a subset of `v` we should get:

`directed_hausdorff(u, v, seed=0) = (0, index_of_any_point_from_u, index_of_the_same_point_from_v)`

While the distance is returned correctly, the indices for the points witnessing this distance are not guaranteed to be correct. For example,

`directed_hausdorff([(0,0)], [(0,1), (0,0)], seed=0)` return correct answer of `(0.0, 0, 1)`
but `directed_hausdorff([(0,0)], [(0,1), (0,0)], seed=1)` returns incorrect `(0.0, 0, 0)`. 

This is due to strict inequality, `cmin > cmax`, in line 66 of [_directed_hausdorff definition](https://github.com/scipy/scipy/blob/v1.4.1/scipy/spatial/_hausdorff.pyx), as this prevents reassignment of `j_ret` (and `i_ret`) from its default value of `0` (because `cmax=cmin=0` on all `i` iterations in the case of `u` being a subset of `v`). 

To fix this, either the `cmin > cmax` could be changed to `cmin >= cmax` or it could be checked in the beginning if `u` is a subset of `v`.

**Comment by tylerjereddy** [comment]
Interesting, thanks. If you get a chance can you check #11333. I liked the simplicity of the first fix you mention.

**Comment by anamamatelashvili** [comment]
So great, thanks for fixing it so quickly.
