### ISSUE TITLE
TestExp1.test_branch_cut test failure with Intel Fortran

### ISSUE THREAD

**Issue by h6197627** [scipy/scipy#11339]
Running Windows Scipy 1.4.1 (compiled with MKL taken from https://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy) standard test suite with Python 3.7.6 x64 results in failure for TestExp1.test_branch_cut test:
 
```
_________________________________________________________________________________________________________ TestExp1.test_branch_cut _________________________________________________________________________________________________________

self = <scipy.special.tests.test_exponential_integrals.TestExp1 object at 0x00000296E7953EC8>

    def test_branch_cut(self):
        assert np.isnan(sc.exp1(-1))
>       assert sc.exp1(complex(-1, 0)).imag == (
            -sc.exp1(complex(-1, -0.0)).imag
        )
E       AssertionError: assert -3.141592653589793 == --3.141592653589793
E        +  where -3.141592653589793 = (-1.8951178163559368-3.141592653589793j).imag
E        +    where (-1.8951178163559368-3.141592653589793j) = <ufunc 'exp1'>((-1+0j))
E        +      where <ufunc 'exp1'> = sc.exp1
E        +      and   (-1+0j) = complex(-1, 0)
E        +  and   -3.141592653589793 = (-1.8951178163559368-3.141592653589793j).imag
E        +    where (-1.8951178163559368-3.141592653589793j) = <ufunc 'exp1'>((-1-0j))
E        +      where <ufunc 'exp1'> = sc.exp1
E        +      and   (-1-0j) = complex(-1, -0.0)

self       = <scipy.special.tests.test_exponential_integrals.TestExp1 object at 0x00000296E7953EC8>

C:\Program Files\Python\3.7.6\lib\site-packages\scipy\special\tests\test_exponential_integrals.py:12: AssertionError
```

On the same PC package manually compiled with MKL on Ubuntu 18.04 (Python 3.6.5) successfully passes all tests.

**Comment by h6197627** [comment]
I tested version installed from the pip (with OpenBLAS) and it passed all the tests. So I guess it is Windows MKL related problem.

**Comment by h6197627** [comment]
It looks like commit #10787 is not working with Intel MKL under Windows. Unfortunately I am not able to debug it as I am not familiar with Fortran and don't have compiler for it under Windows.

cc @pv

**Comment by h6197627** [comment]
Actually, as far as I understand Fortran code, it is not MKL problem but Intel Fortran compiler's (which is used in Windows build as opposite to gfortran in Linux builds)

**Comment by h6197627** [comment]
After asking for help on Intel Fortran compiler forum it turned out that ifort by default treats both -0.0 and +0.0 as 0.0 and to enable differentiation **assume minus0** flag must be provided to compiler (https://software.intel.com/en-us/fortran-compiler-developer-guide-and-reference-assume). Considering that test_branch_cut test checks -0.0 and +0.0 cases it naturally fails for ifort compiled builds.
Thanks to really helpful mate from Inter Fortran forum, solution was proposed to use ieee_arithmetic intrinsic module which is not dependent on default compiler flags:
add in the beginning of **SUBROUTINE E1Z(Z,CE1)**
`use, intrinsic :: ieee_arithmetic`
and change [line 8734](https://github.com/person142/scipy/blob/c3ad98be855bacbf841702c9d741190604df708d/scipy/special/specfun/specfun.f#L8743)
`CE1=-EL-CDLOG(-Z)+Z*CE1-DSIGN(PI,DIMAG(Z))*(0.0D0,1.0D0)`
to
```
IF (IEEE_CLASS(imag(z))==IEEE_POSITIVE_ZERO) THEN
  CE1=-EL-CDLOG(-Z)+Z*CE1-PI*(0.0D0,1.0D0)
ELSE
  CE1=-EL-CDLOG(-Z)+Z*CE1+PI*(0.0D0,1.0D0)
ENDIF
```
I can do PR in case it is acceptable fix.
for visibility cc @person142

**Comment by person142** [comment]
So I think the IEEE arithmetic module is in the 2003 standard, and IIRC we are restricted to Fortran 90/95 right now.

It would be awesome if we could move to 2003 though-it has other useful features for us (ISO C binding e.g.).

**Comment by h6197627** [comment]
Yes, unfortunately it is from 2003 standard.
Maybe it is possible to extend building config and to pass additional **assume minus0** flag in case ifort compiler is detected as a current fix?

**Comment by person142** [comment]
So I went and checked compiler support, and it seems like we might be ok targeting 2003. Opened this issue: https://github.com/scipy/scipy/issues/11421 so that we can make an official decision. Once that's settled we can proceed here. 🤞 for 2003 support!

**Comment by person142** [comment]
Ok, so I think we're waiting a bit on Fortran 2003. For the compiler flag, the right place to add it is here:

https://github.com/scipy/scipy/blob/master/scipy/special/setup.py#L55

Docs on `add_library` are here:

https://github.com/numpy/numpy/blob/master/numpy/distutils/misc_util.py#L1513

It might behoove us to search for any further mentions of negative 0 in the specfun source to make sure there aren't any undiscovered bugs.

Also ping @cgohlke who might find this of interest.

**Comment by h6197627** [comment]
Hi @person142,
I wrote some code which should be fixing this issue, however the main problem is that I don't have ifort to test it. Considering that this bug was not discovered before I guess standard scipy CI also does not test it with ifort.
I made changes in my repo h6197627/scipy@c7b0c289a36e86932fe878dc6103a88048e1fdee so far, if its ok I can do PR.

**Comment by pv** [comment]
@h6197627: looks like the right way to do it, for fixing ifort. We'd want someone to test it before merging, however.

**Comment by h6197627** [comment]
Maybe @cgohlke could be so kind to help us?

**Comment by cgohlke** [comment]
I applied the patch to scipy 1.4.1 and rebuilt to no avail:
```
====================================================== FAILURES =======================================================
______________________________________________ TestExp1.test_branch_cut _______________________________________________

self = <scipy.special.tests.test_exponential_integrals.TestExp1 object at 0x000001C167954940>

    def test_branch_cut(self):
        assert np.isnan(sc.exp1(-1))
>       assert sc.exp1(complex(-1, 0)).imag == (
            -sc.exp1(complex(-1, -0.0)).imag
        )
E       AssertionError: assert -3.141592653589793 == --3.141592653589793
E        +  where -3.141592653589793 = (-1.8951178163559368-3.141592653589793j).imag
E        +    where (-1.8951178163559368-3.141592653589793j) = <ufunc 'exp1'>((-1+0j))
E        +      where <ufunc 'exp1'> = sc.exp1
E        +      and   (-1+0j) = complex(-1, 0)
E        +  and   -3.141592653589793 = (-1.8951178163559368-3.141592653589793j).imag
E        +    where (-1.8951178163559368-3.141592653589793j) = <ufunc 'exp1'>((-1-0j))
E        +      where <ufunc 'exp1'> = sc.exp1
E        +      and   (-1-0j) = complex(-1, -0.0)

D:\Programs\Python38\Lib\site-packages\scipy\special\tests\test_exponential_integrals.py:12: AssertionError
__________________________________________________ test_expi_complex __________________________________________________

    @check_version(mpmath, '0.10')
    def test_expi_complex():
        dataset = []
        for r in np.logspace(-99, 2, 10):
            for p in np.linspace(0, 2*np.pi, 30):
                z = r*np.exp(1j*p)
                dataset.append((z, complex(mpmath.ei(z))))
        dataset = np.array(dataset, dtype=np.complex_)

>       FuncData(sc.expi, dataset, 0, 1).check()
E       AssertionError:
E       Max |adiff|: 6.28319
E       Max |rdiff|: 0.304157
E       Bad results (9 out of 300) for the following points (in output 0):
E                           1.e-99+0.j => -227.37870854150898+6.283185307179586j !=        -227.37870854150898+0.j  (rdiff            0.02763312953742352)
E            1.668100537200083e-88+0.j => -201.5385869423536+6.283185307179586j !=        -201.53858694235356+0.j  (rdiff            0.03117609090400528)
E           2.7825594022071145e-77+0.j => -175.6984653431982+6.283185307179586j !=         -175.6984653431982+0.j  (rdiff            0.03576118490794107)
E           4.6415888336126776e-66+0.j => -149.8583437440428+6.283185307179586j !=         -149.8583437440428+0.j  (rdiff           0.041927497329819895)
E            7.742636826811214e-55+0.j => -124.01822214488739+6.283185307179586j !=        -124.01822214488739+0.j  (rdiff           0.050663404123299706)
E           1.2915496650148721e-43+0.j => -98.178100545732+6.283185307179586j !=           -98.178100545732+0.j  (rdiff            0.06399782917222806)
E           2.1544346900318602e-32+0.j => -72.3379789465766+6.283185307179586j !=          -72.3379789465766+0.j  (rdiff            0.08685873449436396)
E           3.5938136638045226e-21+0.j => -46.49785734742121+6.283185307179586j !=         -46.49785734742121+0.j  (rdiff            0.13512849119547773)
E            5.994842503189323e-10+0.j => -20.657735747666305+6.283185307179586j !=        -20.657735747666308+0.j  (rdiff            0.30415653409107984)

D:\Programs\Python38\Lib\site-packages\scipy\special\tests\test_mpmath.py:46: AssertionError
========================= 2 failed, 1353 passed, 164 skipped, 42 xfailed, 1 xpassed in 13.47s =========================
```

**Comment by h6197627** [comment]
Thanks, @cgohlke!
Well, it actually makes things even worse - test_expi_complex test failed. Just to be sure, was it successfully passing without patching?

**Comment by cgohlke** [comment]
> Just to be sure, was it successfully passing without patching?

no

**Comment by h6197627** [comment]
Hm, on my machine Scipy 1.4.1 taken from @cgohlke repo fails only TestExp1.test_branch_cut
Anyway, unfortunately patch is not working

**Comment by h6197627** [comment]
It appears that [COMPILER EXPLORER](https://godbolt.org) has now Intel Fortran. So I tried to test isolated original failing SciPy function from https://github.com/scipy/scipy/blob/master/scipy/special/specfun/specfun.f#L8711
```
        PROGRAM TEST
        complex(8) :: POS, POS_RES, NEG, NEG_RES
        POS=CMPLX(-1, 0)
        call E1Z(POS, POS_RES)
        PRINT *, POS_RES
        NEG=CMPLX(-1, -0.0)
        call E1Z(NEG, NEG_RES)
        PRINT *, NEG_RES
        END


        SUBROUTINE E1Z(Z,CE1)
        IMPLICIT COMPLEX*16 (C,Z)
        IMPLICIT DOUBLE PRECISION (A,D-H,O-Y)
        PI=3.141592653589793D0
        EL=0.5772156649015328D0
        X=DBLE(Z)
        A0=CDABS(Z)
        XT=-2*DABS(DIMAG(Z))
        IF (A0.EQ.0.0D0) THEN
           CE1=(1.0D+300,0.0D0)
        ELSE IF (A0.LE.5.0.OR.X.LT.XT.AND.A0.LT.40.0) THEN
           CE1=(1.0D0,0.0D0)
           CR=(1.0D0,0.0D0)
           DO 10 K=1,500
              CR=-CR*K*Z/(K+1.0D0)**2
              CE1=CE1+CR
              IF (CDABS(CR).LE.CDABS(CE1)*1.0D-15) GO TO 15
10         CONTINUE
15         CONTINUE
           IF (X.LE.0.0.AND.DIMAG(Z).EQ.0.0) THEN
              CE1=-EL-CDLOG(-Z)+Z*CE1-DSIGN(PI,DIMAG(Z))*(0.0D0,1.0D0)
           ELSE
              CE1=-EL-CDLOG(Z)+Z*CE1
           ENDIF
        ELSE
           ZC=0D0
           ZD=1/Z
           ZDC=1*ZD
           ZC=ZC + ZDC
           DO 20 K=1,500
              ZD=1/(ZD*K + 1)
              ZDC=(1*ZD - 1)*ZDC
              ZC=ZC + ZDC

              ZD=1/(ZD*K + Z)
              ZDC=(Z*ZD - 1)*ZDC
              ZC=ZC + ZDC

              IF (CDABS(ZDC).LE.CDABS(ZC)*1.0D-15.AND.K.GT.20) GO TO 25
20         CONTINUE
25         CE1=CDEXP(-Z)*ZC
           IF (X.LE.0.0.AND.DIMAG(Z).EQ.0.0) CE1=CE1-PI*(0.0D0,1.0D0)
        ENDIF
        RETURN
        END
```
with selected **x86-64 ifort 21.1.9** Fortran compiler this program with default compilation options returns results that will fail SciPy test:

>  (-1.89511781635594,-3.14159265358979)
>  (-1.89511781635594,-3.14159265358979)

However, if additionally add **-assume minus0** compilation flag, it will correctly return:

>  (-1.89511781635594,-3.14159265358979)
>  (-1.89511781635594,3.14159265358979)

So, I think the problem with proposed fix is that provided compilation flag is not correctly propagated. Unfortunately ifort is not available for me to check what goes wrong. But Intel says that it is possible to request it for open source project, so maybe it is possible to introduce Intel Fortran into SciPy CI?

**Comment by h6197627** [comment]
Finally, after Intel released [OneAPI](https://software.intel.com/content/www/us/en/develop/tools/oneapi/all-toolkits.html) with freely available ifort and icc compilers I was able to debug and fix this issue!
@pv, @person142, please help by reviewing changes

**Comment by rgommers** [comment]
> Finally, after Intel released [OneAPI](https://software.intel.com/content/www/us/en/develop/tools/oneapi/all-toolkits.html) with freely available ifort and icc compilers

Thanks for pointing that out @h6197627! Having ifort freely available after so many years is important news. Looks like they even packaged it for conda to make life easy: https://anaconda.org/intel/fortran_rt.

**Comment by rgommers** [comment]
> Looks like they even packaged it for conda to make life easy: https://anaconda.org/intel/fortran_rt.

Correction, their docs are a bit confusing, they only packaged the runtime for conda. Need to use a native installer or Docker for `ifort` and `icc`.

**Comment by h6197627** [comment]
Actually I used [standalone installers](https://software.intel.com/content/www/us/en/develop/articles/oneapi-standalone-components.html) for ifort / icc / MKL.

**Comment by rgommers** [comment]
The description of `assume minus0` in the ifort docs:

_Tells the compiler to use Fortran 95 standard semantics for the treatment of the IEEE* floating value -0.0 in the SIGN intrinsic, which distinguishes the difference between -0.0 and +0.0, and to write a value of -0.0 with a negative sign on formatted output._

So by default we get F77/90 semantics from the compiler, and those semantics are not IEEE 754 compliant.

gh-13271 adds the compile flag only to the `sc_specfun` extension. It looks to me like, if we'd want this flag present , we'd want it everywhere. https://gcc.gnu.org/legacy-ml/fortran/2009-05/msg00351.html provides interesting context, comparing behavior between `ifort` and `gfortran`, and recommending other `ifort` flags to set as defaults (e.g., [-prec-div](https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/compiler-options/compiler-option-details/floating-point-options/prec-div-qprec-div.html)) for more compliant behavior.

Also maintenance-wise it seems nicer to set these flags globally at the build system level, rather than in the one extension that currently has one failing test.

**Comment by rgommers** [comment]
Specifically, we already have this in `numpy/distutils/fcompiler/intel.py`:
```
    def get_flags_opt(self):  # Scipy test failures with -O2
        v = self.get_version()
        mpopt = 'openmp' if v and v < '15' else 'qopenmp'
        return ['-fp-model', 'strict', '-O1', '-{}'.format(mpopt)]
```
That seems like the correct place to add more flags.

**Comment by h6197627** [comment]
@rgommers, thanks for arvices!
I tried locally and it seems to work. Just couple of questions before submitting PR:
1. Where is it more appropriate to place this flag into **get_flags** or **get_flags_opt** methods?
2. Methods **get_flags**, **get_flags_opt**, **get_flags_arch** of IntelEM64TFCompiler class are identical to methods of parent IntelFCompiler class, so I think it is ok to remove them and place new flag into base IntelFCompiler class.
3. Considering other flags - I think I am not the right person to do it as far as I am completely ignorant of Fortran. For example mentioned **-prec-div** flag has notice "The result is more accurate, with some loss of performance.", so I am not sure is it good or not to sacrifice performance there. Though, if someone guide me, I will add another flags as well.

**Comment by rgommers** [comment]
>     1. Where is it more appropriate to place this flag into **get_flags** or **get_flags_opt** methods?

I think `get_flags_opt`.

>     2. Methods **get_flags**, **get_flags_opt**, **get_flags_arch** of IntelEM64TFCompiler class are identical to methods of parent IntelFCompiler class, so I think it is ok to remove them and place new flag into base IntelFCompiler class.

Yes, that sounds like a useful cleanup.

>     3. Considering other flags - I think I am not the right person to do it as far as I am completely ignorant of Fortran. For example mentioned **-prec-div** flag has notice "The result is more accurate, with some loss of performance.", so I am not sure is it good or not to sacrifice performance there. Though, if someone guide me, I will add another flags as well.

Sounds fine, please leave those as is. Making the minimal amount of changes now is fine; someone can get to this later once we go for a larger cleanup of build stuff and can test with Intel Fortran more easily.

**Comment by h6197627** [comment]
@rgommers, I made PR https://github.com/numpy/numpy/pull/18753, please help reviewing
