### ISSUE TITLE
Scipy.csgraph.maximum_flow

### ISSUE THREAD

**Issue by sutanu123** [scipy/scipy#11336]
Unable to import scipy.csgraph.maximum_flow in python code. Installed python 2 weeks back using Anaconda. Checked using repl.it. Same error on importing maximum_flow.
**Msg:**
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from scipy.sparse.csgraph import maximum_flow
ImportError: cannot import name 'maximum_flow' from 'scipy.sparse.csgraph' (/home/runner/.local/share/virtualenvs/python3/lib/python3.7/site-packages/scipy/sparse/csgraph/__init__.py)

**Comment by fuglede** [comment]
This would happen if you're not using a recent version of SciPy; `maximum_flow` was introduced in 1.4.0; what you get from `scipy.__version__`?

**Comment by fuglede** [comment]
This can probably be closed. @rgommers

**Comment by rgommers** [comment]
thanks @fuglede!
