### ISSUE TITLE
scipy.constants 1.4 update contains disparate electric permittivity constants

### ISSUE THREAD

**Issue by gschaffner** [scipy/scipy#11341]
With the CODATA 2014 -> 2018 update that was incorporated into the Scipy 1.3.3. -> 1.4 update, the electric constants became disparate. [CODATA 2014](https://physics.nist.gov/cuu/Constants/Table/allascii_2014.txt) contained a constant `electric constant` that was deprecated and replaced with `vacuum electric permittivity` in [CODATA 2018](https://physics.nist.gov/cuu/Constants/Table/allascii.txt). Comparing related constants in Scipy 1.3.3 and 1.4, we have

```
scipy = 1.3.3
epsilon_0 =                    8.854187817620389e-12
electric constant =            8.854187817620389e-12
vacuum electric permittivity = KeyError

scipy = 1.4.1
epsilon_0 =                    8.854187817620389e-12
electric constant =            8.854187817e-12
vacuum electric permittivity = 8.854187817620389e-12
```

In 1.4+, `epsilon_0 != electric constant`.

It seems to me that 1.4+ should maintain a constant `electric constant` for compatibility reasons, but this value should be updated in 1.4+ to the CODATA 2018 value.

If this is deemed an issue, then there may be other constants that something similar has happened to with the update. They could be found by diffing the CODATA 2014 and 2018 tables and looking for constants that were removed from CODATA 2014.

**Comment by pv** [comment]
This probably affects only the "exact" values. The update in f166e3a7140 removed some of these, but probably should not have:
```
@@ -1340,9 +1710,8 @@ mu0 = 4e-7 * pi
 epsilon0 = 1 / (mu0 * c * c)
 
 exact_values = {
-    'mag. constant': (mu0, 'N A^-2', 0.0),
-    'electric constant': (epsilon0, 'F m^-1', 0.0),
-    'characteristic impedance of vacuum': (sqrt(mu0 / epsilon0), 'ohm', 0.0),
+    'vacuum mag. permeability': (mu0, 'N A^-2', 0.0),
+    'vacuum electric permittivity': (epsilon0, 'F m^-1', 0.0),
     'atomic unit of permittivity': (4 * epsilon0 * pi, 'F m^-1', 0.0),
     'joule-kilogram relationship': (1 / (c * c), 'kg', 0.0),
     'kilogram-joule relationship': (c * c, 'J', 0.0),
```

**Comment by j-bowhay** [comment]
Completed in #11345
