### ISSUE TITLE
Why are the results of line_search_1 and those of line_search_2 different?

### ISSUE THREAD

**Issue by dmeoli** [scipy/scipy#11360]
line_search_1 and line_search_2 returns different step size over the same input:

`from scipy.optimize import rosen`
`from scipy.optimize import rosen_der`
`from scipy.optimize.linesearch import line_search_wolfe1`
`from scipy.optimize.linesearch import line_search_wolfe2`

`line_search_wolfe1(rosen, rosen_der, np.array([-1, 1]), np.array([4, 0]), np.array([-4, 0]))[0]`
`0.0016750668056533036`

`line_search_wolfe2(rosen, rosen_der, np.array([-1, 1]), np.array([4, 0]), np.array([-4, 0]))[0]`
`0.5`

How can I parametrize line_search_2 to make the results equal to line_search_1?

**Comment by mdhaber** [comment]
These are not publicly-documented functions, so I'm afraid we can't offer official support. A maintainer familiar with these functions is welcome to respond, of course, but I don't think we need to keep the issue open.
