### ISSUE TITLE
lil_matrix 2d logical indexing not working as expected

### ISSUE THREAD

**Issue by alexchartier** [scipy/scipy#11371]
Using sparse lil_matrix, I'm trying to pull out a block within a larger matrix, but my logical indexing returns a 1D array (shape 1x2) instead of the expected 2D array (shape 2x2):

#### Reproducing code example:

```
# test_code
lilm = sparse.lil_matrix(np.array([[1, 1, 0], [1, 1, 0], [0, 0, 1]]))
inds = np.squeeze(lilm[0, :].toarray() != 0)
out = lilm[inds, inds].toarray()
print(out.shape)

>>> (1, 2)

```

#### Scipy/Numpy/Python version information:
1.3.0 1.16.4 sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)

**Comment by ewmoore** [comment]
This is old and I hope you've figured it out @alexchartier, but this isn't a bug. Sparse is correctly replicating numpy indexing here.  For example:

```
In [1]: import numpy as np

In [2]: from scipy import sparse

In [3]: a = np.arange(9).reshape(3,3)

In [4]: index = np.array([True, False, True])

In [5]: m = sparse.lil_matrix(a)

In [6]: a[index, index]
Out[6]: array([0, 8])

In [7]: m[index, index].toarray()
Out[7]: array([[0, 8]], dtype=int64)
```
You can use `np.ix_` to get the result you're looking for:
```
In [8]: a[np.ix_(index, index)]
Out[8]:
array([[0, 2],
       [6, 8]])

In [9]: m[np.ix_(index, index)].toarray()
Out[9]:
array([[0, 2],
       [6, 8]], dtype=int64)
```

And the results without `np.ix_` can be under stood by inserting `nonzero()` on both of the boolean indexing arrays:
```
In [11]: a[index.nonzero(), index.nonzero()]
Out[11]: array([[0, 8]])
```
