### ISSUE TITLE
Add wrapper for ?ptsvx

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#11374]
See [NumFOCUS Small Development Grant Proposal 2019 Round 3 proposal](https://www.dropbox.com/s/i24h3j2osol56uf/Small%20Development%20Grant%20-%20LAPACK%20%20%28Condensed%29.pdf?dl=0) for background.

Add wrapper for [?ptsvx](http://www.netlib.org/lapack/explore-html/d5/d56/a18560_ga9584fd037291be2dff42741bb3215772.html). 

Existing [wrapper](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lapack.sgesvx.html#scipy.linalg.lapack.sgesvx) for [?gesvx](http://www.netlib.org/lapack/explore-html/d7/d3b/group__double_g_esolve_ga9d90ccf6e340cacd08b7bbbb502ceb21.html) provides some guidance. Experience from gh-11373 and PR will be very helpful.

Suggested signature:
```
! x, df, ef, rcond, ferr, berr, info  = ptsvx(d, e, b, fact="N", overwrite_d, overwrite_e=0, df=None, ef=None)
```

- Should we return `work`? There is no useful [documentation](http://www.netlib.org/lapack/explore-html/d5/d56/a18560_ga9584fd037291be2dff42741bb3215772.html) for it, and [gesvx ](http://www.netlib.org/lapack/explore-html/d7/d3b/group__double_g_esolve_ga9d90ccf6e340cacd08b7bbbb502ceb21.html) doesn't return them.
- What should I have put as default values of `df`, `ef` above? If the user provides them, great; if not, the arrays need to be allocated to be used as outputs.

Test idea w/ `fact = 'N'`:

- Generate random tridiagonal spd matrix `A` (that is, generate `d`, `e`). See thoughts in gh-11123.
- Generate random solutions `x`
- Generate `b` from `A@x`
- Solve system using `?ptsvx`, not providing `df`, `ef`
- Check `info=0`
- Compare solution from `?ptsvx` against known `x`
- As we did with `?pttrf`, turn factors `df`, `ef` into `L` and compare against `A`
- Maybe just verify that `rcond` is a scalar and `ferr`/`berr` are arrays with the right shape?

Test idea w/ `fact = 'F'`:

- Generate random tridiagonal matrix `A` (that is, generate `d`, `e`).
- Factor `A` with `?pttrf` to generate `df`, `de`
- Generate random solutions `x`
- Generate `b` from `A@x`
- Solve system using `?ptsvx`, providing `df`, `ef`
- Check `info=0`
- Compare solution from `?ptsvx` against known `x`
- Maybe just verify that `rcond` is a scalar and `ferr`/`berr` are arrays with the right shape?

In both cases, perform similar tests for the different `trans` options.
In both cases, also test for singular matrix, checking that `info!=0` and also `<= N` (or more specific)
In both cases, also test for non-spd matrix, checking that `info!=0` and also `<= N` (or more specific)
It might be cool to create an example for which the matrix is numerically - but not exactly - singular to see if we can get `info==N+1`.
In both cases, test for incorrect/incompatible array sizes for each array.

Also: implement all examples from the [NAG manual](https://www.nag.com/numeric/fl/nagdoc_fl26.2/html/f07/f07jbf.html) as additional tests.

**Comment by mdhaber** [comment]
@swallan

**Comment by swallan** [comment]
@mdhaber 
Something I was thinking about with this one was parametrizing `d` and `e` with lambdas for the "N" and "F" facts. Before investigating it took much I wanted to check in with you to see if you already know if this is possible or think that's a good idea.

Where we could pass in a lambda to 
1. for fact="N": do nothing to d and e
2. for fact="F": pass in the pttrf lapack routine

I imagined something like this:
`@pytest.mark.parametrize("fact,de_lambda", 
[("F", lambda d: get_lapack_funcs('pttrf', dtype=e[1][0])(**d)),
 ("N", lambda (d,e): (d,e))])`

Let me know your thoughts!

**Comment by mdhaber** [comment]
There are a few typos but that approach looks good to me.

**Comment by swallan** [comment]
@Kai-Striega I didn't see a branch already created by you for this one so here's is the branch where I have begun to write the tests: [lapack_support_ptsvx](https://github.com/swallan/scipy/tree/lapack_support_ptsvx). I realize now that I created this off of the master branch on my scipy fork which is outdated, unfortunately. 

@mdhaber I still need to check over this a few times but here's the in progress version.

**Comment by mdhaber** [comment]
@swallan I added a few comments in your latest commits. Are you able to see them?

**Comment by swallan** [comment]
Yes, I am able to see them, thank you!

**Comment by swallan** [comment]
@mdhaber Yes, I am able to see them, thank you!

**Comment by Kai-Striega** [comment]
@swallan I can take a look at it (and make the wrapper) over the weekend. In regard to your branch being outdated, could you rebase / pull the upstream branch?

**Comment by swallan** [comment]
I rebased it so now it should be more or less current with scipy:master.

**Comment by Kai-Striega** [comment]
@swallan I've created a branch on my repo for you to look at. I've tried running the tests, but they don't seem to be passing. This is largely because ?pttrf is missing.

Another thing is that the signature is ``df, ef, x`` **not** ``x, df, ef`` as was suggested above. I'm not really sure how to go about changing the order of the arguments, perhaps @ilayn or @mdhaber can give a suggestion?

**Comment by swallan** [comment]
I see that the nag real type test is passing (with the args in the new order), and will investigate the others later today! For now I will swap orders. 

and will break apart this very mega test into the more specific parts.

**Comment by ilayn** [comment]
Order is defined by the most outer definition starting with `subroutine`. There it is up to us to reorder args. The inner callstatement is the fixed Lapack signature but they are independent.

**Comment by swallan** [comment]
@Kai-Striega 

I think that ef should be dimension n-1 in the wrapper, no?

>    <ftype2> optional, intent(in,out), depend(n), dimension(n) :: df
>     <ftype2> optional, intent(in,out), depend(n), **dimension(n)** :: ef
>     <ftype2> intent(in), dimension(ldb, nrhs) :: b
>     integer intent(hide), depend(b) :: ldb = max(1, shape(b, 0))
