### ISSUE TITLE
Add wrapper for ?gtsvx

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#11373]
See [NumFOCUS Small Development Grant Proposal 2019 Round 3 proposal](https://www.dropbox.com/s/i24h3j2osol56uf/Small%20Development%20Grant%20-%20LAPACK%20%20%28Condensed%29.pdf?dl=0) for background.

Add wrapper for [?gtsvx](http://www.netlib.org/lapack/explore-html/d4/d62/group__double_g_tsolve_gaa9e938f737eedf395c4429393c769d07.html).

Existing [wrapper](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lapack.sgesvx.html#scipy.linalg.lapack.sgesvx) for [?gesvx](http://www.netlib.org/lapack/explore-html/d7/d3b/group__double_g_esolve_ga9d90ccf6e340cacd08b7bbbb502ceb21.html) provides some guidance.

Suggested signature:
```
! x, dlf, df, duf, du2f, ipiv, rcond, ferr, berr, info  = gtsvx(dl, d, du, b, fact="N", trans="N", overwrite_dl=0, overwrite_d=0, overwrite_du=0, dlf=None, df=None, duf=None, du2=None, ipiv=None, )
```

- Should we return `work` or `iwork`? There is no useful [documentation](http://www.netlib.org/lapack/explore-html/d4/d62/group__double_g_tsolve_gaa9e938f737eedf395c4429393c769d07.html) for them, really, and [gesvx ](http://www.netlib.org/lapack/explore-html/d7/d3b/group__double_g_esolve_ga9d90ccf6e340cacd08b7bbbb502ceb21.html) doesn't return them.
- What should I have put as default values of `dlf`, etc... above? If the user provides them, great; if not, the arrays need to be allocated to be used as outputs.

Test idea w/ `fact = 'N'`:

- Generate random tridiagonal matrix `A` (that is, generate `dl`, `d`, `du`).
- Generate random solutions `x`
- Generate `b` from `A@x`
- Solve system using `?gtsvx`, not providing `dlf`, `df`, `duf`, `du2f`, `ipiv`
- Check `info=0`
- Compare solution from `?gtsvx` against known `x`
- As we did with `?gttrf`, turn factors `dlf`, `df`, `duf`, `du2f`, `ipiv` into `L` and `U` and compare against `A`
- Maybe just verify that `rcond` is a scalar and `ferr`/`berr` are arrays with the right shape?

Test idea w/ `fact = 'F'`:

- Generate random tridiagonal matrix `A` (that is, generate `dl`, `d`, `du`).
- Factor `A` with `?gttrf` to generate `dlf`, `df`, `duf`, `du2f`, `ipiv`
- Generate random solutions `x`
- Generate `b` from `A@x`
- Solve system using `?gtsvx`, providing  `dlf`, `df`, `duf`, `du2f`, `ipiv`
- Check `info=0`
- Compare solution from `?gtsvx` against known `x`
- Maybe just verify that `rcond` is a scalar and `ferr`/`berr` are arrays with the right shape?

In both cases, perform similar tests for the different `trans` options.
In both cases, also test for singular matrix, checking that `info!=0` (or more specific)
In both cases, test for incorrect/incompatible array sizes for each array.

Also: implement all examples from the [NAG manual](https://www.nag.com/numeric/fl/nagdoc_latest/html/f07/f07cbf.html) as additional tests.

**Comment by mdhaber** [comment]
@swallan

**Comment by ilayn** [comment]
Couldn't use the link on the phone but ptsvx and gtsvx shouldn't have any lwork needed.

**Comment by Kai-Striega** [comment]
I don't think we need any of the ``overwrite_?`` arguments. If the factored version is used (``fact='F'``) then they are input arguments where the documentation guarantees that 

> DL, D, DU, DLF, DF, DUF, DU2 and IPIV will not be modified.

If ``fact='N'`` then those matrices are dedicated as outputs and shouldn't contain any meaningful information to begin with.

**Comment by mdhaber** [comment]
OK good call.

**Comment by swallan** [comment]
I've begun the test for this routine on a branch on my fork based on Kai's with the routine. I'll open a pull for it soon! @mdhaber
