### ISSUE TITLE
scipy entropy function

### ISSUE THREAD

**Issue by RavishKumarTipu** [scipy/scipy#11388]
scipy entropy functions returns incorrect results for array 1,1,1,1.... result should be zero

**Comment by peterbell10** [comment]
I presume that you are looking at the definition of entropy

    S = -k * sum(p * ln(p))

and see that `ln(1) == 0`. However, the input to `scipy.stats.entropy` is normalised before calculating the entropy so the results should actually be

    S = -k * len(p) * (1/len(p) * log(1/len(p)))
      = -k * log(1/len(p))
      =  k * log(len(p))

which is non-zero for all `len(p) > 1`. Perhaps this needs clarified in the docs?

**Comment by WarrenWeckesser** [comment]
The [docstring](http://scipy.github.io/devdocs/generated/scipy.stats.entropy.html) already says

> This routine will normalize `pk` and `qk` if they don’t sum to 1.

Does it need more clarification?

**Comment by peterbell10** [comment]
I suppose that's fair enough.
