### ISSUE TITLE
csgraph.minimum_spanning_tree loses precision

### ISSUE THREAD

**Issue by fabian-paul** [scipy/scipy#11391]
csgraph.minimum_spanning_tree seems to lose double precision somewhere along the way.
This is surprising since all the input and output is formally float64 but still small elements < 1E-8 are rounded to zero.

#### Reproducing code example:
```
>>> import numpy as np
>>> import scipy.sparse
>>> M=np.zeros((3,3), dtype=np.float64)
>>> scipy.sparse.csgraph.minimum_spanning_tree(M + 1E-8).toarray()
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
>>> scipy.sparse.csgraph.minimum_spanning_tree(M + 1E-7).toarray()
array([[0.e+00, 1.e-07, 1.e-07],
       [0.e+00, 0.e+00, 0.e+00],
       [0.e+00, 0.e+00, 0.e+00]])
>>> scipy.sparse.csgraph.minimum_spanning_tree(M + 1E-8).dtype
dtype('float64')
```

#### Scipy/Numpy/Python version information:
```
>>> print(scipy.__version__, np.__version__, sys.version_info)
1.3.1 1.17.2 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
```

**Comment by fabian-paul** [comment]
The problem seems to be related to the automatic conversion from numpy array format
```
>>> scipy.sparse.csgraph.minimum_spanning_tree(M+1.E-8).toarray()
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
>>> scipy.sparse.csgraph.minimum_spanning_tree(scipy.sparse.csr_matrix(M+1.E-8)).toarray()
array([[0.e+00, 1.e-08, 1.e-08],
       [0.e+00, 0.e+00, 0.e+00],
       [0.e+00, 0.e+00, 0.e+00]])
```
Is implicit conversion to sparse formats discouraged?

**Comment by perimosocordiae** [comment]
The issue is actually a result of conversion of the dense distance matrix to a masked array here:
https://github.com/scipy/scipy/blob/f865e9ed01be30c52f2b3841795aa2d8f5fa3d86/scipy/sparse/csgraph/_tools.pyx#L161

The defaults for `np.ma.masked_values` set `rtol=1e-05` and `atol=1e-08` (used in a call to `np.isclose`), which explains why your `M + 1e-8` case is getting messed up.

**Comment by perimosocordiae** [comment]
Possible fixes here:

 1. expose tolerance parameters in the various `csgraph` functions that end up calling this function on dense inputs
 2. document the existing behavior more clearly, and encourage users to provide sparse matrices when possible (as they prevent this ambiguity problem)

I think option (2) is probably the way to go as of now.

**Comment by fabian-paul** [comment]
I agree, (2) sounds reasonable.
