### ISSUE TITLE
KDTree sparse matrix values for distance > max_distance

### ISSUE THREAD

**Issue by adriangb** [scipy/scipy#11392]
This is as much a question as a feature request as I am not all that familiar with the theory behind k-d-trees.

In the cKDTree/KDTree classes' `sparse_distance_matrix` method any distance larger than the `max_distance` parameter is left as zero. Is there a specific reason for choosing zero and not `None`, `np.nan`, etc?

The main reason I see to go with `np.nan` is to differentiate from distance calculations from a point to itself. 
The main reason I see to go with the current implementation is speed (no extra operation to set `result[i,j] = np.nan`) and space (if you set zero values to `np.nan` it's not really a sparse matrix anymore).

**Describe the solution you'd like**
It would be nice to have an option to set the distances larger than `max_distance` to an arbitrary argument. Referencing the [pure Python implementation](https://github.com/scipy/scipy/blob/f865e9ed01be30c52f2b3841795aa2d8f5fa3d86/scipy/spatial/kdtree.py#L185):
```python
def sparse_distance_matrix(self, other, max_distance, set_on_maxdist=0, p=2.):

        result = scipy.sparse.dok_matrix((self.n,other.n))

        def traverse(node1, rect1, node2, rect2):
            ...
                            if d <= max_distance:
                                result[i,j] = d
                            elif set_on_maxdist != 0:
                                result[i,j] = set_on_maxdist
           ...
```

**Describe alternatives you've considered**
One can loop over the results and try to differentiate based on the indexing, but that requires extra computation and relying on indexing is unreliable.

**Comment by sturlamolden** [comment]
This is why in cKDTree, ```sparse_distance_matrix``` has the keyword argument ```output_type```.

**Comment by adriangb** [comment]
> This is why in cKDTree, `sparse_distance_matrix` has the keyword argument `output_type`.

Let me check if I am understanding correctly. That parameter allows me to get back a `dict`. Unlike the `dok_matrix`, asking for a key for which `d > max_distance` gives a `KeyError` instead of returning `0` (which is the behavior `dok_matrix`), this would indeed allow differentiation of `d > max_distance` from `d == 0`. Is this accurate?

**Comment by sturlamolden** [comment]
yes

**Comment by adriangb** [comment]
Glad I could understand. I think that usage would still fall under post-processing, which I think is worse than doing things once. I guess my main gripe is that while using a sparse matrix has obvious advantages, not being able to distinguish between the "sparse" value and a 0 value is not ideal in applications where you expect some zeros valued results.

Looking at the source some more, it seems that really what would need to be changed is the [`dok_matrix` class](https://github.com/scipy/scipy/blob/master/scipy/sparse/dok.py), similar to [this SO question](https://stackoverflow.com/questions/6256206/scipy-sparse-default-value). The changes to allow a non-zero sparse value seem to be pretty straightforward. I'd be happy to give it a shot if you think the feature makes any sense to have.

**Comment by perimosocordiae** [comment]
The pydata/sparse project implements exactly this feature, via the `fill_value` attribute. @hameerabbasi 

Unfortunately the scipy.sparse implementation makes a strong assumption that non implicit values are always zero. It would be a major effort to change that without breaking things.

**Comment by adriangb** [comment]
I see. I was thinking of it exactly how it is implemented in the pydata/sparse project.

I tested implementing it in scipy with a default handled similar to the [SparseArray base class in pydata/sparse](https://github.com/pydata/sparse/blob/40138e042c2aa807a0b96891a82b3583b8c4ae3c/sparse/_sparse_array.py#L39), all tests passed and nothing seemed to break as long as the parameter is never changed from the default. Obviously creating a sparse matrix with a nonzero `fill_value` and passing it to other modules to operate on would break things. I don't think that would need to be fixed, raising an error at most.

**Comment by hameerabbasi** [comment]
Please feel free to raise an issue on the PyData/Sparse repo if you run into any issues!

**Comment by sturlamolden** [comment]
The “empty” elements in a sparse matrix are always zero. That is how a sparse matrix is defined mathematically. As such, it makes no sense to fix something that is not broken.

I would rather suggest you return a dict or ndarray and do the appropriate post-processing. The latter is often the more efficient, as it returns the buffer of the raw C++ std::vector that was collected during the query.

**Comment by adriangb** [comment]
Yeah, I'll do that. It is easier than making any changes. Thank you for the feedback @sturlamolden !
