### ISSUE TITLE
Incorrect version on https://docs.scipy.org/doc/scipy/reference/index.html

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#11401]
https://docs.scipy.org/doc/scipy/reference/index.html currently redirects to scipy 1.2.3 docs.
(This broke the matplotlib doc ci build to to broken intersphinx references.)

**Comment by rgommers** [comment]
Thanks for the report @anntzer, fixed now.

@tylerjereddy `make upload` will do this; it symlinks the the main doc link to whatever release you're uploading. So if you're uploading an older release, you need to comment out that line in the Makefile or undo what you did.

**Comment by tylerjereddy** [comment]
Ah, sorry, noted!

**Comment by anntzer** [comment]
Thanks for the quick resolution :)
