### ISSUE TITLE
Where is the Wiener Filter derived from?

### ISSUE THREAD

**Issue by shamoons** [scipy/scipy#11415]
I am using the Wiener Filter to do speech enhancement (1D data) and while I see the [source code](https://github.com/scipy/scipy/blob/v0.14.0/scipy/signal/signaltools.py#L441), I'm unsure where it was derived from. Is there an academic or authoritative source that it came from?

**Comment by pv** [comment]
Reading https://scipy.github.io/devdocs/tutorial/signal.html#wiener-filter it's probably the same as wiener2 in Octave/Matlab, whose reference points to Lim, Jae S., Two-Dimensional Signal and Image Processing, Englewood Cliffs, NJ, Prentice Hall, 1990, p. 548.

**Comment by shamoons** [comment]
Thanks for replying so quickly @pv.

**Comment by grapheo12** [comment]
May I look into making the necessary changes in the docstrings and documentation?

**Comment by martinbenes1996** [comment]
Just compared Matlab's `wiener2()` and scipy's `scipy.signal.wiener()`, and they do produce different results (unlike what @pv says).

I managed to make them match by changing the padding for the cross-correlation.
While Matlab uses symmetric (which makes sense), scipy uses zero-fill (at least at 1.10.1), perhaps something to reconsider.


```python
import numpy as np
import typing

def wiener2(
    im: np.ndarray,
    size: typing.Tuple,
    noise: float = None,
) -> np.ndarray:

    # process size
    size = np.asarray(size)
    if size.shape == ():
        size = np.repeat(size.item(), im.ndim)
    NM = np.prod(size)

    # Estimate the local characteristics
    lMean = correlate2d(im, np.ones(size), 'same', 'symm') / NM
    lMean2 = correlate2d(im ** 2, np.ones(size), 'same', 'symm') / NM
    lVar = lMean2 - lMean**2

    # Estimate the noise power
    if noise is None:
        noise = np.mean(lVar)

    # weight the image by noise ratio
    res = lMean + ((lVar - noise) / lVar) * (im - lMean)
    return res
```

**Comment by lucascolley** [comment]
hi @martinbenes1996, if you think it would be a good idea to change the SciPy behaviour, could you open a separate issue? Otherwise, a documentation PR is welcome to note the differences (in general we aren't interested in "here is where we differ from MATLAB", but since the documentation says we're similar to MATLAB here, it would probably be useful to note the differences).
