### ISSUE TITLE
Array copying causes unwanted type casting from complex to float in _array_newton

### ISSUE THREAD

**Issue by kamelstekspizza** [scipy/scipy#11412]
### Problem description
In the first lines of _array_newton where the array p is created by copying the input guess array x0, the handling of complex x0 appears to be broken.  (Lines 377-381)

```   
    try:
        p = np.array(x0, copy=True, dtype=float)
    except TypeError:
        # can't convert complex to float
        p = np.array(x0, copy=True)
```

A complex x0 does not raise a TypeError, but rather you get a ComplexWarning message in the terminal.

```
ComplexWarning: Casting complex values to real discards the imaginary part
```

This means that the p array will be of float type, even when you put in a complex x0. Here is samll example that demonstrates this

```
import numpy as np

t = np.zeros(4,dtype='complex128')
t_1 = 1.0*t
t_2 = np.array(t,copy=True,dtype='float')
print(t.dtype)
print(t_1.dtype)
print(t_2.dtype)
```
The output of this code is
```
demonstrate_type_casting.py:5: ComplexWarning: Casting complex values to real discards the imaginary part
  t_2 = np.array(t,copy=True,dtype='float')
complex128
complex128
float64
```

 The knock-on effect of this is that when the Newton step is performed, you get a TypeError when updating your guesses, since the updates can in general be complex if the function is complex-valued. Here is the error message that I get when I try to run a program that searches for complex roots of a complex-valued function.

#### Code:
```
import numpy as np
import scipy.optimize

def f(x):
    return x + 1+1j
def f_prime(x):
    return 1.0

t = np.ones(4,dtype='complex128')
t *=1j
roots = scipy.optimize.newton(f,t,fprime=f_prime)
print(roots)
```

#### Error message:

```
/home/edvinolofsson/.local/lib/python3.6/site-packages/scipy/optimize/zeros.py:378: ComplexWarning: Casting complex values to real discards the imaginary part
  p = np.array(x0, copy=True, dtype=float)
Traceback (most recent call last):
  File "demonstrate_type_casting.py", line 11, in <module>
    roots = scipy.optimize.newton(f,t,fprime=f_prime)
  File "/home/edvinolofsson/.local/lib/python3.6/site-packages/scipy/optimize/zeros.py", line 273, in newton
    full_output)
  File "/home/edvinolofsson/.local/lib/python3.6/site-packages/scipy/optimize/zeros.py", line 405, in _array_newton
    p[nz_der] -= dp
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('complex128') to dtype('float64') with casting rule 'same_kind'

```

### Possible solution
Simply replacing the try except statement with
```
p = np.array(x0, copy=True)
```
appears to fix the issue for me, but I assume that the code was written like this for a reason.

#### Scipy/Numpy/Python version information:
```
Numpy version 1.8.1
Scipy version 1.4.1
Python version 3.6.9
```

**Comment by pvanmulbregt** [comment]
My assumption is that the dtype=float is to handle the case of starting with an array of integer values, say.  The dtype needed is a type that can store both the provided x0, the desired type of the final result, and the type of any intermediate results.  [To find the zeros of a complex function, the np.array needs to be of complex type, even if all the values are pure real.]
When the code was written perhaps the copy did raise a TypeError but now it only raises ComplexWarning?  If so that would explain why the code was written that way and why it fails now.
