### ISSUE TITLE
Unable to update scipy for Raspberry PI 3 b+ using pip

### ISSUE THREAD

**Issue by galah92** [scipy/scipy#11420]
I can't seem to update my Raspberry Pi to the latest scipy version, not sure where the error is.  It keeps printing `Building wheel for scipy...` but nothing happens.

#### Reproducing code example:

    pi@raspberrypi:~/ $ python3 -m pip freeze | grep scipy
    scipy==1.3.3
    pi@raspberrypi:~/ $ python3 -m pip install --upgrade scipy
    Defaulting to user installation because normal site-packages is not writeable
    Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
    Collecting scipy
    Using cached scipy-1.4.1.tar.gz (24.6 MB)
    Installing build dependencies ... done
    Getting requirements to build wheel ... done
        Preparing wheel metadata ... done
    Building wheels for collected packages: scipy
    Building wheel for scipy (PEP 517) ... /

#### Scipy/Numpy/Python version information:

    pi@raspberrypi:~/ $ python3
    Python 3.7.3 (default, Apr  3 2019, 05:39:12)
    [GCC 8.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
    1.3.3 1.17.4 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)

Thanks.

**Comment by pv** [comment]
There's no binary release for ARM architecture, so it ends up compiling which on the slow rpi processor may take forever. We don't ship binary releases for arm; from the above log you seem to be using piwheels.org binaries (no idea who they are), so you'd need to contact them about it.
