### ISSUE TITLE
linkage / clustering / cut_tree default behavior changed???

### ISSUE THREAD

**Issue by brianpenghe** [scipy/scipy#11424]
I just noticed that the newer version of scipy behaves very different from the older versions when I'm trying to do hierarchical clustering. Do you know where I can check what's changed in the new scipy version? Thanks

**Comment by rgommers** [comment]
@brianpenghe you could look at the history of the `cluster` module (https://github.com/scipy/scipy/commits/master/scipy/cluster). Or PRs labeled with `scipy.cluster`.

If you want a less generic answer, we'll need a few more details or a code snippet. I can't remember any recent behavior changes we made on purpose.
