### ISSUE TITLE
Add LAPACK's ZUNCSD cosine sine decomposition

### ISSUE THREAD

**Issue by balopat** [scipy/scipy#11429]
**Is your feature request related to a problem? Please describe.**

I would like to use Cosine Sine decomposition in certain quantum compilation algorithms to decompose 3 qubit circuits - if this project of mine succeeds this will be implemented in Google's [Cirq](https://github.com/quantumlib/Cirq/issues/451). CSD is Central to the [algorithm](https://arxiv.org/abs/quant-ph/0406176). I do have a prototype working with https://github.com/anuesseler/pycsd however I believe SciPy would be a great place for this function. 

**Describe the solution you'd like**

As scipy already has a mature process of importing and distributing compiled LAPACK functions, I would like to have ZUNCSD exposed through scipy.linalg. (Eventually maybe it would be great to have a higher level implementation of CSD amongst the other matrix decompositions.) I believe other python based quantum frameworks could benefit from having zuncsd exposed this way. 

**Describe alternatives you've considered**

Alternatives considered: 

- [transpile from LAPACK](http://www.netlib.org/lapack/explore-html/de/d0d/zuncsd_8f_source.html) ZUNCSD  with dependencies or [reimplement from the original paper](https://arxiv.org/abs/0707.1838) myself  - this seems very laborious and probably going to end up being significantly slower - maybe I could cut some corners by limiting to 8x8 unitaries. 
- add fortran wrapper dependency inspired by https://github.com/anuesseler/pycsd to Cirq. This will be the first dependency there to introduce fortran compilation within Cirq that would complicate the build system there. I think this would be very hard to push through. 
- fork / pick up https://github.com/anuesseler/pycsd and publish a separate library as a dependency - this is possible but in the end but wouldn't be that much different from Cirq maintaining this code in the end - also it has GPL3 licensing so it won't work verbatim for us. 

**Additional context (e.g. screenshots)**

I am open to raise a PR for this (guidance is welcome if you are open to adding this).

**Comment by ilayn** [comment]
This sounds nice. We need to add also sorcsd, dorcsd, and cunscd as a group. @mdhaber Is this along with your lapack project?

**Comment by balopat** [comment]
@mdhaber if you're okay to provide feedback I'm happy to give this a try and open a PR

**Comment by mdhaber** [comment]
No, this is not on the docket. Go for it! Thanks @balopat!

**Comment by balopat** [comment]
@ilayn @mdhaber is it okay to limit my scope to `cunsd` and `zuncsd` or at least to separate the unitary from the orthogonal case implementation into two separate PRs? How strong is the convention that the "whole family" of functions need to go in together? 

Besides the selfish reason that `zuncsd` is my immediate need: 

* I managed to get `zunscd` and `cuncsd` work, but not `s/dorcsd`
* `s/dorcsd` require a different number of arguments (lrwork and rwork are missing compared to ` z/cunsd` - so they do need a separate wrapper - I believe that I have the right ones - but I might have messed up something,
* s/dorcsd` always return the identity matrix for any orthogonal matrix that I pass in. 

It takes a long time for me to get through these issues and investigate them given beginner level familiarity with fortran / py2f and even CSD.

**Comment by mdhaber** [comment]
@balopat where did your most recent message go? I got an email but I don't see it here.

**Comment by balopat** [comment]
Ah sorry, yes, I removed the comment as I found a bug in my test code. Maybe I should have just hidden it/edited it, sorry for the confusion! 
In the end it's not that bad, I can do them together. I have a working prototype for all four. Now I'm working on making the wrappers and the way I call the methods "scipy"-esque. 

I have a couple of issues that I'd love to get guidance on: 
- `c/zuncsd` has two workspace query parameters: LWORK and LRWORK. They can respond with two arrays. I see `__compute_lwork` is used and the `_lwork` & `fortranname` convention for methods that have a single `lwork` parameter. How would you suggest going about using multiple workspaces? 
- `s/dor/c/zuncsd` has IWORK - do we need to return that, or is it okay to intent(hide) it? 
- callstatement pass by reference or value currently is stilly mystical to me, and there is no guidance on the scipy wiki nor in the f2py docs as far as I can tell - can you point me to a guide around this? 

Thank you!

**Comment by ilayn** [comment]
> How would you suggest going about using multiple workspaces?

If you set all work parameters to -1 and expose them then you get all at once see for example `?heevd_lwork` 

https://github.com/scipy/scipy/blob/master/scipy/linalg/flapack_sym_herm.pyf.src#L195-L219

> s/dor/c/zuncsd has IWORK - do we need to return that, or is it okay to intent(hide) it?

All work vars are hidden except for `xxxx_lwork` ones.

> can you point me to a guide around this?

It is indeed a black magic but if you make an example we can have a look right away. You can basically follow the existing examples. Scalars and internal arrays almost always pass by reference.

**Comment by balopat** [comment]
`heevd_lwork` returns three arrays, however only one is used to pass in during the actual `heevd` call, `lwork`, the others are by default calculated? 

https://github.com/scipy/scipy/blob/6bb954d3ce5c743b008bc9036dc29e6f34640b80/scipy/linalg/flapack_sym_herm.pyf.src#L182-L190

and here is the python side logic with `_compute_lwork` only returning `lwork` and only that is used in the `lwork_args`: 

https://github.com/scipy/scipy/blob/6bb954d3ce5c743b008bc9036dc29e6f34640b80/scipy/linalg/decomp.py#L555-L560

Maybe I'm misinterpreting it, but it looks like heevd can "get away with this" because of the default values for `lrwork` `1+5*n+2*n*n:n` and `iwork`. However, `c/zuncsd` don't have good defaults values for `lrwork`.

**Comment by balopat** [comment]
`heevd_lwork` returns three arrays, however only one is used to pass in during the actual `heevd` call, `lwork`, the others are by default calculated? 

https://github.com/scipy/scipy/blob/6bb954d3ce5c743b008bc9036dc29e6f34640b80/scipy/linalg/flapack_sym_herm.pyf.src#L182-L190

and here is the python side logic with `_compute_lwork` only returning `lwork` and only that is used in the `lwork_args`: 

https://github.com/scipy/scipy/blob/6bb954d3ce5c743b008bc9036dc29e6f34640b80/scipy/linalg/decomp.py#L555-L560

Maybe I'm misinterpreting it, but it looks like heevd can get away with this because of the default values for `lrwork` `1+5*n+2*n*n:n` and `iwork`. However, `c/zuncsd` don't have good defaults values for `lrwork`.

**Comment by balopat** [comment]
> All work vars are hidden except for xxxx_lwork ones.

Ah, I just reread this. So just for my curiosity - LWORK contains all the information necessary then for all the other workspaces?

**Comment by ilayn** [comment]
Maybe `heevd` was a bad example because those particular arrays have default and fixed sizes. Sorry about that. I'll find a better example where all of them are exposed in the lwork query and all hidden in the actual call.

**Comment by ilayn** [comment]
Let's try with evr for example

https://github.com/scipy/scipy/blob/6bb954d3ce5c743b008bc9036dc29e6f34640b80/scipy/linalg/flapack_sym_herm.pyf.src#L765-L772

Here you see that liwork and lwork are optional input vars, actual arrays are hidden. But if you look at its lwork counterpart it is the other way around 

https://github.com/scipy/scipy/blob/6bb954d3ce5c743b008bc9036dc29e6f34640b80/scipy/linalg/flapack_sym_herm.pyf.src#L805-L810

**Comment by balopat** [comment]
Thanks @ilayn - I opened a Draft PR for some initial feedback, this is how I used _lwork: 

https://github.com/scipy/scipy/pull/11524/files#diff-0547d172b04a54a4327aa6280727306cR130-R152
