### ISSUE TITLE
run_dualannealing passes bounds incorrectly in benchmarks/optimize.py

### ISSUE THREAD

**Issue by cjekel** [scipy/scipy#11438]
I was trying to run the optimization benchmarks on the dual annealing algorithm, when I was getting this error:
```
in dual_annealing
lu = list(zip(*bounds))
TypeError: type object argument after * must be an iterable, not NoneType
```
It turns out [run_dualannealing](https://github.com/scipy/scipy/blob/40a5c7cd6235bab123c38c89715a3b9261b63803/benchmarks/benchmarks/optimize.py#L191) in benchmarks/benchmarks/optimize.py isn't correctly passing the optimization bounds to dual_annealing. 

The code is:
```python
        res = dual_annealing(self.fun,
                             None,
                             self.bounds)
```

However it should be

```python
        res = dual_annealing(self.fun,
                             self.bounds)
```

**Comment by andyfaff** [comment]
I wonder how this happened, but the changes look correct.

**Comment by tylerjereddy** [comment]
@cjekel Feel like submitting a PR? :)
