### ISSUE TITLE
optimize.brute range doesn't work correctly

### ISSUE THREAD

**Issue by uzhao** [scipy/scipy#11445]
I set range as [1, 3], but output is 4.71240234

#### Reproducing code example:
>>> opt.brute(np.sin, [(1, 3)])
array([4.71240234])
>>> opt.brute(np.sin, [(1, 5)])
array([4.71241648])
>>> opt.differential_evolution(np.sin, [(1, 3)])
     fun: 0.14112716960409583
 message: 'Optimization terminated successfully.'
    nfev: 212
     nit: 13
 success: True
       x: array([2.99999277])

#### Scipy/Numpy/Python version information:
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
... 
1.3.1 1.17.2 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

**Comment by andyfaff** [comment]
The behaviour you see is expected. If you set `finish=None` then you will get what you expect:
```
brute(np.sin, [(1, 3)], finish=None)
3.0
```

If `finish=fmin` (default) a Nelder-Mead minimization is carried out after the brute search has finished. This is an unbounded minimization.

The documentation [states](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.brute.html#scipy.optimize.brute):

> Note that when finish is not None, the values returned are those of the finish program, not the gridpoint ones. Consequently, while brute confines its search to the input grid points, the finish program’s results usually will not coincide with any gridpoint, and may fall outside the grid’s boundary. Thus, if a minimum only needs to be found over the provided grid points, make sure to pass in finish=None.

**Comment by 0todd0000** [comment]
I encountered the same problem and found this thread. Shouldn't `finish` be `None` by default?  Or at least the documentation updated to explain the polishing procedure?

My objective function raises an error when the value is outside the bounds (0,1), and I had set the bounds at (0,1), but encountered an error because, I found out after digging: the default `brute` polishing procedure pushes outside the (0,1) range. This is very confusing default behavior.

**Comment by andyfaff** [comment]
The documentation fully describes this behaviour.

**Comment by 0todd0000** [comment]
The documentation currently states:

> Minimize a function over a given range by brute force.

> Uses the “brute force” method, i.e., computes the function’s value at each point of a multidimensional grid of points, to find the global minimum of the function.

> The function is evaluated everywhere in the range with the datatype of the first call to the function, as enforced by the vectorize NumPy function. The value and type of the function evaluation returned when full_output=True are affected in addition by the finish argument (see Notes).

> The brute force approach is inefficient because the number of grid points increases exponentially - the number of grid points to evaluate is Ns ** len(x). Consequently, even with coarse grid spacing, even moderately sized problems can take a long time to run, and/or run into memory limitations.

There is nothing stated about polishing, there is only a reference to the notes.

In my view it would be much clearer to set `finish` to `None` by default.
