### ISSUE TITLE
Wrongly typed comparison in integrate.quad

### ISSUE THREAD

**Issue by felixhekhorn** [scipy/scipy#11448]
I believe there is an trivial typo in the `integrate.quad` implementation:

https://github.com/scipy/scipy/blob/832bdf3b0378f05bd0f74ff5f00464524729c6d8/scipy/integrate/quadpack.py#L385

The comparison to `a` should be a `a == - Inf`. After

https://github.com/scipy/scipy/blob/832bdf3b0378f05bd0f74ff5f00464524729c6d8/scipy/integrate/quadpack.py#L338

`a` should be definitely smaller then `b` and i.e. smaller than `Inf`. This line is correct:
https://github.com/scipy/scipy/blob/832bdf3b0378f05bd0f74ff5f00464524729c6d8/scipy/integrate/quadpack.py#L368

**Comment by ev-br** [comment]
Indeed, looks like a typo. Care to send a PR with the fix?

**Comment by felixhekhorn** [comment]
see #11582
