### ISSUE TITLE
integrate.quad epsabs, epsrel

### ISSUE THREAD

**Issue by tyomich** [scipy/scipy#11451]
First up, thanks for the amazing tool that the scipy is. It is hugely appreciated.

I have recently encountered an issue using integrate.quad and in particular its epsabs/epsrel options, which github search shows have been raised concern of before though apparently not in the aspect I am worried about.

Specifically, the accuracy estimate returned by quad is above the value requested by epsabs, and the value specified in epsrel appears to be ignored altogether. The issue appears to affect integrands that are unbound (though integrable). The toy example I can provide is the following:
`
def ga(x):
    return np.exp(-x*x/2)/np.sqrt(1-x)

for epsabs in [1e-5, 1e-11, 1e-12, 1e-20]:
    res=quad(ga, 0, 1, epsabs=epsabs)
    print '%50.45f'%res[0], res[1]
`

resulting in 

> 1.555475384971726215965759365644771605730056763 5.73287873595e-06
   1.555475384971473085116144829953555017709732056 2.27595720048e-12
   1.555475384971473085116144829953555017709732056 2.27595720048e-12
   1.555475384971473085116144829953555017709732056 2.27595720048e-12

The reason I'm going rather low (some would say ridiculously so) in the target accuracy is that the results of the actual integration I am doing (a bit cumbersome so not quoting here) span a wide range in logarithm, and specifying epsrel does not seem to affect the results of that integration at all (it does so for the example above, where epsabs can be replaced with epsrel to the exact same effect).

An example involving a regular function is as follows:
`
def gg(x):
    return np.exp(-x*x/2)

res=quad(gg, 0,1, epsrel=1e-2)
print '%60.55f'%res[0], res[1]
res=quad(gg, 0,1, epsrel=1e-50)
print '%60.55f'%res[0], res[1]
print '%60.55f'%(np.erf(1*np.sqrt(2)/2)*np.sqrt(np.pi/2.))
`

>    0.8556243918921490054785294887551572173833847045898437500 9.4993390031e-15
   0.8556243918921490054785294887551572173833847045898437500 9.4993390031e-15
   0.8556243918921488944562270262395031750202178955078125000

The accuracy appears to be estimated correctly but this estimate is above the requested level.

I am not entirely confident I am using these parameters as intended, thus not reporting the issue as a bug but in that case it might perhaps be worth explaining their purpose (and limitations of their use) in greater detail in the documentation. The interaction of epsabs/epsrel mentioned in a recent thread is also somewhat obscure.

Thank you.

**Comment by caos21** [comment]
I think what is happening in your first example is that `epsrel` has a default value of  `1.49e-8`.
quad compares the accuracy against the max of the tolerances `epsrel`, `epsabs`,
as in the function `max_error` below:

```
import numpy as np

from scipy.integrate import quad

def ga(x):
    return np.exp(-x*x/2)/np.sqrt(1-x)

def max_error(i, epsabs, epsrel):
    return np.maximum(epsabs, epsrel*np.abs(i))

epsrel = 1.49e-8
for epsabs in [1e-5, 1e-11, 1e-12, 1e-20]:
    res = quad(ga, 0, 1, epsabs=epsabs, epsrel=epsrel)
    print("i={:45.45}, abserr={:12.5}, epsabs={:8.5}, epsrel={:8.5}, max_error={:12.5}".format(res[0], res[1], epsabs, epsrel, max_error(res[0], epsabs, epsrel)))

i=1.55547538497172621596575936564477160573005676, abserr=  5.7329e-06, epsabs=   1e-05, epsrel=1.49e-08, max_error=       1e-05
i=1.55547538497147308511614482995355501770973206, abserr=   2.276e-12, epsabs=   1e-11, epsrel=1.49e-08, max_error=  2.3177e-08
i=1.55547538497147308511614482995355501770973206, abserr=   2.276e-12, epsabs=   1e-12, epsrel=1.49e-08, max_error=  2.3177e-08
i=1.55547538497147308511614482995355501770973206, abserr=   2.276e-12, epsabs=   1e-20, epsrel=1.49e-08, max_error=  2.3177e-08
```
Note that the returned `abserr` is smaller than `max_error` for these cases.
If I set `epsrel=0` I got:

```
epsrel = 0.0
for epsabs in [1e-1, 1e-2, 1e-3, 1e-5, 1e-12]:
    res = quad(ga, 0, 1, epsabs=epsabs, epsrel=epsrel)
    print("i={:45.45}, abserr={:12.5}, epsabs={:8.5}, epsrel={:8.5}, max_error={:12.5}".format(res[0], res[1], epsabs, epsrel, max_error(res[0], epsabs, epsrel)))

i=1.55547538497172621596575936564477160573005676, abserr=  5.7329e-06, epsabs=     0.1, epsrel=     0.0, max_error=         0.1
i=1.55547538497172621596575936564477160573005676, abserr=  5.7329e-06, epsabs=    0.01, epsrel=     0.0, max_error=        0.01
i=1.55547538497172621596575936564477160573005676, abserr=  5.7329e-06, epsabs=   0.001, epsrel=     0.0, max_error=       0.001
i=1.55547538497172621596575936564477160573005676, abserr=  5.7329e-06, epsabs=   1e-05, epsrel=     0.0, max_error=       1e-05
i=1.55547538497137316504392856586491689085960388, abserr=  5.0915e-13, epsabs=   1e-12, epsrel=     0.0, max_error=       1e-12
```
 Another possible approach to control the accuracy is to set `epsabs=0`, and vary `epsrel`.
Conversely, in your second example, `epsabs` has the same default value and the accuracy
holds.
```
i=0.855624391892149005478529488755157217383384705, abserr=  9.4993e-15, epsabs=1.49e-08, epsrel=    0.01, max_error=   0.0085562
i=0.855624391892149005478529488755157217383384705, abserr=  9.4993e-15, epsabs=1.49e-08, epsrel=   1e-10, max_error=    1.49e-08
i=0.855624391892149005478529488755157217383384705, abserr=  9.4993e-15, epsabs=1.49e-08, epsrel=   1e-50, max_error=    1.49e-08
```
I suggested to change the documentation #11450

**Comment by tyomich** [comment]
Thank you Benjamin! This solved my problem, and I believe the documentation update will help many others avoid it.
