### ISSUE TITLE
Normalisation requirement for `Wn` unclear in `scipy.signal.butter`

### ISSUE THREAD

**Issue by Kadabash** [scipy/scipy#11452]
In the documentation for `scipy.signal.butter`, I think it is unclear (at least to users who are not domain experts) that the `Wn` parameter behaves very differently depending on whether `fs` is specified or not.

If `fs` is specified, then `Wn` will be in the same units as `fs` (for digital filters). This is clearly described in the documentation of `Wn`.

However, if `fs` is *not* specified (it is optional), then the user must normalise `Wn` **themselves**.
I think that does not immediately become clear when looking at the documentation for `Wn`:
```
For digital filters, Wn are in the same units as fs. 
By default, fs is 2 half-cycles/sample, so these are normalized from 0 to 1,
where 1 is the Nyquist frequency. (Wn is thus in half-cycles / sample.)
```
The last sentence is especially confusing since `fs` is `None` by default.

Could this be made a little more explicit?

**Comment by mdhaber** [comment]
Good first issue for someone familiar with the math.

**Comment by Yash621** [comment]
Hello Sir @mdhaber , can you guide me on this? I would like to work on this issue

**Comment by mdhaber** [comment]
@Yash621 sorry I missed your note. Looks like this was taken care of.
