### ISSUE TITLE
Shouldn't data type of KDE evaluation should be like in the input data?

### ISSUE THREAD

**Issue by lschwetlick** [scipy/scipy#11464]
Currently, if I run a kde estimation on some data, the output data is not the same data type as the input data. 

```
x_locs = [33, 111, 11, 94]
y_locs = [49, 17, 58, 106]
k = kde.gaussian_kde([x_locs, y_locs], bw_method="scott")
xi, yi = np.float128(np.mgrid[0:128, 0:128])
zi = k(np.vstack([yi.flatten(), xi.flatten()]))
zi = zi.reshape(xi.shape)
```

In the example, even though `xi` and `yi` are `float128`, `zi` is `float64`. The way I see it, it would be nice if the data type were consistent between input and output. 

The reason is, I think, that the result matrix is always initalized as regular float.
https://github.com/scipy/scipy/blob/master/scipy/stats/kde.py#L242 

Is there a reason why we shouldn't use the input data type here? If not, it looks like a simple fix, I can try to make a pull request!

# Version Info
Python 3.8
Numpy 1.18.1
Scipy 1.4.1

**Comment by rgommers** [comment]
Thanks for the report @lschwetlick. That looks like an inconsistency indeed, a PR is very welcome.
