### ISSUE TITLE
Wrong error message from scipy.linalg.lapack.dgtsv

### ISSUE THREAD

**Issue by mikeWShef** [scipy/scipy#11466]
scipy.linalg.lapack.dgtsv gives the error:

error: failed in converting 1st argument `dl' of _flapack.dgtsv to C/Fortran array

When the array is the wrong length. 

Code to reproduce:

```
>>>from scipy.linalg.lapack import dgtsv
>>>dgtsv(np.array([1,2,3,4]), np.array([1,2,3,4]), np.array([1,2,3]), np.array([1,2,3,4]))
error: ....
```

```
>>>dgtsv(np.array([1,2,3]), np.array([1,2,3,4]), np.array([1,2,3]), np.array([1,2,3,4]))
```

works fine

**Comment by ilayn** [comment]
Hi @mikeWShef Lapack errors are generic and handled by `f2py` module of NumPy hence there won't be a custom explanation for the errors other than which argument has triggered the error. 

Here we should have added a better argument checker that would print a slightly less ugly message but didn't. If you wish to add a PR is more than welcome otherwise I'll mark as good first issue to attract potential contributors.

**Comment by mikeWShef** [comment]
It seemed like a simple problem and I tried to have a look at the code but couldn't even find where the function is defined, I clearly have a lot to learn about wrapping fortran code. If you can point me in the right direction I will have a try.

**Comment by ilayn** [comment]
It is divided into a couple of files but this one lives in 

https://github.com/scipy/scipy/blob/master/scipy/linalg/flapack_gen_tri.pyf.src

But normally the checks are done like this 

https://github.com/scipy/scipy/blob/8dba340293fe20e62e173bdf2c10ae208286692f/scipy/linalg/fblas_l2.pyf.src#L383-L411

You don't need to learn all the stuff regarding Fortran wrappers but you can try yourself what would be a nice check.

**Comment by caos21** [comment]
scipy 1.4.1 gives the following error:
```
ValueError: 0-th dimension must be fixed to 3 but got 4
```
which is OK.

**Comment by melissawm** [comment]
Is this still relevant or is the error message above sufficient?

**Comment by mdhaber** [comment]
The error message for several versions has been:
```
ValueError: _flapack._flapack.dgtsv: failed to create array from the 1st argument `dl` -- 0-th dimension must be fixed to 3 but got 4
```
The correct size of each array is [determined from the second argument](https://github.com/scipy/scipy/blob/ada2bdb797b3e04d6b1f139971bca2612fd5bfce/scipy/linalg/flapack_gen_tri.pyf.src#L7), `d`. In this case, `d` has four elements, and according to [the documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lapack.dgtsv.html), `dl` needs one less. So the error message seems accurate.
