### ISSUE TITLE
Filter radius as optional argument for gaussian_filter1d/gaussian_filter

### ISSUE THREAD

**Issue by jeastrid** [scipy/scipy#11475]
Is it possible for the `gaussian_filter1d` and `gaussian_filter` functions to include an optional argument for kernel size? I see in [https://github.com/scipy/scipy/blob/v1.4.1/scipy/ndimage/filters.py#L214](https://github.com/scipy/scipy/blob/v1.4.1/scipy/ndimage/filters.py#L214) that the kernel size is determined from the values of `sigma` and `truncate`, but it would be nice for the user to be able to provide the function with the desired `radius.` Perhaps the unspecified `truncate` would be calculated based on the given `radius`, and a warning/error would be issued if the user attempts to provide all three arguments (`sigma`, `radius`, and `truncate`).

**Comment by rgommers** [comment]
Thanks for the suggestion @jeastrid. This is now implemented.
