### ISSUE TITLE
scipy.wavefile supports >2 channels !

### ISSUE THREAD

**Issue by bjarthur** [scipy/scipy#11497]
the docs for `write` say only 1 and 2 channels are supported.  for `read` nothing is said regarding the number of channels.  but the simple test script below shows they both support at least 3.  is this by chance?  will it continue to work in future?  is it supported??  i hope so!!  and if so, maybe update the docs.

```
import scipy.io.wavfile
import numpy as np

d = np.random.randint(10, size=(10,3))
scipy.io.wavfile.write("foo.wav", 8000, d)
fs, dp = scipy.io.wavfile.read("foo.wav")
np.all(d==dp)
```

**Comment by endolith** [comment]
Yes, channels are supported, theoretically up to 65,535

https://github.com/scipy/scipy/blob/master/scipy/io/wavfile.py#L416

https://github.com/scipy/scipy/blob/master/scipy/io/wavfile.py#L693

The documentation says 

>  To write multiple-channels, use a 2-D array of shape (Nsamples, Nchannels)

and it has said that for over a decade...

I'll add a line to the read() function about the shape of the data return
