### ISSUE TITLE
Error performing kronecker product between large sparse vectors

### ISSUE THREAD

**Issue by weiT1993** [scipy/scipy#11494]
My issue is about ...
Kronecker product does not handle large sparse vectors.
#### Reproducing code example:

```
import numpy as np
from scipy.sparse import random, kron
from time import time

np.random.seed(10)

sparse_A = random(1, 2**16, format='csr', density=0.1)
sparse_B = random(1, 2**16, format='csr', density=0.1)

begin = time()
scipy_kron = kron(sparse_A,sparse_B)
print('sparse took %.2f seconds'%(time()-begin))
```

#### Error message:

```
Traceback (most recent call last):
  File "sparse_test.py", line 12, in <module>
    scipy_kron = kron(sparse_A,sparse_B)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/scipy/sparse/construct.py", line 355, in kron
    return coo_matrix((data,(row,col)), shape=output_shape).asformat(format)
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/scipy/sparse/coo.py", line 198, in __init__
    self._check()
  File "/Users/weitang/opt/anaconda3/envs/cc-env/lib/python3.7/site-packages/scipy/sparse/coo.py", line 291, in _check
    raise ValueError('negative column index found')
ValueError: negative column index found
```

#### Scipy/Numpy/Python version information:

```
1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
```

**Comment by ruslanye** [comment]
I've investigated it. Negative values first appear after [this multiplication](https://github.com/scipy/scipy/blob/master/scipy/sparse/construct.py#L339). It seems, overflow happens inside the underlying C code of numpy.

**Comment by ewmoore** [comment]
With sparse arrays of this size the index arrays will be 'int32'.  Since `2**16 * 2**16` doesn't fit in a signed 32-bit integer, `kron` is failing.  The fix here will be to make sure the necessary arrays are 64 bit integers when necessary.  This would push the failure out to `2**32` or so, which i guess is probably far enough.

**Comment by weiT1993** [comment]
And how can I change the index arrays' data type to be 'int64'?
