### ISSUE TITLE
Confusing dendrogram labelling

### ISSUE THREAD

**Issue by sedefe** [scipy/scipy#11492]
`scipy.cluster.hierarchy.dendrogram` has undesirable behavior when `labels` specified

#### Reproducing code example:

```
link = np.array([
    [0, 1, 1.0, 4],
    [2, 3, 1.0, 5],
    [4, 5, 2.0, 6],    
])
plt.figure()
dendrogram(link, labels=list(range(100)))
```

Though there are only 4 linked objects, no error raised. Labels on plot are 96, 97, 98, 99.

#### Scipy/Numpy/Python version information:

1.4.1 / 1.18.1 / sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

**Comment by rgommers** [comment]
This is a small issue - it would be nice to have input validation for the `labels` keyword (as well as for other keywords probably), but basically this is user error (providing the wrong length input for `labels`).

**Comment by sedefe** [comment]
Don't think so.
- Docstring says that `labels` is n-sized list/tuple, but doesn't clearly define what is `n` (it should be defined in `Z` parameter description)
- Suppose `matplotlib.pyplot.plot` would always plot `x` vs `y[-len(x):]` instead of checking their consistency. It would obviously be a big problem.

**Comment by rgommers** [comment]
A fix is very welcome of course. Both your points make sense. Would you like to open a PR?
