### ISSUE TITLE
medfilt produces 0 on input of length 1

### ISSUE THREAD

**Issue by aardvarkkrill** [scipy/scipy#11503]
scipy.signal.medfilt returns zero when filtering a singleton list, rather than the the value in the singleton.  This feels wrong, but if it's as intended, could the documentation be clearer?

```
>>> for i in range(5, -1, -1): print(scipy.signal.medfilt([99]*i))

[ 99.  99.  99.  99.  99.]
[ 99.  99.  99.  99.]
[ 99.  99.  99.]
[ 99.  99.]
[ 0.]           <---- !!
[]
```

#### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
0.19.1 1.13.3 sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
```

**Comment by erheron** [comment]
Hi! I would like to work on this issue. I'll  share some thoughts soon

**Comment by erheron** [comment]
@aardvarkkrill  it's said in documentation that "default size is 3 for each dimension" and "array will be automatically 0-padded", so when You have 1-element array it should add 2 zeros, and then return 0 as median value. I think it maybe be helpful to add such special case for documentation, but this is definitely not an issue, so might be closed.

**Comment by grlee77** [comment]
I agree with @erheron that it is not a bug for the reason explained. Setting `kernel_size=1` gives the expected result @aardvarkkrill was expecting. 

One possibility would be to raise a `UserWarning` for cases when the signal size is less than the `kernel_size`.

**Comment by aardvarkkrill** [comment]
I'm happy to accept that the function agrees with the documentation.  

However, I feel that the filtered list should lie in the same "range of values" as the unfiltered list in some way.  For example, a law like:  medianfilter(k*xs+m) = medianfilter(k*xs)+m   (where xs is a numpy array, k and m are any floats.)  To achieve this I imagine the kernel would have to shrink for shorter inputs, or pad with a median value, or similar)

Anyway, thank you for looking in to it.

**Comment by erheron** [comment]
I'm working on it now to implement suggestion from @grlee77 . PR will come soon :p
