### ISSUE TITLE
Recommend ccache for benchmarks in contributor documentation

### ISSUE THREAD

**Issue by smola** [scipy/scipy#11516]
**Is your feature request related to a problem? Please describe.**
Running benchmarks taking too long (builds).

**Describe the solution you'd like**
It seems `ccache` can speed up the build and it is preferred. But that is not documented at http://scipy.github.io/devdocs/dev/contributor/benchmarking.html#benchmarking-with-asv

Maybe it could be mentioned along the note that currently reads:

> This will take a while, because SciPy has to be rebuilt for each commit! 

**Describe alternatives you've considered**
N/A

**Additional context (e.g. screenshots)**
N/A

**Comment by mdhaber** [comment]
Thanks for the suggestion @smola. Sounds like a good idea. What would you like it to say?

**Comment by rgommers** [comment]
Seems useful. An example of using `ccache` can be found in `tools/docker_dev/workspace_config` (used for Gitpod). `runtests.py` in the root of the repo does use `ccache` too, but in a quite odd way.
