### ISSUE TITLE
Pyflakes generates almost 700 warnings.

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#11529]
Running Pyflakes on the code base generates just under 700 warnings.
Having this many warnings can easily obscure new real warnings.

Some seem somewhat problematic to avoid, such as importing all from a sub package for propagation.  E.g.
```
'from .lapack import *' used; unable to detect undefined names
```
Others are just imports that are no longer used, or assignments that are no longer needed.

Listing the subdirectories here so can check them off as go through the list.

 - [x] _lib  gh-11535
 - [x] cluster gh-11536
 - [x] constants  ~~gh-11537~~ (`sqrt` symbol will be needed again in gh-11343 and/or gh-11345)
 - [x] fft  gh-11538
 - [x] fftpack  gh-11545
 - [x] integrate  gh-11544
 - [x] interpolate gh-11539
 - [x] io  gh-11543
 - [x] linalg gh-11532
 - [x] misc  gh-11540
 - [X] ndimage  gh-11530
 - [x] odr gh-11542
 - [x] optimize  gh-11533
 - [x] signal  gh-11546
 - [x] sparse  gh-11548
 - [x] spatial gh-11547
 - [x] special gh-11541
 - [x] stats  gh-11573
 - [x] final round of cleanup gh-12101

**Comment by rgommers** [comment]
You can add a `# noqa` comment at the end of a line (forgot the exact invokation) to make pyflakes ignore something.

**Comment by pvanmulbregt** [comment]
Adding `# noqa` works for `flake8`, but not for `pyflakes`, AFAICT.

**Comment by rgommers** [comment]
> Some seem somewhat problematic to avoid, such as importing all from a sun package for propagation. E.g.

This tool that @asmeurer recently wrote may help: https://github.com/asmeurer/removestar. He used it to remove `*` imports from the Numba code base, so I suspect it may work for SciPy as well.

If it works without too much manual tweaks, I think this is worth doing.

**Comment by pvanmulbregt** [comment]
I installed it just now and gave it a run. It will remove a few (but only a few) more.  The imports from Fortran and C code give it some difficulty.  
Will also have to check that the currently * imported symbols in some files are not officially in the API (e.g. `mstats.py`)

**Comment by asmeurer** [comment]
It doesn't work for now but it wouldn't be hard to add I think. https://github.com/asmeurer/removestar/issues/9

**Comment by asmeurer** [comment]
It also doesn't have any way to detect explicit star imports for name propagation.

**Comment by pvanmulbregt** [comment]
Declaring done.
Still many warnings remain.
* Modules importing for re-export.
* importing symbols to see if a  module can be Imported.

https://github.com/asmeurer/removestar didn't identify many imports which could be simplified, the remaining ones are needed.

**Comment by WarrenWeckesser** [comment]
Thanks Paul!
