### ISSUE TITLE
scipy.stats.zipf doesn't implement zipf distribution

### ISSUE THREAD

**Issue by jroose-jv** [scipy/scipy#11523]
Scipy implements the zeta distribution for scipy.stats.zipf instead of the zipf distribution.  There is no such thing as scipy.stats.zeta, so this affects users who wish to utilize either distribution.  The current scipy.stats.zipf should be renamed to scipy.stats.zeta and the zipf function should be implemented instead.  

#### Reproducing code example:
From `help(scipy.stats.norm.zipf)` the PMF described by the zipf documentation is the PMF for the Zeta distribution, not the Zipf distribution.  
```
class zipf_gen(scipy.stats._distn_infrastructure.rv_discrete)
 |  A Zipf discrete random variable.
 |  
 |  %(before_notes)s
 |  
 |  Notes
 |  -----
 |  The probability mass function for `zipf` is:
 |  
 |  .. math::
 |  
 |      f(k, a) = \frac{1}{\zeta(a) k^a}
 |  
 |  for :math:`k \ge 1`.
 |  
 |  `zipf` takes :math:`a` as shape parameter. :math:`\zeta` is the
 |  Riemann zeta function (`scipy.special.zeta`)
```

#### More Details
See the Wikipedia page for the zipf and zeta distributions.  Wikipedia calls it out as "Zipf distribution is related to the zeta distribution, but is not identical."
https://en.wikipedia.org/wiki/Zipf%27s_law
https://en.wikipedia.org/wiki/Zeta_distribution

#### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.4.1 1.18.1 sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
```

**Comment by jroose-pp** [comment]
If you want a citation beyond Wikipedia: Section 3.5.6 of "Probability, Statistics, and Random Processes for Electrical Engineering - Third Edition" by Alberto Leon-Garcia seems to concur with Wikipedia's characterization of the probability mass function for the Zipf distribution.

**Comment by jroose-pp** [comment]
It appears that the zipf distribution described by Wikipedia converges to the zeta distribution as the N parameters approaches infinity.  Maybe this can be fixed in a backward compatible way by adding an optional N parameter where N is finite.  I've also found references that refer to the zeta distribution as the zipf distribution, so perhaps the name isn't too far off the mark for users seeking the zeta distribution.

**Comment by josef-pkt** [comment]
http://mathworld.wolfram.com/ZipfDistribution.html  is the same (the wikipedia zeta distribution linked to this)

AFAICS, from the two wikipedia pages, Their Zipf distribution is just a truncated Zeta distribution.

**Comment by josef-pkt** [comment]
https://www.statisticshowto.datasciencecentral.com/zeta-distribution-zipf/
references two Johnson and Kotz books, but I don't have them right now.

**Comment by mdhaber** [comment]
> I've also found references that refer to the zeta distribution as the zipf distribution, so perhaps the name isn't too far off the mark for users seeking the zeta distribution.

Even the Wikipedia entry for "Zeta" says:
> The terms "Zipf distribution" and the "zeta distribution" are often used interchangeably.

> Maybe this can be fixed in a backward compatible way by adding an optional N parameter where N is finite.

I wish we could, but can we? Shape parameters go first in the parameter list for all distributions; in order to make it backwards compatible it would have to be added to the end. 

Another way we could resolve this in a backwards compatible way would be to add create a new `zipfian` distribution. In any case, I'm working on some code for it.

**Comment by michimalek** [comment]
On Scipy i tried accessing the Zipfian methods but I am not able to find them when using the folliwing command:

import scipy.stats as ss
ss.zipfian()

It always drops the error "AttributeError: type object 'stats' has no attribute called zipfian" although on the Scipy doc there is obviously this entry: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.zipfian.html#scipy.stats.zipfian

Hope someone can help me out here

**Comment by mdhaber** [comment]
What version of SciPy are you using? I think zipfian was added in 1.6.
