### ISSUE TITLE
IIR comb filter

### ISSUE THREAD

**Issue by agamemnonc** [scipy/scipy#11558]
**Describe the solution you'd like**
I think it would be very useful to support the design of IIR comb filters. 

**Describe alternatives you've considered**
The only alternative I could think of would be the use of multiple IIR notch filters, but doesn't seem like a great idea.

**Comment by e-q** [comment]
I think this is a reasonable feature request. Would you be interested in putting together a PR for this?

Incidentally, I notice that the current peak and notch design functions only output TF form, these should get zpk and sos output options as well.

**Comment by agamemnonc** [comment]
Happy to give it a go. Likely that I will need some help at some point.

Also happy to include zpk and sos support for peak and notch filters. Should this go into a separate PR?

**Comment by e-q** [comment]
Yes, a separate PR would be preferable. I'll be happy to review what you put together!

**Comment by skresearcher** [comment]
@agamemnonc @e-q @larsoner I don't see any PR on IIR comb filters. Let me know if I can work on this. I just recently implemented gammatone filters, so I can work on this.

**Comment by larsoner** [comment]
Sure, go for it!

**Comment by agamemnonc** [comment]
@skresearcher Yes, please go for it -- I hardly have any free time these days to spend on this, unfortunately.
