### ISSUE TITLE
irfft/irfft2/irfftn docs are slightly confusing re: input type.

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#11566]
As of scipy 1.4, the docs for fft.irfft{,2,n} start with "Compute the inverse of the n-point DFT for real input." / "Compute the 2-dimensional inverse FFT of a real array." / "Compute the inverse of the N-dimensional FFT of real input.", which is slightly confusing if you're unfamiliar with fft conventions: a superficial reading would suggest that these functions take a real input, but actually the argument to irfft is complex, and it's the output which is real.
(Also, the inconsistency between the use of "DFT" and "FFT" could be avoided.)

(xref https://github.com/numpy/numpy/issues/15622.)

**Comment by peterbell10** [comment]
Some alternative wordings:
- Computes the inverse of `rfft`
- Computes the inverse FFT for a spectrum with Hermitian symmetry
- Computes the inverse FFT with a real output signal

Any of those better?

**Comment by anntzer** [comment]
First two sound good to me.
