### ISSUE TITLE
SciPy compilation does not find ATLAS libraries and FORTRAN compiler

### ISSUE THREAD

**Issue by Marco-Sulla** [scipy/scipy#11562]
I tried to compile Scipy from source, on Lubuntu 18.0.4.3, since I had some problems installing it with `pip`. This is what I've done:

```bash
sudo apt install libatlas-base-dev
pip install pybind11 # the other requirements was already installed
git clone https://github.com/scipy/scipy.git
cd scipy
git clean -xdf
python setup.py config_fc --fcompiler=gfortran-9.2.0 install --user
```

I got these errors:

> [...]
> 
> openblas_clapack_info:
>   libraries openblas,lapack not found in ['/home/marco/Desktop/*******/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
>   NOT AVAILABLE
> 
> [...]
> 
> don't know how to compile Fortran code on platform 'posix' with 'gfortran-9.2.0' compiler

But I have ATLAS libraries:

```bash
[2020-02-20 19:58:38 /usr/lib/x86_64-linux-gnu/atlas $] ll
total 31684
-rw-r--r-- 1 root root  8689590 set 13  2017 libblas.a
lrwxrwxrwx 1 root root       17 set 13  2017 libblas.so -> libblas.so.3.10.3
lrwxrwxrwx 1 root root       17 set 13  2017 libblas.so.3 -> libblas.so.3.10.3
-rw-r--r-- 1 root root  3938440 set 13  2017 libblas.so.3.10.3
-rw-r--r-- 1 root root 12734022 set 13  2017 liblapack.a
lrwxrwxrwx 1 root root       19 set 13  2017 liblapack.so -> liblapack.so.3.10.3
lrwxrwxrwx 1 root root       19 set 13  2017 liblapack.so.3 -> liblapack.so.3.10.3
-rw-r--r-- 1 root root  7073856 set 13  2017 liblapack.so.3.10.3
```

About the FORTRAN compiler, I think I'll remedy with and alias, but it's strange I can't set the compiler name.

I have NumPy 1.18.1 and Python 9.2.0 alpha 3.

**Comment by tylerjereddy** [comment]
To encourage discovery of the appropriate linear algebra backend I often find it useful to setup a local
`~/.numpy-site.cfg`, which you can draft from the `site.cfg.example` in the source code. You can delete all but the `[atlas]` block, and then adjust that block for your system. Make sure it isn't commented out after adjusting.

For Fortran compiler specification, I think I've previously had success with something like this in bash:

`NPY_DISTUTILS_APPEND_FLAGS=1 FC=gfortran-9 F90=gfortran-9 python setup.py install`

**Comment by Marco-Sulla** [comment]
Well, the problem is I would that the ATLAS libraries will be found when I simply do `pip install scipy`.

About `gfortran`, I simply created a symlink. Anyway it's strange that SciPy knows that I have installed GCC 9.2.0 (how?!?) and not gfortran 9.2.0...

**Comment by Marco-Sulla** [comment]
This is the result with Python 3.8.1 on Rasbpian, using simply `pip3.8 install scipy`:

```
    FOUND:
      language = f77
      libraries = ['lapack', 'f77blas', 'cblas', 'atlas', 'f77blas', 'cblas']
      library_dirs = ['/usr/lib/arm-linux-gnueabihf']
      define_macros = [('NO_ATLAS_INFO', -1)]

  [...]

    FOUND:
      language = c
      define_macros = [('HAVE_CBLAS', None), ('NO_ATLAS_INFO', -1)]
      libraries = ['f77blas', 'cblas', 'atlas', 'f77blas', 'cblas']
      library_dirs = ['/usr/lib/arm-linux-gnueabihf']
```

What does it means? The libraries were found or not?

**Comment by rgommers** [comment]
> I got these errors:
> ...
> NOT AVAILABLE

That's not an error, simply part of the build log.

> What does it means? The libraries were found or not?

That means ATLAS was found, but version info could not be determined.

> `NPY_DISTUTILS_APPEND_FLAGS=1 `

That is no longer needed, that's the default from NumPy 1.18.0 onwards.

I don't think there's anything to do here, so I'll close the issue.
