### ISSUE TITLE
[set up dev environment] unable to run runtests.py

### ISSUE THREAD

**Issue by WillTirone** [scipy/scipy#11576]
Hello! 

I'm a first-time contributor and attempting to set up a dev environment by following the instructions here: https://docs.scipy.org/doc/scipy/reference/dev/contributor/quickstart_ubuntu.html#quickstart-ubuntu

on step 19, I'm trying to run the runtests.py file but I am getting the following: 
`scipy/linalg/tests/test_decomp.py::TestEigh::test_eigh_integer realloc(): invalid next size
Fatal Python error: Aborted
` at 21% completed. 

I'm sure this is not an actual bug, so apologies if this isn't the right place to post this, but I really want to contribute to SciPy and I haven't managed to find any sort of fix to this from googling. I also recently installed Ubuntu to go through this set up so there may be some sort of issue there.

**Comment by EverLookNeverSee** [comment]
Hi @WillTirone 
Please provide information below:

- OS information
- Python version
- Pytest version
- SciPy version

**Comment by EverLookNeverSee** [comment]
> on step 19, I'm trying to run the runtests.py file but I am getting the following:
> `scipy/linalg/tests/test_decomp.py::TestEigh::test_eigh_integer realloc(): invalid next size Fatal Python error: Aborted ` at 21% completed.

Have you successfully completed the previous steps?

**Comment by WillTirone** [comment]
Hi @EverLookNeverSee, 

I've completed the previous steps, yes. I was able to successfully do an in-place build and import the dev version of scipy (1.5)

System info: 

1. Ubuntu 18.04.4 LTS (The guide says Ubuntu 16.04 but I assumed the newer version would be okay) 
2. Python 3.7.6 (installed w/ Anaconda) 
3. Pytest: 5.3.5
4. Scipy: 1.5.0.dev0+d607334 (this is inside the virtual env) 

Thank you!

**Comment by person142** [comment]
So the failing part was reworked quite heavily recently in https://github.com/scipy/scipy/pull/11304, so there's a reasonable possibility that it's a real bug. @ilayn WDYT?

**Comment by person142** [comment]
@WillTirone in the meantime, you can try using e.g. the `-s <submodule>` flag to restrict the tests to a particular submodule. If the tests for other submodules pass, then it increases the chance that there's a SciPy bug, and it might also unblock you on whatever you are trying to work on.

**Comment by andyfaff** [comment]
@WillTirone this is an ideal situation for a `git bisect`. if you can find a last known commit that works, it allows you to find the exact commit that broke things. If you can find the submodule that fails the test then that would speed up the process.

**Comment by WillTirone** [comment]
@andyfaff cool! Thanks for the suggestion - per git bisect, it looks like 6bb954d3ce5c743b008bc9036dc29e6f34640b80 is the first bad commit, so it is actually a Scipy issue.

**Comment by andyfaff** [comment]
The bisect may not be perfect if the test failure is not consistent.

**Comment by ilayn** [comment]
This smells like rather an anaconda and/or MKL bug. Also we should be able to make people work with regular virtual environments.

**Comment by WillTirone** [comment]
@andyfaff good point - there was actually one test that gave me 55% before failure that I marked as "good" because it was a different failure point, although i thought marking that as "bad" would obfuscate the issue. 

@ilayn any way to check if its an Anaconda bug? and by regular do you just mean using the virtualenv module or?

**Comment by ilayn** [comment]
@WillTirone yes just creating a virtualenv and installing the dependencies and following the rest.

**Comment by EverLookNeverSee** [comment]
Hello @WillTirone , Could you solve this issue using python virtual environment?

**Comment by WillTirone** [comment]
Hi @EverLookNeverSee, I've been pretty busy this week but I am going to attempt it tomorrow night!

**Comment by WillTirone** [comment]
![image](https://user-images.githubusercontent.com/42592742/75501196-46283880-599d-11ea-8fee-20ec58428a9b.png)

**Comment by EverLookNeverSee** [comment]
@WillTirone 
what is default python version on your system(preinstalled)?
How many python3 interpreter do you have in your venv?
I mean python3.7 and python3.8

**Comment by WillTirone** [comment]
@EverLookNeverSee 2.7 was my default and 3.6 was what I used to run the test - I can attempt with 3.7 as well.

**Comment by EverLookNeverSee** [comment]
@WillTirone 
- Remove your virtual environment
- remove conda environment(completlly)
- keep only one python3 interpreter on your system
- update python3 version to python3.8
- create a new virtual environment using command below:
`python3 -m scipydev /path/to/new/virtual/environment --system-site-packages`
- activate virtual environment using command below:
`source scipydev/bin/activate`
- install these packages:
`pip install cython numpy pytest spyder pybind11`
- check fortran compiler existence on your system using command below:
`gfortran --version`
- fork and clone scipy repository on your system:
`git clone https://github.com/scipy/scipy.git`
- in scipy root directory, run command below in order to build it:
`python3 setup.py build_ext --inplace`
- run scipy tests:
`python3 runtests.py -v`
- run the following command in order to install development version of scipy in your virtual environment:
`python setup.py develop`
- run python3 interpreter and checkout scipy version:
`>>> import scipy`
`>>> print(scipy.__version__)`
the output will be something like this:
**1.5.0.dev0+e27a9c1**

**Comment by WillTirone** [comment]
@EverLookNeverSee thank you! Should I close this issue?

**Comment by EverLookNeverSee** [comment]
@WillTirone Yes, if the problem is solved!

**Comment by EverLookNeverSee** [comment]
> @EverLookNeverSee thank you! Should I close this issue?

@WillTirone 
Your welcome and Good luck.

**Comment by WillTirone** [comment]
> > @EverLookNeverSee thank you! Should I close this issue?
> 
> @WillTirone
> Your welcome and Good luck.

as a last follow up - is there a place to discuss scipy-related issues (other than formally opening an issue) on a slack / discord or something, or just the dev mailing list?

**Comment by rgommers** [comment]
> is there a place to discuss scipy-related issues (other than formally opening an issue) on a slack / discord or something, or just the dev mailing list?

Just the scipy-dev list. Most maintainers have only a few hours per week for SciPy outside of their day job, so a synchronous messaging option like Slack hasn't really been a good option so far.
