### ISSUE TITLE
Update for linprog presolve

### ISSUE THREAD

**Issue by janvle** [scipy/scipy#11570]
As Matt suggested (issue #11515) I've been taking a look at the presolve routine and its reference, the Andersen & Andersen paper.

A&A describes a set of options for trivial simplifications of the problem (some not too trivial, though), numbered (i) - (xvii). The current `_presolve` function handles just a couple of them: 
* zero row in equality constraints (i)
* zero row in inequality constraints (i)
* zero column in both constraints (ii)
* row singleton in equality constraints (v)
* row singleton in inequality constraints (v)
* identical bounds (iv)

A&A also suggest some of these options should be repeated. That currently doesn't happen either. The variables `bounds` and `undo` contain the information for reversing the simplification in `_postsolve`. `_postsolve` als reverses the problem standardization of `_get_Abc` using `bounds`.

I have a couple of considerations and questions with respect to updating `_presolve`:
1. It would be good to redesign the presolve routine in such a way that we can add options one at a time, in a modular way. Right?
2. A&A warn that some options may be computationally heavy, so it may be good to modify the solver option 'presolve'. Instead of just `True` or `False`, we may introduce a numeric level which in- or excludes specific presolve options. Can we do that?
3. Do we know if we can 'match' presolve efforts to an actual solver? What presolve activity is always advantageous? What presolve activities make sense for specific solvers only?
4. I think we should not use `bounds` as carrier of information for reversing `_presolve` (in `_postsolve`). For some A&A options the `bounds`/`undo` implementation will not work anyway. But it is also not elegant to use a problem parameter for this.
5. Where in the process should presolve take place? In the current implementation, it is the first step, but the A&A-options relate to the standard form. That means that we have to 'translate' their options, e.g. to include `A_ub` and `b_ub`. Would it be better to presolve after the standardization?
6. Some A&A options refer to the dual problem - that is not available at the presolve level. (Is it even used? I did not check the specific `linprog` solvers). What to do with these A&A-options?
7. The final A&A options (xiv - xvii) address rank deficiency, but in a rather ad-hoc way it seems to me. Linprog currently implements a more thorough procedure to remove redundant equations, but I have also read the comment in `_remove_redundancy`. What is the proper location to address/check linear dependencies? Immediately before the solver is called? Or can it be done before the standardization in `_get_Abc`? Is there proof that the standardization never introduces linear dependencies?
8. Analyzing matrix rank (or doing a SVD) is necessary, but it also takes time. Are the solver algorithms able to detect (and perhaps repair) linear dependencies in the course of their process more 'cheaply'? I see quite a bit of literature on this subject, which suggests it is a topic worth exploring, but it is outside of my area of expertise.
9. Am I missing something?
 
Regarding `bounds`: I'm confused about the use of `None` and `np.inf` at various locations in the code. Do they have different meanings? Perhaps related to the `_postsolve` process? See 4 above: I would prefer to standardize the use of `(-)np.inf` for an absent bound.

What do you think of this presolve framework?:

Code each A&A option as a separate function `PR`, with:
- 1 input: current values of the problem parameters `pp` = `(c, A_eq, b_eq, A_ub, b_ub, u, l, x0)`
- 3 outputs: modified values of the problem parameters `pp` = `(c, A_eq, b_eq, A_ub, b_ub, u, l, x0)`, a function `REV` to undo this specific modification and a `status` flag (0 : Modification made, 1 : No modification made, 2 : Problem appears to be infeasible, 3 : Problem appears to be unbounded)

The function `REV` is pre-parametrized to carry out the restauration. It has:
- 1 input: current values of the criterion vector, solution, and initial guess `cp` = `(c, x, x0)`
- 1 output: restored values of the criterion vector, solution, and initial guess `cp` = `(c, x, x0)`

The `REV`-functions can be put on a stack for reversing the modifications, as A&A suggest.

Presolve would now work as follows:
1. input: current values of the problem parameters `pp = (c, A_e, b_e, A_f, b_f, u, l, x0)`
2.
```
REVstack = []
```
3. Perform initial presolve routines
```
(pp, REV, status) = PR_1(pp)
if status == 0: REVstack.append(REV)
if status == 2 or 3: raise error infeasible or unbound
```
... and other initial presolve routines in the same way

4. Perform the looped presolve routines
```modifications = True
while modifications:
    modifications = False
    (pp, REV, status) = PR_2(pp)
    if status == 0: REVstack.append(REV), modifiations = True
    if status == 2 or 3: raise error infeasible or unbound
```
... and other presolve routine which must be repeated

5. Perform final presolve routines
```
(pp, REV, status) = PR_3(pp)
if status == 0: REVstack.append(REV)
if status == 2 or 3: raise error infeasible or unbound
```
... and other final presolve routines in the same way

6. output: modified values of the problem parameters `pp = (c, A_e, b_e, A_f, b_f, u, l, x0)`
7. output: `REVstack` containing the functions to reverse the modifications

Postsolve would work like this:

1. input: criterion vector, solution and initial values of the modified problem `cp = (c, x, x0)`
2. apply functions in `REVstack`, last one first
```
for i in range(len(REVstack),-1,-1):
    cp = REVstack[i](cp)
```

3. output: criterion vector, solution and initial guess `cp = (c, x, x0)` in their original context

**Comment by mdhaber** [comment]
Hi @janvle. Thanks for writing this up. I'm very interested in replying to it in detail, but I'm super busy ATM. Let me start with just a few things.

>1. It would be good to redesign the presolve routine in such a way that we can add options one at a time, in a modular way. Right?

Yes. That would be much better than the current monolithic structure.

> 2. A&A warn that some options may be computationally heavy, so it may be good to modify the solver option 'presolve'. Instead of just True or False, we may introduce a numeric level which in- or excludes specific presolve options. Can we do that?

We can, and I think the modular structure you propose would make that possible to introduce at the end. We should do some benchmarking to see if it's important, though; otherwise it might not be worth the time to develop the interface.

> 3. Do we know if we can 'match' presolve efforts to an actual solver? What presolve activity is always advantageous? What presolve activities make sense for specific solvers only?

If I remember correctly, the A&A paper is geared toward use with interior point solvers. I'm not aware of a situation in which the presolve efforts I've already implemented are harmful to simplex solvers, though. All I can think of right now is that revised simplex uses existing column singletons to create its initial basis. I think if we remove all of them in presolve, they will be added back. 

> 4. I think we should not use bounds as carrier of information for reversing _presolve (in _postsolve). For some A&A options the bounds/undo implementation will not work anyway. But it is also not elegant to use a problem parameter for this.

Agreed. I mentioned that I wasn't really happy with `undo`; I think a more explicit "carrier of information for reversing" presolve in postsolve would be great.

> 5. Where in the process should presolve take place? In the current implementation, it is the first step, but the A&A-options relate to the standard form. That means that we have to 'translate' their options, e.g. to include A_ub and b_ub. Would it be better to presolve after the standardization?

I remember thinking at the type that it made more sense to me to separate them because certain activities would be more important for certain types of constraints. But I could be persuaded otherwise.

> 6. Some A&A options refer to the dual problem - that is not available at the presolve level. (Is it even used? I did not check the specific linprog solvers). What to do with these A&A-options?

The dual simplex method is not implemented yet - but it would be good to add it.
I'd have to take a closer look at what you're referring to in order to decide.

> 7. The final A&A options (xiv - xvii) address rank deficiency, but in a rather ad-hoc way it seems to me. Linprog currently implements a more thorough procedure to remove redundant equations, but I have also read the comment in _remove_redundancy. What is the proper location to address/check linear dependencies? Immediately before the solver is called? Or can it be done before the standardization in _get_Abc? Is there proof that the standardization never introduces linear dependencies?

I thought it would be best to do it on the equality constraint matrix, as converting inequality constraints to equality constraints adds an artificial variable and a column singleton that ensures the row is independent (if I'm thinking correctly).

> 8. Analyzing matrix rank (or doing a SVD) is necessary, but it also takes time. Are the solver algorithms able to detect (and perhaps repair) linear dependencies in the course of their process more 'cheaply'? I see quite a bit of literature on this subject, which suggests it is a topic worth exploring, but it is outside of my area of expertise.

I implemented the redundancy removal stuff because redundancies caused problems for the interior point method. I seem to remember that this helped revised simplex find its initial basis, too. I'd be interested in what you're finding, though.

I'll look at the rest later.

**Comment by mdhaber** [comment]
> 9. Am I missing something?
 
Not that I can tell!

> Regarding `bounds`: I'm confused about the use of `None` and `np.inf` at various locations in the code. Do they have different meanings? Perhaps related to the `_postsolve` process? See 4 above: I would prefer to standardize the use of `(-)np.inf` for an absent bound.

Agreed. I'm not sure, but I think this - like the list of tuples form of bounds - was inherited from the original `linprog`. We need to accept `None` from the user, but I would agree that this should be converted to `(-)np.inf` and we should never look back. 

> What do you think of this presolve framework?:

Great! I'm looking forward to reviewing this. My concern is that if you do this all at once in one big PR, this is going to take forever to get reviewed and merged. Can you think of some way to break this up into small pieces, each in its own PR, while keeping the code in working order? I know that may be challenging, but if you can do that, I am much more likely to be able to keep my reviews timely.

**Comment by janvle** [comment]
Thanks @mdhaber, that is quick & clear.

You are right about the need to break this up into smaller pieces. I've given it some thoughts this weekend. This might be the way to do it:
* Standardize `bounds` (into a Nx2 numpy array)
  This involves `_clean_inputs` mainly. There are small changes in a couple of other functions in _linprog_util.py, mainly comments, and a couple of locations where `None`-bounds need to change into `(-)np.inf`.
* Change the bounds/undo reversal mechanism into a stack of reversal functions
  This looks like a limited operation, since it only requires us to keep track of removed (fixed) variables and create functions for reinserting them. `bounds` and `x` can now be kept aligned (same length) in the course of the _presolve process. Changes to `bounds` do not have to be reversed.
* Modularize presolve with separate functions for each technique, and a framework with an initial part, a looped part and a final part
   This is probably the largest change, but it can be done step by step: create the initial/loop/final framework with dummy presolve technique functions. Then implement these functions one by one.
* Review resolving rank deficiency
   I do not know if this needs changing; as I said I'd prefer a general approach over the A&A-approach. But perhaps we need to compare? The A&A-approach may have speed advantages, if empty-rows, empty-columns, duplicate-rows and duplicate-columns occur sufficiently frequently.

I'll try and prepare a PR for the 1st bullet. Would be the 1st time I do that, so might take a while.

**Comment by mdhaber** [comment]
Sounds good!

**Comment by mdhaber** [comment]
Hey @janvle just thought I'd check in. Need anything from me?

**Comment by janvle** [comment]
Not on this PR, no.
I have started the next one (ENH: add a stack of reversal functions to linprog #11691), which passed a couple of checks but resulted in time-outs in a couple of others. I haven't been paying attention the last couple of days, but how do I reinitiate these?

**Comment by mdhaber** [comment]
Oops I missed that. I'll take a look.
