### ISSUE TITLE
Invalid next size error while building scipy

### ISSUE THREAD

**Issue by TakshKamlesh** [scipy/scipy#11580]
I am in the process of following the exact steps as mentioned in the scipy contributer guide in order to obtain a development version of scipy . When I run the code ' python3 runtests.py -v ' on terminal , on after passing 22% of the test , it gives an error : 

scipy/linalg/tests/test_decomp.py::TestEigh::test_eigh_integer realloc(): invalid next size
Fatal Python error: Aborted

Sorry its not really possible to reproduce the error.

Specs :
Ubuntu  :  16.04

**Comment by andyfaff** [comment]
duplicate of #11576

**Comment by TakshKamlesh** [comment]
Thanks
