### ISSUE TITLE
Python 2 code cleanups

### ISSUE THREAD

**Issue by sethtroisi** [scipy/scipy#11584]
I'm excited about removing old code that is no longer supported; e.g. Python 2 and Python <= 3.4(5?)

For Numpy I cleaned up 
* `import six`
* `PY_MAJOR_VERSION` and `PY_VERSION_HEX`
* `NPY_PY3K`
* C module initialization and return
* `getbuffer` and `newbuffer` (I'm not sure  if this is needed in SciPy)
* `__nonzero__` 
* open tar/gz files

For SciPy I also see
* `__Pyx_PyNumber_Divide`

I'm creating this issue to link against for pull requests.

**Comment by ev-br** [comment]
Is this done or is there still something left to do?

**Comment by sethtroisi** [comment]
There may still be a few unknown changes left but everything we know about is finished.
