### ISSUE TITLE
signal.cheby2 and signal.ellip don't produce expected frequency response

### ISSUE THREAD

**Issue by kamocat** [scipy/scipy#11591]
My issue is about the frequency response of Chebyshev II and Elliptic digital filters.
From my input I am expected a low-pass filter, but the result is more like a notch filter. Butterworth and Chebyshev I work as expected.

#### Reproducing code example:

This is a minimal example, but I have a more interactive example in a [gist](https://gist.github.com/kamocat/ec358157a3d11b20074d441744f1912a) where you can look at the filter resulting from different parameters.
```
import numpy as np
import scipy.signal as sig
import scipy.fft as fft
import matplotlib.pyplot as plt

def plot_freq(sos):
  # Plot frequency response and freqz
  w,h = sig.sosfreqz(sos)
  plt.subplot(121)
  plt.semilogy(w,np.absolute(h))
  plt.title("Frequency response")
  plt.subplot(122)
  pulse = np.zeros(1024)
  pulse[0]=1
  h = sig.sosfilt(sos, pulse)
  plt.semilogy(np.absolute(fft.rfft(h)))
  plt.title("FFT of impulse")
  plt.show()

def design(params):
  print(params)
  if params['wp'] < params['ws']:
    btype = 'lowpass'
  else:
    btype = 'highpass'
  print(f'This is a {btype} filter.')
  cheby2 = sig.cheb2ord(
        params['wp'], params['ws'], params['gpass'], params['gstop'])
  print(F'Order: {cheby2[0]}, Corner: {cheby2[1]}')
  sos = sig.cheby2(N=cheby2[0], rs=params['ws'] , Wn=cheby2[1], 
                    btype=btype, output='sos' )
  return(sos)

params = dict()
params['ws']=0.04
params['wp']=0.03
params['gstop']=50
params['gpass']=.1
sos = design(params)
plot_freq(sos)
```

#### Error message:

No errors.

#### Scipy/Numpy/Python version information:
```
1.4.1 1.18.1 sys.version_info(major=3, minor=8, micro=1, releaselevel='final', serial=0)
```

### Graph illustrating the problem
![not_lowpass](https://user-images.githubusercontent.com/175229/75305791-f5c5a500-57fb-11ea-89c7-5e548a772832.png)
As you can see, this isn't really a low-pass filter, unless you wish to filter out Nyquist. It does seem to have a notch around the corner frequency.

As a sidenote, I computed the impulse response and performed an FFT because I wasn't sure if the sosfreqz was at fault.

**Comment by kamocat** [comment]
For comparison, here's a plot from Octave using the following script:
'''
pkg load signal
[b,a] = cheby2(11, 50, 0.4)
w = linspace(0, pi, 512)
freqs(b, a, w)
'''

![octave_cheby2](https://user-images.githubusercontent.com/175229/75306950-57d3d980-57ff-11ea-8973-d6a76f6eaecd.png)
As you can see, this is a low-pass filter,

**Comment by kamocat** [comment]
Huh. Looks like I have a bug in my code.
This works fine:
'''
sos = sig.cheby2(N=11, rs=50, Wn=0.04, output='sos' )
'''

**Comment by larsoner** [comment]
Thanks for figuring it out and following up @kamocat
