### ISSUE TITLE
What's the license for scipy/stats/stats.py?

### ISSUE THREAD

**Issue by detrout** [scipy/scipy#11599]
Starting at the derived version in Dask I saw this header at the top of stats.py

```
# Copyright 2002 Gary Strangman.  All rights reserved
```
Below is a disclaimer that does not seem to grant any redistribution rights.
https://github.com/scipy/scipy/blob/master/scipy/stats/stats.py

I found that a 2005 copy of stats.py had a GPL-2 header
https://web.archive.org/web/20051224003609/http://www.nmr.mgh.harvard.edu/Neural_Systems_Group/gary/python/stats.py

Eventually I found a 2007 notice in the changelog of statlib that said that stats.py was relicensed under the MIT license.
https://code.google.com/archive/p/python-statlib/

I was wondering if stats.py or LICENSE.txt should include a mention of stats.py license history?

Did stats.py ever get relicensed to BSD? or is it still MIT?

**Comment by rkern** [comment]
Gary contributed it to SciPy under the SciPy license.

**Comment by rkern** [comment]
Which is BSD-ish.

**Comment by detrout** [comment]
Ok thanks.

I don't know if anyone else will look for copyright headers in source files and get confused by the disclaimer at the head of stats.py, but would it be worth mentioning that it was contributed under the scipy license?

**Comment by detrout** [comment]
Honestly the above answer is good enough for now.

**Comment by rkern** [comment]
Our licensing information is consolidated in the main `LICENSE.txt`. Exceptions to the rule are listed there. I don't mind people checking our work on a file-by-file basis, but I'm not sure what would help in this case.

We should add a line for Gary in the `THANKS.txt` file, though. That was a big contribution near the start of the project before we started listing that stuff individually.

**Comment by rkern** [comment]
Ah, no, he's there.

**Comment by detrout** [comment]
Ah I didn't check THANKS. I'd just looked in the two LICENSE files
