### ISSUE TITLE
cdf for scipy.stats.multivariate_normal incorrect

### ISSUE THREAD

**Issue by julians89** [scipy/scipy#11597]
Hi scipy community,

Quite confused at the moment. First time stats user here, trying to to something quite trivial but failing.

I'm trying to evaluate a multivariate gaussian on rectangular region. In uncorrelated distribution conditioning a single variable on half the interval e.g. (0, inf) should return probability of .5 not 1!

Python 3.7.1
Scipy 1.4.1

n = 3
mu = np.zeros(n)
cov = np.eye(n)

a = np.full(mu.shape, -np.inf)
a[0] = 0.
b = np.full(mu.shape, np.inf)

cdf_multivariate = scipy.stats.multivariate_normal.cdf(b, mean=mu, cov=cov) \
    - scipy.stats.multivariate_normal.cdf(a, mean=mu, cov=cov)

print ('cdf_mulitvariate')
print (cdf)

#--- Deconstruct to univariates
cdf_univariate = 1.
for i in range(n):
    cdf_univariate *= (scipy.stats.norm.cdf((b[i] - mu[i]) / cov[i, i]) - scipy.stats.norm.cdf((a[i] - mu[i]) / cov[i, i]))

print ('cdf_univariate')
print (cdf_univariate)

#--- Rejection Sampling for sample mean
samples = scipy.stats.multivariate_normal(mu, cov).rvs(10000000)
for i in range(n):
    ids = np.where(np.logical_and(samples[:, i] > a[i], samples[:, i] < b[i]))
    samples = samples[ids]

cdf_sampled = float(samples.shape[0]) / float(10000000)

print ('sampled_cdf: ', cdf_sampled)

cdf for multivariate case returns 1. while both others (corretly) return .5

Any hints what I could do wrong here?

**Comment by andrewfowlie** [comment]
```
cdf_multivariate = scipy.stats.multivariate_normal.cdf(b, mean=mu, cov=cov)
 - scipy.stats.multivariate_normal.cdf(a, mean=mu, cov=cov)
```
this line is in logic error. You have here
```
cdf(inf, inf, inf) - cdf (0, -inf, -inf)
```
you have entered the arguments as though they were the upper and lower bounds for integration. But `cdf (0, -inf, -inf) = 0`, as it is `~ \int_{-inf}^{-inf} ...`. The arguments are always the upper limits of the integral. The lower limits are always -inf.

You should have
```
cdf(inf, inf, inf) - cdf (0, inf, inf) = 1 - cd (0, inf, inf)
```
back in code
```
cdf_multivariate = 1. - scipy.stats.multivariate_normal.cdf([0., np.inf, np.inf], mean=mu, cov=cov)
# gives 0.5 as expected
```

**Comment by mdhaber** [comment]
@julians89 Looks like this issue was resolved so I'll close. Please reopen if you think there is a bug. Thanks!
