### ISSUE TITLE
Version of BSD license not mentioned in a lot of files.

### ISSUE THREAD

**Issue by rahulmohang** [scipy/scipy#11596]
Hello all,

Some of the examples:

scipy-1.4.1.zip/scipy-1.4.1/scipy/sparse/csgraph/tests/test_graph_laplacian.py

In general - scipy-1.4.1.zip/scipy-1.4.1/scipy/sparse/csgraph/tests/*.*

scipy-1.4.1.zip/scipy-1.4.1/scipy/sparse/csgraph/_traversal.pyx

The authors are Gael Varoquaux <gael.varoquaux@normalesup.org> and Jake Vanderplas <vanderplas@astro.washington.edu>.

@GaelVaroquaux , @jakevdp , can you please check this? I would like to know the version of the license as a part of a license evaluation.

**Comment by rgommers** [comment]
@rahulmohang those files were contributed under the SciPy license. both people you pinged are long-time contributors to SciPy.

**Comment by rahulmohang** [comment]
@rgommers , thank you.

**Comment by GaelVaroquaux** [comment]
I confirm what  @rgommers said!
