### ISSUE TITLE
scipy.optimize.linear_sum_assignment returns reverse diagonal indices for constant arrays in 1.4.1, when it should return normal diagonal indices.

### ISSUE THREAD

**Issue by Hongtao-Niro** [scipy/scipy#11602]
`scipy.optimize.linear_sum_assignment` return reverse diagonal indices for constant arrays in 1.4.1. I found this issue when upgrading scipy from 1.3 to 1.41, where this function yields different results. In 1.3 it returns diagonal indices (e.g. [0,0], [1,1], [2,2] ...) while in 1.4.1 it returns reverse diagonal indices (e.g. for array with shpe [20, 20], the returned indices are [0, 19], [1, 18], [2, 17]...).

#### Reproducing code example:

```
import numpy as np
from scipy.optimize import linear_sum_assignment
row_ind, col_ind = linear_sum_assignment(np.ones([20, 20]))
print("row: ", row_ind)
print("col: ", col_ind)
```
For version 1.3, the above prints:
```
row:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
col:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
```
While version 1.4.1 prints:
```
row:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
col:  [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
```

#### Scipy/Numpy/Python version information:
The two scipy versions given by the command `import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)` are:
```
1.4.1 1.16.4 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```
and
```
1.3.0 1.16.4 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by pmla** [comment]
I do not consider this a bug. The documentation states:
> The goal is to find a complete assignment of workers to jobs of minimal cost.

It does not provide any guarantees about which solution will be selected if the optimal solution is degenerate. A square constant matrix has `n!` equally good solutions.

**Comment by pmla** [comment]
@Hongtao-Niro despite my previous comment I made a fix for this which reverts to the old behaviour in #11631.

**Comment by tylerjereddy** [comment]
I merged Peter's adjustment--doesn't hurt to maintain the backwards compatibility I think.

**Comment by Hongtao-Niro** [comment]
Thanks!
