### ISSUE TITLE
Avoid some unnecessary copying in scipy.linalg.blas and scipy.linalg.lapack

### ISSUE THREAD

**Issue by bsxfan** [scipy/scipy#11606]
I am a Python novice, but I have some experience with BLAS / LAPACK via Julia. 

I believe I have uncovered a possible efficiency improvement that could be applied to `scipy.linalg.blas`, but possibly it could also affect `numpy` and any other code that makes similar use of Python to BLAS/LAPACK interfaces.

I believe that some (or all?) of the interface routines in `scipy.linalg.blas` (and maybe also `scipy.linalg.lapack`) are too strict when inspecting matrices for compatibility with BLAS.  Although BLAS requires matrices to have fortran alignment (contiguous columns), it does **not** require the stride along the elements of a row to be equal to the number of rows.  In typical BLAS/LAPACK calls, the stride along rows is called the *leading dimension* and it must be `>=` number of rows. It seems to me that `scipy.linalg.blas` effectively checks for equality here (leading dimension  = number of rows) and if this is not satisfisfied, the matrix is *unnecessarily* copied to a newly allocated matrix where that condition holds.  

For `numpy` arrays, does the `scipy.linalg.blas` code check the `F_CONTIGUOUS` flag for BLAS compatibility? As I show below, this flag seems to be too strict.

Below is an experimental example where I send `numpy` arrays into `blas.dtrmm`. I did not inspect the fortran source code, but I believe my experiment demonstrates this issue, at least for the case of dtrmm.  

The experiment: 
* As control, creates a canonical, fortran-style matrix and shows that it can be updated *inplace* via `dtrmm` (multiplication by a triangular matrix).   
* Creates a *sliced* array view, that in my opinion should still be a valid BLAS argument, but which is then apparently copied, instead of being processed inplace.

(Note: The array strides produced by the code below are in terms of bytes. For the float64 elements, 8 bytes  = 1 float64.)
  
My code is:

```python
import numpy, scipy 
from numpy.random import randn
import scipy.linalg.blas as blas

print("numpy version:",numpy.__version__)
print("scipy version:",scipy.__version__)
print()

m,n = 3,4

A = randn(m,m).T
if A.strides[0]==8: 
    print("A is blas-fiendly, with fortran alignment:")
    print("A.strides = ", A.strides)
    print("Indeed A.flags also show F_CONTIGUOUS: ")
    print(A.flags)
    print()
    
D = randn(n,m).T
print("The same applies to D:")
print("D.flags.f_contiguous = ", D.flags.f_contiguous,"\n")
    
S = randn(m,2*n).T[0:n,:]
if S.strides[0]==8: 
    print("Although the sliced S is still blas-fiendly, with fortran alignment:")
    print("S.strides = ", S.strides)
if not S.flags.f_contiguous:
    print("... its flags do **not** show F_CONTIGUOUS: ")
    print(S.flags)
    print()

Y = blas.dtrmm(1.0, A, D, 
               side = 0, 
               lower = True, 
               trans_a = False, 
               diag = False, 
               overwrite_b = True)
print("in trmm D was copied = ",not Y is D)


Y = blas.dtrmm(1.0, A, S, 
               side = 0, 
               lower = True, 
               trans_a = False, 
               diag = False, 
               overwrite_b = True)
print("in trmm S was copied = ",not S is D)
```

and the output is:

```
numpy version: 1.18.1
scipy version: 1.4.1

A is blas-fiendly, with fortran alignment:
A.strides =  (8, 24)
Indeed A.flags also show F_CONTIGUOUS: 
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
 [some lines omitted]

The same applies to D:
D.flags.f_contiguous =  True 

Although the sliced S is still blas-fiendly, with fortran alignment:
S.strides =  (8, 64)
its flags do **not** show F_CONTIGUOUS: 
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
 [some lines omitted]


in trmm D was copied =  False
in trmm S was copied =  True
```

**Comment by mdhaber** [comment]
Closing as duplicate (or closely related to) gh-9682.
