### ISSUE TITLE
Add wrapper for ?gbsvx

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#11615]
See [NumFOCUS Small Development Grant Proposal 2019 Round 3 proposal](https://www.dropbox.com/s/i24h3j2osol56uf/Small%20Development%20Grant%20-%20LAPACK%20%20%28Condensed%29.pdf?dl=0) for background.

Add wrapper for [?gbsvx](http://www.netlib.org/lapack/explore-html/d3/d49/group__double_g_bsolve_ga5635d8f59dd5ccf4ff36868ecdc20a11.html#ga5635d8f59dd5ccf4ff36868ecdc20a11).

Suggested signature:
```
! x, ab, afb, ipiv, equed, r, c, rcond, ferr, berr, work, info  = gbsvx(ab, kl, b, fact="E", trans="N", afb=None, ipiv=None, equed=None, r=None, c=None, overwrite_ab=False, overwrite_b=False, overwrite_afb=False)
```
I don't see any reason to return `iwork` as it is undocumented.
I don't see any reason to return `b`. If you think it should be returned, we should check that it is the input `b` modified by `r` or `c` (see documentation for `b` on exit).
I think that given `ab` and `kl`, we can figure out `ku`, so we don't need to accept `ku` as an input. Alternatively, we could only accept `ku` and not `kl`. I don't really want to accept both only to have to raise an error if they are not consistent with the dimensions of the matrix.

Test idea w/ `fact = 'E'` and `fact = 'N'`:

- Generate random banded matrix `A`
- Convert to banded form `AB`
- Generate random solution `x`
- Generate `b` from `A@x`
- Solve using `?gbsvx`
- Compare solution from `?gbsvx` against known `x`
- Check `info=0`
- Convert `AFB` into `L` and `U` and compare against `A`. With `EQUED!='N'`, I think we'll need to undo the equilibration at the end using outputs `R` and/or `C` (depending on `EQUED`).
- Maybe just verify that `rcond` is a scalar and `ferr`/`berr` are arrays with the right shape? `work[0]` should not be tiny.

Test idea w/ `fact = 'F'` and `EQUED='N'`:

- Generate random banded matrix `A`
- Convert to banded form `AB`
- Factor `AB` with [`?dgbtrf`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lapack.dgbtrf.html#scipy.linalg.lapack.dgbtrf) to generate `AFB`
- Generate random solutions `x`
- Generate `b` from `A@x`
- Solve system using `?gbsvx`, providing `AFB`, `ipiv`,
- Check `info=0`
- Compare solution from `?gbsvx` against known `x`
- Maybe just verify that `rcond` is a scalar and `ferr`/`berr` are arrays with the right shape? `work[0]` should not be tiny.

With `EQUED='R'`, `'C'`, or `'B'`, testing is same as with `fact = 'F'` and `EQUED='N'` except that `A` needs to be equilibrated and `r` and/or `c` need to be provided as inputs. I assume that the matrices don't actually need to be _properly_ equilibrated, so I suggest that we create our own (random) `r` and `c` to "equilibrate" the matrix before converting to banded form. If things don't work out, we can try using [`?geequb`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lapack.dgeequb.html#scipy.linalg.lapack.dgeequb) to equilibrate properly (as `?gbequ` is not wrapped).

Be sure to perform similar tests for the different `trans` options.
Also test for singular matrix (`info>0`, `rcond~0`, and I think `work[0]~0`) and for incorrect/incompatible array sizes.

Also: implement examples from the [NAG manual](https://www.nag.com/numeric/fl/nagdoc_latest/html/f07/f07bbf.html) as additional tests.

**Comment by mdhaber** [comment]
The outline above might not be perfect. I've certainly skipped some instructions that I think can be figured out from documentation (like converting to/from banded form, undoing equilibration, etc.). If you run into trouble on any part, let me know and I'll try to fill in the blanks.

**Comment by mdhaber** [comment]
@swallan did you think you were done? : )

**Comment by swallan** [comment]
Omg! Another!

**Comment by Kai-Striega** [comment]
> I think that given ab and kl, we can figure out ku, so we don't need to accept ku as an input. Alternatively, we could only accept ku and not kl. I don't really want to accept both only to have to raise an error if they are not consistent with the dimensions of the matrix.

I would prefer to accept both, that way we stay consistent with the existing ?gbsv function.
