### ISSUE TITLE
Analytic formula for normal moments

### ISSUE THREAD

**Issue by andrewfowlie** [scipy/scipy#11610]
**Is your feature request related to a problem? Please describe.**

I noticed that the scipy.dist.norm normal distribution uses numerical quadrature to compute the non-central moments in the moment member function (norm.moment)

**Describe the solution you'd like**

The moments can be expressed in terms of analytical formula which should be faster and more precise. The analytic formula use hyper geometric functions that are already implemented in scipy.special. The formula should be applicable for integer and non-integer moments.

I’ve already done this, and can probably quickly make a PR. But perhaps there’s something I’m missing...

**Describe alternatives you've considered**

**Additional context (e.g. screenshots)**

**Comment by ev-br** [comment]
I think it's the matter of implementing norm_gen._munp method. Which sounds like a reasonable thing to do IMO, so +1.

**Comment by rlucas7** [comment]
From a quick look it doesn't look like `_munp` method is implemented for `norm_gen`, so would be nice to have that implemented. 
@andrewfowlie, not sure how familiar you are with the SciPy code base, the source code for `norm_gen` (the code the generates normal distribution instances is here:
https://github.com/scipy/scipy/blob/master/scipy/stats/_continuous_distns.py#L274
and for an distribution which has a `_munp` method implemented, here is beta prime:
https://github.com/scipy/scipy/blob/master/scipy/stats/_continuous_distns.py#L768
hopefully that helps you get started.

**Comment by andrewfowlie** [comment]
@rlucas7 take a look at the PR (https://github.com/scipy/scipy/pull/11627) -  it's basically done

**Comment by rlucas7** [comment]
@andrewfowlie I left a review on your PR, thanks for the contribution to SciPy!
The PR is pretty close to done.

**Comment by rlucas7** [comment]
closed by  #11627
