### ISSUE TITLE
scipy cosine/correlation distance doccumentation

### ISSUE THREAD

**Issue by kyleupton** [scipy/scipy#11629]
Hi,

I'm using the scipy.spatial.distance.cosine function and when i checked the source code i noticed that it just calls the correlation function and forces a mean centring of the data. This default mean centring of the data should be mentioned in the documentation.

It could also be useful to add control over the centring function to the cosine function, or just point users to the correlation function

In my case, my data is already centred around 0, but i cannot assume there is any type of symmetry. 

Love the package!

**Comment by EverLookNeverSee** [comment]
Hi @kyleupton 
Please explain your issue with more details such as example code , ...
And also you can use feature request issue template in issue tracker section.

**Comment by kyleupton** [comment]
Hi ELNS, 
Sorry, i misread the source code yesterday. I somehow missed the fact that cosine passes the centered argument with value False when it calls the correlation function.

I can see cosine does what it says on the label :)

I'll close this issue now.
