### ISSUE TITLE
how to output dual variant?

### ISSUE THREAD

**Issue by itaoxiaoran** [scipy/scipy#11625]
hi, all

when i use the scipy.optimize.linprog for a simple LP

how can i get the value of dual variant （in a simple way）?

cuz in my problem, the dual variant has some practical significance

**Comment by ilayn** [comment]
Hi @itaoxiaoran We are using this repo for code related purposes. You would get more attention and possibly answers on SO or the mailing list for usage questions.

**Comment by WarrenWeckesser** [comment]
There *might* be a feature request implicit in the question.  @mdhaber might have a better idea about that.

**Comment by mdhaber** [comment]
This is a feature request, but it is a duplicate. @itaoxiaoran thanks for the suggestion. It is something we want to implement.
