### ISSUE TITLE
optimize.fmin_l_bfgs_b needs bound check and appropiate error message

### ISSUE THREAD

**Issue by dgahle** [scipy/scipy#11659]
fmin_l_bfgs_b (from scipy.optimize) requires bounds as a list of bounds for each parameter/varriable given as a list [lower, upper]. If any of the bounds are given as [upper, lower] then the fmin_l_bfgs_b runs but the output dict only contains the starting position, zeros and a message saying b'No feasible solution found'. A check that the bounds are structured correctly needs to be added to fmin_l_bfgs_b and if the check is failed either the structure of the bound should be corrected or an error should be raised stating the bounds are incorrectly structured.

**Comment by ruslanye** [comment]
Hello, I'd like to tackle this issue. I'm in favor of raising an exception. It will help in debugging, if user used incorrect bounds(since in documentation it's specified as `(min, max)`). Does anyone have a reason to use another approach instead?

**Comment by andyfaff** [comment]
My preference would be for a neat way of fixing the bounds, possibly located in `_minimize.standardize_bounds`. e.g.
```
bounds = [(0, 1), (3, 2)]
limits = [(min(a, b), max(a, b) for a, b in bounds]
```
then it doesn't matter if the upper limit is less than the lower limit.

**Comment by dgahle** [comment]
I think that doing both would be ideal. So by default an error is raised as suggested by @ruslanye and then have a keyword ('correct_bounds' for example), which defaults to False, that when is True fixes the bounds as suggested by @andyfaff. When the bounds are autocorrected then a Warning error is printed and prints out the change that has occured.

**Comment by andyfaff** [comment]
I don't think an extra keyword is desirable here, but it could be mentioned in the docs.

**Comment by dgahle** [comment]
I think autocorrecting the issue with no warning will just change the types of issues with the bounds that get hidden. So in my problem, I had an array of values that I produced bounds from by multiplying by np.array([0.9, 1.1]). Hence for all negative values, the bounds produced were ordered (max, min). In this case optionally being able to autocorrect is ideal and it tidies up my bounds. In the case of a typo such as (4, 1), when (4, 10) was the intention, autocorrecting the bounds would cause other issues that may not be immediately obvious and might only be found down the line. While I like the idea of autocorrecting the bounds I think it should be optional and default to not autocorrecting and raising a warning instead.

**Comment by ruslanye** [comment]
I agree with @dgahle. I'll try to implement it as they suggested.

**Comment by andyfaff** [comment]
I'm really not a fan of adding an extra keyword here. The keyword argument doesn't add much benefit, and makes the list of arguments longer.

The two realistic options are either

1. Just raise a RuntimeError if the min/max aren't in the correct order

-or-

2. Autocorrect the bounds for min/max and raise a RuntimeWarning.

**Comment by ruslanye** [comment]
Well, the keyword argument will have a default value, so the list of arguments will be longer only if you use the option to correct bounds. Alternatively, we can always raise an error and add a function `_minimize.standardize_bounds`, as you mentioned, so users can correct bounds without using a keyword.
