### ISSUE TITLE
TST, MAINT: CI failures for pre-release NumPy wheels

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#11652]
Some recent changes in NumPy are causing 2 different tests to fail, depending on the version of Python in play:

```
=================================== FAILURES ===================================
________________________________ test_lsmr[COO] ________________________________
[gw2] linux -- Python 3.7.1 /home/travis/virtualenv/python3.7.1/bin/python
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/scipy/sparse/linalg/tests/test_pydata_sparse.py:75: in test_lsmr
    assert_allclose(res[0], res0[0], atol=1e-5)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-07, atol=1e-05
E   
E   Mismatched elements: 4 / 9 (44.4%)
E   Max absolute difference: 1.65523639e-05
E   Max relative difference: 0.00042785
E    x: array([-0.030391,  0.227403,  0.055178,  0.146272, -0.372236,  0.186547,
E          -0.078312,  0.283226, -0.082756])
E    y: array([-0.030404,  0.227412,  0.055174,  0.146287, -0.372228,  0.18654 ,
E          -0.078316,  0.283238, -0.082773])
____________________ TestCurveFit.test_curvefit_covariance _____________________
[gw0] linux -- Python 3.7.1 /home/travis/virtualenv/python3.7.1/bin/python
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/scipy/optimize/tests/test_minpack.py:732: in test_curvefit_covariance
    assert_allclose(pcov1, pcov2, atol=1e-14)
E   AssertionError: 
E   Not equal to tolerance rtol=1e-07, atol=1e-14
E   
E   Mismatched elements: 1 / 4 (25%)
E   Max absolute difference: 9.5518202e-08
E   Max relative difference: 1.07895289e-07
E    x: array([[0.885286, 0.212682],
E          [0.212682, 0.058248]])
E    y: array([[0.885286, 0.212682],
E          [0.212682, 0.058248]])
```

For Python `3.8` only the latter fails.

**Comment by tylerjereddy** [comment]
See: https://github.com/scipy/scipy/pull/11608

And many other recent PRs..

**Comment by tylerjereddy** [comment]
A clean build of SciPy following a clean build of NumPy at the commit hash of the nightly wheel pulled in for Python 3.8 on MacOS with OpenBLAS 0.3.7 does not reproduce for me: `python runtests.py -t "scipy/optimize/tests/test_minpack.py::TestCurveFit::test_curvefit_covariance"`

I'll try on native linux tomorrow if I have time.

**Comment by tylerjereddy** [comment]
@ev-br @nmayorov @mdhaber Any ideas on the optimize failure? My testing efforts have failed to identify a susceptibility to the version of NumPy or the linear algebra backend type, at least so far.

In particular, if you can think of i.e., third-party libraries/ apt-packages that might alter the outcome that might be helpful.

I tried a few different versions of gfortran, but the test still passes locally on Linux/Mac for me.

**Comment by mdhaber** [comment]
I'm sorry, but I don't know much about what could have caused this. 

Would it be wrong to try solve the problem by adjusting the stopping tolerances? I know that doesn't track down the cause.

**Comment by rgommers** [comment]
In the test above, `rtol` goes from `<1e-7` to `0.00042785` it looks like. That's too large a bump to just update the test tolerances for I think.

We can temporarily skip the tests to unblock CI, as long as we then start looking into it I think.

Let's try and reproduce locally, someone should be able to with NumPy master - failures are quite consistent.

**Comment by andyfaff** [comment]
I'm using a docker container setup for scipy, using Python3.7 (on ubuntu:bionic). I run the command `python3.7 runtests.py -t "scipy/optimize/tests/test_minpack.py::TestCurveFit::test_curvefit_covariance"` as suggested by @tylerjereddy.

- scipy master works with numpy built from the current tip of master (4f2b21)
- scipy master works with the numpy pre- wheel, https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/numpy-1.19.0.dev0%2B20200315234624_cd3b44d-cp37-cp37m-manylinux2010_x86_64.whl

**Comment by tylerjereddy** [comment]
@andyfaff 

Yep, and I noted the pre-wheel isn't even being used for one of our matrix entries: https://github.com/scipy/scipy/pull/11658#issuecomment-599161637

It is actually a very old version of NumPy there, and switching linalg backends has no effect whatsoever. There must be something like third-party library or, even worse, the older patch versions of Python on Travis CI combining with something else perhaps.

**Comment by andyfaff** [comment]
i can run an older numpy wheel, whch one?

**Comment by tylerjereddy** [comment]
I just mean, that the NumPy version seems irrelevant here--I agree with you based on the debugging in the cross-linked PR.

**Comment by tylerjereddy** [comment]
We may want to purge/deactivate the cache while we debug those Travis issues too, since this has gotten pretty time consuming to deal with!

**Comment by rgommers** [comment]
Both test matrix entries are numpy `1.19.0.dev`; the older numpy built against doesn't matter much I'd think. It's the `ndarray.dot` calls in the test probably, which will invoke the OpenBLAS in the test-time installed wheels. So it's likely indeed a small change in OpenBLAS that's very hard for any of us to reproduce.

> In the test above, `rtol` goes from `<1e-7` to `0.00042785` it looks like. That's too large a bump to just update the test tolerances for I think.

I'll push some test tolerance bumps to verify, let's see what the damage actually is.

**Comment by rgommers** [comment]
> Would it be wrong to try to solve the problem by adjusting the stopping tolerances in the tests? I know that doesn't track down the cause.

Looks like you were right with this suggestion @mdhaber. The regression was much less bad than it looked at first.

**Comment by mdhaber** [comment]
That's a first!
