### ISSUE TITLE
Add Negative Hypergeometric Distribution

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#11654]
Part of ["A Solid Foundation for Statistics in Python with SciPy"](https://chanzuckerberg.com/eoss/proposals/a-solid-foundation-for-statistics-in-python-with-scipy/).

Add [Negative Hypergeometric Distribution](https://en.wikipedia.org/wiki/Negative_hypergeometric_distribution) to `scipy.stats`.

See gh-9309 for example of adding a discrete distribution. See methods inherited from `rv_discrete`; override when a formula is available. Note in PR what you could not override; perhaps we can help.

Consider using [this](https://en.wikipedia.org/wiki/Negative_hypergeometric_distribution) for reference and to generate test cases.

@fletcheaston @WarrenWeckesser

**Comment by pvanmulbregt** [comment]
Also a requirement to read is http://scipy.github.io/devdocs/dev/contributor/adding_new.html#adding-a-new-statistics-distribution

**Comment by mdhaber** [comment]
Thanks, Paul. Now I remember seeing that while going through the developer docs.
