### ISSUE TITLE
A method to calculate the compound probability of N independent events?

### ISSUE THREAD

**Issue by nesanders** [scipy/scipy#11663]
First of all, a huge thanks to all the scipy developers for creating this incredibly important library!

**Question**

Is there a method in scipy to calculate the compound "OR" probability for some number, N, of conditionally independent events with probability specified by a list, p?  In other words, a calculation to find the probability that at least one event will occur among N independent events that each have probability p_i.

For example, say you have three weighted die such that the odds to roll the '6' side are 10%, 15%, and 20%, respectively.  The compound probability to roll at least one '6' should be 38.8%.

Written out, the "OR" probability for any two independent events is P(A) + P(B) - P(A)*P(B)

So the "OR" probability for any three events is P(A)+P(B)+P(C) - [P(A)P(B) + P(B)P(C) + P(A)P(C)] - P(A)P(B)P(C)

...and so on.

One instance where this kind of problem occurs is when calculating cumulative probabilities.  For example, if you know the independent probability of an event happening during any one year and you want to calculate the probability of it happening over a range of years.

**Attempt**

Not being aware of such a method in scipy or related python libraries, I wrote up a quick recursive function that does this, below.  

```
def p_compound_or(x):
    if len(x) == 0:
        return 0
    if len(x) == 1:
        return x[0]
    elif len(x) == 2:
        return x[0] + x[1] - x[0]*x[1]
    else:
        return p_compound_or(list(itertools.chain([x[0] + x[1] - x[0]*x[1]], x[2:])))
```

**Issues**

Clearly, my code above will not be optimal performance-wise for at least these reasons,

* It's written in pure python
* I'm not sure I've made the most efficient use of itertools for the recursive step
* It doesn't do any kind of approximation, so it may waste time computing very small conditional probabilities, especially if the probably of one event dominates.

Thank you in advance for any suggestions!

**Comment by JesseLivezey** [comment]
> In other words, a calculation to find the probability that at least one event will occur among N independent events that each have probability p_i.

Isn't this the same as 1 - the probability of exactly 0 events occurring?

> For example, say you have three weighted die such that the odds to roll the '6' side are 10%, 15%, and 20%, respectively. The compound probability to roll at least one '6' should be 38.8%.

P(0 events) = (1 - .1) * (1 - .15) * (1 - .2)
P( >0 events) = 1 - P(0 events) = .388

You could calculate this like
```python
ps = np.array([0.1, 0.15, 0.2])
1. - np.prod(1. - ps)
# 0.3879999999999999
```

This is probably more stable for large numbers of ps
```python
ps = np.array([0.1, 0.15, 0.2])
1. - np.exp(np.sum(np.log(1. - ps)))
# 0.388
```

Although P(0 events) will tend to get very small and so it will be easier to represent than 1 - P(0 events).

**Comment by nesanders** [comment]
Hi @JesseLivezey thanks for taking a look, and good point!  That it the same, and definitely simpler.  

For posterity - the time cost of your suggested functions seems to be pretty constant regardless of the size of the probability vector (x AKA ps). The exponential formulation is ~50% slower.  The recursive formulation I started with DOES have size-dependent speed and is a little faster than the exponential formulation up until N~8, and gets slower after that.
