### ISSUE TITLE
scipy.ndimage.convolve1d and correlate1d don't behave properly with mode='mirror' on length-1 dimensions

### ISSUE THREAD

**Issue by coderforlife** [scipy/scipy#11661]
`scipy.ndimage.convolve1d` and `correlate1d` don't behave properly with `mode='mirror'` on length-1 axes. It seems to be picking up random data from outside the array.

#### Reproducing code example:
```
import numpy as np
import scipy.ndimage as ndi
x = np.arange(24).reshape((1, 2, 3, 4)).astype(np.int32)
w = np.ones(3, np.int32)
out = ndi.convolve1d(x, w, mode='mirror', axis=0)
```

which has `out` equal to:
```
array([[[[          0, -2147483648, -2147483648, -2147483648],
         [-2147483648,           5,           6,           7],
         [-2147483648,           9, -2147483648,          11]],

        [[-2147483648, -2147483648,          14,          15],
         [         16,          17,          18,          19],
         [         20,          21,          22,          23]]]],
      dtype=int32)
```
but I expect a result more like:
```
array([[[[ 0,  3,  6,  9],
         [12, 15, 18, 21],
         [24, 27, 30, 33]],

        [[36, 39, 42, 45],
         [48, 51, 54, 57],
         [60, 63, 66, 69]]]], dtype=int32)
```

Clearly that output isn't right at all (has negative values). Also, it should have tripled every value, so numbers that weren't made negative didn't change (essentially assuming constant-0 mode, not mirror).

Smaller arrays exhibit this issue as well, just less obvious since the negatives don't show up. However, look for the tripling of values (that never happens). Floating-point arrays work as well, just easier to see with ints.

The requirements are that the `mode` is `'mirror'` and the dimension that is calculated along has a length of 1.

#### Scipy/Numpy/Python version information:
```
1.4.1 1.16.4 sys.version_info(major=3, minor=7, micro=5, releaselevel='final', serial=0)
```

**Comment by grlee77** [comment]
Thanks for reporting this @coderforlife.

It seems that the nd variant does not suffer from the same problem. (extending `w` to size 1 along all other axes and using `convolve` instead of `convolve1d` gives the expected result:
```Python
import numpy as np
import scipy.ndimage as ndi
x = np.arange(24).reshape((1, 2, 3, 4)).astype(np.int32)
w = np.ones((3, 1, 1, 1), np.int32)
out = ndi.convolve(x, w, mode='mirror')
```
