### ISSUE TITLE
p-value varies with the order of the data

### ISSUE THREAD

**Issue by Lee-nju** [scipy/scipy#11669]
My issue is about the results of f_oneway function are not consistent. The size of the p-value varies with the order of the data. Is this a bug?

#### Reproducing code example:

```
import scipy.stats as stats

a = [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
b = [1000, 1000, 1000, 1000, 1000]
c = [100, 100, 100, 100, 100, 100]

print(stats.f_oneway(a, c, b))   
print(stats.f_oneway(a, b, c))   
print(stats.f_oneway(b, c, a))   
```

#### Result:

```
F_onewayResult(statistic=-6.872847162465134e+16, pvalue=nan)
F_onewayResult(statistic=6.872847162465134e+16, pvalue=1.1322762786915646e-143)
F_onewayResult(statistic=-3.436423581232567e+16, pvalue=nan)
```

**Comment by WarrenWeckesser** [comment]
Your data is degenerate, in that the values in each group are constant.  If you work through the analysis of variance calculation, you'll find that this data leads to division by zero when computing the F statistic, so in theory, F should be infinite, and the p-value should be 0.   In the actual numerical calculation, however, the denominator that should be 0 ends up being a small value that is basically numerical noise, and therefore the computed F statistics is, to use the technical term, garbage.  Note that the value of F reported in two of those three results is *negative*.  F should never be negative.

So I guess we can call this a bug, but you should be aware that this is an unusual edge case.

**Comment by Lee-nju** [comment]
Thank you for your interpretation, we’ll consider this situation!

Thank you at all,
Gangli


开 2020年3月15日 在 下午3:05:52, Warren Weckesser (notifications@github.com) 写到:

Your data is degenerate, in that the values in each group are constant. If you work through the analysis of variance calculation, you'll find that this data leads to division by zero when computing the F statistic, so in theory, F should be infinite, and the p-value should be 0. In the actual numerical calculation, however, the denominator that should be 0 ends up being a small value that is basically numerical noise, and therefore the computed F statistics is, to use the technical term, garbage. Note that the value of F reported in two of those three results is negative. F should never be negative.

So I guess we can call this a bug, but you should be aware that this is an unusual edge case.

**Comment by erheron** [comment]
@WarrenWeckesser , is there something which can be done to fix this?
Maybe some `UserWarning` about degenerated data? I would be interested in tackling this

**Comment by Lee-nju** [comment]
Thank you, because the f value cannot be negative, we changed a line in the source code of the f_oneway function, that is, f = msb / msw to f = abs (msb / msw).

Through this we could get the results near of our intention, p-value is near to zero not equal to ‘nan'.

Thank you very much for your enthusiasm and inspiration.

Best regards,
Gangli

开 2020年3月15日 在 下午8:35:33, Vladyslav Rachek (notifications@github.com) 写到:

@WarrenWeckesser , is there something which can be done to fix this?
Maybe some UserWarning about degenerated data? I would be interested in tackling this

**Comment by rlucas7** [comment]
> @WarrenWeckesser , is there something which can be done to fix this?
> Maybe some `UserWarning` about degenerated data? I would be interested in tackling this

Not sure what Warren's opinion is here but we have similar behavior for Spearman correlation:
https://github.com/scipy/scipy/blob/c1372d8aa90a73d8a52f135529293ff4edb98fc8/scipy/stats/stats.py#L3223
which is thrown/raised here:
https://github.com/scipy/scipy/blob/c1372d8aa90a73d8a52f135529293ff4edb98fc8/scipy/stats/stats.py#L3373-L3376

so something like that may be in order. I'd be willing to review the PR, unless Warren has a different approach he would prefer in this case (there could be some reasons I'm not thinking why we'd want to do something different with anova than we do with correlations).

**Comment by erheron** [comment]
This bug still exists in latest SciPy :thinking: 
Maybe I don't understand something, but I can't see a linked PR or anything. Shouldn't this issue be re-opened? @Lee-nju  @rlucas7

**Comment by WarrenWeckesser** [comment]
We could check for the values within each group being constant.  If they are, and if the common value in at least one group is different from that of another group, the function could return `inf` for the statistic and 0 for the p-value.  If all the values in all the groups are the same, then F is 0/0 and the function should probably return `nan` for F and the p-value.

In `pearsonr`, we generate a warning if an input is "almost constant", because that can result in significant loss of precision.  I haven't thought about whether we need that for `f_oneway`.  I suspect it would be possible to find some nearly constant inputs that generate inaccurate results.

**Comment by rlucas7** [comment]
>> On Mar 24, 2020, at 7:03 PM, Warren Weckesser <notifications@github.com> wrote:
> ﻿
> We could check for the values within each group being constant. If they are, and if the common value in at least one group is different from that of another group, the function could return inf for the statistic and 0 for the p-value. If all the values in all the groups are the same, then F is 0/0 and the function should probably return nan for F and the p-value.
> 
This does seem like the most sensible thing to do for the constant case. In Anova terms check that all “within” variances are constant and based on “between” variances either (0, inf) for between variances not all same and 0 and (nan, nan) for between variances all the same and all 0.

> In pearsonr, we generate a warning if an input is "almost constant", because that can result in significant loss of precision. I haven't thought about whether we need that for f_oneway. I suspect it would be possible to find some nearly constant inputs that generate inaccurate results.
> 
Yeah so that is why I was saying that it might require some investigation. Seems likely there are some behaviors like this but not clear to me what would generate them. Handling the constant input case alone would be good for a single PR I’d think.

**Comment by Lee-nju** [comment]
Through debugging, I found that the reason for the inconsistency of the floating point number calculation is about e -10. 

> Thank you, because the f value cannot be negative, we changed a line in the source code of the f_oneway function, that is, f = msb / msw to f = abs (msb / msw).
Because we finally got the results we needed, we didn't pay much attention to this issue.

**Comment by erheron** [comment]
I'll be now working on the PR, based on the comment of @WarrenWeckesser . Hope to produce it soon
