### ISSUE TITLE
ENH: Using type hints for scipy functions

### ISSUE THREAD

**Issue by EverLookNeverSee** [scipy/scipy#11670]
I have an idea about using python type hints for scipy functions and creating new type hints instead of
built-in types.
for example:

```python
from typing import NewType, Union
array_like = NewType("array_like", Union[ndarray, list])
```

**Comment by rgommers** [comment]
Type annotations would be useful I think. I don't know that much about it, it's unclear to me if it's blocked on https://github.com/numpy/numpy-stubs for better annotations for numpy arrays or not.

**Comment by person142** [comment]
So, without the stubs for NumPy we're going to have the issue that Mypy will treat `np.ndarray` as `Any`, i.e. a very lot of things will make it through `Union[np.ndarray, ...]`. But we do still have plenty of function arguments that aren't arrays, and there's no reason to not start typing those.

**Comment by person142** [comment]
@EverLookNeverSee generally speaking though I would be very interested in an effort to start getting type hints into SciPy.

**Comment by andyfaff** [comment]
What is a generalised type hint for something that could be a numpy array/sequence (list, tuple, etc)/iterable?

**Comment by person142** [comment]
> What is a generalised type hint for something that could be a numpy array/sequence (list, tuple, etc)/iterable?

So, as I understand it, the complete solution is unknown at this point. Even if the NumPy types continue to move forward, there's no way to express shapes currently, so you can't fully type `ndarray`. On the sequence/iterable side there's the problem that there are no recursive types-so there's no way to say something like "an iterable of iterable of ... of float".

So there would have to be compromises. I don't think that should stop us from trying though, because we can probably still do enough to provide some value to users!

There is still perhaps a question of whether we should first try to invest some time into the NumPy types; not sure how open they are to that though.

**Comment by rgommers** [comment]
> There is still perhaps a question of whether we should first try to invest some time into the NumPy types; not sure how open they are to that though.

Contributions are very much encouraged, there's not too many NumPy devs who have experience/interest, more momentum there would be great.

**Comment by person142** [comment]
On the SciPy side, we should probably figure out whether we want to do this inside the main repo or not. As I see it:

### Inside the repo
- Types are next to the code they are typing, which is nice
- Can still use backports in `typing_extensions` without adding dependencies by using the `TYPE_CHECKING` flag
- Can't yet use `from __future__ import annotations`

### Outside the repo
- Not being coupled to SciPy releases allows for quicker iteration
- Might be easier to use things like `@overload` and protocols; not sure if people would go for putting that inside the main codebase before the concept is much more proven out
- Higher potential for drift; could be prevented by CI inside SciPy, but not sure if people would go for blocking PRs on external type stubs failing

Thoughts?

**Comment by EverLookNeverSee** [comment]
> On the SciPy side, we should probably figure out whether we want to do this inside the main repo or not. As I see it:
> 
> ### Inside the repo
> * Types are next to the code they are typing, which is nice
> * Can still use backports in `typing_extensions` without adding dependencies by using the `TYPE_CHECKING` flag
> * Can't yet use `from __future__ import annotations`
> 
> ### Outside the repo
> * Not being coupled to SciPy releases allows for quicker iteration
> * Might be easier to use things like `@overload` and protocols; not sure if people would go for putting that inside the main codebase before the concept is much more proven out
> * Higher potential for drift; could be prevented by CI inside SciPy, but not sure if people would go for blocking PRs on external type stubs failing
> 
> Thoughts?

@person142 , I have no idea yet, but i think we need to get help from numpy experienced developers to simulate array_like type hint.

**Comment by perimosocordiae** [comment]
I lean toward adding types in-repo. I've never had great experiences with external type definitions because the potential for drift is so high.

Eventually we could consider adding a CI that runs mypy or some other type checker.

**Comment by rgommers** [comment]
Also leaning towards in-repo, I think it'll encourage more contributions - `numpy-stubs` is languishing. For a lot of code adding annotations will be fairly mechanical, so it's a good place for newcomers to plug in once we have some clear examples/standard to follow.

Also, it will make it quite easy to experiment with Transonic.

**Comment by person142** [comment]
Opened https://github.com/scipy/scipy/pull/11678 as one way we could get started with types in-repo.

**Comment by person142** [comment]
I think we can close this now-there are many more things to do, but I think they are best tracked in separate issues. (And for some things, e.g. satisfying PEP 561 we'll have to see how this experiment goes first.)
