### ISSUE TITLE
Rotation cannot be expressed as matrix

### ISSUE THREAD

**Issue by MDAddario** [scipy/scipy#11685]
My issue is about the documentation for scipy.spatial.transform.Rotation, which describes how you can get the matrix representation for a generalized rotation, but the as_matrix() method fails to function.

#### Reproducing code example:

```
from scipy.spatial.transform import Rotation as R
r = R.from_euler('z', 90, degrees=True)
mat = r.as_matrix()
```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  mat = r.as_matrix()
AttributeError: 'Rotation' object has no attribute 'as_matrix'
```

#### Scipy/Numpy/Python version information:
 1.2.1 1.16.2 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)

**Comment by peterbell10** [comment]
`as_matrix` was first added in version 1.4.0 (specifically gh-10979). In 1.2.1 the same functionality is called `as_dcm`.

The documentation is missing a `versionadded` though.
