### ISSUE TITLE
L-BFGS-B error message always reports 20 line search iterations

### ISSUE THREAD

**Issue by drhagen** [scipy/scipy#11718]
If the L-BFGS-B minimization method terminates abnormally due to the maximum number of line search iterations, it displays this message:

```
 Line search cannot locate an adequate point after 20 function
  and gradient evaluations.  Previous x, f and g restored.
 Possible causes: 1 error in function or gradient evaluation;
                  2 rounding error dominate computation.
```

I want to note that it says "after 20 function...evaluations" regardless of how many evaluations it did. 20 is the default value of `maxls`, but if you change it to something else, say 40, the message still says 20, which is confusing. Ideally, it would display "after 40 function...evaluations", but displaying "after maxls function...evaluations" would also be fine if string interpolation in Fortran is hard.

[Here is the line](https://github.com/scipy/scipy/blob/master/scipy/optimize/lbfgsb_src/lbfgsb.f#L2903) that needs to be changed.

**Comment by EverLookNeverSee** [comment]
@drhagen Please specify Sample code to reproduce the problem.

**Comment by WarrenWeckesser** [comment]
Here's an example:

```
import numpy as np
from scipy.optimize import minimize


def func(x):
    return x + np.exp(-10*x)

result = minimize(func, x0=10, method='L-BFGS-B',
                  options={'maxls': 5, 'disp': 1})
```
Output:

```
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            1     M =           10
 This problem is unconstrained.

At X0         0 variables are exactly at the bounds

At iterate    0    f=  1.00000D+01    |proj g|=  1.00000D+00

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    1      1      6      1     0     0   1.000D+00   1.000D+01
  F =   10.000000000000000     

ABNORMAL_TERMINATION_IN_LNSRCH                              

 Line search cannot locate an adequate point after 20 function
  and gradient evaluations.  Previous x, f and g restored.
 Possible causes: 1 error in function or gradient evaluation;
                  2 rounding error dominate computation.

 Cauchy                time 0.000E+00 seconds.
 Subspace minimization time 0.000E+00 seconds.
 Line search           time 0.000E+00 seconds.

 Total User time 0.000E+00 seconds.
```

**Comment by WarrenWeckesser** [comment]
> Ideally, it would display "after 40 function...evaluations", but displaying "after maxls function...evaluations" would also be fine if string interpolation in Fortran is hard.

Even better would be for it to display both the name (`maxls`) and the value that it was set to by the user.

**Comment by maryhzd** [comment]
Hello,

I am also facing this problem. I increased "maxls" to 40, and it stops after 20 line searches per iteration. So, is there any way to increase the number of line searches?

**Comment by andyfaff** [comment]
@maryhzd, the max number of line searches specified by `maxls` seems to work. However, when that limit is reached it will always say `'Line search cannot locate an adequate point after 20 function ...`. Basically the error message is wrong.

I have no idea how to do string interpolation in fortran. The quick fix would be to follow @drhagen suggestion.
