### ISSUE TITLE
CI failures: AMD64 MB_PYTHON=3.7 

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#11711]
Some recent PRs (gh-11703, gh-11705, gh-11710) are failing a common test due to a CI failure before the test even starts.
```
AMD64
TESTMODE=fast COVERAGE= NUMPYSPEC="--upgrade numpy" MB_PYTHON_VERSION=3.7
```

#### Error message:
```
An error occurred while generating the build script.
```

**Comment by tylerjereddy** [comment]
Perhaps worth clarifying that this is for MacOS only in the Travis CI matrix.

**Comment by peterbell10** [comment]
Travis had a problem with their macOS workers that should be fixed now:
https://www.traviscistatus.com/

>**Identified** - We have identified an issue with a portion of Mac infrastructure which prevents builds from running correctly. We are working on mitigating the impact of this problem.
>
>Affected jobs would indicate "An error occurred while generating the build script." in the logs.
