### ISSUE TITLE
nan_policy does not play well with axes in median_absolute_deviation

### ISSUE THREAD

**Issue by christian-oreilly** [scipy/scipy#11719]
I think that the management of NaNs in median_absolute_deviation might be broken,

#### Reproducing code example:

```python
x = np.array(np.ones((2, 3, 4)))
median_absolute_deviation(x, axis=0, nan_policy="omit")
```
output:
```
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])
```
Inserting a NaN value...
```python
x[0, 0, 0] = np.nan
x
```
output:
```
array([[[nan,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]]])
```
We now get
```python
median_absolute_deviation(x, axis=0, nan_policy="omit")
```
output:
```
0.0
```

I think that the last output have been a matrix of size 3x4. Obviously, because of that, running `median_absolute_deviation` along a different axis such as 
```python
x = np.array(np.ones((2, 3, 4)))
x[0, 0, 0] = np.nan
median_absolute_deviation(x, axis=1, nan_policy="omit")
```
crashes with an AxisError.

#### Scipy/Numpy/Python version information:
```
1.4.1 1.16.1 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
@christian-oreilly, thanks for reporting the problem.  I confirmed that the problem still exists in the master development branch (`'1.5.0.dev0+69f44c0'`).

**Comment by WarrenWeckesser** [comment]
This was fixed in https://github.com/scipy/scipy/pull/11431.  `median_absolute_deviation` is now deprecated (use `median_abs_deviation` instead), but the function was also fixed to handle `nan_policy` correctly.
