### ISSUE TITLE
Monte Carlo methods for scipy.integrate

### ISSUE THREAD

**Issue by EdKaHe** [scipy/scipy#11723]
**Problem description**
I was wondering why there are no Monte Carlo integration methods (uniform sampling, importance sampling, MISER, VEGAS) in scipy.integrate? Especially for high dimensional integrals MC methods provide good efficiency and they are applicable to a wide range of fields in science and engineering.

**The solution I'd like**
One could implement a set of Monte Carlo methods that are applicable to n-dimensional integrals. E.g. something like this (adapted from [here](https://docs.scipy.org/doc/scipy/reference/tutorial/integrate.html#general-multiple-integration-dblquad-tplquad-nquad)):

from scipy import integrate

N = 5
def f(t, x):
    return np.exp(-x*t) / t**N

integrate.mcuniform(f, [[1, np.inf],[0, np.inf]])
integrate.mcmiser(f, [[1, np.inf],[0, np.inf]])
integrate.mcvegas(f, [[1, np.inf],[0, np.inf]])

**Alternatives I've considered**
I am aware of the [vegas](https://github.com/gplepage/vegas) and [scikit-monaco](https://github.com/scikit-monaco/scikit-monaco) projects but there can be issues with the installation on Windows (requires C compiler) and I would think that such important methods should be easily available independent of the platform. Including MC methods into scipy.integrate would also ensure an uniform documentation and syntax.

**Comment by rgommers** [comment]
Hi @EdKaHe, this is the kind of feature that could very well make sense to have as part of `scipy.integrate`, but would be fairly technical code to get right. If there was a proposal to, e.g., integrate `vegas` into SciPy by its maintainer (who would keep maintaining it for the foreseeable future), we would certainly consider that. We've done that kind of integration of fairly mature code in other places, and it's a good way to make algorithms that are best-in-class - or at least better than what we already have - available to users.

**Comment by mdhaber** [comment]
[`qmc_quad`](https://scipy.github.io/devdocs/reference/generated/scipy.integrate.qmc_quad.html#scipy.integrate.qmc_quad) will be part of 1.11.0. It's essentially the simplest possible QMC integration method, but in higher dimensions it's more effective than `nquad`, so I think it satisfies the enhancement request. If not, please feel free to reopen.
