### ISSUE TITLE
aarch64 build for scipy

### ISSUE THREAD

**Issue by odidev** [scipy/scipy#11724]
**Is your feature request related to a problem? Please describe.**

Hi Team, facing issue in Building Scipy in my local environment.

**Describe the solution you'd like**

I am working on adding builds for aarch64 for Scipy.

**Describe alternatives you've considered**

I have tried adding the builds in Travis-ci as well for Python v3.7, but the builds are not getting executed successfully.

**Additional context (e.g. screenshots)**

Please find below the error I am getting:

```
Building wheels for collected packages: scipy
  WARNING: Building wheel for scipy failed: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/c2'
Failed to build scipy
Cleaning up...
  Removing source in /tmp/pip-req-build-fm_cmo2f
Removed build tracker: '/tmp/pip-req-tracker-6p3r1zc_'
ERROR: Could not build wheels for scipy which use PEP 517 and cannot be installed directly
Exception information:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.5/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/home/travis/virtualenv/python3.7.5/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 375, in run
    ", ".join(r.name for r in pep517_build_failures)))
pip._internal.exceptions.InstallationError: Could not build wheels for scipy which use PEP 517 and cannot be installed directly
```
```
python -u runtests.py -g -m $TESTMODE $COVERAGE $USE_WHEEL_BUILD -- -rfEX -n 3 2>&1 | tee runtests.log
Traceback (most recent call last):
  File "runtests.py", line 476, in <module>
    main(argv=sys.argv[1:])
  File "runtests.py", line 276, in main
    __import__(PROJECT_MODULE)
ModuleNotFoundError: No module named 'scipy'
The command "python -u runtests.py -g -m $TESTMODE $COVERAGE $USE_WHEEL_BUILD -- -rfEX -n 3 2>&1 | tee runtests.log" exited with 1.
0.10s$ tools/validate_runtests_log.py $TESTMODE < runtests.log
*** Test runner validation errored: did the run really finish?
The command "tools/validate_runtests_log.py $TESTMODE < runtests.log" exited with 255.
```
It will be really helpful, if you could provide some pointers on this.

**Comment by rgommers** [comment]
`aarch64` builds do work on conda-forge: https://github.com/conda-forge/scipy-feedstock/blob/6eded1642dfebcc4d616a536aeec40e9f63b0275/.drone.yml#L3

> Could not build wheels for scipy which use PEP 517 and cannot be installed directly

not sure if that's a misleading error message or not, but you can try with `--no-build-isolation`. Also use `-v` for verbose output. that should tell you what's wrong

**Comment by odidev** [comment]
@rgommers Thanks for the quick response, As per your suggestion I have installed the scipy in my local environment with conda and tests are passing now.

Also I wanted to ask if you will be willing in accepting a PR that enables support for aarch64 builds in Travis-ci. Please share your thoughts on this.

**Comment by rgommers** [comment]
Great!

> Also I wanted to ask if you will be willing in accepting a PR that enables support for aarch64 builds in Travis-ci. Please share your thoughts on this.

Help with aarch64 CI would be much appreciated. gh-11170 is the relevant open issue for that. There seems to be a preference for Drone rather than TravisCI, and I think that makes sense since TravisCI is already really slow now.

I'll close this, please continue the conversation in gh-11170 (or just dig in with a PR!).
