### ISSUE TITLE
Build faill

### ISSUE THREAD

**Issue by kobango** [scipy/scipy#11730]
I have problem with ./build_openblas.sh
I done all like, http://scipy.github.io/devdocs/building/windows.html
But when I use ./build_openblas.sh on copy of file a have this output:
$ ./build_openblas.sh
which: no gcc in (/usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
./build_openblas.sh: linia 7: gcc: nie znaleziono polecenia
HEAD is now at b6a948fb Merge pull request #2530 from martin-frbg/dynmsg
./build_openblas.sh: linia 26: gcc: nie znaleziono polecenia
make: gcc: No such file or directory
make: *** [Makefile.prebuild:62: getarch] Błąd 127
Makefile.system:1144: Makefile.: No such file or directory
make: *** Brak reguł do wykonania obiektu 'Makefile.'. Stop.
make: gcc: No such file or directory
make: *** [Makefile.prebuild:62: getarch] Błąd 127
Makefile.system:1144: Makefile.: No such file or directory
make: *** Brak reguł do wykonania obiektu 'Makefile.'. Stop.

**Comment by ilayn** [comment]
You are missing the installation of gcc step as the error says

**Comment by kobango** [comment]
Okay,
As i think, so when I finish instaling this it should work.
Thank for reply

pt., 27 mar 2020 o 10:31 Ilhan Polat <notifications@github.com> napisał(a):

**Comment by ilayn** [comment]
No problem @kobango . I'll close this issue since it is not related to SciPy code but feel free to discuss further.
