### ISSUE TITLE
Scalability problem with scipy.interpolate griddata

### ISSUE THREAD

**Issue by asmagen** [scipy/scipy#11738]
I am trying to warp big histopathology images (~15k x 15k pixels) using x y deformation fields generated by drop2 image registration pipeline separately per each image channel using:
```
REF = plt.imread(PATH_IMG_REF)
SRC = plt.imread(PATH_IMG_SRC)

img_dx = sitk.ReadImage(PATH_DEF_X)
img_dy = sitk.ReadImage(PATH_DEF_Y)
spacing = img_dx.GetSpacing()
deform_x = sitk.GetArrayFromImage(img_dx)[0] / spacing[0]
deform_y = sitk.GetArrayFromImage(img_dy)[0] / spacing[1]
grid_y, grid_x = np.mgrid[0:deform_x.shape[0], 0:deform_x.shape[1]]
output = REF
output[:,:,:] = 0
output.shape
level=0
for level in (0,1,2):
img_src = SRC[:,:,level]
img_ref = REF[:,:,level]
img_src_resized = resize(img_src, img_ref.shape)
img_warp2 = griddata((grid_y.ravel(), grid_x.ravel()), img_src_resized.ravel(),(grid_y + deform_y, grid_x + deform_x), method='linear')
```
But, if I understand the problem correctly, I run into memory problems although I allocate ~64GB RAM on a computational node:
```
img_warp2 = griddata((grid_y.ravel(), grid_x.ravel()), img_src_resized.ravel(),(grid_y + deform_y, grid_x + deform_x), method='linear')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/hpc/packages/minerva-centos7/py_packages/3.7/lib/python3.7/site-packages/scipy/interpolate/ndgriddata.py", line 222, in griddata
    rescale=rescale)
  File "interpnd.pyx", line 248, in scipy.interpolate.interpnd.LinearNDInterpolator.__init__
  File "qhull.pyx", line 1836, in scipy.spatial.qhull.Delaunay.__init__
  File "qhull.pyx", line 353, in scipy.spatial.qhull._Qhull.__init__
scipy.spatial.qhull.QhullError: QH6080 qhull error (qh_memalloc): insufficient memory to allocate short memory buffer (65536 bytes)

While executing:  | qhull d Qz Qc Qbb Q12 Qt
Options selected for Qhull 2015.2.r 2016/01/18:
  run-id 22173203  delaunay  Qz-infinity-point  Qcoplanar-keep  Qbbound-last
  Q12-no-wide-dup  Qtriangulate  _pre-merge  _zero-centrum  Qinterior-keep
  Pgood  _max-width 1.7e+04  Error-roundoff 2.4e-11  _one-merge 1.7e-10
  Visible-distance 4.8e-11  U-coplanar-distance 4.8e-11  Width-outside 9.6e-11
  _wide-facet 2.9e-10
Last point added to hull was p734880.  Last merge was #4739486.

At error exit:

Delaunay triangulation by the convex hull of 201763301 points in 3-d:

  Number of input sites and at-infinity: 13057987
  Total number of nearly incident points: 188705314
  Number of Delaunay regions: 0
  Number of non-simplicial Delaunay regions: 2490119

Statistics for:  | qhull d Qz Qc Qbb Q12 Qt

  Number of points processed: 13057987
  Number of hyperplanes created: 63916630
  Number of facets in hull: 22959143
  Number of distance tests for qhull: 50864656
  Number of distance tests for merging: 517567686
  Number of distance tests for checking: 0
  Number of merged facets: 4739486
  Maximum distance of merged point above facet: 6.1e-11 (0.3x)
  Maximum distance of merged vertex below facet: -5.6e-11 (0.3x)


precision problems (corrected unless 'Q0' or an error)
4739484 coplanar horizon facets for new vertices
```

Any advice about how to make it work on the whole image or what's the easiest way to apply it on tiles of an image given the deformation fields of the whole image?

Thanks

**Comment by rgommers** [comment]
> scipy.spatial.qhull.QhullError: QH6080 qhull error (qh_memalloc): insufficient memory to allocate short memory buffer (65536 bytes)

That is possibly a bug, thanks for the report @asmagen. Would you be able to make this example self-contained, so we can run it? I.e. replace `REF` and `SRC` with dummy images (just generate with np.random.random for example) as well as replacing `sitk` usage?

Re a workaround, tiling is a bit of pain - you'd have to add a buffer to each tile, then warp, strip off buffer, and recombine. This is a common problem, but I'm not aware of an easy-to-use function for it in scipy, scikit-image or elsewhere.

**Comment by asmagen** [comment]
It should occur with any big image (more than 5k x 5k pixels) for which you have deformation field output such as the ones produced by [drop2](https://github.com/biomedia-mira/drop2) (separate x and y deformation fields) which you try to wrap the separate channels of an RGB image as attempted in the code above. How can I replace the usage of sitk.ReadImage as you suggested?

**Comment by rgommers** [comment]
> How can I replace the usage of sitk.ReadImage as you suggested?

It's not obvious to me what that does; your code says `img_dx` but https://simpleitk-prototype.readthedocs.io/en/latest/user_guide/plot_image.html says it returns an object with a set of metadata. If there's Python API reference docs for `sitk`, they manage to hide those pretty well.

`img_dx` is what exactly?

**Comment by asmagen** [comment]
It's the x deformation field (and img_dy is the corresponding y deformation field) - basically loading the x and y deformation field nii files generated by drop2.

**Comment by ev-br** [comment]
What Ralf said, https://github.com/scipy/scipy/issues/11738#issuecomment-606574965 : this is not actionable without a reproducible example. 
I'm thus going to close for now, feel free to ping the issue once there is a reproducible example and we'll reopen.
At a guess I'd suspect it's a relative (or a dupe) of https://github.com/scipy/scipy/issues/13037.
