### ISSUE TITLE
MAINT: stats: getting skewness alone takes 34000x longer than getting mean, variance, and skewness

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#11742]
I encountered something surprising while working on gh-11695:
```
from scipy.stats import skewnorm as dist
a, loc, scale = 2, 0.4, 1

%timeit dist.stats(a=a, loc=loc, scale=scale, moments='s')
11 s ± 318 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%timeit dist.stats(a=a, loc=loc, scale=scale, moments='mvs')
323 µs ± 47.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
This sort of behavior is not unique to skewnorm, although it is one of the most exagerated cases. The logic in the code that leads to this is a bit complicated, but in short, if `m` and `v` don't need to be calculated, the calculation for `s` falls back to the generic implementation rather than a simple formula.

**Comment by WarrenWeckesser** [comment]
Thanks @mdhaber.  Weird.  I'll take a look.

**Comment by mdhaber** [comment]
I think this will get fixed by gh-15140

**Comment by Smit-create** [comment]
> I think this will get fixed by [gh-15140](https://github.com/scipy/scipy/pull/15140)

Yes, it does:

```py
In [1]: from scipy.stats import skewnorm as dist
   ...: a, loc, scale = 2, 0.4, 1

In [2]: %timeit dist.stats(a=a, loc=loc, scale=scale, moments='s')
215 µs ± 9.92 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [3]: %timeit dist.stats(a=a, loc=loc, scale=scale, moments='mvs')
206 µs ± 8.78 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

```
