### ISSUE TITLE
BUG: stats: pearson3 returns size 1 arrays where other distributions return scalars 

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#11746]
Example:
```
from scipy.stats import alpha, halfcauchy, invgamma, invweibull, kappa3, levy, levy_l, loglaplace, pareto, pearson3
for dist in [alpha, halfcauchy, invgamma, invweibull, kappa3, levy, levy_l, loglaplace, pareto, pearson3]:
    print(dist.moment(1, 2))
```
prints:
```
inf
inf
1.0
1.7724538509055159
1.4142135623743761
inf
inf
1.3333333333333333
2.0
[0.]
```
The last one, from `pearson3`,  is a size 1 array; it should be a scalar like the rest.

_Update: Another problem is that the `pearson3.moment` function returns an empty array when `skew` is too small._
```
from scipy.stats import pearson
pearson3.moment(1, skew=0.000001)
```
 _When these issues are fixed, please try to remove the override of the `pearson3.fit` method and allow `check_fit_args` and `check_fit_args_fix`  to run in `test_continuous_basic.py` by removing `pearson3` from `fail_fit_test_mm`/`fail_fit_fix__test_mm`._

**Comment by WillTirone** [comment]
@mdhaber hello! I'm a first time contributor but I can take a stab at this if you still think it's a good first issue.

**Comment by mdhaber** [comment]
I imagine it is, at least at the surface. The easiest fix would be just to check the output of the function and convert it to a scalar if necessary. It would be great if you'd dig a bit deeper to see why this is happening for `pearson3`, whether it manifests in other ways, and correct it at the source. Thanks for looking into it!

**Comment by WillTirone** [comment]
Sounds good, I'll take a look here in a bit. A quick question: I have an older fork of the scipy main repo, just from following the steps here: https://docs.scipy.org/doc/scipy/reference/dev/contributor/quickstart_ubuntu.html#quickstart-ubuntu

Do I need to do a completely new fork + and clone again (steps 10 - 13 above) or can I refresh from the upstream repo or something like that?

**Comment by mdhaber** [comment]
No fork, yes rebase on upstream. Please see http://scipy.github.io/devdocs/dev/gitwash/useful_git.html#rebasing-on-master

**Comment by mdhaber** [comment]
So:
`git checkout master` to make sure you're on the master branch
`git fetch upstream` to get the latest changes
`git rebase upstream/master` to update your local master branch according to those changes
`git checkout -b feature_branch` to create a feature branch for you to work on

**Comment by WillTirone** [comment]
awesome, that makes sense. Thanks!

**Comment by WillTirone** [comment]
@mdhaber  on your last point: I saw the below comment in the pearson3 class. Does this clear up your last point or should that transition variable be smaller? Looks like anything < 0.000016 returns an empty array. 

```python
# If skew is small, return _norm_pdf. The divide between pearson3
# and norm was found by brute force and is approximately a skew of
# 0.000016.  No one, I hope, would actually use a skew value even
# close to this small.
norm2pearson_transition = 0.000016
```

**Comment by mdhaber** [comment]
I'm not familiar with the Pearson distribution, and I haven't looked at the code, but from the excerpt you included, I assume that it tends toward the normal distribution as the skew goes to zero? If so, it should return the mean of the normal distribution. In any case, it should never return an empty array.

**Comment by WillTirone** [comment]
@mdhaber hello - it seems like the issue here is the below snippet, where the code uses a mask / invmask if the skew is small enough to transition to use the normal distribution which is done with the arrays. 

However, I'm not sure what the most appropriate way to fix this is. I'm not aware of another method to "mask" like that without an array, and I don't see another continuous distribution that has a similar structure so I'm wondering what the most pythonic approach would be.

```python
# If skew is small, return _norm_pdf. The divide between pearson3
# and norm was found by brute force and is approximately a skew of
# 0.000016.  No one, I hope, would actually use a skew value even
# close to this small.
norm2pearson_transition = 0.000016

ans, x, skew = np.broadcast_arrays([1.0], x, skew)
ans = ans.copy()

# mask is True where skew is small enough to use the normal approx.
mask = np.absolute(skew) < norm2pearson_transition
invmask = ~mask

beta = 2.0 / (skew[invmask] * scale)
alpha = (scale * beta)**2
zeta = loc - alpha / beta

transx = beta * (x[invmask] - zeta)

**Comment by mdhaber** [comment]
I agree that this is relevant because it shows why something different happens when skew is small, but I don't think it is complete. Can you include the rest of the relevant code? Where does it return? I don't see from this how the moment could become empty. 

Also, while other distributions may not use masks, they also accept an array for `skew`, yet somehow their `moment` method returns a scalar when it should. I don't really see from this how the mask complicates things.

**Comment by WillTirone** [comment]
hmm that makes sense, let me continue to look through it. I didn't realize other dists used masks as well. 

Again, definitely still a beginner so it may take me a while to figure out a fix.

**Comment by mdhaber** [comment]
> other dists used masks as well.

They might not use masks, but they do allow `skew` to be an array.

**Comment by WillTirone** [comment]
I believe I have a fix that works and passes testing - however, per your last comment on the original post (below) I don't see a fit method for pearson3 and I don't see fail_fit_test_mm/fail_fit_fix__test_mm in  test_continuous_basic.py

> When these issues are fixed, please try to remove the override of the pearson3.fit method and allow check_fit_args and check_fit_args_fix to run in test_continuous_basic.py by removing pearson3 from fail_fit_test_mm/fail_fit_fix__test_mm.

**Comment by mdhaber** [comment]
You're right, I think I was writing these things in another PR that's not merged yet. Please submit a PR with your fix!
