### ISSUE TITLE
MAINT: stats: inefficient use of optimizer by `rv_continuous.fit`

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#11751]
Even when fitting distributions with certain parameters fixed, `rv_continuous.fit` allows the optimizer to treat all the parameters as decision variables. In order to keep the parameters fixed, it resets those variables to their fixed values after the optimizer calls the objective function. At best, this wastes time replacing the values of decision variables instead of actually leaving them fixed. Worse, for gradient-based algorithms, this wastes time numerically evaluating partial derivatives that are always zero, and depending on the optimization algorithm, these zero gradients (and Hessians) can cause termination issues. It might not be such a problem for the default optimizer, [`scipy.optimize.fmin`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fmin.html) as
> This algorithm only uses function values, not derivatives or second derivatives.

but since the `fit` method accepts a callable `optimizer` argument, this is not the right way to treat the fixed parameters. 

_Update: I read the code incorrectly. There are still some improvements that could be made, noted below._

---

`rv_continuous.fit` works by solving an optimization problem. 
```
vals = optimizer(func, x0, args=(ravel(data),), disp=0)
```
where `x0` is the guess values of the distribution parameters and `vals` are the fitted/optimized parameters. `optimer` is `scipy.optimize.fmin` by default but can be any other optimization routine. `func` is the objective function, which comes from:
```
x0, func, restore, args = self._reduce_func(args, kwds)
```
So `func` is defined in `_reduce_fun` as.
```
            def func(theta, x):
                newtheta = restore(args[:], theta)
                return objective(newtheta, x)
```
where `restore` is:
```
            def restore(args, theta):
                # Replace with theta for all numbers not in fixedn
                # This allows the non-fixed values to vary, but
                #  we still call self.nnlf with all parameters.
                i = 0
                for n in range(Nargs):
                    if n not in fixedn:
                        args[n] = theta[i]
                        i += 1
                return args
```
So the optimizer passes all distribution parameters `theta` as decision variables into `func`, which then `restore`s the fixed values.

It would be better if `func` accepted fixed parameters as a third argument; `theta` would only be the non-fixed parameters that the optimizer is supposed to vary. The new code should also be vectorized (in contrast with `restore`, which uses a pure Python `for` loop). It would also be nice to use `minimize` rather than the `fmin` optimizers and check the status of the optimization, raising a `fit`-specific error when it fails. Even if we don't change to `minimize`, the documentation for `fit` should state what the optimizer should output - just the solution vector.

**Comment by andyfaff** [comment]
What's the interface for deciding which parameters are fixed, and which vary? How about using a decorator here?
```
def fixomatic(fullfunc, full_x, varying):
     full_x_cp = np.copy(full_x)
     reduced_x = full_x[varying]

    def objective(x, args=()):
        assert len(x) == len(reduced_x)
        full_x_cp[varying] = x
        return fullfunc(full_x_cp, *args)

    return objective

func_to_supply_to_minimize = fixomatic(myfunc, full_x, my_bool_arr_same_len_as_full_x)
```

**Comment by mdhaber** [comment]
Yes @andyfaff something like that would do the trick. I haven't looked at exactly how the fixed values are identified, but it looks like it's a list of indices `fixedn` - corresponding with all the elements of your `full_x` that are not `varying`.

**Comment by josef-pkt** [comment]
Is this really correct?

AFAIR, the optimizer should only see the free parameters, and internally we expand the parameters to be able to use the standard likelihood function.

(Aside: It took some time to fix all the bugs in the handling of fixed parameters. statsmodels and my original code used a mask which is simpler for the expand/restore function than the code that ended up in scipy.stats.)

**Comment by mdhaber** [comment]
Maybe not. I'm looking into it again.

**Comment by mdhaber** [comment]
No, I guess I misread the code. I was surprised at what I was seeing, and I thought I tested it just to make sure, but the optimizer does only call `func` with the non-fixed parameters.

Still, wouldn't it be better if we created an array outside `restore`:
```
varying = np.ones_like(args, dtype=bool)
varying[fixedn] = False
```
and replaced the contents of the `restore` function (`for` loop, conditional, etc...) with:
```
args[varying] = theta
``
?

**Comment by josef-pkt** [comment]
I haven't looked at this in scipy in a while

here's my original version (more than 10 years ago)
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/sandbox/distributions/sppatch.py#L170

I found using a  fixed/free mask internally much easier to understand.
In my original code, the user also was supposed to specify an array with nan for the free parameters. However, that is more cumbersome for the user than the current scipy version.

**Comment by mdhaber** [comment]
No need to keep this open. I still think that there are a few things that could be improved about `fit`:
- vectorize `restore`
- use `minimize` rather than the `fmin`
- check the status of the optimization, raising a fit-specific error when it fails
- improve the documentation (e.g. what should `optimizer` output?  just the solution vector)
but I can probably address them in gh-11695.
