### ISSUE TITLE
Improve and fix *Spline docstrings and code

### ISSUE THREAD

**Issue by erheron** [scipy/scipy#11756]
During the investigation of the issue #9718 I've discovered a few possibilities for both improvements and fixes in the documentation of different *Spline classes in 
https://github.com/scipy/scipy/blob/master/scipy/interpolate/fitpack2.py
I create this issue mainly because it seems to me that it'll be (and must be) more general than #9718
The things below will be mostly about `RectBivariateSpline` class

Things that came into mind:

- In `BivariateSpline` class, as far as I understand,  `RectBivariateSpline` should be added to the end of the sentence, because it subclasses `BivariateSpline`
https://github.com/scipy/scipy/blob/b818978f3580e05a3885006cae337f28bd2aaf7d/scipy/interpolate/fitpack2.py#L931-L933
- Docstring of `RectBivariateSpline` containes a few more inconsistencies: e.g. `tx, ty` in here: https://github.com/scipy/scipy/blob/b818978f3580e05a3885006cae337f28bd2aaf7d/scipy/interpolate/fitpack2.py#L1149-L1152
 although they do not appear in `init`:
https://github.com/scipy/scipy/blob/b818978f3580e05a3885006cae337f28bd2aaf7d/scipy/interpolate/fitpack2.py#L1169
- I have a feeling that "See Also" sections in different Spline's might be more... broad? Consistent? There's not so many of that classes, so why not to mention them all, or at least ensure that if `A -> B` and `A -> C` (-> means subclassing), then `B` mentions `C` in "See Also" and vice versa?
- I've got a feeling that two last checks of these 4 are redundant, but I'm not sure
https://github.com/scipy/scipy/blob/b818978f3580e05a3885006cae337f28bd2aaf7d/scipy/interpolate/fitpack2.py#L1171-L1178
- Problem with #9718 remains for now, but I'm working on it

If this issue "makes sense" to some of the members, I suggest closing #9718 in favor of this one.

**Comment by stefanv** [comment]
Thank you, @erheron, a thorough review of this and related docs would be great.  All the inconsistencies you noted should definitely be addressed.
