### ISSUE TITLE
Remove the unit test that searches the code for warnings filters?

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#11762]
In https://github.com/scipy/scipy/blob/master/scipy/_lib/tests/test_warnings.py, there is a unit test that checks for the use of the `warnings` library to filter warnings.  This was important because of bugs in older versions of Python.  Now that we require at least Python 3.6, we can probably remove this test.

I haven't looked too deeply into this.  There might be reasons to keep a test like this in the code,  and to continue to avoid filtering warnings with the `warnings` library.

**Comment by pv** [comment]
It also checks the presence of the stacklevel, and safeguards that warnings.simplefilter is not used to suppress warnings.

**Comment by WarrenWeckesser** [comment]
Is there a summary somewhere of why `warnings.simplefilter` should not be used?

**Comment by pv** [comment]
I was thinking about using it without catch_warnings, but the test does not check for that. So I'm not sure there's actually a reason for the test aside from the old Python bugs and possibly checking for stacklevel= usage. 

The warning filter modifications are not threadsafe (in contrast to e.g. `np.errstate`), which could also be a reason to try to avoid them, but that's a rarer case.

**Comment by rgommers** [comment]
+1 for at least keeping the `stacklevel` check, that's quite useful

**Comment by WarrenWeckesser** [comment]
OK, I'll close this.  The lack of thread safety is good to know.
