### ISSUE TITLE
non-central chi2 (scipy.stats.ncx2.pdf) gets clipped to zero at high df

### ISSUE THREAD

**Issue by jvavrek** [scipy/scipy#11777]
At high values of degrees of freedom `df` the pdf of `ncx2` gets clipped to zero when the non-centrality parameter `nc` is sufficiently less than `df`:

#### Reproducing code example:

```
import numpy as np
from scipy.stats import norm, ncx2
import matplotlib.pyplot as plt

df = 6700
nc = 5300
x = np.linspace(ncx2.ppf(0.001, df, nc), ncx2.ppf(0.999, df, nc), num=10000)
fig, ax = plt.subplots(1)
ax.plot(x, ncx2.pdf(x, df, nc))
ax.plot(x, norm.pdf(x, df+nc, np.sqrt(2*df+4*nc)))  # gaus approximation
plt.show()
```

#### Erroneous plot:
![image](https://user-images.githubusercontent.com/7683814/78216372-8aac6580-746e-11ea-931d-6e4f98bc8bb0.png)

If I set `nc=5500` the curves overlap perfectly; if I set `nc=5100`, the `ncx2` output is pretty close to (but not quite) all zeros

#### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.3.0 1.16.4 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by jvavrek** [comment]
A bit more info. From the [source code](https://github.com/scipy/scipy/blob/e1e44d12637997606b1bcc0c6de232349e11eee0/scipy/stats/_distn_infrastructure.py#L560) (v.1.3.0):

```
from scipy.special import xlogy, ive

# line 560 or so
def _ncx2_log_pdf(x, df, nc):
    # We use (xs**2 + ns**2)/2 = (xs - ns)**2/2  + xs*ns, and include the
    # factor of exp(-xs*ns) into the ive function to improve numerical
    # stability at large values of xs. See also `rice.pdf`.
    df2 = df/2.0 - 1.0
    xs, ns = np.sqrt(x), np.sqrt(nc)
    res = xlogy(df2/2.0, x/nc) - 0.5*(xs - ns)**2
    res += np.log(ive(df2, xs*ns) / 2.0)
    return res


def _ncx2_pdf(x, df, nc):
    return np.exp(_ncx2_log_pdf(x, df, nc))
```

then

```
_ncx2_pdf(x=12000, df=6700, nc=5300)
```
works, while

```
_ncx2_pdf(x=11800, df=6700, nc=5300)
```
gives
```
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in log
  # This is added back by InteractiveShellApp.init_path()
0.0
```

In particular, the threshold for these `df` and `nc` values is around `x=11926`, in which case `df2`, `res` before the log term, and the log term itself are:
```
3349.0, 695.3763867996885, -701.5949773095055
```
while at `x=11925` the log term is `-inf`. I note that at `x=11926`, the argument of the log term is
```
ive(df2, xs*ns) / 2.0 = 2.0006578544063762e-305
```
while, as expected for `x=11925`, it is `0.0`.

So it seems that the problem lies in the numerical precision of `ive`. I've tried a few transformations of the form `ive(c*df2, xs*ns)` or `ive(df2, c*xs*ns)`, for some useful scale factor `c`, but had no success so far. Can someone point me to the actual implementation of `ive` in the source? I can't seem to find it.

**Comment by pvanmulbregt** [comment]
`ive` calls `_func_cbesi_wrap_e` (see `cython_special.pyx`) and eventually resolves to the AMOS routine `zbeck` in https://github.com/scipy/scipy/blob/1d6a0b6750a674a6d17abf42a6cc12cb694b7501/scipy/special/amos/zbesk.f#L1

**Comment by mdhaber** [comment]
@mckib2 another one for the list

**Comment by mckib2** [comment]
@mdhaber  Boost does the right thing here as well:
![image](https://user-images.githubusercontent.com/28734319/100526609-c1ff1d80-3187-11eb-8a4a-3377dd15aabc.png)

**Comment by mdhaber** [comment]
@mckib2 would you be interested in making a PR for this? It would be great to have it as an example for future PRs that replace our old distribution code with that of Boost.

**Comment by mckib2** [comment]
> @mckib2 would you be interested in submitting a PR for this? It would be great to have it as an example for future PRs that replace our old distribution code with that of Boost.

Yes, I can do this.  I just submitted gh-15763 and I'm afraid of merge conflicts as I'll be touching same files/same lines for `nxc2`.  I'll wait for that one to merge before I begin work on this one

**Comment by mdhaber** [comment]
All clear!
