### ISSUE TITLE
Rotation.from_euler mixing extrinsic and intrinsic rotations

### ISSUE THREAD

**Issue by Saleh0694** [scipy/scipy#11778]
My issue is about scipy.spatial.transform.Rotation.from_euler
In the description of the first parameter (seq), it's written that {‘X’, ‘Y’, ‘Z’} stand for intrinsic rotations (i.e. the coordinates are attached to the rotating object), and {‘x’, ‘y’, ‘z’} stand for extrinsic rotations. However, upon testing I found out that the opposite is true, i.e. {'X', 'Y', 'Z'} stand for extrinsic rotations.
The Scipy version I'm using: 1.4.1

**Comment by nmayorov** [comment]
@Saleh0694 Of course we have carefully checked such basic thing. Here is a small drawing I've prepared with two intrinsic rotations (`Rotation.from_euler('XY', [90, 90], degrees=True)`): 

![IMG_20200402_233803](https://user-images.githubusercontent.com/7074023/78289398-96199280-753b-11ea-9183-4e8ecb21e448.jpg)

Feel free to reopen, but provide an explanation why you believe your concern is true.
