### ISSUE TITLE
Multi xatol for Nedler-Mead algorithm

### ISSUE THREAD

**Issue by Ziemnono** [scipy/scipy#11775]
**Is your feature request related to a problem? Please describe.**
I'm currently using Scipy for parameter identification of FEM simulation. The algorithm is working fine and minimize my error function according to my parameters (4 parameters for the moment, given by a callback). I want to stop the algorithm when my error function is reaching a tolerance but also a given xatol for my parameters. The problem is xatol is only accepting a float which is troublesome because my parameters have different magnitude orders (e.g. param1 = 1000 and param2 = 0.1). And I want a tolerance of 1 on param1 and 0.01 on param2 for instance.

**Describe the solution you'd like**
What will be convenient is to pass not a float to xatol but a list of float, list should be of the same dimension as the parameters. Then we can set a xatol for each parameter and not a uniform one.

**Describe alternatives you've considered**

**Additional context (e.g. screenshots)**

**Comment by andyfaff** [comment]
Often in minimisation it's a good idea for minimisers to use parameters that all have similar magnitudes. This reduces issues for minimisers that use gradients and hessians. Whilst Nelder-Mead doesn't use gradients (scaling is less important) you can still get the effect you're looking for by scaling your parameter vector:

```
def fun(x):
    param1 = x[0] * 1000
    param2 = x[1] / 0.1
    # use param1 and param2
```
Although this feature would relatively easy to add there are a few considerations:

- we want the `minimize` options to remain uniform across all the solver methods; there are already a plethora of halting criteria keywords out there (xtol, xatol, xrtol, frtol, fatol, tol). If we allow `xatol` to be array-like for Nelder-Mead, then users might expect other methods to have something similar, would an array-like xatol make sense for all of them?
- does it spaghettify the code-base too much if we accept array-like xatol?

**Comment by Ziemnono** [comment]
Hi,
Thank you for the advice that's what I did to overcome this issue and it works as expected.

- I was talking about Nelder-Mead because I'm using this one currently but the principle can be generalized to other optimizers. I think the idea is just to detect if the user uses more than 1 parameter, if yes allows the user to use xatol = [0.1, 0.001] (for example) otherwise let it like before a default uniform tolerance.

- I cannot answer this question yet, it is my first issue in Scipy and I never took a look at the source code properly... Just a new proposition of feature to avoid the scaling trick.

Thank you for your reply
