### ISSUE TITLE
 ValueError: Does not understand character buffer dtype format string ('?')

### ISSUE THREAD

**Issue by sethtroisi** [scipy/scipy#11780]
I'm trying to build and test SciPy in Colab.

I hit an issue with boolean numpy arrays, this happens in ~100 tests

```
_______________________________ TestCSR.test_ne ________________________________
scipy/sparse/tests/test_base.py:369: in test_ne
    check(dtype)
/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py:2279: in new_func
    return func(*args, **kwargs)
/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py:2279: in new_func
    return func(*args, **kwargs)
scipy/sparse/tests/test_base.py:355: in check
    assert_array_equal_dtype(dat != dat2, (datlil != datsp2).todense())
scipy/sparse/base.py:369: in __ne__
    return self.tocsr().__ne__(other)
scipy/sparse/lil.py:478: in tocsr
    _csparsetools.lil_flatten_to_array(self.data, data)
_csparsetools.pyx:135: in scipy.sparse._csparsetools.lil_flatten_to_array
    ???
_csparsetools.pyx:138: in scipy.sparse._csparsetools._lil_flatten_to_array_bool_
    ???
E   ValueError: Does not understand character buffer dtype format string ('?')
```

`_lil_flatten_to_array_bool_` is being generated [in _csparsetools.pyx.in](https://github.com/scipy/scipy/blob/master/scipy/sparse/_csparsetools.pyx.in#L186)

There are some [threads on StackOverflow](https://stackoverflow.com/questions/49058191/boolean-numpy-arrays-with-cython) about boolean arrays in cython so I assume that's the problem. it's weird I'm the first person to hit this (below you'll see I have a very recent cython version maybe that's it) and the [CSR to lil code](https://github.com/scipy/scipy/commit/8675d6e3bb84c813b4ab9bbad7a493e3c51d101c) is fairly new (Feb 28th)

it's possible the solution is to replace the valuetype with uint8 for flatten_to_array_bool_

#### Scipy/Numpy/Python version information:
Building from head of the git repo

Numpy:  1.18.2
Python 3.6.9
Cython: '0.29.16' (seems to be less than a week old)

**Comment by rgommers** [comment]
Seems new indeed, due to gh-11517 perhaps in combination with either Cython or NumPy version. @smola any thoughts on this?

**Comment by smola** [comment]
@rgommers I'll check.

**Comment by smola** [comment]
@sethtroisi I failed to reproduce this so far. Is this problem still present in master? Also, minimum Cython version is now 0.29.18, so I didn't test specifically with latest master and 0.29.16.

**Comment by sethtroisi** [comment]
@smola I can reproduce in [Colab](https://colab.research.google.com/drive/1ot-CwvFchBl1zvb8SkAlz6uz9L1MZRXR?usp=sharing) I suspect it's some environmental setting Colab sets.

```
SciPy: 1.6.0.dev0+c38df7b
NumPy: 1.18.4

Python 3.6.9
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
GNU Fortran (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Cython version 0.29.19 (also fails with 0.29.12)
```

I noticed that
```
extending extension 'scipy.sparse.linalg.dsolve._superlu' defined_macros with [('USE_VENDOR_BLAS', 1)]
```


I'm not sure what other config settings I could investigate.

**Comment by sethtroisi** [comment]
This seems to be fixed in Colab by running `pip install --force-reinstall -U cython`
