### ISSUE TITLE
Passing LowLevelCallable to Optimizers 

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#11783]
In my field of research, we have to perform a large number (millions) of independent small nonlinear optimizations. To speed things up, I compiled the objective with numba which already gave a speedup of 10. Now I am down to about 600 optimizations/second. At this speed, the overhead for calling a Python function which is then passed to for example minpack could make a difference. I did not time it yet but computation of the objective is very fast. 

The overhead could be avoided by passing a LowLevelCallable to the optimizers written in a compiled language directly to bypass the Python layer as it is possible with integration for example. Therefore my question is, if this is a feature which is planned for the future. Another question is how difficult this would be? If I understand it correctly (and I'm not a scipy expert), this would have to be implemented in the bindings for each optimization algorithm individually. I have never worked with Fortran bindings but we have CS students who are eager to learn Python. ;)

PS: as it will come up in the comments, yes I did parallelize problemwise. With enough computation power, I got all my computations done but I think many people would benefit from this enhancement in scipy.optimize.

**Comment by andyfaff** [comment]
I've often thought about this, but didn't go further. It's a great idea, but whatever happens it needs to be rolled out in such a way that it'll be suitable for all the minimisers. Several of them are Fortran based, a lot are pure Python (most of these could be convertible to cython).
I've looked at minimiser overhead before though, and from memory it's not large. I've implemented nelder mead and differential evolution in cython before, and I didn't see a great deal of speedup. That wasn't with a low-level callable though.

**Comment by rgommers** [comment]
> I did not time it yet but computation of the objective is very fast.

Doing this, and then constructing a representative standalone example, would be very useful. Function call overhead is sub-microsecond, so both hard to time well and not common to become important in optimizers. It would be good to know what the gain would be here.

**Comment by dschmitz89** [comment]
Thanks for your replies. 

To clarify: this question was more asked out of interest, I am aware that the "problem" of Python overhead in function evaluations is not urgent and irrelevant for most optimization problems. In our case, one optimization takes around 2 microseconds with between 15 and 50 function/gradient evaluations, that's why it might have an effect for us. The idea came to me as I recently read that in R the minimal time for a function call is some dozens of nano seconds. I think it is less in Python but could not find reliable sources.

Personally I will work on something different soon, therefore I cannot offer a precise timing at the moment. I still thought it might be worth as a recommendation for potential successors. 

@andyfaff: your answer verified that it would indeed have to be implemented for each optimizer. So it would probably required a lot of hard work.

**Comment by rgommers** [comment]
> The idea came to me as I recently read that in R the minimal time for a function call is some dozens of nano seconds. I think it is less in Python but could not find reliable sources.

It's not less, easy to try:

```
In [1]: def f(): pass                                                                          

In [2]: %timeit f()                                                                            
65.5 ns ± 1.24 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

**Comment by dschmitz89** [comment]
Similar numbers for me. WIth numba nopython compilation, the function call becomes even a bit longer (70ns to 58ns). For a function with 5 arguments, the difference increases:  700ns/180ns).

Still, for our problem the total time for function calls spent is then in the order of micro seconds compared to milliseconds for the whole optimization process. So definitely negligible. 

Thanks for pointing this out to me!

From my side this can be closed then

**Comment by rgommers** [comment]
thanks @dschmitz89

**Comment by Nicholaswogan** [comment]
I wrote a little wrapper to Minpack with ctypes which can be called within numba compiled functions: [https://github.com/Nicholaswogan/NumbaMinpack](https://github.com/Nicholaswogan/NumbaMinpack)

Its not perfect, but it will do OK for now. Suggestions/improvements are welcome.
