### ISSUE TITLE
f_oneway should accept a nested list

### ISSUE THREAD

**Issue by erfannariman** [scipy/scipy#11807]
When you want to make a generic function which gathers all the lists with values and you want to compare their means with `f_oneway`, you have to gather them in a list. Apparantly the functions `f_oneway` does not accept a nested list, but only separate lists.

Example:

```
import pandas as pd
from scipy.stats import f_oneway

df = pd.DataFrame({'Weight': [4.17,5.58,5.18,6.11,4.5,4.61,5.17,4.53,5.33,5.14,4.81,4.17,4.41,3.59,5.87,3.83,6.03,4.89,4.32,4.69,6.31,5.12,5.54,5.5,5.37,5.29,4.92,6.15,5.8,5.26],
                   'Group': ['A','A','A','A','A','A','A','A','A','A','B','B','B','B','B','B','B','B','B','B','C','C','C','C','C','C','C','C','C','C'] 
                   })
```
**This works, when we hardcode each separate list**:
```
grps = [d['Weight'].tolist() for _, d in df.groupby('Group')]

l1 = grps[0]
l2 = grps[1]
l3 = grps[2]

F, p = f_oneway(l1,l2,l3)
print(F, p)

4.846087862380136 0.0159099583256229
```
**This does not work, when we pass the nested list `grps` to `f_oneway`**:
```
F, p = f_oneway(grps)
print(F, p)

[nan nan nan nan nan nan nan nan nan nan] [nan nan nan nan nan nan nan nan nan nan]
```

So am I missing something here, or is there any other solution to this?

**Comment by erfannariman** [comment]
I guess I had a brain freeze, solution is to unpack (`*`):
```
grps = [d['Weight'].tolist() for _, d in df.groupby('Group')]

F, p = f_oneway(*grps)
print(F, p)

4.846087862380136 0.0159099583256229
```

**Comment by WarrenWeckesser** [comment]
@erfannariman, thanks for the feedback. In fact, I'm working on an update to the one-way ANOVA code, and it is likely that we'll include a version that implements a basic "group-by" operation, so you'll be able to pass in `df['Group']` and `df['Weight']` (though perhaps converted to lists or numpy arrays) without having to do the splitting into groups yourself.  If you are interested, I can ping you when the pull request hits the scipy github repository.  Feedback on the API would be welcome.

**Comment by erfannariman** [comment]
Yes definitely, I would love to! I am using scipy couple times a week since my new job and have some ideas for contribution, since I am using some methods within my own projects which can be useful for the community as well perhaps. But Im not confident if my code is written well enough and Im not sure how to write good tests since I don't have any background in that.

**Comment by EverLookNeverSee** [comment]
Hi @erfannariman , Don't worry. just try to learn and level up your technical skills.
There is no need to be a professional and experienced programmer, start from small and simple.
Good luck!

**Comment by WarrenWeckesser** [comment]
>  have some ideas for contribution ... Im not confident if my code is written well enough and Im not sure how to write good tests 

We can help with that.  If you have ideas for new features, it is best to discuss them on the mailing list or in a github issue like this one. But once there is agreement that a new feature would be a good fit for scipy, pull requests are welcome.  (As are pull requests to fix bugs.)

If you do end up submitting a pull request, don't be surprised if you are asked to make a lot of changes.  It can take a while to learn all our requirements for documentation, coding style (including PEP 8), unit tests, commit messages, and so on.

**Comment by erfannariman** [comment]
> Hi @erfannariman , Don't worry. just try to learn and level up your technical skills.
> There is no need to be a professional and experienced programmer, start from small and simple.
> Good luck!

Thank you. Good to hear from someone with experience, I will start with small contributions and hopefully will learn on the way what knowledge I am missing.

**Comment by erfannariman** [comment]
> > have some ideas for contribution ... Im not confident if my code is written well enough and Im not sure how to write good tests
> 
> We can help with that. If you have ideas for new features, it is best to discuss them on the mailing list or in a github issue like this one. But once there is agreement that a new feature would be a good fit for scipy, pull requests are welcome. (As are pull requests to fix bugs.)
> 
> If you do end up submitting a pull request, don't be surprised if you are asked to make a lot of changes. It can take a while to learn all our requirements for documentation, coding style (including PEP 8), unit tests, commit messages, and so on.

Yes I will submit a pull request in time. It's not only about the code, also for the documentation or for the docstrings. About the "lot of changes", that's perfectly fine, even better to get feedback and learn! I will use the [contributor guide](https://docs.scipy.org/doc/scipy/reference/dev/contributor/contributor_toc.html) as my guideline for now.

**Comment by erfannariman** [comment]
> @erfannariman, thanks for the feedback. In fact, I'm working on an update to the one-way ANOVA code, and it is likely that we'll include a version that implements a basic "group-by" operation, so you'll be able to pass in `df['Group']` and `df['Weight']` (though perhaps converted to lists or numpy arrays) without having to do the splitting into groups yourself. If you are interested, I can ping you when the pull request hits the scipy github repository. Feedback on the API would be welcome.

Hi @WarrenWeckesser was this change implemented eventually, would love to try it out
