### ISSUE TITLE
documentation of rollaxis

### ISSUE THREAD

**Issue by BruceMaggs** [scipy/scipy#11819]
Hi,

On the web page https://docs.scipy.org/doc/numpy/reference/generated/numpy.rollaxis.html, where you document the rollaxis function, you first say:

Roll the specified axis backwards, until it lies in a given position.

then you write:

start : int, optional
The axis is rolled until it lies before this position. The default, 0, results in a “complete” roll.

There seems to be a contradiction between "lies in a given position" and "lies before this position", or at least the wording is confusing.

As far as I can tell, "lies in a given position" is what the function really does.

Thanks,

Bruce Maggs

**Comment by ilayn** [comment]
@BruceMaggs Thank you for opening the issue. You might want to carry this to NumPy repository instead 

https://github.com/numpy/numpy/issues
