### ISSUE TITLE
`fft.tests.test_numpy.test_multiprocess` hangs on Python3.8 on macOS

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#11827]
#11822 proposes to add macOS testing on a range of Pythons using Github actions. The 3.8 matrix entry kept hanging on `fft.tests.test_numpy`. I've since reproduced the error on my local machine. The specific test it's hanging on is `fft.tests.test_numpy.test_multiprocess`. If I comment out the test everything runs ok.
The reason it's probably failing is that the default context for multiprocessing on macOS for Python 3.8 is 'spawn', it used to be 'fork'.
('fork' is the default for linux, 'spawn' for macOS, 'spawn' for windows)

A check/fix needs to be done for why the test fails with a 'spawn' context.

**Comment by larsoner** [comment]
@andyfaff maybe this?

https://bugs.python.org/issue38501

**Comment by andyfaff** [comment]
@larsoner possibly, I'm not sure.

- The travisCI matrix has an Ubuntu+3.8 entry, and the test doesn't hang on that.

I tried changing the test code to:

```
@pytest.mark.parametrize("func", [fft.fft, fft.ifft, fft.rfft, fft.irfft])
def test_multiprocess(func):
    ctx = multiprocessing.get_context('fork')
    # Test that fft still works after fork (gh-10422)
    with ctx.Pool(2) as p:
        res = p.map(func, [np.ones(100) for _ in range(4)])

    expect = func(np.ones(100))
    for x in res:
        assert_allclose(x, expect)
```

- The test run works if the context is 'fork', but not if it's 'spawn'

I hope the core devs are paying attention to that Python issue, its a real pain.

**Comment by andyfaff** [comment]
I was running those tests with the normal `python runtests.py -s fft`.

If I run the specific test from an interpreter then I have no issues. The test may need a knownfail.

**Comment by peterbell10** [comment]
@andyfaff does the test still fail  if you replace `p.map(func, ...)` with `p.map(np.array, ...)` or something similar. If this isn't the python issue then that should pass.

**Comment by andyfaff** [comment]
@peterbell10 it hangs on that as well. The test, as-is, passes in an interpreter.
