### ISSUE TITLE
How to get Lagrange / lambda multipliers out of 'linprog' optimize subroutine in scipy module ?

### ISSUE THREAD

**Issue by bharat29** [scipy/scipy#11848]
It is required to obtain Lagrangian multipliers while optimizing a linear programming problem.  Kindly help.

Best regards,
Bharat

**Comment by mdhaber** [comment]
Hi @bharat29, thanks for making the request. This is a duplicate of gh-8836, though, so I'm closing. Hopefully we'll add this with gh-11759.

**Comment by bharat29** [comment]
Sure.  Thank you 😊

**Comment by scratchmex** [comment]
Probably worth adding an example with this on the documentation? It is not clear enough until you start searching. I ended up here because of https://stackoverflow.com/questions/61276749/lagrange-multipliers-with-scipy-optimize-linprog

**Comment by mdhaber** [comment]
@scratchmex Do you have a moment to comment on the example proposed in gh-16268?
