### ISSUE TITLE
Ignore NaN with scipy.optimize.curve_fit

### ISSUE THREAD

**Issue by astrophysaxist** [scipy/scipy#11841]
Occasionally I need to fit data that's incomplete (missing values) or perform a fitting task over a grid of 3-D data, i.e. fitting M points for every NxN element, where one of the elements needs to be masked out or ignored.

It may be a good feature to have a flag (or flags) to curve_fit that tell it to ignore NaNs in an array being fit and return NaN when there are no floats/data to fit (i.e. all nans).

I've seen documented that when you drop the check for nan/infs in curve_fit you can silently get nonsensical results. It seems a flag here would provide a way to define the behavior you'd like when nans/inf are present.

**Comment by rgommers** [comment]
Makes sense, there have been issues with this before IIRC. Also there's gh-4777 which asks for nan/inf handling in `leastsq`.

**Comment by astrophysaxist** [comment]
@rgommers I was specifically thinking about NaNs. I only mentioned infs because they’re called out in the documentation I read about the check for flag.
