### ISSUE TITLE
Issues in documentation of scipy.cluster.hierarchy.dendrogram

### ISSUE THREAD

**Issue by ScottNortonPhD** [scipy/scipy#11851]
The keyword argument `leaf_rotation` is misdocumented as `leaf_label_rotation` in [scipy.cluster.hierarchy.dendrogram](scipy/cluster/hierarchy.py#L2026).

**Comment by ScottNortonPhD** [comment]
Further, the documentation of `R['dcoords']` seems to be a copy-paste of the documentation of `R['icoords']`.

**Comment by WarrenWeckesser** [comment]
@ScottNortonPhD, are you looking at the latest version of the documentation?  I don't see those issues in https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.dendrogram.html

**Comment by ScottNortonPhD** [comment]
My mistake, Warren. Somehow Google brought me to the version 0.14 docs without me noticing.

**Comment by WarrenWeckesser** [comment]
No problem, it happens.  It turned out to be fixed already, but thanks for taking the time to report the issue.
