### ISSUE TITLE
Documentation of fit methods for `weibull_min` and `exponweib` is misleading

### ISSUE THREAD

**Issue by nayefahmad** [scipy/scipy#11856]
My issue is about the documentation of the fit methods for the `weibull_min` and `exponweib` distributions. This arose in discussion around [issue 11806](https://github.com/scipy/scipy/issues/11806). 

The documentation of the methods of weibull_min [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.weibull_min.html) (image below) suggests that if a user does not pass a value to `loc`, the default of `loc=0` will be used.

The results below show that this does not appear to be the case. Also, the documentation of the [fit method for the general rv_continous class](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.fit.html#scipy.stats.rv_continuous.fit) states that if no `loc` value is passed, the `_fitstart` method will be called to find a starting guess (not just `loc=0`, for example).

I'm just wondering if the documentation could be a bit clearer here, as it seems contradictory.

#### Reproducing code example:

```
import numpy as np
from scipy import stats

x = [4836.6, 823.6, 3131.7, 1343.4, 709.7, 610.6, 
     3034.2, 1973, 7358.5, 265, 4590.5, 5440.4, 4613.7, 4763.1, 
     115.3, 5385.1, 6398.1, 8444.6, 2397.1, 3259.7, 307.5, 4607.4, 
     6523.7, 600.3, 2813.5, 6119.8, 6438.8, 2799.1, 2849.8, 5309.6, 
     3182.4, 705.5, 5673.3, 2939.9, 2631.8, 5002.1, 1967.3, 2810.4,
     2948, 6904.8]

# these results are not the same: 
stats.weibull_min.fit(x)  # result without passing a value to loc
stats.weibull_min.fit(x, loc=0)  # result with an initial guess for loc 
```

![image](https://user-images.githubusercontent.com/8826614/79174078-6fb2ed00-7dae-11ea-8468-1328a194e5a8.png)

**Comment by tpudlik** [comment]
`weibull_min` inherits its `fit` method from `rv_continuous`, which actually uses `None` as the default values of `loc` and `scale`: https://github.com/scipy/scipy/blob/4774d47f38fa2a3d708132c92f55df761f11f90e/scipy/stats/_distn_infrastructure.py#L2276-L2283

The docstring currently displayed in the documentation is defined as `_doc_fit` near the top of that file.  A much more comprehensive docstring is actually provided with the method itself (starting at [line 2171](https://github.com/scipy/scipy/blob/4774d47f38fa2a3d708132c92f55df761f11f90e/scipy/stats/_distn_infrastructure.py#L2171)).  That longer docstring makes no mention of `loc` and `shape` at all.

**Comment by tpudlik** [comment]
Oops, I should have said, there is no default value of `loc` and `scale`, rather than that the default value is `None`.  If no value is provided by the caller, these parameters are estimated.
