### ISSUE TITLE
Occurrence of nan values when using multinomial.pmf from scipy.stats?

### ISSUE THREAD

**Issue by bunkerj** [scipy/scipy#11860]
Running a small experiment, I noticed that if the sum of the parameters that are passed to multinomial.pmf are even slightly above 1, then the return value is nan.

See the example below:
```python3
import numpy as np
from scipy.stats import multinomial as multi_s


def safe_multi(x, params):
    params_sum = params.sum()
    safe_params = params / params_sum if params_sum > 1 else params
    return multi_s.pmf(x, sum(x), safe_params)


params1 = np.array(
    [0.21310660657549002, 0.21310660657549002, 0.21310660657549002,
     2.8699968847179538e-06, 0.0023286820110742764, 2.8699968847179538e-06,
     0.0023286820110742764, 2.8699968847179538e-06, 2.8699968847179538e-06,
     0.0023258120141895593, 0.0016006555371205703, 0.0023258120141895593,
     0.0016006555371205703, 0.04333851102588555, 0.04333851102588555,
     0.04333851102588555, 0.04333851102588555, 0.04333851102588555,
     0.04333851102588555, 0.04333851102588555, 0.04333851102588555,
     0.0007251564770689873, 0.0007251564770689873, 7.377915317967555e-27,
     7.377915317967555e-27])

params2 = np.array(
    [0.3333333333333332, 0.3333333333333332, 0.3333333333333332,
     2.931077467598623e-93, 6.532951191692606e-25, 1.4080539652716124e-224,
     6.532951191692606e-25, 1.4080539652716124e-224, 1.4080539652716124e-224,
     6.532951191692606e-25, 6.532951191692606e-25, 6.532951191692606e-25,
     6.532951191692606e-25, 3.5127398105835854e-17, 3.5127398105835854e-17,
     3.5127398105835854e-17, 3.5127398105835854e-17, 3.5127398105835854e-17,
     3.5127398105835854e-17, 3.5127398105835854e-17, 3.5127398105835854e-17,
     7.860388790608641e-191, 7.860388790608641e-191, 2.931077467598623e-93,
     2.931077467598623e-93])

samples = np.array(
    [1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])

result1_scipy = multi_s.pmf(samples, samples.sum(), params1)
result2_scipy = multi_s.pmf(samples, samples.sum(), params2)
print(result1_scipy, result2_scipy)
print(params1.sum(), params2.sum())

print('-----------------')

result1_scipy_sum = multi_s.pmf(samples, samples.sum(), params1 / params1.sum())
result2_scipy_sum = multi_s.pmf(samples, samples.sum(), params2 / params2.sum())
print(result1_scipy_sum, result2_scipy_sum)
print((params1 / params1.sum()).sum(), (params2 / params2.sum()).sum())

print('-----------------')

result1 = safe_multi(samples, params1)
result2 = safe_multi(samples, params2)
print(result1, result2)

```

With the output:
```
nan 0.22222222222222202
1.0000000000000002 0.9999999999999999
-----------------
0.058068684987554825 nan
0.9999999999999998 1.0000000000000002
-----------------
0.058068684987554825 0.22222222222222202
```

Is there a better way I can deal with the numerical overflow that can occur from the parameters? My safe_multi() wrapper seems to do the trick, but I am interested in the best practices of dealing with this.

Also, I found an example, shown below, that seems to always return nan despite the parameters summing to 1.
```python3
c = np.array(
    [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])

params = np.array(
    [0.02702702702702703, 0.02702702702702703, 0.0, 0.0, 0.0,
     0.04054054054054054, 0.0, 0.0, 0.0, 0.0, 0.06756756756756757,
     0.0945945945945946, 0.06756756756756757, 0.06756756756756757,
     0.04054054054054054, 0.04054054054054054, 0.06756756756756757,
     0.06756756756756757, 0.013513513513513514, 0.013513513513513514, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.04054054054054054, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.013513513513513514, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.04054054054054054, 0.013513513513513514,
     0.013513513513513514, 0.013513513513513514, 0.013513513513513514, 0.0, 0.0,
     0.0, 0.0, 0.013513513513513514, 0.013513513513513514, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.02702702702702703, 0.02702702702702703, 0.013513513513513514,
     0.013513513513513514, 0.0, 0.0, 0.0, 0.0, 0.0, 0.013513513513513514, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.013513513513513514, 0.013513513513513514, 0.013513513513513514,
     0.013513513513513514, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.013513513513513514,
     0.0, 0.0, 0.0, 0.0, 0.013513513513513514, 0.013513513513513514, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
     0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])

print(multi_s.pmf(c, c.sum(), params))
print(multi_s.pmf(c, c.sum(), params / params.sum()))
print(params.sum())
```

Output:
```
nan
nan
1.0
```

Having analyzed the scipy code, it seems that the culprit is on line 3012 of _multivariate.py:
```python3
p[..., -1] = 1. - p[..., :-1].sum(axis=-1)
```

This line ensures that the parameters sum to 1 by setting the last parameter to an appropriate value. In the example above, this adds an extremely small negative value for the last parameter which then gets flagged as a problem down the road. To ensure that this condition is satisfied, would it not be possible to divide by the sum of the parameters as opposed to performing subtraction?

**Comment by mdhaber** [comment]
> To ensure that this condition is satisfied, would it not be possible to divide by the sum of the parameters as opposed to performing subtraction?

That sounds like a good idea, but I don't think we can change the behavior in general as that would not be backwards compatible. I think, though, that we can do it for rows that sum to > 1 and perform the subtraction for rows that are  < (strictly) 1. I checked, and that would work for all of your examples. 

Alternatively, we could add an optional parameter for the normalization method. Subtraction would be the default, but users could opt to divide by the sum of the row.

As a user, which would you prefer?

**Comment by bunkerj** [comment]
I agree with the decision to implement the first option. This would definitely fix the issue I was dealing with. I also think that, in general, it's better from a user perspective to abstract away such implementation details. I was actually going to submit a PR myself, but I see you beat me to it!

**Comment by mdhaber** [comment]
Thanks @bunkerj but feedback on #12575 suggested that normalization by division was not the desired approach. It sounds like more discussion is needed, but I have never used multinomial so I don't think I have much to say. If the conclusion is to normalize by division after all, I'd be happy to revive the PR.

**Comment by helmutsimon** [comment]
The current implementation, to adjust the last element of the probability vector, has a problem is the last element of the probability vector was originally zero. It would be better to adjust the argmax element. I am not confident about dividing by the sum, as it seems problems can occur even after this is done.

**Comment by mdhaber** [comment]
There are several comments here and in the linked (closed) PR that suggest that automatically normalizing the probability array would be desirable if it worked reliably. For instance, I can imagine wanting to specify the relative probabilities with integers. So I'd suggest:
* If sum is not close to 1, raise a `FutureWarning` announcing the intent to change to normalization. Users can either ignore/suppress the warning (and accept the change in behavior) or manually make the probabilities sum sufficiently close to 1 now.
* Figure out how to normalize reliably (avoiding the nans). Use Hypothesis to try to find counter-examples.
* In 1.12.0, change the behavior. 

@tirthasheshpatel @tupui @chrisb83 what do you think?

**Comment by tupui** [comment]
API wise, I find this automatic scaling behaviour a bit strange. I would be in favour of deprecating this. I prefer to be explicit saying it should sum to 1 or have a `normalize` parameter.

**Comment by mdhaber** [comment]
We can generate similar pathological examples like:

<details>

```
import numpy as np
from scipy.stats import multinomial

for n in range(2, 1000):
    print(n)
    rng = np.random.default_rng(8879715917488330089)

    p = rng.random(n)
    p[-1] = 1e-30
    p /= np.sum(p)
    x = np.ones(n)
    logpmf = multinomial.logpmf(x, n, p)

    p /= np.sum(p)
    logpmf2 = multinomial.logpmf(x, n, p)
    
    assert not (np.isnan(logpmf) & np.isnan(logpmf2))
```

</details>

`n=88` is a good example on my machine, at least. 

```python3
import numpy as np
from scipy.stats import multinomial
n = 88
rng = np.random.default_rng(8879715917488330089)

p = rng.random(n)
p[-1] = 1e-30

p /= np.sum(p)
x = np.ones(n)
logpmf = multinomial.logpmf(x, n, p)

p /= np.sum(p)
logpmf2 = multinomial.logpmf(x, n, p)

assert np.isnan(logpmf)
assert np.isnan(logpmf2)
assert p.sum() == 1
```

Clearly there is some nonzero probability of this occurring, but SciPy makes it difficult to calculate. We can tease it out by adding a little random noise to the calculation.

<details>

```
import numpy as np
from scipy.stats import multinomial
import matplotlib.pyplot as plt
n = 88
rng = np.random.default_rng(8879715917488330089)

p = rng.random(n)
p[-1] = 1e-30
p /= np.sum(p)
x = np.ones(n)

logpmfs = []
for i in range(10000):
    noise = rng.normal(scale=1e-16)
    p2 = p.copy() + noise
    p2 /= p2.sum()
    logpmf = multinomial.logpmf(x, n, p2)
    if np.isfinite(logpmf) and logpmf != 0:
        logpmfs.append(logpmf)

plt.hist(logpmfs)
plt.xlabel("Calculated logpmf")
plt.ylabel("frequency")
```

</details>

![image](https://user-images.githubusercontent.com/6570539/185812475-cd4e874e-bd8f-4eef-b8e7-7d498a8a1a4a.png)

There's still a problem, though, because this is the logpmf we would when the last element is on the order of `1-16`, not `1e-30`. (If you dig into the code, you can see that the last element gets changed to `1.1102230246251565e-16`, `2.220446049250313e-16`, `3.3306690738754696e-16`, or `4.440892098500626e`. )

```
p3 = p.copy()
p3[0] -= 3e-16
p3[-1] = 1e-16
multinomial.logpmf(x, n, p3)  # -131.01713179
```

We'd prefer it if SciPy would just get out of the way and not do anything to the last element as long as the elements sum to nearly 1. I'll open a PR to do that.
