### ISSUE TITLE
Typo in the docstring of simps()

### ISSUE THREAD

**Issue by hay-k** [scipy/scipy#11875]
In the definition of the function `simps` under `scipy/integrate/quadrature.py` the docstring says
```
    dx : int, optional
        Spacing of integration points along axis of `y`. Only used when
        `x` is None. Default is 1.
```
`dx` is the spacing along the `x` axis, so the correct formulation should be
```
    dx : int, optional
        Spacing of integration points along axis of `x`. Only used when
        `x` is None. Default is 1.
```

**Comment by distroinfinity** [comment]
I would like to correct this typo to get familiar with the workflow as I am new to open source.
