### ISSUE TITLE
The upper code lines are dead code

### ISSUE THREAD

**Issue by maheshwarigagan** [scipy/scipy#11884]
https://github.com/scipy/scipy/blob/f2ec91c4908f9d67b5445fbfacce7f47518b35d1/scipy/stats/stats.py#L3873-L3876

**Comment by ilayn** [comment]
Thanks for this @maheshwarigagan. Indeed they are dead. Care to open a PR?

**Comment by maheshwarigagan** [comment]
@ilayn Yes, I will raise a PR shortly

**Comment by pvanmulbregt** [comment]
These issue also happens to be addressed by the rewrite of `kstest/ks_2samp` in gh-11710.
