### ISSUE TITLE
Dynamically linking C/C++ extensions and `_pre_build_hook` for `build_clib`

### ISSUE THREAD

**Issue by mckib2** [scipy/scipy#11887]
Ref #11759 

The issue is two-fold:
- Is there a way to link multiple extensions?  AND/OR...
- Is there a way to pass c++11/14 flags to static library (i.e., `config.add_library` or `build_clib`)

Why is this a scipy issue?  Because scipy uses its own "build" system and I am only interested in using this.  It has its own ways of constructing setup configurations and uses it's own classes derived from `build_ext`, `build_clib`, etc.

C/C++ extensions can be built using appropriate c++11/14 flags by providing a `_pre_build_hook` function that is called during the `build_ext` command.

As far as I am aware, there is no way to reliably link shared libraries generated from C/C++ extensions using distutils, setuptools, or numpy.distutils in a platform agnostic way (I have not seen this needed previously in scipy and no amount of googling on my part seems to find anything useful).  You can jury rig something to work on Linux but it will break on Windows, Mac, presumably other operating systems.

Static libraries however do seem to work for this purpose, the only drawback is that there is no way to to run a `_pre_build_hook` for a static library.  [It looks like there might be support](https://github.com/scipy/scipy/blob/master/setup.py#L300), but I haven't seen any examples in the repo of how to do this or been able to figure out how to do this on my own.

Here's a concrete description of what I'd like achieve:
- HiGHS builds 3 shared libraries from C and C++ sources: `basiclu` (C), `ipx` (C++11), and `highs` (C++11)
- `ipx` should be dynamically linked to `basiclu` and `highs` should be dynamically linked `ipx`
- The HiGHS interface also builds a Cython wrapper extension named `highs_wrapper` (C++11) and should be linked to `highs`
- There is also another Cython wrapper extension `mpswriter` that should be linked to `highs` as well

The naive solution of compiling all the sources together will not work: clang will throw an error if `-std=c++11` is used for C sources of `basiclu`.

As mentioned, there is no cross-platform solution I am aware of to build `basiclu` as an extension and link to additional extensions `ipx`, `highs`, `highs_wrapper`, and `mpswriter`, so we must build `basiclu` as a static library.  This will work because no extra compile flags are required for `basiclu`.  For the same reason, we might want to build `ipx` and `highs` as static libraries as well -- but we can't because the c++11 compile flag needs to be used and libraries do not have a `_pre_build_hook`.

The current solution being used in #11759 is to build `basiclu` as a static library and build `highs_wrapper` and `mpswriter` using all sources required from `ipx` and `highs` and statically linking `basiclu`.  This of course leads to sources being built multiple times between `highs_wrapper` and `mpswriter`, slowing the build process and introducing more points of error during maintenance and upgrades.

**Comment by rgommers** [comment]
> Static libraries however do seem to work for this purpose, the only drawback is that there is no way to to run a `_pre_build_hook` for a static library. [It looks like there might be support](https://github.com/scipy/scipy/blob/master/setup.py#L300), but I haven't seen any examples in the repo of how to do this or been able to figure out how to do this on my own.

How about https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/eigen/arpack/setup.py#L21?

**Comment by mckib2** [comment]
Thanks @rgommers .  I wasn't aware of this example, thanks for pointing it out.

When I mentioned that I was not "able to figure out how to do this on my own," I did try passing in the `_pre_build_hook` into `config.add_library` and as far as I could tell it was never called.  I tried print statements and writing out to logs, but I could not find any evidence that the hook was actually called.  Any ideas what I might be doing wrong?

**Comment by rgommers** [comment]
Hmm, you are building all of SciPy in the usual fashion? If so, maybe check first if https://github.com/scipy/scipy/blob/master/setup.py#L562 gets executed. If you have a branch with what you're trying, I could have a look at it perhaps.

**Comment by mckib2** [comment]
I am doing:
```
python setup.py build_ext --inplace
```

Branch: https://github.com/mckib2/scipy/tree/clib-prebuild-hook

`scipy/optimize/_highs/setup.py` has library `basiclu` which tried to call a `_pre_build_hook` [here](https://github.com/mckib2/scipy/blob/clib-prebuild-hook/scipy/optimize/_highs/setup.py#L92)

**Comment by mckib2** [comment]
Alright, I see the problem.  I forked scipy about a month ago so didn't have the latest setup.py.  It appears the support for pre_build_hook for build_clib is quite recent according to this git blame: https://github.com/scipy/scipy/blame/dc70c68d4fd9452befbf529414f8dd11209193ca/setup.py#L562

Pulling changes from upstream I can now get this to work.  Thanks for taking a look!

**Comment by rgommers** [comment]
Thanks for the update, and sorry I didn't manage to look at it last week!
