### ISSUE TITLE
scipy doesn't compile in scipy-dev container

### ISSUE THREAD

**Issue by matthias-k** [scipy/scipy#11891]
Scipy doesn't compile in the scipy-dev container as described [in the documentation](https://docs.scipy.org/doc/scipy/reference/dev/contributor/quickstart_docker.html).

#### Reproducing code example:
from the directory where scipy master is checked out:
```
docker run -it --rm -v $PWD/:/home/scipy scipy/scipy-dev /bin/bash
```
and then inside the container:
```
cd /home/scipy
pip3.7 install numpy cython pytest pybind11
python3.7 setup.py build_ext --inplace
```

#### Error message:
the build_inplace command fails with a very long error message. The full output can be found here: 
[build.log](https://github.com/scipy/scipy/files/4498916/build.log). The last part of the output is as follows:
```
error: Command "/usr/bin/gfortran -Wall -g -Wall -g -shared build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/linalg/_interpolativemodule.o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/scipy/linalg/fortranobject.o [... omitting lots of files and flags ...] -lcblas -latlas -lf77blas -lcblas -lgfortran -o build/lib.linux-x86_64-3.7/scipy/linalg/_interpolative.cpython-37m-x86_64-linux-gnu.so -Wl,--version-script=build/temp.linux-x86_64-3.7/link-version-scipy.linalg._interpolative.map" failed with exit status 1
```

#### Scipy/Numpy/Python version information:
numpy version 1.18.2, python version sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0), scipy from current master (e9ec381d90ad7121207e1dd91a68e94a9b363834)

**Comment by pv** [comment]
You'll need to clean up the extra files you have lying under scipy/linalg/src/id_dist/src/.
Build with clean Scipy checkout, or run `git clean -f -d -x scipy/linalg/src/id_dist/src` (removes all changes in that directory that are not committed).

**Comment by matthias-k** [comment]
Ah, I see. Thanks!
