### ISSUE TITLE
newton: Allow passing booleans for fprime and fprime2

### ISSUE THREAD

**Issue by Makman2** [scipy/scipy#11893]
As many other functions offer (namely `root`), making the parameters `fprime` and `fprime2` of the `newton` also accept booleans or rather additionally a `True` argument. That would be extremely beneficial. Sometimes computation of derivatives is cheaper from inside the given function than outside. `newton` should be no exception and allow that too conveniently.

**Comment by pvanmulbregt** [comment]
You can use `optimize.root_scalar` for this.  E.g.
```
def f_and_fprime(x):
 return x*x-1, 2*x

optimize.root_scalar(f_and_fprime, method='newton', x0=2, fprime=True)
```
produces
```
      converged: True
           flag: 'converged'
 function_calls: 6
     iterations: 6
           root: 1.0
```

**Comment by Makman2** [comment]
Perfect, never mind then :)

(For clarification where my issue comes from: I thought before `newton` was capable of multivariate problems, but as stated in https://github.com/scipy/scipy/issues/12006 it is just able to vectorize the input and solve effectively multiple problems at once - hence not the same. :+1:)
