### ISSUE TITLE
Add full pivoting LU decomposition -> PAQ = LU

### ISSUE THREAD

**Issue by iuryt** [scipy/scipy#11903]
**Is your feature request related to a problem? Please describe.**
No. This is just a suggestion of feature.

**Describe the solution you'd like**

I couldn't find a way to do full pivoting LU decomposition using Scipy. This is important for academic purposes.

**Describe alternatives you've considered**

```
from scipy.linalg import lu
P,Q,L,U = lu(A,full=True)
```

**Additional context (e.g. screenshots)**

**Comment by mdhaber** [comment]
gh-10797 adds a lapack routine for this. It's merged into master and will be released with SciPy 1.5.0 in a few weeks.

**Comment by ilayn** [comment]
partial pivoting is as good as full pivoting and quite less expensive. Why would you need full pivoting if I may ask?

**Comment by iuryt** [comment]
Hi @ilayn 
I'm doing a course for Numerical Linear Algebra algorithms and we are having to code this and compare it to the built-in implementations. As a Python person, I just thought I cannot accept having to use a Matlab function because I couldn't find it in Python. haha

**Comment by mdhaber** [comment]
BTW if you can't build from source you can also use the [autogenerated Cython binding](https://docs.scipy.org/doc/scipy/reference/linalg.cython_lapack.html).

**Comment by ilayn** [comment]
Note that matlab doesn't offer it either;only for sparse matrices. So you are still in good position as a pythonista.

**Comment by mdhaber** [comment]
The `?getc2` wrapper merged a while ago, so I thought we should close this. Since it doesn't look like it will be exposed via `scipy.linalg.lu`, I thought it would be helpful to include an example that gets the output into the form you were looking for.

```python3
import numpy as np
from scipy import linalg
rng = np.random.default_rng(2349239810823)
n = 100
eye = np.eye(n)
A = rng.random((n, n))

# "DGETC2 computes an LU factorization with complete pivoting of the
# n-by-n matrix A..."
getc2 = linalg.get_lapack_funcs('getc2', (A,))
lu, ipiv, jpiv, info = getc2(A, overwrite_a=0)

# "The factorization has the form A = P * L * U * Q,
# where P and Q are permutation matrices..."

# "The pivot indices; for 1 <= i <= N, row i of the
# matrix has been interchanged with row IPIV(i)."
P = eye.copy()
for i, row in enumerate(ipiv):
    P[i], P[row] = P[row].copy(), P[i].copy()

# "The pivot indices; for 1 <= j <= N, column j of the
# matrix has been interchanged with column JPIV(j)."
Q = eye.copy()
for i, col in enumerate(jpiv):
    Q[:, i], Q[:, col] = Q[:, col].copy(), Q[:, i].copy()

# (The documentation is phrased in terms of row/column interchanges
#   of A, so we need transpose to bring these onto the right side.) 
P = P.T  
Q = Q.T

#  "L is lower triangular with unit diagonal elements..."
L = np.tril(lu, -1) + eye
#  "...and U is upper triangular."
U = np.triu(lu)

np.testing.assert_allclose(A, P @ L @ U @ Q)
```

I hope the course went well... like four years go : )
