### ISSUE TITLE
LinearOperator should have ndim attribute 

### ISSUE THREAD

**Issue by Mazay0** [scipy/scipy#11908]
**Is your feature request related to a problem? Please describe.**

In some cases `LinearOperator` can not be used in place of matrices because it doesn't have `ndim` attribute.

**Describe the solution you'd like**

It would be convenient, if  `LinearOperator` had `ndim` attribute, that is always equal `2`.

**Describe alternatives you've considered**

The simplest alternative is `len(op.shape)`, but it looks worse than `op.ndim`.
Also here https://github.com/scikit-learn/scikit-learn/pull/16463#discussion_r411423147 folks worry about performance penalty.

**Additional context (e.g. screenshots)**

**Comment by pv** [comment]
Should be simple to add (class attribute). PR welcome (with test added
preferable).

**Comment by Mazay0** [comment]
> Should be simple to add (class attribute). PR welcome (with test added preferable).

OK, I will make a PR ASAP.
