### ISSUE TITLE
Delete misleading v1.2.1 branch

### ISSUE THREAD

**Issue by dimrozakis** [scipy/scipy#11917]
About a week or so ago, a branch named `v1.2.1` was pushed that points to 4774d47f38fa2a3d708132c92f55df761f11f90e with commit date 2020-04-15. This "conflicts" with the release tag `v1.2.1` which points to c3fa90dcfcaef71658744c73578e9e7d915c81e9 with commit date 2019-02-08.

The existence of the the identically named branch makes it trickier to check out the tag. Also, if one tries to clone the tag directly, as I was doing in a build script, with something like `git clone --branch=v1.2.1 --depth=1 https://github.com/scipy/scipy.git`, they'll get the branch instead which points to a more recent commit.

Please delete branch `v1.2.1` to avoid such confusion.

Steps to "reproduce":
```
$ git clone  https://github.com/scipy/scipy.git 
Cloning into 'scipy'...
remote: Enumerating objects: 165801, done.
remote: Total 165801 (delta 0), reused 0 (delta 0), pack-reused 165801
Receiving objects: 100% (165801/165801), 89.03 MiB | 4.32 MiB/s, done.
Resolving deltas: 100% (128514/128514), done.
$ cd scipy
$ git branch -r | grep v1
  origin/v1.2.1
$ git show --oneline origin/v1.2.1
4774d47f3 (origin/v1.2.1) Merge pull request #11861 from szcf-weiya/patch-2
$ git show --oneline refs/tags/v1.2.1
tag v1.2.1

v1.2.1
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAABAgAGBQJcXcUhAAoJELD/41ZX0J71cA0P/R60eBnXYbppm1U+bnNtb8Tb
7NhMZnZwLbI5Yk9JvOaqO+rYIhQHnXTLCNh7srtGymAYoa28F1X037nf9V2Kk4Rw
/6TefpSto0U9s+P79x/ii9qjkt+S/mYvSzYGO033HEsdtUTF5u3AUlIVTJcXQm/y
YfYoSVGow69eZXTMHfvd8Y26wnd3SOcz+Hor9h/ePciUdO2avYNcKJ+bAfU5h8z9
dV3jpt5+V/x2v4IEv8xI/zWKu1YfZN5RnDS/03OUMe95abYWOlRp/5PsJ6iWy1Ik
/OEvcqpNBJNArpPyplDPs96LaEHKhvQLVUKAramoHGQsjcmpjK7KnZvD3/a4rfy+
15XQOcb0LoDLLRiWKF85ctsAMa48du27iBf9r81ozp28hSNaFZKeV5vBdPBrGAER
OS9VwYK2lmMdw6gGumB98o8wsVb1x7y2b73YDSilA6QPs+z5eV/Q2R2vz+2FG9wO
J6P9W28kDm7zhXl9rBwez8Dwm+KjTOvGVz5ZYRGWww36VyOFxpsZAKh7SyYP7LjR
oRgAh9Sgx134eW8IAVY02njIFpqCN88KjTjdNr0KGpUjZbbIXnKv0OtUQ0xlkuCn
8QHSmwxuuDR3nOKuG3tFf2jN7FQAZcWPtwrMpu/4qpMJwzZWGtYkW4Ww2jplVz/q
rDcgdXZKTS/1tYDIoqb1
=gh8J
-----END PGP SIGNATURE-----
c3fa90dcf (tag: v1.2.1) Merge pull request #9787 from tylerjereddy/issue_9777

```

Also, from github's UI, currently https://github.com/scipy/scipy/tree/v1.2.1 & https://github.com/scipy/scipy/releases/tag/v1.2.1 point to different commits.

**Comment by pv** [comment]
Thanks, deleted. (`git push upstream-push :refs/heads/v1.2.1` for reference)
