### ISSUE TITLE
Why scipy.optimize.leastsq only provides a solver？

### ISSUE THREAD

**Issue by 1470391328** [scipy/scipy#11913]
I checked the official documentation and found that leastsq does not provide additional solver options, why not provide other solvers like the optimize.minimize function.The only valid information I got was ‘“leastsq” is a wrapper around MINPACK’s lmdif and lmder algorithms.”

**Comment by mdhaber** [comment]
You're right that `leastsq` could support other solvers, but as you say, right now it is just a wrapper around MINPACK, a library of Fortran routines tailored to solving this type of problem.

Note that there is also [scipy.optimize.least_squares](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.least_squares.html#scipy.optimize.least_squares), which supports a few other methods.

If you want to try to use the `minimize` optimizers, you can write your `my_leastsq` routine. Maybe something like:

```
from scipy.optimize import minimize
import scipy.linalg
import numpy as np

np.random.seed(0)
def my_leastsq(fun, x0, method):

    def sum_squares(xi):
        return np.sum(fun(xi)**2)

    return minimize(sum_squares, x0, method=method)

A = np.random.rand(10, 5)
b = np.random.rand(10)
x0 = np.random.rand(5)

def fun(x):
    return A @ x - b

res = my_leastsq(fun, x0, method='slsqp')
x2, _, _, _ = scipy.linalg.lstsq(A, b)
print(x2 - res.x)
```

**Comment by 1470391328** [comment]
Thanks you very much!😁

**Comment by sturlamolden** [comment]
There are many ways to solve the non-linear least squares problem. Currently we wrap MINPACK’s  Levenberg-Marquardt implementation. There are of course other options, such as Nelder-Mead, Quasi-Newton (BGFS), Newton’s method, IRLS, etc. One could even consider a Levenberg-Marquardt solver in Python, which presumably would be faster because we would use LAPACK for QR (or SVD, or Cholesky) instead of MINPACK’s unoptimized QR solver. So why? Well, this is how it is, but ```scipy.optimize``` provides many optimizers you can use for the (non-linear) least squares problem.

**Comment by fangxu622** [comment]
I don't find Gauss-Newton method in scipy. optimize. where is it ? @sturlamolden

**Comment by sturlamolden** [comment]
@fangxu622 

Maybe it is not there, but it is not like it is hard to write one. Question is, can you do it in five lines of code or do you need ten? 

What it amounts to is to iterate on
```Python
    betas[:,s+1] = betas[:,s] - np.linalg.pinv(Jr) @ r @ betas[:,s]
    # recompute residuals and Jacobi from r = y - f(X, betas[:,s+1]), increment s
```
or 
```Python
    betas[:,s+1] = betas[:,s] + np.linalg.pinv(Jf) @ r @ betas[:,s]
    # recompute r and Jf and increment s
```
with ```Jr``` being the Jacobi or ```r``` and ```Jf``` being the Jacobi of ```f```. Personally I think it is often more convinient to compute ```Jf```, but ```scipy.optimize.leastsq``` wants ```Jr```. Anyhow, Levenberg-Marquardt is an improved Gauss-Newton so implementing Gauss-Newton might not be very useful. You will possibly end up modifying it to Levenberg-Marquardt anyway, or just use ```scipy.optimize.leastsq```. 

You can implement Levenberg-Marquardt from the code above by observing that ```np.linalg.pinv(J)``` is equal to ```np.linalg.inv(J.T@J) @ J.T``` if the columns of ```J``` are linearly independent, and now just add a Tikhonov regularization to ```J.T@J```. The only advantage of doing this in Python is that you get to use LAPACK and BLAS, which is probably linked to MKL or OpenBLAS, and thus might be a bit more efficient than the unoptimized linear algebra in  ```scipy.optimize.leastsq```.
