### ISSUE TITLE
Documentation missing for what M is in init argument

### ISSUE THREAD

**Issue by pooraniravi** [scipy/scipy#11910]
Is M an initial population of x?

**Comment by WarrenWeckesser** [comment]
We need some more context for this question.  What `M` are you asking about?

**Comment by pooraniravi** [comment]
I am referring to the argument 'init' that is passed to differential evolution. Init has M followed by Len(x). So, is M just the initial population of x? What is M in this context?

**Comment by WarrenWeckesser** [comment]
For anyone looking for `M`, you can find it in https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.differential_evolution.html; scroll down to the description of `init` in the *Parameters* section of the docstring.

**Comment by andyfaff** [comment]
`M` is the number of individuals in the population. It should be something like `popsize * len(X)`
