### ISSUE TITLE
bug in minimize_scalar when bounds are equal

### ISSUE THREAD

**Issue by TaZi-loh** [scipy/scipy#11918]
when the function scipy.optimize.minimize_scalar is called with two bounds both being equal to 0.0, the code crashes with 

```
File "/software/zis2rng/anaconda/envs/lat_graph_dyn/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 1880, in _minimize_scalar_bounded
    if np.isnan(xf) or np.isnan(fx) or np.isnan(fu):
UnboundLocalError: local variable 'fu' referenced before assignment
```

this is due to the fact, that he never enters the optimization loop. Maybe one would like to check for equal bounds in the beginning, give out a warning and return the bound as the solution.

**Comment by andyfaff** [comment]
I think this particular bug was dealt with in #11208
