### ISSUE TITLE
ENH: special/integrate: Lebedev quadrature 

### ISSUE THREAD

**Issue by schneiderfelipe** [scipy/scipy#11929]
I would like to request a function that could return weights and points for the [Lebedev quadrature](https://en.wikipedia.org/wiki/Lebedev_quadrature) (doi:[10.1016/0041-5553(76)90100-2](https://doi.org/10.1016/0041-5553(76)90100-2)).

This quadrature solves the problem of integrating on the surface of the three-dimensional unit sphere. It is one of the [fastest known methods](https://cbeentjes.github.io/files/Ramblings/QuadratureSphere.pdf) of doing this. This quadrature (especially when combined with a one-dimensional integration scheme for the radial coordinate for integrating the whole space) has applications in many fields, including computational/quantum chemistry and neutron transport.

My suggestion is to have a function `roots_lebedev` analogous to [`roots_legendre`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.roots_legendre.html), but returning a two-dimensional array instead of a one dimensional.

Alternatives for using the Lebedev quadrature in Python are either reading the [precalculated data points](https://people.sc.fsu.edu/~jburkardt/datasets/sphere_lebedev_rule/sphere_lebedev_rule.html) directly from files or using [another Python library](https://github.com/nschloe/quadpy) that does so. But it would be nice to have something in SciPy, mainly due to the simplicity and elegance of the `scipy.special.roots_*` methods.

**Comment by Irratzo** [comment]
(User, not dev) Thank you for the request @schneiderfelipe. As it has been four years, I guess this has not been adressed yet. I just wanted to add that there is another newer library that seems to be well-designed and to take a similar approach like quadpy in terms of performance, but just for Lebedev quadrature. It is called PyLebedev ([PyPI](https://pypi.org/project/pylebedev/), [GitHub](https://github.com/ifilot/pylebedev), [Docs - Usage](https://pylebedev.imc-tue.nl/usage.html)).
