### ISSUE TITLE
Discrete Lyapunov solving "AXA'-X=-Q" or "A'XA-X=-Q". 

### ISSUE THREAD

**Issue by rperezibacache** [scipy/scipy#11921]
Seems that the solver for 'solve_discrete_lyapunov(A,Q)' solves "AXA' -X=-Q" instead as the manual describes "A'XA -X=-Q". Can you please confirm it.

Thanks,
Ricardo.

**Comment by ilayn** [comment]
@rperezibacache I think you are looking at an old version of docs. Here it is correct http://scipy.github.io/devdocs/generated/scipy.linalg.solve_discrete_lyapunov.html#scipy.linalg.solve_discrete_lyapunov
