### ISSUE TITLE
DOC: signal: Wrong description for sepfir2d, cspline2d, qspline2d

### ISSUE THREAD

**Issue by AtsushiSakai** [scipy/scipy#11928]
My issue is about ...

The descriptions for sepfir2d, cspline2d, qspline2d looks wrong in the scipy.signal page:

<img width="773" alt="SS 2020-04-24 at 21 27 14" src="https://user-images.githubusercontent.com/3813847/80212699-f13e3100-8672-11ea-8e28-9edf64c92497.png">

#### Scipy/Numpy/Python version information:

DevDoc has this issue. 
- Signal processing (scipy.signal) — SciPy v1.5.0.dev0+4b3eac2 Reference Guide http://scipy.github.io/devdocs/signal.html

**Comment by WarrenWeckesser** [comment]
@AtsushiSakai, thanks for reporting the issue.  Those docstrings are defined in the C extension module [`splinemodule.c`](https://github.com/scipy/scipy/blob/5bd4bfce8b8a84ef63f9b67b20429f5ef6aace72/scipy/signal/splinemodule.c).

Those docstrings should be updated to conform to the [docstring standard](https://numpy.org/devdocs/docs/howto_document.html).
