### ISSUE TITLE
scipy.signal.remez ignores the weight parameter

### ISSUE THREAD

**Issue by snedeljkovic** [scipy/scipy#11939]
Here is a sample program used to design a low pass filter using `scipy.signal.remez`:
```
from scipy.signal import remez
import matplotlib.pyplot as plt

N = 31
Kp = 1
Ks = 4
wp = 0.26 * np.pi
ws = 0.34 * np.pi
h_rem = remez(numtaps=N, bands=[0, wp, ws, np.pi / 2], desired=[1, 0], weight=[Kp, Ks], fs=np.pi)
plt.stem(h_rem, use_line_collection=True)
plt.show()
```
Even if I drastically change the weight parameters `Kp` or `Ks` the coefficients of the filter do not change. Also, the `weight` parameter is not tested in the test suite.

**Comment by WarrenWeckesser** [comment]
@EverLookNeverSee, I'm sorry your issue has remained unaddressed for so long!

I don't see how you determined that the weights were not affecting the coefficients.  I have used the weights to design filters, and I did not run into such a problem.  For example, see the subsection on page 10 and the corresponding Figure 14 on page 11 of my notes on ["Signal Processing with SciPy: Linear Filters"](https://warrenweckesser.github.io/papers/weckesser-scipy-linear-filters.pdf).

Here's a modification of your script in which I use your parameters to design two filters.  The only difference is that in the second filter, I swap the weights.  I use `scipy.signal.freqz` to plot the magnitude of the frequency responses.  You can see in the plots of the frequency response that changing the weights *does* change the filter.

```
import numpy as np
from scipy.signal import remez, freqz
import matplotlib.pyplot as plt


N = 31
Kp = 1
Ks = 10
fs = np.pi
nyq = 0.5 * fs
wp = 0.26 * fs
ws = 0.34 * fs

h_rem1 = remez(numtaps=N, bands=[0, wp, ws, nyq], desired=[1, 0],
               weight=[Kp, Ks], fs=fs)
# Same parameters, but swap the weights.
h_rem2 = remez(numtaps=N, bands=[0, wp, ws, nyq], desired=[1, 0],
               weight=[Ks, Kp], fs=fs)

w1, h1 = freqz(h_rem1, worN=8000, fs=fs)
w2, h2 = freqz(h_rem2, worN=8000, fs=fs)

plt.plot(w1, np.abs(h1), label='h1')
plt.plot(w2, np.abs(h2), label='h2')

plt.title('Frequency response')
plt.xlabel('$\omega$')
plt.legend(framealpha=1, shadow=True)
plt.grid(True)

plt.show()
```
Plot:
![Figure_1](https://user-images.githubusercontent.com/321463/167240546-0b8a8b20-9562-4600-9dd9-699b6bf176ff.png)

I'm closing the issue, but please ask if you have any questions, and reopen the issue if I misunderstood the problem.
