### ISSUE TITLE
Add a (potentially temporary) py.typed file?

### ISSUE THREAD

**Issue by person142** [scipy/scipy#11945]
This came up in https://github.com/scipy/scipy/pull/11936#issuecomment-619628764.

As of right now type checkers would ignore an installed version of SciPy because we don't have a `py.typed` file per PEP 561:

https://www.python.org/dev/peps/pep-0561/#packaging-type-information

This makes it harder for downstream projects that want to test out the types we are adding. What do people think about adding that `py.typed` file now so that people can try the types out, and then removing for the next release if the types aren't ready? (Though I hope at least a rudimentary form of them will be.)

This might mean that downstream experimenters have to ignore some errors in their configs, but that seems like a reasonable trade-off.

**Comment by person142** [comment]
Note that the `py.typed` file doesn't contain anything fancy-it's just an empty file that serves as a marker.

**Comment by rgommers** [comment]
Seems reasonable. I can't think of something that will break and can't be easily fixed by copying the ignores we have in our `mypy.ini`.

**Comment by person142** [comment]
Ping @rth: if you want to test things against the SciPy stubs, now you just:

- Install the `mypy_requirements.txt`
- Install SciPy from master
