### ISSUE TITLE
scipy.stats.spearmanr: no except clause after try block

### ISSUE THREAD

**Issue by brynhayder** [scipy/scipy#11953]
Hi,

I just noticed that this try block has no except and that, should an exception be triggered, t would be undefined on line 2717. Link to source below.

Thanks for all your hard work.

https://github.com/scipy/scipy/blob/f2ec91c4908f9d67b5445fbfacce7f47518b35d1/scipy/stats/stats.py#L2713-L2717

**Comment by jakevdp** [comment]
Thanks – I believe this is intended: ``try...finally`` is a way to ensure that some cleanup code is run regardless of whether the main statement results in an error. The lack of ``except`` means that any error will be raised directly to the user.

**Comment by WarrenWeckesser** [comment]
@brynhayder, thanks for taking a look at the source code.   That code works as expected. If an exception occurs that is not `ZeroDivisionErro`, it propagates, because it is not caught by an `except` clause.  The `finally` clause ensures that the error state is restored before the exception is propagated up to the caller.

That code was originally written before NumPy had the `errstate` context manager.  These days, instead of

    olderr = np.seterr(divide='ignore')  # rs can have elements equal to 1
    try:
        t = rs * np.sqrt((n-2) / ((rs+1.0)*(1.0-rs)))
    finally:
        np.seterr(**olderr)

we would write

    with np.errstate(divide='ignore'):
        t = rs * np.sqrt((n-2) / ((rs+1.0)*(1.0-rs)))

**Comment by ilayn** [comment]
Also from the git blame the commit message

>  TST: filter all test noise from scipy.stats
> 
> The tests for the zipf distribution are disabled, because they were generating
> floating point warnings for many (all) methods that can't easily be filtered.
> The chisquare test of dlaplace is disabled for the same reason.

**Comment by WarrenWeckesser** [comment]
@EverLookNeverSee, I removed the `defect` label.  The issue reported here is not a defect.

**Comment by EverLookNeverSee** [comment]
> @EverLookNeverSee, I removed the `defect` label. The issue reported here is not a defect.

@WarrenWeckesser Sorry, My bad!

**Comment by WarrenWeckesser** [comment]
@EverLookNeverSee, no problem, thanks keeping on eye on the issues and tagging them so quickly!

**Comment by WarrenWeckesser** [comment]
There are probably a few places in the code that use this `try-finally` pattern for setting and restoring the numpy floating point error handling state.  I wouldn't object to a PR that replaced those with the appropriate use of `np.errstate`.  It's not a high priority, but it does look like a worthwhile bit of code clean up.

**Comment by ilayn** [comment]
I would actually encourage such a PR since it is harder to read as is.

**Comment by brynhayder** [comment]
Thanks for the responses, but I still don't understand. 

Suppose rs = 1, so that the calculation of t triggers a division error that is caught by the try block. What is then the value of t that goes into line 2717?

**Comment by ilayn** [comment]
You will get a `ZeroDivisionError: division by zero` as you hit the perfect 0.

**Comment by WarrenWeckesser** [comment]
> Suppose rs = 1, so that the calculation of t triggers a division error that is caught by the try block. What is then the value of t that goes into line 2717?

`t` will have the value `inf`.  Then this line

    prob = distributions.t.sf(np.abs(t),n-2)*2

will result in `prob` being 0.

**Comment by brynhayder** [comment]
> > Suppose rs = 1, so that the calculation of t triggers a division error that is caught by the try block. What is then the value of t that goes into line 2717?
> 
> `t` will have the value `inf`. Then this line
> 
> ```
> prob = distributions.t.sf(np.abs(t),n-2)*2
> ```
> 
> will result in `prob` being 0.

Thank you.

I forgot that numpy handles np.array(1)/np.array(0) different to python scalars.

Thanks for the quick responses. Stay safe!

**Comment by WarrenWeckesser** [comment]
FYI: I went ahead and created a pull request to update the code to use `np.errstate` where appropriate: https://github.com/scipy/scipy/pull/11957
