### ISSUE TITLE
DOC: search in devdocs returns wrong link

### ISSUE THREAD

**Issue by gauthe** [scipy/scipy#11971]
Hello,

This is about https://scipy.github.io/devdocs, I hope it fits here. When you use the search engine, the links it returns include an "undefined" that make them invalid. Example: the first link of https://scipy.github.io/devdocs/search.html?q=eigh is https://scipy.github.io/devdocs/generated/scipy.linalg.eighundefined?highlight=eigh.

This does not affect docs.scipy.org and appears only in the search results, the other links are fine.

**Comment by tylerjereddy** [comment]
Yeah, I've noticed this recently as well

**Comment by dsandeep0138** [comment]
Starting v3.1.1, Sphinx introduced LINK_SUFFIX, https://github.com/sphinx-doc/sphinx/commit/a717ffec78db1f92553b42f6524b8f6b031bfda5, but this value is not set in the sphinx-theme that we are using. Please see below code. Because of this, LINK_SUFFIX is "undefined" and we see "undefined" getting append to the links, making them invalid.

https://github.com/scipy/scipy-sphinx-theme/blob/db30e82774efaccb0cac219910994659a40322ba/_theme/scipy/layout.html#L89-L97 

```
{%- macro script() %}
    <script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
        URL_ROOT:    '{{ url_root }}',
        VERSION:     '{{ release|e }}',
        COLLAPSE_INDEX: false,
        FILE_SUFFIX: '{{ '' if no_search_suffix else file_suffix }}',
        HAS_SOURCE:  {{ has_source|lower }}
      };
```

@tylerjereddy Please take a look and let me know, I can raise a PR to fix this! Thanks.

**Comment by pv** [comment]
@dsandeep0138: if you know how to fix the theme for new Sphinx
versions, a PR fixing the issues in the scipy-sphinx-theme repository
would be appreciated. After that is merged, the submodule in this
repository can be updated to the latest version.

**Comment by dsandeep0138** [comment]
@pv I have raised a PR in the scipy-sphinx-theme repository. Thanks!

**Comment by peterbell10** [comment]
Is it possible to update the `scipy.org` website without doing a full release? Broken search is really bad for usability of the docs.

**Comment by rgommers** [comment]
Yes that's possible. Looks like the `1.5.1` docs are broken, `1.5.0` and `devdocs` are both fine. I think gh-12392 needs to be backported to `1.5.x`, and then the docs need to be regenerated. @tylerjereddy does that make sense?

**Comment by tylerjereddy** [comment]
> Broken search is really bad for usability of the docs.

-0.5 on this being urgent but I'll see what I can do later with temporary local backport for a doc rebuild at `1.5.1` release point until `1.5.2`. You can still use Google to pinpoint stuff and +/- 1 point release number with our stable API should probably not make much difference in the vast majority of cases anyway.

To help prevent this in the future, feel free to help me milestone and label PRs  appropriately.

**Comment by peterbell10** [comment]
I agree that browsing the `1.5.0` docs would be completely fine as a replacement. However, I think there's been a push recently to direct people to the absolute latest docs with e.g. the red warning bar at the top of outdated versions. If you follow that link at the moment you're directed to the version with broken search.

If it's too much work though, feel free to ignore. As you say, you can work around it with google fairly easily.

**Comment by tylerjereddy** [comment]
I rebuilt and re-uploaded  `1.5.1` docs--search links are working for me now. Make sure you refresh and see the July 11/2020 date on the index page.

**Comment by tylerjereddy** [comment]
The actual backport to `1.5.x` will not happen until `1.5.2` preparation--this was done locally only.

**Comment by rgommers** [comment]
Thanks Tyler!
