### ISSUE TITLE
sparse.linalg.gmres extra calls to matvec

### ISSUE THREAD

**Issue by omaxian** [scipy/scipy#11975]
Hi, 

I am using GMRES with scipy and am wondering about the initialization. Why are there several calls to matvec before the first iteration starts? Can you explain what the purpose of these is? Is there any way to disable them?

Thanks.

**Comment by pv** [comment]
Can you give an example of what do you mean? I see zero calls before Arnoldi starts?

**Comment by omaxian** [comment]
Sure, here is what I don't understand (maybe I just don't understand how GMRES works). If I take the code below, "applying function" gets output 3 times, even though I've only specified 1 iteration. Is that typical for GMRES? Thanks 

class GMRESThing(object):

    def __init__(self,ain):
        self._a = ain;

    def mv(self,v,b):
        print('Applying function')
        return np.array([(0.1+self._a)*v[0], (b+0.1)*v[1]])

    def mvInverse(self,v,b):
        print('Applying preconditoner')
        return np.array([1/self._a*v[0], 1/b*v[1]])

GRes = GMRESThing(2);
b = 3;
A = LinearOperator((2,2), matvec=partial(GRes.mv,b=b)) 
Pinv = LinearOperator((2,2), matvec=partial(GRes.mvInverse,b=b)) 
x, info = gmres(A,np.ones(2),M=Pinv,callback=print,callback_type='pr_norm',restart=1,maxiter=1,atol=0).

**Comment by pv** [comment]
Yes, it's expected: the documentation says `Maximum number of iterations (restart cycles)`, and "restart cycle" is by default 20. You can read up e.g. on wikipedia what it means.
To avoid one extra call, you should also give the dtype= attribute of your LinearOperators, in addition to giving the matvec=.
