### ISSUE TITLE
scipy.optimize.minimize: Nested minimization does not converg

### ISSUE THREAD

**Issue by waeckerlin** [scipy/scipy#11989]
I use scipy.optimize.minimize to fit a physical model using an external program. Because the calculations are slow (ca 10 s per iteration), some "soft" parameters which do not depend on the external program are optimized in a second, nested minimization loop. 

In case of method1,method2 ='SLSQP','SLSQP' the minimization does not terminate. Other combinations (e.g. method1,method2 ='TNC','SLSQP') work. This suggests that the issue is related to inproper isolation of the internal states of the two SLSQP routines. 

The (silly) minimal code example below reproduces the problem. 

#### Reproducing code example:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import numpy as np
from scipy.optimize import minimize
from scipy.optimize import rosen

#method1,method2 ='TNC','SLSQP' #works
#method1,method2 ='TNC','TNC' #works
#method1,method2 ='SLSQP','TNC' #works
#method1,method2 ='Nelder-Mead','Nelder-Mead' #works
#method1,method2 ='CG','CG' #works

method1,method2 ='SLSQP','SLSQP' #bug

jj=0
def fun_inner(x):
  global jj
  jj=jj+1
  res=rosen(x)
#  print("** jj",jj,res)
  return res  

ii=0
def fun(x):
  global ii
  ii=ii+1
  xres = minimize(fun_inner, x, method=method1)
  x1 = np.array([sum(xres.x)/5, 0.7, 0.8, 1.9, 1.2])

  res=rosen(x1)
  print("* ii",ii,res)
  return res

x0 = np.array([1.3, 0.7, 0.8, 1.9, 1.2])
res = minimize(fun, x0, method=method2)

print(res.x)
```

#### Error message:
None. It keeps iterating forever.

#### Scipy/Numpy/Python version information:
1.1.0 1.18.2 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)

**Comment by pv** [comment]
Upgrade scipy, see #9317
