### ISSUE TITLE
Are the one-sided alternatives of ks_2samp swapped ?

### ISSUE THREAD

**Issue by Lectem** [scipy/scipy#11981]
I am kind of new to the domain of statistics but it seems to me that the alternatives of `ks_2samp` are swapped. (Those were introduced by #9753)

As I understand, if we reject a null hypothesis (that is, have a p-value close to 0), we get the alternative.

The documentation states

> In the one-sided test, the alternative is that the empirical cumulative distribution function F(x) of the data1 variable is “less” or “greater” than the empirical cumulative distribution function G(x) of the data2 variable, F(x)<=G(x), resp. F(x)>=G(x).

So with the following code (tweaked from the documentation example):

```
np.random.seed(12345678)  #fix random seed to get the same result
data1 = stats.norm.rvs(size=500, loc=0., scale=1) # mean = 0
data2 = stats.norm.rvs(size=500, loc=100., scale=1) # mean = 100
# So now we have data1 < data2 for sure

for alt in ['greater', 'less', 'two-sided']:
    print(alt,":",stats.ks_2samp(data1,data2,alternative=alt))
```

will print

> greater : Ks_2sampResult(statistic=1.0, pvalue=3.699753997814024e-300)
> less : Ks_2sampResult(statistic=0.0, pvalue=1.0)
> two-sided : Ks_2sampResult(statistic=1.0, pvalue=7.399507995628047e-300)

Which means:

- `data1` is greater than `data2`
- we can not tell whether `data1` is less than `data2`
- `data1` is not identical to `data2`

While it would be expected:

- we can not tell whether `data1` is greater than `data2`
- `data1` is less than `data2`
- `data1` is not identical to `data2`

Using the same values as input with `mannwhitneyu` we get this output

> greater : MannwhitneyuResult(statistic=0.0, pvalue=1.0)
> less : MannwhitneyuResult(statistic=0.0, pvalue=2.9281214567494703e-165)
> two-sided : MannwhitneyuResult(statistic=0.0, pvalue=5.856242913498941e-165)

which seems to confirm the issue.

# Version informations

Scipy version: '1.4.1'
Numpy version: '1.17.2'
sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

**Comment by josef-pkt** [comment]
It's always a bit difficult to keep this straight.

The statement on cdf implies reversed stochastic dominance.

F1(x)<=G2(x) means that at each x, there are fewer observations below x in data1 than in data2, and more above. So x has larger values, so data1 dominates data2.

Best is to draw two cdf, and check this graphically

**Comment by josef-pkt** [comment]
It's a bit easier to think about it in terms of survival function sf = 1 - cdf.

sf_1(x) > sf_2(x)

As we increase x, then at each x, there are more "survivors", with higher values, in data1 than in data2.

**Comment by Lectem** [comment]
Ah right it makes more sense!
I somehow was still thinking in terms of probability that a value taken from the same variable as samples data1 would be less than a value from data2.
But here we are talking about the cumulative distribution, which actually gives me the opposite conclusion.

I somehow missed that, thanks a lot!
