### ISSUE TITLE
newton: Shouldn't it take a Jacobian for multivariate problems instead of first-order derivative vector?

### ISSUE THREAD

**Issue by Makman2** [scipy/scipy#12006]
Multivariate solving [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.newton.html) is not really well documented.
However, the "real" Newton-Raphson method for multivariate problems actually takes in Jacobians (see e.g. [here](http://fourier.eng.hmc.edu/e176/lectures/NM/node21.html)) instead of any vector form of first order derivatives.

Indeed trying to feed in a Jacobian matrix into `newton` yields

```
IndexError: too many indices for array
```

Maybe I am totally misconcepted here and SciPy maybe simplifies / optimizes something here (for example because the Jacobian must be inverted / at least a linear problem must be solved).

**Comment by pv** [comment]
The answer is that `newton` does not do multivariate problems, only
scalar ones. If `x0` is array, then it iiuc solves multiple scalar
problems for different initial points.

**Comment by Makman2** [comment]
> If `x0` is array, then it iiuc solves multiple scalar
problems for different initial points.

Ahhh okay, thanks for that hint. I thought `x0` taking in arrays meant it's possible to solve multivariate problems.

But yeah maybe improve the documentation to make that clear? In any case, feel free to close if you think it's clear enough. I was then not aware that the "vectorization" mentioned in the docs doesn't say anything about multivariate solving capabilities^^

**Comment by mdhaber** [comment]
Good first issue: explain in appropriate places of Newton documentation that it performs optimization of a scalar valued function of a scalar variable. If `x0` is a vector, it seems to run the function for each guess, but mathematically the objective function is still a function of a scalar.
