### ISSUE TITLE
pybind11 license

### ISSUE THREAD

**Issue by isuruf** [scipy/scipy#12002]
Should pybind11's license be included in wheels and other binary distributions?

xref: https://github.com/pybind/pybind11/issues/1386

**Comment by rgommers** [comment]
Oh, that's a bit annoying. We can amend the license, but that indeed doesn't seem very friendly - there's better ways to acknowledge a project than a license file no one reads.

**Comment by WarrenWeckesser** [comment]
Do other projects have a nice way to do this?

Thinking out loud... maybe add a function to the `scipy` namespace, say `scipy.licenses()`, that returns a string containing the contents of `LICENSES_bundled.txt` that also has the `pybind11` license added to it.

**Comment by rgommers** [comment]
I don't see a reason to change how we're doing this today. It's just a license file, why would we add a function to the API for it?

**Comment by WarrenWeckesser** [comment]
Is the text of the pybind11 license included in a wheel?  Is it accessible to a user of the wheel?

**Comment by isuruf** [comment]
It's not, hence this issue. `LICENSES_bundled.txt` is included in the wheel though.

**Comment by rgommers** [comment]
It's unrelated to wheels though: a wheel is just a zip file and it contains the license and other metadata. We also bundle in other binaries that are already noted in the license file.

The annoyance here is that no one understands that pybind11 licensing affects projects depending on it differently that a regular build-time or runtime dependency. Hence everyone is in violation, and then has to do a bunch of work to fix it. They really should have changed that license.

**Comment by WarrenWeckesser** [comment]
Would it be sufficient then to just add the pybind11 license to `LICENSES_bundled.txt`?

**Comment by rgommers** [comment]
yes
