### ISSUE TITLE
Expose FACTOR parameter instead of using magic number in scipy.optimize.nnls

### ISSUE THREAD

**Issue by joshjohnston** [scipy/scipy#12017]
The Fortran code in scipy/optimize/nnls/nnls.f uses a parameter FACTOR, which is hardcoded to 0.01, to determine when to end the loop due to lack of linear independence.  It would be much appreciated if this magic number was exposed as an option in both the Fortran and the scipy.optimize.nnls python wrapper.

**Comment by rgommers** [comment]
Hi @joshjohnston, do you have a code example perhaps where this would help?

**Comment by Kai-Striega** [comment]
@rgommers I'm not too familiar with the function - so I can't comment on whether it's a good idea or not - but the actual change should be pretty straight forward if you want someone to do it.

**Comment by osullivryan** [comment]
Hello @joshjohnston , I took a crack at it. Let me know how that looks!
