### ISSUE TITLE
scipy optimize verbose output 'disp' flag not working - can't track progress of minimize

### ISSUE THREAD

**Issue by Malley1** [scipy/scipy#12018]
I was previously using scipy version 0.17.0 to run minimization. The command looks like this:

```
invres = minimize(gauss_fit_to_invert, invars, method='powell', options={'ftol': 0.1, 'disp': True, 'maxfev': 10000})
```
where ```invars``` is an array of variables to be optimized by minimizing the result of the function ```gauss_fit_to_invert```, which returns a single floating point number.

The optimization would work fine and output a short summary of the minimization progres after each function evaluation. I have since upgraded from scipy 0.17.0 to scipy 1.4.1, and using the same command the helpful progress messages have disappeared and only the final result prints anything to stdout. I have checked that the flag ```'disp': True``` is the same in version 1.4.1 of ```minimize```. Am I still assigning it correctly? Is this lack of visual output a new feature of scipy 1.4.1 or a bug?

I found it very useful to keep track of the minimization algorithm while it was running, as you could interrupt and try something different if you could see the algorithm was going astray. Now you just have to sit fingers crossed, not knowing how close the minimization is to approaching convergence.

Many thanks.

#### Scipy/Numpy/Python version information:
currently:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.4.1 1.18.3 sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
```

formerly:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
('0.17.0', '1.16.4', sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0))
```

**Comment by abondrn** [comment]
Why was this closed?
