### ISSUE TITLE
Documentation Rendering Issues Visible in CircleCI Artifacts

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#12031]
Documentation has been rendering funny recently: parameter names and types are squashed together.

From `minimize`.
![image](https://user-images.githubusercontent.com/6570539/81122077-ff971300-8ee4-11ea-8e5b-65b394b10f0b.png)

`linprog`
![image](https://user-images.githubusercontent.com/6570539/81122106-13427980-8ee5-11ea-9da7-d4d69b8ff8ca.png)

If those links break, just check:
![image](https://user-images.githubusercontent.com/6570539/81122192-3cfba080-8ee5-11ea-972e-98bf2de79871.png)

in any PR. 

@AtsushiSakai you made a suggestion somewhere, but I can't find it now.

**Comment by WarrenWeckesser** [comment]
The docs that are regularly uploaded to http://scipy.github.io/devdocs/ look OK, so I guess this is a problem with the CircleCI script in https://github.com/scipy/scipy/blob/master/.circleci/config.yml

**Comment by AtsushiSakai** [comment]
oh sorry. it was deleted accidentally. when i change “:” to “\:”, it looks better. but i don’t know why it is needed.

**Comment by larsoner** [comment]
Maybe not the script but some configuration change at their end, is the symptoms match these

https://discuss.circleci.com/t/circleci-403-forbidden-in-html-artifacts/35791

**Comment by larsoner** [comment]
Indeed it does, looking at [this recent CircleCI artifact](https://18925-1460385-gh.circle-artifacts.com/0/html-scipyorg/generated/scipy.optimize.minimize.html#scipy.optimize.minimize) in the Google Chrome console you'll see:
```
basic.css:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
```
The CSS won't load, which messes up the rendering. It's not a problem once data are uploaded to `devdocs`, so almost certaintly a CircleCI artifacts server problem...

**Comment by WarrenWeckesser** [comment]
Thanks, @larsoner, let's hope you get a response from CircleCI.

**Comment by gmemstr** [comment]
:wave: Cross posting this from the Discuss post for visibility - it looks like this is directly due to our recent change with redirecting artifacts: https://circleci.com/changelog/#artifacts-redirects. We recently rolled out a change that allowed JSON files through CORS,  but it looks like there's some other file types we should consider allowing through. I'll pass this along internally :)

**Comment by gmemstr** [comment]
Quick update - we've rolled out the ability to load CSS files, and it appears that the artifact linked for @larsoner is loading nicely. Fonts are a slightly trickier subject since there are a number of different possible extensions. Really appreciate the report!

**Comment by WarrenWeckesser** [comment]
@gmemstr, thanks, it looks like the SciPy docs are rendering correctly again.

**Comment by larsoner** [comment]
Agreed things are working again, thanks for the quick fix @gmemstr !
