### ISSUE TITLE
Spherical mean/variance

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#12041]
**Is your feature request related to a problem? Please describe.**

Currently, scipy has functions to calculate the circular mean and variance but no analogue for spherical data.

**Describe the solution you'd like**

I am currently implementing a library for spherical statistics (https://github.com/dschmitz89/spherical_stats) and recently added functions for spherical mean and variance. Actually, they are quite simple, short and only require numpy, so they could also become a part of scipy.stats without too much effort. 

If you think this is interesting, I would work on a PR.

**Comment by dschmitz89** [comment]
I asked here first because I understood the developer guidelines that way that it should be discussed first if a new method is important enough to become a part of scipy and if some core devs would be potentially interested in reviewing it.

**Comment by mdhaber** [comment]
@dschmitz89 Did you email the [scipy-dev mailing list](https://www.scipy.org/scipylib/mailing-lists.html)? That might help attract some attention to this.

**Comment by dschmitz89** [comment]
@mdhaber : thanks for that suggestion, I will open an Email thread soon.

Regarding #12201 : I think building a new submodule 'spherical' is far beyond the scope of what I wanted to contribute. I just thought of adding two equivalents for circmean and circvar: sphermean and sphervar. I think those would already be helpful to many people for some very basic descriptive statistics of vector data.

**Comment by mdhaber** [comment]
Did this ever make it to the mailing list @dschmitz89?

**Comment by dschmitz89** [comment]
Oops, now it did. Lost track of this before apparently.

**Comment by mdhaber** [comment]
Spherical mean is done, but variance is not.
