### ISSUE TITLE
scipy.signal.spectrogram doesn't exist

### ISSUE THREAD

**Issue by Ecart33** [scipy/scipy#12058]
according to https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.spectrogram.html#scipy.signal.spectrogram, there should be a function scipy.signal.spectrogram. However I can't find any evidence of this existing...

**Comment by WarrenWeckesser** [comment]
Which version of SciPy you using?  `spectrogram` was added in version 0.16, which was released in 2015, so it would be surprising if you don't have it.  You can check the version with

    import scipy
    print(scipy.__version__)

Next, be sure you import the `signal` subpackage explicitly.  Either

    import scipy.signal

and use `scipy.signal.spectrogram` to refer to the function, or

    from scipy import signal

and then use `signal.spectrogram`, or

    from scipy.signal import spectrogram

and then use `spectorgram`.

If you try

    import scipy

and then try to use `scipy.signal.spectrogram`, it won't work.  Importing just the top-level name `scipy` does not import all the subpackages (`signal`, `stats`, `linalg`, etc.).

**Comment by rgommers** [comment]
question was answered - closing
