### ISSUE TITLE
Coupling optimization algorithms with finite element software

### ISSUE THREAD

**Issue by JayArell** [scipy/scipy#12053]
Hello,

I am fairly new to programming in Python and GitHub in general, so hopefully I will be able to explain this properly. 

I am studying geotechnical engineering and I have been trying to couple the SLSQP optimization algorithm with the most used calculation program within geotechnics, PLAXIS 2D. Since PLAXIS 2D already has a built in coupling with Python, I thought it might be possible to utilize the scipy.optimize library for minimizing cost in the design of simple constructions. Because I have limited knowledge of optimization theory, the algorithm becomes a sort of black box for me, and I am only able to analyze the input and output.

I have got the coupling to work to the point that the algorithm makes the program run. However, I cannot make the algorithm respect my set constraint for the situation. Instead, the algorithm goes directly to the lowest defined bound, where the cost is the lowest, but the factor of safety is violated.

I want a factor of safety of 1.4, which is a value that can be extracted for each iteration. The constraint is defined as:

    def constraint1(x):
          msf = g_i.Phase_8.Reached.SumMsf.value
          return msf - 1.4

I realize that the constraint does not take in any of the parameters of x (which contains lengths of different construction elements), could this be a problem? I have tried the constraint as both an equality and inequality.

Does anyone here have experience with this type of coupling in general, and is it even feasible? Could it be an issue with the SLSQP algorithm? I am looking to try the COBYLA in the coming days.

I don't know if people will be able to help on the matter, but any thoughts would be very much appreciated!

-J

**Comment by ilayn** [comment]
I would first export the data out and test the constraints before internal software linking. Then you can have a better shot at doing the integration.

**Comment by pv** [comment]
> I realize that the constraint does not take in any of the parameters of x (which contains lengths of different construction elements), could this be a problem?

That won't work: When the solver asks your constraint "is the parameter set `x` valid?", if you return a result independent of `x`, then either all parameter values are valid or none are (depending which result you returned).

**Comment by JayArell** [comment]
> > I realize that the constraint does not take in any of the parameters of x (which contains lengths of different construction elements), could this be a problem?
> 
> That won't work: When the solver asks your constraint "is the parameter set `x` valid?", if you return a result independent of `x`, then either all parameter values are valid or none are (depending which result you returned) so the constraint won't have a sensible effect.

Ok, I see. It does sound like this coupling might not be feasible after all then, do you agree?

**Comment by JayArell** [comment]
> I would first export the data out and test the constraints before internal software linking. Then you can have a better shot at doing the integration.

Thanks for the tip. This could be tricky in my eyes as the data is created from new iterations, which are all faulty due to the coupling not working properly.
