### ISSUE TITLE
ENH add "maxeval" option to scipy.optimize.minimize and scipy.optimize.differential_evolution

### ISSUE THREAD

**Issue by fakekarma** [scipy/scipy#12051]
**Is your feature request related to a problem? Please describe.**
In order to control resources, an enhancement of the available callback functionalities within `scipy.optimize.minimize` & `differential_evolution` would be beneficial.

**Describe the solution you'd like**
For instance, additional options as "maxeval" or "maxtime" could be considered. Something similar is to the best of my knowledge already present in `scipy.optimize.anneal`, but not available with other optimize alternatives.

**Describe alternatives you've considered**
I considered implementing this within the callback for `differential_evolution` triggering a `True` return value. However, this is not possible by means of the return-less variant offered by `minimize`.

**Additional context (e.g. screenshots)**

**Comment by ev-br** [comment]
Can you raise from a callback?

**Comment by andyfaff** [comment]
`maxfun` is already used by `L-BFGS-B`, `powell`, `nelder-mead`, to limit the maximum number of function evaluations.
In DE you can use the callback to stop iterating by returning `True`. You can also raise a `StopIteration` from your objective function, which will stop immediately (but still return the best solution so far).
Time based halting is best implemented in user-space. There may be a possibility of adding `maxfun` to the remaining minimizer methods, and also implementing a `StopIteration` based approach, but either of those would require significant surgery.

**Comment by andyfaff** [comment]
As @ev-br mentions you can also halt by raising an exception from the callback at the end of each iteration. You would typically have the best solution so far present in that callback.

**Comment by fakekarma** [comment]
> 
> 
> `maxfun` is already used by `L-BFGS-B`, `powell`, `nelder-mead`, to limit the maximum number of function evaluations.
> In DE you can use the callback to stop iterating by returning `True`. You can also raise a `StopIteration` from your objective function, which will stop immediately (but still return the best solution so far).
> Time based halting is best implemented in user-space. There may be a possibility of adding `maxfun` to the remaining minimizer methods, and also implementing a `StopIteration` based approach, but either of those would require significant surgery.

I tested the `StopIteration` and it did work in terms of bare interruption of the script. However, it does not perform as stopping criteria for the optimizer, thus, allowing e.g. the planned post-processing of the solution.

**Comment by andyfaff** [comment]
The StopIteration would only work for differential evolution

**Comment by fakekarma** [comment]
Fine, thanks again for the hint.
