### ISSUE TITLE
ENH: Using docker cache to avoid reinstalling dependencies

### ISSUE THREAD

**Issue by EverLookNeverSee** [scipy/scipy#12055]
We need to reinstall all project dependencies when we rerun scipy container([Development environment quickstart guide (Docker)](https://docs.scipy.org/doc/scipy/reference/dev/contributor/quickstart_docker.html))

Can we use docker run cache in order to keeping dependencies in cache for further uses? 
Or adding some docker commands into scipy dockerfile to auto-install all relevant dependencies while running and creating scipy interactive container?

**Comment by andyfaff** [comment]
It was a conscious decision not to install cython/numpy/pybind11. This is because they can rapidly go out of date, and it's not a big hassle to install them, `pip3.7 install numpy cython pybind11`.
