### ISSUE TITLE
Scipy bounded optimisation does not obey boundaries

### ISSUE THREAD

**Issue by vzografos** [scipy/scipy#12065]
My issue is about using scipy bounded optimisation (minimise with method='trust-constr'), where the optimiser does not respect the boundary values.

More specifically, inside the objective function (likefunc) mu should be smaller than the minimum value of the array x.  This is determined in the boundaries selected for minimisation. But when the error happens I check and inside likefunc, mu is given value above min(x). So the minimiser is searching values outside of the requested boundaries

Note: Reproduction might be difficult if you do not have ALL my code

#### Reproducing code example:

```
epsilon=1e-01

x=np.array([ 0. , 13.3, 12.5,  7.1,  0. , 25. ,  0. , 11.1, 11.1,  0. ,  0. ,  7.1,  6.7, 14.3, 20. , 13.3,  7.7,  7.7,  0. , 14.3,  0. , 22.2,   0. ,  6.7,  0. ,  0. ,  0. , 20. ,  0. ,  0. , 12.5,  0. , 14.3,  22.2,  0. , 22.2, 10. , 14.3, 16.7,  0. ,  0. , 42.9,  0. ,  0. ,   0. ,  0. ,  0. ,  0. , 11.1,  0. , 20. , 20. , 14.3, 14.3,  0. ,   16.7,  0. ,  0. ,  9.1,  0. ,  0. ,  0. , 16.7,  0. ,  0. ,  0. ,     0. ,  0. ,  0. , 40. ,  0. ,  0. ,  0. , 12.5, 12.5,  0. , 14.3,
       15.4, 16.7, 27.3, 14.3,  0. ])

m0=-0.30000000000000004
s0=5.6102818498867455
k0=0.5886365220915479

objective_fun = functools.partial(self.likefunc, arg1=x) 
 jacobian_fun =  functools.partial(self.likefunc_gradient, arg1=x) 
hessian_fun =  functools.partial(self.likefunc_hessian, arg1=x) 

bnds=( (-np.inf, np.min(x)-epsilon), (epsilon, np.inf),  (epsilon, np.inf) )

out= minimize(objective_fun, [m0,s0,k0], method='trust-constr', bounds=bnds, jac=jacobian_fun, hess=hessian_fun,  options={'disp': False, 'maxiter':200}) 




#Extra code
def likefunc(self, params, arg1):
        #Analytic form of the negative log likelihood function
      
        
        mu = params[0]
        sigma = params[1]
        kappa = params[2]
  
        x=arg1
  
  

        n = len(x)      
        xCent=x-mu
        xNorm = xCent/sigma
         
 
        
        sum1= np.sum(np.log(xCent))
        sum2= np.sum(  np.power( xNorm,kappa))

        nll =  -(n*(np.log(kappa)-kappa*np.log(sigma))+(kappa-1)*sum1-sum2)
  
      
        return nll

    def likefunc_gradient(self,params,arg1):

        mu = params[0]
        sigma = params[1]
        kappa = params[2]

        x=arg1
        n=len(x)

        xCent=x-mu
        xNorm = xCent/sigma
        #the gradient vectors of the nll
        dmu = -(kappa-1)*np.sum(1./xCent)+(kappa/sigma)*np.sum( np.power(xNorm,kappa-1)  )
        dsigma=  kappa/sigma* (-n + np.sum( np.power(xNorm,kappa) ))
        dkappa =  n/kappa - n*np.log(sigma) + np.sum(np.log(xCent)) - np.sum( np.power(xNorm, kappa) * np.log(xNorm) )

        return  -np.array([dmu,dsigma,dkappa])
         

    def likefunc_hessian(self,params,arg1):

        mu = params[0]
        sigma = params[1]
        kappa = params[2]

        x=arg1
        n=len(x)

        xCent=x-mu
        xNorm = xCent/sigma

        #the hessian matrix
        dmu2= -(kappa-1)*(    np.sum(np.power(1/xCent,2)) + kappa/(sigma*sigma) * np.sum(np.power(xNorm,kappa-2)))
            
        dmudsigma= -np.power(kappa/sigma,2) * np.sum( np.power(xNorm,kappa-1))
            
        dmudkappa = -np.sum(1./xCent) + kappa/sigma* np.sum(np.power(xNorm,kappa-1)* np.log(xNorm)) + 1/sigma*np.sum( np.power(xNorm,kappa-1) )
            
        dsigma2=  kappa/(sigma*sigma) * (n- (kappa-1)*np.sum(np.power(xNorm,kappa))  )
            
        dsigmadkappa = -1/sigma * (n- np.sum( np.power(xNorm, kappa) ) - kappa*np.sum(( np.power(xNorm,kappa))* np.log(xNorm)))
            
        dkappa2=  -n/(kappa*kappa) - np.sum(np.power(xNorm,kappa)  * np.power(np.log(xNorm),2) )
            
        return -np.array([ [dmu2, dmudsigma, dmudkappa], [dmudsigma, dsigma2, dsigmadkappa], [dmudkappa, dsigmadkappa, dkappa2]  ])




```

#### Error message:

```
RuntimeWarning: invalid value encountered in log


  ...
```

**Comment by vzografos** [comment]
Here is another example with some more verbose results, The problem is the  boundaries on the parameter mu which should be between [-inf and min(x)]


x=np. array([-17., -13., -15.,  -7., -17.,  -3.,  -4., -17., -11.,  12.,  -7., 4.,  -8.,  -3., -11., -13.,   0.,   4.,   0.,  -7.,  -1.,   0.,  -17., -13.,  -7.,   9.,   4.,   1.,   5.,  10.,   3.,   1.,  -6.,  -11.,   1.,  -2.,   1., -12., -11.,  10.,   9.,   4.,   6.,   3., 8.,   0.,   7., -16.,  -8.,  -4.,  10., -12.,  -3.,  -1.,   7.,  -4.,   2.,   4.,  -4.,  -4.,   4.])

#initial values
m0=-17.000001
s0=13.600929684957622
k0=0.755049743018813
#boundaries
Bounds([-inf, 1e-06, 1e-06], [-17.000001, inf, inf])

#Verbose output of optimisation
| niter |f evals|CG iter|  obj func   |tr radius |   opt    |  c viol  | penalty  |barrier param|CG stop|
|-------|-------|-------|-------------|----------|----------|----------|----------|-------------|-------|
|   1   |   1   |   0   | +2.2056e+02 | 1.00e+00 | 4.90e+05 | 0.00e+00 | 1.00e+00 |  1.00e-01   |   0   |
|   2   |   2   |   1   | +2.2056e+02 | 5.00e-01 | 4.90e+05 | 0.00e+00 | 1.00e+00 |  1.00e-01   |   3   |
|   3   |   3   |   2   | +2.2056e+02 | 2.50e-01 | 4.90e+05 | 0.00e+00 | 1.00e+00 |  1.00e-01   |   3   |
|   4   |   4   |   3   | +2.2056e+02 | 1.25e-01 | 4.90e+05 | 0.00e+00 | 1.00e+00 |  1.00e-01   |   3   |
|   5   |   5   |   4   | +2.2056e+02 | 6.25e-02 | 4.90e+05 | 0.00e+00 | 1.00e+00 |  1.00e-01   |   3   |
|   6   |   6   |   5   | +2.2056e+02 | 3.12e-02 | 4.90e+05 | 0.00e+00 | 1.00e+00 |  1.00e-01   |   3   |
|   7   |   7   |   6   | +2.2056e+02 | 1.56e-02 | 4.90e+05 | 0.00e+00 | 1.00e+00 |  1.00e-01   |   3   |
|   8   |   8   |   7   | +2.2056e+02 | 7.81e-03 | 4.90e+05 | 0.00e+00 | 1.00e+00 |  1.00e-01   |   3   |
|   9   |   9   |   8   | +2.2056e+02 | 3.91e-03 | 4.90e+05 | 0.00e+00 | 1.00e+00 |  1.00e-01   |   3   |
|  10   |  10   |   9   | +2.2056e+02 | 1.95e-03 | 4.90e+05 | 0.00e+00 | 1.00e+00 |  1.00e-01   |   3   |
|  11   |  11   |  10   | +2.2056e+02 | 9.77e-04 | 4.90e+05 | 0.00e+00 | 1.00e+00 |  1.00e-01   |   3   |
|  12   |  12   |  11   | +2.2056e+02 | 4.88e-04 | 4.90e+05 | 0.00e+00 | 1.00e+00 |  1.00e-01   |   3   |
|  13   |  13   |  12   | +2.2056e+02 | 2.44e-04 | 4.90e+05 | 0.00e+00 | 1.00e+00 |  1.00e-01   |   3   |
|  14   |  14   |  13   | +2.2056e+02 | 1.22e-04 | 4.90e+05 | 0.00e+00 | 1.00e+00 |  1.00e-01   |   3   |


#Verbose values of mu being searched by the minimisation algoritmh

-17.000001
-17.90924473693651
-17.359892945264605
-17.10750675809002
-17.05375387904501
-17.026877439522504
-17.013439219761253
-17.006720109880625
-17.00336055494031
-17.001680777470156
-17.000840888735077
-17.000420944367537
-17.00021097218377
-17.000105986091874
-16.999949912951045

So once it goes below min(x)=-17  and thus below the upper boundary my code throws an error.

**Comment by mdhaber** [comment]
Have you tried the `keep_feasible` option?

**Comment by vzografos** [comment]
> 
> Have you tried the `keep_feasible` option:
> https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.Bounds.html#scipy.optimize.Bounds


Hi, that works (or at least it converges) however it throws a lot of runtime warnings 

...\lib\site-packages\scipy\optimize\_trustregion_constr\equality_constrained_sqp.py:153: RuntimeWarning: invalid value encountered in double_scalars
  actual_reduction = merit_function - merit_function_next


Not sure if my code/values causes this, I ll have to ivestigate.

**Comment by mdhaber** [comment]
OK, you might want to look at gh-11649 . I haven't looked carefully at that issue, either, but please see if it looks similar to your issue.

**Comment by vzografos** [comment]
Will do. Thanks for the help
