### ISSUE TITLE
scipy.interpolate.splprep task=-1 for fixing the knots.

### ISSUE THREAD

**Issue by tjusxh** [scipy/scipy#12063]
How do I specify my own number of knot points?
I try to set task=-1, and t=np.arange(n).
An error is cast.
\scipy\interpolate\_fitpack_impl.py", line 282, in splprep
    task, ipar, s, t, nest, wrk, iwrk, per)
ValueError: Invalid inputs.

**Comment by ev-br** [comment]
Starting from the docstring example for splprep, https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.splprep.html

```
phi = np.linspace(0, 2.*np.pi, 40)
r = 0.5 + np.cos(phi)         # polar coords
x, y = r * np.cos(phi), r * np.sin(phi)    # convert to cartesian

from scipy.interpolate import splprep

tck1, u1 = splprep([x, y], task=-1, t=np.linspace(0, 1, 11))    # works!
```
Please provide a reproducible example, it's impossible to investigate otherwise.

**Comment by ev-br** [comment]
No follow-up, closing
