### ISSUE TITLE
DOC: some odr models are missing docs

### ISSUE THREAD

**Issue by AtsushiSakai** [scipy/scipy#12087]
As discussed in https://github.com/scipy/scipy/pull/12052#discussion_r422497598, some `odr` models missing docs.
Only `odr.polynomial` has doc, because it is a function with docstring, however, other models: `exponential`, `multilinear`, `unilinear`, `quadratic` does not have doc, because these are instances.
Due to this issue, it is difficult for users to know how to use these models.

**Comment by AtsushiSakai** [comment]
My possible solution is to change these 4 instances to each factory function with docstring like `polynomial`. Code consistency would be better.

**Comment by rgommers** [comment]
This goes all the way back to the creation of the `odr` module 2005, in commit 3f92506da. The reason for the difference will be that `polynomial` takes a parameter (`order`), but the other ones are formulas with no parameters. Still, this looks a little weird.

Maybe the right fix here is to change these four `Model` instances to be instances of `Model` subclasses, that can then have their own docstring and doc page in the html docs. This should be a change that's backwards compatible enough.

@rkern any thoughts?

**Comment by rkern** [comment]
Yeah, that's a plausible workaround.
