### ISSUE TITLE
ENH: Outdated scipy development version on docker hub

### ISSUE THREAD

**Issue by EverLookNeverSee** [scipy/scipy#12082]
Our scipy development version on docker hub is built almost 3 days ago while last commit to upstream  is pushed 9 hours ago.
We can configure docker hub settings so that automatically build scipy containerized development version after every push to upstream.

**Comment by andyfaff** [comment]
As the container exists there's only really a need to rebuild the container as and when the Dockerfile changes. There is no scipy repository available in the container, it has to be mounted when the container is started.

**Comment by EverLookNeverSee** [comment]
@andyfaff Do you mean everything is made as soon as container is ran on local machine?

**Comment by andyfaff** [comment]
When the container is started the user needs to use the `-v` flag to mount the scipy repo on the host machine as a directory on the guest.
Then they need to `pip3.7 install numpy cython pybind11` on the guest. Then one can use the machine for development.
