### ISSUE TITLE
Why does .nnz indicate more non-zero elements being present in sparse matrices?

### ISSUE THREAD

**Issue by science-enthusiast** [scipy/scipy#12099]
In SciPy, I have a CSR matrix. I create a LiL matrix by choosing certain rows of each column from this matrix. Then convert resulting matrix into an CSR matrix.

I have a special case, where all rows of each column are selected. While doing this, I notice a slight perturbation of the values. Here is a MWE. It can be tried with a CSR matrix given [here](https://drive.google.com/open?id=1XmWmBguqFCgB30K3PfmO27JXDKCC10QK).

#### Reproducing code example:

```
from scipy import sparse
import numpy as np
ip_mat = sparse.load_npz('a_di_mat.npz')

# this is not useful for me in practice
# this is being done for comparison
lil_mat_direct = ip_mat.tolil()
csr_mat_direct = lil_mat_direct.tocsr()

# I need to copy column-by-column.
# this a MWE representing the special case where the entire column is copied
lil_mat_steps = sparse.lil_matrix((ip_mat.shape), dtype=np.float64)

for i_col in range(ip_mat.shape[1]):
    lil_mat_steps[:, i_col] = ip_mat[:, i_col]

csr_mat_steps = lil_mat_steps.tocsr()

diff_mat = csr_mat_direct - csr_mat_steps

print('nnz: direct copy: {} columnwise copy: {} diff: {}'.format(
    csr_mat_direct.nnz, csr_mat_steps.nnz, diff_mat.nnz))

# a colleague suggested the following
ind_x, ind_y = ip_mat.nonzero()

print('ip_mat: nonzero indices {} nnz {}'.format(len(ind_x), ip_mat.nnz))
```

#### Output:

```
nnz: direct copy: 2886100 columnwise copy: 2879757 diff: 0
ip_mat: nonzero indices 2879757 nnz 2886100
```
So, could the error be in the way ```.nnz``` is implemented? Did the column-wise copying remove some values that are meant to be zeros?

**Comment by jakevdp** [comment]
I suspect your matrix includes some explicit zeros: ``nnz`` only counts the entries that are left out of the data representation.

A simpler repro:
```
>>> from scipy.sparse import csr_matrix
>>> M = csr_matrix(([1, 1, 0], ([0, 0, 1], [0, 1, 0])), shape=(2, 2))
>>> M.todense()
matrix([[1, 1],
        [0, 0]], dtype=int64)
>>> M.nnz
3
>>> M.eliminate_zeros()
>>> M.nnz
2
```
Matrix format conversions often implicitly do the equivalent of ``eliminate_zeros()``, which is why ``nnz`` may not agree before and after conversion. If it's important to count all zeros in the matrix rather than just those that are marked as missing values, call ``eliminate_zeros()`` after loading your matrix.
