### ISSUE TITLE
Improvements in scipy.optimize.differential_evolution documentation page

### ISSUE THREAD

**Issue by Alessi0X** [scipy/scipy#12104]
In the `differential_evolution` [help page](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.differential_evolution.html), when introducing the `init` argument, it says that

> array specifying the initial population. The array should have shape `(M, len(x))`, where len(x) is the number of parameters. _init_ is clipped to _bounds_ before use.

I have three suggestions in order to improve the documentation page:

- `M` is never mentioned throughout the documentation page, although it shall refer to the number of individuals in the population. Maybe it's worth specifying, for the sake of completeness, especially for novice users.

- "where len(x) is the number of parameters". I think len(x) should be rendered as `len(x)`, alike `(M, len(x))`, in order to distinguish from plain text 

- In the Examples section, one of the examples is not rendered properly (see screenshot attached)
![Screenshot 2020-05-13 at 4 22 27 PM](https://user-images.githubusercontent.com/58035692/81824657-043b7700-9536-11ea-84a9-68a985964b39.png)

**Comment by tupui** [comment]
These are fixed. Thanks.
