### ISSUE TITLE
solve_ivp: custom t_eval list and the terminating event

### ISSUE THREAD

**Issue by evgenykurbatov** [scipy/scipy#12100]
Hi guys! You are great so I bring you a bug.
Assume we use a custom `t_eval` list and also define an event with a `terminate` property. If no event occurred during the calculations, the result is an array of solutions at the time points given in the `t_eval` list (actually, the time corresponds to an axis 1 ... never mind). So its 'length' is `len(t_eval)`.
The terminating event, if happens, may occur in between of the `t_eval` points. In this case the output array will be shortened to a latest time point preceding the event. It seems logical. However, when `len(t_eval)==1` there is no preceding time points.

I like to control every time step so the code may look like this:
```python
import numpy as np
from scipy.integrate import solve_ivp

def upward_cannon(t, y): return [y[1], -0.5]
def hit_ground(t, y): return y[0]
hit_ground.terminal = True
hit_ground.direction = -1

t = [0, 33, 66, 99]
y = np.nan * np.zeros((2, len(t)))
y[:,0] = np.array([0, 10])
for i in range(1, len(t)):
    sol = solve_ivp(upward_cannon, [t[i-1], t[i]], y[:,i-1], t_eval=[t[i]],
                    events=hit_ground)
    y[:,i] = sol.y[:,0]
```
The event occurs in time 40, i.e. between `t[1]` and `t[2]`.

#### Error message:
```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    sol = solve_ivp(upward_cannon, [t[i-1], t[i]], y[:,i-1], t_eval=[t[i]], events=hit_ground)
  File "/home/kurbatov/opt/anaconda3/lib/python3.7/site-packages/scipy/integrate/_ivp/ivp.py", line 651, in solve_ivp
    ts = np.hstack(ts)
  File "<__array_function__ internals>", line 6, in hstack
  File "/home/kurbatov/opt/anaconda3/lib/python3.7/site-packages/numpy/core/shape_base.py", line 345, in hstack
    return _nx.concatenate(arrs, 1)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
```

I don't know how to workaround this in a good fashion. May be to use a sort of
```python
for i in range(1, len(t)):
    sol = solve_ivp(upward_cannon, [t[i-1], t[i]], y[:,i-1], t_eval=[t[i-1], t[i]],
                    events=hit_ground)
    if sol.t_events[0].size == 0:
        y[:,i] = sol.y[:,1]
    else: # there was event
        pass # whatever
```
But it's not cool.

#### Scipy/Numpy/Python version information:
```python
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
```
gives
```
1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=5, releaselevel='final', serial=0)
```

**Comment by arichar6** [comment]
This is not a bug in `scipy.integrate`. The error is cause because of the way you wrote your loop. Try this instead:
```python
import numpy as np
from scipy.integrate import solve_ivp

def upward_cannon(t, y): return [y[1], -0.5]
def hit_ground(t, y): return y[0]
hit_ground.terminal = True
hit_ground.direction = -1

t_eval = [0, 33, 66, 99]
y0 = np.array([0, 10])
sol = solve_ivp(upward_cannon, [t[0], t[-1]], y0, t_eval=t_eval, events=hit_ground)
y = sol.y
t = sol.t
```
This will automatically give you the solution at the time values that you wanted. But note that the length of the vectors `t` and `y` at the end will be shorter than your specified vector `t_eval`, since the integration stopped before `t=t_eval[-1]`.

**Comment by Patol75** [comment]
@evgenykurbatov The failure you report comes from `numpy.hstack` [here](https://github.com/scipy/scipy/blob/bd98068207d2cbbe93d1735ffde21a49ea8e6718/scipy/integrate/_ivp/ivp.py#L649-L651) as a result of `ts` being empty. The reason why `ts` is empty is that both `t_eval` and `events` are provided in the call to `solve_ivp`, and a terminal event is triggered before the integration has reached the smallest value in `t_eval`; it does not matter that `t_eval` only contains a single value. Now, you could avoid the failure in `hstack` by swapping the `else:` in line 649 for an `elif ts:`, but then you would end up with an empty `sol.y` and your example would crash on the final line. I am not sure it is fair to say this is a bug in SciPy.
