### ISSUE TITLE
Doc and error message is unclear when stats.binned_statistic_dd() with binned_statistic_result

### ISSUE THREAD

**Issue by AtsushiSakai** [scipy/scipy#12115]
My issue is about ...
I think doc and error message are unclear when `stats.binned_statistic_dd()` with `binned_statistic_result`.

When I run this code:

```
import numpy as np
from scipy import stats

np.random.seed(12345678)
inp = np.random.rand(9999).reshape(3, 3333) * 200
subbin_x_edges = np.arange(0, 200, dtype=np.float32)
subbin_y_edges = np.arange(0, 200, dtype=np.float64)
stat = 'std'

ret = stats.binned_statistic_dd(
    [inp[0], inp[1]], inp[2], statistic=stat,
    bins=[subbin_x_edges, subbin_y_edges],
    expand_binnumbers=True)
print(ret)

ret = stats.binned_statistic_dd(
    [inp[0], inp[1]], -inp[2], statistic=stat,
    binned_statistic_result=ret)
print(ret)
```

I got this error message, but this message is unclear to know how to fix it.

```
Traceback (most recent call last):
  File "/home/scipy/build/testenv/lib/python3.6/site-packages/scipy/stats/_binned_statistic.py", line 584, in binned_statistic_dd
flatcount = np.bincount(binnumbers, None)
File "<array_function internals>", line 6, in bincount
ValueError: object too deep for desired array
```

The reason of this error is `expand_binnumbers=True` in the first `stats.binned_statistic_dd`.
If using result with `expand_binnumbers=True` for `binned_statistic_result`, the error happens.

I think that should be mentioned explicitly in the docstring and error message.

#### Scipy/Numpy/Python version information:

scipy 1.4.1

**Comment by rlucas7** [comment]
@AtsushiSakai the scipy 1.4.1 docstring does mention this:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.binned_statistic_dd.html
under the binned statistic result argument listing. 

Did I misunderstand the issue?

**Comment by AtsushiSakai** [comment]
@rlucas7 Oh. I'm so sorry. I didn't notice it... You are right. I close this.
