### ISSUE TITLE
Docstring missing defaults

### ISSUE THREAD

**Issue by terrdavis** [scipy/scipy#12118]
metric and sampling argument defaults don't have their defaults documented.
https://github.com/scipy/scipy/blob/adc4f4f7bab120ccfab9383aba272954a0a12fb0/scipy/ndimage/morphology.py#L1813-L1947

**Comment by ilayn** [comment]
Hi @terrdavis . The sampling doesn't have any defaults. And the metric default is given in the function signature. We can probably squeeze one more sentence to make it more obvious. Care to send a PR?

**Comment by terrdavis** [comment]
Sure. I also noticed that the documentation for the distance_transform_* family is inconsistent, is it advisable to make them consistent while I'm at it?

**Comment by ilayn** [comment]
Sure, the more consistent the merrier.

**Comment by terrdavis** [comment]
The documentation and behavior don't appear to be consistent. 

The behavior is to not return results that have output container specified, but the docs don't mention anything about this. Should I update the documentation to reflect the behavior or visa-versa?

**Comment by terrdavis** [comment]
Also, the return_distances and return_indicies flags imply that the results are returned regardless of whether an output container is supplied.

I don't use numpy/scipy a lot; is just a convention that I'm unaware of?
