### ISSUE TITLE
Possible inconsistency in Ward linkage code and documentation?

### ISSUE THREAD

**Issue by jonasenander** [scipy/scipy#12121]
This might very well be my own incompetence, but I can't figure out why in the [documentation](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.cluster.hierarchy.linkage.html)  for linkage/Ward variance minimization algorithm the equation states that each of the proportional distances are summed and then sqrt, while in the [source code
](https://github.com/scipy/scipy/blob/adc4f4f7bab120ccfab9383aba272954a0a12fb0/scipy/cluster/_hierarchy_distance_update.pxi#L61) the first two are added and the last is subtracted. 

Anyone care to explain this to me?

**Comment by Bharat123rox** [comment]
This was fixed in #4278 on the `master` branch, not sure why the latest docs still have the "+" sign

**Comment by peterbell10** [comment]
That doc link is for SciPy 0.14, the SciPy 1.4 docs do have the minus sign:
https://docs.scipy.org/doc/scipy-1.4.0/reference/generated/scipy.cluster.hierarchy.linkage.html

**Comment by jonasenander** [comment]
Oh, my bad. Sorry.
