### ISSUE TITLE
signaltools.py multidimensional indexing

### ISSUE THREAD

**Issue by wilsondyang** [scipy/scipy#12138]
I am new in using rtl-sdr. in their sample sdr-fm, there is a code:

Rpi 3 B+
python 3.7

MY PYTHON CODE:
    async for samples in sdr.stream():

        stream_count += 1
        print ("     stream count " , str(stream_count))
        
        # separate into real and imaginary parts
        sampReal = array(samples.real)
        sampImag = array(samples.imag)

        # normalize
        sampMag = sqrt((square(sampReal) + square(sampImag)))
        sampReal = sampReal / sampMag
        sampImag = sampImag / sampMag
        # reshape arrays
        sampReal = reshape(sampReal, (131072,))
        sampImag = reshape(sampImag, (131072,))
        # demodulate
        fm_demod = ((sampReal * convolve(sampImag, dif, mode='same')) - (sampImag * convolve(sampReal, dif, mode='same'))) / (square(sampReal) + square(sampImag))
        # down sample to capture the audio
        dec_demod = decimate(fm_demod, 10, ftype='fir')
        # put data in queue
        aqueue.put(dec_demod)
        # print('Queue size: ' + str(aqueue.qsize())

THE ERROR:
line of code that generates error:
        fm_demod = ((sampReal * convolve(sampImag, dif, mode='same')) - (sampImag * convolve(sampReal, dif, mode='same'))) / (square(sampReal) + square(sampImag))

errors returned by python:
Warning (from warnings module):
  File "/usr/lib/python3/dist-packages/scipy/signal/signaltools.py", line 2383
    return y[keep]
FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.

Warning (from warnings module):
  File "/usr/lib/python3/dist-packages/scipy/signal/signaltools.py", line 3463
    return y[sl]
FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.

HELP:
please advise what should I do?

**Comment by ilayn** [comment]
There is no error but they are warnings about future behavior. If you can, update your SciPy version and they will be gone (they are fixed in #8936).
