### ISSUE TITLE
scipy.linalg.solve_discrete_lyapunov: it seems is solves  \((AXA`-X=-Q)\) instead of  \((A'XA-X=-Q)\)

### ISSUE THREAD

**Issue by Mekahou** [scipy/scipy#12145]
Consider the  following code:

`def Lyapunov_residual(Q, A, X):
    res = multi_dot([A.transpose(), X, A]) - X + Q
    return res   `

and 

`A =  np.array([[ 9.50000000e-01,  0.00000000e+00,  0.00000000e+00],
       [ 9.03277809e+01,  9.50000000e-01, -4.51638904e-02],
       [ 9.03277809e+01,  0.00000000e+00,  9.04836110e-01]])`

`Q = np.array([[ 4.52028144e+04, -5.00000000e+01, -2.26014072e+01],
       [-5.00000000e+01,  2.95258646e-27,  2.50000000e-02],
       [-2.26014072e+01,  2.50000000e-02,  1.13007036e-02]])`

`X = sp_solve_discrete_lyapunov(A,Q)`

Now when I check the residuals for `A` I get:

`Lyapunov_residual(Q, A, X) = array([[ 9.02015661e+15,  4.74330744e+13,  4.29230502e+13],
       [ 4.74330744e+13, -2.69470399e+10, -5.06636077e+10],
       [ 4.29230502e+13, -5.06636077e+10, -7.21251904e+10]])`
and when I check the residuals for `A.transpose()` I get:

`Lyapunov_residual(Q, A.transpose(), X) = array([[ 2.91038305e-11,  0.00000000e+00, -8.93089300e-08],
       [ 0.00000000e+00,  2.95258646e-27, -2.44140625e-05],
       [-2.97042853e-08, -2.44140625e-05,  9.19969375e-06]])`

**Comment by ilayn** [comment]
Yes that's expected and in accordance with the documentation https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve_discrete_lyapunov.html

What is your concern about it?

**Comment by Mekahou** [comment]
Thanks, thats interesting. 
I was looking at another documentation :
https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.linalg.solve_discrete_lyapunov.html

**Comment by pv** [comment]
0.15.1 is from 2015, so the issue in the docs has been corrected since.
