### ISSUE TITLE
mannwhitneyu pvalues higher than expected

### ISSUE THREAD

**Issue by aleksejs-fomins** [scipy/scipy#12153]
Below is a sanity check for `scipy.stats.mannwhitneyu` function. I generate two sets of uniform random numbers, evaluate the p-value, compare it with 0.01, and count how many times I get the pvalue below 0.01. By definition of p-value, the fraction of datasets for which the p-value would be below 0.01 should be approximately 0.01. Having run the below code several times, I have seen values between 0.017 and 0.02. The values were expected to fluctuate around 0.01.

```
nTest = 10000
M = 50
N = 50
p = 0.01
prob = [mannwhitneyu(np.random.uniform(0,1,M), np.random.uniform(0,1,N))[1] < p for i in range(nTest)]
print(np.mean(prob), np.std(prob))
```

#### Scipy/Numpy/Python version information:
```
1.1.0 1.15.4 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

**Comment by josef-pkt** [comment]
try with normal distribution.
I don't know or don't remember about robustness of mannwhitneyu, but often p-values are only correct for normal distribution in small samples.

**Comment by aleksejs-fomins** [comment]
The issue was resolved by reading and understanding the "alternative" parameter
