### ISSUE TITLE
Question about scipy.interpolate.interp1d

### ISSUE THREAD

**Issue by hsingchenlee** [scipy/scipy#12167]
I want to do linear scaling , for example:
There is a sequence   A=[1,2,3,4],
So the length of A is 4, I want to do linear scaling to make a new sequence B                                                           
(Compare to A ,the length of B maybe 0.5times or 1.1times  or 1.5,times   and so on....)
For example: Suppose the scaling rate is  7/4 , the length of B is  4 * ( 7/4) = 7
Using linear scaling, the result of B sequence must be B=[1, 1.5 , 2 , 2.5, 3, 3.5 ,4]
How to use scipy.interpolate.interp1d to do that ?  Or is there any other function could do that? 
Input A to get output B  (with any scaling rate )
Thank s a lot!!

**Comment by ilayn** [comment]
Hi @hsingchenlee, we are using this repository exclusively for code problems, bugs, feature requests etc. You would attract many more people if you use stackoverflow or SciPy mailing list for usage questions 

Here is a related one after a 5 second googling

https://stackoverflow.com/questions/29085268/resample-a-numpy-array
