### ISSUE TITLE
Storing Rotation object in NumPy array returns an array with 32 dimensions

### ISSUE THREAD

**Issue by pumaking** [scipy/scipy#12162]
Storing Rotation objects in numpy arrays results in a numpy array with 32 dimensions.

#### Reproducing code example:

```
import numpy as np

from scipy.spatial.transform import Rotation as R

r1 = R.identity()
print(r1.as_euler("ZYX"))
arr = np.array([r1])
print(arr)
print(arr.shape)
print(len(arr.shape))
```

#### Error message:

```
[0. 0. 0.]
[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[<scipy.spatial.transform.rotation.Rotation object at 0x7eff21667ac0>]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)
32

```

#### Scipy/Numpy/Python version information:

```
1.4.1 1.18.4 sys.version_info(major=3, minor=8, micro=2, releaselevel='final', serial=0)
```

I'm not sure it's a good idea to store Rotation objects in arrays, since they can already store multiple rotations, but this behavior is very unintuitive and does not seem correct. My guess it that there is some maximum depth of 32 dimensions being hit. Perhaps this is a bug in the np.array constructor?

**Comment by siddhantwahal** [comment]
Well, I don't know if this is a bug, but here's what's going on.

The first argument of `np.array` should be, according to the docs, "an array, any object exposing the array interface, an object whose `__array__` method returns an array, or any (nested) sequence". 

The `Rotation` is object is obviously not an array in the `numpy` sense, nor does it have an `__array__` method. 

Unfortunately, it does have the `__len__` and `__getitem__` methods, which, according to [this SO answer](https://stackoverflow.com/questions/43566044/what-is-pythons-sequence-protocol) is enough to call the `Rotation` object a sequence.

What do these functions return? For your example:
```python
>>> len(r1)
1
>>> r1[0]
<scipy.spatial.transform.rotation.Rotation at 0x11b212c40>
```

So the only "item" in `r1` is itself!

Now, recall how the documentation for `np.array` says it can act on *nested* sequences? Numpy first checks how long `r1` is (it has 1 element). Then it checks if `r1` is nested, by checking how long `r1[0]` is. But `r1[0]` is `r1` itself. And so it goes down the rabbit hole, until, like you said, the  maximum dimension limit (32) is reached.

As I'm finishing typing this, I don't think `numpy` is to blame -- but I'm also new here.

**Comment by pumaking** [comment]
I think the self-reference is a problem. The Rotation object is trying to be both a single rotation and a sequence of rotations at the same time. I actually didn't know this object supported multiple rotations until I encountered this issue, though I'm sure there are benefits of this that I'm not aware of.

Is there a way to fix this without creating two different objects (e.g. a RotationArray) and still supporting rotation sequences?

**Comment by rgommers** [comment]
This could be fixed by adding an `__array__` method and making it raise a `TypeError`.

**Comment by nmayorov** [comment]
I'll try to fix it.
