### ISSUE TITLE
cannot modify the slice of an array returned by `wavfile.read`

### ISSUE THREAD

**Issue by sam81** [scipy/scipy#12176]
Trying to modify the slice of an array returned by `wavfile.read` results in a `ValueError: assignment destination is read-only`:

#### Reproducing code example:

```
from scipy.io import wavfile

fs, snd = wavfile.read("snd.wav");
snd[:,0] = snd[:,0] * 0.5
```

#### Error message:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/media/ntfsShared/otherNoSynch/tmp/pychoacoustics_wav_bug/test.py in <module>()
      2 
      3 fs, snd = wavfile.read("snd.wav");
----> 4 snd[:,0] = snd[:,0] * 0.5
      5 

ValueError: assignment destination is read-only

```

#### Scipy/Numpy/Python version information:

```
In [4]: import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.16.2 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)

```

### Comments
The issue disappears if before performing operations on a slice the whole array is multiplied or divided by 1 as in the example code below:

```
from scipy.io import wavfile

fs, snd = wavfile.read("snd.wav");
snd = snd*1
snd[:,0] = snd[:,0] * 0.5 #now works fine
```
The issue is occurring on Debian Buster with Python 3.7.3 (default, Dec 20 2019, 18:57:59) and scipy version '1.1.0'. The issues does not occur on Debian Stretch with Python 3.5.3 (default, Sep 27 2018, 17:25:39) and scipy version '0.18.1'.

**Comment by larsoner** [comment]
This appears to be because internally we use `np.frombuffer`, which has the advantage of not copying the data from the `fid.read`, but the disadvantage of then being read only (strings are immutable).

In theory we could probably fix this with `np.fromfile`, I'll give it a shot in a quick PR to see if it works.

**Comment by larsoner** [comment]
See #12183
