### ISSUE TITLE
How to use HessianUpdateStrategy in  scipy.optimize.minize(hess=?)

### ISSUE THREAD

**Issue by CatNofishing** [scipy/scipy#12187]
minimize(fun,[1,2],method='dogleg',jac=gradient,hess=scipy.optimize.BFGS)

According to  the official document:
       Or, objects implementing HessianUpdateStrategy interface can be used to approximate the 
       Hessian. Available quasi-Newton methods implementing this interface are: BFGS;SR1。

I  have a try to use "scipy.optimize.BFGS"  ,but it raise ValueError: `exception_strategy` must be 'skip_update' or 'damp_update'.
Besises,  I am puzzled by the official document's description of solving Hesse matrix by finite-differences，I  am  not sure which  algorithm can use   finite-differences to estimate Hess . It seems that only trust-constr can use  finite-differences ( It is right?) .  Why is the description of Hesse matrix so superfluous？

**Comment by andyfaff** [comment]
It's not possible to use 'dogleg' a a HessianUpdateStrategy, such as `hess=BFGS()`, it can only be used with a `callable(hess)`.

The description of the hess keyword is improved in #15019, at which point this issue can be closed.

Note that BFGS must be instantiated before use.
