### ISSUE TITLE
retrieve leave colors from dendrogram

### ISSUE THREAD

**Issue by alejandro-ariza** [scipy/scipy#12190]
**Is your feature request related to a problem? Please describe.**
I can not retrieve leaves colors from [scipy.cluster.hierarchy.dendrogram](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.dendrogram.html). I need it to color other type of graphics. An example is posted [here](https://stackoverflow.com/questions/61959602/retrieve-leave-colors-from-scipy-dendrogram).

**Describe the solution you'd like**
Include a new key in the dendrogram dictionary informing about color leaves.

**Describe alternatives you've considered**
Provide in the meantime an algorithm to obtain the leaves colors using the information contained in the current dendrogram dictionary, if that's possible. Or another workaround.

**Additional context (e.g. screenshots)**
Code example:
```
import numpy as np
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import linkage, dendrogram

# DATA EXAMPLE
x = np.array([[ 5, 3],
              [10,15],
              [15,12],
              [24,10],
              [30,30],
              [85,70],
              [71,80]])

# DENDROGRAM
plt.figure()
plt.subplot(121)
z = linkage(x, 'single')
d = dendrogram(z)

# COLORED PLOT
# This is what I would like to achieve. Colors are assigned manually by looking
# at the dendrogram, because I failed to get it from d['color_list'] (it refers 
# to links, not observations)
plt.subplot(122)
points = d['leaves']
colors = ['r','r','g','g','g','g','g']
for point, color in zip(points, colors):
    plt.plot(x[point, 0], x[point, 1], 'o', color=color)
```
Figure output from code example:
![image](https://user-images.githubusercontent.com/38434631/82689740-42821600-9c5b-11ea-8b7c-f979df7cd85d.png)

**Comment by rgommers** [comment]
Thanks for the clear motivation @alejandro-ariza. This feature makes sense to me, and we can add that to the returned dict without backwards compatibility hassles.

Would you want to work on this? A PR would be very welcome.

**Comment by alejandro-ariza** [comment]
Hi @rgommers, thanks for your reply. I prefer not to mess things up in Scipy, I don't think I have the proper skills for that. Fortunately, someone else helped me out with this problem in [stackoverflow](https://stackoverflow.com/questions/61959602/retrieve-leave-colors-from-scipy-dendrogram/61964297#61964297). Not sure this is the right approach to implement in Scipy (a reverse operation), but hope it helps to other user in the meantime.
