### ISSUE TITLE
PERF: scipy.linalg.pinv is very slow compared to numpy.linalg.pinv

### ISSUE THREAD

**Issue by sturlamolden** [scipy/scipy#12196]
The functions should do the same, but are implemented differently. NumPy uses SVD and SciPy uses a QR based solver from LAPACK. The effect is obvious for anyone who cares to look. 

Is there any reason we should not just alias the NumPy version instead?

```
C = np.random.rand(1000,20)
F = np.asfortranarray(C.copy())

%timeit np.linalg.pinv(C)
610 µs ± 17.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit np.linalg.pinv(F)
583 µs ± 2.88 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

%timeit scipy.linalg.pinv(C)
34.8 ms ± 1.34 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

%timeit scipy.linalg.pinv(F)
33.6 ms ± 329 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by larsoner** [comment]
Perhaps compare to scipy.linalg.pinv2, which uses SVD under the hood as well?

**Comment by sturlamolden** [comment]
Yes, closing in on NumPy's performance. The difference might be due to f2py.

Is there any reason we have ```scipy.linalg.pinv``` when it does the same as ```scipy.linalg.pinv2```, only with 60x longer run-time? 

```
%timeit scipy.linalg.pinv2(C)
663 µs ± 23.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
%timeit scipy.linalg.pinv2(F)
645 µs ± 22.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

**Comment by ilayn** [comment]
It's not less stable but unfortunately quite wasteful. If you flip the shape of the arrays they will have comparable performance results

```python
%timeit np.linalg.pinv(C)
5.1 ms ± 59 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit sp.linalg.pinv(C)
5.18 ms ± 19.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

The issue we have in the SciPy pinv is not taking the shorter route and forming a huge linear problem when we don't need it.

**Comment by ilayn** [comment]
With the proposed PR, the time difference worst case is bounded by x2 slow speed. For the same shape above the results are 

```python
%timeit sp.linalg.pinv(A)
5.17 ms ± 73.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit np.linalg.pinv(A)
2.76 ms ± 59.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
with the extra time spent on the transposition and f2py overhead (I think)
