### ISSUE TITLE
spsolve error: nzvals is not of a type supported by SuperLU

### ISSUE THREAD

**Issue by dusankojic** [scipy/scipy#12191]
I'm trying to use the sparse matrix solver to fit a baseline to some spectral data, by solving a matrix equation of the type: Ax=b.

Here's a section of my input array:

```
y = np.asarray([0.3227648437023163, 0.3186240792274475, 0.31572669744491577,
                       0.3266492336988449, 0.31392455101013184, 0.31541168689727783,
                       0.3163585960865021, 0.3191247135400772, 0.3223631978034973],
                      dtype=float)

```
and the script:
```
import numpy as np
from scipy import sparse
from scipy.sparse.linalg import spsolve

def baseline_als(y, lam, p, niter=10):
  L = len(y)
  D = sparse.csc_matrix(np.diff(np.eye(L), 2))
  w = np.ones(L)
  for i in xrange(niter):
    W = sparse.spdiags(w, 0, L, L)
    Z = W + lam * D.dot(D.transpose())
    z = spsolve(Z, w*y)
    w = p * (y > z) + (1-p) * (y < z)
  return z

bl = baseline_als(y, lam=1e05, p=.01, niter=10)
```
that reproduce the following error message:
```
Traceback (most recent call last):
  File "/Users/user/script.py", line 16, in <module>
    bl = baseline_als(y, lam=1e+05, p=0.01, niter=10)
  File "/Users/user/script.py", line 12, in baseline_als
    x = spsolve(A, b)
  File "/usr/local/lib/python3.8/site-packages/scipy/sparse/linalg/dsolve/linsolve.py", line 195, in spsolve
    x, info = _superlu.gssv(N, A.nnz, A.data, A.indices, A.indptr,
TypeError: nzvals is not of a type supported by SuperLU
```
(The recommended parameters' values are 0.001 ≤ p ≤ 0.1  and 10^2 ≤ λ ≤ 10^9, so I followed up with p=0.01, and lambda =1e05.)

Interestingly, when a random vector is supplied:
```
y_randn = np.random.randn(9)
```
the function produced some real output, without any error messages. Since error message points to the shape of input array I looked at ```linsolve.py```'s line 196 but couldn't deduce how to proceed as my vector ```w*y``` is correctly shaped. Running the ```type``` command on both, ```y``` and ```y_randn```,  produced the expected result:
```
    (9,), <class 'numpy.ndarray'>
    (9,), <class 'numpy.ndarray'>
```

I'm utterly confused about how to troubleshoot this error. Any suggestions would be highly appreciated.

System: OSX 10.15.4, numpy 1.18.3, scipy 1.4.1

**Comment by ilayn** [comment]
I can't reproduce this. Please add `print(<var>)` and `print(type(<var>))` statements in your code almost before and after everyline to find out where it starts getting strange. Also please provide the version information of all components. System, numpy version, scipy version etc. 

Otherwise we can't know what is happening on your system.

**Comment by dusankojic** [comment]
This is embarrassing because now I can't reproduce this either. After more than one week of encountering this error consistently I cannot tell what went wrong. I even back checked with my raw data and it works. The only thing that I can  see changed was explicitly setting ```y = np.asarray(y, dtype=float)```. Now all I can say is that this should not be reported and I apologize for any inconvenience.

**Comment by ewmoore** [comment]
@dusankojic, this is just a thought, but given that it looks like your using a Whittaker smoother for your baseline model, you should know that you can also solve this using `scipy.linalg. cho_solve_banded`.   I’ve found this to be more important when optimizing lambda.

**Comment by dusankojic** [comment]
@ewmoore , thank you ! Since I'm working with spectroscopic data Whittaker seemed popular. Haven't used ```cho_solve_banded``` yet so I will give it a try.

**Comment by perimosocordiae** [comment]
As it happens, I have a library with several baseline removal algorithms implemented, including ALS. Here's the implementation of Whittaker smoothing:
 https://github.com/all-umass/superman/blob/346fc0d590f40bfe0141630e3146ec8e7ee18be3/superman/baseline/common.py#L89

I had to pull some tricks to make it performant, and ended up not using a scipy.sparse matrix at all, as `scipy.linalg.solveh_banded` consumes a specialized input format.

The ALS implementation is here:

https://github.com/all-umass/superman/blob/346fc0d590f40bfe0141630e3146ec8e7ee18be3/superman/baseline/als.py#L7

**Comment by dusankojic** [comment]
@perimosocordiae : much appreciated ! Do you have any updated links to the Eilers & Boelens 2005 paper, referenced in the description of `als.py` ?

**Comment by perimosocordiae** [comment]
It's surprisingly hard to find given how often it's referenced, but here's one I found with a little googling:

http://static.tongtianta.site/paper_pdf/cdaed910-a7ca-11e9-a7c6-00163e08bb86.pdf

**Comment by dusankojic** [comment]
Unusually hard because even the papers referencing it lead to nowhere, or to equally dead google citations or pubmed. Pubmed query showed 191 citations (as of yesterday) but gave zero links.

So thank you very much for the link!
