### ISSUE TITLE
Minimize with 'trust-constr' violates the constraint, which causes an error

### ISSUE THREAD

**Issue by fanzaUCDavis** [scipy/scipy#12195]
Hi,

I have been trying to use minimize with the method 'trust-constr' to solve a maximum-likelihood optimization problem. I was getting some errors so I decided to do a few print() to debug and I realized that the problem was that the minimization algorithm was returning a probability distribution with negative values, despite the fact that I specified the bounds. In turn this causes problems when it has to be put as an input into the log-likelihood as the log of a negative number raises errors. 
I suspected it was due to the fact that evaluation of the derivatives could cause issues at the boundaries, so I also tried passing the analytical form of the jacobian. Same problem, negative values show up.

Here is the code. I am not including some previously defined functions as the code is a bit involved. Commented parts of the code should be enough to clarify related issues

#### Reproducing code example:

```
def discrete_loglikelihood(q_hk,EFF,counting_data,Mx,My):
    N_tot = np.sum(counting_data)
    q_hk=q_hk.flatten()
    if any(q_hk<0)==True:
        print('q_hk = {}'.format(q_hk))
    l0, l1, l2, l3 = counting_data[0]/N_tot*np.log(np.sum(q_hk*EFF[0].flatten())), counting_data[1]/N_tot*np.log(np.sum(q_hk*EFF[1].flatten())), counting_data[2]/N_tot*np.log(np.sum(q_hk*EFF[2].flatten())), counting_data[3]/N_tot*np.log(np.sum(q_hk*EFF[3].flatten()))
    return -(l0+l1+l2+l3)


def derivative(q_hk,counting_data,EFF,Mx,My):
    N_tot = np.sum(counting_data)
    q_hk=q_hk.flatten()
    l0, l1, l2, l3 = counting_data[0]/N_tot*(EFF[0]/np.sum(q_hk*EFF[0].flatten())), counting_data[1]/N_tot*(EFF[1]/np.sum(q_hk*EFF[1].flatten())), counting_data[2]/N_tot*(EFF[2]/np.sum(q_hk*EFF[2].flatten())), counting_data[3]/N_tot*(EFF[3]/np.sum(q_hk*EFF[3].flatten()))
    return -(l0+l1+l2+l3).flatten()

#The function to be passed into minimize are functions of the first argument only, which is a probability distribution q_hk. The other arguments specify some physics-related parameters of the problem at hand. 

def function(q_hk):
    return discrete_loglikelihood(q_hk,grid_effects(4,4),Counting_DiracDelta,4,4)

def jacobian(q_hk):
    return derivative(q_hk,Counting_DiracDelta,grid_effects(4,4),4,4)

bounds = Bounds([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])
#Our variables are probabilities, so they are bounded to be  0 <= q_hk <= 1

linear_constraint = LinearConstraint([[1, 1, 1, 1,1,1, 1, 1,1, 1, 1, 1,1,1, 1, 1]], [1], [1])
#Linear constraint to implement the normalization of probabilities.

x0 = np.random.rand(16) #Random Initial condition
x0 = x0/np.sum(x0) #Normalize it 
res = minimize(function, x0, method='trust-constr', bounds=bounds, jac=jacobian, constraints=linear_constraint)
```

#### Error message:

```
q_hk = [-0.06309215  0.08539274  0.11986699  0.05662226 -0.06446086  0.14704886
  0.19196886  0.03468465 -0.14663683  0.05595011  0.2144567   0.03360037
  0.00917441  0.09173818  0.20556968  0.02811603]
q_hk = [-0.12236064  0.06874503  0.15416735  0.02735955 -0.12871547  0.14107397
  0.25955901  0.01576567 -0.20358945  0.0724261   0.29083748  0.02689568
 -0.01822524  0.11303518  0.26531718  0.0377086 ]

/Users/fanza/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in log
  # This is added back by InteractiveShellApp.init_path()

```

**Comment by fanzaUCDavis** [comment]
I forgot to explain the meaning of EFF. It's a list of 4 matrices, EFF[0],EFF[1],EFF[2],EFF[3] with the same dimensions of the probability distribution to optimize q_hk:
EFF[i].shape == q_hk.shape
True

counting_data is a list of 4 integers, representing some actual experimental data. Its value is given by a numpy array previously loaded into Counting_DiracDelta.

**Comment by mdhaber** [comment]
You should try the `keep_feasible` option on the [`LinearConstraint`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.LinearConstraint.html#scipy.optimize.LinearConstraint) and [`Bounds`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.Bounds.html#scipy.optimize.Bounds).

**Comment by fanzaUCDavis** [comment]
Hi @mdhaber, thank you for the suggestion. I have tried a few things. First, the problem appears only when I try random initial conditions, possibly because of the fact that when the dimensionality of the problem is very high, normalizing a vector whose components are randomly taken from 0 and 1 gives you a lot of terms that are, indeed, already quite close to zero. So, even though this should not happen, I understand the algorithm might have some issues when it's close to the boundaries.

However, if I start from an initial condition where every element is zero and there is one component which is one, the optimization doesn't do anything, it gets stuck on the initial condition, whatever the non-zero element I choose, this will also be the final result. I can try and play with other initial conditions, but these results make me suspicious of the result.

**Comment by mdhaber** [comment]
Ok... but did you try what I suggested? The title of this issue is that constraints are being violated, yet you did not post code that suggested use of the `keep_feasible` option. Let's try that before going further.

**Comment by fanzaUCDavis** [comment]
Oh, sorry if my answer wasn't clear. Yes, everything I said before it's true if and only if I use keep_feasible=True in both Bounds and LinearConstraint. 
I apologize for the lack of clarity.

**Comment by mdhaber** [comment]
What version of SciPy are you using?

**Comment by fanzaUCDavis** [comment]
'1.4.1'

**Comment by mdhaber** [comment]
Do you think this could be related to gh-11649

**Comment by fanzaUCDavis** [comment]
Thank you for suggesting it. I'll look into this and related issues, but it's going to take me a bit as I'm not an expert. It does seem to be related, but also notice that even though I can visually see that the probability distribution I obtain has negative elements, there is never an error related. The error is a calculation-related one, due to the fact that I'm using the log of a negative number. So, for some reason, whatever test the algorithm is running to check if the output of an iteration satisfies the bounds, it doesn't seem to spot the problem.
I'll get back here once I understand better gh-11649, thank you.

**Comment by mdhaber** [comment]
I'll try running the code today. @antonior92 take a look at the constraints here - any reason why `keep_feasible` might not work?

@fanzaUCDavis I'm not so surprised that the guess that is a column of the identity matrix gets stuck in a local minimum.

BTW your problem is pretty small - you might want to try `differential_evolution`

**Comment by fanzaUCDavis** [comment]
I understand, thanks for the help. Also, I tried setting up the problem in a different way and it looks like differential_evolution is working very well. So, thank you again for this further suggestion. I'm going to close the issue and, if I run into the same issue again I'll open another one.

**Comment by mdhaber** [comment]
I would like to be able to run your code to see if this issue should remain open or be merged with another. Can you replace your post above with code that can be executed? (e.g. include imports, `Counting_DiracDelta`, `grid_effects`...)

**Comment by fanzaUCDavis** [comment]
def qubit_grid(Mp,Mphi):
    del_P = 1/Mp #size of the discretization along p
    del_PHI = 2*np.pi/Mphi #size of the discretization along phi
    P_grid = np.linspace(0,1,Mp+1) #boundary values of the grids along p - size Mp+1
    PHI_grid = np.linspace(-np.pi,np.pi,Mphi+1) #boundary values of the grid along phi - size Mphi+1
    P_k = P_grid[:-1] + del_P/2 #p-position associated to the squares of the grid - size Mp
    PHI_j = PHI_grid[:-1] + del_PHI/2 #phi-position associated to the squares of the grid - size Mphi
    P, PHI = np.meshgrid(P_k, PHI_j) #Grid - size (Mp+1,Mphi+1)
    return P_k, PHI_j, P_grid, PHI_grid, P, PHI


P_k, PHI_j, P_grid, PHI_grid, P, PHI = qubit_grid(20,20)

def boundaries_check(point):
    if point[0]>=0 and point[0]<=1 and point[1]>=-np.pi and point[1]<=np.pi:
        return True
    else:
        return False

def psi(x,y):
    if boundaries_check(np.array([x,y]))==True:
        if x==1:
            return np.array([0,1])
        else:
            return np.sqrt(1-x)*np.array([1,0])+np.sqrt(x)*np.exp(1j*y)*np.array([0,1])
    else:
        return print('The point x = {}, y = {} is not a valid state'.format(x,y))


def expectation(A,psi):
    aux = np.matmul(A,psi)
    return np.vdot(psi,aux)

sx = np.array([[0,1],[1,0]])
sy = np.array([[0,-1j],[1j,0]])
sz = np.array([[1,0],[0,-1]])
id1 = np.eye(2)

def observable(vector):
    return 0.25*(np.eye(2)+vector[0]*sx+vector[1]*sy+vector[2]*sz)

vec_povm = []
vec_povm.append(1/np.sqrt(3)*np.array([1,1,1]))
vec_povm.append(1/np.sqrt(3)*np.array([1,-1,-1]))
vec_povm.append(1/np.sqrt(3)*np.array([-1,1,-1]))
vec_povm.append(1/np.sqrt(3)*np.array([-1,-1,1]))

SICPOVM = []
for k in vec_povm:
    SICPOVM.append(observable(k))

def sicpovm_effects2(i,x,y):
    return np.abs(expectation(SICPOVM[i],psi(x,y)))

def e0(x,y):
    return sicpovm_effects2(0,x,y)
def e1(x,y):
    return sicpovm_effects2(1,x,y)
def e2(x,y):
    return sicpovm_effects2(2,x,y)
def e3(x,y):
    return sicpovm_effects2(3,x,y)

def grid_effects(Mx,My):
    P_k, PHI_j, P_grid, PHI_grid, P, PHI = qubit_grid(Mx,My)
    E0, E1, E2, E3 = 100*np.ones((Mx,My)), 100*np.ones((Mx,My)), 100*np.ones((Mx,My)), 100*np.ones((Mx,My))
    for k in range(Mx):
        for j in range(My):
            E0[k,j], E1[k,j], E2[k,j], E3[k,j] = e0(P_k[k],PHI_j[j]), e1(P_k[k],PHI_j[j]), e2(P_k[k],PHI_j[j]), e3(P_k[k],PHI_j[j])
    return [E0,E1,E2,E3]




def discrete_loglikelihood(q_hk,EFF,counting_data,Mx,My):
    N_tot = np.sum(counting_data)
    q_hk=q_hk.flatten()
    if any(q_hk<0)==True:
        print('q_hk = {}'.format(q_hk))
    l0, l1, l2, l3 = counting_data[0]/N_tot*np.log(np.sum(q_hk*EFF[0].flatten())), counting_data[1]/N_tot*np.log(np.sum(q_hk*EFF[1].flatten())), counting_data[2]/N_tot*np.log(np.sum(q_hk*EFF[2].flatten())), counting_data[3]/N_tot*np.log(np.sum(q_hk*EFF[3].flatten()))
    return -(l0+l1+l2+l3)


def derivative(q_hk,counting_data,EFF,Mx,My):
    N_tot = np.sum(counting_data)
    q_hk=q_hk.flatten()
    l0, l1, l2, l3 = counting_data[0]/N_tot*(EFF[0]/np.sum(q_hk*EFF[0].flatten())), counting_data[1]/N_tot*(EFF[1]/np.sum(q_hk*EFF[1].flatten())), counting_data[2]/N_tot*(EFF[2]/np.sum(q_hk*EFF[2].flatten())), counting_data[3]/N_tot*(EFF[3]/np.sum(q_hk*EFF[3].flatten()))
    return -(l0+l1+l2+l3).flatten()

Counting_DiracDelta = np.array([405, 300, 276, 19])



#The function to be passed into minimize are functions of the first argument only, which is a probability distribution q_hk. The other arguments specify some physics-related parameters of the problem at hand. 

def function(q_hk):
    return discrete_loglikelihood(q_hk,grid_effects(4,4),Counting_DiracDelta,4,4)

def jacobian(q_hk):
    return derivative(q_hk,Counting_DiracDelta,grid_effects(4,4),4,4)

bounds = Bounds([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])
#Our variables are probabilities, so they are bounded to be  0 <= q_hk <= 1

linear_constraint = LinearConstraint([[1, 1, 1, 1,1,1, 1, 1,1, 1, 1, 1,1,1, 1, 1]], [1], [1])
#Linear constraint to implement the normalization of probabilities.

x0 = np.random.rand(16) #Random Initial condition
x0 = x0/np.sum(x0) #Normalize it 
res = minimize(function, x0, method='trust-constr', bounds=bounds, jac=jacobian, constraints=linear_constraint)

**Comment by mdhaber** [comment]
I tried to guess at the indentation, but ran into trouble with the syntax error:
`return np.sqrt(1-x)*np.array([1,0])+np.sqrt(x)np.exp(1jy)*np.array([0,1])`
I see there will be many others.
