### ISSUE TITLE
Type error in stats.ks_2samp when alternative != 'two-sided-

### ISSUE THREAD

**Issue by Davide-Bianchi** [scipy/scipy#12218]
https://github.com/scipy/scipy/blob/adc4f4f7bab120ccfab9383aba272954a0a12fb0/scipy/stats/stats.py#L6275

I believe I found a little bug in  `stats.ks_2samp()` when used with argument  `alternative='greater'` or `alternative='less'`.
At line [6275 ](https://github.com/scipy/scipy/blob/adc4f4f7bab120ccfab9383aba272954a0a12fb0/scipy/stats/stats.py#L6275
) `m` and `n` are defined from `max()` and `min()` which return and `int`.
On line 6278,  `m` and `n` are used in `np.sqrt()` returning a TypeError.
On line 6276 the same operation does not cause a problem because the variables are casted to float to perform the division.
In order to solve the issue, an explicit casting should do the trick.

**Comment by pvanmulbregt** [comment]
Hi @Davide-Bianchi  
Do you have example code that shows the problem?
Which version(s) of SciPy/NumPy/python are you using?

**Comment by Davide-Bianchi** [comment]
Hi @pvanmulbregt, thank you for your response. 
I am running `scipy 1.41.` on `python 3.7.3`. After further investigation, I found that is a bit of an edge case since it only gives problems with sizes bigger or equal than 2^31.
Alternative `'less'` or `'greater'` do not work while `'two-sided'` does.
Here there is the minimal non-working example:
`
from scipy import stats
import numpy as np
np.random.seed(12345678)  
n1 = 2097152  
n2 = 2097152 
rvs1 = stats.norm.rvs(size=n1, loc=0., scale=1)
rvs2 = stats.norm.rvs(size=n2, loc=0.5, scale=1.5)
stats.ks_2samp(rvs1, rvs2, alternative='greater')
`

**Comment by Davide-Bianchi** [comment]
I was curious and I kept investigating. I found that the problem is, using `m` and `n` from my first comment, in the operation `np.sqrt(m*n*(m+n))` performed on line [6278](https://github.com/scipy/scipy/blob/adc4f4f7bab120ccfab9383aba272954a0a12fb0/scipy/stats/stats.py#L6275) of `scipy/scipy/stats/stats.py`. The maximum integer value allowed in `np.sqrt` is 2^64-1 and using m=n=2^32-1 exceeds the threshold.
I have numpy `1.18.1`
