### ISSUE TITLE
Interpolating categorical data (interp1d)

### ISSUE THREAD

**Issue by np-8** [scipy/scipy#12222]
I'm trying to interpolate non-numerical data, and tried using the [interp1d](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html). 

```python
from scipy.interpolate import interp1d
x = [1.4, 2.8, 3.1, 4.4, 5.2]
y = ['A', 'B', 'A', 'A', 'B']
f = interp1d(x, y, kind='nearest', fill_value=None)
x_new = [1, 2, 3, 4, 5]
y_new = f(x_new)
```
However, it throws a `ValueError`: 

```python
ValueError                                Traceback (most recent call last)
<ipython-input-50-d6a055a2aef9> in <module>
----> 1 f = interp1d(x, y, kind='nearest', fill_value=None)

c:\python38\lib\site-packages\scipy\interpolate\interpolate.py in __init__(self, x, y, kind, axis, copy, bounds_error, fill_value, assume_sorted)
    459         # Force-cast y to a floating-point type, if it's not yet one
    460         if not issubclass(y.dtype.type, np.inexact):
--> 461             y = y.astype(np.float_)
    462
    463         # Backward compatibility

ValueError: could not convert string to float: 'A'
```

**Example output**

The example output would look, with `kind='nearest'` and `kind='previous'`:
```python
# with kind= 'nearest'
x_new = [1, 2, 3, 4, 5]
y_new = ['A', 'A', 'A', 'A', 'B']

# with kind= 'previous', fill_value = None
x_new = [1, 2, 3, 4, 5]
y_new = [None, 'A', 'B', 'A', 'A']
```

**Describe alternatives you've considered**
I asked a question about this on [stackoverflow](https://stackoverflow.com/questions/62015823/interpolating-categorical-data-in-python-nearest-previous-value/62016097#62016097) and one suggestion was to do the interpolation on the indexes, instead.  However, of course it would be more handy, if the `interp1d` could do this out of the box.

**Comment by ev-br** [comment]
TBH I'd think the workaround given on SO is as good as it gets. Scipy.interpolate functions receive and return floating-point values ; pre- and post-processing is best done on a user side
