### ISSUE TITLE
BUG, REL: gh_lists.py compromised scraping

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#12220]
`python tools/gh_lists.py 1.5.0 >& gh_lists.txt`

Produces only about 40 lines of output instead of listing hundreds of issues and PRs with the `1.5.0` milestone. The selected issues/PRs do appear to be valid `1.5.0` milestone selections and the basis of the reduced information capture is not immediately clear.

**Comment by larsoner** [comment]
I know for github_changelog_generator you need to provide a GitHub token to avoid hitting a GH API request limit. Maybe something similar is happening here?

**Comment by ilayn** [comment]
Probably a pagination issue https://stackoverflow.com/questions/30656761/github-search-api-only-return-30-results

**Comment by ilayn** [comment]
Here is a super-quick desktop hack which restores the functionality (just in case the script fix is not available for some reason). I've skipped the milestone fetching and harcoded `44` and also the `msg` strings. I stole the printing part from `gh_lists.py` but you can also write to a file instead.

```python
import json
import requests

resp = requests.get("https://api.github.com/repos/scipy/scipy/issues?"
                    "milestone=44&state=closed&sort=created&direction=asc")
resp.raise_for_status()
issues = resp.json()
last_page_url = resp.links['last']['url']
totpages = int(last_page_url[last_page_url.find('page=') + 5:])

for page in range(totpages-1):
  resp=requests.get(resp.links['next']['url'])
  issues.extend(resp.json())


# %%
prs = [x for x in issues if 'pull_request' in x.keys()]
iss = [x for x in issues if x not in prs]

def print_list(title, items):
    print()
    print(title)
    print("-"*len(title))
    print()

    for issue in items:
        msg = u"* `#{0} <{1}>`__: {2}"
        # sanitize whitespace, `, and *
        title = re.sub(u"\\s+", u" ", issue['title'].strip())
        title = title.replace(u'`', u'\\`').replace(u'*', u'\\*')
        if len(title) > 60:
            remainder = re.sub(u"\\s.*$", u"...", title[60:])
            if len(remainder) > 20:
                remainder = title[:80] + u"..."
            else:
                title = title[:60] + remainder
        msg = msg.format(issue['number'], issue['url'], title)
        print(msg)
    print()

msg = "Issues closed for 1.5.0"
print_list(msg, iss)

msg = "Pull requests for 1.5.0"
print_list(msg, prs)
```

**Comment by pv** [comment]
gh_lists.py does handle pagination, but there's a bug with case-sensitive HTTP header comparisons, triggered by Github apparently changing the case.

**Comment by ilayn** [comment]
I also noticed that the issue `id` became `number` but let's see what it returns
