### ISSUE TITLE
Documentation issue with stats.lognorm.fit()

### ISSUE THREAD

**Issue by DrBwts** [scipy/scipy#12224]
**stats.lognorm** is an instance of **stats.rv_continuous** yet the documetation on the **fit** method are at odds with each other.

From **stats.lognorm** docs,

> fit(data, s, loc=0, scale=1)
 
From **stats.rv_continuous** docs,

> fit(self, data, \*args, \*\*kwds)

Note this difference in listed arguments. If you try to use the method using the arguments from the **lognorm** docs then an error is thrown.

This issue was brought to [light in this Stackoverflow question.](https://stackoverflow.com/questions/61995196/something-wrong-with-scipy-stats-lognorm-fit/62005328?noredirect=1#comment109678716_62005328)

**Comment by ev-br** [comment]
Looks like it has been fixed in the dev version: 

http://scipy.github.io/devdocs/generated/scipy.stats.lognorm.html#scipy.stats.lognorm
