### ISSUE TITLE
median absolute deviation handling of nan

### ISSUE THREAD

**Issue by lkjell** [scipy/scipy#12239]
My issue is about median absolute deviation handling of nan

#### Reproducing code example:

```
from scipy.stats import median_absolute_deviation
import numpy as np

a = [22,3,4,np.nan]
b = [24,1,2,np.nan]
c = [23,5,4,1]

d = median_absolute_deviation([a,b,c], axis=0, scale=1, nan_policy="omit",
                              center=np.nanmedian)

print(d)
```

#### Error message:
expect MAD to be arrays of 4 element not a single scalar. Changing nan_policy to propagate does not help.

#### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)

1.4.1 1.18.1 sys.version_info(major=3, minor=8, micro=3, releaselevel='final', serial=0)
```

**Comment by rlucas7** [comment]
Hi Kjell,

Can you check https://github.com/scipy/scipy/pull/12217
Solves your issue? 

Sincerely, 

-Lucas Roberts

**Comment by lkjell** [comment]
@rlucas7 pr works perfect as expected with omit flag.

tested with straight forward implementation:
```
def median_absolute_deviation(x, axis=-1):
    m = np.nanmedian(x, axis=axis, keepdims=True)
    return np.nanmedian(abs(x - m), axis=axis)
```

Just have to wait for the pr to get merged.

**Comment by WarrenWeckesser** [comment]
@lkjell, thanks for reporting the issue.  The changes in https://github.com/scipy/scipy/pull/12217 didn't make it into the 1.5.0 branch; we'll see if we can backport it in a release candidate.

With the change in https://github.com/scipy/scipy/pull/12217, your example is

```
In [3]: a = [22,3,4,np.nan]

In [4]: b = [24,1,2,np.nan]

In [5]: c = [23,5,4,1] 

In [6]: median_abs_deviation([a, b, c], axis=0, nan_policy='omit')
Out[6]: array([1., 2., 0., 0.])
```

**Comment by rlucas7** [comment]
I just merged the fix into master, marking as closed.
