### ISSUE TITLE
Dendrogram: enable leaves labelling with 'labels' when using 'truncate_mode'

### ISSUE THREAD

**Issue by erheron** [scipy/scipy#12230]
**Is your feature request related to a problem? Please describe.**
Hi!

My feature request is about `cluster.hierarchy.dendrogram` function.
I've noticed, that when using `truncate_mode` it's impossible to label leaf nodes using `labels` parameter. The only solution is using `leaf_label_func`. I personally don't have many professional experience in using `hierarchy.dendrogram`, but for sure there are people who can express whether proposed feature would be useful.

**Describe the solution you'd like**
I suggest to make it possible to use `labels` together with `truncate_mode` function. E.g. to enable labelling leaves after truncation with list.

@ihowell @rgommers as far as I know You might be the right people to ask about the opinion. Would be grateful for some thoughts about that. 

I personally think that it's possible to implement, thought it might be a bit tricky.

That's the situtation I'm talking about:
```
from matplotlib import pyplot as plt
import matplotlib

from scipy.cluster import hierarchy

X = [[0,0], [0,1], [0,4], [2,4], [6,3],[7,3], [8,3]]
Z = hierarchy.linkage(X, method='single')

fig, axes = plt.subplots(1, 2, figsize=(15, 6))
dn_1 = hierarchy.dendrogram(Z, ax = axes[0])
dn_2 = hierarchy.dendrogram(Z, ax = axes[1], truncate_mode='lastp', p=3)

plt.show()
```
![plot2](https://user-images.githubusercontent.com/36896640/82944770-15f03600-9f9c-11ea-9b68-a11497c66ca5.png)

**Comment by rgommers** [comment]
I'm not sure this combination of truncation and `labels` makes sense, given that `labels` is explicitly documented as being for original observations.

I'd be inclined to just add an understandable example with `leaf_label_func` here.

**Comment by erheron** [comment]
@rgommers  something like "With `leaf_label_func` you can also label your leaves after truncation, and here's how: ..." ?

**Comment by rgommers** [comment]
Yes indeed. The `leaf_label_func` parameter description already contains a small example, but the longer one using `truncate_mode` and `leaf_label_func` together could go in the Examples section. And then refer to it from the `labels` parameter description if that makes sense to you.
