### ISSUE TITLE
Nightly Wheels Updating

### ISSUE THREAD

**Issue by bashtage** [scipy/scipy#12233]
The nightly wheels on 

https://anaconda.org/scipy-wheels-nightly/scipy/files

do not need to be updating frequently.  Is this expected?

**Comment by tylerjereddy** [comment]
> do not need to be updating frequently. Is this expected?

They should update once a week on Tuesday--I don't understand the problem from your description? We just migrated to `anaconda.org` so the first "real" nightly upload was about 6 days ago, with a very early prototype upload months before that:

![image](https://user-images.githubusercontent.com/7903078/82953297-be37d780-9f67-11ea-9e3f-b69f01a0665f.png)

We probably do need to timestamp nightly wheel filenames, but there's already an issue open in the wheels repo for that: https://github.com/MacPython/scipy-wheels/issues/77

Also, worth noting that previously weekly uploads would not happen if there was a master branch merge/build within 24 hours, but now they will always happen if no other issue crops up.

**Comment by tylerjereddy** [comment]
Also, we don't do windows wheels weekly uploads, but that's not new to `anaconda.org`; anyway, that discussion could be migrated to the wheels repo I think.

**Comment by bashtage** [comment]
On statsmodels we do the following.

We use the old nightly repo to install everything including scipy, numpy, cython, pandas and anything else that is there.

We then to a `pip install numpy pandas scipy --upgrade`  against the anaconda.org site.  For some reason the wheels on anaconda.org are not marked as later than the older ones on RackCDN.  This isn't true of NumPy or Pandas which both upgrade.

**Comment by bashtage** [comment]
It is probably MacPython/scipy-wheels#77

**Comment by tylerjereddy** [comment]
Right, `pandas` did the timestamping and then NumPy followed suite and suggested we do the same, which is why that issue is open.

**Comment by tylerjereddy** [comment]
The improved wheel naming (similar to the system used by NumPy for nightlies), appears to have worked correctly for SciPy wheel weekly uploads here: https://anaconda.org/scipy-wheels-nightly/scipy/files

So, I'll close this (and matching wheels repo issue: https://github.com/MacPython/scipy-wheels/issues/77 ), but feel free to open another if something else comes up.
