### ISSUE TITLE
scipy.stats.spearmanr mishandles all zero arrays with nan_policy='omit'

### ISSUE THREAD

**Issue by nkinsky** [scipy/scipy#12241]
My issue is about scipy.stats.spearmanr. I get incorrect r and p-values when one input array consists of all zeros and NaNs in conjunction with the ```nan_policy='omit'``` parameter.

#### Reproducing code example:
If I run the below, I get ```r = nan``` and ```p = nan```, which is correct for a correlation between a random array and a second array that is all zeros.

```
t = [1,2, 3, 4, 5]
u = [0, 0, 0, 0, 0]
r, p = sstats.spearmanr(t, u, nan_policy='omit')
```

If, however, I run the same code, but after tacking on a np.nan to the end of each array and using the nan_policy='omit' option, I get ```r = 0``` and ```p = 1```, which is incorrect. Unless I am missing something, I should get r = nan and p = nan, since after ignoring nans I am comparing the same arrays as above.

```
tnan = [1, 2, 3, 4, 5, np.nan]
unan = [0, 0, 0, 0, 0, np.nan]
r, p = sstats.spearmanr(tnan, unan, nan_policy='omit')
```

While I also see difference between the calculated r and p values when I don't include all zeros for one array, these differences are very small: 

```
x = [1,2,3,4,5]
y = [5,4,3,2,1]
r, p = sstats.spearmanr(x,y)
>>> r = -0.999999999, p = 1.4e-24

xnan = [1,2,3,4,5, np.nan]
ynan = [5,4,3,2,1, np.nan]
rnan, pnan = sstats.spearman(xnan, ynan, nan_policy='omit')
>>> rnan = -1.0, pnan = 0.0
```

#### Scipy/Numpy/Python version information:
```
1.3.1 1.16.5 sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)
```

**Comment by rlucas7** [comment]
I can confirm this is still an issue on master. 

```
(scipy-dev) Lucass-MacBook:scipy rlucas$ python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.stats as sstats 
>>> t = [1,2, 3, 4, 5]
>>> u = [0, 0, 0, 0, 0]
>>> r, p = sstats.spearmanr(t, u, nan_policy='omit')
/Users/rlucas/scipy-dev/scipy/scipy/stats/stats.py:4198: SpearmanRConstantInputWarning: An input array is constant; the correlation coefficent is not defined.
  warnings.warn(SpearmanRConstantInputWarning())
>>> tnan = [1, 2, 3, 4, 5, np.nan]
>>> unan = [0, 0, 0, 0, 0, np.nan]
>>> r, p = sstats.spearmanr(tnan, unan, nan_policy='omit')
>>> r
0.0
>>> p
>>> import numpy as np
>>> xnan = [1,2,3,4,5, np.nan]
>>> ynan = [5,4,3,2,1, np.nan]
>>> rnan, pnan = sstats.spearman(xnan, ynan, nan_policy='omit')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'scipy.stats' has no attribute 'spearman'
>>> rnan, pnan = sstats.spearmanr(xnan, ynan, nan_policy='omit')
>>> rnan
-1.0
>>> 
```

A solution for this, it seems like the easy way to handle this would be to put the same logical check into the 'masked' version of the `spearmanr`. 

Perhaps inside the omit branch here: 

https://github.com/scipy/scipy/blob/dda87ae6cea67284d26f427c0dbc1f74a36cd17f/scipy/stats/mstats_basic.py#L498

If the `nan_policy` is propagate or raise, then those will not enter the code path and would have the existing behavior. 
We'll also need to be careful about behavior of all Nan (edge case) and for the `inf` case too, to make sure the `inf` entries do not get masked. 

Given that @WarrenWeckesser just wrote a wondeful guideline on nan_policy: 
https://github.com/scipy/scipy/pull/12069/files

I'd like to ping him to see if he agrees with the general approach I'm suggesting.

**Comment by mdhaber** [comment]
@rlucas7 
I think a little more work is needed, even in the `stats.py` version, because currently the special logic that handles constant input is only triggered by constant input in the first two rows/column. 

```
    if axisout == 0:
        if (a[:, 0][0] == a[:, 0]).all() or (a[:, 1][0] == a[:, 1]).all():
            # If an input is constant, the correlation coefficient is not defined.
            warnings.warn(SpearmanRConstantInputWarning())
            return SpearmanrResult(np.nan, np.nan)
    else:  # case when axisout == 1 b/c a is 2 dim only
        if (a[0, :][0] == a[0, :]).all() or (a[1, :][0] == a[1, :]).all():
            # If an input is constant, the correlation coefficient is not defined.
            warnings.warn(SpearmanRConstantInputWarning())
            return SpearmanrResult(np.nan, np.nan)
```

Without the special logic, it actually still gives the desired output (`nan`s in the right places) but there are warnings. 

---

Here is a more general test case to consider:
```
import numpy as np
from scipy.stats import spearmanr
np.random.seed(1234321)
shape = 2, 6
tnan = np.arange(np.prod(shape)).reshape(shape)
unan = np.zeros(shape)
x = np.vstack((tnan, unan))
print(x)
```
It doesn't matter whether `tnan` and `unan` get concatenated before or after going into `spearmanr`; I just did it for convenience of checking the output. Here's what `x` looks like without any `nan`s.
```
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
```
We would expect the last two rows and columns of the 4x4 matrix to be NaN, and that's what we get. But we get a bunch of warnings.
```
> r, p = spearmanr(x, axis=1, nan_policy="omit")
> print(r)
[[ 1.  1. nan nan]
 [ 1.  1. nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]
/opt/anaconda3/envs/scipydev/lib/python3.7/site-packages/numpy/lib/function_base.py:2534: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/opt/anaconda3/envs/scipydev/lib/python3.7/site-packages/numpy/lib/function_base.py:2535: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
/Users/matthaberland/Desktop/scipy/scipy/stats/_distn_infrastructure.py:2007: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)
```
With a nan in there, it goes to mstats and we get the wrong result.
```
> x[-1, -1] = np.nan
>  r, p = spearmanr(x, axis=1, nan_policy="omit")
> print(r)
[[ 1.  1.  0.  0.]
 [ 1.  1.  0.  0.]
 [ 0.  0.  1. nan]
 [ 0.  0. nan  1.]]
```

**Comment by rlucas7** [comment]
@mdhaber 

IIUC there are a couple issues to fix here and will require a bit more care. 

Thanks for pointing this out

**Comment by mdhaber** [comment]
Yeah, I was hoping it was a quick fix, too. We'll get to it eventually : )

**Comment by nkinsky** [comment]
Thanks for all the updates Matt and Lucas, much appreciated.

Nat
________________________________

**Comment by mdhaber** [comment]
Will fix as part of gh-14651
