### ISSUE TITLE
Interpolation 2D with SmoothBivariateSpline

### ISSUE THREAD

**Issue by dankal444** [scipy/scipy#12246]
I get some strange results when using [SmoothBivariateSpline](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.SmoothBivariateSpline.html#scipy.interpolate.SmoothBivariateSpline).

I may use it in a wrong way (there is no example in a doc), so I've created simple example to reproduce my problem. Using known recipe for a 2d surface, I sample it and try to interpolate.
To make it simple I use regularly spaced grid of points although the Spline is said to allow to use non-regular grid.

```
import matplotlib.pyplot as plt
import numpy as np
import scipy.interpolate

train_x, train_y = np.meshgrid(np.arange(-5, 5, 0.5), np.arange(-5, 5, 0.5))
train_x = train_x.flatten()
train_y = train_y.flatten()
z_func = lambda x, y: np.cos(x) + np.sin(y) ** 2

train_z = z_func(train_x, train_y)
interp_func = scipy.interpolate.SmoothBivariateSpline(train_x, train_y, train_z)

test_x = np.arange(-10, 10, 0.01)
test_y = np.arange(-10, 10, 0.01)
grid_x, grid_y = np.meshgrid(test_x, test_y)

interp_result = interp_func(test_x, test_y)
perfect_result = z_func(grid_x, grid_y)

fig, axes = plt.subplots(1, 2, figsize=(12, 8))
extent = [test_x[0], test_x[-1], test_y[0], test_y[-1]]
axes[0].imshow(perfect_result, aspect='auto', cmap='nipy_spectral', extent=extent)
axes[0].plot(train_x, train_y, 'w.')
axes[0].set_title('Perfect result, sampled function')
axes[1].imshow(interp_result, aspect='auto', cmap='nipy_spectral', extent=extent)
axes[1].plot(train_x, train_y, 'w.')
axes[0].set_title('SmoothBivariateSpline')
plt.show()
```
The result is somewhat strange:

![Screenshot from 2020-05-28 12-45-31](https://user-images.githubusercontent.com/24862989/83132356-91a7cb00-a0e1-11ea-8e95-ce054ad3817f.png)

Right image should be similar to left image in the middle area, where I've provided sample points of the surface. 

Do I have some error? Or is there a bug? Or maybe you know of some other ways of interpolating using non-regularly spaced points?

**Comment by ewmoore** [comment]
The default `s` is providing too much smoothing for your application, so provide a smaller `s`.  I might start with `s = 1`.  

The docstring and/or the tutorial really could use an example.

**Comment by pv** [comment]
And unless you specifically want to do data smoothing (i.e. not just interpolation), you are probably looking for `griddata` instead of the smoothed splines.

**Comment by dankal444** [comment]
Thanks guys, decreasing smoothing solved problem. Even disabling smoothing `s=0.0` is good. 
Here is updated code (also changed the function so it is not so symmetric):

```
import matplotlib.pyplot as plt
import numpy as np
import scipy.interpolate

train_x, train_y = np.meshgrid(np.arange(-5, 5, 0.5), np.arange(-5, 5, 0.5))
train_x = train_x.flatten()
train_y = train_y.flatten()
z_func = lambda x, y: np.cos(x) + np.sin(y) ** 2 + 0.05 * x + 0.1 * y
train_z = z_func(train_x, train_y)
interp_func = scipy.interpolate.SmoothBivariateSpline(train_x, train_y, train_z, s=0.0)

test_x = np.arange(-10, 10, 0.01)
test_y = np.arange(-10, 10, 0.01)
grid_x, grid_y = np.meshgrid(test_x, test_y)

interp_result = interp_func(test_x, test_y)
perfect_result = z_func(grid_x, grid_y)

fig, axes = plt.subplots(1, 2, figsize=(16, 7))
extent = [test_x[0], test_x[-1], test_y[0], test_y[-1]]
im = axes[0].imshow(perfect_result, aspect='auto', cmap='nipy_spectral', extent=extent, vmin=-1.5, vmax=2.5)
fig.colorbar(im, ax=axes[0])
axes[0].plot(train_x, train_y, 'w.')
axes[0].set_title('Perfect result, sampled function')
im = axes[1].imshow(interp_result, aspect='auto', cmap='nipy_spectral', extent=extent, vmin=-1.5, vmax=2.5)
fig.colorbar(im, ax=axes[1])
axes[1].plot(train_x, train_y, 'w.')
axes[1].set_title('SmoothBivariateSpline')
plt.show()
```
And result:
![Screenshot from 2020-05-28 23-36-34](https://user-images.githubusercontent.com/24862989/83196389-1a535500-a13c-11ea-9298-bc608b09fb36.png)

For some reason the result is transposed. I read the script 3 times and can't find the bug. 
But well, it is fine for me, just doing `.T` somewhere, but I thought you may want to know there might be something wrong inside `SmoothBivariateSpline`.

I am not sure if it is good enough but just in case - feel free to add this example to the docs.

**Comment by ev-br** [comment]
This example is now included into gh-16707. Thank you @dankal444 !
A review of gh-16707 from a user perspective would be much appreciated BTW.

**Comment by ev-br** [comment]
This example is now a part of the tutorial, merged as a part of gh-16707. Thanks @dankal444 !
