### ISSUE TITLE
Codecov migration to marketplace app

### ISSUE THREAD

**Issue by thomasrockhu** [scipy/scipy#12240]
Hi, Tom from [Codecov](https://codecov.io) here.

We noticed that you are using Codecov with fairly high frequency, and we’re so excited to see that! However, because you are not using our app, you may have experienced issues with uploading reports or viewing coverage information. This is due to rate-limiting issues from GitHub.

**In order to prevent any future outages, we ask that you move over to our [GitHub app integration](https://github.com/apps/codecov).**

The process is extremely simple and shouldn’t require more than a few clicks, and you should not expect any downtime. By moving to our app, you will no longer need an admin or separate account to manage the relationship with GitHub as the team bot.

Let me know if you have any questions, or if I can help at all with this process.

**Comment by rgommers** [comment]
@tylerjereddy our SciPy code coverage is in better shape, and the Codecov UI has improved to the point where it seems to be able to show all our coverage results now. Should we try the GitHub app integration?

**Comment by tylerjereddy** [comment]
Worth a try I think--can you or Pauli or Evgeni set that up as owners?

Pauli had previously speculated that we were trying to send more data to codecov than it could handle, at least two years ago.

I sent an email to `support@codecov.io` on 6th September, 2018 asking for assistance, and when we did not receive a response we were not optimistic about resolving the matter.

Great if we have a responsive contact for occasional help now.

**Comment by thomasrockhu** [comment]
@tylerjereddy, that's on us for not responding a few years ago. Since that time, Codecov has seen a lot of positive change including our support. You are welcome to reach out to me this way or via our [community boards](community.codecov.io)

**Comment by tylerjereddy** [comment]
Great!

**Comment by rgommers** [comment]
The CodeCov GitHub App is now installed.

**Comment by thomasrockhu** [comment]
Thanks @rgommers and @tylerjereddy! Let me know if there's anything I can help with.
