### ISSUE TITLE
ENH: least_squares: should not re-instanciate csr_matrix if already provided by user (performance gain)

### ISSUE THREAD

**Issue by Didou09** [scipy/scipy#12249]
**Current status (scipy 1.4.1)**
-----------------------------------------
* When using `scipy.optimize.least_squares()`, the user can, if he/she knows its form, provide the jacobian as a callable to accelerate convergence and avoid discretization errors.
* This option is very valuable since it can make a significant difference, especially for problems with large datasets and many variables (i.e.: large jacobian matrices)
* Currently, `scipy.optimize.least_squares()` first checks whther jac is callable, and if so tests whether it is sparse, because when the user provides a sparse jacobian it should be faster use at every iteration.
* If sparse, a wrapper is implemented to make sure the jac is a csr_matrix format
* This wrapper is called for every iteration, hence possibly hundreds or thousands of times, and every time it converts jac to csr_matrix
* This conversion takes a bit of time (not much I agree), but it does not take advantage of the fact the user may **already** provide jac as a csr_matrix, in which case this conversion is not necessary and time can be saved at every iteration. 

**I would suggest**
---------------------------
* The docstring should explain that, even when it is a callable, jac can (and probably should) be provided as a sparse csr_matrix by the user (indeed, I though sparsity was only relevant for discrete evaluations of jac, i.e.: '2-points' or '3-points', I only realized that a sparse callable would be used too by looking at source code).
* To preserve the generality of the scipy.sparse.csr_matrix() instanciation and still save time when jac is already a csr_matrix, we could:
- test if csr_matrix and implement wrapper only if not
- or use the method .tocsr() which does the same except that, by default, if the matrix is already csr it returns a reference to itself, which is much faster than forcing instanciation of a new csr
- or make sure csr_matrix instanciation returns a reference to the passed array if it is already a csr_matrix (i.e.: equivalent to using tocsr() method)

A solution is proposed in PR #12250 

**Performance gain evaluation**
-------------------------------------------
```
In [1]: import scipy.sparse as scpsparse                                                                                                                                                 

In [2]: a = scpsparse.csr_matrix(np.random.random((100,1000)))                                                                                                                           

In [3]: %timeit b = scpsparse.csr_matrix(a)                                                                                                                                              
19.1 µs ± 158 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [4]: %timeit b = a.tocsr()                                                                                                                                                            
106 ns ± 0.644 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [5]: 19e3/106                                                                                                                                                                         
Out[5]: 179.24528301886792
```
That's two orders of magnitude faster, and the gain occurs at every iteration of least_squares().

Indeed, tocsr() returns a reference to the already existing instance by default:
```
In [13]: a.tocsr??                                                                                                                                                                       
Signature: a.tocsr(copy=False)
Docstring:
Convert this matrix to Compressed Sparse Row format.

With copy=False, the data/indices may be shared between this matrix and
the resultant csr_matrix.
Source:   
    def tocsr(self, copy=False):
        if copy:
            return self.copy()
        else:
            return self
```

**Comment by perimosocordiae** [comment]
Fixed by gh-12250.
