### ISSUE TITLE
special.fresnel documentation error

### ISSUE THREAD

**Issue by bertrandhaut** [scipy/scipy#12252]
According to https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.fresnel.html the fresnel functions are defined as:

S(z) = \int_0^z cos( pi t^2/2) dt
C(z) = \int_0^z sin( pi t^2/2) dt

The "S" function is associated to the "cos" and the "C" function to the "sin".

I presume it should be the inverse. At least this is not in line with the reference mentioned https://dlmf.nist.gov/7.2#iii

**Comment by pv** [comment]
Was fixed in gh-11519
