### ISSUE TITLE
hot to get the required parameters of the distributions in a systematic way

### ISSUE THREAD

**Issue by gioxc88** [scipy/scipy#12268]
I am trying with no success to obtain information about the parameters required for instantiating a particular distribution. In particular continuous distributions.

I know that all of them share the `loc` and `scale` parameter.

But, for example, lets say that I have the `stats.ksone`. Is there a way to know in advance (before calling any method) that this particular distribution requires also the `n` parameter?

I would need to do this argument parsing for all the continuous distributions:
`dist_continu = [d for d in dir(stats) if isinstance(getattr(stats, d), stats.rv_continuous)]`

but after spending a few hours on it I don't know how to proceed.
I tried with `inspect` and also by parsing the docstring but I only get `*args` and `**kwargs` as result 

Any suggestion would be appreciated

**Comment by rkern** [comment]
```
>>> from scipy import stats
>>> stats.beta.shapes
'a, b'
>>> stats.ksone.shapes
'n'
```

**Comment by gioxc88** [comment]
> ```
> >>> from scipy import stats
> >>> stats.beta.shapes
> 'a, b'
> >>> stats.ksone.shapes
> 'n'
> ```

Thank very much you for the answer. Anyway to also have information about the range of this arguments or if it is floating or integer?
