### ISSUE TITLE
Get zero in scipy.stats.norm.sf

### ISSUE THREAD

**Issue by weiguowilliam** [scipy/scipy#12261]
I need to report the p-value for z test. So I use sf function. But it returns zero. I wonder how it could be more accurate? Or what's the range of sf function? So I can write P as smaller than the threshold of survival function. 

Thank you !!

**Comment by WarrenWeckesser** [comment]
At what value are you computing the sf?

One option is to compute the log of the survival function by using the `logsf` method.

For example, for the standand normal distriubition (i.e. mean 0, standard deviation 1), sf(50) is about 1.0e-545.  That number is too small to represent with standard 64 bit floating point numbers, and `norm.sf(50)` returns 0:
```
In [13]: from scipy.stats import norm

In [14]: norm.sf(50)
Out[14]: 0.0
```
The *logarithm* of that value is well within the capabilties of standard floating point representation:
```
In [15]: norm.logsf(50)                                                                                                                  
Out[15]: -5005.524208694205
```

**Comment by weiguowilliam** [comment]
@WarrenWeckesser 
Thank you so much for your help! 
I need to deal with sf(143). 
I just tested with logsf and logsf(143) = -10230. So I can say p-value = (10)**(-10230). 
Am I correct?

**Comment by WarrenWeckesser** [comment]
I should add that, for any "real world" application, there is probably no need for computing an accurate p-value so far out in the tail of the distribution.   If  the p-value is anywhere in the range where the value is too small to represent with standard floating point, then either the result is, let's say *highly* signficant 😄 , or there is a mistake somewhere in the data analysis.

**Comment by WarrenWeckesser** [comment]
> Am I correct?

Not quite.  The logarithm in `logsf` is the natural logarithm.  To get the logarithm with base 10, divide the result by np.log(10):

```
In [28]: norm.logsf(143)/np.log(10)          
Out[28]: -4442.9983774267785
```

**Comment by weiguowilliam** [comment]
@WarrenWeckesser 
Thank you so much for your help! That really helps.
