### ISSUE TITLE
Adding Cramér’s V and Theil’s U into scipy.stats

### ISSUE THREAD

**Issue by idankash** [scipy/scipy#12299]
**Is your feature request related to a problem? Please describe.**

Currently, whenever I want to visualize features correlation I'm using df.corr() from pandas, but when I have a dataset with categorical features I have to encode them before using df.corr() if I want to include the categorical features. To solve this I can pass a method to the function like so:
df.corr(method=cramers_v)

**Describe the solution you'd like**

I'd like to implement Cramér’s V and Theil’s and put it in scipy.stats so I can use them.

Thanks,
Idan Kashtan :)

**Comment by rgommers** [comment]
PR gh-8157 (in progress) has a Cramer's V implementation.
