### ISSUE TITLE
ODR results with huge relative errors for sd_beta

### ISSUE THREAD

**Issue by saroad2** [scipy/scipy#12294]
When running the ODR algorithm on some experiment data, I've been asked to run it with the following model:
![CodeCogsEqn](https://user-images.githubusercontent.com/19425795/83486794-8cb49400-a4b2-11ea-8f9a-cc9fc18772d6.gif)
It is clear that this fitting function is containing a redundant degree of freedom.

When I run the fitting on my experiment data I get enormous relative errors of beta, starting from 8000% relative error.

When I try to run the fitting again but with a fitting function that doesn't have a redundant degree of freedom, such as:
![CodeCogsEqn](https://user-images.githubusercontent.com/19425795/83486976-db622e00-a4b2-11ea-8e77-c86fc081016c.gif)
I don't get this kind of problem.

Why is this happening? Why the ODR algorithm is so sensitive for redundant degrees of freedom? I wasn't able to answer these questions to my supervisors. An answer will be much appreciated.

#### Reproducing code example:

```python
from scipy.odr import RealData, Model, ODR


def func1(a, x):
    return a[0] * (x + a[1]) / (a[3] * (x + a[1]) + a[1] * x) + a[2]


def func2(a, x):
    return a[0] / (x + a[1]) + a[2]


# fmt: off
zx = [
    1911.125, 2216.95, 2707.71, 3010.225, 3410.612, 3906.015, 4575.105, 5517.548,
    6918.481,
]
dx = [
    0.291112577, 0.321695254, 0.370771197, 0.401026507, 0.441068641, 0.490601621,
    0.557573268, 0.651755155, 0.79184836,
]
zy = [
    0.000998056, 0.000905647, 0.000800098, 0.000751041, 0.000699982, 0.000650532,
    0.000600444, 0.000550005, 0.000500201,
]
dy = [
    5.49029e-07, 5.02824e-07, 4.5005e-07, 4.25532e-07, 3.99991e-07, 3.75266e-07,
    3.50222e-07, 3.25003e-07, 3.00101e-07,
]
# fmt: on

data = RealData(x=zx, y=zy, sx=dx, sy=dy)

print("Func 1")
print("======")
beta01 = [
    1.46,
    4775.4,
    0.01,
    1000,
]
model1 = Model(func1)
odr1 = ODR(data, model1, beta0=beta01)
result1 = odr1.run()
print("beta", result1.beta)
print("sd beta", result1.sd_beta)
print("relative", result1.sd_beta / result1.beta * 100)


print()
print()


print("Func 2")
print("======")
beta02 = [
    1,
    1,
    1,
]
model2 = Model(func2)
odr2 = ODR(data, model2, beta0=beta02)
result2 = odr2.run()
print("beta", result2.beta)
print("sd beta", result2.sd_beta)
print("relative", result2.sd_beta / result2.beta * 100)
```

This prints out:
```
Func 1
======
beta [ 1.30884537e+00 -2.82585952e+03  7.79755196e-04  9.47943376e+01]
sd beta [1.16144608e+02 3.73765816e+06 6.12613738e-01 4.20775596e+03]
relative [   8873.82193523 -132266.24068473   78564.88054498    4438.82627453]


Func 2
======
beta [1.40128121e+00 9.80844274e+01 3.00511669e-04]
sd beta [2.73990552e-03 3.22344713e+00 3.74538794e-07]
relative [0.1955286  3.28640051 0.12463369]
```

#### Scipy/Numpy/Python version information:
Versions are:
* **Scipy** - 1.4.1
* **Numpy** - 1.18.2
* **Python** - 3.7.2

**Comment by rkern** [comment]
When two parameters can be traded off with each other, the estimates of the _marginal_ errors on each will be very high. You can change one almost infinitely because you can make it up by changing the other. The covariance matrix is probably highly diagonal for the two that trade off, though. This is a general instance of the [parameter identification problem](https://en.wikipedia.org/wiki/Parameter_identification_problem). You generally do need to remove redundant degrees of freedom from your parameterizations before using nonlinear regressions. ODRPACK is not particularly bad in that regard, I don't think.
