### ISSUE TITLE
Scipy's ks_2samp function returns correct D_statistic but wrong p_value

### ISSUE THREAD

**Issue by Maxence1607** [scipy/scipy#12295]
I perform a two-sample Kolmogorov-Smirnov test to check whether two samples come from the same population. Here is the code to reproduce my problem:

```
from scipy.stats import ks_2samp
import numpy as np

x = list(np.random.normal(10, 1, 3000))
y = list(np.random.normal(12, 1, 2000))
d_statistic, p_value = ks_2samp(x, y)
```
My python version is 3.6.8.
With scipy versions older than 1.3, I get the following results: d_statistic = 0.67317 and p_value = 0.0
However with scipy versions >= 1.3: d_statistic = 0.6705 and p_value = 0.9904774590824749

Both give almost the same d_statistic but the most recent versions of scipy seem to give me a wrong p_value and I do not understand why. Indeed x and y are clearly two samples which do not come from the same population.

I did some research and since scipy==1.3 the 'exact' mode was released and is the default mode for small samples (len(x), len(y) <= 10000 which is the case here). However, if I change the mode from 'exact' to 'asymp' I get the same results as the ones I got from the oldest scipy versions.

`d_statistic, p_value = ks_2samp(x, y, mode='asymp')`

In addition, no matter the scipy version I use, the scipy.stats.mstats.ks_2samp function returns a small p_value (almost 0)...

Is there a problem with the 'exact' mode when computing the p_value or am I missing something?

Thanks for your help, h1t5uj1

**Comment by chrisb83** [comment]
Thanks for reporting this bug. It might be the same issue reported in #11184 which was fixed in 1.5.0.

**Comment by Maxence1607** [comment]
Thanks for your answer @chrisb83. I thought it might be a different issue as someone said in the issue #11184 that "In general, the exact two-sided computation is best suited to situations in which one of the sample sizes is at most a few thousand, or the statistic d is "small", as the computation is O(N1 N2 d)."
And in my case, even with a sample size of a few thousand at most it does not give good results.

**Comment by pvanmulbregt** [comment]
@Maxence1607 What version of SciPy are using? `mstats.ks_2samp` and `stats.ks_2samp` now have the same underlying implementaion and return the same result.

**Comment by pvanmulbregt** [comment]
@Maxence1607 I believe that this is no longer an issue with the current SciPy.
```
>>> import numpy as np                                                                                                                                                                             
>>> import scipy.stats.stats, scipy.stats.mstats                                                                                                                                                   
>>> x = list(np.random.normal(10, 1, 3000))                                                                                                                                                        
>>> y = list(np.random.normal(12, 1, 2000))                                                                                                                                                        
>>> scipy.stats.stats.ks_2samp(x, y)                                                                                                                                                               
KstestResult(statistic=0.695, pvalue=0.0)
>>> scipy.stats.mstats.ks_2samp(x, y)                                                                                                                                                              
KstestResult(statistic=0.695, pvalue=0.0)

>>> scipy.version.version                                                                                                                                                                          
'1.6.0.dev0+271d693'
```

**Comment by Maxence1607** [comment]
Hi @pvanmulbregt thank you for your answers. Yes it seems to be a problem only for older versions of SciPy. As I must use the version 1.4.1 in my project I will just use the mode 'asymp' to get the results I want.
Thank you all for your time
