### ISSUE TITLE
BUG: fmin_powell missing squeeze in 1.5.0rc

### ISSUE THREAD

**Issue by josef-pkt** [scipy/scipy#12298]
statsmodels has one test failure with 1.5.0.rc

It's mainly a scalar return check for fmin_powell

```
>               assert_(xopt.shape == () and xopt.size == 1)
E               AssertionError
```
https://travis-ci.org/github/statsmodels/statsmodels/jobs/693651513
https://github.com/statsmodels/statsmodels/issues/6771

based a quick look
The first `if` does not squeeze the fval, while almost all other `if` use squeeze on return

https://github.com/scipy/scipy/pull/12172/files#diff-c1c2c73ad9e5ddef5673e2e95d19020fR2660

(I didn't run any code)

**Comment by andyfaff** [comment]
I'll make a fix today.

**Comment by andyfaff** [comment]
The issue is [here](https://github.com/scipy/scipy/pull/12172/files#diff-c1c2c73ad9e5ddef5673e2e95d19020fL2708).

Whilst I can make the fix (for back compat) I think the original behaviour is a bug.
I would expect the return output from any of the minimizers to always be an array with a non-zero shape:

with f = lambda x: x**2
`x0 = 1 --> res.x = np.array([0.])`
`x0 = np.array([1]) --> res.x = np.array([0.])`

**Comment by h-vetinari** [comment]
This issues (along with all other issues in https://github.com/scipy/scipy/milestone/44) should be moved to the next milestone.

**Comment by tylerjereddy** [comment]
I've moved the milestone on this issue at least. I'm sure we'll get to bumping the others soon-ish.

**Comment by andyfaff** [comment]
I'm not sure it's a bug, but we should definitely have a discussion what's supposed to happen with a single variable.

**Comment by rgommers** [comment]
I'm going to bump this again - no other complaints, so let's not treat it as a clear regression that's a blocker.

**Comment by mdhaber** [comment]
@josef-pkt I agree with @andyfaff that it looks like that test in statsmodels was working around a bug in `fmin_powell`'s original behavior, and that the change in `fmin_powell`'s behavior is really a bug fix. The behavior of the optimizers seem more consistent now, and the issue in statsmodels has been closed, so it seems this can be closed, too. Please re-open if I'm mistaken. Thanks!
