### ISSUE TITLE
Problem of wrong conversion of quaternion to rotation matrix

### ISSUE THREAD

**Issue by rainfall1998** [scipy/scipy#12304]
my code is :
from scipy.spatial.transform import Rotation as R
import numpy as np
def get_r(q):
	r = np.zeros((3,3))
	r[0,0] = 1-2 * q[2] * q[2]-2 * q[3] * q[3]
	r[1,1] = 1-2 * q[1] * q[1]-2 * q[3] * q[3]
	r[2,2] = 1-2 * q[1] * q[1]-2 * q[2] * q[2]
	r[0,1] = 2 * q[1] * q[2]-2 * q[0] * q[3]
	r[0,2] = 2 * q[1] * q[3]+2 * q[0] * q[2]
	r[1,0] = 2 * q[1] * q[2]+2 * q[0] * q[3]
	r[1,2] = 2 * q[2] * q[3]-2 * q[0] * q[1]
	r[2,0] = 2 * q[1] * q[3]-2 * q[0] * q[2]
	r[2,1] = 2 * q[2] * q[3]+2 * q[0] * q[1]
	r = np.matrix(r)
	return r
q = np.array([0.1729, -0.00259987, 0.984729, 0.0201838])
R1 = get_r(q)
R2 = (R.from_quat(q)).as_matrix()
print('R1:\n',R1)
print('R2:\n',R2)

and get the result 
R1:
 [[-0.94019718 -0.01209989  0.34041434]
 [ 0.00185922  0.99917171  0.04065018]
 [-0.34062424  0.03885211 -0.93939593]]
R2:
 [[-0.93939639 -0.04065019  0.34041442]
 [ 0.03885212 -0.99917171 -0.0120999 ]
 [ 0.34062432  0.00185922  0.94019765]]

R2 doesn't equal R1, is there someting wrong with  scipy.spatial.transform ?
get_r  function is obtained according to the formula of the quaternion conversion rotation matrix on the Internet.
![image](https://user-images.githubusercontent.com/43332711/83611012-ed2afa80-a5b2-11ea-87a3-b84a73dd3091.png)

**Comment by pmla** [comment]
`from_quat` expects the scalar component of the quaternion to be the last element of the array, rather than the first element as in your formula.
See the docs here:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.from_quat.html#scipy.spatial.transform.Rotation.from_quat
