### ISSUE TITLE
scipy.optimize.minimize does not work with repeated or redundant constraints

### ISSUE THREAD

**Issue by bernamdc** [scipy/scipy#12306]
When defining a list of constraints as an input for the scipy.optimize.minimize (using a default 'SLSQP' method), repeated or redundant constraints will raise messages like "Singular matrix C in LSQ subproblem", and a solution is not achieved, when in fact, these repeated/redundant constraints should just be ignored.

This is very relevant when one has to define multiple inequality and equality constraints, which sometimes partially overlap for some of the constraints.

To replicate the problem: Use a working example of a constrained minimization problem, but now duplicate the list of constraints (two times more constraints, but all of them repeated).

Example where this is useful: Forcing a bivariate polynomial f(x,y) of a certain degree, to be f(0,y)=0 and forcing it's first derivative with respect to x, to be d f(x=1,y) / dx = 0, will provide a large set of equality constraints where a few of them are redundant.

**Comment by andyfaff** [comment]
How is the minimizer method supposed to know that constraints are redundant or repeated?
SLSQP needs to work out the jacobian of the constraint, if the jacobian is singular it's just not going to work. The user needs to do the hard work here.

Alternatively use `differential_evolution` which doesn't need to calculate any form of jacobian.

**Comment by bernamdc** [comment]
The constraints represent a system of equations, and in many cases, a linear one. One possible way is:
[Gaussian elimination](https://en.wikipedia.org/wiki/Gaussian_elimination#:~:text=Gaussian%20elimination%2C%20also%20known%20as,the%20corresponding%20matrix%20of%20coefficients.)

**Comment by mdhaber** [comment]
`linprog` has a few routines for identifying and elimination redundancy. See `_remove_redundancy.py`.

**Comment by bernamdc** [comment]
The function `_remove_redundancy()` inside `_remove_redundancy.py` is exactly what I needed, thank you so much! I am not using non-linear constraints so I don't have an example for that.

**Comment by andyfaff** [comment]
I think @mdhaber came up with a solution for the OP, and it doesn't look like it's going to be solve this problem in the general case, so closing.
