### ISSUE TITLE
scipy.spatial.transform.Rotation does not invert rotations properly

### ISSUE THREAD

**Issue by jtrunnels91** [scipy/scipy#12311]
The scipy.spatial.transform.Rotation inv() method is not implemented properly.  The current implementation reverses the sign of the _real_ quaternion component, while it should reverse the sign of the _imaginary_ quaternion components.  This can be derived by noting the definition of the quaternion: the real part contains the cosine term, which is symmetric about zero, while the imaginary parts contain the sine term.  Also see the Wikipedia article (https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation#Using_quaternion_as_rotations) which specifies the definition of the inverse.

#### Reproducing code example:

```
import numpy as np
from scipy.spatial.transform import Rotation

r1 = Rotation.from_euler('xyz',[0,0,0])
r2 = r1 * r1.inv()
print(r2==r1) # This prints "False", but the rotations should be identical!
```

The definition of the inverse function is currently:
```
def inv(self):
        quat = self._quat.copy()
        quat[:, -1] *= -1
        if self._single:
            quat = quat[0]
        return self.__class__(quat, normalize=False, copy=False)
```
but it should be
```
def inv(self):
        quat = self._quat.copy()
        quat[:, 0:3] *= -1
        if self._single:
            quat = quat[0]
        return self.__class__(quat, normalize=False, copy=False)
```
#### Scipy/Numpy/Python version information:
1.3.1 1.16.5 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

**Comment by pmla** [comment]
This is not a bug. The equality operator on Rotation objects tests whether two objects are the same object, not if they represent the same rotation.
```
>>> from scipy.spatial.transform import Rotation
>>> r1 = Rotation.from_euler('xyz', [0, 0, 0])
>>> r2 = Rotation.from_euler('xyz', [0, 0, 0])
>>> r1 == r2  # These represent the same rotation, but are different `Rotation` objects
False
>>> r3 = r1
>>> r1 == r3  # These are the same objects
True
```

The quaternion sphere S4 is a double covering of SO3. This means that flipping the sign of the real or the imaginary components is equivalent.

**Comment by jtrunnels91** [comment]
Well, the definition of the equality operator notwithstanding, the current implementation of inv() leads to numerical instability.  The following crashes:

```
import numpy as np
from scipy.spatial.transform import Rotation

trialEulerAngles = np.array(
    [
        np.linspace(0,np.pi/4,100),
        np.linspace(0,np.pi/4,100),
        np.linspace(0,-np.pi/4,100)
    ]
).T

r1 = Rotation.from_euler('xyz',[np.pi/4,0,0])

for eulerAngle in trialEulerAngles:
    r2 = Rotation.from_euler('xyz',eulerAngle)
    dr = r2 * r1.inv()
    r1=dr*r1

print(r1.as_quat())  # All four elements are NaN
```

Whereas an implementation of inv() in which the imaginary components' signs are flipped has no such problems:

```
import numpy as np
from scipy.spatial.transform import Rotation

trialEulerAngles = np.array(
    [
        np.linspace(0,np.pi/4,100),
        np.linspace(0,np.pi/4,100),
        np.linspace(0,-np.pi/4,100)
    ]
).T

r1 = Rotation.from_euler('xyz',[0,0,0])

for eulerAngle in trialEulerAngles:
    r2 = Rotation.from_euler('xyz',eulerAngle)
    r1Quat = r1.as_quat()
    r1Quat[0:3] *= -1
    dr = r2 * Rotation.from_quat(r1Quat)

    r1=dr*r1

r1 = Rotation.from_euler('xyz',[np.pi/4,0,0])

for eulerAngle in trialEulerAngles:
    r2 = Rotation.from_euler('xyz',eulerAngle)
    dr = r2 * r1.inv()
    r1=dr*r1
print(np.linalg.norm(r1.as_quat() - r2.as_quat()))  # This quantity is about 1e-15; within limits of numerical precision
```

**Comment by pmla** [comment]
The difference between your implementations of `inv()` is not due to the placement of the signs. Rather, you are calling `Rotation.from_quat`, which normalizes the quaternion. Have a look here:
https://github.com/scipy/scipy/blob/master/scipy/spatial/transform/rotation.py#L477

The pertinent question is whether the multiplication operator should perform normalization (currently it does not, but perhaps it should). If you make a new issue about that we can start a discussion there.

**Comment by jtrunnels91** [comment]
I see, that makes sense.  I still feel that the inverse would be more intuitive if the imaginary parts were sign-reversed rather than the real part; this method is easier to derive (in my mind) from Euler's formula since changing the sign of the rotation angle should result in the sign of the imaginary component being changed.  This implementation also has the side-benefit of more consistent representation between equivalent rotations, e.g.

```
import numpy as np
r0 = Rotation.from_euler('xyz',[0,0,0]) # Zero rotation
r1 = Rotation.from_euler('xyz'[np.pi/4,0,0])

print(r0.as_quat()) # [0, 0, 0, 1]
print((r1 * r1.inv()).as_quat())  # [0, 0, 0, -1]
# These are the same rotations but "different" quaternions
```

But, this may just be a matter of preference.
