### ISSUE TITLE
Include Solar Mass Constant

### ISSUE THREAD

**Issue by Bhavesh012** [scipy/scipy#12321]
I often feel the requirement of solar mass constant in scipy.constant whenever I do Astronomical data analysis. 

It would be really better if we have that constant too. 

The value of Solar Mass is 1.9884099e+30 with an uncertainty of ±0.00007.

**Comment by pizzathief** [comment]
#12331 
documentation build is failing due to this:
ImportError: cannot import name 'signature_from_ast' from partially initialized module 'sphinx.util.inspect' (most likely due to a circular import)

**Comment by sethtroisi** [comment]
Feels like this is a better fit for astropy which it already includes the constant as `astropy.constants.M_sun`

**Comment by Bhavesh012** [comment]
I agree but it's not very efficient to import another library just for one constant.

**Comment by Bhavesh012** [comment]
> Feels like this is a better fit for astropy (see [astropy.constants](https://docs.astropy.org/en/stable/constants/)) which it already includes the constant as `astropy.constants.M_sun`

I agree but it's not very efficient to import another library just for one constant.

**Comment by sethtroisi** [comment]
A different question would be why stop here? Why not add all of the Astropy constants to SciPy?
A metric I've seen used in other Issues is "does this have value outside of a single domain" which I'm not sure this meets. That being said I'm new and not an owner.

**Comment by ewmoore** [comment]
#4943, #7451, #7132, #5404 are past similar discussions.  Since this is already in astropy, we have in past declined to add this.  I think we probably want to stick with that discussion.

**Comment by mdhaber** [comment]
@Bhavesh012 Sometimes I feel the same way, but SciPy does not intend to be a one-stop shop for everything. So I think that in this case, it is more appropriate to import from Astropy. Thanks for the suggestion.
