### ISSUE TITLE
BUG: stats.exponnorm.pdf returns 0 for small K

### ISSUE THREAD

**Issue by DanBenHa** [scipy/scipy#12326]
Related to #10003 and #10023, but return value is 0 instead of nan, hence a new issue.
Seems like the problem comes from when the `scipy.special.erfc` function returns 0 for very high input values.

Also, the assertion value in https://github.com/scipy/scipy/blob/c38df7ba7f7158c6cb935153051ca1aaa8c69223/scipy/stats/tests/test_distributions.py#L1831 should be around 0.003678978 (taken from the brms package, so I'm not exactly sure :P), not 0.

I don't know of an immediate fix, but can have a look at it soon.

#### Reproducing code example:

```
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import exponnorm

x = np.arange(-100,100)
plt.plot(x,exponnorm.pdf(x,K=1/40))
```
gives me this plot
<img width="410" alt="image" src="https://user-images.githubusercontent.com/11663234/84035587-42448300-a99c-11ea-9c85-1fc51fc3e952.png">

With R package 'brms':
```
library(brms)

x = seq(-100,100)
gp <- dexgaussian(x, mu=0, sigma=1, beta=40)
plot(x,gp)
```
<img width="481" alt="image" src="https://user-images.githubusercontent.com/11663234/84035885-b5e69000-a99c-11ea-9156-fa249811b747.png">

#### Scipy/Numpy/Python version information:
1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

**Comment by DanBenHa** [comment]
This quick implementation from https://github.com/paul-buerkner/brms/blob/4018a3ea522606bf76eb3a3de64ff197b71f7870/R/distributions.R#L588 seems to work:
```
 import numpy as np
 from scipy.stats import norm
 
 def exgauss(x, mu, sigma, beta):
     mu = mu-beta
     z = x-mu-np.power(sigma,2)/beta
     logp = -np.log(beta) - (z + np.power(sigma,2) / (2*beta)) / beta + norm.logpdf(z/sigma)
     return np.exp(logp)
```

I'll adapt this to the scipy style with shape parameter and make a PR.

**Comment by pvanmulbregt** [comment]
@DanBenHa The license for https://github.com/paul-buerkner/brms appears to be GPL, which is incompatible with SciPy https://docs.scipy.org/doc/scipy/reference/hacking.html#license-considerations.  Is there another algorithm and/or implementation that addresses your issue?

**Comment by DanBenHa** [comment]
Thanks for alerting me to this. What about pymc3 (Apache 2 licence): https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/continuous.py

**Comment by pvanmulbregt** [comment]
SciPy needs BSD or BSD compatible, which doesn't include Apache.
 From https://docs.scipy.org/doc/scipy/reference/hacking.html#license-considerations:

> _I based my code on existing Matlab/R/… code I found online, is this OK?_
>
> It depends. SciPy is distributed under a BSD license, so if the code that you based your code on is also BSD licensed or has a BSD-compatible license (e.g. MIT, PSF) then it’s OK. Code which is GPL or Apache licensed, has no clear license, requires citation or is free for academic use only can’t be included in SciPy. Therefore if you copied existing code with such a license or made a direct translation to Python of it, your code can’t be included. If you’re unsure, please ask on the scipy-dev mailing list.

**Comment by DanBenHa** [comment]
Just for the record: I realised that I mistaked brms's `beta` parameter as the rate. It seems to be the scale parameter of the exponential, same as in scipy.
The bug report is still valid, though, because the exponnorm with K=1/40 should look very much like a standard normal.

**Comment by WarrenWeckesser** [comment]
I don't think we have to refer to any other implementations to fix this.  Using the standard relationship between `erfc` and the CDF of the normal distribution (e.g. https://en.wikipedia.org/wiki/Error_function#Cumulative_distribution_function), we can express the log of the PDF in terms of the log of the CDF of the normal distribution, and we already have an implementation of that (`_norm_logcdf(x)` in `"_continuous_distns.py"`).  Then we can implement the `_pdf` method as the exponentiation of the `_logpdf` function.  Correct values for unit tests can be computed with `mpmath`.  I'm putting together a PR now.
