### ISSUE TITLE
Query - Fixed form fortran files

### ISSUE THREAD

**Issue by EverLookNeverSee** [scipy/scipy#12325]
Why scipy uses fixed form for its fortran files?
Is it possible to translate them to free form and refactor them with newer fortran versions such as v2018?

**Comment by sturlamolden** [comment]
We do not use any particular form of Fortran, except it should be standard compliant (e.g. no Cray pointers) and compile with ifort and gfortran (and preferably other compilers, but at least those two). It is just that most (all?) Fortran in SciPy is legacy Fortran 66 or 77, and it was written that way. SciPy does not have a ban on Fortran 90, 2003, or whatever. Free-form should be ok as well, as long as it compiles.

**Comment by sturlamolden** [comment]
SciPy used to require that any Fortran should compile with g77. Then we had certain rules on Fortran that are no longer relevant.
