### ISSUE TITLE
scipy differential_evolution with a linear constraint 

### ISSUE THREAD

**Issue by imscw95** [scipy/scipy#12329]
I have tried to apply a linear constraint to an optimization problem using scipy.differential_evolution and keep seeing that the `constraints` argument is not recognized, despite it's description in the documentation. Any idea why this is happening? I have installed the most recent scipy package.

**Comment by mdhaber** [comment]
Please post complete example code and the result of
```
import scipy
scipy.__version__
```

**Comment by andyfaff** [comment]
No further followup, so closing.
