### ISSUE TITLE
scipy.sparse.linalg.eigsh documentation is misleading

### ISSUE THREAD

**Issue by devonwp** [scipy/scipy#12337]
The [documentation for scipy.sparse.linalg.eigsh](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigsh.html) states: 

> Find k eigenvalues and eigenvectors of the real symmetric square matrix or complex hermitian matrix A.

The documentation makes similar statements (suggesting that the function is intended for complex Hermitian matrices as well as real symmetric ones) in the sections for the parameters `A` and `M`. However, as multiple comments within [arpack.py](https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/eigen/arpack/arpack.py) indicate, `eigs` rather than `eigsh` is supposed to be used for complex Hermitian matrices. For instance, at the top of the file:

```
# There is no Hermitian complex/double complex interface.
# To find eigenvalues of a Hermitian matrix you
# must use eigs() and not eigsh()
# It might be desirable to handle the Hermitian case differently
# and, for example, return real eigenvalues.
```

Also, immediately after the docstring for `eigsh`:

```
# complex hermitian matrices should be solved with eigs
```

Note that the documentation does say (under the `which` parameter):

> If A is a complex hermitian matrix, ‘BE’ is invalid.

However, it is unclear to me how exactly this relates to the comments quoted above. One way or another, it seems that it would be helpful for the documentation to be better integrated with these comments instead of indicating that `eigsh` should generically be used for complex Hermitian matrices. (Unless the comments themselves are wrong or misleading?)

**Comment by ewmoore** [comment]
If you pass a complex matrix to `eigsh` it simply turns around and calls `eigs` for you ([code](https://github.com/scipy/scipy/blob/v1.4.1/scipy/sparse/linalg/eigen/arpack/arpack.py#L1554-L1572)).  So in this case it looks like both the comments and the documentation are correct.

**Comment by pv** [comment]
eigsh will simply call eigs if passed complex-valued matrix. Is there
then a problem?

**Comment by devonwp** [comment]
I think it would still be good to point this out in the documentation. The wording I used at the bottom of the original post ("instead of indicating that `eigsh` should generically be used for complex Hermitian matrices") is perhaps the wrong way to put it though: as you point out, it is fine to generically use `eigsh` for complex Hermitian matrices. However, as it stands based on reading the documentation, I would think that `eigsh` uses a specialized routine for complex Hermitian matrices (as it does with symmetric real matrices) when in fact it uses the generic routine in `eigs`. A small note at the top saying something like {"Note that for complex Hermitian matrices, `eigsh` will revert to calling `eigs`."} would be helpful. Do people think a pull request to make this addition would be a good idea?

**Comment by jakevdp** [comment]
As I recall, the reason we originally implemented it this way (calling to eigs from eigsh for complex input) was for symmetry with the behavior of `scipy.linalg.eigsh`, which does accept complex input and returns real values. In this case, `eigsh` calls out to `eigs` and only returns the real part: https://github.com/scipy/scipy/blob/2fa34a4d63b2d1986cac87fdec27f402e9fa4129/scipy/sparse/linalg/eigen/arpack/arpack.py#L1564-L1572

 If there is a way the documentation could be made more clear to address the confusion here, that contribution would be appreciated!

**Comment by jakevdp** [comment]
Maybe the best option is for the comments to be removed. They were originally True, and then `eigsh` was modified to delegate to `eigs` for complex input without modifying the comments: https://github.com/scipy/scipy/commit/f035a6b7e35a4520eab7488a9de1a63d437bb73e
