### ISSUE TITLE
scipy.linalg.blas wrapper signatures are inconsistent

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#12333]
Just an example I noticed, I didn't check whether the problem was more widespread...

The fortran signature of dtrsv (triangular solve) is
```
dtrsv(character uplo, character trans, character diag, integer n,
      double precision a, integer lda, double precision x, integer incx)
```
and it is wrapped in scipy.linalg.blas as
```
dtrsv(a, x, [incx, offx, lower, trans, diag, overwrite_x])
```
Conversely, the fortran signature of dtpsv (triangular solve, packed matrix) is
```
dptsv(character uplo, character trans, character diag, integer n,
      double precision ap, double precision x, integer incx)
```
and it is wrapped in scipy.linalg.blas as
```
dtpsv(n, ap, x, [incx, offx, lower, trans, diag, overwrite_x])
```
Note that `n` is absent from the first wrapper but present in the second.

(I'm not sure if anything can be done while maintaining backcompat (without jumping through too many hoops), though.  At least it may be worth pointing this out in the docs so that the reader doesn't have to wonder whether there's a typo in the docs...)

**Comment by sturlamolden** [comment]
Also not that the Cython APIs in ```scipy.linalg.cython_blas``` and ```scipy.linalg.cython_lapack``` are not inconsistent, but rather mirrors the Fortran libraries directly.

**Comment by ilayn** [comment]
I'll close this as it is a non-issue but please feel free to reopen it.
