### ISSUE TITLE
Rayleigh Distribution clarification on PDF

### ISSUE THREAD

**Issue by digitalgemba** [scipy/scipy#12332]
PDF for Rayleigh distribution is different in scipy.stats.rayleigh and numpy.random.rayleigh.
Any reason why the difference ?

https://numpy.org/doc/1.16/reference/generated/numpy.random.rayleigh.html#numpy-random-rayleigh.html

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rayleigh.html

**Comment by pvanmulbregt** [comment]
NumPy lists the scale explicitly.  
The SciPy formula omits the scale --- the implicit scale is 1. 
 If a scale is provided, SciPy will calculate 

```PDF(x, scale) = PDF(x/scale, 1) / scale```

Which agrees with the NumPy formula.

**Comment by digitalgemba** [comment]
Thanks for fast response. 
In that case how will the below case work ?
> rayleigh.fit(data, loc=0, scale=1) 
> how ppf(q, loc=0, scale=1)

I see difference with scale included.

**Comment by WarrenWeckesser** [comment]
The arguments `loc` and `scale` of the `fit` method are only used as initial guesses for a numerical solver.  They do not impose constraints on the fitting method.  If you want to enforce `loc=0` or `scale=1`, the `fit` parameters to use are `floc` and `fscale`, respectively.  For example,

```
In [75]: x = np.array([1, 2, 9, 1.5, 10, 3.5, 1.6])

In [76]: loc, scale = rayleigh.fit(x, fscale=1)

In [77]: loc
Out[77]: 0.941631931489255

In [78]: scale
Out[78]: 1
```

**Comment by digitalgemba** [comment]
I think I have not explained my concern properly.

`loc,scale=rayleigh.fit(data)`
`rayleigh.ppf(0.99865,loc=loc,scale=scale)`

**With existing code in scipy the result is 11.9323, but the actual value with other software  is 11.92655 for the same data **

`data =(11.885,11.902,11.889,11.886,11.888,11.892,11.901,11.908,11.904,11.889,11.906,11.889,11.889,11.910,11.915,11.889,11.887,11.901,11.902,11.904,11.885,11.886,11.885,11.889,11.886,11.892,11.901,11.902,11.904,11.905,11.889,11.904,11.905,11.910,11.915,11.886,11.880,11.889,11.905,11.887,11.904,11.905,11.910,11.915,11.889,11.888,11.892,11.901,11.908,11.904)`

Any reason why the issue exists ?

**Comment by digitalgemba** [comment]
Unfortunately I only have the result and the input data.

**Comment by digitalgemba** [comment]
Unfortunately I only have the results and data.
Can. you please let me know what method is used to estimate the parameters in `rayleigh.fit()` ? I saw this research paper[http://home.iitk.ac.in/~kundu/two-par-rayleigh-final.pdf] . Could parameter estimation method be one of the reason for discrepancy ?

**Comment by WarrenWeckesser** [comment]
The `fit` method uses a numerical optimization routine from `scipy.optimize` to minimize the negative log-likelihood function of the two parameters `loc` and `scale`.  For some distributions and for some data sets, this method can fail to converge, or it can converge to a value that isn't in fact the MLE, but I don't think that is happening here.

Here's the value that `rayleigh.fit(data)` gives for your data:

```
In [5]: data
Out[5]: 
array([11.885, 11.902, 11.889, 11.886, 11.888, 11.892, 11.901, 11.908,
       11.904, 11.889, 11.906, 11.889, 11.889, 11.91 , 11.915, 11.889,
       11.887, 11.901, 11.902, 11.904, 11.885, 11.886, 11.885, 11.889,
       11.886, 11.892, 11.901, 11.902, 11.904, 11.905, 11.889, 11.904,
       11.905, 11.91 , 11.915, 11.886, 11.88 , 11.889, 11.905, 11.887,
       11.904, 11.905, 11.91 , 11.915, 11.889, 11.888, 11.892, 11.901,
       11.908, 11.904])

In [6]: from scipy.stats import rayleigh

In [7]: rayleigh.fit(data)
Out[7]: (11.878601573338143, 0.014789112521984792)
```
As a sanity check, I wrote a function that finds the MLE for the two parameters using a different numerical procedure.  It uses a bit of algebra to eliminate one the variables, and then uses `brentq` from `scipy.optimize` to find the root of a scalar equation.  Mathematically it should produce the same result, but it is a very different numerical procedure.  It agrees with the above result:
```
In [10]: rayleigh_mle_loc_scale_bb(data)
Out[10]: (11.878590467166754, 0.014802796498156214)
```
Between the two results, the relative error of the `loc` estimate is less than 9.4e-7, and that of the `scale` is less than  9.3e-4.

This result gives almost the same quantile for `0.99865` as the result produced by `rayleigh.fit(data)`:

```
In [11]: loc, scale = rayleigh_mle_loc_scale_bb(data)

In [12]:  rayleigh.ppf(0.99865,loc=loc,scale=scale)
Out[12]: 11.932402860074486
```
So I am suspicious of the result produced by your other software.

**Comment by digitalgemba** [comment]
Ok.
One last question and we can close this.

How do we at Scipy.stats differentiate between folded at Zero and not folded zero  ?

**Comment by digitalgemba** [comment]
Help me understand this
```
data =list(range(1,6,1))
loc,scale=rayleigh.fit(data)
print(loc,scale)

0.31733266798033566 2.1443948595904714
```
σ^2 = (1/2n) ∑(xi ^2) , where I = 1 to n
σ^2 = 55/10
σ = 2.345207879911715

Where am I going wrong ?

**Comment by WarrenWeckesser** [comment]
> Rayleigh is valid for x>=0

The support of the two-parameter Rayleigh distribution is x > `loc`.

The MLE formula for σ² when `loc` is not zero is 

    σ² = (∑(x - loc)²)/(2N)

You can verify this for your data.

Here I check the value of σ² using the result of `rayleigh.fit(data)`
```
In [47]: loc, scale = rayleigh.fit(data)                                        

In [48]: scale**2                                                               
Out[48]: 0.0002187178491879274

In [49]: ((data - loc)**2).sum() / (2*len(data))                                
Out[49]: 0.0002189168315485196
```
That is correct to more than three digits.

In my version, I used that formula for σ² explicitly, so it matches the expected value almost perfectly:

```
In [50]: loc, scale = rayleigh_mle_loc_scale_bb(data)                           

In [51]: scale**2                                                               
Out[51]: 0.00021912278416582587

In [52]: ((data - loc)**2).sum() / (2*len(data))                                
Out[52]: 0.0002191227841658259
```

**Comment by digitalgemba** [comment]
Perfect.

- At what sigma level is Rayleigh equal to Normal distribution 
- How is loc estimated ?

**Comment by WarrenWeckesser** [comment]
> 
>     * At what sigma level is Rayleigh equal to Normal distribution

If you are asking under what conditions the Rayleigh distribution can be approximated by the normal distribution, I don't know.  Maybe someone else here can help you with that, but that is not the type of question that we normally deal with in github issues.  You might have better luck with this question over at [Cross Validated](https://stats.stackexchange.com/).

> 
>     * How is loc estimated ?

Both `loc` and `scale` are estimated as part of the minimization of the negative log-likelihood function that I mentioned above.  The code for `fit` is here:

https://github.com/scipy/scipy/blob/8d5430f5928bd5d921ba1792d32daca6e88243f4/scipy/stats/_distn_infrastructure.py#L2198

Don't expect that to be easy reading.  There are a few layers of wrappers for handling argument processing and for handling arguments that fix certain parameters.

In case you're curious: the implementation of the negative log-likelihood function (i.e. the function that is being minimized by the `fit` method) is this one-liner: https://github.com/scipy/scipy/blob/8d5430f5928bd5d921ba1792d32daca6e88243f4/scipy/stats/_distn_infrastructure.py#L2082

**Comment by digitalgemba** [comment]
Thank you  👍

**Comment by digitalgemba** [comment]
@WarrenWeckesser  Can you explain this discrepancy in parameter estimation ?

Outcome of Minitab 19.2020.1.0

Distribution | Location    | Shape |    Scale        | Threshold
 lognormal   |  2.967500 |             |   0.00043    |  

```
lognorm.fit(data)
2.3287503487818055, 19.43599032364755, 0.002464614273454068
```

`data = (19.439,19.438,19.445, 19.448, 19.467, 19.437, 19.439, 19.442, 19.455, 19.458, 19.439 19.441,19.437, 19.436, 19.438, 19.445, 19.441, 19.439, 19.437, 19.436, 19.455, 19.458, 19.439, 19.441, 19.437, 19.439, 19.441, 19.436, 19.438, 19.445, 19.465, 19.436, 19.438, 19.445, 19.458, 19.439, 19.441, 19.44, 19.442, 19.439, 19.436, 19.438, 19.445, 19.465, 19.436, 19.45, 19.445, 19.439, 19.441, 19.439]`

**Comment by WarrenWeckesser** [comment]
I'm not familiar with Minitab.  Please explain the discrepancy.

**Comment by WarrenWeckesser** [comment]
> lognormal | 2.967500 |   | 0.00043 |

Taking another look, I guess these are the result of fitting a log-normal distribution to the data using Minitab.  Apparently Minitab parametrizes the log-normal distribution using the mean and standard deviation of the underlying normal distribution.  If you apply `scipy.stats.norm.fit` to the log of your data, you get (almost) the same values:

```
In [7]: data
Out[7]: 
array([19.439, 19.438, 19.445, 19.448, 19.467, 19.437, 19.439, 19.442,
       19.455, 19.458, 19.439, 19.441, 19.437, 19.436, 19.438, 19.445,
       19.441, 19.439, 19.437, 19.436, 19.455, 19.458, 19.439, 19.441,
       19.437, 19.439, 19.441, 19.436, 19.438, 19.445, 19.465, 19.436,
       19.438, 19.445, 19.458, 19.439, 19.441, 19.44 , 19.442, 19.439,
       19.436, 19.438, 19.445, 19.465, 19.436, 19.45 , 19.445, 19.439,
       19.441, 19.439])

In [8]: from scipy.stats import norm

In [9]: norm.fit(np.log(data))
Out[9]: (2.9675003916152436, 0.0004214541839045522)
```
In SciPy, the log-normal distribution uses a different parametrization.  Also, typically the `loc` parameter of `lognorm` is not used.  If you apply `scipy.stats.lognorm.fit` to your data, with `floc=0`, you get:

```
In [17]: from scipy.stats import lognorm                                        

In [18]: shape, loc, scale = lognorm.fit(data, floc=0)                          

In [19]: shape, scale                                                           
Out[19]: (0.0004214541839045522, 19.443258272836115)
```
Here's the conversion of those parameters to the mean and standard deviation of the underlying normal distribution: 
```
In [20]: mu, sigma = np.log(scale), shape

In [21]: mu, sigma
Out[21]: (2.9675003916152436, 0.0004214541839045522)
```

**Comment by digitalgemba** [comment]
@WarrenWeckesser thanks for your patience 

My issue is not resolved. 
But , it is nothing to do with Scipy . Hence will close this issue.

**Comment by digitalgemba** [comment]
@WarrenWeckesser  No other way to reach you but for this forum.

- Can you help me to understand / share details regarding this. 

```
The MLE formula for σ² when loc is not zero is
σ² = (∑(x - loc)²)/(2N) 

```

```
temp=(rayleigh.rvs(loc=0,scale=1,size=60))
loc,scale=rayleigh.fit(temp)
rayleigh.ppf(.99865,loc=loc,scale=scale)

3.6429665681915706
```

- What would be outcome if I use offset ?
- How would I know the offset and how to use one ?

**Comment by digitalgemba** [comment]
Raised new ticket #12475
