### ISSUE TITLE
sparse.lil_matrix.tocsr() fails silently on matrices with nzn > 2^31-1

### ISSUE THREAD

**Issue by joachim-gassen** [scipy/scipy#12340]
### Issue

Thank you for this great library! Came here to use the sparse matrix functionality for some large-scale simulation work.

Doing so I encountered an issue when converting a large lil_matrix to csr. The matrix has dimensions that are smaller than INT32MAX (2^31-1) but contains more than 2^31-1 non-zero numbers.

The call to tocsr() returns without error but the returned CSR matrix contains no meaningful data. 

#### Reproducing code example

Please note that you need to have a lot of memory (around 40 GB?) and processing time available to run the code below.

```
import scipy as sp
import numpy as np
import sp.sparse as sparse

MAX_INT32 = 2**31-1

# Creates less than MAX_INT32 non-zero values
rows = int(MAX_INT32 / 1e2)
Q = sparse.lil_matrix((rows, 1000))
Q[0:rows,1:101] = 1 
Qcsr = Q.tocsr()

# Works OK, e.q.:
Qcsr[0,0]
# 0.0
Qcsr[0,1]
# 1.0
Qcsr[0,2]
# 1.0
Qcsr[rows-1,100]
# 1.0
Qcsr[rows-1,101]
# 0.0

# Creates more than MAX_INT32 non-zero values
rows = int(MAX_INT32 / 1e2) + 1 
Q = sparse.lil_matrix((rows, 1000))
Q[0:rows,1:101] = 1 
Qcsr = Q.tocsr()

# Returns without error but does not work, e.g.:
Qcsr[0,0]
# -3.954749893618852e-236
Qcsr[0,1]
# 0.0
Qcsr[0,2]
# 0.0
Qcsr[rows-1,100]
# 0.0
Qcsr[rows-1,101]
# 0.0
```

#### Error message

None.

#### Scipy/Numpy/Python version information

```
1.4.1 1.18.4 sys.version.info(major=3, minor=8, micro=3, releaselevel='final', serial=0
```

### Fix/patch

I looked into `scipy/scipy/sparse/lil.py`. The issue seems to be triggered by this part in the code for tocsr():

```
        if M*N <= np.iinfo(np.int32).max:
            # fast path: it is known that 64-bit indexing will not be needed.
            idx_dtype = np.int32
            indptr = np.empty(M + 1, dtype=idx_dtype)
            indptr[0] = 0
            _csparsetools.lil_get_lengths(self.rows, indptr[1:])
            np.cumsum(indptr, out=indptr)
            nnz = indptr[-1]
        else:
            idx_dtype = get_index_dtype(maxval=N)
            lengths = np.empty(M, dtype=idx_dtype)
            _csparsetools.lil_get_lengths(self.rows, lengths)
            nnz = lengths.sum()
            idx_dtype = get_index_dtype(maxval=max(N, nnz))
            indptr = np.empty(M + 1, dtype=idx_dtype)
            indptr[0] = 0
            np.cumsum(lengths, dtype=idx_dtype, out=indptr[1:])
```
In the `else` branch the length array is defined as `int32` given than `N` is smaller than INT32MAX. This triggers lengths.sum() to overflow as this also returns `int32`. I changed the line the `idx_dtype` definition (row number 466) to `idx_dtype = get_index_dtype(maxval=N*M)` and then the adjusted code runs OK locally for me. 

Happy to issue a PR if desired and thanks for letting me know if I missed something (which is likely to be the case as I am not a heavy Python user).

Cheers, Joachim

**Comment by joachim-gassen** [comment]
Hi there and thanks! This helps to clarify things.  I checked various environments (Mac OS, linux) they default to `int64` However, the computer where I ran the actual simulation acts up:

```
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np, sys, platform
>>> platform.architecture()
('64bit', 'WindowsPE')
>>> sys.maxsize.bit_length()
63
>>> lengths = np.full(21474837, 100, dtype=np.int32)
>>> lengths.sum()
-2147483596
```
Weird. The systems looks like a 64 bit system but behaves like a 32 bit system.
So the case will be a special case driven by my local environment but my guess is that `sciy.sparse.tocsr()` should not just silently assume that sum() returns `int64`, right?

**Comment by pv** [comment]
Right, it probably should have `.sum(dtype=np.int64)` instead of
`.sum()`.

**Comment by perimosocordiae** [comment]
I opened a pull request with the fix. Thanks for the report, @joachim-gassen !

**Comment by joachim-gassen** [comment]
Thank you all for dealing with this so quickly. Glad to be helpful.
