### ISSUE TITLE
Create a 2-parameter version of the gamma distribution

### ISSUE THREAD

**Issue by Xodarap** [scipy/scipy#12350]
The gamma distribution is [usually parameterized](https://en.wikipedia.org/wiki/Gamma_distribution) with two parameters, alpha and beta. The scipy implementation only implements `beta = 1`. It would be nice if we could implement different values of beta. Setting `scale = 1/beta` *almost* works, but is off by a factor of beta - see [calculation here](http://mathb.in/42774).

(Alternatively, if there is some way to recapture the 2-parameter version that I'm not seeing it would be good to put that in the documentation.)

**Comment by josef-pkt** [comment]
I'm not sure what you did. Missing a factor is not possible, because then the pdf wouldn't integrate to 1 to be a proper distribution.

The pdf needs to be multiplied by the scale when we do a scale transformation

**Comment by Xodarap** [comment]
Ah, I forgot that the scale parameter is applied twice: `gamma(x, scale) = gamma(x / scale) / scale`. This is where the missing factor comes in.

Would it be helpful if I submitted a PR updating the documentation to explain the relationship between scale and beta? I imagine others would have the same confusion I did.

**Comment by ev-br** [comment]
@Xodarap a PR would be welcome indeed.
