### ISSUE TITLE
np.linalg.svd: strange and wrong result

### ISSUE THREAD

**Issue by IVN-tone** [scipy/scipy#12366]
Hello, everyone!

I started learning the usage of SVD and for the first time tried a very simple example described here:
https://www.youtube.com/watch?v=cOUTpqlX-Xs

I tried the same matrix C = np.array([[5,5],[-1,7]]) as in the example, the result for Vt is not correct (I thought that the reason was in the order of eigenvalues of the matrix Σ, but it was not).

The result of np.linalg.svd for Vt is:  np.array([[ 0.31622777,  0.9486833 ], [ 0.9486833 , -0.31622777]]), but should be: np.array([[ 0.31622777,  -0.9486833 ], [ 0.9486833 , 0.31622777]]).

Does anybody know the reason of such incorrect result? Maybe I missed some issues in np.linalg.svd documentation.

**Comment by ilayn** [comment]
The singular vectors are unique up to sign changes; if v is a valid vector then -v is also a valid vector since both are unitary. Hence signs can come out different in different systems. The result stays correct.

**Comment by matthew-brett** [comment]
It's always worth confirming to yourself:

```
[ins] In [2]: C = np.array([[5,5],[-1,7]])                                                     
[ins] In [3]: U, S, Vt = np.linalg.svd(C)                                                      
[ins] In [4]: U @ np.diag(S) @ Vt                                                              
Out[4]: 
array([[ 5.,  5.],
       [-1.,  7.]])
```
