### ISSUE TITLE
scipy.signal.correlate has an error in the documentation, examples section

### ISSUE THREAD

**Issue by joshx1** [scipy/scipy#12369]
There is an error in the fourth line of the examples section of the documentation for scipy.signal.correlate.

> from scipy import signal
> sig = np.repeat([0., 1., 1., 0., 1., 0., 0., 1.], 128)
> sig_noise = sig + np.random.randn(len(sig))
> corr = signal.correlate(sig_noise, np.ones(128), mode='same') / 128

It should be sig instead of np.ones(128) as the aim is to cross correlate the signal with the noisy signal, not with an array of ones. The plot used in the documentation is also generated with sig instead of np.ones(128), the title for this plot also references cross-correlating with sig not np.ones(128).
> ax_corr.set_title('Cross-correlated with rectangular pulse')

https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.correlate.html

**Comment by larsoner** [comment]
> the aim is to cross correlate the signal with the noisy signal,

For this particular example, I don't think that's actually the aim -- the aim is to "Implement a matched filter using cross-correlation". Here the matched filter is the 128-sample boxcar for each of the original 8 values of interest in the signal (each of which is in the middle of a 128-sample bump). Perhaps it's not totally clear, but I think it's doing something reasonable.

What you propose to do -- computing the cross-correlation of the noisy signal with the original, complete, expanded signal -- could be used to demonstrate a different application of cross-correlation (it should have peak at lag zero, indicating that the signal hasn't shifted in time or anything). PR welcome to improve the docs

**Comment by skresearcher** [comment]
I've added the new example computing the cross-correlation of the noisy signal and the original signal to the documentation.
