### ISSUE TITLE
Memory leakage?

### ISSUE THREAD

**Issue by Albert65** [scipy/scipy#12362]
I have been working past few days with two separate Python applications both using scipy.
The system: OSX Catalina, latest Python 3 packages, the Python itself was installed via Homebrew.
**The problem**: shortly after start, the script aggressively consumes all available memory until crash.
I am not sure if this is a scipy issue, just guessing. There is nothing apparently suspicious neither with script implementation (no huge arrays, etc) nor with Python installation, but the problem is severe.
I would appreciate any suggestion how to investigate memory consumption by numpy/scipy.

**Comment by ilayn** [comment]
Your guess is as good as ours without any details. So we have to have at least some details to diagnose. However, if this script is a loop then I would suggest spin it a few times and see if any variables are growing. Other than that, we need to have a reproducible case.

**Comment by Albert65** [comment]
Maybe you can point out a tool (memory profiler) particularly suitable for numpy/scipy?

**Comment by sturlamolden** [comment]
We have previously used Valgrind for tracking down memory leaks in SciPy. Beware that it can still report leaks due to how Python's memory management works.
