### ISSUE TITLE
interp1d returns incorrect values for step functions

### ISSUE THREAD

**Issue by aizvorski** [scipy/scipy#12373]
For some inputs which have a step change, scipy.interpolate.interp1d returns incorrect values.  

The conditions for this to happen are:
1. The same x value should be present twice in the input with different y values, and
2. Some random property of the input: if it happens for a certain input, it will always happen, but it may not happen for a subset of the input which includes the problem values

The problem appears to be that the order of the y values as used is swapped versus what is in the input; similar to what might happen if the x and y values are sorted using an unstable sort (ie: non-order-preserving for equal inputs).

#### Reproducing code example:

```
import numpy as np
import scipy.interpolate

x, y = (np.array([0.00000000e+00, 8.81834215e-05, 1.23456790e-03, 1.23456790e-03,
        2.29276896e-03, 2.29276896e-03, 2.55731922e-03, 2.55731922e-03,
        2.91005291e-03, 2.91005291e-03, 5.02645503e-03, 5.02645503e-03,
        5.11463845e-03, 5.11463845e-03, 2.40740741e-02, 2.40740741e-02,
        2.54850088e-02, 2.54850088e-02, 2.91005291e-02, 2.91005291e-02,
        3.08641975e-02, 3.08641975e-02, 5.41446208e-02, 5.41446208e-02,
        5.91710758e-02, 5.91710758e-02, 7.87477954e-02, 7.87477954e-02,
        9.88536155e-02, 9.88536155e-02, 1.16666667e-01, 1.16666667e-01,
        1.72927690e-01, 1.72927690e-01, 6.92151675e-01, 6.92151675e-01,
        8.38447972e-01, 8.38447972e-01, 1.00000000e+00]),
        np.array([0.        , 0.        , 0.        , 0.05555556, 0.05555556,
        0.11111111, 0.11111111, 0.16666667, 0.16666667, 0.22222222,
        0.22222222, 0.27777778, 0.27777778, 0.33333333, 0.33333333,
        0.38888889, 0.38888889, 0.44444444, 0.44444444, 0.5       ,
        0.5       , 0.55555556, 0.55555556, 0.61111111, 0.61111111,
        0.66666667, 0.66666667, 0.72222222, 0.72222222, 0.77777778,
        0.77777778, 0.83333333, 0.83333333, 0.88888889, 0.88888889,
        0.94444444, 0.94444444, 1.        , 1.        ]))

f = scipy.interpolate.interp1d(x, y)
print(f(0.90))
# output is 0.9656113509141464, should be 1.0

x2 = np.linspace(0,1,1000)
y2 = f(x2)
plt.plot(x,y)
plt.plot(x2,y2)

```

Note that the x value 8.38447972e-01 is present twice in the input; the interp1d function interpolates between the y value corresponding to the *first* of these x values and the following value, not between the  y value corresponding to the *second* of these x values and the following value.

The same thing happens at x values 7.87477954e-02 and 9.88536155e-02

Using mode='previous' and mode='nearest' shows an equivalent bug on this data.

Truncating the beginning of the input may make the bug disappear (or cause it to show up for different duplicated x values) depending on how much is truncated.

#### Scipy/Numpy/Python version information:

```
1.4.1 1.18.1 sys.version_info(major=3, minor=6, micro=10, releaselevel='final', serial=0)
```

**Comment by jakevdp** [comment]
Thanks for the report. This is one of those situations where the correct output is ambiguous. Numpy makes one choice, and Jax makes another choice (the reason for the choice Jax makes is because it falls out of the implementation of `interp1d` in terms of available lax primitives).

**Comment by aizvorski** [comment]
@jakevdp 

> This is one of those situations where the correct output is ambiguous. 

I don't think it's ambiguous; could you explain?

For example interp1d([0,1,1,2], [0,0,1,1]) should be 0 for x in [0,1) and 1 for x in (1,2]; if there is any ambiguity it is at x=1 only, but there is no reason for it to return any value other than 0 or 1, for any x value other than 1; it's a simple step function.   This is the kind of input that the buggy interp1d interprets as though the arguments passed were interp1d([0,1,1,2], [0,**1,0**,1]) (producing linear ramps, where the input is supposed to be a step function) - but only for specific inputs, and not others.

**Comment by josef-pkt** [comment]
I think interpolation assumes that the x are distinct. How do you interpolate between two values at the same point? It's not a function anymore if y is not unique at each point.
Sorting of x is independent of y.

**Comment by aizvorski** [comment]
@josef-pkt 

> I think interpolation assumes that the x are distinct. How do you interpolate between two values at the same point?

That's true - _at_ the point which is not distinct, the interpolator can do a number of things which would all be reasonable, eg return the first or last value, an average of the values, or even a nan or raise an Exception (as long as it is a defined behavior).  I would think last value or average is what most people would assume.

This bug report isn't about what happens _at_ the duplicate points though.  Passing in an input with duplicate x causes wrong values at _in-between_ points - and they are clearly wrong values (since they are not in between the given y values), and also it is a random effect.

**Comment by aizvorski** [comment]
@jakevdp @josef-pkt 

Additional pointer that this is sort-related:  assume_sorted=True prevents the problem from happening.  Note that the input *is* already sorted, but the results with assume_sorted=False and assume_sorted=True is different.

**Comment by ev-br** [comment]
Cross-ref https://github.com/scipy/scipy/issues/9886

**Comment by aizvorski** [comment]
@ev-br Yep, same issue.  I think it is better to not require unique x values since there are many use cases where duplicates can happen, either on purpose (describing step functions) or accidentally.

I looked at the source for interp1d, and it does almost exactly what I thought.

```
        if not assume_sorted:
            ind = np.argsort(x)
            x = x[ind]
            y = np.take(y, ind, axis=axis)
```

I would propose changing this to np.argsort(x, kind='stable') if the version of numpy has that (>= 1.15.0).  

What do you think about that?

**Comment by josef-pkt** [comment]
> When several x values compare as equal, there is a choice on whether to keep them in the original order (=stable sort), or rearranged (=unstable sort). 

"original order" might not be what's intended either. This assumes that the user presorted the y to get your desired behavior, but then the user could also presort x.

My main worry about these kind of cases is that we add a lot of overhead to handle some "unintended" cases for some users.
i.e. if I want a fast linear interpolation on strictly monotone x values, then I don't need a lot of additional checks and handling of ties in x.

I think having well defined choices for ties would be useful, but it shouldn't punish the currently intended usecase. maybe only piecewise continuous/linear using the min and max value makes sense in the interpolation case.
 
(statsmodels lowess has a similar problem in the smoothing case when there are too many ties. But it's too difficult to fix https://github.com/statsmodels/statsmodels/issues/2449 )

Also, ties with continuous variables might still produce arbitrary behavior and fluctuation if there is some numerical noise in x.

**Comment by ev-br** [comment]
Most interp1d bugs are now features, simply because they've been around \approx forever.

That said, changing to a stable sort might be possible, esp early in the release cycle so that downstream projects have time to adapt.

Lastly, downstream users are almost always better off using specific interpolators instead of `intetp1d`.

**Comment by ev-br** [comment]
@aizvorski care to send a PR with the stable sort?

**Comment by aizvorski** [comment]
@ev-br Sure!  Here you are.  I had to look a bit for which versions of numpy support this; as it is in the current PR we should be good back to numpy=1.3 at least.  Let me know what you think.
