### ISSUE TITLE
interpolate.NearestNDInterpolator.__call__ & LinearNDInterpolator.__call__ documentation

### ISSUE THREAD

**Issue by lhfriedman** [scipy/scipy#12378]
Documentation states that __call__ method takes a single argument xi as an array of points with shape=(..., ndim), but the __call__ method also accepts ndim broadcastible arrays as an argument. This capability stems from code line:

`xi = _ndim_coords_from_arrays(args, ndim=self.points.shape[1])`

This option for evaluation should be included in the documentation.

I suggest the documentation be changed to something like:

> Parameters:
> -------------
>     x1, x2, ... xndim: array_like of float
>          Points where to interpolate data at.
> 
>          x1, x2, ... xndim can be array_like of float with broadcastible shape.
> 
>          or x1 can be array_like of float with shape (..., ndim)

The follwing code demonstrates the two modes of calling working as expected.

```
import numpy as np
import scipy
from scipy.interpolate import NearestNDInterpolator, LinearNDInterpolator

print('numpy version = ', np.version.full_version)
print('scipy version = ', scipy.version.full_version)


for itype in (NearestNDInterpolator, LinearNDInterpolator):
    shape = (4, 5, 6, 7)
    ndims = len(shape)
    x_0 = [np.arange(0, n, dtype=float) for n in shape]
    pts = np.moveaxis(
        np.meshgrid(*x_0, indexing='ij'), 0, -1
        ).reshape(-1, ndims)
    values = np.sum(pts, axis=1)
    interp = itype(pts, values)
    print(40*'-')
    print(itype.__name__)
    print(40*'-')
    print('interp((3, 3, 3, 3)) = ', interp((3, 3, 3, 3)), '\n')
    print('interp(3, 3, 3, 3) = ', interp(3, 3, 3, 3), '\n')
    print(
        'interp([[2], [3]], [[0, 1, 2]], 3, 3) = ',
        interp([[2], [3]], [[0, 1, 2]], 3, 3), '\n'
        )
```
```

numpy version =  1.18.1
scipy version =  1.4.1
----------------------------------------
NearestNDInterpolator
----------------------------------------
interp((3, 3, 3, 3)) =  12.0 

interp(3, 3, 3, 3) =  12.0 

interp([[2], [3]], [[0, 1, 2]], 3, 3) =  [[ 8.  9. 10.]
 [ 9. 10. 11.]] 

----------------------------------------
LinearNDInterpolator
----------------------------------------
interp((3, 3, 3, 3)) =  12.0 

interp(3, 3, 3, 3) =  12.0 

interp([[2], [3]], [[0, 1, 2]], 3, 3) =  [[ 8.  9. 10.]
 [ 9. 10. 11.]] 

```

**Comment by rgommers** [comment]
That behavior is implemented, but it's untested as far as I can tell. Using scalars as input (as in the given example, `interp(3, 3, 3, 3)`) doesn't seem like a good use case, because that adds very little. I can see how it would help if one has a set of 1-D arrays (say `x`, `y`, `z`) for a n-D set of points.

So I think it would be good to update the docs, and regression tests for both interpolators, and add two examples, one for each type of usage.
