### ISSUE TITLE
BUG: Roadmap regression in PR #12334 (cKDTree)

### ISSUE THREAD

**Issue by sturlamolden** [scipy/scipy#12379]
PR #12334 replaces Cython memoryviews with the old syntax for NumPy arrays in several places and therefore introduces a roadmap regression. Commit 3dddff3 should be reverted and PR #12334 should be reworked before 1.6.0.

https://docs.scipy.org/doc/scipy/reference/roadmap-detailed.html

_"Cython’s old syntax for using NumPy arrays should be removed and replaced with Cython memoryviews."_

Ping: @rainwoodman @rgommers @peterbell10

**Comment by rainwoodman** [comment]
Sorry. I took a quick glance at the PR and didn't find any 'old syntax' numpy arrays. 

Cython's old syntax probably refers to
```
np.ndarray[np.float64_t, ndim=2]
```

Cython memoryviews are declared with:
```
np.float64_t [:, ::1]
``` 

We do directly access the `data` pointer of an ndarray object, but that's not using the old Cython ndarray buffer syntax.

**Comment by sturlamolden** [comment]
Ok, then I will just close this issue.

**Comment by peterbell10** [comment]
In #9989, @tylerjereddy also reported a similar 10-20 us performance regression from converting to cython memory views. It might be that creating the memory view itself is expensive and since we don't actually do any array computations in the ckdtree cython code, there's no reason to take that performance hit.

**Comment by sturlamolden** [comment]
> In #9989, @tylerjereddy also reported a similar 10-20 us performance regression from converting to cython memory views. It might be that creating the memory view itself is expensive 

https://github.com/numpy/numpy/pull/16523

**Comment by sturlamolden** [comment]
The only way to reaally find out is to measure:
```Cython
#cython: wraparound = False
#cython: boundscheck = False

cdef extern from *:
    """
    #define NPY_NO_DEPRECATED_API NPY_API_VERSION
    """

cimport numpy as cnp
import numpy as np

cnp.import_array()


def return_first_memview(cnp.ndarray data):
    cdef double[::1] tmp = data
    return data[0]
    
def return_first_numpy(cnp.ndarray data):
    cdef double *tmp = <double*> cnp.PyArray_DATA(data)
    return data[0]
```
And now on my laptop
```
a = np.zeros(100)
return_first_memview(a)
return_first_numpy(a)

%timeit return_first_memview(a)
1.07 µs ± 76.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

%timeit return_first_numpy(a)
167 ns ± 1.96 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```
That is almost a ms (840 ns) extra just to create the Cython memory view.
​

**Comment by sturlamolden** [comment]
Still does not explain (10-20 us though), unless we create many of them or there is something else going on.

**Comment by rainwoodman** [comment]
@sturlamolden 840 ns is about 1us, not 1 ms.

**Comment by sturlamolden** [comment]
Yes, that was a typo, hence my comment that is does not explain 10-20 us slowdown.
