### ISSUE TITLE
SLSQP objective function value increases

### ISSUE THREAD

**Issue by suargi** [scipy/scipy#12390]
Dear all,

I am using slsqp for optimization. I have a callable function for computing the objective function and a callable function to compute the gradient.

The problem is that the value of the objective function increases from one iteration to another. Below, I provide a piece of the output to show my problem:

---
  NIT    FC           OBJFUN            GNORM
.
.
.
    6     6     2.395136E-01     4.981521E-06
FUNCTION EVALUTATION
[0.23951418]
FUNCTION EVALUTATION
[0.23951507]
FUNCTION EVALUTATION
[0.23951597]
FUNCTION EVALUTATION
[0.23951664]
FUNCTION EVALUTATION
[0.2395171]
FUNCTION EVALUTATION
[0.2395174]
FUNCTION EVALUTATION
[0.2395176]
FUNCTION EVALUTATION
[0.23951773]
FUNCTION EVALUTATION
[0.23951781]
FUNCTION EVALUTATION
[0.23951786]
FUNCTION EVALUTATION
[0.23951789]
GRADIENT EVALUTATION
    7    17     2.395179E-01     5.042710E-06
.
.
.
   20   107     2.362838E-01     1.663258E+24
FUNCTION EVALUTATION
[0.241377]
FUNCTION EVALUTATION
[0.24005932]
FUNCTION EVALUTATION
[0.23922256]
FUNCTION EVALUTATION
[0.24793266]
FUNCTION EVALUTATION
[0.24921996]
FUNCTION EVALUTATION
[0.24897627]
FUNCTION EVALUTATION
[0.25178947]
FUNCTION EVALUTATION
[0.27990509]
FUNCTION EVALUTATION
[0.25530838]
FUNCTION EVALUTATION
[0.23398997]
FUNCTION EVALUTATION
[0.23995999]
GRADIENT EVALUTATION
   21   118     2.399600E-01     1.281535E+23
Iteration limit exceeded    (Exit mode 9)
            Current function value: 0.2399599947
            Iterations: 21
            Function evaluations: 118
            Gradient evaluations: 21
---

Please, note that "FUNCTION EVALUTATION" and "GRADIENT EVALUTATION" strings are just part of my code to show the process followed by slsqp. The numerical value between brackets is just the value of the objective function after each call to the function that computes the objective function value.

From my understanding, the value of the objective function should decrease on each iteration. However, on iteration 6 I had a value of 2.395136E-01, and all the calls to the objective function evaluation returned a value greater than 2.395136E-01. So, one would expect that before moving to iteration 7, more calls to the objective function are performed.
It is a major concern, since from my output you can see that the slsqp routine ends with a 'minimum' value larger than the actual minimum (found in FUNCTION EVALUTATION 117: 0.23398997)

Maybe I am missing something?

Unfortunately, I can not provide my code as it depends on other software neither a MWE.

Any help and hit are truly appreciated.

Thank you,
G.

#### Scipy/Numpy/Python version information:
1.4.1 1.16.2 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)

**Comment by pv** [comment]
> From my understanding, the value of the objective function should decrease on each iteration.

When the algorithm does not converge, as in your case where it exits with failure due to iteration limit exceeded, the returned value is not guaranteed to be a minimum or a best approximation to it.

If you have constraints, SLSQP minimizes a penalty function which is not equal to f, and some of the evaluations you see may be in the infeasible region. (If you don't have constraints, then you don't need to use slsqp.)

**Comment by suargi** [comment]
Thank you for the reply.

However, there are still some doubts that i would like to clarify.

In my case, where I do not have any constraint, I do not get the reason why the SLSQP algorithm does not minimize the objective function on each iteration.

> The line search also has a minimum step size, so if the quadratic subproblem gives inaccurate steps (e.g. inaccurate gradient) the steps can increase value of f slightly even without constraints.
I understand that if the problem is not properly defined, the line search algorithm fails. However, the line-search algorithm computes the several values of f. Then, the minimum value should be chosen.

**Comment by pv** [comment]
If the step is to a direction where the function increases, and there is a minimum step length, this can increase the function value. IIUC, this should mainly happen if the gradient information is inaccurate. To understand whether that is actually what happens in your case, you'd need to follow the execution with gdb (or some other debugger) to see what the algorithm is actually doing.
