### ISSUE TITLE
[Doc] search result links don't work

### ISSUE THREAD

**Issue by pitrou** [scipy/scipy#12405]
When using the documentation's search box, one gets 404 errors when clicking the result links. Example at https://docs.scipy.org/doc/scipy/reference/search.html?q=sum_duplicates&check_keywords=yes&area=default

**Comment by pv** [comment]
None of those search results seems to 404 for me. Can you copy a link here that 404s?

**Comment by pitrou** [comment]
For example:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.bsr_matrix.sum_duplicatesundefined?highlight=sum_duplicates#scipy.sparse.bsr_matrix.sum_duplicates

I checked in two different browsers (Chromium, Firefox)

**Comment by pv** [comment]
Ok, I see now after clearing cache. I think the problem is gh-11971

**Comment by pitrou** [comment]
Hmm, I see. Annoying.

**Comment by pv** [comment]
Hotfix applied.

**Comment by pitrou** [comment]
Wow, thank you!
