### ISSUE TITLE
Win32 Azure CI pipeline (almost) always timeouts

### ISSUE THREAD

**Issue by sturlamolden** [scipy/scipy#12409]
I have noticed when submitting PRs (or updating a PR) that the 32-bit Windows Azure pipeline (nearly always) timeout. It runs until about 99 % of the testsuite is completed and then hangs until it is killed due to exceeding 60 minute runtime limit.

**Comment by WarrenWeckesser** [comment]
Yeah, that's happening almost all the time.  In https://github.com/scipy/scipy/pull/12404, the tests finished (all passed); the end of the log is
```
[...]
XFAIL ..\..\stats\tests\test_continuous_basic.py::test_cont_basic[truncnorm-arg95]
  reason: truncnorm
XFAIL ..\..\stats\tests\test_continuous_basic.py::test_cont_basic[truncnorm-arg96]
  reason: truncnorm
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
<string>:14: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --full-trace)
= 35866 passed, 2492 skipped, 128 xfailed, 8 xpassed, 1 warning in 2530.43s (0:42:10) =
Coverage.py warning: Couldn't use data file 'D:\\a\\1\\s\\build\\test\\.coverage.WIN-PN08AGA7H40.2620.053146': database disk image is malformed
Coverage.py warning: Data file 'D:\\a\\1\\s\\build\\test\\.coverage.WIN-PN08AGA7H40.3428.883381' doesn't seem to be a coverage data file: Couldn't use data file 'D:\\a\\1\\s\\build\\test\\.coverage.WIN-PN08AGA7H40.3428.883381': no such table: coverage_schema
Coverage.py warning: Data file 'D:\\a\\1\\s\\build\\test\\.coverage.WIN-PN08AGA7H40.960.573899' doesn't seem to be a coverage data file: Couldn't use data file 'D:\\a\\1\\s\\build\\test\\.coverage.WIN-PN08AGA7H40.960.573899': no such table: coverage_schema
##[error]The operation was canceled.
Finishing: Run SciPy Test Suite
```
I think the test runner hit the process with a keyboard interrupt while it was still printing the `XFAIL` results, so we're right on the edge of the 60 minute limit.

As a quick fix, how about we change the test mode for that test from `full` to `fast`?

**Comment by andyfaff** [comment]
Normally a good idea to turn verbose mode on to figure out which tests take the longest. How long does the build take?

**Comment by WarrenWeckesser** [comment]
In https://github.com/scipy/scipy/pull/12410 I changed the mode from `full` to `fast`.

I won't have time today for a deeper dive into the issue.

**Comment by tylerjereddy** [comment]
I merged that in, you can see some of my notes on the matter in that PR. In short, we  should probably petition for 32-bit mingw to be added to the base image with the Azure team upstream. That can save us 7-8 minutes and the chance of failure on the download stage too.

Even the 64-bit jobs, which as of recently no longer need to download mingw64, are still sometimes scraping really close to the 1 hour mark. When I run on my fork though they often finish much faster--I don't understand the fluctuations..

**Comment by andyfaff** [comment]
Does azure have caching? Can we just save it in a cache so we don't need to download ?

**Comment by andyfaff** [comment]
From inspection of [one of the timeouts](https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=7151&view=logs&j=da2f0622-108b-5827-a4af-f8cb335e1cfa&t=9e634d32-68cc-5895-fa96-80e280e717f3), the installation of mingw32 only takes ~3 minutes. This is only 1 or 2 minutes slower than the 64 bit images that already have mingw installed. The build takes 12.5 minutes, and the test run takes 40 mins. 
We might be able to shave a little bit of time of the build if we can use ccache. Is that preinstalled on the images? If it's not preinstalled we wouldn't save much time at all.

There are a few very slow tests:

```
184.71s call     sparse/linalg/tests/test_matfuncs.py::TestExpM::test_pascal
127.49s call     sparse/linalg/tests/test_expm_multiply.py::TestExpmActionSimple::test_scaled_expm_multiply
71.85s call     sparse/linalg/tests/test_expm_multiply.py::TestExpmActionInterval::test_expm_multiply_interval_matrix
```

From the commit history it looks like @pv and @sethtroisi might have familiarity with those tests + the relevant code. Can these tests be streamlined, their run times are excessive?

**Comment by sethtroisi** [comment]
`test_pascal` is very fast locally, I reduced the amount of work done in the test (see https://github.com/scipy/scipy/pull/11765) but didn't search deeper for what causes it to be slow on cloud machines (I think it's slow in both Colab and Azure)

**Comment by tylerjereddy** [comment]
> From inspection of one of the timeouts, the installation of mingw32 only takes ~3 minutes

7 minutes, 48 seconds in Warren's PR above... it varies and is a source of issues.

**Comment by andyfaff** [comment]
@sethtroisi I ran `test_pascal` in colab, it took 0.2s.

**Comment by andyfaff** [comment]
#12416 caches the mingw package, meaning it won't need to be repeatedly downloaded, but installation of the package will still take a little time.

**Comment by mckib2** [comment]
Looking at a few recent PRs, this appears to fixed?  Most CI Windows builds ~40min

**Comment by mdhaber** [comment]
I haven't noticed this for a while, but there is a new one that usually times out.
