### ISSUE TITLE
test_bisplev_integer_overflow: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Lechnio** [scipy/scipy#12401]
After scipy 1.4.1 instalation I have run the tests with
```
$ python3
>>> import scipy
>>> scipy.test()
```
and the 'test_bisplev_integer_overflow' test exited with `Segmentation fault (core dumped)`. I added few prints that can help me to trace this issue (I do not have dev/debug tools on my target device), and what I figured out, the seg fault occurs on call:
`scipy/interpolate/src/_fitpackmodule.c:198`
```
197: else {
198:         BISPEV(tx, &nx, ty, &ny, c, &kx, &ky, x, &mx, y, &my, z, wrk, &lwrk,
199:                iwrk, &kwrk, &ier);
200: }
```
`BISPEV` is not NULL here and has an address assigned, but I could not debug it deeper, since seg fault occurs just after this call.
I have been testing this for a while and the bisplev function works in other cases (e.g. example codes from [https://docs.scipy.org/doc/scipy-1.4.1/reference/tutorial/interpolate.html](url)), I only noticed problem with input data from the mentioned test.

#### Error message:
When I run `test_bisplev_integer_overflow` line by line in python console:
##### On my intel host:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lechnio/.local/lib/python3.6/site-packages/scipy/interpolate/_fitpack_impl.py", line 1054, in bisplev
    z, ier = _fitpack._bispev(tx, ty, c, kx, ky, x, y, dx, dy)
RuntimeError: Cannot produce output of size 2621440x2621440 (size too large)
```
I expect the same output for my target device.

##### On my target device:
```
>>> interpolate.bisplev(xp, yp, tck)
Segmentation fault (core dumped)
```

#####  Hardware
Architecture:    armv7l
Vendor ID:       ARM
Model name:   Cortex-A9
##### Software
GCC:               9.2.0
Python:            3.7.7
Pybind11:        2.5.0
Scipy:              1.4.1
Numpy:           1.15.4

**Comment by rgommers** [comment]
This was continued in gh-12471, so closing this issue.
