### ISSUE TITLE
scipy.stats.spearmanr mishandles nan variables with "propogate"

### ISSUE THREAD

**Issue by urimerhav** [scipy/scipy#12411]
`scipy.stats.speramnr` tries to see which variables have a nan value and nan-out their results in the output matrix. This is seen in [line 4215](https://github.com/scipy/scipy/blob/ac49c61d92fc11719b4a6a1ad09145ee607dd76f/scipy/stats/stats.py#L4215)

`variable_has_nan = np.isnan(a).sum(axis=axisout)`

 Unfortunately right now it accidentally applies a SUM where it should be applying ANY. As a result, the indexing vector isn't boolean as expected, but instead an integer based off of the number of nan entries. 

So let's say variable 2 has 3 nan entries, the result will be that variable *3* gets replaced with a nan, and not 2. 

Proposed fix:

`variable_has_nan = np.isnan(a).sum(axis=axisout)` -> `variable_has_nan = np.isnan(a).any(axis=axisout)`

**Comment by mdhaber** [comment]
Small working example:
```
import numpy as np
from scipy.stats import spearmanr

np.random.seed(1234321)
x2n = np.random.randn(3, 10)
x2n[1, 0] = np.nan
corr, pvalue = spearmanr(x2n, axis=1, nan_policy="propagate")
print(corr)
```
prints
```
[[nan nan nan]
 [nan nan nan]
 [nan nan  1.]]
```

With the proposed fix:
```
[[1.                nan 0.16363636]
 [       nan        nan        nan]
 [0.16363636        nan 1.        ]]
```
Thanks @urimerhav . I'll fix it.

**Comment by mdhaber** [comment]
This is indeed fixed in `spearmanr` and the proposed `spearmanrho` of gh-23851:
```python3
import numpy as np
from scipy import stats
rng = np.random.default_rng()
x = rng.standard_normal((3, 10))
x[1, 0] = np.nan
ref = stats.spearmanr(x, axis=1, nan_policy="propagate")
ref.statistic
# array([[ 1.        ,         nan, -0.27272727],
#        [        nan,         nan,         nan],
#        [-0.27272727,         nan,  1.        ]])

res = stats.spearmanrho(x[np.newaxis, :], x[:, np.newaxis], axis=-1)
np.testing.assert_allclose(res.statistic, ref.statistic)
```
