### ISSUE TITLE
scipy.stats.gengamma: issue with stats for array case

### ISSUE THREAD

**Issue by berberto** [scipy/scipy#12426]
I'm trying to define an array of variables all distributed with a generalized Gamma, by means of `gengamma`, and by passing array-like with parameters.

```
import scipy.stats as st
import numpy as np
n=10
alphas = 3*np.ones(n) #np.arange(1,n+1)
cs = 2*np.ones(n)
lambdas = np.arange(1,n+1)
distr = st.gengamma(a=alphas, c=cs, scale=lambdas)

mean, var = distr.stats(moments='mv')
print(mean,var)
```

I get the following error when I ask for the stats:
```
Traceback (most recent call last):
  File "test_distr_fit.py", line 9, in <module>
    mean, var = distr.stats(moments='mv')
  File "[...]/.local/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py", line 474, in stats
    return self.dist.stats(*self.args, **kwds)
  File "[...]/.local/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py", line 1060, in stats
    if np.isinf(mu):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

The problem is when calculating the variance. Line 1060 referred to is part of the calculation of the variance within `stats` method of the `rv_generic` class.
I believe the solution would be to add an extra check to discriminate scalar vs array-like rv.

The version of SciPy used is below:
```
1.3.0 1.17.2 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

**Comment by sethtroisi** [comment]
I might be misunderstanding but if you want to generate random values from a bunch of different generalized Gamma distributions
you should be calling `.rvs`

```
import scipy.stats as st
import numpy as np
n=10
alphas = 3*np.ones(n) #np.arange(1,n+1)
cs = 2*np.ones(n)
lambdas = np.arange(1,n+1)
values = st.gengamma.rvs(a=alphas, c=cs, scale=lambdas, size=[1,n]) # 1 random value per distribution
```

If you want to n different distributions 
```
n=10
alphas = 3*np.ones(n) #np.arange(1,n+1)
cs = 2*np.ones(n)
lambdas = np.arange(1,n+1)
values = [st.gengamma(a=a, c=c, scale=l) for a,c,l in zip(alphas, cs, lambdas)]
print([value.stats(moments='mv') for value in values])
```
```
[(array(1.66167549), array(0.23883458)), (array(3.32335097), array(0.95533833)), (array(4.98502646), array(2.14951124)), (array(6.64670194), array(3.82135331)), (array(8.30837743), array(5.97086455)), (array(9.97005291), array(8.59804495)), (array(11.6317284), array(11.70289451)), (array(13.29340388), array(15.28541324)), (array(14.95507937), array(19.34560113)), (array(16.61675485), array(23.88345818))]

```

**Comment by berberto** [comment]
Hi @sethtroisi, that is true, there are workarounds to generate samples or statistics. The problem is that I have a code that requires a frozen distribution object defined as in the original post, i.e. initialized with arrays of parameters as arguments, one for each parameter. This works with several distributions that I tried (`lognorm`, `gamma`, `uniform` and others), but with `gengamma` doesn't work that way.

**Comment by sethtroisi** [comment]
I just tested and this code works for Scipy 1.6.0. I suggest updating as 1.3.0 is > 1 year old.

**Comment by sethtroisi** [comment]
Closing this bug as code works at HEAD and workaround exists for older versions.

Feel free to reopen if updating doesn't fix the problem.
