### ISSUE TITLE
 _csparsetools.lil_flatten_to_array(self.rows, indices) fails if array is numpy

### ISSUE THREAD

**Issue by jgostick** [scipy/scipy#12423]
My issue is about:  lil arrays are not functioning correctly.  It seems like the change listed in the changelog for 1.5 regarding  "scipy.sparse.lil.tocsr is faster"  may have broken something.  Basically, in 1.4 the lil array could be an nd-array, but in 1.5 nd-arrays are no longer accepted by this function.

#### Reproducing code example:

I'm not able to install scipy 1.5 on my local machine since it's not available on conda yet, however my unit testing on github does have 1.5 (as of yesterday afternoon) and is now failing.   When I run the following code on my local machine (scipy 1.4) it works, but I "suspect" that it will fail on 1.5.  I'm sorry that I can't do better than this.  

```
lil = sp.sparse.lil_matrix((100, 100), dtype=int)
sp.sparse.triu(lil)
```

#### Error message:
Here the output of my unit tests over on [github](https://github.com/PMEAL/OpenPNM/pull/1539/checks?check_run_id=801805875)

```
openpnm/io/iMorph.py:155: in load
    conns = sp.sparse.triu(lil, k=1, format="coo")
/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/scipy/sparse/extract.py:160: in triu
    A = coo_matrix(A, copy=False)
/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/scipy/sparse/coo.py:170: in __init__
    coo = arg1.tocoo()
/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/scipy/sparse/base.py:906: in tocoo
    return self.tocsr(copy=False).tocoo(copy=copy)
/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/scipy/sparse/lil.py:477: in tocsr
    _csparsetools.lil_flatten_to_array(self.rows, indices)
_csparsetools.pyx:135: in scipy.sparse._csparsetools.lil_flatten_to_array
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   TypeError: Expected list, got numpy.ndarray

_csparsetools.pyx:192: TypeError
```

#### Scipy/Numpy/Python version information:
As I mention above, my local machine has 1.4, but the testing servers are now using 1.5.  Sorry I can't do better than this.

**Comment by pv** [comment]
Works for me:
```
>>> import scipy, scipy.sparse
>>> lil = scipy.sparse.lil_matrix((100, 100), dtype=int)
>>> scipy.sparse.triu(lil)
<100x100 sparse matrix of type '<class 'numpy.int64'>'
	with 0 stored elements in COOrdinate format>
>>> scipy.__version__
'1.5.0'
```

**Comment by pv** [comment]
Looking at openpnm code, it is indeed assigning numpy arrays to the lil internal structures. I think that this worked previously is an accident, and not something that should be relied on to work. (i.e. other lil methods won't work with such matrices even on 1.4.1)

**Comment by jgostick** [comment]
Thanks for looking into this so quickly!  I will fix our code then...didn't realize we were abusing the lil format.
