### ISSUE TITLE
Request for Python wrapper for LAPACK's ?pptrf (Cholesky factorization in packed format)

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#12431]
**Is your feature request related to a problem? Please describe.**

scipy.linalg.lapack already has wrappers for ?tpsv (triangular solve in packed format).  ?pptrf (Cholesky factorization in packed format) seems to be a common enough function that can be used to generate the matrix passed to ?tpsv, but it is not wrapped at the Python level.

**Describe the solution you'd like**

Add a wrapper for ?pptrf.

**Describe alternatives you've considered**

Manually converting between unpacked and packed formats, but this is not exactly fast.

**Comment by zerothi** [comment]
@anntzer consider adding items for all wrappers you want?

- [ ] `?pptrf`
- [ ] `?ZZZZ`
etc. in that way one can have more in one.

**Comment by anntzer** [comment]
(Right now that's the only one I need, but I will add more as needed :))

**Comment by ilayn** [comment]
PR added. Actually it would be better if we go one by one for each wrapper for maintaining and bookkeeping

**Comment by anntzer** [comment]
thanks for the quick action!
