### ISSUE TITLE
constrained SLSQP minimization fails with ub=lb bounds with previous solution as guess

### ISSUE THREAD

**Issue by gamask** [scipy/scipy#12433]
We are minimizing function f subject to one ineq constraint: sum(x) >= 40.
Each element of x is bound to 0 <= x <= 20.

We also provide an analytical jacobian of f. Without this we crash every time when calculating res_B, with this message:
/usr/local/lib/python3.7/site-packages/scipy/optimize/_numdiff.py:519: RuntimeWarning: invalid value encountered in true_divide
That's a separate issue.

First we obtain a solution res_A.
We print True/False for whether each element of x is within bounds (they always are).
Then we print True/False for whether the value of the constraint function is >= 0 (it isn't always).
Then we print the value of the constraint function at res_A.x.

Then we try to solve the same function again, using the solution res_A as guess and also as both lower and upper bounds.
If the constraint function at res_A.x was positive, this always succeeds, and produces the same solution.
If it was negative, it can succeed or it can fail. That's the issue.

When the constraint function is negative, it's always tiny, on the order of 1e-12.
Passing relatively huge tol values (like 1e-2) makes no difference. Calculating res_B can still fail.

Try seed=159321059281821 for a failure when constraint function is negative.
Try seed=159321061754582 for success when constraint function is negative.

```python
from datetime import datetime
import numpy
import random
import scipy.optimize
import sys


seed = int(datetime.utcnow().timestamp() * 1e5)
#seed = 123
random.seed(seed)
print ('seed %d' % seed)
print ()

# ---------------------------------------------

def f (x):
    return x[0]**3 + x[1]**2 + x[2]*x[3]

def f_jac (x):
    return numpy.asarray([
        3*x[0]**2,
        2*x[1],
        x[3],
        x[2]
    ])


# sum(x) >= 40
constraints = [{
    'type'  : 'ineq',
    'fun'   : lambda x : x[0] + x[1] + x[2] + x[3] - 40
}]

bounds = [
    (0, 20),
    (0, 20),
    (0, 20),
    (0, 20),
]

# ---------------------------------------------

res_A = scipy.optimize.minimize (
    f,
    jac         = f_jac,
    x0          = [random.random() * 20 for i in range(4)],
    method      = 'SLSQP',
    bounds      = bounds,
    constraints = constraints,
)

if res_A.success:
    for i,x in enumerate(res_A.x):
        print ('(0 <= x[%d] <= 20) = %s' % (i, 0 <= x and x <= 20))
    print ('(x[0] + x[1] + x[2] + x[3] - 40 >= 0) = %s' % (res_A.x[0] + res_A.x[1] + res_A.x[2] + res_A.x[3] - 40 >= 0))
    print ('constraint: %30.15f' % (constraints[0]['fun'](res_A.x)))
else:
    print ('fail with status %d' % res_A.status)
    sys.exit()

print ()

# ---------------------------------------------

bounds = [
    (res_A.x[0], res_A.x[0]),
    (res_A.x[1], res_A.x[1]),
    (res_A.x[2], res_A.x[2]),
    (res_A.x[3], res_A.x[3]),
]

res_B = scipy.optimize.minimize (
    f,
    jac         = f_jac,
    x0          = res_A.x,
    method      = 'SLSQP',
    bounds      = bounds,
    constraints = constraints,
)

if res_B.success:
    for i,x in enumerate(res_B.x):
        print ('(0 <= x[%d] <= 20) = %s' % (i, 0 <= x and x <= 20))
    print ('(x[0] + x[1] + x[2] + x[3] - 40 >= 0) = %s' % (res_B.x[0] + res_B.x[1] + res_B.x[2] + res_B.x[3] - 40 >= 0))
    print ('constraint: %30.15f' % (constraints[0]['fun'](res_B.x)))
    
    print ()
    print ('(res_A.x == res_B.x) = %s' % (res_A.x == res_B.x))
else:
    print ('fail with status %d' % res_B.status)
```

Scipy/Numpy/Python version information:
1.5.0 1.18.1 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)

Below are possibly irrelevant ramblings about why I need this to work.
I have a fairly complicated financial function for which I need to produce human-like solutions. There also up to a hundred or so constraints. The function takes up to a few hundred free variables. 
I constrain all but a few of them (using bounds arg) to 0 <= x <= 0, and solve for the few that are unconstrained.
Then I want to run the solver again, constraining the variables I already solved for to the values I got, while allowing a few more variables to vary. This is the problematic step. It fails very often in situations where I'm 100% certain a solution exists.
One simple approach is to fudge the bounds a bit. Instead of:
 solved_x <= x <= solved_x
do:
(solved_x - some_small_value <= x <= solved_x + some_small_value).
This might be doable but it's very cumbersome, because in many cases x +/- some_small_value might be outside bounds or violate a constraint.
Changing my objective function to only take the variables I'm interested in currently is completely out of the question due to how complicated it is. I also have a bunch of analytical jacobians that would be a nightmare to modify.
I did a brief search through prior issues, and found at least one other person who wanted to do something similar, so I'm not alone in this quest :D

**Comment by pv** [comment]
SLSQP converts bounds to inequality constraints, even if lower and upper bounds are equal in which case I guess the problem becomes ill-posed. I guess it should convert them to equality constraints instead in this case.

Indeed, using equality constraints seems to work better here:
```
eq_constraints = []
for j in [0, 1, 2, 3]:
    eq_constraints += [{
        'type'  : 'eq',
        'fun'   : lambda x, j=j: x[j] - res_A.x[j]   # NB: lambda j=j trick to bind variable by value
    }]
res_B = scipy.optimize.minimize (
    f,
    jac         = f_jac,
    x0          = res_A.x,
    method      = 'SLSQP',
    constraints = constraints + eq_constraints,
)
```

**Comment by gamask** [comment]
Your approach does not work for my actual problem.
The failure only occurs when a previous solution has an ineq constraint with a negative value. I found a way to fudge my constraints a bit on each successive step (when I allow more free variables to vary), and the problem goes away for me. The bounds I left untouched.

**Comment by andyfaff** [comment]
Maybe I'm missing something here, but setting equal bounds for *all* the parameters in the OP's second minimisation is a recipe for disaster, the optimiser can't change any of the parameter set.

Related: #13096 prevents issues with numerical differentiation of jacobians for parameters where lb==ub.
