### ISSUE TITLE
eigvalsh inconsistent eigvals= subset_by_index=

### ISSUE THREAD

**Issue by denis-bz** [scipy/scipy#12441]
A low-priority inconsistency, eigvals= subset_by_index= in linalg/decomp.py eigvalsh --

 """ eigvalsh eigvals= vs. subset_by_index= in scipy 1.5
        doc: eigvals : tuple (lo, hi), optional
                *Deprecated by ``subset_by_index``
        code:
            def eigvalsh( ... eigvals=None, subset_by_index=None ... )
                return eigh( ... subset_by_index=eigvals )  # <-- oops

    a quick fix (corrected 29 june):
            if eigvals is None:
                eigvals = subset_by_index  # an alias, either one works
            return as above          

        and change the doc, why deprecate ?
            eigvals is an alias for subset_by_index
    """
    import platform
    import sys
    import numpy as np
    import scipy
    from scipy.linalg import eigvalsh

    print( "numpy %s  scipy %s  python %s  plaform %s " % (
        np.__version__, scipy.__version__ , sys.version.split()[0], platform.platform() ))

    A = np.diag( np.arange( 10 ))
    e = eigvalsh( A, eigvals=[0, 3] )
    print( "eigvalsh( A, eigvals= ):", e )

    e = eigvalsh( A, subset_by_index=[0, 3] )
    print( "eigvalsh( A, subset_by_index= ):", e )  # all, subset_by_index ignored

Output:

    numpy 1.19.0  scipy 1.5.0  python 3.7.6  plaform Darwin-14.5.0-x86_64-i386-64bit 
    eigvalsh( A, eigvals= ): [0 1 2 3]
    eigvalsh( A, subset_by_index= ): [0 1 2 3 4 5 6 7 8 9]

**Comment by ilayn** [comment]
Sigh... thanks @denis-bz. Apparently I needed more coffee at the time. I'll fix that asap.
