### ISSUE TITLE
DOC: scipy.linalg.eigh

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#12445]
The docs say:

> lower bool, optional
>     Whether the pertinent array data is taken from the lower or upper triangle of a. (Default: lower)

but it is undocumented whether the same parameter **lower** is applied to b.

**Comment by ilayn** [comment]
Thanks @keithbriggs That's a good catch. I'll add to #12442

**Comment by keithbriggs** [comment]
Thanks!

________________________________
