### ISSUE TITLE
Fit methods for discrete distributions in scipy.stats

### ISSUE THREAD

**Issue by HDembinski** [scipy/scipy#12440]
**Is your feature request related to a problem? Please describe.**

Continuous distributions in scipy.stats have a `fit` method, but discrete distributions lack this. This is inconsistent.

**Describe the solution you'd like**

All discrete distributions in scipy.stats should have a `fit` method.

**Comment by WarrenWeckesser** [comment]
@HDembinski, thanks for filing the issue.  We already have an open issue about this at https://github.com/scipy/scipy/issues/11948, so I'm closing this one as a duplicate.
