### ISSUE TITLE
spearmanr with entire NaN columns produces errors

### ISSUE THREAD

**Issue by kristianeschenburg** [scipy/scipy#12458]
I'm trying to apply spearmanr to arrays (n x m), where column K is entirely NaN.  I want to correlate the m columns to generate an (m x m) matrix  Using nan_policy="omit", I expect the Kth column and Kth row to be entirely NaN, but the remaining columns should have float values.  However, I'm producing the error below.

#### Reproducing code example:

```
import numpy as np
from scipy.stats import spearmanr

np.random.seed(5)

x = np.random.rand(5, 10)
x[:, 6] = np.nan

spearmanr(x, nan_policy='omit')
```

#### Error message:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-565-9abf6da6f7e5> in <module>()
----> 1 [x,v] = spearmanr(X, nan_policy='omit')

~/anaconda3/lib/python3.7/site-packages/scipy/stats/stats.py in spearmanr(a, b, axis, nan_policy)
   3845     if a_contains_nan:
   3846         if nan_policy == 'omit':
-> 3847             return mstats_basic.spearmanr(a, axis=axis, nan_policy=nan_policy)
   3848         elif nan_policy == 'propagate':
   3849             if a.ndim == 1 or n_vars <= 2:

~/anaconda3/lib/python3.7/site-packages/scipy/stats/mstats_basic.py in spearmanr(x, y, use_ties, axis, nan_policy)
    520         for var1 in range(n_vars - 1):
    521             for var2 in range(var1+1, n_vars):
--> 522                 result = _spearmanr_2cols(x[:, [var1, var2]])
    523                 rs[var1, var2] = result.correlation
    524                 rs[var2, var1] = result.correlation

~/anaconda3/lib/python3.7/site-packages/scipy/stats/mstats_basic.py in _spearmanr_2cols(x)
    487         dof = n_obs - 2 - int(m.sum(axis=0)[0])
    488         if dof < 0:
--> 489             raise ValueError("The input must have at least 3 entries!")
    490 
    491         # Gets the ranks and rank differences

ValueError: The input must have at least 3 entries!
```

**Comment by rlucas7** [comment]
Closed by PR #12460 merge

**Comment by mdhaber** [comment]
This was mostly fixed in `spearmanr`:
```python3
import numpy as np
from scipy import stats
rng = np.random.default_rng()
x = rng.random((5, 10))
x[:, 6] = np.nan
ref = stats.spearmanr(x, nan_policy='omit')
ref.statistic
# array([[ 1. ,  0.1, -0.5, -0.1,  0.5,  0.5,  nan, -1. ,  0.7, -0.4],
#        [ 0.1,  1. ,  0.1, -0.7, -0.1, -0.1,  nan, -0.1,  0.1,  0.2],
#        [-0.5,  0.1,  1. ,  0.4,  0. ,  0. ,  nan,  0.5, -0.8,  0.1],
#        [-0.1, -0.7,  0.4,  1. ,  0.6,  0.6,  nan,  0.1, -0.6,  0.2],
#        [ 0.5, -0.1,  0. ,  0.6,  1. ,  1. ,  nan, -0.5, -0.2,  0.4],
#        [ 0.5, -0.1,  0. ,  0.6,  1. ,  1. ,  nan, -0.5, -0.2,  0.4],
#        [ nan,  nan,  nan,  nan,  nan,  nan,  1. ,  nan,  nan,  nan],
#        [-1. , -0.1,  0.5,  0.1, -0.5, -0.5,  nan,  1. , -0.7,  0.4],
#        [ 0.7,  0.1, -0.8, -0.6, -0.2, -0.2,  nan, -0.7,  1. , -0.6],
#        [-0.4,  0.2,  0.1,  0.2,  0.4,  0.4,  nan,  0.4, -0.6,  1. ]])
```

But notice the 1. on the diagonal? I don't think that should be there.

With `spearmanrho`, we get the same result but with the NaN in the diagonal.
```python3
res = stats.spearmanrho(x[:, :, np.newaxis], 
                        x[:, np.newaxis, :],
                        nan_policy='omit')
```

**Comment by rlucas7** [comment]
> This was mostly fixed in `spearmanr`:
> 
> import numpy as np
> from scipy import stats
> rng = np.random.default_rng()
> x = rng.random((5, 10))
> x[:, 6] = np.nan
> ref = stats.spearmanr(x, nan_policy='omit')
> ref.statistic
> # array([[ 1. ,  0.1, -0.5, -0.1,  0.5,  0.5,  nan, -1. ,  0.7, -0.4],
> #        [ 0.1,  1. ,  0.1, -0.7, -0.1, -0.1,  nan, -0.1,  0.1,  0.2],
> #        [-0.5,  0.1,  1. ,  0.4,  0. ,  0. ,  nan,  0.5, -0.8,  0.1],
> #        [-0.1, -0.7,  0.4,  1. ,  0.6,  0.6,  nan,  0.1, -0.6,  0.2],
> #        [ 0.5, -0.1,  0. ,  0.6,  1. ,  1. ,  nan, -0.5, -0.2,  0.4],
> #        [ 0.5, -0.1,  0. ,  0.6,  1. ,  1. ,  nan, -0.5, -0.2,  0.4],
> #        [ nan,  nan,  nan,  nan,  nan,  nan,  1. ,  nan,  nan,  nan],
> #        [-1. , -0.1,  0.5,  0.1, -0.5, -0.5,  nan,  1. , -0.7,  0.4],
> #        [ 0.7,  0.1, -0.8, -0.6, -0.2, -0.2,  nan, -0.7,  1. , -0.6],
> #        [-0.4,  0.2,  0.1,  0.2,  0.4,  0.4,  nan,  0.4, -0.6,  1. ]])
> 
> But notice the 1. on the diagonal? I don't think that should be there.
> 
> With `spearmanrho`, we get the same result but with the NaN in the diagonal.
> 
> res = stats.spearmanrho(x[:, :, np.newaxis], 
>                         x[:, np.newaxis, :],
>                         nan_policy='omit')

I agree people (myself included) would expect these to exhibit consistent behavior. It's not obvious to me that the `1.` along the (top-left to bottom-right) diagonal are incorrect though, I'd expect `1.` here because the correlation of a variable with itself is usually expected to be 1. 

Am I missing something @mdhaber ?

**Comment by mdhaber** [comment]
Let's restrict our attention to `nan_policy='omit'`, since that's the case described above. 

The correlation of an empty sample with itself is NaN.
```python3
import numpy as np
from scipy import stats
stats.spearmanr([], [])
# SignificanceResult(statistic=nan, pvalue=nan)
```

 The sample is all NaNs, and the NaNs are omitted.
```python3
stats.spearmanr([np.nan, np.nan], [np.nan, np.nan], nan_policy='omit')
# SignificanceResult(statistic=nan, pvalue=nan)
```

I don't see why it would be any different on the diagonal of an array.

(And there are separate arguments for why we'd get NaNs on the diagonal with `nan_policy='propagate'` - and thankfully we do.)

**Comment by rlucas7** [comment]
Ah I was reading it as all the entries on the diagonal. you are specifically calling out the 
`ref.statistic[6,6]` entry e.g. in the submatrix here:

```
>>> ref.statistic[5:8,5:8]
array([[ 1. ,  nan, -0.3],
       [ nan,  1. ,  nan],
       [-0.3,  nan,  1. ]])
>>> 
```
the center element should be `nan` is the claim, is that understanding correct?

In that case then yeah I'd agree the behavior (to be consistent) would need to be `nan`.
Also, I'd say this is a subtle behavior (important to get correct) and not documented in the `help(stats.spearmanr)` docs AFAICS. It probably makes sense to either add a sentence to describe the behavior or better, an example to illustrate, or some better idea that you may have that I've not thought of yet.

**Comment by rlucas7** [comment]
> In that case then yeah I'd agree the behavior (to be consistent) would need to be `nan`. Also, I'd say this is a subtle behavior (important to get correct) and not documented in the `help(stats.spearmanr)` docs AFAICS. It probably makes sense to either add a sentence to describe the behavior or better, an example to illustrate, or some better idea that you may have that I've not thought of yet.

@mdhaber If you agree with the interpretation I can open a separate issue for this if it's not already covered in what you're currently working towards with the array api work.
