### ISSUE TITLE
Add generalized mean calculation

### ISSUE THREAD

**Issue by candalfigomoro** [scipy/scipy#12456]
SciPy does not currently implement "generalized mean" (also known as power mean, or Hölder mean) calculation: https://en.wikipedia.org/wiki/Generalized_mean

This is a Python implementation I've found: https://github.com/Fontkodo/generalized-mean

Note that harmonic mean, geometric mean, etc. could be implemented as special cases of the generalized mean.

**Comment by ewmoore** [comment]
Can’t this be written trivially in terms of linkage.norm?

**Comment by candalfigomoro** [comment]
> 
> 
> Can’t this be written trivially in terms of linkage.norm?

Hi! How would you write it?

**Comment by josef-pkt** [comment]
for positive values, this looks like just the power norm divided by n

**Comment by candalfigomoro** [comment]
> for positive values, this looks like just the power norm divided by n

https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.norm.html ?

We have to divide by n before `**(1./ord)`

**Comment by candalfigomoro** [comment]
Ok we can just multiply by `(1/n)**(1/ord)`

**Comment by candalfigomoro** [comment]
The problem of this "trivial formula" is that it overflows when ord is zero

**Comment by candalfigomoro** [comment]
This is a possible solution, please note that for values of "p" ("ord") near zero, the Python implementation you can find here https://github.com/Fontkodo/generalized-mean is a bit better because we overflow earlier (we already overflow with p=0.001). I used the EAFP approach, but you could also add checks instead of relying on try..except blocks. 

```
import numpy as np
from scipy.linalg import norm
from scipy.stats import gmean


def powermean(x, p):
    with np.errstate(all="raise"):
        try:
            return norm(x, p) * (1 / len(x)) ** (1 / p)
        except (ZeroDivisionError, FloatingPointError):
            try:
                return gmean(x)
            except FloatingPointError:
                return 0.0
```

**Comment by endolith** [comment]
https://github.com/numpy/numpy/issues/19341
