### ISSUE TITLE
scipy.special.binom giving wrong value

### ISSUE THREAD

**Issue by Lakshmikanth2001** [scipy/scipy#12466]
output for **scipy.special.binom(34,15)** should be **1855967520** but code **output was  "1855967519.9999998"**

as scipy.special.binom should be always integer that error is some time fatal 

please try to fix it

**Comment by rkern** [comment]
`binom()` is by design an approximate floating-point implementation. When the result is being used in further floating point calculations, this is usually desirable. Use `special.comb(n, k, exact=True)` to get exact integer arithmetic for integer inputs.

**Comment by Lakshmikanth2001** [comment]
Thank you sir
