### ISSUE TITLE
WIP: Addition of MLE for stats.invgauss/wald

### ISSUE THREAD

**Issue by swallan** [scipy/scipy#12477]
Part of the #11782 issue.

@mdhaber,

I have been investigating the maximum likelihood estimators given in Chapter 25, Inverse Gaussian (Wald) Distribution, but the results from the MLEs don’t seem to come close to the results of either the [wald](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wald.html#scipy.stats.wald) or [invgauss](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.invgauss.html#scipy.stats.invgauss) distributions in scipy. 

Here is how the PDF is described in the textbook we have been using, on page 120: 
<img width="509" alt="Screen Shot 2020-07-02 at 5 01 53 PM" src="https://user-images.githubusercontent.com/44255917/86418668-bb768380-bc85-11ea-81bc-192776c5f1eb.png">

And here are the equations for MLE. 
<img width="495" alt="Screen Shot 2020-07-02 at 5 02 22 PM" src="https://user-images.githubusercontent.com/44255917/86418686-cdf0bd00-bc85-11ea-9729-728e40c779e5.png">

It may be another issue with terminology, since the use of mu to represent the location, as the textbook describes, is implemented as a shape parameter in [`stats.invgauss`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.invgauss.html#scipy.stats.invgauss). However, the mean of a random generate only appears to represent the `mu` used in generation when `loc` and `scale` are the standard `loc=0, scale=1`. 

For example, 

```
from scipy.stats import invgauss
data = invgauss.rvs(mu=3.25, size=10000)
print(data.mean())
```
=> `3.223328...`. Just one example, but it appears that in general it matches.

With other location and scale values it doesn't match. 

```
from scipy.stats import invgauss
data = invgauss.rvs(mu=3.25, scale=2, size=10000)
print(data.mean())
```
=> `6.62447...`. Just one example, but in general they don't match.

The code for the scale is

```scale = len(data) / (np.sum(data**(-1) - mu**(-1)))```

and I played around with both of these equations quite a bit to try to get them to match up with / or be better than the default fit method, but other than the relation I described above, I'm not sure that these will work for these distributions. It may be possible to use the mean to determine the shape parameter in `invgauss` if the person has already fixed `floc=0, scale=1`, but that seems like a very niche usage. 

What are your thoughts?

**Comment by mdhaber** [comment]
I agree that there is not an obvious direct way to convert between $\lambda, \mu$ from the textbook and `mu`, `loc`, `scale` of SciPy in general, and it's not just because SciPy adds `loc`, but also because `scale` $\neq \lambda$. Could you write out SciPy's full formula for the PDF by making the substitution mentioned in the SciPy documentation:

> Specifically, invgauss.pdf(x, mu, loc, scale) is identically equivalent to invgauss.pdf(y, mu) / scale with y = (x - loc) / scale.

And put it side by side with the book's formula for the PDF so we can more easily compare?

**Comment by swallan** [comment]
scipy's Invgauss after applying 

> `invgauss.pdf(x, mu, loc, scale)` is identically equivalent to `invgauss.pdf(y, mu) / scale with y = (x - loc) / scale.`



![image](https://user-images.githubusercontent.com/44255917/86721472-de34cf00-bfda-11ea-92ed-f3e73bd253d1.png)


And then SciPy's wald pdf after the same:

> `wald.pdf(x, loc, scale)` is identically equivalent to `wald.pdf(y) / scale with y = (x - loc) / scale`.

![image](https://user-images.githubusercontent.com/44255917/86713694-2fd95b80-bfd3-11ea-9b57-79a0f9382850.png)


All in comparison to the PDF found in the textbook:
<img width="297" alt="Screen Shot 2020-07-06 at 9 33 27 PM" src="https://user-images.githubusercontent.com/44255917/86710966-55b13100-bfd0-11ea-858b-5791b546c0d6.png">

or, rewriting to be more similar style as scipy: 
![image](https://user-images.githubusercontent.com/44255917/86719947-67e39d00-bfd9-11ea-9531-e2776dbafd1d.png)


So, in all honesty, I don't see a way to refactor that to match wald or invgauss. Should I 'call it' trying to apply MLEs for this one?

**Comment by mdhaber** [comment]
I think if you go a bit further, you'll find with `loc=1` that they are equivalent with 
![image](https://user-images.githubusercontent.com/6570539/86787115-9a14ef00-c019-11ea-8d0c-c47afcbb2fe6.png)

**Comment by WarrenWeckesser** [comment]
@mdhaber, great, that conversion between the SciPy parameters (when `loc` is 0) and the text's parameters checks out, so we can use those MLE formulas when `floc` is given.

By the way (maybe you are already aware of this, and just use `floc=0` as shorthand): we don't have to restrict this to just `0` for `floc`.  For any constant `c`, if the user gives `floc=c`, we can apply the analytical formulas to `x - c`.  We just have to first check that each value in `x` is greater than `c`, and if not, raise an exception.

**Comment by mdhaber** [comment]
> By the way

I was having thoughts along those lines but not fully fleshed out. Thanks for clarifying.

**Comment by swallan** [comment]
@mdhaber @WarrenWeckesser 

Thanks for the pointers! I really appreciate it. I’ll create a PR for this soon.
