### ISSUE TITLE
Submodules not found on global import // AttributeError: module 'scipy' has no attribute 'interpolate'

### ISSUE THREAD

**Issue by from-nowhere** [scipy/scipy#12479]
Hi,

I am unable to access the module `scipy.interpolate` when doing a basic `import scipy`.

This is no big deal in the end, but it has me pulling my hair as to why this could be.

#### Reproducing code example:

Begin with a plain venv/conda environment

```
conda create -n mwe scipy
conda activate mwe
python
```

Then the following fails:

```
import scipy
scipy.interpolate  # raises AttributeError: module 'scipy' has no attribute 'interpolate'
```

However, directly importing the module works:
```
import scipy.interpolate
scipy.interpolate  # returns "<module 'scipy.interpolate' from 'c:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\scipy\\interpolate\\__init__.py'>"
```
Also, the problem is not specific to `scipy.interpolate` -- the same problem exists for e.g. `scipy.sparse`.

On the other hand, `scipy.interpolate` allows access to other modules:

```
import scipy.interpolate
scipy.sparse  # returns "<module 'scipy.sparse' from 'c:\\ProgramData\\Anaconda3\\envs\\test\\lib\\site-packages\\scipy\\sparse\\__init__.py'>"
```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'scipy' has no attribute 'interpolate'
```

#### Scipy/Numpy/Python version information:

I am running Anaconda python on Win10.

```
1.5.0 1.18.5 sys.version_info(major=3, minor=8, micro=3, releaselevel='final', serial=0)
```

This happens in other python versions as well and also when I install scipy globally using `pip install scipy`

I do not know if other scipy versions are affected.

Many thanks in advance!

**Comment by pv** [comment]
It is intentional, sub-packages need to be imported separately, see:
https://docs.scipy.org/doc/scipy/reference/tutorial/general.html

**Comment by from-nowhere** [comment]
D'oh, thanks -.-
