### ISSUE TITLE
.rvs(size) method of Scipy stats fails when size is 2 dimensional

### ISSUE THREAD

**Issue by Rish001** [scipy/scipy#12482]
**Description**: On invoking `.rvs(size)` method where size is a 2 dimensional tuple like (500,10), the individual instantiations of the resultant matrix of random variables depict strange correlation instead of being random.

#### Reproducing code example:

```
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
x = np.arange(0,10)

size = (500,10)
rv = stats.norm(0.0,1.0)
fig, (left, right) = plt.subplots(ncols=2, figsize=(10,5))

data = rv.rvs(size).cumsum(axis = 0)


data_collated = np.empty(size)
for i in range(size[0]):
  data_collated[i] = rv.rvs((size[1],)).cumsum(axis = 0)

for i in np.random.randint(0, 500, size=40):
  left.plot(x,data_collated[i,:])
  left.set_title("Expected")
  right.plot(x,data[i,:])
  right.set_title("Actual")
```

#### outcome:

![issue1](https://user-images.githubusercontent.com/21169674/86506026-e4fbf000-bde8-11ea-9393-50c7572acbb1.png)

**Comment by ev-br** [comment]
Draws with `size=(a, b)` and `size=a*b` seems to be equivalent, as expected.

```
In [3]: from scipy.stats import norm                                            

In [4]: r1 = norm.rvs(size=10*50, random_state=1234)                            

In [5]: r2 = norm.rvs(size=(10,50), random_state=1234) 

In [6]: (r2.ravel() == r1).all()                                                
Out[6]: True
```

**Comment by WarrenWeckesser** [comment]
The calculations of `data` and `data_collated` are not the same.  You compute `data` as

    data = rv.rvs(size).cumsum(axis = 0)

which performs the cumulative sum along axis 0 of the 2-d array. That is, you have performed the cumulative sum of each column.

To create `data_collated`, you compute it row by row, filling in each row with

    data_collated[i] = rv.rvs((size[1],)).cumsum(axis = 0)

So here you are performing the cumulative sums along the rows.  That is not the same calculation that you did to create `data`.

If you intended to performs the cumulative sum on each row, then `data` should be generated by summing along `axis=1`:

    data = rv.rvs(size).cumsum(axis = 1)

If you make that change, the two plots show the expected collections of random walks of length 10.

**Comment by WarrenWeckesser** [comment]
This issue was inspired by a PyMC3 bug report: https://github.com/pymc-devs/pymc3/issues/3962.

My comment in that issue shows the source of the PyMC3 bug.

I'm closing this issue, as this is not a SciPy bug.
