### ISSUE TITLE
RectBivariateSpline derivative evaluator is slow

### ISSUE THREAD

**Issue by tvkalvas** [scipy/scipy#12480]
The derivative evaluator of RectBivariateSpline interpolator seems to be very much slower than the regular call for the interpolator. I traced this back a bit and to me it seems that the fortran code parder.f seems to be building the spline fit all over again at the time of evaluation. This makes no sense to me as the spline fit coefficients should exist already. Aren't they solved at Spline class initialization?

The example below shows the time difference with a large array. 

```
import time
import numpy as np
from scipy.interpolate import RectBivariateSpline

N = 2000
x = np.linspace(0,1,N)
y = np.linspace(0,1,N)
F = np.random.rand(N,N)
spline = RectBivariateSpline(x,y,F)

t = time.time()
spline([0.5],[0.5],0,0,False)
print('Interpolation t =',time.time()-t)

t = time.time()
spline([0.5],[0.5],1,0,False)
print('Derivative t =',time.time()-t)
```

With this code I am getting 

```
Interpolation t = 5.340576171875e-05
Derivative t = 0.016228675842285156
```

This type of use happens in my case as I am solving an ODE using the partial derivatives of a field map in a rectangular grid.

I can work around this, but I was quite surprised to see the performance and don't understand the reason for it. Maybe this should be documented better if there is a reason for calculating the coefficients.

I am running 1.4.1 1.18.1 sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)

Thanks,
Taneli Kalvas

**Comment by pv** [comment]
pardeu.f appears to do it by precomputing all derivative spline coefficients, which is slow
https://github.com/scipy/scipy/blob/393a19294279e33a6422a96f4bfbbaef17cd008b/scipy/interpolate/fitpack/pardeu.f#L92-L94
Probably could be easily limited to computing only those needed.

**Comment by tueda** [comment]
I think I hit exactly this problem when I tried to interpolate `d f(x, y) / dx` where `f(x, y)` was constructed by `scipy.interpolate.interp2d(..., kind='cubic', ...)` with 100000 x 4000 grid points... I need to repeatedly interpolate only `f(x, y)` and `d f(x, y) / dx`, which can be cached on disk once all the coefficients are pre-computed. Is there any easy way to convert an interpolation object for `f(x, y)` into that for `d f(x, y) / dx`?

**Comment by tueda** [comment]
> Is there any easy way to convert an interpolation object for `f(x, y)` into that for `d f(x, y) / dx`?

For those who hit a problem similar to mine: from `f(x, y)` given on a 2D grid, one may generate `d f(x, y) / dx` on the same grid by [`numpy.gradient`](https://numpy.org/doc/stable/reference/generated/numpy.gradient.html#numpy-gradient), which then can be passed to `scipy.interpolate.interp2d`.

**Comment by ev-br** [comment]
@tvkalvas @tueda I'd be great if you could test-drive gh-16220, which implements a `partial_derivative` method  so that you construct it once and evaluate repeatedly.
