### ISSUE TITLE
reading .wav fails when the file is too big on python 3.6.0

### ISSUE THREAD

**Issue by WyattBlue** [scipy/scipy#12483]
Running this on python 3.6.0:

```python
from scipy.io import wavfile
sampleRate, audioData = wavfile.read("output.wav")
```

gives this error:

```
Traceback (most recent call last):
  File "/Users/wyattblue/test.py", line 34
    sampleRate, audioData = wavfile.read("output.wav")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/io/wavfile.py", line 592, in read
    is_big_endian, mmap)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/io/wavfile.py", line 408, in _read_data_chunk
    data = numpy.frombuffer(fid.read(size), dtype=dtype)
OSError: [Errno 22] Invalid argument
```

output.wav is a 4 hour wavfile. This error doesn't occur when the file is only about 40 minutes long.
This error did not happen when I ran the same code with the same file but on python 3.8.3. I didn't test any other python version.

With some experimentation, I found out that `fid.read(size)` is causing the error but I don't know why.

To get the same file that I have, get ffmpeg and youtube-dl and run this code:

```python
import subprocess

cmd = ["youtube-dl", "-f", "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4",
       "https://www.youtube.com/watch?v=od-6uhIMRDQ", "--output", "video.mp4"]
subprocess.call(cmd)

cmd = ['ffmpeg', '-i', myInput, '-ab', '160k', '-ac', '2', '-ar', 
       '48000', '-vn', f'output.wav', '-nostats', '-loglevel', '0']
subprocess.call(cmd)
```

#### Notes
Both python versions are 64-bit
I am using the latest scipy version.

**Comment by larsoner** [comment]
Can you see if https://github.com/scipy/scipy/pull/12183 fixes it? I think it probably will.

**Comment by WyattBlue** [comment]
@larsoner Your code fixed my problem.
