### ISSUE TITLE
BUG: optimize: incorrect result from approx_fprime

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#12487]
This issue is a simple example of the problem with `approx_fprime` reported by @austinwiltshire in a comment in https://github.com/scipy/scipy/pull/10673.

Define the function `func` as

```
def func(x): 
    return -np.abs(x + 1)
```
The graph is

![Figure_1](https://user-images.githubusercontent.com/321463/86522304-ed284f80-be29-11ea-8c7d-17fac7d72ab5.png)

According to  the [docstring for `approx_fprime`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.approx_fprime.html), 

> the function gradient is determined by the forward finite difference formula:

```
         f(xk[i] + epsilon[i]) - f(xk[i])
f'[i] = ---------------------------------
                    epsilon[i]
```

If the finite differences used by `approx_fprime` are, in fact, forward finite difference as stated and shown in the formula in the docstring, `approx_fprime` shouldn't sample the function to the left of the discontinuity.  So `approx_fprime(-1, func, 1e-8)` should return -1.  In SciPy 1.5.0, we get 1:

```
In [112]: import scipy

In [113]: scipy.__version__
Out[113]: '1.5.0'

In [114]: from scipy.optimize import approx_fprime

In [115]: approx_fprime(-1, func, 1e-8)
Out[115]: array([1.])
```

With SciPy 1.4.1, we get the (approximately) correct value:

```
In [11]: import scipy                                                           

In [12]: scipy.__version__                                                      
Out[12]: '1.4.1'

In [13]: from scipy.optimize import approx_fprime                               
                                                                      
In [14]: approx_fprime(np.array([-1]), func, 1e-8)                              
Out[14]: array([-1.00000001])
```

**Comment by andyfaff** [comment]
Due to this [line](https://github.com/scipy/scipy/blob/master/scipy/optimize/_numdiff.py#L405). It should be as simple as removing that line, and adding some tests

**Comment by andyfaff** [comment]
Also, thank you to @austinwiltshire for picking this up.

**Comment by andyfaff** [comment]
Fix underway

**Comment by WarrenWeckesser** [comment]
Fixed in https://github.com/scipy/scipy/pull/12488.  Thanks @andyfaff!
