### ISSUE TITLE
Convergence criterion

### ISSUE THREAD

**Issue by rosegong-D** [scipy/scipy#12497]
I am using SLSQP method with bounds for design variables and inequlaty constraints. However, I find some error even the algrithm still progress. First, some design variables will over the upper bound of the design domian . Second, during optionzation some results violate the constraints , like i want the stiffness higher but somtimes the results smaller than the value I set. Last, I did not find the information for Convergence criterion, I do not know when it will stop. Can this criterior changed based on my problem？ If so, how can I change that?
Dose anyone have some ideas?
thanks

**Comment by mdhaber** [comment]
Hi @rosegong-D This sort of problem has been posted before (e.g. #10726), but we need complete example code that causes the error in order to investigate.

I searched online for the SLSQP reference mentioned in the [`minimize` documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#rdd2e1855725e-12):
http://degenerateconic.com/wp-content/uploads/2018/03/DFVLR_FB_88_28.pdf
Perhaps that has more information about the convergence criteria.

Based on the [method-specific documentation](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-slsqp.html
), it looks like the only thing you can change about the convergence criterion is `ftol`.

**Comment by rosegong-D** [comment]
> Hi @rosegong-D This sort of problem has been posted before (e.g. #10726), but we need complete example code that causes the error in order to investigate.
> 
> I searched online for the SLSQP reference mentioned in the [`minimize` documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#rdd2e1855725e-12):
> http://degenerateconic.com/wp-content/uploads/2018/03/DFVLR_FB_88_28.pdf
> Perhaps that has more information about the convergence criterion.
> 
> Based on the [method-specific documentation](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-slsqp.html), it looks like the only thing you can change about the convergence criterion is `ftol`.

Thank you for your reply. I find my equation was not accurate first, so I have revised that. But, one constraints still be violated. You can see in the picture.
![constraints2],it should be minimise or equal to the original value. But at first it works well, than it gose to the wrong path. (during this time the objective can keep minimized)(https://user-images.githubusercontent.com/57888860/86900445-b5354b00-c14e-11ea-8ec6-89d306a3fda3.png)
The results shows:
Optimization terminated successfully.    (Exit mode 0)
            Current function value: 144.685653626
            Iterations: 60
            Function evaluations: 696
            Gradient evaluations: 56
I also have a question, it might be quite simple. The function was evaluated 696 times(you can also find that in the constraints picture,). But, the SLSQP results only has 60 iteration. Do you know the different between this two numbers? Can I draw a results based on the SLSQP  iteration but not based on the function evaluation iteration.

**Comment by rosegong-D** [comment]
> Hi @mdhaber

Thank you for your reply. I find my equation was not accurate first, so I have revised that. But, one constraints still be violated. You can see in the picture.
![constraints2],it should be minimise or equal to the original value. But at first it works well, than it gose to the wrong path. (during this time the objective can keep minimized)(https://user-images.githubusercontent.com/57888860/86900445-b5354b00-c14e-11ea-8ec6-89d306a3fda3.png)
The results shows:
Optimization terminated successfully. (Exit mode 0)
Current function value: 144.685653626
Iterations: 60
Function evaluations: 696
Gradient evaluations: 56
I also have a question, it might be quite simple. The function was evaluated 696 times(you can also find that in the constraints picture,). But, the SLSQP results only has 60 iteration. Do you know the different between this two numbers? Can I draw a results based on the SLSQP iteration but not based on the function evaluation iteration.

**Comment by mdhaber** [comment]
> But, the SLSQP results only has 60 iteration. Do you know the different between this two numbers?

SLSQP needs partial derivatives, and if you didn't provide them as separate functions, it will do that using finite differences, which require multiple function evaluations.

For the rest, again, we can't help without complete code that causes the problem.
