### ISSUE TITLE
[Question] Are style-only PRs welcome? (black, pyupgrade, isort, flake8, ...)

### ISSUE THREAD

**Issue by MartinThoma** [scipy/scipy#12505]
This is a group of questions around style-only PRs. So PRs which don't make a functional difference, but make the code easier to read.

## My personal setup

I personally like to use a couple of tools to keep a very consistent codebase:

* [black](https://github.com/psf/black): Code auto-formatter
* [isort](https://github.com/timothycrosley/isort): Sort imports automatically
* flake8: Is used already? ([scipy code](https://github.com/scipy/scipy/blob/master/setup.py#L437))
* mypy: Is used already? (I see a couple of PRs, but I haven't seen this in [.travis.yml](https://github.com/scipy/scipy/blob/master/.travis.yml) nor in [tox.ini](https://github.com/scipy/scipy/blob/master/tox.ini))
* [pyupgrade](https://github.com/asottile/pyupgrade): Helps to transition to a codebase which uses the modern Python syntax (e.g. f-strings)

Flake-8 has many pretty cool plugins:

* [flake8-bugbear](https://pypi.org/project/flake8-bugbear/)
* [flake8-builtins](https://pypi.org/project/flake8-builtins/): I think this might be less suitable for scipy
* [flake8-comprehensions](https://pypi.org/project/flake8-comprehensions/)
* [flake8-string-format](https://pypi.org/project/flake8-string-format/)

And finally [pre-commit](https://pre-commit.com/) as a tool to run a lot of those tiny things before I commit ([example config](https://github.com/MartinThoma/hwrt/blob/master/.pre-commit-config.yaml))

### Code Auto-formatter (black / isort / removal of trailing spaces)

Was the application of a code auto formatter discussed before?

* Reasons not to do it is personal preference, trying not to bloat "git blame" and trying to make it as easy as possible for new contributors.
* People  might fear a mess with existing (and complex) PRs. This should not be a big deal as one can simply apply black to the PR-code as well.
* Reasons to apply black is that new contributors might find it easier to read the code. And no discussions about style.

### Auto-formatter Integration in CI pipeline

Going a step further, one can integrate those auto-formatters in the CI pipeline and thus enforce a certain style type. Is that interesting?

### mypy integration in CI pipeline

There seem to be a lot of type hints missing. If I could find a setting which would not break the existing pipeline but enforce type hints for new PRs, would that be interesting? The idea would be to gradually move to a completely typed codebase.

Is there already an issue which summarizes the typing efforts?

### Flake8

Are non-automatic but still only stylistic changes interesting at all? Should they be done or does that waste valuable time of maintainers?

### Pre-commit: Local dev tools

pre-commit is a local tool which developers can install. If Scipy wants the integration of auto-formatters in the CI pipeline, then it might make sense to provide a `.pre-commit-config.yaml`.

What do you think? (also: It's very likely that this was discussed before. I couldn't find an issue here. Maybe somebody can link one?)

**Comment by rgommers** [comment]
Hi @MartinThoma, this has been discussed many times. The basic answer is: please do not send any style-only PRs. For multiple reasons, from it obscuring git history to code churn and load on maintainers for not enough benefit.

We do run `pycodestyle` and `flake8`. A recent improvement was gh-11423, which allowed being more picky on new PRs while not having to do code-base-wide changes.

Also see the `Note` at http://scipy.github.io/devdocs/hacking.html#maintaining-existing-code

**Comment by rgommers** [comment]
> There seem to be a lot of type hints missing. If I could find a setting which would not break the existing pipeline but enforce type hints for new PRs, would that be interesting?

Yes that may be of interest, could be useful.

**Comment by rgommers** [comment]
> Is there already an issue which summarizes the typing efforts?

Not one issue I think, but type annotation improvement PRs are welcome.

**Comment by person142** [comment]
> If I could find a setting which would not break the existing pipeline but enforce type hints for new PRs, would that be interesting?

The mechanism is "set `disallow_untyped_defs` to `True` globally and then add all currently untyped files to the ratchet".

I wouldn't recommend embarking on this right now. I need to hook up mypy in CI still; currently our setup is a little out of date because of changes in NumPy. This will be fixed soonish; for now we have quite a bit of time before a release so improvements in NumPy are my current priority.
