### ISSUE TITLE
ENH: stats: one-sided p-values for statistical tests

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#12506]
In the [CZI Proposal](https://warrenweckesser.github.io/czi/scipy-2019-czi-proposal-revised.pdf), we wrote:

> **Options for one-sided _p_-values.** Many of the existing tests compute only a two-sided _p_-value.
Where appropriate, an option will be added to these tests for computing one-sided _p_-values.

This is part of our effort to address the [Statistics Enhancements roadmap item](https://docs.scipy.org/doc/scipy/reference/roadmap.html#statistics-enhancements).

[Here](https://docs.scipy.org/doc/scipy/reference/stats.html#statistical-tests) is a list of the existing statistical tests in SciPy. We will follow the example of `kstest` and others: add an `alternative` argument that accepts a string in `{'two-sided', 'less', 'greater'}` to select the desired _p_-value. By adding `alternative` at the end of the parameter list and by assigning an appropriate default value, we will ensure backwards compatibility. Most tests currently return a tuple; we don't need to change that to a Bunch (gh-12323).

For tests that determine _p_-values using the `cdf`/`sf` of a symmetric distribution, the _p_-value will be half of the two-sided _p_-value that is currently returned; for most distributions, this can probably be implemented by removing a factor of `2`. If there are any tests to be modified that have asymmetric distributions, the existing code likely calculates the area in each tail independently and adds them to get a two-sided _p_-value, so we can probably just separate the calculations and return the area in the desired tail.

For symmetric distributions, we can adapt existing tests to check that the one-sided _p_-value is half the two-sided _p_-value. For asymmetric distributions, we can adapt existing tests to check that the one-sided _p_-values sum to the two-sided _p_-value, and we should add a test to check that we aren't mixing up the sides (maybe from an example found online or using numerical output of R/[Wolfram Alpha](https://www.wolframalpha.com/input/?i=t+test+&f1=10&f=TTest.mu0_10&f2=8.3&f=TTest.xbar_8.3&f3=3.9&f=TTest.s_3.9&f4=35&x=9&y=9&f=TTest.n_35&a=*FVarOpt.1-_***TTest.n--.***TTest.df---.*--)). 

@swallan @WarrenWeckesser @DominicChm

**Comment by chrisb83** [comment]
This is a great proposal. In my view, the t-tests have the highest priority, it is very common to test mean >= 0 vs < 0.

Note that quite a few of the tests will just have a single alternative, e.g. `stats.anderson_ksamp, epps_singleton_2samp`

**Comment by mdhaber** [comment]
Thanks @chrisb83. @DominicChm will be posting a summary of his plans soon, and he will have a few questions for a domain expert. Shall he @mention you on those?

**Comment by DominicChm** [comment]
So far, I've compiled a table of SciPy's current tests and their eligibility for the enhancement, which is below. 
I'm not a statistician by any means, so please let me know of any issues and I'll update the table to reflect them.

## Table of Tests
(This will be updated as the enhancements are implemented)

| Function Name                             | Pval Source Distribution     | Asymmetric? | Current Status | Notes                                      |
|-------------------------------------------|------------------------------|-------------|----------------|--------------------------------------------|
| ttest\_1samp                              | t distribution               | N           | WIP            |                                            |
| ttest\_ind                                | t distribution               | N           | WIP            |                                            |
| ttest\_ind\_from\_stats                   | t distribution               | N           | WIP            |                                            |
| ttest\_rel                                | t distribution               | N           | WIP            |                                            |
| ranksums                                  | Normal                       | N           |                |                                            |
| ansari                                    | Normal                       | N           |                |                                            |
| mood                                      | Normal                       | N           |                |                                            |
| skewtest                                  | Normal                       | N           |                |                                            |
| kurtosistest                              | Normal                       | N           |                |                                            |
| **Possibility of Implementation Uncertain\.** |                              |             |                |                                            |
| chisquare                                 | Chi\-square                  | Y           |                |                                            |
| power\_divergence                         | Chi\-square                  | Y           |                |                                            |
| epps\_singleton\_2samp                    | Chi\-square                  | Y           |                |                                            |
| kruskal                                   | Chi\-square                  | Y           |                |                                            |
| friedmanchisquare                         | Chi\-square                  | Y           |                |                                            |
| combine\_pvalues                          | Chi\-square                  | Y           |                |                                            |
| jarque\_bera                              | Chi\-square                  | Y           |                |                                            |
| bartlett                                  | Chi\-square                  | Y           |                |                                            |
| levene                                    | foldnorm            | Y           |                | R doesn't implement an alternative param\. |
| shapiro                                   | ? \(Implemented in Fortran\) | ?           |                |                                            |
| **No P\-Value Returned\.**                    |                              |             |                |                                            |
| tiecorrect                                | N/A                          | N/A         |                |                                            |
| rankdata                                  | N/A                          | N/A         |                |                                            |
| **Already implemented\.**                     |                              |             |                |                                            |
| kstest                                    | Kolmogorov\-Smirnov          | Y \(SF\)    |                |                                            |
| ks\_1samp                                 | Kolmogorov\-Smirnov          | Y \(SF\)    |                |                                            |
| ks\_2samp                                 | Kolmogorov\-Smirnov          | Y \(SF\)    |                |                                            |
| mannwhitneyu                              | Normal                       | Y \(SF\)    |                |                                            |
| wilcoxon                                  | Normal                       | N           |                |                                            |
| brunnermunzel                             | t distribution               | N           |                |                                            |


## Points of uncertainty
- I've found somewhat conflicting information about P values and the Chi-square test (some say it's [essentially a one-sided test](https://stats.stackexchange.com/a/22350)) so for now I've marked any tests that use it under the hood as inelegible. This is subject to change.
- The Anderson tests, as implemented, seem to have a very custom way of calculating their P value. I need some help figuring out what changes need to be made to implement the enhancement.

## Next Steps:
I'm in the process of implementing this functionality with the ttests. 

@mdhaber

**Comment by mdhaber** [comment]
Thanks for the summary @DominicChm. 
`tiecorrect` and `rankdata` are not statistical tests themselves; just helper functions. You don't need to do anything with them.
I think that most of the tests marked "Possibility of Implementation Uncertain" will not need an alternative argument, but let's ask the experts. @chrisb83 Do any of the tests marked "Possibility of Implementation Uncertain" need alternatives added?
I also don't think you need to worry about Anderson. It looks like it is using tabulated critical values rather than calculating a _p_-value itself, and changing this is out of scope. Would you agree @WarrenWeckesser ?

**Comment by chrisb83** [comment]
I will take a closer look later. For now, I can confirm that `epps_singleton_2samp` does not have a one-sided version. `combine_pvalues` is not a test and can be dropped from the list.

**Comment by rlucas7** [comment]
> On Jul 13, 2020, at 1:25 PM, Christoph Baumgarten <notifications@github.com> wrote:
> 
> ﻿
> I will take a closer look later. For now, I can confirm that epps_singleton_2samp does not have a one-sided version. combine_pvalues is not a test and can be dropped from the list.
> 
Combine pvalues is a (meta)test, it performs a test on a collection of tests (assumption is they are related) and determines if the collection of individual tests supports the hypothesis. 

You could imagine a collection of health experiments being tested, say the same COVID-19 intervention in X countries. The combine p-values tells you if the intervention is significant or not, aggregating across countries. 

You could also use it for A/B testing of the same feature on a webpage across many experiments/groups. Aggregating pvalues across all experiments is where the method would come in. 

I agree though that it would make sense to drop that one from the list. 
The one-sidedness would come from the underlying hypotheses that are used as input data.

**Comment by chrisb83** [comment]
I am not aware that any of the tests you list under "Possibility of Implementation Uncertain" has one-sided versions.

**Comment by WarrenWeckesser** [comment]
@DominicChm, the table above is really helpful, thanks!  I just updated the entry for `pearsonr` to link to https://github.com/scipy/scipy/pull/12609, a PR that adds the `alternative` argument and the calculation of a confidence interval to `pearsonr`.

**Comment by mdhaber** [comment]
@DominicChm when gh-12531 merges, please add it to this table

**Comment by mdhaber** [comment]
Closing gh-4882 as this is more up to date, but that also mentions zscore and chi2_contingency as candidates.

**Comment by tirthasheshpatel** [comment]
While working on #13958, I found out that the entry `ttest_ind_from_stats [MASKED]` already has an implementation for the `alternative` parameter so it should be removed from the table.

**Comment by mdhaber** [comment]
Is the masked version of `ttest_ind_from_stats` a public function? It doesn't seem to appear in the [documentation](http://scipy.github.io/devdocs/reference/stats.mstats.html). Is it in `__all__`?
```
>>> scipy.stats.mstats.ttest_ind_from_stats
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'scipy.stats.mstats' has no attribute 'ttest_ind_from_stats'
```

**Comment by tirthasheshpatel** [comment]
> Is the masked version of `ttest_ind_from_stats` a public function? It doesn't seem to appear in the [documentation](http://scipy.github.io/devdocs/reference/stats.mstats.html). Is it in `__all__`?

Actuallt the masked version is implemented in `stats.py` itself and omits `nan`s by default. So, it won't be present in `mstats`. This will work instead:

```python
>>> from scipy import stats
>>> import numpy as np
>>> mean1, std1 = [np.nan, 2.], [np.nan, 5.]
>>> mean2, std2 = [np.nan, 3.], [np.nan, 4.]
>>> stats.ttest_ind_from_stats(mean1, std1, 10, mean2, std2, 8)
Ttest_indResult(statistic=array([        nan, -0.45936064]), pvalue=array([       nan, 0.65215468]))
```

**Comment by mdhaber** [comment]
@tirthasheshpatel 

Regarding gh-15586 closing this: technically there are a few other functions that _could_ conceivably have an `alternative` parameter but don't.

`pointbiserialr` it is an alias for `pearsonr`. Shall we just deprecate it?

There are others I'd suggest leaving to a separate effort for various reasons.
* `page_trend_test` is typically used as a one-sided tests, and the other one-sided alternative can be performed by reordering the input. It is possible to define a two-sided version, but I'm not sure if it's important to have unless it's requested.
* Some multi-sample tests are typically used in a two-sided sense, but could probably be defined in a one-sided way like `page_trend_test`. Someone would need to look more closely.
* Some functions, like `theilslopes`, don't return a p-value, but certainly could be used to perform a sensible statistical test. In particular, `theilslopes` already returns a confidence interval, so an `alternative` could be useful there. I think it's OK to leave those without an `alternative` for now, but to add `alternative` if/when someone wants to add other substantial functionality to them.
* `multiscale_graphcorr` was added relatively recently. It also seems to have been invented recently, and the author of the SciPy implementation was involved with that. Presumably, they decided that it didn't need an `alternative` parameter for typical use?
* Some masked versions of tests still don't have alternatives (e.g. `mannwhitneyu`), but given that we're adding masked support to the regular `stats` versions of the tests, I don't see a need to add `alternatives` in `mstats`. 

With those things in mind, do you think it is reasonable to consider this issue closed?
