### ISSUE TITLE
Null hypothesis of Kolmogorov Smirnov test is not correctly described

### ISSUE THREAD

**Issue by chrisb83** [scipy/scipy#12518]
The statement 

> Under the null hypothesis, the two distributions are identical, F(x)=G(x). The alternative hypothesis can be either ‘two-sided’ (default), ‘less’ or ‘greater’. 

in the documentation of `stats.kstest` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kstest.html) is not correct unless `alternative == 'two-sided'`. The other alternatives test `F >= G` vs `F < G` and vice versa.

Same problem for `stats.ks_2samp` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_2samp.html#scipy.stats.ks_2samp):

> This is a two-sided test for the null hypothesis that 2 independent samples are drawn from the same continuous distribution. 

and `stats.ks_1samp` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_1samp.html):

> Under the null hypothesis, the two distributions are identical, F(x)=G(x).

The alternatives are correctly described in the R documentation: 
https://stat.ethz.ch/R-manual/R-patched/library/stats/html/ks.test.html

**Comment by josef-pkt** [comment]
I'm not sure about this, 

The null hypothesis is always F(x)=G(x), only the alternative changes in one sided test.

By monotonicity, this usually implies F(x)<=G(x). However, the test distribution is computed under the assumption that F(x)=G(x).

(The distinction is more important in likelihood ratio and score tests.)

**Comment by brandondavid** [comment]
In case it helps...

From [stats.ks_2samp](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_2samp.html): 
> We generally follow Hodges’ treatment of Drion/Gnedenko/Korolyuk [1].

> Hodges, J.L. Jr., “The Significance Probability of the Smirnov Two-Sample Test,” Arkiv fiur Matematik, 3, No. 43 (1958), 469-86.

...which is available at https://doi.org/10.1007/bf02589501

**Comment by mdhaber** [comment]
[This](https://courses.lumenlearning.com/introstats1/chapter/null-and-alternative-hypotheses/) acknowledges the fact that sometimes the null hypothesis is written differently depending on the alternative, but that writing the null hypothesis the same way in all cases is also acceptable.

> However, be aware that many researchers (including one of the co-authors in research work) use = in the null hypothesis, even with > or < as the symbol in the alternative hypothesis. This practice is acceptable because we only make the decision to reject or not reject the null hypothesis.

I favor the way it is currently written, as I think the distribution we used to determine the *p*-value should be derived from the null hypothesis (as it is stated; not from some variation.). For the KS test, does the distribution used to calculate *p*-values depend on the alternative hypothesis being tested? If not, I think that the way the null hypothesis is written is correct regardless of the alternative.

**Comment by mdhaber** [comment]
@chrisb83 BTW would you still like to change these, or do you think they are ok?

**Comment by chrisb83** [comment]
@mdhaber I would be in favour of being more precise in the documentation, following the R doc. I just had a look at the document you shared:

> However, be aware that many researchers (including one of the co-authors in research work) use = in the null hypothesis, even with > or < as the symbol in the alternative hypothesis. This practice is acceptable because we only make the decision to reject or not reject the null hypothesis.

that makes sense. however, i think there are often situations where practitioners assume H0 holds unless it is rejected. in that case, it is important to interpret H0 correctly.

**Comment by josef-pkt** [comment]
> favour of being more precise

H0: F = G is precise

the p-value is computed under this assumption
If F < G, then the true pvalue would be larger. i.e. if we have a joint null hypothesis, then we have to argue with max or min pvalue in the subset of the parameter space under the null.

In likelihood ratio and score tests, the test results might not be the same for H0: a <= a0 and H0: a = a0. So you couldn't make an argument there that would be consistent with KS tests or simple t-tests which are monotonic.
I'm not sure about KS test with estimated parameters.

> practitioners assume H0 holds unless it is rejected

that's an argument for babysitting and not for being precise.

maybe and explanatory sentence would be useful
If the tests does not reject for alternative F > G against null F = G, then it would also not reject against F < G.

---
I just realized/remembered that the KS test is a functional hypothesis, and the single parameter analogue doesn't work

F >= G vs F < G  are not complements of each other.
F and G can intersect, in that case we also don't reject, so the opposite of` F > G` is `not F > G` which is an even weirder null.

**Comment by josef-pkt** [comment]
Actually I don't remember how inequalities are defined in onesided ks test, but any ordering has to allow for intersections of the cdfs for cases `not F=G`, whether they are included in some null or alternative.

**Comment by josef-pkt** [comment]
the intersection case is in the alternative, there needs to be an "at least for some range"

https://stats.stackexchange.com/questions/107668/does-it-make-sense-to-perform-a-one-tailed-kolmogorov-smirnov-test

H0:F_Y(t)≥F_X(t)
H1:F_Y(t)<F_X(t), for at least one t

quote "You could in some cases write the null as an equality" but then uses weak inequality

(I got suspicious with my initial intuition for the functional case when looking at the confidence band implied by KS-test. In the one-sided case the ecdf has to be completely on one side (the inside side) of one confidence band boundary to **not** reject the null. If at least a small piece of the ecdf crosses or is on the outside of the confidence band, then we reject.)

So that still leaves it open whether null is specified as equality or weak inequality.

**Comment by josef-pkt** [comment]
going back to this

> practitioners assume H0 holds unless it is rejected

The main problem is that some practitioners do this also when their sample size is too small and the test doesn't have much power.
If the sample size is not large, then we would also NOT reject if the ecdf or true cdf wiggles around the null cdf, or in two sample case if the two cdfs wiggle around each other.
In that case we have neither F <=G nor F >= G. If we don't reject, then we can only say that there are no big deviations in parts of the cdf in the alternative direction.

**Comment by chrisb83** [comment]
yes, I also checked in the stats book by Conover. The one-sided case is

H0: F(x) <= G(x) for all x
H1: F(x) > G(x) for at least one x

**Comment by josef-pkt** [comment]
sounds fine to me then to use the last version with weak inequality in null.

I'm sticking to equality null in statsmodels, because I don't want to get into composite nulls when we don't need or use it.
