### ISSUE TITLE
scipy.linalg.cholesky does not raise LinAlgError on non positive-definite matrix

### ISSUE THREAD

**Issue by xie-tony** [scipy/scipy#12511]
My issue is about scipy.linalg.cholesky not raising LinAlgError on non positive-definite matrix

#### Reproducing code example:

```
import numpy as np
from scipy import linalg
a = np.array([
  [0.9701, 0.7078, 0.4594],
  [0.9701, 0.7079, 0.4593],
  [0.9701, 0.7078, 0.4594]
])
linalg.cholesky(a)
linalg.cholesky(a, lower=True)
```

The matrix a is a singular matrix, thus it is not positive-definite.
However, when calling `linalg.cholesky(a)`, it is able to return a result without raising an error.
When calling `linalg.cholesky(a, lower=True)`, it correctly raise numpy.linalg.LinAlgError

#### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.5.1 1.18.5 sys.version_info(major=3, minor=8, micro=3, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment]
Hi @xie-tony when you use `upper` your array is assumed to be 

```
b = array([[0.9701, 0.7078, 0.4594],
       [0.7078, 0.7079, 0.4593],
       [0.4594, 0.4593, 0.4594]])
```

which is not singular and actually pos def 

```
sp.linalg.eigvals(b)
Out[9]: 
(array([1.85840277, 0.19718553, 0.08181169])
```
