### ISSUE TITLE
scipy.stats.skew returning MaskedArray

### ISSUE THREAD

**Issue by gkbit** [scipy/scipy#12548]
scipy.stats.skew(data, nan_policy="omit") returns a MaskedArray when data contains "nan" values, instead of the skewness value itself.  scipy.stats.kurtosis(data, nan_policy="omit") however returns the kurtosis value normally even when data contains "nan" values.

#### Reproducing code example:

```
from numpy import nan
from scipy.stats import skew, kurtosis

skew([1,5,4,6,nan], nan_policy="omit")

kurtosis([1,5,4,6,nan], nan_policy="omit")
```

#### Output:

```
masked_array(data=-0.68724319,
             mask=False,
       fill_value=1e+20)

-1.0
```

#### Scipy/Numpy/Python version information:

```
1.5.0 1.18.5 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)

```

**Comment by Kai-Striega** [comment]
Hey thanks for reporting this! I did some digging and it looks like the masked array is never converted back to a scalar. More interestingly this also seems to happen for ```kurtosis``` 

```python
>>> kurtosis([1,5,4,6,nan], nan_policy="omit")
-1.0  # What we expected
```
```python
>>> kurtosis([1,5,4,6,nan], fisher=False, nan_policy="omit")
masked_array(data=2.,  #  Correct value but a masked array
             mask=False,
       fill_value=1e+20)
```
The difference between the two occurs here where one gets the additional `-3` (converting it to a scalar) while the other does not. 

https://github.com/scipy/scipy/blob/8692c887ac341ace4183f115c55290ec9daf470b/scipy/stats/mstats_basic.py#L2358-L2361

I'm 90% sure a similar situation occurs for the masked version of skew but haven't had time to confirm it yet. If it is I'll prepare a pr and see what everyone else thinks.

**Comment by mdhaber** [comment]
Fixed by gh-15472
