### ISSUE TITLE
ConvexHull of a planar surface in 3D does not give correct points

### ISSUE THREAD

**Issue by chudur-budur** [scipy/scipy#12546]
I have a set of data points that is composed of a plane and a line in a 3-dimensional space. 

The data points are here: [dataf.csv](https://github.com/chudur-budur/visualization/blob/org/data/dtlz8-nbi/3d/dataf.csv)

When I use `ConvexHull`, I get points that are **inside the surface** (I'm using `qhull_options = "Qa QJ Q12"`) --

![Output image](https://i.postimg.cc/DfH7hT4q/download.png)

#### Reproducing code example:

```
%matplotlib notebook

import numpy as np
from scipy.spatial import ConvexHull
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

F = np.loadtxt('dataf.csv', delimiter = ',')
C = ConvexHull(F, qhull_options = "Qa QJ Q12")
print(C.vertices)

H = F[C.vertices]

fig = plt.figure()
ax = Axes3D(fig)
ax.scatter(F[:,0], F[:,1], F[:,2], s = 2.5)
ax.scatter(H[:,0], H[:,1], H[:,2], s = 5, c = 'red')
plt.show()
```

<!--```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```-->

#### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.4.1 1.18.1 sys.version_info(major=3, minor=7, micro=5, releaselevel='final', serial=0)
```

**Comment by rkern** [comment]
It is very difficult to construct sets of points that are _exactly_ coplanar/collinear when represented by finite-precision floating point numbers. However you constructed them, some are bound to get rounded such that they are _ever_ so slightly out of plane/line. I suspect that is what is going on here and that `ConvexHull` is reporting those points accurately, according to the QHull options you selected.

**Comment by chudur-budur** [comment]
> It is very difficult to construct sets of points that are _exactly_ coplanar/collinear when represented by finite-precision floating point numbers. However you constructed them, some are bound to get rounded such that they are _ever_ so slightly out of plane/line. I suspect that is what is going on here and that `ConvexHull` is reporting those points accurately, according to the QHull options you selected.

I see, that might be the reason. I'm closing the issue then.
