### ISSUE TITLE
stats.pareto.fit raises RuntimeWarning 

### ISSUE THREAD

**Issue by swallan** [scipy/scipy#12545]
When using pareto.fit to fit data, including data generated from pareto.rvs, a runtimewarning is raised. 

#### Reproducing code example:

```
from scipy.stats import pareto
data = pareto.rvs(b=1, size=100)
pareto.fit(data)
```

#### Error message:

```
Users/swallan/Documents/SciPy/scipy/scipy/stats/_distn_infrastructure.py:2430: RuntimeWarning: invalid value encountered in double_scalars
  Lhat = muhat - Shat*mu
Out[42]: (1.065735836832905, -0.0001807709658628293, 1.0040027363129118)
```

#### Scipy/Numpy/Python version information:

```
1.6.0.dev0+75a99c5 1.17.4 sys.version_info(major=3, minor=7, micro=7, releaselevel='final', serial=0)
```

In gh-12457, I had to suppress this warning when using the default fit method in comparison to MLE. This warning is not related to the changes made there.

**Comment by WarrenWeckesser** [comment]
The shape parameter `b` for `pareto` must be greater than 1.   If `b` is 1, the mean and variance are infinite:

```
In [6]: pareto.stats(1.0, moments='mv')                                                            
Out[6]: (array(inf), array(inf))
```

The `fit` method, however, uses the value 1 as the default initial guess for `b`, and that leads to the warning in the method `fit_loc_scale`.

If different initial guesses are given for all the parameters, the warning doesn't occur.  E.g.

```
In [10]: x = pareto.rvs(2.5, size=25)

In [11]: pareto.fit(x)   # This triggers the warning.
/Users/warren/mc37scipy/lib/python3.7/site-packages/scipy-1.6.0.dev0+31766cb-py3.7-macosx-10.9-x86_64.egg/scipy/stats/_distn_infrastructure.py:2431: RuntimeWarning: invalid value encountered in double_scalars
  Lhat = muhat - Shat*mu
Out[11]: (2.8729686138231445, 0.009175049018127227, 1.0477362946001745)

In [12]: pareto.fit(x, 3, loc=0, scale=1)   # No warning
Out[12]: (2.8903562253173907, 0.0003045141607943308, 1.0566068295000033)
```

We should be able to fix this by overriding the appropriate method that generates the default initial guess for the parameters.

**Comment by swallan** [comment]
I see. Another option, instead of overriding the method that creates the guess, would be to pass in a guess with the overriden fit method.

**Comment by mdhaber** [comment]
I think the most complete solution here is to avoid the generic fit.

The log likelihood function is:
![image](https://user-images.githubusercontent.com/6570539/100529122-edd6cf00-3198-11eb-9247-43649951cb95.png)

The partials are:
![image](https://user-images.githubusercontent.com/6570539/100529160-502fcf80-3199-11eb-9aae-09ff990ae230.png)

![image](https://user-images.githubusercontent.com/6570539/100529182-82413180-3199-11eb-8aa9-f0833dacbd6b.png)

![image](https://user-images.githubusercontent.com/6570539/100529200-be749200-3199-11eb-8897-e6b0ab4f2d92.png)

The first can be solved in closed form, and you've already implemented that.

There is a constraint on the domain:
![image](https://user-images.githubusercontent.com/6570539/100529221-f67bd500-3199-11eb-9fc7-2a9b7ff64f1e.png)

This, with the requirement that the shape and scale are always positive, means that the second two partials are always greater than zero. Therefore, to maximimize the log likelighood, we want to increase both the scale and location as much as possible.

However, that constraint requires that

![image](https://user-images.githubusercontent.com/6570539/100529267-9b96ad80-319a-11eb-9f9e-3ed859c290aa.png)

At the solution, the constraint will be active:

![image](https://user-images.githubusercontent.com/6570539/100529301-f6c8a000-319a-11eb-8751-7f9b9c17286d.png)

If you apply the method of Lagrange multipliers to this constrained optimization problem, you get

![image](https://user-images.githubusercontent.com/6570539/100529085-7ef97600-3198-11eb-8409-6ea2dee267a2.png)

This can be solved with `root_scalar`, e.g.

```
import numpy as np
from scipy.stats import pareto
from scipy.optimize import root_scalar

np.random.seed(0)
b, u, s = 2, 3, 4
xi = pareto.rvs(b=b, loc=u, scale=s, size=100000)

def ll(dist, xi=xi, *args):
    return np.sum(np.log(dist.pdf(xi, *args)), axis=0)

def get_ub(s):
    N = len(xi)
    u = np.min(xi) - s
    b = N / np.log((xi-u)/s).sum()
    return u, b

def h(s):
    N = len(xi)
    u, b = get_ub(s)
    return s*(b+1)*np.sum(1/(xi-u)) - N*b

res = root_scalar(h, bracket=(0.0001, np.max(xi)))

s = res.root
u, b = get_ub(s)
print(b, u, s)

d = 0.00001
print(ll(pareto, xi, b, u, s) - ll(pareto, xi, b+d, u, s))
print(ll(pareto, xi, b, u, s) - ll(pareto, xi, b-d, u, s))
print(ll(pareto, xi, b, u, s) - ll(pareto, xi, b, u+d, s))
print(ll(pareto, xi, b, u, s) - ll(pareto, xi, b, u-d, s))
print(ll(pareto, xi, b, u, s) - ll(pareto, xi, b, u, s+d))
print(ll(pareto, xi, b, u, s) - ll(pareto, xi, b, u, s-d))
```
prints:
```
1.9850230169885779 3.046847941317803 3.9531586798075518
1.2689561117440462e-06
1.268985215574503e-06
inf
0.5021354560158215
inf
0.5021365668799262
```
The thing that needs to be done is to find an analytical bracket around `s` so we're sure it contains a root, or I'm checking to see if `h(s=0)` is always negative, in which case a derivative-based method should work.

**Comment by mdhaber** [comment]
@swallan I think it would be good to add this to the list. If I remember correctly, I was never able to find analytical bounds for `root_scalar`, but I do think that we can expand the bounds iteratively until we find a sign change, then do `root_scalar`. I think this strategy is employed in some functions - maybe even somewhere in `rv_continuous`? It might be good to break this out into a private function.

**Comment by swallan** [comment]
@mdhaber I have been experimenting with the system of eq. from above. I agree that it is essential to make sure that the brackets contain a sign change. That said, when fitting, I don't alway see a smaller log-likelihood result than the generic fitting from RV continuous. (though they are very similar and match the parameters the data was generated with better)
<img width="559" alt="Screen Shot 2022-01-18 at 1 43 06 PM" src="https://user-images.githubusercontent.com/44255917/150023372-94fb1b90-e4d3-48d4-ab8b-237741117d0b.png">

For 100,000 random variates with the parameters `b, location, scale = 5, 2, 4`.

The speed is much better, as well. Is the trade off of slightly worse LL result worth the massive speed increase (for fitting all three parameters)?

**Comment by mdhaber** [comment]
> Is that the LL or the negative LL? It looks like a LL, which we would be trying to maximize. In that case, there is no problem.

This is the case. You have reported the log-likelihood (which is typically a negative number). We want to _maximimize that_, and -97686.38 > -97799.63, so solving the system of equations has done its job better than the numerical optimization.

We often maximize the LL by minimizing the negative _of the_ LL ("negative LL"), which is typically a positive number. 

```python3
>>> import numpy as np
>>> from scipy.stats import pareto
>>> x = pareto.rvs(5, 2, 4, size=100000)
>>> pareto.nnlf((5, 2, 4), x)  # a positive number
98059.73308263488
>>> help(pareto.nnlf)
Help on method nnlf in module scipy.stats._distn_infrastructure:

nnlf(theta, x) method of scipy.stats._continuous_distns.pareto_gen instance
    Negative loglikelihood function.
    
    Notes
    -----
    This is ``-sum(log pdf(x, theta), axis=0)`` where `theta` are the
    parameters (including loc and scale).
```
I think `nnlf` is an erroneous acronym for Negative Log-Likelihood Function. Its interface is unusual because it accepts a tuple `theta` instead of individual arguments, but can still be handy.

**Comment by swallan** [comment]
We discussed it, but the issue was not negating the LL function. I'm working on writing some tests and figuring out a little bit of instability.

**Comment by swallan** [comment]
I've been using the [hypothesis package](https://hypothesis.readthedocs.io/en/latest/index.html) to figure whether solving the system of equations is broadly applicable and to see where issues may be. Solving the system of equations is very effective in cases where the sample size is large (500+), but when `size=100` it's easy to find a seed where the penalized negative log likelihood function indicates a poor fit. 

In my opinion, fitting all three parameters with such a small sample set might be naturally volatile: 

For parameters `b, location, scale = 2, 0, 5` and `size=100`:
<details>
<summary>(full python script if you would like to run yourself)</summary>
<p>

```
import numpy.testing as t
import scipy.stats as stats
import numpy as np

def _assert_less_or_close_loglike(dist, data, func, **kwds):
    """
    This utility function checks that the log-likelihood (computed by
    func) of the result computed using dist.fit() is less than or equal
    to the result computed using the generic fit method.  Because of
    normal numerical imprecision, the "equality" check is made using
    `np.allclose` with a relative tolerance of 1e-15.
    """
    mle_analytical = dist.fit(data, **kwds)
    numerical_opt = super(type(dist), dist).fit(data, **kwds)
    ll_mle_analytical = func(mle_analytical, data)
    ll_numerical_opt = func(numerical_opt, data)
    print(f"mle_analytical: {mle_analytical}")
    print(f"numerical_opt: {numerical_opt}")
    print(f"ll_mle_analytical: {ll_mle_analytical}")
    print(f"ll_numerical_opt: {ll_numerical_opt}")
    assert (ll_mle_analytical <= ll_numerical_opt or
            np.allclose(ll_mle_analytical, ll_numerical_opt, rtol=1e-15))

# for size in range(50, 1000):
np.random.seed(4597199)
b, location, scale = 2, 0, 5
data = stats.pareto.rvs(b=b, loc=location, scale=scale, size=100)
args = [data, (stats.pareto._fitstart(data), )]
func = stats.pareto._reduce_func(args, {})[1]
_assert_less_or_close_loglike(stats.pareto, data, func)
```
</p>
</details>

Output: 
```
mle_analytical: (5.79527148529069, -9.336516662409203, 14.369757655152599)   # refers to solving system of equations
numerical_opt: (2.5150595902624344, -0.01533774509774542, 5.04857873768222)  # refers to rv_continuous.fit
ll_mle_analytical: 71188.09212981045
ll_numerical_opt: 209.4450969351958
... [assertion failure]
```
Clearly the parameters determined by the system of equations are near some sort of asymptote for the penalized nnlf. I suspect this because if I carefully iterate the scale a little bit from the result obtained by solving the system of partial derivatives, the nnlf result isn't sky high. I can even obtain a better result than even the fit by `rv_continuous`: 
```
>>> stats.pareto._penalized_nnlf((5.79527148529069, -9.326516662409203, 14.34), data)
208.86173921914963
```
I'm not really sure what might be causing this, but it could be relating to the penalization of the nnlf in rv_continuous, whereas the the partial derivatives used in the system of equations in the overridden fit method uses no penalty. One quick and dirty solution would be to fit only large(r) datasets using the system of equations.

**Comment by mdhaber** [comment]
Could you open a PR against my repo so I can see the branch?

**Comment by mdhaber** [comment]
> I'm not really sure what might be causing this, but it could be relating to the penalization of the nnlf in rv_continuous

That is what is happening. As you say, the analytical fit (really, numerical solution to the first-order necessary conditions, but we can call it "analytical" compared to "numerical optimization") is right on the cusp of being better than the numerical optimization fit. The problem is that the left-most data point, `5.03324099` is just outside the support of the distribution.

```

>>> stats.pareto.pdf(data.min(), *mle_analytical)
0.0

>>> stats.pareto.pdf(data.min()+1e-8, *mle_analytical )
0.40329639542152484
```
So the analytical solution is essentially right... but numerics gets in the way. We'll think about how to avoid this tomorrow.

**Comment by mdhaber** [comment]
Closes by gh-15567, right @swallan?

**Comment by fancidev** [comment]
Let me recap the MLE for Pareto and reveal some resemblance to the MLE of the “powerlaw” (inverse Pareto) distribution.

Let $x_1,\cdots,x_n$ be a sample of $n$ independent observations from the Pareto distribution with shape $a > 0$, scale $b > 0$, and location $m \in \mathbb{R}$, such that $m+b \le x_{(1)}$ where $x_{(k)}$ is the $k$-th order statistic. The density function is

$$
f(x)=\frac{ab^a}{(x-m)^{a+1}}
$$

and the log likelihood is

$$
\mathcal{l}(a,b,m)=n \ln a+na\ln b-(a+1)\sum\ln(x_i-m)
$$

**Case 1**. Suppose shape $a$ is known. Since the likelihood function is increasing in $b$ and also increasing in $m$, we want both to be as large as possible subject to the support constraint $b+m\le x_{(1)}$. If $m$ is known, set $\hat{b}=x_{(1)}-m$. If $b$ is known, set $\hat{m}=x_{(1)}-b$. If both are unknown, substitute $b=x_{(1)}-m$ into the log likelihood function to obtain

$$
\mathcal{l}(m)=
$$

**Comment by fancidev** [comment]
**Case 2**. Now suppose shape $a$ is unknown. There are three sub-cases:

*Case 2(a)*. $m$ and $b$ are both known. From the first order condition

$$
\frac{\partial \mathcal{l}}{\partial a} = \frac{n}{a}+n\ln b-\sum\ln (x_i-m) =0
$$

we find

$$
\hat{a}=\frac{n}{\sum\ln(x_i-m)-n\ln b}
$$

$\hat{a}$ is guaranteed to be positive and finite, unless all observations are equal to $m+b$, in which case $\hat{a}=+\infty$ and  is inadmissible.

*Case 2(b)*. Exactly one of $m$ and $b$ is known and the other is unknown. For any fixed value of $a$, the log likelihood is increasing in $m$ and $b$, so we want the unknown parameter to be as large as possible subject to the support constraint $m+b\le x_{(1)}$. If $m$ is known, set $\hat{b}=x_{(1)}-m$. If $b$ is known, set $\hat{m}=x_{(1)}-b$. Then compute $\hat{a}$ as in Case 2(a).
