### ISSUE TITLE
typo in scipy/cluster/_hierarchy.pyx

### ISSUE THREAD

**Issue by GreatV** [scipy/scipy#12547]
https://github.com/scipy/scipy/blob/4fab4fdf8013ad9cc0d90e47eb0b183cd7ba6705/scipy/cluster/_hierarchy.pyx#L503

R is a  (n - 1) -by-4 matrix, not (n - 1)-by-5 matrix。

**Comment by ilayn** [comment]
Hi @GreatV thanks for reporting it. Would you like to send a Pull Request for it? Please feel free to decline but since you found it maybe you also want to fix it. Otherwise someone else would probably attend to it soon.
