### ISSUE TITLE
I am trying to use scipy.optimize to correct an image which is rotated,like:rotated = transform.rotate(img,45),but the corrected image changed little,plz anyone tell me where I did wrong?

### ISSUE THREAD

**Issue by Reyyyyyy** [scipy/scipy#12561]
here is my code:
```python
from skimage import data,transform,filters
from scipy import optimize as op
import numpy as np
from matplotlib import pyplot as plt

#建立刚性转换函数（平移，旋转）
def rigid_transform(img,params):#params包含三个参数r,tc,tr：逆时针旋转r度，向左移（向左若tc为负）tc，向上（向下若tr为负）移tr
    r,tc,tr = params
    transformation = transform.SimilarityTransform(rotation=r,translation=(tc,tr))
    transformed = transform.warp(img,transformation,order=3)#order是方式，共有6个,对应0到5
    return transformed
    
#定义MSE误差函数
def mse(img1,img2):
    return np.mean((img1-img2)**2)

#定义损失函数，作为op.minimize优化函数的输入
def cost(params,label,target):
    transformation = rigid_transform(target,params)
    return mse(label,transformation)

#定义高斯金字塔建立函数
def gaussian_pyramid(img,levels=6):
    pyramid = []
    for level in range(levels):
        level += 1
        pyramid.append(filters.gaussian(img,sigma=level))
    return pyramid
                      

#定义对齐图片的函数，它在高斯金字塔的每一级上优化损失函数，使用前一级别的结果作为下一级别的起始点
def align(label,target,nlevels=3,cost=cost):
    pyramid_label = gaussian_pyramid(label,nlevels)
    pyramid_target = gaussian_pyramid(target,nlevels)
    levels = range(nlevels,0,-1)#3,2,1
    img_pairs = zip(pyramid_label,pyramid_target)
    params = np.ones(3)#待训练的参数:r,tc,tr，参数的初始位置为(0,0,0)
    for n,(lbl,tgt) in zip(levels,img_pairs):
        params[1:] *= 2 #后两个元素(tc,tr)乘等2
        res = op.minimize(cost,params,args=(lbl,tgt),method='Powell')
        params = res.x
    print(params)
    return rigid_transform(target,params)
        
img = data.astronaut()
rotated = transform.rotate(img,45)
corrected = align(img,rotated,nlevels=7)

plt.imshow(corrected)
plt.show()
```

**Comment by sethtroisi** [comment]
I took a look at your code. `SimilarityTransform` rotates around the corner not center of the image.
no `r,tc,tr` will ever undo the 45 degree rotation.

I replaced rigid_transform with this which rotates around the center.
```
def rigid_transform(img, params):#params包含三个参数r,tc,tr：逆时针旋转r度，向左移（向左若tc为负）tc，向上（向下若tr为负）移tr
    r,tc,tr = params
    shift_x, shifty = np.array(img.shape[:2])/2
    tf_rotate = transform.SimilarityTransform(rotation=np.deg2rad(r), translation=(tc,tr))
    tf_shift = transform.SimilarityTransform(translation=[-shift_x, -shift_y])
    tf_shift_inv = transform.SimilarityTransform(translation=[shift_x, shift_y])
    transformed = transform.warp(img, (tf_shift + (tf_rotate + tf_shift_inv)).inverse)
    return transformed
```

`align` seems to throw away the result of the op.minimize for all but the last level (level=0) so I printed `params` inside the loop just to see what it was doing.

Sadly none of this helped and the corrected image is still mostly unchanged.

**Comment by Reyyyyyy** [comment]
> I took a look at your code. SimilarityTransform rotates around the corner not center of the image.
> no r,tc,tr will ever undo the 45 degree rotation.
> I replaced rigid_transform with this which rotates around the center.
> def rigid_transform(img, params):#params包含三个参数r,tc,tr：逆时针旋转r度，向左移（向左若tc为负）tc，向上（向下若tr为负）移tr
>     r,tc,tr = params
>     shift_x, shifty = np.array(img.shape[:2])/2
>     tf_rotate = transform.SimilarityTransform(rotation=np.deg2rad(r), translation=(tc,tr))
>     tf_shift = transform.SimilarityTransform(translation=[-shift_x, -shift_y])
>     tf_shift_inv = transform.SimilarityTransform(translation=[shift_x, shift_y])
>     transformed = transform.warp(img, (tf_shift + (tf_rotate + tf_shift_inv)).inverse)
>     return transformed
> 
> align seems to throw away the result of the op.minimize for all but the last level (level=0) so I printed params inside the loop just to see what it was doing.
> Sadly none of this helped and the corrected image is still mostly unchanged.

thanks for your advice,it seems that the mistake lies in function align.The weird thing is the params are acutually  updated,but still the corrected img stays the same..

**Comment by Reyyyyyy** [comment]
thanks for your advice!!it seems that the mistake lies in function align.The weird thing is the params are acutually  updated,but still the corrected img stays the same..





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "scipy/scipy"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 上午8:15
收件人:&nbsp;"scipy/scipy"<scipy@noreply.github.com&gt;;
抄送:&nbsp;"Bear Grylls"<2483278452@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [scipy/scipy] I am trying to use scipy.optimize to correct an image which is rotated,like:rotated = transform.rotate(img,45),but the corrected image changed little,plz anyone tell me where I did wrong? (#12561)





 
I took a look at your code. SimilarityTransform rotates around the corner not center of the image.
 no r,tc,tr will ever undo the 45 degree rotation.
 
I replaced rigid_transform with this which rotates around the center.
 def rigid_transform(img, params):#params包含三个参数r,tc,tr：逆时针旋转r度，向左移（向左若tc为负）tc，向上（向下若tr为负）移tr     r,tc,tr = params     shift_x, shifty = np.array(img.shape[:2])/2     tf_rotate = transform.SimilarityTransform(rotation=np.deg2rad(r), translation=(tc,tr))     tf_shift = transform.SimilarityTransform(translation=[-shift_x, -shift_y])     tf_shift_inv = transform.SimilarityTransform(translation=[shift_x, shift_y])     transformed = transform.warp(img, (tf_shift + (tf_rotate + tf_shift_inv)).inverse)     return transformed  
align seems to throw away the result of the op.minimize for all but the last level (level=0) so I printed params inside the loop just to see what it was doing.
 
Sadly none of this helped and the corrected image is still mostly unchanged.
