### ISSUE TITLE
lombscargle produces wrong output

### ISSUE THREAD

**Issue by jorabold** [scipy/scipy#12572]
The [lombscargle](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.lombscargle.html) function produces unexpected results: Frequency peak at ~6Hz for a 1Hz cosine oscillation.

#### Reproducing code example:

```
import matplotlib.pyplot as plt
import scipy.signal as signal
import numpy as np

x = np.linspace(0, 10, 1000)
y = np.sin(2*np.pi*x)
f = np.linspace(0.1, 10, 1001)
pgram = signal.lombscargle(x, y - y.mean(), f)
plt.plot(f,pgram)
```

![lomb](https://user-images.githubusercontent.com/52318318/87854680-d0087c00-c913-11ea-97cf-6b857496cc6b.png)

Executing a fft on the same data returns the results I expected (frequency peak at 1Hz):

```
Y = np.fft.fft(y)
f_fft = np.linspace(0, 1000/10, 1000)
plt.plot(f_fft[1:50], abs(Y[1:50]))
```

![fft](https://user-images.githubusercontent.com/52318318/87854684-d4cd3000-c913-11ea-8bc1-c6c76644cdf4.png)

Matlab (and my [octave implementation](https://octave-online.net/workspace~RmeAYnWXiyoabfsolwhASctEsCrzlLsUGQPBcEEGijSUNEiV)) shows a peak at 1 Hz as well:

```
x = linspace(0, 10, 1000);
y = sin(2*pi*x);
f = linspace(0.1, 10, 1001);
[per,f] = plomb(y,x,10);
plot(f, per)
```

![grafik](https://user-images.githubusercontent.com/52318318/87855341-ed3f4980-c917-11ea-8384-918869fdeed2.png)

#### Scipy/Numpy/Python version information:

```
1.4.1 1.18.5 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
```

**Comment by jakevdp** [comment]
It looks like the peak is different than what you expect by a factor of 2π. Perhaps it's an issue of frequency vs. angular frequency?

**Comment by jakevdp** [comment]
Indeed, looking at the `lombscargle` [docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.lombscargle.html), `f` is an angular frequency. So you can produce the results you're looking for like this:
```
import matplotlib.pyplot as plt
import scipy.signal as signal
import numpy as np

x = np.linspace(0, 10, 1000)
y = np.sin(2*np.pi*x)
f = np.linspace(0.1, 10, 1001)
pgram = signal.lombscargle(x, y - y.mean(), 2 * np.pi * f)
plt.plot(f,pgram)
```
![lombscargle](https://user-images.githubusercontent.com/781659/87855635-7d58a100-c8ce-11ea-91ff-b3a81b702591.png)

**Comment by jorabold** [comment]
Oh, thanks!
