### ISSUE TITLE
BLD, MAINT: distutils issues in wheels repo

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#12579]
While attempting to build draft SciPy `1.5.2` wheels, I've noticed [some errors](https://travis-ci.org/github/MacPython/scipy-wheels/builds/709576087) like this during SciPy build:

```
scipy/signal/firfilter.c:185:4: error: ‘for’ loop initial declarations are only allowed in C99 mode
    for (int64_t k=0; k < Nwin[1]; k++) {
    ^/opt/python/cp36-cp36m/lib/python3.6/site-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
Running from SciPy source directory.
```

I'm not sure if that is two separate issues, but I know that NumPy team was pinning the version of setuptools in use recently--cc @charris, @mattip since I've seen similar issues cropping up on their end recently.

Could it be that I'll need to pin `setuptools` in the wheels repo and/or pull in a newer version of the `numpy-distutils` submodule as well?

**Comment by mattip** [comment]
Pinning `setuptools!=49.2.0` like numpy/numpy#16875 should be sufficient to clear the warning. The setuptools people promise the next version will not warn like this.

**Comment by tylerjereddy** [comment]
hmm, wheels issues were Linux-only; not Mac OS or Windows; I'll perhaps have to check the logs more carefully to understand if this is the main/only issue.

**Comment by tylerjereddy** [comment]
That didn't help--I see `g++: error: unrecognized command line option ‘-std=c++14’` with or without that change.

Hmm, will maybe `multibuild` is overriding my pin somewhere I guess, or something completely different is happening.

**Comment by tylerjereddy** [comment]
Might be the old gcc version used by the manylinux1 base image, but why this suddenly crops up now I don't fully understand yet.

**Comment by peterbell10** [comment]
@tylerjereddy that warning is normal. For C++ code we first try `-std=c++14` and if it doesn't work we drop back to `-std=c++11`. The build errors are caused by gh-12238 which requires C99 to build and apparently this isn't enabled by default on that version of gcc. We should consider adding an older gcc to the CI build matrix so we can catch these issues sooner in future. 

I will look into adding `-std=c99` to the `setup.py` which should fix it.
