### ISSUE TITLE
MAINT: argument name inconsistency in NearestNDInterpolator

### ISSUE THREAD

**Issue by AtsushiSakai** [scipy/scipy#12589]
`griddata`, `LinearNDInterpolator`, `NearestNDInterpolator`, `CloughTocher2DInterpolator` are similar functions in `interpolate` module.
- [Interpolation \(scipy\.interpolate\) — SciPy v1\.5\.1 Reference Guide](https://docs.scipy.org/doc/scipy/reference/interpolate.html#multivariate-interpolation)

However, only `NearestNDInterpolator` use `x` and `y` for argument name, but others use `points` and `values`:
<img width="318" alt="SS 2020-07-20 at 20 20 34" src="https://user-images.githubusercontent.com/3813847/87932565-ae032b00-cac6-11ea-8abf-5f379d1408ef.png">

I think `NearestNDInterpolator` should use `points` and `values` for argument name for API consistency.

**Comment by rgommers** [comment]
Yes that would have made a lot of sense. Unfortunately, changing the names now would be a backwards compatibility break, so we can't really do that.

**Comment by AtsushiSakai** [comment]
Oh, I supposed these arguments are normal positional arguments, so it is ok to change the names. 
But someone might use it like:
`interp = NearestNDInterpolator(y=z, x=list(zip(x, y)))
`
I agree we should not do it.
