### ISSUE TITLE
DOC: Invalid syntax in example. 

### ISSUE THREAD

**Issue by Carreau** [scipy/scipy#12606]
In `_bspl.pyx` function evaluate_all_bspl https://github.com/scipy/scipy/blob/0765482e9a7cd7a7975f6161d2ab91994762ac8e/scipy/interpolate/_bspl.pyx#L198

`BSpline.basis_element(k:-k)` is invalid syntax, you can't use a slice like this is a function call. 

Came across this in a completely unrelated context, so haven't looked into what the original meaning was.

**Comment by ev-br** [comment]
Should have been `t[k:-k]`, indeed :-)

**Comment by Carreau** [comment]
(as a question not to open another issue; do you care about things like https://github.com/scipy/scipy/blob/0765482e9a7cd7a7975f6161d2ab91994762ac8e/scipy/sparse/linalg/dsolve/linsolve.py#L523 where the backticks should be double for ` ``A x = B`` ` ?

**Comment by peterbell10** [comment]
If you submit a PR, I'm sure it would be merged. Doc improvements are always appreciated.

**Comment by sethtroisi** [comment]
I couldn't find this doc string in docs.scipy.org or with a google search. Does it actually renders anywhere?

**Comment by ev-br** [comment]
> Does it actually renders anywhere?

No it does not, because it's a private function.

**Comment by Carreau** [comment]
> I couldn't find this doc string in docs.scipy.org or with a google search. Does it actually renders anywhere?

Yeah sorry that was because of me, working on a side project that auto scans docstrings. You might be able to trigger an error in spyder inspector that tries to run sphinx live on docstrings.
