### ISSUE TITLE
Export packages as scipy.ndimage, etc

### ISSUE THREAD

**Issue by brandondube** [scipy/scipy#12615]
There exist other packages that provide the same API as scipy, e.g. [cupyx](https://docs.cupy.dev/en/stable/reference/scipy.html).  One can enable interchange of them at runtime since they provide the same interface.  However, scipy does not export its packages:
```
import scipy
scipy.ndimage
>>> AttributeError: module 'scipy' has no attribute 'ndimage'
```

This is a trivial addition for me to make a PR to add.  Is there a reason scipy does not currently export the packages?

**Comment by rgommers** [comment]
Hi @brandondube, yes there's a reason: that will increase import time for no good reason. There's almost nothing in the main `scipy` namespace, the import style to use is `from scipy import ndimage`.

**Comment by brandondube** [comment]
I did a test,

```
git clone https://github.com/scipy/scipy
python setup.py install 
>>> Finished processing dependencies for scipy==1.6.0.dev0+063ab48
python -X importtime -c "import scipy"  # (repeat many times to warm up file cache and level the field)
import time:      3975 |     173027 | scipy # 170-180ms

I couldn't get any flavor of usual import to work on `scipy/__init__.py`, e.g. `from scipy import ndimage`, `import scipy.ndimage as ndimage`, etc.  They all error due to a cyclic import:
```
ImportError: cannot import name '_nd_image' from 'scipy.ndimage'
```

I do not agree that there is "almost nothing" in the main scipy namespace; `len(dir(scipy))` is > 600.

Is there a technical requirement for this cyclic import?  I don't know how to add entries `ndimage`, etc, to the main scipy namespace with it present.

**Comment by peterbell10** [comment]
>I do not agree that there is "almost nothing" in the main scipy namespace; len(dir(scipy)) is > 600.

Most of that is actually `numpy` imports like `scipy.array` is a deprecated alias for `numpy.array`. In actual fact, most of the `import scipy` time comes from importing NumPy. The only genuine `scipy` functionality in there is `scipy.test()` which runs the test-suite. 

>I couldn't get any flavor of usual import to work on scipy/__init__.py, e.g. from scipy import ndimage, import scipy.ndimage as ndimage, etc. They all error due to a cyclic import:

There shouldn't be any cyclic imports. Your installation is probably broken. Maybe try `pip install .` instead of calling `setup.py` directly.
