### ISSUE TITLE
ImportError: DLL load failed    from ._nnls import nnls

### ISSUE THREAD

**Issue by zzdzzdzzdzzd** [scipy/scipy#12619]
My issue is about ...

#### Reproducing code example:

```
Sample code to reproduce the problem
```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

**Comment by ilayn** [comment]
Hi @zzdzzdzzdzzd without any details, we won't be able to help you. That's why we created these separate sections in the template. Could you please edit the issue and fill out the details?

**Comment by erolgerceker** [comment]
how can i fix it. the error is below

from ._nnls import nnls
ImportError: DLL load failed while importing _nnls:

**Comment by GF-Huang** [comment]
![image](https://user-images.githubusercontent.com/4510984/124756617-3b9d8c00-df5f-11eb-8cb4-d823eefb1948.png)
