### ISSUE TITLE
scipy.interpolate.interpn docstring example

### ISSUE THREAD

**Issue by Blabinator** [scipy/scipy#12622]
My issue is about the example code for the scipy.interpolate.interpn function ( https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interpn.html ).  The np.meshgrid function switches the x and y dimension indexing, since it is set on "Cartesian" as default. The Example Code does not produce an Error, but might does not work as wanted either. The problem can be seen, when changing the x, y and z dimensions into not having equally many entries (see code below). The Problem can be solved by putting the x and y dimension into the right order:
```
values = np.swapaxes(value_func_3d(*np.meshgrid(*points)), 0, 1)
```
or by putting the meshgrid function into matrix indexing (‘ij’) (I don't know how, because of the "*points" as argument, I'm very new to python...).
Not a big bug but might help some people...

#### Reproducing code example:

```
from scipy.interpolate import interpn
import numpy as np
def value_func_3d(x, y, z):
    return 2 * x + 3 * y - z
x = np.linspace(0, 4, 5)
y = np.linspace(0, 5, 6)
z = np.linspace(0, 4, 5)
points = (x, y, z)
values = value_func_3d(*np.meshgrid(*points))
point = np.array([2.21, 3.12, 1.15])
print(interpn(points, values, point))
```

#### Error message:

```
ValueError                                Traceback (most recent call last)
<ipython-input-15-1265e69368be> in <module>
     14 
     15 point = np.array([2, 3, 1])
---> 16 print(interpn(points, values, point))

E:\Programme\Anaconda\lib\site-packages\scipy\interpolate\interpolate.py in interpn(points, values, xi, method, bounds_error, fill_value)
   2632         if not values.shape[i] == len(p):
   2633             raise ValueError("There are %d points and %d values in "
-> 2634                              "dimension %d" % (len(p), values.shape[i], i))
   2635     grid = tuple([np.asarray(p) for p in points])
   2636 

ValueError: There are 5 points and 6 values in dimension 0
```

**Comment by rgommers** [comment]
Thanks for the report and suggested improvement @Blabinator. This is fixed now.
