### ISSUE TITLE
Make root_scalar work when only x0 is given, similar to newton

### ISSUE THREAD

**Issue by astrojuanlu** [scipy/scipy#12620]
**Is your feature request related to a problem? Please describe.**

I would like to use the unified interface for scalar root finding functions, [`root_scalar`](https://docs.scipy.org/doc/scipy-1.5.2/reference/generated/scipy.optimize.root_scalar.html) (introduced in #8890) where I was using `newton`. However, while `newton` allows specifying only `x0` (and then uses the `secant` method by estimating a `x1`), `root_scalar` requires `x1` when `fprime` is not given.

```python
>>> from scipy.optimize import root_scalar, newton
>>> def f(x):
...   return x ** 3 - 1
... 
>>> newton(f, 0.2)
1.0000000000000002
>>> root_scalar(f, x0=0.2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/juanlu/.pyenv/versions/py38/lib/python3.8/site-packages/scipy/optimize/_root_scalar.py", line 251, in root_scalar
    raise ValueError('x1 must not be None for %s' % method)
ValueError: x1 must not be None for secant
```

**Describe the solution you'd like**

Make `root_scalar` work when only `x0` is given, similar to `newton`.

**Describe alternatives you've considered**

I could copy paste the logic that `newton` uses to set `x1` if not given:

https://github.com/scipy/scipy/blob/3bf0af5312f6b6b82bef5fbc8ce1b802522b2d21/scipy/optimize/zeros.py#L322-L325

But wouldn't it be better to have it in `root_scalar` instead?

cc @alexs12 @martosc

**Comment by pvanmulbregt** [comment]
The setting of `x1` from `x0` in `newton` is really an unprincipled hack which doesn't necessarily work well in practice. That's one reason I didn't include it in the`root_scalar` function.
Having a root finding function which starts from a single`x0` would be useful but it likely should first work to find an interval containing a root and then use one of the bracketing rootfinders, such as toms748, to find a better approximation to the root.

**Comment by astrojuanlu** [comment]
Even if it's an "unprincipled hack", it introduces an inconsistency between `root_scalar` and `newton` that in my opinion should not be there. Wouldn't it be better to restore so `root_scalar` can be used as a drop-in replacement of `newton`, and then improve the method so it's not a "hack" anymore?

**Comment by astrojuanlu** [comment]
I've been convinced by @pvanmulbregt in https://github.com/scipy/scipy/pull/12626#issuecomment-686248924 that having `newton` fall back to `secant` and guess a `x1` was a bad idea in the first place.
