### ISSUE TITLE
scipy.optimization.linprog unexpected unbound error

### ISSUE THREAD

**Issue by nathanb01** [scipy/scipy#12637]
My issue is about scipy.optimization.linprog. I expect my linear programming problem to be bound but I am getting an error saying that it is unbound and a matrix filled with inf and 0. 

I expect my problem to be bound because my problem involves dividing limited resources (9 types of resources) across many different products (111 different products). Therefore, each product must be lower bound by 0 (given in the docs) and upper bound by using up 1 or more of the resources. the slack variables (9, 1 for each resource) must also be lower bound by 0 (docs) and upper bound by the total amount of each resource. The function I am trying to optimize is the sum of each of these products weighted by their price (the slack variables are given a weight of 0). In order to maximize this function I instead minimize the negative of this. 

I used the following lines to perform the linear programming
#### Reproducing code example:
```
from scipy.optimization import linprog
print(linprog(c, method='simplex', options={'A':A, 'b':b}))
```
where A, b, and c are large and cumbersome lists or lists of lists so I put them in a spreadsheet [here](https://docs.google.com/spreadsheets/d/1jNtmUn3QTJJSx5NSudwHynP3o0YHpZ4L3XRQJm4y370/edit?usp=sharing).
In the rows of A (each row is an equation for a single resource) is the amount of the resource that each product uses and then the slack variables. In the rows of b is the amount of each resource that is available. In the columns of c are the prices of each product which are trying to be maximized (the values are negative to make it a minimization problem. For ease of viewing, negative numbers are colored in red, positive numbers in green, and 0 in yellow.

The code gave the following error message.
#### Error message:

```
     con: array([], dtype=float64)
     fun: -inf
 message: 'The problem is (trivially) unbounded because there are no non-trivial constraints and a) at least one decision variable is unbounded above and its corresponding cost is negative, or b) at least one decision variable is unbounded below and its corresponding cost is positive. '
     nit: 0
   slack: array([], dtype=float64)
  status: 3
 success: False
       x: array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.])
```

#### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.1 1.16.4 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```
I also tried method='revised simplex' but that didn't work either.

**Comment by nathanb01** [comment]
I also tried method='revised simplex' but that didn't work either.

**Comment by mdhaber** [comment]
Try the option 'presolve' : FALSE with each of the methods, please.

**Comment by nathanb01** [comment]
FALSE is giving me a NameError. Should it be the python builtin False or maybe 'FALSE'?

**Comment by nathanb01** [comment]
```
Traceback (most recent call last):
  File "factory.py", line 1124, in <module>
    print(linprog(c, method='simplex', options={'presolve':False, 'A':A, 'b':b}))
  File "C:\Users\njbar\Anaconda3\lib\site-packages\scipy\optimize\_linprog.py", line 466, in linprog
    c, c0=c0, A=A, b=b, callback=callback, _T_o=T_o, **solver_options)
TypeError: _linprog_simplex() got multiple values for keyword argument 'A'
```

**Comment by nathanb01** [comment]
hmm... 'revised simplex' is saying  `ValueError: Unknown solver revised simplex` now that i used `'presolve':False`

**Comment by mdhaber** [comment]
Sorry, I'm on a cell phone. Yes, `False`.
Well that sounds like a bug. 
How about the other methods with`"'presolve'":False`?

**Comment by nathanb01** [comment]
Which other methods are there?

**Comment by mdhaber** [comment]
Just a minute. I'm getting to a computer.

**Comment by nathanb01** [comment]
With 'interior-point' I get
```
  File "factory.py", line 1124, in <module>
    print(linprog(c, method='interior-point', options={'presolve':False, 'A':A, 'b':b}))
  File "C:\Users\njbar\Anaconda3\lib\site-packages\scipy\optimize\_linprog.py", line 469, in linprog
    c, c0=c0, A=A, b=b, callback=callback, **solver_options)
TypeError: _linprog_ip() got multiple values for keyword argument 'A'
```
I'm not sure where the multiple values for 'A' is coming from. Does this function not work with lists of lists?

**Comment by mdhaber** [comment]
I think you are correctly following incorrect documentation. There is a known bug that causes the current [documentation](https://docs.scipy.org/doc/scipy/reference/optimize.linprog-simplex.html) to show the signature like:
```
scipy.optimize.linprog(c, method='simplex', callback=None, options={'c0': None, 'A': None, 'b': None, 'postsolve_args': None, 'maxiter': 1000, 'tol': 1e-09, 'disp': False, 'bland': False}, x0=None)
```
but it should be like in the [old documentation](https://docs.scipy.org/doc/scipy-0.19.1/reference/optimize.linprog-simplex.html):
```
scipy.optimize.linprog(c, A_ub=None, b_ub=None, A_eq=None, b_eq=None, bounds=None, method='simplex', callback=None, options={'disp': False, 'bland': False, 'tol': 1e-12, 'maxiter': 1000})
```
Specifically, the constraints and bounds should be passed as arguments, not as options.

**Comment by nathanb01** [comment]
I added my own slack variables to make equality constraints so that I could follow the old documentation at https://docs.scipy.org/doc/scipy/reference/optimize.linprog-simplex.html

**Comment by mdhaber** [comment]
OK, then you have equality constraints, and you should try:
```
for method in ['simplex', 'revised simplex', 'interior-point']:
    print(linprog(c, A_eq=A, b_eq=b, method=method, options={"presolve":False}))
```

**Comment by mdhaber** [comment]
Those are the three methods.

I also recommend trying:
```
print(linprog(c, A_eq=A, b_eq=b, method="interior-point"))
```
without turning presolve off.

**Comment by nathanb01** [comment]
Using `print(linprog(c, method='simplex', A_eq=A, b_eq=b))` gives me

```
con: array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00, -5.55111512e-17,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00])
     fun: -20.699340863881787
 message: 'Optimization terminated successfully.'
     nit: 17
   slack: array([], dtype=float64)
  status: 0
 success: True
       x: array([  ...
```
I omitted the large array. This seems to have worked, thanks for the help. Sorry this isn't a new bug.

**Comment by mdhaber** [comment]
OK. Sorry about the trouble. I hope someone can help me with the documentation issue.

BTW, in the future, I'd avoid `method='simplex'`; try the default `method='interior-point'` or, if you need greater accuracy at the cost of speed and reliability, `method='revised simplex'`. Actually, if gh-12043 ever gets merged, I'd recommend `method='highs'` in the next release.
