### ISSUE TITLE
numpy.add.at implementation in sparse matrix

### ISSUE THREAD

**Issue by disadone** [scipy/scipy#12642]
**Is your feature request related to a problem? Please describe.**
My problem is just like (https://stackoverflow.com/questions/24099404/numpy-array-iadd-and-repeated-indices)
However the A is a scipy sparse matrix.
**Describe the solution you'd like**
scipy should implement these features like numpy
(https://numpy.org/doc/stable/reference/generated/numpy.ufunc.at.html)
and B could be either scipy sparse or numpy array.
**Describe alternatives you've considered**
I could transfer my sparse matrix into numpy array and use np.add.at
or write something like in (https://stackoverflow.com/questions/38013778/is-there-any-numpy-group-by-function)
and add these value literally
**Additional context (e.g. screenshots)**
No

**Comment by perimosocordiae** [comment]
Self-contained example from the SO question:

```python
A = np.array([0, 0, 0])
idx = [0, 0, 1, 1, 2, 2]
B = np.array([1, 1, 1, 1, 1, 1])
A[idx] += B  # results in [1, 1, 1], but wanted [2, 2, 2].
np.add.at(A, idx, B)  # results in [2, 2, 2].
```

The sparse version that works today could look like:

```python
A = scipy.sparse.coo_matrix((1, 3))  # all zeros
idx = [0, 0, 1, 1, 2, 2]
B = np.array([1, 1, 1, 1, 1, 1])
B_sparse = scipy.sparse.coo_matrix((B, (np.zeros_like(idx), idx)), shape=A.shape)
A + B_sparse  # results in [2, 2, 2] as a sparse matrix
```

This works because COO and other sparse formats already support construction with duplicate indices, and values at duplicate indices are summed automatically.

Does this solve your issue?

**Comment by disadone** [comment]
A little bit complex, but solve my problem. Thanks!
