### ISSUE TITLE
linalg.qr_update - is there a reason to limit the size of the update?

### ISSUE THREAD

**Issue by samuelstjean** [scipy/scipy#12657]
The QR update function only allows passing N vectors at the same time, with N the rank of QR (see here https://github.com/scipy/scipy/blob/master/scipy/linalg/_decomp_update.pyx.in#L2243)

It would be useful to pass more vectors if allowed as I'm not sure this is a real restriction. Or at the very least we can work around it / I have no clue what I am doing.

**Describe the solution you'd like**

Passing K vectors at once, with k > rank(QR)

**Describe alternatives you've considered**

Looping on it by hand, it works but probably slower than needed, saves a lot of memory at least as I'd like to use bigger matrices than in my small example.

**Additional context (e.g. screenshots)**
Example
~~~python
import numpy as np 
from scipy.linalg import qr, qr_update 

matrix = np.arange(1000).reshape(100,10).astype(np.float64) / 1000

AtA = np.dot(matrix.T, matrix)
Qfull, Rfull = qr(AtA)

# Check that our QR works
print(np.abs(np.dot(Qfull, Rfull) - AtA).max())

# Poor man iterative QR 
size = matrix.shape[1]

for idx in range(0, matrix.shape[0], size):
    part = matrix[slice(idx, idx+size)]

    if idx == 0:
        Q, R = qr(np.dot(part.T, part), overwrite_a=True)
    else:
        Q[:], R[:] = qr_update(Q, R, part.T, part.T, overwrite_qruv=True)

# Check that our iterative QR works
print(np.abs(np.dot(Q, R) - AtA).max())


# Poor man iterative QR, but with larger size, is not allowed?
size = 20

for idx in range(0, matrix.shape[0], size):
    part = matrix[slice(idx, idx+size)]

    if idx == 0:
        Q, R = qr(np.dot(part.T, part), overwrite_a=True)
    else:
        Q[:], R[:] = qr_update(Q, R, part.T, part.T, overwrite_qruv=True)
~~~

which gives 

~~~python
2.1316282072803006e-14
9.237055564881302e-14
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-ea192aaf9aa6> in <module>
     34         Q, R = qr(np.dot(part.T, part), overwrite_a=True)
     35     else:
---> 36         Q[:], R[:] = qr_update(Q, R, part.T, part.T, overwrite_qruv=True)

_decomp_update.pyx in scipy.linalg._decomp_update.qr_update()

ValueError: Update rank larger than np.dot(Q, R).
~~~

I'm not sure if I am doing it wrong or if there is a real (linear algebra) reason to limit the update size (or complicated implementation details).

**Comment by ilayn** [comment]
I am not sure I understand your motivation behind this. But update is meant to be a low-rank addition to the original matrix without re-decomposing the whole array so pictorially something like this. 

```
[                       ]       [            ] [                       ]
[                       ]       [            ] [                       ]
[                       ]   +  [            ]
[                       ]       [            ]
[                       ]       [            ]
```

If your update is of rank n or higher (I don't know how that can be) then it is better to recompute QR of the sum. So it's not the update vectors as if in a queue but they are the update arrays.

**Comment by samuelstjean** [comment]
Ah then what I'd want is indeed to do k rank one updates, and not one update of rank k, guess I'd read it wrongly.
Then you'd get a cheap way of building matrices which are say coming from an online feed or something too huge to be manipulated at once, but which can be cheaply updated, that's kind of the idea I am trying here.

**Comment by ilayn** [comment]
Then poor man has a golden heart because what you have as a loop is quite OK. Maybe another option is to wait for `n` elements and compute full QRs while it is building up if the item arrival speed is too high.

**Comment by samuelstjean** [comment]
It's ok, but I can probably do better indeed by batching more stuff together when for an n x m problem you have n >> m. 
Adding an option specifically to process b batches of k-rank updates might be too problem specific to be worth it here as a new implementation / change of function signature, but I can probably do it myself by hand down in C/cython so it's not necessarily a big deal for me if it's considered a terrible idea.

**Comment by ilayn** [comment]
It's not terrible but very specific use case. Updates in succession and storing the successor elements in another array seems like the obvious way to go. I don't you would get any speed updates since both slicing an array and qr update are done at C/Cython level. The only overhead you have is the python for loop but compared to the actual update complexity that should not matter.

**Comment by samuelstjean** [comment]
That's also what I thought, but I'll probably be doing a cartesian product over a whole bunch of stuff yielding lots of arrays to add together, but yes the linear algebra should dwarf those costs hopefully (worse I'll just numba it or something even). 
I guess it could be closed as too domain specific for an improvement then, I'm not really sure of the overheads of everything though, but the important parts are kind of optimized already anyway (not sure if jit compilation with the loops would improve it, knowing that in advance is above my paygrade).

**Comment by ilayn** [comment]
I'll close this but please feel free to comment further if need be.
