### ISSUE TITLE
print("peak_heights",properties['peak_heights']) KeyError: 'peak_heights'

### ISSUE THREAD

**Issue by paris007** [scipy/scipy#12661]
My issue is about the find_peak function. 

#### Reproducing code example:

```
peaks, properties = find_peaks(s, distance=2*sampling_frequency, width= .8 *sampling_frequency) 
print("peak_heights",properties['peak_heights'])
```

#### Error message:

```
print("peak_heights",properties['peak_heights'])
KeyError: 'peak_heights'
  ...
```

**Comment by sethtroisi** [comment]
Can you provide a full repro script? It's hard to know what went wrong from this code snippet.

**Comment by WarrenWeckesser** [comment]
The `properties` dictionary only contains the key `peak_heights` if the argument `height` was given (and the value was not None).

**Comment by paris007** [comment]
Thank you WarrenWeckesser. The issue is resolved.
