### ISSUE TITLE
Truncnorm PPF returns unexpected result

### ISSUE THREAD

**Issue by hardianlawi** [scipy/scipy#12678]
My issue is about how the truncnorm is outputting value that is outside of the bounds `a` and `b`

#### Reproducing code example:

```
from scipy.stats import truncnorm

truncnorm.ppf(0.218418, 50, 150, loc=100, scale=25) # 1350.1231623133476
```

I would expect the result to be:

```
from scipy.stats import norm

def truncnorm_ppf(p, a, b, loc, scale):
    lower_p = norm.cdf(a, loc=loc, scale=scale)
    upper_p = norm.cdf(b, loc=loc, scale=scale)
    pp = lower_p + p *(upper_p - lower_p)
    return norm.ppf(pp, loc=loc, scale=scale)

truncnorm_ppf(0.218418, 50, 150, loc=100, scale=25) # 81.62995089159442
```

#### Scipy/Numpy/Python version information:

```
1.5.2 1.19.1 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
```

**Comment by ewmoore** [comment]
The [documentation](https://docs.scipy.org/doc/scipy-1.5.2/reference/generated/scipy.stats.truncnorm.html#scipy.stats.truncnorm) says: 

> The probability density above is defined in the “standardized” form. To shift and/or scale the distribution use the loc and scale parameters. Specifically, truncnorm.pdf(x, a, b, loc, scale) is identically equivalent to truncnorm.pdf(y, a, b) / scale with y = (x - loc) / scale. 

So you need to use `truncnorm.ppf(0.218418, (50-100)/25, (150-100)/25, loc=100, scale=25)`

**Comment by hardianlawi** [comment]
Gotcha. Yeah, I found that part a bit confusing. Thanks for the reply!
