### ISSUE TITLE
using scipy.optimize.least_squares when already evaluated many values

### ISSUE THREAD

**Issue by jackureu** [scipy/scipy#12681]
I'm using scipy.optimize.least_squares to optimize my function `func`

The challenge I have is that I already evaluated this function in many input X values and have their corresponding Y values.
I want to somehow "input" that into the the `least_squares` function and allow it to use this information, so it can achieve a better result.

P.S I'm using method="dogbox"

**Comment by ilayn** [comment]
You can try to add a memoization functionality to your function If the values you are giving to your function is exactly what you have in the lookup table. Have a look at this post to get a rough idea; https://stackoverflow.com/questions/1988804/

This is not related to `optimize` code itself so I will close it but please feel free to continue the discussion as you wish.

**Comment by jackureu** [comment]
Memoization will only help if these are the EXACT values. Since I use floating point, it's never the case

**Comment by ilayn** [comment]
So how do you plan to use the readily made values in any case ? Interpolation?

**Comment by jackureu** [comment]
I intend the optimizer to user that as extra information about the way my function looks and improve the way it tries to optimize.

**Comment by ilayn** [comment]
Yes but I don't know how it can do that. Interpolation or curve fitting or something else?

**Comment by jackureu** [comment]
The  basic (over-simplified)logic of any optimization function is:

```
def smart_optimize(func):
  current_values = {}
  while True:
    next_position = find_next_position_to_evaluate(current_values)
    value = func(value)
    current_values[next_position] = value
    if some_stop_condition(current_values):
      return best_value
```

My goal is to start with `current_values` already populated with some information that I have

**Comment by ev-br** [comment]
The short answer is that there is no ready-made algorithm implemented in scipy.optimize that can use this information. You'll need to cook up your own routine for this.
