### ISSUE TITLE
scipy.optimize.fminbound, numpy depreciation warning Creating an ndarray from ragged nested sequences

### ISSUE THREAD

**Issue by YannLePoul** [scipy/scipy#12696]
When using the function `scipy.optimize.fminbound`, I get the following warning:
```
Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
```

I tracked down the message to this line:
https://github.com/scipy/scipy/blob/28d4244b6f5c1543755e586f27f9261d0f84153b/scipy/optimize/optimize.py#L1976

It seems that `np.maximum` should be used instead of `np.max` here anyway !

A minimal example:
```
from scipy import optimize
import numpy as np
optimize.fminbound(lambda x: np.array([x**2]), -np.pi, np.pi, disp=False)
```

Versions:
`scipy: 1.5.0   numpy: 1.19.1   sys: sys.version_info(major=3, minor=6, micro=10, releaselevel='final', serial=0)`

**Comment by andyfaff** [comment]
Do you have a minimal working example that demonstrates the issue? Otherwise it's difficult to provide a fix.

**Comment by YannLePoul** [comment]
Yep, I've edited the issue
