### ISSUE TITLE
interp1d issue when trying to fill for values outsite of the data range

### ISSUE THREAD

**Issue by elea98** [scipy/scipy#12707]
The interpolate.interp1d() function with `kind='previous'` does not work when called for values outside the data range. 
According to the documentation, if no value is given for `fill_value`, the outside values should be set to Nan and if a value or tuple of values are given, they should be used to fill the values outside the data range. However, when trying these two techniques, I get an error message. The only way I can make this work on data with values outside the data range is by setting `fill_value='extrapolate'`.

#### Reproducing code example:

```
f = interpolate.interp1d([3,4,5,6], [1,1,1,1], kind='previous', assume_sorted=True, fill_value=(0,5))
#This should fill all values below data range with 0 and above with 5. 
f([0,1,2,3,7])

f = interpolate.interp1d([3,4,5,6], [1,1,1,1], kind='previous', assume_sorted=True)
#This should fill all values outside data range with Nan
f([0,1,2,3,7])
```

#### Error message:

```
  ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-98-9b5aec5b236e> in <module>
----> 1 f([0,1,2,3,7])

/usr/local/lib/sancare/python/venv/ml-dev/lib/python3.7/site-packages/scipy/interpolate/polyint.py in __call__(self, x)
     77         """
     78         x, x_shape = self._prepare_x(x)
---> 79         y = self._evaluate(x)
     80         return self._finish_y(y, x_shape)
     81 

/usr/local/lib/sancare/python/venv/ml-dev/lib/python3.7/site-packages/scipy/interpolate/interpolate.py in _evaluate(self, x_new)
    661         y_new = self._call(self, x_new)
    662         if not self._extrapolate:
--> 663             below_bounds, above_bounds = self._check_bounds(x_new)
    664             if len(y_new) > 0:
    665                 # Note fill_value must be broadcast up to the proper size

/usr/local/lib/sancare/python/venv/ml-dev/lib/python3.7/site-packages/scipy/interpolate/interpolate.py in _check_bounds(self, x_new)
    690         # !! Could provide more information about which values are out of bounds
    691         if self.bounds_error and below_bounds.any():
--> 692             raise ValueError("A value in x_new is below the interpolation "
    693                              "range.")
    694         if self.bounds_error and above_bounds.any():

ValueError: A value in x_new is below the interpolation range.
```

#### Scipy/Numpy/Python version information:

```
1.4.1 1.18.5 sys.version_info(major=3, minor=7, micro=5, releaselevel='final', serial=0)
```

Note: I have also reproduced this bug on version 1.5.2 of scipy and it gave the exact same error message

**Comment by ev-br** [comment]
You need to set `bounds_error=False` explicitly:

```
In [22]: kinds = ['linear', 'previous', 'next', 3]                                                     

In [23]: for kind in kinds: 
    ...:     fl = interp1d([3,4,5,6], [1,1,1,1], kind=kind, fill_value=(0, 42), bounds_error=False) 
    ...:     print(kind, fl(0), fl(8)) 
    ...:                                                                                               
linear 0.0 42.0
previous 0.0 42.0
next 0.0 42.0
3 0.0 42.0
```

**Comment by elea98** [comment]
Sure, I will do it right now!

**Comment by V0lantis** [comment]
Actually, it is already written in the doc : 

> bounds_error : bool, optional
        If True, a ValueError is raised any time interpolation is attempted on
        a value outside of the range of x (where extrapolation is
        necessary). If False, out of bounds values are assigned `fill_value`.
        By default, an error is raised unless ``fill_value="extrapolate"``.
What could we add @ev-br ?

**Comment by ev-br** [comment]
So you're saying it's plenty clear already? This trips beginners on a fairly regular basis, so there does seem to be some room for improvement. And this improvement is likely best done by someone who just figured it out:  they're best positioned to judge what would have been most helpful for them.

**Comment by ev-br** [comment]
OK, no movement for a while, and the last report is that it's already covered by the existing docs. Closing. If someone comes with a better wording, a pull request is always welcome. Thanks @elea98 for the report, @V0lantis for the clarification.
