### ISSUE TITLE
Request for finding derivatives at multiple points when using interpolation functions.

### ISSUE THREAD

**Issue by yash-2209** [scipy/scipy#12714]
I am trying to find derivatives of an interpolated function using _scipy.interpolate.UnivariateSpline_.
However, the _derivatives_ function only provides the derivative at one point. ([example](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.UnivariateSpline.derivatives.html#scipy.interpolate.UnivariateSpline.derivatives))
I want to compute the derivative at multiple points, as calling derivative at each point seems to be inefficient.
If you could create a function that takes a numpy array as input **x** and provide an output array representing derivatives, that would be very much helpful. (Somewhat similar to how **spalde** works).

For now what I try to do is use:
```
spl = scipy.interpolate.UnivariateSpline(x,y)
scipy.interpolate.spalde(x2, spl._eval_args)
```
Also I just wanted to confirm that the above implementation for finding derivatives at multiple points is correct?

Thanks

**Comment by andyfaff** [comment]
You need to use
```
dydx=spl.derivatives(x)

# or
dspl = spl.derivative(1)
dydx = dspl(x)
```
