### ISSUE TITLE
calling not callable np.ndarray

### ISSUE THREAD

**Issue by KalinStoyanov** [scipy/scipy#12718]
My issue is about calling not callable np.ndarray 

#### Reproducing code example:

```
# -*- coding: utf-8 -*-
"""
Created on Wed Aug  5 12:06:16 2020

@author: Kalin Stoyanov
"""
import numpy as np
# import pandas as pd
from scipy.special import expit #sigmoid activation function
from scipy.spatial import distance
from scipy.optimize import dual_annealing

def activation(w,x,i,nMax,nX, nL ,wL ,nY):
    W=wW(w,nX, nL ,wL ,nY)
    y=expit(x.dot(W[i])) #sigmoid activation function
    if i>=nMax:
        return y
    else:
        return activation(w,y,i+1,nMax,nX, nL ,wL ,nY)

def xy(x_):
    x = np.array([x_[1:]])
    y_ = x_[0]
    y=np.array([np.zeros(10)])
    y[0,int(round(y_))]=1.0
    return x,y

def wW(w,nX, nL ,wL ,nY):

    W0_ = w[:W0_size]
    W0 = W0_.reshape((nX,wL))
    Wj_= w[W0_size:W0_size+Wj_size]
    Wj = Wj_.reshape((nL-1,wL,wL))
    Wn_ = w[(W0_size+Wj_size):]
    Wn = Wn_.reshape((wL,nY)) 
    W=[W0]
    for i in np.arange(Wj.shape[0]):
        W.append(Wj[i])
    W.append(Wn)
    return W

nX = 784 # number of factors (features)
nL=3 # number of layers
wL = 12 # number of nodes per layer
nY = 10 # number of responses
W0_size = nX*wL
Wj_size = (nL-1)*(wL**2)
Wn_size = wL*nY    

np.random.seed(1)
w = (np.random.rand(W0_size+Wj_size+Wn_size)-0.5)/2
dimension = w.size

lw = [-1] * dimension
up = [1] * dimension

x = np.array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   3.,  18.,
         18.,  18., 126., 136., 175.,  26., 166., 255., 247., 127.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         30.,  36.,  94., 154., 170., 253., 253., 253., 253., 253., 225.,
        172., 253., 242., 195.,  64.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,  49., 238., 253., 253., 253., 253.,
        253., 253., 253., 253., 251.,  93.,  82.,  82.,  56.,  39.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         18., 219., 253., 253., 253., 253., 253., 198., 182., 247., 241.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,  80., 156., 107., 253.,
        253., 205.,  11.,   0.,  43., 154.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,  14.,   1., 154., 253.,  90.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
        139., 253., 190.,   2.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,  11., 190., 253.,  70.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,  35., 241., 225., 160., 108.,   1.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  81., 240.,
        253., 253., 119.,  25.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,  45., 186., 253., 253., 150.,  27.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,  16.,  93., 252., 253., 187.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 249., 253.,
        249.,  64.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,  46., 130., 183., 253., 253., 207.,   2.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,  39., 148., 229., 253., 253., 253.,
        250., 182.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  24., 114.,
        221., 253., 253., 253., 253., 201.,  78.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,  23.,  66., 213., 253., 253., 253., 253., 198.,  81.,
          2.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,  18., 171., 219., 253., 253.,
        253., 253., 195.,  80.,   9.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  55.,
        172., 226., 253., 253., 253., 253., 244., 133.,  11.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0., 136., 253., 253., 253., 212., 135.,
        132.,  16.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.]])

func=activation(w,x,0,nL,nX, nL ,wL ,nY)
ret = dual_annealing(func, bounds=list(zip(lw, up)), seed=1234, x0=w)
print(ret.func)
print(ret.w)

```

#### Error message:

```
Traceback (most recent call last):

  File "C:\Users\Kalin Stoyanov\OneDrive\0Papers\1NN\composite loss function\code\gMLP v5 bug report.py", line 138, in <module>
    ret = dual_annealing(func, bounds=list(zip(lw, up)), seed=1234, x0=w)

  File "C:\Users\Kalin Stoyanov\Anaconda3\lib\site-packages\scipy\optimize\_dual_annealing.py", line 631, in dual_annealing
    energy_state.reset(func_wrapper, rand_state, x0)

  File "C:\Users\Kalin Stoyanov\Anaconda3\lib\site-packages\scipy\optimize\_dual_annealing.py", line 171, in reset
    self.current_energy = func_wrapper.fun(self.current_location)

  File "C:\Users\Kalin Stoyanov\Anaconda3\lib\site-packages\scipy\optimize\_dual_annealing.py", line 373, in fun
    return self.func(x, *self.args)

TypeError: 'numpy.ndarray' object is not callable```

#### Scipy/Numpy/Python version information:
<!-- You can simply run the following and paste the result in a code block
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.5.0 1.18.5 sys.version_info(major=3, minor=7, micro=7, releaselevel='final', serial=0)
```
-->

**Comment by ilayn** [comment]
This line

```python
func=activation(w,x,0,nL,nX, nL ,wL ,nY)
```

makes `func` an array not a callable. You need to pass it as `func=activation`.

**Comment by KalinStoyanov** [comment]
Thank you for the answer.

I changed the lines accordingly, but I still have exactly the same result. 

I don't know whether it is important, but the function _**activation**_ is a recursive one. 

Btw I am newbie, so please excuse any naive mistakes. 

Here is the code.

`
import numpy as np
from scipy.special import expit
from scipy.optimize import dual_annealing

def activation(w,x,i,nMax,nX, nL ,wL ,nY):
    W=wW(w,nX, nL ,wL ,nY)
    y=expit(x.dot(W[i])) #sigmoid activation function
    if i>=nMax:
        return y
    else:
        return activation(w,y,i+1,nMax,nX, nL ,wL ,nY)

def xy(x_):
    x = np.array([x_[1:]])
    y_ = x_[0]
    y=np.array([np.zeros(10)])
    y[0,int(round(y_))]=1.0
    return x,y

def wW(w,nX, nL ,wL ,nY):
    W0_ = w[:W0_size]
    W0 = W0_.reshape((nX,wL))
    Wj_= w[W0_size:W0_size+Wj_size]
    Wj = Wj_.reshape((nL-1,wL,wL))
    Wn_ = w[(W0_size+Wj_size):]
    Wn = Wn_.reshape((wL,nY)) 
    W=[W0]
    for i in np.arange(Wj.shape[0]):
        W.append(Wj[i])
    W.append(Wn)
    return W

nX = 784 # number of factors (features)
nL=3 # number of layers
wL = 12 # number of nodes per layer
nY = 10 # number of responses
W0_size = nX*wL
Wj_size = (nL-1)*(wL**2)
Wn_size = wL*nY    

np.random.seed(1)
w = (np.random.rand(W0_size+Wj_size+Wn_size)-0.5)/2
dimension = w.size

lw = [-1] * dimension
up = [1] * dimension

x = np.array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   3.,  18.,
         18.,  18., 126., 136., 175.,  26., 166., 255., 247., 127.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         30.,  36.,  94., 154., 170., 253., 253., 253., 253., 253., 225.,
        172., 253., 242., 195.,  64.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,  49., 238., 253., 253., 253., 253.,
        253., 253., 253., 253., 251.,  93.,  82.,  82.,  56.,  39.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         18., 219., 253., 253., 253., 253., 253., 198., 182., 247., 241.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,  80., 156., 107., 253.,
        253., 205.,  11.,   0.,  43., 154.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,  14.,   1., 154., 253.,  90.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
        139., 253., 190.,   2.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,  11., 190., 253.,  70.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,  35., 241., 225., 160., 108.,   1.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  81., 240.,
        253., 253., 119.,  25.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,  45., 186., 253., 253., 150.,  27.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,  16.,  93., 252., 253., 187.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 249., 253.,
        249.,  64.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,  46., 130., 183., 253., 253., 207.,   2.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,  39., 148., 229., 253., 253., 253.,
        250., 182.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  24., 114.,
        221., 253., 253., 253., 253., 201.,  78.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,  23.,  66., 213., 253., 253., 253., 253., 198.,  81.,
          2.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,  18., 171., 219., 253., 253.,
        253., 253., 195.,  80.,   9.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  55.,
        172., 226., 253., 253., 253., 253., 244., 133.,  11.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0., 136., 253., 253., 253., 212., 135.,
        132.,  16.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.]])

ret = dual_annealing(func=activation(w,x,0,nL,nX, nL ,wL ,nY), bounds=list(zip(lw, up)), seed=1234, x0=w)
"""
the same with
ret = dual_annealing(activation(w,x,0,nL,nX, nL ,wL ,nY), bounds=list(zip(lw, up)), seed=1234, x0=w)
"""
print(ret.func)
print(ret.w)
`
### Here is the error message

`Traceback (most recent call last):

  File "C:\Users\Kalin Stoyanov\OneDrive\0Papers\1NN\composite loss function\code\gMLP v5 bug report.py", line 137, in <module>
    ret = dual_annealing(func=activation(w,x,0,nL,nX, nL ,wL ,nY), bounds=list(zip(lw, up)), seed=1234, x0=w)

  File "C:\Users\Kalin Stoyanov\Anaconda3\lib\site-packages\scipy\optimize\_dual_annealing.py", line 631, in dual_annealing
    energy_state.reset(func_wrapper, rand_state, x0)

  File "C:\Users\Kalin Stoyanov\Anaconda3\lib\site-packages\scipy\optimize\_dual_annealing.py", line 171, in reset
    self.current_energy = func_wrapper.fun(self.current_location)

  File "C:\Users\Kalin Stoyanov\Anaconda3\lib\site-packages\scipy\optimize\_dual_annealing.py", line 373, in fun
    return self.func(x, *self.args)

TypeError: 'numpy.ndarray' object is not callable`

**Comment by ilayn** [comment]
You need to provide the function to be called not the result of the function. Now `activation(w,x,0,nL,nX, nL ,wL ,nY)` is a numpy array because it is evaluated already with those arguments. And you are pushing it to `func`  and then optimization algorithm is trying to call it which is not callable. 

In simpler terms, `sin(x)` is a number `sin` is the function. You need to provide a function not a number.

**Comment by KalinStoyanov** [comment]
but when I put 
`ret = dual_annealing(activation, bounds=list(zip(lw, up)), seed=1234, x0=w)`
the error message is 
`TypeError: activation() missing 7 required positional arguments: 'x', 'i', 'nMax', 'nX', 'nL', 'wL', and 'nY'`

Apparently I miss something.
