### ISSUE TITLE
Misleading scipy.signal.get_window() docstring with 'exponential' window

### ISSUE THREAD

**Issue by jimmy60504** [scipy/scipy#12719]
My issue is about the [scipy.signal.get_window()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.get_window.html) docstring:

```
Window types:
...
exponential (needs decay scale)
```

This leads to set the `window` parameter as `('exponential', tau)`, but it raise an error that is hard to understand. 

#### Reproducing code example:

```
scipy.signal.get_window(('exponential', 1.), 9)
```

#### Error message:

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    scipy.signal.get_window(('exponential', 1.), 9)
  File "/usr/local/lib/python3.6/dist-packages/scipy/signal/windows/windows.py", line 2124, in get_window
    return winfunc(*params)
  File "/usr/local/lib/python3.6/dist-packages/scipy/signal/windows/windows.py", line 1699, in exponential
    raise ValueError("If sym==True, center must be None.")
ValueError: If sym==True, center must be None.
```

Because [scipy.signal.windows.exponential()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.windows.exponential.html#scipy.signal.windows.exponential) has `center` in the second parameter, so turns out it needs to be `('exponential', center, tau)` and `center` must be **None**.

####  Example:
```
scipy.signal.get_window(('exponential', None, 1.), 9)
```
#### Results:
```
[0.011109   0.03019738 0.082085   0.22313016 0.60653066 0.60653066
 0.22313016 0.082085   0.03019738]
```

#### Possible solutions:

1. Move `tau` into the second parameter in [scipy.signal.windows.exponential()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.windows.exponential.html#scipy.signal.windows.exponential), but this will be a breaking change to the API.
2. Change the docstring into `exponential (needs center, decay scale)` to indicate the `center` parameter.
3. Add an example for `exponential` to show that more then two parameters can be passed into the tuple.

#### Scipy/Numpy/Python version information:

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.4.1 1.18.5 sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
```

**Comment by larsoner** [comment]
Agreed (1) is too backward-incompatible, would you be up for adding (2) and if you want (3)?

**Comment by jimmy60504** [comment]
I think add both (2) and (3) will be great.
