### ISSUE TITLE
setup_requires is vestigial

### ISSUE THREAD

**Issue by kousu** [scipy/scipy#12727]
There's some old code in the install script which is supposed to make sure all the build requirements exist:

https://github.com/scipy/scipy/blob/2ed8169c5c4c9181cd38a52db614c692eb802c15/setup.py#L508-L524

This was added to address https://github.com/scipy/scipy/issues/3379.

The same issue exists/existed for:

* https://github.com/nilearn/nistats/issues/154
* https://github.com/scikit-learn/scikit-learn/issues/4164 (they ended up adopting your code: https://github.com/scikit-learn/scikit-learn/issues/4164#issuecomment-76982101)
* https://github.com/scikit-learn/scikit-learn/issues/4164#issuecomment-71550942
* https://github.com/apple/turicreate/issues/642

However it doesn't seem to work anymore:

```
[kousu@laptop scipy]$ python -m virtualenv ../venv
created virtual environment CPython3.8.5.final.0-64 in 365ms
  creator CPython3Posix(dest=/home/kousu/src/neuropoly/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/kousu/.local/share/virtualenv/seed-app-data/v1.0.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
[kousu@laptop scipy]$ . ../venv/bin/activate
(venv) [kousu@laptop scipy]$ python setup.py install

Note: if you need reliable uninstall behavior, then install
with pip instead of using `setup.py install`:

  - `pip install .`       (from a git repo or downloaded source
                           release)
  - `pip install scipy`   (last SciPy release on PyPI)


Traceback (most recent call last):
  File "setup.py", line 590, in <module>
    setup_package()
  File "setup.py", line 565, in setup_package
    from numpy.distutils.core import setup
ModuleNotFoundError: No module named 'numpy'
```

`pip` works

```
(venv) [kousu@laptop scipy]$ pip install .
Processing /home/kousu/src/neuropoly/scipy
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ...
```

because you have https://github.com/scipy/scipy/blob/2ed8169c5c4c9181cd38a52db614c692eb802c15/pyproject.toml.

It seems like you're maintaining the build dependencies in two places: setup.py, where they're not being maintained, and pyproject.toml. I want to remove them from setup.py.

---

I don't really understand what happened. Did setuptools used to work differently? It looks to me like

https://github.com/scipy/scipy/blob/2ed8169c5c4c9181cd38a52db614c692eb802c15/setup.py#L564-L565

always runs before setup() has a chance to even see `setup_requires`. You have that `run_build` flag to prevent running that code if numpy isn't installed yet, but it's not doing its job. I want to get rid of that too.

---

https://github.com/scikit-image/scikit-image/issues/4919 is the same issue. And they have the same problem: their setup.py unconditionally imports `numpy.distutils` before setup() has a chance to run to install build deps. I guess that's why https://www.python.org/dev/peps/pep-0517/ exists, because specifying build deps inside of setup.py is fraught.

**Comment by ilayn** [comment]
Yes basically what you wrote in the very last sentence.

**Comment by rgommers** [comment]
If that `setup_requires` stuff doesn't work anymore, it's probably due to changes in `setuptools` now that that incorporates `distutils`. I'd expect it to work for `setuptools < 0.49`.

I think removing `setup_requires` is a good idea, because that invokes `easy_install` and now that there's a good alternative (`pip` using `pyproject.toml`) there's no need for that anymore.

Removing `setup.py install` or other regularly used commands isn't a good idea (yet), because that will break people's workflow and `pip` isn't the best option for everything (especially development related activities).

**Comment by kousu** [comment]
On August 15, 2020 3:56:04 PM EDT, Ralf Gommers <notifications@github.com> wrote:
>Removing `setup.py install` or other regularly used commands isn't a
>good idea (yet), because that will break people's workflow and `pip`
>isn't the best option for everything (especially development related
>activities).

Cool. I can get behind this. 🍃

**Comment by kousu** [comment]
Alright new day new PR: https://github.com/scipy/scipy/pull/12729

**Comment by rgommers** [comment]
This was fixed in gh-12728, closing.
