### ISSUE TITLE
find_peaks_cwt has undocumented behavior when window_size is None and wavelet is ricker

### ISSUE THREAD

**Issue by hdkire** [scipy/scipy#12739]
From the documentation for find_peaks_cwt (window_size):
> Size of window to use to calculate noise floor. Default is cwt.shape[1] / 20.

However, when window_size is None and wavelet = ricker (default for find_peaks_cwt) this will also
trigger special case handing in scipy.signal.wavelets.cwt:
```
 if wavelet == ricker and window_size is None:
     ceil = np.ceil(N)
     if ceil != N:
         N = int(N)
```
which affects the output with my supplied input: [input.txt](https://github.com/scipy/scipy/files/5094980/input.txt).
So, in the end the result from find_peaks_cwt differs between when window_size is None and cwt.shape[1] / 20.

#### Reproducing code example:

```
>>> import json
>>> import numpy as np
>>> from scipy import signal
>>> vector = np.array(json.load(open('input.txt')))  # Attached file
>>> widths = np.linspace(1, 265)
>>> signal.find_peaks_cwt(vector, widths)
array([  22,  436,  868, 1299, 1732, 2164, 2596, 3028, 3459, 3892, 4324, 4756, 5189, 5620, 6052, 6484, 6916, 7349, 7780, 8212, 8625])
# window_size gets computed in _filter_ridge_lines to 433
>>> window_size = int(np.ceil(len(vector) / 20))
# Now, I supply this computed window_size:
>>> signal.find_peaks_cwt(vector, widths, window_size=window_size)
array([  23,  436,  868, 1300, 1732, 2164, 2596, 3028, 3460, 3892, 4325, 4757, 5189, 5621, 6053, 6485, 6917, 7349, 7781, 8213, 8626])
```

#### Scipy/Numpy/Python version information:
```
1.5.2 1.17.5 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment]
@lagru Care to have a look?

**Comment by lagru** [comment]
@ilayn I've never worked with `find_peaks_cwt`; perhaps you were thinking of `find_peaks`? :wink: If I find the time I might have a look anyway, no promises though.

**Comment by ilayn** [comment]
Today I am exceptionally stupid. Happened a few times with other PRs too. Sorry for that. I'll fill the bathtub with coffee.

**Comment by hdkire** [comment]
FWIW, when running on scipy 1.4.1, calling `signal.find_peaks_cwt(vector, widths)` produces the exact same result as calling `signal.find_peaks_cwt(vector, widths, window_size=window_size)` does for scipy 1.5.2. And therefore the result of calling  `signal.find_peaks_cwt(vector, widths)` is not the same in 1.4.1 as in 1.5.2 - with the provided example data.

The following commit seems to have introduced the change: https://github.com/scipy/scipy/commit/fd966a4007eac55e92683999452431c84d5aaa28 .

**Comment by tylerjereddy** [comment]
I remember doing that one--it was very tricky to fix. If another fix is proposed, and you want it backported, please do make sure it works for the described case "32-bit setup + NumPy <= 1.14.5," which may not be tested by regular repo CI.

**Comment by tylerjereddy** [comment]
For the `1.6.0` release, I believe we may be dropping that NumPy version range, so just deleting the shim might be ok.
