### ISSUE TITLE
circstd doesn't handle R = hypot(S, C) > 1

### ISSUE THREAD

**Issue by belm0** [scipy/scipy#12740]
circstd runtime warning for valid input

#### Reproducing code example:
```
>>> from scipy.stats import circstd
>>> circstd([0.12675364631578953] * 10 + [0.12675365920187928] * 100 )
```

#### Error message:
```
RuntimeWarning: invalid value encountered in sqrt
  return ((high - low)/2.0/pi) * sqrt(-2*log(R))
nan
```

#### Scipy/Numpy/Python version information:
```
1.3.0 1.16.4 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment]
The value is not valid as it is not in the default range. Have a look at the documentation of [`circstd`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.circstd.html)

**Comment by belm0** [comment]
@ilayn ?  Default range is [0, 2*pi].  All the values are within that range.

**Comment by belm0** [comment]
If you aren't familiar with python array ops:

```python
>>> [0.12675364631578953] * 10
[0.12675364631578953, 0.12675364631578953, 0.12675364631578953, 0.12675364631578953, 0.12675364631578953, 0.12675364631578953, 0.12675364631578953, 0.12675364631578953, 0.12675364631578953, 0.12675364631578953]
```

**Comment by ilayn** [comment]
Pffff.... I need more coffee apparently. Sorry for the noise.
