### ISSUE TITLE
Pdf attribute in subclasses of rv_discrete

### ISSUE THREAD

**Issue by perepelart** [scipy/scipy#12741]
I really do not understand why subclasses of rv_discrete have attribute pdf according to call of standart python functions such as dir or hasattr.
Of course i can not use this method using instance of these subclasses (because i get an error) but how i can see in https://github.com/scipy/scipy/blob/55ba7c8432b8908f32632f8c3c1887b1af43425e/scipy/stats/_distn_infrastructure.py subclasses of rv_discrete do not have such attribute and only subclasses of rv_continuous have it. rv_generic does not provide even private implementation of pdf function. I know that instead of pdf function i must use pmf function using discrete random variates. But i can not get why do i obtain pdf attribute in list of attributes of any subclass of rv_discrete if rv_discrete, rv_generic and all subclasses like poisson do not implement this attribute.

#### Reproducing code example:

```
import scipy.stats as sts
poison_rv = sts.poisson(5)
has_pdf1 = 'pdf' in dir(poison_rv)
has_pdf2 = hasattr(poison_rv, 'pdf')
```
After these lines i have True in both "has_pdf1" and "has_pdf2" variables. And if sts.poisson is be replaced with any other subclass of rv_discrete than i get the same "True" value.
If i do

```
print(dir(poison_rv))
```
i see that poison_rv has the attribute pdf.
#### Scipy/Numpy/Python version information:
```
1.4.1 /  1.18.5 /  sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
```

**Comment by ev-br** [comment]
`sts.poisson(5)` creates a frozen distribution, and these have both pdf and pmf attributes:

https://github.com/scipy/scipy/blob/55ba7c8432b8908f32632f8c3c1887b1af43425e/scipy/stats/_distn_infrastructure.py#L435

So, it's a known wart. I'll close the issue, but of course feel free to discuss further.

**Comment by perepelart** [comment]
@ev-br Oh, i will read about frozen distributions, thank you for the answer!
