### ISSUE TITLE
ENH: interp1d Matlab compatibility

### ISSUE THREAD

**Issue by jarau-de** [scipy/scipy#12749]
**Is your feature request related to a problem? Please describe.**
Yes. I want to rewrite Matlab code in Python. Unfortunately the interp1d with 'nearest' is not fully compatible with Matlab interp1. Matlab rounds up and Scipy rounds down. If one wants to interpolate 1.5 between 1 and 2, Matlab gives you the value at 2 and Scipy gives you the value at 1. That's really a mess, if one expects same results.

**Describe the solution you'd like**
An additional parameter left/right or nearest_up/nearest_down

**Comment by ev-br** [comment]
Matching matlab is not a requirement. 

interp1d is already loaded with options. Maybe better introduce a new interpolation kind, "nearest-down" or some such. This route needs a champion :-).

The other route, of course, is to borrow the source into your user code,

https://github.com/scipy/scipy/blob/v1.5.2/scipy/interpolate/interpolate.py#L612

and adjust as needed.

**Comment by jarau-de** [comment]
Thanks for your fast reply.
You are right, Matlab is not an requirement. But in this case it would make thinks easier.

Yes, a new interpolation kind would be fine. In this case nearest-up, because nearest-down is already the default behavior.

**Comment by ev-br** [comment]
> As I understand this is a minor effort, because of the requested functionality is already there (searchsorted(x, y, side='right')). One needs to copy the existing code, change this little piece of code (left -> right) and introduce a new kind='nearest-up'.

A pull request would speed things up.
