### ISSUE TITLE
BUG: special: erfinv(y) is inaccurate for small abs(y).

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#12758]
`erfinv(y)` is implemented as `ndtri(0.5 * (y+1)) * NPY_SQRT1_2` (where `NPY_SQRT1_2` is `1/sqrt(2)`).  This limits the precision that can be obtained for small `abs(y)`, because for any `y` such that `abs(y)` is less than ~1e-16, `y + 1` is `1`.  So, for example, `erfinv(1e-20)` returns 0, but the correct result is `8.86226925452758e-21`:
```
In [45]: erfinv(1e-20)  # incorrect result                                                          
Out[45]: 0.0

In [46]: erf(8.86226925452758e-21)                                              
Out[46]: 1e-20
```
Octave and Boost return the correct value; we should too.

Octave:
```
octave:3> format long
octave:4> erfinv(1e-20)
ans =    8.86226925452758e-21
```
Boost
```
#include <iostream>
#include <boost/math/special_functions/erf.hpp>

using boost::math::erf_inv;
using namespace std;


int main()
{
    double p = 1e-20;
    double x = erf_inv(p);
    cout << scientific << setprecision(15) << x << endl;
    // 8.862269254527580e-21
}
```

**Comment by tylerjereddy** [comment]
I'm going to manually reopen since @WarrenWeckesser seemed interested in even more precision despite gh-12760
