### ISSUE TITLE
SVD is flaky on new laptop

### ISSUE THREAD

**Issue by richardsheridan** [scipy/scipy#12768]
I'm getting frequent `SVD did not converge` errors after changing machines from `curve_fit` in scipy 1.5.2 from pip on Windows 10 (version 2004). The same fit will have an unpredictable outcome, although I am using the same environment, code, and data copied bit for bit.

The error of course originates in the svd routine:

https://github.com/scipy/scipy/blob/d866f8342a1c0f1fb8175460e520ea264bca1ca5/scipy/linalg/decomp_svd.py#L125-L129

Both gesdd and gesvd are returning `info == 4`  _sometimes_ even while fitting the same data. The Jacobians I am dealing with have a condition number around 2000. Keep in mind the Jacobian svd always converges on the other machine with the same software. This does not happen on `conda` provided `scipy` with MKL blas.

Numpy config:
```
>>> np.show_config()
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
```
scipy config:
```
scipy.show_config()
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\scipy-wheels\\scipy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\scipy-wheels\\scipy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\scipy-wheels\\scipy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\scipy-wheels\\scipy\\build\\openblas_info']
```

I happen to use threadpoolctl so that provides some nice information about blas:
```
>>> threadpoolctl.threadpool_info()
[{'filepath': 'C:\\Users\\...\\miniconda3\\envs\\flaky\\Lib\\site-packages\\numpy\\.libs\\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll', 'prefix': 'libopenblas', 'user_api': 'blas', 'internal_api': 'openblas', 'version': '0.3.9.dev', 'num_threads': 8, 'threading_layer': 'pthreads'}, {'filepath': 'C:\\Users\\...\\miniconda3\\envs\\flaky\\Lib\\site-packages\\scipy\\.libs\\libopenblas.3HBPCJB5BPQGKWVZAVEBXNNJ2Q2G3TUP.gfortran-win_amd64.dll', 'prefix': 'libopenblas', 'user_api': 'blas', 'internal_api': 'openblas', 'version': '0.3.9', 'num_threads': 8, 'threading_layer': 'pthreads'}]
```
Might be related to hardware somehow so I've dumped the output of HWiNFO64
[dell (flaky).LOG](https://github.com/scipy/scipy/files/5124596/dell.flaky.LOG)
[lenovo (stable).LOG](https://github.com/scipy/scipy/files/5124597/lenovo.stable.LOG)

And here is a test jacobian that failed: (it doesn't fail every time)
[jacobian.zip](https://github.com/scipy/scipy/files/5125213/jacobian.zip)

**Comment by ilayn** [comment]
If you are mixing miniconda and pip installations, this can happen. Especially, the numpy and the scipy in the threadpool line are quite different. Make sure that the installations are compatible and use either `conda` environment or `pip` but not both.

**Comment by charris** [comment]
Windows? What version? The 2004 (latest) version broke svg.

**Comment by richardsheridan** [comment]
@charris indeed 2004 (Microsoft Windows 10 Home (x64) Build 19041.450 (2004/May 2020 Update)).  Can you link any other issues related to this? also, would users be expecting a fix from scipy, openblas, or from Microsoft?

**Comment by ilayn** [comment]
Baah not that again...

**Comment by richardsheridan** [comment]
@ilayn Thanks I'll just follow that issue then
