### ISSUE TITLE
Finite Difference Hessian in Scipy Optimize Solvers (Newton-CG)

### ISSUE THREAD

**Issue by m-richards** [scipy/scipy#12785]
My issue is about using the '2-point' flag for the hessian in the second order optimization solvers.
The actual error I had (in my non-trivial example) was with the 'trust-ncg' method, but the minimal example below is with 'Newton-CG'.

The example error comes straight from the optimize section of the tutorial, I've just replaced the analytic hessian with '2-point'.

The crash is a result of the line prior to that in the traceback (below), ```curv = np.dot(psupi, Ap)``` which on paper should be p^TAp and hence a scalar, it ends up returning a 5*5 (dimensions of A)``` _SumLinearOperator```. Stepping through with a debugger seems to suggest that the result of ```np.dot()`` scales A by the first component of p, but I can't figure out how to check this - you don't seem to be able to cast LinearOperators to ordinary arrays.

#### Reproducing code example:

```
import numpy as np
from scipy.optimize import minimize

def rosen(x):
    """The Rosenbrock function"""
    return sum(100.0*(x[1:]-x[:-1]**2.0)**2.0 + (1-x[:-1])**2.0)

x0 = np.array([1.3, 0.7, 0.8, 1.9, 1.2])

def rosen_der(x):
    xm = x[1:-1]
    xm_m1 = x[:-2]
    xm_p1 = x[2:]
    der = np.zeros_like(x)
    der[1:-1] = 200*(xm-xm_m1**2) - 400*(xm_p1 - xm**2)*xm - 2*(1-xm)
    der[0] = -400*x[0]*(x[1]-x[0]**2) - 2*(1-x[0])
    der[-1] = 200*(x[-1]-x[-2]**2)
    return der

res = minimize(rosen, x0, method='Newton-CG',
               jac=rosen_der, hess='2-point',
               options={'xtol': 1e-8, 'disp': True})
print(res.x)
```

#### Error message:

```
Traceback (most recent call last):
  File "FPATH/newton_cg_fd_hessian_error_bug_report.py", line 22, in <module>
    options={'xtol': 1e-8, 'disp': True})
  File "FPATH\lib\site-packages\scipy\optimize\_minimize.py", line 615, in minimize
    **options)
  File "FPATH\lib\site-packages\scipy\optimize\optimize.py", line 1755, in _minimize_newtoncg
    if 0 <= curv <= 3 * float64eps:
TypeError: '<=' not supported between instances of 'int' and '_SumLinearOperator'
  ...
```

#### Scipy/Numpy/Python version information:

Version info: (Scipy, Numpy, python)
```
1.5.2 1.19.1 sys.version_info(major=3, minor=7, micro=7, releaselevel='final', serial=0)
```

**Comment by m-richards** [comment]
On reviewing the docs again  (https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize) later, this appears to be behavior as described. 

In this case I think the documentation could be a little clearer perhaps (admittedly I obviously did not read it super thoroughly on first glance). But it does seem a bit confusing to provide that clarification "Only for Newton-CG, dogleg, trust-ncg, trust-krylov, trust-exact and trust-constr." in the first line, discuss how to use the finite difference scheme and the interfaces for it, then only say at the end the preceding discussion is only applicable to 'trust-constr'.

**Comment by CatNofishing** [comment]
Similiar problem，the doc is  confused。
![image](https://user-images.githubusercontent.com/33288114/128110454-035d16d9-d485-4ca8-a54b-b8c256b915fa.png)
please update doc

**Comment by smolyi** [comment]
I get the same error 
TypeError: '<=' not supported between instances of 'int' and '_SumLinearOperator'
please fix this
