### ISSUE TITLE
Computing eigenvalues/eigenvectors for very large sparse matrices with eigsh

### ISSUE THREAD

**Issue by jhalverson** [scipy/scipy#12780]
It appears that scipy.sparse.linalg.eigsh calls ARPACK and the Fortran 77 source code for ARPACK uses 32-bit integers. This causes problems for large sparse matrices. Is there a way to build a 64-bit version?

**Comment by pv** [comment]
Yes, set `NPY_USE_BLAS_ILP64=1`.  https://docs.scipy.org/doc/scipy/reference/building/index.html#reference-for-build-options You'll need a 64-bit ilp64 openblas https://numpy.org/devdocs/user/building.html#bit-blas-and-lapack Probably easiest to grab the one used in the CI https://github.com/scipy/scipy/blob/master/.travis.yml#L170-L176
