### ISSUE TITLE
UserWarning: delta_grad == 0.0 with 'trust-constr' minimzation method

### ISSUE THREAD

**Issue by raghada** [scipy/scipy#12784]
I have an objective function (which is actually a polynomial linear regression of degree 2) i.e. w1*x1 + w2*x2 + w3*x1^2 ... etc

In addition to two linear constraints that I want to solve for. With these, I used `trust-constr` as follows:

```
def objective(x):
    features = poly_features.fit_transform([[x[0], x[1]]])
    return np.sum(weights*features) + poly_model.intercept_
```

```

linear_constraint1 = LinearConstraint([[0.01, 0.02]], 0, 50)
linear_constraint2 = LinearConstraint([[1, 1]], [1000], [2000])

res = minimize(objective, [0,0], method='trust-constr', 
               constraints=[linear_constraint1, linear_constraint2], bounds = ((0, np.inf), (0,np.inf)))
```

my problem is that whenever I run the code, I get the following warning that I actually am suffering to understand (given that my objective function is not linear):

`UserWarning: delta_grad == 0.0. Check if the approximated function is linear. If the function is linear better results can be obtained by defining the Hessian as zero instead of using quasi-Newton approximations.
  'approximations.', UserWarning)`

This second thing that I noticed was the result I achieved is not always within the bounds, e.g. x2 < 0 sometimes!

Am I missing something?

**Comment by andyfaff** [comment]
If no Hessian is given then `trust-constr` estimates the Hessian with a [quasi-Newton update](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.HessianUpdateStrategy.html#scipy.optimize.HessianUpdateStrategy). If your function is linear (you state your function is linear in the first sentence. Linear regression by definition uses a linear function) then `trust-constr` will work better if you give `hess=lambda x: 0`.

**Comment by raghada** [comment]
> If no Hessian is given then `trust-constr` estimates the Hessian with a [quasi-Newton update](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.HessianUpdateStrategy.html#scipy.optimize.HessianUpdateStrategy). If your function is linear (you state your function is linear in the first sentence. Linear regression by definition uses a linear function) then `trust-constr` will work better if you give `hess=lambda x: 0`.

If I'm not missing something, my objective function is not linear

```ObjFunc = w1*x1 + w2*x2 + w3*x1^2 + w4*x1*x2 + w5*x2^2```
where w1,...,w5 are known, x1 and x2 are not

**Comment by rlucas7** [comment]
What are the least squares estimates of w1, w2? 

I’m not exactly clear on the threshold criteria in trust-constr but
it could be that for the fitted values and the range in which the trust-constr is optimizing, the objective function is close to linear so that the warning is raised. 

-L

**Comment by raghada** [comment]
> What are the least squares estimates of w1, w2? I’m not exactly clear on the threshold criteria in trust-constr but it could be that for the fitted values and the range in which the trust-constr is optimizing, the objective function is close to linear so that the warning is raised.
> […](#)
> -L
> On Aug 29, 2020, at 1:59 AM, Raghad Alghonaim ***@***.***> wrote: ﻿ If no Hessian is given then trust-constr estimates the Hessian with a quasi-Newton update. If your function is linear (you state your function is linear in the first sentence. Linear regression by definition uses a linear function) then trust-constr will work better if you give hess=lambda x: 0. If I'm not missing something, my objective function is not linear ObjFunc = w1*x1 + w2*x2 + w3*x1^2 + w4*x1*x2 + w5*x2^2 where w1,...,w5 are known, x1 and x2 are not — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

array([ 1.69615960e-07, -3.37705246e-07, -5.67868029e-12,
       -6.87394505e-12,  8.47190007e-12])

**Comment by andyfaff** [comment]
`w3, w4, w5` are 5 orders of magnitude smaller than `w1, w2`, so I suspect the solver will only be sensitive to the first two terms of ObjFunc, making it appear linear in `x1, x2`.
