### ISSUE TITLE
Unexpected behaviour of interpolate.interp1d with repeated / non-monotonic x values

### ISSUE THREAD

**Issue by samaloney** [scipy/scipy#12783]
Not sure if this is a bug more an additional check / documentation issue but `interpolate.interp1d` gives an unexpected results with non-monotonic x data e.g. `x=[1, 2, 2, 3], y=[1, 2, 3, 4]` using the defaults. Trying the same with any of the spline methods raises an error (`ValueError: Expect x to not have duplicates`) I would expect the same behaviour from 'linear' rather than returning values?
 
#### Reproducing code example:

```python
from scipy.interpolate import interp1d
x = [1, 2, 2, 3]
y = [1, 2, 3, 4]
my_interp = interp1d(x, y)
res = my_interp(x)
print(y, res)

#my_interp = interp1d(x, y, 'cubic') raises ValueError

from matplotlib import pyplot as plt
plt.plot(x, y, '-k.', label='Original')
plt.plot(x, out, '--rx', label='Interpolated')
plt.legend()
```

![iterp_issue](https://user-images.githubusercontent.com/24570854/91542020-1ab6e400-e915-11ea-9821-f22f47c58688.png)

#### Scipy/Numpy/Python version information:

1.5.2 1.19.1 sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)

**Comment by ev-br** [comment]
This shows up quite regularly. The most recent one is https://github.com/scipy/scipy/issues/12373, an attempt to fix this, https://github.com/scipy/scipy/pull/9887, was rejected because of https://github.com/scipy/scipy/issues/9886.

In a nutshell, yes, it'd be desirable but it breaks backwards compatibility (e.g. representing step functions). Therefore, this will not be fixed, sadly.

**Comment by ev-br** [comment]
However documentation improvements are gratefully accepted, so if you feel like submitting a pull request to clarify the docs, it'd be most welcome.

**Comment by samaloney** [comment]
Ok I understand (I did search for interp1d issue but didn't see those 👀), what about logging a warning?

**Comment by ev-br** [comment]
If only python warnings were not only given once :-). And it's apparently used deliberately in contexts where warnings are not wanted.
