### ISSUE TITLE
ModuleNotFoundError: No module named 'scipy.io.wavefile'

### ISSUE THREAD

**Issue by fengwang** [scipy/scipy#12791]
My issue is about `scipy.io.wavefile`

#### Reproducing code example:

```
import scipy.io.wavefile.read
```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy.io.wavefile'
```

#### Scipy/Numpy/Python version information:

1.5.2 1.19.1 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)

OS: ArchLinux with kernel 5.4.61-1-lts

**Comment by rgommers** [comment]
Hi @fengwang, you misspelled it, it's `wavfile` not `wavefile`. Try the example from http://scipy.github.io/devdocs/generated/scipy.io.wavfile.read.html#scipy.io.wavfile.read

**Comment by fengwang** [comment]
> Hi @fengwang, you misspelled it, it's `wavfile` not `wavefile`. Try the example from http://scipy.github.io/devdocs/generated/scipy.io.wavfile.read.html#scipy.io.wavfile.read

That is my fault. Many Thanks for pointing it out.
