### ISSUE TITLE
Add percent point function to dirichlet continous distribution

### ISSUE THREAD

**Issue by JulianWgs** [scipy/scipy#12799]
**Is your feature request related to a problem? Please describe.**
I would like to have a percent point function for the `dirichlet` distribution ( similar to `scipy.stats.norm.ppf`).

**Describe the solution you'd like**
A similiar implementation like for the other distributions.

**Describe alternatives you've considered**
None.

**Additional context (e.g. screenshots)**
I did not find ressources to the inverse cdf of a dirichlet distribution. Is it even possible?

If there is way and it is feasible for me I'd like to implement the feature :)

**Comment by mdhaber** [comment]
Well, first we'd need to have a CDF function. There are a few common ways to define CDFs for multivariate distributions - usually based on rectangular or ellipsoidal regions. Once you choose one of those, the inverse CDF (PPF) is still not a single number as it is for univariate distributions, i.e. there are many different ways of shaping a rectangle that will have the same probability mass inside it. And then, even if the user specifies all but one dimension of the rectangle, it may still be computationally intensive to find the last remaining dimension. So there are a lot of hurdles here, and I don't see it happening soon. I'm tempted to mark this as "technically infeasible" and close. What do you think @steppi? 
(Note: if we close this and you find some literature about it for us to follow, we can certainly reopen this.)

**Comment by steppi** [comment]
> What do you think @steppi?

Agreed about marking it as technically infeasible. Even calculating a multivariate CDF for a Dirichlet distribution is a little tricky and typically requires Monte-Carlo integration, especially for higher dimensions. 

There’s no inverse of this multivariate CDF as a  function. Calculating the set theoretic inverse, i.e. finding all of the lower (hyper)rectangles containing the desired probability mass seems like it could be completely intractable.

I’m curious if someone has a use-case for this though. It could always be reopened if someone has one and finds a workable approximation.
