### ISSUE TITLE
[Bug] The result of stats.beta.isf is inconsistent with stats.beta.sf

### ISSUE THREAD

**Issue by jjy1994** [scipy/scipy#12794]
My issue is about the function stats.beta.isf

#### Reproducing code example:

```
from scipy import stats
count_list=[10,100,1000]
for count in count_list:
    print(stats.beta.isf(1e-11, count + 1, 100000 - count))
```

#### Error message:

The output is as follows:
```
0.05886256830747675
0.0018360586912590238
0.012266391994249615
```
With the increasing of count, the value should increase. However, the value reaches the maximum value when count=10 which is undesired. I further checked the stats.beta.sf function and find the results are inconsistent with stats.beta.isf. The code and results are as follows: 
```
from scipy import stats
count_list=[10,100,1000]
for count in count_list:
    isf_output=stats.beta.isf(1e-11, count + 1, 100000 - count)
    sf_output = stats.beta.sf(isf_output, count + 1,100000 - count)
    print(sf_output)
```
The expected output would be:
1e-11
1e-11
1e-11
However, when I execute the code, I obtain the following output:
1e-16
1e-11
1e-11
#### Scipy/Numpy/Python version information:

1.5.2 1.19.1 sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
`a=11`, `b=99990` appears to be a very challenging case (numerically) for the underlying special functions; the PDF is a sharp spike and `btdtri` is not very accurate.
```
from scipy.special import btdtr, btdtri
> btdtri(11, 99990, 1-1e-11)
0.05886256830747675
> btdtr(11, 99990, btdtri(11, 99990, 1-1e-11))
0.9999999999999999
```
It is probably the inverse function that is inaccurate. 

![image](https://user-images.githubusercontent.com/6570539/100415975-2dcf7200-3032-11eb-948a-182ca2c94d5b.png)

I'm pretty sure that's not supposed to happen.

@mckib2 Boostinator?

**Comment by mckib2** [comment]
@mdhaber  Boost appears to do the right thing here:
```
beta.isf comparison:
     scipy
         0.05886256830747675
         0.0018360586912590238
         0.012266391994249615
     boost
         0.000494446489991609
         0.001836058693052951
         0.012266391998595059

roundtrip comparison (beta.sf(beta.isf()):
     scipy
         1.1102230246251565e-16
         1.000000082740371e-11
         1.000000082740371e-11
     boost
         1.0000000000000037e-11
         1.0000000000000017e-11
         9.999999999999869e-12
```

**Comment by mdhaber** [comment]
Same issue as gh-12794
