### ISSUE TITLE
Example for scipy.signal.convolve2d in documentation does not use correct plot command

### ISSUE THREAD

**Issue by ylevental** [scipy/scipy#12804]
In the "Examples" section of [scipy.signal.convolve2d](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.convolve2d.html), ```fig.show()``` is used to plot the images.  The last line should be ```plt.show()```.

#### Reproducing code example:

```from scipy import signal
from scipy import misc
ascent = misc.ascent()
scharr = np.array([[ -3-3j, 0-10j,  +3 -3j],
                   [-10+0j, 0+ 0j, +10 +0j],
                   [ -3+3j, 0+10j,  +3 +3j]]) # Gx + j*Gy
grad = signal.convolve2d(ascent, scharr, boundary='symm', mode='same')

>>>

import matplotlib.pyplot as plt
fig, (ax_orig, ax_mag, ax_ang) = plt.subplots(3, 1, figsize=(6, 15))
ax_orig.imshow(ascent, cmap='gray')
ax_orig.set_title('Original')
ax_orig.set_axis_off()
ax_mag.imshow(np.absolute(grad), cmap='gray')
ax_mag.set_title('Gradient magnitude')
ax_mag.set_axis_off()
ax_ang.imshow(np.angle(grad), cmap='hsv') # hsv is cyclic, like angles
ax_ang.set_title('Gradient orientation')
ax_ang.set_axis_off()
fig.show()


```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

**Comment by peterbell10** [comment]
The examples are run in CI, so the examples should always at least run. [`Figure.show`](https://matplotlib.org/3.2.2/api/_as_gen/matplotlib.figure.Figure.html?highlight=show#matplotlib.figure.Figure.show) is a real function and when I run the example the plots are displayed as normal.
