### ISSUE TITLE
The result of cheb2ord is not equal to cheb2ord in MATLAB

### ISSUE THREAD

**Issue by SeventeenChen** [scipy/scipy#12807]
My issue is about ...
The result of cheb2ord of scipy.siganl is not equal to the same function in MATLAB.

I read the source code of python and MATLAB, I found the bug: 

#### Reproducing code example:

```
    if not analog:
        # wn = (2.0 / math.pi) * np.arctan(nat)
        wn = ws
    else:
        wn = nat
```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

**Comment by roryyorke** [comment]
The code you propose changing has to do with the frequency pre-warping; in general, wn is not equal to ws.

Matlab and Scipy do sometimes differ in the outputs of the filter *ord functions.  See #3219, which has a long discussion of where and why this is; in brief, there can be more than one Wn satisfying a given filter spec.

If you could give us details of the Matlab inputs and outputs, we could check if this is the case for your filter design.

**Comment by tupui** [comment]
Please be careful about the licensing here as Matlab code is usually copyrighted or under a non compatible license. So you cannot look at the code and report a bug.

Is this still an open issue?

**Comment by roryyorke** [comment]
I think this can be closed; we know `cheb2ord` outputs can differ between Matlab and scipy.  If @SeventeenChen comes back with more detail we can reopen it.
