### ISSUE TITLE
Different result for scipy.optimize.linprog between scipy 1.1.0 and scipy 1.2.2 

### ISSUE THREAD

**Issue by fengqingleiyue** [scipy/scipy#12808]
# We got an issue about the result of 'scipy.optimize.linprog' function with scipy 1.1.0 and scipy 1.2.2 

### specific python code 
```python
import numpy
from scipy import optimize
target=[5.0, 7.0, 1.0, 5.0, 6.0, -2.0, 1.0, -2.0, 6.0, -2.0, 1.0, 6.0, 5.0, -1.0]
a=[[0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, -1, 0, 0], [0, 0, 1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [-1, -1, 0, -1, 0, 1, 0, 1, 0, 1, 0, 0, -1, 1]]
b=[25491197.0, 34431131229.0, 74287463593.0, 0.0] #type(b) is list
d=[[0, 0, -1, 0, 1, 0, 0, -1, 0, 0, 0, 0, 1, 0], [1, 0, 0, 0, 0, -1, 0, 0, 1, 0, -1, 0, 0, 0], [0, 0, 0, 1, 0, 0, -1, 0, 0, -1, 0, 1, 0, 0]]
e=[66801372768.0, 351002969.0, 91862023.0]
bounds=[[0, 227446122813.0], [0, numpy.nan], [0, numpy.nan], [0, 722782112399.0], [0, numpy.nan], [0, 9.223371809408653e+18], [0, numpy.nan], [0, 9.223371950523316e+18], [0, numpy.nan], [0, 9.223371314072663e+18], [0, numpy.nan], [0,numpy.nan], [0, 86331459457.0], [0, numpy.nan]]
res = optimize.linprog(target, a, b, d, e, bounds=bounds)
```
#### with scipy 1.1.0 we got result:
res.success is True

#### with scipy 1.2.2 we got result:
res.success is False 
res.message is 'Phase 1 of the simplex method failed to find a feasible solution. The pseudo-objective function evaluates to 2.0e+03 which exceeds the required tolerance of 1e-12 for a solution to be considered 'close enough' to zero to be a basic solution. Consider increasing the tolerance to be greater than 2.0e+03. If this tolerance is unacceptably  large the problem may be infeasible.' 

#### What i want to know 
why there is a difference between scipy=1.1.0 and scipy=1.2.2 ? , is this a bug of scipy==1.1.0 or this is something wrong happened in scipy==1.2.2 ?

**Comment by fengqingleiyue** [comment]
@pvanmulbregt  any idea about this issue ?

**Comment by mdhaber** [comment]
The simplex solver in these old versions of SciPy had a lot of bugs. Try setting the parameter `method='interior-point'`. If you need an "exact", basic solution, you can use `method='revised simplex'` in SciPy 1.3+.

**Comment by fengqingleiyue** [comment]
@mdhaber Thanks , by using method='interior-point' , we got the same result on scipy=1.10 and scipy=1.2.2 .
(In out case , the problem is infeasible)
