### ISSUE TITLE
ttest_ind returns an object with nan_policy='omit' if groups too small

### ISSUE THREAD

**Issue by billgreenwald** [scipy/scipy#12800]
Hello!

When running ss.ttest_ind(groupA, groupB, nan_policy='omit'), if groupA or groupB only has 1 non NaN entry, the function will still return, but it returns a Ttest object, instead of a tuple of statistic, pvalue.  This can cause unintended code results, and I didn't see documentation anywhere.

Best,
Bill

Version info:
1.4.1 1.18.4 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
I just checked this in master and it seems to return the `Ttest_indResult` regardless of how many `nan`s there are.

```
import numpy as np
from scipy.stats import ttest_ind
x = np.random.rand(10)
y = np.random.rand(10)
res = ttest_ind(x, y)
print(type(res))      # no nans
x [-5] = np.nan
res = ttest_ind(x, y)
print(type(res))      # one nan
x[:-1] = np.nan
res = ttest_ind(x, y)
print(type(res))      # one array all but one nan
y[:] = np.nan
res = ttest_ind(x, y)
print(type(res))      # all but one nan
x[:] = np.nan
res = ttest_ind(x, y)
print(type(res))      # all nans
print(isinstance(res, tuple))  # 
```

Note that the `Ttest_indResult object` _is_ a tuple and can do anything a tuple can do, so it shouldn't cause problems unless you use `type` instead of `isinstance` to determine what type it is. A lot of stats functions have moved in the direction of returning a `namedtuple` or similar, and I don't think we're documenting each of these named classes. Is that right @WarrenWeckesser, or do we intend to document the names of all these?

@billgreenwald thanks for reporting it, though. We wouldn't want the behavior to be inconsistent. Does it sound like this issue is resolved?

**Comment by mdhaber** [comment]
Oops, I notice that it was supposed to be `nan_policy="omit`. Same story, though.

```
import numpy as np
from scipy.stats import ttest_ind
x = np.random.rand(10)
y = np.random.rand(10)
res = ttest_ind(x, y, nan_policy="omit")
print(type(res))      # no nans
x [-5] = np.nan
res = ttest_ind(x, y, nan_policy="omit")
print(type(res))      # one nan
x[:-1] = np.nan
res = ttest_ind(x, y, nan_policy="omit")
print(type(res))      # one array all but one nan
y[:] = np.nan
res = ttest_ind(x, y, nan_policy="omit")
print(type(res))      # all but one nan
x[:] = np.nan
res = ttest_ind(x, y, nan_policy="omit")
print(type(res))      # all nans
print(isinstance(res, tuple))
```
prints
```
<class 'scipy.stats.stats.Ttest_indResult'>
<class 'scipy.stats.mstats_basic.Ttest_indResult'>
<class 'scipy.stats.mstats_basic.Ttest_indResult'>
<class 'scipy.stats.mstats_basic.Ttest_indResult'>
<class 'scipy.stats.mstats_basic.Ttest_indResult'>
True
```

**Comment by WarrenWeckesser** [comment]
@billgreenwald, can you show a simple example that demonstrates the problem?  As @mdhaber noted, in SciPy 1.4.1 the object returned by `ttest_ind` is still a tuple (it's a `namedtuple`), so it should still work the same as older versions of SciPy.  That is, code such as

    tstat, pvalue = ttest_ind(a, b, nan_policy='omit')

should still work.

**Comment by mdhaber** [comment]
@billgreenwald I'll go ahead and close, but please feel free to reopen if you still think there is a problem and can provide example code that demonstrates it.

**Comment by billgreenwald** [comment]
The weekend got the better of me, apologies. I tried to replicate in the
newest version of scipy 1.5.2 and could not. Thanks for looking into it,
sorry if it was an erroneous request.

**Comment by mdhaber** [comment]
No problem. Thanks for reporting bugs!
