### ISSUE TITLE
stats.zscore inconsistent behavior when all values are the same

### ISSUE THREAD

**Issue by mglowacki100** [scipy/scipy#12815]
My issue is about `stats.zscore`. When input vector has the same entries, then standard deviation is 0, so there is division by 0 like in `z1` so e.g. for `arr1=[20.0, 20.0, 20.0]` result is array of `nans`  (`array([nan, nan, nan])`)- perfectly fine. I don't understand why for `arr2=[-0.087, -0.087, -0.087]` I get `array([1., 1., 1.])`. Are there any workaround for this?

#### Reproducing code example:
```
import scipy

arr1 = [20.0] * 3
#[20.0, 20.0, 20.0]

z1 = scipy.stats.zscore(arr1)
#/usr/local/lib/python3.6/dist-packages/scipy/stats/stats.py:2419: RuntimeWarning: invalid value encountered in true_divide
#  return (a - mns) / sstd
#z1 is array([nan, nan, nan]) This is correct behavior

arr2 = [-0.087] * 3
#[-0.087, -0.087, -0.087]

z2 = scipy.stats.zscore(arr2)
#z2 is array([1., 1., 1.]) !!! IMO It should be the same as z1
```

#### Scipy/Numpy/Python version information:
On google colab:
```
1.4.1 1.18.5 sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
```
The same results on scipy 1.5.2 on windows.

**Comment by mglowacki100** [comment]
Issue is caused by numpy (also in 1.19 version)
`
np.std(arr1), np.std(arr2)
#(0.0, 1.3877787807814457e-17)
`

**Comment by mglowacki100** [comment]
Closely related to: https://github.com/scipy/scipy/issues/3728 maybe it could be solved in the same way.

**Comment by mdhaber** [comment]
Also seems related to gh-11086

**Comment by mdhaber** [comment]
@WarrenWeckesser do you have any suggestions for these? They seem to be up your alley.

**Comment by WarrenWeckesser** [comment]
As @mglowacki100 pointed out, we can't rely on `np.std` to give 0 when given a constant input.  We also can't rely on `np.mean()` returning the same constant when its input is constant, e.g.
```
In [48]: a = np.array([-0.087, -0.087, -0.087])                                                                       

In [49]: a[0]                                                                                                         
Out[49]: -0.087

In [50]: np.mean(a)                                                                                                   
Out[50]: -0.08700000000000001
```
See https://github.com/numpy/numpy/issues/9631 for a discussion of this issue.

If we want to guarantee that `zscore` returns `nan`s when the input is constant, we'll have to add an explicit check for constant input.  I'll put together a PR.  We have to handle the `axis` parameter, so it won't be a "one-liner" fix.

**Comment by WarrenWeckesser** [comment]
PR is https://github.com/scipy/scipy/pull/13154.  As expected, the changes are definitely not a simple one-liner.  With the PR:
```
In [40]: arr2 = [-0.087] * 3                                                                                                        

In [41]: zscore(arr2)                                                                                                               
Out[41]: array([nan, nan, nan])
```
Here is an example where the input has `nan`s and we use `nan_policy='omit'` and an `axis`.  In the first row of `x`, the non-`nan` values are all the same, so the output is all `nan`.  The last row shows an edge case, where *all* the input values are `nan`.
```
In [49]: x = np.array([[-0.087, -0.087, -0.087, np.nan, np.nan], 
    ...:               [10.0, 11.0, 12.0, 13.0, np.nan], 
    ...:               [np.nan, np.nan, np.nan, np.nan, np.nan]])                                                                   

In [50]: x                                                                                                                          
Out[50]: 
array([[-0.087, -0.087, -0.087,    nan,    nan],
       [10.   , 11.   , 12.   , 13.   ,    nan],
       [   nan,    nan,    nan,    nan,    nan]])

In [51]: zscore(x, axis=1, nan_policy='omit')                                                                                       
Out[51]: 
array([[        nan,         nan,         nan,         nan,         nan],
       [-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079,         nan],
       [        nan,         nan,         nan,         nan,         nan]])
```
