### ISSUE TITLE
how can i get Lagrange multipliers in  'linprog' optimize

### ISSUE THREAD

**Issue by Aglargil** [scipy/scipy#12823]

**Comment by mdhaber** [comment]
Unfortunately, right now you'd have to get at them backwards - adjust each bound individually and measure the change in the objective function. gh-12043 will add two new, much faster methods to `linprog` and we intend to add sensitivity analysis features to those.

This is an important idea, but the enhancement request is already recorded in gh-8336 (and gh-11848, and one item on gh-9269) so I'll close.
