### ISSUE TITLE
scipy.signal.windows.dpss docstring typo

### ISSUE THREAD

**Issue by chapochn** [scipy/scipy#12840]
in the parameters of scipy.signal.windows.dpss:
NW: float
        Standardized half bandwidth corresponding to 2*NW = BW/f0 = BW*N*dt where dt is taken as 1.

I believe the N should be an M, as M is the window length, i.e., BW*N*dt -> BW*M*dt

also in the return:
v: ndarray, shape (Kmax, N) or (N,)

N should also be replaced by M

And in the example would also be good to replace N by M for consistency

Another option is to change all the M to N, since the name NW comes from the fact that usually, the number of points in the window is N.

**Comment by larsoner** [comment]
> Another option is to change all the M to N, since the name NW comes from the fact that usually, the number of points in the window is N.

I agree this would be nice, but it's harder because it will break people passing everything as kwargs. I think it would be better just to update the docstrings. Are you up for making a PR to do it?

**Comment by chapochn** [comment]
I updated the docs by putting M everywhere. Please see if that works!
