### ISSUE TITLE
What are the input arguments “s” and “scale” defined in scipy.stats.lognorm? (scipy.stats.lognorm documentation error)

### ISSUE THREAD

**Issue by tbgs2020** [scipy/scipy#12844]
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.lognorm.html

The second description paragraph of scipy.stats.lognorm states the following:

"A common parametrization for a lognormal random variable Y is in terms of the mean, mu, and standard deviation, sigma, of the unique normally distributed random variable X such that exp(X) = Y. This parametrization corresponds to setting s = sigma and scale = exp(mu)."

This paragraph is confusing and seems to state the mean = mu and standard deviation = sigma.

The correct answer is s = shape factor and scale = median value, as shown in the below example. Note, Wikipedia defines the shape factor as mu and median value as exp(mu).

#### Reproducing code example:

```
from scipy.stats import *
import numpy as np

#Log-Normal distribution
mu = 1.0          #mean
sigma = 0.5       #Std Dev

zeta = np.sqrt(np.log(1 + (sigma / mu) ** 2)) #shape factor
lambda_value = np.log(mu) - 0.5 * zeta ** 2   # expected value of ln x

median = np.exp(lambda_value)
print('Mean      ', lognorm.mean(s=zeta, loc=0, scale=np.exp(lambda_value)))
print('Median    ', median)
print('Median2   ', lognorm.median(s=zeta, loc=0, scale=np.exp(lambda_value)))
print('Quantile1 ', lognorm.ppf(0.9, s=zeta, loc=0, scale=np.exp(lambda_value)))
print('Quantile2 ', lognorm.ppf(0.2, s=zeta, loc=0, scale=np.exp(lambda_value)))

Mean       1.0
Median     0.8944271909999159
Median2    0.8944271909999159
Quantile1  1.6385447242959015
Quantile2  0.6010137742068968
```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

**Comment by rkern** [comment]
> This paragraph is confusing and seems to state the mean = mu and standard deviation = sigma.

It's referring to the mean and standard deviation of "the unique normally distributed random variable X such that exp(X) = Y", not the log-normal `Y` itself. I can see how that can be missed in that sentence, but I'm not sure how to rephrase it. It is an important relationship that does need to be stated explicitly.

**Comment by mdhaber** [comment]
@tbgs2020 did this resolve the issue? If you'd like the documentation to be updated, do you have a suggestion on how to fix it?

**Comment by mdhaber** [comment]
@rkern is the following accurate?

![image](https://user-images.githubusercontent.com/6570539/101324948-d5615700-381f-11eb-83ed-0d95d117f62c.png)

@tbgs2020 would this help?

**Comment by mdhaber** [comment]
@WarrenWeckesser what do you think of this?

**Comment by mdhaber** [comment]
@tbgs2020 Thanks for mentioning this. I'll go ahead and close for now, since it looks like the question was answered by @rkern. If you think that the documentation can be improved, please take a look at my [suggested wording](https://github.com/scipy/scipy/issues/12844#issuecomment-739746723) above, or let us know how you think it should read. Thanks!
