### ISSUE TITLE
sparse A[0,:] = ndarray is ok, A[:,0] = ndarray ValueError from wrong broadcasting

### ISSUE THREAD

**Issue by denis-bz** [scipy/scipy#12857]
#### Reproducing code example:

```
""" sparse A[0,:] = ndarray is ok, A[:,0] = ndarray ValueError  1.5.2 16sept 2020 """
import numpy as np
from scipy import sparse

n = 3
ones = np.ones( n )

for A in [
    np.eye(n),
    sparse.eye( n ).tolil(),
    sparse.eye( n ).tocsr(),
    sparse.eye( n ).tocsr(),
    ]:
    print( "\n-- A:", type(A).__name__, A.shape )
    print( "A[0,:] = ones" )
    A[0,:] = ones
    print( "A[:,0] = ones" )
    A[:,0] = ones

```
#### Error message:

```
logfile, "wrong broadcasting" marked --
-- A: ndarray (3, 3)
A[0,:] = ones
A[:,0] = ones

-- A: lil_matrix (3, 3)
A[0,:] = ones
A[:,0] = ones
Traceback (most recent call last):
  File "setcol.py", line 26, in <module>
    A[:,0] = ones
    │        └ array([1., 1., 1.])
    └ <3x3 sparse matrix of type '<class 'numpy.float64'>'
    with 5 stored elements in List of Lists format>
  File "/opt/local/py3/lib/python3.7/site-packages/scipy/sparse/lil.py", line 333, in __setitem__
    IndexMixin.__setitem__(self, key, x)
    │                      │     │    └ array([1., 1., 1.])
    │                      │     └ (slice(None, None, None), 0)
    │                      └ <3x3 sparse matrix of type '<class 'numpy.float64'>'
----------------------------- 3x3: wrong broadcasting
    with 5 stored elements in List of Lists format>
    └ <class 'scipy.sparse._index.IndexMixin'>
  File "/opt/local/py3/lib/python3.7/site-packages/scipy/sparse/_index.py", line 123, in __setitem__
    x = x.reshape(i.shape)
    │   │         └ array([[0],
       [1],
       [2]])
    │   └ array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])
    └ array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])
ValueError: cannot reshape array of size 9 into shape (3,1)
```

#### Scipy/Numpy/Python version information:

versions: numpy 1.19.2  scipy 1.5.2  python 3.7.6

Comments --

Possibly related: https://github.com/scipy/scipy/issues/10695 Assignation issues in csr_matrix with fancy indexing

Squeezing i j x in scipy/sparse/_index.py line ~ 119 fixes this case, may well break others
```
    # Make x and i into the same shape
    x = np.asarray(x, dtype=self.dtype)i
    x, i, j = x.squeeze(), i.squeeze(), j.squeeze()  # <-- added
    x, _ = _broadcast_arrays(x, i)
```

**Comment by perimosocordiae** [comment]
Thanks for filing this @denis-bz. I think I have a fix prepared, please take a look at the linked PR.

**Comment by denis-bz** [comment]
A WIBNI, wouldn't it be nice if we had a test of ALL the forms of `i j x` for which `A[i,j] = x` oughta work ?
which would've caught this bug ?
(Bugs in indexing are like mosquitoes -- slap one, there are more around.)
Along the lines --

    n = 3
    ones = np.ones(n)
    As = [ np.eye(n), sparse.eye(n).tocsr() ...
    Ixs = [ 0, -1, range(n), np.arange(n), np.matrix( range(n) ) ...
    Xs = Xs = [ 0, 1, ones, ones.reshape( n, 1 ), ones.reshape( 1, n ) ...
    
    for A, i, j, x in product( As, Ixs, Ixs, Xs ):
        A[i,j] = x  # should work
        
This is just a start, for i j x scalars or `squeeze` 1d; there are *lots* more cases, don't know how to structure them ...

What do you think ?
