### ISSUE TITLE
 Read the file and save it again. The file before and after is inconsistent。

### ISSUE THREAD

**Issue by Qianzujin** [scipy/scipy#12854]
The file is 935kb before reading, and is saved directly without any operation. After saving, it is 1014kb. Is there any way to save the same size as the original file? Due to the company's network is limited, so only text description, please help to see the problem, thank you.

**Comment by Qianzujin** [comment]
Matlab can read the saved file, and the content is the same as before, but the program made in other languages can't parse the file.My English is not very good, use the translation program, please understand, thank you

**Comment by Qianzujin** [comment]
I've tried to use some other parameters when using the loadmat function, but the results are not ideal

**Comment by Qianzujin** [comment]
Matlab 2010b

**Comment by Qianzujin** [comment]
My mat file version is v7.0. Can savemat set this version number? It seems that you can only set two formats: format = 5 'or format = 4'

**Comment by Qianzujin** [comment]
https://github.com/tbeu/matio/issues/154
In this link, I also raised the same question, the above picture and explanation, please help to have a look, thank you very much.

**Comment by Qianzujin** [comment]
@Alex Henrie

**Comment by Qianzujin** [comment]
@alexhenrie

**Comment by rgommers** [comment]
This is to be expected, there's no requirement to read in a file produced from Matlab, save it back out and have it be identical. We should produce a _valid_ file, so if both `scipy.io` and Matlab can again read the file, that's good enough for us.

https://github.com/tbeu/matio/issues/154 has useful discussion, thanks. I'll leave it open for now, but I don't think there's much we can do.

**Comment by rgommers** [comment]
No further discussion and nothing we can do, so I'll close this issue. Thanks for the report @Qianzujin
