### ISSUE TITLE
ubuntu18 python 3.6/3.7 can't install scipy with numpy 1.19.1

### ISSUE THREAD

**Issue by bladerunner512** [scipy/scipy#12853]
My issue is about ...
Trying to install scipy on Ubuntu 18 with python 3.7 (3.6. also fails with same error). Error says can't find numpy >= 1.14.5, but 1.19.1 is installed

#### Reproducing code example:
$ python3.7 -m pip install scipy-1.5.2-cp37-cp37m-manylinux1_x86_64.whl

$ python3.7 -m pip --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.7)

#### Error message:
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb10c0fc0f0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /simple/numpy/
  **Could not find a version that satisfies the requirement numpy>=1.14.5** (from scipy==1.5.2) (from versions: )
No matching distribution found for numpy>=1.14.5 (from scipy==1.5.2)

#### Scipy/Numpy/Python version information:
scipy==1.5.2
Same error occurs in python 3.6 and 3.7
$ python3.6 --version
Python 3.6.9
$ python3.7 --version
Python 3.7.5

$ python3.7 -m pip install numpy -i https://##.com/artifactory/api/pypi/python-anonymous/simple
Collecting numpy
  Using cached https://##.com/artifactory/api/pypi/python-anonymous/numpy/1.19.1/numpy-1.19.1-cp37-cp37m-manylinux1_x86_64.whl
Installing collected packages: numpy
Successfully installed numpy-1.19.1

$ python3.7 -m pip list
.
.
.
**numpy (1.19.1)**

$ python3.7 -m pip install python_reqs/scipy-1.5.2-cp37-cp37m-manylinux1_x86_64.whl
Processing ./python_reqs/scipy-1.5.2-cp37-cp37m-manylinux1_x86_64.whl
Collecting numpy>=1.14.5 (from scipy==1.5.2)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7faf742c8990>: Failed to establish a new connection: [Errno 111] Connection refused')': /simple/numpy/
  Could not find a version that satisfies the requirement numpy>=1.14.5 (from scipy==1.5.2) (from versions: )
**No matching distribution found for numpy>=1.14.5 (from scipy==1.5.2)**

**Comment by ilayn** [comment]
Can you try just the plain `pip install scipy` ?

**Comment by bladerunner512** [comment]
Can only install offline.
Appears to only look online for intalled numpy?
$ python3.7 -m pip install python_reqs/scipy-1.5.2-cp37-cp37m-manylinux1_x86_64.whl -vvv
Processing ./python_reqs/scipy-1.5.2-cp37-cp37m-manylinux1_x86_64.whl
Collecting numpy>=1.14.5 (from scipy==1.5.2)
  1 location(s) to search for versions of numpy:
  * https://pypi.python.org/simple/numpy/
  Getting page https://pypi.python.org/simple/numpy/
  Looking up "https://pypi.python.org/simple/numpy/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org

**Comment by ilayn** [comment]
Your numpy might be 32bit or some other python version might have claimed the numpy installation you have. Other than that I can't think of anything.

**Comment by bladerunner512** [comment]
I don't think numpy is 32bit: numpy-1.19.1-cp37-cp37m-manylinux1_x86_64.whl

Only python 3.6 and 3.7 are installed. Alternatives only points to 3.7:
$ update-alternatives --list python
/usr/bin/python3.7

Other wheels install without issue - only scipy seems to fail to find dependencies

**Comment by tylerjereddy** [comment]
A bit of a stretch since that's a pretty old version of `pip` but may be worth trying to add in the `--no-build-isolation` flag to the `pip install ..` command maybe.

**Comment by bladerunner512** [comment]
Thanks for the suggestion. Didn't realize that pip was such an old version - install by ‘apt install python3-pip’ and all other installs worked fine.

After updating to latest version (20.2.3) I was able to install scipy.
