### ISSUE TITLE
scipy.sparse.csgraph.connected_components does not work for directed graphs

### ISSUE THREAD

**Issue by gunan** [scipy/scipy#12859]
My issue is about scipy.sparse.csgraph.connected_components
When directed arg is set to true, I expect the given matrix to be treated as a directed graph. in the below example, I expect to see 5 separate components. However, the graph is treated as undirected and only 2 components are returned.

#### Reproducing code example:

```python
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import connected_components
graph = [
 [ 0, 1, 1, 0, 0],
 [ 0, 0, 1, 0, 0],
 [ 0, 0, 0, 0, 0],
 [ 0, 0, 0, 0, 1],
 [ 0, 0, 0, 0, 0]
]
graph = csr_matrix(graph)
print(graph)
n_components, labels = connected_components(csgraph=graph, directed=True, return_labels=True)
print(labels)
```

#### Error message:

```
None, just unexpected output.
```

**Comment by jakevdp** [comment]
When I run your code using scipy 1.5.2, I get the following output:
```
  (0, 1)	1
  (0, 2)	1
  (1, 2)	1
  (3, 4)	1
[0 0 0 1 1]
```
This appears to be correct (nodes 0, 1, 2 are in a group with mutual connections, and nodes 3, 4 are in a second group with mutual connections).

Is this the output that you're seeing?

**Comment by jakevdp** [comment]
Note that the default is weakly-connected components. If you want strongly-connected components, you can set the `connection='strong'` keyword.

**Comment by gunan** [comment]
I am very sorry about this. Looks like I misread the documentation. Thank you very much for the explanation.

**Comment by jakevdp** [comment]
No problem, glad you got it figured out!
