### ISSUE TITLE
Can I use ConvexHull in a float data array?

### ISSUE THREAD

**Issue by NicoliHCorrea** [scipy/scipy#12856]
I want to use ConvexHull to find my set diameter, but my data are in float64 format. 
The problem is that the hull.simplices, that I believe is where the points that form the convex are, only give me int values.. And I need the points coodinates to be precise. Is there anything I can do other than multiply my vector per 10^x?
Here is an exemple:

```
from scipy.spatial import ConvexHull
points = np.array([[0.2456, 0.2321],[0.2789, 0.4645],[0.474, 0.4456],[0.4489, 0.246],[0.3156, 0.6456]])
hull = ConvexHull(points)
print(hull.simplices)

```
output:
[[4 2]
 [3 0]
 [3 2]
 [1 0]
 [1 4]]

**Comment by pmla** [comment]
The `hull.simplices` array contains point *indices*, so they are always integer regardless of the input type.
The coordinates of the points on the hull are given by `points[hull.simplices]`.

If you run the [example in the docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.ConvexHull.html) it will hopefully be clear.

**Comment by NicoliHCorrea** [comment]
I'm sorry..I don't get how this work. 
if I have an array like 
[ [ x y ] [ x2 y2] [x3 y3] [xn yn]]
how do I convert the index in the ordered pair? 
When I used points[hull.simplices] the array became a matrix.

**Comment by pmla** [comment]
If you just want the hull points:
```
points[np.unique(hull.simplices)]
```
