### ISSUE TITLE
Build requirements are exact version pins?!

### ISSUE THREAD

**Issue by ionelmc** [scipy/scipy#12865]
Hello, It appears that `pyproject.toml` has this in the build requirements:
```
    "numpy==1.14.5; python_version=='3.6' and platform_system!='AIX'",
    "numpy==1.14.5; python_version=='3.7' and platform_system!='AIX'",
    "numpy==1.17.3; python_version>='3.8' and platform_system!='AIX'",
    "numpy==1.16.0; python_version=='3.6' and platform_system=='AIX'",
    "numpy==1.16.0; python_version=='3.7' and platform_system=='AIX'",
    "numpy==1.17.3; python_version>='3.8' and platform_system=='AIX'",
```

However this will yield horrible build times if you have a different numpy version installed. Perhaps what was meant there is a minimum version constraint (eg: `>=`)?

**Comment by ilayn** [comment]
Hi @ionelmc please have a look at #12803 and #12846 for some context.

**Comment by ionelmc** [comment]
The install requirements do not have any upper constraint for numpy, and in some cases it's not even present in that list. One of these is wrong. Either the build reqs should have min constraints, or the install requirements have upper/lower constraints (if ABI compatibility is really a problem).

**Comment by rgommers** [comment]
> The install requirements do not have any upper constraint for numpy, and in some cases it's not even present in that list. One of these is wrong. Either the build reqs should have min constraints, or the install requirements have upper/lower constraints (if ABI compatibility is really a problem).

Yes, the install requirements need a significant update including upper bounds, I'm just doing that in gh-12862.

Build-time requirements in `pyproject.toml` are correct. 

> However this will yield horrible build times if you have a different numpy version installed.

We're in the world of isolated builds now, installed numpy versions will not be used for a `pip install scipy` or `pip install .` build.

There's nothing left to do here other than finish up gh-12862, so I'll close this issue. If you have more questions or comments, feel free to continue the conversation of course.

**Comment by ilayn** [comment]
oops I saw that last night but my brain was overloaded so I forgot about that. Sorry for not drawing attention to that Ralf.
