### ISSUE TITLE
Vector-valued interpolation in `interp2d`

### ISSUE THREAD

**Issue by mueslo** [scipy/scipy#12868]
**Is your feature request related to a problem? Please describe.**
There should be an easy way to interpolate non-scalar data on a 2D grid. Given e.g. `x.shape == y.shape == (36, 48)` and `z.shape == (36, 48, 11)`, there should be a straight-forward way to interpolate this to get an interpolated vector-valued function. This exists for `interp1d`, so why not for `interp2d`?

**Describe the solution you'd like**
One intuitive approach from the user perspective would be an `axes` keyword, which specifies which axes will be used to interpolate along, such that:

    f = interp2d(x, y, z, axes=(0, 1))
    f(0.253, 0.447).shape == (11,)  # True

For `interp2d` axes would of course (usually) be a length-2 tuple. Also, this should not be limited to vector/1D function data, but arbitrary dimensionality, i.e. `z` could also have shape `(36, 48, 11, 31)`, then the `interp2d` interpolation output should have shape `(11, 31)`.

As the input can also be flattened, `axes` essentially tells you along which axes you will find the data to be flattened/interpolated (could also be longer than *n*). For an already-flattened input (`x.shape == y.shape == (1728,)` and `z.shape == (1728,11)`) the equivalent call signature would of course be `axes=(0,)`

**Describe alternatives you've considered**
Use `interpn` instead

**Comment by pv** [comment]
interpn:

>>> x = np.linspace(0, 2, 5)
>>> y = np.linspace(0, 2, 7)
>>> z =
np.random.randn(5, 7, 3)
>>> interpn((x, y), z, (1.0, 1.0))
array([[
0.41399926, -0.35760212,  0.5403803 ]])
>>> z[2,3]
array([ 0.41399926,
-0.35760212,  0.5403803 ])

**Comment by mueslo** [comment]
> 
> interpn:

As you replied via e-mail you did not see the changes made before your reply - when writing this I was thinking of `interp2d` and assumed `interpn` was just an *n*-D version of it. I did realize that `interpn` behaves differently, and does things the way I want, but still `interp2d` cannot. Since `interp1d` and `interp2d` share basically the same behaviour/call signature and `interp1d` can interpolate along arbitrary axes, it would be expected that `interp2d` should also be able to.
