### ISSUE TITLE
scipy.integrate.solve_ivp diverges on a state space simulation well finished in MATLAB

### ISSUE THREAD

**Issue by hamidosooli** [scipy/scipy#12863]
Dear all,
Please visit the following link regarding the aforementioned problem in solve_ivp.
[scipy.integrate.solve_ivp diverges on a state space simulation well finished in MATLAB](https://stackoverflow.com/questions/63961631/scipy-integrate-solve-ivp-diverges-on-a-state-space-simulation-well-finished-in)
Regards,
Hamid

**Comment by ilayn** [comment]
Hi Hamid, without a reproducible example we can't do much about this. Do you mind stripping down your example *only* to the `solve_ivp` part by cleaning up the parts and posting here?

**Comment by hamidosooli** [comment]
Hi Ilayn, 
Thank you for your help. The problem was with the code itself!
