### ISSUE TITLE
Optimiser Powell does not accept bounds 

### ISSUE THREAD

**Issue by zohimchandani** [scipy/scipy#12876]
When the optimiser "Powell" is used with bounds, an error shows up but the docs state that it does accept bounds. 
https://docs.scipy.org/doc/scipy/reference/optimize.minimize-powell.html

Please clarify this

**Comment by mdhaber** [comment]
I believe bounds were added in gh-12172. What version of SciPy are you using?

**Comment by zohimchandani** [comment]
Thanks for the insight, updating scipy version has resolved the issue. 
I am however getting oscillatory behaviour in my loss function minimisation. Been tweaking around with ftol and xtol but I don't have an insight into what they are doing. Any links you could point me to? Thanks.

**Comment by andyfaff** [comment]
ftol and xtol refer to the changes in f and x below which the minimisation stops. For Powell they are relative changes. https://docs.scipy.org/doc/scipy/reference/optimize.minimize-powell.html#optimize-minimize-powell
