### ISSUE TITLE
Levy Stable Random Variates Code has a typo

### ISSUE THREAD

**Issue by bsdz** [scipy/scipy#12870]
The code to simulate stable random variates uses the following formulation (taken from Nolan, J., 1997. Numerical Calculation of Stable Densities and distributions Functions.):

![image](https://user-images.githubusercontent.com/6608130/93821048-eacdd880-fc55-11ea-8333-cbe57db3cde1.png)

Note in scipy code for alpha == 1:

```python
    def _rvs(self, alpha, beta, size=None, random_state=None):

        def alpha1func(alpha, beta, TH, aTH, bTH, cosTH, tanTH, W):
            return (2/np.pi*(np.pi/2 + bTH)*tanTH -
                    beta*np.log((np.pi/2*W*cosTH)/(np.pi/2 + bTH)))
```

whereas the factor of 2/pi should be applied to both parts of the difference, eg

```python
    def alpha1func(alpha, beta, TH, aTH, bTH, cosTH, tanTH, W):
        return (2/np.pi*(
                (np.pi / 2 + bTH) * tanTH -
                beta*np.log((np.pi/2*W*cosTH)/(np.pi / 2 + bTH))
            )
        )
```

This typo will be resolved in PR #9523 with supporting tests.

It is hard to demonstrate in current scipy as cdf code is unstable around alpha == 1. However, with branch from PR #9523 the following code demonstrates KS test failing with weak pvalue.

```python
>>> d1 = levy_stable(alpha=1., beta=-.5, scale=100., loc=1000.)
>>> kstest(d1.rvs(size=3000, random_state=1234), d1.cdf)
KstestResult(statistic=0.038524906711054685, pvalue=0.00026392725082308383)
```
Whereas with correction:

```python
KstestResult(statistic=0.019095943425717465, pvalue=0.22115623025632158)
``` 

#### Scipy/Numpy/Python version information:
1.5.2 1.19.2 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

**Comment by rgommers** [comment]
gh-9523 was merged, so closing this.
