### ISSUE TITLE
Levy Stable distribution uses parameterisation that is not location / scale aware

### ISSUE THREAD

**Issue by bsdz** [scipy/scipy#12871]
Levy Stable distribution uses Nolan's S1 parameterization for Levy Stable. This (parameterization) was historically ~~fixed~~ set by original random variate code (rvs) that used this parameterization. See related issue #12870.

For the S1 parameterization it is known for alpha == 1 it is not location scale aware. This following excerpt is taken from Nolan, J., 1997. Numerical Calculation of Stable Densities and distributions Functions:

![image](https://user-images.githubusercontent.com/6608130/93823407-acd2b380-fc59-11ea-85d8-0e581fe26b14.png)
 
The issue will be resolved by #9523 which corrects the location / scale for S1 parameterization and also introduces an optional S0 parameterization. Both are accompanied by supporting tests.

#### Scipy/Numpy/Python version information:
1.5.2 1.19.2 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

**Comment by rgommers** [comment]
gh-9523 was merged, so closing this.
