### ISSUE TITLE
Rotation.random vs stats.special_ortho_group

### ISSUE THREAD

**Issue by nisace** [scipy/scipy#12874]
Hi,

As I was looking for a way to generate random rotation matrices uniformly, I found these two methods:
- [scipy.stats.special_ortho_group](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.special_ortho_group.html)
- [scipy.spatial.transform.Rotation.random](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.random.html#scipy.spatial.transform.Rotation.random)

As far as I understand `Rotation.random` is just a special case of `stats.special_ortho_group` where `dim=3`.

Am I right or am I missing something? If correct, should these functions be refactored?

Thanks !

**Comment by ilayn** [comment]
The resulting "stack" via rotations are not necessarily unitary. In the ortho_group this is enforced, that's why row-wise the distribution is uniform on one but the other needs Haar.

**Comment by nisace** [comment]
Hi @ilayn, thanks for your response. Unfortunately I'm not sure I understand your answer. Could  you please elaborate?

Thanks

**Comment by ilayn** [comment]
In the ortho_group, the constraint is the result is an orthogonal(unitary if complex) matrix that A.T @ A should equal to identity. This requires a different probability distribution in the entries. The rotation one only generates random entries per row.

**Comment by nisace** [comment]
A rotation matrix has to be orthogonal by definition thus I guess both methods give orthogonal matrices (and it seems to after a quick test I just ran). 

`Rotation.random` does not sample the matrix coefficients directly. Instead it samples quaternions and then construct a rotation matrix from the sampled quaternions.

**Comment by ilayn** [comment]
Try it on the stack with n=5

**Comment by nisace** [comment]
```
>>> [np.max(np.abs(x @ x.T - np.eye(3))) for x in R.random(5, random_state=1234).as_matrix()]

[2.220446049250313e-16, 6.661338147750939e-16, 6.661338147750939e-16, 2.220446049250313e-16, 1.1102230246251565e-16]

```

**Comment by ilayn** [comment]
Yes but you are now converting to matrix so that's changing the output of the function. Ending up with a unitary matrix doesn't mean how you got there should be the same.

**Comment by ilayn** [comment]
You can also QR decompose a random matrix an use Q as a unitary matrix. Doesn't mean they serve the same purpose

**Comment by rkern** [comment]
`Rotation` is represented as a quaternion, not a matrix. `Rotation.random()` returns a `Rotation` in that quaternion form. It would be less efficient to randomly sample a matrix using `special_ortho_group()` and then convert it into the native quaternion form. I don't think there is an opportunity to refactor. Both do sample uniformly over SO(3), as far as I can tell. The difference is in their representations.

**Comment by nisace** [comment]
Thanks @rkern. My main concern was to misunderstand a difference between the distributions of the generated matrices. 

If both methods sample uniformly over SO(3) and efficiency prevent  `Rotation.random()` from using `special_ortho_group()`, my two questions are addressed.

Final question:  is it worth to mention it in the documentation?

Thanks again

**Comment by rkern** [comment]
What change to the documentation do you think would have helped you?

For example, I think a reference to `Rotation` from `special_ortho_group` could be helpful for people who want a random 3D rotation, knows the "SO(3)" terminology and happened to run into `special_ortho_group` first in their search. The reverse link is probably less useful. Maybe mentioned in the context of generating random rotation matrices in higher-dimensional spaces. Also, explaining the implementation details, why `Rotation.random()` doesn't use `special_ortho_group.rvs()`, is probably a distraction for the documentation.

**Comment by nisace** [comment]
Yes I agree for a reference to `Rotation` from `special_ortho_group`. IMHO it would be useful that such a reference confirms that both methods sample uniformly on SO(3).

Also agreed that implementation details might not to useful in the documentation

**Comment by ilayn** [comment]
I don't think Rotation.random is uniform in SO(3) or at least I don't see any regularization here https://github.com/scipy/scipy/blob/v1.5.2/scipy/spatial/transform/rotation.py#L920-L1013

It seems that it is uniformly sampling the angles and creating the corresponding matrices. That is not the same as picking unitary matrices uniformly over R^(3x3). I didn't check very throughly though.

**Comment by ilayn** [comment]
Yay, wikipedia to the rescue! Put much better than me rambling in ascii 

https://en.wikipedia.org/wiki/Rotation_matrix#Uniform_random_rotation_matrices

**Comment by rkern** [comment]
The resulting axis-angle representations look just fine to my eye, according to the criteria laid out in that article. The CDF of `theta` follows `(theta - sin(theta))/pi`, and the direction vectors are uniformly distributed over the surface of the unit sphere. I don't know why you are looking at the implementation of `as_matrix()`; that's not where the uniform sampling is taking place.

If you do find that `Rotation.random()` is not uniformly sampling over SO(3), that would be a bug to be fixed, not an intentional difference.

**Comment by ilayn** [comment]
That's because otherwise only the angles are picked uniformly, leading to the opening part of the wiki section no? 

I mean I don't need to split the hair on this but it seems that the angles are picked first and converted to rotation matrices which don't carry the uniform distribution to the set of unitary matrices. 

Either way, I don't see any duplication. That's what I mean with my QR argument.

**Comment by rkern** [comment]
Both `Rotation.random()` and `special_ortho_group.rvs()` uniformly sample over the set of SO(3) transformations with respect to the Haar measure. Generating matrices via `special_ortho_group.rvs()` and converting them to `Rotation` objects show the same distribution. Using QR decompositions on arbitrarily random matrices to create orthogonal matrices does _not_ create a uniform distribution with respect to the Haar measure.

FWIW, `Rotation.random()` is using the method laid out in that Wikipedia article in the paragraph starting "Another method uses unit quaternions...".

**Comment by ilayn** [comment]
OK we started talking past each other. I agree. That's why I was looking at `as_matrix` because I was trying to see where the normalization takes place. QR is as I mentioned above *does not* have the same uniform distribution. But anyways, I was trying say we don't need refactoring for this is my opinion.
