### ISSUE TITLE
FFT - documentation - examples - linspace construction

### ISSUE THREAD

**Issue by nadukandi** [scipy/scipy#12881]
cf. https://docs.scipy.org/doc/scipy/reference/tutorial/fft.html

In the examples given in the documentation of FFT shouldn't the `linspace` construction in
```
N = 600
# sample spacing
T = 1.0 / 800.0
x = np.linspace(0.0, N*T, N)
```
be
```x = np.linspace(0.0, (N-1)*T, N)```

in order for the entries in `x` to have `T` spacing?

**Comment by grlee77** [comment]
Yes, good catch. Are you interested in making a PR with a fix?

It seems the linspace call for generating the frequency coordinates is similarly off by one sampling bin and should be:
```Python
xf = np.linspace(0.0, 1.0/(2.0*T)-1/(N*T), N//2)
```

To help avoid such errors in generating the frequency samples, there is a `fftfreq` helper function that can be used instead:
```Python
xf = scipy.fft.fftfreq(N, T)[:N//2]
```

**Comment by nadukandi** [comment]
Yes, I will be happy to make a PR. 
Would appreciate help: how do I navigate to the file `fft.html`? 
I assume the PR has to be made from maintenance/1.5.x branch.

**Comment by peterbell10** [comment]
>The fft.html is generated from https://github.com/scipy/scipy/blob/master/doc/source/tutorial/fft.rst

That's correct

>I assume the PR has to be made from maintenance/1.5.x branch.

All PRs should be made against master. maintenance branches are only used for back-porting bug fixes.

I'll also add that `linspace(0.0, N*T, N, endpoint=False)` might be a clearer way to write it.

**Comment by grlee77** [comment]
Yes, the file to change is `doc/source/tutorial/fft.rst`. The PR should be made against the `master` branch. After merging a maintainer here can backport to 1.5.x as needed (not sure if there are currently plans for an additional 1.5.x release).

There are some [contributor guidelines here](https://docs.scipy.org/doc/scipy/reference/hacking.html), but much of the content may not be relevant for a simple documentation fix like this (i.e. no testing, benchmarks, etc. will be involved). There are also docs helping for [working with Git](https://docs.scipy.org/doc/scipy/reference/dev/gitwash/gitwash.html#git-development).

The beginning sections of the Git docs above list how to create a fork of the SciPy repository and configure an "upstream" remote if you need help with that.

**Comment by grlee77** [comment]
> I'll also add that linspace(0.0, N*T, N, endpoint=False) might be a clearer way to write it.

Yeah, that looks good. I had forgotten `linspace` had an endpoint argument.
