### ISSUE TITLE
Bug on scipy geometric standard deviation (scipy.stats.gstd)

### ISSUE THREAD

**Issue by rmorel** [scipy/scipy#12884]
I think I found a bug/error in [scipy's geometric standard deviation function](https://scipy.github.io/devdocs/generated/scipy.stats.gstd.html). The function value does not match the expected value.

#### Reproducing code example:

```python
import numpy as np
from scipy.stats import gstd

a = np.array([1.05, 1.02, 0.97])

print('Correct value: ', np.exp(np.std(np.log(a))))
print('gstd value: ', gstd(a))
```

#### Results from the code above:

```
Correct value:  1.0332815421561998
gstd value:  1.0409125506656505
```

The function value is wrong in this case. The correct result matches this nice [video tutorial](https://youtu.be/vWJXmRLDrrQ?t=821) and the result calculated using Wikipedia's definition of [geometric standard deviation](https://en.wikipedia.org/wiki/Geometric_standard_deviation).

#### Scipy/Numpy/Python version information:

```python
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
```

My version information:

```
1.5.0 1.18.5 sys.version_info(major=3, minor=8, micro=3, releaselevel='final', serial=0)
```

**Comment by rkern** [comment]
Use `gstd(a, ddof=0)` if you want to match the convention used by default in `np.std()`. Neither `ddof=0` or `ddof=1` is incorrect; it's just a choice of what you want. It is unfortunate that we do use different defaults in different places, but these codes were developed at different times by different people.

**Comment by rkern** [comment]
This difference is called out in the `Notes` section of the docstring.

**Comment by rmorel** [comment]
Yes, indeed. Thank you for the clarification.
