### ISSUE TITLE
derivative function returns undesired values at non-differentiable points.

### ISSUE THREAD

**Issue by devrimcavusoglu** [scipy/scipy#12887]
My issue is about [dervative function ](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.derivative.html). While it outputs correct for loads of points for a function, it outputs an undesired value for non-differentiable function at given points. I know scipy has approx_derivative, but I think the function would be better yielding an output like `None` or `np.nan` or just raise an error. I feel returning a real number at ponit where the function is not differentiable at is incorrect rather than deficient.

#### Reproducing code example:

```python
from scipy.misc import derivative


def relu(x):
    """ Differentiable at any point except x=0 """
    return max(0,x)

>>> derivative(relu, 0)
>>> 0.5

# Also a point close to 0 yields a similar undesired result.
>>> derivative(relu, 1e-5)
>>> 0.500005

# Even for a value like 0.5
>>> derivative(relu, 0.5)
>>> 0.75
```

#### Scipy/Numpy/Python version information:
```
1.5.2 1.19.2 sys.version_info(major=3, minor=8, micro=0, releaselevel='final', serial=0)
```

**Comment by rkern** [comment]
`derivative()` is a very simple function that does a central difference with a fixed spacing that you specify. The default is `dx=1`. It's meant for very simple situations with differentiable functions. It's not meant to discover non-differentiability or adaptively find the limiting value of the derivative as `dx` goes to 0.

**Comment by mdhaber** [comment]
I think it's worth adding a note about unreliable results at points where the derivative doesn't exist. I'll do that today.

**Comment by j-bowhay** [comment]
Arguably I think this could now be closed since `_derivative` is now a private function
