### ISSUE TITLE
binned_statistic_dd does not respect masked arrays

### ISSUE THREAD

**Issue by Jwink3101** [scipy/scipy#12898]
I guess it is debatable as to whether this is a feature request (i.e. it *should* support masked array) or a bug (it doesn't).

#### Reproducing code example:

Simple example:

```python
rnd = np.random.RandomState(seed=54)
x = rnd.uniform(high=2*np.pi,size=1000)
r2 = rnd.normal(size=len(x))
f = np.sin(x) + 0.1 * r2

# To demonstrate, make some of f NaNs based on r2 then use a masked array.
# We could just make a masked array but I want to *know* it's not working
f[np.abs(r2)>2] = np.nan

print(np.sum(np.isnan(f)))

ff = np.ma.masked_invalid(f)

stat,*_ = scipy.stats.binned_statistic(x,ff) # binned_statistic calls binned_statistic_dd
print(stat)
```

Of course, you could do:

```python
stat2,*_ = scipy.stats.binned_statistic(x,ff,statistic=np.nanmean) 
```
but  it is slower. In Jupyter:

```
%timeit scipy.stats.binned_statistic(x,ff)
%timeit scipy.stats.binned_statistic(x,ff,statistic=np.nanmean) 

193 µs ± 5.28 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
669 µs ± 26.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
Around 350% slower (with the same ~ 4% variation)

#### Error message:

N/A

#### Scipy/Numpy/Python version information:
```
print(scipy.__version__, numpy.__version__, sys.version_info)
1.5.0 1.18.5 sys.version_info(major=3, minor=8, micro=3, releaselevel='final', serial=0)
```
(Basically the latest in Anaconda I think)

**Comment by rlucas7** [comment]
I think this is a documentation gap. 

I’d be in favor of adding a line in the documentation that states explicitly. 

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.binned_statistic_dd.html

Reason being that if we propogate nan the. It would be difficult for end user to determine if the nan was a result from binning (no values) or from the behavior of the propogate argument. Plus as you’ve indicated m, a user is free to pass their custom callable that handles the nan how they desire. 

-Lucas Roberts

**Comment by Jwink3101** [comment]
> if we propogate nan then it would be difficult for end user to determine if the nan was a result from binning (no values) or from the behavior of the propagate argument.

I may be mistaken but I think that it would be clear since if the bin is empty, either due to masking and/or bad binning, it *should* be NaN either way. The advantage of accepting a masked array, (masked with NaNs or otherwise) is that it follows the expect behavior of masks.

(masks are not guaranteed to be supported, hence my uncertainty of this being a bug or a feature request but I think it would be good to support it if possible)

**Comment by rlucas7** [comment]
> On Oct 5, 2020, at 4:52 PM, Justin Winokur <notifications@github.com> wrote:
> 
> ﻿
> if we propogate nan then it would be difficult for end user to determine if the nan was a result from binning (no values) or from the behavior of the propagate argument.
> 
> I may be mistaken but I think that it would be clear since if the bin is empty, either due to masking and/or bad binning, it should be NaN either way. The advantage of accepting a masked array, (masked with NaNs or otherwise) is that it follows the expect behavior of masks.
> 
that is what would happen with propagate nan option. If you have a data processing job with several steps and you reuse bin edges then you could have both mapping to nan in a bin. 

It isn’t a major flaw or blocker but it is enough to suggest that it’s too much (at least to me). If you bring it up on the scipy-dev email list other people might have a different opinion. I’m not staunchly against, more like a -0.5 vote. 
> (masks are not guaranteed to be supported, hence my uncertainty of this being a bug or a feature request but I think it would be good to support it if possible)
> 
If we didn’t support custom callable my opinion might be different. We’ve had problems with supporting nan propagate, it’s difficult to get correct, and the benefit to cost seems too low to justify.

**Comment by mdhaber** [comment]
@Jwink3101 would you still like to leave this open as a feature request, or would stating it explicitly in the documentation resolve this issue?

**Comment by Jwink3101** [comment]
I personally would prefer to see support for them, though I don't think it would be trivial without a performance hit. 

At the very least, a documentation update. If it hasn't been done yet (I don't follow super closely) I'll try to accomplish it this weekend. 

Is there a mechanism for long term wants without leaving the issue open? If not, let's close it when the documentation is changed. 

Thanks!

**Comment by mdhaber** [comment]
> At the very least, a documentation update. If it hasn't been done yet (I don't follow super closely) I'll try to accomplish it this weekend.

OK, or if it's easier for you to make the suggestion here I can put it up as a PR.

> Is there a mechanism for long term wants without leaving the issue open? If not, let's close it when the documentation is changed.

Other than the roadmap, I don't think so. That would be nice. But if it's part of a broader want in stats (e.g. consistent masked array support), you could post it in gh-10577.

**Comment by mdhaber** [comment]
@Jwink3101 i don't think this has been addressed yet. Can you suggest what you'd like to see in the documentation and where you'd like it to go? I can also add a note to an appropriate issue that this was a feature request. Thank you!

**Comment by Jwink3101** [comment]
I have to look for the right place for it. And compare if other functions say what they do and don't support. It would be weird if this is the only one that talks about the lack of support for masked arrays.

**Comment by mdhaber** [comment]
Yeah, typically functions that _do_ support masked arrays are in `scipy.stats.mstats`. So maybe mentioning it isn't really needed? I could still add this as a feature request somewhere it will be remembered, though. The whole stats/mstats divide is unfortunate, so this isn't the only issue of it's kind!

**Comment by mdhaber** [comment]
I went ahead and mentioned this in gh-10577. I'm not sure that it's appropriate to patch just `binned_statistics_dd`to work on masked arrays or add a version of it to `mstats` before there is some broader discussion about our support for masked arrays, and I think you're right that addressing this in the documentation of `binned_statistic_dd` would not really be consistent. Since there's not much to be done here in the meantime, I think I'll go ahead and close, but let me know if you had something else in mind. Thank you @Jwink3101!
