### ISSUE TITLE
BUG: `special.riccati_yn`: Definition missing minus sign

### ISSUE THREAD

**Issue by marvync** [scipy/scipy#12895]
Please consider using the definition -xy_n(x) instead of xy_n(x).

The minus sign is important!

Thanks!

**Comment by Hugokth** [comment]
Please do consider this query, the minus sign not being implemented leads to loads of errors in calculations.
The Riccati-Bessel function of second kind **is** -xy_n(x)
Thank you in advance for considering this !

**Comment by mdhaber** [comment]
It does seem to be the more common convention to include the minus sign. However, it is noted in [Barnett 1996](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=fd8b1b4c3549edbec7f05d4d72271d4c5d5d8e3e) that there is another sign convention:

<img width="1097" alt="image" src="https://github.com/user-attachments/assets/8bb69030-cdff-4164-9fbe-16a9b47bad2d">

namely that used in [Abramowitz and Stegun](https://personal.math.ubc.ca/~cbm/aands/abramowitz_and_stegun.pdf) 10.3.

> the minus sign not being implemented leads to loads of errors in calculations.

It would probably lead to more errors in calculations if we were to suddenly change it on everyone. 

Here's what we can do:

- I will submit a PR to emphasize the sign convention being used in the documentation.
-  Reconsider the sign convention if this becomes a ufunc, presumably with a different name.

@steppi @izaid thought I should ping you as something to keep in mind as xsf develops.
