### ISSUE TITLE
Scipy.optimise call back function 

### ISSUE THREAD

**Issue by zohimchandani** [scipy/scipy#12890]
Every time I call the minimise function, there are a certain number of iterations that take place before the final loss is outputted. I would like to store each of these values. 
For eg I have the following code below: 

```
gl=[]
        def gen_callback(xk):
            gl.append(gen_loss(xk))
            
                
        #minimise loss for gen 
        gen_result = minimize(gen_loss, gen_weights, method='Powell', bounds = bounds_gen_weights, options={ 'maxiter': 2000, 'maxfev': n*3, 'ftol':1e-10, 'xtol': 1e-3}, callback =  gen_callback)
        gen_weights = gen_result.x
```

where I want to take the current value of gen_weights, calculate the gen_loss using those gen_weights and store them. However the method I am currently using as shown above doesnt do this. Any ideas on how to store each value of loss rather than just the final results?

**Comment by mdhaber** [comment]
It looks like you have the right idea. Minimum working examples and a description of what you are experiencing would help us to determine whether this is a bug. 

For this code:
```
import numpy as np
from scipy.optimize import minimize

def f(x):
    return np.sin(x)**2

gl = []
def cb(x):
    gl.append(x)

res = minimize(f, [3], callback=cb, method='powell')
print(gl)
```

the output is:
```
[array([3.14216788]), array([3.14159264]), array([3.14159265]), array([3.14159265])]
```
Apparently the callback isn't being called at the initial point. Is that the problem you're having?

**Comment by zohimchandani** [comment]
Please see https://github.com/zohimchandani/Code_share/blob/master/qwgans%2014.ipynb for a working example. You can ignore the initial code cells and only focus on the last cell and the graph at the end. I would like to plot all the loss values and not just the final ones which is what the code is currently doing.

**Comment by mdhaber** [comment]
I don't have those packages, so I can't run it. I don't see a problem with the way you're using `callback` or how you're appending the values to `gloss`. Besides the fact that there are only three values in `gloss`, though, there is no evidence that something is wrong, so I can't debug. From what I can see, there is an alternate explanation for the behavior that isn't related to the callback: the minimizer is exiting after one iteration. Two additional pieces of information would be helpful: what version of SciPy is this (`import scipy; scipy.__version__`), and please print `gen_result` each iteration.

**Comment by zohimchandani** [comment]
scipy version 1.5.2 
please see here for the requested results https://github.com/zohimchandani/Code_share/blob/master/qwgans%2014.ipynb

The results I am getting are correct but I just want to be able to plot them in a smoother fashion rather than the straight lines I am currently plotting. I want to be able to see the variation in values at each step of minimisation. 

Thankyou

**Comment by rkern** [comment]
He asked for `gen_result` because that will show some information about how many iterations each `minimize()` call actually performed. That will test the hypothesis that `minimize()` exits after the first iteration for some reason, which would explain why each call only adds one value to the list.

**Comment by zohimchandani** [comment]
Apoligies, I believe this is now correct: https://github.com/zohimchandani/Code_share/blob/master/qwgans%2014.ipynb

**Comment by rkern** [comment]
And the suspicions have been confirmed: only one iteration is performed (see `nit` in the results). Here are the relevant portions:

```
 message: 'Maximum number of function evaluations has been exceeded.'
    nfev: 24
     nit: 1
  status: 1
 success: False
```

I would recommend removing the `maxfev` parameter. It's too low and causing the optimization to fail.

**Comment by zohimchandani** [comment]
see here for updated results: https://github.com/zohimchandani/Code_share/blob/master/qwgans%2014.ipynb 

nit now is 4, I am guessing that the optimiser is performing gradient descent 4 times and arriving at the final answer?
Still not outputting all the loss values as there is a massive relative jump between the first and the second gloss.

**Comment by rkern** [comment]
It's telling you that it did 4 iterations, and `gloss` records 4 iterations. I'm not sure what loss values you think are missing. Note that `method='Powell'` is not a gradient descent method. It doesn't necessarily take small steps.

**Comment by zohimchandani** [comment]
Thanks for your previous comments. How would I get the corresponding `gen_weights `for each of those iterations?

**Comment by andyfaff** [comment]
The `gen_weights` correspond to the solution vector. Your call back function can be amended to store that.

**Comment by andyfaff** [comment]
Or better still, use the `return_all` keyword.

**Comment by rkern** [comment]
The corresponding `gen_weights` are the `x` that is passed to `gen_callback(x)`. For example, try the following to record the weights and the loss at each iteration:

```python
gen_weights_and_losses = []

def gen_callback(gen_weights):
    gen_weights_and_losses.append((gen_weights, gen_loss(gen_weights)))
```

**Comment by andyfaff** [comment]
Issue looks to have been addressed and no further discussion has happened for a while.
