### ISSUE TITLE
Incorrect documentation for Hilbert matrix

### ISSUE THREAD

**Issue by jacobthejones** [scipy/scipy#12894]
The docs for the Hilbert matrix (https://github.com/scipy/scipy/blob/v1.5.2/scipy/linalg/special_matrices.py) are incorrect. They currently state:
Returns the `n` by `n` array with entries `h[i,j] = 1 / (i + j + 1)`.

I believe it should be `h[i,j] = 1 / (i + j - 1)`.

**Comment by WarrenWeckesser** [comment]
`i` and `j` refer to the NumPy indices that one uses to access the elements, so the current documentation is correct.  For example, `h[0, 0] = 1 / (0 + 0 + 1) = 1`, `h[1, 3] = 1/(1 + 3 + 1) = 0.2`, etc.

**Comment by WarrenWeckesser** [comment]
I'm closing the issue, but further questions or comments are welcome.
