### ISSUE TITLE
Update on signature of `special/_ufuncs.py`

### ISSUE THREAD

**Issue by zwep** [scipy/scipy#12891]
Hi,

simple request.. in the signatures of many functions inside `special/_ufuncs` the signature does not coincide with the description text. For example the function `sph_harm`, the description contains this

```
  Parameters
    ----------
    m : array_like
        Order of the harmonic (int); must have ``|m| <= n``.
    n : array_like
       Degree of the harmonic (int); must have ``n >= 0``. This is
       often denoted by ``l`` (lower case L) in descriptions of
       spherical harmonics.
    theta : array_like
       Azimuthal (longitudinal) coordinate; must be in ``[0, 2*pi]``.
    phi : array_like
       Polar (colatitudinal) coordinate; must be in ``[0, pi]``.
```

However, the signature of the function is defined as 

`def sph_harm(x1, x2, x3, x4, *args, **kwargs)`

which makes it quite confusing on what each x1, x2, ... does. If this can be updated to

`def sph_harm(m, n, theta, phi, **kwargs):`

then that would remove unnecessary checking of the input variables.

**Comment by mckib2** [comment]
Hi @zwep, what you are observing is a consequence of how `ufunc` docstrings are created.

From the [ufunc docs](https://numpy.org/doc/stable/reference/ufuncs.html):
> __doc__ | A docstring for each ufunc. The first part of the docstring is dynamically generated from the number of outputs, the name, and the number of inputs. The second part of the docstring is provided at creation time and stored with the ufunc.

The `def sph_harm(x1, x2, x3, x4, *args, **kwargs)` part is only the first part and it's generated by the ufunc machinery.  The second part should be the complete docstring as in the documentation.

For example:
```python
>>> print(ss.sph_harm.__doc__)
sph_harm(x1, x2, x3, x4, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

sph_harm(m, n, theta, phi)

Compute spherical harmonics.

The spherical harmonics are defined as

.. math::

    Y^m_n(\theta,\phi) = \sqrt{\frac{2n+1}{4\pi} \frac{(n-m)!}{(n+m)!}}
      e^{i m \theta} P^m_n(\cos(\phi))

where :math:`P_n^m` are the associated Legendre functions; see `lpmv`.

Parameters
----------
m : array_like
    Order of the harmonic (int); must have ``|m| <= n``.
n : array_like
   Degree of the harmonic (int); must have ``n >= 0``. This is
   often denoted by ``l`` (lower case L) in descriptions of
   spherical harmonics.
theta : array_like
   Azimuthal (longitudinal) coordinate; must be in ``[0, 2*pi]``.
phi : array_like
   Polar (colatitudinal) coordinate; must be in ``[0, pi]``.
etc...
```

All the functions in `scipy.special._ufunc` are also autogenerated, but all the documentation is provided to the `ufunc` constructor, so it should all be there.

Are you not able to see the whole docstring?  Can you provide any more information about why you're only seeing the first `ufunc`-generated part?

**Comment by ev-br** [comment]
Might be a case for using `__text_signature__`, https://twitter.com/raymondh/status/1343063496330637313.

**Comment by mckib2** [comment]
I might be doing something wrong, but when I get `AttributeError: 'numpy.ufunc' object has no attribute '__text_signature__'` when I try to to set `__text_signature__'` for a `ufunc`

**Comment by mckib2** [comment]
@zwep If you're still wanting to remove the ufunc generated signature, the only way I see to do it is from within numpy.

The function `numpy.core._internal._ufunc_doc_signature_formatter` is called each time a docstring is requested by the ufunc.  Numpy would need to provide some mechanism to override this function or prevent it from being called in the ufunc C code.

**Comment by mdhaber** [comment]
Sounds like this is not actionable within SciPy, so closing.
