### ISSUE TITLE
when i was using 'python3 runtests.py --doc html' i am getting this error as i am totally a newbie here and also a newbie for open source contribution section as i wished to contribute by adding examples here if someone can  help me out i will be glad :) and if anybody have some different method which can word well for me so please 

### ISSUE THREAD

**Issue by 1sarthakbhardwaj** [scipy/scipy#12900]
Building, see build.log...
scipy/linalg/_generate_pyx.py: all files up-to-date
scipy/special/_generate_pyx.py: all files up-to-date
Running scipy\linalg\_generate_pyx.py
Running scipy\special\_generate_pyx.py
scipy\cluster\_hierarchy.pyx has not changed
scipy\io\matlab\mio_utils.pyx has not changed
scipy\io\matlab\streams.pyx has not changed
scipy\linalg\cython_blas.pyx has not changed
scipy\linalg\cython_lapack.pyx has not changed
scipy\linalg\_decomp_update.pyx.in has not changed
scipy\linalg\_matfuncs_sqrtm_triu.pyx has not changed
scipy\linalg\_solve_toeplitz.pyx has not changed
scipy\ndimage\src\_cytest.pyx has not changed
scipy\ndimage\src\_ni_label.pyx has not changed
scipy\optimize\_bglu_dense.pyx has not changed
scipy\optimize\_group_columns.pyx has not changed
scipy\optimize\cython_optimize\_zeros.pyx.in has not changed
scipy\optimize\_lsq\givens_elimination.pyx has not changed
scipy\optimize\_trlib\_trlib.pyx has not changed
scipy\signal\_max_len_seq_inner.pyx has not changed
scipy\signal\_peak_finding_utils.pyx has not changed
scipy\signal\_sosfilt.pyx has not changed
scipy\signal\_spectral.pyx has not changed
scipy\signal\_upfirdn_apply.pyx has not changed
scipy\sparse\_csparsetools.pyx.in has not changed
scipy\sparse\csgraph\_flow.pyx has not changed
scipy\sparse\csgraph\_matching.pyx has not changed
scipy\sparse\csgraph\_min_spanning_tree.pyx has not changed
scipy\sparse\csgraph\_reordering.pyx has not changed
scipy\sparse\csgraph\_shortest_path.pyx has not changed
scipy\sparse\csgraph\_tools.pyx has not changed
scipy\sparse\csgraph\_traversal.pyx has not changed
scipy\spatial\ckdtree.pyx has not changed
scipy\spatial\qhull.pyx has not changed
scipy\spatial\_hausdorff.pyx has not changed
scipy\spatial\_voronoi.pyx has not changed
scipy\interpolate\interpnd.pyx has not changed
scipy\special\cython_special.pyx has not changed
scipy\special\_comb.pyx has not changed
scipy\special\_ellip_harm_2.pyx has not changed
scipy\special\_test_round.pyx has not changed
scipy\special\_ufuncs.pyx has not changed
scipy\special\_ufuncs_cxx.pyx has not changed
scipy\stats\_stats.pyx has not changed
scipy\_lib\messagestream.pyx has not changed
scipy\_lib\_ccallback_c.pyx has not changed
scipy\_lib\_test_deprecation_call.pyx has not changed
scipy\_lib\_test_deprecation_def.pyx has not changed
scipy\cluster\_vq.pyx has not changed
scipy\fftpack\convolve.pyx has not changed
scipy\spatial\transform\rotation.pyx has not changed
scipy\interpolate\_bspl.pyx has not changed
scipy\interpolate\_ppoly.pyx has not changed
scipy\io\matlab\mio5_utils.pyx has not changed
scipy\cluster\_optimal_leaf_ordering.pyx has not changed
Cythonizing sources
lapack_opt_info:
lapack_mkl_info:
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
customize MSVCCompiler
  libraries mkl_rt not found in ['C:/Users/7sart/anaconda3\\Library\\lib']
  NOT AVAILABLE

openblas_lapack_info:
  libraries openblas not found in ['C:\\Users\\7sart\\anaconda3\\lib', 'C:\\', 'C:\\Users\\7sart\\anaconda3\\libs']
get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
customize GnuFCompiler
Could not locate executable g77
Could not locate executable f77
customize IntelVisualFCompiler
Could not locate executable ifort
Could not locate executable ifl
customize AbsoftFCompiler
Could not locate executable f90
customize CompaqVisualFCompiler
Could not locate executable DF
customize IntelItaniumVisualFCompiler
Could not locate executable efl
customize Gnu95FCompiler
Found executable C:\MinGW\bin\gfortran.exe
Using built-in specs.
COLLECT_GCC=C:\MinGW\bin\gfortran.exe
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/6.3.0/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-6.3.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --with-gmp=/mingw --with-mpfr=/mingw --with-mpc=/mingw --with-isl=/mingw --prefix=/mingw --disable-win32-registry --target=mingw32 --with-arch=i586 --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='MinGW.org GCC-6.3.0-1' --enable-static --enable-shared --enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --with-tune=generic --enable-libgomp --disable-libvtv --enable-nls
Thread model: win32
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)
  NOT AVAILABLE

openblas_clapack_info:
  libraries openblas,lapack not found in ['C:\\Users\\7sart\\anaconda3\\lib', 'C:\\', 'C:\\Users\\7sart\\anaconda3\\libs']
get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
customize GnuFCompiler
customize IntelVisualFCompiler
customize AbsoftFCompiler
customize CompaqVisualFCompiler
customize IntelItaniumVisualFCompiler
customize Gnu95FCompiler
Using built-in specs.
COLLECT_GCC=C:\MinGW\bin\gfortran.exe
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/6.3.0/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-6.3.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --with-gmp=/mingw --with-mpfr=/mingw --with-mpc=/mingw --with-isl=/mingw --prefix=/mingw --disable-win32-registry --target=mingw32 --with-arch=i586 --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='MinGW.org GCC-6.3.0-1' --enable-static --enable-shared --enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --with-tune=generic --enable-libgomp --disable-libvtv --enable-nls
Thread model: win32
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)
  NOT AVAILABLE

flame_info:
  libraries flame not found in ['C:\\Users\\7sart\\anaconda3\\lib', 'C:\\', 'C:\\Users\\7sart\\anaconda3\\libs']
  NOT AVAILABLE

atlas_3_10_threads_info:
Setting PTATLAS=ATLAS
  libraries lapack_atlas not found in C:\Users\7sart\anaconda3\lib
  libraries tatlas,tatlas not found in C:\Users\7sart\anaconda3\lib
  libraries lapack_atlas not found in C:\
  libraries tatlas,tatlas not found in C:\
  libraries lapack_atlas not found in C:\Users\7sart\anaconda3\libs
  libraries tatlas,tatlas not found in C:\Users\7sart\anaconda3\libs
<class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
  NOT AVAILABLE

atlas_3_10_info:
  libraries lapack_atlas not found in C:\Users\7sart\anaconda3\lib
  libraries satlas,satlas not found in C:\Users\7sart\anaconda3\lib
  libraries lapack_atlas not found in C:\
  libraries satlas,satlas not found in C:\
  libraries lapack_atlas not found in C:\Users\7sart\anaconda3\libs
  libraries satlas,satlas not found in C:\Users\7sart\anaconda3\libs
<class 'numpy.distutils.system_info.atlas_3_10_info'>
  NOT AVAILABLE

atlas_threads_info:
Setting PTATLAS=ATLAS
  libraries lapack_atlas not found in C:\Users\7sart\anaconda3\lib
  libraries ptf77blas,ptcblas,atlas not found in C:\Users\7sart\anaconda3\lib
  libraries lapack_atlas not found in C:\
  libraries ptf77blas,ptcblas,atlas not found in C:\
  libraries lapack_atlas not found in C:\Users\7sart\anaconda3\libs
  libraries ptf77blas,ptcblas,atlas not found in C:\Users\7sart\anaconda3\libs
<class 'numpy.distutils.system_info.atlas_threads_info'>
  NOT AVAILABLE

atlas_info:
  libraries lapack_atlas not found in C:\Users\7sart\anaconda3\lib
  libraries f77blas,cblas,atlas not found in C:\Users\7sart\anaconda3\lib
  libraries lapack_atlas not found in C:\
  libraries f77blas,cblas,atlas not found in C:\
  libraries lapack_atlas not found in C:\Users\7sart\anaconda3\libs
  libraries f77blas,cblas,atlas not found in C:\Users\7sart\anaconda3\libs
<class 'numpy.distutils.system_info.atlas_info'>
  NOT AVAILABLE

accelerate_info:
  NOT AVAILABLE

lapack_info:
  libraries lapack not found in ['C:\\Users\\7sart\\anaconda3\\lib', 'C:\\', 'C:\\Users\\7sart\\anaconda3\\libs']
  NOT AVAILABLE

lapack_src_info:
  NOT AVAILABLE

  NOT AVAILABLE

C:\Users\7sart\anaconda3\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
Running from SciPy source directory.
C:\Users\7sart\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1730: UserWarning:
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  return getattr(self, '_calc_info_{}'.format(name))()
C:\Users\7sart\anaconda3\lib\site-packages\numpy\distutils\system_info.py:1730: UserWarning:
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  return getattr(self, '_calc_info_{}'.format(name))()
Traceback (most recent call last):
  File "setup.py", line 590, in <module>
    setup_package()
  File "setup.py", line 586, in setup_package
    setup(**metadata)
  File "C:\Users\7sart\anaconda3\lib\site-packages\numpy\distutils\core.py", line 137, in setup
    config = configuration()
  File "setup.py", line 484, in configuration
    raise NotFoundError(msg)
numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found.
To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
See site.cfg.example in the Scipy source directory and
https://docs.scipy.org/doc/scipy/reference/building/index.html for details.

Build failed! (0:00:11.713980 elapsed)

**Comment by rgommers** [comment]
So you're on Windows, and the error message tells you that you need a BLAS/LAPACK library (like OpenBLAS). You can do one of two things:

1. Follow https://docs.scipy.org/doc/scipy/reference/building/windows.html#building-openblas to build and install OpenBLAS
2. Use the Windows Subsystem for Linux (WSL) and follow http://scipy.github.io/devdocs/dev/contributor/quickstart_ubuntu.html#quickstart-ubuntu

I think you're going to have an easier time with (2), but both should work.

**Comment by 1sarthakbhardwaj** [comment]
I have my device booted with both windows and ubuntu 20.04.1 if there is
any compatibility issue on windows so I can clone it in my ubuntu setup,
I have one noob question as this is the first time that I am trying to make
a change in a forked directory so I was having a doubt that for adding
examples what steps I have to follow
- first, I need to build scipy, after that the instructions given in
readme.?

**Comment by ilayn** [comment]
So as a summary, you need to be able to build documentation. Since our documentation includes usable examples (and our test suite tries these examples), behind the scenes you should be able to build SciPy itself. 

In Linux world, this requires you to have the liblapack and other dependencies installed. You can follow the guides for that given above and it should work rather easily. 

On Windows, because we don't have `liblapack` and all the other goodies, there is also another annoying step; building your own `libblas` and `liblapack` etc. That is the time consuming and difficult part mentioned above. 

But both lead to the same end result -> building SciPy. But please follow the guides one step at a time and don't rush it. Most problems disappear if you can borrow us a bit of your patience.

**Comment by 1sarthakbhardwaj** [comment]
hi there, I have done as directed and reached on step no 19,

   1.
   http://scipy.github.io/devdocs/dev/contributor/quickstart_ubuntu.html#quickstart-ubuntu
via
   this link,

when I use python3 setup.py build_ext --inplace. the command I am getting
this error 'error: option --inplace. not recognized'
I have faced some issues earlier also but I somehow got their solution on
the internet but I am unable to tackle it and in one case I have avoided it
and tried to run python3 runtests.py -v. runtests.py
then it is showing this error  - "tests.py: error: argument --verbose/-v:
ignored explicit argument '.'"
  I think it will be due to this inplace error as it ensures that the
compiling happens in the SciPy directory and I am getting error in this. so
please help

**Comment by rgommers** [comment]
There are now more compact instructions: http://scipy.github.io/devdocs/dev/contributor/quickerstart_conda.html

Those definitely work, as does `python setup.py build_ext -i`, so I'll close this issue.
