### ISSUE TITLE
How does powell control the number of iterations in scipy minimize?

### ISSUE THREAD

**Issue by R2h1** [scipy/scipy#12914]
I want to record the loss value for each epoch during the experiment

**Comment by rkern** [comment]
I recommend asking this kind of question on the [scipy-user](https://www.scipy.org/scipylib/mailing-lists.html) mailing list so we can have a better conversation drawing from a wider audience. We try to keep the Github issues to bugs and feature requests and such.

**Comment by andyfaff** [comment]
If you'd like to record the objective value for each iteration you have two options. The first is to use a callback function which will furnish the `x` vector at the end of each iteration. Alternatively you could use the `return_all` keyword that will give the `x` vectors for each iteration (as an attribute of `OptimizeResult`) when `minimize` returns.
