### ISSUE TITLE
BUG: numerical precision, use gammaln in nct.mean

### ISSUE THREAD

**Issue by josef-pkt** [scipy/scipy#12919]
possible precision improvement, no bug yet

I was looking at the mean for nct.
I didn't find any problems in my examples with nct mean, but the gamma values were very large 1e60.

using gammaln should improve precision
`np.exp(special.gammaln(df/2.-0.5) - special.gammaln(df/2.))`

```
df = 100
special.gamma(df/2.-0.5), special.gamma(df/2.)
(8.667601843135274e+61, 6.082818640342675e+62)
```

**Comment by josef-pkt** [comment]
ok bug, when it overflows

```
stats.nct.mean(1000, 2)
nan
```

at df=100, the gamma values are inf

**Comment by josef-pkt** [comment]
AFAIU: c11 should converge to 1   (roughly normal distribution limit of large df)

```
df = 10000
gfac = np.exp(special.gammaln(df/2.-0.5) - special.gammaln(df/2.))
c11 = np.sqrt(df/2.) * gfac
c11
1.000075007811785
``

**Comment by rlucas7** [comment]
Hi Josef 

Might be this one:

https://github.com/scipy/scipy/blob/01d8bfb6f239df4ce70c799b9b485b53733c9911/scipy/stats/_continuous_distns.py#L6033

I can see about a test case based on your example here to see if it fixes. 

-Lucas Roberts

**Comment by rlucas7** [comment]
Some numerical confirmation and investigations on my laptop: 

```
>>> from scipy.stats import nct
>>> nct.mean(1000, 2)
/Users/rlucas/scipy-dev/scipy/scipy/stats/_continuous_distns.py:5875: RuntimeWarning: invalid value encountered in true_divide
  gfac = sc.gamma(df/2.-0.5) / sc.gamma(df/2.)
nan
>>> nct.mean(350, 2)
nan
>>> nct.mean(340, 2)
2.004425323005375
>>> nct.mean(345, 2)
nan
>>> nct.mean(343, 2)
2.0043864996470164
>>> nct.mean(344, 2)
0.0
>>> nct.mean(345, 2)
nan
```
So I'm seeing the same thing and on my machine 345 is the limit. 

Now the underlying issue we suspect is this line  

https://github.com/scipy/scipy/blob/01d8bfb6f239df4ce70c799b9b485b53733c9911/scipy/stats/_continuous_distns.py#L6033

so let's confirm that threshold and behavior there

```
>>> from scipy.special import gamma
>>> for df in range(340, 351):
...     gfac = gamma(df/2.-0.5) / gamma(df/2.)
...     print("df", df)
...     print("gfac", gfac)
... 
df 340
gfac 0.07686620227521021
df 341
gfac 0.07675291402619422
df 342
gfac 0.07664012520969488
df 343
gfac 0.07652783216687982
df 344
gfac 0.0
__main__:2: RuntimeWarning: invalid value encountered in double_scalars
df 345
gfac nan
df 346
gfac nan
df 347
gfac nan
df 348
gfac nan
df 349
gfac nan
df 350
gfac nan
``` 
so it looks like this is (a) source of bug.
