### ISSUE TITLE
Rename Sample Based Integration Methods to Comply with Code of Conduct

### ISSUE THREAD

**Issue by justinkterry** [scipy/scipy#12924]
**Is your feature request related to a problem? Please describe.**

Per a popular post on reddit*, 3/4 of the sample based integrated method names are, or are very close to, popular sexual-ish diminutives or slurs:

Simp: A diminutive for men, most commonly used in the context of the porn industry
Trapz: A slur for transgender women with strong sexual overtones
Cumtrapz: I'm not explaining this one on my professional github account

As I understand, this is probably against the libraries new code of conduct in addition to just generally being troubling.

*https://www.reddit.com/r/programminghorror/comments/j6sd61/i_was_just_looking_at_the_documentation_for/

**Describe the solution you'd like**

Rename the methods at issue to not have weird sexual overtones. It's one thing if a reasonable random abbreviation for something to sound vaguely sexual. This many together just feels awkward and a bit tone-deaf, and the reception on Reddit seems to substantiate this. At minimum, it certainly isn't best practices for design inclusivity.

**Describe alternatives you've considered**

**Additional context (e.g. screenshots)**

**Comment by rgommers** [comment]
Thanks for bringing this to our attention @justinkterry. I - and I believe most/all SciPy maintainers and regular contributors - definitely desire to make SciPy a project that feels inclusive and welcoming to everyone.

As a reply on Reddit pointed out, these names were taken over from Matlab. They're also very old, a commit log search shows they were added right when SciPy was started in 2001. So I'm pretty sure the original developers didn't foresee 20 years ago that the terms could gain a negative colloquial meaning.

To be honest I did not know these terms are now used as slurs. A Google search (in an incognito window to make sure I get unbiased results) shows that the first results for `simps` are indeed for the slur, while for `trapz` the first two pages of results are all code-related (from NumPy, SciPy, Matlab, R, Julia - those all use the same `trapz` name). The slur seems to be "trap", not "trapz".

My conclusion from the above is that we should leave `trapz` and `cumtrapz` alone - those functions are also fairly heavily used. `simps` isn't used nearly as much, and is more clearly a slur, so there's a couple of things we can consider doing:

1. Move it in the function listing, so the 3 terms aren't back to back (no cost to that, so easy to do).
2. Add a note to the `simps` docstring on etymology.
3. Rename `simps` to `simpson` or `simpsons`, and either deprecating `simps` or leaving it as an undocumented alias while only keeping `simpson` in the function listing.

I think a deprecation for a function that's been around for 20 years and no one has ever complained about in that time is a bit much, but I am fine with implementing the aliasing option - that's low effort/cost and solves the identified problem.

**Comment by josef-pkt** [comment]
Never heard of simps, but I suggest Homer instead of Simpson, or maybe Bart.

(I'm not sure terms used in porn industry are of common usage/overtone in scientific areas.)

**Comment by josef-pkt** [comment]
I guess homer is out.

I found a definition for simp that says
"A simp or simpson or homer or homer simpson is a vagina that looks like homer simpson's mouth."
`r/simps/` >18 years

It will be difficult to rename fast enough to stay ahead of new slang words.

**Comment by justinkterry** [comment]
So I should've clarified a bit- "trapz" isn't a slur, "trap" is, yes. The problem is that the plural "traps" is used in all the popular hate-speach-y idioms based around "trap" that have become very popular with the US alt right/4chan demographic in. It's to the point now where youtube videos, watched by millions of people, that are intended to deprogram people who have fallen into the US alt right now include sections on "traps." Cumtrapz in particular, per a straw poll of other American CS PhD students I was telling this story to at my group meeting, was especially "holy shit they actually still have a function called that?"

As far as what to do, my personal preference at least would be aliasing.

**Comment by ilayn** [comment]
If "trapezoidal integration" makes it to 4chan in the refugee context we will have to stop using this method completely. In other words, there needs to be some responsibility on the user too about taking offense. This is a very famous paper in my domain

![image](https://user-images.githubusercontent.com/1303842/95397559-cfc0c100-0903-11eb-8c17-1d95e0c42f75.png)

and everyone calls it FanTitsDoyle paper, including at keynotes etc. You giggle once at the beginning of grad school then nobody takes notice afterwards.

**Comment by justinkterry** [comment]
@ilayn My point here is about inclusive design practices, not removing all possible sources of offense from the world. Similar thinking, for example, led to the famous NIPS machine learning conference being renamed to NeurIPS a few years back.

**Comment by ilayn** [comment]
I totally agree. But also a bit of context helps to clear out things before they get offensive. That's what I am trying to emphasize. Removing is not the only option here to make it inclusive.

I am more in favor of the etymology option since then everyone will know these alternative meanings (I didn't even know until today because it is probably a very cultural-specific thing). But then again please take note of the paper I've put above and the software I've listed.

**Comment by rgommers** [comment]
`simps` rename to `simpson` is in PR gh-12927.

> Cumtrapz in particular, per a straw poll of other American CS PhD students I was telling this story to at my group meeting, was especially "holy shit they actually still have a function called that?"

A search does indeed find comments like _"Every time I use the cumulative trapezoidal numerical integration function in Matlab I'm astonished at the choice of abbreviation"_. It's not pretty - we'll add this to the long list of bad ideas that were taken from Matlab early on in SciPy's life. Let's rename that one too. How about `cumul_trapz`?

To address `trapz` and also `cumsum`, `cumprod`: those are widely used in all numerical computing languages, and searches bring up code examples on the first several pages, nothing offensive. So we should not go and rename those.

**Comment by rkern** [comment]
Expanding the names `simps->simpson` and `trapz->trapezoid` are wins for accurately naming the methods implemented in the functions. If we're going to pay the cost to change some of them, let's go ahead and do all three.

**Comment by justinkterry** [comment]
Just renaming simp and cumtrapz would work for me personally. 

That being said, I too think that `cumulative_trapezoid` is just a better sounding name than `cumul_trapz`, and if we go that direction then then leaving `trapz` as is would be odd.

**Comment by justinkterry** [comment]
I'll also say that in my view `cumsum`, `cumprod` are rather suboptimal names, but aren't nearly as troubling as cumtrapz.

**Comment by rgommers** [comment]
Thanks for the input everyone. Okay, sounds like we want to go with `trapezoid` and `cumulative_trapezoid`, I'll send a follow-up PR for those.

**Comment by larsoner** [comment]
Thanks @rgommers ! Okay to mark that next PR as closing this issue @justinkterry ?

**Comment by justinkterry** [comment]
Works for me.
