### ISSUE TITLE
The use of starred expressions to create data detracts from understanding required data structure 

### ISSUE THREAD

**Issue by maxshowarth** [scipy/scipy#12929]
https://github.com/scipy/scipy/blob/01d8bfb6f239df4ce70c799b9b485b53733c9911/scipy/interpolate/interpolate.py#L2369

Starred expressions can't be readily examined. For users who are attempting to familiarize themselves with the required data structures for RegularGridInterpolator, it adds unnecessary additional complexity.

I would suggest creating the meshgrid outside of the function call so that the purpose of the starred expression is more easily understood.

Despite the description of the structure of ```data``` below, it is difficult to adapt to unique user use cases.

**Comment by ev-br** [comment]
PR welcome

**Comment by maxshowarth** [comment]
Great - I will start taking a look.
