### ISSUE TITLE
incorrect output for pdist and cdist with 'minkowski' metric and infinite p

### ISSUE THREAD

**Issue by rfezzani** [scipy/scipy#12926]
`scipy.spatial.distance.pdist` and `scipy.spatial.distance.cdist` always return ones when the `metric` parameter is set to `"minkowski"` and `p` to `np.inf`. This doesn't happen when you set `metric` to `scipy.spatial.distance.minkowski`.

This is because `pdist` and `cdist` call internally the C function [`minkowski_distance`](https://github.com/scipy/scipy/blob/master/scipy/spatial/src/distance_impl.h#L398) while `scipy.spatial.distance.minkowski` calls `numpy.linalg.norm`.

#### Reproducing code example:

```python
>>> from scipy.spatial.distance import pdist, cdist, minkowski
>>> import numpy as np
>>> 
>>> x = np.random.randn(5, 1)
>>> y = np.random.randn(5, 1)
>>> 
>>> print(f"x = {x}")
x = [[ 0.17434791]
 [-0.59212961]
 [-0.5377257 ]
 [ 0.7551881 ]
 [ 2.12660604]]
>>> print(f"y = {y}")
y = [[-0.67732225]
 [-0.11041384]
 [ 0.87626855]
 [-2.31480127]
 [-0.79008986]]
>>> cdist(x, y, 'minkowski', p=np.inf)
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])
>>> pdist(x, 'minkowski', p=np.inf)
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
```
but when you call `pdist` and `cdist` with the `metric ` parameter set to `scipy.spatial.distance.minkowski`, you get the correct result:
```python
>>> cdist(x, y, minkowski, p=np.inf)
array([[0.85167017, 0.28476175, 0.70192064, 2.48914918, 0.96443778],
       [0.08519265, 0.48171577, 1.46839816, 1.72267166, 0.19796025],
       [0.13959656, 0.42731186, 1.41399425, 1.77707557, 0.25236417],
       [1.43251035, 0.86560194, 0.12108046, 3.06998937, 1.54527796],
       [2.80392829, 2.23701988, 1.25033748, 4.44140731, 2.9166959 ]])
>>> pdist(x, minkowski, p=np.inf)
array([0.76647752, 0.71207361, 0.58084018, 1.95225812, 0.05440391,
       1.3473177 , 2.71873564, 1.29291379, 2.66433173, 1.37141794])
>>> 

```

#### Scipy/Numpy/Python version information:
```python
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.5.2 1.17.4 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by rlucas7** [comment]
Seems two options that I can see:

1. Add an elif block somewhere here:

https://github.com/scipy/scipy/blob/7a7843bc1b54968ee99796333743c73608c0638d/scipy/spatial/distance.py#L2797

For minkowski string and p inf then call the appropriate numpy norm, would be possibly pure python change.

2. Add an if/else block within minkowski_distance. It doesn’t look like there is any checking within that functions for the inf case.

https://github.com/scipy/scipy/blob/7a7843bc1b54968ee99796333743c73608c0638d/scipy/spatial/src/distance_impl.h#L398

Maybe others too.

First one might be easier to implement if someone is less familiar with c and python and our package/language linkages etc. Also, this approach might be slower than pure c fix-I didn’t check just a guess-not sure how important that is for this method. 

I’m not super familiar with the spatial package so would wait for comments from someone with more experience in spatial before proceeding.

-Lucas

**Comment by rfezzani** [comment]
I was thinking about the 2. option :slightly_smiling_face:, I will try to come with a PR :wink:

**Comment by rfezzani** [comment]
OK, I see that it is supposed to be fixed in master (see [here](https://github.com/scipy/scipy/blob/master/scipy/spatial/src/distance_impl.h#L603) and [here](https://github.com/scipy/scipy/blob/master/scipy/spatial/src/distance_impl.h#L854)).

**Comment by rfezzani** [comment]
In other words, it is duplicate of #8776 :wink:
