### ISSUE TITLE
About anderson_ksamp and two-sample version of Anderson-Darling test

### ISSUE THREAD

**Issue by HyoungsungKim** [scipy/scipy#12928]
Are `anderson_ksamp` with k = 2 and two-sample version of Anderson-Darling test different?

Currently i am testing goodness-of-fit using Anderson-Daring(AD) test.

In reference of [aderson_ksamp](http://www.cithep.caltech.edu/~fcp/statistics/hypothesisTest/PoissonConsistency/ScholzStephens1987.pdf), equation (1) shows two-sample version of AD test. 

If I understand correctly, <img src="https://render.githubusercontent.com/render/math?math=A^2_{mn}">  is always positive or 0. Because intuitively its numerator is square value(distance) and weight which is used as denominator is always same or larger than 0.

Therefore i expected `statistic` which is returned by `anderson_ksamp` is not less than 0. However i got a negative result:

```python
from scipy.stats import anderson_ksamp
for i in range(len(data_interval)):
    result = anderson_ksamp([histogram_val_list[i], expected_val_list[i]])
    print(result)
```
where `histogram_val_list` is histogram values of observed results in simulation and `expected_val_list` is result of empirical cumulative distribution function(CDF). What i want to know is these are drawn from same distribution or not.

Results are
```
Anderson_ksampResult(statistic=-1.1198006812943295, critical_values=array([0.325, 1.226, 1.961, 2.718, 3.752, 4.592, 6.546]), significance_level=0.25)
Anderson_ksampResult(statistic=-1.1820361279065328, critical_values=array([0.325, 1.226, 1.961, 2.718, 3.752, 4.592, 6.546]), significance_level=0.25)
Anderson_ksampResult(statistic=-1.0107843547763211, critical_values=array([0.325, 1.226, 1.961, 2.718, 3.752, 4.592, 6.546]), significance_level=0.25)
```
As you can see, i got negative results.

I am confusing a meaning of  <img src="https://render.githubusercontent.com/render/math?math=A^2"> in <img src="https://render.githubusercontent.com/render/math?math=A^2_{mn}">.

Is it `A` * `A`(square of `A`)? or just name is `A^2`? and is it right to return negative value when two-samples are given?

Thank you for reading :sob:

**Comment by HyoungsungKim** [comment]
I skimmed [reference paper](http://www.cithep.caltech.edu/~fcp/statistics/hypothesisTest/PoissonConsistency/ScholzStephens1987.pdf).

In chap 4 of this paper authors mentioned that they standardized  <img src="https://render.githubusercontent.com/render/math?math=A^2">. This standardized form is defined as <img src="https://render.githubusercontent.com/render/math?math=T_{kN}"> . I may think it is implemented in this [line](https://github.com/scipy/scipy/blob/maintenance/1.5.x/scipy/stats/morestats.py#L2052).

However, in document of `anderson_ksamp`, it is mentioned that `statistic` is normalized statistic. Is it right normalized is same with standardized that described in reference?

**Comment by chrisb83** [comment]
indeed, the statistic is normalized / standardized as described in the paper. it is a bit hidden in the documentation. substracting the mean k-1 of A_{kN}^2 explains the negative values. does it answer your question?

**Comment by HyoungsungKim** [comment]
@chrisb83 Thank you for the answer :+1: Now it is clear.
