### ISSUE TITLE
the length of istft's return of scipy will not be the same with the oringal data.

### ISSUE THREAD

**Issue by zhaozhh** [scipy/scipy#12932]
My issue is about the length of istft's return of scipy will not be the same with the oringal data.

#### Reproducing code example:

```
from scipy import signal
import numpy as np
fs = 1023
N = 10*fs
nperseg = 512
amp = 2 * np.sqrt(2)
noise_power = 0.001 * fs / 2
time = np.arange(N) / float(fs)
carrier = amp * np.sin(2*np.pi*50*time)
noise = np.random.normal(scale=np.sqrt(noise_power),
                         size=time.shape)
x = carrier + noise

f, t, Zxx = signal.stft(x, fs=fs, nperseg=nperseg)
_, xrec = signal.istft(Zxx, fs)

print("the length of x is " ,len(x))
print("the length of xrec is " , len(xrec))  
```

#### Error message:

```
The output are:
the length of x is  10230
the length of xrec is  10240
```

**Comment by e-q** [comment]
This is a result of zero padding in `stft`, given that your input signal length does not fit exactly into an integer number of windowed segments; see the documentation for the `padded` keyword argument. In your example `np.allclose(x,xrec[:x.size])` evaluates to `True`, so the input signal is indeed being faithfully recovered.
