### ISSUE TITLE
ModuleNotFoundError: No module named 'scipy.sparse.csgraph._tools'

### ISSUE THREAD

**Issue by FanyouMeng** [scipy/scipy#12930]
The error "ModuleNotFoundError: No module named 'scipy.sparse.csgraph._tools'" suddenly appeared when runing code under python 3.6 enviroment with pycharm and I have scipy 1.5.0
In fact, the project processed successfully but only 5mins later (after I added just single one print statement), the error occured. I changed nothing and triple checked the settings!  Could someone help me out? I have no idea whether the module scipy was updated or the pycharm got some bugs.
Thanks!

**Comment by rgommers** [comment]
No idea what is going on here. Probably an installation issue, hard to say without a traceback.

We dropped Python 3.6 already, so I don't think there's anything actionable here - hence I'll close this issue.
