### ISSUE TITLE
Allowing hierarchy clustering taking in "out" array as a parameter

### ISSUE THREAD

**Issue by WweiL** [scipy/scipy#12944]
**Is your feature request related to a problem? Please describe.**
The problem arises when I tried to cluster a fairly large dataset. I got an out of memory error because in this line:

https://github.com/scipy/scipy/blob/master/scipy/cluster/hierarchy.py#L1060

`y = distance.pdist(y, metric)` tried to allocate too much space(n^2 level where n is the sample number).

**Describe the solution you'd like**
It seems that pdist is also aware of this and allows a parameter  "out" which would be filled if not none. So one can pass a np.memmap to it. So maybe in hierarchy.py, we could also allow the linkage() function, and those wrappers (like ward(), single(), etc.) to take in such an "out" parameter.

**Describe alternatives you've considered**

**Additional context (e.g. screenshots)**
I could add a pull request if you think this is doable.

**Comment by rgommers** [comment]
All clustering methods use (at least) `O(N^2)` memory, and I don't think we want to go as far as making those methods work when `const * N^2` with `const` being reasonably small still does not fit in memory. It's not just a matter of that one `pdist` call, the Cython code in `_hierarchy.pyx` for `nn_chain` and `fast_linkage` also takes that much memory.

I think it'd be better to batch your dataset somehow @WweiL, or use a larger-memory machine.

**Comment by WweiL** [comment]
Thanks for the reply.
