### ISSUE TITLE
Determining parameter in scipy.stats

### ISSUE THREAD

**Issue by Ashish0216** [scipy/scipy#12943]
Hello @WarrenWeckesser,

This is a query ! Since there are no means to ask this query,  I have to do it Issue segment.

Was trying to understand how def fit () works . Complex !

Just keen to understand  in ` vals = optimizer(func, x0, args=(ravel(data),), disp=0)` , how does func looks like say for example Foldnorm or Rayleigh distribution.

Was only able to replicate offline till `fit_loc_scale`.

Any thread / Information / Clarity will be helpful

Thanks in Advance.

**Comment by rkern** [comment]
You can ask questions like this on the [scipy-user mailing list](https://www.scipy.org/scipylib/mailing-lists.html). The `func` is just the negative log-likelihood function, essentially the sum of the logpdfs for all of the datapoints. See [`_penalized_nnlf()`](https://github.com/scipy/scipy/blob/master/scipy/stats/_distn_infrastructure.py#L2155-L2207)

**Comment by peterbell10** [comment]
Since there's no bug, I'll close this.
