### ISSUE TITLE
Should the minimum numpy for AIX be bumped to 1.16.5

### ISSUE THREAD

**Issue by hmaarrfk** [scipy/scipy#12940]
https://github.com/scipy/scipy/blob/37b650e04f3bf49bc11cfcd18f2848ad4f957a0d/pyproject.toml#L9

I'm trying to update the minimum numpy for scikit-image, and noticed that you have different numpy minor versions for AIX and not AIX.

Is there a reason for this?

<details>
Historic conversation can be found here:
https://github.com/scipy/scipy/commit/46df8c0013e97a025376f1bd0ef07bbd8372aca7
</details>

**Comment by rgommers** [comment]
Yes, older numpy versions are simply missing bug fixes that were needed for building on AIX. This may continue to happen since we don't have CI for AIX, so fixes come in ad-hoc.

**Comment by rgommers** [comment]
But in this case, the minimum numpy version can never be _lower_ for AIX, that's an oversight.

**Comment by hmaarrfk** [comment]
Thanks for the quick explanation. PR made.
