### ISSUE TITLE
A possible typo in scipy.stats.weightedtau

### ISSUE THREAD

**Issue by taoky** [scipy/scipy#12951]
My issue is about a possible typo in [line 4711 in file scipy/stats.py](https://github.com/scipy/scipy/blob/37b650e04f3bf49bc11cfcd18f2848ad4f957a0d/scipy/stats/stats.py#L4711).

According to the [SciPy documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.weightedtau.html#scipy.stats.weightedtau), 

> NaNs are considered the smallest possible score.

However, it seems that when there're NaNs in variable `y`, it would not be converted by `__toint64()` (unless `x` and `y` has different `dtype`).

#### Reproducing code example:

```
>>> from scipy import stats
>>> import numpy as np
>>> x = [12.0, 2.0, 1.0, 12.0, 2.0]
>>> y = [1.0, 4.0, 7.0, 1.0, 0.0]
>>> stats.weightedtau(x, y)
WeightedTauResult(correlation=-0.5669496815368272, pvalue=nan)
>>> y = [1.0, 4.0, 7.0, 1.0, np.nan]
>>> stats.weightedtau(x, y)
WeightedTauResult(correlation=-0.7722528001959581, pvalue=nan)
```

#### Scipy/Numpy/Python version information:

```
1.5.2 1.19.2 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
```

**Comment by peterbell10** [comment]
Fixed in #12955
