### ISSUE TITLE
[Documentation question] Would it be more precise to specify p in [0,1] for probability distributions? 

### ISSUE THREAD

**Issue by WillTirone** [scipy/scipy#12952]
Hi all, 

I was looking at a few of the discrete distributions (Geometric: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.geom.html, Binomial: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.binom.html) and noticed that they don't specify 0 < p < 1 though these are included in the argcheck (obviously, since probabilities are only between 0 and 1). 

```python 
class binom_gen(rv_discrete):
    r"""A binomial discrete random variable.
    %(before_notes)s
    Notes
    -----
    The probability mass function for `binom` is:
    .. math::
       f(k) = \binom{n}{k} p^k (1-p)^{n-k}
    for ``k`` in ``{0, 1,..., n}``.
    `binom` takes ``n`` and ``p`` as shape parameters.
    %(after_notes)s
    %(example)s
    """
    def _rvs(self, n, p, size=None, random_state=None):
        return random_state.binomial(n, p, size)

    def _argcheck(self, n, p):
        return (n >= 0) & (p >= 0) & (p <= 1)
```

Would this be a desired contribution to the docstring? For example: 
```python 
class binom_gen(rv_discrete):
    r"""A binomial discrete random variable.
    %(before_notes)s
    Notes
    -----
    The probability mass function for `binom` is:
    .. math::
       f(k) = \binom{n}{k} p^k (1-p)^{n-k}
    for ``k`` in ``{0, 1,..., n}``.
    `binom` takes ``n`` and ``p`` as shape parameters, 
     where 0<p<1 is the probability of success and 
     1-p is the probability of failure. 
    %(after_notes)s
    %(example)s
    """

**Comment by WarrenWeckesser** [comment]
Yes, that would be great, a pull request would be welcome.  Just be sure that the range includes the endpoints, i.e. `0 <= p <= 1`.

**Comment by WillTirone** [comment]
> Yes, that would be great, a pull request would be welcome. Just be sure that the range includes the endpoints, i.e. `0 <= p <= 1`.

Ah, of course. Looks like the text book I was referencing had that mistake as well. I'll work on a PR - if I'm modifying the string of multiple discrete distributions, should those be multiple PRs or just one since they'd be similar enough?

**Comment by WarrenWeckesser** [comment]
For several small and similar changes such as this, one pull request is fine.
