### ISSUE TITLE
Gain wrong when transforming Transfer Function to zeros, poles, gain 

### ISSUE THREAD

**Issue by magraeber** [scipy/scipy#12977]
I believe gain of a continuous transfer function is wrong, when it is transformed to zpk representation.

In the documentation it is stated several times that numerator and denominator polynomials are defined in descending order. That means gain is given by the last entries.

#### Reproducing code example:

```
from scipy.signal.filter_design import tf2zpk

# Simple First Oder model with gain 1 and time constant 10
zeros, poles, gain = tf2zpk([1], [10, 1])

# Should be 1, but is 0.1
print(gain)

```

#### Scipy/Numpy/Python version information:

```
1.5.2 1.16.5 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment]
`1/10s+1` becomes `0.1/s+0.1` if you make the denominator a monic polynomial. So that's why you 0.1 as gain.

**Comment by magraeber** [comment]
Here is an additional code block to see the issue visualized:
```
from scipy import signal
import matplotlib.pyplot as plt
lti = signal.lti([1.0], [10.0, 1.0])
t, y = signal.step(lti)
plt.plot(t, y)
plt.xlabel('Time [s]')
plt.ylabel('Amplitude')
plt.title('Step response for 1. Order Lowpass')
plt.grid()
```
The result clearly shows that gain is 1.0.

And transfer function 0.1/(s + 0.1) still has gain 1.0.

**Comment by ilayn** [comment]
If the gain is 1 and you only have a single pole then you would get `1/s+0.1`. K is the model gain not the DC gain.

**Comment by magraeber** [comment]
Ah, ok. That makes sense. I didn't know there are two different gains and always thought about DC gain.

Thanks, for the help.
