### ISSUE TITLE
Loading of scipy 1.5.3 fails after strip with ELF load command address/offset not properly aligned

### ISSUE THREAD

**Issue by holyketzer** [scipy/scipy#12975]
I'm not sure is it an issue in `scipy` or [strip](https://en.wikipedia.org/wiki/Strip_(Unix)) tool, but people should know, and there a workaround for it.

`scipy` is one of our dependancies, we build a docker image and after `pip install` strip the `*.so` files like

```
find /usr/local/lib/python3.7  -name '*.so*' | xargs strip
```

And it worked until this release https://pypi.org/project/scipy/1.5.3/

Now CI fails with:

```
Traceback:
    ...
    from sklearn.mixture import GaussianMixture
/usr/local/lib/python3.7/site-packages/sklearn/__init__.py:82: in <module>
    from .base import clone
/usr/local/lib/python3.7/site-packages/sklearn/base.py:20: in <module>
    from .utils import _IS_32BIT
/usr/local/lib/python3.7/site-packages/sklearn/utils/__init__.py:27: in <module>
    from .fixes import np_version
/usr/local/lib/python3.7/site-packages/sklearn/utils/fixes.py:18: in <module>
    import scipy.stats
/usr/local/lib/python3.7/site-packages/scipy/stats/__init__.py:388: in <module>
    from .stats import *
/usr/local/lib/python3.7/site-packages/scipy/stats/stats.py:174: in <module>
    from scipy.spatial.distance import cdist
/usr/local/lib/python3.7/site-packages/scipy/spatial/__init__.py:101: in <module>
    from ._procrustes import procrustes
/usr/local/lib/python3.7/site-packages/scipy/spatial/_procrustes.py:9: in <module>
    from scipy.linalg import orthogonal_procrustes
/usr/local/lib/python3.7/site-packages/scipy/linalg/__init__.py:194: in <module>
    from .misc import *
/usr/local/lib/python3.7/site-packages/scipy/linalg/misc.py:3: in <module>
    from .blas import get_blas_funcs
/usr/local/lib/python3.7/site-packages/scipy/linalg/blas.py:213: in <module>
    from scipy.linalg import _fblas
E   ImportError: /usr/local/lib/python3.7/site-packages/scipy/linalg/_fblas.cpython-37m-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
```

Workaround:
Pinning `scipy` to `1.5.2` helps.

```
scipy==1.5.2
```

**Comment by pv** [comment]
Reoccurrence of this: https://github.com/pypa/manylinux/issues/119

**Comment by pv** [comment]
Note however that the wheel binaries are at least supposed to be already stripped, and e.g. for 1.5.2 stripping does not reduce size.

**Comment by tylerjereddy** [comment]
I suppose the wheels repo could have a test of some sort for this, but I also do not know the cause offhand.

**Comment by mdavis-xyz** [comment]
Did we find out what the cause of this issue is?
`strip` is supposed to just remove debugging symbols. Did `strip` do more than that? Or do other binaries expect the debugging symbols to be there?

**Comment by rgommers** [comment]
> Reoccurrence of this: [pypa/manylinux#119](https://github.com/pypa/manylinux/issues/119)

This was fixed, `auditwheel` gained an option `--strip`. 

Also note that with Meson we now have a proper command-line interface to produce various flavors of debug or release binaries (https://mesonbuild.com/Builtin-options.html#core-options) - configuring with `-Dbuildtype=release` should avoid the need to strip binaries after building them.

**Comment by jtlz2** [comment]
I'm now stuck because I require > 1.5.2 to use scipy on macOS Monterey / M1 / ARM chips. Is the only solution to build 1.5.2 from scratch under ARM? :/

**Comment by rgommers** [comment]
@jtlz2 not sure what you are commenting on, but it's very likely not this issue. There are M1 binaries for recent releases on both PyPI and conda-forge. If you have a problem with those or with building from source, please open a new issue (feel free to Cc me).

**Comment by jtlz2** [comment]
@rgommers Done - thank you in advance for any and all assistance!

**Comment by dimidloc** [comment]
I have the same issue even with scipy 1.8.1 and 1.9.3. To reproduce:
```
mkvirtualenv -p python3.8 rasa
workon rasa
pip install rasa
python -c 'from rasa.core.agent import Agent, load_agent' # works
find /home/ubuntu/.virtualenvs/rasa/ -name '*.so' | xargs strip -s
python -c 'from rasa.core.agent import Agent, load_agent' 

ImportError: /home/ubuntu/.virtualenvs/rasa/lib/python3.8/site-packages/scipy/linalg/_fblas.cpython-38-x86_64-linux-gnu.so: ELF load command address/offset not properly aligned
```

**Comment by rgommers** [comment]
@dimidloc same comment as above: please open a new issue, with all required details, like how you installed Python and SciPy, what OS, etc.
