### ISSUE TITLE
Documentation presents second order sections as the correct choice where there is an engineering decision to be made

### ISSUE THREAD

**Issue by RonaldAJ** [scipy/scipy#12970]
With commit aef60c7591f4c3feb2f2dc8db11fa3f1f0a909e1 the documentation takes a stance on the use of 'sos' over the 'ba' form of the IIR-filter without providing motivation. In the issue itself the stance is motivated as providing 'less numerical error'. However, in my use case the 'sos'-form takes twice the computation time of the 'ba'-filter. Developing for an IoT application this is a major concern, so it would be fair if the documentation states the reason for the recommendation and the potential costs involved.

**Comment by ilayn** [comment]
From roots to polynomial coefficients mapping and vice-versa is quite well-known to be ill-conditioned (the poster child example is the Wilkinson polynomial). There are many examples for this and actually you can try it yourself. Especially when implementing digital filters transfer functions are broken down to their biquads etc. for this reason if for some reason cannot be avoided. This is not only relevant for this particular issue but also elsewhere see working with different representations section of https://nl.mathworks.com/help/control/ug/conversion-between-model-types.html 

If you have a particular example to improve you can ask in StackExchange networks both in EE and SO. But without seeing any particular example, my gut feeling says that in context of evaluating the response this difference can't be significant.

**Comment by RonaldAJ** [comment]
The issue is about computation time at deployment, not the calculation of the filter coefficients.

Passing 100 seconds of 44.1 kHz data these are the differences in processing time (repeated 20 times see code):
time elapsed  for ba-filter: 0.05151940584182739 s
time elapsed for sos-filter: 0.11865202188491822 s

I see no qualitative differences between the outputs.

`import numpy as np
import scipy.signal
from matplotlib import pyplot as plt

import time
fs= 44100
dt=100

# Generate some random data
timeseries = np.random.randn(dt*fs)

lp_numerator, lp_denominator = scipy.signal.iirdesign(0.2,0.3,2,80)

lp_sos  = scipy.signal.iirdesign(0.2,0.3,2,80, output='sos')

# Apply BA filter
t = time.time()
for N in np.arange(0,20):
    timeseries_lp = scipy.signal.lfilter(lp_numerator, lp_denominator, timeseries)
elapsed = time.time() - t
print(f'time elapsed  for ba-filter: {elapsed/20}')

# Apply SOS filter
t = time.time()
for N in np.arange(0,20):
    timeseries_lp_sos = scipy.signal.sosfilt(lp_sos, timeseries)
elapsed = time.time() - t
print(f'time elapsed for sos-filter: {elapsed/20}')

plt.figure(figsize=(30,20))

plt.plot(timeseries[int(4.95*fs):5*fs],'+')
plt.plot(timeseries_lp[int(4.95*fs):5*fs],'^-')
plt.plot(timeseries_lp_sos[int(4.95*fs):5*fs],'.-')



plt.show()

`

**Comment by ewmoore** [comment]
What version of scipy do you have?

**Comment by RonaldAJ** [comment]
Originally it ran under:
scipy.__version__: 1.3.2,   Ubuntu 16.04 on VM

time elapsed  for ba-filter: 0.05, filtertype = ellip, len_num: 8, len_denom: 8
time elapsed for sos-filter: 0.12, filtertype = ellip

time elapsed  for ba-filter: 0.056, filtertype = cheby2, len_num: 14, len_denom: 14
time elapsed for sos-filter: 0.2, filtertype = cheby2

time elapsed  for ba-filter: 0.055, filtertype = cheby1, len_num: 14, len_denom: 14
time elapsed for sos-filter: 0.2, filtertype = cheby1

I tested with a more recent version:
scipy.__version__: 1.5.0,   Ubuntu 18.04  on VM
scipy.__version__: 1.5.0
time elapsed  for ba-filter: 0.053, filtertype = ellip, len_num: 8, len_denom: 8
time elapsed for sos-filter: 0.056, filtertype = ellip

time elapsed  for ba-filter: 0.058, filtertype = cheby2, len_num: 14, len_denom: 14
time elapsed for sos-filter: 0.099, filtertype = cheby2

time elapsed  for ba-filter: 0.066, filtertype = cheby1, len_num: 14, len_denom: 14
time elapsed for sos-filter: 0.096, filtertype = cheby1

So it seems with the more recent version the differences in computational load are reduced. For elliptic filters they have become neglible in this case. So the point remains there is a trade-off to be made which requires the user to do some research, and this also implies there is a reason to keep 'ba'-filters around in the mind of the person reading the documentation. 

Reproduction notes:
In all cases 100 s of 44.1kHz whitenoise (np.random.randn) was passed through the filters, repeated 100 times to compensate for fluctuations due to background processes. Times stated are averages.

Butterworth is not included because it is not numerically stable at the given settings. I guess that proves the point of @ilayn . But I think I am happy with cheby2, which doesn't suffer from this problem. 

I can try to propose a text change:

- Current: Default is 'ba' for backwards compatibility, but 'sos' should be used for general-purpose filtering.
- Proposed: Default is 'ba' for backwards compatibility. In general 'sos' is recommended because inferring the 'ba' coëfficients suffers from numerical instabilities. Using the 'sos' filter  is sometimes associated with additional computational costs, for data-intense use cases it is therefore recommended to also investigate the 'ba'-filter format.

r = 5
ripple = 0.05
suppression = 50
lp_numerator, lp_denominator = scipy.signal.iirdesign(0.8/r,1.0/r, ripple, suppression, ftype=filtertype)
lp_sos  = scipy.signal.iirdesign(0.8/r,1./r,ripple, suppression, output='sos', ftype=filtertype)

**Comment by ilayn** [comment]
Ah sorry for misunderstanding earlier. Yes this looks a bit strange that SOS evaluation takes x2 longer. Documentation fix is fine but I'm curious why it is costing that much. I'll try to have a look

**Comment by RonaldAJ** [comment]
The first build had problems due to an offending character. But the current problems seem to go beyond my span of control. 

Something to do with build environment it seems to my untrained eye.

**Comment by RonaldAJ** [comment]
@ilayn Can you advise on how to get this passing the build tests?
