### ISSUE TITLE
Calculate standard error of the intercept in linregress

### ISSUE THREAD

**Issue by MarcinKonowalczyk** [scipy/scipy#12982]
Currently `linregress` from `scipy.stats` calculates standard error of the gradient, but not the intercept. The two are related, but would require re-calculating sum of x^2 outside of the `linregress` function. I propose this gets added to the body of `linregress` (where sum of x^2 is already known) and put into `LinregressResult` namedtuple.

I will submit a PR with my proposed solution just after I post this.

**Comment by rlucas7** [comment]
Looks like this was merged in #12983 so closing
