### ISSUE TITLE
Possible wrong link in scipy.stats.wilcoxon doc

### ISSUE THREAD

**Issue by lionettis** [scipy/scipy#12985]
The documentation of return values from `scipy.stats.wilcoxon` at
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wilcoxon.html
specifies
```
pvalue : float
The p-value for the test depending on alternative and mode.
```
with `mode` linking to `scipy.stats.mode`, while it seems to refer to the `mode` named parameter of the function call.

**Comment by ilayn** [comment]
Ah nice catch @lionettis . That's because we need double backticks around code marks and single backticks autolinks to functions and modules. Care to send a PR if you want to ? 

It's here 

https://github.com/scipy/scipy/blob/master/scipy/stats/morestats.py#L2855
