### ISSUE TITLE
x0 should be an optional parameter for Nelder-Mead minimisation

### ISSUE THREAD

**Issue by oulenz** [scipy/scipy#13000]
There seem to be two public functions that can be used to perform Nelder-Mead minimisation, the general `optimize._minimize.minimize` and the specific `optimize.optimize.fmin`, both of which internally call `optimize.optimize._minimize_neldermead`. There are two ways to initiate the Nelder Mead algorithm, with an initial simplex and with an initial guess. From what I understand, specifying an initial simplex is 'better', because:

a) The initial simplex determines the scale of the initial search. If you specify an initial guess, an initial simplex is chosen for you and if it is too small, Nelder-Mead can get stuck in a local optimum.
b) It requires less information about where the minimum might be located. If your domain is essentially bounded, you can start with a simplex that more or less covers the whole domain and let Nelder-Mead figure out where it needs to go.

Nonetheless, the api of `minimize` and `fmin` strongly pushes users towards providing an initial guess:

* In both functions, `x0` is an obligatory argument. `initial_simplex` is an optional argument for `fmin`, while it can be passed as part of an `options` dict to `minimize`, but is not explicitly mentioned there.
* If an initial simplex is provided, this overrides the initial guess. But the initial guess still can't be `None`, because a `ValueError` [is raised](https://github.com/scipy/scipy/blob/d4789babc26abcf09130b411df10eb72f8401d54/scipy/optimize/optimize.py#L661) if its dimension is not right (even though nothing is subsequently done with the initial guess).

I'd like to propose making `x0` optional and adding a check that either it or `initial_simplex` should be present. If this is not desirable for `minimize` because the other methods need it, then at least for `fmin`. In any case, the dimensionality check should be removed.

**Comment by MarcinKonowalczyk** [comment]
I agree with this suggestion from a scientific point of view. Moreover, it wouldn't even change the function interface, just the way the function could be called, and hence should be easy to merge.

@oulenz Is this just a suggestion (for someone else to implement), or would you like to fork scipy and contribute it yourself?

**Comment by oulenz** [comment]
I'd be happy to contribute a PR.

I just realised that it would also be possible to rig these functions to have them accept initial simplices through `x0`, which could be detected by looking at the number of dimensions of the passed array. If done properly, that would involve deprecating the dedicated `initial_simplex` parameter. Would that be desirable?

**Comment by oulenz** [comment]
Frankly, I don't understand why both `minimize` and the specific functions like `fmin` exist. Especially because they are slightly different, with `minimize` returning a `dict` and `fmin` a list. (Which can be made to include various parts of the `dict` by setting different parameters, but not all. I'm guessing both the parameters and the incompleteness are due to the fact that just expanding the list would break backwards compatibility.)

**Comment by andyfaff** [comment]
The `minimize` function was created to provide a uniform interface to a variety of optimize methods, and is recommended for new code. `fmin` is an older way of calling Nelder Mead. `minimize` returns an `OptimizeResult` object, which is uniform across the solver methods.
The desire for uniformity means that a really solver specific change to `minimize` (such as changing the docstring for `x0`) isn't a good idea.

I suggest that `fmin` could be changed to accomplish what you desire, as indicated in my reply to your PR.

**Comment by mdhaber** [comment]
Closing based on @andyfaff's feedback, the fact that the `fmin_` functions are considered legacy, and there was no response in the PR.
