### ISSUE TITLE
не устанавливается ./build_openblas.sh

### ISSUE THREAD

**Issue by guardian20** [scipy/scipy#13010]
$ ./build_openblas.sh
which: no gcc in (/usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
./build_openblas.sh: строка 9: gcc: команда не найдена
HEAD сейчас на 5f36f181 Update with 0.3.7 changes
./build_openblas.sh: строка 28: gcc: команда не найдена
make: gcc: No such file or directory
make: *** [Makefile.prebuild:62: getarch] Ошибка 127
Makefile.system:216: Makefile.conf: No such file or directory
make: *** Нет правила для сборки цели «Makefile.conf».  Останов.
make: gcc: No such file or directory
make: *** [Makefile.prebuild:62: getarch] Ошибка 127
Makefile.system:216: Makefile.conf: No such file or directory
make: *** Нет правила для сборки цели «Makefile.conf».  Останов.

**Comment by ilayn** [comment]
Hello @guardian20 , as you can read from the error you have no `gcc` installed. You can start from the top of this tutorial and follow it step by step http://scipy.github.io/devdocs/building/windows.html#build-windows otherwise you will not succeed building it on your machine.
