### ISSUE TITLE
scipy.integrate.solve_ivp raises error for a vector of events

### ISSUE THREAD

**Issue by hamidosooli** [scipy/scipy#13018]
using scipy.integrate.solve_ivp for a vector of events results in the following error. However, by adding the following line in ```ivp.py``` before mask initialization in line 142 
```global mask```
and changing line 74 
from ```return brentq(lambda t: event(t, sol(t)), t_old, t, xtol=4 * EPS, rtol=4 * EPS)``` 
to ```return brentq(lambda t: event(t, sol(t))[np.nonzero(mask)[1][0]], t_old, t,
                  xtol=4 * EPS, rtol=4 * EPS)``` the code uses the first event among simultaneous events occurred in each time to interpolate events time. This change will solve the problem

#### Reproducing code example:

```
import numpy as np
from scipy.integrate import solve_ivp

k = np.random.rand(2, 2)
A_st = np.random.rand(3, 3)
Bu = np.random.rand(3, 1)

Cy = np.random.rand(3, 3)
Dy = np.random.rand(3, 1)

time_interval = [0, 200]
init_cond = -np.random.rand(3, 1)


def k_dyn(t, k):
    return t * k


def A_dyn_mat(A_st, fun_k_dyn):
    A = A_st.copy()
    A[1:3,
    1:3] -= fun_k_dyn
    return A


def SttSpcEq(A_dyn_mat, fun_k_dyn, k, A_st, Bu):
    return lambda t, x: (np.matmul(A_dyn_mat(A_st, fun_k_dyn(t, k)), x).reshape(3, 1)  + Bu)


def test_event(t, x):
    return np.matmul(Cy, x).reshape(3, 1) + Dy


test_event.terminal = True
test_event.direction = 0

ssEq = SttSpcEq(A_dyn_mat, k_dyn, k, A_st, Bu)

sol = solve_ivp(ssEq,
                time_interval,
                init_cond.reshape(len(init_cond),),
                method='DOP853', vectorized=True,
                events=test_event)

print(sol.y, '@', sol.t)
```

#### Error message:
```Traceback (most recent call last):
  File "C:/Users/Hamid Osooli/PycharmProjects/Pantohealth/exp.py", line 39, in <module>
    sol = solve_ivp(ssEq,
  File "C:\Users\Hamid Osooli\AppData\Local\Programs\Python\Python38\lib\site-packages\scipy\integrate\_ivp\ivp.py", line 578, in solve_ivp
    root_indices, roots, terminate = handle_events(
  File "C:\Users\Hamid Osooli\AppData\Local\Programs\Python\Python38\lib\site-packages\scipy\integrate\_ivp\ivp.py", line 109, in handle_events
    roots = [solve_event_equation(events[event_index], sol, t_old, t)
  File "C:\Users\Hamid Osooli\AppData\Local\Programs\Python\Python38\lib\site-packages\scipy\integrate\_ivp\ivp.py", line 109, in <listcomp>
    roots = [solve_event_equation(events[event_index], sol, t_old, t)
  File "C:\Users\Hamid Osooli\AppData\Local\Programs\Python\Python38\lib\site-packages\scipy\integrate\_ivp\ivp.py", line 72, in solve_event_equation
    return brentq(lambda t: event(t, sol(t)), t_old, t,
  File "C:\Users\Hamid Osooli\AppData\Local\Programs\Python\Python38\lib\site-packages\scipy\optimize\zeros.py", line 776, in brentq
    r = _zeros._brentq(f, a, b, xtol, rtol, maxiter, args, full_output, disp)
  File "C:\Users\Hamid Osooli\AppData\Local\Programs\Python\Python38\lib\site-packages\scipy\integrate\_ivp\ivp.py", line 72, in <lambda>
    return brentq(lambda t: event(t, sol(t)), t_old, t,
  File "C:\Users\Hamid Osooli\AppData\Local\Programs\Python\Python38\lib\site-packages\scipy\integrate\_ivp\base.py", line 249, in __call__
    t = np.asarray(t)
  File "C:\Users\Hamid Osooli\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: only size-1 arrays can be converted to Python scalars

Process finished with exit code 1```
-->

#### Scipy/Numpy/Python version information:
<!--
1.5.2 1.19.2 sys.version_info(major=3, minor=8, micro=6, releaselevel='candidate', serial=1)
-->

**Comment by laurent90git** [comment]
As I understand it, you are giving an event function which returns a vector of size (3,1).
Scipy's solve_ivp looks out for a sign change in any of the event function return values at the end of the current time step.
However, each event must return a scalar value, not a vector !

If an event has been triggered during a time step. The exact moment of the sign change is determined by finding where the interpolated solution changes sign during this step (using dense output as interpolant). This is done with the brentq routine, which is a "fast" dichotomy let's say. THis brentq routine can only work with on a scalar function, which is not the case here.
What you need to do is to transform your vector-event into separate events. In your case, you can simply write something like:
```python
myevents = [lambda t,x,i=i: np.matmul(Cy, x).reshape(3, 1)[i] + Dy[i] for i in range(3)]
```
and give that to the "events" field in solve_ivp.

**Comment by hamidosooli** [comment]
The code is already able to handle vectors of events. It finds the indices of sign change in the vector ('''mask variable'''). Since "brentq routine can only work with on a scalar function" and the events are occurring simultaneously. brentq can use the first indice of the sign changing events to interpolate the exact moment of the sign change.
In the current case it seems feasible to separate events (there is only 3 of them in each time step). However, in my original project I have to handle vectors of events that are a vector of size 170 or more. Thus, separate events just slow downs the run-time.

**Comment by laurent90git** [comment]
Ok, I see.
But then your modificaiton of the brentq call does not appear in the stacktrace of the error:
`
  File "C:\Users\Hamid Osooli\AppData\Local\Programs\Python\Python38\lib\site-packages\scipy\integrate\_ivp\ivp.py", line 72, in solve_event_equation
    return brentq(lambda t: event(t, sol(t)), t_old, t,
`
Instead, should it not read as follows ?
`
 return brentq(lambda t: event(t, sol(t))[np.nonzero(mask)[1][0]],  t_old, t,
`

Anyway, to achieve what you want, you might need to adapt the way the function " handle_events" is called in "ivp.py", so that it correctly handles vector events.

**Comment by hamidosooli** [comment]
The above error is before using [np.nonzero(mask)[1][0]] in the code. After the suggested modification there will be no Error.
