### ISSUE TITLE
2D Interpolation Scaling Issues

### ISSUE THREAD

**Issue by d-v-t** [scipy/scipy#13021]
I've been trying to build a thermodynamic property calculator within python. The basic operation is that there are several thermodynamic properties of a state (p, T, v, u, s), but only two need to be defined to get all the properties of a state. These tables are tabulated and need to be interpolated (download below). Unless p and T are the independent variables, the grid is irregular. So for example, if provided with T and s, I would make interpolations of p=p(T, s), v=v(T, s), and u=u(T, s). Using some other simple formulae, I can calculate other values.

I've been using griddata to do this, but have experimented with interp2d as well. During some initial testing, I noticed some results that were totally incorrect when density (rho=1/v) and enthalpy (h=u+p*v) were the independent variables. I poked around and found that the interpolator had returned a function that was quite jittery on the enthalpy axis:

![noscale](https://user-images.githubusercontent.com/25378145/97786523-c2e56500-1b71-11eb-82dd-a09511cea783.png)

However, when the density was multiplied by a factor of 1000, things became much better:

![scaled](https://user-images.githubusercontent.com/25378145/97786547-edcfb900-1b71-11eb-8860-0f0752d9ddd1.png)

I suspect that interp2d was primarily developed for interpolating over an area, or at least two variables with the same dimensions and similar scales. I can understand how method='nearest' depends on scales, but I don't understand why method='linear' or method='cubic' would have to be so scale-dependent. Based on how I interpolated across two axes with different units, I can imagine other cases in which poorly-scaled irregular grid interpolation might be useful.

I provided the steam properties in .ods and .csv form in case you wish to reproduce these issues.

[h2o_gas.zip](https://github.com/scipy/scipy/files/5469544/h2o_gas.zip)

**Comment by ev-br** [comment]
Indeed, having vastly different scales in bad for numerical stability, so all sorts of issues are not entirely unexpected. If using `griddata` specifically, you can use the `rescale=True` parameter, or just manually rescale the data like you did in the issue. 
And indeed, checking the scales and rescaling if needed is a good idea regardless of an interpolator. I think the best a library can do is to urge the user to check the scales and act if needed, so gh-17313 attempts to add a note to this effect to all N>1 interpolators.

**Comment by adonath** [comment]
Just for reference: we implement a thin wrapper around the `RegularGridInterpolator` which supports exactly for the both scaling of the data as well as the coordinate axes. This allows e.g. linear interpolation in log-log space, see [code here](https://docs.gammapy.org/1.0/_modules/gammapy/utils/interpolation.html#ScaledRegularGridInterpolator). Maybe that is still helpful...
