### ISSUE TITLE
Error in demo code for Scipy.signal.convolve2d

### ISSUE THREAD

**Issue by MikeLampton** [scipy/scipy#13026]
My issue is about SciPy.signal.convolve2d()

#### Reproducing code example:

```
import numpy as np
from scipy import signal
from scipy import misc

ascent = misc.ascent()
scharr = np.array([[ -3-3j, 0-10j,  +3 -3j],
                   [-10+0j, 0+ 0j, +10 +0j],
                   [ -3+3j, 0+10j,  +3 +3j]]) # Gx + j*Gy
grad = signal.convolve2d(ascent, scharr, boundary='symm', mode='same')

import matplotlib.pyplot as plt
fig, (ax_orig, ax_mag, ax_ang) = plt.subplots(3, 1, figsize=(6, 15))
ax_orig.imshow(ascent, cmap='gray')
ax_orig.set_title('Original')
ax_orig.set_axis_off()
ax_mag.imshow(np.absolute(grad), cmap='gray')
ax_mag.set_title('Gradient magnitude')
ax_mag.set_axis_off()
ax_ang.imshow(np.angle(grad), cmap='hsv') # hsv is cyclic, like angles
ax_ang.set_title('Gradient orientation')
ax_ang.set_axis_off()
fig.show()

```

#### Output: none.

The final statement in the demo ought to be 

plt.show()

not what is posted:  fig.show()

**Comment by ilayn** [comment]
Hi @MikeLampton please also take a look at the explanation given here https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.show

As you can see from the docs, the figure is generated correctly.

**Comment by rajpratyush** [comment]
when i ran the following code in google colab it gave the output as given using numpy version 1.19.5
and scipy version 1.4.1 

here is the link to google colab 

https://colab.research.google.com/drive/1f7WR8EQ6NHJPfOGMLyTMCnYz7Xj_lsjo?usp=sharing

**Comment by rgommers** [comment]
This works fine in both the Colab notebook linked above, and from the docs: http://scipy.github.io/devdocs/reference/generated/scipy.signal.convolve2d.html?highlight=convolve2d#scipy.signal.convolve2d. So I'll close this.
