### ISSUE TITLE
Facing error while installing scipy

### ISSUE THREAD

**Issue by benjaminvarghese** [scipy/scipy#13020]
I'm unable to install scipy using pip3. I only have one version of python installed.
python3 version 3.9.0
pip3 version 20.2.4
I am able to install pandas and numpy but facing some error (link below) while trying to install scipy / seaborn.

https://www.codepile.net/pile/M1a0nVgD

**Comment by AtsushiSakai** [comment]
Hi. Maybe your reporting issue is duplicate to #12923 
I think you need to wait until scipy fully support python3.9.

**Comment by mckib2** [comment]
@benjaminvarghese Yep, the logs you uploaded indicate that pip was trying to install from source.  Are you still having issues installing via pip on Python 3.9?  The wheels should be available on PyPI

**Comment by benjaminvarghese** [comment]
> @benjaminvarghese Yep, the logs you uploaded indicate that pip was trying to install from source. Are you still having issues installing via pip on Python 3.9? The wheels should be available on PyPI

**Comment by benjaminvarghese** [comment]
@mckib2 Yes, it got resolved some weeks back. Thanks.
