### ISSUE TITLE
Generalized Hyperbolic Distribution

### ISSUE THREAD

**Issue by gbonomib** [scipy/scipy#13025]
Hello guys.

I could not find any Python implementation of the Generalized Hyperbolic distribution. This is a class of continuos distribution which unify other semi-fat-tailed distribution as t-student, laplace or inverse-gaussian. More reference can be found [at the wiki article](https://en.wikipedia.org/wiki/Generalised_hyperbolic_distribution)

I think it would make sense to add the `genhyp(*args, **kwds)` class to `scipy.stats` collection of continuos distribution

**Comment by mdhaber** [comment]
Thanks for the suggestion. Would you be interested in contributing it?

**Comment by gbonomib** [comment]
Hi! In principle that was the plan but I am experiencing some issue compiling scipy on a my windows machine. I've got some stub code which I'd like to test but I cannot unfortunately

**Comment by mdhaber** [comment]
Have you followed [these instructions](http://scipy.github.io/devdocs/building/windows.html#build-windows)? What are you running into?

**Comment by mdhaber** [comment]
@gbonomib I just built on a new Windows machine tonight so I might be able to help if I've run into a similar issue before!

**Comment by gbonomib** [comment]
Thank you. I will look into that in the next few weeks if I can make it work.

**Comment by gbonomib** [comment]
Hi @mdhaber. Running Ubuntu on WSL2 turned out for me a much more effective solution than installing BLAS on windows (as despite following the instructions i could still not compile scipy - clearly my bad - but had not the patience to troubleshoot).

**Comment by mdhaber** [comment]
Ok, sorry to hear that Windows didn't work out, but glad WSL is working.

**Comment by gbonomib** [comment]
> Ok, sorry to hear that Windows didn't work out, but glad WSL is working.

No worries, it is most likely my fault. I managed to compile and run  on WSL2 just fine. Just submitted PR https://github.com/scipy/scipy/pull/13298

**Comment by mdhaber** [comment]
Thanks @gbonomib. I edited the top message a tiny bit to close this issue when that one merged ("Closes gh-13025") and to remove the reference to mdhaber/scipy#28, as that is just a list of things I'm helping with. This is not actually tied to the CZI grant mentioned there in particular.

**Comment by gbonomib** [comment]
Thank you @mdhaber for the suggestions on the PR. I quickly went through them and will address them in the coming days.
