### ISSUE TITLE
2SLS formula API doesn't appear to be working

### ISSUE THREAD

**Issue by LoganBitszer** [scipy/scipy#13047]
Here's the code that will reproduce something similar to what I'm doing
```
import pandas as pd
import numpy as np
import scipy as sp
from statsmodels.sandbox.regression.gmm import IV2SLS
from numpy.linalg import LinAlgError
from sklearn.preprocessing import StandardScaler

def gen_data(Sigma, n=100):
    try:
        Chol = sp.linalg.cholesky(Sigma)
        X = np.random.randn(n,Sigma.shape[0])
        X = StandardScaler().fit_transform(X)
        D = X @ Chol
    except LinAlgError:
        print("Provide a valid covariance matrix")
        D = np.nan
    return D

Sigma = np.array(
    [[5,1,0],
     [1,4,2],
     [0,2,3]]
)
df = pd.DataFrame(gen_data(Sigma),columns=["z","x1","u"])
df['y'] = 2*df['x1'] + 2*(df['x1']+df['u']) + np.random.normal(0,1,size=len(df))
IV2SLS.from_formula('y ~ u + [x1 ~ z]', data=df)
```

As far as I can tell from some of the docs --[(1)](https://www.statsmodels.org/stable/generated/statsmodels.sandbox.regression.gmm.IV2SLS.from_formula.html#statsmodels.sandbox.regression.gmm.IV2SLS.from_formula), [(2)](https://bashtage.github.io/linearmodels/doc/iv/examples/using-formulas.html), [(3)](https://bashtage.github.io/linearmodels/devel/iv/examples/using-formulas.html)-- I should be able to run the regression from the code above... I'm not sure why it doesn't like the syntax for `[x1 ~ z]`.

**Comment by josef-pkt** [comment]
this is the scipy issue tracker

you use statsmodels in the example

but you look at the docs of the linearmodels package.

linearmodels supports these formulas, statsmodels does not
