### ISSUE TITLE
DOC: Math / LaTeX not rendered in online SciPy documentation

### ISSUE THREAD

**Issue by henrikh** [scipy/scipy#13055]
The online documentation for SciPy doesn't seem to render the mathematical notation. Aka. the LaTeX is transferred directly to the HTML raw, without rendering/conversion to something which will render nicely in the browser.

#### Reproducing code example:
Go to: https://docs.scipy.org/doc/scipy/reference/tutorial/signal.html (dated 2020 Nov. 9th)

#### Error message:
N/A

#### Scipy/Numpy/Python version information:
N/A

**Comment by ilayn** [comment]
Is it possible that your browser has disabled it? What are the specs of your system

On Firefox 82.0.2 (64bit), Win10, I see 
![image](https://user-images.githubusercontent.com/1303842/98552689-0bea9700-229f-11eb-8934-3ee39947b9a9.png)

it takes a few moments to render all though

**Comment by henrikh** [comment]
Firefox 82.0.2 (32-bit)

Looking through the dev console, I see that there are some errors:

![image](https://user-images.githubusercontent.com/87876/98557757-e3659b80-22a4-11eb-9360-fc6501445ce8.png)

**Comment by ilayn** [comment]
Somehow your browser falls back to NativeMML rendering which as far as I know not supported by the theme. In fact this is the output folder 

https://docs.scipy.org/doc/scipy/reference/_static/scipy-mathjax/jax/output/

So something else might be related but I'll leave it to someone who is more knowledgeable.

**Comment by henrikh** [comment]
I tracked the issue to my end. It was an extension which enabled the NativeMML rendering.
