### ISSUE TITLE
OverflowError when sampling from some handmade stats distributions

### ISSUE THREAD

**Issue by Maelstrom6** [scipy/scipy#13051]
Hi there, I'm coming from [SymPy](https://github.com/sympy/sympy) where we had [the original issue](https://github.com/sympy/sympy/issues/20376). SymPy uses SciPy's stats library in order to generate fast numerical samples of distributions. It does so by creating its own class that inherits from `rv_continuous`. However, some cases, this causes an overflow error (specifically when the support is the entire real line).

I believe this may be because the density is just so small at value that SciPy starts integrating, that Python gives up. SciPy does this integration in order to create the ppf from the pdf.

#### Reproducing code example:

```python
from scipy.stats import rv_continuous
import numpy as np

class scipy_pdf(rv_continuous):
    def _pdf(self, x):
        # pdf of N(0, 0.1)
        # autogenerated from user input
        return np.exp((x/.1)**2 / 2) / np.sqrt(2*np.pi*.1)

scipy_rv = scipy_pdf(a=-np.inf, b=np.inf, name='scipy_pdf')
print(scipy_rv.rvs(size=()))
```

#### Error message:

```
RuntimeWarning: overflow encountered in exp
  return np.exp((x/.1)**2 / 2) / np.sqrt(2*np.pi*.1)
RuntimeWarning: invalid value encountered in ? (vectorized)
  outputs = ufunc(*inputs)
Traceback (most recent call last):
line 11, in <module>
    print(scipy_rv.rvs(size=()))
...
line 8, in _pdf
    return np.exp((x/.1)**2 / 2) / np.sqrt(2*np.pi*.1)
OverflowError: (34, 'Result too large')
```

Everything works as intended for a Normal(0, 1) distribution. But things start to break down when we get to about Normal(0, 0.2).

#### Scipy/Numpy/Python version information:
```
1.5.3 1.17.4 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)
```

#### Possible solutions for SymPy

I'm not sure if this should be considered a SciPy problem or a SymPy problem. If it is a SciPy problem, then here I am letting you know. If it is not, then please could I receive some advice on how to fix this?

My current ideas are:
1. Create a dictionary that maps all of SymPy's distributions to all of SciPy's distributions so that we will not have to use `rv_continuous` most of the time. This seems like the most reliable option to me. SymPy already does this with the NumPy and pymc3 distributions.
2. Identify `a` and `b` to be some large finite value. This might be challenging to find these values though, especially in a symbolic library such as SymPy.
3. In addition the the `_pdf`, we can also specify `_cdf`. This should avoid numerical integration (I think).

Any advice is greatly appreciated.

**Comment by chrisb83** [comment]
Hi, 

if you implement a continuous distribution by just stating the pdf in SciPy, generating rvs relies on the following steps needs to first compute the cdf by integration, then invert it using `brentq`. The approach is VERY slow and unlikely to be accurate. 

As you describe in your last suggestion, you could skip the integration by specifying the cdf. The approach would still be very slow but it would be more robust. Directly using SciPy distributions such that you can use `rvs` (often relying on custom implementations, e.g. by implementing `_ppf`) sounds like the best approach.

There are also efficient methods to generate rvs from the pdf only (e.g. https://dl.acm.org/doi/abs/10.1145/945511.945517). Unfortunately, SciPy only has a basic implementation of the ratio-of-uniforms method but it requires the specification of further parameters, so I do not think it will be helpful in your case.

**Comment by chrisb83** [comment]
I forgot to add the link to RoU: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rvs_ratio_uniforms.html

**Comment by Maelstrom6** [comment]
Thank you for this. We've decided to go with using the distributions directly which should be the best, as you say. 

The ratio of uniforms is something new to me and it looks really impressive. Calculating the extra parameters adds little extra cost for SymPy since the suprema and infima can be done symbolically. We could also use SciPy's `maximize` to calculate those parameters as well I assume. Maybe a later version of SymPy will use SciPy's RoU for user-defined distributions.

**Comment by mdhaber** [comment]
@chrisb83 What do you think about adding the method from the paper you mentioned?

[Here](https://gist.github.com/mdhaber/4085e197bd65fe334740ee01070bd5e0)'s a gist. `_fni` (fast numerical inversion) returns a `scipy.interpolate.CubicHermiteSpline` approximation of the PPF (inverse CDF).  For distributions with slow sampling, like `genexpon`, it's faster to generate the approximate PPF and sample with it than to use the built in PPF/RVS, and the error is small:

```
from scipy.stats import genexpon
dist = genexpon(a=2, b=3, c=4)
np.random.seed(0)
N = 1000
x = np.random.rand(N)
%timeit dist.rvs(N)
%timeit p1 = dist.ppf(x)
%timeit  H, _, _ = _fni(dist); p2 = H(x) 
p1 = dist.ppf(x)
H, _, _ = _fni(dist); p2 = H(x)
print(np.abs(np.max(p1-p2)))
```
prints:
```
1.45 s ± 12.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.47 s ± 8.26 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
12.2 ms ± 108 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
1.5644618933663423e-10
```
