### ISSUE TITLE
Error while comparing a png image and a jpg image

### ISSUE THREAD

**Issue by LeclercTanguy** [scipy/scipy#13064]
My issue is about comparing a .jpg image and a .png image. But when I do I get and error. 

To reproduce it you just need a folder with 2 images 1 jpg and 1 png.

#### Reproducing code example:

```
DIR_TEST = "./DATASET/test/png/"
vector_images, labels = define_list_image_declinations(DIR_TEST)
# labels = ['original.jpg', 'test.png']
res = pdist(vector_images)
```

#### Error message:

```
Traceback (most recent call last)
<ipython-input-89-0494c34b96d3> in <module>
      2 vector_images, labels = define_list_image_declinations(DIR_TEST)
      3 # labels = ['original.jpg', 'test.png']
----> 4 res = pdist(vector_images)

~/.local/share/virtualenvs/similar_image_detection-s1dSs0Gr/lib/python3.9/site-packages/scipy/spatial/distance.py in pdist(X, metric, *args, **kwargs)
   1988     s = X.shape
   1989     if len(s) != 2:
-> 1990         raise ValueError('A 2-dimensional array must be passed.')
   1991 
   1992     m, n = s

ValueError: A 2-dimensional array must be passed.

```

#### Scipy/Numpy/Python version information:

```
1.5.4 1.19.4 sys.version_info(major=3, minor=9, micro=0, releaselevel='final', serial=0)


```

**Comment by andyfaff** [comment]
It's not clear that this is a scipy bug. From the error message it seems that `vector_images` has to be a 2D array, have you checked that it is?

**Comment by LeclercTanguy** [comment]
The bug only occurs when it's a png and jpg. When I use 2 png or 2 jpg with the same way of building my vector_images, it works fine

**Comment by andyfaff** [comment]
What is `vector_images.shape`?

**Comment by LeclercTanguy** [comment]
AttributeError: 'list' object has no attribute 'shape'

**Comment by andyfaff** [comment]
How about `print(np.asarray(vector_images, order='c').shape)`

**Comment by LeclercTanguy** [comment]
(2, 8716800)

**Comment by LeclercTanguy** [comment]
So it is not a pdist problem my bad, thank you for your time.
