### ISSUE TITLE
Weighted geometric mean

### ISSUE THREAD

**Issue by maxfrei750** [scipy/scipy#13065]
I propose the addition of a `weights` argument to `scipy.stats.gmean`, to support the calculation of the weighted geometric mean according to https://en.wikipedia.org/wiki/Weighted_geometric_mean. If there is interest, then I could create a PR.

**Comment by rgommers** [comment]
Thanks @maxfrei750. No need to have both an issue and a PR for a small feature like this. Let me close this, so the conversation stays in one place (on the PR).

**Comment by christabelle** [comment]
Hi, is there an update on this feature?

**Comment by ilayn** [comment]
Hi @christabelle This is already implemented in #13067 and will be available from v1.17.0 and further

**Comment by luckey01** [comment]
hey @ilayn ,

Is this live yet? I can see it in the docs, but when trying to use it I'm getting the following error:


```TypeError                                 Traceback (most recent call last)
<ipython-input-89-2eeeb5ba1f18> in <module>()
----> 1 gmean((100+df_flat["supply_ap_eCPX_diff_%"]), axis=1, weights=df_flat["revenue_euro_tot"])-100

TypeError: gmean() got an unexpected keyword argument 'weights'```

**Comment by mdhaber** [comment]
@luckey01 Please check your SciPy version:
```python3
import scipy
print(scipy.__version__)
```
The feature is only available in SciPy 1.7+.

**Comment by luckey01** [comment]
ah right, thanks. 
![image](https://user-images.githubusercontent.com/15872132/127012871-a77561c1-6780-45ee-89ba-46ba5a626d43.png)

**Comment by ap1690** [comment]
<img width="847" alt="image" src="https://user-images.githubusercontent.com/41077674/194759026-728ce19d-5228-4338-a33b-11fd6be7137f.png">

Facing the same issue for SciPy 1.7.3

**Comment by WarrenWeckesser** [comment]
@ap1690, the `weights` parameter was added to `hmean` in SciPy version 1.9.0.  You are using 1.7.3.

**Comment by ap1690** [comment]
Yes it worked

Thanks @WarrenWeckesser
