### ISSUE TITLE
i'm trying to work on the rf-filter optimization using scipy.optimize

### ISSUE THREAD

**Issue by aravindh29-prog** [scipy/scipy#13076]
```LB = [10.8,10.8];
UB = [10000,10000];
bnds = tuple([LB,UB])
N=30;
count = 0;
x0 =[10.8,100];
def objective(x,freq,gd1):
    Zo = 50;
    w = 2*pi*freq
    #w1 = w.tolist()
    d1 = (1j*w*(x0[0]*1e-11))
    d2 = (1j*w*(x0[1]*1e-12))
    d3 = np.power(d2,-1)
    Zin = 1/(d1+d3)
    S11 = (Zin-Zo)/(Zin+Zo)
    y = angle(S11);
    y  = np.unwrap(y, discont=3.141592653589793, axis=-1)
    y = np.ravel((y))
    y = y.reshape(1,301)
    g1 = w[0];
    g2 = w[1];
    dw = g2-g1;
    gd2o = -diff(y)/dw;
    gd2 = np.append(gd2o,gd2o[0][-1]);
    gd2 = abs(gd2)*1e2
    f = ((gd1-gd2))*1e9
    f = np.ravel((f))
    f = max(f)
    return f
for h in range(1,N):
    if(h<10):
        t = str(h).zfill(3)
        b = 'hairpin filter_param'+ t+'.s1p'
        S = Network(b);
        freq = S.f;
        gd1= S.group_delay
        gd1 = np.ravel((gd1))
        gd1 = abs(gd1)
        gd1 = gd1.reshape(301,1);
        #plt.plot(freq,gd1)
        warnings.filterwarnings("ignore")
        lcopt = optimize.minimize(objective,x,args = (freq,gd1))
        print(lcopt)```

output:
fun: 0.9986006787542225
 hess_inv: array([[1, 0],
       [0, 1]])
      jac: array([0., 0.])
  message: 'Optimization terminated successfully.'
     nfev: 3
      nit: 0
     njev: 1
   status: 0
  success: True
        x: array([ 10.8, 100. ])
my code Is just returning same input values. Can you please help me with this. Thanks in advance

**Comment by aravindh29-prog** [comment]
`fun: 0.9986006787542225
 hess_inv: array([[1, 0],
       [0, 1]])
      jac: array([0., 0.])
  message: 'Optimization terminated successfully.'
     nfev: 3
      nit: 0
     njev: 1
   status: 0
  success: True
        x: array([ 10.8, 100. ])`

**Comment by andyfaff** [comment]
Could you format your code in a Pythonic way (use ``` to include a code block). Without that it's very hard to read the source code.

**Comment by aravindh29-prog** [comment]
i have formatted the code. Thank you so much for your help

**Comment by andyfaff** [comment]
- Your code isn't replicable, what is the `Network` object? 
- Why is the warnings filter there?
- if you perturb `x0` by small amounts does the value returned by objective change at all? If it doesn't then that will be why the solver doesn't find a better solution.

**Comment by aravindh29-prog** [comment]
hello andyfaff 
sorry for the late reply
what do you mean by perturbing x0 by small amounts? and the network function is related to rf filters. I'm trying to convert the string into a network so that I can run the group delay and the working on some filter optimization problems on rf-hairpinfilter design.

**Comment by andyfaff** [comment]
It's not possible to help figure out what's wrong if we can't run the example ourselves.
I suggested that you change x0 by a small amount and see if the cost function changes value

**Comment by andyfaff** [comment]
Closing, no further reply from original poster. If they provide a minimal working example we can reopen.
