### ISSUE TITLE
The R2 value using linear regression model LinearRegression(fit_intercept=False)

### ISSUE THREAD

**Issue by gitanjalIthakur** [scipy/scipy#13080]
I have a question regarding the formulation use to estimate R2  in linear regression model with or  without intercept  as it was not clear in the documentation. I would like to know if the R2 estimation is different for LinearRegression(fit_intercept=False) and
LinearRegression(fit_intercept=True)

I am asking this because :
 In this paper about regression through origin  http://web.ist.utl.pt/~ist11038/compute/errtheory/,regression/regrthroughorigin.pdf
it clearly mentions for OLS with intercept we should use 
![image](https://user-images.githubusercontent.com/41470091/99087246-d6a9b600-25ca-11eb-9b06-488df560fe51.png)

And for OLS passing through origin we should use 
![image](https://user-images.githubusercontent.com/41470091/99087372-fa6cfc00-25ca-11eb-9909-c655c3c16404.png)

I checked the two formulation and yes in terms of R2 they make quite a difference in the magnitude.

Thanks a lot

**Comment by chrisb83** [comment]
Which function in SciPy do you mean? `linregress` does not have an otpion to exclude the intercept (https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.linregress.html)

**Comment by gitanjalIthakur** [comment]
Thanks actually it is a function from Sci-kit named  LinearRegression. My bad i thought it is from  scipy. sorry :)

**Comment by ev-br** [comment]
Ok, closing as not a scipy bug. Thanks for a report anyway!
