### ISSUE TITLE
chebwin window function has broken import

### ISSUE THREAD

**Issue by jgill018** [scipy/scipy#13092]
My issue is about the  Dolph-Chebyshev window function.  It currently crashes due to an invalid import statement.

the import statement below is the issue:
```
from scipy import fft as sp_fft
```

later this function is called:
```
w = np.real(sp_fft.fft(p))
```
fft is not a function in scipy.fft.  Instead it should just be:
```
w = np.real(sp_fft(p))
```

#### Reproducing code example:
```
# from the chebwin docstring
from scipy import signal
window = signal.chebwin(51, at=100)
```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\lib\site-packages\scipy\signal\windows\windows.py", line 1465, in chebwin
    w = np.real(sp_fft.fft(p))
AttributeError: 'function' object has no attribute 'fft'
```

#### Scipy/Numpy/Python version information:

```
1.0.0 1.14.2 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment]
I can't reproduce this on newer versions, From the release notes of v1.4.0 (we are now at 1.5.4) 

> `scipy.fft` is now meant to be used only as a module, so the ability to call `scipy.fft(...)` will be removed in SciPy 1.5.0.

hence this functionality has been removed. 

You mentioned that you are on v1.0.0 but then it should work but you are now using 1.5 syntax so I am a bit confused on what you have.

**Comment by peterbell10** [comment]
Yup, the blame confirms that `import fft as sp_fft` was added in v1.4.0 alongside the `scipy.fft` module. @jgill018 I think your python environment is messed up. You might have two versions of SciPy installed and they are somehow competing with each other. Repeatedly calling `pip uninstall scipy` sometimes works to remove multiple versions, not sure how that interacts with `conda` though.

**Comment by jgill018** [comment]
Thanks!  Yes, there was an issue with my environment.  uninstalling and reinstalling scipy fixed it.  Thank you!
