### ISSUE TITLE
Unexpected behaviour for saving and reading numpy arrays to mat file

### ISSUE THREAD

**Issue by marhofmann** [scipy/scipy#13093]
I noticed that the shape of an array is changed from (n,) to (1,n) by saving and reading it as a mat file! 
Is there a certain reason for that?

For reproduction:
```
import scipy.io as sio
import numpy as np

vec = np.random.rand(10)

dictionary = {'vec': vec}
sio.savemat('dictionary_to_mat.mat', dictionary)

mat_to_dictionary = sio.loadmat('dictionary_to_mat.mat')
print(f"Shape missmatch! dictionary['vec'].shape={dictionary['vec'].shape}  != mat_to_dictionary['vec'].shape={mat_to_dictionary['vec'].shape}\n")
print(dictionary['vec'])
print(mat_to_dictionary['vec'])
```

**Comment by ilayn** [comment]
Yes, matlab doesn't have 1D arrays and every array is at least 2D. So NumPy 1D array is converted to a 2D array such that matlab can read it. Then if you reload it you get the 2D array back.

**Comment by marhofmann** [comment]
Ok I understand. Thanks for your fast reply!
