### ISSUE TITLE
Broken link in doc for signal.max_len_seq

### ISSUE THREAD

**Issue by nbecker** [scipy/scipy#13090]
My issue is about ...
documentation for scipy.signal.max_len_seq()

In this document: https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.max_len_seq.html?highlight=correlation
This link is broken:
http://www.newwaveinstruments.com/resources/articles/m_sequence_linear_feedback_shift_register_lfsr.htm

#### Reproducing code example:

```
Sample code to reproduce the problem
```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

**Comment by larsoner** [comment]
I guess http://in.ncu.edu.tw/ncume_ee/digilogi/prbs.htm#Table%20of%20M-Sequence%20Feedback%20Taps would be a suitable replacement, but it doesn't look particularly permanent. Maybe we should copy the values into the code somewhere...

**Comment by roryyorke** [comment]
How about a Wayback machine link, https://web.archive.org/web/20181001062252/http://www.newwaveinstruments.com/resources/articles/m_sequence_linear_feedback_shift_register_lfsr.htm ?  It looks like they've also archived the data files.

**Comment by rgommers** [comment]
> How about a Wayback machine link,

This looks like a good solution to me. gh-13293 was just opened to do that.
