### ISSUE TITLE
Wrong output format for empty sparse results of kron

### ISSUE THREAD

**Issue by MarkusKoebis** [scipy/scipy#13099]
My issue is about the default behaviour of the Kronecker product: If the input matrices have nnz == 0, the output defaults to the output format "coo" even if I explicitly ask for a format like 'csr'. I would add a ".asformat(format)" in line 333 of construct.py (and potentially also in lines 319/ 325) or add additional documentation if that behaviour is intended.

#### Reproducing code example:

```
# Sample code to reproduce the problem
import scipy.sparse as sp
type(sp.kron(sp.csr_matrix((3,4)), sp.csr_matrix((2,1)), format='csr')) # -> should be csr but is coo
```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

#### Scipy/Numpy/Python version information:
 1.5.0/1.18.5/3.8.3 # but I don't think that matters

**Comment by perimosocordiae** [comment]
Thanks for the report. I can confirm that we're not respecting the given format here: 
https://github.com/scipy/scipy/blob/2a1dc2ae8d2c944209f3053d1285dbe5edaff6cc/scipy/sparse/construct.py#L333

Would you like to open a Pull Request with the changes? In addition to the small code change, it would be nice to have a test case that checks if we respect the format argument.
