### ISSUE TITLE
TST, CI: GitHub Actions MacOS Failures

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#13108]
GitHub Actions MacOS CI jobs have been failing consistently. A sample log is available here: https://github.com/scipy/scipy/pull/13094/checks?check_run_id=1436142836

SciPy itself is built successfully, but runtime access to gfortran dynamic libraries (via openblas lib) is compromised, causing a cascade of failures during the testsuite that look like this:

```
E   ImportError: dlopen(/Users/runner/work/scipy/scipy/build/testenv/lib/python3.8/site-packages/scipy/spatial/qhull.cpython-38-darwin.so, 2): Library not loaded: /libgfortran.3.dylib
E     Referenced from: /Users/runner/work/scipy/scipy/openblas/lib/libopenblasp-r0.3.9.dylib
E     Reason: image not found
_ ERROR collecting build/testenv/lib/python3.8/site-packages/scipy/cluster/tests/test_hierarchy.py _
ImportError while importing test module '/Users/runner/work/scipy/scipy/build/testenv/lib/python3.8/site-packages/scipy/cluster/tests/test_hierarchy.py'.
```

There are quite a few shims in that CI code that deal with dynamic library behavior--I'll try to check this today as it will be important for CI to be consistently green with 1.6.0 branching imminent. If someone else is already close to a solution please chime in to avoid duplicated effort.

**Comment by andyfaff** [comment]
It looks like the major culprit is qhull not being able to load/find the correct libgfortran library.
