### ISSUE TITLE
inquiry of lfilter implementation: the result of scipy.signal.lfilter is different from that of @NAME@_filt in lfilter.c.src

### ISSUE THREAD

**Issue by WeifengY** [scipy/scipy#13105]
Hi,
I wrote a "filter" function in C to filter some ECG signals, which I believed to be correct. However after using it for some time, I found its output was different from what I got in python with ```scipy.signal.lfilter()```, but I couldn't figure out the reason after reviewing my implementation several times. So finally I dug out the C implementation of  ```scipy.signal.lfilter()``` in lfilter.c.src in this repository and extracted the ```@NAME@_filt()``` as below ```filt()```. Also my test code is posted along, where coefficients a and b are from the 6-order butterworth band-pass filter of ```signal.butter()```.
```
#include "stdio.h"
#include "stdlib.h"
#include "string.h"
#include "malloc.h"

typedef double FLOAT_TYPE;

static void filt(FLOAT_TYPE *b, FLOAT_TYPE *a, unsigned int len_b,
        FLOAT_TYPE *x, FLOAT_TYPE *y, FLOAT_TYPE *Z, unsigned int len_x)                                        
{                                                                                
    FLOAT_TYPE *ptr_x = x, *ptr_y = y;                                                 
    FLOAT_TYPE *ptr_Z;                                                               
    FLOAT_TYPE *ptr_b = b;                                                  
    FLOAT_TYPE *ptr_a = a;                                                  
    FLOAT_TYPE *xn, *yn;                                                             
    const FLOAT_TYPE a0 = *a;                                           
    int n;                                                                  
    int k;                                                                 
                                                                                 
    /* normalize the filter coefs only once. */                                  
    for (n = 0; n < len_b; ++n) {                                                
        ptr_b[n] /= a0;                                                          
        ptr_a[n] /= a0;                                                          
    }                                                                            
                                                                                 
    for (k = 0; k < len_x; k++) {                                                
        ptr_b = b;   /* Reset a and b pointers */                     
        ptr_a = a;                                                    
        xn = ptr_x;                                                   
        yn = ptr_y;                                                   
        if (len_b > 1) {                                                         
            ptr_Z = Z;                                              
            *yn = *ptr_Z + *ptr_b  * *xn;   /* Calculate first delay (output) */ 
            ptr_b++;                                                             
            ptr_a++;                                                             
            /* Fill in middle delays */                                          
            for (n = 0; n < len_b - 2; n++) {                                    
                *ptr_Z =                                                         
                    ptr_Z[1] + *xn * (*ptr_b) - *yn * (*ptr_a);                  
                ptr_b++;                                                         
                ptr_a++;                                                         
                ptr_Z++;                                                         
            }                                                                    
            /* Calculate last delay */                                           
            *ptr_Z = *xn * (*ptr_b) - *yn * (*ptr_a);                            
        } else {                                                                 
            *yn = *xn * (*ptr_b);                                                
        }                                                                        
                                                                                 
        ptr_y += 1;      /* Move to next input/output point */            
        ptr_x += 1;                                                       
    }                                                                            
}

static void print_array(FLOAT_TYPE *arr, int len, char *aname)
{
    int i;

    printf("%s = [\n", aname);
    for (i = 0; i < len; i++) {
        printf("%10.6f", arr[i]);
        if (len - 1 == i)
            printf(" ]\n");
        else 
            printf(", ");
        if ((i + 1) % 5 == 0 && i != len - 1) {
            printf("\n");
        }
    }
}

int main()
{
    int i, test_len, alen;
    FLOAT_TYPE *y, *z;

    FLOAT_TYPE x[] = {
   68.87028238,    9.06055931,  -41.16551312,  -75.53115689,   -88.7747965,
  -73.87090749,  -26.39622799,   48.01838001,  131.38053294,  198.27740257,
  226.79709025,  211.17187394,  165.43631153,  112.15345665,   67.54833255,
   38.69929447,   31.28704854,   52.43560211,  100.62093416,  152.53339287,
  164.81341145,   98.36306694,  -48.54038007, -226.67159829, -360.65824424,
 -399.72576079, -354.28539641, -283.84847963, -244.78577714, -247.29127498,
 -260.76479773, -254.4006073 , -227.14190637, -201.55207529, -196.36439469,
 -207.10002523, -209.42274696, -179.70432872, -116.21479302,  -44.35662568,
   -0.97548238,   -9.37563212,  -63.25003692, -129.58773535, -167.82353864,
 -153.42736289,  -91.81108937,  -14.55135531,   40.09553498,   52.11201893,
   33.22991684,   15.00767104,   19.09203366,   38.72268733,   49.88753405,
   36.85924704,    4.0338805 ,  -32.38773479,  -56.82932645,  -58.62446164,
  -32.73909629,   15.16823135,   64.23111848,   86.70908437,   68.85441629,
   25.73248151,   -6.91759408,    1.49647513,   54.92058392,  128.99912854,
  186.22291326,  195.82179748,  150.64098016,   75.83108595,   19.36078116,
   20.29252799,   76.14933758,  143.56169284,  176.64427756,  165.50839739,
  137.65512827,  126.68539317,  143.90193452,  176.96729221,  206.31321335,
  216.51733394,  197.4130138 ,  146.61245783,   76.79954183,   15.67850213,
   -9.18327099,    9.70188755,   52.13032831,   81.14456203,   64.75225195,
   -4.98006001, -106.45504892, -200.45635588, -253.26512586, -256.24090435,
    };

    FLOAT_TYPE a[] = {
  1.00000000e+00, -4.70443125e+00,  8.83544806e+00, -9.03599445e+00,
  7.04786361e+00, -5.75239346e+00,  3.59589860e+00, -1.13432636e+00,
  3.27378726e-01, -2.27401968e-01,  2.72288852e-02,  1.65333132e-02,
  4.19630342e-03,
    };
    FLOAT_TYPE b[] = {
  0.06368296,  0.  ,       -0.38209776,  0.   ,       0.95524441,  0.,
 -1.27365921,  0.  ,        0.95524441,  0.   ,      -0.38209776,  0.,
  0.06368296,
    };

    test_len = sizeof(x)/sizeof(x[0]);
    alen = sizeof(b)/sizeof(b[0]);

    y = malloc(test_len * sizeof(FLOAT_TYPE));
    z = malloc((alen - 1) * sizeof(FLOAT_TYPE));
    memset(z, 0, (alen - 1) * sizeof(FLOAT_TYPE));

    print_array(a, alen, "a");
    print_array(b, alen, "b");
    filt(b, a, alen, x, y, z, test_len);
    print_array(x, test_len, "x");
    print_array(y, test_len, "y");

    free(y);
    free(z);

    return 0;
}
```
it produced:

> a = [
> 1.000000, -4.704431, 8.835448, -9.035994, 7.047864,
> -5.752393, 3.595899, -1.134326, 0.327379, -0.227402,
> 0.027229, 0.016533, 0.004196 ]
> b = [
> 0.063683, 0.000000, -0.382098, 0.000000, 0.955244,
> 0.000000, -1.273659, 0.000000, 0.955244, 0.000000,
> -0.382098, 0.000000, 0.063683 ]
> x = [
> 68.870282, 9.060559, -41.165513, -75.531157, -88.774796,
> -73.870907, -26.396228, 48.018380, 131.380533, 198.277403,
> 226.797090, 211.171874, 165.436312, 112.153457, 67.548333,
> 38.699294, 31.287049, 52.435602, 100.620934, 152.533393,
> 164.813411, 98.363067, -48.540380, -226.671598, -360.658244,
> -399.725761, -354.285396, -283.848480, -244.785777, -247.291275,
> -260.764798, -254.400607, -227.141906, -201.552075, -196.364395,
> -207.100025, -209.422747, -179.704329, -116.214793, -44.356626,
> -0.975482, -9.375632, -63.250037, -129.587735, -167.823539,
> -153.427363, -91.811089, -14.551355, 40.095535, 52.112019,
> 33.229917, 15.007671, 19.092034, 38.722687, 49.887534,
> 36.859247, 4.033881, -32.387735, -56.829326, -58.624462,
> -32.739096, 15.168231, 64.231118, 86.709084, 68.854416,
> 25.732482, -6.917594, 1.496475, 54.920584, 128.999129,
> 186.222913, 195.821797, 150.640980, 75.831086, 19.360781,
> 20.292528, 76.149338, 143.561693, 176.644278, 165.508397,
> 137.655128, 126.685393, 143.901935, 176.967292, 206.313213,
> 216.517334, 197.413014, 146.612458, 76.799542, 15.678502,
> -9.183271, 9.701888, 52.130328, 81.144562, 64.752252,
> -4.980060, -106.455049, -200.456356, -253.265126, -256.240904 ]
> y = [
> 4.385863, 21.209996, 32.093178, -5.061099, -70.761000,
> -89.624334, -56.910393, -18.674279, 33.821624, 111.707497,
> 172.856789, 188.410371, 164.755964, 108.516908, 35.417146,
> -25.435888, -60.964680, -74.514775, -64.374293, -28.754715,
> 17.130606, 40.417302, 5.103096, -102.783349, -252.401701,
> -375.626939, -409.978460, -343.826005, -225.020475, -123.041730,
> -75.038253, -64.468062, -50.358647, -12.428333, 34.756488,
> 65.282523, 71.391118, 70.509660, 88.671483, 137.323559,
> 201.314726, 246.914767, 244.953729, 192.309022, 115.802505,
> 56.420005, 45.211628, 85.556888, 151.631779, 204.135418,
> 214.558200, 183.094164, 136.873810, 107.041938, 102.174841,
> 103.452148, 86.710026, 46.688103, -1.351617, -37.921855,
> -51.588191, -39.466246, -5.991270, 34.097315, 56.961061,
> 43.380618, -3.187538, -53.498971, -72.099344, -44.124909,
> 13.730083, 64.999986, 75.827681, 33.319376, -46.294504,
> -122.531361, -152.050352, -119.720849, -54.395531, -7.748303,
> -10.383280, -48.214544, -81.990541, -85.662379, -63.922862,
> -39.305353, -31.415539, -49.134469, -93.006327, -154.586340,
> -212.958204, -240.999467, -223.652675, -172.367213, -120.748687,
> **-104.153171, -138.156407, -208.945028, -280.563149, -315.358536 ]**

Surprisingly, this result was identical to my implementation, but it was also different from the result of ```scipy.signal.lfilter()```

> [ 4.38586347 21.2099964 32.09317833 -5.06109974 -70.761003
> -89.62434106 -56.91040685 -18.67430149 33.82159298 111.70745923
> 172.85674628 188.41032573 164.75592111 108.5168695 35.41711344
> -25.43591775 -60.96471698 -74.51483776 -64.37441586 -28.75495597
> 17.13015853 40.41651835 5.10179183 -102.7854231 -252.40487391
> -375.63163197 -409.9851965 -343.83542232 -225.03333537 -123.0589278
> -75.06082296 -64.49718518 -50.39564898 -12.47468325 34.69918665
> 65.21254408 71.30662884 70.40874064 88.5521507 137.18379792
> 201.15251506 246.72811686 244.74071399 192.06781997 115.53143432
> 56.11756627 44.87654418 85.18814585 151.22867072 203.69757786
> 214.08564219 182.5873198 136.33355876 106.46964157 101.5723719
> 102.82191826 86.055007 46.01185 -2.04495215 -38.62750924
> -52.30078014 -40.17976113 -6.6990733 33.4024899 56.28710032
> 42.73602201 -3.79366891 -54.05695054 -72.59891596 -44.55526828
> 13.38026673 64.74254273 75.67491162 33.28401857 -46.19930915
> -122.29210799 -151.65320879 -119.15169775 -53.64001245 -6.79186031
> -9.21121198 -46.81205304 -80.34278412 -83.754522 -61.74013395
> -36.83309942 -28.63927969 -46.03995487 -89.57959889 -150.81378566
> -208.82662064 -236.49611341 -218.76533443 -167.08424714 -115.05909493
> **-98.04664446 -131.62338194 -201.9767402 -273.15167903 -307.49685834**]

which could be produced by below snippet in python:

```
from scipy import signal
k = [
   68.87028238,    9.06055931,  -41.16551312,  -75.53115689,   -88.7747965,         
  -73.87090749,  -26.39622799,   48.01838001,  131.38053294,  198.27740257,         
  226.79709025,  211.17187394,  165.43631153,  112.15345665,   67.54833255,         
   38.69929447,   31.28704854,   52.43560211,  100.62093416,  152.53339287,         
  164.81341145,   98.36306694,  -48.54038007, -226.67159829, -360.65824424,         
 -399.72576079, -354.28539641, -283.84847963, -244.78577714, -247.29127498,         
 -260.76479773, -254.4006073 , -227.14190637, -201.55207529, -196.36439469,         
 -207.10002523, -209.42274696, -179.70432872, -116.21479302,  -44.35662568,         
   -0.97548238,   -9.37563212,  -63.25003692, -129.58773535, -167.82353864,         
 -153.42736289,  -91.81108937,  -14.55135531,   40.09553498,   52.11201893,         
   33.22991684,   15.00767104,   19.09203366,   38.72268733,   49.88753405,         
   36.85924704,    4.0338805 ,  -32.38773479,  -56.82932645,  -58.62446164,         
  -32.73909629,   15.16823135,   64.23111848,   86.70908437,   68.85441629,         
   25.73248151,   -6.91759408,    1.49647513,   54.92058392,  128.99912854,         
  186.22291326,  195.82179748,  150.64098016,   75.83108595,   19.36078116,         
   20.29252799,   76.14933758,  143.56169284,  176.64427756,  165.50839739,         
  137.65512827,  126.68539317,  143.90193452,  176.96729221,  206.31321335,         
  216.51733394,  197.4130138 ,  146.61245783,   76.79954183,   15.67850213,         
   -9.18327099,    9.70188755,   52.13032831,   81.14456203,   64.75225195,         
   -4.98006001, -106.45504892, -200.45635588, -253.26512586, -256.24090435,
]
b, a = signal.butter(6, (0.6/50, 30/50), "bandpass")
print(k)
print(a)
print(b)
print(signal.lfilter(b, a, k))

```

As a matter of fact, the longer the input signal is, the farther the filtered signal values deviate. 
Now, my question becomes why the behavior of ```@NAME@_filt()``` in lfilter.c.src can be different from that of ```scipy.signal.lfilter()```? Your comments will be greatly appreciated.

**Comment by WeifengY** [comment]
Can anybody give me any instruction?

**Comment by WeifengY** [comment]
An answer is obtained from https://stackoverflow.com/questions/45076210/c-sharp-digital-filter-implementation-comparable-to-numpy-filtfilt. the difference between the results comes from the loss of precision of coefficients a & b when being copied by text.
the solutions to copy coefficients by binary.

Close it.

**Comment by jimakos96** [comment]
> An answer is obtained from https://stackoverflow.com/questions/45076210/c-sharp-digital-filter-implementation-comparable-to-numpy-filtfilt. the difference between the results comes from the loss of precision of coefficients a & b when being copied by text. the solutions to copy coefficients by binary.
> 
> Close it.

Hi
So if i convert the coefficients a,b,z to binary and give them as input in the c implementation will the precision  increase ?

**Comment by jimakos96** [comment]
Hi
So if i convert the coefficients a,b,z to binary and give them as input in the c implementation will the precision of the filter increase and the results will be closer to the python lfilter function?
