### ISSUE TITLE
BUG: linalg.schur: bug sorting complex eigenvalues in real form

### ISSUE THREAD

**Issue by axsk** [scipy/scipy#13137]
Writing my own sort callables with the schur function it seemed that complex eigenvalues `complex(a,b)` don't get passed to the sort callable via `callable(complex(a,b))` but rather as `callable(a,b)`.

This would imply that the corresponding default sortings `iuc` and `ouc` are not working correctly. The current code expects a single complex variable passed, but instead gets passed the real value only.

The corresponding lines https://github.com/scipy/scipy/blame/67146a96e6c227a85658322429f402ceab91875b/scipy/linalg/decomp_schur.py#L150 are fairly old (10y). Possibly the way how the lapack functions pass complex numebers has changed inbetween?

I observed the problem with SciPy 1.5.2.

**Comment by mdhaber** [comment]
This is indeed a bug. PR for this and gh-15016 coming shortly.
