### ISSUE TITLE
[FEATURE] 2D roc_curve

### ISSUE THREAD

**Issue by andrzejnovak** [scipy/scipy#13131]
In some cases, one wants to see the performance of applying two classifiers simultaneously. To see the performance one would want to look at a 2D roc curve, such as the one here https://cds.cern.ch/record/2703386/plots#0 

<img src="https://user-images.githubusercontent.com/13226500/100224703-76493b80-2f1d-11eb-8926-03e04a40558a.png" width="400" />

It would be very convenient to have this available as a canned method like the 1d roc curve. I would expect a signature like
```
tpr, fpr1, fpr2 = roc_curve2D(ypred1, ypred2, ytru)
```
where `tpr, fpr1, fpr2` would be `np.meshgrid`-like arrays

**Comment by rkern** [comment]
We don't have any code about ROC curves of any variation in scipy. Did you mean to post this to [scikit-learn](https://github.com/scikit-learn/scikit-learn) instead?

**Comment by andrzejnovak** [comment]
Whoops, you are right of course. Gotta drink more coffee, before opening issues :)
