### ISSUE TITLE
roc_curve sampling points

### ISSUE THREAD

**Issue by andrzejnovak** [scipy/scipy#13132]
**Is your feature request related to a problem? Please describe.**

I was making some projections of the ROC curves to show the differences between a couple of them, but the sampling is dynamic, so to do this I needed a function find the closest x-point and get by index the matching y-point.

**Describe the solution you'd like**

This could be easily fixed, by allowing the `roc_curve` to take at which x/tpr values the fpr should be sampled

**Comment by rkern** [comment]
I think you meant to post this to [scikit-learn](https://github.com/scikit-learn/scikit-learn).
