### ISSUE TITLE
Missing wheels for windows and scipy 1.5.4 on conda ?

### ISSUE THREAD

**Issue by neutrinoceros** [scipy/scipy#13145]
#### Reproducing code example:

Hi, I'm maintaining the Yt project (https://github.com/yt-project/yt/)
where I'm trying to upgrade our tests on GitHub actions to use Python 3.9.
The current hurdle is that, scipy 1.5.4 doesn't have wheels on condo-forge, either for Python 3.8 or 3.9 yet

on windows
```shell
conda install --channel conda-forge scipy=1.5.4 
```

error
```
PackagesNotFoundError: The following packages are not available from current channels:
  - scipy~=1.5.4
Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're

looking for, navigate to
    https://anaconda.org

and use the search bar at the top of the page.
Error: Process completed with exit code 1.
```

Can I ask when/if these wheels are supposed to be made available ?

**Comment by ev-br** [comment]
Are we building conda-forge wheels, too? Used to be some third party

**Comment by andyfaff** [comment]
Will be caused by https://github.com/conda-forge/scipy-feedstock/pull/149. This is an issue to do with the conda-forge scipy feedstock, not the scipy project itself.

**Comment by andyfaff** [comment]
Note that a conda package is not equivalent to a wheel. There are scipy wheels for version 1.5.4 and python 3.6 to 3.9 available on pypi

**Comment by neutrinoceros** [comment]
Ok thanks for the clarification !
