### ISSUE TITLE
Kendalltau calculation variance

### ISSUE THREAD

**Issue by zitz2310** [scipy/scipy#13162]
My issue is about bug in the variance calculation and therefore incorrect p-values
####original code

    elif method == 'asymptotic':

        # con_minus_dis is approx normally distributed with this variance [3]_

        var = (size * (size - 1) * (2.*size + 5) - x1 - y1) / 18. + (

            2. * xtie * ytie) / (size * (size - 1)) + x0 * y0 / (9. *

            size * (size - 1) * (size - 2))

        pvalue = special.erfc(np.abs(con_minus_dis) / np.sqrt(var) / np.sqrt(2))``

#### Multiplication by 2*xtie*ytie in second line of var formulae above is icorrect. It should be as below according to wikipedia:
        var = (size * (size - 1) * (2.*size + 5) - x1 - y1) / 18. + (

            xtie * ytie) / (2.* size *(size - 1)) + x0 * y0 / (9. *

            size * (size - 1) * (size - 2))

        pvalue = special.erfc(np.abs(con_minus_dis) / np.sqrt(var) / np.sqrt(2))..

**Comment by WarrenWeckesser** [comment]
`xtie` is `sum(t[i]*(t[i] - 1))/2` (note the division by 2); `ytie` is defined similarly.  If you take that division by 2 into account, the formulas work out to be equivalent.

And as a sanity check, we can compare the p-values computed by `scipy.stats.kendalltau` and by `cor.test` in R.

Here's SciPy:
```
In [16]: x = np.array([1, 3, 5, 7, 9, 9, 10])

In [17]: y = np.array([0, 1.5, 1.5, 1.5, 4, 5, 9])

In [18]: kendalltau(x, y)
Out[18]: KendalltauResult(correlation=0.8959786703810408, pvalue=0.0070524199492218)
```
And here's R:
```
> x <- c(1, 3, 5, 7, 9, 9, 10)
> y <- c(0, 1.5, 1.5, 1.5, 4, 5, 9)
> cor.test(x, y, method='kendall')

	Kendall's rank correlation tau

data:  x and y
z = 2.6944, p-value = 0.007052
alternative hypothesis: true tau is not equal to 0
sample estimates:
      tau 
0.8959787 

Warning message:
In cor.test.default(x, y, method = "kendall") :
  Cannot compute exact p-value with ties
```
They compute the same value for tau and for the p-value.

I'm closing the issue, but let us know if I missed something and you think there is still a problem.
