### ISSUE TITLE
Uninformative error message from bisplev function

### ISSUE THREAD

**Issue by ZhihuiChen0903** [scipy/scipy#13173]
Code: see the post [https://stackoverflow.com/questions/46983476/]( https://stackoverflow.com/questions/46983476/)

Got error message:
![image](https://user-images.githubusercontent.com/57449793/100565882-7f605100-32ff-11eb-9656-48c0232feb2a.png)

The error message `Invalid input data` is uninformative. 
Is it possible to provide the reason or solution of the error in the error message?

**Comment by AtsushiSakai** [comment]
I think this is duplicate with #8565. The error message should be improved, I think.

**Comment by ev-br** [comment]
Fixed by gh-13436, so closing.
