### ISSUE TITLE
Incorrect triple integration result

### ISSUE THREAD

**Issue by vintingb** [scipy/scipy#13174]
My issue is about Incorrect triple integration result

#### Reproducing code example:

```
from scipy import integrate


def getI(f):
    def g(x):
        return 1 - x

    I1, err = integrate.tplquad(f, 0, 1, 0, g, 0, 1)
    print(I1)


getI(lambda x, y, z: y)
getI(lambda x, y, z: x)
```

#### Terminal output:

```
0.16666666666666669
0.25
```
In fact, the result should be 1/6

#### Scipy/Numpy/Python version information:
Scipy 1.54
Numpy 1.19.3
Python 3.9.0

**Comment by mdhaber** [comment]
To make this easier to review, can you write out mathematically what integral you are trying to evaluate and why the value should be 1/6?
Also, which of those results do you expect to be 1/6?

**Comment by vintingb** [comment]
![1A9CBF54772CCFE330D703FDB92B104D](https://user-images.githubusercontent.com/54710337/100584208-bf86fa00-3326-11eb-90fd-2cbd0edbe062.png)

**Comment by vintingb** [comment]
> To make this easier to review, can you write out mathematically what integral you are trying to evaluate and why the value should be 1/6?
> Also, which of those results do you expect to be 1/6?

![1A9CBF54772CCFE330D703FDB92B104D](https://user-images.githubusercontent.com/54710337/100584235-cb72bc00-3326-11eb-92c0-1675ee286f2b.png)

**Comment by vintingb** [comment]
> To make this easier to review, can you write out mathematically what integral you are trying to evaluate and why the value should be 1/6?
> Also, which of those results do you expect to be 1/6?

If I use matlab, the result is
![QQ截图20201130162424](https://user-images.githubusercontent.com/54710337/100585479-9ebfa400-3328-11eb-8f20-9f9db75c5e15.png)

**Comment by WarrenWeckesser** [comment]
As noted in the [docstring](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.tplquad.html), `tplquad` expects the integrand to be defined as `func(z, y, x)` (note the order of the parameters).  Here's one way to express your integral using `tplquad`:
```
In [36]: def func(z, y, x): 
    ...:     return x 
    ...:                                                                                                                   

In [37]: tplquad(func,  
    ...:         0, 1,                # x limits 
    ...:         0, lambda x: 1 - x,  # y limits 
    ...:         0, 1)                # z limits 
    ...:                                                                                                                   
Out[37]: (0.16666666666666669, 1.1078122658246858e-14)
```

**Comment by vintingb** [comment]
> As noted in the [docstring](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.tplquad.html), `tplquad` expects the integrand to be defined as `func(z, y, x)` (note the order of the parameters). Here's one way to express your integral using `tplquad`:
> 
> ```
> In [36]: def func(z, y, x): 
>     ...:     return x 
>     ...:                                                                                                                   
> 
> In [37]: tplquad(func,  
>     ...:         0, 1,                # x limits 
>     ...:         0, lambda x: 1 - x,  # y limits 
>     ...:         0, 1)                # z limits 
>     ...:                                                                                                                   
> Out[37]: (0.16666666666666669, 1.1078122658246858e-14)
> ```

Thanks brother
