### ISSUE TITLE
BUG: Metadata wrong for newer pip resolver

### ISSUE THREAD

**Issue by larsoner** [scipy/scipy#13196]
In [this CI run](https://github.com/mne-tools/mne-python/pull/8602/checks?check_run_id=1493157817) which has pip 20.3, installing our pre-release wheels with:
```
python -m pip install --upgrade --pre --only-binary ":all:" -f "https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com" scipy
```
fails:
```
Collecting scipy
  Downloading https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/1.6.0.dev0%2B2af2d98/scipy-1.6.0.dev0%2B20201111023958_2af2d98-cp39-cp39-manylinux1_x86_64.whl (26.4 MB)
ERROR: Requested scipy from https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/1.6.0.dev0%2B2af2d98/scipy-1.6.0.dev0%2B20201111023958_2af2d98-cp39-cp39-manylinux1_x86_64.whl has different version in metadata: '1.6.0.dev0+2af2d98'
```
Using `--use-deprecated=legacy-resolver` in the `pip` call is a workaround.

Probably the same issue as https://github.com/numpy/numpy/issues/17885 ~~solved~~ EDIT: *worked around* by https://github.com/numpy/numpy/pull/17886 and discussed in https://github.com/pypa/pip/issues/9186.

**Comment by charris** [comment]
The current NumPy solution is a stop gap. Once 1.20.0rc1 is out I am going to switch to [versioneer](https://github.com/python-versioneer/python-versioneer).

**Comment by h-vetinari** [comment]
Needs to be re-milestoned

**Comment by rgommers** [comment]
This is fixed now, closing.
