### ISSUE TITLE
pinv for sparse linalg

### ISSUE THREAD

**Issue by rjkilpatrick** [scipy/scipy#13195]
**Is your feature request related to a problem? Please describe.**
I wanted to determine the moore-penrose inverse on a sparse matrix, but this isn't currenly implemented.
Due to its size, it's not possible to use the dense version of the function.

**Describe the solution you'd like**
It's implemented for dense matrices as `scipy.linalg.pinv`, and the function should be given the equivalent signature `scipy.sparse.linalg.pinv`.

**Describe alternatives you've considered**
Since SVD is already implemented for sparse matrices, it would be perfectly possible to calculate it with this, but I think it should be a built in function.

**Comment by ilayn** [comment]
Pseudo inverse of sparse matrices are often dense and cannot be constructed and hence often skipped. There are alternative solutions such as custom generalized inverses (different than Moore-Penrose machinery), total least squares and so on. Hence we won't be able to provide them. You might want to formulate your problem suitable for such avenues. Or you directly solve via sparse least squares whatever problem you want to solve.
