### ISSUE TITLE
sigma argument as a function of observation and parameters- for scipy.optimize.curve_fit

### ISSUE THREAD

**Issue by AlexSlow94** [scipy/scipy#13205]
Suppose that one wants to minimize the weighted least squares function:
$\sum \frac{y_i-f(x_i,\theta)^2}{\sigma_i^2} $ .
`np.sum( (y-f(x,*params) / sigma)**2)`
If the dataset comes from, e.g., Poisson distributions (centered at the "true" values), it is possible to make as an approximation the substitution $\sigma_i^2=y_i$ (`sigma=np.sqrt(y)`).
However, another choice could be made by making the substitution $\sigma_i^2=f(x_i,\theta)$ (`sigma=f(x,*params)`) (see for example G. Cowan, Statistical Data Analysis, paragraph 7.4).
Can curve_fit or generally the Levenberg-Marquardt algorithm handle this situation?
Sorry for the Latex-style writing of expressions, I am new and I don't know how to write them.

**Comment by josef-pkt** [comment]
You can do it by faking y = zeros, but it might not solve the optimization problem that you want, see below.

statsmodels has Poisson model that estimates parameters by maximum likelihood. I had an example open in a notebook.
(Poisson uses `exp` mean function to impose positive Poisson mean)

```
def fun(data, *params):
    y = data[:, 0]
    x = data[:, 1:]
    m = np.exp(x @ params)
    return (y - m) / np.sqrt(m) 

optimize.curve_fit(fun, np.column_stack((y,exog)), np.zeros(len(y)), respoi.params)
(array([1.14423838, 2.0634058 ]), ...
```

with leastsquares

```
x = exog
​
def fun2(params):
    m = np.exp(x @ params)
    return (y - m) / np.sqrt(m) 
​
res_nl = optimize.least_squares(fun2, respoi.params)
res_nl.x
array([1.14423838, 2.0634058 ])
```

However, this does not estimate a poisson model.
If weights are also a function of the parameters in the optimization, then the first order conditions for the optimization are not the same as for Poisson maximum likelihood.

For fixed sigma2 that corresponds to the Poisson MLE

```
m2 = respoi.predict()  # results from statsmodels Poisson
​
def fun2(params):
    m = np.exp(x @ params)
    return (y - m) / np.sqrt(m2) 
​
res_nl = optimize.least_squares(fun2, respoi.params)
res_nl.x
array([0.99325177, 1.99786989])

respoi.params
array([0.99325177, 1.99786989])
```

**Comment by josef-pkt** [comment]
related aside
iteratively reweighted least-squares IRLS is a default method for Poisson and similar generalized linear models.

IRLS iterates over weighted least squares estimate, where the least squares estimates take weights as fixed and the outer iterations update weights.
In standard IRLS, we can use linear least squares inside the iteration loop.

**Comment by mdhaber** [comment]
It looks to me like this was a question, and it has been answered. Please re-open if there is an associated feature request.
