### ISSUE TITLE
Windows wheel performance of interpolate.griddata

### ISSUE THREAD

**Issue by ncgeib** [scipy/scipy#13201]
When running `scipy.interpolate.griddata` using the official Windows wheels from pip I noticed a slowdown by a factor 7-8 as compared to other builds (e.g, Anaconda or conda-forge). Also, when running the same code on Linux and comparing pip wheels <> Anaconda there is some slowdown, but only within a factor of 2. 

As far as I know Anaconda uses Intel MKL whereas the pip wheels ship OpenBLAS (probably, the current status was hard to figure out). This could explain some of the runtime difference but it should usually not be this large. Also, I was unable to track down if and how MKL/OpenBLAS is involved in griddata, which relies on spatial.Delaunay, which relies primarily on Cython code and the qhull library.

Any insight into this issue is appreciated. Even if it boils down to something scipy cannot fix. I am genuinely interested.

The example code:

```python
import time
import numpy as np
from scipy.interpolate import griddata

np.random.seed(123)

# test griddata
print("Running griddata(): ", end="")
x, y, z = np.random.randn(3, 10000)
x2, y2 = np.linspace(-1.0, 1.0, 250), np.linspace(-1.0, 1.0, 251)

start = time.perf_counter()
for i in range(100):
    z2 = griddata((x, y), z, (x2[None, :], y2[:, None]))
stop = time.perf_counter()
print("%.3f seconds." % (stop - start))
```

This produces on my Windows machine:

```
Running griddata(): 42.665 seconds.  # v1.5.4 on python 3.9.0 official wheel from pypy
Running griddata(): 7.335 seconds.   # v1.5.2 on python 3.8.5 from Anaconda
```

On a (different) Linux machine:

```
Running griddata(): 8.853 seconds.  # v1.5.4 on python 3.9.0 official wheel from pypy
Running griddata(): 5.515 seconds.  # v1.5.2 on python 3.8.5 from Anaconda
```

**Comment by rgommers** [comment]
Interesting, I have no idea. Had not expected a large difference based on Qhull build options.

**Comment by mdhaber** [comment]
@ev-br In my development conda `environment` (SciPy `main`, OpenBLAS), this took 16.626 seconds, but in my `base` environment (SciPy 1.7.1, MKL), it took 5.669 seconds. Should I create a new environment, install everything with `pip`, and try that?

**Comment by ev-br** [comment]
@mdhaber yes indeed, it would be instructive to compare the performance of the OP test case with conda-forge and the official wheel. With an as recent scipy as realistic, 1.9.2 would be best if possible.

**Comment by ev-br** [comment]
I think we can close this unless somebody feels like redoing the perf comparison with the current wheel builds. The OP was reported with numpy.distutils builds, and so was Matt's check in 2022. Thanks for the report @ncgeib, thanks for testing @mdhaber !
