### ISSUE TITLE
More accurate erf(a)-erf(b)

### ISSUE THREAD

**Issue by disadone** [scipy/scipy#13218]
**Is your feature request related to a problem? Please describe.**
I need to calculate erf(a)-erf(b). If a or b is too large or too small, the result is zero. Accuracy is not satisfied by directly minus two erf numbers.

**Describe the solution you'd like**
There should be a "generalized" erf function as the [Mathematica Erf function](https://reference.wolfram.com/language/ref/Erf.html) that can help more accurately calculate erf(a)-erf(b). Array input is also available as erf.

**Describe alternatives you've considered**
integrate the error function formula directly with pool.map acceleration.

**Additional context (e.g. screenshots)**
Nothing

**Comment by mdhaber** [comment]
Is this an example of the problem (and a little extra, exploring the error of direct integration)?
```
import numpy as np
from scipy.integrate import quad
from scipy.special import erf
from mpmath import mp, mpf, erf as mperf

a = 10
b = 10 + 1e-6
print(f"{'subtraction:':<20} {erf(b) - erf(a)}")

def f(t):
    return 2/np.sqrt(np.pi)*np.exp(-t**2)
res, err_est = quad(f, a, b)
print(f"{'quad:':<20} {res}")

mp.dps = 65
a = mpf(10)
b = mpf("10.000001")
res2 = mperf(b) - mperf(a)
err_act = np.abs(res - res2)
print(f"{'mpmath, b as string:':<20} {res2}")

b = mpf(10.000001)
res3 = mperf(b) - mperf(a)
print(f"{'mpmath2, b as float:':<20} {res3}")
err_act2 = np.abs(res - res3)

print("")
print(f"{'quad error estimate:':<26} {err_est}")
print(f"{'actual error, b as string:':<26} {err_act}")
print(f"{'actual error, b as float:':<26} {err_act2}")
```
Prints:
```
subtraction:         0.0
quad:                4.1976142519291535e-50
mpmath, b as string: 4.1976142550705465403554701095830886833657020819775124574099697604e-50
mpmath2, b as float: 4.1976142519290815721329953109376220112704556821054635034650444699e-50

quad error estimate:       4.6602879909864485e-64
actual error, b as string: 3.141393039296800668169954562285054468046605730128735619342930659e-59
actual error, b as float:  7.1928925674130475512109810191931825443223816189671083119569333431e-64
```

**Comment by disadone** [comment]
Sorry. NO.
```python
from scipy.special import erf, erfc
from mpmath import mp, mpf, erf as mperf
mp.dps = 65


a=-12.946102404277376
b=-12.696069446449812
print(erfc(b) - erfc(a))
print(mperf(a) - mperf(b))

a=12.946102404277376
b=12.696069446449812
print(erfc(b) - erfc(a))
print(mperf(a) - mperf(b))
```

Prints
```
0.0
0.0
4.3824116403632767e-72
0.0
```

My solution for now (slow):
```python
def _erf_kernel(x):
    return 2/np.sqrt(np.pi)*np.exp(-x**2)
def gerf(z0,z1):
    """
    accurate way for calculating erf(z1)-erf(z0)
    
    Parameters
    ----------
    z0 : float
        lower limit
    z1 : float
        upper limit
    Returns
    -------
    np.ndarray
        value of erf(z1)-erf(z0)
    """    
    return np.vectorize(quad)(_erf_kernel,z0,z1)[0]
```

**Comment by mdhaber** [comment]
Yeah my original response to this question had some code for `quad`. I removed it when I realized `erfc` works in some cases. Maybe others have ideas for a workaround. If not, if you can find some license-compatible c++ or fortran code that does what you need, we might be able to help you add it.

**Comment by disadone** [comment]
Thank you! Matt. ```quad``` is more accurate than ```erfc```. I will try to find some code. In Mathematica, they declare that they use an integration method, maybe, like ```quad```.

**Comment by disadone** [comment]
I have a better solution that may make this requirement unnecessary.

```python
from scipy.special import log_ndtr
def ndtr_erf(z0,z1):
    return 2*(np.exp(log_ndtr(z1*np.sqrt(2)))-np.exp(log_ndtr(z0*np.sqrt(2))))

z0=-26.99252723608743
z1=-26.74249427825987
print(ndtr_erf(z0,z1))
```
Prints:
```
5.41306632697e-313
```

**Comment by mdhaber** [comment]
Funny, i was playing around with exactly that last night, but i didn't think it was going to help. I guess I should have tried it all the way through. Glad that works for you!

**Comment by disadone** [comment]
Yeah, Matt. I also thought this is not working, but no more options are available for me.
I found another issue using `log_ndtr` method. If I set the previous example positive
```python
z0=26.99252723608743
z1=26.74249427825987
```
My `ndtr_erf` gives 0. **It seems that `log_ndtr` has a bias inside.**
To make this solution complete, though it looks a little bit dumb
```python
def gerf(z0,z1):
    nz0=z0.copy()
    nz1=z1.copy()
    pos=(z0>0) & (z1>0)
    nz0[pos]=-nz0[pos]
    nz1[pos]=-nz1[pos]
    prob=2*(np.exp(log_ndtr(nz1*np.sqrt(2)))-np.exp(log_ndtr(nz0*np.sqrt(2))))
    prob[pos]=-prob[pos]
    return prob
```

**Comment by mdhaber** [comment]
No, I think it's reasonable to do that. You get catastrophic cancellation on the right side, but it's symmetric, so you just do the calculation on the left. Makes sense.

**Comment by mdhaber** [comment]
@DominicChm 
```python3
from scipy.special import ndtr, erfc, erf

def Phi(x):
    return ndtr(x)

def dPhi0(x, y):
    return Phi(x) - Phi(y)

def dPhi1(x, y):
    sqrt2 = np.sqrt(2)
    return -0.5*(erfc(x/sqrt2) - erfc(y/sqrt2))

x = 3
y = x+0.001
print(dPhi0(x, y))
print(dPhi1(x, y))
```
prints
```
-4.425206545088933e-06
-4.42520654512688e-06
```

`dPhi0` can't make it past `x = 8`:
```
> x = 8
> y = x+0.001
> print(dPhi0(x, y))
0
> print(dPhi1(x, y))
-5.032114945472375e-18
```

`dPhi1` can go out to `x = 37`:
```
> x = 37
> y = x+0.001
> print(dPhi0(x, y))
0
 > print(dPhi1(x, y))
-2.081265360020525e-301
```

In the left tail (negative `x` and `y`), it's the other way around. So the idea is to use the appropriate calculation depending on which tail you're in, and you can go out a lot further before losing all precision.

**Comment by mdhaber** [comment]
For future reference, really helpful comment about this sort of thing [here](https://github.com/scipy/scipy/issues/13923#issuecomment-825118292).
