### ISSUE TITLE
[WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by aep013191** [scipy/scipy#13213]
I have the most recent version 1.5.4 installed, is anyone else encountering a similar problem or aware of the work around?

![image](https://user-images.githubusercontent.com/69614817/101450792-14afa680-38f9-11eb-9592-23ee128f5ff5.png)

**Comment by aep013191** [comment]
Thank you, Matt. Apologies in advance as I'm still relatively new around here. These instructions do not seem to resolve the problem, unless I am understanding incorrectly?

The following:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
```

Produces:
```
Traceback (most recent call last):
  File "C:/Users/alexa/OneDrive/Documents/GitHub/derivative_pricing/derivatives/Greeks.py", line 22, in <module>
    import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
  File "C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\__init__.py", line 136, in <module>
    from . import _distributor_init
  File "C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Comment by mdhaber** [comment]
Thanks. The instructions were not intended to resolve the problem; I was just asking you to provide the information needed to understand the problem by copying and pasting the prompts from the bug report template.

From the output, it seems that the problem occurs when you try to `import scipy`, suggesting that `scipy` is not properly installed.  This prevented the system information from printing, so can you report the output of:

```
import sys, numpy; print(numpy.__version__, sys.version_info)
````

Also, what operating system are you using, and how did you try to install SciPy (e.g. `pip`, `conda`, from source, etc...)?

**Comment by aep013191** [comment]
Hi Matt,

Output:
```
PyDev console: starting.
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 16:30:00) [MSC v.1900 64 bit (AMD64)] on win32
import sys, numpy; print(numpy.__version__, sys.version_info)
1.19.4 sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)
```

I am running on windows 10 Home, and everything was installed using the interpreter

**Comment by aep013191** [comment]
Very odd, I tried to uninstall scipy but received an error that its not installed. Note I installed the package through the interpreter

```
C:\Users\alexa\OneDrive\Documents\GitHub\derivative_pricing>pip uninstall scipy
WARNING: Skipping scipy as it is not installed.
```

When trying to install using pip, the following error was generated:
```
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\program files\\python38\\Lib\\site-packages\\numpy'
Consider using the `--user` option or check the permissions.

WARNING: You are using pip version 19.2.3, however version 20.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by ilayn** [comment]
You have multiple python's installed. In your last message it is coming from py38 but your previous errors are from py37. So probably the versions are clashing. Consider uninstalling everything python related and install a fresh one.

**Comment by aep013191** [comment]
Thank you so much, Ilayn. It was a complete mess but that resolved the issue

**Comment by niektuytel** [comment]
NEVER install it from the windows store!

**Comment by dujong** [comment]
scipy version 1.4.0 install
