### ISSUE TITLE
Segmentation fault with `eigh(..., driver="evx")` for 10x10 matrices and above

### ISSUE THREAD

**Issue by jonaslb** [scipy/scipy#13239]
I always get segfault when attempting to use the evx driver for eigh. Not for very small matrices though, only for 10x10 and above.
I don't particularly *need* to use the evx driver, but I was just testing to see if it would work faster than evr for my use case, as the docs mention it may be good method when requesting few eigenvalues in a large problem. To my surprise though, it doesn't work at all for that case.

#### Reproducing code example:

```
from numpy.random import rand; from scipy.linalg import eigh
x = rand(10,20).view(dtype=complex); x += x.T.conj()
eigh(x, driver="evx")
```

#### Error message:
```
Segmentation fault (core dumped)
```

#### Scipy/Numpy/Python version information:

```import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)```

Reproduced the issue  on several systems:
+ Fedora 32 desktop system (scipy is from pip to get latest version, numpy and lapack is system packages): ```1.5.4 1.18.4 sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)```
+ Fedora 33 desktop system (everything system packages): ```1.5.2 1.19.4 sys.version_info(major=3, minor=9, micro=0, releaselevel='final', serial=0)```
+ A HPC installation: ```1.5.2 1.19.1 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)```
+ Another HPC installation: ```1.5.4 1.19.4 sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)```

**Comment by ilayn** [comment]
Indeed I can reproduce this on Windows 10 py3.9

**Comment by zerothi** [comment]
It seems to me that it always queries "NO" eigenvalue calculations for `_lwork`
```python
subroutine <prefix2c>heevx_lwork(lower,n,a,lda,vl,vu,il,iu,abstol,m,w,z,ldz,work,lwork,rwork,iwork,ifail,info)
    ! LWORK routines for (c/z)heevx

    fortranname <prefix2c>heevx
    callstatement (*f2py_func)("N","A",(lower?"L":"U"),&n,&a,&lda,&vl,&vu,&il,&iu,&abstol,&m,&w,&z,&ldz,&work,&lwork,&rwork,&iwork,&ifail,&info)
    callprotoargument char*,char*,char*,F_INT*,<ctype2c>*,F_INT*,<ctype2>*,<ctype2>*,F_INT*,F_INT*,<ctype2>*,F_INT*,<ctype2>*,<ctype2c>*,F_INT*,<ctype2c>*,F_INT*,<ctype2>*,F_INT*,F_INT*,F_INT*
```

The first 3 arguments in `heevx` are: `compute_v`, `range` and `lower`. None of the first two are used...

**Comment by zerothi** [comment]
However, there are quite a bit of routines that have this explicitly written... I don't know if this may the reason.

**Comment by ilayn** [comment]
These hardcoded values is `_lwork` wrappers mostly done by looking at the `lwork=-1` branch of the original code and only leave those parameters available. For example `zheevx` does 

```fortran
       IF( info.EQ.0 ) THEN
          IF( n.LE.1 ) THEN
             lwkmin = 1
             work( 1 ) = lwkmin
          ELSE
             lwkmin = 2*n
             nb = ilaenv( 1, 'ZHETRD', uplo, n, -1, -1, -1 )
             nb = max( nb, ilaenv( 1, 'ZUNMTR', uplo, n, -1, -1, -1 ) )
             lwkopt = max( 1, ( nb + 1 )*n )
             work( 1 ) = lwkopt
          END IF
```

Hence there is no reference to the job or range. But maybe they are related I'll take a look.

**Comment by zerothi** [comment]
You are correct, I had always anticipated that they were meaningful. But perhaps they are not!

**Comment by ilayn** [comment]
I guess I found it after looking at it so long. I really hate these wrappers. Who wrote these things?... oh wait

In the `callstatement` we (probably I) passed `rwork` by pointer and that is wreaking havoc. I don't know how it survived to this day though. Probably my brainfart along the way. I'll fix it asap.
