### ISSUE TITLE
Kurtosis returning 1 for array of same elements

### ISSUE THREAD

**Issue by stefannesic** [scipy/scipy#13245]
My issue is about scipy.stats.kurtosis returning 1.0 instead of 0.0 for a large array of repeating floating point elements.

#### Reproducing code example:

```
a = np.repeat(-0.27829495, 10)
sstats.stats.kurtosis(a, fisher=False)
```

#### Result
```
1.0
```

#### Scipy/Numpy/Python version information:

```
1.4.1 1.17.2 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
This looks like the same problem that was reported for `skew` in gh-11086.  For this constant array, `np.mean(a)` does not equal the values in the array:

```
In [6]: a = np.repeat(-0.27829495, 10)

In [7]: a[0]
Out[7]: -0.27829495

In [8]: np.mean(a)
Out[8]: -0.27829494999999993
```

**Comment by mdhaber** [comment]
@WarrenWeckesser We've seen this for a bunch of functions, and we've seen how much code it takes to fix it (gh-13154), with all the different forms the data can take. The patches don't actually fix the problem when data is nearly constant. I noticed that `boxcox` takes a different approach. In the docstring for `x`: 
```
Input array. Must be positive 1-dimensional. Must not be constant.
```
Shall I open a PR for that?

**Comment by WarrenWeckesser** [comment]
The expressions for the [sample skew](https://en.wikipedia.org/wiki/Skewness#Sample_skewness) and [sample kurtosis](https://en.wikipedia.org/wiki/Kurtosis#Sample_kurtosis) result in 0/0 if you attempt to evaluate them with a constant input.  So a naive approach is to say that a constant input should either result in `nan` or raise an exception.

However, the docstrings actually state how the functions handle constant inputs.

[`skew`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.skew.html):
```
Returns
-------
skewness : ndarray
    The skewness of values along an axis, returning 0 where all values are
    equal.
```

[`kurtosis`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kurtosis.html)
```
Returns
-------
kurtosis : array
    The kurtosis of values along an axis. If all values are equal,
    return -3 for Fisher's definition and 0 for Pearson's definition.
```

I guess the `skew` result can be justified with a symmetry argument.  The `kurtosis` result is less clear to me.  Justified or not, we currently state clearly how constant input should be handled, so perhaps we should ensure that we do that?
