### ISSUE TITLE
Not enough values to unpack when passing tuple to `blocksize` in `sparse.bsr_matrix`

### ISSUE THREAD

**Issue by ducbueno** [scipy/scipy#13241]
Hello.

I'm trying to create a `bsr_matrix` with the `sparse` module using:

```
from scipy.sparse import bsr_matrix

bs = 3
dim = 300
nnzValues = ...
colIndices = ...
rowPointers = ...

mat = bsr_matrix((nnzValues, colIndices, rowPointers), blocksize=(bs, bs), shape=(dim, dim))
```

When I try to run this I get the following error:

```
Traceback (most recent call last):
  File "./convert.py", line 14, in <module>
    mat = bsr_matrix((nnzValues, colIndices, rowPointers), shape=(dim, dim), blocksize=(bs, bs))
  File "/home/ducbueno/.local/lib/python3.8/site-packages/scipy/sparse/bsr.py", line 212, in __init__
    self.check_format(full_check=False)
  File "/home/ducbueno/.local/lib/python3.8/site-packages/scipy/sparse/bsr.py", line 224, in check_format
    R,C = self.blocksize
ValueError: not enough values to unpack (expected 2, got 0)
```

It seems like the constructor isn't "seeing" that I have specified the `blocksize` parameter. 

Does anyone know whats going on?

**Comment by perimosocordiae** [comment]
The BSR format doesn't store blocksize explicitly, rather encoding it as the last two dimensions of the `self.data` array (in your example, `nnzValues`. When using the three-array constructor argument like you are, it's assumed that you've already shaped this array correctly and the explicit `blocksize` argument is ignored.

I think we may want to raise an error in cases where an explicit `blocksize` is given but doesn't match the dimensions of the data array.

**Comment by ducbueno** [comment]
Thanks a lot man! Reshaping my `nnzValues` array solved it.
