### ISSUE TITLE
sparse matrix converted to dense not work with numpy operation

### ISSUE THREAD

**Issue by zhaofeng-shu33** [scipy/scipy#13244]
My issue is about matrix type conversion

#### Reproducing code example:

```
from scipy.sparse import csr_matrix
import numpy as np
a=csr_matrix((3, 4))
A=a.todense()
print(np.sum(A, axis=0).shape)
# (1, 4)
# expected result should be (4,)
```

#### Scipy/Numpy/Python version information:
scipy = 1.5.4
numpy = 1.19.4

**Comment by WarrenWeckesser** [comment]
The `todense()` method returns a [`numpy.matrix`](https://numpy.org/doc/stable/reference/generated/numpy.matrix.html) object.  The `matrix` objects are special, in that they are always two-dimensional, and they are designed to create two-dimensional results even when a reduction such as a sum along an axis is applied to them.  When you sum a `matrix` with shape `(m, n)` along axis 0, the result will have shape `(1, n)`.

To convert your sparse matrix to a standard NumPy array, use the `toarray()` method:

```
In [121]: from scipy.sparse import csr_matrix

In [122]: a = csr_matrix((3, 4))

In [123]: A = a.toarray()

In [124]: np.sum(A, axis=0).shape
Out[124]: (4,)
```

**Comment by zhaofeng-shu33** [comment]
Thanks for your information. I am confused with `np.array` and `np.matrix` previously.
