### ISSUE TITLE
Does kmeans "drop" clusters?

### ISSUE THREAD

**Issue by btjanaka** [scipy/scipy#13242]
Hi, I am using [`scipy.cluster.vq.kmeans`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.vq.kmeans.html), and I noticed that on occasion, the number of clusters returned is not the same as the number of clusters passed in via the `k_or_guess` parameter. Specifically, I am passing in 10,000 points, and asking for 2000 clusters (I am approximating a Centroidal Voronoi Tesselation), and on occasion, I am getting back 1,999 or 1,998 clusters.

Is this behavior intended? If so:

1. Is it the result of clusters not having points assigned to them?
1. It does not seem to be mentioned in the documentation (though perhaps I missed it).
1. What can I do to mitigate it? Would increasing number of iterations (i.e. number of times kmeans is run) or number of samples help?

Thanks!

#### Reproducing code example:

This code should roughly replicate the error.

```python
import numpy as np
from scipy.cluster.vq import kmeans

samples = np.random.uniform(
    np.array([-1, -1]),
    np.array([1, 1]),
    size=(10_000, 2),
)

for i in range(10):  # Or however many itrs.
    centroids = kmeans(samples, 2000, iter=1)[0]
    print(len(centroids))
```

#### Error message:

The output from the above code is shown below. I would expect to only see 2000, no 1999.

```text
2000
2000
2000
1999
1999
1999
2000
2000
2000
2000
```

#### Scipy/Numpy/Python version information:

```
1.5.4 1.19.4 sys.version_info(major=3, minor=7, micro=8, releaselevel='final', serial=0)
```

**Comment by AtsushiSakai** [comment]
Hi. Thanks for reporting. I checked this behavior, same thing happened in my environment.

> Is this behavior intended? If so:

I think this is intended. The reason why the centroid number was changed is that some controids was assigned to no points, and this code removed these non-assigned centroids. 
https://github.com/scipy/scipy/blob/5f4c4d802e5a56708d86909af6e5685cd95e6e66/scipy/cluster/vq.py#L311

> 1. Is it the result of clusters not having points assigned to them?

Yes. I think your understanding is correct.

> It does not seem to be mentioned in the documentation (though perhaps I missed it).

Yes. I think the document is missing it. I think the document should be improved.

> What can I do to mitigate it? Would increasing number of iterations (i.e. number of times kmeans is run) or number of samples help?

You can use [scipy\.cluster\.vq\.kmeans2](http://scipy.github.io/devdocs/generated/scipy.cluster.vq.kmeans2.html#scipy.cluster.vq.kmeans2)

This function can keep the number of centroids.
https://github.com/scipy/scipy/blob/21d2b6ff75d0f82dc48f70f5d9e0fde07ee2d813/scipy/cluster/vq.py#L750-L755

**Comment by btjanaka** [comment]
@AtsushiSakai Thanks for the response! It's good to know I'm not going crazy. I also appreciate the new documentation in #13301; I will certainly consider using sklearn's kmeans instead.
