### ISSUE TITLE
GitHub Actions test failures for MacOS

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#13257]
For a while now the tests run via GitHub Actions on MacOS have been failing to build SciPy.  The error in the log is

    error: library mach has Fortran sources but no Fortran compiler found

It turns out there is a bug in `.github/workflows/macos.yml` that results in`gfortran` not being in the search path.  I fixed that in gh-13256, and in that PR, the build of SciPy completes, but then a segmentation fault occurs when the tests are run.

**Comment by andyfaff** [comment]
Fixed in #13260.
