### ISSUE TITLE
Link not working in the Ways to Contribute section

### ISSUE THREAD

**Issue by aflah02** [scipy/scipy#13250]
I was going through the Ways to Contribute section and saw the following where there was no redirecting upon clicking the link -

:ref:`contributor-toc` - twice
:ref:`deciding-on-new-features`
:ref:`license-considerations`
:doc:`numpy:reference/testing`
:ref:`runtests`
:ref:`benchmarking-with-asv`
:ref:`numpy:howto-document`
:ref:`rendering-documentation`
:ref:`pep8-scipy`
:ref:`checklist<pr-checklist>`
:ref:`development-workflow`
:ref:`scipy-api`
:ref:`git-development`
:ref:`scipy-licensing`

It seems the syntax is correct for the relinking but the file name might be wrong or might have been changed causing this error.

I'll be happy doing these changes if I can get any references to these documents so that I can link them

**Comment by AtsushiSakai** [comment]
Hi. Which document are you checking? The dev doc looks OK in my environment: [Ways to Contribute — SciPy v1\.7\.0\.dev0\+6e15c52 Reference Guide](http://scipy.github.io/devdocs/hacking.html)

**Comment by aflah02** [comment]
@AtsushiSakai I just realized I was probably looking at the back end of this file and codes like - :ref:contributor-toc didn't relink anywhere so maybe that was causing the errors. Sorry for taking up your time
