### ISSUE TITLE
scipy.stats.yeojohnson_llf doc mistake

### ISSUE THREAD

**Issue by MuellerSeb** [scipy/scipy#13272]
There is a *minus* missing in the documentation for the log-likelihood function of the Yeo-Johnson transformation:

https://github.com/scipy/scipy/blob/19acfed431060aafaa963f7e530c95e70cd4b85c/scipy/stats/morestats.py#L1414

should be (similar to the boxcox_llf):
```
    .. math::
        llf = -N/2 \log(\hat{\sigma}^2) + (\lambda - 1)
              \sum_i \text{ sign }(x_i)\log(|x_i| + 1)
```

It is correct in the code:
https://github.com/scipy/scipy/blob/19acfed431060aafaa963f7e530c95e70cd4b85c/scipy/stats/morestats.py#L1476

Cheers,
Sebastian

**Comment by mdhaber** [comment]
Thanks @MuellerSeb; fixed in gh-13273.
