### ISSUE TITLE
Generate binomial CDF with mu instead of prob

### ISSUE THREAD

**Issue by afogarty85** [scipy/scipy#13287]
**Is your feature request related to a problem? Please describe.**

The feature is related to a problem where I am unclear as to how to translate my data into parameters: `n` and `p` for `nbinom.cdf`. I am sort of lost translating R to Python here given different params:

```
test_arr = np.array([(1, 1, 3, 1, 1, 0, 0, 2, 2, 0, 1, 3, 0, 0, 0, 0, 3, 2, 1, 5, 2, 2,
           4, 0, 7, 3, 0, 0, 2, 1, 2, 0, 1, 4, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
           0, 0, 0, 0, 0, 2, 0, 3, 3, 1, 3, 0, 0, 2, 0, 3, 1, 0, 0, 0, 0, 1,
           0, 4, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 1, 2, 0, 0, 3, 2, 2, 0, 3,
           0, 1, 0, 1, 0, 0, 0, 2, 1, 0, 1, 0)])
nbinom.cdf(test_arr, n=?, p=?)  # how determine n and p from the data?
```

**Describe the solution you'd like**

When using R, I can obtain `nbinom.cdf` seemingly from the data itself
```
library(pscl)
arr1 <- c(1, 1, 3, 1, 1, 0, 0, 2, 2, 0, 1, 3, 0, 0, 0, 0, 3, 2, 1, 5, 2, 2,
           4, 0, 7, 3, 0, 0, 2, 1, 2, 0, 1, 4, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
           0, 0, 0, 0, 0, 2, 0, 3, 3, 1, 3, 0, 0, 2, 0, 3, 1, 0, 0, 0, 0, 1,
           0, 4, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 1, 2, 0, 0, 3, 2, 2, 0, 3,
           0, 1, 0, 1, 0, 0, 0, 2, 1, 0, 1, 0)
m1 <- zeroinfl(arr1 ~ 1, dist='negbin')
m1$theta  # dispersion param

library(VGAM)
# size is dispersion parameter
pnbinom(arr1, size=m1$theta, mu=mean(arr1))
```

It would be nice to derive the CDF of a value/vector by specifying the dispersion parameter and the mean.

**Describe alternatives you've considered**
 N/A

**Additional context (e.g. screenshots)**
 N/A

**Comment by josef-pkt** [comment]
statsmodels is supposed to have some functions to convert from GLM/Regression parameterization of negbin to the standard negbin.

scipy avoids duplicating distributions with just changes in parameterization

**Comment by afogarty85** [comment]
Wow thanks again for all your time and help. Are you able to help me better understand how I can determine `n` and `p`, if say, my data was the numpy array: `test_arr `?

**Comment by josef-pkt** [comment]
you can look at the code of NegativeBinomialP at predict and convert_params methods, for appropriate version of "P"

I don't find convert_params for NegativeBinomial right now, but old issue and recipe is in
https://github.com/statsmodels/statsmodels/issues/106#issuecomment-43961704

**Comment by mdhaber** [comment]
@afogarty85 When you have figured this out, would you let us know what we should add to the documentation to help others? Just recently I noticed a similar question in gh-11465.

**Comment by afogarty85** [comment]
Thanks all, this has been super helpful, particularly this: https://github.com/statsmodels/statsmodels/issues/106#issuecomment-43961704.

In terms of documentation, perhaps it might be helpful to add @josef-pkt's work showing how we can estimate `n` and `p` if we already have collected some data and then we want to proceed to other methods like the CDF.

```
from scipy.stats import nbinom
import statsmodels.api as sm
import numpy as np

nbinom_rv = nbinom.rvs(n=1.089, p=0.514, size=10000)
intercept = np.ones(len(nbinom_rv))
res = sm.NegativeBinomial(nbinom_rv, intercept, loglike_method='nb2').fit();
mu = np.exp(res.params[0])
alpha = res.params[1]
res.params

# find size and prob
Q = 0  # nb2, cited most common
size = 1. / alpha * mu ** Q
prob = size / (size + mu)
print('estimated params:', 'size:', round(size, 4), 'prob:', round(prob, 4))
cdf_out = nbinom.cdf(nbinom_rv, n=size, p=prob)
np.allclose(nbinom_rv, nbinom.ppf(cdf_out, size, prob))
```

**Comment by mdhaber** [comment]
@afogarty Looking more closely, part of your question is about fitting the distribution to data. That is a feature SciPy doesn't have for discrete distributions, but it has already been requested in gh-11948. In the meantime, you have statsmodels and, if you're interested, a [recipe](https://github.com/scipy/scipy/issues/11948#issuecomment-742964862) in gh-11948. 

The other part is about parameterization in terms of mu. Would gh-13292 address that and close this PR?

**Comment by josef-pkt** [comment]
As an aside to statsmodels:
The models have now `get_distribution` methods that create frozen scipy distributions from the parameterization in the regression models using the appropriate parameter conversion functions.

Another example is the Beta distribution where the regression model also has a mean-dispersion parameterization that needs to be converted to the standard parameterization in scipy.
