### ISSUE TITLE
Wrong results with hypergeom cdf

### ISSUE THREAD

**Issue by ricardoV94** [scipy/scipy#13280]
The hypergeometric cdf gives wrong results with invalid parameters

#### Reproducing code example:

```python
import numpy as np 
import scipy.stats as st 

print(st.hypergeom(M=3, n=3, N=4).pmf(np.arange(5))) 
print(st.hypergeom(M=3, n=3, N=4).cdf(np.arange(5)))                    
```

```python
[nan nan nan nan nan]
[nan nan nan  1.  1.]
```

#### Scipy/Numpy/Python version information:
```
scipy = 1.5.4
numpy = 1.19.4
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
@ricardoV94, thanks for reporting the issue.  I see that `nhypergeom` has the same problem:
```
In [32]: from scipy.stats import nhypergeom

In [33]: k = np.arange(-2, 6)

In [34]: nhypergeom.cdf(k, 5, 2, 8)
Out[34]: array([nan, nan, nan, nan,  1.,  1.,  1.,  1.])
```

Neither of these distributions implement the `_cdf` method, so the problem is probably in the parent class, `rv_discrete`.

**Comment by tirthasheshpatel** [comment]
@WarrenWeckesser Is it normal to get upper bound less than the lower bound when `_get_support` is called?

```python
>>> hypergeom._get_support(5, 3, 4)
(2, 3)
>>> hypergeom._get_support(4, 3, 4)
(3, 3)
>>> hypergeom._get_support(3, 3, 4)
(4, 3)
>>> hypergeom._get_support(2, 3, 4)
(5, 3)
>>> hypergeom._get_support(1, 3, 4)
(6, 3)
```

**Comment by WarrenWeckesser** [comment]
@tirthasheshpatel, that doesn't look right.  The same problem occurs with the public method `support`:
```
n [2]: hypergeom.support(1, 3, 4)
Out[2]: (6, 3)
```
I suspect a call to `_argcheck` needs to be incorporated into the `support` method of the `rv_generic` class.

**Comment by tirthasheshpatel** [comment]
Should this be done is a seperate PR or in gh-13283?

**Comment by WarrenWeckesser** [comment]
I think a separate PR would be better.
