### ISSUE TITLE
description correction in scipy.stats.t

### ISSUE THREAD

**Issue by smurfit89** [scipy/scipy#13285]
Good afternoon  dear developer community.

In https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.t.html

in the Example section is written that "Calculate a few first moments:".
I think a sentence like "We create the first four moments: " is more precisely.
I state it because I would read that four means would be created rather than 

1. mean
2. variance
3. skewness
4. kurtosis

I have added the screenshot below:

![grafik](https://user-images.githubusercontent.com/76477137/102882111-2db66c80-444e-11eb-9293-00dc547a3dda.png)

Thank you very much

**Comment by mdhaber** [comment]
Thanks for reporting this @smurfit89. Please see gh-13286 and let me know there whether it addresses the concern.

**Comment by smurfit89** [comment]
@mdhaber Thanks for fixing it, I will close the issue
