### ISSUE TITLE
Add a single individual to a latinhypercube initial population in differential_evolution

### ISSUE THREAD

**Issue by MaxGhenis** [scipy/scipy#13300]
**Is your feature request related to a problem? Please describe.**
I'd like to pass a single individual to `differential_evolution`, where it still starts with a `latinhypercube`, but adds the individual. Currently `init=array` requires an array of size `(M, len(x))` where `M>=4`. This seems also to skip the `latinhypercube`, and I have only a single individual.

Context is that this individual is the optimal solution from a related optimization. I don't want the search space constrained, but I want this related optimum to be part of the population.

**Describe the solution you'd like**
New arg that defines additional individual(s) to add to the population, while still respecting the `init` arg and allowing fewer than 4 individuals.

**Comment by andyfaff** [comment]
I've thought about this kind of thing before. What can happen is that the solve process spends a lot of time converging around the supplied `x0` to start with, unless `x0` is a really bad solution. If `x0` is a pretty good global solution then it's not clear to me that `differential_evolution` will necessarily improve on that. Moreover one wouldn't want to use any `best*` strategies.

**Comment by MaxGhenis** [comment]
Thank you, @andyfaff!
