### ISSUE TITLE
Extending with Pythran - next steps

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#13308]
After the 1.6.x branch we merged gh-8306, which adds Pythran as an optional build dependency. This should get us some more experience with how much of an improvement over Cython this is, and if there are any pain points or showstoppers to keep Pythran as a build-time dependency for the next release.

Things that are necessary before the next release (from https://github.com/scipy/scipy/pull/8306#issuecomment-751397248):

- [ ] We don't have PyPy and AIX CI, so that isn't tested yet - ensure that all works fine. PyPy in particular.
- [x] CI is using `clang-cl` on Windows - figure out what that means for wheel and conda builds, and other packaging.
- [x] Pythran is packaged for `conda-forge` but not `defaults`, so that may give some delays for introducing the next release (we need to give the Anaconda team a heads up, at the latest around the 1.7.x branch point)
- [x] check SIMD instructions included by default, and see if we can use more of them for improved performance. need to ensure it's SSE3 in wheels I believe.
- [ ] Also document how to enable all SIMD instructions detected for local builds.
- [x] Update the build instructions and release notes once we decide to keep Pythran enabled for 1.7.0
- [x] Update the `scipy-wheels` repo

Pythran usage related to convince ourselves that it's a good addition, and preferable to Cython in some circumstances:

- [x] try on a more complex Cython extension, such as `ndimage/_ni_label.pyx` (which uses fused types)
- [x] try on suitable pure Python code (e.g. `integrate.quad_vec`, `stats.ks_2samp`)
- [x] add a good set of benchmarks
- [x] try the Pythran OpenMP support as well - we won't want that in binaries, but for people who want optimal performance and are happy to build from source, getting it for free may be useful.
- [x] ~Update the way `PythranExtension` is used in `signal/setup.py` after updates in Pythran itself. see gh-8306 for discussion.~ EDIT: this was about needing to use full paths (e.g., `sources=["scipy/signal/_max_len_seq_inner.py"]`) because `PythranExtension` doesn't handle subpackages. I don't care that much though, if we plan to get rid of distutils anyway, why bother putting work into this.

Cc @serge-sans-paille

**Comment by ilayn** [comment]
I think Cython wrappers for BLAS/LAPACK routines is another point that I don't see how Pythran can be used right away.

**Comment by rgommers** [comment]
@ilayn I'm not sure that's relevant. If you mean generating wrappers, our `cython_blas/linalg` modules are complete and I wouldn't touch them. 

If you mean using Pythran with BLAS, then Pythran can build directly against BLAS, so that's probaby easier than trying to reuse the function pointers exposed in `cython_blas`. If that's done, we just need to ensure the build flags get passed correctly, so Pythran picks up the same BLAS as the one we find via `numpy.distutils`. That said, functionality needing direct access to BLAS routines aren't good candidates early on probably, because it's extra build config work that may be a little painful.

**Comment by ilayn** [comment]
Yes I meant not to recycle the cython pointers but if someone sets out to write Pythran compiled code which uses BLAS/LAPACK code I am not sure what the mechanism is. If it exists then nevermind it can wait.

**Comment by rgommers** [comment]
Yes it exists. Maybe it's even easy through `cython_blas`: https://pythran.readthedocs.io/en/latest/examples/Third%20Party%20Libraries.html#With-Cython

**Comment by Kai-Striega** [comment]
I'd be willing to help with this but don't have much (any) experience with pythran besides looking at the existing PRs do you have any suggestions for where to look to get up to speed with pythran and all this?

**Comment by serge-sans-paille** [comment]
@Kai-Striega I think 
[ ] try on suitable pure Python code (e.g. integrate.quad_vec, stats.ks_2samp)

I had a quick dive in scipy's source code and it seems to me `scipy/stats/_wilcoxon_data.py` would be a good start for python -> pythran conversion. You can probably give it a try

**Comment by Kai-Striega** [comment]
thanks @serge-sans-paille I'll take a look at it this week

**Comment by rgommers** [comment]
> check SIMD instructions included by default, and see if we can use more of them for improved performance. need to ensure it's SSE3 in wheels I believe. 

@peterbell10 checked that a nightly wheel runs without issues on an old CPU without AVX instructions: _I successfully ran the signal and optimize test without any issues. I also was able to confirm the wheel was using pythran:_
```
In [9]: scipy.__version__
Out[9]: '1.7.0.dev0+c4a1f02'
In [10]: scipy.signal._max_len_seq_inner.__pythran__
Out[10]: 
('0.9.9',
 '2021-04-12 14:10:58.968991',
 'ccd4c6b01dd37c8a698a8beaea85985732ea19d0ab7d0883d689f577fbda0424')
```

SIMD instructions can be enabled via `-DUSE_XSIMD` at build time, but there's no runtime dispatch so that'll only work for local builds. I haven't dug far enough to see what happens without `-DUSE_XSIMD`, probably no SIMD instructions are used at all. @serge-sans-paille I don't think we discussed this before - do you think we can enable SIMD instructions with the same baseline as numpy uses (up to SSE3), would that gain performance?

**Comment by rgommers** [comment]
I needed this figure, and thought it may be useful to share here and put in the docs later. tl;dr we now have 9 build dependencies, with Pythran that becomes 10. That's not an issue; the one annoyance is that on Windows there's a preference/need for using `clang.cl.exe` right now - wheel builds work, but that's an extra install and constraint.

![SciPy_build dependency_graph_with_Pythran](https://user-images.githubusercontent.com/98330/116005843-098bb780-a609-11eb-884b-b183a119322a.png)

**Comment by andyfaff** [comment]
@rgommers, I know we discussed this before, but I'm not sure that I gave the full explanation for why I'm not 100% behind adding extra dependencies for scipy building.

I do some of my work on a cluster that isn't allowed access to the internet. Thus, to run Python programs I have to download, build, install Python from source. The same applies to all Python packages I'd like to use in my workflow. The entire dependency tree can get very unwieldy.

For example, when extra dependencies like Pythran are added this means that I have to then download, build, install several more packages: `ply, networkx, decorator, gast, six, numpy, beniget`, before I can build scipy. This increases the time taken to get my workflow going.

The root cause in my case is lack of access to internet, but it's fair to say that others might experience the same kind of issues.

**Comment by tylerjereddy** [comment]
> but it's fair to say that others might experience the same kind of issues.

Yes, I encounter this as well.

**Comment by mdhaber** [comment]
Not sure if this needs its own issue; might be a simple answer: I have environment variable `SCIPY_USE_PYTHRAN=0`, but when I try to run benchmarks I got an error involving `ResolvePackageNotFound: - pythran`. Is there a way to run benchmarks without Pythran?

**Comment by rgommers** [comment]
> Still, can I use `asv` directly? I don't think `python runtests.py --bench-compare master` is working.

I'll have a look, there's nothing special related to pythran there, it's just that `runtests.py` tries to build in a fresh virtualenv under the hood, so the dependency specification should take into account the env var.

> I do some of my work on a cluster that isn't allowed access to the internet. Thus, to run Python programs I have to download, build, install Python from source. The same applies to all Python packages I'd like to use in my workflow. The entire dependency tree can get very unwieldy.

Interesting (or, painful) use case. I'm not sure I understand. If you can download and copy source code to the cluster, why can't you copy wheels or conda packages to it? Or is it a platform we don't provide packages for?

Cluster rules are usually a pain, but this surprises me. If you really are required to build everything from source, I'd expect there to also be a solution where you can install packages from within the cluster's network (which then provides scipy) or some HPC-specific build thing like Spack with a set of recipes. Building a full Python stack from scratch with no system at all other than "copy sources and good luck" seems like madness.

**Comment by mdhaber** [comment]
> I'll have a look, there's nothing special related to pythran there

No, that's not a pythran problem. I'll post a separate issue.

**Comment by andyfaff** [comment]
> If you can download and copy source code to the cluster, why can't you copy wheels or conda packages to it? Or is it a platform we don't provide packages for?

Installing packages means downloading them (source/wheels/packages) to my desktop and then using SFTP to transfer them to the cluster. There is no in/out bound apart from SFTP (e.g. curl from a terminal is not possible). All binaries have to be in your home directory, e.g. `~/bin`, with you then adding that to `PATH`. I've not tried copying wheels, it'll be a Linux wheel if anything. 

One key win would be to use a dependency resolver tool that would tell me *all* the packages needed for a given environment/install, and would then go out and retrieve the source tarball, or wheels, for a specific platform (or all platforms).

> Cluster rules are usually a pain, but this surprises me.

> Building a full Python stack from scratch with no system at all other than "copy sources and good luck" seems like madness.

Hmm, there's so much I could say here, but discretion wins out. Needless to say, I think it'll be quite a common situation.

**Comment by rgommers** [comment]
> I've not tried copying wheels, it'll be a Linux wheel if anything.

That's probably worth trying then. Nothing should change for you if you can use wheels or conda packages. That's the whole reason why we can be way more liberal with build dependencies vs. runtime dependencies - it's O(100-1000) people who should need the former, vs. O(10,000,000) who need the latter. We even have nightlies if you need something that's not in the latest release: https://anaconda.org/scipy-wheels-nightly/scipy/files. 


> One key win would be to use a dependency resolver tool that would tell me all the packages needed for a given environment/install, and would then go out and retrieve the source tarball, or wheels, for a specific platform (or all platforms).

You should be able to do this with Conda, or with Poetry as well if you must have wheels I think. E.g. try https://conda.github.io/conda-pack/ to move a complete environment at once.

I have only limited experience with clusters, but I did find using conda to install everything was a lot nicer than trying to interact with the (usually outdated) Python version installed by the admins.

**Comment by h-vetinari** [comment]
> Needless to say, I think it'll be quite a common situation.

I empathise with the constraints of your situation, but I disagree that this is anywhere near "common" (notwithstanding the fact that you'll probably personally know other people in this situation). I think there are other solutions still to try - like Ralf suggests - especially with conda (if your target architecture is one of x86/ppc/aarch64).

E.g. you could do (on a machine with linux & the same architecture as the cluster, doesn't have to be connected to the cluster):
```
# install miniconda
conda config --add channels conda-forge
conda create -n my_staging_env python=3.8 scipy [other dependencies]
conda activate my_staging_env
conda list --explicit > spec-file.txt
```
That `spec-file.txt` gives you a list of artefacts URLs to download (this then obviously from a machine that _can_ access the cluster). Put them in a folder, run `conda index .` (will probably need to install `conda-build` for that), and then move the whole thing to the cluster. Then you should be able to do [in the cluster]
```
# put conda binary in /bin
conda create -n my_hpc_env -c "<path/to/where/you/copied/the/folder>" [same list of specs as before]
conda activate my_hpc_env 
# off to the races...
```

There's probably ways to do this without installing an actual environment somewhere, but this should give you a starting point.

**Comment by tylerjereddy** [comment]
> Air-gapped clusters and environments in particular should have no problem in adopting.

`spack` + tarballs for all sources in the dependency graph is a common solution at US National labs at least; that said, we shouldn't pretend it is *no* work--the gains should be pretty substantial and my assumption here is that the folks advocating for pythran argue that they are

**Comment by czgdp1807** [comment]
Some benchmarking code and results are available at [here](https://github.com/Quansight-Labs/rbfi-benchmark). Please let me know your feedback. I will make updates as soon as possible. 

P.S. It seems like, `openmp` directives aren't mentioned in `_rbfinterp_pythran.py` file, so, `openmp` functionality might not be in use as of now. Let me know if I can add these directives. Thanks.

**Comment by rgommers** [comment]
> P.S. It seems like, `openmp` directives aren't mentioned in `_rbfinterp_pythran.py` file, so, `openmp` functionality might not be in use as of now. Let me know if I can add these directives. Thanks.

This is my mistake I think. In the todo list in the issue description I wrote _"try the Pythran OpenMP support as well - we won't want that in binaries, but for people who want optimal performance and are happy to build from source, getting it for free may be useful."_. What I seemed to remember when writing that was that Pythran would automagically parallelize things if you give it a `-fopenmp` flag. But I now see this isn't the case, from https://pythran.readthedocs.io/en/latest/MANUAL.html#adding-openmp-directives it's clear that this does require adding directives like:
```python
#omp parallel for reduction(+:r)
```
So my assumption that we could build binaries without OpenMP, but let individual users simply pass a flag to get OpenMP-enabled code, was wrong. Hence I think we should just ignore the Pythran OpenMP support, since adding specific directives that won't be used in any SciPy binaries doesn't seem worth the time.

Sorry for the noise!

**Comment by rgommers** [comment]
By the way, SciPy 1.7.0 has been out for 5 days and no one has reported a Pythran related build failure yet - that's a good sign:)

**Comment by czgdp1807** [comment]
> Sorry for the noise!

No problems. Though it is good on Pythran's part to not do parallelization of loops on its own. So, the next thing to do is to add the benchmarking code in scipy tutorial, right?

**Comment by rgommers** [comment]
> Some benchmarking code and results are available at [here](https://github.com/Quansight-Labs/rbfi-benchmark). Please let me know your feedback. I will make updates as soon as possible.

Thanks @czgdp1807! It looks good to me. Even though for this algorithm there's no speedup when using SIMD, that was expected as you explained, based on the algorithm having another bottleneck. 

It would be useful to add to the README how to obtain the with/without SIMD results. I believe it's simply adding `define_macros=[`-DUSE_XSIMD']` to `setup.py` or as an evironment variable? That worked as expected, which is good.

**Comment by rgommers** [comment]
> So, the next thing to do is to add the benchmarking code in scipy tutorial/docs?

I'd suggest that since it requires (re)building extensions, it belongs in the developer guide (https://scipy.github.io/devdocs/dev/index.html) rather than in the tutorials. Right now we have these section in the dev guide:

<img width="328" alt="image" src="https://user-images.githubusercontent.com/98330/123402750-5c053800-d5a8-11eb-9334-eda55070ed36.png">

How about adding a new section titled `SciPy Build and Performance Guide` right under `SciPy API Development Guide`? We can add this topic ("enabling SIMD for Pythran") there, as well as some other old or new topics (like the OpenMP question, which comes up regularly). Also that gives a place to add the Meson info soon, and things like how to do a debug build.

**Comment by rgommers** [comment]
AIX works once the next Pythran release (0.9.12) arrives, see gh-14289.

**Comment by h-vetinari** [comment]
This is milestoned in a closed milestone. I'm moving it to 1.9 for visibility, but there's no urgency at the moment AFAICT.

**Comment by rgommers** [comment]
Nice! I'd say on all arches. The main performance boost is coming from using C++ instead of Python for some functionality; SIMD is only a little extra performance on top, so should not make a difference for any such decisions.

**Comment by drew-parsons** [comment]
Great, I'll load up full pythran dependencies then. Should become available in Debian unstable over the course of the week.

**Comment by serge-sans-paille** [comment]
Thanks @drew-parsons for the packaging effort!

**Comment by tylerjereddy** [comment]
The checklist above suggests this issue is almost done, but I'll bump the milestone in the absence of a confident assertion that this can be closed. Branching is imminent (May 29th).

**Comment by rgommers** [comment]
I believe we can close this now. We have not had any reports of issues on PyPy, AIX or other more niche platforms, and the SIMD usage we leave to Pythran itself (it now vendors `xsimd`, and it doesn't matter much from SciPy's perspective).
