### ISSUE TITLE
friedmanchisquare p-value

### ISSUE THREAD

**Issue by jozsvar** [scipy/scipy#13307]
Hello, 

I have performed friedmanchisquare on my data and my p-value is 0.000e+00. Is there a minimum p-value border? 

Thanks, J

**Comment by mdhaber** [comment]
Hi @jozsvar, can you provide example code that reproduces the problem? If not, can you tell us anything about the data (any statistics, number of measurements, length of each measurement, etc...) and the value of the test statistic?

**Comment by jozsvar** [comment]
hi @mdhaber, thank you for your answer. 

I am attaching a tsv file with the ranks. 
About my data, I have 31 time points (0-30). 8 different conditions (each conditions contains at each time point contain multiple values) were measured at each time point. 
I am not sure what went wrong. 

Thanks for your help! 
J


[ranks_jo.tsv.zip](https://github.com/scipy/scipy/files/5756933/ranks_jo.tsv.zip)

**Comment by mdhaber** [comment]
Thanks very much! Can you send the code you're using to process it? If I can run it, then I see what is causing the problem.

**Comment by jozsvar** [comment]
Hello, 
Sorry for my late reply. 
I may have figured my problem out. I was inputing each time point as a measurement, however, I need to consider the conditions as measurement 1 (etc.). I want to evaluate the differences between each condition (with several timepoints). 

For this, I need to take the average for each group. I still get a very high significance but I get a number. 
Please let me know, if you find a mistake (or mis-thinking)

Thanks a lot for your help!

See code bellow: 
`rank_file = '/ranks_jo.tsv'
df = pd.read_csv(rank_file, sep='\t', encoding='utf8')

def get_means(df):
	'''creates a new file with means per condition per timepoint 
	'''
	ID = ['condition_1', 'condition_2', 'condition_3', 'condition_4', 'condition_5', 'condition_6', 'condition_7', 'condition_8']
	mean_list=[]
	

	for i in ID:
		data=df.loc[df['condition'] == i]
		#get mean of value_ranks for each condition
		mean = data.groupby('time_point')['values_ranks'].mean().reset_index()
		#insert the condition name
		mean.insert(0, 'condition', i)
		mean_list.append(mean)

	df1 = pd.concat(mean_list)
	
	friedman(df1, ID)

def friedman(df1, ID):
	'''Takes mean value ranks and calculates the Friedman's Test for repeated measurements
	'''
	# compare samples by conditions
	stat, p = friedmanchisquare(df1.loc[df1['condition'] == ID[0], 'values_ranks'], 
								df1.loc[df1['condition'] == ID[1], 'values_ranks'], 
								df1.loc[df1['condition'] == ID[2], 'values_ranks'], 
								df1.loc[df1['condition'] == ID[3], 'values_ranks'], 
								df1.loc[df1['condition'] == ID[4], 'values_ranks'], 
								df1.loc[df1['condition'] == ID[5], 'values_ranks'], 
								df1.loc[df1['condition'] == ID[6], 'values_ranks'], 
								df1.loc[df1['condition'] == ID[7], 'values_ranks'])

	print('Statistics=%.3f, p=%.3e' % (stat, p))

	#interpret
	alpha = 0.05
	if p > alpha:
		print('Same distributions (fail to reject H0)')
	else:
		print('Different distributions (reject H0)')

get_means(df)`

**Comment by mdhaber** [comment]
I tested your data using R:
```R
RoundingTimes <-
matrix(c(817.18181818,  611.54545455, 1059.58333333,  611.75      ,
        442.66666667,   74.375     ,  843.25      ,  475.08333333,
       1200.        ,  684.68181818, 1479.25      ,  743.91666667,
        572.5       ,   59.        , 1066.58333333,  245.        ,
       2335.86363636, 1382.86363636, 3008.75      , 1565.16666667,
       1742.5       ,  453.375     , 2081.5       ,  652.        ,
       2351.5       , 1420.27272727, 3026.58333333, 1592.5       ,
       1768.16666667,  467.0625    , 2105.25      ,  697.58333333,
       2383.77272727, 1442.22727273, 3081.33333333, 1662.83333333,
       1820.83333333,  516.25      , 2141.66666667,  719.08333333,
       2353.04545455, 1430.31818182, 3050.75      , 1696.58333333,
       1869.        ,  528.5       , 2159.75      ,  686.75      ,
       2426.5       , 1539.09090909, 3153.41666667, 1842.66666667,
       1887.16666667,  673.8125    , 2192.25      ,  764.25      ,
       2445.40909091, 1608.77272727, 3158.66666667, 1866.58333333,
       1904.        ,  633.375     , 2207.66666667,  793.16666667,
       2477.18181818, 1645.36363636, 3164.33333333, 1896.5       ,
       1912.5       ,  788.125     , 2227.16666667,  871.16666667,
       2500.04545455, 1666.13636364, 3166.75      , 1951.25      ,
       1914.16666667,  873.5       , 2253.58333333,  913.83333333,
       2532.22727273, 1721.81818182, 3172.08333333, 2006.58333333,
       1931.        ,  996.4375    , 2288.5       ,  974.41666667,
       2549.86363636, 1743.36363636, 3171.75      , 2018.83333333,
       1922.16666667, 1117.375     , 2289.25      , 1031.66666667,
       1118.81818182,  885.27272727, 1900.5       ,  840.91666667,
        827.83333333,   77.125     , 1415.41666667,  266.41666667,
       2580.59090909, 1784.63636364, 3202.66666667, 2078.08333333,
       1924.5       , 1095.        , 2325.        , 1044.91666667,
       2592.77272727, 1828.45454545, 3217.16666667, 2159.16666667,
       1926.        , 1294.6875    , 2338.08333333, 1096.        ,
       2601.04545455, 1851.31818182, 3209.66666667, 2175.33333333,
       1952.83333333, 1344.375     , 2375.16666667, 1123.5       ,
       2631.31818182, 1902.5       , 3217.83333333, 2190.5       ,
       1947.66666667, 1424.125     , 2388.91666667, 1146.5       ,
       2679.31818182, 1984.        , 3234.91666667, 2222.66666667,
       2038.        , 1610.0625    , 2458.83333333, 1248.91666667,
       2688.77272727, 2014.77272727, 3241.58333333, 2282.83333333,
       2034.83333333, 1615.1875    , 2463.        , 1280.33333333,
       2714.27272727, 2070.27272727, 3262.        , 2291.75      ,
       2151.83333333, 1860.125     , 2516.16666667, 1360.5       ,
       2728.81818182, 2138.04545455, 3309.25      , 2439.33333333,
       2091.16666667, 1870.875     , 2516.75      , 1378.91666667,
       2729.68181818, 2134.        , 3320.83333333, 2473.91666667,
       2097.5       , 1848.9375    , 2510.66666667, 1394.83333333,
       2739.72727273, 2170.31818182, 3320.08333333, 2494.5       ,
       2162.83333333, 1941.75      , 2602.16666667, 1516.41666667,
       1906.54545455,  981.5       , 2428.16666667,  981.66666667,
        989.16666667,   96.6875    , 1658.5       ,  322.75      ,
       2748.36363636, 2179.72727273, 3316.5       , 2464.08333333,
       2161.        , 1950.        , 2625.16666667, 1588.33333333,
       2063.86363636, 1066.13636364, 2671.08333333, 1063.58333333,
       1171.16666667,  168.        , 1799.41666667,  310.5       ,
       2163.18181818, 1152.09090909, 2842.5       , 1151.33333333,
       1327.5       ,  249.6875    , 1863.08333333,  459.75      ,
       2202.5       , 1200.09090909, 2917.91666667, 1280.58333333,
       1439.16666667,  301.4375    , 1919.91666667,  427.83333333,
       2269.31818182, 1248.95454545, 2963.16666667, 1357.83333333,
       1511.        ,  339.8125    , 1992.91666667,  466.33333333,
       2270.27272727, 1312.36363636, 2988.91666667, 1429.25      ,
       1603.        ,  353.        , 2015.08333333,  549.25      ,
       2302.        , 1333.54545455, 3001.5       , 1453.83333333,
       1698.16666667,  441.4375    , 2049.16666667,  594.75      ),
       nrow = 31,
       byrow = TRUE)
friedman.test(RoundingTimes)
```
at https://rdrr.io/r/stats/friedman.test.html.

It gets the same value of the test statistic, and it states that the p-value is less than 2.2e-16
![image](https://user-images.githubusercontent.com/6570539/104510751-81752b00-55a0-11eb-8607-a5371ed7b849.png)

so I don't think there's a bug here. If I'm missing something, please reopen the issue. Thanks!
