### ISSUE TITLE
MAINT: pavement.py PYVER is outdated

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#13311]
It hasn't affected me so far, but since we've dropped Python `3.6` support I imagine this entry in `pavement.py` may need an update:

```python
# Default Python version  
PYVER="3.6" 
```

I suppose if I run into issues I can temporarily bump it pending a backport fix after the release.

**Comment by 1nF0rmed** [comment]
Hey, can I bump it and make a master considering we aren't supporting Python 3.6 anymore

**Comment by rgommers** [comment]
@tylerjereddy you can change it permanently to whatever is your default Python version. It doesn't really matter. We use very little of what's in `pavement.py`, we should just do whatever is easiest until we build _all_ release artifacts in the `scipy-wheels` CI and then get rid of `pavement.py` completely.
