### ISSUE TITLE
Large sparse matrices of big integers lose information

### ISSUE THREAD

**Issue by matteodellamico** [scipy/scipy#13329]
When I create a pretty large sparse matrix of big integers, somehow I get slightly different values stored in the matrix, even for values that should fit in an `uint64`. I suspect this is because there's a convertion from int to float and back to int somewhere.

#### Reproducing code example:

```python
import random

import numpy as np
import scipy.sparse

size = 100_000
m = n = 10_000
data = [random.randrange(2**64 - 1) for _ in range(size)]
row_ind = [i * m // size for i in range(size)]
col_ind = [i * size // m % n for i in range(size)]
assert len(set(zip(row_ind, col_ind))) == size
assert max(row_ind) < m
assert max(col_ind) < n

matrix = scipy.sparse.csr_matrix((data, (row_ind, col_ind)), dtype=np.uint64)

for i in range(size):
    v = matrix[row_ind[i], col_ind[i]]
    assert v == data[i], (i, data[i], v)
```

#### Error message:

```
AssertionError: (2, 18072150216881262918, 18072150216881262592)
```

#### Scipy/Numpy/Python version information:
```
1.4.1 1.18.3 sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
When you create your data like that, you will almost certainly have some repeated occurrences of (row, col) pairs, and when you create the sparse matrix, the values associated with the repeated coordinates will be added. This could result in an overflow of the 64 bit unsigned integers.

**Comment by matteodellamico** [comment]
Thanks Warren, I made a mistake in writing the code I needed to reproduce the bug. Now I'm making sure that the `(row, col)` pairs are all distinct (see the first assertion): I still get an error, where the number I get changes in the 3 least significant digits.

Apparently I _don't_ get an error when `data` is a numpy array rather than a list.

**Comment by WarrenWeckesser** [comment]
@matteodellamico, thanks for the update.  This looks like a bug.  Even though you specified `dtype=np.uint64`, an intermediate step converts the values in `data` to floating point.  That intermediate result is then cast back to `np.uint64`.  Sufficiently large values in `data` will be changed in the round trip through floating point.

For other devs, here is what is happening:

`csr_matrix` is a subclass of `_cs_matrix`, and in `_cs_matrix.__init__`, when the input is a tuple of the form `(data, ij)`, the argument is passed to `coo_matrix` without specifying the dtype.  In the `coo_matrix` code, `data` eventually gets passed to `np.array` without a dtype being specified.  In the code that shows the problem, `data` is a Python list of Python integers, with some values greater than or equal to `2**63` and some less than that. This is one of those cases where `np.array` surprisingly returns a floating point array, even though all the values can be represented as `uint64`.  A simple example is
```
In [30]: np.array([2**63, 1])                                                                                                        
Out[30]: array([9.22337204e+18, 1.00000000e+00])
```

> Apparently I don't get an error when data is a numpy array rather than a list.

In that case, `data` is already a NumPy array, so `np.array(data)` returns `data`.  This avoids the round trip through `np.float64`.

**Comment by tylerjereddy** [comment]
@matteodellamico  Has the original reproducer above been edited to correct for the unrelated problem?

**Comment by matteodellamico** [comment]
Yes, it has.
