### ISSUE TITLE
add scipy.stats.variation with an ddof parameter

### ISSUE THREAD

**Issue by smurfit89** [scipy/scipy#13341]
**Is your feature request related to a problem? Please describe.**
Good afternoon dear developer community,

in my opinion it would make sense to include a ddof parameter, to adjust the standard deviation of the inbuild numpy std, that supports the ddof statement.

The documentation states that it calculates the variation of coefficient in a biased case. 

![grafik](https://user-images.githubusercontent.com/76477137/103529782-8f32fe00-4e86-11eb-83cc-e9910e6c5451.png)

This is only true for sample statistics, for Normal distributed population statistics, the calculation procedure is correct and not biased. Therefore the documentation should be specified more precisely. 

**Describe the solution you'd like**

I would add the ddof parameter as an additional parameter with a default value of 0 to ensure compatibility. the user can adjust the values based it his/her needs.

proposed_variation(a, axis=0, nan_policy='propagate', **ddof=0**)
...
...

return a.std(axis,ddof=ddof) / a.mean(axis) # change the last line. Same needs to applied into mstats.variation as the only difference is not supporting masked values

**Describe alternatives you've considered**

Calculate the coefficient of variation by using the "handwritten" formula

import numpy as np
np.std(a,ddof=1)/np.mean(a) 

**Additional context (e.g. screenshots)**

![grafik](https://user-images.githubusercontent.com/76477137/103529496-12a01f80-4e86-11eb-8bc5-077110ee6af8.png)

Thank you very much for your efforts.

**Comment by tirthasheshpatel** [comment]
Thanks for submitting this, @smurfit89!

> This is only true for sample statistics, for Normal distributed population statistics, the calculation procedure is correct and not biased.

Can confirm this from the [Wikipedia page](https://en.wikipedia.org/wiki/Coefficient_of_variation):

> But this estimator, when applied to a small or moderately sized sample, tends to be too low: it is a biased estimator. For normally distributed data, an unbiased estimator[4] for a sample of size n is:

> ![image](https://user-images.githubusercontent.com/43181252/103540681-1fda0000-4ec0-11eb-9d73-4808fb4988b2.png)

But I don't think `ddof=1` is giving the correct results. According to the Wikipedia page, the unbiased value is calculated using the above formula. So, `np.std([1,2,3,4,5], ddof=1) / np.mean([1,2,3,4,5])` should give result equal to `(1 + 1/(4*5))*variation([1,2,3,4,5])` which is not the case.

```python
>>> from scipy.stats import variation
>>> from numpy import std, mean
>>> std([1,2,3,4,5], ddof=1) / mean([1,2,3,4,5])
0.5270462766947299
>>> (1 + 1/(4*5))*variation([1,2,3,4,5])
0.49497474683058335
```

Can you please confirm this? Am I doing something wrong here, @smurfit89?

**Comment by smurfit89** [comment]
@tirthasheshpatel Thats true, you are mathmatically correct.

I have found a source which also states same, it also states the Formula I have written is almost all seen.

https://slideplayer.com/slide/13458380/

**Comment by smurfit89** [comment]
@tirthasheshpatel After the break i have seen that in wikipedia is stated that

![grafik](https://user-images.githubusercontent.com/76477137/103550163-c7e3cf00-4ea8-11eb-93d2-61ac1a3d5971.png)

where s 

![grafik](https://user-images.githubusercontent.com/76477137/103550212-da5e0880-4ea8-11eb-8b16-d1ad7cff0895.png)

so we need still the ddof=1 in np.std here.

Seems to be more complicated than I have thought.

**Comment by tirthasheshpatel** [comment]
Oh, I see. You are right. Thanks for the clarification!

**Comment by smurfit89** [comment]
My second question is why we are computing the mean twice. Once the mean is needed to compute the standard deviation, second step we divide by the mean. Is it possible to get the mean value from numpy.std funtion, store it somewhere and use the stored value to divide by it?

**Comment by rkern** [comment]
No, there isn't. I wouldn't worry about it.

**Comment by rkern** [comment]
Note that the docstring is not saying that the calculated coefficient of variation is biased. Rather, it is just trying to say that it is using the `ddof=0` variant of standard deviation. It refers to this, not entirely correctly, as "the biased standard deviation". Note that `ddof=1` is not an unbiased estimate of standard deviation, either (it's just the square root of an unbiased estimate of the variance). This may partly explain why simply using `ddof=1` in the `variation` calculation doesn't yield an unbiased estimated of the coefficient of variation.

Nonetheless, passing in `ddof` would be a good change, as `ddof=1` seems to be an attested convention.
