### ISSUE TITLE
Documentation: in scipy.stats.johnsonsu, parameter `a` can be less than or equal to zero

### ISSUE THREAD

**Issue by robert-dodier** [scipy/scipy#13353]
The documentation for scipy.stats.johnsonsu (https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.johnsonsu.html) says that the parameter `a` must be greater than zero, but on looking at the formulas on the Wikipedia page (https://en.wikipedia.org/wiki/Johnson%27s_SU-distribution) and looking at the source code, it turns out that `a` can be less than or equal to zero. Values of `a` less than or equal to zero are allowed by the code, and don't cause run time errors.

The bug fix is just to change the documentation.

Inspired by this Stackoverflow question: https://stackoverflow.com/questions/65567759/why-doesnt-johnson-su-distribution-give-positive-skewness-in-scipy-stats/

**Comment by WarrenWeckesser** [comment]
The documentation say "for all x, a, b > 0, ...".  That could be interpreted as meaning x > 0 and a > 0, but that is not the intent.  I agree we should adjust the documentation to avoid that ambiguity.

**Comment by WarrenWeckesser** [comment]
[`johnsonsb`](http://scipy.github.io/devdocs/generated/scipy.stats.johnsonsb.html) has the same issue.  The documentation says "a, b > 0", but in fact, a < 0 is allowed.

**Comment by mdhaber** [comment]
I would have submitted a PR, but I'll leave this open, as it is indeed a good first issue. I'll have the email return to my inbox in case it hasn't been addressed by 1.7 release time.

**Comment by robert-dodier** [comment]
About restating the description, I wonder if there is or should be a convention for stating the ranges of variables and parameters. E.g. "For all x in R, all a in R, and all b in R such that b > 0, ...". I don't know how other functions in Scipy are described. I leave it to someone else to sort it out.
