### ISSUE TITLE
scipy.signal doesn't allow for user modules to be named `constants`

### ISSUE THREAD

**Issue by fpdotmonkey** [scipy/scipy#13350]
If you have a module named `constants` in your project, then if you try to use that module while at the same time using scipy.signal (and it seems any module that uses scipy.optimize), you'll get an exception.  It seems to be related to https://github.com/scipy/scipy/blame/master/scipy/optimize/_highs/cython/src/constants.pyx

#### Reproducing code example:

```sh
#!/bin/sh

# Don't run this in a place where you have an existing file named `constants.py`
echo "MY_IMPORTANT_CONSTANT = 1" > constants.py
python3 -c "from scipy import signal; import constants; print(constants.MY_IMPORTANT_CONSTANT)"
rm constants.py
```

#### Error message:

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
AttributeError: module 'scipy.optimize._highs.constants' has no attribute 'MY_IMPORTANT_CONSTANT'
```

#### Scipy/Numpy/Python version information:

```
1.6.0 1.19.4 sys.version_info(major=3, minor=9, micro=1, releaselevel='final', serial=0)
```

**Comment by smurfit89** [comment]
Does the error also occur if the 

import constants

is changed to 

import constants as "put_the_name_in"

?

**Comment by 153957** [comment]
We encountered the same issue. We resolved it by renaming our constants module to something else (which was fine, we did not like the name anyway), but it is an annoying bug.

**Comment by mckib2** [comment]
Looking into this now.  The `_highs.constants` module (as well as `_highs.highs_wrapper`) should almost certainly be private and hopefully not causing these sorts of issues

**Comment by WarrenWeckesser** [comment]
It looks like it is related to `_highs`.  In this example, I don't have a file named `constants.py`:
```
~$ python3 -c "import scipy.optimize; import constants; print(constants)"
<module 'scipy.optimize._highs.constants' from '/Users/warren/mc37allpip/lib/python3.7/site-packages/scipy-1.7.0.dev0+e38446e-py3.7-macosx-10.9-x86_64.egg/scipy/optimize/_highs/constants.cpython-37m-darwin.so'>
```

**Comment by fpdotmonkey** [comment]
> Does the error also occur if the
> 
> import constants
> 
> is changed to
> 
> import constants as "put_the_name_in"
> 
> ?

Yeah, same error

**Comment by warrickball** [comment]
I'm working on a GitLab-hosted project where the pipeline tests have just reported a similar error, although the tests passed locally on the same version of Python (3.9.1) and SciPy (1.6.0) but different OSes (Ubuntu vs Fedora 33). The relevant error message is:
````
self.glb[ifreq_ref] = 5e5*math.sqrt(constants.G*self.glb[imass]/self.glb[iradius]**3)/math.pi
E       AttributeError: module 'scipy.optimize._highs.constants' has no attribute 'G'
model.py:309: AttributeError
````
Our package has it's own `constants.py` module with some physical constants. The file in which the error occurs has `from scipy.spatial import Delaunay` and the file with the call has `from scipy.stats import truncnorm`.

**Comment by warrickball** [comment]
Based on #13377, I've worked around this for now by importing my `constants` module *before* any SciPy imports.

**Comment by mikemikezhu** [comment]
Also encountered same issue when importing the `constants` module
```
ImportError: cannot import name 'IMAGE_NET_DISPLAY_ROW' from 'scipy.optimize._highs.constants'
```
