### ISSUE TITLE
ENH|DOC: documentation and tests specify wrong inputs in interpolate.RectSphereBivariateSpline

### ISSUE THREAD

**Issue by Muthsera** [scipy/scipy#13359]
As already discussed in #11736, the function interpolate.RectSphereBivariateSpline should expect colatitudes `u` from an **open** interval `(0, pi)`.
Currently the docstring however specifies a **closed** interval `[0, pi]`. Input verification is also done for the closed interval.
The underlying Fortran code will indeed print an error message if the singularities at `0` or `pi` are included in the colatitudes.

Curiously the implemented tests so far don't test for these specific singularities either.

**Comment by Muthsera** [comment]
@AtsushiSakai @rgommers I will submit a pull request shortly.

**Comment by AtsushiSakai** [comment]
This should be closed by #13360
