### ISSUE TITLE
supported_dtypes np.half/float16

### ISSUE THREAD

**Issue by telemmaite** [scipy/scipy#13352]
Is there any reason why np.half/float16 is not in the `supported_dtypes` -> https://github.com/scipy/scipy/blob/5f4c4d802e5a56708d86909af6e5685cd95e6e66/scipy/sparse/sputils.py#L13

it gets upcasted to float32 every time when convert my dok_matrix to csr, which in my case of 10000x10000 matrix is big difference in terms of memory?

**Comment by zyberg2091** [comment]
I had the same problem and when i checked last time then another similar issue https://github.com/scipy/scipy/issues/2111 was addressed before. however i am providing a PR if maintainers feel to add this.

**Comment by ilayn** [comment]
most of the underlying Fortran libs don't support half precision. Hence there is little to be gained for allowing it since at some point they will be upcasted anyways.

**Comment by zyberg2091** [comment]
with reference to this issue , similar issues have been raised before https://github.com/scipy/scipy/issues/2111. 

considering the time factor it may been neglected in scipy community.

Look at this https://stackoverflow.com/questions/24587433/why-does-numpy-float16-break-the-openblas-atlas-functionalities fir the the reason of avoiding half precision.

I was able to reproduce this again

**Comment by telemmaite** [comment]
Thank you for the explanation and info on the topic. I guess my only chance is to find a workaround and go on with float32 and higher unnecessary memory consumption. I am storing distances between points on a mercator map, so I would never go past 65504.0
