### ISSUE TITLE
numpy 1.19.3 in pyproject.toml not compatible with macOS 11

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#13363]
We added Python 3.9 support to `pyproject.toml` in commit 9228984a7 for 1.6.0. That commit required numpy 1.19.3, which is the first version to support Python 3.9. However macOS 11 is not yet supported by that release, hence we need to bump the minimum numpy version for macOS >= 11.

See the `sys_platform` and `platform_version` in [PEP 509](https://www.python.org/dev/peps/pep-0508/) for how to specify this. 

It looks like numpy 1.20.0 (not yet released) will be the first version with macOS 11 compatible wheels (but double check this). When addressing this issue, both the SciPy `pyproject.toml` and the one in https://github.com/scipy/oldest-supported-numpy should be updated.

Cc @dplepage who reported this issue.

**Comment by rgommers** [comment]
I looked into this, and I don't quite understand yet what's going on - there's multiple recent macOS 11 issues open. See gh-13102 in particular. NumPy `1.19.3` should be the correct version in `pyproject.toml` but depending on `pip` version and maybe something else the wheel ABI tags don't get recognized. So not yet clear that any change to `pyproject.toml` is needed.

**Comment by charris** [comment]
Ah, I see a possible problem, ISTR we may need to manually rename the mac files to `11_0` before uploading. @mattip Do you recall the details of that?

**Comment by charris** [comment]
Update: the fix was to use pip 20.3, see https://github.com/numpy/numpy/issues/17807. I don't know if that is related.

**Comment by rgommers** [comment]
> Update: the fix was to use pip 20.3, see [numpy/numpy#17807](https://github.com/numpy/numpy/issues/17807). I don't know if that is related.

Indeed, I think that fix (tell users to upgrade `pip`) is fine. Happy with not uploading new wheels with manually renamed ABI tags.

**Comment by rgommers** [comment]
Added a release note about the minimum required pip version in gh-13518. Nothing else to do, so closing.
