### ISSUE TITLE
HiddenImport: No module named scipy.spatial.transform._rotation_groups when building with pyinstaller

### ISSUE THREAD

**Issue by leosh64** [scipy/scipy#13378]
After upgrading to the latest `scipy` version, a binary built with `pyinstaller` fails to run due to a hidden import:

<!-- #### Reproducing code example:

If you place your code between the triple backticks below, 
it will be rendered as a code block. 

```
Sample code to reproduce the problem
```-->

#### Error message:
<!-- If any, paste the *full* error message inside a code block
as above (starting from line Traceback)
-->

```
Traceback (most recent call last):
  File "myscript.py", line 23, in <module>
...
  File "scipy/spatial/__init__.py", line 107, in <module>
  File "/home/user/work/.venv/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "scipy/spatial/transform/__init__.py", line 19, in <module>
  File "rotation.pyx", line 5, in init scipy.spatial.transform.rotation
ModuleNotFoundError: No module named 'scipy.spatial.transform._rotation_groups'
```

#### Scipy/Numpy/Python version information:
```
Python 3.8.5
scipy==1.6.0
numpy==1.19.5
pyinstaller==4.1
```

#### Workaround:
The module can be given to `pyinstaller` as hidden-import:
```
pyinstaller myscript.py \
    --hidden-import scipy.spatial.transform._rotation_groups
```
However, it would be better if it doesn't need to be specified manually.

**Comment by AtsushiSakai** [comment]
Might be related that the "spatial.transform.rotation" was cythonized in #12286

**Comment by andyfaff** [comment]
This isn't a scipy issue, the scipy pyinstaller hook probably needs updating (that's an issue for pyinstaller).

If, however, the some part of the codebase is not importable when it should be, then please let us know.

**Comment by andyfaff** [comment]
I understand that pyinstaller recommends package maintainers create a [hooks entry point](https://pyinstaller.readthedocs.io/en/stable/hooks.html#provide-hooks-with-package) in setup.cfg. Whilst this is a nice idea it also places a maintenance burden on the scipy project for a third party package. We would have to add additional checking to continuous integration to make sure the hooks were up to date, and then troubleshoot third party codebases when the hooks stopped working.

**Comment by zapaishchykova** [comment]
I had this problem when installing open3d with pip.
Resolved by:`
conda install -c open3d-admin open3d`
