### ISSUE TITLE
spearmanr throws indexError when a row contains all nan values

### ISSUE THREAD

**Issue by kkawabat** [scipy/scipy#13391]
When I run scipy.stats.spearmanr() with an array with a row containing all nans it throws an indexError exception

```
import scipy.stats
import numpy as np
a = np.array([[1,float('nan'),5],[2,float('nan'),3],[2,float('nan'),4]]).transpose()
scipy.stats.spearmanr(a, axis=1)
```

Traceback (most recent call last):
  File "/snap/pycharm-community/220/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/kan/PycharmProjects/analytics_engine/venv/lib/python3.7/site-packages/scipy/stats/stats.py", line 4233, in spearmanr
    rs[variable_has_nan, :] = np.nan
IndexError: index 3 is out of bounds for axis 0 with size 3

I expect that it would propagate the `nan` values into it's output's correlation matrix since by default `nan_policy='propagate'`

**Comment by mdhaber** [comment]
What version of SciPy are you using? This appears to be fixed in master.

**Comment by mdhaber** [comment]
I can confirm the error in SciPy 1.2, so I assume this is a bug in older versions. There is no error in SciPy 1.6 for me, so I suggest updating. I'll go ahead and close, but please reopen if I've missed something!

**Comment by mdhaber** [comment]
Looks like this was fixed in gh-12458.

**Comment by mdhaber** [comment]
This was indeed fixed for `spearmanr` and still fixed by the proposed `spearmanrho`.

```python3
from scipy import stats
import numpy as np
a = np.array([[1, np.nan, 5],
              [2, np.nan, 3],
              [2, np.nan, 4]]).T
ref = stats.spearmanr(a, axis=1)
res = stats.spearmanrho(a[:, np.newaxis], a[np.newaxis, :], axis=-1)
res.statistic
# array([[ 1.       ,        nan, -0.8660254],
#        [       nan,        nan,        nan],
#        [-0.8660254,        nan,  1.       ]])
np.testing.assert_allclose(res.statistic, ref.statistic)
```
