### ISSUE TITLE
ENH: Faster Max Flow algorithm in scipy.sparse.csgraph

### ISSUE THREAD

**Issue by touqir14** [scipy/scipy#13402]
The ```scipy.sparse.csgraph.maximum_flow``` uses Edmonds–Karp algorithm for computing the maximum flow of a graph. There exists [Orlin's algorithm](http://users.eecs.northwestern.edu/~haizhou/457/O(nm)MaxFlow.pdf) which is much faster and probably the fastest algorithm for sparse graphs. Has anyone looked into this? Will a PR be welcome?

**Comment by touqir14** [comment]
I also like the simplicity of Edmonds-Karp algorithm and I agree that the code for a complicated algorithm will be harder to maintain. The performance of scipy's max flow from what your benchmarks show are quite impressive indeed! While I don't have any particular graph in mind, I am interested on sparse graphs in general. The graphs in the benchmarks however are mostly dense. 

Seeing that your implementation of Edmonds-Karp is significantly outperforming the implementations from graph-tool and Networkx, I am starting to think those implementations are not optimized enough. I haven't benchmarked Orlin's algorithm against Edmonds-Karp. I haven't found a python implementation of Orlin's algorithm which is also the other reason for opening this issue. 

I think it would be worthwhile benchmarking scipy's Edmonds-Karp against Orlin's algorithm. I can work on this but it might be a while before I can get back with the results.

**Comment by jjerphan** [comment]
Dinic's algorithm is apparently also used for this problem. There are reference implementations for this algorithm, at least in C++ for competitive programming. One should be able to bind such an implementation.

**Comment by touqir14** [comment]
This [repo](https://github.com/Zagrosss/maxflow) (MIT license) contains a bunch of max-flow implementations in C++. Interestingly few of them are significantly outperforming scipy's max flow implementation on @fuglede's benchmarks with the data provided in DIMACS format. As a result, I am currently creating a python module for an even comparison using data in scipy's sparse format.

**Comment by touqir14** [comment]
I have created a python module containing those implementations here : https://github.com/touqir14/MaxFlow . Below are some benchmarks comparing against scipy's maximum_flow algorithm on the same benchmark that @fuglede tested and showed scipy's implementation's superior performance in contrast to other libraries. Other than edmond-karp's algorithm, all other implementations significantly outperforms scipy's maximum_flow.

|Algorithm | Density: 0.1 | Density: 0.3 | Density: 0.5 | Density: 0.9 |
|----------|--------------|--------------|--------------|--------------|
|Scipy's maximum_flow| 0.0605s | 0.2305s | 0.5193s | 1.1952s |
|ahuja_orlin | 0.0178s | 0.0545s | 0.0897s| 0.1159s |
|dinic | 0.0188s | 0.0561s | 0.0946s | 0.1202s |
|edmonds_karp | 0.0909s | 0.8998s | 2.5775s | 3.9351s |
|push_relabel_fifo | 0.0186s | 0.0559s | 0.0930s | 0.1214s |
|push_relabel_highest | 0.0179s | 0.0549s | 0.0931s | 0.1215s |
|parallel_AhujaOrlin_segment | 0.0181s | 0.0556s | 0.0896s | 0.1220s |
|parallel_push_relabel | 0.0188s | 0.0563s | 0.0942s | 0.1227s |
|parallel_push_relabel_segment | 0.0191s | 0.0572s | 0.0981s | 0.1319s |

**Comment by jjerphan** [comment]
Thanks for those benchmarks @touqir14!

**Comment by touqir14** [comment]
Based on the benchmarks, it might be fruitful to implement dinic's algorithm in scipy. Implementation wise, it is simpler than most of the other ones I benchmarked above. Any thoughts on this?

**Comment by jjerphan** [comment]
> Based on the benchmarks, it might be fruitful to implement dinic's algorithm in scipy. Implementation wise, it is simpler than most of the other ones I benchmarked above. Any thoughts on this?

From a user perspective, having other algorithms in `scipy.sparse.csgraph` (like Dinic's and a few others) is interesting. I don't know whether core contributors and maintain would be integrating those in, especially given that some algorithms for Max-Flow are already available in other libraries like [in networkx](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.flow.maximum_flow.html).

I guess you can ask [the SciPy-dev mailing list](https://www.scipy.org/scipylib/mailing-lists.html) to get some feedback. 🙂

**Comment by fuglede** [comment]
Push-relabel is also really quite simple: see e.g. [the Python sample implementation on Wikipedia](https://en.wikipedia.org/wiki/Push%E2%80%93relabel_maximum_flow_algorithm#Sample_implementations). So complexity and maintenance-wise, this wouldn't put SciPy in a much worse spot. I'd check with the maintainers before spending too much time, though (cc @rgommers); trying the mailing list is also a good way to get input.

If the performance improvements would persist in a Cython port, I would personally think that having additional implementations would be fine (and can probably assist with porting/integrating/reviewing as necessary).

**Comment by touqir14** [comment]
The generic implementation of the push-relabel algorithm given in the wikipedia page is rather slow. I think if we decide to go with the push-relable approach, we are probably better off with the dynamic tree based implementation ([here](https://dl.acm.org/doi/10.1145/48014.61051)) which is pretty good in terms of practical and theoretical performance. Just not so good in terms of implementational simplicity.

If we desire better practical and theoretical performance along with reasonable simplicity, I think Dinic's algorithm is a better candidate. On the other hand, there are a bunch of push-relable variants and if the core scipy developers think it is worthwhile covering them, then the generic version will (probably) provide a good base which can then be extended to cover the more complicated versions.

I will send an email to the scipy dev mailing list.

**Comment by rgommers** [comment]
> If the performance improvements would persist in a Cython port, I would personally think that having additional implementations would be fine (and can probably assist with porting/integrating/reviewing as necessary).

I agree with this. @touqir14's benchmarks show a 3x to 10x improvement, which is really nice and definitely a good enough reason to add a second implementation.

> If we desire better practical and theoretical performance along with reasonable simplicity, I think Dinic's algorithm is a better candidate. On the other hand, there are a bunch of push-relable variants and if the core scipy developers think it is worthwhile covering them, then the generic version will (probably) provide a good base which can then be extended to cover the more complicated versions.

My feeling is a second algorithm is useful, it's unclear if adding other ones offers more than incremental gains. If there's particular use cases (e.g. for low density) where a third algorithm is significantly faster than Dinic's algorithm, then adding a third makes sense too. I would suggest judging it like that though, rather than adding all of them just because we can.

Regarding how to add them, a `method=` keyword to `maximum_flow` seems good and in line with how we do this in other modules.

> This [repo](https://github.com/Zagrosss/maxflow) (MIT license) contains a bunch of max-flow implementations in C++.

I noticed this says _"A C++17 compliant compiler is needed to build Maxflow"_. This is probably fine, but may run into some Windows-related hiccups depending on what C++17 features are used (see http://scipy.github.io/devdocs/toolchain.html#c-and-c-language-standards).

**Comment by touqir14** [comment]
That sounds good. A Cython port should preserve the performance improvements. The porting process will likely be lengthy. I am a bit preoccupied this month but I should be able to get back with the results sometime on April.

**Comment by czgdp1807** [comment]
Hi. It seems like the final consensus is for Dinic's algorithm. I am interested to work on this issue. Let me know if it works. Thanks.
cc @touqir14 @rgommers

**Comment by touqir14** [comment]
Hi @czgdp1807 , feel free to take on this since I am still quite busy with my work.

**Comment by czgdp1807** [comment]
This is resolved via #14358 .Should we close this?

**Comment by rgommers** [comment]
Yes we should, closing. Thanks everyone!
