### ISSUE TITLE
DOC: Add example as to how to use solve_ivp to solve complex matrix differential equations

### ISSUE THREAD

**Issue by TejasAvinashShetty** [scipy/scipy#13437]
**Is your feature request related to a problem? Please describe.**
No. 
The example given in the documentation does not make it easy to 
guess the way to use solve_ivp to solve complex matrix differential equations.

**Describe the solution you'd like**
Add a sufficiently  detailed example

**Describe alternatives you've considered**
[example ](https://www.dropbox.com/s/ip1fqko2f7xfs41/patol75_answer_pristine_only_matrix.ipynb?dl=0) based on [this answer](https://stackoverflow.com/a/65838993/7952027) to this [question](https://stackoverflow.com/q/65793457/7952027)

**Additional context (e.g. screenshots)**

**Comment by nitin-pandita** [comment]
i would like to work on it. Thanks

**Comment by j-bowhay** [comment]
@nitin-pandita it's great that you're interested in working on SciPy! There is already a PR adding this so it would be best to work on to work on one of the many other issues or even better consider reviewing #14103 so that we don't duplicate efforts

**Comment by nitin-pandita** [comment]
> @nitin-pandita it's great that you're interested in working on SciPy! There is already a PR adding this so it would be best to work on to work on one of the many other issues or even better consider reviewing #14103 so that we don't duplicate efforts

Sure @j-bowhay , i have made a comment on #14103 . Please assign this to me
