### ISSUE TITLE
Doc notes of scipy.stats.ks_2samp are potentially reversed

### ISSUE THREAD

**Issue by manuflores** [scipy/scipy#13449]
Hi, I've found that the `stats.ks_2samp()`  documentation notes section  states:

```
In the one-sided test, the alternative is that the empirical
cumulative distribution function F(x) of the data1 variable is "less"
or "greater" than the empirical cumulative distribution function G(x)
of the data2 variable, ``F(x)<=G(x)``, resp. ``F(x)>=G(x)``.
```
However, when running the function it has the opposite behavior. This is perhaps just a documentation error.

#### Reproducing code example:

In the code below I generate two gaussian distributions with different means,`data1` has a smaller mean than `data2`. 

```
data1 = np.random.normal(loc = 0, size = 100)
data2 = np.random.normal(loc = 5, size = 100)

# Should accept alternative hypothesis (data1 ECDF is less than data2's). 
ks_2samp(data1, data2, alternative ='less')
>>>Ks_2sampResult(statistic=0.0, pvalue=1.0)

# Should reject alternative hypothesis
ks_2samp(data1, data2, alternative = 'greater')
>>>Ks_2sampResult(statistic=0.98, pvalue=2.197716889733508e-55)
```

#### Scipy/Numpy/Python version information:

Scipy version 1.4.1
Numpy version 1.19.1
sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
In this example, the values in data 1 are less than the values in data 2, but this means that for any given x the CDF of the first distribution is _greater_ than the CDF of the second distribution. KSTest compares the CDFs. Does gh-13188 make this more clear? Here is a [direct link](https://25284-1460385-gh.circle-artifacts.com/0/html-scipyorg/generated/scipy.stats.kstest.html#scipy.stats.kstest) to what the new documentation for `kstest` would look like.

**Comment by josef-pkt** [comment]
I think this is the same as #11981

draw two cdf and check which one is larger in vertical axis


@mdhaber 
an additional sentencem something like
Suppose x1 ~ F and x2 ~ G. If F(x) > G(x) for all x, then x1 has smaller values.

**Comment by mdhaber** [comment]
Thanks @josef-pkt . Please see [suggested changes](https://github.com/scipy/scipy/pull/13188/files#r565769511) in gh-13188 based on your comment. If they look good to you, please commit them; if not, please adjust and commit. Otherwise, I think it's ready, so feel free to merge when CI is done!

**Comment by josef-pkt** [comment]
sounds good to me, "tend" is good, I didn't know how to phrase this without getting technical. (first order stochastic dominance )

I have never seen a commit suggestion in the github interface. What am I supposed to do there?

**Comment by mdhaber** [comment]
Since there are three that should go in one commit:
![image](https://user-images.githubusercontent.com/6570539/106095366-8da4d080-60e8-11eb-9289-72537dbfb537.png)

After adding all three to a batch, commit:
![image](https://user-images.githubusercontent.com/6570539/106095456-af05bc80-60e8-11eb-86e9-8dd9b926065a.png)

![image](https://user-images.githubusercontent.com/6570539/106095638-f8eea280-60e8-11eb-828e-8deb0cd3cfe5.png)

I went ahead and committed them. PTAL at gh-13188 and merge if you think it's ready. Thanks!

**Comment by manuflores** [comment]
Thank you for clearing the documentation, now it makes a lot more sense.
