### ISSUE TITLE
stl_vector.h raising issue when running differential_evolution from scipy.optimize

### ISSUE THREAD

**Issue by CCoudereau** [scipy/scipy#13453]
Hello,

I am running a python script on a server (CentOs 8) and run into the following issue when calling differential_evolution : 
```
/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = double; _Alloc = std::allocator<double>; std::vector<_Tp, _Alloc>::reference = double&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.

Aborted (core dumped)
```

I am not even sure I understand what is going wrong there..

Here is a part of my code, the last line is the one raising the issue : 
```# This function defines the model as a function of its hyper-parameters
def SRF_Model(params):
    #Defines the parameter of the model
    num_trees, max_depth, min_node_size, sample_size_pct, seed = params
    
    #Trains the model by fitting it to the train subsample
    model = RandomSurvivalForestModel(num_trees = int(num_trees))
    model = model.fit(X_train, T_train, E_train,
                      max_features = 'sqrt',
                      max_depth = int(max_depth),
                      min_node_size = int(min_node_size),
                      num_threads = -1,
                      weights = None,
                      sample_size_pct = sample_size_pct,
                      importance_mode = 'normalized_permutation',
                      seed = int(seed),
                      save_memory=True)
    
    #Returns the already fitted model object
    return model
    
#This function computes the C-index for the internal validation cohort
def Train_C_Index(params):
    #Calls the fitted model with hyper-parameters=params
    model = SRF_Model(params)
    
#Returns 1-concordance index, which later will be minimized
    return 1.0-concordance_index(model, X_train, T_train, E_train)

# This is the optimizer of the model
boundary = [(2, 500), (1,500), (1, 500), (0.0001, 1.0), (0, 100)]
opt = differential_evolution(Train_C_Index, bounds=boundary,seed=1)
```

The script runs on my personal computer perfectly even if it is very slow, though.

The server run on CentOs 8, I am using python 3.6.8, scipy 1.5.4.
The script is working fine on my MacOS big sur 11.1 using python 3.6.8 and scipy 1.5.4.

**Comment by andyfaff** [comment]
differential_evolution is pure python, so I'm pretty sure that this is not an issue with `differential_evolution`, but with your SRF_Model or Train_C_index functions.

**Comment by CCoudereau** [comment]
Hum.. I'll look into it.

I thought it was scipy related since I had added some print function to locate where the script was failing and the previous function were running fine. The script was failing when the last line was called.

**Comment by andyfaff** [comment]
differential_evolution has no C or Cython code, so is not responsible for allocating any memory. This either means that there is something wrong in numpy, or the libraries one of your functions calls. I think it'll be the latter.

**Comment by CCoudereau** [comment]
I think you are definitely right. I was looking into the wrong direction. Thank you for your answer.
