### ISSUE TITLE
About Cubic Spline Interpolation

### ISSUE THREAD

**Issue by Philosober** [scipy/scipy#13455]
From the textbook, there are three common boundary condition. Of these, the '  f''(x_0) = f''(x_n)=0  ' is called as the natural boundary condition. I guess the scipy.Interpolation.splrep() use this condition, but when I have other value about f''(x_0) and f''(x_n). How can I use this API ?

**Comment by ev-br** [comment]
splrep does not support clamped BC. You can use either CubicSpline or make_interp_spline, which both do.

**Comment by Philosober** [comment]
I find it, thanks
