### ISSUE TITLE
Unexpected behaviour of scipy.integrate.solve_ivp with RK45

### ISSUE THREAD

**Issue by fpradelli94** [scipy/scipy#13456]
Hi everyone,
I don't know if this is actually a bug or is the effect of a voluntary choice of the developers, but I choose to report this anyway because just in case. Moreover, it might be useful to other users wishing to use `solve_ivp()` for the same kind of problem.
I really hope you can answer my doubts. Thank you in advance! 

## Introduction to the issue
I'm playing a bit with numerical integration these days and I'm facing the super-classic problem of [heat equation](https://en.wikipedia.org/wiki/Heat_equation) in 2d:

![equation1](http://www.sciweavers.org/tex2img.php?eq=%5Cfrac%7B%5Cpartial%20u%7D%7B%5Cpartial%20t%7D%20%3D%20%5Cbeta%20%28%5Cfrac%7B%5Cpartial%5E2%20u%7D%7B%5Cpartial%5E2%20x%7D%20%2B%20%5Cfrac%7B%5Cpartial%5E2%20u%7D%7B%5Cpartial%5E2%20y%7D%29%20%2B%20g%28x%2C%20y%2C%20t%29&bc=White&fc=Black&im=png&fs=12&ff=arev&edit=0)

Even though it would be better to use an implicit method for this kind of problems, I wanted to use **RK45** to see how it worked. 
To test the accuracy of the solution found by `solve_ivp()` with `RK45` I've considered a **test case** where the exact solution is known (Lx x Ly represent the size of my domain):

![equation2](http://www.sciweavers.org/tex2img.php?eq=u%28x%2C%20y%2C%20t%29%20%3D%20%283t%20%2B%202%29%28x%20-%20L_x%29%28y%20-%20L_y%29&bc=White&fc=Black&im=png&fs=12&ff=arev&edit=0)

And then I compared the exact solution with the solution calculated with `solve_ivp()`, **getting insane errors** (see following sections). This really surprised me given the fact that RK45 should be precise to the fourth order, so the error for a linear solution should be zero.
Thus, I decided to inspect the problem a bit further (see below for a short description) and report what I found to you.

## Problem inspection
Inspecting the problem I discovered, indeed, that the problem arose from `solve_ivp()` itself and not from the Runge-Kutta method. To prove this I **implemented myself the RK45 method** in the exact same way is implemented in `solve_ivp()`, not implementing the part related to the step adaptation:
```
def my_rk4_solver(rhs, y0, t_eval):
    # implementation not reported for the sake of brevity (see at link [1] if interested)
```
And **tested it against solve_ivp()** in two cases: 

 - not specifying the time points integrate, letting the program auto-compute a proper time step (`t_eval = None`); 
 - and specifying it (`t_eval = t`).

See the code below to have an idea of what I did.
```
import scipy.integrate as spintegrate
t = np.arange(0, 1000, np.float128(0.25))
solution_my_solver= my_rk4_solver_butcher(heatEq2dLin.rhs,  # right hand side of the system defined at [2]
                                          u0_matrix.reshape((heatEq2dLin.linear_dimension,)),  # initial condition defined in [3]
                                          t) 
solution_auto = spintegrate.solve_ivp(heatEq2dLin.rhs,
                                      [t[0], t[-1]],
                                      u0_matrix.reshape(heatEq2dLin.linear_dimension),
                                      method="RK45")
solution_teval = spintegrate.solve_ivp(heatEq2dLin.rhs,
                                       [t[0], t[-1]],
                                       u0_matrix.reshape(heatEq2dLin.linear_dimension),
                                       method='RK45',
                                       t_eval=t)   
```
And I compared each solution at each time point with the known exact solution reported above. This is the error i get:
![image1](https://i.imgur.com/9tE8HjC.png)

As you can see, with my solver I get a low error (subplot(111)), while with `solve_ivp` I get insane errors (subplot(112) and (113)).

## Explanation I found
Why does this happen?
Well, for those who are experienced with the diffusion equation, you probably know that there is a **stability condition for explicit methods** like RK45, that forces the integration step in time (dt) to respect this condition:
![equation3](http://www.sciweavers.org/tex2img.php?eq=dt%20%5Cleq%20%5Cfrac%7Bdx%5E2%7D%7B4%5Cbeta%7D&bc=White&fc=Black&im=png&fs=12&ff=arev&edit=0) 
Where dx represent the discretization step in space (for both x and y). If that condition is not respected for each integration step, the numerical method will diverge and will not find the correct solution.

I expected the RK45 algorithm to be able (thanks to error estimation) to automatically evaluate a proper step that satisfies this condition, but this is definitely not the case. Indeed, the integration points **almost never respect the condition**.
To have a **visual proof** of this I generated a pie-chart that shows if the dt values computed by RK45 respect the condition: 
```
# compute dt at each step
dt_array_auto = np.diff(solution_auto.t)
# test if those satisfy the stability criterion
is_dt_stable = dt_array_auto <= heatEq2dLin.dt_stability  # heatEq2dLin.dt_stability == (dx**2)(4 * beta), see [4] for definition
# get percentages
p_true = np.array(np.sum(is_dt_stable) / len(is_dt_stable)) * 100
p_false = np.array(1 - p_true) * 100
# plot
plt.figure()
plt.pie([p_true, p_false],
        labels=[r"$ dt \leq \frac{dx^2}{4\beta}$", r"$ dt > \frac{dx^2}{4\beta} $"],
        autopct='%1.1f%%',
        startangle=45,
        explode=(0.1, 0.1))
plt.axis('equal')
plt.title("dt values grouped by stability criterion")
``` 
![image2](https://i.imgur.com/uUv9U0P.png)

This compromise the solution found by `solve_ivp` in **both of the tested cases**, namely, when `t_eval = None` and when `t_eval != None`. Indeed, inspecting the code I noticed that when `t_eval` is not `None` the program behaves exactly the same, computing the solution at the steps it consider appropriate. Then, it returns the solution at the `t_eval` points by interpolation.
In brief, the output of `solve_ivp` when `t_eval` in not `None` is treated as a dense output.

## Conclusion
As I said at the beginning I don't know it this is actually a bug, but still I don't understand this behaviour. More precisely, two are the things I don't understand 

1. Why RK45 is not able to auto-detect that the error is so big? Has this something to do with the very nature of the diffusion equation?
2. Why the use of `t_eval` does not force the solver to actually solve the equation at the time points? 

**Thank you so much if you reached the end of this report and I really hope you can answer me!**

## References
[1] ![Implementation of my solver (see method `my_rk4_solver_butcher`)](https://github.com/fpradelli94/private/blob/master/heatEq2d_testLinear_problem2and3.py)
[2] ![Implementation of the rhs (see method `rhs`)](https://github.com/fpradelli94/private/blob/master/heatEq2d_testLinear_setup.py)
[3] ![Initial condition (see method `evaluate_u0`)](https://github.com/fpradelli94/private/blob/master/heatEq2d_testLinear_setup.py)
[4] ![dt value that ensures stability (see `dt_stability`)](https://github.com/fpradelli94/private/blob/master/heatEq2d_testLinear_setup.py)

**Comment by laurent90git** [comment]
Hi,

Regarding your second question on `t_eval`, this option is only meant to choose the time points at which the solution.is exported. If you set `t_eval=None`, you will get all the time points the solver has taken. This option is not meant to force the solver into taking different steps than it would automatically choose. This is actually a common misconception (see Stackoverflow for some examples). The only thing you can do is:
1) play with `rtol` and `atol` (try `atol=rtol=10^-n` with `n` in [2,..,12] for example. This will ask for more precision, hence the solver will use lower time step. Note though that the default values are such that the problem should already be well resolved.

2) set the optional argument `max_step` so as the solver does not take time steps larger than this value.

Anyway the behaviour you mention seems rather awkward. I wonder if there's not an issue with the type conversions you operate in your ODE function. Also, I see that you impose your boundary conditions based on the analytical solution values at these points. What were the BCs used to actually generate this analytical solution ?

I will try to have a look in the next couple of days. On my side, I have never had issues with any kind of integrators to solve the heat equation.

**Comment by fpradelli94** [comment]
Dear laurent90git,
Thank you very much for dedicating your time to my issue.

Regarding `t_eval`, **thanks for clarifying!** I didn't understand well how to use this parameter and how to use the parameter `max_step`. As soon as I can I will try to solve the system setting the `max_step` to a value that forces the solver to respect the stability condition I mentioned above. I expect this to completely remove the error, but I'll let you know.

Regarding the other problem, I'm quite sure it's not a matter of type conversion. I had the same idea and I **tested if using different data types led to differences in the error I showed**. But, as you can see in the figure below, the problem remains using any data-type.

---
![image1](https://i.imgur.com/fNQ8TBJ.png)
**Brief hitchhikers guide to the figure above**: each subplot has a title in this form: dt = *value* | *data type 1* | auto/t_eval | y: *data type 2* | t: *data type 3*. 
 - dt is the dt value I was using in the simulation, not really important for what we're discussing here
 - *data type 1* is the data-type I used to represent the data I gave as input to `solve_ivp`. As you can see, in the six subplots on the right I tested `np.float32`, `np.float64`, and `np.float128`
 - *auto/t_eval* indicates if I was giving a `t_eval` vector as input (t_eval in the title) or not (auto in the title)
 - *data type 2* and *data type 3* refer to the actual data types of y and t returned by  `solve_ivp`. In every case was `np.float64`, except for the last two subplots on the right, where `solve_ivp` returned data in `np.float128` format.

---

Finally, regarding the BCs you mentioned, **there are no other BCs I used to generate the linear solution I presented above**. 
It is not a solution I obtained solving the heat equation for a real case. 
My purpose was to test `solve_ivp` from the beginning, thus I:
 - assumed the final solution to be the linear function u(x, y, t) I reported above;
 - derived the BCs and initial conditions based on this assumption;
 - and finally solved the system with `solve_ivp` to see wheter the analitical solution matched the numerical solution.

If you're interested in a slighly more detail explanation of this testing approched, It's explained [here](http://hplgit.github.io/Programming-for-Computations/pub/p4c/p4c-sphinx-Python/._pylight006.html#construction-of-a-test-problem-with-known-discrete-solution) (see the section "Construction of a test problem with known discrete solution").

Thank you again and all the best.

**Comment by fpradelli94** [comment]
Dear laurent90git,
I tried again to use RK45 to solve the heat equation 2d setting the parameter `max_step` to a value that respect the stability criterion presented in my first comment and indeed, as you suggested, **the error completely disappear**.

Also, after studying a bit further I think I understood the reason for the problem I experienced. **Its definitely not a bug of the code, it's just how RK45 in this particular case**. Thus, I decided to close this issue to not make anyone loose more time with that (sorry for bothering, I really couldn't understand what was happening before). Above I wrote a short explanation of what I think caused the issue, in case anyone is courious.

Thank you very much and all the best.


### Origin of issue
As I stated above the origin of the issue I experienced simply comes from how RK45 works for linear solution like mine. I report it below again:
![equation1](https://bit.ly/3rbrHae)
First of all, we have to premise that RK45 gives a numerical solution that is accurate to the **fourth order**[1], which means that the error of the numerical solution compared with the analytical solution is proportional to the fourth derivative of the analytical solution. In this case the fourth derivative of the analytical solution is zero, that's why I'd never expected to find such big errors.

However, RK45 is also method that is able to estimate the proper integration step for the given ODE system. This is because, conceptually, it behaves following this algorithm:
 - solve the system with a RK method fourth order accurate at the given step
 - solve the system a second time with a RK method fifth order accurate at the given step
 - compare the two numerical solution to have an estimation of the error
If the error is lower than a predetermined tolerance then the solution is considered correct; otherwise, it makes everything again with a **smaller step**.

This is where the issue comes. In this particular case the solution is linear, which means that both the error of the fourth order RK method and of the fifth order RK method **are zero for any given step**. Thus, the method will choose steps that seem appropriate from the comparison between the 4th and the 5th order solution, but are not because of the stability criterion mentioned in my first comment.

Thus, this solves the mistery, I guess. I hope any other more experienced user can confirm my reasoning, but I'm quite sure that this is the origin of the problem.

### References
[1] [Runge–Kutta–Fehlberg method - Wikipedia](https://en.wikipedia.org/wiki/Runge%E2%80%93Kutta%E2%80%93Fehlberg_method)
