### ISSUE TITLE
Scipy cosine distance can be greater than 2

### ISSUE THREAD

**Issue by dulietina** [scipy/scipy#13454]
I am using the cosine distance as implemented in scipy.spatial.distance and while (mathematically) the value should always be between 0 and 2 this is not practically the case: 
Namely, with v= [-3.0e-05 -2.4e-05  0.0e+00] and w=[3.5e-05 2.8e-05 0.0e+00]  the returned value is: 2.0000000000000004 

I am not surprised that this is computationally possible, but I am surprised that the mathematical properties of the function are not enforced as this will cause other functions not to work, hence the bug request. Or maybe it is a feature request? :)

versions: scipy 1.6.0, numpy 1.19.4, python 3.8.5

**Comment by rgommers** [comment]
Yes, we can just clamp the min/max values to ensure there's no exceeding the theoretical bounds.

**Comment by charlotte12l** [comment]
Hi, actually I can't reproduce the bug with scipy 1.6.0, numpy 1.19.4, python 3.8.5(the returned value is 2.0 using your example), but I think it would be better if we clamp the values to 0~2. I just made a pull request, thanks! https://github.com/scipy/scipy/pull/13685

**Comment by rgommers** [comment]
There's more discussion in https://github.com/scipy/scipy/issues/5208#issuecomment-138118172, which also points out that clamping may be a good idea. gh-5225 partially fixes the C implementation of `pdist(..., 'cosine')`, but doesn't touch the corresponding Python implementation of `cosine`. So clamping does look like the right fix.
