### ISSUE TITLE
Broken link in cramervonmises documentation

### ISSUE THREAD

**Issue by chrisb83** [scipy/scipy#13459]
The link to the Wikipedia entry of the CvM test (https://en.wikipedia.org/wiki/Cram%C3%A9r%E2%80%93von_Mises_criterion) is not displayed correctly, most likely due to the special character in the link:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.cramervonmises.html

**Comment by WarrenWeckesser** [comment]
@chrisb83, are you already working on a fix for this?  Would using the name with the escaped characters  (https://en.wikipedia.org/wiki/Cram%C3%A9r%E2%80%93von_Mises_criterion) in the docstring fix the issue?

**Comment by WarrenWeckesser** [comment]
Answering my own question: yes, using the name with the escaped characters worked (at least it did on my local machine). PR with fix: https://github.com/scipy/scipy/pull/13460
