### ISSUE TITLE
directed_hausdorff issue with shuffle

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#13468]
`TestHausdorff.test_symmetry` and a number of other `directed_hausdorff` tests triggered the check for unknown objects we just put into `RandomState.shuffle` (see [here](https://github.com/scipy/scipy/pull/13463/checks?check_run_id=1799089671)):
```
mtrand.pyx:4478: in numpy.random.mtrand.RandomState.shuffle
    ???
E   UserWarning: `x` isn't a recognized object; `shuffle` is not guaranteed to behave correctly.
E.g., non-numpy array/tensor objects with view semantics may contain duplicates after shuffling.
```

**Comment by rgommers** [comment]
Ah, @tylerjereddy commented at https://github.com/scipy/scipy/issues/13464#issuecomment-770321107 on it.

It's related to https://github.com/numpy/numpy/pull/18211

**Comment by rgommers** [comment]
The problematic code is:
```
    cdef long[:] resort1, resort2

    rng = np.random.RandomState(seed)
    resort1 = np.arange(N1)
    resort2 = np.arange(N2)
    rng.shuffle(resort1)
    rng.shuffle(resort2)
```
We should have special-cased memoryviews in the untyped path in `RandomState.shuffle`.

**Comment by rgommers** [comment]
Cython memoryviews also don't have to be contiguous though (see [docs](https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html)). I believe that the `shuffle` code is still buggy, and memoryviews should take the same path as `ndarray` rather than the "untyped path". @rkern do you agree?

**Comment by rkern** [comment]
Is the shuffle code for these `cdef long[:]` memoryviews actually buggy? Contiguity isn't really the issue so much as whether indexing has view semantics or copy semantics. I could definitely see `cdef long[:, :]` or higher dimensions having issues. Wouldn't we have seen bugs in `directed_hausdorff()` if the `cdef long[:]` case were actually buggy?

**Comment by tylerjereddy** [comment]
> Is the shuffle code for these cdef long[:] memoryviews actually buggy? 

No issues that I'm aware of

> Wouldn't we have seen bugs in directed_hausdorff() if the cdef long[:] case were actually buggy?

Probably yes. I'm happy to remove the typed memoryview as you suggest though, provided it has no detrimental effect on performance (the `asv` benchmarks for `directed_hausdorff` run pretty fast so easy to check).

**Comment by rkern** [comment]
I can confirm that 1D memoryviews like `cdef long[:]` don't seem to have a problem, but 2D ones do.

```python
%%cython

import numpy as np


def swaptest_1d():
    cdef long[:] x
    
    x = np.arange(10)
    x[0], x[1] = x[1], x[0]
    return np.asarray(x)


def swaptest_2d():
    cdef long[:, :] x
    
    x = np.arange(12).reshape([3, 4])
    x[0], x[1] = x[1], x[0]
    return np.asarray(x)

print(swaptest_1d())
print(swaptest_2d())
```

```
[1 0 2 3 4 5 6 7 8 9]
[[ 4  5  6  7]
 [ 4  5  6  7]
 [ 8  9 10 11]]
```

@rgommers Yes, we should have a path for (at least) 2+-D memoryviews. It looks like just viewing them with `np.asarray()` and passing those `ndarray` views through the rest of the code works fine.

**Comment by rgommers** [comment]
No, this code is not buggy, these are simple 1-D contriguous memoryviews. But it shows that memoryviews take the untyped path and that's still potentially buggy. So we can explicitly handle the memoryviews in numpy.
