### ISSUE TITLE
Add dense and sparse graph embedding functions

### ISSUE THREAD

**Issue by asaadeldin11** [scipy/scipy#13486]
I’d like to add graph embedding functionality to scipy, specifically adding [Adjacency](https://arxiv.org/pdf/1108.2228.pdf)/[Laplacian](https://arxiv.org/pdf/1607.08601.pdf) spectral embedding to scipy.sparse.csgraph (or anywhere else it would make sense to have it). Both methods are useful in a variety of graph applications, such as clustering nodes with similar connective structure; in essence, they both amount to an SVD. Unlike sk-learn's [SpectralEmbedding,](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.SpectralEmbedding.html) which is restricted to symmetric affinity matrices (thus losing the underlying asymmetries and potential directional clusters present in the adjacency matrix of a directed graph input), our proposed methods accept both symmetric and asymmetric matrices.

Our current implementations in [microsoft/graspologic,](https://microsoft.github.io/graspologic/tutorials/embedding/AdjacencySpectralEmbed.html) (available at [ASE](https://github.com/microsoft/graspologic/blob/dev/graspologic/embed/ase.py) and [LSE)](https://github.com/microsoft/graspologic/blob/dev/graspologic/embed/lse.py) input a graph represented as a dense or sparse array, and return the appropriate embedding.

**Comment by asaadeldin11** [comment]
@rgommers please see above

**Comment by rgommers** [comment]
Thanks @asaadeldin11. It sounds like interesting functionality. Despite the "graph" in the name, I'm not sure this fits in `sparse.csgraph` or not. The origin of `csgraph` is scikit-learn functionality be upstreamed, so there's a fuzzy boundary. This could conceivably also live next to `SpectralEmbedding` in scikit-learn, or be integrated with it. 

It looks to me like the functionality that `ASE` and `LSE` build on top of are what `csgraph` already offers (it uses NetworkX now, so needs a small rewrite). But `ASE` and `LSE` themselves are more like users of `csgraph` than that they fit directly into it?

Let's see if there are other opinions. Maybe @fuglede, @pmla?

**Comment by asaadeldin11** [comment]
> This could conceivably also live next to `SpectralEmbedding` in scikit-learn, or be integrated with it.

The `SpectralEmbedding` class in sk-learn builds the affinity matrix locally, but then is mostly calling scipy functions. For that reason, I think it would make more sense for `ASE` and `LSE` to be in scipy, and then perhaps `SpectralEmbedding` would call them. So I agree that this would eventually be integrated into `SpectralEmbedding`

> It looks to me like the functionality that `ASE` and `LSE` build on top of are what `csgraph` already offers (it uses NetworkX now, so needs a small rewrite). But `ASE` and `LSE` themselves are more like users of `csgraph` than that they fit directly into it?

That's fine with me. I think this would also fit well into `sparse.linalg`(and/or `linalg`).

**Comment by pmla** [comment]
IMO [sklearn.manifold](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.manifold) is a more suitable venue. The `manifold.spectral_embedding` function takes an adjacency matrix as input too, so there is perhaps scope for more embedding methods there.

**Comment by rgommers** [comment]
@rth @thomasjpfan @amueller would you be open to incorporating the proposed features in `sklearn.manifold`?

**Comment by thomasjpfan** [comment]
I see there is already an issue was already opened in https://github.com/scikit-learn/scikit-learn/issues/18177. Since this would be a major feature, I think the blocker would be maintainer time for reviewing.

In the meantime, I think it would be good to add `microsoft/graspologic` to https://scikit-learn.org/stable/related_projects.html .

**Comment by rgommers** [comment]
Thanks for the responses @thomasjpfan and @pmla. I think we're on the same page here. Scikit-learn would be more appropriate than SciPy, so I'll close this issue.

Thanks for asking @asaadeldin11.
