### ISSUE TITLE
One-word typo in the documentation of optimize.linprog_simplex

### ISSUE THREAD

**Issue by Naereen** [scipy/scipy#13494]
Hello there,
I just observed this typo
https://github.com/scipy/scipy/blob/232092afebf7a59949dca5595aaac3446814293c/scipy/optimize/_linprog_doc.py#L1105
tabluea-based => tableau-based
I've contributed to tiny tiny changes in scipy a few years ago, but I'm not sure what's the best things to do for such tiny typos: do you want me to submit a pull request?
Thanks in advance. -- @Naereen

**Comment by mdhaber** [comment]
Please do! I'll merge it right away.

**Comment by Naereen** [comment]
Thanks!
I know you guys are extra busy (the number of issues and PR here is quite scary), and I preferred to ask.
I also read all the documentation pages of `optimize.linprog` and various options/solvers, didn't find any other typo or things I could easily improve.

**Comment by Naereen** [comment]
(Oh boy, 16 checks for a one-word PR... It always bothers me to see so many CI builds triggered by tiny tiny pull requests, the ecological cost is non-negligible, but I guess there is no other solution...)

**Comment by Naereen** [comment]
> (Oh boy, 16 checks for a one-word PR... It always bothers me to see so many CI builds triggered by tiny tiny pull requests, the ecological cost is non-negligible, but I guess there is no other solution...)

Oh man thanks for your blazing-fast merging, I was having the same concern regarding CI computations ressources! https://github.com/scipy/scipy/pull/13495#issuecomment-771928237
