### ISSUE TITLE
DOC: error in description of "direc" parameter of "fmin_powell"

### ISSUE THREAD

**Issue by dwight200** [scipy/scipy#13511]
I think there is a small mistake in the otherwise useful documentation introduced in #9227.  Specifically the default is described as ``np.ones((N, N))`` but should be ``np.eye((N, N))``?

Current documentation:
```
   direc : ndarray, optional
          Initial fitting step and parameter order set as an (N, N) array, where N
          is the number of fitting parameters in `x0`. Defaults to step size 1.0
          fitting all parameters simultaneously (``np.ones((N, N))``). To
```

Source code (scipy/optimize/optimize.py:_minimize_powell):
```
      if direc is None:
         direc = eye(N, dtype=float)
```

**Comment by tupui** [comment]
Indeed, would you do a PR to fix this?
