### ISSUE TITLE
latest Version on RPi buster

### ISSUE THREAD

**Issue by Eefried** [scipy/scipy#13517]
The latest scipy version with Raspbian is 1.1.0-7?
How to get the latest for python 3?
many thanks

**Comment by rgommers** [comment]
I'm not sure what install method you used, but for Raspberry Pi I believe the architecture is `aarch64`, so you should be able to simply `pip install scipy` and get SciPy 1.6.0. We have `aarch64` wheels: https://pypi.org/project/scipy/1.6.0/#files

**Comment by Eefried** [comment]
I used all install methods I could find apt-get pip. , scipy python3-scipy...

**Comment by rgommers** [comment]
It could be that you have Raspbian for another architecture, or it's configured to not look at PyPI. I'm not sure, it's impossible to tell without more details.

**Comment by Eefried** [comment]
well, the installation pages on scipy already announces problems with **pip.**
https://www.scipy.org/install.html
how to resolve?

**Comment by rgommers** [comment]
> Raspberry Zero

You're going to have to figure out what hardware that is, I have no idea. If it's not `aarch64` architecture (modern 64-bit ARM), then there are no SciPy wheels (wheels are binary installers). If so, maybe someone has precompiled packages.

**Comment by andyfaff** [comment]
https://www.piwheels.org will probably be of use here.

**Comment by matthew-brett** [comment]
I think Raspbian is 32-bit - I guess that means the `aarch64` wheels won't match?

```
[ins] In [7]: import distutils.util; print(distutils.util.get_platform())
linux-armv7l
```

**Comment by andyfaff** [comment]
https://www.piwheels.org/project/scipy/

There are 1.6 wheels there, for Raspbian Buster.

**Comment by Eefried** [comment]
Thanks for offering help - I included --extra-index-url  with this path and used pip3 -v. The result is the same. disappointing
- creating some directories
- looking in indexes
- checking requirements (already satisfied usr/lib/python3/dist-packages (1.1.0).
-cleaning up
- removed build tracker

**Comment by matthew-brett** [comment]
Not sure what's going on there, but I think I have a completely default Buster install, and this works correctly for me...

```
sudo apt install libatlas-base-dev
python3 -m pip install --upgrade scipy
python3 -c 'import scipy; print(scipy.__version__)'
```

This gives `1.6.0`.
