### ISSUE TITLE
ValueError in scipy/cluster/hierarchy.py (line 3277)

### ISSUE THREAD

**Issue by Cedricyf** [scipy/scipy#13528]
The if statement join two statements without bracket which can not run in python 3.8 but able to run on python 3.6. Please see the attachment.
![4011612744450_ pic_hd](https://user-images.githubusercontent.com/37076023/107164113-23572000-6973-11eb-944a-6dd606dd15b0.jpg)

**Comment by AtsushiSakai** [comment]
Hi. thank you for reporting. 
Could you give us the reproducing codes for your issue? 
And could you let us know which version of scipy you are using in python3.8 and python 3.6?

**Comment by rgommers** [comment]
This was fixed, code now reads:
```python
    if labels is not None and Z.shape[0] + 1 != len(labels):
        raise ValueError("Dimensions of Z and labels must be consistent.")
```

Thanks for the report @Cedricyf
