### ISSUE TITLE
signal.decimate doesn't use sosfilters and sosfiltfilt 

### ISSUE THREAD

**Issue by iampritishpatil** [scipy/scipy#13529]
Since the default recommended filters for scipy are now SOS, it should make sense to use them for decimate (and other internal uses)

This is the current state of scipy.signal.decimate
```
        if zero_phase:
            y = filtfilt(b, a, x, axis=axis)
        else:
            y = lfilter(b, a, x, axis=axis)
```

Sorry if this isn't the right class of Issue, new to doing this.

**Comment by SAP-20** [comment]
A NEWBIE IN THE OPEN SOURCE COMMUNITY.SIR, WOULD LIKE TO ASSIGN THE ISSUE TO ME??

**Comment by j-bowhay** [comment]
@varunjain3 looks like @roryyorke's pr is pretty much ready to be merged and we don't want to duplicate effort but there are plenty of other good first issues.
