### ISSUE TITLE
Newton-iteration should not be done after secant interpolation

### ISSUE THREAD

**Issue by jamadagni** [scipy/scipy#13535]
https://github.com/scipy/scipy/blob/417761e719dcb5cf3c9bb0a25f9f0f792cfb350a/scipy/optimize/zeros.py#L1020

I believe this line should read `return a - fa / B` because the following lines are the Newton iteration steps and there is no meaning to do them after secant interpolation.

**Comment by mdhaber** [comment]
@world would someone be able to confirm this after reading the [TOMS 748 paper](https://na.math.kit.edu/alefeld/download/1995_Algorithm_748_Enclosing_Zeros_of_Continuous_Functions.pdf)? Is `A=0` a termination condition?

**Comment by mdhaber** [comment]
@pvanmulbregt Thanks for your help with gh-17687. This issue is also pretty straightforward question about TOMS748. If you agree with the suggestion, I'd be happy to take care of the PR.

**Comment by pvanmulbregt** [comment]
After rereading the original [TOMS 748 paper](https://na.math.kit.edu/alefeld/download/1995_Algorithm_748_Enclosing_Zeros_of_Continuous_Functions.pdf) I think that I misunderstood the description of the Newton-Quadratic subroutine (Equation 4, but note that the 2nd expression for r<sub>i</sub> may be missing a `f(a)` term in the numerator.) 
The statement   

If A=0, then r = a - B<sup>-1</sup>f(a)     

is meant to set the final value of `r`, not the value of r<sub>0</sub> to be used in the subsequent Newton iteration steps.

So I agree that the [code block in optimize.zeros._newton_quadratic ](
https://github.com/scipy/scipy/blob/417761e719dcb5cf3c9bb0a25f9f0f792cfb350a/scipy/optimize/zeros.py#L1023-L1031) should not be executed if the secant step is applied.  Either by returning immediately or by indenting that block to only execute under the else part of `if A == 0`.
