### ISSUE TITLE
Why the version is 0.0.0?

### ISSUE THREAD

**Issue by huwei1024** [scipy/scipy#13544]
I build scipy from source, the version is 1.6.0. 
But the fold name is 0.0.0 ?
`scipy-0.0.0-py3.9-macosx-11-arm64.egg`

How can i fix this?

**Comment by ilayn** [comment]
If you are not building from a git capable repo then the version number might not be available. It reads the tag or the commit number depending what the current branch is sitting on. Other than that, this is tested practically everywhere so it is very likely that your config is somehow having issues. Hence we need more info about this in a reproducible fashion.

**Comment by larsoner** [comment]
@huwei1024 feel free to follow #13609, where I experience the same issue (and provide more details of my particular workflow)
