### ISSUE TITLE
Modified z-score

### ISSUE THREAD

**Issue by darrencl** [scipy/scipy#13548]
Scipy has `stats.median_abs_deviation` implemented, which means this supports non-parametric/'median-stack' stats. There is `stats.zscore`, which is mean-std stack. This feature would be very helpful when working with skewed data or data with outliers. 

I'm just wondering if we could have modified z-score with median and median abs deviation implemented?

I am happy to work on this if maintainer would approve. Suggestion on how to implement is appreciated.

**Comment by mdhaber** [comment]
Thanks for your patience @darrencl. I'm not familiar with the term "stack".
Are you looking asking whether z-score could have an option that calculates `(x - stats.median(x))/stats.median_abs_deviation(x)`?

**Comment by darrencl** [comment]
@mdhaber Sorry for the confusion. I referred 'stack' in this case to the combination of analysis functions. For instance, one would use mean-std-zscore to perform parametric analysis.

> Are you asking whether z-score could have an option that has it calculate (x - stats.median(x))/stats.median_abs_deviation(x)

Yes! I think something having it as separate function would be neat, i.e. `stats.modified_zscore`. I think that makes more sense than including this in `stats.zscore` as modified z-score is essentially different function. But if you want, we probably can have something like `nonparametric=True` argument to the `stats.zscore`.

**Comment by mdhaber** [comment]
We avoid adding functions which are trivial combinations of other functions. There is a lot of overhead that goes into implementing, documenting, testing, and reviewing these things, and often it doesn't justify the time it saves users. The exception would be if it is _very_ widely used. Do you have references that illustrate how widely this is used?

**Comment by darrencl** [comment]
@mdhaber I see! Here's some reference that uses this:

- https://medium.com/analytics-vidhya/anomaly-detection-by-modified-z-score-f8ad6be62bac
- [IBM knowledge centre](https://www.ibm.com/support/knowledgecenter/SSEP7J_11.1.0/com.ibm.swg.ba.cognos.ug_ca_dshb.doc/modified_z.html#:~:text=The%20modified%20z%20score%20is,differs%20from%20the%20typical%20score.&text=The%20modified%20z%20score%20is%20calculated%20from%20the%20mean%20absolute,median%20absolute%20deviation%20(MAD).)
- https://www.itl.nist.gov/div898/handbook/eda/section3/eda35h.htm

How to send a message to the mailing list? Aren't they tracking the issue here?

**Comment by mdhaber** [comment]
You can join the scipy-dev mailing list [here](https://www.scipy.org/scipylib/mailing-lists.html) then email that address.

Not everyone receives notifications about GitHub activity, and there are far fewer mailing list emails than GitHub notifications, so more noticeable.

See gh-13475 for an example PR adding what is essentially a one-line function. 

I think it would be less work to add an argument to `zscore`. Its documentation there says:
> Compute the z score of each value in the sample, relative to the sample mean and standard deviation.

A new argument could just explain the option to calculate it "relative to the sample median and median absolute deviation".

**Comment by darrencl** [comment]
@mdhaber Thanks for that! Anyway, would it be more helpful if I create a PR for this instead of bothering the scipy-dev team?

**Comment by mdhaber** [comment]
You can, but you will still need to email the list at some point to see if adding the feature is desired. The order is up to you.

**Comment by rlucas7** [comment]
If I understand correctly there is already a function that does this in sklearn 

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

Any reason why to not use that one?

We usually avoid duplication when possible for reasons @mdhaber already mentioned about maintainer time.

-Lucas Roberts

**Comment by darrencl** [comment]
@rlucas7 Thanks for responding! Does that have any option to use median and median_abs_deviation?

> where u is the mean of the training samples or zero if with_mean=False, and s is the standard deviation of the training samples or one if with_std=False.

From the documentation above it seems that the `with_mean` is set to 0 (not median) if it is False, and std is one if `with_std == False` (not median absolute deviation).

> Any reason why to not use that one?

In addition to above, `scipy.stats` should have this option nevertheless. If a user writes a package that only needs statistical analysis and not building a model, it would not make any sense to depend on sklearn just for this purpose.

**Comment by rlucas7** [comment]
> On Mar 11, 2021, at 7:55 PM, Darren Christopher Lukas ***@***.***> wrote:
> 
> ﻿
> @rlucas7 Thanks for responding! Does that have any option to use median and median_abs_deviation?
> 
There are different, robust scalers that subtract median, please consult the sklearn docs for specifics.
> where u is the mean of the training samples or zero if with_mean=False, and s is the standard deviation of the training samples or one if with_std=False.
> 
> From the documentation above it seems that the with_mean is set to 0 (not median) if it is False, and std is one if with_std == False (not median absolute deviation).
> 
> Any reason why to not use that one?
> 
> In addition to above, I think scipy.stats should have this option nevertheless. If a user writes a package that only needs statistical analysis and not building a model, it would not make any sense to depend on sklearn just for this purpose.
> 
that is up to the developers of the hypothetical project. My vote would be to not include something like this in SciPy.

**Comment by darrencl** [comment]
> that is up to the developers of the hypothetical project. My vote would be to not include something like this in SciPy.

Thanks a lot for your thought! I'm not trying to argue or anything since I'm not part of Scipy myself (just a user :-) ), but if the argument against this is simply because sklearn has it, doesn't it mean that `stats.zscore` shouldn't be written too, since sklearn standardscaler does this?

**Comment by mdhaber** [comment]
@darrencl I think more opinions here would help a decision to be made. Would you email the mailing list as described above (https://github.com/scipy/scipy/issues/13548#issuecomment-795631438)?

**Comment by mdhaber** [comment]
This needed an email to the mailing list to move forward. Since there are some reasons not to add this, let's close in the meantime. If anyone would like to champion this, to please send that email and lmk to re-open the issue. Thanks!
