### ISSUE TITLE
shape error in linprog with revised simplex

### ISSUE THREAD

**Issue by martinResearch** [scipy/scipy#13559]
scipy.optimize.linprog  with method  "revised simplex" fails with a shape error.

#### Reproducing code example:

download attached zip file [scipy_optimize_linprog_inputs.zip](https://github.com/scipy/scipy/files/5975660/scipy_optimize_linprog_inputs.zip) and unzip the file to get scipy_optimize_linprog_inputs.pkl file that contains the LP problem dumped in a pickle file

```
import pickle
import scipy
import scipy.optimize
import numpy as np

with open("scipy_optimize_linprog_inputs.pkl", "rb") as fh:
    inputs = pickle.load(fh)

# using highs-ds works fine
inputs["method"] = "highs-ds"
sol = scipy.optimize.linprog(**inputs)["x"]

# using revised simplex fails
inputs["method"] = "revised simplex"
scipy.optimize.linprog(**inputs)
```

#### Error message:

I get the error 

```
Exception has occurred: ValueError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
shapes (1,640) and (1,640) not aligned: 640 (dim 1) != 1 (dim 0)
  File "D:\repos\PySparseLP\python_venv\Lib\site-packages\numpy\matrixlib\defmatrix.py", line 220, in __mul__
    return N.dot(self, asmatrix(other))
  File "D:\repos\PySparseLP\python_venv\Lib\site-packages\scipy\optimize\_linprog_rs.py", line 256, in _select_singleton_columns
    same_sign = A[row_indices, column_indices]*b[row_indices] >= 0
  File "D:\repos\PySparseLP\python_venv\Lib\site-packages\scipy\optimize\_linprog_rs.py", line 197, in _generate_auxiliary_problem
    cols, rows = _select_singleton_columns(A, r)
  File "D:\repos\PySparseLP\python_venv\Lib\site-packages\scipy\optimize\_linprog_rs.py", line 50, in _phase_one
    A, b, c, basis, x, status = _generate_auxiliary_problem(A, b, x0, tol)
  File "D:\repos\PySparseLP\python_venv\Lib\site-packages\scipy\optimize\_linprog_rs.py", line 563, in _linprog_rs
    maxiter, tol, disp, maxupdate, mast, pivot))
  File "D:\repos\PySparseLP\python_venv\Lib\site-packages\scipy\optimize\_linprog.py", line 647, in linprog
    postsolve_args=postsolve_args, **solver_options)
  File "D:\repos\PySparseLP\bug_scipy_linprog.py", line 13, in <module>
    scipy.optimize.linprog(**inputs)
  File "D:\Python3.7.9\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python3.7.9\Lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Python3.7.9\Lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\Python3.7.9\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python3.7.9\Lib\runpy.py", line 193, in _run_module_as_main (Current frame)
    "__main__", mod_spec)
```

#### Scipy/Numpy/Python version information:

Using scipy 1.6.0

**Comment by mdhaber** [comment]
Thanks for reporting the issue! Pickle files are not a safe way to transmit this sort of thing, though. Nor are zip files, for that matter. Please provide the example in plain text, perhaps as a [gist](https://docs.github.com/en/github/writing-on-github/creating-gists) if it's too big to post here.

**Comment by martinResearch** [comment]
This can reproduce the problem 
```
import scipy.sparse
import numpy as np

m=100
n=150
A_eq = scipy.sparse.rand(m, n, 0.5)
x_valid = np.random.randn((n))
c = np.random.randn((n))
ub = x_valid + np.random.rand((n))
lb = x_valid - np.random.rand((n))
bounds = np.column_stack((lb, ub))
b_eq = A_eq*x_valid
scipy.optimize.linprog(
    A_eq=A_eq, c=c, b_eq=b_eq, bounds=bounds, method="revised simplex"
)
```

It seems that the revised simplex simply does not support sparse constrain matrices. Maybe a more explicit error about sparse constraint matrices not being supported could be raised ? 

The problem can be fixed on that specific failing line by replacing 

```
column_indices = np.nonzero(np.sum(np.abs(A) != 0, axis=0) == 1)[0]
```
by
```
column_indices = np.nonzero(np.sum(np.abs(A) != 0, axis=0).flat == 1)[0]
```
but then other errors appear down the line. 
I don't know if making the code able to handle sparse matrices without converting the constraint matrix to a dense matrix would make sense for the revised simplex method.

**Comment by mdhaber** [comment]
I don't think we'll be adding native sparse support to revised simplex, and it might be better to get errors from `'revised simplex'` than to convert to dense because the `'highs'` methods should be used now that they're available. I'm curious - any reason you'd prefer revised simplex?
I can try to make the documentation more explicit about sparse support, though.

**Comment by martinResearch** [comment]
Raising a more explicit error seems to be the best option to me. I have no preference for `revised simplex` over `highs`, I was simply trying to compare the different methods. Actually the "simplex" method also fails and would also benefit from a more explicit error message.
