### ISSUE TITLE
rotation._compute_euler_from_matrix() creates an array with negative stride (-8)

### ISSUE THREAD

**Issue by marscher** [scipy/scipy#13584]
The scipy.spatial.transform.Rotation class generates a "weird" output array when calling the method as_euler. The stride of this array is negative (-8). This does not seem like a problem, but causes issues in downstream software, e.g. when serializing the array.
Taking a copy "fixes" the stride again, e.g. makes it positive again. I assume that this is caused by the extrensic broadcasting/reversing done here:
https://github.com/scipy/scipy/blob/f6762e4b502c7cb2455f660ed48954110d5ff616/scipy/spatial/transform/rotation.pyx#L221

Downstream code using Rotation.from_euler worked prior version 1.6, in which the Rotation class is a cythonized class.

xref: https://github.com/asdf-format/asdf/issues/916
xref: https://github.com/BAMWelDX/weldx/issues/226

#### Reproducing code example:

``` python
from scipy.spatial.transform import Rotation

R = Rotation([1, 0, 0, 0])
euler = R.as_euler("xyz")
assert all(i >= 0 for i in euler.strides), euler.strides
euler_intrinsic = R.as_euler("XYZ")
assert all(i >= 0 for i in euler_intrinsic.strides), euler.strides # this "works", e.g. has a positive stride.
```

#### Error message:

```
    assert all(j >= 0 for i,j  in enumerate(euler.strides)), euler.strides
AssertionError: (-8,)
  ...
```

#### Scipy/Numpy/Python version information:
1.6.0 1.20.1 sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)

**Comment by marscher** [comment]
Mhm I guess this is not a bug, but quite expected due to the reversing array operation. So downstream projects should deal with this, right?

**Comment by tylerjereddy** [comment]
Let's check with @nmayorov

**Comment by nmayorov** [comment]
@marscher 

To be honest I have never thought about array strides and especially negative strides. It looks like having negative strides is strange and unnecessary. Adding copy operation easily fixes that:

```
a = np.arange(10)
b = a[::-1]
print(b.strides)

b = a[::-1].copy()
print(b.strides)
```
```
(-8,)
(8,)
```

Can you send a fix PR for that?

**Comment by marscher** [comment]
Sure can do, thanks for looking into this!

**Comment by marscher** [comment]
@nmayorov I've opened up PR #13598
