### ISSUE TITLE
ENH: stats: `rv_continuous.stats` with array shapes: use `_stats` when possible and `_munp` otherwise?

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#13582]
After some input standardization, `rv_continuous.stats` calls:
```python3
mu, mu2, g1, g2 = self._stats(*goodargs)
```

For those outputs that are `None`, it uses `_munp` instead to calculate the moment.
e.g.:
```python3
if mu is None:
    mu = self._munp(1, *goodargs)
```

The problem is that the shape parameters can be arrays, and so `mu` could be an array. For some distributions (e.g. `kappa3`, `kappa4`), `_stats` can calculate the moments for some values of the shape parameters. However, `_stats` has only two options:

- return the moments for all values in the array of shapes or
- return `None` and let `_munp` calculate the moments.

It's all or nothing. At best this is inefficient, but it can also lead to other problems.

For example, `kappa3._stats` is currently implemented as:
```python3
    def _stats(self, a):
        outputs = [None if i < a else np.nan for i in range(1, 5)]
        return outputs[:]
```

Currently, it doesn't consider the possibility that `a` could be an array, so it fails when `a` is an array:
```python3
from scipy.stats import kappa3
kappa3.stats([1.5, 2.5])  # ValueError: The truth value of an array...
```

One option to make it work with arrays is to change `i < a` to `np.any(i < a)`. But this leads to inaccurate values of the moments for the elements where `i > a`. They should be `nan`, but `_munp` tries to calculate a numerical value... and doesn't get `nan`.

That is, if we change `i < a` to `np.any(i < a)`,
```python3
kappa3.stats([0.5])  # (array([nan]), array([nan]))
kappa3.stats([0.5, 1.5])
```
results in:
```

C:\Users\matth\scipy\scipy\stats\_distn_infrastructure.py:1801: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  return integrate.quad(self._mom_integ1, 0, 1, args=(m,)+args)[0]
Out[32]: (array([-13.14848276,   2.31495165]), array([nan, nan]))
```

So I don't know how we would add array shape support to `kappa3` (or `kappa4`) without a lot of changes to `rv_continuous.stats`.

Suggestions on how to deal with this? I have some thoughts, but I don't really like them.

**Comment by mdhaber** [comment]
To close this issue, `kappa3` and `kappa4` `stats` should work for array inputs, and these distributions should be removed from the list `fail_loc_scale` in `test_continuous_basic.py` (assuming 13581 merges).

**Comment by Smit-create** [comment]
Hi @mdhaber ,

Using the following diff:

```diff
diff --git a/scipy/stats/_continuous_distns.py b/scipy/stats/_continuous_distns.py
index 0c92eb9c9..890836515 100644
--- a/scipy/stats/_continuous_distns.py
+++ b/scipy/stats/_continuous_distns.py
@@ -5964,7 +5964,7 @@ class kappa3_gen(rv_continuous):
         return (a/(q**-a - 1.0))**(1.0/a)
 
     def _stats(self, a):
-        outputs = [None if i < a else np.nan for i in range(1, 5)]
+        outputs = [None if np.any(i < a) else np.nan for i in range(1, 5)]
         return outputs[:]
 
 
diff --git a/scipy/stats/_distn_infrastructure.py b/scipy/stats/_distn_infrastructure.py
index 0d7d958c7..949004686 100644
--- a/scipy/stats/_distn_infrastructure.py
+++ b/scipy/stats/_distn_infrastructure.py
@@ -1857,6 +1857,8 @@ class rv_continuous(rv_generic):
         return (self.ppf(q, *args))**m
 
     def _mom1_sc(self, m, *args):
+        if np.any(np.array(args) >= m):
+            return np.nan
         return integrate.quad(self._mom_integ1, 0, 1, args=(m,)+args)[0]
```

I get these results:

```py
>>> from scipy.stats import kappa3
>>> kappa3.stats([0.5, 1.5])
(array([-13.14848276,          nan]), array([nan, nan]))
>>> kappa3.stats([0.5]) 
(array([nan]), array([nan]))
```
Any suggestions to improve or this works well?

**Comment by mdhaber** [comment]
@Smit-create thanks for looking into this. I left a comment in the PR for you.
