### ISSUE TITLE
binned_statistic unreliable with single precision

### ISSUE THREAD

**Issue by jeffplourde** [scipy/scipy#13587]
When using single precision values not every value in my array is put into a bin by `binned_statistic`. The final (closed) bin interval excludes my original single precision value.

#### Reproducing code example:

```
from scipy.stats import binned_statistic
import numpy

x = numpy.array([0, 0.42358226], dtype=numpy.float32)
count, _, _ = binned_statistic(x, values=None, statistic='count')
count.sum()!=x.shape[0]
```

#### Error message:
The second data point in my data array is not included in any bin.

#### Scipy/Numpy/Python version information:
```
1.6.1 1.19.4 sys.version_info(major=3, minor=7, micro=8, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment]
The problem is in `_bin_numbers` in _binned_statistic.py. This line:
```
        # Find which points are on the rightmost edge.
        on_edge = np.where(np.around(sample[:, i], decimal) ==
                           np.around(edges[i][-1], decimal))[0]
```
is not doing its job. When:
```
x = numpy.array([0, 0.4235822], dtype=numpy.float32)
```
`on_edge` is `[1]`, but when
```
x = numpy.array([0, 0.4235826], dtype=numpy.float32)
```
`on_edge` is `[]`.

**Comment by mdhaber** [comment]
PRs welcome.

**Comment by jeffplourde** [comment]
I'm a first time contributor to scipy so I'm open to criticism on it but I proposed a fix.

https://github.com/scipy/scipy/pull/13593

Thanks @mdhaber.
