### ISSUE TITLE
Behavior change in coo_matrix when dtype=None

### ISSUE THREAD

**Issue by rossbar** [scipy/scipy#13585]
There is a change in behavior with `dtype=None` in the `scipy.sparse.coo_matrix` constructor between versions 1.6.0 and 1.6.1.

#### Reproducing code example:

```python
>>> import scipy.sparse
>>> m = scipy.sparse.coo_matrix(([1], ([0], [0])), dtype=None)
```

**1.6.0**
```python
>>> m
<1x1 sparse matrix of type '<class 'numpy.int64'>'
        with 1 stored elements in COOrdinate format>
```

**1.6.1**
```python
>>> m
<1x1 sparse matrix of type '<class 'numpy.float64'>'
        with 1 stored elements in COOrdinate format>
```

#### Scipy/Numpy/Python version information:
numpy = 1.19.5
scipy = 1.6.0/1.6.1
python = 3.9.1

**Comment by rossbar** [comment]
I was able to confirm this is related to 494b25ca248 via local testing, h/t @jarrodmillman for investigating this initially.

**Comment by WarrenWeckesser** [comment]
@rossbar, yeah, that change is the first thing I suspected.  It looks like we now incorrectly set the default data type for COO matrices that are given as `(data, (i, j))` to `float`.  Instead, it should be the data type determined by `np.array(data)`.

**Comment by WarrenWeckesser** [comment]
Potential fix in https://github.com/scipy/scipy/pull/13586

**Comment by jakelishman** [comment]
Just to add that complex numbers also break the dtype inference:
```python
>>> import scipy.sparse
>>> scipy.__version__
'1.6.1'
>>> scipy.sparse.coo_matrix(([1+1j], ([0], [0])), shape=(2, 2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/scipy/sparse/compressed.py", line 54, in __init__
    other = self.__class__(coo_matrix(arg1, shape=shape,
  File "/Users/jake/.anaconda3/envs/qutip-dev/lib/python3.8/site-packages/scipy/sparse/coo.py", line 161, in __init__
    self.data = np.array(obj, copy=copy, dtype=data_dtype)
TypeError: can't convert complex to float
```
I suspect scipy/scipy#13586 would fix this too.
