### ISSUE TITLE
Is it possible to access earlier values in odeint?

### ISSUE THREAD

**Issue by Antonio-Nappi** [scipy/scipy#13599]
Hello everybody, I'd like to know if it possible to access earlier values in odeint during the integration. My question arises since I'm converting a discrete system into a continuous one. The equation that I can't translate is:
`S(t+1)= S(t) - k*S(t)*I(t)/(Q(t)+..D(t))`
In a continuous version I could write directly:
`dSdt = k*...` but the other values are also equations that I'm solving, how can I access to the previous value? Should I use it as a discrete system?

**Comment by tupui** [comment]
Hi! If you set `full_output=True`, you will have `infodict` with all the intermediate results.

For support questions, prefer using StackOverflow or the user mailing list 😄
