### ISSUE TITLE
The crystallball distribution entropy is sometimes minus infinity

### ISSUE THREAD

**Issue by iandall** [scipy/scipy#13602]
The crystalball entropy function returns -inf for valid shape parameters.

#### Reproducing code example:

```
from scipy.stats import crystalball
crystalball.entropy(2, 3)
```

#### Error message:

```
>>> cb.entropy(2,3)
array(-inf)
```

#### Scipy/Numpy/Python version information:

```
1.7.0.dev0+5ac5f63 1.19.4 sys.version_info(major=3, minor=9, micro=1, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
This appears to be the result of the bug in the internal utility function `_lazywhere` that was noted in https://github.com/scipy/scipy/pull/13370#pullrequestreview-564665361.  The fix suggested there also fixes this issue with `crystalball.entropy`.

**Comment by ev-br** [comment]
Apart from the _lazywhere bug, there is an issue with numeric integration of `pdf * log(pdf)` being thrown off by an integrable singularity at `x=-beta`. Two possible fixes: (i) play with `integrate.quad` parameters, `points` or some such, (ii) implement an explicit formula for the `crystallball.entropy` (sorry for the image quality)

**Comment by mdhaber** [comment]
N and A shouldn't factor out completely, right?

**Comment by ev-br** [comment]
The other PR shows a warning from quad (distriburions silence them IIRC), which signalsthat quadpack has difficulties it did or did not manage to overcome. I suspect the answer it gives may be bogus.

**Comment by mdhaber** [comment]
Oops, I missed that PR...

**Comment by mdhaber** [comment]
Yeah I think that note in the other PR was about the behavior pre-PR.

**Comment by iandall** [comment]
> This appears to be the result of the bug in the internal utility function `_lazywhere` that was noted in [#13370 (review)](https://github.com/scipy/scipy/pull/13370#pullrequestreview-564665361). The fix suggested there also fixes this issue with `crystalball.entropy`.

The two fixes to `_lazywhere` are rather different though. The fix in [#13370 (review)](https://github.com/scipy/scipy/pull/13370#pullrequestreview-564665361) just adds `np.asarray(cond)` which results in the following behavior:
```
>>> a = np.random.rand(3,4)
>>> cond = np.asarray(True)
>>> np.extract(cond, a)
array([0.96527571])
```
All elements of a except the first one are masked out. Whereas I was proposing, in effect:
```
>>> cond, a = np.broadcast_arrays(cond,a)
>>> cond
array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])
>>> a
array([[0.96527571, 0.5226296 , 0.01173389, 0.53483096],
       [0.82768954, 0.90497178, 0.70879789, 0.64090641],
       [0.1620266 , 0.59160494, 0.70857117, 0.95175377]])
``` 
None of the elements of `a` are masked out. It comes down to what semantics are meant by a scalar `cond`, but this (latter) is how `np.where` works.

**Comment by mdhaber** [comment]
Does the difference affect the output of `_lazywhere`?

**Comment by mdhaber** [comment]
`np.place` requires that the mask and the array be the same size, so it looks like the fix suggesting in https://github.com/scipy/scipy/pull/13370#pullrequestreview-564665361 will cause an error if the broadcasting is not done before entering the function. Sure, I think doing broadcasting is a good idea, even if SciPy functions (apparently) don't currently rely on it to be done.

**Comment by mdhaber** [comment]
How about this: gh-13607 is very focused - it makes the minimal change required to fix `crystalball`, and it adds a regression test. Let's merge that as is. gh-13603 appears to suggest many different things, among them an additional improvement to `lazywhere` to broadcast the `cond` input. That sounds like a good thing to consider, too, but there are also a lot of unrelated things in that PR. You might consider breaking it into a few PR, each with a focus and possibly tests.

**Comment by iandall** [comment]
> [gh-13603](https://github.com/scipy/scipy/pull/13603) appears to suggest a few different things, among them an additional improvement to `_lazywhere` to broadcast the `cond` input. That sounds like a good thing to consider, too, although it is not essential to be done just to fix `crystalball`, as `_lazywhere` is a private function and no SciPy code currently relies on it to broadcast the arguments. It seems that there are a few unrelated changes in [gh-13603](https://github.com/scipy/scipy/pull/13603), too, Please consider breaking it into a few PRs, each with a focus and tests that confirm that the changes work as intended.

Sorry about that [gh-13603](https://github.com/scipy/scipy/pull/13603). That PR was only supposed to have the `_lazywhere` broadcast commit in it. I clearly have something to learn about how pull requests work. I created a separate branch, cherry picked the commit and, pushed it, then created a PR. Isn't that how it is supposed to to work? But somehow other commits are included. Is there guide somewhere?

**Comment by mdhaber** [comment]
> Again, sorry for the confusion!

No problem! Yeah, the PR is not frozen once you submit it; it is tied to a branch in your GitHub repo. You should create a new branch for each PR. 

> Is there guide somewhere?

Maybe [this](http://scipy.github.io/devdocs/dev/contributor/development_workflow.html#development-workflow) will help. For this and other developer documentation, see the [contributor guide](http://scipy.github.io/devdocs/dev/contributor/contributor_toc.html).
