### ISSUE TITLE
BUG: SciPy pip install -e gets unusable version spec

### ISSUE THREAD

**Issue by larsoner** [scipy/scipy#13609]
For a couple of years now I've been installing a dev version locally with some variant of:
```console
$ pip install --no-use-pep517 -ve .
```
And up until a couple of months ago this worked. Nowadays after doing this I get an error when I actually try to use modules that depend on SciPy:
```
pkg_resources.DistributionNotFound: The 'scipy>=1.1.0' distribution was not found and is required by mne
```
This is because in the `scipy.egg-info/PKG-INFO` that gets produced the contents are:
```
Metadata-Version: 1.2
Name: scipy
Version: 0.0.0
Summary: SciPy: Scientific Library for Python
...
```
in other words, the Version gets written as 0.0.0, when really it should match this:
```
$ python -c "import scipy; print(scipy.__version__)"
1.7.0.dev0+d78daa5
```
And putting this in as the `Version` makes everything work again.

I'm not really sure where to start looking since I find it challenging to navigate packaging infrastructure -- any tips appreciated! I guess it could be our problem, or PyPi's, or NumPy's somewhere, but I don't have this problem when installing this way with NumPy at least. I'll tag for 1.7.0 as a reminder for me to hopefully look into it before then.

**Comment by tupui** [comment]
Could this be linked to #13544?

**Comment by larsoner** [comment]
Probably the same issue, yeah

**Comment by tylerjereddy** [comment]
cc @rgommers @charris maybe?

If we have a suitable solution for this I could probably backport along with Ralf's recent adjustments/procedure for `pyproject.toml` and related files.

**Comment by rgommers** [comment]
I can have a look later; my first guess is that it's a pip bug or it's calling a weird setuptools command. `pip install .`, `pip weel`, `python setup.py develop` et al. all get it right. Pip editable installs are a bit problematic, that's why they're still not included in PEP 517. I've always avoided it.

**Comment by larsoner** [comment]
> python setup.py develop et al. all get it right.

At least on my system `setup.py develop` has the same problem:
```Console
$ git fetch upstream
$ git reset --hard upstream/master
$ git clean -xdf
$ ln -s ../site.cfg
$ python setup.py develop --user
$ grep Version scipy.egg-info/PKG-INFO
Metadata-Version: 1.2
Version: 0.0.0
$ pip check | grep "mne "
mne 0.23.dev0 has requirement scipy>=1.1.0, but you have scipy 0.0.0.
```
And my site.cfg is just this so it's hopefully not the problem (but maybe I should try without it just to be sure at some point):
```ini
[ALL]
extra_compile_args = -march=native

[openblas]
libraries = openblas
library_dirs = /opt/OpenBLAS/lib
include_dirs = /opt/OpenBLAS/include
runtime_library_dirs = /opt/OpenBLAS/lib
```
And just for completeness, this is all on Ubuntu x86_64 20.10 with Python 3.9 and latest `pip install --upgrade pip setuptools wheel` and on NumPy `master` from a few weeks ago.

I went back to a commit from July 312b706c1d98980ed140adae943d41f9f7dc08f5 and it still had this problem, so it probably is some dependency like pip/setuptools/NumPy. I can dig into it more later.

**Comment by ilayn** [comment]
pip is updated recently and there are major changes in it. I'd say this is already happening to others too. Frankly the new resolver is not usable yet. So I also wait for many other issues very soon.

**Comment by rgommers** [comment]
`python setup.py` develop with `pip` 21.0.1 and `setuptools` 49.6.0:
```
$ grep Version scipy.egg-info/PKG-INFO
Metadata-Version: 1.2
Version: 1.7.0.dev0+d98dbb9
```
Quicker way to test:
```
$ python setup.py egg_info
$ grep Version scipy.egg-info/PKG-INFO
```

**Comment by rgommers** [comment]
Also check the version number in `scipy/version.py` to exclude an issue with our version handling.

**Comment by larsoner** [comment]
> Quicker way to test:

When I do it that way it works:
```
$ python setup.py egg_info
...
$ rm -Rf scipy.egg-info
$ grep Version scipy.egg-info/PKG-INFO
Metadata-Version: 1.2
Version: 1.7.0.dev0+fc77ea1
```
But it's not equivalent for some reason:
```
$ rm -Rf scipy.egg-info
$ python setup.py develop --user
...
$ grep Version scipy.egg-info/PKG-INFO
Metadata-Version: 1.2
Version: 0.0.0
```
So it's something weird about using develop mode in particular. FWIW the version is fine in Python (and `version.py` looks okay):
```
$ python -c "import scipy; print(scipy.__version__)"
1.7.0.dev0+fc77ea1
```

**Comment by larsoner** [comment]
I am on pip 21.0.1 and setuptools 53.0.0. When I downgrade to setuptools 49.6.0, same behavior:
```
$ pip install setuptools==49.6.0
$ rm -Rf scipy.egg-info/
$ python setup.py develop --user
...
$ grep Version scipy.egg-info/PKG-INFO
Metadata-Version: 1.2
Version: 0.0.0
```
When I change to pip numpy, it seems to work though:
```
$ grep Version scipy.egg-info/PKG-INFO
Metadata-Version: 1.2
Version: 1.7.0.dev0+fc77ea1
```
So I guess this is a NumPy regression somehow.

**Comment by rgommers** [comment]
> When I change to pip numpy, it seems to work though:

what does this mean exactly? did you downgrade numpy version?

**Comment by larsoner** [comment]
Yep instead of using my version of NumPy `master` compiled a few weeks ago I `pip uninstall numpy; pip install numpy`ed which installed 1.20.1.

I then tested https://github.com/numpy/numpy/commit/7829237f823ea1d21952bc5bccb435a0782234da, which was fine, and then the next commit which switched to versioneer, https://github.com/numpy/numpy/commit/40fd17e3a2418d54284b53dbcf2ba72dbfbb58ad / https://github.com/numpy/numpy/pull/17956 broke it -- just checking out one branch or the other then repeating `python setup.py develop --user` on the same latest SciPy `master` commit toggles between `1.7.0.dev0+fc77ea1` and `0.0.0` showing up in PKG-INFO. I'm tempted to open a NumPy bug for this, but their version shows up fine so it seems like it should be fixable at the SciPy end somehow (?).

**Comment by larsoner** [comment]
Closing for https://github.com/numpy/numpy/pull/18493

**Comment by rgommers** [comment]
Grr, `versioneer` has been such a bad change to make.

**Comment by larsoner** [comment]
Personal side note that I dislike that it adds ~100 ms of import time due to the `git describe` command it runs, when doing a lot of testing every little bit adds up :(

**Comment by rgommers** [comment]
I dislike everything about it. It was like 100 lines of code to produce a 5-line `version.py` file. Now it's ~2000 LoC generating a ~500 LoC `version.py` file. 

> Personal side note that I dislike that it adds ~100 ms of import time due to the `git describe` command it runs, when doing a lot of testing every little bit adds up :(

This is at build time or at `import scipy` time? The latter would be really bad.

**Comment by larsoner** [comment]
`import numpy`, hence by extension `import scipy`

**Comment by larsoner** [comment]
(but this is just for the local dev build, I doubt it's this way for the wheel versions, assuming those use a static `version.py` rather than trying to figure out the version on the fly using versioneer)
