### ISSUE TITLE
solve_ivp with RK45 evaluates time values twice, adding error to my solution 

### ISSUE THREAD

**Issue by GitHub-Saga** [scipy/scipy#13619]
I am doing a molecular dynamics simulations and i have noticed that solve_ivp with RK45 destroys my system by adding energy.
The OdeSolver evaluates *fun(...)* at certain seemingly 'random' times twice. This wouldnt be an issue if the solution isnt being altered however the second call does alter it. RK23 and DOP853 do not evaluate twice. I've seen a other similiar bug reports suggesting to change stepsizes and tolerances. These suggestions only minimizes the added error.  

The following code is a simple diff. equation for the exponential function. The output has 3 columns. The first 2 columns are the times evaluated twice. The third column is the error added to the solution. 

For this simple example the error is small enough, so the RK45 solution is still better than the RK23 solution. For multi-particle systems the error gets out of hand.

#### Reproducing code example:

```
import matplotlib.pyplot as plt
import numpy as np
import scipy.integrate as si



def fun(t, ph, tH_, Hol_):     #right-hand-side expressions of diff-equations

    for i in range(Hol_.shape[1]):
        Hol_[0,i]=Hol_[1,i]
        Hol_[1,i]=ph[i]
    
    tH_[0]=tH_[1]
    tH_[1]=t
    
    
    if tH_[0] == tH_[1] and tH_[1] != 0:
        tH_[2] = np.sum(np.abs(Hol_[0]-Hol_[1]))
        print(tH_[0], tH_[1], tH_[2])  
    
    
    return -ph

tmax=1e1    

tH=np.array([0.,0.,0.])     

init=np.array([1])        
Hol=np.zeros((2,init.shape[0]))
solution=si.solve_ivp(fun, (0,tmax), init, method='RK45', dense_output=True, args=(tH, Hol))


# t=np.arange(0,tmax,tmax*1e-3)
# sol=solution.sol(t)                       
  
# plt.figure()
# plt.plot(t,sol[0])
# plt.grid()
# plt.show()
```

#### Output:

```
0.10001999200479661 0.10001999200479661 0.00022459121333262555
1.0318648679184732 1.0318648679184732 0.22446004584572865
1.9076513619659983 1.9076513619659983 0.07203449823974353
2.7872027754639603 2.7872027754639603 0.03044741045348956
3.667207215286887 3.667207215286887 0.012662388716474744
4.5488343612816555 4.5488343612816555 0.005286765229399644
5.43428935305761 5.43428935305761 0.002221968052007064
6.328718602525958 6.328718602525958 0.0009481893241976187
7.243493017774126 7.243493017774126 0.00041786366653675665
8.201472966157132 8.201472966157132 0.00019524866783588373
9.242089962853626 9.242089962853626 9.883353674514255e-05
10.0 10.0 1.2255082666651014e-05
```

#### Scipy/Numpy/Python version information:
```
1.6.1 1.19.2 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
```

**Comment by laurent90git** [comment]
Hi,
RK45, RK23, and DOP853 are explicit methods which use the exact same code and differ only by the method coefficients.
They will all perform substeps (or stages): for on time step `dt`, each method will construct a quadrature (see wiki on Runge-Kutta for more info on that) to approximate the integral of `f` (that defines the ODE) from `t`to `t+dt`.

For that, they construct intermediate solution points at various time points `t + c[i]*dt` for the i-th stage. Then after one step, th method calls `f`once at `t + dt`.
For RK45 and DOP853, one of the coefficient of `c` is one, therefore the function `f` will be called twice at `t+dt` with *different* inputs (one is the a stage value, while the other one is the "final" value computed by the overall Runge-Kutta quadrature using all the stages) for each step and that is absolutely normal.
RK23 does not have the value one in `c`.

I am quite surprised you do no see a double call with DOP853.

Anyway I am pretty sure there is not a specific issue with RK45.

Do you have any plots that show the energy loss/addition that you have found to occur ?

**Comment by GitHub-Saga** [comment]
>What is the similar bug report you mentionned ?

[this threads](https://github.com/scipy/scipy/issues/9899) issue, seems similiar to my issue

Here are the energy graphs of the system. And yes, i missed the fact that DOP853 also evaluates times twice, but RK45 is still much more volatile than DOP853. In one of the graphs I included a custom 'fix', this 'fix' insures solutions arent altered twice for same times. I have also tried this 'fix' for DOP853, the result is the DOP853 solution but slightly expanded to the right (rather minimal change). The solutions in the plots are calculated through the dense_output of solve_ivp.

![vergleiche_verfahren](https://user-images.githubusercontent.com/40702352/109422750-36db3100-79dd-11eb-8e87-e3bf39e94c70.png)

**Comment by laurent90git** [comment]
Best thing would be that you provide a standalone code that we can use to investigate. I remember seeing the thread you mention. I think its problem and yours is maybe more with the default tolerances. Can you try producing the same plots, but with multiple tolerances (set the argument `atol` and `rtol` of `solve_ivp`to the same value and `tol`and try  `tol=1e-3`, `tol=1e-6`, `tol=1e-9`, `tol=1e-12`. I would recommend plotting (as y axis) the log10 of the energy delta compared to the initial state.

What I think is that the error estimate used in RK45 for the time step adaptation is more optimistic than in RK23 and DOP853, in the sense that error is underestimated compared to the error estimated by the other integrators. Therefore, it is possible that it uses larger time steps and makes more error.

**Comment by laurent90git** [comment]
I've run a quick test to see what is the true error achieved on a simple problem versus the specified error tolerance. RK45 does not seem to overestimate the error as I was suggesting in my previous post, however this might problem-related.
Here is a graph of the true error versus the required error for all the integrators from `solve_ivp`:
![image](https://user-images.githubusercontent.com/30652822/109428291-c4774a80-79f6-11eb-978c-3944d6483443.png)

The code:
```python
import scipy.integrate
import numpy as np
import matplotlib.pyplot as plt

def ode(t,x):
    """ Simple ode dy/dt = y """
    return x

y0 = 1. # initial condition
tf = 1e1 # simulation time

# Test all methods
tol_test = np.logspace(-1,-13,10) # all tolerances to be tested
methods = ['RK23', 'RK45', 'DOP853', 'BDF', 'Radau', 'LSODA'] # methods to be tested
rel_error = np.zeros( (len(methods), tol_test.size) )
for i,method in enumerate(methods):
    print(method)
    for j, tol in enumerate(tol_test):
        print(' ',j)
        # compute numerical solution with specified tolerances
        out = scipy.integrate.solve_ivp(fun=ode,
                      t_span=[0.,tf], y0=np.array([y0]),
                      method=method, first_step=tf, max_step=tf,
                      rtol=tol, atol=tol)
        # compute analytical
        y_true = y0 * np.exp( out.t[-1] )
        
        # compute true relative global error
        rel_error[i,j] = np.abs( (out.y[:,-1] - y_true)/y_true )
        
        
        
#%% Plot true error vs required error
plt.figure(dpi=200)
plt.loglog(tol_test, tol_test, label='reference', linestyle='--', color=[0,0,0])
for i,method in enumerate(methods):
    plt.loglog( tol_test, rel_error[i,:], label=method)
plt.grid()
plt.legend()
plt.xlabel('specified tolerance')
plt.ylabel('true error achieved')
````

**Comment by GitHub-Saga** [comment]
here are the plots of the energy delta for different tolerances, guess there wasnt an issue to start with. Its still very peculiar that the default tolerances completely messes up RK45, atleast for my system.

![Unbenannt](https://user-images.githubusercontent.com/40702352/109538851-d6bdbb00-7ac0-11eb-85f5-e4e9d68045c9.png)

**Comment by adrn** [comment]
Just a note to say that the default tolerances for RK45 also led to some unexpected results in my use case (computing a circular orbit in a point mass gravitational potential!). With default tolerances, comparing the non-stiff solvers:
![image](https://user-images.githubusercontent.com/583379/123145054-65689600-d42a-11eb-8fe5-57f863511f5b.png)

It surprises me that RK23 does so well with the default tolerances...Given the confusion in this issue and the one linked above, it might make sense to update the default tolerance parameters for RK45?
