### ISSUE TITLE
Highs solver did not provide a solution nor did it report a failure

### ISSUE THREAD

**Issue by kalvdans** [scipy/scipy#13610]
My issue is about `scipy.optimize.linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, method='highs')` telling me to submit a bug report.

#### Reproducing code example:
See minimal reproducer in a comment
https://github.com/scipy/scipy/issues/13610#issuecomment-785620302

#### Error message:
```
/home/chn/env/lib/python3.8/site-packages/scipy/optimize/_linprog_highs.py:316: OptimizeWarning: model_status is not optimal, using scaled_model_status instead.
  res = _highs_wrapper(c, A.indptr, A.indices, A.data, lhs, rhs,
The solver did not provide a solution nor did it report a failure. Please submit a bug report.
```

#### Scipy/Numpy/Python version information:

```
1.6.1 1.18.3 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
```

**Comment by kalvdans** [comment]
Testcase is around 600k unzipped. Sorry to not trying to minimize the test case.

[reproducer.py.gz](https://github.com/scipy/scipy/files/6038754/reproducer.py.gz)

**Comment by mdhaber** [comment]
@kalvdans thanks very much for reporting this! 
Would you be willing to add this as a [gist](https://gist.github.com/) instead of the zipped file?

**Comment by mckib2** [comment]
This is actually an interesting case I don't think I ever expected to see, so I'm interested to see what this problem is.  A gist would be very helpful

**Comment by kalvdans** [comment]
Ok.. but it has 20000 lines: https://gist.github.com/kalvdans/087c71acda7fb1064d0e4cdc07e85759

**Comment by mdhaber** [comment]
One thing is that these arrays are sparse but they're provided as dense. HiGHS might be choking on that.

**Comment by kalvdans** [comment]
A little background; I tried to follow https://stackoverflow.com/questions/17067351/polynomial-fitting-using-l1-norm#answer-17071311 which results in huge diagonal matrices. Thanks for the tip about using sparse matrices.

**Comment by mckib2** [comment]
Haven't started looking at this -- just fishing for information.  Does this fail for the other linprog methods other than highs?

**Comment by mdhaber** [comment]
I've been running it with "interior-point" using sparse matrices. It's definitely too big for the other methods, so I didn't bother, and "interior-point" is still running.

**Comment by mckib2** [comment]
The best I can do tonight is this simpler reproducer -- I'll be able to dig in more tomorrow.  The trouble seems to be from the size of `A_ub`.  It breaks for me when `A_ub` is `(130, 73)` or larger (when `n > 64` in the reproducer below):
```python
'''Simple LAD regression.'''

import numpy as np
from scipy.optimize import linprog
from scipy.sparse import lil_matrix, csc_matrix

if __name__ == '__main__':
    # Training data is {(x0, y0), (x1, y2), ..., (xn-1, yn-1)}
    #     x \in R^d
    #     y \in R
    #
    # n: number of training samples
    # d: dimension of x, i.e. x \in R^d
    # phi: feature map R^d -> R^m
    # m: dimension of feature space

    # size of features and feature space
    m, d, = 8, 9

    # number of samples (this is where the trouble is!)
    # 64: works
    # 65: reproduces the strange behavior
    n = 64

    # any feature mapping will do -- why not a random one
    np.random.seed(0) # reproducibility
    phi = np.random.normal(0, 1, size=(m, d))

    # we are omnipotent, so we get to know what the truth is
    w_true = np.random.randn(m)

    # any features will do
    x = np.random.normal(0, 1, size=(d, n))

    # corresponding measurements -- with a little spice
    y = w_true @ (phi @ x) + np.random.normal(0, 1e-5, size=n)

    # construct the problem
    c = np.ones(m+n)
    c[:m] = 0
    A_ub = lil_matrix((2*n, n+m))
    idx = 0
    for ii in range(n):
        A_ub[idx, :m] = phi @ x[:, ii]
        A_ub[idx, m+ii] = -1
        A_ub[idx+1, :m] = -1*phi @ x[:, ii]
        A_ub[idx+1, m+ii] = -1
        idx += 2
    A_ub = A_ub.tocsc()
    b_ub = np.zeros(2*n)
    b_ub[0::2] = y
    b_ub[1::2] = -y
    bnds = [(None, None)]*m + [(0, None)]*n

    # solve
    res = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=bnds, method='highs')

    # did strange things happen?
    if res.x is None and res.success:
        raise ValueError('Strange things are the foot')

    # check
    assert np.allclose(res.x[:m], w_true, atol=1e-5)
    print('We did it!')
```

**Comment by mckib2** [comment]
Update: using the HiGHS standalone solver, the LAD regression problem doesn't show the warning about model and scaled model status difference, so it appears to be an issue with how the problem is passed through by the Cython bindings

**Comment by mckib2** [comment]
@kalvdans I have a fix coming (see #13626) but it's currently blocked by an [upstream bug](url).  In the meantime, try running your model with the `'disp': True` option to see if it gives you some hints about primal/dual feasibility tolerance adjustments.  Tightening those tolerances removes the scaled/unscaled model status warning and might help give you a solution for dual simplex

**Comment by odow** [comment]
> I don't think I ever expected to see (model_status != scaled_model_status

This happens surprisingly frequently in solvers. 

CPLEX has a great status [`CPX_STAT_OPTIMAL_INFEAS`](https://www.ibm.com/support/knowledgecenter/SSSA5P_20.1.0/ilog.odms.cplex.help/refcallablelibrary/macros/CPX_STAT_OPTIMAL_INFEAS.html), which means it found an optimal solution to the scaled model, but that the solution was infeasible in the unscaled model, and CPLEX could not repair the solution to feasibility. I guess HiGHS is doing something similar here as well.

**Comment by mckib2** [comment]
> CPLEX has a great status CPX_STAT_OPTIMAL_INFEAS, which means it found an optimal solution to the scaled model, but that the solution was infeasible in the unscaled model, and CPLEX could not repair the solution to feasibility. I guess HiGHS is doing something similar here as well.

Thanks for pointing this out.  This is certainly a case that we can easily catch and might be worth creating a new `linprog` status code for -- thoughts @mdhaber ?

**Comment by mdhaber** [comment]
We have a catch-all code 4 which, in the rendered documentation, says "numerical difficulties encountered". It is the code that @kalvdans would have received along with the error message. It's also used for all the solvers when we do a sanity check of the "optimal" solution and find that it doesn't satisfy the constraints. I think it's reasonable to provide a more specific error message, but I'm not sure if we want a new status code (unless we want to get more specific with status codes in general).

**Comment by mckib2** [comment]
Yep, that makes sense @mdhaber, no new status code needed.  In the PR I have provided a (hopefully) more useful message when this case does occur

**Comment by mdhaber** [comment]
@kalvdans our computers have trouble with your large test case. Are you able to build the branch in gh-13626 and check that it resolves your original problem?

**Comment by kalvdans** [comment]
I built it with `pip install git+https://github.com/scipy/scipy.git@refs/pull/13626/head`
and my testcase resulted in:

> An optimal solution to the scaled model was found but was HiGHS Status Code 0: HighsModelStatusNOTSET in the unscaled model. For more information run with the option `disp: True`.

I could not reproduce the issue with https://github.com/scipy/scipy/issues/13610#issuecomment-785620302 , neither before nor after upgrading scipy.

**Comment by mdhaber** [comment]
> my testcase resulted in

Thanks! That is the intent for now, until HiGHS changes something upstream. Your status code will be `4`, but now you get the solution HiGHS found as `res.x`, which should essentially be a correct solution; the unscaled solution just doesn't satisfy HiGHS' tolerances. If you run with option `'disp': True`, HiGHS recommends how the tolerance can be changed to get a solution that should satisfy the unscaled problem, too. (That's my understanding - right @mckib2)?

> I could not reproduce the issue with #13610 (comment)

Nor could I, but the unit test @mckib2 added was a little different. I was able to reproduce the issue with that unit test code in master, and the PR fixes it.

I understand that it would be preferable if HiGHS would report normal status code with default tolerances, but until then, this gives you access to the solution and more information about how to coax HiGHS toward successful exit status. Does that resolve the issue from your perspective?

**Comment by kalvdans** [comment]
> Does that resolve the issue from your perspective?

More than so :) Thanks a lot for your devotion to this project and explaining the details of the solvers to newcomers.

**Comment by mckib2** [comment]
> HiGHS recommends how the tolerance options can be changed to get a solution that should result in status 0

Correct!  Example below.

> Nor could I, but the unit test @mckib2 added was a little different. I was able to reproduce the issue with that unit test code in master, and the PR fixes it.

To get the model mismatch, change the `n` parameter in the code to > 64.  For example, running with `n = 100` and `disp: True` I get the following:
```
Presolve : Reductions: rows 200(-0); columns 108(-0); elements 1800(-0) - Not reduced
INFO   : Problem not reduced by presolve: solving the LP
INFO   : Scaling: Improvement factor is 20.08 >= 1 so scale LP
INFO   : Basis condition estimate of           1 is within the tolerance of 1e+14
WARNING: Number of OMP threads available = 0 < 1 = Number of HiGHS threads to be used: Parallel performance will be less than anticipated
INFO   : Using dual simplex solver - serial
       Iteration        Objective     Infeasibilities num(sum)
DuPh2          0     0.0000000000e+00 Pr: 100(302.503); Du: 0(7.40104e-11)
DuPh2         50     3.6502310104e-04 Pr: 84(0.000733159)
DuPh2        100     6.0745428311e-04 Pr: 57(0.000454163)
DuPh2        126     6.5491771695e-04 Pr: 0(6.856e-08)
DuPh2        126     6.5491690978e-04 Pr: 0(6.856e-08)
INFO   : Dual simplex iterations [Ph1 0; Ph2 126; Pr 0] Total 126
INFO   : Have 1 primal and 0 dual unscaled infeasibilities
INFO   : Possibly re-solve with feasibility tolerances of 5e-08 primal and 1e-07 dual
INFO   : Not re-solving with refined tolerances
Postsolve  : 
Time       :     0.00
Time Pre   :     0.00
Time PreLP :    -1.00
Time PostLP:     0.00
For LP                 : Presolve     0.00 (  3%): Solve original LP     0.00 ( 95%)
/home/nicholas/Documents/scipy/scipy/optimize/_linprog_highs.py:325: OptimizeWarning: model_status is not optimal, using scaled_model_status instead.
  res = _highs_wrapper(c, A.indptr, A.indices, A.data, lhs, rhs,
           con: None
 crossover_nit: 0
           fun: None
       message: 'The solver did not provide a solution nor did it report a failure. Please submit a bug report.'
           nit: 126
         slack: None
        status: 4
       success: False
             x: None
Traceback (most recent call last):
  File "test_lap.py", line 69, in <module>
    raise ValueError('Strange things are the foot')
ValueError: Strange things are the foot
```

Notice the line in HiGHS INFO log where it recommends:
```
INFO   : Possibly re-solve with feasibility tolerances of 5e-08 primal and 1e-07 dual
```

Setting the options:
```python
options = {
        'primal_feasibility_tolerance': 5e-8,
        'dual_feasibility_tolerance': 1e-7,
}
```
solves the model to optimality with a status code of `0`.

**Comment by Michael-git96** [comment]
> 
> Notice the line in HiGHS INFO log where it recommends:
> 
> ```
> INFO   : Possibly re-solve with feasibility tolerances of 5e-08 primal and 1e-07 dual
> ```
> 
> Setting the options:
> 
> ```python
> options = {
>     'primal_feasibility_tolerance': 5e-8,
>     'dual_feasibility_tolerance': 1e-7,
> }
> ```
> 
> solves the model to optimality with a status code of `0`.

@mdhaber - Is there a way to grab the suggested tolerances and rerun the optimization with those suggested feasibility tolerances? 

I also noticed some strange behaviour a few days ago where I was running an LP with primal and dual infeasibility tolerances set to 1e-7, and I saw that it suggested a dual tolerance of 1e-7 and a primal tolerance of 2.5e-8. When I changed the tolerances to the suggested ones, then the status was optimal. I thought that was quite odd considering that the suggested primal tolerance was smaller than the original one. Do you have any idea why that may happen?

**Comment by mdhaber** [comment]
> Is there a way to grab the suggested tolerances and rerun the optimization with those suggested feasibility tolerances?

Yes, it's possible, but what would trigger the re-run? (What is the interface you have in mind? There's not an obvious UI that I like.)

> I also noticed some strange behaviour a few days ago...

The suggested primal tolerance in your example is ` 2.5e-8` whereas in the example you quoted it was `5e-8`; otherwise, these situations seem identical. To make sure I understand the question, are you just asking why this behavior happens in general, or is there something different about the case you're describing?

**Comment by Michael-git96** [comment]
@mdhaber - thank you for your reply. 

> Yes, it's possible, but what would trigger the re-run? (What is the interface you have in mind? There's not an obvious UI that I like.)
I thought of possibly having a boolean constraint e.g. feas_tol_rerun = True within the options dictionary of scipy linprog, which would automatically adjust the feasibility tolerances, raise a warning specifying what the new tolerances are and rerun the optimisation.

 I think I may not have explained the behaviour I was noticing properly. I ran an LP and set:
primal tol = 1e-7
dual tol = 1e-7

The HiGHS solver scaled the problem and returned res['status']=MODEL_STATUS_OPTIMAL and res['unscaled_status']=MODEL_STATUS_NOTSET . So from my understanding from the conversation above, this means it found an optimal solution to the scaled problem but when converted back to the original problem it was suboptimal/infeasible. I could also see that it had suggested a dual tol of 1e-7 and a primal tol of 2.5e-8 . When I ran the problem with these new tolerances, the res['status'] and res['unscaled_status'] were both MODEL_STATUS_OPTIMAL.

My question was: Why would it return optimal for a tighter primal tol (2.5e-8 as opposed to 1e-7) ?

I hope my comment is a little clearer now.

**Comment by Michael-git96** [comment]
@mdhaber - I would be happy to contribute and submit a pull request for the feas_tol_rerun parameter if you think it is a good idea?

I think my question regarding the feasible tolerances I used and the ones suggested may be better directed to the HiGHS solvers authors.

**Comment by mdhaber** [comment]
> I think I may not have explained the behaviour I was noticing properly. I ran an LP and set:
primal tol = 1e-7
dual tol = 1e-7

Assuming these are `primal_feasibility_tolerance` and `dual_feasibility_tolerance`, just note that these are the default values. So there is not really a difference between this observation and what @mckib2 mentioned above

As to why, yes, it may be better directed to the HiGHS authors. I agree that it seems counter-intuitive at first, but depending on how the tolerances are used, I can imagine reasonable scenarios in which it makes sense. For instance, in the `interior-point` algorithm, `tol` is used for several different termination criteria. The values being compared against `tol` don't necessarily drop in a very regular way with each iteration. It may be that for one value of `tol`, one criterion is the first to be satisfied, whereas for a lower value of `tol`, a different criterion is the first to be satisfied, and this would lead to a different status message. I'm not sure exactly what is going on in HiGHS, but I can imagine a scenario like this.

Personally, I would not be interested in `feas_tol_rerun`. There are many options like this that we could consider adding to `linprog` for use in very particular scenarios, but I think good UI design balances the simplicity of the interface against the simplicity of achieving a given task (assuming knowledge of that interface). I'm not sure that the use case justifies the addition of an option like this when a few extra keystrokes gives the same result with the existing interface. But perhaps others may be interested.

**Comment by Michael-git96** [comment]
@mdhaber - thank you for your reply. I do agree that adding a parameter like `feas_tol_rerun` counteracts the simplicity of the interface. The reason I was looking into this was because I was running several LPs and going through the output (when disp=True) manually was quite tedious.

Is there a way to actually grab the output when disp=True as a string? I took a look at this solution in StackOverflow: https://stackoverflow.com/questions/1218933/can-i-redirect-the-stdout-into-some-sort-of-string-buffer , however I am unable to get it to work and I suspect it is because the information is not printed in python using print() but rather in C++.
