### ISSUE TITLE
AttributeError module scipy has no attribute stats 

### ISSUE THREAD

**Issue by VanBantam** [scipy/scipy#13618]
My issue is about an attribute error when calling scipy.stats.

#### Reproducing code example:

```
import scipy
print(scipy.stats.describe([i for i in range(10)]))
```

#### Error message:

```
Traceback (most recent call last):
  File "problem.py", line 2, in <module>
    print(scipy.stats.describe([i for i in range(10)]))
AttributeError: module 'scipy' has no attribute 'stats'
```

#### Scipy/Numpy/Python version information:

```
1.6.1 1.20.1 sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)
```

#### Notes:
The same behavior occurs when installing scipy 1.6.1 from pip and from anaconda.

**Comment by rkern** [comment]
This is expected. Most of the subpackages are not imported when you just do `import scipy`. There are a lot of them, with a lot of heavy extension modules that take time to load. You should always explicitly import the subpackages that you want to use:

```python
from scipy import stats

stats.describe(...)
```

**Comment by VanBantam** [comment]
This makes a lot of sense.  Closing issue because it is not an issue.
