### ISSUE TITLE
no correlation_lags member

### ISSUE THREAD

**Issue by Eefried** [scipy/scipy#13635]
Hello,

I'm still struggling to get access to that function. On the RPi the problem is the old scipy version, and there is no way to get round this problem, all tips failed. But the error pertains also with the W10 machine. Pylint claims that the correlation_lags is no member of scipy.signal.
I'm pretty sure that there is  something wrong with the rollout of scipy- covering also anaconda.
please improve
many thanks

**Comment by ilayn** [comment]
Can you explain your problem in generic terms? You have to import `scipy.signal` first. Otherwise you cannot directly call `scipy.signal.correlation_lags(...)`

**Comment by rgommers** [comment]
No follow-up, so closing.
