### ISSUE TITLE
stats.rv_discrete is not checking that xk values are integers

### ISSUE THREAD

**Issue by Gabriel-p** [scipy/scipy#13632]
[`scipy.stats.rv_discrete`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_discrete.html) requires that the `x` input for the `values` parameters are integers:

> values : tuple of two array_like, optional
(xk, pk) **where xk are integers** and pk are the non-zero probabilities between 0 and 1 with sum(pk) = 1. xk and pk must have the same shape.

#### Reproducing code example:

The example code:
```
from scipy import stats
xk = np.arange(7)
pk = (0.1, 0.2, 0.3, 0.1, 0.1, 0.0, 0.2)
custm = stats.rv_discrete(name='custm', values=(xk, pk))

import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 1)
ax.plot(xk, custm.pmf(xk), 'ro', ms=12, mec='r')
ax.vlines(xk, 0, custm.pmf(xk), colors='r', lw=4)
plt.show()
```

returns

![](https://docs.scipy.org/doc/scipy/_images/scipy-stats-rv_discrete-1_00_00.png)

but if I change to `xk = np.linspace(1., 6.9, 7)` I get:

![Captura de pantalla de 2021-03-01 10-52-59](https://user-images.githubusercontent.com/6054951/109506871-e61b1500-7a7c-11eb-9eae-7279f56399f5.png)

This is a user error with a silent fail. There should be a validation or at least a warning shown.

#### Scipy/Numpy/Python version information:

```
1.6.1 1.19.2 sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)
```

**Comment by tupui** [comment]
Thanks @Gabriel-p, would you do a PR to fix this?

**Comment by mdhaber** [comment]
See gh-2414.

**Comment by Gabriel-p** [comment]
Thanks for that link @mdhaber. I also wonder what (if anything) would be in need of fixing here. I tested reproducing a PDF I got from the literature and I can sample it perfectly using floats in `xk`:

```
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

xk = np.arange(0.05, 1.01, 0.1)
pk = np.array([
    0.07320166320166316, 0.0811413721413721, 0.0924109494109494,
    0.08995495495495492, 0.07918849618849616, 0.07049757449757446,
    0.07344906444906443, 0.08970755370755368, 0.11137075537075536,
    0.24156202356202355])
pk /= pk.sum()
fq = stats.rv_discrete(values=(xk, pk))
dist = fq.ppf(np.random.uniform(0., 1., 100000))
weights = np.ones_like(dist) / len(dist)
plt.hist(dist, histtype='step', weights=weights)
plt.show()
```

![zzzz](https://user-images.githubusercontent.com/6054951/109518712-4617b880-7a89-11eb-8357-ed62653dea68.png)

Is there anything not working here?

**Comment by mdhaber** [comment]
I'm not sure. But i can see where the confusion is from if the docs say that xk must be integers, so at least those could be clarified.

**Comment by tupui** [comment]
The `ppf` is working correctly but seems like `pmf` is troubled.

**Comment by mdhaber** [comment]
@tupui It seems OK to remove that there, as it's not really consistent to check only in `_pmf`. 

But please also see gh-2414; I'll ping you there, too.

**Comment by josef-pkt** [comment]
AFAIR (more than 10 years ago),
 rv_discrete has or had code in several places that assumes support on integers.
I tried to use the (xk, pk) rv_discrete for arbitrary points and for equal spaced, but non-integer grid on the real line, and that broke or produced incorrect results in several methods.

So, integer valued  xk is or was a requirement to not get incorrect results in some methods.

(i haven't looked at this in a very long time)

**Comment by mdhaber** [comment]
@josef-pkt Right. In gh-2414 I'm suggesting that we deprecate calling the distributions with non-integer values of arguments that are supposed to be integer. In the future, we could make the result `nan` or raise an error.

**Comment by mdhaber** [comment]
After reading this and gh-3758, it is more clear that they are duplicates. Let's close this and continue in gh-3758.
