### ISSUE TITLE
Sparse matrix argmax() integer overflow on Windows 10

### ISSUE THREAD

**Issue by jeffbinder** [scipy/scipy#13646]
When running on Windows 10, the sparse.csc_matrix.argmax() function can silently overflow the int data type and return the wrong value with sufficiently large matrices. This issue does not occur on Linux.

#### Reproducing code example:

```
import numpy
from scipy import sparse

dim = (100000, 100000)
mat = sparse.lil_matrix(dim)
mat[99998, 99998] = 1
mat = sparse.csc_matrix(mat)

idx = mat.argmax()
idx_unravelled = numpy.unravel_index(idx, dim)

print(idx_unravelled)
print(mat[idx_unravelled])
print(mat[99998, 99998])
```

Expected output:

```
(99998, 99998)
1.0
1.0
```

Actual output:

```
(14099, 65406)
0.0
1.0
```

Workaround:

```
maxval = mat.max()
if idx < 0:
    idx += 1 << 32
idx_unravelled = numpy.unravel_index(idx, dim)
while mat[idx_unravelled] < maxval:
    idx += 1 << 32
    idx_unravelled = numpy.unravel_index(idx, dim)

print(idx_unravelled)
print(mat[idx_unravelled])
```

#### Scipy/Numpy/Python version information:
```
1.6.1 1.18.4 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
```

Again, I am only having this problem on Windows. The same code runs with SciPy 1.6.1 on Ubuntu 20.04 with no problem.

**Comment by mckib2** [comment]
I was able to reproduce this error with the following test on Windows:
```python
def test_argmax_overflow():
    dim = (100000, 100000)
    A = lil_matrix(dim)
    A[-2, -2] = 42
    A = csc_matrix(A)
    with pytest.warns(RuntimeError):
        idx = np.unravel_index(A.argmax(), dim)
    assert A[idx] == A[-2, -2]
```
Although as shown in the test, I am also getting a `RuntimeWarning: overflow encountered in int_scalars`, so this doesn't "silently" fail.  @jeffbinder do you not get this warning message?

**Comment by mckib2** [comment]
The fix appears to be to cast a couple C integral types to Python `int` types to gracefully overcome the overflow, I'll open a PR

**Comment by jeffbinder** [comment]
@mckib2 Yes, I am getting the warning. By "silently" I meant that the method returned an incorrect value rather than raising an exception. Sorry for the confusion.
