### ISSUE TITLE
Documentation wrong in scipy.linalg.eigvalsh

### ISSUE THREAD

**Issue by loftusa** [scipy/scipy#13651]
https://github.com/scipy/scipy/blob/v1.6.1/scipy/linalg/decomp.py#L901

`eigvalsh` takes different parameters than what are described in the "Parameters" section. For instance, `eigvals_only` is listed as a parameter in the docstring, but is not a parameter of the function.

**Comment by ilayn** [comment]
🤦
Thanks @loftusa! Care to send a PR to remove that parameter from the docstring?

**Comment by loftusa** [comment]
@ilayn sure! See #13652.
