### ISSUE TITLE
MAINT: stats.rv_generic: `moment` method falls back to `_munp` unnecessarily

### ISSUE THREAD

**Issue by alcrene** [scipy/scipy#13655]
In `rv_generic`, the `moment` method attempts to use the distribution-specific moment method `_stats` for efficiency and accuracy. However, sometimes even if it calls `_stats`, it ends up calling the generic moment method `_munp` unnecessarily. Here is the relevant excerpt from `moment`:

https://github.com/scipy/scipy/blob/b8fcb788733e0d31a6f85a68437f0b78624c199c/scipy/stats/_distn_infrastructure.py#L1391-L1398

In line 1392 and 1393, we see that if 
* the distribution's `_stats` method has the parameter named `moments` (`if self._stats_has_moments`) and
* the order `n == 4`, then

only the variance (`'v'`) and kurtosis (`'k'`) are computed in the call to `_stats` (line 1396). The rest will be `None`.

However, the function `_moment_from_stats` (called on line 1398) requires all four statistics to compute this moment:

https://github.com/scipy/scipy/blob/b8fcb788733e0d31a6f85a68437f0b78624c199c/scipy/stats/_distn_infrastructure.py#L385-L391

Note in line 386 that if any of the four moments are `None`, `moment_func` (which is always the generic noncentral moment method `_munp`) gets called in line 387.

So with `n == 4`, the call to `_stats` may be performed, but since the mean and skew are `None`, `self._munp` ends up getting called anyway.

It seems that the obvious fix is to compute all four moments in the call to `_stats` in line 1394:
```python3
      mdict = {'moments': {1: 'm', 2: 'v', 3: 'vs', 4: 'mvsk'}[n]}
```

**Comment by mdhaber** [comment]
I haven't looked at the code for this specifically, but this seems consistent with the sort of things that happen in `_distn_infrastructure`. PR welcome, I think!

**Comment by mdhaber** [comment]
@alcrene thanks for your patience on this. Coincidently, I find myself addressing it on the one-year anniversary. Your post was spot-on, but I'm going to make some very light edits to help the reviewer of my PR. Thanks for this!
