### ISSUE TITLE
BUG: gamma distribution's inverse survival function overflows for very small input

### ISSUE THREAD

**Issue by zoj613** [scipy/scipy#13664]
`gamma.isf` overflows when `q` is small

#### Reproducing code example:
```ipynb
In [41]: gamma.isf(1e-17, 0.864)
Out[41]: inf

In [42]: gamma.isf(1e-17, 1)
Out[42]: inf

In [43]: gamma.isf(1e-17, 5)
Out[43]: inf

In [44]: gamma.isf(1e-17, 100)
Out[44]: inf
```

By comparison, this is the correct output produced by R:
```R
> qgamma(1e-17, 0.864, lower.tail=FALSE)
[1] 38.54902
> qgamma(1e-17, 1, lower.tail=FALSE)
[1] 39.14395
> qgamma(1e-17, 5, lower.tail=FALSE)
[1] 51.83694
> qgamma(1e-17, 100, lower.tail=FALSE)
[1] 210.006

```

I discovered this because it became a blocker in a PR i'm working on for improving the `invgauss` distribution.

#### Scipy/Numpy/Python version information:
```
1.7.0.dev0+f551178 1.20.1 sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)

```

**Comment by mdhaber** [comment]
@zoj613 does it look like there is an easy fix?
If not, maybe Boost does better, in which case we could use it after gh-13328 merges.

**Comment by zoj613** [comment]
It looks like there is no direct implementation for `gamma.isf` method in the gamma_gen class : https://github.com/scipy/scipy/blob/9ebe12790b6a683669916a55fbf8e35deee93e0b/scipy/stats/_continuous_distns.py#L2627-L2745

**Comment by rlucas7** [comment]
The gamma distribution contains calls to scipy.special where there is overlap between probability functions (cdf,pdf,etc) and special functions. 

Most of the special functions used in stats come from cephes fork at the moment. 

I’m not clear what isf refers to, could you elaborate? 

-L

**Comment by zoj613** [comment]
@rlucas7 `isf` is the inverse of the survival function. The right tail quantile function of the gamma distribution.

**Comment by rlucas7** [comment]
> @rlucas7 `isf` is the inverse of the survival function. The right tail quantile function of the gamma distribution.

Ah right, so I don't think that one is in cephes so I'm guessing we fall back to this:

https://github.com/scipy/scipy/blob/9ebe12790b6a683669916a55fbf8e35deee93e0b/scipy/stats/_distn_infrastructure.py#L1019

that is in `rv_generic` and it does not look like there is anything in `rv_continuous`:

https://github.com/scipy/scipy/blob/master/scipy/stats/_distn_infrastructure.py#L1492

**Comment by zoj613** [comment]
Yes, there doesn't appear to be a function implementing it specifically for the gamma distribution, and as far as im aware there is no corresponding special function for it in the cephes library. I linked a paper in this thread that has an algorithm for the `isf` function. I believe scipy already has the required functions in place for making its implementation painless should someone be willing to contribute.

**Comment by josef-pkt** [comment]
does this help

```
p = [0.5, 1e-10, 1e-15, 1e-20, 1e-50] 
stats.gamma.isf(p, 2), special.gammainccinv(2, p)
(array([ 1.67834699, 26.33398152, 38.20846876,         inf,         inf]),
 array([  1.67834699,  26.33398161,  38.20764823,  49.98319799,
        119.92442038]))
```

**Comment by zoj613** [comment]
> does this help
> 
> ```
> p = [0.5, 1e-10, 1e-15, 1e-20, 1e-50] 
> stats.gamma.isf(p, 2), special.gammainccinv(2, p)
> (array([ 1.67834699, 26.33398152, 38.20846876,         inf,         inf]),
>  array([  1.67834699,  26.33398161,  38.20764823,  49.98319799,
>         119.92442038]))
> ```

It does! I had no idea no idea those inverse functions existed in scipy. Thank you. I wonder why they aren't used to compute the `isf` and `ppf` of the distribution.

**Comment by zoj613** [comment]
I submitted a fix at https://github.com/scipy/scipy/pull/13684
