### ISSUE TITLE
Add a physical unit conversion module

### ISSUE THREAD

**Issue by Marathon2112** [scipy/scipy#13660]
Is there any interest in adding a module providing physical unit conversions? SciPy already implements the ``convert_temperature``, ``lambda2nu``, and ``nu2lambda`` methods, but this could be extended to a larger class of quantities.

I have been working on [Qty](https://gitlab.com/jdesch/qty), a module making use of Python descriptors to easily set and get quantities in a wealth of units. Additionally, the module includes a class factory to generate prefixed descriptors (using SI prefixes).

I would be happy to contribute to SciPy if adding a similar functionality is of interest.

**Comment by rkern** [comment]
I don't think we intend to expand the unit-conversion code within `scipy`. There are a number of packages out there with different approaches with their own sets of tradeoffs. No one of them has settled to be the one obvious way to do it, so independent packages is probably for the best right now.

It's possible that some of the work going on in `numpy` with respect to custom dtypes and array-like interfaces might eventually make one approach or another dominant, but I think it's still early.
