### ISSUE TITLE
incorporate sklearn's cdist

### ISSUE THREAD

**Issue by GalAvineri** [scipy/scipy#13672]
In [sklearn's website](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise_distances.html#sklearn.metrics.pairwise_distances) they claim that their cdist calculation for some metrics is faster than scipy's.

I've tested this with the following:

```python
from scipy.spatial.distance import cdist
from sklearn.metrics import pairwise_distances
import numpy as np
from time import time

xA = np.random.randn(500, 1000)
xB = np.random.randn(400, 1000)


def assert_equal():
    d1 = cdist(xA, xB)
    d2 = pairwise_distances(xA, xB)
    assert d1.shape == d2.shape
    assert np.allclose(d1, d2)


def test_times():
    s1 = time()
    cdist(xA, xB)
    t1 = time() - s1

    s2 = time()
    pairwise_distances(xA, xB)
    t2 = time() - s2
    print("scipy's cdist: ", t1)
    print("sklearn's cdist: ", t2)


assert_equal()
test_times()
```
the results are:
```
scipy's cdist:  0.10004925727844238
sklearn's cdist:  0.0070781707763671875
```
Indeed it seems that sklearn's implementation is faster.

Should the implementation be replaced with sklearn's implementation than?

**Comment by peterbell10** [comment]
There is scope for improving performance, but I don't think sklearn's approach is good here for the same reasons mentioned in https://github.com/scipy/scipy/issues/12570#issuecomment-791041213. Namely: `X*X - 2 * X*Y + Y*Y` while mathematically equivalent, doesn't give as much precision as `(X-Y)**2`.

**Comment by tupui** [comment]
@peterbell10 I propose to close this one thanks to your recent drastic improvements. What do you think?

**Comment by peterbell10** [comment]
The really drastic improvements from my recent PR was mainly for weighted distances. For the example in this issue,  `cdist` is still around 10x slower than `sklearn`.  That said, I notice that for lower dimensional input (e.g 3d data) `cdist` is actually faster than `sklearn`'s `pairwise_distances`. I also think my precision concerns of `sklearn`'s approach are genuine, so for those reasons I'll close the issue.

**Comment by tupui** [comment]
Great thanks!
