### ISSUE TITLE
Wilcoxon does not appropriately detect ties when mode=exact.

### ISSUE THREAD

**Issue by jreynolds01** [scipy/scipy#13689]
My issue is about `stats.wilcoxon()`. `stats.wilcoxon` detects when d== 0, and appropriately warns that 'exact' will not work under such a circumstance. However, it reports that this is because of 'ties', and not because of the presence of 0s. 

Exact calculations will also not be accurate when there are ties in rank, but the function does not appropriately detect such scenarios.

R produces appropriate warnings in both circumstances

```
wilcox.test(0:4)

	Wilcoxon signed rank test with continuity correction

data:  0:4
V = 10, p-value = 0.1003
alternative hypothesis: true location is not equal to 0

Warning message:
In wilcox.test.default(0:4) : cannot compute exact p-value with zeroes
> wilcox.test(c(1,1:4))

	Wilcoxon signed rank test with continuity correction

data:  c(1, 1:4)
V = 15, p-value = 0.05791
alternative hypothesis: true location is not equal to 0

Warning message:
In wilcox.test.default(c(1, 1:4)) : cannot compute exact p-value with ties
```

#### Reproducing code example:

```
>>> from scipy import stats as stats
>>> x = [1, 1, 2, 3, 4]
>>> stats.wilcoxon(x, correction=True, mode='exact') ## should produce a warning similar to R and should fall back to approx
WilcoxonResult(statistic=0.0, pvalue=0.0625)
>>> stats.wilcoxon(x, correction=True, mode='approx')
/home/jrr/miniconda3/lib/python3.8/site-packages/scipy/stats/morestats.py:2981: UserWarning: Sample size too small for normal approximation.
  warnings.warn("Sample size too small for normal approximation.")
WilcoxonResult(statistic=0.0, pvalue=0.05790726541729728)
>>> x = [0, 1, 2, 3, 4]
>>> stats.wilcoxon(x, correction=True) ## warns, but calls ties.
/home/jrr/miniconda3/lib/python3.8/site-packages/scipy/stats/morestats.py:2967: UserWarning: Exact p-value calculation does not work if there are ties. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
WilcoxonResult(statistic=0.0, pvalue=0.10034824646229075)
```

#### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)

1.6.1 1.19.2 sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)
```

**Comment by chrisb83** [comment]
Thanks for reporting this. 

I think the reason to say that `d == 0` means that there are ties is that x_i = y_i for some i, i.e. you have ties in the pooled sample. maybe it is better to say `Exact p-value calculation does not work if there are zeros in d = x - y`.

If there are ties in d, you are right that this is a problem. In the worst case, if `y = x + const`, d only has a single unique value. Would you know if the exact calculation return a conservative p-value in that case? Otherwise one should raise a warning and switch to asymp.

**Comment by mdhaber** [comment]
@chrisb83 please see previous reply to this in gh-13690. I don't see a problem with ties in `d`, except potentially an edge case like you mention - can you explain how that a tie in `d` is a problem?
Is there anything else in that reply that you disagree with?

**Comment by chrisb83** [comment]
Thanks, I read your comment and I agree with your assessment: if it is recommended to treat non-zero ties in the book you mentioned, maybe the current implementation works fine in practice (+there is no guarantee that the normal approximation is better). For example, in the extreme case `y = x + c`, the p-value tends to be very small and maybe the p-value is indeed conservative. From a theoretical point of view, the independence assumption of x and y is violated in that case.

**Comment by mdhaber** [comment]
Thanks @chrisb83!
@jreynolds01 what do you think? If you agree, maybe gh-13690 should just improve the existing error message a bit to avoid future confusion, but not really change behavior. Of course, if you would be interested in extending the method I started [here](https://github.com/scipy/scipy/pull/13438#pullrequestreview-577009696) to calculate the null distribution considering ties, that would be even better!

**Comment by mdhaber** [comment]
The desired enhancement is to have the ability to consider ties in the `wilcoxon` exact p-value calculation. In the meantime, there is `permutation_test` (although I need to add something there to try to correct for numerically distinct but theoretically identical values in the null distribution).

**Comment by mdhaber** [comment]
To close this issue, we at least need to correct the documentation. At a minimum, we need to clearly distinguish between ties and zeros in the documentation and describe what happens in each case.

Shall I add options for performing the `permutation_test` in case of ties and zeros? If so, what should the interface be? That is under what circumstances (user-specified `method`, presence of ties, presence of zeros) should it kick in? If there are too many possible combinations for a truly exact permutation test (with ties), how would the user control `n_resamples` for a randomized test?
