### ISSUE TITLE
About the  scipy.stats.ttest_1samp() results, and why?

### ISSUE THREAD

**Issue by zengqing1** [scipy/scipy#13709]
When I used the scipy.stats.ttest_1samp() for one sample t test , I got some error results. The ttest_1samp() function got t=1.22. But when I used the t test one sample formula directly, I got t=1.29. And I can not find why it was .

Reproducing code example:
```
import numpy as np
import scipy.stats as sts

x = 3.59,2.66,3.89,2.23,1.61,2.94,1.96,3.68,1.54,2.59

sts.ttest_1samp(x, popmean=3)
#Ttest_1sampResult(statistic=-1.2285981915148954, pvalue=0.2503790104923504)

#use the t test formula directly to compute
# t= (x-mu)/( std/ sqrt(n) )
(np.mean(x)-3)/np.std(x)*np.sqrt(10)
#-1.2950562047836085

(np.mean(x)-3)/np.std(x， ddof=1)*np.sqrt(10)
#-1.2285981915148954
#(2.669-3)/0.852* np.sqrt(10)
#-1.2285374477884197
```
Supposed I simulated a sample which had known mean=33.5 ，std=1.95, and sample size was n=40. The population mean was 34. ttest_1samp() with simulated data was t=-1.60. But the corrected t value was -1.62.

```
y = sts.zscore( np.arange(0,40) ) *1.95 +33.5
np.mean(y),np.std(y)
#(33.5, 1.9499999999999997)

##simulated data
sts.ttest_1samp(y, popmean=34)
#Ttest_1sampResult(statistic=-1.6012815380508716, pvalue=0.11738481140904926)

(np.mean(y)-34)/ np.std(y) *np.sqrt(40) 
#-1.6012815380508718

(np.mean(y)-34)/ np.std(y, ddof=1) *np.sqrt(40) 
#-1.6216808513684
(33.5-34)/1.95*np.sqrt(40)
#-1.6216808513684
```

Scipy/Numpy/Python version information:
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
#1.6.1 1.20.1 sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)

**Comment by matthew-brett** [comment]
Could you say what you were expecting?    Your example shows that, as expected, you get a different answer if you use the `ddof=0` default for `np.std`.

**Comment by zengqing1** [comment]
```
y = sts.zscore( np.arange(0,40) ) *1.95 +33.5
np.mean(y),np.std(y)
np.mean(y),np.std(y, ddof=1)
```

The behavior of numpy  std  was unexpted.  And according the t one sample test formula , the ttest_1samp() results was unexpected.

**Comment by zengqing1** [comment]
```
y = sts.zscore( np.arange(0,40) ) *1.95 +33.5
np.mean(y),np.std(y)
np.mean(y),np.std(y, ddof=1)
```

The behavior of numpy  std  was unexpected.  And according to the t one sample test formula , also the ttest_1samp() results was unexpected.

**Comment by matthew-brett** [comment]
Is this then a bug-report for Numpy?    The `ddof=0` default was quite consciously chosen, but you are welcome to open an issue on Numpy if you think that choice was wrong.

I don't understand why you think the one sample test formula is incorrect, unless you mean that `np.std` has a different meaning from `std` in some other contexts - which would be the same point as above.

**Comment by zengqing1** [comment]
I expected ttest_1samp() be consistent with statistical results, correct and consistent. And according to the t test formula the results sometime was right and another time was wrong.


















At 2021-03-20 23:07:02, "Matthew Brett" ***@***.***> wrote:

Is this then a bug-report for Numpy? The ddof=0 default was quite consciously chosen, but you are welcome to open an issue on Numpy if you think that choice was wrong.

I don't understand why you think the one sample test formula is incorrect, unless you mean that np.std has a different meaning from std in some other contexts - which would be the same point as above.

**Comment by zengqing1** [comment]
The one sample t test  formula is  (sample.mean - mu) / (sample.std / sqrt(sample.n)) , and sample.std should always be  numpy.std(x, ddof=1). 
















At 2021-03-20 23:07:02, "Matthew Brett" ***@***.***> wrote:

Is this then a bug-report for Numpy? The ddof=0 default was quite consciously chosen, but you are welcome to open an issue on Numpy if you think that choice was wrong.

I don't understand why you think the one sample test formula is incorrect, unless you mean that np.std has a different meaning from std in some other contexts - which would be the same point as above.

**Comment by matthew-brett** [comment]
In some of your examples, you're using the wrong `np.std` in the formula, and these give a different result from the one sample t-test - as expected.    I can't see any example where you use the correct invocation for `np.std` and get a different result from the one sample t-test.   Could you post just one calculation, which you think is incorrect, and say why, precisely?

**Comment by zengqing1** [comment]
I dont think it is numpy bug, but the numpy.std option ddof is set to 0 is not in conformity with statistics, it sholud be more appropriate and common to set it to 1.
















At 2021-03-20 23:07:02, "Matthew Brett" ***@***.***> wrote:

Is this then a bug-report for Numpy? The ddof=0 default was quite consciously chosen, but you are welcome to open an issue on Numpy if you think that choice was wrong.

I don't understand why you think the one sample test formula is incorrect, unless you mean that np.std has a different meaning from std in some other contexts - which would be the same point as above.

**Comment by matthew-brett** [comment]
For `np.std` default - there's no point in discussing that here - as that is a Numpy decision.   In general I think you'll find that different people, and different fields, have different expectations as to what `std` should be.     Numpy chose the ddof=0 interpretation.  I doubt you'll persuade them to change at this point.

**Comment by zengqing1** [comment]
The 2nd simulated data example as before results was incorrect . 
```
#mean=1.95, std=33.5, popmean=34
y = sts.zscore( np.arange(0,40) ) *1.95 +33.5


#right ddof but std is incorrect
np.mean(y),np.std(y,ddof=1)


#right std is 1.95, but the ddof should be 1
np.mean(y),np.std(y, ddof=0)


#incorrect answer
sts.ttest_1samp(y, popmean=34)


#right answer
(33.5-34)/1.95*np.sqrt(40)
```


















At 2021-03-20 23:31:26, "Matthew Brett" ***@***.***> wrote:

In some of your examples, you're using the wrong np.std in the formula, and these give a different result from the one sample t-test - as expected. I can't see any example where you use the correct invocation for np.std and get a different result from the one sample t-test. Could you post just one calculation, which you think is incorrect, and say why, precisely?

**Comment by zengqing1** [comment]
I think ,at least, the results in the same statistics with the same data, the test results should be as the anthor software results, for example R or SAS and not anything else.


















At 2021-03-20 23:35:51, "Matthew Brett" ***@***.***> wrote:

For np.std default - there's no point in discussing that here - as that is a Numpy decision. In general I think you'll find that different people, and different fields, have different expectations as to what std should be. Numpy chose the ddof=0 interpretation. I doubt you'll persuade them to change at this point.

**Comment by matthew-brett** [comment]
I think the calculation of `np.std` is what I'd expect:

```
import scipy.stats as sts
y = sts.zscore( np.arange(0,40) ) *1.95 +33.5
```

Now you have a *population* (ddof=0) standard deviation of 1.95 - as expected. 

```
[ins] In [13]: mu = np.mean(y)                                                                                         
[ins] In [14]: n = len(y)
[ins] In [16]: np.std(y)                                                                                               
Out[16]: 1.9499999999999997
[ins] In [17]: np.sqrt(np.sum((y - mu) ** 2) / n)                                                                      
Out[17]: 1.9499999999999997
```

Remember, the one-sample t-test uses the *sample* (ddof=1) standard deviation, so:

```
[ins] In [18]: sts.ttest_1samp(y, popmean=34)                                                                          
Out[18]: Ttest_1sampResult(statistic=-1.6012815380508716, pvalue=0.11738481140904929)
[ins] In [19]: samp_std = np.sqrt(np.sum((y - mu) ** 2) / (n - 1))                                                     
[ins] In [21]: (mu - 34) / samp_std * np.sqrt(n)                                                                       
Out[21]: -1.6012815380508718
```

As far as I can see these are all correct and as expected.  Closing, but please re-open if you think I'm wrong.

**Comment by zengqing1** [comment]
Oh, but the t test  is always for the samples. In my example, the sample mean was 3.5 and sample std was 1.95 , and then sample size n was 40.  It was not a population. I just simulated a sample data.
so according to the t test formula the t=(3.5-4)/( 1.95/sqrt(40))=1.62 and it was not 1.60.  After read you comment, I found the one sample t test formula difference between us. 
mine:  t = (sample.mean - mu) /(sample.std / sqrt(sample.n) ), and sample.std= sqrt ( sum( (x - xbar)*(x-xbar)) /(n-1) )
```
samp_std = np.sqrt( np.sum((y - np.mean(y) ) ** 2) / ( n -1) )
```
your:    t = (sample.mean - mu) /(sample.std / sqrt(sample.n) ), and sample.std= sqrt ( sum( (x - mu)*(x-mu)) /n ) 
```
samp_std = np.sqrt(np.sum((y - mu) ** 2) / (n - 1)) # this is incorrect, mu should be sample mean
```
so the sample.std was  difference . But others stististical software , R ,SAS,SPSS etc , accept mine.






















At 2021-03-20 23:59:44, "Matthew Brett" ***@***.***> wrote:

I think the calculation of np.std is what I'd expect:

import scipy.stats as sts
y = sts.zscore( np.arange(0,40) ) *1.95 +33.5


Now you have a population (ddof=0) standard deviation of 1.95 - as expected.

[ins] In [13]: mu = np.mean(y)                                                                                         
[ins] In [14]: n = len(y)
[ins] In [16]: np.std(y)                                                                                               
Out[16]: 1.9499999999999997
[ins] In [17]: np.sqrt(np.sum((y - mu) ** 2) / n)                                                                      
Out[17]: 1.9499999999999997


Remember, the one-sample t-test uses the sample (ddof=1) standard deviation, so:

[ins] In [18]: sts.ttest_1samp(y, popmean=34)                                                                          
Out[18]: Ttest_1sampResult(statistic=-1.6012815380508716, pvalue=0.11738481140904929)
[ins] In [19]: samp_std = np.sqrt(np.sum((y - mu) ** 2) / (n - 1))                                                     
[ins] In [21]: (mu - 34) / samp_std * np.sqrt(n)                                                                       
Out[21]: -1.6012815380508718


As far as I can see these are all correct and as expected. Closing, but please re-open if you think I'm wrong.
