### ISSUE TITLE
`scipy.stats.mood` does not correct for ties

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#13730]
It seems that `scipy.stats.mood` does not correct for ties. See [discussion](https://github.com/scipy/scipy/pull/13008/files#r599688679) in gh-13008.

#### Reproducing code example:
```python3
from scipy import stats
import numpy as np

x = [111, 107, 100, 99, 102, 106, 109, 108, 104, 99,
     101, 96, 97, 102, 107, 113, 116, 113, 110, 98]
y = [107, 108, 106, 98, 105, 103, 110, 105, 104, 100,
     96, 108, 103, 104, 114, 114, 113, 108, 106, 99]
expected = (1.037127561496, 0.299676411857)  # from R mood.test
res = stats.mood(x, y)
np.testing.assert_allclose(res, expected)
```

#### Error message:

```
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 2 / 2 (100%)
Max absolute difference: 0.04520716
Max relative difference: 0.07194409
 x: array([0.99192 , 0.321236])
 y: array([1.037128, 0.299676])
```

#### Scipy/Numpy/Python version information:
```
1.5.2 1.19.2 sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)
```
But also master.

**Comment by mdhaber** [comment]
@swallan @tirthasheshpatel @swallan This looks like really low-hanging fruit. If one of you could fix this and add the case above as a test, I can review and merge quickly. I think all that is needed is an adjustment to the formula the counts and corrects for the ties:

![image](https://user-images.githubusercontent.com/6570539/113503134-b7151a80-94e4-11eb-963a-250dd77d346d.png)

See [here](https://www.jstor.org/stable/1266427).

**Comment by swallan** [comment]
Working on this and making subtle progress -- thought it's not matching up with the R implementation yet. 

here's a draft PR with the changes in my repo:

https://github.com/swallan/scipy/pull/5

**Comment by mdhaber** [comment]
Sorry. I think that the definition of the test statistic might need to be generalized for ties. It looks like in the paper the statistic definition contains a count of the number of ties, but I don't see that in the implemention. It could be that they're equivalent, but the best way to tell is to re-implement the statistic following the paper exactly.

**Comment by mdhaber** [comment]
For future reference: R and SAS do not agree, and the current SciPy implementation does not agree with either. A Python implementation of the complete statistic (including ties) as described [here](https://www.jstor.org/stable/1266427) agrees with SAS.
