### ISSUE TITLE
The behavior of sparse matrix initialization with bool differs between 1.6.0 and 1.6.1

### ISSUE THREAD

**Issue by yellowshippo** [scipy/scipy#13733]
With scipy 1.6.0, when initializing a sparse matrix with bool values, it generates a matrix with `numpy.bool_`. However, with scipy 1.6.1, it generates `numpy.float64`. Is it an intended change? If so, can we add some description about this in the release notes?

#### Reproducing code example:
```
from scipy import sparse as sp
sp.csr_matrix(([True]*3, ([0, 1, 1], [0, 0, 1]))).toarray()  # The same results with coo_matrix and csc_matrix
```

#### Results with scipy 1.6.0
```
array([[ True, False],
       [ True,  True]])
```

#### Results with scipy 1.6.1
```
array([[1., 0.],
       [1., 1.]])
```

#### Scipy/Numpy/Python version information for scipy1.6.0:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.6.0 1.19.5 sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)
```

#### Scipy/Numpy/Python version information for scipy1.6.1:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.6.1 1.19.5 sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
@yellowshippo, thanks for reporting the issue.  This is a [bug](https://github.com/scipy/scipy/issues/13585) in 1.6.1. The bug has been [fixed](https://github.com/scipy/scipy/pull/13586) in 1.6.2, which is due to be released soon.

**Comment by yellowshippo** [comment]
Thank you for the answer!
