### ISSUE TITLE
brentq can overflow / underflow

### ISSUE THREAD

**Issue by mbaudin47** [scipy/scipy#13737]
According to the source code:

https://github.com/scipy/scipy/blob/5f4c4d802e5a56708d86909af6e5685cd95e6e66/scipy/optimize/Zeros/brentq.c#L67

the brentq algorithm uses the product of two function values to see if the zero is in the bracketing interval.

In 

    Malcolm, Michael A., Cleve B. Moler, and George Elmer Forsythe. 
    Computer methods for mathematical computations. Prentice-Hall, 1977.

we see the following advice:

"Careful attention is paid to underflow and overflow problems. For example, the test to ensure that F(B) and F(C) have different signs is *not* the conventional:

F(B) * F(C) < 0.0

If F(B)=10^-40 and F(C)=10^-40, then they have opposite signs, but on many computers the product will underflow and be set to zero, and the test will fail."

**Comment by tupui** [comment]
Hi, thanks for raising this. Do you have an example we could use to check this?

**Comment by mbaudin47** [comment]
Hi Pamphile !
The following script:
```
import numpy as np
from scipy import optimize
def test_fBaudin1(x):
    y = np.exp(x) - 1.9151695967140057e-174
    return y
a = -450.0
b = -350.0
root = -400.0

root = optimize.brentq(test_fBaudin1, a, b)
print(root)
```
produces:
```
0.0
```
but should print -400. This is the bug.
The following script:
```
def test_fBaudin2(x):
    y = np.exp(x) - 5.221469689764144e+173
    return y
a = 350.0
b = 450.0
root = 400.0
root = optimize.brentq(test_fBaudin2, a, b)
print(root)
```
produces:
```
400.0
```
as expected. This is an "invisible" bug.
Here is a detailed analysis:
* The test 1 is so that f(a) * f(b) = -1.902 × 10^-326. This is represented as the floating point number zero with IEEE754-64bits binary floating point numbers. Hence, the code cannot bracket the root.
* The test 2 is so that f(a) * f(b) = -1.413 × 10^369. This is represented represented as -INF. This is a silent overflow, but does not produce a bug because the arithmetic of infinite numbers is correct.

In both cases, I have chosen numbers which are just over the underflow/overflow threshold, by taking the square root of 10^308 and 10^-308. Then I searched for values of x such that the exponential is larger than that.

The solution is to avoid the product f(a) * f(b), which is unnecessary at this point. The condition:
```
if np.sign(fa) == np.sign(fb):
```
would fit the mathematical requirement (to test if we bracket the root), does not require an unnecessary multiplication and does not produce neither overflow nor underflow.

**Comment by tupui** [comment]
Nice analysis, thank you Michael 👍 . But then would you like to do a PR?

**Comment by mbaudin47** [comment]
Apparently, the same pattern can be found at:
https://github.com/scipy/scipy/blob/5f4c4d802e5a56708d86909af6e5685cd95e6e66/scipy/optimize/Zeros/bisect.c#L17
https://github.com/scipy/scipy/blob/5f4c4d802e5a56708d86909af6e5685cd95e6e66/scipy/optimize/Zeros/bisect.c#L37
https://github.com/scipy/scipy/blob/5f4c4d802e5a56708d86909af6e5685cd95e6e66/scipy/optimize/Zeros/brenth.c#L52
https://github.com/scipy/scipy/blob/5f4c4d802e5a56708d86909af6e5685cd95e6e66/scipy/optimize/Zeros/brenth.c#L67
https://github.com/scipy/scipy/blob/5f4c4d802e5a56708d86909af6e5685cd95e6e66/scipy/optimize/Zeros/ridder.c#L29

Looking at the code more closely, we find some suspicious statements:
https://github.com/scipy/scipy/blob/5f4c4d802e5a56708d86909af6e5685cd95e6e66/scipy/optimize/Zeros/brentq.c#L92
https://github.com/scipy/scipy/blob/5f4c4d802e5a56708d86909af6e5685cd95e6e66/scipy/optimize/Zeros/brentq.c#L98
https://github.com/scipy/scipy/blob/5f4c4d802e5a56708d86909af6e5685cd95e6e66/scipy/optimize/Zeros/brenth.c#L92
https://github.com/scipy/scipy/blob/5f4c4d802e5a56708d86909af6e5685cd95e6e66/scipy/optimize/Zeros/brenth.c#L98
https://github.com/scipy/scipy/blob/5f4c4d802e5a56708d86909af6e5685cd95e6e66/scipy/optimize/Zeros/ridder.c#L48

Previous expressions should be factored so as to avoid underflows/overflows.
Looking at the code in (Malcolm, Moler, Forsythe, 1977), p.165 we read:
```
C Linear interpolation
S = FB / FA
P = 2.0 * XM * S
Q = 1.0 - S
```
You see that the calculation is expressed as a ratio. We cannot have a division by zero, otherwise FA=0 and the problem is solved: the root is A. I do not have a strong argument to prove that this is the right thing to do, but this may require a more in-depth analysis. Anyway, this seems to be worth to analyze.

**Comment by mbaudin47** [comment]
> Nice analysis, thank you Michael +1 . But then would you like to do a PR?

I do not wish to solve the bug by myself, but it would be a pleasure to provide tests, if this can help.

**Comment by mbaudin47** [comment]
Got it. 
Consider the update of the secant method.
The naive update is:
```
b = (fc * b - fb * c) / (fc - fb)
```
The robust implementation is:
```
t = fc / fb
b = b + (b - c) / (t - 1.0)
```
When we use regular numbers such as:
```
b = 1.0
c = 2.0
fb = 3.0
fc = 4.0
```
both codes produce the same result.
But feed them with e.g.:
```
b = 1.e160
c = 2.e160
fb = 1.e160
fc = 2.e160
```
and the naive implementation produces a nan, while the robust one produces a finite number.

**Comment by josef-pkt** [comment]
I didn't look at any details

can you not just compare signs? `np.sign(fpre) * np.sign(fcur) < 0`

**Comment by tupui** [comment]
> I didn't look at any details
> 
> can you not just compare signs? `np.sign(fpre) * np.sign(fcur) < 0`

@josef-pkt I don't know how to do that from the C code. I tried using `signbit` instead of NumPy but it still gives 0. TBH, I don't know anything about C and just tried to apply what I saw here.

**Comment by charris** [comment]
You could try `fpre != 0 && fcur != 0 && signbit(fpre) != signbit(fcur)` which takes care of the signed zero problem.
