### ISSUE TITLE
scipy.interpolate.interp1d has inconsistent behavior for non-unique x-values

### ISSUE THREAD

**Issue by FirefoxMetzger** [scipy/scipy#13744]
When using `scipy.interpolate.interp1d` and specifying the same x-value multiple times the result is undefined, i.e., it depends on the interpolation method used (`kind`), but not in a very predictable way. The result ranges from `np.nan`, through any of the y-values that correspond to the duplicate x-values, to exceptions in the case of quadric and cubic splines.

I guess this is a weird edge case, so maybe it is okay to be inconsistent and not support it at all. This would make a lot of sense to me. In this case, I would like to suggest updating the documentation to something like `x-values must be unique`, potentially paired with an exception if non-unique values are encountered.

Alternatively, one could sanitize the input by merging duplicates, e.g., by computing their mean. That said, I didn't spend a lot of time thinking this option through so it might be unexpected for some interpolation methods.

```python
>>> from scipy.interpolate import interp1d
>>> kinds = ['linear', 'nearest', 'nearest-up', 'zero', 'slinear', 'previous', 'next']
>>> for kind in kinds:
...     print(f"Output for Kind: {kind} \n {interp1d([0, 0, 1], [0, 0.5, 1], kind=kind)(0)}\n----")
... 
Output for Kind: linear 
 nan  # also creates warnings when called outside of f-string
----
Output for Kind: nearest 
 0.0
----
Output for Kind: nearest-up 
 0.5
----
Output for Kind: zero 
 0.5
----
Output for Kind: slinear 
 0.5
----
Output for Kind: previous 
 0.5  # should this not be 0.0 since the previous value should be 0
----
Output for Kind: next 
 0.0 # should this not be 0.5 since the next value is 0.5
----
>>> interp1d([0, 0, 1], [0, 0.5, 1], kind="quadric")(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sebastian/.local/lib/python3.8/site-packages/scipy/interpolate/interpolate.py", line 443, in __init__
    raise NotImplementedError("%s is unsupported: Use fitpack "
NotImplementedError: quadric is unsupported: Use fitpack routines for other types.
>>> interp1d([0, 0, 1], [0, 0.5, 1], kind="cubic")(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sebastian/.local/lib/python3.8/site-packages/scipy/interpolate/interpolate.py", line 546, in __init__
    self._spline = make_interp_spline(xx, yy, k=order,
  File "/home/sebastian/.local/lib/python3.8/site-packages/scipy/interpolate/_bsplines.py", line 788, in make_interp_spline
    raise ValueError("Expect x to not have duplicates")
ValueError: Expect x to not have duplicates
```

**Comment by ev-br** [comment]
The outcome of the previous discussion in

https://github.com/scipy/scipy/pull/9887

Is that the behavior is frozen by backwards compatibility. That said, doc improvement are most welcome! 
I'd be willing to review a doc PR.
