### ISSUE TITLE
different default atol, btol for lsqr, lsmr

### ISSUE THREAD

**Issue by nschloe** [scipy/scipy#13745]
The default `atol` and `btol` for [lsqr](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.lsqr.html) is `1.0e-8`, but only `1.0e-6` for [lsmr](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.lsmr.html).

**Comment by tupui** [comment]
Hi, thanks. But should it be the same values? Is there underlying assumptions supporting that? What about specifics of the current implementation?

**Comment by nschloe** [comment]
> But should it be the same values?

From the docstring of lsmr:
> If both tolerances are 1.0e-6 (say), the final norm(r) should be accurate to about 6 digits.

and lsqr:
> If both are 1.0e-9 (say), the final residual norm should be accurate to about 9 digits.

When tossing the same problem at lsqr and lsmr, I think the expectation should be that they (try to) solve the problem up to the same default accuracy. Note they they both measure the same thing, namely the residual norm.

**Comment by tupui** [comment]
Ok, I actually checked the paper of LSMR (https://arxiv.org/pdf/1006.0758.pdf) and in their comparison they say that they used the same tolerances. 

> 3.6. Practical stopping criteria. For LSMR we use the same stopping rules
as LSQR [16], involving dimensionless quantities ATOL, BTOL, CONLIM

Still, in the end the tolerance depends on the problem at hand and one should adjust it. The issue with changing default values is that we could potentially break lot of codes. Maybe we could increase the tolerance of LSMR to 1e9 to match the one of LSQR. I will let another reviewer with more background here judge.

**Comment by nschloe** [comment]
> Still, in the end the tolerance depends on the problem at hand and one should adjust it.

Then it shouldn't have a default value, right? I actually think this is a good idea, but that'd certainly break people's code.

>  depends on the problem

Indeed, so you plug the same problem into these two different methods, by default you should expect it to be solved with the same tolerance.

> Maybe we could increase the tolerance of LSMR to 1e9 to match the one of LSQR. I will let another reviewer with more background here judge.

:+1:
