### ISSUE TITLE
How to manually set initial step size for line-searching in optimize.minimize?

### ISSUE THREAD

**Issue by AlbertZhangHIT** [scipy/scipy#13751]
Hi,  I tried `L-BFGS-B` method to solve my problem, where I set `ftol=2e4, gtol=1e-4, maxls=5`. 
```	
result = optimize.minimize(f, x0, args=(...), method='L-BFGS-B', jac=True, callback=_callback, bounds=bounds, 
	    		options={'ftol':ftol, 'maxiter':maxiter, 'disp':True,
	    			'maxls':maxls, 'gtol':gtol, 'iprint':1})
```
I inserted printing in function ```f``` to track the function value in line-searching. The output information is following. 
```
Loss: 17225852.397213

At iterate    0    f=  1.72259D+07    |proj g|=  3.98619D-01
Loss: 54587864.108585
Loss: 34436349.330525
Loss: 20670919.360353
Loss: 11692907.120710

At iterate    1    f=  1.16929D+07    |proj g|=  3.97715D-01

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
31800      1      5  29683     0 31482   3.977D-01   1.169D+07
  F =   11692907.120710351     

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH   
```

As can be seen, the initial function value is 1.7e7, and in the first line-searching increases to 5.4e7. It takes a few trials to decrease. But every call of ```f``` is very time comsuming. I have no idea how the initial step size is determined for line-searching. Is there a way to set it manually?

**Comment by andyfaff** [comment]
There is no way of setting a line-search step size for L-BFGS-B. The underlying Fortran code does not expose that. You can set the maximum number of line search steps per iteration though.
