### ISSUE TITLE
optimize.minimize 'trust' methods and finite difference Hessian strategies potentially breaking due to NumPy broadcasting. 

### ISSUE THREAD

**Issue by mgudorf** [scipy/scipy#13754]
I'm writing this issue specifically pertaining to the "trust-krylov" method in scipy.optimize.minimize in conjunction with built-in finite difference {'2-point', '3-point', 'cs'} Hessian methods. However, similar but different issues seem to also arise, reproduced
by the same code below for trust-exact and trust-ncg. 

#### Reproducing code example:
```
import sys
from scipy.optimize import minimize
import numpy as np


def main():
    def _minfunc(x):
        return (x**2 - 1).sum()

    def _minjac(x):
        # ravel included just for my sanity
        return (2 * x).ravel()

    x0 = 4*np.ones(32)
    x_final = minimize(_minfunc, x0, method='trust-krylov', jac=_minjac, hess='cs')
    return x_final


if __name__ == '__main__':
    sys.exit(main())
```

#### Error message:

```
Traceback (most recent call last):
  File "scipy-trust-broadcasting-error.py", line 21, in <module>
    sys.exit(main())
  File "scipy-trust-broadcasting-error.py", line 16, in main
    x_final = minimize(_minfunc, x0, method='trust-krylov', jac=_minjac, hess='cs')
  File "C:\Users\Matt\Desktop\env\lib\site-packages\scipy\optimize\_minimize.py", line 641, in minimize
    callback=callback, **options)
  File "C:\Users\Matt\Desktop\env\lib\site-packages\scipy\optimize\_trustregion_krylov.py", line 57, in _minimize_trust_krylov
    **trust_region_options)
  File "C:\Users\Matt\Desktop\env\lib\site-packages\scipy\optimize\_trustregion.py", line 189, in _minimize_trust_region
    p, hits_boundary = m.solve(trust_radius)
  File "_trlib.pyx", line 113, in scipy.optimize._trlib._trlib.TRLIBQuadraticSubproblem.solve
TypeError: float() argument must be a string or a number, not '_ScaledLinearOperator'
```

#### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.6.2 1.20.1 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
```

#### Environment information

I am running on
```
Microsoft Windows 10 Education
Version 10.0.19042 Build 19402
```

For testing purposes, I created a virtual environment using the following commands in command prompt. 

```
$ python -m venv env
$ cd env\Scripts
$ activate
$(env) python -m pip --upgrade pip
$(env) python -m pip install scipy
$(env) python -m pip list

Package    Version
---------- -------
numpy      1.20.1
pip        21.0.1
scipy      1.6.2
setuptools 41.2.0
```

#### Relevant Debugging Information

https://github.com/scipy/scipy/blob/d03be7c789097a994507e6ce8b6be14d450eeac8/scipy/optimize/_trustregion.py#L63

In the BaseQuadraticSubproblem method 

```
def hessp(self, p):
    if self._hessp is not None:
        return self._hessp(self._x, p)
    else:
        return np.dot(self.hess, p)
```

In the minimal code example I provided, the issue is occurring during the evaluation of ```np.dot(self.hess, p)```. More
specifically, I believe that the issue is due to NumPy broadcasting, as what is being returned is an array whose elements are of _ScaledLinearOperator type.

#### Proposed/Possible Fix

I do not know enough about SciPy/NumPy internals but the following is at least an incredibly simple change that could be
considered.  I believe that a method for fixing this would be to evaluate the dot product by not appealing to numpy, but rather, appealing to the ```dot``` method instead, which I presume (perhaps incorrectly) must exist for all ndarray / LinearOperator types
that would possibly arise here. 

```
def hessp(self, p):
    if self._hessp is not None:
        return self._hessp(self._x, p)
    else:
        return self.hess.dot(p)
```

I have attached an image of using Pycharm's evaluation tool during debugging, showing the results of the two different evaluations; namely, the current code vs. code that could possibly resolve the issue. 

![scipy_issue_debug_evaluation](https://user-images.githubusercontent.com/41150404/112709214-b4377b80-8e8d-11eb-91ca-02fdb7029a3d.png)

#### Contact Info

For questions feel free to contact me at matthew.gudorf@gmail.com. Thanks!

**Comment by mgudorf** [comment]
Additional comment: 

Error was generated via 
```
$(env) python scipy-trust-broadcasting-error.py
```
where ```scipy-trust-broadcasting-error.py``` was the name of the script containing the minimal code example.

**Comment by andyfaff** [comment]
As far as I can tell from the git history of `_trustregion.py` (which serves *trust-krylov, trust-ncg, trust-exact*), those trust region methods (`trust-constr` is different) have always required a callable `hess` in order to work properly.
It does say in the documentation

> Finite-difference options {‘2-point’, ‘3-point’, ‘cs’} and HessianUpdateStrategy are available only for ‘trust-constr’ method.

, which means that they're not allowed for *trust-krylov, trust-ncg, trust-exact*. This indirectly means that you need a callable `hess`. So the documentation is already there, @mgudorf how could the documentation be made clearer?

One change to the code could be to make a check that will raise an appropriate error is hess isn't callable.

If `2-point`, `3-point`, `cs`, or `HessianUpdateStrategy` are provided for hess then `ScalarFunction.H` is either a `LinearOperator` or `HessianUpdateStrategy`. It *may* be possible to use a Hessian estimated from that to give to the trustregion methods, but that's not my area of expertise.

**Comment by mgudorf** [comment]
@tupui @andyfaff 

My apologies, I missed that sentence; however, more testing on my end still yielded unexpected results; notably providing the Hessian as a `LinearOperator` and two dimensional `np.ndarray` have disparate results for `trust-constr` and `trust-krylov`; the
latter breaking down in the same place as the original issue. 

### Using a `LinearOperator` with `trust-krylov`

```
import sys
from scipy.optimize import minimize
import numpy as np
from scipy.sparse.linalg import LinearOperator

def main():
    def _minfunc(x):
        # The scalar function to minimize
        return (x**2 - 1).sum()

    def _minjac(x):
        # The scalar function's gradient
        return (2 * x).ravel()

    def _minhess(x):
        # The Hessian provided as a LinearOperator (exact hessian is 2 * identity)
        mv = lambda y : 2 * y
        return LinearOperator(shape=(x.size, x.size), matvec=mv, rmatvec=mv)

    x0 = 4*np.ones(32)
    x_final = minimize(_minfunc, x0, jac=_minjac, hess=_minhess, method='trust-krylov')
    return x_final

if __name__ == '__main__':
    sys.exit(main())
```

#### Error message:

```
Traceback (most recent call last):
  File "scipy-trust-broadcasting-error.py", line 29, in <module>
    sys.exit(main())
  File "scipy-trust-broadcasting-error.py", line 24, in main
    x_final = minimize(_minfunc, x0, jac=_minjac, hess=_minhess, method='trust-krylov')
  File "C:\Users\Matt\Desktop\scipy-test\lib\site-packages\scipy\optimize\_minimize.py", line 641, in minimize
    callback=callback, **options)
  File "C:\Users\Matt\Desktop\scipy-test\lib\site-packages\scipy\optimize\_trustregion_krylov.py", line 57, in _minimize_trust_krylov
    **trust_region_options)
  File "C:\Users\Matt\Desktop\scipy-test\lib\site-packages\scipy\optimize\_trustregion.py", line 189, in _minimize_trust_region
    p, hits_boundary = m.solve(trust_radius)
  File "_trlib.pyx", line 113, in scipy.optimize._trlib._trlib.TRLIBQuadraticSubproblem.solve
TypeError: float() argument must be a string or a number, not '_ScaledLinearOperator'
```

### Using a `LinearOperator` with `trust-constr`

```
import sys
from scipy.optimize import minimize
import numpy as np
from scipy.sparse.linalg import LinearOperator

def main():
    def _minfunc(x):
        # The scalar function to minimize
        return (x**2 - 1).sum()

    def _minjac(x):
        # The scalar function's gradient
        return (2 * x).ravel()

    def _minhess(x):
        # The Hessian provided as a LinearOperator (exact hessian is 2 * identity)
        mv = lambda y : 2 * y
        return LinearOperator(shape=(x.size, x.size), matvec=mv, rmatvec=mv)

    x0 = 4*np.ones(32)
    x_final = minimize(_minfunc, x0, jac=_minjac, hess=_minhess, method='trust-constr')
    return x_final

if __name__ == '__main__':
    sys.exit(main())
```

#### Output

```
         cg_niter: 3
     cg_stop_cond: 4
           constr: []
      constr_nfev: []
      constr_nhev: []
      constr_njev: []
   constr_penalty: 1.0
 constr_violation: 0
   execution_time: 0.008998870849609375
              fun: -32.0
             grad: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
              jac: []
  lagrangian_grad: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
          message: '`gtol` termination condition is satisfied.'
           method: 'equality_constrained_sqp'
             nfev: 4
             nhev: 4
              nit: 4
            niter: 4
             njev: 4
       optimality: 0.0
           status: 1
          success: True
        tr_radius: 102.39191898578666
                v: []
                x: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

Meanwhile, providing the Hessian as an array works fine for both. 

### Using a `ndarray` Hessian with `trust-krylov`

```
import sys
from scipy.optimize import minimize
import numpy as np
from scipy.sparse.linalg import LinearOperator

def main():
    def _minfunc(x):
        # The scalar function to minimize
        return (x**2 - 1).sum()

    def _minjac(x):
        # The scalar function's gradient
        return (2 * x).ravel()

    def _minhess(x):
        return 2*np.eye(x.size)

    x0 = 4*np.ones(32)
    x_final = minimize(_minfunc, x0, jac=_minjac, hess=_minhess, method='trust-krylov')
    return x_final


if __name__ == '__main__':
    sys.exit(main())
```

#### Output
``` 
     fun: -32.0
    hess: array([[2., 0., 0., ..., 0., 0., 0.],
       [0., 2., 0., ..., 0., 0., 0.],
       [0., 0., 2., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 2., 0., 0.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 0., ..., 0., 0., 2.]])
     jac: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
 message: 'Optimization terminated successfully.'
    nfev: 6
    nhev: 5
     nit: 5
    njev: 6
  status: 0
 success: True
       x: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```
## `trust-constr` output using Hessian as 2-d array. 
```
import sys
from scipy.optimize import minimize
import numpy as np
from scipy.sparse.linalg import LinearOperator

def main():
    def _minfunc(x):
        # The scalar function to minimize
        return (x**2 - 1).sum()

    def _minjac(x):
        # The scalar function's gradient
        return (2 * x).ravel()

    def _minhess(x):
        return 2*np.eye(x.size)

    x0 = 4*np.ones(32)
    x_final = minimize(_minfunc, x0, jac=_minjac, hess=_minhess, method='trust-constr')
    return x_final


if __name__ == '__main__':
    sys.exit(main())

```
### Output
``` 
       cg_niter: 3
   cg_stop_cond: 4
         constr: []
    constr_nfev: []
    constr_nhev: []
    constr_njev: []
 constr_penalty: 1.0
constr_violation: 0
 execution_time: 0.009998798370361328
            fun: -32.0
           grad: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
     0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
            jac: []
lagrangian_grad: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
     0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
        message: '`gtol` termination condition is satisfied.'
         method: 'equality_constrained_sqp'
           nfev: 4
           nhev: 4
            nit: 4
          niter: 4
           njev: 4
     optimality: 0.0
         status: 1
        success: True
      tr_radius: 102.39191898578666
              v: []
              x: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
     0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
```

If I understood @andyfaff correctly then I think the issue stands, albeit for a different reason now, and I believe would be fixed by the same correction I originally proposed.

**Comment by andyfaff** [comment]
In the examples where you're providing an "`np.ndarray`", what you're actually providing to `minimize` is a callable `hess`, `callable(hess) is True`. A callable hess has always been accepted for the trust region minimizers, and was mandatory for all of them except trust-constr.

As you suggest, it should be possible to amend `_trustregion.py`, around about [here](https://github.com/scipy/scipy/blob/master/scipy/optimize/_trustregion.py#L163) such that if a callable `hessp` is not provided, then the function you suggest above can be used to create a `hessp` from the LinearOperator/HessianUpdateOperator that's returned from `ScalarFunction.hess`. Whilst this would be suitable for trust-krylov and trust-ncg the documentation suggests it wouldn't work for trust-exact.

**Comment by mgudorf** [comment]
@andyfaff 

Apologies once again for the brain lapse; I definitely dropped the ball on what I was trying to say. What I meant was a callable that returns an array versus a callable which returns a `LinearOperator`. 

Regardless, I was wrong either way. In in light of your comments, I suppose what I was trying to show kind of missed the point of having `hessp` available. If I can form a `LinearOperator` I might as well just create a callable which would be compatible with `hessp` instead of passing the `LinearOperator` to `hess` directly. 

Thanks for the feedback! I'm sure there is a good reason but I am still curious as to why `np.dot` is used over the alternative though, but I'm sure there is a better place to ask such questions.

**Comment by andyfaff** [comment]
>  In in light of your comments, I suppose what I was trying to show kind of missed the point of having hessp available. If I can form a LinearOperator I might as well just create a callable which would be compatible with hessp instead of passing the LinearOperator to hess directly.

#13775 adds this.

The community is always striving to make better documentation. It's a hard task though. Both to make it crystal clear, and to accurately reflect what's going on in the code. (Keeping it up to date is difficult as well).

**Comment by mgudorf** [comment]
| Admissible (jac, hess) combinations       | callable  > array (n,n)                                                | callable  > Linear Operator or spmatrix | {‘2 point’, ‘3 point’, ‘cs’} or HessianUpdateStrategy| quasi newton |                     
|-------------------------------------------|------------------------------------------------------------------------|-----------------------------------------|------------------------------------------------------|--------------|
| True (fun returns (objective, gradient))  | Newton CG, dogleg, trust ncg, trust krylov, trust exact, trust-constr  |         trust-constr                    | trust-constr                                         | trust-constr |
| (‘2 point’, ‘3 point’, ‘cs’)              | trust-constr                                                           |         trust-constr                    | X                                                    | trust-constr |
| callable  > array_like, shape (n,)        | Newton CG, dogleg, trust ncg, trust krylov, trust exact, trust-constr  |         trust-constr                    | trust-constr                                         | trust-constr |
| None or False  > 2 point finite difference| trust-constr                                                           |         trust-constr                    | X                                                    | trust-constr |

For what it is worth I included a markdown and restructured text versions of the above table, attached in .txt file, in case
it might be useful. Thanks for the insight @andyfaff and @tupui !

[jac_hess_tables.txt](https://github.com/scipy/scipy/files/6233383/jac_hess_tables.txt)

**Comment by mayou36** [comment]
That is indeed a very nice table and highlights one of the main problems with the common docs: that things are highly complicated. I guess one would be better of moving all these options to the minimizers.

I think the table is not quite true though: for example, Newton CG seems not able to use no jac and the docs says it needs a callable, reality says it also works with '2-point' for example :) (but tbh, it's hard to keep up with the docs if they are spread)

This whole thread seems to me just another symptom of the over-unification of the minimize interface and the solution would be to decouple minimizer specific arguments and minimization specific arguments, e.g.

```
minimizer = MyMinimizer(jac='2-points', my_magic_arg=420)
result = minimizer.minimize(func, x0, bounds)
```

as in #8414, which seems stalled. This also allows to keep the docs per optimizer up-to-date.

What do you think, I guess this should be a larger discussion of a re-design and an implementation should follow on it, otherwise we're just fixing inherently broken things.

**Comment by tupui** [comment]
I believe the PR closes this issue. Thanks everyone.
