### ISSUE TITLE
How are the plots inside the API docs (docstring) generated?

### ISSUE THREAD

**Issue by FirefoxMetzger** [scipy/scipy#13760]
This is not an issue, but a (devops) question.

In the scipy API docs, I can see plots being generated from the docstring examples ([example](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.splprep.html#scipy.interpolate.splprep)). I think this is a really cool feature 🚀 , and I would like to use it for documentation in my projects as well. I tried googling for it, and I scoured some of the source code for clues on how this is done, but I seem to be lacking the right keywords to figure this out.

Could somebody tell me the right keywords or where in the code the magic happens, so I can educate myself?

Many thanks in advance for any pointers :)

**Comment by tupui** [comment]
This is coming from the extension https://matplotlib.org/stable/api/sphinxext_plot_directive_api.html?highlight=plot_directive#module-matplotlib.sphinxext.plot_directive
Have a look at the Sphinx configuration and at some examples from tutorials in rst for how to use it.
