### ISSUE TITLE
probplot draws fit line even when fit=False

### ISSUE THREAD

**Issue by jackbenn** [scipy/scipy#13769]
The documentation for `probplot` states:
```
    fit : bool, optional
        Fit a least-squares regression (best-fit) line to the sample data if
        True (default).
```

This implies that a best-fit line is only produced if `fit` is True. But in the code, a fit is always calculated and plotted if `plot` is not None, though is only returned if `fit` is True.

This could be resolved by clarifying the documentation (changing "Fit a least-squares..." to "Return a least-squares..."), but I believe it would be better not to draw a line at all if `fit` is False.

If a user wants to compare data to a distribution with specific parameters (e.g., norm(0, 1) rather than just any normal distribution), the least-squares fit line is unhelpful and misleading. Instead the user should plot the 45-degree diagonal and compare the points to that. While the user *could* remove the line from the graph, that requires substantial knowledge of matplotlib., so the user has to create the plot manually.

The current behavior for that combination of options (`plot=ax, fit=False`) has minimal usefulness. It's not that common for a user to want both the plot and the return value, and when they do, it's easy to ignore the second value.

The backwards-incompatibility of changing this would be minimal. It would only cause a problem if someone used these options, which seems rare, and the effect would only be a missing fit line on the plot (rather than a different return value that might cause other code to fail).

#### Reproducing code example:

The best-fit line here is problematic, but there's no easy way to remove it:
```
import matplotlib.pyplot as plt
from scipy import stats

data = stats.norm(0.3, 0.8).rvs(200)
# Do these data come from norm(0, 1)?
fig, ax = plt.subplots()
stats.probplot(data,
               dist=stats.norm(0, 1),
               fit=False,
               plot=ax)
ax.plot([-2, 2], [-2, 2],
        label="norm(0, 1)")
ax.legend()
```

#### Scipy/Numpy/Python version information:
```
1.6.0 1.19.2 sys.version_info(major=3, minor=9, micro=1, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment]
@jackbenn would gh-13769 resolve the issue?
