### ISSUE TITLE
API: Rethinking input validations

### ISSUE THREAD

**Issue by tupui** [scipy/scipy#13761]
I propose a general reflection around input validation. Part of this reflection happened on the [scipy-dev mail list](https://mail.python.org/pipermail/scipy-dev/2021-March/024588.html). The objective of this issue is to come to a decision about how we should structure existing and new codes.

In a recent issue #13629 (and #13474), the cost of validation was raised in context such as optimization.
In situations like these, or even when you know how to use the API, there are lots of unnecessary validations happening.

Following are some ideas which got discussed.

#### Split the API
A simple approach would be to systematically separate the logic in two: core function on one side, user interface on the other. This way the user could by-pass all the time the validation. The core function would be private. It would be the responsibility of the user to use it correctly as we would not guarantee the interface.

```python
def func(*inputs):
  ... validate, raise errors as necessary ...
  result = _func(*sanitazed_inputs)
  return result
```

A possibility would be to add a `validation: bool` keyword in the public API.

#### Mock validations
After some quick tests, it looks like the overhead is too big. I could be wrong.

Here is a simple experiment:
```python
import time
from unittest.mock import patch

import numpy as np
from scipy.spatial import distance

coords = np.random.random((100, 2))
weights = [1, 2]

itime = time.time()
for _ in range(50):
    distance.cdist(coords, coords, metric='sqeuclidean', w=weights)

print(f"Time: {time.time() - itime}")

with patch('scipy.spatial.distance._validate_vector') as mock_requests:
    mock_requests.side_effect = lambda x, *args, **kwargs: np.asarray(x)

    itime = time.time()
    for _ in range(50):
        distance.cdist(coords, coords, 'sqeuclidean', w=weights)

    print(f"Time: {time.time() - itime}")
```

#### Decorator like `cython.boundscheck` or `cython.wraparound`
Need to be evaluated, but most likely would have a similar overhead as mocking above.

#### `assert` for validation
The advantage of the `assert` is that validation would be cleanly identified in the code (Starlette is using this mechanism). `assert` are removed if using `python -OO`. This can either be seen as a feature or a bug. Launching python in optimized mode would indeed make SciPy faster and in a sense "optimized". But this is still more of a hidden and misunderstood behaviour of Python and this would probably break a lot of code.

Also, error message from `assert` are not perfect and a more complicated treatment might be required.

#### `array_like`
This simple check is used everywhere and is actually responsible of lots of overhead. It's usage should be reconsidered as to what we really thrive to check doing so.

####  Easier to Ask for Forgiveness than Permission
In a polished code, all tests are mostly passing all the time. We could move away from the paradigm "Look Before You Leap" to the model "Easier to Ask for Forgiveness than Permission". This is more pythonic and would definitely speedup everything.

### Take aways
From these discussions, my conclusion is as follows.

For new code, we should try to split the API in 2 blocks with the core on one side and the validation on the other side. In the validation part, using a `try ... except` construct when possible would be beneficial too. Most user would only use the public API so we still need to have a solution for them. Of course, we could add to all functions a `validation` keyword, but this could/would break all signatures.

**Comment by StanczakDominik** [comment]
> In a polish code, all tests are mostly passing all the time.

I would just like to chime in and say that I write Polish code all the time and that's not entirely true.

**Comment by rgommers** [comment]
The `cdist` issue is real, but that's just badly written code that needs to be rewritten. It'd be nice to get some more compelling examples where it matters more than a few percent. I think 10-20% overhead from excessive `asarray` etc. calls is the worst I've seen.

**Comment by tupui** [comment]
> The `cdist` issue is real, but that's just badly written code that needs to be rewritten. It'd be nice to get some more compelling examples where it matters more than a few percent. I think 10-20% overhead from excessive `asarray` etc. calls is the worst I've seen.

I did a quick check with `stats.qmc.discrepancy` and removing the `asarray` (and the 2 small validations) lead to 800ms -> 700ms with an a sample of size (1000, 100). So yes around 10%. Thus, with the new version in Cython, the overhead will be substantial.

**Comment by peterbell10** [comment]
>I did a quick check with stats.qmc.discrepancy and removing the asarray (and the 2 small validations) lead to 800ms -> 700ms with an a sample of size (1000, 100).

@tupui I can't reproduce that result from your description:
```python
In [1]: from scipy.stats.qmc import discrepancy
   ...: from scipy.stats._qmc_cy import _cy_wrapper_centered_discrepancy
   ...: import numpy as np
   ...: space = np.random.rand(1000, 100)
   ...: %timeit discrepancy(space)
   ...: %timeit _cy_wrapper_centered_discrepancy(space, iterative=False, workers=1)
94.2 ms ± 337 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
94.7 ms ± 529 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Can you post code?

**Comment by tupui** [comment]
> >I did a quick check with stats.qmc.discrepancy and removing the asarray (and the 2 small validations) lead to 800ms -> 700ms with an a sample of size (1000, 100).
> 
> 
> 
> @tupui I can't reproduce that result from your description:
> 
> ```python
> 
> In [1]: from scipy.stats.qmc import discrepancy
> 
>    ...: from scipy.stats._qmc_cy import _cy_wrapper_centered_discrepancy
> 
>    ...: import numpy as np
> 
>    ...: space = np.random.rand(1000, 100)
> 
>    ...: %timeit discrepancy(space)
> 
>    ...: %timeit _cy_wrapper_centered_discrepancy(space, iterative=False, workers=1)
> 
> 94.2 ms ± 337 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
> 
> 94.7 ms ± 529 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
> 
> ```
> 
> 
> 
> Can you post code?

This was before `discrepancy` got merged with cythonization. I will try to redo some benchmark.

**Comment by tupui** [comment]
@peterbell10 I could reproduce the slowdown using a smaller sample. I don't get why we don't have the same 100ms though. Maybe some changes on NumPy side too.

```python
import numpy as np
from scipy.stats.qmc import discrepancy
from scipy.stats._qmc_cy import _cy_wrapper_centered_discrepancy
rng = np.random.default_rng()
space = rng.random((100, 10))
%timeit discrepancy(space, iterative=False, workers=1)
# 132 µs ± 892 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
%timeit _cy_wrapper_centered_discrepancy(space, iterative=False, workers=1)
# 119 µs ± 328 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Comment by peterbell10** [comment]
Running the same code I get:
```
101 µs ± 375 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
93.9 µs ± 136 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
Most of the time difference (~5.8 us) is spent in this line:
https://github.com/scipy/scipy/blob/5afab5ad900bac7080a42016de40aac7a14e2e36/scipy/stats/_qmc.py#L263

Which is the only check that actually reads the input array, so has O(n) cost. For comparison, the `asarray` call I benchmark at 0.3 us. I think it's generally true that constant time overheads are fairly okay (but worth minimizing) but O(n) or worse checks should actively be avoided.

Some functions already have a `check_finite=True` argument that can be disabled to stop O(n) checks for INF or NANs in the input.

**Comment by ilayn** [comment]
It should be much faster if we write `(sample.max() >= 1.) and (sample.min() <= 0.)` check eliminating the extra array comparisons.
