### ISSUE TITLE
standard deviation of lognorm

### ISSUE THREAD

**Issue by mcgrete** [scipy/scipy#13781]
I find that the standard deviation returned by lognorm.std() is incorrect.  Forgive me if I am wrong; I have attempted to verify and prove that I am correct.  I will describe my attempt and follow with code used to demonstrate.

1. I specify a normal distribution with mu=5 and std=1.5.  Then, create random samples from the distribution; then transform the random samples to get obtain a lognormal distribution; - pretty straight forward.  Then I fit the random samples using scipy.stats.lognorm() and capture the output parameters, i.e. [shape, loc, scale].  I interpret as follows: shape is the fit estimate of std (not exp(std)), and scale is the fit estimate of exp(mu) - not mu.  Ok so far.  [ FYI - I find it confusing that the parameters returned are essentially not in the same distribution space, e.g. shape is the standard deviation of the data expressed in the space where the data is normally distributed, and scale is the median of the same data transformed to a space where it is lognormally distributed.  I would have expected the parameters returned to be either for N(u,sig) or LN(u',sig'), not a mixture as in (u', sig).  I am sure there is a good reason for this; can you please enlighten me? ]

2.  I can obtain the Sample median value with the fit of the lognormal distribution via lognorm.median(), and transform its value to compare to the Population mu via ln(lognorm.median()); excellent agreement, as expected (4.93 vs 5.0).  

3. By definition, I calculate the standard deviation per Wikapedia combining the equations for the median and mean, knowing Sample estimates of the median & mean one simply solves for the Sample standard deviation (aka sigma): sigma = (2*[ln(mean)-ln(median)])^0.5., where mean and median are obtained from lognorm.mean() and lognorm.median().  The Sample standard deviation == sigma is equal to ~1.439; this is very close to the Population standard deviation== std = 1.5, as expected.

4.   However, lognorm.std(), which is provides the standard deviation of the distribution is far from the Sample or Population standard deviation: sigma & std; e.g. lognorm.std()~1023, and ln(1023)~6.93, also far from sigma or std.

5. I thought that perhaps lognorm.std() simply returns the equivalent of np.std(data)~783; this is apparently not true as  lognorm.std()~1023; note: 'data' are the random samples transformed into lognormal space via exp(datao) where datao are the data generated randomly in normal space.

For now, I simply use the parameters returned from 'fit' and not lognorm.std().  However, I would like to understand my error, or assist with catching a bug.

Your efforts are much appreciated.

I have attached code as .txt file.  Forgive, I will paste herein as 'code', but the format of my comment statements and a few commands appear to not be fully compatible with this widget.

``` python
from scipy.stats import lognorm
from scipy.stats import norm
import matplotlib.pyplot as plt
import numpy as np
from textwrap import wrap

# Attempt to verify how to use scipy.stats.lognorm

# IN NATURAL LOG SPACE...
mu_ln=5.0 # median in ln space; MEDIAN IS NOT SAME AS MEAN!
sigma_ln=1.5 # stdev in ln space
normDist = norm(loc=mu_ln, scale=sigma_ln) # create function 
N=1000 # of of samples
data_ln=normDist.rvs(size=N) # random samples in ln space

# Fit normal
params_ln = norm.fit(data_ln)
norm_dist_fitted = norm(*params_ln)
x_ln = np.linspace(0.8*np.min(data_ln), 1.2*np.max(data_ln), 100)
normDist_model =  normDist.pdf(x_ln)



# Plot normals
fig, ax = plt.subplots(1, sharex='col', figsize=(10, 5))
ax.hist(data_ln, bins=np.arange(0.8*data_ln.min(), 1.2*data_ln.max()+1), density=True, color='yellow',label='{0:d} Data: X~N(mu={1:.3f}, sigma={2:.3f})'.format(N, mu_ln, sigma_ln))
ax.plot(x_ln, norm_dist_fitted.pdf(x_ln), lw=2, color='r', label='Fitted Model X~N(mu={0:.3f}, sigma={1:.3f})'.format(norm_dist_fitted.median(), norm_dist_fitted.std()))
ax.plot(x_ln, normDist_model, lw=2, color='black', ls=':', label='Original Model X~N(mu={0:.3f}, sigma={1:.3f})'.format(normDist.median(), normDist.std()))
ax.legend(loc='upper right')
plt.show()


#%% REGULAR SPACE, e.g. x=exp(X), X is in ln space; x is in regular space
data=np.exp(data_ln) # use same data from ln space, transform via exp()
mu=np.exp(mu_ln) # transform via exp()
sigma=np.exp(sigma_ln) # transform via exp()
# fit with longorm.fit() in regular space
params3 = lognorm.fit(data, floc=0) # just with raw data, assuming we don't know mu at this point


# model predictions
lognorm_dist_fitted3 = lognorm(*params3)
print(lognorm_dist_fitted3.std())

x = np.linspace(0.8*np.min(data), 1.2*np.max(data), 100)

# Original model: i.e. given parameters, create model
# yes, one is in ln space, other is in regular space!
lognormDist = lognorm(s=sigma_ln, loc=0, scale=mu) 


# Plot lognormals
fig3, ax2 = plt.subplots(1, sharex='col', figsize=(10, 5))
ax2.hist(data, bins=25, density=True, alpha=0.2, color='cyan', 
         label='{0:d} MC Data Sampled in ln-space: X~N(mu={1:.2f}, sigma={2:.2f})'.format(N, mu_ln, sigma_ln))

# params3[0]!=np.log(lognorm_dist_fitted3.std()); unexpected!
ax2.plot(x, lognorm_dist_fitted3.pdf(x), lw=2, color='black', ls=':',
        label='LogNorm Fit of "MC Data xfmd from ln-space to reg space": x~exp[LN(mu={0:.2f}, sigma={1:.2f})]'.format(np.log(lognorm_dist_fitted3.median()), params3[0] ) )

# params_ln[0]==norm_dist_fitted.std(), as expected.
ax2.plot(x, lognorm.pdf(x, s=sigma_ln,loc=0, scale=mu), lw=2, color='blue', ls='-',
        label='Model via lognorm() w/ params xfrmd from params of N() fit of ' + \
        'MC Data in ln-space: x~exp[N(mu={0:.2f}, sigma={1:.2f})]'.format(norm_dist_fitted.median(), norm_dist_fitted.std())) 



# wrap labels...
handles, labels = ax2.get_legend_handles_labels()
labels2 = [ '\n'.join(wrap(l, 30)) for l in labels ]
ax2.legend(loc='best')
plt.legend(labels2)
plt.show()


# Update normal plot w/ fit from lognormal; verify one can fit in either space...
fig, ax = plt.subplots(1, sharex='col', figsize=(10, 5))

ax.hist(data_ln, bins=np.arange(0.8*data_ln.min(), 1.2*data_ln.max()+1), 
        density=True, color='yellow',label='{0:d} Data: X~N(mu={1:.1f}, sigma={2:.1f})'.format(N, mu_ln, sigma_ln))
ax.plot(x_ln, norm_dist_fitted.pdf(x_ln), lw=2, color='r',
        label='Fitted Model X~N(mu={0:.3f}, sigma={1:.3f})'.format(norm_dist_fitted.median(), norm_dist_fitted.std()))
ax.plot(x_ln, normDist_model, lw=2, color='black', ls=':',
        label='Original Model X~N(mu={0:.3f}, sigma={1:.3f})'.format(normDist.median(), normDist.std()))

# use fit parameters returned from lognorm.fit(), ie. can't use lognorm.std()...
ax.plot(x_ln, norm.pdf(x_ln, loc=np.log(params3[2]), \
        scale=params3[0]), lw=2, color='blue', ls='--',
        label='LogNorm Fit of "MC Data xfmd from ln-space to reg space": X~N(mu={0:.3f}, sigma={1:.3f})]'.\
        format(np.log(params3[2]),params3[0] ) )

# demonstrate use of lognorm.std() is in error...
ax.plot(x_ln, norm.pdf(x_ln, loc=np.log(lognorm_dist_fitted3.median()),
        scale=np.log(lognorm_dist_fitted3.std())), lw=4, color='black', ls='--',
        label='lognorm_dist_fitted3.std() --> LogNorm Fit of "MC Data xfmd from ln-space to reg space": X~N(mu={0:.3f}, sigma={1:.3f})]'.\
        format(np.log(lognorm_dist_fitted3.median()),np.log(lognorm_dist_fitted3.std()) ) )


ax.legend(loc='upper right')
handles, labels = ax.get_legend_handles_labels()
labels2 = [ '\n'.join(wrap(l, 30)) for l in labels ]
plt.legend(labels2)
plt.show()
```

**Comment by tirthasheshpatel** [comment]
Can you please render your code snippets as Markdown code blocks using this around them:

\`\`\`python
\< your code goes here \>
\`\`\`

This will make them easier to read and copy/paste (especially the code you use to create the plots.).

**Comment by mcgrete** [comment]
Hello; I modified code rendering; finally figured out that I need to copy the single quote that is created with the widget as opposed to my keyboard entry.  Renders fine now.

**Comment by chrisb83** [comment]
There was some confusion related to the parametrization before, see #12844. The key statement is in the documentation of `scipy.stats.lognorm`: 

> A common parametrization for a lognormal random variable Y is in terms of the mean, mu, and standard deviation, sigma, of the unique normally distributed random variable X such that exp(X) = Y. This parametrization corresponds to setting s = sigma and scale = exp(mu).

I just had a quick look at your code, it seems you used the former version that still needs to be translated to the SciPy parametrization. I hope it helps...

**Comment by mcgrete** [comment]
Hello, and thank you for your response.

I believe that I do already have the proper understanding of `It's referring to the mean and standard deviation of "the unique normally distributed random variable X such that exp(X) = Y", not the log-normal Y itself. I can see how that can be missed in that sentence, but I'm not sure how to rephrase it. It is an important relationship that does need to be stated explicitly.` found in #12488.  I can and do recognize the variables shape and scale in that context, and how they relate to the mean and standard deviation of the normally distributed variable X, not the log-normal Y.  My code demonstrates the proper use of them.

My question, perhaps not made clear, is that when I utilize the function `lognorm.std()` I am expecting (perhaps in error) to obtain the standard deviation of X.  scipy documentation clearly states:  `std(loc=0, scale=1)  --->> Standard deviation of the distribution`.   `lognorm.std()` generates neither the standard deviation of X nor standard deviation of Y.  Example: if the function is intended to obtain the standard deviation of the normally distribution, then in my example it should return `1.5`, but it does not.  

**Please help me understand specifically what `lognorm.std()` is returning,** I believe my example code shows that if I utilize the standard deviation returned from this function, that it is not returning the standard deviation of Y or X or some other transform of the same (e.g. exp() or ln()), i.e. I cannot reproduce the normal distribution X using the standard deviation returned by `lognorm.std()` as demonstrated in the 3rd plot by the distribution being excessively wide, while the mean is correct.

**In contrast, the fit of the lognormal distribution** via `lognorm.fit()` **does return** `shape, loc, scale`; I clearly demonstrate an understanding and ability to apply these terms properly as `shape==sigma` and `scale==exp(u)`, and I can properly reconstruct the specified normal distribution of X, and the lognormal distribution exp(X)=Y.  Hence,  `lognorm.fit()` does return the appropriate parameters to reconstruct the distribution, whether in normal space or lognormal space.

My expectation is that `lognorm.std()` will produce either an identical value as ` shape` returned by `lognorm.ft()`, or some equivalent transformation.  I demonstrate that it does not; I also demonstrate in my text per #3 and #4 that I can calculate and verify the standard deviation via `lognrom.median()` and `lognorm.mean()` relative to the specified value of `sigma=1.5`, and that `lognorm.std() `is not correct or consistent with the same.

 Thank you for your time and patience if somehow I am in error.

**Comment by rkern** [comment]
`lognorm.std()` will return the standard deviation of the log-normal distribution (i.e. `Y=exp(X)`), not the underlying normal distribution (`X`). You can check that it computes the same value as the square root of the variance as given in the formula on [the Wikipedia page for the log-normal distribution](https://en.wikipedia.org/wiki/Log-normal_distribution).

**Comment by rkern** [comment]
```python
>>> np.sqrt((np.exp(sigma_ln**2) - 1)*np.exp(2*mu_ln + sigma_ln**2))                                                                                                                                
1331.8325625497584

>>> lognormDist.std()                                                                                                                                                                               
1331.8325625497584
```

**Comment by mcgrete** [comment]
Of course; apologies.  A momentary lapse or reason.  I check properly in normal space, but tried to straight away transform standard deviation.  The median, mean, and data transform via exp(), but standard deviation does not.  Thank you.
