### ISSUE TITLE
BUG: stats: wrapcauchy.cdf does not broadcast the shape parameter correctly.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#13791]
When an array is given as the shape parameter to `wrapcauchy.cdf`, it appears that only the first value in the array is used in the calculations.  For example,

```
In [3]: c = np.array([0.03, 0.25, 0.5])                                                                                                             

In [4]: wrapcauchy.cdf(2.0, c)                                                                                                                      
Out[4]: array([0.3268839, 0.3268839, 0.3268839])
```
All the values are the same in that output, and they correspond to the CDF when the shape is 0.03.

Here are the correct values:
```

In [5]: [wrapcauchy.cdf(2, t) for t in c]                                                                                                           
Out[5]: [0.32688389546873015, 0.3829474595854628, 0.43288446668740754]
```

SciPy and NumPy versions:
```
In [7]: scipy.__version__                                                                                                                           
Out[7]: '1.7.0.dev0+08390dc'

In [8]: np.__version__                                                                                                                              
Out[8]: '1.19.5'
```

**Comment by mdhaber** [comment]
I haven't had time to finish yet, as it's lower priority, but i wanted to basically rewrite a more comprehensive version of `test_continuous_basic`/`test_continuous_basic` (to) smoke out these things. It wouldn't necessarily need to run on CI all the time if it's slow. Does that sound useful?

**Comment by WarrenWeckesser** [comment]
According to a git bisect, 2233802 (part of https://github.com/scipy/scipy/pull/13611) is the commit where this broke.

**Comment by WarrenWeckesser** [comment]
@mdhaber, yes, something that would have caught this issue would be useful.
