### ISSUE TITLE
" import scipy"raises ModuleNotFoundError: No module named '_ctypes'

### ISSUE THREAD

**Issue by zhifeiji-han** [scipy/scipy#13821]
I use SCIRun software which include python3.8.2. When I   import scipy in the python console , it raises error that ModuleNotFoundError: No module named '_ctypes'. When I   import scipy in the cmd.exe , it raises normal.

#### Error message:
![image](https://user-images.githubusercontent.com/70640243/113808583-e18efe00-9798-11eb-8877-6325d52fae41.png)
![image](https://user-images.githubusercontent.com/70640243/113809089-fcae3d80-9799-11eb-8c19-dbc0ed20a3ef.png)

#### Scipy/Numpy/Python version information:
![image](https://user-images.githubusercontent.com/70640243/113808754-477b8580-9799-11eb-87da-9b22efd9caec.png)
![image](https://user-images.githubusercontent.com/70640243/113808932-a50fd200-9799-11eb-9505-b2eb2eba9358.png)

**Comment by zhifeiji-han** [comment]
I don't understand the cause of the mistake（ModuleNotFoundError: No module named '_ctypes'）

**Comment by ilayn** [comment]
Somehow your Python installation is not good. Either reinstall Python itself or make sure python is on the path. It is possible that the SciRun is not installing Python correctly. They also mention to install python separately here http://sciinstitute.github.io/scirun.pages/python.html

If you search for `No module named '_ctypes'` + windows you can have lots of similar issues not related to SciPy. Hence we can't do more about this. But feel free to continue the discussion.
