### ISSUE TITLE
Memory leak with sparse matrices?

### ISSUE THREAD

**Issue by nordam** [scipy/scipy#13827]
My issue is about apparent memory leaks when working with sparse matrices. I am writing a physics simulation that involves solving a sparse system of equations. My system matrix has a bunch of diagonals, so I store it using `scipy.sparse.dia_matrix`. I also use a sparse incomplete LU decomposition as part of the solver, this is created with `scipy.sparse.linalg.spilu`. Since `spilu` requires a `csc_matrix` as input, I have to temporarily create a copy of my matrix in that format, and that seems to cause a memory leak.

Here is a fairly compact working example:

```
import numpy as np
from scipy.sparse import diags, csc_matrix
from memory_profiler import profile

def create_matrix(N):
    diagonals = []
    offsets = []
    for i in range(0, N*N-1, N):
        diagonals.append(np.ones(N*N - i))
        offsets.append(i)
    return diags(diagonals, offsets)

@profile
def main():

    # Create a large-ish sparse matrix in dia_matrix format
    L = create_matrix(500)

    # create a temporary copy in CSC format
    tmp = csc_matrix(L)

    # Delete the temporary copy
    del(tmp)

    # create a new temporary copy in CSC format
    tmp = csc_matrix(L)

    # Delete the new temporary copy
    del(tmp)

if __name__ == '__main__':
    main()

```

and here is the output of the memory debugger:

```
Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
    17     62.3 MiB     62.3 MiB           1   @profile
    18                                         def main():
    19
    20                                             # Create a large-ish sparse matrix in dia_matrix format
    21    571.7 MiB    509.4 MiB           1       L = create_matrix(500)
    22
    23                                             # create a temporary copy in CSC format
    24   1993.8 MiB   1422.1 MiB           1       tmp = csc_matrix(L)
    25
    26                                             # Delete the temporary copy
    27   1275.3 MiB   -718.6 MiB           1       del(tmp)
    28
    29                                             # create a new temporary copy in CSC format
    30   1991.9 MiB    716.7 MiB           1       tmp = csc_matrix(L)
    31
    32                                             # Delete the new temporary copy
    33   1275.3 MiB   -716.7 MiB           1       del(tmp)
```

Here are the steps in the code above, with comments about what I don't understand:

* First, I create the matrix `L`. This takes about 510 MB of memory according to the memory debugger. When I use `L.nnz` to get the number of stored elements in the sparse matrix, and calculate the size from that, I get 466 MB, so that seems reasonable.
* Next, I create the temporary copy in CSC format, `tmp`. According to the memory debugger, this takes an extra 1422 MB. Of course `tmp` has the same number of stored elements as `L`, but since the matrix has a bunch of diagonals, I expect the `dia_matrix` format to be more efficient that the `csc_matrix` format, so for all I know, it may be reasonable that `tmp` takes almost three times the memory of `L`.
* Then, I delete the temporary copy, `tmp`. According to the memory debugger, this only frees up about 720 MB, so around half the memory that got occupied when I created `tmp`.
* Then, I repeat the process of creating and deleting `tmp`, and now I see more expected behaviour, in that this first takes up, and then frees, 717 MB of memory.

To me, it looks like some memory is allocated when I create `tmp`, which doesn't get freed when I delete `tmp`. And the fact that recreating `tmp` a second time takes up less memory indicates, I guess, that the same memory is reused.

#### Scipy/Numpy/Python version information:
```
1.5.2 1.19.2 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
```

**Comment by perimosocordiae** [comment]
I'm unable to reproduce locally with Python 3.8.6, scipy 1.6.2, numpy 1.20.2 on Ubuntu:

```
Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
    13     54.9 MiB     54.9 MiB           1   @profile
    14                                         def main():
    15                                         
    16                                             # Create a large-ish sparse matrix
    17    576.9 MiB    522.0 MiB           1       L = create_matrix(500)
    18                                         
    19                                             # create a temporary copy in CSC format
    20   1293.7 MiB    716.8 MiB           1       tmp = csc_matrix(L)
    21                                         
    22                                             # Delete the temporary copy
    23    577.0 MiB   -716.7 MiB           1       del(tmp)
    24                                         
    25                                             # create a new temporary copy in CSC format
    26   1293.7 MiB    716.7 MiB           1       tmp = csc_matrix(L)
    27                                         
    28                                             # Delete the new temporary copy
    29    577.0 MiB   -716.7 MiB           1       del(tmp)
```

What OS are you running?

Also, if you can, try bumping your scipy version to 1.6.2 and try again.

**Comment by nordam** [comment]
I'm on MacOS (Big Sur, 11.2.3), and I have python installed via conda. Here is the output with scipy 1.6.2:

```
Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
    17     32.6 MiB     32.6 MiB           1   @profile
    18                                         def main():
    19
    20                                             # Create a large-ish sparse matrix
    21    541.9 MiB    509.3 MiB           1       L = create_matrix(500)
    22
    23                                             # create a temporary copy in CSC format
    24   1941.6 MiB   1399.6 MiB           1       tmp = csc_matrix(L)
    25
    26                                             # Delete the temporary copy
    27   1224.9 MiB   -716.7 MiB           1       del(tmp)
    28
    29                                             # create a new temporary copy in CSC format
    30   1941.6 MiB    716.7 MiB           1       tmp = csc_matrix(L)
    31
    32                                             # Delete the new temporary copy
    33   1224.9 MiB   -716.7 MiB           1       del(tmp)


> python -c "import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)"
1.6.2 1.19.2 sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)
```

**Comment by tupui** [comment]
I have the same on macOS BigSur.

`1.7.0.dev0+272f7b2 1.20.2 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)`

But I am not sure about this. I though memory management was not that simple in Python. Even calling `gc.collect()` after `del` could not necessarily free the memory right away.

**Comment by tirthasheshpatel** [comment]
I agree with @tupui. Garbage collection can happen anytime or not happen at all. [See this](https://docs.python.org/3/reference/datamodel.html):

> Objects are never explicitly destroyed; however, when they become unreachable they may be garbage-collected. An implementation is allowed to postpone garbage collection or omit it altogether — it is a matter of implementation quality how garbage collection is implemented, as long as no objects are collected that are still reachable.

**Comment by tupui** [comment]
So is there any issue then? Or can we close?

**Comment by tirthasheshpatel** [comment]
I would let @nordam decide. Does my comment answer your question @nordam?

**Comment by nordam** [comment]
I suppose it does. But which implementation of what exactly are you talking about, when you say it's a matter of implementation quality? I'm not sure I understand why there is apparently a difference between Mac and Linux. Or is that just an accident?

Or to put it another way: Should I want to make an effort to fix this, where would I have to look?

**Comment by tupui** [comment]
> I suppose it does. But which implementation of what exactly are you talking about, when you say it's a matter of implementation quality? I'm not sure I understand why there is apparently a difference between Mac and Linux. Or is that just an accident?
> 
> Or to put it another way: Should I want to make an effort to fix this, where would I have to look?

It's from the link. So it's on Python side I believe.

**Comment by tirthasheshpatel** [comment]
> I suppose it does. But which implementation of what exactly are you talking about, when you say it's a matter of implementation quality? I'm not sure I understand why there is apparently a difference between Mac and Linux. Or is that just an accident?

I think "an implementation" refers to CPython's implementation which is just one of the many interpreters among PyPy, Jython, etc. 

> Should I want to make an effort to fix this, where would I have to look?

I like [this answer](https://stackoverflow.com/a/64626271/10177420) on SO. It recommends:

> So looking at the memory consumption of the CPython process from the operating system's perspective really does not help at all. A rather common work-around is to run memory intensive jobs in a sub-process / worker process (via multiprocessing for instance) and "only" return the result to the main process. Once the worker dies, the memory is actually freed.

**Comment by nordam** [comment]
The subprocess suggestion might work. In any case, if I understand this correctly the issue is probably not in SciPy?

Just a final question (sorry for all the questions): It says above that an implementation is allowed to postpone garbage collection, but is it also allowed to ignore calls to `gc.collect()`? Here are the results of running the same code with memory debugging, with garbage collection explicitly called after every line:

```
Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
    18     62.4 MiB     62.4 MiB           1   @profile
    19                                         def main():
    20
    21                                             # Create a large-ish sparse matrix
    22    571.8 MiB    509.4 MiB           1       L = create_matrix(500)
    23    571.8 MiB      0.0 MiB           1       gc.collect()
    24
    25                                             # create a temporary copy in CSC format
    26   1811.7 MiB   1239.9 MiB           1       tmp = csc_matrix(L)
    27   1811.7 MiB      0.0 MiB           1       gc.collect()
    28
    29                                             # Delete the temporary copy
    30   1095.1 MiB   -716.7 MiB           1       del(tmp)
    31   1095.1 MiB      0.0 MiB           1       gc.collect()
    32
    33                                             # create a new temporary copy in CSC format
    34   1974.2 MiB    879.2 MiB           1       tmp = csc_matrix(L)
    35   1974.2 MiB      0.0 MiB           1       gc.collect()
    36
    37                                             # Delete the new temporary copy
    38   1257.5 MiB   -716.7 MiB           1       del(tmp)
    39   1257.5 MiB      0.0 MiB           1       gc.collect()
```

**Comment by tupui** [comment]
Yes calling `gc.collect()` does not mean the memory will be free right away. There are tons of discussion about this on matplotlib actually where people want to create figures in loop. You really don't have an easy way to free the memory from Python from what I understand.

**Comment by nordam** [comment]
Ok. Then I guess we should just close the issue. I can anyway get around the problem by running on linux in this case, or I might look at the trick with the subprocesses.

Thanks for all the help!

**Comment by tupui** [comment]
Sure pleasure 😃  Thanks for the questions.
