### ISSUE TITLE
Unable to reproduce the output of cdf() from multivariate_normal using the same random seed

### ISSUE THREAD

**Issue by JargonPiHarston** [scipy/scipy#13824]
If my understanding if correct, I think multivariate_normal.cdf() somehow does not utilize the seed parameter given when creating the object.

```
from scipy.stats import multivariate_normal

m = [[1.000, 0.257, 0.284],
     [0.257, 1.000, 0.366],
     [0.284, 0.366, 1.000]]

random_seed = 1038743790

mvn = multivariate_normal(cov=m, seed=random_seed)
print("PDF = ", mvn.pdf([0.25, 0.50, 0.75]))
print("CDF = ", mvn.cdf([0.25, 0.50, 0.75]))

random_seed = 1038743790

mvn = multivariate_normal(cov=m, seed=random_seed)
print("PDF = ", mvn.pdf([0.25, 0.50, 0.75]))
print("CDF = ", mvn.cdf([0.25, 0.50, 0.75]))
```

Output

```
PDF =  0.05294304436416716
CDF =  0.39150623877601404
PDF =  0.05294304436416716
CDF =  0.39151457642133086
```

I believe the second time the cdf result is produced should be identical to the first.

In fact even if we set random_seed = None then cdf() still produces the identical number to this seed every time the interpreter is restarted.

#### Scipy/Numpy/Python version information:

scipy='1.5.2'
numpy='1.19.1'
python='3.7.7'

**Comment by tupui** [comment]
The PDF is calculated explicitly so `seed` has no effect. For the CDF it's almost the same but what you see is a variation around the tolerance (you can set this with parameters).

The underlying function is calling some fortran code and indeed we are not passing an information about the `seed`.

**Comment by JargonPiHarston** [comment]
Thanks for the swift response Roy!

> 
> 
> The PDF is calculated explicitly so `seed` has no effect. For the CDF it's almost the same but what you see is a variation around the tolerance (you can set this with parameters).
I see. I will try playing around with the tolerance then.
> 
> The underlying function is calling some fortran code and indeed we are not passing an information about the `seed`.
I am aware that the underlying code is actually the infamous Alan Genz fortran code. However I was mistakenly assuming that the RNG in the fortran code is somehow controlled through the seed infomation. It makes more sense though that it does not pass any information at all to fortran.

Thanks again!

**Comment by tupui** [comment]
You're welcome, I am glad I could help you and we could close the issue then.
