### ISSUE TITLE
Change name of `alpha` parameter in `interval()` method

### ISSUE THREAD

**Issue by ArturoSbr** [scipy/scipy#13835]
My issue is about the confusion caused by the `alpha` parameter in the `interval()` method.

In statistical inference, `alpha` is typically used to denote the probability enclosed by the rejection region. However, the `interval()` method treats alpha as the probability **within** the confidence interval or acceptance region. This parameter is even more confusing considering that `alpha` is also used to denote the rejection region in all `scipy` tests of significance.

I am raising this issue as a petition to change the name of the parameter passed to `interval()` from `alpha` to something else.

#### Example:
```
# Set local environment
import numpy as np
from scipy import stats

# Decalre random variable
X = stats.norm(loc=0, scale=1)

# Calculate a 95% confidence interval
### What I would expect to do
X.interval(alpha=0.05)

### Correct way to do it
X.interval(alpha=0.95)
```

Otherwise, could you add a docstring to the `interval` method? The [Reference Gude](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.norm.html) does state that the method returns the endpoints that contain `alpha` percent of the distribution. However, there is no docstring is displayed when typing.
![no_docstring](https://user-images.githubusercontent.com/47676848/114287054-8c1d5000-9a29-11eb-9cf3-90aa1bf4d10b.png)

**Comment by mdhaber** [comment]
There is another reason to change the name: see gh-13490 and its reference issue gh-5982

**Comment by mdhaber** [comment]
Fixed by gh-13490
