### ISSUE TITLE
BUG: `signal.get_window` argument handling issue 

### ISSUE THREAD

**Issue by AtsushiSakai** [scipy/scipy#13878]
My issue is about ...
[signal\.windows\.taylor](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.windows.taylor.html#scipy.signal.windows.taylor) needs only one argument `M`, others are optional.
So, this code works:
```
>>> signal.windows.taylor(7)
array([0.29009531, 0.5782126 , 0.87800822, 1.        , 0.87800822,
       0.5782126 , 0.29009531])
```

However, same thing using [signal\.windows\.get\_window](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.windows.get_window.html#scipy.signal.windows.get_window) does not work:
```
>>> signal.get_window("taylor",7)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/scipy/signal/windows/windows.py", line 2153, in get_window
    return winfunc(*params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/scipy/signal/windows/windows.py", line 1714, in taylor
    Fm = np.empty(nbar-1)
ValueError: negative dimensions are not allowed
```
I think it should work.

#### Scipy/Numpy/Python version information:

Scipy: 1.6.2

**Comment by ilayn** [comment]
This is covered in the docs 

> If the window requires parameters, then window must be a tuple with the first argument the string name of the window, and the next arguments the needed parameters.

but I agree it is a bit unintuitive.
