### ISSUE TITLE
Boschloo's Test for More Powerful Hypothesis Testing of 2x2 Contingency Tables

### ISSUE THREAD

**Issue by MrTomRod** [scipy/scipy#13896]
Recently, Barnard's test was implemented for analysing 2x2 contingency tables. A variant of Barnard's, called **Boschloo's test**, is uniformly more powerful than Fisher's exact. It applies only if the following condition is met (see [wikipedia](https://en.wikipedia.org/wiki/Boschloo's_test)): The row sums of the contingency table are fixed in advance but the column sums are not.

I propose the addition of a `boschloo_exact` function to `scipy.stats.contingency`.

This has already been discussed on issue #11014 (Barnard's test) and user @V0lantis may already be working on it.

Because the other issue was closed, I'm opening this one to keep track.

**Comment by V0lantis** [comment]
Yep, you are right @MrTomRod. I started working on it but since the previous issue has been closed, by laziness, I stoped. I'll try to finish it then :-) 
Thank you for mentioning me

**Comment by MrTomRod** [comment]
Thanks a lot, @V0lantis!

I will integrate the test into my software and write a paper. Can I cite your effort specifically somehow?

I have a problem with the documentation, though: The assumption of Boschloo's test that the row sums are fixed, but the column sums are not. (See [Wikipedia > Boschloo > Setting](https://en.wikipedia.org/wiki/Boschloo's_test#Setting)) With Fisher's test, it doesn't make a difference and it gives the same result whether or not the input table is transposed. But with Boschloo's, we get different results.

```python3
from scipy.stats import fisher_exact, boschloo_exact
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

tables = ([[43, 40], [10, 39]], [[100, 2], [1000, 5]], [[2, 7], [8, 2]], [[5, 1], [10, 10]], [[5, 15], [20, 20]], [[5, 16], [20, 25]], [[10, 5], [10, 1]], [[5, 0], [1, 4]], [[0, 1], [3, 2]], [[0, 2], [6, 4]], [[2, 7], [8, 2]], [[7, 12], [8, 3]], [[10, 24], [25, 37]])

df = pd.DataFrame(index=[str(t) for t in tables])
df['fisher'] = [fisher_exact(np.array(t))[1] for t in tables]
df['fisher_t'] = [fisher_exact(np.array(t).T)[1] for t in tables]
df['boscholoo'] = [boschloo_exact(np.array(t), n=100).pvalue for t in tables]
df['boscholoo_t'] = [boschloo_exact(np.array(t).T, n=100).pvalue for t in tables]

np.allclose(a=df['fisher'], b=df['fisher_t'])  # True
np.allclose(a=df['boscholoo'], b=df['boscholoo_t'])  # False
```

In the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.boschloo_exact.html), we have this example:
```
                 college professors   scientists
Very Satisfied   74                     31
Dissatisfied     43                     32
```

Because of how the question is asked (we know the number of satisfied/dissatisfied people beforehand and want to know whether college professors are happier with their work than scientists), the row sums are fixed but the column sums are not. Thus, we encode the table like this: `[[74, 31], [43, 32]]`.

If we knew the numbers of college professors and scientists beforehand and wanted to know whether they are satisfied or dissatisfied, we would have to transpose the table (`[[74, 43], [31, 32]]`) and would get a different result.

Am I understanding this correctly? If so, I think extending the documentation would be a good idea. BTW: I found the examples in this paper very helpful: https://onlinelibrary.wiley.com/doi/full/10.1111/1440-1681.12052

**Comment by tupui** [comment]
> I will integrate the test into my software and write a paper. Can I cite your effort specifically somehow?

Glad to read that this new addition to SciPy is helpful. In general we invite people to cite the SciPy article directly https://www.nature.com/articles/s41592-019-0686-2 of course you are free to complete this citation with specific contributors information.

As for the rest I will let @V0lantis answer 😃

**Comment by V0lantis** [comment]
> Thanks a lot, @V0lantis!
> 
> I will integrate the test into my software and write a paper. Can I cite your effort specifically somehow?

This would be very nice of you even if I don't really know how it works. as @tupui said, you still can add the fact that I have written the algorithm following the SciPy's citation itself :-) (you can find all the information you want about me on my GitHub profile I guess, and if not, don't hesitate to send me an email)

> I have a problem with the documentation, though: The assumption of Boschloo's test that the row sums are fixed, but the column sums are not. (See [Wikipedia > Boschloo > Setting](https://en.wikipedia.org/wiki/Boschloo's_test#Setting)) With Fisher's test, it doesn't make a difference and it gives the same result whether or not the input table is transposed. But with Boschloo's, we get different results. This fact and how to properly use the test should be mentioned in the documentation.
> 
> ```python
> from scipy.stats import fisher_exact, boschloo_exact
> import numpy as np
> import pandas as pd
> import matplotlib.pyplot as plt
> 
> tables = ([[43, 40], [10, 39]], [[100, 2], [1000, 5]], [[2, 7], [8, 2]], [[5, 1], [10, 10]], [[5, 15], [20, 20]], [[5, 16], [20, 25]], [[10, 5], [10, 1]], [[5, 0], [1, 4]], [[0, 1], [3, 2]], [[0, 2], [6, 4]], [[2, 7], [8, 2]], [[7, 12], [8, 3]], [[10, 24], [25, 37]])
> 
> df = pd.DataFrame(index=[str(t) for t in tables])
> df['fisher'] = [fisher_exact(np.array(t))[1] for t in tables]
> df['fisher_t'] = [fisher_exact(np.array(t).T)[1] for t in tables]
> df['boscholoo'] = [boschloo_exact(np.array(t), n=100).pvalue for t in tables]
> df['boscholoo_t'] = [boschloo_exact(np.array(t).T, n=100).pvalue for t in tables]
> 
> np.allclose(a=df['fisher'], b=df['fisher_t'])  # True
> np.allclose(a=df['boscholoo'], b=df['boscholoo_t'])  # False
> ```

Thank you for the reproductible code. 

> In the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.boschloo_exact.html), we have this example:
> 
> ```
>                  college professors   scientists
> Very Satisfied   74                     31
> Dissatisfied     43                     32
> ```
> 
> Because of how the question is asked (we know the number of satisfied/dissatisfied people beforehand and want to know whether college professors are happier with their work than scientists), the row sums are fixed but the column sums are not. Thus, we encode the table like this: `[[74, 31], [43, 32]]`.
> 
> If we knew the numbers of college professors and scientists beforehand and wanted to know whether they are satisfied or dissatisfied, we would have to transpose the table (`[[74, 43], [31, 32]]`) and would get a different result.
> 
> Am I understanding this correctly?

Indeed, this is the case. The test basically iterates over all possible 2x2 tables with fixed row sums, but with the column sums varying. Then it computes the maximum pvalue over a nuisance param.

But the point here is, if you transpose your table, the rows won't be the same anymore and therefore, you are not computing the same thing anymore, unless the table is symmetric I suppose.

I hope my explanation was clear enough. Don't hesitate to ask if you need more precision.

>  If so, I think extending the documentation would be a good idea. BTW: I found the examples in this paper very helpful: https://onlinelibrary.wiley.com/doi/full/10.1111/1440-1681.12052

Can I ask you where and how you would like the documentation to be extended so that it would became better ?
