### ISSUE TITLE
Savitzky-Golay filter for even number data

### ISSUE THREAD

**Issue by Pfed-prog** [scipy/scipy#13898]
Savitzky-Golay filter in scipy.signal.savgol_filter implements only for odd numbers of window-lengths but there is substantial amount of literature on even number data.

Reference: 
Jianwen Luo, Kui Ying, Jing Bai, (2005), Savitzky–Golay smoothing and differentiation filter for even number data, Signal Processing, Volume 85, Issue 7, Pages 1429-1434, ISSN 0165-1684, https://doi.org/10.1016/j.sigpro.2005.02.002.

**Comment by czgdp1807** [comment]
Hi. I read the paper from [this link](https://www.researchgate.net/publication/220227041_Savitzky-Golay_smoothing_and_differentiation_filter_for_even_number_data). It seems like the implementation for even number data would be in parallel to existing odd number data with different convolution coefficient vectors. I can try looking into the code to verify. 
Thoughts/comments @Pfed-prog ?
cc @rgommers Can I try this out?

**Comment by Pfed-prog** [comment]
It is very likely that your idea is correct. Here is the matlab implementation of the (Lou et al. 2005) paper [https://www.mathworks.com/matlabcentral/fileexchange/4038-savitzky-golay-smoothing-and-differentiation-filter](link). The package is created by Luo himself and contains discussion on how to enhance the algorithm.

**Comment by czgdp1807** [comment]
Awesome. I will look into this tomorrow and next week. Will comment my findings here and if possible will raise a PR. Thanks for replying.

**Comment by rgommers** [comment]
That Matlab page says the code has no license. So please don't look at it, doing so means you cannot reimplement the same idea in SciPy under a BSD license.

**Comment by czgdp1807** [comment]
Hi. I have opened the above referenced PR. @Pfed-prog As of now I am able to test `savgol_coeffs` with even `window_length` using the closed form results given in the paper. Could you please suggest some examples or properties which can be used to test `savgol_filter` on `window_length`. Thanks.

**Comment by Pfed-prog** [comment]
@czgdp1807 Thank you for the information).
On page 1430 of the paper
