### ISSUE TITLE
Different solvers of `svds` return quite different results

### ISSUE THREAD

**Issue by HQJo** [scipy/scipy#13902]
Solvers 'arpack' and 'lobpcg' in `scipy.sparse.linalg.svds` give quite different results.

Code example:
```ipython
>>> import numpy as np
>>> from scipy.sparse.linalg import svds
>>> import networkx as nx
>>> G = nx.erdos_renyi_graph(100, 0.05)
>>> L = nx.laplacian_matrix(G)
>>> L = L.astype(float)
>>> L
<100x100 sparse matrix of type '<class 'numpy.float64'>'
        with 595 stored elements in Compressed Sparse Row format>
>>> U1, sigma1, Vt1 = svds(L, k=10, which='SM', solver='arpack')
>>> U2, sigma2, Vt2 = svds(L, k=10, which='SM', solver='lobpcg')
>>> U1[:10, 0]
array([-0.001181  ,  0.00150397, -0.0706747 , -0.0741597 , -0.08867621,
       -0.01822176, -0.06213899,  0.02762306,  0.00154229,  0.00461096])
>>> U2[:10, 0]
array([0.08745244, 0.08722969, 0.08729504, 0.0863007 , 0.08716143,
       0.08743749, 0.08759144, 0.08692896, 0.08836112, 0.08750255])
```

Singular vectors given by two solvers have a big difference.
The first eigenvector (singular vector) of the Laplacian matrix is a constant vector \vec{1}  (up to some constant). So the result of lobpcg solver seems right.

Even when I specify the `v0` parameter:
```ipython
>>> v = np.random.rand(100)
>>> U1, sigma1, Vt1 = svds(L, k=10, which='SM', solver='arpack', v0=v)
>>> U2, sigma2, Vt2 = svds(L, k=10, which='SM', solver='lobpcg', v0=v)
>>> U1[:10, 0]
array([ 0.16994681, -0.22514645,  0.15675597, -0.04775263,  0.08946672,
        0.04773851, -0.04691655, -0.05051937, -0.01861545,  0.06445551])
>>> U2[:10, 0]
array([0.08745244, 0.08722969, 0.08729504, 0.0863007 , 0.08716143,
       0.08743749, 0.08759144, 0.08692896, 0.08836112, 0.08750255])
```

- Numpy: 1.19.2
- Scipy: 1.5.2
- Python: Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
- OS: Windows 10 20H2

**Comment by ilayn** [comment]
sigma1 has the correct values and sigma2 misses the zero singular values. But I am not sure what the discrepancy is about.

**Comment by HQJo** [comment]
OK, I think I have found the reason for arpack solver.

https://github.com/scipy/scipy/blob/cb88079050e86f77680100c798b13aa48408a0bb/scipy/sparse/linalg/eigen/arpack/arpack.py#L1886-L1904

In `svds`, singular values greater than `cutoff` are picked out. And their corresponding singular vectors (called `ularge`) are OK.
For small singular values, the singular vectors are generated by `_augmented_orthonormal_cols`, in which a modified gram schmidt process is performed to add random vectors orthogonal to `ularge`. So these random vectors are not correct singular vectors.
https://github.com/scipy/scipy/blob/cb88079050e86f77680100c798b13aa48408a0bb/scipy/sparse/linalg/eigen/arpack/arpack.py#L1695-L1716

I will try to find the reason why lobpcg solver returns wrong singular values next.

**Comment by HQJo** [comment]
So it seems that if you are concerned with singular vectors associated with large singular values, using arpack solver is ok.
But if you are interested in singular vectors associated with singular values close to 0 and use arpack solver, the result is actually random and not trustable.

**Comment by HQJo** [comment]
This PR is related to this issue. #11829

**Comment by HQJo** [comment]
It seems that the reason for lobpcg is the iteration turn. After I set `maxiter` to 50, the returned singular values are correct.

**Comment by ilayn** [comment]
Ah that one... I now remembered.

**Comment by lobpcg** [comment]
@HQJo do you feel that this issue may be closed since you have found the solution? Also, since https://github.com/scipy/scipy/pull/14868 lobpcg now gives a user warning if  maxiter turns out to be too low.

**Comment by HQJo** [comment]
> @HQJo do you feel that this issue may be closed since you have found the solution? Also, since #14868 lobpcg now gives a user warning if maxiter turns out to be too low.

I'm OK with that.
