### ISSUE TITLE
sparse matrix: drop dimension after sum

### ISSUE THREAD

**Issue by katosh** [scipy/scipy#13901]
It seems, summing a sparse matrix over a selected axis leaves a dimension of size 1 that cannot be dropped.

#### Reproducing code example:
```
from scipy.sparse import csr_matrix
print(csc_matrix((2, 2)).sum(axis=1).squeeze().shape)
```
Has the output `(1, 2)` while I expected `(2,)`.

This issue exists for `squeeze()`, `ravel()` and `flatten()` and the other sparse matrix types `bsr_matrix`, `coo_matrix`, `csc_matrix` and `csr_matrix`.

#### Workaround
```
import numpy as np
from scipy.sparse import csr_matrix
print(np.array(csr_matrix((2, 2)).sum(axis=1)).squeeze().shape)
```
returns `(2,)`.

#### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.6.2 1.20.1 sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)
```

**Comment by jakevdp** [comment]
I believe this is intended, because scipy sparse matrices follow the semantics of `np.matrix` rather than `np.array`:
```python
>>> import numpy as np
>>> np.matrix([[1, 2], [4, 5]]).sum(0).squeeze().shape
(1, 2)
```

**Comment by katosh** [comment]
I see. Thank you for the hint! I will close this then.
