### ISSUE TITLE
Stopping taking away credit from small contributors

### ISSUE THREAD

**Issue by mborgerding** [scipy/scipy#13904]
There's no money in open source for most of us.  Credit is one of the few rewards it does give.

When I saw the project list for the [Mars Helicoptor badge on github](https://github.blog/2021-04-19-open-source-goes-to-mars/), I got excited because I have small bits of code in a couple: the [linux kernel ]https://mirrors.edge.kernel.org/pub/linux/kernel/v2.6/ChangeLog-2.6.2) and scipy.

The problem is that in both cases, the commits on the main line were redone and committed by a maintainer (with no malice, I'm sure).  The end result is that I am not a contributor to the project in any automatically traceable sense. 

No gold star on my paper.

Petty maybe, but please try harder to keep the chain of evidence intact.

I know this is not really what an issue is for but I'm not sure how to spread the news -- I am not a blogger with millions of followers. I thought this might help make one project a little better, a little kinder to us little people.

**Comment by ilayn** [comment]
I think there is a mixup because a maintainer when clicks on merge on a PR doesn't overwrite the authorship. And also if you have contributed GitHub marks you as a contributor. So under normal conditions we don't transfer any ownership to the maintainers. 

Could you please point to your Pull request so we can investigate?

**Comment by ilayn** [comment]
Ah I found it #11003 became #12135 later under the impression that the PR went stale so a maintainer picked it up later again. My apologies if this wasn't the case.

**Comment by charris** [comment]
On Tue, Apr 20, 2021 at 6:00 AM Ilhan Polat ***@***.***>
wrote:

> Ah I found it #11003 <https://github.com/scipy/scipy/pull/11003> became
> #12135 <https://github.com/scipy/scipy/pull/12135> later under the
> impression that the PR went stale so a maintainer picked it up later again.
> My apologies if this wasn't the case.
>
> The recommended procedure when taking over a PR is to preserve the
original commits, possibly squashed, and work on top of them so the
starting author gets some credit.

Chuck

>

**Comment by mborgerding** [comment]
To clarify:

* No one did anything wrong. I don't feel slighted, just a little disappointed.
* I'm sure there's something that could've been done differently to make the PR easier to merge intact.    
* I'm not asking for retroactive changes.  

I'm hoping to plant a seed with the maintainers that might grow into a workflow tweak that would better maintain `Author` records instead of turning them into `Co-Author`.

**Comment by ilayn** [comment]
That's quite a good reminder actually. Thanks for that. I've reached out to GitHub to see if anything can be done about this. I'll keep you posted.

**Comment by tupui** [comment]
IMO this is a really a GitHub issue as they have the co-authors visibility. They decided to properly show you as a co-author on some commits, but seemingly do not to consider this enough for the badge. Let see how GitHub respond. I am pretty sure they are getting lot of similar requests as we speak... I would not be surprised to see some updates.

But I hear you. I am a recent core-dev and I was also a bit sad to see that I don't have the badge 😉 As with any metric (or badge in this case), some people will get rewarded and some not, and the rational could seem arbitrary, unfair or might not please everybody.

**Comment by ilayn** [comment]
Quoting GitHub response ;

> I can see how not getting the badge stings - alas there's nothing we can do on our end. Looks like the issue maybe is that he changed his username, too.

so I responded just in case they find a way to put this in. I don't know what else we can do about this.

BUT! your point is not lost on us @mborgerding I will definitely keep an eye out for this . Apologies once again for ruining the fun regardless of its importance and thanks again for bringing this up.

**Comment by matkoniecz** [comment]
> alas there's nothing we can do on our end

Just noting that obviously GitHub can fix this rename bug, just that support is not allowed to escalate (decided to not escalate?) because it is something not worth spending money to fix
