### ISSUE TITLE
Scipy Griddata artifacts

### ISSUE THREAD

**Issue by ngc1535git** [scipy/scipy#13915]
Thank you in advance. Help!!
I am using griddata to interpolate values in a rectilinear grid and then I display the information in a polar plot as shown.  The artifacts are likely due to the triangular geometry it employs.  Is there another tool I can use in place of griddata that will insure smooth results- even at the expense of small errors? Precision in the plot isn't super critical. The code snippet looks like:

    x = 0 # index for transformed az/alt to x array
    y = 1 # index for transformed az/alt to y array
    skybrightness = 2 #index for nsb values array

    xgrid = np.linspace(min(Data[x]), max(Data[x]),gridsize)
    ygrid = np.linspace(min(Data[y]), max(Data[y]),gridsize)

    xCoords = xgrid
    yCoords = ygrid

    xgrid, ygrid = np.meshgrid(xgrid, ygrid, indexing='ij')
    nsb_grid = griddata((Data[x], Data[y]), Data[skybrightness], (xgrid, ygrid), method='linear')

![Capture1](https://user-images.githubusercontent.com/47374461/115639874-84cc3100-a2ca-11eb-9724-d3ff5b63e1be.JPG)

**Comment by ngc1535git** [comment]
I would also add that cubic does not help (nor nearest neighbor) for the interpolation method.

**Comment by tupui** [comment]
Hi, please use StackOverflow or the user mailing list for user related questions.

I will close this for now as it does not seem like there is an issue.

I would say that it'S a visualization question. Also, don't use jet/rainbow anymore (cf matplotlib's documentation which explains perfectly why it's really wrong)
