### ISSUE TITLE
Need Exception / Error for Incorrect and/or misleading analog filter design 

### ISSUE THREAD

**Issue by rwedelich** [scipy/scipy#13922]
My issue is about ...

Sos output is incorrect for analog filter design. I found a comment in fitler_design.py stating as much, but I would expect an error or clearer documentation if this is a known limitation. Instead the code below will generate incorrect SOS coefficients. The combined SOS result in a  higher order analog highpass fitler, not a bandpass. 

For this this ticket I suggest adding a simple exception to the library code to make this obvious. After which, we can open another ticket to add the feature of correct SOS analog filter design.  

#### Reproducing code example:

```
BWsos = signal.butter(order,np.array([flow, fhigh]),btype='bandpass', analog=True, output='sos')
```

#### Scipy/Numpy/Python version information:
version 1.5.4

**Comment by roryyorke** [comment]
This is likely a dup of https://github.com/scipy/scipy/issues/5668 "Need zpk2sos for analog filters".

**Comment by ggkogan** [comment]
I suggest generalizing this statement as it seems to me that this behavior is not specific for SOS filters only. This might pull more attention.

**Comment by roryyorke** [comment]
@ggkogan can you give an example of this bug with a non-SOS representation?

**Comment by ggkogan** [comment]
I think it is a more general issue than the specific case that was described. The definition for the output should be clarified for the other cases too:
```
b, a = iirfilter(N=2, btype='bandpass',
        Wn=np.array([3000, 4850]) / (12400 / 2),
        rp=1, rs=20, output='ba')

len(b)
Out[36]: 5

len(a)
Out[37]: 5
```

**Comment by roryyorke** [comment]
You  expect for N=2 that the returned coefficient arrays should have length 3, like they do for a low-pass filter?

It's probably worth noting in the docs that `N` is interpreted differently for band-pass and band-stop filters, i.e., filter order will be `2 * N`for those, but I don't think it's directly related to the original bug of SOS coefficients being wrong.

**Comment by rwedelich** [comment]
> I suggest generalizing this statement as it seems to me that this behavior is not specific for SOS filters only. This might pull more attention.

Good point. Honestly, just throwing an exception for this case and other similar ones would be fine for now, as that could save people some confusion and time.

**Comment by roryyorke** [comment]
Closed via gh-15085.
