### ISSUE TITLE
Get rid of the few .c.src source files

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#13930]
There's a couple of files that use the `numpy.distutils`-specific C templating `/** begin repeat` pattern:
```
$ rg "begin repeat"
scipy/signal/correlate_nd.c.src
108:/**begin repeat
144:/**begin repeat
296:/**begin repeat

scipy/signal/lfilter.c.src
546:/**begin repeat

scipy/special/_logit.c.src
18:/**begin repeat
```

I would like to get rid of these by replacing them with more standard templated C++. Other solutions also fine, as long as we get rid of this templating method.

The reason for it is that we don't want to support this when implementing Meson build system support. Using a standard method that compilers directly understand is of course also helpful for build times, caching, etc. Plus it's 2021, and this stuff is quite weird and hard to read.

**Comment by ev-br** [comment]
Just throwing it out there: C++ templates or tempita , which we have with cython. Will need to support *.c.in similar to *pyx.in.

**Comment by rgommers** [comment]
Good point @ev-br.

> Will need to support *.c.in similar to *pyx.in.

We don't have `.c.in`, that's not a thing (`.pyx.in` transpiles to `.c`). We do have three `.pyx.in` files:
```
$ find -name "*.pyx.in"
./scipy/linalg/_decomp_update.pyx.in
./scipy/optimize/cython_optimize/_zeros.pyx.in
./scipy/sparse/_csparsetools.pyx.in
```
Those we can keep, but the support is quite different from that of `.c.src`. We will need Cython support indeed, either with the current `tools/cythonize.py` or natively in Meson.

I think C++ is still preferable, because compilers, build systems, etc. all understand it, while there's exactly zero tools that understand `.pyx.in` (VS Code doesn't even have Cython syntax highlighting). But I agree `.pyx.in` is also okay, certainly much better than `.c.src`.

**Comment by ev-br** [comment]
A crude shot for `logit/expit`: https://github.com/scipy/scipy/pull/13931 
The LOC does not go down too much and templates still need to be instantiated manually, but it's likely specific to the scipy.special toolchain.

**Comment by ev-br** [comment]
Since the issue is labelled `task`:

> We will need Cython support indeed, either with the current tools/cythonize.py or natively in Meson.

Given that cythonize.py still has a comment

```
Simple script to invoke Cython (and Tempita) ... while waiting for a proper build system.
```

for I'm not sure how many years and how many copy-pastes and small per-project tweaks, it'd be nice indeed if Meson does provide that long-awaited build system :-).


Also there's a templating engine in f2py, not sure if it depends on numpy.distutils .

**Comment by sturlamolden** [comment]
I guess C++ templates or Cython fused types are the more obvious alternatives.

**Comment by rgommers** [comment]
> Also there's a templating engine in f2py, not sure if it depends on numpy.distutils.

`f2py` has a small dependency on `numpy.distutils` that someone has been trying to disentangle, but I think it doesn't matter for SciPy. My understanding is that we have to change to invoking `python -m numpy.f2py ....` to generate `*module.c` files (Meson has a `run_command` to do such things), and then we have plain `.c` and `.f` files that we can build normally.

**Comment by rgommers** [comment]
> I guess C++ templates or Cython fused types are the more obvious alternatives.

Yes, Cython's fused types are handy when they're enough. `Cython.Tempita` is actually not public API, even though we rely on it. The one mention of templating in Cython docs is https://cython.readthedocs.io/en/latest/src/userguide/wrapping_CPlusPlus.html#templates.

**Comment by rgommers** [comment]
> this particular fix is going to fit in a single screen, so it'll be fine; but generally the way it all unfolds does make tempita templating more and more attractive. Esp for messier cases like the giant switch over typecodes in `correlate_nd`.

I looked at Tempita some more. It's basically unmaintained (last update 2013); the version Cython vendored got some more fixes. It's super simple code though, so maintenance is not a real worry. We should just vendor Tempita ourselves in `tools/` and make it a command-line thing. And then the Meson support will look something like:

```python
fname_pyx = custom_target('fname_pyx',
  output : 'fname.pyx.in',
  input : 'fname.pyx',
  command : [tools/tempita, '@INPUT@', '-o', '@OUTPUT@'],
)

slib = py3.extension_module('fname',
  'fname.pyx',
  dependencies : py3_dep)
```

**Comment by ilayn** [comment]
It is actually very straightforward and jinja2-like. Quite a nice tool to write separate instances rapidly while Cyton can still crash with fused types in strange ways. 

The new major Cython version is said to fix all those quirks but until then `tempita` makes it quite convenient to spit out the unrolled versions of the template with no fusing necessary.

**Comment by rgommers** [comment]
Thanks Evgeni!
