### ISSUE TITLE
BENCH: python runtests.py --bench-compare not working?

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#13939]
#### Reproducing code example:
From the command line:
```
python runtests.py --bench-compare master optimize_linprog
```
(Problem not specific to this commit or benchmark)

#### Error message:
```
(scipydev) C:\Users\matth\scipy>python runtests.py --bench-compare master optimize_linprog
Traceback (most recent call last):
  File "runtests.py", line 565, in <module>
    main(argv=sys.argv[1:])
  File "runtests.py", line 285, in main
    run_asv(cmd)
  File "runtests.py", line 554, in run_asv
    return subprocess.call(cmd, env=env, cwd=cwd)
  File "C:\Users\matth\Anaconda3\envs\scipydev\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\matth\Anaconda3\envs\scipydev\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\matth\Anaconda3\envs\scipydev\lib\subprocess.py", line 1148, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\matth\Anaconda3\envs\scipydev\lib\subprocess.py", line 555, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'

(scipydev) C:\Users\matth\scipy>
```

#### Scipy/Numpy/Python version information:

```
1.7.0.dev0+864.e260458 1.19.2 sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)
```

**Comment by peterbell10** [comment]
I'm able to use `--bench-compare without problems. I think the command should be:
```
python runtests.py --bench-compare master --bench optimize_linprog
```

Could do with a better error message though.

**Comment by mdhaber** [comment]
Interesting. I tried that - with `--bench` between `master` and `-optimize_linprog` - and I get the same error.

**Comment by peterbell10** [comment]
@mdhaber never mind, I was wrong. I just looked  at the code and the `--bench` flag implicitly set by using `--bench-compare`. 

I think what's actually going on is one of the `git` calls is failing. Can you post your full terminal output, not just the python error?

**Comment by mdhaber** [comment]
That's really all there is. I've update the above to show the command prompt before and after.

**Comment by tupui** [comment]
Searching a bit for this issue I can see that some people have the same calling some Matplotlib. Maybe you need to update your dependencies?

**Comment by mdhaber** [comment]
Thanks @tupui. Updated dependencies, but no change.

**Comment by rgommers** [comment]
Windows shells can be a pain, where things are not working in `subprocess`. It's these two lines, why not run just those in a Python script for debugging:
```python
            out = subprocess.check_output(['git', 'rev-parse', commit_a])
            commit_a = out.strip().decode('ascii')
```

**Comment by perimosocordiae** [comment]
Perhaps unrelated, but I was having issues getting `--bench-compare` working as well.

I found that it was trying to run `git rev-list HEAD ^1.6.0 --count` to produce a proper version name for my commit, but the branch I was on didn't have tags fetched so git complained that it didn't know what to do with `^1.6.0`. This led to an invalid version name, which may or may not be related to the `pip wheel` failure later in the build process.

**Comment by mdhaber** [comment]
I don't suppose `runtest.py` will be maintained anymore, so closing.
