### ISSUE TITLE
linalg.pinvh() works inconsistently on Windows and Linux

### ISSUE THREAD

**Issue by GBR-613** [scipy/scipy#13945]
linalg.pinvh() works inconsistently on Windows and Linux

#### Reproducing code example:

```
import numpy as np
from scipy import linalg
covariance = np.load("bug_covariance.npy", allow_pickle=True)
precision = linalg.pinvh(covariance)
np.save("precision.npy", precision)
```

#### Error message:

The generated file is different on Windows and Linux

#### Scipy/Numpy/Python version information:

```
1.6.3 1.18.3 sys.version_info(major=3, minor=8, micro=1, releaselevel='final', serial=0)
```
The problem was found first with v1.4.1, still appears with v1.6.3.

Attached is a zip with "bug_covariance.npy" to reproduce the problem and the outcome files I got on Windows 10 and Linux Ubuntu 16.04.
[scipy-bug.zip](https://github.com/scipy/scipy/files/6385079/scipy-bug.zip)

Please notice, not with any input the problem is reproduced.  In my case, it occurred with about 10% of datasets.

**Comment by GBR-613** [comment]
If you have a version in which the problem does not appear, please let me know.

**Comment by GBR-613** [comment]
*Update*
The problem is with linalg.decomp.eigh(), not linalg.pinvh().

Try the following code:
```
import numpy as np
from scipy import linalg
import platform

covariance = np.load("bug_covariance.npy", allow_pickle=True)
drv_str = [None, "ev", "evd", "evr"]   #, "evx", "gv", "gvd", "gvx"]
for drv in drv_str:
    s, u = linalg.decomp.eigh(covariance, lower=True, check_finite=False, driver=drv)
    np.save(platform.system() + "_" + str(drv) + "_s.npy", s)
    np.save(platform.system() + "_" + str(drv) + "_u.npy", u)
```
All generated files in Windows and Linux are different.
Unlike suggestion in issue #12515, switching to another driver does not help.

**Comment by ilayn** [comment]
Thanks @GBR-613 Do you mind explaining what the difference is between two platforms? Very small fraction of our users have dual systems or access to such. 

For others here is the covariance array

```python
covariance = np.array([[0.5512258143945572, -0.09338463732633583, -0.23222506684475697, 0.5872634023605511, 0.5932115796988717, 0.4062499211943958, -0.25848160981763824, -0.5072528531078639, -0.5072528531078639, -0.2450558131873405, 0.0, -0.6341703724606732, -0.4812434757865452, -0.3121089719794764, -0.41793412751086334, -0.4607233325336611],
                       [-0.09338463732633583, 0.03402326600339467, 0.10861353664278255, -0.05810036326157662, -0.059979129356882536, -0.01877357952085975, 0.10932713767151019, 0.16924268435757117, 0.16924268435757117, -0.08558001073605499, 0.0, 0.2682281020538191, 0.2035462862056251, 0.1343460775962431, 0.17896294085979456, 0.19486710578721964],
                       [-0.23222506684475697, 0.10861353664278255, 0.8820886084450233, -0.6102632706884292, -0.11187693942442885, -0.5392347381762373, 0.32371713081087344, 0.513852286590436, 0.513852286590436, -0.31853900309491245, 0.0, 0.7942221249823839, 0.6026995781749495, 0.5494075490668114, 0.6722500858046406, 0.5770005665418269],
                       [0.5872634023605511, -0.05810036326157662, -0.6102632706884292, 1.23986482915276, 0.7402760990777693, 1.1048799862630243, -0.0917958168857802, -0.3341187405726355, -0.3341187405726355, -0.6119279718369385, 0.0, -0.2252159734917225, -0.17090630939642038, -0.255085554448495, -0.28385016587542955, -0.16361889226124907],
                       [0.5932115796988717, -0.059979129356882536, -0.11187693942442885, 0.7402760990777693, 0.729089019129614, 0.5659390531650853, -0.13121371862000739, -0.35992643158493615, -0.35992643158493615, -0.5485511019645759, 0.0, -0.321925621199539, -0.2442949270709051, -0.15787953059754173, -0.21163390118558534, -0.23387823125751322],
                       [0.4062499211943958, -0.01877357952085975, -0.5392347381762373, 1.1048799862630243, 0.5659390531650853, 1.0362590530244882, 0.026804433638404634, -0.12666953192313163, -0.12666953192313163, -0.5964673121862192, 0.0, 0.06576319946342475, 0.04990474494389117, -0.12174345371711949, -0.101348851537606, 0.04777681476556806],
                       [-0.25848160981763824, 0.10932713767151019, 0.32371713081087344, -0.0917958168857802, -0.13121371862000739, 0.026804433638404634, 0.3594644841900329, 0.5389237292228376, 0.5389237292228376, -0.3467941303817248, 0.0, 0.8819262847597034, 0.6692543346332277, 0.4325163910243478, 0.5797783335987323, 0.6407174390486342],
                       [-0.5072528531078639, 0.16924268435757117, 0.513852286590436, -0.3341187405726355, -0.35992643158493615, -0.12666953192313163, 0.5389237292228376, 0.8486054299654654, 0.8486054299654654, -0.35817250418990937, 0.0, 1.3222196439052827, 1.0033732334691903, 0.656577667531267, 0.8768616660732569, 0.960589562577349],
                       [-0.5072528531078639, 0.16924268435757117, 0.513852286590436, -0.3341187405726355, -0.35992643158493615, -0.12666953192313163, 0.5389237292228376, 0.8486054299654654, 0.8486054299654654, -0.35817250418990937, 0.0, 1.3222196439052827, 1.0033732334691903, 0.656577667531267, 0.8768616660732569, 0.960589562577349],
                       [-0.2450558131873405, -0.08558001073605499, -0.31853900309491245, -0.6119279718369385, -0.5485511019645759, -0.5964673121862192, -0.3467941303817248, -0.35817250418990937, -0.35817250418990937, 1.003711138291237, 0.0, -0.850840270557408, -0.645664551551726, -0.4172711138323071, -0.5593423880737115, -0.6181335204671046],
                       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
                       [-0.6341703724606732, 0.2682281020538191, 0.7942221249823839, -0.2252159734917225, -0.321925621199539, 0.06576319946342475, 0.8819262847597034, 1.3222196439052827, 1.3222196439052827, -0.850840270557408, 0.0, 2.1637574947150218, 1.6419785955554367, 1.0611551088093691, 1.4224541622993516, 1.5719648962654917],
                       [-0.4812434757865452, 0.2035462862056251, 0.6026995781749495, -0.17090630939642038, -0.2442949270709051, 0.04990474494389117, 0.6692543346332277, 1.0033732334691903, 1.0033732334691903, -0.645664551551726, 0.0, 1.6419785955554367, 1.2460239721167523, 0.8052630571979911, 1.0794367175430122, 1.1928937133375053],
                       [-0.3121089719794764, 0.1343460775962431, 0.5494075490668114, -0.255085554448495, -0.15787953059754173, -0.12174345371711949, 0.4325163910243478, 0.656577667531267, 0.656577667531267, -0.4172711138323071, 0.0, 1.0611551088093691, 0.8052630571979911, 0.5637144607597732, 0.7382566899019867, 0.770926771884302],
                       [-0.41793412751086334, 0.17896294085979456, 0.6722500858046406, -0.28385016587542955, -0.21163390118558534, -0.101348851537606, 0.5797783335987323, 0.8768616660732569, 0.8768616660732569, -0.5593423880737115, 0.0, 1.4224541622993516, 1.0794367175430122, 0.7382566899019867, 0.9732895752518492, 1.0334097121063082],
                       [-0.4607233325336611, 0.19486710578721964, 0.5770005665418269, -0.16361889226124907, -0.23387823125751322, 0.04777681476556806, 0.6407174390486342, 0.960589562577349, 0.960589562577349, -0.6181335204671046, 0.0, 1.5719648962654917, 1.1928937133375053, 0.770926771884302, 1.0334097121063082, 1.1420289201200118]])
```

I don't see the difference between the files you have included in the original post. Linux precision and Win Precision differ by at most 

```
np.max(np.abs(L-W))
Out[18]: 5.828670879282072e-16
```

which is ~2*`eps` well beyond the negligible difference. What were you expecting to find?

**Comment by GBR-613** [comment]
@ilayn there are too many differences between Windows and Linux to elaborate in one post :-)
I don't believe one needs dual-boot system to work on this issue. I personally use Windows notebook and Linux virtual machine running on AWS, but I don't believe AWS maters here. You can easy get a virtual machine powered by QEMU or Oracle VirtualBox, they both are free.
I am expecting to get results completely equal, so `diff --binary` will not notice any difference.  At least, I don't understand what a justification can be for the difference.  
I have to admit that I don't use scipy "directly". My code uses some library which uses other library which uses sklearn which uses linalg.pinvh().  
The problem in our site raised when my co-worker tried to re-run my code on Mac and got results different from those I got on my Linux. (I don't believe Mac plays any role here: if the result is different between Windows and Linux, why Mac should be an exception?) My code generates results in range between 0 and 1.0, and the differences are in 3rd position after the decimal point: for such the range such the difference is hardly negligible. I started debugging and found that the difference begins in results of linalg.pinvh(). 
It looks like during a lot of calculations the small differences are accumulated into a large one.
However I can not guarantee that this is the only one problem.  I keep working on that.

**Comment by ilayn** [comment]
> I am expecting to get results completely equal, so diff --binary will not notice any difference. At least, I don't understand what a justification can be for the difference.

With floating point operations this will never be possible but only up to the machine precision which is around 2.2e-16 for most systems today.

> My code generates results in range between 0 and 1.0, and the differences are in 3rd position after the decimal point: for such the range such the difference is hardly negligible

That's certainly  possible but depends heavily on what you do. If I multiply the results with 1e12 obviously they will start changing around 3rd decimal. So without knowing what you do I don't see any problem with pinvh or eigh yet

**Comment by GBR-613** [comment]
OK, you persuaded me.  I am closing the ticket.
