### ISSUE TITLE
vectorize expm

### ISSUE THREAD

**Issue by nschloe** [scipy/scipy#13943]
I would like to compute the matrix exponential of many small matrices at once.  This works, but is slow:
```python
import numpy as np
import scipy.linalg


A = np.random.rand(3, 3, 777)

exp_A = np.array([
    scipy.linalg.expm(dt * W[..., k])
    for k in range(m)
])

scipy.linalg.expm(A)
```
It'd be great of `expm` could be vectorized.

**Comment by ilayn** [comment]
Duplicate of #12838

**Comment by ilayn** [comment]
Let's continue in the linked one. I guess we need this since more than 3 times this has come up

**Comment by nschloe** [comment]
Thanks for point that out!
