### ISSUE TITLE
N=4 must not exceed M=3

### ISSUE THREAD

**Issue by mahengrui1** [scipy/scipy#13969]
My issue is about ... from scipy.optimize import curve_fit

#### Reproducing code example:

```
x = [0,75,745.5027446]
x = np.array(x).astype(float)
num = [1e-6,5,135.4783469]
y = np.array(num).astype(float)
param_bounds=([0,0,0,0],[np.inf,np.inf,np.inf,np.inf])
popt, pcov = curve_fit(func, x, y, bounds=param_bounds)
  ...
```

#### Scipy/Numpy/Python version information:
```
1.5.2 sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)

```
-->

In my opinion, if the curving lack enough data, it be better says: I need 4 points for 3 paras, not 'N=4 must not exceed M=3'

**Comment by AtsushiSakai** [comment]
The code is here: 
https://github.com/scipy/scipy/blob/4ec4ab8d6ccc1cdb34b84fdcb66fde2cc0210dbf/scipy/optimize/minpack.py#L413-L415

I agree the error message can be improved.

**Comment by Mazensayed91** [comment]
I think this will be meaningful

if n > m: 
     raise TypeError('Improper input: The number of the initial parameters=%s must not exceed the number of model parameters needed=%s' % (n, m))

**Comment by rkern** [comment]
`m` is not "the number of model parameters needed". It's the number of data points (in most contexts where `leastsq()` is used).
