### ISSUE TITLE
Dispatchable: Understending Scipy Implementation

### ISSUE THREAD

**Issue by eduardo4jesus** [scipy/scipy#13965]
I am trying to understand the implementation of the DCT function. But the architecture of the scipy library is really confusing for me. I do have a fair experience with python programming, but when it comes to the software engineering of libraries like scipy, I really need guidance.

Could anyone shine some light on it? Where do I actually find the source code of the functions? Is it written in C?
What is [`Dispatchable`](https://github.com/scipy/scipy/blob/30db3618e897887217b16c0ca1cb817d7aaf9eb3/scipy/fft/_realtransforms.py#L123)?

How lines like these actually work?
```
    return (Dispatchable(x, np.ndarray),)
```

**Comment by rkern** [comment]
The functions in `scipy.fft` use the somewhat new multidispatch mechanism through [`uarray`](https://uarray.org/en/latest/) to allow the functions in `scipy.fft` have their backend replaced, especially depending on the exact type of array-like object. For example, a CUDA-based tensor object from a deep learning framework could invoke CuFFT. I think (not 100% certain) that this also allows you to slot in your own preferred FFT library as a backend even for plain-old numpy `ndarray` objects. We used to have multiple FFT backends selected at build time, but it was difficult to add new ones, and not easy to support incompatibly-licensed FFT libraries like the popular FFTW. I _think_ this new multidispatch mechanism allows that to be slotted in at runtime.

You can follow the imports for `Dispatchable` to here, where we have a vendorized copy of `uarray` as a backup: https://github.com/scipy/scipy/blob/master/scipy/_lib/_uarray/_backend.py

And here is the out-of-box default backend for `scipy.fft`:
https://github.com/scipy/scipy/blob/master/scipy/fft/_backend.py

So we can see [here](https://github.com/scipy/scipy/blob/master/scipy/fft/_backend.py#L19) that we are using the implementations in [`scipy.fft._pocketfft`](https://github.com/scipy/scipy/blob/master/scipy/fft/_pocketfft/) as the defaults. And from there, you'll have to dive into the C++ and work your way through the template logic.

It's a lot of indirection, I will grant you. At the moment, we only use this mechanism in `scipy.fft`. It's possible it will extend to `scipy.linalg`, as it also has some need to swap out backends like that, but it probably won't be a widely used pattern across all of `scipy`.

**Comment by eduardo4jesus** [comment]
@rkern, Thank you so much.
