### ISSUE TITLE
An error occurred when using scipy.io.wavfile of scipy 1.6 version or higher to read the wav file

### ISSUE THREAD

**Issue by Hydralisk2333** [scipy/scipy#13988]
When I use scipy version 1.6 and above to read a single-channel wav file, the length of the signal is half of the original signal length. The reading of this signal is completely wrong. In order to verify whether it is a problem with this version of the library, I read the same wav file with a library below version 1.6 and matlab, and finally found that there is really some problem with this version of the code.

#### Reproducing code example:

```
import scipy.io.wavfile as wav
filePath = '1.wav'
fs, signalWav = wav.read(filePath)
print(len(signalWav))
```

#### Error message:

```
47488
(Actually the output should be 94976)
```

**Comment by tupui** [comment]
Hi, thanks for reporting. Could you give more info about your file?
@endolith I see you modified the functions "recently". Maybe you would know?

**Comment by endolith** [comment]
Please post the wav file, or at least its header if you can't publish the whole thing

**Comment by Hydralisk2333** [comment]
> Please post the wav file, or at least its header if you can't publish the whole thing

How do I send the file to you? May I email it to you?

**Comment by endolith** [comment]
Sure, my username at gmail.  Or post it on wetransfer.com or something

**Comment by endolith** [comment]
Ocenaudio says it's 47488 samples, too:

![image](https://user-images.githubusercontent.com/58611/117233863-eb386f80-adf1-11eb-9eb8-e70c85a6c72f.png)

It shows a tone at 20000 Hz, sampled at 44100 Hz.

Looking through the header:

```
52 49 46 46 24 E6 02 00 57 41 56 45 66 6D 74 20 10 00 00 00 01 00 01 00 44 AC 00 00 88 58 01 00 04 00 10 00
```

- wFormatTag = 0x0001 = PCM
- nChannels = 0x0001 = 1-channel
- nSamplesPerSec = 0x0000AC44 = 44100 Hz
- nAvgBytesPerSec = 0x00015888 = 88200 bytes per second
- nBlockAlign = 0x0004 = 4 bytes per sample
- wBitsPerSample = 0x0001 = 16 bits per sample

So the WAV header is self-contradictory.

> If wFormatTag is WAVE_FORMAT_PCM, nAvgBytesPerSec should be equal to the product of nSamplesPerSec and nBlockAlign.

This is not met.  44100 * 4 = 176400, not 88200

>  If wFormatTag is WAVE_FORMAT_PCM … nBlockAlign must be equal to the product of nChannels and wBitsPerSample divided by 8 (bits per byte).

This is likewise not met. 1 * 16 / 8 = 2, not 4.

The data chunk is 0x0002E600 = 189952 bytes long.  It looks like it really is 16-bit samples, in 2-byte blocks, so the total number of samples is 94976 and it's nBlockAlign that's wrong; it should be 2.

SciPy uses nBlockAlign to determine what data format to use, so this file can't be read.  https://github.com/scipy/scipy/pull/12287/files#diff-1ab1d5855c83ac385f9623f5890c00643dc510ecb62662c557a05b928c9cedaaR426

**Comment by Hydralisk2333** [comment]
> Ocenaudio says it's 47488 samples, too:
> 
> ![image](https://user-images.githubusercontent.com/58611/117233863-eb386f80-adf1-11eb-9eb8-e70c85a6c72f.png)
> 
> It shows a tone at 20000 Hz, sampled at 44100 Hz.
> 
> Looking through the header:
> 
> ```
> 52 49 46 46 24 E6 02 00 57 41 56 45 66 6D 74 20 10 00 00 00 01 00 01 00 44 AC 00 00 88 58 01 00 04 00 10 00
> ```
> 
> * wFormatTag = 0x0001 = PCM
> * nChannels = 0x0001 = 1-channel
> * nSamplesPerSec = 0x0000AC44 = 44100 Hz
> * nAvgBytesPerSec = 0x00015888 = 88200 bytes per second
> * nBlockAlign = 0x0004 = 4 bytes per sample
> * wBitsPerSample = 0x0001 = 16 bits per sample
> 
> So the WAV header is self-contradictory.
> 
> > If wFormatTag is WAVE_FORMAT_PCM, nAvgBytesPerSec should be equal to the product of nSamplesPerSec and nBlockAlign.
> 
> This is not met. 44100 * 4 = 176400, not 88200
> 
> > If wFormatTag is WAVE_FORMAT_PCM … nBlockAlign must be equal to the product of nChannels and wBitsPerSample divided by 8 (bits per byte).
> 
> This is likewise not met. 1 * 16 / 8 = 2, not 4.
> 
> The data chunk is 0x0002E600 = 189952 bytes long. It looks like it really is 16-bit samples, in 2-byte blocks, so the total number of samples is 94976 and it's nBlockAlign that's wrong; it should be 2.
> 
> SciPy uses nBlockAlign to determine what data format to use, so this file can't be read. https://github.com/scipy/scipy/pull/12287/files#diff-1ab1d5855c83ac385f9623f5890c00643dc510ecb62662c557a05b928c9cedaaR426
> 
> [`bytes_per_second` is read](https://github.com/endolith/scipy/blob/master/scipy/io/wavfile.py#L356), but ignored.
> 
> I guess we should check for consistency and raise an exception in cases like this?

It turns out that there are some problems with my data. Thank you for your answers.

**Comment by Hydralisk2333** [comment]
> Ocenaudio says it's 47488 samples, too:
> 
> ![image](https://user-images.githubusercontent.com/58611/117233863-eb386f80-adf1-11eb-9eb8-e70c85a6c72f.png)
> 
> It shows a tone at 20000 Hz, sampled at 44100 Hz.
> 
> Looking through the header:
> 
> ```
> 52 49 46 46 24 E6 02 00 57 41 56 45 66 6D 74 20 10 00 00 00 01 00 01 00 44 AC 00 00 88 58 01 00 04 00 10 00
> ```
> 
> * wFormatTag = 0x0001 = PCM
> * nChannels = 0x0001 = 1-channel
> * nSamplesPerSec = 0x0000AC44 = 44100 Hz
> * nAvgBytesPerSec = 0x00015888 = 88200 bytes per second
> * nBlockAlign = 0x0004 = 4 bytes per sample
> * wBitsPerSample = 0x0001 = 16 bits per sample
> 
> So the WAV header is self-contradictory.
> 
> > If wFormatTag is WAVE_FORMAT_PCM, nAvgBytesPerSec should be equal to the product of nSamplesPerSec and nBlockAlign.
> 
> This is not met. 44100 * 4 = 176400, not 88200
> 
> > If wFormatTag is WAVE_FORMAT_PCM … nBlockAlign must be equal to the product of nChannels and wBitsPerSample divided by 8 (bits per byte).
> 
> This is likewise not met. 1 * 16 / 8 = 2, not 4.
> 
> The data chunk is 0x0002E600 = 189952 bytes long. It looks like it really is 16-bit samples, in 2-byte blocks, so the total number of samples is 94976 and it's nBlockAlign that's wrong; it should be 2.
> 
> SciPy uses nBlockAlign to determine what data format to use, so this file can't be read. https://github.com/scipy/scipy/pull/12287/files#diff-1ab1d5855c83ac385f9623f5890c00643dc510ecb62662c557a05b928c9cedaaR426
> 
> [`bytes_per_second` is read](https://github.com/endolith/scipy/blob/master/scipy/io/wavfile.py#L356), but ignored.
> 
> I guess we should check for consistency and raise an exception in cases like this?

I think checking consistency is a good idea. Using matlab to analyze the same data will get different results, which may make people feel a little confused. Thanks for your answer.

**Comment by tupui** [comment]
Thanks @endolith for your help.

@Hydralisk2333 would you like to help here?

**Comment by Hydralisk2333** [comment]
> Thanks @endolith for your help.
> 
> @Hydralisk2333 would you like to help here?

Sorry, I am busy with other tasks, and may not be able to participate in the enhancement.

**Comment by endolith** [comment]
https://github.com/endolith/scipy/commit/76cfcd5afa156c87760d08da5a07f8cb4df5a37c I just need to make a test
