### ISSUE TITLE
scipy.sparse.csgraph.dijkstra not working for multiple indices

### ISSUE THREAD

**Issue by tretherington** [scipy/scipy#13993]
Hello!

I think I've found a bug in the [scipy.sparse.csgraph.dijkstra](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csgraph.dijkstra.html#scipy.sparse.csgraph.dijkstra) function relating to the indices parameter.

All works perfectly when I feed in one index, but when I feed in two indices, only the first index seems to be processed, and the resulting dist_matrix always has the shape [1, n_nodes] when it is supposed to have the shape (n_indices, n_nodes,).

I've tried to follow the function's underlying code, but I'm getting lost, so I can't suggest where the issue is, but the following example should serve to demonstrate the problem.  In the three calls to the function can get the distances to index 0, and then index 1, but when I ask for the distances to 0 and 1 I only get back the 0 distances.

```
import numpy as np # 1.20.2
from scipy.sparse import csgraph # version 1.6.3

M = np.array([[ 0,  7,  9,  0, 0, 14],
              [ 7,  0, 10, 15, 0,  0],
              [ 9, 10,  0, 11, 0,  2],
              [ 0, 15, 11,  0, 6,  0],
              [ 0,  0,  0,  6, 0,  9],
              [14,  0,  2,  0, 9,  0]])

sp0 = csgraph.dijkstra(csgraph=M, 
                      indices = np.array([0]))

print(sp0[0])

sp1 = csgraph.dijkstra(csgraph=M, 
                      indices = np.array([1]))

print(sp1[0])

sp01 = csgraph.dijkstra(csgraph=M, 
                      indices = np.array([0, 1]))

print(sp01[0])
```

**Comment by tupui** [comment]
Hi, in this case I think that using `return_predecessors=True` is doing what you want.

**Comment by fuglede** [comment]
Hi @tretherington, in considering `sp01[0]`, what you're effectively saying is "give me only the distances from 0"; from the sound of it, what you're really looking for is `sp01` itself, the length two array whose two elements are the distances from 0 and 1 respectively?

```python
In [4]: print(sp0)
[[ 0.  7.  9. 20. 20. 11.]]

In [6]: print(sp1)
[[ 7.  0. 10. 15. 21. 12.]]

In [7]: print(sp01)
[[ 0.  7.  9. 20. 20. 11.]
 [ 7.  0. 10. 15. 21. 12.]]
```

**Comment by tretherington** [comment]
Hi @tupui and @fuglede thanks so much for the help, embarrassingly in turns out the bug was in my head! :grimacing:

What was confusing me was that the number of elements being returned from the function changes based on the `predecessors`  argument, and my code wasn't adapting to that - which seems really obvious to me today, but for some reason I just wasn't able to see yesterday.

I really appreciate the fresh eyes :thumbsup:, closing issue now, apologies for the confusion.

**Comment by tupui** [comment]
No problem thanks @tretherington for closing also! If something is unclear in the documentation, feel free to propose some improvements. We are always looking for ways to improve.
