### ISSUE TITLE
n degree derivative not working, if n = 2 or any +ve integer greater than 1, the function derivative  always gives zero.

### ISSUE THREAD

**Issue by ramjan-raeen** [scipy/scipy#13994]
https://github.com/scipy/scipy/blob/v1.6.3/scipy/misc/common.py#L75-L145

Hi 
n degree derivative is not working.

```python
from scipy.misc import derivative

def f(x):
    return x**3

plt.figure(figsize=(20,10))

plt.plot(time, f(time), 
         color='purple', 
         lw=3,
         label='Particle Moving Path')

plt.plot(time, derivative(f, time), 
         color='green', 
         lw=3,
         label='Velocity Graph')

plt.plot(time, derivative(f, time, n=2), 
         color='red', 
         lw=3,
         label='Acceleration Graph')

plt.legend(loc='center left')
plt.xlabel('Time')
plt.ylabel('Position of Particle')
plt.grid(True)
```

![Screenshot 2021-05-06 at 1 58 34 PM](https://user-images.githubusercontent.com/40716654/117266798-3d6da500-ae73-11eb-8bf4-dd5bbf5c2b53.png)

**### Problem: Red line should be straight line y'' = x**

**Comment by tupui** [comment]
I guess here you just have to adapt the parameter `dx`. By default `dx=1`.
Because it does work:

```python
>>> x = np.array([1, 2, 3, 4, 5])
>>> 6*x
array([ 6, 12, 18, 24, 30])
>>> derivative(f, x, n=2)
array([ 6., 12., 18., 24., 30.])
```

**Comment by ramjan-raeen** [comment]
Here , I got 
Thanks for response
![Screenshot 2021-05-06 at 3 04 30 PM](https://user-images.githubusercontent.com/40716654/117276868-eec50880-ae7c-11eb-99d6-227588651985.png)

Sorry It was my mistake, the bin of y-axis grid was too large so red line appear parallel to x-axis. But I got solution.

from scipy.misc import derivative
import numpy as np
import matplotlib.pyplot as plt


time = np.linspace(0, 20, 100)

def f(x):
    return x**3



plt.figure(figsize=(20,10))

plt.plot(time, f(time), 
         color='purple', 
         lw=3,
         label='Particle Moving Path')

plt.plot(time, derivative(f, time), 
         color='green', 
         lw=3,
         label='Velocity Graph')

plt.plot(time, derivative(f, time, n=2), 
         color='red', 
         lw=3,
         label='Acceleration Graph')
plt.xlim(0, 15)
plt.ylim(0, 1000)

plt.legend(loc='center left')
plt.xlabel('Time')
plt.ylabel('Position of Particle')
plt.grid(True)

**Comment by tupui** [comment]
Thank you for the feedback, glad to read that you found a solution to your problem. Then I am closing this issue.

**Comment by ramjan-raeen** [comment]
I want to contribute for calculus library. How can I do?

**Comment by tupui** [comment]
What do you mean exactly?

If you want to contribute to SciPy, please have a look at our [contributing guide](https://scipy.github.io/devdocs/dev/contributor/contributor_toc.html) and a good place to start is to look on our issue tracker at issues labeled [good first issue](https://github.com/scipy/scipy/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)

**Comment by ramjan-raeen** [comment]
Thank you, I'll go through this.

**Comment by ev-br** [comment]
An obligatory note: in all but very special old code (stats.distributuons being one example), use approx_derivative instead.

**Comment by tupui** [comment]
@ev-br sorry what do you mean? Are you talking about `approx_fprime`?

**Comment by ev-br** [comment]
Nope, this one: https://github.com/scipy/scipy/blob/master/scipy/optimize/_numdiff.py#L257
