### ISSUE TITLE
splu 1000x slower on CircleCI Ubuntu, but only for some matrices

### ISSUE THREAD

**Issue by guyer** [scipy/scipy#13999]
- I have isolated extreme slowness in `scipy.sparse.linalg.splu()` for some, but not most, matrices when running on CircleCI Ubuntu with `continuumio/miniconda3` Docker image. 

- Call to `splu()` takes ~300 s on CircleCI (Ubuntu) for certain matrices, compared to <0.5 s on AppVeyor (Windows) and Travis-CI (macOS).

- Our test suite invokes `splu()` nearly three thousand times without exhibiting this slowdown in the vast majority of cases.

- Same test on a Debian machine or running `continuumio/miniconda3` Docker image on macOS runs in <0.5 s.

- Installing `blas=*=mkl` speeds this step up to ~20 s... so only 100x too slow.

#### Reproducing code example:

https://github.com/guyer/fipy/tree/slowsplu contains code, data files, and CI scripts that demonstrate the issue. 
Specifically, when `timelu.py` loads [`phase-matrix.mtx`](https://raw.githubusercontent.com/usnistgov/fipy/0f3676b17f02d3dd1107d7f0d944a02ce476ab1b/phase-matrix.mtx).

https://github.com/usnistgov/fipy/pull/808 is a pull request that invokes the CIs.

##### timelu.py
```python
import logging
from scipy.sparse.linalg import splu
from scipy.io import mmread

logging.basicConfig(level=logging.DEBUG, format='%(asctime)s:%(levelname)s:%(message)s')

logging.debug("START")

L = mmread("phase-matrix.mtx")

logging.debug("mmread")

Lcsc = L.asformat("csc")

logging.debug("asformat_csc")

LU = splu(Lcsc,
          diag_pivot_thresh=1.,
          relax=1,
          panel_size=10,
          permc_spec="COLAMD")

logging.debug("splu")

logging.debug("END")
```

#### Output:

```
2021-05-07 03:35:15,947:DEBUG:START
2021-05-07 03:35:16,261:DEBUG:mmread
2021-05-07 03:35:16,267:DEBUG:asformat_csc
2021-05-07 03:40:49,060:DEBUG:splu
2021-05-07 03:40:49,060:DEBUG:END
```

Compare to, e.g, Travis-CI macOS instance:
```
2021-05-07 03:36:52,013:DEBUG:START
2021-05-07 03:36:52,412:DEBUG:mmread
2021-05-07 03:36:52,417:DEBUG:asformat_csc
2021-05-07 03:36:52,762:DEBUG:splu
2021-05-07 03:36:52,762:DEBUG:END
```

[Full CircleCI output](https://app.circleci.com/pipelines/github/usnistgov/fipy/412/workflows/84887d52-e02c-462c-9a8e-8fdf74ed0236/jobs/4975)

#### Scipy/Numpy/Python version information:

```
  - python=3.9.4=hdb3f193_0
  - scipy=1.6.2=py39hf56f3a7_1
  - numpy=1.20.1=py39h5a90a98_0
  - blas=1.0=openblas
```

**Comment by rgommers** [comment]
@guyer thank you for the detailed report. This fell through the cracks so far - looks like a bug that needs to be looked at.

**Comment by v0dro** [comment]
I cloned @guyer 's repo here https://github.com/v0dro/fipy/tree/slowsplu, and ran the circleCI tests
here: https://app.circleci.com/pipelines/github/v0dro/fipy/1/workflows/0029e844-20ef-435d-965a-309fc1e7c01f/jobs/1/steps

This happens to be the output:
```
2022-04-07 21:45:49,289:DEBUG:START
2022-04-07 21:45:49,448:DEBUG:mmread
2022-04-07 21:45:49,454:DEBUG:asformat_csc
2022-04-07 21:46:16,272:DEBUG:splu
2022-04-07 21:46:16,272:DEBUG:END
```

From this output it seems that the call to `splu()` took about 25s. Is this still a problem? The whole suite in the
TravisCI suite (https://app.travis-ci.com/github/v0dro/fipy/builds/249108930) shows the following output:

```
2022-04-07 22:13:47,452:DEBUG:START
2022-04-07 22:13:47,801:DEBUG:mmread
2022-04-07 22:13:47,806:DEBUG:asformat_csc
2022-04-07 22:13:48,078:DEBUG:splu
2022-04-07 22:13:48,079:DEBUG:END
```

The macos output on travisCI is about 1s. If 25s is still a problem on circleCI, I can proceed with
investigating this issue further.

**Comment by rossbar** [comment]
FWIW I've experienced problems with BLAS threading on CircleCI specifically. One solution is to use the `OMP_NUM_THREADS`  environment variable (or e.g. `threadpoolctl` for finer control) to suppress threading, see e.g. numpy/numpy-tutorials#76.

**Comment by guyer** [comment]
Indeed, `OMP_NUM_THREADS=1` makes a smidge of a difference:

```
python timelu.py

2022-04-08 20:16:12,548:DEBUG:START
2022-04-08 20:16:12,704:DEBUG:mmread
2022-04-08 20:16:12,708:DEBUG:asformat_csc
2022-04-08 20:19:28,531:DEBUG:splu
2022-04-08 20:19:28,531:DEBUG:END
```

vs.

```
OMP_NUM_THREADS=1 python timelu.py

2022-04-08 20:22:14,386:DEBUG:START
2022-04-08 20:22:14,541:DEBUG:mmread
2022-04-08 20:22:14,546:DEBUG:asformat_csc
2022-04-08 20:22:14,719:DEBUG:splu
2022-04-08 20:22:14,719:DEBUG:END
```

Ironically, we were already setting `OMP_NUM_THREADS=1` when we solved with petsc4py and PyTrilinos because we found that OpenMP and MPI fought with each other horribly, but we didn't (used to) do it for serial runs with scipy or PySparse. Since I've migrated everything to Azure, I've been setting `OMP_NUM_THREADS=1` for everything and, if I remembered this issue at all, I attributed it to something about the CircleCI environment and not OpenMP. 

Thanks for looking into it @v0dro, @rossbar, and @rgommers!

**Comment by v0dro** [comment]
So this is a non-issue then? Can we close this? Seems like a superlu specific problem that needs to be resolved by the user on that system. Alternatively, we can make changes to the code such that it uses only one openMP thread (set the number of openmp threads within the code before calling the function and reset it after the call is done).

**Comment by rgommers** [comment]
Thanks for confirming @guyer.

@v0dro yes let's close it. It's not specific to SuperLU, it's a generic issue (or behavior) for every extension that uses OpenBLAS/MKL. OpenBLAS is known to be worse here because it has larger overhead when spawning new threads. Which becomes a real pain on machines with a large number of cores, as is the case here.
