### ISSUE TITLE
How to give maxiter argument to local_search algorithm in dual_annealing

### ISSUE THREAD

**Issue by BrawlingBear** [scipy/scipy#14016]
When I give the following local search options to dual_annealing, I get a TypeError.
`local_search_options={"method":"L-BFGS-B","maxiter":10}`

`[ERROR] TypeError: minimize() got an unexpected keyword argument 'maxiter'`

How can I limit the iterations in local search?

**Comment by tupui** [comment]
Hi, thanks for reporting. The message is quite clear, `minimize` does not have `maxiter`. Have a look at the doc here https://scipy.github.io/devdocs/reference/optimize.minimize-lbfgsb.html#optimize-minimize-lbfgsb. You need to pass an `options` which got `maxiter`.

Please use the user mailing list or better StackOverflow to ask questions. I am closing as this answer your question.
