### ISSUE TITLE
wrong output in lsqr when giving an initial solution

### ISSUE THREAD

**Issue by rkuoyemnbeek** [scipy/scipy#14028]
My issue is about the function lsqr. If I give an initial solution, the function gives wrong output, i.e `r2norm`. In the next example I provided an example where I show that if I give no initial solution everything works fine, but when I give an initial solution the variable `r2norm` is wrong. As I am doing research on how an initial solution can help to solve my problem, this is very annoying. Can someone  fix this issue? It would a great help for me.

#### Reproducing code example:

```python
from scipy.sparse.linalg import lsqr
import numpy as np
from scipy.linalg import block_diag

X = np.array( [ [1, 1, 0, 1], [0, 1, 1, 0], [1, 0, 1, 1], [0, 0,0 , 1], [1, 0, 0, 1]])

X1 = block_diag( X[:, 1:4], X[:, [0, 2, 3]], X[:, [0, 1, 3]], X[:, [0, 1, 2]] )

y = np.matrix.flatten(X, order='F')
l2 = 25
b  = lsqr( X1, y, damp = np.sqrt(l2))
r1norm = b[3]
r2norm = b[4]
print( np.linalg.norm( y - X1 @ b[0]), r1norm)
print( np.sqrt( np.linalg.norm( y - X1 @ b[0])**2 + l2 *np.linalg.norm( b[0])**2), r2norm)
print( '---------------------------------------')

l2 = 50
b1 = lsqr( X1, y, damp = np.sqrt(l2))
r1norm = b1[3]
r2norm = b1[4]
print( np.linalg.norm( y - X1 @ b1[0]), r1norm)
print( np.sqrt( np.linalg.norm( y - X1 @ b1[0])**2 + l2 *np.linalg.norm( b1[0])**2), r2norm)
print( '---------------------------------------')

l2 = 50
b1 = lsqr( X1, y, damp = np.sqrt(l2), x0 = b[0])
r1norm = b1[3]
r2norm = b1[4]
print( np.linalg.norm( y - X1 @ b1[0]), r1norm)
print( np.sqrt( np.linalg.norm( y - X1 @ b1[0])**2 + l2 *np.linalg.norm( b1[0])**2), r2norm)
```

#### output:

```
3.045209327882141 3.045209327882141
3.171977552860766 3.171977552860766
---------------------------------------
3.1660981443638176 3.1660981443638176
3.238767778544454 3.238767778544454
---------------------------------------
2.92989948441173 2.92989948441173
3.4539083940263473 2.9855205966252227
```
The last 2 number should be equal to each other, which is not the case
#### Scipy/Numpy/Python version information:

1.6.0 1.19.5 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)

**Comment by zhaog6** [comment]
Dear Koen @rkuoyemnbeek Pamphile @tupui 
Because the initial guess is nonzero, the correct test code is :
```python
print( np.sqrt( np.linalg.norm( y - X1 @ b1[0])**2 + l2 *np.linalg.norm( b1[0] - b[0])**2), r2norm)
```
instead of 
```python
print( np.sqrt( np.linalg.norm( y - X1 @ b1[0])**2 + l2 *np.linalg.norm( b1[0])**2), r2norm)
```
The comments  is somewhat misleading when `x0` is not zero. I have modified the comments in the PR #14837.

**Comment by nschloe** [comment]
I can confirm that @zhaog6's PR fixes the issue in the correct manner.

**Comment by tupui** [comment]
> I can confirm that @zhaog6's PR fixes the issue in the correct manner.

@nschloe would you consider making a review directly on @zhaog6's PR? We lack reviewers' time in some area and could use some help 😃

**Comment by nschloe** [comment]
Done.
