### ISSUE TITLE
MAINT: add type annotations for _sobol.pyx

### ISSUE THREAD

**Issue by tupui** [scipy/scipy#14038]
Following what have been done for `scipy.stats._qmc_cy.pyx`, we could add easily types to `scipy.stats._sobol.pyx`. Types for Cython cannot be inline but have to be added using a `.pyi` file.

**Comment by akpandeya** [comment]
I would like to work on this issue.

**Comment by tupui** [comment]
Hi, great sure 😃  feel free to reach me for any question!
