### ISSUE TITLE
ENH: other quality metrics for random sampling

### ISSUE THREAD

**Issue by tupui** [scipy/scipy#14037]
The new `scipy.stats.qmc` sub-module provide `discrepancy` as a way to measure the quality of a random sample. This measure is a uniformity criterion.

Other metrics can be used to measure the quality such as _mindist_ and _minimum spanning tree_. 

Here is a simple implementation of useful measures:

```python
import numpy as np
from scipy.spatial.distance import cdist


def l1_norm(sample):
    l1 = cdist(sample, sample, 'cityblock')
    return np.min(l1[l1.nonzero()])


# mindist
def l2_norm(sample):
    l2 = cdist(sample, sample)
    return np.min(l2[l2.nonzero()])


def linf_norm(sample):
    linf = cdist(sample, sample, 'chebyshev')
    return np.min(linf[linf.nonzero()])
```

These are more "geometrically/topologically" based whereas the discrepancy is a statistical criterion. We could have a common function with a `method` argument to select one of the metrics.

From a dependency perspective, this should go in `scipy.spatial`. Also, if we add _mst_, `scipy.spatial` already has a dependency to `scipy.sparse`.

**Comment by czgdp1807** [comment]
@tupui Can I take this up too? Are there any discussions needed for deciding which measures are to be included? Related to https://github.com/scipy/scipy/issues/14510

**Comment by tupui** [comment]
> @tupui Can I take this up too? Are there any discussions needed for deciding which measures are to be included? Related to #14510

This one is free for all, but very accessible this is why I flagged it for sprints. So I would prefer if you could find another one to help on (like poisson disk as I wrote in another issue). But OC if you would really like to take something I would not reject it 😄 It should be fun to come here and help out.

**Comment by kejsitake** [comment]
Can I work on this as part of the today's sprint?

**Comment by tupui** [comment]
@kejsitake I am happy to review any work there. Warning though this is quite involved (needs docs, tests, etc.) and would also need to go through the mailing list at some point. So it would probably not make it in the 1.10 release (also because I will only have this week to review and then in Dec. right before the branch for the new release)

**Comment by aglebov** [comment]
We'd like to take this up for the SciPy 2023 sprint.

**Comment by tupui** [comment]
I am happy to review anything here.

@mdhaber what do you think about making a single function for these? Something like `geometric_measures` or `geometric_uniformity`?

**Comment by mdhaber** [comment]
I don't object. I can't personally envision usage of the function so I can't be more assertive : )

**Comment by aglebov** [comment]
While working on an implementation, we found that the `minimum_spanning_tree` function does not distinguish between the absence of an edge and an edge with zero weight in its input: https://github.com/scipy/scipy/issues/18892.

A work-in-progress pull request is here for any early feedback: https://github.com/scipy/scipy/pull/18893

We had a few questions:

- Should we add this function in a new module in `scipy.spatial`, keep it in `scipy.stats` or perhaps merge it into `scipy.stats.qmc.discrepancy`?
- We can get two metrics from the minimum spanning tree: the mean distance and the standard deviation, so we could let the user choose which metric they want or return both.

**Comment by tupui** [comment]
Thank you 😃 I will reply on the PR itself.
