### ISSUE TITLE
DOC: missing git submodule information

### ISSUE THREAD

**Issue by tupui** [scipy/scipy#14048]
The installation and quickstarter documentation needs to be updated to initialize git submodules (boost).

This for instance https://scipy.github.io/devdocs/dev/contributor/recommended_development_setup.html#recommended-development-setup

```bash
git submodule update --init
```

**Comment by rgommers** [comment]
The other thing we can (/should) do here is to implement a check that a file in the submodule exists, and raise a clear error otherwise at the start of the build process. Now people wait 5-10 minutes to get a cryptic "missing header" build error. I'll have a look at doing that.

**Comment by tupui** [comment]
Then I propose this for the check
```python
>>> boost_dir = pathlib.Path('scipy2/scipy/_lib/boost/boost')
>>> boost_dir.exists()
False
>>> boost_dir = pathlib.Path('./scipy/_lib/boost/boost')
# True
```

**Comment by tupui** [comment]
Actually in `setup.py` we have `check_submodules` so we just need to ensure it's called.
