### ISSUE TITLE
signal.iircomb rounds unexpectedely

### ISSUE THREAD

**Issue by dasteihn** [scipy/scipy#14043]
`signal.iircomb` seems to (always?) pick a delay-time 1 step to large.

#### Reproducing code example:

In the sample below, eplace the 49.999 with 50.0 and run both versions on a wavesound file of your choice.
Watching where the notches are in the spectrum, it seems to me that (in my wav file with fs=44100) the IIR filter is using a delay of 881 instead of 882 Ts.
Therefore I suspect it is always using the delay time higher than selected by the user. In my example however, the filter should absolutely be able to hit the N*50Hz exactly, by using a delay of 882 samples.

In these pictures, you can see how that becomes very visible for high frequencies.

![drift-with-50](https://user-images.githubusercontent.com/28155519/118320581-bff20680-b4fc-11eb-8c27-d7fa5597f784.png)
![exact-with-4999](https://user-images.githubusercontent.com/28155519/118321040-56262c80-b4fd-11eb-8af2-ac75c17340f4.png)

```
import numpy as np
import wave
import sys

from scipy.io import wavfile
from scipy import signal as sig
import matplotlib.pyplot as plt

rate, data = wavfile.read(sys.argv[1])

b, a = sig.iircomb(49.999/int(rate/2), 50.0, ftype='notch') # replace with 50.0 to see the issue

zi = sig.lfilter_zi(b, a)
bearb = sig.lfilter(b, a, data, zi=zi)

out = bearb[0].astype('int16')

wf = wave.open(sys.argv[2], "wb")
wf.setnchannels(1)
wf.setframerate(rate)
wf.setsampwidth(2)
wf.writeframes(out)
wf.close()
```

#### Scipy/Numpy/Python version information:

```
1.6.2 1.20.1 sys.version_info(major=3, minor=9, micro=3, releaselevel='final', serial=0)
```
-->

**Comment by endolith** [comment]
Because of the line `N = int(fs // w0)` and the way int division works with float divisor:

```
44100 / 50
Out[70]: 882.0

44100 // 50
Out[71]: 882

2 / 0.0022675736961451248
Out[68]: 882.0

2 // 0.0022675736961451248
Out[69]: 881.0
```

It should probably be `N = round(fs / w0)` instead.

```
round(44100 / 50)
Out[90]: 882

round(2 / 0.0022675736961451248)
Out[92]: 882
```

The previous check of divisibility `np.round(fs % w0) != 0` is strange because it means `fs=44100`, `w0=49.999` is forbidden, but `fs=2`, `w0=49.999/int(44100/2)` is fine.

**Comment by skresearcher** [comment]
That makes sense. I also think that divisibility check is not working with float divisors as it was intended. It was placed to ensure that `N` (the number of notches) would not be fractional, which means that `w0 = 49.999 / int(44100 / 2)` should not work if `fs = 2`. Maybe it can be changed to `(fs / w0).is_integer()`? In that case, even `N = int(fs / w0)` would work as a replacement for `N = int(fs // w0)`.

**Comment by endolith** [comment]
Well sample rates aren't necessarily integers, and so the two float numbers may not divide exactly(?)  Comparing for exact divisibility is like [comparing floats for equality](https://floating-point-gui.de/errors/comparison/).  Instead we should have some kind of "close enough" test, like np.allclose does.

(Also I think we should add an optional `N=` integer parameter that would subdivide the spectrum evenly, and you can use one parameter or the other, but not both at the same time.)
