### ISSUE TITLE
Google Colab fails to locate scipy when running a script using pypy

### ISSUE THREAD

**Issue by alexzhang0825** [scipy/scipy#14054]
I was prompted with the following error:
```
Traceback (most recent call last):
  File "run_distill.py", line 4, in <module>
    import dataset
  File "/content/gdrive/My Drive/project_folder/RKD/dataset/__init__.py", line 1, in <module>
    from .cars196 import Cars196Metric
  File "/content/gdrive/My Drive/project_folder/RKD/dataset/cars196.py", line 3, in <module>
    import scipy.io as io
ImportError: No module named scipy
```
after I have re-installed scipy multiple times using
```
!pip install scipy
```
The code itself is rather large and contains multiple files so I'm not sure if I can just give everything needed to reproduce the error here. I feel like I'm missing something (maybe I installed scipy under python3 instead of pypy), but I'm not sure exactly what it is.

**Comment by jakevdp** [comment]
The `pip` command is generally tied to a particular Python installation; if you want to pip install something for pypy, you'll first have to install pip for pypy.

**Comment by alexzhang0825** [comment]
I tried
```!pypy -m pip install scipy```
and it prompted me with
```/usr/bin/pypy: No module named pip```
I believe on a Colab you have to install module in the following fashion:
```!apt-get install pypy-pip```
But I tried that as well and was told that it's unable to locate package ```pypy-pip```.

**Comment by jakevdp** [comment]
If you're having trouble installng pip for pypy, perhaps there is another forum where you can ask for help? I've never actually used pypy.

**Comment by alexzhang0825** [comment]
I tried on stackoverflow but so far no working answer has appeared, which is why I turnt to here for a potential one. I will try my luck at some other places I find. Is it ok for me to leave it unclosed for more people to see just in case?

**Comment by tupui** [comment]
Sure but please remember to come back and let us know how you solved it 😃

**Comment by alexzhang0825** [comment]
So I managed to get a working solution from reddit user u/llub888
```
!wget https://downloads.python.org/pypy/pypy3.7-v7.3.4-linux64.tar.bz2
!tar -xf pypy3.7-v7.3.4-linux64.tar.bz2
!rm pypy3.7-v7.3.4-linux64.tar.bz2 
import os
os.environ['PATH'] += ':/content/pypy3.7-v7.3.4-linux64/bin/'
!/content/pypy3.7-v7.3.4-linux64/bin/pypy -m ensurepip
!pypy -m pip install scipy
with open('test.py', 'w') as f:
  f.write('import scipy\nprint("scipy imported successfully!")')
  f.close()
```
It installed ```scipy``` under ```pypy``` without any problem. Unfortunately the python script is now saying it's missing the module ```torch```. But I guess that's a problem I should seek for an answer to elsewhere. Thanks to anyone helping in this post.
