### ISSUE TITLE
Gitpod - Docker image build still failing

### ISSUE THREAD

**Issue by trallard** [scipy/scipy#14056]
I just checked the GH actions and the build for the Gitpod Docker image is still failing 👀

#### Reproducing code example:

I cannot reproduce locally - cloned the repo. Built the Docker image successfully and managed to build SciPy and run the tests in the container. 
From conversations in  #14047 (and at pycon sprints) It first seemed like what was missing was initialising the submodule but this seems to be a whole different thing

#### Error message:

See https://github.com/scipy/scipy/runs/2588163998?check_suite_focus=true#step:9:12152 which returns 

```
#11 198.2 scipy/_lib/tests/test_boost_build.cpp:4:10: fatal error: boost/math/distributions.hpp: No such file or directory
```

#### Scipy/Numpy/Python version information:

Building from commit `d98e31ec` so it is the same from which the scheduled Docker build failed. 

I will try and figure out what is happening (not had time to do it but decided to open the issue before I forgot)  but maybe a more experienced set of eyes can point me in the right direction.

**Comment by rgommers** [comment]
Working now. In case someone runs into this in the future: `fatal error: boost/math/distributions.hpp: No such file` is the problem you will see when `git submodule update --init` is not run.

**Comment by trallard** [comment]
Sorry for opening this issue and then closing it - I was at the APAC sprints and my brain failed to realise that it was looking at the previous day action 😭 

All is good now

**Comment by rgommers** [comment]
No worries at all, our brains all need a rest:)
