### ISSUE TITLE
shgo + sobol + high dimensional input: skip argument missing for sobol_points_10k

### ISSUE THREAD

**Issue by cherrywoods** [scipy/scipy#14071]
When running `scipy.optimize.shgo` with high dimensional input and sobol as sampling strategy a TypeError is thrown, 
because the `sobol_points_10k` function misses a parameter `skip`, which is passed to it.

The error goes away if adding such a skip parameter to this function. 

#### Reproducing code example:

```
from scipy.optimize import shgo
shgo(
    lambda x: -np.sum(np.sin(x)),
    [(-1, 1) for _ in range(64)], 
    n=100, iters=10, sampling_method='sobol', minimizer_kwargs={'method': 'COBYLA'}, options=None
)
```

#### Error message:

```
 ...
 Traceback (most recent call last):
  File ".../IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "...", line 1, in <module>
    shgo(lambda x: -np.sum(np.sin(x)), [(-1, 1) for _ in range(64)], n=100, iters=10, sampling_method='sobol', minimizer_kwargs={'method': 'COBYLA'}, options=None)
  File ".../scipy/optimize/_shgo.py", line 421, in shgo
    shc.construct_complex()
  File ".../scipy/optimize/_shgo.py", line 726, in construct_complex
    self.iterate()
  File ".../scipy/optimize/_shgo.py", line 869, in iterate
    self.iterate_complex()
  File ".../scipy/optimize/_shgo.py", line 906, in iterate_delaunay
    self.sampled_surface(infty_cons_sampl=self.infty_cons_sampl)
  File ".../scipy/optimize/_shgo.py", line 1225, in sampled_surface
    self.sampling(self.nc, self.dim)
  File ".../scipy/optimize/_shgo.py", line 1367, in sampling_sobol
    self.C = self.sobol_points(n, dim, skip=self.n_sampled)
TypeError: sobol_points_10k() got an unexpected keyword argument 'skip'
```

#### Scipy/Numpy/Python version information:

```
1.6.3 1.19.5 sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)
```

**Comment by tupui** [comment]
Hi. So you know this part has been completely refactored to take advantage of the new `scipy.stats.qmc.Sobol`. Hence there is no limitation anymore on Sobol' sampling. You can test all that if you use the current dev version.

Also `shgo` is receiving a big update (in progress).

**Comment by ilayn** [comment]
@cherrywoods could you please confirm if current implementation fixes the issue?

**Comment by tupui** [comment]
@ilayn this is not relevant anymore. The code was calling `sobol_points_10k` when asking for more points. Now this has been changes completely and you can sample as many points as you want with a single function. So if this works for 1000 points it will work for 10000. The code is not branching or anything else.

What you might have though with sampling as much is memory errors from other parts of the code. But there is no issue on Sobol' here.

**Comment by ilayn** [comment]
It won't hurt to get a confirmation since we don't test with real world case. We can close it later on another sweep if we don't hear back.

**Comment by cherrywoods** [comment]
I probably won't confirm that this works before the next scipy release.

**Comment by tupui** [comment]
FYI, I testing your code and it's crashing after a while because I don't have enough memory. But in smaller dimensions it seems to be running fine.
