### ISSUE TITLE
`scipy.optimize._linprog_simplex._apply_pivot` relies on asymmetric closeness definition

### ISSUE THREAD

**Issue by pmeier** [scipy/scipy#14081]
We are currently looking into using a [symmetric closeness definition for `numpy.isclose`](https://github.com/data-apis/array-api/issues/170). To judge the impact this move would have on other libraries we ran `scipy`'s test suite against a modified `numpy`. 

While doing this a lot of tests emitted this warning

https://github.com/scipy/scipy/blob/0617428d9fb1d57fe8b0808291818e61b00efdbf/scipy/optimize/_linprog_simplex.py#L219-L229

because it relies on the asymmetric definition.

I've tracked it down to #9081 and specifically https://github.com/scipy/scipy/pull/9081#discussion_r205899909 (cc @Kai-Striega @mdhaber). If I understand the intention correctly it should check if the `pivval` is significantly greater than the tolerance. If that is the case

```python
if abs(pivval) <= tol * 1e4:
    ...
```

would be a better choice, because

1. it communicates the intent better, and
2. is safer since `np.isclose` basically checks `abs(pivval - tol) <= ...` which might lead to unwanted behavior in an edge case.

**Comment by mdhaber** [comment]
That's OK if it causes this test to fail. `simplex` is going to be deprecated anyway.
