### ISSUE TITLE
scipy.stats.norm.pdf takes too much time and memory

### ISSUE THREAD

**Issue by chahak13** [scipy/scipy#14095]
Hi, I needed the norm.pdf values for an array of mus (`loc`) and sigmas (`scale`) and was trying to use `scipy.stats.norm.pdf`. While using this, I observed that my RAM usage was increasing inexplicably. I decided to dig a little and found these two issues
1. The function is too slow for repeated runs
2. It takes a lot of memory, which is probably not required.

I'm not sure if there's something wrong that I'm doing or if there's some issue on scipy's side, so I thought I should bring it up. Any help would be great.
#### Reproducing code example:

```python
import numpy as np
from scipy import stats

def norm_pdf(x, mu, sigma):
    mu, sigma = mu.reshape(-1, 1), sigma.reshape(-1, 1)
    variance = sigma**2
    numerator = np.broadcast_to(x, (mu.shape[0], x.shape[0])) - mu
    denomenator = 2*variance
    pdf = ((1/(np.sqrt(2*np.pi)*sigma))*np.exp(-(numerator**2)/denomenator))
    return pdf

def func_scipy(x, mu, sigma):
    res = stats.norm.pdf(x[:,None], mu, sigma)
    return res

x = np.arange(10**7)
mu, sigma = np.arange(1, 2), np.arange(1, 2)
t1 = norm_pdf(x, mu, sigma)
t2 = func_scipy(x, mu, sigma)

```

As you can see above, I wrote a simple function that calculates the same pdf values for my use-case. To compare it with the `norm.pdf` I performed a few profiling experiments. For memory, I used the `memory-profiler` library and for time I used the `cProfile` and `timeit` modules.

##### Memory profiling
I performed two experiments for memory profiling.
1. `x = np.arange(10**7)` with a single value of `mu` and `sigma` as seen in the sample code above. The results for the same were plotted using the `mprof` functionality 
![scipy_norm_pdf_1_mu_benchmark](https://user-images.githubusercontent.com/29800965/118939723-9eb26f80-b96d-11eb-9c26-39142a89d07f.png)

2. I also performed one more experiment with an array of `mu` and `sigma`, namely, `mu=np.arange(1, 51)` and `sigma=np.arange(1, 51)`. The results for this were
![scipy_norm_pdf_benchmark](https://user-images.githubusercontent.com/29800965/118939985-e2a57480-b96d-11eb-9713-23f6a5740ad8.png)

As can be seen in both the images, somewhere in the stats.norm.pdf function, the memory consumption reaches a peak that is too high when compared to the function I wrote. 

##### Time profiling
I first of all did a simple `timeit` test in ipython. The results were as follows (`x=np.arange(10**5)` because it was taking too much time otherwise)
```python
In [20]: %timeit -n100 -r1 stats.norm.pdf(x[:,None], mu, sigma)
326 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)

In [21]: %timeit -n100 -r1 norm_pdf(x, mu, sigma)
108 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)
``` 
On seeing that the `norm_pdf` function is indeed fast, I used the `python -m cProfile` to dig deeper and profile the time and this is the top few lines of the result.
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   1436/1    0.017    0.000    4.709    4.709 {built-in method builtins.exec}
        1    0.004    0.004    4.709    4.709 benchmark.py:1(<module>)
        1    0.005    0.005    2.976    2.976 benchmark.py:15(func_scipy)
        1    0.594    0.594    2.971    2.971 _distn_infrastructure.py:1809(pdf)
    26/18    0.070    0.003    1.269    0.070 {built-in method numpy.core._multiarray_umath.implement_array_function}
        1    0.034    0.034    1.122    1.122 _distn_infrastructure.py:528(argsreduce)
        1    0.198    0.198    1.088    1.088 _distn_infrastructure.py:553(<listcomp>)
       92    0.005    0.000    1.080    0.012 __init__.py:1(<module>)
        1    1.064    1.064    1.064    1.064 benchmark.py:6(norm_pdf)
        2    0.000    0.000    0.889    0.445 <__array_function__ internals>:2(extract)
        2    0.002    0.001    0.889    0.445 function_base.py:1651(extract)
        4    0.000    0.000    0.887    0.222 fromnumeric.py:52(_wrapfunc)
```
Full file: [benchmark_profile.txt](https://github.com/scipy/scipy/files/6513924/benchmark_profile.txt)

As you can see, there is some kind of slowness in `stats.norm.pdf`. One particular source of this is the list comprehension written in the return value of `np.argsreduce` (line no. 12 of the profiler output). I saw a comment saying ["# This should be rewritten"](https://github.com/scipy/scipy/blob/4ec4ab8d6ccc1cdb34b84fdcb66fde2cc0210dbf/scipy/stats/_distn_infrastructure.py#L527) on the `np.argsreduce` function so it seems that you do know there's some issue there but this is just another effect that function is having. There might be other reasons for this too but I couldn't find them.

#### Scipy/Numpy/Python version information:

```python
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.6.1 1.20.1 sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)
```

**Comment by chahak13** [comment]
PS: I checked the `git blame` of that comment on `np.argsreduce` but that's 8 years old. So I'm not sure if that's a problem or not anymore. Do let me know if I can help in any way :)

**Comment by ev-br** [comment]
Could you rerun it with the master branch? There was some work addressing exactly this comment just recently.

**Comment by ev-br** [comment]
On a side note, if stats.distributions overhead is too large for your use case, you can call the underlying ufunc from scipy.special (see norm_gen._pdf source for which one it is)

**Comment by chahak13** [comment]
Ah, thanks! I'll try to do the same after building from the source and update here

**Comment by chahak13** [comment]
Hi, I compared the two versions (1.6.3 and master) and for an array of loc and scale values, the peak memory used in 1.6.3 was 2435.5 MB (`scipy.stats.norm.pdf`) vs 1201.3 MB (`norm_pdf`). 
On the other hand, as you suggested, the master did have a significant improvement with peak memory used being 1674.1 MB (`scipy.stats.norm.pdf`) vs 1204.8MB (`norm_pdf`). Though, it still used ~470MB more, which may or may not be an issue on a larger scale but I could not check that. 

On the time side, 
1.6.3:
```
In [10]: %timeit -n100 -r1 norm_pdf(x, mu, sigma)
109 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)

In [11]: %timeit -n100 -r1 stats.norm.pdf(x[:,None], mu, sigma)
382 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)
```

master:
```
In [7]: %timeit -n100 -r1 norm_pdf(x, mu, sigma)
110 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)

In [8]: %timeit -n100 -r1 stats.norm.pdf(x[:,None], mu, sigma)
212 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)
```
So there is some slowness and some memory thing, but it is definitely a significant improvement. 

Also, can you please point me to the changes/commits made? I'm curious what was causing the issue and what fixes were made. Let me know if you need more info from my side

**Comment by mdhaber** [comment]
@DominicChm let's also make sure the benchmarks track this sort of thing, then I think we can close this. Reduction of stats distribution overhead is an ongoing sort of thing.

**Comment by mdhaber** [comment]
@DominicChm would you post your findings here? IIRC, we tested with the normal distribution, and peak memory usage was ~8x higher than that required to hold the input of the `pdf` method, `x`. Since the calculations are not performed in-place, this was reasonable considering the number of intermediate results that are generated while performing the calculations, right? If the calculations _were_ performed in-place, we observed most of the expected reduction in memory usage, but do I remember that there was a factor of 2 in memory usage that seemed to be unaccounted for? Was that actually a _factor_ of 2, or was it a constant amount that happened to be approximately the same size as the input array we were testing with?

**Comment by DominicChm** [comment]
(cross-posted from gh-15982)
In our testing, norm.pdf uses 66mB of peak RAM to process a 1e6 sized array. Looking at the code for the normal PDF (np.exp(-x**2/2.0) / _norm_pdf_C), you can count ~5 individual operations. arange allocates ~8mb per creation (sizeof(float64) * 1e6), which is copied once per operation. That means that we expect to see norm.pdf use at least 40mB of RAM. That leaves 16mB, which is easily explained by the original allocation and checks that _rv_continous does to ensure input validity. This seems to hold true for other distributions as well. 

What that means is that the overhead observed in this issue is expected given how Numpy/Scipy operate. If necessary, memory overhead might be reduced by manually vectorizing the operation (IE processing cases 1-by-1 from the input to output array in a loop) to prevent intermediate copies of the entire dataset being created during processing.

**Comment by mdhaber** [comment]
We could also copy the input array once and do in-place operations, but that does not seem to have been a consideration when the distributions were created. I don't think we need to track this anymore, but at some point we can consider reducing memory usage as an enhancement.
