### ISSUE TITLE
Scipy.stats.qmc does not exist but documentation claims it does

### ISSUE THREAD

**Issue by EnderWiggin14** [scipy/scipy#14128]
My issue is about ...

I want to use the `LatinHypercube` sampler from the `qmc` class(?)/module, but I am greeted with 

```
Traceback (most recent call last):
  File "lhs_sampling.py", line 22, in <module>
    latin_sampler = stats.qmc.LatinHypercube(d=4)
AttributeError: module 'scipy.stats' has no attribute 'qmc'
```

This [documentation](https://scipy.github.io/devdocs/reference/generated/scipy.stats.qmc.LatinHypercube.html#scipy.stats.qmc.LatinHypercube) claims that by using `from scipy.stats import qmc` should work. I tried this, but it didn't work.

I looked in the library file stats.py in ./scipy/stats and found no mention of qmc or LatinHypercube.

I'm using `scipy 1.6.3` because `scipy 1.7.0` is not pip installable right now.

#### Reproducing code example:

```
import scipy.stats as stats
latin_sampler = stats.qmc.LatinHypercube(d=4)
```

#### Error message:

```
Traceback (most recent call last):
  File "lhs_sampling.py", line 22, in <module>
    latin_sampler = stats.qmc.LatinHypercube(d=4)
AttributeError: module 'scipy.stats' has no attribute 'qmc'
```

#### Scipy/Numpy/Python version information:

```
numpy    1.20.3
scipy    1.6.3
```

**Comment by ilayn** [comment]
The documentation is synced to the current master branch which includes the module but it is not out yet for pip and conda install. But will be out very shortly. Sorry for the confusion about it.

**Comment by ilayn** [comment]
The 1.6.3 version of the docs are here if you need to browse further https://docs.scipy.org/doc/scipy-1.6.3/reference/

**Comment by tupui** [comment]
Hi @EnderWiggin14, thanks for your interest in QMC! The release of SciPy 1.7 (which will have `scipy.stats.qmc`) is due end of June. In the meantime, you can use the development version if you want to use un-released features.

Closing this as there is no issues.

@rgommers maybe we could had a banner to make it explicit that this page is for the development version? We would add a link to the current released doc in this banner.

**Comment by rgommers** [comment]
A banner like this is too ugly I think:

<img width="842" alt="image" src="https://user-images.githubusercontent.com/98330/119464356-f3296680-bd42-11eb-9c55-fcfa7a2665a0.png">

I, and I'm sure quite a few other people, read the devdocs by default. It would be good to have an unobtrusive link or version number somewhere:

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/98330/119464507-148a5280-bd43-11eb-8e9e-5489acc4ec97.png">

Or better, implement the version switcher in the Sphinx theme - that will solve it the right way.

**Comment by tupui** [comment]
I was more thinking about a banner that you can close, but still I agree to say it's generally ugly 😅

Alternatively, there would be the sklearn way with the version in the side-bar. But the cleanest IMO is the read-the-doc way (https://pydata-sphinx-theme.readthedocs.io/en/latest/).

**Comment by tupui** [comment]
If we would just want the version number, we could have something pretty close to the logo, there is lot of space here.

**Comment by rgommers** [comment]
The pandas-like RTD version switcher would be good, but then a non-RTD version that is part of the theme. And in the top bar rather than "always visible" I'd say. Styling-wise the Pandas thing looks pretty out of place.

**Comment by tupui** [comment]
Here is a quick working version. I would need to figure out proper spacing/alignment/sizing, but this looks clean IMO. What do you think?

<img width="1106" alt="Screenshot 2021-05-25 at 10 44 36" src="https://user-images.githubusercontent.com/23188539/119467908-43ee8e80-bd46-11eb-8b1d-9504fa43d9c1.png">

**Comment by tupui** [comment]
> The pandas-like RTD version switcher would be good, but then a non-RTD version that is part of the theme. And in the top bar rather than "always visible" I'd say. Styling-wise the Pandas thing looks pretty out of place.

Agreed the style can be improved. If we want to do this over the simple badge/text it will be more work. I could take a stab or we could wait for a grant for the websites.

**Comment by rgommers** [comment]
The simple badge sounds good to me.

**Comment by tupui** [comment]
> The simple badge sounds good to me.

Great! I will make a PR then.
