### ISSUE TITLE
How to deal with, who's equation infinite solution or Finding solution for two collinear line of equation which has det(A)=0

### ISSUE THREAD

**Issue by ramjan-raeen** [scipy/scipy#14120]
since, we have XA = B => X = A^-1*B. How to find solution of given two collinear equation and which |A| = 0 and adj(A).B = 0.

**Condition for consistency of linear equation AX = B.**

- if |A| != 0 then the system is consistent and has a unique solution, given by X = A −  1  B.
- if |A| = 0, and (Adj A)B != 0, then the system is inconsistent.
- if |A| = 0, and (Adj A)B = 0, then the system is consistent and has infinitely many solutions.
I'm stuck with condition 2'nd and 3'rd.

Thanks in advance

![Screenshot 2021-05-24 at 11 55 14 AM](https://user-images.githubusercontent.com/40716654/119305870-efd0a500-bc86-11eb-9b13-fa212d0aaf25.png)

**Comment by ev-br** [comment]
This tracker is for reporting scipy issues and enhancements. This question is thus off-topic, so I'll close it.
`solve` is not prepared to deal with degenerate matrices.  I'd suggest you read up on linear algebra, esp solving linear systems in the least-squares sense. If that's relevant to what you're doing, there's e.g. `np.linlag.lstsq`.
(This system is obviously inconsistent, there is no solution.)
