### ISSUE TITLE
Item assignement for spatial.transform.Rotation objects

### ISSUE THREAD

**Issue by OrtnerMichael** [scipy/scipy#14122]
**Specific Problem**
 I want to apply a vector of rotations (e.g. Rotation object R1 with len(R1)=N) to another vector of rotations (e.g. Rotation object R2 with len(R2)=M) with N<M, meaning that I only what to apply the R1 rotation to specific parts (e.g. a slice [i:j]) of the R2 object.

**Solution without item assignment:**
```
R3 = R2[i:j]*R1
R2q = R2.as_quat()
R2q[i:j] = R3.as_quat()
R2 = R2q.from_quat()
```
I always have to transform between ndarray represenation and Rotation object.

**Potential solution with item assignment:**
```
R2[i:j] *= R1
```

**Additional info**
I love the Rotation package - but generally I wish the Rotations would behave more like numpy arrays. I am regularly missing features like **item assignment** or **ndim** or **pad**.

Thank you for considering my request.

**Comment by pmla** [comment]
I am in favour of this feature. @nmayorov what is your opinion?

**Comment by pmla** [comment]
@OrtnerMichael thank you for this feature suggestion - it has been merged now.
