### ISSUE TITLE
Feature request: DIRECT algorithm for global optimization

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#14121]
**Is your feature request related to a problem? Please describe.**

The global optimization algorithm DIRECT is a popular and widely used algorithm for low dimensional problems. It is also methodically very different from the algorithms currently implemented in SciPy. Ihere seemed to be a concensus on the mailing list that it would be a valuable addition for SciPy.

**Describe the solution you'd like**

A scipy.optimize.direct() function. Ideally, this repo could be used or mimiced as a starting point: https://github.com/andim/scipydirect

**Describe alternatives you've considered**

DIRECT wrappers are available via [NLopt](https://github.com/stevengj/nlopt) and [scipydirect ](https://github.com/andim/scipydirect). NLopt unfortunately implements a very different API for its optimizers and scipydirect requires manual compilation of the Fortran source code which makes the entry barrier quite high for regular Python developers. 

**Additional context (e.g. screenshots)**

Benchmark of derivative free global optimizers in Python including the DIRECT_L variant:
http://infinity77.net/go_2021/thebenchmarks.html

**Comment by rgommers** [comment]
It looks like what needs to happen is:

- Include either the Fortran or the NLopt f2c'd source in a directory `scipy/optimize/_direct_lib/`. Note that the C sources had some maintenance to fix a lot of warnings, which could be useful: https://github.com/stevengj/nlopt/commits/496be736b8b249273838b891f4c8ca3669551127/src/algs/direct
- Hook it up in the build system in a similar way as `_shgo_lib`
- Add the Python implementation from `scipydirect` in `_direct.py`
- Add tests (a little more extensive than what `scipydirect` has
- Add support in `optimize.minimize` for it
- Hook  it up to the benchmarking system for global optimizers

**Comment by andim** [comment]
Thanks @rgommers for checking the licensing and for this detailed list!

I had a look at how the shgo library is included, which seems straightforward enough. However, I don't think it includes a fortran source. Is there another optimization algorithm that shows how to integrate such an external source?

I will not have much time over at least the next 2-3 weeks to work on this. If you have more time @dschmitz89 feel free to go ahead setting this up!

**Comment by rgommers** [comment]
> However, I don't think it includes a fortran source. Is there another optimization algorithm that shows how to integrate such an external source?

`slsqp` may be a good example: https://github.com/scipy/scipy/blob/8d8bfbf91699054201e81cd6e5f03cb193024ca9/scipy/optimize/setup.py#L90. It only needs a few lines of code in `setup.py`, the rest is automatic.

**Comment by dschmitz89** [comment]
Hey there, 

I might have some time for this from July on or so. I am not much of a C person though and have used f2py only once. So in case that we utilize the Fortran source, I might be helpful, not so much if we use the C course. Especially as the f2py Port is already written, I had expected the Fortran version to be the easiest to include. If core devs judge by experience and the number of hacks necessary for NLopt that this code better not be used, I would of course agree.

I would like to point out that Steve Johnson [reimplemented](https://github.com/stevengj/nlopt/tree/master/src/algs/cdirect) DIRECT from scratch in C for nlopt under MIT license. This code does not have any restrictions anymore regarding the number of function evaluations etc, so is probably the best implementation of DIRECT on the market. Judging by Johnson's github activity, he is very responsive. I imagine that if a SciPy core dev asked, he could be persuaded to help in a standalone version of that code. Currently, it is deeply intermingled with other helper functions in NLopt.

**Comment by rgommers** [comment]
> I would like to point out that Steve Johnson reimplemented DIRECT from scratch in C for nlopt under MIT license

Great, thanks for pointing that out. I had only seen the initial f2c'd version. That completely clears it up.

> Judging by Johnson's github activity, he is very responsive. I imagine that if a SciPy core dev asked, he could be persuaded to help in a standalone version of that code. Currently, it is deeply intermingled with other helper functions in NLopt.

It does look much better that the Fortran 77 code, both in terms of maintenance / code quality and extra functionality (the hybrid version), I think it's worth spending some time extracting it. Although that can be done separately - if the `scipydirect` code works unmodified and works well on all platforms, that can be step 1.

**Comment by dschmitz89** [comment]
Agreed that adding DIRECT the scipydirect way would be the first step, would there be a need for a step 2? Or do you mean running the benchmarks? Writing a wrapper for the Fortran version AND one for the C version seems like implementing a mostly equal functionality twice for me.

**Comment by rgommers** [comment]
> Writing a wrapper for the Fortran version AND one for the C version seems like implementing a mostly equal functionality twice for me.

I expect that the Fortran implementation is going to spew a lot of build warnings, and is generally worse than the C version. So we can throw it away in step 2.

**Comment by czgdp1807** [comment]
Hi. @dschmitz89 @rgommers Can I work on this issue? Seems interesting to me, so thought of asking here. I can give dedicated time to this issue. Let me know. Thank you.

**Comment by andim** [comment]
From my side happy to have you go ahead! I'm still stretched quite thin so
it would surely take me longer.

**Comment by rgommers** [comment]
+1 this would be great @czgdp1807!

**Comment by czgdp1807** [comment]
Awesome. I will start looking into the steps discussed above from tomorrow. May be a PR by the end of next week (for early reviews).

**Comment by dschmitz89** [comment]
+1 from my side too, at the moment I cannot find the time unfortunately.

On the discussion about the C vs Fortran implementation: it seems like a standalone version of the f2c implementation from NLopt is available (no NLopt baggage and removed bugs compared to the Jablonsky's Fortran implementation): https://github.com/rlnx/DiRect

But of course @czgdp1807 : it is up to you which version/language you are most comfortable with. Looking forward to having DIRECT in scipy :)

**Comment by czgdp1807** [comment]
N.B. - https://github.com/andim/scipydirect/issues/11

I will try using `scipy/tools/generate_f2pymod` and will see if the things work out there. The process will not be that hectic. Mostly the fortran warnings are non-serious (unused variables and labels). The C code in NLopt is also not updated much (i.e., only two commits in `direct.c` one for adding the code and other for silencing, https://github.com/stevengj/nlopt/commits/master/src/algs/direct/DIRect.c), so I think there shouldn't be much difference in the results from these two libraries.
