### ISSUE TITLE
Resolution/search space of input parameters in optimization

### ISSUE THREAD

**Issue by JulianWgs** [scipy/scipy#14135]
**Is your feature request related to a problem? Please describe.**
I want to optimize a function using SciPy. This function however does only evaluate with a coarse input parameter resolution.

**Describe the solution you'd like**
I would like to tell SciPy the needed input parameter resolution. Internally the optimizer always uses np.float64, but what if the function only calculates with np.float32 internally. What if the function has an arbitrary internal step.

Here is a dummy function to demonstrate what I mean:

```python
def func(x):
    step = 0.5
    x_coarse = x // step * step
    return x_coarse**2
```

```python
res = scipy.optimize.differential_evolution(func, [(-5, 5)])
res
```

During the optimization the function was evaluated 137, but only 25 of the inputs were unique evaluation. The solution space has 40 possible unique evaluations. This is of course is an extreme example. The behavior for different step sizes and/or optimizers is very interesting and I recommend to check it out.

I would like to give SciPy information about the solution space, so it can avoid unnecessary evaluations. For the given optimizer this could be done, by rejecting parameters. Since the optimizer is non-deterministic new input parameters could be generated easily. Another approach would be similar to Latin-Hypercube, but that parameters are being actively optimized.

I would propose a validation function or a search space argument.

Here a quick and dirty API example of a validation function:

```python
input_parameters_set = set()
def validation_function(input_parameter):
    input_parameter_course = input_parameter // 0.2 * 0.2
    if input_parameter_course not in input_parameters_set:
        input_parameters_seta.add(input_parameter_course)
        return True
    else:
        return False

res = scipy.optimize.differential_evolution(func, [(-5, 5)], validation_function=validation_function)
res
```

Of course this is just a dummy example and I hope could make my point. The real function takes around an hour to finish and calls external programs.

**Describe alternatives you've considered**
Using a cache for repeated function evaluations. While this solutions may cure the symptoms of the problem, it keeps the optimizer "dumb" about the solution space.

**Additional context (e.g. screenshots)**
None.

**Comment by andyfaff** [comment]
How far down the road from continuous to discrete are we talking about? I understand that you'd like to do something along the lines of `[-5, -4.5, -4.0, ... , 4.5, 5.0]`.

 For the specific case of `differential_evolution` it's possible to do integer optimisation by rounding+casting to an int. By recasting your objective function might be able to use that approach for what you want to do. However, `differential_evolution` suggests new population members based on floating point arithmetic, see the notes on the [docstring](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.differential_evolution.html). Therefore depending on the dimensionality, granularity, and time per evaluation of the function caching could make a lot of sense. 

> I would like to give SciPy information about the solution space, so it can avoid unnecessary evaluations. For the given optimizer this could be done, by rejecting parameters

If the parameter vector is feasible then a function value would still have to be returned by your objective function. The minimizer could be sending e.g. 4.5 and 4.6 which both correspond to 4.5 when rounded. I think caching by your function is necessary if you'd like to improve performance. Such caching would work really well when everything was relatively granular, but poorly if there are any parameters that are float-like.

**Comment by JulianWgs** [comment]
Thanks for the quick response :)

> However, differential_evolution suggests new population members based on floating point arithmetic, see the notes on the docstring.

But this process happens randomly, so if the function could reject a given set of float parameters, new ones could be generated with another draw. If no parameters can be created, which are not rejected the optimization also converges.

I believe that caching and a resolution aware algorithm would give different results as the unaware algorithm could think it is at a optimum when in fact it just always evaluates the same parameters. (This could also be applied to gradient based algorithm which are far more sensitive to parameter resolution.)

I want to give the optimization algorithm information about the solution space. Bounds already constrain this space in the up and down direction, but now I want constrain it in the resolution.

**Comment by andyfaff** [comment]
- If a solution isn't feasible then the objective function should return `np.inf`.
- If there are areas that the solver shouldn't visit, then that's when constraints should be used.
- as exists I believe the solver should handle integer parameters. If all the parameters are integers then a good caching mechanism will speed things up.

```
import numpy as np
from scipy.optimize import differential_evolution
from functools import lru_cache

@lru_cache(maxsize=100000)
def ff(x):
    return np.sum(np.array(x)**2)

def f(x):
    x = tuple(np.rint(x).astype(int))
    
    return ff(x)

bounds = [(-100, 100)] * 5

res = differential_evolution(f, bounds)

print(np.rint(res.x))
print(ff.cache_info())
```
prints all zeros. This caching won't work so well when the dimensionality or granularity increase.
- I believe that there are approaches out there that are more efficient for *integers* than this approach, but I don't have more information (e.g. a paper) for how to implement. I don't know the level of difficulty for integrating such an approach into the existing code/interface, but I'm not on the optimistic side there.
- Specifying a resolution is kind of similar to integer optimisation, so if integer optimisation can be done, it should be possible to do what you want via integer optimisation, but the end user would have to shoulder some of the burden to convert from integers to float with a certain resolution in the objective function.

If you have a good example of how to implement integer optimisation then please reopen this issue and attach a reference.
