### ISSUE TITLE
Likely unnecessary invalid value warning from PchipInterpolator

### ISSUE THREAD

**Issue by millivolt9** [scipy/scipy#14140]
My issue is about Scipy.Interpolate.PchipInterpolator sometimes producing likely unnecessary
"RuntimeWarning: invalid value encountered in true_divide"
at line 288 during the evaluation of:
whmean = (w1/mk[:-1] + w2/mk[1:]) / (w1 + w2)
when interpolating over complex values.

This is because numpy produces both "invalid value" and "divide by zero" warnings in a true_divide when the divisor (in this case mk) contains a complex 0.+0.j. This can be shown by evaluating
np.array(4)/np.array(0).astype('complex128')
Because the above line in PchipInterpolator is inside a with np.errstate(divide='ignore') block, the "divide by zero" warning is suppressed, but not the "invalid value" warning. If the intent is to suppress warnings from all zero value divisors, and not just real zeros, adding invalid='ignore' to the np.errstate call will fix the problem.

Definitions of both types of numpy warning are at https://numpy.org/doc/stable/reference/generated/numpy.seterr.html.

#### Reproducing code example:

```
interpolated_point = PchipInterpolator(np.array([1,2,3,4,5]),np.array([1,2,2,3,4]).astype('complex128'))
```

#### Error message:

```
RuntimeWarning: invalid value encountered in true_divide
  whmean = (w1/mk[:-1] + w2/mk[1:]) / (w1 + w2)
```

#### Scipy/Numpy/Python version information:

Scipy 1.6.2 
Numpy 1.20.2 
sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)

**Comment by ev-br** [comment]
This would likely be acceptable, would you be interested in sending a PR? 

An obligatory comment is that pchip is not guaranteed to do sensible things in the complex plane.

**Comment by millivolt9** [comment]
Sure, what should I fork from, and what should be the target branch?

**Comment by ev-br** [comment]
It's the master branch

**Comment by millivolt9** [comment]
Created PR: https://github.com/scipy/scipy/pull/14208
