### ISSUE TITLE
Cannot Import scipy.stats.qmc

### ISSUE THREAD

**Issue by adam-lam** [scipy/scipy#14147]
My issue is about importing scipy.stats.qmc :

The line reads - 
import scipy
from scipy.stats import qmc

the error reads -
ImportError: cannot import name 'qmc' from 'scipy.stats' (.../python3.9/site-packages/scipy/stats/__init__.py)

Scipy/Numpy/Python version information:
Scipy 1.6.3
Numpy 1.20.3
Python 3.9.5

------------
I am not sure what is causing this issue. Would you have any suggestions?

**Comment by rkern** [comment]
`scipy.stats.qmc` will be in the 1.7.0 release, not 1.6.3.

**Comment by adam-lam** [comment]
Thanks for the clarification.
