### ISSUE TITLE
`ndimage.affine_transform` unexpected rotation result

### ISSUE THREAD

**Issue by the-lay** [scipy/scipy#14156]
My issue is about `ndimage.affine_transform`. I am not sure if that's an actual bug or am I creating a wrong matrix. I would appreciate if someone checks it out. 

It seems that there is a some kind of an off-by-one error that I first noticed when rotating an object by 90, 180 or 270 degrees. This seem to happen in various modes (including "nearest") and spline orders.

#### Reproducing code example:
```python
from scipy.ndimage import affine_transform
import numpy as np
import matplotlib.pyplot as plt


def _2d_rotation_matrix(theta, rotation_center):
    theta = np.deg2rad(theta)
    c, s = np.cos(theta), np.sin(theta)
    m = np.array([
        [1, 0, rotation_center[0]],
        [0, 1, rotation_center[1]],
        [0, 0, 1]
    ])
    m = np.dot(m, np.array([
        [c, -s, 0],
        [s, c, 0],
        [0, 0, 1]
    ]))
    m = np.dot(m, np.array([
        [1, 0, -rotation_center[0]],
        [0, 1, -rotation_center[1]],
        [0, 0, 1]
    ]))
    return m


data = np.ones((100, 100))
fig, ax = plt.subplots(1, 4)
plt.tight_layout()
fig.suptitle('constant mode, order=3')
ax[0].set_title('Original')
ax[0].imshow(data, vmin=0)
ax[1].set_title('90 deg')
ax[1].imshow(affine_transform(data, _2d_rotation_matrix(90, (50, 50))))
ax[2].set_title('180 deg')
ax[2].imshow(affine_transform(data, _2d_rotation_matrix(180, (50, 50))))
ax[3].set_title('270 deg')
ax[3].imshow(affine_transform(data, _2d_rotation_matrix(270, (50, 50))))
plt.show()

```
![scipy](https://user-images.githubusercontent.com/1889128/120174099-646a8d00-c20d-11eb-9d4e-1f1942c1d65c.png)

#### Scipy/Numpy/Python version information:
```
1.6.3 1.20.0 sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)
```

**Comment by rkern** [comment]
Use `sindg()` and `cosdg()` from `scipy.special` if you want more precise results for 90-degree increments. Converting to radians means that the resulting sines and cosines are not exactly 1 or 0.

**Comment by the-lay** [comment]
> Use `sindg()` and `cosdg()` from `scipy.special` if you want more precise results for 90-degree increments. Converting to radians means that the resulting sines and cosines are not exactly 1 or 0.

Thanks for the suggestion, but that does not solve the problem:
<details>
  <summary>sindg / cosdg</summary>

  ```python

    from scipy.ndimage import affine_transform
    from scipy.special import sindg, cosdg
    import numpy as np
    import matplotlib.pyplot as plt
    
    
    def _2d_rotation_matrix(theta, rotation_center):
        c, s = cosdg(theta), sindg(theta)
        m = np.array([
            [1, 0, rotation_center[0]],
            [0, 1, rotation_center[1]],
            [0, 0, 1]
        ])
        m = np.dot(m, np.array([
            [c, -s, 0],
            [s, c, 0],
            [0, 0, 1]
        ]))
        m = np.dot(m, np.array([
            [1, 0, -rotation_center[0]],
            [0, 1, -rotation_center[1]],
            [0, 0, 1]
        ]))
        return m
    
    
    data = np.ones((100, 100))
    fig, ax = plt.subplots(1, 4)
    plt.tight_layout()
    ax[0].set_title('Original')
    ax[0].imshow(data, vmin=0)
    ax[1].set_title('90 deg')
    ax[1].imshow(affine_transform(data, _2d_rotation_matrix(90, (50, 50))))
    ax[2].set_title('180 deg')
    ax[2].imshow(affine_transform(data, _2d_rotation_matrix(180, (50, 50))))
    ax[3].set_title('270 deg')
    ax[3].imshow(affine_transform(data, _2d_rotation_matrix(270, (50, 50))))
    plt.show()

  ```
![cosdg_sindg](https://user-images.githubusercontent.com/1889128/120211815-fee0c580-c239-11eb-8a4c-18d0092fb0a8.png)
  

</details>

I've also tried to use radians and I got a similar result:
<details>
  <summary>radians</summary>

  ```python

from scipy.ndimage import affine_transform
import numpy as np
import matplotlib.pyplot as plt


def _2d_rotation_matrix(theta, rotation_center):
    c, s = np.cos(theta), np.sin(theta)
    m = np.array([
        [1, 0, rotation_center[0]],
        [0, 1, rotation_center[1]],
        [0, 0, 1]
    ])
    m = np.dot(m, np.array([
        [c, -s, 0],
        [s, c, 0],
        [0, 0, 1]
    ]))
    m = np.dot(m, np.array([
        [1, 0, -rotation_center[0]],
        [0, 1, -rotation_center[1]],
        [0, 0, 1]
    ]))
    return m


data = np.ones((100, 100))
fig, ax = plt.subplots(1, 4)
plt.tight_layout()
ax[0].set_title('Original')
ax[0].imshow(data, vmin=0)
ax[1].set_title('90 deg')
ax[1].imshow(affine_transform(data, _2d_rotation_matrix(np.pi/2, (50, 50))))
ax[2].set_title('180 deg')
ax[2].imshow(affine_transform(data, _2d_rotation_matrix(np.pi, (50, 50))))
ax[3].set_title('270 deg')
ax[3].imshow(affine_transform(data, _2d_rotation_matrix(3*np.pi/2, (50, 50))))
plt.show()


  ```

![radians](https://user-images.githubusercontent.com/1889128/120212127-4e26f600-c23a-11eb-9739-9ac7bdecdc38.png)


</details>

**Comment by rkern** [comment]
You still have an off-by-one (or off-by-0.5). The center is not `(50, 50)`, but `(49.5, 49.5)` (the first pixel is `(0, 0)` and the last is `(99, 99)`). But notice that you will still want the `sindg()` and `cosdg()`.

**Comment by the-lay** [comment]
> You still have an off-by-one (or off-by-0.5). The center is not `(50, 50)`, but `(49.5, 49.5)` (the first pixel is `(0, 0)` and the last is `(99, 99)`). But notice that you will still want the `sindg()` and `cosdg()`.

Thank you for your help! Completely missed that off-by-0.5 error.
It seems `ndimage.rotate()` is also doing [`(shape - 1) / 2`](https://github.com/scipy/scipy/blob/master/scipy/ndimage/interpolation.py#L928) to find center (as well as uses `sindg` and `cosdg`)
