### ISSUE TITLE
TST, BUG: test_rbfinterp.py -- test_interpolation_misfit_1d fails at least sporadically on Windows

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#14158]
@treverhines 

The rbf test failure described here is still causing issues: https://github.com/scipy/scipy/pull/14118#issuecomment-849024743

The most recent failure I see is in this log for Windows Python 3.8 64-bit with 64-bit OpenBLAS integers active: 
https://dev.azure.com/scipy-org/df8ffb44-7275-43bc-90f9-aa5c93ef5c51/_apis/build/builds/12443/logs/201

Do I have permission to temporarily disable this test on the windows platform while you investigate so I can proceed with the SciPy `1.7.0` release candidate process? If so, I will `xfail` it for that platform most likely and we can keep this issue open until a fix is available. If it really is the test itself that is the problem and not the underlying algorithm/implementation, that is less concerning at least for me, but I'm not an expert here.

**Comment by treverhines** [comment]
Sorry about this. Can you try changing `epsilon=0.6` to `epsilon=5.0` on the below line?
https://github.com/scipy/scipy/blob/a0e875ac3441a33ee90606143636d497802c5e36/scipy/interpolate/tests/test_rbfinterp.py#L203

If that still does not work, then I would be concerned that there is a real issue here. With `epsilon=0.6` there is a very ill-conditioned matrix being inverted, and so it seems reasonable that some platform differences could result in a singular matrix. The matrix should be much better conditioned with `epsilon=5.0`.

**Comment by tylerjereddy** [comment]
I'll check this today, give me a bit

**Comment by tylerjereddy** [comment]
Reproduced on MacOS as well on latest `master`, actually for a different kernel (`gaussian` on MacOS vs. `inverse_multiquadric` on Windows).

`python runtests.py -t scipy.interpolate.tests.test_rbfinterp::TestRBFInterpolatorNeighbors20::test_interpolation_misfit_1d `

```
__________________________________________________________________________________________________________________________ TestRBFInterpolatorNeighbors20.test_interpolation_misfit_1d[gaussian] ___________________________________________________________________________________________________________________________
scipy/interpolate/tests/test_rbfinterp.py:203: in test_interpolation_misfit_1d
    yitp = self.build(x, y, epsilon=0.6, kernel=kernel)(xitp)
scipy/interpolate/_rbfinterp.py:451: in __call__
    shift, scale, coeffs = _build_and_solve_system(
scipy/interpolate/_rbfinterp.py:127: in _build_and_solve_system
    raise LinAlgError(msg)
E   numpy.linalg.LinAlgError: Singular matrix.
```

**Comment by tylerjereddy** [comment]
Also, should this be in `.gitignore`: 


![image](https://user-images.githubusercontent.com/7903078/120370276-9e9d6280-c2d1-11eb-90ca-0449676db458.png)

**Comment by treverhines** [comment]
I do not understand why these errors are only sometimes occurring. That test should be deterministic (I have an unseeded RNG as input to `Halton`, but that should make no difference when `scramble=False`). I think increasing epsilon to 5.0 should resolve the issue for both of these kernels.  

That file should be put in .gitignore.

**Comment by tylerjereddy** [comment]
thanks, yeah the Mac/`gaussian` one happens *every* time for me locally when I call it directly; still checking windows just to be sure
