### ISSUE TITLE
Missing "inverse" word in the multidimensional Discrete Cosine/Sine Transforms documentation

### ISSUE THREAD

**Issue by FallenApart** [scipy/scipy#14168]
In https://docs.scipy.org/doc/scipy/reference/fft.html and inside idctn and idstn documents both methods are described as multidimensional Discrete Cosine/Sine Transforms instead of multidimensional inverse Discrete Cosine/Sine Transforms.

**Comment by kadatatlukishore** [comment]
Hello @tupui , can you assign me this issue ?

@FallenApart , this is required `multidimensional Discrete Cosine/Sine Transforms` to `multidimensional inverse Discrete Cosine/Sine Transforms` right ?

**Comment by tupui** [comment]
HI @kadatatlukishore, in our workflow we don't assign issues. It's enough to say here that you are working on this. Just check before on open PRs that someone is not working on it and did not say anything here (which they should). So feel free to propose something, you can also co-author some commits with @FallenApart. As you both wish 😃

**Comment by kadatatlukishore** [comment]
Thanks for the clarification @tupui and I've checked there is no open PR for this. Will start working on this, thanks again !

**Comment by FallenApart** [comment]
@kadatatlukishore @tupui The word "inverse" is still missing.

**Comment by peterbell10** [comment]
There hasn't been a release yet, so you'll only see it updated in the development version documentation:
https://scipy.github.io/devdocs/reference/fft.html
