### ISSUE TITLE
energy_distance is the squared value

### ISSUE THREAD

**Issue by vnmabus** [scipy/scipy#14161]
The `energy_distance` function does not compute the energy distance (as defined by Székely and used in the scientific literature). Instead it computes the **square root** of that distance (which is a metric, as the original energy distance does not verify the triangle inequality, but its square root does).

Thus, either the code should be changed to use the right definition, or a warning should be placed in the documentation to explain that the definition used is not the original one.

**Comment by rkern** [comment]
It depends on the reference which quantity is called "the energy distance". Our references 1 and 3, at least, label the metric quantity as "the energy distance", but some others label the square of the metric quantity as "the energy distance" (reference 4 notes the variability). The variability in the literature is worth noting in the docstring, but I wouldn't say that we are using a wrong definition.

**Comment by vnmabus** [comment]
Well, the Wikipedia should not be a primary source, but I agree that in the third reference the authors seem to have changed their mind and call "energy distance" to the square root of the original definition, either because its metric properties or by analogy with the distance covariance. However most scientific literature still uses the old name. Note that even recent work (such as https://doi.org/10.1016/j.jspi.2020.11.001) from the original authors uses the original definition. Maybe we should ask directly to @mariarizzo the rationale for that.

In coding the `dcor` package (which is mine) uses the original definition, and `energy` (the R package of the original authors) does not even have a function to compute the energy distance (the function `edist` computes a statistic based on the squared definition instead).

I am not sure if changing the implementation is appropriate, but I think that at least a warning in the documentation could help to clarify everything.

**Comment by rkern** [comment]
In scipy, we try to reserve "distance" for those with metric properties and use "divergence" or "dissimilarity" for others. Since the literature gives us an option here, I'm inclined to leave the name and implementation alone, but I welcome the addition of a note (but not a warning) about the variability in the naming.
