### ISSUE TITLE
gamma.ppf bug?

### ISSUE THREAD

**Issue by sling1678** [scipy/scipy#14180]
My issue is about ... scale in scipy.stats.gamma.ppf appears to be wrong.
scipy.stats.gamma.ppf(0.05, 13, scale=1/.685) should be 5.26736112976714, but it gives 11.225661739607098, which you would get if you wrongly did scipy.stats.gamma.ppf(0.05, 13, scale=.685) since I have beta=.685. A textbook claims that in R, the command qgamma(.05,13,1/.685) gives 5.26736. Is scale=1/beta versus scale=beta bug in scipy.stats.gamma.ppf?

#### Reproducing code example:

```
Sample code to reproduce the problem
```

#### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

**Comment by rkern** [comment]
Note that in R, the function signature is `qgamma(x, shape, rate)`, not `qgamma(x, shape, scale)`. `scale=1/rate`. `qgamma(0.05, 13, 0.685)` gives 11.22566, which matches the result of `gamma.ppf(x, shape, scale=1/rate)`.

```
> qgamma(0.05, 13, 0.685)
[1] 11.22566
> qgamma(0.05, 13, scale=1/0.685)
[1] 11.22566
```
