### ISSUE TITLE
Convex Hull Accuracy Issue

### ISSUE THREAD

**Issue by George-Ogden** [scipy/scipy#14185]
My issue is about `scipy.spatial.ConvexHull`

#### Reproducing code example:
```
from scipy.spatial import ConvexHull
import numpy as np
v = np.array(((0,1),(1,1e4+1),(2,1e8+1),(2,-1),(0,-1)))
print(ConvexHull(v).vertices)
>>> [3 2 4]
This should return [3 2 0 4]
v = np.array(((0,1),(1,1e4),(2,1e8),(2,-1),(0,-1)))
print(ConvexHull(v).vertices)
>>> [3 2 4]
This should return [3 2 1 0 4]
```

#### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
>>> 1.6.2 1.19.2 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
```
```
python --version
Python 3.8.10
```

**Comment by rkern** [comment]
The underlying library that we use for `ConvexHull` and the Delaunay triangulations uses relatively plain floating point arithmetic, which can have problems when you have such extreme examples.

http://www.qhull.org/html/qh-impre.htm

Adding `qhull_options='QJ'` or `qhull_options='QbB'` will give you the results that I expect (I _think_ that vertex 1 isn't on the convex hull in either case; it should always be on the left of the ray from `v[2]` to `v[0]` in either case).

**Comment by tylerjereddy** [comment]
Robert's answer sounds correct. A log-scale plot is useful in this case and see annotated code below. Note that if vertex 1 were ever so slightly higher you'd risk having co-linear points, which is a degenerate condition of convex hull algorithms. After all, if three vertices are co-linear two of them can't "see each other," which would violate the definition of convexity.

With randomly-generated points you are effectively guaranteed to avoid issues with what is called *general position* of the input generators, but of course real-world data can have issues with co-linearity and floating point precision problems.


![test](https://user-images.githubusercontent.com/7903078/120905261-366eb980-c60e-11eb-98e7-5b3cac978cd9.png)


```python
import numpy as np
from scipy.spatial import ConvexHull, convex_hull_plot_2d
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111)

v = np.array(((0,1), # top left corner
              (1,1e4+1), # internal generator, but dangerously close
                         # to being co-linear
              (2,1e8+1), # top right corner
              (2,-1), # bottom right corner
              (0,-1))) # bottom left corner

hull = ConvexHull(v, qhull_options='QJ')

# plotting stuff
convex_hull_plot_2d(hull, ax=ax)
ax.set_yscale('log', base=1.001)
ax.set_ylim((1e-4, v[..., 1].max() + 1e8))
fig.savefig('test.png')
```

**Comment by tylerjereddy** [comment]
I think we can close this as a usage query that is explained by the near-degeneracy/floating-point issues in the input, which is always a challenge in computational geometry.
