### ISSUE TITLE
Incorrect shape handling in `scipy.stat.multivariate_t.rvs` method

### ISSUE THREAD

**Issue by Sayam753** [scipy/scipy#14189]
The `rvs` method of `multivariate_t` works only when size parameter is strictly 1 dimensional. This is not the case with `multivariate_normal`.

#### Reproducing code example:

```python
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.6.3 1.20.3 sys.version_info(major=3, minor=7, micro=7, releaselevel='final', serial=0)
>>> import numpy as np
>>> from scipy.stats import multivariate_normal, multivariate_t
>>> mean, cov = np.zeros(2), np.eye(2)
>>> multivariate_normal.rvs(mean=mean, cov=cov, size=None).shape
(2,)
>>> multivariate_t.rvs(loc=mean, shape=cov, size=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sayam/miniconda3/envs/pymc_dev/lib/python3.7/site-packages/scipy/stats/_multivariate.py", line 4148, in rvs
    samples = loc + z / np.sqrt(x)[:, None]
IndexError: invalid index to scalar variable.

>>> multivariate_normal.rvs(mean=mean, cov=cov, size=(10, 3)).shape
(10, 3, 2)
>>> multivariate_t.rvs(loc=mean, shape=cov, size=(10, 3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sayam/miniconda3/envs/pymc_dev/lib/python3.7/site-packages/scipy/stats/_multivariate.py", line 4148, in rvs
    samples = loc + z / np.sqrt(x)[:, None]
ValueError: operands could not be broadcast together with shapes (10,3,2) (10,1,3) 

>>> multivariate_t.rvs(loc=mean, shape=cov, size=(3))
array([[ 1.54502738, -0.23866557],
       [-0.79040924, -1.72035808],
       [-0.28060545, -0.69889876]])
```

I guess the errors arise from this line - 
https://github.com/scipy/scipy/blob/f856e3e852a59120d44133a0ce550cceb19f9244/scipy/stats/_multivariate.py#L4084

This issue popped up while adding `MvStudentT` to PyMC3 https://github.com/pymc-devs/pymc3/pull/4731. Its random sampling method makes use of `scipy.stats.multivariate_t`.

**Comment by tirthasheshpatel** [comment]
The shape handling of ``multivariate_t`` and ``multivaraite_normal`` is completely broken. See gh-7689 for shape bugs in ``multivariate_normal`` distribution. Here are a few more broken examples:

```py
>>> from scipy.stats import multivariate_normal, multivariate_t
>>> # all the problems below also hold for multivariate_normal
>>> multivariate_t.rvs([0], [[1]], size=7)   # expected array of shape (7, 1)
array([ 1.64545405, -0.11754869,  0.14135387, -0.72304521, -3.50994847,
        2.15339272,  1.32959055])
>>> multivariate_t.rvs([0], [[1]], size=1)  # expected array of shape (1, 1)
9.221726325909353
>>> multivariate_t.rvs([0], [[1]], size=(1,))  # expected array of shape (1, 1)
0.38894268481522826
>>> multivariate_t.rvs([0], [[1]], size=(1,1,1,1,1,1))  # expected array of shape (1,1,1,1,1,1, 1)
-18.01539251887883
```

PDF also gives unexpected shapes:

```py
>>> from scipy.stats import multivariate_normal, multivariate_t
>>> # all the problems below hold for multivariate_normal too.
>>> multivariate_t.pdf([[[[[1.]]]]], loc=[0.], shape=[[1.]])  # expected an array of shape (1,1,1,1)
0.15915494309189535
```

Other inconsistencies:

```py
>>> from scipy.stats import multivariate_normal, multivariate_t
>>> # all the problems below hold for multivariate_normal too.
>>> multivariate_t.pdf([0., 1.], loc=[0], shape=[[1]])  # multivariate_t accepts this
array([0.31830989, 0.15915494])
>>> multivariate_t.pdf([[0., 1.]], loc=[0], shape=[[1]])  # but fails to accept this. I would expect it to broadcast
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tirthasheshpatel/Desktop/scipy_source/scipy/stats/_multivariate.py", line 3958, in pdf
    logpdf = self._logpdf(x, loc, shape_info.U, shape_info.log_pdet, df,
  File "/home/tirthasheshpatel/Desktop/scipy_source/scipy/stats/_multivariate.py", line 4029, in _logpdf
    maha = np.square(np.dot(dev, prec_U)).sum(axis=-1)
  File "<__array_function__ internals>", line 5, in dot
ValueError: shapes (1,2) and (1,1) not aligned: 2 (dim 1) != 1 (dim 0)
```

In the above example, the ideal behavior would be to only accept inputs with shape ``(..., 1)`` as it is a one-dimensional multivariate distribution. Other input sizes must raise an error. But currently, it accepts inputs with shape `(N, )` which is technically wrong. 

This is because of the use of `_squeeze_output` function before returning. As many other distributions use it, we might be too late to fix them without breaking backward compatibility. For now, I have submitted gh-14192 fixing this issue. But it would be better to fix some of the above inconsistencies in some other PR.

**Comment by Sayam753** [comment]
Hello @tirthasheshpatel . Happy to see you around and thanks for the quick reply.

I was also thinking about the use of ellipsis to fix this issue but struggled my way through setting up scipy dev environment locally. FInally, I got it working.

Now, I'll try to understand the shape handling in scipy in near future 🤞

**Comment by tirthasheshpatel** [comment]
> I was also thinking about the use of ellipsis to fix this issue but struggled my way through setting up scipy dev environment locally. FInally, I got it working.
> 

Happy to hear that you got it working! You can refer to https://docs.scipy.org/doc/scipy/reference/building/linux.html#debian-ubuntu anytime if you are on Ubuntu/Debian. If you are on windows, [this wiki page](https://github.com/scipy/scipy/wiki/Easy-Windows-10-Build-Scipy-from-source) might help set it up easily. Sorry, I was not aware you were working on this.

> Now, I'll try to understand the shape handling in scipy in near future crossed_fingers

Sure, @Sayam753 :smiley:! It would be very helpful if you could resolve the shape bugs I mentioned above. If you face any problems, feel free to ping me.

**Comment by Sayam753** [comment]
Unfortunately, I am on MacOS and was following this [tutorial](https://docs.scipy.org/doc/scipy/reference/dev/contributor/quickstart_mac.html#building-scipy). 

- In step 1, I installed `miniconda` instead of Anaconda (trying to be minimalist here)
- In step 11, this command `conda install mkl openblas cython numpy pytest pybind11 pythran=0.9.11 -c conda-forge` helped me to follow next steps.

>  Sorry, I was not aware you were working on this.

My bad, I should have mentioned this earlier. Thanks for the helping hands anyways.

**Comment by mdhaber** [comment]
@Sayam753 what step in the guide did you struggle with when setting up your environment?

**Comment by Sayam753** [comment]
Hello @mdhaber 
On the [Building Scipy](https://docs.scipy.org/doc/scipy/reference/dev/contributor/quickstart_mac.html#building-scipy) part in MacOS development guide - 

- The first step recommends installing Anaconda. But I installed miniconda. After the installation, I created a new conda environment (creating a conda env comes a lot later in the tutorial but I prefer keeping my base env clean, so that's why I created a new env)
- Then following as it is till step 13, I could not do an in-place build. Tracing the errors, it turned out my environment didn't have `mkl`, `openblas` and `pythran`
- So, my step 11 was basically to install them all via
```
conda install mkl openblas cython numpy pytest pybind11 pythran=0.9.11 -c conda-forge
conda install conda-build  # Helped in `conda develop /scipy` part
```

Rest, everything was smooth.

**Comment by Sayam753** [comment]
As I am looking more into it, I should have been following latest [devdocs tutorial](https://scipy.github.io/devdocs/dev/contributor/quickstart_mac.html#quickstart-mac) instead of tutorial at `1.6.3` release [here](https://docs.scipy.org/doc/scipy/reference/dev/contributor/quickstart_mac.html#quickstart-mac)

I got confused tricked with `dev` word in 1.6.3 release URL https://docs.scipy.org/doc/scipy/reference/dev/contributor/quickstart_mac.html#building-scipy and assumed them to be dev docs. Anyways, I will https://scipy.github.io/devdocs/dev/contributor/quickstart_mac.html#quickstart-mac from now

**Comment by mdhaber** [comment]
Yes, it's best to look at the dev version of the developer guide when working with `master`. (Then again, not even _that_ is always up to date... there are some issues with the Ubuntu quickstart guide right now.)
