### ISSUE TITLE
Links in documentation of Dirichlet distribution are a mess

### ISSUE THREAD

**Issue by madphysicist** [scipy/scipy#14190]
Looking at page for `scipy.stats.dirichlet`: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.dirichlet.html, the following issues cropped up:

- Link to `alpha` in the second sentence is to the wrong alpha (not the parameter).
- Methods in the last section have a bunch of double backticks but no meaningful links.
- Self-link in the notes section seems spurious, but at least it's not outright wrong.

See https://stackoverflow.com/q/67855329/2988730 for an example of how this makes the documentation confusing.

**Comment by NamamiShanker** [comment]
I'll take up this issue

**Comment by NamamiShanker** [comment]
@madphysicist Can you please give me the link to the correct alpha?

**Comment by ilayn** [comment]
you need to double the single backticks here so that it doesn't try to link it to a function or a module 

https://github.com/scipy/scipy/blob/v1.6.3/scipy/stats/_multivariate.py#L1320

**Comment by NamamiShanker** [comment]
Thanks, @ilayn! I have made the changes. What should I do about the second and third point of this issue?

**Comment by NamamiShanker** [comment]
@madphysicist @ilayn I have submitted PR #14200. Please review it and suggest any changes.
