### ISSUE TITLE
find_peaks_cwt raises TypeError when using wavelet functions different than ricker

### ISSUE THREAD

**Issue by griquelme** [scipy/scipy#14229]
Hi I was trying to use the `find_peaks_cwt` function using other wavelets, but I get a TypeError:

```
import numpy as np
from scipy.signal.windows import gaussian
from scipy.signal import find_peaks_cwt

x = gaussian(200, 2)
widths = np.array([1, 2, 3, 4])
find_peaks_cwt(x, widths, wavelet=gaussian)
```

#### Error message:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-f207b53c7d51> in <module>
      5 x = gaussian(200, 2)
      6 widths = np.array([1, 2, 3, 4])
----> 7 find_peaks_cwt(x, widths, wavelet=gaussian)

~/miniconda3/envs/pycharm/lib/python3.8/site-packages/scipy/signal/_peak_finding.py in find_peaks_cwt(vector, widths, wavelet, max_distances, gap_thresh, min_length, min_snr, noise_perc, window_size)
   1289         wavelet = ricker
   1290 
-> 1291     cwt_dat = cwt(vector, wavelet, widths, window_size=window_size)
   1292     ridge_lines = _identify_ridge_lines(cwt_dat, max_distances, gap_thresh)
   1293     filtered = _filter_ridge_lines(cwt_dat, ridge_lines, min_length=min_length,

~/miniconda3/envs/pycharm/lib/python3.8/site-packages/scipy/signal/wavelets.py in cwt(data, wavelet, widths, dtype, **kwargs)
    461     # Determine output type
    462     if dtype is None:
--> 463         if np.asarray(wavelet(1, widths[0], **kwargs)).dtype.char in 'FDG':
    464             dtype = np.complex128
    465         else:

TypeError: gaussian() got an unexpected keyword argument 'window_size'
```

This error is raised also when using other wavelets from `scipy.signal.wavelet`

scipy version: 

```
1.6.2 1.20.3 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
```

Looking at the source of  `find_peaks_cwt` I think that the problem is related with the  `window_size` argument that is passed to the wavelet function inside `cwt`. Currently, I am avoiding this problem by wrapping the `gaussian` function, but I think that the problem could be solved by removing the `window_size` parameter passed to `cwt`

```
def gaussian_wavelet(n, sigma, window_size=None):
    return gaussian(n, sigma)

find_peaks_cwt(x, widths, wavelet=gaussian_wavelet)
```

**Comment by endolith** [comment]
`gaussian` is a window function, not a wavelet function.  I think the only compatible wavelet functions are `ricker` and `morlet2`.  

`morlet` was created before `cwt` and is not compatible with it. https://dsp.stackexchange.com/a/18104/29

find_peaks_cwt should document what the built-in options are, and maybe accept strings instead?

Maybe a better error message would help?

> ValueError: The "gaussian" function is not compatible with "cwt". Function must have have parameters [points, width].

or something like that?
