### ISSUE TITLE
Documentation for dctn/idctn s-parameter is confusing

### ISSUE THREAD

**Issue by Firionus** [scipy/scipy#14220]
The [documentation for dctn](https://docs.scipy.org/doc/scipy/reference/generated/scipy.fft.dctn.html) states that `s` is the shape of the result. It then details truncation and padding behavior.  
Therefore, I would have expected this truncation/padding happens on the output, after performing dct. However, it applies to the input before performing dct. 

### Steps to Reproduce
```python
import numpy as np
from scipy.fft import dctn

a = np.array([
    [1,2,3],
    [4,5,6],
    [7,12,9]
    ])

with_s_param = dctn(a, s=(2,2))
trunc_input = dctn(a[0:2, 0:2])
trunc_output = dctn(a)[0:2, 0:2]

print("s applies to input: ", np.array_equal(with_s_param, trunc_input))
print("s applies to output: ", np.array_equal(with_s_param, trunc_output))
```

Output:

```
s applies to input:  True
s applies to output:  False
```

### Expected Behavior

From the documentation I expected `s` to apply to the output. This would allow not calculating some dct values if only certain frequencies are of interest. This would belong into a different issue though. 

### Suggested Wording

Insert "of `x`" at relevant places:

```
    s : int or array_like of ints or None, optional
        The shape of the result. If both `s` and `axes` (see below) are None,
        `s` is ``x.shape``; if `s` is None but `axes` is not None, then `s` is
        ``numpy.take(x.shape, axes, axis=0)``.
        If ``s[i] > x.shape[i]``, the ith dimension of `x` is padded with zeros.
        If ``s[i] < x.shape[i]``, the ith dimension of `x` is truncated to length
        ``s[i]``.
        If any element of `s` is -1, the size of the corresponding dimension of
        `x` is used.
```

### Environment

- SciPy 1.6.3
- NumPy 1.20.2
- Python 3.8.6
- Linux 5.8.0

**Comment by lucascolley** [comment]
thanks @Firionus . I'll fix this
