### ISSUE TITLE
SciPy minimize breaks on newer versions of NumPy

### ISSUE THREAD

**Issue by winstxnhdw** [scipy/scipy#14223]
I am working on a API that relies on minimizing a complicated equation using SciPy 1.6.3. On a working version, I was on NumPy 1.17.4 and there were no problems with running SciPy's minimize function. However, when I updated to NumPy 1.20.3, the minimize function would go on endlessly and never return, even though the input is exactly the same. 

I can't provide much sample code as the code I write is legally bound to my company. However, I believe this information might still be helpful for others that come across this issue.

EDIT: I tested and it only breaks from NumPy 1.19.3 onwards on Python 3.9.5. If you use Python 3.8.5, this version of NumPy will not work.

#### Reproducing code example:
```
def objective_fcn(lateral_offset, wox, woy, wyaw, wk):

    for n in range(0, len(wyaw)):
        wox[n] += lateral_offset[n]*np.sin(wyaw[n])
        woy[n] -= lateral_offset[n]*np.cos(wyaw[n])

    wok = calculate_curvature(wox, woy)

    curvature_cost = wk * np.mean(np.square(wok))

    return curvature_cost

result = minimize(objective_fcn, guess, args, bounds=bounds, options={'maxfun': 1000000})
```

#### Error message:
None. Never has the chance to produce an error.

**Comment by mdhaber** [comment]
Please try to find another example that you can share that exhibits the same problem. Can you modify the code and numbers to strip away sensitive information? Can you provide your call to `minimize`, tell us which solver is being used, or describe what types of constraints you have?

**Comment by winstxnhdw** [comment]
```
result = minimize(objective_fcn, guess, args, bounds=bounds, options={'maxfun': 1000000})
```

> Please try to find another example that you can share that exhibits the same problem. Can you modify the code and numbers to strip away sensitive information? Can you provide your call to `minimize`, tell us which solver is being used, or describe what types of constraints you have?

**Comment by winstxnhdw** [comment]
> Please try to find another example that you can share that exhibits the same problem. Can you modify the code and numbers to strip away sensitive information? Can you provide your call to `minimize`, tell us which solver is being used, or describe what types of constraints you have?

I am using L-BFGS-B
```
result = minimize(objective_fcn, guess, args, bounds=bounds, options={'maxfun': 1000000})
```

**Comment by tupui** [comment]
Did you solve your issue @winstxnhdw? Without more details, I am afraid I don't see how we could debug the problem.

**Comment by winstxnhdw** [comment]
> Did you solve your issue @winstxnhdw? Without more details, I am afraid I don't see how we could debug the problem.

Hello @tupui, I did not find a way to solve this issue other than downgrading my NumPy version. However, I did notice that I was able to reproduce the same issue in this [Notebook](https://github.com/winstxnhdw/OfflinePathOptimisation/blob/master/examples/controlled.ipynb) of mine. You may want to give it a try by running the Notebook with NumPy >1.19.3.

**Comment by tupui** [comment]
> > Did you solve your issue @winstxnhdw? Without more details, I am afraid I don't see how we could debug the problem.
> 
> Hello @tupui, I did not find a way to solve this issue other than downgrading my NumPy version. However, I did notice that I was able to reproduce the same issue in this [Notebook](https://github.com/winstxnhdw/OfflinePathOptimisation/blob/master/examples/controlled.ipynb) of mine. You may want to give it a try by running the Notebook with NumPy >1.19.3.

Sorry but I don't have enough time to go through this much code to try to spot something here... It will be difficult without a minimal example here. The function is benchmarked on so many cases, that I would first suggest to ensure your code is really doing what you think it is doing.

**Comment by winstxnhdw** [comment]
> > > Did you solve your issue @winstxnhdw? Without more details, I am afraid I don't see how we could debug the problem.
> > 
> > 
> > Hello @tupui, I did not find a way to solve this issue other than downgrading my NumPy version. However, I did notice that I was able to reproduce the same issue in this [Notebook](https://github.com/winstxnhdw/OfflinePathOptimisation/blob/master/examples/controlled.ipynb) of mine. You may want to give it a try by running the Notebook with NumPy >1.19.3.
> 
> Sorry but I don't have enough time to go through this much code to try to spot something here... It will be difficult without a minimal example here. The function is benchmarked on so many cases, that I would first suggest to ensure your code is really doing what you think it is doing.

I was able to replicate my issue on another colleague's laptop and solved it by downgrading NumPy. I think we can just place this as an outlier case. I am unable to replicate the issue on a simpler case. AFAIK, I've not seen anyone use the function this way and I don't think the minimize function was intended to be used the way I am using it. If you wish to investigate further and require more specific information, I am more than happy to help.

**Comment by tupui** [comment]
> ... I've not seen anyone use the function this way and I don't think the minimize function was intended to be used the way I am using it.

What do you mean by that? You have an objective function, a guess, some bounds and a callback function. What is specific here in terms of optimization?

**Comment by winstxnhdw** [comment]
> > ... I've not seen anyone use the function this way and I don't think the minimize function was intended to be used the way I am using it.
> 
> What do you mean by that? You have an objective function, a guess, some bounds and a callback function. What is specific here in terms of optimization?

The arguments I am passing to the objective function is an array that could have a length of >100, which I have not seen any examples of online. I guess I would say that the objective function is not conventional and cannot be easily visualised as a 2D graph?

**Comment by tupui** [comment]
n-D optimization problems are very frequents. Have a look at the documentation of [scipy.optimize.basinhopping](https://scipy.github.io/devdocs/reference/generated/scipy.optimize.basinhopping.html#scipy.optimize.basinhopping). The note section clearly state that this method has been used in problems with over 300 parameters.

**Comment by andyfaff** [comment]
I've had a look at the code in the notebook that was suggested as an example. It's very inefficient, with a lot of for loops which can be vectorised relatively straightforwardly. For example:

```
def solve_1st_derivative(x, y):

    dx = []
    dy = []

    for i in range(0, max(len(x), len(y)) - 1):
        dx.append(x[i+1] - x[i])
        dy.append(y[i+1] - y[i])

    dx.append(dx[-1])
    dy.append(dy[-1])
    return dx, dy
```
the loop could be removed by replacing with the `np.ediff1d` function, or `dx = x[1:] - x[:-1]`.

You could replace:
```
for n in range(0, len(wyaw)):
    wox[n] += lateral_offset[n]*np.sin(wyaw[n])
    woy[n] -= lateral_offset[n]*np.cos(wyaw[n])
```
with 
```
   wox += lateral_offset * np.sin(wyaw)
   woy -= lateral_offset * np.cos(wyaw)
```

I'd expect at least a couple of orders of magnitude speedup with fully vectorised code. You could do even better by using JAX to do autodifferentiation, but that's an advanced exercise.

Anyway the minimization code seems to run successfully:
```
def callback(Xi):
    print(objective_fcn(Xi))

result = minimize(objective_fcn, guess, bounds=bounds, callback=callback, options={'maxfun': 1000000})

print(result)
```
```
0.0658525998677267
0.060806787361024656
0.05881815071216538
0.05699806293173606
0.055267224998168
0.052613000036262014
0.05030845004793137
0.049319539146835054
0.049195285996606886
0.047415692698585664
0.046987716600306234
0.04664024193717391
0.045873553592608335
0.04530918642002008
0.04522880482226817
0.04474659872216179
0.04459810395585275
0.04401491416387783
0.04380918039113812
0.04359035057679652
0.04328377764709902
0.043055689500981896
0.042617837489822875
0.04251974116632993
0.04236449269954498
0.04229490125378102
0.042220399191091114
0.04212228909879529
0.04201790934448101
0.04193221405272249
0.041761458386260976
0.04163015571136675
0.04145689231594317
0.041352618900566594
0.04124013030108428
0.04115312674172401
0.041112472337094634
0.041078237945150003
0.04105933638097692
0.041035893324791566
0.041009097228665504
0.04100037557215719
0.040977328803338695
0.0409637088499271
0.04095275666173207
0.04093706216805471
0.04091741320539784
0.04090705169166499
0.0408965759413781
0.040890167407183944
0.04088539161361263
0.04088056055253094
0.04087757281596992
0.04087116159276822
0.04086491915110123
0.04086055685231321
0.04085528185528008
0.0408527108195816
0.04084743611974086
0.04084460593053029
0.04084154220022286
0.040838512989302495
0.040835921543271224
0.04083249993457688
0.040828802321176146
0.04082523619939868
0.04082238522978843
0.040818597567709274
0.0408143445047303
0.04081033802472016
0.04080660482714849
0.04080261008458173
0.04080006860152019
0.04079775532705549
0.040796737258156066
0.04079451294466342
0.04079107013479045
0.04078814604170903
0.040784096455860806
0.040782268534509405
0.040780370440288795
0.04077747954780895
0.04077541768020169
0.04077248322499417
0.0407714831963916
0.0407708960597597
0.04076954097855637
0.04076815161628393
0.04076548308320448
0.04076440158978425
0.04076371965366293
0.040762866039149304
0.04076169549217993
0.04076034205323629
0.040759613683232256
0.040757523667306464
0.04075562048045566
0.04075332573181078
0.04075097231912483
0.040749171329569595
0.04074693734240372
0.04074432720385816
0.0407417358743648
0.040739952897841596
0.04073797695733971
0.04073735112354205
0.040736561882618566
0.040735437079354245
0.040734184645675985
0.04073251215516516
0.040731567641462046
0.04073131976409382
0.04073114461811371
0.040730899411177295
0.0407307510374362
0.040730141963178784
0.04072939174738155
0.04072885858002787
0.040728305609354025
0.040728101560878666
0.04072790625648542
0.040727455586243855
0.04072656775246403
0.04072514108870734
0.040724479574452806
0.04072297213794204
0.04072230032461728
0.04072203030828571
0.04072191060086138
0.04072191059390295
      fun: 0.04072191059390295
 hess_inv: <117x117 LbfgsInvHessProduct with dtype=float64>
      jac: array([ 7.41612605e-03, -7.25808303e-07, -4.51431670e-03, -5.89624946e-03,
       -1.43898782e-05,  3.60114716e-05,  5.69821967e-06,  3.85779186e-03,
        2.75258982e-05, -1.80661042e-05,  1.73826231e-05,  3.73312492e-06,
       -1.28605460e-05,  3.90104615e-06, -8.60561622e-06,  2.12559137e-05,
       -6.22141228e-06, -7.12832571e-06,  1.58212124e-03, -4.60818883e-05,
       -4.97456243e-05, -2.46172249e-03,  3.90382171e-05, -1.48839274e-06,
       -6.36463105e-05, -1.59143532e-05,  6.81309176e-05, -5.48727730e-05,
       -7.62584440e-07, -4.59243754e-05,  2.40175796e-03,  7.44349027e-05,
       -4.54761229e-05,  6.54712396e-05, -8.20935681e-04, -5.38046691e-04,
       -7.47901741e-05, -3.16278254e-04,  6.08214868e-05,  7.83500348e-04,
        2.12226070e-05,  5.53460056e-05, -2.72407097e-04, -1.43088319e-04,
       -9.81784099e-06,  2.35908515e-05, -8.29197822e-07,  3.40769080e-06,
       -3.25003913e-05, -1.47756807e-05,  1.10807197e-05, -2.00950368e-06,
        6.58015309e-06, -4.37212766e-05, -4.24302260e-04,  3.23754912e-05,
        1.24553146e-06,  4.55515487e-04,  4.78950907e-04, -6.97122915e-05,
        7.19736771e-05, -3.20377752e-04, -1.17912624e-05, -2.12593832e-05,
       -2.69666234e-05, -3.28660710e-05, -2.18533525e-05, -5.97924488e-06,
       -5.14148446e-04,  9.85947435e-06,  6.96205594e-04,  4.65115446e-04,
        2.40370224e-05, -4.93793201e-04, -5.68503578e-06, -8.93798924e-06,
       -5.35821388e-06, -8.59590177e-06, -1.71987424e-05, -7.95197241e-06,
        6.99162950e-06,  7.80972509e-06,  8.43908277e-06, -2.72559752e-06,
        4.98975861e-06, -6.79109546e-06,  1.53009549e-05, -5.37181411e-05,
        5.78419257e-05, -2.63511435e-05,  1.58976998e-05, -9.58955138e-07,
        8.02136136e-07, -2.71314221e-04, -8.77391216e-04, -5.02996256e-04,
        6.12995766e-05,  2.40831175e-03,  2.37393438e-05,  1.81292481e-05,
       -1.41617620e-03, -1.77231840e-04, -9.25107214e-05, -2.01345885e-05,
        1.07906739e-05,  8.79157858e-07, -8.12752643e-06, -1.38916656e-05,
        1.58220659e-05, -2.08763562e-05,  2.51021426e-05, -1.36508860e-05,
        1.04451170e-05,  8.14140422e-06, -3.30305228e-05,  1.35717826e-05,
        5.85712035e-06])
  message: 'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     nfev: 21948
      nit: 130
     njev: 186
   status: 0
  success: True
        x: array([-0.14639508,  0.19146153,  0.5       ,  0.5       ,  0.30338461,
        0.13814399, -0.0155635 ,  0.        ,  0.11858782,  0.11700586,
        0.10138431, -0.13609716, -0.11037305,  0.0445164 ,  0.0401983 ,
        0.11023333,  0.07329941,  0.03003496,  0.        ,  0.03354432,
        0.38322968,  0.5       ,  0.18412689,  0.08848675, -0.19610823,
        0.05042909,  0.28118243,  0.17286661, -0.28084572, -0.46072737,
       -0.5       , -0.35788139,  0.14558001,  0.33030084,  0.5       ,
        0.5       ,  0.5       ,  0.5       ,  0.25496107,  0.        ,
        0.09788152,  0.28629596,  0.5       ,  0.5       ,  0.46561254,
        0.17441206,  0.00975119, -0.09831178, -0.14547266, -0.12591886,
       -0.01128213,  0.16886985,  0.33943658,  0.5       ,  0.5       ,
        0.23948668, -0.01222591, -0.26907873, -0.35325879, -0.1808709 ,
        0.14834904,  0.5       ,  0.40205712,  0.36597854,  0.29567265,
        0.33851716,  0.48293965,  0.42442069,  0.5       ,  0.02983126,
       -0.15893649,  0.        ,  0.40123612,  0.5       ,  0.37708481,
        0.28567538,  0.2162202 ,  0.0742568 , -0.04298986, -0.0025823 ,
       -0.02138931, -0.17190568,  0.00760392,  0.05339598, -0.005686  ,
       -0.04826551,  0.01762861,  0.06961584,  0.05733849, -0.05873952,
       -0.06342499,  0.09458716,  0.20591917,  0.5       ,  0.5       ,
        0.5       , -0.21036681, -0.5       , -0.44446404,  0.20338488,
        0.5       ,  0.5       ,  0.5       ,  0.36293575,  0.2181898 ,
        0.14898882,  0.09542703, -0.10658777, -0.14832537, -0.10404173,
        0.00307073,  0.03392289,  0.13429068,  0.09670851, -0.05010586,
        0.01936023, -0.09736319])
```

I'm using 3.9.6 and numpy 1.21 and scipy 1.7.0.

I note that you're using a package called `optimparallel`, that's not a part of scipy, so if it's an issue there then we can't help further.

**Comment by winstxnhdw** [comment]
> I've had a look at the code in the notebook that was suggested as an example. It's very inefficient, with a lot of for loops which can be vectorised relatively straightforwardly. For example:
> 
> ```
> def solve_1st_derivative(x, y):
> 
>     dx = []
>     dy = []
> 
>     for i in range(0, max(len(x), len(y)) - 1):
>         dx.append(x[i+1] - x[i])
>         dy.append(y[i+1] - y[i])
> 
>     dx.append(dx[-1])
>     dy.append(dy[-1])
>     return dx, dy
> ```
> 
> the loop could be removed by replacing with the `np.ediff1d` function, or `dx = x[1:] - x[:-1]`.
> 
> You could replace:
> 
> ```
> for n in range(0, len(wyaw)):
>     wox[n] += lateral_offset[n]*np.sin(wyaw[n])
>     woy[n] -= lateral_offset[n]*np.cos(wyaw[n])
> ```
> 
> with
> 
> ```
>    wox += lateral_offset * np.sin(wyaw)
>    woy -= lateral_offset * np.cos(wyaw)
> ```
> 
> I'd expect at least a couple of orders of magnitude speedup with fully vectorised code. You could do even better by using JAX to do autodifferentiation, but that's an advanced exercise.

Hey @andyfaff, thank you for the insightful suggestions. I have implemented them, earning me a 4 second improvement on the dataset and definitely much cleaner code.

> Anyway the minimization code seems to run successfully:
> 
> ```
> def callback(Xi):
>     print(objective_fcn(Xi))
> 
> result = minimize(objective_fcn, guess, bounds=bounds, callback=callback, options={'maxfun': 1000000})
> 
> print(result)
> ```

> I'm using 3.9.6 and numpy 1.21 and scipy 1.7.0.
> 
> I note that you're using a package called `optimparallel`, that's not a part of scipy, so if it's an issue there then we can't help further.

I've tried again with scipy 1.6.3 and numpy 1.20.3 *without* using the `optimparallel` package. Again, the issue remains and the optimizer does not ever return.

**Comment by andyfaff** [comment]
The suggestions I gave were just the start. What does the callback print in the situation where it never finishes?

**Comment by winstxnhdw** [comment]
> The suggestions I gave were just the start. 
Very much appreciated :)

> What does the callback print in the situation where it never finishes?
It was printing a value so I left it to run on its own for about an hour and you were right, it did succeed in the end. However, when I am on NumPy 1.19.3, it takes **half** the time to complete. All this time I was thinking that it was frozen because it was taking so much longer.

**Comment by andyfaff** [comment]
Your code takes so long because of the loops you are using rather than vectorising everything with numpy. I'd expect a 2 to 3 order of magnitude speedup if you could eliminate all the loops.
