### ISSUE TITLE
Can not profile a script import scipy with nvprof

### ISSUE THREAD

**Issue by szsdk** [scipy/scipy#14233]
I have a script using scipy and cupy. When I tried to profile the running, I got an error.

#### Reproducing code example:

```python
from scipy.ndimage import gaussian_filter
```
Run this `t.py` with
```
nvprof -o t.prof python t.py
```

#### Error message:
```
Missing definition of the OpenACC API routine/s in the OpenACC library linked to the application.
```
Is this error related to how scipy compiled?

#### Scipy/Numpy/Python version information:
- system: Linux sz-desktop 5.12.10-arch1-1 x86_64 GNU/Linux
- scipy: 1.6.3
- numpy: 1.20.3
- nvcc: Build cuda_11.3.r11.3/compiler.29745058_0

**Comment by rgommers** [comment]
This question fell through the cracks, sorry @szsdk. SciPy is CPU-only so has nothing to do with either OpenACC or NVCC. I'll close this, since it seems irrelevant.
