### ISSUE TITLE
_nd_image.py not available

### ISSUE THREAD

**Issue by LilianaArguello** [scipy/scipy#14247]
Trying to understand what was inside _nd_image to check out _nd_image.correlate1d, but could not find the file in ndimage folder while it is imported at scipy/scipy/ndimage/filters.py

from . import _nd_image

**Comment by ShantanuDash** [comment]
from what i understand there are files `nd_image.c` and `nd_image.h` in the src folder which are processed using [cython](https://cython.org/)  most probably by setup.py. I did not delve too deep but i think this part of the setup.py describes it

```py
config = Configuration('ndimage', parent_package, top_path)

    include_dirs = ['src',
                    get_include(),
                    os.path.join(os.path.dirname(__file__), '..', '_lib', 'src')]

    config.add_extension("_nd_image",
        sources=["src/nd_image.c",
                 "src/ni_filters.c",
                 "src/ni_fourier.c",
                 "src/ni_interpolation.c",
                 "src/ni_measure.c",
                 "src/ni_morphology.c",
                 "src/ni_splines.c",
                 "src/ni_support.c"],
        include_dirs=include_dirs,
        **numpy_nodepr_api)
```

**Comment by LilianaArguello** [comment]
Very eye opening your comment. Makes sense, I'll spend some time to understand cython. Thanks a lot. I close the issue.

**Comment by rkern** [comment]
For the record, they are not Cython files, but just plain old pure C extension modules.

You can see [here](https://github.com/scipy/scipy/blob/master/scipy/ndimage/src/nd_image.c#L1124) the table that maps the Python name `correlate1d` to the [`Py_Correlate1D`](https://github.com/scipy/scipy/blob/master/scipy/ndimage/src/nd_image.c#L184) C function. That function does not do much except handle the conversion of Python arguments to pass on to the [C implementation `NI_Correlate1D`](https://github.com/scipy/scipy/blob/master/scipy/ndimage/src/ni_filters.c#L38) which has the guts of the algorithm.

**Comment by ShantanuDash** [comment]
@rkern Thanks for clarifying. I had no idea how cython really worked so just made a guess!
