### ISSUE TITLE
Sparse pivot for linalg.lu

### ISSUE THREAD

**Issue by RikVoorhaar** [scipy/scipy#14243]
Currently `p, l, u = scipy.linalg.lu(a)` returns a dense permutation matrix `p` for the pivots of shape `(M, M)` for `a` of shape `(M, N)`. If the input matrix is tall and skinny (`M` >> `N`), then the storage costs of `p` are unacceptable. 

A workaround is to make LAPACK calls directly, e.g. use `linalg.lapack.dgetrf(a)`, since the LAPACK implementation of the LU factorization returns a 1-d integer array for the pivots. 

It seems that `linalg.lu` uses `linalg/src/lu.f` rather than the LAPACK implementation. Is this faster than the LAPACK implementation? Either way, I suggest to add an option to return an 1-d integer array for the pivots. If this option is invoked, then the appropriate LAPACK routine is called. This should be very easy to implement, shall I make a PR?

**Comment by ilayn** [comment]
If you only need the permutation you can use `scipy.linalg.lu_factor`

**Comment by RikVoorhaar** [comment]
`scipy.linalg.lu_factor` is only for square matrices. My use case is precisely tall skinny matrices.

**Comment by RikVoorhaar** [comment]
Also, it seems `dgetrf` is faster than `scipy.linalg.lu`, especially for tall matrices. For square matrices (in simple benchmarks) it is a bit faster, but not by much.

**Comment by ilayn** [comment]
That is a bug if getrf only works with square arrays and we have to fix it. dgetrs should require squareness not the trf

**Comment by RikVoorhaar** [comment]
Right, `lu_factor` calls `getrf`, but it explicitly checks for a square matrix,
I would suggest removing the the check, and updating the documentation. It should also be a little clearer in the documentation what the difference is between `lu_factor` and `lu`. 
For `lu_factor` one can say something along the likes of
"Unlike `scipy.linalg.lu`, this function returns L and U stored in the same matrix LU, with U the upper triangular part, and L the lower triangular part with ones on the diagonal. Furthermore the permutation matrix P is returned as a 1D integer array instead of a  dense matrix"

Shall I make a PR?

**Comment by ilayn** [comment]
That would much be appreciated if you can indeed. Thanks @RikVoorhaar

**Comment by RikVoorhaar** [comment]
As mentioned in my original post
> It seems that `linalg.lu` uses `linalg/src/lu.f` rather than the LAPACK implementation. Is this faster than the LAPACK implementation?

It seems that it is in fact slower than the LAPACK implementation in my own benchmarks. For square matrices the methods are comparable with the Fortran `lu.f` being slightly faster, but for matrices of shape (M,N) with M>>N the LAPACK implementation is faster. 
In extreme cases of a (10,10000) matrix the difference between the two methods is a factor 500.

I can past a more detailed benchmark, (is there a specific format I should adhere to?).

Based on detailed benchmarks we can make `scipy.linalg.lu` call either the Fortran implementation or call LAPACK depending on the shape of the matrix.

**Comment by ilayn** [comment]
Wow I've been looking at this codebase for quite some time now and still get surprises. I just realized that this `lu.f` file is still in use. This probably predates the LAPACK wrappers and hence the custom roll of 4 flavors. As you said we should definitely switch back to regular wrappers unconditionally because there is no need for it. The overhead probably would be negligible depending on the matrix size

**Comment by RikVoorhaar** [comment]
Shall I make a PR for a version using a LAPACK wrapper?
