### ISSUE TITLE
ImportError: cannot import name '_valarray' from 'scipy._lib._util'

### ISSUE THREAD

**Issue by pipthagoras** [scipy/scipy#14253]
I am currently using scipy version 1.6.3 and I am getting the following error when trying to run my code:

ImportError: cannot import name '_valarray' from 'scipy._lib._util'

I can see that _valarray was removed in the feature "MAINT: Remove _util._valarray #12682", so it is perhaps unsurprising that it cannot be found. I am surprised that it is being looked for in the first place.

Could this be a bug? Is there anything I can do to deal with this issue?

**Comment by ev-br** [comment]
Please add a reproducible example which triggers the error.
