### ISSUE TITLE
Broken reference in docstring of scipy.stats.power_divergence

### ISSUE THREAD

**Issue by FirefoxMetzger** [scipy/scipy#14277]
Quick Link: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.power_divergence.html#scipy.stats.power_divergence

The parameter `lambda_` creates a reference to a paper in its documentation, but this reference is not rendered in the docs. Instead, a mangled string is shown. This happens twice for different references; however, the raw docstring looks good.

Not sure if this is caused by something in scipy, if it could be a bug in sphinx, or something else entirely. If anybody knows the cause, I can submit a PR once a solution has been identified.

**Comment by tupui** [comment]
Thanks indeed. This is because the block is written as a code block. Would you like to make a PR to fix it?

**Comment by FirefoxMetzger** [comment]
Sure. Is there a way to create references in a code block? If not, what would be the preferred way to fix it?

**Comment by tupui** [comment]
> Sure. Is there a way to create references in a code block? If not, what would be the preferred way to fix it?

I found this https://stackoverflow.com/questions/44527391/how-to-include-an-internal-reference-in-a-code-block but recently when adding such things we just did not use code blocks. See for instance description of parameters from optimization or stats module.

**Comment by FirefoxMetzger** [comment]
Done. Let's see if it renders properly. I briefly tried building the docs locally, but apparently, that is not so trivial on a Windows machine since it involves building scipy from source (if I understand correctly).

@tupui Are you able to review?

**Comment by tupui** [comment]
I will try to get some time for it. Thanks 😊
