### ISSUE TITLE
rv_histogram misrepresenting lowest bin when computing cdf?

### ISSUE THREAD

**Issue by ml-l** [scipy/scipy#14288]
Hi. I've noticed that for a histogram with support [a,b] that computing the cdf(a) via rv_histogram (once fitted) will always result in 0 no matter how how weight may be allocated to that initial bin.

From plotting the cdf and looking into the source code, the problem seems to be in the [`__init__`](https://github.com/scipy/scipy/blob/v1.7.0/scipy/stats/_continuous_distns.py#L9267-L9296) in setting up the capability for extrapolating cdf values lower than the support lower bound (namely the logic behind line 9292).

From the cdf plot it seems to be treating bins like `(c,d]` intervals rather than how numpy.histogram treats its outputs which seems to be `[c,d)` intervals (see notes section of https://numpy.org/doc/stable/reference/generated/numpy.histogram.html) contrary to the provided example in the documentation. Another point of concern when it comes to cdf computation is whether using `(c,d]` interval logic breaks the right-continuous property of cumulative distribution functions.

#### Reproducing code example:

```Python
import numpy as np
import scipy.stats as stats
import matplotlib
import matplotlib.pyplot as plt
hist_counts = [10,1,2,3,4]
hist_bins = [0,1,2,3,4,5]
hist = stats.rv_histogram((hist_counts, hist_bins))
print(hist.cdf(0)) # returns 0 despite half the probability density is in the 1st bin
# plotting cdf to further show the issue
x = np.linspace(-1,6,100)
cdf = hist.cdf(x)
plt.plot(x,cdf)
plt.show()
```
We can see from the plot that the 0.5 that was supposed to be for `hist.cdf(0)` had been shifted to `hist.cdf(1)`.

#### Scipy/Numpy/Python version information:

1.7.0 1.21.0 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
I think there is a misunderstanding about how `rv_histogram` is supposed to work. It is not supposed to behave like a discrete distribution with a probability mass at the left end of the support. The histogram is used to determine the probability mass that would be _spread out_ over the first bin. In the end, it behaves like a continuous distribution, so the CDF should be exactly 0 at the left end of the support.

Here's an example that shows how an `rv_histogram` generated from random variates behaves like the `rv_continuous` used to generate the random variates.

```python3
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

a, b = 0, 1
x = np.linspace(a, b, 100)
dist = stats.uniform(loc=a, scale=b-a)

# reference cdf
cdf_ref = dist.cdf(x)

# rv_histogram cdf
sample = dist.rvs(size=250)
hist = np.histogram(sample, bins=np.linspace(a, b, 20))
dist_hist = stats.rv_histogram(hist)
cdf_hist = dist_hist.cdf(x)

# compare
plt.plot(x, cdf_ref, x, cdf_hist)
plt.legend(('Reference CDF', 'Histogram CDF'))
```
![image](https://user-images.githubusercontent.com/6570539/159219550-48e1ec80-1dc3-4818-bc17-ba4c9f3fb156.png)

Closing, but please re-open if I've missed something here.
