### ISSUE TITLE
Scipy-1.7.0 build fails in AIX

### ISSUE THREAD

**Issue by ayappanec** [scipy/scipy#14289]
pip install scipy fails with the below error in AIX. The earlier version 1.6.3 had no problem in AIX.

    setup.py:492: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-1jt97u3e'), proceeding with generating Cython sources and expanding templates
      ' '.join(sys.argv[1:])))
    Running from SciPy source directory.
    Traceback (most recent call last):
      File "/opt/freeware/lib64/python3.7/configparser.py", line 788, in get
        value = d[option]
      File "/opt/freeware/lib64/python3.7/collections/__init__.py", line 916, in __getitem__
        return self.__missing__(key)            # support subclasses that define __missing__
      File "/opt/freeware/lib64/python3.7/collections/__init__.py", line 908, in __missing__
        raise KeyError(key)
    KeyError: 'defines'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/freeware/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
        main()
      File "/opt/freeware/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/opt/freeware/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-qym5xzvr/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-qym5xzvr/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 259, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/tmp/pip-build-env-qym5xzvr/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 629, in <module>
        setup_package()
      File "setup.py", line 625, in setup_package
        setup(**metadata)
      File "/tmp/pip-build-env-qym5xzvr/overlay/lib64/python3.7/site-packages/numpy/distutils/core.py", line 137, in setup
        config = configuration()
      File "setup.py", line 536, in configuration
        config.add_subpackage('scipy')
      File "/tmp/pip-build-env-qym5xzvr/overlay/lib64/python3.7/site-packages/numpy/distutils/misc_util.py", line 1036, in add_subpackage
        caller_level = 2)
      File "/tmp/pip-build-env-qym5xzvr/overlay/lib64/python3.7/site-packages/numpy/distutils/misc_util.py", line 1005, in get_subpackage
        caller_level = caller_level + 1)
      File "/tmp/pip-build-env-qym5xzvr/overlay/lib64/python3.7/site-packages/numpy/distutils/misc_util.py", line 942, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/setup.py", line 12, in configuration
        config.add_subpackage('interpolate')
      File "/tmp/pip-build-env-qym5xzvr/overlay/lib64/python3.7/site-packages/numpy/distutils/misc_util.py", line 1036, in add_subpackage
        caller_level = 2)
      File "/tmp/pip-build-env-qym5xzvr/overlay/lib64/python3.7/site-packages/numpy/distutils/misc_util.py", line 1005, in get_subpackage
        caller_level = caller_level + 1)
      File "/tmp/pip-build-env-qym5xzvr/overlay/lib64/python3.7/site-packages/numpy/distutils/misc_util.py", line 942, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/interpolate/setup.py", line 62, in configuration
        config=['compiler.blas=none']
      File "/tmp/pip-build-env-qym5xzvr/overlay/lib/python3.7/site-packages/pythran/dist.py", line 145, in __init__
        cfg_ext = cfg.make_extension(python=True, **kwargs)
      File "/tmp/pip-build-env-qym5xzvr/overlay/lib/python3.7/site-packages/pythran/config.py", line 139, in make_extension
        cfg.get('compiler', 'defines').split()],
      File "/opt/freeware/lib64/python3.7/configparser.py", line 791, in get
        raise NoOptionError(option, section)
    configparser.NoOptionError: No option 'defines' in section: 'compiler'
    ----------------------------------------

Any idea/hint about this error ?

**Comment by tupui** [comment]
Can it be related to Pythran @serge-sans-paille??

**Comment by serge-sans-paille** [comment]
It certainly is! Looks like we need to ship a configuration file for aix, which we don't.

@ayappanec  what's the output of `sys.platform` on AIX?

**Comment by ayappanec** [comment]
It is "aix6" or "aix7" based on the AIX OS level where python is built. We can safely assume it contains "aix".

**Comment by rgommers** [comment]
Can you try `export SCIPY_USE_PYTHRAN=0` and see if that fixes things @ayappanec? We haven't tested the AIX build after the recent build system changes for Pythran, so it failing is not completely surprising.

**Comment by ayappanec** [comment]
@rgommers It worked , exporting SCIPY_USE_PYTHRAN=0

**Comment by rgommers** [comment]
Great, I think that's fine for now on AIX. For the 1.8.0 release I expect we have to do some real work on AIX, to make both Pythran and Meson work. So might as well take those two things together and not worry about it too much right now.

**Comment by ayappanec** [comment]
> It certainly is! Looks like we need to ship a configuration file for aix, which we don't.
> 
> @ayappanec what's the output of `sys.platform` on AIX?

Any update on having a configuration file for AIX in pythran ?

**Comment by serge-sans-paille** [comment]
@ayappanec can you try that branch? https://github.com/serge-sans-paille/pythran/pull/1824

**Comment by ayappanec** [comment]
> @ayappanec can you try that branch? [serge-sans-paille/pythran#1824](https://github.com/serge-sans-paille/pythran/pull/1824)

Tried it . Now the script build fails with the below error.

 C compiler: g++ -maix64 -fPIC -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -I/usr/include -I/opt/freeware/include -I/opt/freeware/include/ncurses -DAIX_GENUINE_CPLUSCPLUS -D_LINUX_SOURCE_COMPAT -Wl,-brtl -O2 -fPIC -I/usr/include -I/opt/freeware/include -I/opt/freeware/include/ncurses -DAIX_GENUINE_CPLUSCPLUS -D_LINUX_SOURCE_COMPAT -Wl,-brtl -O2 -fPIC
  
  compile options: '-DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DPYTHRAN_BLAS_NONE -I/opt/freeware/lib/python3.7/site-packages/pythran-0.9.12.dev0-py3.7.egg/pythran -I/opt/freeware/lib64/python3.7/site-packages/numpy/core/include -I/opt/freeware/lib64/python3.7/site-packages/numpy/core/include -Ibuild/src.aix-7.1-3.7/numpy/distutils/include -I/opt/freeware/include/python3.7m -c'
  extra options: '-std=c++11'
  g++: scipy/interpolate/_rbfinterp_pythran.cpp
  In file included from /opt/freeware/lib/python3.7/site-packages/pythran-0.9.12.dev0-py3.7.egg/pythran/xsimd/types/xsimd_traits.hpp:17,
                   from /opt/freeware/lib/python3.7/site-packages/pythran-0.9.12.dev0-py3.7.egg/pythran/xsimd/xsimd.hpp:16,
                   from /opt/freeware/lib/python3.7/site-packages/pythran-0.9.12.dev0-py3.7.egg/pythran/pythonic/include/numpy/exp.hpp:8,
                   from scipy/interpolate/_rbfinterp_pythran.cpp:26:
  /opt/freeware/lib/python3.7/site-packages/pythran-0.9.12.dev0-py3.7.egg/pythran/xsimd/types/xsimd_types_include.hpp:83:7: warning: #warning "No SIMD instructions set detected, please enable SIMD instructions or activate the fallback mode. (e.g. for x86 -march=native or for ARM -mfpu=neon)" [-Wcpp]
        #warning "No SIMD instructions set detected, please enable SIMD instructions or activate the fallback mode. (e.g. for x86 -march=native or for ARM -mfpu=neon)"
         ^~~~~~~
  In file included from /opt/freeware/lib/python3.7/site-packages/pythran-0.9.12.dev0-py3.7.egg/pythran/xsimd/math/xsimd_math.hpp:23,
                   from /opt/freeware/lib/python3.7/site-packages/pythran-0.9.12.dev0-py3.7.egg/pythran/xsimd/xsimd.hpp:17,
                   from /opt/freeware/lib/python3.7/site-packages/pythran-0.9.12.dev0-py3.7.egg/pythran/pythonic/include/numpy/exp.hpp:8,
                   from scipy/interpolate/_rbfinterp_pythran.cpp:26:
  /opt/freeware/lib/python3.7/site-packages/pythran-0.9.12.dev0-py3.7.egg/pythran/xsimd/math/xsimd_scalar.hpp: In function 'void xsimd::sincos(float, float&, float&)':
  /opt/freeware/lib/python3.7/site-packages/pythran-0.9.12.dev0-py3.7.egg/pythran/xsimd/math/xsimd_scalar.hpp:362:11: error: '::sincosf' has not been declared
           ::sincosf(val, &s, &c);
             ^~~~~~~
  /opt/freeware/lib/python3.7/site-packages/pythran-0.9.12.dev0-py3.7.egg/pythran/xsimd/math/xsimd_scalar.hpp:362:11: note: suggested alternative: 'sincos'
           ::sincosf(val, &s, &c);
             ^~~~~~~
             sincos
  /opt/freeware/lib/python3.7/site-packages/pythran-0.9.12.dev0-py3.7.egg/pythran/xsimd/math/xsimd_scalar.hpp: In function 'void xsimd::sincos(double, double&, double&)':
  /opt/freeware/lib/python3.7/site-packages/pythran-0.9.12.dev0-py3.7.egg/pythran/xsimd/math/xsimd_scalar.hpp:374:11: error: '::sincos' has not been declared
           ::sincos(val, &s, &c);
             ^~~~~~
  /opt/freeware/lib/python3.7/site-packages/pythran-0.9.12.dev0-py3.7.egg/pythran/xsimd/math/xsimd_scalar.hpp:374:11: note: suggested alternative:
  /opt/freeware/lib/python3.7/site-packages/pythran-0.9.12.dev0-py3.7.egg/pythran/xsimd/math/xsimd_scalar.hpp:369:17: note:   'xsimd::sincos'
       inline void sincos(double val, double&s, double& c)
                   ^~~~~~
  /opt/freeware/lib64/python3.7/site-packages/numpy/distutils/system_info.py:933: UserWarning: Specified path /usr/local/include/python3.7m is invalid.
    return self.get_paths(self.section, key)
  
  ########### EXT COMPILER OPTIMIZATION ###########
  Platform      :
    Architecture: unsupported
    Compiler    : gcc
  
  CPU baseline  :
    Requested   : optimization disabled
    Enabled     : none
    Flags       : none
    Extra checks: none
    Requested   : optimization disabled
  
  CPU dispatch  :
    Enabled     : none
    Generated   : none
  CCompilerOpt.cache_flush[804] : write cache to path -> /tmp/pip-req-build-_jmugyn8/build/temp.aix-7.1-3.7/ccompiler_opt_cache_ext.py
  
  ########### CLIB COMPILER OPTIMIZATION ###########
  Platform      :
    Architecture: unsupported
    Compiler    : gcc
  
  CPU baseline  :
    Requested   : optimization disabled
    Enabled     : none
    Flags       : none
    Extra checks: none
    Requested   : optimization disabled
  
  CPU dispatch  :
    Enabled     : none
    Generated   : none
  CCompilerOpt.cache_flush[804] : write cache to path -> /tmp/pip-req-build-_jmugyn8/build/temp.aix-7.1-3.7/ccompiler_opt_cache_clib.py
  error: Command "g++ -maix64 -fPIC -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -I/usr/include -I/opt/freeware/include -I/opt/freeware/include/ncurses -DAIX_GENUINE_CPLUSCPLUS -D_LINUX_SOURCE_COMPAT -Wl,-brtl -O2 -fPIC -I/usr/include -I/opt/freeware/include -I/opt/freeware/include/ncurses -DAIX_GENUINE_CPLUSCPLUS -D_LINUX_SOURCE_COMPAT -Wl,-brtl -O2 -fPIC -DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DPYTHRAN_BLAS_NONE -I/opt/freeware/lib/python3.7/site-packages/pythran-0.9.12.dev0-py3.7.egg/pythran -I/opt/freeware/lib64/python3.7/site-packages/numpy/core/include -I/opt/freeware/lib64/python3.7/site-packages/numpy/core/include -Ibuild/src.aix-7.1-3.7/numpy/distutils/include -I/opt/freeware/include/python3.7m -c scipy/interpolate/_rbfinterp_pythran.cpp -o build/temp.aix-7.1-3.7/scipy/interpolate/_rbfinterp_pythran.o -MMD -MF build/temp.aix-7.1-3.7/scipy/interpolate/_rbfinterp_pythran.o.d -std=c++11" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for scipy

**Comment by serge-sans-paille** [comment]
Thanks for the feedback. Can you give it a try with https://github.com/serge-sans-paille/pythran/pull/1829 ?

**Comment by serge-sans-paille** [comment]
@ayappanec did you have the opportunity to test the above PR?

**Comment by ayappanec** [comment]
Yes, now i am able to pip install scipy 1.7.0 with the above pythran changes.

**Comment by serge-sans-paille** [comment]
Thanks! I'll merge the PR and it will be in next Pythran release, cc @rgommers

**Comment by rgommers** [comment]
Awesome, thanks @serge-sans-paille and @ayappanec! Let's close this issue then.
