### ISSUE TITLE
Order of indices in n-dimensional fourier transform (fftn)

### ISSUE THREAD

**Issue by adch99** [scipy/scipy#14292]
My issue is about the order of the indices in the output of `scipy.fft.fftn`. Concretely, `fftn( f(t1, t2, t3) )` seems to return `f_tilde(m3, m1, m2)`, at least when used with meshgrid.

#### Reproducing code example:

```python
import numpy as np
import scipy.fft as fft
from scipy.integrate import nquad

ALPHA = 0.5
BETA = 0.2

def f(t1, t2, t3):
    kick = -np.cos(t1) * (1 + ALPHA * np.cos(t2)) * (1 + BETA * np.cos(t3))
    return np.cos(kick) + 1j * np.sin(kick)

def g_real(t1, t2, t3, m1, m2, m3):
    kick = -np.cos(t1) * (1 + ALPHA * np.cos(t2)) * (1 + BETA * np.cos(t3))
    kernel = -m1*t1 - m2*t2 - m3*t3
    return np.cos(kick + kernel)

def g_imag(t1, t2, t3, m1, m2, m3):
    kick = -np.cos(t1) * (1 + ALPHA * np.cos(t2)) * ( 1 + BETA * np.cos(t3))
    kernel = -m1*t1 - m2*t2 - m3*t3
    return np.sin(kick + kernel)

def findIntegral(m1, m2, m3):
    params = (m1, m2, m3)
    ranges = [(0, 2*np.pi), (0, 2*np.pi), (0, 2*np.pi)]
    result_real, abserr_real = nquad(g_real, ranges, args=params)
    result_imag, abserr_imag = nquad(g_imag, ranges, args=params)
    result = (result_real + 1j * result_imag) / (2*np.pi)**3
    abserr = (abserr_real + 1j * abserr_imag) / (2*np.pi)**3
    return result, abserr

def getFourier():
    theta = np.arange(64) * 2 * np.pi / 64
    t1, t2, t3 = np.meshgrid(theta, theta, theta)
    x = f(t1, t2, t3)
    y = fft.fftshift(fft.fftn(x, norm="forward"))
    return y

def test(m1, m2, m3):
    fourier_coeffs = getFourier().T
    fourier = fourier_coeffs[m1+32, m2+32, m3+32]
    integral, abserr = findIntegral(m1, m2, m3)
    diff = np.abs(fourier - integral)
    print(f"From Fourier: {fourier}")
    print(f"From Integral: {integral}")
    print("Difference:", np.abs(fourier - integral))

if __name__ == "__main__":
    test(2, 1, -1)
```

#### Returned Output:
```
$ python .\fourier_test.py
From Fourier: (-6.074558508975231e-20+0.0010767153985724652j)
From Integral: (-0.007913825746533081-6.242934988775879e-18j)
Difference: 0.00798673612910887
```

However, if I we change

```
fourier = fourier_coeffs[m1+32, m2+32, m3+32]
```

to 

```
fourier = fourier_coeffs[m3+32, m1+32, m2+32]
```

Then things start to work:

```
$ python .\fourier_test.py
From Fourier: (-0.007913825746533086+1.8131470478555937e-18j)
From Integral: (-0.007913825746533081-6.242934988775879e-18j)
Difference: 9.59082100885434e-18
```

I have used the function `f(t1, t2, t3) = exp(-1j * cos(t1) * (1 + ALPHA * cos(t2)) * (1 + BETA * cos(t3))  )` because it is
asymmetric wrt to the 3 variables `t1`, `t2`, `t3` (and also because that is where I encountered this issue first). This behaviour may be due to the fact that the example in the docs uses `mgrid` and not `meshgrid`. But if this is the intended behaviour then I feel, it should at least be mentioned as a comment in the docs.

#### Scipy/Numpy/Python version information:
```
scipy version: 1.6.2
numpy version: 1.20.1
sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)
```

**Comment by grlee77** [comment]
I think the issue is just that you need to specify `indexing='ij'` in the call to `meshgrid`
```Python
t1, t2, t3 = np.meshgrid(theta, theta, theta, indexing='ij')
```

If I make that change and then remove the transpose in the first line of `test` it works for me. Specifically
```Python
def getFourier():
    theta = np.arange(64) * 2 * np.pi / 64
    t1, t2, t3 = np.meshgrid(theta, theta, theta, meshgrid='ij')
    x = f(t1, t2, t3)
    y = fft.fftshift(fft.fftn(x, norm="forward"))
    return y

def test(m1, m2, m3):
    fourier_coeffs = getFourier()
    fourier = fourier_coeffs[m1+32, m2+32, m3+32]
    integral, abserr = findIntegral(m1, m2, m3)
    diff = np.abs(fourier - integral)
    print(f"From Fourier: {fourier}")
    print(f"From Integral: {integral}")
    print("Difference:", np.abs(fourier - integral))
```

**Comment by grlee77** [comment]
It is easier to see the difference if you set axes of different sizes, as in:
```
In [14]: np.mgrid[:4, :5, :6].shape
Out[14]: (3, 4, 5, 6)

In [15]: np.meshgrid(np.arange(4), np.arange(5), np.arange(6), indexing='ij')[0].shape
Out[15]: (4, 5, 6)

In [15]: np.meshgrid(np.arange(4), np.arange(5), np.arange(6))[0].shape
Out[15]: (5, 4, 6)
```

Note that the default meshgrid setting has the first two axes swapped!

**Comment by adch99** [comment]
@grlee77 Thank you for that explanation! I knew the issue had something to do with `np.meshgrid` but didn't know exactly what. However, the second example in the scipy docs for [fftn](https://docs.scipy.org/doc/scipy/reference/generated/scipy.fft.fftn.html) does not use `indexing = "ij"`:

```python
>>> import matplotlib.pyplot as plt
>>> rng = np.random.default_rng()
>>> [X, Y] = np.meshgrid(2 * np.pi * np.arange(200) / 12,
                     2 * np.pi * np.arange(200) / 34)
>>> S = np.sin(X) + np.cos(Y) + rng.uniform(0, 1, X.shape)
>>> FS = scipy.fft.fftn(S)
>>> plt.imshow(np.log(np.abs(scipy.fft.fftshift(FS))**2))
<matplotlib.image.AxesImage object at 0x...>
>>> plt.show()
```

I would request that this example to be changed to reflect the fact that we require the `ij` matrix indexing when using `fftn` since this is rather unclear for a first time user reading the docs.

**Comment by peterbell10** [comment]
>I would request that this example to be changed to reflect the fact that we require the ij matrix indexing when using fftn since this is rather unclear for a first time user reading the docs.

The way it's written is correct for using with `imshow`, i.e. `X` varies in the left-right axis and `Y` varies in up-down. I'm guessing matlab is to blame for the indexing being `im[Y, X]` because it's the order you would write out a matrix?
