### ISSUE TITLE
KDTree returns indices with float dtype; was (and probably should be) int

### ISSUE THREAD

**Issue by gerritholl** [scipy/scipy#14296]
Since SciPy 1.6, the `scipy.spatial.KDTree` `data` attribute has dtype `float64`.  Until SciPy and including 1.5, it had dtype `int64`.  Considering that the algorithm returns indices, it would seem that the dtype should be int, not float.

I can't find this specific behaviour change in the [SciPy 1.6.0 release notes](https://docs.scipy.org/doc/scipy/reference/release.1.6.0.html), but it does note that there was an implementation change in kdtree.  I expect that change has introduced this change in behaviour.

#### Reproducing code example:

```
from scipy import spatial
print(spatial.KDTree([(0, 0)]).data.dtype)
```

#### Expected result, and result with SciPy 1.5.3:

```
int64
```

#### Actual result with SciPy 1.6.0 or newer:

```
float64
```

#### SciPy/NumPy/Python version information:

Tested with the latest versions available on conda-forge: Python 3.9.5, NumPy 1.21.0, SciPy 1.6.3.

**Comment by tylerjereddy** [comment]
It looks to me like the `data` attribute should be the input generators (points), which I'd expect to be `float64`:

```python
In [5]: scipy.spatial.KDTree([(0.3, 1.5), (1.7, 3.6)]).data
Out[5]:
array([[0.3, 1.5],
       [1.7, 3.6]])

In [6]: scipy.__version__
Out[6]: '1.8.0.dev0+1287.bcea20c'
```

Looking at the current documentation, there is also an explicit mention of an array of doubles:

![image](https://user-images.githubusercontent.com/7903078/123561524-17270000-d766-11eb-99ca-7fa0fe4f82c3.png)

Finally, I can't even reproduce the alleged change in behavior with SciPy `1.5.0`--those clearly are not integers, even with the old Python backed for KDTree:

```python
In [3]:  scipy.spatial.KDTree([(0.3, 1.5), (1.7, 3.6)]).data
Out[3]:
array([[0.3, 1.5],
       [1.7, 3.6]])

In [4]: scipy.__version__
Out[4]: '1.5.0'
```

**Comment by gerritholl** [comment]
Ah, OK.  The change in behaviour probably applies if the user inputs integers.  Sorry, I hadn't noticed that in the documentation.  Then it's not a bug in current scipy.

**Comment by peterbell10** [comment]
Actually this issue is correct and the behaviour did change. Note that `np.asarray([0, 0])` creates an array of ints, but `np.asarray([(0.3, 1.5), (1.7, 3.6)])` creates an array of floats. That's the difference between the examples.

`KDTree` used to allow any dtype and that was lost in the merge with `cKDTree`, which stores everything as double. That really should have been mentioned in the release notes, I just don't think int arrays was ever brought up in discussion. Complex data was brought up, but `KDTree` was actually wrong to allow complex types in the first place.

**Comment by tylerjereddy** [comment]
I think that's basically what we deduced

**Comment by tylerjereddy** [comment]
> Actually this issue is correct 

The issue says:

> Considering that the algorithm returns indices, it would seem that the dtype should be int, not float.

That's the part I was trying to indicate was not correct--they are not indices, they are the input generators/points. If they were indices, then the original contention that these are indices and should be ints would be something to take more seriously.

But that would be an extremely serious bug, and the test suite would have caught that.

**Comment by peterbell10** [comment]
Ah, I see. "the algorithm" was so vague I ignored that part of the sentence.
