### ISSUE TITLE
Lost triangles in 2D Voronoi diagram

### ISSUE THREAD

**Issue by xk1009111** [scipy/scipy#14307]
I am trying to analysize the geometrical features of triangles in 2D Voronoi diagram generated by SciPy. Although triangles can be generated , they are not recognized as polygons. In addition, the vertex coordinates, edge number, and neighbor edges of the triangle can not be extracted. Do you know how to get the geometrical information of triangles?

**Comment by rkern** [comment]
The [Voronoi diagram](https://en.wikipedia.org/wiki/Voronoi_diagram) of a set of points is not composed of triangles. Its dual, the [Delaunay triangulation](https://en.wikipedia.org/wiki/Delaunay_triangulation), is. `scipy` has routines for both, but to help you do what you want, you'll need to clarify more precisely what it is that you want to do. Can you show us what you've tried so far?

**Comment by xk1009111** [comment]
Thank you! In 2D Voronoi diagram, each seed point corresponds to a polygonal region, and each polygon contains at least three edges. I noticed that the triangle can be generated by SciPy (see attached image), but its information can not be extracted. 

![triangle](https://user-images.githubusercontent.com/86545328/123534313-ebe4e680-d74e-11eb-87bf-d903c22a94bd.png)

**Comment by rkern** [comment]
The `regions` attribute has the lists of points for each of these Voronoi cells. They are indices into the `vertices` attribute to get the actual coordinates. The documentation describes this more fully.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Voronoi.html

**Comment by rkern** [comment]
I'm closing this because there's no action that we need to take. If you have more questions, you can still ask them, or join us on the [mailing list](http://www.scipy.org/scipylib/mailing-lists.html) (preferred for usage questions).
