### ISSUE TITLE
Feature Request: Full functionality of optimize.least_squares for optimize.curve_fit

### ISSUE THREAD

**Issue by Patschke** [scipy/scipy#14337]
**Is your feature request related to a problem? Please describe.**
I would like to use `optimize.curve_fit()` together with the `loss` keyword arg while using `lm` as fit method. 

Currently `curve_fit` uses either `optimize.least_squares` or `optimize.leastsq`, depeding on the specified `method` (the later presumably only for backwards compatibility). `loss` is only a valid keyword arg for `least_squares`, not for `leastsq` - therefore `loss` can't be used as argument for `curve_fit` with `method='lm'` (since `leastsq` will be used with that method). However, `least_squares` is also able to handle `lm` as method, and would simply have more/better/newer options. 

**Describe the solution you'd like**
Add a `method` option to `curve_fit` (e.g. `'least_squares_lm'`), that will invoke `least_squares` with `method='lm'`. This will not break backwards-compatibility, but allows to use all features of `least_squares` within `curve_fit`, instead of restricting those features to methods other than `lm`.

**Describe alternatives you've considered**
As far as I know, directly using `least_squares` (instead of `curve_fit`) is currently the only option, which is basically re-implementing `curve_fit`. This works, but is of course not desirable. 

**Additional context (e.g. screenshots)**
```python
curve_fit(fit_func, x_data, y_data, loss='cauchy')
# TypeError: leastsq() got an unexpected keyword argument 'loss'.

curve_fit(fit_func, x_data, y_data, method='trf', loss='cauchy')
# works, by invoking least_squares(method='trf', loss='cauchy',...)

curve_fit(fit_func, x_data, y_data, method='lm', loss='cauchy')
# TypeError: leastsq() got an unexpected keyword argument 'loss'.

# Proposed solution:
curve_fit(fit_func, x_data, y_data, method='least_squares_lm', loss='cauchy')
# works, by invoking least_squares(method='lm', loss='cauchy',...)
```

**Comment by Patschke** [comment]
I just noticed 
> Method ‘lm’ supports only ‘linear’ loss.

In the description of `scipy.optimize.least_squares`. So my initial use-case is not going to be available with that proposal - However, I still believe, that having the syntax of 'least_squares' available for all methods is beneficial.

**Comment by TimZaragori** [comment]
Similarly, `optimize.curve_fit` doesn't accept a callable that return a sparse matrix for `jac`. It is specified in the documentation that the callable should return a dense array_like structure but no error is raised when it returns a sparse matrix. The sparse matrix is automatically converted to dense numpy array in the `_wrap_jac` function which can cause error due to lack of memory for large systems. I understood that sparse matrix are not accepted for `lm` but it would be nice to harmonize `optimize.curve_fit` functionnalities  with `scipy.optimize.least_squares` ones

**Comment by AtsushiSakai** [comment]
@Patschke @TimZaragori Thank you for the great request. I created PR #18198. Let's 🤞.

**Comment by dschmitz89** [comment]
I have trouble understanding what how this can improve the functionality of Levenberg Marquardt optimization in `curve_fit`. In `least_square` `method=lm` calls MINPACK which does not support sparse jacobians. See the docs [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.least_squares.html):


> ‘lm’ : Levenberg-Marquardt algorithm as implemented in MINPACK. Doesn’t handle bounds and sparse Jacobians. Usually the most efficient method for small unconstrained problems.

In my understanding all the advanced features of `least_squares` such as complex loss function and sparsity handling are only available via the Python solvers, not via MINPACK.
