### ISSUE TITLE
Extract spline coefficient from splprep: tck

### ISSUE THREAD

**Issue by shmulike** [scipy/scipy#14348]
I am using python3, Scipy

I have a 3d points (x,y,z] From them I make s a spline using scipy.interpolate.splprep dunction

```
x_points = np.linspace(0, 2*np.pi, 10)
y_points = np.sin(x_points)
z_points = np.cos(x_points)
path = np.vstack([x_points, y_points, z_points])
tck, u = sc.splprep(path, k=3, s=0)
```

I wish to get the coefficients of the spline[i].
For example, the first spline:
sp_y0 = ay0 + by0(x-x4) + cy0(x-x4)^2 + dy0(x-x4)^3
sp_z0 = az0 + bz0(x-x4) + cz0(x-x4)^2 + dz0(x-x4)^3
to the second spline: [ay1, by1, cy1, dy1], [az1, bz1, cz1, dz1]

I used PPoly.from_spline
```
t, c, k = tck
cc = np.asarray(c)    # cc.shape is (3, 10) now
spl0 = sc.PPoly.from_spline((t, cc.T[0], k))
```
the coefficient suppose to be in `spl0.c`
but I'm expecting to get 8 coefficients for each spline, 4 for the sp_y, and 4 for sp_z

And please can you explain the parameter tck: t?
why are the first falues of the vector of knots are the same.
for the example above: 

> t=
> array([0.        , 0.        , 0.        , 0.        , 0.21757366,
>        0.34535401, 0.45402382, 0.54597618, 0.65464599, 0.78242634,
>        1.        , 1.        , 1.        , 1.        ])

Thanks

**Comment by ev-br** [comment]
cross-ref: https://stackoverflow.com/questions/68194269/python-extract-spline-coefficient

**Comment by shmulike** [comment]
I read the documentation but there is still something odd with the array size and I still can't find the coefficients of the spline of s_y(x) and s_z(x) functions.
is there an example or other documentation for the use of
`PPoly.from_spline(tck)`
when tck came from `splprep`
