### ISSUE TITLE
scipy.stats.rv_continuous.fit returns wrapper instead of fit method for some distributions

### ISSUE THREAD

**Issue by georgebv** [scipy/scipy#14346]
My issue is about `scipy.stats.rv_continuous` objects not returning the same type of object for the `fit` method for different distributions.

`scipy.stats.genextreme.fit` gives `<bound method rv_continuous.fit of <scipy.stats._continuous_distns.genextreme_gen object at 0x7f66083e19a0>>`
`scipy.stats.gumbel_r.fit` gives `<bound method _call_super_mom.<locals>.wrapper of <scipy.stats._continuous_distns.gumbel_r_gen object at 0x7f66083fb610>>`

This has caused issues when I pass `fit` method of one of these distributions to a function called within multiprocessing pool. genextreme works fine, but gumbel_r (and other distributions like it returning wrapper instead of fit function) now result in infinite loop (not getting an error). This change wasn't documented in the release notes.

#### Reproducing code example:

```python
import multiprocessing
import scipy.stats

def func(fit_method):
    fit_method([1, 2, 3])

with multiprocessing.Pool(2) as pool:
    pool.map(func, [scipy.stats.genextreme.fit])

with multiprocessing.Pool(2) as pool:
    pool.map(func, [scipy.stats.gumbel_r.fit])
```

#### Error message:

Same for each process in the pool:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/local/lib/python3.9/multiprocessing/queues.py", line 368, in get
    return _ForkingPickler.loads(res)
AttributeError: 'gumbel_r_gen' object has no attribute 'wrapper'
```

#### Scipy/Numpy/Python version information:

numpy                      1.21.0
scipy                      1.7.0
python 3.9.6

**Comment by mdhaber** [comment]
@georgebv I just started experimenting with `multiprocessing` this past week. It wasn't documented in the release notes because it was seen as an implementation detail, but now I see that it can change the way users are able to use the methods. Do you know of anything we can do to make wrapped functions pickleable?

**Comment by rkern** [comment]
Just putting the snippet into each of the `fit()` methods would probably not be too onerous, given the technical constraint.

```python
        method = kwds.get('method', 'mle').lower()
        if method == 'mm':
            return super().fit(data, *args, **kwds)
```

**Comment by georgebv** [comment]
Thank you @rkern , this indeed appears to be the thing needed. I also reviewed the code too and wanted to add a bit of context.

The issue is with the wrapper:

https://github.com/scipy/scipy/blob/5acc23400ce53ab69e97e44e4faae7f3fb039cae/scipy/stats/_continuous_distns.py#L54-L63

which is used as (multiple spots, this is example):

https://github.com/scipy/scipy/blob/5acc23400ce53ab69e97e44e4faae7f3fb039cae/scipy/stats/_continuous_distns.py#L3276-L3309

**Comment by georgebv** [comment]
I also updated my own package where I was having this issue by doing the following:

```python
import multiprocessing
import scipy.stats

def func(distribution):
    distribution.fit([1, 2, 3])

with multiprocessing.Pool(2) as pool:
    pool.map(func, [scipy.stats.genextreme])

with multiprocessing.Pool(2) as pool:
    pool.map(func, [scipy.stats.gumbel_r])
```

This works, but feels like a hack and was pretty hard to track - my CI runs were running for hours instead of minutes, no exceptions were raised, and it took over an hour to figure out the issue.

**Comment by georgebv** [comment]
I have another idea (inspired by this https://stackoverflow.com/questions/34253069/how-to-use-class-decorators-with-pickle). What if we simply add one line (`wrapper.__name__ = fun.__name__`) to the decorator function:

```python
def _call_super_mom(fun):
    # if fit method is overridden only for MLE and doesn't specify what to do
    # if method == 'mm', this decorator calls generic implementation
    def wrapper(self, *args, **kwds):
        method = kwds.get("method", "mle").lower()
        if method == "mm":
            return super(type(self), self).fit(*args, **kwds)
        else:
            return fun(self, *args, **kwds)

    wrapper.__name__ = fun.__name__

    return wrapper
```

**Comment by ev-br** [comment]
As a side note, I wonder why our test suite did not pick this. IIRC we do have tests to make sure distributions are picklable

**Comment by rkern** [comment]
Try [`functools.wraps()`](https://docs.python.org/3/library/functools.html#functools.wraps) and see if that helps.

The distribution itself is pickleable since all it needs is to record the name of the class. That's why the (perfectly idiomatic) workaround of passing the distribution object itself to the subprocesses works. Pickling just the method itself, on the other hand, I don't think we test.
