### ISSUE TITLE
convolve2d not working

### ISSUE THREAD

**Issue by Hamuel101** [scipy/scipy#14369]
My issue is about the scipy.signal.convolve2d operation not working

#### Reproducing code example:

```
from scipy.signal import convolve2d
x = np.array([[1,2,3],[4,5,6],[6,7,8]])
y = np.array([[1,1],[2,2]])
print(convolve2d(y,x,mode = 'valid'))
```

#### Error message:
it prints:
[[15 21]
 [31 37]]
it should print:
[[21 27]
[39 45]]
-->

#### Scipy/Numpy/Python version information: returns: 1.7.0 1.19.5 sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)
<!-- You can simply run the following and paste the result in a code block
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)

```

**Comment by jakevdp** [comment]
Hi - thanks for the question. I'm not sure where your expected numbers come from, but perhaps you have in mind `correlate2d` rather than `convolve2d`? The difference is that `convolve` will flip the axes of the second input before doing the sliding window operation, correlate will not. The results for correlate2d are similar to the values you expect (I could not understand what operation you have in mind to produce the exact expected values in your question):
```python
from scipy.signal import correlate2d
import numpy as np
x = np.array([[1,2,3],
              [4,5,6],
              [6,7,8]])
y = np.array([[1,1],
              [2,2]])
print(correlate2d(x, y, mode = 'valid'))
# [[21 27]
#  [35 41]]
```

**Comment by rkern** [comment]
They intended `x = np.array([[1,2,3],[4,5,6],[7,8,9]])` as the example input. Using `correlate2d()` with that input gives the expected results.

It's worth noting that convolutional neural network implementations typically use "convolution" to refer to the _un_-flipped convention as opposed to the standard signal processing convention that we use in scipy. That is going to be an increasing source of confusion, I'm willing to bet.

I am going to close this issue as we are doing a correct thing, and the desired thing is available.

**Comment by Hamuel101** [comment]
yeah my bad. I am working on a convolutional NN, and I did get mistaken. 

Maybe rename? not sure, but it was a bit confusing for me. Thanks for the clarification!

**Comment by rkern** [comment]
We will not be renaming the function. The signal-processing convention (and `scipy.signal.convolved2d()`) _long_ predates the popular implementations of CNNs that repurposed the word.

**Comment by Hamuel101** [comment]
fair enough. Thanks for the help.
