### ISSUE TITLE
Memory leak in `scipy.spatial.distance` for `cdist`

### ISSUE THREAD

**Issue by amiranas** [scipy/scipy#14382]
There is a memory leak in `cdist` in 1.7 that was not there in 1.6.3.

#### Reproducing code example:
```
from scipy.spatial.distance import cdist
import numpy as np

while True:
    cdist(np.random.rand(3, 2000), np.random.rand(5, 2000))
```

#### Scipy/Numpy/Python version information:
`1.7.0 1.21.0 sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)`

**Comment by tupui** [comment]
Thank you @amiranas for finding this.
