### ISSUE TITLE
`linalg.inv` fails for arrays of shape (0, 0)

### ISSUE THREAD

**Issue by Kaniee** [scipy/scipy#14389]
My issue is about the behavior of `linalg.inv` for arrays of shape (0, 0).
I would like to move from `numpy.linalg` to `scipy.linalg`, but with scipy inverting this kind of matrices is not possible.
Normally my functions runs with (M, M) matrices with M > 0 but I would like to handle the edge case as well where M = 0.
I can work around this issue by checking the shape beforehand, but it seams to me like a bug with scipy's `linalg.inv` that it can't handle this case.

#### Reproducing code example:

```
import numpy
import scipy
z = numpy.zeros((0, 0))
numpy.linalg.inv(z) # --> array([], shape=(0, 0), dtype=float64)
scipy.linalg.inv(z) # --> ValueError
```

#### Error message:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/test.py in <module>
      3 z = numpy.zeros((0, 0))
      4 numpy.linalg.inv(z) # --> array([], shape=(0, 0), dtype=float64)
----> 5 scipy.linalg.inv(z) # --> ValueError

~/anaconda3/lib/python3.8/site-packages/scipy/linalg/basic.py in inv(a, overwrite_a, check_finite)
    963         raise LinAlgError("singular matrix")
    964     if info < 0:
--> 965         raise ValueError('illegal value in %d-th argument of internal '
    966                          'getrf|getri' % -info)
    967     return inv_a

ValueError: illegal value in 4-th argument of internal getrf|getri
```

#### Scipy/Numpy/Python version information:

`1.6.2 1.20.2 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)`

**Comment by tupui** [comment]
It is indeed inconsistent with what NumPy does. @ilayn what do you think? Should we improve the validation here?

**Comment by ilayn** [comment]
Argh. Yes we need to accomodate for these indeed. 

But as a word of obligatory caution, prefer `solve` to `inv` if you don't need the inverse itself.

**Comment by tupui** [comment]
@Kaniee would you like to make a PR?

**Comment by Kaniee** [comment]
Would be my first one here, but I can give it at try.
I would add something like this:
```
if a1.shape[0] == 0:
    return np.identity(0)
```

**Comment by ilayn** [comment]
You can just return `a1.copy()` after the squareness check.

**Comment by ev-br** [comment]
There are several open issues about zero-sized matrices in other linalg functions, would be nice to handle these uniformly across scipy.linalg.

IIRC there also was an issue with a link to a Nick Higham paper about zero-sized matrices, but I cannot find it anymore. IIRC it was Alex Griffing advocating for it.

**Comment by ilayn** [comment]
@ev-br  #4908 ?

**Comment by ev-br** [comment]
Thanks @ilayn, clicking though... found it ---It's de Boor, not Higham:
https://github.com/scipy/scipy/pull/4672#issuecomment-124718692
