### ISSUE TITLE
Let CloughTocher2DInterpolator fit "nearest" for points outside the convex hull (instead of nans)

### ISSUE THREAD

**Issue by chausies** [scipy/scipy#14386]
Currently, [CloughTocher2DInterpolator](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.CloughTocher2DInterpolator.html#scipy.interpolate.CloughTocher2DInterpolator) can only fill in a constant value (nan by default) when queried outside the convex hull of the input points. But this absolutely isn't ideal.

What would be much better is to use the value of the nearest neighbor, which [NearestNDInterpolator](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.NearestNDInterpolator.html#scipy.interpolate.NearestNDInterpolator) does by default. For CloughTocher2DInterpolator, which already constructs the Delaunay Triangulation of the input points, finding the nearest point on the convex hull should be efficient.

Here's just my naive implementation for filling in the nearest neighbor value outside the convex hull of the inputs.

```python3
import matplotlib.pylab as P
from scipy.interpolate import CloughTocher2DInterpolator as CT
def my_CT(xy, z):
  x = xy[:, 0]
  y = xy[:, 1]
  f = CT(xy, z)
  def new_f(xx, yy):
    xx = P.array(xx) + [0.0]
    yy = P.array(yy) + [0.0]
    zz = f(xx, yy)
    nan = P.isnan(zz)
    if nan.any():
      inds = P.argmin(
          (x.reshape(-1, 1) - xx[nan])**2 + 
          (y.reshape(-1, 1) - yy[nan])**2
          , 0)
      zz[nan] = z[inds]
    return zz
  return new_f
```

**Comment by ev-br** [comment]
@chausies Thank you for the example! I've added it in gh-17299, do you want me to add you as a co-author of the relevant commit? I'll then need your email address to properly format the co-authored-by git entry.

**Comment by chausies** [comment]
@ev-br thanks so much! Sorry for not replying sooner. If it's not too late, I wouldn't mind being credited. My email is chausies @ stanford.edu .
Let me know if it works out. Cheers!

**Comment by ev-br** [comment]
Well, the relevant scipy commit does list your name, which was taken from your GH profile: https://github.com/scipy/scipy/commit/61ff61f38f65ba257c409993b4b7e0feaf6d103a

For adding a git-recognized `co-authored-by` stanza, it unfortunately is too late: rewriting the commit in the main branch is a big no-no, it would wreak too much havoc on everyone who pulled main over the last few months.

Let me ask our release manager @tylerjereddy if it is still possible to manually add a name to the list of authors for the upcoming 1.10 release?

**Comment by tylerjereddy** [comment]
@ev-br I manually added @chausies to the author list in https://github.com/scipy/scipy/pull/17696#issuecomment-1369091874

**Comment by ev-br** [comment]
Thank you Tyler!

**Comment by chausies** [comment]
Thank you so much @tylerjereddy @ev-br! Now I can tell everyone I've hit the big leagues ^_^.
Keep up the great work! Happy New Years!
