### ISSUE TITLE
Memory use is increasing as the times of call in function scipy.stats._sobol._categorize

### ISSUE THREAD

**Issue by Stardust1225** [scipy/scipy#14399]
My issue is about memory leak in function scipy.stats._sobol._categorize.
As the below code shows, if I input illegal input to the function, the memory use is increasing as the number of calls.

#### Reproducing code example:
```
import sys
import tracemalloc
import numpy
import scipy.stats._sobol

arg_list = []
arg_list.append(-87.11965751389266)
arg_list.append(17.04812581438513)
arg_list.append(-3)
arg_list.append(-87)
arg_list.append(-14)
arg_list.append(37)
arg_list.append(-63)
arg_list.append(-73)
arg_list.append(-83)
arg_list.append(-14)
arg_list.append(96)
arg_list.append(70)

memory_recorder = []
tracemalloc.start()
start_snapshot = tracemalloc.take_snapshot()
for i in range(0, 100):
  try:
    scipy.stats._sobol._categorize(numpy.array([arg_list[0], arg_list[1]]),
                                   numpy.array([arg_list[2], arg_list[3], arg_list[4], arg_list[5], arg_list[6]]),
                                   numpy.array([arg_list[7], arg_list[8], arg_list[9], arg_list[10], arg_list[11]]))
  except:
    pass
  if i % 10 == 0:
    one_snapshot = tracemalloc.take_snapshot()
    memory_recorder.append(one_snapshot.compare_to(start_snapshot, 'lineno')[0])

for i in range(2, len(memory_recorder)):
  if str(memory_recorder[i].traceback) == str(memory_recorder[1].traceback):
    print(memory_recorder[i].traceback)
    print(memory_recorder[i].size)

tracemalloc.stop()
```

#### Error message:
```
test.py:32
9594
test.py:32
13690
test.py:32
17482
test.py:32
21482
test.py:32
25274
test.py:32
29322
test.py:32
33114
test.py:32
37210
```

#### Scipy/Numpy/Python version information:
scipy 1.7.0

**Comment by rgommers** [comment]
@Stardust1225 thanks for the report. `_sobol._categorize` is a private function, is there actually any way that a public function can pass such invalid input to it? Normally the input validation in public functions should catch this.

**Comment by tupui** [comment]
Yeah if there is no leak when called by a public function I would not say that it's a concern. This is really not meant to be used elsewhere.

**Comment by tupui** [comment]
So this function is only called once here:
```python
base_draws = self.engine.random(n).ravel()
p_cumulative = np.empty_like(self.pvals, dtype=float)
_fill_p_cumulative(np.array(self.pvals, dtype=float), p_cumulative)
sample = np.zeros_like(self.pvals, dtype=int)
_categorize(base_draws, p_cumulative, sample)
```
The types are explicitely given for all parameters excepts `base_draws`. But all engines return float arrays. To call this function with a list of integers here, you would need to make your own class sampling only integers and this would fail. But I am not convince that this would make any sense to try to do this.

**Comment by peterbell10** [comment]
I've reported the leak to cython (cython/cython#4296) but agree this particular function shouldn't cause any issues. The issue @tupui points out with `base_draws` doesn't matter because it's the first argument so no other memory views will have been constructed yet.

**Comment by tupui** [comment]
Thanks for having a deeper look @peterbell10
