### ISSUE TITLE
BUG: Sphinx 4.1 breaks the banner's logo

### ISSUE THREAD

**Issue by tupui** [scipy/scipy#14396]
Sphinx 4.1 was released on July 11th, 2021. Since then the logo file is not present anymore in the artifact which is uploaded. As we did not touch anything (I checked pipelines before and after to confirm this), I am confident this is linked to Sphinx release.

[EDIT: the path is indeed changed to `/_static/_static/scipyshiny_small.png` due to a Sphinx regression, see the linked Sphinx PR below.]

From the logs
```
# working
Running Sphinx v4.0.3
SciPy (VERSION 1.8.0.dev0+1419.1d97b81)

# failing
Running Sphinx v4.1.0
SciPy (VERSION 1.8.0.dev0+1420.0a95709)
```

**Comment by ViktorHaag** [comment]
Issue created upstream in Sphinx project: https://github.com/sphinx-doc/sphinx/issues/9438
