### ISSUE TITLE
Incomplete docstring in `brenth`

### ISSUE THREAD

**Issue by astrojuanlu** [scipy/scipy#14390]
There is an incomplete sentence in the `brenth` documentation:

https://github.com/scipy/scipy/blob/3dbe759189bf0f947530c5ab1bf59a43ea4924de/scipy/optimize/zeros.py#L788

([Credit goes to @jacobwilliams 😉](https://twitter.com/DegenerateConic/status/1411790932106690565))

**Comment by tupui** [comment]
Thanks for spotting this @astrojuanlu. Would you do a PR to fix it?

**Comment by astrojuanlu** [comment]
I have already contributed to SciPy in the past, perhaps I could leave this to first contributors? Otherwise I'll be happy to send a PR this week 👍🏽

**Comment by tupui** [comment]
> I have already contributed to SciPy in the past, perhaps I could leave this to first-time contributors? Otherwise I'll be happy to send a PR this week 👍🏽

It's completely fine if you do it as well. I just flagged it because it should be a simple fix. As you wish 😃

**Comment by melissawm** [comment]
I am wondering if it would be interesting to include a citation for that paper? I tried searching for similar papers but didn't find anything to match the description. There is a reference in a comment below the function definition but I didn't really check it.

**Comment by jacobwilliams** [comment]
Do you mean this?
```
################################
# TOMS "Algorithm 748: Enclosing Zeros of Continuous Functions", by
#  Alefeld, G. E. and Potra, F. A. and Shi, Yixun,
#  See [1]
```

I think that is referring to the code after this one. 

I haven't been able to figure out what paper 1980s is being referred to here.

**Comment by Palash-Vishnani** [comment]
Can I work on this issue.?
I found this after some research. Is this right?

**In 1980 he and Nobel laureate Edwin McMillan found a new algorithm for high-precision computation of the Euler constant using Bessel functions, and showed that gamma can not have a simple rational form p/q (where p and q are integers) unless q is extremely large.**
