### ISSUE TITLE
scipy.io.write too slow

### ISSUE THREAD

**Issue by brianpenghe** [scipy/scipy#14398]
I'm analyzing single-cell transcriptomic data which can be about a huge sparse matrix. Currently `scipy.io.mmwrite` works for writing a matrix into Matrix Market format, but it seems to be only using one CPU. 

Is there a way to speed up this function?

**Comment by rgommers** [comment]
The implementation is looping in pure Python (https://github.com/scipy/scipy/blob/master/scipy/io/mmio.py#L678), so the obvious way to speed it up would be to rewrite it in Cython.

**Comment by dschmitz89** [comment]
With [fast matrix market](https://github.com/scipy/scipy/pull/18631) merged, `.mtx` IO is much faster, so closing this.
