### ISSUE TITLE
Extra function arguments to `scipy.integrate.quad_vec`

### ISSUE THREAD

**Issue by chahak13** [scipy/scipy#14412]
Hello, thanks for the work on scipy! 

I was looking at the docs/source for `scipy.integrate.quad_vec` and I noticed that there isn't a provision to provide arguments for the callable function we wish to integrate. For the `scipy.integrate.quadrature`, we have the `args` argument that we can pass to the function for such a behaviour. Is there a way to do that with `quad_vec`?

Thanks!

**Comment by tupui** [comment]
Thanks for the suggestion. In the meantime, you can pass the parameters by using [functools.partial](https://docs.python.org/3/library/functools.html#functools.partial) for instance.

**Comment by chahak13** [comment]
Ah thanks! I forgot about partial, for some reason. I'll do that for now. But it'll be great to have this feature built-in too in future!

**Comment by AnirudhDagar** [comment]
@tupui I can send a PR to add this argument. Should be straightforward.
