### ISSUE TITLE
`_cdf_cvm` inaccurate for small `n`

### ISSUE THREAD

**Issue by allefeld** [scipy/scipy#14415]
The documentation of `_cdf_cvm` notes:

> The function is not expected to be accurate for large values of x, say
    x > 2, when the cdf is very close to 1 and it might return values > 1
    in that case, e.g. _cdf_cvm(2.0, 12) = 1.0000027556716846.

However, in addition to that, the function is inaccurate for small values of `n`, in particular 2. Below approx. 0.042 the value drops to 0, and above approx. 0.666 it jumps to 1. To a smaller extent, similar things happen for other small `n`.

I don't know whether this can be fixed, but it should be documented.

#### Reproducing code example:
```
>>> _cdf_cvm([0.041, 0.042, 0.666, 0.667], n=2)
array([0.      , 0.031081, 0.993724, 1.      ])
```

#### Scipy/Numpy/Python version information:
```
1.6.3 1.20.2 sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)
```

#### Plots
![bokeh_plot](https://user-images.githubusercontent.com/1738353/125690393-7c89a381-4713-45e9-b394-57e4fcb233c5.png)
![bokeh_plot](https://user-images.githubusercontent.com/1738353/125690535-144db187-ce68-473b-8839-90084fe13ef1.png)

**Comment by allefeld** [comment]
#### Additional remark

I used these small n because I was checking the correctness of the implementation, and the only tabulation I could find, [Scott (2000)](http://dx.doi.org/10.1080/03610920008832479), uses these – probably because for larger n, the distribution quickly approaches n = ∞.

Here is the table:
![Scott2000TableI](https://user-images.githubusercontent.com/1738353/125690961-1f0421b4-d423-486d-81ad-e4b4380af3c9.png)

Comparing these tabulated values with `_cdf_cvm`:

```python
x = [0.11888, 0.34730, 0.46136, 0.58016, 0.74346, 1.16786]
for n in [2, 3, 4, 5, 6, None]:
    print(_cdf_cvm(x, n=n))
```
```
[0.462506 0.906943 0.960456 0.985229 1.       1.      ]
[0.475004 0.904628 0.956971 0.981798 0.995221 1.      ]
[0.481254 0.90347  0.955228 0.980082 0.993916 1.000132]
[0.485003 0.902776 0.954182 0.979053 0.993133 0.999905]
[0.487503 0.902312 0.953485 0.978366 0.992611 0.999754]
[0.500002 0.899997 0.95     0.974935 0.99     0.999   ]
```

For n = ∞ the agreement is good – for smaller n, not so much. Of course it is possible that `_cdf_cvm` is correct and Scott (2000) is not. However, the author notes that the values for n = 2 are based on an analytical calculation, and that for both 2 and 3 his values agree with those of an earlier paper.

**Comment by tupui** [comment]
Thank you for finding this. FYI, this is a private method so you should not use it as there is no guarantee that it will be present/break in any future release.

**Comment by allefeld** [comment]
I am aware. I was thinking of asking you guys to expose this as a public function. I need the CvM CDF in a context outside of a CvM test.

**Comment by chrisb83** [comment]
Hi,

if you check the second reference in the documenation, you will find some more details on the approximation:

Csorgo, S. and Faraway, J. (1996). The Exact and Asymptotic Distribution of Cramér-von Mises Statistics. Journal of the Royal Statistical Society, pp. 221-234. => you can find it on the website https://people.bath.ac.uk/jjf23/papers/index.html

> Below approx. 0.042 the value drops to 0, and above approx. 0.666 it jumps to 1

That is correct, the support of the exact distribution is contained in [1/(12*n), n/3], see Eq 1.1 in the article

You can take a look at Table 1 in the article, it contains a comparison of the exact values and the approximation. And indeed, for n=2, the approximation is not great but that is not a problem with the implementation but rather the way the approximation works (error is about 1/n**2, see Eq 1.8)

So if you need more accurate values for small n, there are other approaches you could use, they are briefly mentioned in the article, too. I hope it helps...

**Comment by allefeld** [comment]
@chrisb83 thanks!

The explanation makes sense, but it should be documented. Especially since the documentation already mentions inaccuracies, that suggests that these are the *only* inaccuracies.

**Comment by tupui** [comment]
> The explanation makes sense, but it should be documented. Especially since the documentation already mentions inaccuracies, that suggests that these are the _only_ inaccuracies.

Would you like to do a PR to improve the documentation of the function? As for making it public, I am not able to judge as I don't know how this can be used. But since the function is here, I am not against the idea. Then it would mean adding more documentation, input validation (can call a private method which does not have the validation part if that would impact speed) and tests.

What do you think @chrisb83?

**Comment by mdhaber** [comment]
@allefeld can you tell us more about applications of the distribution beyond the test?

**Comment by allefeld** [comment]
@tupui, I can make a PR, might take a bit.

@mdhaber  my application is an implementation of the method of [Patra & Sen (2016)](http://users.stat.ufl.edu/~rohitpatra/PapersandDraft/FinalVerNPMixModelJRSSB_high_cont.pdf). Its purpose is to estimate the mixing proportion in a semi-parametric mixture model, useful e.g. for prevalence estimation as well as in the context of FDR correction.

**Comment by chrisb83** [comment]
I am not against adding it as a public method. There are a few points that we should take into account:

- It might be confusing if we implement an approximation of the cdf and not the exact CDF. In the CvM test, we clearly say that the p-value is computed using the approximation derived in the article (in the R package `goftest`, the same implementation is used for the CDF: https://search.r-project.org/CRAN/refmans/goftest/html/pCvM.html). At least for small values of n, a user probably expects higher accuracy whereas for the CvM test, it might not be as important (one should still update the documentation). 
- in stats, the CDFs are usually part of the distribution, there are no standalone CDFs => the right place might be `scipy.special`, this already contains functions like `kolmogorov`. but the integration requires a bit more work in that case

**Comment by allefeld** [comment]
I've created a PR, please check.

@chrisb83:

I don't understand the problems of the approximation well enough to say whether it would be feasible to make a more precise implementation. I suspect that would entail numerical calculations that are too expensive for the function itself, so one would probably have to pre-calculate a tabulation and then interpolate.

I agree that there is no acute problem for the GoF test, because it is unlikely that anyone would do such a test on a sample size of 2, and even then at the conventional level of 0.05 one would have to Bonferroni-correct for several test in order to reach the values where the approximation fails relevantly.

I would still appreciate if the function (either the current approximation or something better) could be exposed publicly. `scipy.special` seems like a good place for that.
