### ISSUE TITLE
Is the r-value outputted by scipy.stats.linregress always the Pearson correlation coefficient?

### ISSUE THREAD

**Issue by aidan-fitz** [scipy/scipy#14416]
The [documentation][linregress] just says that `rvalue` is the "Correlation coefficient" but there are many different correlation coefficients, not just the Pearson one. However, it also says that the square of `rvalue` is the coefficient of determination, and according to [Wikipedia][coeffdet]:
> When an intercept is included, then r2 is simply the square of the sample correlation coefficient (i.e., r) between the observed outcomes and the observed predictor values.[4] If additional regressors are included, R2 is the square of the coefficient of multiple correlation.

Is the output always the Pearson coefficient, or is it sometimes the coefficient of multiple correlation? We should clarify that in the documentation.

[linregress]: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.linregress.html
[coeffdet]: https://en.wikipedia.org/wiki/Coefficient_of_determination

**Comment by charlotte12l** [comment]
In `scipy.stats.linregress `, `r = ssxym / sqrt( ssxm * ssym )` so I think it is [Pearson coefficient](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient). 

> However, it also says that the square of `rvalue` is the coefficient of determination, and according to [Wikipedia](https://en.wikipedia.org/wiki/Coefficient_of_determination):
> 
> > When an intercept is included, then r2 is simply the square of the sample correlation coefficient (i.e., r) between the observed outcomes and the observed predictor values.[4] If additional regressors are included, R2 is the square of the coefficient of multiple correlation.
> 
> Is the output always the Pearson coefficient, or is it sometimes the coefficient of multiple correlation? We should clarify that in the documentation.

According to [Wikipedia 1.3 As squared correlation coefficient](https://en.wikipedia.org/wiki/Coefficient_of_determination#As_squared_correlation_coefficient)
>In linear least squares multiple regression with an estimated intercept term, R2 equals the square of the Pearson correlation coefficient between the observed {\displaystyle y}y and modeled (predicted) {\displaystyle f}f data values of the dependent variable.
> In a linear least squares regression with an intercept term and a single explanator, this is also equal to the squared Pearson correlation coefficient of the dependent variable {\displaystyle y}y and explanatory variable {\displaystyle x.}x.

Here in our linear least-squares regression ` scipy.stats.linregress`,  the square of `rvalue`(Pearson coefficient) is equal to  `R2` (Coefficient of determination).
