### ISSUE TITLE
brentq does converge and not raise an error for np.nan functions

### ISSUE THREAD

**Issue by juergspaak** [scipy/scipy#14414]
When useing the brentq optimizer to find a root it does not raise an error while encountering an np.nan value

#### Reproducing code example:

```
from scipy.optimize import brentq
import numpy as np

x,r = brentq(lambda x: np.nan if x == 1 else x, 1,2, full_output = True)
```
This returns x = 0 (which is not even in the bound [1,2]) and r.converged = True. In my opinion this should raise an error.

Scipy/Numpy/Python version information:
1.5.2 1.19.2 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Thanks for finding this. Note that from the note section `f must be continuous. f(a) and f(b) must have opposite signs.` Although I agree that input validation is missing here.
