### ISSUE TITLE
Running tests in parallel is not any faster than without pytest-xdist anymore

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#14425]
I have no idea what is going on here, but no matter how I run the tests, I'm not getting them to run any faster in parallel. These commands all give me the same timings (about 21 sec):
- `python -c "import scipy; scipy.test()"`
- `python -c "import scipy; scipy.test(parallel=4)"`
- `pytest --pyargs scipy.linalg`
- `pytest -n 4 --pyargs scipy.linalg`

And the same if I try it on other submodules or on scipy as a whole. I even uninstalled `pytest-xdist` to make sure - no difference whatsoever.

This used to work after gh-10172 two years ago. Does this still work for anyone else?

**Comment by rgommers** [comment]
There's also different strategies in `pytest-xdist` (e.g. `--dist loadfile`) that don't help. And there's `pytest-split`, `pytest-test-groups`, and even attempts to use `pytest-xdist` and `pytest-split` together: https://github.com/jerry-git/pytest-split/issues/2. It's all a bit clunky though.

**Comment by tylerjereddy** [comment]
I can get a speedup, although the amount of hardware I had to through at it to cut the time in half is pretty staggering.

On an i9 with 10 cores/20 threads (ubuntu Linux) with latest `master` installed:

- `python runtests.py -n -- -n 20`
  - `32599 passed, 2112 skipped, 104 xfailed, 11 xpassed in 178.68s (0:02:58)`
- `python runtests.py -n`
  - `32599 passed, 2112 skipped, 11134 deselected, 104 xfailed, 11 xpassed in 377.89s (0:06:17)` 

I know that for some projects I work on the tradeoff of distributing the tests becomes a bit murkier as more of the codebase itself becomes inherently parallel, though seem like a stretch that we have *that* much default-parallel machinery just yet at least (plus we try to make parallel opt-in to empower custom workflows usually, I think).

**Comment by rgommers** [comment]
> seems like a stretch that we have _that_ much default-parallel machinery just yet

Yes, very little - the only thing that's significant is BLAS/LAPACK usage.

20 processes for a 2x speedup is a bit better than what I'm seeing, but either way it's terrible. I'm pretty sure it used to be much better. Maybe a `pytest` or `pytest-xdist` regression, or something we did.

**Comment by rgommers** [comment]
Okay you do have a good point with the influence of parallelism @tylerjereddy. The oversubscription issue matters more on a larger machine.

```bash
# spatial
$ export OMP_NUM_THREADS=1
$ pytest -n1 --pyargs scipy.spatial
43.68s
$ pytest -n2 --pyargs scipy.spatial
23.44s
$ pytest -n4 --pyargs scipy.spatial
13.35s
$ pytest -n12 --pyargs scipy.spatial
13.28s

$ export OMP_NUM_THREADS=4
$ pytest -n1 --pyargs scipy.spatial
45.67s 
$ pytest -n2 --pyargs scipy.spatial
25.06s
$ pytest -n3 --pyargs scipy.spatial
17.93s
$ pytest -n4 --pyargs scipy.spatial
14.43s

# linalg
$ export OMP_NUM_THREADS=4
$ pytest -n1 --pyargs scipy.linalg
19.06s
$ pytest -n4 --pyargs scipy.linalg
9.83s


$ export OMP_NUM_THREADS=1
$ pytest -n1 --pyargs scipy.linalg
19.85s
$ pytest -n4 --pyargs scipy.linalg
9.90s
$ pytest -n8 --pyargs scipy.linalg
9.25s
```

To verify that `OMP_NUM_THREADS` actually has an effect (also shows up in `top` with the process using >100% CPU):

<details>

```bash
$ python -c "import scipy; scipy.show_config()"
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/home/rgommers/anaconda3/envs/scipy-meson/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/home/rgommers/anaconda3/envs/scipy-meson/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/home/rgommers/anaconda3/envs/scipy-meson/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/home/rgommers/anaconda3/envs/scipy-meson/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

$ export OMP_NUM_THREADS=4
$ python -m threadpoolctl -i numpy scipy.linalg
[
  {
    "filepath": "/home/rgommers/anaconda3/envs/scipy-meson/lib/libopenblasp-r0.3.12.so",
    "prefix": "libopenblas",
    "user_api": "blas",
    "internal_api": "openblas",
    "version": "0.3.12",
    "num_threads": 4,
    "threading_layer": "pthreads",
    "architecture": "SkylakeX"
  }
]
$ unset OMP_NUM_THREADS
$ python -m threadpoolctl -i numpy scipy.linalg
WARNING: could not import scipy.linalg
[
  {
    "filepath": "/home/rgommers/anaconda3/envs/scipy-meson/lib/libopenblasp-r0.3.12.so",
    "prefix": "libopenblas",
    "user_api": "blas",
    "internal_api": "openblas",
    "version": "0.3.12",
    "num_threads": 24,
    "threading_layer": "pthreads",
    "architecture": "SkylakeX"
  }
]

```

</details>

```bash
$ export OMP_NUM_THREADS=1
$ pytest -n8 --pyargs scipy
198.57s
$ export OMP_NUM_THREADS=4
$ pytest -n8 --pyargs scipy
198.28s
$ export OMP_NUM_THREADS=6
$ pytest -n4 --pyargs scipy
272.37s
$ unset OMP_NUM_THREADS  # will use 24 threads
$ pytest -n1 --pyargs scipy
724.20s
$ pytest -nauto --pyargs scipy  # chooses 12 processes
579.97s
$ pytest --n3 --pyargs scipy  # chooses 12 processes
435.93s
$ export OMP_NUM_THREADS=2
$ pytest -n6 --pyargs scipy
247.05s
```

Conclusions:
- `pytest-xdist` scalability is really bad, it doesn't help beyond `-n 4` and may even have a negative effect on machines with a lot of cores.
- Limiting the number of OpenMP threads for OpenBLAS/MKL doesn't hurt, and can help significantly.

I briefly played with `pytest-split` as well, and it looks much more capable of scaling linearly, because there's no communication overhead -i f you do a 10-fold split, it just runs 10% of the tests (balanced so total time for each split is about equal) in a process and reports the 10 results separately. The price you pay is doing test collection separately in all 10 processes.

**Comment by rgommers** [comment]
This is also a bit sad:
```bash
$ time pytest --collect-only --pyargs scipy
============================ 45927 tests collected in 41.89s =============================

real    0m43.740s
user    0m42.629s
sys     0m1.009s
```
The main culprits are `stats` and `sparse`, they take ~15s each.

**Comment by rgommers** [comment]
Based on what scikit-learn does in in `sklearn/conftest.py`, I tried using `threadpoolctl`:

```diff
diff --git a/scipy/conftest.py b/scipy/conftest.py
index dae9dbcf33..8faf59450a 100644
--- a/scipy/conftest.py
+++ b/scipy/conftest.py
@@ -8,6 +8,13 @@ import numpy as np
 from scipy._lib._fpumode import get_fpu_mode
 from scipy._lib._testutils import FPUModeChangeWarning
 
+try:
+    from threadpoolctl import threadpool_limits
+    HAS_THREADPOOLCTL = True
+except ImportError:
+    # Optional dependency only
+    HAS_THREADPOOLCTL = False
+
 
 def pytest_configure(config):
     config.addinivalue_line("markers",
@@ -39,6 +46,22 @@ def pytest_runtest_setup(item):
     if mark is not None and np.intp(0).itemsize < 8:
         pytest.xfail('Fails on our 32-bit test platform(s): %s' % (mark.args[0],))
 
+    if HAS_THREADPOOLCTL:
+        # Set the number of openmp threads based on the number of workers
+        # xdist is using to prevent oversubscription. Simplified version of what
+        # sklearn does (it can rely on threadpoolctl and its builtin OpenMP helper
+        # functions)
+        try:
+            xdist_worker_count = int(os.environ['PYTEST_XDIST_WORKER_COUNT'])
+        except KeyError:
+            # raises when pytest-xdist is not installed
+            return
+
+        if not os.getenv('OMP_NUM_THREADS'):
+            max_openmp_threads = os.cpu_count() // 2  # use nr of physical cores
+            threads_per_worker = max(max_openmp_threads // xdist_worker_count, 1)
+            threadpool_limits(threads_per_worker, user_api='openmp')
+
 
 @pytest.fixture(scope="function", autouse=True)
 def check_fpu_mode(request):
```

But it doesn't seem to be effective. There's of course various system-dependent reasons why this can fail; using `export OMP_NUM_THREADS=2` in CI configs and local dev envs will be more robust.

**Comment by rgommers** [comment]
@thomasjpfan pointed out that there's a separate `user_api='blas'`: https://github.com/joblib/threadpoolctl/blob/master/threadpoolctl.py#L61. Need to try that. It's unclear whether `user_api='openmp'` is supposed to have an effect on opnblas-compiled-with-openmp.

**Comment by thomasjpfan** [comment]
With the same patch in https://github.com/scipy/scipy/issues/14425#issuecomment-881967659,  and running `pytest -n 16 --pyargs scipy`.

1. With `user_api='blas'`: 151s.
2. With `user_api='openmp'`: 246s.
3. On master: 247s.

**Comment by rgommers** [comment]
Thanks Thomas!
