### ISSUE TITLE
SuperLU symbol not found : _Destroy_CompCol_Matrix

### ISSUE THREAD

**Issue by goanayven** [scipy/scipy#14424]
#### Problem definition

This report may not be related with bugs, and a prominent solution surely pre-exists elsewhere.
My issue is about an internal linear solver and optimize functions failing to find a superLU function : _Destroy_CompCol_Matrix. 

#### Environment

First of all, I run Scipy in Apple silicon M1. I installed Scipy with Homebrew OpenBLAS with the install command line like - 
```
> OPENBLAS=/opt/OpenBLAS AR=libtool ARFLAGS="-static -o $@" python3 setup.py install 
```
, and versions from 1.6 - most recent 1.7 tried.

My installation results are looking good. All of egg files and .so are successfully generated.

I can successfully run codes
```
import Scipy
import Scipy.sparse
```

#### Reproducing code example:

My problem appears after I import lining, and optimize like - 
```
 import Scipy.sparse.linarg
```
or 
```
from Scipy.optimize import minimize
```

#### Error message:
```
<!--
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scipy-1.5.4-py3.8-macosx-11-universal2.egg/scipy/sparse/linalg/__init__.py", line 112, in <module>
    from .dsolve import *
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scipy-1.5.4-py3.8-macosx-11-universal2.egg/scipy/sparse/linalg/dsolve/__init__.py", line 58, in <module>
    from .linsolve import *
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scipy-1.5.4-py3.8-macosx-11-universal2.egg/scipy/sparse/linalg/dsolve/linsolve.py", line 11, in <module>
    from . import _superlu
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scipy-1.5.4-py3.8-macosx-11-universal2.egg/scipy/sparse/linalg/dsolve/_superlu.cpython-38-darwin.so, 2): Symbol not found: _Destroy_CompCol_Matrix
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scipy-1.5.4-py3.8-macosx-11-universal2.egg/scipy/sparse/linalg/dsolve/_superlu.cpython-38-darwin.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scipy-1.5.4-py3.8-macosx-11-universal2.egg/scipy/sparse/linalg/dsolve/_superlu.cpython-38-darwin.so
-->
```

As this error analysis, the issue happens from

> 2): Symbol not found: _Destroy_CompCol_Matrix

and 

> Expected in: flat namespace in _superlu.cpython-38-darwin.so.

Though I reported this issue into bugs, the problem probably caused by my method of build.
So I ask to investigate this issue with a wide view of aspects. 

#### Scipy/Numpy/Python version information:
Finally, I attached my version information -
```
<!--
<module 'scipy.version' from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/scipy-1.5.4-py3.8-macosx-11-universal2.egg/scipy/version.py'> 
<module 'numpy.version' from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy-1.22.0.dev0+342.ge69faef03-py3.8-macosx-11-universal2.egg/numpy/version.py'>
 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
-->
```

**Comment by rgommers** [comment]
This seems like a funky way to install dependencies and build SciPy indeed. You are building with the system Python (`/Library/Frameworks/Python.framework/...`), I'd strongly recommend not doing that. If you are building SciPy from source because only there are no wheels: either use the experimental wheels at https://anaconda.org/scipy-wheels-nightly/ for macOS `arm64`, or install your whole stack from conda-forge. The latter is recommended, since it has much better support for `arm64` than PyPI right now.

Either way, I suggest we close this issue since the config is not supported and bound to lead to issues. So I'll do that now - please comment though if there's more to talk about, I'm happy to continue the conversation or reopen the issue if needed @goanayven.
