### ISSUE TITLE
Issues concerning closing Delaunay triangulation for a 3D geometry

### ISSUE THREAD

**Issue by elifoo** [scipy/scipy#14428]
Hi,

I'm trying to use Delaunay function to obtain a 3D surface starting from a points cloud. 
The example that I report is a simplification of a more complex case to which I will then have to go and apply the code.
I cannot understand why the result of the triangulation is not a closed surface. The geometry is quite simple, as it is a sphere without the face top and the one bottom. However, I cannot understand why the triangulation does not close in on itself, but remains open ...

Any idea?

Thanks a lot!!!

[nxyz.npy.zip](https://github.com/scipy/scipy/files/6835996/nxyz.npy.zip)
<img width="452" alt="delaunay_triangulation" src="https://user-images.githubusercontent.com/78592327/126063242-dcb1bd41-0f6f-4421-af1e-dfa63037c714.png">

import matplotlib.pyplot as plt
import numpy as np
from scipy.spatial import Delaunay

points = np.load("nxyz.npy")

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(points[:,0],points[:,1],points[:,2])
plt.show()

##Convert to polar coordinates
rad = np.linalg.norm(points, axis=1)
zen = np.arccos(points[:,2] / rad)
azi = np.arctan2(points[:,1], points[:,0])
    
coor_del = np.array(list(zip(zen,azi)))
triang_del = Delaunay(coor_del,qhull_options="Q5")

fig = plt.figure()
ax  = plt.axes(projection='3d')
ax.plot_trisurf(points[:,0], points[:,1], points[:,2], triangles=triang_del.simplices, cmap=plt.cm.RdYlBu)
plt.show()

**Comment by tupui** [comment]
Hi, thanks for opening an issue. Note that the issue tracker is not meant to answer user questions and you should go on StackOverflow for instance.

For your problem, I did not really look at your code, but I guess you just have to add the first points at the end of the array.

**Comment by tylerjereddy** [comment]
Yeah, maybe try StackOverflow--some of us are interested in computational geometry but we don't have the bandwidth to answer queries on top of maintaining the code/dealing with bug reports, etc.

**Comment by elifoo** [comment]
Ok, thanks for your suggestion. I was just wondering if by any chance the problem was in the value set for qhull_options...
