### ISSUE TITLE
scipy.stats.entropy include a "normalized=True/False" argument

### ISSUE THREAD

**Issue by jolespin** [scipy/scipy#14436]
**Is your feature request related to a problem? Please describe.**
Yes, entropy scales by the size of the set. 

**Describe the solution you'd like**
Normalized entropy that is robust to set size

**Describe alternatives you've considered**
Coding it myself but I think it would be useful for other people to have this. 

**Additional context (e.g. screenshots)**
* https://en.wikipedia.org/wiki/Entropy_(information_theory)#Efficiency_(normalized_entropy)
* https://math.stackexchange.com/questions/395121/how-entropy-scales-with-sample-size
![image](https://user-images.githubusercontent.com/9061708/126208873-40305797-24cf-4f0d-ad03-e6326280fcb6.png)

**Comment by jolespin** [comment]
I believe this is the correct implementation. Though, I'm not sure how to generalize it for all logs: 

```python
def scaled_entropy(pk, log_func=np.log2, remove_zeros=True):
    pk = np.asarray(pk)
    assert np.all(pk >= 0), "Cannot calculate entropy with negatives"
    if remove_zeros:
        pk = pk[pk > 0]
    S = -(pk)*log_func(pk) # scipy.special.entry; S = entr(pk)
    S /= log_func(pk.size)
    S = S.sum() 
    return S
```

**Comment by mdhaber** [comment]
@jolespin the screenshot suggests that this is just a change of base (but i haven't looked closely). Can you clarify whether this can be accomplished by setting `base=n`?

**Comment by mdhaber** [comment]
Please set `base=len(pk)` to get a normalized entropy:

```python3
import numpy as np
from scipy.stats import entropy

# function copied from above
def normalized_entropy(pk, log_func=np.log2, remove_zeros=True):
    pk = np.asarray(pk)
    assert np.all(pk >= 0), "Cannot calculate entropy with negatives"
    if remove_zeros:
        pk = pk[pk > 0]
    S = -(pk)*log_func(pk) # scipy.special.entry; S = entr(pk)
    S /= log_func(pk.size)
    S = S.sum()
    return S

n = 21

# max entropy sample
pk1 = np.ones(n) / n

# intermediate entropy sample
pk2 = np.random.rand(n)
pk2 /= pk2.sum()

# zero entropy sample
pk3 = np.zeros(n)
pk3[10] = 1

print(normalized_entropy(pk1), normalized_entropy(pk2), normalized_entropy(pk3))  
# 1.0000000000000002 0.9175240813785063 nan
# RuntimeWarning: invalid value encountered in true_divide S /= log_func(pk.size)

print(entropy(pk1, base=n), entropy(pk2, base=n), entropy(pk3, base=n))
# 0.9999999999999996 0.9175240813785066 0.0
# no warning
```
