### ISSUE TITLE
ImportError: cannot import name 'fsolve' from 'scipy.optimize' (/miniconda3/lib/python3.7/site-packages/scipy/optimize/__init__.py)

### ISSUE THREAD

**Issue by dusweaver** [scipy/scipy#14437]
Hi,

I can't seem to import the optimize sub module into python using:

`from scipy.optimize import fsolve`

I tried both python 3.7 and 3.8 and both give the same errors. Also, I tried on Centos, Ubuntu, and Windows 10 Bash using Anaconda 2021.05 (python 3.8), 2020.07(python 3.8), and 2019.10 (python 3.7).
Any help will be greatly appreciated.

**Comment by Palash-Vishnani** [comment]
@dusweaver I am able to import "fsolve" using the same import statement `from scipy.optimize import fsolve` , I am using python 3.9.  Also to let you know, "fsolve" function definition is written in `minpack.py` . `site-packages/scipy/optimize/__init__.py` this path contain an import statement which says, `from .minpack import *` thus this statement import every thing from minpack.py, "fsolve" too.

**Comment by ilayn** [comment]
Could you please fill in the template parts specifically for this purpose ? Otherwise this is a no-repro.

**Comment by Palash-Vishnani** [comment]
@ilayn actually I am new to open source and I don't know what template parts are you talking about? Are you telling this to the guy who opened this issue? Or can you please elaborate what are you trying to tell me.

**Comment by ilayn** [comment]
Yes it was meant for OP. You can see the template of you click New Issue button

**Comment by tupui** [comment]
@dusweaver any update?

**Comment by tupui** [comment]
@dusweaver friendly reminder.

**Comment by rgommers** [comment]
No follow-up and this works fine, so fairly sure this was just some kind of corrupt install issue - closing.
