### ISSUE TITLE
BUG: out of bounds indexing issue in `prini.f`

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#14445]
This build warning looks like a real bug:
```
[284/1311] Compiling Fortran object scipy/linalg...-x86_64-linux-gnu.so.p/src_id_dist_src_prini.f.o
../scipy/linalg/src/id_dist/src/prini.f:147:20:

  145 |         do 1800 i=1,1000
      |                                                                        2
  146 | c
  147 |         c(iadd+i)=b(i)
      |                    1
Warning: Array reference at (1) out of bounds (1000 > 1) in loop beginning at (2)
```

Should be easy to fix for someone familiar with Fortran.

**Comment by melissawm** [comment]
It looks like this `msgmerge` subroutine is not even used anywhere - all the tests pass without it. Not sure if this was there for licensing or historical reasons.

**Comment by rgommers** [comment]
`interpolative` was a vendored library, I think it just wasn't super carefully pruned when it was initially integrated.

**Comment by czgdp1807** [comment]
+1 with @melissawm Removing the subroutine doesn't affect the build so probably it was added but not used anywhere. Can I make a PR to remove this subroutine?

**Comment by rgommers** [comment]
yes please!
