### ISSUE TITLE
more step size control strategy for solving ODE(solve_ivp)

### ISSUE THREAD

**Issue by zhaofeng-shu33** [scipy/scipy#14443]
**Is your feature request related to a problem? Please describe.**
Using explicit method with default adaptive strategy leads to instability phenomena in stiff computations (the number of rejection is quite large). In such case, more sophisticated step size controller is preferred, such as PID control. This option is supported in the numerical ODE library of Julia programming language.

https://diffeq.sciml.ai/latest/extras/timestepping/#Proportional-Integral-Controller-(PI-Controller)

**Describe the solution you'd like**
Possibly add some keyword argument when constructing RK solvers (`class RungeKutta`) to switch the step size control strategy (or even totally disable adaptive control by using fixed step).

**Comment by laurent90git** [comment]
Hi,
explicit methods are usually not suited for stiff problems. Anyway, the difficulty in solving such problems is not solely linked to the time step control algorithm, but to the integration scheme itself.

If you however wish to have fixed time steps, you can do that by setting the integration tolerance at very large values, like `atol=rtol=1e30`, and then specifying the desired time step value as the maximum time step allowed: `max_step=2e-8` for instance. You can also enforce the first_step to be equal to that value with the argument `first_step=2e-8`. Note that this should not be used with implicit algorithms (BDF, LSODA, Radau), as these use define their inner convergence criteria (for the Newton loop) based on integration tolerances. Thus large tolerances may cause bad convergence.

**Comment by zhaofeng-shu33** [comment]
Thanks for your information. If I set both `atol` and `rtol` to a very large value, and set `max_step` and `first_step` to the same step length, I can get the result of fixed step method.
