### ISSUE TITLE
DOC/FEAT Rotation.from_rotvec documents a degrees argument which doesn't exist.

### ISSUE THREAD

**Issue by FirefoxMetzger** [scipy/scipy#14444]
As per the title, the documentation of [`scipy.spatial.transform.Rotate.from_rotvec`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.from_rotvec.html) documents an optional kwarg `degrees : bool`. However, when I try it it doesn't work.

```python
>>> from scipy.spatial.transform import Rotation
>>> foo = Rotation.from_rotvec((0, 0, 90), degrees=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: from_rotvec() takes no keyword arguments
>>> foo = Rotation.from_rotvec((0, 0, 90), True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: from_rotvec() takes exactly one argument (2 given)
```

I think the `degrees` option isn't super important since conversion between deg and rad is simple enough; however, I do think that the docs should match the code. What would be the correct fix? Updating the docs or adding the feature?

**Comment by FirefoxMetzger** [comment]
Ups, sorry for the noise. I just realized that this is a new feature in `v1.7.0`; however, I was still on `v1.6.1` on this machine. 

I guess this can be closed unless adding a line like `New in version 1.7.0` to the argument would be a useful addition.

**Comment by tupui** [comment]
Hi, thanks for the issue. Would you add this by doing a PR?

**Comment by FirefoxMetzger** [comment]
@tupui Done. The PR is running through CI.
