### ISSUE TITLE
mannwhitneyu acceptes nans

### ISSUE THREAD

**Issue by orena1** [scipy/scipy#14448]
Not sure if this is a feature request or a bug. 
mannwhitneyu should not accept np.nan, currently, it accepts it and gives bad p_values.

```python
import scipy.stats as stats
import numpy as np

a = [1,2,np.nan,np.nan,np.nan,np.nan]
b = [1,2,np.nan,np.nan,np.nan,np.nan]
stats.mannwhitneyu(a,b).pvalue
#  0.0281021903842455
```

This is pretty dangerous, especially when working with dataframes. I assume adding nan_policy to mannwhitneyu will be good (have not seen a ticket for that), but until it is added, maybe just returning an error if one of the vectors has np.nan (if None exists an error is already returned)

scipy.__version__
'1.6.3'

**Comment by orena1** [comment]
Sorry, it already exisits here:
https://github.com/scipy/scipy/blob/44e31b1eb202ef91caad059952ba268d2610a60b/scipy/stats/_mannwhitneyu.py#L132

**Comment by mdhaber** [comment]
Yes, i rewrote MWU for 1.7.0. it can now do the exact test for samples of moderate size, and it's vectorized / supports an `axis` argument. My plan is to add `nan_policy` with a decorator (gh-13312).
