### ISSUE TITLE
Adds Mixed Integer Linear Programming from highs

### ISSUE THREAD

**Issue by brunorigal** [scipy/scipy#14455]
Apparently Highs includes an MIP solver. do you plan to integrate it in the near future?

Apparently the behavior is very similar to that of the linprog solver except that you can set some variables as integer: 
https://github.com/ERGO-Code/HiGHS/blob/87ca783572a0ad8ee8a8b98f73585ae58d2e0032/examples/call_highs_from_python.py

**Comment by mdhaber** [comment]
> do you plan to integrate it in the near future?

Yes.

**Comment by mdhaber** [comment]
@brunorigal @AtsushiSakai @jhelgert @mkoeppe thanks for your interest!

Do you think that an argument (e.g. `intcon`, a boolean array to indicate which decision variables are integer-constrained) should be added to `linprog`, or should we expose this in a new function (e.g. `intlinprog`)?

**Comment by mkoeppe** [comment]
Not what you asked, but generally LP and MIP users benefit from having a more detailed API available than just a MATLAB-style blackbox function like the existing `linprog`. In particular, this is crucial for warmstarting when making small changes to the input (in particular RHS and objective), or adding a few rows. For example, if an API such as https://github.com/Pyomo/pyomo/blob/main/pyomo/solvers/plugins/solvers/persistent_solver.py can be implemented efficiently using the functions that you provide, you'll be in good shape.

**Comment by brunorigal** [comment]
As far as I am concerned, I would expose a new function, I think milp (mixed integer linear programming programming) is the standard name. If this function is called linprog, many users may not search for milp here.

**Comment by brunorigal** [comment]
@mkoeppe, I totally agree. I [discussed](https://github.com/cvxpy/cvxpy/issues/1443) with the guys of [cvxpy](https://www.cvxpy.org/) they told me they would integrate the milp solver in their api once it is available in scipy.

**Comment by rileyjmurray** [comment]
@mdhaber:

> @brunorigal @AtsushiSakai @jhelgert @mkoeppe thanks for your interest!
> 
> Do you think that an argument (e.g. `intcon`, a boolean array to indicate which decision variables are integer-constrained) should be added to `linprog`, or should we expose this in a new function (e.g. `intlinprog`)?

CVXPY interfaces with solvers with APIs that match either of those patterns. I think scipy users would benefit from allowing ``intcon`` (as an array of integer indices that specify the locations of integer-valued variables) to the existing ``linprog`` function. You could then wrap this with a ``milp`` function to make the mixed-integer functionality more prominent in the documentation.

**Comment by mdhaber** [comment]
Yes, there has been progress! Our proposal to the NASA ROSES E.7 funding opportunity was successful (see [here](https://numfocus.medium.com/numfocus-projects-receive-nasa-grants-deee374e7a57)), and part of the proposal was:

> SciPy’s linear programming functionality is missing some oft-requested functionality; we will
address this by adding interfaces to the best available open source libraries available. SciPy
1.6.0 made a start by adding the HiGHS Linear Programming solvers. We will extend that
interface to include the HiGHS mixed-integer programming capabilities. Separate interfaces to
CLP (linear programming), CBC (mixed-integer programming) and Ipopt (nonlinear programming)
[will be added].

We should know our start date in the next few weeks. I hope it will be in December, and this is the first thing that @mckib2 and I plan to work on.

**Comment by rileyjmurray** [comment]
@jajhall what's the "them" that you're referring to?

**Comment by jajhall** [comment]
> @jajhall what's the "them" that you're referring to?

Clp and Cbc

**Comment by mdhaber** [comment]
We wrote the proposal a year ago, and things have changed since then. I think we would only add them if we expect them to remain more performant. HiGHS seems as fast or faster than CBC right now, so do you expect it to stay that way? Do you expect HiGHS to overtake CLP in the next few years?

**Comment by jajhall** [comment]
HiGHS is very much faster than Cbc now, and the gap will only grow.

Clp's benchmark performance is misleading, as it has the "tricks" required to avoid using full-scale simplex on many of the benchmark problems. Put another way, I'm sure that Gurobi's not losing sleep over its simplex solver being less than half the speed of Alibaba's in the benchmarks.

Head-to-head as simplex solvers on "normal" problems, there's never been much difference in performance between Clp and HiGHS. That said, HiGHS simplex continues to improve and Clp won't. Support for Clp is declining as John ages and, eventually will cease.

**Comment by mdhaber** [comment]
Ok, we can reconsider those.
BTW the current plan is to work on adding the HiGHS MIP solver in December.

**Comment by mdhaber** [comment]
As promised: gh-15294.
A PR for a new `milp` function will follow.
