### ISSUE TITLE
optimize.root_scalar "converged" to the wrong root

### ISSUE THREAD

**Issue by mikeduan** [scipy/scipy#14453]
I encountered the following strange error in a calculation and I'm not sure why.

```
import numpy as np
from scipy.optimize import root_scalar

f = lambda x: 100*np.exp(-0.03*x)
sol = root_scalar(lambda x: f(x)-100, x0=150, x1=75)
assert sol.converged, "Cannot find the root."
sol.root, f(sol.root)-100
```

Obviously the root is 0, but `root_scalar` found it to be 150 and thought it had converged. I understand that the choices of x0 and x1 are not optimal, but I'm puzzled why `root_scalar` thought it had found the root.

#### Scipy/Numpy/Python version information:
`1.6.3 1.20.2 sys.version_info(major=3, minor=9, micro=4, releaselevel='final', serial=0)`

**Comment by tupui** [comment]
Hi @mikeduan, thank you for opening an issue. But this feel more like a question and we don't have the bandwidth for that here. I would suggest to ask on StackOverflow for instance. Still, if there is a bug, feel free to add more information.

As for your issue, the secant method is used when only provided with x0, x1 and a function. The secant method is not guaranteed to converge and in this case the starting points where quite far. I mean, just making a plot of your function and doing the method by hand and it's clear that you're troubling it.

<img width="685" alt="Screenshot 2021-07-22 at 20 16 05" src="https://user-images.githubusercontent.com/23188539/126689155-2212f568-f374-4b1f-a795-7c693b162cd6.png">

**Comment by mikeduan** [comment]
@tupui Thanks for the prompt reply! I'm not sure I would call it a bug, but it certainly surprised me. I thought that the algorithm would have checked if f(root) was indeed close to 0 before setting the converged flag 🙂

**Comment by tupui** [comment]
True although "close to 0" is very subjective. It converged to the right side due to the shape of the function and your starting points. This is a parametrization issue here.

**Comment by mikeduan** [comment]
@tupui Will it be a good idea for `root_scalar` (and probably `root` too) to have a `ytol` option so that the function will only report converged or successful when `abs(f(sol.root)) <= ytol` if `ytol` is set? It will simplify some codes and cause fewer surprises.

**Comment by tupui** [comment]
Why not. I will let `optimize` maintainers weight in for this. @pvanmulbregt @andyfaff what do you think about this?

**Comment by mdhaber** [comment]
@tupui @NuCO-UNM I agree with this suggestion. Please see my proposal for adding `fatol` (and probably `frtol`) in https://github.com/scipy/scipy/issues/6379#issuecomment-1364748484.
