### ISSUE TITLE
Passing a numpy array as sampling frequency to signal.iirfilter causes unexpected error message

### ISSUE THREAD

**Issue by yetinam** [scipy/scipy#14450]
My issue is about the interface for filter design. When passing a numpy array instead of a single float as fs to iirfilter (and derived filters), the function crashes with the error message: "Must specify a single critical frequency Wn for lowpass or highpass filter". While clearly the function should crash, the error message seems misleading, as indeed only one critical frequency was passed to the function.

As far as I can tell, this issue arises from the following line, because the division of a single critical frequency by an array of sampling rates will return an array of critical frequencies.
https://github.com/scipy/scipy/blob/12b77ad2e2d8ee766566e19d66845ca02e378ff4/scipy/signal/filter_design.py#L2374

I'd suggest to add an explicit check for the type of fs and raise a specific exception in case of wrong types.

#### Reproducing code example:

```
scipy.signal.butter(1, 1, "highpass", fs=np.array([10, 20]))
```

#### Error message:

```
Traceback (most recent call last)
<ipython-input-5-0f771327b56e> in <module>
----> 1 scipy.signal.butter(1, 1, "highpass", fs=np.array([10, 20]))

~/python3.8/site-packages/scipy/signal/filter_design.py in butter(N, Wn, btype, analog, output, fs)
   2953     >>> plt.show()
   2954     """
-> 2955     return iirfilter(N, Wn, btype=btype, analog=analog,
   2956                      output=output, ftype='butter', fs=fs)
   2957 

~python3.8/site-packages/scipy/signal/filter_design.py in iirfilter(N, Wn, rp, rs, btype, analog, ftype, output, fs)
   2431     if btype in ('lowpass', 'highpass'):
   2432         if numpy.size(Wn) != 1:
-> 2433             raise ValueError('Must specify a single critical frequency Wn for lowpass or highpass filter')
   2434 
   2435         if btype == 'lowpass':

ValueError: Must specify a single critical frequency Wn for lowpass or highpass filter

```

#### Scipy/Numpy/Python version information:

1.6.2 1.20.2 sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @yetinam, thanks for finding this 😃  You are right, the input validation is not correct here. Would you like to propose a PR to fix it?

**Comment by yetinam** [comment]
Hi @tupui , thanks for the quick reply. I'll propose a PR to fix it.
