### ISSUE TITLE
Possible bug in Mann Whitney U p-value computation?

### ISSUE THREAD

**Issue by michaellindon** [scipy/scipy#14469]
No matter how many times I simulate from the null distribution, the p-value never exceeds 0.5 - is there a possible factor of 2 missing?

Here is the code to reproduce:

```
from scipy.stats import gamma, mannwhitneyu


print(max([mannwhitneyu(x,y)[1] for x,y in zip([gamma(10,10).rvs(100) for _ in range(0, 1000)], [gamma(10,10).rvs(100) for _ in range(0, 1000)])]))
```

The above code simulates 1000 experiments, each experiment contains two datasets, each dataset is 100 samples from a gamma(10,10) distribution. The output printed for me is `0.49951261455397133`.

As another example I found this old [thread](https://stats.stackexchange.com/questions/259112/interpretation-of-p-value-in-mann-whitney-rank-test). The OP achieves the result `MannwhitneyuResult(statistic=73.5, pvalue=0.95291544831453867)`. Using the same data I get the result `MannwhitneyuResult(statistic=70.5, pvalue=0.47645772415726934)`.

My Scipy version is 1.6.3 and python version is
```
3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:36:15) 
[Clang 11.1.0 ]
```

**Comment by mdhaber** [comment]
Prior to 1.7.0, use of `mannwhitneyu` without an `alternative` argument was deprecated. The documentation explains the unusual behavior you're seeing.

https://docs.scipy.org/doc/scipy-1.6.3/reference/generated/scipy.stats.mannwhitneyu.html#scipy.stats.mannwhitneyu

Not sure about that old thread, but try upgrading to 1.7.0. `mannwhitneyu` was rewritten, and now use without an `alternative` is allowed again, defaulting to a two-sided test.
