### ISSUE TITLE
Shapiro test returning negative p-value

### ISSUE THREAD

**Issue by Pokala15** [scipy/scipy#14462]
My issue is about logical error while running shapiro test

#### Reproducing code example:

```
>>> from scipy import stats
>>> trans_val, maxlog = stats.boxcox([122500,474400,110400])
>>> stats.shapiro(trans_val)
ShapiroResult(statistic=0.08333337306976318, pvalue=-1.4407120943069458)

```
#### Error message:
The correct range of p-value should be [0,1]. The sample shown above is giving negative p-value which is incorrect.

#### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.7.0 1.19.1 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment]
It looks like `trans_val` has range approximately zero:
```
>>> (trans_val.max() - trans_val.min())/trans_val.min()
 5.7469895570330386e-08
```
which is problematic for many stats functions. In the `shapiro` code:
```python3
    a, w, pw, ifault = statlib.swilk(y, a[:N//2], init)
    if ifault not in [0, 2]:
        warnings.warn("Input data for shapiro has range zero. The results "
                      "may not be accurate.")
```
but this is not getting triggered.

In the underlying `swilk.f`, there is:
```fortran
      IFAULT = 6
      RANGE = X(N1) - X(1)
      IF (RANGE .LT. SMALL) RETURN
```
where
```fortran
      DATA SQRTH /0.70711E0/, QTR/0.25E0/, TH/0.375E0/, SMALL/1E-19/
```
Without knowing Fortran, `SMALL` seems to be defined as `1e-19`, which is indeed smaller than the range we have. Yet the function is still not accurate.

My guess is that we won't be able to return the correct p-value here very soon, unless someone wants to dive into the Fortran or re-implement the test in Python. 

In the meantime, what would you suggest? Maybe check for the p-value in the valid range and raise an error if it's outside? I don't think clipping is appropriate, because the correct p-value here is probably not zero. (There is so little data, and it's degenerate, so I don't think the correct p-value would point toward rejecting the null hythosis of normality.) R's `shapiro.test` reports `0.2805581778133`:
```R
options(digits=16)
x = c(0.7021304129042957, 0.7021304469039881, 0.7021304065526269)
shapiro.test(x)
```

**Comment by josef-pkt** [comment]
subtract mean, 
I think test statistic should theoretically be invariant to mean

```
from scipy import stats
trans_val, maxlog = stats.boxcox([122500,474400,110400])
stats.shapiro(trans_val - trans_val.mean())
ShapiroResult(statistic=0.8646843433380127, pvalue=0.2805574834346771)
```

**Comment by josef-pkt** [comment]
having a tiny coefficient of variation often causes large deterioration in numerical precision

**Comment by Pokala15** [comment]
I suppose the solution could be like this
In the [shapiro code](https://github.com/scipy/scipy/blob/v1.7.0/scipy/stats/morestats.py#L1689-L1762)
```
    a, w, pw, ifault = statlib.swilk(y, a[:N//2], init)
    if ifault not in [0, 2]:
        warnings.warn("Input data for shapiro has range zero. The results "
                      "may not be accurate.")
```
it's is calling statlib.swilk, In this after [line 172](https://github.com/scipy/scipy/blob/master/scipy/stats/statlib/swilk.f#L172  ) there should be if condition for checking negative values like 
```
IF (PW .LT. 0) THEN
    PW = 0
```
taking reference from [here](http://ftp.stjude.org/pub/software/JUMPm/labeled/R-3.1.0/src/library/stats/src/swilk.c)

**Comment by mdhaber** [comment]
We'd do an out of range check in Python.

Interesting @josef-pkt . The [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.shapiro.html) shows an example with nonzero mean, so it sounds like it isn't supposed to matter. Would you recommend subtracting the mean before passing the data to `swilk`?

**Comment by josef-pkt** [comment]
Nonzero mean is no problem if the variation is large enough compare to it. But if mean is huge compared to variation, then some computation get imprecise. 

I only have examples in other contexts and don't know or remember the details for shapiro-wilk, so I don't know which computation cause the numerical problem.

> Would you recommend subtracting the mean before passing the data to swilk?

I think that would be good. Fixes or improves precision for these kind of issues.
It's possible to make it conditional on a small relative range as in your example, but just unconditionally removing the mean is simpler.

**Comment by josef-pkt** [comment]
given that y is already sorted before going to the fortran code, it might be better to subtract the median (or next value close to it)

median would be robust to outliers compared to mean
