### ISSUE TITLE
scipy.interpolate.CubicSpline boundary conditions appear to be incorrect

### ISSUE THREAD

**Issue by shusheer** [scipy/scipy#14472]
scipy.interpolate.CubicSpline allows for a series of boundary conditions in bc_type. These do not appear to be respected.

For example, 'natural' should result in second derivative being zero outside the x-values of the data, whilst 'clamped' should result in the first derivative being zero outside this range.

There is some difference between the splines generated with each setting of boundary condition, but the derivatives do not match the description.

#### Reproducing code example:
```
import matplotlib.pyplot as plt

import numpy as np

from scipy.interpolate import CubicSpline

xs = [1,2,3,4,5,6,7,8]
ys = [4.5, 3.6, 1.6, 0.0, -3.3, -3.1, -1.8, -1.7]

notaknot_smoother = CubicSpline(xs,ys, bc_type='not-a-knot')

natural_smoother = CubicSpline(xs,ys, bc_type='natural')

clamped_smoother = CubicSpline(xs,ys, bc_type='clamped')

extrapolated = np.linspace(min(xs)-10,max(xs)+10,int(21+(max(xs)-min(xs))))

fig, axs = plt.subplots(3, 3,figsize=(12,12))
axs[0, 0].plot(xs, ys,'.')
axs[0, 0].plot(extrapolated,notaknot_smoother(extrapolated),'-')
axs[0, 0].set_title('not-a-knot, deriv=0')
axs[0, 1].plot(xs, ys,'.')
axs[0, 1].plot(extrapolated,natural_smoother(extrapolated),'-')
axs[0, 1].set_title('natural, deriv=0')
axs[0, 2].plot(xs, ys,'.')
axs[0, 2].plot(extrapolated,clamped_smoother(extrapolated),'-')
axs[0, 2].set_title('clamped, deriv=0')
axs[1, 0].plot(xs, notaknot_smoother(xs,nu=1),'.')
axs[1, 0].plot(extrapolated,notaknot_smoother(extrapolated,nu=1),'-')
axs[1, 0].set_title('not-a-knot, deriv=1')
axs[1, 1].plot(xs, natural_smoother(xs,nu=1),'.')
axs[1, 1].plot(extrapolated,natural_smoother(extrapolated,nu=1),'-')
axs[1, 1].set_title('natural, deriv=1')
axs[1, 2].plot(xs, clamped_smoother(xs,nu=1),'.')
axs[1, 2].plot(extrapolated,clamped_smoother(extrapolated,nu=1),'-')
axs[1, 2].set_title('clamped, deriv=1')
axs[2, 0].plot(xs, notaknot_smoother(xs,nu=2),'.')
axs[2, 0].plot(extrapolated,notaknot_smoother(extrapolated,nu=2),'-')
axs[2, 0].set_title('not-a-knot, deriv=2')
axs[2, 1].plot(xs, natural_smoother(xs,nu=2),'.')
axs[2, 1].plot(extrapolated,natural_smoother(extrapolated,nu=2),'-')
axs[2, 1].set_title('natural, deriv=2')
axs[2, 2].plot(xs, clamped_smoother(xs,nu=2),'.')
axs[2, 2].plot(extrapolated,clamped_smoother(extrapolated,nu=2),'-')
axs[2, 2].set_title('clamped, deriv=2')
plt.show()
```

#### Scipy/Numpy/Python version information:

Confirmed in both these versions:

1.5.4 1.19.5 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)

1.7.0 1.21.1 sys.version_info(major=3, minor=8, micro=0, releaselevel='final', serial=0)

**Comment by ev-br** [comment]
> For example, 'natural' should result in second derivative being zero outside the x-values of the data, whilst 'clamped' should result in the first derivative being zero outside this range.

I think this expectation is too strong. The guarantee is only that the boundary conditions fix the derivative value *at* the boundary, and that seems to work:

```
xs = [1,2,3,4,5,6,7,8]
ys = [4.5, 3.6, 1.6, 0.0, -3.3, -3.1, -1.8, -1.7]

spl = CubicSpline(xs, ys, bc_type='clamped')
spl([xs[0], xs[-1]], nu=1)
```
prints `array([0., 0.])`. However the second derivative is not guaranteed to be zero, since extrapolation is done by extending the first/last polynomial piece of the spline, whatever it happens to be. 

For example, consider a cubic spline with three breakpoints (two intervals) and `natural` BCs. To have linear extrapolation, both spline pieces need to be linear, and this does not allow C^2 smoothness at the internal breakpoint. 

This behavior is only mentioned in the docstring, at the "extrapolate" parameter, `If bool, determines whether to extrapolate to out-of-bounds points based on first and last intervals`, which is cryptic indeed. A doc PR to clarify this will be gratefully accepted. Also, this may be a great addition to the interpolate tutorial (which is missing CubicSpline altogether, and in general needs some work --- help is appreciated).

If you need to enforce a specific extrapolation form, you'd probably need to do it in the user code, in a subclass or a wrapper, depending on how it's structured.

**Comment by shusheer** [comment]
Thanks for clarifying this behavior. Would a simple way to enforce the stronger expectation be to add an additional breakpoint at each end, some infinitesimal distance from the existing ones, with the polynomial coefficients that one would wish to use for extrapolation? I can see a potential downside here in that the breakpoints now do not exactly match the initially supplied datapoints, but it does make extrapolation substantially more robust. Perhaps a parameter to select this behavior would be desirable, avoiding users having to subclass/wrap for what is presumably the expected behaviour of extrapolation when a boundary condition is specified.

**Comment by ev-br** [comment]
This can probably work --- not sure if it's simpler than just masking the out-of-bounds values --- but it's a judgement call here. Either way, I believe this belongs to downstream code, not scipy.interpolate itself. 

The reason is exactly what you mention: currently CubicSpline has a simple and easy to understand invariant that interpolation knots are exactly at the data points, and adding more to it is probably too much. 

Your trick --- and it's a nice one! --- can probably be a nice example in the interpolate tutorial or scipy cookbook or maybe even scipy lecture notes. We only control the tutorial, and I'd be happy to review a PR with this example (can't speak for the other ones).

**Comment by shusheer** [comment]
Ok, here are two functions for adding the additional knots for clamped and natural boundary conditions, and a copy of my test code above showing that these work as intended. Let me know if this seems acceptable.

```
import matplotlib.pyplot as plt

import numpy as np

from scipy.interpolate import CubicSpline

def add_natural_boundary(spline):
    leftx = spline.x[0]
    leftxnext = np.nextafter(leftx, leftx-1)
    lefty = spline(leftx)
    leftslope = spline(leftx,nu=1)
    leftynext = lefty+leftslope*(leftxnext-leftx)
    leftcoeffs = np.array([0,0,leftslope,leftynext])
    spline.extend(leftcoeffs[...,None],np.r_[leftxnext])
    rightx = spline.x[-1]
    rightxnext = np.nextafter(rightx, rightx+1)
    righty = spline(rightx)
    rightslope = spline(rightx,nu=1)
    rightynext = righty+rightslope*(rightxnext-rightx)
    rightcoeffs = np.array([0,0,rightslope,rightynext])
    spline.extend(rightcoeffs[...,None],np.r_[rightxnext])
    return

def add_clamped_boundary(spline):
    leftx = spline.x[0]
    leftxnext = np.nextafter(leftx, leftx-1)
    lefty = spline(leftx)
    leftcoeffs = np.array([0,0,0,lefty])
    spline.extend(leftcoeffs[...,None],np.r_[leftxnext])
    rightx = spline.x[-1]
    rightxnext = np.nextafter(rightx, rightx+1)
    righty = spline(rightx)
    rightcoeffs = np.array([0,0,0,righty])
    spline.extend(rightcoeffs[...,None],np.r_[rightxnext])
    return

xs = [1,2,3,4,5,6,7,8]
ys = [4.5, 3.6, 1.6, 0.0, -3.3, -3.1, -1.8, -1.7]

notaknot_smoother = CubicSpline(xs,ys, bc_type='not-a-knot')
# not-a-knot does not require additional boundary conditions for extrapolation

natural_smoother = CubicSpline(xs,ys, bc_type='natural')
# extend natural_smoother with linear extrapolating knots
add_natural_boundary(natural_smoother)

clamped_smoother = CubicSpline(xs,ys, bc_type='clamped')
# extend clamped_smoother with constant extrapolating knots
add_clamped_boundary(clamped_smoother)

extrapolated = np.linspace(min(xs)-10,max(xs)+10,int(21+(max(xs)-min(xs))))

fig, axs = plt.subplots(3, 3,figsize=(12,12))
axs[0, 0].plot(xs, ys,'.')
axs[0, 0].plot(extrapolated,notaknot_smoother(extrapolated),'-')
axs[0, 0].set_title('not-a-knot, deriv=0')
axs[0, 1].plot(xs, ys,'.')
axs[0, 1].plot(extrapolated,natural_smoother(extrapolated),'-')
axs[0, 1].set_title('natural, deriv=0')
axs[0, 2].plot(xs, ys,'.')
axs[0, 2].plot(extrapolated,clamped_smoother(extrapolated),'-')
axs[0, 2].set_title('clamped, deriv=0')
axs[1, 0].plot(xs, notaknot_smoother(xs,nu=1),'.')
axs[1, 0].plot(extrapolated,notaknot_smoother(extrapolated,nu=1),'-')
axs[1, 0].set_title('not-a-knot, deriv=1')
axs[1, 1].plot(xs, natural_smoother(xs,nu=1),'.')
axs[1, 1].plot(extrapolated,natural_smoother(extrapolated,nu=1),'-')
axs[1, 1].set_title('natural, deriv=1')
axs[1, 2].plot(xs, clamped_smoother(xs,nu=1),'.')
axs[1, 2].plot(extrapolated,clamped_smoother(extrapolated,nu=1),'-')
axs[1, 2].set_title('clamped, deriv=1')
axs[2, 0].plot(xs, notaknot_smoother(xs,nu=2),'.')
axs[2, 0].plot(extrapolated,notaknot_smoother(extrapolated,nu=2),'-')
axs[2, 0].set_title('not-a-knot, deriv=2')
axs[2, 1].plot(xs, natural_smoother(xs,nu=2),'.')
axs[2, 1].plot(extrapolated,natural_smoother(extrapolated,nu=2),'-')
axs[2, 1].set_title('natural, deriv=2')
axs[2, 2].plot(xs, clamped_smoother(xs,nu=2),'.')
axs[2, 2].plot(extrapolated,clamped_smoother(extrapolated,nu=2),'-')
axs[2, 2].set_title('clamped, deriv=2')
plt.show()
```

**Comment by ev-br** [comment]
Completely missed the last message here @shusheer --- this would indeed be a nice example to add to the tutorial. I'm looking forward for a PR!

**Comment by ev-br** [comment]
https://github.com/scipy/scipy/pull/17299 contains the example from https://github.com/scipy/scipy/issues/14472#issuecomment-900668526. @shusheer do you want me to add you as a co-author of the relevant commit? I'll then need an email address to properly format the co-authored-by entry.

**Comment by shusheer** [comment]
Sure, I'm username s.husheer at the gmail domain (tortured method of giving it, to hamper spambots ;)

**Comment by ev-br** [comment]
Okay, done: https://github.com/scipy/scipy/pull/17299/commits/521e421d8f2b05a742651c1ca806f36e0b22a0ce

**Comment by j-bowhay** [comment]
@ev-br I appreciate this is slightly more effort at your end but you don't actually need to know someones true email address to add them as a coauthor: https://youtu.be/_-qNX8EbVYI?t=222
