### ISSUE TITLE
Azure CI jobs do not set exit status for build stage correctly

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#14482]
Example: https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=13208&view=logs&j=9ae1e178-a5f4-5daa-ec3c-fcbf39c6865a&t=85635e71-f6a7-533b-0837-ec61d4bb6072

The "Build SciPy" stage is green, but it failed. The "Run SciPy Test Suite" is red, because it's failing with a hard to parse import error (due to the build not succeeded). This is the offending line:
```
pip wheel --no-build-isolation -v -v -v --wheel-dir=dist .
```
That command should be setting exit code correctly. Or maybe it is, and there's a `set -ex` or some such thing missing.

**Comment by tylerjereddy** [comment]
yeah, this came up before--I have a stagnant PR I started in March: https://github.com/scipy/scipy/pull/13752

Can probably just lift settings from another project if that's not on target.

**Comment by rgommers** [comment]
The issue is that in Azure the default behavior is pretty useless: failing commands do not fail the job step if they are not the last command in a multiline script (see https://github.com/Microsoft/azure-pipelines-yaml/issues/135). 

Explicitly checking the output status looks like the way to go. From https://stackoverflow.com/questions/55194446/how-do-i-get-my-azure-devops-pipeline-build-to-fail-when-my-linting-script-retur:
```
    if [ $? -ne 0 ]; then
        exit 1
    fi
```
