### ISSUE TITLE
Finding roots on a subset of R using root_scalar with derivative-based methods 

### ISSUE THREAD

**Issue by MerlinDumeur** [scipy/scipy#14495]
Hello,

I have a function, which I know has a root in a specific interval, and I need to find that root.
I also have the first and second order derivatives of that function.
However the function and its derivatives are undefined (it computes a log of zero) for multiple values outside of the search interval.
I need to be able to call scipy.optimize.root_scalar with a derivative-based method so that it only calls my function on values which are defined (ideally within my search interval).

Right now I can solve my problem by using bracketing methods but they are very slow and I would like to be able to use the information from the derivatives.

It is mentioned in the documentation:
>The derivative-based methods, all built on newton, can converge quite quickly if the initial value is close to the root. They can also be applied to functions defined on (a subset of) the complex plane.

However I could not figure out how to do it.

**Comment by tupui** [comment]
Hi, sorry but we cannot provide user support for questions. Please try StackOverflow for instance. If there is an issue, feel free to come back here and I would re-open this.
