### ISSUE TITLE
MAINT: Sparse matrices: switch the API to produce arrays and not np.matrix

### ISSUE THREAD

**Issue by akhmerov** [scipy/scipy#14497]
**Is your feature request related to a problem? Please describe.**

This is a continuation of the reasoning of #14494. Many sparse matrix methods return a `numpy.matrix`. An offender that I found includes `.sum(axis=i)`, but there are likely more.

**Describe the solution you'd like**

I believe that when reasonable these methods should return a 1D numpy array, however a 2D array with shape 1×N or N×1 for backwards compatibility is also an option.

What I am not quite sure about is whether this should follow a deprecation cycle, and if yes, what should be the course of action.

**Comment by stefanv** [comment]
Addressed in #14822
