### ISSUE TITLE
`Optimization converged to parameters that are outside the range` should be a `ValueError`

### ISSUE THREAD

**Issue by csala** [scipy/scipy#14505]
**Is your feature request related to a problem? Please describe.**

`scipy` 1.7.0 introduced a validation of the parameters learned by the stats distributions. When the validation fails, the code raises a plain `Exception`:

```python3
>>> import numpy as np
>>> from scipy.stats import beta
>>> 
>>> vector = np.concatenate([np.zeros(29), np.ones(21)])
>>> beta.fit(vector)
.../scipy/optimize/minpack.py:175: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)
.../scipy/optimize/optimize.py:761: RuntimeWarning: invalid value encountered in subtract
  np.max(np.abs(fsim[0] - fsim[1:])) <= fatol):
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../scipy/stats/_continuous_distns.py", line 62, in wrapper
    return fun(self, *args, **kwds)
  File ".../scipy/stats/_continuous_distns.py", line 662, in fit
    return super().fit(data, *args, **kwds)
  File ".../scipy/stats/_distn_infrastructure.py", line 2505, in fit
    raise Exception("Optimization converged to parameters that are "
Exception: Optimization converged to parameters that are outside the range allowed by the distribution.
```

**Describe the solution you'd like**

Since the problem is that the values are not valid for the current distribution, I think that raising a `ValueError` would be better.

**Additional context (e.g. screenshots)**

This error was discovered because the `Exception` escaped an `except ValueError` statement that was previously able to capture all the fit errors, which means that `ValueError` is probably the optimal exception type and what other implementations may also be expecting. See https://github.com/sdv-dev/Copulas/issues/264 for reference.

**Comment by mdhaber** [comment]
Oops, I don't think we meant to return a plain `Exception` there. 

`ValueError` suggests to me that there is something wrong with the user's values. Really, the user's input may be fine, but the algorithm is not doing what is expected. That seems like a conceptually distinct type of exception, to me. Do you think that distinction is important, or do you think it is ok to be liberal about the use of `ValueError`?

**Comment by mdhaber** [comment]
PR welcome!
