### ISSUE TITLE
Generalize student's t to real-valued degrees of freedom

### ISSUE THREAD

**Issue by HDembinski** [scipy/scipy#14512]
The current implementation (v1.7) of the student's t distribution in scipy supports only integer values of the degrees of freedom parameter `df` for the cdf and inverse of the cdf.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.t.html

The implementation of the pdf formula is already valid for real values of `df`. The cdf implementation calls `stdtr` from scipy.special which maps to https://github.com/scipy/scipy/blob/master/scipy/special/cephes/stdtr.c#L92, which supports only integer values of `df`.

The implementation of `stdtr` based on the regularised incomplete beta function already supports real-valued `df`, but it is only used from -oo to t=-2. Only for -2 < t < 0 it uses an implementation that relies on `df` being an integral value.

According to my numerical experiments, the implementation based on the regularised incomplete beta function can be used over the full range -oo < t < 0, so the extension should be trivial.

I want to add that the documentation of https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.t.html does not mention that the cdf is only valid for integer values of `df`, neither is this mentioned here https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.stdtr.html#scipy.special.stdtr.

You may ask why this is needed. It turns out that the shifted and rescaled student's t distribution with a real-valued `df` is a suitable empirical fitting function for peaks in the invariant mass distribution of particle decays in high energy physics. A paper that uses this technique is https://arxiv.org/abs/2107.10090

**Update:** Despite of what I found from reading the source code and looking at the scipy tests, it seems that scipy actually does support real values for `df`.

```
from scipy.special import stdtr

stdtr(1, 1)
# 0.7500000000000002

stdtr(2, 1)
# 0.7886751345948129

stdtr(1.5, 1)
# 0.7744323163616447
```

I don't fully understand what code is called then, but it seems to be https://github.com/scipy/scipy/blob/master/scipy/special/cdflib/cdft.f, which apparently supports real values for `df` (my FORTRAN is a little rusty). If that's the case and calling `stdtr` with real values for `df` is officially supported, this issue can be closed - although it would be great to stress a bit more in the documentation that real values for `df` are supported.

**Comment by rkern** [comment]
You can find the mapping in [`functions.json`](https://github.com/scipy/scipy/blob/master/scipy/special/functions.json). We used to use the Cephes implementation, hence the name, but switched to CDFLIB afterwards.

PRs are welcome to add the desired emphasis in the docstring.
