### ISSUE TITLE
CI: Azure pipelines don't appear to be running

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#14529]
see e.g. https://dev.azure.com/scipy-org/SciPy/_build?definitionId=1

I'm getting the following message from CI on my fork:

> /azure-pipelines.yml: (Line: 343, Col: 7, Idx: 12071) - (Line: 343, Col: 7, Idx: 12071): While scanning a simple key, could not find expected ':'.

**Comment by andyfaff** [comment]
@rgommers

**Comment by tupui** [comment]
I think we are getting this error since #14492 got in. I propose to click revert for now. Is this how we should do @rgommers?

```
      # The below 3 lines ensure exit status of every line in this step is checked
      Set-StrictMode -Version Latest
      $ErrorActionPreference = "Stop"
      $PSDefaultParameterValues['*:ErrorAction']='Stop'
```

**Comment by tylerjereddy** [comment]
I'd say feel free to revert temporarily if you think it will restore Azure CI runs for now, and then either open a new issue or re-open the old one and add a comment about this observation so we can come back to it.

One of us can debug on a fork if needed when we get time.

**Comment by rgommers** [comment]
Yes, it's always fine to revert something if it broke CI and it's not immediately clear how to fix. Reverting is not a "this was all terrible" but more "this wasn't 100% right so let's try once more".
