### ISSUE TITLE
filter frequency response appears to be wrong

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [scipy/scipy#14537]
When I attempted to use the code below to design a lowpass filter, I got a frequency response that is quite different from what was expected.  Possibly my inputs are wrong, but in this case it would be nice to have better error checking in SciPy.  Note that there is too much variation in the passband and insufficient rejection in the stopband.

```
from matplotlib import pyplot as plt
import numpy as np
from numpy import log10, pi
from scipy import signal

b, a= signal.iirfilter(16, Wn=0.2, rp=0.1, rs=40, btype='lowpass', ftype='ellip',
  analog=False)
w, h= signal.freqs(b, a, 1000)
fig= plt.figure()
ax= fig.add_subplot(1, 1, 1)
ax.semilogx(w / (2*pi), 20 * log10(np.maximum(abs(h), 1e-5)))
ax.set_title('Elliptic filter lowpass frequency response')
ax.set_xlabel('Frequency')
ax.set_ylabel('Amplitude [dB]')
# ax.axis((10, 1000, -100, 10))
ax.grid(which='both', axis='both')
plt.show()
```

#### Scipy/Numpy/Python version information:
```
1.6.1 1.19.2 sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)
```

**Comment by rkern** [comment]
[`freqs()`](https://scipy.github.io/devdocs/reference/generated/scipy.signal.freqs.html) is for analog filters. Use [`freqz()`](https://scipy.github.io/devdocs/reference/generated/scipy.signal.freqz.html) for this digital filter.

**Comment by Phillip-M-Feldman** [comment]
I'm now using freqz.  Thanks!  With this change, I'm still seeing frequency
responses that don't make sense.  E.g.,for the Butterworth filter defined
below, `freqz` reports a flat frequency response.

```
from matplotlib import pyplot as plt
import numpy as np
from numpy import log10, pi
from scipy import signal

b, a= signal.butter(20, Wn=20e6, btype='low', analog=False, fs=5.2e9)
w, h = signal.freqz(b, a, worN=4096)
fig= plt.figure()
ax= fig.add_subplot(1, 1, 1)
ax.semilogx(w / (2*pi), 20 * log10(np.maximum(abs(h), 1e-5)))
ax.set_title('Lowpass filter frequency response')
ax.set_xlabel('Frequency')
ax.set_ylabel('Amplitude [dB]')
# ax.axis((10, 1000, -100, 10))
ax.grid(which='both', axis='both')
plt.savefig('Lowpass filter frequency response.png')
plt.show()
```

**Comment by rkern** [comment]
I think the `ba` representation starts to have numerical problems at higher orders, around 9 or so. Switching to `output='sos'` and using `sosfreqz()` seems to handle the higher order that you are asking for.

```
fs = 5.2e9
sos = signal.butter(20, Wn=20e6, btype='low', analog=False, fs=fs, output='sos')
w, h = signal.sosfreqz(sos, worN=4096, fs=fs)
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.semilogx(w, 20 * log10(np.maximum(abs(h), 1e-5)))
ax.set_title('Lowpass filter frequency response')
ax.set_xlabel('Frequency')
ax.set_ylabel('Amplitude [dB]')
ax.grid(which='both', axis='both')
```

The "flat" frequency response that you saw was an artifact of your clipping to 1e-5. The full `abs(h)` shows an appropriate shape, but with the `ba` representation, numerical errors depressed the overall gain.

**Comment by Phillip-M-Feldman** [comment]
Thank you!
