### ISSUE TITLE
Add convention flag to quanternion in `Scipy.spatial.transform.rotation.Rotation`

### ISSUE THREAD

**Issue by ManuelPalermo** [scipy/scipy#14548]
**Is your feature request related to a problem? Please describe.**

`Scipy.spatial.transform.rotation.Rotation` uses scalar-last (xyzw) quaternion convention, however most [libraries/literature](https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation#Alternative_conventions) use scalar-first (wxyz).

**Describe the solution you'd like**
I propose adding an optional argument to `from_quat()` and `as_quat()` methods to specify the convention used.

In case of "wxyz" convention is passed to `from_quat()`, the quaternion array can be reorder to correctly perform internal operations:

```python
def from_quat(cls, quat, convention="xyzw"):
    if convention == "xyzw":
        return cls(quat, normalize=True)
    elif convention == "wxyz":  # convert to "xyzw" for implemented methods
        return cls(quat[..., [1,2,3,0]], normalize=True)
```

In the case of `as_quat()` the quaternion array is reordered before output:

```python
def as_quat(self, convention="xyzw"):
    if self._single:
        _quat = np.array(self._quat[0], copy=True)
    else:
        _quat = np.array(self._quat, copy=True)

    if convention == "xyzw":
        return _quat
    elif convention == "wxyz":  # convert to "wxyz" for output
        return _quat[..., [3,0,1,2]]
```

**Describe alternatives you've considered**

**Additional context (e.g. screenshots)**

**Comment by ManuelPalermo** [comment]
I did not look for long at the code, but at a first glance the changes needed seem minimal and don't break anything. I can also submit a pull request once a solution is approved.

**Comment by alspitz** [comment]
Since this seems to have gotten reverted: +1 I would find this very useful. Since Rotation objects can intake many different rotation formats: rotation matrix, Euler angles of different conventions, etc., it seems natural for Rotation objects to also accept quaternions in different conventions even if it's a simple re-ordering of the axes.

Since there are really only two options, w-first and w-last, it may be simpler to just have a scalar_last keyword argument that defaults to true.

**Comment by jmw182** [comment]
@tupui is it possible to reopen this issue? Or @pmla is it possible to reopen your PR #15410 ?

It seems like the work to add this feature was more-or-less complete but never merged. I would also find this very useful!
