### ISSUE TITLE
BUG: Failure to create sparse matrix on PPC

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#14560]
This is from https://github.com/conda-forge/osqp-feedstock/pull/39, happens both with openblas & netlib backends. Scipy version 1.7.1, numpy 1.21.1.

Minimal example directly from osqp test suite:
```python
import scipy
from scipy import sparse
scipy.random.seed(1)
sparse.random(5, 5, density=0.7)
```

fails with

```
[...]/lib/python3.8/site-packages/osqp/tests/update_matrices_test.py:23:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
[...]/lib/python3.8/site-packages/scipy/sparse/construct.py:813: in random
    return coo_matrix((vals, (i, j)), shape=(m, n)).asformat(format,
[...]/lib/python3.8/site-packages/scipy/sparse/coo.py:196: in __init__
    self._check()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <5x5 sparse matrix of type '<class 'numpy.float64'>'
        with 18 stored elements in COOrdinate format>

    def _check(self):
        """ Checks data structure for consistency """

        # index arrays should have integer data types
        if self.row.dtype.kind != 'i':
            warn("row index array has non-integer dtype (%s)  "
                    % self.row.dtype.name)
        if self.col.dtype.kind != 'i':
            warn("col index array has non-integer dtype (%s) "
                    % self.col.dtype.name)

        idx_dtype = get_index_dtype(maxval=max(self.shape))
        self.row = np.asarray(self.row, dtype=idx_dtype)
        self.col = np.asarray(self.col, dtype=idx_dtype)
        self.data = to_native(self.data)

        if self.nnz > 0:
            if self.row.max() >= self.shape[0]:
>               raise ValueError('row index exceeds matrix dimensions')
E               ValueError: row index exceeds matrix dimensions
```

Same thing for  `scipy.sparse.random(100, 200, density=0.9, format='csc')`,

**Comment by tupui** [comment]
I did not test this with PPC, but I have 2 comments:
* `scipy.random.seed` please don't do this. We are removing all code that rely on global seed as per NumPy's own recommendation. Also I would not advise to use NumPy from SciPy's namespace...
* SciPy sub-packages need to be imported separately: `from scipy import sparse`. I am not sure how this works as I cannot run your snippet.

**Comment by h-vetinari** [comment]
Thanks for taking a look!

I'm just packaging the library, it's not "my" code, which comes from [here](https://github.com/osqp/osqp-python/blob/v0.6.2/module/tests/update_matrices_test.py#L15-L23).

Indeed the import is done separately there; I had just tried to translate that function into a minimal example (without rerunning directly) - apologies.

**Comment by tupui** [comment]
> Thanks for taking a look!
> 
> I'm just packaging the library, it's not "my" code, which comes from [here](https://github.com/osqp/osqp-python/blob/v0.6.2/module/tests/update_matrices_test.py#L15-L23).
> 
> Indeed the import is done separately there; I had just tried to translate that function into a minimal example (without rerunning directly) - apologies.

No problem 😃 Just wanted to clarify these points.

**Comment by h-vetinari** [comment]
> Debugging something like this is difficult on developers personal machines.

Completely agreed. And the CI situation has become frankly atrocious with Travis, leading to questions like [these](https://github.com/conda-forge/scipy-feedstock/issues/171).

> Perhaps we should be raising a `DeprecationWarning` on `scipy.random.seed`.

Just a suspicion, but I'm pretty sure it's unrelated to `random.seed`, but to sparse matrices.

**Comment by rgommers** [comment]
Probably an emulation bug, this code is too simple to actually be broken specifically on PPC I'd think. Let's close it - if someone finds this problem on an actual PPC machine instead of on QEMU please reopen.
