### ISSUE TITLE
Problem with freeing-up memory of matrix

### ISSUE THREAD

**Issue by micstein89** [scipy/scipy#14586]
When performing a cholesky decomposition of a large matrix, freeing-up the memory of the resulting matrix leads to an "invalid pointer"-error (see below). When the example code is in a function, then the same error occurs at the end of the function also without the del-statement. The error only occurs for large covariance matrices. The size, where the error starts to occur, is depending on the type of computer node used. The error below occurs on piz daint at CSCS when using a covariance matrix larger than ca. 70000x70000. On other systems, the same code causes a Segmentation fault instead of this "invalid pointer"-error. 

#### Reproducing code example:

```
import numpy as np
from scipy.sparse import csr_matrix
from scipy.linalg import cholesky

covariancematrix = csr_matrix( np.identity(70000) )
C = cholesky(covariancematrix.toarray(), lower=True)
del C
```

#### Error message:

```
*** Error in `python3': free(): invalid pointer: 0x00002ab7b049c010 ***
```

#### Scipy/Numpy/Python version information:

```
Python  3.8.5
numpy  1.21.1
scipy  1.7.1
```

**Comment by czgdp1807** [comment]
It seems like a problem with too much memory being requested. This is probably leading to bad allocation, resulting in invalid pointer error or segmentation fault on python side. IMHO, adding a better error message in the underlying C-code (if any) should resolve the issue.

**Comment by ev-br** [comment]
Let's close this under an assumption that the origin is the same as in gh-20229. Feel free to reopen if the problem surfaces again.
