### ISSUE TITLE
Negative arguments for scipy.special.spherical_jn leads to nans

### ISSUE THREAD

**Issue by cw-tan** [scipy/scipy#14582]
`scipy.special.spherical_jn` seems to generate `nan`s for negative input arguments, which does not seem to be prohibited and the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.spherical_jn.html) does not seem to warn against. For example, the following code

```
import numpy as np
from scipy.special import spherical_jn

n = 5
zs = np.linspace(-5, 5, 10)
print(spherical_jn(n, zs))
```
yields an output of 
`[           nan            nan            nan            nan      nan 5.03098996e-06 1.11092345e-03 1.17516973e-02 4.66525179e-02 1.06811161e-01]`

Based on the reflection formula from [DLMF](http://dlmf.nist.gov/10.47.E14), I used the following fix for my purposes

```
import numpy as np
from scipy.special import spherical_jn

def spherical_bessel(n, z):
  return np.where(not isinstance(z, complex) and z<0, (-1)**n*spherical_jn(n, -z), spherical_jn(n, z))

zs = np.linspace(-5, 5, 10)
print(spherical_bessel(n, zs))
```
which gave the result
`[-1.06811161e-01 -4.66525179e-02 -1.17516973e-02 -1.11092345e-03
 -5.03098996e-06  5.03098996e-06  1.11092345e-03  1.17516973e-02
  4.66525179e-02  1.06811161e-01]`

I suspect that a similar, but more general fix can be used for a PR if this is deemed a legitimate issue. 

(I'm using Python 3.7.7, numpy-1.21.1 and scipy-1.7.1)

**Comment by czgdp1807** [comment]
I can look into this. Probably the issue might be somewhere deeper. Please let me know.

**Comment by cw-tan** [comment]
That would be great, thanks!

**Comment by czgdp1807** [comment]
I see that there aren't any functions for `h1`, `h2`, and `i2`. Should we add them? What are your thoughts @cw-tan ?

**Comment by cw-tan** [comment]
@czgdp1807 Although it doesn't seem necessary, adding them seems nice for completeness and would be good if users need them. They also seem easy to implement by calling existing scipy.special functions, which is what a user who needs them would do anyway.

**Comment by czgdp1807** [comment]
Thanks. Yeah, it seems like that's why they weren't added originally. The PR linked is ready then.
