### ISSUE TITLE
DOC: toolchain updates and max Python

### ISSUE THREAD

**Issue by tupui** [scipy/scipy#14585]
In the current toolchain [roadmap](https://scipy.github.io/devdocs/dev/toolchain.html#numpy) page, I find the information regarding Python versions confusing as the last versions of SciPy are not listed and also there is no information about the max Python version for a given version of SciPy.

I propose to change the table with the following columns:

SciPy version | Python versions | NumPy versions
-- | -- | --
1.7 | >3.7, <=3.10 | >=1.16.5, >= 1.20.x

Right now, I am not sure for most items about the max Python version. This should also answer: should we drop Python 3.7 for 1.8? Same goes for NumPy 1.16.5.

**Comment by rgommers** [comment]
The update seems fine.

>  This should also answer: should we drop Python 3.7 for 1.8? 

Yes. NumPy already dropped 3.7 in its `main` branch.

**Comment by tupui** [comment]
Thanks @rgommers, then can you then confirm the following?

SciPy version | Python versions | NumPy versions
-- | -- | --
1.2 | >=2.7, <=3.7 | >=1.8.2, <= 1.16.x
1.4 | >=3.5, <=3.8 | >=1.13.3, <= 1.18.x
1.5 | >=3.6, <=3.9 | >=1.14.5, <= 1.19.x
1.6 | >=3.7, <=3.9 | >=1.14.5, <= 1.20.x
1.7 | >=3.7, <=3.10 | >=1.16.5, >= 1.21.x
1.8 | >=3.8, <=3.10 | >=1.17.3, >= 1.21.x

Also if this is correct, shall we send an email to the mailing list to say we are dropping 3.7 and also updating NumPy to 1.17.x? With the latter, we could finally clean `check_random_state` which would generate discussion around the global seeding...

**Comment by rgommers** [comment]
That does not look 100% correct. Just looking at 1.7 and 1.8, here's what it should be I think:

SciPy version | Python versions | NumPy versions
-- | -- | --
1.7.0/1 | >=3.7, <3.10 | >=1.16.5, <1.23.0
1.7.2-x | >=3.7, <3.11 | >=1.16.5, <1.24.0
1.8 | >=3.8, <3.11 | >=1.17.3, <1.24.x

The older ones also don't quite look correct. There's also the issue that the actual releases before 1.7 do not have correct upper bounds, so I'm not sure it's helpful to have them in the docs.

**Comment by tupui** [comment]
mmm ok what should we do then? For the Python version I just looked at what we have on PyPi. For NumPy I copy pasted what is currently on the doc and what you previously wrote.

**Comment by tupui** [comment]
Taking some guess following `oldest-supported-numpy` here. Not sure how to do this otherwise.

SciPy version | Python versions | NumPy versions
-- | -- | --
1.2 | >=2.7, <=3.7 | >=1.8.2, <= 1.16.x  # not present
1.4 | >=3.5, <=3.8 | >=1.13.3, <= 1.17.3  # np upper bound
1.5 | >=3.6, <=3.9 | >=1.14.5, <= 1.19.3  # np upper bound
1.6 | >=3.7, <=3.9 | >=1.14.5, <= 1.20.x  # don't know
1.7.0/1 | >=3.7, <3.10 | >=1.16.5, <1.23.0
1.7.2-x | >=3.7, <3.11 | >=1.16.5, <1.24.0
1.8 | >=3.8, <3.11 | >=1.17.3, <1.24.0
