### ISSUE TITLE
Question about angle unit in scipy.stats

### ISSUE THREAD

**Issue by A-ep93** [scipy/scipy#14598]
Hello all,
I am new to scipy and I have a question about unit of angles that should be used.
I want to create a cdf for VonMises data and this is what I do:

from scipy.stats import vonmises
c=vonmises.cdf(X, kappa, loc=value, scale=1)

I want to know whether the values here (such as the value for loc) should be in degree or radian? What is the default angle in general?

**Comment by tupui** [comment]
Hi, thanks for dropping by. The answer is in the doc `The cdf is implemented such that cdf(x + 2*np.pi) == cdf(x) + 1.`

I am closing this as it's a user question. We do not have the bandwidth to do support sorry. StackOverflow for instance is more appropriate.
