### ISSUE TITLE
scipy.sparse.linalg.inv cannot take ndarray as argument despite what documentation says

### ISSUE THREAD

**Issue by gdupras** [scipy/scipy#14607]
The documentation ([scipy.sparse.linalg.inv](https://docs.scipy.org/doc/scipy/reference/reference/generated/scipy.sparse.linalg.inv.html#scipy.sparse.linalg.inv)) says

> Parameters
>
>   A(M,M) ndarray or sparse matrix
>
>   square matrix to be inverted

But this code
```
import numpy as np
from scipy.sparse import linalg
linalg.inv(np.array([[1, 2], [3, 4]]))
```
throws:
```
TypeError: Input must be a sparse matrix
```

**Comment by WarrenWeckesser** [comment]
I suspect the best option here is to fix the docs.  The `Notes` section of the docstring already recommends using `scipy.linalg.inv` for non-sparse input.

**Comment by gdupras** [comment]
Would it be possible for `scipy.sparse.linalg.inv` to call `np.linalg.inv` if `A` is an `ndarray`?

**Comment by WarrenWeckesser** [comment]
@gdupras, yes, that's possible, and it may have been the original intent of the docstring author, but the explicit check for a sparse input has been there for many years, so I suspect there isn't much demand for that convenience.  @perimosocordiae, @pv: any preferences?
