### ISSUE TITLE
ENH: add d2 statistical function

### ISSUE THREAD

**Issue by khavernathy** [scipy/scipy#14604]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
[The d2 constant](https://v8doc.sas.com/sashtml/qc/chapc/sect9.htm) in statistics is used to approximate standard deviation when only the range and number of samples is known

I made a PR (in progress) here: https://github.com/scipy/scipy/pull/14597

**Describe alternatives you've considered**
I can compute d2 myself but seems like a good tool to have. d2 is in statistical tables in textbooks etc.

**Additional context (e.g. screenshots)**

**Comment by tupui** [comment]
@mdhaber I cannot find your big issue about stats enhancements (IMO we could actually pin it as it's global and a large one). Does this fit its scope?

**Comment by mdhaber** [comment]
Do you mean gh-10577 ?

mdhaber/scipy#26 was specific to the CZI project, which is done, so it would not fit there.

I don't think this fits in either. It looks like gh-13475 : the bulk of the work is interface, documentation, code style, and testing. It would be good to see if there is some support from others who would use this and if there are some highly cited references to see if this is considered fundamental.

**Comment by tupui** [comment]
> Do you mean [gh-10577](https://github.com/scipy/scipy/issues/10577) ? I don't think this fits here unless it's part of a larger vision

I did not see this one, thanks!

> [mdhaber#26](https://github.com/mdhaber/scipy/issues/26) was specific to the CZI project, which is done, so it would not fit there.

I was referring to this one (very impressive listing, with most of it done, btw 👏 ). 
 
> It looks like [gh-13385](https://github.com/scipy/scipy/issues/13385) : a _lot_ work (the large majority, I think) is needed for interface, documentation, code style, and testing. Before going too far, it would be good to see if there is some support from others who would use this and if there are some highly cited references to see if this is considered fundamental.

Agreed here. This is why I suggested to get more insights before reviewing too much. I am not using such metric so cannot really judge and did not see much literature yet (did not look too hard as well).

**Comment by mdhaber** [comment]
@khavernathy are there some references, or is this in a lot of other software besides SAS? What are typical uses?

**Comment by khavernathy** [comment]
> @khavernathy are there some references, or is this in a lot of other software besides SAS? What are typical uses?

> @khavernathy are there some references, or is this in a lot of other software besides SAS? What are typical uses?

Typical in quality assurance engineering and process control etc.
It's used to estimate standard deviation for a population (normally distributed) where the only knowns are range and n.

where 

sigma = range / d2(n)

It's in R: https://www.rdocumentation.org/packages/IQCC/versions/1.0/topics/d2

And shown in process control charts: https://web.mit.edu/2.810/www/files/readings/ControlChartConstantsAndFormulae.pdf

I defer to y'all for where this might fit, or if its in scope or not.

**Comment by mdhaber** [comment]
@khavernathy Did you send a note to the mailing list, or did you decide not to pursue this?
