### ISSUE TITLE
Pre-release sdist CI job is failing

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#14617]
Example from https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=13644&view=logs&j=5a504361-84f9-5b04-9e0f-a07fc1c630c2&t=fb42939b-bd21-5b32-1e4c-876ce4d20951:
```
Looking in indexes: https://pypi.anaconda.org/scipy-wheels-nightly/simple
ERROR: Could not find a version that satisfies the requirement numpy (from versions: none)
ERROR: No matching distribution found for numpy
```

Not sure what changed there. @charris or @mattip any thoughts? Did one of you clean up a set of wheels from the anaconda.org bucket maybe?

**Comment by charris** [comment]
I deleted all but the 3.8+ versions (except for pypy) so that it would elicit errors. I suspect CI is looking for a 3.7 version. (checks) Yep it is using 3.7.

**Comment by rgommers** [comment]
Hmm slightly aggressive, but I guess it's a good prompt for us to drop 3.7 in master:)
