### ISSUE TITLE
On-line documentation has broken links

### ISSUE THREAD

**Issue by iandall** [scipy/scipy#14612]
### Please describe your issue.

I'm not sure if this is the right place to report this, but the documentation at `https://docs.scipy.org/doc/scipy/reference/` contains broken links.

The user guide link (`https://docs.scipy.org/doc/scipy/reference/tutorial/index.html#user-guide`) and the developer guide link (`https://docs.scipy.org/doc/scipy/reference/dev/index.html#scipy-development`) are OK, but the getting started guide link (`https://docs.scipy.org/doc/scipy/reference/getting_started.html#getting-started-ref`) returns a 404 error and the API link (`https://docs.scipy.org/doc/scipy/reference/reference/index.html#scipy-api`) goes to a page which seems to lack formatting, does not have the API docs and contains a broken (404 error) link (`https://docs.scipy.org/doc/scipy/reference/reference/reference/index.html#scipy-api`)  to the reference guide.

**Comment by tirthasheshpatel** [comment]
This is being tracked in gh-14522. As it has more discussion, I will close this. You are welcome to comment on gh-14522 if you find any new broken links, thanks!
