### ISSUE TITLE
BUG: No module named scipy._lib

### ISSUE THREAD

**Issue by JPGlaser** [scipy/scipy#14614]
### Reproducing Code Example

```python
python -c "from scipy import integrate"
```

### Error message

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jglaser/.local/lib/python3.8/site-packages/scipy/__init__.py", line 74, in <module>
    from ._lib.deprecation import _deprecated
ModuleNotFoundError: No module named 'scipy._lib'
```

### SciPy/NumPy/Python version information

1.7.1 1.21.1 sys.version_info(major=3, minor=8, micro=3, releaselevel='final', serial=0)

**Comment by rgommers** [comment]
`/home/jglaser/.local/lib/python3.8/site-packages/scipy/__init__.py` is not a path to a conda package. You are somehow mixing up multiple installs.

**Comment by rgommers** [comment]
I'll close this, since this is some kind of path issue and not a SciPy bug.

**Comment by delaprada** [comment]
> To add context, this is happening on a miniconda install of Python 3.8.3. Scipy was installed via: `mamba install -y -c defaults conda-forge::libblas=*=*mkl scipy`

Hello! Could you tell me how to solve this problem? I came over this problem today. Thank you!
