### ISSUE TITLE
failed to install Scipy via `pip` (OSX M1)

### ISSUE THREAD

**Issue by CrepeGoat** [scipy/scipy#14615]
# System Environment:
macOS Big Sur 11.5.2, M1 processor
Python 3.8.11 (using a `venv`)
pip==21.2.4 (updated via `pip`)
setuptools==57.4.0 (updated via `pip`)

# Observed output
```zsh
(venv) % python -m pip install scipy
Collecting scipy
  Using cached scipy-1.7.1.tar.gz (36.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/work/Repos/endaq-python-calc/venv/bin/python /Users/work/Repos/endaq-python-calc/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/1s/lrjbk2v17m7063f944nmy7vh0000gn/T/tmp7dun4f3u
         cwd: /private/var/folders/1s/lrjbk2v17m7063f944nmy7vh0000gn/T/pip-install-cc3mdfet/scipy_90eec6ff22e54b9d84809dedc230c072
    Complete output (4 lines):
    setup.py:490: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /private/var/folders/1s/lrjbk2v17m7063f944nmy7vh0000gn/T/pip-modern-metadata-0oa55ptb'), proceeding with generating Cython sources and expanding templates
      warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
    Error: 'None' must be installed before running the build.

    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/47/33/a24aec22b7be7fdb10ec117a95e1e4099890d8bbc6646902f443fc7719d1/scipy-1.7.1.tar.gz#sha256=6b47d5fa7ea651054362561a28b1ccc8da9368a39514c1bbf6c0977a1c376764 (from https://pypi.org/simple/scipy/) (requires-python:>=3.7,<3.10). Command errored out with exit status 1: /Users/work/Repos/endaq-python-calc/venv/bin/python /Users/work/Repos/endaq-python-calc/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/1s/lrjbk2v17m7063f944nmy7vh0000gn/T/tmp7dun4f3u Check the logs for full command output.
```

It then tries other versions of `scipy`, but they all result in the same message.

Any help appreciated, thanks!

**Comment by GT135813** [comment]
Hey  CrepeGoat,

Try this:

```
brew install scipy
```

**Comment by Yarden92** [comment]
> Hey CrepeGoat,
> 
> Try this:
> 
> ```
> brew install scipy
> ```
> 
> My specs:
> 
> macOS Big Sur 11.5.2, M1 processor
> Python 3.9.6
> pip 21.2.4
> setuptools 57.0.0
> 
> After install via-homebrew:
> scipy 1.7.1

and then what?
how do I import it via python?
doing `import scipy` isn't working

**Comment by GT135813** [comment]
This is most likely due to pathing.

Try this inside your Terminal:

```
brew info scipy
```
Once you know your path to Scipy:

Go back to your Terminal Window and run Python3
```
my@user ~ % python3
Python 3.9.6 (default, Jun 28 2021, 19:24:41)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
>>> your path will appear here
```

Note:
If your Python3 is not installed via Homebrew, I would highly suggest doing so.
(This would fix your pathing issue without having to alter settings inside of your ```~/.bash_profile``` )

You can install Python3 via Homebrew like this:
```
brew install python3
```

If you choose not to install Python3 like mentioned above, you will need to put your Scipi inside your ~/.bash_profile


**sourced here**
```https://stackoverflow.com/questions/3387695/add-to-python-path-mac-os-x#3387737```

Modifications to sys.path only apply for the life of that Python interpreter. If you want to do it permanently you need to modify the PYTHONPATH environment variable:
```
PYTHONPATH="/Me/Documents/mydir:$PYTHONPATH"
export PYTHONPATH
```
Note that PATH is the system path for executables, which is completely separate.
You can write the above in ~/.bash_profile and the source it using source ~/.bash_profile

Honestly, I would just install Python with Homebrew :)

**Comment by rgommers** [comment]
I would not recommend installing SciPy with Homebrew. Use conda-forge if you want M1 binaries.

Also if you do prefer pip, there are M1 wheels for testing at https://anaconda.org/scipy-wheels-nightly/.

SciPy 1.7.1 does not have M1 support, but 1.7.2 will. For now please install from master, that should build just fine. There's no other issues I'm aware of, so I will close this issue. If you do have a problem building from master, please open a new issue.

**Comment by GT135813** [comment]
@rgommers Thank you for the clarification.

**Comment by CrepeGoat** [comment]
@GT135813 @rgommers thank you for your replies!

> I would not recommend installing SciPy with Homebrew. Use conda-forge if you want M1 binaries.

This was my sentiment as well, since I was trying to install this specifically in a venv and afaik Homebrew wouldn't help me do that.

> Also if you do prefer pip, there are M1 wheels for testing at https://anaconda.org/scipy-wheels-nightly/.

I do prefer pip, thanks for this option!

> SciPy 1.7.1 does not have M1 support, but 1.7.2 will. For now please install from master

Good to know, thanks! For anyone else reading, I'll probably be pip installing directly from the git master branch via `pip install git+https://github.com/scipy/scipy@master`

**Comment by GT135813** [comment]
@CrepeGoat No worries at all. Best of luck.

**Comment by CrepeGoat** [comment]
More fixes for anyone else with the same problem:

> Good to know, thanks! For anyone else reading, I'll probably be pip installing directly from the git master branch via `pip install git+https://github.com/scipy/scipy@master`

So this resulted in some errors for me due to, afaik, missing c-library dependencies when compiling from source.

Now I *could* dig into these C compilation issues. But I'm a Python developer on a time budget, so I'm going to instead opt for the easier solution.

# The easier solution
## Check your Python interpreter
If you install python through the installer available directly from https://www.python.org/, you'll install a *universal binary*. You can tell it's a universal binary because running in the command line `which python3 | xargs file` prints to stdout something like the below message, which makes note of both `x86_64` and `arm64` architectures:
```zsh
crepegoat@CrepeScape ~ % which python3 | xargs file
/usr/local/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
/usr/local/bin/python3 (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/local/bin/python3 (for architecture arm64):	Mach-O 64-bit executable arm64
```
(If you installed via another means like e.g. Homebrew, as long as the above command prints the same result this will still work.)

## Set `zsh` to run programs in `x86_64` mode
By default, Terminal (i.e., `zsh`) will run programs in `arm64` mode; this is evidenced by the result of running `uname -m`:
```zsh
crepegoat@CrepeScape ~ % uname -m
arm64
```
This can be changed on either a command-, terminal-session- or permanent-basis using the `arch` command. Below I opt for the session-basis change:
```zsh
crepegoat@CrepeScape ~ % arch -x86_64 zsh
crepegoat@CrepeScape ~ % uname -m                          
x86_64
```

## Install `scipy` as usual
Now after setting up `zsh` in `x86_64`, running `pip` will install binaries for the  `x86_64` architecture, with which `scipy` has perfectly functional compatibility. At the time of writing this, I've successfully installed `scipy==1.7.1` on my system.

**Comment by jl-gel** [comment]
@CrepeGoat -> best solution by far without having to mess around with installation of other libraries or whatnot!

**Comment by Aryan-Ridecell** [comment]
> More fixes for anyone else with the same problem (and as a reference for myself, if we're being honest):
> 
> > Good to know, thanks! For anyone else reading, I'll probably be pip installing directly from the git master branch via `pip install git+https://github.com/scipy/scipy@master`
> 
> So this resulted in some errors for me due to, afaik, missing c-library dependencies when compiling from source.
> 
> Now I _could_ dig into these C compilation issues. But I'm a Python developer on a time budget, so I'm going to instead opt for the easier solution.
> 
> # The easier solution
> ## Check your Python interpreter
> If you install python through the installer available directly from https://www.python.org/, you'll install a _universal binary_. You can tell it's a universal binary because running in the command line `which python3 | xargs file` prints to stdout something like the below message, which makes note of both `x86_64` and `arm64` architectures:
> 
> ```shell
> crepegoat@CrepeScape ~ % which python3 | xargs file
> /usr/local/bin/python3: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64]
> /usr/local/bin/python3 (for architecture x86_64):	Mach-O 64-bit executable x86_64
> /usr/local/bin/python3 (for architecture arm64):	Mach-O 64-bit executable arm64
> ```
> 
> (If you installed via another means like e.g. Homebrew, as long as the above command prints the same result this will still work.)
> 
> ## Set `zsh` to run programs in `x86_64` mode
> By default, Terminal (i.e., `zsh`) will run programs in `arm64` mode; this is evidenced by the result of running `uname -m`:
> 
> ```shell
> crepegoat@CrepeScape ~ % uname -m
> arm64
> ```
> 
> This can be changed on either a command-, terminal-session- or permanent-basis using the `arch` command. Below I opt for the session-basis change:
> 
> ```shell
> crepegoat@CrepeScape ~ % arch -x86_64 zsh
> crepegoat@CrepeScape ~ % uname -m                          
> x86_64
> ```
> 
> ## Install `scipy` as usual
> Now after setting up `zsh` in `x86_64` mode, running `pip` will install binaries for the `x86_64` architecture, with which `scipy` has perfectly functional compatibility. At the time of writing this, I've successfully installed `scipy==1.7.1` on my system with this method. If you're reading this, I hope it helps you too :)

This worked !
