### ISSUE TITLE
ENH: MemoryError when trying to bootstrap with large amounts of data

### ISSUE THREAD

**Issue by rsundqvist** [scipy/scipy#14645]
### Please describe your issue.

Trying to bootstrap "large" amounts of data will throw a `MemoryError`, even without vectorization. Generating the drawn samples one iteration at a time would allow for larger data arrays without causing memory errors.

**Expected result**
Setting `vectorized=False` should reduce the memory requirement, since we no longer need to create a matrix of size `len(data) * n_resamples`. Drawing a single sample at a time should be enough when we don't want to parallellize anything.

**Actual result**
A `MemoryError` is raised for even moderately large arrays.

**Step to reproduce**
```python
import scipy
import numpy as np
print(scipy.__version__)
```
Output:
```
1.7.1
```
```python
data = np.random.randint(low=0, high=1, size=1_000_000)
scipy.stats.bootstrap(data=(data,) , statistic=np.var, vectorized=False)
```
Output:
```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
/tmp/ipykernel_21666/4129127229.py in <module>
      1 data = np.random.randint(low=0, high=1, size=1_000_000)
----> 2 scipy.stats.bootstrap(data=(data,) , statistic=np.var, vectorized=False)

~/.local/lib/python3.8/site-packages/scipy/stats/_bootstrap.py in bootstrap(data, statistic, vectorized, paired, axis, confidence_level, n_resamples, batch, method, random_state)
    431         resampled_data = []
    432         for sample in data:
--> 433             resample = _bootstrap_resample(sample, n_resamples=batch_actual,
    434                                            random_state=random_state)
    435             resampled_data.append(resample)

~/.local/lib/python3.8/site-packages/scipy/stats/_bootstrap.py in _bootstrap_resample(sample, n_resamples, random_state)
     50 
     51     # bootstrap - each row is a random resample of original observations
---> 52     i = rng_integers(random_state, 0, n, (n_resamples, n))
     53 
     54     resamples = sample[..., i]

~/.local/lib/python3.8/site-packages/scipy/_lib/_util.py in rng_integers(gen, low, high, size, dtype, endpoint)
    537 
    538         # exclusive
--> 539         return gen.randint(low, high=high, size=size, dtype=dtype)
    540 
    541 

mtrand.pyx in numpy.random.mtrand.RandomState.randint()

_bounded_integers.pyx in numpy.random._bounded_integers._rand_int64()

MemoryError: Unable to allocate 74.5 GiB for an array with shape (9999, 1000000) and data type int64
```

The issue stems from this line:
```python
---> 52     i = rng_integers(random_state, 0, n, (n_resamples, n))
```
The `_bootstrap_resample` (and calling) method needs to know that generating `n_resamples` samples all at once isn't necessary when `vectorized=False`.

**Comment by rsundqvist** [comment]
> What is the statistic in your actual application? (I assume it is natively vectorized and not actually using vectorized=False?) Can pythran or numba be used to make it faster?

Yes, we're using regular vectorized `numpy` functions for the actual use case. I'd not have touched `vectorized` at all if I'd understood what it did.

> And I suppose it's worth asking - why bootstrap? Are there other methods you could use that might be faster?

We've got one KPI in particular (a probability, there are others which seem to work fine) where we're seeing CIs which very quickly converge to 100% certainty, while in reality it can change quite a bit day-to-day. We're looking into different methods to model CI to get a more accurate measure of the certainty that our AB tests have converged on this point. Bootstrapping is just one of the alternatives we're exploring. To make it messier, we're "CI-ing" percentage changes instead of absolute changes.

We're currently using conventional CI methods for all of the KPIs, there is only this one in particular which is misbehaving (we're aware that traditional CI/SE computations don't directly apply to ratios).

**Comment by mdhaber** [comment]
> Yes, we're using regular vectorized numpy functions for the actual use case

Then yeah, if you can use a GPU, it looks really easy to use CuPy as a back end for the expensive calculations.

**Comment by mdhaber** [comment]
See mdhaber/scipy#63 for what I meant about using a GPU. I'm seeing ~10x speedup on this:

```
import numpy as np
import cupy as cp
from scipy import stats

data_np = np.random.rand(10000)
rng_np = np.random.RandomState(0)
res_np = stats.bootstrap((data_np,), np.std, batch=1000,
                         random_state=rng_np, xp=np)  # 2.8 s ± 9.26 ms per loop 

data_cp = cp.array(data_np)
rng_cp = cp.random.RandomState(0)
res_cp = stats.bootstrap((data_cp,), cp.std, batch=1000, 
                         random_state=rng_cp, xp=cp)  # 240 ms ± 518 µs per loop  
```
