### ISSUE TITLE
[Feature]: Non-Normal Distributed Effect-Size Measures

### ISSUE THREAD

**Issue by lapplislazuli** [scipy/scipy#14646]
### Is your feature request related to a problem? Please describe.

For an experiment, I first performed the Wilcoxon Rank Sum Test (of Scipy) and now I would like to report the measured effect-size.

### Describe the solution you'd like.

For non-normal distributed data, that has a Wilcoxon-RankSum-Test proven difference common tests would be Vargha-Delaney or Cliff's Delta [e.g. from Wikipedia](https://en.wikipedia.org/wiki/Effect_size)

### Describe alternatives you've considered.

There are some Gist-Implementations and Snippets found online, that will do the trick.

**Comment by mdhaber** [comment]
Good idea, but closing because I just added some additional information to gh-14869 and they are essentially duplicates. 
@lapplislazuli would you go hit the thumbs up button in the top post of gh-14869? The more support shown there, the more likely it is to happen! Thanks!
