### ISSUE TITLE
BUG: not enough values to unpack (expected 6, got 5) in linregress

### ISSUE THREAD

**Issue by ArchangeGabriel** [scipy/scipy#14659]
### Reproducing Code Example

```python
from scipy.stats import linregress

slope, intercept, rvalue, pvalue, stderr, intercept_stderr = linregress([1,2],[1,2])
```

### Error message

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-f8c8c3600141> in <module>
----> 1 slope, intercept, rvalue, pvalue, stderr, intercept_stderr = linregress([1,2],[1,2])

ValueError: not enough values to unpack (expected 6, got 5)
```

### SciPy/NumPy/Python version information

1.7.1, 1.20.3, 3.9.6

**Comment by ArchangeGabriel** [comment]
According to [the documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.linregress.html), a `LinregressResult instance` has 6 properties but apparently only 5 can be unpacked this way.

**Comment by rkern** [comment]
This behavior is documented and explained in the Notes of the linked documentation. In general, we recommend assigning to a single `result` variable and accessing the individual items with attributes in any case.

**Comment by ArchangeGabriel** [comment]
>This behavior is documented and explained in the Notes of the linked documentation.

Oops, sorry for missing that… I guessed it might be a retro-compatibility issue since one user had issue accessing `intercept_stderr`.

>In general, we recommend assigning to a single result variable and accessing the individual items with attributes in any case.

That’s what I ended up doing. ;)
