### ISSUE TITLE
BUG: find_peaks does not detect maximal peak if it's at the start of array

### ISSUE THREAD

**Issue by Yodude120** [scipy/scipy#14661]
Hello,

I noticed a bug in Scipy while using the find_peaks function.

Namely, if I have a signal/array where I want to detect peaks higher than X % of the maximum, the returned peaks sometimes lack the actual maximum. This happens when the maximum is at the very start of the array -- e.g., index 0.

The function call looks something like the code below

I think it's because the peak picking logic tries to check that neighbouring peaks are of lower value/amplitude, but this is not possible for the start/end positions in the array. I would suggest counting a value at the start/end of an array as a peak if the values in the respective one-sided (instead of two-sided) neighbourhood are lower.

Best

### Reproducing Code Example

```python

currentPeakIndices = scipy.signal.find_peaks(currentSignal, height=percentageThresshold*max(currentSignal))[0]

```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

1.6.2 1.20.1 sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi, thanks for the report. This is known bug already reported here #13710. Closing this issue in favour of the old one which had some activity. Feel free to come over there and comment.
