### ISSUE TITLE
dblquad has confusing variable order x and y expected from func

### ISSUE THREAD

**Issue by jonas-eschle** [scipy/scipy#14678]
### Please describe your issue.

dblquad expects a function with signature `func(y, x)`. This is highly confusing as the signature of functions is everywhere else expected to be `func(x, y)`. This can be easily overlooked. Why is this?  I would actually suggest to use keyword arguments in the position call or to add a warning (or even to change it), as errors can easily happen this way.

**Comment by tupui** [comment]
Hi @jonas-eschle

> dblquad expects a function with signature `func(y, x)`. This is highly confusing as the signature of functions is everywhere else expected to be `func(x, y)`. This can be easily overlooked. Why is this? 

Not sure what you mean by everywhere else as the n-Dimensional integrals are in order.

It's going from outer to inner variables as explained in the doc `y = gfun(x)..hfun(x)`. Same for triple integration with `tplquad`. And `nquad` explains it better:

`Integration is carried out in order. That is, integration over x0 is the innermost integral, and xn is the outermost.`

> I would actually suggest to use keyword arguments in the position call or to add a warning (or even to change it), as errors can easily happen this way.

Public API changes are very hard as people rely on these. As for using keywords arguments, it's the same. People can use the naming they want for their parameters and we would not want to impose anything on others signature here.

If this answers your issue, please consider closing it 😃

**Comment by jonas-eschle** [comment]
Hm, I see, indeed that is a way to go about it. Many thanks for the answer!
