### ISSUE TITLE
Why does rtol bottom out at 100*eps?

### ISSUE THREAD

**Issue by nbelakovski** [scipy/scipy#14671]
### Please describe your issue.

If rtol is set to a very low value or to 0, it gets reset to 100*(machine epsilon). It's not immediately clear why this is, and the docs do not specify. It doesn't appear that Julia's DifferentialEquations does this. I'm happy to contribute to either docs or code if there's an explanation for why this is done or if there's a better way to achieve what this feature is trying to achieve.

**Comment by tupui** [comment]
I will close it for now. There is nothing we can do without more information.
