### ISSUE TITLE
BUG: SciPy API reference not rendering properly

### ISSUE THREAD

**Issue by joosephook** [scipy/scipy#14670]
### Please describe your issue.

When clicking the [API Reference]() link [here](https://docs.scipy.org/doc/scipy-1.7.1/reference/index.html), you see the same(?) page as before, only with broken CSS. If, on this new site, you click again on [API Reference](https://docs.scipy.org/doc/scipy-1.7.1/reference/reference/index.html#scipy-api), you end up with a 404.  However, when you download the documentation as zipped HTML, it renders nicely.

**Comment by tupui** [comment]
Thanks, it's a known but already reported. I will close this one in favour of gh-14267
