### ISSUE TITLE
BUG: Gettings started docs link is returning 404

### ISSUE THREAD

**Issue by tylerpotts** [scipy/scipy#14698]
### Describe your issue.

When navigating to https://docs.scipy.org/doc/scipy/reference/ and clicking the `getting started` box, a 404 is returned

### Reproducing Code Example

```python
n/a
```

### Error message

![image](https://user-images.githubusercontent.com/49161327/132259155-9ff8cd4a-ab9b-40da-bd63-4a38a0641b25.png)

### SciPy/NumPy/Python version information

n/a

**Comment by melissawm** [comment]
Probably related to #14267

**Comment by tupui** [comment]
Yes, definitely! In this case, the correct path does not even have any `reference`. Thanks Melissa.

**Comment by tupui** [comment]
@tylerpotts sorry about this and thanks for the report. In the meanwhile please use the devdocs: https://scipy.github.io/devdocs/index.html
