### ISSUE TITLE
Different results on Windows and Mac for `lbfgsb`

### ISSUE THREAD

**Issue by chrissles** [scipy/scipy#14691]
Using scipy/optimize for the optimization of the parameters of a Gaussian Process, there are differences in the optimized parameters occuring between Windows and Mac.
The difference appears in the function minimize_lbfgsb in lbfgsb.py in scipy/optimize. There is a for-loop returning very precise values for x, f, g. Those values start diverging between the machines. When rounding these values to e.g. 4 decimal points the results are identical.

**Comment by rgommers** [comment]
Hi @chrissles, that's normal for floating point calculations. This is not a bug report we can act on. If there's a specific problem you are seeing, a code example that we can run to reproduce it would be helpful.

**Comment by chrissles** [comment]
[scripts.zip](https://github.com/scipy/scipy/files/7106205/scripts.zip)

So here is an example. You can try it with Windows and Mac and you will see the differences.

**Comment by rgommers** [comment]
Can you please add the Python code here if it's short, or put it in a gist (https://gist.github.com/) otherwise?

**Comment by chrissles** [comment]
import numpy as np
import pickle
from scipy.optimize.lbfgsb import _minimize_lbfgsb

args = ()
bounds = None
opts = {'disp': -1, 'iprint': -1, 'maxcor': 10, 'ftol': 2.220446049250313e-09, 'gtol': 1e-05, 'eps': 1e-08, 'maxfun': 1000, 'maxiter': 1000, 'callback': None, 'maxls': 20}

x0 = np.array([0.54132485, 0.54132485, 0.54132485, 0.54132485, 0.54132485,
       0.54132485, 0.54132485, 0.54132485, 0.54132485, 0.54132485,
       0.54132485, 0.54132485, 0.54132485, 0.54132485, 0.54132485,
       0.54132485])

jac = pickle.load(open('jac.dump', 'rb'))
f_fp = pickle.load(open('f_fp.dump', 'rb'))

res = _minimize_lbfgsb(f_fp, x0, args=args, jac=jac, bounds=bounds,
                       **opts)

**Comment by rgommers** [comment]
Thanks @chrissles. That doesn't yet show the deviations, nor am I able (or willing) to load a pickle file - that's a security risk, sorry. I'm still not sure if there's an actual problem here (it doesn't seem like it), but we really need a self-contained example that can be run.

**Comment by rgommers** [comment]
I'm going to close this as invalid - this is expected behavior. As the issue description says, all values are equal to 4 decimal points.
