### ISSUE TITLE
BUG: Zeros of Bessel function J'_v

### ISSUE THREAD

**Issue by msshaqfa** [scipy/scipy#14705]
### Describe your issue.

The first zero of Bessel function $J^{\prime}_0$ should be zero and not 3.831.., which is actually the second root. This can be found in many textbooks in this regard. Fixing this requires only shifting the roots of the $J^{\prime}_0$ by one. Indeed the value numerically is not zero but it's close to it. I computed it myself to be about: 4.963083675318166E-23. Placing it with "zero" could result in some numerical issues with the normalization.

### Reproducing Code Example

```python
scipy.special.jnp_zeros(0, 10)
```

### Error message

```shell
No error message.
```

### SciPy/NumPy/Python version information

Scipy, Python3: 1.6.2 1.17.4 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
According to the documentation:
<img width="1286" alt="image" src="https://github.com/user-attachments/assets/2761eb5d-5bca-4747-b7b7-860e4acf1154">

This would exclude the zero of $J ^\prime_0$ at $x = 0$.

> Indeed the value numerically is not zero but it's close to it. I computed it myself to be about: 4.963083675318166E-23

If this were true, then it should be included as the first zero, but `4.963083675318166E-23` is not a root.

```python3
from scipy import special
special.jvp(0, 4.963083675318166E-23, 1)  # -2.481541837659089e-23
special.jvp(0, 0, 1) == 0  # True
```

Just to double check:
```python3
from mpmath import mp
mp.dps = 100
float(mp.besselj(0, 4.963083675318166E-23, 1))  # -2.481541837659083e-23
float(mp.besselj(0, 0, 1)) == 0  # True 
```

> The first zero of Bessel function... should be zero and not 3.831.., which is actually the second root. This can be found in many textbooks in this regard. 

That is a convention. SciPy follows a different convention, which also has precedent; e.g. [Wolfram Language / Mathematica](https://mathworld.wolfram.com/BesselFunctionZeros.html):

<img width="1199" alt="image" src="https://github.com/user-attachments/assets/79693066-bc3e-4892-9446-17e08bc50984">

This has been the documented behavior of `jnp_zeros` for many years, so I think this is firmly in the realm of feature, not bug.
