### ISSUE TITLE
BUG: overflow_error with ibeta_derivative not throwing an exception

### ISSUE THREAD

**Issue by JPFrancoia** [scipy/scipy#14704]
### Describe your issue.

Similar to https://github.com/scipy/scipy/issues/14606, I'm getting a boost overflow error. Unfortunaterly the bug is quite hard to pinpoint as the codebase I'm working on is big and complex (and believe me, I tried). See below for the error message.

### Reproducing Code Example

I'm running scipy 1.8.0.dev0+1704.ff34402 installed from Anaconda's pypi repo (https://anaconda.org/scipy-wheels-nightly/scipy). I installed the nightly. I believe the version of Scipy I'm running should contain https://github.com/scipy/scipy/pull/14618.

I knew it was a long shot, but I had hoped this version would wrap the boost error into a Python exception. No luck there, it looks like `overflow_error` is not caught.

I confirm that I also get this error with scipy 1.7.0 and 1.7.1, but not with versions <1.7.0 (so before boost libraries were vendored by scipy).

### Error message

```shell
terminate called after throwing an instance of 'boost::wrapexcept<std::overflow_error>'
  what():  Error in function ibeta_derivative<double>(double,double,double): Overflow Error
```

### SciPy/NumPy/Python version information

```
1.8.0.dev0+1704.ff34402 1.19.4 sys.version_info(major=3, minor=8, micro=11, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment]
@mckib2 Looks like this is another error we need to catch and raise as a Python exception.

**Comment by JPFrancoia** [comment]
> @mckib2 Looks like this is another error we need to catch and raise as a Python exception.

It looks like it yes. I don't have the skills to make a PR, but I'll gladly test an eventual fix.

**Comment by mckib2** [comment]
Yes, I can look at this in the next few days.  Even without a reproducer we can at least get a fix in and hopefully you can help us track down the offending distribution once it's caught

**Comment by JPFrancoia** [comment]
Can we reuse the same approach as in https://github.com/scipy/scipy/pull/14618/files?

I'd just need help with the func_defs.hpp  file, the  rest I can handle

**Comment by JPFrancoia** [comment]
UPDATE: ok I was able to work around the undefined symbol error mentioned above. I just needed to merge master into your branch and it solved the problem (https://github.com/JPFrancoia/scipy/tree/boost-ibeta-derivative-overflow).

It looks like your fix "works", the error message disappeared, and my program still crashed. I'm still investigating, I just need a way to find the error message in the log. I'll come back

**Comment by JPFrancoia** [comment]
This is the minimal snippet to reproduce the issue (stripping away any dependency on statsmodels):

```python
from scipy.version import version
from scipy import optimize, stats
from sys import float_info

print("Scipy version:", version)

count = 5
nobs = 6
alpha = 0.05
q_ = count * 1. / nobs


def func(qi):
    return stats.binom_test(q_ * nobs, nobs, p=qi) - alpha


optimize.brentq(func, float_info.min, q_)
```

I'll open another bug to track this issue, I think the current issue should be targeted at catching the overflow error and throwing an exception. WHat do you think?

**Comment by JPFrancoia** [comment]
Thank you for taking care of this bug! Much appreciated.
