### ISSUE TITLE
BUG: stats: The `loguniform` distribution is overparametrized.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#14716]
### Describe your issue.

The `loguniform` distribution (aka `reciprocal`) is overparametrized.

There are two shape parameters, `a` and `b`, and the usual `loc` and `scale`.  Assume `loc=0`. The PDF in that case is `f(x, a, b, scale) = 1/(x*log(b/a))` with support `scale*a <= x  <= scale*b`.  If we replace `a` with `k*a`, `b` with `k*b` and `scale` with `scale/k`, we get the same distribution:

    f(x, k*a, k*b, scale/k) = 1/(x*log(k*b/(k*a)) = 1/(x*log(b/a)) = f(x, a, b, scale)

and the support is `(scale/k)*k*a <= x <= (scale/k)*k*b` ⇒ `scale*a <= x <= scale*b`.  I.e. the distribution is the same for any k > 0.

For example,
```
In [29]: from scipy.stats import loguniform

In [30]: a = 1

In [31]: b = 5

In [32]: scale = 2

In [33]: x = np.linspace(0, 11, 15)

In [34]: loguniform.pdf(x, a, b, scale=scale)
Out[34]: 
array([0.        , 0.        , 0.        , 0.26359664, 0.19769748,
       0.15815798, 0.13179832, 0.11296999, 0.09884874, 0.08786555,
       0.07907899, 0.07188999, 0.06589916, 0.        , 0.        ])

In [35]: k = 2.5

In [36]: loguniform.pdf(x, k*a, k*b, scale=scale/k)  # Different params, same PDF.
Out[36]: 
array([0.        , 0.        , 0.        , 0.26359664, 0.19769748,
       0.15815798, 0.13179832, 0.11296999, 0.09884874, 0.08786555,
       0.07907899, 0.07188999, 0.06589916, 0.        , 0.        ])
```

-----

I ran into this while working on code for fitting of distributions that involves computing the Hessian of the log-likelihood function.  When there are redundant variables like this, we end up with a singular Hessian matrix.

### Reproducing Code Example

```python
See the ipython session above.
```

### Error message

```shell
No error messages; see above.
```

### SciPy/NumPy/Python version information

This problem exists in the master branch ('bf0806b').

**Comment by szkafander** [comment]
@WarrenWeckesser could you post your fitting code?

**Comment by mdhaber** [comment]
Here is some example code for fit confidence intervals. 

```python3
import numpy as np
from scipy import stats
from scipy.optimize import minimize

# # If you have numdifftools
# from scipy import linalg
# import numdifftools as nd

# distribution to fit to data
dist = stats.norm

# examgrades data from Matlab
data = np.array([65, 61, 81, 88, 69, 89, 55, 84, 86, 84, 71, 81, 84, 81, 78,
                  67, 96, 66, 73, 75, 59, 71, 69, 63, 79, 76, 63, 85, 87, 88,
                  80, 71, 65, 84, 71, 75, 81, 79, 64, 65, 84, 77, 70, 75, 84,
                  75, 73, 92, 90, 79, 80, 71, 73, 71, 58, 79, 73, 64, 77, 82,
                  81, 59, 54, 82, 57, 79, 79, 73, 74, 82, 63, 64, 73, 69, 87,
                  68, 81, 73, 83, 73, 80, 73, 73, 71, 66, 78, 64, 74, 68, 67,
                  75, 75, 80, 85, 74, 76, 80, 77, 93, 70, 86, 80, 81, 83, 68,
                  60, 85, 64, 74, 82, 81, 77, 66, 85, 75, 81, 69, 60, 83, 72])

# # generate random data
# data = dist.rvs(loc=10, scale = 20, size=100)

# negative log-likelihood function
def fun(theta):
    # "nnlf" is an erroneous acronym for Negative Log-Likelihood Function
    return dist.nnlf(theta, data)

# parameter estimates
theta = dist.fit(data)

# # information matrix is the hessian of the log-likehood function at the estimate
# hess = nd.Hessian(fun)
# I = hess(theta)

# # Standard error is the diagonal elements of the inverse information matrix
# # stderr = np.sqrt(np.diag(linalg.inv(I)))  # if you don't mind explicit inversion
# stderr = np.sqrt(np.diag(linalg.solve(I, np.eye(2))))

# alternatively, use L-BFGS-B estimate of information matrix
# estimate isn't great if you guess the exact solution
perturbed_fit = stats.norm.fit(data) + np.random.rand(2)
res = minimize(fun, x0=perturbed_fit, method='L-BFGS-B')
stderr = np.sqrt(np.diag(res.hess_inv @ np.eye(2)))  # diagonal of information matrix

confidence = 0.95
alpha = 1 - confidence
intervals = stats.norm(loc=theta, scale=stderr).interval(0.95)

# We can do all that in a lot less code by bootstrapping
def bootfun(data):
    return dist.fit(data)

res = stats.bootstrap((data,), bootfun, vectorized=False)
intervals2 = res.confidence_interval

intervals = np.array(intervals)
intervals2 = np.array(intervals2)
print(f"Fisher Information CI of Location: {intervals[:, 0]}")
print(f"Bootstrap Information CI of Location: {intervals2[:, 0]}")
print(f"Fisher Information CI of Scale: {intervals[:, 1]}")
print(f"Bootstrap Information CI of Scale: {intervals2[:, 1]}")
```

Results can be compared against the "Parameter Confidence Intervals" example from the Matlab [`paramci`](https://www.mathworks.com/help/stats/prob.normaldistribution.paramci.html) documentation. A good reference about Fisher information MLE confidence intervals is [here](https://www.stat.umn.edu/geyer/s06/5102/notes/fish.pdf).

This sort of thing will be added to the new [`scipy.stats.fit`](http://scipy.github.io/devdocs/reference/generated/scipy.stats.fit.html#scipy.stats.fit) and to continuous distribution `fit` methods at some point.

**Comment by mdhaber** [comment]
I think one way of fixing this issue is by deprecating `a` and `b` and introducing a new parameter `c` that is the ratio of the two. In the deprecation warning and notes, we can explain that users can calculate values for the new parameters based on their old ones as follows:
```python3
scale = scale_old * a
c = b / a
loc = loc_old
```
In the argcheck, `c > 1`. 
In the implementation, wherever `b` occurs it can be replaced with `c`, and wherever `a` occurs it can be replaced with `1`.

Of course, users would probably prefer elimination of the `scale` parameter from this distribution, since the parameterization in terms of `a` and `b` is everywhere, but that would be considerably more disruptive to the codebase. There is a lot of support for making it easy to use alternative parameterizations. I think we should introduce this possibility at some point, but I don't think that should be required to fix this issue.

**Comment by mdhaber** [comment]
It would be challenging to deprecate those parameters; I tried a bit, but we'd have to fight with the distribution infrastructure. 
I now think we should deprecate the `loguniform` and `reciprocal` distributions, replace them with `log_uniform` with the new parameterization. When the deprecation period is done, we the `loguniform` name is available again, if we prefer, so we could remove `log_uniform` from the docs and make them all aliases for the same distribution.
