### ISSUE TITLE
BUG: dir(scipy) shows only ['test']

### ISSUE THREAD

**Issue by rdfuhr** [scipy/scipy#14715]
### Describe your issue.

I have Python 3.9.7 installed on a MacBook Pro with the M1 chip.
When I import scipy I expect dir(scipy) to list all the functions available, but instead I see only the test function.

By contrast, when I import numpy and invoke dir(numpy) there is a list of all its functions.

### Reproducing Code Example

```python
Richards-MacBook-Pro Fri Sep 10 11:21 AM ~ % which python3.9
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
Richards-MacBook-Pro Fri Sep 10 11:25 AM ~ % python3.9
Python 3.9.7 (v3.9.7:1016ef3790, Aug 30 2021, 16:39:15) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> dir(scipy)
['test']
```

### Error message

```shell
There are no error messages associated with this issue.
```

### SciPy/NumPy/Python version information

1.7.1 1.21.2 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by ev-br** [comment]
It's a feature, not a bug.  Scipy top-level namespace is supposed to be (almost) empty. You'd need to import submodules directly.

```
>>> import scipy
>>> dir(scipy)
['test']
>>> import scipy.stats as stats
>>> len(dir(stats))
306
```

**Comment by ev-br** [comment]
On a side note, I'm a bit surprised though that `LowLevelCallable` does not show in `dir(scipy)`

```
>>> import scipy
>>> scipy.LowLevelCallable
<class 'scipy._lib._ccallback.LowLevelCallable'>
```
