### ISSUE TITLE
Is there a way to print the output of fmin_l_bfgs_b on a file and not on screen?

### ISSUE THREAD

**Issue by martinanibbi** [scipy/scipy#14728]
Hello everyone,
I have a question about the usage of the function fmin_l_bfgs_b.
In my code I perform two optimizations inside a bigger loop, something like:
```
for ...
    res_1 = fmin_l_bfgs_b(f1, iprint=1001, ...)
    ....
    res_2 = fmin_l_bfgs_b(f2, iprint=1001, ...)
    ...
```
and I would like to see the full output for all the optimizations.
In order to save it into a file I simply write from the command line: "python program.py > program.out" but unfortunately this way the output looks unreadable as sometimes the different prints overlap.
Is there a way to force the function fmin_l_bfgs_b to write its output on a file instead of screen?

Thank you in advance for your help and I apologize if this was the wrong section.

**Comment by tupui** [comment]
Hi @martinanibbi, sorry but this is not a support channel. We don't have the bandwidth to answer user questions. Please post on StackOverflow or the user mailing list instead.

You problem can be googled it's a general Python thing to redirect the output to files.
