### ISSUE TITLE
BUG: resample_poly does not preserve dtype

### ISSUE THREAD

**Issue by bmcfee** [scipy/scipy#14733]
### Describe your issue.

When given an input of dtype `np.float32`, the output of resamply_poly has dtype `float64`.

This was previously raised as #9104, but I think incompletely addressed in #9105. I think the fix (and corresponding test) only apply when the window is explicitly constructed by the user as is done in the test here:
https://github.com/scipy/scipy/blob/ce782b6a805b4d98e40ccb444203ddfff4eb74ac/scipy/signal/tests/test_signaltools.py#L1253-L1259

If the window is not explicitly constructed by the user, it is constructed automatically, and apparently always with dtype=float64.  This would result in (unintended) dtype promotion.

Probably the easiest fix here is to match the window dtype to the input signal if it is constructed automatically.

### Reproducing Code Example

```python
import scipy
import numpy as np

x = np.random.randn(22050).astype(np.float32)
y = scipy.signal.resample_poly(x, 2, 1)
```

### Error message

```shell
No error message, but `y.dtype = np.float64`, when I would expect it to match the input (float32).
```

### SciPy/NumPy/Python version information

1.7.1 1.20.3 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Thanks @bmcfee. I would not call it a big since we don't guarantee anything. But it's a good point. Would you like to make a PR?

**Comment by bmcfee** [comment]
> I would not call it a bug, since we don't guarantee anything.

Fair enough, bug looked like the most relevant issue template. :grin: 

Yeah, I can put up a PR for this.

**Comment by tupui** [comment]
Haha true (the blank template is gone and we still need to add it back), it was not a complain at all 😃
