### ISSUE TITLE
ENH: Solving two-step interpolation in scipy

### ISSUE THREAD

**Issue by Ricyteach** [scipy/scipy#14735]
### Is your feature request related to a problem? Please describe.

This is being cross-posted here [from SO](https://stackoverflow.com/questions/69197193/solving-two-step-interpolation-in-python-and-numpy-scipy).

This problem is a little complicated, so I will try to make it as simple as possible.

Say that I have a table of values for which I want to perform two-step 1d interpolation; i.e., interpolation of a 2d value via interpolating in 1d *twice*. Note that this is a different problem from that being solved by `scipy.interpolate.interp2d`, and the appropriate algorithm is going to be quite different.

Here is an example of source data for performing the interpolation. The column labels are the dependent variable, Z. The row labels are the SECOND independent variable, Y. The 2d, interior portion of the table is the FIRST independent variable, X.

```
   Z  1  2  3
Y
1     1  2  3   <-- X row 1
2     3  4  5   <-- X row 2
```
We want to produce a factory function. The factory produces another function which, given the above source data, performs appropriate twice-interpolation of any `x,y` pair. 

### Describe the solution you'd like.

Here I will call the factory function `twice_interp1d_with_2d_x`, and it will look like this;

```
def twice_interp1d_with_2d_x(x, y, z):
    """Produce an interpolating function of the form:
           f(x,y)
       The function interpolates an x and y value to a z value.
       Expects a 2d x argument. The y-axis is expected to be the rows; z is the columns."""
    ...
```

Here is the same function with type information attached (all variables are array_like; x is expected to be 2d, y and z are 1d):

```
def twice_interp1d_with_2d_x(x: array_like, y: array_like, z: array_like) -> Callable[[array_like, array_like], array_like]: ...
```

### Describe alternatives you've considered.

Using the existing `scipy.interpolate.interp1d` function (which includes additional `bounds_error` and `fill_value` arguments), I have already written this function (but it is broken; see below), and the basic solution works like this:

```
from scipy.interpolate import interp1d

def twice_interp1d_with_2d_x(x, y, z, bounds_error=True, fill_value=None):
    interp1d_rows = [interp1d(row, z, bounds_error=bounds_error, fill_value=fill_value) for row in x]
    def interpolator(x_inner, y_inner):
        temp_z = [f(x_inner) for f in interp1d_rows]
        return interp1d(y, temp_z, bounds_error=bounds_error, fill_value=fill_value)(y_inner)
    return interpolator
```

This works for many situations:

```
>>> twice_interp1d_with_2d_x(X, Y, Z)(3, 2)
array(1.)
```
*Side note: `interp1d` always produces numpy arrays; this result is a 0d (ie, atomic) array*

### Additional context (e.g. screenshots, GIFs)

But there is a big problem. Consider the case of `(x=4, y=2)`. The solution to this case should be:

```
>>> twice_interp1d_with_2d_x(X, Y, Z)(4, 2)
array(2.)
```

But instead, we get a `ValueError` because the value of 4 is beyond the upper bounds of the first row in X. We can try to fix this by passing `bounds_error=False`, but then we just get a `nan`:

```
>>> twice_interp1d_with_2d_x(X, Y, Z, bounds_error=False)(4, 2)
array(nan)
```

To make matters even more complicated, sometimes an array will be passed as the first argument or second argument, or BOTH arguments, and we might have to deal with `np.nan` for some combinations, but not others:

```
>>> twice_interp1d_with_2d_x(X, Y, Z, bounds_error=False)([3, 4], 2)
array([nan,  2.])
```

The question is: is there a simple, concise way to produce a correct version of this function using modern idiomatic python and numpy that I am overlooking? I know I could solve this using line after line of logic-- but it is going to be hours of work. Is this solvable in some quick, elegant way that I am not thinking of? 

If not, it seems to me something like this would be a good candidate to be added to the `scipy.interpolate` module. Note that I have limited the problem description to the case of a table with a 2d x value; however, it could just as easily be a 2d y or 2d z value (but the case of the z value is simple: no boundary error problem exists).

**Comment by Ricyteach** [comment]
For the curious: below is some actual real-world data (from the snow chapter of US reference building code called ASCE 7) that requires this kind of interpolation (2d x values, 1d y and z values).

![image](https://user-images.githubusercontent.com/4923361/133480660-d1474863-13d5-499c-afb5-9d9d425135f8.png)

The table describing this chart looks like this:

```
_FIG7P4D1_Cs__STR = """
                        C_t
                        1.0     1.1     1.2
Surface Type    C_s
slippery        1.0     0       0       0
                1.0     5       10      15
                0       70      70      70
                0       90      90      90
other           1.0     0       0       0
                1.0     30      37.5    45
                0       70      70      70
                0       90      90      90
"""
```

**Comment by tupui** [comment]
Hi, do I get this right that you are looking for something like constructing let say an enthalpy–entropy chart (Mollier diagram)? So to have a set of 1d curves for a given set of fixed parameters?

**Comment by Ricyteach** [comment]
> Hi, do I get this right that you are looking for something like constructing let say an enthalpy–entropy chart (Mollier diagram)? So to have a set of 1d curves for a given set of fixed parameters?

It is similar to that. However, an enthalpy–entropy chart (Mollier diagram) can utilize 2d interpolation as already written in the `scipy.interpolate.inter2d` function, which essentially treats the interpolation space as a 3d surface (2d x and y, and z is the third d). This twice-interpolation algorithm is a different thing, and will produce different answers than `interp2d` or n-D, and as I described, in some cases `interp2d` can't handle it at all.

> I am not sure I see why you could not formulate your problem as a n-D interpolation. Z depends on x and y that can have any shape but you can flatten all that. It's just on the inputs that you would need to transform the data I would say. I might be missing something.

If you flatten in the way you describe, n-D doesn't produce the expected twice-interpolate answer in many cases. From the simplified example above, if we try to use `interp2d` (which I believe is the same algorithm as n-D, just excluded to two dimensions) we see the following example:

```
import pytest
import numpy as np
from scipy.interpolate import interp2d

@pytest.mark.parametrize("x, y, x_arr, y_arr, z_arr, expected", [
    (5, 1.0, [[0, 0, 0],
            [5, 10, 15],
            [70, 70, 70],
            [90, 90, 90],
            ], [1.0, 1.1, 1.2]*4, [1.0, 1.0, 0, 0]*3, 1.0),
])
def test_interp2d(x, y, x_arr, y_arr, z_arr, expected):
    result = interp2d(x_arr, y_arr, z_arr)(x, y)
    np.testing.assert_array_equal(result, expected)
```

This fails with:

```
E       AssertionError: 
E       Arrays are not equal
E       
E       Mismatched elements: 1 / 1 (100%)
E       Max absolute difference: 0.63833571
E       Max relative difference: 0.63833571
E        x: array([0.361664])
E        y: array(1.)
```

But my algorithm passes:

```
import pytest
import numpy as np
from scipy.interpolate import interp1d


def twice_interp1d_with_2d_x(x_2d, y_1d, z_1d, bounds_error=True, fill_value=None):
    interp1d_rows = [interp1d(row, z_1d, bounds_error=bounds_error, fill_value=fill_value) for row in x_2d]

    def interpolator(x_inner, y_inner):
        temp_z = [f(x_inner) for f in interp1d_rows]
        return interp1d(y_1d, temp_z, bounds_error=bounds_error, fill_value=fill_value)(y_inner)

    return interpolator


# NOTE: the 2d x_arr has been transposed here; this is the same problem as above though
@pytest.mark.parametrize("x, y, x_arr, y_arr, z_arr, expected", [
    (5, 1.0, [[0, 5, 70, 90],
              [0, 10, 70, 90],
              [0, 15, 70, 90]
              ], [1.0, 1.1, 1.2], [1.0, 1.0, 0, 0], 1.0),
])
def test_twice_interp1d_with_2d_x(x, y, x_arr, y_arr, z_arr, expected):
    result = twice_interp1d_with_2d_x(x_arr, y_arr, z_arr)(x, y)
    np.testing.assert_array_equal(result, expected)
```

Rick.

**Comment by tupui** [comment]
Thanks for providing some simpler code example. It will help to think about the problem (I will try to get more time to).

True for the unpacking. When writing this I had more in mind some copying than plain unpacking. Hence what I wanted to say with data manipulation.

**Comment by Ricyteach** [comment]
> Thanks for providing some simpler code example. It will help to think about the problem (I will try to get more time to).
> 
> True for the unpacking. When writing this I had more in mind some copying than plain unpacking. Hence what I wanted to say with data manipulation.

Thanks for taking time to think about it! Look forward to any thoughts.

**Comment by Ricyteach** [comment]
Note that I had a mistake in the formulation above; I will delete that part of the comment. See below for a better test regimen. There are 8 out of 21 failures, but a couple of them are within E-16 of the answer, so it's more like 5 or 6 failures.

```
import pytest
import numpy as np
from scipy.interpolate import interp2d

@pytest.mark.parametrize("x, y, expected", [
    (0, 1.0, 1.0),
    (5, 1.0, 1.0),
    (70, 1.0, 0),
    (90, 1.0, 0),
    (0, 1.1, 1.0),
    (10, 1.1, 1.0),
    (70, 1.1, 0),
    (90, 1.1, 0),
    (0, 1.2, 1.0),
    (15, 1.2, 1.0),
    (70, 1.2, 0),
    (90, 1.2, 0),

    (1, 1.0, 1.0),
    (37.5, 1.0, 0.5),
    (80, 1.0, 0),
    (1, 1.1, 1.0),
    (40, 1.1, 0.5),
    (80, 1.1, 0),
    (1, 1.2, 1.0),
    (42.5, 1.2, 0.5),
    (80, 1.2, 0),
])
def test_interp2d_FIG7P4D1_Cs(x, y, expected):
    x_arr = [[0, 0, 0],
            [5, 10, 15],
            [70, 70, 70],
            [90, 90, 90]]
    y_arr = [1.0, 1.1, 1.2]*4
    z_arr = [[1.0]*3, [1.0]*3, [0]*3, [0]*3]
    result = interp2d(x_arr, y_arr, z_arr)(x, y)
    np.testing.assert_array_equal(result, expected)


_FIG7P4D1_Cs__STR = """
                        C_t
                        1.0     1.1     1.2
Surface Type    C_s
slippery        1.0     0       0       0
                1.0     5       10      15
                0       70      70      70
                0       90      90      90
other           1.0     0       0       0
                1.0     30      37.5    45
                0       70      70      70
                0       90      90      90
"""

```

**Comment by tupui** [comment]
I went again your `twice_interp1d_with_2d_x` and to me it still sounds strange to do this. You are using the results from an interpolation to do another interpolation. Which means that the second interpolation is based on possible wrong interpolated values. I really don't see how having a 2 step process could improve the results since you don't add more information. It's just a matter of using it efficiently.

The only reason I would see to do this in 2 steps would be to have some knowledge about the first interpolation needing a different treatment than the other interpolation. A different function form for instance. This does not seem to be the case since you would use twice the same interpolation method.

Even if, this could be solved using smarter interpolation methods like [Rbf](https://scipy.github.io/devdocs/reference/generated/scipy.interpolate.Rbf.html) or Gaussian processes (in sklearn for instance since we don't have this in SciPy) by specifying a specific kernel or even building yours.

**Comment by Ricyteach** [comment]
Thanks for looking over it.

I'm not familiar with those other interpolation methods and how they differ. Maybe I should give those a try, but I doubt they will solve the problem.

The bottom line is, whether or not it sounds strange to do this, this two-step process is how interpolation is done every day by professional civil engineers using the building code all around the world, and it leads to the expected answers more reliably than treating the data like a description of a 3D surface and interpolating that way.

However I'm mindful at this point that I might be engaging in an episode of YAGNI here-- since I have not actually identified any tables or charts in the ASCE 7 building code that has different domains for the independent variable. I expect there are some, but until I actually identify one and test the different interpolation algorithms against it (instead of made up data like I have given above), I should probably defer this discussion.

**Comment by tupui** [comment]
> The bottom line is, whether or not it sounds strange to do this, this two-step process is how interpolation is done every day by professional civil engineers using the building code all around the world, and it leads to the expected answers more reliably than treating the data like a description of a 3D surface and interpolating that way.

If you have some literature comparing such 2 step 1D-interpolation with a n-D interpolation I would be interested.

I am not saying that it's not used. But I also don't blindly accept a method under the only argument that some professionals use it (cf Milgram) 😉. I am an aerospace engineer by training and never had to do a 2 step interpolation. Again not saying it does not exist or it does not perform well. And I am sure in this field they might use this method for some good reason. Just questioning the maths behind the idea and wondering if there might be another way. It would not be the first/and last time that some people use different tools to solve the same underlying problem, just slightly framed in a different manner.

**Comment by Ricyteach** [comment]
Understood.

But keep in mind it's a two-part argument, though. Not just that pros use it, but my testing regimen shows the 2d interpolation algorithm method gives a significantly unexpected answer for about 5 or 6 of 21 examples I provided. The two-step interpolation provides a expected answers for all examples.

**Comment by tupui** [comment]
Yes of course 😃 Just to be clear, hope you don't feel this discussion as an attack of any sort. I am just trying to get the problem right and see how this could fit in SciPy. We only consider things which are general enough to serve multiple domains. Hence my questions about literature. It's almost a hard requirement to have a new method backed by a highly cited reference.

Back to this example, the bad results could simply be explained by the fact that this interpolant is inapropriate. The problem  can be solved with a simple decision tree. Almost just looking at `x` we can give `z`. Again, I am not saying that all such problem can be solved with a decision tree of course.

**Comment by Ricyteach** [comment]
Well given that you're a volunteer trying to be of HELP to me, it would be ridiculous to feel attacked! :D THANK YOU so much for the input.

I'll have to think about literature. The only thing I can come up with at the moment is to point you to the building code itself. Here is another great example:

![image](https://user-images.githubusercontent.com/4923361/134392862-33d93202-cb24-4cc3-8163-0483d6b2a261.png)

Note the directive I have highlighted at the bottom to _linearly interpolate_ between the two curves. This means the user of the building code is required to use a GCp coefficient value that conforms to a two-step interpolation process of:

1. Interpolate the value from the two curves
2. Interpolate between the two values you obtained

I have not implemented this figure yet (haven't had a need); however, this is another instance in which I expect that naively using the `interpolate.interp2d` function, thus treating the curves like slices of a 3 surface, will lead to serious errors compared to two-step linear interpolation. And thus will not conform to the requirements of the building code.

**Comment by Ricyteach** [comment]
For reference: [here is my implementation](https://github.com/Ricyteach/asce7/blob/1aa859b912877e9cdbcadb6970320591f2bf7540/asce7/interp.py#L88) of the two-step algorithm. It currently handles cases in which any one of the three input arrays (X, Y, or Z) might be 2d and the other two are 1D. And [here](https://github.com/Ricyteach/asce7/blob/master/tests/test_interp.py) is the test suite.

**Comment by Patol75** [comment]
It seems to me that what you are trying to achieve, at least in the way that you described it, is similar to an inverse problem for `interp2d`. Using `interp2d`, the logical approach would be to find an interpolated value `x` within `X` given `y` and `z` coordinates that belong, respectively, to `Y` and `Z`. However, here, it looks like you already have `x`, and you also know at which `y` it was sampled. Thereby, you are asking the question: given `y`, at which value `z` of `Z` should I interpolate `X` to obtain `x`? At least, that is the way I see it from the summary you gave. If this is correct, I am tempted to say this is a fair question, but I am not sure if it is in the current scope of SciPy.

Regarding your issue with `nan` values, I have suggested a solution on StackOverflow, which I am cross-posting here to illustrate that it seems to work for the test case you posted above.

```
import numpy as np
import pytest
from scipy.interpolate import interp1d


def fun(X, Y, Z, x, y, **kwargs):
    X, Y, Z = np.asarray(X), np.asarray(Y), np.asarray(Z)
    if y in Y:
        return interp1d(X[np.nonzero(Y == y)[0][0]], Z, **kwargs)(x)
    else:
        return interp1d(Y, [interp1d(row, Z, **kwargs)(x) for row in X],
                        **kwargs)(y)


@pytest.mark.parametrize("x, y, expected", [
    (0, 1, 1), (5, 1, 1), (70, 1, 0), (90, 1, 0), (0, 1.1, 1), (10, 1.1, 1),
    (70, 1.1, 0), (90, 1.1, 0), (0, 1.2, 1), (15, 1.2, 1), (70, 1.2, 0),
    (90, 1.2, 0), (1, 1, 1), (37.5, 1, 0.5), (80, 1, 0), (1, 1.1, 1),
    (40, 1.1, 0.5), (80, 1.1, 0), (1, 1.2, 1), (42.5, 1.2, 0.5), (80, 1.2, 0)])
def test_interp2d_FIG7P4D1_Cs(x, y, expected):
    x_arr = [[0, 5, 70, 90], [0, 10, 70, 90], [0, 15, 70, 90]]
    y_arr = [1, 1.1, 1.2]
    z_arr = [1, 1, 0, 0]
    result = fun(x_arr, y_arr, z_arr, x, y)
    np.testing.assert_array_equal(result, expected)

```

**Comment by Ricyteach** [comment]
That is a nice solution and it does pass my tests-- thank you for providing it. It is succinct and just really nice.

However, I guess my tests weren't good enough since it doesn't pass other use cases I haven't yet provided here. I'll have to look really closely at your solution and see if it can be adapted for those. I'll post an update later when I have some more time.

But still: pretty cool that it does pass all my tests!

**Comment by ev-br** [comment]
OK, at this stage ISTM that the original query has been responded to (even if not in a fully complete way), a possibly full solution can be cooked up using tools scipy.interpolate provides already, and there does not seem to be much to track for a possible enhancement. Closing, but do feel free to discuss.
