### ISSUE TITLE
BUG: issue in betainc() documentation

### ISSUE THREAD

**Issue by Xunius** [scipy/scipy#14744]
### Describe your issue.

This is related to https://github.com/scipy/scipy/issues/1350.

The documentation now includes a formula where the gamma term is multiplied by the integration. This is neither the incomplete beta function or the regularized incomplete function. 

The **Notes** section reads:

> The incomplete beta function is also sometimes defined without the gamma terms, in which case the above definition is the so-called regularized incomplete beta function. Under this definition, you can get the incomplete beta function by multiplying the result of the SciPy function by beta.

So it is describing an equation where the integral is **divided** by the gamma term, not **multiplied** by it.

Please rephrase the documentation to clarify.

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

1.2.1 1.19.2 sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)

**Comment by person142** [comment]
Hm, it is early in the morning and my eyes are bleary, but

```
Beta(a, b) = Gamma(a) * Gamma(b) / Gamma(a + b)
```

and in the formula we are multiplying by

```
Gamma(a + b) / ((Gamma(a) * Gamma(b)) = 1 / Beta(a, b)
```

i.e. it is dividing by `Beta`.

**Comment by Xunius** [comment]
@person142 Indeed! I was reading it late at night so my eyes were bleary.
Sorry for the noise, false alarm.
