### ISSUE TITLE
Not able to install requirements.txt file getting the below error

### ISSUE THREAD

**Issue by SandeepAppium** [scipy/scipy#14742]
### Describe your issue.

Building wheels for collected packages: scipy
  Building wheel for scipy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-r6jd3zfp
       cwd: /tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/
  Complete output (161 lines):
  /tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/setup.py:114: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
  lapack_opt_info:
  lapack_mkl_info:
  customize UnixCCompiler
    libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
    NOT AVAILABLE

  openblas_lapack_info:
  customize UnixCCompiler
  customize UnixCCompiler
    libraries openblas not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
    NOT AVAILABLE

  openblas_clapack_info:
  customize UnixCCompiler
  customize UnixCCompiler
    libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries tatlas,tatlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib64
  customize UnixCCompiler
    libraries tatlas,tatlas not found in /usr/lib64
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib
  customize UnixCCompiler
    libraries tatlas,tatlas not found in /usr/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
  customize UnixCCompiler
    libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries satlas,satlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib64
  customize UnixCCompiler
    libraries satlas,satlas not found in /usr/lib64
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib
  customize UnixCCompiler
    libraries satlas,satlas not found in /usr/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
  customize UnixCCompiler
    libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib64
  customize UnixCCompiler
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib
  customize UnixCCompiler
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
  customize UnixCCompiler
    libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries f77blas,cblas,atlas not found in /usr/local/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib64
  customize UnixCCompiler
    libraries f77blas,cblas,atlas not found in /usr/lib64
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib
  customize UnixCCompiler
    libraries f77blas,cblas,atlas not found in /usr/lib
  customize UnixCCompiler
    libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
  customize UnixCCompiler
    libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  accelerate_info:
    NOT AVAILABLE

  /usr/local/lib/python3.8/dist-packages/numpy/distutils/system_info.py:639: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    self.calc_info()
  lapack_info:
  customize UnixCCompiler
    libraries lapack not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
    NOT AVAILABLE

  /usr/local/lib/python3.8/dist-packages/numpy/distutils/system_info.py:639: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    self.calc_info()
  lapack_src_info:
    NOT AVAILABLE

  /usr/local/lib/python3.8/dist-packages/numpy/distutils/system_info.py:639: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE

  Running from scipy source directory.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/setup.py", line 474, in <module>
      setup_package()
    File "/tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/setup.py", line 470, in setup_package
      setup(**metadata)
    File "/usr/local/lib/python3.8/dist-packages/numpy/distutils/core.py", line 137, in setup
      config = configuration()
    File "/tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/setup.py", line 388, in configuration
      config.add_subpackage('scipy')
    File "/usr/local/lib/python3.8/dist-packages/numpy/distutils/misc_util.py", line 1034, in add_subpackage
      config_list = self.get_subpackage(subpackage_name, subpackage_path,
    File "/usr/local/lib/python3.8/dist-packages/numpy/distutils/misc_util.py", line 1000, in get_subpackage
      config = self._get_configuration_from_setup_py(
    File "/usr/local/lib/python3.8/dist-packages/numpy/distutils/misc_util.py", line 942, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy/setup.py", line 15, in configuration
      config.add_subpackage('linalg')
    File "/usr/local/lib/python3.8/dist-packages/numpy/distutils/misc_util.py", line 1034, in add_subpackage
      config_list = self.get_subpackage(subpackage_name, subpackage_path,
    File "/usr/local/lib/python3.8/dist-packages/numpy/distutils/misc_util.py", line 1000, in get_subpackage
      config = self._get_configuration_from_setup_py(
    File "/usr/local/lib/python3.8/dist-packages/numpy/distutils/misc_util.py", line 942, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy/linalg/setup.py", line 19, in configuration
      raise NotFoundError('no lapack/blas resources found')
  numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
  ----------------------------------------
  ERROR: Failed building wheel for scipy
  Running setup.py clean for scipy
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec
  Complete output (11 lines):
  /tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/setup.py:114: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).

  ----------------------------------------
  ERROR: Failed cleaning build dir for scipy
Failed to build scipy
Installing collected packages: scipy, python-dateutil, configparser, xgboost, pandas, minio, gensim
  Attempting uninstall: scipy
    Found existing installation: scipy 1.7.1
    Uninstalling scipy-1.7.1:
      Successfully uninstalled scipy-1.7.1
    Running setup.py install for scipy ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1rn3l91t/install-record.txt --single-version-externally-managed--compile --install-headers /usr/local/include/python3.8/scipy
         cwd: /tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/
    Complete output (170 lines):
    /tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/setup.py:114: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      import imp

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)

    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE

    openblas_lapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE

    openblas_clapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib64
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib64
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib64
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib64
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib64
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib64
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib64
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    accelerate_info:
      NOT AVAILABLE

    /usr/local/lib/python3.8/dist-packages/numpy/distutils/system_info.py:639: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
    customize UnixCCompiler
      libraries lapack not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE

    /usr/local/lib/python3.8/dist-packages/numpy/distutils/system_info.py:639: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE

    /usr/local/lib/python3.8/dist-packages/numpy/distutils/system_info.py:639: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE

    Running from scipy source directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/setup.py", line 474, in <module>
        setup_package()
      File "/tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/setup.py", line 470, in setup_package
        setup(**metadata)
      File "/usr/local/lib/python3.8/dist-packages/numpy/distutils/core.py", line 137, in setup
        config = configuration()
      File "/tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/setup.py", line 388, in configuration
        config.add_subpackage('scipy')
      File "/usr/local/lib/python3.8/dist-packages/numpy/distutils/misc_util.py", line 1034, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "/usr/local/lib/python3.8/dist-packages/numpy/distutils/misc_util.py", line 1000, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "/usr/local/lib/python3.8/dist-packages/numpy/distutils/misc_util.py", line 942, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "/usr/local/lib/python3.8/dist-packages/numpy/distutils/misc_util.py", line 1034, in add_subpackage
        config_list = self.get_subpackage(subpackage_name, subpackage_path,
      File "/usr/local/lib/python3.8/dist-packages/numpy/distutils/misc_util.py", line 1000, in get_subpackage
        config = self._get_configuration_from_setup_py(
      File "/usr/local/lib/python3.8/dist-packages/numpy/distutils/misc_util.py", line 942, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/linalg/setup.py", line 19, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
    ----------------------------------------
  Rolling back uninstall of scipy
  Moving to /usr/local/lib/python3.8/dist-packages/scipy-1.7.1.dist-info/
   from /usr/local/lib/python3.8/dist-packages/~cipy-1.7.1.dist-info
  Moving to /usr/local/lib/python3.8/dist-packages/scipy.libs/
   from /usr/local/lib/python3.8/dist-packages/~cipy.libs
  Moving to /usr/local/lib/python3.8/dist-packages/scipy/
   from /usr/local/lib/python3.8/dist-packages/~cipy
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b_ad1fui/scipy_bebacd68c6e14294901683aca68151ec/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1rn3l91t/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/scipy Check the logs for full command output.

### Reproducing Code Example

```python
Requirements.txt file

flask==1.1.1
flask-cors==3.0.8
waitress==1.4.3
uWSGI==2.0.18
pika==1.0.0
pydantic==1.1.1
elasticsearch==7.0.0
requests==2.22.0
httpretty==0.9.7
sure==1.4.11
bump2version==0.5.11
flake8==3.7.9
nltk==3.4.5
scikit-learn==0.19.2
numpy==1.16.4
scipy==1.1.0
xgboost==0.90
python-dateutil==2.8.1
minio==6.0.0
gensim==3.5.0
pandas==1.1.4
```

### Error message

```shell
sudo pip3 install -r  requirements.txt
```

### SciPy/NumPy/Python version information

python 3.8

**Comment by andyfaff** [comment]
The requirements.txt file is attempting to install `scipy 1.1.0` which was released 1.5 years before Python 3.8 was available, that's why the pip install process was trying to build scipy from source. If you wish to use that specific version of scipy without needing to build the package then you would need to be using Python 3.7.
The build is failing because you don't have a BLAS library available, or specified in `site.cfg`. Installing BLAS might get around the build issue, but I'm still not sure you'd be able to use that pinned version of scipy with Python 3.8.

Lastly, installing Python libraries with `sudo` is highly inadvisable, as it has high possibility of interfering with the system Python setup. Using a virtualenv is good in this kind of situation.
