### ISSUE TITLE
DPSS Multi-Tapering and STFT

### ISSUE THREAD

**Issue by tensionhead** [scipy/scipy#14740]
I tried to implement a standard multi-tapered short time fourier analysis only using functionality from `scipy.signal` and ran into problematic results.

## Reproducing Code Example
```python
import numpy as np                                                                        
from scipy.signal import windows, stft                                                    
from numpy.random import randn                                                            
                                                                                          
nSamples = 1000                                                                           
win_size = nSamples // 4                                                                  
# create a slepian sequence of 6 orthogonal tapers                                        
slepians = windows.dpss(win_size, NW=2, Kmax=6)                                           
signal = randn(nSamples)                                                                  
                                                                                          
# stft for each taper                                                                     
for order, taper in enumerate(slepians):                                                  
    freqs, times, pxx = stft(signal, window=taper, nperseg=win_size)     
    # the mean power over all windows                                            
    power_sum = np.abs(pxx).mean()   
    print(f'order {order}: {power_sum:e}')
```
This gives something like:
```bash
order 0: 6.270107e-02
order 1: 3.343302e+12
order 2: 1.013352e-01
order 3: 2.472677e+13
order 4: 2.233694e-01
order 5: 8.161814e+12
```
In multi-taper analysis one would now average along the different slepians to get a spectral estimate. However this clearly can't work here as the odd slepians give a power spectral estimate >10orders of magnitude larger than the even ones. The reason for this is the **built-in normalization** of SciPy's `stft`, which normalizes by the window norm. However, mathematically the odd Slepians fullfill `win.sum() = 0`, in practice it's often more like `win.sum() = 1e-13`, hence SciPy's normalization blows up the result. I ran some more in depth numerical tests and found some troubling instances where these number can become astronomical.

## Suggestion

Maybe add a `norm=None` parameter to `stft`, right now a certain `norm=spectral`is anyways enforced internally in `scipy.signal.spectral._spectral_helper(...)`.

**Comment by tensionhead** [comment]
Hey @dhruv9vats, sorry for the delay but I am mostly afk these days until next week.. So yeah, if you wanna give it a shot go ahead! For me it now looks like that also 'ordinary' multi-taper analysis (so no short-time windowing) will produce the same problems with scipy's slepians, as some **window norm** is  always taken within the fft backends. I think to look at `scipy.signal.spectral._spectral_helper(...)` and figuring out how the different **frontend** functions like `signal.psd` or `signal.stft` make use of it would be a good starting point.  Right now in my own application code,  I have to 'de-normalize' by the window.sum(), which might lead to numerical instabilities (as for the odd slepians mathematically this will be zero as described in the post above). Imho having a `norm=None` option for all these methods would be best, as the slepians are already correctly normalized: I could recover the harmonic amplitudes of some test signals after 'de-normalization'. Let me know if you have any more questions!

**Comment by dhruv9vats** [comment]
So while I'm still tracing and wrapping my head around how `scipy.signal.spectral._spectral_helper(...)` is being used by the different functions, from a preliminary look at the code snippet you provided, I tried using the `sym=False` keyword argument ([documentation link](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.windows.dpss.html?highlight=dpss#scipy.signal.windows.dpss))  when generating the Slepians (as I used it during my project to implement the Multitaper periodogram), so the line looks like 

```python
slepians = windows.dpss(win_size, NW=2, Kmax=6, sym=False)
```
produces the results:
```
order 0: 6.557644e-02
order 1: 8.444441e+01
order 2: 1.072922e-01
order 3: 8.913163e+00
order 4: 2.323713e-01
order 5: 4.216890e+00
```

which looks slightly more relevant.

So if your testing using this keyword argument produces similar, more digestible results, this could be a possible lead to explore.

I'm sorry if I'm overlooking something obvious.

**Comment by tensionhead** [comment]
Mmh.. I definitely overlooked that option, probably as it didn't made much sense to me: imho a symmetric function over a symmetric interval [-x, x] should also be periodic with respect to this interval as f(x) = f(-x). Plotting the slepians with or without `sym=False` also only shows minor differences, yet as you showed clearly enough to get quite far away from the odd 0-sum. Now the best would be to test the behavior for a simple harmonic signal with `sym=False` in a standard multi-taper analysis, maybe using `scipy.signal.welch`, and see if it's possible to recover the amplitudes. This would show that the normalization with that dpss option now indeed works fine. I can whip sth like this up next week, but if you wanna have a go in the mean time go ahead ;)

PS: the program flow internally is `scipy.signal.welch` --> `scipy.signal.csd' --> `scipy.signal._spectral_helper`

**Comment by dhruv9vats** [comment]
Sorry for the delay, was caught up in some work.

I tried this with my shallow understanding:

Using a periodic square wave for the harmonic signal:
```python
nSamples = 1000
t = np.linspace(0, 1000, nSamples, endpoint=False)
sig = signal.square(2 * np.pi * 5 * t)
```
The first 100 data points of the signal:
![5](https://user-images.githubusercontent.com/65168627/135972561-311009bf-65d0-4751-bea4-dfbb12ccb15c.png)

I tried using a combination of `win_size = (nSamples, nSamples // 4)` and `sym = (True, False)`, using the code:

```python
for sym in (True, False):
    for win_size in (nSamples, nSamples // 4):
        slepians = signal.windows.dpss(
            win_size, NW=2, Kmax=6, sym=sym)
        power_combined = []
        print(f"win_size: {win_size}, sym: {sym}")
        for order, taper in enumerate(slepians):
            freq_welch, pxx = signal.welch(sig, window=taper, nperseg=win_size)
            power_combined.append(pxx)
            # the mean power over all windows
            power_sum = np.abs(pxx).mean()
            print(f'order {order}: {power_sum:e}')

        power_combined = np.mean(power_combined, axis=-2)
        fig = plt.figure()

        freq_periodogram, psd = signal.periodogram(sig)
        plt.plot(freq_periodogram, psd, label="periodogram")
        plt.plot(freq_welch, power_combined, label="welch_dpss")
        plt.title(f"win_size: {win_size}, sym: {sym}")
        plt.legend()
```
The resulting plots:
![1](https://user-images.githubusercontent.com/65168627/135976378-95c17ea4-cb16-407b-a1fe-ffbfe473bc30.png)

![2](https://user-images.githubusercontent.com/65168627/135976388-c8f178b3-af92-47c9-9645-e86e83239fe8.png)


![3](https://user-images.githubusercontent.com/65168627/135976396-a15709af-6261-48f7-bf08-f32bc79baff0.png)

![3](https://user-images.githubusercontent.com/65168627/135976405-2b6eb271-0094-448e-b27a-40e1d11fe068.png)

I'm pretty sure I'm missing the point here, so please do tell what your thoughts are.

Also, here is the `power_sum` metric you used: (not really sure if these are even valid, as in, do they even make sense for the `welch` method)
```
win_size: 1000, sym: True
order 0: 1.995787e+00
order 1: 1.995934e+00
order 2: 1.995840e+00
order 3: 1.996039e+00
order 4: 1.996343e+00
order 5: 1.997121e+00
win_size: 250, sym: True
order 0: 1.983833e+00
order 1: 1.984301e+00
order 2: 1.983856e+00
order 3: 1.983630e+00
order 4: 1.983987e+00
order 5: 1.983734e+00
win_size: 1000, sym: False
order 0: 1.995787e+00
order 1: 1.995934e+00
order 2: 1.995841e+00
order 3: 1.996039e+00
order 4: 1.996344e+00
order 5: 1.997124e+00
win_size: 250, sym: False
order 0: 1.983833e+00
order 1: 1.984304e+00
order 2: 1.983846e+00
order 3: 1.983618e+00
order 4: 1.984013e+00
order 5: 1.983826e+00
```

Sidenote:
This might seem like marketing, but it's really not 😅

Using the project where I implemented the multitaper periodogram,
for the code:
```python
from stingray import Lightcurve, Multitaper

lc = Lightcurve(t, sig, err_dist="gauss", err=np.ones_like(t))

mtp = Multitaper(lc, NW=3, norm="abs")

plt.plot(freq_periodogram, psd, label="periodogram")
plt.plot(mtp.freq, mtp.power, label="stingray_multitaper")
plt.legend()
```

this is the result:
![6](https://user-images.githubusercontent.com/65168627/135975649-ec1d3191-8681-4dfb-bb6d-6e824b5ad44b.png)

which seems more in line, but manually does the Tapering --> FFT --> (optional adaptive weighing) --> PSD steps internally.

**Comment by tensionhead** [comment]
Ok, that's a lot of information to process here.. 

I agree that it doesn't look too bad, most and foremost the `sym=True/False` for the slepians has apparently no effect anymore! I traced it to the spectral parameter `scaling`, which has the default of `scaling='density'`  for both `signal.periodogram` and `signal.welch`, but `scaling='spectrum'` for `signal.stft`. Try to add `scaling='spectrum'` to your `signal.welch(...)` calls above, and you will see everything blows apart! With `scaling='density'` the quadratic norm of the window inside `signall.spectral._spectral_helper()` is taken, and hence the problematic sum-to-zero for the odd slepians disappears. So with this we found that the default behaviors of these `scipy.signal` spectral estimation methods differ, and that matters a lot for multi-taper analysis! Whereas the slepian `sym` parameter has no effect for `scaling='density'`.

## Harmonic Amplitudes
I went the other way around, and build a little test-scenario with `scaling='spectrum'` as to be close to my initial issue with `scipy.stft`:

```python
import numpy as np                                                                                                        
from scipy.signal import windows, periodogram                                                                             
                                                                                                                          
nSamples = 2500                                                                                                           
                                                                                                                          
# signal parameters                                                                                                       
fs = 1000 # 1000Hz sampling frequency                                                                                     
tvec = np.arange(0, nSamples) * 1 / fs                                                                                    
freq = 250 # Hz                                                                                                           
Ampl = 8                                                                                                                  
signal = Ampl * np.cos(2 * np.pi * freq * tvec)                                                                           
                                                                                                                          
# hann tapered power spectrum                                                                                             
freqs_hann, pxx_hann = periodogram(signal, fs=fs, window='hann', scaling='spectrum')                                      
                                                                                                                          
# amplitude spectrum -> pxx gives Ampl**2 / 2                                                                             
ampl_hann = np.sqrt(2 * pxx_hann)                                                                                         
peak = pxx_hann.max()                                                                                                     
                                                                                                                          
print(f'Real amplitude: {Ampl}, Hann peak: {ampl_hann.max()}')                                                            
                                                                                                                          
# create a slepian sequence of 6 orthogonal tapers                                                                        
Kmax = 6                                                                                                                  
sym = False   # change to True if needed                                                                                                            
slepians = windows.dpss(nSamples, NW=2, Kmax=Kmax, sym=sym)                                                               
                                                                                                                          
# -- uncomment this line for normalization! --                                                                           
# slepians = slepians * np.sqrt(Kmax) / np.sqrt(nSamples)                                                                 
# ---                                                                                                                     
                                                                                                                          
pxx_seq = []                                                                                                              
# fft for each taper                                                                                                      
for order, taper in enumerate(slepians):                                                                                  
    freqs, pxx = periodogram(signal, fs=fs, window=taper, scaling='spectrum')                                             
                                                                                                                          
    # -- uncomment this line for normalization! --                                                                       
    # pxx = taper.sum()**2 * pxx                                                                                          
    # ---                                                                                                                 
                                                                                                                          
    pxx_seq.append(pxx)                                                                                                   
                                                                                                                          
# average tapers                                                                                                          
pxx_slepian = np.mean(pxx_seq, axis=0)                                                                                    
ampl_slepian = np.sqrt(2 * pxx_slepian)                                                                                   
                                                                                                                          
print(f'Real amplitude: {Ampl}, MTM peak: {ampl_slepian.max()}') 
```
This gives me:

```shell
Real amplitude: 8, Hann peak: 8.0
Real amplitude: 8, MTM peak: 35292.08524782706
```

So by using a plain Hann window I can recover the harmonic amplitude of the test signal, whereas for the slepians neither `sym=True` nor `sym=False` give the correct result (but they still differ!!). Moreover, when you zoom into the power spectrum you see a wrong double peak, as the normalization bites us:

![DPSS norm](https://user-images.githubusercontent.com/10595420/136041277-1a77c430-c624-4da2-9d80-80ec57a92f06.png)

I actually now found a way to get  a correct normalization (via reversing scipy's and a little educated guessing), with the two commented lines in the script above I can get it to work :smiley: 

## Discussion
So what to make of it all? I will see that I get a correct normalization working (recovering the harmonic amplitude) with `scaling='density'`. If that works nicely, than at least the default **`scaling` should be the same** for all `scipy.signal` methods?! 

Right now out-of-the box multi-taper analysis with `stft` is definitely broken, as it is for the other methods with `scaling='spectrum'`. The cleanest solution imho would still be to have an option to turn off automatic normalization for expert users (`scaling=None`), so they can take care about normalization themselves.

**Comment by vollbier** [comment]
With the merging of PR #17408 there is an improved STFT implementation, named [ShortTimeFFT](https://scipy.github.io/devdocs/reference/generated/scipy.signal.ShortTimeFFT.html), with more explicit scaling possibilities. A comparison to the existing implementation can be found [here](https://scipy.github.io/devdocs/tutorial/signal.html#comparison-with-legacy-implementation). 

You suggested to  allow the `scaling` parameter to be `None`, i.e., perform no scaling at all. This is possible with the [ShortTimeFFT](https://scipy.github.io/devdocs/reference/generated/scipy.signal.ShortTimeFFT.html) now. So perhaps this issue is resolved and could be closed. What do you think, @tensionhead?

**Comment by tensionhead** [comment]
Oh yes that looks good @vollbier! I'll see that I do a little test of that new implementation myself, then I am happy to close.

**Comment by tensionhead** [comment]
So finally I wanted to look at your new `ShortTimeFFT` @DietBru and I was happy to see that scipy 1.11.4 got released 2 days ago. However, I could not find this new stft implementation in the `scipy.signal` name space, even though your changes got merged in July?! Anyways, so then I tried getting a dev version of scipy to work on my system, but I failed :/ Installation itself worked, but trying to fire up ipython via `python dev.py ipython` does not work, and all other tries to import the repository did not work either. I probably have to contact them via github or the mailing list to solve that issue first.

**Comment by lucascolley** [comment]
> I was happy to see that scipy 1.11.4 got released 2 days ago. However, I could not find this new stft implementation in the scipy.signal name space, even though your changes got merged in July?!

1.11.4 was a bug fix release - most new features which have been merged since 1.11.0 will be released in 1.12.0, which is provisionally scheduled for release at the start of January :)

**Comment by tensionhead** [comment]
Ah I see, thx for that info @lucascolley :slightly_smiling_face: ! Just to add, after successfully installing scipy from source according to exactly the documentation you pointed at with
```bash
python dev.py build
```
unfortunately
```bash
python dev.py ipython
```
fails with
```bash
Traceback (most recent call last):                                                                           
  File "/home/xxx/scipy/dev.py", line 1482, in <module>                                                     
    cli()                                                                                                    
  File "/home/xxx/.cache/pypoetry/virtualenvs/scipy-stft-diAFXCzI-py3.10/lib/python3.10/site-packages/click/\
core.py", line 1157, in __call__                                                                             
    return self.main(*args, **kwargs)                                                                        
  File "/home/xxx/.cache/pypoetry/virtualenvs/scipy-stft-diAFXCzI-py3.10/lib/python3.10/site-packages/rich_c\
lick/rich_command.py", line 126, in main                                                                     
    rv = self.invoke(ctx)                                                                                    
  File "/home/xxx/.cache/pypoetry/virtualenvs/scipy-stft-diAFXCzI-py3.10/lib/python3.10/site-packages/click/\
core.py", line 1688, in invoke                                                                               
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                  
  File "/home/xxx/.cache/pypoetry/virtualenvs/scipy-stft-diAFXCzI-py3.10/lib/python3.10/site-packages/click/\
core.py", line 1434, in invoke                                                                               
    return ctx.invoke(self.callback, **ctx.params)                                                           
  File "/home/xxx/.cache/pypoetry/virtualenvs/scipy-stft-diAFXCzI-py3.10/lib/python3.10/site-packages/click/\
core.py", line 783, in invoke                                                                                
    return __callback(*args, **kwargs)                                                                       
  File "/home/xxx/.cache/pypoetry/virtualenvs/scipy-stft-diAFXCzI-py3.10/lib/python3.10/site-packages/pydevt\
ool/cli.py", line 271, in callback                                                                           
    sys.exit(cls.run(**kwargs))                                                                              
  File "/home/xxx/scipy/dev.py", line 1160, in run                                                           
    cls._setup(pythonpath, **kwargs)                                                                         
  File "/home/xxx/scipy/dev.py", line 1123, in _setup                                                        
    Build.run(add_path=True, **vals)                                                                         
  File "/home/xxx/scipy/dev.py", line 634, in run                                                            
    cls.install_project(dirs, args)                                                                          
  File "/home/xxx/scipy/dev.py", line 536, in install_project                                                
    raise RuntimeError("Can't install in non-empty directory: "                                              
RuntimeError: Can't install in non-empty directory: '/home/xxx/scipy/build-install'
```

**Comment by lucascolley** [comment]
ah, there was a similar problem reported in https://github.com/scipy/scipy/issues/19153#issuecomment-1698376006. Unfortunately it looks like you'll have to do some debugging of your environment, but maybe a `git clean -xdf` will do? In any case, it hopefully shouldn't be as convoluted as gh-19153, that was a particularly unlucky case.

**Comment by tensionhead** [comment]
Ok, I managed to get an environment with the latest `scipy:main (1.12.0)`. To test the new `ShortTimeFFT` interface I ran it and the legacy `stft` over a white noise signal with slepian windows (aka multi-tapering):
```python
import numpy as np                                                                                                                                           
from scipy.signal import windows, stft, ShortTimeFFT                                                                                                         
from numpy.random import randn                                                                                                                               
                                                                                                                                                             
nSamples = 1000                                                                                                                                              
win_size = nSamples // 10                                                                                                                                    
noverlap = win_size // 2                                                                                                                                     
fs = 1000                                                                                                                                                    
# create a slepian sequence of 4 orthogonal tapers                                                                                                           
slepians = windows.dpss(win_size, NW=2, Kmax=4)                                                                                                              
# white noise                                                                                                                                                
signal = randn(nSamples)                                                                                                                                     
                                                                                                                                                             
print('order', '\t',                                                                                                                                         
      'legacy stft', '\t',                                                                                                                                 
      'SFT magnitude', '\t\t',                                                                                                                               
      'SFT None')                                                                                                                                            
print()                                                                                                                                                      
                                                                                                                                                             
# stft for each taper                                                                                                                                        
for order, taper in enumerate(slepians):                                                                                                                     
    freqs, times, pxx_legacy = stft(signal, fs=fs,                                                                                                           
                                    window=taper,                                                                                                            
                                    nperseg=win_size,                                                                                                        
                                    noverlap=noverlap)                                                                                                       
                                                                                                                                                             
    # the mean power over all windows                                                                                                                        
    legacy_result = f'{np.abs(pxx_legacy).mean():e}'                                                                                                         
                                                                                                                                                             
    # New STFT:                                                                                                                                              
    SFT = ShortTimeFFT(taper, fs=fs,                                                                                                                         
                       hop=len(taper) - noverlap,                                                                                                            
                       fft_mode='centered',                                                                                                                  
                       scale_to='magnitude')                                                                                                                 
    pxx = SFT.stft(signal)                                                                                                                                   
    new_result = f'{order}: {np.abs(pxx).mean():e}'                                                                                                          
                                                                                                                                                             
    SFT = ShortTimeFFT(taper, fs=fs,                                                                                                                         
                       hop=len(taper) - noverlap,                                                                                                            
                       fft_mode='centered',                                                                                                                  
                       scale_to=None)                                                                                                                        
    pxx = SFT.stft(signal)                                                                                                                                   
    new_none_result = f'{order}: {np.abs(pxx).mean():e}'                                                                                                     
                                                                                                                                                             
    print(f'{order}:', '\t',                                                                                                                                 
          legacy_result, '\t',                                                                                                                               
          new_result, '\t',                                                                                                                                  
          new_none_result) 
```

with the results for the time- and frequency-averaged powers:
```bash
order 	 legacy stft 	 SFT magnitude 		 SFT None

0: 	 1.043207e-01 	 0: 1.047680e-01 	 0: 8.654323e-01
1: 	 1.571661e+13 	 1: 1.538749e+13 	 1: 8.549783e-01
2: 	 1.670870e-01 	 2: 1.675376e-01 	 2: 8.605767e-01
3: 	 4.795412e+13 	 3: 5.158598e+13 	 3: 8.705335e-01
```

So with `scaling='magnitude'` the new `ShortTimeFFT` produces very similar output as the legacy `stft`. Note that the initial problem of that issue here shows (of course) again: the odd slepian windows have a norm of 0, and hence normalization (aka scaling) blows up the result making taper-averaging to obtain a multi-taper estimate impossible. 
However now with `scaling=None` I can get a nice set of single-taper results, which are ready to be averaged.  So many thx to @DietBru , this solves also this issue here and I am happily closing :rocket:

PS: Why the resulting average power is not exactly 1 here with `scaling=None` I am not sure, maybe edge effects?!

**Comment by DietBru** [comment]
As a far as I understand multi-tapered Fourier analysis, it only works of estimating the power spectral density but not for calculating a magnitude spectrum. Thus you need to average over the absolute square not the absolute value of the spectrum to obtain an average power of 1. Also ``scaling='psd'`` instead of ``scaling='magnitude'`` should be used.

**Comment by tensionhead** [comment]
So with anything else but `scaling=None` multitapering won't even work, that was the whole point of that issue here :) The multi-tapers themselves are normalized, and $1^2 = 1$. It's just a finite size effect, the lower frequencies won't be covered in a single finite white noise realization, that's why the power/magnitude drops to 0 for $f \rightarrow 0$
