### ISSUE TITLE
site.cfg: [ALL] or [DEFAULT]?

### ISSUE THREAD

**Issue by jaskij** [scipy/scipy#14746]
Looking at the current master, [site.cfg](https://github.com/scipy/scipy/blob/master/site.cfg.example#L86) uses the name `[ALL]` for common parameters. Meanwhile, NumPy has been using `[DEFAULT]` [as far back as 1.0.3](https://github.com/numpy/numpy/blob/maintenance/1.0.3.x/site.cfg.example#L58).

Considering how the build system for both is intertwined *and* both `site.cfg.example` files use the same comment for this sections, this is quite confusing - could I please request a clarification be included in the comment?

**Comment by tupui** [comment]
It's actually been a while since we updated this file... I am not sure how relevant is the information here. NumPy's one got some recent changes on the other hand.

**Comment by rgommers** [comment]
Good point, thanks @jaskij. As explained at https://github.com/numpy/numpy/blob/main/numpy/distutils/system_info.py#L31, `ALL` should not be used. gh-14759 changes it to `DEFAULT`.
