### ISSUE TITLE
BUG: online API Documentation seems broken

### ISSUE THREAD

**Issue by fabianegli** [scipy/scipy#14752]
### Describe your issue.

The formatting, styling and browsability of the API reference documentation seems broken. 

See https://docs.scipy.org/doc/scipy/reference/reference/index.html#scipy-api

Tested with Brave, Safari, Firefox.

### Reproducing Code Example

```python
1. open https://docs.scipy.org/doc/scipy/
2. click on the "API reference" tile.
```

### Error message

```shell
Basically not CSS styling, rudimentary HTML page.
```

### SciPy/NumPy/Python version information

current (Mon Sep 20 11:12:12 CEST 2021)

**Comment by tupui** [comment]
Thanks, but it's known and the issue is pinned. #14267
