### ISSUE TITLE
SciPy documentation website is broken

### ISSUE THREAD

**Issue by QuaternionsRock** [scipy/scipy#14764]
### Describe your issue.

I'm not sure if this is the right place for this, but most of the hyperlinks on the documentation website are severely broken. [Here is a short clip of the issue, using the latest version of Edge](https://imgur.com/BCz3K20). 

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
Not Found
The requested URL /doc/scipy/reference/getting_started.html was not found on this server.

Apache/2.4.39 (Ubuntu) Server at docs.scipy.org Port 443

---

Not Found
The requested URL /doc/scipy/reference/reference/reference/index.html was not found on this server.

Apache/2.4.39 (Ubuntu) Server at docs.scipy.org Port 443
```

### SciPy/NumPy/Python version information

N/A

**Comment by tupui** [comment]
Hi, thanks but known. It's a pinned issue #14267
