### ISSUE TITLE
BUG: Analog IIR Filter Produces Unstable Results for Wn > 1

### ISSUE THREAD

**Issue by slc-tl** [scipy/scipy#14765]
### Describe your issue.

Calling 

`b, a = signal.iirfilter(lpf_order,
                        Wn,
                        btype='lowpass',
                        analog=True,
                        ftype='bessel',
                        output='ba')`

With values for Wn greater than 1 always yields values whose denominator roots (roots of a) are less than 1 -- and thereby unstable. 

### Reproducing Code Example

```python
from scipy import signal
import numpy as np

lpf_order   = 4 # Analog lpf filter order


b, a = signal.iirfilter(lpf_order,
                        Wn,
                        btype='lowpass',
                        analog=True,
                        ftype='bessel',
                        output='ba')

print("filter " + str(np.all(np.abs(np.roots(a))<1)))
```

### Error message

```shell
No error is produced from the python interpreter.
```

### SciPy/NumPy/Python version information

1.7.1 1.21.2 sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)

**Comment by slc-tl** [comment]
> less

greater

**Comment by WarrenWeckesser** [comment]
For an *analog* system (i.e. a continuous time system), the stability condition is that the real parts of the roots are negative.  The condition that `abs(roots(a)) < 1` is for *discrete* systems (corresponding to `analog=False`).
