### ISSUE TITLE
BUG: lpmn ref broken link

### ISSUE THREAD

**Issue by maedoc** [scipy/scipy#14770]
### Describe your issue.

The reference link 1 (https://people.sc.fsu.edu/~jburkardt/f_src/special_functions/special_functions.html) for `scipy.special.lpmn` in the docs (https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.lpmn.html#scipy.special.lpmn) is broken.  The NIST link still works.  lpmv drops the link and just references the book.

### Reproducing Code Example

```python
curl https://people.sc.fsu.edu/~jburkardt/f_src/special_functions/special_functions.html
```

### Error message

```shell
404 Not Found

The requested URL was not found on this server.
```

### SciPy/NumPy/Python version information

n/a

**Comment by maedoc** [comment]
It would neat (tho non-trivial) to have a script check all such references in the project prior to a release.

**Comment by ilayn** [comment]
Thanks @maedoc for letting us know ! Linked PR would solve the issue.
