### ISSUE TITLE
scipy version 1.6.0 not installing in ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by iamharikrishnank** [scipy/scipy#14778]
Using python 3 enviornment I am trying to install scipy 1.6 using pip install and countered following error
ERROR: Could not find a version that satisfies the requirement scipy==1.6.0 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0b1, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.1.0rc1, 1.1.0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0rc1, 1.5.0rc2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4)
ERROR: No matching distribution found for scipy==1.6.0

**Comment by tupui** [comment]
Hi, thanks for reporting. As indicated by the issue template, we need the Python version to help.

**Comment by tupui** [comment]
It's because you need Python >=3.7 as stated in the release notes and here https://scipy.github.io/devdocs/dev/toolchain.html#numpy
