### ISSUE TITLE
BUG: Wrong limit and no warning in stats.t for df=np.inf

### ISSUE THREAD

**Issue by Edenhofer** [scipy/scipy#14777]
### Describe your issue.

Scipy's stats module for Student's t distribution does not have the correct limit of a Gaussian distribution if the degree-of-freedom (`df`) parameter is set to `np.inf`. Most importantly, Scipy does not print a warning nor does it raise an error, instead it simply yields a completely wrong result.

While I think it would make sense to branch for `df=np.inf`, it certainly does not make sense to let the user plug in values that produce bogus results.

### Reproducing Code Example

```python
In [1]: import numpy as np

In [2]: from scipy.stats import norm as stats_norm

In [3]: from scipy.stats import t as stats_t

In [4]: stats_t.sf(loc=3., df=99999., x=2., scale=1.)
Out[4]: 0.8413435362058463

In [5]: stats_t.sf(loc=3., df=np.inf, x=2., scale=1.)
Out[5]: 0.5
```

### Error message

```shell
None
```

### SciPy/NumPy/Python version information

1.7.1 1.21.2 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by tirthasheshpatel** [comment]
Thanks for reporting, @Edenhofer!

> ... I think it would make sense to branch for `df=np.inf` ...

I agree. In fact, that's exactly what `multivariate_t` does right now:

```py
In [1]: from scipy.stats import norm, multivariate_t                                                                                                                                                       

In [2]: norm.pdf(x=2, loc=3, scale=1)                                                                                                                                                                      
Out[2]: 0.24197072451914337

In [3]: multivariate_t.pdf(x=2, df=float('inf'), loc=3)                                                                                                                                                    
Out[3]: 0.24197072451914337
```
