### ISSUE TITLE
DOC: `linalg.hankel`: clarify that first entry of `r` is ignored

### ISSUE THREAD

**Issue by ddejohn** [scipy/scipy#14788]
A Hankel matrix is supposed to be a square matrix, but the [`scipy` implementation](https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/linalg/special_matrices.py#L243-L297) can sometimes return non-square matrices, which I think is misleading/unexpected:

```python
In [1]: from scipy import linalg

In [2]: linalg.hankel([1, 2, 3], [4, 5, 6, 7, 8, 9])
Out[2]:
array([[1, 2, 3, 5, 6, 7],
       [2, 3, 5, 6, 7, 8],
       [3, 5, 6, 7, 8, 9]])
```

Note that `4` is not included in the output, which may be unexpected (I know that the documentation says that `r[0]` is ignored, but the initial description of `r` is "the last row" of the matrix, so at the very least the documentation could do a better job clarifying). This output seems much more reasonable as it captures all elements from both arrays and returns a square matrix:

```python
array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])
```

**Comment by jdkramhoft** [comment]
Why is r[0] ignored? Is there a practical reason for this?

**Comment by ilayn** [comment]
For the last example the input can be entered as `linalg.hankel([1, 2, 3, 4, 5], [5, 6, 7, 8, 9])` which has all the necessary information in the correct number of elements and data.

**Comment by ddejohn** [comment]
Please forgive my ignorance, I'm certainly much less experienced in this area and was not familiar with non-square Hankel matrices. However, I'm not entirely sure I understand the difference between my example, which also exhibits constant anti-diagonals, and what you are describing as the necessary property for "Hankelness".
