### ISSUE TITLE
BUG: Conda installation not working

### ISSUE THREAD

**Issue by V0lantis** [scipy/scipy#14785]
### Describe your issue.

While following the [development quickstart for installing scipy](https://scipy.github.io/devdocs/dev/contributor/quickerstart_conda.html#quickerstart-conda), I always encounter the following message error while importing scipy : 

```bash
$ python -c "import scipy"

Traceback (most recent call last):
  File "/home/avolant/workspace/scipy/scipy/__init__.py", line 126, in <module>
    from scipy.__config__ import show as show_config
ModuleNotFoundError: No module named 'scipy.__config__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/avolant/workspace/scipy/scipy/__init__.py", line 131, in <module>
    raise ImportError(msg) from e
ImportError: Error importing SciPy: you cannot import SciPy while
        being in scipy source directory; please exit the SciPy source
        tree first and relaunch your Python interpreter.
```

### Reproducing Code Example

Just run the installation guide : 

```bash
# Create an environment with all development dependencies
conda env create -f environment.yml  # works with `mamba` too
conda activate scipy-dev

# Initialize git submodules
git submodule update --init

# Build SciPy for development work plus run tests
python runtests.py    # Alternatively, it's fine to use `python setup.py develop`

# Install SciPy in develop mode in conda
conda develop .

```

and then try to import SciPy : 
```
python -c "import scipy"
```
### Error message

```shell
Traceback (most recent call last):
  File "/home/avolant/workspace/scipy/scipy/__init__.py", line 126, in <module>
    from scipy.__config__ import show as show_config
ModuleNotFoundError: No module named 'scipy.__config__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/avolant/workspace/scipy/scipy/__init__.py", line 131, in <module>
    raise ImportError(msg) from e
ImportError: Error importing SciPy: you cannot import SciPy while
        being in scipy source directory; please exit the SciPy source
        tree first and relaunch your Python interpreter.
```

### SciPy/NumPy/Python version information

```bash
python -c "import sys, numpy; print(numpy.__version__, sys.version_info)"
1.21.2 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)
```

### Additional information
I tried to put the `$PYTHONPATH` variable to successively : 
* `~/miniconda3/envs/scipy-dev/lib/python3.9`
* `path-to/scipy`

I tried some other issues on GitHub or Stackoverflow, but it doesn't appear to be correlated to this one

**Comment by V0lantis** [comment]
It works fine after doing `python setup.py develop`. But `conda develop .` doesn't look to do anything ...

**Comment by tupui** [comment]
I am always installing with `conda` and I follow the guide except that, instead of using `python runtests.py`, I do `python setup.py build_ext --inplace`. I don't get this `runtests.py`, too much complicated to my liking.

So I guess here it's more a doc issue than anything else.

**Comment by h-vetinari** [comment]
This might be a bug in `conda develop` and/or the conda-forge packaging and/or scipy. If it's in the conda-packaging, I'm happy to help (trying to) fix it.

**Comment by V0lantis** [comment]
> This might be a bug in `conda develop` and/or the conda-forge packaging and/or scipy. If it's in the conda-packaging, I'm happy to help (trying to) fix it.

Basically, `condo develop . ` doesn't appear to do anything for me. I need to do `python setup.py develop` otherwise I am not able to import *scipy* and I get the error described in my first post. Before condo, I was using `pip install -e .` and I thought `conda develop .` was doing the same thing

**Comment by tupui** [comment]
You sure about `conda develop .` not doing anything? It's not suppose to edit the file `conda/envs/scipy/lib/pythonxx/site-packages/conda.pth`

**Comment by V0lantis** [comment]
> You sure about `conda develop .` not doing anything? It's not suppose to edit the file `conda/envs/scipy/lib/pythonxx/site-packages/conda.pth`

I am not sure actually. Just that `python runtests.py` works builds and run fine. Then `conda develop .` adds the path : 

```
path exists, skipping /Users/arthurvolant/Documents/Development/python/scipy-dev/scipy
completed operation for: /Users/arthurvolant/Documents/Development/python/scipy-dev/scipy
```

but then, I get the `ImportError` and I am not able to do anything about scipy before running `python setup.py develop `.

**Comment by AnirudhDagar** [comment]
This is real. Faced the exact same problem today. A lot of people will follow the docs and we should get this fixed soon. In case the fix takes too long then maybe update the docs?

**Comment by V0lantis** [comment]
Going to submit a Doc fix then
