### ISSUE TITLE
ENH: Work on Object-oriented design of digital filtering in scipy.signal

### ISSUE THREAD

**Issue by dhruv9vats** [scipy/scipy#14800]
On the SciPy's wiki page, under the GSoC 2021 ideas page, there is the project [Object-oriented design of digital filtering in scipy.signal](https://github.com/scipy/scipy/wiki/GSoC-2021-project-ideas#object-oriented-design-of-digital-filtering-in-scipysignal) which seems to have gone unallocated this year.

So if this is still on the to-do list and its integration is aimed, I am very interested in working on this and would love to discuss possible starting points and how do you guys see this coming together.

@nmayorov 
@rgommers

**Comment by rgommers** [comment]
I think the summary is that this is a huge undertaking, so maintainers are reluctant to start this or comment here. Sorry for the lack of reply @dhruv9vats. I'll reply in more detail on the mailing list.

**Comment by dhruv9vats** [comment]
I guess your reply on the mailing list closes this, at least for now.
