### ISSUE TITLE
b'STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT

### ISSUE THREAD

**Issue by eikmeier-cn** [scipy/scipy#14818]
### Describe your issue.

Hi guys

Or my understanding of the code is wrong or there is probably a bug here. I run an inversion test with `scipy.minimize(method = l_bfgs_b)` and it stops with the following message: `b'STOP: TOTAL NO. off AND g EVALUATIONS EXCEEDS LIMIT`. However, it does not correspond to the value of `maxfun=20`. Any idea what's going on here? Thanks!

### Reproducing Code Example

```python
# my code:
res_summary = optimize.minimize(
            fun, m_current,
            args=(m_t, model_current, sgs_obs),
            method='L-BFGS-B', jac=True, callback=fwi_callback, bounds=bounds,
            options={'ftol': 1e-6, 'gtol': 1e-20, 'maxfun': 20,
                     'maxiter': 30, 'disp': 99})

#my return:
###L_BFGS_B INVERSION INFORMATION###
Iteration: 1 | Evaluation: 3
Iteration: 2 | Evaluation: 6
Iteration: 3 | Evaluation: 9
Iteration: 4 | Evaluation: 9
```

### Error message

```shell
fun: 94149.87264966885
 hess_inv: <10201x10201 LbfgsInvHessProduct with dtype=float64>
      jac: array([ -37.70637123, -190.42026409, -277.88007295, ...,   -9.08818323,
         13.41612702,   43.94295883])
  message: b'STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT'
     nfev: 27
      nit: 4
     njev: 27
   status: 1
  success: False
        x: array([0.163554  , 0.16447512, 0.14660401, ..., 0.16269842, 0.16254759,
       0.16232158])
```

### SciPy/NumPy/Python version information

1.5.1 1.18.5 sys.version_info(major=3, minor=7, micro=6, releaselevel='final', serial=0)

**Comment by andyfaff** [comment]
Each time LBFGSB goes through the iteration loop it evaluates the user supplied function multiple times, especially if the gradient is estimated by numerical differentiation, which takes at least `N` function evaluations (`N+1` if `f0` has to be evaluated as well).
It's possible that maxfun is exceeded part way through the evaluation loop, during that numerical differentiation. If that's the case then that iteration will still complete, but not go around again. Thus, maxfun may be exceeded by a small amount, hence the error message.

- is there a reason why you set maxfun so low?
- how would you write the error message to improve it?
- how would you write the documentation to improve it?

**Comment by AtsushiSakai** [comment]
Related discussion: https://github.com/scipy/scipy/pull/14805#issuecomment-937413098
