### ISSUE TITLE
BUG: On Py3.10 importing `scipy.x` fails

### ISSUE THREAD

**Issue by ullix** [scipy/scipy#14826]
### Describe your issue.

Importing `scipy.signal` under Py3.10 (in a venv) fails with this message (on Py3.9.4 and older it works):
```
$ python3
Python 3.10.0a6 (default, Mar  2 2021, 02:01:08) [GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.signal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/vgl310/lib/python3.10/site-packages/scipy/signal/__init__.py", line 302, in <module>
    from .filter_design import *
  File "~/vgl310/lib/python3.10/site-packages/scipy/signal/filter_design.py", line 16, in <module>
    from scipy import special, optimize, fft as sp_fft
  File "~/vgl310/lib/python3.10/site-packages/scipy/optimize/__init__.py", line 421, in <module>
    from ._shgo import shgo
  File "~/vgl310/lib/python3.10/site-packages/scipy/optimize/_shgo.py", line 9, in <module>
    from scipy import spatial
  File "~/vgl310/lib/python3.10/site-packages/scipy/spatial/__init__.py", line 107, in <module>
    from . import distance, transform
  File "/home/ullix/geigerlog/vgl310/lib/python3.10/site-packages/scipy/spatial/transform/__init__.py", line 19, in <module>
    from .rotation import Rotation, Slerp
ImportError: /home/ullix/geigerlog/vgl310/lib/python3.10/site-packages/scipy/spatial/transform/rotation.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send
```

The latest version of scipy is installed:
```
$ python3 -m pip install -U scipy
Requirement already satisfied: scipy in ~/vgl310/lib/python3.10/site-packages (1.6.1)
Requirement already satisfied: numpy>=1.16.5 in ~/vgl310/lib/python3.10/site-packages (from scipy) (1.21.2)
```

### Reproducing Code Example

```python
-
```

### Error message

```shell
-
```

### SciPy/NumPy/Python version information

```import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info) 1.6.1 1.21.2 sys.version_info(major=3, minor=10, micro=0, releaselevel='alpha', serial=6)```

**Comment by xmatthias** [comment]
the latest version of scipy is actually 1.7.1 - which is pinned to `<python==3.10` - so it appears to be a deliberate decision to not support 3.10 for the moment (most likely due to some issues like #13122).

I'd wait for a final release (#14567) of a 3.10 supported version before upgrading to 3.10.

**Comment by tupui** [comment]
Thanks @xmatthias. Indeed we are waiting for #14567 before bumping SciPy to 1.7.2 and officially support Python 3.10. Still, our CI is passing on 1.7.x with Python 3.10 so in the meantime, you could install manually NumPy and SciPy from source. You can have a look at how we do this in the CI (`Nightly CPython` in `linux.yml`).

**Comment by tupui** [comment]
Renaming and pining the issue in case we have more reports on Python 3.10 not working.

**Comment by tylerjereddy** [comment]
Yeah, I saw the same error message in another package I help maintain when checking on Python 3.10 situation: https://github.com/darshan-hpc/darshan/pull/515

In that case, it was an interaction with `seaborn` calling `scipy.stats`, which then called `scipy.spatial`

**Comment by taiseiyo** [comment]
When will Scipy be stable on Python 3.10？

**Comment by tupui** [comment]
> When will Scipy be stable on Python 3.10？

It's stable already. Just wait for 1.7.2 to be released to have the wheels. Please read the thread...

**Comment by tupui** [comment]
> When will Scipy be stable on Python 3.10？

It's stable already. Just wait for 1.7.2 to be released to have the wheels. Please read the thread...

**Comment by dschwoerer** [comment]
`pip install https://github.com/scipy/scipy` solves the issue for me.
A new release would be great :+1: 

Note that not having a release of scipy on pypi makes it hard for downstream projects to test with 3.10 ...

**Comment by tupui** [comment]
> `pip install git+https://github.com/scipy/scipy` solves the issue for me. A new release would be great 👍
> 
> Note that not having a release of scipy on pypi makes it hard for downstream projects to test with 3.10 ...

A release is in the making (cf the branch 1.7.2 and #14567). It just takes time out of our limited resources.

**Comment by rgommers** [comment]
`1.7.2` is released, closing.
