### ISSUE TITLE
BUG: optimize.brentq triggers an overflow error

### ISSUE THREAD

**Issue by JPFrancoia** [scipy/scipy#14851]
### Describe your issue.

`optimize.brentq` triggers an overflow error. This bug reports follows our investigation here: https://github.com/scipy/scipy/issues/14704.

Note that the other issue is about catching the overflow error, this issue is about preventing the error from happening.

The problem started with the release of scipy 1.7.0, when scipy started vendoring boost libraries. It doesn't happen with 1.6.3.

### Reproducing Code Example

```python
from scipy.version import version
from scipy import optimize, stats
from sys import float_info

print("Scipy version:", version)

count = 5
nobs = 6
alpha = 0.05
q_ = count * 1. / nobs


def func(qi):
    return stats.binom_test(q_ * nobs, nobs, p=qi) - alpha


optimize.brentq(func, float_info.min, q_)
```

### Error message

```shell
libc++abi: terminating with uncaught exception of type boost::wrapexcept<std::overflow_error>: Error in function ibeta_derivative<double>(double,double,double): Overflow Error
[1]    94186 abort      python crash.py
```

### SciPy/NumPy/Python version information

1.7.1 1.21.2 sys.version_info(major=3, minor=8, micro=11, releaselevel='final', serial=0)

**Comment by andyfaff** [comment]
The underlying issue is reported in #14704 (possibly fixed by #14833), it's not specifically an issue with `optimize.brentq`. Therefore, I'm going to close this issue.
