### ISSUE TITLE
BUG: sqrtm dtype

### ISSUE THREAD

**Issue by garrettwrong** [scipy/scipy#14853]
### Describe your issue.

`sqrtm` does not pass through `np.float32` for single precision input.  I think the behavior changed starting at 1.6.

Reporting after a debugging session (the joys of mysteriously mixing dtypes in numerical code, 😂 ).

It's not a terrible bug or anything, but I'd like to know if this was intentional or will be changed.

I have seen this on multiple platforms now that I narrowed it down.

I really appreciate your software.
Thanks!

### Reproducing Code Example

```python
Python 3.7.11 (default, Jul 27 2021, 07:03:16) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import scipy.linalg as la
>>> la.sqrtm(np.zeros((10,10),dtype=np.float32)).dtype
dtype('float64')
>>>


# Old behavior:
Python 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 12:58:59) 
[GCC Clang 10.0.0 ] on darwin
Type “help”, “copyright”, “credits” or “license” for more information.
>>> import numpy as np
>>> import scipy.linalg as la
>>> la.sqrtm(np.zeros((10,10),dtype=np.float32)).dtype
dtype(‘float32’)
```

### Error message

```shell
See code example for differing dtype.
```

### SciPy/NumPy/Python version information

1.6.1 1.21.2 sys.version_info(major=3, minor=7, micro=11, releaselevel='final', serial=0)

**Comment by ilayn** [comment]
Ah we are busted :) Thanks @garrettwrong for the report. This is something we briefly discussed way back when and unfortunately went float64-only to ease up the Cythonization effort. But you are right that we need some sort of a unification. As usual I am going waaaay behind of my promises such as #12838 thus the intention is most definitely there but commitments are not in par with them. Sorry about this. I really want to get to this as soon as our work over linalg.solve materializes.

**Comment by rgommers** [comment]
@ilayn do you still want to get this into 1.9.0? If so, you may want to merge gh-16294.

**Comment by ilayn** [comment]
Argh, I don't think we can make it to 1.9.0 I have the PR ready but didn't finish all the tests regarding the nd array inputs

**Comment by fAndreuzzi** [comment]
Hi guys, I noticed that `1.10.0` breaks some of our tests since `np.complex128` becomes `np.complex256` after a pass through `scipy.linalg.sqrtm`:

```python
>>> import numpy as np
>>> from scipy.linalg import sqrtm
>>> sqrtm(np.zeros((10,10),dtype=np.complex128)).dtype
dtype('complex256')
```

I'm using NumPy `1.24.1` and SciPy `1.10.0`.

**Comment by tupui** [comment]
@fAndreuzzi This is intended as we can see in the PR which closed this issue.

**Comment by fAndreuzzi** [comment]
Okay thanks @tupui, I was just curious since `numpy.linalg` does not work with `np.complex256`. So this is a kind of breaking change in SciPy interface. For now I'm just casting the `ndarray` back to `np.complex128`.

**Comment by tupui** [comment]
From reading the PR's comments, yes dtype is changed but it seems to me that the previous behaviour was a bug.

**Comment by WarrenWeckesser** [comment]
The comments in gh-16294 are about *preserving* the dtype.  The problem that @fAndreuzzi reported above is that the precision of the dtype *increased* from `complex128` (where the underlying real data type is `double`) to `complex256` (where the underlying real data type is `long double`. That is surprising.  Was that really the intent of gh-16294?  The line in the docstring that says "When the dtype is complex, the precition [sic] is double as `A`" could be clearer, but I guess that is what is happening here.  That is, `complex64` is upcast to `complex128`, and `complex128` is upcast to `complex256` (if it exists). Not all the matrix functions do this, and `sqrtm` doesn't upcast when the input dtype is real.  Is there something special about `sqrtm` that justifies this special handling of complex inputs?
