### ISSUE TITLE
BUG: NumPy's `random` module should not be in the `scipy` namespace.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#14889]
### Describe your issue.

Currently, `scipy.random` is an alias for `numpy.random`:
```
In [12]: import numpy as np

In [13]: import scipy

In [14]: scipy.__version__
Out[14]: '1.8.0.dev0+1859.14341ea'

In [15]: scipy.random
Out[15]: <module 'numpy.random' from '/home/warren/mc39scipy/lib/python3.9/site-packages/numpy/random/__init__.py'>

In [16]: scipy.random is np.random
Out[16]: True
```
 We have already deprecated other names in `scipy` that come from `numpy`, e.g.
```
In [17]: scipy.array([1, 2, 3])
<ipython-input-17-773c09c10413>:1: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  scipy.array([1, 2, 3])
Out[17]: array([1, 2, 3])
```
We should do the same for `random`, so a call such as the following generates a deprecation warning:

```
In [18]: scipy.random.randint(10, size=3)
Out[18]: array([8, 5, 5])
```

### Reproducing Code Example

```python
See above.
```

### Error message

```shell
See above.
```

### SciPy/NumPy/Python version information

1.8.0.dev0+1859.14341ea 1.21.2 sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)

**Comment by j-bowhay** [comment]
#15230 removed `scipy.random` without a deprecation period. Do we need to add deprecation warning or can this be closed? @h-vetinari

**Comment by h-vetinari** [comment]
> #15230 removed `scipy.random` without a deprecation period. Do we need to add deprecation warning or can this be closed?

Thanks @j-bowhay; @WarrenWeckesser pointed this out [already](https://github.com/scipy/scipy/pull/15230#issuecomment-1032197085) after the PR was merged, but it received no response.

Generally I have the impression scipy has been cautious about hard API breaks (not without deprecation unless absolutely necessary), but I don't know the details of this change. Perhaps one could reintroduce a dummy module that just exposes the right functionality but always raises a deprecation warning?

CC other participants of #15230: @stefanv @josef-pkt @rgommers @tupui @tylerjereddy

**Comment by ilayn** [comment]
Not really an API break but actually fixes something that should have not happened anyways but just a missed star import. So it's not really a big deal. And it didn't create any noise so let's close it and deal when it becomes an issue.

**Comment by ilayn** [comment]
Yes but this was not an alias because we never had a random module it was carried over from a missed numpy import. Hence that entry won't be accurate but won't hurt either.

**Comment by rgommers** [comment]
Agreed, all the `from numpy import *` imports are gone, this was one of them. Should be fine to leave that as is.
