### ISSUE TITLE
RegularGridInterpolator should be called RectilinearGridInterpolator

### ISSUE THREAD

**Issue by mueslo** [scipy/scipy#14926]
https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/interpolate/interpolate.py#L2345-L2572

This function is somewhat misnamed and mis-documented. 

![image](https://user-images.githubusercontent.com/847751/139123819-0187a9c1-d58f-4c17-9bd5-68e6d7363013.png)

1) Points e.g. on a hexagonal/triangular grid form a **perfectly regular** grid, the resulting tessellation cells are all identical parallelepipeds, yet these points **cannot be used** with this interpolator class (even with a basis transformation, as the distance metrics are not compatible).

2) Points defined on a general rectilinear grid are **not regular**, since the cells are not all congurent parallelepipeds, yet they **can be used** with this interpolator class

![image](https://user-images.githubusercontent.com/847751/139123266-da317289-f579-4ab9-95bf-091af14fa1f9.png)

This class should be named RectilinearGridInterpolator for accuracy.

Please see also: https://en.wikipedia.org/wiki/Regular_grid

This also applies for the documentation of interpn: https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/interpolate/interpolate.py#L2577-L2583

**Comment by AtsushiSakai** [comment]
I’m not familiar with mathematical correctness in this field, but I feel that "Regular grid" and "uneven spacing" seems like a contradiction.

**Comment by mueslo** [comment]
Let me just also point out that [RectBivariateSpline](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RectBivariateSpline.html) also uses a rectilinear/rectangular (non-regular) grid/mesh, so calling it RectGridInterpolator would also improve consistency.

**Comment by tupui** [comment]
@JohannesBuchner I suppose you would have an opinion 😃

**Comment by JohannesBuchner** [comment]
Reading https://mathworld.wolfram.com/Grid.html it seems what is supported are arbitrary orthogonal grids.

It seems correct to me that a more general case is supported by RegularGridInterpolator than regular grids. I think this is not the first case in the numpy/scipy universe though, that a method becomes more powerful than its original description.

In any case, the doc should be corrected for both interp and RegularGridInterpolator, to talk about support for regular grids (with np.arange/linspace) and rectilinear grids (with non-uniform spacing).

I think the class does not have to disappear, which indeed would be an upgrading nightmare. A possible solution would be to add an alias, RectilinearGridInterpolator. But I don't know if it is worth it. But we should get the doc correct.

**Comment by JohannesBuchner** [comment]
Thanks for discovering this @mueslo, I learned something.

**Comment by tupui** [comment]
Thanks @JohannesBuchner for your inputs. Let's correct the doc first and during the review we might have more discussions with others. Do you or @mueslo would do a PR?

**Comment by mueslo** [comment]
@JohannesBuchner thanks for the input. However, I would like to point out something where it seems we are not quire on the same page: RegularGridInterpolator does **not** in fact support a more general case than regular grids, since it only supports a strict subset of regular grids, namely the orthogonal ones.

If my data is on grid points defined by e.g. x_ijk = i*(1, 0, 0) + j*(0, 1, 0) + z*(0.5, 0.5, 1) then this forms a perfectly regular grid according to all definitions. But it is not orthogonal, and not supported by RegularGridInterpolator. This is my whole point - it does not support all regular grids.

If it truly supported a superset of all regular grids, then I would not mind it being called RegularGridInterpolator. But alas, it doesn't.

But I agree that being explicit in what it does in the documentation is a good step. I can submit a PR here.

![image](https://user-images.githubusercontent.com/847751/140043207-56006202-d0f6-4a5c-ac46-1a02d8fe8621.png)

I am not trying to argue on a technicality here. I discovered it, because in my case I actually do need to interpolate on arbitrary (orthogonal and non-orthogonal) regular grids, but I can't use this function.
