### ISSUE TITLE
BUG: genextreme.ppf differs from analytical ppf

### ISSUE THREAD

**Issue by antoscha** [scipy/scipy#14949]
### Describe your issue.

Hi,

It seems that `scipy.stats.genextreme.ppf` produce an incorrect result compared with the analytical one. Please consider the code example below.

### Reproducing Code Example

```python
import numpy as np

from scipy.stats import genextreme


d = genextreme.rvs(0.1, 0, 1, 10000, random_state=42)
c, loc, scale = genextreme.fit(d)
numerical_ppf = genextreme.ppf(0.005, c, loc, scale)
analytical_ppf = loc + scale / c * ((-np.log(0.005))**(-c) - 1)
print(numerical_ppf, analytical_ppf)
```

### Error message

```shell
No error message
```

### SciPy/NumPy/Python version information

1.7.1 1.21.2 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by antoscha** [comment]
Probably, [this](https://github.com/scipy/scipy/blob/c30fefc2446a7cb93de1b45765e243345d5929db/scipy/stats/_continuous_distns.py#L2510) lambda should be without minuses: `sc.expm1(c * x) / c`.

**Comment by josef-pkt** [comment]
There should be a roundtrip unit test to verify that ppf and cdf are consistent. 

My guess is that your analytical_ppf uses a different parameterization than scipy uses.
Check that the inverse function of your analytical_ppf actually corresponds to the scipy version. My guess is that it doesn't.


quick check

```
import numpy as np
​
from scipy.stats import genextreme
​
​
d = genextreme.rvs(0.1, 0, 1, 10, random_state=42)
c, loc, scale = genextreme.fit(d)
numerical_ppf = genextreme.ppf(0.005, c, loc, scale)
c = -c
analytical_ppf = loc + scale / c * ((-np.log(0.005))**(-c) - 1)
print(numerical_ppf, analytical_ppf)
-1.9657172274817558 -1.9657172274817554
```

**Comment by antoscha** [comment]
Yes, I missed it. You're right. Thanks!
