### ISSUE TITLE
BUG: orthogonal_procrustes returns the transpose/inverse

### ISSUE THREAD

**Issue by mdabdk** [scipy/scipy#14948]
### Describe your issue.

The [`scipy.linalg.orthogonal_procrustes`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.orthogonal_procrustes.html) function will return the transpose (or inverse) of the desired orthogonal matrix instead of the correct one on some occasions.

If the code below is run a few times, it will print `True` sometimes and `False` other times. At the times when it prints `False`, I find that `R_hat` is the transpose of `R` and not `R` itself. **However**, if I uncomment the line
```python
# R = np.linalg.qr(np.random.randn(2,2))[0]
```
and comment the line
```python
R = scipy.stats.ortho_group.rvs(2)
```
I will always get `True` as expected. It seems that the way that the random orthogonal matrix `R` is sampled affects the result of `orthogonal_procrustes`. Sampling using `scipy.stats.ortho_group.rvs(2)` seems to be causing the problem,

### Reproducing Code Example

```python
import numpy as np
import scipy.linalg
import scipy.stats

X = np.random.randn(2,3)

# sample random orthogonal matrix
# R = np.linalg.qr(np.random.randn(2,2))[0]
R = scipy.stats.ortho_group.rvs(2)

# rotate/reflect each column vector in X using R
Y = R @ X

# estimate R using orthogonal procrustes
R_hat = scipy.linalg.orthogonal_procrustes(X.T,Y.T)[0]

print(np.allclose(R,R_hat))
```

### Error message

```shell
No error message.
```

### SciPy/NumPy/Python version information

1.5.4 1.19.2 sys.version_info(major=3, minor=8, micro=11, releaselevel='final', serial=0)

**Comment by melissawm** [comment]
In the examples above, you are getting `True` when the generated `R` from `scipy.stats.ortho_group.rvs` is symmetric; in fact, calling `orthogonal_procrustes` with `X.T` and `Y.T` you are solving the problem

```
X.T @ R.T = Y.T
```

so `orthogonal_procrustes` is giving you the right solution, `R.T`.

**Comment by ilayn** [comment]
This is not a problem of the functions you have given but missing transpose. If you check the failing R and R_hat they should have signs swapped in certain entries. Here is one such problem my computer stopped at

```python
print(R)
[[-0.62955578  0.77695529]
 [-0.77695529 -0.62955578]]

print(R_hat)
[[-0.62955578 -0.77695529]
 [ 0.77695529 -0.62955578]]

R_hat.T @ X - Y
Out[84]: 
array([[ 0.00000000e+00, -2.91433544e-16,  4.44089210e-16],
       [-5.55111512e-17,  4.44089210e-16, -2.22044605e-16]])

R @ X - Y
Out[85]: 
array([[0., 0., 0.],
       [0., 0., 0.]])
```

**Comment by ilayn** [comment]
Ah what @melissawm said. My apologies, I missed the page refresh

**Comment by mdabdk** [comment]
Hi @melissawm, thanks a lot for your comment! It was helpful.

I'm a bit confused about the usage of `orthogonal_procrustes`. What I really want to do is rotate each column vector in the 2 x 3 matrix `X` using the 2 x 2 matrix `R` to get the matrix `Y`, and then try to find the orthogonal matrix `R_hat` that is as close to `R` as possible. This only worked when I applied `orthogonal_procrustes` to `X.T` and `Y.T` and not `X` and `Y` directly. If I try to use the following code instead
```python
import numpy as np
import scipy.linalg
import scipy.stats

X = np.random.randn(2,3)
R = scipy.stats.ortho_group.rvs(2)
Y = R @ X
R_hat = scipy.linalg.orthogonal_procrustes(X,Y)[0]
```
I get a 3 x 3 matrix `R_hat`, but I want a 2 x 2 matrix. Any suggestions on how I can do this?

**Comment by mdabdk** [comment]
Here is the solution to my problem above. According to the documentation for the [`scipy.linalg.orthogonal_procrustes`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.orthogonal_procrustes.html) function:

> Returns **R** : _(N, N) ndarray_
The matrix solution of the orthogonal Procrustes problem. Minimizes the Frobenius norm of `(A @ R) - B`, subject to `R.T @ R = I`.

I initially thought that this function solves the problem `(R @ A) - B` and not `(A @ R) - B`, which was the source of my confusion. The following code works fine
```python
import numpy as np
import scipy.linalg
import scipy.stats

# each row is a 2D vector
X = np.random.randn(3,2)

# sample random orthogonal matrix
R = scipy.stats.ortho_group.rvs(2)

# rotate/reflect each column vector in X using R
Y = X @ R

# estimate R using orthogonal procrustes. NOTE: this function solves
# the problem A * R - B and NOT R * A - B
R_hat = scipy.linalg.orthogonal_procrustes(X,Y)[0]

print(np.allclose(R,R_hat))
```
Note that each row of the matrix `X` is a separate vector and **not** each column as before.
