### ISSUE TITLE
BUG: distributions' var method does not respect broadcasting

### ISSUE THREAD

**Issue by fehiepsi** [scipy/scipy#14953]
### Describe your issue.

It seems that since scipy 1.7.0, the `.var()` method of scipy distributions like `norm` or `logistic` does not respect the broadcasting rule. I would expect the following reproducing assertation pass.

### Reproducing Code Example

```python
import numpy as np
import scipy.stats as sp
assert (sp.norm(np.zeros(2), np.array([[1], [2]])).var() == sp.norm(np.zeros(2), np.array([[1, 1], [2, 2]])).var()).all()
```

### Error message

```shell
AssertionError
```

### SciPy/NumPy/Python version information

1.7.1 1.19.5 sys.version_info(major=3, minor=7, micro=12, releaselevel='final', serial=0)

**Comment by tirthasheshpatel** [comment]
Seems like a bug in `argsreduce` here:

https://github.com/scipy/scipy/blob/c30fefc2446a7cb93de1b45765e243345d5929db/scipy/stats/_distn_infrastructure.py#L572

When all the values are valid, it doesn't broadcast the arrays to correct shape. But if any invalid values are given, it will return the correct output:

```python
>>> import scipy.stats as sp
>>> sp.norm.var([0,0], [[1],[float('nan')]])
array([[ 1.,  1.],
       [nan, nan]])
```
