### ISSUE TITLE
BUG: signal.morlet2 documentation does not accurately describe implementation

### ISSUE THREAD

**Issue by J-Lentz** [scipy/scipy#14952]
### Describe your issue.

The documentation of signal.morlet2 states: "Returns the complete version of morlet wavelet".

This implies that the output wavelet should contain the -exp(-w**2 / 2) correction term, analogous to signal.morlet with complete=True. However, morlet2 actually implements the "standard" variant without the correction term, analogous to signal.morlet with complete=False.

### SciPy/NumPy/Python version information

SciPy 1.7.1

**Comment by ev-br** [comment]
`scipy.signal.morlet2` is deprecated, along with the rest of the wavelet functionality.
