### ISSUE TITLE
BUG: Wrong calculation from Euler to Quaternion

### ISSUE THREAD

**Issue by nuomifan** [scipy/scipy#14975]
### Describe your issue.

OS: Ubuntu 18.04 

scipy version: 1.7.1

When I use Rotation in scipy, it returns wrong value

`Rotation.from_euler('xyz',[3.14,0.2623,0]).as_quat() `

It returns
`array([ 9.91411844e-01,  1.04139110e-04, -1.30774311e-01,  7.89487983e-04])`

Actually, the results should be (from https://www.andre-gaschler.com/rotationconverter/)
`array([ 9.91411844e-01,  1.04139110e-04, 1.30774311e-01,  7.89487983e-04])`

I am pretty sure that the scipy is wrong

### Reproducing Code Example

```python
Rotation.from_euler('xyz',[3.14,0.2623,0]).as_quat()
```

### Error message

```shell
array([ 9.91411844e-01,  1.04139110e-04, -1.30774311e-01,  7.89487983e-04])
```

### SciPy/NumPy/Python version information

1.7.1

**Comment by rkern** [comment]
Note in the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.from_euler.html) that there is a difference between `'XYZ'` to ask for intrinsic rotations while `'xyz'` asks for extrinsic rotations. The converter site you linked does not mention whether they are using intrinsic or extrinsic rotations, but it uses the capitalized `XYZ` and the results match when you ask for intrinsic rotations by using `'XYZ'`, so I guess they are using intrinsic rotations. See the Wikipedia article linked from our documentation and the converter site explains the variety of conventions.
