### ISSUE TITLE
BUG: "SVD did not converge" error in scipy.linalg.orth

### ISSUE THREAD

**Issue by veronica320** [scipy/scipy#14977]
### Describe your issue.

Hi there,

I'm trying to find the orthonormal basis of a matrix with `scipy.linalg.orth()`.  But it sometimes throws the following error:
```
Traceback (most recent call last):
    w_basis = linalg.orth(W) # my code
  File "env/lib/python3.7/site-packages/scipy/linalg/decomp_svd.py", line 321, in orth
    u, s, vh = svd(A, full_matrices=False)
  File "env/lib/python3.7/site-packages/scipy/linalg/decomp_svd.py", line 131, in svd
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge
```

I checked for a few StackOverflow posts / Github issues and ruled out a few common causes (e.g. W doesn't have any NaN values in it; numpy and scipy version isn't too old, ...), and the issue persists. 

[Here](https://drive.google.com/file/d/17hxYzwKaivJ8htJmP4Nte5sUdIpfYQeP/view?usp=sharing) is a sample `W` I'm using. You can reproduce the problem by downloading it and running the following code.

Any info is appreciated. Thanks in advance!

### Reproducing Code Example

```python
import numpy as np
from scipy import linalg

W = np.load("sample_W.npy") # download and open the file from the link above
w_basis = linalg.orth(W)
```

### Error message

```shell
Traceback (most recent call last):
    w_basis = linalg.orth(W)
  File "env/lib/python3.7/site-packages/scipy/linalg/decomp_svd.py", line 321, in orth
    u, s, vh = svd(A, full_matrices=False)
  File "env/lib/python3.7/site-packages/scipy/linalg/decomp_svd.py", line 131, in svd
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge
```

### SciPy/NumPy/Python version information

1.7.1 1.17.2 sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)

**Comment by ilayn** [comment]
Hi @veronica320 how big is your array? Do you mind copy pasting the array itself into the issue instead of putting it somewhere GDocs?

**Comment by veronica320** [comment]
It's 768 * 768, a bit too big to paste into the textbox : ( 
But I'm attaching it here: [sample_W.npy.zip](https://github.com/scipy/scipy/files/7478465/sample_W.npy.zip). You can unzip it and load the .npy file in the 3rd line of my code, `W = np.load("sample_W.npy")`. Does this work?

**Comment by ilayn** [comment]
Can you at least paste it as a txt file somewhere? We really don't want to download random files online just to check something due to security concerns. Especially no zip files. 

You can use GitHub's gist or pastebin or whatever you wish.

**Comment by veronica320** [comment]
Sure, here is a .txt version: https://gist.github.com/veronica320/f06db7144dc305fab016c1f250b29e64. It's a lot larger than the binary .npy though.
To load the .txt file, please use the following code snippet instead:
```
import os
import numpy as np
from scipy import linalg

W = np.loadtxt("sample_W.txt", delimiter=",")
w_basis = linalg.orth(W)
```

**Comment by ogauthe** [comment]
I cannot reproduce. This looks like a LAPACK bug that is implementation dependent. With the MKL
`Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications`
shipped by cona on an intel x86, I can compute the SVD with both `gesvd` and `gesdd`.

@veronica320  `orth` is just a small overlay upon `svd`. As a workaround, you may reuse its code doing the svd yourself, changing the driver in case the svd fails (use kwarg ` lapack_driver='gesvd'`). Maybe the kwarg should be added to `orth`.
