### ISSUE TITLE
ENH: The knot interval lookup for BSpline.design_matrix is inefficient

### ISSUE THREAD

**Issue by derb12** [scipy/scipy#14987]
### Is your feature request related to a problem? Please describe.

The `_make_design_matrix` function in scipy.interpolate._bspl.pyx uses https://github.com/scipy/scipy/blob/ebfac22a32c79c7b44a6ecc7d5e4844f60449818/scipy/interpolate/_bspl.pyx#L451-L452
where t are the knots and k is the spline degree, to find the index `ind` where t[ind] <= x[i] < t[ind + 1]. The issue is that the previous knot index (fourth argument in the `find_interval` call) is fixed at `k-1`. It should instead be `ind` so that the previous knot index is constantly updated, like it's done in the `_norm_eq_lsq` and `_colloc` functions in scipy.interpolate._bspl.pyx. As it is now, each `find_interval` call starts the search at the beginning of the knot array, rather than at the last index, making the search slower than it needs to be, especially when x is monotonically increasing.

### Describe the solution you'd like.

The change is simple and should look something like this (I don't know Cython well enough to know if `ind` should be declared as int or intp type):

```python
ind = k
for i in range(n):
    ind = find_interval(t, k, x[i], ind, 0)
```

### Describe alternatives you've considered.

The current implementation is fine, but it could be faster.

**Comment by ev-br** [comment]
PR welcome, I'd say. 
(Index variables should be intp)
