### ISSUE TITLE
Prevent new Python versions from trying to install older releases from sdists

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#14986]
This is a follow up to https://github.com/scipy/scipy/issues/14738#issuecomment-934199718. The issue is that for older SciPy versions, we use `python_requires>=3.xx` and there is no `<3.yy`. For newer release (starting from 1.7.0) we do this more correctly, like `python_requires='>=3.7,<3.11'`. The effect of this is that a 1.7.x release is only found for supported Python versions, but 1.6.x will be found for every future Python version. So the moment Python 3.11 is available and someone uses `pip install scipy`, an attempt will be made to install 1.6.x from source. That will then fail halfway through the build with an obscure error.

The solution to this is to upload a new sdist for the most recent 1.6.x release, which keeps the same `>=3.xx` (and _not_ `<3.yy`) constraint, and immediately errors out when building from source with a too new Python version with a clear error message and instructions for the user about what to do (most likely "don't use this not-yet-supported Python version!".

This is probably best done as a `.post0` sdist upload. It may need re-uploading all wheels as `.post0` (not sure, needs checking). This needs careful testing to ensure nothing gets broken.

**Comment by tylerjereddy** [comment]
Fixed by gh-16553; closing manually because PRs to non-default branches don't auto-close their matching issues.
