### ISSUE TITLE
BUG: Levy stable

### ISSUE THREAD

**Issue by lady-pandas** [scipy/scipy#14994]
### Describe your issue.

Behaviour of generated levy-stable distribution is not compliant with expected one (https://en.wikipedia.org/wiki/Stable_distribution)

### Reproducing Code Example

```python
pd.DataFrame({
    f'alpha={alpha}': stats.levy_stable.rvs(alpha=alpha, beta=0, loc=0, scale=1, size=10000) for alpha in [0.5, 1, 1.5, 2]
})
```

### Error message

```shell
-
```

### SciPy/NumPy/Python version information

1.5.2 1.21.0 sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @lady-pandas. I does work as expected. After some tests, I can see that the plots can be confusing because of some outliers. So just set the limits for your plots. Have a look at the following:


```python
import numpy as np
from scipy.stats import levy_stable
import matplotlib.pyplot as plt

distribution = levy_stable(alpha=0.5, beta=0, loc=0, scale=1)

fig, axs = plt.subplots(nrows=1, ncols=2, sharex=True, figsize=(9, 4))
x = np.linspace(distribution.ppf(0.01), distribution.ppf(0.99), 100)
# PDF
pdf = distribution.pdf(x)
axs[0].plot(x, pdf, "-", lw=5, alpha=0.6)
# CDF
cdf = distribution.cdf(x)
axs[1].plot(x, cdf, "-", lw=5, alpha=0.6)
# Empirical PDF
sample = distribution.rvs(size=1000)
# discrete samples
delta = np.max(pdf) * 5e-2
axs[0].plot(sample[:100], -delta - delta * np.random.random(100), "+k")
axs[0].set(title="PDF", ylabel=r"$f$", xlabel=r"$x$", xlim=[-1000, 1000])
axs[1].set(title="CDF", ylabel=r"$F$", xlabel=r"$x$", xlim=[-1000, 1000])
plt.show()
```

![0 5](https://user-images.githubusercontent.com/23188539/141080343-1472f701-d532-457d-a3ee-70e0bc4030a1.png)

**Comment by lady-pandas** [comment]
I have to disagree, of course I narrowed down the domain :)

Here is how the output of scipy.stats looks like: 
![image](https://user-images.githubusercontent.com/52793237/141151066-6d4e1988-5ab3-4a91-a371-19b7b257b4f8.png)

And here is how it should look like:
![image](https://user-images.githubusercontent.com/52793237/141151133-e857d0ca-095b-452e-b727-ed847ea8b32c.png)

Best,
Marta

**Comment by tupui** [comment]
Can you try with the latest version? I see in the bug tracker that we closed some issues about some values of alpha (in the version 1.7). Might be related to this.

FYI, tests for this distribution are here https://github.com/scipy/scipy/blob/f1c6b54f51dfc8c3e83d826867a68026f20b243b/scipy/stats/tests/test_distributions.py#L3041

**Comment by tupui** [comment]
Oh I see now, it's with `alpha < 1` that there is something. Sorry I missed this at first glance. I will reopen this and investigate.

**Comment by tupui** [comment]
Actually there is some work in the way which I believe would fix this gh-9523. There are explicit references to `alpha=0.5`

**Comment by steppi** [comment]
Hi @lady-pandas, gh-9523 has been merged. Thanks to the hard work of @bsdz and @ragibson I was able to reproduce the results from your plot with the following script. See the figure below. 

```python
import numpy as np

from scipy.stats import levy_stable
import matplotlib.pyplot as plt

fig, ax = plt.subplots(nrows=1, ncols=1, sharex=True, figsize=(7, 5))
for alpha, color in zip(
        [2.0, 1.5, 1.0, 0.5],
        ['black', 'blue', 'green', 'red'],
):
    distribution = levy_stable(alpha=alpha, beta=0, loc=0, scale=1)
    x = np.linspace(-4.0, 4.0, 10000)
    pdf = distribution.pdf(x)
    ax.plot(
        x, pdf, "-", lw=2, alpha=0.6, color=color, label=f"$\\alpha$= {alpha}"
    )
ax.set_xlim([-4.0, 4.0])
ax.set_ylim([0.0, 0.7])
ax.legend()
plt.show()
```
![levy_stable_pdf](https://user-images.githubusercontent.com/1953382/146655958-8f01f670-96a6-41b4-9a1d-39896e1cf7ea.png)
