### ISSUE TITLE
SciPy on Python 3.10 Windows does not include msvcp140.dll

### ISSUE THREAD

**Issue by thomasjpfan** [scipy/scipy#14998]
When downloading the wheels from https://pypi.org/project/scipy/#files, `scipy-1.7.2-cp310-cp310-win_amd64.whl` does not include `.libs/msvcp140.dll`, while `scipy-1.7.2-cp39-cp39-win_amd64.whl` does include `msvcp140.dll`.

When looking at the build logs for [Windows Python 3.9](https://ci.appveyor.com/project/scipy/scipy-wheels/build/job/bjie6pkv2xm926op), we see the line that shows `msvcp140.dll` is copied into the wheel

```
[00:13:20] copying build\lib.win-amd64-3.9\scipy\.libs\msvcp140.dll -> build\bdist.win-amd64\wheel\.\scipy\.libs
```

In the build logs for [Windows Python 3.10](https://ci.appveyor.com/project/scipy/scipy-wheels/build/job/i4pv1vlslv8f1mu1) the line is missing. This is causing the import of `scipy.sparse` to fail.

Related to https://github.com/scipy/scipy/issues/7969

**Comment by rgommers** [comment]
Argh, that's a critical issue. Replacing wheels is a pain though, not 100% sure but I think if we do a `.post0` upload we have to re-upload all wheels and not just this one. So may as well do a `1.7.3` soon.

**Comment by tylerjereddy** [comment]
alright

**Comment by thomasjpfan** [comment]
According to to [this blog post](https://snarky.ca/what-to-do-when-you-botch-a-release-on-pypi/) by Bret Cannon, there is a [build number](https://packaging.python.org/specifications/binary-distribution-format/#file-name-convention) that can be incremented:

> ... what you can do is tell installers to use a newer wheel file instead via a build number, effectively shadowing the old wheel file. When wheel tags match in all other ways than build number, installers always use the wheel file with the highest build number.

**Comment by rgommers** [comment]
Ah yes, good point. We've never done that so it's possible this is not yet well-supported by all commonly used installers, but it's worth a try.

**Comment by tylerjereddy** [comment]
Reopening b/c not fixed just yet. The wheel builds on the `v1.7.x` branch of the wheels repo are now underway. IIUC correctly, we may only really need to wait for the Windows Python 3.10 wheel build to finish before downloading it, changing its name, and then uploading it, assuming we are "ok" with not officially reporting hashes to the community and so on (I could do that informally outside the normal release process I suppose for that single wheel file). For the GitHub assets I'm not sure we even need to keep the old wheel for win 3.10, for PyPI just upload the new one and leave old one alone I guess.

Here are the new wheel builds for Windows in progress, and we may luck out a bit in the sense that the first build in the matrix (which only does 1 job at a time) is Windows 3.10, though we're queued b/c of another merge event:

https://ci.appveyor.com/project/scipy/scipy-wheels/builds/41449295

If someone wants to suggest the exact name of the new wheel just to confirm whatever I try based on the docs that might help too, though presumably not too hard to figure out.

**Comment by rgommers** [comment]
> assuming we are "ok" with not officially reporting hashes to the community and so on (I could do that informally outside the normal release process I suppose for that single wheel file).

That should be fine. Hashes aren't really used, just recording the new hash on this issue should be good enough

> For the GitHub assets I'm not sure we even need to keep the old wheel for win 3.10, for PyPI just upload the new one and leave old one alone I guess.

Agreed, let's delete the broken wheel once the new one is added.

> If someone wants to suggest the exact name of the new wheel just to confirm whatever I try based on the docs that might help too, though presumably not too hard to figure out.

I believe it should be `scipy-1.7.2-1-cp310-cp310-win_amd64.whl` (change is the `-1` in `1.7.2-1`).

**Comment by tylerjereddy** [comment]
@thomasjpfan @rgommers Ok, the upload to PyPI and replacement in GitHub release page assets has been completed. It will be interesting to see if this works automatically for `pip` in CI and so on.

Before uploading I checked that `scipy/.libs/msvcp140.dll` was present in the new unzipped wheel, but not in the previous iteration.

Local hash checks via `openssl` on mac (the algos are meant to reflect the ones we normally send by email, not the ones I think are best for security):

- `MD5(scipy-1.7.2-1-cp310-cp310-win_amd64.whl)= c2029e690ba6e21ed9fc03ef8eba234b`
- `SHA256(scipy-1.7.2-1-cp310-cp310-win_amd64.whl)= dc2d1bf41294e63c7302bf499973ac0c7f73c93c01763db43055f6525234bf11`

**Comment by rgommers** [comment]
Great, thanks @tylerjereddy!

**Comment by thomasjpfan** [comment]
I can verify that that the `pip` picks up the correct version. I had a [CI build](https://github.com/thomasjpfan/scipy-windows-test/runs/4145157378?check_suite_focus=true) a Windows docker image:

```docker
FROM winamd64/python:3.10-windowsservercore-1809
RUN pip install scipy
```

And ran:

```bash
docker build -t test_build .
docker run test_build python -c "from scipy.sparse import csr_matrix"
```

The import previously failed and now passes. Thank you everyone for the quick fix!
