### ISSUE TITLE
BUG: Invalid Rotation created for 2d rotations

### ISSUE THREAD

**Issue by ds-steventondeur** [scipy/scipy#15002]
### Describe your issue.

I'm experiencing strange results when creating 2D rotations (i.e. 3D rotations but only in the XY-plane). Converting from matrix to rotation and back to matrix gives unexpected results.

The error seems to be at the creation side of the `Rotation` object as also other conversion (back to quaternion, ..) produces wrong results.

I'm working in an enviornment that also uses Tensorflow, as such my max numpy version is currently pinned to 1.19.

### Reproducing Code Example

```python
import numpy as np
from scipy.spatial.transform import Rotation

a = np.array([[ 0.15514354, -0.98789194,  0.        ],  [-0.98789194, -0.15514354,  0.        ],  [ 0.        ,  0.        ,  1.        ]])

a
#Out[6]: 
#array([[ 0.15514354, -0.98789194,  0.        ],
#       [-0.98789194, -0.15514354,  0.        ],
#       [ 0.        ,  0.        ,  1.        ]])

Rotation.from_matrix(a).as_matrix()
# Out[7]: 
#array([[-1.,  0.,  0.], 
#       [ 0., -1.,  0.], 
#       [ 0.,  0.,  1.]])

Rotation.from_matrix(a).as_rotvec()
#Out[9]: array([0.        , 0.        , 3.14159265])

Rotation.from_matrix(a).as_quat()
#Out[10]: array([0., 0., 1., 0.])
```

### Error message

```shell
# no error message, just wrong results.
```

### SciPy/NumPy/Python version information

1.7.1 1.19.5 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment]
`a` is not a [rotation matrix](https://en.wikipedia.org/wiki/Rotation_matrix); it is a reflection.  Perhaps you have the signs wrong. With, for example,
```
a = np.array([[0.15514354, -0.98789194, 0.0],
              [0.98789194,  0.15514354, 0.0],
              [0.0,         0.0,        1.0]])
```

your code works as expected.

**Comment by ds-steventondeur** [comment]
-sigh- that was a stupid mistake. Thanks for showing me the light!
