### ISSUE TITLE
BUG:  scipy.stats.multiscale_graphcorr p-values are computed differently from literature and other packages

### ISSUE THREAD

**Issue by sampan501** [scipy/scipy#15009]
### Describe your issue.

This bug is as described as here: https://github.com/neurodata/hyppo/issues/124. The issue is reproduced here:

p-values do not appear to be computed correctly. Literature review/review of similar independence testing code seems to suggest most people use the approach suggested in Phipson et al., 2011 described in 6.2 to always include the given ordering as a permutation. Should be updated for all permutation-based approaches to my knowledge.

### Reproducing Code Example

```python
from scipy.stats import multiscale_graphcorr
import numpy as np

X = np.arange(0, 25)
Y = np.arange(0, 25)
stat, pval, _ = multiscale_graphcorr(X, Y, reps=100)
print(pval)
print(stat)
>> .01
>> 1
```

p-value obtained is 1/100.

R example using energy package (contains other nonparametric multivariate independence tests using permutation tests), with energy version 1.7-7 and R version 4.0.2:

```R
require(energy)
X = 0:25; Y = 0:25; result = dcor.test(X, Y, R=100)
print(result$p.value)
>> .0099...
print(result$stat)
>> 1
```

p-value obtained is 1/(100 + 1). We should always use the result from Phipson et. al 2011, rather than only in the case where the p-value would otherwise be 0.

### Error message

```shell
There is no error message for this issue. The proposed change is very small. It would require changing this line (https://github.com/neurodata/hyppo/pull/223):


# calculate p-value and significant permutation map through list
pvalue = (null_dist >= stat).sum() / reps

# correct for a p-value of 0. This is because, with bootstrapping
# permutations, a p-value of 0 is incorrect
if pvalue == 0:
    pvalue = 1 / reps
```

to:

```
pvalue = ((null_dist >= stat).sum() + 1) / (1 + reps)
```

### SciPy/NumPy/Python version information

```
1.7.0 1.21.1 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)d
```

**Comment by tupui** [comment]
Hi @sampan501, thanks for the report. Did you write this R code? Please remove anything that might be GPL otherwise it will be a problem if latter we say there is something to fix.

**Comment by sampan501** [comment]
I think that @ebridge2 might know more about that specific R code since he wrote the original issue in `hyppo`.

I'm not sure if this is relevant, but the specific fix that I mentioned was lifted straight from here: https://github.com/neurodata/hyppo/blob/e69fe12b68fde7a86c06e18912728821db4b4362/hyppo/tools/common.py#L464. This is a package I maintain and where I had originally written the source code for `multiscale_graphcorr`.

**Comment by sampan501** [comment]
@tupui I removed the GPL code. I think that the bug still stands as mentioned in Phipson et al., 2011

**Comment by mdhaber** [comment]
Agreed on +1 in the denominator. I ran across this issue for [`permutation_test`](https://docs.scipy.org/doc//scipy/reference/generated/scipy.stats.permutation_test.html) shortly before that was finished.

@sampan501 would you submit a PR? If so, I can merge.

**Comment by sampan501** [comment]
@mdhaber Yes I will do that this week

**Comment by mdhaber** [comment]
@sampan501 just thought I'd ping you about this so we don't forget. Please mention me when you open one. Thanks!
