### ISSUE TITLE
ENH: Update the documentation to show the algorithm behind scipy.ndimage.measurements.label

### ISSUE THREAD

**Issue by allamiro** [scipy/scipy#15028]
### Is your feature request related to a problem? Please describe.

I cannot find anything on how the "scipy.ndimage.measurements.label" algorithm works or how its implemented 

### Describe the solution you'd like.

Could you please explain in the documentation the algorithm or the theory used in  scipy.ndimage.measurements.label ?

### Describe alternatives you've considered.

I have considered looking at connected component analysis algorithms however there are multiple variations of that algorithm out there the link 
https://aimagelab.ing.unimore.it/imagelab/researchActivity.asp?idActivity=15

**Comment by AtsushiSakai** [comment]
Related: #14557
