### ISSUE TITLE
LinAlgError: SVD did not converge  with default lapack_driver 

### ISSUE THREAD

**Issue by Davidcohen2** [scipy/scipy#15024]
### Describe your issue.

Hi all,

The SVD did not converge for matrix using scipy. linalg. svd.
I have checked the matrix and there aren't nans or infs

I found out that when using the non-default lapack_driver the problem is disappeared 

To reproduce this error please download the following matrix
[matrix.zip](https://github.com/scipy/scipy/files/7523302/matrix.zip)

### Reproducing Code Example

```python
#Download the attached matrix and run the following code lines:

import pickle
from scipy.linalg import svd

with open('matrix.pckl', "rb") as f:
    matrix = pickle.load(f)
    f.close()

svd(matrix,lapack_driver='gesdd')  % default lapack_driver 

#Then I got LinAlgError: SVD did not converge

#The following option seems to run without any error.
svd(matrix,lapack_driver='gesvd')
```

### Error message

```shell
LinAlgError: SVD did not converge
```

### SciPy/NumPy/Python version information

1.6.2 1.20.3 sys.version_info(major=3, minor=8, micro=11, releaselevel='final', serial=0)

**Comment by tylerjereddy** [comment]
The title mentions `numpy.linalg`--is that a typo or did you try the NumPy equivalent as well? Does this happen with the latest SciPy (`1.7.2`)?

Not sure if folks might be a little nervous to download/execute a random `zip`--maybe it is ok.

**Comment by Davidcohen2** [comment]
The same problem is with NumPy 1.20.3

I have upgraded now my scipy  and numpy according to the following to  scipy=1.7.2  and numpy=1.21.4 
Now the problem is completely gone -thank you.

I have tried to upload the pckl file but it's not supported - do you have a suggestion for the next time?

**Comment by ogauthe** [comment]
Hi @Davidcohen2 , the safest way to share arrays is to upload them as a txt on a gist, and load them using `np.loadtxt`.

In your case, this looks like an internal LAPACK issue. It will probably depend on the exact LAPACK distribution you are using (ATLAS, system LAPACK, MKL...) and probably not on numpy/scipy version. In my experience, `gesdd` is much faster but less stable than `gesvd`. I try `gesdd` first and catch an exception to use `gesvd` as a fallback.

I think there is little that can be done in scipy here, `svd` already allows to select the driver.

**Comment by tupui** [comment]
Seems like we can close this.
