### ISSUE TITLE
ENH: 3d examples for filters (e.g.  `gaussian_filter`) 

### ISSUE THREAD

**Issue by kolibril13** [scipy/scipy#15032]
### Is your feature request related to a problem? Please describe.

Right now, there are only 2D examples for Multidimensional  filters, e.g. the Gaussian filter:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.gaussian_filter.html

### Describe the solution you'd like.

Provide also 3D examples.
Toy examples in 3D will help to make the filter parameters easier to understand. 
I had the idea to use [3D voxel](https://matplotlib.org/stable/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.html#mpl_toolkits.mplot3d.axes3d.Axes3D.voxels) for that.

### Additional context (e.g. screenshots, GIFs)

Either as animation:

https://user-images.githubusercontent.com/44469195/141647703-cf3c597c-e404-4fef-b746-495d59146685.mp4

Or as images
![image](https://user-images.githubusercontent.com/44469195/141647520-81459a3c-6db8-48a6-b1d7-90c838c31484.png)
![image](https://user-images.githubusercontent.com/44469195/141647525-963691c5-f18f-416e-9705-a1d0d82cb9c9.png)

This is only a quick code draft for reproduction (not very pretty):
```py
import matplotlib.pyplot as plt
import numpy as np
import matplotlib as mpl
from scipy.ndimage import gaussian_filter
%config InlineBackend.figure_format = 'svg'

size= 10
x, y, z = np.indices((size*2, size*2, size*2))

o1,o2,o3 =(0,0,0)
cube1 = (o1 <= x) & (x < o1+size) & (o2 <= y) & (y < o2+size) &  (o3 <= z) & (z < o3+size) 

o1,o2,o3 =(size,0,0)
cube2 = (o1 <= x) & (x < o1+size) & (o2 <= y) & (y < o2+size) &  (o3 <= z) & (z < o3+size) 

o1,o2,o3 =(0,size,0)
cube3 = (o1 <= x) & (x < o1+size) & (o2 <= y) & (y < o2+size) &  (o3 <= z) & (z < o3+size) 

o1,o2,o3 =(size,size,0)
cube4 = (o1 <= x) & (x < o1+size) & (o2 <= y) & (y < o2+size) &  (o3 <= z) & (z < o3+size) 

o1,o2,o3 =(0,0,size)
cube5 = (o1 <= x) & (x < o1+size) & (o2 <= y) & (y < o2+size) &  (o3 <= z) & (z < o3+size) 

o1,o2,o3 =(size,0,size)
cube6 = (o1 <= x) & (x < o1+size) & (o2 <= y) & (y < o2+size) &  (o3 <= z) & (z < o3+size) 

o1,o2,o3 =(0,size,size)
cube7 = (o1 <= x) & (x < o1+size) & (o2 <= y) & (y < o2+size) &  (o3 <= z) & (z < o3+size) 

o1,o2,o3 =(size,size,size)
cube8 = (o1 <= x) & (x < o1+size) & (o2 <= y) & (y < o2+size) &  (o3 <= z) & (z < o3+size) 


voxelarray = np.zeros(cube1.shape)

voxelarray[cube1]=1 * 255/8
voxelarray[cube2]=2 * 255/8
voxelarray[cube3]=3 * 255/8
voxelarray[cube4]=4 * 255/8
voxelarray[cube5]=5 * 255/8
voxelarray[cube6]=6 * 255/8
voxelarray[cube7]=7 * 255/8
voxelarray[cube8]=8 * 255/8
voxelarray = np.uint8(voxelarray)

cmap = plt.get_cmap('magma')    
cols256=[]
for i in range(cmap.N):
    rgb = cmap(i)[:3] 
    cols256.append(mpl.colors.rgb2hex(rgb))

def get_color(x):
    return cols256[x]
get_color = np.vectorize(get_color)

colors = get_color(voxelarray)


def plot_voxels(varray,title):
    colors = get_color(varray)
    global ax
    ax = plt.figure().add_subplot(projection='3d')
    plt.axis('off')
    ax.voxels(varray, facecolors=colors, edgecolor="#000000",linewidth=0.1)
    ax.set_title(title) 
plot_voxels(voxelarray,"Original")
voxelarray2=gaussian_filter(voxelarray, sigma=1)
plot_voxels(voxelarray2,"gaussian_filter(voxelarray, sigma=1)")
voxelarray2=gaussian_filter(voxelarray, sigma=3)
plot_voxels(voxelarray2,"gaussian_filter(voxelarray, sigma=3)")
```

**Comment by tupui** [comment]
Thé images looks great! Would you make a PR? Maybe things like that would be better in the tutorial section.

**Comment by kolibril13** [comment]
That would be possible.
But should  all the code be displayed?
It is about 70 lines in total, but only these 6 lines are actually important to understand the gaussian_filter:
```py
from scipy.ndimage import gaussian_filter
plot_voxels(voxelarray,"Original")
voxelarray2=gaussian_filter(voxelarray, sigma=1)
plot_voxels(voxelarray2,"gaussian_filter(voxelarray, sigma=1)")
voxelarray2=gaussian_filter(voxelarray, sigma=3)
plot_voxels(voxelarray2,"gaussian_filter(voxelarray, sigma=3)")
```

**Comment by tupui** [comment]
I suggest to have a look at the stats tutorial. You will see that you can use a file to generate plots and you decide if you want the file's sources to appear or not in the tutorial. This way you can show just these 6 lines and the plot.

**Comment by kolibril13** [comment]
I guess you mean like this?
https://github.com/scipy/scipy/blame/master/doc/source/tutorial/stats.rst#L975
Sounds reasonable.
But wouldn't people then be confused because they can not find the `plot_voxels` function?

**Comment by tupui** [comment]
What we need is to understand how to construct this `voxelarray`, what's its shape, etc. And then we apply `gaussian_filter` and do some plotting. A bit like the 2D example.

**Comment by kolibril13** [comment]
Sounds good!
I can refactor the code a bit and then make a pull request.
@tupui : Would you be willing to make some fine-tuning of the formatting and commit them directly to my soon coming pull request branch, so that my example is embedded nicely in the style of the docs?

**Comment by tupui** [comment]
> Sounds good!
> 
> I can refactor the code a bit and then make a pull request.
> 
> @tupui : Would you be willing to make some fine-tuning of the formatting and commit them directly to my soon coming pull request branch, so that my example is embedded nicely in the style of the docs?

Sure of course! Thanks for making a PR 😃
