### ISSUE TITLE
BUG: ks_2samp alternative parameter is inverted

### ISSUE THREAD

**Issue by Noxbru** [scipy/scipy#15030]
### Describe your issue.

I am testing two distributions to check if they are equal, less than and greater than. But I am obtaining weird results using the Kolmogorov-Smirnov test. In particular, it seems that the alternative parameter is inverted. That is, it seems to check whether the alternative is true, rather than the null hipothesis.

As can be seen in the code example, I have generated two samples from different normal distributions, well separated so that there are no doubts that they are different. And in our case, x2 < x1.

The result of the ttest with 'less' as the alternative is that the p value is big, meaning that the null hypothesis (that x1 > x2) is true, just as expected. But for the ks_2samp test we obtain the opposite. We get that the p value is low, so the alternative hypothesis (that x1 < x2) is true, which is clearly wrong.

### Reproducing Code Example

```python
>>> import scipy.stats as st
>>> x1 = st.norm.rvs(loc=5, size=128)
>>> x2 = st.norm.rvs(loc=-5, size=128)
>>> 
>>> st.ttest_ind(x1, x2, alternative='less')
Ttest_indResult(statistic=84.0829810318511, pvalue=1.0)
>>> st.ks_2samp(x1, x2, alternative='less')
KstestResult(statistic=1.0, pvalue=1.733505188303159e-76)
```

### Error message

```shell
No Error
```

### SciPy/NumPy/Python version information

1.7.2 1.21.2 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by josef-pkt** [comment]
see #13449  #11981 and maybe a few other similar ones

**Comment by Noxbru** [comment]
Oh.
I'm sorry, I was absolutely wrong.

If I may say something, would it be possible to maybe change the documentation from:
```
This test compares the underlying continuous distributions F(x) and G(x) of two independent samples.
See Notes for a description of the available null and alternative hypotheses.
```
to
```
This test compares the underlying continuous *cumulative* distributions F(x) and G(x) of two independent samples.
See Notes for a description of the available null and alternative hypotheses.
```
?

And also add some examples where the `alternative` parameter is used explicitly? At least for the sake of completeness.
