### ISSUE TITLE
C++ api 

### ISSUE THREAD

**Issue by LingCoderSonoscape** [scipy/scipy#15038]
Hi, I am new to scipy but I feel this project is fantastic after using it. 
In  my Python project, I used "**find_peaks**" function as part of my postprocess. However, due to some reasons, I need to transfer my project into C++ code. 
I tried to find the C++ API for this function, but I failed. Could you help me with it or maybe providing an alternative way to achieve it?

**Comment by rkern** [comment]
I'm afraid that there is no corresponding C++ API for `find_peaks()`. Conceptually, the function is a relatively straightforward combination of more primitive functions, first finding all of the local peaks, then winnowing down the list based on the conditions specified by the user. These more primitive functions are written in Cython, so they should be relatively easy to translate over to C++ (e.g. they are written mostly as `for` loops over individual elements, not numpy array operations). I'm afraid there isn't much of a shortcut beyond just reading the source and translating the code over. The details of that translation are probably more affected by how you are representing your signals (plain-old `double *` arrays or `std::vector`s or more specialized array classes) than anything else, so I don't think there is much help we can provide.

I am going to close this issue as this is not a feature request or bug report. If you still have some more specific questions (like why a particular bit of the code was written in a way that you didn't expect), you can continue to ask them here, but you may not get a lot of responses. Other forums like the [mailing list](https://scipy.org/mailing-lists/) might be more likely to get some of that more specific help.

**Comment by giladroyz** [comment]
You can check this out: https://github.com/giladroyz/FindPeaks
