### ISSUE TITLE
BUG: Visualization of CWT matrix in signal.cwt example code

### ISSUE THREAD

**Issue by xiays146** [scipy/scipy#15049]
### Describe your issue.

When show the matrix which from `signal.cwt` in a figure, the x_axis represents length of  `t`, the  y_axis represents `widths` (corresponding to the scale of ricker wavelet) in example code from the Scipy website https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.cwt.html. 

It is mistake as shown in Figure 1, because a smaller width means a more narrow peak theoretically. 

**The correct figure should be like as Figure 2 which data is the y_axis flip of the cwt matrix**. 

Figure 1 is very misleading though there is nothing wrong when calculate the cwt matrix. For a better experience and improving Scipy , the bug is given.

![image](https://user-images.githubusercontent.com/48829659/141977807-82383ade-a60b-4965-827e-5bfdfaf0f482.png)
Figure 1

![image](https://user-images.githubusercontent.com/48829659/141978086-82ee86c6-6271-4eaa-b228-f991b71b72fb.png)
Figure 2

### Reproducing Code Example

```python
from scipy import signal
import matplotlib.pyplot as plt
import numpy as np
t = np.linspace(-1, 1, 200, endpoint=False)
sig  = np.cos(2 * np.pi * 7 * t) + signal.gausspulse(t - 0.4, fc=2)
widths = np.arange(1, 31)
cwtmatr = signal.cwt(sig, signal.ricker, widths)
plt.imshow(cwtmatr, extent=[-1, 1, 1, 31], cmap='PRGn', aspect='auto',
           vmax=abs(cwtmatr).max(), vmin=-abs(cwtmatr).max())
#plt.imshow(np.flip(cwtmatr, axis=0), extent=[-1, 1, 1, 31], cmap='PRGn', aspect='auto',
#           vmax=abs(cwtmatr).max(), vmin=-abs(cwtmatr).max())
plt.show()
```

### Error message

```shell
none
```

### SciPy/NumPy/Python version information

1.5.4 1.19.5 sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)

**Comment by rgommers** [comment]
Thanks for the bug report @xiays146. Fixed now in gh-16543
