### ISSUE TITLE
ENH: Return last population of scipy.optimize.differential_evolution

### ISSUE THREAD

**Issue by Abduhu** [scipy/scipy#15046]
### Is your feature request related to a problem? Please describe.

Differential evolution is population based algorithm. However, scipy.optimize.differential_evolution returns result as OptimizeResult which gives only the best elite of the population ignoring the rest of its generation.

How can someone preserve information about the last population?

### Describe the solution you'd like.

`result.x` should be the last population in sorted way. Otherwise, `OptimizeResult`  should include a new attribute that memorizes the last population.

### Describe alternatives you've considered.

Right now I have downloaded the source code to work with the class `DifferentialEvolutionSolver` directly. So it is possible to make this class available to be imported i.e: `from scipy.optimize import DifferentialEvolutionSolver`

**Comment by tupui** [comment]
Hi @Abduhu. All optimizers have a `callback` parameter that you could use to track additional things like that. But it's a frequent request to have an history of function calls. Maybe we should consider adding something along the line.

**Comment by andyfaff** [comment]
Just as a matter of interest, is there a reason you'd like to see the final population (or even intermediate populations)? Note that the final population, if left to converge, is unlikely to have much variation in it. It would be an easy thing to return in the OptimizeResult, but I do wonder about the utility.

Whilst it's possible to use DifferentialEvolutionSolver directly you should be aware that it's currently a private class, and is subject to possible changes.

It's been raised several times that it'd be good to have something like an intermediate `OptimizeResult` that is provided to the callback function at each iteration. The population would be a good attribute to have in that callback function. Returning the entire history of the population would potentially take a large amount of memory.

**Comment by andyfaff** [comment]
@tupui the callback doesn't return the population, just the best solution so far.

**Comment by tupui** [comment]
> It's been raised several times that it'd be good to have something like an intermediate `OptimizeResult` that is provided to the callback function at each iteration. The population would be a good attribute to have in that callback function. Returning the entire history of the population would potentially take a large amount of memory.

The memory concern is real although it would depend on how/what/which frequency we store. Users could have the choice. For some, it's interesting to have a way to understand the optimization path the algorithm took.

> @tupui the callback doesn't return the population, just the best solution so far.

Just seeing this, thanks @andyfaff. Maybe we could provide more here. Then a user could track what they want and we would not need to handle the storing interface ourselves.

**Comment by tupui** [comment]
The behaviour of the callback is actually inconsistent here. My confusion was coming from the fact that for other minimizers from `minimize` it does return the input vector and not the solution.

**Comment by andyfaff** [comment]
The `x/xk` in all those `callback` are equivalent, the (best) solution (so far) at the end of each solver iteration loop.

**Comment by tupui** [comment]
> The `x/xk` in all those `callback` are equivalent, the (best) solution (so far) at the end of each solver iteration loop.

In `minimize` it says `where xk is the current parameter vector` while in `differential_evolution` it says `xk is the current value of x0. val`.

**Comment by andyfaff** [comment]
The callback signature for trust-constr looks good, that should be rolled out to all methods.

**Comment by andyfaff** [comment]
> differential_evolution it says xk is the current value of x0

that docstring is incorrect, it's basically the same as the others.

**Comment by tupui** [comment]
> The callback signature for trust-constr looks good, that should be rolled out to all methods.

Agreed. We could use the new version and if the old signature is found, have a wrapper to print a warning and convert to the new signature. I can give it a try if you want?

**Comment by andyfaff** [comment]
It'd require a bit of thought. Each minimizer is going to want to fill out slightly different attributes of an intermediate `OptimizeResult`. There would have to be a wrapper that could distinguish between the old/new signatures (e.g. `state` present as a keyword argument), but I'm not sure if (how much) the wrapper would have to be specialised for each method. It might require that each minimizer method has to be altered, which is not trivial.

I think it'd be worth discussing a design before a lot of code is written.

**Comment by tupui** [comment]
I think that what could be convenient/future proof to have is both the full current state (common things and extras to be defined per optimizer) and the current optimization result. That would be two data structure to pass. Something like

```python
def callable(state: CurrentState, result: OptimizeResult):
    ...
```

Practically, as these callables are user code, we could inspect the functions to determine (`inspect.signature(callable).parameters`) if we can pass the new structure or have to pass the old one-along with a deprecation warning.

**Comment by andyfaff** [comment]
If I remember correctly there's been a discussion on the scipy-dev mailing list about modifying the callback before, and there are also a few related GH issues/PRs.
I think having more than one data structure to pass would be unwieldy. My preference would just me to have a single `state`. The object (`OptimizeState`?) could be composed from an `OptimizeResult`, so it would have similar attributes, but also other information.

Making `DifferentialEvolutionSolver` public is a two edged sword. It would give the user a lot more control, but it would make my ultimate wish of bringing #8414 and #8552 to life harder. Those ancient WIP describe class based Optimizers. I believe that a class based Optimizer could bring more uniformity to how minimizers are interacted with. The existing `minimize` function is already doing a  pretty good job, it just has some pain points.

(note that with DifferentialEvolutionSolver there's no need to use a callback, because it's an iterator and on each step you can inspect the internals)

**Comment by tupui** [comment]
I didn't know about the SciPEP, thanks. What is the status on this? I don't see much activity since 2-3 years. I am sure we can find people to help working on the architecture and do the implementation part if we finish the proposal (this would fit a GSoC or SDG). With SciPy 2.0 coming up, we have a good opportunity to change things.

**Comment by Abduhu** [comment]
> Just as a matter of interest, is there a reason you'd like to see the final population (or even intermediate populations)? Note that the final population, if left to converge, is unlikely to have much variation in it. It would be an easy thing to return in the OptimizeResult, but I do wonder about the utility.

In some cases, users want to study the evolution of a specific optimization problem. Returning back the last population is enough since we can always continue evolution from it.

**Comment by andyfaff** [comment]
It's also possible to keep the populations at each iteration using the ability of the workers keyword to accept a map-like callable that is sent the entire population and is expected to return an array with the function values evaluated for the entire population:

```
from scipy.optimize import rosen, differential_evolution
bounds=[(0, 10), (0, 10)]

# pop will retain all population at each iteration of the minimisation
# you could also keep the the function values corresponding to those vectors.
pop = []
def maplike_fun(func, x):
    # x.shape == (S, N), where S is the size of the population and N
    # is the number of parameters. The rosen function is vectorised,
    # so calling rosen with x.T will return an array of shape (S,)
    # you could also do:
    # v = np.array(list(map(func, x)))
    pop.append(x)
    return func(x.T)

res = differential_evolution(rosen, bounds, workers=maplike_fun, polish=False, updating='deferred')
# the initial evaluation of the population is not counted in the number
# of iterations, so pop[0] is the initial population.
assert res.nit == len(pop) - 1
```
From scipy 1.9 there will also be a vectorized keyword, which will send the entire population to the objective function at each iteration.
