### ISSUE TITLE
BUG: pip -install scipy failing on PypPy 7.3.7

### ISSUE THREAD

**Issue by carlosyanez** [scipy/scipy#15056]
### Describe your issue.

Hi!,

When trying to install scipy on pypy 7.3.7, it fails due to numpy failing to build - this happens even if numpy has been previously installed.

This issue has been raised here https://github.com/pypa/pip/issues/10631 - but it doesn't seem to be  a pip problem.
I'm just copying the example submitted by @gwerbin - but further troubleshooting has been done on the aforementioned thread.

Thanks,
Carlos

### Reproducing Code Example

```python
#How to Reproduce

/usr/local/bin/pypy3 --version
# Python 3.7.12 (44db26267d0a38e51a7e8490983ed7e7bcb84b74, Oct 28 2021, 05:11:03)
# [PyPy 7.3.7 with GCC Apple LLVM 13.0.0 (clang-1300.0.29.3)]

/usr/local/bin/pypy3 -m venv ./my-project
./my-project/bin/python -m pip install -U pip setuptools wheel

#This works fine:

./my-project/bin/python -m pip install numpy

#This does not:

./my-project/bin/python -m pip install -U scipy

#But this works fine (until it hits the unrelated Cython error):

./my-project/bin/python -m pip install --no-use-pep517 -U scipy
```

### Error message

```shell
< ... huge build log and traceback ... >

    AssertionError: would build wheel with unsupported tag ('pp37', 'pypy37_pp73', 'macosx_10_7_x86_64')
    ----------------------------------------
    ERROR: Failed building wheel for numpy
  Failed to build numpy
  ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
  ----------------------------------------
```

### SciPy/NumPy/Python version information

1.7.1 1.21.2 sys.version_info(major=3, minor=8, micro=12, releaselevel='final', serial=0)

**Comment by rgommers** [comment]
Thanks @carlosyanez. Investigated and commented on https://github.com/pypa/pip/issues/10631. I'll close this to avoid having a duplicate issue. In case the discussion turns up that it is a SciPy issue after all, we can reopen.
