### ISSUE TITLE
TST: review usage of `_assert_within_tol` with positional arguments in `test_distance.py`

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#15058]
While working on #15055, I found that tests in `test_distance.py` (seemingly unintentionally) use absolute rather than relative tolerance, because `_assert_within_tol` is often called with positional parameters that end up being filled into the signature:
```
def _assert_within_tol(a, b, atol=0, rtol=0, verbose_=False):
```

There are some that are definitely misleading (or outright false), because a call-site like
```
_assert_within_tol(Y1, Y2, eps, verbose > 2)
```
will end up calling `rtol=False/True`, which then presumably gets cast to 0/1.

I think these tests need some review if they're working as intended, and @peterbell10 agreed in #15055 that this should be tracked.

**Comment by Kai-Striega** [comment]
I haven't done much work on `spatial` but I'd be happy to start looking at them. I'm guessing that to fix these changes it would be a matter of changing the above (and similar) call sites to something more like ``_assert_within_tol(a, b, rtol=eps, verbose_=verbose > 2)`` as appropriate.

**Comment by h-vetinari** [comment]
Hey @Kai-Striega, that would be great thanks! :)
In addition, I believe the `eps` per test should be reviewed - I think generally it should be possible to be in the range of `1e-15` to `1e-13` for relative tolerance, but many tests (presumably due to actually measuring absolute tolerance currently) use a way higher `eps` at the moment.

**Comment by Kai-Striega** [comment]
Looking at the code, do you think it's still necessary to have a separate function ``_assert_within_tol`` looking at the definition:

```python
def _assert_within_tol(a, b, atol=0, rtol=0, verbose_=False):
    if verbose_:
        print(np.abs(a - b).max())
    assert_allclose(a, b, rtol=rtol, atol=atol)
```
all it does is add an extra print statement to an existing ``assert_allclose`` check. With modern IDEs / tooling this seems kinda redundant and could be simplified to just the ``assert_allclose`` call. Thoughts?
