### ISSUE TITLE
ENH: allow KDTree to be constructed with single-precision data

### ISSUE THREAD

**Issue by ajouellette** [scipy/scipy#15065]
### Is your feature request related to a problem? Please describe.

Currently the KDTree implementation copies the data if it is not a contiguous array of doubles. I am trying to construct trees for large arrays of single-precision data (a couple GBs). The way it currently works, the data has to be copied as well as promoted to double-precision greatly increasing the memory usage to the point where it is basically prohibitive.

### Describe the solution you'd like.

Ideally, the KDTree would not copy data as long as the input array is contiguous with the data type of the internal data depending on the type of the input data (float32 or float64). This would allow trees to be constructed for much larger datasets as long as the data fits in memory in a contiguous array.

### Describe alternatives you've considered.

I'm not sure how hard this would be to implement since it looks like sckit-learn's KDTree and BallTree also have this issue (https://github.com/scikit-learn/scikit-learn/issues/7059). And I don't know too much about cython to look into the internals of the implementation.

I've also found this package https://github.com/storpipfugl/pykdtree that is able to construct trees with either float64 or float32 data, but it doesn't look like it supports periodic boundary conditions like scipy's implementation and can only query for the k nearest neighbors rather than querying a radius.

Thanks!

**Comment by mdhaber** [comment]
gh-18467 is a duplicate, but I'm closing this one because there's more information there.
