### ISSUE TITLE
How to get the angular frequencies of .wav file?

### ISSUE THREAD

**Issue by IshkMagar** [scipy/scipy#15068]
I am trying to get the angular frequencies of .wav file but I think I am doing it wrong. May I know how to fix it?

import numpy as np
from scipy import signal
from scipy.io.wavfile import read

** load the audio signal
sampling_rate, data = read('audio.wav')
print(f'sample rate is ', sampling_rate)
** get length of the audio signal
length = data.shape[0] / sampling_rate
time = np.linspace(0, length, data.shape[0])

** I am having an issue here. May I know what I have done wrong here
freq = np.linspace(time, 5, data.shape[0])

print(f'time shape {time.shape} , data shape {data[:,0].shape}, freq shape {freq.shape}')

**Comment by tupui** [comment]
Hi @IshkMagar, thanks for stopping by. What is your issue? Can you follow the template and provide a minimal working example reproducing the bug?

Please note that if there is no bug, we don't have the bandwidth to answer user questions and I would ask you to either use the mailing list or other forums like StackOverflow.

**Comment by IshkMagar** [comment]
@tupui, This is the error I am getting 
MemoryError                               
Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_18124/1475926947.py in <module>
      1 # I am having an issue here. May I know what I have done wrong here
----> 2 freq = np.linspace(time, 5, data.shape[0])
      3 
      4 print(f'time shape {time.shape} , data shape {data[:,0].shape}, freq shape {freq.shape}')

<__array_function__ internals> in linspace(*args, **kwargs)

~\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\function_base.py in linspace(start, stop, num, endpoint, retstep, dtype, axis)
    151                 y *= step
    152             else:
--> 153                 y = y * step
    154     else:
    155         # sequences with 0 items or 1 item with endpoint=True (i.e. div <= 0)

MemoryError: Unable to allocate 877. GiB for an array with shape (343067, 343067) and data type float64

**Comment by tupui** [comment]
I think the error is pretty self explanatory. You are trying to allocate a huge array and you don't have this much RAM. Check the arguments when you are creating the array:

```python
np.linspace(time, 5, data.shape[0])
```

With that being said, it seems there is no issue related to SciPy, hence I will close it for now. Still, if you can show there is indeed a bug, I would gladly reopen 😃. Thanks again for the report.

**Comment by IshkMagar** [comment]
fft_spectrum = np.fft.rfft(data[:,0])
freq = np.fft.rfftfreq(data[:,0].size, 1/sampling_rate)
pgram = signal.lombscargle(time, data[:,0], freq, normalize=True)


I am getting error here. I don't know it is bug or not. 
ZeroDivisionError                         Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_4696/1439696588.py in <module>
     12 print(data[:,0])
     13 print(freqs)
---> 14 pgram = signal.lombscargle(time, data[:,0], freq, normalize=True)
     15 #plt.plot(freq, pgram)

~\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\signal\spectral.py in lombscargle(x, y, freqs, precenter, normalize)
    148         pgram = _lombscargle(x, y - y.mean(), freqs)
    149     else:
--> 150         pgram = _lombscargle(x, y, freqs)
    151 
    152     if normalize:

ZeroDivisionError: ()
