### ISSUE TITLE
I can not understand the extrinsic and intrinsic rotation order.

### ISSUE THREAD

**Issue by FavorMylikes** [scipy/scipy#15080]
After some research, for now, I understand `scipy` has right-handed axis coordinate system, and left-handed rotation.

For example

```python
from scipy.spatial.transform import Rotation as R
np.array([0,1,0]) @ R.from_euler("XYZ", [0,0,30], degrees=True).as_matrix()  # should be [0.5,sqrt(3)/2,0]
```

But I can not figure out the different between `extrinsic` and `intrinsic` rotation.

For my understand.

`extrinsic` should use a fixed axis, and `intrinsic` should use rotatable axis.

So, if I understand this correctly.

Here "XYZ" means `intrinsic rotation`, you can find it at the [official doc](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.from_euler.html#reaa093f6923f-1)

```python
# should be [-0.5,sqrt(3)/2,-1]
# But it is [0.5,sqrt(3)/2,-1], seems like the `extrinsic rotation`
np.array([0,1,1]) @ R.from_euler("YZX", [0,180,30], degrees=True).as_matrix()
# should be [0.5,sqrt(3)/2,-1]
# But it is [-0.5,sqrt(3)/2,-1], seems like the `intrinsic rotation`
np.array([0,1,1]) @ R.from_euler("yzx", [0,180,30], degrees=True).as_matrix()
```

Am I misunderstand this?

**Comment by tupui** [comment]
Hi @FavorMylikes, I am afraid we do not answer user questions here but only deal with bugs as we do not have the bandwidth for that. Please ask your question on the user mailing list or another forum like StackOverflow.

**Comment by rkern** [comment]
When representing the `Rotation` as a matrix, it's supposed to be multiplied on the left of the vector, not the right. Positive Euler angles are right-handed rotations when applied this way.

```
[~]                                                                                                                                                                                                                  
|6> R.from_euler("XYZ", [0,0,30], degrees=True).as_matrix() @ np.array([0, 1, 0])                                                                                                                                    
array([-0.5      ,  0.8660254,  0.       ])

[~]                                                                                                                                                                                                                  
|7> R.from_euler("XYZ", [0,0,30], degrees=True).apply(np.array([0, 1, 0]))                                                                                                                                           
array([-0.5      ,  0.8660254,  0.       ])
```
