### ISSUE TITLE
BUG: Segmentation fault caused by scipy.stats.qmc.qmc.update_discrepancy

### ISSUE THREAD

**Issue by 99991** [scipy/scipy#15081]
### Describe your issue.

The array `abs_` in the function `_cy_wrapper_update_discrepancy` is of size `sample_view.shape[0] + 1`, which is 3 + 1 = 4 in the reproducing code example below. The write operation in line 258 causes memory corruption when `x_new_view.shape[0]` is 4 or larger (e.g. 11 in this example).

https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/stats/_qmc_cy.pyx#L258

### Reproducing Code Example

```python
import numpy as np
from scipy.stats import qmc

samples = np.random.rand(3, 11)
x = np.random.rand(11)

qmc.update_discrepancy(x, samples, 4)
```

### Error message

```shell
Segmentation fault
```

### SciPy/NumPy/Python version information

1.7.2 1.19.1 sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @99991 thanks for the report. I am looking into this and indeed it does not sounds right. Seems like we interchanged dimensions with number of samples when translating this to Cython.

**Comment by tupui** [comment]
Actually no it's fine. I got confused for an instant with the naming which says line although it's a column. (this should be modified).

We have `xnew_nlines = x_new_view.shape[0]` which is the dimension. Here 11. And in the loop we do use `xnew_nlines` to iterate on `x_new_view`. Which is correct.

```python
    for i in range(xnew_nlines):
        abs_[i] = fabs(x_new_view[i] - 0.5)
```

With your example I could not reproduce any segmentation fault.

As a side note. I am curious about why you have a discrepancy of 4? For such dimension it seems huge.

**Comment by 99991** [comment]
Unfortunately, memory corruption might manifest itself in nondeterministic ways. The original code only crashed sporadically. Perhaps it is possible to trigger the error more easily by setting `boundscheck=True` here:

https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/stats/_qmc_cy.pyx#L2

Alternatively, it might be sufficient to increase the 11 from the minimal reproducible example to 9999 or some other large number.

To fix this bug, it might be sufficient to change

https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/stats/_qmc_cy.pyx#L253

to

```python
double[::1] abs_ = np.zeros(xnew_nlines, dtype=np.float64)
```

although I have not worked through the math yet, so I do not know if that makes any sense at all. (Just to make sure: The invalid index is in the left hand side with `abs_[i]` because the array `abs_` is too small. The right hand side with `x_new_view[i]` is fine.)

**Comment by tupui** [comment]
> although I have not worked through the math yet, so I do not know if that makes any sense at all. (Just to make sure: The invalid index is in the left hand side with `abs_[i]` because the array `abs_` is too small. The right hand side with `x_new_view[i]` is fine.)

Thank you for the additional information. I will have a look at what I originally intended here. `abs_` should be like the dimension indeed.

**Comment by tupui** [comment]
I could reproduce the bug as you said by enabling `boundscheck`

```python
Exception ignored in: 'scipy.stats._qmc_cy.c_update_discrepancy'
Traceback (most recent call last):
  File ".../scipy/scipy/stats/_qmc.py", line 373, in update_discrepancy
    return _cy_wrapper_update_discrepancy(x_new, sample, initial_disc)
IndexError: Out of bounds on buffer access (axis 0)
```

Would you like to make a PR? Otherwise I will do it. The following is to be done:

I propose to remove the confusing line `xnew_nlines` and do `Py_ssize_t d = sample_view.shape[1]` (we already check the dimensions matches when calling this function). And then we can have `double[::1] abs_ = np.empty(d, dtype=np.float64)`. We will also need to have test to cover this case.

**Comment by 99991** [comment]
Great! Feel free to go ahead with the PR.
