### ISSUE TITLE
DOC: Sampling from the truncated normal 

### ISSUE THREAD

**Issue by mikewojnowicz** [scipy/scipy#15082]
### Describe your issue.

The sample means for runs of the code below concentrate around .36, not .50, as expected.   
 
Am I misunderstanding the documentation and examples?  I was expecting `mu` to reflect the expected value of the probability distribution post-truncation. 

### Reproducing Code Example

```python
from scipy.stats import truncnorm 
import numpy as np 

lower = -5
upper = 1
mu = 0.5
sigma = 0.5
N = 100000

samples = truncnorm.rvs(
          (lower-mu)/sigma,(upper-mu)/sigma,loc=mu,scale=sigma,size=N)
print(f"The sample mean is {np.mean(samples):.02f}.")
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

numpy==1.19.4, scipy==1.7.1

**Comment by rkern** [comment]
The `loc` parameter is the mean of the underlying normal distribution, not the mean of the final truncated distribution. The docstring could be a little clearer about that.

**Comment by mikewojnowicz** [comment]
@rkern Ah, I see, thanks for the clarification.   Ran another quick simulation and it now works as expected.  

Agree re: documentation.  Even just a slightly altered documentation which includes the first sentence you wrote above would have been illuminating for me.

**Comment by tupui** [comment]
Would you make a PR @mikewojnowicz to improve the documentation?

**Comment by NamamiShanker** [comment]
Can I make a PR if @mikewojnowicz doesn't want to work on this?

**Comment by mikewojnowicz** [comment]
@NamamiShanker  Go for it.  I'm recovering from a bike accident so bandwidth is poor right now.

**Comment by tupui** [comment]
Really sorry to read that. Hope you recover soon.
