### ISSUE TITLE
BUG: Implementation of Bessel Functions in Scipy

### ISSUE THREAD

**Issue by pontsm** [scipy/scipy#15091]
### Describe your issue.

According to the documentation in scipy, the spherical bessel function (https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.spherical_jn.html#r1a410864550e-3) 
is implemented using a recursion relation provided in the documentation: 
(https://dlmf.nist.gov/10.51#E1)

However, there are two issues I seem to have with this:

1) The documentation says that for arguments bigger than the order, reference [1] is used and for small arguments
reference [2] is used. However, when rearranging reference [2], I get _the same equation_ as in reference [1], which seems
very suspicious to me. Can someone explain this?

2) When using the relation given in the reference, it only seems to hold for arguments bigger than the order
but not for arguments smaller than the order, even though the documentation specifies that for small arguments
the same relation is used.

_PLEASE_ clarify this. It is a very important and urgent issue for me.

### Reproducing Code Example

```python
#Implementation using the derivative definition for the spherical bessel functions
def besselrecursion(n,x):
    
    if n >= 2:
        result = (2*(n-1)+1)/x * besselrecursion(n-1,x) - besselrecursion(n-2,x)
    elif n == 1:
        result = np.sin(x)/x**2 - np.cos(x)/x
    elif n == 0:
        result = np.sin(x)/x
    return result

#Alternative definition of the recurrence relation using the implemented jn directly

def besselrecursion(n,x):
    
    if n >= 2:
        result = (2*(n-1)+1)/x * besselrecursion(n-1,x) - besselrecursion(n-2,x)
    elif n == 1:
        result = spherical_jn(1,x)
    elif n == 0:
        result = spherical_jn(0,x)
    return result

#already with order 30 and argument 12 the results vary greatly
z = 12
n = 30
print(besselrecursion(n,z))
print(spherical_jn(n,z))
```

### Error message

```shell
No Error message
```

### SciPy/NumPy/Python version information

1.7.1 1.19.5 sys.version_info(major=3, minor=8, micro=11, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi! Maybe having a look at the tests and implementation could give you some insights? https://github.com/scipy/scipy/blob/57bf4d674c6d31ce5e070498c8cbdc0f2ea8c8d6/scipy/special/tests/test_spherical_bessel.py#L14
https://github.com/scipy/scipy/blob/master/scipy/special/_spherical_bessel.pxd

**Comment by pontsm** [comment]
Thanks for the answer. I checked it out but it doesn't give any more information regarding the problem.

In any text I can find there is no restriction on order or argument for which the recursion relation holds. 
So as far as I can see the recurrence relation has to hold for every order and every argument.

However, as can be seen from my code example, if I implement the recursion relation, the values do not
match the values computed by the implemented functions. 

This is the problem and (at least for me) to solve this problem one of two things are needed.

Either (1) there is a source specifying that this recurrence relation only holds for arguments bigger than the order
(documentation page says that but I didn't find any independent source verifying this), or (2) there is something
wrong with the implementation in scipy and the recursion relation gives the correct values.

Any help is greatly appreciated.

Here some sources for the recursion relations:

Handbook of mathematical functions, Abramowitz, p.439
The NIST link provided above doesn't specify a constraint on the argument/order either

**Comment by pontsm** [comment]
Also, the documentation talks about the "definitional relation to the cylindrical Bessel functions"

(https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.spherical_jn.html#scipy.special.spherical_jn)

However, I cannot find any reference anywhere to "cylindrical" Bessel functions or a "definitional" relation.

**Comment by duetosymmetry** [comment]
@pontsm, the "cylindrical" Bessel functions are just the usual ones, `scipy.special.jv(v,z)`. The docs can definitely be improved. If you look at the [relevant part of the implementation](https://github.com/scipy/scipy/blob/a25ea1bf5d069f2dd2f9f78393d4c97377f16599/scipy/special/_spherical_bessel.pxd#L91-L109), you see that it dispatches to the usual Bessel function when n>=x. This is what's meant by the "definitional relation". Meanwhile, when x>n, the multiplicative factors in the recurrence relation will have absolute value less than one. That's the region where using the recurrence relation is advantageous.

**Comment by pontsm** [comment]
@duetosymmetry Thank you for the code reference and your answer! This helped.

It did, however, not yet fully answer why the recurrence relation seems to give values that diverge more and more
from the correct value when applying it to x<n, for example x=12, z=30, which is the case in the code example above.

Is the recurrence relation only valid for x>n? This is the statement I cannot find anywhere in literature.

Thank you again :)

**Comment by duetosymmetry** [comment]
The recurrence relation is valid everywhere in the complex plane. Back [on the DLMF](https://dlmf.nist.gov/10.51#E1), they include conditions for when an identity is valid. Here the only condition is that n=1, 2, …, but z is any complex variable.

As n becomes very large with fixed z, the result for spherical_jn(n,z) becomes exponentially small (see the [asymptotic expansion on the DLMF](https://dlmf.nist.gov/10.19#E1) and apply the relationship between ordinary and spherical Bessel functions). This means that if you tried to use the recurrence relation to compute spherical_jn, you would be relying on very large cancellations. This will be extremely inaccurate. This is why the code only uses the recurrence relation when n < |z|.

**Comment by ilayn** [comment]
I think this issue is settled so I'll close but feel free to continue discussion if there is anything left
