### ISSUE TITLE
scipy.integrate.solve_ivp runtime event

### ISSUE THREAD

**Issue by chsher** [scipy/scipy#15128]
I would like to include an event in my ODE solver that requires the solver to terminate after it has been running for 60 seconds. However, when I include the below event function, I receive an error: 

> ValueError: f(a) and f(b) must have different signs

Do you know why this may be happening and how to remedy it?   

```
def time_event(t, y, start, elapsed_max=60): 
    current = time.time()
    elapsed = current - start
    return elapsed - elapsed_max 
```

![image](https://user-images.githubusercontent.com/23045343/144078117-96118292-8247-4982-a757-a9ada4bf6230.png)

**Comment by tupui** [comment]
Hi @chsher. Please note that this is not a user forum but a bug/enhancement reporting platform. We don't have the necessary bandwidth to address questions.

If after asking on StackOverflow or the mailing list there is indeed a bug, we would be happy to have a look.
