### ISSUE TITLE
BUG: Log_norm description is incorrect and produces incorrect results if interpreted literally

### ISSUE THREAD

**Issue by ynad93** [scipy/scipy#15133]
### Describe your issue.

Hello! In scipy.stats, the LogNorm distribution claims that "mu" is the mean... it is totally wrong. The "scale" parameter is the median and the "s" parameter behaves exactly as defined on the Wikipedia LogNorm page. This is only form testing and using the lognorm.rvs() function for astrophysical research

### Reproducing Code Example

```python

import matplotlib.pyplot as plt
import numpy as np

fig, axs = plt.subplots()
N = 1000000
mo = .001
median = .01

s = np.sqrt(np.log(median/mo))
compare = lognorm.rvs(s, scale=median)

axs.set_xscale('log')

axs.hist(compare, bins=bins, density=False, histtype='step')

plt.show()

print(np.median(compare), median)

print(np.mean(compare), median*np.exp(.5*s**2))
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

1.5.1 1.19.0 sys.version_info(major=3, minor=8, micro=4, releaselevel='final', serial=0)

**Comment by rkern** [comment]
The docstring does not claim that `mu` is the mean of the log-normal distribution.

```
A common parametrization for a lognormal random variable ``Y`` is in
terms of the mean, ``mu``, and standard deviation, ``sigma``, of the
unique normally distributed random variable ``X`` such that exp(X) = Y.
This parametrization corresponds to setting ``s = sigma`` and ``scale =
exp(mu)``.
```

`mu` is described as the mean of the "normally distributed random variable ``X`` such that exp(X) = Y"

**Comment by rkern** [comment]
It's certainly likely that a rephrasing of that sentence could be clearer. Perhaps introducing the normally-distributed `X` random variable and its transformation to `Y` first, then talking about the mean and standard deviation of `X`.
