### ISSUE TITLE
I have a real recorded signal in the .wav file. I want to find the start and end time of data processing. 

### ISSUE THREAD

**Issue by IshkMagar** [scipy/scipy#15132]
### Is your feature request related to a problem? Please describe.

I have a real recorded signal in the .wav file. I want to find the start and end time or just the start time of data processing in the signal. I have a noisy real signal that is flowing on the air recorded in the .wav file. There is a way to find the start and end times of voice signal processing. I want to use the same idea for real signals too. If you guys have a scipy library to solve my issue then would you please share it?

**Comment by tupui** [comment]
Hi @IshkMagar. Sorry but we don't have the bandwidth to answer user questions. Issues are only for feature requests or bug. Please ask your question on the user mailing list or other forums like StackOverflow.
