### ISSUE TITLE
ENH: interp1d should be able to perform interpolation in log space

### ISSUE THREAD

**Issue by jvavrek** [scipy/scipy#15146]
### Is your feature request related to a problem? Please describe.

If (x, y) data looks linear on a log-log plot it is often more appropriate to perform 1D linear interpolation on the log-scaled (x, y) data and input x value.

### Describe the solution you'd like.

`scipy.interpolate.interp1d` should take two new kwargs, perhaps called `xspace` and `yspace`, that are either `"linear"` (default) or `"log"`. (Or maybe one `space` kwarg such as `"linlog"` that gets parsed appropriately?)

If `yspace == 'log'`, the input y data is log-scaled; if `xspace == 'log'`, the input x data and the interpolation x point(s) are log-scaled. Interpolation (whether linear or spline or whatever) then proceeds normally. The output y point(s) are then exp-scaled if `yspace == 'log'` to reverse the initial log-scaling.

Care needs to be taken to avoid `log(0)` situations.

### Describe alternatives you've considered.

The community [recommends](https://stackoverflow.com/questions/29346292/logarithmic-interpolation-in-python) a DIY loglog interpolation, and I have done something similar in my own code, but I think this should be added to `scipy` as well.

**Comment by ev-br** [comment]
-1. 
The need for something like this does arise quite often. However, I believe this should stay in userland. Whether to use np.interp (as in the SO example from the OP) or interp1d, as well as whether to use loglog or semilog scales (or some other nonlinear transform) is problem-dependent, and is best done in user code IMO.

**Comment by tupui** [comment]
Agreed, I am also -1. There are many cases to consider. We would need to really work on the API first.

**Comment by byoung4** [comment]
I happened to need this functionality today, so I whipped up something quick. It's not necessarily pretty with argument checks and other such luxuries, but it's a good place to start.

```python
import numpy as np
import scipy.interpolate
import matplotlib.pyplot as plt

class interpolate1d(scipy.interpolate.interp1d):
    """Extend scipy interp1d to interpolate/extrapolate per axis in log space"""
    
    def __init__(self, x, y, *args, xspace='linear', yspace='linear', **kwargs):
        self.xspace = xspace
        self.yspace = yspace
        if self.xspace == 'log': x = np.log10(x)
        if self.yspace == 'log': y = np.log10(y)
        super().__init__(x, y, *args, **kwargs)
        
    def __call__(self, x, *args, **kwargs):
        if self.xspace == 'log': x = np.log10(x)
        if self.yspace == 'log':
            return 10**super().__call__(x, *args, **kwargs)
        else:
            return super().__call__(x, *args, **kwargs)
```

And here is a usage example

```python
# linear space data
x_lin = np.linspace(-10, 10, 32)
y_lin = x_lin

# log space data
x_log = np.logspace(np.log10(1e-2), np.log10(100), 32)
y_log = x_log**.5

# make interp/extrap objects
f_linlin = interpolate1d(x_lin, y_lin,                             fill_value='extrapolate')
f_loglin = interpolate1d(x_log, y_lin, xspace='log',               fill_value='extrapolate')
f_linlog = interpolate1d(x_lin, y_log,               yspace='log', fill_value='extrapolate')
f_loglog = interpolate1d(x_log, y_log, xspace='log', yspace='log', fill_value='extrapolate')

# x-axes to interp/extrap onto
x_lin2 = np.linspace(-15, 15, 32)
x_log2 = np.logspace(np.log10(1e-3), np.log10(500), 32)

def style_axes(axes):
    """small function to reduce code clutter"""
    for ax in axes:
        ax.minorticks_on()
        ax.grid(which='minor', alpha=.4, linestyle='--')
        ax.grid(which='major', alpha=.7)
        ax.set_title('{}-{}'.format(ax.get_xscale(), ax.get_yscale()), fontsize=14)
        ax.tick_params(labelsize=12)

# plot lin-lin
fig, axes = plt.subplots(ncols=2, figsize=[16,8])
for ax in axes:
    ax.plot(x_lin, y_lin, 'o-')
    ax.plot(x_lin2, f_linlin(x_lin2))
style_axes(axes)
plt.show()

# plot log-lin
fig, axes = plt.subplots(ncols=2, figsize=[16,8])
for ax in axes:
    ax.plot(x_log, y_lin, 'o-')
    ax.plot(x_log2, f_loglin(x_log2))
axes[0].set_xscale('log')
style_axes(axes)
plt.show()

# plot lin-log
fig, axes = plt.subplots(ncols=2, figsize=[16,8])
for ax in axes:
    ax.plot(x_lin, y_log, 'o-')
    ax.plot(x_lin2, f_linlog(x_lin2))
axes[0].set_yscale('log')
style_axes(axes)
plt.show()

# plot log-log
fig, axes = plt.subplots(ncols=2, figsize=[16,8])
for ax in axes:
    ax.plot(x_log, y_log, 'o-')
    ax.plot(x_log2, f_loglog(x_log2))
axes[0].set_xscale('log')
axes[0].set_yscale('log')
style_axes(axes)
plt.show()
```

**Comment by tupui** [comment]
Thank you @byoung4 for the code snippet. I will close this issue now and interested people can still find this as reference.

The transformation is really simple and easy to do on users side and as we said there are too many things we would need to consider if we added this in SciPy instead. To start with why a log transformation vs any other transformation.
