### ISSUE TITLE
BUG: least_squares cannot fit the correct result but leastsq can

### ISSUE THREAD

**Issue by WZG3661** [scipy/scipy#15148]
### Describe your issue.

when I test least_sqauls, I find that it can't fit the correct result, but leastsq can.
Sometimes least_sqauls can get right result, but when run multiple times,  always get wrong result.
But leastsq always can get the right result, is much more stable than least_sqauls.

### Reproducing Code Example

```python
import matplotlib.pyplot as plt
import numpy as np
from scipy.optimize import least_squares, leastsq

def func(x, p):
    A, k, theta = p
    return A * np.sin(2 * np.pi * k * x + theta)

def residuals(p, x, y):
    return func(x, p)-y

x = np.linspace(0, -2 * np.pi, 100)
A, k, theta = 10, 0.34, np.pi / 6                       # parameters to estimate
y_truth = func(x, [A, k, theta])                        # true values
y_obs = y_truth + 2 * np.random.randn(len(x))           # observations with noise
p0 = [7, 0.2, 0]                                        # initial value

plsq_1 = least_squares(residuals, p0, args=(x, y_obs),
                     method='lm')
plsq_2 = leastsq(residuals, p0, args=(x, y_obs))

print("true params:", [A, k, theta])
print("estimate result by least_squares:", plsq_1.x)
print("estimate result by leastsq:", plsq_2[0])

plt.plot(x, y_truth, marker='+', label="True Value")
plt.plot(x, y_obs, marker='^', label="Observations")
plt.plot(x, func(x, plsq_1.x), label="least_squares")
plt.plot(x, func(x, plsq_2[0]), label="leastsq")
plt.legend()
plt.show()
```

### Error message

```shell
true params: [10, 0.34, 0.5235987755982988]
estimate result by least_squares: [-2.00987649  0.57026667 -7.46630253]
estimate result by leastsq: [-10.07434389   0.33737295  -2.70526658]
```

### SciPy/NumPy/Python version information

1.7.1 1.20.3 sys.version_info(major=3, minor=8, micro=11, releaselevel='final', serial=0)

**Comment by aserputov** [comment]
Hey, @WZG3661 
I want to work on this issue. Could you please assign me?

**Comment by andyfaff** [comment]
Feel free to investigate, there's no need to be assigned something to work on it.

**Comment by WZG3661** [comment]
I found that if x_scale set to 'jac', least_squares can get the correct result

**Comment by WZG3661** [comment]
when the method is 'lm', x_scale should be 'jac', otherwise, the result will be wrong

**Comment by rkern** [comment]
These settings are frequently problem- and parameterization-dependent. In nonlinear least-squares, there are few guarantees of convergence to the right answer. While the combination `method='lm', x_scale='jac'` worked well for you with this problem, it might not for others.

By the way, instead of parameterizing the sinusoid with a phase `theta`, consider using the `A*sin + B*cos` representation. I often find that is more amenable to optimization.
