### ISSUE TITLE
BUG: initial approximations to eigenvectors in svds should not be with all positive components

### ISSUE THREAD

**Issue by lobpcg** [scipy/scipy#15152]
### Describe your issue.

https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/_eigen/_svds.py at least in one place sets initial approximations to eigenvectors with all components random uniform on [0, 1]. This is a poor choice as common sense suggests that vectors with only positive components cover the positive quadrant only, not the whole vector space, are generally not so good to approximate eigenvectors. E.g., all example in the original MATLAB/Octave code, written for the paper, https://github.com/lobpcg/blopex/blob/master/blopex_tools/matlab/lobpcg/lobpcg.m use randn, e.g., line 97.
Poor initial approximations may make the solver running longer or even fail. 

The simplest solution is replacing all calls of uniform random with normal random. 

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

N/A

**Comment by rgommers** [comment]
Fixed for `lobpcg` in gh-15154, but I think there's more instances in other places that need fixing, right?

**Comment by lobpcg** [comment]
gh-15154 is very minor, since only changes the documentation and only in one file. The present issue is bigger, affecting the actual default initialization choices of lobpcg calls in  https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/_eigen/_svds.py, although still easy to fix. 
I would however wait for the more important and very long-awaiting https://github.com/scipy/scipy/pull/11829 to merge first before making a PR for this issue.

**Comment by rgommers** [comment]
Apologies, done.

**Comment by lobpcg** [comment]
@rgommers I am concerned if the important and very long-awaiting #11829 gets stalled again - maybe you could review it while it is all green?
