### ISSUE TITLE
Standard Error vs. Standard Deviation in Bootstrap

### ISSUE THREAD

**Issue by VSteinborn** [scipy/scipy#15160]
https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/stats/_bootstrap.py#L196-L461

Hello, 

I came across a line of code, which I think may be written in error.
Bootstrap claims to calculate the standard error, however on line 461 numpy.std() is called, which calculates the standard deviation instead. (https://numpy.org/doc/stable/reference/generated/numpy.std.html)

I am not sure what the origional intention was, but I just wanted to point this out in case it was written by accident.
Best regards

**Comment by mdhaber** [comment]
From Effron's "Introduction to the Bootstrap" pg 47:
![image](https://user-images.githubusercontent.com/6570539/144770812-5b118ca4-4b08-42b2-8657-07b265f1d775.png)

The bootstrap estimate of the standard error is the sample standard deviation of the bootstrap distribution.

**Comment by BlaneG** [comment]
Yes, SE is just the std of the sample statistic. This is also noted in the docstring for the return value. I suggest closing this @mdhaber

**Comment by mdhaber** [comment]
Thanks all!
