### ISSUE TITLE
Bin-Packing using HiGHS with scipy--challenges!!

### ISSUE THREAD

**Issue by srinivascnu166** [scipy/scipy#15189]
**Problem statement:** 
For instance, we have ‘n’ different types of packages which can be utilized multiple times based on requirement. Each package has its own weight and cost. On the other hand, we have ‘m’ number of items that are to be packed into given packages in an optimal way.
Problem statement: For instance, we have ‘n’ different types of packages which can be utilized multiple times based on requirement. Each package has its own weight and cost. On the other hand, we have ‘m’ number of items that are to be packed into given packages in an optimal way. Optimal way means the total cost of packages used should be minimum. These packages are further placed in bin being an imaginary container.

Constraints:

An item can be placed only in one package.
A bin can accommodate only one package.
Sum of weights of all items in package should not be greater than weight of package.
I have been trying to solve this bin pack problem which has already been solved in **PYOMO** and **PYSCIPOPT** . The challenges I faced are designing the constraints and decision variables in a way that has to be given for scipy HiGHS solver. for n=7(bins) and m=34(items), Complexity is growing in designing the constraints. I have come up with 273 constraints and is growing. With PYOMO, declaring constraints and objective function is easier than in **SCIPY**.

Can anyone tell me I am doing the right way or guide me on how to model the constraints in scipy.

**Comment by ilayn** [comment]
Hi @srinivascnu166 thanks for reaching out. Unfortunately we are only considering features and bugs of the code itself and not the problems solved with the code due to our limited capacity. 

This is a perfect question for https://scicomp.stackexchange.com/ and if you want a broader programming audience https://stackoverflow.com/ or Scipy user mailing list.

**Comment by mdhaber** [comment]
I agree that stackexchange/stackoverflow are the places to go for help setting this up. I wanted to mention that to solve the problem, it sounds like you could use (binary) integer constraints, which `linprog` can't do yet. However, we're working on wrapping those features of HiGHS, and we expect to add them to SciPy in 1.9.0.
