### ISSUE TITLE
Fix use of `pytest.warns(None)` for pytest 7.0.0

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#15186]
We currently use the context manager `pytest.warns` with the argument None in three places:
```
$ rg "pytest\.warns\(None"
scipy/sparse/csgraph/tests/test_shortest_path.py
315:    with pytest.warns(None) as record:

scipy/fft/tests/test_fftlog.py
111:    with pytest.warns(None) as record:
117:    with pytest.warns(None) as record:

<occurrence in sphinxext/numpydoc omitted>
```
With pytest 7.0.0, those calls result in a DeprecationWarning.  This can be seen in the CI results of recent PRs in the **scipy.scipy (Main prerelease_deps_coverage_64bit_blas)** check, where the test summary reports
```
FAILED scipy/fft/tests/test_fftlog.py::test_fht_special_cases - pytest.Pytest...
FAILED scipy/sparse/csgraph/tests/test_shortest_path.py::test_NaN_warnings - ...
```
<details><summary>Details from the log of a recent PR</summary>

```
=================================== FAILURES ===================================
____________________________ test_fht_special_cases ____________________________
[gw0] linux -- Python 3.8.12 /opt/hostedtoolcache/Python/3.8.12/x64/bin/python
scipy/fft/tests/test_fftlog.py:111: in test_fht_special_cases
        firstresult = True
        hook_name  = 'pytest_pyfunc_call'
        kwargs     = {'pyfuncitem': <Function test_fht_special_cases>}
        methods    = [<HookImpl plugin_name='python', plugin=<module '_pytest.python' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/_pytest/python.py'>>]
        self       = <_pytest.config.PytestPluginManager object at 0x7f3ce52608b0>
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/_pytest/python.py:192: in pytest_pyfunc_call
    result = testfunction(**testargs)
        funcargs   = {'check_fpu_mode': None, 'request': <FixtureRequest for <Function test_fht_special_cases>>}
        pyfuncitem = <Function test_fht_special_cases>
        testargs   = {}
        testfunction = <function test_fht_special_cases at 0x7f3cc94715e0>
scipy/fft/tests/test_fftlog.py:111: in test_fht_special_cases
    with pytest.warns(None) as record:
        a          = array([-1.12884913e+00,  4.18400908e-01, -1.41696768e+00,  1.48817091e+00,
       -1.77498877e+00,  2.36438510e+00, -6...4215e-02,  7.61753132e-01,  1.64643447e-01,
       -7.13788349e-01, -2.35421899e+00,  2.78841166e-03,  1.38421631e+00])
        bias       = 1.0
        dln        = -0.055849123963318315
        mu         = -4.0
        rng        = RandomState(MT19937) at 0x7F3CA97BB540
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/_pytest/recwarn.py:246: in __init__
    warnings.warn(WARNS_NONE_ARG, stacklevel=4)
E   pytest.PytestRemovedIn8Warning: Passing None to catch any warning has been deprecated, pass no arguments instead:
E    Replace pytest.warns(None) by simply pytest.warns().
        __class__  = <class '_pytest.recwarn.WarningsChecker'>
        _ispytest  = True
        expected_warning = None
        match_expr = None
        msg        = 'exceptions must be derived from Warning, not %s'
        self       = WarningsChecker(record=True)
```

</details>

The essential message in the log is
```
E   pytest.PytestRemovedIn8Warning: Passing None to catch any warning has been deprecated, pass no arguments instead:
E    Replace pytest.warns(None) by simply pytest.warns().
```
The current uses of `pytest.warns(None)` need to be updated to avoid this deprecation warning.

For the tests in `test_fftlog.py`,
https://github.com/scipy/scipy/blob/d634f179a008fe1d8448a0c84842821a85c8f38a/scipy/fft/tests/test_fftlog.py#L109-L119

 it looks like the test checks that no warnings are raised by the function call.  For that case, I think we can simply remove the context manager, because we configure pytest to convert most unexpected warnings to errors (ping @ntessore, @larsoner).

It looks like the test in `test_shortest_path.py`,
https://github.com/scipy/scipy/blob/d634f179a008fe1d8448a0c84842821a85c8f38a/scipy/sparse/csgraph/tests/test_shortest_path.py#L314-L318
 is supposed to catch all the warnings in the call of `shortest_path`, and then check that none of them are `RuntimeWarnings`.  Maybe we can also remove this use of `pytest.warns(None)`, and let any warning be reported as an error?

**Comment by ntessore** [comment]
The explicit check for no warning in test_fftlog.py is to give a more meaningful message if the test fails (the FHT thought the transform is ill-defined when it wasn't). I find that easier to understand than getting an error that the transform is singular, where someone might look for a mistake in the input of the call. If I understand the deprecation warning correctly, it might be enough to remove the `None` argument to keep the current behaviour?

**Comment by WarrenWeckesser** [comment]
@ntessore, it turns out that `pytest.warns()` in 7.0.0rc1 is not the same as `pytest.warns(None)` in 6.2.5.  In 7.0.0rc1, `pytest.warns()` is the same as `pytest.warns(Warning)`.

Here's a trivial example using 6.2.5:
```
In [1]: import pytest

In [2]: pytest.__version__
Out[2]: '6.2.5'

In [3]: with pytest.warns(None):
   ...:     pass
   ...: 

In [4]:
```
Here's the same example with 7.0.0rc1
```
In [1]: import pytest

In [2]: pytest.__version__
Out[2]: '7.0.0rc1'

In [3]: with pytest.warns() as record:
   ...:     pass
   ...: 
---------------------------------------------------------------------------
Failed                                    Traceback (most recent call last)
<ipython-input-3-7fdcccb2d75a> in <module>
      1 with pytest.warns() as record:
----> 2     pass
      3 

    [... skipping hidden 1 frame]

~/mc39pip/lib/python3.9/site-packages/_pytest/outcomes.py in fail(reason, pytrace, msg)
    194     __tracebackhide__ = True
    195     reason = _resolve_msg_to_reason("fail", reason, msg)
--> 196     raise Failed(msg=reason, pytrace=pytrace)
    197 
    198 

Failed: DID NOT WARN. No warnings of type (<class 'Warning'>,) were emitted. The list of emitted warnings is: [].

In [4]: 
```

**Comment by WarrenWeckesser** [comment]
Based on the pytest issue [Improve pytest.warns() docs to clarify difference with catch_warnings()](https://github.com/pytest-dev/pytest/issues/9002), it looks like `pytest.warns` is designed to assert the occurrence of a specific warning, and it isn't suitable for checking that no warnings occur.  The comments in that issue suggest using `warnings.catch_warnings()` instead of `pytest`.

**Comment by rgommers** [comment]
> The explicit check for no warning in test_fftlog.py is to give a more meaningful message if the test fails

I'm not sure I understand this. In `master`, any warning gets turned into a test error immediately, hence checking for no warnings should not be necessary or useful.

**Comment by ntessore** [comment]
> > The explicit check for no warning in test_fftlog.py is to give a more meaningful message if the test fails
> 
> I'm not sure I understand this. In `master`, any warning gets turned into a test error immediately, hence checking for no warnings should not be necessary or useful.

If the test fails, it will fail with a warning message that says you are attempting a singular transform, meaning there’s something wrong with the input data. I wanted to assure the person seeing that message that the algorithm is mistaken, and that the transform is well-defined. In other words, the failure is that the algorithm thinks the transform is singular when it’s not, not that the transform is singular as the warning would say.
