### ISSUE TITLE
BUG: Error occured `spsolve_triangular`

### ISSUE THREAD

**Issue by j7168908jx** [scipy/scipy#15199]
### Describe your issue.

Errors might occur when using `scipy.sparse.linalg.spsolve_triangular` with `unit_diagonal=true`.

As the doc said 
```
    unit_diagonal : bool, optional
        If True, diagonal elements of `a` are assumed to be 1 and will not be
        referenced.
```

It should be fine if I pass a strict lower-triangular sparse matrix to it (such as `L` in any LU decomposition) while error occurs in this case.

---

Analysis:

This is caused by row 606, row 617 in `scipy/sparse/linalg/_dsolve/linsolve.py` as the `indptr` will be `[0, 0, ...]` and `A_diagonal_index_row_i = -1` (in the first iteration), causing the indexing in row 617 behaves wrongly. The error then outputs `A[0, {n-2}]` is nonzero. (`n` is the size of matrix)

The problem is gone after I forcibly set the diagonal to have any nonzero elements.

### Reproducing Code Example

```python
from scipy.sparse.linalg import spsolve_triangular
import scipy.sparse as sp
import numpy as np
l = np.array([
[0, 0, 0],
[1, 0, 0],
[1, 1, 0]], dtype=np.float64)
b = np.array([1.,2.,3.])

spsolve_triangular(l, b, unit_diagonal=True)
```

### Error message

```shell
numpy.linalg.LinAlgError: A is not triangular: A[0, 1] is nonzero.
```

### SciPy/NumPy/Python version information

1.4.1 1.19.5 sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment]
@j7168908jx, thanks for reporting the problem.

@j7168908jx reported the error with scipy version 1.4.1, but the error still exists in the master branch (i.e. version `1.9.0.dev0+1057.202d03c`).

**Comment by v0dro** [comment]
I have confirmed that this fails on macOS.

I can take up this issue. Please assign me to it.

**Comment by mdhaber** [comment]
In general, there's no need for assignments - just feel free to submit a PR. Thanks!
