### ISSUE TITLE
BUG: Can not find Maximum value

### ISSUE THREAD

**Issue by Shinichi52** [scipy/scipy#15198]
### Describe your issue.

I've a problem when find a maximum value using below formula:

Objective:
TotalG = Sum(G1+G2+...+Gn)

ColD (Max Value): D1, D2,..., Dn
ColE (Min Value): E1, E2,..., En

Constraints:
E1 =< G1 <= D1
E2 =< G2 <= D2
...
En =< Gn <= Dn

1.96* Sum((G1/totalG)^2 + (G2/totalG)^2 + ... + (Gn/totalG)^2) * totalG <= 23000000000

I try to run the solver function on Excel it will sugget total value maximum. However, i recieved a very small value when i used the scipy. Please use this file to run my example code

[solver.xlsx](https://github.com/scipy/scipy/files/7696745/solver.xlsx)

### Reproducing Code Example

```python
import numpy as np
from scipy.optimize import minimize, NonlinearConstraint

import cvxpy as cp
import numpy as np
import pandas as pd
from pulp import *
# import cvxopt
# import mosek
from helper import convert_excel
import pandas as pd

print(cp.installed_solvers())

pathFile = 'testdata/solver.xlsx'
dataFromExcel = convert_excel.handleDataFromExcel(pathFile, '', "ABC")
divNum = 1
dicData = {}
lengthData = 0
listName = []
for iData in dataFromExcel["data"]:
    if iData["Historical EADi Min"] is None or iData["Historical EADi Max"] is None:
        continue
    else:
        listName.append(str(iData["Customer ID"]))
    # if lengthData > 2: continue
    lengthData+=1
    for key in iData:
        vData = iData[key]
        if key != 'Historical EADi Min' and key != 'Historical EADi Max':
            continue
        if key in dicData:
            listData = dicData[key]
        else:
            listData = []
        if vData is not None:
            listData.append(vData / divNum)
        dicData[key] = listData

K4 = 23000000000 / divNum

colE = np.array(dicData['Historical EADi Min']) # G > E
colD = np.array(dicData['Historical EADi Max']) # G < D



def objective(x):
    sumG =  sum(x)
    temp = sumG * -1
    return temp

bnds = ()
for i in range(lengthData):
    exx = colE[i]
    dxx = colD[i]
    bnds += ((exx, dxx),)

def checkTotal(x):
    try:
        sumSquare = 0
        sumG = sum(x)
        listSquare = []
        for xi in x:
            div = xi / sumG  if sumG > 0 else 0
            square = pow(div, 2)
            listSquare.append(square)
        sumSquare = sum(listSquare)
        # 1.96 * sumJ * sumG <= K4
        afterMinus = K4 - sumSquare * 1.96 * sumG
        return afterMinus
    except Exception as e:
        print(e)
        return 0

def checkX(x):
    totalCheck = 0
    for xi in x:
        totalCheck += xi % 1
    return totalCheck
    # =1.96*SUM(J2:J51)*SUM(G2:G51) <= K4
    # J = (G/sumG)^2
    

    # return sum(x) - 30094995354
    #  30094995353


# con0 = lambda x: x[1] - x[0]

# nlc = NonlinearConstraint(con0, -np.inf, 2)
x0 = np.zeros(lengthData)
con1 = {'type': 'ineq', 'fun': checkTotal}
con2 = {'type': 'eq', 'fun': checkX}
cons = [con2, con1]
sol = minimize(objective, x0, method='SLSQP', bounds = bnds, constraints = cons)

print('SUM: ', sum(sol.x))

df = pd.DataFrame({'colG': sol.x, 'colD': colD, 'colE': colE})
df.to_excel(excel_writer = "test.xlsx")
print("END")
```

### Error message

```shell
No message
```

### SciPy/NumPy/Python version information

1.7.3

**Comment by mdhaber** [comment]
Please let me know if one of the following is incorrect:

- You are trying to maximize a function using SciPy's `minimum` function. 
- You are doing this by multiplying the objective function by negative one because minimizing the negative of a function is equivalent to maximizing the original function.
- You expect the optimal value of the objective function reported by `minimize` to be a large _magnitude_ negative number, but its magnitude is much smaller than expected.

Is that correct?

If so, before we are able to determine whether there is a bug in SciPy or not, you need to check Excel's solution. When you use Excel's optimal solution as the input for the function in Python, does the objective function match what Excel is reporting? Are all the constraints satisfied? If you start with this as the "guess" `x0` for `minimize`, now what does `minimize` report as the optimal value of the objective function?

**Comment by Shinichi52** [comment]
Thanks @mdhaber  for your response.

You've understood correctly. 
The objective function matched and all the the constraints are satisfied.
if i run excel solver with target is minimize, the result that excel sugget is equal with scipy

**Comment by mdhaber** [comment]
Does `minimize` report success? That is, what is `sol.success` and `sol.message`?

Does this code solve your problem as you would expect?
<details>

```python3
import numpy as np
from scipy.optimize import minimize, Bounds, NonlinearConstraint

l = np.array([7694282826,  5616800891,  3507130200,  8111395500,  8653238820,
              8856102168,  3857372953,   115912250, 11857652858,    32836804,
              16566722225,  1535465739,    70362220,  2407774000,   191238077,
              131835244,  2316540000,  3830019130,   364302034,  4650167124,
              70160000,  3901898742,   971474755,  4632670000,  2318248000,
              1167450000,  4709160000,  2528775143,    29374313,  2070775952,
              129928302,    41686436,   346457558,   965218788,   255313435,
              695230848,    59294931,   243826508,  2261740107,    27262368,
              156541547,   126955198,    18804498,    33369863,    29165310,
              3113539470,   126266269,  1067830710,    55134693,   140179820])

u = np.array([15070139175, 15024856178, 10778738041, 26605247500, 22279329410,
              51339126741, 18255099817, 10186671774, 53383844307,    34065395,
              42875837784, 16689345509,   258385211,  9888514404,   668492763,
              24994171600,  5894362075, 19759710857,  9897262480, 22374542089,
              1764237000,  5651367290,  4811098173,  5057550287,  9489318254,
              1167450000, 11719803000,  2528775143,    29374313,  3279631125,
              4500564647,    72299547,   361882641,  1208315464,   765610278,
              2791487530,   133157163,   873235646,  3224794549,    27262368,
              200445234,   126955198,    21678780,    51221365,    45900892,
              3113539470,   126266269,  1067830710,    55134693,   140179820])

def obj(x):
    return -np.sum(x)

def cfun(x):
    total = np.sum(x)
    return 1.96*np.sum((x/total)**2)*total

x0 = 2*l
bounds = Bounds(l, u)
con = NonlinearConstraint(cfun, 0, 23000000000)
options = {'maxiter': 1000}
res = minimize(obj, x0, bounds=bounds, constraints=(con,),
               method='slsqp', options=options)


assert(res.success)
assert(cfun(res.x) <= 23000000000)
assert(np.all(l <= res.x))
assert(np.all(res.x <= u))
```

</details>

I'm getting an optimal value of the objective function `-219353680666.90967`.

**Comment by mdhaber** [comment]
I think I can reproduce what you're saying: 
> if i run excel solver with target is minimize, the result that excel sugget is equal with scipy

When this occurs, all the decision variables (`res.x`) are equal to their lower bounds, right?

What I think is happening is that your constraint `checkX` is causing the solver to get stuck in a local minimum with all decision variables equal to their lower bounds. 

I don't think there is a "bug" here. We can wish that SciPy's optimizers could find the global optimum of any problem from any arbitrary initial guess, but that's not the state of the art. Here, the `checkX` constraint makes the problem very challenging, and it seems to trap the (gradient-based) solver in a local optimum - the lower bound of each decision variable. Had the initial guess been something else, the solver would probably fail. That's not really the optimizer's fault. If you need an integer solution, you need a specialized technique, or in this case it may be good enough to round the results of the relaxed problem (i.e. without the `checkX` integer constraint).

**Comment by Shinichi52** [comment]
Thanks @mdhaber. Let me check my formula fisrt, I will get back to you if i have any update
