### ISSUE TITLE
Documentation issue with minimize finite_diff_rel_step  

### ISSUE THREAD

**Issue by bertrandhaut** [scipy/scipy#15208]
### Describe your issue.

Some methods of the minimization function are accepting the finite_diff_rel_step  option. See for example https://docs.scipy.org/doc/scipy/reference/optimize.minimize-tnc.html#optimize-minimize-tnc .

This option is documented as 
```The absolute step size is computed as h = rel_step * sign(x0) * max(1, abs(x0)), possibly adjusted to fit into the bounds.```
This sentence is a copy/paste from the approx_derivative in _numdiff.py.

Unfortunately the name "x0" is also used for an argument in minimize and has not the same meaning. By reading the documentation of optimize-minimize-tnc we can think that "x0" is a constant (the starting point of the optimization) leading to constant "h". In practice this "h" will vary with each iteration.

Suggestion: simply change the documentation to 
```The absolute step size is computed as h = rel_step * sign(x) * max(1, abs(x)), possibly adjusted to fit into the bounds.```

### Reproducing Code Example

```python
no code, only doc issue
```

### Error message

```shell
no error message, only doc issue
```

### SciPy/NumPy/Python version information

1.6.2 1.20.2 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by AtsushiSakai** [comment]
I agree the `x0` of `optimize.minimise` is
https://github.com/scipy/scipy/blob/2fc2458c2f46dd59d9900d500a8dddd5066a4d71/scipy/optimize/_minimize.py#L60-L62
But `x0` of `approx_derivative` is
https://github.com/scipy/scipy/blob/3b0cf8649e9414556dd44f11e37acb6e9f2cffcd/scipy/optimize/_numdiff.py#L291-L293
These are different meanings. We can improve the doc.
