### ISSUE TITLE
BUG: Minor issue with suggestions in scipy.sparse DeprecationWarnings for 1.8rc1

### ISSUE THREAD

**Issue by rossbar** [scipy/scipy#15206]
### Describe your issue.

A very minor issue with the DeprecationWarning message suggesting an incorrect access pattern for submodules within deprecated subpackage names. For example:

```python
>>> import scipy.sparse.linalg as spla
>>> spla.eigen.arpack.ArpackNoConvergence
DeprecationWarning: Please use `arpack` from the `scipy.sparse.linalg` namespace, the `scipy.sparse.linalg.eigen` namespace is deprecated.
scipy.sparse.linalg._eigen.arpack.arpack.ArpackNoConvergence
```

The problem here is the DeprecationWarning message suggests accessing `arpack` from the `scipy.sparse.linalg`, but `arpack` is not available in the `scipy.sparse.linalg` namespace. Instead the warning should tell the user to access the `ArpackNoConvergence` object itself from scipy.sparse.linalg.

### Reproducing Code Example

```python
See above
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

1.8.0rc1 1.22.0rc2 sys.version_info(major=3, minor=9, micro=9, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment]
The same problem exists for `scipy.sparse.linalg.dsolve.linsolve`.  For example, in the following, the deprecation message says "use `linsolve` from the `scipy.sparse.linalg` namespace", but `linsolve` is not in the `scipy.sparse.linalg` namespace:
```
In [3]: spla.dsolve.linsolve.factorized
<ipython-input-3-015a515a0257>:1: DeprecationWarning: Please use `linsolve` from the `scipy.sparse.linalg` namespace, the `scipy.sparse.linalg.dsolve` namespace is deprecated.
  spla.dsolve.linsolve.factorized
Out[3]: <function scipy.sparse.linalg._dsolve.linsolve.factorized(A)>
```
A proposed fix for the deprecation messages is in https://github.com/scipy/scipy/pull/15220
