### ISSUE TITLE
Question about:  sklearn.linear_model.least_angle.py : (solve_cholesky,) = get_lapack_funcs(("potrs",), (L,))

### ISSUE THREAD

**Issue by wingdi** [scipy/scipy#15218]
According :
http://www.netlib.org/lapack/explore-html/d1/d7a/group__double_p_ocomputational_ga167aa0166c4ce726385f65e4ab05e7c1.html, 
ports function should return a triangle matrix. 
this is the invoke code from scripy:
```
(solve_cholesky,) = get_lapack_funcs(("potrs",), (L,)) 
least_squares, _ = solve_cholesky(
            L[:used_feature_num, :used_feature_num], used_covs_sign[:used_feature_num], lower=True,
        )
```
This is my input data：
```
L = 
[[ 7.1271454e+02  2.00000000e+00  4.84877646e-01  4.65774752e-10
  -1.64716327e+25  4.58322689e-41 -1.63117733e+25  4.58322689e-41]
 [-1.62107589e+25  4.58322689e-41 -3.88354876e+25  4.58322689e-41
  -1.61568944e+25  4.58322689e-41 -1.61552711e+25  4.58322689e-41]
 [-1.62095045e+25  4.58322689e-41 -1.61648634e+25  4.58322689e-41
  -1.61595507e+25  4.58322689e-41 -1.94947553e+27  4.58322689e-41]
 [-6.09281937e+25  4.58322689e-41 -6.11434634e+28  4.58322689e-41
  -4.32277872e+28  4.58322689e-41 -1.58450706e+25  4.58322689e-41]
 [-2.36398597e+27  4.58322689e-41 -1.61652323e+25  4.58322689e-41
  -1.79887299e+25  4.58322689e-41 -1.61084348e+25  4.58322689e-41]
 [-1.21184991e+29  4.58322689e-41 -1.90019726e+25  4.58322689e-41
  -1.22427162e+29  4.58322689e-41 -1.22428976e+29  4.58322689e-41]
 [-3.91232479e+27  4.58322689e-41 -6.14369301e+28  4.58322689e-41
  -9.20305358e+28  4.58322689e-41 -1.59492578e+25  4.58322689e-41]
 [-1.75826801e+25  4.58322689e-41 -1.22522365e+29  4.58322689e-41
  -1.22436834e+29  4.58322689e-41 -1.61591818e+25  1.51520021e-39]]

L[:used_feature_num, :used_feature_num] = [[ 7.1271454e+02]]

used_covs_sign[:used_feature_num] = [1]
```
this is the least_square i finally get :
```
[1.968651e-06]
```
I just don't know how to get the final least_square . because according 
, 
ports function should return a triangle matrix.  

I need to implement this code without fortran. so i need to know how to calculate least_square.  
and the fortran code from 
http://www.netlib.org/lapack/explorehtml/d1/d7a/group__double_p_ocomputational_ga167aa0166c4ce726385f65e4ab05e7c1.html
using three file and the implementation is a little complex, 
So anyone know materials or python code about potrs function ?

**Comment by ilayn** [comment]
Hi @wingdi You are providing a scalar since you probably have `used_feature_num==1` . Hence you are essentially solving ` (7.1271454e+02 ** 2) * x = 1` which is as you got `x = 1.968651e-06` . So there is no problem in the code. Moreover, SciPy actually provides ways to use the Fortran code and does not provide a python only code for such functions.

However unfortunately we cannot provide usage support due to our limited capacity so I'll close this but feel free to continue the discussion if there is a code-related bug or feature.

**Comment by wingdi** [comment]
@ilayn  Ok,  very thanks for your quick reply .

**Comment by wingdi** [comment]
@ilayn  Ok,  very thanks for your quick reply .
