### ISSUE TITLE
BUG: exponnorm loc and scale

### ISSUE THREAD

**Issue by ryanhammonds** [scipy/scipy#15222]
### Describe your issue.

When passing loc and scale to the `rvs` method of `scipy.stats.exponnorm`, the `loc` (mean) and `scale` (std) are seemingly incorrect. In the code block, I expect a mean of 100 and std of 10. Instead, the method returns a mean of ~300 and a std of ~200. The second to last line in the block is a proposed solution. That line would need to overwrite [this line](https://github.com/scipy/scipy/blob/1474e4c4f7a934d2390fbc259def0ba2cc3526a1/scipy/stats/_distn_infrastructure.py#L1095) somehow. If this is an actual bug, a not a user error / misunderstanding, I'm happy to help out with a PR. 

### Reproducing Code Example

```python
import numpy as np
from scipy.stats import exponnorm

np.random.seed(0)

k = 20
scale = 10
loc = 100
size = 1000

dist = exponnorm.rvs(k, scale=scale, loc=loc, size=size)
print(dist.mean(), dist.std()) # 300.998483580713 206.20465132435544

# Expected
dist = exponnorm.rvs(20, scale=1, loc=0, size=size)
dist = (dist * scale / k) + (loc - scale) # updated normalization
print(dist.mean(), dist.std()) # 100.18909444278653 10.530253212009073
```

### Error message

```shell
No error, this is an accuracy bug.
```

### SciPy/NumPy/Python version information

`1.7.3 1.21.4 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)`

**Comment by WarrenWeckesser** [comment]
> When passing loc and scale to the rvs method of scipy.stats.exponnorm, the `loc` (mean) and `scale` (std) are seemingly incorrect. 

In general, `loc` and `scale` are *not* the mean and standard deviation of a probability distribution.  To get, for example, the mean of `exponnorm` with your parameters, you can call the `mean()` method:

```
In [9]: exponnorm.mean(k, loc=loc, scale=scale)
Out[9]: 300.0
```
In fact, the mean is 300.

**Comment by ryanhammonds** [comment]
Thanks for the explanation. I read in the docs that `loc` and `scale` were the mean and std for normal distributions, and thought this extended to other distributions, but it does not. It's still a black box to me what the `loc` and `scale` parameters control in other distributions but I'll have to dig deeper. Thanks again!
