### ISSUE TITLE
BUG: L-BFGS-B non fortran contiguous error

### ISSUE THREAD

**Issue by jschiavon** [scipy/scipy#15237]
### Describe your issue.

Hi,

I am using [jax](https://github.com/google/jax) (0.2.26, jaxlib v 0.1.75) to write a function to be optimized for the mle, but I have a problem with scipy minimizer. 

The function itself is a R^n -> R function written in jax-jit compatible format. The function itself is pretty simple and convex, and indeed the optimization is quite simple.

Unfortunately, for my project I need to use the `L-BFGS-B` method, as I have to compare it with other implementations, but when called it raises the exception `ValueError: failed to initialize intent(inout) array -- input not fortran contiguous`. Note that both the x and the gradient have the correct (n,) shape.

The fun thing is that the exact same code does not give any problem if I use the `BFGS` method of scipy optimize.

At the moment I can't provide a reproducible code, I will do it as soon as I get back home tonight.

### Reproducing Code Example

```python
from numpy.random import default_rng
import jax.numpy as jnp
import jax
from jax.config import config
config.update('jax_enable_x64', True)   # This way jax uses 64-bit float instead of the default 32

from scipy.optimize import minimize

# Data generation
rng = default_rng(42)
p = 5; n = 1000
mean = rng.normal(size=p); cov = rng.normal(size=(p, p)); cov = cov @ cov.T
print(mean.shape)    # (p,)
print(cov.shape)        # (p, p)

y = rng.multivariate_normal(mean, cov, size=(n))
y = jnp.concatenate([y.T, jnp.ones(shape=(1, n))], axis=0)
print(y.shape)           # (p+1, n)

# Function and gradient definition, this is the logpdf of a p+1 mvn with 0 mean
@jax.jit
def nloglik(x):
     mat = jnp.zeros(shape=(p+1, p+1)).at[jnp.tril_indices(p+1)].set(x)
     mat = jnp.matmul(mat, mat.T)
     maha = jnp.trace(jnp.linalg.solve(mat, jnp.matmul(y, y.T)))
     return 0.5 * (n * jnp.linalg.slogdet(mat)[1] + maha)

grad = jax.jit(jax.grad(nloglik))

# Starting point
init = jnp.linalg.cholesky(jnp.identity(p+1))[jnp.tril_indices(p+1)]
print(init.shape)                  # ((p+1) * (p+2) / 2, ) 
starting_fun = nloglik(init) # To trigger jit
starting_grad = grad(init) # To trigger jit
print(starting_fun.shape)     # ()
print(starting_grad.shape)    # ((p+1) * (p+2) / 2, )

minimize(nloglik, init, jac=grad, method='l-bfgs-b')
# This throws the error shown below while
minimize(nloglik, init, jac=grad, method='bfgs')
# This works perfectly fine
```

### Error message

```shell
Traceback (most recent call last):
  File "small_test.py", line 215, in <module>
    'iprint':50,
  File "/home/jschiavon/.pyenv/versions/optispd/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 624, in minimize
    callback=callback, **options)
  File "/home/jschiavon/.pyenv/versions/optispd/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py", line 353, in _minimize_lbfgsb
    isave, dsave, maxls)
ValueError: failed to initialize intent(inout) array -- input not fortran contiguous
```

### SciPy/NumPy/Python version information

1.7.3 1.21.4 sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)

**Comment by IvanYashchuk** [comment]
`L-BFGS-B` expects regular NumPy arrays as outputs for `nloglik` and `grad` functions, internally JAX arrays are converted to NumPy arrays. Here, the output of `grad` function can't be used without an explicit copy.
Using `minimize(nloglik, init, jac=lambda x: numpy.array(grad(x)), method='l-bfgs-b')` would fix the problem.

**Comment by jschiavon** [comment]
Thank you, I solved it a while ago with the same workaround.

Still, I would add a couple of lines in the docs to specify that the "L-BFGS-B" has stronger requirements for the outputs of the function.
