### ISSUE TITLE
DOC: scipy.special.binom could use a more thorough docstring

### ISSUE THREAD

**Issue by steppi** [scipy/scipy#15247]
The ufunc `scipy.special.binom` based on a cython function in [scipy/stats/orthogonal_eval.pxd](https://github.com/scipy/scipy/blob/master/scipy/special/orthogonal_eval.pxd#L68) offers an implementation of the binomial coefficient considered as a function of two real arguments. The [docstring](https://github.com/scipy/scipy/blob/e569c7a2d8d53a976b94a0cd984db469f7572a4f/scipy/special/_add_newdocs.py#L699-L709) for this function is extremely spare and offers no indication to the user what types of arguments are accepted or what sets `scipy.special.binom` apart from `scipy.special.comb`.

I think this has lead to some confusion. See for instance gh-15213, where @HexCodeFFF pointed out that `scipy.special.binom` differs from a convention that is usually used when the binomial coefficient is considered as a function of two integers. HexCodeFFF even submitted a PR gh-15216 attempting to align `scipy.special.binom` with this convention. The convention is over how to define x choose y when x is a negative integer and y an integer. I left a [comment](https://github.com/scipy/scipy/issues/15213#issuecomment-996811141) in the aforementioned issue giving my thoughts on the matter. 

I personally think the function does not need to be changed but could benefit from a thorough docstring that clarifies how it is defined for two real arguments and explaining somewhere why it differs from the expected convention for integer arguments. I would be happy to write the docstring and should have time over the holidays.

**Comment by HexCodeFFF** [comment]
If binom isn't changed to accommodate for negative integers, could a new function be created that does? call it nCr (n choose r) maybe, fits in with statistics

**Comment by steppi** [comment]
> If binom isn't changed to accommodate for negative integers, could a new function be created that does? call it nCr (n choose r) maybe, fits in with statistics

Possibly, although it would complicate things from an API perspective to have three separate functions for binomial coefficients. 
I think it would be preferable to modify `scipy.stats.binom` honestly. Potential new features are discussed and decided on the [SciPy Developers Mailing List](https://scipy.org/mailing-lists/). See the section **Deciding on New Features** in the [SciPy Core Developer Guide](https://docs.scipy.org/doc/scipy/reference/dev/core-dev/index.html). Note that maintainer time is scarce and therefore the decision to add new features is not made lightly.

In the meantime, I suggest trying out [mpmath's binomial coefficient implementation](https://mpmath.org/doc/current/functions/gamma.html#binomial), which does have the behavior you expect and may be suitable for your purposes.

**Comment by AtsushiSakai** [comment]
I’m +1. I think enhancing the doc based on current behavior is a great first step. Then we should discuss how can we enhance the functionality.
