### ISSUE TITLE
BUG: Docs (or implementation) for negative inputs to factorial2 are incorrect

### ISSUE THREAD

**Issue by TyBalduf** [scipy/scipy#15246]
### Describe your issue.

The docstring for [factorial2](https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/special/_basic.py#L2399-L2453) says:
>If ``n < 0``, the return value is 0.

However directly below that in the code, we can see this is not the case for `n==-1`

```
if exact:
    if n < -1:
        return 0
    if n <= 0:
        return 1
```
This will give a value of 1 for `factorial2(-1)` (if `exact` is false, it returns 1.0).

The code could be made consistent with the documentation (either making the result for n==-1 be 0 or saying that for n<-1, factorial2 is 0).

Alternatively, the code could be adapted to perform the [extended double factorial](https://en.m.wikipedia.org/wiki/Double_factorial#Negative_arguments) which allows for negative inputs.

### Reproducing Code Example

```python
scipy.special.factorial(-1)
```

### Error message

```shell
None
```

### SciPy/NumPy/Python version information

1.7.1 1.21.2 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by samO2I1** [comment]
Dear sir,
I would like to work on this issue.

**Comment by TyBalduf** [comment]
@samO2I1 I think if you submit a pull-request and connect it with this issue, they will be able to see if they want to use your version of the code or make any corrections to it before merging it.

**Comment by samO2I1** [comment]
Sure Sir

**Comment by samO2I1** [comment]
The result of n==-1 should be 1 as per [info](https://en.m.wikipedia.org/wiki/Double_factorial#Negative_arguments)  and the code when run 
```
if exact:
    if n < -1:
        return 0
    if n <= 0:
        return 1
```
gives 1 and 0 for all the values less than -1  which also satisfies the condition of factorial2 docstring.
So sir can you please explain the issue more clearly .
Thanks

**Comment by TyBalduf** [comment]
@samO2I1 The docstring says that for n>0, the result should be 0. So for n==-1 it's giving the "wrong" result at least according to the docstring. 

Factorial2 should either give 0 for all negative values or it should be extended to work for all negative values. I'm more partial to extending it (I happen to have some code that uses needs factorial2 (-1) to be 1).

**Comment by samO2I1** [comment]
Ok sir i will work on the code that can give exact answers to all the negative values i.e extending to work for all negative values.

**Comment by samO2I1** [comment]
I am not able to find the solution to the negative even integers whereas we have a formula for negative odd integers.
So should we give 0 for all negative even integers and normal solutions to negative odd integers according to the formula ?

**Comment by samO2I1** [comment]
@TyBalduf  I am not able to find the solution to the negative even integers whereas we have a formula for negative odd integers.
So should we give 0 for all negative even integers and normal solutions to negative odd integers according to the formula ?

**Comment by TyBalduf** [comment]
@samO2I1 the extension still leaves the value for negative even integers undefined, so it would make sense to leave these as zero and use the formula for negative odd integers.

**Comment by samO2I1** [comment]
@TyBalduf  then to make the result consistent should I make the solution 0 for all negative integers as the value for negative even integers is undefined.

**Comment by TyBalduf** [comment]
@samO2I1 some ideas for this are being discussed on an open pull request: https://github.com/scipy/scipy/pull/15299. One could choose to define these arbitrarily as zero or as mentioned in the pull request have them return a ValueError for these other inputs.

**Comment by samO2I1** [comment]
@TyBalduf learning from this pull request should I return the value as ValueError for all the **negative even** integers?

**Comment by AvinashDwivedi** [comment]
Hello sir, I would like to work on this issue.

**Comment by AvinashDwivedi** [comment]
_Hello is there someone who can guide me to solve this issue. I really want to do this_, **It will be my first contribution, Please guide me I'm a newbie**

**Comment by j-bowhay** [comment]
I think this can be closed gh-15592 changed the docstring to match the implementation and gh-15600 is discussing the current inconsistencies and any possible extensions.
