### ISSUE TITLE
DOC: Multivariate normal CDF docstring typo

### ISSUE THREAD

**Issue by timleathart** [scipy/scipy#15252]
I noticed that the docstring for the [multivariate normal `_cdf` function](https://github.com/scipy/scipy/blob/master/scipy/stats/_multivariate.py#L520) says 

```python
"""Log of the multivariate normal cumulative distribution function."""
```

However, I believe that this function is actually computing the standard, non-transformed CDF. 

Obviously this is extremely minor, but I thought it could be a good "first issue" for someone!

**Comment by tupui** [comment]
Thanks @timleathart. True, It should have the same docstrings as `cdf`.

**Comment by bobcatCA** [comment]
I'll take this on for a first issue - I use the library often and am looking to be more active fixing. Just will take me a minute to read over the PR process to make sure I'm doing it per the book

**Comment by tupui** [comment]
Thanks for your interest @bobcatCA!
