### ISSUE TITLE
BUG: problem with building scipy against system boost

### ISSUE THREAD

**Issue by kloczek** [scipy/scipy#15260]
### Describe your issue.

I'm using github autogenerated source tar ball from v1.7.3 tag
I'm trying to package `scipy module as an rpm package. So I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account. First step is to build module using `python3 -sBm build -w`.
Looks like

Prepared site.cfg files has:
```
[amd]
library_dirs = /usr/lib64
include_dirs = /usr/include/suitesparse
amd_libs = amd

[umfpack]
library_dirs = /usr/lib64
include_dirs = /usr/include/suitesparse
umfpack_libs = umfpack

[openblas]
libraries = flexiblas
library_dirs = /usr/lib64
```

Looks like wit those settings build by default is trying to use boost cloned as git submodule.

**Is any procedure to be able build scipy using ststem installed boost?**
Do I need to add something more to my site.cfg?

### Reproducing Code Example

```python
git clone -t v1.7.3 https://github.com/scipy/scipy/
cd scipy
python3 -sBm build -w
```

### Error message

```shell
Here is build output:

+ /usr/bin/python3 -sBm build -w
/usr/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (Cython>=0.29.18,<3.0, numpy; python_version=='3.10' and platform_python_implementation=='PyPy', numpy; python_version=='3.8' and platform_python_implementation=='PyPy', numpy; python_version=='3.9' and platform_python_implementation=='PyPy', numpy==1.16.5; python_version=='3.7' and platform_machine!='aarch64' and platform_python_implementation != 'PyPy', numpy==1.17.3; python_version=='3.8' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_python_implementation != 'PyPy', numpy==1.19.2; python_version=='3.7' and platform_machine=='aarch64', numpy==1.19.2; python_version=='3.8' and platform_machine=='aarch64', numpy==1.19.3; python_version=='3.9' and (platform_machine!='arm64' or platform_system!='Darwin') and platform_python_implementation != 'PyPy', numpy==1.20.0; python_version=='3.7' and platform_python_implementation=='PyPy', numpy==1.21.4; python_version=='3.10' and platform_python_implementation != 'PyPy', pybind11>=2.4.3,<2.8.0, pythran>=0.9.12,<0.10.0, setuptools<58.0.0, wheel<0.38.0)
* Getting dependencies for wheel...
running egg_info
creating scipy.egg-info
writing scipy.egg-info/PKG-INFO
writing dependency_links to scipy.egg-info/dependency_links.txt
writing requirements to scipy.egg-info/requires.txt
writing top-level names to scipy.egg-info/top_level.txt
writing manifest file 'scipy.egg-info/SOURCES.txt'
reading manifest file 'scipy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*_subr_*.f' found under directory 'scipy/linalg/src/id_dist/src'
no previously-included directories found matching 'benchmarks/env'
no previously-included directories found matching 'benchmarks/results'
no previously-included directories found matching 'benchmarks/html'
no previously-included directories found matching 'benchmarks/scipy'
no previously-included directories found matching 'doc/build'
no previously-included directories found matching 'doc/source/generated'
no previously-included directories found matching '*/__pycache__'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.bak' found anywhere in distribution
warning: no previously-included files matching '*.swp' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
adding license file 'LICENSE.txt'
adding license file 'LICENSES_bundled.txt'
writing manifest file 'scipy.egg-info/SOURCES.txt'
* Installing packages in isolated environment... (wheel)
* Building wheel...
Running from SciPy source directory.
Cythonizing sources
Running scipy/linalg/_generate_pyx.py
Running scipy/special/_generate_pyx.py
Running scipy/stats/_generate_pyx.py
Processing scipy/_lib/_ccallback_c.pyx
Processing scipy/_lib/_test_deprecation_call.pyx
Processing scipy/_lib/_test_deprecation_def.pyx
Processing scipy/_lib/messagestream.pyx
Processing scipy/cluster/_hierarchy.pyx
Processing scipy/cluster/_optimal_leaf_ordering.pyx
Processing scipy/cluster/_vq.pyx
Processing scipy/fftpack/convolve.pyx
Processing scipy/interpolate/_bspl.pyx
Processing scipy/interpolate/_ppoly.pyx
Processing scipy/interpolate/interpnd.pyx
Processing scipy/io/matlab/mio5_utils.pyx
Processing scipy/io/matlab/mio_utils.pyx
Processing scipy/io/matlab/streams.pyx
Processing scipy/linalg/_decomp_update.pyx.in
Processing scipy/linalg/_matfuncs_sqrtm_triu.pyx
Processing scipy/linalg/_solve_toeplitz.pyx
Processing scipy/linalg/cython_blas.pyx
Processing scipy/linalg/cython_lapack.pyx
Processing scipy/ndimage/src/_cytest.pyx
Processing scipy/ndimage/src/_ni_label.pyx
Processing scipy/optimize/_bglu_dense.pyx
Processing scipy/optimize/_group_columns.pyx
Processing scipy/optimize/_highs/cython/src/_highs_constants.pyx
Processing scipy/optimize/_highs/cython/src/_highs_wrapper.pyx
Processing scipy/optimize/_lsq/givens_elimination.pyx
Processing scipy/optimize/_trlib/_trlib.pyx
Processing scipy/optimize/cython_optimize/_zeros.pyx.in
Processing scipy/signal/_max_len_seq_inner.pyx
Processing scipy/signal/_peak_finding_utils.pyx
Processing scipy/signal/_sosfilt.pyx
Processing scipy/signal/_spectral.pyx
Processing scipy/signal/_upfirdn_apply.pyx
Processing scipy/sparse/_csparsetools.pyx.in
Processing scipy/sparse/csgraph/_flow.pyx
Processing scipy/sparse/csgraph/_matching.pyx
Processing scipy/sparse/csgraph/_min_spanning_tree.pyx
Processing scipy/sparse/csgraph/_reordering.pyx
Processing scipy/sparse/csgraph/_shortest_path.pyx
Processing scipy/sparse/csgraph/_tools.pyx
Processing scipy/sparse/csgraph/_traversal.pyx
Processing scipy/spatial/_hausdorff.pyx
Processing scipy/spatial/_voronoi.pyx
Processing scipy/spatial/ckdtree.pyx
Processing scipy/spatial/transform/rotation.pyx
Processing scipy/spatial/qhull.pyx
Processing scipy/special/_comb.pyx
Processing scipy/special/_ellip_harm_2.pyx
Processing scipy/special/_test_round.pyx
Processing scipy/special/_ufuncs.pyx
Processing scipy/special/_ufuncs_cxx.pyx
Processing scipy/special/cython_special.pyx
Processing scipy/stats/_qmc_cy.pyx
Processing scipy/stats/_sobol.pyx
Processing scipy/stats/_stats.pyx
Processing scipy/stats/biasedurn.pyx
Processing scipy/stats/_boost/src/beta_ufunc.pyx
Processing scipy/stats/_boost/src/binom_ufunc.pyx
Processing scipy/stats/_boost/src/nbinom_ufunc.pyx
warning: _cython_special_custom.pxi:9:8: Unreachable code
warning: _cython_special_custom.pxi:13:4: Unreachable code
warning: _cython_special_custom.pxi:21:8: Unreachable code
warning: _cython_special_custom.pxi:25:4: Unreachable code
warning: _cython_special_custom.pxi:33:8: Unreachable code
warning: _cython_special_custom.pxi:37:4: Unreachable code
warning: _cython_special_custom.pxi:45:8: Unreachable code
warning: _cython_special_custom.pxi:49:4: Unreachable code
lapack_opt_info:
lapack_mkl_info:
customize UnixCCompiler
  libraries mkl_rt not found in ['/tmp/build-env-m9a9wxsh/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

openblas_lapack_info:
customize UnixCCompiler
customize UnixCCompiler
customize UnixCCompiler
C compiler: /usr/bin/gcc -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -D_GNU_SOURCE -fPIC -fwrapv -ffat-lto-objects -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -D_GNU_SOURCE -fPIC -fwrapv -ffat-lto-objects -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -D_GNU_SOURCE -fPIC -fwrapv -ffat-lto-objects -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -fPIC

creating /tmp/tmpi3kqtfni/tmp
creating /tmp/tmpi3kqtfni/tmp/tmpi3kqtfni
compile options: '-c'
gcc: /tmp/tmpi3kqtfni/source.c
/usr/bin/gcc /tmp/tmpi3kqtfni/tmp/tmpi3kqtfni/source.o -L/usr/lib64 -lflexiblas -o /tmp/tmpi3kqtfni/a.out
customize UnixCCompiler
  FOUND:
    libraries = ['flexiblas', 'flexiblas']
    library_dirs = ['/usr/lib64']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

  FOUND:
    libraries = ['flexiblas', 'flexiblas']
    library_dirs = ['/usr/lib64']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

/tmp/build-env-m9a9wxsh/lib64/python3.8/site-packages/numpy/distutils/system_info.py:782: UserWarning: Specified path /tmp/build-env-m9a9wxsh/lib64/python3.8/site-packages/numpy/__init__.py/include/python3.8 is invalid.
  return self.get_paths(self.section, key)
/tmp/build-env-m9a9wxsh/lib64/python3.8/site-packages/numpy/distutils/system_info.py:782: UserWarning: Specified path /usr/local/include/python3.8 is invalid.
  return self.get_paths(self.section, key)
/tmp/build-env-m9a9wxsh/lib64/python3.8/site-packages/numpy/distutils/system_info.py:782: UserWarning: Specified path /usr/include/suitesparse/python3.8 is invalid.
  return self.get_paths(self.section, key)
blas_opt_info:
blas_mkl_info:
customize UnixCCompiler
  libraries mkl_rt not found in ['/tmp/build-env-m9a9wxsh/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

blis_info:
customize UnixCCompiler
  libraries blis not found in ['/tmp/build-env-m9a9wxsh/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
  NOT AVAILABLE

openblas_info:
customize UnixCCompiler
customize UnixCCompiler
customize UnixCCompiler
  FOUND:
    libraries = ['flexiblas', 'flexiblas']
    library_dirs = ['/usr/lib64']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

  FOUND:
    libraries = ['flexiblas', 'flexiblas']
    library_dirs = ['/usr/lib64']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

non-existing path in 'scipy/signal/windows': 'tests'
non-existing path in 'scipy/sparse': 'sparsetools/sparsetools_impl.h'
non-existing path in 'scipy/sparse': 'sparsetools/bsr_impl.h'
non-existing path in 'scipy/sparse': 'sparsetools/csc_impl.h'
non-existing path in 'scipy/sparse': 'sparsetools/csr_impl.h'
non-existing path in 'scipy/sparse': 'sparsetools/other_impl.h'
[makenpz] generating scipy/special/tests/data/boost.npz
[makenpz] generating scipy/special/tests/data/gsl.npz
[makenpz] generating scipy/special/tests/data/local.npz
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 261, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "/tmp/build-env-m9a9wxsh/lib/python3.8/site-packages/setuptools/build_meta.py", line 221, in build_wheel
    return self._build_with_temp_dir(['bdist_wheel'], '.whl',
  File "/tmp/build-env-m9a9wxsh/lib/python3.8/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
    self.run_setup()
  File "/tmp/build-env-m9a9wxsh/lib/python3.8/site-packages/setuptools/build_meta.py", line 258, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/tmp/build-env-m9a9wxsh/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 631, in <module>
    setup_package()
  File "setup.py", line 627, in setup_package
    setup(**metadata)
  File "/tmp/build-env-m9a9wxsh/lib64/python3.8/site-packages/numpy/distutils/core.py", line 137, in setup
    config = configuration()
  File "setup.py", line 537, in configuration
    config.add_subpackage('scipy')
  File "/tmp/build-env-m9a9wxsh/lib64/python3.8/site-packages/numpy/distutils/misc_util.py", line 1033, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/tmp/build-env-m9a9wxsh/lib64/python3.8/site-packages/numpy/distutils/misc_util.py", line 999, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/tmp/build-env-m9a9wxsh/lib64/python3.8/site-packages/numpy/distutils/misc_util.py", line 941, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/setup.py", line 26, in configuration
    config.add_subpackage('_lib')
  File "/tmp/build-env-m9a9wxsh/lib64/python3.8/site-packages/numpy/distutils/misc_util.py", line 1033, in add_subpackage
    config_list = self.get_subpackage(subpackage_name, subpackage_path,
  File "/tmp/build-env-m9a9wxsh/lib64/python3.8/site-packages/numpy/distutils/misc_util.py", line 999, in get_subpackage
    config = self._get_configuration_from_setup_py(
  File "/tmp/build-env-m9a9wxsh/lib64/python3.8/site-packages/numpy/distutils/misc_util.py", line 941, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "scipy/_lib/setup.py", line 25, in configuration
    check_boost_submodule()
  File "scipy/_lib/setup.py", line 9, in check_boost_submodule
    raise RuntimeError("Missing the `boost` submodule! Run `git submodule "
RuntimeError: Missing the `boost` submodule! Run `git submodule update --init` to fix this.
```

### SciPy/NumPy/Python version information

scipy 1.7.3

**Comment by mckib2** [comment]
SciPy now requires submodules, so a "simple" `git clone` will not get all required sources.  The RuntimeError has the solution in its text: run
```
git submodule update --init
```

**Comment by rgommers** [comment]
> I'm using github autogenerated source tar ball from v1.7.3 tag

Please do not do this. We cannot delete these autogenerated tarballs unfortunately, but they're invalid. Use the proper sdist on that same page (`scipy-1.7.3.tar.gz`).

> problem with building scipy against system boost

This is a bad idea, please do not do this either. The version in the git submodule (pointing to https://github.com/scipy/boost-headers-only, currently at Boost `1.75.0`) works, other versions may not (and in fact, `1.76.0` is known to not work).

**Comment by rgommers** [comment]
I'll close this as invalid. Please use the correct (vendored) version. If there's rules in your Linux distro telling you to use the system version: this is nonsense for a build-time-only, header-only vendored submodule. There cannot be conflicts between the built SciPy RPM and other RPMs due to using the vendored version.

**Comment by kloczek** [comment]
Sorry but I must to ask ..
Why scipy depends on custom boost copy?
What is wrong with scipy github repo content?

**Comment by mckib2** [comment]
>  Why scipy depends on custom boost copy?

Probably the biggest reason is that SciPy doesn't want a dependency on CMake.  Currently, all C/C++ libraries have to be compatible and able to be built using distutils/setuptools (and in the near future we will be moving to meson, not cmake).  Compiled libraries stress the current build system, and header-only libraries are much easier to integrate.  Since we do not rely on any of Boost's compiled libraries (and it turns out to be tricky to compile Boost on all the platforms we want to support), all we really need to do is generate the header files we need and use those at build time.  [boost-headers-only](https://github.com/scipy/boost-headers-only) is exactly that: only the header files for distribution.  More recent versions of Boost also drop support for compiler tool chains that we still support, most notably older versions if GCC <7, so we have to pin ourselves to specific upper versions which might not be respected by system-provided Boost installations.

**Comment by kloczek** [comment]
Using system installed header files does not mean "cmake build dependency"
What is wrong with latest boost used with older gcc?

**Comment by mckib2** [comment]
There are notes in a couple different places about this, the most recent being gh-15136. It's a lack of modern c++ support in the minimum supported GCC for scipy 

I think I now understand what you're suggesting: using an existing boost install instead of the version of boost that comes with scipy through the submodule. I am not aware that anyone has tried to do this, but I'm not sure why you would want to. What issue are you running into where you need exactly the boost installation already existing on your system?

One of the pros of using our header-only boost distribution is consistency across all scipy builds. We don't have to make sure we work with any boost version, just the one we support for any given release. If there's a significant drawback of our approach that you're running into, please do say. If you do have a compelling use case, it might be possible to allow users to configure the build to use an existing boost include directory

**Comment by mckib2** [comment]
It's worth noting that this is not only a boost submodule issue when building scipy. UNURAN, PROPACK, and (hopefully soon) HiGHS are all included as submodules. It's likely you just ran into the boost error first.

**Comment by kloczek** [comment]
BTW are you aware of that gcc <7 is already EOSed?

**Comment by mckib2** [comment]
> BTW are you aware of that gcc <7 is already EOSed?
> 

Oh yes, things just move slowly around here :) please see the tool chain roadmap for more info there.

**Comment by rgommers** [comment]
Another major reason for vendoring Boost is that it's then a (simple) build system integration. Adding it as an external build-time dependency is hugely more expensive. It's a dependency we cannot even express in `pyproject.toml` (cause PyPI is not in the business of shipping native libraries), Windows users won't have it, etc.

> BTW are you aware of that gcc <7 is already EOSed?

There are multiple blockers, probably the most important one being that the most recent `manylinux` standard and Docker image only provides GCC 6.3

**Comment by rgommers** [comment]
> UNURAN, PROPACK, and (hopefully soon) HiGHS are all included as submodules.

Also, git submodules are an implementation detail of vendoring. We have many other things vendored. Example: `scipy.sparse.linalg` contains copies of ARPACK and SuperLU. ARPACK used to be unmaintained, but is now maintained again at https://github.com/opencollab/arpack-ng. And SuperLU at https://github.com/xiaoyeli/superlu.

Half of SciPy is vendored C/C++/Fortran code. If we'd remove those and declare them all as dependencies, things would be super fragile and almost impossible to package/build.

**Comment by rgommers** [comment]
> I think I now understand what you're suggesting: using an existing boost install instead of the version of boost that comes with scipy through the submodule.

It's worth noting that with Meson we do gain the ability to easily express _"use system Boost=1.75 if you can find it, otherwise fall back on the vendored copy"_. So that's an option in the future. It won't gain us a huge amount (except tick some distro guidelines box), but it's in principle a nice capability to have. And may make it easier to run tests with newer Boost versions, because all you do is update the version number in a `meson.build` file instead of having to mess with the submodule.

**Comment by kloczek** [comment]
> Adding it as an external build-time dependency is hugely more expensive

What you mean?
I would only gently repeat questions: what ius wrong with system installed for example 1.76.0 boost that it cannot be used with scipy?
Just checked my rpm packages spec files:
```consile
[tkloczko@ss-desktop SPECS]$ grep boost-devel -l * | wc -l
47
```
None of those packages has any issue with that version of the boost.
If iit is something wrong with boost where is the opened issue ticket with exact problem?

**Comment by mckib2** [comment]
> what ius wrong with system installed for example 1.76.0 boost that it cannot be used with scipy?

No technical limitations that I am immediately aware of. In my mind (and as I've mentioned before) there's a lot to be gained by maintainers from consistency. At my day job I work on code bases that support building with multiple versions of boost and we run into strange and unexpected issues all the time - that's just a reality of software development (also see Hyrum's law for example). And as Ralf mentioned, scipy lives in a world of library integration and we need to respect maintainer time and not unnecessary complicate things. So while it is possible to build against 1.76, I want to have a very good reason to fork the user base like that.

If you have a genuine use case that warrants support for this, please say. If not, I think this discussion has run its course for now

**Comment by rgommers** [comment]
> > Adding it as an external build-time dependency is hugely more expensive
> 
> What you mean?

If you don't understand what I mean when I say a dependency is more expensive than vendoring code, I recommend this book: [Software Engineering at Google](https://abseil.io/resources/swe_at_google.2.pdf), and in particular chapter 18 (Build systems and build philosophy) and the _Managing dependencies_ section in it.

There's also a rule explained there that's quite important: _The One-Version Rule_. It applies here - it's important for SciPy to have to deal with only one version of the Boost headers we need. On the contrary, it does not apply to your distro in this case (although it does to full packages): there is absolutely no reason why it should matter to you whether we vendor some Boost headers from 1.75 or 1.76 - both work for building your RPM, and it's totally transparent to you which version we use.
