### ISSUE TITLE
Boost and PROPACK git submodules are too easy to commit changes for

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#15276]
I've now been bitten about 5 times by the latest change in the PROPACK submodule, either committing it by accident myself or seeing that in other PRs. The problem is the combination of `active` and `ignore` settings in `.gitmodules`:

```
[submodule "doc/sphinxext"]
	path = doc/sphinxext
	url = https://github.com/numpy/numpydoc.git
[submodule "doc/source/_static/scipy-mathjax"]
	path = doc/source/_static/scipy-mathjax
	url = https://github.com/scipy/scipy-mathjax.git
[submodule "scipy/_lib/boost"]
	path = scipy/_lib/boost
	url = https://github.com/scipy/boost-headers-only
	shallow = true
	active = false
	ignore = all
[submodule "scipy/sparse/linalg/_propack/PROPACK"]
	path = scipy/sparse/linalg/_propack/PROPACK
	url = https://github.com/scipy/PROPACK
	shallow = true
	active = false
	ignore = all
[submodule "scipy/_lib/unuran"]
	path = scipy/_lib/unuran
	url = https://github.com/scipy/unuran.git
```

This makes changes to those submodules invisible, for example in the output of `git status` and `gitk`. So when you check what you're committing with `git status`, you can't see you're about to commit a change of the commit that the PROPACK submodule points to. And when you're switching branches a lot, such changes happen all the time. Normally you rely on `git status` to catch that, and then run `git submodule update` to fix it.

@mckib2 is there any reason why you added those settings? Can we simply remove them?

**Comment by tylerjereddy** [comment]
Yeah, I've seen this as well. I just narrowly caught it when switching branches for release stuff.

**Comment by mckib2** [comment]
> @mckib2 is there any reason why you added those settings? Can we simply remove them?

Yes, if these are an issue please remove.  My intent was carry around as little history as possible (`shallow = true`) to make the submodules "lighter" and it looks like I set a few other options as well thinking I was advertising that changes "should" be ignored.  I haven't personally run into any issues with cross contamination even though I do work with them fairly frequently

**Comment by rgommers** [comment]
Thanks Nicholas.

The `shallow = true` is useful. The other options (and in particular `ignore = all`) aren't great. The actual changes are then hidden, but `git commit -a` still commits then - leading to silent problems.
