### ISSUE TITLE
freqz: suboptimal performance for worN=2**n+1, include_nyquist=True and real coefficients

### ISSUE THREAD

**Issue by drestebon** [scipy/scipy#15273]
### Describe your issue.

freqz can be way faster, when the coefficients are real, `worN=2**n+1` and `include_nyquist=True`. In this case `rfft` can be used directly.

The attached code illustrates this, I hope.

Thanks for the great work!

### Reproducing Code Example

```python
import numpy as np
from scipy.signal import freqz
import timeit

N = 128

for n in range(7):
    worN = 2**n*N//2+1
    print('worN = {}'.format(worN))

    h = np.random.rand(N)*2-1

    f0 = lambda: freqz(h, worN=worN, include_nyquist=True)[1]
    f1 = lambda: np.fft.rfft(h, n=2*(worN-1))

    H0 = f0()
    H1 = f1()

    err = np.sum(np.abs(H0-H1)**2)/np.sum(np.abs(H0)**2)
    print('error = {}'.format(err))

    t0 = timeit.timeit(f0, number=10000)
    t1 = timeit.timeit(f1, number=10000)
    print('speedup = {}\n'.format(t0/t1))
```

### Error message

```shell
worN = 65
error = 7.582436736470968e-29
speedup = 118.5314640968968

worN = 129
error = 1.2033665898383146e-28
speedup = 62.96460648165139

worN = 257
error = 6.748460212611348e-29
speedup = 54.55989853561076

worN = 513
error = 6.378075125203393e-29
speedup = 47.368120583063835

worN = 1025
error = 8.559451508895459e-29
speedup = 38.34191925764777

worN = 2049
error = 7.356556838100076e-29
speedup = 29.080013414218744

worN = 4097
error = 8.396001469974994e-29
speedup = 22.058802358213786
```

### SciPy/NumPy/Python version information

1.7.3 1.21.4 sys.version_info(major=3, minor=10, micro=1, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @drestebon, thanks for reporting. Looking at the documentation, there are some rules to observe so that (R)FFT is used. From what I see in your example, worN's shape is not good. I did not check yet the code as to why it would be needed. Did you have a look? Are you suggesting something else?

**Comment by drestebon** [comment]
Hi @tupui, thanks for your reply.

It seems like the rules implemented to use (R)FFT do not reflect the case I'm referring to.

I made an attempt at this. You can see it here:

https://github.com/drestebon/scipy/blob/f4c9c947b2220f52415fff349a79147ec6afc4ab/scipy/signal/_filter_design.py#L445

My feeling is that the way I did it is a bit hackish and clumsy, but it shows what is required: `n_fft` for this case is `2*(N-1)`.

It still looks like numpy's fft does a better job though.

```
worN = 65
error = 5.63413763959627e-29
speedup = 121.96746809708475

worN = 129
error = 4.657502702331312e-32
speedup = 11.959434175189896

worN = 257
error = 4.2029261309019205e-32
speedup = 9.685627976708963

worN = 513
error = 4.568295653285404e-32
speedup = 7.261198177906964

worN = 1025
error = 3.702060680434987e-32
speedup = 4.869401531950861

worN = 2049
error = 3.6579413212381833e-32
speedup = 3.173570125199443

worN = 4097
error = 4.7836664035146534e-32
speedup = 2.060847729547769
```

**Comment by AtsushiSakai** [comment]
When worN is small, it is faster, but the error looks big. We should be careful for backward compatibility.
```
worN = 3
error = 1.9374009635386986
speedup = 21.30843158223846

worN = 5
error = 0.18741190054056306
speedup = 16.77478100125656

worN = 9
error = 8.612108265284007e-32
speedup = 15.351992009731502

worN = 17
error = 5.22888645839279e-31
speedup = 13.55208721451381

worN = 33
error = 0.10942613312814237
speedup = 12.463569226773217

worN = 65
error = 3.79794227671082e-31
speedup = 14.018722794359956
```

**Comment by drestebon** [comment]
If we use `rfft` with `2*(worN-1) < b.shape[0]`, it means we are truncating the impulse response, which causes the error. My guess would be, that the user wouldn't want `freqz` to make any approximations.

In my branch I included the condition `2*(N-1) >= b.shape[0]` to reflect this.

**Comment by drestebon** [comment]
I ran a bit more exhaustive benchmarks and it seems the `rfft` approach is faster than the `polyval` for any value of `worN`.

For these simulations I introduced a `force_poly` argument, to skip the `fft`-related optimizations in `freqz`.

![rfft_speedup](https://user-images.githubusercontent.com/6323472/147413756-ea90a073-fcc8-4666-b27f-5747d9e6c14c.png)
![rfft_speedup_long](https://user-images.githubusercontent.com/6323472/147413757-fb054bd4-b144-4111-b7d5-2f7d1eebc7d3.png)

The code:

```
import matplotlib.pyplot as plt
import numpy as np
import scipy
from scipy.signal import freqz
import timeit

from scipy import fft as sp_fft

print(scipy.__file__)

fig = plt.figure(1, figsize=(19, 12))
fig.clf()
ax = fig.subplots(3,4)

Ntop = 20

# for Ntc, N in enumerate([64, 128, 256, 512]):
for Ntc, N in enumerate([4, 8, 16, 32]):

    NN = np.arange(N//2+1, Ntop*N//2+1)
    speedup = np.zeros((len(NN),))
    error   = np.zeros((len(NN),))
    t0   = np.zeros((len(NN),))
    t1   = np.zeros((len(NN),))

    for tc, n in enumerate(NN):
        # worN = 2**n*N//2+1
        worN = n

        h = np.random.rand(N)*2-1

        f0 = lambda: freqz(h, worN=worN, include_nyquist=True, force_poly=True)[1]
        f1 = lambda: sp_fft.rfft(h, n=2*(worN-1), axis=0)
        # f1 = lambda: np.fft.rfft(h, n=2*(worN-1))

        H0 = f0()
        H1 = f1()

        error[tc] = np.sum(np.abs(H0-H1)**2)/np.sum(np.abs(H0)**2)

        t0[tc] = timeit.timeit(f0, number=200)
        t1[tc] = timeit.timeit(f1, number=200)
        speedup[tc] = t0[tc]/t1[tc]

        print('N = {}\tworN = {:5d}\terror = {:.10e}\tspeedup = {:.5f}'.format(N, worN, error[tc], speedup[tc]))

    ax[0,Ntc].semilogy(NN, error)
    ax[1,Ntc].semilogy(NN, speedup)
    ax[1,Ntc].hlines(1, NN[0], NN[-1], color='k', ls=':')
    ax[2,Ntc].semilogy(NN, t0, label='freqz{polyval}')
    ax[2,Ntc].semilogy(NN, t1, label='rfft')
    ax[0,Ntc].set_xlabel('worN')
    ax[1,Ntc].set_xlabel('worN')
    ax[2,Ntc].set_xlabel('worN')
    ax[0,Ntc].set_ylabel('error')
    ax[1,Ntc].set_ylabel('speedup')
    ax[2,Ntc].set_ylabel('time')
    ax[2,Ntc].legend()
    ax[0,Ntc].set_title('sig.freqz{{polyval}} v/s scipy.fft.rfft\nlen(b)={}'.format(N))

fig.savefig('rfft_speedup.png')

```

**Comment by tupui** [comment]
Thanks you for the benchmark @drestebon. It looks like we could benefit for another condition to benefit from this. @ilayn does this look right to you?

**Comment by drestebon** [comment]
People,

I was trying to get fairer benchmark, that included the _fixed costs_ of `sig.freqz` and noted a much more concerning issue. For the new benchmark, the first thing I wanted to do was to check that, when `freqz` uses `rfft`, it does the same operation I think it should be doing (an fft of a given length), so that I can substract the `rfft`-calculation-time and get the overhead in `freqz`. To my surprise, `freqz` is not doing the `rfft` at the length I was expecting.

I think the way `freqz` is currently using the `rfft` is wrong!!!

In the example below I am calculating the frequency response of `H(z) = z^-8` on an evenly spaced grid of 64 points between DC and Nyquist (0 and pi included). For `rfft` to produce the correct grid, I need to apply it on a window of 126 samples, i.e. `2*(worN-1)`. `freqz`, however, uses a window of 128 samples, which produces an evenly spaced grid of 65 points!!

This error should be very easy to catch, since using the wrong fft length will give a result of a different length than what we are asking for (worN). Alas! in `freqz` we are truncating the result of the fft here: `h = fft_func(b, n=n_fft, axis=0)[:N]`, masking the error.

For sanity, in the example I am calculating the frequency response analytically, using `freqz`, with an `rfft` and forcing `freqz` to use `polyval`. As you can see in the plot, the two methods currently implemented in `freqz` give very different results! The polyval being the correct one (to the best of my knowledge).

I think this is a separate issue from what we have been discussing in this thread. Is the use to open another issue, or should we open the scope of this issue?

![freqz rfft grid error](https://user-images.githubusercontent.com/6323472/147514768-12c6f118-7e9a-4535-8843-97dc2273318c.png)


Script for reproducing the plot:

```
import numpy as np
import matplotlib.pyplot as plt

import scipy
import scipy.signal as sig
from scipy import fft as sp_fft

print(scipy.__file__)

has_freqz_debug = False

worN = 64
N = 8

# impulse response for H(z) = z**-7
h = np.zeros(N)
h[-1] = 1

fig = plt.figure(1, figsize=[21,  6])
plt.clf()

if has_freqz_debug:
    # default behaviour
    foo = {'debug' : True}
    w, H = sig.freqz(h, worN=worN, include_nyquist=True, freqz_debug=foo)

    plt.plot(np.real(H), label='freqz')
    plt.plot(np.imag(H), label='freqz')

    print(foo)

    # Forced poly
    w, Hp = sig.freqz(h, worN=worN, include_nyquist=True, force_poly=True)

    plt.plot(np.real(Hp), '.', lw=3, label='freqz force_poly=True re')
    plt.plot(np.imag(Hp), '.', lw=3, label='freqz force_poly=True im')
else:
    # default behaviour
    w, H = sig.freqz(h, worN=worN, include_nyquist=True)

    plt.plot(np.real(H), label='freqz')
    plt.plot(np.imag(H), label='freqz')


# Analyic
zm1 = np.exp(-1j * w)
Ha = zm1**(N-1)

plt.plot(np.real(Ha), lw=1, label='analytic re')
plt.plot(np.imag(Ha), lw=1, label='analytic im')


# rfft
nrfft = 2*(worN-1)
Hrfft = sp_fft.rfft(h, n=nrfft, axis=0)
plt.plot(np.real(Hrfft),  '--', lw=2, label='rfft re')
plt.plot(np.imag(Hrfft),  '--', lw=2, label='rfft im')
print('nrfft = {}'.format(nrfft))


# error
plt.plot(np.real(Ha - H),  lw=1, label='Error: analytic - freqz re')
plt.plot(np.imag(Ha - H),  lw=1, label='Error: analytic - freqz im')

plt.legend()

plt.savefig('freqz rfft grid error.png')

plt.show()
```

Output of the script (when I set `has_freqz_debug=True`):

```
/home/e/src/scipy/scipy/__init__.py
{'debug': True, 'n_fft': 128, 'is_fft': True}
nrfft = 126
```

**Comment by drestebon** [comment]
_Sorry for yet another very long comment._

I did some benchmarking using the fix in the commit above.

I'm measuring the execution time of the _poly_ and _(r)fft_ implementations. The plots below show the error (difference between both approaches) and the speed improvement of the later as a function of `worN` and of `n_fft`. The column on the left corresponds to randomized impulse responses of length `n_fft`. The column on the right corresponds to impulse responses where `len(b) << n_fft`, which means the fft will do some zero-padding. They also include an allpass component. The purpose of this IR is to show the limitation of the current implementation (mentioned earlier).


## Things to note:

* The fix removes the spikes in the error that appear on the right column
* The fix improves the execution time across the board, except for small values of `n_fft`. An ideal solution would include a threshold on `n_fft`. I tried the fix on two very different machines (see below) and the results look equivalent. A conservative threshold would be, for example, that the _(r)fft_ is applied only for `n_fft >= 32`.
* The point on the `n_fft` axis where the _(r)fft_ improves the execution time increases as the amount of zero-padding increases: for a small number of coefficients, the _poly_ approach is faster than _(r)fft_, and improvements only appear for very long values of `n_fft`. An ideal solution would have a threshold on `n_fft` that is a function of `n_fft / len(b)`. This would require a bit more benchmarking that I'd be happy to do.

So far, the fix boils down to correctly calculating `n_fft` for `include_nyquist=True` and removing the constraint `sp_fft.next_fast_len(N) == N` (see the commit mentioned above).


Benchmark for the current implementation:

![freq_fft_benchmark_i5_mainline](https://user-images.githubusercontent.com/6323472/147794259-fbfa6ac7-fd75-410c-a753-d3ab32b7ae3e.png)


Benchmark for the fix:

![freq_fft_benchmark_i5_fix](https://user-images.githubusercontent.com/6323472/147794284-d8c3f344-dc0a-4378-b60d-5c56253f4fd1.png)


Both these benchmarks were carried out on this computer:

    model name	: Intel(R) Core(TM) i5-7260U CPU @ 2.20GHz
    MemTotal:       32763848 kB


# Run on a bigger computer

Further results were obtained on this computer:

    model name      : Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz
    MemTotal:       197564584 kB


Benchmark for the current implementation

![freq_fft_benchmark_xeon_mainline](https://user-images.githubusercontent.com/6323472/147794342-54a318f3-df0c-4938-a158-c3163bee8c5a.png)


Benchmark for the fix

![freq_fft_benchmark_xeon_fix](https://user-images.githubusercontent.com/6323472/147794325-304cfe46-4c74-43e0-a52a-a7bb4af9c470.png)


# script
<details>
  <summary>Click to expand!</summary>

```
import sys

if len(sys.argv) < 2:
    print('Hey! give a name to the run with an argument')
    sys.exit()

import matplotlib.pyplot as plt

import numpy as np
import numpy.random

import scipy
from scipy.signal import freqz
from scipy import fft as sp_fft

import timeit

print(scipy.__file__)

fig = plt.figure(1, figsize=(12, 12))
fig.clf()
ax = fig.subplots(3,2)

attempts = 256

NN      = np.arange(4, 256)
speedup = np.zeros((len(NN),))
error   = np.zeros((len(NN),))
t0      = np.zeros((len(NN),))
t1      = np.zeros((len(NN),))

rng = np.random.RandomState(0)

for zp in [False, True]:
    for cplx in [False, True]:
        for whole in [False, True]:
            for include_nyquist in [False, True]:
                for tc, n in enumerate(NN):
                    worN = n

                    N = n if whole else 2*(n - 1) if include_nyquist else 2*n

                    # Bad things happen with zero padding (len(impulse response) << n_fft)
                    if zp:
                        N = N//2

                    h = rng.randn(N)
                    if cplx:
                        h = h + 1.0j*rng.randn(N)

                    # Bad things happen with a wide band response
                    if zp:
                        k = min(4, N-1)
                        h[k] = h[k]+10.0 # mala leche

                    ww, Hf = freqz(h, worN=worN, include_nyquist=include_nyquist, whole=whole)
                    f0 = lambda: freqz(h, worN=ww)[1] # poly
                    f1 = lambda: freqz(h, worN=worN, include_nyquist=include_nyquist, whole=whole)[1]

                    H0 = f0()
                    H1 = f1()

                    error[tc] = np.sum(np.abs(H0-H1)**2)/np.sum(np.abs(H0)**2)

                    t0[tc] = timeit.timeit(f0, number=attempts)
                    t1[tc] = timeit.timeit(f1, number=attempts)
                    speedup[tc] = t0[tc]/t1[tc]

                    print('{}{}{}{} N = {}\tworN = {:5d}\terror = {:.10e}\tspeedup = {:.5f}'.format(
                           int(zp), int(cplx), int(whole), int(include_nyquist), N, worN, error[tc], speedup[tc]))

                lbl = []
                if cplx:
                    lbl.append('c')
                if whole:
                    lbl.append('wh')
                if include_nyquist:
                    lbl.append('ny')
                if not lbl:
                    lbl.append('-')

                Nfft = NN if whole else 2*(NN - 1) if include_nyquist else 2*NN
                ax[0, int(zp)].semilogy(NN , error   , label=' '.join(lbl))
                ax[1, int(zp)].semilogy(NN , speedup , label=' '.join(lbl))
                ax[2, int(zp)].semilogy(Nfft , speedup , label=' '.join(lbl))

title = ['sig.freqz[poly] v/s sig.freqz[(r)fft]',
         '$\\bf{c}$plx in [False, True]',
         '$\\bf{wh}$ole in [False, True]',
         'include_$\\bf{ny}$quist in [False, True]']

for k in range(2):
    ax[0, k].set_title('\n'.join(title+['zero_padding='+str(bool(k))]))
    ax[0, k].set_ylabel('error')
    ax[0, k].set_xlabel('worN')
    ax[0, k].legend()
    ax[1, k].hlines(1, NN[0], NN[-1], color='k', ls=':')
    ax[1, k].set_xlabel('worN')
    ax[1, k].set_ylabel('speedup')
    ax[1, k].legend()
    ax[2, k].hlines(1, NN[0], 2*NN[-1], color='k', ls=':')
    ax[2, k].set_xlabel('n_fft')
    ax[2, k].set_ylabel('speedup')
    ax[2, k].legend()

fig.savefig('freq_fft_benchmark_{}.png'.format(sys.argv[-1]))

plt.show()

import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
```

</details>
