### ISSUE TITLE
BUG(?): Following the meson build instructions results in Python 3.10.1 being installed. 

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#15307]
### Describe your issue.

If I follow the instructions at https://github.com/scipy/scipy/blob/master/doc/source/dev/contributor/meson.rst, starting with the latest miniconda (which has Python 3.9), the environment created by the command 

    conda env create -f environment_meson.yml

installs Python 3.10.1.

Is this a bug, or a known (and hopefully temporary) glitch in the meson build configuration?

**Comment by dhomeier** [comment]
Maybe an oversight, but not specific to meson – `conda env` seems to have defaulted to Python 3.10 for some time now, although its 3.10 support has not been that robust so far (and the initially installed version is still 3.9).
For the time being, changing the `dependencies` line to `python=3.9` may be the only option to ensure you use that version.

**Comment by tupui** [comment]
I guess conda just treats `python` as a dependency and so tales latest.

**Comment by rgommers** [comment]
@tupui and @dhomeier are correct. Conda works like every other package manager (`apt`, `brew`, `yum`, etc.) and treats Python as a normal dependency - so it defaults to the latest version unless there's a conflict that would cause it to downgrade to `3.9`. Which is a good thing:)

**Comment by WarrenWeckesser** [comment]
When I hesitantly called this a "bug", I didn't mean to suggest that this was a bug in conda.  I meant that this was a problem with the workflow recommended in [`meson.rst`](https://github.com/scipy/scipy/blob/master/doc/source/dev/contributor/meson.rst).  If I am using Python 3.9, I definitely do *not* want my Python version upgraded to 3.10 just so I can use meson.  Does meson require 3.10?

**Comment by rgommers** [comment]
No, it's certainly not a bug. If you want to install `meson`, `ninja` and `pkg-config` in your existing Python 3.9 environment, you can. Meson works with all supported Python 3.x versions.

The `conda env create -f environment_meson.yml` creates a new environment, and that should just use the normal solver rules - which will give you Python 3.10. This is typically recommended - a fresh environment for every project - so the docs follow best practice.

**Comment by WarrenWeckesser** [comment]
OK.  It still feels wrong to me, but I guess I have a different mental model of the purpose of those instructions.

**Comment by rgommers** [comment]
I think like all our instructions they are "from scratch". If you already have an existing environment, it's hard to write instructions - it could be just `conda install meson ninja pkg-config`, but it may not be (e.g. your environment doesn't have `openblas`).
