### ISSUE TITLE
How to give the initial guess step length in the line search?

### ISSUE THREAD

**Issue by Find-Oneself** [scipy/scipy#15329]
Hi, everybody.

I find that the initial guess step length is determined in the line search by 

### "old_old_fval = old_fval + np.linalg.norm(gfk) / 2", (line 1621 in scipy/scipy/optimize/_optimize.py).

And the note is "Sets the initial step guess to dx ~ 1". 

What's the principle behind it? Could you give me some guides? Thank you!

Best regards.

**Comment by tupui** [comment]
Hi @Find-Oneself 👋. The issue tracker is not meant for user questions as we don't have the bandwidth to help here. I suggest you to ask either on our user mailing list or StackOverflow.
