### ISSUE TITLE
Getting troubles while installing python packages on apple m1 processor

### ISSUE THREAD

**Issue by sanpreet** [scipy/scipy#15324]
Hi, I have been facing a lot of issues while installing python packages such as scipy, skearn, numpy, spacy and scikit-learn. I tried using pip, conda but unfortunately i was not able to install all requirements. I have asked the question in [askubuntu](https://askubuntu.com/questions/1384640/how-to-install-python-packages-on-mac-with-m1-processor) with the detailed explanation and screenshots of the error i am facing.

I tried a lot and seeking a way to get the things resolved.

**Comment by ilayn** [comment]
Duplicate of #13409
