### ISSUE TITLE
DOC: Rename `*args` param in `f_oneway` to `*samples`

### ISSUE THREAD

**Issue by ShivnarenSrinivasan** [scipy/scipy#15338]
The current signature for the [`f_oneway`](https://github.com/scipy/scipy/blob/47bb6febaa10658c72962b9615d5d5aa2513fa3a/scipy/stats/stats.py#L3475-L3699) function in the `stats` module reads:
```python
def f_oneway(*args, axis=0):
```
which does not provide any real clarity, imo.

**My suggestion is to refactor the `*args` param to `*samples`, or `*samps`—whatever form is more agreeable**.
The docstring itself uses `sample`:
>  sample1, sample2, ... : array_like

Of course anyone calling this function would have an idea of what the function would accept; nevertheless, I think this would add value at zero cost (*just a refactor within the function*).

![Untitled](https://user-images.githubusercontent.com/71850263/147878911-6b5af806-2478-447c-a39c-6de758f1f32f.png)

**Comment by tupui** [comment]
Thanks @ShivnarenSrinivasan. Seems like a good idea and the docstrings would also need an update. `samples` seems more appropriate. We should avoid truncating words like this.

**Comment by mdhaber** [comment]
Just wanted to mention explicitly that this is one of few examples where we _can_ change the name without a backward compatibility break, I think, because `args` cannot be provided as a keyword argument.

**Comment by tupui** [comment]
Thanks Matt, I should have written that explicitly 😅

Two reasons I prefer `samples`: it might be clearer for a less "programmer" public and as all elements should be of the same type/form, it makes sense to have an explicit name.

For a/b vs x/y, I tend to prefer x/y. But only because I've been more used to this personally (engineering background). I agree that we should also uniformize.

**Comment by ShivnarenSrinivasan** [comment]
> Thanks for reporting @ShivnarenSrinivasan! Seems like a good idea and the docstrings would also need an update. `samples` seems more appropriate. We should avoid truncating words like this. Would you like to make a PR?

Sure—happy to 👍
Should I do the other functions as well? @`kruskal, levene, bartlett, fligner`

> Just wanted to mention explicitly that this is one of few examples where we can change the name without a backward compatibility break, I think, because args cannot be provided as a keyword argument.

Right, of course


Regarding the docstrings: couldn't find anything wrong with them, but maybe I'm overlooking something?
> sample1, sample2, ... : array_like
> *args : tuple of array_like

These are the two formats I found; do we prefer the second form, or the first (*when the param is a *arg*)

Had one question on the tests before submitting the PR—I've already run the entire test suite once today; after the change, is it sufficient to run `python[3] runtests.py -v --submodule stats`? 
Or is it required to rerun the entire suite before pushing?

**Comment by tupui** [comment]
> Sure—happy to 👍 Should I do the other functions as well? @`kruskal, levene, bartlett, fligner`

I would say so.

> Regarding the docstrings: couldn't find anything wrong with them, but maybe I'm overlooking something?
> 
> > sample1, sample2, ... : array_like
> > *args : tuple of array_like
> 
> These are the two formats I found; do we prefer the second form, or the first (*when the param is a _arg_)

I would go with the second form `*samples : tuple of array_like`. It's what numpydoc says.

> Had one question on the tests before submitting the PR—I've already run the entire test suite once today; after the change, is it sufficient to run `python[3] runtests.py -v --submodule stats`? Or is it required to rerun the entire suite before pushing?

Thanks for asking! The more you test locally the better as you could limit CI usage. Still, it's usually fine to just run the tests of the module you are touching. Of course, some functions are used in other modules and it might be disruptive. But it's ok and the CI will catch this. Something that is more important I would say would be to skip some CI if you just change the doc for instance (cf CI doc on our dev doc).
