### ISSUE TITLE
BUG: `highs-ds` returns memoryviews instead of np.arrays for the dual values

### ISSUE THREAD

**Issue by jhelgert** [scipy/scipy#15339]
According to the docs, the `highs-ds` method returns the Lagrangian multipliers (also known as *dual values*) corresponding to both the inequality/equality constraints and the upper/lower bounds as np.ndarray. However, for the latter it returns memoryviews.

# Reproducing Code Example

``` python
import numpy as np
from scipy.optimize import linprog

c = -1*np.array([300, 500])
A_ub = np.array([[1, 2], [1, 1], [0, 3]])
b_ub = np.array([170, 150, 180])
bounds = [(0, 100), (0, 100)]

# solve c'x  s.t.  A_ub*x <= b_ub,  0 <= x <= 100
result = linprog(c=c, A_ub=A_ub, b_ub=b_ub, bounds=bounds, method="highs-ds")
for key in ['lower', 'upper', 'eqlin', 'ineqlin']:
    print(result[key]['marginals'])
```

yields

``` none
<MemoryView of 'ndarray' object>
<MemoryView of 'ndarray' object>
[]
[-250.   -0.   -0.]
```

---

I had a look at the Cython wrapper and it indeed returns a memoryview which isn't converted to np.ndarray:

https://github.com/scipy/scipy/blob/a0e129fc3ba89fd81a5fa7e5e4d6aa2ec635a674/scipy/optimize/_highs/cython/src/_highs_wrapper.pyx#L706

https://github.com/scipy/scipy/blob/a0e129fc3ba89fd81a5fa7e5e4d6aa2ec635a674/scipy/optimize/_linprog_highs.py#L385-L386

**Comment by mckib2** [comment]
Thanks for reporting @jhelgert !  I do remember seeing this as well, should be a simple cast to `np.array`.  Would you like to submit a PR?
