### ISSUE TITLE
BUG: boschloo_exact gives pvalue > 1 (and sometimes nan)

### ISSUE THREAD

**Issue by MrTomRod** [scipy/scipy#15345]
### Describe your issue.

Found a bug in `boschloo_exact` (EXAMPLE 1): Sometimes, it yields pvalue > 1! The pvalue should obviously never be greater than 1.

In addition, I think `boschloo_exact` should never return `nan`, like `fisher_exact` (EXAMPLE 2). The documentation says that `statistic` is " the p-value from Fisher’s exact test", thus it should be 1. Imo, `pvalue` should also be 1 rather than nan.

Honestly, I don't understand what the `statistic` means, because it's not the same value as Fisher's test.

I'm tagging @V0lantis because he implemented the function (#13896).

### Reproducing Code Example

```python
from scipy.stats import fisher_exact, boschloo_exact



# EXAMPLE 1: pvalues > 0
boschloo_exact([[0,0],[7,4]])  # BoschlooExactResult(statistic=1.0, pvalue=2.0)

boschloo_exact([[1, 1], [13, 12]])  # BoschlooExactResult(statistic=0.7407407407407399, pvalue=1.2772982529540837)



# EXAMPLE 2: pvalues are nan
TABLE = [[0,5],[0,8]]

odds_ratio, pvalue = fisher_exact(TABLE)  # odds_ratio=nan pvalue=1.0

boschloo_exact(TABLE)  # BoschlooExactResult(statistic=nan, pvalue=nan)
```

### Error message

```shell
(no error message)
```

### SciPy/NumPy/Python version information

1.7.3 1.22.0 sys.version_info(major=3, minor=10, micro=1, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
@V0lantis thoughts here?

**Comment by V0lantis** [comment]
Ill try to have a look at it tomorrow :) Otherwise, don't mind me and go ahead if you think you have the solution

**Comment by V0lantis** [comment]
Thank you for the reminder. I’ll give another try next weekend if this sounds good to you :-)

**Comment by tupui** [comment]
The NaN behaviour is intentional. In the tests I see:

> Why do we disagree with R `Exact` library about the statistic here? (It reports 1 in both cases.) If the statistic is NaN, why not the p-value, too?

If we cannot compute anything, it does not really make sense to return something which could be interpreted as a good result. If you have one column which is null, it's not really a contingency table.

For going above 1, I suppose we are just missing a clip after `pvalue = 2 * res.pvalue`.

**Comment by tupui** [comment]
This is the result for `boschloo_exact([[1, 1], [13, 12]])` from the R library we compare our results to:
<img width="607" alt="Screenshot 2022-03-17 at 10 55 33" src="https://user-images.githubusercontent.com/23188539/158784132-87652bd5-2941-41a6-8f57-e33d24475c73.png">

**Comment by V0lantis** [comment]
Hello @tupui,
Thanks for the exploration ! 
Should I add some more documentation to the test?

**Comment by tupui** [comment]
> Hello @tupui,
> Thanks for the exploration !
> Should I add some more documentation to the test?

Hey @V0lantis

I would not say documentation is missing, I mean the NaN thing is pretty much related to all contingency tests. If we were to add anything I would add a general section for all the tests instead (we don't have such general section AFAIK).

To close this issue we just need to add the clipping I think.

**Comment by mdhaber** [comment]
Well there may be one other thing - the OP wrote:

> Honestly, I don't understand what the statistic means, because it's not the same value as Fisher's test.

@MrTomRod this test's statistic is the *p-value*, not the statistic, from Fisher's exact test. 

@V0lantis it's doing that correctly, right?

If so, I agree that the clipping is all that's needed. The documentation is clear enough about what the statistic is.
