### ISSUE TITLE
DOC: Reference guide for version 1.7.3 seems to be missing

### ISSUE THREAD

**Issue by christian-cahig** [scipy/scipy#15358]
The [site summarizing the lists of documentations](https://docs.scipy.org/doc/) links to the reference guides for [the development version (1.9.0.dev0+1221.b9fc49b)](http://scipy.github.io/devdocs/) and for [version 1.7.1](https://docs.scipy.org/doc/scipy-1.7.1/reference/).

Is this intentional?

**Comment by tupui** [comment]
Thank you @christian-cahig. Indeed it's missing. We have a few things we are trying to rework regarding the documentation. Everything is getting migrated slowly to scipy.org. There are also some issues with the 1.7 documentation that should be resolved for 1.8.

**Comment by christian-cahig** [comment]
@tupui I see. Thank you for this information. For the meantime, I’ll just stick with 1.7.1; it will be sufficient for my use case.

**Comment by tupui** [comment]
FYI, if 1.7.1 works for you I still suggest you get 1.7.3. We are using semantic versioning so 1.7.x only fix bugs that we really think should go in. But the stack does not change so for you it would be 100% transparent.

**Comment by christian-cahig** [comment]
@tupui that's great! Thank you very much!
