### ISSUE TITLE
BUG: misleading behaviour for `exact=True` in comb/factorial/factorial2

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#15351]
I stumbled across this in #15279
```
    Note that if ``exact=True``, non-integer arguments to  `comb` will be
    truncated to integers, leading to inaccurate results.
    >>> x, y = 3.9, 2.8
    >>> (binom(x, y), comb(x, y), comb(x, y, exact=True))
    (4.2071983565457955, 4.2071983565457955, 3)
```
which to me is _very_ unintuitive, bordering on misleading. If I pass `exact=True` to anything, I expect the result to become more precise, not less.

For `factorial`, there's no warning for floats by default, but then a misleading warning for `exact=True`:
```
>>> factorial(7.7)
21327.693789920282
>>> factorial(7.7, exact=True)
Traceback (most recent call last):
  [...]
ValueError: factorial() only accepts integral values
```

I also saw that #15349 enables floats for `factorial2`. It might be possible that it's best to raise an error if `exact=True` is used with non-integral values (similar to what `factorial` does now in spirit, though with an improved error message).

CC @steppi @tirthasheshpatel

**Comment by steppi** [comment]
Ah yes. When I wrote that docstring I was just trying to clarify the existing behavior. I hoped it would start the reckoning for the weird behavior for non-integral arguments when `exact=True`.  I was planning on submitting a mailing list post over the coming weekend about possible improvements to `comb` and `binom` and was going to bring this up along with gh-15213.

My personal preference would be to raise a `DeprecationWarning` warning that support for non-integer arguments will be removed in a future version, and then eventually to replace that with a `ValueError`.

**Comment by h-vetinari** [comment]
> My personal preference would be to raise a `DeprecationWarning` warning that support for non-integer arguments will be removed in a future version, and then eventually to replace that with a `ValueError`.

If you're talking about removing non-integer support generally (and not just for `exact=True`), then I'd be much more hesitant to agree. My only issue is with the current behaviour for non-integer + `exact=True`.

**Comment by steppi** [comment]
> > My personal preference would be to raise a `DeprecationWarning` warning that support for non-integer arguments will be removed in a future version, and then eventually to replace that with a `ValueError`.
> 
> If you're talking about removing non-integer support generally (and not just for `exact=True`), then I'd be much more hesitant to agree. My only issue is with the current behaviour for non-integer + `exact=True`.

I don’t want to leave the broader deprecation off the table and planned to include it as one of several options in my mailing list post, but in my previous comment I only had the `exact=True` case in mind.

**Comment by tirthasheshpatel** [comment]
Not a special expert but I agree that floats should be handled explicitly in the case of `exact=True`. Deprecation and eventual removal of the behavior seems like a good solution to me.

**Comment by h-vetinari** [comment]
I consider the `comb`-part of this solved by https://github.com/scipy/scipy/pull/15359 - thanks @j-bowhay! - resp. tracked more accurately by https://github.com/scipy/scipy/issues/15722. The factorial pieces have a better home in #15600, so closing this one.
