### ISSUE TITLE
MESON: test fails always manifest with runtests.py, but not dev.py (unless build directory is removed)

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#15365]
### Describe your issue.

I've made some changes in a [PR](https://github.com/scipy/scipy/pull/15363) which would cause some [test failures](https://github.com/scipy/scipy/pull/15363#discussion_r779213814). When I use `runtests.py` those failures always manifest (as they should). 

However, when I use `dev.py` those failures don't always manifest. If I run `python dev.py` before I make the breaking changes, then run `python dev.py` again the test failures don't appear. If make the breaking changes, delete the `build` directory, then run `python dev.py`, then the failures manifest.

It therefore appears to me that changes to any of the pure python files don't get updated in the `build` directory when `dev.py` gets run again. I would expect them to.

### Reproducing Code Example

```python
python dev.py
# make some changes to a test file such that it would now fail
python dev.py # the test doesn't fail, when it should.
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

1.9.0.dev0+1226.e650e5d 1.21.4 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by andyfaff** [comment]
Grr, now I can't repeat this issue. However, I did experience this problem, and I wasn't dreaming:

- `python runtests.py` fails on some tests related to some changes I made to some optimize code
- `python dev.py` run just afterwards passed, when I expected the same test fails to appear.

Leaving open just in case I'm not imagining things.

**Comment by rgommers** [comment]
It's a simple pure Python PR, so I don't see anything that could cause this. Are you sure you didn't run with `-n` or something like that? In that case you shouldn't see `"Installing, see meson-install.log...` printed before the test run.

**Comment by rgommers** [comment]
`tools/check_installation.py` now verifies that every single test file gets installed, and any `python dev.py` invocation with `--no-build` will run `meson install`. So I'm fairly confident that we can close this.

If you do see this again please reopen @andyfaff
