### ISSUE TITLE
BUG: API reference documentation has no main page

### ISSUE THREAD

**Issue by jacione** [scipy/scipy#15372]
### Describe your issue.

This isn't really a problem with scipy itself, but the documentation has a broken link. The main documentation page (https://docs.scipy.org/doc/scipy/reference/) has a link for API reference, which takes me to what looks like an unformatted version of the same page, but which has an extra `/reference` in the URL (https://docs.scipy.org/doc/scipy/reference/reference/index.html#scipy-api). If I click the same link again from the unformatted page, it tries to add a third `/reference` to the URL and then gives me a 404 error, since the page doesn't exist.

All of the API reference docs are still there, but they're only accessible by either web-searching the specific subpackage/function or else using a link from somewhere else in the docs, such as [this list from the tutorial introduction](https://docs.scipy.org/doc/scipy/reference/tutorial/general.html#scipy-organization) (which is what I've currently bookmarked instead of the missing title page).

### Reproducing Code Example

```python
n/a
```

### Error message

```shell
n/a
```

### SciPy/NumPy/Python version information

n/a

**Comment by tupui** [comment]
Thank you for reporting @jacione. I will close it as we are tracking this in #14267
