### ISSUE TITLE
BUG: Tippett’s and Pearson’s method for combine_pvalues are not monotonous

### ISSUE THREAD

**Issue by Wrzlprmft** [scipy/scipy#15373]
### Describe your issue.

Something is wrong with the methods `pearson` and `tippett` for `scipy.stats.combine_pvalues`. They should be monotonically increasing with all components of the input, yet they are monotonically decreasing. At first glance, the output seems to be 1 − _p_ when it should be _p._ It’s also straightforward to compute that Tippett’s method for an input of (½,½) should yield _p_ = ¾ but it does not.

@rlucas7 IIUC, you should know best about this.

### Reproducing Code Example

```python
import numpy as np
from scipy.stats import combine_pvalues

n = 5
ps = np.linspace(0.1,0.9,5)

for method in ("pearson","tippett"):
	combined_ps = [
			combine_pvalues( np.full(n,p), method )[1]
			for p in ps
		]
	assert np.all( np.diff(combined_ps) >= 0 )

assert combine_pvalues([0.5,0.5],method="tippett") == 0.75
```

### Error message

All assertions fail.

### SciPy/NumPy/Python version information

1.6.3 1.19.5 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by chrisb83** [comment]
According to https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.combine_pvalues.html, the "meta"-p-value of Tippet's method is `min(p_1, ..., p_N)`, Pearson's approach is `-2 sum_i log(1-p_i)`, see e.g., Heard, N. and Rubin-Delanchey, P. “Choosing between methods of combining p-values.” Biometrika 105.1 (2018): 239-246.

Why do you think the p-value should be 0.75 if method='tippett`?

**Comment by steppi** [comment]
@chrisb83 What I learned as Tippet's defines meta-p-value as `1 - (1 - min(p_1, ..., p_N))^N`. This is also the definition used by R's [Tippet's Method Package](https://search.r-project.org/CRAN/refmans/poolr/html/tippett.html), which cites the same 1931 book as the paper by Heard and Rubin-Delanchey.

Defined as above, the Tippet's meta-p-value is the probability of observing a minimum p-value among the N at least as small, assuming that the N p-values were generated iid from U(0, 1) (the uniform distribution with support [0 ,1]). It's possible that there were multiple methods discussed in Tippet's 1931 book, but I think it's more likely that this actually is a mistake.

**Comment by steppi** [comment]
Curiously, Heard and Rubin-Delanchy worked out that their version of Tippet's method is unsound, but didn't put together that they have had the incorrect formula.

From [page 6 ](https://arxiv.org/pdf/1707.06897.pdf).

![image](https://user-images.githubusercontent.com/1953382/149042312-1b34b483-4bb1-4348-a899-4400e54eb655.png)

**Comment by steppi** [comment]
@Wrzlprmft thanks for pointing these out. I checked and your observation that SciPy’s Pearson p-value is actually 1 - p turns out to be correct. See for instance [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2771157/).

**Comment by josef-pkt** [comment]
clearly a bug

monotonicity in tippet goes in the wrong direction

Based on the example I guess the `1 - (1 - min(p_1, ..., p_N))^N` transformation is the same as `beta.cdf(min(pvalues), 1, n)`
with cdf instead of sf as steppi pointed out.

`1 - (1 - min(p_1, ..., p_N))^N`  looks like the Sidak multiple testing correction to me applied to the smallest p-value

> I think it's more likely that this actually is a mistake in Heard and Rubin-Delanchy's paper, since I don't think there's any good theoretical justification for taking the min of the p-values as the meta-p-value.

They don't do that, at least not skimming the definitions
min(pvalues) is the "test statistic", the actual p-value needs to come from the distribution of the test statistic, which is almost right in scipy except that's the complement, not left tail.

(based on a bit of fast skimming of small parts of articles)

**Comment by steppi** [comment]
> They don't do that, at least not skimming the definitions
> min(pvalues) is the "test statistic", the actual p-value needs to come from the distribution of the test statistic, which is almost right in scipy except that's the complement, not left tail.

You are correct. I skimmed too carelessly :)
