### ISSUE TITLE
BUG: linalg: f2py warnings when building

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#15386]
### Describe your issue.

When building scipy `1.9.0.dev0+1241.f916acd` with numpy 1.22.0, the following warnings are generated by f2py:
```
[...]
INFO:   adding 'build/src.linux-x86_64-3.10/build/src.linux-x86_64-3.10/scipy/linalg/_fblas-f2pywrappers.f' to sources.
INFO: building extension "scipy.linalg._flapack" sources
INFO: from_template:> build/src.linux-x86_64-3.10/scipy/linalg/flapack.pyf
INFO: f2py options: []
INFO: f2py: build/src.linux-x86_64-3.10/scipy/linalg/flapack.pyf
/home/warren/py3.10.1/lib/python3.10/site-packages/numpy/f2py/symbolic.py:1508: ExprWarning: fromstring: treating "'A'||" as symbol (original=(compute_v?(2*(*range=='A'||(*range=='I' && iu-il+1==n)?n:0)):0))
  ewarn(
/home/warren/py3.10.1/lib/python3.10/site-packages/numpy/f2py/symbolic.py:1508: ExprWarning: fromstring: treating "'I' && iu" as symbol (original=(compute_v?(2*(*range=='A'||(*range=='I' && iu-il+1==n)?n:0)):0))
  ewarn(
/home/warren/py3.10.1/lib/python3.10/site-packages/numpy/f2py/symbolic.py:1508: ExprWarning: fromstring: treating '(jobt == 0)&&' as symbol (original=((jobt == 0)&&(jobu == 3)?0:m))
  ewarn(
/home/warren/py3.10.1/lib/python3.10/site-packages/numpy/f2py/symbolic.py:1508: ExprWarning: fromstring: treating '(jobt == 0)&&' as symbol (original=((jobt == 0)&&(jobu == 3)?0:(jobu == 1?m:n)))
  ewarn(
/home/warren/py3.10.1/lib/python3.10/site-packages/numpy/f2py/symbolic.py:1508: ExprWarning: fromstring: treating '(jobt == 0)&&' as symbol (original=((jobt == 0)&&(jobv == 3)?0:ldv))
  ewarn(
/home/warren/py3.10.1/lib/python3.10/site-packages/numpy/f2py/symbolic.py:1508: ExprWarning: fromstring: treating '(jobt == 0)&&' as symbol (original=((jobt == 0)&&(jobv == 3)?0:n))
  ewarn(
Reading fortran codes...
	Reading file 'build/src.linux-x86_64-3.10/scipy/linalg/flapack.pyf' (format:free)
Post-processing...
[...]
```

The warnings appear to be triggered with expressions in `dimension` attributes in a `.pyf` that use a mix of comparisons, logical operators and ternary operators.  E.g.
```
    integer intent(out),dimension((compute_v?(2*(*range=='A'||(*range=='I' && iu-il+1==n)?n:0)):0)),depend(n,iu,il,compute_v,range) :: isuppz

```

Further down the build log, we have similar warnings when building `specfun`:
```
[...]
creating build/src.linux-x86_64-3.10/scipy/special
INFO: f2py options: ['--no-wrap-functions']
INFO: f2py: scipy/special/specfun.pyf
/home/warren/py3.10.1/lib/python3.10/site-packages/numpy/f2py/symbolic.py:1508: ExprWarning: fromstring: treating '(int)v' as symbol (original=(int)v+1)
  ewarn(
/home/warren/py3.10.1/lib/python3.10/site-packages/numpy/f2py/symbolic.py:1508: ExprWarning: fromstring: treating '(int)v' as symbol (original=abs((int)v)+2)
  ewarn(
Reading fortran codes...
	Reading file 'scipy/special/specfun.pyf' (format:free)
Post-processing...
[...]
```
The relevant code in `specfun.pyf` is
```
            double precision intent(out),depend(v),dimension((int)v+1) :: vl
            double precision intent(out),depend(v),dimension((int)v+1) :: dl
```

I don't know if the warnings are harmless, and I don't know if this is something that we should fix in our `.pyf` files, or if this is a f2py bug (ping @pearu).  Whatever the cause, it would be nice to eliminate these warnings.

### SciPy/NumPy/Python version information

1.9.0.dev0+1241.f916acd 1.22.0 sys.version_info(major=3, minor=10, micro=1, releaselevel='final', serial=0)

**Comment by ilayn** [comment]
The first seems like a new one which wasn't there @melissawm might know about it too. I can take a look since I know where it is coming from.

**Comment by pearu** [comment]
The warnings should be harmless, no need to fix the `.pyf` files, and this is not a bug but a set of missing features in f2py:
1. support parsing C logical expressions
2. support parsing C relational expressions
3. support parsing C casting operations

Background: starting from numpy version 1.22, f2py uses a symbolic parser for dimension expressions to improve the quality of estimating the sizes of array arguments. The "treating ... as symbol" warnings can be ignored and these become resolved once the missing features listed above are implemented in the f2py expression parser.

**Comment by pearu** [comment]
Btw, to eliminate these warnings, theoretically (read: untested), the following might work:
```
export PYTHONWARNINGS="ignore::ExprWarning"
```
To refine this idea, see https://docs.python.org/3/library/warnings.html#describing-warning-filters

**Comment by WarrenWeckesser** [comment]
Thanks @pearu.  I created a [numpy issue](https://github.com/numpy/numpy/issues/20771), and I'm closing this issue.
