### ISSUE TITLE
BUG: scipy.optimize.linear_sum_assignment matchings are not 1-to-1

### ISSUE THREAD

**Issue by zburq** [scipy/scipy#15383]
### Describe your issue.

**Using SciPy version 1.7.1.**  `scipy.optimize.linear_sum_assignment` 

**Expected behaviour:** 
With a symmetric matrix `M`  containing pairwise distance between elements of a set `S`, and diagonal zeros replaced with a large number, `scipy.optimize.linear_sum_assignment(M)` should produce a set of matched pairs from `M` so that the sum of distances within pairs is minimised.  This is equivalent to a minimum distance non-bipartite matching of `S`.  The output of the function contains each pair twice, e.g., `(1, 7)` and then reversed `(7, 1)`. 

If `M` is small, this works. For large `M` (50 or larger), I start to see non-symmetric matchings. E.g., 1 matches 7, `(1, 7)` , but 7 matches 11: `(7, 11)` and 11 matches back to 1: `(11, 1)`. These situations seem to form cycles (see image below).

**Code to reproduce issue:** https://github.com/zburq/scipy_linear_sum_assignment_issue

<img width="568" alt="image" src="https://user-images.githubusercontent.com/6443451/148643676-b9877a27-eb5c-4741-9778-fa87a1c3d230.png">

### Reproducing Code Example

```python
https://github.com/zburq/scipy_linear_sum_assignment_issue
```

### Error message

```shell
NA
```

### SciPy/NumPy/Python version information

1.7.1

**Comment by pmla** [comment]
It looks like you are trying to find the minimum weight matching in a general graph. Scipy does not have a solver for this problem.

`linear_sum_assignment` finds the minimum weight matching in bipartite graphs only. There is no requirement that the matching be symmetric for this problem.

**Comment by zburq** [comment]
Understood. You're right. Thank you.
