### ISSUE TITLE
ENH: Randomized Quasi Monte Carlo

### ISSUE THREAD

**Issue by dmetivie** [scipy/scipy#15398]
### Is your feature request related to a problem? Please describe.

I want to generate many randomized realizations of a low discrepancy sequence thanks to `scipy.stat.qmc`. I only know this way, which directly provide a randomized sequence:

    from scipy.stats import qmc
    ld = qmc.Sobol(d=2, scramble=True)
    r = ld.random_base2(m=10)

But if I run 

    r = ld_deterministic.random_base2(m=10)
twice I get 

    The balance properties of Sobol' points require n to be a power of 2. 2048 points have been previously generated, then: n=2048+2**10=3072. If you still want to do this, the function 'Sobol.random()' can be used.

It seems like using `Sobol.random()` is discouraged from the doc.
I asked [here](https://stackoverflow.com/questions/69855127/scipy-stats-qmc-how-to-do-multiple-randomized-quasi-monte-carlo) but got no answers.

### Describe the solution you'd like.

What I would like (and it should be faster) is to first get 

    ld = qmc.Sobol(d=2, scramble=False)

then to generate like a 1000 scrambling (or other randomization method) from this initial series. 
It avoids having to regenerate the Sobol sequence for each sample and just do scrambling.

More generally, from any sequence `x` I would like a function that apply the various randomization scheme (Owen scramble, shift, etc.) like `rqmc_x = randomize(x)`.

**Comment by tupui** [comment]
Hi @dmetivie, thanks for reporting.

As the warning suggests, Sobol' is a sequence meaning that there is a link between with the previous samples. You have to respect the properties of 2**m. It's perfectly fine to use `Sobol.random()` if you understand how to use it, this is why we created `random_base2` which prints a warning if you try to do something that would break the properties of the sequence. Remember that with Sobol' you cannot skip 10 points and then sample 5 or do arbitrary things like that. If you do that, you will not get the convergence rate guaranteed by Sobol'.

In your case, what you want to do is to reset the sequence between the draws. A new draw will be different from the previous one if `scramble=True`. Another way (using a non scrambled sequence for instance) is to sample 2**k and skip the first 2**(k-1) points then you can sample 2**n with n<k-1.

To your suggestion, having some general functions to scramble or randomize a sample is wanted.

**Comment by dmetivie** [comment]
Thanks for the response.
That is how I am currently doing: I reset the sequence every time.

I am not sure to understand why the scrambling/randomization functionality is not implemented independently of the sequence. 
Unfortunately, this seems to be the case of every QMC package I have seen.

The code for randomization must already be written somewhere if the package is doing it, it should just be a matter of extracting the right part of the function into an independent one, no?
Unfortunately, I am not a Python expert, and I am not sure to understand the relevant part of the source code provided on the GitHub.

**Comment by tupui** [comment]
Randomizing is different than scrambling. Randomization is mostly shuffling or adding something to an existing sample. While scrambling is done during the sampling. It depends on the method but what we have here is a scrambling on some vector at the initialization.

**Comment by tupui** [comment]
On a simple randomization for Sobol', from a personal correspondence with Pierre L'Ecuyer:

> If one insists on deterministic Sobol' points, then I believe the best thing to do is shift all coordinates of all points by 1/(2n).   In case n = 2^k, then each one-dimensional projection corresponds to the midpoint (integration) rule: there is one point centered in each interval (i/n, (i+1)/n), i=0,.., n-1.  And all linear functions are integrated exactly.  Regardless of the direction numbers.   Without this shift, the points are asymmetric w.r. to 1/2 and this is not good.

**Comment by dmetivie** [comment]
> Randomizing is different than scrambling. Randomization is mostly shuffling or adding something to an existing sample. While scrambling is done during the sampling. It depends on the method but what we have here is a scrambling on some vector at the initialization.

I am not sure to agree (or I miss completely misunderstood what you meant by scrambling).
 See for example [this survey](https://www.iro.umontreal.ca/~lecuyer/myftp/papers/rqmc-survey-2002.pdf) on page 29 and after (whole section 5: Randomizations) by L’Ecuyer and Lemieux. 
They define randomization methods, including scrambling independently of the sequence 
Of course, some randomization are better suited for some sequences like Sobol' and scrambling or lattice and shift.
Doing the scrambling as you generate the sequence, like you are saying, is probably faster?

About your quote, you mean that if you don't know the sequence length `n` in advance, then simple shift is not appropriate?
Probably. In my case `n` is known so that is not an issue.

**Comment by tupui** [comment]
I have a correction to make to the documentation of Sobol' regarding scrambling (PR are welcomed if you want). It's saying that it's doing NUS (Owen) although the code is doing LMS.

Again from personal conversation with Pierre L'Ecuyer:
> I had a look at your code and it seems that what you have implemented is the left linear matrix scramble (LMS) from Matousek and not the nested uniform scrambling (NUS) which was proposed by Art Owen.  For the difference between the two, see on page 5 in here:   http://www.iro.umontreal.ca/~lecuyer/myftp/papers/mcqmc20latnet.pdf   According to my experience, the LMS that you have implemented typically performs as well as the NUS and is significantly faster.  

and 

>Note: In my SSJ Java library (package hups here:  https://github.com/umontreal-simul/ssj), several types of randomizations are offered for Sobol points:  Owen's scrambling (NUS), various linear (matrix) scrambles (LMS), digital random shift, and also adding a baker transform or an antithetic transform afterward.  LMS is much faster than NUS and in the majority of applications it performs as well in terms of variance.  Exceptions include simple very smooth integrands such as polynomials, where NUS gives a faster convergence rate than LMS.

So yes, it's fast and performs well. I also did extensive analysis with Sergei Kuckerenko (see [here](https://www.researchgate.net/publication/354089921_Construction_and_comparison_of_high-dimensional_Sobol'_sequence_generators)) to check the performance of the generator.

> About your quote, you mean that if you don't know the sequence length `n` in advance, then simple shift is not appropriate?

Yes exactly. There might be ways to work this around, but I don't know about it nor read any convergence study. But since Sobol' already constrains a lot on the sampling size, it's not really an issue I would say. I would never recommend Sobol' for cases where you need to be flexible with `n`.

**Comment by dmetivie** [comment]
Thank you for your answer. 
I see the doc has been updated to specify the randomization method LMS+DS.
Are you considering adding a NUS method like the one implemented here `https://artowen.su.domains/code/rsobol.R`?
(I translated it into Julia but I do not know enough Python to contribute to an efficient code).

To answer my original question, it seemed like doing 
```
import numpy as np
from scipy.stats import qmc

N = 2**16
M = 1000
sampler = qmc.Sobol(d=40, seed=10)
for i in range(1,M):
    sample = sampler.random(N)
```
produce independent RQMC sample exactly as I wanted.

However, it seems like there is a bug: some point of the sequence are zeros!
```
N = 2**16
M = 1000
sampler = qmc.Sobol(d=40, seed=10)
for i in range(1,M):
    sample = sampler.random(N)
    # count zeros in array
    n_zeros = np.count_nonzero(sample==0)
    # display the count of zeros
    if n_zeros != 0:
        print("i = ", i,"nb zeros = ", n_zeros)
i =  77 nb zeros =  1
i =  364 nb zeros =  1
i =  652 nb zeros =  1
i =  853 nb zeros =  1
```

**Comment by tupui** [comment]
> Thank you for your answer. I see the doc has been updated to specify the randomization method LMS+DS. Are you considering adding a NUS method like the one implemented here `https://artowen.su.domains/code/rsobol.R`? (I translated it into Julia but I do not know enough Python to contribute to an efficient code).

I don't plan to do it myself but would be happy to review/help. Pierre L'Ecuyer expressed some interest at some point but does not have the time right now. If you can make some Python out of your Julia we could have a look even if it's not optimised.

> To answer my original question, it seemed like doing
> 
> ```
> import numpy as np
> from scipy.stats import qmc
> 
> N = 2**16
> M = 1000
> sampler = qmc.Sobol(d=40, seed=10)
> for i in range(1,M):
>     sample = sampler.random(N)
> ```
> 
> produce independent RQMC sample exactly as I wanted.

It produces samples, but remember that it's "wrong". The second sample will not respect the properties of a sequence of Sobol'. Cf what I said above.

> However, it seems like there is a bug: some point of the sequence are zeros!

It's not a bug, it's ok to have zeros in the sequence. Having 1s is more problematic and can rarely happen due to rounding errors.

**Comment by dmetivie** [comment]
> I don't plan to do it myself (mostly because LMS+DS works great and according to Pierre L'Ecuyer and Art Owen is similar in terms of quality to NUS) but would be happy to review/help. Pierre L'Ecuyer expressed some interest at some point but does not have the time right now. If you can make some Python out of your Julia we could have a look even if it's not optimised.

Ok, I'll try something when I have a bit more time.

> > To answer my original question, it seemed like doing
> > ```
> > import numpy as np
> > from scipy.stats import qmc
> > 
> > N = 2**16
> > M = 1000
> > sampler = qmc.Sobol(d=40, seed=10)
> > for i in range(1,M):
> >     sample = sampler.random(N)
> > ```
> > produce independent RQMC sample exactly as I wanted.
> 
> It produces samples, but remember that it's "wrong". The third sample will not respect the properties of a sequence of Sobol'. Cf what I said above. You have also a nice message if you use instead `sampler.random_base2`.
> 
> Some more personal communication with Art Owen:
> 
> > This should be another thing to warn about.  If somebody gets 256 and then keeps adding 256 more points at a time, they are only going to get the plain Monte Carlo rate, probably with a somewhat better constant.  Sobol' warned about that and I wrote a followup paper.
> > So ... if the past points are 2^m then the only reasonable numbers of new points would be of the form 2^M-2^m for some M>m with M = m+1 being the most likely case. (Doubling the sample size.  Sometimes I jump to 4n or 8n or 16n.)
> > The warning could be:  Unless the additional points bring the cumulative sample size per scramble to a power of 2, Sobol' points will fail to have their desired balance properties.

Ok, I think I get it.
So the only way to do what I want is 
```
sample = np.zeros((M,N,d))
for i in range(0,M):
    sampler = qmc.Sobol(d=d)
    sample[i,:,: ] = sampler.random_base2(m)
```
where again I want `M` copies of a scrambled Sobol sequence of size `N=2**m` and dimension `d`.
At each draw, the sampler is reset to generate the first `N=2**m` randomized point of the Sobol sequence.

> > However, it seems like there is a bug: some point of the sequence are zeros!
> 
> It's not a bug, it's ok to have zeros in the sequence. Having 1s is more problematic and can rarely happen due to rounding errors.

I believe it is not ok to have zeros (especially "as often" as I observed them) in RQMC sequence. 
That is one of the point of randomization, it avoids every point with probability 1 because each point is uniformly distributed. 
Of course, in practice it is not with probability 1, but maybe something like `1/2**32`?
It is like a uniform random number generator, it never should return `0` (does it sometime in practice? I don't know).
When dealing with singular integrand this is unpleasant.

**Comment by tupui** [comment]
> Ok, I'll try something when I have a bit more time.

Great!

> Ok, I think I get it. So the only way to do what I want is
> 
> ```
> sample = np.zeros((M,N,d))
> for i in range(0,M):
>     sampler = qmc.Sobol(d=d)
>     sample[i,:,: ] = sampler.random_base2(m)
> ```
> 
> where again I want `M` copies of a scrambled Sobol sequence of size `N=2**m` and dimension `d`. At each draw, the sampler is reset to generate the first `N=2**m` randomized point of the Sobol sequence.

Yes this is one way to do it correctly.

> I believe it is not ok to have zeros (especially "as often" as I observed them) in RQMC sequence. That is one of the point of randomization, it avoids every point with probability 1 because each point is uniformly distributed. Of course, in practice it is not with probability 1, but maybe something like `1/2**32`?

The current probability is quite low. You have 2^16 points in 40 dim and you do this 1000 times and only get 4 zeros (p=1.5e-9 compared to 1/(2^30)=9e-10. Redo this K times and you might just get close to it.).

> It is like a uniform random number generator, it never should return `0` (does it sometime in practice? I don't know).

No, MC or (R)QMC generators are always advertised to sample from `[0, 1]^d` or `[0, 1)^d` (usually for (R)QMC). (R)QMC sequences always start with zero to be digital nets.

> When dealing with singular integrand this is unpleasant.

Sure, but this is case dependent. Some other applications love to have zeros. You can always rescale the samples to fit into desired bounds.

The convergence properties (mean and (spurious) variance of integrands) of this generator have been checked on a ton of functions (from Art Owen and Sergei Kucherenko mostly) so from that perspective it works as expected. So if there is an issue with some zeros, it would be very limited as it did not show up in all the tests we've done.

**Comment by dmetivie** [comment]
Thanks!
It makes sense. 
I think I can close the issue now.

**Comment by sdementen** [comment]
> > 
> > It's not a bug, it's ok to have zeros in the sequence. Having 1s is more problematic and can rarely happen due to rounding errors.
> 
> I believe it is not ok to have zeros (especially "as often" as I observed them) in RQMC sequence. That is one of the point of randomization, it avoids every point with probability 1 because each point is uniformly distributed. Of course, in practice it is not with probability 1, but maybe something like `1/2**32`? It is like a uniform random number generator, it never should return `0` (does it sometime in practice? I don't know). When dealing with singular integrand this is unpleasant.

As I generate the QMC to feed a normal.ppf, I need to ensure the QMC are strictly in the (0,1) interval.

What I do is to add 1/2**(bits+1) to the result with bits being the argument of Sobol. Is that a correct approach ?
If I generate 2**bits sample, then I will get a mean exactly equal to 0.5 (irrespective of bits)

**Comment by tupui** [comment]
>  I need to ensure the QMC are strictly in the (0,1) interval.


 @sdementen I am not sure I follow, the output of the QMC generator in SciPy ensure that samples are in [0, 1] or [0, 1).

**Comment by sdementen** [comment]
I want to generate QMC normal random variables. I transform a uniform
variable sample to a normal one by using the inverse cdf of the normal
distribution (ndtri in script). This function returns -inf when given 0.0
(and inf given 1.0). I must therefore ensure the uniform is in (0,1) which
I do by shifting by half of the less significant bit.
