### ISSUE TITLE
ENH: Avoid dense representation of sparse matrices

### ISSUE THREAD

**Issue by SultanOrazbayev** [scipy/scipy#15409]
### Is your feature request related to a problem? Please describe.

When converting sparse matrix representation there is a dense representation of the underlying data, see the following:

```python
import scipy.sparse as ss

data = [1]
i = [1089924553097310219]
j = [10]

b = ss.coo_matrix((data, (i, j)))

b.tocsr()
```

Running this will raise the following error:

```pytb
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
/var/folders/r0/yy240000gn/T/ipykernel_1391/3769887823.py in <module>
      7 b = ss.coo_matrix((data, (i, j)))
      8 
----> 9 b.tocsr()

~/env/lib/python3.10/site-packages/scipy/sparse/coo.py in tocsr(self, copy)
    400             col = self.col.astype(idx_dtype, copy=False)
    401 
--> 402             indptr = np.empty(M + 1, dtype=idx_dtype)
    403             indices = np.empty_like(col, dtype=idx_dtype)
    404             data = np.empty_like(self.data, dtype=upcast(self.dtype))

MemoryError: Unable to allocate 7.56 EiB for an array with shape (1089924553097310221,) and data type int64
```

### Describe the solution you'd like.

There might be a way of converting sparse matrix representations in a more memory efficient way.

### Additional context (e.g. screenshots, GIFs)

This is a somewhat relevant issue: https://github.com/scipy/scipy/issues/14674

**Comment by SultanOrazbayev** [comment]
Also, happy to collaborate on a PR, with some guidance.

**Comment by perimosocordiae** [comment]
This is a fundamental constraint of the CSR format: it stores an array of index offsets (`indptr`) for every row in the matrix, regardless of the sparsity pattern. Try converting to CSC format and you'll find we can handle large row indices just fine (at the cost of memory linear in the number of columns).

For matrices with very large row and column indices at the same time, COO format is likely your best choice.

**Comment by SultanOrazbayev** [comment]
Thank you for the clarification, but is there a scope to implement `b.getrow(0)` within COO without the intermediate CSR conversion? (right now it triggers the memory error)

**Comment by perimosocordiae** [comment]
You can manually work around it via `b.tocsc().getrow(0)`, or if you need more performance you could do:

```
mask = b.row == 0
values = b.data[mask]
indices = b.col[mask]
```

I agree that we should think about a specialization for the COO format here.
