### ISSUE TITLE
BUG: scipy.stats.fisher_exact strange interaction

### ISSUE THREAD

**Issue by ahelmstetter** [scipy/scipy#15412]
### Describe your issue.

Calling `scipy.stats.fisher_exact` has a strange side effect and is impacting subsequent function calls, specifically but not limited to rpy2 functionality.

In the provided code example, if `print(sp.fisher_exact(n))` is left commented out, the provided `R` function correctly prints the dimension of the input argument as `[1] 2 2` and the second element as `[1] 2`. However, if the line `print(sp.fisher_exact(n))` is actually run prior to the provided `R` function, the `R` function will print the second element of the input dimension as `NA`. 

Depending on whether `scipy.stats.fisher_exact` is called earlier in the script, this strange behavior/interaction breaks subsequent inline calls to `R`, including the `R` `fisher.test`.

Note this observed behavior is specific to `scipy.stats.fisher_exact` and does not for instance appear when calling `scipy.stats.chisquare`.

### Reproducing Code Example

```python
import numpy as np
from scipy import stats as sp
from rpy2 import robjects
import rpy2.robjects.numpy2ri
rpy2.robjects.numpy2ri.activate()

n = np.array( [[6, 2], [1, 12]] )

# commenting or uncommenting this line alters the behavior of what follows afterwards
print(sp.fisher_exact(n))


v = robjects.FloatVector([6, 1, 2, 4])
m = robjects.r['matrix'](v, nrow = 2)
robjects.r('''
        # create a function `f`
        fisher <- function(mat) {
            print(dim(mat))
            print(dim(mat)[2])
            # fisher.test(mat)
            return(TRUE)
        }
        ''')
    
r_fisher = robjects.globalenv['fisher']
r_fisher = robjects.r['fisher']
res = r_fisher(m)
```

### Error message

```shell
No error message, just un-understood behavior.
```

### SciPy/NumPy/Python version information

1.7.3 1.21.2 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by ahelmstetter** [comment]
@tupui thanks. I'll see if I can reproduce under a fresh environment/install and provide my procedural steps if I am successful.

**Comment by mdhaber** [comment]
@ahelmstetter any luck or shall we close this?

**Comment by mdhaber** [comment]
I'll go ahead and close this, but if you're able to reproduce it after a new install, let us know.
