### ISSUE TITLE
BUG: Rotation.from_matrix() function returning error using Scipy 1.7.2

### ISSUE THREAD

**Issue by TheDech** [scipy/scipy#15417]
### Describe your issue.

The Rotation.from_matrix() function is returning error messages using Scipy 1.7.2 but works fine using Scipy 1.5.2. Also tested without the as_quat() and still have the same error message.

### Reproducing Code Example

```python
from scipy.spatial.transform import Rotation as R

mat = [[ 0.96990875 -0.23643638 -0.05809357]
 [ 0.15001382  0.76828415 -0.62228235]
 [-0.19176255 -0.59484225 -0.78063424]]

quaternion = (R.from_matrix(mat)).as_quat()
```

### Error message

```shell
Traceback (most recent call last):
  File "o3d_realsense.py", line 88, in <module>
    quaternion = R.from_matrix(mat)
  File "rotation.pyx", line 736, in scipy.spatial.transform.rotation.Rotation.from_matrix
  File "stringsource", line 658, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
```

### SciPy/NumPy/Python version information

1.7.2 1.21.4 sys.version_info(major=3, minor=7, micro=12, releaselevel='final', serial=0)

**Comment by tylerjereddy** [comment]
It works "ok" for me with SciPy `1.7.2` and NumPy `1.21.4`. Note that your example isn't executable so I'm assuming `mat` can just be a list of lists (probably a pasted `repr` of a NumPy array?). Regardless of whether I make `mat` a `list` or `np.array()`, the code still works for me locally.

**Comment by tylerjereddy** [comment]
Are you building from source? Platform? Alpha version of Cython or something?

**Comment by TheDech** [comment]
Thank you for your quick reply.
I installed it through `pip`. The matrix is a rotation matrix retrieved from Open3D using the same code for both 1.7.2 and 1.5.2.

**Comment by tylerjereddy** [comment]
I've never used Open3D--can we construct the "rotation matrix" using NumPy alone? That might be useful for the reproducer. If not, maybe show how to construct it from Open3D at least. That might become a question of array/matrix subclasses or something like that.

**Comment by TheDech** [comment]
I followed the tutorial [here](http://www.open3d.org/docs/latest/tutorial/geometry/pointcloud.html#Bounding-volumes) and then used the code in the issue.
I will try again by using np.array but my concern is: do you obtain the same result for both versions?
Will update you as soon as possible.
Thank you!

**Comment by TheDech** [comment]
I try a quick fix
`quaternion = (R.from_matrix(np.array(mat))).as_quat()`
Adding `np.array` was not necessary in the 1.5.2, it seems like the matrix is not identified as is.
Let me know if you need any other information from my side.
