### ISSUE TITLE
ENH: Add `fatol` for scipy.optimize.ridder() 

### ISSUE THREAD

**Issue by tpstps** [scipy/scipy#15428]
### Describe your issue.

Hi,

I would like to use `scipy.optimize.ridder()` for a function of me.

I set the absolute tolerance to `1.` and expect that the resulting function call would be in the range `[-1.:+1.]`.

When looking at the second call to `ridder()`, I can see `5.000065000084806` as a result.

Did I make a mistake when calling `ridder()` or is something wrong with the result of it?

Thanks in advance!

### Reproducing Code Example

```python
import scipy.optimize as sco
import numpy as np
# import scipy

import sys, scipy, numpy;

print(scipy.__version__, numpy.__version__, sys.version_info)

amountOfCalls = 0


def myFunc(x):
    global amountOfCalls
    amountOfCalls += 1
    y = x ** 3 + x - 5
    return y


for xtol in [0.00001, 1., ]:
    amountOfCalls = 0
    xValue, root1_result = sco.ridder(myFunc, -1000, 1000, xtol=xtol, full_output=True, disp=True, )
    print('atol:', xtol, 'nullvalue:', myFunc(xValue), 'xValue:', xValue, 'amountOfCalls:', amountOfCalls)  # , ' '.join(str(root1_result).split('\n')))
```

### Error message

```shell
1.2.2 1.17.0 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
atol: 1e-05 nullvalue: 3.9394811365944804e-05 xValue: 1.515985217781899 amountOfCalls: 31
atol: 1.0 nullvalue: 5.000065000084806 xValue: 2.000004999994985 amountOfCalls: 13
```

### SciPy/NumPy/Python version information

1.2.2 1.17.0 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)

**Comment by AtsushiSakai** [comment]
The [ridder doc](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.ridder.html) says `xtol` is 
> The computed root x0 will satisfy np.allclose(x, x0, atol=xtol, rtol=rtol), where x is the exact root. The parameter must be nonnegative.

So, `xtol` means the tolerance for `x`, not for `f(x)`.
In your example, the root is 1.5, the range is [0.5, 2.5]. The solution 2.0 is included in the range.

**Comment by tupui** [comment]
I believe we can close the issue since it's more of a user question than a bug then.

**Comment by tpstps** [comment]
Hi,

I know that ridder is really an old, robust, and commonly used algorithm.

But I wonder why the users do not need what I assumed to be case.

From a user perspective: doesn't it make sense to look for the max absolute deviation from `f(x)` instead  from `x`?

**Comment by tupui** [comment]
AFAIK, for all our optimizers, the tolerance refers to the optimization variable, `x`.

**Comment by AtsushiSakai** [comment]
Actually some [`minimize`](http://scipy.github.io/devdocs/reference/optimize.minimize-neldermead.html) solvers have `fatol` option to set absolute error in `f(x)` between iterations that is acceptable for convergence.
But I'm not sure it is reasonable for root-finding solvers or not.

**Comment by tupui** [comment]
> Actually some [`minimize`](http://scipy.github.io/devdocs/reference/optimize.minimize-neldermead.html) solvers have `fatol` option to set absolute error in `f(x)` between iterations that is acceptable for convergence.
> But I'm not sure it is reasonable for root-finding solvers or not.

Indeed. In general it would be good to uniformize the way we want stopping criterion to function. We have per-function and per-iteration criteria and under this we have criteria on the input and solution. We can think about how to design this in a sensible way. I would not just add the feature without discussion.

**Comment by AtsushiSakai** [comment]
> I would not just add the feature without discussion.
I agree. I updated the issue title. Let's leave it and hear other opinions.

**Comment by mdhaber** [comment]
In gh-6379, I've suggested adding relative and absolute tolerances on `x` and `f(x)` for all scalar root finders. For other possibilities, we offer a `callback` interface.

**Comment by tupui** [comment]
Let's close this to keep track of a single issue: gh-6379 which has this info.
