### ISSUE TITLE
BUG: optimize: minimize: `ValueError` when `np.all(lb==ub)`

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#15433]
### Describe your issue.

In gh-13096, we fixed some problems in `minimize` when lower bounds equal upper bounds. However, when _all_ lower bounds equal upper bounds, there are no decision variables or bounds left, and we run into a `ValueError` in `old_bound_to_new`. 

I suspect that once we get past that some solvers would complain because there is no problem to be solved. One solution would be to detect the condition and produce an `OptimizeResult` before we dispatch to any solver, but it would require checking whether the other constraints are satisfied or not.

### Reproducing Code Example

```python
import numpy as np
from scipy.optimize import minimize

def f(x):
    return np.linalg.norm(x)

bounds = [(1, 1), (2, 2)]
x0 = (1, 2)
res = minimize(f, x0, bounds=bounds)
```

### Error message

```shell
runfile('C:/Users/matth/scipy/scipy/optimize/untitled1.py', wdir='C:/Users/matth/scipy/scipy/optimize', current_namespace=True)
Traceback (most recent call last):

  File "C:\Users\matth\scipy\scipy\optimize\untitled1.py", line 16, in <module>
    res = minimize(f, x0, bounds=bounds)

  File "C:\Users\matth\scipy\scipy\optimize\_minimize.py", line 688, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,

  File "C:\Users\matth\scipy\scipy\optimize\_lbfgsb_py.py", line 292, in _minimize_lbfgsb
    new_bounds = old_bound_to_new(bounds)

  File "C:\Users\matth\scipy\scipy\optimize\_constraints.py", line 358, in old_bound_to_new
    lb, ub = zip(*bounds)

ValueError: not enough values to unpack (expected 2, got 0)
```

### SciPy/NumPy/Python version information

1.9.0.dev0+1281.f6d08ab 1.21.2 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by andyfaff** [comment]
This could be done in minimize before dispatch to the individual solver.

**Comment by mdhaber** [comment]
Yes, that's what I suggested above, too.
