### ISSUE TITLE
ENH: `scipy.signal.cwt` : provide richer output

### ISSUE THREAD

**Issue by jerabaul29** [scipy/scipy#15435]
### Is your feature request related to a problem? Please describe.

When using cwt, the results are often plotted as a 2d pcolor or pcolormesh or similar; currently, cwt only returns the 2D array to be plotted, and the user has to figure out everything about the X and Y axis content.

### Describe the solution you'd like.

Change the return of cwt to provide, similar to for example scipy.signal.spectrogram, a triplet (f, t, cwt): frequency, time, cwt matrix.

### Describe alternatives you've considered.

The alternative I found so far is to use another package, for example it is possible to do the following in pywt

```
coef, freqs = pywt.cwt(x, np.arange(1, 50), 'morl',
                       sampling_period=sampling_period)
```

or in squeezepy:

```
Twxo, Wxo, *_ = squeezepy.ssq_cwt(xo)
```

but would be nice to have all in scipy

**Comment by NamamiShanker** [comment]
Hey @jerabaul29, the input signal's length is generally used for the time scale, and the input width parameter is used for the width scale. Can you please clarify how will receiving 'f' and 't' from the function will help?

**Comment by jerabaul29** [comment]
Currently the user has to do the scaling, sampling, definition of the "coordinate arrays", correctly, in order to generate the right time and width. This is potentially error prone. I think that it would be even better if this could be done directly by the function call, so that the user can "just" take the output of the function, and directly plug it in additional functions like pcolor, or plots, etc. See the examples above: pywt and squeezepy provide additional output variables that represent these scales :) .

**Comment by ev-br** [comment]
CWT is deprecated in scipy 1.12, along with the rest of the wavelet functionality. So, this enhancement request cannot be acted upon. Thank you @jerabaul29 regardless.
