### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by pauljurczak** [scipy/scipy#15434]
### Describe your issue.

Documentation search doesn't work.

### Reproducing Code Example

```python
Searching for `KDTree` (https://docs.scipy.org/doc/scipy/reference/search.html?q=KDTree) or any other query fails
```

### Error message

```shell
Not Found
The requested URL /doc/scipy/reference/search.html was not found on this server.

Apache/2.4.39 (Ubuntu) Server at docs.scipy.org Port 443
```

### SciPy/NumPy/Python version information

most current

**Comment by tupui** [comment]
Thank you @pauljurczak. This is a known issue tracked in #14267.
