### ISSUE TITLE
BUG: Documentation of stft misses the import statement for numpy

### ISSUE THREAD

**Issue by hoehnp** [scipy/scipy#15446]
### Describe your issue.

The sample code given for stft in the signal module misses the following line:
import numpy as np

### Reproducing Code Example

```python
from scipy import signal
import matplotlib.pyplot as plt
rng = np.random.default_rng()
```

### Error message

```shell
NameError: name 'np' is not defined
```

### SciPy/NumPy/Python version information

1.7.3 1.21.4 sys.version_info(major=3, minor=9, micro=9, releaselevel='final', serial=0)

**Comment by ilayn** [comment]
Have a look at https://github.com/scipy/scipy/issues/13049

**Comment by hoehnp** [comment]
@ilayn, thanks for the very quick response. Sorry I missed that issue. 
I was just looking for bugs related to stft and didn't expect it is a 
general issue. One can then probably also close my related PR.
