### ISSUE TITLE
Segfault in HiGHS code when building with Mingw-w64 on Windows

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#15456]
Observing this consistently in the Meson Windows CI:

```
......                                                                   [ 40%]
Windows fatal exception: access violation

Current thread 0x000009d8 (most recent call first):
  File "D:\a\scipy\scipy\build\Lib\site-packages\scipy\optimize\_linprog_highs.py", line 405 in _linprog_highs
  File "D:\a\scipy\scipy\build\Lib\site-packages\scipy\optimize\_linprog.py", line 640 in linprog
  File "D:\a\scipy\scipy\build\Lib\site-packages\scipy\optimize\tests\test_linprog.py", line 288 in test_choose_solver
  File "C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\_pytest\python.py", line 183 in pytest_pyfunc_call
...
  File "<string>", line 1 in <module>
..\build\Lib\site-packages\scipy\optimize\tests\test_linprog.py .
Error: Process completed with exit code 1.
```

Before the update to a newer version of HiGHS in gh-15217 all tests were passing with the same build config. It looks like there are more issues with Mingw in HiGHS and it's not tested/supported yet upstream: https://github.com/ERGO-Code/HiGHS/issues/625.

Cc @mckib2.

**Comment by mckib2** [comment]
Just getting back from travel, will hopefully have time this week to pull in latest HiGHS upstream and see if the fixes in https://github.com/ERGO-Code/HiGHS/pull/706 resolve this for us

**Comment by carlkl** [comment]
resolved with a small change in `parallel/HighsTaskExecutor` https://github.com/ERGO-Code/HiGHS/issues/625#issuecomment-1030883895.
@mckib2, should this patch go to https://github.com/scipy/HiGHS? Or simply update https://github.com/scipy/HiGHS to https://github.com/ERGO-Code/HiGHS/tree/61ac057a014573fbee609281320f8a396d13cd30 see https://github.com/ERGO-Code/HiGHS/issues/625#issuecomment-1031341811

**Comment by rgommers** [comment]
Awesome! I'd prefer just adding the patch that fixes the segfault to https://github.com/scipy/HiGHS, then ensure our Meson CI passes, then add that CI job to SciPy `main`. That way we can be confident we are pulling in another HiGHS issue with the next larger update.

**Comment by carlkl** [comment]
Applied: https://github.com/scipy/HiGHS/pull/56

**Comment by matthew-brett** [comment]
Thanks Carl!

**Comment by mckib2** [comment]
Yes, thank you @carlkl !
