### ISSUE TITLE
DOC: Documentation inaccuracy of scipy.interpolate.bisplev

### ISSUE THREAD

**Issue by kaigaox** [scipy/scipy#15458]
### Is your feature request related to a problem? Please describe.

Documentation for scipy.interpolate.bisplev at https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.bisplev.html should be improved. The implementation of bisplev in scipy does not only rely on **bisplev** of fitpack, it also relies on **parder** of fitpack when the order of derivative(s) of the evaluation is non-zero (i.e., dx /=0 or dy /= 0 in scipy's bisplev functon). 

### Describe the solution you'd like.

The documentation should be revised from 
**Based on BISPEV from FITPACK.**
to 
**Based on BISPEV and PARDER from FITPACK.**

**Comment by tupui** [comment]
Hi @kaigaox, thank you for reporting. We welcome contributions which seek to improve the documentation. Feel free to open a PR.

**Comment by j-bowhay** [comment]
Where is parder used?

**Comment by kaigaox** [comment]
> 

https://github.com/scipy/scipy/blob/8a64c938ddf1ae4c02a08d2c5e38daeb8d061d38/scipy/interpolate/src/_fitpackmodule.c#:~:text=int%20*)(wrk%20%2B%20lwrk)%3B-,if%20(nux%20%7C%7C%20nuy)%20%7B,%7D,-free(wa)%3B

**Comment by kaigaox** [comment]
> Where is parder used?

https://github.com/scipy/scipy/blob/8a64c938ddf1ae4c02a08d2c5e38daeb8d061d38/scipy/interpolate/src/_fitpackmodule.c

Line 221-228:
`    if (nux || nuy) {
        PARDER(tx, &nx, ty, &ny, c, &kx, &ky, &nux, &nuy, x, &mx, y, &my, z,
                wrk, &lwrk, iwrk, &kwrk, &ier);
    }
    else {
        BISPEV(tx, &nx, ty, &ny, c, &kx, &ky, x, &mx, y, &my, z, wrk, &lwrk,
                iwrk, &kwrk, &ier);
    }`
