### ISSUE TITLE
ConvexHull not working correctly

### ISSUE THREAD

**Issue by zi-yang-kang** [scipy/scipy#15468]
I want to plot a concave hull of a function, but have noticed that ConvexHull sometimes fails when this function is convex and decreasing. I've appended a minimum breaking example in which ConvexHull thinks that this function is already convex (which I inferred from `envelope` in the following code).

```from scipy.spatial import ConvexHull, convex_hull_plot_2d
import numpy as np
import matplotlib.pyplot as plt
import scipy.interpolate

R_GRID = np.arange(10, 11, 0.01)

def obj(r):
  return 43.45 + r - r ** 2 + 0.05 * r ** 3

points = np.array([R_GRID, obj(R_GRID)]).T
hull = ConvexHull(points)

envelope = points[hull.vertices,1]
envelope[1:] = envelope[1:][::-1]

x_arr = points[hull.vertices,0]
x_arr[1:] = x_arr[1:][::-1]

y_interp = scipy.interpolate.interp1d(x_arr, envelope)

plt.plot(R_GRID, obj(R_GRID))
plt.plot(R_GRID, y_interp(R_GRID))
plt.show()

**Comment by WarrenWeckesser** [comment]
I don't see how your code demonstrates a failure of `ConvexHull`.  If I remove all code related to `envelope` and interpolation, and use `scipy.spatial.convex_hull_plot_2d`, the figure looks correct.  E.g. this script
```
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial import ConvexHull, convex_hull_plot_2d

R_GRID = np.arange(10, 11, 0.01)

def obj(r):
  return 43.45 + r - r ** 2 + 0.05 * r ** 3

points = np.array([R_GRID, obj(R_GRID)]).T
hull = ConvexHull(points)

plot = convex_hull_plot_2d(hull)
plt.show()
```
produces this plot:

![Figure_1](https://user-images.githubusercontent.com/321463/150902139-b7f82984-d222-4bf2-abb1-96fd57ba0069.png)

**Comment by zi-yang-kang** [comment]
Thanks. For some reason I thought I'd ruled out problems with interpolation, but evidently that is not the case here. I'll open a new issue if something else crops up.
