### ISSUE TITLE
LinearOperator unnecessary in lobpcg

### ISSUE THREAD

**Issue by lobpcg** [scipy/scipy#15461]
### Is your feature request related to a problem? Please describe.

https://github.com/scipy/scipy/tree/main/scipy/sparse/linalg/_eigen/lobpcg currently requires that the matrix-free input is in the LinearOperator format, although it is unnecessary and a basic function handle should work equally well. 
Additionally, internally the lobpcg solver turns the matrix input into the LinearOperator format, which is also an overkill - should just use a function. 

### Describe the solution you'd like.

Remove the check for LinearOperator format input and thus allow a simple function handle as an input. 

Replace the internal matrix converter into the LinearOperator with a simple function, removing the unnecessary dependence.

**Comment by rgommers** [comment]
fixed by gh-16320
