### ISSUE TITLE
ENH:  `skewnorm.cdf` is very slow. Consider a much more efficient approach

### ISSUE THREAD

**Issue by zoj613** [scipy/scipy#15473]
### Describe your issue.

`skewnorm.cdf` is very inefficient. Looking at the implementation in 
https://github.com/scipy/scipy/blob/3bdce7aee0c5be623f83e98a16b4ad1af2ac66d7/scipy/stats/_continuous_distns.py#L7067-L7078

It appears that a numerical integration of pdf is being done.

### Reproducing Code Example

Here is a minimal example
```python

In [10]: import numpy as np

In [11]: from scipy.stats import skewnorm

In [12]: rng = np.random.default_rng(1)

In [13]: x = rng.uniform(-5, 5, size=5000)

In [14]: %timeit skewnorm.cdf(x, 1.5)
2.06 s ± 9.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

It takes over 2 seconds just to compute the cdf for a small array of 5k elements.

It turns out that there is a simple and much more efficient approach to computing the cdf that makes use of a bivariate standard normal cdf [1]. This approach produces identical accuracy to scipy's current implementation for the values I tested it in and the authors claim it is accurate for precision within 1e-20. The also provide 2 other algorithms for the far left and far-right tails. The bivariate normal can use scipy's `multivarite_normal` or the routines described in [2].

PS: I tried writing a rather naive implementation of the bivariate normal based approach on [1] and could reproduce the values from the example above in less than 20 milliseconds.

References
----------
[1] https://alecospapadopoulos.files.wordpress.com/2020/04/evaluating-sn-cdf-full-work-final.pdf
[2] https://www.ams.org/journals/mcom/1978-32-141/S0025-5718-1978-0461849-9/S0025-5718-1978-0461849-9.pdf

### SciPy/NumPy/Python version information

1.6.2 1.20.3 sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
Sounds like a good idea! Do you plan to submit a PR?

**Comment by zoj613** [comment]
> Sounds like a good idea! Do you plan to submit a PR?

I'm reluctant to jump on this in case someone else with more time to invest is interested. I still have #13665 waiting for me to finish it.

**Comment by mdhaber** [comment]
Willing to post your rough implementation here? : ) No judgment!

**Comment by europeanplaice** [comment]
Is this what [1] https://alecospapadopoulos.files.wordpress.com/2020/04/evaluating-sn-cdf-full-work-final.pdf
shows?
```python
  def _cdf_single(self, x, *args):
      from scipy.special import owens_t
      _a, _b = self._get_support(*args)
      return _norm_cdf(x) - 2 * owens_t(x, _a)
```

**Comment by zoj613** [comment]
> Is this what [1] [alecospapadopoulos.files.wordpress.com/2020/04/evaluating-sn-cdf-full-work-final.pdf](https://alecospapadopoulos.files.wordpress.com/2020/04/evaluating-sn-cdf-full-work-final.pdf) shows?
> 
> ```python
>   def _cdf_single(self, x, *args):
>       from scipy.special import owens_t
>       _a, _b = self._get_support(*args)
>       return _norm_cdf(x) - 2 * owens_t(x, _a)
> ```

The accuracy of this approach is very bad at the tails as it involves subtraction. The authors mention this in the paper as well.

**Comment by WarrenWeckesser** [comment]
See https://github.com/scipy/scipy/pull/8473 for a discussion of the problem with `_norm_cdf(x) - 2 * owens_t(x, _a)`.
