### ISSUE TITLE
ENH: Update documentation on scipy.signal.butter regarding the correctness of the term "order"

### ISSUE THREAD

**Issue by jake-is-ESD-protected** [scipy/scipy#15492]
IMO the term "order" in the docs for `scipy.signal.butter` is misleading in case of bandpass-filters. Discussion is located [here](https://dsp.stackexchange.com/questions/81285/sanity-check-does-python-or-i-not-understand-sos-matrices)

Based on documentation [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.butter.html)

**Comment by tupui** [comment]
Hi @jake-is-ESD-protected, thank you for reporting. Documentation improvement are always welcome. Would you like to make a PR?

**Comment by jake-is-ESD-protected** [comment]
@tupui Where do i edit the documentation after cloning?

**Comment by tupui** [comment]
@jake-is-ESD-protected I suppose this is the documentation here that you want to update https://github.com/scipy/scipy/blob/v1.7.1/scipy/signal/filter_design.py#L2846-L2957

**Comment by jake-is-ESD-protected** [comment]
PR is located [here](https://github.com/scipy/scipy/pull/15496)
