### ISSUE TITLE
BUG: Incorrect error message in multivariate_normal

### ISSUE THREAD

**Issue by IgnacioHeredia** [scipy/scipy#15508]
### Describe your issue.

Hi everyone,

I'm getting an incorrect (?) error message when using multivariate normal. Here is my minimally reproducible example.

```python
from scipy.stats import multivariate_normal

cov = [[1., 0.],
       [1., 1.]]

f = multivariate_normal(cov=cov)
```
Output:
```bash
LinAlgError: singular matrix
```

This matrix has a non-zero determinant, is invertible, has rank 2, etc. It is clearly not a singular matrix, so I don't get where this error is coming from. 

As covariance matrices should (symmetric) positive definite (and this matrix is not), I guess the error in this case should be either:

* `not symmetric` or,
* `LinAlgError: Matrix is not positive definite`

Especially because one could use the `allow_singular=True` flag and `multivariate_normal` won't raise an error despite the cov matrix not being (symmetric) positive definite.

Thanks!

Ignacio

### Reproducing Code Example

```python
from scipy.stats import multivariate_normal

cov = [[1., 0.],
       [1., 1.]]

f = multivariate_normal(cov=cov)
```

### Error message

```shell
LinAlgError: singular matrix
```

### SciPy/NumPy/Python version information

1.6.2

**Comment by NamamiShanker** [comment]
Hey @AtsushiSakai @IgnacioHeredia, I have submitted a PR to fix this error message. Please review it.

**Comment by AtsushiSakai** [comment]
I'm not sure this is a bug or not, because a correct covariance matrix is always symmetric and positive semi-definite, so I think passing a non-symmetric matrix is a user error.

**Comment by mdhaber** [comment]
@AtsushiSakai @NamamiShanker I glanced at gh-15579 but did not follow closely. If this error occurs for other non-symmetric matrices, why not just change the error message to "matrix is not symmetric positive definite" (or "semidefinite when `allow_singular` is true)? It seems like that is a simple change that would make the error message correct in strictly more cases than it is now.

**Comment by AtsushiSakai** [comment]
@mdhaber I’m sorry I don’t remember this discussion well… But i agree better error massage is always great.
