### ISSUE TITLE
BUG: Link to mailing list seems broken

### ISSUE THREAD

**Issue by Sbozzolo** [scipy/scipy#15517]
### Describe your issue.

The link "mailing list" in https://scipy.github.io/devdocs/index.html returns a 404 error.

### Reproducing Code Example

```python
.
```

### Error message

```shell
.
```

### SciPy/NumPy/Python version information

Website

**Comment by tupui** [comment]
Thanks @Sbozzolo. I actually opened a PR to fix it earlier today.
