### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by henrypinkard** [scipy/scipy#15518]
### Describe your issue.

The description of the gamma distribution is wrong [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gamma.html).

Under **Notes** it says the gamma PDF takes one parameter (_a_). This is only referring to the special case where the scale parameter theta is set to 0.

See the [wikipedia description](https://en.wikipedia.org/wiki/Gamma_distribution#Characterization_using_shape_k_and_scale_%CE%B8)

### Reproducing Code Example

```python
NA
```

### Error message

```shell
NA
```

### SciPy/NumPy/Python version information

1.7.1 manual

**Comment by rkern** [comment]
The `Notes` talks about this starting with "Gamma distributions are sometimes parameterized with two variables..."

**Comment by henrypinkard** [comment]
Nonetheless, its a very confusing bit a of documentation to introduce the general concept with a specialized case like that.

The API makes this more confusing, since `gamma.pdf(x, a, b)` does not correspond to either of the two common parameterizations of the Gamma distribution, but instead you have to write `gamma.pdf(x, a, scale=b)`. 

I think this could be made a lot more clear if the documentation specifically addressed how to relate this function to the common parameterizations.

**Comment by rkern** [comment]
We have made the architectural design decision to make all of the distributions have consistent `loc` and `scale` parameters. This is [discussed at length in the Users Guide](https://docs.scipy.org/doc/scipy/tutorial/stats.html#shifting-and-scaling). We can't recapitulate that explanation in each distribution's docstring. However, the full `Notes` section does explicitly address how this relates to common parameterizations for this distribution.
