### ISSUE TITLE
BUG: Released documentation unreachable

### ISSUE THREAD

**Issue by maxnoe** [scipy/scipy#15545]
It seems the documentation page is down?

https://docs.scipy.org/doc/scipy/

**Comment by bjodah** [comment]
Yes, I've been using google to directly search the docs of the dev-snapshot, i.e. search using  the `site:` specifier:

`pchip integrator site:scipy.github.io/devdocs/`

**Comment by tylerjereddy** [comment]
Can you try again now? It works for me.

For the record, this is the current set of web server config adjustments I've made--more robust suggestions are welcome:
https://github.com/tylerjereddy/htaccess_backup/pull/1

**Comment by maxnoe** [comment]
I am still getting a blank page for the link above, it seems redirects are not working as intended.

The link now seems to be https://docs.scipy.org/doc/scipy/html-scipyorg/, which is working, but e.g. getting the intersphinx directory does not:

https://docs.scipy.org/doc/scipy/html-scipyorg/objects.inv

Where it works with 1.8.0 explicitly:

https://docs.scipy.org/doc/scipy-1.8.0/html-scipyorg/objects.inv

**Comment by tylerjereddy** [comment]
There should be an automatic redirect for `https://docs.scipy.org/doc/scipy/` now

**Comment by matthewfeickert** [comment]
> There should be an automatic redirect for `https://docs.scipy.org/doc/scipy/` now

> There's a symlink from `scipy` to the latest release dir `scipy-1.8.0`, but there is also a need to remap `scipy-1.8.0/reference` to `scipy-1.8.0/html-scipyorg/reference`.

Thanks for the responsive work here @tylerjereddy. If we're still seeing

```
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://docs.scipy.org/doc/scipy/reference/objects.inv' not readable due to ValueError: unknown or unsupported inventory version: ValueError('invalid inventory header: ')
```

in CI jobs (https://github.com/scikit-hep/pyhf/issues/1766), even though the redirect is already in effect, is the recommendation to just be patient and let things finish rolling out? Or is this indicative of further problems?

**Comment by tylerjereddy** [comment]
@matthewfeickert We're still having problems I think--I can't quite get the redirect working yet, but there are some suggestions in https://github.com/tylerjereddy/htaccess_backup/pull/1

So far, the suggestions that I have tried for `.htaccess` changes have had other side effects, but hopefully we'll find something that works eventually.

I tried messing around with stuff like `scipy/reference/objects.inv` to `scipy/html-scipyorg/objects.inv` (the new location), but no success yet.

**Comment by matthewfeickert** [comment]
Thanks for the update in general and also thanks for the work that you're doing to address this problem.

> I tried messing around with stuff like `scipy/reference/objects.inv` to `scipy/html-scipyorg/objects.inv` (the new location), but no success yet.

Ah, this is good to know in general. Even if things aren't working with `https://docs.scipy.org/doc/scipy/html-scipyorg/objects.inv` quite yet this is still good to know that people should be updating their Sphinx `conf.py`s to use the new address to avoid the redirect anyway. Thanks for this!

**Comment by pllim** [comment]
FWIW, `scipy.fft` intersphinx used to work but no longer. The page is up though at https://docs.scipy.org/doc/scipy-1.8.0/html-scipyorg/reference/fft.html but I get this: `py:obj reference target not found: scipy.fft`

**Comment by matthewfeickert** [comment]
> It seems to work as well as our best previous solution, but I don't yet see an advantage for accessing i.e., `https://docs.scipy.org/doc/scipy/html-scipyorg/objects.inv`?

Ah, indeed, now we get this nice warning telling use what to use. :+1: 

```
intersphinx inventory has moved: https://docs.scipy.org/doc/scipy/reference/objects.inv -> https://docs.scipy.org/doc/scipy/objects.inv
```

Thanks!

**Comment by maxnoe** [comment]
I think we can close this, everything seems to be working from my side.
