### ISSUE TITLE
BUG: ImportError: cannot import name 'F_onewayResult' from 'scipy.stats'

### ISSUE THREAD

**Issue by ParticularMiner** [scipy/scipy#15549]
### Describe your issue.

Hi,

Not sure what's going on here:

```cmd
> python -c "import scipy.stats; print('PASS')"
PASS

> python -c "from scipy.stats import F_onewayResult; print('PASS')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'F_onewayResult' from 'scipy.stats' (C:\Users\runner\anaconda3\envs\...\lib\site-packages\scipy\stats\__init__.py)
```

However, if I modify https://github.com/scipy/scipy/blob/63472fd76eadf2c97b9aaf6f55ffc6ddce4b39b6/scipy/stats/__init__.py#L453
by adding the line:
```python
from ._stats_py import F_onewayResult
from ._stats_py import *
```
I get a pass for both commands:
```cmd
> python -c "import scipy.stats; print('PASS')"
PASS

> python -c "from scipy.stats import F_onewayResult; print('PASS')"
PASS
```

Thanks in advance for your help!

### Reproducing Code Example

```python
from scipy.stats import F_onewayResult


print('PASS')
```

### Error message

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'F_onewayResult' from 'scipy.stats' (C:\Users\runner\anaconda3\envs\...\lib\site-packages\scipy\stats\__init__.py)
```

### SciPy/NumPy/Python version information

1.8.0 1.20.2 sys.version_info(major=3, minor=9, micro=10, releaselevel='final', serial=0)

**Comment by ParticularMiner** [comment]
Please note that prior to `scipy` v1.8.0, the above import could be executed in the following way:
```python
from scipy.stats.stats import F_onewayResult
```
which is now deprecated.   The associated warning in the current version directs one to use instead:
```python
from scipy.stats import F_onewayResult
```
which produces an `ImportError`.

**Comment by rgommers** [comment]
Thanks for the report @ParticularMiner. The discussion in gh-13118 is relevant. I think for now we do not want these objects in the public API. I'll close this as a duplicate, because `F_onewayResult` is just one instance of the general pattern discussed in gh-13118.
