### ISSUE TITLE
BUG: np.matmul(scipy.sparse.csr_array, numpy array) throws an error

### ISSUE THREAD

**Issue by mfmullen** [scipy/scipy#15547]
### Describe your issue.

An error is thrown when multiplying a scipy.sparse.csr_array by a dense numpy array with appropriate dimensions using matmul. Using @ works.

Using Numpy 1.22.1, Scipy 1.8.0

### Reproducing Code Example

```python
from scipy.sparse import csr_array
import numpy
a = csr_array(numpy.eye(4))
b = numpy.random.randn(4,1)
c_working = a @ b
c_alsoWorking = a.dot(b)
c_notWorking = numpy.matmul(a,b)
```

### Error message

```shell
ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?, k),(k, m?)->(n?,m?) requires 1)
```

### SciPy/NumPy/Python version information

1.8.0 1.22.1 sys.version_info(major=3, minor=10, micro=0, releaselevel='final', serial=0)

**Comment by perimosocordiae** [comment]
This is working as intended, as far as I'm aware. `np.matmul` is the ufunc version of matrix multiplication, which is lower level than the normal `dot` or `@` APIs. If you need code that works with both sparse and dense inputs, use one of those instead.

Note that scalar multiplication is also not supported by `np.matmul`.
