### ISSUE TITLE
MAINT: stats: deprecating non-numeric array support in `stats.mode`

### ISSUE THREAD

**Issue by tirthasheshpatel** [scipy/scipy#15551]
`stats.mode` currently supports non-numeric arrays (like string and object arrays):

```py
import numpy as np
from scipy.stats import mode

x = np.array(['a', 'a', 'b', 'c'])  # array of strings
res = mode(x)  # ModeResult(mode='a', count=2)

x = x.astype('object')
res = mode(x)  # ModeResult(mode='a', count=2)
```

but it isn't consistent when different Python objects and `nan`s are present:

It throws when objects don't support comparison operators (see https://github.com/scipy/scipy/issues/9815#issuecomment-1013834361):

```py
a = np.array([10, True, 'hello', 10], dtype='object')
res = mode(a)  # TypeError: '<' not supported between instances of 'str' and 'int'
```

but works when `nan` values are present in the object array:

```py
a = np.array([10, True, 'hello', 10, np.nan], dtype='object')
res = mode(a)  # ModeResult(mode=10, count=2)
```

gh-15516 fixes these issues but also raises more questions: should `nan`s be handled specially or just be treated as any other Python objects? Would `nan_policy` make any sense for object arrays if we choose the latter?

This also makes it difficult to add the  [`_axis_nan_policy_factory`](https://github.com/scipy/scipy/blob/63472fd76eadf2c97b9aaf6f55ffc6ddce4b39b6/scipy/stats/_axis_nan_policy.py#L271) decorator for consistent `nan_policy` handling and `axis` tuple support (see https://github.com/scipy/scipy/pull/15516#issuecomment-1030153330). Since most stats functions only support numerical arrays, deprecating support for non-numeric arrays from `stats.mode` would make it more consistent and allow us to add the `_axis_nan_policy_factory` decorator easily.

**Comment by tupui** [comment]
I am 👍 to do this. Better to deprecate than having undefined or complex behaviour like that. User can pre-process their data before passing it to this function.

**Comment by mdhaber** [comment]
Playing devil's advocate, BTW.

> User can pre-process their data before passing it to this function.

What does this mean if the user really wants to take the mode of a set of strings or mixed objects?

**Comment by mdhaber** [comment]
Good call, and it looks like [it does](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mode.html).

**Comment by chrisb83** [comment]
I am also supportive of your proposal to deprecate support for non-numeric arrays

**Comment by mdhaber** [comment]
Thanks all! @tirthasheshpatel, would you like to submit a PR for the deprecation and send a message about it to the mailing list?

**Comment by tirthasheshpatel** [comment]
Thanks everyone for the feedback! I will create a PR and send a mail to the mailing list.
