### ISSUE TITLE
DOC: Formulas for chndtr and chndtrix

### ISSUE THREAD

**Issue by SebastianJHM** [scipy/scipy#15556]
Is possible know the mathematical definition of this function?
scipy.special.chndtr
scipy.special.chndtrix

Also this functions:
scipy.special.nctdtr
scipy.special.nctdtrit

**Comment by melissawm** [comment]
Following the code, according to [this comment in cdfchn.f](https://github.com/scipy/scipy/blob/fa6b307ba4b46a0a7e5f956831a68223cc7a5a39/scipy/special/cdflib/cdfchn.f#L77), the formula for the Non-Central Chi-Square Distribution Function (which is [scipy.special.chndtr](https://scipy.github.io/devdocs/reference/generated/scipy.special.chndtr.html#scipy.special.chndtr)) is 

```
\[
P(\Chi^{\prime 2} \vert \nu, \lambda) = \sum_{j=0}^{\infty} e^{-\lambda /2} \frac{(\lambda /2)^j}{j!} P(\Chi^{\prime 2} \vert \nu + 2j)
\]
```
where `$\lambda \geq 0$`is termed the non-centrality parameter:

![Screenshot_20220208_154111](https://user-images.githubusercontent.com/3949932/153054460-355c31d3-3d6f-45ee-8c4d-d2765fbcdb51.png)

The `chndtrix` function, [according to the docs](https://scipy.github.io/devdocs/reference/generated/scipy.special.chndtrix.html#scipy.special.chndtrix) is the Inverse to [chndtr](https://scipy.github.io/devdocs/reference/generated/scipy.special.chndtr.html#scipy.special.chndtr) vs x. 

I think it would be really useful to add the complete formula to the documentation for both functions. @SebastianJHM maybe you can edit the title for this issue, to read "DOC: Formulas for chndtr and chndtrix" or something similar that makes the issue clearer. Thanks!

**Comment by SebastianJHM** [comment]
@melissawm thank you for the answer and the recomendations.

**Comment by tupui** [comment]
@SebastianJHM would you like to make a PR?

**Comment by SebastianJHM** [comment]
@tupuiin the case of scipy.special.chndtrix I know the definition, but in the case scipy.special.chndtrix I don´t. This is my question, if there is a mathematical definition of this function or if scipy solve it using a different method like find the root. The same whith scipy.special.nctdtr and the inverse scipy.special.ncfdtri

**Comment by k-styles** [comment]
@melissawm @tupui Instead of writing all the 8 chi-distribution functions, wouldn't it be better to provide wiki links for all of them?

**Comment by tupui** [comment]
> @melissawm @tupui Instead of writing all the 8 chi-distribution functions, wouldn't it be better to provide wiki links for all of them?

Not really as links have a tendency to change as opposed to maths 😉

**Comment by k-styles** [comment]
Alright then, I'll would like to make a PR soon for the same.

**Comment by j-bowhay** [comment]
@SebastianJHM For the inverse it is just doing a search see https://github.com/scipy/scipy/blob/fa6b307ba4b46a0a7e5f956831a68223cc7a5a39/scipy/special/cdflib/cdfchn.f#L81

```
Computation of other parameters involve a search for a value that
produces  the desired  value  of P.   The search relies  on  the
monotinicity of P with the other parameter.
```

**Comment by rgommers** [comment]
`chndtr` formula was added. The second half of this issue was `nctdtr`, the formula for that is (according to Wikipedia):

<img width="413" alt="image" src="https://user-images.githubusercontent.com/98330/158594653-89df5e45-9755-480d-99af-14346d640819.png">

That seems overly complicated to add as LaTeX and is easy enough to look up on Wikipedia, so I'd say we're done here indeed.

**Comment by j-bowhay** [comment]
@rgommers I agree this seems reasonable to be as the exact implementation by page 532  of Johnson, Kotz,  Balakrishnan, Coninuous Univariate Distributions, Vol 2, 2nd Edition.  Wiley (1995) which is quite complicated:
![image](https://user-images.githubusercontent.com/60778417/158680017-9cefdb44-5e58-427e-a53c-94aad9dfd856.png)
