### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by toncho11** [scipy/scipy#15562]
### Describe your issue.

Hi 

I can not execute:
cdist(XA, XB, 'mahalanobis', VI=None)
or
cdist(XA, XB, 'mahalanobis', VI=Vi_m)

### Reproducing Code Example

```python
import numpy as np
from scipy.spatial.distance import cdist

#from numpy.random.mtrand import dirichlet
#rray =  dirichlet([1] * 400).reshape(20,20)
array = np.random.randint(10, size=(200,200))

V = np.cov(array.T)
IV_m = np.linalg.inv(V)
print(cdist(array,array,'mahalanobis',IV=IV_m))
```

### Error message

```shell
File "C:\Work\python38\lib\site-packages\scipy\spatial\distance.py", line 1672, in __call__
    cdist_fn(XA, XB, dm, **kwargs)

TypeError: cdist_mahalanobis_double_wrap() takes at most 4 arguments (5 given)
```

### SciPy/NumPy/Python version information

1.7.3 1.19.0 sys.version_info(major=3, minor=8, micro=0, releaselevel='final', serial=0)

**Comment by melissawm** [comment]
I believe the fourth argument you are trying to use is `VI` - and not `IV` ([documentation for cdist](https://scipy.github.io/devdocs/reference/generated/scipy.spatial.distance.cdist.html)):

```
VI : array_like The inverse of the covariance matrix for Mahalanobis. Default: inv(cov(vstack([XA, XB].T))).T
```
