### ISSUE TITLE
BUG: `scipy.spatial.transform.rotation`, wrong deprecation or missing `Rotation` in `scipy.spatial`

### ISSUE THREAD

**Issue by Alexboiboi** [scipy/scipy#15572]
### Describe your issue.

With the new `scipy=1.8.0` release, when importing `Rotation` from `scipy.spatial.transform.rotation` , a new deprecation message states:

```
DeprecationWarning: Please use `Rotation` from the `scipy.spatial` namespace, the `scipy.spatial.transform.rotation` namespace is deprecated.
  from scipy.spatial.transform.rotation import Rotation
```

Problem:

There is no `Rotation` in the `scipy.spatial` namespace.

### Reproducing Code Example

```python
from scipy.spatial import Rotation
```

### Error message

```shell
cannot import name 'Rotation' from 'scipy.spatial'
```
```


### SciPy/NumPy/Python version information

1.8.0 1.20.3 sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)

**Comment by swallan** [comment]
It's possible the error message is incorrect. This pr (gh-14923) deprecated the `spatial.transform.rotation` namespace, but you can still import `Rotation` from `transform`. 

It looks like this is where `Rotation` is actually located if you need it now: 

`from scipy.spatial.transform import Rotation`

**Comment by tupui** [comment]
I think the message is actually telling it right: `from scipy.spatial.transform.rotation import Rotation` maybe a non needed `rotation` but otherwise it's correct.

**Comment by swallan** [comment]
I suppose the message is technically correct, since Rotation is in the transform submodule of the spatial namespace. I do think the warning message is a bit vague since it's not entirely clear that it is the `.rotation` rather than `.transform.rotation` that is to be depricated.

**Comment by tupui** [comment]
Oh right, I misread it. Agreed we should change this.
