### ISSUE TITLE
BUG: scipy.special.factorialk docstring inconsistent with behaviour

### ISSUE THREAD

**Issue by j-bowhay** [scipy/scipy#15589]
### Describe your issue.

The docstring for scipy.special.factorialk states: Calculate multifactorial. If n < 0, the return value is 0. However the code actually returns 0 if `n < 1 - k` else 1 if  `n <= 0`

### Reproducing Code Example

```python
>>> factorialk(-5,1)
0
>>> factorialk(-1,3)
1
```

### Error message

```shell
None
```

### SciPy/NumPy/Python version information

1.9.0.dev0+1479.321a18f 1.21.2 sys.version_info(major=3, minor=8, micro=12, releaselevel='final', serial=0)

**Comment by AtsushiSakai** [comment]
I think `scipy.special.factorial2` has same issue:
https://github.com/scipy/scipy/blob/b5d8bab88af61d61de09641243848df63380a67f/scipy/special/_basic.py#L2418
https://github.com/scipy/scipy/blob/b5d8bab88af61d61de09641243848df63380a67f/scipy/special/_basic.py#L2440-L2443

**Comment by AtsushiSakai** [comment]
I'm not sure this behavior inconsistency is intended or not.
```
In [44]: [scipy.special.factorial(i, exact=True) for i in [0.0, -0.5, -1.0, -1.5]]
Out[44]: [1, 0, 0, 0]

In [45]: [scipy.special.factorialk(i, 1, exact=True) for i in [0.0, -0.5, -1.0, -1.5]]
Out[45]: [1, 0, 0, 0]

In [43]: [scipy.special.factorial2(i, exact=True) for i in [0.0, -0.5, -1.0, -1.5]]
Out[43]: [1, 1, 1, 0]

In [42]: [scipy.special.factorialk(i, 2, exact=True) for i in [0.0, -0.5, -1.0, -1.5]]
Out[42]: [1, 1, 1, 0]
```
