### ISSUE TITLE
BUG: scipy FTBFS on sh4 debian port

### ISSUE THREAD

**Issue by bigon** [scipy/scipy#15584]
### Describe your issue.

Currently, scipy FTBFS (Fails To Build From Source) on the SH4 debian port: https://buildd.debian.org/status/fetch.php?pkg=scipy&arch=sh4&ver=1.7.3-2&stamp=1644622573&raw=0

### Reproducing Code Example

```python
See current released code of version 1.7.3
```

### Error message

```shell
sh4-linux-gnu-gcc: scipy/special/_test_round.c
scipy/special/_test_round.c: In function ‘__pyx_pf_5scipy_7special_11_test_round_have_fenv’:
scipy/special/_test_round.c:2213:30: error: ‘FE_UPWARD’ undeclared (first use in this function)
 2213 |     __pyx_t_1 = ((fesetround(FE_UPWARD) != 0) != 0);
      |                              ^~~~~~~~~
scipy/special/_test_round.c:2213:30: note: each undeclared identifier is reported only once for each function it appears in
scipy/special/_test_round.c:2241:30: error: ‘FE_DOWNWARD’ undeclared (first use in this function); did you mean ‘FP_INT_DOWNWARD’?
 2241 |     __pyx_t_1 = ((fesetround(FE_DOWNWARD) != 0) != 0);
      |                              ^~~~~~~~~~~
      |                              FP_INT_DOWNWARD
scipy/special/_test_round.c: In function ‘__pyx_pf_5scipy_7special_11_test_round_4test_add_round’:
scipy/special/_test_round.c:2767:37: error: ‘FE_UPWARD’ undeclared (first use in this function)
 2767 |         __pyx_v_status = fesetround(FE_UPWARD);
      |                                     ^~~~~~~~~
scipy/special/_test_round.c:2825:37: error: ‘FE_DOWNWARD’ undeclared (first use in this function); did you mean ‘FP_INT_DOWNWARD’?
 2825 |         __pyx_v_status = fesetround(FE_DOWNWARD);
      |                                     ^~~~~~~~~~~
      |                                     FP_INT_DOWNWARD
```
```


### SciPy/NumPy/Python version information

1.7.3

**Comment by tupui** [comment]
Hi @bigon, thanks for reporting. Did you try to build 1.7.2 and 1.8? Do you have the same issue? Which instructions are you following to build SciPy?

Not sure what could be happening. Everything seems to be there. `_round.h` is in the `setup.py` and defines both `FE_DOWNWARD` and `FE_UPWARD`.

**Comment by bigon** [comment]
Hello,

SciPy actually never has never build on debian sh4 architecture: https://buildd.debian.org/status/logs.php?pkg=scipy&arch=sh4

The way it's built is in the [debian/rules file](https://salsa.debian.org/python-team/packages/scipy/-/blob/master/debian/rules)

**Comment by tupui** [comment]
Did you open an issue on Debian side?

**Comment by rgommers** [comment]
> Quickly looking on google, it seems that it's a difference of the architecture itself, for example: https://sourceware.org/pipermail/libc-alpha/2012-May/031608.html

So that link says that `FE_UPWARD` and `FE_DOWNWARD` were removed. Our `scipy/special/_round.h` header contains:
```C
#if __STDC_VERSION__ >= 199901L
/* We have C99 */
#include <fenv.h>
#else

int fesetround(int round)
{
    return -1;
}

int fegetround()
{
    return -1;
}

#define FE_UPWARD -1
#define FE_DOWNWARD -1

#endif
```
So what is likely happening is that ` __STDC_VERSION__ >= 199901L` is true _and_ the SH4 platform doesn't correctly implement everything that is needed for that. This could be fixed on the SciPy side by conditional compilation to check for the presence of these macros. However this really is an SH4 bug and is going to affect other projects as well. So my preferred solution is for Debian to carry a patch here like:
```C
...
#define FE_UPWARD -1
#define FE_DOWNWARD -1

#endif

/* SH4 is not C99 compliant, see https://github.com/scipy/scipy/issues/15584 */
#ifndef FE_UPWARD
#define FE_UPWARD -1
#endif
#ifndef FE_DOWNWARD
#define FE_DOWNWARD -1
#endif
```

**Comment by bigon** [comment]
I've opened a bug in debian for this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1007769

**Comment by rgommers** [comment]
This was fixed upstream, see linked thread above and patch in https://salsa.debian.org/python-team/packages/scipy/-/commit/9c6b9d8639bc5801ef4a88769ee23c5c75ce91cf

Closing, thanks @bigon
