### ISSUE TITLE
DEP: Remove `scipy.misc` submodule 

### ISSUE THREAD

**Issue by AnirudhDagar** [scipy/scipy#15608]
Currently `scipy.misc` only serves for a handful of useful functions and some dataset functions. With the new submodule `scipy.datasets` to be introduced in #15607 we can essentially remove the `misc` submodule.

Currently it is home for the following 5 functions.

Method | Description
-- | --
[central_diff_weights](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.central_diff_weights.html#scipy.misc.central_diff_weights) | Return weights for an Np-point central derivative.
[derivative](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.derivative.html#scipy.misc.derivative) | Find the nth derivative of a function at a point.
[ascent](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.ascent.html#scipy.misc.ascent) | Get an 8-bit grayscale bit-depth, 512 x 512 derived image for easy use in demos
[face](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.face.html#scipy.misc.face) | Get a 1024 x 768, color image of a raccoon face.
[electrocardiogram](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.electrocardiogram.html#scipy.misc.electrocardiogram) | Load an electrocardiogram as an example for a 1-D signal.

The last 3 functions are datasets that can now live in the `scipy.datasets` submodule and we should deprecate these over a couple of cycles.

I wanted to open up this issue to particularly discuss the other two functions i.e `central_diff_weights` and `derivative`.
Which submodule should they move to? Should we slowly phase them out deprecating them now and probably remove them completely in a future version? I found that internally in SciPy we only have one such instance:

https://github.com/scipy/scipy/blob/821f62242c2c0b4e1e96af476a1293859439e47b/scipy/stats/_distn_infrastructure.py#L30

The question is if people really use these two methods. A quick stackoverflow and google search gave a few results for the `scipy.misc.derivative` but almost no discussion or usage around `scipy.misc.central_diff_weights`.

I feel `derivative` can be moved to the `integrate` submodule as it seems like a useful method. For `central_diff_weights` we can simply remove it.

cc @rgommers

**Comment by tupui** [comment]
Thanks @AnirudhDagar. Could you move all details from your PR here as well (Pooch is not mentioned here for instance)? I think it would be easier to discuss both the new module and the accompanying deprecations in a single place.

I like the idea and having a `misc` module was not clear (bad name). We just need to write down somewhere what is the vision for this module. If we start to offload datasets, it opens the door to adding anything, hence a clear policy would be needed.

**Comment by rgommers** [comment]
Thanks @AnirudhDagar!

> Could you move all details from your PR here as well (Pooch is not mentioned here for instance)? I think it would be easier to discuss both the new module and the accompanying deprecations in a single place.

Please don't mix everything. Introducing `scipy.datasets` and deprecating `scipy.misc` are related but very much independent topics/solutions. We can do one without the other.

**Comment by rgommers** [comment]
> I feel `derivative` can be moved to the `integrate` submodule as it seems like a useful method. 

It would be good to search for related functions and issues here. For example, gh-14946 is relevant here: `approx_derivative` may be more useful/powerful than `derivative`.

> For `central_diff_weights` we can simply remove it.

Also relevant for both functions: history on adding more numerical derivative functionality (e.g., gh-2035). I think we don't want to do that anymore at this point. So deprecating `central_diff_weights` as it is not used much and there are better alternatives makes sense I'd think.

**Comment by rgommers** [comment]
xref the mailing list thread for this deprecation: https://mail.python.org/archives/list/scipy-dev@python.org/thread/AACMUJES2D3F24QWSQNOBVIYBOUZD2QX/
