### ISSUE TITLE
BUG: error in sparse/linalg/_eigen/arpack/arpack.py

### ISSUE THREAD

**Issue by OulanB** [scipy/scipy#15612]
### Describe your issue.

When modifying this file to use MUMPS solver, it seems to me that the line # 1304 in 
def eigs(A, k=6, M=None, sigma=None, which='LM', v0=None,
         ncv=None, maxiter=None, tol=0, return_eigenvectors=True,
         Minv=None, OPinv=None, OPpart=None):

#1304                Minv_matvec = get_inv_matvec(M, hermitian=True, tol=tol)

should be 

#1304                Minv_matvec = get_inv_matvec(M, hermitian=False, tol=tol)

as we have the general problem to solve here.

### Reproducing Code Example

```python
no code needed
```

### Error message

```shell
no error message needed
```

### SciPy/NumPy/Python version information

scipy 1.8.0

**Comment by ogauthe** [comment]
According to `eigs` documentation, `M` has to be hermitian, so I think this is fine. The flag `hermitian` is only used to speed-up a transpose in `_fast_spmatrix_to_csc`.

As far as I understand the function there is no issue here, `M` is not `A`.

**Comment by OulanB** [comment]
ogauthe is right, sorry for the mistake.
