### ISSUE TITLE
ENH: stats: all multivariate distributions should be freezable

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#15617]
### Is your feature request related to a problem? Please describe.

All univariate and most multivariate distributions can be frozen, e.g.
```python3
import numpy as np
from scipy.stats import multivariate_normal
rv = multivariate_normal(mean=[1, 2], cov=np.eye(2), allow_singular=False)
rv.rvs(size=10)
```
`ortho_group`, `unitary_group`, and `random_correlation` cannot be frozen.

### Describe the solution you'd like.

The `__call__` methods of `ortho_group`, `unitary_group`, and `random_correlation` should be implemented as for the other multivariate distributions. 

### Describe alternatives you've considered.

It would be even better if the multivariate distributions could inherit freezability from `multi_rv_generic`, but perhaps that is part of a larger issue of having a more complete `multi_rv_generic`.

### Additional context (e.g. screenshots, GIFs)

See gh-13103

**Comment by NamamiShanker** [comment]
Hi @mdhaber, do we need to create frozen class objects for these distributions and add the `__call__` function, which will accept the parameters and return a frozen class object?

**Comment by mdhaber** [comment]
Yes, we could follow the example of other distributions.
(Alternatively, we could try to bake this behavior into the superclass.)

**Comment by NamamiShanker** [comment]
Okay, can I work on this issue? I can implement frozen classes of these distributions and add tests.

Parallelly, I will think of some way to bake this behaviour into a superclass. Have you thought of something how we could implement this?

**Comment by mdhaber** [comment]
Let's start with just freezing individually. And let's start with just one of them. We'll build up some experience and then maybe we can think about generalizing.

**Comment by NamamiShanker** [comment]
Hey @mdhaber, I have started on this. I added freezability to ortho_group distribution in #15653.

**Comment by NamamiShanker** [comment]
Hey @mdhaber, I have added a PR for `unitary_group` distribution in #15671
