### ISSUE TITLE
ENH: Build wheels for musllinux

### ISSUE THREAD

**Issue by amw** [scipy/scipy#15628]
### Is your feature request related to a problem? Please describe.

Currently installing `scipy` on linux distributions using musl (e.g. Alpine) requires compiling from source. [PEP 656](https://www.python.org/dev/peps/pep-0656/) added `musllinux` platform tag to allow distributing compiled wheels for these distributions. There are packages already taking advantage of this and I think `scipy` would be a great candidate given how long it takes to compile. Distributions like Alpine are very popular in the container world because of their relatively small size.

There's also related issue for `numpy`:
https://github.com/numpy/numpy/issues/20089

### Describe the solution you'd like.

Build `musllinux` wheels.

**Comment by tupui** [comment]
Interesting take on Alpine. In the end, there are other issues than package support. https://pythonspeed.com/articles/alpine-docker-python/

**Comment by amw** [comment]
The premise of that article is exactly that Alpine is missing Python binary wheels. The article at the end says:

> An update: [PEP 656](https://www.python.org/dev/peps/pep-0656/) is under discussion as of April 2021, and would eventually lead to pip and PyPI supporting wheels for Alpine. If package maintainers then start uploading Alpine wheels, using Alpine images won’t be slow anymore.

Do you see other issues than this?

**Comment by amw** [comment]
Not sure about the other runtime issues the article mentions. For what it's worth I am already using scipy on Alpine and it seems to be working fine beside the dead slow image building time.

**Comment by rgommers** [comment]
Yes, the prerequisites are:
- NumPy to have `musllinux` wheels
- SciPy having moving to `cibuildwheel`
Then we'll probably add them, provided the extra CI is maintainable enough.

**Comment by tgross35** [comment]
For completeness, the numpy musl work is here https://github.com/numpy/numpy/pull/21200

**Comment by mattip** [comment]
I would think the appeal of musl linux is to have a smaller footprint, but doesn't getting numpy and scipy into the mix kind of defeat that purpose? Then the difference between a 4mb base image (debian) and a 500mb base image (alpine) is dwarfed by the size of python + numpy + scipy, no?

**Comment by tupui** [comment]
Yep, that the premise from the article I linked. Unless you put in a lot of effort to clean the image, you will not gain much with all that's needed to build/run SciPy, NumPy and the thing you are actually doing.

**Comment by mattip** [comment]
@amw OK, thanks for the data.

**Comment by rgommers** [comment]
It's starting to look to me like `x86_64` and `aarch64` `musllinux` wheels are reasonable to add. There's a fair amount of demand, and it's likely to continue growing. And the help the NumPy team is getting with both the `cibuildwheel` migration and now adding `musllinux` is nice. Let's first see how NumPy fares, but this shouldn't be too onerous.

**Comment by andyfaff** [comment]
This issue should be closed by #16842, as soon as there are numpy wheels available for musllinux.

**Comment by andyfaff** [comment]
We would also need the OpenBLAS toolchain to be updated for musllinux

**Comment by rgommers** [comment]
> We would also need the OpenBLAS toolchain to be updated for musllinux

That was done, see:
- https://github.com/MacPython/openblas-libs/pull/73
- https://anaconda.org/multibuild-wheels-staging/openblas-libs/files

**Comment by rgommers** [comment]
NumPy PR is close but still in progress: https://github.com/numpy/numpy/pull/21200

**Comment by andyfaff** [comment]
I've been playing around with building scipy in alpine today, in a docker image. I've created a CI run for musllinux on my fork. I'll ask scipy-dev if it's worthwhile adding.

**Comment by andyfaff** [comment]
`musllinux_x86_64` wheels for scipy and numpy are now available from https://anaconda.org/scipy-wheels-nightly. There is still a discussion to be had on releasing them to PyPI, so the wheels remain 'unofficial' for now. 

The presence of nightly wheels does make it easier for downstream projects in CI.

numpy and scipy also have `musllinux_x86_64` entries in their CI matrices.

**Comment by amw** [comment]
This is great progress, but when I said "build wheels for musllinux" in the title I meant "Publish musllinux wheels to PyPI". I'm going to open a new issue 🙂
