### ISSUE TITLE
ENH: Support broadcasting over many covariances for `multivariate_normal.cdf`

### ISSUE THREAD

**Issue by zoj613** [scipy/scipy#15627]
### Is your feature request related to a problem? Please describe.

I am currently trying to compute the standard bivariate normal cdf using multiple covariance matrices constructed from an array of correlation coefficient values.
```python
		x = np.random.rand(20, 2)
		a = np.random.rand(20)
        corr = - a / np.sqrt(1 + a**2)
        cdf = np.asarray(
            [
				2 * multivariate_normal.cdf(x, cov=((1, c), (c, 1)))
                for c in corr
            ]
        )
```

### Describe the solution you'd like.

This approach is obviously slow since it loops over the correlation coefficients just to generate the bivariate cdf's for each. Is there a way to use broadcasting over the covariance parameter and eliminate the need for this loop? I tried creating a 3d array of covariances and passed that to `multivariate_normal` but that didn't work. Any workaround that could be much faster than what I have?

### Describe alternatives you've considered.

I've considered just implementing the technique described here: https://arxiv.org/abs/1004.3616, which looks like it could be vectorizable if I could convert the c++ implementation to numpy. But this approach could take some time to get right and potentially be buggy. I would prefer just using the existing scipy function.

**Comment by mdhaber** [comment]
Thanks @zoj613. This issue is generalized and tracked in gh-16278.
