### ISSUE TITLE
BUG:  DOCS incorrect `source` link on docs

### ISSUE THREAD

**Issue by swallan** [scipy/scipy#15636]
### Describe your issue.

When I click `source` on [mannwhitenyu](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mannwhitneyu.html), <img width="882" alt="Screen Shot 2022-02-21 at 9 34 21 PM" src="https://user-images.githubusercontent.com/44255917/155069433-c894cadc-60c0-488f-8101-6abd9122a6ca.png">

it takes me here, https://github.com/scipy/scipy/blob/b5d8bab88af61d61de09641243848df63380a67f/scipy/stats/_axis_nan_policy.py#L181
 to the NaN policy functions.

when I think it should probably be here:
https://github.com/scipy/scipy/blob/b5d8bab88af61d61de09641243848df63380a67f/scipy/stats/_mannwhitneyu.py#L182

The same thing happens with [Wilcoxon](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wilcoxon.html?highlight=wilcox#scipy-stats-wilcoxon), but I haven't look extensively for others with the same issue

### Reproducing Code Example

```python
N/a
```

### Error message

```shell
N/a
```

### SciPy/NumPy/Python version information

1.8 docs online

**Comment by mdhaber** [comment]
Yes, this is something I've noticed - Sphinx doesn't know how to find the original function to which a decorator was applied. I've meant to figure out some way of telling it where to go manually. @tirthasheshpatel any thoughts?

There are a few other issues I noticed with the `[source]` link:

- It's missing for all the `scipy.stats.sampling` classes.
- It doesn't know what lines distributions classes are defined on.
