### ISSUE TITLE
CI:ASK: Remove LaTeX doc builds? 

### ISSUE THREAD

**Issue by ilayn** [scipy/scipy#15635]
In every CI run we are firing up a LaTeX run for a document with more than 3K pages with questionable quality. I think nobody needs that file and for offline needs HTML docs are still a better option. But we waste a significant effort on CI machines for this file both in terms of energy and time. Design wise it's not a special document either and it's kind of an eyesore

Horrifying option of printing the docs entirely is, I'm hoping, not a thing at this point. And for specific parts one can still print out the html files. 

Any arguments against removal from CI jobs & artifacts?

**Comment by mdhaber** [comment]
I love LaTeX, but it certainly doesn't need to run in every CI job!

**Comment by tupui** [comment]
Agreed, I am all in for removing LaTeX completely. I am actually working on the doc CI caching and can see it would really be useful.

**Comment by ilayn** [comment]
Yes probably some historical reason for including pdf files as images in the compilation though png would have been also a possibility. Maybe someone wanted to keep the vector graphics for the manual. But yes pdf generation is also eating a lot.

I am not sure why but lately I started to feel like our compute footprint is massive. Probably we can improve this situation by extensive download and compile caches.

**Comment by tupui** [comment]
I am adding some caching here #13917. Hopefully I have something working soon...

If we would want to really reduce our footprint, we could go a different route: manual CI with labels for instance. On my side I would actually prefer this. You could "allow" CI to be run on a PR when some labels are present. You could then add/remove as you go in the PR. Most PRs really don't need to trigger x100 times the CI for all changes. And lot of people forget to use the skip directives (which are either way not flexible: cannot skip circleCI only, only skip by platform and not "task").

**Comment by ilayn** [comment]
Teaching people that or attending to all PRs by maintainers I think becomes a chore very quickly. What I meant more in the line of, if a py file is changed the build shouldn't compile every C and Fortran library from scratch or only that module maybe but not the whole codebase etc.

**Comment by tupui** [comment]
> Teaching people that or attending to all PRs by maintainers I think becomes a chore very quickly. What I meant more in the line of, if a py file is changed the build shouldn't compile every C and Fortran library from scratch or only that module maybe but not the whole codebase etc.

We have a bit of that with ccache on some meson jobs. Compile still takes ~3 mins. I don't know meson enough to know if we can do better.

**Comment by ilayn** [comment]
Ah, I keep on forgetting the meson part.

**Comment by rgommers** [comment]
So yes, we have a significant amount of potential improvements in the pipeline for CI, with Meson but also with reducing jobs (e.g., no longer Pythran yes/no for double the Windows builds after the next Meson release). 

I suggest keeping this issue focused on removing LaTex, and pdf docs, completely. I'd be happy to drop it, it's a continuous source of problems (also at release time) and the pdf docs don't really have much of a reason to exist anymore. 

This does need to be proposed on the mailing list.

**Comment by astrojuanlu** [comment]
I understand the sentiment behind this decision. However, some users do want good offline docs for various reasons still these days.

@ilayn you mentioned "offline HTML" in the mailing list. Is there a way to download such a thing as, say, a `.zip` that contains everything? Otherwise, what are the options besides doing `Ctrl+S` for every single page, or building the docs from source?

**Comment by astrojuanlu** [comment]
(To clarify: I don't think these minority use cases warrant keeping this frustrating part of the CI. However, it would be useful to articulate some reasonable alternatives, or figure out how someone would get the SciPy docs offline)

**Comment by tupui** [comment]
I think this is a question we could/should raise on the theme side. All projects will go to the same thought process and there might be a common ground to find here.

**Comment by rgommers** [comment]
> @ilayn you mentioned "offline HTML" in the mailing list. Is there a way to download such a thing as, say, a `.zip` that contains everything?

Yes, every release has the html docs as a zipped download available, see `HTML+zip` links at https://docs.scipy.org/doc/. You just unzip and go - much higher quality docs than the pdf.
