### ISSUE TITLE
BUG:  possible bug for stats.trim_mean

### ISSUE THREAD

**Issue by kwhkim** [scipy/scipy#15630]
### Describe your issue.

when there are many `np.nan`, `trim_mean()` would generate erreneous result,
because `np.partition()` or `np.sort()` would put all `np.nan`s to the behind.

We need to check if there is `np.nan` first and
omit all `np.nan`s before `np.partition()` and `np.mean()` if it's what we want

### Reproducing Code Example

```python
x = np.array([0,1,2,3,4,5,6,7, np.nan,np.nan,np.nan])
trim_mean(x, 0.3)
# 5.0
trim_mean(x,0.2)
# nan  # this is an example of inconsistent result
# consistent result would be np.nan for both of the above if that's what we want
```

### Error message

```shell
None
```

### SciPy/NumPy/Python version information

1.7.3 1.21.5 sys.version_info(major=3, minor=8, micro=12, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
Thanks for noticing, @kwhkim. Really, `trim_mean` needs a `nan_policy`, and the same could be said about dozens of other stats functions. We'll consider this as part of gh-14651, so I'll close this issue and add it to the list of references in gh-14651.
