### ISSUE TITLE
DSPGROUP_TRUESPEECH wav file

### ISSUE THREAD

**Issue by nellorebhanuteja** [scipy/scipy#15642]
Hi 
I am using scipy.io.wavfile.read() method for reading a wav file.
I see that it does not handle DSPGROUP_TRUESPEECH files.

Is there a way i can read it using scipy/python ?!!

**Comment by tupui** [comment]
Hi @nellorebhanuteja, thanks for reporting. I am sorry I will have to close this issue. This is not a user forum, I would suggest you to ask your question on StackOverflow using the tag `SciPy` or `Python`.
