### ISSUE TITLE
DOC: stats.ks_1samp: incorrect commentary in examples

### ISSUE THREAD

**Issue by ThijsStockmans** [scipy/scipy#15644]
### Describe your issue.

The examples in the documentation of scipy.stats.ks_1samp is very unclear:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_1samp.html

Whether the H0 should be rejected depends on the pvalue (generally >0.05 means rejected). However, the documentation shows a lot of inconsistencies in this respect. Rejecting at 0.92 and 0.12, not rejecting at 0.25.  

>>> x = stats.norm.rvs(loc=0.2, size=100, random_state=rng)
>>> stats.ks_1samp(x, stats.norm.cdf, alternative='less')
     KstestResult(statistic=0.100203351482..., pvalue=0.125544644447...)
     Reject null hypothesis in favor of alternative hypothesis: less
>>> stats.ks_1samp(x, stats.norm.cdf, alternative='greater')
     KstestResult(statistic=0.018749806388..., pvalue=0.920581859791...)
     Reject null hypothesis in favor of alternative hypothesis: greater
>>> stats.ks_1samp(x, stats.norm.cdf)
     KstestResult(statistic=0.100203351482..., pvalue=0.250616879765...)
     Don't reject null hypothesis in favor of alternative hypothesis: two-sided

### Reproducing Code Example

```python
from scipy.stats import ks_1samp
help(ks_1samp)
```

### Error message

```shell
no computer error
```

### SciPy/NumPy/Python version information

1.7.3 1.21.5 sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
Thanks for reporting @ThijsStockmans. Does https://github.com/scipy/scipy/pull/15646 address this?

**Comment by mdhaber** [comment]
Let's leave this open even after gh-15646 merges. `kstest` and `ks_1samp` examples could also use a similar lift.
