### ISSUE TITLE
DOC, REL: reminder to check release process with no-PDF doc workflow

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#15668]
Mostly a reminder for me to check `paver` commands and `make dist` before the next release process gets busy after the merging of gh-15649. It should simplify things in the long-term to remove the PDF/LaTeX doc build, but it can be hard to predict small errors that crop up in the untested standard release process.

**Comment by soma2000-lang** [comment]
@tylerjereddy  I am working on this

**Comment by rgommers** [comment]
@tylerjereddy did you check this? I think everything should be in good shape after gh-16296.

**Comment by rgommers** [comment]
This seems to have worked out fine, closing.
