### ISSUE TITLE
BUG: scipy.stats.skew does not work with scipy.stats.bootstrap

### ISSUE THREAD

**Issue by rmorel** [scipy/scipy#15678]
### Describe your issue.

Using scipy.stats.skew with scipy.stats.bootstrap results in a TypeError exception.

The same code works if you replace scipy.stats.skew with other statistical funcions, like numpy.std or numpy.mean.

A bit of context: I'm trying to use scipy's bootstrap to calculate confidence intervals for a skewness estimate.

### Reproducing Code Example

```python
import numpy as np
from scipy.stats import bootstrap, skew, norm

rng = np.random.default_rng()

dist = norm(loc=2, scale=4)  # our "unknown" distribution
data = dist.rvs(size=100, random_state=rng)
data = (data,)  # samples must be in a sequence

# This should work as is but it does not
res = bootstrap(data, skew, confidence_level=0.9, random_state=rng)
```

### Error message

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_13164/3868874016.py in <module>
      7 data = dist.rvs(size=100, random_state=rng)
      8 data = (data,)  # samples must be in a sequence
----> 9 res = bootstrap(data, skew, confidence_level=0.9, random_state=rng)

~\anaconda3\lib\site-packages\scipy\stats\_bootstrap.py in bootstrap(data, statistic, vectorized, paired, axis, confidence_level, n_resamples, batch, method, random_state)
    442     alpha = (1 - confidence_level)/2
    443     if method == 'bca':
--> 444         interval = _bca_interval(data, statistic, axis=-1, alpha=alpha,
    445                                  theta_hat_b=theta_hat_b, batch=batch)
    446         percentile_fun = _percentile_along_axis

~\anaconda3\lib\site-packages\scipy\stats\_bootstrap.py in _bca_interval(data, statistic, axis, alpha, theta_hat_b, batch)
     86 
     87     # calculate z0_hat
---> 88     theta_hat = statistic(sample, axis=axis)[..., None]
     89     percentile = _percentile_of_score(theta_hat_b, theta_hat, axis=-1)
     90     z0_hat = ndtri(percentile)

TypeError: 'float' object is not subscriptable
```

### SciPy/NumPy/Python version information

1.7.3 1.20.3 sys.version_info(major=3, minor=8, micro=12, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
Thanks for the code. Let me take a look and get back to you shortly.

**Comment by mdhaber** [comment]
In the meantime, call `bootstrap` with `vectorized=False`:
```python3
res = bootstrap(data, skew, confidence_level=0.9, random_state=rng, vectorized=False)
```

**Comment by mdhaber** [comment]
The problems is that `scipy.stats.skew` currently returns a Python `float`, not the `np.float64` that `bootstrap` expects.
Another fix is:
```python3
def statistic(x, axis):
    return np.asarray(skew(x, axis=axis), dtype=np.float64)

res = bootstrap(data, statistic, confidence_level=0.9, random_state=rng)
```
I'll submit a patch for 1.8.1.

**Comment by mdhaber** [comment]
Unfortunately, `skew` is using the idiom:
```python3
    if vals.ndim == 0:
        return vals.item()

    return vals
```
to turn 0D arrays into Python floats, whereas I would suggest
```python3
return vals[()]
```
which turns 0D arrays into NumPy floats and leaves other arrays unchanged.

**Comment by rmorel** [comment]
@mdhaber thank you very much for the quick answer =)

Both proposed solutions worked just fine (setting vectorized=False or using a helper function).

**Comment by mdhaber** [comment]
OK, I'll close this by making `bootstrap` ensure that the output of the `statistic` is a NumPy float or array. Separately, I will open a PR suggesting the replacement of the `.item()` way of converting 0D arrays to (NumPy) floats to  `[()]`.
