### ISSUE TITLE
ENH: `multivariate_normal` should accept eigendecomposition of the covariance matrix (or maybe variances and rotation angles).

### ISSUE THREAD

**Issue by KOLANICH** [scipy/scipy#15675]
### Is your feature request related to a problem? Please describe.

If we specify the covariance matrix manually, we usually do it in a form of rotation matrix and variances. So running the decomposition internally is redundant and inefficient.

### Describe the solution you'd like.

Internally the covariance matrix should be stored in the decomposed form, so we can alter the components separately. We should be able to provide them explicitly, so skipping the solver. We should also be able to provide the angles instead of the matrix, as a more convenient interface, so we don't have to mess with `.spatial.transform.Rotation` ourselves.

**Comment by mdhaber** [comment]
Related: gh-11053

**Comment by mdhaber** [comment]
@tirthasheshpatel I was thinking that `Covariance` addresses only the first part of this. But then again, 

- I can see having the user provide a `Rotatation` so they can specify the rotation by any one of several parametrizations, but the issue specifically asks for us to allow the user to specify rotation angles *and not* `Rotations`. I don't think we want to duplicate the `Rotation` interface like this if we are going to provide all sorts of ways of specifying rotations, and I think that limiting this sort of functionality to rotation angles only is a bit arbitrary (e.g. why not quaternions?).
- `Rotations` is only for 3d. I don't think we'd want to add special functionality for <=3 dimensions, and ND rotations aren't available yet (gh-12693).

Even though it would not be that hard to do, I don't think we want to add this sort of `Covariance` subclass. But users can subclass `Covariance` to do this sort of thing. If I were to add an example of that to the documentation, would that resolve the issue, do you think?

**Comment by mdhaber** [comment]
In retrospect, I don't think I want to officially document the extendability right now. It is a brand new class; let's let it stabilize for a bit before we do that. But hopefully an example is enough. This one shows how the pseudoinverse could be used to define such a class. (Perhaps in the future, instead of directly using `whiten`, we will use a `mahalanobis_distance` method to compute the Mahalanobis distance in `multivariate_normal`. That would make it possible to avoid the matrix square root below. We could also use `ldl`, but this is simpler.)

```python3
import numpy as np
from scipy import stats, linalg
from functools import cached_property
rng = np.random.default_rng(9813621189651214)


class CovViaPseudoinverse(stats.Covariance):

    def __init__(self, pinv, covariance):
        self.pinv = pinv
        self.cov = covariance

    # Required Attributes
    @property
    def covariance(self):
        return self.cov

    @property
    def shape(self):
        return self.cov.shape

    @property
    def log_pdet(self):
        return -np.sum(np.log(self.peigs))

    @property
    def rank(self):
        return len(self.peigs)

    # Required Method
    def whiten(self, x):
        return self.sqrt_pinv @ x

    # Other
    @cached_property  # relatively expensive to compute; cache it
    def peigs(self):
        evals, evecs = np.linalg.eigh(self.pinv)
        return evals[evals > 1e-8]

    @cached_property
    def sqrt_pinv(self):
        return linalg.sqrtm(self.pinv)


eigs = np.array([0, 1, 2, 3])
A = stats.random_correlation(eigs * len(eigs)/sum(eigs), seed=rng).rvs()

cov = CovViaPseudoinverse(np.linalg.pinv(A), A)
cov2 = stats.Covariance.from_eigendecomposition(np.linalg.eigh(A))

x = rng.random(4)
w = cov.whiten(x)
w2 = cov2.whiten(x)

print(np.allclose(cov.log_pdet, cov2.log_pdet))  # True
print(np.allclose(w, w2))  # False, but that's OK. It may still be a valid whitening.
print(np.allclose(w.T @ w, w2.T @ w2))  # True; whiten is valid.
```

**Comment by mdhaber** [comment]
We'll keep this in mind to officially document how `Covariance` can be overridden. In the meantime, I think this can be closed since it's not actionable for a long time, but please re-open if you think we should keep this open @tirthasheshpatel.

**Comment by KOLANICH** [comment]
Thanks to everyone involved into implementing this feature.
