### ISSUE TITLE
ENH: Compute bounding boxes for multivariate distribution

### ISSUE THREAD

**Issue by KOLANICH** [scipy/scipy#15677]
### Is your feature request related to a problem? Please describe.

For visualization purposes it'd be nice to have built-in function to get bounding boxes in terms of scale parameters. For example for `scipy.stats.multivariate_normal` in terms of count of sigmas aligned to the principal components

### Describe the solution you'd like.

`distribution.get_bounding_box([sigma1, sigma2])`

### Describe alternatives you've considered.

Doing myself. It is inconvenient.

### Additional context (e.g. screenshots, GIFs)

```python
# c is covariance matrix
S, e = scipy.linalg.eig(c)
s = np.sqrt(np.real(S))
e = np.real(e)
n = 2.6

ns = s * n
bounds = np.array([
    [-ns[0], -ns[1]],
    [ns[0], -ns[1]],
    [-ns[0], ns[1]],
    [ns[0], ns[1]]
])
bounds = (bounds @ e).T
bounds[0] += m[0]
bounds[1] += m[1]
xbs = np.min(bounds[0]), np.max(bounds[0])
ybs = np.min(bounds[1]), np.max(bounds[1])
bounds = (xbs, ybs)
```

**Comment by mdhaber** [comment]
A few questions:
- What is `m`?
- Is this for visualizing the PDF of the distribution?
- Is this different from the desire to have an easy way of computing a "bounding box" (region in which the function is interesting) around any function?

**Comment by KOLANICH** [comment]
1. means
2. Yes.
3. Yes. In general for "any function" we have to compute that function. But for distributions we have parameters and from them we can estimate bounding boxes without computing the function in many points.

**Comment by mdhaber** [comment]
OK. For 3, I understand, but there are many functions other than distribution PDFs that accept parameters from which we could compute bounding boxes without computing the function at many points. Why do multivariate distribution PDFs deserve special treatment?

**Comment by KOLANICH** [comment]
Do you propose introducing a class for such kind of functions with a method `get_roi_by_integral_threshold` and making distributions a subclass of it?

**Comment by mdhaber** [comment]
No, I'm wondering whether computation of bounding boxes for multivariate distributions, in particular, falls within SciPy's scope. If so, is computation of bounding boxes in scope for _all_ functions that would benefit from it?

**Comment by mdhaber** [comment]
@KOLANICH would you send an email to the [scipy-dev list](https://mail.python.org/mailman3/lists/scipy-dev.python.org/) about this and invite people to this issue for discussion? Then we can make a decision based on wider feedback.

**Comment by KOLANICH** [comment]
>@KOLANICH would you send an email to the scipy-dev list about this and invite people to this issue for discussion? Then we can make a decision based on wider feedback.

Thanks for the suggestion, but no. I am not subscribed to that list and currently have no plans to subscribe. Could anyone subscribed do it for me?

>No, I'm wondering whether computation of automatic bounding boxes for visualization of multivariate distributions, in particular, falls within SciPy's scope. If so, is computation of bounding boxes in scope for all functions that would benefit from it?

I think it should be, but only for the ones for which it can be done cheaply.

And not only for visualization. I.e. I also use the boxes for computation purposes.


I also think we should have such functions for univariate too, and not only in terms of scale parameters, but also in terms of integral of the PDF outside of the box. Each dist has a scale parameter, but obtaining limits for each may look a bit different, so we need an unified abstraction, and so the probability of a point to be missed seems to be an universal measure for all distributions.

**Comment by mdhaber** [comment]
> Thanks for the suggestion, but no. I am not subscribed to that list and currently have no plans to subscribe. Could anyone subscribed do it for me?

I'm still not convinced that it's within SciPy's scope, so I'd prefer not to. But I'll leave this open for a while in case others are interested. Next month, I'll ping a few stats maintainers to get their thoughts.

**Comment by KOLANICH** [comment]
https://github.com/KOLANICH-libs/StatsUtils.py/blob/master/StatsUtils/dists/MultivariateGaussian.py

**Comment by mdhaber** [comment]
@rkern @chrisb83 @tirthasheshpatel @tupui Anyone want to champion this issue on the mailing list for @KOLANICH? Otherwise, I'd suggest we close this in one month, the default decision being that it's not obviously in SciPy's scope.

**Comment by rkern** [comment]
I don't think it's really in-scope, no. It's not unreasonable to want to compute these things, but it requires certain assumptions about what the user wants to see that make this better implemented in user's own code, outside of scipy.

**Comment by tupui** [comment]
Isn't it already what `ppf` can be used for?

**Comment by mdhaber** [comment]
Yes, but this is for multivariate distributions, which don't all have PPF.

**Comment by tupui** [comment]
Yes ok, then I could see a feature request to compute `ppf` on multivariate distributions if it's lacking somewhere. But nothing more.

**Comment by mdhaber** [comment]
Actually, I don't think `ppf` alone solves the problem. There are a few different notions of `ppf` for multivariate distributions, and I'm not sure if any of them would solve the bounding box problem.

**Comment by tupui** [comment]
Ok I did not realise it was more complicated than "ppf of the marginals". The way you describe it sounds more like a research topic, hence on the off topic side. I never had to look into these so I don't know more like that.

**Comment by mdhaber** [comment]
I think "PPF of the marginals" would correspond with this rectangular PPF idea where all the coordinates except the one you're interested in are infinity. I suppose you could use that to get a reasonable bounding box.

**Comment by KOLANICH** [comment]
OK, let's try to formalize what we want.

1. We want a ROI (region of interest) containing the certain probability `\int_ROI f(X) dX = 1 - α`.
2. We want this ROI do be as "dense" as possible. `ROI = argmax_ROI \int_ROI f(X) dX / \int_ROI dX`
3. We want the hypersurface bounding the ROI be a convex curve, so we can put it into a bounding box.
4. Do we need the hypersurface bounding the ROI be a surface of constant PDF (hyperellipses for gaussians)?
5. This ROI boundary in general is a hypersurface. But we don't want it to be an arbitrary hypersurface matching the criteria because:
    * scipy is not a 3d-modelling and FEM package, having tools for arbitrary meshes here is out of scope
    * visualization viewports are rectangular.
So instead we want it to be a box. Let's cal, the box related to ROI a bROI.
6. We need to decide how bROI is related to ROI. I guess the area of ROI within bROI have to be maximized (it is achieved when bROI contains whole ROI) and area of bROI out of ROI has to be minimized (it occurs when bROI bounds are tangent to the ROI).

**Comment by rkern** [comment]
I stand by my comment. It's not unreasonable to want to compute such things, but I think it's best for it to be done outside of `scipy`.

**Comment by mdhaber** [comment]
@KOLANICH I'm sorry this idea didn't get much support here : / It's a very reasonable thing to ask for, but as it's -3 from maintainers and there is nobody to champion the issue (e.g. by sending an email to the mailing list), I'll need to close it. Have you considered creating a separate library with some of these ideas? Although they seem out of scope for the main library, they do seem useful!

**Comment by KOLANICH** [comment]
>Have you considered creating a separate library with some of these ideas?

Already have done it, but it is now in a dirty and unfinished state. Here it is: https://github.com/KOLANICH-libs/StatsUtils.py , `StatsUtils.dists.MultivariateGaussian:MultivariateGaussian.computeBounds`.
