### ISSUE TITLE
BUG: default value of shape parameter in fit method of rv_continuous might not be admissible

### ISSUE THREAD

**Issue by chrisb83** [scipy/scipy#15689]
### Describe your issue.

If no guess of the shape parameter is provided to `rv_continuous.fit`, the value of 1.0 is taken as a guess. However, it is not guaranteed that this value is allowed as a shape parameter, e.g., if `_argcheck(1.0)` is True

### Reproducing Code Example

```python
import numpy as np
from scipy.stats import rv_continuous
from scipy.optimize import fmin


class myDist_gen(rv_continuous):
    def _argcheck(self, a):
        return a > 2

    def _pdf(self, x, a):
        # we need a >= 2 to avoid division by 0 at x=Pi
        return (1 + np.cos(x))**(a-2)

myDist = myDist_gen(a=0.0, b=4.0, name='bla') 
data = myDist.rvs(a=3, size=20)
myDist.fit(data, floc=0, fscale=1)
```

### Error message

```shell
Exception: Optimization converged to parameters that are outside the range allowed by the distribution
```

### SciPy/NumPy/Python version information

1.7.1 1.21.2 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by chrisb83** [comment]
To explain the root cause, I tried to replicate the behaviour of `fit` in `stats\_distn_infrastructure.py`:

```
args = ()
kwds = {'floc': 0.0, 'fscale': 1.0}

start = [None]*2
# fitstart will set the guess for a to 1.0
start = myDist._fitstart(data)
args += start[:-2]
loc = kwds.pop('loc', start[-2])
scale = kwds.pop('scale', start[-1])
args += (loc, scale)

x0, func, restore, args = myDist._reduce_func(args, kwds, data=data)
vals = fmin(func, x0, args=(np.ravel(data),), disp=1) # array([1.])

obj = func(vals, data) # np.inf

if not (np.all(self._argcheck(*shapes)) and scale > 0):
            raise Exception("Optimization converged to parameters that are "
                            "outside the range allowed by the distribution.")

```

From the above, it is clear that the optimizer did not converge...

If one specifies a valid guess for a, it works:
```
myDist.fit(data, 2.2, floc=0, fscale=1) # I got (1028.5702001953148, 0, 1)
```

**Comment by chrisb83** [comment]
If we have `ShapeInfo` for all distributions, one could make sure that the guess of the shape parameter is valid

**Comment by mdhaber** [comment]
Yup. I [had asked](https://github.com/scipy/scipy/pull/15436#issuecomment-1043892084) whether you'd like me to open PRs for those or whether you'd like to do it and I can review. The advantage of the latter is that it would give others a reason to test `stats.fit` out before 1.9.0 branches.

**Comment by mdhaber** [comment]
Here is the start of a test that we can add to `test_fit.py` to check for when the `_fitstart` shape guess fails `_argcheck`.

```python3
def cases_test_fitstart():
    for distname, shapes in dict(distcont).items():
        if not isinstance(distname, str):
            continue
        yield distname, shapes


@pytest.mark.parametrize('distname, shapes', cases_test_fitstart())
def test_fitstart(distname, shapes):
    dist = getattr(stats, distname)
    data = np.random.rand(5)

    with np.errstate(invalid='ignore', divide='ignore'):  # irrelevant to test
        guess = dist._fitstart(data)

    assert np.all(dist._argcheck(*guess[:-2]))
```
