### ISSUE TITLE
BUG: dok_matrix rank 1

### ISSUE THREAD

**Issue by smorken** [scipy/scipy#15687]
### Describe your issue.

scipy dok_matrix either incorrectly not support rank 1 matrix, and/or has a misleading error message:

`TypeError: Expected rank <=2 dense array or matrix.`

### Reproducing Code Example

```python
from scipy import sparse
mat = sparse.dok_matrix(1)
```

### Error message

```shell
`TypeError: Expected rank <=2 dense array or matrix.`
```

### SciPy/NumPy/Python version information

1.7.2 1.20.3 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by ilayn** [comment]
You need to give an array not an integer as `mat = sparse.dok_matrix([[1]])`
