### ISSUE TITLE
BUG: scipy.stats.ks_2samp behaviour

### ISSUE THREAD

**Issue by vilmar-hillow** [scipy/scipy#15697]
### Describe your issue.

I'm working on monitoring data drift for some ML models in production. We plan one using `evidently`, which under the hood uses `ks_2samp` for numeric features. During the tests, I've noticed weird behaviour where similar data returns low P-values where they are expected to be close to 1. I've attached an example using the iris dataset that mimics the data drift monitoring process.

The code is attached here, and also available in [colab](https://colab.research.google.com/drive/1_ZP9lrNOpti3XlRxDqH-zzgtZ9Txc5u_?usp=sharing) and a [repo](https://github.com/vilmar-hillow/ks_2samp_test).

Does anyone have some insight into what's going on here?

### Reproducing Code Example

```python
import pandas as pd
from scipy.stats import ks_2samp
from sklearn.preprocessing import MinMaxScaler


def get_data():
    """Fetch iris dataset."""
    names = ["sepal-length", "sepal-width", "petal-length", "petal-width", "class"]
    url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"
    data = pd.read_csv(url, names=names)

    return data


def get_features(data: pd.DataFrame):
    """Generate features."""
    data = data.copy()

    numeric_fields = [
        "sepal-length",
        "sepal-width",
        "petal-length",
        "petal-width",
    ]

    data_numeric = data[numeric_fields]
    scaler = MinMaxScaler()
    scaler.fit(data_numeric)
    data[numeric_fields] = scaler.transform(data_numeric)

    return data[numeric_fields]

raw_data = get_data()
features = get_features(raw_data)
features.to_csv("reference.csv", index=False)
reference = pd.read_csv("reference.csv")

for feature_name in features.columns:
    scipy_p_value = ks_2samp(reference[feature_name], features[feature_name])[1]
    print(f"Feature '{feature_name}' p value: {scipy_p_value}")
```

### Error message

```shell
Feature 'sepal-length' p value: 0.8943205382966369
Feature 'sepal-width' p value: 0.021902713572760964
Feature 'petal-length' p value: 0.7249566931207618
Feature 'petal-width' p value: 0.010603075080924049
```

### SciPy/NumPy/Python version information

1.8.0 1.22.2 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
When you save the data to csv and load it again, the floating point representations are changing slightly. Since KS test depends on orderings, this makes a big difference in the resulting calculation.
