### ISSUE TITLE
BUG: scipy.integrate.simps returns NaN when span of x is 0

### ISSUE THREAD

**Issue by shawnperdue** [scipy/scipy#15721]
### Describe your issue.

Obviously, this is an edge case, but I think it should be handled. Having an array for x with no span (all values are the same), integrate.simpson returns NaN and throws a couple divide by 0 errors from _quadrature. Instead, since integrating over a span of 0 is in fact 0, I think the function should return 0.

### Reproducing Code Example

```python
scipy.integrate.simpson(range(5), [0,0,0,0,0])
```

### Error message

```shell
C:\AeroApps\AnacondaP3x64-5.1.0\envs\cf310\lib\site-packages\scipy\integrate\_quadrature.py:415: RuntimeWarning: invalid value encountered in true_divide
  h0divh1 = h0 / h1
C:\AeroApps\AnacondaP3x64-5.1.0\envs\cf310\lib\site-packages\scipy\integrate\_quadrature.py:417: RuntimeWarning: invalid value encountered in true_divide
  y[slice1] * (hsum * hsum / hprod) +
Out[58]: nan
```

### SciPy/NumPy/Python version information

1.8.0 1.22.3 sys.version_info(major=3, minor=10, micro=2, releaselevel='final', serial=0)

**Comment by k-styles** [comment]
@tupui I have created another pull request #15824 for this issue. I have made it with the changes that you requested. Could you please review it?

**Comment by tupui** [comment]
Why did you close the first PR and created a new one?

**Comment by k-styles** [comment]
> Why did you close the first PR and created a new one?

Last time I encountered some failures while running tests for scipy on my local machine, so I thought of going over "building the scipy library" process from the official docs once again. In the process, I deleted the first fork and created a new one, which closed the previous PR. So I had to create a new one this time.
