### ISSUE TITLE
DEP: special.comb: deprecate `exact=True` for non-integers

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#15722]
Following #15359, where we promise a change of behaviour by scipy 1.11.

* 1.11.0
  * `legacy is not None`:
    ```
                warnings.warn(
                    "Using legacy=True is deprecated and will raise an error "
                    "by Scipy 1.13.0. If you want to keep the legacy "
                    "behaviour, cast your inputs directly, "
                    "e.g. comb(int(your_N), int(your_k), exact=True).",
                    DeprecationWarning
                )
    ```
* 1.14.0 (due to out-of-band release of 1.13 and waiting for positional deprecation)
  * `legacy` kwarg removed
  * Also deprecate using `exact=True` for non-integer inputs.

**Comment by tupui** [comment]
+1 with the plan. And I would say it's fine to remove the parameter in 1.13.

**Comment by h-vetinari** [comment]
Not closing this, to track removal of the `legacy=` keyword in 1.13.

Also, I noted one other thing in #17637 that I think should be fixed (perhaps also for 1.13):
> We could start warning about using `exact=True` with non-integers [...]

**Comment by h-vetinari** [comment]
Since #17637 emits a warning `if legacy is not None`, I think we can directly remove the keyword for 1.13. And we should then also deprecate `exact=True` with non-integers. I've updated the OP to reflect that.

**Comment by h-vetinari** [comment]
@j-bowhay, not sure how this issue fell off the tracker, but it seems we missed the 1.13 train here... 😑

**Comment by j-bowhay** [comment]
Apologies missed this too, I been very busy with uni as of late

**Comment by lucascolley** [comment]
The legacy kwarg is removed. Deprecating `exact=True` with non-integers remains.

**Comment by h-vetinari** [comment]
@j-bowhay / @lucascolley, since https://github.com/scipy/scipy/pull/20588 did only half of the remaining tasks for 1.14, would you be able to raise a PR to deprecate what's left to be deprecated?

**Comment by lucascolley** [comment]
I won't have time before 1.14.0, apologies (busy with exams)

**Comment by j-bowhay** [comment]
I can take this
