### ISSUE TITLE
BUG: scipy.sparse.csr_matrix((data, indices, indptr), [shape=(M, N)]) returns different matrices when instantiated by the same attributes

### ISSUE THREAD

**Issue by tagagi** [scipy/scipy#15726]
### Describe your issue.

There are two ways to instantiate a csr_matrix :
1) Defining the variables out of the  csr_matrix() function and instantiating it by passing parameters.
2) Defining the variables just in the csr_matrix() function.

With the same parameters, the matrices obtained in these two different ways are transposed to each other.

### Reproducing Code Example

```python
import numpy as np
import scipy.sparse as ssp


indptr = np.array([0, 2, 4, 6])
indices = np.array([0, 1, 1, 2, 0, 2])
data = np.array([1, 2, 3, 4, 5, 6])
a = ssp.csr_matrix((data, indices, indptr), shape=(3, 3)).toarray()  # 1
b = ssp.csc_matrix((np.array([1, 2, 3, 4, 5, 6]), np.array([0, 1, 1, 2, 0, 2]), np.array([0, 2, 4, 6])), shape=(3, 3)).toarray()  # 2

print(a)
print()
print(b)
```

### Error message

```shell
[[1 2 0]
 [0 3 4]
 [5 0 6]]

[[1 0 5]
 [2 3 0]
 [0 4 6]]
```

### SciPy/NumPy/Python version information

1.5.0 1.19.2 sys.version_info(major=3, minor=8, micro=12, releaselevel='final', serial=0)

**Comment by perimosocordiae** [comment]
Your `b` matrix is using CSC format, where `a` is using CSR.
