### ISSUE TITLE
Query: Building for python2 on m1 mac

### ISSUE THREAD

**Issue by maczikasz** [scipy/scipy#15720]
Hi,

I am assuming that this will be a though ride since python2 support is long gone but maybe it's doable

I am trying to build scipy for python2 on my m1 mac.

I have checked out the `maintenance/0.16.x` branch and trying to install it

The errors come from SuperLU 

```    scipy/sparse/linalg/dsolve/SuperLU/SRC/zcolumn_bmod.c:234:3: error: implicit declaration of function 'ztrsv_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                    ztrsv_( "L", "N", "U", &segsze, &lusup[luptr],
```

It seems that somehow the OpenBLAS functions are not found. I tried to add the openblas location with -L but no luck

Any other tips or tricks would be extremely appreciated

**Comment by tupui** [comment]
Hi @maczikasz. I am afraid this will never happen from us. As of today, we are only supporting Python >3.8. It just cannot work on previous versions because we use features which are not present in Python version bellow that point.

**Comment by maczikasz** [comment]
I understand, but anyway it seems the issue is with SuperLU and M1 macs, since I cannot even build that

**Comment by tupui** [comment]
If you followed the contributor [guide](https://scipy.github.io/devdocs/dev/contributor/quickstart_mac.html#quickstart-mac) and can reproduce with Python >= 3.8, then feel free to open a new issue.

I doubt there is anything here. Some maintainers, including myself, have an M1 and don't have any trouble building from source using our instructions.
