### ISSUE TITLE
DEP: remove quiet parameter from fitpack

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#15733]
It's been deprecated for over 7 years, see https://github.com/scipy/scipy/pull/4003.

**Comment by h-vetinari** [comment]
I remember looking at the [code](https://github.com/scipy/scipy/blob/main/scipy/interpolate/_fitpack_impl.py) but forgot to comment then.

The deprecation is going to be a bit tricky, because the current default is `quiet=1`, and the number is then both used
as an int:
https://github.com/scipy/scipy/blob/59d974bf14ff8c82f3353e2d2a9282d9bda67db5/scipy/interpolate/_fitpack_impl.py#L225-L227
and as a boolean
https://github.com/scipy/scipy/blob/59d974bf14ff8c82f3353e2d2a9282d9bda67db5/scipy/interpolate/_fitpack_impl.py#L294-L297

At the same time, it _doesn't_ cover the following warning
https://github.com/scipy/scipy/blob/59d974bf14ff8c82f3353e2d2a9282d9bda67db5/scipy/interpolate/_fitpack_impl.py#L298-L300
... so `quiet` and `full_output` are somewhat working at odds.

The whole code there is not a small amount of baroque, like how the error messages are outsourced into a dict [`_iermess`](https://github.com/scipy/scipy/blob/main/scipy/interpolate/_fitpack_impl.py#L52-L69), but wait!, there's [`_iermess2`](https://github.com/scipy/scipy/blob/main/scipy/interpolate/_fitpack_impl.py#L71-L100) which is the same but more extensive? 🤔 

I think that's why I ended up not commenting - the closer I looked, the more parts I discovered that substantial attention. 😅

**Comment by j-bowhay** [comment]
yes that's why I deleted my comment, I realised it was more messy that I first thought!

**Comment by j-bowhay** [comment]
This is also tricky because the default behaviour is also the deprecated behaviour

**Comment by h-vetinari** [comment]
The only sensible thing IMO is to re-deprecate this properly (together with a clean-up of how it's used) and remove it in 1.11

**Comment by h-vetinari** [comment]
Changing milestones after 1.9 branched

**Comment by j-bowhay** [comment]
@h-vetinari @ev-br do either of you have a preference on how to do this? My thought is you change the default value to `quiet=0` and raise a deprecation warning for non-zero values saying quiet will be removed after two releases. Of course the other approach would be to leave the default value as is and raise a deprecation warning saying the default value will change to 0 and then another cycle to remove quiet completely. I dont see how it is going to be possible to do this without users seeing new warnings in their code (either runtime warnings for the first option or deprecation warning for the second) but the first option seems preferable to me at least as it gets this dealt with faster.

**Comment by ev-br** [comment]
I've no preference on this. Whichever is faster and simpler?

**Comment by h-vetinari** [comment]
I think the two most important rules are:
* There must be a way to run the code without warnings 
* We strive not to break behaviour unannounced

It's debatable if a change in logging behaviour is a big enough break that it would really inconvenience anyone, so from that POV I'd be fine with just changing (and documenting) it. This is quite an exception though (and arguably it would be cleaner to go through the full deprecation cycle) - for any change affecting the result of a computation I wouldn't agree to do that.

**Comment by j-bowhay** [comment]
> * There must be a way to run the code without warnings

Just to clarify, does this include the user filtering the warnings themselves?

**Comment by h-vetinari** [comment]
> Just to clarify, does this include the user filtering the warnings themselves?

IMO no (though it's clearly possible to do, it's not what we should impose on them).

**Comment by j-bowhay** [comment]
I am beginning to think we should just remove the deprecation from the docstring as the deprecation is calling for the user to filter the warnings themselves:
https://github.com/scipy/scipy/blob/59d974bf14ff8c82f3353e2d2a9282d9bda67db5/scipy/interpolate/_fitpack_impl.py#L174-L175
So following this through is just going to result in a load of logging appear in users code. Also use of arguments to suppress logging is used else where in scipy eg. https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.lobpcg.html#scipy.sparse.linalg.lobpcg

**Comment by j-bowhay** [comment]
> I am beginning to think we should just remove the deprecation from the docstring as the deprecation is calling for the user to filter the warnings themselves:
> 
> https://github.com/scipy/scipy/blob/59d974bf14ff8c82f3353e2d2a9282d9bda67db5/scipy/interpolate/_fitpack_impl.py#L174-L175
> 
> 
> So following this through is just going to result in a load of logging appear in users code. Also use of arguments to suppress logging is used else where in scipy eg. https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.lobpcg.html#scipy.sparse.linalg.lobpcg

@h-vetinari any thoughts on this?

**Comment by h-vetinari** [comment]
@ev-br is the better person to ask on the long-term plans for this, but I'm fine to remove the docstring deprecation. 👍
