### ISSUE TITLE
DEP: deal with deprecation of ndim >1 in bspline

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#15734]
Since https://github.com/scipy/scipy/commit/0131d72f0f7a5c13f00961aea054094b2b78f071 from https://github.com/scipy/scipy/pull/3174, there's a warning that says
```
Calling splev() with BSpline objects with c.ndim > 1 is not recommended. Use BSpline.__call__(x) instead.
```

It _does_ raise a `DeprecationWarning` (and for over 5 years, at that), but the message text is a bit soft. Either we should sharpen the deprecation warning to schedule removal in 1.10 / 1.11, or simply remove it for 1.9.

CC @ev-br

**Comment by ev-br** [comment]
Since there was not a single complaint about this, we can even raise an error. If anybody feels stong enough about it --- not sure whether it's of any use. It won't be less code, so as far as I'm concerned it can just be left as-is.
