### ISSUE TITLE
DEP: Execute deprecation of pinv2

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#15737]
From #13831. That PR does not specify a specific removal date, so I think we could sharpen the warnings to indicate removal by 1.10/1.11; on the other hands, two releases between deprecation and removal is also common practice, so would be an option as well IMO. In either case, there's something actionable for 1.9, hence the milestone.

CC @ilayn

**Comment by ilayn** [comment]
Somehow we missed the same deprecation cycle in `pinvh` apparently 😃 

https://github.com/scipy/scipy/blob/main/scipy/linalg/_basic.py#L1416-L1419=
