### ISSUE TITLE
DEP: raise on >1-dim inputs for optimize.minimize

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#15739]
This comes from #15297, which only landed for 1.9. Currently the message of the deprecation warning is a bit soft:
```
Use of `minimize` with `x0.ndim != 1` is deprecated. Currently, singleton dimensions
will be removed from `x0`, but an error may be raised in the future.
```

Can we sharpen this to say that an error _will_ be raised in version X? (1.11? 1.12?)

CC @mdhaber

**Comment by mdhaber** [comment]
That is fine with me.
