### ISSUE TITLE
DEP: remove k=None from KDTree.query

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#15746]
Deprecated since https://github.com/scipy/scipy/pull/12382, contains still-extant announcement of removal in 1.8

**Comment by ML-Nielsen** [comment]
Hello,
I would like to make my first contribution open source software. 
Can I try to solve this issue? How does it work? Can I just start working on it, and then at some point make a pull request, or should I be assigned to this issue somehow?

**Comment by h-vetinari** [comment]
Sure, go for it! :)

Commenting on this issue that you intend to do it is usually enough to avoid that people work at cross-purposes.

You can just make the change and open a PR. Of course, the tests will very likely need adaptation to reflect the change in behaviour, and whether you test those locally or through the CI on the PR is up to you. If you can test locally that's better, but not a big deal.

Once you have a green CI (or you end up stuck somewhere), just ask for review/tips. You can ping me directly if you want.

Good luck!

**Comment by ML-Nielsen** [comment]
@h-vetinari Thanks a lot!
So far, I have removed the few lines pasted below (in scipy/scipy/spatial/_kdtree.py):
![image](https://user-images.githubusercontent.com/101410494/158019451-d2a2c361-5d50-44f9-a550-37006bd87e85.png)
Should the lines below also be removed, even though they are part of a comment?
![image](https://user-images.githubusercontent.com/101410494/158019622-fb967efb-da7e-4c88-8157-fe44d207f348.png)

If the tests are not running, should I adapt them as well as part of the same PR?

**Comment by h-vetinari** [comment]
Yeah exactly; we should remove all things related to the behaviour of `k=None` (including documentation!), and then raise an error in the `if k is None` branch.
