### ISSUE TITLE
DEP: docstring-related deprecations

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#15757]
#9652 deprecated all methods in https://github.com/scipy/scipy/blame/main/scipy/misc/_doccer.py

**Comment by Matt711** [comment]
@h-vetinari Hi! I would like to work on this issue. Can I have a little more information? How should the docstrings here: [_doccer.py](https://github.com/scipy/scipy/blame/main/scipy/misc/_doccer.py) be updated? Thanks!

**Comment by h-vetinari** [comment]
Looking at the git blame and thus #9652, it looks to me like these should just be removed (if there are any uses left in the scipy codebase, they should migrate to the equivalent functions in `_lib`.
