### ISSUE TITLE
DEP: absorb lsim2 into lsim

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#15755]
Non-uniform timestamps have been deprecated since #4675

**Comment by h-vetinari** [comment]
Unfortunately, simply executing the deprecation (an attempt was made in #15796) conflicts with the goals of #5676. After some discussion there, the approach will need to be adapted:
* Ingest the logic of `lsim2` into `lsim`
* Investigate behavioural differences between `lsim2` & `lsim`
* If there are any, deprecate legacy behaviour of `lsim`, adding a `legacy=True` keyword to keep the current behaviour for now (similar to how this was done for #15359)
* Deprecate `lsim2` at the same time

**Comment by FranzForstmayr** [comment]
I'll try to fix this issue!

**Comment by h-vetinari** [comment]
Looking more closely at the discussion in #4675, it appears that actually `lsim` had been rewritten and is supposed to replace `lsim2`, despite the name inversion, and despite `lsim2` supporting non-uniform timestamps (this part was [discussed](https://github.com/scipy/scipy/pull/4675#issuecomment-92075425) as well, including a [post](https://github.com/scipy/scipy/pull/4675#issuecomment-92075425) to the mailing list).

That actually means my plan from above makes no sense anymore and we should directly deprecate `lsim2`.

**Comment by j-bowhay** [comment]
@h-vetinari what state is this in, appears #15929 has stalled?

**Comment by FranzForstmayr** [comment]
I'll try to fix the points from the review in #15929 today.

**Comment by h-vetinari** [comment]
1.10 was released, resetting the milestone to 1.11
