### ISSUE TITLE
DEP: remove object arrays in sparse matrices

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#15764]
A warning (not explicitly a `DeprecationWarning`) was added in #2719 for #2528; current usage [here](https://github.com/scipy/scipy/blob/v1.8.0/scipy/sparse/_sputils.py#L114).

**Comment by h-vetinari** [comment]
Given that the warning just says
```
warnings.warn("object dtype is not supported by sparse matrices")
```

I'd usually suggest turning this into a proper deprecation warning with announced removal. _But_, reading #2528, it seems that object types for sparse matrices simply are not fully implemented and/or expected to work. There was already an attempt to turn this into an outright error, though @pv [noted](https://github.com/scipy/scipy/issues/2528#issuecomment-23031188) then (in 2013):
> I changed the PR to raise a warning rather than error on object dtypes --- I think this change needs some deprecation first.

I would suggest just raising an error outright for 1.9 - does that sound reasonable to you @pv @rgommers?

**Comment by rgommers** [comment]
Yes that's fine, the warning has been there for a decade.

**Comment by perimosocordiae** [comment]
Yep, raising a ValueError makes sense here.
