### ISSUE TITLE
MAINT: There is no unittest and documentation of Improper integral in multiple integrals.

### ISSUE THREAD

**Issue by derbuihan** [scipy/scipy#15792]
I appreciate Scipy's excellent code. I would like to make a suggestion to make it even better.

From the tutorial (https://docs.scipy.org/doc/scipy/tutorial/integrate.html), it appears that scipy's integrate.dblquad supports Improper integral. On the other hand, there is no mention of it in the unittest (https://github.com/scipy/scipy/blob/main/scipy/integrate/tests/test_quadpack.py) and documentation (https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.dblquad.html). I think it would be better if we did a unittest on Improper integral for multiple integrals in scipy and clarify the scope of support in the documentation.

I would like to work on this issue, any opinions?

**Comment by mdhaber** [comment]
@derbuihan thanks for your patience. I do think `dblquad` can handle infinite limits of integration. (I'm not sure about other improper integrals... it doesn't accept `points` like `quad` does.) Are you still interested in writing unit tests and examples? I would review it.

**Comment by Kai-Striega** [comment]
I can confirm that `dblquad` (and `tplquad`) support both.

**Comment by Kai-Striega** [comment]
@derbuihan are you still free to work on this issue? Otherwise, @jdilanzo I think this would be a good issue for you to get started with.

**Comment by jdilanzo** [comment]
Thanks @Kai-Striega, if there's no word from @derbuihan by the time the weekend rolls around I will take a look at this!
