### ISSUE TITLE
BUG: `isspmatrix` doesn't account for sparse arrays

### ISSUE THREAD

**Issue by rossbar** [scipy/scipy#15790]
### Describe your issue.

There are two functions in `scipy.sparse` which determine whether or not an object is a sparse container: `sp.sparse.isspmatrix` and `sp.sparse.issparse`. Based on the names of these functions, one might expect the former to return `True` for the sparse matrix containers (e.g. `csr_matrix`) and the latter to return true for either sparse matrices or sparse arrays.

It turns out that `issparse` is just an alias of `isspmatrix`, and `isspmatrix` returns True for sparse arrays as well as matrices, which might be a misleading.

Given the addition of the sparse array containers, I would propose modifying the behavior of these functions to account for the distinction between sparse arrays and matrices, i.e. something like:

```python
def issparse(x):
    # Note: the sparse array containers are currently subclasses of
    # spmatrix, so this will be true for both arrays and matrices
    return isinstance(x, spmatrix)

def isspmatrix(x):
    return isinstance(x, spmatrix) and not isinstance(x, _sparray)
```

### Reproducing Code Example

```python
>>> import scipy as sp
>>> a = sp.sparse.csr_array(np.eye(3))
>>> m = sp.sparse.csr_matrix(np.eye(3))
>>> sp.sparse.isspmatrix(m)  # Expect True
True
>>> sp.sparse.issparse(m)  # Expect True
True
>>> sp.sparse.issparse(a)  # Expect True
True
>>> sp.sparse.isspmatrix(a)  # Expect False: problem
True
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

1.9.0.dev0+1669.b9427e1 1.22.3 sys.version_info(major=3, minor=10, micro=2, releaselevel='final', serial=0)

**Comment by rgommers** [comment]
Thanks @rossbar. I agree with the proposed semantics for `issparse` and `ismatrix`.

This shows an unfortunate issue though:
```python
def isspmatrix(x):
    return isinstance(x, spmatrix) and not isinstance(x, _sparray)
```
The sparse array classes are subclasses of the matrix classes.  That means existing `isinstance(x, spmatrix)` in the wild are not quite doing the right thing. Perhaps that was discussed in @stefanv's PR, I can't remember. It's not easy to fix, so at least it should be pointed out with a warning not to use `isinstance` near the top of http://scipy.github.io/devdocs/reference/sparse.html I think.

**Comment by rossbar** [comment]
> The sparse array classes are subclasses of the matrix classes. That means existing isinstance(x, spmatrix) in the wild are not quite doing the right thing

Agreed, though fortunately this shouldn't really be breaking existing usages of `isinstance(x, spmatrix)`, since the sparse array classes were only recently added in 1.8.

> It's not easy to fix,

I actually don't think it would be that bad. The main issue is that the `spmatrix` class is what has the concrete implementation of almost all of the methods. One idea would be to introduce a new class, say `class _SparseBase` that both `spmatrix` and `_sparray` derive from. That would clean up the inheritance model and thus resolving this issue as well, e.g.

```python
def issparse(x):
    return isinstance(x, _SparseBase)  # True for both spmatrix and sparray

def isspmatrix(x):
    return isinstance(x, spmatrix)  # Now only True for spmatrix
```

**Comment by rgommers** [comment]
That sounds like a good plan.

**Comment by perimosocordiae** [comment]
I'm not sure we need to introduce _SparseBase to accomplish this, but I agree with the proposed semantics. We should fix this sooner than later to reduce the possibility of breakage.

One side note: it's possible that this will hamper adoption of the array-style classes, as older code written with `isspmatrix` will now no longer work as intended. But maybe that's a good thing, as it's likely the older code would have subtle bugs related to slice shapes, etc.

**Comment by arogozhnikov** [comment]
> The sparse array classes are subclasses of the matrix classes.

I was very emotional after seeing my attempts to require sparse arrays failed, because:
```
isinstance(sparse_array, sp.coo_matrix) is True!
```

This breaks LSP is a bad way.

From practical side, I believe that (co-)inheritance should be avoided here. 

I see main scenarios as these:
- code operates with matrices (will check for `isspmatrix`)
- code operates with arrays (will check for `issparray`)
  - I think code shouldn't work with both at the same time: many differences that are easy to overlook
- code operates with neither (better not providing any check here)
- code accepts 'sparse whatever' only to convert it to dense or their format of choice.

Previously written code used `issparse` to pass by only scipy sparse matrices (as @perimosocordiae noted), and better just deprecate that function.

**Comment by stefanv** [comment]
@arogozhnikov You are right, of course. This is because the current sparse array implementation is a bit of a hack, building on top of matrices. We plan on addressing this in the upcoming months.

/cc @dschult @rossbar

**Comment by perimosocordiae** [comment]
Somewhat belated update: gh-18531 is introducing a `_spbase` class and separating the inheritance of `spmatrix` from `sparray`. This will resolve the `isinstance()` woes that @arogozhnikov encountered.

At the same time, we're close to merging gh-18528, which ensures that `isspmatrix()` only returns True for matrix-like sparse classes.

Once both of these land, then I think we will have resolved this issue.
