### ISSUE TITLE
BUG: shortest_path returns different paths when it should return the same path

### ISSUE THREAD

**Issue by 00sapo** [scipy/scipy#15806]
### Describe your issue.

I'm having this issue while working with a directed acyclic graph `g` with weights `w_i` in [0, 1).
The aim is to find the longest path. Therefore, I manipulate the weights to their complement `1 - w_i` for using Dijkstra or Bellman-Ford or to their inverse `-w_i` for using Bellman-Ford. 

The resulting path should be the same -- i.e. the predecessor matrix should identical.

e.g. with the following matrix:

```
[[       inf 0.85539201 0.84812456]
 [       inf        inf 0.13917551]
 [       inf        inf        inf]]
```

I compute the complement and the inverse:
```
A = [[      -inf 0.14460799 0.15187544]
     [      -inf       -inf 0.86082449]
     [      -inf       -inf       -inf]]

B = [[       -inf -0.85539201 -0.84812456]
     [       -inf        -inf -0.13917551]
     [       -inf        -inf        -inf]]
```

When using Dijkstra or Bellman-Ford on A, the result is:

```
dist = [[0.         0.14460799 0.15187544]
        [       inf 0.         0.86082449]
        [       inf        inf 0.        ]]
pred = [[-9999     0     0]
        [-9999 -9999     1]
        [-9999 -9999 -9999]]
```

When using Bellman-Ford on B, instead the result is the following:

```
dist = [[ 0.         -0.85539201 -0.99456752]
        [        inf  0.         -0.13917551]
        [        inf         inf  0.        ]]
pred = [[-9999     0     1]
        [-9999 -9999     1]
        [-9999 -9999 -9999]]
```

### Reproducing Code Example

```python
import numpy as np
import networkx as nx
from scipy.sparse.csgraph import shortest_path

# creating random directed acyclic graph
rng = np.random.default_rng(2737)
graph = nx.gnp_random_graph(3, 1, directed=True)

dag = nx.DiGraph([(u, v, {
    'weight': rng.uniform()
}) for (u, v) in graph.edges() if u < v])

# get the distance matrix
mat = nx.to_numpy_array(dag)
mat[mat == 0] = np.inf
print(mat)
print(1-mat)
print(-mat)

w1, p1 = shortest_path(1-mat, method="D", return_predecessors=True)
w2, p2 = shortest_path(1-mat, method="BF", return_predecessors=True)
w3, p3 = shortest_path(-mat, method="BF", return_predecessors=True)
print(np.all(p1 == p2))
print(np.all(p1 == p3))
print(np.all(p2 == p3))

print("----")
print(w1)
print(p1)
print("----")
print(w2)
print(p2)
print("----")
print(w3)
print(p3)
```

### Error message

```shell
.
```

### SciPy/NumPy/Python version information

1.6.1 1.22.3 sys.version_info(major=3, minor=9, micro=6, releaselevel='final', serial=0)

**Comment by jakevdp** [comment]
I think this is the expected result. With the complement weights, `0->2` has a length of 0.15, while `0->1->2` has a length of   0.14 + 0.86 ~ 1.0. With the inverse weights, `0->2` has a length of -0.84, while `0->1->2` has a length of -0.85 -0.14 = -0.99.

So it's clear that the minimum path length with complement weights is `0 -> 2`, while the minimum path length with inverse weights is `0 -> 1 -> 2`, so I would not expect the predecesors matrix to be the same for the two approaches.

**Comment by 00sapo** [comment]
Oh sorry, you're completely right! Thank you for pointing out this!
