### ISSUE TITLE
Proprietary  Matlab code clarification

### ISSUE THREAD

**Issue by ndevost** [scipy/scipy#15816]
I found out that scipy includes some code copied from Matlab.

It seems to be proprietary, so I wanted to clarify with you if it was actually the case or if you have an agreement with them on those specific [lines](https://github.com/scipy/scipy/blob/main/scipy/optimize/tests/test_minimize_constrained.py#L263).

If you do have an aggreement, would you happen to have a reference to it ?
If not then I suggest removing those, since they are only used inside tests and it is a violation. I would be happy to do a PR on that matter.

**Comment by matthew-brett** [comment]
You mean lines like this?

```
    The following optimization problem:
        minimize sum(100.0*(x[1] - x[0]**2)**2.0 + (1 - x[0])**2)
        subject to: x[0] + 2 x[1] <= 1
```

I don't think there's any way Matlab can assert copyright for the _problem_ ...  Was there some other code you were referring to?

**Comment by ilayn** [comment]
Documentation problems are not proprietary code of matlab, also we are using the problem to test the functionality. There are many examples in matlab documentation that uses famous problems without attribution hence this is not a license problem.

If you still think this is an issue please consult with mathworks.

**Comment by ndevost** [comment]
I am not sure of what line the author was referring to when he wrote: "Taken from matlab ``fmincon`` documentation."

What I know is that some Open Source Audits companies detect that as propietary code

**Comment by ndevost** [comment]
Alright @ilayn thanks for the quick reply
