### ISSUE TITLE
BUG: Import error on Mac OS

### ISSUE THREAD

**Issue by mberaha** [scipy/scipy#15833]
### Describe your issue.

All of a sudden (maybe after a system update? not sure) I get an import error complaining about a missing symbol in _ufuncs.cpython-39-darwin.so

I also tried uninstalling and force-reinstalling as well as installing from source.

### Reproducing Code Example

```python
from scipy.interpolate import splev
```
```


### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/scipy/interpolate/__init__.py", line 166, in <module>
    from ._interpolate import *
  File "/opt/homebrew/lib/python3.9/site-packages/scipy/interpolate/_interpolate.py", line 11, in <module>
    import scipy.special as spec
  File "/opt/homebrew/lib/python3.9/site-packages/scipy/special/__init__.py", line 649, in <module>
    from . import _ufuncs
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/scipy/special/_ufuncs.cpython-39-darwin.so, 2): Symbol not found: _dstevr_
  Referenced from: /opt/homebrew/lib/python3.9/site-packages/scipy/special/_ufuncs.cpython-39-darwin.so
  Expected in: flat namespace
 in /opt/homebrew/lib/python3.9/site-packages/scipy/special/_ufuncs.cpython-39-darwin.so
```
```


### SciPy/NumPy/Python version information

1.9.0.dev0+1727.b8fcb78 1.22.3 sys.version_info(major=3, minor=9, micro=10, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @mberaha, thanks for reporting. Did you strictly follow our contributors' guides to build SciPy? https://scipy.github.io/devdocs/dev/contributor/quickerstart_conda.html#quickerstart-conda or https://scipy.github.io/devdocs/dev/contributor/quickstart_mac.html#quickstart-mac

**Comment by mberaha** [comment]
Hi @tupui, I did not actually.

However the same error happens after running
```
pip3 uninstall scipy
pip3 install --upgrade --force-reinstall scipy 
```

In this case the versions are
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.8.0 1.22.3 sys.version_info(major=3, minor=9, micro=10, releaselevel='final', serial=0)
```

**Comment by tupui** [comment]
Mmm ok it sounds similar than #15784

**Comment by tupui** [comment]
@mberaha do you still have issues there?

**Comment by tupui** [comment]
Thank you for the feedback @mberaha. I just tested now and can create from scratch a new pip environment with Python 3.9 and latest SciPy on a M1. Make sure you are using the correct environment (e.g. prefer using `python -m pip install scipy`).

**Comment by mberaha** [comment]
Then it's a problem on my side... Thanks!
