### ISSUE TITLE
No win32 wheel for Python 3.10

### ISSUE THREAD

**Issue by domdfcoding** [scipy/scipy#15836]
The [current scipy release on PyPI](https://pypi.org/project/scipy/#files) lacks `win32` (32 bit Windows) wheels for Python 3.10. There are `win32` wheels for Python 3.9 and 3.8, along with `win_amd64` wheels for all three Python versions.

Is this a deliberate decision? I looked through the changelog and other issues and couldn't see anything to suggest it was.

**Comment by ilayn** [comment]
Yes 32-bit wheels are going to be dropped 1.8.0 onwards.

**Comment by tupui** [comment]
I believe we can close this. We have some extensive discussions on the wheels repo and it's something we will not forget to discuss moving forward.

**Comment by tylerjereddy** [comment]
I think I recently saw Chuck confirm that such wheels would be possible to generate here: https://github.com/MacPython/numpy-wheels/pull/157#issuecomment-1063659342

Not sure we'd want to spend energy on that though.

**Comment by rgommers** [comment]
Related: there is currently no 32-bit compiler toolchain to build wheels with for Meson. Could be fixed, but is a _lot_ of work. Dropping wheels would make sense. It doesn't preclude stragglers using MSVC + Intel Fortran to build SciPy for 32-bit. That's just not something we can do for official wheels.

**Comment by rgommers** [comment]
Also to point out where you can find 32-bit Windows binaries:
- https://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy has wheels
- The Anaconda distribution has a 32-bit flavor: https://www.anaconda.com/products/distribution

**Comment by rgommers** [comment]
gh-16286 has more relevant content; we don't need 2 separate issues about the same 32-bit Python on Windows topic, so I'll close this one.
