### ISSUE TITLE
BUG: Wasserstein Distance

### ISSUE THREAD

**Issue by xingyuuchen** [scipy/scipy#15832]
### Describe your issue.

The EMD for the following case is expected to be non-zero, but `Scipy` gives an answer of 0.

### Reproducing Code Example

```python
if __name__ == '__main__':
    from scipy.stats import wasserstein_distance
    print(wasserstein_distance([1/2, 1/2, 0, 0], [0, 0, 1/2, 1/2]))
```

### Error message

```shell
No.
```

### SciPy/NumPy/Python version information

1.5.2 1.19.2 sys.version_info(major=3, minor=6, micro=13, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Thanks @xingyuuchen for reporting. This is a statistical distance comparing the "distance" between probability measures, since you have the same elements in both arrays I don't see why it should be different than 0. Why did you expect something different?

**Comment by xingyuuchen** [comment]
> Thanks @xingyuuchen for reporting. This is a statistical distance comparing the "distance" between probability measures, since you have the same elements in both arrays I don't see why it should be different than 0. Why did you expect something different?
> 
> I am closing the issue since I am confident this is the expected result.

The Wasserstein distance is also known as the earth mover’s distance, since it can be seen as the minimum amount of “work” required to transform  `u` into `v`, where “work” is measured as the amount of distribution weight that must be moved, multiplied by the distance it has to be moved.

Obviously the two distributions are not equal, so the "work" to transport `u` into `v` is a positive number, isn't it?

**Comment by tupui** [comment]
> Obviously the two distributions are not equal, so the "work" to transport `u` into `v` is a positive number, isn't it?

Why would that be? When you would calculate the empirical CDF of both vectors, they would be exactly the same. And Wasserstein is just |CDF1 - CDF2|. The order of the elements does not matter for PDF/CDF, only the frequency does.

**Comment by xingyuuchen** [comment]
> > Obviously the two distributions are not equal, so the "work" to transport `u` into `v` is a positive number, isn't it?
> 
> Why would that be? When you would calculate the empirical CDF of both vectors, they would be exactly the same. And Wasserstein is just |CDF1 - CDF2|. The order of the elements does not matter for PDF/CDF, only the frequency does. To convince yourself, just take a 1D array of size 1000 and plot the histogram, shuffle the array and plot again the histogram. They will be strictly the same.

Thanks, I see what you mean. But in some cases the order of elements matters. e.g.,
`distribution1`: the animal has a 50% chance to be a cat, 50% to be a dog, 0% tiger, 0% lion;
`distribution2`: the animal has a 0% chance to be a cat, 0% to be a dog, 50% tiger, 50% lion,

in which case, these two differs.

**Comment by tupui** [comment]
You are not using the right tool for that. For it to work with this distance: since you have a 3-dimensional distribution, you have to either assume no correlation and do 3 analysis (and possibly combining them together in a single metric) or you need to work on the 3-dimensional distribution at once (not supported by SciPy). As it is, you described it as a 1-dimensional distribution which is wrong.

**Comment by xingyuuchen** [comment]
So how can I measure the EMD between my example (distributions of the animal prediction), is there an API?

**Comment by tupui** [comment]
I cannot say more than above. I am sorry but this is not a forum and we don't have much bandwidth. I will redirect you to StackOverflow or https://stats.stackexchange.com in your case might be appropriate.

**Comment by xingyuuchen** [comment]
Ah....
I checked the documentation again, it says the input vectors are observed values in the distribution, **not** the probability of each observed value. This would be the exact reason that my example is not appropriate.

Thanks again for your patience.

**Comment by tupui** [comment]
> Ah.... I checked the documentation again, it says the input vectors are observed values in the distribution, **not** the probability of each observed value. This would be the exact reason that my example is not appropriate.

Yes, `u` and `v` are samples from 1-d distributions.

> Thanks again for your patience.

Pleasure.
