### ISSUE TITLE
It's not that obvious that `firls` requires an even number of edges

### ISSUE THREAD

**Issue by chmendoza** [scipy/scipy#15844]
Hi!

This line requires the length of `bands` to be even:

https://github.com/scipy/scipy/blob/b5d8bab88af61d61de09641243848df63380a67f/scipy/signal/_fir_filter_design.py#L982

But from the docs, and the example that uses a flattened sequence as bands (see below), it's not that obvious that `firls` requires an even number of edges. Could this be improved/clarified in the docs? Thank you!

https://github.com/scipy/scipy/blob/b5d8bab88af61d61de09641243848df63380a67f/scipy/signal/_fir_filter_design.py#L942

**Comment by tupui** [comment]
Hi @chmendoza, thank you for reporting. Documentation improvements are always welcome.
