### ISSUE TITLE
BUG: scipy.stats.brunnermunzel incorrectly returns nan for undocumented reason

### ISSUE THREAD

**Issue by sg-s** [scipy/scipy#15843]
### Describe your issue.

```python

x = np.array([1,2,3])
y = np.array([5,6,7,8,9])

scipy.stats.brunnermunzel(x,y)

```

returns:

```
BrunnerMunzelResult(statistic=inf, pvalue=nan)
```

### Reproducing Code Example

```python
x = np.array([1,2,3])
y = np.array([5,6,7,8,9])

scipy.stats.brunnermunzel(x,y)
```

### Error message

```shell
None.
```

### SciPy/NumPy/Python version information

1.8.0 1.21.5 sys.version_info(major=3, minor=8, micro=12, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
I haven't investigated carefully, but it does not have to do with the sample sizes being unequal:
```python3
x1 = [1,2,3,4,5]
x2 = [5,6]
w, p_value = scipy.stats.brunnermunzel(x1, x2)  # OK
```
or simply that the total sample size is too small. It looks to me like we get NaN whenever the first sample has fewer than 5 observations. This should be assessed for correctness and, if it is correct, documented. 
Since `brunnermunzel` does not have an `axis` parameter, raising an error would be OK. But when there is an `axis` parameter, NaN will be the desired result (if, say, NaNs are omitted and cause the number of elements in a single slice to fall below the threshold).

**Comment by sg-s** [comment]
hi @mdhaber your counterexample is interesting. it's an issue that happens when you have small sizes and unequal sample sizes.

i should mention that it also throws this cryptic warning:

```
/Users/srinivas/opt/anaconda3/envs/longo/lib/python3.8/site-packages/scipy/stats/_stats_py.py:8055: RuntimeWarning:

divide by zero encountered in double_scalars

/Users/srinivas/opt/anaconda3/envs/longo/lib/python3.8/site-packages/scipy/stats/_stats_py.py:8061: RuntimeWarning:

invalid value encountered in double_scalars
```

meanwhile, this works:

```python
x = np.arange(0,12)
y = np.arange(5,20)

scipy.stats.brunnermunzel(x,y)
```

and so does this:


```python
x = np.arange(0,3)
y = x + 1

scipy.stats.brunnermunzel(x,y)
```

but this doesn't:


```
x = np.arange(0,3)
y = x + 3

scipy.stats.brunnermunzel(x,y)
```

**Comment by mdhaber** [comment]
Well it seems to be happening when one group is strictly greater than the other. I suspect `inf` might just be the value of the statistic you get in this case.

**Comment by mdhaber** [comment]
In your example, `df` is 0/0 in the t-approximation.
https://github.com/scipy/scipy/blob/b5d8bab88af61d61de09641243848df63380a67f/scipy/stats/_stats_py.py#L8057-L8062

If the distribution is undefined, the p-value is undefined. 
One possibility would be to emit a warning suggesting the use of a normal approximation or permutation test.

**Comment by sg-s** [comment]
@mdhaber thanks -- this is relatively straightforward, i can send you  APR

**Comment by Arech** [comment]
Hey guys, I'd like to get back to this issue and ask to reconsider it from the point of view of the test usability.

When one of the sets are strictly less/greater than the other (or when each of the sets is composed of repetitions of the same single value), the `scipy.stats.brunnermunzel()` test emits irrelevant warnings and produces non-interpretable result. This is in a stark contrast with its cousin `scipy.stats.mannwhitneyu()` test, which remains totally reasonable:

```python
>>> x,y=np.zeros((10,)),np.ones((10,))
>>> s=scipy.stats.brunnermunzel(x,y)
...\scipy\stats\_stats_py.py:8819: RuntimeWarning: divide by zero encountered in scalar divide
  wbfn /= (nx + ny) * np.sqrt(nx * Sx + ny * Sy)
...\scipy\stats\_stats_py.py:8825: RuntimeWarning: invalid value encountered in scalar divide
  df = df_numer / df_denom
...\scipy\stats\_axis_nan_policy.py:586: RuntimeWarning: p-value cannot be estimated with `distribution='t' because degrees of freedom parameter is undefined (0/0). Try using `distribution='normal'
  res = hypotest_fun_out(*samples, **kwds)
>>> # WTH is this above???
>>> s
BrunnerMunzelResult(statistic=np.float64(inf), pvalue=np.float64(nan))
>>> s=scipy.stats.mannwhitneyu(x,y)
>>> s
MannwhitneyuResult(statistic=np.float64(0.0), pvalue=np.float64(1.593791168806624e-05))
```
(behaviour is the same in v1.10-1.15.2)

IMO, even if the canonical test itself doesn't handle this, this seem irrelevant from a user's point of view. I want to get an answer about my two sets and given how the test works now - I might get it sometimes, but sometimes - not. This is wrong, imo...
