### ISSUE TITLE
CI: Windows Meson job failing sometimes on OpenBLAS binary download

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#15854]
I've seen this a bunch of times now:
```
 Installing collected packages: certifi, urllib3, tqdm, soupsieve, six, PySocks, idna, filelock, charset-normalizer, requests, beautifulsoup4, gdown
Successfully installed PySocks-1.7.1 beautifulsoup4-4.10.0 certifi-2021.10.8 charset-normalizer-2.0.12 filelock-3.6.0 gdown-4.4.0 idna-3.3 requests-2.27.1 six-1.16.0 soupsieve-2.3.1 tqdm-4.63.0 urllib3-1.26.9
C:\hostedtoolcache\windows\Python\3.9.10\x64\lib\site-packages\gdown\cli.py:127: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1G3jwxMY4ZVRqvz6owl0kmw_Innmr4ZnV 

Access denied with the following error:
unzip:  cannot find either openblas_32_if.zip or openblas_32_if.zip.zip.
```

~20% of the actions on the first page of https://github.com/scipy/scipy/actions/workflows/windows.yml show this failure. @matthew-brett it'd be nice if we could move this, or could make the download more robust somehow. What do you think?

**Comment by matthew-brett** [comment]
Sure - moving it seems like a good idea.   It could go in a submodule I guess - do we have a favored place for binary downloads?

**Comment by rgommers** [comment]
A submodule doesn't quite work, that makes it visible for everyone rather than only our CI and the handfuls of Windows contributors. I think all we need is a more reliable place than GDrive + `gdown`. I think putting it on GitHub itself in a separate repo under the SciPy org should do it. And then grab it with either `git` or `curl`.

**Comment by mattip** [comment]
The MacPython/openblas-lib repo uploads to https://anaconda.org/multibuild-wheels-staging/openblas-libs/files. I think it would be fine if SciPy would also upload there. I didn't know SciPy builds its own OpenBLAS, is there some incompatibility with the way MacPython/openblas-libs is building for windows?

**Comment by rgommers** [comment]
@mattip I believe so, it needs to be built with the MinGW toolchain that SciPy is also built with. @matthew-brett built it that way. A write up with more details on that will be added to the docs in the near future.
