### ISSUE TITLE
ENH: scipy.optimize.minimize method='Nelder-Mead': behavior when clipping starting simplex

### ISSUE THREAD

**Issue by bwheelz36** [scipy/scipy#15858]
### Is your feature request related to a problem? Please describe.

If a user provides bounds for their parameters, the starting simplex will be clipped according to those bounds (this happens at line 783 of scipy/optimize/_optimize in the current main branch).
In some situations, the 'clipped' starting simplex can be quite different to what was expected. The documents are clear on this so it's my fault for not realizing it was happening sooner; I have some suggestions around this behavior though.

### Describe the solution you'd like.

1. I think if the starting simplex gets clipped, a warning should be thrown. The same for when x0 gets clipped.
2. In the scipy implementation (which I have copied and modified) generation of the starting simplex  is based on a proportion of x0, like this:

```python
y[k] = (1 + nonzdelt)*y[k]
```

I would suggest that we could add a line that checks if this violates supplied bounds. If it does, throw a warning and try the reverse:

```python
y[k] = (1 - nonzdelt)*y[k]
```

Thanks!

**Comment by bwheelz36** [comment]
Here's the implementation I will put in my code (it's basically the same as the default but the user can change ```nonzdelt```)
This or something like it could replace the code currently at line 743 of scipy/optimize/_optimize

```python
for k in range(N):
    y = np.array(self.StartingValues, copy=True)
    if y[k] != 0:
        store_yk_temp = y[k]  # yuck, surely someone can do better than this
        y[k] = (1 + nonzdelt) * y[k]
        if y[k] > self.UpperBounds[k]:
            y[k] = (1 - nonzdelt) * store_yk_temp
        if y[k]  < self.LowerBounds[k]:
            logger.warning('unable to generate starting simplex within bounds. Simplex will be clipped to bounds.'
                           'To avoid this behavior, consider changing the starting point, bounds, or value of'
                           'NM_StartingSimplexRelativeVal')
```

**Comment by tupui** [comment]
Hi @bwheelz36, thank you for reporting. Is this alternative method describe in any paper?

**Comment by bwheelz36** [comment]
Hey, not that I'm aware of - I don't think it's complicated enough to be in a paper! It's just a slight tweak to how a simplex would be auto-generated based on a starting point. At the moment, it always makes vertices that are larger than x0, but I don't think there's any a priori reason for making them larger than x0 rather than smaller than x0 - we are just trying to generate a simplex that spans a certain range of the search space. Of course, the user always has the option to just supply their own simplex.

I just implemented this for my code, and it made a huge difference. That is a real 'edge case', because I randomly generate my start point and in this particular instance it was right next to the upper bounds. Assuming you pick your start point somewhere in the middle of your bounds, this situation will rarely arise anyway. 

I drew out the image below explaining the idea  in 1D, hopefully this explain the idea a bit better. Read the text in order of the 1,2,3 labels.

![image](https://user-images.githubusercontent.com/64300337/160016076-c317c739-19e5-4287-b743-5f7630a4c1f4.png)

**Comment by tupui** [comment]
Yes I understood, but it's still a change of direction. I would say it should not be problematic if the bounds are far enough (ill defined) from the optimum, but if the solution happens to be close to bounds it can be an issue. This strategy would effectively prevent to put points close to the bounds. IMO this is not wanted because you should always try to define sensible bounds.

@andyfaff what do you think?

**Comment by bwheelz36** [comment]
1. In general we have no idea where the optimal point is, so i don't really think it makes more sense to be focused on x0+some_number as opposed to x0-some_number - these are both equally valid starting simplex's. 
2. If I recall correctly, the first (or at least one of the first) operation should be a reflection of the simplex. So if you start with a large simplex that gets reflected, you will hit this bound anyway. But if you start off with a truncated simplex you will be spanning a much smaller part of the objective function than you intended.

**Comment by tupui** [comment]
Currently, we clip to bounds so if the solution is as/close to the boundary, the search domain still includes it. On the other hand, if we do not go up to the bound (right on your fig), but the other way (left on your fig), we are discarding a part of the domain (the right part). If the optimum happens to be in this region, we will miss it.

**Comment by bwheelz36** [comment]
"we are discarding a part of the domain (the right part)."

Sorry, that is not correct. Maybe I'm not being clear. I'm not suggesting you reflect the simplex **every** time it hits the bound - only when it is first generated. The solution does **not** have to lie within the starting simplex (although that would probably always help) - what is important to general convergence is generating a starting simplex that spans an appropriate part of the domain. 

I have attached some code to demonstrate minimising the rosebrock function with a starting point of [0.99, 0.99], an upper bound of [1,1] and a minimum at [.5,0.25] - admittedly a far-fetched set up, but helpful for demonstration. 

I have run this example for three cases:

1. Default scipy settings
2. Reflected starting simplex, nozdelta=.05 (scipy default)
3. Reflected starting simplex, larger nozdelta=0.2 (larger simplex)

I have plotted the results in excel (I am ashamed to admit that in public but I also want to go to bed :-P). You can see that all three cases converge but that the latter two cases converge faster. I am actually a bit surprised the first case converges tbh, it would be better for my example if it didn't, but just trust me that in some cases I have seen that this is a problem!

![image](https://user-images.githubusercontent.com/64300337/160385865-17aadc9a-b75c-42ea-a5b8-78f16692c87e.png)

OK, what about your concern: what if the true minimum lies at say .995, and we reflect the starting simplex away from this? you can edit the attached code to test this if you want, but I just did and I can tell you that again all three cases converge. It's not actually a great example because the optimiser in that case basically starts at the minimum, but importantly you can easily see from the values of {x} logged to screen that cases 1 and 2 do **not** exclude the right hand side of the domain.

```python
from scipy.optimize import minimize
import numpy as np

def rosenbrock_function(x, a=.5, b=.5, print_current_values=True):
    """
    has a global minimum at a,a**2. In this case, [.5,.25] to simulate a case where the minimum
    is relatively far away from both the startin point and the bounds.

    You can play with where the minimum is to simulat various scenarios.
    """
    f = (a - x[0]) ** 2 + (b * (x[1] - (x[0]) ** 2) ** 2)
    if print_current_values:
        # can be useful for debugging
        print(f'x0: {x[0]:1.2f}, x1: {x[1]: 1.2f}, f: {f: 1.2f}')
    return f


def _get_starting_simplex(x0, upper_bounds, lower_bounds, nonzdelt=.05, TurnOnMirroringOfStartingSimplex=True):
    """
    This is the same as the current code to generate the starting simplex, EXCEPT

    1. nonzdelt is set be the user (hard coded to 0.05 in scipy)
    2. TurnOnMirroringOfStartingSimplex allows one to turn on/ off the feature under discussion
        [here](https://github.com/scipy/scipy/issues/15858)
    """

    N = len(x0)
    zdelt = nonzdelt / 200  # based on the scipy code where zdelt - nonzdelt/200
    sim = np.empty((N + 1, N), dtype=x0.dtype)
    sim[0] = x0
    for k in range(N):
        y = np.array(x0, copy=True)
        if y[k] != 0:
            store_yk_temp = y[k]  # yuck, surely someone can do better than this
            y[k] = (1 + nonzdelt) * y[k]
            if TurnOnMirroringOfStartingSimplex:
                if y[k] > upper_bounds[k]:
                    y[k] = (1 - nonzdelt) * store_yk_temp
                if y[k] < lower_bounds[k]:
                    print('unable to generate starting simplex within bounds. Simplex will be clipped to bounds.'
                                   'To avoid this behavior, consider changing the starting point, bounds, or value of'
                                   'NM_StartingSimplexRelativeVal')
        else:
            y[k] = zdelt
        sim[k + 1] = y

    return sim

# problem set up
upper_bounds = np.array([1, 1])
lower_bounds = np.array([-1, -1])
start_point  = np.array([.99, .99])  # note start point right next to upper bounds

# case 1. Minimise rosenbrock with default settings:
bnds = tuple(zip(lower_bounds, upper_bounds))
function_calls = 0
NMresult = minimize(rosenbrock_function, x0=start_point, method='Nelder-Mead', bounds=bnds,
                       options={'disp': True, 'maxiter': 100})


# case 2. Minimise rosenbrock with reflected starting simplex
starting_simplex = _get_starting_simplex(start_point, upper_bounds, lower_bounds,
                                         nonzdelt=.05, TurnOnMirroringOfStartingSimplex=True)
NMresult = minimize(rosenbrock_function, x0=start_point, method='Nelder-Mead', bounds=bnds,
                       options={'disp': True, 'maxiter': 100, 'initial_simplex': starting_simplex})

# case 3. Minimise rosenbrock with reflected starting simplex, larger span
starting_simplex = _get_starting_simplex(start_point, upper_bounds, lower_bounds,
                                         nonzdelt=.2, TurnOnMirroringOfStartingSimplex=True)
NMresult = minimize(rosenbrock_function, x0=start_point, method='Nelder-Mead', bounds=bnds,
                       options={'disp': True, 'maxiter': 100, 'initial_simplex': starting_simplex})
```

**Comment by tupui** [comment]
> "we are discarding a part of the domain (the right part)."
> 
> Sorry, that is not correct. Maybe I'm not being clear. I'm not suggesting you reflect the simplex **every** time it hits the bound - only when it is first generated. The solution does **not** have to lie within the starting simplex (although that would probably always help) - what is important to general convergence is generating a starting simplex that spans an appropriate part of the domain.

Thanks for clarifying this point.

> I have plotted the results in excel (I am ashamed to admit that in public but I also want to go to bed :-P). You can see that all three cases converge but that the latter two cases converge faster. I am actually a bit surprised the first case converges tbh, it would be better for my example if it didn't, but just trust me that in some cases I have seen that this is a problem!

FYI, we have a benchmark suite with more than 100 optimisation functions (`SCIPY_XSLOW=1` and see the benchmark folder)

**Comment by bwheelz36** [comment]
OK, well... what happens from here? I can test running the change over all the benchmark functions, but as I mentioned I think it is an edge case - I guess in nearly all situations it makes no difference. I just think in a small minority of cases it can substantially improve results. But if there is no interest/consensus on this then I suppose we just close the issue? 

The other change I think would be very helpful for users and hopefully uncontroversial is to make nonzdelt a user accessible parameter. Although it is already possible for users to generate their own simplex, this is a pretty big ask for casual users, whereas providing a single parameter where higher value=more exploration just makes this algorithm a bit more accessible beyond the initial 'tried it, didn't work'.

**Comment by tupui** [comment]
We work on a "lazy consensus", meaning it would be good to have another maintainers' view on this. On my side, if there is no literature around the proposal, we should at least run the benchmark and show similar performances with and without the change.

@andyfaff can you advice here?

If there is no reply, you can try sending an email to the mailing list to attract more people.

**Comment by bwheelz36** [comment]
I'm going to close this as I realistically don't have time to do it...
