### ISSUE TITLE
BUG: Generalized Gamma PDF Wrong

### ISSUE THREAD

**Issue by kevinpalm** [scipy/scipy#15864]
### Describe your issue.

I think scipy's implementation of the generalized gamma distribution's PDF is wrong when the second shape parameter is not equal to 1.

### Reproducing Code Example

```python
from math import gamma, exp
import pandas as pd
from scipy.stats import gengamma
%matplotlib inline

def generalized_gamma_pdf(x, a, d, p):
    # copied from https://en.wikipedia.org/wiki/Generalized_gamma_distribution
    return (p/a**d)*x**(d-1)*exp(-(x/a)**p)/gamma(d/p)

ax = pd.Series([gengamma.pdf(float(x), 1, 5, scale=5) for x in range(10)]).plot(color='blue') # doesn't match wikipedia plot, even if you try swapping shape parameters
pd.Series([generalized_gamma_pdf(float(x), 5, 1, 5) for x in range(10)]).plot(color='red', ax=ax) # does match wikipedia plot
```

### Error message

```shell
NA
```

### SciPy/NumPy/Python version information

1.2.1 1.16.4 sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)

**Comment by rkern** [comment]
Please note that [our parameterization follows a different convention](https://scipy.github.io/devdocs/reference/generated/scipy.stats.gengamma.html) than Wikipedia's; neither is wrong, just different. `generalized_gamma_pdf(x, a, d, p)` corresponds to `gengamma.pdf(x, d/p, p, scale=a)`.

**Comment by kevinpalm** [comment]
Oh thank you, got it!
