### ISSUE TITLE
ENH: Implement a method to get modes of `rv_frozen`

### ISSUE THREAD

**Issue by KOLANICH** [scipy/scipy#15862]
### Is your feature request related to a problem? Please describe.

Needed to access this in unified way.

### Describe the solution you'd like.

`dist.modes()`, or even better, `dist.modes`, returning a tuple of modes, sorted by PDF in that point in descending order.

### Describe alternatives you've considered.

Sort by variable value.

**Comment by mdhaber** [comment]
This is a more specific version of gh-14895, which asks for `mode` in all distributions, not just frozen ones, so I'll close this.
Please clarify how multiple modes would be sorted by PDF. Wouldn't all the PDFs be the same by definition?
