### ISSUE TITLE
BUG/CI:  Wrong python version used for tests labeled "Linux Tests / NumPy main"

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#15866]
### Describe your issue.

The file [linux.yml](https://github.com/scipy/scipy/blob/main/.github/workflows/linux.yml) in `.github/workflows` defines a test job `test_numpy_main` (with `name: NumPy main`), and according to the settings in that file, the job is supposed to run with Python 3.10.  Error messages in test failures on the main branch show that it is actually using Python 3.8.

**Comment by WarrenWeckesser** [comment]
It looks like the relevant change was in https://github.com/scipy/scipy/pull/14832 (back in November).  @tupui, do you recall why the explicit installation and use of Python 3.10 was removed for this job?  It looks like the job now uses the system python, which is apparently 3.8.

**Comment by tupui** [comment]
Indeed, thanks for noticing this. I actually should have remove the matrix thing which confused me. I will send a PR now to fix this.

**Comment by andyfaff** [comment]
Iirc that job was originally designed for testing pre release versions of python.

**Comment by tupui** [comment]
It is yes, we just disabled this part for now until there is a RC of 3.11. This is why the matrix is still there. Also we might be able to remove the custom code because GH provides pre-release versions now.
