### ISSUE TITLE
BUG: stats: Test failure of `TestTruncnorm.test_moments` on CI

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#15871]
The stats test `TestTruncnorm.test_moments` is <strike>consistently</strike> sporadically failing in the github actions job `Linux Tests / NumPy main 3.10`.  Here's a typical error report from the CI log:
```
__________________________ TestTruncnorm.test_moments __________________________
../testenv/lib/python3.10/site-packages/scipy/stats/tests/test_distributions.py:987: in test_moments
    self._test_moments_one_range(-20, -19, [-19.0523439459766628,
        self       = <scipy.stats.tests.test_distributions.TestTruncnorm object at 0x7f5ffd3e4430>
../testenv/lib/python3.10/site-packages/scipy/stats/tests/test_distributions.py:947: in _test_moments_one_range
    assert_almost_equal(k, k0)
E   AssertionError: 
E   Arrays are not almost equal to 7 decimals
E   
E   Mismatched elements: 1 / 1 (100%)
E   Max absolute difference: 1.9596281e-05
E   Max relative difference: 3.3373635e-06
E    x: array(5.8718046)
E    y: array(5.871785)
```
Fixing this will not be as simple as tweaking the test tolerances.  The problem is that the skewness and kurtosis values that we are using as the true values (i.e. the expected values) are not very accurate.  For example, the true value in the test log above (for the kurtosis when the interval is [-20, -19]) should be `5.871801893091683`.  The computed value is closer to the true value than to the value used in the test, with an actual relative error of about 5e-7.  For the test of the kurtosis with the interval [39, 40] (which is pretty darn far out in the tail), the expected value used in the test is `5.6167758371700494`, but the true value is actually `5.968744357649675`.

I put a script that uses `mpmath` to compute the true values for all the intervals used in the test `TestTruncnorm.test_moments` in a [gist](https://gist.github.com/WarrenWeckesser/636b537ee889679227d53543d333a720).  The table output of the script is:

```
     a      b                     mean                 variance                 skewness          excess kurtosis
   -30     30                      0.0                      1.0                      0.0                      0.0
   -10     10                      0.0                      1.0                      0.0  -1.4927521335810455e-19
    -3      3                      0.0       0.9733369246625415                      0.0     -0.17111443639774404
    -2      2                      0.0       0.7737413035499232                      0.0      -0.6344632828703505
     0   +inf       0.7978845608028654       0.3633802276324187        0.995271746431156       0.8691773036059741
  -inf      0      -0.7978845608028654       0.3633802276324187       -0.995271746431156       0.8691773036059741
    -1      3        0.282786110727154       0.6161417353578293       0.5393018494027877     -0.20582065135274694
    -3      1       -0.282786110727154       0.6161417353578293      -0.5393018494027877     -0.20582065135274694
   -10     -9       -9.108456288012409     0.011448805821636248      -1.8985607290949496       5.0733461105025075
   -20    -19      -19.052343945976656     0.002725073018195613      -1.9838693623377885        5.871801893091683
   -30    -29      -29.034401237736176    0.0011806604886186853      -1.9929615171469608        5.943905539773037
   -40    -39       -39.02560741993011    0.0006548827702932775      -1.9960847672775606        5.968744357649675
    39     40        39.02560741993011    0.0006548827702932775       1.9960847672775606        5.968744357649675
```
If the end of the script is changed to call `print_test_code(check_intervals)`, it prints Python code containing this data that can be used with a parametrized unit test.

A first step towards fixing the failing tests is to get this data into the unit test.  Then it will be necessary to figure out just how accurately we can expect to calculate these statistics, especially for intervals far out in a tail of the normal distribution.  I suspect we'll have to adjust the acceptable tolerances of the tests, permitting greater error the further out in the tail the interval lies.

**Comment by lobpcg** [comment]
This makes unrelated PRs to fail making debugging more difficult. Maybe you could fix it temporarily asap by changing the tolerance, while looking for a permanent fix?

**Comment by mdhaber** [comment]
I think that's a good idea. I'll submit a temporary patch that will not close the issue.

**Comment by tylerjereddy** [comment]
For now, I merged Matt's tolerance bump to keep CI running smoothly--hopefully Warren doesn't mind as long as this stays open for the "real investigation."
