### ISSUE TITLE
BUG:  a sentence in stats.norm's docstring seems incorrect 

### ISSUE THREAD

**Issue by clwez** [scipy/scipy#15918]
### Describe your issue.

Specifically, norm.pdf(x, loc, scale) is identically equivalent to norm.pdf(y) / scale with y = (x - loc) / scale.Here 'pdf' should be repalced by cdf

### Reproducing Code Example

```python
.
```

### Error message

```shell
.
```

### SciPy/NumPy/Python version information

.

**Comment by ev-br** [comment]
Why would that be? For PDF, normalization condition (that the integral of PDF over the support equals one) dictates the division by scale for the PDF. 

https://github.com/scipy/scipy/blob/main/scipy/stats/_distn_infrastructure.py#L2127
