### ISSUE TITLE
BUG: Wrong Answer with `scipy.optimize.linprog`

### ISSUE THREAD

**Issue by Smit-create** [scipy/scipy#15912]
### Describe your issue.

I am trying to solve the following dual problem:

<img width="889" alt="Screenshot 2022-04-01 at 4 18 52 PM" src="https://user-images.githubusercontent.com/55887635/161249895-09f531e0-8882-46c2-a7aa-553543879db0.png">

The variables of the problem are defined as:
<details>
<summary> Variables </summary>
<p>

```py
# Define parameters
N = 2
M = 4
ql = 1   # an arbitrary value for ql
qu = 10  # an arbitrary value for qu
Phi = np.array([[ql-0,ql-1,ql-4,ql-5],[qu-0,qu-1,qu-4,qu-5]])
u = np.reshape(np.array([0**0.5,1**0.5,4**0.5,5**0.5]),(4,1))
w = 1.5
p = np.reshape(np.array([1/2,1/2]),(2,1))

# Vectorlize matrix Phi
Phi_vec = Phi.reshape(N*M,1,order = 'F')

# Construct matrix A by Kronecker product
A1 = np.kron(u.T,np.ones((1,N)))
A2 = np.kron(np.ones((1,M)),np.identity(N))
A3 = np.kron(np.ones((1,M)),np.ones((1,N)))
A = np.vstack([A1,A2,A3])

# Construct vector b
b = np.vstack([w,p,1])

bounds = [(0,None)] * N*M

X = list(range(N))
Y = list(range(M))
```
</p>
</details>

Solution using `scipy.optimize.linprog`

<details>
<summary> Solution 1 </summary>
<p>

```py
# Solve the dual problem
res_d = linprog(b, A_ub = -A.transpose(), b_ub = -Phi_vec)

print("success:",res_d.success)
print("fun:",round(res_d.fun,2))
print("nu_1:",round(res_d.x[0],2))
print("mu:",np.round([res_d.x[i] for i in [1,2]],2))
print("nu_2:",round(res_d.x[3],2))
```
Output:
```
success: True
fun: 5.5
nu_1: 0.0
mu: [0.51 9.51]
nu_2: 0.49
```
</p>
</details>

Here, Scipy gives the wrong solution. Theoretically, dual problems' object function values are no greater than primal problems'. To guarantee our conclusion, we use CVXPY to implement

<details>
<summary> Solution 2 </summary>
<p>

```py
# Define variable _lambda
_lambda = cp.Variable((4,1))

# Define objective function
obj_expr_d = b.transpose() @ _lambda
obj_d = cp.Minimize(obj_expr_d)

# Define constraints
constraints_d = [A.transpose() @ _lambda >= Phi_vec]

# Create the model
cvxpy_dual = cp.Problem(obj_d,constraints_d)

# Solve the dual problem
cvxpy_dual.solve()

# print the result
print("status:", cvxpy_dual.status)
print("fun:", np.round(obj_expr_d.value,2))
print("nu_1:", np.round(_lambda.value[0],2))
print("mu:", np.round([_lambda.value[1]],2), np.round([_lambda.value[2]],2))
print("nu_2:", np.round(_lambda.value[3],2))
```

Output:
```
status: optimal
fun: [[3.]]
nu_1: [-3.]
mu: [[-2.]] [[7.]]
nu_2: [5.]
```
</p>
</details>

### Reproducing Code Example

```python
Same as the above code snippets.
```

### Error message

```shell
NA
```

### SciPy/NumPy/Python version information

1.7.1 1.20.3 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
Please check your `bounds`. All decision variables are non-negative by default. I see the CVXPY solution has some negative values.

**Comment by Smit-create** [comment]
> Please check your `bounds`. All decision variables are non-negative by default. I see the CVXPY solution has some negative values.

Oh, thanks for pointing that. It fixed the problem!
