### ISSUE TITLE
BUG: Inconsistent handling of INF and NAN in signal.convolve

### ISSUE THREAD

**Issue by kohlerjl** [scipy/scipy#15927]
### Describe your issue.

When one of the input vectors to signal.convolve contains an INF or NAN value, the returned vector differs depending whether method='fft' or method='direct' is used. 

When computing the convolution with method='direct,' an INF or NAN value in the longer of the two arrays would only result in a sequence of INF or NANs in the output with the same length as the shorter of the two vectors, as one might expect from the definition of the convolution.

However, when method='fft' is used, a single NaN value results in the entire FFT and therefore output array being NaN. This behavior can lead to particularly subtle bugs when using the default method='auto', as the behavior will differ depending on the size of the inputs.

This behavior should at least be documented. In addition, a warning could be raised if the FFT method is used and the first value of the resulting vector is NaN.

### Reproducing Code Example

```python
# Generate random signal vector
sig_nan = np.random.randn(1000)
# Replace single value with INF or NAN
sig_nan[100] = np.nan

# Form low-pass FIR filter window
coeffs = signal.firwin(200, 0.2)

# Compute convolution with method='direct'
filt_direct_nan = signal.convolve(sig_nan, coeffs, mode='same', method='direct')
# Compute convolution with method='fft'
filt_fft_nan = signal.convolve(sig_nan, coeffs, mode='same', method='fft')

# Check equality
np.all(filt_direct_nan == filt_fft_nan)
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

1.8.0 1.22.3 sys.version_info(major=3, minor=10, micro=2, releaselevel='final', serial=0)

**Comment by v0dro** [comment]
Changing either the direct or FFT transformation techniques would involve making changes to the core methods themselves, which is not the core issue here. I will fix this by sending over a patch that will specify this behavior in the documentation as a note, and raise a warning in case the method used is FFT and a NAN value is present in the output.
