### ISSUE TITLE
Analog and digital version of butterworth filter

### ISSUE THREAD

**Issue by haotianh9** [scipy/scipy#15937]
Hello scipy developers,
    I have a question about the analog and digital version of butterworth filter (scipy.signal.butter). I tried two things to get a digital butterworth filter, one is directly get from the function `scipy.signal.butter`  with `analog=False`, the other is getting a analog filter by  `scipy.signal.butter`  with `analog=True`, and then use `scipy.signal.bilinear `  to transform it into a digital filter, but I got different results from the two methods. I'd like to ask whether I should expect same result from this? My code and out put is attached. Thank you!

Code:

```
from scipy import signal
[b1,a1]=signal.butter(1,1,'high',analog=True)
print("analog filter: ",[b1,a1])
[b2,a2]=signal.bilinear(b1,a1,fs)
print("digital filter got from bilinear transformation of analog filter: ",[b2,a2])
fs=100
[b,a]=signal.butter(1,1*2/fs, 'high',analog=False)
print("digital filter: ",[b,a])
```
Output:
```
analog filter:  [array([1., 0.]), array([1., 1.])]
digital filter got from bilinear transformation of analog filter:  [array([ 0.99502488, -0.99502488]), array([ 1.        , -0.99004975])]
digital filter:  [array([ 0.96953125, -0.96953125]), array([ 1.        , -0.93906251])]
```

**Comment by tupui** [comment]
Hi @haotianh9, thank you for reporting. I am sorry but we don't answer user questions here as we don't have the bandwidth to. Please ask on other medium such as StackOverflow.
