### ISSUE TITLE
AttributeError: module 'scipy' has no attribute 'signal'

### ISSUE THREAD

**Issue by insung3511** [scipy/scipy#15941]
```python
import matplotlib.pyplot as plt
from scipy import signal as sp
from time import time
import medfilt as mf
import pandas as pd
import numpy as np
```
I import some python modules and I using scipy on print like this.
```python
print(sp.signal.medfilt(all_result))
```
But Idk reason why got a error that can't find scipy.signal module. Its already install scipy module and no problem import that module. Please help.

---
Hardware
- Macbook pro (M1, 2020)

Software
- macOS Monterey
- Python (anaconda) 3.9.4

Raw Error
```
Traceback (most recent call last):
  File "/Users/bahk_insung/Documents/Github/ecg-dbn/data/median_filter.py", line 37, in <module>
    print(sp.signal.medfilt(all_result))
AttributeError: module 'scipy.signal' has no attribute 'signal'
```

**Comment by insung3511** [comment]
I was idiot. sp.medfilt is right way. sorry guys. 🥲

**Comment by MrDyna** [comment]
from scipy import signal
print(signal.medfilt(all_result))
