### ISSUE TITLE
Are docs for the two-sample Kolmogorov-Smirnov test not correct?

### ISSUE THREAD

**Issue by StefanR44** [scipy/scipy#15942]
In the last section it says:
"For an identical distribution, we cannot reject the null hypothesis since the p-value is high, 41%:"

```
rvs4 = stats.norm.rvs(size=n2, loc=0.0, scale=1.0, random_state=rng)
stats.ks_2samp(rvs1, rvs4)
KstestResult(statistic=0.12166666666666667, pvalue=0.05401863039081145)
```

but the pvalue is 0.054? Or am I simply not understanding something? The part before that also seems to be wrong.

Link to the page : https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ks_2samp.html

Screenshot of what im referring to: 
![image](https://user-images.githubusercontent.com/90157240/161784034-5d5702c1-d405-414b-a5f9-8505f9c1b5ff.png)

I am looking forward to your input!

**Comment by mdhaber** [comment]
They were not. This was reportedin gh-15644 and fixed in PRs linked from there. Please find the `main` branch version of the docs [here] (http://scipy.github.io/devdocs/reference/stats.html#module-scipy.stats). Do those resolve the issue?
