### ISSUE TITLE
BUG: Power operator behaviour for sparse arrays

### ISSUE THREAD

**Issue by jpdehollain** [scipy/scipy#15948]
### Describe your issue.

Currently, applying the `**` operator to a sparse array implements the `numpy.linalg.matrix_power` function. This is not compatible with the `np.array` implementation of `**`, which does element-wise power. This should be fixed as part of the migration from sparse "matrices" to sparse "arrays". Additionally, the `matrix_power` function should then also be included in the `sparse.linalg` package.

### Reproducing Code Example

```python
from scipy.sparse import csr_array, random

A = csr_array(random(5,5,0.1))
print(A.A)  
print((A**2).A)  #This does matrix_power, eventhough it is initialised as a sparse array (not a matrix)
print((A.A)**2)  #This does element-wise power, since it is a numpy array
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

1.8.0 1.20.3 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by cahitkargi** [comment]
My duplicate issue (#15950) is closed, but there is a slight difference which might be important for you, so I just want to comment here. 
This issue is for sparse arrays, and the same problem occurs also with the sparse matrices (which, I guess, is no longer supported ?)

```python
import scipy.sparse as sp

someMatrix = sp.csc_matrix(([1, -1], ([0, 1], [1, 0])), shape=(2, 2))

print(someMatrix.A)                 # print the matrix
print((someMatrix**2).A)        # raises the matrix to a power
print((someMatrix.A)**2)        # element-wise power   
```

**Comment by kutal10** [comment]
@perimosocordiae Could this please be assigned to me? Happy to take a look - looks like it'll also need tests added to make sure the overrides work

**Comment by perimosocordiae** [comment]
Go for it! Please tag me when your PR is ready to review.

**Comment by asmijafar20** [comment]
Hey! Is this issue still up? I would like to take it. Thanks.
