### ISSUE TITLE
ENH: generelize scipy.linalg.lstsq to complex numbers

### ISSUE THREAD

**Issue by gideonKogan** [scipy/scipy#15952]
### Is your feature request related to a problem? Please describe.

Generalization of the least square solution to complex numbers

**Comment by mdhaber** [comment]
I'm not certain, but it looks like `scipy.linalg.lstsq` has always supported complex input.

```python3
import numpy as np
from scipy import linalg
m, n = 6, 5
A = np.random.rand(m, n) + np.random.rand(m, n)*1j
b = np.random.rand(m) + np.random.rand(m)*1j
for driver in ['gelsd', 'gelsy', 'gelss']:
    x, residues, rank, s = linalg.lstsq(A, b, lapack_driver=driver)
    print(np.linalg.norm(A @ x - b)**2)
# .06310500909751662
# 0.06310500909751657
# 0.06310500909751662
```

I'll go ahead and close, but please follow-up with more information if I've misunderstood.
