### ISSUE TITLE
Transform object has no atttribute '__getitem__'

### ISSUE THREAD

**Issue by MohamadHalwani** [scipy/scipy#15957]
I'm trying to compile a python code which has the following 
```
TCP_transformation_matrix = np.eye(4)
        TCP_transformation_matrix[:3, :3] = R.from_rotvec(self.pose[3:]).as_dcm()
        TCP_transformation_matrix[0, 3] = self.pose[0]
        TCP_transformation_matrix[1, 3] = self.pose[1]
        TCP_transformation_matrix[2, 3] = self.pose[2]
```
and I'm getting this issue !
```
 File "*", line 265, in update_poses
    TCP_transformation_matrix[:3, :3] = R.from_rotvec(self.pose[3:]).as_dcm()
TypeError: 'Transform' object has no attribute '__getitem__'
```
R is the transform object assigned as follows:
`from scipy.spatial.transform import Rotation as R`

**Comment by tupui** [comment]
Hi @MohamadHalwani, thank you for reporting. Please can you update the issue report by following our template? A few things are missing such as the versions numbers and the code snippet is not complete.

**Comment by WarrenWeckesser** [comment]
Without a reproducible example, we can't provide any help here.  I'm closing the issue, but we can reopen it if code is provided that demonstrates that this is a problem with the SciPy library.
