### ISSUE TITLE
wilcoxon produces different results with same code

### ISSUE THREAD

**Issue by jnehring** [scipy/scipy#15969]
### Describe your issue.

My colleague and me run the same code for scipys wilcoxon signed rank test and we got different results.

Setup a: Ubuntu Linux with scipy version 1.4.1 produces a p value of 0.04088813291185591

Setup b: Windows 10 with scipy version 1.7.1 produces a p value of 0.041259765625

We would expect the same results from the same code.

### Reproducing Code Example

```python
# from the documentation: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wilcoxon.html#scipy-stats-wilcoxon

d = [6, 8, 14, 16, 23, 24, 28, 29, 41, -48, 49, 56, 60, -67, 75]
from scipy.stats import wilcoxon
w, p = wilcoxon(d)

print(w,p)
```

### Error message

```shell
no error message
```

### SciPy/NumPy/Python version information

1.7.1, 1.4.1

**Comment by mdhaber** [comment]
The important difference is the different version of SciPy.
In `main`:
```python3
d = [6, 8, 14, 16, 23, 24, 28, 29, 41, -48, 49, 56, 60, -67, 75]
from scipy.stats import wilcoxon
w, p = wilcoxon(d)
print(w, p) # (24.0, 0.041259765625)
w, p = wilcoxon(d, mode='approx')
print(w, p) # (24.0, 0.04088813291185591)
```
Reading the documentation of 1.4, I would have expected it to be producing an exact p-value, too, but it appears to be producing an approximate p-value (using a normal approximation). 1.7 is producing the exact p-value.
