### ISSUE TITLE
BUG: Documentation Error in scipy.signal.lfilter

### ISSUE THREAD

**Issue by cdboschen** [scipy/scipy#15960]
### Describe your issue.

The description of 'filtfilt' in the doc string for scipy.signal.lfilter is incorrect in describing the use of filtfilt for creating linear phase filters. filtfilt creates "zero-phase" filters (which is a subset of linear phase filters).

It currently reads:

    See Also
    --------
    lfiltic : Construct initial conditions for `lfilter`.
    lfilter_zi : Compute initial state (steady state of step response) for
                 `lfilter`.
    filtfilt : A forward-backward filter, to obtain a filter with linear phase.
    savgol_filter : A Savitzky-Golay filter.
    sosfilt: Filter data using cascaded second-order sections.
    sosfiltfilt: A forward-backward filter using second-order sections.

And it should be: 

    See Also
    --------
    lfiltic : Construct initial conditions for `lfilter`.
    lfilter_zi : Compute initial state (steady state of step response) for
                 `lfilter`.
    filtfilt : A forward-backward filter, to obtain a filter with zero phase.
    savgol_filter : A Savitzky-Golay filter.
    sosfilt: Filter data using cascaded second-order sections.
    sosfiltfilt: A forward-backward filter using second-order sections.

### Reproducing Code Example

```python
help(sig.filtfilt)
```

### Error message

```shell
(None)
```

### SciPy/NumPy/Python version information

1.7.3 1.22.1 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment]
This was fixed by https://github.com/scipy/scipy/pull/16003
