### ISSUE TITLE
import scipy.optimize calling 

### ISSUE THREAD

**Issue by HirotsuguMINOWA** [scipy/scipy#15966]
### Describe your issue.

Thank you very much your development of scipy.

If you know solution, please tell me.

The error occurred when just `import scipy.optimize` on pypy where installed scipy etc.

```bash
$ pypy3
Python 3.9.12 (05fbe3aa5b0845e6c37239768aa455451aa5faba, Mar 29 2022, 08:15:34)
[PyPy 7.3.9 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import scipy.optimize
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  IndentationError: ('unexpected indent', ('<string>', 2, 1, '        class pybind11_static_property(property):\n', 2))
Aborted
root@48933591bab3:~#
```

The pypy was installed based on official pypy docker image.

Env:
- MacOS: catalina
- Docker: 4.7.0 (77141)
- PyPy 7.3.9, 7.3.8 (both)
- pybind11                      2.9.2

### Reproducing Code Example

```python
import scipy.optimize
```

### Error message

```shell
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  IndentationError: ('unexpected indent', ('<string>', 2, 1, '        class pybind11_static_property(property):\n', 2))
Aborted
```

### SciPy/NumPy/Python version information

PyPy 7.3.9, Scipy 1.8.0, Numpy 1.22.3

**Comment by mdhaber** [comment]
It looks like there may have been a bug in PyPy; see https://github.com/conda-forge/pypy-meta-feedstock/issues/25. Please upgrade PyPy, SciPy (to 1.9.3), and open a new issue with a title that identifies the problem, e.g. "BUG: `import scipy.optimize` fails on PyPy" . (That said, I'm not sure if we support PyPy right now, so I can't guarantee that it will be addressed.)
