### ISSUE TITLE
ENH: Generate histogram bins from distribution

### ISSUE THREAD

**Issue by KOLANICH** [scipy/scipy#15977]
### Is your feature request related to a problem? Please describe.

If we have fit a distribution to data, for visualization purposes we may want to plot a histogram. Making a histogram with uniform bins is not very rational if we want it to approximate PDF. So if we assumme that the hist is an approximation of the PDF of the dist, we can compute bins from it.

### Describe the solution you'd like.

1. #15976 is implemented
2. a method is added to `rv_frozen` to get the bins using the method described in #15976 . The method takes the count of bins, or `None`, in this case the count of bins is determined automatically.

### Describe alternatives you've considered.

No.

### Additional context (e.g. screenshots, GIFs)

https://github.com/KOLANICH-libs/StatsUtils.py/blob/master/StatsUtils/hist.py
https://github.com/KOLANICH-libs/StatsUtils.py/blob/master/StatsUtils/core.py

**Comment by rkern** [comment]
FWIW, I think this would be an overly-optimistic procedure that will paper over discrepancies between the fitted distribution and the data. Personally, I'd want a more pessimistic visualization to highlight discrepancies between the data and the distribution. I think the standard tools in, say, `seaborn` (KDE plots, rug plots, and yes, uniformly-binned histograms) are quite reasonable and standard approaches for this task. I've never seen this procedure documented elsewhere, so if you have a reference that explains the merits of this approach, it would help.

I'm not sure this needs special support inside of the `rv_continuous` framework. This seems like it's better implemented closer to the visualization tools (e.g. `seaborn`) from the primitives already provided by `scipy`.
