### ISSUE TITLE
BUG: signal.lfilter sometimes works with complex coefficients and sometimes not

### ISSUE THREAD

**Issue by hadamard-zweistein** [scipy/scipy#15980]
### Describe your issue.

lfilter sometimes works with complex coefficients and sometimes not. In one example (a version of Goertzel alogrithm), the lfilter from signal computed with complex numbers.

In a further modified version, lfilter ignored the imaginary parts of the complex coefficients.

### Reproducing Code Example

```python
from scipy.signal import lfilter
import numpy as np

x_n = np.array([1, 4, 9, 16, 25])

# working example
# goertzel

k = 1
N = len(xn) 

b = np.array([1, -np.exp(-2j*pi*k/N)])
b = b * np.exp(2j*pi*k/N)
a = np.array([1, -2*np.cos(2*pi*k/N), 1])

y = lfilter(b, a, xn)
y

# not working example
# sgdft


k = 1
N = len(xn) 

b = np.zeros(N)
b[0] = 1
b[1] = -np.exp(2j*pi*k/N)
b[-2] = np.exp(2j*pi*k/N)
b[-1] = -1
b = b * np.exp(2j*pi*k/N)
a = np.array([1, -2*np.cos(2*pi*k/N), 1])

y = lfilter(b, a, xn)
y
```

### Error message

```shell
<ipython-input-134-8ef5bc7772dc>:10: ComplexWarning: Casting complex values to real discards the imaginary part
  b[1] = -np.exp(2j*pi*k/N)
<ipython-input-134-8ef5bc7772dc>:11: ComplexWarning: Casting complex values to real discards the imaginary part
  b[-2] = np.exp(2j*pi*k/N)
```

### SciPy/NumPy/Python version information

1.5.0 1.18.5 sys.version_info(major=3, minor=8, micro=3, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @hadamard-zweistein, thank you for reporting but this is not an issue with SciPy but with the code you have before even calling `lfilter`.

Just run this part of your example and you will get your error
```
b = np.zeros(N)
b[0] = 1
b[1] = -np.exp(2j*pi*k/N)
```

I will close this for now.

**Comment by hadamard-zweistein** [comment]
@tupui , perfect! Thank you
