### ISSUE TITLE
ENH, DOC: Add section explaining why and when to use a custom BLAS to build SciPy

### ISSUE THREAD

**Issue by melissawm** [scipy/scipy#15985]
### Is your feature request related to a problem? Please describe.

See https://github.com/scipy/scipy/pull/15947#discussion_r849163545

We have an FAQ item describing how to use a custom BLAS to build on Linux, but no explanation about why this is needed.

### Describe the solution you'd like.

Add an FAQ item or page on the contributing guide to explain this.

**Comment by rgommers** [comment]
I added more BLAS/LAPACK docs in gh-18429. I noted that that'll close this issue. I don't think it is useful or maintainable to have a guide on why various BLAS libraries may be chosen. If the user doesn't already know, it's not relevant. If they do know, they know. There can be multiple reasons, but typically performance.
