### ISSUE TITLE
CI: `np.matrix` deprecation warning

### ISSUE THREAD

**Issue by tupui** [scipy/scipy#15987]
`np.kron` is now (appeared in the NumPy pre-released job) raising a deprecation warning because we are using a matrix in `::TestSparseFunctions::test_scale_rows_and_cols`

(`np.array(*args, **kwargs).view(np.matrix)`). This is from `from scipy.sparse._sputils import matrix`.

```
/home/runner/.local/lib/python3.10/site-packages/numpy/matrixlib/defmatrix.py:116: in __new__
[1104](https://github.com/scipy/scipy/runs/5999820014?check_suite_focus=true#step:7:1104)
    warnings.warn('the matrix subclass is not the recommended way to '
[1105](https://github.com/scipy/scipy/runs/5999820014?check_suite_focus=true#step:7:1105)
E   PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
```

See for instance: https://github.com/scipy/scipy/runs/5999820014?check_suite_focus=true

**Comment by tupui** [comment]
@rossbar, I think changes are due to this PR https://github.com/numpy/numpy/pull/21262

**Comment by rossbar** [comment]
Yup that's the culprit - fortunately I think this can be fixed with a few relatively straightforward changes to the affected test. I will push up my suggestion as soon as the tests finish locally.
