### ISSUE TITLE
NotImplementedError: input type '<U1' not supported

### ISSUE THREAD

**Issue by vathsalashetty25** [scipy/scipy#16008]
Getting this error while running python3.9 runtests.py for scipy v1.5.4..anybody have anyidea on this failure?

scipy/signal/tests/test_signaltools.py:1765: in test_lfilter_bad_object
    lfilter([1.], [1., 1.], ['a', 'b', 'c'])
scipy/signal/signaltools.py:1907: in lfilter
    return sigtools._linear_filter(b, a, x, axis)
E   NotImplementedError: input type '<U1' not supported
        a          = array([1., 1.])
        axis       = -1
        b          = [1.0]
        x          = ['a', 'b', 'c']
        zi         = None
==========================================

**Comment by tupui** [comment]
Hi @vathsalashetty25, thank you for reporting. This test has been updated in main. I will close this for now.
