### ISSUE TITLE
BUG: Confusing documentation in `ttest_ind_from_stats`

### ISSUE THREAD

**Issue by alonme** [scipy/scipy#16007]
### Is your feature request related to a problem? Please describe.

The documentation in `ttest_ind_from_stats` is confusing.

it states that the variances of  
```
a = np.array([1, 3, 4, 6, 11, 13, 15, 19, 22, 24, 25, 26, 26])
b = np.array([2, 4, 6, 9, 11, 13, 14, 15, 18, 19, 21])
```
are `87.5` and `39.0`, while they are not.

### Describe the solution you'd like.

Fix the table in the start of the examples to have the right values

### Additional context (e.g. screenshots, GIFs)

![image](https://user-images.githubusercontent.com/25847554/163881122-4463643d-e40c-44ad-871a-5b183a2e7f3c.png)
![image](https://user-images.githubusercontent.com/25847554/163881159-8c8b682c-527e-44bf-96b6-95e412dd5d53.png)

**Comment by alonme** [comment]
OK, its just that ddof=1 should be used.
closing

**Comment by mdhaber** [comment]
We should document that, though, so I've reopened this.

**Comment by alonme** [comment]
Hi @mdhaber, 
There is still a related mistake in this part of the doc
![image](https://user-images.githubusercontent.com/25847554/164959646-812346b3-e88b-4080-96e6-5de35e4c5d41.png)


![image](https://user-images.githubusercontent.com/25847554/164959742-c0c1e007-a8bb-482c-a3e4-6c5e253cbcb9.png)

**Comment by mdhaber** [comment]
I see. I assumed the author would have calculated those with `ddof`. @fAndreuzzi if you like to change that column to the corrected sample standard deviation (rather than uncorrected variance), I can review.

**Comment by mdhaber** [comment]
Thanks @alonme @fAndreuzzi!

**Comment by fAndreuzzi** [comment]
Sorry @mdhaber, I missed that! I'm opening a new PR
