### ISSUE TITLE
BUG: typo in documentation for scipy.optimize.basinhopping

### ISSUE THREAD

**Issue by cam92473** [scipy/scipy#16011]
### Describe your issue.

There's a notational mistake in the examples section on the page https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.basinhopping.html#scipy.optimize.basinhopping. In the code blocks, it should say `f(x)`, not `f(x0)`, since `x` is the value of the parameter that minimizes `f`, whereas `x0` is the initial guess.

### Reproducing Code Example

```python
n/a
```

### Error message

```shell
n/a
```

### SciPy/NumPy/Python version information

n/a

**Comment by tupui** [comment]
Hi @cam92473, thank you for reporting. You mean these correct `global minimum: x = %.4f, f(x0) = %.4f`?

I agree. Would you like to do a PR to fix it?

**Comment by cam92473** [comment]
Yes, I've gone ahead and done that.
