### ISSUE TITLE
jc should be (n-1)/2

### ISSUE THREAD

**Issue by nstarman** [scipy/scipy#16027]
The docs say (n+1)/2 but assume that n runs from from 0 to n-1

https://github.com/scipy/scipy/blob/ced4d67ec8bfd7e25e5087c7dedc53bd8bd632d0/scipy/fft/_fftlog.py#L74

so it should be calculated as jc = (n-1)/2. This is also what the code does:

https://github.com/scipy/scipy/blob/ced4d67ec8bfd7e25e5087c7dedc53bd8bd632d0/scipy/fft/_fftlog.py#L121

**Comment by WillTirone** [comment]
I'll take this one, I'm at PyCon at the moment so I'll work on this over the next few days and at the sprints Mon. / Tues.; still a relative beginner so I'll give it my best shot

**Comment by tylerjereddy** [comment]
Let me know if you get stuck
