### ISSUE TITLE
Color nodes in dendrogram of HCA based on list of children

### ISSUE THREAD

**Issue by saskra** [scipy/scipy#16048]
I would be pleased about an extension of the possibilities of the dendrogram function - or about a hint, if my desired behavior should already be possible now.

Namely, I have performed a hierarchical cluster analysis and had the dendrogram output for this purpose, as shown in this example: https://scikit-learn.org/stable/auto_examples/cluster/plot_agglomerative_dendrogram.html.

I then selected certain nodes with their children and would like to color them accordingly in the dendrogram. Unfortunately, I can only find in the documentation the possibility to set a threshold so that all nodes with a larger distance to the root are displayed in a common color and all with a smaller distance are displayed in different colors, see https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.dendrogram.html . But my selected nodes are in different distances/hierarchy levels and not all leaves belong to selected nodes.

Does anyone know a way to achieve the desired behavior? (I know I was able to do this in Matlab years ago).

To give you a better idea, here is a simple example I created manually: https://i.stack.imgur.com/xZCYb.png

**Comment by tupui** [comment]
Hi @saskra, thank you for reporting. Could you not use the parameter `link_color_func`?

**Comment by saskra** [comment]
Thanks for the answer, @tupui! I haven't figured out yet how to use link_color_func for my purpose, but will take a closer look.

**Comment by saskra** [comment]
Thanks, I've actually managed to do it with this in the meantime.
