### ISSUE TITLE
BUG: iircomb peaking behavior doesn't match documentation

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#16052]
### Describe your issue.

The second example in the documentation for `signal.iircomb` says:

    f0 = 250.0  # Frequency to be retained (Hz)

But this is not the frequency to be retained, it's the frequency that is cut:

![](https://docs.scipy.org/doc/scipy/_images/scipy-signal-iircomb-1_01_00.png)

Likewise the parameter `w0` says:

> Frequency to attenuate (notching) or boost (peaking).

which is incorrect.  With `ftype='peak'`, 250 Hz is not boosted.

Comb filters _do_ support peaking and notching at both types of frequencies, by varying the sign of the last coefficients, and I would like to support all four configurations in SciPy:

    b = [0.0498, 0, 0, 0, -0.0498], a = [1, 0, 0, 0, 0.9]

![peaking between frequencies](https://user-images.githubusercontent.com/58611/165438204-f0b8edc0-c07b-4a22-b63a-2dc3c905517c.png)

     b = [0.0498, 0, 0, 0, 0.0498], a = [1, 0, 0, 0, -0.9]

![peaking at frequencies](https://user-images.githubusercontent.com/58611/165438290-6ce8805d-d94d-49ae-a2fc-bce67eb6710b.png)

    b = [0.95, 0, 0, 0, -0.95], a = [1, 0, 0, 0, -0.9]

![notching at frequencies](https://user-images.githubusercontent.com/58611/165438430-e7282594-2d23-4104-87f8-1111cd909327.png)

    b = [0.95, 0, 0, 0, 0.95], a = [1, 0, 0, 0, 0.9]

![notching between frequencies](https://user-images.githubusercontent.com/58611/165438476-4b914757-bf2e-4593-9b89-eab6317c2bff.png)

However, I'm not sure what the best interface is.  I'm not sure if this counts as a bug in the documentation or a bug in the code.

- If we consider it a bug in the code, then we could change the functionality to match the documentation, so that peaking and notching both occur on the frequency specified (which seems more natural to me), and then add another parameter (`shift`?  `invert`?) that shifts to the "between frequencies" when `True`.
- If we consider the documentation to be the bug, then the behavior is kind of strange, but I guess we'd add some other parameter to get the other two behaviors (notching between specified frequency, peaking at specified frequency).
- Or there could be four `ftype` options for the two notching and two peaking variants?  With `peak` and `notch` kept undocumented for backwards compatibility?  But I don't know what to call the other four options.  `peak_at` and `peak_between` or something?

### Reproducing Code Example

```python
fs = 1000.0  # Sample frequency (Hz)
f0 = 250.0  # Frequency to be retained (Hz)
Q = 30.0  # Quality factor

# Design peaking filter
b, a = signal.iircomb(f0, Q, ftype='peak', fs=fs)

# Frequency response
freq, h = signal.freqz(b, a, fs=fs)
response = abs(h)

# To avoid divide by zero when graphing
response[response == 0] = 1e-20

# Plot
fig, ax = plt.subplots(2, 1, figsize=(8, 6))
ax[0].plot(freq, 20*np.log10(np.maximum(abs(h), 1e-5)), color='blue')
ax[0].set_title("Frequency Response")
ax[0].set_ylabel("Amplitude (dB)", color='blue')
ax[0].set_xlim([0, 500])
ax[0].set_ylim([-80, 10])
ax[0].grid()
ax[1].plot(freq, np.unwrap(np.angle(h))*180/np.pi, color='green')
ax[1].set_ylabel("Angle (degrees)", color='green')
ax[1].set_xlabel("Frequency (Hz)")
ax[1].set_xlim([0, 500])
ax[1].set_yticks([-90, -60, -30, 0, 30, 60, 90])
ax[1].set_ylim([-90, 90])
ax[1].grid()
plt.show()
```

### Error message

```shell
None
```

### SciPy/NumPy/Python version information

1.7.3 1.20.3 sys.version_info(major=3, minor=7, micro=13, releaselevel='final', serial=0)

**Comment by endolith** [comment]
@skresearcher @agamemnonc any opinions on this?  It looks from https://github.com/scipy/scipy/pull/12476#issuecomment-655709388 that maybe this was done for compatibility with Matlab? I agree with @larsoner that it would be more natural for the peak and notch options to be complementary, though.

**Comment by skresearcher** [comment]
As you figured out, the current interface was designed to maintain compatibility with MATLAB. The `'notch'` and `'peak'` arguments changed the shape of the comb filter, but functionally it worked as a notching comb filter in both cases (even in MATLAB). I think I prefer the first option of fixing the bug in the code for the reasons you've outlined above, and we can add a new input argument (`shift` makes more sense) to deal with the other two cases.

**Comment by endolith** [comment]
The Orfanidis book calls the parameter `s`, though this is not very descriptive:

```matlab
% combeq.m - periodic comb/notch EQ filter design
%
% [a, b, c, beta] = combeq(G0, G, GB, D, Dw, s)
%
% s = 1, −1 for peaks at 2kπ/D, or, (2k + 1)π/D
% G0, G, GB = reference, boost/cut, and bandwidth gains
% D = period, Dw = width in [rads/sample]
% note Dw < π/D, beta = design parameter β
%
% for plain COMB use: G0 = 0, G = 1, GB = 1/√2
% for plain NOTCH use: G0 = 1, G = 0, GB = 1/√2
```

**Comment by larsoner** [comment]
>> I would like to support all four configurations in SciPy

> OK, that would then break backwards compatibility and Matlab compatibility, though? :/

Agreed that breaking backward compat with ourselves and MATLAB is not great. It seems like the least painful way forward would be to add two more mode names corresponding to the other two modes.

**Comment by endolith** [comment]
>  add two more mode names corresponding to the other two modes.

Any suggestions? :)

Maybe since `peak` and `notch` behavior aren't consistent with each other, there could be 4 new mode names, with two as backwards-compatibility synonyms?

**Comment by larsoner** [comment]
> If we consider the documentation to be the bug, then the behavior is kind of strange, but I guess we'd add some other parameter to get the other two behaviors (notching between specified frequency, peaking at specified frequency).

Okay thinking about this option more, how about following `firwin` a bit and add `pass_zero=False`:
```
iircomb(w0, Q, ftype='notch', fs=2.0, pass_zero=False):
```
Then it's clear(er) that for either `ftype`, by default, zero will be notched -- and hence `f0` and its multiples will be notched, too. If you pass `pass_zero=True`, `(f0 * n)/ 2.` will be notched instead.

It's not as pretty as maybe we'd like, but it's at least internally somewhat consistent (with `firwin`) and avoids any deprecation...

**Comment by larsoner** [comment]
> I guess this could be a separate parameter? Or a different ftype maybe?

At least for the FIR case it's a bit weird to get the behavior from a function named `iircomb`, I'd be tempted to make a `fircomb`. But if we can get all these behaviors from a single function I can live with it being part of `iircomb` even if the impulse response is finite.

Can you think of a clean API from scratch that would work for the Wikipedia cases? Maybe we should start from there and then decide if we can make it fit into `iircomb` somehow, or if we should make a separate function / separate functions.
