### ISSUE TITLE
ENH: Make sparse matrix element accessible via subscription operator / `__getitem__` and `__setitem__`

### ISSUE THREAD

**Issue by stevenleeS0ht** [scipy/scipy#16059]
### Is your feature request related to a problem? Please describe.

Currently, all type of sparse matrix doesn't support subscription

```python
c_matrix = scipy.sparse.coo_matrix([[True, False], [False, True]],dtype=bool)
c_matrix[1,1]
TypeError: 'coo_matrix' object is not subscriptable
```

### Describe the solution you'd like.

Add `__getitem__` and `__setitem__` method for each sparse matrix class. And can retrieve single element directly. Like what `numpy.matrix` do.

**Comment by stevenleeS0ht** [comment]
For different type of sparse matrix, due their data structure is different, different algorithm should be implemented for optimization.

**Comment by fAndreuzzi** [comment]
Do SciPy maintainers plan to fix this eventually? If yes, I'd like to help!

**Comment by perimosocordiae** [comment]
This is a bit of a tricky question. While it's nice to be able to access a particular element [i, j] from your matrix, depending on the format this operation has a wide range of (in)efficiencies. For example, DOK matrix is a simple dict lookup, whereas in the general case, a COO matrix would require a full linear scan of the nonzero entries.

So while it's certainly possible to implement overloads for these operations on all formats, we want to discourage users from using the wrong format for the job and inadvertently hitting performance walls.
