### ISSUE TITLE
Bug: Meson build with dev.py fails to detect SciPy with debian python

### ISSUE THREAD

**Issue by AnirudhDagar** [scipy/scipy#16054]
While trying to build SciPy with meson on a 32bit machine for [#15814](https://github.com/scipy/scipy/issues/15814)  (using docker image `ubuntu:i386:bionic`; though this is not an architecture specific bug, I think)

After installing python3.8  and other required deps (through `apt` in ubuntu), and then python deps with pip3 (installed through [get-pip.py](https://bootstrap.pypa.io/get-pip.py)).

On running `python3.8 dev.py -j 2 --build-only` , build goes through fine; even the installation goes through fine.
```
Meson build setup OK
Build OK
Installing, see meson-install.log...
Installation OK
```

But later the script fails when [`get_project_info`](https://github.com/scipy/scipy/blob/653fd090fe18e28254986cd4c446c47b7051ef57/dev.py#L385) is called in dev.py script to import scipy, with the error message attached below.

```bash
Trying to find scipy from development installed path at: /__w/scipy/scipy/build-install/lib/python3.8/site-packages
Traceback (most recent call last):
  File "dev.py", line 393, in get_project_info
    test, version, mod_path = runtests.import_module()
  File "/__w/scipy/scipy/runtests.py", line 356, in import_module
    __import__(PROJECT_MODULE)
ModuleNotFoundError: No module named 'scipy'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "dev.py", line 635, in <module>
    main(argv=sys.argv[1:])
  File "dev.py", line 282, in main
    test, version, mod_path = get_project_info()
  File "dev.py", line 403, in get_project_info
    test, version, mod_path = runtests.import_module()
  File "/__w/scipy/scipy/runtests.py", line 356, in import_module
    __import__(PROJECT_MODULE)
ModuleNotFoundError: No module named 'scipy'
Error: Process completed with exit code 1.
```

The problem is that in dev.py, [`get_site_packages`](https://github.com/scipy/scipy/blob/653fd090fe18e28254986cd4c446c47b7051ef57/dev.py#L556) method returns `'/scipy/build-install/lib/python3.8/site-packages'` but actually meson installs scipy to `'/scipy/build-install/lib/python3/dist-packages'`

Feel free to check logs about the error and for reproducibility [here](https://github.com/AnirudhDagar/scipy/runs/6197379647?check_suite_focus=true).

### Additional Information
When I run ` python3.8 -c "import site; print(site.getsitepackages())"` I get the following:
```
['/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.8/dist-packages']
```

I guess this issue is also discussed in mesonbuild/meson#8739, explaining problems with debian python and dist-packages vs site-packages or python3.x vs python3, depending on what python (system, venv, compiled) is being used.

Edit 1: Adding more info for someone who reads this later. Great blog on [Python, Debian, and the install locations](https://ffy00.github.io/blog/02-python-debian-and-the-install-locations/) and meson patching similar problem in https://github.com/mesonbuild/meson/pull/9288 

#### SciPy/NumPy/Python version information
`1.9.0.dev0+1925.653fd09 1.19.0 sys.version_info(major=3, minor=8, micro=0, releaselevel='final', serial=0)`

### Pitch
I can suggest a hacky fix to tweak `dev.py` specifically in [`get_project_info`](https://github.com/scipy/scipy/blob/1a945cae6ddc9186318cf34cfe1756cdd86eea34/dev.py#L385) or more specifically `PATH_INSTALLED` variable to also fall back to check for other possible installation paths that meson used in debian like here, for example utilizing path from `['/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.8/dist-packages']` and stripping them to
`['/lib/python3.8/dist-packages', '/lib/python3/dist-packages', '/lib/python3.8/dist-packages']` and then joining it with the prefix.

There is probably a better way to do this. I can send a PR after a discussion if this is indeed a valid bug.

cc @rgommers @Smit-create

**Comment by rgommers** [comment]
Thanks for the detailed bug report @AnirudhDagar. You diagnosed it correctly, it's indeed due to that mess Debian made. It looks like it boils down to:

```python
>>> import sys
>>> from sysconfig import get_path
>>> from pathlib import Path
>>> plat_path = Path(get_path("platlib"))
```
where `plat_path` gives `python3.8/site-packages` while things get installed to `python3/dist-packages`. 

I don't think there's a correct solution, so a hacky one to extend `get_site_packages` and see if the constructed path exists and trying `python3` and `dist-packages` fallbacks if not seems like the right thing to do here. A PR would be great.

**Comment by AnirudhDagar** [comment]
Thanks for the quick reply and confirmation, sending a PR in a bit.

**Comment by Smit-create** [comment]
Does this work fine with `runtests.py`? That has a bit different hack:
https://github.com/scipy/scipy/blob/820fe86bf3ad8ba1c5647632b131659ed7bd447e/runtests.py#L431-L433

**Comment by AnirudhDagar** [comment]
> Does this work fine with runtests.py?

Do you mean if Debian python used with runtests.py (distutils based build) works without failing? Yes, it does. See `Linux_Python_38_32bit_full` job example.

IIUC, I don't think there is any hack here. This works in runtests.py because it defines `dst_dir` where the build needs to install scipy eg: `/scipy/build/testenv/lib/python3.8/site-packages` and then installs it to the same path.

Meson uses the path detected from global site-packages (which in case of debian is `..../python3/dist-packages/...`) of the selected python interpreter to install scipy. Then we try to recreate that same path for exporting `PYTHONPATH` in `dev.py` using `get_path('platlib')`. But for Debian python with the current logic it mismatches the actual installed path to the one we get through `platlib`.

Please correct me/explain a bit more if I don't understand your comment fully. Thanks!
