### ISSUE TITLE
BUG: Missing Constant in Documentation

### ISSUE THREAD

**Issue by akern40** [scipy/scipy#16068]
### Describe your issue.

The table in the documentation that [lists constants](http://scipy.github.io/devdocs/reference/constants.html) is missing the characteristic impedance of a vacuum. This is because the constant is not listed directly in the CODATA 2018 table (this occured in [#10920](https://github.com/scipy/scipy/pull/10920)); however, it has been maintained in scipy since January 2020 (see [#11343](https://github.com/scipy/scipy/pull/11343)). Because the code that handles the documentation of constants [defines obsolete values](https://github.com/scipy/scipy/blob/40f4455eef9bb64e18eb9a6f557fa6fe4a7dd3ca/scipy/constants/_codata.py#L1541) as those not in the CODATA 2018 table, the constant isn't included in the documentation. I'm a little out of my depth of expertise here, but I'm not sure that the characteristic impedance of a vacuum should be counted as an obsolete constant. I'm not really sure why it's not included in the CODATA 2018 table, despite the fact that it is still listed [on NIST's website](https://physics.nist.gov/cgi-bin/cuu/Value?z0) as a fundamental constant. Is it fair to say that this should not be included as an obsolete constant? I'd love to hear from anybody who knows more about this subject and its nuances, thanks!

### Reproducing Code Example

```python
>>> from scipy import constants
>>> constants.physical_constants['characteristic impedance of vacuum']
(376.73031366686166, 'ohm', 5.61366546036269e-08)
>>> 'characteristic impedance of vacuum' in constants._obsolete_constants
True
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

1.7.3 1.21.5 sys.version_info(major=3, minor=7, micro=11, releaselevel='final', serial=0)

**Comment by akern40** [comment]
Ok, I think I found the location where the actual text in the source comes from (https://physics.nist.gov/cuu/Constants/Table/allascii.txt) which does indeed list characteristic impedance of a vacuum. A quick diff (https://www.diffchecker.com/1hgzMrhi) shows that characteristic impedance of a vacuum is the only constant that was dropped when the table was inserted into the source code. This makes me think the correct move is to add it back in to the table, which will fix the obsolete issue and put it back into the documentation. Is the redefinition that currently sets the value still necessary?

**Comment by jakobjakobson13** [comment]
Apparently, codata data table was updated sometime between the Sep 26, 2019 ( https://web.archive.org/web/20190926042548/https://physics.nist.gov/cuu/Constants/Table/allascii.txt) and Sep 06, 2020 ( https://web.archive.org/web/20200906102720/https://physics.nist.gov/cuu/Constants/Table/allascii.txt ). So, adding the one line should be sufficient to introduce the constant.

**Comment by akern40** [comment]
Given that the redefinition using the `exact_values` approach was added as a stopgap, should that now be removed as well?

**Comment by akern40** [comment]
Thanks for making the PR for this!
