### ISSUE TITLE
BUG: f-stat distribution output doesn't make sense, possibly incorrect?

### ISSUE THREAD

**Issue by dyc3** [scipy/scipy#16064]
### Describe your issue.

The output of `scipy.stats.f.ppf()` doesn't make any sense to me. Maybe I'm missing something obvious.

Comparing the output of this function to f distribution tables found online, the results don't match.

For example: looking at [this table](http://www.socr.ucla.edu/Applets.dir/F_Table.html), `f` for `alpha=0.1`, `df1=1`, `df2=1` should be `39.86346`, but `f.ppf()` gives `0.025085630936916573`.

### Reproducing Code Example

```python
import scipy.stats
print(scipy.stats.f.ppf(0.1, 1, 1))
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

1.6.3 1.21.2 sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
I think you want `isf`. 
```python3
import scipy.stats
print(scipy.stats.f.isf(0.1, 1, 1))  # 39.86345818906144
```
