### ISSUE TITLE
BUG: refguide check fails with `numpydoc==1.3`

### ISSUE THREAD

**Issue by AnirudhDagar** [scipy/scipy#16074]
## Problem
numpydoc released [v1.3](https://github.com/numpy/numpydoc/releases/tag/v1.3.0) a few hrs ago.

With this release, as seen in numpy/numpydoc#381 they unpinned the upper version of Jinja2 and now a new RuntimeError is raised asking the numpydoc users to be responsible for pinning Jinja2 in case of unmaintained sphinx versions.

This has now lead to broken Refguide Checks in `refguide_asv_check` job.

```bash
Traceback (most recent call last):
  File "/home/vsts/work/1/s/tools/refguide_check.py", line 46, in <module>
    from numpydoc.docscrape_sphinx import get_doc_object
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/numpydoc/__init__.py", line 30, in <module>
    _verify_sphinx_jinja()
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/numpydoc/__init__.py", line 23, in _verify_sphinx_jinja
    raise VersionRequirementError(
sphinx.errors.VersionRequirementError: 

Sphinx<4.0.2 is incompatible with Jinja2>=3.1.
If you wish to continue using sphinx<4.0.2 you need to pin Jinja2<3.1.
```

 See [example1](https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=17928&view=logs&j=ede89041-5e8e-5201-ce5c-f68c2cbf02dd&t=bf6d2fae-c4b4-5aaf-e29f-d3092465da33) from #16069 and [example2](https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=17927&view=logs&jobId=ede89041-5e8e-5201-ce5c-f68c2cbf02dd&j=ede89041-5e8e-5201-ce5c-f68c2cbf02dd&t=bf6d2fae-c4b4-5aaf-e29f-d3092465da33) from #15607.

## Solution
We should pin `Jinja2<3.1` again.

cc @tupui @rgommers

**Comment by tupui** [comment]
Or just unpin Sphinx no?

**Comment by rossbar** [comment]
Yeah, the at least one of the linked failing azure jobs has the following under the `Install Documentation Dependencies` step: `pip install matplotlib sphinx==3.1 numpydoc`.

If there is a particular reason why sphinx 3.1 is required, then yes you'll have to pin Jinja2<3.1. If however the sphinx==3.1 is not required, then unpinning would also solve the problem.

**Comment by AnirudhDagar** [comment]
sphinx is pinned to 3.1, see discussion after https://github.com/scipy/scipy/pull/13389#issuecomment-762365964 where we tried to completely remove the pin. @rgommers might know the exact reason, logs are gone by now.
