### ISSUE TITLE
CI, MAINT: minor refguide failure with stats.describe

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#16081]
Showing up in unrelated PRs: gh-16078 and gh-16073

Looks like a bit of floating point shenanigans we should be able to massage over one way or another?

```
Checking tutorial files at doc/source/tutorial/*.rst:

===========
scipy.stats
===========

scipy.stats.describe
--------------------

File "build/testenv/lib/python3.9/site-packages/scipy/stats/_stats_py.py", line 1328, in describe
Failed example:
    stats.describe(a)
Expected:
    DescribeResult(nobs=10, minmax=(0, 9), mean=4.5,
                   variance=9.166666666666666, skewness=0.0,
                   kurtosis=-1.2242424242424244)
Got:
    DescribeResult(nobs=10, minmax=(0, 9), mean=4.5, variance=9.166666666666668, skewness=0.0, kurtosis=-1.2242424242424244)
```

**Comment by ev-br** [comment]
As a wild guess, refguide-check does not understand `minmax=(0, 9)` as it probably expects only floating-point numbers in https://github.com/scipy/scipy/blob/main/tools/refguide_check.py#L499

So if there's a regex wiz to express "or a tuple of values" in https://github.com/scipy/scipy/blob/main/tools/refguide_check.py#L507 ?

**Comment by ev-br** [comment]
Nope, no need for regex wiz; let's see if gh-16082 agrees
