### ISSUE TITLE
BUG: Locally Optimal Block Preconditioned Conjugate Gradient (LOBPCG) gets worse with perfect preconditioner

### ISSUE THREAD

**Issue by vlad17** [scipy/scipy#16089]
### Describe your issue.

Adding a perfect preconditoiner to the LOBPCG routine results in worse iteration.

Attached is a detailed jupyter notebook which recreates and visualizes this issue. For matrices with both linear and geometric spectrum separation, we notice severely degraded performance for finding the largest eigenvalues, using an ideal preconditioner derived from a cholesky decomposition.

![linear spectrum](https://user-images.githubusercontent.com/5834964/166160502-4bdf8032-2839-4892-83cf-bc78d4411876.png)

![geometric spectrum](https://user-images.githubusercontent.com/5834964/166160509-b0ab955d-f2f7-4780-9708-2b31d438dcbe.png)

[lobpcg-ex.zip](https://github.com/scipy/scipy/files/8599541/lobpcg-ex.zip)

The literature on this shows:
  - Preconditioners should improve convergence ([Preconditioned Eigensolver LOBPCG in hypre and PETSc, Lashuk, et al. 2007](https://cims.nyu.edu/dd16/proceedings/knyazev_contrib.pdf)).
  - Preconditioners may need to be symmetric, linear, and PSD (I verify this in the notebook) ([Block Locally Optimal Preconditioned Eigenvalue Xolvers (BLOPEX) in hypre and PETSc, Knyazev, et al. 2007](https://arxiv.org/abs/0705.2626))
  - More recent results show LOBPCG should even be tolerant to asymmetry of preconditioner ([Nonsymmetric multigrid preconditioning for conjugate gradient methods, Bouwmeester et al 2013](https://arxiv.org/abs/1212.6680))

I'm just spitballing here, but for computing largest eigenvalues I can see how preconditioning with `A^{-1}` might hurt convergence (as the action of `A^{-1}` should highlight the smallest eigenvectors in the residual for PSD matrices `A`), though maybe @lobpcg  might know if there's a clear bug in the scipy code that might be causing this issue.

### Reproducing Code Example

```python
n = 1000
k = 10
m = 300
kappa = 1000
np.random.seed(1234)
X = np.random.randn(n, k).astype(np.float32)
A = np.diag(np.linspace(1, kappa, n)).astype(np.float32)
f = scipy.linalg.cho_factor(A)
Linv = scipy.linalg.cho_solve(f, np.eye(A.shape[0]))
Linv = (Linv + Linv.T) / 2
for M in [None, Linv]:
    _, _, hist = scipy.sparse.linalg.lobpcg(A, X, maxiter=m, M=M, retResidualNormsHistory=True)
    print('precond? ', M is not None, 'best residual', min(np.array(hist).max(axis=1)))
```

### Error message

```shell
# prints
# precond?  False best residual 2.5630512
# precond?  True best residual 9.13194302949972
```

### SciPy/NumPy/Python version information

1.8.0 1.21.5 sys.version_info(major=3, minor=9, micro=10, releaselevel='final', serial=0)

**Comment by lobpcg** [comment]
The goal of the preconditioner M is to improve the condition number of the matrix M(A - lamba I) where lamba is the seeking eigenvalue and the null space is ignored. 
The ideal preconditioner is the pseudo inverse of (A - lamba I). 

If A>0 and lambda is the smallest, M=inv(A) is a good preconditioner  compared to the trivial M=I, since lambda is close to zero, informality speaking. 

If A>0 and lambda is the largest, as in the example, M=inv(A) is a poor preconditioner  compared to the trivial M=I, as the example  demonstrates. 

It surely is not a bug of the code.

**Comment by vlad17** [comment]
That makes sense! I think I was needlessly carrying over my notion of a preconditioner for unshifted PCG.

In that case, for `k > 1`, we'd presumably want more than one preconditioner, `M(lambda)`, to apply to the corresponding residuals based on the intermediate Ritz eigenvalues, correct?

**Comment by lobpcg** [comment]
Within the block, lambdas may be close enough to ignore the fact that they are different, practically speaking.
