### ISSUE TITLE
BUG: `sparse.linalg` docstrings

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#16085]
### Describe your issue.

Reported by Tyler in https://github.com/scipy/scipy/pull/16082#issuecomment-1114052991: 

```
===================
scipy.sparse.linalg
===================

scipy.sparse.linalg.bicgstab
----------------------------

File "build/testenv/lib/python3.9/site-packages/scipy/sparse/linalg/_isolve/iterative.py", line 62, in bicgstab
Failed example:
    np.allclose(A.dot(x), b)
Expected:
    True
Got:
    False
```

The failure seems to be sporadic and/or platform dependent (cannot repro locally). 

A few things to check / fix:

- The web docs, https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.bicgstab.html, do not show a docstring example at all
- The source, https://github.com/scipy/scipy/blob/main/scipy/sparse/linalg/_isolve/iterative.py#L215, shows some non-standard manipulations with docstrings --- which seem to include some usage examples.
- These examples use random numbers *without seeding*. So that might be the cause of sporadic failures?
- The web docs do not have a `source` link.

**Comment by WarrenWeckesser** [comment]
The occasional failure should be fixed by https://github.com/scipy/scipy/pull/16276

**Comment by ev-br** [comment]
fixed by https://github.com/scipy/scipy/pull/16276, closing.

**Comment by WarrenWeckesser** [comment]
*Actually* closing now 😀 .
