### ISSUE TITLE
ENH: double call for `solve` in each iteration of `BroydenFirst`

### ISSUE THREAD

**Issue by Ar-Kareem** [scipy/scipy#16097]
https://github.com/scipy/scipy/blob/2b4b1f088ca8b76cff26c1cd56322486f8c23658/scipy/optimize/_nonlin.py#L889

In the above function, it seems that in the majority of iterations, `solve` (through `self.Gm.matvec(f)`) is being called twice per function call for no reason as I understand it.

Wouldn't the following save time on computation every iteration?

```python
    def solve(self, f, tol=0):
        r = self.Gm.matvec(f)
        if not np.isfinite(r).all():
            # singular; reset the Jacobian approximation
            self.setup(self.last_x, self.last_f, self.func)

            # CHANGE FROM HERE
            return self.Gm.matvec(f)

        return r
```

**Comment by tupui** [comment]
Hi @Ar-Kareem, thank you for reporting. Did you try out your proposal? Are the existing tests passing? How did you came to the conclusion that `solve` was called twice as needed?

Please provide a bit more information.

**Comment by Ar-Kareem** [comment]
Sorry for not providing more information,

I am not familiar with scipy. I'm currently working on a paper that deals with Broyden's method and was merely looking at the source code to compare with my own implementation when I noticed this.

I'm 100% sure if the double call is actually useless (maybe under the hood it's doing something), I'll make a pull-request and see if the tests are passing.
