### ISSUE TITLE
BUG: scipy.spatial.Delaunay in 3D creating intersecting tetrahedra?

### ISSUE THREAD

**Issue by ivncl** [scipy/scipy#16094]
### Describe your issue.

Hi all,

I'm trying to build a Delaunay 3D tetrahedral mesh of a regular grid (2x2x1, cell dimension 8), and I'm obtaining more tetras than expected: I would expect 6*4=24, while 28 are available through `len(dela.simplices)`. The issue seems also evident in figure, especially at the bottom where intersecting edges are present.

What am I missing? Any help appreciated.

### Reproducing Code Example

```python
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits import mplot3d
from scipy.spatial import Delaunay as delaa

pts=np.array([[ 0.,  0.,  0.],
       [ 0.,  0.,  8.],
       [ 0.,  8.,  0.],
       [ 0.,  8.,  8.],
       [ 0., 16.,  0.],
       [ 0., 16.,  8.],
       [ 8.,  0.,  0.],
       [ 8.,  0.,  8.],
       [ 8.,  8.,  0.],
       [ 8.,  8.,  8.],
       [ 8., 16.,  0.],
       [ 8., 16.,  8.],
       [16.,  0.,  0.],
       [16.,  0.,  8.],
       [16.,  8.,  0.],
       [16.,  8.,  8.],
       [16., 16.,  0.],
       [16., 16.,  8.]])
	   
dela=delaa(pts)

def plot_tri_simple(ax, dela):
    for tr in dela.simplices:
        pts = dela.points[tr, :]
        ax.plot3D(pts[[0,1],0], pts[[0,1],1], pts[[0,1],2], color='g', lw='0.1')
        ax.plot3D(pts[[0,2],0], pts[[0,2],1], pts[[0,2],2], color='g', lw='0.1')
        ax.plot3D(pts[[0,3],0], pts[[0,3],1], pts[[0,3],2], color='g', lw='0.1')
        ax.plot3D(pts[[1,2],0], pts[[1,2],1], pts[[1,2],2], color='g', lw='0.1')
        ax.plot3D(pts[[1,3],0], pts[[1,3],1], pts[[1,3],2], color='g', lw='0.1')
        ax.plot3D(pts[[2,3],0], pts[[2,3],1], pts[[2,3],2], color='g', lw='0.1')

    ax.scatter(dela.points[:,0], dela.points[:,1], dela.points[:,2], color='b')

fig = plt.figure()
ax = plt.axes(projection='3d')
plot_tri_simple(ax, dela)
```

### Error message

```shell
-
```

### SciPy/NumPy/Python version information

1.7.3 1.19.3 sys.version_info(major=3, minor=7, micro=9, releaselevel='final', serial=0)

**Comment by rkern** [comment]
When you have coplanar points, it is common to have degenerate simplices in the results, [as noted in the Qhull documentation](http://www.qhull.org/html/qh-optq.htm#Qt) (Qhull is the library underneath `Delaunay`). For this particular problem, you can either omit zero-volume simplices (`abs(np.linalg.det(pts[1:] - pts[0])) < some_eps`) or fiddle with the `qhull_options`. Try just `qhull_options='Qbb'` or `qhull_options='Qbb Qc Qz Q12 Q0'`, for instance.

**Comment by ivncl** [comment]
Perfect. Thank you very much, was sure to be missing something. Closing.
