### ISSUE TITLE
Division by zero in pow2Scaled_D

### ISSUE THREAD

**Issue by rguenth** [scipy/scipy#16102]
### Describe your issue.

https://bugzilla.suse.com/show_bug.cgi?id=1199150

When testing scipy on i586 the test_kolmogorov.py::TestSmirnovp::test_oneminusoneovern test fails with a division
by zero.  The above points at

'a' is x = {0, 0}, m is 8 and we run into

    /*
     *  y ^ maxExpt >= 2^{-960}
     *  =>  maxExpt = 960 / log2(y.x[0]) = 708 / log(y.x[0])
     *              = 665/((1-y.x[0] + y.x[0]^2/2 - ...)
     *              <= 665/(1-y.x[0])
     * Quick check to see if we might need to break up the exponentiation
     */
    if (m*(y.x[0]-1) / y.x[0] < -_MAX_EXPONENT * NPY_LOGE2) {
        /* Now do it carefully, calling log() */
        double lg2y = log(y.x[0]) / NPY_LOGE2;
        double lgAns = m * lg2y;
        if (lgAns <= -_MAX_EXPONENT) {
            maxExpt = (int)(nextPowerOf2(-_MAX_EXPONENT / lg2y + 1)/2);
        }
    }

but we compute

    y = frexpD(a, &yE);

and that results in {0, <optimized out>}, we bogously run into the above
and lg2y ends up as -Inf and it's all bullshit from here.

I also note that scipy seems to enable SSE2 even on i586 but fails to pass -mfpmath=sse to the compiler which
means we use some SSE2 but also mix it with x87 FP usage possibly causing unexpected precision differences
due to the 80bit intel FP format of double.

### Reproducing Code Example

```python
special/tests/test_kolmogorov.py
```

### Error message

```shell
[  559s] ../../special/tests/test_kolmogorov.py::TestSmirnovp::test_oneminusoneovern <- ../../../../../usr/lib/python3.9/site-packages/scipy/special/tests/test_kolmogorov.py Fatal Python error: Floating point exception
[  559s]
[  559s] Current thread 0xf7970700 (most recent call first):
[  559s]   File "/usr/lib/python3.9/site-packages/scipy/special/_testutils.py", line 213 in eval_func_at_params
```

### SciPy/NumPy/Python version information

1.8.0

**Comment by rgommers** [comment]
Thanks for the report @rguenth. This is indeed i586 rather than i686 - I didn't know that that was still supported anywhere. SSE2 is indeed a hard requirement. The problem seems solved upstream, so do you mind if we close this?

**Comment by rguenth** [comment]
If the division by zero is fixed then yes, it's fine to close.  Note "i586" refers to a 32bit build where the ABI specifies the use of
the x87 register stack for argument and return value passing, so if the intent is to use SSE in numpy then for 32bit builds
you should also pass -mfpmath=sse to the compiler, that way you avoid excess precision issues when using x87 math and
you also likely get a faster result (note the ABI is unchanged by this).

**Comment by rgommers** [comment]
The flags we get from `numpy.distutils` are `-msse2` and other `-m`, and if supported also `-march=native`. I think that's equivalent? All the flavors can be found in `numpy/distutils/ccompiler_opt.py`.

> If the division by zero is fixed then yes, it's fine to close

Thanks!
