### ISSUE TITLE
ENH: have scipy Wheel for pypy3.8-v7.3.9-win64

### ISSUE THREAD

**Issue by stonebig** [scipy/scipy#16103]
### Is your feature request related to a problem? Please describe.

I don't have a scipy wheel for PyPy, unless I use the cgohlke one, but that requires the gigantic numpy+mkl wheel

Having an official wheel from scipy build for OpenBlas would make things 210Mo smaller (couting on wheel size)
 

### Describe the solution you'd like.

official wheels from Scipy for PyPy 3.8 (and soon 3.9), on Windows

### Describe alternatives you've considered.

cgohlke wheels are getting way too big with the MKL

**Comment by tupui** [comment]
Hi @stonebig, thank you for reporting. We don't have plans at the moment to distribute again wheels for PyPy.

FYI, SciPy wheels are built on another repo and there is already an issue for that: https://github.com/MacPython/scipy-wheels/issues/87

I will close this one to keep a single discussion.
