### ISSUE TITLE
BUG: `io.mmread` fails to read skew-symmetric real matrix

### ISSUE THREAD

**Issue by fvanmaele** [scipy/scipy#16119]
### Describe your issue.

`scipy` fails to read a 512x512 skew-symmetric real matrix in MM format. The matrix was generated in MATLAB using [`mmwrite.m`](https://math.nist.gov/MatrixMarket/mmio/matlab/mmiomatlab.html). A symmetric version of the real matrix is read without problems.

`mminfo` for the skew-symmetric matrix:
```
mminfo("19-512.mtx")
(512, 512, 262144, 'array', 'real', 'skew-symmetric')
```
for the symmetric matrix:
```
mminfo("18-512.mtx")
(512, 512, 262144, 'array', 'real', 'symmetric')
```
Difference between both files:
```diff
-%%MatrixMarket matrix array real symmetric
+%%MatrixMarket matrix array real skew-symmetric
 512 512
  4
 -1
```
The respective matrices can be found here:
[`19-512.mtx`](https://gist.github.com/fvanmaele/d63774a329241a34a131f5f510951149)
[`18-512.mtx`](https://gist.github.com/fvanmaele/36f515a6d734e022f2228cbebe05e197)

### Reproducing Code Example

```python
mmread("19-512.mtx")
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fvanmaele/.local/lib/python3.8/site-packages/scipy/io/_mmio.py", line 76, in mmread
    return MMFile().read(source)
  File "/home/fvanmaele/.local/lib/python3.8/site-packages/scipy/io/_mmio.py", line 436, in read
    return self._parse_body(stream)
  File "/home/fvanmaele/.local/lib/python3.8/site-packages/scipy/io/_mmio.py", line 562, in _parse_body
    a[i, j] = 0
IndexError: index 512 is out of bounds for axis 0 with size 512
```

### SciPy/NumPy/Python version information

1.8.0 1.22.2 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment]
It looks like there is a bug in the Matlab code that generated the file `19-512.mtx`.  According to https://math.nist.gov/MatrixMarket/formats.html, https://networkrepository.com/mtx-matrix-market-format.html and https://people.sc.fsu.edu/~jburkardt/data/mm/mm.html, the diagonal elements are not to be included in the skew-symmetric format.  The file `19-512.mtx` has 131330 lines.  The first two are the header, so the remaining 131328 are data.  But for a 512x512 matrix, there should be `512*511/2` = 130816 entries below the diagonal.  If the diagonal is included, the number of elements on or below the diagonal is `512*513/2` = 131328, so it appears that the file `19-512.mtx` incorrectly includes the diagonal elements in the file.

**Comment by WarrenWeckesser** [comment]
Since the problem was apparently a bad file, I'm closing the issue.
