### ISSUE TITLE
BUG: callback defined both in options of scipy.optimize.minimize and in its signature

### ISSUE THREAD

**Issue by VolodyaCO** [scipy/scipy#16127]
### Describe your issue.

The [documentation of version 1.8.0](https://docs.scipy.org/doc/scipy-1.8.0/html-scipyorg/reference/optimize.minimize-lbfgsb.html#optimize-minimize-lbfgsb) says that `callback` is one possible option of the L-BFGS-B solver, but setting that option causes an error :

```zsh
_minimize_lbfgsb() got multiple values for keyword argument 'callback'
```

Indeed, the [documentation also states](https://docs.scipy.org/doc/scipy-1.8.0/html-scipyorg/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize) that `callback` is an argument.

### Reproducing Code Example

```python
>>> import numpy as np
>>> from scipy.optimize import minimize
>>> def f(x):
...   return x*x
... 
>>> minimize(f, np.array([10]), method="L-BFGS-B", options={"callback": lambda xk: print(xk)})
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vvargas-calderon/miniconda3/envs/zapata/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 681, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
TypeError: _minimize_lbfgsb() got multiple values for keyword argument 'callback'
```

### SciPy/NumPy/Python version information

1.8.0 1.21.6 sys.version_info(major=3, minor=8, micro=12, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @VolodyaCO, thank you for reporting.

The `options` which can be used for a given solver corresponds to the options which are in `options` for this solver.

E.g. for L-BFGS-B we have:

```python
scipy.optimize.minimize(fun, x0, args=(), method='L-BFGS-B', jac=None, bounds=None, tol=None, callback=None, options={'disp': None, 'maxcor': 10, 'ftol': 2.220446049250313e-09, 'gtol': 1e-05, 'eps': 1e-08, 'maxfun': 15000, 'maxiter': 15000, 'iprint': - 1, 'maxls': 20, 'finite_diff_rel_step': None})
```

Then from `minimize` you can use 
```python
options={'disp': None, 'maxcor': 10, 'ftol': 2.220446049250313e-09, 'gtol': 1e-05, 'eps': 1e-08, 'maxfun': 15000, 'maxiter': 15000, 'iprint': - 1, 'maxls': 20, 'finite_diff_rel_step': None}
```

Other parameters, like `callback`, are not in `options`. In your case you want:

```python
minimize(f, np.array([10]), method="L-BFGS-B", callback=lambda xk: print(xk))
```

To me it's then a documentation "issue". Do you have a suggestion to improve the wording?

**Comment by VolodyaCO** [comment]
@tupui thanks for your quick reply. I find it inconsistent that the signature of the documentation page does not have `callback` as an option, but the subsequent description of the options does include it. I think it should be removed:
<img width="754" alt="Screenshot 2022-05-06 at 8 45 52 AM" src="https://user-images.githubusercontent.com/31494271/167145478-0642b591-d08d-4a0c-999d-646910c29389.png">

**Comment by tupui** [comment]
Oh indeed I see 👍 Would you like to make a PR @VolodyaCO?

**Comment by tupui** [comment]
@andyfaff I think `Options` in the docstrings of `scipy/optimize/_lbfgsb_py.py:_minimize_lbfgsb` should only describes the `options`. I suppose this is general to other optimizers.

**Comment by VolodyaCO** [comment]
Yeah I can make the PR if you want me to... would that be in here (scipy/optimize/_lbfgsb_py.py:_minimize_lbfgsb)?

**Comment by tupui** [comment]
Thanks! Yes it should be. But please wait for a confirmation from @andyfaff.

**Comment by andyfaff** [comment]
Yes, I don't think it should be removed from the docstring in `_minimize_lbfgsb`.

**Comment by AtsushiSakai** [comment]
I found [`_minimize_cobyla`](http://scipy.github.io/devdocs/reference/optimize.minimize-cobyla.html#optimize-minimize-cobyla) has the same issue. I fixed both in[ this PR](https://github.com/scipy/scipy/pull/16354).
