### ISSUE TITLE
Magic comments to skip the CI

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#16124]
### Describe your issue.

It'd be helpful to have magic incantations to skip (parts of the) CI listed somewhere (in the devguide?). Probably best have them listed by the provider --- our current CI has GHA, Azure, CircleCI, and it's not immediately clear how to e.g. skip a battery of 1.5hr test runs for a doc change.

**Comment by tirthasheshpatel** [comment]
Documented here: https://scipy.github.io/devdocs/dev/contributor/continuous_integration.html#skipping

![image](https://user-images.githubusercontent.com/43181252/166921889-1137f930-8a6d-49a2-9396-25754bf4b4ac.png)

**Comment by ev-br** [comment]
Thanks Tirth, this settles it!

The only remaining enhancement request is then to spell out if these comments work if placed in the PR comment not the commit message?

**Comment by tirthasheshpatel** [comment]
> The only remaining enhancement request is then to spell out if these comments work if placed in the PR comment not the commit message?

No, these only work in commit messages. Not sure if it's worth adding them in the PR description since we might want some commits to run the CI and some commit to skip the CI.
