### ISSUE TITLE
Documentation in spearmanr

### ISSUE THREAD

**Issue by davidsuculum** [scipy/scipy#16148]
I think it would be great if the line in [spearmanr](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.spearmanr.html) function: "_Unlike the Pearson correlation, the Spearman correlation does not assume that both datasets are normally distributed"_ is corrected, because Pearson **does not** assume normality for the calculation of the coefficient, only for the p-values calculation. I think an specific mention to the p-value would avoid this source of potential confusion.

Here, commenting that Pearson's coefficient does not assume normality: [https://stats.stackexchange.com/questions/3730/pearsons-or-spearmans-correlation-with-non-normal-data](https://stats.stackexchange.com/questions/3730/pearsons-or-spearmans-correlation-with-non-normal-data)

**Comment by tupui** [comment]
Hi @davidsuculum thank you for reporting. Any documentation update is welcomed. I think we would need a reference from a reference paper since this is something people argue about.

**Comment by davidsuculum** [comment]
Hi, there's this article but I can't readit: https://psycnet.apa.org/doiLanding?doi=10.1037%2Fh0048216[](https://psycnet.apa.org/doiLanding?doi=10.1037%2Fh0048216). In Wikipedia's article you find no mention to normality of the datasets for Pearson's correlation, except when doing the inference and calculating the p-values. I have also checked in my copy of "Foundations of Agnostic Statistics" (Aronow, Miller), where the correlation coefficient is introduced and no mention to normality of the variables is commented. Could all this help?

**Comment by josef-pkt** [comment]
As a descriptive statistic, Pearson correlation only measures `linear` association while spearmanr is for `monotonic` association.
Descriptive statistics like variance and correlation (pearson, spearman, kendalltau) do not depend on any distributional assumptions.

For the descriptive statistic the only relationship to normal distribution is that the conditional mean of a bivariate normal distribution is linear.

For inference like p-values the distributional assumptions are important.
(but I don't know how pvalues for spearmanr are derived.)

**Comment by josef-pkt** [comment]
I don't think changing the docstring and dropping the mention of a normality assumption for the correlation itself needs a reference.
We are using (prarson) correlation on any kind of data all the time.

**Comment by tupui** [comment]
All right then if there is no disagreement. @davidsuculum feel free to make a PR 😃

**Comment by mdhaber** [comment]
Picking low hanging fruit: gh-16470.
