### ISSUE TITLE
Error in scipy.stats.mannwhitneyu documentation

### ISSUE THREAD

**Issue by migp11** [scipy/scipy#16164]
Below is the docstring of the `scipy.stats.mannwhitneyu` function (scipy==1.8.0)
If *F(u)* and *G(u)* are the cumulative distribution functions of the distributions underlying `x` and `y`, respectively
then the hypothesis for 'greater' would be *F(u) > G(u)* for all *u*, right?. However, in the documentation, the inequality is written in the other direction. And the same for the 'less' hypothesis.

```
Parameters
----------
x, y : array-like
    N-d arrays of samples. The arrays must be broadcastable except along
    the dimension given by `axis`.
use_continuity : bool, optional
    Whether a continuity correction (1/2) should be applied.
    Default is True when `method` is ``'asymptotic'``; has no effect
    otherwise.
alternative : {'two-sided', 'less', 'greater'}, optional
    Defines the alternative hypothesis. Default is 'two-sided'.
    Let *F(u)* and *G(u)* be the cumulative distribution functions of the
    distributions underlying `x` and `y`, respectively. Then the following
    alternative hypotheses are available:
    
    * 'two-sided': the distributions are not equal, i.e. *F(u) ≠ G(u)* for
      at least one *u*.
    * 'less': the distribution underlying `x` is stochastically less
      than the distribution underlying `y`, i.e. *F(u) > G(u)* for all *u*.
    * 'greater': the distribution underlying `x` is stochastically greater
      than the distribution underlying `y`, i.e. *F(u) < G(u)* for all *u*.
```

**Comment by josef-pkt** [comment]
Note, If `*F(u) > G(u)* for all *u*` , then x ~ F has smaller values (in probability) than y ~ G.
so, x is stochastically smaller than y.

Larger cdf means that smaller values have higher probability.

similar confusion showed up also for the one-sided kstest.

**Comment by josef-pkt** [comment]
However, the statement is not actually correct, not in general without additional assumptions on F and G.

The mannwhitneyu statsitics is for a weaker form of stochastic dominance.
The statement is for first order stochastic dominance F > G, but mannwhitneyu statistic is for P(x < y) = 0.5 (in continuous distributions) versus P(x < y ) > 0.5 or P(x<y) < 0.5.

AFAIR

**Comment by migp11** [comment]
Hi Josep,

Thanks for the clarification. I see it more clearly now. From my point of view, it is a more intuitive expression of the hypothesis using the PDF, i.e. P(x>y) > 0.5 (for greater) as is also explained in Wikipedia:

".... The probability of an observation from population X exceeding an observation from population Y is different (larger, or smaller) than the probability of an observation from Y exceeding an observation from X; i.e., P(X > Y) ≠ P(Y > X) or P(X > Y) + 0.5 · P(X = Y) ≠ 0.5...."

[https://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test](https://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test)

It is clear to me now, though the way it is explained in the documentation could be confusing.

**Comment by tupui** [comment]
Documentation improvement are always welcomed.

**Comment by josef-pkt** [comment]
As reference here are my notes, docs for Wilcoxon-Mann-Whitney’s U test, Fligner-Policello test and Brunner-Munzel test
 https://www.statsmodels.org/dev/generated/statsmodels.stats.nonparametric.rank_compare_2indep.html#statsmodels.stats.nonparametric.rank_compare_2indep

**Comment by migp11** [comment]
Thanks! I'll go through the notes. By the way, be aware that either there is a typo in the doc string on one of the parameters
`use_t: poolean`
or there is a new data type I did not know anything about XD

**Comment by mdhaber** [comment]
For reference, SciPy's description of the alternatives is directly from the [original paper](https://www.jstor.org/stable/pdf/2236101.pdf):
![image](https://user-images.githubusercontent.com/6570539/168322397-2ce058bb-84fe-48ea-9bdf-1f7443b31a23.png)
