### ISSUE TITLE
ENH:  Which parameters of Welch do determine the length of the output? (python)

### ISSUE THREAD

**Issue by reihanehk** [scipy/scipy#16199]
### Is your feature request related to a problem? Please describe.

I am using Welch in python.
 Which parameter in Welch does define the length of the output array? Based on my trials, the output length is related to nperseg/2; but I cannot understand its reason and mathematics. And, I am not sure about the effect of other parameters on the output length.

Also, there is not enough explanation in its documentation (https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.welch.html)

I will be more than happy if anyone can help me. I could not find any clear info on the web!

**Comment by tupui** [comment]
Hi @reihanehk, thank you for reporting. I will close this issue as we don't have sufficient bandwidth to answer user questions. I invite you to ask your question on other forums such as StackOverflow.

**Comment by rkern** [comment]
Recall that FFTs report both positive and negative frequency terms, but for real-valued signals, those contain the same information. Thus the periodogram only reports the positive-frequency half (plus the `f=0` term). The Welch periodogram is an average of several periodograms computed from FFTs that are `nperseg` in length, so it will be `nperseg//2 + 1` (the `+1` for the `f=0` term).
