### ISSUE TITLE
BUG: Scipy can't be downloaded on M1 2020

### ISSUE THREAD

**Issue by AngelikB** [scipy/scipy#16192]
### Describe your issue.

Hello everyone!

I don't use this platform very often and I'm trying to find a solution for a few errors if someone has any ideas, that would be super nice.
It seems spicy can't be downloaded here, I tried pip instal spicy and brew install spicy but none of these work.
(I'm on a M1 2020)
Have a good one!

### Reproducing Code Example

```python
[Collecting scipy==1.6.1
Using cached scipy-1.6.1.tar.gz (27.3 MB)
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing metadata (pyproject.toml) ... error
error: subprocess-exited-with-error

× Preparing metadata (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [4 lines of output]
setup.py:463: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /private/var/folders/2s/9j3z_ls129b3cpsx824sc01r0000gp/T/pip-modern-metadata-354tp06i'), proceeding with generating Cython sources and expanding templates
' '.join(sys.argv[1:])))
Error: 'None' must be installed before running the build.

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.]
```

### Error message

```shell
error: subprocess-exited-with-error

Error: 'None' must be installed before running the build

error: metadata-generation-failed
```

### SciPy/NumPy/Python version information

distlib 0.3.4, filelock  3.6.0, numpy 1.22.3, pip 22.0.4, pipenv 2022.5.2, platformdirs 2.5.2, pybind11 2.9.2, scipy 1.8.0, setuptools 60.10.0, six 1.16.0, virtualenv 20.14.1, virtualenv-clone 0.5.7, wheel 0.37.1

**Comment by tupui** [comment]
Hi @AngelikB, thank you for reporting. I will close this issue as it's been discussed already. Please look for similar issues in the tracker. You probably have macOS < 12 (BigSur) as we only provide wheels for Monterey on M1.
