### ISSUE TITLE
BUG: OptimizeResult from optimize.minimize_scalar changes 'x' type if convergence is found in first step.

### ISSUE THREAD

**Issue by melomcr** [scipy/scipy#16196]
### Describe your issue.

Executing an optimization of the same function through `optimize.minimize_scalar`, but with different bounds or tolerance values, is causing the type of the `x` attribute of the `OptimizeResult` object to change between executions.

In this example, the function returns after the first iteration. The `x` value is a scalar.

 ```
 Func-count     x          f(x)          Procedure
    1     3.2482e-09  -3.8548e+08        initial

Optimization terminated successfully;
The returned value satisfies the termination criteria
(using xtol =  1e-05 )
     fun: array([-3.8547964e+08])
 message: 'Solution found.'
    nfev: 1
     nit: 1
  status: 0
 success: True
       x: 3.2481988817183283e-09
```

In this example, the function is called with an explicit tolerance value that forces it to iterate further, and returns after the 8th iteration. The `x` value is now a numpy array (as it should be, according to the documentation).

``` 
 Func-count     x          f(x)          Procedure
    1     3.2482e-09  -3.8548e+08        initial
    2    4.34094e-09 -1.14571e+07        golden
    3    2.57285e-09      -543583        golden
    4    3.46288e-09 -9.51544e+08        parabolic
    5    3.74413e-09 -1.55055e+09        parabolic
    6    3.97209e-09 -9.13931e+08        golden
    7    3.71079e-09 -1.53441e+09        parabolic
    8    3.77746e-09 -1.53008e+09        parabolic

Optimization terminated successfully;
The returned value satisfies the termination criteria
(using xtol =  1e-10 )
     fun: array([-1.55054734e+09])
 message: 'Solution found.'
    nfev: 8
     nit: 8
  status: 0
 success: True
       x: array([3.74412799e-09])
```
I understand that multiple optimization approaches in SciPy have different output formats, but the same optimizer should not change output types depending on iterations.

Looking at the code, I could not pinpoint the location where this `x` value changes to an nd array, but it consistently returns as a scalar if only one iteration is performed before termination. 

### Reproducing Code Example

```python
import numpy as np
from scipy import stats, optimize

testArray = np.array([3.98870996e-09, 3.98826001e-09, 3.67428003e-09, 3.76826001e-09,
       3.61183008e-09, 3.77692993e-09, 3.95031006e-09, 2.96020996e-09,
       3.35727002e-09, 3.52889990e-09, 3.38438989e-09, 3.95433008e-09,
       3.37065991e-09, 3.19607007e-09, 3.86244995e-09, 3.35210010e-09,
       3.60525000e-09, 3.87412988e-09, 3.79013989e-09, 3.75905005e-09,
       3.89471997e-09, 3.40269995e-09, 3.72817993e-09, 3.72587988e-09,
       3.89586011e-09, 3.75660010e-09, 3.77033008e-09, 3.41007007e-09,
       3.39072998e-09, 4.01754004e-09, 3.57187012e-09, 3.65805005e-09,
       3.54221997e-09, 3.86550000e-09, 3.43247998e-09, 2.99565991e-09,
       3.63393994e-09, 3.74633008e-09, 3.83310010e-09, 3.70584009e-09,
       3.64812988e-09, 4.07268994e-09, 3.72121997e-09, 3.58945996e-09,
       3.82662988e-09, 3.98991992e-09, 3.66976001e-09, 3.42454004e-09,
       3.54378003e-09, 3.76230005e-09])

kdeModelForces = stats.gaussian_kde(testArray, bw_method="silverman")

result = optimize.minimize_scalar(lambda x: -kdeModelForces(x), 
                                  bounds=[testArray.min()*0.5,
                                          testArray.max()*1.5], 
                                  method="Bounded", 
                                  options={'disp':3}, 
                                  tol=None)

print(result)

print(" ------- ")

result = optimize.minimize_scalar(lambda x: -kdeModelForces(x), 
                                  bounds=[testArray.min()*0.5,
                                          testArray.max()*1.5], 
                                  method="Bounded",
                                  options={'disp':3},
                                  tol=1.0e-10)

print(result)
```

### Error message

```shell
---
```

### SciPy/NumPy/Python version information

`1.8.0 1.22.3 sys.version_info(major=3, minor=9, micro=12, releaselevel='final', serial=0)`

**Comment by mdhaber** [comment]
@seberg I came up with many ways to convert a python scalar, NumPy scalar, or size 1 NumPy array to a NumPy scalar of the appropriate `dtype`. The simplest is probably:
```python3
x = np.atleast_1d(x)[0]
```
What is the preferred way?
---
Related: I was surprised by this:
```python3
np.float32(np.array([1])).shape  # (1,)
np.float64(np.array([1])).shape  # ()
```

**Comment by seberg** [comment]
Do you need the squeeze?  If you  know you got a 0-D array, I would suggest `arr[()]`.  The last one is because it uses `float(...)` which it inherits from Python `float`.  We had discussed a lot to deprecate allowing `float(size_1_array)` (which would hange the behavior there), I think there is even a PR on it, which could be breathed in new momentum.

**Comment by mdhaber** [comment]
> Do you need the squeeze? 

Last night I thought so.

This morning I've decided to `reshape` to one dimension fewer than what the user-provided `bracket`.
Currently, users are only _supposed_ to pass in a 1D sequence of scalars, so the output now _should_ only be 0d. 

But it would be reasonable to vectorize this function in the future, so it is reasonable to respect the shape of the user's input as long as each of its elements has size 1. So I will use `reshape` in the PR.

**Comment by mdhaber** [comment]
@seberg 

> If you know you got a 0-D array, I would suggest arr[()]

Sure, that was part of my original solutions, but that doesn't work if the values are Python scalars. 

So the idiomatic way of ensuring that a value that could be a Python scalar, NumPy scalar, or NumPy 0D array is a NumPy scalar of the appropriate type is:

```python3
x = np.asarray(x)[()]
```

And if I _do_ need to also handle cases in which the value might be array-like of size 1, you would suggest:

```python3
x = np.asarray(x).squeeze()[()]
```
?

**Comment by seberg** [comment]
I think I have to look at what you got.  If you know your input has size 1 of "compatible" shape (whatever that means) and want to make sure the result is an array: Then yes, squeeze is OK, although I am confused by it.

I am confused by "be a Python scalar, NumPy scalar, or NumPy 0D array", I thought we were talking about function results not inputs.  For an input, it makes sense to me to always call `np.asarray()` first, and after that, you have an array.

There is another question though, if this function passes on the scalar value as  Python value to a user callback, passing the Python value may be more performant, and converting it undesireable?
