### ISSUE TITLE
ENH: Support Random Unit Vector

### ISSUE THREAD

**Issue by saroad2** [scipy/scipy#16205]
### Proposed new feature or change:

Description
========

Often you want to randomize a "direction" that doesn't have "size". This can be useful when:
* You want to randomize the direction of an NPC walk in a 2D or 3D games, where its speed is a predefined constant.
* You're developing particles simulation with all particles moving in random directions
* etc.

This random direction should be an `n`th dimensional unit vector which is randomized **uniformly** from the unit sphere. That means that sections of the unit sphere with equal areas should have the same chance of getting a vector from.

Implementation
===========

If one wants to randomize `n`th dimensional direction uniformly, one must do the following:
1. Generate `n` components of the vector using the standard normal distribution
2. Find the norm the generated vector
3. Divide the vector by its norm

In simple Python code:
```python
import numpy as np
from scipy import stats


def sphere_uniform(n: int):
    vec = stats.norm.rvs(size=n)
    size = np.linalg.norm(vec)
    return vec / size
```

This implementation suggestion is based on [this blog post](https://towardsdatascience.com/the-best-way-to-pick-a-unit-vector-7bd0cc54f9b). I'm not sure if there's a faster way of implementing it using C++ and Cython, but I'm confident that someone here will know.

Why Implement It in *Scipy*?
===================

Originally, I suggested implementing it on *Numpy* (numpy/numpy#21523), but they stated that they are not interested in expending the `numpy.random` library and suggested adding this new feature as part of `scipy.stats`.

I believe that random unit vectors are common enough to be a part of *Numpy* or *Scipy*, which are two of the most popular python libraries (if not the most popular ones). Scientists, gamers and engineers use random directions all the time, and I believe there is no reason why this ability shouldn't be provided out-of-the-box.

**Comment by ilayn** [comment]
Seems a bit too specific to be on its own as a function to be honest. The following is sufficient (similar to what you have instead you want a uniform distribution):

```python
import numpy as np

def unit_vector(n: int):
    rng = np.default_rng()
    vec = rng.random(n)
    vec /= np.linalg.norm(vec)
    return vec
```

It gets even shorter if you don't mind using `np.random.rand(n)` directly. Hence I think this is a bearable burden for any use.

**Comment by ilayn** [comment]
I have quite some technical issues with that blogpost but regardless of the distribution which involves no additional code for changing it normal distribution, this is still a two-liner code that I would prefer burdening the user instead of maintaining within scipy or numpy.

**Comment by saroad2** [comment]
I understand.

Thanks anyway

**Comment by rkern** [comment]
Uniformly-random vectors on the unit hypersphere is an important multivariate distribution. It's not _hard_ to implement oneself, _if_ one knows the necessary trick (and yes, the normal distribution _is_ necessary). If one doesn't know the appropriate trick, ad hoc implementations tend to fail in ways that are hard to diagnose in higher dimensions than 2.

**Comment by dschmitz89** [comment]
What could be a good API for this?
Sth like a distribution `scipy.stats.UniformUnitSphere` with method `rvs` or just a function `scipy.stats.randomunitvector(size)` ?

**Comment by mdhaber** [comment]
The former, I think. It would fit well as a subclass of `multi_rv_generic` in [`_multivariate.py`](https://github.com/scipy/scipy/blob/main/scipy/stats/_multivariate.py).

**Comment by saroad2** [comment]
Good to see that other people find this feature needed and usefull.

Do I have a go on implementing it?

**Comment by dschmitz89** [comment]
I asked on the mailing list if there are any objections against this and a function for spherical mean/variance. If there are none , I think it can be taken as a yes in a few days.

**Comment by mdhaber** [comment]
I think that's true, @dschmitz89.

One thing to look out for is to not start with the shortcomings we're addressing in gh-16278. If you use another multivariate distribution as a reference, you may be tempted to add `np.squeeze` to the output of `rvs`. This is undesirable. If `d` is the number of dimensions and `size` is passed in as a shape parameter (or `()` if `size is None`), then the output shape should be `size + (d,)`. (I think it's OK to support only scalar `d` for now because there is a decision to be made w.r.t. [how to vectorize over array shapes](https://github.com/scipy/scipy/issues/7689#issuecomment-1140394967).)

**Comment by rkern** [comment]
`multi_rv_generic` instances have methods that take the distribution parameters. One instance of the `multi_rv_generic` is made at the module level.

```python
stats.multivariate_normal.pdf(x, mean, cov)
```

`multi_rv_frozen` instances are created by calling the `multi_rv_generic` instance with the distribution parameters. The frozen instance then carries those distribution parameters around so that you can call the methods without providing the distribution parameters.

```python
my_norm = stats.multivariate_normal(mean, cov)
my_norm.pdf(x)
```

This scheme is relatively complicated for the multivariate distributions because each one is fairly different from the others. The univariate distributions have much more shared infrastructure and only need to implement the `generic` class. They all share a `frozen` implementation.

**Comment by mdhaber** [comment]
@saroad2 are you still interested in implementing this? If you do, I can review and merge.

**Comment by saroad2** [comment]
Hey @mdhaber.

After many hours of trying, I could not build *Scipy* on my Windows environment. It was really frustrating.
Unfortunately, I don't have access to a Linux or Mac environments, so I cannot implement this ability for now.

Would love to see this ability implemented! It should be quite easy once you get to build *Scipy*...

**Comment by dschmitz89** [comment]
@saroad2 I am using the Windows Subsystem for Linux on Windows 11. Works like a charm there with the instructions for conda given [here](https://docs.scipy.org/doc/scipy/dev/dev_quickstart.html) . I admit, I have not even tried to build using windows directly. Anything related to complex compiled code on Windows has always been very painful for me too (Fortran ... :'( ).
There is a discussion about building on windows in #16769 .

In case you cannot find the time, I would be able to take this over.

**Comment by saroad2** [comment]
Hey @dschmitz89 , thanks for the feedback!

In the following weeks I will not be able to work on this. A little bit preoccupied with other things.

I would love if you could take over so I won't block it.

Thanks!
