### ISSUE TITLE
ENH: Please make the "cutoff" variable in "scipy.sparse.linalg.svds" user-definable

### ISSUE THREAD

**Issue by mgoldeli** [scipy/scipy#16210]
### Is your feature request related to a problem? Please describe.

Please add an option to "scipy.sparse.linalg.svds" to set the "cutoff" parameter to zero or please give the option not the use this cutting off option in svds function. This option is something we need for our python package "pyFBS". We are working on a new filter implementation based on truncated singular value decomposition, so svds. Since "scipy.sparse.linalg.svds" is a very strong tool for calculating a subset of singular values, we are also using it integrated with our python package. But, we need the option which allows us to set the cutoff parameter to zero. I do not want to use the "sophisticated detection of small eigenvalues from pinvh", which is used by "scipy.sparse.linalg.svds" automatically. Please make it used-defined or give the user the option to not use this cutting off the singular values.

### Describe the solution you'd like.

Solution 1: Adding an additional input parameter in "svds" funtion for "cutoff" variable, so that a user can set it to zero.

User can call the svds function as below:
svds(A, k=10, **cutoff=0**)

Modifications should be done in svds function:
svds(A, k=6, ncv=None, tol=0, which='LM', v0=None, maxiter=None, return_singular_vectors=True, solver='arpack', random_state=None, options=None, **cutoff=None**)
        ...
        if cutoff=None:
            # Use the sophisticated detection of small eigenvalues from pinvh.
            t = eigvec.dtype.char.lower()
            factor = {'f': 1E3, 'd': 1E6}
            cond = factor[t] * np.finfo(t).eps
            cutoff = cond * np.max(eigvals)
        else:
            cutoff = **_user-defined value_ (which is 0 in this case)**
        ...

### Additional context (e.g. screenshots, GIFs)

We need this feature/option for our new filter implementation. Please put this option in the new version of scipy.

**Comment by tupui** [comment]
Hi @mgoldeli, thank you for reporting. I am not sure about adding this parameter since not all solvers are doing this cutoff. If you use `solver=propack`, you won't go into this logic.

**Comment by ftrainotti** [comment]
Hi guys,

Propack still seems to have some problems with Windows. Can you confirm that?
Using the cutoff threshold with the Arpack solver may cause some undesired removal of SVs (in many cases it starts cutting SVs of 5/6 orders lower than the maximum one). If I have some criteria to select a specific number of SVs, I should be able to retain them without encountering further constraints. The matlab svds implementation is also based on Arpack and does not encounter similar issues.
I'd would be really nice if you could add such an option or, in alternative, solve the issues of Propack.

**Comment by tupui** [comment]
Is there an issue open about the problems with Propack you are referring to @ftrainotti?

**Comment by mgoldeli** [comment]
I am having an issue with "propack" solver. The error is as follows:
 _Fortran runtime error: Insufficient number of elements in TARRAY._

Apparently, there are still some issues with "propack" solver. I tried it out also with the lastest version of scipy, but I am not able to run the code or use "propack" solver option right now. I read that this option will be fully available in the next scipy version. I am looking forward to testing the fully available version soon.

On the other hand, I think it is still necessary to have this "cutoff = 0" option (or a similar implementation) also for the "arpack" algorithm. We want to use the "arpack" algorithm without cutting off the smallest eigenvalues, which is very important for our new filter implementation that we will have in our python package soon. We have already the matlab implementation of this new svds based filter. **In matlab with svds command**, we are able to get **all the singular values ****without cutting off the smallest singular values** (Matlab also uses in svds the Arpack algorithm as defautl). Also **with svds of scipy**, we are able to get **all the singular values, only if we set the cutoff value to zero.** Due to this automatic/not-user-defined cutting off of the smallest singular values in svds of scipy, we can not keep the quality level of our new filter implementation. That's why, I think this cutoff variable should be user-defined. With this enhancement, scipy will serve the option to its users to have consistent results with the matlab, which I think is a high reliable reference software for such applications.

**Comment by tupui** [comment]
To clarify, I am not opposed to adding this option if it does something for all solvers. What I want to say is, as it is if we were to add this parameter it could be confusing for users of Propack.

**Comment by tupui** [comment]
> Apparently, there are still some issues with "propack" solver. I tried it out also with the lastest version of scipy, but I am not able to run the code or use "propack" solver option right now. I read that this option will be fully available in the next scipy version. I am looking forward to testing the fully available version soon.

Did you set the env variable `USE_PROPACK=1`? Propack came with SciPy 1.8

**Comment by ftrainotti** [comment]
I tried the following on a windows pc with python 3.8.13 and scipy 1.8.1:

------------------------------------
import os
os.environ["USE_PROPACK"]='1'
"USE_PROPACK" in os.environ

import scipy.sparse.linalg as sp
import numpy as np
rng = np.random.rand(1000,1000)

u, s, vT = sp.svds(rng, k=3, solver='arpack')
u2, s2, v2T = sp.svds(rng, k=3, solver='propack')
---------------------------------------------------------------

when I run propack, I get:
'Restarting kernel'
--------------------------------------
What am I doing wrong? I don't get it

**Comment by tupui** [comment]
This is probably what is referred to as issues on windows. Sorry I cannot help I don't have a windows. @mckib2 is this fixed on main?

**Comment by ogauthe** [comment]
This is a dupplicate of #12629
I hope #11829 will solve the problem.

**Comment by tupui** [comment]
Indeed, I will link it. Thank you!

**Comment by mgoldeli** [comment]
Hey Olivier, 

Thank you for your contribution here. 

I went through your [#11829](https://github.com/scipy/scipy/pull/11829 ) and It seems that this issue is still open and still needs to be enhanced/fixed. You meant that this  [#11829](https://github.com/scipy/scipy/pull/11829 ) can solve my issue, but I am still confused about how did you deactivate this cutting off the smallest singular values issue in svds. **I need to get also these smallest singular values in the output of svds function** and **not the zero**s and I don't want to use an additional svd function which is time wasting compared to svds. 

As far as I get it, the solution that you suggest in [#11829](https://github.com/scipy/scipy/pull/11829 ) can be done locally by modifiying your code on your pc, right?  But that makes no sense for us as python package developers, since we want to give our users a complete code and we can't say to our users "_please change your svds code manually, if you want to use our new filter_". That is not a solution for us! Can you please explain me the solution that you suggest precisely or is this issue still not solved?

**Comment by tupui** [comment]
I suggest continuing the discussion in #12629. Maintainers of this part of SciPy will be notified as they contributed to the discussion.

**Comment by mgoldeli** [comment]
@tupui Okay fine. I will continue on [#12629](https://github.com/scipy/scipy/issues/12629)
