### ISSUE TITLE
Issue with scipy 1.5.4 // Python 3.6.9 on ubuntu while importing scipy.stats on flask

### ISSUE THREAD

**Issue by gregou2007** [scipy/scipy#16218]
Hello,

We have an issue in an flask application while importing scipy.stats on our application on an python 3.6.9 ubuntu apache2 environnement with scipy 1.5.4. The page we include scipy.stats using "from scipy.stats import norm" loops indefinitively, nothing on the error log....

The same exact code works on a test/dev machine with python 3.8 and scipy 1.8 // apache 2 on windows 

Do you know from where the problem can be ? 

thanks

**Comment by tupui** [comment]
Hi @gregou2007, thanks for reporting. Since the issue does not appear on latest I will close this. I am sorry but we don't have the bandwidth to do user support. Please consider other forums such as StackOverflow.
