### ISSUE TITLE
BUG: Possible bug when using winsorize on pandas data instead of numpy data

### ISSUE THREAD

**Issue by ddeloss** [scipy/scipy#16211]
### Describe your issue.

When `scipy.stats.mstats.winsorize` is used with a `nan_policy` of `omit` on a numpy array it behaves as expected. However, when used on Pandas data such as a series, all NaNs are converted to the maximum possible value. I believe this may be a bug, but could possibly be an enhancement if pandas data is never meant to be used. An example can be seen in the image below:

![image](https://user-images.githubusercontent.com/3191351/169163081-c17f9770-38c5-413c-bee0-5189d3a7fc35.png)

### Reproducing Code Example

```python
import numpy as np
import pandas as pd
from scipy.stats.mstats import winsorize

nans_10 = list(np.repeat(np.nan,10))
data = np.array(
	nans_10
	+ list(range(100))
	+ nans_10
)


print(f"Numpy array: {winsorize(data, (0.2, 0.2), nan_policy = 'omit')}")

print(f"Pandas series: {winsorize(pd.Series(data), (0.2, 0.2), nan_policy = 'omit')}")
```

### Error message

```shell
No error/warning message is given. The behavior is just unexpected. The pandas version used was 1.4.2.
```

### SciPy/NumPy/Python version information

1.8.0 1.21.6 sys.version_info(major=3, minor=10, micro=2, releaselevel='final', serial=0)

**Comment by ddeloss** [comment]
The code is also in there as the "reproducible code example."

**Comment by mdhaber** [comment]
<facepalm>

**Comment by mdhaber** [comment]
The problem was that `_contains_nan` relies on the sum of the array to be `nan` if there are any NaNs. This is not true for Pandas types, which ignore NaNs by default. I'll submit a PR.
