### ISSUE TITLE
BUG: take ~10X times from different docker parameter

### ISSUE THREAD

**Issue by shqcandy** [scipy/scipy#16222]
### Describe your issue.

i use same docker image run same code, and take 10X times
ENV-1 (11.643s) : docker run -itd --cpus 2 --name docker_cpu_2 \<docker-image\>
ENV-2 (1.124s) : docker run -itd --cpuset-cpus 10,11 --name docker_core_cpu_2 \<docker-image\>

i want know what happen behind it, and can't get any message from the web.

### Reproducing Code Example

```python
import sys
import json
import time
import numpy as np
from sklearn import decomposition
from scipy.linalg.decomp_svd import svd
from scipy import linalg
import numpy as np

def main():
    start = time.time()
    num = 100
    x = np.random.standard_normal((num, num))
    y = np.random.standard_normal((num))
    #pca = decomposition.PCA()
    #pca_result = pca.fit(x)
    svd(x)
    # linalg.solve(x, y)

if __name__ == "__main__":
    start = time.time()
    for line in range(10):
        main()
        print(time.time() - start)
```

### Error message

```shell
ENV-1: 
         780828 function calls (764406 primitive calls) in 11.640 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   1316/1    0.032    0.000   11.643   11.643 {built-in method builtins.exec}
        1    0.000    0.000   11.643   11.643 pca_demo.py:13(<module>)
       10    0.000    0.000   10.001    1.000 pca_demo.py:24(main)
       10    9.991    0.999    9.993    0.999 decomp_svd.py:13(svd)
    954/4    0.007    0.000    1.641    0.410 <frozen importlib._bootstrap>:978(_find_and_load)


ENV-2:
         781270 function calls (764848 primitive calls) in 1.121 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   1316/1    0.030    0.000    1.124    1.124 {built-in method builtins.exec}
        1    0.000    0.000    1.124    1.124 pca_demo.py:13(<module>)
    954/4    0.006    0.000    1.065    0.266 <frozen importlib._bootstrap>:978(_find_and_load)
    954/4    0.005    0.000    1.065    0.266 <frozen importlib._bootstrap>:948(_find_and_load_unlocked)
    872/4    0.005    0.000    1.064    0.266 <frozen importlib._bootstrap>:663(_load_unlocked)
```

### SciPy/NumPy/Python version information

scipy==1.5.4; 1.21.5==1.21.5

**Comment by shqcandy** [comment]
SciPy/NumPy/Python version information 
1.5.4 1.21.5 sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)

**Comment by ragibson** [comment]
This code takes 1-4 milliseconds per loop iteration on my machine.

I think you're basically just benchmarking docker startup times, so this is unrelated to scipy.

**Comment by rgommers** [comment]
Docker should have started by then, if you can run a Python script. My guess is that the `svd` call actually does take that much longer, because with `--cpus` vs. ``cpuset-cpus` there's a difference in how many CPUs appear to be available (one says `2`, one says `n-cores-in-machine`, and OpenBLAS suffers from oversubscription. To verify this, please try running both with `export OPENBLAS_NUM_THREADS=1` and measure again (assuming you use OpenBLAS).

Either way, it's not a SciPy issue though.

**Comment by rgommers** [comment]
I'll close this, because it's not something we can do anything about.
