### ISSUE TITLE
ENH: intFFT and fxpFFT

### ISSUE THREAD

**Issue by yoav-palti** [scipy/scipy#16237]
### Is your feature request related to a problem? Please describe.

Usually when getting a signal from the sampler each sample has a fixed sample depth and hance it is very natural to represent it as int16 (or int8, depending on the sampler). scipy has already an implementation that use the fact that the signal can be real in order to boost computation speed.  I came across an article about intFFT that calculate the FFT with fix point values witch should be much faster (if I am not mistaken). intFFT not like fxpFFT (fix point FFT) is invertible and they claim in the article it can be implemented with only bit shifts and additions but no multiplication.
I don't know if its an issue for scipy of other c lib that scipy uses.
The article is:
Soontorn Oraintara, Ying-Jui Chen, Truong Q. Nguyen "Integer Fast Fourier Transform" (IEEE TRANSACTIONS ON SIGNAL PROCESSING, VOL. 50, NO. 3, MARCH 2002)
A more readable explanation can also be found here:
https://link.springer.com/content/pdf/10.1007%2F978-1-4020-6629-0_4.pdf

### Describe the solution you'd like.

Two functions under scipy.fft
one is intfft and the other is iintfft (the inverse) that calculate using this method.

**Comment by mreineck** [comment]
For convenience: I found a non-paywalled PDF of he article at https://www.researchgate.net/publication/3908291_Integer_fast_Fourier_transform_IntFFT.

I'm not sure how much performance advantage this algorithm would give us ... we already have `rfft` and `irfft` to speed up situations where the input is purely real or Hermitian, which covers one of the aspects mentioned.
It's undeniable that bit-shift operations are typically much faster than floating-point multiplications, but the main factor that limits performance for FFTs is not the computing power of the CPU, but rather the latency of memory transfers. (At least for FFTs that are not very short ... and for very short FFTs other aspects like the calling overhead from Python become important.)

In the paper I only see transform lengths of `2**N`, whereas an alternative to `scipy.fft` would have to support arbitrary lengths. Do you know wheher an IntFFT approach exists for non-power-of-two lengths as well?

As the authors mention also, I expect the main use of IntFFT will be in mobile and embedded devices, at a level very close to the hardware and for vry specific tasks; under these circumstances it can be more energy-efficient (and perhaps also faster) than floating-point FFT. In a high-level, general purpose package like `scipy`, I'm not sure the effort of implementing it will be worthwhile.

**Comment by yoav-palti** [comment]
I don't know if there an non `2**N` algorithm but they state 
"In this paper, lifting factorization is proposed to be used in the fast
structures of the DFT where complex multiplications are
expressed in terms of liftings. The approach can be used in
many existing structures such as radix-2, radix-4 and splitradix **with arbitrary sizes**"

Another use is compression and reversibility. some usages require the ability to perfectly reconstruct the original array.
I wasn't aware that the bottleneck is memory transfer...

**Comment by mreineck** [comment]
I don't doubt that there are perfectly good use cases for the algorithm; but I do think that they are _very_ specialized, and that each of them may have different particular requirements (e.g. number of bits in the input type that need to be reconstructed perfectly). So a generic implementation in a general-purpose package like `scipy` will find very few users, if any.
(I'd be happy to be proven wrong of course!)

**Comment by yoav-palti** [comment]
Thanks for the response.
Leaving the issue open for more comments...
If no interest in this enhancement will come I will close the issue
