### ISSUE TITLE
ENH: I wonder if scipy can support spline interpolation in higher dimensions (i.e. 3D or 4D)

### ISSUE THREAD

**Issue by SuiFeng2020** [scipy/scipy#16244]
### Is your feature request related to a problem? Please describe.

I wonder if scipy can support spline interpolation in higher dimensions (i.e. 3D or 4D).  I know that 2D spline interpolation is now supported in scipy.

**Comment by ev-br** [comment]
Assuming you mean tensor product splines on (hyper)rectangular grids, `RegularGridInterpolator` has recently acquired "cubic" and "quintic" modes, see http://scipy.github.io/devdocs/reference/generated/scipy.interpolate.RegularGridInterpolator.html#scipy.interpolate.RegularGridInterpolator

This is very new will be available in scipy 1.9.0 when it's released. Until then it's only available in the development version. Feedback is appreciated BTW!

**Comment by SuiFeng2020** [comment]
Exactly what I need, thanks for your reply! Best wish!

**Comment by ev-br** [comment]
Closing as completed then.
