### ISSUE TITLE
DEP: add deprecation warnings to kwargs `turbo` / `eigvals` of `linalg.eigh`

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#16252]
Deprecated in documentation only since https://github.com/scipy/scipy/pull/11304

CC @ilayn

**Comment by hfactor13** [comment]
Isn't this issue just a duplicate of #16355? After looking at that issue number, they seem very similar. I suggest adding a duplicate tag if that's the case.

**Comment by h-vetinari** [comment]
> Isn't this issue just a duplicate of #16355? After looking at that issue number, they seem very similar.

This is the issue and #16355 is the PR intended to close this issue - no duplication, but a very intimate relation.
