### ISSUE TITLE
ENH: How to install Scipy1.90 developer version in windows environment？

### ISSUE THREAD

**Issue by SuiFeng2020** [scipy/scipy#16250]
### Is your feature request related to a problem? Please describe.

How to install Scipy1.90 developer version in windows environment？ Do you have any reference tutorials, thanks a lot!

**Comment by AtsushiSakai** [comment]
Might this document help you?: [Building from source on Windows — SciPy v1\.8\.2\.dev0\+2333\.b76137f Manual](http://scipy.github.io/devdocs/building/windows.html#build-windows)

**Comment by tupui** [comment]
Hi @SuiFeng2020 thank you for reporting. I am closing the issue as we don't have the bandwidth to answer user questions. Usually it's better to ask questions on forums such as StackOverflow. If you have issues after reading the windows guide @AtsushiSakai linked, I would be happy to reopen this 😃
