### ISSUE TITLE
DEP: add deprecation warning for binom_test 

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#16256]
This was originally planned in https://github.com/scipy/scipy/pull/12603 already but was then weakened to a doc-only deprecation in https://github.com/scipy/scipy/commit/c88177cd5e43117628a440f33ccabc7efd35beac based on [feedback](https://github.com/scipy/scipy/pull/12323#issuecomment-662561285) by @rgommers:
> Can you doc-deprecate it instead? A real deprecation in the absence of bugs or other major issues seems a bit gratuitous.

I think by now, this could be reconsidered, as having duplicate methods is not ideal either...

**Comment by deadb0d4** [comment]
Hey! Can I work on this issue as my first time here? Could you please provide a good reference PR/code to start with?

**Comment by h-vetinari** [comment]
Hey @deadb0d4, great to hear!

You can take #16258 as an example, or any of the PRs that closed an issue in the section "Old deprecation, warning sharpened for removal in 1.10/1.11" of the deprecation tracker.
