### ISSUE TITLE
DEP: add deprecation warning to `maxiter` kwarg in `_minimize_tnc`

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#16254]
Deprecated in documentation only in https://github.com/scipy/scipy/pull/11526

Since this is happening in the private method `_minimize_tnc` (and the wrapper `fmin_tnc` doesn't seem to use `maxiter` anymore), it might be possible to remove this outright.

CC @AtsushiSakai

**Comment by tupui** [comment]
Actually we cannot do this directly since we can call this private method using `minimize`. See the doc on main: https://scipy.github.io/devdocs/reference/optimize.minimize-tnc.html?highlight=tnc
We need to go through a deprecation cycle with warnings there.

**Comment by tupui** [comment]
Plus I don't get why we did this in the first place if we say in the doc of `minimize` that all methods should accept `maxiter`. 

@andyfaff if the change is correct, maybe we should update the doc on `minimize`.
