### ISSUE TITLE
DEP: remove `maxiter` kwarg in `_minimize_tnc`

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#16269]
Follow-up to #16254 / https://github.com/scipy/scipy/pull/16261

**Comment by AtsushiSakai** [comment]
Let's remove `maxiter` option from the root `minimize` doc based on the [discussion](https://github.com/scipy/scipy/pull/16274#issuecomment-1138459769).
https://github.com/scipy/scipy/blob/cef817269ea1e1a3e6b27024f08e822073f6bd46/scipy/optimize/_minimize.py#L184-L186
