### ISSUE TITLE
BUG: `longintrepr.h` not found. Cannot compile for 3.11

### ISSUE THREAD

**Issue by rishacha** [scipy/scipy#16263]
### Describe your issue.

**Version used** : `Using cached scipy-1.6.1.tar.gz (27.3 MB)`

I've attached the log file and the suspected issue - [scipy-compile.log](https://github.com/scipy/scipy/files/8765273/scipy-compile.log)

### Reproducing Code Example

```python
pip install scipy
Pip version - pip 22.1.1 from /home/rishacha/.local/lib/python3.11/site-packages/pip (python 3.11)
Python version - Python 3.11.0b1
OS - elementaryOS

>>> import sys, numpy; print("Numpy version: ", numpy.__version__,"\nSys version: ", sys.version_info)
Numpy version:  1.22.3 
```
Sys version:  sys.version_info(major=3, minor=11, micro=0, releaselevel='beta', serial=1)
```


### Error message

```shell
2022-05-24T23:43:03,313   scipy/cluster/_vq.c:196:12: fatal error: longintrepr.h: No such file or directory
2022-05-24T23:43:03,313     196 |   #include "longintrepr.h"
2022-05-24T23:43:03,313         |            ^~~~~~~~~~~~~~~
2022-05-24T23:43:03,313   compilation terminated.
```

### SciPy/NumPy/Python version information

>>> import sys, numpy; print("Numpy version: ", numpy.__version__,"\nSys version: ", sys.version_info) Numpy version:  1.22.3  Sys version:  sys.version_info(major=3, minor=11, micro=0, releaselevel='beta', serial=1)

**Comment by tupui** [comment]
Hi @rishacha, I will close this in favour of your duplicate which already have comments.

#16262

**Comment by rishacha** [comment]
Yes, makes sense. I just changed the title. Sorry if it created a duplicate
