### ISSUE TITLE
Documentation for scipy.spatial.transform.Rotation.from_euler

### ISSUE THREAD

**Issue by igrega348** [scipy/scipy#16275]
I believe there is a typo in the documentation at https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.from_euler.html

Description of parameter seq says:
    "Up to 3 characters belonging to the set {‘X’, ‘Y’, ‘Z’} for **_intrinsic_** rotations, or {‘x’, ‘y’, ‘z’} for **_extrinsic_** rotations."
Whereas it should say:
    "Up to 3 characters belonging to the set {‘X’, ‘Y’, ‘Z’} for **_extrinsic_** rotations, or {‘x’, ‘y’, ‘z’} for **_intrinsic_** rotations."

**Comment by rkern** [comment]
The docstring matches the [code](https://github.com/scipy/scipy/blob/main/scipy/spatial/transform/_rotation.pyx#L987-L988). AFAICT, this also follows the [convention used on Wikipedia](https://en.wikipedia.org/wiki/Euler_angles#Conventions_by_intrinsic_rotations), which is likely not universal.

Is there an observation that led you to believe there is an error?

**Comment by igrega348** [comment]
Thanks for the quick reply. The observation which led me to believe that there was an error was a discrepancy when I applied the resulting rotation matrix to a tensor. I mixed up rotating the object with rotating the frame of reference. Sorry for the false alarm and thanks again.
