### ISSUE TITLE
DOC: minor release procedure adjustment

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#16297]
Maybe not worth its own PR until we've accumulated any other corrections, but for `doc/source/dev/core-dev/releasing.rst.inc` we have:

> Then edit ``meson.build`` and ``setup.py`` to get the correct version number (set
``version:`` in the former, and ``ISRELEASED = True`` in the latter) and commit
it with a message like ``REL: set version to <version-number>``.  Don't push
this commit to the SciPy repo yet.

the version numbers and `ISRELEASED` stuff are now in `tools/version_utils.py` instead of `setup.py` it seems

**Comment by marianasalamoni** [comment]
Hi! I am new in Scipy and I would like to solve this issue. I think it's a simple change and I'd like to try, as my first contribution.

**Comment by tylerjereddy** [comment]
@marianasalamoni sure, sounds good--in general, we don't assign most issues so it is open to whomever would like to submit a fix.
