### ISSUE TITLE
BUG: lambertw returns nan's on small values

### ISSUE THREAD

**Issue by cjtosh** [scipy/scipy#16291]
### Describe your issue.

For very small values (i.e. between 1e-323 and 1e-316), scipy.special.lambertw returns nans on the default branch (k=0) with the default tolerance (tol=1e-8).

### Reproducing Code Example

```python
import scipy.special
print(scipy.special.lambertw(1e-316))
```

### Error message

```shell
When the above is run, it outputs the following:

(nan+nanj)
```

### SciPy/NumPy/Python version information

1.8.0 1.21.5 sys.version_info(major=3, minor=9, micro=12, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @cjtosh, thank you for reporting. Isn't this past float precision?

**Comment by WarrenWeckesser** [comment]
A proposed fix: https://github.com/scipy/scipy/pull/17545
