### ISSUE TITLE
DOC: building on Windows uses GCC with Meson, not MSVC

### ISSUE THREAD

**Issue by mattip** [scipy/scipy#16322]
When looking at the meson-generated `build.ninja` on windows, on a machine that is duplicating the CI build, it seems there is no use of msvc only gcc. Is this correct? If so it might be nice to document this in the [meson build faq](https://scipy.github.io/devdocs/dev/contributor/meson.html#meson-frequently-asked-questions). Also I think the build requires the rtools gcc compiler, I have had problems with standard mingw.

Another niggle: `meson build --debug` on windows sets the gcc flags to `"-O2" "-g"`. Is using `-O2` intentional for the debug builds?

**Comment by eli-schwartz** [comment]
> Another niggle: `meson build --debug` on windows sets the gcc flags to `"-O2" "-g"`. Is using `-O2` intentional for the debug builds?

Meson has a "buildtype" option, which can be set to release/debug/debugoptimized/minsize etc. This is described at https://mesonbuild.com/Builtin-options.html#core-options

It will bidirectionally map to the individual options "debug" and "optimization" which are separately toggleable -- one sets -g, the other sets -O. Please check what your current setting is there.

Per the listed table -- debugoptimized maps to `debug=true optimization=2`, and SciPy sets the default buildtype to debugoptimized in the project options.

So, what I think happens is that first the buildtype gets set to debugoptimized, which maps debug to true and optimization to 2, and then you override the individual debug option to true (which it already is, FWIW). What you actually want to do is override the buildtype to debug, which can be done with:

```
meson build/ --buildtype=debug
```

**Comment by mattip** [comment]
Thanks.

> What you actually want to do is override the buildtype to debug ... `meson setup build/ --buildtype=debug`

This should probably be in the developer documentation as well.

**Comment by rgommers** [comment]
> When looking at the meson-generated `build.ninja` on windows, on a machine that is duplicating the CI build, it seems there is no use of msvc only gcc.

Yes, that is correct. Well, more or less - you can use MSVC just fine if you have a matching Fortran compiler - i.e. Intel Fortran. The MSVC + gfortran hack is not available.

**Comment by mckib2** [comment]
> The [windows 10 wiki page](https://github.com/scipy/scipy/wiki/Easy-Windows-10-Build-Scipy-from-source), maintained by @mckib2, will need updating.

This was from a while ago (pre-Pythran) building via venv/pip and can be considered unmaintained as changes with clang/Pythran broke the environment described in that page.  Meson should hopefully be easier to setup.  Best course of action is to delete/archive?

**Comment by rgommers** [comment]
There's no such thing as archiving wiki pages I think, so either deleting or adding a prominent note at the top saying this may be outdated is likely the way to go.

That said, I can see a case for updating it. The main pain points there are things like installing the right compiler and downloading the right OpenBLAS, dealing with PowerShell and Chocolatey. Those are probably not things to include in the contributor docs. I'd probably reference `.github/workflows/windows.yml` for those. The tl;dr is that that remains a pain, and Windows users are best served using WSL unless they want to work on Windows-specific things.
