### ISSUE TITLE
DOC: pydata-sphinx-theme v0.9 defaults to darkmode depending on browser settings

### ISSUE THREAD

**Issue by rossbar** [scipy/scipy#16378]
### Describe your issue.

Just a heads up - with `pydata-sphinx-theme v0.9`, the new dark mode feature is set to "auto", meaning that it follows users' browser settings. For example, in my browser I get darkmode by default - the problem is that the darkmode theme doesn't look particularly great. Here's what I see on the scipy devdocs:

![scipy-darkmode](https://user-images.githubusercontent.com/1268991/172835895-f4706785-97c3-4deb-a498-e6f299b983d2.png)

It might be worth setting the theme to light mode by default instead of "auto" for now - see networkx/networkx#5715

### Reproducing Code Example

```python
n/a
```

### Error message

```shell
n/a
```

### SciPy/NumPy/Python version information

n/a

**Comment by tupui** [comment]
I am working on this right now, thanks @rossbar
