### ISSUE TITLE
BUG: RegularGridInterpolator error message is wrong

### ISSUE THREAD

**Issue by cm7S** [scipy/scipy#16380]
### Describe your issue.

The regularGridInterpolator checks that the data to be interpolated has the same dimensions as the reference data points.
However if that checks fails, the error message reports the wrong dimensions:

In scipy/interpolate/_rgi.py at line 303

```     ndim = len(self.grid)
        xi = _ndim_coords_from_arrays(xi, ndim=ndim)
        if xi.shape[-1] != len(self.grid):
            raise ValueError("The requested sample points xi have dimension "
                             "%d, but this RegularGridInterpolator has "
                             "dimension %d" % (xi.shape[1], ndim))
```

Last line should be 
` "dimension %d" % (xi.shape[-1], ndim))`

Since the check is on dimension -1, and the number of dimensions of the points to be interpolated is indeed xi.shape[-1]

### Reproducing Code Example

```python
import scipy
from scipy.interpolate import RegularGridInterpolator
data=[[[1.]]]
x=[0]
y=[0]
z=[0]
my_interpolating_function = RegularGridInterpolator((x, y, z), data,bounds_error=False)

my_interpolating_function([[[0.1,0.2]]])
```

### Error message

```shell
Traceback (most recent call last):

  File "/tmp/ipykernel_9436/4103262667.py", line 9, in <module>
    my_interpolating_function([[[0.1,0.2]]])

  File "/home/clement/.local/lib/python3.8/site-packages/scipy/interpolate/_interpolate.py", line 2517, in __call__
    raise ValueError("The requested sample points xi have dimension "

ValueError: The requested sample points xi have dimension 1, but this RegularGridInterpolator has dimension 3
```

### SciPy/NumPy/Python version information

1.8.1 1.21.4 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0

**Comment by ev-br** [comment]
Would you be interested in submitting a PR with a fix @cm7S ?

**Comment by cm7S** [comment]
Sure thing!
________________________________
