### ISSUE TITLE
BUG: truncnorm.fit does not fit correctly

### ISSUE THREAD

**Issue by Dradeliomecus** [scipy/scipy#16382]
### Describe your issue.

I'm trying to fit a truncated normal distribution, but the fit just does not work.

I'm generating 1,000,000 samples (which should be enough for this fit) from a truncated normal distribution and try to fit it.
I always get a similar result which is nowhere near the parameters.

I plotted an histogram of the samples, and they look fine.

### Reproducing Code Example

```python
import scipy.stats

for i in range(3):
    samples = scipy.stats.truncnorm.rvs(a=0, b=3, loc=0.4, scale=0.2, size=1_000_000)
    print(scipy.stats.truncnorm.fit(samples))
```

### Error message

```shell
(0.49875287578859007, 1.2652801489244518, 0.00959379451449982, 0.782765177862864)
(0.5022952168052932, 1.2660868048747094, 0.00541401128025297, 0.7855660351927634)
(0.5044827222553034, 1.264749809038968, 0.0018691892856018651, 0.7891866191335009)
```

### SciPy/NumPy/Python version information

1.8.1 1.21.6 sys.version_info(major=3, minor=10, micro=4, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @Dradeliomecus, thank you for reporting.

Optimization is hard. And I am not sure there is anything else to say here. In the next release (1.9) we added `scipy.stats.fit` which gives you more control.

A naïve approach would lead to a correct result:
```python
bounds = [(-1, 1), (-1, 5), (-1, 1), (-1, 1)]
# res = stats.fit(stats.truncnorm, samples, bounds)
#   params: FitParams(a=-0.047307169868569865, b=3.1842295226384567, # loc=0.4091186162575773, scale=0.19385456199849882)
#  success: True
#  message: 'Optimization terminated successfully.'
```

@mdhaber can you confirm?

**Comment by Dradeliomecus** [comment]
But if it was stuck in a local minima, when I give it different samples it shouldn't land on the same answer?

I have also tried giving it one of the 4 parameters as a starting point ; it was a bit better but still off.
I tried giving it 2 of the 4 parameters, and it still was pretty off.

**Comment by tupui** [comment]
> But if it was stuck in a local minima, when I give it different samples it shouldn't land on the same answer?

Oh it can. There is really no guarantee here. By default `scipy.optimize.fmin` is used and this is a local optimiser.

> I have also tried giving it one of the 4 parameters as a starting point ; it was a bit better but still off. I tried giving it 2 of the 4 parameters, and it still was pretty off.

You could try to play with the `optimizer` parameter. This is why we have the new fit function to have easier control.

**Comment by mdhaber** [comment]
Yup, `stats.fit` takes some time, but eventually finds a reasonable fit, even with dumber bounds like `bounds = [(-10, 10), (-10, 10), (-10, 10), (0, 10)]`. 

![image](https://user-images.githubusercontent.com/6570539/172988381-6e33930a-a479-4efd-abc5-1222d857340b.png)

(Note: fitting truncated distributions has other issues - gh-9439 - that I'd like to address as part of gh-15928.)
Unfortunately, we cannot guarantee that the generic `rv_continuous.fit` method can fit any distribution to any provided data from any given parameter guesses. I don't think this is bug so much as the limitations of numerical optimization, so I think we should close this and track the suggestion along with other requests for distribution-specific `fit` enhancements.

**Comment by tupui** [comment]
Thank you for confirming, closing this one then. Thanks again @Dradeliomecus
