### ISSUE TITLE
BUG: SIGSEGV in qhull when array type is wrong

### ISSUE THREAD

**Issue by sylvlecl** [scipy/scipy#16409]
### Describe your issue.

Received a SIGSEGV, when creating a `scipy.spatial.HalfspaceIntersection` with an integer array instead of a float array.

Downgrading scipy to an earlier version (1.6.0 but did not try in-between), fixed the issue:
I got an error message telling me the input array has wrong type.
Adding `dtype=float` indeed solved this usage issue.

Execution environment:
ubuntu 20.04

### Reproducing Code Example

```python
from scipy.spatial import HalfspaceIntersection
import numpy as np

intersection = HalfspaceIntersection(
    halfspaces=np.array([[0, 1, -1],
                         [0, -1, 1],
                         [1, 0, -1],
                         [-1, 0, 1]]),
    interior_point=np.array([0, 0])
)
```

### Error message

```shell
Segmentation fault (core dumped)
```

### SciPy/NumPy/Python version information

1.8.1 1.22.4 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment]
I just tried this with the main development branch (`'1.10.0.dev0+1272.31013c0'`), and I got the segmentation fault.
