### ISSUE TITLE
BUG: scipy.interpolate.NearestNDInterpolator returns different results on different operating systems

### ISSUE THREAD

**Issue by nathanv-bell** [scipy/scipy#16402]
### Describe your issue.

When using `scipy.interpolate.NearestNDInterpolator` with the exact same input data set and requesting the same interpolated value, I sometimes get different values on Windows versus Linux. I've tested this on a Windows 10 machine, an Ubuntu 22.04 VM and Ubuntu 22.04 WSL with repeatable results. Using the attached CSV file ([test.csv](https://github.com/scipy/scipy/files/8899930/test.csv)) and sample code:

Windows:
```bash
win32: 776.9816376092916
```

Ubuntu/WSL:
```bash
linux: 339.51961150764384
```

I tried making the test data set smaller, to the 2 data points of interest for example, `(10, 0)` and `(20,0)` but this made the result the exact same every time, so it seems to have something to do with the size of the data set.

I don't have a Mac to also try it on unfortunately. I've installed scipy from PyPi, not built from source or anything.
It may be related to #11828 but that's just a guess.

### Reproducing Code Example

```python
import sys

import numpy as np
import pandas as pd
import scipy.interpolate

data_file = "test.csv"
points_colnames = ("A", "B")
values_colnames = ("C",)
eval_point = (15, 0)

data_df = pd.read_csv(data_file)
points = [data_df[f"{colname}"] for colname in points_colnames]
values = [data_df[f"{colname}"] for colname in values_colnames]

interp = scipy.interpolate.NearestNDInterpolator(np.rot90(points), np.rot90(values))

point = interp(*eval_point)[0]

print(f"{sys.platform}: {point}")
```

### Error message

```shell
No error message.
```

### SciPy/NumPy/Python version information

1.8.1 1.22.4 sys.version_info(major=3, minor=10, micro=4, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment]
The point (15, 0) has two nearest neighbors at (10, 0) and (20, 0), where the values are 776.9816376092916 and 339.51961150764384, respectively.  So in fact, either answer is correct.  On different platforms or with a reduced data set, the results of the floating point calculations involved in the nearest neighbor calculation might be slightly different, making the choice of the nearest neighbor ambiguous.

**Comment by nathanv-bell** [comment]
Gotcha, I realized this particular case was ambiguous, I just didn't think different results on different platforms was expected behavior.

**Comment by tupui** [comment]
Seems like there is no issue after all. Thank you for reporting @nathanv-bell I will close now.
