### ISSUE TITLE
AWS services provided by NumFOCUS to SciPy

### ISSUE THREAD

**Issue by datapythonista** [scipy/scipy#16410]
I'm helping with NumFOCUS infrastructure, and documenting and cleaning up the services that NumFOCUS currently provides to different stakeholders. For context, around 80% of the infrastructure NumFOCUS was paying for, happened to not be in use anymore.

We've got a service numfocus-scipy (Account Id: 395059269882) in our AWS, that doesn't seem to be useful anymore. I see that there are 3 instances (2 windows and 1 ubuntu) that are stopped and didn't run for a year.

I double checked with the SciPy conference people to see if they know about, but seems this was requested for the SciPy project. Creating this issue for visibility, to make sure nobody is interested in keeping those servers, before I delete them permanently. If they are still useful, it's totally fine to keep them, I just need to know a contact person for them, and information on how they are being used. Thanks!

**Comment by rgommers** [comment]
The one person who I can think of that may have requested them other than me (and it wasn't me) is @mdhaber, since he was interested in benchmarking. Matt, does this ring any bells?

**Comment by mdhaber** [comment]
Yes, those instances can be deleted. They were used when there were donated credits, but I believe those ran out or expired.
Last fall, there was discussion about setting up benchmark servers if NumFOCUS received a new donation of credits, but it sounds like that didn't come through? 
Pinging @V0lantis in case he's still interested.

**Comment by datapythonista** [comment]
We're working on getting more free credits, from AWS, GCP and OVH. But we don't have them now, so NumFOCUS is paying for what's being hosted. These servers are stopped, so the cost is not big, but AWS is still charging us for the storage of the images, it's like $300 a year I think. So, good to know they can be deleted.

We'll try to formalize the procedures for those things in the future. So, it's easier for everyone to know what can be requested, what's being hosted, what can be stopped... We'll be sending information when we're ready, with the usual channels between NumFOCUS and the projects.

Closing this issue, as it's resolved.
