### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by strongboarding** [scipy/scipy#16417]
### Describe your issue.

I wanted to use the ZoomFFT class or the zoom_fft function, but i get an issue : module 'scipy.signal has no attribute ZoomFFT'. I import scipy.signal as signal and have never any issue with the other function from scipy.signal.

### Reproducing Code Example

```python
import scipy.signal as signal
import numpy as np

x = np.linspace(0,1,1000)
z = signal.zoom_fft(x, [0.5,0.7])
```

### Error message

```shell
AttributeError: module 'scipy.signal' has no attribute 'ZoomFFT'
```

### SciPy/NumPy/Python version information

1.7.1 1.20.3 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by ilayn** [comment]
To avoid loading everything all at once, certain items need to be imported explicitly. Have a look at the documentation for the usage for zoom_fft.

This is being improved in the new versions but I'm not sure if this item is included in those efforts.

**Comment by tupui** [comment]
I just checked and with the new version it will work.

**Comment by strongboarding** [comment]
Now that i updated the package, it works. Loading only ZoomFFT wasn't enough without updating. 
Thank you both, have a good day.
