### ISSUE TITLE
BUG: stats.shapiro inplace modification of user array

### ISSUE THREAD

**Issue by josef-pkt** [scipy/scipy#16426]
### Describe your issue.

stats.shapiro

AFAICS: #15777 introduced inplace modification that changes the user data

test failure in statsmodels with dev version of scipy

I don't have dev version of scipy, so cannot confirm

### Reproducing Code Example

```python
-
```

### Error message

```shell
-
```

### SciPy/NumPy/Python version information

SciPy                1.10.0.dev0+0.df3fe4e

**Comment by mdhaber** [comment]
Thanks. gh-16427 fixes it.
