### ISSUE TITLE
ENH: skewnorm should return useful distribution

### ISSUE THREAD

**Issue by 2sn** [scipy/scipy#16437]
### Is your feature request related to a problem? Please describe.

inconsistent results
```python
from scipy.stats import skewnorm, describe
describe(skewnorm.rvs(a=1,size=1000000))
```
output (example) is
```python
DescribeResult(nobs=1000000, minmax=(-3.264534658955493, 4.938913717289125), mean=0.5632787709254797, variance=0.6828342037997541, skewness=0.14341119237384578, kurtosis=0.05894410217278079)
```

### Describe the solution you'd like.

output should be
```python
DescribeResult(nobs=1000000, minmax=(..., ...), mean=0, variance=1, skewness=1, kurtosis=0)
```

### Describe alternatives you've considered.

Whip something up myself.  But this should exist.  If it already exists, it should be made visible to find.

### Additional context (e.g. screenshots, GIFs)

Maybe there is another function that can do this (but current online doc is really hard to navigate).

**Comment by mdhaber** [comment]
It sounds like you are looking for a different parameterization. https://en.m.wikipedia.org/wiki/Skew_normal_distribution suggests that it is not a standard parameterization. It sounds useful, but do you have a reference for it? (e.g. one that expresses the PDF in terms of these parameters?) If it's not something that can be expressed in closed form, you may have to convert between the parameterizations numerically.

**Comment by 2sn** [comment]
shape parameter does not seem to correspond to actual skewness.

**Comment by mdhaber** [comment]
No, it does not seem to in the usual parameterization.

**Comment by 2sn** [comment]
Pearson3 seems to give specified mean, variance, and skewness, but adds non-zero kurtosis.

**Comment by 2sn** [comment]
@mdhaber What I am really after is that a measurement is provided as $x^{+a}_{-b}$ and I want a distribution similar to normal to simulates that, i.e., for $a=b=1$ it should be a normal distribution about $x$.

**Comment by mdhaber** [comment]
Well, here's what I can suggest ATM:

```python3
import numpy as np
from scipy.stats import skewnorm
from scipy.optimize import root

# desired properties
mean = 0
var = 1
skew = 1

def f(x):
    return skewnorm(*x).stats('mvs') - np.array([mean, var, skew])

# guess parameters
a = 1
loc = -1
scale = 1

# required parameters
res = root(f, [a, loc, scale])
a, loc, scale = res.x

from scipy.stats import skewnorm, describe
print(describe(skewnorm.rvs(a=a, loc=loc, scale=scale, size=1000000)))
# DescribeResult(nobs=1000000, minmax=(-1.3236065242849013, 6.82428136377313), mean=0.00014425238396072995, variance=1.0021524044699766, skewness=0.9990140235757836, kurtosis=0.8876457366902275)
```

**Comment by 2sn** [comment]
@mdhaber Thanks, that seems to be a practical way of doing it.

**Comment by 2sn** [comment]
@mdhaber Yes, that would be a useful feature; actually, just the code idea to use root to solve it may be sufficient.  (obviously, if coded in C/Fortran, it would be a lot faster, calls are expensive)

**Comment by mdhaber** [comment]
Sure, but most distributions are implemented in Python. 

Yeah, maybe I'll add it to the documentation somewhere since this has come up before. I'd rather avoid creating a funding for it since it won't always work.

**Comment by mdhaber** [comment]
@2sn I've been working on `skewnorm` for something else, and I decided to override its method of moments fitting implementation. The formulas are useful here, too, so I thought I'd post them. There is probably little practical advantage here compared to the code above; this is just faster and more robust (which is needed for the `fit` method of a distribution).

```python3
# Find `skewnorm` parameters required to achieve desired mean, variance, and 
# skewness. Note that max possible skewness of skewnorm is ~0.9952717 as
# shape parameter approaches infinity.
# See https://en.wikipedia.org/wiki/Skew_normal_distribution

import numpy as np
from scipy.optimize import root_scalar
from scipy import stats

def skew_d(d):  # skewness in terms of delta
    return (4-np.pi)/2 * ((d * np.sqrt(2 / np.pi))**3 
                          / (1 - 2*d**2 / np.pi)**(3/2))

# desired moments
m, v, s = 0.5, 1.5, -0.9  # note that skewness magnitude can't be greater than ~0.995

# corresponding distribution parameters
d = root_scalar(lambda d: skew_d(d) - s, bracket=[-1, 1]).root
a = np.sqrt(d**2 / (1-d**2))*np.sign(s)  # shape parameter
scale = np.sqrt(v / (1 - 2*d**2/np.pi))  # scale
loc = m - scale*d*np.sqrt(2/np.pi)  # location

dist = stats.skewnorm(a, loc=loc, scale=scale)
np.testing.assert_allclose(dist.stats(moments='mvs'), [m, v, s])
```

**Comment by 2sn** [comment]
@mdhaber Thanks!
