### ISSUE TITLE
ENH: scipy.stats.bootstrap() should do BCa for multivariate statistics too

### ISSUE THREAD

**Issue by FlorinAndrei** [scipy/scipy#16433]
### Is your feature request related to a problem? Please describe.

I've seen this several times while looking at datasets. In R I can do BCa correction any time. When I try to do the same analysis with Python and I want to apply the BCa correction, it only works for univariate.

### Describe the solution you'd like.

Would be really nice to have BCa available for all analyses.

### Describe alternatives you've considered.

R-lang - I mean, it works already.

**Comment by mdhaber** [comment]
Ok, i can add it. The reason we didn't is that there is not much literature that we could find about a multi-sample jackknife. It is conceptually simple to generalize, but the algorithm is time-consuming. So we started thinking about using bootstrap within bootstrap... and decided to let it go for the time being.
Without looking at the R code, do you have a reference for doing the jackknife part with multiple samples? (We found one, but it didn't seem like a super reliable reference.)

**Comment by josef-pkt** [comment]
multivariate or multi-sample ?

those are different things (in most applications)

**Comment by FlorinAndrei** [comment]
Let me provide a concrete example to make it clear what I want to do.

[BirdPecks.csv](https://github.com/scipy/scipy/files/8943744/BirdPecks.csv)

This code fails:

```python
import pandas as pd
import numpy as np
from scipy import stats

BirdPecks = pd.read_csv("BirdPecks.csv")
Nboot = 10000

pg1 = BirdPecks[BirdPecks["group"] == 1]["pecks"].to_numpy()
pg2 = BirdPecks[BirdPecks["group"] == 2]["pecks"].to_numpy()

bdist = []
global bdist

def boot_mean(x, y):
    global bdist
    m = np.mean(x) - np.mean(y)
    bdist.append(m)
    return m

bs_out = stats.bootstrap(
    data=(pg1, pg2),
    statistic=boot_mean,
    vectorized=False,
    paired=False,
    confidence_level=0.9,
    n_resamples=Nboot,
    random_state=123,
    method="BCa"
)

print(bdist)
```

**Comment by mdhaber** [comment]
Yup. Looks like you'd also like the bootstrap distribution to be returned, based on `bdist`? What would you like to use it for?

**Comment by mdhaber** [comment]
What R function do you use to do this, BTW? (e.g. If you use `boot`, do you use `strata` to distinguish between the two samples?) 

I looked at the [documentation](https://cran.r-project.org/web/packages/bcaboot/bcaboot.pdf) and corresponding [paper ](https://efron.ckirby.su.domains/papers/2018Automatic-Construction-BCIs.pdf) of Efron and Narasimhan's package `bcaboot`. There are some cool ideas there for extending `bootstrap`, but multi-sample statistics are explicitly not supported:

![image](https://user-images.githubusercontent.com/6570539/174729835-f00ae970-c41d-45e6-82cd-90193fa683dc.png)

For future reference to others who find this issue: I believe that _multivariate_ statistics are already handled: statistics of multivariate samples (i.e. multi-input statistics) are supported with `paired=True`, and vector-valued (multi-output) statistics are supported as of gh-15491. (I can imagine ways in which all this could be generalized - e.g. multiple multivariate samples - but, but let's take it one step at a time.)

**Comment by FlorinAndrei** [comment]
> Looks like you'd also like the bootstrap distribution to be returned, based on bdist? What would you like to use it for?

That's not always needed, of course, but you could run tests on the bootstrap distribution, compare it with known distributions (to what extent does it diverge from those, test a hypothesis, etc), assess central values, etc. It greatly extends the usefulness of the original function, besides the basic test you do with the `statistic` parameter. There are times when just graphing it is useful.

It could be an optional parameter, return the distribution only when needed.

> What R function do you use to do this, BTW?

Data set:

[repair.csv](https://github.com/scipy/scipy/files/8953607/repair.csv)

R code:

```r
rp <- read.csv('repair.csv')
rp$type <- factor(rp$type)

require(boot)
bootMeanDiff <- function(d, i){
  means <- tapply(d[i, 1], d[, 2], mean)
  means[1] - means[2]
}

boot.object <- boot(rp, bootMeanDiff, R = 5000, strata = rp$type)
bca.ci = boot.ci(boot.object, conf=.95, type='bca')$bca[4:5]
print(bca.ci)
```

**Comment by alexscott-ff** [comment]
Just wanted to +1 this request for the exact same use case. Looks like returning the distribution is already merged which is great! FWIW I mostly want it to plot it out to see what the distribution actually looks like. Thanks for your work on this.

**Comment by mdhaber** [comment]
@alexscott-ff gh-16455 would implement the feature. It's just waiting for review.
