### ISSUE TITLE
ENH: Update differential_evolution for its 'polish' parameter

### ISSUE THREAD

**Issue by mrkwjc** [scipy/scipy#16464]
### Is your feature request related to a problem? Please describe.

In differential_evolution function 'polish=True' is set by default. This runs a local optimizer at the end of global optimization. For small problems this is ok, but for bigger problems with a bunch of constraints, this causes the "hang up", i.e. it may take ages to finish the job. That's confusing, I've spent hours discovering what is going on when solving such a big problem.

### Describe the solution you'd like.

The solution is twofold: 1. Set polish=False as default and let the people decide if they are going to use this functionality. 2. Be more informative, i.e. the warning can be written in the docs when describing the 'polish' parameter, and also some message can be sent when this polishing procedure starts its job.

**Comment by tupui** [comment]
Hi @mrkwjc, thank you for reporting. I understand the issue with large problems.

1. We cannot just change the parameters like this as it would change downstream results for everyone. If we would change the value, it would need a deprecation period with some warning when people use default parameters. I don't think we want to do this here as it would generate a lot of noise for downstream packages for little value.
2. We could make this more visible in the documentation. But a warning or print during normal execution is not wanted as normal execution should not print anything.

Would you be interested in making a PR for 2?

**Comment by mrkwjc** [comment]
I'll try with PR to change the docstring. Also: I thought a message like "Polishing with local optimizer" put under 'disp=True' will not hurt anyone, how do you think?

**Comment by tupui** [comment]
That sounds like a good idea.

**Comment by andyfaff** [comment]
I think this is closed by #16479
