### ISSUE TITLE
handle spline interpolation methods in `interpn`

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#16472]
As long as `interpn` is (mostly) a convenience wrapper over RegularGridInterpolator, it may make sense for it to grow support for new `cubic`, `quintic` and `pchip` modes which were added for 1.9.0.

Currently it only supports `nearest` and `linear` modes of RGI, plus `splinef2d` which should probably kept for backwards compatibility.

**Comment by tupui** [comment]
Good point. Looking at the doc we could make a top section with these wrapper: `interp1d`, `interpn` and `griddata` (which could be also extended to take `RBFInterpolator` by the way). (Also not clear if we have such wrapper for splines). It would make it clearer for end users which are looking for an easy on the shelf flexible solution.

**Comment by ev-br** [comment]
FWIW I'd recommend to avoid the wrappers in favor of workhorse routines and classes. But that's a judgement call, we should keep supporting stuff we have. And that's a separate discussion anyway. 

The docs(the tutorial) need to be adjusted indeed. My plan is to structure them in 1D, ND grid, ND unstructured, and of course if you feel like giving it a stab in this or a different structure, I'll gladly review.
