### ISSUE TITLE
BUG: qz not performing as expected

### ISSUE THREAD

**Issue by marcdelabarrera** [scipy/scipy#16488]
### Describe your issue.

I'm testing the `scipy.linalg.qz` function, with complex results. In general it works but sometimes it does not. If I run the example code, `Q@AA@Z.T` should coincide with `A` and `Q@BB@Z.T` should coincide with `B`, but it is not the case. 

I tried the same two matrices in matlab, and I obtain the desired result (accounting for the transposition of Q). In fact I get the same AA, BB, Q and Z matrix, but AA, BB and Q are the conjugate of what they should be. That is:
`Q.conjugate()@AA.conjugate()@Z.T=A`
`Q.conjugate()@BB.conjugate()@Z.T=B`

Is this behavior expected?  

### Reproducing Code Example

```python
import numpy as np
from scipy.linalg import qz
A = np.array([[1,2],[3,4]])
B = np.array([[3,4],[4,4]])
AA, BB, Q, Z = qz(A, B, output='complex')
print(f'Q@AA@Z.T=\n{Q@AA@Z.T}\n')
print(f'A=\n{A}\n')
print(f'Q@BB@Z.T=\n{Q@BB@Z.T}\n')
print(f'B=\n{B}\n')
print('But if we take the conjugate of Q, AA and BB, we obtain the desired result')
print(f'\n{Q.conjugate()@AA.conjugate()@Z.T}\n')
print(f'\n{Q.conjugate()@BB.conjugate()@Z.T}\n')
```

### Error message

```shell
No error, but the identity that should be satisfied is not satisfied.
```

### SciPy/NumPy/Python version information

1.8.1 1.20.3 sys.version_info(major=3, minor=9, micro=13, releaselevel='final', serial=0)

**Comment by ilayn** [comment]
Communicated in https://github.com/Reference-LAPACK/lapack/issues/689
