### ISSUE TITLE
BUG: interp2d - decreasing order of the array defining the data points (x, y) is not kept in interpolant object

### ISSUE THREAD

**Issue by lhoupert** [scipy/scipy#16492]
### Describe your issue.

I have an array of datapoint where dimension y is in decreasing order. I need to order my data array by ascending order for x and y otherwise the interpolation is wrong.

Is it possible to edit interp2 to take this into consideration or maybe through an error message to tell the user that the x and y dimensions need to be sorted? 

### Reproducing Code Example

```python
from scipy import interpolate
import numpy as np

x = [-99, -98, -97]
y = [43.0, 42.0]
var = [[305.9215703790299, 281.5026525257677, 275.8311317544098], [262.392031049527, 321.0926387196282, 257.6484227709075]]
f = interpolate.interp2d(x, y, var)

np.testing.assert_array_equal(var, f(x,y))
```

### Error message

```shell
(env) PS C:\Users\loich\Work\Dev\pyQt\sea_routes> python .\tests\test_interpolation_datapoint.py
Traceback (most recent call last):
  File "C:\Users\loich\Work\Dev\pyQt\sea_routes\tests\test_interpolation_datapoint.py", line 106, in <module>
    np.testing.assert_array_equal(var, f(x,y))
  File "C:\Users\loich\Work\Dev\pyQt\sea_routes\env\lib\site-packages\numpy\testing\_private\utils.py", line 934, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "C:\Users\loich\Work\Dev\pyQt\sea_routes\env\lib\site-packages\numpy\testing\_private\utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

Mismatched elements: 6 / 6 (100%)
Max absolute difference: 43.52953933
Max relative difference: 0.16589505
 x: array([[305.92157 , 281.502653, 275.831132],
       [262.392031, 321.092639, 257.648423]])
 y: array([[262.392031, 321.092639, 257.648423],
       [305.92157 , 281.502653, 275.831132]])
```

### SciPy/NumPy/Python version information

1.6.0 1.22.3 sys.version_info(major=3, minor=9, micro=11, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @lhoupert, thank you for reporting. This is indeed confusing and documentation improvements are always welcomed.

**Comment by lhoupert** [comment]
Happy to do a pull request to update the documentation. I was also thinking that maybe raising an error to let the user know would be useful?

Something like:

```python
class interp2d:
....
    def __init__(self, x, y, z, kind='linear', copy=True, bounds_error=False,
                 fill_value=None):
          if x[-1]<x[1]:
               raise DimensionError('x has to be in increasing order')
          
          if y[-1]<y[1]:
               raise DimensionError('y has to be in increasing order')

``` 

where `DimensionError` is defined as a custom exception? 

```python
class DimensionError(Exception):
    pass

```

What are your thoughts?

**Comment by tupui** [comment]
That sounds good, but not my territory. @ev-br does this look right?

**Comment by lhoupert** [comment]
Doing more investigations on this, I also realized that the interpolation function returns wrong values if the coordinates of the data points to interpolate `xi`  and `yi`  are not in increasing order:

```python
	x0 = [-99, -98, -97]
	y0 = [43.0, 42.0]
	var0 = [[305.9215703790299, 281.5026525257677, 275.8311317544098], [262.392031049527, 321.0926387196282, 257.6484227709075]]
	var = var0
	
	if y0[-1]<y0[0]:
		y = y0[::-1]
		var = var[::-1]
	else:
		y = y0

	f = interpolate.interp2d(x0, y, var)
	np.testing.assert_array_equal(var, f(x0,y))
```

doesn't return an error, but: 

```python
	xi=x0
	yi=y0
	np.testing.assert_array_equal(var0, f(xi,yi))
```

returns:
```
>       np.testing.assert_array_equal(var0, f(xi,yi))
E    AssertionError: 
E    Arrays are not equal
E    
E    Mismatched elements: 6 / 6 (100%)
E    Max absolute difference: 43.52953933
E    Max relative difference: 0.16589505
E     x: array([[305.92157 , 281.502653, 275.831132],
E           [262.392031, 321.092639, 257.648423]])
E     y: array([[262.392031, 321.092639, 257.648423],
E           [305.92157 , 281.502653, 275.831132]])

tests\test_interpolation_datapoint.py:153: AssertionError
```

**Comment by ev-br** [comment]
OK, so here's one more way interp2d is broken. I'd suggest to document it --- the matching PR is good --- and leave it be. A standing recommendation is to try `RegularGridInterpolator` instead of interp2d, we'd be interested in hearing about the experience using RGI!

**Comment by lhoupert** [comment]
Thank you @ev-br  for your msg, I didnt know about `RegularGridInterpolator`.
 I just tried on the same data on the previous example and it seems more robust. The code below doesnt return any error:

```python
	x0 = [-99, -98, -97]
	y0 = [43.0, 42.0]
	var0 = [[305.9215703790299, 281.5026525257677, 275.8311317544098], [262.392031049527, 321.0926387196282, 257.6484227709075]]
	var = var0
	
	if y0[-1]<y0[0]:
		y = y0[::-1]
		var = var[::-1]
	else:
		y = y0

	pts0 = [[j,i] for j in y for i in x0]

	f = interpolate.RegularGridInterpolator((y,x0), var)
	arvar = np.array(var)
	np.testing.assert_array_equal(arvar.reshape(arvar.size), f(pts0))

	xi=x0
	yi=y0
	ptsi = [[j,i] for j in yi for i in xi]
	arvar0 = np.array(var0)
	np.testing.assert_array_equal(arvar0.reshape(arvar0.size), f(ptsi))

```

Two questions:
- [ ] Is it worth mentioning in interp2d doc, that interp2d should not be use if the data point coordinates are not sorted and instead `RegularGridInterpolator`  should be used?
- [ ] Is it worth me adding and additional simple example to RegularGridInterpolator based on my experience?

**Comment by ev-br** [comment]
Yes x2, looking forward for the follow-up PRs

**Comment by ev-br** [comment]
OK, now that interp2d is deprecated in scipy 1.10 (and will thus be removed in a future scipy version), I think we can close this as a wontfix. Thank you @lhoupert, @tupui !
