### ISSUE TITLE
HiGHS does not compile on windows (on conda-forge infra)

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#16495]
Trying to build 1.9.0rc1 in https://github.com/conda-forge/scipy-feedstock/pull/206 (not yet switching to meson which I'm attempting in https://github.com/conda-forge/scipy-feedstock/pull/205), everything but windows builds & passes the test suite.

Windows fails while trying to compile the new-in-1.9 HiGHS submodule. Not sure yet why this appears for us but not (presumably) in CI here. Looks like a C++ issue:
```
[...]
%SRC_DIR%\scipy\_lib\highs\src\simplex\HEkkDual.cpp(1556): warning C4244: 'initializing': conversion from 'double' to 'HighsInt', possible loss of data
%SRC_DIR%\scipy\_lib\highs\src\simplex\HEkkDual.cpp(2606): warning C4244: 'initializing': conversion from 'double' to 'HighsInt', possible loss of data
%SRC_DIR%\scipy\_lib\highs\src\parallel/HighsTask.h(94): error C2338: given task type must be trivially copyable
%SRC_DIR%\scipy\_lib\highs\src\parallel/HighsSplitDeque.h(282): note: see reference to function template instantiation 'void HighsTask::setTaskData<_Ty>(F &&)' being compiled
        with
        [
            _Ty=HEkkDual::iterateTasks::<lambda_51aa44907c8cff9e8cec8b07ee6926c4>,
            F=HEkkDual::iterateTasks::<lambda_51aa44907c8cff9e8cec8b07ee6926c4>
        ]
%SRC_DIR%\scipy\_lib\highs\src\parallel/HighsParallel.h(39): note: see reference to function template instantiation 'void HighsSplitDeque::push<_Ty>(F &&)' being compiled
        with
        [
            _Ty=HEkkDual::iterateTasks::<lambda_51aa44907c8cff9e8cec8b07ee6926c4>,
            F=HEkkDual::iterateTasks::<lambda_51aa44907c8cff9e8cec8b07ee6926c4>
        ]
%SRC_DIR%\scipy\_lib\highs\src\parallel/HighsParallel.h(44): note: see reference to function template instantiation 'void highs::parallel::spawn<_Ty>(HighsSplitDeque *,F &&)' being compiled
        with
        [
            _Ty=HEkkDual::iterateTasks::<lambda_51aa44907c8cff9e8cec8b07ee6926c4>,
            F=HEkkDual::iterateTasks::<lambda_51aa44907c8cff9e8cec8b07ee6926c4>
        ]
%SRC_DIR%\scipy\_lib\highs\src\simplex\HEkkDual.cpp(1331): note: see reference to function template instantiation 'void highs::parallel::spawn<HEkkDual::iterateTasks::<lambda_51aa44907c8cff9e8cec8b07ee6926c4>>(F &&)' being compiled
        with
        [
            F=HEkkDual::iterateTasks::<lambda_51aa44907c8cff9e8cec8b07ee6926c4>
        ]
error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DCMAKE_BUILD_TYPE="Release" -DHiGHSRELEASE -DIPX_ON=ON -DHIGHS_GITHASH="n/a" -DHIGHS_COMPILATION_DATE="2022-06-29" -DHIGHS_VERSION_MAJOR=1 -DHIGHS_VERSION_MINOR=1 -DHIGHS_VERSION_PATCH=1 -DHIGHS_DIR="C:\bld\scipy_1656495183905\work\scipy\_lib\highs" -DCMAKE_BUILD_TYPE="Release" -DHiGHSRELEASE -DIPX_ON=ON -DHIGHS_GITHASH="n/a" -DHIGHS_COMPILATION_DATE="2022-06-29" -DHIGHS_VERSION_MAJOR=1 -DHIGHS_VERSION_MINOR=1 -DHIGHS_VERSION_PATCH=1 -DHIGHS_DIR="C:\bld\scipy_1656495183905\work\scipy\_lib\highs" -UOPENMP -UEXT_PRESOLVE -USCIP_DEV -UHiGHSDEV -UOSI_FOUND -Iscipy\optimize\_highs\src -IC:\bld\scipy_1656495183905\work\scipy\_lib\highs\src -IC:\bld\scipy_1656495183905\work\scipy\_lib\highs\src\util -IC:\bld\scipy_1656495183905\work\scipy\_lib\highs\extern -IC:\bld\scipy_1656495183905\work\scipy\_lib\highs\cython\src -IC:\bld\scipy_1656495183905\work\scipy\_lib\highs\src\lp_data -IC:\bld\scipy_1656495183905\work\scipy\_lib\highs\src\io -IC:\bld\scipy_1656495183905\work\scipy\_lib\highs\src\ipm\ipx\include -IC:\bld\scipy_1656495183905\work\scipy\_lib\highs\src\ipm\ipx\include -IC:\bld\scipy_1656495183905\work\scipy\_lib\highs\src\ipm\basiclu\include -IC:\bld\scipy_1656495183905\_h_env\lib\site-packages\numpy\core\include -Ibuild\src.win-amd64-3.10\numpy\distutils\include -IC:\bld\scipy_1656495183905\_h_env\include -IC:\bld\scipy_1656495183905\_h_env\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt -IC:\bld\scipy_1656495183905\_h_env\Library\include -IC:\bld\scipy_1656495183905\_h_env\Library\include /EHsc /TpC:\bld\scipy_1656495183905\work\scipy\_lib\highs\src\simplex\HEkkDual.cpp /Fobuild\temp.win-amd64-3.10\Release\bld\scipy_1656495183905\work\scipy\_lib\highs\src\simplex\HEkkDual.obj /std:c++14 /Zm1000" failed with exit status 2
```

**Comment by tylerjereddy** [comment]
@h-vetinari I saw the exact same problem trying to build `HEkkDual.obj` in the wheels repo as described here: https://github.com/MacPython/scipy-wheels/pull/166#issuecomment-1146491746

Summary of Windows changes here as well: https://github.com/MacPython/scipy-wheels/pull/166#issuecomment-1153434427

I suspect this may help you find a solution--from a quick look, you may also need to bump the MSVC toolchain like I had to?

**Comment by mdhaber** [comment]
Pinging @mckib2.

**Comment by h-vetinari** [comment]
So the actual only real issue in that trace is
```
%SRC_DIR%\scipy\_lib\highs\src\parallel/HighsTask.h(94): error C2338: given task type must be trivially copyable
```

which comes from a failed static_assert [here](https://github.com/scipy/HiGHS/blob/885c5de95a2b73269b0f885ea27234bb0c29c2a3/src/parallel/HighsTask.h#L94-L95). This function gets used only [once](https://github.com/scipy/HiGHS/blob/885c5de95a2b73269b0f885ea27234bb0c29c2a3/src/parallel/HighsSplitDeque.h#L282) elsewhere in the codebase (side note: GH code search doesn't find it anywhere 🤦). There's too many template shenanigans (with a sprinkling of lambdas & openmp at the [callsite](https://github.com/scipy/HiGHS/blob/885c5de95a2b73269b0f885ea27234bb0c29c2a3/src/simplex/HEkkDual.cpp#L1327-L1331)) going on for me to fully penetrate what's happening, but it seems the compiler is generating suboptimal (non-copyable) types somewhere, and indeed, updating the compiler toolchain solves the problem.

I've been [advocating](https://github.com/conda-forge/conda-forge.github.io/issues/1732) for a while for conda-forge to move onto to VS2019 and its toolchain. I'll try to reopen that discussion.

**Comment by rgommers** [comment]
This is a potential blocker for 1.9.0, pending the conda-forge discussion. @h-vetinari you opened a conda-forge wide discussion, but can the toolchain also be bumped to `vc142` just on `scipy-feedstock`?

**Comment by rgommers** [comment]
Either way we should document that `vc142` is now the minimum version required if we don't fix it up in our `highs` submodule.

**Comment by h-vetinari** [comment]
> you opened a conda-forge wide discussion, but can the toolchain also be bumped to `vc142` just on `scipy-feedstock`?

Yes, I plan to do that if there are no further comments. Scipy is also much less critical from that POV than numpy, because it's used much less (if at all) as a host dependency.

**Comment by rgommers** [comment]
Indeed. There is a small C API that is being exposed, but it's not used much and likely won't have `vc142` vs. `vs141` differences that matter.

**Comment by rgommers** [comment]
@h-vetinari I think we can include the `vc14x` requirements in http://scipy.github.io/devdocs/dev/toolchain.html#c-compilers and the section above it which does mention Visual Studio 2019 but not the actual toolchain version. WDYT? Can I interest you in making that update?

**Comment by h-vetinari** [comment]
> Can I interest you in making that update?

Made an attempt: #16563 :)

**Comment by mckib2** [comment]
A little late to the party, but this appears to have been fixed upstream: https://github.com/ERGO-Code/HiGHS/issues/720

We may be overdue pulling upstream updates

**Comment by h-vetinari** [comment]
Thanks for the link @mckib2 - strictly speaking such an update would mean we'd be able to revert (parts of) #16563, but I think the upstream fix for this is not ideal (basically going back to a more hacky solution to avoid the warning), and the reasons for moving to vc142 should be solid enough IMO. Happy to hear others' thoughts though!

**Comment by rgommers** [comment]
I think we can stay with moving to `vc142`; future regressions are likely unless we add a CI job, and unlike numpy we don't have a strong incentive to continue supporting `vc141`.
