### ISSUE TITLE
BUG: Error in error message for incorrect sample dimension in `interpn`

### ISSUE THREAD

**Issue by j-bowhay** [scipy/scipy#16519]
### Describe your issue.

While debugging #16508 I noticed a potentially incorrect error message in `interpn`.
https://github.com/scipy/scipy/blob/3c59bb7b19d3e8b4bff9087adcae73ba77405d9e/scipy/interpolate/_rgi.py#L602-L605
The check here is `xi.shape[-1] != len(grid)` however the error message prints `(xi.shape[1], len(grid)`.

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

N/A

**Comment by WarrenWeckesser** [comment]
Thanks @j-bowhay.  Will you be able to submit a pull request to fix this?

**Comment by j-bowhay** [comment]
Yes will do
