### ISSUE TITLE
BUG: test failure in pre-release job: `TestFactorized.test_singular_with_umfpack`

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#16523]
### Describe your issue.

(Is there some tool to automatically find these flaky tests by running the suite over and over until it finds them?  Or to let us flag them as false positives ("false negatives"?) within the PR that failed, and it will automatically create an issue from the failure and re-run the tests?  It's really frustrating to push a PR and see failures and have to dig through and find out they're not related to your PR at all.)

### Reproducing Code Example

SciPy test suite as of commit 3c59bb7b

### Error message

https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=19024&view=logs&j=7902a2c1-7b88-5b2d-6408-84b88759c642&t=5471a576-12f4-5533-4de4-506800a17112&l=812

```shell
=================================== FAILURES ===================================
__________________ TestFactorized.test_singular_with_umfpack ___________________
[gw1] linux -- Python 3.9.13 /opt/hostedtoolcache/Python/3.9.13/x64/bin/python
scipy/sparse/linalg/_dsolve/tests/test_linsolve.py:89: in test_singular_with_umfpack
        autoTranspose = True
        indx       = array([], dtype=int64)
        mtx        = <5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Column format>
        rhs        = array([1., 1., 1., 1., 1.])
        self       = <scikits.umfpack.umfpack.UmfpackContext object at 0x7fc894177730>
        sol        = array([0., 0., 0., 0., 0.])
        status     = 1
        sys        = 0
```

https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=19024&view=logs&j=7902a2c1-7b88-5b2d-6408-84b88759c642&t=5471a576-12f4-5533-4de4-506800a17112&l=812

```
=================================== FAILURES ===================================
__________________ TestFactorized.test_singular_with_umfpack ___________________
[gw1] linux -- Python 3.9.13 /opt/hostedtoolcache/Python/3.9.13/x64/bin/python
scipy/sparse/linalg/_dsolve/tests/test_linsolve.py:89: in test_singular_with_umfpack
        A          = <5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Column format>
        b          = array([1., 1., 1., 1., 1.])
        self       = <scipy.sparse.linalg._dsolve.tests.test_linsolve.TestFactorized object at 0x7fc8d3d6b340>
scipy/sparse/linalg/_dsolve/linsolve.py:517: in solve
    return umf.solve(umfpack.UMFPACK_A, A, b, autoTranspose=True)
        A          = <5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Column format>
        b          = array([1., 1., 1., 1., 1.])
        umf        = <scikits.umfpack.umfpack.UmfpackContext object at 0x7fc894177730>
/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/scikits/umfpack/umfpack.py:717: in solve
    econd = 1.0 / self.info[UMFPACK_RCOND]
E   RuntimeWarning: divide by zero encountered in scalar divide
        autoTranspose = True
        indx       = array([], dtype=int64)
        mtx        = <5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Column format>
        rhs        = array([1., 1., 1., 1., 1.])
        self       = <scikits.umfpack.umfpack.UmfpackContext object at 0x7fc894177730>
        sol        = array([0., 0., 0., 0., 0.])
        status     = 1
        sys        = 0
```

### SciPy/NumPy/Python version information

platform linux -- Python 3.9.13, pytest-7.1.2, pluggy-1.0.0

**Comment by rgommers** [comment]
> Is there some tool to automatically find these flaky tests by running the suite over and over until it finds them? Or to let us flag them as false positives ("false negatives"?) within the PR that failed, and it will automatically create an issue from the failure and re-run the tests? 

Good question. We don't have a bot or other method of doing this automatically, someone must manually open an issue and then fix it or add an `xfail`/`skip` marker. I think scikit-learn recently added a bot though, so maybe that's worth copying.

Thanks for opening this issue @endolith!

 > It's really frustrating to push a PR and see failures and have to dig through and find out they're not related to your PR at all.

Yes, agreed. I think at the moment the flaky issue is secondary to breakages that are consistently happening (e.g. due to a change in numpy or another dependency) - but both are equally annoying.

**Comment by rgommers** [comment]
Update: it's not a flaky test, it's consistently failing in that job. I'll fix that up.
