### ISSUE TITLE
BUG: Unexpected wrong results for euclidean distance with 2 points

### ISSUE THREAD

**Issue by cassiasamp** [scipy/scipy#16548]
### Describe your issue.

I tried using Euclidean distance with this two points:  (5, 3), (10,15) 
Since Euclidean distance formula is: $$ed = \sqrt(x2 – x1)^2 + (y2 – y1)^2$$
The result of those two points would be: $$ed = \sqrt(10 – 5)^2 + (15 – 3)^2$$
$$ed = \sqrt(25 + 144)$$
$$ed = \sqrt169$$
$$ed = 13$$

The scipy Euclidean distance function (and also math.distance function) returned: 
```
distance.euclidean((3,5), (10,15))
12.206555615733702
```
Taking a quick look at the source, I believe that might be happening because the Euclidean distance is being calculated as a case of Minkowski distance, which is pre-setted to p=3.

I can fix it by including the Euclidean formula. And perhaps, a similar situation could be happening for Manhattan, it would be interesting to check.

### Reproducing Code Example

```python
from scipy.spatial import distance
distance.euclidean((3,5), (10,15))
# returns 12.206555615733702 instead of 13.0
```

### Error message

```shell
There isnt an error message.
```

### SciPy/NumPy/Python version information

1.8.1 1.22.4 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @cassiasamp, thank you for reporting. You have it wrong I am afraid. With `(5, 3), (10, 15)` you should have `distance.euclidean((5, 3), (10, 15))` instead of `distance.euclidean((3, 5), (10, 15))`.

**Comment by cassiasamp** [comment]
omg! thanks! I hadn't noticed and thought it was a bug. sorry!

**Comment by tupui** [comment]
No worries happens to everyone 😃
