### ISSUE TITLE
Typo in scipy/optimize/tests/test_optimize.py,  logit instead of expit

### ISSUE THREAD

**Issue by kboulif** [scipy/scipy#16580]
Hi, 

I noticed that there is a typo in the test_optimize.py file. The file refer to logit function instead of expit(or sigmoid). 

`def logit(x):
        return 1 / (1 + np.exp(-x))
`

Best regards,

**Comment by tupui** [comment]
Hi @kboulif thank you for reporting. Could you maybe be more precise and explain a bit more why there is an error?

**Comment by kboulif** [comment]
Hi @tupui, 

It is an error in the **naming** of the function. In the file I mentioned above, the function **expit** is named **logit**.
