### ISSUE TITLE
TST: RegularGridInterpolator tests should be parameterised

### ISSUE THREAD

**Issue by Kai-Striega** [scipy/scipy#16582]
### Is your feature request related to a problem? Please describe.

The RegularGridInterpolator [tests](https://github.com/scipy/scipy/blob/main/scipy/interpolate/tests/test_rgi.py) often test multiple conditions inside the same test. This underreports the number and type of test failures. For example, ``test_nearest`` tests multiple different conditions, each of which should be its own test. 

https://github.com/scipy/scipy/blob/633172ca3241ac06d8122e3a3d090ebe8bef84cd/scipy/interpolate/tests/test_rgi.py#L160-L177

### Describe the solution you'd like.

I'd like the tests to be parameterised so that each tested condition is its own test. This issue is for someone to go through the above tests and identify which tests can be parameterised and do it.

### Describe alternatives you've considered.

We could leave it as is.

**Comment by Kai-Striega** [comment]
@jdilanzo maybe you would be interested in this?

**Comment by ev-br** [comment]
Cross-ref gh-16508

**Comment by jdilanzo** [comment]
@Kai-Striega I would be very interested in this. You know I love a good unit test. I'll try to take a look when I'm able.

**Comment by Kai-Striega** [comment]
@j-bowhay I don't have a problem with leaving it for a while. Thanks for Anat working on it :)

**Comment by ev-br** [comment]
How does it look now that gh-16508 is in?

**Comment by j-bowhay** [comment]
I think whilst gh-16508 knocked out quite a bit of this I think there is still work here to be done. For example the original example given by @Kai-Striega has not been addressed

**Comment by Kai-Striega** [comment]
I agree with @j-bowhay; there's still work to be done here. Although the changes in #gh-16508 look excellent.
