### ISSUE TITLE
BUG: stats.mode emits annoying RuntimeWarning about nans even though I set nan_policy='omit'

### ISSUE THREAD

**Issue by dllu** [scipy/scipy#16595]
### Describe your issue.

Often we really don't care about nans, or we are sure that we have already sanitized the input against nans.

However, this annoying warning keeps appearing even though I set `nan_policy='omit'`.

```
RuntimeWarning: The input array could not be properly checked for nan values. nan values will be ignored.
```

This is because of a mandatory call to `_contains_nan` regardless of what `nan_policy` was: https://github.com/scipy/scipy/blob/main/scipy/stats/_stats_py.py#L631

Also, `_contains_nan` is extremely slow and takes up 30 seconds in my code.

![image](https://user-images.githubusercontent.com/14482624/178889320-44a31b6a-89e2-4f5a-bf15-51562118c864.png)

### Reproducing Code Example

```python
import scipy.stats
import numpy as np


my_dtype = np.dtype([('asdf', np.uint8), ('qwer', np.float64, (3,))])
test = np.zeros(10, dtype=my_dtype)
result = scipy.stats.mode(test, nan_policy='omit')
print(result)
```

### Error message

```shell
RuntimeWarning: The input array could not be properly checked for nan values. nan values will be ignored.
```

### SciPy/NumPy/Python version information

1.7.3 1.19.5 sys.version_info(major=3, minor=8, micro=13, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
gh-16423 should speed things up. Are you able to test this branch to see if it helps?

Also, `_contains_nan` is important to check whether your array contains NaNs. The fastest option if you don't have NaNs is `nan_policy='raise'`. Do you know whether you will have NaNs or not?

**Comment by dllu** [comment]
> Last thought: we are deprecating use of stats.mode for non-numeric input in 1.9.0.

I'm a little bit confused by this statement. The example given is a structured numpy array containing only numeric data --- all fields are either `np.uint8` or `np.float64`.

**Comment by mdhaber** [comment]
Oops, let me take a closer look shortly at whether we can continue to be support those.
In the meantime, does `nan_policy='raise'` speed things up for you?

**Comment by dllu** [comment]
![image](https://user-images.githubusercontent.com/14482624/179060549-7e8397fb-17b0-49df-ac84-6fdee2898451.png)

In fact, with `nan_policy='raise'`, it did not speed up at all. In my code, I am calling `stats.mode` about 800,000 times.

**Comment by mdhaber** [comment]
Oops again. Thanks, I understand better now. 
Well, this reinforces the need for a `nan_policy=None`, I think. Then we could skip the call to `_contains_nan` altogether.
