### ISSUE TITLE
BUG: linalg.khatri_rao

### ISSUE THREAD

**Issue by djbacad** [scipy/scipy#16597]
### Describe your issue.

Trying to replicate khatri_rao example from documentation

### Reproducing Code Example

```python
from scipy import linalg
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[3, 4, 5], [6, 7, 8], [2, 3, 9]])
linalg.khatri_rao(a, b)
```

### Error message

```shell
module 'scipy.linalg' has no attribute 'khatri_rao'
```

### SciPy/NumPy/Python version information

1.4.1 1.19.2 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by AtsushiSakai** [comment]
@djbacad Hi. Thank you for reporting. The `khatri_rao` function was introduced from Scipy v1.5.0 in https://github.com/scipy/scipy/pull/11456.
You are using v1.4.1, so If you upgrade Scipy to v1.5.0 or higher, maybe you can use it. Please try it.
