### ISSUE TITLE
ENH, DOC: Add policy on typo and small docs fixes

### ISSUE THREAD

**Issue by melissawm** [scipy/scipy#16603]
### Is your feature request related to a problem? Please describe.

Continuing the discussion from #16578, and summarizing some of the comments:

- It would be ideal to accumulate doc changes rather then send typo fixes one by one if possible, and also try to use the correct commands to skip CI
- The easiest fixes to accept are those where the original version is clearly and unambiguously wrong; changes that require subtle editorial judgement are probably best avoided. (But note that this is not about updating documentation to fix confusing statements or otherwise deal with documentation problems reported by users.)
- One can imagine, however, cases where it is not clear that a "fix" should be made, e.g.:
	- Attempting to "fix" all the uses (or lack thereof) of the [Oxford comma](https://en.wikipedia.org/wiki/Serial_comma).
	- The sentence that I wrote above that begins "A problem with" has an issue (or issues!) that some might be inclined to fix.
	- Cases where the correctness of common usage is evolving, e.g. ["comprised of"](https://www.merriam-webster.com/words-at-play/can-you-use-comprised-of-grammar) (currently only occurring in a few comments in the boost submodule, so not an actual issue in SciPy--phew).
- [NumPy has a bit on this](https://numpy.org/doc/stable/dev/howto-docs.html#contributing-fixes), and we can probably take the opportunity to get similar wording for the policies of both projects

### Describe the solution you'd like.

Write a policy similar the the NumPy one about submitting smaller typo and documentation fixes.

An additional suggestion is to have a specific DOC issue template linking to that policy.

**Comment by tupui** [comment]
Thank you for summarizing the discussion!

**Comment by rgommers** [comment]
The details @WarrenWeckesser added in gh-16578 are quite useful to include. It's fine to say "please do not open PRs for changing the use or non-use of Oxford commas" for example.
