### ISSUE TITLE
BUG: `KDTree`'s optional argument `eps` seems to have no effect

### ISSUE THREAD

**Issue by ghendrickx** [scipy/scipy#16600]
### Describe your issue.

When calling `query_pairs()` or `query_ball_tree()` from the `KDTree`-object, the `eps`-argument seems to have no effect (this might hold for other `query_`-methods as well). This becomes apparent when the distance between nodes of a grid is an irrational number (e.g. `np.sqrt(2)`) and the search radius (i.e. `r`) is as well. Due to rounding errors introduced by working with irrational numbers, the calculated distance might become slightly larger than the radius, which excludes the node(s) from the "connecting". It seems that the `eps`-argument is introduced (partly) because of this, but it is not working; see the MWE below.

### Reproducing Code Example

```python
import numpy as np
from scipy.spatial import KDTree

# create an evenly distributed grid with a spacing of np.sqrt(2)
spacing = np.sqrt(2)
x_range = np.linspace(0, 3 * spacing, 4)
y_range = np.linspace(0, 3 * spacing, 4)
xy_array = [(xi, yi) for xi in x_range for yi in y_range]

# initiate the KDTree
tree = KDTree(xy_array)

# search for the internal combinations of points
# the correct answer is 24 pairs, i.e. `len(pairs) = 24`
pairs = tree.query_pairs(r=spacing)
print(len(pairs))
# result: 16

# using `eps` to overcome the rounding errors
pairs = tree.query_pairs(r=spacing, eps=.1)
print(len(pairs))
# result: 16

# the above should result in the same
pairs = tree.query_pairs(r=1.01 * spacing)
print(len(pairs))
# result: 24
```

### Error message

```shell
-
```

### SciPy/NumPy/Python version information

1.7.3 1.19.4 sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)

**Comment by njj67229** [comment]
Looking into this, eps is indeed unused in a few traversals

**Comment by njj67229** [comment]
So, eps is actually used but it does not end up being correct. Working on finding a fix now, it involves the Minkowski norm, p, and RectRectDistanceTracker within `scipy/spatial/ckdtree/src/rectangle.h`
