### ISSUE TITLE
BUG: `scipy.optimize.linprog` reports optimal for trivially infeasible MILP

### ISSUE THREAD

**Issue by tasseff** [scipy/scipy#16609]
### Describe your issue.

In anticipation of the upcoming 1.9.0 release, I've been trying to update [cvxpy](https://github.com/cvxpy/cvxpy) to use SciPy's newly-introduced MILP functionality. I've been working with SciPy `1.9.0rc2`. You can find [my draft fork of cvxpy here](https://github.com/tasseff/cvxpy) and the associated issue [here](https://github.com/cvxpy/cvxpy/issues/1443). While performing cvxpy unit tests, I came across [a MILP problem](https://github.com/cvxpy/cvxpy/blob/8cc75a8616ac4643134e25147033054d92d89951/cvxpy/tests/test_mip_vars.py#L92-L97) of the form
```
Minimize
 obj: t
Subject To
 c1: y = 0.5
Bounds
 0 <= t
General
 y
End
```
The problem is clearly infeasible, as `y` cannot be both integer (indicated by the `General` entry) and equal to `0.5`. This would be solved using SciPy's new MILP functionality with the script I've added below. Curiously, the solution status is reported as optimal, although it should clearly be reported as infeasible. (It is even acknowledged as infeasible in the rest of the log.) Replacing the `options` flag with `options={'disp': True, 'presolve': False}` provides the expected result, i.e., infeasibility is proven. This suggests the issue may be with the version of HiGHS used by SciPy, and more specifically, its presolve routine.

Indeed, building from [the HiGHS master branch](https://github.com/ERGO-Code/HiGHS) and solving using the above `.lp` problem provides the correct logging output, i.e., the problem is identified as infeasible. A similar issue raised [here](https://github.com/ERGO-Code/HiGHS/issues/902) suggests that this issue may not have been corrected, but another issue [here](https://github.com/ERGO-Code/HiGHS/issues/907) has been closed. Suffice to say, I think this is a trivial enough example where the correct behavior needs to be ensured by both SciPy and HiGHS. You may want to consider updating the version of HiGHS used for the 1.9.0 release or, if that is not enough, (i) providing a fix within HiGHS or (ii) waiting for this fix before releasing SciPy 1.9.0.

### Reproducing Code Example

```python
import numpy as np
import scipy

res = scipy.optimize.linprog(
    c=[1.0, 0.0],
    A_eq=[[0.0, 1.0]],
    b_eq=[[0.5]],
    bounds=[(0.0, None), (None, None)],
    integrality=[0, 1],
    options={'disp': True})
```

### Error message

```shell
Presolving model
0 rows, 0 cols, 0 nonzeros
0 rows, 0 cols, 0 nonzeros
Presolve: Optimal
WARNING: Untransformed solution with objective 0 is violated by 0.5 for the original model

Solving report
  Status            Optimal
  Primal bound      0
  Dual bound        0
  Solution status   infeasible
                    0 (objective)
                    0 (bound viol.)
                    0.5 (int. viol.)
                    0 (row viol.)
  Timing            0.01 (total)
                    0.00 (presolve)
                    0.00 (postsolve)
  Nodes             0
  LP iterations     0 (total)
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)
```

### SciPy/NumPy/Python version information

1.9.0rc2 1.22.3 sys.version_info(major=3, minor=9, micro=12, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
We'll look into this. In the meantime, consider using the new `milp`:

```python3
import numpy as np
from scipy.optimize import milp, Bounds, LinearConstraint

c=[1.0, 0.0]

integrality=[0, 1]

lb = [0, np.inf]
ub = [-np.inf, np.inf]
bounds = Bounds(lb, ub)

A_eq=[[0.0, 1.0]]
b_eq=[0.5]
constraints = LinearConstraint(A_eq, b_eq, b_eq)

res = milp(c, integrality=integrality, bounds=bounds, constraints=constraints)
res
```
```
            fun: None
        message: '(HiGHS Status 2: Model error)'
 mip_dual_bound: None
        mip_gap: None
 mip_node_count: None
         status: 2
        success: False
              x: None
```

**Comment by mdhaber** [comment]
Oops! Same issue with `milp`. I had a mistake above.

**Comment by mdhaber** [comment]
BTW, thanks for finding this @tasseff! We're looking into updating the version of HiGHS. Nicholas mentioned that he has seen those issues reported on the HiGHS repo.

**Comment by mckib2** [comment]
This issue is resolved by pulling in HiGHS updates, see gh-16622
