### ISSUE TITLE
How to install SciPy through dev.py system-wide?

### ISSUE THREAD

**Issue by ilayn** [scipy/scipy#16604]
This is a placeholder for the question probably will come that is currently `dev.py` can 

 - compile and install
 - can skip build and do other things 
 - however it can't just install system-wide. 

That is to say, there is no equivalent of `python setup.py install` in or outside of a venv. 

(or I am just not aware of, please close if so),

**Comment by ilayn** [comment]
By the way `--install-prefix` points to a strange place that we need to point such as before `Lib` so that the resulting `scipy` actually falls into the right place in `site-packages`.

**Comment by tylerjereddy** [comment]
Yeah, I guess I always looked at `dev.py` and `runtests.py` as more in-place type things and tend to switch to i.e., `pip` for the system install a bit later in the dev process if I need to test a big separate script/workflow outside the suite.

**Comment by rgommers** [comment]
Neither `dev.py` nor `runtests.py` installs into any `site-packages`. They're the interface for working on SciPy itself. 

`pip install .` (or `python -m pip install .` as @ev-br said) is the normal tool to use. `python setup.py install` has been not recommended since forever, because it breaks uninstalling and has other random issues. It is deprecated in `setuptools`.

Side note: you can install with `meson install`; so the `meson` CLI is the equivalent of the `setup.py` CLI.

**Comment by rgommers** [comment]
Ha ha, not a wheel/`pip` fan eh:)

**Comment by ilayn** [comment]
Heh, more like an avid follower of the least resisting path :)

**Comment by eli-schwartz** [comment]
Meson generates ninja rules to install: `ninja install` (makes sure that everything is built, then runs `meson install --no-rebuild`)

Meson also generates ninja rules to uninstall: `ninja uninstall` (this runs the internal command `meson --internal uninstall`). 

> `python setup.py install` has been not recommended since forever, because it breaks uninstalling and has other random issues. It is deprecated in `setuptools`.

My perception has always been that the single overriding issue with setup.py install is that it was originally authored in the egg days, so it creates a legacy metadata format, and that rather than fix this, the setuptools authors decided "now is a good time to get out of the business of providing a CLI, because CLIs can be painful and annoying to do well".

Also, it doesn't do dependencies (and badly does build-time dependencies), which is apparently a footgun when setuptools does it, but a matter of reasonable scope when https://github.com/pypa/installer/ does it. :p

Now admittedly, the fact that it uses a legacy metadata format is reasonable grounds to suggest avoiding it. But on the other hand, Meson's CLI doesn't currently install any kind of metadata at all (that's blocked on at least the stable Python 3.11). This doesn't prevent using SciPy in scripts, it just means people doing `pip install thing-that-depends-on-scipy` will try to install scipy again...

**Comment by ev-br** [comment]
Ninja uninstall is great, but at least last time I checked, it did not remove a package cleanly:
https://github.com/ev-br/mc_lib/issues/64#issuecomment-1068417987

(I'm with you Ilhan missing the time when ` python setup.py` was *the* way)

**Comment by ilayn** [comment]
Oh I also forgot the step, *just build and don't install* which was the reason why I typed this issue. That is also missing maybe another keyword `--no-install` ?

**Comment by ilayn** [comment]
Also I don't know if I am using this correctly but have a look at the following behavior

```bash
C:\Users\ilhan\Documents\GitHub\scipy [main ≡]> python dev.py build
💻  meson setup build --prefix build-install
The Meson build system
Version: 0.62.1
Source dir: C:\Users\ilhan\Documents\GitHub\scipy
Build dir: C:\Users\ilhan\Documents\GitHub\scipy\build
Build type: native build

meson.build:1:0: ERROR: prefix value 'build-install' must be an absolute path

A full log can be found at C:\Users\ilhan\Documents\GitHub\scipy\build\meson-logs\meson-log.txt
Meson build setup failed!
```

Am I not using this tool correctly? Apologies for all these noobie questions but I really want to understand the basics properly.

**Comment by ilayn** [comment]
Because it succeeds the second time, probably something necessary was not present in the first run then gets written and things move on later I guess. So probably we are deleting one too many thing or it changes the context second time somehow

**Comment by rgommers** [comment]
> Because it succeeds the second time, probably something necessary was not present in the first run then gets written and things move on later I guess. So probably we are deleting one too many thing or it changes the context second time somehow

I cannot reproduce this. Are you sure this is happening in a clean repo (e.g., `git clean -xdf` followed by `python dev.py build`)? If so, it must be a Windows-specific thing.

**Comment by ilayn** [comment]
Upgrading to meson 63 removed that error. So we can forget about that part.

**Comment by ilayn** [comment]
Just as a summary so far, after the build we can still use `pip install .` machinery to answer the title query but we can't skip the installation step at the end. That is to say, we don't have an option to skip installation with `no-install`

**Comment by ev-br** [comment]
So `$ python dev.py build` then `$ python dev.py shell` does not do what you're after?

**Comment by ilayn** [comment]
`build` still installs or attempts to install. What I meant was that just build and stop. I didn't know `shell` let me check what it does

**Comment by ev-br** [comment]
Well, you can manually do `meson setup --prefix=... ` , `$ meson build` if you want to avoid it copying stuff `... /site-packages` if that's what you're after (which I doubt TBH). In smaller projects without dev.py I do `$ meson install` and set PYTHONPATH env variable. `dev.py shell` is nice in that the last part is not needed with it. But again, I'm probably not understanding your desired workflow.

**Comment by ilayn** [comment]
What I am trying to do is to separate the build and install steps just using `dev.py` no meson exposure for the end user. Adding it to PYTHONPATH is an install thing. In the old workflow terminology, what I want to achieve is `python setup.py build`.

**Comment by ev-br** [comment]
I *think* `python dev.py build` is the closest analog. are there issues with it?

**Comment by ilayn** [comment]
Almost if we can stop this step 

```bash
[snip]
[1550/1550] Linking target scipy/optimize/_highs/_highs_wrapper.cp39-win_amd64.pyd
Build OK
💻  meson install -C build
Installing, see meson-install.log...
Installation OK
```

**Comment by rgommers** [comment]
> Almost if we can stop this step

But why? I cannot think of a valid reason not to always do this.

**Comment by ilayn** [comment]
Why should there be a need for an installation step if say just testing the build or installing it system-wide? The only way now is to break it or wait until it does what it does. Also adjusting the install directory is not that trivial so it is not super useful as is now.

**Comment by ilayn** [comment]
Currently `build` is overloaded with `build and install` so if you want to install but not build then you use `--no-build` (I think). So the command reads `python dev.py build --no-build` which confuses me quite a bit if I am not having these conversations with you folks.

**Comment by rgommers** [comment]
> Why should there be a need for an installation step if say just testing the build or installing it system-wide? The only way now is to break it or wait until it does what it does. Also adjusting the install directory is not that trivial so it is not super useful as is now.

This all does not make much sense to me without a concrete thing that you are trying to achieve. The "build" step here results in a set of sources and extension modules split over multiple directories, it only gets assembled in the install dir. Also note that the build step of `runtests.py` does _exactly_ the same, see `build_project()` there (it calls `python setup.py install <more-args>`).

> The only way now is to break it or wait until it does what it does

This takes only 1-2 seconds for a rebuild, is that what is bothering you?

> Also adjusting the install directory is not that trivial so it is not super useful as is now.

Again something that is not even possible with `runtests.py`, and possible (but not useful for anything I can think of) with `meson configure`.




> so if you want to perform other actions but not build then you use `--no-build` (I think)

There is no such flag anymore (which also fixes a `runtests.py` bug where the version numbering was off with `--no-build` sometimes).

> Moreover, now `build` is marked with wrench but that cannot be since `build` is going to build and install the instance

I think you have a conceptual confusion here. The last step of `dev.py build` is "assemble the individual source files and extensions". Meson happens to call that `install` in the log you see, but really that this happens should _not_ interfere with any development step you may want to do. 

Can you please try to make concrete what development workflow you have is a problem (if any)?

**Comment by ilayn** [comment]
I don't follow why should there be any reason for an install with your same argument. What is the concrete requirement to have an immediate install step? It is not the speed. It is just a moot step if I am testing the build say for C or Fortran code? 

What is your objection to separating this step other than it is as is now? 

> Again something that is not even possible with runtests.py,

`python setup.py build` does not install anything. I can still do some surgery without creating a full installation folder. Again where is this installation requirement coming from? Why did we make it default? It makes no sense to me. 

> There is no such flag anymore

I don't understand. This is my help screen

Can't copy paste because terminal issues 

![image](https://user-images.githubusercontent.com/1303842/180652072-35010f35-7253-40b2-b91b-6bb7c6edbdc2.png)

Am I missing a version issue? 

Ralf, before you object help me understand first. I know this is your baby but usability is important. So flat out objection takes us nowhere. These are choices made by a few and makes no sense to me. it might to you now but I can assure you this is far from usable for now for a generic audience if you want individuals become self-sufficient contributors.

**Comment by eli-schwartz** [comment]
> There is no such flag anymore (which also fixes a `runtests.py` bug where the version numbering was off with `--no-build` sometimes).

Seems to me that it does indeed exist. It's a global flag, not specific to `dev.py build`.

I assume the rationale for `python dev.py --no-build build` (a no-op that just prints "Skipping build") is that it's an accidental side effect of allowing `python dev.py --no-build test` to work for quickly rerunning the tests without rechecking the scipy package validity.

**Comment by rgommers** [comment]
> Seems to me that it does indeed exist. It's a global flag, not specific to `dev.py build`.

Ah good catch, yes. So that solves the problem of the 1-2 sec. step if really desired.

> What is your objection to separating this step other than it is as is now?

You're just asking for extra options in the CLI that are not doing anything useful, with no real rationale.

> I don't understand. This is my help screen

@eli-schwartz explained it, after your comment I was looking at `python dev.py build --help`, which does not have a `--no-build`. 

> `python setup.py build` does not install anything.

I think this is the issue here, you are comparing `dev.py` with `setup.py` - that is not the correct analogy. `dev.py` translates pretty much 1:1 from `runtests.py`. The analogy for `setup.py` is the `meson` CLI.

> Ralf, before you object help me understand first.

Does the analogy right above help? AFAIK `dev.py` is >= `runtests.py`, and `meson xxx` is >= `python setup.py xxx`.

**Comment by ilayn** [comment]
> You're just asking for extra options in the CLI that are not doing anything useful, with no real rationale.

Right back at you Ralf, with that. install is also not useful. I don't understand why you need install one second or one femtosecond. If you have an answer I'd like to hear otherwise this is waste of time. Nevermind then.

**Comment by ilayn** [comment]
I guess that concludes the issue, so the conclusive answer is use 

```
pip install .
```

or 

```
meson instal
```

**Comment by rgommers** [comment]
> Does the analogy right above help? AFAIK `dev.py` is >= `runtests.py`, and `meson xxx` is >= `python setup.py xxx`.

This FAQ expands on this: http://scipy.github.io/devdocs/dev/contributor/meson.html#meson-frequently-asked-questions. We can add more to it if needed - happy to do that if there's a concrete equivalent that you want explained there.

> Right back at you Ralf, with that. install is also not useful.

It is _necessary_ to have `import scipy` work in any subsequent dev step, and completely harmless if you want to do something (which isn't much) which does not require `import scipy`.

**Comment by ilayn** [comment]
If you say so fine with me. On a native workflow it doesn't import and exits with _don't import inside the repo_ message, but whatever if needed let's keep it then. Splitting hair won't solve anything.
