### ISSUE TITLE
runtests.py: ModuleNotFoundError: No module named 'scipy'

### ISSUE THREAD

**Issue by nschloe** [scipy/scipy#16637]
(This is rather a discussion than a bug report.)

When running
```
python runtests.py
```
on a fresh clone, I'm getting
```
Building, see build.log...
Build OK (0:00:05.021195 elapsed)
Trying to import scipy from development installed path at: /path/to/build/testenv/lib/python3.10/dist-packages
Traceback (most recent call last):
  File "/path/to/runtests.py", line 293, in main
    test, version, mod_path = import_module()
  File "/path/to/runtests.py", line 355, in import_module
    __import__(PROJECT_MODULE)
ModuleNotFoundError: No module named 'scipy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/runtests.py", line 611, in <module>
    main(argv=sys.argv[1:])
  File "/path/to/runtests.py", line 306, in main
    test, version, mod_path = import_module()
  File "/path/to/runtests.py", line 355, in import_module
    __import__(PROJECT_MODULE)
ModuleNotFoundError: No module named 'scipy'
```
The directory `/path/to/build/testenv/lib/python3.10/dist-packages` is indeed empty.

Not sure exactly what might be going wrong. Any hint on how to debug?

**Comment by tupui** [comment]
Thanks for reporting @nschloe. Please use instead `python dev.py`. We are going to remove `runtests.py` very soon. Are you missing something in `dev.py`? (in-place builds is coming very soon FYI.)

Which set of instructions did you follow before running this?

**Comment by nschloe** [comment]
Didn't know about `dev.py` which works flawlessly. Thanks for the pointer!

**Comment by nschloe** [comment]
Didn't know about `dev.py` which works flawlessly. Thanks for the pointer!

**Comment by tupui** [comment]
Great thanks for the feedback.
