### ISSUE TITLE
BUG: signal.medfilt no longer works on booleans

### ISSUE THREAD

**Issue by jpauwels** [scipy/scipy#16648]
### Describe your issue.

Applying `signal.medfilt` on a boolean array used to work (not entirely sure of previous version), but no longer does with v1.8.0

### Reproducing Code Example

```python
medfilt(np.array([True, True, False, True, False], dtype=bool), 3) # fails
medfilt(np.array([True, True, False, True, False], dtype=int), 3) # works
```

### Error message

```shell
Input In [9], in <module>
----> 1 medfilt(np.array([True, True, False, True, False], dtype=bool), 3)

File ~/.homebrew/lib/python3.9/site-packages/scipy/signal/_signaltools.py:1538, in medfilt(volume, kernel_size)
   1536 numels = np.prod(kernel_size, axis=0)
   1537 order = numels // 2
-> 1538 return _sigtools._order_filterND(volume, domain, order)

ValueError: order_filterND not available for this type
```

### SciPy/NumPy/Python version information

1.8.0 1.22.2 sys.version_info(major=3, minor=9, micro=12, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @jpauwels, I believe this is intended. See #14327

**Comment by rgommers** [comment]
I'll close this - was intentional indeed. Thanks for the report though @jpauwels.
