### ISSUE TITLE
dtype not preserved with operations on sparse arrays

### ISSUE THREAD

**Issue by gdudziuk** [scipy/scipy#16656]
I'm not 100% sure whether this is a feature or a bug but I can describe what I see as "unexpected output for a valid input". So it seems to be rather a bug.

In brief, multiplication of empty sparse arrays of shape `Nx0` by empty vectors of length `0` seems to always cast the dtype to `float64`. The code to reproduce:

```python
import numpy as np
import scipy as sp
import scipy.sparse as sps

print(f'numpy version: {np.__version__}')
print(f'scipy version: {sp.__version__}')

A = np.array([[0,1,1,1],[1,0,1,0],[0,1,0,1]]).astype('int8')
A = sps.csr_array(A)
x = np.array([1,0,1,1]).astype('int16')

# Partial mask
mask = [False, False, True, True]
result = A[:,mask] @ x[mask] # This gives dtype=int16
print(result.dtype)

# Full mask
mask = [False, False, False, False]
result = A[:,mask] @ x[mask] # This gives dtype=float64
print(result.dtype)
```

My output is:

```
numpy version: 1.23.1
scipy version: 1.8.1
int16
float64
```

This is inconsistent with the results of plain numpy arrays. Comment out the line `A = sps.csr_array(A)` and you get `int16` for both cases in the above snippet.

**Comment by WarrenWeckesser** [comment]
Definitely a bug.  The dtype is changed just by indexing `A` with a mask that is all False:
```
In [10]: import numpy as np

In [11]: from scipy.sparse import csr_matrix

In [12]: A = csr_matrix(np.zeros((3, 2), dtype=np.int32))

In [13]: A[:, [False, False]]  # dtype of result should be int32...
Out[13]: 
<3x0 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>

```

**Comment by gdudziuk** [comment]
Thanks for dealing with this so quickly. I'm staying tuned for the deploy.
