### ISSUE TITLE
BUG: stats: The `expect` method of `vonmises` is broken. 

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#16655]
### Describe your issue.

`vonmises` is a somewhat incomplete and broken implementation of a circular distribution. This shows up in a calculation such as using the `expect` method to compute the integral of the PDF, which should be 1 in the following example:
```
In [12]: vonmises.expect(lambda x: 1, args=(3,))
/home/warren/repos/git/forks/scipy/build-install/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py:2908: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  lbc = integrate.quad(fun, lb, c, **kwds)[0]
/home/warren/repos/git/forks/scipy/build-install/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py:2910: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  dub = integrate.quad(fun, d, ub, **kwds)[0]
Out[12]: 9793.8327480096
```

The support for `vonmises` is [-inf, inf]
```
In [13]: vonmises(3).support()
Out[13]: (-inf, inf)
``` 
and `expect` doesn't "know" that `vonmises` is a circular distribution, so it tries to do the numerical integration on the entire real line.  `vonmises` treats the PDF as periodic, so the result of the integration is meaningless. 

Anyone who has looked into `vonmises` and `vonmises_line` will not be surprised by this--it is known that `vonmises` has issues.  I'm creating this specific issue so I can refer to the problem with `expect` as the reason for one of the failures reported in https://github.com/scipy/scipy/issues/15384.

### SciPy/NumPy/Python version information

1.10.0.dev0+1490.75850dc 1.24.0.dev0+568.g606fa1fb6 sys.version_info(major=3, minor=10, micro=1, releaselevel='final', serial=0)

**Comment by cowden** [comment]
Is the intention here to fix these specific methods for vonmises (e.g. overriding methods), or is the intention to rethink the support for circular distributions (e.g. `rv_circular` class inheriting from `rv_continuous`)?
