### ISSUE TITLE
Regarding standard deviation and covariance matrix

### ISSUE THREAD

**Issue by tanumanghosh** [scipy/scipy#16661]
In Scipy.ODR, I found that standard deviation on the parameter is not same as the sqrt(diag(covariance_matrix)). It is actually sqrt(diag(covariance_matrix*residual_variance)). I think the latter one is the correct definition of standard deviation on parameters. However, the confusion is that when I run ODR with fit_type=OLS, the standard deviation will match with the "curve_fit" tool standard deviation, only when I do sqrt(diag(covariance_matrix)). Why is that so? In standard OLS fit, is the residual_variance not used?

**Comment by rkern** [comment]
`scipy.odr` will directly return whatever ODRPACK provides ([ODRPACK User's Guide, p. 85](https://docs.scipy.org/doc/external/odrpack_guide.pdf)). What's documented is consistent with `sd_beta = sqrt(diag(cov_beta*res_var))`. This is the case for both ODR and OLS fits computed by `scipy.odr`.

To clarify your question, it seems like you are doing OLS with both `scipy.odr` and `curve_fit()`, then comparing the `sd_beta` from `scipy.odr` to `sqrt(diag(pcov))` from `curve_fit()` (`curve_fit()` does not compute the `sd_beta` itself). So your question could be rephrased as why `scipy.odr`'s `cov_beta` not equal `curve_fit()`'s `pcov` when both are doing OLS.

`curve_fit()` and `scipy.odr` have different conventions for the covariance matrices by default. `curve_fit()` can in fact switch conventions depending on whether or not `absolute_sigma=True` is passed to it. By default, `curve_fit()` will return a pre-scaled covariance matrix (i.e. `cf_pcov == odr_cov_beta * odr_res_var`). With `curve_fit(..., absolute_sigma=True)`, it will not pre-scale the covariance matrix (i.e. `cf_pcov == odr_cov_beta`). ODRPACK has a mixed convention, using the unscaled convention for the full covariance matrix while doing the pre-scaling for the standard deviations. I don't know exactly why they chose a mixed convention like this, but reading [their paper on computing the covariance matrix for ODR models](https://docs.scipy.org/doc/external/odr_vcv.pdf), it suggests to me that with the ODR problem, somewhat more skepticism of pre-scaling the covariance matrix is required. The uncertainties in the `x` variables need to be estimated more accurately than in the case of the `y` variables.

**Comment by tanumanghosh** [comment]
Thank you for the explanation. Yes, I understood that curve_fit with absolute_sigma = False, it would give the same result for the standard deviations as script.odr tool. When residual variance (Chi^2/d.o.f in curve_fit) is unity, all the cases will give same result! 

So, to understand, in the scipy.odr tool, the sd_beta gives the 1 sigma confidence (standard deviation) on the parameters, right?

Another query is, at the last, you say that "The uncertainties in the x variables need to be estimated more accurately than in the case of the y variables". What does it mean?

**Comment by tanumanghosh** [comment]
Thank you for recommending the paper. How is it possible to know the "true uncertainty" in real data? How can we compare whether the uncertainty in x is within a factor of 2?

Also, why the "sd_beta" is sometimes called standard error, and sometimes as standard deviation. They have different meanings, right?

**Comment by rkern** [comment]
> How is it possible to know the "true uncertainty" in real data? How can we compare whether the uncertainty in x is within a factor of 2?

You don't. It's a statement about experiments that were done with synthetic data. They observed that the covariance matrix was reasonably reliable when the specified uncertainties in `x` were within a factor of 2 of the true synthetically created noise that they added. And became less reliable when they were outside of that.

> Also, why the "sd_beta" is sometimes called standard error, and sometimes as standard deviation. They have different meanings, right?

Broadly speaking, "standard deviation" can be used to refer to the parameter 𝛔 in any Gaussian distribution (in practice, if not originally). Standard error refers to the standard deviation in the Gaussian distribution of estimates under some estimating procedure over data under some assumed data generating process. In some contexts, (e.g. particularly univariate descriptive statistics), people use "standard deviation" to specifically mean the estimated standard deviation of Gaussian distribution of the assumed data generating process itself (e.g. `np.std(data)`). This is distinct from the "standard error of the mean" in that univariate context, which is the standard deviation of the Gaussian distribution of the _estimated means_.

`sd_beta` is the standard error of the estimated `beta`. It is the standard deviation of the assumed Gaussian distribution of those `beta` estimates. In this context, unlike the univariate descriptive statistics case, there isn't another standard deviation concerning `beta` that claims special status, so there isn't much confusion in calling it a standard deviation. It is the only standard deviation of `beta` that matters.

**Comment by tanumanghosh** [comment]
Hi, I have two power law models, y=ax^m and y=bx^n, where m and n are just constant numbers, a and b are the free parameters in the problem. Can they be considered as similar to the linear model fitting in ODR? 

Also, is there any way to quantify which model is better fit to my data from the residual variance? I mean the one with lower residual variance seems to be better fit, but can I quantify how much better is that model? Is there any tool in scipy for that?

**Comment by rkern** [comment]
Sorry, but we can't really use Github issues as open-ended question threads. But I will answer these last questions here.

1. No, not for ODR. Remember that ODR basically casts itself into an OLS problem by adding a new `delta[i]` parameter for each `x[i]`. So the model is `y[i] = a*(x[i] + delta[i]) ** m`, and that's not linear in the new `delta[i]` parameters.
2. Model comparison (or in my preferred framing, _model criticism_) is a large topic, and tastes differ. You may consider the [Aikake Information Criterion](https://en.wikipedia.org/wiki/Akaike_information_criterion#Comparison_with_least_squares) as a good starting place for quantifying the difference, particularly as you start changing the number of parameters (note that `res_var = RSS / (n-k)` in the parameterization of that article).

**Comment by tanumanghosh** [comment]
OK, I understand. Thank you for the explanation.
