### ISSUE TITLE
BUG: `bool(rotation)` leads to error

### ISSUE THREAD

**Issue by Helveg** [scipy/scipy#16663]
### Describe your issue.

Maybe it's undefined behavior, but calling `bool` on an instance of `scipy.spatial.transform.Rotation` yields an unclear error.

Perhaps any identity rotations could be Falsy, and anything else be truthy? (That's also why I tried `bool` on it)

### Reproducing Code Example

```python
from scipy.spatial.transform import Rotation
bool(Rotation.from_euler("x", 0))
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_rotation.pyx", line 563, in scipy.spatial.transform._rotation.Rotation.__len__
TypeError: Single rotation has no len().
```

### SciPy/NumPy/Python version information

1.8.1 1.22.2 sys.version_info(major=3, minor=9, micro=9, releaselevel='final', serial=0)

**Comment by rkern** [comment]
Apologies for the tag turn; this is in fact a defect.

At least in Python 3.6 and scipy 1.4.1, `bool(some_rotation)` used to unconditionally return `True` without error. Now, it will return `True` in some cases but not others. Did something change in Python's `bool()` semantics since 3.6? Or Cython's code generation?

In any case, if we want to eliminate the `TypeError`, we should define `__bool__()` but unconditionally return `True` regardless of the contents.

**Comment by fabianegli** [comment]
It is not clear to me if and how the boolean transform of a Rotation is useful. If it is indeed not useful, throwing a TypeError with a clear error message from the __bool__ method would be more useful.

Identity rotations could return False to indicate that, but this might be better put into a separate method check. e.g. in the form of `Rotation().yields_identity()` that then would return a boolean. Such an approach will lead to more readable code being written by scipy users.

**Comment by Helveg** [comment]
Most objects in Python are simply truthy. Always returning `True` would be more Pythonic than a TypeError for the attempted conversion.

**Comment by fabianegli** [comment]
@Helveg You are right. https://docs.python.org/3/reference/expressions.html#boolean-operations

**Comment by fabianegli** [comment]
I wonder if `__len__` could return `1` instead of raising the TypeError.

https://github.com/scipy/scipy/blob/c1ce773461be108a703a7e4efd3de0d7c231b591/scipy/spatial/transform/_rotation.pyx#L548-L565

**Comment by fabianegli** [comment]
If __len__ is implemented, __bool__ uses it to asses if it. If it is so that Rotation can't be an instance with zero rotations I think it makes more sense to change the behaviour of __len__ instead of implementing __bool__.

**Comment by fabianegli** [comment]
It seems at least one argument is necessary to instantiate a Rotation

```python
>>> len(Rotation([0.85090352, 0.        , 0.        , 0.52532199]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rotation.pyx", line 562, in scipy.spatial.transform.rotation.Rotation.__len__
TypeError: Single rotation has no len().
>>> len(Rotation([[0.85090352, 0.        , 0.        , 0.52532199], [0.85090352, 0.        , 0.        , 0.52532199]]))
2
```

It is not clear to me why one single rotation should result in a TypeError, when in the case of multiple rotations length is the number of rotations. Wouldn't it be more consistent to make length equal 1 in the case of one rotation?

**Comment by rkern** [comment]
`[0, 0, 0, 1]` is distinct from `[[0, 0, 0, 1]]`.

**Comment by fabianegli** [comment]
Apparently:

```
>>> len(Rotation([[0, 0, 0, 1]]))
1
```

While the Error says "Single rotation has no len().", it is not clear to me why?

**Comment by rkern** [comment]
Basically, `Rotation` has a weird dual life, both as a single quaternion by itself and as the collection of quaternions. Those are distinct, and we have them behave distinctly. Just like `10.0` and `[10.0]` are distinct. `len(10.0)` raises a `TypeError` and does not return `1` even though both are just "single floats".

**Comment by rkern** [comment]
C.f. https://github.com/scipy/scipy/pull/12398 and https://github.com/scipy/scipy/issues/12162

**Comment by fabianegli** [comment]
This dual role is not intuitive for me - that one "bare" rotation is `single` but a single rotation in a list of rotations is not. However, if that is the correct behaviour, a separate `__bool__` method that always returns to `True` is probably the right way to solve this issue.

**Comment by fabianegli** [comment]
The behaviour observed is indeed as intended and I think the additional test is a good addition for the stated reason.

**Comment by Helveg** [comment]
Nice digging on the reasons of the `len` `TypeError`. While it settles len, and might warrant these extra tests to cement them (preferably with links to these issues), it still leaves `bool` up to discussion. Even though for good reasons it turns out you can't check the length of a single rotation, it doesn't seem like there's reason to bar it's truth value as a generic Python object to be consistently assessed.

**Comment by rkern** [comment]
I am of the opinion that `bool()` should not do anything special like being `False` if it is an identity transformation. If you want an interface to express that, it is better, more discoverable API design to have an explicit interface for that (e.g. `rot_object.is_identity()` or something). Not least, since `Rotation` objects can be sequences of rotation transformations, `bool(rot_object)` won't be able to implement any such semantics. `bool()` has to return `True` or `False`, whereas you would want it to return a boolean array being `False` where each element was an identity transformation.

**Comment by Helveg** [comment]
Ah, I missed it, but #16705 already closed this. Sorry for the extra chatter :)
