### ISSUE TITLE
BUG: linprog integrality only accepts list, not array

### ISSUE THREAD

**Issue by bluss** [scipy/scipy#16681]
### Describe your issue.

linprog(integrality=None) is documented as `integrality : 1-D array, optional` but it only accepts listlike and not array due to a conditional in argument checking.

The code uses a plain truthiness check `if integrality` that works well with lists but not ndarrays:

```python
if integrality and not meth == "highs":
```

This causes an exception `ValueError: The truth value of ...` when using linprog integrality with an array.

### Reproducing Code Example

Borrowed and adapted from #11854 thanks :)

```python
from scipy.optimize import linprog
import numpy as np

c = np.array([-29.0, -45.0, 0.0, 0.0])
A_ub = np.array([[1.0, -1.0, -3.0, 0.0],
                 [-2.0, 3.0, 7.0, -3.0]])
b_ub = np.array([[5.0],
                 [-10.0]])
A_eq = np.array([[2.0, 8.0, 1.0, 0.0],
                 [4.0, 4.0, 0.0, 1.0]])
b_eq = np.array([[60.0],
                 [60.0]])
bounds = [(0, None)]
result = linprog(c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds = bounds, integrality=np.ones_like(c))
```

### Error message

```shell
~/.local/lib/python3.8/site-packages/scipy/optimize/_linprog.py in linprog(c, A_ub, b_ub, A_eq, b_eq, bounds, method, callback, options, x0, integrality)
    582         warn(warning_message, OptimizeWarning)
    583 
--> 584     if integrality and not meth == "highs":
    585         integrality = None
    586         warning_message = ("Only `method='highs'` supports integer "

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

### SciPy/NumPy/Python version information

1.9.0rc2 1.22.4 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
Thanks, I'll fix that today.
