### ISSUE TITLE
ENH: P-ARPACK support

### ISSUE THREAD

**Issue by xper0418** [scipy/scipy#16695]
Do you have any plan to support P-ARPACK which is a parallel version of ARPACK?

**Comment by rgommers** [comment]
@xper0418 no. I can't even find a repo, just a paper. Can you please add more details about P-ARPACK if you have them?

**Comment by xper0418** [comment]
@rgommers Thank you for your quick response. 

1. Here's download page.
https://www.caam.rice.edu/software/ARPACK/download.html#P_ARPACK

2. This repo contains PARPACK subroutines
https://github.com/opencollab/arpack-ng

**Comment by rgommers** [comment]
Thanks, that is helpful. 

> https://github.com/opencollab/arpack-ng

Ah, missed that. That is our upstream repo for regular ARPACK. 

> https://www.caam.rice.edu/software/ARPACK/download.html#P_ARPACK

From the README: _The message passing layers currently supported are BLACS and MPI._ So the answer is: no, distributed libraries/functionality like that are out of scope for SciPy.

**Comment by xper0418** [comment]
@rgommers I got it. Thank you and have a nice day.
