### ISSUE TITLE
BUG: Installing nightly wheel from anaconda.org does not install the latest uploaded wheel

### ISSUE THREAD

**Issue by lesteve** [scipy/scipy#16702]
### Describe your issue.

Installing nightly wheel from https://anaconda.org/scipy-wheels-nightly installs a wheel that has been uploaded roughly one month ago, namely this [one](https://anaconda.org/scipy-wheels-nightly/scipy/files?version=1.10.0.dev0%2B0.df3fe4e&page=1).

We spotted that in scikit-learn since we are testing against the nightly wheels of numpy, scipy and pandas.

My guess is that this is because the wheel naming is
`scipy-1.10.0.dev0+0.<something>.whl`
instead of:
`scipy-1.10.0.dev0+<increasing-number>.<something>.whl`

(Note that for OSX wheels the increasing number appears in the wheel filename for some reason ...).

The numpy wheel does follow the convention with the increasing number as you can see from: https://anaconda.org/scipy-wheels-nightly/numpy/files

### Reproducing Code Example

```python
mamba create -n test python -y
conda activate test
dev_anaconda_url=https://pypi.anaconda.org/scipy-wheels-nightly/simple
pip install --pre --extra-index $dev_anaconda_url scipy
```

scipy-1.10.0.dev0+0.df3fe4e (uploaded roughly one month ago see [this](https://anaconda.org/scipy-wheels-nightly/scipy/files?version=1.10.0.dev0%2B0.df3fe4e&page=1)) is installed as you can see from the output:
```
Looking in indexes: https://pypi.org/simple, https://pypi.anaconda.org/scipy-wheels-nightly/simple
Collecting scipy
  Downloading https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/1.10.0.dev0%2B0.df3fe4e/SciPy-1.10.0.dev0%2B0.df3fe4e-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.9/43.9 MB 11.9 MB/s eta 0:00:00
Collecting numpy>=1.19.5
  Downloading https://pypi.anaconda.org/scipy-wheels-nightly/simple/numpy/1.24.0.dev0%2B569.gf1e50253a/numpy-1.24.0.dev0%2B569.gf1e50253a-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.2/17.2 MB 13.6 MB/s eta 0:00:00
Installing collected packages: numpy, scipy
Successfully installed numpy-1.24.0.dev0+569.gf1e50253a scipy-1.10.0.dev0+0.df3fe4e
```

### SciPy/NumPy/Python version information

`1.10.0.dev0+0.df3fe4e 1.24.0.dev0+569.gf1e50253a sys.version_info(major=3, minor=10, micro=5, releaselevel='final', serial=0)`

**Comment by rgommers** [comment]
Thanks for the report @lesteve.

This is the relevant code: https://github.com/scipy/scipy/blob/7ed8128f86dadf9a9a912f0699576dbeadb02638/tools/version_utils.py#L93-L104. Probably something with clone depth, I'll have a look.

**Comment by larsoner** [comment]
Closing for #16709 , but feel free to reopen if it's not fixed

**Comment by rgommers** [comment]
I'll trigger a new build from https://github.com/MacPython/scipy-wheels/pull/172 to see if we're good there.

**Comment by lesteve** [comment]
> I'll trigger a new build from https://github.com/MacPython/scipy-wheels/pull/172 to see if we're good there.

This seems to be working fine: 
https://dev.azure.com/numpy/numpy/_build/results?buildId=25384&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=40afa967-24d1-5e46-a04a-2cd69c6d379f&l=22557
```
Copying scipy.egg-info to build/bdist.linux-x86_64/wheel/scipy-1.10.0.dev0+1555.eecd600-py3.10.egg-info
```

Thanks a lot!

**Comment by rgommers** [comment]
Yep, new nightlies are up on https://anaconda.org/scipy-wheels-nightly/scipy/files
