### ISSUE TITLE
DOC: Dead link in the doc page "Additional Git Resources" 

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#16716]
The `git foundation` link in the sentence "Our own [git foundation](http://matthew-brett.github.com/pydagogue/foundation.html) expands on the [git parable](http://tom.preston-werner.com/2009/05/19/the-git-parable.html)" in https://scipy.github.io/devdocs/dev/gitwash/git_resources.html#additional-git-resources gives a 404 error.

Ping @matthew-brett.

**Comment by tupui** [comment]
We should really check for deadlinks when building the doc.

**Comment by ev-br** [comment]
> We should really check for deadlinks when building the doc.

IIRC we tried running linkcheck, it did smoke out a few problems, but turned out to be too noisy or too strict. There must be a PR somewhere in the backlog

**Comment by melissawm** [comment]
Locally, https://github.com/lycheeverse/lychee is a good option. Not sure if this is the best option in CI though (see https://github.com/lycheeverse/lychee-action)
