### ISSUE TITLE
BUG/DOC: spatial: docstrings of `Rotation` methods are missing the function signature.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#16713]
### Describe your issue.

The docstrings of the methods of `scipy.spatial.transform.Rotation` are missing the function signature in their first line.  See, for example, https://scipy.github.io/devdocs/reference/generated/scipy.spatial.transform.Rotation.from_euler.html, where the page shows `Rotation.from_euler()` as the signature.

These methods are implemented in Cython, so either the signature must be manually added as the first line of the docstring, or the Cython decorator or compiler directive [`embedsignature`](https://cython.readthedocs.io/en/stable/src/userguide/source_files_and_compilation.html?highlight=embedsignature#compiler-directives) should be used.

### SciPy/NumPy/Python version information

1.10.0.dev0+1555.eecd600 1.24.0.dev0+568.g606fa1fb6 sys.version_info(major=3, minor=10, micro=1, releaselevel='final', serial=0)

**Comment by j-bowhay** [comment]
@Quantaforce https://scipy.github.io/devdocs/dev/dev_quickstart.html is a good starting point
