### ISSUE TITLE
BUG: pip install SciPy fails under PyPy

### ISSUE THREAD

**Issue by oscarbenjamin** [scipy/scipy#16737]
### Describe your issue.

I'm seeing this in SymPy CI in https://github.com/sympy/sympy/pull/23859. I don't immediately have a computer on which I can test this with PyPy locally.

Essentially `pip install scipy` has failed under PyPy with:
```
        File "/tmp/pip-build-env-mupbdlja/overlay/lib/pypy3.8/site-packages/mesonpy/_tags.py", line 79, in __init__
          f'Unknown Python implementation: {self.implementation}. '
      NotImplementedError: Unknown Python implementation: pypy38. Please report this to https://github.com/FFY00/mesonpy/issues and include information about the Python distribution you are using.
```

You can see the CI setup for this up to the line that fails here:
https://github.com/sympy/sympy/blob/7754d037d97d56de9e1bcecb81ecadd4a2e683be/.github/workflows/runtests.yml#L170-L208

The logs for the failed SciPy build are here:
https://github.com/sympy/sympy/runs/7583332309?check_suite_focus=true

I have just confirmed that the same CI setup with `scipy!=1.9.0` builds 1.8.1 just fine so it seems to be a problem with the 1.9.0 release.

### Reproducing Code Example

```python
# Run on Ubuntu 20.04 under PyPy 3.8.
# There might be more to it than this.
# See the CI config above.
pip install scipy
```

### Error message

```shell
+ meson install --destdir /tmp/pip-install-pkqrdcy5/scipy_8a1b991ddd494020a114650533cb4ba6/.mesonpy-ve4kjypi/install
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/PyPy/3.8.13/x64/lib/pypy3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-build-env-mupbdlja/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 714, in _calculate_file_abi_tag_heuristic_posix
          return mesonpy._tags.StableABITag(tag)
        File "/tmp/pip-build-env-mupbdlja/overlay/lib/pypy3.8/site-packages/mesonpy/_tags.py", line 39, in __init__
          raise ValueError(f'Invalid PEP 3149 stable ABI tag, expecting pattern `{self._REGEX.pattern}`')
      ValueError: Invalid PEP 3149 stable ABI tag, expecting pattern `^abi(?P<abi_number>[0-9]+)$`
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/PyPy/3.8.13/x64/lib/pypy3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/opt/hostedtoolcache/PyPy/3.8.13/x64/lib/pypy3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/hostedtoolcache/PyPy/3.8.13/x64/lib/pypy3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-mupbdlja/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 927, in build_wheel
          return project.wheel(out).name
        File "/tmp/pip-build-env-mupbdlja/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 875, in wheel
          wheel = _WheelBuilder(self).build(self._install_plan, self._copy_files, self._build_dir)
        File "/tmp/pip-build-env-mupbdlja/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 356, in build
          wheel_file = pathlib.Path(directory, f'{self.name}.whl')
        File "/tmp/pip-build-env-mupbdlja/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 165, in name
          python_tag=self._project.python_tag,
        File "/tmp/pip-build-env-mupbdlja/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 657, in python_tag
          selected_tag = self._select_abi_tag()
        File "/tmp/pip-build-env-mupbdlja/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 779, in _select_abi_tag
          tags = self._files_by_tag()
        File "/tmp/pip-build-env-mupbdlja/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 759, in _files_by_tag
          tag = self._calculate_file_abi_tag_heuristic(file)
        File "/tmp/pip-build-env-mupbdlja/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 723, in _calculate_file_abi_tag_heuristic
          return self._calculate_file_abi_tag_heuristic_posix(filename)
        File "/tmp/pip-build-env-mupbdlja/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 716, in _calculate_file_abi_tag_heuristic_posix
          return mesonpy._tags.LinuxInterpreterTag(tag)
        File "/tmp/pip-build-env-mupbdlja/overlay/lib/pypy3.8/site-packages/mesonpy/_tags.py", line 79, in __init__
          f'Unknown Python implementation: {self.implementation}. '
      NotImplementedError: Unknown Python implementation: pypy38. Please report this to https://github.com/FFY00/mesonpy/issues and include information about the Python distribution you are using.
```

### SciPy/NumPy/Python version information

SciPy 1.9.0, PyPy 3.8

**Comment by rgommers** [comment]
I think this bug should be filed against https://github.com/FFY00/mesonpy, as the message says.

**Comment by rgommers** [comment]
Let's leave this open too though. I believe there are more issues with PyPy, and we don't have any CI for PyPy - but if `pip install scipy` on PyPy worked for you before, we should get things back to that same state for 1.9.x

**Comment by oscarbenjamin** [comment]
> I think this bug should be filed against https://github.com/FFY00/mesonpy, as the message says.

I opened an issue with mesonpy: https://github.com/FFY00/meson-python/issues/121

I think that "can't install scipy under pypy" is a SciPy issue in any case though even if the root cause lies elsewhere.

> I believe there are more issues with PyPy, and we don't have any CI for PyPy

Is PyPy not considered to be "supported" by SciPy? The release notes say "For running on PyPy, PyPy3 6.0+ is required" which suggests that it is supported in which case perhaps some CI or pre-release testing would make sense.

**Comment by rgommers** [comment]
PyPy is at the same status as other Python implementations (Graal, Pyston, etc.) and platforms (AIX, HPC platforms, the niche Debian architectures) for which we have no CI: we accept patches and do our best to be responsive to issues, but without CI that's all we can do. So "tier 3 support" I guess.

We had PyPy in CI for a little while (IIRC ~1.5 years back), but it was too unstable so we removed it again.

**Comment by oscarbenjamin** [comment]
> "tier 3 support" I guess.

Maybe there could be a very low level of platform CI that just tests if you can build, install, import a few things and call a couple of functions. They could just be used on the release branches rather than main so you can see around release time if any platforms are likely affected by the changes since the last release.

The change here seems to be that SciPy is not usable under PyPy at all now if I've understood this correctly. Maybe that's still a valid choice as part of the move to meson but it's one of those things that you'd want to know about and mention in the release notes etc.

> We had PyPy in CI for a little while (IIRC ~1.5 years back), but it was too unstable so we removed it again.

Maybe it's different at the C level. For SymPy which is pure Python PyPy used to show instability and bugs but that has stabilised and it's unusual now to see any PyPy specific bugs or even differences (the only example I can think of right now is https://github.com/sympy/sympy/pull/23321#issuecomment-1166782369).

Recently most instability in SymPy's CI seems to be SciPy-related :)

**Comment by eli-schwartz** [comment]
BTW the bug in question seems to be in the PEP 517 build backend glue, not Meson itself. There's some testing at https://github.com/mattip/scipy/pull/1 but that uses Meson directly and/or dev.py

@mattip has contributed a couple pypy fixes for Meson and helped us set up our CI so that we are testing our "basic python project" CI on pypy as well as cpython. :)

**Comment by rgommers** [comment]
> Maybe it's different at the C level.

Yes, it was mostly related to the `cpyext` layer IIRC.

> The change here seems to be that SciPy is not usable under PyPy at all now if I've understood this correctly. Maybe that's still a valid choice

It's simply a bug, not a deliberate choice. 

> Maybe there could be a very low level of platform CI that just tests if you can build, install, import a few things and call a couple of functions. They could just be used on the release branches

Yes, I think we can add such a job. It should run on `main` too (perhaps not PRs, but at least on merges to `main` so that we catch regressions in time).

**Comment by rgommers** [comment]
There's now also PyPy CI in `meson-python`, including a "scipy-like" package for which wheels are built and checked. The problems here are fixed, so I'll close the issue..

**Comment by oscarbenjamin** [comment]
Good work all!

**Comment by snydej** [comment]
How do I get the fix?

I am trying to install scipy and I am currently getting this error:

`AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'`

This appears to be the same as what was originally reported. I'm using PyPy version 7.3.9 which is the most recent version on https://www.pypy.org/download.html and I just upgraded pip using `pypy3.exe -m pip install --upgrade pip`.

Is there anything else I need to update to install scipy under pypy? It installed just fine under my normal python3 installation.

**Comment by rgommers** [comment]
@snydej can you please open a new issue with the full traceback you are seeing, and Cc me on the issue? 

> AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'

This is a generic message that will be visible for all build failures, the actual problem will be higher up. 

The problem reported in this bug reported (`NotImplementedError: Unknown Python implementation: pypy38`) was fixed. Maybe there's another issue on your system, or with PyPy in general.

**Comment by mattip** [comment]
@snydej: perhaps try the new [7.3.10 release candidates](https://downloads.python.org/pypy/). I think you will have a smoother user experience [using conda](https://www.pypy.org/posts/2022/11/pypy-and-conda-forge.html) with PyPy, since you will get pre-compiled binary packages.

**Comment by ygl-rg** [comment]
> @snydej: perhaps try the new [7.3.10 release candidates](https://downloads.python.org/pypy/). I think you will have a smoother user experience [using conda](https://www.pypy.org/posts/2022/11/pypy-and-conda-forge.html) with PyPy, since you will get pre-compiled binary packages.

Hi mattip

    I have tried to install scipy 1.9.3 via pip with pypy 7.3.10 without success. I still saw "module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'"

   scipy 1.8.1 is fine.

**Comment by entangledloops** [comment]
Is there a known workaround for this? Setting `scipy==1.8.1` didn't help me. I'm trying to install `librosa` which depends on `scipy`.

**Comment by oscarbenjamin** [comment]
Maybe this should be reopened.

After opening this issue I pinned `scipy<1.9.0` in the relevant part of SymPy's CI. I just tried removing that pin but found that SciPy 1.9.3 fails to build under PyPy: https://github.com/sympy/sympy/pull/24393

The build failure log ends with a segfault in boost.npz:
```
[237/1576] Generating scipy/special/_data_boost with a custom command
      FAILED: scipy/special/boost.npz
      /opt/hostedtoolcache/PyPy/3.8.15/x64/bin/python ../../scipy/special/utils/makenpz.py --use-timestamp boost -o scipy/special
      Segmentation fault (core dumped)
      [238/1576] Generating 'scipy/special/_ufuncs.pypy38-pp73-x86_64-linux-gnu.so.p/_ufuncs.c'.
      [239/1576] Generating 'scipy/special/cython_special.pypy38-pp73-x86_64-linux-gnu.so.p/cython_special.c'.
      ninja: build stopped: subcommand failed.
      INFO: autodetecting backend as ninja
      INFO: calculating backend command to run: /tmp/pip-build-env-dtk8i39b/normal/bin/ninja
      + meson setup --prefix=/opt/hostedtoolcache/PyPy/3.8.15/x64 /tmp/pip-install-pzj_psgt/scipy_7357d47d5[480](https://github.com/sympy/sympy/actions/runs/3707780050/jobs/6284631258#step:8:481)420c8ee98ac8970ba85b /tmp/pip-install-pzj_psgt/scipy_7357d47d5480420c8ee98ac8970ba85b/.mesonpy-5x6cfkno/build --native-file=/tmp/pip-install-pzj_psgt/scipy_7357d47d5480420c8ee98ac8970ba85b/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      + meson compile
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/PyPy/3.8.15/x64/lib/pypy3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/PyPy/3.8.15/x64/lib/pypy3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/opt/hostedtoolcache/PyPy/3.8.15/x64/lib/pypy3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/hostedtoolcache/PyPy/3.8.15/x64/lib/pypy3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-dtk8i39b/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 1061, in build_wheel
          return project.wheel(out).name
        File "/tmp/pip-build-env-dtk8i39b/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 920, in wheel
          wheel = self._wheel_builder.build(self._build_dir)
        File "/tmp/pip-build-env-dtk8i39b/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line [502](https://github.com/sympy/sympy/actions/runs/3707780050/jobs/6284631258#step:8:503), in build
          self._project.build()  # ensure project is built
        File "/opt/hostedtoolcache/PyPy/3.8.15/x64/lib/pypy3.8/functools.py", line 566, in wrapper
          result = user_function(*args, **kwds)
        File "/tmp/pip-build-env-dtk8i39b/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 737, in build
          self._meson('compile', *self._meson_args['compile'],)
        File "/tmp/pip-build-env-dtk8i39b/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 657, in _meson
          return self._proc('meson', *args)
        File "/tmp/pip-build-env-dtk8i39b/overlay/lib/pypy3.8/site-packages/mesonpy/__init__.py", line 652, in _proc
          subprocess.check_call(list(args), env=self._env)
        File "/opt/hostedtoolcache/PyPy/3.8.15/x64/lib/pypy3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'compile']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by oscarbenjamin** [comment]
I don't know what causes it but something should really be done about the error message:
```
     AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'
```
Failure should be reported in some other way than AttributeError.

**Comment by eli-schwartz** [comment]
> I don't know what causes it but something should really be done about the error message:

https://github.com/mesonbuild/meson-python/pull/231

**Comment by eli-schwartz** [comment]
Since the underlying error is:
```
/opt/hostedtoolcache/PyPy/3.8.15/x64/bin/python \
    ../../scipy/special/utils/makenpz.py \
    --use-timestamp \
    boost \
    -o scipy/special
```

And this same program is run, more or less, in setup.py, it seems something rather fishy is going on. But since that script does pretty much nothing other than `numpy.loadtxt()` and `numpy.savez_compressed()` it sounds like whatever it is, is probably a numpy bug, not a SciPy one.

**Comment by rgommers** [comment]
> The build failure log ends with a segfault in boost.npz:

That's a segfault of PyPy it looks like.

> Maybe this should be reopened.

We can, but I'm not sure there is much point in doing that (EDIT: I'll reopen, but see below). PyPy isn't very stable, not tested in SciPy CI, and building SciPy from source with PyPy is even worse. As @mattip said above (https://github.com/scipy/scipy/issues/16737#issuecomment-1329338815), the experience with conda-forge may be better - and at least maintainable. Help may be needed there too, but it's tractable.  See https://www.pypy.org/posts/2022/11/pypy-and-conda-forge.html.

Building from source with such a complex and untested stack is just not a great idea. We're happy to take patches, whether this issue is open or not. But just reopening it isn't going to fix anything I'm afraid.

Recommendations for anyone using PyPy:
1. Use conda-forge to install PyPy and the dependencies you need
2. If there's no PyPy package for your platform or it's outdated, go help out to build it at https://github.com/conda-forge/scipy-feedstock
3. If it turns out it needs a patch in either PyPy or SciPy, add it there and then upstream it (no need to wait for a new SciPy or PyPy release!)

**Comment by oscarbenjamin** [comment]
> PyPy isn't very stable, not tested in SciPy CI

We discussed above adding something to SciPy CI.

This issue was closed but did any version of SciPy correctly install? I previously confirmed that 1.9.0 and 1.9.1 did not install and I now confirm that 1.9.3 does not. SciPy 1.8.1 (pre meson) installed fine.

**Comment by eli-schwartz** [comment]
Again, it seems like Meson is a red herring here. The same script is run with setup.py or meson, so it should segfault the same way -- inside numpy.

Does SciPy 1.9.3 build with setup.py when run manually, without pip, but otherwise in the same environment? Alternatively, patch pyproject.toml so pip uses the setup.py backend?

**Comment by oscarbenjamin** [comment]
> Just that it builds, yes (on Linux, easiest case )

That is the part that this issue concerns and also the part that is still not currently working.

> it seems like Meson is a red herring here.

Possibly. We are talking about build failures dating back to a release that involves a major change of build system though. It's possible that a change in numpy or something else is related to this but I think it would be quite naive to rule out anything related to the change of build system before the cause is understood. As I understood it there was an a priori expectation that some problems of this kind would emerge after making the change so it shouldn't be a surprise that when such problems arise the change of build system is considered as a potential cause. Of course that doesn't mean that the *bug* is in Meson itself but the general change in SciPy's build system should not be overlooked.

A final point: SymPy has no particular interest in this particular PyPy+SciPy combination but it just happens to be tested in CI. On the assumption that SciPy folks do want SciPy to be installable under PyPy I am taking the time to feed these issues back. If this particular setup is considered to be unsupported by SciPy then I'll make sure that SymPy does not test it any more and I won't open issues along the lines of this one.

**Comment by eli-schwartz** [comment]
Sure, but that's why my own suggestion (at least as a drive-by contributor) was just "to try to factor out the build system as a potential cause, it would be good to check if the issue reproduces when using setup.py".

I'm not suggesting to ignore the issue, merely to run more tests.

**Comment by oscarbenjamin** [comment]
> I'm not suggesting to ignore the issue, merely to run more tests.

I understand but it's not hard for anyone else to reproduce this setup and run whatever tests. Just remove the pin here (probably a much simpler config will reproduce this):
https://github.com/sympy/sympy/blob/4801871259a1a8db27bae99f5ea4db109bb1320a/.github/workflows/runtests.yml#L197-L201

Personally I have other things I need to spend time on. As I said above this setup is not needed by SymPy: I am just reporting what I observe in case it is of interest.

**Comment by mattip** [comment]
See https://foss.heptapod.net/pypy/pypy/-/issues/3870. This was fixed on PyPy HEAD.

**Comment by mattip** [comment]
The root cause is that the code calls `Py_UNICODE_ISSPACE(0xffffffff)`, when `sys.maxunicode` is 0x10ffff

**Comment by rgommers** [comment]
Thanks @mattip!

> A final point: SymPy has no particular interest in this particular PyPy+SciPy combination but it just happens to be tested in CI. On the assumption that SciPy folks do want SciPy to be installable under PyPy

We do want SciPy to work with PyPy, and with as many possible platform/interpreter configs as possible. That said, I would not recommend any project to build SciPy from source on every run in their regular CI, not for any platform or interpreter. It's going to be time-consuming in CI, and will see the same kind of instability as we see in our own CI.

**Comment by oscarbenjamin** [comment]
> That said, I would not recommend any project to build SciPy from source on every run in their regular CI, not for any platform or interpreter.

Okay, well I'll keep it there for now until we can see that this is fixed but then I'll remove it.

**Comment by mattip** [comment]
Maybe at some point SciPy will release wheels for PyPy which would make testing downstream projects like sympy simpler.

**Comment by oscarbenjamin** [comment]
In SymPy's case in particular I doubt that testing this setup does much besides detecting upstream bugs. You can question the value of that but apparently it picks up things that are not tested in upstream CI e.g. because SciPy CI doesn't have anything checking the PyPy build itself.

**Comment by oscarbenjamin** [comment]
I can confirm that with the latest release of PyPy (7.3.11) this is now fixed as tested in this PR: https://github.com/sympy/sympy/pull/24393.

**Comment by ygl-rg** [comment]
Today I installed scipy & scikit-learn successfully with pypy 7.3.11

 Thanks.

**Comment by karkir0003** [comment]
getting this error when running in ubuntu-latest in github action

```
× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      The Meson build system
      Version: 0.62.2
      Source dir: /tmp/pip-install-ll2hfubu/scipy_2c9b53b7e8054244987219dc55724edb
      Build dir: /tmp/pip-install-ll2hfubu/scipy_2c9b53b7e8054244987219dc55724edb/.mesonpy-n6mu_qg8/build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.0
      C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
      C linker for the host machine: cc ld.bfd 2.35.2
      C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")
      C++ linker for the host machine: c++ ld.bfd 2.35.2
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Library m found: YES
```

**Comment by eli-schwartz** [comment]
This doesn't tell us much -- it seems like the second half of the build logs was accidentally omitted from your report, including the half with the error in it.

**Comment by karkir0003** [comment]
So I got this error message from running in github actions using `scipy == 1.7.3` in `requirements.txt` @eli-schwartz

**Comment by karkir0003** [comment]
The github action environment was `ubuntu-latest` and it is an x86 based architecture

**Comment by andyfaff** [comment]
If it was a github actions run, can you give a link to the log?

**Comment by karkir0003** [comment]
https://github.com/DSGT-DLP/Deep-Learning-Playground/actions/runs/4299741691/jobs/7495260827

**Comment by karkir0003** [comment]
@andyfaff

**Comment by andyfaff** [comment]
@karkir0003 you missed the important bits of the build log out. You need to have a fortran compiler installed to build scipy.

```
× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      The Meson build system
      Version: 0.62.2
      Source dir: /tmp/pip-install-ll2hfubu/scipy_2c9b53b7e8054244987219dc55724edb
      Build dir: /tmp/pip-install-ll2hfubu/scipy_2c9b53b7e8054244987219dc55724edb/.mesonpy-n6mu_qg8/build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.0
      C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
      C linker for the host machine: cc ld.bfd 2.35.2
      C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")
      C++ linker for the host machine: c++ ld.bfd 2.35.2
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Library m found: YES
      
      ../../meson.build:41:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['g95']]
      The following exception(s) were encountered:
      Running "gfortran --version" gave "[Errno 2] No such file or directory: 'gfortran'"
      Running "gfortran -V" gave "[Errno 2] No such file or directory: 'gfortran'"
      Running "flang --version" gave "[Errno 2] No such file or directory: 'flang'"
      Running "flang -V" gave "[Errno 2] No such file or directory: 'flang'"
      Running "nvfortran --version" gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running "nvfortran -V" gave "[Errno 2] No such file or directory: 'nvfortran'"
      Running "pgfortran --version" gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running "pgfortran -V" gave "[Errno 2] No such file or directory: 'pgfortran'"
      Running "ifort --version" gave "[Errno 2] No such file or directory: 'ifort'"
      Running "ifort -V" gave "[Errno 2] No such file or directory: 'ifort'"
      Running "g95 --version" gave "[Errno 2] No such file or directory: 'g95'"
      Running "g95 -V" gave "[Errno 2] No such file or directory: 'g95'"
```

**Comment by karkir0003** [comment]
so is there a command I can run to install fortran compiler from within a docker image? @andyfaff

**Comment by eli-schwartz** [comment]
Apt install gfortran?

**Comment by karkir0003** [comment]
ok. Giving that a shot. For reference, I was using this base docker image: `FROM nikolaik/python-nodejs:latest`

**Comment by andyfaff** [comment]
Compiling scipy for CPython on Ubuntu is quite straightforward. However, PyPy is not currently actively tested/built/used by many of the scipy team, so it's not clear how you'll get on.

**Comment by eli-schwartz** [comment]
Fortunately, @karkir0003 appears to be using CPython, unlike the topic of this bug report.

**Comment by karkir0003** [comment]
@eli-schwartz Got this issue resolved. I changed the base docker image to a different version and it worked. I think that the base docker image used in the github action was 3.11, but scipy 1.7.3 didn't seem to be compatible with those settings, so I adjusted accordingly

**Comment by andyfaff** [comment]
@karkir0003 I'm general it's a bad idea to piggyback on another issue because it muddies the original conversation, and it confuses those trying to help. Advice on building would be better asked via the slack channel or the scipy-dev mailing list.

**Comment by oscarbenjamin** [comment]
As far as I can tell this issue is fixed so I'm going to close this. Please let me know if I've overlooked something.

**Comment by oscarbenjamin** [comment]
I noted above that it was fixed: https://github.com/scipy/scipy/issues/16737#issuecomment-1369250812

**Comment by oscarbenjamin** [comment]
Also thanks to all from SciPy and PyPy for fixing!
