### ISSUE TITLE
scipy.optimize import error

### ISSUE THREAD

**Issue by aevdzande** [scipy/scipy#16744]
I just updated my arch linux system and i know have installed :
Python 3.10.5
numpy-1.23.1-1 
scipy-1.9.0-1

now 

import scipy.optimize

generates an error

module compiled against API version 0x10 but this version of numpy is 0xf

end of the traceback:

/usr/lib/python3.10/site-packages/scipy/sparse/_csr.py in <module>
--->from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,get_csr_submatrix)
ImportError: numpy.core.multiarray failed to import

**Comment by tupui** [comment]
Hi @aevdzande thank you for reporting. Does SciPy 1.8.1 works for you? Did you install via PyPi, build yourself or used conda?

**Comment by rgommers** [comment]
NumPy API versions:
```
# Version 15 (NumPy 1.22)
# Configurable memory allocations
0x0000000f = b8783365b873681cd204be50cdfb448d

# Version 16 (NumPy 1.23)
# NonNull attributes removed from numpy_api.py
# Version 16 (NumPy 1.24) No change.
0x00000010 = 04a7bf1e65350926a0e528798da263c0
```

So this error indicates that your installed `scipy` was built against `numpy` 1.23 but you are picking up 1.22 at runtime. You probably haved mixed up two numpy installs there, maybe one with `pacman` and one with `pip`. Cleaning that up will fix your problem.
