### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by nipnipj** [scipy/scipy#16746]
### Describe your issue.

Error when importing `sklearn.mixture`

### Reproducing Code Example

```python
`import sklearn.mixture`
```

### Error message

```
Error in py_module_import(module, convert = convert): ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /root/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/scipy/optimize/_highs/_highs_wrapper.cpython-38-x86_64-linux-gnu.so)

Traceback:

1. import("sklearn.mixture")
2. py_module_import(module, convert = convert)
```

### SciPy/NumPy/Python version information

1.7.3 1.21.6 sys.version_info(major=3, minor=7, micro=12, releaselevel='final', serial=0)

**Comment by rkern** [comment]
Looks like a problem with the `r-miniconda` build of `scipy`. For some reason you are getting a binary that links to the external system library `libstdc++` that is not the right version for your OS. You might be using a Linux version that is not supported by `r-miniconda`.

I don't think there is anything we can do on this side. This is not a bug in `scipy` that we can fix, just a mismatch between your OS and what is supported by the vendor of the binary that you installed.
