### ISSUE TITLE
BUG: Memory leak with sparse.linalg.svds

### ISSUE THREAD

**Issue by francois-rozet** [scipy/scipy#16745]
### Describe your issue.

`scipy.sparse.linalg.svds` has (large) memory leaks. After calling `svds` on an array, deleting the array does not free its memory anymore. Additional memory is also used but never freed.

It looks like the memory is still referenced somewhere the garbage collector is unaware of.

### Reproducing Code Example

```python
>>> import numpy as np
>>> import scipy.sparse.linalg as ssl
>>> import psutil
>>>
>>> A = np.random.rand(2**16, 2**10)
>>> psutil.Process().memory_info().rss
590266368
>>>
>>> U, S, Vh = ssl.svds(A, k=16)
>>> psutil.Process().memory_info().rss
781103104
>>>
>>> del A, U, S, Vh
>>> psutil.Process().memory_info().rss
756367360
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

1.9.0 1.22.3 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @francois-rozet thank you for reporting. The memory management is trickier than that in Python. The garbage collection process happens in cycle and calling `del` does not mean that the memory is going to be freed right away. You can try to force the garbage collection to happen, but it's also not guarantee from what I understand.

**Comment by tupui** [comment]
Using `gc.collect()` right after the `del` call I can see on my side that the memory is back to a somehow previous state. I will close this for now as I don't think there is a problem here.

**Comment by francois-rozet** [comment]
Hello @tupui, thank your for the quick response. I thought the objects would be delete right away with `del`. Calling `gc.collect()` solves the problem as well for me!
