### ISSUE TITLE
None of the `cython_*` APIs have any tests using Cython

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#16748]
There are Python-level tests, e.g. `scipy/linalg/tests/test_cython_blas.py`. However, no tests failed when some `.pxd` files went missing in the Meson build. We need some basic tests that `cimport` some functionality and invoke Cython in a subprocess. Submodules that need testing:

- [ ] `linalg.cython_blas`
- [ ] `linalg.cython_lapack`
- [ ] `optimize.cython_optimize`
- [ ] `special.cython_special`

Test infrastructure can be stolen from https://github.com/numpy/numpy/blob/main/numpy/random/tests/test_extending.py

**Comment by rgommers** [comment]
The docs could also use some usage examples. scipy.github.io/devdocs/reference/special.cython_special.html#module-scipy.special.cython_special is pretty bare-bones. Same for `cython_blas` and `cython_lapack`. They should also reference [this paper on the topic](https://conference.scipy.org/proceedings/scipy2015/pdfs/ian_henriksen.pdf).

Just in case it's helpful, we have one nice bit of user guide content: http://scipy.github.io/devdocs/tutorial/ndimage.html#extending-scipy-ndimage-in-c. Something similar for `cython_*` would be great.

**Comment by Kai-Striega** [comment]
I'm happy to work on this once I'm done with the RGI stuff. It might require a bit of learning on my part (which is a plus!).

**Comment by Kai-Striega** [comment]
@rgommers I understand why we should test this  - and I agree we should test it -  I'm just not sure about the how. I've looked at the NumPy code, and I'm not sure that I follow it as well as I should. Are we just testing one function from the module (i.e. can we import it)?

**Comment by rgommers** [comment]
I'd say yes, that is enough for now, one or two functions per cython module. The tests I linked in the PR description builds an extension with cython (https://github.com/numpy/numpy/tree/main/numpy/random/_examples/cython), and then not only imports it but uses the API. If that works for one function in a module, it's quite likely that it works for all of them. So while complete coverage would be nice, that's a large task that's best left until we see a need.

**Comment by Kai-Striega** [comment]
Ok great, I'll get to it over the Christmas break

**Comment by rgommers** [comment]
In gh-188997 there are comments around `cython_optimize`; the example we have in the docs can serve as a regression test.

One addition: we should be testing with a different version of Cython that we use to build. That is more likely to smoke out issues due to changes in `.pxd` files.
