### ISSUE TITLE
BUG: DOC: editing docstring example in svds

### ISSUE THREAD

**Issue by lobpcg** [scipy/scipy#16741]
### Is your feature request related to a problem? Please describe.

Changed this issue to BUG, since coincidently every PR now fails on exactly this docstring example in refguide_asv_check , e.g., see https://github.com/scipy/scipy/pull/14563#issuecomment-1200290619

The only docstring example in svds is a bit strange. It's essentially a dense problem forced into sparse by using the sparse format of singular vectors although in practical applications the singular vectors are typically dense - only the matrix may be sparse.  

The second issue that the example computes the accuracy of individual vectors, which only makes sense in the absence of clustered singular values.

### Describe the solution you'd like.

Turn the existing example into dense, e.g.,
```
import numpy as np
from scipy.stats import ortho_group
from scipy.sparse.linalg import svds
rng = np.random.default_rng()
orthogonal = ortho_group.rvs(10, random_state=rng)
s = [0.0001, 0.001, 3, 4, 5]  # singular values
u = orthogonal[:, :5]          # left singular vectors
vT = orthogonal[:, 5:].T      # right singular vectors
A = u @ diags(s) @ vT 

u5, s5, vT5 = svds(A, k=5)
A5 = u5 @ np.diag(s5) @ vT5
np.allclose(A5, A.toarray())
np.allclose(s5, s)
np.allclose(np.abs(u5), np.abs(u))
np.allclose(np.abs(vT5), np.abs(vT))
```

And a new example with clustered singular vectors and use something like 
```
from scipy.linalg import subspace_angles
subspace_angles(u5[:, :2], u[:, :2])
subspace_angles(vT5[:2, :], vT[:2, :])
```
to check their accuracy

Add yet another truly sparse example that resembles a practical scenario.

**Comment by lobpcg** [comment]
Changed this issue to BUG, since coincidently every PR now fails on exactly this docstring example in refguide_asv_check ...

**Comment by ev-br** [comment]
At a minimum, this seems to need an explicit atol/rtol.

**Comment by lobpcg** [comment]
> At a minimum, this seems to need an explicit atol/rtol.

@ev-br Already fixed in https://github.com/scipy/scipy/pull/16712 by changing the singular values to be further apart making the example less challenging for inexact computations. Please feel free to have a look and review

**Comment by tylerjereddy** [comment]
I merged the matching PR which claimed to close this I think.

**Comment by rgommers** [comment]
I just came here to say the same - let's close this, it can always be reopened if there are some loose ends.
