### ISSUE TITLE
BUG: `stats.fit` on `boltzmann` expects `bound` for `lambda`, not `lambda_`

### ISSUE THREAD

**Issue by davidgilbertson** [scipy/scipy#16751]
### Describe your issue.

For the `stats.fit` function, the expected values of the `bounds` parameter should be the accepted parameters of the provided distribution. But for `stats.boltzmann`, the parameter name is `lambda_` but `bounds` expects `lambda`.

### Reproducing Code Example
I'm playing with the excellent new goodies in 1.9. Here I'm trying to fit a Botlzmann distribution to some data. Note that for `bounds`, I'm using the parameter names that I would usually pass, e.g `stats.boltzmann(lambda_=0.3, N=10)`.

```python
n = 10
data = (rng.random(size=100) ** 2 * n).astype(int)

fit_res = stats.fit(
    stats.boltzmann,
    data,
    bounds={
        "lambda_": (0, 1),
        "N": n,
    },
)
```

This fails however, because the `fit` module uses `dist._param_info()`, and `[info.name for info in stats.boltzmann._param_info()] == ['lambda', 'N', 'loc']` - no underscore for `lambda`.

Of course, the following works, using `"lambda"` as the key in `bounds`.

```py
n = 10
data = (rng.random(size=100) ** 2 * n).astype(int)

fit_res = stats.fit(
    stats.boltzmann,
    data,
    bounds={
        "lambda": (0, 1),
        "N": n,
    },
)
```

### Error message

```shell
ValueError: The intersection of user-provided bounds for `lambda` and the domain of the distribution is not finite. Please provide finite bounds for shape `lambda` in `bounds`.
```

IMO, a slightly more useful error would be that a) a provided parameter was not recognised, and/or b) an expected parameter was not passed.

### SciPy/NumPy/Python version information

`1.9.0 1.23.1 sys.version_info(major=3, minor=10, micro=2, releaselevel='final', serial=0)`

**Comment by mdhaber** [comment]
Thanks for the report, and sorry for the typo! I'll fix that shortly.

**Comment by davidgilbertson** [comment]
Oh my bad, I didn't even see that first error. I guess my brain sees a dozen lines of red and automatically filters out the first n-1 as the usual Traceback fluff.

I think that's fine then as it is unless there are hoards of dummies like me that don't read the errors properly then complain that the errors aren't good enough :)

**Comment by mdhaber** [comment]
I agree it's tough to see with all that red. But let's see how it goes. While the error message could be more specific in this case, I imagine it will be easier to interpret when there isn't a typo in a shape parameter name!
