### ISSUE TITLE
BUG: numpy version requirement mismatch docs vs setup.py

### ISSUE THREAD

**Issue by psarka** [scipy/scipy#16763]
### Describe your issue.

According to the setup.py file of the scipy 1.7.3, numpy is <1.23.0
According to the [SciPy's documentation](https://docs.scipy.org/doc/scipy/dev/toolchain.html) of the scipy 1.7.3, numpy is <1.24.0

First reported here: https://stackoverflow.com/questions/73072257

### Reproducing Code Example

```python
pip install scipy==1.7.3 numpy==1.23.1
```

### Error message

```shell
Collecting scipy==1.7.3
  Using cached scipy-1.7.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (39.3 MB)
Collecting numpy==1.23.1
  Downloading numpy-1.23.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
     |████████████████████████████████| 17.1 MB 7.6 MB/s 
ERROR: scipy 1.7.3 has requirement numpy<1.23.0,>=1.16.5, but you'll have numpy 1.23.1 which is incompatible.
Installing collected packages: numpy, scipy
Successfully installed numpy-1.23.1 scipy-1.7.3
```

### SciPy/NumPy/Python version information

1.7.3 1.23.1 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Thank you for reporting @psarka. This seems to be wrong in the doc indeed. Would you like to make a PR to fix it?
