### ISSUE TITLE
DOC: `scipy.stats.skew` no longer returns 0 on constant input

### ISSUE THREAD

**Issue by mfeurer** [scipy/scipy#16765]
### Describe your issue.

The documentation of `scipy.stats.skew` states

> Returns: skewness ndarray
> The skewness of values along an axis, returning 0 where all values are equal.

However, while this used to be the case for scipy < 1.9, it is no longer the case for scipy 1.9.

### Reproducing Code Example

```python
In [1]: import scipy

In [2]: scipy.stats.skew([0, 0])
```

### Error message

```shell
Out[2]: nan
```
### Expected Outcome

```shell
Out[2]: 0.0
```

### SciPy/NumPy/Python version information

1.9.0 1.23.1 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
This was an intentional change in gh-16061. The sample skewness for constant input is undefined because common definitions of sample skewness would have zero in the numerator and denominator.

In R, for example:
```R
library(moments)
x=c(0, 0)
skewness(x)
```

https://github.com/scipy/scipy/pull/13254#issuecomment-747579313 gives a numerical example that suggests why it should not be 0 or any other number.

**Comment by mfeurer** [comment]
Thank you very much for the explanation and immediate answer, we'll adapt our code to this change. A related issue then appears that this commit and the related issue do not show up in the [scipy 1.9 changelog](https://docs.scipy.org/doc/scipy/release.1.9.0.html).

**Comment by mdhaber** [comment]
Oops, sorry for that @mfeurer. @tylerjereddy is there anything we should do if a change didn't make it into the release notes (e.g. mention it in 1.9.1 notes)?

**Comment by mfeurer** [comment]
Just checking, this means that this change will not be featured in the changelog?

**Comment by tupui** [comment]
We usually don't update the changelog during PR development but when we do create a release (we keep a wiki page for that but for backporting there are only a few items to look at so not needed and we address manually).
