### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by monika2082** [scipy/scipy#16771]
### Describe your issue.

Getting error when installing scipy package using pip

(test3) [ab63996@sl01plpchd023 ~]$ pip install --cert /opt/cloudera/security/x509/cert.pem --trusted-host pypi.python.org --no-cache-dir scipy
Collecting scipy
  Downloading scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl (25.9 MB)
     |████████████████████████████████| 25.9 MB 102 kB/s
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    scipy from https://files.pythonhosted.org/packages/c8/89/63171228d5ced148f5ced50305c89e8576ffc695a90b58fe5bb602b910c2/scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl#sha256=368c0f69f93186309e1b4beb8e26d51dd6f5010b79264c0f1e9ca00cd92ea8c9:
        Expected sha256 368c0f69f93186309e1b4beb8e26d51dd6f5010b79264c0f1e9ca00cd92ea8c9
             Got        a92cc0fae8b65771b0b53287daeb39cd3ee228d6d5580fdd5af4062612070042

### Reproducing Code Example

```python
pip install --cert /opt/cloudera/security/x509/cert.pem --trusted-host pypi.python.org --no-cache-dir scipy
```

### Error message

```shell
(test3) [ab63996@sl01plpchd023 ~]$ pip install --cert /opt/cloudera/security/x509/cert.pem --trusted-host pypi.python.org --no-cache-dir scipy
Collecting scipy
  Downloading scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl (25.9 MB)
     |████████████████████████████████| 25.9 MB 102 kB/s
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    scipy from https://files.pythonhosted.org/packages/c8/89/63171228d5ced148f5ced50305c89e8576ffc695a90b58fe5bb602b910c2/scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl#sha256=368c0f69f93186309e1b4beb8e26d51dd6f5010b79264c0f1e9ca00cd92ea8c9:
        Expected sha256 368c0f69f93186309e1b4beb8e26d51dd6f5010b79264c0f1e9ca00cd92ea8c9
             Got        a92cc0fae8b65771b0b53287daeb39cd3ee228d6d5580fdd5af4062612070042
```

### SciPy/NumPy/Python version information

>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info) 1.5.4 1.19.5 sys.version_info(major=3, minor=6, micro=13, releaselevel='final', serial=0)on__, sys.version_info)  1.19.5 sys.version_info(major=3, minor=6, micro=13, releaselevel='final', serial=0)

**Comment by rkern** [comment]
I've just downloaded that file and got the correct hash. Can you try again?

**Comment by monika2082** [comment]
Hi , 
We are still getting the same error. . We are using PIP package that was installed when creating conda virtual environment to install the package 
    On Wednesday, August 3, 2022, 03:20:17 PM MST, Robert Kern ***@***.***> wrote:  
 
 


I've just downloaded that file and got the correct hash. Can you try again?

**Comment by rkern** [comment]
The only thing I can think of is that you are in some custom environment that is putting up a custom PyPI mirror with `pypi.python.org` and `files.pythonhosted.org` resolving to that custom mirror. Is that the reason you have to provide the custom cert and `--trusted-host`?

AFAICT, there is nothing that we can do to help you. The files on the official `pypi.python.org` are correct (the `sha256sum` for that file is definitely `368c0f69f93186309e1b4beb8e26d51dd6f5010b79264c0f1e9ca00cd92ea8c9`). There is something about your configuration that is preventing you from getting those files uncorrupted.

**Comment by tylerjereddy** [comment]
I should mention we had this problem at work a few months ago with the implementation of SSL interception in use. I don't know a good workaround. I think in theory providing the organizational internal certificate is supposed to suffice, but it always seemed to me like SSL interception was somehow changing the content of the wheels/zip files.

**Comment by rkern** [comment]
Ugh. That's nasty.

Maybe adding `pypi.org` and `files.pythonhosted.org` to the list of `trusted-files`? ([per this search hit](https://blog.wirhabenstil.de/2021/08/18/some-notes-about-python-pip/))

**Comment by rkern** [comment]
Possibly also setting the proxy info explicitly with `--proxy`.

**Comment by tupui** [comment]
Looks like we can close the issue as not related to SciPy itself.

**Comment by tylerjereddy** [comment]
Yeah, probably not SciPy specific. I understand the frustration though, sometimes I even had the problem with the trusted lists.
