### ISSUE TITLE
BUG: indexing error in scipy.spatial.Voronoi in 3D

### ISSUE THREAD

**Issue by larszod** [scipy/scipy#16773]
### Describe your issue.

Voronoi() creates a Voronoi map from a point set of N points. 

point_region contains the contained point for each Voronoi region. But in this list there is a single extra increment, e.g. [0, 1, 2, 4, 5, 6] (when sorted) instead of [0, 1, 2, 3, 4, 5] (when sorted).

Python 3.9
Numpy 1.22.3

I haven't check if the point_region list is corrupted or the indices above the missing element can simply have a 1 subtracted

### Reproducing Code Example

```python
'''
Date Aug. 8th 2022
Author Lars Rindorf

'''

import numpy as np

N = 100
points3D = np.random.random((N,3))

from scipy.spatial import Voronoi

vor = Voronoi(points3D)

print('Number of points N', N)
print('Max index given by voronoi', np.amax(vor.point_region))

sorted_indices = vor.point_region
sorted_indices.sort()
diff = np.diff(sorted_indices)
print('Point index missing is', np.where(diff > 1)[0][0])

# I have seen a single occasion where there was no indexing error. However it seems to be rare
'''
for m in range(100000):
    vor = Voronoi(points3D)
    if np.amax(vor.point_region) < N:
        print('success')
        break
'''
```

### Error message

```shell
No message
```

### SciPy/NumPy/Python version information

1.8.0 1.22.3 sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)

**Comment by tylerjereddy** [comment]
See the cross-linked PR, where I try to alleviate the confusion a bit.
