### ISSUE TITLE
BUG: Manually vectorizing scipy.linalg.expm fails in version 1.9.0

### ISSUE THREAD

**Issue by nkoep** [scipy/scipy#16792]
### Describe your issue.

I'm not sure if this is expected behavior, but scipy 1.9.0 breaks code that manually vectorizes calls to `scipy.linalg.expm` via `np.vectorize`. I understand support for calling `expm` on stacked matrices was added in https://github.com/scipy/scipy/pull/15079. This now requires a workaround like
```python
if scipy.version.version >= "1.9.0":
    scipy_expm = scipy.linalg.expm
else:
    scipy_expm = np.vectorize(scipy.linalg.expm, signature="(m,m)->(m,m)")
```
I believe this change should not break existing code. For instance, NumPy recently added support for stacked matrices to `numpy.linalg.qr` (see https://numpy.org/doc/1.22/release/1.22.0-notes.html#numpy-linalg-qr-accepts-stacked-matrices-as-inputs) which did not break any existing code wrapping the function with `np.vectorize`. This still works fine in numpy 1.23.1:
```python
import numpy as np

a = np.random.normal(size=(3, 3))
np.vectorize(np.linalg.qr, signature="(m,n)->(m,k),(k,n)")(a)
```

### Reproducing Code Example

```python
import numpy as np
import scipy.linalg

a = np.random.normal(size=(3, 3))
np.vectorize(scipy.linalg.expm, signature="(m,m)->(m,m)")(a)
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/blaenv/lib/python3.10/site-packages/numpy/lib/function_base.py", line 2328, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/tmp/blaenv/lib/python3.10/site-packages/numpy/lib/function_base.py", line 2402, in _vectorize_call
    res = self._vectorize_call_with_signature(func, args)
  File "/tmp/blaenv/lib/python3.10/site-packages/numpy/lib/function_base.py", line 2442, in _vectorize_call_with_signature
    results = func(*(arg[index] for arg in args))
  File "/tmp/blaenv/lib/python3.10/site-packages/scipy/linalg/_matfuncs.py", line 335, in expm
    lu = bandwidth(aw)
  File "_cythonized_array_utils.pyx", line 104, in scipy.linalg._cythonized_array_utils.bandwidth
  File "_cythonized_array_utils.pyx", line 114, in scipy.linalg._cythonized_array_utils.bandwidth_c
  File "stringsource", line 660, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 350, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
```

### SciPy/NumPy/Python version information

1.9.0 1.23.1 sys.version_info(major=3, minor=10, micro=5, releaselevel='final', serial=0)

**Comment by rgommers** [comment]
> For instance, NumPy recently added support for stacked matrices to `numpy.linalg.qr` (see https://numpy.org/doc/1.22/release/1.22.0-notes.html#numpy-linalg-qr-accepts-stacked-matrices-as-inputs) which did not break any existing code wrapping the function with `np.vectorize`.

Only because the `signature` keyword was already necessary before it looks like.

This is a little unfortunately, but given that the function was completely re-written from scratch, I am not sure this is avoidable. @ilayn WDYT?

**Comment by ilayn** [comment]
This looks like a shortcoming of Cython for some reason doesn't like the memorybuffer to be read-only. We tried out previously to use const in the signature of `bandwidth` but it is an open bug that I'm told that it is fixed in Cython 3.0. I am not able to build things now but if I can fix that soon I'll change it to tempita maybe. 

Nevertheless, `numpy.vectorize` does not seem to be the right tool for this anyways. But I guess it's too late for that. I don't know why everybody likes to call for loops as `vectorizing`.

**Comment by ilayn** [comment]
The relevant issue https://github.com/cython/cython/issues/1605 for future reference

**Comment by ilayn** [comment]
What I don't understand is why vectorize marks things as read-only.

**Comment by ev-br** [comment]
Fixed by gh-20195

```
In [1]: import numpy as np
   ...: import scipy.linalg
   ...:
   ...: a = np.random.normal(size=(3, 3))
   ...: np.vectorize(scipy.linalg.expm, signature="(m,m)->(m,m)")(a)
Out[1]: 
array([[ 0.29571569, -0.0045622 ,  0.48342085],
       [ 0.33301448,  0.40461489,  0.85759304],
       [ 0.52706851,  1.4820707 ,  3.49340838]])
```
