### ISSUE TITLE
DOC: Method "bisect" for root_scalar lacks correct argument list

### ISSUE THREAD

**Issue by asberk** [scipy/scipy#16796]
### Describe your issue.

In the [documentation](https://docs.scipy.org/doc/scipy/reference/optimize.root_scalar-bisect.html#optimize-root-scalar-bisect) for `root_scalar` with `method='bisect'`, there is no mention of having to use the `bracket` argument. This is also the case for other methods, such as `brentq`, which take a `bracket` argument not shown by the documentation sub-page. 

### Reproducing Code Example

```python
NA
```

### Error message

```shell
NA
```

### SciPy/NumPy/Python version information

SciPy 1.9.0

**Comment by tupui** [comment]
Hi @asberk thank you for reporting. Indeed it's missing. Would you like to make a PR to improve the doc?
