### ISSUE TITLE
BUG: COBYLA Callback function not working

### ISSUE THREAD

**Issue by Chad-Peterson** [scipy/scipy#16798]
### Describe your issue.

Hi, the scipy.optimize.minimize documentation implies that the COBYLA method supports callback and the sourcecode explicitly states that the callback function argument is optional; however, when I attempt to run the solver, I get a runtime error message stating hat COBYLA doesn't support callback.

By the way, I am interested in getting involved with SciPy. The contributor's guide said that I could reach out while submitting an issue. I am a PhD student at the University of Illinois studying systems engineering. I use the Optimize module often and find it very helpful.
 

### Reproducing Code Example

```python
import numpy as np
from scipy.optimize import minimize, show_options


def callback(xk):
    print('xk', xk)

# Random function to test COBYLA
def fun(x): return x ** 2 + 2


x0 = np.array([1, 2, 3])
res = minimize(fun, x0, method='COBYLA', callback=callback)
```

### Error message

```shell
RuntimeWarning: Method COBYLA does not support callback.
```

### SciPy/NumPy/Python version information

1.7.3 1.21.6 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @Chad-Peterson thank you for reporting. 

Can you try updating SciPy? I remember some PRs around that recently. A quick look at the code seem to pass the callback down to the optimizer so it should work.

About getting into SciPy, welcome! Feel free to join our next community or newcomers meeting to introduce yourself and discuss what you can and want to do: 
https://scientific-python.org/calendars/

**Comment by Chad-Peterson** [comment]
Thanks, it looks like updating python and SciPy to the latest versions resolve the issue. 

I've added the meetings to my calendar--looking forward.

**Comment by tupui** [comment]
Great thank you for confirming.
