### ISSUE TITLE
DOC: Wrong formula for the calculation of t statistic in scipy.stats.ttest_1samp

### ISSUE THREAD

**Issue by BLKSerene** [scipy/scipy#16807]
### Describe your issue.

In the Notes part of the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_1samp.html#scipy.stats.ttest_1samp) of `scipy.stats.ttest_1samp`, the formula for calculating the t statistic is: `(np.mean(a) - popmean) / se`.

This seems to be wrong, as the denominator should be first divided by the number of samples, which would then match the [implementation](https://github.com/scipy/scipy/blob/651a9b717deb68adde9416072c1e1d5aa14a58a1/scipy/stats/_stats_py.py#L6075).

Reference: [Student's t-test - Wikipedia](https://en.wikipedia.org/wiki/Student%27s_t-test#One-sample_t-test)

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

SciPy 1.8.0 / NumPy 1.22.3 / Python 3.8.10 x64

**Comment by matthew-brett** [comment]
I think the formula is correct, where `(np.mean(a) - popmean) / se` where `se` is the standard *error* (not standard deviation), `se = np.sqrt(v / n)` and v is the DF adjusted variance.

**Comment by BLKSerene** [comment]
Ah, I mistook standard error as standard deviation. Yes, it is correct.

**Comment by josef-pkt** [comment]
It could be made more explicit and specify that se is the standard deviation of the mean (estimate), `sem`.
