### ISSUE TITLE
BUG: stats.binned_statistic_2d is ~8x slower when using `statistic=np.mean` vs `statistic="mean"`

### ISSUE THREAD

**Issue by jvavrek** [scipy/scipy#16819]
### Describe your issue.

passing numpy array functions to `stats.binned_statistic_2d` is ~8x slower than passing their string names. Presumably there are some optimizations for specific function names that don't exist when a generic `callable` is passed in?

A perhaps-simple fix would be to check if the `statistic` passed in is one of a few corresponding numpy functions, e.g.,
```py
if statistic in {"mean", np.mean}:
    ...
elif statistic in {"sum", np.sum}:
    ...
```

### Reproducing Code Example

```python
import numpy as np
from scipy.stats import binned_statistic_2d

points = np.random.random(size=(10_000_000, 3))

%timeit binned_statistic_2d(*points.T, statistic="mean")
# 974 ms ± 21.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%timeit binned_statistic_2d(*points.T, statistic=np.mean)
# 8.22 s ± 78.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

### Error message

```shell
n/a
```

### SciPy/NumPy/Python version information

1.6.1 1.19.5 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Thank you for reporting @jvavrek. This seems like a sensible ask. I am +1. Let see what other think.

If we go with it, would you be interested in contributing?

**Comment by jvavrek** [comment]
> If we go with it, would you be interested in contributing?

Yes, I'd be happy to contribute
