### ISSUE TITLE
BUG: Sparse matrix multiplication output outright wrong

### ISSUE THREAD

**Issue by taufique71** [scipy/scipy#16827]
### Describe your issue.

For same two matrices, matrix multiplication output generated by `numpy` and `scipy.sparse` does not match 

### Reproducing Code Example

```python
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix

DA = np.array([[0.82, 0.0, 0.0], [0.0, 0.84, 0.0], [0.0, 0.0, 0.0]])
DB = np.array([[0.0, 0.0, 0.41], [0.90, 0.0, 0.0], [0.0, 0.0, 0.0]])
print(np.matmul(DA, DB))

SA = csr_matrix(DA)
SB = csr_matrix(DB)
print(SA.multiply(SB).toarray())
```

### Error message

```shell
numpy output:
[[0.     0.     0.3362]
 [0.756  0.     0.    ]
 [0.     0.     0.    ]]

scipy output:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
```

### SciPy/NumPy/Python version information

1.8.1 1.22.3 sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment]
The `multiply` method of the sparse matrix classes is element-wise multiplication.  For the matrix product, you can use the `@` operators
```
In [12]: (SA @ SB).toarray()
Out[12]: 
array([[0.    , 0.    , 0.3362],
       [0.756 , 0.    , 0.    ],
       [0.    , 0.    , 0.    ]])
```
