### ISSUE TITLE
ENH: stats.binned_statistics functions could take a list of callables

### ISSUE THREAD

**Issue by jvavrek** [scipy/scipy#16820]
### Is your feature request related to a problem? Please describe.

Say I have a 3D point cloud and I would like to compute some statistics on the z values in each xy pixel. `stats.binned_statistics` is perfect for this, with one exception—if I want to compute multiple statistics, I have to rebin the data each time, which could be quite inefficient, especially for generic callables (see also https://github.com/scipy/scipy/issues/16819)

### Describe the solution you'd like.

`stats.binned_statistics` should take a list (really, any sequence) of callables and/or strings, and compute binned statistics for each of them, returning a sequence of binned results.

### Describe alternatives you've considered.

Repeatedly calling `stats.binned_statistics`, once for each desired `statistic`. As mentioned this can be quite inefficient.

**Comment by tupui** [comment]
Thank you for reporting @jvavrek. This seems reasonable and the math part could be done quite easily since everything happens in `_calc_binned_statistic`. But then we need to think about the data structure we want to output in the end. Did you look into this and would have a proposal?

**Comment by jvavrek** [comment]
> But then we need to think about the data structure we want to output in the end. Did you look into this and would have a proposal?

Currently we return a named tuple:
```py
BinnedStatisticddResult = namedtuple('BinnedStatisticddResult',
                                     ('statistic', 'bin_edges',
                                      'binnumber'))
```

I think just a tuple or list of these `namedtuples` would suffice.

**Comment by jvavrek** [comment]
Looking through the source code however I see:
```
binned_statistic_result : binnedStatisticddResult
        Result of a previous call to the function in order to reuse bin edges
        and bin numbers with new values and/or a different statistic.
        To reuse bin numbers, `expand_binnumbers` must have been set to False
        (the default)
```
so perhaps that is the "expected" way of avoiding the rebinning, and this can be closed?

**Comment by tupui** [comment]
Oh indeed I missed this somehow 👍 Let's close it now then and we can revisit how this is done if we have more problems/ideas. Thanks again.
