### ISSUE TITLE
BUG: CircleCI broken

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#16838]
### Describe your issue.

Currently, CircleCI fails.

Probably related to the misc -> dataset stuff.

### Reproducing Code Example

[CircleCI Output from a current PR](https://app.circleci.com/pipelines/github/scipy/scipy/14913/workflows/c12fd4ad-c87c-490c-b892-69f5d45c2f18/jobs/53096)

### Error message

```shell
ImportError: Missing optional dependency 'pooch' required for scipy.datasets module. Please use pip or conda to install 'pooch'.
```

### SciPy/NumPy/Python version information

irrelevant

**Comment by AnirudhDagar** [comment]
Thanks, @dschmitz89 for the report. Let me take a look.

**Comment by dschmitz89** [comment]
Merging main helped for my PR already, might have been mistaken.

**Comment by AnirudhDagar** [comment]
Great, closing this now! :)
