### ISSUE TITLE
LICENSE.txt, LICENSES_bundled.txt not being included in the package directory structure when building with meson

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#16841]
### Describe your issue.

When building a wheel with meson LICENSE.txt, LICENSES_bundled.txt are not included in the package hierarchy.
e.g. scipy/LICENSE.txt isn't present in the wheel:
```
$ ls scipy/LICENSE.txt
ls: scipy/LICENSE.txt: No such file or directory
```
It is however in the dist info:
```
$ ls scipy-1.10.0.dev0.dist-info/LICENSE.txt
scipy-1.10.0.dev0.dist-info/LICENSE.txt
```

Should the LICENSE.txt file be present within the package hierarchy when installed, or is it fine just to have it within the `dist-info`? At the moment all wheels on pypi have the license file present in the package hierarchy.

### Reproducing Code Example

```python
<>
```

### Error message

```shell
<>
```

### SciPy/NumPy/Python version information

<>

**Comment by rgommers** [comment]
Within `dist-info` is fine. A license file is metadata, so in that folder seems better actually than in the importable tree (it's not a data file, and there is no requirement that it should be there).

We did this on purpose, so I suggest we close this issue.
