### ISSUE TITLE
distance matrix Python to C++

### ISSUE THREAD

**Issue by HyungJoo-Kwon** [scipy/scipy#16849]
I want to convert Scipy distance matrix to C++ code.
I used a variety of libraries, but it took too long.
And then i found optimized C version code  <https://github.com/scipy/scipy/blob/main/scipy/spatial/distance.py>   2846 line.
Where can i check optimized C version code or any better idea?

**Comment by rkern** [comment]
The C-implemented distance metrics are here: https://github.com/scipy/scipy/tree/main/scipy/spatial/src

I will close this as the question has been answered, and there is no feature request or bug report to follow up on.
