### ISSUE TITLE
Python 3.11 manylinux wheels

### ISSUE THREAD

**Issue by hrnciar** [scipy/scipy#16851]
Hello.

Could you please release CPython 3.11 manylinux wheels on PyPI?

Python 3.11.0 release candidate 1 was released: https://discuss.python.org/t/python-3-11-1rc1-is-now-available/18068/7

It should be quite safe to release wheels for the release candidate. ABI for Python 3.11 should be frozen from now on, even for bug fixes. From release notes:

    There will be no ABI changes from this point forward in the 3.11 series and the goal is that there will be as few code changes as possible.

Thank You.

**Comment by ilayn** [comment]
Thanks @hrnciar we are receiving this request prior to every major Python releases and we are kind of giving the same response that we don't want to jump on the gun until the official version is released. There are multiple reasons for this and they are becoming less and less important so maybe soon we will start with RCs but so far we shy away from early releases since it causes a lot of problems if we miss something and then we have to release immediate minor versions and handle the fallout.

**Comment by tupui** [comment]
I am pinning this so we don't get more issues for that.

**Comment by andyfaff** [comment]
Another aspect is that some of the test dependencies aren't available for 3.11 yet. So any build wouldn't be tested fully.

**Comment by tupui** [comment]
> Another aspect is that some of the test dependencies aren't available for 3.11 yet. So any build wouldn't be tested fully.

What do you mean exactly? We are testing in the CI 3.11 since the first beta.

**Comment by andyfaff** [comment]
gmpy2 isn't available as a wheel yet. I guess it's an optional test dependency though.

**Comment by tupui** [comment]
Yes we don't install mpmath nor gmpy2 in this job (all the rest is the same). I am not sure if they could build fine by themselves, maybe.

**Comment by tylerjereddy** [comment]
I think this gets a bit easier to do with the new cibuildwheel infrastructure @andyfaff has been driving forward, and I believe that's how NumPy got a 3.11rc wheel out recently? That said, I don't think we plan to do CPython rc wheels just yet.

**Comment by rgommers** [comment]
> Thanks @hrnciar we are receiving this request prior to every major Python releases and we are kind of giving the same response that we don't want to jump on the gun until the official version is released.

This isn't quite true anymore, after CPython declared ABI stability from RC1 we are now able to put wheels up before the final 3.11.0 release. NumPy already did this, so we can do this whenever is convenient for us.

We are planning to do a 1.9.1 release in a week or so, so we should try to take 3.11 wheels along for that.

**Comment by tylerjereddy** [comment]
Are we still using multibuild for `1.9.1`/`3.11` wheels? It wasn't immediately clear to me that i.e., Appveyor wouldn't be at least a bit annoying for that?

**Comment by rgommers** [comment]
Yes I think so. Although I need to get to reviewing @andyfaff's PR. I'd rather let that sit in `main` for a little while and test it with nightlies though, rather than doing a release with it straight away.

You are right though, if it's a significant pain to add 3.11 support in the multibuild setup, we can wait until 1.9.2

**Comment by tylerjereddy** [comment]
Ok, I'll start poking a bit for `3.11` stuff to see where it stands.

**Comment by andyfaff** [comment]
> . I'd rather let that sit in main for a little while and test it with nightlies though, rather than doing a release with it straight away.

Definitely makes sense. I've just fired up the cibw PR again to build 3.11 wheels.

**Comment by tylerjereddy** [comment]
For `3.11` support, if folks want to help with the `multibuild` debug issues: https://github.com/MacPython/scipy-wheels/pull/174. It is a bit painful to deal with, and I haven't even started on Windows. I think we may delay the `3.11` support to SciPy `1.9.2` unless we make considerable progress there before ~Friday.

**Comment by rgommers** [comment]
> I think we may delay the `3.11` support to SciPy `1.9.2` unless we make considerable progress there before ~Friday.

Makes sense, not a major surprise. +1 for delaying. The `cibuildwheel` infra may be ready by `1.9.2` release time, and it already has 3.11 support.

**Comment by andyfaff** [comment]
@hrnciar, 3.11 wheels are available, unofficially (not release, not even nightly), from artifacts in the [wheel action page](https://github.com/scipy/scipy/actions/workflows/wheels.yml). By all means experiment with them, but please don't use in production.

e.g. https://github.com/scipy/scipy/actions/runs/2908455453#artifacts.

You need to look for a run where the build actually happened, rather than being skipped.

**Comment by andyfaff** [comment]
@rgommers, do you have the bandwidth to make the nightly wheels upload in the wheel builder script go [live](https://github.com/scipy/scipy/blob/main/.github/workflows/wheels.yml#L199), or do you think we should debug a little more?

**Comment by rgommers** [comment]
I think it's good to go. Let me try to figure this out today. I may have to hunt down the right token for the Anaconda bucket, not sure if I still have that stored in my password manager.

**Comment by andyfaff** [comment]
Is the token saved in the GitHub settings somewhere?

**Comment by rgommers** [comment]
Yes it is, but for safety reasons you can't make it visible, only remove it or update its value. I found my credentials though, I can create a new token.

**Comment by andyfaff** [comment]
@cclauss @hrnciar and others, there are nightly wheels for 3.11 now available at https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/. It would be great if you could test them out.

**Comment by EwoutH** [comment]
Any way we can get wheels for Python 3.11 published to PyPI sooner than later? Either by building and adding them to the current 1.9.1 release, by creating a 1.9.2 release with them or releasing them with 1.10.0?

SciPy is an upstream dependency for a huge number of libraries and packages, for which wheels for 3.11 are really important.

**Comment by rgommers** [comment]
Yes, I think we can/should do a 1.9.2 release within the next 2 weeks. What needs doing is:
- there's 13 PRs labelled for backporting,
- we need to give `cibuildwheel` on the 1.9.x branch a spin (should be fine without the CirrusCI changes),
- we need the `meson-python` 0.9.0 release

**Comment by tupui** [comment]
In the past we always waited for Python versions to be released before shipping wheels. But since rc2 is out today, maybe it's safe enough for us to consider releasing a wheel.

**Comment by rgommers** [comment]
@tupui we can release wheels from Python's rc1 onwards, because of ABI stability. That's a settled topic by now.

**Comment by EwoutH** [comment]
> * we need the `meson-python` 0.9.0 release

[meson-python 0.9.0](https://github.com/FFY00/meson-python/releases/tag/0.9.0) was released Friday and is [available](https://pypi.org/project/meson-python/) on PyPI!

**Comment by tupui** [comment]
1.9.2 is coming soon with wheels for Python 3.11. Meanwhile, dev wheels are now available as Andrew said above: https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/

**Comment by tylerjereddy** [comment]
`3.11` wheels should be up on PyPI now; I'm still going through some final motions of the release process, but `1.9.2` is effectively "out"  as far as PyPI is concerned now.

**Comment by EwoutH** [comment]
Congratulations, and thanks for this effort!

**Comment by rgommers** [comment]
Great, all looks good. Thanks all, closing this issue.
