### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by Kurt-Shiwz** [scipy/scipy#16861]
### Describe your issue.

exp2: t-statistic is `inf`. The p-value `0`.

### Reproducing Code Example

```python
base=[4.28,4.34]
exp1=[4.43,4.45]
exp2=[4.33,4.39]
t,p=stats.ttest_rel(exp1,base)
print(t,p)
t,p=stats.ttest_rel(exp2,base)
print(t,p)
```

### Error message

```shell
6.500000000000133 0.0971795806950559
inf 0.0
```

### SciPy/NumPy/Python version information

1.9.0 1.23.2 sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
A t-statistic of infinity is consistent with a p-value of zero. 
Please explain why the output is not what you would expect.

**Comment by Kurt-Shiwz** [comment]
> A t-statistic of infinity is consistent with a p-value of zero. Please explain why the output is not what you would expect. If you think that something is wrong, please calculate the t-statistic from its definition manually and show that it is different than what the code produces.

t-statistic should be `Inf`?  se is zero?
![image](https://user-images.githubusercontent.com/7554917/185557435-cc7c6881-9ff6-4031-873f-cb2f64eaa73e.png)

```
>>> import numpy as np
>>> base=[4.28,4.34]
>>> exp2=[4.33,4.39]
>>> print((np.mean(np.array(exp2) - np.array(base)))/np.std(np.array([exp2,base]),ddof=1))
1.1088319064318612
>>> print(np.std(np.array([exp2,base]),ddof=1))
0.045092497528228706```

**Comment by mdhaber** [comment]
`ttest_rel` is for a relative t-test. It tests the _paired_ differences for significance. The mean and standard error are of the quantity `a-b` shown above, and `exp2 - base == [0.5, 0.5]` which has zero variance.
