### ISSUE TITLE
BUG: center of mass

### ISSUE THREAD

**Issue by TomFD** [scipy/scipy#16879]
It is not really a bug but an issue of typical int32 overflow.
Below is an image, which, if converted to a numpy matrix is int32 and the scipy center of mass function delivers coordinates outside the grid, which is wrong. This happens, because in scipy:
`normalizer = sum(input, labels, index)`
overflows. Especially as 16bit images contain large numbers.

There are many methods to avoid, like making the matrix float, etc, but can it maybe be handled inside the scipy functions?

![nf_2](https://user-images.githubusercontent.com/44144239/185934034-d7382b2f-6f36-4416-b144-5ac5c16722d8.png)

### Reproducing Code Example

```python
from PIL import Image
from scipy import ndimage
import numpy as np

im = Image.open('nf_2.png')

npa = np.array(im) 

print(npa.shape,npa.dtype) # is int32
print('min/max of array',npa.min(),npa.max())
print(ndimage.center_of_mass(npa))

com_x = 0.0
com_y = 0.0
sum = 0.0 # float
for x in range(npa.shape[1]):
    for y in range(npa.shape[0]):
        sum += npa[y][x] # overflow if sum is int32
        com_x += float(npa[y][x])*float(x)
        com_y += float(npa[y][x])*float(y)
com_x /= sum
com_y /= sum
print('should be:',com_y,com_x)
```

### Error message

```shell
(1216, 1936) int32
min/max of array 96 65520
(2645.1217782736508, 4121.233298317583)
should be: 622.3249332060187 969.6136707837329
```

### SciPy/NumPy/Python version information

1.7.1 1.20.3 sys.version_info(major=3, minor=7, micro=7, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment]
Thanks for the report, @TomFD. I suspect you are on Windows, where the default integer type in NumPy is `int32`.  I can reproduce the problem on systems where the default integer is `int64` with this simple example:

```
In [72]: import numpy as np

In [73]: from scipy.ndimage import center_of_mass

In [74]: m = 2**63-1

In [75]: x = np.array([[m, m], [m, m]])

In [76]: x
Out[76]: 
array([[9223372036854775807, 9223372036854775807],
       [9223372036854775807, 9223372036854775807]])

In [77]: center_of_mass(x)
Out[77]: (-4.611686018427388e+18, -4.611686018427388e+18)
```
The result should be (0.5, 0.5):
```
In [78]: center_of_mass(x.astype(np.float64))
Out[78]: (0.5, 0.5)
```

**Comment by rkern** [comment]
Previously reported in #16821. My proposed fix is to try to make the [normalization constant calculation](https://github.com/scipy/scipy/blob/main/scipy/ndimage/_measurements.py#L1417) use a `float` accumulator the same way that we use floats later in the calculation. Unfortunately, that requires making API changes through a moderately long chain of of functions.

**Comment by rkern** [comment]
We end up creating a bunch of `float64` temporaries later when we multiply the `input` against the grids, so one more temporary (`sum(input.astype(float), labels, index)`) would probably not be *too* onerous.

**Comment by WarrenWeckesser** [comment]
Thanks @rkern.  I'll close this as a duplicate.
