### ISSUE TITLE
ENH: Add Rotation.align_vector

### ISSUE THREAD

**Issue by noamraph** [scipy/scipy#16880]
### Is your feature request related to a problem? Please describe.

I wanted to plot a wireframe of a sphere, where its pole is directed at some direction.
I already had a wireframe of a sphere with its pole in the Z direction. So it made sense to apply a rotation to this sphere. However, I had to implement by myself the function that finds the required rotation.

### Describe the solution you'd like.

Add a method, perhaps called `Rotation.align_vector()`, which would get two vectors, and would find the simple rotation that rotates the first vector to the second.

(There is more than one rotation that would transform the first vector to the second, since you can rotate around the second vector. However, there is one "obvious" rotation, around the normal to the plane containing the vectors)

### Describe alternatives you've considered.

I tried `Rotation.align_vectors()`, but it requires more than one vector. This is expected, since it uses an optimization algorithm, and there is more than one solution.

At the end I implemented this function:

```python
def get_rot_from_vecs(vec0, vec1):
  """
  Get the rotation that rotates one vector to another.
  """
  from numpy.linalg import norm
  vec0 = vec0 / norm(vec0)
  vec1 = vec1 / norm(vec1)
  cross = np.cross(vec0, vec1)
  theta = np.arccos(np.dot(vec0, vec1))
  rot_vec = cross / norm(cross) * theta
  rot = Rotation.from_rotvec(rot_vec)
  assert np.allclose(rot.apply(vec0), vec1)
  return rot

```

**Comment by scottshambaugh** [comment]
I believe that https://github.com/scipy/scipy/pull/17542 would satisfy this.

**Comment by scottshambaugh** [comment]
Actually, thinking about it more I believe this PR is asking for something different - wanting to rotate between frames while zeroing the secondary axis rotation. That's not something the above PR does, but it might be an easy thing to add into it (or add on as a separate fcn).

**Comment by scottshambaugh** [comment]
Specifically, you can get this behavior from the above PR by calling `align_constrain([vec0, vec0], [vec1, vec1])`, which will see the parallel primary and secondary axes, and resolve to the same as `align_constrain([vec0, [1, 0, 0], [vec1, [1, 0, 0]])`. This should keep zero rotation about that secondary axis.

However, the ergonomics of that function could be better, and I think your code above is a good test case. I'll add in some stuff to make it more usable.

**Comment by scottshambaugh** [comment]
The above PR has been updated, so you'll be able to get this behavior with just `align_constrain(vec0, vec1)`. This is also now the fallback behavior if the pairs of primary and secondary axes are parallel.

**Comment by cgobat** [comment]
I may be missing something here, but [`Rotation.align_vectors()`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.align_vectors.html)[^versionnote] should be able to work with single vectors.

[^versionnote]: Introduced in [SciPy 1.4](https://docs.scipy.org/doc/scipy-1.4.0/reference/generated/scipy.spatial.transform.Rotation.align_vectors.html), but a similar function [`Rotation.match_vectors()`](https://docs.scipy.org/doc/scipy-1.3.0/reference/generated/scipy.spatial.transform.Rotation.match_vectors.html) existed even before then

In order to do so, you just need to wrap your vectors in another set of braces so that their shape is each `(1, 3)`, or use [`numpy.atleast_2d()`](https://numpy.org/doc/stable/reference/generated/numpy.atleast_2d.html), which will accomplish the same thing. For example
```python
In [1]: import numpy as np
        from scipy.spatial.transform import Rotation
        z_axis = np.atleast_2d([0, 0, 1])
        desired_pointing = np.atleast_2d([1, 0, 0]) # or whatever
        r, rssd = Rotation.align_vectors(desired_pointing, z_axis) # (or vice versa)
        r.as_matrix()

Out[1]:
array([[ 0.,  0.,  1.],
       [-1.,  0.,  0.],
       [ 0., -1.,  0.]])
```

This will not throw the `ValueError: Expected input 'a' to have shape (N, 3), got (3,)` that it does when you pass 1-dimensional arrays. Is this what you're going for?

**Comment by scottshambaugh** [comment]
I tested it out and that will work to align the primary vectors! However it doesn't replicate the minimum distance rotation like the original issue suggested. Here's my script:

```python
import numpy as np
from scipy.spatial.transform import Rotation

atol = 1e-12
mats_a = Rotation.random(100, random_state=0).as_matrix()
mats_b = Rotation.random(100, random_state=1).as_matrix()
for i, (mat_a, mat_b) in enumerate(zip(mats_a, mats_b)):
        # Get random 3-element unit vectors
        a = mat_a[0]
        b = mat_b[0]

        # align_vectors method
        R1, _ = Rotation.align_vectors(np.atleast_2d(a), np.atleast_2d(b))
        assert np.allclose(R1.apply(b), a, atol=atol)

        # align_constrain method
        theta = np.arccos(np.dot(a, b))
        cross = np.cross(b, a)
        rot_vec = cross / np.linalg.norm(cross) * theta
        R2 = Rotation.from_rotvec(rot_vec)
        assert np.allclose(R2.apply(b), a, atol=atol)

        try:
            assert np.allclose(R1.as_matrix(), R2.as_matrix())
        except Exception as e:
            print(f'Failed on iteration {i}')
            print(f'R1:\n{R1.as_matrix()}')
            print(f'R2:\n{R2.as_matrix()}')
            raise e
```

The assert statements checking that we have aligned the primary vectors pass, but the rotation matrix comparison fails:
```
Failed on iteration 0
R1:
[[ 0.99580291 -0.08355747  0.03734576]
 [-0.00792712  0.3277697   0.9447244 ]
 [-0.09117959 -0.94105535  0.32573165]]
R2:
[[ 0.81662816 -0.18834755 -0.54556727]
 [ 0.42295984  0.83846068  0.3436403 ]
 [ 0.3927129  -0.51137939  0.76437405]]
```
