### ISSUE TITLE
BUG: There is no infomation about the predictor in BoxCox transformation, stats.boxcox()

### ISSUE THREAD

**Issue by Yan9564** [scipy/scipy#16882]
`###` Describe your issue.

**stats.boxcox** can make BoxCox transformation on data $x$ according to the method proposed in the reference[^1] below.

According to the reference, we make transformation by

$$y = \frac{x^\lambda-1}{\lambda} ~\text{when} ~~\lambda \neq 0~ ~\text{and} ~~y = \log x ~~\text{when} ~~\lambda = 0$$

There is an assumption that

$$ \mathbb{E}(y)=t \times {\theta} $$

This indicates that we assume a linear function for $y$ with predictor $t$ and parameter $\theta$

When finding the optimal value $\hat\lambda$ using MLE, we need to find the value $\hat\theta$ too, specifically

$$\hat\lambda,\hat\theta = \max \mathcal{L}(y|\theta,\lambda)$$

Obviously, different $\theta$ would lead to different $\lambda$.

However, in our current function stats.boxcox, there is no information about $\theta$.
Also, no input of the predictor $t$ is required.

[^1]: G.E.P. Box and D.R. Cox, “An Analysis of Transformations”, Journal of the Royal Statistical Society B, 26, 211-252 (1964).

### Reproducing Code Example

```python
Null
```

### Error message

```shell
Null
```

### SciPy/NumPy/Python version information

Null

**Comment by mdhaber** [comment]
AFAICT, `boxcox` does what it is intended to do, although it may not be doing what you want or returning all the information you're looking for. Is there other software that does what you think should happen, such as scikit-learn's [`power_transform`](https://www.google.com/url?sa=t&source=web&rct=j&url=http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.power_transform.html&ved=2ahUKEwjSgZLMktz5AhVoLEQIHdVPD2QQFnoECBEQAQ&usg=AOvVaw3_olWEKM_lY7t4bH--3NFP) or a Box-Cox function in R (e.g. https://www.rdocumentation.org/packages/EnvStats/versions/2.7.0/topics/boxcox)? That would help me understand what you're looking for.

**Comment by mdhaber** [comment]
@Yan9564 thanks for reporting but without follow-up, I'm not sure what we can do. I'll close for now, but feel free to re-open.
