### ISSUE TITLE
Add legend to `rv_histogram` plot in docs

### ISSUE THREAD

**Issue by jo-mueller** [scipy/scipy#16892]
Hi scipy folks, 

I was wondering whether it would add to the documentation to add legends to the example rv_histogram plot [here](https://docs.scipy.org/doc/scipy-1.8.1/reference/generated/scipy.stats.rv_histogram.html). In order to add this, I think I'd just have to add a `plt.legend()` [here](https://github.com/scipy/scipy/blob/7c6d6aa0d48b1f91ce4e24a19e08e9410f815b68/scipy/stats/_continuous_distns.py#L9645), right?

**Comment by tupui** [comment]
Hi @jo-mueller, thank you for reporting. Yes this would be a good improvement and you correctly identified the fix. Another optional thing to consider while we are at it is to use the object oriented approach for Matplotlib.

**Comment by jo-mueller** [comment]
Hi @tupui ,

thanks for the feedback.

> the object oriented approach for Matplotlib.

With that you mean something like this in the example?

```python
import matplotlib.pyplot as plt
X = np.linspace(-5.0, 5.0, 100)

fig, ax = plt.subplots()
ax.set_title("PDF from Template")
ax.hist(data, density=True, bins=100)
ax.plot(X, hist_dist.pdf(X), label='PDF')
ax.plot(X, hist_dist.cdf(X), label='CDF')
ax.legend()
ax.show()
```

**Comment by tupui** [comment]
Yes, exactly.
