### ISSUE TITLE
MAINT: stats: optimize: Move `_contains_nan` function to more common place for other modules.

### ISSUE THREAD

**Issue by AtsushiSakai** [scipy/scipy#16912]
There are some requests to add nan handling functionally for some APIs in the `optimize` module.
- #11841 (Staled PR #11846)
- #4777

If we add nan handling functionalities for these functions, I think these should have [`nan_policy`](http://scipy.github.io/devdocs/dev/api-dev/nan_policy.html?highlight=nan_policy) optional argument for consistent UX similar to `stats` module.
Also, I think we should move `_contains_nan` function from the `stats` module to a more common place (e.g. under [_lib](https://github.com/scipy/scipy/tree/main/scipy/_lib) directory?) for using by other modules like `optimize`.
It is useful for `nan_policy` implementation.

Any comments about having the `nan_policy` argument by not `stats` module functions and moving `contains_nan` function to a more common place?

**Comment by mdhaber** [comment]
No concerns from me.
