### ISSUE TITLE
BUG: `scipy.sparse.csc_matrix.argmin` returns wrong values

### ISSUE THREAD

**Issue by asi1024** [scipy/scipy#16929]
### Describe your issue.

`scipy.sparse.csc_matrix.argmin` seems to return wrong value when all elements are positive.

### Reproducing Code Example

```python
>>> import scipy
>>> x = scipy.sparse.coo_matrix(([1, 0.1, 1, 1], ([0, 0, 1, 1], [0, 1, 0, 1])), shape=(2, 2)).tocsc()
>>> x.todense()
matrix([[1. , 0.1],
        [1. , 1. ]])
>>> x.argmin()
2
>>> x.todense().argmin()
1
```

### Error message

```shell
No error messages.
```

### SciPy/NumPy/Python version information

1.9.1 1.23.0 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment]
Thanks for the report, @asi1024.  Here are a few more examples:
```
In [75]: a = csc_matrix([[3, 4, 1], [10, 2, 9]])

In [76]: a.A
Out[76]: 
array([[ 3,  4,  1],
       [10,  2,  9]])

In [77]: a.argmin()  # Should be 2
Out[77]: 4

In [78]: a.A.argmin()
Out[78]: 2
```

```
In [79]: b = csr_matrix([[3, 4, 1], [10, 2, 9]])

In [80]: b.A
Out[80]: 
array([[ 3,  4,  1],
       [10,  2,  9]])

In [81]: b.argmin()  # Should be 2
Out[81]: 4

In [82]: b.A.argmin()
Out[82]: 2
```

```
In [83]: c = coo_matrix(([10, 9, 8, 0, 6, 5], ([0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1])))

In [84]: c.A
Out[84]: 
array([[10,  9],
       [ 8,  0],
       [ 6,  5]])

In [85]: c.argmin()  # Should be 3
Out[85]: 4

In [86]: c.A.argmin()
Out[86]: 3
```
The above was run using the main development branch:
```
In [87]: import scipy

In [88]: scipy.__version__
Out[88]: '1.10.0.dev0+1757.cc63003'
```

**Comment by perimosocordiae** [comment]
The bug is here: https://github.com/scipy/scipy/blob/cc63003326b7ae2e9dd41cd6af0e6e3079c32b95/scipy/sparse/_data.py#L282

If the matrix is entirely nonzero (i.e., `nnz == prod(shape)`) then we exit early with the untransformed argmin result. From a first look, it appears that the correct return value for that case should be `mat.row[am] * mat.shape[1] + mat.col[am]`.

**Comment by perimosocordiae** [comment]
I'll put a fix together soon.
