### ISSUE TITLE
ENH: Spline/piecewise polinomial operations

### ISSUE THREAD

**Issue by vnmabus** [scipy/scipy#16921]
### Is your feature request related to a problem? Please describe.

I would want to be able to add and multiply BSpline and/or PPoly representations. This would simplify my code a lot and make it easier to do more advanced manipulations.

### Describe the solution you'd like.

Add `__add__` and `__mul__` operators for `BSpline` /`PPoly` objects that work (at least) when they are defined in the same knots.

### Describe alternatives you've considered.

Currently in some cases I have to perform operations numerically (on the evaluated function), which makes things way slower. Alternatively, this can be implemented by the user, but it is error-prone if you are not an expert on splines.

**Comment by ev-br** [comment]
With BSpline and PPoly instances you can manipulate the coefficient arrays directly, e.g. `BSpline(t, c1+c2, k)` etc.

**Comment by ev-br** [comment]
ping @vnmabus , what is the status here, are you still interested in arguing for this?  I'm still not clear what is the desired behavior TBH.

**Comment by ev-br** [comment]
OK, I'll close the issue for it now then. Feel free to reopen when you have time or add more details!
