### ISSUE TITLE
BUG: considerable performance degradation of svds since v. 1.7.3

### ISSUE THREAD

**Issue by evfro** [scipy/scipy#16925]
## Problem:
`svds` compute time has increased 2-3x since v.1.7.3. See table below for timings with rank=15 svds on 6000 x 4000 random CSR matrix with 0.05 density.

| numpy ver. / scipy ver. | `1.7.3` | `1.9.0` |
| :---         |     :---:      |   :---: |
| `1.21.4` | 1.19 s ± 82.4 ms | 2.8 s ± 351 ms |
| `1.23.2` | incompatible | 3.17 s ± 241 ms |

## Expected behavior:
Compute time remains the same or decreases.

### Reproducing Code Example

```python
# run in jupyter notebook / google colab:

from scipy.sparse.linalg import svds
from scipy.sparse import random as sprandom

shape = 6000, 4000
rank = 15
matrix = sprandom(*shape, density=0.05, format='csr', random_state=987)

%timeit svds(matrix, k=rank)
```

### Error message

```shell
n/a
```

### SciPy/NumPy/Python version information

1.9.0 1.23.2 sys.version_info(major=3, minor=9, micro=13, releaselevel='final', serial=0)

## UPDATE:
The problem seem to become less severe on larger matrices. For example, with a CSR matrix of size 60000 x 40000 with 0.01 density, the difference between old vs recent version of scipy is `3min 20s` vs `3min 47s`, albeit still a bit slower.

**Comment by mdhaber** [comment]
I couldn't reproduce this. Is the BLAS/LAPACK version controlled in your experiment? 

I just created three new environments, `scipy17`, `scipy18`, and `scipy19` like:
```
conda create -n scipy19
conda activate scipy19
conda install -c conda-forge python=3.9 numpy=1.21 mkl=2021.4 scipy=1.9 python
```
(changing the SciPy version number as appropriate).

Running your script, I got:
```
1.05 s ± 21.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)  # 1.7.3
1.07 s ± 14.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)  # 1.8.1
1 s ± 25.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)  # 1.9.1
```

**Comment by evfro** [comment]
@mdhaber thanks, I haven't checked BLAS/LAPACK versions actually.

Here're the related packages from the two main environments I compared:

### SP17
```
blas                      2.108                       mkl    conda-forge
blas-devel                3.9.0                     8_mkl    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
mkl                       2020.4             h726a3e6_304    conda-forge
numpy                     1.21.4           py39hdbf815f_0    conda-forge
scipy                     1.7.3            py39hee8e79c_0    conda-forge
```

### SP19
```
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_2    conda-forge
numpy                     1.21.4           py39hdbf815f_0    conda-forge
scipy                     1.9.0            py39h8ba3f38_0    conda-forge
```

So, the env with more recent scipy uses openblas and no mkl (in both cases I used mamba-forge for installation, and it seems that they switched from mkl to openblas sometime in between the two environments were created). I'll need to rerun my tests then. I'll post the results when finish.

**Comment by tupui** [comment]
Agreed, thanks @akhmerov for the help 🚀 

@evfro thank you for the initial report. Feel free to comment further. We could reopen in the future if need be.
