### ISSUE TITLE
ENH: Vectorized spline interpolation

### ISSUE THREAD

**Issue by vnmabus** [scipy/scipy#16920]
### Is your feature request related to a problem? Please describe.

I would want to be able to do curve interpolation using splines at several curves/surfaces/hypersurfaces (measured at the same points) simultaneously. Currently I think the only way to do this is with a Python loop, which seems slower than necessary.

### Describe the solution you'd like.

Being able to pass a ND-array to spline functions (and maybe an optional `axis` argument) to perform vectorized interpolations.

### Describe alternatives you've considered.

Using a for loop, but it makes things slower.

**Comment by ev-br** [comment]
Most spline functionality (make_interp_spline, monotone interp plants, cubic spline etc, and RGI/interpn) support data with trailing dimensions. What are the limitations you are facing?

**Comment by vnmabus** [comment]
Hum, currently my code uses `PchipInterpolator`/`UnivariateSpline`, `RectBivariateSpline` and `RegularGridInterpolator` depending on the dimension. These are not documented as accepting additional dimensions AFAIK. Are you saying that the low-level API has support for this?

**Comment by ev-br** [comment]
y: ndarray
A 1-D array of real values. y’s length along the interpolation axis must be equal to the length of x. **If N-D array, use axis parameter to select correct axis.**

https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.PchipInterpolator.html

**Comment by ev-br** [comment]
UnivariateSpline / RectBivariateSpline : better use make_interp_spline/BSpline in 1D and RGI in d>1.

**Comment by vnmabus** [comment]
> UnivariateSpline / RectBivariateSpline : better use make_interp_spline/BSpline in 1D and RGI in d>1.

Do they have the same results? In other words, are they different implementations of the same spline method?

**Comment by ev-br** [comment]
Not necessarily because `*Spline` objects wrap FITPACK, so these are technically smoothing splines with FITPACK's automatic knot placement. These are really not recommended for use in new code unless you really do smoothing (and then prefer the functional interface of `splrep` and wrap the result into a BSpline). See gh-16707 for an overview (and a user review would be useful).

**Comment by ev-br** [comment]
OK, ISTM the functionality requested is already there, better user documentation is certainly welcome, and one improvement is tracked at gh-16707. I'll close this issue, but feel free to continue discussing.
