### ISSUE TITLE
BUG: scrollbar not visible in docs

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#16944]
### Describe your issue.

The browser's scrollbar on the right is not visible when it is toggled by mouseover. I do not see the same behaviour for example in the NumPy docs which also use the pydata theme, so probably related to SciPy itself. To reproduce, just go to the docs page and hover over your browser's scrollbar.

Browser: Chrome

Scrollbar not toggled:

![image](https://user-images.githubusercontent.com/40656107/187843426-60ee180d-7d60-400d-bcb8-fe6e65300122.png)

Scrollbar toggled:

![image](https://user-images.githubusercontent.com/40656107/187843411-107f98f1-b743-4dcd-a27e-096e6e025ca3.png)

### Reproducing Code Example

```python
not applicable
```

### Error message

```shell
not applicable
```

### SciPy/NumPy/Python version information

not applicable

**Comment by tupui** [comment]
Thanks @dschmitz89. This will be fixed with the new version of the theme in #16660
