### ISSUE TITLE
BUG: error from `scipy.stats.mode` with `NaN`s, `axis != 0`, `keepdims=False`, and `nan_policy="omit"`

### ISSUE THREAD

**Issue by djmannion** [scipy/scipy#16952]
### Describe your issue.

`scipy.stats.mode` raises an error when called with a particular combination of arguments:

* multidimensional `a` that has one or more `NaN` values
* `axis` is not `0`
* `keepdims=False`
* `nan_policy="omit"`

The error seems to be specific to this combination.

### Reproducing Code Example

```python
import numpy as np
import scipy.stats

data = np.ones((4, 3))
data[0, 0] = np.nan

result = scipy.stats.mode(
    a=data,
    axis=1,
    keepdims=False,
    nan_policy="omit",
)
```

### Error message

```shell
Traceback (most recent call last):
  File "/home/damien/venv_study/scipy/bug.py", line 12, in <module>
    result = scipy.stats.mode(
  File "/home/damien/venv_study/scipy/scipy/build-install/lib/python3.9/site-packages/scipy/stats/_stats_py.py", line 618, in mode
    return mstats_basic._mode(a, axis, keepdims=keepdims)
  File "/home/damien/venv_study/scipy/scipy/build-install/lib/python3.9/site-packages/scipy/stats/_mstats_basic.py", line 352, in _mode
    return ModeResult(*output)
TypeError: <lambda>() takes 3 positional arguments but 5 were given
```

### SciPy/NumPy/Python version information

1.10.0.dev0+1772.07fc190 1.23.2 sys.version_info(major=3, minor=9, micro=13, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
Thanks for the report. This is fixed in gh-16954 and should be backported in 1.9.2.

**Comment by djmannion** [comment]
Great, thank you!
