### ISSUE TITLE
BUG:  't_span' is illustrated as 2-tuple of floats in scipy‘s documention, but which is always defined as  array_like in examples

### ISSUE THREAD

**Issue by tsinglinrain** [scipy/scipy#16978]
### Describe your issue.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html#scipy.integrate.solve_ivp

We can notice that 't_span' is illustrated as 2-tuple of floats in scipy‘s documention.

> **t_span: _2-tuple of floats_**
> Interval of integration (t0, tf). The solver starts with t=t0 and integrates until it reaches t=tf.

Then, the example is show below.

> from scipy.integrate import solve_ivp
> 
> def exponential_decay(t, y): return -0.5 * y
> 
> sol = solve_ivp(exponential_decay, [0, 10], [2, 4, 8])
> 
> print(sol.t)

However, in third line of the above paragraph ,we use [0, 10] as 't_sapn', which is array_like.

### Reproducing Code Example

```python
from scipy.integrate import solve_ivp
def exponential_decay(t, y): return -0.5 * y
sol = solve_ivp(exponential_decay, [0, 10], [2, 4, 8])
print(sol.t)
```

### Error message

```shell
t_span2-tuple of floats
Interval of integration (t0, tf). The solver starts with t=t0 and integrates until it reaches t=tf.
```

### SciPy/NumPy/Python version information

1.9.1 1.23.1 sys.version_info(major=3, minor=10, micro=4, releaselevel='final', serial=0)

**Comment by Femme-js** [comment]
Hi @tupui !

Can I pick this up?

**Comment by tupui** [comment]
Hi @Femme-js not really, as you can see, there is already a PR opened. We do not want competing work as well as to not waste review resources.

**Comment by Femme-js** [comment]
Sure, Thanks!
