### ISSUE TITLE
scripy.sparse.linalg. cgs / cg / bicg   has wrong results (?)  with  complex  linear operator    

### ISSUE THREAD

**Issue by MR4LEAF** [scipy/scipy#16979]
https://github.com/scipy/scipy/blob/2e5883ef7af4f5ed4a5b80a1759a45e43163bf3f/scipy/sparse/linalg/_isolve/iterative.py#L412

Not only cgs can not support the linear equation of complex numbers ( using linear operator) 

Those are claimed to support (such as cg, bicg) also do not support complex

**Comment by MatteoRaso** [comment]
Can you post the code that caused the problem?

**Comment by MR4LEAF** [comment]
(1)  Afun= lambda x: At(A(x))
(2) AtA= spla.LinearOperator(shape=(n,n),matvec= Afun)
(3) x2, info = spla.cg(A=AtA2, b=np.imag(z0), x0=np.imag(x0), tol=1e-05, maxiter=5, M=None, callback=None,atol=None)

Here At， A is also defined using lambda. We can explain it： A is a matrix m×n,  At is a matrix nxm,  x is a vector n×1
At，A, x  are all complex


Line 3 can work out, but the results are wrong.  others such as bicg can not support the Lin3 expression (do not why ?)

**Comment by tupui** [comment]
@MR4LEAF please follow our template for the issue. We need a clear minimal reproducible example with all variables defined, what you expected numerically, etc.

**Comment by MR4LEAF** [comment]
MATLAB version:

function example()

%%
dims= [128,128];
image= randn(dims);
image= image.*exp(1j*image);

%% fft2
ampl_fft= fft2(image)/sqrt(numel(image));

image_true= sqrt(numel(image))*ifft2(ampl_fft);

e1= norm(image- image_true,'fro');

%% iteration
Afun= @(x) getfft(x,dims);

sol=cgs(@(x) Afun(x),ampl_fft(:),1e-3,30,[],[], image(:) + 0.01*randn(numel(image),1));
x0= sol;
%% 
e2= norm(x0-image(:),2);

%
figure(1);clf
plot(e1,'b*');hold on;grid on
plot(e2,'rs')

function y= getfft(x,dims)
x_matrix= reshape(x,dims);
y_matrix= fft2(x_matrix)/sqrt(dims(1)*dims(2));
y= y_matrix(:);
end

end

**Comment by tupui** [comment]
@MR4LEAF thank you but can you also show the output of both? Some people don't have access to Matlab.
