### ISSUE TITLE
BUG: [issue in scipy.optimize.shgo, for COBYLA's minimizer_kwargs in scipy.optimize._shgo.py]

### ISSUE THREAD

**Issue by thibaudrosin** [scipy/scipy#16971]
### Describe your issue.

In file scipy.optimize._shgo.py on line 557 in the declaration of solver_args, the solver method's specific arguments, the 'catol' as one of COBYLA's method specific argument is missing, leading this argument to be removed on line 584:
" _restrict_to_keys(self.minimizer_kwargs['options'],
                          self.min_solver_args + ['ftol'])"
Therefore the catol args is reset to its default value when cobyla is called upon each value of the minimizer pool (same issue with 'rhobeg' argument).

Please fix this in the next patch,
Have a good day.
![issue_coybla_args_in_shgo](https://user-images.githubusercontent.com/67007859/188654988-ca31db08-ec2b-434d-971f-c16e880aa457.png)

See attached example, print the catol value used in cobyla minimizer compared with the 0.05 catol args passed as argument in the minimizer_kwargs of shgo.

### Reproducing Code Example

```python
import numpy as np
from scipy.optimize import shgo


def eggholder(x):
    return (-(x[1] + 47) * np.sin(np.sqrt(abs(x[0]/2 + (x[1]  + 47))))
            -x[0] * np.sin(np.sqrt(abs(x[0] - (x[1]  + 47)))))

bounds = [(-512, 512), (-512, 512)]

def cons(x):
    return x[0] - 0

res_optim = shgo(func=eggholder,
                     bounds=bounds,
                     constraints = {'fun': cons, 'type': 'ineq'},
                     minimizer_kwargs={
                         'method': 'COBYLA',
                         'options': {
                             'rhobeg': 5,
                             'tol': 5e-1,
                             'catol': 0.05
                         }
                     },
                     n=200,
                     iters=5,
                     options={
                         'f_tol': 5e-5,
                         'disp': True
                     })
```

### Error message

```shell
No error
```

### SciPy/NumPy/Python version information

1.8.1 1.23.1 sys.version_info(major=3, minor=10, micro=1, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Thank you @thibaudrosin. We will see to have this in our big re-write #16313
