### ISSUE TITLE
ENH: Is there any equivalent of matlab's interpft() function in spicy? 1d fft interpolation.

### ISSUE THREAD

**Issue by patilabhay679** [scipy/scipy#16981]
### Is your feature request related to a problem? Please describe.

https://in.mathworks.com/help/matlab/ref/interpft.html
I mean how to fit periodic data like , x* sin(x) and shown on above link in python?

**Comment by tupui** [comment]
Hi @patilabhay679, thanks for reporting. I am afraid we don't have the bandwidth to answer user questions. Please use StackOverflow or other forums, issues are reserved to bug or feature requests.

**Comment by patilabhay679** [comment]
I mean, I have searched on major forums, didn't got any similar function in scipy and numpy.  Wouldn't it  be great if you guys consider adding this function in ? It would really people like me who are doing machine learning on periodic data.

**Comment by andyfaff** [comment]
@patilabhay679 would you be interested in developing such a feature for scipy? If so, then it may be worth approaching the scipy-dev mailing list and asking if there's any appetite for adding it.

**Comment by tupui** [comment]
> Wouldn't it be great if you guys consider adding this function in ?

We have strict requirements for adding new things in SciPy. To assess this we at least need to have all the information from the issue template filled out... This needs to be strongly motivated, applicable to multiple fields, be standard, etc. And as suggested by Andrew, it needs to go through the mailing list.

I am happy to reopen the issue if there are more elements and it's indeed something we want to consider.

**Comment by ev-br** [comment]
To add to what Pamphile and Andrew already said, we'd want to see some details of what's currently lacking. I mean, for just periodic signals, `make_interp_spline(x, y, bc_type="periodic")` or `CubicSpline(x, y, bc_type="periodic")` work fine. If you really want to interpolate in the Fourier space, just do the FFT yourself and interpolate the result, how does this not do what you need etc.

**Comment by patilabhay679** [comment]
the splines and polynomial approximations won't last after the domain of training dataset. Yes you can interpolate between the fitted curve, but what about extrapolating? 
I mean for f(x) = x*sin(x) [ it is just demonstration. in practice i don't know the function.]
![image](https://user-images.githubusercontent.com/72353341/189352248-df7b60f1-817c-4c2e-9075-5b72c7de1bf0.png)

if I have trained the model from x = 0 and x = 12, any polynomial or spline approximation will give relevant result between [0,12].
what if I want f(x=40) ?

![image](https://user-images.githubusercontent.com/72353341/189356528-a14d05e5-9069-48d9-b5ae-47c586e00ad0.png)
it's diverging like nuts.

**Comment by patilabhay679** [comment]
can someone give me the documentation or  actual code of interpft() in matlab.

**Comment by ev-br** [comment]
That's a separate (known) issue. Which, BTW, `bc_type="periodic"` does not have, when it's applicable. 

Like Pamphile said, we do not really have the bandwidth for the user queries here, so you are unlikely to get help on the issue tracker for "can someone give me the code" type requests. Prefer Stackoverflow or scipy-user mailing list for this.

If, like Andrew said, you have an idea of how this can be implemented and are willing to argue for inclusion into scipy, please formulate the proposal. We will certainly consider it!

I'd start from the do-it-yourself FFT + interpolation, like I said above.
