### ISSUE TITLE
BUG: Documentation for Bessel functions wrong about array_like order parameter

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#16993]
### Describe your issue.

The docs state that `jv` and friends accept an array_like argument for the order parameter.

This only works if the functions are evaluated at a single point, not if an array is passed for the `z` parameter.

![image](https://user-images.githubusercontent.com/40656107/189436467-32bbe1a2-f407-4f0b-a6e0-19858c5fdd25.png)

### Reproducing Code Example

```python
import numpy as np
from scipy.special import jv

z=np.linspace(0., 10., 1000)
y = jv([0., 1.], z)
```

### Error message

```shell
ValueError: operands could not be broadcast together with shapes (2,) (1000,)
```

### SciPy/NumPy/Python version information

1.6.3 1.20.3 sys.version_info(major=3, minor=9, micro=4, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment]
`jv` is a ufunc, and all ufuncs broadcast their arguments.  The problem with the example `jv([0., 1.], z)` is that `[0., 1.]` has shape (2,) and `z` has shape (1000,).  These shapes are not compatible for broadcasting. Instead, try something like this:
```
In [6]: z = np.linspace(0., 10., 1000)

In [7]: y = jv([[0], [1]], z)

In [8]: y.shape
Out[8]: (2, 1000)
```
The array-like input `[[0], [1]]` has shape (2, 1), and this is compatible for broadcasting with `z`, resulting in the array `y` with shape (2, 1000).

**Comment by dschmitz89** [comment]
Ah okay. Will add an example about that to the docs. Other people will be as confused as me probably.
