### ISSUE TITLE
Unpickled and deepcopied distributions do not use global random state

### ISSUE THREAD

**Issue by JelleAalbers** [scipy/scipy#16998]
scipy.stats distributions participate in numpy's global random state, unless the user initializes them with a custom random state (using the `seed` argument to `__init__`, or by setting `.random_state`).

Currently however, a distribution (frozen or not) that is unpickled or deepcopied will always use an independent random state:

```python
from copy import deepcopy
import numpy as np
from scipy import stats

a = deepcopy(stats.norm)
# We can set the seed...
np.random.seed(42)
# ... but this is still not deterministic (across sessions)
a.rvs()
```

and

```python
import pickle
a_pickle = pickle.dumps(stats.norm(0, 2))

# This always produces the same value
# (unless the pickle is re-made)
pickle.loads(a_pickle).rvs()
```

This behaviour makes sense for distributions created with a custom random seed, but not for the default distributions that should use numpy's global random state. In fact, pickled/deepcopied distributions copy the global random state, causing another potential surprise:

```python
a = stats.norm()
# Even though this copies a different stats.norm() instance...
b = deepcopy(stats.norm())
# ... these draws give the same result:
assert a.rvs() == b.rvs()
```

I could easily be wrong, but I think this is a bug, not the intended behaviour:
  * The [rv_continuous docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.html) say that distributions use the numpy singleton RandomState by default. After a copy/unpickle, one would expect that behaviour -- using the active singleton RandomState -- to be preserved. Why would a distribution that lacked a private random state before suddenly have one after an unpickle?
  * This is surprising for users unfamiliar with PRNGs and random state objects. While relying on a global random state is discouraged nowadays (to avoid exactly these kind of problems), it is still the default in many codebases, and a sin I must myself also still confess to regularly :-)

If this is the intended behaviour, maybe it is worth a caution somewhere in the documentation?

**Comment by tupui** [comment]
Agreed. In the new interface we will not allow the use of the global state to avoid things like this (and also because we should not do that anymore per NEP19).
