### ISSUE TITLE
BUG: nightly wheel authentication token isn't valid

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#17000]
### Describe your issue.

@rgommers, the authentication token for uploading the nightly wheels isn't valid. 
https://github.com/scipy/scipy/actions/runs/3030982137

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
Error:  ('Authentication token does not have the sufficient scope to perform this action expected: api:write', 401)
Error: Process completed with exit code 1.
```

### SciPy/NumPy/Python version information

N/A

**Comment by rgommers** [comment]
I had given it scope `pypi:upload`, which seems like the sensible thing to add. Guess it needs both.

**Comment by andyfaff** [comment]
Once you've changed the scope then you can manually trigger the workflow.

**Comment by rgommers** [comment]
I've checked the scope of the corresponding numpy token, it is:
```

    api
    Allow all API operations
    pypi:upload
    Allow uploads to Standard Python repositories
```
I'll do the same here.

**Comment by andyfaff** [comment]
The wheels are now uploading to https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/. I think that the nightly wheels site could do with a bit of a purge; there appears to be a tonne of wheels available there dating back to 1.8 and links to 1.5 pages.

**Comment by rgommers** [comment]
Great. I'll do a cleanup now.

**Comment by rgommers** [comment]
As I expected, it will prefer `+1624` when you run
```
pip install -i https://pypi.anaconda.org/scipy-wheels-nightly/simple scipy
```

**Comment by rgommers** [comment]
And you can't select the other wheels, because the `+1624` is a more specific version of the exact version number of the `1.10.0.dev0` wheels. So let's delete them. If it's broken though, the pre-release testing needs to be fixed asap or downstream projects will see breakage given that there are no suitable wheels left.

**Comment by charris** [comment]
> The links cannot be deleted from the Anaconda UI,

I haven't had a problem doing it. Maybe a permission problem? ISTR needing more permission to see the delete button.

**Comment by rgommers** [comment]
There's one wheel missing above, for Python 3.10 `aarch64`. CI is still running, it's very slow because of QEMU. Once it's complete I will pull the trigger here.

**Comment by rgommers** [comment]
Done now - let's see if anything breaks ....

**Comment by rgommers** [comment]
Okay, I bit the bullet, removed the need for manual confirmation from the anaconda CLI, and wrote a script. https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/ is completely cleaned up now.
