### ISSUE TITLE
Negative numbers for pmean

### ISSUE THREAD

**Issue by realjanpaulus** [scipy/scipy#17010]
## Problem description
I would like to use the new [pmean](http://scipy.github.io/devdocs/reference/generated/scipy.stats.pmean.html) implementation to calculate the generalized mean for **word embeddings** to create **sentence embeddings**. The idea is taken from the paper [Concatenated Power Mean Word Embeddings as Universal Cross-Lingual Sentence Representations](https://arxiv.org/pdf/1803.01400.pdf). Currently, I'm using my own implementation:

```python 
def generalized_mean(vals: np.array, p: int = 1) -> np.real:
    """Calculate the general mean (see: https://en.wikipedia.org/wiki/Generalized_mean).

    Notes
    -----
    p = -1: harmonic mean
    p = 0: geometric mean
    p = 1: arithmetic mean

    Code taken and adapted from:
    https://github.com/UKPLab/arxiv2018-xling-sentence-embeddings/blob/master/model/sentence_embeddings.py

    Parameters
    ----------
    vals : np.array
        Array with values.
    p : int, optional
        Parameter to represent different means, by default 1.

    Returns
    -------
    np.real
        Generalized mean as a real number.
    """
    return np.power(np.mean(np.power(np.array(vals, dtype=np.complex128), p), axis=0), 1 / p).real
```

This implementation currently doesn't work with values like `p=0` or `p=-1`, so my plan was to switch to the scipy implementation of the generalized mean. The main problem here is, that it isn't defined for negative numbers, see [code](https://github.com/scipy/scipy/blob/06da9ee65cdee4a8aa036767489bfc5a030527f4/scipy/stats/_stats_py.py#L493-L504). But word embeddings typically have negative numbers, e.g. one embedding could loook like this:

```python 
embedding = [
    [0.10901299864053726, 0.15312300622463226, -0.24146799743175507, 0.2262050062417984, 0.11391100287437439, ...], 
    ...
]
```
## Question

Are there any plans to integrate an implementation of `pmean` for negative numbers? Or are there alternative solutions to my problem?

**Comment by tupui** [comment]
Hi @realjanpaulus, thank you for reporting. The issue is that to generalize with any exponent we would need to involve complex values. By definition, these means also need to have positive values. I don't think we would want to go around that.
