### ISSUE TITLE
BUG: Small oversight in sparse.linalg.lsmr?

### ISSUE THREAD

**Issue by mreineck** [scipy/scipy#17012]
### Describe your issue.

While reading the scipy LSMR implementation, this line (https://github.com/scipy/scipy/blob/06da9ee65cdee4a8aa036767489bfc5a030527f4/scipy/sparse/linalg/_isolve/lsmr.py#L305) caught my eye.

How can `x=b` ever be valid in this kind of routine? Both have different shapes in the general case, or am I missing something?

The test case below shows that the shape of the returned array changes depending on the values in `b`. I think this is wrong...

### Reproducing Code Example

```python
import numpy as np
import scipy.sparse.linalg

A=np.ones((10,1))
x0=np.ones(1)

x=scipy.sparse.linalg.lsmr(A, b=np.ones(10), x0=x0)[0]
print(x.shape)
# (1,)


x=scipy.sparse.linalg.lsmr(A, b=np.zeros(10), x0=x0)[0]
print(x.shape)
# (10,)
```

### Error message

```shell
No error message, but the shape of the result is different depending on the provided RHS.
```

### SciPy/NumPy/Python version information

1.8.1 1.21.5 sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)

**Comment by rgommers** [comment]
Thanks for the report @mreineck. Yes, that does look wrong. Perhaps the author meant something like `x[:] = b`, because if the norm of `b` is zero then `x` all zeros should be a valid solution.

**Comment by mreineck** [comment]
Yes, that should work.
(It's an extreme corner case, and I'm not surprised that this hasn't caused problems so far ... if `b[:]==0` you typically don't need a solver :-)
