### ISSUE TITLE
ENH: Generalized Sylvester equation solver

### ISSUE THREAD

**Issue by paulgomme** [scipy/scipy#17028]
### Is your feature request related to a problem? Please describe.

Yes, it's a problem in that I'm an economist who would like to be able to compute second-order approximations to a model. I know what to do for a generalized Sylvester equation. The matrix algebra looks like:

     A * R - L * B = scale * C
     D * R - L * E = scale * F

The matrices A, B, C, D, E, F are inputs; R and L are outputs.

The above differs from what scipy.linalg.solve_sylvester will solve:

     A * X - X * B = C

where A, B and C are inputs and X is the output.

### Describe the solution you'd like.

A scipy function that ultimately calls LAPACK's routine TGSYL.

### Describe alternatives you've considered.

I've looked at cvxopt but it doesn't include the ability to call TGSYL.

I could continue working in Fortran, but really would like to move this work to Python.

**Comment by ilayn** [comment]
We need to provide Python wrappers for this which would take some time but in the meantime you can use `scipy.linalg.cython_lapack.dtgsyl` within Cython environment if you know your way around with Cython.

**Comment by paulgomme** [comment]
Thanks for the pointer to Cython.

**Comment by dschmitz89** [comment]
Can this be closed since the `tgsyl` wrapper is available after merging #18404 ?

**Comment by ilayn** [comment]
Indeed
