### ISSUE TITLE
New CI failures in `sparse` with nightly numpy

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#17033]
If you have submitted a pull request recently, you probably noticed some new failures in the Azure job `prerelease_deps_coverage_64bit_blas` that are unrelated to your changes:

```
=========================== short test summary info ============================
FAILED scipy/sparse/tests/test_base.py::TestCOO::test_reshape_copy - Assertio...
FAILED scipy/sparse/tests/test_base.py::TestCOONonCanonical::test_reshape_copy
FAILED scipy/sparse/tests/test_base.py::Test64Bit::test_resiliency_limit_10[TestCOO-test_reshape_copy]
FAILED scipy/sparse/tests/test_base.py::Test64Bit::test_no_64[TestCOO-test_reshape_copy]
FAILED scipy/sparse/tests/test_base.py::Test64Bit::test_resiliency_random[TestCOO-test_reshape_copy]
FAILED scipy/sparse/tests/test_base.py::Test64Bit::test_resiliency_all_32[TestCOO-test_reshape_copy]
FAILED scipy/sparse/tests/test_base.py::Test64Bit::test_resiliency_all_64[TestCOO-test_reshape_copy]
```

This job is the one that uses a "nightly" NumPy build.  The failures are the result of a [recent change](https://github.com/numpy/numpy/pull/21995) in NumPy; see https://github.com/numpy/numpy/pull/21995#issuecomment-1249447631 for a description of how the NumPy change breaks the tests in `scipy.sparse`.

Based on the follow-up comment and the tests in that PR that were approved, it looks like this is an intentional change that is not considered a backwards compatibility break.  It changes behavior, but it is apparently behavior that was never guaranteed to always remain the same.

I think we'll be able to work-around the NumPy change pretty easily.

**Comment by mdhaber** [comment]
There are also harmless failures in `stats` that should be fixed by gh-17034.
