### ISSUE TITLE
ENH: DOC: add links to reference LAPACK docs for scipy.linalg.lapack

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#17040]
### Is your feature request related to a problem? Please describe.

`scipy.linalg.lapack` docs are currently only helpful when the correct routine is already known. As I assume that no one in the world has time to write helpful docstrings for all of these functions, I thought it might be helpful to at least link into reference lapack's docs.

### Describe the solution you'd like.

Example: [scipy.linalg.sgbsv](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lapack.sgbsv.html#scipy.linalg.lapack.sgbsv) would include a link to the [Netlib doc](https://netlib.org/lapack/explore-html/dc/db2/group__real_g_bsolve_ga3656935309a19ed624052103572a4a47.html) of this function.

### Additional context (e.g. screenshots, GIFs)

Automatically generating the URLs to Netlib is not possible probably from what I see :/ .

**Comment by ilayn** [comment]
The docs are unfortunately auto generated by `f2py` tool and because Netlib team is using `doxygen` for generating their own documentation, the links are all garbled to be referenced properly. Hence we can't automate it unless there is some logic behind those hash looking urls. This is probably something for the Netlib team I'm afraid.

**Comment by melissawm** [comment]
We could add a general link to the Netlib docs if not the main docs for the function. There may be a way to find a logic behind these links but I'm not sure how to navigate their folder structure.

Examples:
- https://netlib.org/lapack/explore-html/da/da7/sgbsv_8f.html 
- https://netlib.org/lapack/explore-html/dd/dc2/dgbsv_8f.html

**Comment by dschmitz89** [comment]
This seems unfeasable. Unless there are objections, I will close in a few days.
