### ISSUE TITLE
BUG: Cannot get rid of Deprecation Warning with cKDTreeNode

### ISSUE THREAD

**Issue by davelajoie** [scipy/scipy#17045]
### Describe your issue.

Cannot get ride of Deprecation Warning with cKDTreeNode
As cKDTreeNode is not exposed at the root of scipy.spatial

### Reproducing Code Example

```python
import scipy.spatial.ckdtree

scipy.spatial.ckdtree.cKDTree()     # fixable!
scipy.spatial.ckdtree.cKDTreeNode() # not fixable!

# to fix it,as the Deprecation Warning states

import scipy.spatial
scipy.spatial.cKDTree() # fixes it!
scipy.spatial.cKDTreeNode() # errors out

The problem is that cKDTreeNode is not exposed in scipy.spatial
python -c "import scipy.spatial; print( scipy.spatial.cKDTreeNode )"
AttributeError: module 'scipy.spatial' has no attribute 'cKDTreeNode'
```

### Error message

```shell
DeprecationWarning: Please use `cKDTree` from the `scipy.spatial` namespace, the `scipy.spatial.ckdtree` namespace is deprecated.

DeprecationWarning: Please use `cKDTreeNode` from the `scipy.spatial` namespace, the `scipy.spatial.ckdtree` namespace is deprecated.
```

### SciPy/NumPy/Python version information

1.9.1 1.23.3 sys.version_info(major=3, minor=9, micro=13, releaselevel='final', serial=0)

**Comment by davelajoie** [comment]
as an information, I am using that class (cKDTreeNode), as it is returned by the code, so I am doing type checking. I checked and cKDTreeNode is not derived from cKDTree, otherwise I would just used cKDTree.

**Comment by tupui** [comment]
Thank you for the precision @davelajoie. Yes since the class is returned it does make sense that it's made publicly available.

Are you interested in making a PR?

**Comment by davelajoie** [comment]
Sure, but I will need to get up to speed on how to submit a PR first :) Maybe is the my time to get into open source software contributions after all...

**Comment by tupui** [comment]
Use `main` to create a new branch from. And then it should be a PR against `main` as well.

**Comment by davelajoie** [comment]
Just checked @tupui and the main branch might not have the problem at all... looks like I should be able to move to a more recent version. please can you confirm?

**Comment by tupui** [comment]
What do you mean? On `main` the following raises and error `from scipy.spatial import cKDTreeNode`

**Comment by sturlamolden** [comment]
One is not supposed to instantiate ```cKDTreeNode``` like that. It is returned from the ```.tree``` attribute of a ```cKDTree``` instance. Using it in any other way would probably result in a segfault.

**Comment by davelajoie** [comment]
Actually the repro steps are used to illustrate the problem. in my case I am *not* creating instance but instead using it to validate an function argument 

```
if not isinstance( inTreeObj, (scipy.spatial.cKDTree,scipy.spatial.ckdtree.cKDTreeNode)):
    <do something>
```

just the fact that I am referencing the class ( not creating an instance ), I get the deprecation message.

**Comment by sturlamolden** [comment]
In that case it is not simply a matter of adding ```"cKDTreeNode"``` to ```__all__```. We must change the ```cKDTreeNode``` object to make sure it is inert when instantiated outside the ```cKDTree``` Cython code.

**Comment by sturlamolden** [comment]
But I suppose we can do that.

**Comment by j-bowhay** [comment]
@sturlamolden what do you think is the right approach here? I have been working on tidying up the error messages emitted from modules that were not intended to be public eg. `scipy.spatial.ckdtree`. For example, https://github.com/scipy/scipy/pull/18968 addressed similar issues for the optimize module. Here there was a similar issue:
```
In [3]: from scipy.optimize.optimize import MemoizeJac
<ipython-input-3-ad2abe888e13>:1: DeprecationWarning: Please use `MemoizeJac` from the `scipy.optimize` namespace, the `scipy.optimize.optimize` namespace is deprecated.
```

However `MemoizeJac`  is not in the optimize `__all__`. It was decided that this was never meant to be public so we changed the message to:
```
In [1]:  from scipy.optimize.optimize import MemoizeJac
<ipython-input-1-ad2abe888e13>:1: DeprecationWarning: `scipy.optimize.optimize.MemoizeJac` is deprecated along with the `scipy.optimize.optimize` namespace. `scipy.optimize.optimize.MemoizeJac` will be removed in SciPy 1.13.0, and the `scipy.optimize.optimize` namespace will be removed in SciPy 2.0.0.
  from scipy.optimize.optimize import MemoizeJac
```

Would you be happy with a similar fix here to resolve this since it seems `cKDTreeNode` was not really meant for public consumption?
