### ISSUE TITLE
Scipy QZ documentation

### ISSUE THREAD

**Issue by amitvarshney00** [scipy/scipy#17053]
The scipy.linalg.qz function implements generalized Schur decomposition for a pair of matrices `A`, `B` such that 
`(A, B) = (Q @ AA @ Z*, Q @ BB @ Z*)`, where `AA` is quasi upper triangular and `BB` is upper triangular. The documentatian says for the matrix `AA` "1x1 blocks correspond to real generalized eigenvalues and 2x2 blocks are **‘standardized’** by making the corresponding elements of BB have the form: [[a 0], [0, b]]". I was wondering if someone is aware of how this standardization is done?

**Comment by ilayn** [comment]
This is coming from the documentation of the LAPACK routines underneath. See for example, [`dgges`](https://netlib.org/lapack/explore-html/d9/d8e/group__double_g_eeigen_ga8637d4b822e19d10327ddcb4235dc08e.html). I don't remember the exact details but probably this is done in `dhgeqz` (or something like that) step. You can often follow the code to get the gist of the algorithm. You might get a more up-to-date information if you ask this on https://scicomp.stackexchange.com/

**Comment by amitvarshney00** [comment]
Hi @ilayn - Thank you. I will post the question on https://scicomp.stackexchange.com/
