### ISSUE TITLE
ENH: Robust and fast numerical derivative for error propagation

### ISSUE THREAD

**Issue by HDembinski** [scipy/scipy#17059]
### Is your feature request related to a problem? Please describe.

I am a particle physicist by trade, and error propagation is very important for us. We need to propagate errors through complex functions that may execute arbitrary code and whose analytical behavior we do not understand in detail. Therefore, it is important to have a reliable and fast black-box derivative that just works and does not require expert knowledge about the function.

### Describe the solution you'd like.

I wrote the [jacobi library](https://github.com/hDembinski/jacobi) ([docs](https://hdembinski.github.io/jacobi/)) which I would like to include in scipy. Jacobi is an implementation of John d'Errico's DERIVEST algorithm for matlab written from scratch. Jacobi has remarkable features that make it ideal for this use case. It is a fast, safe-to-use, black-box numerical derivative for many applications. I think it is a great match for a foundational scientific library like scipy. On top of the derivative, I wrote a function `propagate` which uses the derivative to do error propagation for any vector-valued function.

Jacobi uses an adaptive algorithm to compute the numerical derivative. It converges fast if the derivative is trivial (constant or linear) and it can handle functions which have poor numerical accuracy (they are numerically noisy, use single precision arithmetic etc.). The amount of numerical noise is detected automatically and propagated into an error estimate for the derivative, which is computed alongside the derivative. This is fairly unique for such a library. By default, the algorithm runs until the error on the result does not improve anymore (usually when it reaches machine precision), but one can also set an accuracy target and jacobi will stop once the estimated error drops below this target.

jacobi uses polynomial extrapolation, which is a higher-order form of Richardson extrapolation. Thanks to extrapolation, it can compute numerical derivatives to machine precision. The polynomial fit also provides the error estimate on the extrapolated derivative.

jacobi is written in pure Python and the implementation is written in a concise way by me, a Python expert and author and maintainer of several open source Python and C++ libraries. I am also the designer and author of Boost Histogram in the Boost C++ project. Jacobi uses only 250 lines. It is very fast, too, because it uses numpy array math efficiently. It is faster than numdifftools by up to a factor of 2 to 1000, depending on the problem.

### Describe alternatives you've considered.

- **scipy.misc.derivative** is too difficult to use correctly. The step size `dx` has to be provided by the user, it is not determined automatically. I cannot run this function like a black box and get my derivative to machine precision, I need to know what I am doing and set the parameters `dx` and `order` to suitable values, which I can only do optimally if I already know a lot about my function and its implementation. jacobi is a black-box derivative. It just works, parameters like step size and order are determined automatically from an iterative analysis of the function response.
- **scipy.optimize.approx_fprime** or **scipy.optimize.approx_derivative** are not robust, cannot achieve machine precision unless "cs" step is used which is rarely possible in practice, and do not provide an error estimate. They call a low-order finite difference formula, which has sqrt(EPS) precision at best (unless "cs" step is used, which is rarely possible in practice), while jacobi often achieves EPS. They are not robust, because these algorithms cannot detect that the function is noisy; the step size that each algorithm selects to find the optimum between truncation error and round-off error is only valid for a function that calculates the correct result within a few ULPs. Non-trivial functions often do not achieve this. It is also possible that some part of the internal calculation is done in single precision, but the inputs and outputs are double precision. In that case, neither algorithm can detect the right step size. jacobi handles this case just fine, because it detects the precision of the calculation by probing the function response iteratively.
- **numdifftools** offers a black-box derivative, but it is neither robust nor fast. It does not provide an error estimate. The implementation is also much more complex than jacobi due to excessive use of code structuring.
- **automatic differentiation** libraries like JAX are very intrusive, this is bad. They cannot be integrated into an existing code base, one has to write the application around the AD library. Jacobi can be integrated into any application and it can calculate the derivative for any function, whatever the implementation of that function does (it could call into C or Fortran, use numba, etc.).

### Additional context (e.g. screenshots, GIFs)

Jacobi is not intended to provide first derivatives for numerical minimizers like those accessible via scipy.optimize.minimize. It is not a replacement for **scipy.optimize.approx_fprime** or **scipy.optimize.approx_derivative**. Numerical minimizers are designed to handle imperfect derivatives that can be computed very fast. Jacobi is not fast enough for those applications and too accurate.

Check out https://hdembinski.github.io/jacobi/ for plots and benchmarks that show how well jacobi works.

**Comment by mdhaber** [comment]
The license of the Matlab program appears to be the two-clause BSD (FreeBSD), which is compatible. 👍 I'll take a look.
Can you see a need for implementing other algorithms if we were to include this one? There was talk of a (`scipy.diff`)[https://github.com/scipy/scipy/issues/7457] subpackage a while ago (and long before that one, I think).

**Comment by HDembinski** [comment]
I rewrote the code from scratch using only the documentation of the algorithm, so the original license shouldn't be a concern, but like you said it is also compatible.

I agree with the API choice in https://github.com/scipy/scipy/issues/7457

**Comment by j-bowhay** [comment]
Have you considered https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.approx_fprime.html#scipy.optimize.approx_fprime

**Comment by HDembinski** [comment]
> Can you see a need for implementing other algorithms if we were to include this one?

No, I don't see that need. The precision, speed, and robustness of jacobi outperform other numerical algorithms known to me. It is possible to be faster than jacobi by sacrificing precision or robustness. I think we don't want to sacrifice robustness. jacobi also offers a tolerance keyword to trade precision against speed.

I have researched numerical derivatives for a long time and I haven't come across anything as good as DERIVEST/jacobi for this problem.

**Comment by HDembinski** [comment]
> Have you considered https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.approx_fprime.html#scipy.optimize.approx_fprime

@j-bowhay Thanks for reminding me, I added why approx_fprime is not an alternative to my initial statement.

**Comment by ev-br** [comment]
As a drive-by comment, when there's a comparison to other tools, it'd be nice to compare to `approx_derivative`. (I realize these two are very different)

**Comment by HDembinski** [comment]
My comments regarding `approx_fprime` and `approx_derivative` are the same, because those two functions despite some differences in implementation, fundamentally are based on the same concept. They do a single finite-step to compute the derivative, while jacobi uses several steps at different step lengths and extrapolates to zero step length.

**Comment by andyfaff** [comment]
Is that like Richardson extrapolation?

**Comment by HDembinski** [comment]
Polynomial extrapolation is generalized Richardson extrapolation. Richardson is linear extrapolation. Polynomial extrapolation uses a higher order polynomial.

**Comment by mdhaber** [comment]
This sounds great to me. 
Where do you think it belongs in SciPy? Do you think it deserves a new subpackage, `scipy.diff`?

**Comment by ev-br** [comment]
>Polynomial extrapolation is generalized Richardson extrapolation. Richardson is linear extrapolation. Polynomial extrapolation uses a higher order polynomial.

How do you select the defeee of this polynomial? What controls the extrapolation not going away from the data?

**Comment by HDembinski** [comment]
The degree of the polynomial is 3 and it is fitted with the last 4 values in a series where the step size is always reduced. For a smooth function, reducing the step size always improves the derivative until round-off error takes over. The algorithm iterates until the round-off error is dominant. There is no control that the extrapolation is going away from "the data" but you never have that guarantee. I cannot give you proof, but the algorithm works because convergence is basically guaranteed.

**Comment by laurent90git** [comment]
Is there a published paper on such an approach ?

**Comment by HDembinski** [comment]
John d'Errico wrote up the ideas on which I based my implementation, but I don't know of any publication.

**Comment by HDembinski** [comment]
> Where do you think it belongs in SciPy? Do you think it deserves a new subpackage, `scipy.diff`, or would it fit into an existing subpackage?

@mdhaber I am not sure what the best place would be. I think it should *not* go to scipy.optimize, to not create a false association with optimization for which the algorithm is not intended.

Perhaps it is reasonable to add a whole submodule like `scipy.diff`, assuming we probably want to add more functionality in the future. Right now, jacobi can only compute the jacobi matrix (first derivative). Eventually I want to also add the hessian as well, at the very least. In principle, one could also consider calculating even higher derivatives.

We could also discuss where the error propagation code should go that uses the jacobi matrix. `scipy.stats`?

**Comment by mdhaber** [comment]
I'd lean toward `scipy.diff`. The idea has been met favorably before - it was a Google Summer of Code project five years ago, but the code just didn't turn out to be something we could release publically. 

Just so that it's all in one place, here is some background reading:
- gh-2035
- [a fairly detailed `scipy.diff` proposal](https://github.com/scipy/scipy/wiki/Proposal:-add-finite-difference-numerical-derivatives-as-scipy.diff)
- [mailing list discussion](https://mail.python.org/archives/search?mlist=scipy-dev%40python.org&q=scipy.diff)
- gh-7457
- [SciPy 1.9.0 detailed roadmap ](https://docs.scipy.org/doc/scipy-1.9.0/dev/roadmap-detailed.html) calls for more extensive differentiation capabilisities 
- The [SciPy 1.1.0 roadmap](https://docs.scipy.org/doc/scipy-1.1.0/reference/roadmap.html#new-modules-under-discussion) was the last to mention `scipy.diff` by name

But I think you make a strong case for why this is different and superior in some ways to existing tools: very accurate derivatives for black-box (and potentially noisy) functions, IIUC.

Before we add a whole submodule, though, we'll need to hint at where it's going. Could you suggest what other functions and classes the submodule might have?

> We could also discuss where the error propagation code should go

Is that as simple as multiplying the derivatives by some finite errors on the input to calculate finite errors on the output?

**Comment by HDembinski** [comment]
> Is that as simple as multiplying the derivatives by some finite errors on the input to calculate finite errors on the output?

Yes, the math is simple: for a function y = f(x) where x and y can be vectors of arbitrary length (generalizing this, we could allow for arbitrarily shaped arrays x and y), one computes the Jacobian and then via C_y = J C_x J^T, where C_x is the covariance matrix (or in general a "tensor") of the input and C_y is the covariance matrix (or in general a "tensor") of the output.

The implementation of the propagate function in jacobi is a bit more complex to handle special cases, e.g. what if C_x or C_y are scalars. I decided to also cover the use-case where f has several independent arguments f(x, y, ...). This is convenient for the users, and the computation can be more efficient since we know that correlations between x and y are zero.

**Comment by mdhaber** [comment]
I can see why the error propagation code might belong in `stats`. On the other hand, it is a relatively simple calculation if you already have the Jacobian, so users will probably need it most often when computing the Jacobian with a feature in `scipy.diff`. From that perspective, I can see an argument for putting it in `scipy.diff`, too.

Would you be willing to write out a few thoughts on what you think a `scipy.diff` might look like in two years? I think people will want to see what besides the Jacobian code (and possibly this error propagation code) will go there before creating a new subpackaage. Then, I think we should send an email to the mailing list about it, and if there are no concerns, we can go ahead and implement it.

**Comment by j-bowhay** [comment]
> * **scipy.misc.derivative** is too difficult to use correctly. The step size `dx` has to be provided by the user, it is not determined automatically. I cannot run this function like a black box and get my derivative to machine precision, I need to know what I am doing and set the parameters `dx` and `order` to suitable values, which I can only do optimally if I already know a lot about my function and its implementation. jacobi is a black-box derivative. It just works, parameters like step size and order are determined automatically from an iterative analysis of the function response.
> * **scipy.optimize.approx_fprime** or **scipy.optimize.approx_derivative** are not robust, cannot achieve machine precision unless "cs" step is used which is rarely possible in practice, and do not provide an error estimate. They call a low-order finite difference formula, which has sqrt(EPS) precision at best (unless "cs" step is used, which is rarely possible in practice), while jacobi often achieves EPS. They are not robust, because these algorithms cannot detect that the function is noisy; the step size that each algorithm selects to find the optimum between truncation error and round-off error is only valid for a function that calculates the correct result within a few ULPs. Non-trivial functions often do not achieve this. It is also possible that some part of the internal calculation is done in single precision, but the inputs and outputs are double precision. In that case, neither algorithm can detect the right step size. jacobi handles this case just fine, because it detects the precision of the calculation by probing the function response iteratively.

Would the addition of `scipy.diff` replace these in the long term?

**Comment by lorentzenchr** [comment]
As info: I guess it was some other scipy issue or mailing list thread that mentioned https://github.com/maroba/findiff.

For several tests in scikit-learn, a better numerical derivative function would have been very convenient!

**Comment by HDembinski** [comment]
@mdhaber I would like to start working on this in the next week. Do you have any suggestions how to start? Should I write function stubs first so that we can review the structure or should I start with a copy of my existing Jacobi library and we start iterating from there?

**Comment by HDembinski** [comment]
@lorentzenchr mentioned FinDiff, which allows you to compute arbitrary orders of derivatives. Jacobi can only do first derivatives at the moment, although the algorithm should generalize to higher orders.

The key feature that Jacobi has and FinDiff seems to lack, is the robustness of the derivative against noise in the function, and that you can specify in advance how accurate you want the derivative to be with a tolerance. FinDiff uses higher order formulas and you can specify the accuracy by the order of the formula, but that does not tell you anything about the final tolerance of the derivative.

**Comment by mdhaber** [comment]
> Do you have any suggestions how to start?

I think it's worth hammering out where we think it should go. To some extent, that will determine who will review it and help maintain it in the future. 

if you envision a new module, I'd suggest writing more about what the module would look like in a few years when more features have been added (
https://github.com/scipy/scipy/issues/17059#issuecomment-1263964068).

I can also see this function in scipy.stats next to the proposed `sobol` under a "sensitivity analysis" heading (global vs local). Once it can do second derivatives, it would also be useful internally for an accurate calculation of the Fisher information matrix for confidence intervals of `fit`. 

Once we have a proposed location, it does need an email to the mailing list.

> Should I write function stubs first so that we can review the structure or should I start with a copy of my existing Jacobi library and we start iterating from there?

In the meantime, yes,  I think it's good to start looking at function signatures. Maybe with a draft of the documentation that would appear in SciPy?

**Comment by lucascolley** [comment]
A slight preference for `integrate` over `optimize` and `stats` I think, but definitely not ideal. `stats` would probably be better than `optimize`.

> ~three functions (e.g. derivative, jacobian, hessian) would not really be enough for a full-blown sub-package

Sure, it would be a very small subpackage, but is that a problem? As long as we communicate the scope of the subpackage clearly, having a few very general purpose tools be exposed in a sensible place seems worth it. I haven't looked through the history, but maybe being less ambitious and starting small will be enough to make it doable.

**Comment by andyfaff** [comment]
`differentiate` is great, but it's for a very specific task. I would hazard a guess that `optimize._numdiff.approx_derivative` would offer 90% of what people wanted. Perhaps we could make that public?

But then `approx_derivative` does have many drawbacks. It doesn't offer arbitrary order, and its functionality is specifically targeted to help minimisation. If one wants to develop further features then it's getting into a discussion of a full-blown subpackage that would replicate a lot of what numdifftools offers.

**Comment by mdhaber** [comment]
> I would hazard a guess that `optimize._numdiff.approx_derivative` would offer 90% of what people wanted. Perhaps we could make that public?

Sure, that would be great in `optimize` as a replacement or alternate method for the already-public [`scipy.optimize.approx_fprime`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.approx_fprime.html). As you note, `derivative`, `jacobian`, and `hessian` would be geared toward a different task.

**Comment by andyfaff** [comment]
> scalar derivatives, Jacobians, and Hessians

Clarity of scope and naming is important. If I see `derivative, jacobian, hessian` I would assume that they would differentiate anything, including the general non-elementwise R^n --> R^m.

If the suggestion is to have elementwise derivative, jacobian, hessian for R^1 --> R^1, then a name should be along the lines 
`elementwise_scalar_derivative`, `elementwise_scalar_hessian`, etc.

i.e. general names like `derivative` shouldn't be use if they're not geared towards a wider scope of differentiation functionality.

**Comment by mdhaber** [comment]
> I would assume that they would differentiate anything, including the general non-elementwise R^n --> R^m.

I think there's a misunderstanding. `jacobian` is for R^n --> R^m functions. The meaning of "elementwise" in that context is that it can evaluate not only the Jacobian at a point in a vectorized call (no loops), but it can do arbitrary numbers of points (arranged in an array with an arbitrary number of dimensions) in a single call. `hessian` would be similar. They are all built up from `differentiate`.

**Comment by andyfaff** [comment]
> The meaning of "elementwise" in that context is that it can evaluate not only the Jacobian at a single point in a vectorized call (no loops), but it can do arbitrary numbers of points in a single call

ok. The misunderstanding arose from reading the `differentiate` docstring. 

> ``func(x)[i]`` must equal ``func(x[i])`` for all indices ``i``

There's no way that this can be the case for R^n -> R^m where `x.shape == (n,)`.

I had a look at the gh-20063 and compared the jacobian function given there against `approx_derivative` for a simple example. The output from `jacobian` is less accurate. I wasn't expecting that given the default order for finite differences is 8. 
The simple example was:
```
def f(x):
    return np.array([np.sin(x[0]), np.cos(x[1]), np.sin(x[1]) * np.cos(x[2])])
```

**Comment by mdhaber** [comment]
These are great things to bring up when `jacobian` is under review. There's not a PR for that yet, so I went ahead and responded in https://github.com/scipy/scipy/pull/18811#issuecomment-2062999571. In short, the maximum absolute accuracy of the zero elements (~2e-13) is somewhat high because the default `atol` is too strict (essentially 0), but the absolute accuracy of the nonzero elements is better than `1e-14`.

In case others are just coming to this issue, please see https://github.com/scipy/scipy/issues/17059#issuecomment-2062195681!

**Comment by lorentzenchr** [comment]
> The meaning of "elementwise" in that context is that it can evaluate not only the Jacobian at a single point in a vectorized call (no loops), but it can do arbitrary numbers of points in a single call.

Maybe, it’s worth to consider some standard for the axis of the function argument `x`, e.g. first axis is for the "points/elements", the other axis for the function signature $R^{m,..,n} \rightarrow R^{?}$.

**Comment by mdhaber** [comment]
Yes, that I've thought about a lot in this and other contexts. As you wrote, there could be a fixed convention - and currently, the convention is for the 0th axis to correspond with the dimensionality of the input. This allows functions written like the [example above](https://github.com/scipy/scipy/issues/17059#issuecomment-2062797122) to work without modification when `x` becomes multidimensional. Of course, the other option is to accept an `axis` argument. (But usually `axis` means the axis along which a reduction occurs, which isn't happening here.)

**Comment by HDembinski** [comment]
Sorry for my silence, but I really think this is a great development, and I hope you, @mdhaber, can push through with `scipy.diff` or rather `scipy.differentiate`, which has a nicer symmetry with `scipy.integrate`.

**Comment by MothNik** [comment]
@HDembinski @laurent90git 
> Is there a published paper on such an approach ?

I also sometimes use polynomial extrapolation to zero and I "accidently" stumbled over this issue which seems to be quite mature already. However, for completeness I want to add that this approach is described in

Schwarz H.R., Köckler N. *Numerische Mathematik*, 2011, [DOI](https://doi.org/10.1007/978-3-8348-8166-3)

It's a german source which I think is a bit unfortunate because the content is really good. In the book version from 2009 (first publication was 1986 and I think it was already described there), example 3.5 in chapter 3 "Interpolation and Approximation" demonstrates how polynomials can be used to extrapolate accurate derivatives. There, they fit fully determined polynomials, e.g., the mentioned 4 data points for degree 3. I personally prefer to add a few more data points because then, error estimates are quite straightforward by computing the confidence interval at the extrapolated value (when you compute the small SVD, you get them basically for free).

However, they don't mention how the step size of the derivation can be chosen automatically to enhance the numerical precision in this context and I like the function/data-driven approach I found in this issue.

**Comment by HDembinski** [comment]
Thank you for the pointer to this resource, that's very much appreciated. In principle, the step from linear extrapolation to polynomial extrapolation is natural, but since it is not covered in most text books, I wouldn't call it "well established".
