### ISSUE TITLE
Mypy failure in CI for `numpy/__init__.pyi` positional-only parameters

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#17056]
The issue is (see [example log](https://github.com/scipy/scipy/actions/runs/3089188186/jobs/4996511280):
```
numpy/__init__.pyi:637: error: Positional-only parameters are only supported in Python 3.8 and greater  [syntax]
```

This is a known Mypy bug that occurs with Python >= 3.10.7, see https://github.com/python/mypy/issues/13627. It will be fixed in Mypy 0.980, but that version is not yet released. I'll submit a PR to work around the issue.

**Comment by tylerjereddy** [comment]
We could reopen this to remind us to switch the Python version back, but I'll leave that up to the team. Seems debatable if we'd want to anyway.

**Comment by rgommers** [comment]
I'd say it is fine to leave it at 3.9, arguably even better. We're not going to find anything useful by running Mypy with latest CPython/NumPy/Meson/Pythran, only less stability.
