### ISSUE TITLE
Pearson3 PPF does not function properly with negative skew.

### ISSUE THREAD

**Issue by jrkasprzyk** [scipy/scipy#17050]
Before scipy 1.6, the pearson3 cdf did not work properly for negative skew. It is fixed now, but this fix is not yet reflected in the PPF:

`scipy.stats.pearson3.ppf(0.5, -1.0, 0.0, 1.0)`
`#0.16396962557455153`
`scipy.stats.pearson3.ppf(0.75, -1.0, 0.0, 1.0)`
`#-0.5547137425616904`

_Originally posted by @jrkasprzyk in https://github.com/scipy/scipy/issues/12640#issuecomment-1251124399_

**Comment by mdhaber** [comment]
@jrkasprzyk It looks like the first snippet works fine, but there is a problem with the second?
```
scipy.stats.pearson3.cdf(0.16396962557455153, -1.0, 0.0, 1.0)  # ~0.5, right
scipy.stats.pearson3.cdf(-0.5547137425616904, -1.0, 0.0, 1.0)  # 0.25, wrong; should be 0.75
```

**Comment by jrkasprzyk** [comment]
The workaround seems to be that you have to pass in 1-CDF if the skew is negative. Actually 0.5 was a silly example to start with because 1-0.5 also equals 0.5. I was just trying to demonstrate the fact that the answers from the PPF function should increase as the alpha parameter increases, which is also an indication that something's wrong.

`# this yields 0.25`
`scipy.stats.pearson3.cdf(-0.5547137425616904, -1.0, 0.0, 1.0) #~0.25`
`#so you'd think that this would work:`
`scipy.stats.pearson3.ppf(0.25, -1.0, 0.0, 1.0) #it yields 0.7323398940499535`
`#but instead you have to do this:`
`scipy.stats.pearson3.ppf(1.0-0.25, -1.0, 0.0, 1.0) #-0.5547137425616904`

**Comment by mdhaber** [comment]
Sure. Yeah I can fix this shortly.
