### ISSUE TITLE
BUG: solve_ivp VisibileDeprecationWarning in find_active_events()

### ISSUE THREAD

**Issue by ddmarshall** [scipy/scipy#17060]
### Describe your issue.

When using solve_ivp with multiple events, the function `find_active_events()` produces a VisibleDeprecationWarning on the following line:
```
g, g_new = np.asarray(g), np.asarray(g_new)
```
This warning does not appear when using only one event and did not appear using older versions of numpy/scipy.

The code is based on an example from [StackOverflow](https://stackoverflow.com/questions/52175326/how-to-use-events-in-scipy-integrate-solve-ivp).

### Reproducing Code Example

```python
def fprime(x, y):
    return 3 * x**2 + 12 * x - 4

def event1(x, y):
    return y

def event2(x, y):
    return x

import numpy as np
from scipy.integrate import solve_ivp
# This works
sol_good1 = solve_ivp(fprime, (-8, 4), np.array([-120]),
                      t_eval=np.linspace(-8, 4, 10), events=[event1])
# This also works
sol_good2 = solve_ivp(fprime, (-8, 4), np.array([-120]),
                      t_eval=np.linspace(-8, 4, 10), events=[event1])
# This produces warning
sol_warning = solve_ivp(fprime, (-8, 4), np.array([-120]),
                        t_eval=np.linspace(-8, 4, 10), events=[event1, event2])
```

### Error message

```shell
~/miniconda3/envs/spyder-cf/lib/python3.10/site-packages/scipy/integrate/_ivp/ivp.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  g, g_new = np.asarray(g), np.asarray(g_new)
```

### SciPy/NumPy/Python version information

1.9.1 1.23.2 sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)

**Comment by Patol75** [comment]
`t`, or `x` in your case, is a `float` within `solve_ivp`. `y` must be a sequence, hence why you have to write `np.array([-120])` and not just `-120`. When events are calculated, they are expected to return a `float` or an `int`. This is true for `event2`, as it returns `t`, or `x` in your case. However, for `event1`, it returns `y`, which is not a `float` or an `int`. Both return values become members of the same `list`, which is then given to `numpy.asarray` that complains in the fashion you reported. A very simple reproducer is the following one:
```
import numpy as np
print(np.asarray([0, [0]]))

**Comment by ddmarshall** [comment]
You are correct. Changing the code for `event1` to the following eliminates the warning:
```
def event1(x, y):
    return y[0]
```
Thanks for pointing out my error.
