### ISSUE TITLE
BUG: minimize(method=’L-BFGS-B’) documentation is contradictory

### ISSUE THREAD

**Issue by naharrosp** [scipy/scipy#17065]
### Describe your issue.

Documentation of the method L-BFGS-B ([minimize(method='L-BFGS-B')](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-lbfgsb.html))seems not accurate and can lead to errors. The `maxfun` parameter is described as the "Maximum number of function evaluations.". Nevertheless, this function is a wrapper of [fmin_l_bfgs_b](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fmin_l_bfgs_b.html#scipy.optimize.fmin_l_bfgs_b), which specifies that the maximum number of function evaluations can be violated.

I think it would be clearer to include the full description of the `maxfun` parameter in [fmin_l_bfgs_b](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fmin_l_bfgs_b.html#scipy.optimize.fmin_l_bfgs_b) to [minimize(method='L-BFGS-B')](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-lbfgsb.html). From the users perspective, they could miss the [fmin_l_bfgs_b](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fmin_l_bfgs_b.html#scipy.optimize.fmin_l_bfgs_b)  docs page and perform experiments trusting that the maximum number of function evaluations is going to be respected.

### Reproducing Code Example

```python
-
```

### Error message

```shell
-
```

### SciPy/NumPy/Python version information

1.9.1 (stable)

**Comment by tupui** [comment]
Thanks @naharrosp for reporting. It would indeed be good to have matching documentation.
