### ISSUE TITLE
BLD: issues while making macosx_arm64 natively on cirrus-ci

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#17077]
### Describe your issue.

This is a catch-all issue for problems experienced while building `macosx_arm64` natively on cirrus-ci. I'm trying this in anticipation of #17029 being merged (native builds of `linux_aarch64`). The work is being done in https://github.com/andyfaff/scipy/pull/33, which is a branch off of the first PR.

I'm running into a few problems that span the cibuildwheel/meson/CI/pip ecosystem. 

@rgommers, @eli-schwartz, the first problem is an architecture problem. Two matrix entries are for cp38 and cp39, see the build log [here](https://api.cirrus-ci.com/v1/task/4544934911934464/logs/cibuildwheel.log). For each of the builds meson thinks its doing a native build for `x86_64`, even though I'm on an `arm64` machine:
```
  Build type: native build
  Project name: SciPy
  Project version: 1.10.0.dev0
  C compiler for the host machine: cc (clang 13.1.6 "Apple clang version 13.1.6 (clang-1316.0.21.2.3)")
  C linker for the host machine: cc ld64 762
  C++ compiler for the host machine: c++ (clang 13.1.6 "Apple clang version 13.1.6 (clang-1316.0.21.2.3)")
  C++ linker for the host machine: c++ ld64 762
  Host machine cpu family: x86_64
  Host machine cpu: x86_64
```

The cibuildwheel infrastructure thinks the build machine is arm64:
```
  platform: 'macos'
  architectures: {<Architecture.arm64: 'arm64'>}
```

Prior to the cibuildwheel step I also query the machine (with a different Python interpreter installed using brew):
```
> python -c "import platform;print(platform.python_version());print(platform.system());print(platform.machine())"
3.10.4
Darwin
arm64
> uname -m
arm64
> clang --version
Apple clang version 13.1.6 (clang-1316.0.21.2.3)
Target: arm64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Applications/Xcode-13.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
How does meson pick up the host machine architecture?

I also note that the build process is trying to install `numpy-1.19.5-cp38-cp38-macosx_10_9_x86_64.whl`:

```
Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "arm64" and platform_system == "Darwin"' don't match your environment
```

How can pip try to install an `x86_64` wheel onto an `arm64` machine? Why doesn't the pattern match; the system is `Darwin`, the machine is `arm64`, the python version is `3.8.10`? Does the `python_version` string have to match `3.8` exactly?

I then need to point out that things appear to work when using [Python 3.10 and 3.11](https://api.cirrus-ci.com/v1/task/4521218773614592/logs/cibuildwheel.log):
```
  Build type: native build
  Project name: SciPy
  Project version: 1.10.0.dev0
  C compiler for the host machine: cc (clang 13.1.6 "Apple clang version 13.1.6 (clang-1316.0.21.2.3)")
  C linker for the host machine: cc ld64 762
  C++ compiler for the host machine: c++ (clang 13.1.6 "Apple clang version 13.1.6 (clang-1316.0.21.2.3)")
  C++ linker for the host machine: c++ ld64 762
  Host machine cpu family: aarch64
  Host machine cpu: arm64
```

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

N/A

**Comment by eli-schwartz** [comment]
> How does meson pick up the host machine architecture?

By checking platform.machine, with a quirk for arm64 and x86_64 to detect, by running the compiler and checking for built-in defines, if it's actually arm or x86 (i386) respectively, because in both cases the kernel and userland may very reasonably be different.

This quirk isn't relevant here; intel x86 and arm machine architectures won't be autodetected as each other no matter your compiler. ;)

> How can pip try to install an x86_64 wheel onto an arm64 machine? 

That's odd and suggests a more sweeping problem? At that point meson hasn't run yet, so it seems like fundamentally a pip + CI environment issue. I don't know enough about pip internals to guess why though.

> Does the python_version string have to match 3.8 exactly?

PEP 496 gives examples that imply this should work. It also documents python_version as being "3.1" on python 3.10, which is obvious nonsense, but anyway for python 3.8.x it will always be "3.8" which means `python_version == "3.8"` will exactly match it.

**Comment by rgommers** [comment]
@andyfaff that looks like an issue with `cibuildwheel`. From the log:
```
Here we go!


Building cp38-macosx_arm64 wheel
CPython 3.8 macOS arm64 - Apple Silicon

Installing Python cp38...

+ pkgutil --pkgs
+ Download https://www.python.org/ftp/python/3.8.10/python-3.8.10-macosx10.9.pkg to /private/var/folders/_f/lyvxf0v13gs7984d7sf7j83c0000gn/T/cibw-run-ch0thltp/cp38-macosx_arm64/build/Python.pkg
```

If you download https://www.python.org/ftp/python/3.8.10/python-3.8.10-macosx10.9.pkg and run the installer, you see:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/98330/191912320-9581aef6-e32c-45a4-afb9-c337a8b8c501.png">

There was indeed a problem with Python 3.8, we had to do something nonstandard to get it to build with `multibuild` (can't remember what right now).

The [python-3.8.10-macos11.pkg](https://www.python.org/ftp/python/3.8.10/python-3.8.10-macos11.pkg) installer uses Rosetta as well. 

It's not clear to me from https://cibuildwheel.readthedocs.io/en/stable/options/#archs that `cibuildwheel` supports building Python 3.8 arm64 wheels. @henryiii maybe you can enlighten us?

> I then need to point out that things appear to work when using [Python 3.10 and 3.11](https://api.cirrus-ci.com/v1/task/4521218773614592/logs/cibuildwheel.log):

Those should have `universal2` installers, that'll work better. I assume `3.9` works as well?

**Comment by andyfaff** [comment]
[This log](https://api.cirrus-ci.com/v1/task/4792071021133824/logs/cibuildwheel.log) would seem to suggest that the Python 3.9 doesn't suffer from this issue (search for "*Downloading numpy-1.21.0-cp39-cp39-macosx_11_0_arm64.whl (12.1 MB)*" to get to the correct point in the log file). So I think you're probably right Ralf, the issue is that Python installer doesn't provide any arm64 support.
