### ISSUE TITLE
Can't import rel_entr from scipy.special

### ISSUE THREAD

**Issue by CrissTyl** [scipy/scipy#17072]
### Describe your issue.

Import statement `from scipy.special import rel_entr` fails

### Reproducing Code Example

```python
from scipy.special import rel_entr
```

### Error message

```shell
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-36fe78ea68ea> in <module>
----> 1 from scipy.special import rel_entr

ImportError: cannot import name 'rel_entr' from 'scipy.special' (unknown location)
```

### SciPy/NumPy/Python version information

1.9.1 1.22.4 sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
I can't reproduce this in the main branch. This might help others help you debug: how did you install SciPy, and what platform are you on?

**Comment by CrissTyl** [comment]
I am currently using my university's version of JupyterHub and Jupyter notebooks (.ipynb), and I installed scipy using the command !pip install --user scipy -U​ from within the notebook to update my scipy completely. Thank you for the quick reply!
________________________________

**Comment by mdhaber** [comment]
Is the version of SciPy before you update older than 0.15? Could be that it's still trying to import from the pre-existing SciPy version. I've had trouble updating from within a notebook and using the new version.
In any case, sounds like an installation issue and not necessary something we can fix.
