### ISSUE TITLE
DOC: "These are not universal functions" difficult to understand for newcomers

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#17078]
### Is your feature request related to a problem? Please describe.

The docs of [special](https://scipy.github.io/devdocs/reference/special.html) include the sentence "These are not universal functions" to point out that a function only accepts scalar arguments and not arrays. I suggest to change the formulation to something a novice numpy user will understand as the concept of "universal function" is a NumPy thing. I guess that even many regular NumPy users do not know the term although they use ufuncs every day.

### Describe the solution you'd like.

Alternative formulation that appeals to newbies and veterans:

"These functions only accept scalar arguments but not arrays. They are not universal functions."

**Comment by tupui** [comment]
I agree here. Either we leave it like this and point to the NumPy definition of ufunc or we rephrase-which I prefer.

**Comment by rgommers** [comment]
+1 from me. Universal functions should get an explanation ("ufuncs" with a link to the relevant NumPy docs), and what is/isn't a ufunc should come after a regular explanation of what the functions do. Ufuncs are an implementation detail mostly.

**Comment by melissawm** [comment]
@dschmitz89 would you be willing to submit a PR for this?

**Comment by dschmitz89** [comment]
@melissawm : yep :)
