### ISSUE TITLE
ENH: Exporting the removed component of detrend()

### ISSUE THREAD

**Issue by CommonClimate** [scipy/scipy#17084]
### Is your feature request related to a problem? Please describe.

Currently, `scipy.signal.detrend()` simply returns the detrended array. However, it would be valuable to also export the component that was removed (i.e. the trend), so it can be used and/or put back later.

The scientific use case for this is that it is common in timeseries analysis to model a signal as a superposition of a deterministic and stochastic part. The deterministic part is often isolated via trend fitting, which `scipy.signal.detrend()` does under the hood, but then jettisons the result where no-one can find it.  

### Describe the solution you'd like.

Export the removed component (trend) as a second, optional array of same dimension as `y`.  In general, one might consider doing the same for other data processing steps that remove part of a signal, so the components can be added back in at the end of an analysis. 

### Describe alternatives you've considered.

Re-writing a detrending function from scratch or hacking `scipy.signal.detrend()` in another package so it does what I want

**Comment by WarrenWeckesser** [comment]
The suggested enhancement here is

> Export the removed component (trend) as a second, optional array of same dimension as y.

One can get that by simply subtracting the output from the input, e.g.

    y = detrend(x)
    trend = x - y

I don't think we need to extend the API for such a simple operation.

A more interesting enhancement would be to return the *parameters* of the trend.  That is, if `type='linear'`,  return the slope and intercept, and if `type='constant`, return the constant. If `type='linear` and `bp` is used, the return value would be a sequence of (slope, intercept) pairs.

I'm not advocating for such a change; I don't know if there is sufficient demand for such a feature to make it worthwhile.

**Comment by DietBru** [comment]
> A more interesting enhancement would be to return the _parameters_ of the trend. That is, if `type='linear'`, return the slope and intercept, and if `type='constant`, return the constant. If `type='linear` and `bp` is used, the return value would be a sequence of (slope, intercept) pairs.

For reference: Numpy's [Polynomial] has [fit] classmethod, which also can be used for detrending (as explained in PR #20778.)  [Polynomial] stores the polynomial coefficients.

[Polynomial]: https://numpy.org/devdocs/reference/generated/numpy.polynomial.polynomial.Polynomial.html
[fit]: https://numpy.org/devdocs/reference/generated/numpy.polynomial.polynomial.Polynomial.fit.html
