### ISSUE TITLE
ENH: Documentation on test behind p-values of .spearmanr

### ISSUE THREAD

**Issue by tstoeger** [scipy/scipy#17089]
### Is your feature request related to a problem? Please describe.

The docstring of [.spearmanr](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.spearmanr.html#scipy.stats.spearmanr) currently does not report on the test which is used to determine the p-value.

Used scipy.stats.spearmanr for a scientific manuscript, and journal editor requested more information about used test.

Reading the code, the specific test is not evident. While it appears based on t distribution, could not identify the full procedure by name. Nor, identify by name the preprocessing scheme between computation of Spearman's rho and comparison against t distribution.

Possibly related to first point under [#8789](https://github.com/scipy/scipy/issues/8789). 

### Describe the solution you'd like.

Docstring stating or citing the test used for p-values.

**Comment by mdhaber** [comment]
I can help you find the information. Would you be willing to submit a PR adding this information to the docstring? Then I could review/merge the PR.

**Comment by tstoeger** [comment]
Thank you for helping me find the information.

Happy to then submit PR.

**Comment by mdhaber** [comment]
Wikipedia mentions the same use of the t distribution and gives citations, but I can't find them online.

![image](https://user-images.githubusercontent.com/6570539/192166531-e6f20b87-b133-4b49-99f9-e6774153b32e.png)

I'll see if I can a more accessible reference.

**Comment by tstoeger** [comment]
Thank you! This is wonderful. Will later this week prepare PR.

**Comment by mdhaber** [comment]
Hi @tstoeger - please ping me when you open a PR so I don't miss it. Thanks!

**Comment by mdhaber** [comment]
@tstoeger just thought I'd check in. Are you still able to submit this PR so we can complete this issue?

**Comment by tstoeger** [comment]
@mdhaber Apologies for the delay. Got caught up by manuscript revision. Submitted PR. Thank you again!
