### ISSUE TITLE
BUG: inv() for quat 

### ISSUE THREAD

**Issue by W-chengjie** [scipy/scipy#17097]
### Describe your issue.

Function inv() returns the inverse of rotation, but when expressed in quaternions, it does not give the correct inverse form.

### Reproducing Code Example

```python
r = R.from_euler('zyx',[40,40,40],degrees=True)
print(r.as_quat())
rq = r.inv()
print(rq.as_quat())
```

### Error message

```shell
[0.41193454 0.19208823 0.41193454 0.78976071]
[ 0.41193454  0.19208823  0.41193454 -0.78976071]
```

**Comment by rkern** [comment]
It looks correct to me, given the double-cover nature of quaternions (`q` and `-q` representing the same rotation). What result are you expecting? Note that for the quaternion `w + i*x + j*y + k*z`, the array is of the form `[x, y, z, w]`.

**Comment by rkern** [comment]
Given double-cover, `[-x, -y, -z, w]` and `[x, y, z, -w]` represent the same rotation. `r.inv().as_quat()` gives _a_ quaternion for _the_ inverse of the rotation, not _the_ inverse of the quaternion for the rotation.
