### ISSUE TITLE
BUG: The signature of cKDTree.query_pairs in the docs does not mention the output_type parameter

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#17107]
### Describe your issue.

At https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.query_pairs.html the method signature is given as `cKDTree.query_pairs(self, r, p=2., eps=0)`, missing the `output_type` parameter (which is correctly listed in the parameter list just below.

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

1.9.1 1.23.3 sys.version_info(major=3, minor=10, micro=7, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @anntzer, thank you for reporting. Indeed in the Cython code (`scipy/spatial/_ckdtree.pyx:L1087`) we define the first line of docstring as the signature. But it was not updated to include this parameter. We should either update the docstring, or use a more robust solution like `@cython.embedsignature(True)`. @jjerphan what do you think?

**Comment by jjerphan** [comment]
> We should either update the docstring, or use a more robust solution like @cython.embedsignature(True). @jjerphan what do you think?

We can easily try it in a Draft PR dedicated to this interfaces, and see if it resolves this issue.

**Comment by tupui** [comment]
@anntzer Would you like to make a PR?

**Comment by anntzer** [comment]
I'll pass on that one :)

**Comment by jjerphan** [comment]
@tupui: I do not know enough about SciPy's Cython implementation to know if `embedsignature=True` could be used generally. Still, I think `embedsignature=True` can be set locally on API which needs to have their documentation propagated, and after some more inspection `embedsignature=True` could be set globally.

**Comment by tupui** [comment]
@jjerphan are you interested in looking into that? You have more Cython experience than I do and it's a good way to look into all the Cython we have and find other projects to work on.

**Comment by jjerphan** [comment]
Yes, but probably after I treat other PRs I've started?
