### ISSUE TITLE
BUG, BLD: SCIPY_USE_PYTHRAN=0 has a blind spot in stats testing

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#17102]
While investigating gh-17099, I noticed that `meson` builds can't pass the full test suite when using `export SCIPY_USE_PYTHRAN=0`, which remains useful when probing more exotic compilers. I observed similar behavior with Intel and GNU compiler toolchains.

Since GNU builds are way easier to deal with, here is the reproducer for Linux/GNU on latest `main`:

- `export SCIPY_USE_PYTHRAN=0`
- `python dev.py test -j 10 -s stats`

The errors all look like this:

```
ImportError while importing test module '/home/tyler/github_projects/scipy/build-install/lib/python3.9/site-packages/scipy/stats/tests/test_variation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../../spack/opt/spack/linux-ubuntu22.04-skylake_avx512/gcc-11.2.0/python-3.9.12-osore4bvxpxd66nnaw6pvjrmkf7csyia/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/stats/__init__.py:480: in <module>
    from ._stats_py import *
scipy/stats/_stats_py.py:53: in <module>
    from ._hypotests import _all_partitions
scipy/stats/_hypotests.py:14: in <module>
    from ._hypotests_pythran import _a_ij_Aij_Dij2
E   ModuleNotFoundError: No module named 'scipy.stats._hypotests_pythran'
```

I did not check if this was also true for the `distutils`-based build system, but `meson` is the future anyway and way faster for me to check.

**Comment by rgommers** [comment]
Hmm, this is due to an issue in the Azure CI config, the `SCIPY_USE_PYTHRAN` variable isn't properly used there. I on purpose did not duplicate all those CI jobs when introducing Meson, to keep CI load manageable. The `numpy.distutils` builds would have caught this. I'll open a PR with a fix for that.

**Comment by rgommers** [comment]
This is fixed, we have a job that uses `-Duse-pythran=false` here: https://github.com/scipy/scipy/blob/290512429ccf5a0933165a6ec00d7d3748725a4d/.github/workflows/windows.yml#L154
