### ISSUE TITLE
BUG: stats: spurious warning from `ncf.cdf`

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#17101]
### Describe your issue.

When the shape parameters `dfn` and `dfd` of the `ncf` distribution are both 1.0 or both 2.0, `ncf.cdf` generates a spurious `RuntimeWarning`.

### Reproducing Code Example

```python
In [87]: import scipy

In [88]: scipy.__version__
Out[88]: '1.10.0.dev0+1953.3644066'

In [89]: from scipy.stats import ncf

In [90]: ncf.cdf(1.5, 2.0, 2.0, 1.0)
/home/warren/repos/git/forks/scipy/build-install/lib/python3.10/site-packages/scipy/stats/_continuous_distns.py:6587: RuntimeWarning: invalid value encountered in _ncf_cdf
  return _boost._ncf_cdf(x, dfn, dfd, nc)
Out[90]: 0.49123845184678905
```
The value is correct; the only problem is the spurious warning.

### SciPy/NumPy/Python version information

1.10.0.dev0+1953.3644066 1.24.0.dev0+809.g852f79700 sys.version_info(major=3, minor=10, micro=1, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment]
I looked into this a bit more, and found that the spurious warnings can occur in the `cdf` function when `dfn + dfd` is exactly 4, and in the `pdf` method when `dfn + dfd` is exactly 2. For example,
```
In [21]: ncf.cdf(1, 1.5, 2.5, 5)
/home/warren/repos/git/forks/scipy/build-install/lib/python3.10/site-packages/scipy/stats/_continuous_distns.py:6624: RuntimeWarning: divide by zero encountered in _ncf_cdf
  return _boost._ncf_cdf(x, dfn, dfd, nc)
Out[21]: 0.12644056682002733

In [22]: ncf.pdf(1, 0.125, 1.875, 5)
/home/warren/repos/git/forks/scipy/build-install/lib/python3.10/site-packages/scipy/stats/_continuous_distns.py:6621: RuntimeWarning: divide by zero encountered in _ncf_pdf
  return _boost._ncf_pdf(x, dfn, dfd, nc)
Out[22]: 0.01572327497755057
```
The problem is that the `pdf` and `cdf` functions for the Boost `non_central_f` distribution leave floating point exception flags set, even though the return value is correct.  For more details, see the [boost/math issue](https://github.com/boostorg/math/issues/845).

**Comment by mdhaber** [comment]
Rather than open new issues for `nct` and `ncx2`, let's track progress in gh-14901. (https://github.com/scipy/scipy/issues/14901#issuecomment-1287383211)
