### ISSUE TITLE
DOC : Reference to `nperseg` in `periodogram`  doc left unexplained

### ISSUE THREAD

**Issue by mocquin** [scipy/scipy#17100]
The doc of `scipy.signal.periodogram` refers to `nperseg` in the `window` argument description, but `nperseg` is not described anywhere in the doc of the function. Knowledge of other tools like welch's method and the `nperseg` meaning is not obvious especially for newcomers.

I guess either `nperseg`should be explicitely explained (or users should be directed to welch documentation, or basicaly anything that doesn't leave this parameter unexplained)

https://github.com/scipy/scipy/blob/2e5883ef7af4f5ed4a5b80a1759a45e43163bf3f/scipy/signal/_spectral_py.py#L156-L173

**Comment by DanielGoman** [comment]
Hello :)
I'm new to open source contribution.
If this is still relevant, I would like to work on this issue.
Could you assign it to me?

**Comment by roryyorke** [comment]
@DanielGoman I suggest just making a branch and pull request.  Start at https://docs.scipy.org/doc/scipy/dev/index.html . For this work you'll especially want to be able to build the docs and check they look OK.

I'm not a core dev, so I can't say for sure if a PR would be accepted, but documentation fixes are normally not a big deal to get accepted.

**Comment by musteng** [comment]
Are you still working on this issue @DanielGoman ?

**Comment by kuchidareo** [comment]
Hi. I tried to work on this issue and found that the explanation of this section was corrected.
No need to work more on this issue.

before
` window : str or tuple or array_like, optional 
         Desired window to use. If `window` is a string or tuple, it is 
         passed to `get_window` to generate the window values, which are 
         DFT-even by default. See `get_window` for a list of windows and 
         required parameters. If `window` is array_like it will be used 
         directly as the window and its length must be nperseg. Defaults 
         to 'boxcar'. `

and now
` window : str or tuple or array_like, optional
        Desired window to use. If `window` is a string or tuple, it is
        passed to `get_window` to generate the window values, which are
        DFT-even by default. See `get_window` for a list of windows and
        required parameters. If `window` is array_like it will be used
        directly as the window and its length must be equal to the length
        of the axis over which the periodogram is computed. Defaults
        to 'boxcar'.`

**Comment by tupui** [comment]
Looks like it's fixed yes, there is no reference to `nperseg` on this page anymore. Thank you all.
