### ISSUE TITLE
BUG: 1.9.1 pypi package seems to be compiling extensions with the --inplace distutils option on

### ISSUE THREAD

**Issue by sieira** [scipy/scipy#17143]
### Describe your issue.

When installing scipy using pip, all shared objects are dumped in `site-packages` instead of their respective folders

### Reproducing Code Example

Run in a fresh docker python:3.10.7-alpine3.16

```python
$ pip install scipy==1.9.1
$ python
>>> import scipy
...
 from . import _ccallback_c
 ImportError: cannot import name _ccallback_c‍‍‍‍‍‍‍‍‍‍‍

$ find / -name _ccallback_c.cpython-310-x86_64-linux-gnu.so
/usr/local/lib/python3.10/site-packages/_ccallback_c.cpython-310-x86_64-linux-gnu.so

this one should be in /usr/local/lib/python3.10/site-packages/scipy/_lib/
```

### Error message

```shell
ImportError: cannot import name _ccallback_c‍‍‍‍‍‍‍‍‍‍‍
```

### SciPy/NumPy/Python version information

1.9.1 / 1.23.3 / 3.10.7

**Comment by tupui** [comment]
Hi @sieira, thank you for reporting. Seems like you are on alpine. Otherwise disregard the following. Was the output of pip install concluent? It should have tried to compile SciPy as we do t provide wheels for musl yet. I would be inclined to close this as we already have a musl issue.

**Comment by sieira** [comment]
The distribution packages are not suitable in my case, however, it actually seems to be an issue of the python docker image that is not setting an adequate PYTHONPATH. So, I'm closing this...
