### ISSUE TITLE
ENH: Access to dual variable results of the MILP solver

### ISSUE THREAD

**Issue by jinningwang** [scipy/scipy#17148]
### Is your feature request related to a problem? Please describe.

Regarding the mixed integer linear programming, scipy provides the wrapper of HiGHS as scipy.optimize.milp.
With version 1.9.1, the dual variables are not included in the results, although the decision variables can be accessed.
In power engineering, it is useful to access the dual variables after solving the model. For example, local marginal price is the dual of power generation.

### Describe the solution you'd like.

I kindly request to include the dual variables in the solver wrapper.
For example, after solving the model, the dual can be accessed as
```python
from scipy.optimize import milp
res = milp(c=c, constraints=constraints, integrality=integrality)
res.x
res.dual
```

### Describe alternatives you've considered.

Another costly solution will be to bypass the wrapper under scipy.optimize, directly calling the HiGHS.
However, including access to dual should be a low-cost but useful enhancement.

### Additional context (e.g. screenshots, GIFs)

The example is referenced from [scipy.optimize.milp](https://docs.scipy.org/doc/scipy-1.9.1/reference/generated/scipy.optimize.milp.html?highlight=scipy%20optimize%20milp#scipy.optimize.milp).

**Comment by mdhaber** [comment]
We might be able to add this, but I'm not sure if HiGHS currently returns the duals for when there are `integrality` constraints. I say that because `linprog` exposes the duals when there are no `integrality` constraints, but they are all zero when there are `integrality` constraints.

For example:
```python3
import numpy as np
from scipy.optimize import linprog, milp, Bounds, LinearConstraint
rng = np.random.default_rng(0)
c = rng.random(size=5) - 0.5
A = rng.random(size=(4, 5))
b = rng.random(size=4)
bounds = [(-10, np.inf)]*5
linprog(c, A_eq=A, b_eq=b, bounds=bounds)
```
The result is:
```
           con: array([0., 0., 0., 0.])
 crossover_nit: 0
         eqlin:  marginals: array([ 0.13760231,  0.09501787, -0.25585934, -0.74905967])
  residual: array([0., 0., 0., 0.])
           fun: -7.4607245688555945
       ineqlin:  marginals: array([], dtype=float64)
  residual: array([], dtype=float64)
         lower:  marginals: array([0.        , 0.        , 0.        , 0.        , 0.68438045])
  residual: array([13.26897509, 10.03465834, 16.41472038, 13.77113844,  0.        ])
       message: 'Optimization terminated successfully. (HiGHS Status 7: Optimal)'
           nit: 4
         slack: array([], dtype=float64)
        status: 0
       success: True
         upper:  marginals: array([0., 0., 0., 0., 0.])
  residual: array([inf, inf, inf, inf, inf])
             x: array([  3.26897509,   0.03465834,   6.41472038,   3.77113844,
       -10.        ])
```
Note the integrality constraint happens to be satisfied.
The dual variables are under "marginals" for the different types of bounds. For example, the dual variables corresponding with the equality constraints are `[ 0.13760231,  0.09501787, -0.25585934, -0.74905967]`.

When we add an integrality constraint:
```python3
integrality = [0, 0, 0, 0, 1]
linprog(c, A_eq=A, b_eq=b, bounds=bounds, integrality=integrality)
```
we get
```
           con: array([ 3.33066907e-16, -1.99840144e-15,  8.88178420e-16,  6.66133815e-16])
 crossover_nit: -1
         eqlin:  marginals: array([0., 0., 0., 0.])
  residual: array([ 3.33066907e-16, -1.99840144e-15,  8.88178420e-16,  6.66133815e-16])
           fun: -7.460724568855594
       ineqlin:  marginals: array([], dtype=float64)
  residual: array([], dtype=float64)
         lower:  marginals: array([0., 0., 0., 0., 0.])
  residual: array([13.26897509, 10.03465834, 16.41472038, 13.77113844,  0.        ])
       message: 'Optimization terminated successfully. (HiGHS Status 7: Optimal)'
           nit: -1
         slack: array([], dtype=float64)
        status: 0
       success: True
         upper:  marginals: array([0., 0., 0., 0., 0.])
  residual: array([inf, inf, inf, inf, inf])
             x: array([  3.26897509,   0.03465834,   6.41472038,   3.77113844,
       -10.        ])
```
The marginals all turn to zero, even though the solution hasn't actually changed.

@mckib2 For this example, when we get to this part of the code:
https://github.com/scipy/scipy/blob/2e5883ef7af4f5ed4a5b80a1759a45e43163bf3f/scipy/optimize/_linprog_highs.py#L377-L385

`'lambda'` is indeed in `res`, but `marg_eqlin` is all zeros when there are integrality constraints. Is that happening in the wrapper or is HiGHS returning them as all zero?

**Comment by jinningwang** [comment]
Hi @mdhaber,

Thanks for your reply.
I checked HiGHS python_api at https://github.com/ERGO-Code/HiGHS/blob/master/src/interfaces/highs_python_api.py
From lines 102 - 124, it seems that they do not offer dual values for MIP.
Will drop them a query about this and keep you updated in this thread.

Regards,
Jinning

**Comment by jinningwang** [comment]
Conclusion:
MIP has no dual problem, so the access to dual is unreasonable. We can discard this issue since it was my misunderstanding.

A Further information is attached below as the background of my issue.
In the power engineering, MILP is used first to determine the generator status. After eliminating all the integer variables, LP is further used to determine the marginal price.

Thanks,
Jinning

**Comment by mdhaber** [comment]
Ok, that would have been my guess. But depending on the algorithm used, those marginal prices might have been calculated in the solution of a relaxed problem in the last iteration, so it was worth asking.
