### ISSUE TITLE
BUG: Incorrect documentation for scipy.stats.foldnorm

### ISSUE THREAD

**Issue by mhlinder** [scipy/scipy#17160]
### Describe your issue.

The formula for the Probability Density Function of the Folded Normal Distribution [given in the documentation](https://github.com/scipy/scipy/blob/v1.9.1/scipy/stats/_continuous_distns.py#L2146) of `scipy.stats.foldnorm` is incorrect:
```
f(x, c) = \sqrt{2/\pi} cosh(c x) \exp(-\frac{x^2+c^2}{2})
```

I am not fully familiar with this distribution, however, consider the following:

Let c=0. Then the term `cosh(cx) = cosh(0) = 1`, and `f` reduces to
```
f(x, 0) = \sqrt{2/\pi} \exp(-\frac{x^2}{2})
```

This is proportional to a Standard Normal Distribution, which has support from `-\infty` to `\infty`.

I am not familiar with the cosh parameterization, however, the implementation uses a different parameterization.

The reproducing example below demonstrates the correctness of the underlying implementation: theoretical quantiles and histograms match between `scipy.stats.foldnorm.ppf` and the corresponding quantiles from a sample of Normal values, with the absolute value applied.

The conclusion is that the documentation does not give the correct specification for the probability distribution function.

Note: I would submit a PR to correct this, however, I am unsure of whether the PPF is implemented and thus cannot prove that the `.ppf` method is correct (the example below simply gives me sufficient confidence).

### Reproducing Code Example

```python
from scipy.stats import norm, foldnorm
import matplotlib.pyplot as plt

foldnorm.ppf(.1, c=0), pd.Series(norm.rvs(size=10000000)).abs().quantile(.1)
# (0.12566134685507396, 0.12570017164077882)

foldnorm.ppf(.8, c=0), pd.Series(norm.rvs(size=10000000)).abs().quantile(.8)
# (1.281551565544601, 1.28163668353497)

foldnorm.ppf(.9, c=0), pd.Series(norm.rvs(size=10000000)).abs().quantile(.9)
# (1.6448536269514726, 1.645007112959206)

fig, ax = plt.subplots(figsize=(6, 6))
bins = np.linspace(0, 6, num=15)
ax.hist(foldnorm.rvs(c=0, size=100000), facecolor='k', bins=bins)
ax.hist(np.abs(norm.rvs(size=100000)), alpha=.5, bins=bins)
```

### Error message

```shell
The comments in the example give the values that confirm the correctness of the ppf.
```

### SciPy/NumPy/Python version information

1.9.1

**Comment by mdhaber** [comment]
If I understand correctly, you are saying that only the documentation is wrong, but that the implementation is correct.

Are you sure they're not the same?

```python3
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
# rng = np.random.default_rng(1638083107694713882823079058616272161)
x = np.linspace(0, 10, 100)
c = 1.5624
pdf =  np.sqrt(2 / np.pi) * np.cosh(c * x) * np.exp(- (x**2 + c**2) / 2)
pdf2 = stats.foldnorm(c=c).pdf(x)
plt.plot(x, pdf, '-', x, pdf2, '--')
plt.legend(['As Described', 'As Implemented'])
plt.title('PDF of `scipy.stats.foldnorm')
np.allclose(pdf, pdf2)
```

![image](https://user-images.githubusercontent.com/6570539/194382967-c6fc64e4-f785-4de6-a44e-fce48624fcfb.png)

**Comment by WarrenWeckesser** [comment]
> Let c=0. Then the term `cosh(cx) = cosh(0) = 1`, and f reduces to
>
>     f(x, 0) = \sqrt{2/\pi} \exp(-\frac{x^2}{2})
>
> This is proportional to a Standard Normal Distribution

That is *twice* the PDF of the standard normal distribution, which is what it should be for the folded normal distribution with c=0.  For the standard normal distribution, the factor in front of `exp(...)` is `1/sqrt{2\pi}`.

**Comment by mhlinder** [comment]
f(x,0) cannot be a valid pdf, Twice the pdf of a standard normal will not integrate correctly to equal 1
