### ISSUE TITLE
BUG: bernoulli.pmf returns non-zero values with non-integer arguments

### ISSUE THREAD

**Issue by vincentvalton** [scipy/scipy#17167]
### Describe your issue.

I've observed a bug with SciPy 1.9.1 and the `scipy.stats.bernoulli.pmf` function:

To reproduce the error:

In SciPy 1.9.1:
```
scipy.stats.bernoulli.pmf([0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 0.8)
>>[0.2, 0.25108801, 0.30859638, 0.37173758, 0.43923729,
       0.50929582, 0.57957708, 0.64723272, 0.7089683 , 0.76115652,
       0.8]
```
       
While the expected output should be:
`[0.2, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.8]`

By comparison, downgrading scipy to 1.7.3 results in the correct behaviour:
In SciPy 1.7.3
```
scipy.stats.bernoulli.pmf([0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 0.8)
>> [0.2, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.8]
```

### Reproducing Code Example

```python
scipy.stats.bernoulli.pmf([0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0], 0.8)
```

### Error message

```shell
No error message, just fails silently
```

### SciPy/NumPy/Python version information

1.9.1 1.23.1 sys.version_info(major=3, minor=10, micro=4, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment]
Thanks @vincentvalton.  @mdhaber is already working on a fix in https://github.com/scipy/scipy/pull/17166

**Comment by mdhaber** [comment]
Closed by gh-17166. (Forgot to link.)
