### ISSUE TITLE
BUG: scipy.interplate.griddata states wrong shape of xi input in documentation

### ISSUE THREAD

**Issue by aoerder** [scipy/scipy#17164]
### Describe your issue.

For `scipy.interpolate.griddata` the documentation states that the shape requirements of the input are:
- points: `(n, D)`
- values: `(n, )`
- xi: `(m, D)`

However `xi` needs to be in the same shape as `points` if passed in as an array

This is referenced in: <https://github.com/scipy/scipy/blob/acac27527df9c8723647512361c581f714fb473a/scipy/interpolate/_ndgriddata.py#L129>

### Reproducing Code Example

```python
N.A.
```

### Error message

```shell
N.A.
```

### SciPy/NumPy/Python version information

1.9.0 1.23.2 sys.version_info(major=3, minor=10, micro=4, releaselevel='final', serial=0)

**Comment by j-bowhay** [comment]
Can you provide some example code showing this, I am not sure I follow your argument at this point.

**Comment by WarrenWeckesser** [comment]
@aoerder, it is not required that `xi` and `points` have the same length.  The arrays `points` and `values` are the known function values of the function.  `xi` is the set of points at which new function values are to be interpolated.

In the following example, there are 5 known values at 5 points (`n` is 5), and we interpolate the values at the 3 locations given in `xi` (`m` is 3):
```
In [34]: from scipy.interpolate import griddata

In [35]: points = np.array([[0, 0], [1, 0], [1.25, 1], [0, 2], [2, 2]])

In [36]: values = np.array([5, 2.5, 2, 4, 7.5])

In [37]: xi = np.array([[0.5, 0.5], [0.5, 1.5], [1, 1.5]])

In [38]: griddata(points, values, xi)
Out[38]: array([3.75   , 3.25   , 3.65625])

```

I'm closing the issue, but if you have an example that demonstrates a problem, please include it here.
