### ISSUE TITLE
MAINT: wheel build trigger on push

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#17171]
It may be useful to allow the `wheels.yml` file to trigger a wheel build on pushing to a maintenance branch. We currently have `# push:` (disabled), but I think it would be convenient to allow pushing the release commit right up with `[wheel build]` (without the tag yet), then follow up with the tag push later if the wheel builds succeed.

I'm probably going to manually do this myself on `maintenance/1.9.x` shortly, since my usual process + `[wheel build]` wasn't sufficient.

**Comment by rgommers** [comment]
Maybe the manual trigger is enough for that use case?

<img width="946" alt="image" src="https://user-images.githubusercontent.com/98330/194721783-a73b0af6-b727-4a8b-8203-0b2027d0f3cf.png">

**Comment by tylerjereddy** [comment]
I think we should just allow it on push on maintenance, can't think of a drawback since we pretty much always create a merge commit there (no squashing) that shouldn't have a wheel build trigger on it.

**Comment by tylerjereddy** [comment]
And why do we have the wheel builds triggered on tags still? I guess I'm not understanding the use case for that in:

- push with `[wheel build]`
- everything works and the wheels are produced/uploaded to staging/downloaded
- push the tag
- don't trigger another wheel build

**Comment by andyfaff** [comment]
It may not be useful for this point release, but can you give an exact set of conditions for what a release needs from a wheel build process? I'm not familiar with releases, so I just copied what numpy did.

**Comment by tylerjereddy** [comment]
heh, maybe Chuck likes living on the edge and pushes the tag to build NumPy wheels :)

**Comment by andyfaff** [comment]
Modifications to the wheel building have to take into account that it gets done with two different CI providers, Github Actions (`wheels.yml`) and Cirrus-ci (`.cirrus.star`). So it's important to have a specification because scripts have to be modified in two different places.

I don't think a manual press (to start GHA) will make the cirrus-ci run.

**Comment by tylerjereddy** [comment]
The order of wheel building vs. tag pushing should be relatively clear from our release docs: https://docs.scipy.org/doc/scipy/dev/core-dev/index.html#making-a-scipy-release

>  Only push the release tag to the repo once all wheels have been built successfully ...

That in itself is probably a sufficient specification to rule out the current design at least. I can try to provide more detail if you like. I do keep an exact step-by-step record of every release I do in bullet points as well.

**Comment by rgommers** [comment]
Good points. Agreed now that this needs the tweak that Tyler proposes. Pushes to maintenance branches with `[wheel build]` support should be added.

**Comment by andyfaff** [comment]
#17181 builds and uploads wheels for any push to maintenance.
