### ISSUE TITLE
BUG: build exits with "ModuleNotFoundError: No module named 'scipy.__config__'"

### ISSUE THREAD

**Issue by Tartopohm** [scipy/scipy#17186]
### Describe your issue.

I just tried to build and install from source on a Fedora 34 station running py39.
The build and the installation seem to go fine (there are some issues with openblas not being detected, that are fixed by `$ meson setup build -Dblas=blas -Dlapack=lapack --prefix=$PWD/build-install`).
However, the post-installation check fails as `scipy` cannot be imported.
Fedora does this thing where it keeps a `lib` path and a `lib64` distinct, and I suspect the problem stems from here.
There are a few bits under `lib`:
```
$ ls lib/python3.9/site-packages/scipy/
> linalg  special  __config__.py  version.py
```
and the bulk is under `lib64`:
```
$ ls lib64/python3.9/site-packages/scipy/
> cluster  constants  fft  fftpack  integrate  interpolate  io  _lib  linalg  misc  ndimage  odr  optimize  __pycache__  signal  sparse  spatial  special  stats  conftest.py  _distributor_init.py  __init__.py
```
The install script fails when trying to access `__config__` from the `lib64` path (see trace). If I link it from `lib` into `lib64`, then `scipy` can be imported, but it feels a bit shaky (and basic tests do not pass afterwards, anyway).

Any suggestion?

EDIT: I build in a venv.

### Reproducing Code Example

```python
$ meson setup build -Dblas=blas -Dlapack=lapack --prefix=$PWD/build-install
$ python dev.py build
```

### Error message

```shell
ninja: Entering directory `build'
[2/2] Generating scipy/generate-version with a custom command
Build OK
Installing, see meson-install.log...
Installation OK
Trying to find scipy from development installed path at: /home/nmokus/emmyHome/scipy/build-install/lib64/python3.9/site-packages
Traceback (most recent call last):
  File "/home/nmokus/emmyHome/scipy/build-install/lib64/python3.9/site-packages/scipy/__init__.py", line 121, in <module>
    from scipy.__config__ import show as show_config
ModuleNotFoundError: No module named 'scipy.__config__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nmokus/emmyHome/scipy/dev.py", line 399, in get_project_info
    test, version, mod_path = runtests.import_module()
  File "/home/nmokus/emmyHome/scipy/runtests.py", line 355, in import_module
    __import__(PROJECT_MODULE)
  File "/home/nmokus/emmyHome/scipy/build-install/lib64/python3.9/site-packages/scipy/__init__.py", line 126, in <module>
    raise ImportError(msg) from e
ImportError: Error importing SciPy: you cannot import SciPy while
        being in scipy source directory; please exit the SciPy source
        tree first and relaunch your Python interpreter.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nmokus/emmyHome/scipy/build-install/lib64/python3.9/site-packages/scipy/__init__.py", line 121, in <module>
    from scipy.__config__ import show as show_config
ModuleNotFoundError: No module named 'scipy.__config__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nmokus/emmyHome/scipy/dev.py", line 661, in <module>
    main(argv=sys.argv[1:])
  File "/home/nmokus/emmyHome/scipy/dev.py", line 288, in main
    test, version, mod_path = get_project_info()
  File "/home/nmokus/emmyHome/scipy/dev.py", line 409, in get_project_info
    test, version, mod_path = runtests.import_module()
  File "/home/nmokus/emmyHome/scipy/runtests.py", line 355, in import_module
    __import__(PROJECT_MODULE)
  File "/home/nmokus/emmyHome/scipy/build-install/lib64/python3.9/site-packages/scipy/__init__.py", line 126, in <module>
    raise ImportError(msg) from e
ImportError: Error importing SciPy: you cannot import SciPy while
        being in scipy source directory; please exit the SciPy source
        tree first and relaunch your Python interpreter.
```

### SciPy/NumPy/Python version information

1.23.3 sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0) (numpy and sys only)

**Comment by rgommers** [comment]
Thanks for the detailed report @Tartopohm. The files that end up in `lib/` are the ones that get installed with:
```meson
custom_target(
  ...
  py3.get_install_dir(pure: false)
```
There was a bug in Meson that was present till 0.63.2 but fixed in 0.63.3. Before, the install plan in `build/meson-info/intro-install_plan.json` would have an absolute path for those files, and after the fix it should say `{py_platlib}/scipy/...` as the destination.

Can you check what version of Meson you have installed? And if it's older than 0.63.3, can you upgrade and try again?

**Comment by rgommers** [comment]
Ah, one more light bulb went off: if it's not fixed with Meson 0.63.3 when installing with `python dev.py build`, can you please also try if there's a difference between what you did:
```bash
$ meson setup build -Dblas=blas -Dlapack=lapack --prefix=$PWD/build-install
$ python dev.py build
```

And building a wheel and installing that:
```bash
$ meson setup build -Dblas=blas -Dlapack=lapack --prefix=$PWD/build-install
$ python -m build --wheel --no-isolation --skip-dependency-check    # you may have to install the `build` package
$ pip install dist/*.whl
$ cd ..
$ python -c "import scipy; scipy.test()"
```

Why I am asking is because building a wheel uses `intro-install_plan.json` while installing into the development dir with `python dev.py build` uses `intro-installed.json`, and they may diverge.

**Comment by Tartopohm** [comment]
It was meson 0.63.3 indeed.
I could not run ```python -m build --wheel --no-isolation --skip-dependency-check```, it failed with `Run-time dependency openblas found: NO (tried pkgconfig and cmake)`, even after the meson configuration stage.

However, I was trying to build `1.9.0`. Building the development branch worked; there is now a single `lib64` directory under `build-install`. I can run other tests if you want, otherwise I am happy to close.

**Comment by rgommers** [comment]
> However, I was trying to build `1.9.0`. Building the development branch worked; there is now a single `lib64` directory under `build-install`.

Ah, that explains it. The `pure: false` part was missing in 1.9.0, so the failure is expected. If `main` works, then `1.9.2` will work as well. So I think we're good here.

> I could not run `python -m build --wheel --no-isolation --skip-dependency-check`, it failed with `Run-time dependency openblas found: NO (tried pkgconfig and cmake)`, even after the meson configuration stage.

My suggestion ignored the `meson setup` command run before, I should have added `-Cbuilddir=build` to pick that up. Either way, I think we're good here, so I'll close. Thanks @Tartopohm
