### ISSUE TITLE
SciPy 1.9.2 for Windows does not contain msvcp140.dll

### ISSUE THREAD

**Issue by thomasjpfan** [scipy/scipy#17191]
SciPy 1.9.1 contained `msvcp140.dll` while 1.9.2 does not. For scikit-learn, the removal of `msvcp140.dll` is causing build issue because scikit-learn depended on the DLL from SciPy: https://github.com/scikit-learn/scikit-learn/issues/24612.

Coming from https://github.com/scipy/oldest-supported-numpy/issues/45 and https://github.com/scipy/scipy/pull/16842, it looks like SciPy does not need to vendor `msvcp140.dll` anymore. Was the removal of `msvcp140.dll` intentional?

**Comment by andyfaff** [comment]
See also this comment, https://github.com/scipy/scipy/issues/16787#issuecomment-1207190425, made whilst trying to develop the cibuildwheel process on windows. It points to https://github.com/scipy/oldest-supported-numpy/issues/45.

As understand those comments we (scipy) don't need to vendor msvcp140.dll.

On https://github.com/scikit-learn/scikit-learn/issues/24612 there's also questions about the 32 bit scipy wheels for windows. They are not currently part of the build plan as it requires fortran compiler tooling. Whether work on the compiler tooling will occur is in doubt as it's unclear whether there is enough demand to justify the effort.

**Comment by andyfaff** [comment]
It may be worth sklearn adding a CI entry for testing against the nightly builds of scipy (pippable from https://anaconda.org/scipy-wheels-nightly/scipy/files) to anticipate issues like this.

**Comment by thomasjpfan** [comment]
> On https://github.com/scikit-learn/scikit-learn/issues/24612 there's also questions about the 32 bit scipy wheels for windows

I suspect Scikit-learn will drop 32-bit Windows.

> It may be worth sklearn adding a CI entry for testing against the nightly builds of scipy (pippable from [anaconda.org/scipy-wheels-nightly/scipy/files](https://anaconda.org/scipy-wheels-nightly/scipy/files)) to anticipate issues like this.

Scikit-learn does test against SciPy nightly, but that nightly CI instance has `msvcp140.dll` on the system. The wheel building infrastructure, which uses the public PyPI index, has a minimal installation of Windows using a `winamd64/python` Docker image that does not contain `msvcp140.dll`.

As for this issue, if SciPy does not plan to vendor `msvcp140.dll` anymore, then scikit-learn can work around it. I can not gauge the impact of not including `msvcp140.dll` in SciPy for other projects yet.

**Comment by cmarmo** [comment]
> It may be worth sklearn adding a CI entry for testing against the nightly builds of scipy (pippable from https://anaconda.org/scipy-wheels-nightly/scipy/files) to anticipate issues like this.

https://github.com/scikit-learn/scikit-learn/pull/24446 adds scipy nightly builds to the searchable pip indexes.

**Comment by rgommers** [comment]
Re `msvcp140.dll`, I don't expect many issues. Using a Windows Docker image is rare, and C++ Python packages are rare - the combination will be very rare.

The 32-bit Windows part will be the more impactful change here, because unfortunately there's users that continue to choose that installer option (often by accident). There's no way in `pyproject.toml` metadata to distinguish between 32-bit and 64-bit Windows as far as I know, so again there's not much we can do. about this. Pip preferring older wheels over newer sdists would have solved this, but that's not moving forward much (simply lots of work that hasn't been done yet, it's still on my radar but haven't had real time for that).

**Comment by rgommers** [comment]
Scikit-learn 1.1.2 is vendoring the necessary DLL, so I'll close this. Thanks for the discussion and helping solve this, everyone!
