### ISSUE TITLE
BUG: special.betainc documentation should say "regularized incomplete beta function"

### ISSUE THREAD

**Issue by carlosgmartin** [scipy/scipy#17195]
### Describe your issue.

The documentation for [scipy.special.betainc](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.betainc.html) should say "_regularized_ incomplete beta function" instead of "incomplete beta function" everywhere, especially up front (as opposed to burying it in the notes). The latter almost universally refers to the unregularized version (see e.g. [here](https://mathworld.wolfram.com/IncompleteBetaFunction.html)). Not emphasizing this up front can cause confusion and bugs. (I had to chase down a bug caused by this.) See #1350 and #14744 for previous related issues.

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

N/A

**Comment by WarrenWeckesser** [comment]
This is mentioned in the Notes section of the [docstring](https://scipy.github.io/devdocs/reference/generated/scipy.special.betainc.html).  But I agree that it would be even better to mention this earlier.  In fact, the first line of the docstring could be "Regularized incomplete beta function" (with the Notes updated accordingly).  Similarly, the first line of the docstring for [`betaincinv`](https://scipy.github.io/devdocs/reference/generated/scipy.special.betaincinv.html) could be "Inverse of the regularized incomplete beta function."
