### ISSUE TITLE
BUG: scipy.stats.mode: inconsistent shape with `axis=None` and `keepdims=True`

### ISSUE THREAD

**Issue by jakevdp** [scipy/scipy#17214]
### Describe your issue.

Depending on whether an array is empty or full, `scipy.stats.mode` with `axis=None` and `keepdims=True` returns inconsistent results:
```python
>>> from scipy.stats import mode

>>> import numpy as np

>>> mode(np.empty((0, 1, 2)), axis=None, keepdims=True)[0].shape
(1, 1, 1)

>>> mode(np.empty((1, 1, 2)), axis=None, keepdims=True)[0].shape
(1,)
```
I'm not sure which is more correct here (the first is correct if `axis=None` should be thought of as a reduction over all axes, while the second is correct if `axis=None` should be thought of as equivalent to ravelling the input) but in either case, I think the outputs should match.

### SciPy/NumPy/Python version information

1.9.2 1.23.2 sys.version_info(major=3, minor=8, micro=2, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
Thanks; this is something I ran across recently, too. The situation with `mode` has been pretty complicated, and as soon as we can remove the recently deprecated "features" it will be a lot easier to get everything right. In the meantime, we can patch this.

**Comment by mdhaber** [comment]
The behavior of `mean` is what we want. gh-17561 will fix this.
