### ISSUE TITLE
BUG: link to roadmap broken

### ISSUE THREAD

**Issue by janusheide** [scipy/scipy#17229]
### Describe your issue.

The link to the roadmap in this file is broken:
https://github.com/scipy/scipy/blob/main/doc/ROADMAP.rst.txt

### Reproducing Code Example

```python
n/a
```

### Error message

```shell
404 :)
```

### SciPy/NumPy/Python version information

main

**Comment by tupui** [comment]
Hi @janusheide thank you for reporting. Do you want to make a PR? It should be http://scipy.github.io/devdocs/dev/roadmap.html

**Comment by janusheide** [comment]
sure, will do, was unsure if the link needed to be corrected or the file removed altogether.

**Comment by tupui** [comment]
I would remove it. @melissawm do you agree? I think we should clean all we have at the root which is doc related.

**Comment by melissawm** [comment]
I'm OK with removing duplication - seems reasonable!
