### ISSUE TITLE
Backport fix for flapack_sym_herm.pyf.src to mainatince/1.9.x

### ISSUE THREAD

**Issue by thomasjpfan** [scipy/scipy#17224]
While debugging a segfault in scikit-learn's test suite on Python 3.11 and Linux, I found that https://github.com/scipy/scipy/commit/292b643b98dc797c0ff8ab64d806f4167939f0a2 is required to prevent the segfault. For testing, I cherry-picked the commit onto `mainatince/1.9.x`, build SciPy's wheel with cibuildwheel, and it resolve the segfault issue in scikit-learn's test suite.

Can SciPy backport https://github.com/scipy/scipy/commit/292b643b98dc797c0ff8ab64d806f4167939f0a2 to `mainatince/1.9.X`?

**Edit**: For reference: this [CI test run](https://github.com/scikit-learn/scikit-learn/actions/runs/3243037218/jobs/5317180383) illustrates the error from Python. I get [this backtrace](https://gist.github.com/thomasjpfan/192b2e9439512a21e710fca0a90f4f76) when I have debug symbols on.

**Comment by thomasjpfan** [comment]
For verification, I built SciPy 1.9.3 wheels with https://github.com/scipy/scipy/commit/292b643b98dc797c0ff8ab64d806f4167939f0a2 cherry-picked, uploaded it to my [own index](https://thomasjpfan.github.io/scipy-pypi-index/scipy/) and ran scikit-learn's test suite using my index. This resolves the segfault issue and all [the tests pass](https://github.com/thomasjpfan/scikit-learn/actions/runs/3253770396)!

**Comment by tylerjereddy** [comment]
@rgommers @ilayn what do you think? As far as I can tell I simply missed a ping in gh-16528 back in July. We've already got 8 merged backport candidates after labeling that one.. shall I aim for `1.9.3` soon? There's some manual artifact downloaing/unzipping and wheel renaming on `maintenance/1.9.x` for releases but the process is a fair bit faster than it used to be at least.

**Comment by rgommers** [comment]
Yes, a `1.9.3` seems like a good idea. I think it'd be useful to do a scan through commits on `main` that weren't backported and see if anything else important may be missing. Not everyone is in the habit of thinking about backports when merging PRs.

**Comment by ilayn** [comment]
My apologies @tylerjereddy I should have marked it as a candidate instead of a mere ping. The code change is harmless for us but clearly has certain implications for downstream so I'd say at your first convenience it would be nice to have this backported either 1.9.2 backport if there will be or 1.9.3 if not.

**Comment by ev-br** [comment]
@tylerjereddy am tentatively adding a backport-candidate label so that it does not fall through the cracks again :-).

**Comment by tylerjereddy** [comment]
@ev-br I think we're good now--I already included the fix in https://github.com/scipy/scipy/pull/17239 right? `1.9.3` is on the way soon-ish

**Comment by ev-br** [comment]
Sorry for the noise then

**Comment by rgommers** [comment]
1.9.3 was released with the backport in it, so let's close this. Thanks all.
