### ISSUE TITLE
BUG: Scipy.stats.circvar outputs a value greater than 1

### ISSUE THREAD

**Issue by owadhwa** [scipy/scipy#17231]
### Describe your issue.

scipy.stats.circvar should output a value between 0 and 1, but I found a set of angles for which the circular variance is greater than 1. 

### Reproducing Code Example

```python
from scipy.stats import circmean
from scipy.stats import circvar
angles = np.array([np.pi, 0, -np.pi, 0])
circvar(angles, np.pi, -np.pi)
```

### Error message

```shell
C:\Users\wadhwao\Anaconda3\lib\site-packages\scipy\stats\morestats.py:3592: RuntimeWarning: divide by zero encountered in log
  return ((high - low)/2.0/pi)**2 * -2 * log(R)
inf
```

### SciPy/NumPy/Python version information

1.7.3 1.21.5 sys.version_info(major=3, minor=9, micro=12, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
This is indeed a bug in an old version of SciPy: the definition of `circvar` was not supported by the literature. We're at 1.9.2 now, and the bug is resolved.
