### ISSUE TITLE
BUG: 'BootstrapResult' object has no attribute 'bootstrap_distribution'

### ISSUE THREAD

**Issue by david26694** [scipy/scipy#17249]
### Describe your issue.

After running a paired bootsrap, I cannot access bootstrap distribution. I understood this was solved in https://github.com/scipy/scipy/pull/16454/files

What am I doing wrong?

### Reproducing Code Example

```python
import numpy as np
from scipy.stats import bootstrap

rng = np.random.default_rng()

n = 100
x = np.linspace(0, 10, n)
y = x + rng.uniform(size=n)

def my_statistic(x, y, axis=0):
    s1 = np.mean(x, axis=axis)
    s2 = np.mean(y, axis=axis)
    return s1 - s2

res = bootstrap((x, y), my_statistic, random_state=rng, paired=True, method='BCa', axis=0)

res.bootstrap_distribution
```

### Error message

```shell
AttributeError: 'BootstrapResult' object has no attribute 'bootstrap_distribution'
```

### SciPy/NumPy/Python version information

1.9.2 1.23.4 sys.version_info(major=3, minor=8, micro=6, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @david26694, thank you for reporting. This is just not released yet. SciPy is making a feature release every 6 months and this change is due for 1.10.

If you need this now, you can use a development version. We have wheels for conveniency https://anaconda.org/scipy-wheels-nightly/scipy

**Comment by mdhaber** [comment]
@david26694 it may be possible to install from weekly builds. https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/

**Comment by mdhaber** [comment]
Oops I didn't see that you already wrote that @tupui!
