### ISSUE TITLE
DEP: deprecate numpy aliases scipy.special.sinc

### ISSUE THREAD

**Issue by j-bowhay** [scipy/scipy#17246]
https://github.com/scipy/scipy/issues/16759#issuecomment-1280987784

> FYI: `scipy.special.sinc` is an alias for `numpy.sinc`, so we can ignore that docstring. It would be nice to deprecate and remove `sinc` from the `scipy.special` namespace, but that's a separate issue.
> 
> Similarly, `scipy.integrate.trapezoid` is an alias for `numpy.trapz`.
> 
> I have updated the script to skip these two functions.

**Comment by rgommers** [comment]
The suggestion in that linked comment was just about deprecating `special.sinc`. That seems okay, assuming it's not in use anywhere important (then we need to ask those users to update first).

Given the discussion in gh-12924, I'm -1 on touching `trapezoid`.

**Comment by j-bowhay** [comment]
Thanks @rgommers, I have updated the title accordingly
