### ISSUE TITLE
coo_matrix.todense() returns a deprecated instance np.matrix, return regular numpy array instead

### ISSUE THREAD

**Issue by bashirmindee** [scipy/scipy#17251]
[coo_matrix.todense()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.todense.html#scipy.sparse.coo_matrix.todense) currently returns [np.matrix](https://numpy.org/doc/stable/reference/generated/numpy.matrix.html) which is no longer recommended... Is it possible to return np.ndarray instead ?

**Comment by j-bowhay** [comment]
The `toarray()` method does what you are looking for.

[https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.toarray.html#scipy.sparse.coo_matrix.toarray](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.toarray.html#scipy.sparse.coo_matrix.toarray)
