### ISSUE TITLE
ENH: CI: Add a `[skip cirrus]` markup to skip running Cirrus jobs.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#17252]
It would be nice to be able to skip the Cirrus jobs, especially in their current state.  It looks like it might be as simple as adding something like 

```
    if "[skip cirrus]" in dct["message"]:
        return []
```

at the appropriate place in [`.cirrus.star`](https://github.com/scipy/scipy/blob/main/.cirrus.star), but that idea is the result of about 5 minutes of code browsing.  @andyfaff, would something like that work?

**Comment by andyfaff** [comment]
It's inbuilt to cirrus-ci. See https://github.com/andyfaff/scipy/pull/36/checks?check_run_id=8970766219 where I created a PR against my own fork with `[skip cirrus]` in the commit message.

Your suggestion would also work @WarrenWeckesser. Note however, that there's nothing wrong with the infrastructure of the `cirrus_general_ci` runs, there are 15 failing tests that we need to address.

**Comment by WarrenWeckesser** [comment]
That's great, thanks @andyfaff.

I'll submit a PR to update the development docs on CI [Skipping](https://scipy.github.io/devdocs/dev/contributor/continuous_integration.html#skipping).

> Note however, that there's nothing wrong with the infrastructure of the cirrus_general_ci runs, there are 15 failing tests that we need to address.

Got it. I had an issue where a problem occurred in the Circle CI build that I couldn't reproduce locally.  I wanted to disable everything except Circle CI to avoid wasting computer time while debugging the issue.

**Comment by andyfaff** [comment]
>  I wanted to disable everything except Circle CI to avoid wasting computer time while debugging the issue.

You have my sympathy. Debugging in CI can be a bind.

**Comment by WarrenWeckesser** [comment]
For the record, here's what the Cirrus CI docs on [Writing Tasks](https://cirrus-ci.org/guide/writing-tasks/) say:



> Skip CI Completely
>
>Just include [skip ci] or [skip cirrus] in the first line or last line of your commit message in order to skip CI execution for a commit completely.
>
> If you push multiple commits at the same time, only the last commit message will be checked for [skip ci] or [ci skip].
>
> If you open a PR, PR title will be checked for [skip ci] or [ci skip] instead of the last commit message on the PR branch.

That means a commit message such as

```
Something important here.

[skip cirrus]
[skip azp]
```
would not actually cause CirrusCI to be skipped.

Also, until I see it work, I wouldn't assume that "[skip cirrus] *in* the first line or last line" (emphasis added) means it can be anywhere in the line.  Conceivably, they could require that it be the only text in the line.

Moreover, based on the note about PRs in the Cirrus docs and the comment in  `.cirrus.star`, it is not clear if including `[skip cirrus]` in a commit message even works with a PR.  Over in https://github.com/scipy/scipy/pull/17259, the CirrusCI jobs started even though `[skip cirrus]` was in the last line of the commit message (but it wasn't the only text in that line, and the text was not in the PR title).

**Comment by andyfaff** [comment]
There are no tasks generated for PR #17260, https://cirrus-ci.com/build/4593111846879232. This has the same type of commit message that you used.

**Comment by andyfaff** [comment]
The following code in the `.cirrus.star` script obtains the actual commit message used, whether it be in a PR, merge, push/whatever.

```
    SHA = env.get("CIRRUS_CHANGE_IN_REPO")
    url = "https://api.github.com/repos/scipy/scipy/git/commits/" + SHA
    dct = http.get(url).json()
    if "[wheel build]" in dct["message"]:
        return fs.read("ci/cirrus_wheels.yml")
```

**Comment by andyfaff** [comment]
`CIRRUS_CHANGE_IN_REPO` is the SHA of the last commit. The code I mentioned above grabs information from GH on that commit message, placing it into `dct`. One of the keys is `message` which is the commit message.
