### ISSUE TITLE
BUG: Issue with Blender

### ISSUE THREAD

**Issue by CaBaccoRic** [scipy/scipy#17254]
### Describe your issue.

Apparently Blender does not like SciPy package.
Tried installing it from GitHub desktop, from powershell, from Python, Anaconda and the scripting console of Bleder as well.

### Reproducing Code Example

```python
ImportError('The `scipy` install you are using seems to be broken, (extension modules cannot be imported), please try reinstalling.')
```

### Error message

```shell
ImportError('The `scipy` install you are using seems to be broken, (extension modules cannot be imported), please try reinstalling.')
```

### SciPy/NumPy/Python version information

py3.7

**Comment by tupui** [comment]
Hi @CaBaccoRic, thank you for reporting. But we don't support Blender's possible integration. Also note that we now only support Python >=3.8.
