### ISSUE TITLE
BUG: 'multivariate_normal_frozen' object has no attribute 'allow_singular' error showing only on Ubuntu 20.04 and not Windows 10

### ISSUE THREAD

**Issue by alyssa-rose** [scipy/scipy#17297]
### Describe your issue.

Exact same code has different behavior on Ubuntu 20.04 vs Windows 10.

Attempting to use `multivariate_normal()` from `scipy.stats` throws the error `AttributeError: 'multivariate_normal_frozen' object has no attribute 'allow_singular'` when on Ubuntu, **but runs without issue on Windows 10.**

Both are using `scipy==1.9.3` with Python 3.8.13

### Reproducing Code Example

```python
from scipy.stats import multivariate_normal

# some variables/information excluded due to proprietary information
# variable 'new_observation' is same size as data.mean()
param_dict = dict()
param_dict["mu"] = data.mean()
param_dict["sigma"] = data.cov()

param_dict["multi_norm_obj"] = multivariate_normal(mean=param_dict["mu"], cov=param_dict["sigma"], allow_singular=True)

pdf_observation = param_dict["multi_norm_obj"].pdf(new_observation)
```

### Error message

```shell
Traceback (most recent call last):
  File "/home/<name>/<file>.py", line 155, in observation_given_mode
    pdf_observation = param_dict["multi_norm_obj"].pdf(
  File "/home/<name>/miniconda3/envs/pm_v1/lib/python3.8/site-packages/scipy/stats/_multivariate.py", line 776, in pdf
    return np.exp(self.logpdf(x))
  File "/home/<name>/miniconda3/envs/pm_v1/lib/python3.8/site-packages/scipy/stats/_multivariate.py", line 770, in logpdf
    if self.allow_singular and (self.cov_info.rank < self.dim):
AttributeError: 'multivariate_normal_frozen' object has no attribute 'allow_singular'
```

### SciPy/NumPy/Python version information

1.9.3 1.22.4 sys.version_info(major=3, minor=8, micro=13, releaselevel='final', serial=0)

**Comment by tirthasheshpatel** [comment]
Can you check if you are deleting the `param_dict["multi_norm_obj"].allow_singular` attribute anywhere in your Ubuntu 20.04 code?

**Comment by alyssa-rose** [comment]
> Can you check if you are deleting the `param_dict["multi_norm_obj"].allow_singular` attribute anywhere in your Ubuntu 20.04 code?

**Comment by alyssa-rose** [comment]
> Can you check if you are deleting the `param_dict["multi_norm_obj"].allow_singular` attribute anywhere in your Ubuntu 20.04 code?

That attribute is not deleted anywhere in the code. The code ran on Ubuntu is from the same repo and branch as the code on Windows, so even if the attribute was deleted, the same error would've been thrown when running on Windows.

**Comment by tirthasheshpatel** [comment]
Can you share your code and data? I am not able to reproduce the error from the MRE you have given in the description.

**Comment by alyssa-rose** [comment]
Using dummy data, and am not able to share code.

**mu_val** = np.array([0.308239, 0.468255, 0.412909, 0.752947, 0.351932])

**sigma_val** = np.array([[0.047492, -0.006228, 0.001946, 0.003943, -0.009426],
                      [-0.006228, 0.058038, -0.010722, -0.007658, 0.010560],
                      [0.001946, -0.010722, 0.070474, -0.004314, 0.001608],
                      [0.003943, -0.007658, -0.004314, 0.041661, 0.000663],
                      [-0.009426, 0.010560, 0.001608, 0.000663, 0.036341]])

**obs** = np.array([0.625, 0.45783808, 0, -1.66004162, 0])


code would therefore be of the form:

```
from scipy.stats import multivariate_normal
mv = multivariate_normal(mu_val, sigma_val, allow_singular=True)
mv.pdf(obs)
```
The above throws an error on Ubuntu, but not Windows. However,

```
from scipy.stats import multivariate_normal
multivariate_normal.pdf(obs, mu_val, sigma_val, allow_singular=True)
```
does NOT throw the error on either Ubuntu or Windows.

**Comment by mdhaber** [comment]
@tirthasheshpatel are you able to reproduce this based on the example above? For convenience, here is an executable snippet:

```python3
import numpy as np
from scipy.stats import multivariate_normal
mu_val = np.array([0.308239, 0.468255, 0.412909, 0.752947, 0.351932])
sigma_val = np.array([[0.047492, -0.006228, 0.001946, 0.003943, -0.009426],
                      [-0.006228, 0.058038, -0.010722, -0.007658, 0.010560],
                      [0.001946, -0.010722, 0.070474, -0.004314, 0.001608],
                      [0.003943, -0.007658, -0.004314, 0.041661, 0.000663],
                      [-0.009426, 0.010560, 0.001608, 0.000663, 0.036341]])
obs = np.array([0.625, 0.45783808, 0, -1.66004162, 0])
mv = multivariate_normal(mu_val, sigma_val, allow_singular=True)
mv.pdf(obs)  # 1.1325359140091029e-33
```

@alyssa-rose Note that when SciPy 1.10 is released, you will be able to sidestep this if you're still having trouble:
```python3
from scipy.stats import Covariance
w, v = np.linalg.eigh(sigma_val)
w[1] = 0  # make the covariance singular
cov = Covariance.from_eigendecomposition((w, v))
mv = multivariate_normal(mu_val, cov)
mv.pdf(v.T + mu_val)
# array([9.30469927e-08, 0.00000000e+00, 1.65904952e-04, 3.97440507e-03,
#        1.74537096e-02])
```
This works without specifying `allow_singular` even if the Covariance matrix is singular.

In any case, I can't see how the `allow_singular` attribute wouldn't exist. There are exactly two occurrences of `.allow_singular` in `_multivariate.py`, and they are both in this relatively straightforward excerpt:

https://github.com/scipy/scipy/blob/de80faf9d3480b9dbb9b888568b64499e0e70c19/scipy/stats/_multivariate.py#L709-L776

The `allow_singular` attribute is stored in the first line of the initializer that gets called when the MVN is frozen. It is not deleted, so it should be present when `pdf` calls `logpdf`. 

How did you install SciPy 1.9.3 @alyssa-rose?
Since there will be a workaround in 1.10, shall we consider this closed if nobody can reproduce the problem?
