### ISSUE TITLE
Docs webserver unavailable - connection refused 

### ISSUE THREAD

**Issue by cappetta** [scipy/scipy#17316]
heads up in case you dont know: 

`curl: (7) Failed to connect to docs.scipy.org port 443 after 36 ms: Connection refused`

**Comment by rossbar** [comment]
Possibly related: there have been problems with intersphinx inventory resolution for scipy. See e.g. https://app.circleci.com/pipelines/github/numpy/numpy/16300/workflows/c8bc40f0-9063-4914-a224-0745962e2ed8/jobs/28403

**Comment by bskinn** [comment]
@rossbar Yep, intersphinx is broken due to the entire docs site being down.

**Comment by tupui** [comment]
FYI, the team is aware of the issue it was reported on the doc repo.

**Comment by rgommers** [comment]
It's back up. Thanks for reporting.

**Comment by cappetta** [comment]
saw this update earlier in the week - many thanks for the quick assist!
