### ISSUE TITLE
ENH: Clarify that ndimage.find_objects returns slices ordered by indices

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#17312]
### Is your feature request related to a problem? Please describe.

The docstring of find_objects does not specify the order in which the slices are returned, but (per #277 and https://github.com/scipy/scipy/issues/13648#issuecomment-791853680) it seems that it returns them "in order", i.e. first the slices corresponding to label 1, then the slice corresponding to label 2, etc.  This is nice, but not obvious given the current docstring:
```
    Find objects in a labeled array.

    Parameters
    ----------
    input : ndarray of ints
        Array containing objects defined by different labels. Labels with
        value 0 are ignored.
    max_label : int, optional
        Maximum label to be searched for in `input`. If max_label is not
        given, the positions of all objects are returned.

    Returns
    -------
    object_slices : list of tuples
        A list of tuples, with each tuple containing N slices (with N the
        dimension of the input array). Slices correspond to the minimal
        parallelepiped that contains the object.

        Each tuple If a number is missing,
        None is returned instead of a slice.
```
e.g. it could easily have been the case that slices are simply returned in the order in which objects are seen when raster scanning through the image.  (The remark about None and missing numbers hints at the actual behavior, but is quite implicit.)

### Describe the solution you'd like.

Clarify that label `l` corresponds to index `l - 1` in the returned array.

### Describe alternatives you've considered.

N/A

### Additional context (e.g. screenshots, GIFs)

N/A

**Comment by harivamsi9** [comment]
Hey I would like to pick up this issue

**Comment by j-bowhay** [comment]
Thanks @harivamsi9, @vinayakdsci already has a pr open so it would be best not duplicate effort here however there are plenty of other good first issues.
