### ISSUE TITLE
BUG: Rotation matrix is changed with scipy.spatial.transform.Rotation

### ISSUE THREAD

**Issue by akvilonBrown** [scipy/scipy#17324]
### Describe your issue.

Greetings, 
I think I encountered some bug in processing a 3D rotation matrix.
I tried to retrieve Euler angles, but they made the wrong rotation.
Even when I retrieve the matrix back, it is altered incorrectly.
I think this failure has something to do with the internal storage of rotation objects as quaternions.
But I don't have expertise enough to debug through the source code, and I haven't found description in the documentation about conversion limitations between rotation formats, except gimbal lock.
There is a code example of the initial rotation matrix and the wrong output during conversions.
Even the first retrieved matrix **rotmatrix11** (without conversions) is wrong.
I dubbed my question on _StackOverflow_
https://stackoverflow.com/questions/74265765/rotation-matrix-is-changed-with-scipy-spatial-transform-rotation 
The rotation matrix seems correct in terms of orthonormality and the determinant.

### Reproducing Code Example

```python
from scipy.spatial.transform import Rotation as R
import numpy as np

rotmatrix1 = np.array([[ 0.86345719, -0.48700394,  0.13141101],
       [ 0.02362667, -0.221185  , -0.97494563],
       [-0.5038685 , -0.84492861,  0.1794775 ]])

print(f"rotmatrix1:\n  {rotmatrix1}")

r1 = R.from_matrix(rotmatrix1)
rotmatrix11 = r1.as_matrix()
angles1 = r1.as_euler("xyz")
print(f"angles1:  {angles1}")
print(f"rotmatrix11:\n  {rotmatrix11}")
print("-------------------------------")

r2 = R.from_euler("xyz", angles1)
rotmatrix2 = r2.as_matrix()
print(f"rotmatrix2:\n  {rotmatrix2}")

r3 = R.from_matrix(rotmatrix2)
angles2 = r3.as_euler("xyz")
print(f"angles2:  {angles2}")
r4 = R.from_euler("xyz", angles2)
rotmatrix3 = r4.as_matrix()
print(f"rotmatrix3:\n  {rotmatrix3}")
```

### Error message

```shell
Output (all matrices are expected to be the same or at least do the same rotation job, but they differ):
rotmatrix1:
  [[ 0.86345719 -0.48700394  0.13141101]
 [ 0.02362667 -0.221185   -0.97494563]
 [-0.5038685  -0.84492861  0.1794775 ]]
angles1:  [ 2.91754028  0.33066594 -0.51471512]
rotmatrix11:
  [[ 0.82327846 -0.4171921  -0.3849199 ]
 [-0.46561791 -0.88418854 -0.03755775]
 [-0.32467296  0.21014609 -0.9221855 ]]
-------------------------------
rotmatrix2:
  [[ 0.82327846 -0.4171921  -0.3849199 ]
 [-0.46561791 -0.88418854 -0.03755775]
 [-0.32467296  0.21014609 -0.9221855 ]]
angles2:  [ 2.91754028  0.33066594 -0.51471512]
rotmatrix3:
  [[ 0.82327846 -0.4171921  -0.3849199 ]
 [-0.46561791 -0.88418854 -0.03755775]
 [-0.32467296  0.21014609 -0.9221855 ]]
```

### SciPy/NumPy/Python version information

1.7.3 1.21.6 sys.version_info(major=3, minor=7, micro=15, releaselevel='final', serial=0)

**Comment by akvilonBrown** [comment]
UPD:  the example shows how the matrices differ from the original one.  Further manipulations with altered matrix don't change it.

**Comment by jgborch** [comment]
@nboudrie and I will be taking on this issue.

**Comment by rkern** [comment]
`rotmatrix1` is not a rotation matrix. It incorporates a reflection.

```                                                                                                                                                                                                                  
|2> np.linalg.det(rotmatrix1)                                                                                                                                                                                        
-1.0000000047994289
```

**Comment by jgborch** [comment]
Unfortunately, we will not be able to take this issue on.

**Comment by chibai** [comment]
> `rotmatrix1` is not a rotation matrix. It incorporates a reflection.
> 
> ```
> |2> np.linalg.det(rotmatrix1)                                                                                                                                                                                        
> -1.0000000047994289
> ```

Is there any approach to transfer the approximate rotmatrix into precise rotmatrix???
For example, let's say rotation_matrix_normalization??

**Comment by WarrenWeckesser** [comment]
A reflection is not an "approximate rotation", and as @rkern pointed out, `rotmatrix1` has a reflection.  If you are going to use the `Rotation` class, you must ensure that the input to the class is actually a pure rotation matrix.

I'm going to close the issue, as the original problem is the result of an incorrect input.

**Comment by akvilonBrown** [comment]
Thank you for your clarification and for your time.
My knowledge gap didn't allow me to reveal it in time.
I was misled by some custom code snippets on the web which can handle negative determinants and stated that it was OK for rotation.
Now I see that in **scipy** documentation that determinant +1 is a mandatory condition.
Indeed reflection is quite likely to occur when I use PCA results as a basis for the rotational matrix.

**Comment by akvilonBrown** [comment]
> Is something similar happening here? Could you explain what is happening?

Hello,
No, it's a different problem.
Actually, not a problem for the task because both sets of angles [ -150, -180, -120 ] and [ 30., 0., 60] give the same rotation matrix, and both rotate to the desired position.
https://math.stackexchange.com/questions/1972196/determining-the-unique-set-of-euler-angles-that-produce-a-set-of-3-left-hand
Euler angles are not unique for a particular task. They could be unique when they have some constraints.
The Scipy documentation mentions about optimizations somewhere (I can't find it now).
As for me, it produces a more optimal version of rotation because the object rotates with smaller angles.
For example, suppose you have some physical object with mass and momentum that you need to rotate quickly - then smaller angles are more helpful.
Besides, Euler angles suffer from Gimbal lock, but not for this example, otherwise you would have a warning.

**Comment by DavidBoja** [comment]
Thank you very much for the quick response @akvilonBrown !

It does make sense for practical reasons to chose the smaller angle.

I noticed that this choosing of the smaller angle only happens when the second euler angle (that rotates around the y-ax in my case -- i was using the 'xyz' convention) is not constrained to the range <-90,90> degrees.
That is why in my second example above (where the second angle is -83)

> euler_angles2 = [ -114, -83, - 68 ]
> rotation2 = R.from_euler("xyz", euler_angles2,degrees=True)
> print(rotation2.as_euler("xyz",degrees=True))

the euler angles remain the same.
Thank you once again for the help.
