### ISSUE TITLE
ENH: Implement Beta negative binomial distribution

### ISSUE THREAD

**Issue by jachymb** [scipy/scipy#17330]
### Is your feature request related to a problem? Please describe.

This is a distribution I would find useful in the library https://en.wikipedia.org/wiki/Beta_negative_binomial_distribution 
I would like to be able to calculate the probability mass function etc. like with other distributions.

**Comment by dschmitz89** [comment]
@steppi @WarrenWeckesser : would you have time to review if I submit a PR for this one?

I did a quick experiment using the following Wikipedia sources.

Sampling:
![image](https://github.com/scipy/scipy/assets/40656107/6477acf0-17d0-4e1a-9276-6d455a11f83c)

PMF:
![image](https://github.com/scipy/scipy/assets/40656107/148f2c04-8900-497a-bbe4-777e561c1667)

```python

import numpy as np
from scipy import special as sc
import matplotlib.pyplot as plt

rng = np.random.default_rng(seed=234346)
a = 100
b = 20
r = 500
p = rng.beta(a, b, size=10000)
x = rng.negative_binomial(r, p)

k = np.linspace(0, x.max(), 500)
logpmf = sc.gammaln(r + k) + sc.betaln(a + r, b + k) - sc.betaln(a, b) - sc.gammaln(k + 1) - sc.gammaln(r)
plt.hist(x, density=True, bins='auto', histtype='stepfilled', alpha=0.2)
plt.plot(k, np.exp(logpmf))
plt.show()
``` 

![image](https://github.com/scipy/scipy/assets/40656107/b5bbb080-964a-463d-84bf-018203d02e33)

A formula for the CDF is given by [Wolfram](https://reference.wolfram.com/language/ref/BetaNegativeBinomialDistribution.html):

![image](https://github.com/scipy/scipy/assets/40656107/683a5740-1be1-41f9-8ee3-d1d46134c7df)

**Comment by chrisb83** [comment]
@dschmitz89 Hi, I could take a look at your PR.
