### ISSUE TITLE
ENH: change term zero to root in newton

### ISSUE THREAD

**Issue by upstartjohnvandivier** [scipy/scipy#17335]
### Is your feature request related to a problem? Please describe.

in [root finding](https://en.wikipedia.org/w/index.php?title=Root-finding_algorithms&oldid=1101747227), we try to find `x | f(x) == 0`

here, x is sometimes called a root of the function or a zero of the function.

This request is to use the term 'root' instead of the term 'zero' because it's technically confusing that both x and y can be seen as a "zero value"

consider the specific case of documenting the `tol` argument to the `newton` method:
https://github.com/scipy/scipy/blob/v1.9.3/scipy/optimize/_zeros_py.py#L94-L370

tol is labeled as "The allowable error of the zero value." but it is applied along the x-axis only, not to the "zero value" along the y-axis

### Describe the solution you'd like.

it would be much clearer if scipy sticks to the term "root" to identify x within root-finding algorithms

### Describe alternatives you've considered.

you could also actually apply tol to the output variable. in many cases this speeds things up although i don't think it's backwards compatible. it also arguably doesn't solve the root issue 😉  of confusing parameter naming

**Comment by dschmitz89** [comment]
I ran into this naming confusion too in the `special` module too: the terms roots and zeros are used both.
With regards to the root finders: I see that issue for two root finders and for the `cython optimize zeros` description:

![image](https://user-images.githubusercontent.com/40656107/200185555-f3b5d082-d7fb-4a63-8f59-911a4bc1f034.png)

In special for example:

![image](https://user-images.githubusercontent.com/40656107/200185646-020ac24f-ef42-4145-822c-70f8d9e3c5a0.png)

I would propose to at change _zeros_ to _roots_ in all of the one line descriptions and the section heading in `special`.

**Comment by mdhaber** [comment]
@j-bowhay would you be willing to submit a PR? If you don't mind, I've removed the "good first issue" label because it is not always immediately obvious whether the text is referring to the `x` or `f(x)`, and this issue is not as simple as replacing all occurrences of the word "zero" with "root".

**Comment by j-bowhay** [comment]
Yes happy to although cant guarantee I'll get to it before 1.10 branches. With regard to the scope just get optimise done first or both optimise and special?

**Comment by mdhaber** [comment]
I'd prefer to review optimize only.

**Comment by WarrenWeckesser** [comment]
I think it would be best to focus on the consistent use of `root` in the root-finding functions in `optimize`.  In other contexts, the use of [`zero`](https://en.wikipedia.org/wiki/Zero_of_a_function) has a long history, and I think it would be more confusing to switch to *root*.  For example, with Bessel functions, *zeros* is widely used:

* https://en.wikipedia.org/wiki/Bessel_function#Zeros_of_the_Bessel_function
* https://mathworld.wolfram.com/BesselFunctionZeros.html
* Chapter XV of the classic ["A treatise on the theory of Bessel functions"](https://archive.org/details/treatiseontheory00watsuoft/page/n3/mode/2up) is "The zeros of Bessel functions"

**Comment by j-bowhay** [comment]
@mdhaber I did another search for zeros that should be roots and couldn't fine any so I think this is done

**Comment by mdhaber** [comment]
Ok, thanks!
