### ISSUE TITLE
BUG: Meson build unconditionally probes for pythran, despite SCIPY_USE_PYTHRAN=0

### ISSUE THREAD

**Issue by thesamesam** [scipy/scipy#17336]
### Describe your issue.

Originally reported downstream in Gentoo at https://bugs.gentoo.org/878361.

It appears that scipy's Meson build will unconditionally search for pythran, even with `export SCIPY_USE_PYTHRAN=0`.

In meson.build, we have:
```
cython = find_program('cython')
pythran = find_program('pythran')
```

Note that find_program's 'required' option defaults to on (https://mesonbuild.com/Reference-manual_functions.html#find_program).

### Reproducing Code Example

```python
-
```

### Error message

```shell
[...]
Library m found: YES
Fortran compiler for the host machine: gfortran (gcc 12.2.1 "GNU Fortran (Gentoo Hardened 12.2.1_p20221029 p1) 12.2.1 20221029")
Fortran linker for the host machine: gfortran ld.bfd 2.39
Compiler for Fortran supports arguments -Wno-conversion: YES
Program cython found: YES (/usr/sbin/cython)
Program pythran found: NO

../../meson.build:72:0: ERROR: Program 'pythran' not found or not executable

A full log can be found at /var/tmp/portage/dev-python/scipy-1.9.3/work/scipy-1.9.3/.mesonpy-lo4vu62u/build/meson-logs/meson-log.txt
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/gpep517", line 4, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/gpep517/__main__.py", line 322, in main
    return func(args)
  File "/usr/lib/python3.8/site-packages/gpep517/__main__.py", line 122, in build_wheel
    print(build_wheel_impl(args, args.wheel_dir), file=out)
  File "/usr/lib/python3.8/site-packages/gpep517/__main__.py", line 105, in build_wheel_impl
    wheel_name = backend.build_wheel(str(wheel_dir), args.config_json)
  File "/usr/lib/python3.8/site-packages/mesonpy/__init__.py", line 986, in build_wheel
    with _project(config_settings) as project:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.8/site-packages/mesonpy/__init__.py", line 948, in _project
    with Project.with_temp_working_dir(
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.8/site-packages/mesonpy/__init__.py", line 777, in with_temp_working_dir
    yield cls(source_dir, tmpdir, build_dir)
  File "/usr/lib/python3.8/site-packages/mesonpy/__init__.py", line 682, in __init__
    self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
  File "/usr/lib/python3.8/site-packages/mesonpy/__init__.py", line 713, in _configure
    self._meson(
  File "/usr/lib/python3.8/site-packages/mesonpy/__init__.py", line 696, in _meson
    return self._proc('meson', *args)
  File "/usr/lib/python3.8/site-packages/mesonpy/__init__.py", line 691, in _proc
    subprocess.check_call(list(args))
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=/var/tmp/portage/dev-python/scipy-1.9.3/work/scipy-1.9.3/.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=/usr', '/var/tmp/portage/dev-python/scipy-1.9.3/work/scipy-1.9.3', '/var/tmp/portage/dev-python/scipy-1.9.3/work/scipy-1.9.3/.mesonpy-lo4vu62u/build']' returned non-zero exit status 1.
 * ERROR: dev-python/scipy-1.9.3::gentoo failed (compile phase):
 *   Wheel build failed
```

### SciPy/NumPy/Python version information

1.9.3

**Comment by eli-schwartz** [comment]
The use of an environment variable here to set SCIPY_USE_PYTHRAN instead of `-Duse_pythran=true` is a bit awkward... code organization wise, it seems painful to check this in find_program (but if it was just a single get_option() away, this would be so much easier).

In that sense, this is a bit of just https://github.com/mesonbuild/meson-python/issues/54 again.

**Comment by rgommers** [comment]
The code is written to use the env var: https://github.com/scipy/scipy/blob/main/scipy/meson.build#L73-L79. It's just ignored by the `pythran` detection. So you can currently build without _using_ Pythran, as long as it's installed. The CI job which uses `SCIPY_USE_PYTHRAN=0` still uses `numpy.distutils`, otherwise we'd have made this a bit more user-friendly already.

I'll open a PR.

**Comment by rgommers** [comment]
And @eli-schwartz, yes I agree with your comment - but I'd like to put off dealing with that unless we no longer have `numpy.distutils` builds at all. At that time we may also want to decide whether we keep Pythran optional or mandatory.

**Comment by rgommers** [comment]
Should be fixed by gh-17346

**Comment by thesamesam** [comment]
Thanks! Any chance of a backport to 1.9.x?

**Comment by eli-schwartz** [comment]
From #17263

> - no real intention to do 1.9.4 but prep just in case
> - current plan is to send the email proposing 1.10 schedule to mailing list on Nov. 9th, similar to last November cycle

**Comment by rgommers** [comment]
I've added a backport label to the PR, just in case we do need to do another bugfix release.
