### ISSUE TITLE
BUG: scipy.spatial.KDtree can return impossible indices

### ISSUE THREAD

**Issue by AnotherSamWilson** [scipy/scipy#17342]
### Describe your issue.

I am the maintainer of [miceforest](https://github.com/AnotherSamWilson/miceforest/issues/64), which calls KDtree.query many times.

I have an array of size 806 that I attempt to find the nearest neighbors in. `KDtree.query` is returning 806 as a possible index, but the maximum should be 805.

This appears to be a rare bug. Unfortunately I only have a series of pickled numpy arrays that reproduce the problem. Here is a picture of the issue:
![image](https://user-images.githubusercontent.com/44655289/200003778-95f8f833-74a9-4e74-93e8-f325cf643831.png)

If it helps you all, I can upload the pickled arrays somewhere to help with debugging.

### Reproducing Code Example

```python
import dill
from scipy.spatial import KDTree
candidate_preds = dill.load(open("support/candidate_preds.pkl", "rb"))
bachelor_preds = dill.load(open("support/bachelor_preds.pkl", "rb"))
kd_tree = KDTree(candidate_preds, leafsize=16, balanced_tree=False)
_, knn_indices = kd_tree.query(
    bachelor_preds, k=5, workers=-1
)
print(knn_indices.max())
print(candidate_preds.shape)

```
```


### Error message

```shell
No Error Message, just incorrect results.
```

### SciPy/NumPy/Python version information

1.7.3 1.22.4 sys.version_info(major=3, minor=9, micro=6, releaselevel='final', serial=0)

**Comment by j-bowhay** [comment]
Could you provide a plain text example?

**Comment by AnotherSamWilson** [comment]
I discovered that this occurs when an array with `inf` values is passed:

```
from scipy.spatial import KDTree
import numpy as np
candidate_preds = np.random.uniform(0,10,size=(100, 4))
bachelor_preds = np.random.uniform(0, 10, size=(10, 4))
bachelor_preds[0,0] = np.inf
kd_tree = KDTree(candidate_preds, leafsize=16, balanced_tree=False)
_, knn_indices = kd_tree.query(
    bachelor_preds, k=5, workers=-1
)
print(knn_indices[0])
```

I'm not sure if this is intended behavior, I personally think it makes sense for kdtree to fail in this case.

**Comment by sturlamolden** [comment]
Does it only happen in case of an inf, or are the other situations as well?

**Comment by sturlamolden** [comment]
This issue can be closed. It is not a bug but intentional and documented behavior. 

806 is returned to indicate missing neighbor.

**Comment by j-bowhay** [comment]
Thanks for investigating @sturlamolden, indeed this is documented behaviour.
