### ISSUE TITLE
DOC: Cleanup developer documentation

### ISSUE THREAD

**Issue by astrojuanlu** [scipy/scipy#17373]
At the PyData NYC sprints, we are following the instructions to create a development environment for SciPy and we are finding some orphan pages, incomplete procedures, or dead-ends. I'm dumping here some notes with the idea of sending a follow-up pull request to cleanup things a bit.

- https://docs.scipy.org/doc/ contains a link to the "Scipy developer guide" pointing to `https://docs.scipy.org/doc/scipy-dev/reference/dev/`, which then redirects to `http://scipy.github.io/devdocs/dev/`. But from any of the version-specific docs like https://docs.scipy.org/doc/scipy-1.9.3/, one can go to an outdated version of the dev docs, like `https://docs.scipy.org/doc/scipy-1.9.3/dev/index.html`. Wondering if it's worth having pointers to all these old dev instructions, or whether we could replace them all with the `dev` version (also using HTTPS in the URL).

After the CoC and the "Ways to Contribute", the important sections of the dev docs are [Contributor quickstart guide](https://scipy.github.io/devdocs/dev/dev_quickstart.html), [Development workflow](https://scipy.github.io/devdocs/dev/contributor/development_workflow.html), and [SciPy contributor guide](https://scipy.github.io/devdocs/dev/contributor/contributor_toc.html).

- The first line of the quickstart says

> After [getting the source code from GitHub](https://scipy.github.io/devdocs/dev/gitwash/development_setup.html#git-start), there are three steps to start contributing:

First, the `https://scipy.github.io/devdocs/dev/gitwash/development_setup.html` page is not in any toctree, so the left navigation bar appears empty, even if it's not marked as `:orphan:`. But most importantly, even though this is the only page describing how to setup GitHub and make a fork, the `git clone` instructions are outdated (they don't include the `git submodule update --init`). Should we update that page and make it the entry point for cloning the repository?

- Still in the quickstart, there are a couple of pointers to the [system-level dependencies](https://scipy.github.io/devdocs/dev/contributor/building.html#system-level). This page does not appear in any toctree either, although this one is marked as `:orphan:`, so I'm not sure if those are up to date or still recommended. In addition, this page contains pointers to things like `https://scipy.github.io/devdocs/dev/contributor/osx.html`, which [according to @rgommers "should be removed"](https://scipy-community.slack.com/archives/C03JL2YGCNR/p1667924647211819?thread_ts=1667924213.041649&cid=C03JL2YGCNR). I'm wondering what other pages there should be removed too?
- In the Development workflow, it's said

> This guide assumes that you have created your own fork (copy) of the SciPy repository, cloned the repository on your own machine, and built SciPy from this source code. If you haven’t, check the [Development environment](https://scipy.github.io/devdocs/dev/contributor/contributor_toc.html#dev-env) pages appropriate to your system.

But none of the pages there (System-level dependencies, conda_guide, ubuntu_guide, quickstart_docker, quickstart_gitpod) actually explain how to fork & clone the repository. Maybe we should point to the `gitwash/development_setup` page mentioned above?

And there are other things I'm observing, but probably starting with these and deciding which pages to move/remove would be a good starting point.

This is essentially a continuation of the issue I opened a couple of years ago https://github.com/scipy/scipy/issues/12633 which @melissawm already addressed in https://github.com/scipy/scipy/pull/15947.

**Comment by dschmitz89** [comment]
The old scripts instead of dev.py are also still mentioned in:
* The docs contributor [guide](http://scipy.github.io/devdocs/dev/contributor/rendering_documentation.html)
* Testing [guide](http://scipy.github.io/devdocs/dev/contributor/runtests.html)
