### ISSUE TITLE
BUG:  "SystemError: initialization of beta_ufunc raised unreported exception" in >= 1.9.2 with Valgrind

### ISSUE THREAD

**Issue by RUrlus** [scipy/scipy#17377]
### Describe your issue.

Hi all,

Our Valgrind CICD run broke after upgrading to Scipy >= 1.9.2 from 1.9.1.
The error does not occur without valgrind.

Due to the valgrind involvement making an MRE is though. If needed I can create a MRE repo and add a maintainer.

Some additional info:
* OS: Ubuntu-latest
* valgrind amd64 1:3.15.0-1ubuntu9.1

Bindings and generator:
* Pybind11 v2.10.1 
* ninja v1.10.2.4

Extension does include a number of Numpy headers but nothing special.

Valgrind is run with:

```PYTHONMALLOC=malloc valgrind --leak-check=yes --track-origins=yes  python -m pytest```

See [Workflow file](https://github.com/RUrlus/ModelMetricUncertainty/blob/stable/.github/workflows/valgrind.yml) for details.

### Reproducing Code Example

```python
import scipy.stats
```

### Error message

```shell
/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/sklearn/utils/fixes.py:19: in <module>
    import scipy.stats
/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/scipy/stats/__init__.py:467: in <module>
    from ._stats_py import *
/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/scipy/stats/_stats_py.py:46: in <module>
    from . import distributions
/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/scipy/stats/distributions.py:10: in <module>
    from . import _continuous_distns
/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/scipy/stats/_continuous_distns.py:31: in <module>
    import scipy.stats._boost as _boost
/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/scipy/stats/_boost/__init__.py:1: in <module>
    from scipy.stats._boost.beta_ufunc import (
E   SystemError: initialization of beta_ufunc raised unreported exception
```

### SciPy/NumPy/Python version information

1.9.3 1.23.3 sys.version_info(major=3, minor=10, micro=7, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @RUrlus, thank you for reporting. This was already reported earlier this week in #17368. I am closing this issue to not duplicate efforts.

**Comment by RUrlus** [comment]
Sorry, I looked when I started the issue but not when I actually submitted it.
