### ISSUE TITLE
BUG: stats.binom: Boost binomial distribution edge case bug?

### ISSUE THREAD

**Issue by ssvb** [scipy/scipy#17388]
### Describe your issue.

When q is zero, the `binom.ppf` function returns -1.0. And when p is 1.0, the result should be `n` regardless of q.

### Reproducing Code Example

```python
from scipy.stats import binom

print(binom.ppf(q = 0.0, n = 4, p = 0.5)) # prints -1.0 (but should be 0.0?)
print(binom.ppf(q = 0.3, n = 4, p = 1.0)) # prints 0.0 (but should be 4.0?)
```

### Error message

```shell
-
```

### SciPy/NumPy/Python version information

1.8.1 1.23.1 sys.version_info(major=3, minor=9, micro=13, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
In the first example, the CDF at -1 _is_ 0, so the result is not wrong.
```
print(binom.cdf(k=-1, n=4, p=0.5))  # 0
``` 
SciPy's convention is `ppf` methods with `q=0` is to return `-1`. The rationale is discussed here.

**Comment by ssvb** [comment]
> SciPy's convention for `ppf` methods at `q=0` is to return `-1`. The rationale is discussed in [#15967 (comment)](https://github.com/scipy/scipy/pull/15967#issuecomment-1095817726).

This is a bit unfortunate, because such choice makes a simulation of the outcome of 100M dice rolls via `binom.ppf` more complicated than necessary and potentially error prone. The following code needs to handle edge cases (see comments):

```Python
from scipy.stats import binom
from random import random

def diceDistrib(k, N):
  result = []
  n = N
  for i in range(0, k - 1):
    q = random()
    p = 1.0 / (k - i) # be sure not to get p == 1.0 here
    if q > 0: # dodge -1 when q == 0.0
      cnt = int(binom.ppf(q, n, p))
    else:
      cnt = 0
    result.append(cnt)
    n -= cnt
  result.append(n)
  return result

print(diceDistrib(6, 100_000_000)) # [16664115, 16666144, 16677962, 16660692, 16663181, 16667906]
```

<details>
<summary>Yes, a better solution would be to use `binom.rvs` for such simulation, but I wanted to see if `binom.ppf` can also do the job and compare results.</summary>

```Python
from scipy.stats import binom

def diceDistrib(k, N):
  result = []
  n = N
  for i in range(0, k):
    cnt = binom.rvs(n, 1.0 / (k - i))
    result.append(cnt)
    n -= cnt
  return result

print(diceDistrib(6, 100_000_000)) # [16667252, 16668575, 16663811, 16674710, 16661590, 16664062]
```
</details>

**Comment by mdhaber** [comment]
Sorry. It wasn't my choice. I defended it in the past only to justify why we can't change it on a whim. Changing it would be backward incompatible, and SciPy has a lot of users, so more would be needed to justify such a change.
That said, [this](https://chanzuckerberg.com/eoss/proposals/scipy-fundamental-tools-for-biomedical-research/) was just announced today, and we will be working on gh-15928 as part of the grant. We can definitely consider changing convention there.

**Comment by mdhaber** [comment]
@mckib2 can you see what Boost does here (without the wrapper)?
```python3
from scipy.stats import binom
binom.ppf(q = 0.3, n = 4, p = 1.0)  # prints 0.0 (but should be 4.0?)
```

**Comment by mdhaber** [comment]
@mborland would you be willing to check whether Boost's binomial PPF has a bug with `p = 1`?

**Comment by mborland** [comment]
> @mborland would you be willing to check whether Boost's binomial PPF has a bug with `p = 1`?

Yes. I'll cross reference this issue from if there is a problem on our end.

**Comment by mborland** [comment]
@mdhaber the fix has been merged into Boost.Math.

**Comment by mdhaber** [comment]
Great, thanks!
