### ISSUE TITLE
BUG: Documentation for `scipy.optimize.differential_evolution` is incomplete, reference link is broken

### ISSUE THREAD

**Issue by Dominik1123** [scipy/scipy#17398]
### Describe your issue.

The different possible choices for [`scipy.optimize.differential_evolution`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.differential_evolution.html), parameter `strategy`, are not explained in the documentation. Currently, it lists 12 different values:

```
    strategy : str, optional
        The differential evolution strategy to use. Should be one of:
            - 'best1bin'
            - 'best1exp'
            - 'rand1exp'
            - 'randtobest1exp'
            - 'currenttobest1exp'
            - 'best2exp'
            - 'rand2exp'
            - 'randtobest1bin'
            - 'currenttobest1bin'
            - 'best2bin'
            - 'rand2bin'
            - 'rand1bin'
        The default is 'best1bin'.
```

Only one of them, the default, is explained in the doc string section **Notes**. There is [reference `[2]`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.differential_evolution.html#r108fc14fa019-2) but the provided link is broken. Also [reference `[1]`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.differential_evolution.html#r108fc14fa019-1) does not seem to contain details on what the different strategies mean.
Since this is a critical parameter of the function, it would be good if it is documented properly, so that users can make an informed choice.

### Reproducing Code Example

```python
This is a docs issue.
```

### Error message

```shell
This is a docs issue.
```

### SciPy/NumPy/Python version information

v1.9.3

**Comment by andyfaff** [comment]
Seems like ref 2 is stale. https://www.osti.gov/servlets/purl/1163659 also explains what the strategies represent. They give references within that article as well. 
Can also reference that paper as "Qiang, JI. (2014). A Unified Differential Evolution Algorithm for Global Optimization. Lawrence Berkeley National Laboratory. Retrieved from https://escholarship.org/uc/item/41b84414"

**Comment by Femme-js** [comment]
@tupui If this doc enhancement seems important, Can I pick this up?

**Comment by mdhaber** [comment]
@Femme-js a PR would be welcome.

**Comment by mkiffer** [comment]
I will try to work on this too.

**Comment by meaviral17** [comment]
Hi. This project is interesting. I will try to work on this too

**Comment by mkiffer** [comment]
Can you access the changes I have made? I just wasn’t able to format them correctly and haven’t had a chance to fix them :)
