### ISSUE TITLE
BUG: Transposed CSR Matrix is no longer a CSR matrix type

### ISSUE THREAD

**Issue by peterkim95** [scipy/scipy#17396]
### Describe your issue.

A CSR matrix is of CSR matrix type. But transposing it, the matrix becomes no longer a CSR Matrix type.

### Reproducing Code Example

```python
import numpy as np
from scipy.sparse import csr_matrix

m = csr_matrix((3, 4), dtype=np.int8)

print(isinstance(m, csr_matrix)) # True, as expected
print(isinstance(m.transpose(), csr_matrix)) # Should be true, but false!
```

### Error message

```shell
None see code example above
```

### SciPy/NumPy/Python version information

1.7.1 1.20.3 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @peterkim95, thank you for reporting. From the code, doing `transpose` is creating a `csc_matrix` and not a `csr_matrix`.

**Comment by perimosocordiae** [comment]
This is working as intended: many operations on scipy.sparse matrix types will change the format, to enable efficient algorithms.
