### ISSUE TITLE
DOC: comparison of optimizers in optimization guide

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#17404]
Hi everyone,

the optimization [user guide](https://scipy.github.io/devdocs/tutorial/optimize.html) currently does not contain any form of easily accessible comparison of the different solver capabilties.

I think this would be helpful for many users as the typical questions for someone looking to solve an optimization problem are (for example been requested in #16191):
* How do I formulate my problem with this package?
* Which solver is probably a good fit for me?

As a first start of discussion, I created a google doc table to compare the local and global solvers:
https://docs.google.com/spreadsheets/d/1PNpOcy99qfn-ip168vL4Qskc3bpybJP7e2vpuhrQKN4/edit#gid=0

Let me know if you think that an important category is missing.

**Comment by rgommers** [comment]
Good idea @dschmitz89. The SciPy 1.0 paper has this table though: https://www.nature.com/articles/s41592-019-0686-2/tables/1. We should repurpose that.

**Comment by jburke52** [comment]
Hello @dschmitz89 and @rgommers, I'll be working on this suggested enhancement and will pull when it's ready.

**Comment by lucascolley** [comment]
gh-17491 worked on this and received some substantial review, but it went stale and the head repository was deleted. If anyone else would like to pick this up, it would be a good idea to look at what was done over there first.

**Comment by koko1928** [comment]
> Hi everyone,
> 
> the optimization [user guide](https://scipy.github.io/devdocs/tutorial/optimize.html) currently does not contain any form of easily accessible comparison of the different solver capabilties.
> 
> I think this would be helpful for many users as the typical questions for someone looking to solve an optimization problem are (for example been requested in #16191):
> 
> * How do I formulate my problem with this package?
> * Which solver is probably a good fit for me?
> 
> As a first start of discussion, I created a google doc table to compare the local and global solvers: https://docs.google.com/spreadsheets/d/1PNpOcy99qfn-ip168vL4Qskc3bpybJP7e2vpuhrQKN4/edit#gid=0
> 
> Let me know if you think that an important category is missing.

I think it sounds nice.

**Comment by SauravChittal** [comment]
Is this issue up for a contribution?

**Comment by dschmitz89** [comment]
@koko1928 : would you be interested to contribute something along the lines of my table to the documentation?

**Comment by koko1928** [comment]
> @koko1928 : would you be interested to contribute something along the lines of my table to the documentation?

Hi @dschmitz89  ,

Thank you for considering my contribution. I'm definitely interested in contributing to the documentation with the comparison table you've initiated. However, before I proceed, I would appreciate some guidance on how to integrate the table into the documentation effectively. Could you provide me with some details on the preferred format and any specific documentation guidelines I should follow? Additionally, if there's any particular procedure for submitting this kind of update to the documentation, I'd like to understand that as well.

Looking forward to your response.

Best,
koko1928

**Comment by dschmitz89** [comment]
> > @koko1928 : would you be interested to contribute something along the lines of my table to the documentation?
> 
> Hi @dschmitz89 ,
> 
> Thank you for considering my contribution. I'm definitely interested in contributing to the documentation with the comparison table you've initiated. However, before I proceed, I would appreciate some guidance on how to integrate the table into the documentation effectively. Could you provide me with some details on the preferred format and any specific documentation guidelines I should follow? Additionally, if there's any particular procedure for submitting this kind of update to the documentation, I'd like to understand that as well.
> 
> Looking forward to your response.
> 
> Best, koko1928

To get this documentation update into SciPy, you need to create a PR which will be reviewed. A good reference is our developer documentation: [see here](https://docs.scipy.org/doc/scipy/dev/dev_quickstart.html). Once you have your development environment running, hopefully you can build the documentation locally on your machine (invoke via `python dev.py doc`). Then have a look at the [documentation guide](https://docs.scipy.org/doc/scipy/dev/contributor/rendering_documentation.html#contributing-docs).

The closed PR https://github.com/scipy/scipy/pull/17491 can give you an example. The trickiest part about this new table is in my opinion how to add it so that it renders nicely. Sphinx is not always the easiest tool for such tasks. If there are further questions, feel free to ping me here. :)

**Comment by koko1928** [comment]
I created a PR. Please leave a review.
