### ISSUE TITLE
ENH: need to get a length on sparse matrix

### ISSUE THREAD

**Issue by wph524** [scipy/scipy#17406]
### Is your feature request related to a problem? Please describe.

The problem is that I tried to use sparse lil matrix from pyclustering.cluster.center_initializerl.kmeans_plusplus_initializer but there is an error that a length is needed. After use toarray() there is an unable to allocate memory error.

### Describe the solution you'd like.

Give a length on sparse matrix

**Comment by perimosocordiae** [comment]
Can you include the exact error message you observed?

**Comment by wph524** [comment]
I am sorry that the exact error message is not available now. But I can say that it is occured when using pyclustering.cluster.center_initializer.kmeans_plusplus_initializer.
















在 2022-11-12 22:36:57，"CJ Carey" ***@***.***> 写道：

Can you include the exact error message you observed?
