### ISSUE TITLE
DOC: There is no general `scipy.sparse` page in the user guide

### ISSUE THREAD

**Issue by rossbar** [scipy/scipy#17403]
I searched the issue tracker with sparse + the documentation label and didn't see this reported; apologies if I've missed it.

Something I noticed while searching the [scipy user guide](https://docs.scipy.org/doc/scipy-1.9.3/tutorial/index.html): there doesn't appear to be a top-level document for the `sparse` subpackage. Instead there is an article about sparse eigenvalue problems that seems to be serving as a stand-in, though it is focused specifically on sparse linalg and arpack. AFAICT there is no general introduction to the `scipy.sparse` package as a whole in the user guide.

IMO it'd be a nice improvement to add such a document to the user guide.

**Comment by melissawm** [comment]
Good point - the main user guide landing page is undergoing some changes in #17322 - I can at least leave a stub for this page there.
