### ISSUE TITLE
BUG: scipy.interpolate.interp1d left hang

### ISSUE THREAD

**Issue by pedro-acunha** [scipy/scipy#17419]
### Describe your issue.

I am having problems with `scipy.interp1d` function. Even the most simple example provided in the package documentation, is left hanging.

Everything works fine until I actually try to use the `interpolate.interp1d` function.

I already removed scipy, using pip, and installed it again. The problem still persisted.

### Reproducing Code Example

```python
x = np.arange(0, 10)
y = np.exp(-x/3.0)
f = interpolate.interp1d(x, y)

xnew = np.arange(0, 9, 0.1)
ynew = f(xnew)   # use interpolation function returned by `interp1d`
plt.plot(x, y, 'o', xnew, ynew, '-')
plt.show()
```
```


### Error message

```shell
The code is left hang and nothing happen.
```

### SciPy/NumPy/Python version information

1.8.0 1.21.0 sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)

**Comment by ev-br** [comment]
Suspect that something is wrong with your python install and/or scipy build. How did you install scipy?
Here's how I'd investigate:

- Does it still hang if you remove the plotting call? (best, remove the whole of matplotlib from this script)
- Does pure numpy work, if you only keep `x = np.arange(0, 10); print(x)`, does it print it?
- If it does but `interp1d` call hangs, does it hang on `from scipy import interpolate` or `f = interpolate.inter1d(...)` or `f(xnew)`?

**Comment by pedro-acunha** [comment]
Hi @ev-br ,
The scipy installation was done using `pip install scipy`.

The code hangs in `f(xnew)`.

I was able to make scipy run, as expected, in a conda environment. I am however puzzled about this particular problem. I have been using scipy for a while without any problems, up until now.

**Comment by ev-br** [comment]
Definitely an installation glitch it is.
A first suspect is using `pip` in a conda environment. It can have weird effects, as they say. 
Maybe try a more recent scipy version (why would you use 1.8.0 still) either with pip in a fresh virtualenv, or with from conda-forge in a clean conda environment?
