### ISSUE TITLE
ENH: scipy.fft commonly used functions wrapper

### ISSUE THREAD

**Issue by Moooongo** [scipy/scipy#17420]
### Is your feature request related to a problem? Please describe.

There are some oftenly used function pairs in scipy.fft, such as the pair fft and fftfreq. It would be a time-save/nice-to-have of a function that wraps the function pairs alike. 

### Describe the solution you'd like.

Assume two numpy arrays of the same length, containing information of evenly spaced time and some measured signal. If one wants to find the frequency component of the signal, one might write:
`transformed_data = fft(signal_array)`
`frequency = fftfreq(
n = len(signal_array),
d = time[1] - time[0] 
)# assume time is evenly spaced`
`return (frequency, transformed_data)`

These two steps are so frequently used in daily signal processing, that it might be worthwhile to have a dedicated function for them. There could also be some other function sequences that I am unware of, and it could be a good idea to gather more of these before making any changes.

**Comment by musteng** [comment]
Is this issue good for my lecture assignment @melissawm ?

**Comment by melissawm** [comment]
@musteng I believe this still requires a bit of discussion among maintainers to decide if this is something worth having. Please take a look at the ["good first issue" label](https://github.com/scipy/scipy/issues?q=is%3Aopen+label%3A%22good+first+issue%22+sort%3Aupdated-desc) as those have already been triaged. Cheers!

**Comment by lucascolley** [comment]
I think that we generally avoid implementing helpers which are 'trivial' for users to do in a few lines to avoid API bloat, so I'm not sure if there will be much support for this. Feel free to send a message to the mailing list if you would like to gauge interest.

**Comment by Moooongo** [comment]
> I think that we generally avoid implementing helpers which are 'trivial' for users to do in a few lines to avoid API bloat, so I'm not sure if there will be much support for this. Feel free to send a message to the mailing list if you would like to gauge interest.

Thanks. I agree it's probably not worth it.
