### ISSUE TITLE
ENH: Add power (exponent) operator for Rotation objects

### ISSUE THREAD

**Issue by scottshambaugh** [scipy/scipy#17429]
### Is your feature request related to a problem? Please describe.

At the moment, scipy.spatial.transform.Rotation objects can be composed with the multiplication operator. The power operator is a natural extension of this to compose a rotation with itself (ie, apply the same rotation multiple times).

### Describe the solution you'd like.

For an exponent `n` where `n` is a positive integer, the interpretation is straightforward:
`R * R == R**2`

For `n=1`, the original rotation should be returned.
`R == R**1`

For `n=0`, the identity rotation should be returned, but I'm open to arguments that this should be left undefined.
`Rotation.from_quat([0, 0, 0, 1]) == R**0`

For integer `n<0`, the obvious interpretation would be to return the inverse rotation, but I'm more ambivalent on whether this is implemented or left undefined. A future improvement could be to add both this and the division operator as a representation for inversion.
`R.inv() * R.inv() == R**-2`
`R1 / R2 = R1 * R2.inv()`

For non-integer `n`, we could consider it as a 'scaling' of the rotation, and apply `n` as a factor to the angle in the rotation vector interpretation. However, this results in underconstrained behavior. I think it makes more sense to leave it undefined for now.
For example, consider a 180 deg rotation raised to a 3/2 power, where it is unclear in which direction to apply the additional 90 deg: 
```python
R1 = Rotation.from_rotvec(np.pi * np.array([0, 0, 1]))
R2 = Rotation.from_rotvec(-np.pi * np.array([0, 0, 1]))
R1 == R2
R1a = R1 ** 3/2 == Rotation.from_rotvec(3/2 * np.pi * np.array([0, 0, 1]))
R2a = R2 ** 3/2 == Rotation.from_rotvec(-3/2 * np.pi * np.array([0, 0, 1]))
R1a != R2a
```

### Describe alternatives you've considered.

Instead of `R*R == R**2`, one might be tempted to write `R*R == 2*R`. However this introduces confusion since in many of the representations of a rotation multiplying all the factors by a scalar does not change the meaning, and this breaks with the current analogy of multiplication standing in for composition.

**Comment by rkern** [comment]
The real benefit of the quaternion representation of rotations is that the [power operation with real exponents is quite well-defined](https://en.wikipedia.org/wiki/Quaternion#Exponential,_logarithm,_and_power_functions).

**Comment by scottshambaugh** [comment]
Quaternion exponentials are well defined (the equation there is equivalent to what I said about scaling the angle), but we are dealing here with quaternions as a representation of the fundamental object: rotations. Having the equation doesn’t resolve rotations for non-integer exponents being non-unique.

**Comment by rkern** [comment]
FWIW, in your example, `R1 != R2`. They'll yield the same matrix representation, sure, but we use the richer representation for good reasons. This is one of them. We make use of it to implement `Slerp` (what essentially amounts to real-valued powers between 0 and 1).

**Comment by scottshambaugh** [comment]
Sure, but those are only not equivalent because of floating point round-off. An orientation in space is 'stateless' - it does not matter how you got there. Removing the ambiguity in which direction to represent the exact 180 deg poles is the reason for [my MR here](https://github.com/scipy/scipy/pull/17334), which chooses the positive representation (a somewhat arbitrary choice). 
```
>>> R1.as_quat()
array([0.000000e+00, 0.000000e+00, 1.000000e+00, 6.123234e-17])
>>> R2.as_quat()  # equivalent to [0, 0, 1, -6.123234e-17]
array([-0.000000e+00, -0.000000e+00, -1.000000e+00,  6.123234e-17])
```

Slerp has baked into it the assumption that you are travelling the shortest absolute angle to a new orientation. However, the sqrt of a 240 degree rotation could result in 2x -60 degree rotations, 2x 120 deg rotations, 2x 300 deg rotations, etc. I'm not totally opposed to just choosing the smallest absolute angle for noninteger exponents, but I do think it could be a potential source of confusion for people. For example, this would result in exponents of `n` and `1/n` not necessarily being inverses:
```
>>> R = Rotation.from_rotvec([0, 0, 120], degrees=True)
>>> ((R ** 2) ** 0.5).as_rotvec(degrees=True)
array([  -0.,   -0., -60.])
```

But there is value in it, do you think the pros outweigh the cons?

**Comment by rkern** [comment]
Maybe it's due to round-off, but it makes the same decisions in multiple places such that we can represent both a rotation of `+pi` and `-pi` around an axis as distinct things. You can see this by going from the quaternion to the rot-vec:

```
[~]                                                                                                                                                                                                                  
|43> R1 = Rotation.from_quat([0., 0, 1, 0])                                                                                                                                                                          

[~]                                                                                                                                                                                                                  
|44> R2 = Rotation.from_quat([0., 0, -1, 0])                                                                                                                                                                         

[~]                                                                                                                                                                                                                  
|45> R1.as_rotvec()                                                                                                                                                                                                  
array([0.        , 0.        , 3.14159265])

[~]                                                                                                                                                                                                                  
|46> R2.as_rotvec()                                                                                                                                                                                                  
array([ 0.        ,  0.        , -3.14159265])
```

If your PR removes that, then I'm a little less happy with it. Note that a rotation of `+/-pi` seems to be a special case here. The usual double-cover in the quaternion representation usually collapses to the same result in the rotation-vector.

```
[~]                                                                                                                                                                                                                  
|58> R3 = Rotation.from_quat([0.0, 0.0, np.sin(np.pi/3), np.cos(np.pi/3)])                                                                                                                                           

[~]                                                                                                                                                                                                                  
|59> R3._quat                                                                                                                                                                                                        
array([[0.       , 0.       , 0.8660254, 0.5      ]])

[~]                                                                                                                                                                                                                  
|60> R4 = Rotation.from_quat([0.0, 0.0, -np.sin(np.pi/3), -np.cos(np.pi/3)])                                                                                                                                         

[~]                                                                                                                                                                                                                  
|61> R4._quat                                                                                                                                                                                                        
array([[ 0.       ,  0.       , -0.8660254, -0.5      ]])

[~]                                                                                                                                                                                                                  
|62> R3.as_rotvec()                                                                                                                                                                                                  
array([0.       , 0.       , 2.0943951])

[~]                                                                                                                                                                                                                  
|63> R4.as_rotvec()                                                                                                                                                                                                  
array([-0.       , -0.       ,  2.0943951])
```

So I'm not really sure that our behavior with respect to `+/-pi` is indicative of much; it's a weird special case.

It is true that the non-integral power of a quaternion is multiple-valued, regardless of the double-cover and the `+/-pi` behavior. I see no particular problem with non-integer powers taking the principal root of the quaternion power, much the same way that we do with complex numbers. We have no problem having `np.sqrt(-1j*-1j)` return `+1j`. It's somewhat arbitrary, but it has practical applications that most people actually have in mind when they request such a thing about rotations (not just quaternions).

**Comment by scottshambaugh** [comment]
Yeah, `+/-pi` is an edge case with the current setup. There's no principled reason why that single point should be the only place that exhibits the double coverage as is currently the case with the rotvec representation. The other option to completely mapping to a single cover is to extend the double coverage to the entire rotation space, but I think that's even more obviously a bad idea.

Copy that on extending to non-integer powers, I can add that in.
