### ISSUE TITLE
`python dev.py lint` may not match what the CI lint job does

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#17434]
The below was reported by @HDembinski in a comment on gh-15489. That should be considered a bug if it's indeed not matching, so this should be looked at.

> `python dev.py` lint should also run`flake8`, but for the PEP8 part should be the same. Can you point to a branch where you see one failing but the other passing?

Sorry, I don't have a clean reproducer, but I think this patch here 
https://github.com/scipy/scipy/pull/17237/commits/0545e5e0c3e6601e584e3afda88a8df0cec74795
was a change that I made after `python dev.py lint` gave me no complains (about my new code), but `python tools/lint_diff.py` run by the CI job found those issues. I haven't looked into the implementation, but these two commands apparently do not apply the same rules.

**Comment by ev-br** [comment]
Cross-ref https://github.com/scipy/scipy/issues/17394

**Comment by j-bowhay** [comment]
see https://github.com/scipy/scipy/issues/17394#issuecomment-1311594807

To summarise,  `python dev.py lint` runs `tools/lint_diff.py` and then also runs flake8 on the entire code base which is why the output is different to the ci job. A pretty easy fix would just be to separate these two functionality (maybe  `python dev.py lint` and  `python dev.py flake8`)

**Comment by rgommers** [comment]
That sounds like a good idea. And then maybe also a `dev.py ci` which runs a bunch of checks at once? E.g. also `mypy`? And we may even want to extend that with an option to use `act` to run build/test CI jobs locally?

**Comment by j-bowhay** [comment]
> That sounds like a good idea.

Will work on submitting a pr for this part

**Comment by rgommers** [comment]
This is indeed a duplicate of gh-17394. See https://github.com/scipy/scipy/issues/17394#issuecomment-1328335872 for what is happening. I'll close this issue.
