### ISSUE TITLE
ENH: ECDF in scipy.

### ISSUE THREAD

**Issue by hadjipantelis** [scipy/scipy#17431]
### Is your feature request related to a problem? Please describe.

When in Python, calculating an ECDF requires loading `statsmodels`' [`ECDF`](https://www.statsmodels.org/dev/generated/statsmodels.distributions.empirical_distribution.ECDF.html) function. It is a really big dependency for something relatively small.

### Describe the solution you'd like.

A function to calculate the empirical distribution function of a given sample.

### Describe alternatives you've considered.

Using `statsmodels`.

### Additional context (e.g. screenshots, GIFs)

It was mentioned as a `numpy` feature requrest at some point but they decided against it (reasonably) as it is more of a `scipy` feature: https://github.com/numpy/numpy/issues/9057.

**Comment by mdhaber** [comment]
The KS test functions have a very nice way of doing this. I'll add it shortly because I'm working on a function for survival analysis and a lot of code can be shared.
