### ISSUE TITLE
BUG: AttributeError: 'float' object has no attribute 'shape'

### ISSUE THREAD

**Issue by bhaskoro-muthohar** [scipy/scipy#17441]
### Describe your issue.

I tried to plot QQ plot by using stats.probplot, but raised `AttributeError`.

![image](https://user-images.githubusercontent.com/35159954/202650805-241c2c91-f614-4d8d-8f10-1c728ab2abef.png)

### Reproducing Code Example

```python
stats.probplot(
    df['col'], 
    dist="norm", 
    plot=pylab
    )
pylab.show()
```

### Error message

```shell
AttributeError: 'float' object has no attribute 'shape'
```

### SciPy/NumPy/Python version information

1.7.3 1.21.6 sys.version_info(major=3, minor=7, micro=15, releaselevel='final', serial=0)

**Comment by j-bowhay** [comment]
Thanks for reporting. Does adding `df['col'].to_numpy()` change anything? If not could you please provide a reproducible example that can be ran.

**Comment by mdhaber** [comment]
I cannot reproduce this in `main`, at least not without `pylab`, which makes me suspect that it's a `pylab` issue if anything.
```python3
import numpy as np
import pandas as pd
from scipy import stats
df = pd.DataFrame({'x': np.random.rand(100), 'col': np.random.rand(100)})
stats.probplot(
    df['col'], 
    dist="norm", 
    )
```

```
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
ax = plt.subplot()
df = pd.DataFrame({'x': np.random.rand(100), 'col': np.random.rand(100)})
stats.probplot(
    df['col'], 
    dist="norm", 
    plot=ax
    )
```

```python3
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
df = pd.DataFrame({'x': np.random.rand(100), 'col': np.random.rand(100)})
stats.probplot(
    df['col'], 
    dist="norm", 
    plot=plt
    )
plt.show()
@bhaskoro-muthohar please try using `matplotlib` directly instead of `pylab` and upgrading to the latest version of SciPy (1.9.3). If the problem persists, please reopen this issue, providing complete code to reproduce the problem (including any code to generate a Pandas dataframe) and including a complete stack trace of the error (i.e. so we can see where the `AttributeError` is generated). I'll close in the meantime.

**Comment by bhaskoro-muthohar** [comment]
> Thanks for reporting. Does adding `df['col'].to_numpy()` change anything? If not could you please provide a reproducible example that can be ran.

It does not work, still raised the same error.

Here I'm using google colab and using bigquery public data, you need to use bigquery api tho.
```python
from google.colab import auth

auth.authenticate_user()
```


```python
%load_ext google.cloud.bigquery
```

```python
%%bigquery test --project [your BQ project name]
SELECT name, SUM(number) as count
FROM `bigquery-public-data.usa_names.usa_1910_current`
GROUP BY name
ORDER BY count DESC
```

```python
test.head(10)
```
![image](https://user-images.githubusercontent.com/35159954/202833850-12ef4887-3027-49b8-90c9-d7459e1ce212.png)

```python
from scipy import stats

stats.probplot(
    test['count'].to_numpy(), 
    dist="norm", 
    )
pylab.show()
```

raised
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-9-eaf90185aa1a>](https://localhost:8080/#) in <module>
      1 stats.probplot(
      2     test['count'],
----> 3     dist="norm",
      4     # plot=pylab
      5     )

3 frames
[/usr/local/lib/python3.7/dist-packages/scipy/stats/morestats.py](https://localhost:8080/#) in probplot(x, sparams, dist, fit, plot, rvalue)
    602     if fit:
    603         # perform a linear least squares fit.
--> 604         slope, intercept, r, prob, _ = stats.linregress(osm, osr)
    605 
    606     if plot is not None:

[/usr/local/lib/python3.7/dist-packages/scipy/stats/_stats_mstats_common.py](https://localhost:8080/#) in linregress(x, y, alternative)
    153     #   ssxm = mean( (x-mean(x))^2 )
    154     #   ssxym = mean( (x-mean(x)) * (y-mean(y)) )
--> 155     ssxm, ssxym, _, ssym = np.cov(x, y, bias=1).flat
    156 
    157     # R-value

<__array_function__ internals> in cov(*args, **kwargs)

[/usr/local/lib/python3.7/dist-packages/numpy/lib/function_base.py](https://localhost:8080/#) in cov(m, y, rowvar, bias, ddof, fweights, aweights, dtype)
   2516             w *= aweights
   2517 
-> 2518     avg, w_sum = average(X, axis=1, weights=w, returned=True)
   2519     w_sum = w_sum[0]
   2520 

<__array_function__ internals> in average(*args, **kwargs)

[/usr/local/lib/python3.7/dist-packages/numpy/lib/function_base.py](https://localhost:8080/#) in average(a, axis, weights, returned)
    413 
    414     if returned:
--> 415         if scl.shape != avg.shape:
    416             scl = np.broadcast_to(scl, avg.shape).copy()
    417         return avg, scl

AttributeError: 'float' object has no attribute 'shape'
```

**Comment by bhaskoro-muthohar** [comment]
> 

I'm tried to use `matplotlib` but still raised the same error. The issue is on the dataframe that produced by bigquery magic I used https://cloud.google.com/python/docs/reference/bigquery/latest/magics, when I tried to read dataframe manually by using `pd.read_csv('xxx.csv')` the plot works just fine!

![image](https://user-images.githubusercontent.com/35159954/202834154-e61e2e8b-d1b2-48ce-959a-976f02d46f8e.png)

**Comment by mdhaber** [comment]
> you need to use bigquery api tho.

There are other ways. For instance, you could create a gist with the data included in the file, or you could find a smaller example that reproduces the problem by looking at the data in the Series you extract.
What is the dtype of `count`? We'd expect it to be an integer, but does it turn out to be something else? Does it have infs or nans?

**Comment by bhaskoro-muthohar** [comment]
OK, I think I've found the issue. Probplot will raise an error if the data frame input is coming from Bigquery, otherwise it's fine.

Here's the example:

```python
from google.cloud import bigquery
from scipy import stats
import pandas as pd

client = bigquery.Client(project='[insert_your_project_name_here]')

sample_count = 2000
df = client.query('''
  SELECT 
    name,
    SUM(number) AS count
  FROM `bigquery-public-data.usa_names.usa_1910_current`
  GROUP BY 1
  ''').to_dataframe()

stats.probplot(
    df["count"], 
    dist="norm",
    )
pylab.show()
```
raised
```python
from google.cloud import bigquery
from scipy import stats
import pandas as pd

client = bigquery.Client(project='[insert_your_project_name_here]')

sample_count = 2000
df = client.query('''
  SELECT 
    name,
    SUM(number) AS count
  FROM `bigquery-public-data.usa_names.usa_1910_current`
  GROUP BY 1
  ''').to_dataframe()

stats.probplot(
    df["count"], 
    dist="norm", 
    plot=pylab
    )
pylab.show()
```

But, if I write the data frame from BQ to csv then write the csv again as data frame, it works just fine!
```python
from google.cloud import bigquery
from scipy import stats
import pandas as pd

client = bigquery.Client(project='[insert_your_project_name_here]')

sample_count = 2000
df = client.query('''
  SELECT 
    name,
    SUM(number) AS count
  FROM `bigquery-public-data.usa_names.usa_1910_current`
  GROUP BY 1
  ''').to_dataframe()

df.to_csv('df.csv')

df2 = pd.read_csv('df.csv')

stats.probplot(
    df2["count"], 
    dist="norm",     )
pylab.show()
```

**Comment by bhaskoro-muthohar** [comment]
It's weird. Any thoughts sir @mdhaber @j-bowhay ?

**Comment by WarrenWeckesser** [comment]
Almost certainly, the data type of the data in the Pandas DataFrame create by bigquery is `object`.  I can recreate the problem with numpy with data type `object`:

```
In [140]: from scipy.stats import probplot

In [141]: a = np.arange(20.0).astype(object)

In [142]: probplot(a, dist='norm')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[... snip ...]
File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:554, in average(a, axis, weights, returned, keepdims)
    550     avg = np.multiply(a, wgt,
    551                       dtype=result_dtype).sum(axis, **keepdims_kw) / scl
    553 if returned:
--> 554     if scl.shape != avg.shape:
    555         scl = np.broadcast_to(scl, avg.shape).copy()
    556     return avg, scl

AttributeError: 'float' object has no attribute 'shape'
```
Try passing `df['col'].to_numpy(dtype=float)` to `probplot`.

**Comment by bhaskoro-muthohar** [comment]
> Almost certainly, the data type of the data in the Pandas DataFrame create by bigquery is `object`. I can recreate the problem with a numpy array with data type `object`:
> 
> ```
> In [140]: from scipy.stats import probplot
> 
> In [141]: a = np.arange(20.0).astype(object)
> 
> In [142]: probplot(a, dist='norm')
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> [... snip ...]
> File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/numpy/lib/function_base.py:554, in average(a, axis, weights, returned, keepdims)
>     550     avg = np.multiply(a, wgt,
>     551                       dtype=result_dtype).sum(axis, **keepdims_kw) / scl
>     553 if returned:
> --> 554     if scl.shape != avg.shape:
>     555         scl = np.broadcast_to(scl, avg.shape).copy()
>     556     return avg, scl
> 
> AttributeError: 'float' object has no attribute 'shape'
> ```
> 
> Try passing `df['col'].to_numpy(dtype=float)` to `probplot`.

Yess, it's worked like a charm! Thanks!!

**Comment by mdhaber** [comment]
It looks like the average of something is a Python `float` rather than a NumPy scalar. What is `type(sum(df["count"]))`?
