### ISSUE TITLE
BUG: Why can't I get the right result with quad？

### ISSUE THREAD

**Issue by yuyuwo** [scipy/scipy#17443]
### Describe your issue.

This is my code:
`y = lambda x:1/(3.81*(2*np.pi)**0.5)*np.exp(-(x-116)**2/(2*3.81**2))
y1= quad(y,0,np.inf)
print(y1)`
This is result:
(8.871948827438051e-22, 1.718414783764695e-21)

### Reproducing Code Example

```python
y = lambda x:1/(3.81*(2*np.pi)**0.5)*np.exp(-(x-116)**2/(2*3.81**2))
y1= quad(y,0,np.inf)
print(y1)
```

### Error message

```shell
(8.871948827438051e-22, 1.718414783764695e-21)
```

### SciPy/NumPy/Python version information

1.7.3

**Comment by rkern** [comment]
There is only a very tiny portion of that integration region that has any significant mass. `quad()` isn't magic; it has to sample the function at a finite number of places, and it happened to not find ones near `116` where all the mass is. Using a large, but finite range like `(0, 1000)` would help.

```
|30> y = lambda x:1/(3.81*(2*np.pi)**0.5)*np.exp(-(x-116)**2/(2*3.81**2)) 
...> y1 = quad(y, 0, 1000) 
...> print(y1)                                                                                                                                                                                                       
(0.9999999999999993, 1.2774716999478267e-10)
```

**Comment by yuyuwo** [comment]
@rkern Thank you for your answer. It really helped. 
But why can't I get the correct result when I integrate another long function? Is there any solution?This is my code: 
>`y=lambda  x:0.19*9.31*10**(8)/(10/60*(2*np.pi)**0.5*3.81)*np.exp(-116/(8.3145*400)*10**3-9.31*10**(8)/10*60*
         x/8.314*np.exp(-x/(8.314*400))/(x/(8.314*400))**2*(((x/(8.314*400))**4+18*(x/(8.314*400))**3+86*(x/(8.314*400))**2+
        96*(x/(8.314*400)))/((x/(8.314*400))**4+20*(x/(8.314*400))**3+120*(x/(8.314*400))**2+240*(x/(8.314*400))+120)))*\
             1/(3.81*(2*np.pi)**0.5)*np.exp(-(x-116*10**3)**2/(2*3.81**2))`
>`y1=quad(y,0,1000)`
>`print (y1)`
#This is rerult:
>`(0.0, 0.0)`

**Comment by rkern** [comment]
Most of the mass of that one is around `116*10**3`, which is well outside of those bounds.
