### ISSUE TITLE
ENH: scipy.optimize.fminbound: example uses "minimum" instead of "minimizer"

### ISSUE THREAD

**Issue by jupsal** [scipy/scipy#17445]
### Is your feature request related to a problem? Please describe.

The example on the [scipy.optimize.fminbound](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fminbound.html) help page uses incorrect language, conflating "minimum" with "minimizer." In particular, the sentence "[fminbound](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fminbound.html#scipy.optimize.fminbound) finds the minimum of the function in the given range." is incorrect. `fminbound` finds the *minimizer*, as previously mentioned in the docs.

The example is also highly confusing since in the example the minimum and minimizer are the same.

### Describe the solution you'd like.

Please change the language to "minimizer" instead of "minimum." Also, please consider a more illustrative and less confusing example, such as:

```
>>> def f(x):
...     return (x-1)**2
```
```
>>> from scipy import optimize
```
```
>>> minimizer = optimize.fminbound(f, -1, 2)
>>> minimizer
1.0
>>> minimum = f(minimizer)
>>> minimum
0.0
>>>minimizer = optimize.fminbound(f, 1, 2)
>>> minimizer
1.0000059608609866
```

I believe this example will help demonstrate the difference between "minimizer" and "minimum," which is a common misunderstanding (clearly so, since the developers seem to misunderstand it).

**Comment by mdhaber** [comment]
Thank you for bringing this to our attention. Please submit a PR to be sure it is done correctly.

**Comment by mdhaber** [comment]
I went ahead and created a PR since I decided to work on that file for another reason. Please let me know if gh-17447 addresses the issue.

**Comment by jupsal** [comment]
This addresses my issue, thank you.

**Comment by mdhaber** [comment]
Thanks, but the PR hasn't merged yet, so I'll reopen it. It will be closed automatically when the PR gets merged.
