### ISSUE TITLE
BUG: beta.ppf causes segfault

### ISSUE THREAD

**Issue by bfis** [scipy/scipy#17444]
### Describe your issue.

Calling `beta.ppf` with extreme values causes an segfault.

This issues may be related to the handling of `boost::wrapexcept<std::overflow_error>` exceptions:
For the following SciPy/NumPy/Python version: `1.7.0 1.19.5 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)` on gets the following error instead:
```
terminate called after throwing an instance of 'boost::wrapexcept<std::overflow_error>'
  what():  Error in function boost::math::beta<double>(double,double): numeric overflow
Aborted (core dumped)
```

This may be related to #14704 or even #14606.

### Reproducing Code Example

```python
from scipy.stats import beta
beta.ppf(.9, 1e-320, 1234)
```

### Error message

```shell
Segmentation fault (core dumped)
```

### SciPy/NumPy/Python version information

1.9.3 1.23.4 sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
I can reproduce this in main. ping @mckib2

**Comment by WarrenWeckesser** [comment]
There is an exception being thrown in the Boost code that is not being caught by the wrapper.

The value 1e-320 is [subnormal](https://en.wikipedia.org/wiki/Subnormal_number).  A "feature" of this value is that 1/1e-320 overflows to `inf`:
```
In [11]: 1/1e-320
Out[11]: inf
```
With the input values `a=1e-320`, `b=1234`, the Boost code eventually swaps the values to `a=1234` and `b=1e-320` and ends up evaluating the beta function with these values, which ultimately leads to [this line](https://github.com/scipy/boost-headers-only/blob/3af99e6d566043072e95bc882d32c9c26f37e0ba/boost/math/special_functions/beta.hpp#L50) in `boost/math/special_functions/beta.hpp` being executed:

```
          return 1 / b;
```
That results in an overflow error.  The exception propagates up and is never caught by any wrapper code, so Python crashes.

That's as far as I got in my investigation, so at the moment I don't know what the appropriate fix is.  One thing that is clear from our growing experience with Boost is that we have to assume that any call to C++ can result in a C++ exception being thrown, even if we have configured Boost to not raise exceptions--Boost is great, but it is not bug-free.

**Comment by WarrenWeckesser** [comment]
The segmentation fault occurs in https://github.com/scipy/scipy/blob/b4a970bf4eba1065ea31f8d0988cd4ec523a07d4/scipy/stats/_boost/include/func_defs.hpp#L22-L36

It turns out that `message` is actually NULL, so it must not be referenced. The fact that `message` might be NULL is definitely not clear in the Boost docs!
