### ISSUE TITLE
ENH: Rotation equality checks

### ISSUE THREAD

**Issue by scottshambaugh** [scipy/scipy#17458]
### Is your feature request related to a problem? Please describe.

It would be useful to have a function to determine if two scipy.spatial.transform.Rotation objects are equal. 

### Describe the solution you'd like.

Since Rotations have floating point representations an approximate equality check is needed, and since the space of rotations is cyclic with a discontinuity in representation at +-pi, we can't simply check equality between the values of the quaternions of the two rotations. I believe the right way to do this is to calculate the magnitude of the angle between the two rotations, and check if it is near zero. 

A simple way to implement this:
```python
# a standalone function, or a method of the Rotation class (replace R1 with self)?
# atol measured in radians, 1e-12 as a default is notional
def rotation_approx_equal(R1, R2, atol=1e-12):
    Rdiff = R1* R2.inv()
    return Rdiff.magnitude() < atol
```

I think it would also be useful to take this chance to add a distance function as well:
```python
def dist(self, R2):
    Rdiff = self * R2.inv()
    return Rdiff.magnitude()

def approx_equal(self, R2, atol=1e-12):
    return self.dist(R2) < atol
```

[Huynh, "Metrics for 3D Rotations: Comparison and Analysis"](http://www.cs.cmu.edu/~cga/dynopt-19/readings/Rmetric.pdf) describes a potentially more efficient distance function (note that @ is the dot product of the vector representation, not Hamilton multiplication): `dist = 2 * arccos(abs(q1 @ q2))`

**Comment by cgobat** [comment]
Given that most of `Rotation`'s internals deal with quaternion representations, another possible implementation of this equality check could be
```python
    def approx_equal(self, other: Rotation, atol=1e-12) -> bool:
        return np.allclose(self.as_quat(), other.as_quat(), atol=atol) # or maybe just self._quat and other._quat ?

    def __eq__(self, other: Rotation) -> bool: # enables `if R1 == R2:` syntax
        return np.array_equal(self.as_quat(), other.as_quat())
```

**Comment by scottshambaugh** [comment]
Hey @cgobat, unfortunately that approach runs into problems with the double cover of rotation space by quaternions. In other words, `q` and `-q` describe the same rotation. There's a lot of good discussion here: https://github.com/scipy/scipy/pull/17334

I do think the `__eq__` operator might have its uses, though I'll note that it's inherently fragile for floating points and does work right now for identifying specific class instances:
```
>>> from scipy.spatial.transform import Rotation as R
>>> R0 = R.identity()
>>> R0 == R0
True
>>> R1 = R.identity()
>>> R0 == R1
False
```

**Comment by cgobat** [comment]
Right, good point about $-q$ representing the same rotation as $q$. I guess there would have to be an extra step of making sure both of the quaternions being compared have positive scalar components, for instance, and flipping them if not.

I don't think the fragility with floats is a problem, per se. That "exact equality" behavior mirrors the behavior of comparing of two NumPy arrays using `==`, (which is probably the wrong choice of operator for *most* use cases&mdash;but that's why things like `np.isclose`, `np.allclose`, and the proposed `Rotation.approx_equal` method are needed), but I would think we want to have that parallel in place. As you've constructed them, I think the intuitive value for `R0 == R1` should be `True`, but of course `R0 is R1` is and should be `False`. This holds for the NumPy analogy:
```python
>>> import numpy as np
>>> A = np.eye(3)
>>> np.array_equal(A, A)
True
>>> np.array_equal(A, A.copy())
True
>>> B = np.eye(3)
>>> np.array_equal(A, B)
True
>>> A is A, A is A.copy(), A is B
(True, False, False)
```

**Comment by scottshambaugh** [comment]
Even ensuring the positive scalar components wouldn't work out, because there then becomes a discontinuity in the other components. Consider the small angular jump jump from eg `q1 = (0, 0, 0.9999, 0.0001)` to `q2 = (0, 0, -0.9999, 0.0001)`. It's why the approach in https://github.com/scipy/scipy/pull/17460 calculates the angle by taking `(R2 * R1.inv()).magnitude()`.

I do like what you're saying about that equality check.
