### ISSUE TITLE
ENH: custom stopping criteria with auxiliary function

### ISSUE THREAD

**Issue by AdrianPerezSalinas** [scipy/scipy#17456]
### Is your feature request related to a problem? Please describe.

The solution I am looking forward is not about an existing problem, but about expanding the capabilities of the optimizers in scipy. Consider the following problem. Let `f(x)` and `g(x)` be two functions that depend on the same parameters. Then we want to optimize `f(x)` without having `g(x)` out of control. We monitor the value of `g(x)` to have a criteria to stop the minimization. 

### Describe the solution you'd like.

I look for something easy like for example
```
def f(x): 
    f = sum(x) # or some other function
    return f

def g(x): 
    f = sum(x**2) # or some other function
    return f


def callback(x): 
    f_val = f(x)
    g_val = g(x)

    print(x, f_val, g_val)
    if g_val > 1: # or some other custom condition
        # stop optimization

x0 = np.random.rand(10)

res = optimize(f, x0, callback=callback)

print(res)

```

### Describe alternatives you've considered.

I have checked several threads in `stackoverflow`, as well as previous issues related to early stopping using callbacks (https://github.com/scipy/scipy/issues/12103) but they are either not valid or I cannot manage to make them work. 

### Additional context (e.g. screenshots, GIFs)

Thank you in advance!

**Comment by mdhaber** [comment]
The capability is not implemented for most optimizers. We've discussed this recently in other issues, which I'll link here later. I'll go ahead and work on it this week.
