### ISSUE TITLE
BUG: scipy.interpolate.interp1d gives "nan" with "kind='next', fill_value='extrapolate'" in v1.9.3

### ISSUE THREAD

**Issue by dylanwu711** [scipy/scipy#17461]
### Describe your issue.

I find the output of scipy.interpolate.interp1d gives nan output when "kind='next', fill_value='extrapolate'" in v1.9.3.

You can reproduce the error the result with the following code.

The output is 'nan'. And, there is no 'extrapolate' at all.

### Reproducing Code Example

```python
import numpy as np
from scipy.interpolate import interp1d

x = np.array([0, 1, 2, 3, 4])

y = np.array([2, 3, 4, 5, 6])

func = interp1d(x, y, kind='next', fill_value='extrapolate')

new_y = func(np.arange(10))

print(new_y)
```

### Error message

```shell
array([ 2.,  3.,  4.,  5.,  6., nan, nan, nan, nan, nan])
```

### SciPy/NumPy/Python version information

1.9.3

**Comment by Patol75** [comment]
I am pretty sure this has already been raised and addressed. Can you please have a look at gh-16997 and confirm?

**Comment by dylanwu711** [comment]
Got It! I will close the issue. But, I would **strongly** suggest mention the differences in the API Doc. A lot of people may think that is an unwanted behavior.

**Comment by ev-br** [comment]
@dylanwu711 could I tempt you to send a pull request with a doc clarification? You are probably the best person to do that, now that the issue is fresh in your mind and you can phrase it the way it would have been most helpful for your past self (hence, future readers).
