### ISSUE TITLE
BUG: cho_solve and solve_triangular give different results for the same system

### ISSUE THREAD

**Issue by mvsoom** [scipy/scipy#17476]
### Describe your issue.

`cho_solve` and `solve_triangular` return different results for the same system `L x = b`.

### Reproducing Code Example

```python
from numpy.random import randn
from numpy.linalg import cholesky
from scipy.linalg import solve_triangular, cho_solve

# Get a "random" lower triangular matrix L
R = randn(3, 3)
L = cholesky(R @ R.T)

# Solve the system L x = b
b = randn(3)
solve_triangular(L, b, lower=True), cho_solve((L, True), b)
# These give different results, e.g.
# (array([-0.27529196,  0.63432194, -1.58746099]),
#  array([ 4.21641427,  6.05963718, -1.88058974]))
# The first one is correct
```

### Error message

```shell
None
```

### SciPy/NumPy/Python version information

`1.8.0 1.22.3 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)`

**Comment by mvsoom** [comment]
Sorry, my bad, I got heavily confused :) No issue at all here.

**Comment by WarrenWeckesser** [comment]
I was writing the following when your last comment appeared...

`solve_triangular` and `cho_solve` solve different problems.  `solve_triangular` does just what it says, solve a triangular system.  `cho_solve` is designed to work with [`cho_factor`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.cho_factor.html) to efficiently solve the problem `A x = b` for a Hermitian positive definite matrix A.
