### ISSUE TITLE
Pythran build warnings with numpy main

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#17474]
When building SciPy with the numpy main branch (e.g. `'1.25.0.dev0+11.ga872fd73e'`), *many* repetitions of this warning are generated:

```
/home/warren/py3.10.8/lib/python3.10/site-packages/pythran/tables.py:4555: FutureWarning: In the future `np.bytes` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  obj = getattr(themodule, elem)
```

I have Pythran 0.12.0 installed.

I haven't looked into the cause, so I don't know if this has already been addressed in the development version of Pythran.

If this is a purely Pythran issue, we can close this and open up a Pythran issue for it.

Ping @serge-sans-paille.

**Comment by serge-sans-paille** [comment]
> If this is a purely Pythran issue, we can close this and open up a Pythran issue for it.

That's the case, please open a Pythran issue.

**Comment by WarrenWeckesser** [comment]
Thanks for checking @serge-sans-paille.  The new issue is https://github.com/serge-sans-paille/pythran/issues/2041.
