### ISSUE TITLE
MAINT: HiGHS build flag cleanup

### ISSUE THREAD

**Issue by mckib2** [scipy/scipy#17494]
### Describe your issue.

Legacy [`setup.py`](https://github.com/scipy/scipy/blob/main/scipy/optimize/_highs/setup.py) and [`meson.build`](https://github.com/scipy/scipy/blob/main/scipy/optimize/_highs/meson.build) files specify C/C++ preprocessor directives that are unneeded/unused.  These were originally included to match flags added by the upstream cmake build system, but lead to increased maintenance burden trying to understand which flags are actually important and need to be updated.

The unused/unneeded build flags should be removed.

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

main branch/`n/a`/`n/a`

**Comment by mckib2** [comment]
xref gh-17430

**Comment by mahimairaja** [comment]
Is this issue solved?

**Comment by HaoZeke** [comment]
Thanks for the mention! It is mostly irrelevant now IMO the plan is to simply use `highspy` directly and in any case the flags need to be (and are now) set programmatically based on the system features (see e.g. this [mesonbuild file](https://github.com/HaoZeke/HiGHS/blob/cb91728e011eb0b81f1f53f123770e382ce051e3/src/HConfig.h.meson.in))

**Comment by rgommers** [comment]
This was addressed (or is no longer relevant) after gh-21565. So closing - thanks all!
