### ISSUE TITLE
optimize.differential_evolution not releasing memory when finished

### ISSUE THREAD

**Issue by jzod** [scipy/scipy#17492]
I have a loop where I call differential evolution successively with different arguments (see attached code). The amount of memory used continues to rise, even after the call to differential evolution is completed and results are obtained. I don't see anything in my code that adds to memory in the loop. I save results out to a log file but don't keep them in memory.

Can you explain why memory used never decreases until the program is exited? It should be going back to the starting memory used when differential evolution is done each time through the loop.

[code.txt](https://github.com/scipy/scipy/files/10096912/code.txt)

**Comment by andyfaff** [comment]
That minimiser is pure Python, so any memory effects will be due to how the interpreter handles memory. There is nothing about the optimise r itself that will cause memory allocation to continuously increase.

**Comment by jzod** [comment]
Makes sense. Now I have to figure out what the hell Python is doing! Any suggestions?

Joe

**Comment by andyfaff** [comment]
How much memory are we talking about? Is it an issue because it's a sizeable fraction of free memory? You might get some traction with `gc`. How is your objective function written? Is this creating lots of dangling objects that can't be freed? Is any part of it written in C?

**Comment by jzod** [comment]
Each pass thru the loop uses about 3GB of more memory. That really adds up and the program dies when I use smaller step sizes. 

I’m going to try gc, thanks!

My code is not creating dangling objects but I use TensorFlow and OpenCV. My code is all Python but I assume these packages have C in them. 

Joe
