### ISSUE TITLE
BUG: latest version of flake8 breaks `tools/lint_diff.py`

### ISSUE THREAD

**Issue by j-bowhay** [scipy/scipy#17503]
https://flake8.pycqa.org/en/latest/release-notes/6.0.0.html#backwards-incompatible-changes

Flake8 version 6.0.0 removed the `--diff` flag which breaks `tools/lint_diff.py`

**Comment by rgommers** [comment]
Oh yes, they decided to break the world. Can we just pin it to `<6.0` in `environment.yml`? This is not a defect, we _need_ to run on the diff only. Running on the whole code base is a nonstarter.

**Comment by j-bowhay** [comment]
closed via https://github.com/scipy/scipy/pull/17496
