### ISSUE TITLE
ENH: Enable user parameters in nonlin linesearch

### ISSUE THREAD

**Issue by gabrielfougeron** [scipy/scipy#17510]
### Is your feature request related to a problem? Please describe.

I am using nonlin_solve to find roots of a function. This gradient based procedure first determines a search direction, and then proceeds with a line search along this direction, using the function _nonlin_line_search.

I would like more control over what is happening during this line search. The only level of control one has (through nonlin_solve) is to choose between three parameters ("wolfe", "armijo" and None). However, it is clear from the code of _nonlin_line_search that many search parameters are present and are always set to their default values.

As far as I can tell, _nonlin_line_search is used only once in the whole scipy codebase, namely in nonlin_solve.

I would like more flexibility in choosing the linesearch method

### Describe the solution you'd like.

Several possibilities come to mind, the simplest of which would be the possibility for the user to provide a callable that would replace the following lines in nonlin_solve:

```        
        # Line search, or Newton step
        if line_search:
            s, x, Fx, Fx_norm_new = _nonlin_line_search(func, x, Fx, dx,
                                                        line_search)
```

into somethin along the liens of 

```     
if user_callable_provided:
            s, x, Fx, Fx_norm_new = the_user_callable(func, x, Fx, dx)
 else:
        # Line search, or Newton step
        if line_search:
            s, x, Fx, Fx_norm_new = _nonlin_line_search(func, x, Fx, dx,
                                                        line_search)
```

If this is the case, it would be possible to override default parameters in _nonline_line_search with a simple partial instanciation of the function.

### Describe alternatives you've considered.

A more complex API change could be envisioned, but I assume this would require more in depth work.

**Comment by mdhaber** [comment]
`_nonlin_line_search` is a private function. Private functions are denoted by a preceding `_` and they typically lack documentation (some have docstrings, but they are not rendered online) and they cannot be imported directly from subpackages (e.g. `scipy.optimize`). The maintenance team does not support external use of private functions, so we would not change the API for this request unless we were to make the function public.

As for making `_nonlin_line_search` public, I think would vote -1. It looks like you're making a solver for the N-body problem?For that, I'd suggest copy-pasting this function into your own code and making whatever modifications you'd like.

What do you think @andyfaff @Kai-Striega?

**Comment by gabrielfougeron** [comment]
Thank you very much for your quick response. I'll do exactly as you suggest 😊. And yes, this is for a periodic n-body spectral solver.

**Comment by mdhaber** [comment]
Great. I'll leave gh-17511 open, because that sounds like it could be a bug if our solvers are using `armijo`.

**Comment by Kai-Striega** [comment]
If there is more interest we could consider it, but for not I'm -1 on making `_nonlin_line_search` public. Although I haven't used this part of SciPy very much so it's not the hill I'm going to die on.
