### ISSUE TITLE
BUG: Error in documentation for scipy.optimize.minimize

### ISSUE THREAD

**Issue by isaacgerg** [scipy/scipy#17516]
### Describe your issue.

Documentation here, 
https://docs.scipy.org/doc/scipy/reference/optimize.minimize-trustexact.html#optimize-minimize-trustexact ,
indicates the intial trust region is specified with a dictionary keyword "initial_tr_radius."

However, the code expects this key to be "initial_trust_radius."

See link 117 in https://github.com/scipy/scipy/blob/main/scipy/optimize/_trustregion.py for verification of the function interface.

### Reproducing Code Example

```python
N/A documentation error
```

### Error message

```shell
N/A documentation error
```

### SciPy/NumPy/Python version information

1.9.3

**Comment by j-bowhay** [comment]
Thanks @isaacgerg for reporting, would you like to open a pr to fix?

**Comment by isaacgerg** [comment]
@j-bowhay   I am on a system not connected to the internet.

**Comment by faithhunja** [comment]
Hi. Can I take on this issue? 
I presume all "initial_trust_radius" in the code should be replaced with "initial_tr_radius" as indicated in the documentation?
Also, I noticed the same problem exists with the maximum value of the trust-region radius "max_tr_radius", which is referenced in the code as "max_trust_radius".

**Comment by isaacgerg** [comment]
@faithhunja There is some code to check for unknown parameters which should have trapped this but I think there is a bug in there also.  You will see it in the code I reference in the initial post.

**Comment by j-bowhay** [comment]
@faithhunja yes go for it. It is the documentation that should be updated not the code. As this will be a documentation only change please try to skip the relevant ci https://scipy.github.io/devdocs/dev/contributor/continuous_integration.html#skipping
