### ISSUE TITLE
BUG: `[source]` button in the docs sending to the wrong place

### ISSUE THREAD

**Issue by jpcbertoldo** [scipy/scipy#17523]
### Describe your issue.

The button `[source]` in the doc page of `scipy.stats.wilcoxon`  is pointing to its decorator `scipy.stats._axis_nan_policy`.

Extracted bit of code:

```python
@_axis_nan_policy_factory(
    wilcoxon_result_object, paired=True,
    n_samples=lambda kwds: 2 if kwds.get('y', None) is not None else 1,
    result_to_tuple=wilcoxon_result_unpacker, n_outputs=wilcoxon_outputs,
)
def wilcoxon(x, y=None, zero_method="wilcox", correction=False,
             alternative="two-sided", method='auto'):
```

Links: 
- `scipy.stats.wilcoxon`: [docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wilcoxon.html](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.wilcoxon.html): 
- `scipy.stats._axis_nan_policy` : [github.com/scipy/scipy/blob/v1.9.3/scipy/stats/_axis_nan_policy.py](https://github.com/scipy/scipy/blob/v1.9.3/scipy/stats/_axis_nan_policy.py#L3131-L3433)

![image](https://user-images.githubusercontent.com/24547377/205274762-dcb2cadf-c4e0-481b-beb2-e0f7ab5a9d18.png)

### Reproducing Code Example

```python
Go to the website and click on the button : )
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version information

1.9.3 (stable) [doc]

**Comment by mdhaber** [comment]
@tirthasheshpatel you've fixed some Sphinx "Source" linking issues before. Do you know how to tell Sphinx to link to the location of the wrapped function rather than the wrapper?
The low-tech solution is to separate the function with the documentation from a private function with the implementation. The latter would be wrapped and the former would call the wrapped private function.

**Comment by tirthasheshpatel** [comment]
> The low-tech solution is to separate the function with the documentation from a private function with the implementation. The latter would be wrapped and the former would call the wrapped private function.

We can do this and would simplify a lot of things for us but it would also not be straightforward for the user so I submitted an alternative solution in #17526. Let me know if it looks good.

**Comment by mdhaber** [comment]
I prefer the gh-17526 approach, of course! Thank you!
