### ISSUE TITLE
DOC: side bar renders over the top of some of the text in the optimize tutorial

### ISSUE THREAD

**Issue by j-bowhay** [scipy/scipy#17532]
https://docs.scipy.org/doc/scipy/tutorial/optimize.html#full-hessian-example

![image](https://user-images.githubusercontent.com/60778417/205464431-b0b7a197-94db-4ad7-bef7-37740568d569.png)

**Comment by tupui** [comment]
Yeah this is not ideal... I think it's more of a theme thing though.

**Comment by melissawm** [comment]
I did a quick search, since the rest of the text flows as the window is resized, and we can't do that with equations, maybe what we need is something like [a scrollbar for wide equations](https://github.com/executablebooks/sphinx-book-theme/blob/master/src/sphinx_book_theme/assets/styles/content/_math.scss)?

**Comment by melissawm** [comment]
As an experiment/quick fix I also tried just making the font smaller and got a reasonable solution for a regular-sized screen:
![Screenshot_20221206_145841](https://user-images.githubusercontent.com/3949932/205986870-7c0722b0-b919-43d7-85b4-fbaa846c52c7.png)

**Comment by tupui** [comment]
Maybe both? ATM the font seems a bit large for math so we could adjust it. But scrolling math is the definitive solution I thing (seems to hard otherwise to make something like equation wrapping work on all screen config)

**Comment by ilayn** [comment]
You can also play some TeX+math tricks by squeezing things individually that gives by injecting negative math space. But I don't know if markdown supports these things.

![image](https://user-images.githubusercontent.com/1303842/206059003-db63afa7-2793-4d4b-859b-e798f288ddee.png)


```latex

\mathbf{H}=
\begin{bmatrix}1200x_{0}^{2}+2\mkern-2em\\
    &1200x_{1}^{2}+202\mkern-2em\\
    &&1200x_{1}^{2}+202\mkern-2em\\
    &&&1200x_{3}^{2}+202\mkern-1em\\
    &&&&200
\end{bmatrix}
-400\begin{bmatrix}
x_1&x_0 \\x_0&x_2&x_1 \\&x_1&x_3&x_2\\&&x_2&x_4&x_3\\&&&x_3&0
\end{bmatrix}

```
