### ISSUE TITLE
CI: The Ubuntu 18.04 Actions runner image is deprecated

### ISSUE THREAD

**Issue by scottshambaugh** [scipy/scipy#17548]
I receive the following warning on [azure runs](https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=21918&view=results):
```
##[warning]The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
```

From https://github.com/actions/runner-images/issues/6002:
> We have started the deprecation process for Ubuntu 18.04. While the image is being deprecated, You may experience longer queue times during peak usage hours. Deprecation will begin on 2022/08/08 and the image will be fully unsupported by 2023/04/01
> 
> To raise awareness of the upcoming removal, we will temporarily fail jobs using Ubuntu 18.04. Builds that are scheduled to run during the brownout periods will fail. The brownouts are scheduled for the following dates and times: [...]

**Comment by rgommers** [comment]
Thanks @scottshambaugh. I don't think there's a specific reason we need that image, it can be upgraded to 20.04 or 22.04

**Comment by SaumyaBhushan** [comment]
Hi @rgommers , @tupui Can I work on this issue ?

**Comment by tupui** [comment]
@SaumyaBhushan sure, unless @scottshambaugh wants to do it himself

**Comment by scottshambaugh** [comment]
Go for it!

**Comment by SaumyaBhushan** [comment]
Thanks @scottshambaugh

**Comment by SaumyaBhushan** [comment]
Hi team , I was exploring the actions yml files and found that it has already been updated. Let me know if somewhere else we need to update it else we can close this issue . +cc @tupui @rgommers @scottshambaugh

**Comment by tupui** [comment]
@SaumyaBhushan it is not update everywhere, see:

https://github.com/scipy/scipy/blob/502df0ece7eb9525de8a7f243044b3fe18ad5cca/azure-pipelines.yml#L110
