### ISSUE TITLE
Numba accelerated scipy.optimize.minimize

### ISSUE THREAD

**Issue by pushkar5586** [scipy/scipy#17550]
Hi,

Is there a way to speed up scipy.optimize.minimize by using numba's njit decorator if the function to be minimized has already been njit-ed?

Thanks in advance.

**Comment by tupui** [comment]
Hi @pushkar5586, thank you for reporting. I am sorry but we don't have the bandwidth to answer user related question. This issue tracker is solely for reporting issues. Please use other forum such as StackOverflow or our Slack channels.

Note that we do not provide any support for numba (there are a few discussion already you can look for on GitHub or our mailing list).

**Comment by pushkar5586** [comment]
`Jax`is the solution I was looking for!
