### ISSUE TITLE
ENH: optimize.root_scalar: default to `newton` when only `x0` is provided

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#17570]
### Is your feature request related to a problem? Please describe.

When `method` is not specified, `optimize.root_scalar` attempts to select the best method given the information available. I was always surprised that the following:

```python3
from scipy import optimize

def f(x):
    return x**2 - 1

res = optimize.root_scalar(f, x0=2)
```

fails with the error:

```
Traceback (most recent call last):

  File "C:\Users\matth\AppData\Local\Temp\ipykernel_35340\1932188727.py", line 6, in <module>
    res = optimize.root_scalar(f, x0=2)

  File "C:\Users\matth\scipy\scipy\optimize\_root_scalar.py", line 280, in root_scalar
    raise ValueError('x1 must not be None for %s' % method)

ValueError: x1 must not be None for secant
```

I expected Newton's method to be used because `x0` is enough information to use Newton's method.

When I try to force Newton to be used,

```python3
res = optimize.root_scalar(f, x0=2, method='newton')
```

we see why `newton` wasn't selected automatically:

```
Traceback (most recent call last):

  File "C:\Users\matth\AppData\Local\Temp\ipykernel_35340\1942526262.py", line 1, in <module>
    res = optimize.root_scalar(f, x0=2, method='newton')

  File "C:\Users\matth\scipy\scipy\optimize\_root_scalar.py", line 289, in root_scalar
    raise ValueError('fprime must be specified for %s' % method)

ValueError: fprime must be specified for newton
```

But `scipy.optimize.root` does not require an analytical derivative, so I don't think `root_scalar` should. 

### Describe the solution you'd like.

Use numerical differentiation for gradient-based `root_scalar` methods when `fprime` is not provided, and default to a gradient-based method when only `x0` is provided.

### Additional context (e.g. screenshots, GIFs)

I'll do it. I just thought I'd create an issue to see if there were others that supported the idea.

**Comment by tupui** [comment]
+1 from me. I don't see why we would be required to provide fprime.
