### ISSUE TITLE
BUG: Deprecation warning says to use non-existent symbols

### ISSUE THREAD

**Issue by moorepants** [scipy/scipy#17572]
### Describe your issue.

There is a deprecation warning for importing `MemoizeJac` that recommends importing it from `scipy.optimize` as a new approach, but I can't import it from `scipy.optimize`.

### Reproducing Code Example

```python
Python 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:46:39) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.33.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import scipy

In [2]: scipy.__version__
Out[2]: '1.9.3'

In [3]: from scipy.optimize.optimize import MemoizeJac
<ipython-input-3-ad2abe888e13>:1: DeprecationWarning: Please use `MemoizeJac` from the `scipy.optimize` namespace, the `scipy.optimize.optimize` namespace is deprecated.
  from scipy.optimize.optimize import MemoizeJac

In [4]: from scipy.optimize import MemoizeJac
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-2958dec3cdad> in <cell line: 1>()
----> 1 from scipy.optimize import MemoizeJac

ImportError: cannot import name 'MemoizeJac' from 'scipy.optimize' (/home/moorepants/miniconda/lib/python3.8/site-packages/scipy/optimize/__init__.py)

In [5]: import scipy.optimize

In [6]: scipy.optimize.MemoizeJac
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-d0f0a395bf46> in <cell line: 1>()
----> 1 scipy.optimize.MemoizeJac

AttributeError: module 'scipy.optimize' has no attribute 'MemoizeJac'
```
```


### Error message

```shell
See above.
```

### SciPy/NumPy/Python version information

1.9.3 1.23.5 sys.version_info(major=3, minor=8, micro=15, releaselevel='final', serial=0)

**Comment by ev-br** [comment]
A relative of https://github.com/scipy/scipy/pull/16532#issuecomment-1173112142 ?

**Comment by moorepants** [comment]
Yes, looks the same. So this will be fixed in 1.10?

**Comment by moorepants** [comment]
I see that the PR you referenced didn't address this class. So I guess the same fix could be applied.

**Comment by ev-br** [comment]
Would you be willing to send a PR with the fix? It should go to the main branch, once it's merged we can ask the RM about backporting to 1.10.
I guess since the fix is going to be similar to those already made, it should be an uncontroversial merge.

**Comment by moorepants** [comment]
I'll have a look.

**Comment by mdhaber** [comment]
Are we sure `MemoizeJac` is supposed to be public? It doesn't have a complete docstring.

**Comment by mdhaber** [comment]
Oh I see @ev-br that in https://github.com/scipy/scipy/pull/16532#issuecomment-1176752145 you suggested being liberal about adding to the namespace. I'll let you deal with any "trouble" that ensues : )

**Comment by moorepants** [comment]
It was public in the past. I'm reporting this because I'm getting deprecation warnings downstream that we can no longer import in the prior supported way and the deprecation warning gives an alternative that does not work.

**Comment by ev-br** [comment]
This is not about being liberal with the namespace. It's just that these things were available, and now they are not. Worse, they emit deprecation warnings that are actually misleading and that users cannot act on: these warnings recommend using non-existing objects from the main namespace. 

So IMO it's a clear bug in application of our deprecation/removal process. Hence the suggestion to fix the bug. And when it's fixed, we can start a regular deprecation process :-).

**Comment by mdhaber** [comment]
I thought I'd update this issue with what we discussed in the PR (https://github.com/scipy/scipy/pull/17575#issuecomment-1346011901): we need to change the warning to an `ImportError`, but `MemoizeJac` will not be made public.
