### ISSUE TITLE
ENH: override fit method for von mises

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#17576]
### Is your feature request related to a problem? Please describe.

The von Mises distribution is a circular distribution, so the current distribution fitting infrastructure is not ideal for it resulting in very slow and wrong fits (wrong concentration parameter).

Fortunately, fitting it is mathematically not very difficult: $\mu$ is given by the circular mean and $\kappa$ is the solution to
$$\frac{I_1(\kappa)}{I_0(\kappa)}-r=0$$
with the mean resultant length $r$ (cf. [Wikipedia](https://en.wikipedia.org/wiki/Von_Mises%E2%80%93Fisher_distribution#Concentration_parameter)).

### Describe the solution you'd like.

The fit method for vonmises should be overwritten. The following code snippet finds the parameters in principle, but I am very much confused with the loc/shape/scale parametrization used in `scipy.stats`.

```
from scipy.optimize import root_scalar
from scipy.stats import circmean, circvar
from scipy.special import i0e, i1e

mu = circmean(data)
r = 1 - circvar(data)

def solve_for_kappa(kappa):
    return i1e(kappa)/i0e(kappa) - r

root_res = root_scalar(solve_for_kappa, method="brentq",
                               bracket=(1e-8, 1e9))
if root_res.converged:
    kappa = root_res.root
```

Questions from my side:
* If neither loc/shape/scale are given, should the fit method return `mu ` and `kappa` ?
* If `loc` is given, should only `kappa `be returned?
* If `shape` is given, should only `mu` be returned?

### Additional context (e.g. screenshots, GIFs)

There seems to be a lot of literature about the accurate computation of the ratio of  modified Bessel functions $\frac{I_v(x)}{I_{v-1}(x)}$ needed for the von Mises-Fisher distribution: tensorflow folks go to great length in their implementation (see [here](https://github.com/tensorflow/probability/blob/0759c57eb0306a5bb0fcc3d105bbcab9943092a5/tensorflow_probability/python/math/bessel.py#L349)). They use the following reference: http://www.jstor.com/stable/2006491

In all my tests so far in my ongoing work on the n-dimensional von Mises-Fisher distribution, I did not encounter any problems though, using exponentially scaled Bessel functions seemed to suffice also for large values.

**Comment by tupui** [comment]
Sounds like a sensible thing to do. Do you propose to make a PR?
