### ISSUE TITLE
ENH: Add units to scipy.constants description

### ISSUE THREAD

**Issue by BenediktBurger** [scipy/scipy#17571]
### Is your feature request related to a problem? Please describe.

I could not find out, in which units the constants of `scipy.constants` are.
I guess they are in SI notation, but I'd like to be sure, before I use these numbers.

### Describe the solution you'd like.

Could you add either a general note, that all the constants are given in base units of the SI system, or add to every constant the relavant units (e.g. speed of light in vacuum in meters/second).

**Comment by tupui** [comment]
Hi @bmoneke, thank you for reporting. Units are in the doc here https://docs.scipy.org/doc/scipy/reference/constants.html

Is there something missing? (scroll down).

**Comment by bmoneke** [comment]
Below are the constants with units, but the "base constants" are not labelled.

I can do it.

I'll add a general note at the beginning.

What do you think about writing to every constant (in that list) the unit as well? Just as a reminder for the readers.

**Comment by tupui** [comment]
Spelling out all constants, as done for the rest, is a good idea 👍 

If you are looking into making changes to this doc. I recall there is a stalled PR that wanted to change the organisation etc. If you are interested, it would be great to pick up 😃 

Thanks!

**Comment by bmoneke** [comment]
I saw that other point, when I searched for open/closed issues before opening my own one.

Thanks for your fast responses.

**Comment by jakobjakobson13** [comment]
@bmoneke : Could you answer me two questions for clarification?

> Below are the constants with units, but the "base constants" are not labelled.
> 
The base constants are included in the CODATA constants provided by scipy but the base constants are not emphasized explicitly. So you are right, they can be easily overlooked.
Do you want to list the base constants in an dedicated section or do you want to just emphasize them? In the first case they would be listed twice (which I would neither consider ideal) whereas the second case will not be easy to implement.

**Comment by bmoneke** [comment]
@jakobjakobson13 , thanks for the question.

I just want to know the units next to the name. They don't have to be emphasized.

Here my problem: I imported the package and found `c = 3e8` (approximately). Then I try to figure out, what the unit of that `c` is and I don't find anything in the documentation.
The documentation regarding CODATA did not help either, as the same constant is included several times (e.g. Boltzmann constant), albeit in different units. Which of these is now the directly imported value?

I cannot use a constant without knowing, that the units fit.

Maybe a (bold) remark, that these base constants are the numbers in the SI system might be enough and a small change. However, being explicit about the units is better, I think.

I hope I succeeded in showing my problem.

**Comment by jakobjakobson13** [comment]
Congratulations, you picked a nice corner case here :)
By loading the `scipy.constants` module some constants are currently imported automatically.
https://github.com/scipy/scipy/blob/5da8a3adc664ca57235b9f60f57d705561117893/scipy/constants/__init__.py#L325
Among these constants is `c` or the `speed of light in vacuum`.
https://github.com/scipy/scipy/blob/5da8a3adc664ca57235b9f60f57d705561117893/scipy/constants/_constants.py#L109
The problem now is however that `_cd` only imports the value but not the unit.
https://github.com/scipy/scipy/blob/5da8a3adc664ca57235b9f60f57d705561117893/scipy/constants/_constants.py#L15
https://github.com/scipy/scipy/blob/5da8a3adc664ca57235b9f60f57d705561117893/scipy/constants/_codata.py#L1575

If you had imported the constant via ` scipy.constants.physical_constants` you would have had the constant with its value AND its unit. I hope that helps to your understanding.
