### ISSUE TITLE
`curve_fit`'s `f_vec` is wrong

### ISSUE THREAD

**Issue by zuckerruebe** [scipy/scipy#17599]
`curve_fit` gives me different values in its `f_vec` than what I compute using the solution parameters for the objective function on the input data.

See this [notebook](https://gist.github.com/zuckerruebe/9348c26f5ef2612a901a5dba84b7ff6d) (relevant stuff starts at `In [15]`).

**Comment by andyfaff** [comment]
Please make the notebook available as an ipynb viewable somewhere. It's a security risk for anyone to try to view the PDF.

**Comment by andyfaff** [comment]
Also, please ensure that the example is an MWE, a minimal working example.

**Comment by zuckerruebe** [comment]
@andyfaff Would a zipped .html export also work?

**Comment by zuckerruebe** [comment]
@andyfaff Character-wise it could be more minimal, but in terms of logic it's really compute the solution, compute the fitted `y`s and compare. Let me know if you need the raw data, too.

**Comment by zuckerruebe** [comment]
@tupui Yes, OK, sorry, somehow managed to bypass the template selection. Will do that once I get round to it. Cheers.

**Comment by zuckerruebe** [comment]
Opened a new issue according to the "Bug" template with a MWE here: https://github.com/scipy/scipy/issues/17604.
