### ISSUE TITLE
BUG: cannot import name 'permutation_test' from 'scipy.stats'

### ISSUE THREAD

**Issue by Palash123-4** [scipy/scipy#17593]
### Describe your issue.

I am trying to implement the permutation_test from scipy.stats. Unfortunately, it shows I cannot import 'permutation_test' 

### Reproducing Code Example

```python
>>> from scipy.stats import permutation_test
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'permutation_test' from 'scipy.stats' (/home/choaak/anaconda3/lib/python3.7/site-packages/scipy/stats/__init__.py)
```

### SciPy/NumPy/Python version information

Python 3.7.15, numpy 1.21.5, scipy 1.7.3

**Comment by mdhaber** [comment]
This function was added in 1.8.0, but you are using 1.7.3. please upgrade to use `permutation_test`.
