### ISSUE TITLE
BUG: dgemm wrapper ignores beta?

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#17594]
As far as I can tell, we currently ignore `beta` for our `dgemm` wrapper. The following prints the same array over and over for example.

```python
import numpy as np

import scipy
from scipy.linalg.blas import dgemm


alpha = 1.0
a = np.array([[1, 7, 9],
             [3, 1, 3],
             [5, 5, 22]], dtype=np.float64)
b = np.array([[9, 0, 2],
             [77, 100, 4],
             [1, 500, 9]], dtype=np.float64)

for beta in range(1000):
    result = dgemm(alpha, a, b, beta)
    print("result:\n", result)
```

@ilayn am I missing something? I was comparing with Algorithm 1 from Kurzak et al. (2012), IEEE Transactions on Parallel and Distributed Systems 23 (11).

**Comment by JesseLivezey** [comment]
`beta` scales the `+beta*C` term
https://netlib.org/lapack/explore-html/d1/d54/group__double__blas__level3_gaeda3cbd99c8fb834a60a6412878226e1.html

```python
    result = dgemm(alpha, a, b, beta, c)
```
should give different values if `c!=0`

**Comment by tylerjereddy** [comment]
Ah, gothca
