### ISSUE TITLE
BUG: Python 3.11 install problem

### ISSUE THREAD

**Issue by Mitchell-kw-Lee** [scipy/scipy#17607]
### Describe your issue.

just cannot be installed with python 3.11.
NO Wheel for python 3.11 exist. urgent

### Reproducing Code Example

```python
pip install scipy
```

### Error message

```shell
build error
```

### SciPy/NumPy/Python version information

python 3.11

**Comment by andyfaff** [comment]
Please provide more details. There are wheels for 3.11 available on PyPI. What OS, what flavour of Python, are you pip installing?

**Comment by Mitchell-kw-Lee** [comment]
- windows 11 22H2 64bit
- Python 3.11.0 **_32BIT_**

**Comment by tylerjereddy** [comment]
see also: https://github.com/scipy/scipy/issues/17424#issuecomment-1315105135

**Comment by andyfaff** [comment]
There are windows 64 bit wheels available on PyPI for cp311.

**Comment by tylerjereddy** [comment]
looks like the interpreter is 32 bit though

**Comment by andyfaff** [comment]
Yeah, sorry I mistakenly read that as two different interpreters. There is no current plan to make 32 bit wheels available for future releases. Is there a reason you can't use a 64 bit interpreter?

**Comment by andyfaff** [comment]
Closing as a similar issue to https://github.com/scipy/scipy/issues/17424, and there are no current plans to release a windows 32 bit wheel.

**Comment by Mitchell-kw-Lee** [comment]
> Yeah, sorry I mistakenly read that as two different interpreters. There is no current plan to make 32 bit wheels available for future releases. Is there a reason you can't use a 64 bit interpreter?

Ok, by the relieved the uncertainty, will find out workaround
since I only can to use a windows specific 32bit library(my headache) 
which only allows python 32bit.

Have a gooday.
