### ISSUE TITLE
DOC: optimize.curve_fit: documentation of `fvec` is not specific

### ISSUE THREAD

**Issue by zuckerruebe** [scipy/scipy#17604]
### Describe your issue.

`curve_fit` gives me different values in its `fvec` than what I compute using the solution parameters for the objective function on the input data.

### Reproducing Code Example

```python
import scipy.optimize as so
import numpy.random as rnd
import numpy as np

rng = rnd.default_rng(3141592)

def objective_function(x, A, phi, Tbar):
    return Tbar - A*np.cos(2*np.pi/365*(x - phi))

x = np.arange(0, 366, 1)
y = objective_function(x, A=8.7, phi=13.5, Tbar=12.3) + 5*rng.normal(size=x.shape)

result = so.curve_fit(objective_function, x, y, p0=[12, 31, 12], full_output=True)

p = result[0]

y_fitted_theirs = result[2]["fvec"]

y_fitted_mine = objective_function(x, *p)

import numpy.linalg as lin
erel = lin.norm(y_fitted_theirs-y_fitted_mine)/lin.norm(y_fitted_mine)
erel
```

### Expected behaviour
Would expect `erel` to be much lower.

### SciPy/NumPy/Python version information

1.9.3 1.23.5 sys.version_info(major=3, minor=10, micro=5, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
Change `y_fitted_mine = objective_function(x, *p)` to `y_fitted_mine = objective_function(x, *p) - y`.

**Comment by andyfaff** [comment]
Yeah, the documentation is incorrect here. From my reading of the docstring `fvec = fun(x, *p)`. As @mdhaber points out the behaviour is actually `fvec = fun(x, *p) - y`.

**Comment by andyfaff** [comment]
Actually my change wasn't fully correct. It should be `fvec = (fun(x, *p) - y)/sigma` for a 1-D sigma. I'm not sure what it is for a 2-D sigma.
