### ISSUE TITLE
BUG: interp1d with fill_value="extrapolate" results in linter error

### ISSUE THREAD

**Issue by hans1602** [scipy/scipy#17612]
### Describe your issue.

When using fill_value="extrapolate" in interp1d, linters will flag the use of a str value. The expected value is a ndarray or float, as defined in the interp1d class `__init__`.

```
    def __init__(self, x, y, kind='linear', axis=-1,
                 copy=True, bounds_error=None, fill_value=np.nan,
                 assume_sorted=False):
```
### Reproducing Code Example

```python
from scipy.interpolate import interp1d

rate = interp1d(x, y, fill_value="extrapolate")
```

### Error message

```shell
Argument of type "Literal['extrapolate']" cannot be assigned to parameter "fill_value" of type "float" in function "__init__"
  "Literal['extrapolate']" is incompatible with "float" Pylance(reportGeneralTypeIssues)
```

### SciPy/NumPy/Python version information

1.9.3 1.22.3 sys.version_info(major=3, minor=8, micro=15, releaselevel='final', serial=0)

**Comment by ev-br** [comment]
The pattern of overloading an argument to a number or a string is very common, in scipy and elsewhere. The linter here is being unreasonable. 
So this is something to fix with the linter. 

Adding correct type annotations along the lines of `number | str` is also an option. Note that scipy.interpolate is not type annotated currently. This might be a dedicated if rather large project. We might consider type annotating it --- this will need a champion who is willing to first formulate the proposal, discuss it on the scipy-dev mailing list, and implement the outcome of the ML discussion. Would you be interested in doing that?

**Comment by tupui** [comment]
It's always PyLance that complains... it's not the first issue we have due to this plugin.

I would close this issue. Nothing in there we are not already tracking.

**Comment by ev-br** [comment]
Okay, let's close this as a wontfix indeed. 
Thanks for the report @hans1602 anyway. Hopefully the linter plugin gets fixed at some point.
