### ISSUE TITLE
BUG: Confusing documentation

### ISSUE THREAD

**Issue by rvzaytsev** [scipy/scipy#17623]
### Describe your issue.

The documentation for scipy.stats.norm is confusing: what is parameter scale? The usual notation is mu and sigma, the documentation should explicitly explain their relation to parameters loc and scale.

### Reproducing Code Example

```python
-
```

### Error message

```shell
-
```

### SciPy/NumPy/Python version information

-

**Comment by tupui** [comment]
Hi @rvzaytsev, thank you for reporting.

I believe it's clear though: 

```
The location (loc) keyword specifies the mean. The scale (scale) keyword specifies the standard deviation.
```
