### ISSUE TITLE
ENH: Cachable normalisation parameter for frozen distributions

### ISSUE THREAD

**Issue by health-nut-cocopops** [scipy/scipy#17620]
### Is your feature request related to a problem? Please describe.

Suppose I want to create the Conway-Maxwell-Poisson distribution. I have 

```
import numpy as np
from mpmath import nsum, fac, inf
from scipy import stats


def pmf(k, z, mu, nu):
    return float((mu ** k) / ((fac(k) ** nu) * z))


vectorized_pmf = np.vectorize(pmf)


class com_poisson_gen(stats.rv_discrete):
    def _argcheck(self, mu, nu):
        return mu >= 0 & nu >= 0

    def _pmf(self, k, mu, nu):
        normalization_factor = nsum(lambda j: (mu ** j) / (fac(j) ** nu), [0, inf])
        return vectorized_pmf(k, normalization_factor, mu, nu)


com_poisson = com_poisson_gen(name="com-poisson", longname='Conway-Maxwell-Poisson')
com_poisson(4, 1).rvs(size=100)
```

However this is very inefficient to keep recalculating the normalization parameter.

### Describe the solution you'd like.

Some ability to pre-calculate this parameter at initialization or freezing

**Comment by tupui** [comment]
Hi @health-nut-cocopops, thank you for reporting.

Did you consider caching `normalization_factor` on your side? Without changing too much what you do, you can just define this in the class initialisation and check for existing values. Or use a LRU cache.

I am not sure there is much to do in SciPy itself.

**Comment by health-nut-cocopops** [comment]
That would be great but how does one access mu and nu from there @tupui ? Sorry a bit new to the structure

**Comment by tupui** [comment]
E.g. following `skew_norm_gen`

```python
@lru_cache
def _normalization_factor(self, mu, nu):
    return nsum(lambda j: (mu ** j) / (fac(j) ** nu), [0, inf])

def _pmf(self, k, mu, nu):
	normalization_factor = self._normalization_factor(mu, nu)
    return vectorized_pmf(k, normalization_factor, mu, nu)
```

**Comment by health-nut-cocopops** [comment]
Thank you kindly

**Comment by tupui** [comment]
Great, then since it seems to cover the issue, I am closing it.
