### ISSUE TITLE
ENH: Improve small angle approximations in Rotations class

### ISSUE THREAD

**Issue by scottshambaugh** [scipy/scipy#17635]
Per the discussion here: https://github.com/scipy/scipy/pull/17452#discussion_r1042630440 @evbernardes discovered that there are two small angle taylor series approximations in `scipy.spatial.transform._rotation.pyx` that may have higher fidelity / faster ways of being calculated. Should investigate further and update as appropriate.

**Comment by j-bowhay** [comment]
Closing as testing with mpmath shows that the linked pr was less accurate:
```
In [3]: from mpmath import mp

In [4]: mp.dps = 50

In [5]: def taylor_3terms(angle):
   ...:     angle2 = angle * angle
   ...:     return 0.5 - angle2 / 48 + angle2 * angle2 / 3840
   ...:

In [6]: def real(angle):
   ...:     return mp.sin(angle / 2) / angle
   ...:

In [7]: def test(angle):
   ...:     error_3 = taylor_3terms(angle) - real(angle)
   ...:     error_1 = 0.5 - real(angle)
   ...:     print(f'Input: {angle}, Error Taylor 3 terms: {error_3}, Error Taylor 1 term: {error_1}')
   ...:

In [8]: test(1e-3)
Input: 0.001, Error Taylor 3 terms: 1.4227050928359908448757176701359848262792983693296e-17, Error Taylor 1 term: 0.000000020833333072916669084127583937944417301945785762793

In [9]: test(1e-5)
Input: 1e-05, Error Taylor 3 terms: -1.7237837674059221863412819606379162162941607841419e-19, Error Taylor 1 term: 0.0000000000020833333333307295075127261910442282526146283705839

In [10]: test(1e-7)
Input: 1e-07, Error Taylor 3 terms: -1.3711271591698019648013072832216252525123455380981e-17, Error Taylor 1 term: 2.0833333333333328843671326078594780997487654461902e-16

In [11]: test(1e-8)
Input: 1e-08, Error Taylor 3 terms: 2.0833333333333334179065034588686373588934566793233e-18, Error Taylor 1 term: 2.0833333333333334179065034588686373588934566793233e-18
````

**Comment by evbernardes** [comment]
This confirms my tests though, doesn't it? As the original has three terms and is valid to differences up to `1e-3`, leading to errors up to `A = 1.422e-17` while my proposal uses one term and is valid to differences up to `1e-8`, leading to errors up to `B = 2.08e-18`, which is smaller.

**Comment by j-bowhay** [comment]
Sorry I missed that you were also moving the cutoff point. But still, I think there needs to be a more compelling reason to make the change. Yes, you gain one decimal place of accuracy but you have use `np.sin` more which is slower:
```
In [12]: angle = 1e-4

In [13]: angle2 = angle * angle

In [14]: %timeit 0.5 - angle2 / 48 + angle2 * angle2 / 3840
85.3 ns ± 15.2 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [15]: import numpy as np

In [16]: %timeit np.sin(angle / 2) / angle
744 ns ± 236 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```
So I am not sure there is compelling evidence to change it

**Comment by evbernardes** [comment]
Ok, makes perfect sense! Thank you for looking into this!
