### ISSUE TITLE
Inconsistent support for empty matrices in linalg

### ISSUE THREAD

**Issue by JozsefKutas** [scipy/scipy#17658]
Some functions in `scipy.linalg` handle empty matrix arguments and some don't - there doesn't seem to be an obvious pattern. On the other hand, `numpy.linalg` seems to support empty matrices in all functions (though I didn't test exhaustively).

For example, `solve` and `cholesky` both support empty matrices by explicitly handling empty matrix arguments before calling LAPACK:

```python
>>> import numpy as np
>>> from scipy import linalg
>>> a = np.array([]).reshape((0, 0))
>>> linalg.solve(a, a)
array([], shape=(0, 0), dtype=float64)
>>>  linalg.cholesky(a)
array([], shape=(0, 0), dtype=float64)
```

while `inv` and most other functions don't:

```python
>>> linalg.inv(a)
```

```
Traceback (most recent call last):
  File "...\.venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-8c6d9a341a08>", line 1, in <module>
    linalg.inv(a)
  File "...\.venv\Lib\site-packages\scipy\linalg\_basic.py", line 958, in inv
    raise ValueError('illegal value in %d-th argument of internal '
ValueError: illegal value in 4-th argument of internal getrf|getri
```

Empty matrix support can be convenient when matrix sizes are determined dynamically, for example, according to statistical significance tests.

**Comment by ilayn** [comment]
Agreed. This is something we should consider breaking backwards compatibility to attain a consistent implementation. Edge cases had been our soft spot in linalg for such functions that grew a bit heterogeneously.

**Comment by boatwrong** [comment]
I'm interested in looking into this issue. From what I can tell the cholesky decomp function returns an empty array of the same size. This seems like it would also serve as a valid return for the inverse function right? 

Also, Iĺl look into other functions that could benefit from empty matrix support that do not already implement it.

**Comment by JozsefKutas** [comment]
> I'm interested in looking into this issue. From what I can tell the cholesky decomp function returns an empty array of the same size. This seems like it would also serve as a valid return for the inverse function right?

Yup, it should just be an array of the same (zero size) dimensions as the input.

I think either `solve` or `cholesky` could be used for reference. For functions like `inv`, the result should be consistent with the result from the corresponding function in numpy.

**Comment by JozsefKutas** [comment]
Hi @boatwrong, thanks for working on this. I should have some free time over the next couple of weeks, so if you want I'd be happy to continue from where you left off.

**Comment by boatwrong** [comment]
@JosefKutas Apologies for my late response, thank you for reaching out and looking into this! Please feel free to continue on.

What you’ve explained/written looks great and I appreciate you taking it further than I could.
________________________________
