### ISSUE TITLE
Check for non-running tests because of test function name and fix them up

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#17652]
It looks like we have some issues in the test suite with non-running tests. @MarcoGorelli just wrote a script to check this, see `scripts/check_test_naming.py` in https://github.com/pandas-dev/pandas/pull/50397. 

I verified that we've got at least one such test (see https://github.com/rgommers/scipy/tree/fix-broken-test-name), so there are probably more. It'd be good if we could take over the test script from Pandas, put it in `tools/`, fix whatever issues that turns up, and then run the script in exactly one CI job (next to refguide check probably).

**Comment by tupui** [comment]
Should we not just rely on coverage of tests as @MarcoGorelli suggests instead of running this tool?

**Comment by rgommers** [comment]
No one is going to look through all coverage results for PRs, that's way too much work. And it's not possible to rely on a coverage threshold either. So someone can look through coverage results once manually and fix what's not running, but that's about it.

If we judge that this script is too maintenance-intensive, then it's fine to reject the idea. But I think it's either that, or the status quo.

**Comment by MarcoGorelli** [comment]
There's quite a few more:

https://github.com/scipy/scipy/blob/6a555164767a6624ba3721edd8c3f580f97a85f3/scipy/stats/tests/test_distributions.py#L6743-L6750

https://github.com/scipy/scipy/blob/6a555164767a6624ba3721edd8c3f580f97a85f3/scipy/stats/tests/test_distributions.py#L4402-L4415

https://github.com/scipy/scipy/blob/6a555164767a6624ba3721edd8c3f580f97a85f3/scipy/stats/tests/test_distributions.py#L1166-L1172

https://github.com/scipy/scipy/blob/4e738d77dd217304a564c4269c99f2f4332f02a8/scipy/stats/tests/test_continuous_basic.py#L638-L644

https://github.com/scipy/scipy/blob/4c53ae1f970cf8c3a8e5d624c8043af9fe465db7/scipy/special/tests/test_orthogonal.py#L211-L238

and many, many more...all the ones I checked were genuine, though if there are any false positives, you can prevent the check from flaggin them with a `# not a test` comment

---

@tupui yeah if you're close enough to 100% coverage that you can enable it, that would be a better solution. In meantime, I've made this a bit more generic and have put it in its own package: https://github.com/MarcoGorelli/madforhooks#check-test-naming

**Comment by j-bowhay** [comment]
The current output from my pr:
```
python dev.py check-test-name
scipy/spatial/tests/test_qhull.py:20:0 found test function which does not start with 'test'
scipy/stats/tests/test_continuous_basic.py:638:0 found test function which does not start with 'test'
scipy/stats/tests/test_mstats_basic.py:1080:4 found test function which does not start with 'test'
scipy/stats/tests/test_distributions.py:1166:4 found test function which does not start with 'test'
scipy/stats/tests/test_distributions.py:4402:0 found test function which does not start with 'test'
scipy/stats/tests/test_distributions.py:6743:4 found test function which does not start with 'test'
scipy/stats/tests/test_hypotests.py:673:4 found test function which does not start with 'test'
scipy/sparse/tests/test_sparsetools.py:223:4 found test function which does not start with 'test'
scipy/sparse/tests/test_sparsetools.py:231:4 found test function which does not start with 'test'
scipy/sparse/tests/test_sparsetools.py:239:4 found test function which does not start with 'test'
scipy/sparse/tests/test_sparsetools.py:247:4 found test function which does not start with 'test'
scipy/sparse/tests/test_sparsetools.py:252:4 found test function which does not start with 'test'
scipy/sparse/tests/test_sparsetools.py:257:4 found test function which does not start with 'test'
scipy/sparse/linalg/_eigen/tests/test_svds.py:39:0 found test function which does not start with 'test'
scipy/sparse/linalg/_eigen/arpack/tests/test_arpack.py:133:0 found test function which does not start with 'test'
scipy/optimize/tests/test__spectral.py:152:0 found test function which does not start with 'test'
scipy/optimize/tests/test__spectral.py:162:0 found test function which does not start with 'test'
scipy/optimize/tests/test__remove_redundancy.py:24:0 found test function which does not start with 'test'
scipy/optimize/tests/test__remove_redundancy.py:28:0 found test function which does not start with 'test'
scipy/optimize/tests/test_linesearch.py:56:4 found test function which does not start with 'test'
scipy/optimize/tests/test_linesearch.py:62:4 found test function which does not start with 'test'
scipy/optimize/tests/test_linesearch.py:68:4 found test function which does not start with 'test'
scipy/optimize/tests/test_linesearch.py:76:4 found test function which does not start with 'test'
scipy/optimize/tests/test_linesearch.py:82:4 found test function which does not start with 'test'
scipy/optimize/tests/test__numdiff.py:218:4 found test function which does not start with 'test'
scipy/fftpack/tests/test_basic.py:45:0 found test function which does not start with 'test'
scipy/io/tests/test_idl.py:15:0 found test function which does not start with 'test'
scipy/cluster/tests/test_hierarchy.py:1020:0 found test function which does not start with 'test'
scipy/fft/_pocketfft/tests/test_basic.py:52:0 found test function which does not start with 'test'
scipy/special/tests/test_basic.py:497:4 found test function which does not start with 'test'
scipy/special/tests/test_basic.py:512:4 found test function which does not start with 'test'
scipy/special/tests/test_basic.py:539:4 found test function which does not start with 'test'
scipy/special/tests/test_basic.py:562:4 found test function which does not start with 'test'
scipy/special/tests/test_basic.py:565:4 found test function which does not start with 'test'
scipy/special/tests/test_basic.py:703:4 found test function which does not start with 'test'
scipy/special/tests/test_basic.py:715:4 found test function which does not start with 'test'
scipy/special/tests/test_basic.py:757:4 found test function which does not start with 'test'
scipy/special/tests/test_basic.py:781:4 found test function which does not start with 'test'
scipy/special/tests/test_basic.py:838:4 found test function which does not start with 'test'
scipy/special/tests/test_basic.py:950:4 found test function which does not start with 'test'
scipy/special/tests/test_orthogonal.py:136:0 found test class which does not start with 'Test'
scipy/special/tests/test_orthogonal.py:161:0 found test class which does not start with 'Test'
scipy/special/tests/test_orthogonal.py:186:0 found test class which does not start with 'Test'
scipy/special/tests/test_orthogonal.py:211:0 found test class which does not start with 'Test'
scipy/special/tests/test_data.py:67:0 found test function which does not start with 'test'
scipy/linalg/tests/test_decomp.py:88:0 found test function which does not start with 'test'
scipy/linalg/tests/test_decomp.py:131:0 found test function which does not start with 'test'
scipy/linalg/tests/test_decomp.py:2247:0 found test function which does not start with 'test'
scipy/_lib/tests/test_public_api.py:14:0 found test function which does not start with 'test'
```

**Comment by tupui** [comment]
A suggestion, that would help searching if you also printed the name of the function.

**Comment by MarcoGorelli** [comment]
Why not run it in CI? In pandas [this only takes 3-4 seconds to run on all files](https://github.com/pandas-dev/pandas/actions/runs/3893392488/jobs/6645943036)

You could have a list of excluded tests (initially, all of them), and as tests are fixed up, you remove them from the exclusions list

This has worked well in pandas - e.g. of PR fixing up some test names + removing that file from the exclusions list: https://github.com/pandas-dev/pandas/pull/50445/files

I'm aware you don't use pre-commit, but you could just do this with a list in the file

**Comment by tupui** [comment]
> Why not run it in CI? In pandas [this only takes 3-4 seconds to run on all files](https://github.com/pandas-dev/pandas/actions/runs/3893392488/jobs/6645943036)

If embedded with the linter check why not. I try to spare resources.
