### ISSUE TITLE
ENH: Generate documentation for old versions of scipy

### ISSUE THREAD

**Issue by KOLANICH** [scipy/scipy#17659]
### Is your feature request related to a problem? Please describe.

I happenned to be porting an old abandonware program (Python 2.6 one, the last release was more than 10 years before) found in the Internet to modern versions of Python and its packages. It turns out that quite some API got extinct and there is no docs about it. So since IDK what exactly those API does and what signature it uses and what is the semantics of the arguments, it's hard to find proper modern replacement.

It turns out the docs for those `scipy` versions that still had that API is missing from the website.

### Describe the solution you'd like.

1. regenerate the docs for every past release
2. make [Wayback Machine](https://web.archive.org/) to archive them fully
3. after this, if storage is a concern, you can remove the legacy API docs from the website and rewrite the links to use Wayback Machine
4. setup a flow that when a release is made, the API docs are automatically backuped to Wayback Machine

**Comment by KOLANICH** [comment]
P.S. I know I can look it within the source code on GitHub (I had already done this), but it'd nice if that was present on the website too.

**Comment by ilayn** [comment]
The previous versions of the docs are here https://docs.scipy.org/doc/

Also, you can always generate the HTML/PDF SciPy docs offline for your own use. Note that Wayback Machine is not a storage and that is practically abusing it. It has a very important purpose and we shouldn't use it for storage needs.

**Comment by KOLANICH** [comment]
Thanks, that's what I needed.
