### ISSUE TITLE
BUG: Deprecation warning says to use non-existent symbols

### ISSUE THREAD

**Issue by efahl** [scipy/scipy#17671]
### Describe your issue.

About a year ago (commit 6b08e087171479b30fc2dc015d2074a24844789e) the ``optimize.tnc`` module gained some deprecation warnings, indicating that symbols of the form ``optimze.tnc.<SYM>`` were deprecated, use instead ``optimize.<SYM>``.  Since none of these symbols exist in optimize directly, doing as suggested generates ``ImportError``.

### Reproducing Code Example

```python
$ python -c 'from scipy.optimize.tnc import RCSTRINGS ; from scipy.optimize import RCSTRINGS'
```

### Error message

```shell
<string>:1: DeprecationWarning: Please use `RCSTRINGS` from the `scipy.optimize` namespace, the `scipy.optimize.tnc` namespace is deprecated.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'RCSTRINGS' from 'scipy.optimize' (C:\Program Files\Python310\lib\site-packages\scipy\optimize\__init__.py)
```

### SciPy/NumPy/Python version information

1.9.3 1.24.1 sys.version_info(major=3, minor=10, micro=7, releaselevel='final', serial=0)

**Comment by j-bowhay** [comment]
xref #17572

**Comment by efahl** [comment]
Thanks, yup, same thing.  My searches for deprecation, optimize and so on missed those.  Feel free to close as a duplicate, if it doesn't add anything to those already-existing bug reports.

**Comment by tupui** [comment]
Yes let's close it since we have already an active issue. Still thank you for reporting @efahl!
