### ISSUE TITLE
BUG: special: `pbvv_seq` is broken.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#17681]
The function `scipy.special.pbvv_seq` fails to run:

```
In [1]: import scipy

In [2]: scipy.__version__
Out[2]: '1.11.0.dev0+1208.2af3085'

In [3]: from scipy.special import pbvv_seq

In [4]: pbvv_seq(3, 1.5)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [4], line 1
----> 1 pbvv_seq(3, 1.5)

File ~/repos/git/forks/scipy/build-install/lib/python3.10/site-packages/scipy/special/_basic.py:2235, in pbvv_seq(v, x)
   2233     n1 = n
   2234 v1 = n1 + v0
-> 2235 dv, dp, pdf, pdd = _specfun.pbvv(v1, x)
   2236 return dv[:n1+1], dp[:n1+1]

AttributeError: module 'scipy.special._specfun' has no attribute 'pbvv'
```
This function has no tests, otherwise we would have caught this issue a long time ago.  <strike>I don't know how long it has been broken.  If it has *never* worked, we could consider simply deleting it.</strike> *Edit:* `pbvv_seq` was discussed in https://github.com/scipy/scipy/issues/4957, so apparently it was working back in 2015.

**Comment by tupui** [comment]
+1 for the deletion if it's not working since a few releases. If no one is complaining, probably not used.

**Comment by WarrenWeckesser** [comment]
After reading https://github.com/scipy/scipy/issues/4957, it is clear that `pbvv_seq` has worked in the past.  It broke some time after that issue was reported in 2015.
