### ISSUE TITLE
TST: stats: Several functions with no tests in `stats.mstats`

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#17683]
I noticed a few functions in `scipy.stats.mstats` that have no tests:
- [x] [`median_cihs`](https://scipy.github.io/devdocs/reference/generated/scipy.stats.mstats.median_cihs.html)
- [x] [`sen_seasonal_slopes`](https://scipy.github.io/devdocs/reference/generated/scipy.stats.mstats.sen_seasonal_slopes.html)
- [x] [`trimmed_var`](https://scipy.github.io/devdocs/reference/generated/scipy.stats.mstats.trimmed_var.html)
- [x] [`trimmed_std`](https://scipy.github.io/devdocs/reference/generated/scipy.stats.mstats.trimmed_std.html)

I added the 'good first issue' tag, because the *code* required to add tests is simple. Tests for all the functions do not have to be added in a single pull request.  I suspect `trimmed_var` and `trimmed_std` would be the easiest ones to add tests for, and a single pull request that covers both of them should be easy.  The other two will probably require some understanding of what the functions compute, so those could be considered "good first issue for someone with knowledge of the statistics involved".

**Comment by tupui** [comment]
What is the status actually of this submodule? I was under the impression that we would want to deprecate this no?

**Comment by mdhaber** [comment]
Yes. Functions in `stats` will support masked arrays, and `mstats` will be deprecated.

**Comment by mdhaber** [comment]
I already added `sen_seasonal_slopes` in gh-16434.

> ok then I don't think we should spend any energy there.

If there is no stats counterpart, like `sen_seasonal_slopes`, I think it's worth doing. It will save some effort when we want to move the function to `stats`. So I'd be willing to review an example for `median_cihs`, personally.

**Comment by WarrenWeckesser** [comment]
> ok then I don't think we should spend any energy there.

By "there", do you mean tests for these `mstats` functions?  They will needs tests regardless of where they end up.

**Comment by tupui** [comment]
ok thanks for the precisions 😃

**Comment by OmarManzoor** [comment]
Hi @WarrenWeckesser , @mdhaber 
As a first time contributor would it be okay for me to work on this issue?

**Comment by mdhaber** [comment]
Yes, @OmarManzoor you're welcome to work on it.

**Comment by mdhaber** [comment]
Basic tests have been added for the four functions listed in the top post. The tests have blind spots that we try to avoid these days - for example, they don't exercise all arguments, and not all confirm that the function deals with masked arrays as expected. On the other hand, the same can be said of existing tests of other mstats functions. So I'll let others assess whether this issue should be closed.

I'd also alert others to the issue that `median_cihs` does not always agree with the R function it is tested against. 
https://github.com/scipy/scipy/blob/7116af119d82ce305e496cf23f0eae3990657097/scipy/stats/tests/test_mstats_extras.py#L151-L166

The lower limits of the confidence interval always seem to agree precisely, and for some ranges of `alpha` the upper limits of the confidence interval also agree precisely, but there are ranges of `alpha` for which they do not agree. This may warrant its own issue.

**Comment by WarrenWeckesser** [comment]
OK, closing.

> ...  there are ranges of alpha for which they do not agree. This may warrant its own issue.

A new issue specifically for that question makes sense.
