### ISSUE TITLE
scipy.stats.bootstrap broke with statistic returning multiple values

### ISSUE THREAD

**Issue by slanzmich** [scipy/scipy#17715]
The issue appeared upgrading from scipy-1.9.3 to scipy-1.10.0

We are using `scipy.stats.bootstrap` with a vectorized `statistic` that returns multiple values, i.e. computes multiple statistics at once.

Consider the following example:
```python
import numpy as np
from scipy.stats import bootstrap


def statistic_ccc(cm: np.ndarray, axis: int) -> np.ndarray:
    tp, tn, fp, fn = cm
    actual = tp + fp
    expected = tp + fn

    ret = np.nan_to_num(
        concordance_array(actual, expected, axis=axis), copy=False, nan=0.0
    )
    # This is intended to return multiple statistics, this just inserts an extra
    # dimension. With scipy-1.9.3, stacking along the zeroth dimension worked.
    # However, due to the changes in PR 16455, this no longer works.
    return ret[None, ...]


def concordance_array(x: np.ndarray, y: np.ndarray, axis: int) -> np.ndarray:
    assert x.shape == y.shape
    assert axis == -1

    if x.ndim == 1:
        return np.asarray(concordance(x, y), dtype=float)
    if x.ndim == 2:
        return np.array(
            [concordance(x[k, :], y[k, :]) for k in range(x.shape[0])], dtype=float
        )
    assert False


def concordance(x: np.ndarray, y: np.ndarray) -> float:
    xm = x.mean()
    ym = y.mean()
    covariance = ((x - xm) * (y - ym)).mean()
    ccc = (2 * covariance) / (x.var() + y.var() + (xm - ym) ** 2)
    return ccc


# Elements are (tp, tn, fp, fn)
data = (
    np.array([[4, 0, 0, 2], [2, 1, 2, 1], [0, 6, 0, 0], [0, 6, 3, 0], [0, 8, 1, 0]]),
)
ret = bootstrap(
    data,
    statistic_ccc,
    confidence_level=0.9,
    random_state=42,
    vectorized=True,
)
print(ret.confidence_interval)
```

With `scipy-1.9.3`, the output was
```
ConfidenceInterval(low=array([0.]), high=array([0.87804878]))
```
or, without the insertion of another dimension in `statistic_ccc`, 
```
ConfidenceInterval(low=0.0, high=0.878048780487805)
```

With `scipy-1.10.0`, the output becomes
```
ConfidenceInterval(low=array([nan]), high=array([nan]))
```
or, without the insertion of another dimension in `statistic_ccc`, 
```
ConfidenceInterval(low=0.23076923076923073, high=0.8962655601659751)
```
which still differs from the behavior in `scipy-1.9.3`, but produces finite values.

This is caused by the changes in #16455, more specifically the use of `len` in [`n_j = [len(theta_hat_i) for theta_hat_i in theta_hat_ji]`](https://github.com/scipy/scipy/pull/16455/files#diff-5e166dc85b2974fd7623468824906943e72c8b43ac1f45bcc1374c5dcc797895R132).

Due to the batching and concatenation in `_bca_interval`, `statistic` cannot insert a dimension at the end. Using `theta_hat_i.shape[-1]` instead of `len(theta_hat_i)` would solve the issue for my use case, but I'm not sure I miss anything. What do you think?

**Comment by slanzmich** [comment]
All computations in `_bca_interval` are done along `axis=-1`, so `.shape[-1]` looks more reasonable than `.shape[0]` / `len()`. If you agree, I can prepare a PR with that one-line fix, and add a parametrization to the existing test cases.

Also, shouldn't this be labelled `bug` or `regression` instead of `query`?

**Comment by mdhaber** [comment]
I broke it, so I'll fix it today.

**Comment by mdhaber** [comment]
@slanmich it looks to me like you really have a four-sample statistic. When each of `tp, tn, fp, fn` are 1D arrays (e.g. of length 5, like you have in `data` right now), `statistic_ccc` returns one number, right? I'm surprised you didn't get an error before. This is how `bootstrap` saw your data before:
- `data` was a tuple with _one_ sample, a 5 x 4 array, 
- `axis=0` by default
- `bootstrap` expects that `statistic` is a reduction statistic that acts along `axis=0`, so `bootstrap` would expect `statistic_ccc(data, axis=0)` to return an array with four elements.

If you want `tp, tn, fp, fn` to get reduced to a single number, this needs to be treated as a multi-sample statistic; `data` should have four elements. You can do this by taking `data` out of the tuple and transposing it, and `statistic_ccc` should accept `tp, tn, fp, fn` as separate arguments.

There is still a bug, but I'll continue to investigate.

**Comment by mdhaber** [comment]
@slanmich it looks to me like you really have a four-sample statistic. When each of `tp, tn, fp, fn` are 1D arrays (e.g. of length 5, like you have in `data` right now), `statistic_ccc` returns one number, right? I'm surprised you didn't get an error before. This is how `bootstrap` saw your data before:
- `data` was a tuple with _one_ sample, a 5 x 4 array, 
- `axis=0` by default
- `bootstrap` expects that `statistic` is a reduction statistic that acts along `axis=0`, so `bootstrap` would expect `statistic_ccc(data, axis=0)` to return an array with four elements.

If you want `tp, tn, fp, fn` to get reduced to a single number, this needs to be treated as a multi-sample statistic; `data` should have four elements. You can do this by taking `data` out of the tuple and transposing it, and `statistic_ccc` should accept `tp, tn, fp, fn` as separate arguments.

There is still a bug, but I'll continue to investigate.

**Comment by slanzmich** [comment]
Right, I think I also tried passing `data[0].transpose()`, but that causes the following `ValueError`, which is probably what you are referring to.
```
    actual = tp + fp
ValueError: operands could not be broadcast together with shapes (5,4) (5,5)
```
That error goes away if I call `bootstrap` with `paired=True`, which I thought would apply to my case. The handling of the `paired` parameter in `_bootstrap_iv` modifies `data` to contain a single item, which is probably why I stayed with the original single-item `data` in the example.

**Comment by mdhaber** [comment]
Ah, yes, ok. I'll submit a PR soon. Also, I mentioned above that I left the ability for `bootstrap` to handle multi-output statistics undocumented. Other than this issue, has it been working well enough that support for multi-output statistics should be a documented feature? Any other features you'd like to see in 1.11.0?
