### ISSUE TITLE
BUG: `_axis_nan_policy` changes some common `TypeError`s

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#17713]
### Describe your issue.

Functions wrapped with the `_axis_nan_policy` decorator give the correct error message when unrecognized arguments are passed and when multiple values are passed for the same argument:

<details>

```python3
from scipy import stats
stats.gmean([1, 2, 3], invalid_arg=1)
```
raises:
```
TypeError: gmean() got an unexpected keyword argument 'invalid_arg'
```
and
```python3
stats.gmean([1, 2, 3], a=True)
```
raises
```
TypeError: gmean() got multiple values for argument 'a'
```
</details>

---

However, it looks like some other common cases did not get the same treatment:

```python3
stats.gmean()  # requires an argument
```
raises:
```
KeyError: 'a'
```
when it should be:
```
TypeError: gmean() missing 1 required positional argument: 'a'
```

and

```python3
stats.gmean([1, 2, 3], 0, float, [1, 1, 1], 10, 20, 30)  # too many positional arguments
```
raises nothing, but it should raise

```
TypeError: gmean() takes from 1 to 4 positional arguments but 7 were given
```

Fortunately, it seems that this hasn't been terribly bothersome, as the bug has been present for a year without report. These sorts of issues should be quite easy to fix (if we can find them), so please let me know if you can find any others. I'll try to fix them in time for 1.10.1.

### Reproducing Code Example

```python
from scipy import stats
stats.gmean()  # requires an argument
```

### Error message

```shell
Traceback (most recent call last):

  File "C:\Users\matth\AppData\Local\Temp\ipykernel_52816\3198214520.py", line 1, in <module>
    stats.gmean()

  File "C:\Users\matth\scipy\scipy\stats\_axis_nan_policy.py", line 434, in axis_nan_policy_wrapper
    samples = [np.atleast_1d(kwds.pop(param))

  File "C:\Users\matth\scipy\scipy\stats\_axis_nan_policy.py", line 434, in <listcomp>
    samples = [np.atleast_1d(kwds.pop(param))

KeyError: 'a'
```

### SciPy/NumPy/Python version information

Since 1.8.0

**Comment by SoubhagyaKhan** [comment]
Sir, I want to work on this issue. Could you please guide me how to fix this bug?

**Comment by mdhaber** [comment]
May I suggest resolving the request discussed at https://github.com/scipy/scipy/issues/17250#issuecomment-1282964647 instead?
There are currently checks on what `options` are passed into `linprog` with `method='highs'`. The options should be passed into HiGHS, but a warning should be emitted. Please make it behave similar to `milp` in this situation and add a test that shows that the warning is emitted when an unrecognized option is used.
