### ISSUE TITLE
MAINT, DOC: doc_requirements and make dist and pooch

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#17710]
This patch is needed to succeed with `make dist` locally during the release process, to build the docs:

```diff
diff --git a/doc_requirements.txt b/doc_requirements.txt
index f601052f3..8f66e5886 100644
--- a/doc_requirements.txt
+++ b/doc_requirements.txt
@@ -5,3 +5,4 @@ pydata-sphinx-theme==0.9.0
 sphinx-design>=0.2.0
 numpydoc
 matplotlib>2
+pooch
```

It isn't caught by our CI because CircleCI installs `pooch` after the `pip install -r doc_requirements.txt` step. This really only matters for release management I think, but it may be helpful to pack the true requirements into that file.

**Comment by AnirudhDagar** [comment]
Interesting, out of curiosity, are the requirements from `environment.yml` not already installed before running `make dist` and building the docs? Or is this always a standalone, independent command?

**Comment by tylerjereddy** [comment]
`environment.yml` is a `conda`-specific thing, not used in local doc build process, which isolates to a `venv` I think; I also use a `venv` for releasing, so wouldn't use `environment.yml` in any case

**Comment by rgommers** [comment]
+1 to apply the suggested patch
