### ISSUE TITLE
BUG: dijkstra algorithm is returning different results in v1.10 compared to v1.9

### ISSUE THREAD

**Issue by jgostick** [scipy/scipy#17734]
### Describe your issue.

A unit test is failing in my CI but not locally, which usually means something changed in a dependency.  I have tracked it down to ``scipy.sparse.csgraph.dijkstra`` returning a different path in v1.10 (the CI version) compard to v1.9 (my local version). 

### Reproducing Code Example

```python
import numpy as np
import scipy.sparse as sprs
from scipy.sparse import csgraph
   
am = \
    [[0, 1, 0, 1, 0, 0, 0, 0, 0],
     [1, 0, 1, 0, 1, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 1, 0, 0, 0],
     [1, 0, 0, 0, 1, 0, 1, 0, 0],
     [0, 1, 0, 1, 0, 1, 0, 1, 0],
     [0, 0, 1, 0, 1, 0, 0, 0, 1],
     [0, 0, 0, 1, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 1, 0, 1, 0, 1],
     [0, 0, 0, 0, 0, 1, 0, 1, 0]]

am = sprs.coo_matrix(am)

paths = csgraph.dijkstra(csgraph=am, 
                         directed=False, 
                         indices=0,
                         return_predecessors=True, 
                         min_only=False)[1]
print(paths)
```

### Error message

```shell
On v1.10 I get this: ``[-9999     0     1     0     1     4     3     4     7]``.  Here is the full version info for this one: ``1.10.0 1.23.5 sys.version_info(major=3, minor=9, micro=15, releaselevel='final', serial=0)``

On v1.9 I get this: ``[-9999     0     1     0     1     2     3     6     7]``.  Here is the full version number for this one: ``1.9.3 1.23.5 sys.version_info(major=3, minor=9, micro=15, releaselevel='final', serial=0)``
```

### SciPy/NumPy/Python version information

1.10.0 1.23.5 sys.version_info(major=3, minor=9, micro=15, releaselevel='final', serial=0)

**Comment by windows-server-2003** [comment]
I made a change that caused this issue in #16696.
I think, in case where a vertex has more than one predecessor that achieves the shortest distance, the function can return any one of them, and that choice may change across scipy versions.
That being said, this may count as a breaking change. I ask for the scipy maintainers for an opinion on this.

**Comment by tupui** [comment]
@jjerphan Could you have a look?

**Comment by jjerphan** [comment]
I might, but it will take quite some time for me to get free time for it (especially given the technicality of resolving tie-breaks). :confused:

(Note that I have not approved https://github.com/scipy/scipy/pull/16696.)

**Comment by rgommers** [comment]
If there are two equivalent solutions, then I believe returning a different one in a newer SciPy version is not a breaking change. I see this as similar to linalg decompositions - the requirement is that a decomposition is valid/correct, not the detailed numerical results.

@jgostick is this just a difference you are observing and are the old and new solution equivalent for you? If not, what's the practical consequence of this behavior change for you?

**Comment by tupui** [comment]
To give a bit more context. This was discussed in a community meeting and we came to the conclusion that we should document that we cannot guarantee the outcome of a function if there are multiple optima or correct values. In case of graphs, it's easy to construct graphs which have multiple equal/shortest paths.

Hence we flagged this as a documentation issue to clarify this point to users.

**Comment by jgostick** [comment]
I actually seem to recall that the docs *used* to say this, but might be thinking of a different function. Anyway, a disclaimer to that effect is a good solution and would have helped me.  Thanks all!

**Comment by perimosocordiae** [comment]
Seems like the consensus is that in the presence of multiple valid solutions, scipy.csgraph is free to return any valid result, which may change depending on both scipy version and Python version(!): see gh-18494.

To close this issue, let's write a PR to include something to this effect in relevant docstrings / module documentation.
