### ISSUE TITLE
ENH: Please keep releasing scipy for 32bit linux 

### ISSUE THREAD

**Issue by ph1248** [scipy/scipy#17739]
### Is your feature request related to a problem? Please describe.

scipy is required for many projects / applications. Older 32bit hardware is often readily available and can be put to good use for these. (e.g., in my case I try to use an old thinclient as a paperless server). Unfortunately (to my knowledge) there are no recent scipy releases for 32bit linux. 

### Describe the solution you'd like.

Please release every version also for 32bit linux.

### Describe alternatives you've considered.

none

**Comment by tylerjereddy** [comment]
There are a bunch of discussions about this in various places in our ecosystem, this one in particular comes to mind: https://github.com/numpy/numpy/issues/20277, and it links to other discussions.

As far as I know, we do still test on Linux 32-bit, and we do support it, we just don't provide new pre-built binaries for some of the reasons highlighted in these discussions.

**Comment by tupui** [comment]
Let's close this. We have enough discussions all around (here and mailing list).
