### ISSUE TITLE
ENH: Further explanation about license using

### ISSUE THREAD

**Issue by Ashley123456789** [scipy/scipy#17741]
### Is your feature request related to a problem? Please describe.

When I **import** scipy as a third-party dependency through Anaconda or pip methods, 

- Should I comply with the LICENSE.txt (i.e., BSD 3-Clause)? Is the **import** action considered as **Redistribution and use** in the LICENSE.txt?
- Do I need to pay attention to **license compatibility**, i.e., can I claim a  **less strict license** than BSD 3-Clause for my projects?

**Comment by rgommers** [comment]
@Ashley123456789 no, if all you do is import scipy, then you don't have to worry about the license that SciPy is under. SciPy's BSD-3 license is not viral (unlike the GPL).
