### ISSUE TITLE
ENH: confidence interval for spearman confidence interval

### ISSUE THREAD

**Issue by lesshaste** [scipy/scipy#17746]
### Is your feature request related to a problem? Please describe.

Scipy currently doesn’t return a confidence interval for the spearman correlation coefficient.  This is standard in R however, https://search.r-project.org/CRAN/refmans/DescTools/html/SpearmanRho.html .

### Describe the solution you'd like.

An option to compute the confidence interval

**Comment by mdhaber** [comment]
We're gradually working on adding confidence intervals to the statistics that do not already have them. In the meantime, consider `scipy.stats.bootstrap`:
```python3
import numpy as np
from scipy import stats
rng = np.random.default_rng(82468935639010)

x = np.linspace(0, 10)
y = 1.5*x + rng.normal(size=x.shape)

def statistic(x, y):
    return stats.spearmanr(x, y).statistic

res = stats.bootstrap((x, y), statistic, method='bca', paired=True)

print(statistic(x, y), res.confidence_interval)
# 0.9726290516206483 ConfidenceInterval(low=0.9517124639523833, high=0.9884739535066726)
# compared to:
# SpearmanRho(x, y, conf.level=0.95)
#      rho    lwr.ci    upr.ci 
# 0.9726291 0.9520211 0.9844559 
```

**Comment by lesshaste** [comment]
Thank you so much. That code is very helpful.

**Comment by mdhaber** [comment]
@lesshaste if you like gh-18227 and would like that to be added to `spearmanr`, please consider mentioning your support in that PR.
