### ISSUE TITLE
ENH: Compute non centraled moments with `stats.moment`?

### ISSUE THREAD

**Issue by doronbehar** [scipy/scipy#17749]
### Is your feature request related to a problem? Please describe.

To compute a non-central moment of order `n>2`, one can't use the current implementation, but has to reside to implement their own.

### Describe the solution you'd like.

I'd like the `stats.moment` function to perhaps support a `central: Bool` argument, that will tell it whether the input vectors should be centralized around their average or not.

### Describe alternatives you've considered.

Implement this myself:

```python
def nmoment(arr, n):
	return np.sum(arr**n)/len(arr)
```

**Comment by doronbehar** [comment]
Haven't tested this yet, but it seems a fix wouldn't be that hard:

```patch
diff --git i/scipy/stats/_mstats_basic.py w/scipy/stats/_mstats_basic.py
index 145323c08..d25a6da5d 100644
--- i/scipy/stats/_mstats_basic.py
+++ w/scipy/stats/_mstats_basic.py
@@ -2549,7 +2549,7 @@ def winsorize(a, limits=None, inclusive=(True, True), inplace=False,
                                    upinc, contains_nan, nan_policy)
 
 
-def moment(a, moment=1, axis=0):
+def moment(a, moment=1, centralized=True, axis=0):
     """
     Calculates the nth moment about the mean for a sample.
 
@@ -2559,13 +2559,15 @@ def moment(a, moment=1, axis=0):
        data
     moment : int, optional
        order of central moment that is returned
+    centralized : bool, optional
+       If True, then the moments are computed centralized. Default is True.
     axis : int or None, optional
        Axis along which the central moment is computed. Default is 0.
        If None, compute over the whole array `a`.
 
     Returns
     -------
-    n-th central moment : ndarray or float
+    n-th (central) moment : ndarray or float
        The appropriate moment along the given axis or over all values if axis
        is None. The denominator for the moment calculation is the number of
        observations, no degrees of freedom correction is done.
@@ -2590,7 +2592,10 @@ def moment(a, moment=1, axis=0):
 
     # for array_like moment input, return a value for each.
     if not np.isscalar(moment):
-        mean = a.mean(axis, keepdims=True)
+        if centralized:
+            mean = a.mean(axis, keepdims=True)
+        else:
+            mean = 0
         mmnt = [_moment(a, i, axis, mean=mean) for i in moment]
         return ma.array(mmnt)
     else:
diff --git i/scipy/stats/_stats_py.py w/scipy/stats/_stats_py.py
index e3e5f2bff..00d8c9f6f 100644
--- i/scipy/stats/_stats_py.py
+++ w/scipy/stats/_stats_py.py
@@ -1046,14 +1046,14 @@ def moment(a, moment=1, axis=0, nan_policy='propagate'):
 
     Notes
     -----
-    The k-th central moment of a data sample is:
+    The k-th moment of a data sample is:
 
     .. math::
 
-        m_k = \frac{1}{n} \sum_{i = 1}^n (x_i - \bar{x})^k
+        m_k = \frac{1}{n} \sum_{i = 1}^n (x_i)^k
 
-    Where n is the number of samples and x-bar is the mean. This function uses
-    exponentiation by squares [1]_ for efficiency.
+    Where n is the number of samples. This function uses exponentiation by
+    squares [1]_ for efficiency.
 
     Note that, if `a` is an empty array (``a.size == 0``), array `moment` with
     one element (`moment.size == 1`) is treated the same as scalar `moment`
```

**Comment by vmpyr** [comment]
Hi, can I take up this issue if no one's working on it. I might need some help since this would be my first contribution to scipy.

**Comment by mdhaber** [comment]
May I suggest something simpler for a first contribution? For example, https://github.com/scipy/scipy/issues/17683 would involve writing unit tests for existing functions, which would be just one part of what you'd need to do for this issue. Also, can you find other example like the one reported in https://github.com/scipy/scipy/issues/17999 in which a stats function documentation refers to numbers that aren't produced by the code? Then, you could make an adjustment to the documentation, which is another component of what you'd need to do for this issue. Once you have some experience with those things, tackling a more complex issue like this would be easier.

**Comment by doronbehar** [comment]
@mdhaber if I'd go and file a PR with the patch I pasted above, as a solution to this issue, do you think a separate unit test is needed to solve the functionality added here?

**Comment by mdhaber** [comment]
Unit tests and documentation are needed for all new features. This is why I suggested starting with an issue that requires tackling just one of these components before something that requires implementation, documentation, and unit tests.

**Comment by mdhaber** [comment]
I took a closer look. The suggested patch would remove the mention of "central" from the documentation. We wouldn't want to do that, since the default behavior must remain unchanged.

Instead of a boolean "centralized", why not a float `center`? Then the user can pass the mean if they already have it or 0 if they want the non-central moment. Then the only change to the documentation would be to redefine the x-bar symbol as the desired center, which is the mean by default.

Either way, an API change like this requires an email to the [mailing list](https://svn.scipy.org/scipylib/mailing-lists.html). Please suggest the proposed change there.

**Comment by doronbehar** [comment]
Link for reference: https://mail.python.org/archives/list/scipy-dev@python.org/thread/FGVXUAA5Q2326LSZHXHLDE6I2MTTFFVO/

**Comment by tupui** [comment]
Sounds good to me to add a float to define the mean. As for naming `center` seems ok. Alternative, `mode`?

**Comment by doronbehar** [comment]
`mode` is too ambiguous IMO, `None` / float `mean` sounds best to me in the meantime, but we can also use the same `None` / float logic but for an argument named `center`.

**Comment by mdhaber** [comment]
I suggested `center` because `mean` suggests that the user should pass the mean as the argument. But the point of adding the parameter is to allow the user to take moments about a point *other* than the mean.

**Comment by doronbehar** [comment]
Thanks for the suggestion, here's a draft PR: https://github.com/scipy/scipy/pull/18152
