### ISSUE TITLE
BUG: Asymptotic computation of ksone.sf has intermediate overflow

### ISSUE THREAD

**Issue by aherbert** [scipy/scipy#17775]
### Describe your issue.

The asymptotic approximation for the one-sided one-sample Kolmogorov-Smirnov distribution is:
```
p ~ e^(-(6nx+1)^2 / 18n)
```
The code that computes this is `scipy/special/cephes/kolmogorov.c` using:
```c
/* p ~ e^(-(6nx+1)^2 / 18n) */
double logp = -pow(6*n*x+1.0, 2)/18.0/n;
sf = exp(logp);
cdf = 1 - sf;
```
When integer `n` is very large the term`6*n` overflows. This can be fixed using `6.0*n`. Here is the output from the original and the fixed computation:
```
1073741824 1.0E-6 :        0.9997616412882125 :        0.9978541552573539
1073741824 1.0E-5 :        0.9764236615944953 :        0.8067390416113425
1073741824 1.0E-4 :       0.09199043083077693 :     4.715937751790102E-10
1073741824 2.0E-4 :      7.160631249855586E-5 :      4.94686617627386E-38
1073741824 3.0E-4 :     4.716566585411689E-10 :    1.1542138829781214E-84
1073741824 5.0E-4 :    1.2398618639225049E-26 :    6.914816492890092E-234
1073741824  0.001 :   2.3626353537306987E-104 :                       0.0
```

Since we are modifying this computation we should also change to using expm1 for the CDF:
```c
/* p ~ e^(-(6nx+1)^2 / 18n) */
double logp = -pow(6*n*x+1.0, 2)/18.0/n;
sf = exp(logp);
cdf = -expm1(logp);
```

### Reproducing Code Example

```python
from scipy.stats.distributions import ksone
ksone.sf(5e-4, 1073741824)
```

### Error message

```shell
NA
```

### SciPy/NumPy/Python version information

1.9.3 1.23.5 sys.version_info(major=3, minor=9, micro=15, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @aherbert, thank you for reporting. I am not familiar with C things, but plugging this into mpmath I can get the 6.914816492890092E-234.
```
import mpmath
x, n = 5e-4, 1073741824
logp = -mpmath.power(6.0*n*x+1.0, 2)/18.0/n
mpmath.exp(logp)
# mpf('6.914816492890092e-234')
```

Do you want to make a PR?

**Comment by aherbert** [comment]
The issue is that `n` must be a 32-bit integer. This is the case is the c code.

If you use regular python or any other code where `n` will be expanded to 64-bit precision if required by multiplication then the computation is correct.

I can raise a PR by a simple edit on GH. As a new contributor is there any special labelling of the PR I should use?

**Comment by aherbert** [comment]
OK. I will look into where to add the appropriate test and make a PR.

**Comment by aherbert** [comment]
Verified locally using:
```
python dev.py test -t scipy.stats.tests.test_continuous_basic::test_gh17775_regression
python dev.py test -t scipy.stats.tests.test_continuous_basic
```
Tests for very small p-values use equality with a ULP limit chosen to pass. This could be reduced if the  expected result is evaluated entirely in double precision (16 digits). Using 50 digits has an advantage in the precision of the argument passed to the exp function.
