### ISSUE TITLE
BUG: optimization does not stop when callback returns True

### ISSUE THREAD

**Issue by jstmn** [scipy/scipy#17779]
### Describe your issue.

Hi, 

I've noticed that the optimization function `scipy.optimize.minimize` does not stop when the provided callback returns True.

This is different behavior vs. what the docs describe [here](https://docs.scipy.org/doc/scipy-1.10.0/reference/generated/scipy.optimize.minimize.html#:~:text=If%20callback%20returns%20True%20the%20algorithm%20execution%20is%20terminated): "If callback returns True the algorithm execution is terminated"

### Reproducing Code Example

```python
import scipy
import numpy as np

def fn(x, *args) -> float:
    loss = np.power(x, 2).mean()
    return loss

def callback(x):
    max_value = x.max()
    print(f"max value={max_value}")
    if max_value < 50:
        print(" --> max_value is less than 50, returning True")
        return True

x0 = 51*np.ones(5)
opt_result = scipy.optimize.minimize(fn, x0, callback=callback, method="bfgs")
```

### Error message

```shell
# Output:
max value=41.51459963944587
 --> max_value is less than 50, returning True
max value=20.165154723747435
 --> max_value is less than 50, returning True
max value=-1.660312227258487e-05
 --> max_value is less than 50, returning True

# Expected output:
max value=41.51459963944587
 --> max_value is less than 50, returning True
```

### SciPy/NumPy/Python version information

`1.9.3 1.24.1 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)`

**Comment by mdhaber** [comment]
The documentation intends to state that when `minimize` is used with `method='trust-constr'` and callback returns `True`, optimization will halt. For other methods, it has no effect.
![image](https://user-images.githubusercontent.com/6570539/212268309-eb7b7ccf-9a3c-4396-92c1-f5150cb5eff7.png)

In 1.11.0, most optimizers will support a new callback interface that allows the callback function to raise a `StopIteration` exception to gracefully stop early.
![image](https://user-images.githubusercontent.com/6570539/212268550-0c9d6f57-bc4b-48bd-9712-fc1fdeb7ac9d.png)

**Comment by jstmn** [comment]
Ah, I misread that paragraph. Thanks for clarifying.
