### ISSUE TITLE
BUG: Segfault in scipy.sparse.csgraph.shortest_path() with v1.10.0

### ISSUE THREAD

**Issue by ct-ms** [scipy/scipy#17782]
### Describe your issue.

Hello! Since last week’s upgrade from scipy 1.9.3 to 1.10.0, we have encountered a reproducible segmentation fault on running `scipy.sparse.csgraph.shortest_path()` with a particular weighted adjacency matrix and two `method` parameters. The matrix is attached. The problem has been observed with Python 3.9.15 on both macOS 12.6.2/arm64 and Debian 11.6/x86\_64.
[test_case.zip] DELETED

### Reproducing Code Example

```python
import scipy.sparse

mat = scipy.sparse.load_npz("test_case.npz")

# these crash
scipy.sparse.csgraph.shortest_path(mat)
scipy.sparse.csgraph.shortest_path(mat, method="D")
scipy.sparse.csgraph.shortest_path(mat, method="J")

# these don't
scipy.sparse.csgraph.shortest_path(mat, method="FW")
scipy.sparse.csgraph.shortest_path(mat, method="BF")
```

### Error message

```shell
segmentation fault
```

### SciPy/NumPy/Python version information

1.10.0 1.24.1 sys.version_info(major=3, minor=8, micro=15, releaselevel='final', serial=0)

**Comment by tupui** [comment]
Hi @ct-ms thank you for reporting. Please post the matrix in plain text. I will delete the zip for security reasons.

**Comment by ct-ms** [comment]
Got it! Here is a textual representation which can be loaded with `scipy.io.mmread()`: [test_case.txt](https://github.com/scipy/scipy/files/10410853/test_case.txt)

**Comment by tupui** [comment]
Thank you, I can reproduce. I will let sparse residents take over.

**Comment by JensWehner** [comment]
Hello, same team as @ct-ms. We encountered another symptom. For this matrix the algorithm does not seem to terminate, while scipy 1.9 it finishes near instantly.

Read with `scipy.io.mmread()`

[not_terminating.txt](https://github.com/scipy/scipy/files/10412900/not_terminating.txt)

**Comment by Kai-Striega** [comment]
I've tried both the examples and can reproduce both on my system (Ubuntu22.04, Python3.10). I think this has to do with the changes in [gh-16696](https://github.com/scipy/scipy/pull/16696). Maybe @windows-server-2003 has further ideas?

I'd like to look further into this. I haven't done much sparse stuff before, it might take a while for me to get going.

**Comment by windows-server-2003** [comment]
Sorry for this regression. I am looking into it.

**Comment by JensWehner** [comment]
Thanks a lot.

**Comment by windows-server-2003** [comment]
I spotted the bug and opened a PR for a fix. Thank you for reporting the issue.
