### ISSUE TITLE
BUG: stats.pearsonr one-sided hypothesis yields incorrect p-value for negative correlations

### ISSUE THREAD

**Issue by kernfel** [scipy/scipy#17795]
### Describe your issue.

Running scipy.stats.pearsonr with negatively correlated data while -- ostensibly -- testing for negative correlation with `alternative='less'` returns a large p-value (1), whereas testing for `alternative='greater'` returns a small p-value (0), contrary to expectations.

This has recently also been reported in https://stackoverflow.com/questions/74954418/scipy-pearsonr-p-value-confusion-when-using-the-alternative-hypothesis-as-less-t

Positively correlated data report p-values as expected.

### Reproducing Code Example

```python
x = np.arange(10)
y = -x
test_greater = scipy.stats.pearsonr(x, y, alternative='greater')
test_less = scipy.stats.pearsonr(x, y, alternative='less')
print(test_greater.pvalue, test_less.pvalue)
```

### Error message

```shell
# expected output: 1.0 0.0
# actual output: 0.0 1.0
```

### SciPy/NumPy/Python version information

1.10.0 1.22.3 sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
Thanks for reporting. At first glance it looked like the alternatives were reversed, but actually we get the same p-values when `y = x`. This will be fixed in 1.10.1.
