### ISSUE TITLE
BUG:  macos_arm64 meson unable to detect compiler type on Ventura.

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#17796]
### Describe your issue.

I'm trying to run the test suite. I'm on macOS Ventura 13.0.1 (arm64) with Xcode . It looks like meson (1.0.0) can't cope at the moment with the  OS version.
Please see https://gist.github.com/andyfaff/fac456a9a17962ddabf13435ca1c6d4b for the full build log.

@eli-schwartz @rgommers 

```
$ clang --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

### Reproducing Code Example

```python
conda create -n test python
conda activate test
python -m pip install pybind11 pythran doit click rich_click pydevtool cython numpy ninja meson
python dev.py test
```

### Error message

```shell
The Meson build system
Version: 1.0.0
Source dir: /Users/andrew/Documents/Andy/programming/scipy
Build dir: /Users/andrew/Documents/Andy/programming/scipy/build
Build type: native build
Project name: SciPy
Project version: 1.11.0.dev0
C compiler for the host machine: cc (clang 14.0.0 "Apple clang version 14.0.0 (clang-1400.0.29.202)")
C linker for the host machine: cc ld64 820.1
C++ compiler for the host machine: c++ (clang 14.0.0 "Apple clang version 14.0.0 (clang-1400.0.29.202)")
C++ linker for the host machine: c++ ld64 820.1
Host machine cpu family: aarch64
Host machine cpu: aarch64
Compiler for C supports arguments -Wno-unused-but-set-variable: YES 
Compiler for C supports arguments -Wno-unused-function: YES 
Compiler for C supports arguments -Wno-conversion: YES 
Compiler for C supports arguments -Wno-misleading-indentation: YES 
Compiler for C supports arguments -Wno-incompatible-pointer-types: YES 
Library m found: YES

meson.build:63:0: ERROR: Unable to detect GNU compiler type:
Compiler stdout:
#define __DBL_MIN_EXP__ (-1021)
#define __LDBL_MANT_DIG__ 53
#define __UINT_LEAST16_MAX__ 0xffff
...
... (etc - more defines)

-----
Compiler stderr:
<built-in>: error: unknown value ‘13.0.0’ of ‘-mmacosx-version-min’

-----
```

### SciPy/NumPy/Python version information

n/a

**Comment by andyfaff** [comment]
`clang test.c -mmacosx-version-min=13.0.0` works on my machine with:
```test.c
int main(void) { return 0; }
```

**Comment by rgommers** [comment]
I've had this issue as well (xref https://github.com/conda-forge/gfortran_impl_osx-64-feedstock/issues/60). You need to upgrade your conda `compilers` package as well as the related `clang` and `llvm` packages you have. The latter is a bit annoying, it's not automatic. But the latest version of all those packages will fix things.

**Comment by rgommers** [comment]
Ah wait, you're trying to do this with the Apple compilers. That's very strange. I haven't tried that yet.

**Comment by andyfaff** [comment]
There you go, I missed that in the log file. It turns out that the 12.1 compiler (Monterey) from https://github.com/fxcoudert/gfortran-for-macOS/releases was producing the issues. When I updated to 12.2 (Ventura) the problem went away.

**Comment by andyfaff** [comment]
thanks @rgommers
