### ISSUE TITLE
BUG: `stats.ttest_ind_from_stats` doesn't check whether standard deviations are nonnegative

### ISSUE THREAD

**Issue by goxberry** [scipy/scipy#17819]
### Describe your issue.

As far as I can tell, there's no check in `stats.ttest_ind_from_stats` as to whether its standard deviation arguments are nonnegative, and no indication in the design contract of `stats.ttest_ind_from_stats` as to whether clients are responsible for such a check.

### Reproducing Code Example

```python
scipy.stats.ttest_ind_from_stats(mean1=10, std1=-5, nobs1=50, mean2=25, std2=-3, nobs2=60, equal_var=False)
```

### Error message

```shell
Ttest_indResult(statistic=-18.605210188381267, pvalue=3.1587179651930366e-30)
```

### SciPy/NumPy/Python version information

1.9.3

**Comment by karthikkurella** [comment]
[https://github.com/scipy/scipy/blob/dde50595862a4f9cede24b5d1c86935c30f1f88a/scipy/stats/_stats_py.py#L6340](ttest_ind_from_stats) internal calling method to check for non-negative standard deviations.

**Comment by goxberry** [comment]
@karthikkurella Clicking on that link takes me to https://github.com/scipy/scipy/issues/ttest_ind_from_stats.

**Comment by karthikkurella** [comment]
@goxberry I have added line of the code that needs to be modified for the check on non-negative standards. Issue still persists.

**Comment by goxberry** [comment]
That function does not have enough information to make that check -- its arguments are the mean of sample 1, the mean of sample 2, the denominator of the t-statistic, the degrees of freedom for the test, and the test alternative, which is of type `Literal["less", "greater", "two-sided"]`.

You might mean https://github.com/scipy/scipy/blob/dde50595862a4f9cede24b5d1c86935c30f1f88a/scipy/stats/_stats_py.py#L6490.

**Comment by goxberry** [comment]
The issue is still present in SciPy 1.10.0, and in main, at least as of 5 minutes ago: https://github.com/scipy/scipy/blob/91a0ff8f5c7f37eb206372ae1ad35401601ad590/scipy/stats/_stats_py.py#L7097-L7100

One option could be to change a line like

```python
std1 = np.asarray(std1)
```
in the body of `ttest_ind_from_stats` to
```python
std1 = np.asarray(std1)
std1 = np.where(std1 >= 0, std1, numpy.nan)
```
which is a change I'd be happy to submit, along with the same sort of change for the `std2`. Another option would be to document in the docstring that validating the input parameters is the caller's responsibility. A third option would be to do nothing.

**Comment by mdhaber** [comment]
To help me suggest how to proceed: how did you get a negative value for the standard deviation? 

This is a very low-level function, so unless a check is likely to protect users against a legitimate mistake, I'd rather document that if the standard deviation is negative, the result will be the same as if it were positive.

**Comment by goxberry** [comment]
I did not. I was writing a wrapper around `stats.ttest_ind_from_stats` that would return a p-value of 1 in the case where `mean1 == mean2` and `std1 == std2 == 0` to handle a corner case in data processing for my application. I decided that since `std1` and `std2` are user inputs, I should probably check to see what happens if either one of them were negative.

**Comment by goxberry** [comment]
I'm happy to submit a change, whatever maintainers decide. Also happy to leave this alone, if that's the decision.

**Comment by mdhaber** [comment]
OK. Since this is more of a building block than a complete test function, I would suggest a doc-only change. If you submit a PR explaining what happens with negative standard deviations, I can review. I'll leave this open for at least a week to make sure there is time for others to express their opinions, though.

**Comment by mdhaber** [comment]
@goxberry would you like to submit that PR?

**Comment by goxberry** [comment]
@mdhaber I'm still interested in doing so. I took a first stab at it last weekend, but found that the instructions for new contributors, at least with a non-`conda` setup on an aarch64 Linux machine running Python 3.9.2, required some modifications. I'll see if I can dig into it more this weekend, but I may end up submitting more than one PR to update those instructions if they still don't work for me.

**Comment by mdhaber** [comment]
Thanks @goxberry!

**Comment by goxberry** [comment]
@mdhaber I've submitted a documentation PR in #17939, as requested.
