### ISSUE TITLE
DOC: improve documentation for distance_transform_{cdt,edt}

### ISSUE THREAD

**Issue by j-bowhay** [scipy/scipy#17815]
While `distance_transform_bf` give the convention for foreground and background in the documentation
https://github.com/scipy/scipy/blob/dde50595862a4f9cede24b5d1c86935c30f1f88a/scipy/ndimage/_morphology.py#L1874-L1880

both `distance_transform_{cdt,edt}` don't. It would be worth documenting this as it is the opposite way around to MATLAB and appears to have surprised more than just me:
https://stackoverflow.com/questions/44770396/how-does-the-scipy-distance-transform-edt-function-work

Also `distance_transform_bf` has a much better explanation for what the optionally returned indices are so could be nice to transfer that over too.

**Comment by harivamsi9** [comment]
Hey, Can I take up this issue?

**Comment by j-bowhay** [comment]
Go for it @harivamsi9
