### ISSUE TITLE
DOC: UnivariateSpline does not have any documentation or a reference.

### ISSUE THREAD

**Issue by jjgsherwood** [scipy/scipy#17828]
### Describe your issue.

UnivariateSpline interpolation does not have any explanation on how it works only what the different parameters do. It also does not have a reference to any source where this is explained. The source code starts with the following:

"""
fitpack --- curve and surface fitting with splines
fitpack is based on a collection of Fortran routines DIERCKX
by P. Dierckx (see http://www.netlib.org/dierckx/) transformed
to double routines by Pearu Peterson.
"""

Therefore, I believe it would be correct and helpful to also place a citation to his work in the documentation. Also, when reading the source code of UnivariateSpline nothing is revering to fitpack or explaining that explanation of the source code and the source code itself can be found in  DIERCKX by P. Dierckx.  Therefore changing the documentation of UnivariateSpline would really help to find/understand how it works.

### Reproducing Code Example

```python
None
```

### Error message

```shell
None
```

### SciPy/NumPy/Python version information

1.10.0

**Comment by ev-br** [comment]
UnivariateSpline and `splrep` use the same algorithm, and the latter has citations to the original papers and the Dierckx's book: 
https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.splrep.html

If you feel like adding these reference to the  `*UnivariateSpline`  docstrings, a PR is welcome.

**Comment by ev-br** [comment]
Fixed by https://github.com/scipy/scipy/pull/18101, closing.
