### ISSUE TITLE
DOC: doc build is broken

### ISSUE THREAD

**Issue by j-bowhay** [scipy/scipy#17840]
See:
https://app.circleci.com/pipelines/github/scipy/scipy/17890/workflows/c9620cd5-3df9-4d95-bfd1-f4ee20b9719e/jobs/61287
https://app.circleci.com/pipelines/github/scipy/scipy/17892/workflows/5ba17356-9d1e-420e-87e6-57ec90212c62/jobs/61291

Also building locally yields the same error

**Comment by j-bowhay** [comment]
Looks like this might be a numpy issue as pinning an old version fixes the problem

**Comment by melissawm** [comment]
I think this may be due to numpy/numpy#23063

**Comment by tupui** [comment]
Yes this is due to NumPy moving some things to the C API. Sebastian knows about it and is working on it.

**Comment by j-bowhay** [comment]
This looks to be fixed now
