### ISSUE TITLE
DOC: unable to read BSpline object property

### ISSUE THREAD

**Issue by parsarahimi** [scipy/scipy#17858]
### Issue with current documentation:

BSpline object possesses coefficients array c, tick array t, and an integer k. After creating a BSpline object, youre not able to access these variables through for example: print(myBspline.c)
Neither does the @property tck work for this purpose.
I am using make_lsq_spline for making the BSpline, so I do not know the values of c and would like to know these values.

**Comment by parsarahimi** [comment]
It seems that
`print(myBspline.tck)`
doesn't work as opposed to:
`cs,ts,k = myBspline.tck
print(cs,ts,k)`
which does work, odd.

**Comment by ev-br** [comment]
```
In [10]: from scipy.interpolate import make_interp_spline

In [11]: x, y = [1, 2, 3, 4, 5, 6], [1, 4, 9, 16, 25, 26]

In [12]: spl= make_interp_spline(x, y)

In [13]: spl.c
Out[13]: 
array([ 1.        ,  2.18518519,  6.62962963, 17.37037037, 30.81481481,
       26.        ])

In [14]: spl.t
Out[14]: array([1., 1., 1., 1., 3., 4., 6., 6., 6., 6.])

In [16]: spl.k
Out[16]: 3

In [17]: spl.tck
Out[17]: 
(array([1., 1., 1., 1., 3., 4., 6., 6., 6., 6.]),
 array([ 1.        ,  2.18518519,  6.62962963, 17.37037037, 30.81481481,
        26.        ]),
```

**Comment by ev-br** [comment]
All seems to work as expected (at least with `make_interp_spline`, but I'be very surprised if `make_lsq_spline` is any different). Hard to tell what's going on with your example without a reproducible example, please add one here if you're still having difficulties.
