### ISSUE TITLE
DOC: Incorrect link to ARPACK

### ISSUE THREAD

**Issue by ThijsDrost** [scipy/scipy#17860]
### Issue with current documentation:

The link http://www.caam.rice.edu/software/ARPACK/ which is present in the documentation for scipy.sparse.linalg.eigs and scipy.sparse.linalg.eigsh, and at https://scipy.github.io/devdocs/tutorial/arpack.html leads to a 404 error on the Rice University website

**Comment by j-bowhay** [comment]
Indeed, thanks. Would you be interested in fixing it?

**Comment by Ajitofy** [comment]
Hi, Can you please explain which link we have to provide instead of " http://www.caam.rice.edu/software/ARPACK/"?

**Comment by Saksham093** [comment]
Hello, @j-bowhay ... I researched, and also thanks to @ThijsDrost for the statement. Ya, that's true ARPACK is now moved to Github : [https://github.com/opencollab/arpack-ng](https://github.com/opencollab/arpack-ng), but in the documentation needs to update, So, I would like to work on this and want to change some paths like ...

![](https://user-images.githubusercontent.com/69385787/215335850-613521b8-af2f-496a-8bb8-55686237540e.png)

**Comment by Papaganti-sravya** [comment]
Hi I would like to work on this issue. @Saksham093 are the links provided resembles the correct link to be updated.

**Comment by Saksham093** [comment]
Hey @Papaganti-sravya ... You can work, I think their is not active on this issue. 
Do some research and fix it.

**Comment by Papaganti-sravya** [comment]
Hi, @Saksham093 Glad for the oppurtunity provided  to work on this issue, Do I have any person to talk on this issue for further assistance, share my thoughts and get this fixed.

**Comment by Papaganti-sravya** [comment]
Hi @Saksham093  I have done some resech and got these links, please check and let me know if any of these links can be useful.
http://rsusu1.rnd.runnet.ru/libraries/ARPACK/node6.html

https://people.sc.fsu.edu/~jburkardt/f_src/arpack/arpack.html

**Comment by Papaganti-sravya** [comment]
Hi @Saksham093 If you feel like these links 
http://rsusu1.rnd.runnet.ru/libraries/ARPACK/node6.html
https://people.sc.fsu.edu/~jburkardt/f_src/arpack/arpack.html 
works as a replacement of https://cmor.rice.edu/software/ARPACK/  for reference let me know I will update on the main page. 

Thank you
Sravya

**Comment by ThijsDrost** [comment]
@Papaganti-sravya as far as I know scipy uses (the still maintained) arpack-ng, which is located at: https://github.com/opencollab/arpack-ng

**Comment by Papaganti-sravya** [comment]
Hi @ThijsDrost this is my first contribution can you guide me and let me know if i just have to update https://github.com/opencollab/arpack-ng on the referece part of https://scipy.github.io/devdocs/tutorial/arpack.html
Thank you

**Comment by ThijsDrost** [comment]
@Papaganti-sravya I neither know how to do it

**Comment by Papaganti-sravya** [comment]
Hi @Saksham093 Can you provide me some ideas on how to solve this issue, that would be much appreciated.

Thank you 
Sravya

**Comment by Papaganti-sravya** [comment]
Hi @melissawm Thank you so much for the information It is really helpful. The link for the reference ([reference](http://www.caam.rice.edu/software/ARPACK/).) is not working do you have any reference link to update in all threee documents.

**Comment by melissawm** [comment]
I believe the reference is now https://github.com/opencollab/arpack-ng

However, it does seem odd that going through the Rice website, there are still references to this page (maybe there is some internal error?) I have reached out via email to the Rice University folks to see if they can clarify this. In the meantime, adding the link to the arpack-ng github repository is a nice addition. Thanks!

**Comment by melissawm** [comment]
Here's the official response:

> Dear Melissa,
> 
> Unfortunately, we are no longer the official link to ARPACK since Professor Sorensen retired several years ago.
> 
> As far as know, due to stalled upstream development, ARPAСK has been forked into ARPACK-NG as a form of a collaborative effort of the various groups that rely on ARPACK.
> https://github.com/opencollab/arpack-ng
> 
> Regards,
> CMOR Staff

**Comment by harshvardhan2707** [comment]
Is this issue still active or has it been resolved?

**Comment by j-bowhay** [comment]
Resolved by #18173
