### ISSUE TITLE
DOC: Should `Result Classes` be its own top level section?

### ISSUE THREAD

**Issue by Kai-Striega** [scipy/scipy#17866]
### Issue with current documentation:

Currently the SciPy documentation for version 1.10 shows [Result Classes](https://docs.scipy.org/doc/scipy/reference/stats._result_classes.html) as its own, top level, section. I don't believe this is correct, as they are only results for stats. Should this come under scipy.stats.result_classes?

### Idea or request for content:

Move results classes to scipy.stats.result_classes

### Additional context (e.g. screenshots, GIFs)

 ![SciPy Result Classes in wrong position](https://user-images.githubusercontent.com/30074037/214999095-cbf05cbd-628f-4aff-8dfc-6e22c507f3b9.png)

**Comment by mdhaber** [comment]
It has been like that for a few versions but when I fight with Sphinx, Sphinx usually wins.

Ideally, it would not show up anywhere. These are classes that we want to be linked from the corresponding functions; e.g. in `scipy.stats.contingency.relative_risk`:

![image](https://user-images.githubusercontent.com/6570539/214999971-3a237651-944b-46b8-8137-fa3738fdba12.png)

But these are not importable or intended to be used.

```python3
from scipy.stats import RelativeRiskResult  # should raise ImportError
# ImportError: cannot import name 'FitResult' from 'scipy.stats' (C:\Users\matth\scipy\scipy\stats\__init__.py)
```

So ideally, they would not appear anywhere except via links from the functions that use them.

**Comment by Kai-Striega** [comment]
Ok. Thanks for the explanation. I'm going to leave this open and, if someone comes along who wants to take a crack at it, great.

**Comment by mdhaber** [comment]
Well, if you can't completely fix it, would you move to the very bottom of the stats page? That way it is at least less visible.

**Comment by Kai-Striega** [comment]
I can try, although I have very little experience with Sphinx so I'm not sure how far I'll get.

**Comment by tupui** [comment]
> You could include a note that the classes are not importable and they are documented only because instances are returned by other functions.

This is a very important point to make as not common in other libraries. Normally all specific exceptions or other return objects are also part of the public API. So as we go another way it needs to be documented.

About the toc, there are other elements I would remove from there as well, we have too many things in the sidebar ATM.

**Comment by Kai-Striega** [comment]
@tupui I've tried to remove it but haven't gotten very far. I've been able to delete the file and build the documentation which leads to the following warnings:

```
checking consistency... /home/kai/Projects/SciPy/kai/scipy/doc/source/reference/generated/scipy.stats._result_classes.BinomTestResult.rst: WARNING: document isn't included in any toctree
/home/kai/Projects/SciPy/kai/scipy/doc/source/reference/generated/scipy.stats._result_classes.FitResult.rst: WARNING: document isn't included in any toctree
/home/kai/Projects/SciPy/kai/scipy/doc/source/reference/generated/scipy.stats._result_classes.OddsRatioResult.rst: WARNING: document isn't included in any toctree
/home/kai/Projects/SciPy/kai/scipy/doc/source/reference/generated/scipy.stats._result_classes.PearsonRResult.rst: WARNING: document isn't included in any toctree
/home/kai/Projects/SciPy/kai/scipy/doc/source/reference/generated/scipy.stats._result_classes.RelativeRiskResult.rst: WARNING: document isn't included in any toctree
/home/kai/Projects/SciPy/kai/scipy/doc/source/reference/generated/scipy.stats._result_classes.TtestResult.rst: WARNING: document isn't included in any toctree
/home/kai/Projects/SciPy/kai/scipy/doc/source/reference/generated/scipy.stats._result_classes.TukeyHSDResult.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
/home/kai/Projects/SciPy/kai/scipy/doc/source/reference/stats.rst:6: WARNING: toctree contains reference to nonexisting document 'reference/stats._result_classes'
/home/kai/Projects/SciPy/kai/scipy/doc/source/reference/stats.rst:6: WARNING: toctree contains reference to nonexisting document 'reference/stats._result_classes'
/home/kai/Projects/SciPy/kai/scipy/doc/source/reference/stats.rst:6: WARNING: toctree contains reference to nonexisting document 'reference/stats._result_classes'                     
/home/kai/Projects/SciPy/kai/scipy/doc/source/reference/stats.rst:6: WARNING: toctree contains reference to nonexisting document 'reference/stats._result_classes'
/home/kai/Projects/SciPy/kai/scipy/doc/source/reference/stats.rst:6: WARNING: toctree contains reference to nonexisting document 'reference/stats._result_classes'                     
/home/kai/Projects/SciPy/kai/scipy/doc/source/reference/stats.rst:6: WARNING: toctree contains reference to nonexisting document 'reference/stats._result_classes'
```

Any idea of where to go from here?

**Comment by tupui** [comment]
Thanks Kai. So yeah every document needs to be present in a toctree. What you need to do is to have a hidden tree. Basically on an existing tree you can add `:hidden:`. And it will not be included, but still there for Sphinx.

**Comment by Kai-Striega** [comment]
It looks like it's already hidden but being ignored:

https://github.com/scipy/scipy/blob/main/doc/source/reference/stats.rst

**Comment by tupui** [comment]
ok so you are saying you removed the file `stats._result_classes.rst` and you got the warnings?

**Comment by tupui** [comment]
So I found the culprit. It's due to the interaction of `includehidden=True` we have in `doc/source/_templates/sidebar-nav-bs.html` and the fact that in `doc/source/reference/stats.rst` we have on the same level the hidden sections.

First option is doing `includehidden=False` would mean that we need to rewrite the toctree in the `index.rst` (and other places maybe?).

So I propose instead to remove the hidden toctree and reference all that in the init of stats as Matt suggested. I will make a PR and ping you.

We might want to do similar things for other submodules. (e.g. linalg)
