### ISSUE TITLE
DOC: Setting correct number of knots in splprep for task=-1

### ISSUE THREAD

**Issue by JulianWgs** [scipy/scipy#17893]
### Describe your issue.

I can't get splprep for task=-1 to work.

No matter what number I use for the number of knots I always get this error message. I also tried setting k to different values, but that didn't help either.

The [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.splprep.html) says that t must be an integer, but I've seen examples using an array:

```
t: int, optional
    The knots needed for task=-1.
```

I haven't looked at the code yet.

### Reproducing Code Example

```python
import numpy as np
from scipy import interpolate
s = np.linspace(0, 1, 10000)

tck, u = interpolate.splprep([np.sin(s), np.cos(s)], task=-1, t=100,)
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/scipy/interpolate/_fitpack_py.py", line 153, in splprep
    res = _impl.splprep(x, w, u, ub, ue, k, task, s, t, full_output, nest, per,
  File "/usr/local/lib/python3.9/site-packages/scipy/interpolate/_fitpack_impl.py", line 260, in splprep
    raise TypeError('There must be at least 2*k+2 knots for task=-1')
TypeError: There must be at least 2*k+2 knots for task=-1
```

### SciPy/NumPy/Python version information

1.10.0 1.24.1 sys.version_info(major=3, minor=9, micro=16, releaselevel='final', serial=0)

**Comment by ev-br** [comment]
You need to supply the knots themselves, not just their number, I'm afraid.

**Comment by RishabhSpark** [comment]
Hi! I'd like to work on this, but I'm new to open source. Can someone please guide me through this? :D
