### ISSUE TITLE
ENH: Stirling Numbers of the second Kind 

### ISSUE THREAD

**Issue by rlucas7** [scipy/scipy#17890]
### Is your feature request related to a problem? Please describe.

Hi, I'd like to propose an enhancement to SciPy. 
I've been doing some stuff with 
[Stirling numbers of the second kind](https://en.wikipedia.org/wiki/Stirling_numbers_of_the_second_kind)-these numbers are useful in many applications. 
These numbers count the number of ways to create `k` ***non-empty*** subsets from `n` items.

Some places where the numbers have applications:

1. [Moments of a Poisson distribution](https://en.wikipedia.org/wiki/Stirling_numbers_of_the_second_kind#Moments_of_the_Poisson_distribution)

```math
\mathbb{E}(X^n) = \sum_{k=0}^{n} {n \brace k} \lambda^k
```

2. moments of fixed points of a random permutation `X`
```math
\mathbb{E}(X^n) = \sum_{k=0}^n {n \brace k} 
```

3 Irwin-Hall distribution moments 
```math
Z = \sum_{i=1}^n U_k 
```
where each `U_k` is uniform on `(0,1)`.
Then `Z` has an Irwin-Hall distribution and the `j-m`th moment is
```math
\frac{{j \brace m}}{j \choose{m}} =  \mathbb{E}\left(\sum_{i=1}^n U_k\right)^{j-m}.
```
This is the effectively the Equation (unnumbered) at the top of page 640 of 
[Probabilistic Stirling Numbers of the Second Kind and Applications
Jose Adell, journal of theoretical probability 2022](https://link.springer.com/content/pdf/10.1007/s10959-020-01050-9.pdf)

Note 1: The sum of the `U_k` is an Irwin-Hall random variable so rearranging the equation in the paper gives the equation above. 
Note 2: This equation (for Irwin-Hall moments) is not described on [the wikipedia page for the Irwin-Hall distribution](https://en.wikipedia.org/wiki/Irwin%E2%80%93Hall_distribution).

4. Counting the number of possible partitions of `n` data points into `k` non-empty sets
This is what K-means optimizes greedily-not necessarily globally optimal.
To verify global optimality for a given data set of `n` data points we'd need to check all possible
```math
{n \brace k}
```
non-empty partitions of the data.
 
5. The probability for a collision in the Birthday problem and [generalizations for multiple types of people](https://en.wikipedia.org/wiki/Birthday_problem#Generalization_to_multiple_types_of_people)

6. The exact calculation of the false positive rate in a Bloom filter, e.g. Theorem 1 of [this paper](https://cglab.ca/~morin/publications/ds/bloom-submitted.pdf)
Which was [published here](https://www.sciencedirect.com/science/article/abs/pii/S0020019008001579)

Note: This [person's blog notes](https://jamesmccaffrey.wordpress.com/2020/07/30/computing-a-stirling-number-of-the-second-kind-from-scratch-using-python/
) that they'd expect this to be in either SciPy or Numpy, verbatim quote:

""" I’m sure there is certainly a Stirling function in one of the Python libraries (probably SciPy or NumPy) """

Although we have an implementation of Stirling's approximation to the factorial function this is Not the same-although it is the same person named Stirling.

6. [scicomp.stackexchange question](https://scicomp.stackexchange.com/questions/1571/an-efficient-way-to-numerically-compute-stirling-numbers-of-the-second-kind)

There are a couple of different ways to calculate the Stirling numbers of the second kind and it is non-trivial to get a bug free -and somewhat fast-implementation. 

I'd like to propose we implement these numbers somewhere in SciPy. I've started a working implementation in pure python in [this gist](https://gist.github.com/rlucas7/3adf2ad4923e2a8402e465537763e4fe) which contains code that will generate the `nth` row of the Stirling numbers triangle and a method to calculate an individual value. Both seem to have uses and neither implementation (dynamic programming/inclusion-exlcusion) outperforms the other.

The gist also contains some `unittest` tests for both functions and some `timeit` timings from my laptop.

Questions: 
(i) is this something that we'd be willing to merge into SciPy? 

(ii) Any feedback on function names, and signatures? (maybe we want something slightly different)

(iii) Where would we put these (if the answer to (i) is Yes)? (my guess is they'd fit in special along w/`comb` but open to other ideas)

I'll wait for input and clarification in particular on (i) before putting more work into this effort. 

### Describe the solution you'd like.

Something approximately like the code in the gist I linked above. 

### Describe alternatives you've considered.

I evaluated a couple of alternatives (you can see them in the gist link). It seems that the Dynamic Program approach is faster than inclusion-exclusion for calculating an entire row but if we want only a single entry from a row when `n` is somewhat large then the Inclusion-Exclusion result is faster. So I'd propose a row function using Dynamic Programming and a function for calculating a single entry using Inclusion-Exclusion approach. 

### Additional context (e.g. screenshots, GIFs)

![snsk_fig_1](https://user-images.githubusercontent.com/5400493/215644998-53520f93-d1b1-4627-80e0-b00eed1b7314.png)

Plot of runtimes from the code in the gist to compare the row calculation using both Dynamic Program and Inclusion Exclusion approaches.

**Comment by rgommers** [comment]
> (i) is this something that we'd be willing to merge into SciPy?

It seems like a good fit to me. 

> (ii) Any feedback on function names, and signatures? (maybe we want something slightly different)

Something more descriptive than `snsk` would be good - maybe simply `stirling_second`? Regarding the `n, k` parameters, those should probably accept arrays and integers rather than only integers.

This seems like a good candidate to write in Cython/Pythran/C, given that it's mostly a single for-loop and the timing above seem like the pure Python version is not that fast.

> (iii) Where would we put these (if the answer to (i) is Yes)? (my guess is they'd fit in special along w/`comb` but open to other ideas)

`scipy.special` sounds good to me.

**Comment by josef-pkt** [comment]
+1

I also just needed them for copulas
plus 1st kind, plus polylog (fortunately we only need polylog for negative integer order)
https://github.com/statsmodels/statsmodels/blob/main/statsmodels/distributions/copula/_special.py

**Comment by steppi** [comment]
+1. I'd also support adding Stirling Numbers of the First Kind. These give the number of permutations of n elements that contain k disjoint cycles.

**Comment by rlucas7** [comment]
@rgommers 

> > (ii) Any feedback on function names, and signatures? (maybe we want something slightly different)
> 
> Something more descriptive than `snsk` would be good - maybe simply `stirling_second`? 


Based on @josef-pkt comments and a search for R's equivalent, I'll instead propose
`stirling2()` for the function name, that way it aligns w/josef's code in statsmodels and [what R does](https://search.r-project.org/CRAN/refmans/copula/html/Stirling.html)


> This seems like a good candidate to write in Cython/Pythran/C, given that it's mostly a single for-loop and the timing 
> above seem like the pure Python version is not that fast.

I'll look into which language makes most sense-I am unlikely to do this is Pythran.

>Regarding the `n, k` parameters, those should probably accept arrays and integers rather than only integers.

I had thought a little about that approach before, for Inclusion-Exclusion on a single value it's the same approach just vectorized so I'd think the ufunc mechanism in special should take care of that for us-unless you had something else in mind?

For the dynamic programming approach (on rows) it's a bit more complicated. 
The fast way to  proceed is to sort the array of `n_i` values ascending and output for each `n_i` instance. 
This modifies the implementation slightly b/c we'd want a warm start array, e.g. for `n = [2,4,9]` you'd want to first calculate the row for `n_0=2` store that array, then use this value to iterate to `n_1=4`, storing that value and then using the fourth row as a warm start row to proceed from `n_1=4` row to `n_2=9` row. 
Longer lists of ints would proceed similarly.

This also makes it slightly more complicated in terms of how to determine a threshold for when to do the inclusion-exclusion vs the dynamic-program approach.

Here is an example of what I was thinking for the `array-like` input for the rows function. 

```
from typing import List, Union


def stirling2_rows(rns: Union[int, List[int]]) -> List[List[int]]:
    """ given `ns` a sorted list of non-negative integers return a list where 
        each row is the nth row of the Stirling triangle

        ns: List[int] a sorted list of non-negative integers

        returns: List[List[int]] a list of lists of integers. 
        Each inner list corresponds to the `n`th row of the 2nd Stirling triangle where `n = rns[i]`

        TODO: write some doctest
    """
    if not isinstance(rns, list):
        rns = [rns]
    if any([n < 0 for n in rns]):
        raise ValueError(f"ns must all be non-negative, entered {rns}")
    answer = []
    n0, row = [1], [0,1]
    prev = 1
    for val in rns:
        if val > 1:
            num_iters = val - prev 
            row.extend([0]*(num_iters+1))
            while num_iters > 0:
                row = [0] + [row[j+1]*(j+1) + row[j] for j in range(val+1)]
                num_iters -= 1
            else:
                prev = val
                answer.append(row[:len(row)-1].copy())
        elif val == 1:
            answer.append(row.copy())
        else: # val == 0 case
            answer.append(n0.copy())
    return answer

### some tests

import unittest


class test_stirling2_rows(unittest.TestCase):
    def setUp(self):
        self.table = [
            [1],
            [0,1],
            [0,1,1],
            [0,1,3,1],
            [0,1,7,6,1],
            [0,1,15,25,10,1],
            [0,1,31,90,65,15,1],
            [0,1,63,301,350,140,21,1],
            [0,1,127,966,1701,1050,266,28,1],
            [0,1,255,3025,7770,6951,2646,462,36,1],
            [0,1,511,9330,34105,42525,22827,5880,750,45,1],
        ]

    def test_Table_cases(self):
        results = stirling2_rows([0,1,2,3,4,5,6,7,8,9,10])
        self.assertEqual(results, self.table)

    def test_noncontiguous_rows(self):
        non_contiguous_row_indices = [0,1,5,9]
        self.assertEqual(stirling2_rows(non_contiguous_row_indices), [self.table[i] for i in non_contiguous_row_indices])

    def test_raises_if_at_least_1_negative_entry(self):
        self.assertRaises(ValueError, stirling2_rows, *([0, -1],))

    def test_valid_single_integer(self):
        self.assertEqual(stirling2_rows(0), [[1]])
        self.assertEqual(stirling2_rows(4), [[0, 1, 7, 6, 1]])

    def test_raises_if_negative_single_integer(self):
        self.assertRaises(ValueError, stirling2_rows, *(-1,))

### seems ok for the row case...

if __name__ == '__main__':
    unittest.main()



```

**Comment by rlucas7** [comment]
> +1
> 
> I'd also support adding Stirling numbers of the first kind (number of permutations of n elements that contain k disjoint cycles).

Thanks for your comments. I'd prefer to focus on a single implementation. The 1st kind have their own set of design considerations e.g. signed vs unsigned etc. 
I know that Josef would like them for statsmodels, perhaps I'll do a follow on PR-or if someone else designs that one that'd be good too. 

There are a couple other types of numbers of this nature Eulerian, etc that could be considered but trying to keep the proposed changes scoped here.

**Comment by rgommers** [comment]
> Last time I can recall that I put C into `special` was [here](https://github.com/scipy/scipy/commit/fdf4cd83e0a80a083da3790453a12862b3460793) I can see how we'd put the inclusion-exclusion method into the ceph setup but have we changed anything about that build setup since 2019 or should I follow that approach?

Not sure when we changed what, but probably still the same. There are docs: http://scipy.github.io/devdocs/dev/api-dev/special_ufuncs.html.

And yes, writing it as a ufunc sounds great and will address the array input question.

**Comment by steppi** [comment]
> Thanks for your comments. I'd prefer to focus on a single implementation. The 1st kind have their own set of design considerations e.g. signed vs unsigned etc.
> I know that Josef would like them for statsmodels, perhaps I'll do a follow on PR-or if someone else designs that one that'd be good too.

I agree those should have their own PR. One PR per combinatorial number ufunc seems reasonable.

**Comment by rlucas7** [comment]
@josef-pkt I'm was trying to find where the Stirling numbers are going to be used in the Copula's to get a better understanding for the use case, [I couldn't find](https://github.com/statsmodels/statsmodels/search?q=stirling2) it is there a paper link or a module in statsmodels you can link to here? (it's possible the repo search hassn't reindexed yet)

**Comment by josef-pkt** [comment]
@rlucas7 

Those are not used yet in copula. I parked them there for a future PR.
Usage is in generator derivatives of 2 archimedean copulas (Gumbel and Frank) and in pdf if dimension is > 2 (my last PR added explicit expression for dim 3 and 4.)
https://github.com/statsmodels/statsmodels/issues/8631
https://github.com/statsmodels/statsmodels/issues/8631#issuecomment-1402289693

**Comment by josef-pkt** [comment]
statsmodels has now the PR to add the missing copula pdf using sterling and polylog, WIP https://github.com/statsmodels/statsmodels/pull/8649

**Comment by rlucas7** [comment]
thanks @josef-pkt I'm curious do you have an idea of the range of (n, k) values for Stirling2 ? I'm looking at implementing with C in scipy.special as a ufunc and it looks like Strirling2 overflows at n = 17 (for 32 bit ints) and n=27 (for 64 bit ints). 

```
from typing import List

def snsk_row(n: int) -> List[int]:
    if n < 0:
        raise ValueError(f"n must be non-negative, entered {n}")
    if n == 0:
        return [1]
    snsk_nm1 = [0,1] + [0]*(n-1)
    # do the dynamic program forward: given n-1 length k-array, build the n length k array
    for i in range(1, n):
        #print(f"begining array {i} with values {snsk_nm1}")
        snsk_nm1 = [snsk_nm1[j]*j + snsk_nm1[j-1] for j in range(n+1)]
        #print(f"completed array {i+1} with values {snsk_nm1}")
    return snsk_nm1

notFound32 = True
notFound64 = True
n = 1
while n:
    row = snsk_row(n)
    if notFound32 and any([r > 4294967295 for r in row]):
        print(f"n = {n} is first instance of element > 32 bit int can hold, row = {row}")
        notFound32 = False
    if notFound64 and any([r > 18446744073709551616 for r in row]):
        print(f"n = {n} is first instance of element > 32 bit int can hold, row = {row}")
        notFound64 = False
    if not notFound64 and not notFound32:
        break
    n += 1
```

`n = 17` seems to be the limit for the row where 32 bit overflow occurs, a slice [5:10] on the row shows all overflow
`n = 27` seems to be the limit for the row where 64 bit overflow occurs, a slice [8:14] on the row shows all overflow

**Comment by josef-pkt** [comment]
The contributor that asked for extension of archimedean to higher dimension needs at least 20.
AFAIR, the authors of the articles and R package mentioned over 100 (or 300? for some)

Looking at the formula for Gumbel pdf, the sum of terms with sterling2 go up to the dimension (number of components) in the multivariate copula.

My guess is that this will be like `comb` where I almost never use the "exact" option with integers, I use mainly the float version or `gamma` , `gammaln` directly. 

I have no experience with larger dimensional copulas and almost all articles for applied work that I read, use at most 4 or 5 components in the copulas (maybe more for elliptical copulas).
For higher dimensional cases, other copula construction like vines, hierarchical copulas and similar are more popular because they are more flexible in correlation across components than one parameter copulas. (statsmodels does not have those yet, but there is an other python package for those.)

**Comment by rlucas7** [comment]
>My guess is that this will be like comb where I almost never use the "exact" option with integers, I use mainly the float >version or gamma , gammaln directly.

There is this: https://en.wikipedia.org/wiki/Stirling_numbers_of_the_second_kind#Asymptotic_approximation
but I haven't looked at that closely. Maybe I misunderstand what you mean, I don't think using an approximation will help with the overflow issue. A log version of that approximation (or something like it) would work across a larger range but it seems like a different function (e.g. `approx_log_stirling2`) or something along those lines.

**Comment by josef-pkt** [comment]
I didn't mean an asymptotic approximation. I meant using float64 dtype instead of int.
Float dtype will not overflow even though we don't have an exact integer value as results.
(by analogy to comb, factorial/gamma)
