### ISSUE TITLE
ENH: Add softplus implementation

### ISSUE THREAD

**Issue by tommyod** [scipy/scipy#17905]
### Is your feature request related to a problem? Please describe.

It might be nice to have a numerically stable [softplus](https://en.wikipedia.org/wiki/Rectifier_(neural_networks)#Softplus) implementation, ie `np.log1p(np.exp(x))`

### Describe the solution you'd like.

Something based on one of these stackoverflow answers:

- https://cs.stackexchange.com/questions/110798/numerically-stable-log1pexp-calculation
- https://stackoverflow.com/questions/44230635/avoid-overflow-with-softplus-function-in-python

### Describe alternatives you've considered.

I could use `logsumexp` with zeros in the first argument
```
>>> from scipy.special import logsumexp
>>> import numpy as np
>>> logsumexp(np.vstack((np.zeros(10), 10**np.arange(10))), axis=0)
```
but it's a bit cumbersome. Not sure if it's enough of a pain to warrant this enhancement proposal though.

**Comment by tommyod** [comment]
Yes it is. Corrected it above!

I'm not sure if it's a good fit for scipy either. It came up in a different context to me. It's tied to some other functions implemented:
- Its derivative is [scipy.special.expit](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.expit.html#scipy.special.expit)
- As mentioned above it's equal to `logsumexp([0, x])` if `x` is a scalar.

I'm sure it has other uses, but when I searched github for usage I mostly found ML/AI. That might be due to the popularity of implementing NNs from scratch on github. I think it's a quite natural penalty function in optimization if one desires a smooth penalty in some optimization problems.

**Comment by tupui** [comment]
I am going to say +1. You might want to get more opinions by asking the mailing list (and this would be required before inclusion if we wanted to move forward.)

**Comment by tupui** [comment]
@aadya940 thank you for the proposal. If I recall correctly, this still needs to go through the mailing list. Correct me if I am wrong @tommyod. Either way, @tommyod would have the primmer as he opened the issue. We do not want folks to compete 😃 We have more than enough issues/PRs to work on so we don't have to do that.

**Comment by tommyod** [comment]
I wanted to air the suggestion, but unfortunately I don't have capacity to do the work right now.

Therefore I won't follow this up through the mailing list, so if @aadya940 wants to do that, then go ahead :) Thanks!

**Comment by tupui** [comment]
Thank you @tommyod. @aadya940 would you mind sending an email to the mailing list motivating this change? This is the first step for inclusion in SciPy.

**Comment by aadya940** [comment]
> 

Done

**Comment by tupui** [comment]
Thank you @aadya940, I've replied. Posting here as well: StackOverflow is not compatible with our license and cannot be used/read. Good thing is that the maths is simple enough so we can easily implement it ourselves from scratch.

**Comment by aadya940** [comment]
Hi @tupui , It would be good if you can help me with the implementation considering I don't know much about the scipy architecture. From what I understand is I can define the softplus function in scipy.special.utils._basic and then add it to __all__ , later write a parametrized test checking the function in scipy.special.tests. What am I missing?

**Comment by tupui** [comment]
Before doing anything, we need to wait a bit for the mailing list. No reply for a week or so would mean OK.

To start with, you can have a look at our contributing documentation: https://scipy.github.io/devdocs/dev/contributor/contributor_toc.html

We also have monthly newcomers meeting and a Slack server. You will find all info here: https://scipy.org/community/

**Comment by tupui** [comment]
Hum this resource links to a R package which is GPL-2… I would prefer if we would stay away from the grey area of "n-lines of code should be fine”.

Cheers,
Pamphile

**Comment by lorentzenchr** [comment]
Scikit-learn is BSD and I implemented it based on the pdf, not the R code!

**Comment by WarrenWeckesser** [comment]
FYI: A simple option that works now is to use `numpy.logaddexp` with 0 as the first argument.  For example,

```
In [507]: x = 2.5

In [508]: np.log1p(np.exp(x))  # A naive implementation
Out[508]: 2.5788897342925496

In [509]: np.logaddexp(0, x)
Out[509]: 2.5788897342925496

In [510]: x = 20

In [511]: np.log1p(np.exp(x))
Out[511]: 20.000000002061153

In [512]: np.logaddexp(0, x)
Out[512]: 20.000000002061153

In [513]: x = 1000  # With x this large, `exp(x)` in the naive implementation overflows

In [514]: np.log1p(np.exp(x))
<ipython-input-514-1647fa2e1120>:1: RuntimeWarning: overflow encountered in exp
  np.log1p(np.exp(x))
Out[514]: inf

In [515]: np.logaddexp(0, x)
Out[515]: 1000.0

``` 

`np.logaddexp` is a ufunc, so it is vectorized:

```
In [516]: a = [-500, -100, -10, 0, 1e-6, 2, 10, 25]

In [517]: np.logaddexp(0, a)
Out[517]: 
array([7.12457641e-218, 3.72007598e-044, 4.53988992e-005, 6.93147181e-001,
       6.93147681e-001, 2.12692801e+000, 1.00000454e+001, 2.50000000e+001])
```

-----

> I could use `logsumexp` with zeros in the first argument

In theory, that also works, since `scipy.special.logsumexp` is a generalization of `np.logaddexp`. `np.logaddexp` is simpler for this use, and as a ufunc, probably faster.  Also, while exploring this, I found that `logsumexp` has a bug where it appears to lose precision unnecessarily:

```
In [523]: from scipy.special import logsumexp

In [524]: logsumexp([0, -40.0])
Out[524]: 0.0
```
The correct result of `logsumexp([0, -40.0])` is `4.248354255291589e-18`:
```
In [525]: np.logaddexp(0, -40)
Out[525]: 4.248354255291589e-18
```

**Comment by aadya940** [comment]
@tupui Can I start working on this feature?

**Comment by WarrenWeckesser** [comment]
The scikit-learn implementation of `log1pexp` is a `cdef` Cython function:
https://github.com/scikit-learn/scikit-learn/blob/6ca4970ca28840b61229b8016b60382e3a930915/sklearn/_loss/_loss.pyx.tp#L250-L266
It is not exposed as a function callable from Python.

If we want to add this to SciPy, a simple implementation based on my [comment above](https://github.com/scipy/scipy/issues/17905#issuecomment-1507247170) is a one-line wrapper of `np.logaddexp`.  As a wrapper, it would not be a ufunc, but with `**kwargs` passed through to `np.logaddexp`, we can preserve much of the ufunc goodness:

```
def log1pexp(x, **kwargs):
    return np.logaddexp(0.0, x, **kwargs)
```

E.g.
```
In [31]: def log1pexp(x, **kwargs):
    ...:     return np.logaddexp(0.0, x, **kwargs)
    ...: 

In [32]: log1pexp(2.5)
Out[32]: 2.5788897342925496

In [33]: log1pexp(1000)
Out[33]: 1000.0

In [34]: a = [-500, -100, -10, 0, 1e-6, 2, 10, 25]

In [35]: log1pexp(a)
Out[35]: 
array([7.12457641e-218, 3.72007598e-044, 4.53988992e-005, 6.93147181e-001,
       6.93147681e-001, 2.12692801e+000, 1.00000454e+001, 2.50000000e+001])

In [36]: out = np.empty_like(a)

In [37]: log1pexp(a, out=out)
Out[37]: 
array([7.12457641e-218, 3.72007598e-044, 4.53988992e-005, 6.93147181e-001,
       6.93147681e-001, 2.12692801e+000, 1.00000454e+001, 2.50000000e+001])

In [38]: out
Out[38]: 
array([7.12457641e-218, 3.72007598e-044, 4.53988992e-005, 6.93147181e-001,
       6.93147681e-001, 2.12692801e+000, 1.00000454e+001, 2.50000000e+001])
```

-----

We could implement it as a ufunc (as @rkern suggested in the mailing list thread), but that would not be a good first issue for someone new to SciPy development.  It might be a good issue for an existing contributor who wants to dive deeper into how ufuncs are implemented in `scipy.special`.

**Comment by NeilGirdhar** [comment]
Also, the inverse function is really useful when using softplus to map between the real line and the positive real line, and back:
```python
def inverse_softplus(y):
    xp = get_namespace(y)
    return xp.where(y > 80.0,  # noqa: PLR2004
                    y,
                    xp.log(xp.expm1(y)))
```
