### ISSUE TITLE
A problem about 'scipy.io.matlab.mio5_utils'

### ISSUE THREAD

**Issue by Transtars** [scipy/scipy#17902]
Running under Windows environment appears errors

Traceback (most recent call last):
  File "F:/Learning/TrajectoryClustering-master/trajectory_clustering.py", line 9, in <module>
    from clustering import Clustering
  File "F:\Learning\TrajectoryClustering-master\clustering.py", line 12, in <module>
    from scipy.io.matlab.mio5_utils import scipy
ImportError: cannot import name 'scipy' from 'scipy.io.matlab.mio5_utils' (E:\python\lib\site-packages\scipy\io\matlab\mio5_utils.cp38-win32.pyd)

how can i solve the problem?

**Comment by tupui** [comment]
Hi @Transtars thank you for reporting. Your import is wrong. You cannot import SciPy from within a submodule of SciPy.

Closing this. Issues are reserved for bugs and features. For support please use other forums such as StackOverflow.
