### ISSUE TITLE
Unexpected behaviour of pearsonr pvalue for one sided tests

### ISSUE THREAD

**Issue by jillxoreilly** [scipy/scipy#17913]
Hi, I am running stats.pearsonr on samples from a population with zero correlation and checking how often I get a type 1 error (it's a teaching exercise!). I find that if I use alternative='two-sided' I get a sig result (pvalue<0.05) 5% of the time as expected, but if use alternative='less' I never get pvalue<0.05, I get pvalue<0.05 10% of the time.

```python3
# Code to generate the population with zero correlation - don't worry about understanding this bit

rho=0 # the desired correlation

# desired mean and sd of variables in columns 0 and 1
m0=50
m1=50
s0=8
s1=5

c=[[1,rho],[rho,1]] # the correlation matrix that we want in the simulated dataset

# make two columns of numbers with the desired correlation (mean of each column is zero, sd is 1)
tmp=np.random.multivariate_normal([0,0],c,size=25000)

# scale the variables to get correct mean and sd
tmp[:,0]=(tmp[:,0]*s0)+m0
tmp[:,1]=(tmp[:,1]*s1)+m1
pop_rZero=pandas.DataFrame(tmp,columns=['Maths','French'])

# check probability of type 1 error
nReps=10000
sampleSize=50
p = np.empty(nReps)

for i in range(nReps):
    sample = pop_rZero.sample(n=sampleSize)
    p[i] = stats.pearsonr(sample['Maths'], sample['French']).pvalue
# How many of our 10000 samples had p<0.05?
np.mean(p<0.05)
```

**Comment by mdhaber** [comment]
One problem with `pearonsr` `alternative` parameter, gh-17795, has been fixed by gh-17797. Could you try the latest [nightly wheels](https://pypi.anaconda.org/scipy-wheels-nightly/simple/scipy/) and see if that resolves the problem?

**Comment by mdhaber** [comment]
```
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt

rng = np.random.default_rng()

n_experiments = 10000
n_observations = 1000
x, y = rng.normal(size=(2, n_experiments, n_observations))
p = np.empty(n_experiments)
for i in range(n_experiments):
    p[i] = stats.pearsonr(x[i], y[i], alternative='less').pvalue
np.mean(p < 0.05) 
```
In 1.11.0.dev0+1400.6a0465b, the output is # 0.0524 and the p-values are uniform on [0, 1].

![image](https://user-images.githubusercontent.com/6570539/216456641-30ee6abb-082e-4a07-b8c3-1150116cda25.png)

In 1.10.0, the output is 0 and the p-values are uniform on [0.5, 1].

@tylerjereddy is there an estimate on 1.10.1 release date? There have been two reports about this, so I suspect there are many other unreported cases.

**Comment by tupui** [comment]
So we should close this right @mdhaber?

**Comment by mdhaber** [comment]
@jillxoreilly did https://github.com/scipy/scipy/issues/17913#issuecomment-1414092080 resolve this issue? Were you able to test the nightly wheels?

@tylerjereddy any plans for a 10.1.0?

**Comment by jillxoreilly** [comment]
Thanks, looks like it is a known problem and will be gone in the next release - will use two-tailed tests for my demos til then

**Comment by tylerjereddy** [comment]
For the release we wanted to address the two open issues from Debian and Fedora maintainers. I should check in to see if they are happy with current progress on those.
