### ISSUE TITLE
BUG: binom.stats with frequency of 0

### ISSUE THREAD

**Issue by sicotteh** [scipy/scipy#17923]
### Describe your issue.

binomial interval should be 0,0 when population frequency is 0.
e.g.

binom.interval(0.95,2000,0)
(1999.0, 0.0)

should give the same answer as with a tiny frequency.
binom.interval(0.95,2000,1e-6)

(0.0,0.0)

### Reproducing Code Example

```python
binom.interval(0.95,2000,0)
```

### Error message

```shell
No error message, this is a bug in functionality.
```

### SciPy/NumPy/Python version information

1.5.4 1.19.5 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)

**Comment by mdhaber** [comment]
Please upgrade your version of SciPy; it is a few years out of date and the implementation of `binom` has been replaced in the meantime. I cannot reproduce this behavior in main.

```python3
from scipy import stats
stats.binom.interval(0.95,2000,0)  # (0.0, 0.0)
```
