### ISSUE TITLE
BUG: meson `__config__` generation - truncated unicode characters

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#17934]
### Describe your issue.

The wheel builder CI entry has started failing for all the `win_amd64` entries. See https://github.com/scipy/scipy/actions/runs/4090921150
The issue comes when the wheel is tested. The issue is probably related to #17862. @ganesh-k13. When the fix is made remember to include `[wheel build]` in the commit message. This will ensure that the failure is exercised.

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
+ python -c 'import sys; import scipy; sys.exit(not scipy.test())'
  0
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-p68m4u3y\cp38-win_amd64\venv-test\lib\site-packages\scipy\__init__.py", line 141, in <module>
      from scipy.__config__ import show as show_config
    File "C:\Users\runneradmin\AppData\Local\Temp\cibw-run-p68m4u3y\cp38-win_amd64\venv-test\lib\site-packages\scipy\__config__.py", line 54
      "include directory": "C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-zh9c8rzi\overlay\Lib\site-packages\pythran"
                           ^
  SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
                                                             ✕ 56.74s
Error: Command bash D:\a\scipy\scipy/tools/wheels/cibw_test_command.sh D:\a\scipy\scipy failed with code 1. None
```

### SciPy/NumPy/Python version information

N/A

**Comment by ganesh-k13** [comment]
Ah ok, I think in `C:\Users`, the `\U` is treated as unicode. The fix will be to convert the strings into `r`(raw) strings. ref: https://stackoverflow.com/a/1347854/5671364

I'll raise a PR for this around noon IST. apologies for missing this.
