### ISSUE TITLE
DOC: guidance on setting dev.py build -j flag in documentation, particularly if build hangs machine repeatedly

### ISSUE THREAD

**Issue by goxberry** [scipy/scipy#17941]
### Is your feature request related to a problem? Please describe.

When the amount of RAM per Ninja build task drops below a certain threshold, say, somewhere between 1-2 GB RAM, based on experience, the build system will wedge a machine because there's not enough memory available for all the compilation jobs it spawns [^0].  For example, on an `aarch64` machine with 2 Cortex-A76 cores and 6 Cortex-A55 cores with 8 GB RAM, the `dev.py` script uses the default number of build jobs, which is `n_logical_cpus + 2`, or 10 jobs. This setting reliably wedges that machine.

While overriding this setting for a `python dev.py build` invocation is relatively straightforward, after diagnosing the cause, I'm not sure how many people would get that far. It's also unclear to me how one would override that setting when installing a locally-built development version of `scipy`. I was using `python3 -m pip install -v --no-build-isolation` in my copy of the project root, based on the instructions in [How to build SciPy with Meson](https://docs.scipy.org/doc/scipy/dev/contributor/meson.html#meson-frequently-asked-questions), and couldn't figure out how I'd pass a `-j` setting through `pip` and the `meson-python` build backend to `meson` and `ninja`. (I finally hardcoded a value of 2 in `dev.py` just to get past this wedging issue.)  

[^0]: See, for instance, Gentoo's advice on `make -j`. <https://wiki.gentoo.org/wiki/MAKEOPTS>

### Describe the solution you'd like.

I don't think there's a great solution to this problem.

One path forward could be documentation, with some sort of section like, "If building `scipy` crashes your machine, run `ninja --help` on the command line after activating your virtual environment. In the output, there should be a line that starts with `-j`, and towards the end of that line, you'll see the default number of `ninja` jobs on your system. Divide the number of gigabytes of RAM installed on your system, e.g., 16 GB, by this default number of jobs. If this ratio is less than 2 GB RAM per job, when you next attempt to build `scipy` from source using the `dev.py` script, run `python dev.py build -j N`, where `N` is the largest natural number such that you still have at least 2 GB of RAM per job."

I don't know if I simply missed a better way to install a locally built development version of SciPy into my SciPy development environment, or if I'm just totally ignorant of the appropriate flags, but if there's a way to expose a `-j N` type of option whatever contributors are supposed to do that resembles `pip install -v --no-build-isolation .`, I could see that option being helpful.

Another path forward could be to try to set some kind of default maximum number of jobs, although I could see that sort of topic potentially becoming contentious, based on previous experience working on [Spack](https://github.com/spack/spack). If I remember correctly, most source-based package managers set a default max number of jobs; for example, [Spack](https://github.com/spack/spack/blob/2516ed181ad05c34a4eb0948ca4bc6bd567a99ba/lib/spack/spack/build_environment.py#L561) defaults the max number of build jobs to `max(num_logical_cpus, 16)`, and [Nix](https://nixos.org/manual/nix/unstable/command-ref/conf-file.html#conf-max-jobs) uses a conservative default maximum of 1 job. I don't have any preference, and would also support leaving the build settings as they are.

### Describe alternatives you've considered.

Doing nothing, I think, is a viable alternative, though I wonder how many other people have run into this issue; a cursory search of the project issues (e.g., `build crash`, `build hang`, `build lock`, `build wedge`, `hang`, `ninja hang`) did not yield much, aside from https://github.com/scipy/scipy/issues/10234.

Suggesting users cross-compile for particularly memory-constrained systems could be another viable option, or suggesting minimum development requirements.

### Additional context (e.g. screenshots, GIFs)

I'm sort of loath to deliberately crash my Chromebook again, but if need be, I can do it again, and take a screenshot because it runs Linux on a container. I have not tried to look at `crosh top` for system memory usage, plus I'm not sure how it use of ZRAM would affect any sort of memory contention; in general, the performance data seems a bit opaque to me. I was able to build `scipy` successfully, though, with `python dev.py build -j 4` and `python dev.py build -j 2`.

I was using ChromeOS 109 with a stock Debian 11 container, and all SciPy development system dependencies installed.

**Comment by tupui** [comment]
I would be +1 to add some doc around setting correctly `j`. Gentoo's doc you linked seems like a good idea.

**Comment by melissawm** [comment]
@goxberry can we interest you in submitting a PR for this? :D

**Comment by goxberry** [comment]
@melissawm Yes, I'd be happy to submit a PR.

**Comment by rgommers** [comment]
The `dev.py` interface already has what's needed here (`build --parallel` or `build -j`), and that's documented (see `python dev.py build --help`).

I'd expect this to be an issue mostly for `pip install scipy` when building from source though. That is going to be very rare (that's why you can't find much about it), but if it happens it's painful. The correct invocation will be:
```
pip install scipy --config-settings=setup-args=-j4  # for using 4 cores
```
There's docs for how to use `--config-settings` in https://meson-python.readthedocs.io/en/latest/how-to-guides/config-settings.html#how-to-guides-config-settings.


> Another path forward could be to try to set some kind of default maximum number of jobs, although I could see that sort of topic potentially becoming contentious, based on previous experience working on [Spack](https://github.com/spack/spack). If I remember correctly, most source-based package managers set a default max number of jobs; for example, [Spack](https://github.com/spack/spack/blob/2516ed181ad05c34a4eb0948ca4bc6bd567a99ba/lib/spack/spack/build_environment.py#L561) defaults the max number of build jobs to `max(num_logical_cpus, 16)`, and [Nix](https://nixos.org/manual/nix/unstable/command-ref/conf-file.html#conf-max-jobs) uses a conservative default maximum of 1 job. I don't have any preference, and would also support leaving the build settings as they are.

Yeah, that's not a great idea. We need at least 8 parallel processes for somewhat reasonable performance (in my testing, 12 is about optimal), and that wouldn't have helped you on a machine with 8 GB.

**Comment by goxberry** [comment]
> The dev.py interface already has what's needed here (build --parallel or build -j), and that's documented (see python dev.py build --help).

It's not documented in the quickstart

![Screenshot 2023-02-12 19 45 22](https://user-images.githubusercontent.com/321479/218365952-e722caa9-2836-4353-be74-0a1648250cfa.png)

which was what I was following. I'm aware that those command-line options exist, having contributed to source-based package managers for over a decade, but that failure mode wasn't top of mind, particularly [already having had to modify the build instructions](https://github.com/scipy/scipy/pull/17937) to even get to the point where I could attempt a build.

> I'd expect this to be an issue mostly for pip install scipy when building from source though. That is going to be very rare (that's why you can't find much about it), but if it happens it's painful.

Again, as someone who never contributed to the project before last week, I looked at the documentation regarding rendering the project's Sphinx docs locally:

![Screenshot 2023-02-12 20 05 29](https://user-images.githubusercontent.com/321479/218368213-c449a0fa-fa28-47e1-aa1e-5ada9439d5d4.png)

These directions don't mention building the documentation via `python dev.py doc` -- they mention running `make html` in the same fashion as the default Sphinx project build setup. Running that command would fail unless I installed `scipy` from source -- so I built it from source using `pip`. This build also failed repeatedly, until I moved to a more powerful `amd64` machine.

Should I have looked at `python dev.py --help` a bit more closely? Probably, but I'm also not expecting to see conflicting information in the documentation. These conflicts create a serious barrier to entry for new contributors.

**Comment by tupui** [comment]
> Should I have looked at python dev.py --help a bit more closely? Probably, but I'm also not expecting to see conflicting information in the documentation. These conflicts create a serious barrier to entry for new contributors.

This is a valid remark @goxberry. We have been updating a few things on the architecture side and we still need to complete our overall of the documentation. Any help is appreciated and doc PR's are more than welcomed 😃

**Comment by rgommers** [comment]
> It's not documented in the quickstart

That quickstart guide should be quick, so this is certainly too detailed for it there. That guide should probably just mention that the `dev.py --help` and `dev.py <cmd> --help` (where `<cmd>` is `build`, `test`, `doc`, etc.) can be consulted for detailed options for each development task.

We have too many development docs already, and despite a ton of work on them they've never been fully up-to-date. So let's point at the source of truth rather than double-documenting this.

**Comment by tupui** [comment]
In #17987 I am doing some cleanup of install/setup instructions. After that I can create a single `dev.py` ressource and do some cleaning. e.g. I see we have some redundant description in `meson.rst` and `devpy_test.rst`

**Comment by rgommers** [comment]
gh-18451 should fix this for `dev.py`, and gh-18429 adds docs for `pip install` usage. Actually changing the behavior for `pip install` is more difficult, but I'm going to try.
