### ISSUE TITLE
Trying to install mplsoccer with pip within a Venv and get an error related to Scipy

### ISSUE THREAD

**Issue by resona8e** [scipy/scipy#17966]
I'm only posting here as I've done a deep dive on stackoverflow and have posted the issue on stackoverflow  to no avail.

pip install -U mplsoccer

`Collecting mplsoccer
  Using cached mplsoccer-1.1.10-py3-none-any.whl (67 kB)
Collecting numpy
  Using cached numpy-1.24.2-cp310-cp310-macosx_10_9_x86_64.whl (19.8 MB)
Collecting pillow
  Using cached Pillow-9.4.0-2-cp310-cp310-macosx_10_10_x86_64.whl (3.3 MB)
Collecting scipy
  Using cached scipy-1.10.0.tar.gz (42.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      The Meson build system
      Version: 1.0.0
      Source dir: /private/var/folders/hk/4ryb7f7d4ln3rh6dlm3khpcr0000gn/T/pip-install-m8528x6z/scipy_0b848504e1aa417b8fab2d86cb1cc279
      Build dir: /private/var/folders/hk/4ryb7f7d4ln3rh6dlm3khpcr0000gn/T/pip-install-m8528x6z/scipy_0b848504e1aa417b8fab2d86cb1cc279/.mesonpy-90lmtyda/build
      Build type: native build
      Project name: SciPy
      Project version: 1.10.0
      C compiler for the host machine: cc (clang 10.0.1 "Apple LLVM version 10.0.1 (clang-1001.0.46.4)")
      C linker for the host machine: cc ld64 450.3
      C++ compiler for the host machine: c++ (clang 10.0.1 "Apple LLVM version 10.0.1 (clang-1001.0.46.4)")
      C++ linker for the host machine: c++ ld64 450.3
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: NO
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES
      Fortran compiler for the host machine: gfortran (gcc 12.2.0 "GNU Fortran (Homebrew GCC 12.2.0) 12.2.0")
      Fortran linker for the host machine: gfortran ld64 530
      Compiler for Fortran supports arguments -Wno-conversion: YES
      Checking if "-Wl,--version-script" : links: NO
      Program cython found: YES (/private/var/folders/hk/4ryb7f7d4ln3rh6dlm3khpcr0000gn/T/pip-build-env-wdhemktq/overlay/bin/cython)
      Program python found: YES (/Users/nathaniel/Desktop/futbolSci2/soccerSci2/bin/python3)
      Did not find pkg-config by name 'pkg-config'
      Found Pkg-config: NO
      Program pythran found: YES (/private/var/folders/hk/4ryb7f7d4ln3rh6dlm3khpcr0000gn/T/pip-build-env-wdhemktq/overlay/bin/pythran)
      Run-time dependency threads found: YES
      Library npymath found: YES
      Library npyrandom found: YES
      Found CMake: /usr/local/bin/cmake (3.25.2)
      Run-time dependency openblas found: NO (tried pkgconfig, framework and cmake)
      Run-time dependency openblas found: NO (tried framework and cmake)
      
      ../../scipy/meson.build:134:0: ERROR: Dependency lookup for OpenBLAS with method 'pkgconfig' failed: Pkg-config binary for machine 1 not found. Giving up.`

**Comment by tupui** [comment]
Hi @resona8e thank you for reporting. I am going to close this as we are well aware of build complications when wheels are not available. Nothing more to track here.
