### ISSUE TITLE
BUG: nbinom.cdf is very slow

### ISSUE THREAD

**Issue by lesshaste** [scipy/scipy#17973]
### Describe your issue.

I noticed that scipy.stats.nbinom.cdf() is much slower than the most naive pure python implementation.  I was wondering why that was.

### Reproducing Code Example

```python
In [13]: %timeit nbinom.cdf(16, 26, 0.5)
110 µs ± 2.68 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


This  is 110 µs for a simple call.

Now consider the following naive pure Python implementation.


def nbinom_pmf(k, n, p):
        return comb(k+n-1, n-1)* p**n * (1-p)**k

def nbinom_cdf(k, n, p):
        return sum(nbinom_pmf(x, n, p) for x in range(k+1))


We now get:

%timeit nbinom_cdf(16, 26, 0.5)
10.5 µs ± 64.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```

This is about 10 times faster than the scipy call.

### Error message

```shell
This not an error report.
```

### SciPy/NumPy/Python version information

blas_mkl_info:   NOT AVAILABLE blis_info:   NOT AVAILABLE openblas_info:     libraries = ['openblas', 'openblas']     library_dirs = ['/usr/local/lib']     language = c     define_macros = [('HAVE_CBLAS', None)]     runtime_library_dirs = ['/usr/local/lib'] blas_opt_info:     libraries = ['openblas', 'openblas']     library_dirs = ['/usr/local/lib']     language = c     define_macros = [('HAVE_CBLAS', None)]     runtime_library_dirs = ['/usr/local/lib'] lapack_mkl_info:   NOT AVAILABLE openblas_lapack_info:     libraries = ['openblas', 'openblas']     library_dirs = ['/usr/local/lib']     language = c     define_macros = [('HAVE_CBLAS', None)]     runtime_library_dirs = ['/usr/local/lib'] lapack_opt_info:     libraries = ['openblas', 'openblas']     library_dirs = ['/usr/local/lib']     language = c     define_macros = [('HAVE_CBLAS', None)]     runtime_library_dirs = ['/usr/local/lib'] Supported SIMD extensions in this NumPy install:     baseline = SSE,SSE2,SSE3     found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2     not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL

**Comment by mdhaber** [comment]
This is because the distribution infrastructure is extremely slow at slow at checking for NaNs, arguments outside the support, etc. If you use the `_cdf` method, which is private, all of that is bypassed, and the result is much faster.
```python3
from scipy.stats import nbinom
%timeit nbinom.cdf(16, 26, 0.5)  # 72.7 µs ± 634 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
%timeit nbinom._cdf(16, 26, 0.5)  # 1.97 µs ± 17.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```
The need for the distribution infrastructure to be more efficient and for all the exception case checks to be optional are both tracked in gh-15928.

**Comment by lesshaste** [comment]
I tested again and ._cdf is much faster but still slower than the naive python implementation for small parameter values. For example:

In [22]: %timeit nbinom_cdf(1, 26, 0.5)
978 ns ± 30.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [23]: %timeit nbinom._cdf(1, 26, 0.5)
3.08 µs ± 221 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


The difference is even more stark for ._pmf, e.g.

In [24]: %timeit nbinom_pmf(1, 26, 0.5)
282 ns ± 1.61 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [25]: %timeit nbinom._pmf(1, 26, 0.5)
2.03 µs ± 6.55 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

**Comment by mdhaber** [comment]
The same could be said of many SciPy/NumPy functions:

```python3
import math
%timeit math.sin(3.5)  77.2 ns ± 0.196 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

import numpy as np
%timeit np.sin(3.5)  # 516 ns ± 2.02 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```
They are optimized for array input so that they are fast when the computation would otherwise be slow.

```
x = np.linspace(0, np.pi, 10000)
%timeit np.sin(x)  # 39.9 µs ± 241 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

%timeit [math.sin(xi) for xi in x]  # 1.07 ms ± 5.07 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

But yes, there is some overhead, so pure Python may be faster in cases that take very little time.
