### ISSUE TITLE
BUG: ILP64 build issue on Python 3.11

### ISSUE THREAD

**Issue by tupui** [scipy/scipy#17970]
When trying to update the job `Main Windows Python311-64bit-full-ilp64` from Python 3.10 to 3.11 in #17959, it fails with:

```
scipy\_lib\_ccallback_c.c(198): fatal error C1083: Cannot open include file: 'longintrepr.h': No such file or directory
```

See for instance:

https://dev.azure.com/scipy-org/SciPy/_build/results?buildId=23197&view=logs&jobId=5798bea6-6f0e-53d8-f5d0-dee01455df3d&j=e9067a85-bfec-502c-be7f-b409b431f362&t=a32c8242-15a8-506e-c1c1-22ace30b9b75

From a quick search, it might be due to the fact that we have `PyLong_AsVoidPtr(long(...))` in the corresponding Cython.

**Comment by andyfaff** [comment]
I wonder if unpinning cython would help here. https://github.com/aio-libs/aiohttp/issues/6600

**Comment by tupui** [comment]
Indeed, I can try to put this back in the PR and update all Cython to 0.29.32

**Comment by rgommers** [comment]
The point of the pin in CI is to have at least one job that uses the oldest Cython version we claim to support. So if our requirement says `>=0.29.24` then we install `cython` in most jobs and `cython--0.29.24` in one job. 

Upgrading the minimum Cython version is fine in general.

**Comment by tupui** [comment]
Our requirement say 0.29.32, so in the PR I changed occurrences of 0.29.24 to 0.29.32

**Comment by tupui** [comment]
Just seeing it worked. So I linked this issue to be closed when the PR get merged.
