### ISSUE TITLE
DOC: Examples on integration page have slightly inaccurate results

### ISSUE THREAD

**Issue by squenson1** [scipy/scipy#18004]
### Issue with current documentation:

While testing scipy version 1.10.0, I ran the examples on the integration page (https://docs.scipy.org/doc/scipy/tutorial/integrate.html). I noticed a few discrepancies between the results I obtained and the content of the web page. You may like to update the documentation with the new values.

1. On the first example, I get:
(1.1178179380783253, 7.866317250224184e-09) instead of
(1.1178179380783249, 7.8663172481899801e-09) (current content of the doc)

and the value of abs() is different as well. I get:
1.0375700298936863e-11 instead of 
1.03761443881e-11 (current content of the doc)

2. On the second example, I get:
array([0.10969197, 0.05673949, 0.03013338, 0.01629537, 0.00893065, 0.00494538]) instead of
array([ 0.1097,  0.0567,  0.0301,  0.0163,  0.0089,  0.0049]) (current content of the doc)

array([0.10969197, 0.05673949, 0.03013338, 0.01629537, 0.00893065, 0.00494538]) instead of
array([ 0.1097,  0.0567,  0.0301,  0.0163,  0.0089,  0.0049]) (current content of the doc)

(0.33333333325010883, 2.8604069920115143e-09) instead of
(0.33333333324560266, 2.8548934485373678e-09) (current content of the doc)

0.3333333333333333 instead of
0.333333333333 (current content of the doc)

8.322448286079975e-11 instead of
8.77306560731e-11 (current content of the doc)

3. Under the section "General multiple integration ([dblquad])", I get:
(0.2500000000043577, 1.298303346936809e-08) instead of
(0.2500000000043577, 1.29830334693681e-08) (current content of the doc)

As area, I get:
(0.010416666666666668, 4.101620128472366e-16) instead of
(0.010416666666666668, 1.1564823173178715e-16) (current content of the doc)

As integrate.nquad(f, [[1, np.inf],[0, np.inf]]), I get:
(0.2000000000189363, 1.3682975855986131e-08) instead of
(0.20000000000002294, 1.2239614263187945e-08) (current content of the doc)

**Comment by tupui** [comment]
Thank you for reporting @squenson1. Nothing out of the ordinary here, it's just some numerical error. Besides any seeding, the platform and versions of the libraries which are used can all have an impact.

Closing this as there is not much to do and nothing we need to track more here.
