### ISSUE TITLE
DOC: PyPI SciPy logo still missing

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#18007]
Probably low priority, but looks like backporting gh-17984 wasn't enough for `1.10.1`:

https://pypi.org/project/scipy/1.10.1/

![image](https://user-images.githubusercontent.com/7903078/219979087-ab8c59ff-7eb1-4cfe-91e0-fd3b6310e852.png)

**Comment by tupui** [comment]
Ark ok I had a look at what scikit-learn is doing and they use a different URL as GH is blocking the request:

```
.. image:: https://raw.githubusercontent.com/scikit-learn/scikit-learn/main/doc/logos/scikit-learn-logo.png
  :target: https://scikit-learn.org/
```

Hence we need to have this:

```
.. image:: https://raw.githubusercontent.com/scipy/scipy/main/doc/source/_static/logo.svg
  :target: https://scipy.org
  :width: 110
  :height: 110
  :align: left 
```

**Comment by tupui** [comment]
Is there a simple way for you to re-upload?
