### ISSUE TITLE
DOC: Include parent object in sidebar links

### ISSUE THREAD

**Issue by scottshambaugh** [scipy/scipy#18017]
### Issue with current documentation:

Once you navigate down to the docs for methods of a class, there is no link that will bring you back to the top level object. For  example, in the page for [scipy.spatial.transform.Rotation.from_quat](https://scipy.github.io/devdocs/reference/generated/scipy.spatial.transform.Rotation.from_quat.html), there isn't a link that I can see to go back up to [scipy.spatial.transform.Rotation](https://scipy.github.io/devdocs/reference/generated/scipy.spatial.transform.Rotation.html). 

### Idea or request for content:

It'd be great to have the top level object as the first item in the sidebar list: 
![image](https://user-images.githubusercontent.com/14363975/220229792-80c9d07d-d4f9-4b71-8850-cc10f963cb50.png)

**Comment by tupui** [comment]
Thank you for reporting @scottshambaugh. We actually just changed the sidebar to remove all nesting. See the dev docs.

The difficulty is that dynamic nesting cannot be done in the sidebar (html size issue as we need the full nesting of everything and cannot filter out). It's something the they are thinking about on the theme side.

Having another button or UI element for that would also be an issue for the theme.

I will close for now as it a theme thing.
