### ISSUE TITLE
BUG: stats: Error from e.g. `stats.betabinom.stats(10, 2, 3, moments='k')`

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#18026]
When integers are given as the `a` and `b` parameters in a call of `stats.betabinom.stats(n, a, b, moments='k')`, the function raises an exception.

For example, 

```
In [1]: from scipy.stats import betabinom

In [2]: betabinom.stats(10, 2, 3, moments='k')
---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
Cell In [2], line 1
----> 1 betabinom.stats(10, 2, 3, moments='k')

File ~/repos/git/forks/scipy/build-install/lib/python3.10/site-packages/scipy/stats/_distn_infrastructure.py:1124, in rv_generic.stats(self, *args, **kwds)
   1121 scale, loc, goodargs = goodargs[-2], goodargs[-1], goodargs[:-2]
   1123 if self._stats_has_moments:
-> 1124     mu, mu2, g1, g2 = self._stats(*goodargs,
   1125                                   **{'moments': moments})
   1126 else:
   1127     mu, mu2, g1, g2 = self._stats(*goodargs)

File ~/repos/git/forks/scipy/build-install/lib/python3.10/site-packages/scipy/stats/_discrete_distns.py:254, in betabinom_gen._stats(self, n, a, b, moments)
    252 g2 += 3 * a * b * (n - 2)
    253 g2 += 6 * n ** 2
--> 254 g2 -= 3 * e_p * b * n * (6 - n)
    255 g2 -= 18 * e_p * e_q * n ** 2
    256 g2 *= (a + b) ** 2 * (1 + a + b)

UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```
If either `a` or `b` is a float, the error does not occur:
```
In [3]: betabinom.stats(10, 2, 3.0, moments='k')
Out[3]: -0.6904761904761907

```
The above was run with the main development branch of SciPy (`'1.11.0.dev0+1559.890ffe9'`) and NumPy 1.24.2.

### SciPy/NumPy/Python version information

/home/warren/repos/git/forks/scipy/build-install/lib/python3.10/site-packages/scipy/__config__.py:140: UserWarning: Install `pyyaml` for better output   warnings.warn("Install `pyyaml` for better output", stacklevel=1) {   "Compilers": {     "c": {       "name": "gcc",       "linker": "ld.bfd",       "version": "11.3.0",       "commands": "cc"     },     "cython": {       "name": "cython",       "linker": "cython",       "version": "0.29.33",       "commands": "cython"     },     "c++": {       "name": "gcc",       "linker": "ld.bfd",       "version": "11.3.0",       "commands": "c++"     },     "fortran": {       "name": "gcc",       "linker": "ld.bfd",       "version": "11.3.0",       "commands": "gfortran"     },     "pythran": {       "version": "0.12.1",       "include directory": "/home/warren/py3.10.8/lib/python3.10/site-packages/pythran"     }   },   "Machine Information": {     "host": {       "cpu": "x86_64",       "family": "x86_64",       "endian": "little",       "system": "linux"     },     "build": {       "cpu": "x86_64",       "family": "x86_64",       "endian": "little",       "system": "linux"     },     "cross-compiled": false   },   "Build Dependencies": {     "blas": {       "name": "openblas",       "found": true,       "version": "0.3.20",       "detection method": "pkgconfig",       "include directory": "/usr/include/x86_64-linux-gnu/openblas-pthread/",       "lib directory": "/usr/lib/x86_64-linux-gnu/openblas-pthread/",       "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER=1 NO_CBLAS= NO_LAPACK= NO_LAPACKE=1 NO_AFFINITY=1 USE_OPENMP=0 generic MAX_THREADS=64",       "pc file directory": "/usr/lib/x86_64-linux-gnu/pkgconfig"     },     "lapack": {       "name": "openblas",       "found": true,       "version": "0.3.20",       "detection method": "pkgconfig",       "include directory": "/usr/include/x86_64-linux-gnu/openblas-pthread/",       "lib directory": "/usr/lib/x86_64-linux-gnu/openblas-pthread/",       "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER=1 NO_CBLAS= NO_LAPACK= NO_LAPACKE=1 NO_AFFINITY=1 USE_OPENMP=0 generic MAX_THREADS=64",       "pc file directory": "/usr/lib/x86_64-linux-gnu/pkgconfig"     }   },   "Python Information": {     "path": "/home/warren/py3.10.8/bin/python3",     "version": "3.10"   } }

**Comment by vmpyr** [comment]
The docs for the parent class say that `a` and `b` need to be floats. Ref: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_discrete.html#scipy.stats.rv_discrete

Should we change that to include integers as well? We can simply convert the integer to float before passing the argument in the current definition of the class.
