### ISSUE TITLE
CI: linux_meson.yml 3.11 run has been failing since Feb21. 

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#18025]
### Describe your issue.

The linux_meson.yml 3.11-dev run has been failing for the last day or so. It get's almost to the end of the test run and then segfaults. It installs numpy, pythran and meson from git, so there's a few things to check there (should we change to numpy-nightly?).

I don't think it's anything we've committed to scipy, but not completely sure.

### Reproducing Code Example

```python
CI
```

### Error message

```shell
CI
```

### SciPy/NumPy/Python version information

3.11.2

**Comment by andyfaff** [comment]
The test fails seem to be the same across different PR runs:

```
_ build-install/lib/python3.11/site-packages/scipy/stats/tests/test_mstats_basic.py _
[gw0] linux -- Python 3.11.2 /opt/hostedtoolcache/Python/3.11.2/x64/bin/python
worker 'gw0' crashed while running 'build-install/lib/python3.11/site-packages/scipy/stats/tests/test_mstats_basic.py::TestMode::test_mode'
_ build-install/lib/python3.11/site-packages/scipy/stats/tests/test_mstats_basic.py _
[gw2] linux -- Python 3.11.2 /opt/hostedtoolcache/Python/3.11.2/x64/bin/python
worker 'gw2' crashed while running 'build-install/lib/python3.11/site-packages/scipy/stats/tests/test_mstats_basic.py::TestMode::test_mode_modifies_input'
_ build-install/lib/python3.11/site-packages/scipy/stats/tests/test_mstats_basic.py _
[gw3] linux -- Python 3.11.2 /opt/hostedtoolcache/Python/3.11.2/x64/bin/python
worker 'gw3' crashed while running 'build-install/lib/python3.11/site-packages/scipy/stats/tests/test_mstats_basic.py::TestPercentile::test_percentile'
```

I can repeat the test fail locally, but am unsure as to go about searching any further (plus it's slow to do so, I'm emulating x86_64 on my M1 mac). @mdhaber, do you have ideas?

**Comment by andyfaff** [comment]
- An individual test run of `python dev.py --no-build test -t scipy.stats.tests.test_mstats_basic::TestMode::test_mode` fails, i.e. without the parallelisation introduced by `-j 2`. I daresay the other fails would occur as well.
- I uninstalled the numpy built from the git repo and installed numpy-1.24.2, then did a partial rebuild of scipy via `python dev.py build --werror` (build 254 files instead of ~1600). `test_mode` passes with 1.24.2. --> problem is probably with a specific numpy commit. So I'll try bisecting on numpy builds.

**Comment by andyfaff** [comment]
I've done a manual bisection with numpy, building various commits and seeing if `[scipy.stats.tests.test_mstats_basic::TestMode::test_mode](https://github.com/scipy/scipy/blob/main/scipy/stats/tests/test_mstats_basic.py#L740)` passes or fails.

numpy/numpy@cfef4c0 - pass
numpy/numpy@bca3155 - pass
numpy/numpy@1779c5a - fail
numpy/numpy@f6eaca8 - pass
numpy/numpy@b657a75 - pass
numpy/numpy@138bba5 - fail

@seberg it seems something introduced in numpy/numpy@138bba5 caused something in `scipy.stats` to break. It only manifests in the three test fails above, and I've only seen it on Python3.11.2 so far (but that's the only entry that uses repo numpy).

If I understand correctly the test function calls [`_mode`](https://github.com/scipy/scipy/blob/main/scipy/stats/_mstats_basic.py#L338), which narrows things down a lot. From a quick inspection there's no compiled scipy code being called, which would indicate that it's a numpy bug.

**Comment by andyfaff** [comment]
@seberg  is a MWE that causes a segfault:

```
import numpy as np
import numpy.ma as ma

def find_repeats(arr):
    # Make sure we get a copy. ma.compressed promises a "new array", but can
    # actually return a reference.
    compr = np.asarray(ma.compressed(arr), dtype=np.float64)
    try:
        need_copy = np.may_share_memory(compr, arr)
    except AttributeError:
        # numpy < 1.8.2 bug: np.may_share_memory([], []) raises,
        # while in numpy 1.8.2 and above it just (correctly) returns False.
        need_copy = False
    if need_copy:
        compr = compr.copy()
    return _find_repeats(compr)


def _mode1D(a):
	(rep,cnt) = find_repeats(a)
	print("there")
	if not cnt.ndim:
		return (0, 0)
	elif cnt.size:
		return (rep[cnt.argmax()], cnt.max())
	else:
		return (a.min(), 1)
		

axis=0
a = [0, 0, 0, 1, 1, 1, 2, 3, 3, 3, 3, 4, 5, 6, 7]

output = ma.apply_along_axis(_mode1D, axis, a)
```

**Comment by seberg** [comment]
Thanks.  It must be somewhere deeper, maybe in `ma.compressed` which might be using a function that can hit the changes.  I am a bit surprised, but can happen.

Will look into it some time today, but got to run it through lldb/gdb to see the issue (at which point it is probably obvious).

**Comment by andyfaff** [comment]
I've got a simpler MWE, I'm currently making a numpy issue.

**Comment by andyfaff** [comment]
It's higher than that, `_mode1D` doesn't even get called.

**Comment by seberg** [comment]
Yeah, it had to be in putto or putmask.  In any case, it is in `np.put` (or so).  The problem is some error (or early finish) path where cleanup gets triggered but the prepare never happened.

Thanks for tracking this down, could have opened the issue first, with even a very rough repro, could have tracked it down quickly (due to where it crashes roughly).

**Comment by andyfaff** [comment]
Fixed by https://github.com/numpy/numpy/commit/b30e6d0a4876666688041d63e5be3ad45a356bff
