### ISSUE TITLE
DOC: Unable to click links or select text in "warning" bubble

### ISSUE THREAD

**Issue by jmole** [scipy/scipy#18048]
### Issue with current documentation:

On this page, I am unable to click on the links or select text inside the deprecation warning: https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.derivative.html

**Comment by mdhaber** [comment]
I can reproduce this (Android Chrome ATM). It is not true of other warning or note admonitions, and it doesn't seem to be true of deprecation warnings in other libraries (e.g. https://pandas.pydata.org/docs/reference/api/pandas.Timedelta.delta.html#pandas.Timedelta.delta). It does seem to be true of all SciPy deprecations.

**Comment by tupui** [comment]
Thank you for reporting. This is known issue and already fixed on the theme side. We are stuck with this version but this will resolve eventually.
Nothing to do here so closing.
