### ISSUE TITLE
ENH: Decorator for `solve_ivp` event functions

### ISSUE THREAD

**Issue by ZedThree** [scipy/scipy#18041]
### Is your feature request related to a problem? Please describe.

When passing `event` functions to `solve_ivp`, you might like to add the `terminal`/`direction` attributes. Unfortunately, this doesn't play nice with type checkers like mypy (see https://github.com/python/mypy/issues/2087)

### Describe the solution you'd like.

A simple decorator resolves the errors:

```py
class Event(Protocol):
    terminal: bool = False
    direction: float = 0.0

    def __call__(self, t, y, *args):
        pass


def event(terminal: bool, direction: float):
    def decorator_event(func: Any) -> Event:
        func.terminal = terminal
        func.direction = direction
        return func

    return decorator_event

@event(terminal=True, direction=1.0)
def my_event(t, y):
  ...
```

This is obviously not very difficult for the user to implement themselves, but it would be a nice quality of life improvement for projects using mypy.

**Comment by tupui** [comment]
Hi @ZedThree, thank you for reporting. I am not sure I see the link with `solve_ivp`. Could you be more specific and show the SciPy code you would have, the issue raised by MyPy, etc.

**Comment by ZedThree** [comment]
Sure, here's an minimal example:

```py
from scipy.integrate import solve_ivp

def my_event(t, y):
    return y - 42

event.terminal = False
event.direction = 1.0

output = solve_ivp(lambda t, y: y, t_span=[0, 10], y0=0, events=(my_event,))
```

Then running mypy on this file:
```bash
$ mypy solve_ivp_mvce.py 
solve_ivp_mvce.py:6: error: "Callable[[Any, Any], Any]" has no attribute "terminal"
solve_ivp_mvce.py:7: error: "Callable[[Any, Any], Any]" has no attribute "direction"
Found 2 errors in 1 file (checked 1 source file)
```

Now here's the same example with my decorator:

```py
from scipy.integrate import solve_ivp
from typing import Protocol, Any

class Event(Protocol):
    terminal: bool = False
    direction: float = 0.0

    def __call__(self, t, y, *args):
        pass


def event(terminal: bool, direction: float):
    def decorator_event(func: Any) -> Event:
        func.terminal = terminal
        func.direction = direction
        return func

    return decorator_event


@event(terminal=False, direction=1.0)
def my_event(t, y):
    return y - 42

output = solve_ivp(lambda t, y: y, t_span=[0, 10], y0=0, events=(my_event,))
```

```bash
$ mypy solve_ivp_mvce.py 
Success: no issues found in 1 source file
```

Note that this isn't really anything to do with typing in SciPy itself, this would be convenience decorator provided to squash typing errors coming from user code.

Do you think this is suitable for SciPy? I'd be happy to try and add some typing to `solve_ivp` while I'm at it.

**Comment by tupui** [comment]
Ok thank you for the details. Way better 👍 

The decorator is one approach (the one shown in the doc), another one is a class and here mypy won't get confused.

```python
class Event:
    terminal = False
    direction = 1.0

    def __call__(self, t, y):
        return y - 42
```

I am -1 on including such decorator as in the end it's a very valid syntax. Until there is a solution on mypy's side, some noqa would do the trick.

Adding types itself is welcomed though. Note that it's a hard task, cf existing typed files we have such as `scipy.stats.qmc`.

**Comment by ZedThree** [comment]
Yes, using a class directly is another approach, though it doesn't really scale when using multiple events.

Ok, that's fair enough! I thought others might find it useful, but it's pretty niche, and I wasn't sure if it fitted in with SciPy in general.

**Comment by tupui** [comment]
I will close for now if you don't mind. Since this part is not even typed, it's a bit premature anyway to consider something like this. We could re-open when this is again a thing.
