### ISSUE TITLE
ENH/QUERY: Appel's hypergeometric functions

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#18056]
### Is your feature request related to a problem? Please describe.

The [Appel functions](https://en.wikipedia.org/wiki/Appell_series) are generalizations of the hypergeometric function $_2F_1$.

I stumbled upon them researching formulas of the [gausshyper distribution](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gausshyper.html#scipy.stats.gausshyper). That distribution currently lacks every method but `pdf` and `munp` methods. The CDF of that one contains the Appel function $_1F$ (source [here](https://www.redalyc.org/pdf/835/83522621002.pdf)):

![image](https://user-images.githubusercontent.com/40656107/221419740-9f23d1c0-7c7f-486f-83dd-864dcb8dcdf5.png)

There exists only one 20 year old public implementation of $_1F$ in Fortran without license info which is also used in R apparently:
https://github.com/cran/appell

That code is based on [this paper](https://www.sciencedirect.com/science/article/abs/pii/S0010465503004909) which lists among others:

External subprograms used: Numerical Recipes hypgeo [W.H. Press et al., Numerical Recipes in Fortran 77, Cambridge Univ. Press, 1996] or chyp routine of R.C. Forrey [J. Comput. Phys. 137 (1997) 79], rkf45 [L.F. Shampine and H.H. Watts, Rep. SAND76-0585, 1976].

That probably means, the code cannot be wrapped for SciPy license wise (correct me if I am wrong).

I am by no means an expert on such functions but I guess an implementation in scipy would require a lot of effort. So the question is: is it worth it? Are there other uses cases for that function?

CC @steppi @WarrenWeckesser

**Comment by rgommers** [comment]
> That probably means, the code cannot be wrapped for SciPy license wise (correct me if I am wrong).

That sounds right to me.

> I am by no means an expert on such functions but I guess an implementation in scipy would require a lot of effort. So the question is: is it worth it? Are there other uses cases for that function?

It seems like in scope in theory, and this function is being mentioned in other places, like in the Mathematica docs and in https://en.wikipedia.org/wiki/Appell_series. And in principle it'd be in scope. That said, we have a lot of issues with our existing hypergeometric functions, and the Appell ones seem to be a generalization - so from that perspective I'd be very hesitant to embark on an implementation journey here.

**Comment by steppi** [comment]
> It seems like in scope in theory, and this function is being mentioned in other places, like in the Mathematica docs and in https://en.wikipedia.org/wiki/Appell_series. And in principle it'd be in scope. That said, we have a lot of issues with our existing hypergeometric functions, and the Appell ones seem to be a generalization - so from that perspective I'd be very hesitant to embark on an implementation journey here.

Agreed. The analytic continuation formulas involve series where every term contains a Gaussian hyper geometric function evaluation. That's a complete non-starter with the current state of `hyp2f1`, so the issues there are a blocker. 

If we do decide to go down this road, it would be good to have an arbitrary precision reference implementation.It might be a good idea to submit a feature request issue to `mpmath` instead. This could be a good fit there and probably wouldn't be *too* difficult to implement based on their existing arbitrary precision `hyp2f1`.

**Comment by rgommers** [comment]
@dschmitz89 how about we close this for now, and if the `hyp2f1` blocker is resolved and there's a stronger motivation for someone to work on this feature, we can reopen?

**Comment by dschmitz89** [comment]
That works for me. For future reference: this function is already in mpmath (see [here](https://mpmath.org/doc/current/functions/hypergeometric.html#mpmath.appellf1)).

**Comment by steppi** [comment]
> That works for me. For future reference: this function is already in mpmath (see [here](https://mpmath.org/doc/current/functions/hypergeometric.html#mpmath.appellf1)).

Good to know. Thanks. I should have checked
