### ISSUE TITLE
ENH: Accept `kwargs` in `cramervonmises`

### ISSUE THREAD

**Issue by FredericWantiez** [scipy/scipy#18055]
### Is your feature request related to a problem? Please describe.

The `cramervonmises` test does not support `kwargs` on top of `args` for distributions called by name. It would be helpful for testing distributions with alternative parametrizations (like `gengamma`):

```python
# Testing GenGamma(a, d, p) as defined in https://en.wikipedia.org/wiki/Generalized_gamma_distribution
test = cramervonmises(samples, 'gengamma', args=(d/p, p), kargs={scale=a})
```

### Describe the solution you'd like.

The most obvious one would be to forward the `kwargs` to the `cdf` call in `cramervonmises`:
https://github.com/scipy/scipy/blob/c1ed5ece8ffbf05356a22a8106affcd11bd3aee0/scipy/stats/_hypotests.py#L589

Would become:
```python
cdfvals = cdf(vals, *args, **kwargs)
```

### Describe alternatives you've considered.

You can get around by forwarding `args = (*args, loc, scale)` but that only works because of the implementation details in `rv.cdf`:
https://github.com/scipy/scipy/blob/9d74b29239d05f6ec63e4c16cd8a49d0fa58e7c2/scipy/stats/_distn_infrastructure.py#L2061

**Comment by tupui** [comment]
Thank you for reporting @FredericWantiez. It's a bit unfortunate we went with this interface. As it is it seems legitimate. Personally I would instead advocate to only allow passing a callable (so you would create beforehand the correct distribution.) There is little to no need to do this within the function. Defining fully a distribution by passing all arguments vs passing a distribution.

**Comment by mdhaber** [comment]
It doesn't look like that is SciPy's version of `gengamma` you're referring to, right? SciPy's doesn't offer an alternative parametrization, AFAICT.

`cramervonmises` probably went with that interface to follow `ks_1samp`, which is quite old. But I think both allow the user to pass the CDF of a frozen distribution, i.e. one that accepts only `x` and no additional parameters. Does that not work for you, @FredericWantiez?
