### ISSUE TITLE
ENH: stats.ttest_ind is inconsistent with R. It does not allow testing against a single datapoint

### ISSUE THREAD

**Issue by qa-aleksejs-fomins** [scipy/scipy#18069]
### Is your feature request related to a problem? Please describe.

It is frequently useful to perform a two-sample t-test for the case when one of the samples has only one datapoint, and variances are equal. Mathematically, only the total variance is required for the test, so variance of 0 can be assumed for the degenerate dataset.

### Describe the solution you'd like.

I would like for the command

ttest_ind(np.random.normal(0,1,100), [1], equal_var=True)

to produce a test statistic and a p-value, not (NAN, NAN) as it does at the moment. Can be made consistent with R, where one can do the following without problem

t.test(rnorm(100),1,var.equal = TRUE)

**Comment by mdhaber** [comment]
Often the formulas for the t statistic are expressed in terms of the individual sample variances. Can they be reduced to show that the sample variance of the individual sample variances don't matter, or is it an assumption that the variance is zero? 
If it is an assumption, does the test still produce uniformly distributed p-values under the null hypothesis?

**Comment by qa-aleksejs-fomins** [comment]
I am sorry. The solution was recommended to me by stats SE community, to them it makes common sense. I am trying to find the proof for this case online, but so far I have not succeeded.

Looking at the implementation of the ttest_ind in scipy, I can certainly tell that it attempts to calculate the variance of both arrays in all cases, which should result in a NAN if the array only has one datapoint. Thus, one could extend the functionality of the ttest_ind by allowing exactly one of the arrays to have length 1. This can be done by putting a bunch of IF statements: throwing an exception of both have length 1, otherwise setting the corresponding variance to 0 manually if only one of the arrays have length 1.

So the edit to the function is simple. It still remains to be seen if this is actually correct. I am hoping if somebody with more statistics knowledge could comment

**Comment by mdhaber** [comment]
Yup, I can't find anything wrong with this. The formulas I'm finding present the pooled variance as a weighted average of the sample variances, but symbolically, the `(n-1)` weights cancel with the `(n-1)`s in the denominators of the unbiased sample variances, and we're left with the sum of squared differences of the sample means. This is zero for the sample with only one observation.

After making this fix, as a sanity check:
```python3
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
rng = np.random.default_rng(246834602926842)

x = rng.normal(size=(10000, 2))
y = rng.normal(size=(10000, 1))
res = stats.ttest_ind(x, y, equal_var=True, axis=-1)
plt.hist(res.pvalue)
plt.xlabel('p-value')
plt.ylabel('frequency')
plt.title('p-values produced by ttest_ind under the null hypothesis')
```
![image](https://user-images.githubusercontent.com/6570539/222023862-ecf9b4a1-496d-4fcf-9a62-5076b87025f6.png)

Looks quite uniform to me.  Also `stats.ttest_ind([2, 3, 5], [1.5], equal_var=True)` gives the same result as `t.test(c(2, 3, 5), c(1.5), equal.var=TRUE)` in R.

There are a few ways to get the same numerical result, including setting the sample variance to zero (although this _looks_ a bit suspicious, so it would deserve an explanatory comment). **PR welcome**, but please keep in mind that we only want to change the `equal_var=True` case. I haven't looked at the unequal variance math lately, but I doubt it works the same way, and R produces a `not enough 'y' observations` error in this case.

**Comment by tupui** [comment]
@mdhaber I suppose that would help support the issue we've seen on Dunnett's test with the test case having a single obs in the last group.

**Comment by mdhaber** [comment]
Sure. If you can open a PR, we can probably merge it today.

**Comment by tupui** [comment]
👍 for visibility also putting this here. I propose to add the following in `_equal_var_ttest_denom`.

```python
    if n1 == 1:
        v1 = 0
    if n2 == 1:
        v2 = 0
```

Then the only thing is that there is the `RuntimeWarning`. Shall I just filter it out in the root function?

**Comment by mdhaber** [comment]
Yes, that and a comment would be good. I would also be OK with one-liners in this case, e.g. `v1 = 0 if n1 == 1 else v1`.

Preferably, the "Precision loss occurred in moment calculation due to " "catastrophic cancellation." would not be emitted by `_moment`  at all if there is only one observation.

The others due to division by zero in `var *= np.divide(n, n-ddof)` can safely be silenced with `np.errstate`, I think.

**Comment by qa-aleksejs-fomins** [comment]
Hmm, sorry for noob question, but I suppose that the code should also throw some kind of an exception if both n1=1 and n2=1. I think this case is not covered in the pull request at the moment.

**Comment by tupui** [comment]
Maybe yes. Please let's discuss these in the linked PR 😃

**Comment by mdhaber** [comment]
I think it will still return NaNs and emit a warning without doing anything special because `denom` will be 0. We should check for this if it's not already checked.

**Comment by joshtburdick** [comment]
Another corner case, which I'm not sure about. The variance (for one or both samples) can be zero, even if n>1. For instance:
```
>>> import scipy.stats
>>> scipy.stats.ttest_ind([1,2,3], [3,3,3])
[...] /python3.12/site-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
TtestResult(statistic=np.float64(-1.7320508075688774), pvalue=np.float64(0.15830242337545783), df=np.float64(4.0))
```
However, R prints the same answer, without a warning:
```
> t.test(c(1,2,3), c(3,3,3), var.equal=TRUE)

	Two Sample t-test

data:  c(1, 2, 3) and c(3, 3, 3)
t = -1.7321, df = 4, p-value = 0.1583
```

I'm not sure what the right thing to do here is. I'm guessing R is correct here (though I don't mean to assume that) . So it might be worth considering that case.
