### ISSUE TITLE
BUG: rv_continuous.stats fails to converge when trying to estimate moment parameters for particular distributions

### ISSUE THREAD

**Issue by medgives** [scipy/scipy#18071]
### Describe your issue.

When trying to get moments estimation (mean, variance, skewness, kurtosis) for Johnson SU distributions parametrized with specific location, scale, a and b values, the function fails to converge.
Tried to increase the limit from 50 to 100 as suggested from the error message, with no result. 
From a quick look at _distn_infrastructure.py, the culprit should be the part where the ppf is integrated, especially when it contains high steepness near the boundaries (singularities). It can be mitigated by changing the integration boundaries in _distn_infrastructure.py:2041 from (0, 1) to (0.00000001, 0.9999999). This however changes the integration result. 

### Reproducing Code Example

```python
from scipy.stats import johnsonsu

l= 0.02; s= 0.0001; a = -0.01; b = 1.1
mean, var, skew, kurt = johnsonsu.stats(a, b, loc=l, scale=s, moments='mvsk')
```

### Error message

```shell
IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
If increasing the limit yields no improvement it is advised to analyze
the integrand in order to determine the difficulties.  If the position of a
local difficulty can be determined (singularity, discontinuity) one will
probably gain from splitting up the interval and calling the integrator
on the subranges.  Perhaps a special-purpose integrator should be used.
return integrate.quad(self._mom_integ1, 0, 1, args=(m,)+args)[0]
```

### SciPy/NumPy/Python version information

1.10.1 1.22.3 sys.version_info(major=3, minor=10, micro=1, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment]
Formulas for the mean, variance, skewness and excess kurtosis are given in the [wikipedia article](https://en.wikipedia.org/wiki/Johnson%27s_SU-distribution)  on Johnson's $S_U$ distribution, so this should be an "easy fix".

**Comment by medgives** [comment]
> Formulas for the mean, variance, skewness and excess kurtosis are given in the [wikipedia article](https://en.wikipedia.org/wiki/Johnson%27s_SU-distribution) on Johnson's SU distribution, so this should be an "easy fix".

Indeed they are useful, but the nice thing about the stats method is that can "convert" easily from location/scale parametrization (more Scipy-like) to the moments parametrization, which is much more used in the scientific community. IIRC, there's no direct "easy" correspondence between them (e.g., location is not always equal to the mean).

**Comment by WarrenWeckesser** [comment]
@medgives, to be clear, when I say there is an "easy fix", I mean this is something we can easily implement in the `johsnonsu` code in SciPy.  The `stats` method would use the explicit formulas instead of doing numerical integration. There would be no change in the use of `johnsonsu` from a user's point of view, except that the calculations of those moments would be faster and more accurate.

There is a direct mapping between the parameters used in SciPy and those used in the wikipedia article: `a` ⇔ $\gamma$, `b` ⇔ $\delta$, `loc` ⇔ $\xi$, `scale` ⇔ $\lambda$.

**Comment by medgives** [comment]
I didn't get your point at the beginning! Yes, I know that in Johnson's SU there is direct mapping, but this is not always true for every distribution in Scipy. And probably the integration issue will occur with other distribution as well, in particular conditions. Anyway, thanks for your reply!
