### ISSUE TITLE
BUG: `Halton(seed=rng)` does not consume `Generator` PRNG state

### ISSUE THREAD

**Issue by rkern** [scipy/scipy#18079]
### Describe your issue.

Ported from [another thread](https://github.com/scipy/scipy/pull/16923#issuecomment-1234551154) on request.

The `Halton` `QMCEngine` implements scrambling in a way that does not advance the PRNG state of a `Generator` instance that is passed in. This has consequences for its ability to use it like other `QMCEngine`s in a randomized QMC integration like `qmc_quad()`, as shown in the reference PR.

```python

>>> rng = np.random.default_rng(0xa29cabb11cfdf44ff6cac8bec254c2a0)

>>> for i in range(3):
...     q = qmc.Halton(d=2, seed=rng)
...     print(q.random(4))
... 
[[0.92701897 0.40341341]
 [0.42701897 0.07008008]
 [0.67701897 0.73674674]
 [0.17701897 0.51452452]]
[[0.92701897 0.40341341]
 [0.42701897 0.07008008]
 [0.67701897 0.73674674]
 [0.17701897 0.51452452]]
[[0.92701897 0.40341341]
 [0.42701897 0.07008008]
 [0.67701897 0.73674674]
 [0.17701897 0.51452452]]
```

Contrast with `Sobol` which does advance the PRNG state in the way one would expect and desire in an RQMC scenario:

```python
>>> rng = np.random.default_rng(0xa29cabb11cfdf44ff6cac8bec254c2a0)

>>> for i in range(3):
...     q = qmc.Sobol(d=2, seed=rng)
...     print(q.random(4))
... 
[[0.12786313 0.37406467]
 [0.60378522 0.97493285]
 [0.78469998 0.05257057]
 [0.4483653  0.66849917]]
[[0.62039108 0.1264537 ]
 [0.34204027 0.88977271]
 [0.20952058 0.47037593]
 [0.98823756 0.73434347]]
[[0.403715   0.34581335]
 [0.57170838 0.63953364]
 [0.96115589 0.00454448]
 [0.01191571 0.97690696]]
```

The reason `Halton` behaves this way is that it delegates its work to multiple calls of [`van_der_corput()`](https://github.com/scipy/scipy/blob/cfc8958d1933de9a848c78703cea814e6ff0ce90/scipy/stats/_qmc.py#L1012-L1016), once for each dimension. In so doing, it deepcopies whatever `seed=` was passed in to give a separate identical copy to each dimension's call. As far as I can tell, the deepcopy isn't actually important to spread the work to each dimension; in fact, I think it's incorrect that they get identical copies. However, it is true that in order for multiple sequential calls to `random()` to be coherently scrambled, _something_ needs to be done to coordinate between the separate `random()` calls; here, that's being accomplished as a bankshot from the multiple deepcopiies but could be accomplished in other ways.

My [first assertion has been disputed](https://github.com/scipy/scipy/pull/17955#discussion_r1122225994), so let's walk through it. `Halton` assigns a prime number to each dimension. This is the `base` integer that's passed into `van_der_corput()`.

```python
>>> q = qmc.Halton(d=5)

>>> q.base
[2, 3, 5, 7, 11]
```

In the [guts of `van_der_corput()`](https://github.com/scipy/scipy/blob/cfc8958d1933de9a848c78703cea814e6ff0ce90/scipy/stats/_qmc.py#L583-L592) for one dimension with a given `base`, the scrambling needs to generate an `(count, base)` array of integers where each of the `count` rows is an independent permutation of `np.arange(base)`. `count` is a small integer that is a function of `base` and not the number of requested samples; the precise details are otherwise unimportant here. So when `van_der_corput()` gets called with different `base` prime numbers, the PRNG that is used to shuffle them is not trying to repeat the same shuffling _across dimensions_ because the lengths of the arrays that are being shuffled are quite different. And while it's probably not especially harmful that the same parts of the PRNG cycle are being used for calls to `rng.shuffle()`, each permuted row for each dimension _is_ supposed to be independent according to my reading of [the paper referenced in the comments](https://artowen.su.domains/reports/rhalton.pdf). The R code in that paper even takes special care to ensure that each dimension does _not_ get the same PRNG state.

But it _is_ true that the _same_ permutations need to get used for multiple calls to `random()`. The deepcopying to send identical copies of the `Generator` to each dimension had the _side effect_ of ensuring that each call to `random()` started off with the same `Generator` state, too. But I think the answer here is to precompute the scrambling permutation arrays inside of `Halton.__init__()` much like `Sobol.__init__()` computes its scrambling data there. That will end up advancing the state of the passed-in `Generator` when constructing `Halton` and restoring the desirable semantics for RQMC.

### Reproducing Code Example

```python
As above.
```

### Error message

```shell
As above.
```

### SciPy/NumPy/Python version and system information

```shell
1.8.0 1.21.2 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
```

**Comment by tupui** [comment]
I will double check that and remove the deep copy if we can.

**Comment by tupui** [comment]
Ok so the deepcopy is not needed for the algorithm itself (could not see a difference in terms of convergence on my test suite), but for being able to continue sampling. e.g. the following test would fail.

```python
    def test_continuing(self, scramble):
        engine = self.engine(d=2, scramble=scramble)
        ref_sample = engine.random(n=8)

        engine = self.engine(d=2, scramble=scramble)

        n_half = len(ref_sample) // 2

        _ = engine.random(n=n_half)
        sample = engine.random(n=n_half)
        assert_allclose(sample, ref_sample[n_half:], atol=1e-1)
```

The first half of the sample would be the same. But the second half would be different as we would not use the same permutations.

So yes, pre-computing the permutations outside of VDC might be required. Looking into it.
