### ISSUE TITLE
BUG: `QMCEngine.reset()` semantics and passed `Generator` instances

### ISSUE THREAD

**Issue by rkern** [scipy/scipy#18078]
### Describe your issue.

Ported from [another thread](https://github.com/scipy/scipy/pull/17955#discussion_r1122185322). I apologize for the length, but I was asked to explain in more detail.

The `QMCEngine`s use pseudorandomness through `Generator` in various ways for the purpose of scrambling. `QMCEngine`s also implement a `reset()` method that purports to reset the QMC sequence back to its initial state so that subsequent samples can be repeated. When a user chooses not to use scrambling or when a user specifies a static seed integer, this resetting works as I expect; you can get exactly the same samples repeatably.

```python
>>> q = qmc.Halton(d=2, scramble=False)

>>> q.random(4)
array([[0.        , 0.        ],
       [0.5       , 0.33333333],
       [0.25      , 0.66666667],
       [0.75      , 0.11111111]])

>>> q.reset()
<scipy.stats._qmc.Halton at 0x7f38ea51aeb0>

>>> q.random(4)
array([[0.        , 0.        ],
       [0.5       , 0.33333333],
       [0.25      , 0.66666667],
       [0.75      , 0.11111111]])

>>> q = qmc.Halton(d=2, seed=0xa29cabb11cfdf44ff6cac8bec254c2a0)

>>> q.random(4)
array([[0.92701897, 0.40341341],
       [0.42701897, 0.07008008],
       [0.67701897, 0.73674674],
       [0.17701897, 0.51452452]])

>>> q.reset()
<scipy.stats._qmc.Halton at 0x7f38e67a8250>

>>> q.random(4)
array([[0.92701897, 0.40341341],
       [0.42701897, 0.07008008],
       [0.67701897, 0.73674674],
       [0.17701897, 0.51452452]])
```

However, when the user passes an existing `Generator` instance as the seed or passes `None`, the resetting semantics work more variably. `QMCEngine` stores a deepcopy of the passed `seed` object and stores it in the `.rng_seed` attribute for later resetting. It will pass the original `seed` object through `np.random.default_rng()` (more or less) to coerce it to a `Generator` instance which it stores in the `.rng` attribute; `seed` objects that are already `Generator` instances are passed through without copying. When `.reset()` is called, the `.rng_seed` object is deepcopied again and passed through `default_rng()` to coerce it to a `Generator`.

When `seed=None`, `default_rng(None)` creates a fresh `Generator` with OS-provided entropy. Resetting the state no longer actually resets.

```python
>>> q = qmc.Halton(d=2, seed=None)

>>> q.random(4)
array([[0.86786616, 0.14418323],
       [0.36786616, 0.47751656],
       [0.61786616, 0.81084989],
       [0.11786616, 0.25529434]])

>>> q.reset()
<scipy.stats._qmc.Halton at 0x7f38e66cc7c0>

>>> q.random(4)
array([[0.42982941, 0.78171812],
       [0.92982941, 0.11505145],
       [0.17982941, 0.44838478],
       [0.67982941, 0.670607  ]])
```

Now, that might be  considered useful, as if the user is requesting that you start the QMC part of the sequence over, but do a new rescrambling because `seed=None`, but not all `QMCEngine`s work like that. `Sobol`, for instance, only uses the `Generator` during instantiation and not sampling. Resetting the `.rng` to be `default_rng(None)` does nothing, and the scrambling is not reapplied during the reset.

```python
>>> q = qmc.Sobol(d=2, seed=None)

>>> q.random(4)
array([[0.47767156, 0.93139656],
       [0.79002613, 0.37025878],
       [0.67699522, 0.67998868],
       [0.11413617, 0.11979645]])

>>> q.reset()
<scipy.stats._qmc.Sobol at 0x7f38e886ec70>

>>> q.random(4)
array([[0.47767156, 0.93139656],
       [0.79002613, 0.37025878],
       [0.67699522, 0.67998868],
       [0.11413617, 0.11979645]])
```

When a `Generator` instance is passed, we are in a bit of a correctness bind. While there are use cases for sampling the same segment of the PRNG cycle multiple times (this kind of resetting can be one of them), one has to be careful and do it under very controlled circumstances such that one is only doing it in exactly the place that is desired. The code that is doing that resetting needs to own the `Generator` entirely. If the semantics of `QMCEngine` wants to store the given `Generator` state and restore it upon `reset()`, then it cannot accept a passed `Generator` instance as-is. One could spawn a new `Generator` from it and only sample from the spawned `Generator` (and warn people against accessing it directly because only the `QMCEngine` owns it now).

```python
>>> rng = np.random.default_rng(0xa29cabb11cfdf44ff6cac8bec254c2a0)

>>> q = qmc.LatinHypercube(d=2, seed=rng)

# One continues to use the Generator somehow. This could even be something
# innocuous-looking like `qmc.Sobol(d=2, seed=rng)` which consumes some PRNG
# state during initialization.

>>> rng.random(4)
array([0.24573226, 0.85685711, 0.02918954, 0.96401299])

>>> q.random(4)
array([[0.88200533, 0.35298427],
       [0.55332016, 0.78001033],
       [0.05455107, 0.01202496],
       [0.3535495 , 0.7165475 ]])

>>> q.reset()
<scipy.stats._qmc.LatinHypercube at 0x7f38e66a0f40>

>>> q.random(4)
array([[0.68856694, 0.78578572],
       [0.24270262, 0.25899675],
       [0.38200533, 0.10298427],
       [0.80332016, 0.53001033]])
```

So `reset()` can't make good on its promised semantics in such cases. The reset's deepcopy of the passed-in `Generator` instance isn't a replacement for the thing that the `QMCEngine` used during the first `.random()` call. Parts of the PRNG cycle are reused, but not for the parts where we _wanted_ them to be used (i.e. the two `QMCEngine.random()` calls). The subsequent calls to `QMCEngine.random()` will correlate with the other outputs from the `Generator`, not the two supposed copies of the QMC sequence.

There are a couple of outs here, but it just depends on what the intended semantics of `QMCEngine.reset()` actually are. Given the variability between implementations and different scenarios for `seed=` values, I don't quite know what they are intended to be. Generally, if we want `reset()` to be a way to reproduce scrambled QMC sequences, then I think it needs to own its own `Generator` instance. When passed a `Generator` instance, it should spawn a child and store a deepcopy of it for later use in `reset()`. When passed `seed=None`, it should store a deepcopy of the instantiated `Generator` for the same purpose, not `None`. Copying the state of a `Generator` can really only be a safe and valid thing to do when you own the whole lifecycle of the `Generator`, from birth to death. If you are using a `Generator` that was passed in, you don't own it.

If the goal is just to reset the QMC parts of the state and reinitialize the scrambling "mostly as if" the user passed in the same `seed=` object again, then I would probably just avoid the deepcopy. This would get fresh `Generator`s each time when `seed=None` and would just continue to use the same `Generator` object when it was passed a `Generator` object. With a couple of fixups to recompute scrambling data for `Sobol` in the `reset()`, this would be actually be useful in cases like `qmc_quad()` where we want to repeat the same QMC setup, but with different scrambling in order to estimate the error. Right now, one just has to instantiate multiple `QMCEngine`s carefully. While I think this is a coherent set of semantics, it _is_ relatively complicated.

### Reproducing Code Example

```python
As above.
```

### Error message

```shell
As above.
```

### SciPy/NumPy/Python version and system information

```shell
1.8.0 1.21.2 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
```

**Comment by tupui** [comment]
Thank you for the report.

> When passed a Generator instance, it should spawn a child and store a deepcopy of it for later use in reset(). When passed seed=None, it should store a deepcopy of the instantiated Generator for the same purpose, not None.

I think this is what we want. I will work on that and improve the tests.
