### ISSUE TITLE
ENH: k-shortest path feature in scipy.sparse.csgraph?

### ISSUE THREAD

**Issue by chandrad** [scipy/scipy#18080]
### Is your feature request related to a problem? Please describe.

It's beneficial to have the K-shortest loopless path for a graph between two nodes with a non-negative edge cost in `scipy.sparse.csgraph`. This function would find the K shortest paths through a weighted graph using [Yen's algorithm](https://en.wikipedia.org/wiki/Yen%27s_algorithm).

Thank you for the contributions.

### Describe the solution you'd like.

Given a connected graph G, and two nodes, k (parameter of paths by user), directed/undirected, the method would give a list of k shortest paths between two nodes in ascending order of the total edge weight.

### Describe alternatives you've considered.

There are implementations in `Networkx` [shortest_simple_paths](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.simple_paths.shortest_simple_paths.html#networkx.algorithms.simple_paths.shortest_simple_paths) ; `igraph` [k_shortest_path](https://python.igraph.org/en/latest/api/igraph.GraphBase.html#get_k_shortest_paths); `Graphs.jl` [yen_k_shortest_paths](https://juliagraphs.org/Graphs.jl/dev/algorithms/shortestpaths/) latest variants of Yen's Algorithm listed [here](https://gitlab.inria.fr/dcoudert/k-shortest-simple-paths).

**Comment by rgommers** [comment]
Yen's paper has >400 citations, and that multiple other libraries have it is also a sign that this is a useful method. I think it easily meets the bar for inclusion in SciPy. gh-20187 looks promising.

**Comment by Kai-Striega** [comment]
I'm +1 on including this too.

**Comment by chandrad** [comment]
> Yen's paper has >400 citations, and that multiple other libraries have it is also a sign that this is a useful method. I think it easily meets the bar for inclusion in SciPy. [gh-20187](https://github.com/scipy/scipy/pull/20187) looks promising.

So is it going to be available in the upcoming version of Scipy?

**Comment by Kai-Striega** [comment]
It should be, yes, depending on if gh-20187 is merged in time

**Comment by Kai-Striega** [comment]
@chandrad It looks like this isn't going to be in 1.13 as we still need some time to review it more thoroughly and the branch for the 1.13 release will happen in the next few days. It should be in the 1.14 release (in 6 months time).
