### ISSUE TITLE
DOC: <Scaling due to window not clear for spectrum and density>

### ISSUE THREAD

**Issue by grigorishat** [scipy/scipy#18089]
### Issue with current documentation:

When I calculate the PSD with ```scaling = density``` and a hann and a boxcar window, the result differs by the factor of 1.5, which is due to the equivalent noise bandwidth. 

For the case of ```scaling = spectrum``` and different windows (hann vs. boxcar) the results are equal. Thus, it already scale the result with the equivalent noise bandwidth of 1.5.

If I compare density and scaling with the boxcar window, the result differs by the resolution of the frequency, known as well as bandwidth. If I compare it with a hann window, a factor of 1.5 is present. 

I attached the code and the plots for all four cases.

### Example:

```python
import numpy as np
import matplotlib.pyplot as plt
from scipy import signal

FREQ = 100000
f = 200
N = 1000
A = 10
#t = np.linspace(0,N/f,FREQ)

t = np.arange(0,N/f,1/FREQ)

p = A*np.sin(2*np.pi*f*t)

plt.plot(t,p)
plt.xlabel('TIME s in s')
plt.ylabel("PRESSURE in bar")
plt.xlim(0,.01)

f_box_PSD, P_box_PSD = signal.welch(p, FREQ, nperseg=200000, noverlap = 50000, window='box', scaling = 'density')
f_hann_PSD, P_hann_PSD = signal.welch(p, FREQ, nperseg=200000, noverlap = 50000, window='hann', scaling = 'density')

plt.plot(f_hann_PSD,P_hann_PSD, 'k') 
plt.plot(f_box_PSD+20,P_box_PSD, 'r') # offset of 20 Hz to see the difference 
plt.xlim(0,1000)
plt.ylabel("PSD")
plt.xlabel("FREQUENCY")
print(np.max(P_hann_PSD))
print(np.max(P_box_PSD))

f_box_PS, P_box_PS = signal.welch(p, FREQ, nperseg=200000, noverlap = 50000, window='box', scaling = 'spectrum')
f_hann_PS, P_hann_PS = signal.welch(p, FREQ, nperseg=200000, noverlap = 50000, window='hann', scaling = 'spectrum')

plt.plot(f_hann_PSD,P_hann_PSD, 'k') 
plt.plot(f_box_PSD+20,P_box_PSD, 'r') # offset of 20 Hz to see the difference 
plt.xlim(0,1000)
plt.ylabel("PSD")
plt.xlabel("FREQUENCY")
print(np.max(P_hann_PSD))
print(np.max(P_box_PSD))

f_box_PS, P_box_PS = signal.welch(p, FREQ, nperseg=200000, noverlap = 50000, window='box', scaling = 'spectrum')
f_hann_PS, P_hann_PS = signal.welch(p, FREQ, nperseg=200000, noverlap = 50000, window='hann', scaling = 'spectrum')

plt.plot(f_hann_PS,P_hann_PS, 'k')
plt.plot(f_box_PS+20,P_box_PS, 'r') # offset of 20 Hz to see the difference 
plt.xlim(0,1000)
plt.ylabel("PSD")
plt.xlabel("FREQUENCY")
print(np.max(P_hann_PS))
print(np.max(P_box_PS))

f_1, P_1 = signal.welch(p, FREQ, nperseg=200000, noverlap = 50000, window='box', scaling = 'density')
f_2, P_2 = signal.welch(p, FREQ, nperseg=200000, noverlap = 50000, window='box', scaling = 'spectrum')

plt.plot(f_1,P_1, 'k')
plt.plot(f_2+20,P_2, 'r') # offset of 20 Hz to see the difference 
plt.xlim(0,1000)
plt.ylabel("PSD")
plt.xlabel("FREQUENCY")
print(np.max(P_1))
print(np.max(P_2))
```

### Additional context (e.g. screenshots, GIFs)

![output1](https://user-images.githubusercontent.com/114856563/222755643-92cc05de-28e0-4bf1-9826-dc77db9f2760.png)
![output2](https://user-images.githubusercontent.com/114856563/222755647-2dfd5880-b8e5-4420-822c-d2d32c081c74.png)
![output3](https://user-images.githubusercontent.com/114856563/222755649-866b2af8-0d1d-454f-b5cc-e61426a49264.png)
![output4png](https://user-images.githubusercontent.com/114856563/222755653-87f21de0-2a02-4cbf-864d-c7cb0e659283.png)

**Comment by tupui** [comment]
Hi @grigorishat, thank you for reporting.

I am not sure I understand what you are suggesting as a documentation improvement. Could you clarify?

**Comment by grigorishat** [comment]
> Hi @grigorishat, thank you for reporting.
> 
> I am not sure I understand what you are suggesting as a documentation improvement. Could you clarify?

Thank you for the answer. You're right, I should it clarify. 

The scaling by the window function is to be described, but it is inconsistent when the scaling differs for the both cases, density vs. spectrum. Unless I have a mistake in thinking.

**Comment by DietBru** [comment]
It is not documented how a windowed "power spectrum" and a "power spectral density" is calculated. #19488 addresses that. The results in your example are consistent, but a bit tricky to interpret.
@grigorishat, do you think the documentation in #19488 is sufficient in that regard?
