### ISSUE TITLE
BUG: entropy calculations failing for large values

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#18093]
### Describe your issue.

For a few distributions, the entropy calculation currently fails for large values. As an example, consider the gamma distribution:
for $x>1e12$, the computed entropy starts to oscillate and after approx. `2e16`, returns just 0.

![image](https://user-images.githubusercontent.com/40656107/222923668-485d6cee-0fc8-4d65-b910-1c7293ec4e4f.png)

Affected distributions and current PRs that aim to fix it:

- [x]  `gamma` #18095
- [x]  `gengamma` #18131
- [x] `invgamma` #18122 
- [ ] `f`
- [x] `t` #18135 
- [ ] `beta` #18499 #18714 
- [x] `chi` #18094
- [x] `chi2` #17930
- [x] `genlogistic` #17930
- [ ] `wishart`
- [ ] `invwishart`
- [x] `multivariate_t` #18465 

The reason for the failures are catastrophic cancellations occuring in the subtraction of logarithmic beta/gamma functions `betaln`/`gammaln` on one side and the digamma function `psi` or simply `log` on the other side.

This can be avoided by using asymptotic expansions instead of calling the functions from `scipy.special`. See #17930 for examples.

The expansions for $\psi$ and $\ln(\Gamma)$ used in PRs such as #17929 are:

$$
\begin{align}
\psi(x) & \sim\ln(x) - \frac{1}{2x} - \frac{1}{12x^2}+\frac{1}{120x^4}-\frac{1}{252x^6} \\\
\ln(\Gamma(x)) &\sim x\ln(x)-x-\frac{1}{2}\ln(x)+\frac{1}{2}\ln(2\pi)+\frac{1}{12x}-\frac{1}{360x^3}+\frac{1}{1260x^5}
\end{align}
$$

For the beta function, expansions are listed on  [Wikipedia](https://en.wikipedia.org/wiki/Beta_function#Approximation):

If $x$ and $y$ are large:

$$
\begin{align}
B(x, y) & \sim\sqrt{2\pi}\frac{x^{x-1/2}y^{y-1/2}}{(x+y)^{x+y-1/2}} \\\
\ln(B(x, y)) & \sim \ln(\sqrt{2\pi})+(x-1/2)\ln(x)+(y-1/2)\ln(y)-(x+y-1/2)\ln(x+y)
\end{align}
$$

If one argument is large (here `y`, same holds for large `x` as `betaln` is symmetric):

$$
\begin{align}
B(x, y) & \sim\Gamma(x)y^{-x} \\\
\ln(B(x, y)) & \sim \ln(\Gamma(x)) - x\ln(y) \\\
\end{align}
$$

This issue can keep track of the necessary fixes.

### Reproducing Code Example

```python

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from mpmath import mp

mp.dps = 50

@np.vectorize
def gamma_entropy_reference(x):
    x = mp.mpf(x)
    return mp.digamma(x) * (mp.one - x) + x + mp.loggamma(x)

x = np.logspace(5, 20, 1000)
reference_entropy = np.array(gamma_entropy_reference(x), np.float64)
plt.semilogx(x, stats.gamma.entropy(x), label="scipy main")
plt.semilogx(x, reference_entropy, label="mpmath")
plt.legend(loc='upper left')
plt.xlabel("$x$")
plt.ylabel("$h$")
plt.ylim(0, 40)
plt.show()
```

### Error message

```shell
See plot above
```

### SciPy/NumPy/Python version and system information

```shell
current main branch
```

**Comment by MatteoRaso** [comment]
>If one argument is large (here y, same holds for large x as betaln is symmetric):

Just a heads up that this formula is wrong. You used the expansion used for large x on gammaln, when x is defined to not be large.

**Comment by dschmitz89** [comment]
> > If one argument is large (here y, same holds for large x as betaln is symmetric):
> 
> Just a heads up that this formula is wrong. You used the expansion used for large x on gammaln, when x is defined to not be large.

Thanks for finding, will correct it!

**Comment by mdhaber** [comment]
FYI technically these implementations don't really need to use `_lazywhere`. ISTM that `if.`...`else` would work fine because the distribution infrastructure apparently applies `np.vectorize` to `_entropy` before it is called, so `_entropy` only ever gets passed scalar arguments. But go ahead and keep using `_lazywhere` for now; the new infrastructure will take advantage of the inherent vectorization. (And it is not worth a fix or a an enhancement request. I'll track this in gh-15928,)

**Comment by dschmitz89** [comment]
@MatteoRaso : in case you are also still looking into this. I would like to use this to get more familiar with sympy, so if you dont mind I would finish the last two cases :).

**Comment by MatteoRaso** [comment]
> @MatteoRaso : in case you are also still looking into this. I would like to use this to get more familiar with sympy, so if you dont mind I would finish the last two cases :).

Yes, that sounds good. I'm a bit busy right now, so I wouldn't be able to handle this for a while, anyways.

**Comment by OmarManzoor** [comment]
Hi @dschmitz89 
Is there any among these that I could work on?

**Comment by dschmitz89** [comment]
> Hi @dschmitz89 Is there any among these that I could work on?

Yes definitely! I guess that `multivariate_t` is the easiest one to start out with. In the univariate case, Wolfram Alpha gave a very neat formula directly without any symbolic math effort of ourselves in [#18903](https://github.com/scipy/scipy/pull/18135).

**Comment by OmarManzoor** [comment]
> > Hi @dschmitz89 Is there any among these that I could work on?
> 
> Yes definitely! I guess that `multivariate_t` is the easiest one to start out with. In the univariate case, Wolfram Alpha gave a very neat formula directly without any symbolic math effort of ourselves in [#18903](https://github.com/scipy/scipy/pull/18135).

I see thank you. I'll have a look at that then as a start.

**Comment by OmarManzoor** [comment]
> > > Hi @dschmitz89 Is there any among these that I could work on?
> > 
> > 
> > Yes definitely! I guess that `multivariate_t` is the easiest one to start out with. In the univariate case, Wolfram Alpha gave a very neat formula directly without any symbolic math effort of ourselves in [#18903](https://github.com/scipy/scipy/pull/18135).
> 
> I see thank you. I'll have a look at that then as a start.

@dschmitz89 I tried using wolfram alpha and the output it returns is quite long. Could you kindly have a look to see if I have inputted this correctly. https://www.wolframalpha.com/input?i2d=true&i=%22asymptotic+expansion+-gammaln%5C%2840%29Divide%5B%5C%2840%29m%2Bd%5C%2841%29%2C2%5D%5C%2841%29+%2B+gammaln%5C%2840%29Divide%5Bd%2C2%5D%5C%2841%29+%2B+0.5+*+m+*+np.log%5C%2840%29d+*+np.pi%5C%2841%29+%2B+%5C%2840%29Divide%5B%5C%2840%29m%2Bd%5C%2841%29%2C2%5D%5C%2841%29+*+%5C%2840%29psi%5C%2840%29Divide%5B%5C%2840%29m%2Bd%5C%2841%29%2C2%5D%5C%2841%29+-+psi%5C%2840%29Divide%5Bd%2C2%5D%5C%2841%29%5C%2841%29%22
I left out the last term `+ 0.5 * shape_info.log_pdet` in the original formula when creating the equation.

**Comment by OmarManzoor** [comment]
Hi @dschmitz89 

I we want to handle the beta entropy
```python
def _entropy(self, a, b):
    return (sc.betaln(a, b) - (a - 1) * sc.psi(a) -
            (b - 1) * sc.psi(b) + (a + b - 2) * sc.psi(a + b))
```
 do we need to consider each of the three conditions for the expansions as mentioned in the description i.e.
- both a and b are large
- a is large
- b is large

**Comment by OmarManzoor** [comment]
> > Hi @dschmitz89
> > If we want to handle the beta entropy
> > ```python
> > def _entropy(self, a, b):
> >     return (sc.betaln(a, b) - (a - 1) * sc.psi(a) -
> >             (b - 1) * sc.psi(b) + (a + b - 2) * sc.psi(a + b))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > do we need to consider each of the three conditions separately for the expansions as mentioned in the description i.e.
> > 
> > * both a and b are large
> > * a is large
> > * b is large
> 
> Edit: I think we only need two cases. One if both arguments are large and one if only one argument is large. The formula is kind of "symmetric" so a→∞ yields the same formula as b→∞ if a and b are switched. CC @OmarManzoor

@dschmitz89 
For the case where only one of the arguments is large the expansion for betaln involves the gammaln term. So we need to substitute the expansion of gammaln as well right?

**Comment by dschmitz89** [comment]
> 

@OmarManzoor 
I think the problem is that the asymptotic expansion is very wrong for `digamma(a)` at `a=1`. Only for `b` it should be applied here, for `a` the regular `digamma` function is correct.

**Comment by OmarManzoor** [comment]
> > 
> 
> @OmarManzoor I think the problem is that the asymptotic expansion is very wrong for `digamma(a)` at `a=1`. Only for `b` it should be applied here, for `a` the regular `digamma` function is correct.

Thanks.

**Comment by OmarManzoor** [comment]
> > 
> 
> @OmarManzoor I think the problem is that the asymptotic expansion is very wrong for `digamma(a)` at `a=1`. Only for `b` it should be applied here, for `a` the regular `digamma` function is correct.

I tried this out by ignoring the - (a-1)*digamma(a) in the expansion

<Details>

```python
import sympy

from sympy import log, pi, sqrt, simplify, expand, Rational

x, y, a, b = sympy.symbols("x, y, a, b")

def digamma(x):
    return log(x) - 1/(2*x) - 1/(12*x**2) + 1/(120*x**4)

def gammaln(x):
    return x*log(x) - x - Rational(1,2)*log(x) + Rational(1,2)*log(2*pi) + 1/(12*x) - 1/(360*x**3)
    
def betaln(x, y):
    return gammaln(x) - x*log(y)

#old_1 = betaln(a, b) - (a - 1)*digamma(a) - (b - 1)*digamma(b) + (a + b - 2)*digamma(a+b)
old = betaln(a, b) - (b - 1)*digamma(b) + (a + b - 2)*digamma(a+b)

ref = simplify(simplify(simplify(old)))
ref
```
<img width="1358" alt="Screenshot 2023-06-16 at 7 50 54 PM" src="https://github.com/scipy/scipy/assets/17495884/272bc6e0-ec53-4f0d-b016-cdb57ae6b3fc">

I simplified this expression and added the - (a - 1) * psi(a) at the end

```python
def asymptotic_one_large(a, b):
    sm = a + b
    return (
        a*np.log(a) - a*(np.log(b) + 1) + (np.log(2*np.pi) - np.log(a)) / 2
        + (sm - 2) * (-1/(2*sm) - sm**-2.0/12 + np.log(sm) + sm**-4.0/120)
        - (b - 1) * (np.log(b) - 1/(2*b) - b**-2.0/12 + b**-4.0/120)
        + 1/(12*a) - a**-3.0/360
        - (a - 1) * psi(a)
    )

def beta_entropy_mpmath(a, b):
    a = mp.mpf(a)
    b = mp.mpf(b)
    entropy = mp.log(mp.beta(a, b)) - (a - 1) * mp.digamma(a) - (b - 1) * mp.digamma(b) + (a + b - 2) * mp.digamma(a + b)
    return float(entropy)

a, b = 1.0, 1e50
print(asymptotic_one_large(a, b))
print(beta_entropy_mpmath(a, b))

>>>0.08055555555555555
>>>-114.12925464970229

```

</Details>

The overall results seem to be really off. Could you kindly have a look?

**Comment by dschmitz89** [comment]
> > > 
> > 
> > 
> > @OmarManzoor I think the problem is that the asymptotic expansion is very wrong for `digamma(a)` at `a=1`. Only for `b` it should be applied here, for `a` the regular `digamma` function is correct.
> 
> I tried this out by ignoring the - (a-1)*digamma(a) in the expansion
> 
> ```python
> import sympy
> 
> from sympy import log, pi, sqrt, simplify, expand, Rational
> 
> x, y, a, b = sympy.symbols("x, y, a, b")
> 
> def digamma(x):
>     return log(x) - 1/(2*x) - 1/(12*x**2) + 1/(120*x**4)
> 
> def gammaln(x):
>     return x*log(x) - x - Rational(1,2)*log(x) + Rational(1,2)*log(2*pi) + 1/(12*x) - 1/(360*x**3)
>     
> def betaln(x, y):
>     return gammaln(x) - x*log(y)
> 
> #old_1 = betaln(a, b) - (a - 1)*digamma(a) - (b - 1)*digamma(b) + (a + b - 2)*digamma(a+b)
> old = betaln(a, b) - (b - 1)*digamma(b) + (a + b - 2)*digamma(a+b)
> 
> ref = simplify(simplify(simplify(old)))
> ref
> ```
> 
> <img alt="Screenshot 2023-06-16 at 7 50 54 PM" width="1358" src="https://user-images.githubusercontent.com/17495884/246451786-272bc6e0-ec53-4f0d-b016-cdb57ae6b3fc.png">
> I simplified this expression and added the - (a - 1) * psi(a) at the end
> 
> ```python
> def asymptotic_one_large(a, b):
>     sm = a + b
>     return (
>         a*np.log(a) - a*(np.log(b) + 1) + (np.log(2*np.pi) - np.log(a)) / 2
>         + (sm - 2) * (-1/(2*sm) - sm**-2.0/12 + np.log(sm) + sm**-4.0/120)
>         - (b - 1) * (np.log(b) - 1/(2*b) - b**-2.0/12 + b**-4.0/120)
>         + 1/(12*a) - a**-3.0/360
>         - (a - 1) * psi(a)
>     )
> 
> def beta_entropy_mpmath(a, b):
>     a = mp.mpf(a)
>     b = mp.mpf(b)
>     entropy = mp.log(mp.beta(a, b)) - (a - 1) * mp.digamma(a) - (b - 1) * mp.digamma(b) + (a + b - 2) * mp.digamma(a + b)
>     return float(entropy)
> 
> a, b = 1.0, 1e50
> print(asymptotic_one_large(a, b))
> print(beta_entropy_mpmath(a, b))
> 
> >>>0.08055555555555555
> >>>-114.12925464970229
> ```
> 
> The overall results seem to be really off. Could you kindly have a look?

We are confusing the arguments with each other. For large $b$, $\ln(\Gamma(a))$ must not be expanded. Let*s look at the original expansion from wiki:

![image](https://github.com/scipy/scipy/assets/40656107/62391668-0f17-4edf-b3d0-55acd897d372)

That means here we need to do:

$$
\begin{align}
\lim_{b\to\infty} h_{\beta}(a, b) & = \lim_{b\to\infty} \ln(\beta(a, b)) - (a -1)\psi(a) - (b-1)\psi(b) + (a+b-2)\psi(a+b) \\\\
& = \ln(\Gamma(a)) - a\ln(b) -(a-1)\psi(a)-(b-1)\psi_{exp}(b) + (a+b -2)\psi_{exp}(a+b) 
\end{align}
$$

where $\psi_{exp}$ denotes the asymptotic expansion of $\psi$.

**Comment by OmarManzoor** [comment]
@dschmitz89 

I tried this as well but it just does not seem to match. Here is the code

```python
from scipy.special import psi
from scipy.special import gammaln

def asymptotic_one_large(a, b):
    s = a + b
    t1 = gammaln(a) - a*np.log(b) - (a - 1)*psi(a)
    t2 = np.log(b) - b*np.log(b) - 1/(2*b) + 1/(12*b) - b**-2./12
    t3 = a*np.log(s) + b*np.log(s) - 2*np.log(s) - 1/(12*s) + 1/s + s**-2./6
    return t1 + t2 + t3

def beta_entropy_mpmath(a, b):
    a = mp.mpf(a)
    b = mp.mpf(b)
    entropy = mp.log(mp.beta(a, b)) - (a - 1) * mp.digamma(a) - (b - 1) * mp.digamma(b) + (a + b - 2) * mp.digamma(a + b)
    return float(entropy)

a, b = 2.0, 1e20
print(asymptotic_one_large(a, b))
print(beta_entropy_mpmath(a, b))

>>>0.0
>>>-44.47448619497938
```

By the way if I define asymptotic_one_large like this by returning the value at once instead of keeping it in t1,t2,t3 and then adding, the result is completely different
```python

def asymptotic_one_large(a, b):
    s = a + b
    return (
        gammaln(a) - a*np.log(b) - (a - 1)*psi(a)
        + np.log(b) - b*np.log(b) - 1/(2*b) + 1/(12*b) - b**-2./12
        + a*np.log(s) + b*np.log(s) - 2*np.log(s) - 1/(12*s) + 1/s + s**-2./6
    )

a, b = 2.0, 1e20
print(asymptotic_one_large(a, b))
print(beta_entropy_mpmath(a, b))

>>>-92.10340371976183
>>>-44.47448619497938

```

**Comment by dschmitz89** [comment]
I found a way around the catastrophic cancellations that occur in the logarithmic terms.

```python

from scipy.special import psi
from scipy.special import gammaln
from mpmath import mp
import numpy as np

mp.dps = 100

def asymptotic_one_large(a, b):
    s = a + b
    simple_terms = gammaln(a) - (a -1)*psi(a) - 1/(2*b) + 1/(12*b) - b**-2./12 - 1/(12*s) + 1/s + s**-2./6
    difficult_terms = s * np.log1p(a/b) + np.log(b) - 2 * np.log(s) #np.log(b) * (1 - s) + (s - 2) * np.log(s)

    return simple_terms + difficult_terms

def beta_entropy_mpmath(a, b):
    a = mp.mpf(a)
    b = mp.mpf(b)
    entropy = mp.log(mp.beta(a, b)) - (a - mp.one) * mp.digamma(a) - (b - mp.one) * mp.digamma(b) + (a + b - 2*mp.one) * mp.digamma(a + b)
    return float(entropy)

a, b = 20, 1e20
print(asymptotic_one_large(a, b))
print(beta_entropy_mpmath(a, b))

>>> -43.151773525282245
>>> -43.15177352528225
``` 

The trick is to write  $\ln(a+b)-\ln(b)=\ln((b+a)/b)=\ln(1+a/b)=log1p(a/b))$
That way the above labeled "difficult terms" can be calculated accurately:

```python

a, b = 20., 1e20
s = a+b
np.log(b) * (1 - s) + (s - 2) * np.log(s), s * np.log1p(a/b) + np.log(b) - 2 * np.log(s)

>>> (0.0, -26.051701859880907)
```

**Comment by OmarManzoor** [comment]
> @OmarManzoor sorry for all this back and forth. I found a way around the catastrophic cancellations that occur in the logarithmic terms finally.
> 
> ```python
> from scipy.special import psi
> from scipy.special import gammaln
> from mpmath import mp
> import numpy as np
> 
> mp.dps = 100
> 
> def asymptotic_one_large(a, b):
>     s = a + b
>     simple_terms = gammaln(a) - (a -1)*psi(a) - 1/(2*b) + 1/(12*b) - b**-2./12 - 1/(12*s) + 1/s + s**-2./6
>     difficult_terms = s * np.log1p(a/b) + np.log(b) - 2 * np.log(s) #np.log(b) * (1 - s) + (s - 2) * np.log(s)
> 
>     return simple_terms + difficult_terms
> 
> def beta_entropy_mpmath(a, b):
>     a = mp.mpf(a)
>     b = mp.mpf(b)
>     entropy = mp.log(mp.beta(a, b)) - (a - mp.one) * mp.digamma(a) - (b - mp.one) * mp.digamma(b) + (a + b - 2*mp.one) * mp.digamma(a + b)
>     return float(entropy)
> 
> a, b = 20, 1e20
> print(asymptotic_one_large(a, b))
> print(beta_entropy_mpmath(a, b))
> 
> >>> -43.151773525282245
> >>> -43.15177352528225
> ```
> 
> The trick is to write ln⁡(a+b)−ln⁡(b)=ln⁡((b+a)/b)=ln⁡(1+a/b)=log1p(a/b)) That way the above labeled "difficult terms" can be calculated accurately:
> 
> ```python
> a, b = 20., 1e20
> s = a+b
> np.log(b) * (1 - s) + (s - 2) * np.log(s), s * np.log1p(a/b) + np.log(b) - 2 * np.log(s)
> 
> >>> (0.0, -26.051701859880907)
> ```

Very nice! Thank you for this.

**Comment by mdhaber** [comment]
I was curious whether anyone could share an example use of the numerical value of the entropy of a distribution. The concept of differential entropy is used all over, of course, but I haven't been able to find examples where the entropy of a named distribution (like one of those named above) is used. Thanks for considering it!

**Comment by dschmitz89** [comment]
Closing for some time until more reviewer capacity is available.
