### ISSUE TITLE
in boxcox     raise ValueError("Data must be 1-dimensional.") ValueError: Data must be 1-dimensional.

### ISSUE THREAD

**Issue by TheFoolFred1** [scipy/scipy#18100]
I would appreciate some guidance on this.

When I un-comment the first "data =" line, the following code does what I want which is to display the original data next to the transformed data.  However, every time I try to read real data into the program from an Excel spreadsheet it throws the "Data must be 1-dimensional" error.  The spreadsheet only has one tab with one column of numbers.

Printing the data shows me that the data from the data generated from stats.lognom.rvs is just comma delimited numbers while the data from the Pandas read is a column.  Both seem 'one dimensional' to me, but of course, I am not the program.  Is there something I have to do to condition the imported data?

Thanks in advance for any insights you can bless me with.

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import pandas as pd

# data generation
np.random.seed(42)
#data = sorted(stats.lognorm.rvs(s=0.5,loc=1, scale = 1000, size = 1000))
data = pd.read_excel('C:\\Users\Owner\AppData\Local\Programs\Python\CycleData2.xlsx')

print(data)

#perform Box-Cox transformation on original data
transformed_data, best_lamda = stats.boxcox(data)

#transformed_data.sort

# visualize

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(8, 4))

ax1.hist(data, bins='auto', density=False)
ax1.set_ylabel('probability')
ax1.set_title('Linear Scale')

ax2.hist(transformed_data, 'auto', density=False)
ax2.set_xscale('log')
ax2.set_title('Log Scale');

print(best_lamda)

plt.show();

**Comment by mdhaber** [comment]
[`pd.read_excel`](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html) returns a `DataFrame`, which is a 2D array-like object, regardless of how many columns it has. You need to extract the 1D column you're interested in (e.g. as a `Series` or even better - as an array) before passing it into `boxcox`.

**Comment by TheFoolFred1** [comment]
Okay, I found the problem and fixed it.  It was primary ignorance but in that I spent a lot of time seeking the answer (which proved simple), I thought I should post it just in case someone else is at the same point I was on the learning curve and bumps into this.

imported = pd.read_excel('C:\\Users\Owner\AppData\Local\Programs\Python\CycleData2.xlsx',index_col = 0, header=None)
data = imported.index.values
