### ISSUE TITLE
BUG: sparse.csr_array.argmax() returns 2D numpy.matrix instead of 1D numpy.ndarray

### ISSUE THREAD

**Issue by jni** [scipy/scipy#18111]
### Describe your issue.

If I understand correctly, the idea behind the new sparse `*_array` classes implemented in #14822 was to produce objects that behaved like NumPy arrays rather than NumPy matrices. (If that is *not* the idea, then close this issue. 😂) However, currently, some methods/array-functions return dense arrays, some returns 2D sparse arrays, and some return dense 2D `numpy.matrix` objects. This is confusing. 😅 

### Reproducing Code Example

```python
import numpy as np
from scipy import sparse

dense_arr = np.array([[0, 1, 0], [2, 0, 1]])
sparse_arr = sparse.csr_array(dense_arr)

results = {}

results['sum'] = sparse_arr.sum(axis=1)
results['np.sum'] = np.sum(sparse_arr, axis=1)

results['max'] = sparse_arr.max(axis=1)
results['np.max'] = np.max(sparse_arr, axis=1)

results['argmax'] = sparse_arr.argmax(axis=1)
results['np.argmax'] = np.argmax(sparse_arr, axis=1)

for func, result in results.items():
    type_ = type(result)
    shape = result.shape
    print(f'{func}: {type_.__module__}.{type_.__name__}, {shape=}')
```

### Error message

```shell
Output:


sum: numpy.ndarray, shape=(2,)
np.sum: numpy.ndarray, shape=(2,)
max: scipy.sparse._arrays.coo_array, shape=(2, 1)
np.max: scipy.sparse._arrays.coo_array, shape=(2, 1)
argmax: numpy.matrix, shape=(2, 1)
np.argmax: numpy.matrix, shape=(2, 1)
```

### SciPy/NumPy/Python version and system information

```shell
1.8.1 1.22.4 sys.version_info(major=3, minor=10, micro=5, releaselevel='final', serial=0)
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
flame_info:
  NOT AVAILABLE
accelerate_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/Users/jni/conda/envs/all/lib']
    language = f77
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/Users/jni/conda/envs/all/lib']
    include_dirs = ['/Users/jni/conda/envs/all/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/Users/jni/conda/envs/all/lib']
    include_dirs = ['/Users/jni/conda/envs/all/include']
    language = c
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/Users/jni/conda/envs/all/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jni/conda/envs/all/include']
Supported SIMD extensions in this NumPy install:
    baseline = NEON,NEON_FP16,NEON_VFPV4,ASIMD
    found = ASIMDHP,ASIMDDP
    not found =
```

**Comment by perimosocordiae** [comment]
Thanks for flagging this. We should definitely not be returning np.matrix objects from any of the new sparse array classes.

**Comment by jni** [comment]
@perimosocordiae thanks for reassuring me! 😂 

I would also suggest that `*_array`s should behave like NumPy arrays, in which case, probably the marginal results `ufunc(..., axis=1)` or `ufunc(..., axis=0)` should be 1D, which currently means it should be dense? Or maybe sparse 1D arrays are not so hard to hack based on the current code base?

To put it another way, `np.matrix` from argmax was *very* surprising, but (2, 1) coo_matrix from max is still a bit surprising. Only the 1D array from sum is expected. (From me, anyway 😅)

**Comment by jni** [comment]
@perimosocordiae @tylerjereddy thanks for the quick fix!

Should I open a new issue to discuss my other points above, about the dimensionality of the result?

**Comment by perimosocordiae** [comment]
As of now the sparse array classes only support two-dimensional shapes, but we are planning to support 1d sparse arrays soon(ish). Once we do, we'll be able to clean up several of these inconsistencies.
