### ISSUE TITLE
BUG: <scipy.interpolate.SmoothSphereBivariateSpline gives constant output for non-constant input>

### ISSUE THREAD

**Issue by dosoe** [scipy/scipy#18110]
### Describe your issue.

I use `scipy.interpolate.SmoothSphereBivariateSpline` to interpolate points on a sphere, but the interpolation fails in the sense that the resulting function does not interpolate the points at all, regardless of smoothing. I provide an example where I try to interpolate the points `(0,0,-1)`,`(0,90,-1)`,`(0,-90,-1)`,`(90,0,1)`,`(180,0,-1)`,`(270,0,1)` (represented as lon-lat-value, but I do the necessary conversions in the code example) with a smoothing of 10. This should give a central meridian at -1. , an identic antipode and two zones around 1. at 90° east and west of 0 respectively. This is not what the interpolator gives: it provides a uniform value of around -0.3. Is there something that I fundamentally not understand on how scipy.interpolate works? The first figure shows the distribution and values of the input points, the second figure the output of the interpolator on a regular grid, plotted on a world map using cartopy. 
![test_points](https://user-images.githubusercontent.com/25985080/223283410-26ee1892-8056-445c-8cb5-531015432d89.png)
![test_grid](https://user-images.githubusercontent.com/25985080/223283408-9281cb61-9578-4d48-95a5-0c4074919a34.png)

### Reproducing Code Example

```python
from scipy.interpolate import SmoothSphereBivariateSpline
import numpy as np
conf_lon=np.deg2rad(np.array([0,0,0,90,180,270]))
conf_lat=np.deg2rad(np.array([0,90,-90,00,00,00]))
values_for_this_rad=np.array([-1,-1,-1,1,-1,1])
# convert to colatitude
colats_decim = (np.pi/2)-conf_lat
lons_decim   = conf_lon
interpolator = SmoothSphereBivariateSpline(theta=colats_decim, phi=lons_decim,
                                           r=values_for_this_rad,
                                           s=10)
# interpolator is basically a constant function
print(interpolator.get_knots(),interpolator.get_coeffs())

# plotting
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import matplotlib.colors as colors

# plot input of interpolator
fig = plt.figure(figsize=(14, 10))
ax = fig.add_subplot(1, 1, 1,projection=ccrs.Robinson(central_longitude=0))
ax.set_global()
im = ax.scatter(np.rad2deg(conf_lon), np.rad2deg(conf_lat), c=values_for_this_rad,transform=ccrs.PlateCarree(), norm=colors.CenteredNorm())
ax.coastlines()
fig.colorbar(im, ax=ax, location='bottom')

# plot output of interpolator on a regular grid
fig2 = plt.figure(figsize=(14, 10))
ax2 = fig2.add_subplot(1, 1, 1,projection=ccrs.Robinson(central_longitude=0))
ax2.set_global()
lon,lat=np.meshgrid(np.arange(360),np.arange(-90,90))
lon=lon.flatten()
lat=lat.flatten()
values=[]
for i in range(len(lon)):
    values.append(interpolator((np.pi/2)-np.deg2rad(lat)[i],np.deg2rad(lon)[i]))
im = ax2.scatter(lon, lat, c=values,transform=ccrs.PlateCarree(), norm=colors.CenteredNorm())
ax2.coastlines()
fig2.colorbar(im, ax=ax2, location='bottom')
plt.show()
```

### Error message

```shell
No error message
code output: 
(array([0.        , 0.        , 0.        , 0.        , 3.14159265,
       3.14159265, 3.14159265, 3.14159265]), array([0.        , 0.        , 0.        , 0.        , 6.28318531,
       6.28318531, 6.28318531, 6.28318531])) [-0.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333
 -0.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333 -0.33333333
 -0.33333333 -0.33333333 -0.33333333 -0.33333333]
```

### SciPy/NumPy/Python version and system information

```shell
1.10.1 1.24.2 sys.version_info(major=3, minor=11, micro=0, releaselevel='final', serial=0)
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
flame_info:
  NOT AVAILABLE
accelerate_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/home/gcl/BR/d.soergel/anaconda3/envs/mergemod/lib']
    language = f77
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/gcl/BR/d.soergel/anaconda3/envs/mergemod/lib']
    include_dirs = ['/home/gcl/BR/d.soergel/anaconda3/envs/mergemod/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/gcl/BR/d.soergel/anaconda3/envs/mergemod/lib']
    include_dirs = ['/home/gcl/BR/d.soergel/anaconda3/envs/mergemod/include']
    language = c
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/gcl/BR/d.soergel/anaconda3/envs/mergemod/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/gcl/BR/d.soergel/anaconda3/envs/mergemod/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2,AVX512F,AVX512CD,AVX512_SKX
    not found = AVX512_KNL,AVX512_KNM,AVX512_CLX,AVX512_CNL,AVX512_ICL
```

**Comment by tupui** [comment]
Hi @dosoe, thank you for reporting. From the doc, the order is important so my guess is that it simply does not like the wrapping on lat. Did you try to play with that? What else did you try?

**Comment by dosoe** [comment]
I initially tried with a more complex dataset that covered the whole globe with a regular grid that had a point on the south pole, but not the north pole. The initial data is basically zero except in an area on the south-west pacific, so there shouldn't be singularity problems. I just ran a second test with no points on the south pole, it doesn't help. The two plots show the initial data and the data as interpolated on a regular grid using the interpolator. 
![test_plot_compute_operator_0](https://user-images.githubusercontent.com/25985080/223298071-4ea2f191-8345-4ec9-a10e-1072c31ad28c.png)
![test_interpolator_0](https://user-images.githubusercontent.com/25985080/223298110-9cee83b1-266e-40fb-9899-92fb135ef428.png)

**Comment by dosoe** [comment]
The docs don't specify an order, they just say the points should be between 0 and pi and 0 and 2pi respectively (which is the case, I tried switching ad it throws an error). The points are as three lists of colatitude, longitude and value, I do not see anything mentioned in the documentation about order (you mean order of the points or if I do a complete wraparound?).

**Comment by tupui** [comment]
The doc says `1-D sequences of data points (order is not important)`. I am just suggesting to have a look at this.

Also I would suggest to start from the example of the doc (which should be correct) and see how you can gradually change it to your needs. That will help to see where is the issue (either with SciPy or your use of it.)

**Comment by dosoe** [comment]
Thank you. I will have a look at this, but it is late where I live, so it will be tomorrow.

**Comment by tupui** [comment]
No worries (and same here 😉)

**Comment by ev-br** [comment]
Where does the value of `s=10`  come from? It may rather drastically affect the result, so I'd also play with it (in a way Pamphile suggested above, starting from a simple example).

**Comment by dosoe** [comment]
I have played with it, setting it at 1, 10 or 100 with no noticeable change. I'm trying to reproduce the problem right now, obviously the code I sent doesn't work, but the example from the documentation doesn't.

**Comment by dosoe** [comment]
Ok, so it increasingly looks like the smoothing was too high, I should have set it for a lower value (more like 0.1 or 0.001). I will come back to you if it is not the case.
