### ISSUE TITLE
ENH: Simple constraints for direct and dual_annealing

### ISSUE THREAD

**Issue by lesshaste** [scipy/scipy#18126]
### Is your feature request related to a problem? Please describe.

Some of the global optimizers in scipy support constraints.  basinhopping can use constraints if you use minimizer_kwargs={"bounds": bounds, "constraints": cons, "method": "SLSQP"} for example. differential_evolution has constraints as an argument as does shgo. However neither dual_annealing nor direct has support for constraints as far as I can tell.

### Describe the solution you'd like.

Support for constraints to be added to direct and dual_annealing

**Comment by dschmitz89** [comment]
I see the value this would bring, but how would we implement constraints for these algorithms? At least, for DIRECT I do not see a way to do it. Apart from that, digging through DIRECT's C codebase gets very ugly very quickly.

For `dual_annealing`, I also do not see an elegant way to restrict the sampler to a certain region. `differential_evolution` simply repositions candidate solutions that evolve outside the feasible space randomly inside the feasible region. If that is a viable strategy for other algorithms, is debatable.

One thing that comes to mind is the [augmented Langrangian](https://en.wikipedia.org/wiki/Augmented_Lagrangian_method) to adapt the objective function. This is for example available in nlopt to make all solvers work with constraints.

**Comment by lesshaste** [comment]
The augmented Lagrangian method seems very attractive if there are any scipy devs with the right expertise. Do you think there are?

**Comment by dschmitz89** [comment]
PR welcome but typically this also needs to be discussed on the mailing list first.
