### ISSUE TITLE
DOC: optimize.differential_evolution, example use of constraints and vectorized

### ISSUE THREAD

**Issue by Pi9GW** [scipy/scipy#18155]
### Issue with current documentation:

Current documentation is a bit too terse regarding use of constraints and vectorized.

### Idea or request for content:

A minimum code example of both would be an excellent addition.

**Comment by tupui** [comment]
Hi @Pi9GW thank you for reporting. I am going to close the issue because we do already have multiple similar issues and a bit tracking one about adding more examples. Hence leaving this one open does not help.
