### ISSUE TITLE
ENH: stats.vonmises.pdf: return 1/(2pi) when kappa=0

### ISSUE THREAD

**Issue by jdrugo** [scipy/scipy#18166]
### Describe your issue.

The probability density function a `scipy.stats.vonmises` returns `nan` when called with `kappa = 0`, whereas it should return ~0.159.

The `_pdf` method of the `vonmises_gen` class in `_continuous_distns.py` should return the correct results. My guess is that things go wrong in the `pdf` method of the `rv_continous` in `_distn_infrastructure.py`, where `scale = 0` is treated as a special case.

I tried to write a patch that fixes this, but don't have enough insight into the details of distribution handling in `scipy` to not potentially screw up some other distributions.

### Reproducing Code Example

```python
import scipy.stats
print(scipy.stats.vonmises.pdf(x=0, kappa=1))
print(scipy.stats.vonmises.pdf(x=0, kappa=0))
```

### Error message

```shell
0.3417104886234632
nan
```

### SciPy/NumPy/Python version and system information

```shell
1.9.1 1.23.3 sys.version_info(major=3, minor=10, micro=10, releaselevel='final', serial=0)
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/arm64-builds/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/opt/arm64-builds/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/arm64-builds/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/opt/arm64-builds/lib']
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/arm64-builds/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/opt/arm64-builds/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/opt/arm64-builds/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/opt/arm64-builds/lib']
```

**Comment by mdhaber** [comment]
The `vonmises` documentation states that the implementation is valid for $\kappa > 0$

![image](https://user-images.githubusercontent.com/6570539/225983932-53801a87-978c-4b0d-abd0-501b41510793.png)

So I have converted this to an enhancement request.

You are welcome to submit a PR that adjusts the definition of `pdf`. You should only need to change the `vonmises_gen._pdf` method in `_continuous_distns.py`. No changes involving the distribution infrastructure (e.g. `rv_continuous` in `distn_infrastructure.py` should be required.) The `scale` parameter is known to be broken and will be fixed as part of another effort this summer.

**Comment by jdrugo** [comment]
Thank you. I just noticed the $\kappa > 0$ restriction in the documentation. As it turns out, `vonmises_gen._pdf` already returns the correct density for `kappa = 0`, so no change is required. It just never seems to get called from `rv_continuous.pdf` for `kappa = 0`, as, in this case, `scale = 0`, which gets treated as a special case.

**Comment by mdhaber** [comment]
Mm... I'll look into it.

**Comment by mdhaber** [comment]
We just need to define an `_argcheck` method for `vonmises`.
