### ISSUE TITLE
MAINT: more consistent API for multivariate interpolation

### ISSUE THREAD

**Issue by gjhuizing** [scipy/scipy#18165]
### Is your feature request related to a problem? Please describe.

Overall the different interpolators have inconsistent names for the same things. For example, the classes `LinearNDInterpolator`, `NearestNDInterpolator`, `CloughTocher2DInterpolator` and `RBFInterpolator` have the following constructors:

- `LinearNDInterpolator(points, values, fill_value=np.nan, rescale=False)`
- `NearestNDInterpolator(x, y, rescale=False, tree_options=None)`
- `CloughTocher2DInterpolator(points, values, fill_value=nan, tol=1e-06, maxiter=400, rescale=False)`
- `RBFInterpolator(y, d, neighbors=None, smoothing=0.0, kernel='thin_plate_spline', epsilon=None, degree=None)`

Those are three different ways to name `points, values`, and `y` is used both to mean `point` and `values`. Also, `LinearNDInterpolator` uses `np.nan` where `CloughTocher2DInterpolator` uses `nan`.

These 4 interpolators also have different conventions in the documentation to refer to the shapes of the input, respectively:
- `(npoints, ndims)`
- `(Npoints, Ndims)`
- `(npoints, ndims)`
- `(P, N)`

### Describe the solution you'd like.

I think the API could be unified a bit, in particular using the convention `points, values` when possible, and settling on a way to name the dimensions. Happy to draft a PR on this.

### Additional context (e.g. screenshots, GIFs)

- https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.LinearNDInterpolator.html#scipy.interpolate.LinearNDInterpolator
- https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.NearestNDInterpolator.html#scipy.interpolate.NearestNDInterpolator
- https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.CloughTocher2DInterpolator.html#scipy.interpolate.CloughTocher2DInterpolator
- https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RBFInterpolator.html#scipy.interpolate.RBFInterpolator

**Comment by tupui** [comment]
Hi @gjhuizing, thank you for reporting.

I am afraid that it's a complicated problem to solve. We cannot change the APIs as we want for backward compatibility reasons. Doing some renaming or change or parameters order would break older code.

In the end we try as much as we can to reduce users' churn and only change the API when there is an issue to address. When we do, we try to limit such things and when we do, we set a deprecation period.

I am not opposed to some uniformization, but this needs clear planing and justification on why we should do it, how, etc.

**Comment by gjhuizing** [comment]
Hi @tupui that's fair! Maybe the docs could still be changed at some point (`Npoints` vs `P` vs `npoints`) but that's of course quite a minor issue.

**Comment by tupui** [comment]
Documentation improvements are always welcomed. Would you like to propose a PR?

**Comment by gjhuizing** [comment]
Sure, happy to contribute! Should I just get started and link the PR here when it's ready?

**Comment by tupui** [comment]
Yes exactly, and if you have questions don't hesitate to ask. Thank you 🙌 

In 2 weeks (Friday) we have a newcomers meeting if that's of interest to you.

**Comment by ev-br** [comment]
Making argument names more uniform would be great indeed, if possible.
The process for renaming a public argument is 
- add a new argument (to the end of the arg list to keep backcompat)
- emit deprecation warnings on using non-default values for an "old" parameter
- after at least two scipy releases, remove the old parameter

This does not apply to `nan` vs `np.nan` difference: this is the same thing, only printed differently.  Given that the repr for np.nan is `nan`:

```
>>> import numpy as np
>>> np.nan
nan
```

I guess it makes more sense to follow numpy and spell it just `nan`.

**Comment by gjhuizing** [comment]
@ev-br sounds like a reasonable process! In this case it's a positional argument with no default value though. Would the process then involve giving None as a default value?

**Comment by ev-br** [comment]
Possibly.
However, as Pamphile said, it needs some written planning and motivation to justify the churn. My personal assessment is -0 , meaning I'm not going to work on this myself but will not oppose if a motivated individual (you?) pushes it through.

**Comment by gjhuizing** [comment]
Thanks for the input! I wouldn't want to push too hard for something as a first time contribution. So I'll start with a documentation PR and see if I can get traction for the more ambitious API change.

**Comment by ev-br** [comment]
Superb. Looking forward for that PR then!

**Comment by AtsushiSakai** [comment]
I think a documentation update was introduced in #18413, so I think we can close this issue. If any other improvement is needed, please add a comment here and reopen this.
