### ISSUE TITLE
BUG: scipy.stats.logistic.fit() returns negative `scale`

### ISSUE THREAD

**Issue by tvoipio** [scipy/scipy#18176]
### Describe your issue.

Fitting a logistic distribution to data using `scipy.stats.logistic.fit()` returns a negative value for the scale parameter for some input data. Changing the sign of the result and using it as the initial guess for the next `fit()` returns practically the same result as the input values.

The issue happens on versions 1.9.1 and 1.10.1, but based on blame the current head of development has exactly the same code as 1.10.1 does, https://github.com/scipy/scipy/blame/v1.10.1/scipy/stats/_continuous_distns.py#L5341-L5448

It seems that the analytic solution for location and scale parameters involve an even function with respect to scale: https://github.com/scipy/scipy/blob/main/scipy/stats/_continuous_distns.py#L5725-L5727 - although I have not quite worked out how the sign flip does not mess up the `loc` parameter equation.

Maybe the solution should be constrained to strictly positive values of `scale`? We worked around the issue by rerunning `fit()` using `(loc, -scale)` as the initial guess if the first `fit()` returned `scale < 0`, but this might not be ideal. It seems that even in general, the analytical formulas (especially indirect ones relying on finding roots) should explicitly constrain the output values to valid ranges in https://github.com/scipy/scipy/issues/11782 ?

### Reproducing Code Example

```python
import numpy as np
import scipy

data = np.array([-459, 37, 43, 45, 45, 48, 54, 55, 58] + [59] * 3 + [61] * 9)
params = scipy.stats.logistic.fit(data)
print(f"SciPy version: {scipy.__version__}")
print(f"Params (loc, scale): {params}")
```

### Error message

```shell
(none)
```

### SciPy/NumPy/Python version and system information

```shell
1.10.1 1.23.5 sys.version_info(major=3, minor=10, micro=9, releaselevel='final', serial=0)
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
flame_info:
  NOT AVAILABLE
accelerate_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/home/[REDACTED]/miniconda3/envs/[ENV_REDACTED]/lib']
    language = f77
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/[REDACTED]/miniconda3/envs/[ENV_REDACTED]/lib']
    include_dirs = ['/home/[REDACTED]/miniconda3/envs/[ENV_REDACTED]/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/[REDACTED]/miniconda3/envs/[ENV_REDACTED]/lib']
    include_dirs = ['/home/[REDACTED]/miniconda3/envs/[ENV_REDACTED]/include']
    language = c
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/home/[REDACTED]/miniconda3/envs/[ENV_REDACTED]/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/[REDACTED]/miniconda3/envs/[ENV_REDACTED]/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2,AVX512F,AVX512CD,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
    not found = AVX512_KNL,AVX512_KNM
```

**Comment by mdhaber** [comment]
Thanks for reporting. I'll take a look.

**Comment by mdhaber** [comment]
Usually we don't override the generic fit unless there is an explicit formula or we can use a bracketing root finders, which constrains the solution. Here, we used `root`, which doesn't accept constraints, because there are two equations to solve simultaneously. I don't immediately see how to solve for one parameter in terms of the other, but there are a few other options (e.g. see if it tolerates using the absolute value of scale, or use a minimizer that accepts bounds to solve the equation). I will also convert the fixed location and fixed scale cases to use a bracketing root finder.

**Comment by WarrenWeckesser** [comment]
The first order equation for the scale is even, so if `(loc, scale)` is a solution, then so is `(loc, -scale)`.  So a possible fix is to let the solver do what it does, and always return the absolute value of the scale.  I just added the function `mle()` to `mpsci.distributions.logistic`, and that's how I handle the possibility of the solver finding the solution with a negative scale: https://github.com/WarrenWeckesser/mpsci/blob/f16718661c56875862c728d957693d552ad6b290/mpsci/distributions/logistic.py#L177-L187

**Comment by WarrenWeckesser** [comment]
Yes; in terms of the code in `logistic.fit`, `dl_dloc` is odd in `scale`, and `dl_dscale` is even in `scale`.  The latter is clear from `tanh` being odd.  The former is clear if the equation is expressed in terms of `tanh` instead of `expit`, but to derive the result using `expit`, first note that changing the sign of the scale changes the sign of `c = (data - loc)/scale`, and that `expit(-x) = 1 - expit(x)`.  Let `f(c) = sum(expit(c)) - n/2`. Then

    f(-c) = sum(expit(-c)) - n/2
          = sum(1 - expit(c)) - n/2
          = n - sum(expit(c) - n/2
          = -sum(expit(c) + n/2
          = -f(c)

**Comment by tvoipio** [comment]
Awesome, thanks!
