### ISSUE TITLE
Using ODR in multiple regression - what if one independent variable has no uncertainty?

### ISSUE THREAD

**Issue by JSAnandEOS** [scipy/scipy#18185]
Is it possible to use `scipy.odr` to fit a model where one of the independent variables is perfectly known (e.g. date of measurement), and so has no corresponding `sx`?

Here's some example code: 

```
import numpy as np
from scipy import odr

def model_test(B, x):

 x_0, x_1 = x[0], x[1]

 return B[0]*x_0 + B[1]*x_1**2 + B[2]
 
N = 1000
x_0 = np.linspace(0, 100, N)
x_1 = np.linspace(0, 100, N)

x = np.row_stack([x_0, x_1])
sx = np.row_stack([np.full(N, 0.0), np.random.random(N)])
sy = np.random.random(N)

y = model_test([3.0, 4.0, 5.0], x)

model = odr.Model(model_test)

data = odr.RealData(x = x, y = y, sx = sx, sy = sy)

odr_test = odr.ODR(data = data, model = model, beta0 = [1.0, 2.0, 3.0])

output = odr_test.run()

output.pprint()
```

`y` and `x_1` have errors associated with them, but `x_0` does not. I've tried representing this by using an array of zeros. However, I get a divide by zero error when I implement the above code:

```
RuntimeWarning: divide by zero encountered in true_divide
  return 1./numpy.power(sd, 2)
Beta: [nan nan nan]
Beta Std Error: [0. 0. 0.]
Beta Covariance: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Residual Variance: 0.0
Inverse Condition #: 0.001067101765072725
Reason(s) for Halting:
  Numerical error detected
```
Is this caused by an error on my part, or is ODR not suitable for this problem? What should I use instead if ODR is not the right solution to my problem?

**Comment by rkern** [comment]
Use the [`ifixx` parameter to `ODR`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.odr.ODR.html) to specify which of the `x` entries are allowed to vary. Use nominal non-zero values for `sx` to avoid 0/0.

```python
sx = np.row_stack([np.full(N, 1.0), np.random.random(N)])
ifixx = np.ones(x.shape, dtype=int)
ifixx[0, :] = 0
```
