### ISSUE TITLE
Questions about scipy.odr

### ISSUE THREAD

**Issue by Federico2111** [scipy/scipy#18183]
scipy.odr: https://docs.scipy.org/doc/scipy/reference/odr.html

I am not sure if this library does an orthogonal distance regression (ODR) or a weighted orthogonal distance regression (WODR), which are not the same thing.
I could read in the literature that the ODR is used when the ratio between the x and y error variances is constant over the range of data, while the WODR is used when this assumption is not valid. 
Does this library have an assumption about the error variances or can it be used with any type of errors on x and y?

The output of the linear regression includes the fit parameters and their sd or errors. 
The name of the array uses the expression "sd", while the output print uses the expression "std error".
Are the uncertainties on the fit parameters, calculated by this library, standard deviations or standard errors? This is important to know in order to calculate correctly confidence intervals around fit parameters. 

Thanks for your help.

**Comment by tupui** [comment]
Hi @Federico2111, thank you for reporting.

In the description that you linked, we are explaining that this provides an interface to ODRPACK and point to it's documentation, the tile of which being: `User’s Reference Guide for ODRPACK Version 2.01 Software for Weighted Orthogonal Distance Regression`. Maybe we could bring this information forward a bit more in the documentation. I think the current state is ok too and hence will close the issue. Still, fee free to propose a documentation enhancement 😃

**Comment by Federico2111** [comment]
Thanks for you reply. 
By reading the documentation it appears that it is a Weighted Orthogonal Distance Regression. However, the issue related to standard deviation and standard error is still open and may have to be addressed. 
In the documentation (page ix) I can read: "The covariance matrix and the standard errors of the model parameter estimators are optionally provided."
This seems consistent with the printed output of the library, which returns the estimated parameters "Beta", with "Beta Std Error" and "Beta Covariance". 
However, in scipy.odr.Output, it says that the standard deviations, of the estimated parameters, are retuned: https://docs.scipy.org/doc/scipy/reference/generated/scipy.odr.Output.html#scipy.odr.Output

**Comment by Federico2111** [comment]
@tupui and @j-bowhay,

Who do you think can help me with this question? Should I ask it publicly?
Mistaking or miscalling standard errors for standard deviations, or vice versa, is frequent and problematic. It has happened in other python libraries, and the authors have clarified or corrected the code. 

Thanks

**Comment by tupui** [comment]
@Federico2111 I see, you would want to change the word "deviation" with "error" correct?

Not my area but you could try opening a PR to propose the adjustment and people familiar with `scipy.odr` could chime in.

**Comment by Federico2111** [comment]
What I am trying to understand is what this library calculates. 
The uncertainties around the returned fit parameters are standard errors or standard deviations?
This is my question. It is fine in both cases, as long as it is correctly specified in the description.

Standard errors and standard deviations are scaled by a factor sqrt(N), which is important to know to calculate correct confidence intervals around fit parameters. 

Who wrote this code?

**Comment by rkern** [comment]
I wrote the code. The [ODRPACK User's Guide](https://docs.scipy.org/doc/external/odrpack_guide.pdf) uses "standard deviation" and "standard error" fairly interchangeably but usually "standard deviation". In particular, the `SD` variable in FORTRAN that fills the `Output.sd` attribute is documented as "standard deviation", so that's how I documented it on our side.

**Comment by tupui** [comment]
Thanks Robert. Ok so what I am reading is that all is good from your perspective?

**Comment by Federico2111** [comment]
Okay thanks, so you confirm that, even if the documentation often mentions "standard errors" and the output print also mentions "standard errors", the returned uncertainties around fit parameters are actually "standard deviations". My guess was that they were standard errors (SE) because they look a bit small to be standard deviations (SD). But I trust what you say.

A reminder that:
SE = SD/sqrt(N), where N is the sample size 
Parametric CI = +- (SE x T-statistic)

Therefore, to calculate the parametric CI around fit parameters, first I have to calculate the standard errors from the standard deviations given by this library. 

@rkern do you confirm?

Thanks for your help.

**Comment by Federico2111** [comment]
I am now reading the past comment and it seems that "sd_beta is the standard error of the estimated beta. It is the standard deviation of the assumed Gaussian distribution of those beta estimates".

It appears that in this context the term are used interchangeably and coincide?

**Comment by rkern** [comment]
> It appears that in this context the terms are used interchangeably and coincide?

Yes.

**Comment by Federico2111** [comment]
Thanks @rkern. 

Therefore, I can use the uncertainties returned by this library around fit parameters, as standard errors, which they are. 

I think it may be worth specifying this in the library description, because I am not the only one who was confused, based on the past comment you shared. It is common practice to calculate CI's around fit parameters. It is thus important to explain that the outputs of this library are the estimated fit parameters, with their standard errors, which can be directly used to calculate CI's. It may also be worth specifying that, in this case, standard deviations and standard errors coincide, because it is not always the case. 

If I understood all correctly.
