### ISSUE TITLE
DOC: Linear Programming with Incrementally added constraints

### ISSUE THREAD

**Issue by MarvelTu** [scipy/scipy#18194]
### Issue with current documentation:

Does Scipy.linprog have any support for solving a series LP problems with increasing inequality constraints. 
It seems that dual simplex method should be used. I asked chatGPT, it gave the answer with getting `basis` from `OptimizeResult`. But by checking the document, `basis` is not in the list of `OptimizeResult`, is it removed?

**Comment by mdhaber** [comment]
The basis is not currently returned by any of the `linprog` methods. There are plans to add an object oriented interface to the HiGHS linear programming solver that would expose the features you're looking for. That is tracked in gh-15915, so I'll close this one.
@mckib2 anything to add?

**Comment by mckib2** [comment]
> @mckib2 anything to add?

Nope, gh-15915 directly addresses this use-case
