### ISSUE TITLE
BUG: KDTree does not return with np.nan and dtype=float32

### ISSUE THREAD

**Issue by dschwoerer** [scipy/scipy#18206]
### Describe your issue.

`KDTree()` does not return if called with float32 data containing invalid data.

### Reproducing Code Example

```python
import numpy as np
dat = np.random.random((3, 422500)).astype(np.float32)
dat[dat < .5] = np.nan
from scipy.spatial import KDTree
KDTree(dat.T)
```

### Error message

```shell
n/a
```

### SciPy/NumPy/Python version and system information

```shell
1.8.0.dev0+1921.c30fefc 1.23.4 sys.version_info(major=3, minor=10, micro=7, releaselevel='final', serial=0)
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/lib64']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/lib64']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/lib64']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/lib64']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2,AVX512F,AVX512CD,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
    not found = AVX512_KNL,AVX512_KNM
```

**Comment by tylerjereddy** [comment]
I can't reproduce the behavior (on Linux) where `KDTree` "does not return" (i.e., hangs indefinitely) on any of these versions of SciPy using a reproducer similar to yours (note: it may be helpful to pin the random seed for reproducers...):

- `1.10.1` is fine
- `1.9.3` is fine
- `1.8.1` is fine
- `1.8.0` is fine
- `1.7.3` is fine

I can leave this open for a while in case you want to clarify that you can still reproduce this on i.e., the latest stable release pulled from PyPI, or that you have some other special configuration...

**Comment by rgommers** [comment]
Returns fine for me on macOS arm64 with most recent build from `main` too.
