### ISSUE TITLE
Improvement suggestion for 'keep_feasible=True'  in 'scipy.optimize.NonlinearConstraint' 

### ISSUE THREAD

**Issue by lhg1992** [scipy/scipy#18234]
Issue:
'keep_feasible=True' in the 'scipy.optimize.NonlinearConstraint' requires 'x0' in 'scipy.optimize.minimize' to meet the constraints. This is so unreasonable for users, because the initial guess can easily violate the constraints.
Besides, sometimes, it also can't converge to the right results, while ''keep_feasible=False' can converge. 
However, if I set ''keep_feasible=False', it sometimes converges to the point of minimum objective but violating constraints.

Analysis:
The reason of the failure is quite obvious, because once we set 'keep_feasible=True' , the optimization process doesn't accept the "infeasible" trials to compute the finte difference to let the optimization process go further.

Improvement suggestion:
Why can't we make the process go as "keep_feasible=False", so that it can use the "infeasible" trials to converge to the final feasible result, but only accept the "feasible" trials as the valid steps towards the final result.
We should also set a number limit to the **consecutive** "infeasible" trials so that it can come back to the last valid step and make it as the final result or continue trials in different directions or step-sizes.

My objective function and constraint function are just too complex to share here, so that it's just better to describe the issues by words rather than posting more than a hundred lines of code.
BTW, I also tried Matlab, it is more robust in solving the problem. By giving different x0, it converges more than scipy does.
(Actually I'm migrating my PhD results coded in Matlab into Python)
### Reproducing Code Example

```python
cons=NonlinearConstraint(fun_con,  0+1e-6, np.inf, keep_feasible=True) #require x0 to fulfil cons
res = opt.minimize(obj, x0, #method = 'SLSQP', #'COBYLA'(fail), #'SLSQP'(default)
                    constraints=cons,
                    bounds=bounds,
                    tol=1e-4)
```

### Error message

```shell
Exception has occurred: ValueError
`x0` is infeasible with respect to some inequality constraint with `keep_feasible` set to True.
```

**Comment by lhg1992** [comment]
Here I give one failure example and one success example of how the constraint value changes as the optimization goes, with "keep_feasible=False":
The constraint is '-angle+65'>=0, i.e. angle<=65.
The variable for optimization is just the z_axis value in the Point.

The following information(except 'current x') is printed from the nonlinear constraint function.
'current x' is printed from the callback.

constraint, Point:(x,y,z), angle:
#====================================
# %% Failure example 
[16.829] [[ 527400. 6756900.   -1000.]] [48.171]
[16.829] [[ 527400. 6756900.   -1000.]] [48.171]
[16.708] [[ 527400.    6756900.       -999.231]] [48.292]
current x=[-999.231]

[16.708] [[ 527400.    6756900.       -999.231]] [48.292]
[16.708] [[ 527400.    6756900.       -999.231]] [48.292]
[16.111] [[ 527400.    6756900.       -995.454]] [48.889]
current x=[-995.454]

[16.111] [[ 527400.    6756900.       -995.454]] [48.889]
[16.111] [[ 527400.    6756900.       -995.454]] [48.889]
[12.918] [[ 527400.    6756900.       -976.117]] [52.082]
current x=[-976.117]

[12.918] [[ 527400.    6756900.       -976.117]] [52.082]
[12.918] [[ 527400.    6756900.       -976.117]] [52.082]
[-7.839] [[ 527400.    6756900.       -884.797]] [72.839]
current x=[-884.797]

[-7.839] [[ 527400.    6756900.       -884.797]] [72.839]
[-7.839] [[ 527400.    6756900.       -884.797]] [72.839]
[-3.999] [[ 527400. 6756900.    -800.]] [68.999]
current x=[-800.]

[-3.999] [[ 527400. 6756900.    -800.]] [68.999]
[-3.999] [[ 527400. 6756900.    -800.]] [68.999]
[-3.999] [[ 527400. 6756900.    -800.]] [68.999]
current x=[-800.] 

[-3.999] [[ 527400. 6756900.    -800.]] [68.999]
[-3.999] [[ 527400. 6756900.    -800.]] [68.999]
[-3.999] [[ 527400. 6756900.    -800.]] [68.999]
[-3.999] [[ 527400. 6756900.    -800.]] [68.999]
[-3.999] [[ 527400. 6756900.    -800.]] [68.999]
[-3.999] [[ 527400. 6756900.    -800.]] [68.999]
[-3.999] [[ 527400. 6756900.    -800.]] [68.999]
[-3.999] [[ 527400. 6756900.    -800.]] [68.999]
[-3.999] [[ 527400. 6756900.    -800.]] [68.999]
[-3.999] [[ 527400. 6756900.    -800.]] [68.999]
[-3.999] [[ 527400. 6756900.    -800.]] [68.999]
[-3.999] [[ 527400. 6756900.    -800.]] [68.999]
[-3.999] [[ 527400. 6756900.    -800.]] [68.999]
current x=[-800.]
...
_Then it stucks at this infeasible point with objective function minimized, but constraints violated._
#====================================
#====================================
# %% successful example 
[18.245] [[ 527400.    6756900.      -1009.157]] [46.755]
[18.245] [[ 527400.    6756900.      -1009.157]] [46.755]
[17.615] [[ 527400.    6756900.      -1005.051]] [47.385]
current x=[-1005.051]

[17.615] [[ 527400.    6756900.      -1005.051]] [47.385]
[17.615] [[ 527400.    6756900.      -1005.051]] [47.385]
[14.395] [[ 527400.    6756900.       -984.885]] [50.605]
current x=[-984.885]

[14.395] [[ 527400.    6756900.       -984.885]] [50.605]
[14.395] [[ 527400.    6756900.       -984.885]] [50.605]
[-7.718] [[ 527400.    6756900.       -888.282]] [72.718]
current x=[-888.282]

[-7.718] [[ 527400.    6756900.       -888.282]] [72.718]
[-7.718] [[ 527400.    6756900.       -888.282]] [72.718]
[3.601] [[ 527400.    6756900.       -928.173]] [61.399]
current x=[-928.173]

[3.601] [[ 527400.    6756900.       -928.173]] [61.399]
[3.601] [[ 527400.    6756900.       -928.173]] [61.399]
[-4.678] [[ 527400.   6756900.      -896.93]] [69.678]
current x=[-896.93]

[-4.678] [[ 527400.   6756900.      -896.93]] [69.678]
[-4.678] [[ 527400.   6756900.      -896.93]] [69.678]
[3.011] [[ 527400.    6756900.       -925.582]] [61.989]
current x=[-925.582]

[3.011] [[ 527400.    6756900.       -925.582]] [61.989]
[3.011] [[ 527400.    6756900.       -925.582]] [61.989]
[-3.792] [[ 527400.    6756900.       -899.743]] [68.792]
current x=[-899.743]

[-0.201] [[ 527400.    6756900.       -912.452]] [65.201]
[-0.201] [[ 527400.    6756900.       -912.452]] [65.201]
[-0.201] [[ 527400.    6756900.       -912.452]] [65.201]
[0.19] [[ 527400.    6756900.       -913.959]] [64.81]
current x=[-913.959]

[0.19] [[ 527400.    6756900.       -913.959]] [64.81]
[0.19] [[ 527400.    6756900.       -913.959]] [64.81]
[-0.19] [[ 527400.    6756900.       -912.492]] [65.19]
current x=[-912.492]

[0.002] [[ 527400.    6756900.       -913.231]] [64.998]
[0.002] [[ 527400.    6756900.       -913.231]] [64.998]
[0.002] [[ 527400.    6756900.       -913.231]] [64.998]
[-0.002] [[ 527400.    6756900.       -913.217]] [65.002]
current x=[-913.217]

[0.] [[ 527400.    6756900.       -913.224]] [65.]
[0.] [[ 527400.    6756900.       -913.224]] [65.]
[0.] [[ 527400.    6756900.       -913.224]] [65.]
[0.] [[ 527400.    6756900.       -913.223]] [65.]
current x=[-913.223]

[0.] [[ 527400.    6756900.       -913.223]] [65.]
[0.] [[ 527400.    6756900.       -913.223]] [65.]
current x=[-913.223]
#=======================================

I hope the process values above can help scipy developers to improve the

**Comment by andyfaff** [comment]
Unfortunately the second example did not give enough to work with. If started with a feasible region the constrained minimisers should keep within the feasible region and iterate towards a minimum of the objective function.

If you use `keep_feasible=True` with SLSQP or Cobyla then its only effect will be to produce an Exception when a point that doesn't obey Bounds is used to calculate a finite difference. The keyword has no other effect in the minimisation.

`keep_feasible` was mainly designed for use with [`trust_constr`](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-trustconstr.html#optimize-minimize-trustconstr). With this method `keep_feasible` is used to specify that all steps taken should be within a feasible region. `trust-constr` works towards minimising the objective function *and* minimising constraint violation (see `initial_constr_penalty`).

> 'keep_feasible=True' in the 'scipy.optimize.NonlinearConstraint' requires 'x0' in 'scipy.optimize.minimize' to meet the constraints. This is so unreasonable for users, because the initial guess can easily violate the constraints.

This is by design - users don't want their objective function to be evaluated in invalid regions.

> Besides, sometimes, it also can't converge to the right results, while ''keep_feasible=False' can converge. However, if I set ''keep_feasible=False', it sometimes converges to the point of minimum objective but violating constraints.

It helps if we have a concrete example here to exercise the issue. This effect is understandable if iteration has never visited a feasible region. Sometimes the problem is just too difficult to find a feasible region.

> Why can't we make the process go as "keep_feasible=False", so that it can use the "infeasible" trials to converge to the final feasible result, but only accept the "feasible" trials as the valid steps towards the final result.

`'slsqp', 'cobyla', 'trust-constr'` all work towards final feasible results, even from infeasible regions. e.g. 
```
>>> from scipy.optimize import minimize, NonlinearConstraint, rosen
>>> def quad(x):
...       return np.sum(x**2)

>>> nlc = NonlinearConstraint(quad, 2.2, 3)
minimize(rosen, np.array([0.1, 0.1]), method='SLSQP', constraints=(nlc,))
minimize(rosen, np.array([0.1, 0.1]), method='SLSQP', constraints=(nlc,))
minimize(rosen, np.array([0.1, 0.1]), method='SLSQP', constraints=(nlc,))
 message: Optimization terminated successfully
 success: True
  status: 0
     fun: 0.0010302902148435482
       x: [ 1.032e+00  1.065e+00]
     nit: 11
     jac: [ 4.869e-02  7.514e-03]
    nfev: 40
    njev: 11
```

You should also look into `differential_evolution` as its global minimiser nature can aid in finding small feasible regions in parameter space.

**Comment by lhg1992** [comment]
Thank you for your reply.
> If started with a feasible region the constrained minimisers should keep within the feasible region and iterate towards a minimum of the objective function.
>
But unfortunately, the failure example above exactly shows it starts within feasible region (x0=-1000, cons_val=16.829>0) but finally ends up with constraints violated (x=-800, cons_val=-3.99<0).

I have tried "differential_evolution", it can converge to the right point, but of course, with much longer time as it is actually trying a lot more points. However [it can't handle parallel computing properly ](https://github.com/scipy/scipy/issues/18236).

**Comment by andyfaff** [comment]
Without a MWE we won't be able to investigate this issue further.
