### ISSUE TITLE
BUG: `complex256` type created by entering `complex128` into `linalg.sqrtm` causes errors.

### ISSUE THREAD

**Issue by cphys** [scipy/scipy#18250]
### Describe your issue.

When `scipy.linalg` operates on a complex array/matrix it returns a complex array with double the precision of the input array. As a result if given a `complex128` type array it will return a `complex256` array.

This type of array is not supported by `numpy.linalg` functions and will result in errors. And  `scipi.linalg` functions it will automatically downcast any `complex256` type to a `complex128` type.

This causes many problems in large code bases with combine `scipy` and `numpy`. 

I have attached a sample code which shows the behavior of both scipy and numpy when acting on this datatype.

### Reproducing Code Example

```python
import numpy as np
import scipy as sp

# create a numpy array of type complex128
a = np.array([[1.0, 3.0], [1.0, 4.0]],dtype=np.complex128)
print(type(np.square(a[0][0])))

# sqrtm returns an array of complex256
b = sp.linalg.sqrtm(a)
print(type(np.square(b[0][0])))

# arrays of type complex128 will run fine for both
# scipy and numpy functions
print(type(np.linalg.eig(a)[0][0]))
print(type(sp.linalg.eig(a)[0][0]))

# arrays of type complex256 will run for
# scipy functions, but not for the exact same numpy function
# it would seem that scipy functions reduce the precision of
# the complex256 inputs while numpy functions throw a TypeError
print(type(sp.linalg.eig(b)[0][0]))
print(type(np.linalg.eig(b)[0][0]))
```

### Error message

```shell
<class 'numpy.complex128'>
<class 'numpy.complex256'>
<class 'numpy.complex128'>
<class 'numpy.complex128'>
<class 'numpy.ndarray'>
Traceback (most recent call last):
  File "/home/cphys/projects/scipy_numpy_bug/scipy_test.py", line 20, in <module>
    print(type(np.linalg.qr(b)[0][0]))
  File "<__array_function__ internals>", line 200, in qr
  File "/home/cphys/.local/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 915, in qr
    t, result_t = _commonType(a)
  File "/home/cphys/.local/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 147, in _commonType
    raise TypeError("array type %s is unsupported in linalg" %
TypeError: array type complex256 is unsupported in linalg
```

### SciPy/NumPy/Python version and system information

```shell
1.10.0 1.24.2 sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX1.10.0 1.24.2 sys.version_info(major=3, minor=10, micro=6, releaselevel='final', serial=0)
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_KNM,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
512_ICL
```

**Comment by ilayn** [comment]
That's probably an oversight that came from a contributor with a Windows machine. Because on Win, complex256 is complex 128 anyways. We don't use complex256 anywhere anyways. I'll check.

**Comment by rkern** [comment]
For reference, this was added intentionally in gh-16294 in response to gh-14853, but as noted in the last comment there, this was probably not the correct thing to do. @AtsushiSakai, can you explain why the precision was doubled in that case? I concur with @WarrenWeckesser's comment. It doesn't seem like the right thing to do to me.

**Comment by AtsushiSakai** [comment]
I thought if the input dtype of the `sqrtm` function is real and the output dtype is complex, the precision had to be doubled to maintain accuracy (e.g., if the input was int32, the output would be complex64). 

However, it is true that there may not have been a need to double the precision if both the input and output were complex. In the current implementation, the decision is made based only on the output dtype of the calculation result, so using the input dtype as well might allow for maintaining precision when both input and output are complex.

 I will try to implement it that way and see if it works.

**Comment by rkern** [comment]
Yes, when the input is real floating, the complex output will be twice the `itemsize` of the input, but that should not be the case when the input is complex. The real part of the input needs to be the same as the real part of the output.

One more thing: in the case of integer input, you need to check the size of the input _after_ it gets converted to a floating point type by `_asarray_validated(A, check_finite=True, as_inexact=True)`. That's the relevant dtype to be looking at, not the integer's `itemsize`.
