### ISSUE TITLE
BUG: optimize OptimizeResult and now  RootResult  has empty `__dict__`

### ISSUE THREAD

**Issue by josef-pkt** [scipy/scipy#18253]
### Describe your issue.

#17998 made RootResults a subclass of OptimizeResult and lost the information in the `__dict__`.

AFAICS OptimizeResult has empty `__dict__`  (I'm currently using scipy 1.7.3)

The missing `__dict__` information in RootResults cause unit test failure in statsmodels with pre-release dependencies
uses optimize.brentq
https://github.com/statsmodels/statsmodels/issues/8776#issuecomment-1499141262

The unit test uses
`assert_array_less(info.__dict__['iterations'], 70)`

This part of statsmodels was written for scipy 0.7 to 0.9 and not changed since then. 

### Reproducing Code Example

```python
na
```

### Error message

```shell
a = 500
        val, info = brentq_expanding(func, args=(a,), full_output=True)
        assert_allclose(val, a, rtol=1e-5)
        info1 = {'iterations': 63, 'start_bounds': (-1, 1),
                 'brentq_bounds': (100, 1000), 'flag': 'converged',
                 'function_calls': 64, 'iterations_expand': 3, 'converged': True}
    
        # adjustments for scipy 0.8.0 with changed convergence criteria
>       assert_array_less(info.__dict__['iterations'], 70)
E       KeyError: 'iterations'
```

### SciPy/NumPy/Python version and system information

```shell
pre-release scipy
```

**Comment by josef-pkt** [comment]
Aside:

The `__dict__` attribute is very useful when we want to copy all attributes to a new instance.
I use that pretty often.

statsmodels might also have problems with OptimizeResult where we loose the information.
However, we use optimize.minimize only in a few places or as extra option.
The orgininal optimize functions still return a tuple (and so have been backwards compatible forever, unchanged statsmodels code for 10 to 12 years)

```
res = optimize.fmin(func, [1, 1, 1], maxiter=1000, full_output=True, disp=0)
type(res)
tuple
```

**Comment by rkern** [comment]
It's a judgement call, but typically I would consider direct access to `__dict__` to be an implementation detail that's subject to change. The public API is regular attribute access (i.e. `info.iterations` or `gettatr(info, name)` if you don't have a literal rather than `info.__dict__['iterations']`). Python has a number of different mechanisms for implementing attribute access (storing attributes in `__dict__`, properties, `__getattr__`, etc.), and I'd typically consider moving between any of them a valid option that preserves the public API.

In the particular case of this failing test, it would be more simple, more correct, and more idiomatic to write `info.iterations` instead of `info.__dict__['iterations']`.

**Comment by josef-pkt** [comment]
```
class Holder()
    pass

res = Holder()
res.__dict__.update(another_res.__dict__)
```

Without `__dict__` there is no one liner to replace the last line.

(I don't like hybrid classes like OptimizeResult if methods are too complicated and the class is "non-standard". There might be too much unintended inherited behavior.)

The change is https://github.com/scipy/scipy/pull/17998 changed the base class of RootResults from the basic type to a subclass of dict. This does not sound like a simple API change to me.

If we had been subclassing RootResults, then the behavior would have considerable changed when switching the base superclass.

(checking the statsmodels `minimize` code:
Optimize Result was always a subclass of dict. So it was that way when statsmodels started to use `minimize`.
However, we only use attribute access and only for specific attributes, i.e. we don't try to get all info that might be in the OptimizeResult.
)

Whatever, I will change the code in statsmodels.
I don't remember at all why I used `__dict__` in the unit test.
