### ISSUE TITLE
BUG: Scipy stats rv_continuous fit does not handle numpy objects and pandas series

### ISSUE THREAD

**Issue by jankaWIS** [scipy/scipy#18265]
### Describe your issue.

This issue is a problem with using `np.isfinite` in the check and in the fit as that does not handle `object` types or the pandas types (e.g. https://stackoverflow.com/questions/40809503/python-numpy-typeerror-ufunc-isfinite-not-supported-for-the-input-types). The problem is that if one passes an array that is of type object or a pandas series, the following error appears:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/bx/tb4883l53hdd3zp2y0nyy_4m0000gp/T/ipykernel_51806/2824632564.py in <module>
----> 1 beta_fx.fit(data)

~/anaconda3/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py in wrapper(self, *args, **kwds)
     60             return super(type(self), self).fit(*args, **kwds)
     61         else:
---> 62             return fun(self, *args, **kwds)
     63     return wrapper
     64 

~/anaconda3/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py in fit(self, data, *args, **kwds)
    660         if floc is None or fscale is None:
    661             # do general fit
--> 662             return super().fit(data, *args, **kwds)
    663 
    664         # We already got these from kwds, so just pop them.

~/anaconda3/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py in fit(self, data, *args, **kwds)
   2470             raise TypeError("Too many input arguments.")
   2471 
-> 2472         if not np.isfinite(data).all():
   2473             raise RuntimeError("The data contains non-finite values.")
   2474 

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

```

Note that I'm explicitly passing the data type to the default pandas data type; even though it is a float type, it still does not handle it. One solution to that is to explicitly redefine the types on call but I believe that should not be the default behaviour.

### Reproducing Code Example

```python
import numpy as np
import pandas as pd
from scipy.stats import beta as beta_fx


print(beta_fx.fit(pd.Series(np.random.beta(2,3,100), dtype='Float64')))
# or
print(beta_fx.fit(pd.Series(np.random.beta(2,3,100).astype('object'))))
```

### Error message

```shell
import numpy as np

import pandas as pd

from scipy.stats import beta as beta_fx

​

​

beta_fx.fit(pd.Series(np.random.beta(2,3,100), dtype='Float64'))

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/bx/tb4883l53hdd3zp2y0nyy_4m0000gp/T/ipykernel_51806/4270923539.py in <module>
      4 
      5 
----> 6 beta_fx.fit(pd.Series(np.random.beta(2,3,100), dtype='Float64'))

~/anaconda3/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py in wrapper(self, *args, **kwds)
     60             return super(type(self), self).fit(*args, **kwds)
     61         else:
---> 62             return fun(self, *args, **kwds)
     63     return wrapper
     64 

~/anaconda3/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py in fit(self, data, *args, **kwds)
    660         if floc is None or fscale is None:
    661             # do general fit
--> 662             return super().fit(data, *args, **kwds)
    663 
    664         # We already got these from kwds, so just pop them.

~/anaconda3/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py in fit(self, data, *args, **kwds)
   2470             raise TypeError("Too many input arguments.")
   2471 
-> 2472         if not np.isfinite(data).all():
   2473             raise RuntimeError("The data contains non-finite values.")
   2474 

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

### SciPy/NumPy/Python version and system information

```shell
1.7.3 1.22.3 sys.version_info(major=3, minor=8, micro=11, releaselevel='final', serial=0)
lapack_mkl_info:
    libraries = ['blas', 'cblas', 'lapack', 'pthread', 'blas', 'cblas', 'lapack']
    library_dirs = ['/Users/jan/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jan/anaconda3/include']
lapack_opt_info:
    libraries = ['blas', 'cblas', 'lapack', 'pthread', 'blas', 'cblas', 'lapack', 'blas', 'cblas', 'lapack']
    library_dirs = ['/Users/jan/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jan/anaconda3/include']
blas_mkl_info:
    libraries = ['blas', 'cblas', 'lapack', 'pthread', 'blas', 'cblas', 'lapack']
    library_dirs = ['/Users/jan/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jan/anaconda3/include']
blas_opt_info:
    libraries = ['blas', 'cblas', 'lapack', 'pthread', 'blas', 'cblas', 'lapack', 'blas', 'cblas', 'lapack']
    library_dirs = ['/Users/jan/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/jan/anaconda3/include']
```

**Comment by mdhaber** [comment]
`scipy.stats` currently supports numeric arrays; it does not currently support object arrays. 
```python3
import numpy as np
import pandas as pd
np.asarray(pd.Series([1, 2, 3, np.nan], dtype='Float64'))
array([1.0, 2.0, 3.0, <NA>], dtype=object)
```
You can avoid this by using a NumPy data type.
```python3
np.asarray(pd.Series([1, 2, 3, np.nan], dtype=float))
np.asarray(pd.Series([1, 2, 3, np.nan], dtype=np.float64))
```

**Comment by mdhaber** [comment]
@seberg I'm wondering what NumPy's opinion is on this, since it's come up in two similar ways recently.

Should this work?
```python3
import numpy as np
import pandas as pd
x = pd.Series([1, 2, 3, np.nan], dtype='Float64')
np.isfinite(np.asarray(x))  # or np.isfinite(x.to_numpy())
```

**Comment by jankaWIS** [comment]
> If NumPy users want it to work, is that something for NumPy to consider, pandas to consider, or users to work around?
@mdhaber, that's exactly my issue :). I know it's specific to scipy and I know a workaround -- the same one you write with manually converting dtypes to numpy compatible. But it took me a while to figure out where and what the issue is and it makes it not very user-friendly, especially as it's not a straightforward issue and it's not the user's fault.

**Comment by mdhaber** [comment]
Sure, and because of this, I've also converted gh-18254 to an enhancement request. But currently, `scipy.stats` just doesn't (in general) support Pandas inputs natively. You can find some functions that work OK, but many don't.

> it's not the user's fault.

That depends on the documentation. In this case, you are right that `stats.fit` says it accepts "array_like" `data`, which is defined by NumPy as 

![image](https://user-images.githubusercontent.com/6570539/230790007-0a6f5590-5ae5-4d68-8215-dcdca2b1bccd.png)

 astoundingly broad. By that definition, this should also work:

```
from scipy import stats
x = np.array(stats)  # apparently, `scipy.stats` is "array_like"!
stats.norm.fit(x)  # TypeError: ufunc 'isfinite' not supported for the input types...
```

So I've also labeled gh-18254 with a "documentation" label that "array_like" needs to be qualified: when accepted by `np.array`, the output needs have `dtype` that is a subtype of `np.number`.

**Comment by seberg** [comment]
Pandas goes to object here.  You may be able to argue about `object` and isfinite in NumPy, but IMOM the main issue here is that pandas makes it hard to stay with the normal dtype for the NA version one.

**Comment by mdhaber** [comment]
Thanks @seberg! Yeah, it might be nice if NumPy would try to do NaN checks for object arrays, but I agree that Pandas could also consider converting to arrays with a normal NumPy dtype.

**Comment by rgommers** [comment]
We should make this raise a clear exception in numpy eventually, as a follow-up to https://numpy.org/neps/nep-0034-infer-dtype-is-object.html. I believe that we had a tracking issue for that, but I'm not sure where. @seberg do you remember? Do you think we can/should do this for NumPy 2.0?

**Comment by seberg** [comment]
The only thing I see is adding the actual dtypes to the error message.  Anything else seems to go beyond the issue discussed here (you may be thinking of disallowing coercion of iterables that are not sequences).
