### ISSUE TITLE
Performance regression in `stats.mode` due to `_axis_nan_policy` decorator

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#18277]
_Copying relevant part of https://github.com/scipy/scipy/issues/18254#issuecomment-1502973890:_

I wanted to do some quick tests of  `_axis_nan_policy_factory` from within IPython, and it failed with a hard to understand `inspect.signature` traceback:

```python
>>> def f(x):
...     x
...
>>> _axis_nan_policy_factory(f)([1])
Traceback (most recent call last):
  Cell In[16], line 1
    _axis_nan_policy_factory(f)([1])
  File ~/code/scipy/build-install/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py:612 in axis_nan_policy_decorator
    sig = inspect.signature(axis_nan_policy_wrapper)
...
ValueError: callable [1] is not supported by signature
```

That led me to look at that factory function closer, and it's using `inspect` quite a bit - which tends to be not a good idea at runtime. Aside from robustness, some benchmarking shows large performance regressions:

```python
>>> import numpy as np
>>> from scipy import stats
>>> z = np.random.randint(10000)
>>> scipy.__version__
'1.10.1'
>>> %timeit stats.mode(z, keepdims=True)
47.9 µs ± 235 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```
compared to `main`:
```python
>>> %timeit stats.mode(z, keepdims=True)
229 µs ± 2.45 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

I have not been involved in review of that machinery - I assume some of this was discussed already? My first impression is that the ~250 line implementation of `_axis_nan_policy_factory` looks a bit scary.

**Comment by mdhaber** [comment]
> Aside from robustness, some benchmarking shows large performance regressions:

Basing this assessment on input of size 1 input seems somewhat unfair to me : /

The regression on 1D input is a constant overhead that disappears once the total execution time is on the order of a few ms. 

![image](https://user-images.githubusercontent.com/6570539/231905890-85973d7f-d8c0-4f5b-9e20-710916417de3.png)

<details>

```python3
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
rng = np.random.default_rng(1638083107694713882823079058616272161)
from time import perf_counter_ns

np.logspace(0, 7, 17, dtype=int)

times_main = []
times_110 = []
sizes = np.logspace(0, 7, 17, dtype=int)
for size in sizes:
    z = np.random.randint(10000, size=size)

    tic = perf_counter_ns()
    res = stats.mode(z)
    toc = perf_counter_ns()
    times_main.append((toc-tic)/1e9)

    tic = perf_counter_ns()
    res = stats.mode(z, _no_deco=True)
    toc = perf_counter_ns()
    times_110.append((toc-tic)/1e9)

plt.loglog(sizes, times_main, sizes, times_110)
plt.legend(("With Decorator", "Without Decorator"))
plt.xlabel("input size")
plt.ylabel("execution time (s)")
plt.show()
```

</details>

Reducing this overhead _is_ important to me, but I think it's important to keep it in context.

> I have not been involved in review of that machinery - I assume some of this was discussed already?

Yes, I believe a few active stats maintainers discussed that this was a fair, temporary price to pay for fixing lots of bugs. Note that there are many ways to reduce that overhead, all in good time. But there haven't been issues filed about the overhead (except this), so I haven't prioritized it.

> I wanted to do some quick tests of _axis_nan_policy_factory from within IPython, and it failed with a hard to understand inspect.signature traceback:

It is a private tool, so it does not give great error messages when configured incorrectly. For instance, the decorator is primarily for reduction operations, and `f` is an elementwise operation. 
The factory also needs a few arguments to produce a decorator for this function. (It was originally designed for hypothesis tests that produce `namedtuples`, so the defaults are not configured to handle this simple case.)

<details>

```python3
from scipy import stats
import numpy as np
from scipy.stats._axis_nan_policy import _axis_nan_policy_factory
rng = np.random.default_rng(94713882823079058616272161)

@_axis_nan_policy_factory(tuple_to_result=lambda x: x,
                          n_outputs=1,
                          result_to_tuple=lambda x: (x,))
def my_mean(x):
    return sum(x)/len(x)

x = rng.random(size=(3, 5))
my_mean(x, axis=None)  # 0.5260813343900258
my_mean(x, axis=0)  # array([0.66651292, 0.61757697, 0.28485519, 0.40367072, 0.65779087])
my_mean(x, axis=-1, keepdims=True)
# array([[0.4448106 ],
#        [0.76953225],
#        [0.36390116]])

x[x > 0.5] = np.nan
my_mean(x, axis=1)  # array([nan, nan, nan])
my_mean(x, axis=1, nan_policy='omit')  # array([0.12083134, 0.46403535, 0.19273502])
# my_mean(x, nan_policy='raise')  # ValueError: The input contains nan values

x = rng.random(size=(2, 3, 4, 5))
my_mean(x, axis=(1, 2)).shape  # (2, 5)

x = rng.random(size=(0, 5))
assert my_mean(x, axis=0).shape  # (5,), like NumPy
assert my_mean(x, axis=1).shape  # (0,), like NumPy

```

</details>

**Comment by rgommers** [comment]
> Yes, I believe a few active stats maintainers discussed that this was a fair, temporary price to pay for easily fixing bugs, addressing enhancement requests, and paving a way toward unifying `stats` and `mstats`. Note that there are many ways to reduce that overhead, all in good time. But I don't recall issues filed about the overhead (except this), so I haven't prioritized it.

Thanks for the detailed reply, and fair enough - correctness and maintainability should come first, and performance optimization afterwards. 

The `inspect` usage does look a bit too fragile to me (e.g., I suspect it may not be happy with `PYTHONOPTIMIZE=2`, which strips docstrings, in all circumstances), but I did a cursory bit of testing and could not make it break - so should be good enough, and bugs will get addressed if/when they show up.

**Comment by rgommers** [comment]
@mdhaber I wanted to flag this as a concern, but please feel free to close this issue if it's not helpful to you.
