### ISSUE TITLE
BUG: special: Loss of precision in `logsumexp`

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#18295]
### Describe your issue.

`logsumexp` loses precision in cases where it shouldn't, and in extreme cases it can return 0 when it should return a nonzero float.

### Reproducing Code Example

```python
In [2]: from scipy.special import logsumexp

In [3]: logsumexp([0, -40.0])
Out[3]: 0.0

In [4]: np.logaddexp(0, -40)  # This is the expected result of `logsumexp([0, -40.0])`.
Out[4]: 4.248354255291589e-18
```

<details>
<summary>

### SciPy/NumPy/Python version and system information

</summary>

```shell
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "11.3.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "0.29.33",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "11.3.0",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "11.3.0",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.12.1",
      "include directory": "../../../../../py3.10.8/lib/python3.10/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas",
      "found": true,
      "version": "0.3.20",
      "detection method": "pkgconfig",
      "include directory": "/usr/include/x86_64-linux-gnu/openblas-pthread/",
      "lib directory": "/usr/lib/x86_64-linux-gnu/openblas-pthread/",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER=1 NO_CBLAS= NO_LAPACK= NO_LAPACKE=1 NO_AFFINITY=1 USE_OPENMP=0 generic MAX_THREADS=64",
      "pc file directory": "/usr/lib/x86_64-linux-gnu/pkgconfig"
    },
    "lapack": {
      "name": "openblas",
      "found": true,
      "version": "0.3.20",
      "detection method": "pkgconfig",
      "include directory": "/usr/include/x86_64-linux-gnu/openblas-pthread/",
      "lib directory": "/usr/lib/x86_64-linux-gnu/openblas-pthread/",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER=1 NO_CBLAS= NO_LAPACK= NO_LAPACKE=1 NO_AFFINITY=1 USE_OPENMP=0 generic MAX_THREADS=64",
      "pc file directory": "/usr/lib/x86_64-linux-gnu/pkgconfig"
    }
  },
  "Python Information": {
    "path": "/home/warren/py3.10.8/bin/python3",
    "version": "3.10"
  }
}
```

</details>

**Comment by WarrenWeckesser** [comment]
The following script contains a couple alternative implementations for `logsumexp(a)` that avoid the loss of precision.  These are for a 1-d input with no weight parameter; actually implementing `scipy.special.logsumexp` with one of these will require some more work.

```
import numpy as np
from mpmath import mp


def mp_naive_logsumexp(a):
    with mp.extradps(10):
        return mp.log(mp.fsum([mp.exp(ai) for ai in a]))


def np_logaddexp_reduce_sort(a):
    return np.logaddexp.reduce(np.sort(a)[::-1])


def logsumexp_v2(a):
    a = np.asarray(a)
    a_max = a.max()
    b = a[a != a_max] - a_max
    m = len(a) - len(b)
    return np.log1p(np.exp(b).sum()/m) + np.log(m) + a_max
```
`mp_naive_logsumexp` provides a reference implementation based on `mpmath`.  Be sure to set `mp.dps` sufficiently high to avoid loss of precision in that implementation.

The simpler implementation is just `np.logaddexp.reduce(np.sort(a)[::-1])`. E.g.

```
In [95]: a = [0, -40]

In [96]: np_logaddexp_reduce_sort(a)
Out[96]: 4.248354255291589e-18
```

The array is sorted in descending order in that implementation to improve the result for an input such as `a = [-600, -600, -600, -600, -600, -600, -600, 0]`.  If the array is not sorted before calling `np.logaddexp.reduce`, the result is `1.8552775871029815e-260`, which has a relative error of about 2e-14.  If the array is sorted, the result is accurate to machine precision:

```
In [171]: a = [-600, -600, -600, -600, -600, -600, -600, 0]

In [172]: mp.dps = 400

In [173]: float(mp_naive_logsumexp(a))
Out[173]: 1.8552775871030176e-260

In [174]: np_logaddexp_reduce_sort(a)
Out[174]: 1.8552775871030176e-260
```
(Such high precision is not guaranteed in all cases, of course.)

The other implementation, `logsumexp_v2`, is a refinement of the current implementation in `logsumexp`.  Let $\hat{a}$ be the maximum value in `a`.  Then

$$\begin{align}
  \log\left(\sum_i e^{a_i}\right)
      &= \log\left(\sum_{i}e^{\hat{a}}e^{a_i - \hat{a}}\right) \\
      &= \log\left(e^{\hat{a}} \sum_{i} e^{a_i - \hat{a}}\right) \\
      &= \hat{a} + \log\left(\sum_{i}e^{a_i - \hat{a}}\right) \\
      &= \hat{a} + \log\left(m + \sum_{i \in S} e^{a_i - \hat{a}}\right) \\
      &= \hat{a} + \log(m) + \log\left(1 + \frac{1}{m}\sum_{i \in S} e^{a_i - \hat{a}}\right)
\end{align}$$

where $m$ is the number of elements in $a$ that equal $\hat{a}$ and $S$ is the set of indices of $a$ where $a_i \ne \hat{a}$.  The first three lines in the above equations are the standard "trick" of factoring out the maximum of `a`; that is what is implemented currently in `logsumexp`.  In the remaining equations, the values in the sum that are known to be 1 are pulled out of the sum, allowing `log1p` to be used in the implementation.

The implementation in `logsumexp_v2` handles the examples shown above correctly:
```
In [498]: a = [0, -40]

In [499]: logsumexp_v2(a)
Out[499]: 4.248354255291589e-18

In [500]: a = [-600, -600, -600, -600, -600, -600, -600, 0]

In [501]: logsumexp_v2(a)
Out[501]: 1.8552775871030176e-260
```

`logsumexp_v2` appears to work as well as `np_logaddexp_reduce_sort`, and possibly even slightly better.  In my experiments, both generally get within a few ULPs of the reference value, but `logsumexp_v2` might do slightly better more often.  But that might be a bias created by the various specific examples I've experimented with.

I probably won't get around to creating a pull request based on one of these implementations to fix `logsumexp` any time soon, so anyone is welcome to do so.  You'll have to deal with the `axis` and `b` parameters appropriately.

**Comment by jjerphan** [comment]
If I may interjection, scikit-learn is also facing numerical instability for some edge cases (e.g. https://github.com/scikit-learn/scikit-learn/pull/28048/).

I stumbled on this article which might be for your interest for resolving this issue: https://doi.org/10.1093/imanum/draa038.
