### ISSUE TITLE
Doc build is broken - probably after notebook support was merged

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#18300]
I noticed that my local doc build with `python dev.py doc` got broken (I get `build finished with problems, 2718 warnings.`). It was working very recently, so it's very likely due to `myst-nb`/`jupytext` related changes (Cc @melissawm). I wiped my whole dev env and reinstalled from scratch with `conda env create -f environment.yml`, and it's still broken, so it should be reproducible.

It probably also affected our CI doc builds; an example where content went missing is http://scipy.github.io/devdocs/dev/contributor/ubuntu_guide.html#ubuntu-guide:

![image](https://user-images.githubusercontent.com/98330/231903612-8534cf1d-f95d-432a-a720-b5799a622673.png)

**Comment by tupui** [comment]
Thanks Ralf! Seems like a concurrency issue, adjusting the number of parallel jobs is having an impact. With `-j 2` it was going a bit further for me and now with `-j 1` it seems to go (still building, so far so good). I am to debug this more.

> an example where content went missing

You do not have the collapsible element at the end of the line? If not, which browser are you using. I can see the element and it's working as expected on Safari and chrome based browser on my side.

**Comment by rgommers** [comment]
> You do not have the collapsible element at the end of the line?

Ah! It is collapsible, but that is completely impossible to see with the dark theme. It looks exactly line my screenshot above in both Firefox and Chrome. With the light theme it's better. The side-by-side tabs are not great in the dark theme either:

<img width="754" alt="image" src="https://user-images.githubusercontent.com/98330/232034742-c03b5f7c-dfdb-4ce0-95e7-b72a2f1d6098.png">

But still that's a lot better. The quick fix here is to completely avoid the problematic element, and only use the side-by-side tabs. There's also no reason to have a section with _only_ foldouts, that can never be good.

**Comment by tupui** [comment]
Ouch totally agree it's impossible to read in dark mode. I can have a look and fix the style and also use tabs.

In general I am not sure about this page, there are quite some duplicate info with the conda only page. I see if I can propose something.

Regarding the concurrency thing. I confirm that using a single thread worked without producing any error nor warnings. That's annoying, still debugging.

**Comment by melissawm** [comment]
Oh no - I will try to check that out too.

**Comment by rgommers** [comment]
Please don't worry about the content - I am going to rewrite it all in one go (or better, throw most of this away). If you can fix the immediate rendering problem and the doc build issues, that would be awesome though.

**Comment by ilayn** [comment]
As a fellow colorblind, I would be grateful if we adjust the contrast indeed https://webaim.org/resources/contrastchecker/ here is a very nice tool that I use (there are many others)

**Comment by tupui** [comment]
Ok I will focus on these 👍 

For the colour of the theme, etc. We did not do much so far because the new version of the theme would fix a lot of our issues... Still I will do what I can for the current issue.

**Comment by ilayn** [comment]
No rush but much appreciated.

**Comment by melissawm** [comment]
@rgommers it looks like the parallel build failure is only related to python 3.11 (which is why it's not failing on CI), so as a workaround could you try building with python 3.10? I am looking into a better fix now.

**Comment by rgommers** [comment]
Ah that's helpful, thanks Melissa!

**Comment by tupui** [comment]
FYI we iterated a bit here and on my machine 3.10 is not working. I have an M1 and she tested on both an Ubuntu and a Mac (both Intel). So might be an M1 thing.

**Comment by rgommers** [comment]
A year has passed and the theme update landed at long last. I'll close this. If anything is still relevant, that's probably better for a new issue.
