### ISSUE TITLE
ENH: milp supporting sparse inputs

### ISSUE THREAD

**Issue by SimoneConiglio** [scipy/scipy#18326]
### Is your feature request related to a problem? Please describe.

When trying to use milp with sparse inputs I got this error:
![image](https://user-images.githubusercontent.com/26006909/233319179-36d9b727-cc62-4054-b696-2163c13de84b.png)

### Describe the solution you'd like.

To be able to define the constraint  and the objective coefficients as sparse object and not only numpy array.

### Describe alternatives you've considered.

recasting input is not memory efficient and should as well affect the solver efficiency (I don't know how this reflect on Highs performances)

**Comment by mdhaber** [comment]
The 2D arrays (e.g. the constraint matrices) may be sparse, and they are converted to sparse if they are not sparse already.

From the documentation,
> Before the problem is solved, all values are converted to double precision, and the matrices of constraint coefficients are converted to instances of [scipy.sparse.csc_array](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_array.html#scipy.sparse.csc_array).

This is the format the underlying HiGHS solver users.

The 1D arrays are treated as dense by HiGHS, IIRC, so we do not convert them or allow sparse input. Can you confirm that you only get this error when one of the 1D inputs is sparse? If so, we can improve the error message.

**Comment by SimoneConiglio** [comment]
yes I confirm I tested with `c` vector only as sparse and got the error I did not try to put only the constraint matrix as a sparse. My bad thank you for your answer that is great!

**Comment by mdhaber** [comment]
Thanks @SimoneConiglio. Please see gh-18327 and approve it if it resolves your concern.
