### ISSUE TITLE
BUG: Adding a sparse matrix to a dense NumPy ndarray converts type to matrix type, should matrix type be removed?

### ISSUE THREAD

**Issue by lucashc** [scipy/scipy#18336]
### Describe your issue.

When adding a sparse matrix to a numpy ndarray, the resulting object is neither sparse (as expected) nor a ndarray. The resulting object will be a numpy matrix object, which behaves differently from the ndarray object. Normally this is not a big problem, but methods like reshape and flatten no longer work as expected. 

Upon investigation, it seems the problem does not lie with NumPy, as in my code example, executing `x.__add__(y)` raises a `NotImplemented`, so instead the `y.__add__(x)` method is called. 

This method is defined in [scipy/sparse/_base.py](https://github.com/scipy/scipy/blob/d81c948a75aaed3b0345be7dfb8b8e0282afc0fb/scipy/sparse/_base.py#L462). In that method the numpy array is broadcasted to the correct shape. Then the `self._add_dense(other)` method is called, which calls the `_add_dense()` method in [scipy/sparse/_coo.py](https://github.com/scipy/scipy/blob/d81c948a75aaed3b0345be7dfb8b8e0282afc0fb/scipy/sparse/_coo.py#L563). In turn the `_container()` method in [scipy/sparse/_base.py](https://github.com/scipy/scipy/blob/d81c948a75aaed3b0345be7dfb8b8e0282afc0fb/scipy/sparse/_base.py#L234) is called to determine the output type. Somehow the resulting type is not a NumPy array anymore and gets converted to a matrix. 

I believe that this behaviour should be changed, as  NumPy states in their documentation that the class should no longer be used: [numpy.matrix](https://numpy.org/doc/stable/reference/generated/numpy.matrix.html).

I am not sure how deep this runs in SciPy, but would it be as simple as changing the `_container()` method in `sparse/_base.py`?

### Reproducing Code Example

```python
import scipy.sparse as sp
import numpy as np

# Create dense numpy ndarray.
x = np.zeros((3, 3))

# Create a sparse matrix.
y = sp.eye(3)

# Type is now np.ndarray.
print(type(x))

# Equivalent with x += y as np.ndarray does not have the __iadd__ method. 
z = x + y

# Type should be np.ndarray or sparse, but is numpy matrix. 
print(type(z))
```

### Error message

```shell
<class 'numpy.ndarray'>
<class 'numpy.matrix'>
```

### SciPy/NumPy/Python version and system information

```shell
1.10.1 1.24.2 sys.version_info(major=3, minor=10, micro=10, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: cmake
    found: true
    include directory: unknown
    lib directory: unknown
    name: OpenBLAS
    openblas configuration: unknown
    pc file directory: unknown
    version: 0.3.18
  lapack:
    detection method: cmake
    found: true
    include directory: unknown
    lib directory: unknown
    name: OpenBLAS
    openblas configuration: unknown
    pc file directory: unknown
    version: 0.3.18
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.33
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: /tmp/pip-build-env-xob7rtip/overlay/lib/python3.10/site-packages/pythran
    version: 0.12.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp310-cp310/bin/python
  version: '3.10'
```

**Comment by tupui** [comment]
Hi @lucashc, thank you for reporting!

We are aware of np.matrix being deprecated and it's one of the item we have on our roadmap: https://scipy.github.io/devdocs/dev/roadmap-detailed.html#sparse

I don't think there are additional information on this issue so I will close it for now 😃

**Comment by lucashc** [comment]
Hi @tupui,

Thank you for your reply. Yeah, it is not truly a bug, and good to hear it is on the roadmap.

However, it may be good to have a note for this behaviour. Specifically, as code snippets like:
`x += y`, where `x` is `np. ndarray` and `y` is sparse results in `np.matrix` which is unclear. The syntax seems to suggest the type of `x` won't change, even though it does.

Would it make sense to add a runtime warning with the suggestion to explicitly call `.todense()`?

**Comment by tupui** [comment]
Adding warnings is only done when we do change something. Here it would potentially create a lot of noise for existing users. We only do that if we are starting a deprecation cycle and have something else to often to "silence" the warning.

But again we do know all these inconsistency (sadly 😅) and are working on it 😃

**Comment by perimosocordiae** [comment]
Note also that we are actively working on improving sparse array support at the moment, but you can do this with the current released version of scipy right now:

```python
import scipy.sparse as sp
import numpy as np

# Create dense numpy ndarray.
x = np.zeros((3, 3))

# Create a sparse *array*. Easier construction functions are coming soon.
y = sp.dia_array(sp.eye(3))

z = x + y

# Type is still np.ndarray
print(type(z))
```
