### ISSUE TITLE
`ruff` flags a UP code after its 0.0.262 release, CI failing on format strings

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#18347]
In gh-18345, CI is failing because `ruff` flags `%s` string specifiers. Locally I didn't see this failure with `python dev.py lint` with ruff `0.0.261`, but it becomes visible after upgrading to `0.0.262`. This is not an okay thing to fail on, we have lots of code like that and it's perfectly valid code. 

I also don't know what the deal is what the `UP031` error. From `tools/lint.toml` we only specify E and F codes and that's what we check for. So this shouldn't be visible at all I think? If this happens more often, should we pin `ruff`?

_From gh-18345:_

The complaint is
```
dev.py:849:23: UP031 [*] Use format specifiers instead of percent format
```
for this code:
```python
print("Running benchmarks for Scipy version %s at %s"
      % (version, mod_path))
```

Cc @stefanv

**Comment by j-bowhay** [comment]
While we are looking at the linter, currently the max line length is set to 88 where as the docs say we follow pep8. Should one of these two be updated?

**Comment by rgommers** [comment]
The 88 line length seems fine, you can add a clarifying note to the relevant place in the doc if that helps? 88 is nicer to avoid complaints, and is also the [black default](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length).

**Comment by stefanv** [comment]
I'll investigate on Monday, unless @charliermarsh beats me to it.

**Comment by charliermarsh** [comment]
Lemme take a look...

**Comment by charliermarsh** [comment]
One point of clarification: it looks like `lint.py` uses `tools/ruff.toml` for configuration, and that `tools/lint.toml` is unused. `tools/ruff.toml` _does_ include the `UP` code, so the question may be whether SciPy wants to enforce that rule or not. If not, it can be disabled (either by disabling `UP031` or removing the `UP` rule set entirely).

**Comment by stefanv** [comment]
I thought I enabled it, thanks for spotting that discrepancy,@charliermarsh! We don't need both files anymore. That was from before ruff supported arbitrarily named config files.

**Comment by stefanv** [comment]
Hrm, the intent may have been the opposite way around, now I think of it, so can delete the ruff.toml.

**Comment by charliermarsh** [comment]
I'm happy to play around with getting the configuration in `lint.toml` setup and passing.

**Comment by rgommers** [comment]
Fixed in gh-18347, closing. Thanks all!
