### ISSUE TITLE
ENH: Is that ok to add tau-a to Kendall’s tau implementation?

### ISSUE THREAD

**Issue by zhimin-z** [scipy/scipy#18356]
### Is your feature request related to a problem? Please describe.

As seen in https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kendalltau.html, there are only two variants: `b` and `c` which correspond to `tau-b` and `tau-c` in https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient. I wonder if it is okay to add a `tau-a` option for completeness?

### Describe the solution you'd like.

Propose a new PR to implement `tau-a`

**Comment by mdhaber** [comment]
It's been discussed before. The rationale for not adding it is that Tau-b simplifies to Tau-a in the absence of ties. What is the use case in which Tau-a is needed that Tau-b does not fulfill?
