### ISSUE TITLE
ENH: Set Lowest Supported Python Version to 3.8

### ISSUE THREAD

**Issue by rbebb** [scipy/scipy#18366]
### Is your feature request related to a problem? Please describe.

Projects that use Python 3.8 will be unable to use future releases of scipy.

### Describe the solution you'd like.

It would be great for `requires-python` in pyproject.toml to be set to >=3.8 since Python 3.8 will be supported until October 2024.

### Describe alternatives you've considered.

N/A

### Additional context (e.g. screenshots, GIFs)

N/A

**Comment by tylerjereddy** [comment]
See: https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table

If you have a compelling objection to that community policy I suppose you could bring that up more broadly, but I think we're basically tracking that for Python itself.

**Comment by tylerjereddy** [comment]
I think this has been discussed in great detail already though, accounting for various support vs. maintenance burden realities.

**Comment by rgommers** [comment]
Agreed with @tylerjereddy. We dropped Python 3.8 support deliberately - that's not really up for discussion here anymore, unless there's an extremely compelling reason. So I'll close this issue.
