### ISSUE TITLE
BUG: refguide check failure in sparse svd code

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#18381]
### Describe your issue.

Lately I have seen the refguide job failing in CI multiple times in some sparse svd section: https://app.circleci.com/pipelines/github/scipy/scipy/19755/workflows/7be1af01-79dc-459c-92c4-d4a6d72c2471/jobs/66447

Thought I would raise attention with a separate issue.

Slightly related: it looks like the Fortran sparse SVD libraries are very painful to maintain. One unfortunately license incompatible alternative could be [Spectra](https://github.com/yixuan/spectra), ARPACK rewritten in C++. Are there any thoughts on replacements for the old PACKs?

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
File "build-install/lib/python3.9/site-packages/scipy/sparse/linalg/_eigen/_svds.py", line 280, in svds
Failed example:
    s_a(u2[:, :1], u[:, :1]) + s_a(u2[:, 1:], u[:, 1:]) > 1e-3
Expected:
    True
Got:
    array([False])

File "build-install/lib/python3.9/site-packages/scipy/sparse/linalg/_eigen/_svds.py", line 283, in svds
Failed example:
    (s_a(vT2[:1, :].T, vT[:1, :].T) +
     s_a(vT2[1:, :].T, vT[1:, :].T)) > 1e-3
Expected:
    True
Got:
    array([False])
```

### SciPy/NumPy/Python version and system information

```shell
N/A
```

**Comment by ilayn** [comment]
Probably @mckib2 is the right person to comment on the Spectra part in case he wants to chime in.

**Comment by ev-br** [comment]
Just commenting on the CI failure: this and related docstrings keep generating intermittent problems for too long already.  Redoing examples to make them less brittle would be great.

**Comment by mckib2** [comment]
> Probably @mckib2 is the right person to comment on the Spectra part in case he wants to chime in.

Eigen is MPL2, but if that's license-compatible there shouldn't be a problem.  Would require negotiating another CMake integration which we've traditionally handled by rewriting the build system in Meson.  I don't see an easy path for necessarily removing the old PACKs

**Comment by rgommers** [comment]
The main issue is fixed here. Just a comment on the side question:
- MPL2 is more restrictive than BSD/MIT, so is not usable for us
- Yes, the Fortran code is a maintenance headache - that's discussed in multiple other places
  - ARPACK is actually maintained (at https://github.com/opencollab/arpack-ng), so less problematic in principle. We haven't kept up-to-date though with the latest version
  - PROPACK is unmaintained AFAIK
- A license-compatible non-Fortran replacement would be awesome, but it's not something one writes in a few evenings
