### ISSUE TITLE
BUG: Can't interrupt kernel when doing sparse operations

### ISSUE THREAD

**Issue by irodionzaytsev** [scipy/scipy#18397]
### Describe your issue.

For example let R be a sparse matrix, v me a vector sparse or not sparse. If R.multiply(v) is taking ages, I try to interrupt the operations, jupyter notebook stuck.

### Reproducing Code Example

```python
For example let R be a sparse matrix, v me a vector sparse or not sparse. If R.multiply(v) is taking ages, I try to interrupt the operations, jupyter notebook stuck.
```

### Error message

```shell
For example let R be a sparse matrix, v me a vector sparse or not sparse. If R.multiply(v) is taking ages, I try to interrupt the operations, jupyter notebook stuck.
```

### SciPy/NumPy/Python version and system information

```shell
For example let R be a sparse matrix, v me a vector sparse or not sparse. If R.multiply(v) is taking ages, I try to interrupt the operations, jupyter notebook stuck.
```

**Comment by tupui** [comment]
Hi @irodionzaytsev, thank you for reporting. Could you provide a bit more details? At least a minimal example?

I suppose the memory usage is high and then the notebook is becoming unresponsive. You should still be able to interrupt the kernel. I am not sure there is any issue in the sense that this is a Python thing, you perform operations that would take up all the resources and this is your responsibility in the end to check that what you do is "sensible".

**Comment by irodionzaytsev** [comment]
Strangely enough, the example that I had seems to be working without lags now, and I just can't get it to lag long enough to actually show that interruptions aren't working. So I guess I will just close the issue, and if I find an example in the future, I will post it here. Thank you for advice - yeah, maybe it's a notebook thing rather than scipy.
