### ISSUE TITLE
MAINT: status of C++17 in the interregnum of meson without native windows support

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#18408]
Some time ago we did an [analysis](https://github.com/scipy/scipy/pull/16589) of the various compiler constraints and bumped our minimum versions to a point where we could universally use C++17 (the core language bits, not necessarily all of the C++ stdlib yet).

In the context of unbreaking the CI with the recent pythran version (which had snuck in a C++17 change), I wanted to explore if setting `'cpp_std=c++17'` in `meson.build` would unbreak CI. It did for the most part, but not on the meson + windows jobs, where it failed with
```
error: 'aligned_alloc' is not a member of 'std'
```

This should be [impossible](https://en.cppreference.com/w/cpp/memory/c/aligned_alloc) in C++17 mode, unless that compiler does not actually support C++17. Judging from the `-D__USE_MINGW_ANSI_STDIO=1` in the failing invocation, I have the sinking feeling that the use of MinGW for meson on windows, resp. the version of GCC therein, has now undone the prior assessment that we can use C++17.

<details>

Using a small patch to avoid a spurious warning
```diff
commit f4aff7ba54ecf5463f9fcb48038f74992df58331
Author: @h-vetinari <h.vetinari@gmx.com>
Date:   Tue May 2 21:38:37 2023 +1100

    be unambiguous when using std::aligned_alloc

diff --git a/scipy/fft/_pocketfft/pocketfft_hdronly.h b/scipy/fft/_pocketfft/pocketfft_hdronly.h
index 7d8ce9c9d..24f4a1f61 100644
--- a/scipy/fft/_pocketfft/pocketfft_hdronly.h
+++ b/scipy/fft/_pocketfft/pocketfft_hdronly.h
@@ -152,7 +152,7 @@ template<> struct VLEN<double> { static constexpr size_t val=2; };
 #if __cplusplus >= 201703L
 inline void *aligned_alloc(size_t align, size_t size)
   {
-  void *ptr = ::aligned_alloc(align,size);
+  void *ptr = std::aligned_alloc(align,size);
   if (!ptr) throw std::bad_alloc();
   return ptr;
   }
```
the result is

```
[1022/1624] Compiling C++ object scipy/fft/_pocketfft/pypocketfft.cp310-win_amd64.pyd.p/pypocketfft.cxx.obj
FAILED: scipy/fft/_pocketfft/pypocketfft.cp310-win_amd64.pyd.p/pypocketfft.cxx.obj 
"c++" "-Iscipy\fft\_pocketfft\pypocketfft.cp310-win_amd64.pyd.p" "-Iscipy\fft\_pocketfft" "-I..\scipy\fft\_pocketfft" "-IC:\hostedtoolcache\windows\Python\3.10.11\x64\Include" "-IC:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\pybind11\include" "-fvisibility=hidden" "-fvisibility-inlines-hidden" "-fdiagnostics-color=always" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-std=c++17" "-O2" "-g" "-D__USE_MINGW_ANSI_STDIO=1" "-DMS_WIN64=" "-DPOCKETFFT_NO_MULTITHREADING" -MD -MQ scipy/fft/_pocketfft/pypocketfft.cp310-win_amd64.pyd.p/pypocketfft.cxx.obj -MF "scipy\fft\_pocketfft\pypocketfft.cp310-win_amd64.pyd.p\pypocketfft.cxx.obj.d" -o scipy/fft/_pocketfft/pypocketfft.cp310-win_amd64.pyd.p/pypocketfft.cxx.obj "-c" ../scipy/fft/_pocketfft/pypocketfft.cxx
In file included from ../scipy/fft/_pocketfft/pypocketfft.cxx:19:
../scipy/fft/_pocketfft/pocketfft_hdronly.h: In function 'void* pocketfft::detail::aligned_alloc(std::size_t, std::size_t)':
../scipy/fft/_pocketfft/pocketfft_hdronly.h:155:20: error: 'aligned_alloc' is not a member of 'std'; did you mean 'aligned_union'?
  155 |   void *ptr = std::aligned_alloc(align,size);
      |                    ^~~~~~~~~~~~~
      |                    aligned_union
```

</details>

**Comment by andyfaff** [comment]
rtools43 has gcc12, compared to rtools40 using gcc10.3. I wonder if the newer gcc would solve the issue.

**Comment by h-vetinari** [comment]
I haven't checked the GCC version, but anything >=7 should give support for C++17, so it must be really old.

**Comment by rgommers** [comment]
This ticket says it's supported since 2020: https://osdn.net/projects/mingw/ticket/40315. However, searching the code base shows nothing, only `_aligned_malloc` and other `_aligned_*` functions: https://github.com/search?q=repo%3Amingw-w64%2Fmingw-w64+aligned_malloc&type=code.

@carlkl do you happen to know what is going on there?

**Comment by carlkl** [comment]
These functions are not suported by `Mingw-w64`. 
BTW: https://osdn.net/projects/mingw is the current repository of the original [MinGW](https://de.wikipedia.org/wiki/MinGW) project. `Mingw-w64` on the other side is a fork of of this project, see: [Mingw-w64 History](https://sourceforge.net/p/mingw-w64/wiki2/History/). 
As `Mingw-w64` is the base of all modern non-cygwin GCC based toolchains on Windows and `MinGW` is unmaintaned since at least 6 years there is no other way to ask the `Mingw-w64` maintainers to support these functions, if (and only if) they are really needed.

**Comment by carlkl** [comment]
There is already a bug report: [#964 delaration of function 'aligned_alloc' missing from stdlib.h](https://sourceforge.net/p/mingw-w64/bugs/964/)

**Comment by rgommers** [comment]
Thanks @carlkl!

This use of `aligned_alloc` is in our own code, so we could work around it. It's unclear what will happen next then though - this may not be the only use of `aligned_alloc` nor may it be the only C++17 function missing from Mingw-w64.

**Comment by carlkl** [comment]
I never stumbled upon this function. On a quick scan it seems, that this in an OS problem rather a problem of mingw-w64:
https://social.msdn.microsoft.com/Forums/azure/en-US/4617cd56-4c8d-4717-a96b-348ad3b2f149/why-isnt-c17s-stdalignedalloc-at-all-implemented?forum=vcgeneral
and
https://developercommunity.visualstudio.com/t/c17-stdaligned-alloc%E7%BC%BA%E5%A4%B1/468021

**Comment by rgommers** [comment]
Thanks for finding that @carlkl! Makes sense. I searched our code base and I think there's nothing else - Boost doesn't use this function, so it looks like a known and isolated issue. For any other C++ construct I usually get a ton of hits in Boost.

**Comment by h-vetinari** [comment]
> I never stumbled upon this function. On a quick scan it seems, that this in an OS problem rather a problem of mingw-w64:

Well, not exactly. It's an ABI problem (as always...), and Microsoft cannot provide a C symbol `aligned_alloc` without breaking something else. But they _do_ provide the functionality through [`_aligned_malloc`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/aligned-malloc), which is also how they implement C++17's `std::aligned_alloc`. Is there a fundamental reason (other than not having been implemented yet) why MinGW couldn't do the same under the hood?

**Comment by carlkl** [comment]
I guess `__mingw_aligned_malloc` and friends is what you are searching for.

**Comment by h-vetinari** [comment]
> or `_aligned_alloc`, see https://sourceforge.net/p/mingw-w64/discussion/723798/thread/ca63be68/

Wouldn't that be the responsability of mingw to resolve `std:aligned_alloc` correctly? It can hardly be the solution to patch every C++17 code base to mechanically replace `std:aligned_alloc` -> `_alligned_alloc`?

**Comment by h-vetinari** [comment]
Another C++17 sticking point that I forgot to note here from the issues surrounding pythran 0.13: the xsimd headers were using a C++17-ism (hexadecimal floating point [literal](https://en.cppreference.com/w/cpp/language/floating_literal)), which however didn't [compile](https://github.com/serge-sans-paille/pythran/pull/2100#issuecomment-1530962638) in our CI (with MinGW, but also on musl):

It got fixed by https://github.com/xtensor-stack/xsimd/commit/a1e07510dd81a0b074d2cef8e09bf8e59b926aae & backporting that to pythran.

If our compilers were fully C++17-ready, this error would obviously not have shown up.

**Comment by carlkl** [comment]
@h-vetinari, hexadecimal fomatting _is_ supported by mingw-w64. However, which toolchain is used today?

**Comment by lucascolley** [comment]
Can this be closed now that we have made the changes to bump to `cpp_std=c++17`?

**Comment by h-vetinari** [comment]
Yes, thanks
