### ISSUE TITLE
ENH: extensions of `factorial{,2,k}` for complex domains, recurrences, ...

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#18409]
Following the clean-up of #15600 in #15841, we can now discuss the extensions separately.

## Design Space

There are several dimensions that come into play:
- extensions to negative integers
- extensions to floats
- extensions to complex numbers
- extensions to poles through recurrence (possible e.g. for `factorial2`)

## Extension Issues

Some people would like to have the float/complex extensions of these functions (e..g. https://github.com/scipy/scipy/pull/15349). I tend to agree, but that raises another problem:

#### Complex extensions are incompatible with current inputs

First off, everything that's 0 currently on the negative axis gets a different value. More importantly, all even numbers get smaller by a factor ~0.79=sqrt(2/pi) in the [extension](https://en.wikipedia.org/wiki/Double_factorial#Complex_arguments).

For non-complex floats, there doesn't seem to be another relevant extension, especially not one that matches on all the integers and isn't just a gratuitous hack (this is what #15841 ended up stalling on for a long while). Compared to #15600 I now propose that floats continue to be treated as errors for `extend='zero'` in `factorial{2,k}`.

#### Extensions based on recurrence are incompatible with current status as well as complex extension

This came up for example in #15299. It's [possible](https://en.wikipedia.org/wiki/Double_factorial#Negative_arguments) (for example) to invert the recurrence relation n!! = n * (n-2)!!, and so extend the double-factorial to negative integers. The resulting value would be neither 0 (currently) nor the pole in the complex extension.

## Design Considerations

- Complex extensions  (together with non-positive floats) should be behind a keyword, roughly because:
  - 0-for-negative-values is a valid approach, and has been in scipy ~forever.
  - Since the values being produced are incompatible (for negative & even integers), the complex extension should be explicitly opt-in.
- Using recurrence relations for extending into poles is an open question; not sure if worth it, but if so, probably with another enum value for a potential `extend` keyword.
- Use the most general approximation, except when alternatives with better accuracy / performance exist.

## Possible Future Behaviour (note `extend=`, not `exact=`)

| Inputs | `factorial(`<br/>`extend=`<br/>`'zero')` | `factorial(`<br/>`extend=`<br/>`'complex')` | `factorial2(`<br/>`extend=`<br/>`'zero')` | `factorial2(`<br/>`extend=`<br/>`'complex')` | `factorialk(`<br/>`extend=`<br/>`'zero')` | `factorialk(`<br/>`extend=`<br/>`'complex')` |
|-|-|-|-|-|-|-|
| Scalar positive integer&nbsp;w/ `exact=True` | n! | n! | n!! | n!! | n!(k) | n!(k) |
| Scalar positive integer | Γ(n+1) | Γ(n+1) | [1a] for odd,<br/>[1b] for even<br/>(matches n!!) | [1a] (_doesn't_<br/>match n!!<br/>for even n) | n!(k)<br/>(no approx.) | [2] |
| Scalar negative integer / poles | 0.0 | NaN | 0.0 | NaN | 0.0 | NaN |
| Scalar positive float | Γ(n+1) | Γ(n+1) | `ValueError` | [1a] | `ValueError` | [2] |
| Scalar negative float | 0.0 | Γ(n+1) | `ValueError` | [1a] | `ValueError` | [2] |
| Scalar complex | `ValueError` | Γ(n+1) | `ValueError` | [1a] | `ValueError` | [2] |
| Scalar NaN | NaN | NaN | NaN | NaN | NaN | NaN |
| Positive integer in array | Γ(n+1) | Γ(n+1) |[1a] for odd,<br/>[1b] for even<br/>(matches n!!) | [1a] (_doesn't_<br/>match n!!<br/>for even n) | n!(k)<br/>(no approx.) | [2] |
| Negative integer in array | 0.0 | NaN | 0.0 | NaN | 0.0 | NaN |
| Positive float in array | Γ(n+1) | Γ(n+1) | `ValueError` | [1a] | `ValueError` | [2] |
| Negative float in array | 0.0 | Γ(n+1) | `ValueError` | [1a] | `ValueError` | [2] |
| Complex in array | `ValueError` | Γ(n+1) | `ValueError` | [1a] | `ValueError` | [2] |
| NaN in array | NaN | NaN | NaN | NaN | NaN | NaN |
| Empty array | `array([])` | `array([])` | `array([])` | `array([])` | `array([])` | `array([])` |

The formulas in question are:
* [1a]: `z!! = 2^((z-1)/2) Γ(z/2 + 1) / Γ(1/2 + 1) == 2^(z/2) Γ(z/2 + 1) sqrt(2 / π)` (holds exactly for odd integers and is the basis for the extension)
* [1b]: `z!! = 2^(z/2) Γ(z/2 + 1)` (holds only for even integers)
* [2]: `z!(α) =  α^((z-1)/α) Γ(z/α + 1) / Γ(1/α + 1)` (extension based on α'th integers)

I'd very much welcome feedback on this - there are some trade-offs to be made (e.g. whether negative floats should also raises without `extend='complex'`, etc.)

**Comment by tovrstra** [comment]
Not a general comment, but just a remark on one specific case.

In SciPy-1.10.*, the result of `factorial2(-1)` was `1` and this changed to `0` in version 1.11, which was an unexpected change that broke a library I'm involved in. We relied on the old behavior for the implementation of integrals involving products of Gaussian functions. In the recurrence relations for these integrals, `factorial2(2*n-1)` often appears in denominators, where `n` can be zero or a positive integer.

In case of the double factorial, it is common to define a meaningful result for negative odd integer arguments, see e.g. https://en.wikipedia.org/wiki/Double_factorial#Negative_arguments. Is there any chance of supporting odd negative arguments in `factorial2`? (Note that this is not related to complex arguments, but rather comes from a generalization of the standard recurrence relation.)

**Comment by h-vetinari** [comment]
> Is there any chance of supporting odd negative arguments in `factorial2`?

Yes it's possible; I mentioned this in the OP already:🙃 

> This came up for example in #15299. It's [possible](https://en.wikipedia.org/wiki/Double_factorial#Negative_arguments) (for example) to invert the recurrence relation n!! = n * (n-2)!!, and so extend the double-factorial to negative integers. The resulting value would be neither 0 (currently) nor the pole in the complex extension.

Personally I was waiting for 1.12 to branch before touching the factorial functions again, but feel free to raise a PR!

**Comment by tovrstra** [comment]
Sorry for having completely missed your point. I should have gone for that coffee first. The reason I didn't get it, is that in the rows "Scalar negative integer / poles" and "Negative integer in array" contain 0.0 or NaN. Shouldn't these follow the same rules? Letting the outcome depend on the dtype of the argument may cause a lot of confusion.

Do you suggest a PR for a 1.11.x version in which support for negative odd arguments is added to `factorial2` without changing the API? Or do you prefer to go for the API change right away?

**Comment by h-vetinari** [comment]
What I'm suggesting - as described in the OP (so you picked the right issue!) - is to add a keyword argument `extend=` to `factorial2` that allows _opting into_ a different behaviour for `n<0`. In your case, using the values that arise from the recurrence relation. Independently of that, we'll also want to eventually allow using the complex extension, which the design allows without further overhauls.

> P.S. I'm not convinced by the backward compatibility argument to treat integers differently. With 1.11, backward compatibility is already broken.

Yes, it was breakage we accepted (perhaps wrongly without a deprecation period), see https://github.com/scipy/scipy/issues/18813

**Comment by tovrstra** [comment]
Thanks for clarifying, and sorry for having missed some points. Just to avoid confusion, I'd rather ask a few more questions:
- The proposal is to have `extend="zero"` as the default value, because this is the current behavior?
- For our use case, the option `extend="recurrence"` would need to be implemented in `factorial2`? (It's not in the table, but this seems to make sense.)
- The `extend="recurrence"` is only meaningful for (some) integer arguments of `factorial2`. Would you return `NaN` when it is combined with a `float` or `complex` argument, or when a negative even integer argument is given?

**Comment by h-vetinari** [comment]
> The proposal is to have `extend="zero"` as the default value, because this is the current behavior?

Yes

> For our use case, the option `extend="recurrence"` would need to be implemented in `factorial2`?

Yes

> The `extend="recurrence"` is only meaningful for (some) integer arguments of `factorial2`. Would you return `NaN` when it is combined with a `float` or `complex` argument, or when a negative even integer argument is given?

Raising an error for known-to-be-incompatible values is the best approach IMO.

**Comment by h-vetinari** [comment]
Alright, I have a branch that implements almost all of this (except the recurrence for `factorial2`) based on #19716 / #19703. In order to have any chance at review/understandability, I split off a bunch of the required changes & clean-ups into separate commits. So far, I'm planning to have at least 3 PRs after that one (cleanup, complex support, unification), but happy to slice and dice things into more PRs if desired:
```
d9b4a04e6 (HEAD -> factorial_unify) MAINT: unify implementations for factorial{,2,k}
6c637c736 MAINT: add short-cut to _range_prod and unify calling pattern also for factorial
5459ca712 (factorial_complex) MAINT: also test infinities for factorial{,2,k}
8253d8b62 ENH: extend factorial{,2,k} to allow complex inputs
dd78431b2 MAINT: remove helpmsg from factorialk errors; will reach parity with factorial{,2}
95b57d7ac MAINT: prepare tests for `extend=` kwarg of factorial{,2,k}
ffe4e9595 (factorial_cleanup) MAINT: minor test refactors & clean-ups for factorial functions
50b778323 MAINT: ensure assert_allclose uses useful tolerance for factorial{,2,k} tests
5659b9b59 MAINT: also test factorial{,2,k} with complex NaNs
881c15451 MAINT: homogenise cases in test_factorialk_array_corner_cases
37c1c0f2a MAINT: be consistent about dtype in factorial{,2,k} also for empty/None.
0f452cb0e MAINT: refactor test_factorial*_corner_cases and test_factorialx_nan
d1f3566d7 MAINT: harmonise factorial{,2,k} error message for unsupported types
650f19f49 MAINT: break out test for `factorialk(..., exact=None)`
c29bca08c MAINT: break out assert_really_equal utility, teach it rtol
f6d56747c MAINT: introduce subtype helper function for factorial{,2,k}
955fd4825 MAINT: improve testing of correct dtypes in test_factorial_array_corner_cases
33dcbc4df (factorialk_approx) MAINT: avoid unnecessary calculations in factorialk-approximation  == #19716
f5908b30d MAINT: unify factorialx approximation function
1acd17c31 MAINT: make naming of auxiliary functions for factorial{,2,k} more consistent
d12062e49 ENH: enable approximation for factorialk
```

```
git diff factorialk_approx..factorial_complex --stat
 scipy/special/_basic.py           | 310 +++++++++++++----
 scipy/special/tests/test_basic.py | 683 ++++++++++++++++++++++++++++----------
 2 files changed, 756 insertions(+), 237 deletions(-)
```

**Comment by tovrstra** [comment]
Thanks! That's good news. I may be able to help with reviewing, but my availability is limited in January.

**Comment by h-vetinari** [comment]
Since this issue mainly itself almost exclusively with the complex extension, I've opened an issue for the only remaining concrete extension proposal I'm aware of: #21874

**Comment by h-vetinari** [comment]
> The factors like `cos(pi*x)` used in the other extensions look almost like an artificial way to avoid this though which makes me wonder if any extension beyond integers is particularly meaningful.

That's exactly what caused me to [stop](https://github.com/scipy/scipy/pull/15841#discussion_r850264410) and think about this, which ended up causing the initial implementation work for this to slip by about a year or so.

I stand behind the conclusion that
> AFAICT, the choice of modulation term `(pi / 2) ** ((cos(pi * z) - 1)/4)` is completely arbitrary and just a "nice" choice to get an exponent that does the right thing at even/odd integers.

Worse than being arbitrary, it violates some fundamental [qualities](https://en.wikipedia.org/wiki/Bohr%E2%80%93Mollerup_theorem) like convexity, and there are cases which actually rely on the divergence at the even integers - e.g. this formula for the volume of the n-dimensional hypersphere:
```
V_n = (2 * (2 \pi) ^ ((n-1)/2)) / n!! * R^n
```

Ultimately it seemed like the much saner choice to go with the underlying mathematical facts (e.g. the `factorial2` extension is only _defined_ through the odd integers, and forcing them to fit for the even ones does more harm than good). That's why the docstring prominently warns about the fact that the values change at even integers, if using the complex extension. I consider it a mathematical fact of life (and it's not too difficult add the exponential factor for those who care). 🙃

**Comment by h-vetinari** [comment]
> Ultimately it seemed like the much saner choice to go with the underlying mathematical facts (e.g. the `factorial2` extension is only _defined_ through the odd integers, and forcing them to fit for the even ones does more harm than good).

Ah, and it would have been more or less impossible to extend this generically to `factorialk`, if we had tried to "fix" the extension in this way. See also https://github.com/scipy/scipy/commit/6a027ff89f8a7e42ae9b2c48d28561befb8c751f and
https://github.com/scipy/scipy/blob/bc4b0e9764833597b3fab8859ebe3034aae51c15/scipy/special/_basic.py#L3002-L3004
(which we would have had to try to fix into an analytical correction factor that's valid for all complex n & k).

**Comment by oscarbenjamin** [comment]
> Ultimately it seemed like the much saner choice to go with the underlying mathematical facts (e.g. the `factorial2` extension is only _defined_ through the odd integers,

I think it makes more sense to just think of these as different functions though like there is `factorial2` which is only for integers and then some other function like `gamma2` or something that is for complex values and lines up with `factorial2` only for some integers. The implementation here with the extension kwarg effectively makes it two separate functions but maybe it would be better if they actually had different names.

Is there any prior art for using the definition that SciPy is using here or for alternatives perhaps using different names?

**Comment by h-vetinari** [comment]
> Is there any prior art for using the definition that SciPy is using here or for alternatives perhaps using different names?

I'm not aware of anything. At the time, I tried to look for a reference for the factorial2 extension, and came to the conclusion that it was just a mathematical hack.

I disagree that the extension should be named `gamma2`. It's an extension of `factorial2` to the complex plane, and it deserves that name IMO. Acknowledging how that extension process to the complex numbers actually works (i.e. it really only is an extension for the function as defined on values  `==1 (mod k)`) does not justify inventing a name (which would be IMO a much worse overreach liable to get us into hot water, e.g. it could be confused with the digamma function, since "di-" means two).

**Comment by oscarbenjamin** [comment]
> I disagree that the extension should be named `gamma2`.

That was a throwaway name.

> It's an extension of `factorial2` to the complex plane

It isn't really an extension if its restriction to integers doesn't agree with the original function.

> does not justify inventing a name

I think if it is a different function then it should have a different name.

Right now I'm not sure if it makes sense to try to extend SymPy's factorial2 function at all. It is currently defined only for nonnegative or odd integers. It looks like other libraries have used somewhat artificial extensions. The definition here seems like a more reasonable function for real or complex values but is not compatible for integer values. To me that seems like it should be a different function and maybe we should keep `factorial2` only for integer values.

**Comment by h-vetinari** [comment]
> > It's an extension of `factorial2` to the complex plane
> 
> It isn't really an extension if its restriction to integers doesn't agree with the original function.

There are different trade-offs to make in an extension. You cannot force the extension to match `factorial2(n)` at all integers _and_ maintain key properties like logarithmic convexity. In principle you could choose any residue class modulo k to make your extension (so you could likewise choose the one that's correct for even integers), but realistically the only sensible choice is the one that satisfies `f(1) = 1`:
https://github.com/scipy/scipy/blob/bc4b0e9764833597b3fab8859ebe3034aae51c15/scipy/special/_basic.py#L3312-L3329

The consistency between these different definitions and their properties is not optional. I consider it a much worse mathematical "crime" to just randomly add factors to a well-defined mathematical concept like an analytical extension, rather than to accept that it does not match the the integer definition everywhere _by necessity_. You can come up with infinitely many analytical functions that pass through the points `(n, n!!)`, but only one (up to a multiplicative factor) that can actually claim to be the canonical extension.

**Comment by oscarbenjamin** [comment]
> The consistency between these different definitions and their properties is not optional.

What is optional is whether or not to extend the function at all. It seems to me that the basic integer definition of double factorial does not extend in a sensible way to real or complex numbers. What you have here is an extension of a different function and as reasonable as that choice may be I don't think that I would want SymPy to do the same without giving the function a different name.

**Comment by h-vetinari** [comment]
> What is optional is whether or not to extend the function at all. It seems to me that the basic integer definition of double factorial does not extend in a sensible way to real or complex numbers.

I agree.

> What you have here is an extension of a different function

I disagree. IMO you get too attached to the values at the integers, which are an infinitessimally small subset of the complex plane -- the function is much more closely determined by its behaviour, mathematical properties and functional equation. Especially for symbolic calculation, the latter would appear of bigger importance to me.

The definition of the k-factorial fundamentally has something to do with a process modulo k, and if you want to extend that behaviour canonically (and not just by haphazardly), you get a family of functions for the various residue classes of k (which are just a constant multiple apart). So these are not extensions of a different function, but so-closely-related-you-can't-tell-the-difference actualisations of the same function, based on different subsets modulo k (although of course I understand the source of our difference in opinion; it'd be nice if the distinction wasn't necessary, but analytical continuation often has unintuitive behaviour 🤷).

> I don't think that I would want SymPy to do the same without giving the function a different name.

That's your prerogative of course.
