### ISSUE TITLE
BUG: Windows compilation error with Intel Fortran in PROPACK

### ISSUE THREAD

**Issue by hovavalon** [scipy/scipy#18415]
### Describe your issue.

@rgommers
Resuming conversation from #17928.

### Reproducing Code Example

After updating my code from #18411 I still get a compilation error while compiling with `python dev.py build` with MSVC and the Intel Fortran compiler.

### Error message

```shell
ninja: Entering directory `C:\Users\alonho\OneDrive - Shamir Optical Industry Ltd\src\scipy\build'
[3/1176] Linking static target scipy/sparse/linalg/_propack/liblib__dpropack.a
PROPACK_double_dmgs.pentium.F.obj : warning LNK4006: dmgs_ already defined in PROPACK_double_dmgs.risc.F.obj; second definition ignored
[4/1176] Linking target scipy/sparse/linalg/_propack/_spropack.cp310-win_amd64.pyd
FAILED: scipy/sparse/linalg/_propack/_spropack.cp310-win_amd64.pyd scipy/sparse/linalg/_propack/_spropack.cp310-win_amd64.pdb
"xilink.exe"  /MACHINE:x64 /OUT:scipy/sparse/linalg/_propack/_spropack.cp310-win_amd64.pyd scipy/sparse/linalg/_propack/_spropack.cp310-win_amd64.pyd.p/meson-generated_..__spropack-f2pywrappers.f.obj scipy/sparse/linalg/_propack/_spropack.cp310-win_amd64.pyd.p/meson-generated_..__spropackmodule.c.obj "/nologo" "/DEBUG" "/PDB:scipy\sparse\linalg\_propack\_spropack.cp310-win_amd64.pdb" "/DLL" "/IMPLIB:scipy\sparse\linalg\_propack\_spropack.cp310-win_amd64.lib" "scipy\sparse\linalg\_propack\liblib__spropack.a" "scipy\lib_fortranobject.a" "C:/Users/alonho/AppData/Local/anaconda3/envs/scipy-dev/Library/lib/openblas.lib" "C:\Users\alonho\AppData\Local\anaconda3\envs\scipy-dev\libs\python310.lib"
   Creating library scipy\sparse\linalg\_propack\_spropack.cp310-win_amd64.lib and object scipy\sparse\linalg\_propack\_spropack.cp310-win_amd64.exp
liblib__spropack.a(PROPACK_single_second.F.obj) : error LNK2019: unresolved external symbol etime_ referenced in function second_
liblib__spropack.a(PROPACK_single_second.F.obj) : error LNK2001: unresolved external symbol realetime_
scipy\sparse\linalg\_propack\_spropack.cp310-win_amd64.pyd : fatal error LNK1120: 2 unresolved externals
[9/1176] Linking target scipy/sparse/csgraph/_shortest_path.cp310-win_amd64.pyd
   Creating library scipy\sparse\csgraph\_shortest_path.cp310-win_amd64.lib and object scipy\sparse\csgraph\_shortest_path.cp310-win_amd64.exp
[13/1176] Compiling Fortran object scipy/sparse/linalg/_propack/liblib__cpropack.a.p/PROPACK_complex8_cgemm_ovwr.F.obj
ninja: build stopped: subcommand failed.
Build failed!
```

### SciPy/NumPy/Python version and system information

```shell
Windows 11, MSVC 17, scipy main branch with update from PR mentioned above.
```

**Comment by rgommers** [comment]
Thanks @hovavalon. That looks familiar, the problem is that `etime` is a GNU extension and it's named differently in the Intel Fortran library. The correct fix is to remove any use of `second` in the PROPACK sources, but since that's a submodule that's a bit of a pain. For right now I think the last commit in this branch will work around the problem: https://github.com/rgommers/scipy/tree/ifort-second. I don't have a Windows machine at hand, so I hope I got that right.

**Comment by rgommers** [comment]
I submitted the more structural fix in gh-18421, removing all usages of `second`. That will definitely fix this problem; I'm curious if you then get the build to complete @hovavalon or if there is something else.

**Comment by hovavalon** [comment]
Actually there are still failures, maybe due to missing packages:
`C:\Users\USER\anaconda3\envs\scipy-dev\lib\site-packages\pythran\pythonic/include/numpy/ceil.hpp(8): fatal error C1083: Cannot open include file: 'xsimd/xsimd.hpp': No such file or directory`

There are also additional compilation errors but I think they might be consequences of the first one, here are two samples:
```
C:\\Users\\USER\\anaconda3\\envs\\scipy-dev\\lib\\site-packages\\pythran\\pythonic/include/types/ndarray.hpp(481): error C2559: 'std::enable_if<`anonymous-namespace'::pythonic::types::is_numexpr_arg<F>::value&&std::is_same<bool,F::dtype>::value&&F::value==1&&!`anonymous-namespace'::pythonic::types::is_pod_array<F>::value,`anonymous-namespace'::pythonic::types::numpy_vexpr<`anonymous-namespace'::pythonic::types::ndarray<T,pS>,`anonymous-namespace'::pythonic::types::ndarray<long,`anonymous-namespace'::pythonic::types::pshape<long>>>>::type `anonymous-namespace'::pythonic::types::ndarray<T,pS>::operator [](const F &) const': cannot overload a member function without ref-qualifier with a member function with ref-qualifier

 C:\\Users\\USER\\anaconda3\\envs\\scipy-dev\\lib\\site-packages\\pythran\\pythonic/types/numpy_expr.hpp(207): error C2244: '`anonymous-namespace'::pythonic::types::numpy_expr<O,Args...>::map_fast': unable to match function definition to an existing declaration
```

All other errors are also `C2244` and `C2559`.

**Comment by h-vetinari** [comment]
> Actually there are still failures, maybe due to missing packages:

That one should be easy to fix by installing xsimd in your environment (though pythran also vendors the headers, so presumably you could also just point the include path there)

**Comment by hovavalon** [comment]
I actually already have the package installed, so this is quite odd.
```
(scipy-dev) C:\Users\USER\Desktop\src\scipy>conda install xsimd                                                                                                                                                                              Collecting package metadata (current_repodata.json): done                                                                                                                                                                                    Solving environment: done                                                                                                                                                                                                                                                                                                                                                                                                                                                                 # All requested packages already installed
```
I checked and this is unrelated to the fortran compiler, as it also happens with the `rtools40` compilers.
Also, there is a `xsimd` directory in the anaconda library path.

**Comment by rgommers** [comment]
This seems to be the same as https://github.com/scipy/scipy/issues/15698#issuecomment-1068374269. The reason there seemed to be a missing `CXXFLAGS` after environment activation. In the case there it was due to using the Fish shell rather than the Bash one on Linux. One of the linked issues seems to say that all non-Bash shells are having problems. Probably on Windows the same is happening?

This is quite an annoying issue, and we should see if we can apply a workaround. @hovavalon what shell are you using exactly?

> I have solved this temporarily by copying the `xsmid` directory from `C:\Users\USER\anaconda3\envs\scipy-dev\Library\include` to `C:\Users\USER\anaconda3\envs\scipy-dev\include`.

@hovavalon with that workaround, does the build complete now?

**Comment by rgommers** [comment]
gh-18439 should fix the `xsimd` header detection for conda users on all OSes I believe.

**Comment by hovavalon** [comment]
@rgommers Yes, the build process did complete.

**Comment by rgommers** [comment]
Awesome, thanks for confirming!
