### ISSUE TITLE
Error installing scipy on a Mac

### ISSUE THREAD

**Issue by adamingram** [scipy/scipy#18448]
Hi,
I'm getting an error when I try to install scipy on my MacBook (MacBook Air M1 202 running OS 11.6.8) using pip (pip3 install scipy). The error message is written out below in full, but the thing that makes me write here is that it says "note: This is an issue with the package mentioned above, not pip.". Also, I have been able to install other packages (e.g. numpy). The version of python I'm using is python3 installed via Homebrew. I also tried forcing pip to not used the cached file, but got the same error message. Any suggestions would be greatly appreciated.

Full error message:
% pip3 install scipy
Collecting scipy
  Using cached scipy-1.10.1.tar.gz (42.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      The Meson build system
      Version: 1.1.0
      Source dir: /private/var/folders/r5/zz21mh8x15zbsrm9_h8qlk4w0000gn/T/pip-install-shkfde4i/scipy_60039a3674194b4d8e22d0f6d5745d1c
      Build dir: /private/var/folders/r5/zz21mh8x15zbsrm9_h8qlk4w0000gn/T/pip-install-shkfde4i/scipy_60039a3674194b4d8e22d0f6d5745d1c/.mesonpy-a8z82uz1/build
      Build type: native build
      Project name: SciPy
      Project version: 1.10.1
      C compiler for the host machine: /usr/bin/clang (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.30)")
      C linker for the host machine: /usr/bin/clang ld64 711
      C++ compiler for the host machine: /usr/bin/clang++ (clang 13.0.0 "Apple clang version 13.0.0 (clang-1300.0.29.30)")
      C++ linker for the host machine: /usr/bin/clang++ ld64 711
      Cython compiler for the host machine: cython (cython 0.29.34)
      Host machine cpu family: aarch64
      Host machine cpu: aarch64
      Compiler for C supports arguments -Wno-unused-but-set-variable: NO
      Compiler for C supports arguments -Wno-unused-function: YES
      Compiler for C supports arguments -Wno-conversion: YES
      Compiler for C supports arguments -Wno-misleading-indentation: YES
      Compiler for C supports arguments -Wno-incompatible-pointer-types: YES
      Library m found: YES
      Fortran compiler for the host machine: /opt/homebrew/bin/gfortran-12 (gcc 12.2.0 "GNU Fortran (Homebrew GCC 12.2.0) 12.2.0")
      Fortran linker for the host machine: /opt/homebrew/bin/gfortran-12 ld64 711
      Compiler for Fortran supports arguments -Wno-conversion: YES
      Checking if "-Wl,--version-script" : links: NO
      Program cython found: YES (/private/var/folders/r5/zz21mh8x15zbsrm9_h8qlk4w0000gn/T/pip-build-env-40k5htbk/overlay/bin/cython)
      Program python found: YES (/opt/homebrew/Cellar/python@3.11/3.11.3/bin/python3.11)
      Found pkg-config: /opt/local/bin/pkg-config (0.29.2)
      Program pythran found: YES (/private/var/folders/r5/zz21mh8x15zbsrm9_h8qlk4w0000gn/T/pip-build-env-40k5htbk/overlay/bin/pythran)
      Run-time dependency threads found: YES
      Library npymath found: YES
      Library npyrandom found: YES
      Did not find CMake 'cmake'
      Found CMake: NO
      Run-time dependency openblas found: NO (tried pkgconfig, framework and cmake)
      Run-time dependency openblas found: NO (tried pkgconfig and framework)
      
      ../../scipy/meson.build:134:7: ERROR: Dependency "OpenBLAS" not found, tried pkgconfig and framework
      
      A full log can be found at /private/var/folders/r5/zz21mh8x15zbsrm9_h8qlk4w0000gn/T/pip-install-shkfde4i/scipy_60039a3674194b4d8e22d0f6d5745d1c/.mesonpy-a8z82uz1/build/meson-logs/meson-log.txt
      + meson setup --prefix=/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11 /private/var/folders/r5/zz21mh8x15zbsrm9_h8qlk4w0000gn/T/pip-install-shkfde4i/scipy_60039a3674194b4d8e22d0f6d5745d1c /private/var/folders/r5/zz21mh8x15zbsrm9_h8qlk4w0000gn/T/pip-install-shkfde4i/scipy_60039a3674194b4d8e22d0f6d5745d1c/.mesonpy-a8z82uz1/build --native-file=/private/var/folders/r5/zz21mh8x15zbsrm9_h8qlk4w0000gn/T/pip-install-shkfde4i/scipy_60039a3674194b4d8e22d0f6d5745d1c/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by tylerjereddy** [comment]
> MacBook Air M1 202 running OS 11.6.8

You need OS version `>= 12.x` on the ARM series Macs for PyPI wheel/binary installs. We have some closed issues that describe the situation in more detail, but that's the short version of it.

**Comment by adamingram** [comment]
Many thanks. I will take a deep breath and upgrade!
