### ISSUE TITLE
ENH: Allow passing non-varying arguments for the model function to scipy.optimize.curve_fit

### ISSUE THREAD

**Issue by scottshambaugh** [scipy/scipy#18456]
### Is your feature request related to a problem? Please describe.

I have a function which I am trying to curve fit some parameters for, but it also depends on other parameters that I want to manually control. This is not natively supported at the moment.

Taking the example from the [scipy.optimize.curve_fit](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.curve_fit.html) docs, say that I have a function such as below, but I am only trying to fit `a`, and `b`, and I know `c`. There is currently no way to pass in `c`, and the only way around this is to modify it in the local scope outside the function, which is rather messy and is not very conducive to modularity.
```python
def func(x, a, b, c):
    return a * np.exp(-b * x) + c
```

### Describe the solution you'd like.

Other optimization functions such as [scipy.optimize.minimize_scalar](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize_scalar.html) allow for passing in an `args` tuple which does exactly this - "Extra arguments passed to the objective function". I haven't done a full sweep of all the functions in the optimization module, but I would propose that `args` be extended to all of them.

The assumption for the function would then be:
```python
ydata = f(xdata, *params, *args) + eps
```

I would want to call this like the below:
```python
c = 10
(a, b), cov = curve_fit(func, xdata, ydata, args=(c,)
```

**Comment by rkern** [comment]
Use [`functools.partial`](https://docs.python.org/3/library/functools.html#functools.partial) to wrap up your function in one that provides the fixed argument.

```
(a, b), cov = curve_fit(partial(func, c=10), xdata, ydata)
```

Most of the `args, kwds` arguments in other functions predated the availability of `functools.partial`. We encourage the use of `functools.partial` these days so we don't have to place that machinery everywhere, and we can simplify our implementations.

**Comment by scottshambaugh** [comment]
Thanks @rkern! Is it possible to reopen this issue as a documentation request then? That info is new to me and I don't think the docs page covers that option.

**Comment by mdhaber** [comment]
I'll add it to the optimize tutorial shortly.

**Comment by mdhaber** [comment]
Actually, I already did in gh-17674. That uses a wrapper function, but I could add `partial`, too.
