### ISSUE TITLE
Code alignment issues

### ISSUE THREAD

**Issue by qqwqqw689** [scipy/scipy#18479]
![image](https://github.com/scipy/scipy/assets/114795525/e826b007-ed42-491c-b451-42e68c021f3d)

I think the "else" in this code should align with the first "if".(better readability?) 

code location :  https://github.com/scipy/scipy/blob/main/scipy/signal/__init__.py

**Comment by ilayn** [comment]
in python `for` loops can end with `else` blocks to run when the for loop is exhausted without breaks. Hence the else block belongs to `for` and not `if` https://docs.python.org/3/tutorial/controlflow.html#break-and-continue-statements-and-else-clauses-on-loops
