### ISSUE TITLE
DEP: Warn on deprecated windows-import in base `scipy.signal` namespace

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#18484]
This was discussed in #7898 and executed in #7900 for SciPy 1.1. However, the deprecation mechanism there only inserts a warning into the docstring.

I think we should start emitting actual DeprecationWarnings for those functions that are imported from the wrong name space (i.e. `scipy.signal.<x>` instead of `scipy.signal.windows.<x>`).

CC @larsoner @rgommers

**Comment by rgommers** [comment]
That sounds good to me, it's been long enough.

**Comment by h-vetinari** [comment]
OK cool. Milestoning this for 1.11, in case we can still squeeze it in. FYI, in case you're interested @j-bowhay ;-)

**Comment by larsoner** [comment]
Agreed!
