### ISSUE TITLE
BUG: optimize.direct is executing maxiter + (maxiter-1) iterations rather than just maxiter iterations

### ISSUE THREAD

**Issue by thcasey3** [scipy/scipy#18490]
### Describe your issue.

The function optimize.direct iterates more than 'maxiter' when 'maxiter' is given. The excess is always equal to whatever is given for 'maxiter' minus 1. So, if maxiter=10, 19 iterations are performed. If maxiter=6, 11 iterations are performed. etc.

### Reproducing Code Example

```python
from scipy.optimize import direct, Bounds
global n
n = 0

def func(x):
    global n
    n += 1
    print(f"Iteration {n}")
    return 0

rslt = direct(
    lambda x: func(x),
    bounds=Bounds(lb=1, ub=10),
    maxiter=10,
)
```

### Error message

```shell
no error, just wrong behavior
```

### SciPy/NumPy/Python version and system information

```shell
scipy 1.10.1
numpy 1.24.3
python 3.9.13 or 3.11.1
sys.version_info(major=3, minor=11, micro=1, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment]
The result object of your code prints like:

```
message: Number of iterations is larger than maxiter=10
 success: False
  status: 2
     fun: 0.0
       x: [ 5.500e+00]
     nit: 10
    nfev: 19
```

19 function evaluations, but 10 iterations of the algorithm - approximately two evaluations per iteration. If you want to control the number of function evaluations, use `maxfun`. Note that `maxfun` is "Approximate upper bound on objective function evaluations.", so an off by one error will not be considered to be a bug.

**Comment by thcasey3** [comment]
@mdhaber ok got it, thanks
