### ISSUE TITLE
DEP: decide and act about `PRIVATE_BUT_PRESENT_MODULES`

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#18491]
In the context of #14360 & #15040, we cleaned up a lot of our module API and deprecated those that are supposed to be private, for removal that's scheduled for SciPy 2.0

This was primarily (only?) done for the first-level modules though, not further down the tree. The added test [infrastructure](https://github.com/scipy/scipy/blob/main/scipy/_lib/tests/test_public_api.py) contains:
```python
# The PRIVATE_BUT_PRESENT_MODULES list contains modules that look public (lack
# of underscores) but should not be used.  For many of those modules the
# current status is fine.  For others it may make sense to work on making them
# private, to clean up our public API and avoid confusion.
# These private modules support will be removed in SciPy v2.0.0
PRIVATE_BUT_PRESENT_MODULES = [
    ...
```

IMO, without tracking what needs to be done (deprecate and make private, or keep public) and then doing it, we won't be in a position to actually execute this for SciPy 2.0, hence I'm opening this issue. Ideally we decide per module what needs to be done, and then do it, so we can actually remove what we'd like to remove when the time comes.

 - [ ] `scipy.constants.codata`
 - [ ] `scipy.constants.constants`
 - [ ] `scipy.fftpack.basic`
 - [ ] `scipy.fftpack.convolve`
 - [ ] `scipy.fftpack.helper`
 - [ ] `scipy.fftpack.pseudo_diffs`
 - [ ] `scipy.fftpack.realtransforms`
 - [ ] `scipy.integrate.odepack`
 - [ ] `scipy.integrate.quadpack`
 - [ ] `scipy.integrate.dop`
 - [ ] `scipy.integrate.lsoda`
 - [ ] `scipy.integrate.vode`
 - [ ] `scipy.interpolate.dfitpack`
 - [ ] `scipy.interpolate.fitpack`
 - [ ] `scipy.interpolate.fitpack2`
 - [ ] `scipy.interpolate.interpnd`
 - [ ] `scipy.interpolate.interpolate`
 - [ ] `scipy.interpolate.ndgriddata`
 - [ ] `scipy.interpolate.polyint`
 - [ ] `scipy.interpolate.rbf`
 - [ ] `scipy.io.arff.arffread`
 - [ ] `scipy.io.harwell_boeing`
 - [ ] `scipy.io.idl`
 - [ ] `scipy.io.mmio`
 - [ ] `scipy.io.netcdf`
 - [ ] `scipy.io.matlab.byteordercodes`
 - [ ] `scipy.io.matlab.mio`
 - [ ] `scipy.io.matlab.mio4`
 - [ ] `scipy.io.matlab.mio5`
 - [ ] `scipy.io.matlab.mio5_params`
 - [ ] `scipy.io.matlab.mio5_utils`
 - [ ] `scipy.io.matlab.mio_utils`
 - [ ] `scipy.io.matlab.miobase`
 - [ ] `scipy.io.matlab.streams`
 - [ ] `scipy.linalg.basic`
 - [ ] `scipy.linalg.decomp`
 - [ ] `scipy.linalg.decomp_cholesky`
 - [ ] `scipy.linalg.decomp_lu`
 - [ ] `scipy.linalg.decomp_qr`
 - [ ] `scipy.linalg.decomp_schur`
 - [ ] `scipy.linalg.decomp_svd`
 - [ ] `scipy.linalg.flinalg`
 - [ ] `scipy.linalg.matfuncs`
 - [ ] `scipy.linalg.misc`
 - [ ] `scipy.linalg.special_matrices`
 - [ ] `scipy.misc.common`
 - [ ] `scipy.misc.doccer`
 - [ ] `scipy.ndimage.filters`
 - [ ] `scipy.ndimage.fourier`
 - [ ] `scipy.ndimage.interpolation`
 - [ ] `scipy.ndimage.measurements`
 - [ ] `scipy.ndimage.morphology`
 - [ ] `scipy.odr.models`
 - [ ] `scipy.odr.odrpack`
 - [ ] `scipy.optimize.cobyla`
 - [ ] `scipy.optimize.cython_optimize`
 - [ ] `scipy.optimize.lbfgsb`
 - [ ] `scipy.optimize.linesearch`
 - [ ] `scipy.optimize.minpack`
 - [ ] `scipy.optimize.minpack2`
 - [ ] `scipy.optimize.moduleTNC`
 - [ ] `scipy.optimize.nonlin`
 - [ ] `scipy.optimize.optimize`
 - [ ] `scipy.optimize.slsqp`
 - [ ] `scipy.optimize.tnc`
 - [ ] `scipy.optimize.zeros`
 - [ ] `scipy.signal.bsplines`
 - [ ] `scipy.signal.filter_design`
 - [ ] `scipy.signal.fir_filter_design`
 - [ ] `scipy.signal.lti_conversion`
 - [ ] `scipy.signal.ltisys`
 - [ ] `scipy.signal.signaltools`
 - [ ] `scipy.signal.spectral`
 - [ ] `scipy.signal.spline`
 - [ ] `scipy.signal.waveforms`
 - [ ] `scipy.signal.wavelets`
 - [ ] `scipy.signal.windows.windows`
 - [ ] `scipy.sparse.base`
 - [ ] `scipy.sparse.bsr`
 - [ ] `scipy.sparse.compressed`
 - [ ] `scipy.sparse.construct`
 - [ ] `scipy.sparse.coo`
 - [ ] `scipy.sparse.csc`
 - [ ] `scipy.sparse.csr`
 - [ ] `scipy.sparse.data`
 - [ ] `scipy.sparse.dia`
 - [ ] `scipy.sparse.dok`
 - [ ] `scipy.sparse.extract`
 - [ ] `scipy.sparse.lil`
 - [ ] `scipy.sparse.linalg.dsolve`
 - [ ] `scipy.sparse.linalg.eigen`
 - [ ] `scipy.sparse.linalg.interface`
 - [ ] `scipy.sparse.linalg.isolve`
 - [ ] `scipy.sparse.linalg.matfuncs`
 - [ ] `scipy.sparse.sparsetools`
 - [ ] `scipy.sparse.spfuncs`
 - [ ] `scipy.sparse.sputils`
 - [ ] `scipy.spatial.ckdtree`
 - [ ] `scipy.spatial.kdtree`
 - [ ] `scipy.spatial.qhull`
 - [ ] `scipy.spatial.transform.rotation`
 - [ ] `scipy.special.add_newdocs`
 - [ ] `scipy.special.basic`
 - [ ] `scipy.special.cython_special`
 - [ ] `scipy.special.orthogonal`
 - [ ] `scipy.special.sf_error`
 - [ ] `scipy.special.specfun`
 - [ ] `scipy.special.spfun_stats`
 - [ ] `scipy.stats.biasedurn`
 - [ ] `scipy.stats.kde`
 - [ ] `scipy.stats.morestats`
 - [ ] `scipy.stats.mstats_basic`
 - [ ] `scipy.stats.mstats_extras`
 - [ ] `scipy.stats.mvn`
 - [ ] `scipy.stats.statlib`
 - [ ] `scipy.stats.stats`

**Comment by h-vetinari** [comment]
CC @rgommers @Smit-create

**Comment by h-vetinari** [comment]
Related: #18279

**Comment by rgommers** [comment]
I'm not sure why this issue is needed. Using anything from these namespaces already raises a warning. E.g., from `sparse/linalg/dsolve.py`:
```python
def __getattr__(name):
    if name not in __all__ and name not in dsolve_modules:
        raise AttributeError(
            "scipy.sparse.linalg.dsolve is deprecated and has no attribute "
            f"{name}. Try looking in scipy.sparse.linalg instead.")

    if name in dsolve_modules:
        msg = (f'The module `scipy.sparse.linalg.dsolve.{name}` is '
               'deprecated. All public names must be imported directly from '
               'the `scipy.sparse.linalg` namespace.')
    else:
        msg = (f"Please use `{name}` from the `scipy.sparse.linalg` namespace,"
               " the `scipy.sparse.linalg.eigen` namespace is deprecated.")

    warnings.warn(msg, category=DeprecationWarning, stacklevel=2)

    return getattr(_dsolve, name)
```

All those `.py files can simply be deleted at some point. I don't think there is anything left to decide other than when the time is to do that.

**Comment by h-vetinari** [comment]
> All those `.py files can simply be deleted at some point. I don't think there is anything left to decide other than when the time is to do that.

Ah ok, that's not what I read from that comment I quoted in the OP ("some are fine, some are not"). If they're _all_ deprecated, and _all_ scheduled for removal, then I agree that nothing needs to be done, except perhaps update that comment.

**Comment by tupui** [comment]
The problem I still have with the machinery are summarized in #18279.

**Comment by rgommers** [comment]
> The problem I still have with the machinery are summarized in #18279.

Thanks, I hadn't seen that yet, will comment. 

I think we can close this as a duplicate then?

**Comment by tupui** [comment]
I think so? @h-vetinari does that sound good to you?

**Comment by h-vetinari** [comment]
Fine by me. I still think the comment above `PRIVATE_BUT_PRESENT_MODULES` is misleading and should be improved, be we can deal with that in the other issue.

**Comment by rgommers** [comment]
Okay, I clarified the comment in gh-18500.
