### ISSUE TITLE
BUG: Strange behavior of scipy.stats.hypergeom.sf function with increasing population

### ISSUE THREAD

**Issue by svalkiers** [scipy/scipy#18506]
### Describe your issue.

Consider the following example (using the same terminology as described in the scipy documentation):

M = i
n = 10
N = 10**5
x = n - 1

Let i be a variable number. In this example we are computing p-values for a fixed number of observations (n = 10) in a sample with size N and increasing total population size (M = i) using the survival function of the hypergeometric. The number of observations in the background remains fixed (thus the observation rate gets rarer with increasing M). Now one would assume p-values decrease as the rate of drawing n observations from the total population becomes increasingly rarer. Instead, p-values seem to plateau at some point, increase or even output _nan_ (see code example below). This issue seems to occur exclusively in newer scipy versions, but not in older ones (<1.5).

### Reproducing Code Example

```python
from scipy.stats import hypergeom
n = 10
N = 10**5
for i in range(5,20):
    population_size = 10**i
    p = hypergeom.sf(n-1, i, N, n)
    print(i, p)
```

### Error message

```shell
100000 1.0
1000000 9.995950679087263e-11
10000000 9.995545837022797e-21
100000000 9.995505446092684e-31
1000000000 9.995500164880522e-41
10000000000 3.216711239373477e-42
100000000000 1.4169478140706858e-41
1000000000000 nan
10000000000000 6.4091488811647e-42
100000000000000 3.8342654344802435e-35
1000000000000000 nan
10000000000000000 1.8619946500900136e-43
100000000000000000 1.1032539286549626e-42
1000000000000000000 nan
10000000000000000000 nan
```

### SciPy/NumPy/Python version and system information

```shell
1.10.0 1.23.5 sys.version_info(major=3, minor=9, micro=16, releaselevel='final', serial=0)
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/home/sebastiaan/miniconda3/envs/knn_tcr/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/home/sebastiaan/miniconda3/envs/knn_tcr/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/home/sebastiaan/miniconda3/envs/knn_tcr/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/home/sebastiaan/miniconda3/envs/knn_tcr/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
```

**Comment by mdhaber** [comment]
@mborland Looks like we're now using Boost for the survival function. Can we improve the precision for large values of the argument, perhaps using an asymptotic expansion?

**Comment by WarrenWeckesser** [comment]
@svalkiers, could you update the code in the question so that it actually generated the output that you show?  The code defines but does not use `population_size`, and the printed values of `i` shown in the output do not match the values defined in `for i in range(5,20):`.

**Comment by WarrenWeckesser** [comment]
The problem is that the integer values in the boost distribution use the C `unsigned` integer type, which for most compilers is just 32 bits. Assuming the example code is updated to use `population_size` instead of `i` in the last two lines in the loop, the results are correct up to `population_size = 1000000000`.  For all the following values, `population_size` exceeds 2**32-1.  On my installation of SciPy 10.1, all the results are `nan` from then on.  But in the output shown above, it appears that some of the results are computed for the "wrapped" input, i.e. for `population_size % 2**32`.
