### ISSUE TITLE
ENH: SciPy Knowledgebase

### ISSUE THREAD

**Issue by sr5434** [scipy/scipy#18524]
### Is your feature request related to a problem? Please describe.

NA

### Describe the solution you'd like.

I was thinking there could be a data repository in Scipy, similar to the Wolfram Knowledgebase. People could perform analysis on this data, and it can be used for demos.

**Comment by tupui** [comment]
Hi @sr5434, thank you for reporting.

I think this might be slightly out of scope for SciPy itself. That being said, we already have a tutorial section that we do want to expand and are actively working on. This is why I am going to close this as there is nothing actionable here or that we are not already tracking or aware of.

For information, we are also in the process of updating the SciPy Lecture Notes (which are going to be renamed to Scientific Python Lecture Notes.) These are similar to what you are suggesting here.

**Comment by sr5434** [comment]
Ok.
