### ISSUE TITLE
DOC: Dev branch docs render Dev TOC while viewing API Reference

### ISSUE THREAD

**Issue by ivirshup** [scipy/scipy#18535]
### Issue with current documentation:

When viewing https://scipy.github.io/devdocs/reference/index.html I see the table of contents for the developer guide, not the reference table of contents.

This is not an issue with the stable builds.

The issue persists after clearing the browser cache, so I assume that's unrelated.

### Idea or request for content:

It would be nice if the correct table of contents was displayed. It's curious that this isn't an issue for stable, so hopefully isn't related to how hosting is handled.

### Additional context (e.g. screenshots, GIFs)

https://scipy.github.io/devdocs/reference/index.html looks like:

<img width="1091" alt="image" src="https://github.com/scipy/scipy/assets/8238804/714b0379-3909-4218-89bb-ec9fac2a9b92">

https://docs.scipy.org/doc/scipy/reference/index.html looks like

<img width="1091" alt="image" src="https://github.com/scipy/scipy/assets/8238804/a18394f5-fece-41c2-8623-d9b5d8d50dcf">

**Comment by tupui** [comment]
Hey @ivirshup, thanks for reporting. Yes I noticed this. It happears from time to time and I also suppose it's some sort of caching happening here. Not sure though. We are in the process of updating the doc (🤞) hopefully that would "fix" something.
