### ISSUE TITLE
BUG: Version constraint on numpy conflicts with version on numpy main

### ISSUE THREAD

**Issue by ngoldbaum** [scipy/scipy#18534]
### Describe your issue.

The numpy 2.0 branch happened this week, and now the version constraint in the newest scipy release conflicts with the version from numpy main. Presumably some adjustments to the version constraints are needed on supported maintenance branches to properly conform with NEP 29. Although that said, there isn't any language in the NEP about what happens if numpy increments the major version number, so maybe not supporting numpy 2.0 on older releases is fine.

### Reproducing Code Example

```python
# done inside a checkout of numpy's main branch
$ pip install scipy
$ pip install .
```

### Error message

```shell
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scipy 1.10.1 requires numpy<1.27.0,>=1.19.5, but you have numpy 2.0.0.dev0+2.gcc0abd768 which is incompatible.
```

### SciPy/NumPy/Python version and system information

```shell
1.10.1 2.0.0.dev0+2.gcc0abd768 sys.version_info(major=3, minor=10, micro=9, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: cmake
    found: true
    include directory: unknown
    lib directory: unknown
    name: OpenBLAS
    openblas configuration: unknown
    pc file directory: unknown
    version: 0.3.18
  lapack:
    detection method: cmake
    found: true
    include directory: unknown
    lib directory: unknown
    name: OpenBLAS
    openblas configuration: unknown
    pc file directory: unknown
    version: 0.3.18
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.33
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: /tmp/pip-build-env-xob7rtip/overlay/lib/python3.10/site-packages/pythran
    version: 0.12.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp310-cp310/bin/python
  version: '3.10'
```

**Comment by tupui** [comment]
Thanks for the report @ngoldbaum 

You have to use SciPy's nightlies or the `main` branch for that. There are no pins there.

The pin for 1.10.1 not working with NumPy 2.0 is correct. Since we released 1.10.1, NumPy already broke a few things on our end. (Depends on what you use in SciPy of course.)

I would close this personally as I don't think there are any action points there. We are pretty conscious about our pins.

**Comment by tylerjereddy** [comment]
> if numpy increments the major version number, so maybe not supporting numpy 2.0 on older releases is fine.

That sounds right, I think. Hard to say how many shims we'd have to backport to support 2.0 final, but could be more mess/hassle than we're prepared to guarantee support for on older branches.

**Comment by rgommers** [comment]
+1 to this, the comments by Pamphile and Tyler seem correct to me. NumPy 2.0 contains an ABI break, so already-released versions of SciPy will have wheels that cannot work with NumPy 2.0 (and a from-source build highly likely won't either, due to API breaks).
