### ISSUE TITLE
ENH: Request for scipy wheel for Python 3.10 on armv7l

### ISSUE THREAD

**Issue by tukaisg** [scipy/scipy#18548]
### Is your feature request related to a problem? Please describe.

Subject: Request for scipy wheel for Python 3.10 on armv7l

Hi,

I'm using a Raspberry Pi with armv7l architecture and I've recently upgraded to Python 3.10. I noticed that there isn't a scipy wheel available for this configuration on piwheels or pypi . It would be very helpful if you could add a scipy wheel for Python 3.10 on armv7l. 

Thank you for considering my request.

### Describe the solution you'd like.

Subject: Request for scipy wheel for Python 3.10 on armv7l

Hi,

I'm using a Raspberry Pi with armv7l architecture and I've recently upgraded to Python 3.10. I noticed that there isn't a scipy wheel available for this configuration on piwheels or pypi . It would be very helpful if you could add a scipy wheel for Python 3.10 on armv7l. 

Thank you for considering my request.

**Comment by andyfaff** [comment]
This platform is not one for which we receive many requests. As a project we try to focus wheel development on major platforms, and keep buildability on others. This platform falls into the latter category. We would action issues and PRs for it, but not to the extent of building a wheel.

Furthermore, there's no CI available to build and test natively, which precludes wheel building.
