### ISSUE TITLE
Maybe redundant del 

### ISSUE THREAD

**Issue by qqwqqw689** [scipy/scipy#18558]
In scipy/signal/__init__ .py

https://github.com/scipy/scipy/blob/main/scipy/signal/__init__.py

I think the "del name" in 387th line is redundant. 

(But I'm not sure for it.)👀

**Comment by rkern** [comment]
It is not. `name` gets assigned by [the preceding `for name in deprecated_windows:` line](https://github.com/scipy/scipy/blob/main/scipy/signal/__init__.py#L384). [See this section in the Python language reference.](https://docs.python.org/dev/reference/compound_stmts.html#for)

**Comment by qqwqqw689** [comment]
Thank you very much.
