### ISSUE TITLE
DEP: deprecate positional arguments in `stats.kendalltau`

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#18578]
~Follow-up of #16388, informally [deprecated](https://github.com/scipy/scipy/commit/748e775c60a82b7579979d16eaeebee3c4063b00) since 0.19~ delayed in #18624, now should follow #18703

**Comment by mdhaber** [comment]
`initial_lexsort` is the third argument of the function. If users had code that passed subsequent arguments by position, they would need to pass them by keyword during the deprecation period to address the warning. (Or pass `None` for the third positional argument, which doesn't really address the intent of the warning.) Does this mean we can make the subsequent arguments keyword-only, even though it wasn't stated explicitly in the deprecation warning?

**Comment by h-vetinari** [comment]
> Does this mean we can make the subsequent arguments keyword-only, even though it wasn't stated explicitly in the deprecation warning?

It would be good to re-confirm this, but my understanding from https://github.com/scipy/scipy/issues/14714 was, that if we do touch the signature of a function, it's desirable to use that opportunity to make the relevant arguments keyword-only.

However, I think this would need an extra deprecation warning for all the other arguments as well. scikit-learn has a useful [helper](https://github.com/scikit-learn/scikit-learn/blob/1.2.2/sklearn/utils/validation.py#L42) function for that which we could vendor (scikit-learn did this wholesale for all their functions under [SLEP0009](https://scikit-learn-enhancement-proposals.readthedocs.io/en/latest/slep009/proposal.html), SciPy decided not to do such a big bang overhaul).

CC @tupui @ev-br @rgommers

**Comment by rgommers** [comment]
It would be nice if we could change to keyword-only indeed, but unfortunately @h-vetinari is right I think and it's not possible here. It would have been possible if the signature would have been changed to use `_NoValue` (like in numpy reductions) and then a user-passed `None` would also have generated the deprecation. But as it stands, `kendalltau(x, y, None, 'omit', 'exact')` passes without warning, so that can't be broken without a warning.

**Comment by j-bowhay** [comment]
Closing as no longer actionable for this release

**Comment by h-vetinari** [comment]
We still need to deprecate something after #18624 (see #18703), so I'm repurposing this issue to avoid creating a new one.
