### ISSUE TITLE
Difference between scipy.linalg and numpy.linalg

### ISSUE THREAD

**Issue by vineel96** [scipy/scipy#18572]
Hello,
I have the following doubts:
1. what is the difference between scipy.linalg and numpy.linalg? which performs better?
2. do scipy has parallel implementations on its own or only parallelization it gets is through openblas's openmp i.e openmp parallelism in openblas(if scipy is built on openblas)?

**Comment by ilayn** [comment]
Hi @vineel96 

Please refer to the documentation or other public QA and information sources for queries. We use here only for code related bugs and issues. Here is the relevant part https://docs.scipy.org/doc/scipy/tutorial/linalg.html

No we don't have any inhouse parallelization schemes and don't support OpenMP for different reasons. It is somewhere on the distant roadmap though.
