### ISSUE TITLE
DEP: deprecate positional arguments in `sparse.gmres`

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#18577]
~Follow-up of #16392, informally [deprecated](https://github.com/scipy/scipy/commit/87c9baafaae3435ebe95571fc22b9c9141231255) since 0.11~ delayed in #18624 / #18723, now should follow #18703

**Comment by j-bowhay** [comment]
This should probably wait for #18488

**Comment by j-bowhay** [comment]
Closing as no longer actionable for this release

**Comment by h-vetinari** [comment]
We still need to deprecate something after #18624 (see #18703), so I'm repurposing this issue to avoid creating a new one.
