### ISSUE TITLE
BUG: Floating point CSC with int64 indices doesn't work with linalg

### ISSUE THREAD

**Issue by stefanv** [scipy/scipy#18603]
### Describe your issue.

When sending a sparse matrix with dtype float and indices of type int64 into `sparse.linalg`, various routines emit the error shown below.

Perhaps related to https://github.com/scipy/scipy/pull/18509 ?

Thanks to @jarrodmillman and the NetworkX team for picking it up in their pre-release tests.

/cc @ivirshup @perimosocordiae @jjerphan 

### Reproducing Code Example

```python
import numpy as np
import scipy as sp

L1 = sp.sparse.csc_matrix([
    [3, -1, -1],
    [-1, 3, -1],
    [-1, -1, 3]
])

# --- problematic: float dtype + int64 indices
L1 = L1.astype(float)
L1.indices = L1.indices.astype(np.int64)
L1.indptr = L1.indptr.astype(np.int64)
# ---

lusolve = sp.sparse.linalg.factorized(L1.tocsc())
```

### Error message

```shell
Traceback (most recent call last):
  File "/tmp/nxtest.py", line 16, in <module>
    lusolve = sp.sparse.linalg.factorized(L1.tocsc())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/stefan/envs/py311/lib64/python3.11/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py", line 576, in factorized
    return splu(A).solve
           ^^^^^^^
  File "/home/stefan/envs/py311/lib64/python3.11/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py", line 414, in splu
    return _superlu.gstrf(N, A.nnz, A.data, A.indices, A.indptr,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### SciPy/NumPy/Python version and system information

```shell
scipy 1.12.0.dev0+1099.e38ddf1
```

**Comment by jjerphan** [comment]
I confirm that this is related to #18509.

**Comment by perimosocordiae** [comment]
Previously, we would aggressively downcast to int32 whenever the indices could fit in that bitwidth. This behavior was covering for the lack of 64-bit index support in this linear algebra code.

As a quick fix, we could add an explicit index dtype check to SPLU and related functions, which would restore the downcasting behavior for just those inputs.

We might also want to look at the possibility of supporting 64-bit index arrays natively.

**Comment by perimosocordiae** [comment]
Based on a quick read through the `linsolve` code, it looks like the umfpack implementation already supports 64-bit index arrays (see gh-8278).

The superlu code contains the following check:

```
#define _CHECK_INTEGER(x) (PyArray_ISINTEGER((PyArrayObject*)x) && PyArray_ITEMSIZE((PyArrayObject*)x) == sizeof(int))
```
This implies that we'll need to downcast indices to `np.intc` before dropping to native code in `spsolve`, `splu`, and `spilu`. Should be a relatively simple change, though.
