### ISSUE TITLE
DOC: Mistake in the PDF of multivariate t distribution

### ISSUE THREAD

**Issue by ksnxr** [scipy/scipy#18607]
### Issue with current documentation:

In [scipy's documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.multivariate_t.html) the pdf of multivariate-t is different from e.g. [Wikipedia](https://en.wikipedia.org/wiki/Multivariate_t-distribution). Specifically, it should be \Gamma((\nu + p)/2) on the top for the first term of the pdf, instead of \Gamma(\nu + p)/2. My numerical experiments confirm that scipy's implementation follows the formulation in Wikipedia, and I believe the current documentation is incorrect.

### Idea or request for content:

Change the pdf to match the form in Wikipedia

### Additional context (e.g. screenshots, GIFs)

![image](https://github.com/scipy/scipy/assets/70186663/3b09b4d0-e92f-4567-925a-4948cd5cf7c2)

**Comment by mdhaber** [comment]
Thanks. I'll fix that shortly.

**Comment by mdhaber** [comment]
This was already fixed in main by gh-18307.
