### ISSUE TITLE
ENH: Cumulative Simpson's integration.

### ISSUE THREAD

**Issue by rowlesmr** [scipy/scipy#18621]
### Is your feature request related to a problem? Please describe.

I had an issue where I needed a more accurate cumulative integration that given by [`cumulative_trapezoidal`](https://github.com/scipy/scipy/blob/v1.10.1/scipy/integrate/_quadrature.py#L395-L485), and so wrote a simple routine that works for single-axis arrays.

### Describe the solution you'd like.

If it is desired, I can contribute at least a partial PR implementing cumulative Simpson's; arrays with more than one axis are not supported in my current code.

**Comment by j-bowhay** [comment]
Thanks, @rowlesmr. We are actually already looking at adding this so I will go ahead and close this issue as it is tracked elsewhere. However, it could be extremely helpful in moving #18151 (which implements this) forward if you would consider leaving a review on the PR.

**Comment by rowlesmr** [comment]
It's great that it's in the pipeline. The fact that `initial` doesn't actualy do what it is supposed to and add to every value is a pass from me.

I'll have to dig through the reasons SciPy only prepends it. I'll see if I can help out.

**Comment by j-bowhay** [comment]
Yes the current `initial` behaviour is a definite sharp corner. We are aware of this and a fix is in progress. I am on the phone so will try to find the pr later.

**Comment by rowlesmr** [comment]
#18588 is updating the docs to match the current behaviour.

Ah! #18219 makes `initial` be `0` or  `None`. Nice. I can work with that.
