### ISSUE TITLE
ENH: normalized estimated differential entropy

### ISSUE THREAD

**Issue by ejc043** [scipy/scipy#18648]
Hello!
Differential (and discrete) entropy is inversely dependent on the # observations i.e. high # observations --> low entropy 
I'm wondering if there is a way to account for this dependence i.e. compute entropy irrespective of # observations? There are implementations when computing discrete Shannon entropy: 
<img width="680" alt="Screen Shot 2023-06-08 at 9 22 10 AM" src="https://github.com/scipy/scipy/assets/81693735/12c7f573-e94d-4e47-857d-5022193e5e7a">

Thank you!!

**Comment by mdhaber** [comment]
The `scipy.stats.differential_entropy`produces a point estimate of an unknown population entropy based on a sample from the population. I interpret

> Differential (and discrete) entropy is inversely dependent on observations i.e. high # observations --> low entropy

to be a statement about the bias of the estimator. I'm not sure if that's true in general.

<details>

```python3
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
rng = np.random.default_rng(1638083107694713882823079058616272161)

dist = stats.norm()
n_samples = 1000
for sample_size in [100, 1000, 10000]:
    rvs = dist.rvs(size=(n_samples, sample_size), random_state=rng)
    h = stats.differential_entropy(rvs, axis=-1)
    plt.hist(h, alpha=0.5, label=f"Estimate, size={sample_size}")

ylim = plt.gca().get_ylim()
plt.vlines(dist.entropy(), *ylim, label='True Value')
plt.gca().set_ylim()
plt.xlabel("Differential Entropy Estimate")
plt.ylabel("Frequency")
plt.legend()
plt.show()
```

</details>

For samples from a normal distribution and the default method, I don't see a bias toward large values when the sample is small.

![image](https://github.com/scipy/scipy/assets/6570539/a8d2c9f4-1bc6-452f-b8d6-c43de5434cc9)

**Comment by ejc043** [comment]
@mdhaber This is very helpful!! Yes thank you! I'll close
