### ISSUE TITLE
DOC: Problem with the randint description

### ISSUE THREAD

**Issue by pepCV** [scipy/scipy#18643]
### Issue with current documentation:

In the randint page https://scipy.github.io/devdocs/reference/generated/scipy.stats.randint.html

it is said that the index k can go from [low to high-1] (both included), so in that example from 7 to 30. The PMF values are calculated and shown correctly, but the generated k values are missing the value 30, i.e. only k values from 7 to 29 are generated and shown in the plot, when the value 30 should also be included.

### Idea or request for content:

One solution would be to change
`x = np.arange(randint.ppf(0.01, low, high),randint.ppf(0.99, low, high))`
for
`x = np.arange(low,high)`

**Comment by rkern** [comment]
Yes, that would be a good fix. The `ppf(0.1, ...)` stuff is copy-pasted from other distributions that have infinite support. But maybe `x = np.arange(low - 5, high + 5)` to show that there are 0s outside of the range.

**Comment by pepCV** [comment]
Yes, that sounds good. There are other instances where the usage of the ppf method to generate the k values can fail, I have seen this too with the binomial distribution.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.binom.html

**Comment by tupui** [comment]
@pepCV would you like to make a PR to fix it?

**Comment by pepCV** [comment]
Yes, I can do that! One question though, I see in the code

https://github.com/scipy/scipy/blob/main/scipy/stats/_discrete_distns.py#L1054

where is this example string stored, in which file can I see it and modify it? Thanks!

**Comment by dschmitz89** [comment]
> Yes, I can do that! One question though, I see in the code
> 
> https://github.com/scipy/scipy/blob/main/scipy/stats/_discrete_distns.py#L1054
> 
> where is this example string stored, in which file can I see it and modify it? Thanks!

I think it comes from [here](https://github.com/scipy/scipy/blob/e1f0d9717a20919cc55d947a46edda9942748b93/scipy/stats/_distn_infrastructure.py#L293)

**Comment by mdhaber** [comment]
@pepCV thought I'd check in - when should we look out for that PR?

**Comment by Kyle0** [comment]
I started looking at this, struggling to understand where the string substitutions are defined?

**Comment by rkern** [comment]
In the `randint_gen` docstring, there is a line [`%(example)s`](https://github.com/scipy/scipy/blob/e1f0d9717a20919cc55d947a46edda9942748b93/scipy/stats/_discrete_distns.py#L1054) which is where the generic `Examples` section is inserted. Remove that line and write your own `Examples` section there instead. [`hypergeom_gen`](https://github.com/scipy/scipy/blob/e1f0d9717a20919cc55d947a46edda9942748b93/scipy/stats/_discrete_distns.py#L479-L511) is another distribution that has its own non-generic `Examples` section, for reference.
