### ISSUE TITLE
DOC: Missing equal sign in equation of Lomb-Scargle periodogram

### ISSUE THREAD

**Issue by mocquin** [scipy/scipy#18651]
### Issue with current documentation:

It seems an equal sign '=' is missing in the equation of the Lomb-Scargle periodogram in the user guide documentation  :  https://docs.scipy.org/doc/scipy/tutorial/signal.html#lomb-scargle-periodograms-lombscargle

### Idea or request for content:

Add an equal sign in the latex equation of the doc

### Additional context (e.g. screenshots, GIFs)

![image](https://github.com/scipy/scipy/assets/36188368/ed79480f-4bbd-4004-9fd1-aae387beabe0)

**Comment by j-bowhay** [comment]
Thanks @mocquin, would you like to submit a pr?

**Comment by mocquin** [comment]
See #18653
