### ISSUE TITLE
BUG: ci/circleci: build_scipy broken

### ISSUE THREAD

**Issue by alugowski** [scipy/scipy#18654]
### Describe your issue.

ci/circleci: build_scipy CI appears to be broken for all PRs in the last few days. They all fail with this error:
![image](https://github.com/scipy/scipy/assets/2730364/d664239a-72c3-453c-ad90-b199586d40a8)

### Reproducing Code Example

```python
Any recent PR
```

### Error message

```shell
#!/bin/bash -eo pipefail
pip install --install-option="--no-cython-compile" cython
pip install numpy==1.23.5
pip install -r doc_requirements.txt
# `asv` pin because of slowdowns reported in gh-15568
pip install mpmath gmpy2 "asv==0.4.2" pythran ninja meson click rich-click doit pydevtool pooch
pip install pybind11
# extra benchmark deps
pip install pyfftw cffi pytest


Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --install-option

Exited with code exit status 2

CircleCI received exit code 2
```

### SciPy/NumPy/Python version and system information

```shell
1.12.0.dev0+0.c4bfa2e 1.24.3 sys.version_info(major=3, minor=10, micro=11, releaselevel='final', serial=0)
```

**Comment by tupui** [comment]
Indeed than you @alugowski, want to make a PR to fix it?

Relevant issue on PyPi https://github.com/pypa/pip/issues/11358

**Comment by alugowski** [comment]
> Indeed than you @alugowski, want to make a PR to fix it?
> 
> Relevant issue on PyPi [pypa/pip#11358](https://github.com/pypa/pip/issues/11358)

[Sure :)](https://github.com/scipy/scipy/pull/18657)
