### ISSUE TITLE
Changing the order of the constraints will cause the result to change?

### ISSUE THREAD

**Issue by liuhuanshuo** [scipy/scipy#18674]
I am solving a minimum problem using SCIPY

When using `SLSQP` for minima, changes in the order of the constraints can lead to changes in the results

The following is my code, I found that as long as the order of constraint1 to constraint5 in cons is disturbed, the result will change (the range will not be very large)
```python
from scipy.optimize import minimize
def objective(x):
    return x[0]**2 + x[1]**2 + x[2]**2 + x[3]**2 + x[4]**2
def constraint1(x):
    return x[0] + x[1] + x[2] - 1

def constraint2(x):
    return x[0] - x[1] + x[3] - 2

def constraint3(x):
    return x[2] + x[4] - 3

def constraint4(x):
    return x[0] + x[1] - x[2] - 4

def constraint5(x):
    return x[3] + x[4] - 5

x0 = [0, 0, 0, 0, 0]

cons = [{'type': 'eq', 'fun': constraint1},
        {'type': 'ineq', 'fun': constraint2},
        {'type': 'ineq', 'fun': constraint3},
        {'type': 'ineq', 'fun': constraint4},
        {'type': 'ineq', 'fun': constraint5}]

result = minimize(objective, x0, constraints=cons)
```

The following is my code, I found that as long as the order of `constraint1` to `constraint5` in `cons` is disturbed, the result will change (the range will not be very large)

Is it an algorithm problem or a code problem? If I still want to use the `SLSQP` algorithm, can I keep the result unchanged?

**Comment by liuhuanshuo** [comment]
> It sounds like you can keep the result unchanged by not changing the order of the constraints, right? You could also choose a guess that is closer to the solution you're interested in, or add constraints that restrict the solution to the one you prefer.

Thank you for your reply.

Yes, I can find a best fit order by trying multiple order of constraints so the result won't change.

But what makes me question is exactly what I asked, why is the order of the constraints changed (of course, the content of each constraint has not changed), will it lead to a change in the local minimum?

Is this a math problem, or is there something wrong with the code?

**Comment by liuhuanshuo** [comment]
@mdhaber 

> It may be too much to expect that changing the problem formulation wouldn't change the result.

As I asked, does merely changing the order of the constraints essentially modify the question?

I think just a change in order should not lead to a change in the solution space? The local minimum should not change.

**Comment by mdhaber** [comment]
> As I asked, does merely changing the order of the constraints essentially modify the question? I think just a change in order should not lead to a change in the solution space?

No, it doesn't change the mathematical question, and indeed, you always get valid solutions to the original question.

> The local minimum should not change.

That doesn't follow.
```python3
x = 1e20

x += 1
x += -1e20

x 
```

Mathematically, addition is commutative, but swap the middle lines and you'll get a different result. Numerical algorithms don't always work in ways that are intuitive from the outside.

**Comment by mdhaber** [comment]
@liuhuanshuo it's been a few days, so I'll go ahead and close this, but please reopen it it has not resolved your concern. Thanks!
