### ISSUE TITLE
TST: Weekly builds to test against latest OpenBLAS

### ISSUE THREAD

**Issue by steppi** [scipy/scipy#18685]
Currently there's a lag between the release of a new version of OpenBLAS and us testing against this new version. At the moment updating is a manual process involving editing some config files. It would be nice to automate this. There's currently an issue in openblas-libs, https://github.com/MacPython/openblas-libs/issues/100, for uploading nightly wheels to https://anaconda.org/scientific-python-nightly-wheels/; after this is completed we can add a cron for weekly pre-lease builds using the latest OpenBLAS.

**Comment by tupui** [comment]
+1 to do this. I opened an issue on the Scientific Python side (link in your linked issue) for transparency.

**Comment by steppi** [comment]
cc @honno, @mattip

**Comment by rgommers** [comment]
The hardcoded exact version we use right now is at https://github.com/scipy/scipy/blob/96c973a3d19c5b83d93a25190cc12f47a2aa30d4/tools/openblas_support.py#L16-L19

> after this is completed we can add a cron for weekly pre-lease builds using the latest OpenBLAS.

Not quite a cron job - rather, we have a `prerelease_xxx` job in GitHub Actions that uses pre-release or nightly versions of all dependencies. See https://github.com/scipy/scipy/blob/96c973a3d19c5b83d93a25190cc12f47a2aa30d4/.github/workflows/linux_meson.yml#L255

**Comment by steppi** [comment]
> The hardcoded exact version we use right now is at
> 
> https://github.com/scipy/scipy/blob/96c973a3d19c5b83d93a25190cc12f47a2aa30d4/tools/openblas_support.py#L16-L19
> 
> > after this is completed we can add a cron for weekly pre-lease builds using the latest OpenBLAS.
> 
> Not quite a cron job - rather, we have a `prerelease_xxx` job in GitHub Actions that uses pre-release or nightly versions of all dependencies. See
> 
> https://github.com/scipy/scipy/blob/96c973a3d19c5b83d93a25190cc12f47a2aa30d4/.github/workflows/linux_meson.yml#L255

Thanks for clarifying.

**Comment by alugowski** [comment]
Sounds like an ideal candidate for GitHub's dependabot.

Dependabot checks dependencies for a newer version, and when it finds one out of date it creates a PR to update. That PR then serves as a place to test the update, and only the update. This way if upstream breaks something it is isolated to the update PR, and PRs not related to dependency changes don't get random test fails.
