### ISSUE TITLE
DOC, REL: GPG signatures on PyPI

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#18691]
This seems low priority (?) to change since it is only a warning, but we do have a lot of consumers and I haven't thought too much about the security component so I'll just paste the automatic email PyPI sends me when following our current release (candidate) process:

> What?

> During your recent upload of scipy to PyPI, we noticed you uploaded a GPG signature. However, support for GPG signatures has been removed from PyPI.

> What should I do?

> While uploads will continue to work, any signatures uploaded to PyPI will be discarded. It is recommended to no longer upload signatures to PyPI.

I suspect we just remove the `-s` from the `twine` command in our release process to comply: https://scipy.github.io/devdocs/dev/core-dev/index.html#uploading-release-artifacts

So, if others agree, I suspect we just change that and we're done here. I don't know if PyPI support for GPG sigs would substantially improve our security posture, but I think that's kind out of our scope/control anyway if that's what they decided?

**Comment by tylerjereddy** [comment]
Pertinent article here: https://blog.pypi.org/posts/2023-05-23-removing-pgp/

I only skimmed it a bit. To be fair, I believe that SciPy release managers have typically done a decent job of making their GPG keys available for public inspection, since it was in our release docs to do so, but anyway.

**Comment by rgommers** [comment]
Yes, not much else that can be done here except from removing `-s`. It is what it is for now, hopefully SigStore integration will get completed and then we can use that for signing in a way that's nicer than GPG.
