### ISSUE TITLE
BUG: <Module> is unknown import symbol

### ISSUE THREAD

**Issue by einarwar** [scipy/scipy#18707]
### Describe your issue.

Using VSCode with the pylance extension (v2023.6.20) for static type checking, i have some problems with typing for scipy. The scipy package gets imported correctly, and all scipy-related code works, but pylance gives a "<module> is unknown import symbol" in my editor. This causes me to not get autocomplete suggestions or type checking. This might be a pylance related issue as well, but i could not find any resources online, so hopefully someone here can help me.

This issue is for all scipy modules

### Reproducing Code Example

```python
from scipy.signal import find_peaks

# If i try to import it differently in another file

from scipy import signal
```

### Error message

```shell
"find_peaks" is unknown import symbol Pylance(reportGeneralTypeIssues)

# Corresponding error for other code example

"signal" is unknown import symbol Pylance(reportGeneralTypeIssues)
```

### SciPy/NumPy/Python version and system information

```shell
1.10.1 1.24.3 sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: cmake
    found: true
    include directory: unknown
    lib directory: unknown
    name: OpenBLAS
    openblas configuration: unknown
    pc file directory: unknown
    version: 0.3.18
  lapack:
    detection method: cmake
    found: true
    include directory: unknown
    lib directory: unknown
    name: OpenBLAS
    openblas configuration: unknown
    pc file directory: unknown
    version: 0.3.18
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.33
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: /tmp/pip-build-env-9ehqkjz3/overlay/lib/python3.11/site-packages/pythran
    version: 0.12.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp311-cp311/bin/python
  version: '3.11'
```

**Comment by tupui** [comment]
Hi @einarwar thank you for reporting. I would say that it's a PyLance thing since PyCharm is not complaining. It's not the first report we have about PyLance struggling with SciPy. Not much we can do here (there is a bunch of necessary magic on our side, that is true but we cannot reasonably go around), so I will close for now.
