### ISSUE TITLE
ENH: Ask for tqdm in Delaunay.

### ISSUE THREAD

**Issue by PogusTheWhisper** [scipy/scipy#18701]
### Is your feature request related to a problem? Please describe.

How do I add tqdm to see the progress? Because i have 500k point cloud and it is taking too long and don't know when it will finish.

### Describe the solution you'd like.

location of Delaunay function?

**Comment by rgommers** [comment]
Adding progress bars to numerical routines isn't something we are willing to consider @PogusTheWhisper. You can run your computation with smaller numbers of points and extrapolate to the estimated completion time yourself.
