### ISSUE TITLE
Relationships between `scipy.optimize.milp` vs `scipy.optimize.linprog`

### ISSUE THREAD

**Issue by HanGuo97** [scipy/scipy#18700]
### Issue with current documentation:

Hello, I need clarification regarding the relationship between two functions: 'milp' (mixed-integer LP) and 'linprog'.

My understanding is that 'milp' is specifically designed to handle mixed-integer situations. However, 'linprog' has the 'integrality' flag and uses the same linear optimization software (HiGHS) by default -- does it do the same thing too?

Can I conclude that 'linprog' is a more comprehensive function than 'milp', and the latter is essentially 'linprog' with a specific set of interfaces and limitations to mixed-integer settings?

Thanks in advance for your help!

**Comment by mdhaber** [comment]
They have essentially the same functionality and they rely on the same HiGHS library under the hood. We were advised that users looking for MILP functionality would not look in `linprog`, so we created a new function named `milp` with a interface that was designed all at once rather than evolved over time. I think the only difference is that `milp` does not give sensitivity information (dual variables / shadow prices / marginal values) because that is not available for problems with integrality constraints. Let us know if this needs to be added to the documentation and if so, whether you'd be willing to submit a PR.

**Comment by HanGuo97** [comment]
Thank you for the clear explanation!

I have a question regarding the performance of these two options. Although they offer the same functionality, I have noticed that `linprog` tends to be significantly faster than `milp` in some of my use cases (by orders of magnitude). This falls outside of the documentation aspect, so I am willing to raise a separate issue on this matter.

**Comment by mdhaber** [comment]
Is the total runtime on the order of milliseconds or microseconds? There is a lot more input validation in `milp`, which adds constant overhead.

**Comment by HanGuo97** [comment]
My use case is a multiple-choice knapsack problem (MCKP). Here are a few more details about my case:
- My problem involves a decision variable of 2688 elements (i.e.,`c.shape=(2688,)`)
- The problem has 1 upper bound condition (`A_upperbound.shape=(1, 2688)`)
- And 112 equality conditions (`A_equality.shape=(112, 2688)`)
- All decision variables are binary (i.e., `integrality = np.full_like(c, True)` with `Bounds(0, 1)`)

`linprog` takes <0.5s to solve. `milp` seems to take forever (I ran it for a while, in the order of minutes, and then gave up). 

Here is an observation I had earlier. I couldn't figure out why that happened, nor make this happen again. Strangely, in some rare cases earlier, `milp` also runs as fast as `linprog`. And if so, these two return near identical function values.

**Comment by HanGuo97** [comment]
Thanks -- I'm preparing the code sample.

While preparing, I came across a case where the above situation was reversed. In one instance, the `linprog` function took more than 6 minutes to execute, whereas `milp` only took 15 seconds. This led me to question whether there are any default optimizer configurations that differ between these two APIs. For instance, `linprog` appears to automatically select between `highs-ds` and `highs-ipm`, but `milp` doesn't offer this option. Unfortunately, I'm having difficulty making a proper comparison because `linprog` doesn't allow users to explicitly choose between `highs-ds` and `highs-ipm`. It appears that `linprog` ensures only `highs` can be used with `integrality`, but forgot to include `highs-ds` and `highs-ipm`.

**Comment by HanGuo97** [comment]
Below is the code I used. After observing `linprog` sometimes being considerably faster or slower, I believe it's plausible to consider that the optimization configuration selection might be the root of the issue.

<details>

```python
def milp_solve(
    budget: float,
    costs: np.ndarray,
    weights: np.ndarray,
    backend: str,
) -> scipy_optimize.OptimizeResult:
    if backend not in ["milp", "linprog"]:
        raise ValueError(f"Unknown backend: {backend}")

    N = costs.shape[0]
    coefficients = costs.reshape(-1)
    A_upperbound = weights.reshape(1, -1)
    b_upperbound = np.array([budget])
    A_equality = np.zeros_like(
        weights,
        shape=(N,) + weights.shape)
    A_equality[
        np.arange(N),
        np.arange(N), :] = 1.
    A_equality = A_equality.reshape(N, -1)
    b_equality = np.ones(N)
    integrality = np.ones_like(coefficients)

    if backend == "milp":
        constraints = [
            scipy_constraints.LinearConstraint(
                A=A_upperbound,
                lb=0,
                ub=b_upperbound),  # type: ignore
            scipy_constraints.LinearConstraint(
                A=A_equality,
                lb=b_equality,   # type: ignore
                ub=b_equality),  # type: ignore
        ]
        bounds = scipy_constraints.Bounds(0, 1)
        return scipy_milp.milp(
            c=coefficients,
            constraints=constraints,
            integrality=integrality,
            bounds=bounds)
    else:
        return scipy_linprog.linprog(
            c=coefficients,
            A_ub=A_upperbound,
            b_ub=b_upperbound,
            A_eq=A_equality,
            b_eq=b_equality,
            bounds=(0, 1),
            integrality=integrality)
```
</details>

Unfortunately, I'm not sure how to show the issue above without dumping the entire data here (since this seems to be data-dependent). That being said, here are the runtime profiles on my end.

<details>

```python
N = 50
C1 = costs  [:N, ...].reshape(N, -1)
W1 = weights[:N, ...].reshape(N, -1)
budget1 = W1[:, 0].sum()
print(C1.shape, W1.shape, budget1)
# (50, 24) (50, 24) 3.6938357

C2 = costs  [N: 2 * N, ...].reshape(N, -1)
W2 = weights[N: 2 * N, ...].reshape(N, -1)
budget2 = W2[:, 0].sum()
print(C2.shape, W2.shape, budget2)
# (50, 24) (50, 24) 3.6938357


%time r0 = milp_solve(budget1, C1, W1, "linprog")
# CPU times: user 808 ms, sys: 158 ms, total: 966 ms
# Wall time: 717 ms
%time r1 = milp_solve(budget1, C1, W1, "milp")
# CPU times: user 598 ms, sys: 91.9 ms, total: 690 ms
# Wall time: 524 ms


%time r0 = milp_solve(budget2, C2, W2, "linprog")
# CPU times: user 7min 44s, sys: 3min 58s, total: 11min 42s
# Wall time: 6min 42s
%time r1 = milp_solve(budget2, C2, W2, "milp")
# CPU times: user 16.4 s, sys: 1.41 s, total: 17.8 s
# Wall time: 15 s
```

</details>

**Comment by mdhaber** [comment]
@HanGuo97 I'm afraid I can't help to debug without the complete problem definition or another reproducible example.

**Comment by HanGuo97** [comment]
Okay, here's the data file!

https://gist.github.com/HanGuo97/b8f9dbdf4476212ffcb82ea22396c329

**Comment by mdhaber** [comment]
Please modify your code above to run given the data. It still refers to undefined variables `cost` and `weights`, for instance. In the future, please also provide everything - including imports.

**Comment by HanGuo97** [comment]
Sorry, please try the following (after converting the list into numpy arrays).

```python
%time r0 = milp_solve(3.6938357, C1, W1, "linprog")
# CPU times: user 808 ms, sys: 158 ms, total: 966 ms
# Wall time: 717 ms
%time r1 = milp_solve(3.6938357, C1, W1, "milp")
# CPU times: user 598 ms, sys: 91.9 ms, total: 690 ms
# Wall time: 524 ms


%time r0 = milp_solve(3.6938357, C2, W2, "linprog")
# CPU times: user 7min 44s, sys: 3min 58s, total: 11min 42s
# Wall time: 6min 42s
%time r1 = milp_solve(3.6938357, C2, W2, "milp")
# CPU times: user 16.4 s, sys: 1.41 s, total: 17.8 s
# Wall time: 15 s
```

**Comment by mdhaber** [comment]
I tested the code on Google Colab, and I get
```
CPU times: user 6.17 ms, sys: 0 ns, total: 6.17 ms
Wall time: 21.8 ms
CPU times: user 6.65 ms, sys: 0 ns, total: 6.65 ms
Wall time: 13.3 ms
CPU times: user 5.94 ms, sys: 0 ns, total: 5.94 ms
Wall time: 13 ms
CPU times: user 5.91 ms, sys: 0 ns, total: 5.91 ms
Wall time: 12.9 ms
```
All the results report that the problem is infeasible.

**Comment by HanGuo97** [comment]
That's odd. Let me investigate it on my own. 

Thank you very much for all the helps!!!
