### ISSUE TITLE
DOC: scipy.spatial.ConvexHull volume attribute does not work as expected

### ISSUE THREAD

**Issue by thanapat-pat** [scipy/scipy#18725]
### Issue with current documentation:

Documentation: https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.ConvexHull.html#scipy.spatial.ConvexHull

I'm trying to estimate a volume of object from point cloud by using the convex hull method but currently its volume attribute does not seem to work as expected.

### Idea or request for content:

The algorithm behind the volume (float)  attribute is missing.

**Comment by rkern** [comment]
Can you show a self-contained example? What did you expect and what did you get?

We rely on QHull's [`qh_getarea`](http://www.qhull.org/src/libqhull_r/geom2_r.c#getarea) function.

**Comment by j-bowhay** [comment]
Closing as not actionable
