### ISSUE TITLE
BUG: excess memory usage on macOS from `blas_memory_alloc`

### ISSUE THREAD

**Issue by alugowski** [scipy/scipy#18735]
### Describe your issue.

Importing scipy on macos can cause OpenBLAS to allocate 32MB, and sometimes much more.

Appologies that this isn't a slam dunk, as the observations vary between runs and some appear to contradict. However there is a possibly intermittent phantom allocation worth knowing about. So I'm opening this here to share observations in case others have some ideas.

This may be a scipy issue, a numpy issue, or an interaction of both. 

## Motivation

I've been benchmarking memory as part of the [`fast_matrix_market` PR](https://github.com/scipy/scipy/pull/18631) and noticed these large allocations that my code saw but the pure-Python `scipy.io._mmio` ones did not. These would be larger than the allocations my code made, so it skewed the benchmarks and made me think I have problems that I really didn't.

See the allocation plots generated by [memray](https://github.com/bloomberg/memray):
![Screenshot 2023-06-22 at 11 23 10 AM](https://github.com/scipy/scipy/assets/2730364/ddbf316a-33ec-4cab-b957-d4ee4235c402)
Another run:
![Screenshot 2023-06-23 at 8 29 02 PM](https://github.com/scipy/scipy/assets/2730364/6b11bb3d-0b0b-48fd-8517-ffe515a62866)
memray correctly identified all of mine.

Two weird things I can't explain:
* my code does not touch any BLAS operations. I create arrays with `np.zeros()` (in Python), fill them in threaded C++, and wrap the results in a `coo_matrix`. That's it.
* The size of this BLAS allocation appears to be somewhat related to the size of the matrix my code is loading. This is evident in the memory benchmark in the first post of the PR linked above, where loading large matrices has a larger phantom allocation.
* The pure python `_mmio` code never saw a 100+MB allocation, only a 32MB one at most. Maybe the C++ allocators interact with the OpenBLAS allocator? Can starting `std::thread`s cause `blas_memory_alloc` to request more memory? Notice the blas allocations appear to be in multiples of 32MB.

And the same code, but with a method that does not wrap in `coo_matrix`, hence only uses numpy (no scipy import at all), notice there is no excess:
![Screenshot 2023-06-23 at 8 31 45 PM](https://github.com/scipy/scipy/assets/2730364/d2dfee55-3a58-4533-a1fd-95072bf176cd)

That suggests the issue only appears if scipy is imported, or at least if scipy performs the numpy import.

To contradict that, I built numpy with debug symbols to get better traces, and I see this 32MB:
![Screenshot 2023-06-23 at 8 50 27 PM](https://github.com/scipy/scipy/assets/2730364/f1554e59-ca30-4aed-bcf3-78429372ea3d)
There appears to be a special macos check in `numpy/__init__.py` that calls BLAS (on macos only). However those methods use fixed inputs so shouldn't create 192MB allocations?

These debug builds never showed the larger allocations, so I can't confirm or deny that this is it.  

### Reproducing Code Example

```python
from fast_matrix_market import mmread
mmread("mat_coo.mtx")

# Or:

from scipy.io import mmread
mmread("mat_coo.mtx")


# where "mat_coo.mtx" is a 100MB coordinate matrix written by mmwrite()
```

### Error message

```shell
Allocations of multiples of 32MB from:

blas_thread_server at <unknown>:0
blas_memory_alloc at <unknown>:0
alloc_mmap at <unknown>:0
```

### SciPy/NumPy/Python version and system information

```shell
multiple.
built with `python dev.py build` for debug symbols:
1.12.0.dev0+0.f12979c

and from PyPI:

1.10.1 1.25.0 sys.version_info(major=3, minor=11, micro=2, releaselevel='final', serial=0)
/Users/enos/projects/fast_matrix_market/python/venv/lib/python3.11/site-packages/scipy/__config__.py:140: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "13.1.6",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "0.29.33",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "13.1.6",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld64",
      "version": "12.1.0",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.12.1",
      "include directory": "/private/var/folders/_f/lyvxf0v13gs7984d7sf7j83c0000gn/T/pip-build-env-c1_tgrdc/overlay/lib/python3.11/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "OpenBLAS",
      "found": true,
      "version": "0.3.18",
      "detection method": "cmake",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "lapack": {
      "name": "OpenBLAS",
      "found": true,
      "version": "0.3.18",
      "detection method": "cmake",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    }
  },
  "Python Information": {
    "path": "/private/var/folders/_f/lyvxf0v13gs7984d7sf7j83c0000gn/T/cibw-run-s3_k_ke5/cp311-macosx_arm64/build/venv/bin/python",
    "version": "3.11"
  }
}
```

**Comment by ilayn** [comment]
Can you please try with a newest OpenBLAS and MKL backends too?

**Comment by alugowski** [comment]
The dev build was with OpenBLAS 0.3.21 and the issue was visible there. I'm on ARM so no MKL for me.

**Comment by ilayn** [comment]
Not sure but maybe COO matrix creation is touching some blas stuff at some point probably through `numpy.matrix` usage.

**Comment by alugowski** [comment]
Turns out the matrix stuff is extraneous, the issue can be reproduced with a simple import.

Reproducing script follows. This will open 10 flamegraphs as tabs in your default browser, assuming your system has an `open`:

```bash
pip install scipy memray

for i in 1 2 3 4 5 6 7 8 9 10; do
    rm -f output-$i.bin
    rm -f memray-flamegraph-output-$i.html

    # run benchmark
    python -m memray run --native -o output-$i.bin -c "from scipy.io import mmread"
    #python -m memray run --native -o output-$i.bin -c "import scipy"

    # generate flamegraph
    python -m memray flamegraph output-$i.bin

    # show flamegraph
    open memray-flamegraph-output-$i.html
done
```

Interestingly, `from scipy.io import mmread` seems to produce much more of these allocations than `import scipy`.

I just did a run and saw the following `blas_memory_alloc` allocations (often two separate ones):

none
224MB
192MB and 32MB
160MB and 32MB
224MB and 32MB
224MB and 32MB
224MB and 64MB
224MB
224MB and 32MB
64MB

Other times you mostly see 32MB and none with an occasional larger allocation. It seems very intermittent. Wouldn't be an issue if the larger allocations didn't drive the RSS up.

**Comment by alugowski** [comment]
The problem isn't triggered by what this issue implies it is, so to avoid drawing folks in with red herrings I opened a new issue without the baggage of this one: https://github.com/scipy/scipy/issues/18774
