### ISSUE TITLE
DOC: documenting the SciPy API with `__init__.py` files (discussion)

### ISSUE THREAD

**Issue by agriyakhetarpal** [scipy/scipy#18733]
### Issue with current documentation:

Hi there, I am opening this issue to collect thoughts and ideas on an open-ended question regarding the SciPy documentation. I am a GSoC student this year under the NumFOCUS umbrella organisation, and @tinosulzer and I have been planning to draw some inspiration from SciPy to improve the documentation infrastructure for the [PyBaMM](https://github.com/pybamm-team/PyBaMM) package: the documentation is currently hosted at [docs.pybamm.org](https://docs.pybamm.org/) with ReadTheDocs, and we aim to make it more maintainable with all the moving parts it has, possibly programmatically or with other methods we can incorporate into our workflows. We have some questions for the SciPy maintainers whose answers shall be, in our regard, worthwhile in our endeavour:

1. It is to note that the SciPy documentation makes extensive use of Sphinx `.. toctree::` directives inside `__init__.py` files of module folders, e.g., [`scipy/stats/__init__.py`](https://github.com/scipy/scipy/blob/v1.10.1/scipy/stats/__init__.py). However, adding `toctrees` inside an `__init__.py` file with a docstring is generally rare (ref: [this StackOverflow answer](https://stackoverflow.com/a/67116418)). These may be generated by the `autosummary` Sphinx extension which we don't use at the moment (I am not sure how it works), but `__init__.py` files are meant to serve as labels for module imports in Python packages—key functions can be imported directly into the package namespace which keeps the API stable for users, even if the API undergoes an internal restructuring process – of course not without pros and cons, and a multitude of other approaches to `__init__.py` files also exist. TLDR: It would be great to get insight on documenting APIs inside `__init__.py` files plus their `.rst` counterparts to list `.. autoclass::` or `.. autofunction::` directives, in comparison to adding documentation separately inside a `docs/source/api/` directory with traditional `.rst` files.

2. What concerns does the above approach serve pertaining to the maintainability of the SciPy documentation? For example, there are 70 issues labelled with the "documentation" tag and a bit more with the `DOC:` prefix (including this one now haha). Are there any unforeseen difficulties that have been noticed; and in hindsight, was doing this a good idea?

Please feel free to close this issue lest it does not fit triaging requirements and continue the conversation in this thread, or serve these questions a redirection to an appropriate platform for asking them (mailing lists, et cetera).

### Idea or request for content:

N/A

### Additional context (e.g. screenshots, GIFs)

For example, [scipy/stats/__init__.py](https://github.com/scipy/scipy/blob/v1.10.1/scipy/stats/__init__.py) contains a primer on the statistics-related functionality offered by SciPy and links all of them in one place, while the individual methods in the API are documented on their own pages. It would be assumed that such a file would reside in the `docs/` folder, but having it in `__init__.py` has its own advantages of making the code more reachable (everything is inside the same folder for hasty access).

**Comment by rgommers** [comment]
@agriyakhetarpal you wrote a good summary, thanks. The linked StackOverflow answer seems very reasonable. I'd say that the current structure in SciPy is a result of both history and the need for detailed control over how docs are laid out for a large and messy library. A few points:
- SciPy did not have a good split between public and private APIs until very recently, so simply using `.. automodule::` with `:members:` wasn't possible.
- In the past it was very common to read docs in IPython & co. It may still be important, if less so than in the past. What goes in `.rst` files isn't accessible, while the contents of `__init__.py` are. E.g., `from scipy import stats` and then `stats??` in IPython is something I still do.
- I would not use `.. autoclass::` or `.. autofunction::` directives directly, that's going to be much more verbose than `.. automodule::` or `.. autosummary::` when you have a large API surface.

If you're writing redoing something from scratch, I'd keep `__init__.py` completely empty except for named (not `*`) imports of public API objects from other files. And then using `.. automodule::` should be much easier.

**Comment by agriyakhetarpal** [comment]
We don't have plans to redo the documentation from scratch, so keeping `__init__.py` empty would not be a necessity as such—but we do have plans to mark certain public API members as private, which could possibly end up being a long-drawn-out process and getting up to closure on that might just make using autoclasses and autofunctions easier.
I shall close this issue; thank you so much not only for the detailed reply but also for these tidbits of yesteryear on reading documentation locally with `IPython`, I had not heard of it before but it sounds very cool. :)
