### ISSUE TITLE
[DOC] Incorrect docstring for `boxcox_normmax` argument `method="mle"`, should be "maximizes the log-likelihood"

### ISSUE THREAD

**Issue by fkiraly** [scipy/scipy#18748]
The docstring of `boxcox_normmax` seems incorrect: in

https://github.com/scipy/scipy/blob/694a35789a92e7aced8b8c9a9e5c4d960766eadd/scipy/stats/_morestats.py#L1115-L1280

I think it should say "maximizes the log-likelihood", instead of

```
        'mle'
            Minimizes the log-likelihood `boxcox_llf`.  This is the method used
            in `boxcox`.
```

(internally, it minimizes, but the negative log-likelihood)

**Comment by mdhaber** [comment]
Thanks. I'll fix that tonight.
