### ISSUE TITLE
ENH: Generating very large random sparse arrays.

### ISSUE THREAD

**Issue by nvenkov1** [scipy/scipy#18757]
### Is your feature request related to a problem? Please describe.

In order to generate a random sparse array of dimensions m-by-n with prescribed density, scipy.sparse.random allocates a dense vector with m*n components. It is completely absurd to try to allocate data for a dense array when instantiating a sparse array. How can you ever generate a very large random sparse array using scipy.sparse.random?

### Describe the solution you'd like.

As an alternative to the current implementation of scipy.sparse.random, I had to use the following definition:

def sprand(m, n, rho):
  nnz = int(m * n * rho)
  I = np.random.randint(m, size=nnz)
  J = np.random.randint(n, size=nnz)
  V = np.random.rand(nnz)
  return scipy.sparse.coo_matrix((V, (I, J)), shape=(m, n))

**Comment by nvenkov1** [comment]
Okay, I understand. Then why not adding "if random_state is None: random_state = np.random.default_rng()" prior to executing "random_state = check_random_state(random_state)"? It would correct the default behavior of the function and maintain its backward compatibility. Allocating a dense array for the purpose of creating a sparse one is very bad practice.

**Comment by perimosocordiae** [comment]
The good news here is that we're planning to introduce new sparse array creation functions soon, and deprecate the old ones. When we do, we can do the efficient thing by default.
