### ISSUE TITLE
MAINT: Faster code proposition for multivariate.py

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#18750]
### Is your feature request related to a problem? Please describe.

There's a lot of unnecessary divisions and multiplications here:

https://github.com/scipy/scipy/blob/v1.11.0/scipy/stats/_multivariate.py#L4082-L4195

```
        # Add back a dimension for proper broadcasting: we're dividing
        # each row of each R matrix by the diagonal of the R matrix.
        q *= (d/abs(d))[..., np.newaxis, :]  # to broadcast properly
```

Wouldn't something like this be faster (modulo the broadcasting)?

```
for row,diag in zip(q,d):
  if diag<0: row=-row
```

It matters because this is a RNG and might be used a large number of times in a simulation.  The comment isn't too accurate either - we're not "dividing each row of each R matrix by the diagonal of the R matrix", but change changing the sign of a row whenever a diagonal element is negative.

**Comment by ilayn** [comment]
@keithbriggs Please keep the structure of the issues as proposed, it's just unnecessary work to get the right information to the right text field for us. You could do the same after opening the issue and editing if necessary. 

Also you are asking a question which you can benchmark yourself first locally and we don't need to discuss but evaluate the results. I am not sure exactly what you want us to do here.

**Comment by keithbriggs** [comment]
I just want you to aware of the inefficiency.   My report did not fit the template structure.

**Comment by mdhaber** [comment]
> Wouldn't something like this be faster (modulo the broadcasting)?

Maybe, but please test it and let us know the methodology and conclusion. 

> It matters because this is a RNG and might be used a large number of times in a simulation.

In that case, please use `size` to generate many elements from the distribution in a single call. https://github.com/scipy/scipy/pull/16574 gave this a large speed boost.

> the present code fails for dim=1

It doesn't look like this is a failure but a conscious decision by the author to emit an error message for this case. If you need a random point on the unit circle, please see [`uniform_direction`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.uniform_direction.html). (One of the values can be converted to an imaginary component, if desired.)
