### ISSUE TITLE
Licensing concern

### ISSUE THREAD

**Issue by hyandell** [scipy/scipy#18765]
Hi scipy folk,

Digging around into scipy 1.11.0  on PyPI, I wanted to flag that the tar.gz contains a GPL-2.0 file, which as I can't find it previously reported may be unintended given scipy's BSD licensing.

The file comes through into scipy through the unuran git submodule; namely this file:

    https://github.com/scipy/unuran/blob/a63d39160e5ecc4402e7ed0e8417f4c3ff9634cb/unuran/src/specfunct/log1p.c

**Comment by andyfaff** [comment]
C11 should have log1p available in math.h

**Comment by tupui** [comment]
Hi @hyandell, thank you for reporting.

SciPy got an authorisation from the original copyright and license holders to relicense UNU.RAN to our BSD-3-license. See https://github.com/scipy/unuran/blob/main/license.txt

I am not sure if we should edit this file. I guess the intent here was to just have a plain copy of the source as they are given to us.

**Comment by rkern** [comment]
This one is actually a problem as it was not originally authored by the UNURAN authors but [copied from the GPLed GSL codebase](https://github.com/scipy/unuran/blob/main/unuran/src/specfunct/log1p.c#L7-L13). [We've encountered this before.](https://github.com/scipy/unuran/pull/5#issuecomment-1531662829)

**Comment by charris** [comment]
Hmm, ISTR seeing similar code before. I wouldn't be surprised if the GSL folks also copied it from somewhere.

**Comment by rkern** [comment]
> Do you want to do the change?

I don't have the bandwidth to do it in short order.

> I wouldn't be surprised if the GSL folks also copied it from somewhere.

Possibly, but we have lots of `log1p` implementations with definitely-clean provenance laying about.

**Comment by tupui** [comment]
Anyone wants to take this one up?

**Comment by tylerjereddy** [comment]
Can we clarify the actions that are needed?

1. Is it sufficient to release `1.11.1` reasonably soon that rectifies the situation? Or is leaving "any trace" of the accidental/potential licensing issue in our PyPI release problematic in a practical sense?
2. What does rectification mean here, exactly? We should replace the `unuran` C source file in question with a license-compatible equivalent, and that's it? Or we pull the `log1p` from one of our own internal implementations (`scipy.special.log1p` under the hood? or the NumPy one somehow?)

**Comment by rgommers** [comment]
Hmm, this is a problem. It would be great if someone had turned the initial discussion of this into an issue and marked it as a release blocker.

> 1. Is it sufficient to release `1.11.1` reasonably soon that rectifies the situation?

We should do that asap, and then yank `1.11.0` from PyPI (Cc @tylerjereddy). That way, no one will pull it in by accident (only if they explicitly install with `== 1.11.0`) and we have a very visible marker of there being a problem with that release.

> 2. What does rectification mean here, exactly? We should replace the `unuran` C source file in question with a license-compatible equivalent, and that's it? Or we pull the `log1p` from one of our own internal implementations (`scipy.special.log1p` under the hood? or the NumPy one somehow?)

That's the same, whatever is the easiest thing to do.

**Comment by tupui** [comment]
@tirthasheshpatel could you have a look and make the change?? Thanks in advance 🙇

**Comment by tupui** [comment]
@WarrenWeckesser Yes, we "just" need someone to do that and then Tyler can make a new release as per Ralf's comment.

**Comment by tylerjereddy** [comment]
Ok, I'm working on this now

**Comment by tupui** [comment]
Much appreciated Tyler, thank you 🙇
