### ISSUE TITLE
BLD: How to Limit the Meson/Ninja Parallelism

### ISSUE THREAD

**Issue by ax3l** [scipy/scipy#18766]
Hi,

We are installing SciPy as part of our scientific software stack for laser-plasma modeling on the world's largest supercomputers (HPC). On HPC systems, we usually install software on shared resources ("head nodes"). We also use some more exotic architectures, such as [ppc64le](https://en.wikipedia.org/wiki/POWER9), for which SciPy provides no pre-compiled binary wheels. Thus, on Systems like [Summit (OLCF)](https://www.olcf.ornl.gov/summit/), we compile from source.

```bash
# in a venv with all dependencies provided
python3 -m pip install --upgrade scipy
```

We noticed that SciPy in 1.9+, with the splendid new [Meson+Ninja install support](https://labs.quansight.org/blog/2021/07/moving-scipy-to-meson), always compiles on all available logical codes. This is problematic for our workflows, because we will run into system resource limiters that abort (pkill) our build scripts that call into `pip`.

We searched the documentation but found no option to limit the parallelism during build, e.g., to `-j 12`. Is there an option we can set, e.g., an environment variable? Numpy has `export NPY_NUM_BUILD_JOBS=12` but we could not find an equivalent for SciPy yet.

**Comment by ax3l** [comment]
attn @rgommers for insight (#14847)

**Comment by ilayn** [comment]
Hi @ax3l could you please try using our `dev.py` for builds via `python dev.py build -j<number of parallel jobs>`  ? dev.py is located at the root of the repo folder

**Comment by ax3l** [comment]
Thank you, @ilayn!
Yes, those work to explicitly control parallelism, but since SciPy publishes source packages to PyPI, would an enhancement to provide control for the pip source install parallelism to control `-j<N>` be thinkable?

**Comment by rgommers** [comment]
http://scipy.github.io/devdocs/building/compilers_and_options.html#controlling-build-parallelism addresses exactly this, using `pip`.

**Comment by rgommers** [comment]
I'll note that if your `pip` version is not up-to-date, it may require using `--config-settings=compile-args="-j6"` instead of `-Ccompile-args="-j6"`.

**Comment by ax3l** [comment]
Thanks @rgommers!

Adopting the guidance to
```
# in a venv with all dependencies provided
python3 -m pip install --upgrade -Ccompile-args="-j12" scipy
```
works!

**Comment by ilayn** [comment]
I don't have an authoritative answer but we wouldn't know what to set for the value. There are simply way too many edge cases hence we just don't want people to wait 15 or more minutes to build like pre-meson days. We do publish sdist for architectures that are either on their way out or too tricky/too costly/(no CI infra for) to maintain.

**Comment by ax3l** [comment]
Thank you both, really appreciate it! :blush: 

Sorry for not finding the page in the first place.

**Comment by andyfaff** [comment]
BTW, if you know any CI providers with easy ppc offerings, we're always interested to know (TravisCI doesn't really suit, because of cost). If you come across other pain points with ppc please let us know.

**Comment by rgommers** [comment]
No worries at all @ax3l, this kind of bug report is quite useful. I'll note that this is the relevant feature request to improve the default behavior: https://github.com/mesonbuild/meson-python/issues/416 (ideally it'd be a `ninja` change, but they're very slow in changing anything).

**Comment by ax3l** [comment]
Hi @andyfaff,

Thanks, happy to help! Yes, the changes in TravisCI were tricky for the whole FOSS Community. It turns out though, that the PPC64le runners on TravisCI.com are sponsored by IBM and actually not charged:
https://docs.travis-ci.com/user/multi-cpu-architectures/#partner-queue-solution
![Screenshot from 2023-06-27 12-05-57](https://github.com/scipy/scipy/assets/1353258/024646b8-8ad0-410f-9bd7-4ee74b6f12b6)


I thus still use TravisCI for releasing binary wheels for my projects :)

**Comment by rgommers** [comment]
> Yes, the changes in TravisCI were tricky for the whole FOSS Community. It turns out though, that the PPC64le runners on TravisCI.com are sponsored by IBM and actually not charged

They are used on and off by NumPy and conda-forge, but they're very unreliable. So there's still a desire to move away from them - and conda-forge tends to switch back and forth to QEMU for ppc64le builds based on whether or not Travis CI has issues or not. So I'd prefer to avoid them.
