### ISSUE TITLE
BUG: large `blas_memory_alloc` allocations on scipy import

### ISSUE THREAD

**Issue by alugowski** [scipy/scipy#18774]
### Describe your issue.

Simply importing some scipy modules like `import scipy.linalg` or `import scipy.sparse` (possibly others) sometimes results in some very large memory allocations with `blas_memory_alloc` in their allocator's stack trace.

Run the reproducing script in an empty virtual environment. I've observed this with scipy 1.10.1 and 1.11.0 PyPI wheels on macOS. It's likely not present on Linux, else it would show up in memory benchmarks. Also rarely present with a `dev.py` build in a conda environment on macOS.

Plain `import scipy` tends to show one smaller allocation or none at all. `import numpy` has one such allocation from [`_mac_os_check()`](https://github.com/numpy/numpy/blob/85385d6eb9da2b45d1e5fa9994e82608e562ef32/numpy/__init__.py#L370) which is always 32MB and always accounted for in the stack trace (and goes away if commented out).

The issue is semi-intermittent. Out of the 10 repeats in the reproducing example, expect ~2 to not have any issues, ~2 to have only one, and the rest to have two large allocations. Some add up to over 200MB, which significantly raises peak RSS and script memory requirements of smaller scripts.

Example memory profiler flame graph:

![Screenshot 2023-06-27 at 9 14 02 PM](https://github.com/scipy/scipy/assets/2730364/4a1e870c-f41d-42e4-9192-15c85640bcae)

The column headed by the green cell is the total of all memory allocations for the Python code. Cell widths are proportional to memory usage. The orange line graph at the top is RSS over time.

### Reproducing Code Example

```python
# in an empty venv
pip install scipy memray

for i in 1 2 3 4 5 6 7 8 9 10; do
    # clear output files from previous script run else memray will halt
    rm -f output-$i.bin
    rm -f memray-flamegraph-output-$i.html

    # run memory profiler
    python -m memray run --native -o output-$i.bin -c "import scipy.sparse"

    # generate flamegraph
    python -m memray flamegraph output-$i.bin

    # show flamegraph
    open memray-flamegraph-output-$i.html
done
```

### Error message

```shell
Allocations of multiples of 32MB from:

blas_thread_server at <unknown>:0
blas_memory_alloc at <unknown>:0
alloc_mmap at <unknown>:0

Example allocation sizes over 10 attempts:
none
224MB
192MB and 32MB
160MB and 32MB
224MB and 32MB
224MB and 32MB
224MB and 64MB
224MB
224MB and 32MB
64MB
```

### SciPy/NumPy/Python version and system information

```shell
1.11.0 1.25.0 sys.version_info(major=3, minor=10, micro=9, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 14.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 14.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.35
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 12.1.0
  pythran:
    include directory: ../../pip-build-env-c59p96qu/overlay/lib/python3.10/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cibw-run-ie8qdf2r/cp310-macosx_arm64/build/venv/bin/python
  version: '3.10'
```

**Comment by rgommers** [comment]
I don't know why the behavior isn't reproducible, but I think the memory usage is known behavior of OpenBLAS, which allocates a fixed amount of memory per thread. To confirm that: the effect should go away when you set `export OPENBLAS_NUM_THREADS=1`.

**Comment by alugowski** [comment]
@rgommers you're right, `export OPENBLAS_NUM_THREADS=1` cures it. Yes it's curious why it's not consistent.

I'm tempted to add this to memory benchmarks. The reason I opened this issue is because I spent a lot of time tracking down why the `io_mm` memory benchmark was showing a lot more memory use than expected, and inconsistently so. Turns out I wasn't the problem after all :) Hopefully this saves the sanity of some future soul.

Is this an accepted hazard of using scipy in general? I was a bit surprised to see it in code that didn't depend on BLAS, though of course the imports are so interconnected that pretty much everything seems to import BLAS. I only say this because I've used scipy in memory-constrained environments before (think PAAS web servers like AppEngine) where such allocations were deal breakers. Though now that I think of it we did have random memory usage swings with OOM errors on datasets that didn't change size.

**Comment by rgommers** [comment]
> Is this an accepted hazard of using scipy in general?

I think it's an accepted hazard of using OpenBLAS. It's possible to build SciPy with MKL, ATLAS or other libraries that don't have this issue - or at least not to the same extent. I believe there are plans to improve on this in OpenBLAS, but I can't find an exact description of that. For a relevant issue, see https://github.com/xianyi/OpenBLAS/issues/3321.

> I'm tempted to add this to memory benchmarks. 

Sure, that sounds quite reasonable to me.
