### ISSUE TITLE
BUG: scipy.stats.gamma.fit doesn't fit the data well, when using method="ML"

### ISSUE THREAD

**Issue by lavakin** [scipy/scipy#18775]
### Describe your issue.

When trying to fit the gamma parameters from 100000 data points, the outputed distribution does not fit the data well. It also computes the cdf incorrectly.
(For method="MM" it works fine)
![bad_fit](https://github.com/scipy/scipy/assets/76702901/4bbd62c4-3883-40ed-be06-824f16d2de2a)

### Reproducing Code Example

```python
shape,loc,scale = scipy.stats.gamma.fit(variances)
gamma = scipy.stats.gamma(shape, scale=scale,loc=loc)
p = 1 - gamma.cdf(0.002187402275833706)
```

### Error message

```shell
No error message, just incorrect result
```

### SciPy/NumPy/Python version and system information

```shell
1.10.0 1.23.5 sys.version_info(major=3, minor=10, micro=9, releaselevel='final', serial=0)
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/nkalabova/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/nkalabova/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/nkalabova/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/Users/nkalabova/anaconda3/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512CD,AVX512_KNL,AVX512_SKX,AVX512_CLX,AVX512_CNL,AVX512_ICL
```

**Comment by mdhaber** [comment]
If you know the location and only need to fit the other parameters, you can use `floc` to specify it. That should fix the problem because there is an analytical solution when you only need to fit the scale and the shape. Please see `help(stats.gamma.fit)`.

Otherwise, please use [`scipy.stats.fit`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fit.html), which uses a more robust global optimization algorithm that `gamma.fit`.
