### ISSUE TITLE
DOC: Broken link to installation instructions in README.rst

### ISSUE THREAD

**Issue by prisae** [scipy/scipy#18788]
### Issue with current documentation:

The current `README.rst` (https://github.com/scipy/scipy/blob/main/README.rst) has the line

> For the installation instructions, see [our install guide](https://docs.scipy.org/doc/scipy/getting_started.html#installation).

This link, https://docs.scipy.org/doc/scipy/getting_started.html#installation, leads to a 404.

I could not immediately see what would be the right/new link, otherwise I would have created a PR to correct it.

### Idea or request for content:

Update link or remove line.

**Comment by prisae** [comment]
Ah, now I stumbled upon https://scipy.org/install/, that might be the right link? If so I can open a PR for that.

**Comment by prisae** [comment]
That page, https://scipy.org/install/, has at the end

> A word of warning: building SciPy from source can be a nontrivial exercise. We recommend using binaries instead if those are available for your platform. For details on how to build from source, see [this guide in the SciPy docs](https://scipy.github.io/devdocs/dev/contributor/building.html).

That link _also_ leads to a 404.

**Comment by rgommers** [comment]
Ah, so much fun keeping links alive. Thanks for this issue @prisae. https://scipy.org/install/ is indeed the right link for installation, and http://scipy.github.io/devdocs/building/index.html for building from source. PRs for these would be very welcome.

**Comment by prisae** [comment]
Oh it is. Always feels like Whac-A-Mole... I opened two PR's in the corresponding repos. I am closing this issue therefore.
