### ISSUE TITLE
ENH: concatenating sparse arrays should return sparse arrays

### ISSUE THREAD

**Issue by ivirshup** [scipy/scipy#18839]
### Is your feature request related to a problem? Please describe.

Concatenating sparse arrays (via `hstack`, `vstack`, `bmat`) returns a sparse matrix.

### Describe the solution you'd like.

I would like them to maintain the input classes.

### Describe alternatives you've considered.

`hstack` and `vstack` could be replaced with something more `concat`, which is in the `array-api`, unlike `hstack`, `vstack`.

cc: @dschult

**Comment by tupui** [comment]
The alternative you describe sounds like a good idea in any case. Moving towards supporting the Array API is something we might want to do in general.

**Comment by ilayn** [comment]
The specification would be around what the outcome would be if I supply CSR, CSC and DIA arrays. Also note that, `np.hstack([a, b])` is order of magnitude more readable than `np.concat([a, b], axis=1)` so not sure that we should get rid of them that quick.

**Comment by tupui** [comment]
> Also note that, np.hstack([a, b]) is order of magnitude more readable than np.concat([a, b], axis=1) so not sure that we should get rid of them that quick.

I was not suggesting a removal, just moving towards supporting the Array API. That does not necessarily imply that we would remove methods not part of the standard.
