### ISSUE TITLE
BUG: stats.burr12: distribution returns invalid moments 

### ISSUE THREAD

**Issue by gbene** [scipy/scipy#18838]
### Describe your issue.

Hi all!

I am using the new `scipy.stats.CensoredData` and when trying to fit a `burr12` distribution to a dataset (attached). When I try to get the stats of the fitted distribution nonsensical are returned. In particular the variance results negative (similar to issue #9544). 

The numpy mean and variance of the entire dataset is 1.158 and 2.008.

The fitted burr12 distribution mean and variance results 7.0219 and **-49.2284**. 
 
Moreover these values are completely absurd when the location is fixed to 0 (using `floc=0`) resulting in 1586.2322 and -2516132.9718

When I compare graphically the pdf, cdf and sf of the fitted distribution to the data and empirical cdf, and sf (calculated using `scipy.stats.ecdf`) they seem to be very close so I do not know why the mean and variance are giving these results.

![burr12](https://github.com/scipy/scipy/assets/40857804/d2a9f98b-cb85-435f-9ebc-5e1a408111ab)

 If we do not use censoring the mean is closer with 1.2379 (no floc) and 1.30129(floc=0) but the variance is still negative -7.2545(no floc) and -3.6738 (floc=0).

![burr12_nocens](https://github.com/scipy/scipy/assets/40857804/01ebeb63-ee34-4155-85c0-4af3886695b6)

How is it possible that the variance is negative?

[data.csv](https://github.com/scipy/scipy/files/11980038/data.csv)

### Reproducing Code Example

```python
import pandas as pd
import scipy.stats as ss
import seaborn as sns
import matplotlib.pyplot as plt

sns.set_theme()

data = pd.read_csv('data.csv', index_col=0)
complete_data = data['length'].values

print(complete_data.mean())
print(complete_data.var())


uncensored_data = data.loc[data['censored'] == 0, 'length'].values
censored_data = data.loc[data['censored'] == 1, 'length'].values

data_set = ss.CensoredData(uncensored=uncensored_data, right=censored_data)

# ================ fitting with censoring and no floc ================

dist = ss.burr12

fit_params = dist.fit(data_set)

fitted_dist = ss.burr12(*fit_params)

print(f'censoring, no floc: {fitted_dist.stats()}')

fig = plt.figure()

ecdf = ss.ecdf(data_set).cdf
esf = ss.ecdf(data_set).sf

x_vals = ecdf.quantiles

plt.subplot(2, 2, 1)
sns.lineplot(x=complete_data, y=fitted_dist.pdf(complete_data), color='r', label='Distribution PDF')
sns.histplot(complete_data, stat='density', bins=50)

plt.subplot(2, 2, 2)
sns.lineplot(x=x_vals, y=fitted_dist.cdf(x_vals), color='r', label='Distribution CDF')
sns.lineplot(x=ecdf.quantiles, y=ecdf.probabilities, color='b', label='Empirical CDF')
plt.subplot(2, 2, 3)
sns.lineplot(x=x_vals, y=fitted_dist.sf(x_vals), color='r', label='Distribution SF')
sns.lineplot(x=esf.quantiles, y=esf.probabilities, color='b', label='Empirical SF')
plt.show()

# ================ fitting with censoring and floc = 0 ================


fit_params = dist.fit(data_set, floc=0)

fitted_dist = ss.burr12(*fit_params)

print(f'censoring, floc = 0: {fitted_dist.stats()}')


fig2 = plt.figure()

ecdf = ss.ecdf(data_set).cdf
esf = ss.ecdf(data_set).sf

x_vals = ecdf.quantiles

plt.subplot(2, 2, 1)
sns.lineplot(x=complete_data, y=fitted_dist.pdf(complete_data), color='r', label='Distribution PDF')
sns.histplot(complete_data, stat='density', bins=50)

plt.subplot(2, 2, 2)
sns.lineplot(x=x_vals, y=fitted_dist.cdf(x_vals), color='r', label='Distribution CDF')
sns.lineplot(x=ecdf.quantiles, y=ecdf.probabilities, color='b', label='Empirical CDF')
plt.subplot(2, 2, 3)
sns.lineplot(x=x_vals, y=fitted_dist.sf(x_vals), color='r', label='Distribution SF')
sns.lineplot(x=esf.quantiles, y=esf.probabilities, color='b', label='Empirical SF')
plt.show()

# ================ fitting with no censoring and no floc ================


dist = ss.burr12

fit_params = dist.fit(complete_data)

fitted_dist = ss.burr12(*fit_params)

print(f'no censoring, no floc: {fitted_dist.stats()}')

fig3 = plt.figure()

ecdf = ss.ecdf(complete_data).cdf
esf = ss.ecdf(complete_data).sf

x_vals = ecdf.quantiles

plt.subplot(2, 2, 1)
sns.lineplot(x=complete_data, y=fitted_dist.pdf(complete_data), color='r', label='Distribution PDF')
sns.histplot(complete_data, stat='density', bins=50)

plt.subplot(2, 2, 2)
sns.lineplot(x=x_vals, y=fitted_dist.cdf(x_vals), color='r', label='Distribution CDF')
sns.lineplot(x=ecdf.quantiles, y=ecdf.probabilities, color='b', label='Empirical CDF')
plt.subplot(2, 2, 3)
sns.lineplot(x=x_vals, y=fitted_dist.sf(x_vals), color='r', label='Distribution SF')
sns.lineplot(x=esf.quantiles, y=esf.probabilities, color='b', label='Empirical SF')
plt.show()

# ================ fitting with no censoring and floc = 0 ================

dist = ss.burr12

fit_params = dist.fit(complete_data, floc = 0)

fitted_dist = ss.burr12(*fit_params)

print(f'no censoring, floc = 0: {fitted_dist.stats()}')

fig = plt.figure()

ecdf = ss.ecdf(complete_data).cdf
esf = ss.ecdf(complete_data).sf

x_vals = ecdf.quantiles

plt.subplot(2, 2, 1)
sns.lineplot(x=complete_data, y=fitted_dist.pdf(complete_data), color='r', label='Distribution PDF')
sns.histplot(complete_data, stat='density', bins=50)

plt.subplot(2, 2, 2)
sns.lineplot(x=x_vals, y=fitted_dist.cdf(x_vals), color='r', label='Distribution CDF')
sns.lineplot(x=ecdf.quantiles, y=ecdf.probabilities, color='b', label='Empirical CDF')
plt.subplot(2, 2, 3)
sns.lineplot(x=x_vals, y=fitted_dist.sf(x_vals), color='r', label='Distribution SF')
sns.lineplot(x=esf.quantiles, y=esf.probabilities, color='b', label='Empirical SF')
plt.show()
```

### Error message

```shell
No errors
```

### SciPy/NumPy/Python version and system information

```shell
1.11.1 1.24.3 sys.version_info(major=3, minor=10, micro=11, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.35
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-hy2eo89f/overlay/lib/python3.10/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp310-cp310/bin/python
  version: '3.10'
```

**Comment by mdhaber** [comment]
So the integrator is just returning garbage because he integral doesn't converge. Ok. Will you submit a PR?

**Comment by WarrenWeckesser** [comment]
> Will you submit a PR?

Not in the immediate future, so if anyone else has time, go for it.

Note that we have a similar problem for the calculation of the mean; for the mean to exist, it is necessary that $cd > 1$.  For example, currently `burr12.mean(2.0, 0.25)` returns -1.198140234735592.  The support is $x > 0$, so a negative mean is clearly not correct.

**Comment by mdhaber** [comment]
I think it's for all moment $r$; only if $cd > r$ does finite moment $r$ exist, right?

**Comment by WarrenWeckesser** [comment]
> I think it's for all moments $r$; only if $cd > r$ does finite moment $r$ exist, right? 

Yes, that's the general case.

When the condition is violated, the integral that defines the raw moment diverges, so a case can be made for `inf` instead of `nan`. In practice, I don't think it matters that much.  Likewise for the central moments: if the mean diverges, than any central moment should be `nan`, but if, for example, $cd > 1$, one can make the case for the variance being `inf` instead of `nan`--but I'm not making that case.

**Comment by gbene** [comment]
Hi! Sorry for the late response. Thank you @mdhaber for tackling this problem!

> You mean that fit returns numbers that don't necessarily look invalid, but calling stats of the resulting distribution gives a negative variance, right?

Yes as you stated in https://github.com/scipy/scipy/issues/18838#issuecomment-1625651830, and from the script that I provided, you can see that by plotting the fitted distribution everything makes sense (PDF follows the hist, CDF and SF follow the empirical counterparts) but the stats do not really make sense.

> Have you tried plotting this? It's possible that the fit is still very good and that this (with the magnitude of the variance) really does maximize the likelihood.

By plotting do you mean the fit or the likelihood function? I have plotted the former an the fit seems correct, but still is it possible that the variance is so huge? Also the mean (1586.2322) is a bit absurd when comparing the available data. 

> BTW, you may find stats.CensoredData.right_censored to be useful since you have an array of data and a boolean array indicating which values are censored.

Nice, thanks!

**Comment by mdhaber** [comment]
Mathematica agrees with the moments for those values of the parameters.
https://www.wolframalpha.com/input?i=SinghMadallaDistribution%5B2.4578152987175885%2C+0.4069822658485208%2C+0.4555252408087812%5D

Again, if matching the moments is what's important, method of moments would be more appropriate than MLE. You could also consider whether the data is more consistent with a different distribution.

**Comment by gbene** [comment]
ah, alright I see.

> method of moments would be more appropriate than MLE.

Ok but "mm" is not available for CensoredData right?

**Comment by mdhaber** [comment]
No, and it probably wouldn't work well for this distribution even if the censoring were ignored because it can produce non-finite moments.
