### ISSUE TITLE
BUG: curve_fit memoization causes significant overhead in function call

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#18864]
### Describe your issue.

In #17688 a simple memoizer was added to avoid duplicate calls to the target function at the starting point of the optimizer (once from python to check that the target function returns sane values, and one from the fortran optimizer).  A problem is that the memoizer (_minpack_py._lightweight_memoizer) itself can cause significant overhead, because `np.all(last_params == params)` can be slow.

In the example below, I fit a decreasing exponential over 100 points many times.  This is a mild simplification of a relevant use case: it is common, e.g. in super-resolution microscopy, to have to fit a very large number of 2D gaussians (so the target function is just a bit more complicated and the relative overheads change, but not that much).

As of scipy 1.11.1, this takes 206μs per iteration.  Simply replacing _lightweight_memoizer by `return f` (i.e. fully dropping memoization) greatly speeds up that line to 136μs per iteration.

If one really wants to avoid the first few duplicated calls, the solution mentioned at the end of https://github.com/scipy/scipy/pull/17688#issuecomment-1368258735 (only memoize the very first call) can be made efficient, by entirely skipping memoization once we move away from the first point, i.e.
```python
def _lightweight_memoizer(f):
    first_call_args = None
    first_call_result = None
    skip_memo = False

    def _memoized_func(params):
        nonlocal first_call_args, first_call_result, do_memo
        if skip_memo:
            return f(params)
        elif first_call_args is None:
            first_call_args = np.copy(params)
            first_call_result = f(params)
            return first_call_result
        elif np.all(params == first_call_args):
            return first_call_result
        else:
            skip_memo = True
            return f(params)

    return _memoized_func
```
This brings back the speed to 136μs per iteration, as the `if skip_memo` check has insignificant overhead.
(Feel free to pick up this implementation.)

### Reproducing Code Example

```python
In [1]: import numpy as np; from scipy.optimize import curve_fit

In [2]: np.random.seed(0); x = np.arange(100); y = 2 * np.exp(-.1 * x) + .25 * np.random.rand(len(x))

In [3]: %timeit curve_fit(lambda x, a, b: a * np.exp(-b * x), x, y)
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version and system information

```shell
1.11.1 1.24.3 sys.version_info(major=3, minor=11, micro=3, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 14.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 14.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.35
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 12.1.0
  pythran:
    include directory: ../../pip-build-env-aaeg2ib1/overlay/lib/python3.11/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cibw-run-w1_4nbi0/cp311-macosx_arm64/build/venv/bin/python
  version: '3.11'
```

**Comment by mdhaber** [comment]
Ah, we didn't remember that 
```
import numpy as np
x = np.asarray([1])
%timeit np.all(x == x)
```
would take hundreds of times longer e.g. `1 == 1`.

Now that we know that the extra complexity is warranted, it is easy to modify the code slightly to avoid this.
