### ISSUE TITLE
CI/BENCH: Fail on error

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#18868]
The current benchmark job does not fail if the benchmark code itself fails (see e.g. #18860). There's already `SCIPY_ALLOW_BENCH_IMPORT_ERRORS` to respond to import failures or not, but we're not doing the same for just _running_ the code.

IMO this job should fail if there are errors (or even warnings?) as otherwise the benchmarking code will slowly bitrot until it's hardly useful anymore.

Not sure if asv supports this natively... Our current invocation is:
https://github.com/scipy/scipy/blob/bd8ef0c59cea2a065eca8e4d9a9e8f7b0a5f1792/.circleci/config.yml#L149-L155

CC @haozeke @rgommers @tupui @j-bowhay

**Comment by tupui** [comment]
That sounds like a good idea, thanks for having a look. I did not réalise it was not already doing that! Maybe locally I was doing something else.

**Comment by tupui** [comment]
In light of other discussions, I want to clarify my statement. I am +1 on failing in case of execution errors, but I would not want that to be used as a way to check things like algorithmic convergence. To me this is a fundamentally different task and the benchmark suite is only geared toward the speed/memory aspect.

Algorithmic convergence should be checked in the testing suite (like we have for optimization). Even there it can be questionable to have these running all the time. We don't need to re-prove all convergences nor proof all the time. What we need is to ensure that code paths are preserved and outputs are consistent with inputs. That's the software engineering part vs the "science".

**Comment by h-vetinari** [comment]
> Algorithmic convergence should be checked in the testing suite [...] More in #18568

This issue only has the faintest relation to #18568 from my POV. I'm talking about the code of the benchmarks itself trivially failing on execution, e.g. because it fails due to using deprecated (and later removed) features of python, numpy, scipy, etc.

**Comment by tupui** [comment]
Yes totally agree, just wanted to clarify as one could have misinterpreted my position reading the 2 discussions 😅
