### ISSUE TITLE
pre-release CI job broken with cython 3.0.0rc1, Meson can't detect `cython` or `cython3`

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#18865]
Our pre-release CI job just died with this error ([log](https://github.com/scipy/scipy/actions/runs/5530345479/jobs/10089633793?pr=18668)):
```
meson.build:1:0: ERROR: Unknown compiler(s): [['cython'], ['cython3']]
The following exception(s) were encountered:
Running `cython3 -V` gave "[Errno 2] No such file or directory: 'cython3'"
```

I can reproduce it locally; it's due to the release of Cython 3.0.0rc1 a few hours ago (3.0.0b3 works fine), however it feels like a Meson bug rather than a Cython one. Meson checks for `cython` and `cython3` executables (it's normally `cython`, but Debian has unhelpfully renamed it to `cython3`). The detailed logging shows nothing more than the above.

It looks like the problem here is that the output from `cython -V` is now going to stdout rather than stderr, and Meson only checks the latter: https://github.com/cython/cython/pull/5505 (that PR said "it won't hit many users"). Cc @scoder, @mattip, @eli-schwartz.

I think the change in Cython is reasonable, and for SciPy this only impacts one CI job. However, scikit-image does not have a `<3.0` upper bound on Cython in its `pyproject.toml`, so scikit-image 0.21.0 will break when Cython 3.0 is released (Cc @stefanv, @lagru). 

I think the most pragmatic thing to do here is:
1. Revert the change in Cython,
2. Make the Meson code more robust by checking both stdout and stderr.

**Comment by rgommers** [comment]
Alternatively, scikit-image could do a 0.21.1 release of course to add the `<3.0` bound, and then the change can stay in Cython. Fixing up Meson and the SciPy CI job isn't too difficult.

**Comment by mattip** [comment]
It seems hard to imagine scikit-image will be the only project that will be impacted. Perhaps cython should rethink cython/cython#5505 and issue cython/cython#5504

**Comment by ilayn** [comment]
Fiddling with stdout or stderr is always leading to problems and basically removing anything Windows from that feature. Anyone knows why the version information is sent to `stderr` ?

Also this is a good example of why we prefer upper bounds for later discussions.

**Comment by eli-schwartz** [comment]
It's trivial for meson to search stdout too, I can change this later today and then a fixed meson version will be out next week. People who want to use the latest cython will have to use the latest meson too, but probably not the biggest problem ever. :D

It's just one simple additional branch.

**Comment by scoder** [comment]
Sorry for this. As you suggested, the change in Cython is really for correctness and not something that's strictly required.

I've made a change in https://github.com/cython/cython/commit/36a370289cd41604b65054b49a67cc746f2b518d now that additionally writes the version to stderr if that's not a TTY. That should keep existing tools happy that pipe from stderr and avoid confusing terminal users by not printing the version twice (stdout+stderr).

Please start reading the version from stdout, though. That's the right thing to do.

**Comment by eli-schwartz** [comment]
Fixed in meson git master.

**Comment by scoder** [comment]
I released a second Cython RC that should mitigate the problem for existing code.

**Comment by rgommers** [comment]
Thanks for the lightning fast fixes both! I confirmed that it's fixed in both places.
