### ISSUE TITLE
ENH: Add Support for Multiply–accumulate Operation

### ISSUE THREAD

**Issue by hongyuchen1030** [scipy/scipy#18875]
### Is your feature request related to a problem? Please describe.

When we calculate the native $\ a\leftarrow a+(b\times c)$, we still using the normal multiple and add in the floating point precision, which might have limited mathematical precision. [Wikie Page for Multiply–accumulate Operation](https://en.wikipedia.org/wiki/Multiply%E2%80%93accumulate_operation#:~:text=A%20fused%20multiply%E2%80%93add%20(FMA%20or%20fmadd)%20is%20a,step%2C%20with%20a%20single%20rounding.)

Supporting the FMA/FMAC operation can greatly improve our the computation precision in floating point number operation

### Describe the solution you'd like.

Have some function like `scipy.fma(a,b,c)` that calculate $\ a\leftarrow a+(b\times c)$

**Comment by roryyorke** [comment]
scipy.special, maybe?  Not sure this belongs to scipy.signal.

**Comment by mdhaber** [comment]
@seberg Does this sort of thing happen under the hood in NumPy `matmul`, or does rounding occur after every multiplication and division?

**Comment by seberg** [comment]
I am not sure what blas implementers do, likely depends on the platform in practice, but I would expect FMA is normally mostly used; for things like einsum, I am also not sure what you end up with.  (There are also dot-product instructions, which I am sure BLAS would use and for which I am not sure what their rounding is.)

Creating a ufunc for it is probably easy enough, fma is a common operation, but it would be nice to invent a submodule/home for it.

**Comment by j-bowhay** [comment]
Cross-referencing https://github.com/nschloe/pyfma

**Comment by vollbier** [comment]
Another cross-reference: This [stackoverflow answer](https://stackoverflow.com/a/67358748/1879010) compares the speed of different implementations.

**Comment by mdhaber** [comment]
`special` maintainers, please feel free to revive, but I'm not sure if `special` is even the right place for this. 

Seems like `linalg` if anything, since it's in BLAS territory. If BLAS has it, it's probably exposed in `scipy.linalg.blas` already.

Indeed, it looks like BLAS `axpy` (`y = a*x + y`) is doing exactly what you have in mind. 

It seems to be more accurate and faster than separate multiplication and addition:

```python3
import numpy as np
from scipy.linalg.blas import daxpy
from mpmath import mp
mp.dps = 100

@np.vectorize
def axpy(x, y, a):
    x, y, a = mp.mpf(x), mp.mpf(y), mp.mpf(a)
    return float(a*x + y)

rng = np.random.default_rng(234823498234)
n = 1000000
a = rng.random()
x, y = rng.random(size=(2, n))

ref = axpy(x, y, a)
res1 = a*x + y
res2 = daxpy(x, y, a=a)
np.sum(res1 == ref), np.sum(res2 == ref)
# (846650, 1000000)

%timeit a*x + y
# 1.98 ms ± 151 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit daxpy(x, y, a=a)
# 1.14 ms ± 679 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

Perhaps @ilayn can confirm? 

In the meantime, I'll go ahead and close.
