### ISSUE TITLE
minimize does not satisfy nonlinear constraint even if keep_feasible=True

### ISSUE THREAD

**Issue by CarrascoCesar** [scipy/scipy#18882]
### Describe your issue.

I am creating a general app that can calculate the probability of failure of engineering systems based on a limit state function.  In its most simple form this requires the solution of a minimization problem with an equality constraint.  The app works on almost all tests but have found that one specifically (very academic) causes problems where the equality constraint is not satisfied. 

There is no error message but the result is not correct.  The result is close to x = [0,0] but it should be x = [0, 4].  The resulting equality constraint has a value equal to 1.0 and not 0.0 as required.  The correct result can be obtained if u0 is set to other values like [0,1] but not when set to [1,0].  My expectation was that the equality constraint would be always satisfied if the minimization was successful but it appears it is not, even when keep_feasible=True.  I can solve the issue by setting u0 to [0,1] but the goal of the app I am developing is to work for a general set of limit state functions (constraint functions) and so would like to set u0 = zeros for all cases.

I know this is a challenging problem because the gradient of both the objective and constraint functions is zero at u0 = [0,0].  But why does minimize also fail to satisfy the equality constraint when u0 = [1,0]?

I am using method="trust-constr" because my general app also requires bounds (linear constraints) on the variables and the objective and constraint functions can return gradient and hessian to speed up the solution in large problems.

### Reproducing Code Example

```python
import numpy as np
from scipy import optimize
from IPython.core.interactiveshell import InteractiveShell

def lsf(u):
    u1, u2 = u

    a, b, c, d = [0.0, 0.0, 3.0, 4.0]

    g = 1.0 + (((u1 - a) ** 2) / c**2 - (u2 - b) ** 2 / d**2)

    return g

def of(u):
    d = np.sum(u**2) # sum of squares
    return d

cons = optimize.NonlinearConstraint(lsf, 0, 0, keep_feasible=True)
u0 = [0.0, 0.0]

res = optimize.minimize(
            of,
            u0,
            method="trust-constr",
            constraints=cons,
        )

res
```

### Error message

```shell

```

### SciPy/NumPy/Python version and system information

```shell
1.11.1 1.25.1 sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0)
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.7",
      "commands": "arm64-apple-darwin20.0.0-clang"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "0.29.35",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.7",
      "commands": "arm64-apple-darwin20.0.0-clang++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld64",
      "version": "12.2.0",
      "commands": "/Users/runner/miniforge3/conda-bld/scipy-split_1687995684757/_build_env/bin/arm64-apple-darwin20.0.0-gfortran"
    },
    "pythran": {
      "version": "0.13.1",
      "include directory": "../../../_build_env/venv/lib/python3.11/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "arm64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "darwin"
    },
    "cross-compiled": true
  },
  "Build Dependencies": {
    "blas": {
      "name": "blas",
      "found": true,
      "version": "3.9.0",
      "detection method": "pkgconfig",
      "include directory": "/Users/Carrasco/miniconda3/envs/carrasco_env311/include",
      "lib directory": "/Users/Carrasco/miniconda3/envs/carrasco_env311/lib",
      "openblas configuration": "unknown",
      "pc file directory": "/Users/Carrasco/miniconda3/envs/carrasco_env311/lib/pkgconfig"
    },
    "lapack": {
      "name": "lapack",
      "found": true,
      "version": "3.9.0",
      "detection method": "pkgconfig",
      "include directory": "/Users/Carrasco/miniconda3/envs/carrasco_env311/include",
      "lib directory": "/Users/Carrasco/miniconda3/envs/carrasco_env311/lib",
      "openblas configuration": "unknown",
      "pc file directory": "/Users/Carrasco/miniconda3/envs/carrasco_env311/lib/pkgconfig"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.10.4",
      "detection method": "pkgconfig",
      "include directory": "/Users/Carrasco/miniconda3/envs/carrasco_env311/include"
    }
  },
  "Python Information": {
    "path": "/Users/Carrasco/miniconda3/envs/carrasco_env311/bin/python",
    "version": "3.11"
  }
}
```

**Comment by CarrascoCesar** [comment]
Should clarify that the problem has two solutions at [0,4] and [0,-4] since equality constraint is a hyperbola.

**Comment by ellieLitwack** [comment]
Hi Cesar!

The $\frac{\partial of(x,y)}{\partial y} = 0$ for your initial condition, so the solver is "stuck" between increasing and decreasing y. If you change the y of your initial condition just a little bit (for example, ```u0 = [0.0, 0.01]``` or ```u0 = [0.0, -0.01]```, depending on which solution you'd like) you will converge on the solution.

**Comment by ellieLitwack** [comment]
Hi Cesar!

This is a great question. There are two things to note here.

First, keep_feasible is ignored when an equality constraint is used. This is described in the [documentation for Nonlinear Constraint](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.NonlinearConstraint.html). I believe the reason for this is that it is not practical to assure that every iteration is feasible for an equality constraint.

Second, your initial condition is on a saddle point. Because of this, the minimizer thinks your initial condition is a solution to the minimization problem. This is the expected behavior, and the solution for this is to change the y value in your initial condition. 

However, trust-constr incorrectly says "success: True" even though the constraint is not met. I am going to work on fixing this.

**Comment by CarrascoCesar** [comment]
Hello Ellie,
Thanks for the response.
Yes, this is a difficult problem and it is probably why it appears on some journal papers dealing with the topic of the app I am developing.  It is a completely academic problem but made it into my test unit and now I am stuck with it :)
Completely missed the documentation on keep_feasible for equality constraints and it of course makes sense.

Changing the result to "success=False" and maybe a "status=4" indicating that a minimum was found but  the constraint was not met within tolerance would be great.

Will probably modify my app to have the minimize function inside a while loop that first tries zeros as the initial condition but then adds a random disturbance when "success==False" and try a few times.

Thanks again for your response and look forward to the implementation of the "success==False" result.  I am new to python (about three months of experience) and do not feel proficient enough to attempt a truly pythonic modification of the code on my own.

**Comment by ellieLitwack** [comment]
Happy to help! This change is not going to show up until the next release of scipy, which will probably not be for a little while. In the mean time, you can use
```python 
success = res.success and (res.constr_violation < 1e-8)
```
as you success criterion.
