### ISSUE TITLE
DOC: lobpcg examples improvement

### ISSUE THREAD

**Issue by lobpcg** [scipy/scipy#18881]
### Issue with current documentation:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.lobpcg.html Examples includes
from scipy.sparse.linalg import LinearOperator, aslinearoperator
which is no longer use in the current development version.

### Idea or request for content:

Either remove the unused import or better yet include examples that use it

**Comment by anudeepadi** [comment]
Hey @lobpcg, I noticed issue #18881 regarding the documentation for scipy.sparse.linalg.lobpcg and I'd like to contribute by providing some example that use LinearOperator, aslinearoperator. Let me know if you're open to it and if I can proceed with submitting a pull request to address this issue.

**Comment by lobpcg** [comment]
@anudeepadi - of course please feel free evidently. Ping me after you finish if you would like me to review your PR.

**Comment by anudeepadi** [comment]
Hey @lobpcg,

I worked on the lobpcg examples improvement and came up with these examples:

**Using `aslinearoperator`:**
```python
from scipy.sparse.linalg import lobpcg, aslinearoperator
import numpy as np

n = 100
vals = np.diag(np.arange(1, n+1, dtype=np.float64))
A = aslinearoperator(vals)
X = np.random.default_rng().normal(size=(n, 3))
eigenvalues, _ = lobpcg(A, X, largest=False, maxiter=80)
print(eigenvalues)  # Output: [4., 5., 6.]
```

**Using `LinearOperator` with a callable:**
```python
from scipy.sparse.linalg import lobpcg, LinearOperator
import numpy as np

n = 100
vals = np.arange(1, n+1, dtype=np.float64)
def matvec(X):
    return vals[:, np.newaxis] * X
A = LinearOperator((n, n), matvec=matvec, dtype='float64')
X = np.random.default_rng().normal(size=(n, 3))
eigenvalues, _ = lobpcg(A, X, largest=False, maxiter=80)
print(eigenvalues)  # Output: [4., 5., 6.]
```

Let me know if these are okay for the issue. If so, I'll raise a PR. Sorry for the late submission, and thanks for checking this out!

**Comment by lobpcg** [comment]
@anudeepadi - in the first example, use sparse diags. In the second one, add matmat with a comment that LOBPCG requires matmat for better performance.

But in both examples the expected output should be 1, 2, 3?

**Comment by anudeepadi** [comment]
Hey @lobpcg,

I've updated the examples as per your feedback:

### Example using `aslinearoperator`:

```python
from scipy.sparse.linalg import lobpcg, aslinearoperator
import numpy as np
from scipy.sparse import diags

n = 100
vals = np.arange(1, n+1, dtype=np.float64)
A = diags(vals)  # Using sparse diags
A_aslo = aslinearoperator(A) # Converting to LinearOperator
X = np.random.default_rng().normal(size=(n, 3))
eigenvalues, _ = lobpcg(A_aslo, X, largest=False, maxiter=80)
print(eigenvalues)  # Output: [1., 2., 3.]
```

### Example using `LinearOperator` with a callable:


```python
from scipy.sparse.linalg import lobpcg, LinearOperator
import numpy as np

n = 100
vals = np.arange(1, n+1, dtype=np.float64)

# Define matvec for matrix-vector multiplication
def matvec(X):
    return vals[:, np.newaxis] * X

# Define matmat for matrix-matrix multiplication (important for LOBPCG performance)
def matmat(X):
    return vals[:, np.newaxis] * X

# Create a LinearOperator with matvec and matmat
A = LinearOperator((n, n), matvec=matvec, matmat=matmat, dtype='float64')

X = np.random.default_rng().normal(size=(n, 3))
eigenvalues, _ = lobpcg(A, X, largest=False, maxiter=80)

print(eigenvalues)  # Expected output: [1., 2., 3.]
```

Could you please review these changes? If everything is fine, I'll proceed with the PR. Thanks!

**Comment by lobpcg** [comment]
No need to define an identical matvec, just use matvec=matmat in the call.

**Comment by anudeepadi** [comment]
Ok sure. Can you please point out where do I make the changes?

**Comment by lobpcg** [comment]
`A = LinearOperator((n, n), matvec=matmat, matmat=matmat, dtype='float64')`

**Comment by anudeepadi** [comment]
Ok I will make the change and do you want me to include these examples in the lobpcg function?

**Comment by lobpcg** [comment]
It is a part of the lobpcg docsting. Please feel free to make a PR a draft and mention me there. After you see that your lobpcg updated documentation looks good, open your PR for review for maintainers.
