### ISSUE TITLE
DOC: make default bounds in scipy.optimize.linprog more obvious

### ISSUE THREAD

**Issue by TiloRC** [scipy/scipy#18902]
### Issue with current documentation:

If you open up the [docs page](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.linprog.html), it's very hard to tell that by default the lower bound is 0 without reading everything very carefully. You have to scroll down to see it unless you're in full screen on my laptop. 

Furthermore, when the default lower bound is mentioned, it's mentioned in reference to  the `lb` and `up` variables which are not part of the function's signature or the LaTeX.

Edit: I think it's worth noting that not realizing that there was a lower bound by default causes me a lot of confusion. The lack of mention of this in the latex section or the function's signature prevented me from realizing that a lower bound existed causing me to be very confused and lose a lot of time. 

### Idea or request for content:

Either include that this is the default in the function's signature or mention this with in the LaTeX or both. You could add a line like this: 

 Note that by default $l=0$  and $u=\infty$.

### Additional context (e.g. screenshots, GIFs)

<img width="1437" alt="Screen Shot 2023-07-17 at 9 31 11 PM" src="https://github.com/scipy/scipy/assets/67246777/b9a43bae-e214-4bb8-ac34-70799372574f">

**Comment by mdhaber** [comment]
You are welcome to open a PR.

**Comment by gloriadesideri** [comment]
Is this still open?
