### ISSUE TITLE
BUG: dev.py has `distutils` usage

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#18922]
### Describe your issue.

`distutils` is removed in Python 3.12. In https://github.com/andyfaff/scipy/pull/53 I'm trying to add scipy CI support for cp312. The test run fails straightaway because `distutils` is removed in 3.12.

It seems that this was known about in https://github.com/scipy/scipy/pull/16058.

Pinging @AnirudhDagar @rgommers @schettino72.

I would say that this is reasonably urgent to look into, as 3.12 release candidates are going to be released soon.

### Reproducing Code Example

```python
python dev.py build --werror
```

### Error message

```shell
Run python dev.py build --werror
  python dev.py build --werror
  shell: /usr/bin/bash -e {0}
  env:
    CCACHE_DIR: /home/runner/work/scipy/scipy/.ccache
    INSTALLDIR: build-install
    pythonLocation: /opt/hostedtoolcache/Python/3.12.0-beta.4/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.0-beta.4/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0-beta.4/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0-beta.4/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.0-beta.4/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.0-beta.4/x64/lib
Traceback (most recent call last):
  File "/home/runner/work/scipy/scipy/dev.py", line 119, in <module>
    from distutils import dist
ModuleNotFoundError: No module named 'distutils'
```

### SciPy/NumPy/Python version and system information

```shell
python3.12-dev
```

**Comment by tupui** [comment]
Thanks for having a look @andyfaff

FYI there is already a discussion here #18689
