### ISSUE TITLE
ENH: Remove ._is_array attribute from sparse arrays

### ISSUE THREAD

**Issue by ivirshup** [scipy/scipy#18921]
### Is your feature request related to a problem? Please describe.

Currently there are two ways to check if one of the sparse types is an array type.

* `a._is_array`
* `isinstance(a, sparse.sparray)`

It's probably good to consolidate on a single way to do things.

### Describe the solution you'd like.

`isinstance(a, sparse.sparray)`

It's public, it's pythonic. "There should be one -- and preferably only one -- obvious way to do it."

### Describe alternatives you've considered.

We could keep an attribute. But I can't think of any cases which `a._is_array` allows that aren't equivalent to an instance check.

### Additional context (e.g. screenshots, GIFs)

I believe `_is_array` was previously included as a way of indicating array-ness while the array classes still inherited from the matrix classes.

Since @dschult's refactoring of the class hierarchy in #18531, we can use the `sparray` and `spmatrix` public classes to differentiate between arrays and matrices via `isinstance` checks.

**Comment by perimosocordiae** [comment]
+1 for removing the attribute, now that we have a proper class hierarchy for doing isinstance checks.

**Comment by ivirshup** [comment]
Do we need to bother with a deprecation?
