### ISSUE TITLE
ENH: add new representations for Sakurai and Mikota matrices and use them for benchmarking

### ISSUE THREAD

**Issue by lobpcg** [scipy/scipy#18939]
### Is your feature request related to a problem? Please describe.

Sakurai and Mikota matrices are being used in scipy for benchmarking and testing: 
https://github.com/scipy/scipy/blob/c8069d94d5b2eb33193977b3744ed36105cc4cf7/benchmarks/benchmarks/sparse_linalg_lobpcg.py#L32
https://github.com/scipy/scipy/blob/c8069d94d5b2eb33193977b3744ed36105cc4cf7/scipy/sparse/linalg/_eigen/lobpcg/tests/test_lobpcg.py#L54
https://github.com/scipy/scipy/blob/c8069d94d5b2eb33193977b3744ed36105cc4cf7/benchmarks/benchmarks/sparse_linalg_lobpcg.py#L14
and for lecture notes, e.g., https://github.com/glemaitre/scipy-lecture-notes/blob/60baf1b669842637b9494674cd84c2a00522e4b1/advanced/scipy_sparse/examples/lobpcg_sakurai.py#L2 

1. Every time their definition is being repeated rather than called from a single public source.  
2. Their current definitions only construct matrices in one format, thus limiting their use.

### Describe the solution you'd like.

1. Define Sakurai and Mikota matrices with public API, e.g., in  https://github.com/scipy/scipy/blob/c8069d94d5b2eb33193977b3744ed36105cc4cf7/scipy/linalg/_special_matrices.py
2. Add various matrix formats - sparse, banded, and as matrix-free callable objects that perform the dot-product of the matrix by an input matrix without constructing the matrix explicitly.
3. Use these new matrix formats for benchmarking and testing. 

### Additional context (e.g. screenshots, GIFs)

See also [gh-18940]

**Comment by h-vetinari** [comment]
Some [context](https://github.com/scipy/scipy/pull/18954#issuecomment-1676516735) from #18954 for why we don't want to do the "public API" part of this issue:

> @rkern: Laplacians [have real applications](https://en.wikipedia.org/wiki/Discrete_Laplace_operator) in addition to testing and benchmarking, so I'm happy enough to keep it in the public API. The matrices from Mikota and Sakurai do not, AFAICT.
> 
> I am -1 on putting them in the public API. It's great for each to have one common implementation that we use in both tests and benchmarks rather than repeating the implementation, so it's fine that it exists inside of `scipy` itself, but they are not the kind of thing that we want to support in the public API. That's just a project policy choice. I'm glad your MATLAB implementations are popular in their own right, but that's not the kind of functionality that `scipy` exists to provide. We focus on other things.

This was the summary after some discussion where my opinion was also a -1 on putting things in the public API, if there isn't a strong motivating use case (beyond just benchmarking the code we have).
