### ISSUE TITLE
ENH: Jones and Faddy Skew-T distribution

### ISSUE THREAD

**Issue by JWTownhill** [scipy/scipy#18947]
### Is your feature request related to a problem? Please describe.

Jones and Faddy introduced a skew extension of the t distribution, which includes the t distribution as a special case. Their main paper discussing it is available [here](https://academic.oup.com/jrsssb/article/65/1/159/7110653?login=false).

The Jones and Faddy skew-t distribution can provide a good fit for data which is heavy tailed and skewed such as asset returns in finance. This makes it suited for Monte Carlo simulations in order to calculate the market risk associated with financial assets. I've used it for this purpose both in personal projects and at work (using implementations built independent of SciPy, and also recently implementing it myself using SciPy machinery).

It's also a distribution which has been applied more widely: their paper on the distribution has been cited 254 times. Jones and Faddy provide in their paper two applications where the skew-t is fit to: (1) the strength of glass fibres and (2) blood flow data.

It would be useful to have an implementation as part of SciPy so that it's easier for others to make use of.

### Describe the solution you'd like.

An implementation in SciPy of the Jones and Faddy Skew-T distribution. It's quite a tractable distribution, with analytical expressions for the mode, pdf, cdf, inverse cdf, and moments (all derived and presented in Jones and Faddy's 2003 paper). The paper also gives an expression for a skew-t random variable in terms of a beta random variable, which is useful for simulating samples from a skew-t distribution.

It would be good for the implementation to make use of all the above, to make computations more efficient.

I would propose calling the implementation a `jf_skew_t` distribution, or Jones and Faddy Skew-T distribution. This distinguishes it from other skew-t extensions which exist, for example the two discussed in Jones and Faddy's [paper](https://academic.oup.com/jrsssb/article/65/1/159/7110653?login=false) in sections 5.1 and 5.2.

**Comment by rkern** [comment]
That satisfies my criteria for inclusion in SciPy, especially if you already have an implementation using the `scipy.stats` machinery that you can contribute.

**Comment by JWTownhill** [comment]
> That satisfies my criteria for inclusion in SciPy, especially if you already have an implementation using the `scipy.stats` machinery that you can contribute.

Great, I have raised a PR for my implementation. I've tried to follow the guide for contributing and the guide for adding new distributions, but any input is appreciated as it's my first issue / PR. Thanks!
