### ISSUE TITLE
How to change the default setup for using res.plot()

### ISSUE THREAD

**Issue by Jiangchao3** [scipy/scipy#18944]
### Is your feature request related to a problem? Please describe.

Hi all,

I am fitting my data with a poisson distribution, and I use the commond res.plot to visualize my result. 

How can I change the line color or hist color for the default setting up?

for example, I want set the color of fitted PMF as red want to increase the linewidth.

![image](https://github.com/scipy/scipy/assets/66854878/631b9c62-fe8d-4101-bdce-83808e46ca57)

Hope can get your suggestion. Thanks

**Comment by mdhaber** [comment]
This seems to be about the `plot` method of the object returned by `stats.fit`. 

SciPy provides no features for customizing the plot directly. However, it returns the Matplotlib axis object, and you should be able to modify the attributes using the features of Matplotlib.
