### ISSUE TITLE
BUG: Regression in SciPy mode return shape with 1.11.1

### ISSUE THREAD

**Issue by jpl-jengelke** [scipy/scipy#18957]
### Describe your issue.

Returns float and not array as expected. Shape of return data changed. 

Please see and REOPEN https://github.com/scipy/scipy/issues/16418

### Reproducing Code Example

```python
Please see https://github.com/rzellem/EXOTIC/issues/1206
```

### Error message

```shell
Added Comparison Star #3 [324,365] from AAVSO
Finding transformation 1 of 142 : /proj/survey-ws/source/EXOTIC_sampledata/HatP32Dec202017/HATP-32171220013343.FITS
Traceback (most recent call last):
  File "/System/Volumes/Data/proj/survey-ws/source/EXOTIC/exotic/exotic.py", line 2641, in <module>
    main()
  File "/System/Volumes/Data/proj/survey-ws/source/EXOTIC/exotic/exotic.py", line 2124, in main
    aper_data["target"][i][a][an], aper_data["target_bg"][i][a][an] = aperPhot(imageData, 0,
                                                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/System/Volumes/Data/proj/survey-ws/source/EXOTIC/exotic/exotic.py", line 1137, in aperPhot
    bgflux, sigmabg, Nbg = skybg_phot(data, starIndex, xc, yc, r + 2, dr)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/System/Volumes/Data/proj/survey-ws/source/EXOTIC/exotic/exotic.py", line 1204, in skybg_phot
    return mode(dat.flatten(), nan_policy='omit').mode[0], np.nanstd(dat.flatten()), np.sum(mask)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: invalid index to scalar variable.
```

### SciPy/NumPy/Python version and system information

```shell
Python 3.11, SciPy 3.11.1 (but works in SciPy 3.10.1)
```

**Comment by rkern** [comment]
This old behavior was [deprecated in 1.9.0](https://github.com/scipy/scipy/blob/main/doc/source/release/1.9.0-notes.rst#deprecated-features), went through 1.9 and 1.10 release cycles, and was finally removed on schedule in 1.11.0. We did this intentionally, with plenty of warning per our policies. Use `keepdims=True` to get the old behavior.

**Comment by jpl-jengelke** [comment]
> This old behavior was [deprecated in 1.9.0](https://github.com/scipy/scipy/blob/main/doc/source/release/1.9.0-notes.rst#deprecated-features), went through 1.9 and 1.10 release cycles, and was finally removed on schedule in 1.11.0. We did this intentionally, with plenty of warning per our policies. Use `keepdims=True` to get the old behavior.

I am going to refer you to the [Semantic Versioning 2.0.0 specification](https://semver.org/) which says, precisely, "MINOR version (to be used) when you add functionality in a backward compatible manner." I am quite certain that the argument `keepdims=True` could have been set to default to just that so as to maintain backwards compatibility. Please do not add breaking functionality in a non-backwards compatible manner or alternately increment version numbers correctly per standards.

**Comment by rkern** [comment]
We have not adopted SemVer (and will not; it has been discussed many times). [Here is our deprecation policy](https://docs.scipy.org/doc/scipy/dev/core-dev/index.html#deprecations), which was followed in this case.

**Comment by jpl-jengelke** [comment]
OK, missed the DeprecationWarning and [got bitten](http://blog.khinsen.net/posts/2017/11/22/stability-in-the-scipy-ecosystem-a-summary-of-the-discussion/).
