### ISSUE TITLE
BUG: `PyArray_MAX` no longer available in `numpy/arrayobject.h`  

### ISSUE THREAD

**Issue by tupui** [scipy/scipy#18966]
There was a change in NumPy which removes `PyArray_MAX` and `PyArray_MIN`. E.g. of issue in our CI https://github.com/scipy/scipy/actions/runs/5663008932/job/15343987040#step:9:2979

```c
../scipy/integrate/_odepackmodule.c:477:12: error: implicit declaration of function ‘PyArray_MAX’; did you mean ‘PyArray_Max’? [-Werror=implicit-function-declaration]
  477 |     *lrw = PyArray_MAX(lrn,lrs);
      |            ^~~~~~~~~~~
      |            PyArray_Max
```

I believe the PR on NumPy is https://github.com/numpy/numpy/pull/24258

**Comment by ev-br** [comment]
Can you comment on why this change and not importing PyArray_MAX from npy_math.h, where the linked numpy PR moves them to?

**Comment by tupui** [comment]
I have no clue what's best to do 😅 I just followed the bug, C and NumPy's internal are not my expertise. I am happy to try to do the change you are suggesting instead. And seems like CI does not like what I did hum.

So I would need to do `#include "numpy/npy_math.h"` in both files??

**Comment by tupui** [comment]
But if we use `npy_math.h` then it's not backward compatible no?

**Comment by ev-br** [comment]
These includes might need to be guarded by an #ifdef depending on the numpy version? Let's ask @lysnikolaou for a recommended way of working around the numpy change.

**Comment by ev-br** [comment]
Or maybe it's easiest to just copy-paste the macros in their full complexity and not depend on numpy for them:

```
#define PyArray_MAX(a,b) (((a)>(b))?(a):(b))
#define PyArray_MIN(a,b) (((a)<(b))?(a):(b))
```

**Comment by tupui** [comment]
Let's ask yes 👍 

For now locally I got it working with:

```c
out = (PyArrayObject*)PyArray_Max(a, b, NULL);
out = (PyArrayObject*)PyArray_Min(a, b, NULL);
```

**Comment by lysnikolaou** [comment]
I'm not an expert really, and with my limited understanding, I don't get why including "numpy/npy_math.h" is backwards-incompatible. If it is, then you can hide it behind an `#ifdef`, since the move will only be realeased in numpy 2.0.

Agreed that it might be best to copy-paste the macros though since they're not overly complex.

**Comment by tupui** [comment]
> I don't get why including "numpy/npy_math.h" is backwards-incompatible.

We need to support NumPy >=1.22.4. So I would suppose that new changes in `npy_math.h` would not be backported/available on older versions. But I don't know how all that works.

I am happy to move the macros as there are just 2 files where these are used in our code base.

**Comment by lysnikolaou** [comment]
> So I would suppose that new changes in npy_math.h would not be backported/available on older versions.

They won't be backported but my feeling is that if you keep both the old `#include` and the new `#include "numpy/npy_math.h"` in, it should be okay on all of the supported versions.

Still better to just move the macros.

**Comment by tupui** [comment]
Ah yes i see what you both meant now! See my C level 😅

I will update my PR to just hard code the macro there then, thanks again!
