### ISSUE TITLE
DOC: incorrect reference to parameter name

### ISSUE THREAD

**Issue by apple-phi** [scipy/scipy#18989]
### Issue with current documentation:

`scipy.optimize.minimise(method="BFGS")` has a mention in it's documentation to `method='3-point'`. I assume it is supposed to say `jac='3-point'`, given that `method="BFGS"` already? If that's not the case, the wording could still do with a clean-up.

```
If jac in [‘2-point’, ‘3-point’, ‘cs’] the relative step size to use for numerical approximation of the jacobian. The absolute step size is computed as h = rel_step * sign(x) * max(1, abs(x)), possibly adjusted to fit into the bounds. For method='3-point' the sign of h is ignored. If None (default) then step is selected automatically.
```

### Idea or request for content:

Either reword docs to make clear what `method` refers to in this case, or fix the wrong symbol being named in the docs (depending on whether this is a mistake or not).

### Additional context (e.g. screenshots, GIFs)

The doc page is https://docs.scipy.org/doc/scipy-1.11.1/reference/generated/scipy.optimize.minimize.html 
Generated from https://github.com/scipy/scipy/blob/604e7a28e145dd14b77666752b65879bb73b01d7/scipy/optimize/_optimize.py#L340

**Comment by andyfaff** [comment]
Thanks for pointing this out. A fix is present in #18991
