### ISSUE TITLE
BUG: reproducible builds problem in _stats_pythran.cpython-311-x86_64-linux-gnu.so

### ISSUE THREAD

**Issue by bmwiedemann** [scipy/scipy#18987]
### Describe your issue.

While working on reproducible builds for openSUSE, I found that our
`python-scipy` 1.10.1 package varies between builds for multiple reasons. This issue is about one reason:

There is a timestamp embedded in `_stats_pythran.cpython-311-x86_64-linux-gnu.so`

### Reproducing Code Example

```python
build it twice - we use scratch VMs, but it might be possible to reproduce by removing a few relevant files

https://code.opensuse.org/package/python-scipy/blob/master/f/python-scipy.spec#_182 has our build description.
```

### Error message

```shell
--- old /usr/lib/hpc/gnu13/python-scipy/1.10.1/lib64/python3.11/site-packages/scipy/stats/_stats_pythran.cpython-311-x86_64-linux-gnu.so (objdump)
+++ new /usr/lib/hpc/gnu13/python-scipy/1.10.1/lib64/python3.11/site-packages/scipy/stats/_stats_pythran.cpython-311-x86_64-linux-gnu.so (objdump)
@@ -6289,8 +6289,8 @@
  198c0 5f415252 41595f41 5049206e 6f742066  _ARRAY_API not f
  198d0 6f756e64 005f4152 5241595f 41504920  ound._ARRAY_API 
  198e0 6973204e 554c4c20 706f696e 74657200  is NULL pointer.
- 198f0 32303233 2d30372d 32352031 373a3537  2023-07-25 17:57
- 19900 3a31392e 35343936 39330030 2e31332e  :19.549693.0.13.
+ 198f0 32303339 2d30382d 32372030 373a3536  2039-08-27 07:56
+ 19900 3a33382e 39373931 30360030 2e31332e  :38.979106.0.13.
  19910 31002873 73732900 5f5f7079 74687261  1.(sss).__pythra
  19920 6e5f5f00 756e6162 6c652074 6f20616c  n__.unable to al
  19930 6c6f6361 74652000 20627974 65730050  locate . bytes.P
```

### SciPy/NumPy/Python version and system information

```shell
scipy-1.10.1
numpy-1.24.2
openSUSE-Tumbleweed-20230728
```

**Comment by andyfaff** [comment]
There's nothing in the _stats_pythran file that would generate a timestamp. I reckon it's something introduced by pythran in its build process.

**Comment by andyfaff** [comment]
@bmwiedemann can you share what tools/process you use to figure out if a particular binary has changed?

**Comment by andyfaff** [comment]
@bmwiedemann, can you check that none of the other `.so` (not made with Pythran) have this issue?

**Comment by bmwiedemann** [comment]
For diffing, you can use https://github.com/bmwiedemann/reproducibleopensuse/blob/master/filterdiff with a first param of `"hexdump -C"` and then the two `.so` files.

There are many differing .so files, and they all have a `__pythran__` string right after the timestamps.

**Comment by bmwiedemann** [comment]
It probably comes from https://github.com/serge-sans-paille/pythran/blob/e3babfd430/pythran/cxxgen.py#L683 via pythran/toolchain.py:187

**Comment by andyfaff** [comment]
Can you confirm that Pythran HEAD solves this issue? This should be fixed by https://github.com/serge-sans-paille/pythran/pull/2131

**Comment by andyfaff** [comment]
I think this issue can be closed now as pythran addressed this issue.
