### ISSUE TITLE
ENH: Publish musllinux wheels to PyPI

### ISSUE THREAD

**Issue by amw** [scipy/scipy#18981]
### Is your feature request related to a problem? Please describe.

When building production images based on Alpine SciPy needs to be compiled from scratch taking a really long time as previously discussed in https://github.com/scipy/scipy/issues/15628.

### Describe the solution you'd like.

`musllinux` SciPy binary packages are already compiled and published on [https://anaconda.org/scientific-python-nightly-wheels/scipy](https://anaconda.org/scientific-python-nightly-wheels/scipy). It would be great if they were also published on PyPI.

### Describe alternatives you've considered.

I've considered using the images from Anaconda in my images, but it's not as straightforward as regular PyPI.

**Comment by tupui** [comment]
Thank you @amw for raising this again.

As Andrew said in the other issue, we still need to decide on our support tier. For now we are confident enough to publish nightlies but doing more is still an open question.

**Comment by rgommers** [comment]
NumPy has published `musllinux` wheels since June 17 in 1.25.0: https://pypi.org/project/numpy/1.25.0/#files. It would be quite useful to see some download statistics from that. @amw would you be willing to look into that? E.g. using https://packaging.python.org/en/latest/guides/analyzing-pypi-package-downloads/#useful-queries?

**Comment by tupui** [comment]
Good idea 👍 Until then we can have quick numbers with PyPi stats:

<img width="1274" alt="Screenshot 2023-07-28 at 17 41 44" src="https://github.com/scipy/scipy/assets/23188539/d7af675f-8197-489d-814c-605656528188">

We should also probably check on conda-forge.

Also @amw I noted that you are pointing to the old URL for the nightlies. I will update your post. This is the new one:

https://anaconda.org/scientific-python-nightly-wheels/scipy

**Comment by h-vetinari** [comment]
> We should also probably check on conda-forge.

conda-forge has no musl builds of anything, if that's the question. Otherwise, some rough numbers can be found [here](https://anaconda.org/conda-forge/numpy/files), but it's not in an easy format and I don't know a better API.

**Comment by andyfaff** [comment]
I'm happy with the build system for musllinux_x86_64 being maintainable. I don't think we had many issues with having to modify the test suite for musllinux - numpy had more.

My view is that if numpy is making wheels available (tick), and the build process is easy (tick), then we should also release official wheels.

**Comment by rgommers** [comment]
Agreed with @andyfaff reasoning here. Let's see if @tylerjereddy is also happy. I tentatively milestoned this for 1.12.0, but it could also be done for 1.11.2 already perhaps.

Download numbers will still be quite useful to see.

**Comment by tylerjereddy** [comment]
Sounds good to me. There are usually a few surprises when backporting wheel build changes, although I don't know that I can avoid that anyway if we need to release `3.12` wheels in the `1.11.x` series, which I believe we may have to based on the timeline.

**Comment by tylerjereddy** [comment]
@andyfaff can you remind me what I need to backport? or what work still needs to be done on `main` to move us forward? I suppose I may need to backport some things that reduce pressure on cirrus as well? feel free to ping me on PRs that have stuff I should consider backporting, even if only part of the commit(s).

**Comment by andyfaff** [comment]
I think you need to backport #18937, #18985, #18999, in that order.

**Comment by andyfaff** [comment]
@tylerjereddy, is this closeable now? Do you have to modify release procedures to upload musl wheels to staging?

**Comment by tylerjereddy** [comment]
> is this closeable now? Do you have to modify release procedures to upload musl wheels to staging?

Amazingly, the release procedure worked almost perfectly without my intervention re: `musl`, so closing yeah.

**Comment by amw** [comment]
Thank you, everyone. I love how quickly my CI images build now.
