### ISSUE TITLE
DOC: scipy.stats.lognorm — SciPy v1.12.0.dev Manual 

### ISSUE THREAD

**Issue by lamrongol** [scipy/scipy#18984]
### Issue with current documentation:

The document says "lognorm takes s as a shape parameter for s".
However, It seems that you can set σ and μ by `lognorm(s=σ, scale=math.exp(μ))`.

I confirmed it seems to work properly:
```python
import math
from scipy.stats import lognorm
import matplotlib.pyplot as plt

sigma = 1
mu = 0

lgnrm: lognorm = lognorm(s=sigma, scale=math.exp(mu))  # DistHolder.generate_log_normal_dist(10, 10 ** 2 * 1.0000005)

x = [v / 10 for v in range(30)]
y = [lgnrm.pdf(v) for v in x]
plt.plot(x, y)
plt.show()
```
reffered https://en.wikipedia.org/wiki/Log-normal_distribution

### Idea or request for content:

"lognorm takes s as a shape parameter and scale as a scale parameter, like a form`math.exp(mu)`".

I think it's better that changing arg names and `math.exp()` is not needed, as following:
```python
lognorm(sigma=sigma, mu=mu)
```

**Comment by mdhaber** [comment]
The documentation already points out the connection between the lognormal and normal distribution.

> Suppose a normally distributed random variable `X` has mean `mu` and standard deviation `sigma`. Then `Y = exp(X)` is lognormally distributed with `s = sigma` and `scale = exp(mu)`.

We cannot change the variable name in a backward compatible way with the existing distribution infrastructure.

**Comment by lamrongol** [comment]
> The documentation already points out the connection between the lognormal and normal distribution.
> 
> > Suppose a normally distributed random variable `X` has mean `mu` and standard deviation `sigma`. Then `Y = exp(X)` is lognormally distributed with `s = sigma` and `scale = exp(mu)`.

OK, but  "lognorm takes s as a shape parameter for s" seems confusing to mean that `lognorm` has only `s` parameter. The way to set mu and sigma can't be understood at a glance on following page, either.
https://stackoverflow.com/questions/8870982/how-do-i-get-a-lognormal-distribution-in-python-with-mu-and-sigma/13837335
How about to add a description "If you know mu and sigma, you can initialize by `lognorm(s=sigma, scale=math.exp(mu))`".
 
> We cannot change the variable name in a backward compatible way with the existing distribution infrastructure.

Changing names is difficult but how about adding variables?

**Comment by mdhaber** [comment]
`s` is the only "shape" parameter. The location and scale parameters, `loc` and `scale`, are common to all SciPy distributions. The next paragraph of the documentation explains that part.

"If you know mu and sigma..." may not be understood by all readers. Presumably these refer to the mean and standard deviation of the underlying normal distribution, but that would need to be explicit. Writing documentation that is immediately understood by everyone is challenging. You are welcome to submit a PR with your suggestion, though.

> Changing names is difficult but how about adding variables?

That is also challenging with the current infrastructure. I  will be addressing this and other concerns as part of https://github.com/scipy/scipy/issues/15928, which I am working on almost full time this month.

**Comment by mdhaber** [comment]
I've documented this request specifically in gh-15928 so I'm sure to review it again as I'm working.

**Comment by mdhaber** [comment]
@lamrongol Does gh-18995 help address this issue?

**Comment by lamrongol** [comment]
@mdhaber I think users can't find the constructor with sigma and mu at a glance  by https://github.com/scipy/scipy/pull/18995/commits/fec08e1ccf6b68cc0234b30070f2bfe6e9f96842 .
Is it difficult to add an example to the top of page?
