### ISSUE TITLE
DOC: Maybe a typo on the parameter 'alternative' in the Mann-Whitney U test documentation

### ISSUE THREAD

**Issue by terilias** [scipy/scipy#19009]
### Issue with current documentation:

Hello,
In the [Mann-Whitney U test documentation](https://scipy.github.io/devdocs/reference/generated/scipy.stats.mannwhitneyu.html) and more precisely on the following point:
![εικόνα](https://github.com/scipy/scipy/assets/37142366/9c3dd296-38d1-4724-81e5-16faa392ce22)
I think that the symbols "less than <" and "greater than >" for the distributions they are reversed.

### Idea or request for content:

Maybe I am missing something but I would expected to see the "less than <" symbol for the alterative hypothesis "less" and the "greater than >" symbol for the hypothesis "greater".

**Comment by mdhaber** [comment]
Please refer to https://github.com/scipy/scipy/issues/14970. 

From the KS test documentation:
> Note that the alternative hypotheses describe the CDFs of the underlying distributions, not the observed values of the data. For example, suppose x1 ~ F and x2 ~ G. If F(x) > G(x) for all x, the values in x1 tend to be less than those in x2.

Would adding that below the description of the alternative help?

**Comment by terilias** [comment]
Thank you for your answer!
