### ISSUE TITLE
BUG: scipy test suite sometimes hangs in Slurm job

### ISSUE THREAD

**Issue by boegel** [scipy/scipy#19028]
### Describe your issue.

The SciPy test suite sometimes hangs when it's being run in parallel in an environment where resource usage is controlled via cgroups (for example a [Slurm](slurm.schedmd.com/) job).

### Reproducing Code Example

```python
python3 dev.py --no-build --install-prefix test -v -m full --parallel N # with N > 1
```

### Error message

```shell
No error messages, test suite hangs: runs for hours and eventually gets killed due to time limit for Slurm job
```

### SciPy/NumPy/Python version and system information

```shell
Python 3.11.3
numpy 1.25.1
scipy 1.11.1
pytest-xdist 3.3.1
```

**Comment by boegel** [comment]
The culprit here most likely is a bug in pytest-xdist, see also https://github.com/pytest-dev/pytest-xdist/issues/658

Workaround is to use `--parallel 1`, or not use `--parallel` at all (default is 1).

**Comment by andyfaff** [comment]
It sounds like this issue is closable then.

**Comment by rgommers** [comment]
`pytest-xdist` parallelism is absolutely terrible, it already starts getting slower with `--parallel 4`. So I'm not surprised that on a cluster with a potentially large number of cores it hangs completely. I'd say this is a `pytest-xdist` bug. 

Really I think we're waiting for someone to rewrite pytest + common plugins in Rust:)
