### ISSUE TITLE
BUG: stats.zscore returns all NaN if given masked array with first element masked

### ISSUE THREAD

**Issue by drammock** [scipy/scipy#19039]
### Describe your issue.

passing a masked array to `scipy.stats.zscore` yields results that are all `nan` when the first element of the array is masked.

### Reproducing Code Example

```python
import numpy as np
from scipy.stats import zscore

rng = np.random.default_rng(seed=8675309)  # tried with 3 different seeds
x = rng.standard_normal(10)
mask = np.zeros_like(x)
y = np.ma.masked_array(x, mask)
y.mask[1] = True
print(zscore(y))
# [-0.6327236439032247 -- -0.6005585026611974 0.03365730448338995
#  -0.9428312016417735 1.775001047420241 1.189629067553608
#  -0.5510199319620768 -1.2407231008627846 0.9695689615738183]
y.mask[1] = False
y.mask[0] = True  # still happens if additional elements are masked besides element [0]
print(zscore(y))
# [nan nan nan nan nan nan nan nan nan nan]
```

### Error message

```shell
n/a
```

### SciPy/NumPy/Python version and system information

```shell
1.11.1 1.25.2 sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/mambaforge/envs/mwe/include
    lib directory: /opt/mambaforge/envs/mwe/lib
    name: blas
    openblas configuration: unknown
    pc file directory: /opt/mambaforge/envs/mwe/lib/pkgconfig
    version: 3.9.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/mambaforge/envs/mwe/include
    lib directory: /opt/mambaforge/envs/mwe/lib
    name: lapack
    openblas configuration: unknown
    pc file directory: /opt/mambaforge/envs/mwe/lib/pkgconfig
    version: 3.9.0
  pybind11:
    detection method: pkgconfig
    include directory: /opt/mambaforge/envs/mwe/include
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: /home/conda/feedstock_root/build_artifacts/scipy-split_1687995550978/_build_env/bin/x86_64-conda-linux-gnu-cc
    linker: ld.bfd
    name: gcc
    version: 12.3.0
  c++:
    commands: /home/conda/feedstock_root/build_artifacts/scipy-split_1687995550978/_build_env/bin/x86_64-conda-linux-gnu-c++
    linker: ld.bfd
    name: gcc
    version: 12.3.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.35
  fortran:
    commands: /home/conda/feedstock_root/build_artifacts/scipy-split_1687995550978/_build_env/bin/x86_64-conda-linux-gnu-gfortran
    linker: ld.bfd
    name: gcc
    version: 12.3.0
  pythran:
    include directory: ../../../_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/mambaforge/envs/mwe/bin/python
  version: '3.11'
```

**Comment by WarrenWeckesser** [comment]
Thanks for reporting the issue, @drammock.

Here's another example, using a freshly built scipy (version '1.12.0.dev0+1454.d98afea'):

```
In [23]: from scipy.stats import zscore

In [24]: y = np.ma.masked_array([[1.5, 2, 3], [2, 1.5, 3]], mask=[[0, 1, 0], [1, 0, 0]])

In [25]: y
Out[25]: 
masked_array(
  data=[[1.5, --, 3.0],
        [--, 1.5, 3.0]],
  mask=[[False,  True, False],
        [ True, False, False]],
  fill_value=1e+20)

In [26]: zscore(y, axis=1)
Out[26]: 
masked_array(
  data=[[-1.0, --, 1.0],
        [nan, nan, nan]],
  mask=[[False,  True, False],
        [False, False, False]],
  fill_value=1e+20)
```

The second row should not be all `nan`.

**Comment by mdhaber** [comment]
This may be related to gh-8669 and gh-17755. If there is a quick fix we can consider patching `zscore` individually, since it appears to be one of the most used functions of its type. If not, these issues are part of the theme of gh-14651, and would be addressed as part of that.

**Comment by drammock** [comment]
IIUC it looks like the problem is with the use of `_first()` to determine whether the input was of constant value. When the first element is masked, the input is wrongly determined to be constant.

https://github.com/scipy/scipy/blob/d98afeae0fcb2302d0f25ba561e7984d5fadf65c/scipy/stats/_stats_py.py#L3153

**Comment by larsoner** [comment]
@drammock if `_first` can be fixed, PR welcome with that plus a tiny test that gives `nan` on `main` but correct values on this PR! From a very quick look it seems separate from #17755

**Comment by drammock** [comment]
I'll take a look tomorrow and see if I can come up with a reasonable patch.

**Comment by drammock** [comment]
I didn't have much time to look today. Interim conclusion is that for finding the first non-masked value along an axis `np.ma.nonmasked_edges` seems like it will help but it probably won't work (it simply omits indices when there are no unmasked elements, which means the results don't broadcast). In a chat with @larsoner he suggested an approach of reshaping input array to always be 2D and/or operating on the mask itself to find the relevant indices; I'll have a go at that early next week (unless someone beats me to it, which, feel free).

**Comment by mdhaber** [comment]
@drammock please let me know if fh-19093 looks alright to you. Since any non-masked element will do, I used `min`.

**Comment by drammock** [comment]
> @drammock please let me know if fh-19093 looks alright to you. Since we're just trying to detect whether all elements are the same, any non-masked element will do. I used `min` since it is simple, just as fast in fast cases, and fast enough compared to `std` in slow cases.

That looks fine, I was focused on fixing `_first` and should have just changed `zmap` to not call `_first` (as you did). Sorry this fell off my plate, it's been a very busy week
