### ISSUE TITLE
Build failure of SuperLU with the development version of numpy

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#19036]
NumPy has recently changed how it defines complex numbers in its C code.  As a result of these changes, the NumPy C header file "npy_common.h" now does `#include <complex.h>`.  This will break the compilation of any extension module that includes the NumPy C header files and that has its own definition of the name `complex`.  See https://github.com/numpy/numpy/issues/24344 and https://github.com/numpy/numpy/issues/24198 and the links therein for details.

We are encountering this problem with the SuperLU code.  Specifically, in https://github.com/scipy/scipy/blob/main/scipy/sparse/linalg/_dsolve/SuperLU/SRC/slu_scomplex.h, which has https://github.com/scipy/scipy/blob/7e7d8679269287564bb0c4bdf2b8da34a89592da/scipy/sparse/linalg/_dsolve/SuperLU/SRC/slu_scomplex.h#L31

Until SuperLU modernizes its code so that it doesn't rely on its own implementation of complex arithmetic (or at least doesn't use the name `complex`), AND someone then takes on the challenges of updating our vendored version, I think we'll have to add another patch to our vendored copy, to change the name `complex` to, say, `singlecomplex`.

**Comment by rgommers** [comment]
@lysnikolaou would you have time to patch this up and then upstream the fix to https://github.com/xiaoyeli/superlu?

**Comment by lysnikolaou** [comment]
> @lysnikolaou would you have time to patch this up and then upstream the fix to https://github.com/xiaoyeli/superlu?

Of course! I'll be back home and in front of a computer on Sunday, so I'll probably work on this on Monday. Is that okay?

**Comment by rgommers** [comment]
Sure no worries! And in case it bothers anyone enough before that time, they can fix it instead.

**Comment by lysnikolaou** [comment]
Opened #19062.
