### ISSUE TITLE
DOC: Scipy Sparse BSR does not support slicing: __getitem__ not implemented

### ISSUE THREAD

**Issue by szeliski** [scipy/scipy#19042]
### Issue with current documentation:

The documentation for the BSR (Block Compressed Row) at https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.bsr_array.html#scipy.sparse.bsr_array does not mention that slicing, e.g., a[0:3, 1:4] is not supported for this sparse matrix sub-class.

It took me a while to find in the source code for `_bsr.py` that the `__getitem__` function raises a `NotImplementedError` and to figure out that this is the only sparse matrix sub-class that does this (the rest default to the `__getitem__` method in `_index.py`.

Please add this to the documentation, along with an explanation as to why this has not been implemented.

### Idea or request for content:

Right after the following text in the class bsr_matrix comment string:

    Notes
    -----
    Sparse matrices can be used in arithmetic operations: they support
    addition, subtraction, multiplication, division, and matrix power.

Add the following text.

    The BSR format does not support slicing, e.g., m[0:1, 3:4] and is the only sparse matrix
     type to not support this.  Please use or convert to a different sparse array format if
     you need this functionality.

**Comment by dschult** [comment]
Indexing is supported for CSC, CSR, DOK and LIL formats.
The BSR, DIA and COO formats do not support indexing. 

We could also improve docs by describing other features 
that they do or do not support. For example, min/max, arithmetic, ...
