### ISSUE TITLE
Increase the nighly wheel upload frequency to daily during numpy 2.0 release cycle

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#19048]
What the title says - we're going to have regular breakage when things in numpy change, and when we fix them in scipy then all the users of our nightly wheels will need those fixes too to unbreak their own CI. 

We don't have to do this for all wheels; only the ones that are used regularly. I'd expect primarily x86-64 Linux, however right now the `cp312` wheels are also popular say the download stats: https://anaconda.org/scientific-python-nightly-wheels/scipy/files.

**Comment by rgommers** [comment]
Hat tip to @ngoldbaum for this suggestion.

**Comment by tylerjereddy** [comment]
Sounds fair, as you may have noticed I already did a manual one today in gh-19046 for `astropy` and `MDAnalysis` CI fails, so probably better than waiting for a maintainer to respond to a new ticket each time.
