### ISSUE TITLE
ENH: Need new scipy dev wheel for numpy dev compatibility

### ISSUE THREAD

**Issue by pllim** [scipy/scipy#19046]
### Is your feature request related to a problem? Please describe.

I am unable to run any job downstream that pulls both numpy dev and scipy dev wheels. I understand that you have fixed it in `main` but would really like that fix to land on your dev wheel too.

### Describe the solution you'd like.

New dev wheel.

### Describe alternatives you've considered.

Wait it out but it has been a few days.

### Additional context (e.g. screenshots, GIFs)

`E   ImportError: cannot import name 'ComplexWarning' from 'numpy'`

**Comment by tylerjereddy** [comment]
This came up in https://github.com/MDAnalysis/mdanalysis/issues/4232 as well, I imagine we'll get a few more reports. Let me check on this.

**Comment by tylerjereddy** [comment]
Ok, I manually triggered the GitHub actions wheel builder here: https://github.com/scipy/scipy/actions/runs/5835071653

I didn't trigger for the ARM architectures on cirrus CI--I think we're trying to be cautious of resource usage there, but one of us could probably do that if really needed. I believe the "natural" cron is about a day away from happening anyway?

**Comment by tylerjereddy** [comment]
Obviously, this may happen more frequently for a while, NumPy `main` is seeing a flurry of 2.0 and Python 3.12-related activity. We do try to keep up with patches on our side fairly swiftly.

**Comment by pllim** [comment]
Thanks! I see that cp312 jobs failed but date stamp updated at https://anaconda.org/scientific-python-nightly-wheels/repo so 🤞
