### ISSUE TITLE
DOC: typo in scipy.linalg.pinv.html

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#19063]
### Issue with current documentation:

`hermititan`

**Comment by keithbriggs** [comment]
Another one on the same page: `independant`

**Comment by lucascolley** [comment]
Here are the lines containing the typos:
https://github.com/scipy/scipy/blob/881b9fe85eae39015693ea3c83d406c252eebcab/scipy/linalg/_basic.py#L1385C55-L1385C55
https://github.com/scipy/scipy/blob/881b9fe85eae39015693ea3c83d406c252eebcab/scipy/linalg/_basic.py#L1415C9-L1415C9

**Comment by j-bowhay** [comment]
Whoops I should stay away from writing docs! Would you be willing to submit a pr @keithbriggs  ?

**Comment by keithbriggs** [comment]
Probably - give me a bit of time to set things up.
