### ISSUE TITLE
ENH: Allow to choose line-search parameters in related optimization algorithms

### ISSUE THREAD

**Issue by paulestano** [scipy/scipy#19075]
### Is your feature request related to a problem? Please describe.

While looking at #18481 I noticed it is not yet possible to choose `c1` and/or `c2` parameters of the line-search algorithm used within multiple optimization algorithms (CG, BFGS, NEWTON-CG) from the `scipy.optimize.minimize` API.

### Describe the solution you'd like.

Add `c1` and `c2` parameters with default values to `1e-4` and `0.9` to the signature of [`_minimize_newtoncg`](https://github.com/scipy/scipy/blob/5ebc7afe8949d097728ee5b93271a481f2fcb881/scipy/optimize/_optimize.py#L1980), [`_minimize_cg`](https://github.com/scipy/scipy/blob/5ebc7afe8949d097728ee5b93271a481f2fcb881/scipy/optimize/_optimize.py#L1720) and [`_minimize_bfgs`](https://github.com/scipy/scipy/blob/5ebc7afe8949d097728ee5b93271a481f2fcb881/scipy/optimize/_optimize.py#L1382) .

### Describe alternatives you've considered.

I am not mastering the whole `scipy.optimize` code base but I can't see any other straightforward one.

**Comment by andyfaff** [comment]
This is already covered by #18977 for BFGS

**Comment by paulestano** [comment]
I was not aware of this PR. Is there any reason for not exposing `c1` and `c2` for other algorithms than BFGS?

**Comment by dschmitz89** [comment]
I don't think there are reasons against it. So far just no one looked into it.

Would you be interested in submitting a PR? #18977 can serve as a helpful example.
