### ISSUE TITLE
BUG: scipy.special.gammasgn implementation & docs inconsistent with numpy.sign of scipy.special.gamma

### ISSUE THREAD

**Issue by goxberry** [scipy/scipy#19071]
## Summary

The `scipy.special.gammasgn` function does not quite appear to do what it says -- compute the sign of the gamma function -- nor does the documentation of `scipy.special.gammasgn` reflect its definition in the SciPy source code, at least as of commit https://github.com/scipy/scipy/commit/ac729b8f96a018b9156a0e5679e18b5d6e2e70a7.

Discrepancies only appear when invoking `scipy.special.gammasgn` on inputs that are negative integers or minus infinity. The negative integers are singularities of the gamma function, so whether these discrepancies actually matter to users in practice is difficult to say; I only noticed because I was poking around multiple versions of Cephes, including the modified version vendored into SciPy. The discrepancies occur at singularities because the implementation of `gammasgn` appears to have been chosen for consistence with the sign of `scipy.special.rgamma`, the reciprocal gamma function. At those singularities, the reciprocal gamma function has a value of zero, whereas the numerical computation of the gamma function uses the one-sided limit of the gamma function from above to impute a sign onto the computation.

Given that `gammasgn` is used in multiple places, including the computation of Struve functions, some hypergeometric functions, and Pochhammer symbols, I'm not sure what the impact of changes to `gammasgn` would be without more investigation. Perhaps the best path forward is to modify the `gammasgn` documentation to reflect slightly more accurately what `gammasgn` actually does. A riskier option would be to change the `gammasgn` implementation to better reflect the documentation. Another option would be to do nothing. (Not my preference, but I'd respect that decision.)

----

## Details

Augmenting an example from the SciPy test suite[^1]:

```pycon
>>> import numpy, scipy
>>> x = numpy.array([-numpy.inf, -4, -3.5, -3, -2.3, 0, 1, 4.2, numpy.inf, numpy.nan])
>>> sign_gamma = numpy.sign(scipy.special.gamma(x))
>>> gammasgn = scipy.special.gammasgn(x)
>>> sign_rgamma = numpy.sign(scipy.special.rgamma(x))
>>> sign_gamma
array([-1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1., nan])
>>> gammasgn
array([ 1.,  0.,  1.,  0., -1.,  0.,  1.,  1.,  1., nan])
>>> sign_rgamma
array([nan,  0.,  1.,  0., -1.,  0.,  1.,  1.,  0., nan])
```

Notably, `sign_gamma` and `gammasgn` are not equal, which suggests that `scipy.gammasgn` does not return the sign of the gamma function for nonpositive integers and for minus infinity. The documentation[^2] for `scipy.special.gammasgn` also indicates the output of that function will not take on values other than -1.0 or +1.0, except possibly at zero (where it is unspecified in the documentation), or when its input is `numpy.nan` (not stated in the documentation, but it's a reasonable inference). Given that these inputs are edge cases, I could see why those cases might not be mentioned.

As far as I can tell, `scipy.special.gammasgn` is implemented to be consistent with the sign of `scipy.special.rgamma` for finite and `numpy.nan` (or equivalent[^3]) values because that is what the unit test in [^1] tests -- at least for finite values. It's worth noting here that both the Netlib Cephes and SciPy Cephes implementations of `rgamma` do *not* use `gammasgn`, and perhaps that's why `rgamma` was used in the `gammasgn` unit tests[^1], even though the sign of `rgamma` isn't consistent with the sign of the Gamma function. I can appreciate why one would think `rgamma` and the gamma function would have consistent signs -- given properties of real arithmetic, that's not an unreasonable inference, and it's also true for most inputs. However, at singularities of the gamma function, the numerical implementation of the gamma function in floating point arithmetic will impute a sign to the output of that function. The sign imputed corresponds to the one-sided limit of the gamma function from above. For finite inputs, the reciprocal gamma function will return zero (both in real and floating-point arithmetic) at those singularities of the gamma function, effectively "removing" the sign of the function.

An implementation of `gammasgn` that would be more faithful for nonpositive integers in Python would be

```python
import numpy

# An implementation in C is discussed later; this version is provided
# for clarity.
def gammasgn(x: float) -> float:
    # In Cephes, this case would actually return 1.0, but in SciPy, it might
    # make sense to stick with NaN.
    if numpy.isnan(x):
        return x

    if numpy.isinf(x):
        return 1.0

    if x >= 0:
        return 1.0

    # The actual implementation in Cephes uses a bitwise and operator;
    # this simplification is purely for readability and clarity.
    if numnpy.floor(x) % 2 == 0:
        return -1.0

    # Otherwise, if x < 0 and its truncated value is even (so its
    # floor is odd), the gamma function is positive (or undefined).
    return 1.0
```

and in C would be:

```c
#include <math.h>
#include "mconf.h" /* This header is from Cephes. */

double gammasgn(double x)
{
    if (isnan(x)) {
      return x;
    }

    if (!isfinite(x)) {
      return 1.0;
    }

    if (x > 0) {
        return 1.0;
    }

    /* else x <= 0, x finite, and x is not NaN */
    double fx = floor(x);
    if ((int)fx % 2 /* != 0 */) { /* Cephes uses ((int)fx & 1 == 0) */
        return -1.0;
    }
    
    /* else ((int)fx % 2 == 0) */
    return 1.0;
}
```

The Netlib Cephes source code [^4][^5] and its version in SciPy both compute a value (in C) stored in a [symbol called `sgngam`](https://github.com/scipy/scipy/blob/c20c60f2a149c314611b02aff5652ad5665132b4/scipy/special/cephes/gamma.c#L164) that signifies the "sign of the gamma function". The code snippets above correspond to the values of `sgngam` upon exit of the Cephes implementations of the gamma function and log gamma functions.

As mentioned earlier, the potential impacts of changing `scipy.special.gammasgn` aren't entirely clear (or at least, not clear to me without testing).

[^1]: Specifically, https://github.com/scipy/scipy/blob/c20c60f2a149c314611b02aff5652ad5665132b4/scipy/special/tests/test_basic.py#L421-L423.
[^2]: https://github.com/scipy/scipy/blob/a779101423c50f3af4c4e81a4b87762d59475d9e/scipy/special/_add_newdocs.py#L5777-L5848
[^3]: e.g., `math.nan`, IEEE-754 "not a number".
[^4]: Hosted at https://www.netlib.org/cephes/.
[^5]: A GitHub mirror of this source code can be found at https://github.com/jeremybarnes/cephes.

### Reproducing Code Example

```python
see above
```

### Error message

```shell
Not applicable.
```

### SciPy/NumPy/Python version and system information

```shell
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()
1.11.1 1.25.2 sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.35
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-ozcbcrh7/overlay/lib/python3.9/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp39-cp39/bin/python
  version: '3.9'
```

**Comment by steppi** [comment]
I agree it would be good to have more consistency.

Since strictly speaking $\Gamma$ isn't defined at negative integers, I think `NaN` is a reasonable value, but a common convention in complex analysis is to take as the sign the limit of the sign from above, which is consistent with the sign of the residue

$$\mathrm{Res}\left(\Gamma, -n\right) = \frac{(-1)^n}{n!}$$

If I'm reading correctly, it looks like that's what you're proposing above.

cephes' implementation of the $\Gamma$ function just returns positive infinity at all of the poles. However, the implementation we use for complex numbers, defined [here](https://github.com/scipy/scipy/blob/6d7daabd759719a075b5a1f35a86da443ee4e0b6/scipy/special/_loggamma.pxd#L148), returns `NaN`s at the poles. At a glance I think `NaN` or the limit from above are the only defensible choices. I'd like find out why cephes went with the convention they did.  I think it would be good if  `gammasgn`, `gamma` for real values, and `gamma` for complex values were all consistent at the poles.

I'll try to look into how things could break downstream, but tentatively I'm supportive of making a change beyond just a docs solution.

**Comment by goxberry** [comment]
> Since strictly speaking $\Gamma$ isn't defined at negative integers, I think NaN is a reasonable value.

I agree with you, and so does Annex F.9.5.4 of the C99 standard, the IEEE-754 standard, and the [POSIX.1-2017 standard](https://pubs.opengroup.org/onlinepubs/9699919799/functions/tgamma.html).

> Since strictly speaking isn't defined at negative integers, I think NaN is a reasonable value, but a common convention in complex analysis is to take as the sign the limit of the sign from above, which is consistent with the sign of the residue $\mathrm{Res}(\Gamma, -n) = (-1)^{n} / n!$. If I'm reading correctly, it looks like that's what you're proposing above.

Yes, it is.

> I'd like find out why cephes went with the convention they did.

I'm curious about that as well. That said, I don't know whether the author of Netlib Cephes is alive, and there are parts of the library that predate the IEEE-754 and C89 standards. The Netlib Cephes implementation of `pow`, for instance, does not conform to IEEE-754 and C99 standards because `pow(1, nan)` should equal 1 instead of NaN, along with a few other corner cases.

As for alternatives, [the POSIX.1-2017 standard](https://pubs.opengroup.org/onlinepubs/9699919799/functions/lgamma.html) states that the value of the sign of $\Gamma$ is left unspecified at its poles. The implementations of `lgamma_r` (log of $\Gamma$) in [musl](https://github.com/bminor/musl/blob/718f363bc2067b6487900eddc9180c84e7739f80/src/math/lgamma_r.c#L178) and [fdlibm](https://github.com/freemint/fdlibm/blob/2ac612603bf5fcfadf76e1b53952da8827733ae6/e_lgamma_r.c#L252) both store the sign of $\Gamma$ in a variable named `signgamp`, and both store a value of +1 in that variable at the finite poles of $\Gamma$. That convention differs from the convention I proposed above (and thus also the convention used in Netlib Cephes).

**Comment by steppi** [comment]
> I agree with you, and so does Annex F.9.5.4 of the C99 standard, the IEEE-754 standard, and the [POSIX.1-2017 standard](https://pubs.opengroup.org/onlinepubs/9699919799/functions/tgamma.html).

Thanks for the link to the POXIX.1-2017 standard.

Beyond the sign issues, the behavior of SciPy's `gamma` implementation at $-\infty$ at at poles is a little troubling. For Netlib Cephes, `gamma` does return `NaN` at negative integers, we can see that here in the commit where cephes was first added to SciPy in 2001:

https://github.com/scipy/scipy/blob/52c64a94dee663b941de2b2f6592dcc6bfc4f817/Lib/special/cephes/gamma.c#L336-L344

Almost a year later in 2002 this behavior was changed:

https://github.com/scipy/scipy/blob/dbb3d6a4bf4bee31634e9b8747cb0bd6323f6288/Lib/special/cephes/gamma.c#L334-L344

and also $\Gamma(-\infty)$ was changed to be $-\infty$.

I'm not sure why this was done. The commit message was *"Made several special functions valid for complex numbers and added more special functions."* which isn't too helpful.

imo `gamma` in SciPy should return `NaN` at the poles and at $-\infty$, which is already the behavior for complex arguments.

I wonder if making `gamma` return $+\infty$ at the polls was a pragmatic way to make calculations work out when `gamma` at a pole appears in the denominator? In any case, changing the return value to the POSIX.1-2017 specified `NaN` will likely break some real code instances where `gamma` appears in the denominator of an expression.

Before working on the consistency of `gammasgn` I think it would be good to change the return values at the poles and at $-\infty$. 

I'm not very knowledgeable about the deprecation process. @h-vetinari, @j-bowhay, what might it entail to change the return value of `gamma` (for double arguments) at negative integers and negative infinity to `NaN`? Do either of you have an opinion on whether the improvement in consistency would be worth it? `NaN` is already returned in these cases for complex arguments.

Thanks again @goxberry for bringing these things to light. Any bug reports that could help us improve `special` are appreciated.

**Comment by j-bowhay** [comment]
As you say the change can either be made directly if you consider this enough of a bug or the other option is to introduce a legacy kwarg as was used for changing the behaviour of the factorial functions. Either way, I would suggest a post to the mailing list explaining the change and rationale would be appropriate.

**Comment by goxberry** [comment]
> I wonder if making gamma return $+\infty$ at the poles was a pragmatic way to make calculations work out when gamma at a pole appears in the denominator?

The POSIX.1-2017 standard permits using an implementation-defined value at negative integers, but only if the compiler isn't configured for IEEE-754 conformance (detectable via preprocessor macros); IEEE-754 requires those values be NaNs. Given that $\Gamma$ is meromorphic, I wouldn't be surprised if the $+\infty$ value at negative integers were set for precisely that reason -- then `1.0 / gamma(x) == rgamma(x) == 0.0`.

**Comment by steppi** [comment]
> As you say the change can either be made directly if you consider this enough of a bug or the other option is to introduce a legacy kwarg as was used for changing the behaviour of the factorial functions. Either way, I would suggest a post to the mailing list explaining the change and rationale would be appropriate.

Thanks.  I consider this a bug, but a direct change would likely burn some users for the reasons mentioned above, so I'd be inclined towards introducing the legacy kwarg. There should probably be a separate issue just for the behavior of `gamma`  at the poles, and agreed that this should go through the mailing list. I'll probably have time to write up another issue + a mailing list post sometime within the next two weeks, but @goxberry you're welcome (and encouraged) to do one or both sooner since you have a good grasp on the issue.

**Comment by goxberry** [comment]
@steppi I'd be happy to write something up for both the behavior of `gamma` at poles and a mailing list post, although I likely won't be able to get to either until 2023-09-02 at the earliest.

**Comment by steppi** [comment]
> @steppi I'd be happy to write something up for both the behavior of `gamma` at poles and a mailing list post, although I likely won't be able to get to either until 2023-09-02 at the earliest.

Sounds good. I don't think I would be able to get to it until maybe a week after that. I appreciate it.

**Comment by h-vetinari** [comment]
I ran into this while trying to add the extensions for the factorial* functions to complex numbers, and noted that `gamma(n) == inf` for all negative integers, which is just wrong on several levels (even if we accept the "limit from above" convention).

> imo `gamma` in SciPy should return `NaN` at the poles

+100, this was the issue I would have raised independently (had it not existed already)

> I'm not very knowledgeable about the deprecation process. @h-vetinari, @j-bowhay, what might it entail to change the return value of `gamma` (for double arguments) at negative integers and negative infinity to `NaN`? Do either of you have an opinion on whether the improvement in consistency would be worth it? `NaN` is already returned in these cases for complex arguments.

I'm very sorry I missed this ping. I would say it's overkill to go through a deprecation period for this. I find it hard to believe that someone relies exactly on the poles being `inf` rather than `NaN`. I would of course call it out in the docstring and the release notes, but IMO we should just change it.

**Comment by steppi** [comment]
> I'm very sorry I missed this ping. I would say it's overkill to go through a deprecation period for this. I find it hard to believe that someone relies exactly on the poles being `inf` rather than `NaN`. I would of course call it out in the docstring and the release notes, but IMO we should just change it.

Unfortunately, I think this actually would break some user code. At the moment, expressions which naively divide by `gamma` will still work out correctly, e.g. `1/gamma(-2)` will evaluate to zero. It seems current behavior at the poles was a deliberate departure from cephes made in SciPy’s earliest days, but I couldn’t find the reason in my code archeology expedition. I suspect this was done to make expressions work out correctly when `gamma` is in a denominator somewhere.

I think a deprecation cycle might actually be needed.

**Comment by h-vetinari** [comment]
> At the moment, expressions which naively divide by `gamma` will still work out correctly, e.g. `1/gamma(-2)` will evaluate to zero.

I mean yes, every change is observable _somehow_, I just don't think it's worth doing a deprecation dance for _this one_. For example, in cleaning up the factorial functions (#15600), some were returning 0-dim arrays instead of scalars, and we just fixed those (as had been done [previously](https://github.com/scipy/scipy/pull/10954)).

To my mind, a deprecation cycle is for things where it's clear that the degree of disruption would be non-negligible. But if we needed to deprecate every single observable behaviour change, things would grind to a halt. Even if it does affect someone, scipy is still a versioned library, and users can make use of that to constrain their dependencies, etc.

It's always a trade-off between how many users we are serving (protecting from breakage) and how much effort it is maintenance-wise. That said, I don't mind being conservative if you really think this is worth our time. In any case, we need to fix it IMO.

**Comment by steppi** [comment]
Yeah. I also think it would be preferable if we didn’t have to do the deprecation cycle, but I’m concerned about the ways this could break in ways that would be difficult for end users to detect. Imagine if someone is using a pipeline which does some transform involving the gamma function, where the implementation was just copied out of a book without thought for its numerical properties. This could be working for them now, but with the next release the now incidentally correct result will be replaced with `NaN`. Now suppose `NaN` values are later being, dropped, filled or imputed in the pipeline. I would hate to be a grad student trying to figure out why my results have degraded.

Maybe I’m overthinking it though.

**Comment by h-vetinari** [comment]
> Maybe I’m overthinking it though.

I think a scenario where "incidentally correct" depends on a wrong definition of the values of gamma in its poles (already highly instable unless you use integers) is quite a stretch, but maybe I'm to cavalier 🤷

**Comment by steppi** [comment]
> I think a scenario where "incidentally correct" depends on a wrong definition of the values of gamma in its poles (already highly instable unless you use integers) is quite a stretch, but maybe I'm to cavalier 🤷

I don't think you're being too cavalier, and you have a lot more experience with the deprecation process. It's a strange situation though. It really seems like the incorrect behavior may have been deliberately chosen precisely for handling ratios containing gamma functions. We see in the first commit adding special, https://github.com/scipy/scipy/blob/52c64a94dee663b941de2b2f6592dcc6bfc4f817/Lib/special/cephes/gamma.c#L336-L344 that `NaN` is returned.

This behavior was changed 9 months later here, https://github.com/scipy/scipy/blob/dbb3d6a4bf4bee31634e9b8747cb0bd6323f6288/Lib/special/cephes/gamma.c#L336-L345.
Though the [README](https://github.com/scipy/scipy/blob/dbb3d6a4bf4bee31634e9b8747cb0bd6323f6288/Lib/special/README) for `special` at the time does explain the mystery of `gamma` being changed to `Gamma` in SciPy's vendored copy of `cephes`, no mention is made of the unusual choice for `Gamma`, nee `gamma` at the poles.

The strange behavior where `gammasgn` actually gives the sign of `rgamma` is the other piece of evidence.

I agree we should update `gamma` to correctly return `NaN` at the poles. I'd like to at least see it go through the mailing list. I don't want to push for a deprecation process if no one else thinks it's necessary.

**Comment by h-vetinari** [comment]
Just noticed that `gamma(-np.inf) == -np.inf`, which - aside from being wrong - is also inconsistent with how currently all negative integers get assigned positive infinity.
