### ISSUE TITLE
MAINT, REL: Programming Language directive

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#19082]
I never remember to do this, but you can see on bottom left of https://pypi.org/project/scipy/1.11.2/ that `Programming Language` directive should probably be expanded to include `3.12` moving forward.

I think this is pretty minor though. I assume we'll want to change it in `pyproject.toml`, but perhaps not `_setup.py` which is really mostly intended for `conda-forge` windows.

**Comment by rgommers** [comment]
Ah yes, classifiers ... 

> I assume we'll want to change it in `pyproject.toml`, but perhaps not `_setup.py` which is really mostly intended for `conda-forge` windows.

Indeed. I wanted to make a few more tweaks, so let me take this along today.
