### ISSUE TITLE
DOC: Error in the example for wavfile.read()

### ISSUE THREAD

**Issue by mortalis13** [scipy/scipy#19099]
### Issue with current documentation:

In the documentation for the function `scipy.io.wavfile.read` the example shows how to get the number of channels with the following line:
```
print(f"number of channels = {data.shape[1]}")
```
This would work for stereo files but for mono it returns an error, as `data.shape` only has 1 dimension.

### Idea or request for content:

Maybe that line should be replaced with this one:
```
print(f"number of channels = {len(data.shape)}")
```
Thanks.

**Comment by j-bowhay** [comment]
![image](https://github.com/scipy/scipy/assets/60778417/52608c7e-3d33-4afa-afc5-e1670920d24d)
Thanks for reporting. Not sure the proposed change is correct as for `Nchannels`>2 it will still show 2. I am inclined to close this as I am not sure the example needs to be generalised to mono. What do you think @mortalis13 @yanchick ?

**Comment by mortalis13** [comment]
Yeah, you're right. Missed that part, thought the `data` had N size per N channels.
But it's of size 1 or 2 only, so it was a bit confusing at the beginning, so you have to do an extra step to check if it's mono o N channels.
Thanks for clarifying.
