### ISSUE TITLE
ENH: update vendored SuperLU version

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#19092]
### Is your feature request related to a problem? Please describe.

SuperLU is at the core of `sparse.linalg`. Recently, [version 6.0](https://github.com/xiaoyeli/superlu/releases/tag/v6.0.0) was released with support for 64bit index support. Changing from 32bit to 64bit indexing in scipy 's sparse arrays caused a lot of issues such as #18644 downstream because scipy's SuperLU cannot handle them at the moment. Updating the SuperLU version would resolve this issue.

The biggest issue is likely the complexity of the wrapper as scipy not only needs to wrap the C code in a safe way but additionally applied some [patches](https://github.com/scipy/scipy/blob/main/scipy/sparse/linalg/_dsolve/SuperLU/scipychanges.patch) to work around other issues in SuperLU.

**Comment by rgommers** [comment]
I'm in the middle of untangling this. Not sure I can finish soon, but if not I'll submit a PR for what I have so far.
