### ISSUE TITLE
BUG: optimize.root returns OptimizeResult instead of RootResults

### ISSUE THREAD

**Issue by lorentzenchr** [scipy/scipy#19097]
### Describe your issue.

`scipy.optimize.root` for multidimensional (function) root finding return a `OptimizeResult` object instead of a `RootResults` as `root_scalar` does.
As both classes have different attributes, it makes it more difficult to use them both (one needs more case distinctions).

**Comment by mdhaber** [comment]
I don't think this is a bug. It is an `OptimizeResult` in the sense that it is a result returned by a function in `scipy.optimize`. `root_scalar` was the oddball in that it returned a `RootResult`, but now that is a subclass of `OptimizeResult`. `OptmizeResult`s are not consistent in the attributes they include, sure. What do you suggest can be done in a backward compatible way besides improve documentation? We could add aliases and deprecate old names, but that would need discussion on the mailing list.

**Comment by j-bowhay** [comment]
I guess the fact the attributes of the two objects are not named the same is unfortunate, ie we have:

(`RootResult` vs `OptimizeResult`)
- `root` vs `x`
- `iterations` vs `nit`
- `function_calls` vs `nfev`
- `converged` vs `success`
- `flag` vs `message`

Unifying the interfaces would be nice if we were starting from scratch but fairly on the fence about whether we want to inconvenience users through a deprecation/renaming cycle for what is a cosmetic change. @lorentzenchr @mdhaber what are your thoughts here?

**Comment by mdhaber** [comment]
My thoughts are above. 
Also, I wouldn't support attribute name changes because there are enough other issues with `root_scalar` that I'd prefer a replacement rather than disruptive modifications. It's not so urgent that it needs this issue as a reminder, though, so I would be happy to close the issue.

**Comment by j-bowhay** [comment]
Ok I am happy to close too, there are bigger fish to fry!

**Comment by mdhaber** [comment]
@lorentzenchr you are welcome to propose interface changes on the mailing list if you'd still like to pursue this. If they get a lot of traction, we can reopen.

**Comment by lorentzenchr** [comment]
It is not a bug, true. But recently, I got to make the case distinction between 1d and nd root finding and it was a bit of an annoying experience. That's all.

How about adding the same names of OptimizeResult to RootResults (just redirecting as property) such that `rootresult.x` and `rootresult.root` are identical?

**Comment by mdhaber** [comment]
You can propose that, but in my experience people are not fond of aliases.
