### ISSUE TITLE
ENH: add method in RootResults of root_scalar and root

### ISSUE THREAD

**Issue by lorentzenchr** [scipy/scipy#19098]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like.

Add an attribute `method` to the result object of `root_scalar` and `root`.

### Additional context (e.g. screenshots, GIFs)

It is already hard to tell which method is chosen as default. It would be nice to have it at least in the return results object.

**Comment by mdhaber** [comment]
This seems helpful and not contentious. Will you submit a PR @lorentzenchr ?
