### ISSUE TITLE
cannot interpolate multiple groups of data at one time

### ISSUE THREAD

**Issue by BeijingBlueSky** [scipy/scipy#19108]
### Describe your issue.

I have N groups of data that need to be interpolated. The data formats as (N, M, D), where N, M, and D mean that there are N groups of data, each group of data has M points, and each point has D dimension. e.g, (10, 100, 2) means that there are 10 groups data and each groups of data has 100 2d points. Of course, I could use a loop to interpolate each group of data, but that would be very slow(since N is very large) and I want to interpolate N groups of data at once.

### Reproducing Code Example

```python
'''python
import numpy as np
from scipy.interpolate import LinearNDInterpolator

# 10 groups of data and each group has 100 2-d points
data = np.random.random((10,100,2))
values = np.random.random((10,100))

# a loop to interpolate each group of data, which work well
# for i in range(data.shape[0]):
#     interp = LinearNDInterpolator(data[i],values[i])

# interpolate all data at once, do not work
interp = LinearNDInterpolator(data,values)
'''
```

### Error message

```shell
Traceback (most recent call last):
  File ".\test_opt_time.py", line 87, in <module>
    interp = LinearNDInterpolator(data,values)
  File "interpnd.pyx", line 278, in scipy.interpolate.interpnd.LinearNDInterpolator.__init__
  File "interpnd.pyx", line 78, in scipy.interpolate.interpnd.NDInterpolatorBase.__init__
  File "interpnd.pyx", line 194, in scipy.interpolate.interpnd._check_init_shape
ValueError: invalid shape for input data points
```

### SciPy/NumPy/Python version and system information

```shell
print(scipy.__version__, np.__version__, sys.version_info)

1.7.1 1.20.3 sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)
```

**Comment by j-bowhay** [comment]
Please could you edit the title with a valid summary

**Comment by rkern** [comment]
I'm not sure there's any practical amount of overhead that can be gotten rid of by collapsing this into one call. The `LinearNDInterpolator` would still need to do `N` separate Delaunay triangulations.

**Comment by ev-br** [comment]
LinearNDInterpolator can handle multiple `values`, stacked at the trailing _dimensions_. That is, if you have single `points` array of shape `(npts, ndims)` and `values` of dimensions `(npts, N)`, and you evaluate it on `xi` of shape `(ndims,)`, it will return at the result of shape `(N,)`. Following up the OP example:

```
>>> interp = LinearNDInterpolator(data[0, ...], values.T)     # values.T.shape = (100, 10)
>>> interp((0.5, 0.5))
array([0.33235109, 0.50261742, 0.4093455 , 0.50418409, 0.3644    ,
       0.30866288, 0.22372978, 0.74048567, 0.15668861, 0.47085499])
```

Vectorizing over stacked `points` is indeed not supported, and unlikely to be supported in the future, exactly for the reasons Robert mentioned above. 

Concluding, this enhancement request is not really actionable, and I'm going to close it.
