### ISSUE TITLE
BUG: scipy-1.5.4-cp37-cp37m-win32.whl sha256 mismatch

### ISSUE THREAD

**Issue by rwgk** [scipy/scipy#19119]
### Describe your issue.

For the last 3-4 days we're getting this error in the pybind11 GHA:

* https://github.com/pybind/pybind11/actions/runs/5954169481/job/16150117926

Is this a known issue?

I looked for the "Expected" hash in the pybind11 source tree but it's not coming from there.

### Reproducing Code Example

```python
https://github.com/pybind/pybind11/actions/runs/5954169481/job/16150117926
```

### Error message

```shell
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    scipy==1.5.4 from https://files.pythonhosted.org/packages/f4/4a/d2a1ace4fb6f94a4f6ac553be45249719c25185e7b10975f916e523d146c/scipy-1.5.4-cp37-cp37m-win32.whl (from -r tests/requirements.txt (line 8)):
        Expected sha256 d6d25c41a009e3c6b7e757338948d0076ee1dd1770d1c09ec131f11946883c54
             Got        51c2aeb8c1e18b964e0abcb758fdc29c19348e7e8ea718279f552bb3def6aea2
```
```


### SciPy/NumPy/Python version and system information

```shell
scipy-1.5.4-cp37-cp37m-win32.whl
```

**Comment by tylerjereddy** [comment]
I used `sha256sum` to verify the hash obtained for that wheel from both the GitHub release page and a direct download via `pip download` (PyPI), and both agreed that the expected hash should indeed be `d6d25c41a009e3c6b7e757338948d0076ee1dd1770d1c09ec131f11946883c54`.

I also checked the original email I sent as release manager three years ago here: https://mail.python.org/archives/list/scipy-dev@python.org/message/IMXF2AXD5JE4JNG7K6MT2LTPFBE7G2BH/

And the hash still agrees with my manual checks above.

So, the expected value you get does appear correct to me as the release manager.

I have seen problems with mismatches before, but mostly in an internal context where security policies are modifying the zip files that carry wheels to try to sign them, but I can't imagine that would be happening on any regular GitHub actions workflow.

**Comment by rwgk** [comment]
Thanks a lot for looking into this!

I'll ask around if anyone can think of how the hash might wind up being unexpected.

FWIW, we have 23 jobs downloading scipy, the counts are:

```
   1 scipy-1.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
   2 scipy-1.10.0-cp310-cp310-win_amd64.whl (42.5 MB)
   1 scipy-1.11.2-cp311-cp311-macosx_10_9_x86_64.whl (37.0 MB)
   1 scipy-1.11.2-cp311-cp311-macosx_10_9_x86_64.whl.metadata (54 kB)
   3 scipy-1.5.4-cp36-cp36m-manylinux1_x86_64.whl (25.9 MB)
   1 scipy-1.5.4-cp36-cp36m-win32.whl (28.3 MB)
   2 scipy-1.5.4-cp36-cp36m-win_amd64.whl (31.2 MB)
   1 scipy-1.5.4-cp37-cp37m-win32.whl (28.3 MB)
   1 scipy-1.5.4-cp38-cp38-manylinux1_x86_64.whl (25.8 MB)
   2 scipy-1.5.4-cp38-cp38-win32.whl (28.4 MB)
   3 scipy-1.5.4-cp39-cp39-manylinux1_x86_64.whl (25.8 MB)
   2 scipy-1.5.4-cp39-cp39-win32.whl (28.4 MB)
   3 scipy-1.5.4-cp39-cp39-win_amd64.whl (31.4 MB)
```

It's just that one that suddenly stopped working.

**Comment by andyfaff** [comment]
It's beside the point, but 1.5.4 is fairly old now. Would the pybind11 test suite be better served by using a more recent version, e.g. 1.8/1.9?

**Comment by rwgk** [comment]
> It's beside the point, but 1.5.4 is fairly old now. Would the pybind11 test suite be better served by using a more recent version, e.g. 1.8/1.9?

I gave it a quick try, it was a crash landing: https://github.com/pybind/pybind11/pull/4816

But before I continue:

**The problem seems to have magically disappeared:** https://github.com/pybind/pybind11/actions/runs/5978589805?pr=4814

So we can close this bug.

Coming back to  https://github.com/pybind/pybind11/pull/4816, from the failures I **SUSPECT** that there is a mirror somewhere, or maybe even multiple, and that a mirrored version of scipy-1.5.4-cp37-cp37m-win32.whl was temporarily corrupted in some way.

Here is why I'm thinking that:

Using "Download log archive" from here:

* https://github.com/pybind/pybind11/actions/runs/5980799634/job/16227636792?pr=4816

* Filename: logs_29804.zip

```
$ grep 'Downloading scipy' *.txt  | sed 's/.*Downloading scipy/scipy/' | sort | uniq -c
      1 scipy-1.10.0-cp310-cp310-macosx_10_15_x86_64.whl (35.1 MB)
      1 scipy-1.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
      2 scipy-1.10.0-cp310-cp310-win_amd64.whl (42.5 MB)
      1 scipy-1.11.2-cp311-cp311-macosx_10_9_x86_64.whl (37.0 MB)
      1 scipy-1.11.2-cp311-cp311-macosx_10_9_x86_64.whl.metadata (54 kB)
      1 scipy-1.8.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.6 MB)
      2 scipy-1.8.1-cp38-cp38-win32.whl (33.4 MB)
      1 scipy-1.8.1-cp39-cp39-macosx_12_0_universal2.macosx_10_9_x86_64.whl (55.6 MB)
      3 scipy-1.8.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (42.2 MB)
      2 scipy-1.8.1-cp39-cp39-win32.whl (33.4 MB)
      3 scipy-1.8.1-cp39-cp39-win_amd64.whl (36.9 MB)
```

```
$ grep 'ERROR: Could not find a version that satisfies the requirement scipy' *.txt | sed 's/.*Z ERROR: //' | sort | uniq -c
      7 Could not find a version that satisfies the requirement scipy==1.8.1 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4)
      1 Could not find a version that satisfies the requirement scipy==1.8.1 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0, 1.7.1, 1.7.2, 1.7.3)
```

So we are successfully receiving scipy-1.8.1 on some platforms, but not all.

The platforms that fail with an `ERROR` are:

```
1___3.6___MSVC_2019___x86.txt
1___3.6___ubuntu-20.04___x64_-DPYBIND11_FINDPYTHON=ON_-DCMA.txt
1___3___centos7___x64.txt
17___3.6___macos-latest___x64.txt
2___3.7___MSVC_2019___x86_-DCMAKE_CXX_STANDARD=14.txt
2___3___almalinux8___x64.txt
25___3.6___windows-2019___x64_-DPYBIND11_FINDPYTHON=ON.txt
9___3.6___windows-2022___x64.txt
```

Is there something obvious and useful we can learn from this?

**Comment by rwgk** [comment]
Some extra information, while I have it handy:

`ERROR` version lists by platform:

```
3.7___MSVC_2019
(from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0, 1.7.1, 1.7.2, 1.7.3)

MSVC_2019  other than the above!
almalinux8
centos7
macos-latest
ubuntu-20.04
windows-2019
windows-2022
(from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4)
```
