### ISSUE TITLE
No way to specify CPU instruction set while building from source

### ISSUE THREAD

**Issue by h6197627** [scipy/scipy#19120]
### Describe your issue.

Before Scipy 1.11.2 it was possible to build current CPU optimized  code with command
`python3 setup.py bdist_wheel build --cpu-baseline="native"`
In my case it added:
> extra options: '-msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f -mno-mmx -mavx512cd -mavx512vl -mavx512bw -mavx512dq -mavx512vnni -mavx512ifma -mavx512vbmi -mavx512vbmi2 -mavx512bitalg -mavx512vpopcntdq'

and:
> ########### EXT COMPILER OPTIMIZATION ###########
> INFO: Platform      : 
>   Architecture: x64
>   Compiler    : gcc
> 
> CPU baseline  : 
>   Requested   : 'native'
>   Enabled     : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
>   Flags       : -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f -mno-mmx -mavx512cd -mavx512vl -mavx512bw -mavx512dq -mavx512vnni -mavx512ifma -mavx512vbmi -mavx512vbmi2 -mavx512bitalg -mavx512vpopcntdq
>   Extra checks: AVX512F_REDUCE AVX512BW_MASK AVX512DQ_MASK
> 
> CPU dispatch  : 
>   Requested   : 'max -xop -fma4'
>   Enabled     : AVX512_KNL AVX512_KNM
>   Generated   : none
> INFO: 
> ########### CLIB COMPILER OPTIMIZATION ###########
> INFO: Platform      : 
>   Architecture: x64
>   Compiler    : gcc
> 
> CPU baseline  : 
>   Requested   : 'native'
>   Enabled     : SSE SSE2 SSE3 SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
>   Flags       : -msse -msse2 -msse3 -mssse3 -msse4.1 -mpopcnt -msse4.2 -mavx -mf16c -mfma -mavx2 -mavx512f -mno-mmx -mavx512cd -mavx512vl -mavx512bw -mavx512dq -mavx512vnni -mavx512ifma -mavx512vbmi -mavx512vbmi2 -mavx512bitalg -mavx512vpopcntdq
>   Extra checks: AVX512F_REDUCE AVX512BW_MASK AVX512DQ_MASK
> 
> CPU dispatch  : 
>   Requested   : 'max -xop -fma4'
>   Enabled     : AVX512_KNL AVX512_KNM
>   Generated   : none

However with new build system (and "no longer supported old method") there is no such flag and as far as I understand it can't be obtained from previously built NumPy build configuration as Meson downloads it's own NumPy copy during build process ignoring the fact that this dependency is already satisfied.

### Reproducing Code Example

```python
Build with command:
pip wheel . -Csetup-args=-Dblas=mkl-sdl -Csetup-args=-Dlapack=mkl-sdl --verbose
```

### Error message

```shell
Not recognizable --cpu-baseline option and no other (documented) ways to specify target CPU ISA
```

### SciPy/NumPy/Python version and system information

```shell
1.11.2 1.25.2 sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/intel/oneapi/mkl/latest/lib/pkgconfig/../../include
    lib directory: /opt/intel/oneapi/mkl/latest/lib/pkgconfig/../../lib/intel64
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: /usr/local/share/pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/intel/oneapi/mkl/latest/lib/pkgconfig/../../include
    lib directory: /opt/intel/oneapi/mkl/latest/lib/pkgconfig/../../lib/intel64
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: /usr/local/share/pkgconfig
    version: '2023.1'
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 11.4.0
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 11.4.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 11.4.0
  pythran:
    include directory: ../../../../../../tmp/pip-build-env-5q_e1f20/overlay/local/lib/python3.10/dist-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /usr/bin/python3
  version: '3.10'
```

**Comment by rgommers** [comment]
Hi @h6197627, you should be able to simply insert `-march=native` in `CFLAGS`/`CXXFLAGS`/`FFLAGS`. SciPy itself has no "dispatchable sources" (like numpy does have) that make use of the custom `--cpu-baseline`/`--cpu-dispatch` functionality from `numpy.distutils`.

Any kinds of optimization flag in environment variables like `CFLAGS` should work exactly like you'd expect for SciPy. 

I think that answers the question, so I'll close this issue. If you think things don't work as you'd expect, please comment with more details.
