### ISSUE TITLE
BUG: cannot import name '_get_dtype' from 'scipy.sparse.linalg.interface'

### ISSUE THREAD

**Issue by mirmusz** [scipy/scipy#19122]
### Describe your issue.

![image](https://github.com/scipy/scipy/assets/87347555/af6ac2c0-2469-455c-88a4-99c285de34d5)

Hello,
I'm quite new to Python. Currently, I'm trying to use the _get_dtype function from scipy and got this error. Can someone help me? I tried install-uninstall difference versions of other packages. It still happens.

### Reproducing Code Example

```python
import scipy.sparse.linalg.interface
from scipy.sparse.linalg.interface import _get_dtype
```

### Error message

```shell
cannot import name '_get_dtype' from 'scipy.sparse.linalg.interface'
```

### SciPy/NumPy/Python version and system information

```shell
python : 3.10.12
scipy : 1.11.2
numpy : 1.24.3
```

**Comment by lucascolley** [comment]
Hi @mirmusz , could I ask _why_ you are trying to import `_get_dtype`? The name starting with an `_` means that it is not a part of the public API of `scipy.sparse.linalg` (https://docs.scipy.org/doc/scipy/reference/sparse.linalg.html), so it is not intended for end-users (just internal SciPy use).

If you _really_ want to import this function, you can do so by using:
```
from scipy.sparse.linalg._interface import _get_dtype
```

However, this is not recommended as it could break in a future version of SciPy. There is no guarantee that private functions stay in the same place (or stay in the project at all).

If you just want to use the function in your own project, I recommend copying it to your own files:
```python
def _get_dtype(operators, dtypes=None):
    if dtypes is None:
        dtypes = []
    for obj in operators:
        if obj is not None and hasattr(obj, 'dtype'):
            dtypes.append(obj.dtype)
    return np.result_type(*dtypes)
```

Note: please keep in mind SciPy's license if using any of its code in your own work: https://github.com/scipy/scipy/blob/main/LICENSE.txt

**Comment by j-bowhay** [comment]
As @lucascolley this function is not designed for public consumption

**Comment by mirmusz** [comment]
Hi @lucascolley and @j-bowhay , thank you for the reply. Actually I'm using pylops-distributed for my study and the error is coming when using the package and the pylops-distributed is calling for the _get_dtype

Here is the example of the codes:
![image](https://github.com/scipy/scipy/assets/87347555/953a2b1e-a364-4420-b418-e84f48c9487f)

I'm not sure why.

**Comment by j-bowhay** [comment]
I would raise this as an issue with pylops

**Comment by mirmusz** [comment]
Noted that. Thanks.
