### ISSUE TITLE
BUG: Incorrect predecessor list in breadth_first_order

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [scipy/scipy#19133]
### Describe your issue.

I run `breadth_first_order` on a fully connected graph and it seems that I'm getting an incorrect predecessor array. At index 1 the `predecessor` and `order` array contain the same element which should be impossible

The adjacency list of the (bipartite!) graph is available here: https://gist.github.com/GuillaumeLeclerc/3a5feaa7c582526e0ffb29fb32bc71d2

### Reproducing Code Example

```python
import numpy as np
import scipy

num_A = 10
num_B = 50
graph = np.zeros((num_A + num_B, num_B + num_A), dtype=int)
for a, b in adjacency_list:
    graph[a, num_A + b] = 1
    graph[num_A + b, a] = 1

num_components, labels = scipy.sparse.csgraph.connected_components(graph)
print(num_components)
order = scipy.sparse.csgraph.breadth_first_order(graph, 0)
print(order[0][1]) 
print(order[1][1])
```

### Error message

```shell
1
11
11  # Same is the previous one
```
The correct answer should be `0` here as there is indeed an edge between node 0 and 11.

### SciPy/NumPy/Python version and system information

```shell
1.10.1 1.23.5 sys.version_info(major=3, minor=10, micro=9, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: cmake
    found: true
    include directory: unknown
    lib directory: unknown
    name: OpenBLAS
    openblas configuration: unknown
    pc file directory: unknown
    version: 0.3.18
  lapack:
    detection method: cmake
    found: true
    include directory: unknown
    lib directory: unknown
    name: OpenBLAS
    openblas configuration: unknown
    pc file directory: unknown
    version: 0.3.18
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.33
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: /tmp/pip-build-env-xob7rtip/overlay/lib/python3.10/site-packages/pythran
    version: 0.12.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp310-cp310/bin/python
  version: '3.10'
```

**Comment by scidam** [comment]
I don't think this is a bug. If you read the [docs ](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csgraph.breadth_first_order.html), you can find that 

> Returned only if return_predecessors is True. The length-N list of predecessors of each node in a breadth-first tree. If node i is in the tree, then its parent is given by predecessors[i]. If node i is not in the tree (and for the parent node) then predecessors[i] = -9999.

So, in the example above you have i-th node (i=11), and you should use `print(order[1][11])` instead of `print(order[1][1])`; You can find that `order[1][11]` is `0` as expected.

**Comment by GuillaumeLeclerc** [comment]
My bad, I assumed the order of the two arrays way identical
