### ISSUE TITLE
DOC: stats: alternative loc-scale handling in levy_stable

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#19140]
### Describe your issue.

This problem was reported as a [question on stackoverflow](https://stackoverflow.com/questions/76982144/scale-parameter-is-producing-a-displacement-in-scipy-distribution).

With the default parametrization `S1`, `levy_stable` does not handle `loc` and `scale` correctly.  We say

> Specifically, levy_stable.pdf(x, alpha, beta, loc, scale) is identically equivalent to levy_stable.pdf(y, alpha, beta) / scale with y = (x - loc) / scale.

(We say the same for all the continuous univariate distributions.)

But this property fails for `levy_stable`.  For example, the graphs in the following plot (generated by the script below) should coincide, but they do not.

![levy_stable_plot](https://github.com/scipy/scipy/assets/321463/fefaec9c-4bb5-4143-8d7e-e1fc012cc0dc)

### Reproducing Code Example

```python
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import levy_stable


alpha = 1
beta = 1
loc = 1
scale = 3

# Uncomment the following to see the correct behavior.
# levy_stable.parameterization = 'S0'

x = np.linspace(-5, 10, 1000)
y1 = levy_stable.pdf(x, alpha, beta, loc=loc, scale=scale)
y2 = levy_stable.pdf((x-loc)/scale, alpha, beta)/scale

plt.plot(x, y1, '--', linewidth=1,
         label='pdf(x, alpha, beta, loc=loc, scale=scale)')
plt.plot(x, y2, alpha=0.4, linewidth=3,
         label='pdf((x-loc)/scale, alpha, beta)/scale')

plt.legend(shadow=True, framealpha=1)
plt.grid(alpha=0.25)
plt.savefig('levy_stable_plot.png')
```

### Error message

```shell
No error message.
```

### SciPy/NumPy/Python version and system information

```shell
1.11.2 1.25.2 sys.version_info(major=3, minor=11, micro=1, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 14.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 14.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 12.1.0
  pythran:
    include directory: ../../pip-build-env-pynhp79a/overlay/lib/python3.11/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cibw-run-b55l7izd/cp311-macosx_arm64/build/venv/bin/python
  version: '3.11'
```
```

**Comment by ev-br** [comment]
Somehow `levy_stable_gen` deliberately overrides the `pdf` method ? This is ...unorthodox

```
    @inherit_docstring_from(rv_continuous)
    def pdf(self, x, *args, **kwds):
        # override base class version to correct
        # location for S1 parameterization
        if self._parameterization() == "S0":
            return super().pdf(x, *args, **kwds)
        elif self._parameterization() == "S1":
```

**Comment by dschmitz89** [comment]
Changing to `_pdf` as usually fixes the issue reported here but leads to a test failure somewhere else: https://github.com/scipy/scipy/blob/2d27cf72806113e64f3eb4f3831dfd46bda1646c/scipy/stats/tests/test_distributions.py#L5384

**Comment by lutefiskhotdish** [comment]
I think the problem is not with loc-scale handling, but with the claim that 

> Specifically, levy_stable.pdf(x, alpha, beta, loc, scale) is identically equivalent to levy_stable.pdf(y, alpha, beta) / scale with y = (x - loc) / scale.

This relationship does not hold for the `S1` parameterization.  In the `S1` parameterisation, when `alpha = 1`, the relationship of a rescaled distribution `X` to the original `Z` is `X = scale * Z + loc + beta * 2 / pi * scale * log(scale)`.  See Definition 1.8 in [Stable Distributions](https://edspace.american.edu/jpnolan/wp-content/uploads/sites/1720/2020/09/Chap1.pdf).

We can produce overlapping density curves using the default (`S1`) parameterization if we account for the relationship between loc and scale parameters in this parameterization.

![levy_stable_plot_resolved](https://github.com/scipy/scipy/assets/87871567/660d5e76-02e7-4b64-9fbb-b643eef403c9)

This chart is obtained by inserting the following into the original reproducing code above:
```
loc_S1 = loc + beta*2/np.pi*scale*np.log(scale)
y3 = levy_stable.pdf((x - loc_S1)/scale, alpha, beta)/scale
plt.plot(x, y3, alpha=0.4, linewidth=3,
         label='pdf((x-loc_S1)/scale, alpha, beta)/scale')
```

**Comment by mdhaber** [comment]
Thanks @lutefisk. I expected this was due to the alternative parameterization but wasn't sure. Would you be willing to adjust the documentation to make this more clear?

**Comment by lutefiskhotdish** [comment]
@mdhaber I'm happy to look at the documentation, though if anybody else actually knows what they're doing they needn't hold back on my account.

**Comment by mdhaber** [comment]
At https://github.com/scipy/scipy/blob/686422c4f0a71be1b4258309590fd3e9de102e18/scipy/stats/_levy_stable/__init__.py#L634-L1121, the standard bit about `loc`/`scale` is injected by ` %(after_notes)s`. I think that needs to be replaced.

**Comment by lutefiskhotdish** [comment]
Hmm.

> This relationship does not hold for the S1 parameterization. In the S1 parameterisation, when alpha = 1, the relationship of a rescaled distribution X to the original Z is X = scale * Z + loc + beta * 2 / pi * scale * log(scale). See Definition 1.8 in [Stable Distributions](https://edspace.american.edu/jpnolan/wp-content/uploads/sites/1720/2020/09/Chap1.pdf).

If that line of reasoning is right, then I would expect to see a deviation from simple rescaling in the `S0` parameterization when `alpha` is not 1, based on Definition 1.7.  But rescaling seems to work fine in the `S0` parameterization, for a variety of alpha and beta values.  So there is something I don't yet understand about the parameterization.

**Comment by mdhaber** [comment]
You won't need to build SciPy locally for that. Just be sure to include `[skip actions] [skip cirrus]` in your commit message so that only the docs CI service runs.
