### ISSUE TITLE
BUG: asfarray is removed from numpy

### ISSUE THREAD

**Issue by lithomas1** [scipy/scipy#19147]
### Describe your issue.

We at pandas are using numpy nightlies and also scipy nightlies in our tests, and it seems that the removal of asfarray is causing an import error in scipy.

However, usage of asfarray hasn't been removed in scipy yet.

See e.g. these lines
https://github.com/scipy/scipy/blame/8bb5e31784573f56a8de8362c15e61d66225f15b/scipy/optimize/_optimize.py#L44-L46

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version and system information

```shell
python 3.11
numpy and scipy from latest nightly wheels
```

**Comment by lucascolley** [comment]
This is being addressed in #19143.
