### ISSUE TITLE
BUG: Source archives have bogus timestamps

### ISSUE THREAD

**Issue by mathstuf** [scipy/scipy#19158]
### Describe your issue.

The timestamps in the source archives from PyPI do not have valid timestamps and extract as `Dec 31  1969 meson_options.txt`. When making patches against this, `git` reads the `1969` date as "not a valid Unix timestamp" and thinks that it is a new file patch (I'll file an issue with Git upstream about this separately).

### Reproducing Code Example

```python
% curl https://files.pythonhosted.org/packages/9c/ef/87a5565907645998d7c62e76b84b0ca9f0b7c25cd433f5617a968051cec3/scipy-1.11.2.tar.gz | tar xzf -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 53.4M  100 53.4M    0     0  1930k      0  0:00:28  0:00:28 --:--:-- 1763k
% ls -l scipy-1.11.2
total 168
drwxr-xr-x.  3 user user    63 Aug 29 16:50 benchmarks
-rw-r--r--.  1 user user  1188 Dec 31  1969 CITATION.bib
-rw-r--r--.  1 user user  1150 Dec 31  1969 CONTRIBUTING.rst
-rw-r--r--.  1 user user 49632 Dec 31  1969 dev.py
drwxr-xr-x.  3 user user    53 Aug 29 16:50 doc
-rw-r--r--.  1 user user   236 Dec 31  1969 doc_requirements.txt
-rw-r--r--.  1 user user 11435 Dec 31  1969 LICENSES_bundled.txt
-rw-r--r--.  1 user user  1536 Dec 31  1969 LICENSE.txt
-rw-r--r--.  1 user user  5623 Dec 31  1969 meson.build
-rw-r--r--.  1 user user   759 Dec 31  1969 meson_options.txt
-rw-r--r--.  1 user user 12810 Dec 31  1969 mypy.ini
-rw-r--r--.  1 user user   172 Dec 31  1969 mypy_requirements.txt
-rw-r--r--.  1 user user  7852 Dec 31  1969 PKG-INFO
-rw-r--r--.  1 user user  6684 Dec 31  1969 pyproject.toml
-rw-r--r--.  1 user user   745 Dec 31  1969 pytest.ini
-rw-r--r--.  1 user user  3436 Dec 31  1969 README.rst
drwxr-xr-x. 22 user user  4096 Aug 29 16:51 scipy
-rwxr-xr-x.  1 user user 20805 Dec 31  1969 _setup.py
drwxr-xr-x.  3 user user  4096 Aug 29 16:51 tools
```

### Error message

```shell
% cp -a scipy-1.11.2{,.use-blas-lapack}
% sed -i -e "1s/value: 'openblas'/value: 'blas'/;3s/value: 'openblas'/value: 'lapack'/" scipy-1.11.2.use-blas-lapack/meson_options.txt
% diff -Nr -U5 scipy-1.11.2 scipy-1.11.2.use-blas-lapack | git -C scipy-1.11.2 --git-dir= apply -p1 /dev/stdin
error: new file meson_options.txt depends on old contents
```

### SciPy/NumPy/Python version and system information

```shell
1.11.2

Fedora 38 host; both Git 2.41.0 and `git version 2.42.0.51.g5dc72c0fbc.dirty` (`dirty` for the debugging output I added).
```

**Comment by mathstuf** [comment]
Actually, it appears as though this timestamp is used for `/dev/null` and "file does not exist" purposes explicitly in the Git source code. I think real timestamps should be used for all files (not sure why only a few end up with such timestamps though).

**Comment by tylerjereddy** [comment]
I started looking into this, and my brain started melting after reading https://github.com/mesonbuild/meson-python/issues/450 and https://github.com/mesonbuild/meson-python/pull/452. But perhaps those references will give you an idea of the debate/proposals in the ecosystem related to this?

To be fair, it looks like those weird timestamps have some relationship to the concept of "reproducible builds" and hash stability? Anyway, if you aren't already involved in those discussions I linked, perhaps chime in there as well?

I'll cc @rgommers, who is already actively in those discussions.

**Comment by rgommers** [comment]
Indeed. I'll mark this as an upstream bug. It'll be solved for scipy 1.12.0 when we upgrade to a new meson-python release. I'll leave this open until we've upgraded to that new (to be made soon) release.

**Comment by mathstuf** [comment]
Thanks! I read through the discussion and things still seem to be in the works. I didn't see any discussion of an ultimate fallback timestamp, so I added a summary of what I found here to the issue.

**Comment by rgommers** [comment]
`meson-python` 0.14.0 was released, which addresses this problem.

**Comment by tylerjereddy** [comment]
Looks like we now get the timestamp of the most recent branch commit from a quick check with newer `meson-python`.
