### ISSUE TITLE
Build warnings from cython

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#19151]
Building cython extensions from source generates a wall of warnings

```
[7/8] Compiling C object scipy/linalg/_matfuncs_expm.cpython-310-x86_64-linux-gnu.so.p/meson-generated__matfuncs_expm.c.o
scipy/linalg/_matfuncs_expm.cpython-310-x86_64-linux-gnu.so.p/_matfuncs_expm.c: In function '__Pyx_Import':
scipy/linalg/_matfuncs_expm.cpython-310-x86_64-linux-gnu.so.p/_matfuncs_expm.c:48372:21: warning: the comparison will always evaluate as 'true' for the pointer operand in '(char *)"scipy.linalg._matfuncs_expm" + 5' must not be NULL [-Waddress]
48372 |             if ((1) && (strchr(__Pyx_MODULE_NAME, '.'))) {
      |                     ^~
[8/8] Linking target scipy/linalg/_matfuncs_expm.cpython-310-x86_64-linux-gnu.so
Build OK
```

This is for a recent cython:

```
$ cython --version
Cython version 3.0.2
```

**Comment by ev-br** [comment]
Maybe @da-woods or @matusvalo could weight in on these?

**Comment by da-woods** [comment]
But definitely file a Cython bug. The C compiler version you're using is probably the most relevant information. And we can see if it can be fixed

**Comment by ev-br** [comment]
Thanks @da-woods , filed  https://github.com/cython/cython/issues/5663

**Comment by rgommers** [comment]
The fix for the warning in the issue description will be present in Cython 3.0.3. Together with other gh-19170 we should be down to a reasonable number of warnings - I'm aiming to get it back down to zero in the near future.

**Comment by lucascolley** [comment]
Looks to me like this was closed by gh-19714 - there may be a few warnings from Cython still there so feel free to reopen for those if so, but the wall is gone (it's hard for me to tell as I have a lot of warnings still, see gh-19734 and gh-19736

**Comment by rgommers** [comment]
Yes indeed, this is fixed.
