### ISSUE TITLE
BUG: Generating Sparse Matrices requires equivalent dense matrix memory

### ISSUE THREAD

**Issue by khaled3ttia** [scipy/scipy#19159]
### Describe your issue.

Hello, 

I've been trying to generate large sparse matrices. More specifically, the required shape of the matrix is (2097152, 2097152), but the density is 0.00002. So, the expected number of non-zeros is  8796093022208.
Assuming using the biggest structure (COO) with all `rows`, `cols` and `data` lists storing 8-byte numbers. So, the total storage requirement = 8796093022208 nnz x 3 arrays x 8 bytes = 2111062,32532992 bytes which is  1.96608 GB
However, when I try to generate a random sparse matrix with the previously mentioned parameters, SciPy initially requires the full storage as if it was a dense matrix, with no regard to the `density`. So, it tries to allocate memory for a shape of 2097152 x 2097152 (32 TiB), which eventually leads to out of memory error. 

Is there anyway to workaround this issue, so that I can generate such sparse matrices? Thank you!

### Reproducing Code Example

```python
import numpy as np
import scipy.sparse as sp

out = sp.random(2097152, 2097152, 0.00002)
```

### Error message

```shell
Traceback (most recent call last):
  File "/home/khaled/sample.py", line 5, in <module>
    out = sp.random(2097152, 2097152, 0.00002)
  File "/home/khaled/.local/lib/python3.9/site-packages/scipy/sparse/_construct.py", line 877, in random
    ind = random_state.choice(mn, size=k, replace=False)
  File "mtrand.pyx", line 991, in numpy.random.mtrand.RandomState.choice
  File "mtrand.pyx", line 4630, in numpy.random.mtrand.RandomState.permutation
numpy.core._exceptions.MemoryError: Unable to allocate 32.0 TiB for an array with shape (4398046511104,) and data type int64
```

### SciPy/NumPy/Python version and system information

```shell
1.9.1 1.23.3 sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)

lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
```

**Comment by perimosocordiae** [comment]
This is a known issue (see gh-9699) that thankfully has a reasonably simple workaround. If you pass `random_state=np.random.default_rng()`, then the memory issues will go away.

We're working on making this behavior the default (see gh-18592), so eventually this will do the fast thing automatically.
