### ISSUE TITLE
jacobian matrix in scipy.optimize.least_squares

### ISSUE THREAD

**Issue by rahatN-tech** [scipy/scipy#19160]
can i find whole jacobian matrix of order (mXn) in scipy.optimize as in result we are getting only an array. But i need to find the whole matrix, is there any other way in least square optimization

**Comment by andyfaff** [comment]
It's not clear what you're missing. The `OptimizeResult` object that is returned from `least_squares` has a `jac` attribute, which contains the Jacobian of the system. From the documentation:

> Modified Jacobian matrix at the solution, in the sense that J^T J is a Gauss-Newton approximation of the Hessian of the cost function. The type is the same as the one used by the algorithm.

Thus, you can also estimate the Hessian from `OptimizeResult.jac` and from there obtain the covariance matrix.

**Comment by mdhaber** [comment]
I'd echo @andyfaff's comments. If an issue remains, we can reopen this, but the Jacobian is already in the `jac` attribute.

**Comment by rahatN-tech** [comment]
The jac in the results is an array of length equal to the no of variables.
۔.
How can I get mxn jacobian
matrix

**Comment by mdhaber** [comment]
Here is an example from the documentation in which the result object's `jac` attribute has shape `(15, 3)`, where 15 is the number of outputs of `fun` and 3 is the number of variables.

<details>

```
import numpy as np
from numpy.random import default_rng
from scipy.optimize import least_squares

rng = default_rng()
def gen_data(t, a, b, c, noise=0., n_outliers=0, seed=None):
    rng = default_rng(seed)

    y = a + b * np.exp(t * c)

    error = noise * rng.standard_normal(t.size)
    outliers = rng.integers(0, t.size, n_outliers)
    error[outliers] *= 10

    return y + error

a = 0.5
b = 2.0
c = -1
t_min = 0
t_max = 10
n_points = 15

t_train = np.linspace(t_min, t_max, n_points)
y_train = gen_data(t_train, a, b, c, noise=0.1, n_outliers=3)

def fun(x, t, y):
    return x[0] + x[1] * np.exp(x[2] * t) - y

x0 = np.array([1.0, 1.0, 0.0])

res_lsq = least_squares(fun, x0, args=(t_train, y_train), method='lm')
res_lsq.jac.shape  # (15, 3)
```

</details>

If this is not what you are observing, please provide a minimum reproducible example that runs when it is copy-pasted into a Python prompt.

**Comment by rahatN-tech** [comment]
Thanks alot, I'll check it out and will get back to you

**Comment by rahatN-tech** [comment]
i am not providing any method in the least_squares and the 'lm' method is
for unconstrained optimization..and i have an objective function with
'bounds'.

i am new to scipy..so plz excuse if i cant frame my question in a more
comprehensive way.

i require a mxn jacobian matrix after least_square optimization which i
couldnt get..
plz guide
