### ISSUE TITLE
BUG: build graph non-determinism

### ISSUE THREAD

**Issue by mathstuf** [scipy/scipy#19167]
### Describe your issue.

It seems that some Cython code needs more dependencies specified. Namely, some Cython generation requires `from scipy.special cimport cython_special` to work. While trying to `ninja -k0` in order to `ninja -j1` to isolate the error message, the problem went away. This tells me that dependencies probably just need better ordered.

### Reproducing Code Example

```python
N/A
```

### Error message

```shell
[674/845] Generating 'scipy/special/_ellip_harm_2.cpython-39-darwin.so.p/_ellip_harm_2.c'
FAILED: scipy/special/_ellip_harm_2.cpython-39-darwin.so.p/_ellip_harm_2.c
/Users/ben.boeckel/code/superbuild/build/install/bin/cython -3 --fast-fail --output-file scipy/special/_ellip_harm_2.cpython-39-darwin.so.p/_ellip_harm_2.c --include-dir . ../../scipy/special/_ellip_harm_2.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from scipy.special cimport cython_special
^
------------------------------------------------------------
```

### SciPy/NumPy/Python version and system information

```shell
SciPy 1.11.2
MesonPy 0.13.2
Meson 1.2.1
Cython 3.0.0
```

**Comment by rgommers** [comment]
Thanks for the report. 0.13.2 is the `meson-python` version. Can you add the `meson` and `Cython` versions? This should be automatic, but it's very well possible that we're missing an explicit dependency here and that triggering the resulting problem is difficult.

**Comment by mathstuf** [comment]
So I tracked it down to these two rules which should reproduce anywhere (may need a `ninja -t clean` first depending on how you get your builddir and hacking mesonpy (see Bartpab/meson-py#4) to get access to such a build directory):

```
% <generate meson build>
% ninja scipy/special/_ellip_harm_2.cpython-39-darwin.so.p/_ellip_harm_2.c
<fails as above>
% ninja scipy/special/cython_special.cpython-39-darwin.so
<works>
% ninja scipy/special/_ellip_harm_2.cpython-39-darwin.so.p/_ellip_harm_2.c
<now works>
```

**Comment by rgommers** [comment]
Thanks! Yes, this is a clear bug. I've had on my wish/idea list for a long time to build every target separately to smoke out issues like these. 

Here's how I reproduce it, from a clean repo:
```
$ meson setup build  # configure the build dir
$ # find an exact target name:
$ ninja -C build -t targets depth 0 | rg ".*ellip_harm.*.so"
$ # try to build only that target:
$ ninja -C build scipy/special/_ellip_harm_2.cpython-310-x86_64-linux-gnu.so
ninja: Entering directory `build'
[1/3] Generating 'scipy/special/_ellip_harm_2.cpython-310-x86_64-linux-gnu.so.p/_ellip_harm_2.c'.
FAILED: scipy/special/_ellip_harm_2.cpython-310-x86_64-linux-gnu.so.p/_ellip_harm_2.c 
/home/rgommers/mambaforge/envs/scipy-dev/bin/cython -3 --fast-fail --output-file scipy/special/_ellip_harm_2.cpython-310-x86_64-linux-gnu.so.p/_ellip_harm_2.c --include-dir . ../scipy/special/_ellip_harm_2.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from scipy.special cimport cython_special
^
------------------------------------------------------------

/home/rgommers/code/scipy/scipy/special.pxd:1:0: 'scipy/special/cython_special.pxd' not found
ninja: build stopped: subcommand failed.
```

Meson is good at automatically adding dependencies, but it will miss the ones that come through a `custom_target` where we use a Python script to generate Cython source files which are then needed for a next target.

**Comment by mathstuf** [comment]
I'm unsure of how many places need this added, but I suppose grepping `pyx` files for `scipy` imports would be a good guide.

**Comment by rgommers** [comment]
I think it's only the places that use the output of a `_generate_pyx.py` script - that's easy to grep for.
