### ISSUE TITLE
BUG: LinearOperator dtype determination broken

### ISSUE THREAD

**Issue by lobpcg** [scipy/scipy#19207]
### Describe your issue.

Calling the `LinearOperator` without specifying the dtype activates the dtype determination in ```scipy/sparse/linalg/_interface.py", line 182, in _init_dtype
        self.dtype = np.asarray(self.matvec(v)).dtype```
that looks strange. 

In `/scipy/sparse/linalg/_interface.py` the code in question is
```
    def _init_dtype(self):
        """Called from subclasses at the end of the __init__ routine.
        """
        if self.dtype is None:
            v = np.zeros(self.shape[-1])
            self.dtype = np.asarray(self.matvec(v)).dtype
```

 `v.dtype` is `np.float64` so `self.dtype` will be at least  `np.float64`, like in the docstring example:
```
    >>> import numpy as np
    >>> from scipy.sparse.linalg import LinearOperator
    >>> def mv(v):
    ...     return np.array([2*v[0], 3*v[1]])
    ...
    >>> A = LinearOperator((2,2), matvec=mv)
    >>> A
    <2x2 _CustomLinearOperator with dtype=float64>
```
even though it only multiplies by `int`, so should not   `self.dtype` be `int` in this example?
Naively, is not `self.dtype` suppose to match the `dtype` of the underlying matrix implicitly used for the product? Maybe use `v = np.zeros(self.shape[-1], type=np.int8)` i.e. with the "smallest" `dtype`?

Need to invoke `matmat` in `dtype` determination together with `matvec` and pickup the largest if both   `matmat` and `matvec` are provided; see https://github.com/scipy/scipy/issues/19213

**Comment by rkern** [comment]
The provided `matvec` must correctly handle the case when the input is `(n,)`-shaped. This is a documented requirement (see the [`Notes`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.LinearOperator.html)). The `A_matmat` function here is an invalid value for the `matvec` argument.

Do you have a reproducer with a valid `matvec` implementation?

**Comment by lobpcg** [comment]
> The provided `matvec` must correctly handle the case when the input is `(n,)`-shaped. This is a documented requirement (see the [`Notes`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.LinearOperator.html)). The `A_matmat` function here is an invalid value for the `matvec` argument.
> 
> Do you have a reproducer with a valid `matvec` implementation?

I have forgotten that, thanks. But why is this a requirement? It prevents a valid matmat to be used also as matvec, which is illogical.

Another strange requirement is that matvec is mandatory, i.e. cannot be deduced from matmat. Logically, only one of them matvec or matmat should be mandated.

**Comment by rkern** [comment]
Yes, `_CustomLinearOperator` imposes extra requirements that don't exist for `LinearOperator`, which indeed can infer `matvec` from `matmat` and vice versa. Probably just to simplify the logic. A contribution would be welcome in that vein, but this doesn't have anything to do with `dtype` determination.

**Comment by lobpcg** [comment]
In in `scipy/sparse/linalg/_interface.py`
the code
```
v = np.zeros(self.shape[-1])
 self.dtype = np.asarray(self.matvec(v)).dtype
```
is replaced with
```
v = np.zeros((self.shape[-1], 1))
self.dtype = np.asarray(self.matmat(v)).dtype
```
that could solve the trouble in https://github.com/scipy/scipy/issues/19212

But my testing it in https://github.com/scipy/scipy/pull/19209/commits/89f5fe5e5d6f6b1ef3b93f6b087f85caa15df38e gives multiple errors from tests in `scipy/optimize/` that probably are not written compliant to generate valid `matmat` from `matvec`? The errors are like:
```
E   ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)```
and `E   ValueError: cannot reshape array of size 121 into shape (11,1)`
I do not know how to deal with this sudden can of worms.

**Comment by rkern** [comment]
It is indeed possible that those `LinearOperator` `matvec`s were written incorrectly and assumed they are only passed `(n,)`-shaped arrays (which they were, previously) and not also `(n, 1)` shaped arrays, which they should. Those are certainly worth fixing, in their own right, but not to enable you to change to using `.matmat()` in the dtype-determination. That code should be left alone.
