### ISSUE TITLE
ENH: LinearOperator matvec should correctly handle the case when the input is (n,1)-shaped

### ISSUE THREAD

**Issue by lobpcg** [scipy/scipy#19212]
### Is your feature request related to a problem? Please describe.

The provided `matvec` must correctly handle the case when the input is (n,)-shaped. This is a documented requirement (see the [Notes](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.LinearOperator.html)). 
 It prevents a valid `matmat` to be used also as `matvec`, which is illogical.

### Describe the solution you'd like.

Require that `matvec` must correctly handle the case when the input is `(n,)`-shaped ONLY if `matmat` is not provided. Or better yet, check for the shape of the vector input to matvec and reshape `(n,1)` into `(n,)` if needed. At least one spot where it is needed is in `/scipy/sparse/linalg/_interface.py` the code in question is
```
    def _init_dtype(self):
        """Called from subclasses at the end of the __init__ routine.
        """
        if self.dtype is None:
            v = np.zeros(self.shape[-1])
            self.dtype = np.asarray(self.matvec(v)).dtype
```

### Describe alternatives you've considered.

The requirement puts more burden on the user while it could be easily handled internally.

### Additional context (e.g. screenshots, GIFs)

Originally reported at https://github.com/scipy/scipy/issues/19207, but moved here.

**Comment by rkern** [comment]
`LinearOperator` itself does not require a `matvec`. It already has the internal logic to infer one from the other. Rather, the only constraint is that `_CustomLinearOperator` does not also implement this and requires a `matvec`.

I'm going to close this because the stated enhancement request is not the direction we need to go to solve the problem.

**Comment by rkern** [comment]
#19213 is the right description, with my clarification as to exactly where the change needs to be made.

**Comment by lobpcg** [comment]
These two are separate issues, no?

**Comment by rkern** [comment]
If you solve that one, this one is unnecessary. There is no need to make the `matvec=` argument accept `matmat` functions if one can construct `LinearOperator`s with just a `matmat=` argument.

**Comment by lobpcg** [comment]
I disagree - this issue is unrelated to `matmat`. Even if only `matvec=` is set, I still see no point to restrict its input to `(n,)`-shaped ONLY and not allow `(n,1)`

**Comment by rkern** [comment]
Each `matvec` implementation must handle both. If you want to only deal with proper matrices (i.e. by implementing only a `matmat`), that's fine! The logic to infer `matvec` behavior from a `matmat` implementation [already exists](https://github.com/scipy/scipy/blob/main/scipy/sparse/linalg/_interface.py#L193-L203). You just need the ability to construct a `LinearOperator` by providing a `matmat=` argument, and that's covered by #19213 .
