### ISSUE TITLE
BUG: io: scipy.io.loadmat error message recommend use of function from deprecated namespace

### ISSUE THREAD

**Issue by j-bowhay** [scipy/scipy#19223]
Originally reported by @ldevillez in #19211

> When using `scipy.io.loadmat` we can have the following message:
> 
> ```
> MatReadWarning: Duplicate variable name XXXX in stream - replacing previous with new
> Consider mio5.varmats_from_mat to split file into single variable files
> ```
> 
> If we use `scipy.io.matlab.mio5.varmats_from_mat` we then get:
> 
> ```
> DeprecationWarning: Please use `varmats_from_mat` from the `scipy.io.matlab` namespace, the `scipy.io.matlab.mio5` namespace is deprecated.
> ```
> 
> If we use `scipy.io.matlab.varmats_from_mat`we have:
> 
> ```
> AttributeError: module 'scipy.io.matlab' has no attribute 'varmats_from_mat'
> ```

Either this function needs exposing in the `scipy.io.matlab` namespace or as suggested by @h-vetinari:

> My preference would be to fix `scipy.io.loadmat` (or add an option), so that
> 
> ```
> MatReadWarning: Duplicate variable name XXXX in stream - replacing previous with new
> Consider mio5.varmats_from_mat to split file into single variable files
> ```
> 
> is not necessary in the first place.

**Comment by j-bowhay** [comment]
@matthew-brett maybe you have an opinion on whether `varmats_from_mat` should be exposed into the `scipy.io.matlab` namespace?

**Comment by h-vetinari** [comment]
1.13 is released already, bumping the milestone

**Comment by h-vetinari** [comment]
> I think we should go ahead with exposing this in `io.matlab` for next release if a fix doesn't look inbound.

@lucascolley @j-bowhay anyone up for tackling this before we branch in December? :)
