### ISSUE TITLE
Nightly wheels built on CirrusCI are not uploaded to scientific-python-nightly-wheels

### ISSUE THREAD

**Issue by lesteve** [scipy/scipy#19221]
"It seems like arm wheels have not been uploaded to [scientific-python-nightly-wheels](
https://anaconda.org/scientific-python-nightly-wheels/scipy/files) for a while. The latest upload of `macosx_12_0_arm64` and the `manylinux_2_17_aarch64` wheels are 1 month and 13 days old. 

This is an issue because trying to use them with the numpy nightly wheel will give the error `ImportError: cannot import name 'ComplexWarning' from 'numpy'`.

Looking at a recent [Cirrus run](https://cirrus-ci.com/task/4614845278978048), the wheels are built but the upload step does seem to upload anything. The fact that there is no output and that the upload step takes one second probably means that the `IS_SCHEDULED_DISPATCH` is not `true` in the following condition:

https://github.com/scipy/scipy/blob/d781501cc7b150a152e3f9bcfe84c10fcb57f486/ci/cirrus_wheels.yml#L132

I said "nightly" but they may be less often e.g. every one or two weeks according to https://github.com/scipy/scipy/pull/18985. In any case the upload step seems to have an issue.

**Comment by andyfaff** [comment]
Thank you for opening this issue. I also noticed and looked into this today. I don't think there is an issue apart from the frequency we run the wheel build at.

The build frequency was drastically reduced because CirrusCI now has a cap in how many free resources you can use in a month. When the scheduled run last triggered, the builds failed because of an issue that's now been fixed, as evidenced by the recent non-cron runs that worked.  Unfortunately the wheels are only designed to upload on a successful cron run.

We could increase the frequency of the cron run, but it would have a monetary impact because we'd have to pay for CI resources.

**Comment by andyfaff** [comment]
The Cron job is currently scheduled to run once a month on the third Saturday. Building the full wheelset takes a lot of resources, especially on macOS, which is why the frequency is so low.

**Comment by lesteve** [comment]
OK makes sense, thanks a lot for looking into it!

Given that the third Saturday of September is the 16th, which is in 4 days, it is completely fine waiting for the cron job to run.

I guess the build I was looking at had the wheels triggered on `main` because `[wheel build]` was in the commit message, which as you say is enough to make the wheel build not enough to make them upload.

**Comment by lesteve** [comment]
For completeness, it looks like the monthly [Cron invocation](https://cirrus-ci.com/task/5091309355008000) did not succeed because of:
FAILED_PRECONDITION: Monthly free compute limit exceeded

I am going to reopen this issue to make it more easily discoverable.

I guess the next opportunity of wheels being uploaded will be the third Saturday of October?

**Comment by andyfaff** [comment]
Yeah, out free cirrus credits have run out. It probably makes sense to make the Cron run on the first day of the month, to make sure the credits haven't run out. Then again, there may be a possibility of credits being donated via numfocus. @rgommers

**Comment by rgommers** [comment]
Good idea to run it on the first day of the month.

I'll try to deal with credits this week - I wanted to see how buying them works out for numpy first. Which is pretty good so far - we used 4 credits (= $4) in 6 days so far. A full set of wheel builds seems to be about $1. The one hiccup so far has been that their Settings page has been down for over 24 hours, shortly after they seem to have started to enforce credit limits more tightly.
