### ISSUE TITLE
Doc build fails with Python 3.11

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#19228]
Attempting to build the docs (e.g. `python dev.py doc`) fails with Python 3.11, because of an issue with a `myst-nb` Sphinx extension; see https://github.com/executablebooks/MyST-NB/issues/540.

I suspect this issue has been reported or discussed before, but I can't find anything.  Is no one out there building the docs with Python 3.11?

**Comment by tylerjereddy** [comment]
Yeah, Pamphile and I ran into this `N` times in Seattle a few months ago--I think we just switched back to an older Python to avoid dealing with the mess at the time.

**Comment by melissawm** [comment]
I just built the docs with Python 3.11.6 and myst-nb 0.17.6 (from conda-forge) with no issue so I assume this was solved upstream (as noted in the myst-nb issue). I am going to close this as resolve, feel free to reopen if necessary.

**Comment by WarrenWeckesser** [comment]
Thanks for checking @melissawm.

@choldgraf, @agoose77: Will the latest myst-nb be released on PyPI?.  The latest version there is 0.17.2.

**Comment by agoose77** [comment]
I'll get to this in the next 24hrs
