### ISSUE TITLE
stats.t.fit() with own optimizer (e.g. to use Nelder-Mead) fails due to "returning result too late"

### ISSUE THREAD

**Issue by kraxli** [scipy/scipy#19225]
### Describe your issue.

Using an own `optimizer` in e.g. `stats.t.fit`, the result "object" (`OptimizeResult`) is not returned but further passed to the optimizer as independent variable resulting in an `KeyError`. 

Specifically, the "object" `OptimizeResult`  is passed to the function `_unpack_loc_scale()` like the variables in previous optimization steps.  But `_unpack_loc_scale()`  takes tuples or lists but not final result objects (`OptimizeResult` ).

![scipy_optim_error](https://github.com/scipy/scipy/assets/8371948/acdf5733-2dff-4387-82d3-0c8b6352f126)

Additionally, the starting value `x0` is not taken advantage of: 

![scipy_optim_x0_not_respeted](https://github.com/scipy/scipy/assets/8371948/cedf263c-81a1-4b7d-87d2-d34b0d2a7919)

### Reproducing Code Example

```python
import numpy as np
from scipy import stats as stats
from scipy.optimize import minimize

num_sim = 1000
degrees_freedom = 3
t_loc = 0
t_scale = 1

np.random.seed(42)
draws_t_dist = stats.distributions.t.rvs(degrees_freedom, t_loc, t_scale, size=num_sim)

# Nelder-Mead
def optimizer_NM(func, x0=3, args=(0, 1), disp=False):
    return minimize(func, x0, args, method="nelder-mead")


stats.t.fit(draws_t_dist, method="MLE", optimizer=optimizer_NM)
```

### Error message

```shell
`Thread stopped due to exception of type KeyError`
```

### SciPy/NumPy/Python version and system information

```shell
1.11.2 1.25.2 sys.version_info(major=3, minor=11, micro=1, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-tshsyzfz/overlay/lib/python3.11/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp311-cp311/bin/python
  version: '3.11'
```

**Comment by mdhaber** [comment]
This is definitely a shortcoming, although I'm not convinced that it's a bug but a lack of documentation. Regarding the user-provided `optimizer`, the documentation of [`stats.rv_continuous.fit`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.fit.html#scipy.stats.rv_continuous.fit) says only:

> optimizer : The optimizer to use. The optimizer must take `func` and starting position as the first two arguments, plus `args` (for extra arguments to pass to the function to be optimized) and `disp=0` to suppress output as keyword arguments.

This isn't really enough to use the `optimizer` parameter without looking into the source code. It doesn't state what the optimizer should return or guarantee that user guesses will be used.

To resolve this issue, I'd suggest that the the documentation of `optimizer` be adjusted to reflect what currently happens or, better yet, removed. The request for distribution `fit` methods to provide full support for a user-provided optimizer will be considered in gh-15928, which I've made a good start on this summer. In the meantime, please use [`scipy.stats.fit`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fit.html). Here is an example:

```python3
import numpy as np
from scipy import stats as stats
from scipy.optimize import minimize
import matplotlib.pyplot as plt

num_sim = 1000
degrees_freedom = 3
t_loc = 0
t_scale = 1

np.random.seed(42)
draws_t_dist = stats.distributions.t.rvs(degrees_freedom, t_loc, t_scale, size=num_sim)

# Nelder-Mead
def optimizer_NM(func, x0, bounds):
    return minimize(func, x0, bounds=bounds, method="nelder-mead")

bounds = dict(df=(0.1, 100), loc=(-100, 100), scale=(0.01, 100))
guess = dict(df=4, loc=-0.1, scale=0.5)
res = stats.fit(stats.t, draws_t_dist, bounds=bounds, guess=guess,
                optimizer=optimizer_NM)
res.plot()
plt.show()
```

![image](https://github.com/scipy/scipy/assets/6570539/56c9c797-f0e3-406d-b28d-03d4d0f5f450)

**Comment by mdhaber** [comment]
@kraxli would you be willing to submit a PR adjusting the documentation of `stats.rv_continuous.fit` according to the plan above? I can review.

**Comment by WarrenWeckesser** [comment]
> .. or, better yet, just removed. 

:scream: Definitely not better, I use that option a lot!  Betters docs + examples is the way to go.

**Comment by mdhaber** [comment]
Would you be willing to update the documentation then, since you know the interface? I can review it.

**Comment by WarrenWeckesser** [comment]
I won't have time in the immediate future to prepare a pull request.  For anyone who wants to tackle this, here are some additional descriptions and examples:

* Stackoverflow answer: https://stackoverflow.com/questions/65733870/scipy-stats-rv-continuous-fit-optimizer-parameters/65737886#65737886

* SciPy unit tests:
  * [`test_continuous_fit_censored.py`](https://github.com/scipy/scipy/blob/main/scipy/stats/tests/test_continuous_fit_censored.py)
  * [`test_distributions.py`](https://github.com/scipy/scipy/blob/5ed604385ff0912dccf958a6ae48a76e3d9571b8/scipy/stats/tests/test_distributions.py), specifically this test: https://github.com/scipy/scipy/blob/5ed604385ff0912dccf958a6ae48a76e3d9571b8/scipy/stats/tests/test_distributions.py#L8601-L8631

* In my `experiments` github repo:
  * https://github.com/WarrenWeckesser/experiments/tree/master/python/scipy/gev-return-levels
  * https://github.com/WarrenWeckesser/experiments/blob/master/python/scipy/check-mle/plot_check.py

@kraxli, that last file shown above (`plot_check.py` in my `experiments` repo), is an example of the use of the `nelder-mead` method of `scipy.optimize.minimize`.  The issue with your code is that the `fit()` method expects the custom optimizer to return just the optimal `x`, and not an `OptimizeResult`.  You have to check the result in your wrapper, and return `x` from the result if the optimization succeeded.  You could modify your optimizer function as follows:

    def optimizer_NM(func, x0=3, args=(0, 1), disp=False):
        res = minimize(func, x0, args, method="nelder-mead")
        if res.success:
            return res.x
        raise RuntimeError('optimization routine failed')

and your script should work.  For anyone updating the docs, this is a key point that should be added to the description and examples.

**Comment by kraxli** [comment]
thanks @mdhaber and @WarrenWeckesser for your help and suggestions! 

I can give the documentation update of [stats.rv_continuous.fit](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.fit.html#scipy.stats.rv_continuous.fit) a try, even though I am not yet familiar with the "interface" and it probably won't be immediate either.

**Comment by m-maggi** [comment]
I opened PR #19663 which includes an example with a custom optimiser, thanks to @WarrenWeckesser for the examples.
