### ISSUE TITLE
ENH: 

### ISSUE THREAD

**Issue by jmoralesFusion** [scipy/scipy#19234]
### Is your feature request related to a problem? Please describe.

Dear,
We rely extensively in "scipy.interpolate.interp1d" and we discover is deprecated in the last version (or legacy). I know numpy "interp" can be a replacement but the way it works is different. The fact that "interp1d" returns a function performing the interpolation is a very useful feature. We would like to ask to not remove this very useful function. Thank you in advance.
Regards, Jorge

**Comment by j-bowhay** [comment]
See https://scipy.github.io/devdocs/tutorial/interpolate/1D.html#tutorial-interpolate-1dsection for the recommended replacements. AFAIK there is not a current plan to remove `interp1d`, its legacy status means we do not intend to develop it further.
