### ISSUE TITLE
ENH: Please return pivots as well when `scipy.linalg.ldl( )` function is called.

### ISSUE THREAD

**Issue by khethan123** [scipy/scipy#19231]
## **present problem:**
`scipy.linalg.ldl(A, lower=True, hermitian=True, overwrite_a=False, check_finite=True)[[source]]`
 
_Returns:_

        lu : ndarray
            The (possibly) permuted upper/lower triangular outer factor of the factorization.
        
        d : ndarray
            The block diagonal multiplier of the factorization.
        
        perm : ndarray
            The row-permutation index array that brings lu into triangular form.

It does not return pivots which has also been computed!.

### Describe the solution you'd like.

![image](https://github.com/scipy/scipy/assets/100506743/f1117daf-3a4c-496c-a79e-9970ba42820a)

It would be better if it also returned pivots.

`lu, d, perm, pivot_arr = scipy.linalg.ldl(A) # Capture pivots as well`

##  Why?
**well**, pivots helps in identifying whether a matrix is a positive definite matrix or not and cholesky decomposition provides an error when we give a non-positive definite matrix as input, but LDL decomposition does not. 

This is where pivots play an important role. PyTorch implemented this and just by looking at the output we get to know whether the given input matrix was a positive definite matrix or not. 

### `LD, pivots = torch.linalg.ldl_factor(torch.from_numpy(A))`
 
![image](https://github.com/scipy/scipy/assets/100506743/86e28ec5-5a8b-4181-95fd-13bbce156a09)

### Additional context (e.g. screenshots, GIFs)

Here you can see that `cholesky` decomposition can't be performed for the matrix `A` but `ldl` can be performed
![image](https://github.com/scipy/scipy/assets/100506743/10741c75-da16-404a-bc1d-9e397f0c8142)

PyTorch's implementation of pivots. Seeing as there are negative elements in the array, the input matrix is not a positive definite matrix.
Here is how **PyTorch** deals with this
![image](https://github.com/scipy/scipy/assets/100506743/f4b716f5-4ab5-49c9-ac27-78a742d9d60d)

**Comment by ilayn** [comment]
Pivots and perm arrays encode the same information and negative pivots mean that there is a complex eigenvalue pair which is not possible for symmetric arrays. So I'm not sure what pytorch is testing it for but that is not the correct test anyways. There can be still  decompositions with all-positive pivot but not positive definite arrays.

If you must, you can also call `scipy.linalg.lapack.dsytrf()` yourself to test.

By the way, success of the cholesky decomposition is the industry standard test for positive definiteness check. LDL does not offer the same certificate.

**Comment by khethan123** [comment]
I am grateful for your clarification. I was hoping to implement the LDL decomposition from PyTorch in Python, but it is written in C++. SciPy uses LAPACK, which is written in Fortran, and I do not know either of these languages. I thought that if SciPy returned pivots like PyTorch, it would make my task easier.

I apologize for any inconvenience this may have caused. I created this issue to complete an open issue in `ivy` where in torch frontend folder `ldl_factor` function was to be implemented which behaves similar to PyTorch's `ldl_factor`.

**Comment by ilayn** [comment]
Then ‛scipy.linalg.lapack.dsytrf()‛ should be a better way to test things out which returns the pivot array. I'll close the issue as it is not actionable but please let us know if there is anything we can further clarify
