### ISSUE TITLE
About Matlab convert

### ISSUE THREAD

**Issue by panhu** [scipy/scipy#19258]
### Describe your issue.

Hi：
 I have a code of Matlab,like this:

h = fir2(200,[0,0.02,0.2,1],[1,1,0,0]);

Now, I would like to use scipy's firewin2 for replacement：

h = firwin2(200, [0, 0.48, 0.5, 1], [1, 1, 0, 0])

The results are different.
I would like to ask how the parameters should be modified to match the results of MATLAB.

### Reproducing Code Example

```python
None
```

### Error message

```shell
None
```

### SciPy/NumPy/Python version and system information

```shell
None
```

**Comment by andyfaff** [comment]
(saying with tongue in cheek ...) perhaps we should be asking the same from Matlab? How should Matlab be adapting their code to match our output?

**Comment by rgommers** [comment]
This is something we cannot answer I think. The results for any function in SciPy should be correct, but they may not match Matlab for a multitude of reasons. 

I'll close this issue since it's not actionable.
