### ISSUE TITLE
Calculation of frequencies w is not accurate when fs is default value (fs=2*pi)

### ISSUE THREAD

**Issue by sined23** [scipy/scipy#19273]
Calculation of frequencies w is not accurate when fs is default value (fs=2*pi)

https://github.com/scipy/scipy/blob/686422c4f0a71be1b4258309590fd3e9de102e18/scipy/signal/_filter_design.py#L483

Because at first python calculates w * fs and then divide into (2*pi). 
It's needed to use parentheses to allow python at first calculates fs/(2 * pi) and then multiply w
This is correct:
w = w * (fs / (2 * pi))

And pls fix other functions which has the same issue (freqz_zpk, group_delay)

**Comment by roryyorke** [comment]
Could you give an example where this makes a practical difference?  E.g., here's one where's the a `1e-16`-order difference:

```
In [20]: w = 0.8278445229178596

In [21]: fs = 2 * pi

In [22]: (w - w * fs / (2 * pi))
Out[22]: 1.1102230246251565e-16

In [24]: (w - w * (fs / (2 * pi)))
Out[24]: 0.0
```

**Comment by sined23** [comment]
I agree, it's not a big difference

**Comment by sined23** [comment]
I agree, it's not a big difference

**Comment by rgommers** [comment]
This seems like an easy fix, and may as well do it - applying `(fs / (2*pi))` first seems right.
