### ISSUE TITLE
SciPy 1.11.3 release with Python 3.12 support

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#19274]
@tylerjereddy just checking: with the NumPy 1.26.0 release out, I think it's our turn now to do the 1.11.3 release with Python 3.12 support. We have ~2 weeks left before the final Python 3.12.0 release, but since we're a dependency for many other projects we should probably do this as soon as possible. 3.12 wheel builds are working, so there's probably nothing blocking it. Did you plan for this release already?

**Comment by tylerjereddy** [comment]
Sounds good, did you have any suggested adjustment to what I did for pyproject.toml? I think I had hard pinned to the beta, do we still want a hard pin to stable 1.26.0?

**Comment by tylerjereddy** [comment]
Oh, cirrus credits for wheel builds on arm?

**Comment by rgommers** [comment]
Ah good point - let me resolve the credits issue by tomorrow. 

> I think I had hard pinned to the beta, do we still want a hard pin to stable 1.26.0?

We do want to tweak that. There's at least one build issue with the .0 release that I'm aware of, so we probably want `>=1.26.0,<1.27.0` right now.

**Comment by rgommers** [comment]
> I think it's our turn now to do the 1.11.3 release with Python 3.12 support. We have ~2 weeks left before the final Python 3.12.0 release

@tylerjereddy apologies, obviously my brain wasn't working yesterday - it completely escaped me that we already have `cp312` wheels up in the 1.11.2 release. So there's no real urgency here. That said, we accumulated a pretty large set of backports, so it's still nice to do a release. 

I'll check for other backports and the metadata update.

> Ah good point - let me resolve the credits issue by tomorrow.

Done now.

**Comment by rgommers** [comment]
`1.11.3` was released - thanks Tyler!
