### ISSUE TITLE
BUG: `scipy.optimize.newton` does not handle `float` initial values correctly

### ISSUE THREAD

**Issue by JeS24** [scipy/scipy#19272]
### Describe your issue.

I'm not sure if this is a bug per se, but I'm facing a weird issue in `scipy>=1.11.0` (tested with `1.11.0, 1.11.1, 1.11.2`, where the code below produces `nan` and fails to converge. The same code works normally in `scipy<1.11.0`. So, I looked into changes to the file mentioned in the error message, i.e., `scipy\optimize\_zeros_py.py`. It seems that to fix https://github.com/scipy/scipy/issues/10103, these changes were made to `newton()` ([commit](https://github.com/scipy/scipy/commit/58a08f0cf08f3b2907a2fbeaade2367cf6419962)):
```py
# scipy v1.10.1 - L295
p0 = 1.0 * x0

# scipy v1.11.0 - L295, L296
x0 = np.asarray(x0)[()]
p0 = x0
````
On the surface, this change should not alter how my code behaves, since the only effective change here is that `type(x0)` is `np.float64` in the new code, when it used to be `float` earlier (`x0 = 0.1`). And as far as I am aware, `np.float64` is equivalent to `float` in every manner. **However, for some reason, `newton` fails, if the type of `x0` is `np.float64` and not `float`**. Adding a simple `x0 = float(x0)` at L296 in the new code makes the code below work with no errors. Personally, I am at a loss as to why this is happening. I'd be grateful, if someone can help me here.

### Sidenote
Changing L295 to the following fixes this issue, while also fixing https://github.com/scipy/scipy/issues/10103. However, it doesn't help with an explanation.
```py
# scipy >= v1.11.0 - ~L295 - Proposed
x0 = np.complex128(x0) if np.iscomplexobj(x0) else x0
``` 

### Reproducing Code Example

```python
# Turning points for given impact parameters (solving for Schwarzschild black hole shadow)
import numpy as np
from scipy.optimize import newton

mass = 1
fov = 30
n_rays = 1000
b_crit = 3 * np.sqrt(3) * mass
b = np.linspace(b_crit, fov, n_rays)

def root_equation(r_tp, i):
    return r_tp / ((1 - (2 * int(mass) / r_tp))) ** 0.5 - i

for i in b:
    root = newton(root_equation, 0.1, args=(i,))
    # Other stuff to do with root
```

### Error message

```shell
XXXX\Temp\ipykernel_12984\3489237660.py:12: RuntimeWarning: invalid value encountered in scalar power
  return r_tp / ((1 - (2 * int(mass) / r_tp))) ** 0.5 - i
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
XXXX.ipynb Cell 10 line 1
     12     return r_tp / ((1 - (2 * int(mass) / r_tp))) ** 0.5 - i
     14 for i in b:
---> 15     root = newton(root_equation, 0.1, args=(i,))

XXXX\Lib\site-packages\scipy\optimize\_zeros_py.py:400, in newton(func, x0, fprime, args, tol, maxiter, fprime2, x1, rtol, full_output, disp)
    397 if disp:
    398     msg = ("Failed to converge after %d iterations, value is %s."
    399            % (itr + 1, p))
--> 400     raise RuntimeError(msg)
    402 return _results_select(full_output, (p, funcalls, itr + 1, _ECONVERR))

RuntimeError: Failed to converge after 50 iterations, value is nan.
```

### SciPy/NumPy/Python version and system information

```shell
1.11.0 1.24.4 sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: c:/opt/64/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: c:/opt/64/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.35
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  pythran:
    include directory: C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-12ywd98f\overlay\Lib\site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
Python Information:
  path: C:\Users\runneradmin\AppData\Local\Temp\cibw-run-uqg6lkbl\cp311-win_amd64\build\venv\Scripts\python.exe
  version: '3.11'
```

**Comment by ev-br** [comment]
Ideally, drop a breakpoint into newton's implementation and see where the two iterations start diverging. Would be great if you could do that @JeS24 , actually

**Comment by andyfaff** [comment]
`root_equation` is a complex function, when given the initial `r_tp`, `i` values, it returns a complex number. If you supply an initial `x0` guess of `0.1+1e-5j`, then the root find seems to work.

**Comment by andyfaff** [comment]
I'm not sure if a fix is required here. We could possibly do a check for finiteness coming back from the user function, but that would add overhead.

**Comment by andyfaff** [comment]
Changing `root_equation` to:
```
def root_equation(r_tp, i):
    r_tp = complex(r_tp)
    return r_tp / ((1 - (2 * int(mass) / r_tp))) ** 0.5 - i
```
will solve the current issues.

**Comment by JeS24** [comment]
@andyfaff Thank you for the detailed response. I had tried a complex `x0` before and that works with `scipy>=1.11.0`, but it unfortunately breaks compatibility with `scipy<=1.10.0` due to https://github.com/scipy/scipy/issues/10103. More importantly, it did not shed light on why this issue was occurring. numpy's sqrt being domain-limited does answer that. On that note, `np.emath.sqrt` instead of `** 0.5` would also help here as would your `complex(r_tp)` suggestion.

As for the issue, would replacing `x0 = np.asarray(x0)[()]` with `x0 = np.complex128(x0) if np.iscomplexobj(x0) else x0` not work as a general fix, instead of a finiteness check. Based on my testing, it adds negligible overhead (tested with jupyter):
```py
import numpy as np

x0 = np.random.uniform(-1, -0.1, int(1e8)) # Real
%timeit np.complex128(x0) if np.iscomplexobj(x0) else x0
# 450 ns ± 21.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

x0 = np.emath.sqrt(np.random.uniform(-1, 1, int(1e8))) # Mixed
%timeit np.complex128(x0) if np.iscomplexobj(x0) else x0
# 634 ns ± 43.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

x0 = np.emath.sqrt(np.random.uniform(-1, -0.1, int(1e8))) # Complex
%timeit np.complex128(x0) if np.iscomplexobj(x0) else x0
# 689 ns ± 41.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```
Of course, there might be other considerations here that I am missing.

> We could possibly do a check for finiteness coming back from the user function, but that would add overhead.

Besides the overhead issue with the finiteness check, I don't think such a check would be appropriate here, as it could cause confusion by conflating a numpy design choice with user error, for instance in this case. I understand, `np.sqrt`'s documentation mentions this issue explicitly, but given how elementary the square root operation is, it can become complicated to troubleshoot an issue like that, when the functional expression itself is semantically, if not syntactically correct.

**Comment by andyfaff** [comment]
> would replacing x0 = np.asarray(x0)[()] with x0 = np.complex128(x0) if np.iscomplexobj(x0) else x0 not work as a general fix

No, I think there are other considerations there.

**Comment by andyfaff** [comment]
@mdhaber, you last touched these lines, adding the `np.asarray`:

```
    # Convert to float (don't use float(x0); this works also for complex x0)
    x0 = np.asarray(x0)[()]
    p0 = x0
```

If `x0` is an integer then `p0` becomes an integer array, and not a float array. The comment seemingly wants an inexact type. Shouldn't we have:

```
    # Convert to float (don't use float(x0); this works also for complex x0)
    x0 = np.asarray(x0)[()] * 1.0       # <---- multiply by 1.0 to get an inexact type.
    p0 = x0
```

**Comment by mdhaber** [comment]
Oops.  Multiplying by 1.0 will always produce a `float64`. Is that OK? If not, consider multiplying by `np.float16(1)`, or determining the `result_type` of `x0.dtype` and `np.float16` and specifying the `dtype` of the array.

**Comment by andyfaff** [comment]
I make the change in #19280. I think multiplying by 1.0 should be ok. If `x0` is a smaller floating point type multiplying it by 1.0 won't make it double.

**Comment by mdhaber** [comment]
It depends on whether it's an array or not. If it is a scalar, it will become a float64.

**Comment by mdhaber** [comment]
```
x = np.asarray([1], dtype=np.float32)[()]*1.
x.dtype  # dtype('float32')
x = np.asarray(1, dtype=np.float32)[()]*1.
x.dtype  # dtype('float64')
```

**Comment by andyfaff** [comment]
Perhaps the solution is to use common_type:

```
# first one gets promoted to float64 because it's an integer
np.common_type(np.asarray(1)[()], np.float16(1.0)) # numpy.float64
np.common_type(np.asarray(1, dtype=np.float32)[()], np.float16(1.0)) # numpy.float32
np.common_type(np.asarray([1], dtype=np.float32)[()], np.float16(1.0)) # numpy.float32

**Comment by mdhaber** [comment]
Huh, that looks like what I've wanted. Elsewhere, I've resorted to something like:
```python3
dtype = np.float64 if np.issubdtype(x.dtype, np.integer) else x.dtype
```
