### ISSUE TITLE
Reuse conjugate gradient in newton-cg

### ISSUE THREAD

**Issue by lorentzenchr** [scipy/scipy#19288]
Scipy has a conjugate gradient solver for linear equations, `scipy.sparse.linalg.cg`. This could be used in the optimization method "Newton-CG" of `scipy.optimize.minimize` which currently reimplements CG.

**Comment by dschmitz89** [comment]
Related/same issue: https://github.com/scipy/scipy/issues/8792

**Comment by WebFa98** [comment]
We took a look at it. 
The lines are at https://github.com/scipy/scipy/blob/main/scipy/optimize/_optimize.py#L2051 and we compared the cg implementation with the implementation of `scipy.sparse.linalg.cg` at  https://github.com/scipy/scipy/blob/main/scipy/sparse/linalg/_isolve/iterative.py#L308 , 
but i dont think we can just easily replace it by `scipy.sparse.linalg.cg`, since there are some optimizations for the matrix-vector product, with the hessian evaluations.

**Comment by jeffrey-hokanson** [comment]
My background is more numerical linear algebra, but my understanding is that although the [CG iterations in Newton-CG](https://github.com/scipy/scipy/blob/ae3ca70a72ef04547fbc28501009246cef5ee6c8/scipy/optimize/_optimize.py#L2199C1-L2205) are similar to [those in the CG implementation](https://github.com/scipy/scipy/blob/ae3ca70a72ef04547fbc28501009246cef5ee6c8/scipy/sparse/linalg/_isolve/iterative.py#L416), Newton-CG needs to handle negative curvature differently (e.g., the presence of negative eigenvalues). With standard CG, the algorithm will fail if the matrix is not symmetric positive definite. However, with Newton-CG even if the Hessian is indefinite (i.e., has negative curvature), we can still extract a useful descent direction from the current iterate of CG; note the break when negative curvature is detected [here](https://github.com/scipy/scipy/blob/ae3ca70a72ef04547fbc28501009246cef5ee6c8/scipy/optimize/_optimize.py#L2194C26-L2194C26). 

With a bit of work, we could combine the CG component of Newton-CG with the pure CG implementation, but we would need add logic to return the partial progress in the case of negative curvature. My instinct is that combining ~5 lines of the two CG implementations doesn't merit the additional complexity, but that is up to the maintainers to decide.

Looking over the code though, we may want to reconsider some of the termination conditions. For example, the default allows 20*n iterations of CG, where n is the dimension of the Hessian---this may lead to too much work finding a descent direction when taking an approximate step would be preferable. @ccmagruder Do you have any insights?

**Comment by lorentzenchr** [comment]
Good arguments against.
