### ISSUE TITLE
`pytest` is slower then `scipy.test()`?

### ISSUE THREAD

**Issue by doronbehar** [scipy/scipy#19325]
Hello,

In Nixpkgs, we have automatic hooks to test python packages with `pytest` during build. For example, we recently changed numpy to use pytest instead of running manually `numpy.test` in https://github.com/NixOS/nixpkgs/pull/251923 .

I'm trying to do the same for scipy at https://github.com/NixOS/nixpkgs/pull/255607 , and it takes for me hours instead of minutes to run the `"fast"` tests, in comparison to running manually `scipy.test`. I included `pytest-xdist` dependency in https://github.com/NixOS/nixpkgs/pull/255607, which adds the pytest flags `--numprocesses` flag, per:

https://github.com/NixOS/nixpkgs/blob/a4a1616950b72be17bcbdda218da1c165ffbb69d/pkgs/development/python-modules/pytest-xdist/setup-hook.sh#L1-L5

I also verified that it is indeed added to the `pytest` call. I also verified that with `-m slow` flag indeed pytest run the same number of tests as when I run `scipy.test` manually, and after enough time, the same number of tests xfail, xpass, and pass...

Do you have any idea why would that happen? What is Numpy doing different?

Help will be appreciated to make scipy's Nixpkgs expression cleaner and nicer.

**Comment by rgommers** [comment]
> Do you have any idea why would that happen? What is Numpy doing different?

Hmm, `numpy` now skips the slow tests by default when `pytest --pyargs numpy` is used? If so, it'd be nice to figure out the difference indeed, and do the same in scipy. But I'm not sure that that is what you are saying in your first sentence. Perhaps numpy slow tests are run too, but there are simply fewer of them?

The `slow` marker is defined in `scipy/conftest.py`. `pytest` doesn't have a great design for discovering `conftest.py`, and in particular getting it from an installed package is something that the docs (despite multiple other disclaimers) is silent on:
- https://doc.pytest.org/en/latest/how-to/writing_plugins.html#conftest-py-local-per-directory-plugins
- https://doc.pytest.org/en/latest/explanation/pythonpath.html#pythonpath

**Comment by doronbehar** [comment]
> Hmm, `numpy` now skips the slow tests by default when `pytest --pyargs numpy` is used?

We don't use `--pyargs numpy` when we test numpy.

> Perhaps numpy slow tests are run too, but there are simply fewer of them?

That's possible, perhaps we can answer this question by looking at the number of numpy tests we run? For numpy 1.25.2 ([Link to our CI](https://hydra.nixos.org/build/236811063)), with the `numpy.test` -> `pytest` change, our logs indicate:

```
= 35344 passed, 1624 skipped, 1308 deselected, 31 xfailed, 4 xpassed, 616 warnings in 166.22s (0:02:46) =
```

Where as **without** the `numpy.text` -> `pytest` change, for numpy 1.25.1, we get ([Link to our CI](https://hydra.nixos.org/build/236437927)):

```
= 35263 passed, 1624 skipped, 1308 deselected, 31 xfailed, 4 xpassed, 377 warnings in 279.44s (0:04:39) =
```

I'll note again, that for scipy, both with `pytest` and with `scipy.test`, I get the same report as the above - same number of tests fail, skipped, xfail etc.

> The `slow` marker is defined in `scipy/conftest.py`

In both `numpy` and `scipy`, I see that this file is installed in Nix' `site-packages/{pkg}` directory, so if indeed we managed to _not_ run the slow tests on numpy, the discoverability of `conftest.py` is not the issue?

> getting it from an installed package is something that the docs (despite multiple other disclaimers) is silent on:

Hmm I'm not sure exactly what you mean here, but I will note that we observed testing related issues in Python packages that use Cython, and we investigate it in https://github.com/NixOS/nixpkgs/issues/255262 . What maybe relevant to mention here, is the fact we use `cd $out` before running tests to workaround the issue, where to `$out/lib/python3.11/site-packages/scipy` scipy's compiled files reach.

**Comment by andyfaff** [comment]
How do the timings change between using pytest-xdist and not?

**Comment by doronbehar** [comment]
> How do the timings change between using pytest-xdist and not?

To the best of memory, it took hours with and without pytest-xdist. Hopefully I will be able to give an accurate report a few days after the weekend, when I reach a strong enough machine to run these tests over and over. I'll note here for myself what I want to test when I reach my stronger machine:

- [ ] Test scipy with and without pytest-xdist. What is the time difference between the two?
- [ ] Test what happens when I `cd $out/lib/python3.11/site-packages/scipy` instead of `cd $out` - is `conftest.py` detected?
- [ ] What happens if I use `-m bla`, or `-m slow` - do invalid markers cause an appropriate error? Or does running only the slow tests really happens?

**Comment by tylerjereddy** [comment]
Other things that may be useful with `pytest` incantations include perhaps:
- `-rsx` flag for a bit more detail on what gets skipped and why
- on the topic of `pytest-xdist`, do you have `threadpoolctl` installed? I've seen hangs without it on some machine with high concurrency testing? `OMP_NUM_THREADS` is set in the env? Using standard OpenBLAS from somewhere? which version?

**Comment by doronbehar** [comment]
Thanks for the ideas @tylerjereddy . We don't add `threadpoolctl` to our build, and I'm testing it on an 8 core office PC and on my 8 core laptop, with no such high concurrency... We do set `OMP_NUM_THREADS` to the numpy build, but not to the scipy build. We use openblas 0.3.21.

I know we can in principle update it, but I doubt it will make a difference, as using `scipy.test()` proves that the tests can run fast in principle. I also managed to screenshot the processes that run when the tests are slow, with `OMP_NUM_THREADS=8`:

![image](https://github.com/scipy/scipy/assets/10998835/4c2f37f7-fce2-4858-8df5-b5ac753cb282)

Indeed there are 8 process, and the `-rsx` flags are used, and it takes too long as before - `OMP_NUM_THREADS` didn't make a difference so it seems.. As for the pytest flags, `-r` is not needed, because I always get a report of how many tests passed, failed, xfailed etc, as I reported in [my 2nd comment](https://github.com/scipy/scipy/issues/19325#issuecomment-1741719601). `-x` is also unneeded, as all tests pass, and as for `-s`, I'm not sure what it's supposed to do, as I didn't find documentation by pytest's docs, and I didn't see reports of what tests got skipped and why... Also, please note that the short summary reports show the same number of tests passed, xfailed, skipped etc, both when I use `scipy.test()` and when I use `pytest`.

In contrast to the above processes screenshot, when running `scipy.test()`, I see:

![image](https://github.com/scipy/scipy/assets/10998835/c5adeb9f-f3a9-4e6f-80c9-df032eb1ff56)

And just by looking at how the percentages progress, I can see it takes less 6 minutes, vs ~1 hour.

> * run verbose `pytest -v` to see if you notice which test you get "stuck" on

I don't see any test that is slow in particular... Is there a way to tell pytest how long did each test took?

**Comment by tylerjereddy** [comment]
You could use i.e., `--durations=20` to record the slowest 20 tests for example. Perhaps comparing that for the two scenarios might be interesting.

**Comment by tylerjereddy** [comment]
By the way, are you saying there is an easy way to reproduce this outside of some CI process? Like a few steps you could provide to make it easy for us to reproduce? Maybe through a container or something like that?

**Comment by doronbehar** [comment]
> By the way, are you saying there is an easy way to reproduce this outside of some CI process? Like a few steps you could provide to make it easy for us to reproduce? Maybe through a container or something like that?

Yes! No need for containers. Only need to install Nix, and clone [`nixpkgs`](https://github.com/NixOS/nixpkgs) (takes a while :)). Then, you'd be able to checkout [my PR](https://github.com/NixOS/nixpkgs/pull/255607), and be able to compare `nix-build -A python3.pkgs.scipy` in branch `staging-next`, vs branch `pkg/numpy-scipy-pytest`.

**Comment by doronbehar** [comment]
BTW this is the output of `pytest --markers`

```
@pytest.mark.filterwarnings(warning): add a warning filter to the given test. see https://docs.pytest.org/en/stable/how-to/capture-warnings.html#pytest-mark-filterwarnings
@pytest.mark.skip(reason=None): skip the given test function with an optional reason. Example: skip(reason="no way of currently testing this") skips the test.
@pytest.mark.skipif(condition, ..., *, reason=...): skip the given test function if any of the conditions evaluate to True. Example: skipif(sys.platform == 'win32') skips the test if we are on the win32 platform. See https://docs.pytest.org/en/stable/reference/reference.html#pytest-mark-skipif
@pytest.mark.xfail(condition, ..., *, reason=..., run=True, raises=None, strict=xfail_strict): mark the test function as an expected failure if any of the conditions evaluate to True. Optionally specify a reason for better reporting and run=False if you don't even want to execute the test function. If only specific exception(s) are expected, you can list them in raises, and if the test fails in other ways, it will be reported as a true failure. See https://docs.pytest.org/en/stable/reference/reference.html#pytest-mark-xfail
@pytest.mark.parametrize(argnames, argvalues): call a test function multiple times passing in different arguments in turn. argvalues generally needs to be a list of values if argnames specifies only one name or a list of tuples of values if argnames specifies multiple names. Example: @parametrize('arg1', [1,2]) would lead to two calls of the decorated test function, one with arg1=1 and another with arg1=2.see https://docs.pytest.org/en/stable/how-to/parametrize.html for more info and examples.
@pytest.mark.usefixtures(fixturename1, fixturename2, ...): mark tests as needing all of the specified fixtures. see https://docs.pytest.org/en/stable/explanation/fixtures.html#usefixtures
@pytest.mark.tryfirst: mark a hook implementation function such that the plugin machinery will try to call it first/as early as possible. DEPRECATED, use @pytest.hookimpl(tryfirst=True) instead.
@pytest.mark.trylast: mark a hook implementation function such that the plugin machinery will try to call it last/as late as possible. DEPRECATED, use @pytest.hookimpl(trylast=True) instead.
@pytest.mark.xdist_group: specify group for tests should run in same session.in relation to one another. Provided by pytest-xdist.
```

And the output of `pytest --fixtures`:

```
============================= test session starts ==============================
platform linux -- Python 3.11.5, pytest-7.4.2, pluggy-1.2.0
rootdir: /nix/store/j2h237mywxxa9cn60nlq3f9az620dbdb-python3.11-scipy-1.11.3
plugins: xdist-3.3.1
collected 58131 items
cache -- .../_pytest/cacheprovider.py:532
    Return a cache object that can persist state between testing sessions.
capsysbinary -- .../_pytest/capture.py:1001
    Enable bytes capturing of writes to ``sys.stdout`` and ``sys.stderr``.
capfd -- .../_pytest/capture.py:1029
    Enable text capturing of writes to file descriptors ``1`` and ``2``.
capfdbinary -- .../_pytest/capture.py:1057
    Enable bytes capturing of writes to file descriptors ``1`` and ``2``.
capsys -- .../_pytest/capture.py:973
    Enable text capturing of writes to ``sys.stdout`` and ``sys.stderr``.
doctest_namespace [session scope] -- .../_pytest/doctest.py:757
    Fixture that returns a :py:class:`dict` that will be injected into the
    namespace of doctests.
pytestconfig [session scope] -- .../_pytest/fixtures.py:1353
    Session-scoped fixture that returns the session's :class:`pytest.Config`
    object.
record_property -- .../_pytest/junitxml.py:282
    Add extra properties to the calling test.
record_xml_attribute -- .../_pytest/junitxml.py:305
    Add extra xml attributes to the tag for the calling test.
record_testsuite_property [session scope] -- .../_pytest/junitxml.py:343
    Record a new ``<property>`` tag as child of the root ``<testsuite>``.
tmpdir_factory [session scope] -- .../_pytest/legacypath.py:302
    Return a :class:`pytest.TempdirFactory` instance for the test session.
tmpdir -- .../_pytest/legacypath.py:309
    Return a temporary directory path object which is unique to each test
    function invocation, created as a sub directory of the base temporary
    directory.
caplog -- .../_pytest/logging.py:570
    Access and control log capturing.
monkeypatch -- .../_pytest/monkeypatch.py:30
    A convenient fixture for monkey-patching.
recwarn -- .../_pytest/recwarn.py:30
    Return a :class:`WarningsRecorder` instance that records all warnings emitted by test functions.
tmp_path_factory [session scope] -- .../_pytest/tmpdir.py:245
    Return a :class:`pytest.TempPathFactory` instance for the test session.
tmp_path -- .../_pytest/tmpdir.py:260
    Return a temporary directory path object which is unique to each test
    function invocation, created as a sub directory of the base temporary
    directory.
---------------------- fixtures defined from xdist.plugin ----------------------
worker_id [session scope] -- ../yqdvg7prsw0jqpby0yszvi807rwvvnyx-python3.11-pytest-xdist-3.3.1/lib/python3.11/site-packages/xdist/plugin.py:330
    Return the id of the current worker ('gw0', 'gw1', etc) or 'master'
    if running on the master node.
testrun_uid [session scope] -- ../yqdvg7prsw0jqpby0yszvi807rwvvnyx-python3.11-pytest-xdist-3.3.1/lib/python3.11/site-packages/xdist/plugin.py:339
    Return the unique id of the current test.
--------------------- fixtures defined from scipy.conftest ---------------------
check_fpu_mode -- lib/python3.11/site-packages/scipy/conftest.py:84
    Check FPU mode was not changed during the test.
------------- fixtures defined from scipy._lib.tests.test_warnings -------------
warning_calls [session scope] -- lib/python3.11/site-packages/scipy/_lib/tests/test_warnings.py:63
    no docstring available
------------ fixtures defined from scipy.spatial.tests.test_kdtree -------------
kdtree_type -- lib/python3.11/site-packages/scipy/spatial/tests/test_kdtree.py:19
    no docstring available
----------- fixtures defined from scipy.spatial.tests.test_distance ------------
metric [session scope] -- lib/python3.11/site-packages/scipy/spatial/tests/test_distance.py:66
    Fixture for all metrics in scipy.spatial.distance
----------- fixtures defined from scipy.optimize.tests.test_optimize -----------
function_with_gradient -- lib/python3.11/site-packages/scipy/optimize/tests/test_optimize.py:2648
    no docstring available
----------- fixtures defined from scipy.special.tests.test_ndtri_exp -----------
uniform_random_points [class scope] -- lib/python3.11/site-packages/scipy/special/tests/test_ndtri_exp.py:13
    no docstring available
---------- fixtures defined from scipy.fft.tests.test_multithreading -----------
x [module scope] -- lib/python3.11/site-packages/scipy/fft/tests/test_multithreading.py:10
    no docstring available
---------- fixtures defined from scipy.special.tests.test_log_softmax ----------
log_softmax_x -- lib/python3.11/site-packages/scipy/special/tests/test_log_softmax.py:24
    no docstring available
log_softmax_expected -- lib/python3.11/site-packages/scipy/special/tests/test_log_softmax.py:30
    no docstring available
log_softmax_2d_x -- lib/python3.11/site-packages/scipy/special/tests/test_log_softmax.py:69
    no docstring available
log_softmax_2d_expected -- lib/python3.11/site-packages/scipy/special/tests/test_log_softmax.py:75
    no docstring available
--------- fixtures defined from scipy.linalg.tests.test_interpolative ----------
eps -- lib/python3.11/site-packages/scipy/linalg/tests/test_interpolative.py:44
    no docstring available
A -- lib/python3.11/site-packages/scipy/linalg/tests/test_interpolative.py:49
    no docstring available
L -- lib/python3.11/site-packages/scipy/linalg/tests/test_interpolative.py:57
    no docstring available
rank -- lib/python3.11/site-packages/scipy/linalg/tests/test_interpolative.py:62
    no docstring available
------ fixtures defined from scipy.stats.tests.test_sensitivity_analysis -------
ishigami_ref_indices [session scope] -- lib/python3.11/site-packages/scipy/stats/tests/test_sensitivity_analysis.py:16
    Reference values for Ishigami from Saltelli2007.
------------- fixtures defined from scipy.datasets.tests.test_data -------------
test_download_all [module scope] -- lib/python3.11/site-packages/scipy/datasets/tests/test_data.py:30
    no docstring available
------ fixtures defined from scipy.sparse.linalg.tests.test_pydata_sparse ------
sparse_cls -- lib/python3.11/site-packages/scipy/sparse/linalg/tests/test_pydata_sparse.py:35
    no docstring available
sp_sparse_cls -- lib/python3.11/site-packages/scipy/sparse/linalg/tests/test_pydata_sparse.py:40
    no docstring available
same_matrix -- lib/python3.11/site-packages/scipy/sparse/linalg/tests/test_pydata_sparse.py:45
    no docstring available
matrices -- lib/python3.11/site-packages/scipy/sparse/linalg/tests/test_pydata_sparse.py:52
    no docstring available
---- fixtures defined from scipy.fft._pocketfft.tests.test_real_transforms -----
fftwdata_size -- lib/python3.11/site-packages/scipy/fft/_pocketfft/tests/test_real_transforms.py:69
    no docstring available
mdata_x -- lib/python3.11/site-packages/scipy/fft/_pocketfft/tests/test_real_transforms.py:73
    no docstring available
mdata_xy -- lib/python3.11/site-packages/scipy/fft/_pocketfft/tests/test_real_transforms.py:78
    no docstring available
---- fixtures defined from scipy.sparse.linalg._isolve.tests.test_iterative ----
case [session scope] -- lib/python3.11/site-packages/scipy/sparse/linalg/_isolve/tests/test_iterative.py:190
    Fixture for all cases in IterativeParams
solver [session scope] -- lib/python3.11/site-packages/scipy/sparse/linalg/_isolve/tests/test_iterative.py:32
    Fixture for all solvers in scipy.sparse.linalg._isolve
---------- fixtures defined from scipy.stats.tests.test_distributions ----------
rng -- lib/python3.11/site-packages/scipy/stats/tests/test_distributions.py:2065
    no docstring available
rng -- lib/python3.11/site-packages/scipy/stats/tests/test_distributions.py:3967
    no docstring available
rng -- lib/python3.11/site-packages/scipy/stats/tests/test_distributions.py:2915
    no docstring available
rng -- lib/python3.11/site-packages/scipy/stats/tests/test_distributions.py:1960
    no docstring available
nolan_pdf_sample_data -- lib/python3.11/site-packages/scipy/stats/tests/test_distributions.py:4529
    Sample data points for pdf computed with Nolan's stablec
nolan_cdf_sample_data -- lib/python3.11/site-packages/scipy/stats/tests/test_distributions.py:4563
    Sample data points for cdf computed with Nolan's stablec
nolan_loc_scale_sample_data -- lib/python3.11/site-packages/scipy/stats/tests/test_distributions.py:4607
    Sample data where loc, scale are different from 0, 1
ROOT_pdf_sample_data -- lib/python3.11/site-packages/scipy/stats/tests/test_distributions.py:8877
    Sample data points for pdf computed with CERN's ROOT
============================ no tests ran in 13.65s ============================
```

Is it me or is there no `slow` marker test?

**Comment by doronbehar** [comment]
OK now I see that also for numpy, `pytest --markers` doesn't show the `slow` marker. This issue is deeply intermingled with https://github.com/NixOS/nixpkgs/issues/255262 , which basically points out a somewhat common issue we experience only in Nix, with python packages that use cython... Basically, the workaround I'm currently using that fits `numpy` as well, is to `cd $out` where `conftest.py` is installed in `$out/lib/python3.11/site-packages/{scipy,numpy}/`, along all the other files of `{scipy,numpy}`.

I'm not sure how to further investigate this issue, so I'll let it go for now...

**Comment by doronbehar** [comment]
This doesn't seem to be an issue with scipy 1.12.0rc2 . Closing.
