### ISSUE TITLE
ENH: scipy.optimize should not import numpy.testing

### ISSUE THREAD

**Issue by danielhollas** [scipy/scipy#19344]
### Is your feature request related to a problem? Please describe.

I am not sure how much this is intented or not, but `scipy/optimize/_constraints.py` imports `suppress_warnings` from `numpy.testing` module.
At least on my machine (specs below) this introduces 30ms import latency since `numpy.testing` calls `lscpu` via subprocess on import. The same issue appears to be in `signal/_ltisys.py`, `stats/_binned_statistic.py`  and `stats/_stats_py`

I am running linux Mint 20.3

```console
$ uname -a
Linux hollas-atmospec 5.15.0-83-generic #92~20.04.1-Ubuntu SMP Mon Aug 21 14:00:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

```console
$ python -c "import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()"
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "0.29.36",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.2.1",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.14.0",
      "include directory": "../../tmp/pip-build-env-_ne5uwbp/overlay/lib/python3.9/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21.dev",
      "detection method": "pkgconfig",
      "include directory": "/usr/local/include",
      "lib directory": "/usr/local/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2",
      "pc file directory": "/usr/local/lib/pkgconfig"
    },
    "lapack": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21.dev",
      "detection method": "pkgconfig",
      "include directory": "/usr/local/include",
      "lib directory": "/usr/local/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2",
      "pc file directory": "/usr/local/lib/pkgconfig"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.11.0",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "/opt/python/cp39-cp39/bin/python",
    "version": "3.9"
  }
}

```

### Describe the solution you'd like.

Do not import `numpy.testing` in production code.

### Describe alternatives you've considered.

Could be fixed in `numpy.testing` but the module name suggests that it is not intended for production?

**Comment by andyfaff** [comment]
At least in `optimize._constraints` the code can be amended to:

```python
        with catch_warnings():
            warnings.filterwarnings("ignore", "delta_grad", UserWarning)
            ev = self.fun.fun(np.asarray(x))
```

I'm not sure why suppress_warnings was used in the other examples, they'd have to be investigated individually.

**Comment by mdhaber** [comment]
If I remember correctly, uses of `filterwarnings` causes some test to fail, or it has in the past. That is my guess for why `suppress_warnings` was used.

**Comment by andyfaff** [comment]
Back in 46f67f29928b85e954d5633a996c9df1e09fa272 we (I) changed to `suppress_warnings` from `catch_warnings`. Unfortunately I didn't leave a comment saying why that was necessary. I know a warning is raised when `NonlinearConstraint` is used when a `LinearConstraint` is probably better.  However, there are no test fails when I substitute the code above.

@mdhaber, do you know about the other instances suggested?

**Comment by mdhaber** [comment]
Not off the top of my head. I'd suggest trying it and if there are no failures, it's fine.

**Comment by mdhaber** [comment]
There is a bit of discussion here:
https://github.com/scipy/scipy/pull/15323#issuecomment-1003430757
https://github.com/scipy/scipy/pull/13382#issuecomment-759239298

**Comment by rgommers** [comment]
Agreed, we can remove it - and also agreed that we should not import `numpy.testing` anywhere except for in our own test suite.

**Comment by danielhollas** [comment]
Thanks guys for such an amazingly fast turnaround 🙏 Cheers.
