### ISSUE TITLE
ENH: A vectorized version of scipy.optimize.brentq

### ISSUE THREAD

**Issue by adonath** [scipy/scipy#19354]
### Is your feature request related to a problem? Please describe.

For a very specific problem I was working on, I needed to find many O(>10^6) roots using `scipy.optimize.brentq`. Brent's method is very nice, because it is very stable and typically very fast. However it does not scale to a large number of problems, because it needs to have a Python loop, which then becomes the bottleneck.

### Describe the solution you'd like.

I decided to re-implement the method just using plain numpy and vectorization. The prototype can be found here: https://github.com/adonath/array-brentq. It is by a factor of 100 faster once one is using large array sizes (>500 entries). If the Scipy maintainers think this is potentially useful for the community, I would be more than happy to contribute this. However I would need some guidance.

### Describe alternatives you've considered.

A Python loop over `scipy.optimize.brentq` does not scale to a large number of root finding problems, because the loop then becomes the bottleneck.

One could possibly extend the existing C implementation to support arrays. But it seems the Numpy version just works fine.

**Comment by mdhaber** [comment]
There is a vectorized version of Chandrupatla's algorithm that is already merged into SciPy for internal use but is waiting for a public interface. Would you be interested in trying it to so whether it meets your needs?

**Comment by mdhaber** [comment]
In any case, I think this issue is a duplicate of https://github.com/scipy/scipy/issues/7242. I'll go ahead and close this one shortly, and we can continue the discussion there.

**Comment by adonath** [comment]
Thanks a lot @mdhaber, yes indeed we can continue the discussion in #7242. I searched specifically for "brentq" and no issue did not show up. 

Thanks @ev-br, I am aware of the inverse method as well. However in practice the `brentq` converges nicely within <5 iterations, while I would maybe need more function evaluations to sample the function sufficiently.
