### ISSUE TITLE
ENH: Using basinhopping with a multivariate valued function and a specified norm, instead of an objective function

### ISSUE THREAD

**Issue by TrakJohnson** [scipy/scipy#19353]
### Is your feature request related to a problem? Please describe.

I'm working on a root finding problem to solve a system of equations. I've had a lot of success using `scipy.optimize.least_squares(method="trf")`, and I'd now like to use this as a local optimization method in a global two-phase method. 

Using `scipy.optimize.basinhopping` in this fashion would be nice:

    # f: Callable[[np.array], np.array]

    # local
    def custom_minimizer(fun, _x0, *args, **kwargs):
        return scipy.optimize.least_squares(fun, _x0)

    # global: minimize f starting at x0
    ret = basinhopping(
        f,
        x0,
        minimizer_kwargs={"method": custom_minimizer},
    )

but basinhopping requires a scalar valued function. This means that in the custom_minimizer, I'll only have access to `x -> norm(f(x))`, which prevents me from using the Trust Region Reflective method for example.

### Describe the solution you'd like.

Allow the `basinhopping` function to separate the norm from the multidim-valued function, and pass that function as an argument to the local optimizer.

### Describe alternatives you've considered.

I can't use most other strategies, because my system of equations isn't square. That's why I rely on `least_squares`, and it would be great if there was a way to use basinhopping directly.

**Comment by andyfaff** [comment]
This is already possible:

```
import numpy as np
from scipy.optimize import rosen, basinhopping, least_squares
from numpy.random import default_rng
rng = default_rng()


ts = np.linspace(0, 1)

def fun(x):
    return y(x, ts)

K = 1
r = 10
t0 = 0.5
noise = 0.1
ys = fun([K, r, t0]) + noise*np.random.rand(ts.shape[0])

def residuals(x):
    return fun(x) - ys

def norm(x):
    return np.sum(residuals(x) ** 2)

x0 = [1, 2, 3]
res1 = least_squares(residuals, x0)  # challenge by least_squares first
assert (res1. success)

# local
def custom_minimizer(fun, _x0, *args, **kwargs):
    # use least_squares on residuals in the custom minimizer instead of norm
    res = least_squares(residuals, _x0)
    res.fun = fun(res.x)  # but we need to insert the norm value for the successfully found minimum
    return res

# global: minimize f starting at x0
# then challenge via basinhopping with a custom_minimizer
ret = basinhopping(
    norm,
    x0,
    minimizer_kwargs={"method": custom_minimizer},
)
assert ret.success
```
