### ISSUE TITLE
DOC: inconsistent terminology at scipy.interpolate.griddata.html

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#19363]
### Issue with current documentation:

This page has:

```
LinearNDInterpolator
    Piecewise linear interpolant in N dimensions.
NearestNDInterpolator
    Nearest-neighbor interpolation in N dimensions.
```

That's three different words for the same thing - interpolator, interpolant, interpolation.  This will confuse beginners. If the the functions are called interpolators, why can't we just stick to this word in the descriptions?

**Comment by ev-br** [comment]
DOC clarification PRs are welcome
