### ISSUE TITLE
BUG: scipy.linalg.cossin fails for specific values of (p, q) and separate=False

### ISSUE THREAD

**Issue by sfcaracciolo** [scipy/scipy#19365]
### Describe your issue.

I found a case where the scipy.linalg.cossin function returns an incorrect diagonal block matrix (D) when separate=False. Using terminology like https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.cossin.html, if q > m - p then `assert np.allclose(U@D@Vt, X)` fails.

I developed a workaround in https://github.com/sfcaracciolo/cossin_wrapper. I use separate=True to build each matrix from theta.

### Reproducing Code Example

```python
import scipy  as sp 
import numpy as np 

# generate a random dimension m
rng = np.random.default_rng()
m = rng.integers(50, high=100)
p = np.random.randint(10, 40) # always p < m
q = np.random.randint(m-p+1, m-1) # always m-p < q < m 
# next line works
# q = np.random.randint(1, m-p-1) # always q < m-p
X = sp.stats.unitary_group.rvs(m) # random unitary matrix
U, D, Vt = sp.linalg.cossin(X, p=p, q=q, separate=False)
assert np.allclose(U@D@Vt, X)
```

### Error message

```shell
Traceback (most recent call last):
  File "E:\Repositorios\cossin_wrapper\tests\issue.py", line 13, in <module>
    assert np.allclose(U@D@Vt, X)
AssertionError
```

### SciPy/NumPy/Python version and system information

```shell
Python: 3.10.0
SciPy: 1.11.3
NumPy: 1.26.0
```

**Comment by ilayn** [comment]
That indeed smells like a bug. Since U and V are just block diags of the individual parts, probably the bug is living in the D generation part. Since you already did the exercise, do you have any insights on where the issue might be on the SciPy code? I will circle back to this at some point anyways but if you already know that would be great.

**Comment by sfcaracciolo** [comment]
> That indeed smells like a bug. Since U and V are just block diags of the individual parts, probably the bug is living in the D generation part. Since you already did the exercise, do you have any insights on where the issue might be on the SciPy code? I will circle back to this at some point anyways but if you already know that would be great.

Yes, the issue is in D and begins in line 199. The issue is to suppose that the inner blocks of D11, D12, D21 and D22 share some dimension between them. For instance,  in line 199, the position of Id12 depends on n11.

The correct shape of each inner block is in these figures:

![imagen](https://github.com/scipy/scipy/assets/41028670/a6472a3f-1c47-4783-aa6d-c3221c7913de)

![imagen](https://github.com/scipy/scipy/assets/41028670/dfe0635b-d87d-4705-8782-2fd03a6b04a9)

where $m_1 = m-p$, $m_2 = m-q$, $f_m(a,b) = min(a,b)-w$, $f_M(a,b) = max(a-b,0)$ and $w = min(p, q, m_1, m_2)$ ($r$ in scipy code)

**Comment by mdhaber** [comment]
This is closed by gh-20194.
