### ISSUE TITLE
BUG: problem importing libgfortran.5.dylib on macOS Sonoma

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#19387]
### Describe your issue.

On macOS Sonoma I use gfortran 12.2 from [here](https://github.com/fxcoudert/gfortran-for-macOS/releases/tag/12.2-ventura). When I try running the test suite there's an issue loading all the dylib that are linked to libgfortran. The `install_name` paths aren't being set correctly. I had no problem on Ventura.

I work around by setting `DYLD_LIBRARY_PATH`, but something in the build setup needs to be modified to fix the paths in the dylibs.

### Reproducing Code Example

```python
python dev.py test
```

### Error message

```shell
_____________________ ERROR collecting build-install/lib/python3.10/site-packages/scipy/integrate/tests/test_quadrature.py _____________________
ImportError while importing test module '/Users/andrew/Documents/Andy/programming/scipy/build-install/lib/python3.10/site-packages/scipy/integrate/tests/test_quadrature.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Users/andrew/miniconda3/envs/blas/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
scipy/integrate/__init__.py:93: in <module>
    from ._quadrature import *
scipy/integrate/_quadrature.py:8: in <module>
    from scipy.special import roots_legendre
scipy/special/__init__.py:777: in <module>
    from . import _ufuncs
E   ImportError: dlopen(/Users/andrew/Documents/Andy/programming/scipy/build-install/lib/python3.10/site-packages/scipy/special/_ufuncs.cpython-310-darwin.so, 0x0002): Library not loaded: @rpath/libgfortran.5.dylib
E     Referenced from: <1D1D80A8-B3A5-3AC7-9FF3-1E845ABF6186> /Users/andrew/Documents/Andy/programming/scipy/build-install/lib/python3.10/site-packages/scipy/special/_ufuncs.cpython-310-darwin.so
E     Reason: tried: '/Users/andrew/miniconda3/envs/blas/bin/../lib/libgfortran.5.dylib' (no such file), '/Users/andrew/miniconda3/envs/blas/bin/../lib/libgfortran.5.dylib' (no such file)
_____________________ ERROR collecting build-ins
```

### SciPy/NumPy/Python version and system information

```shell
python 3.10, macOS Sonoma
gfortran 12.2.0

(blas) 192-168-1-107:scipy andrew$ clang --version
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by rgommers** [comment]
Hmm. Probably related to gh-19357. If you do a full build after `export LDFLAGS=-Wl,-ld_classic`, does the problem go away?

**Comment by rgommers** [comment]
> The `install_name` paths aren't being set correctly.

I'm not actually sure what this is referring to, since `install_name` isn't a code/variable name we use in build definitions. 

I assume `/Users/andrew/miniconda3/envs/blas/bin/../lib/libgfortran.5.dylib` does exist?

**Comment by andyfaff** [comment]
Sorry, the rpaths.

**Comment by rgommers** [comment]
It looks like those gfortran builds simply don't support macOS 14 (Sonoma) yet. https://github.com/fxcoudert/gfortran-for-macOS/releases shows the latest release is explicitly for macOS 13 (Ventura). There is another bug report at  https://github.com/fxcoudert/gfortran-for-macOS/issues/60.

Maybe the `export LDFLAGS=-Wl,-ld_classic` workaround works? If so, we can incorporate that flag in our build until the problem is solved. If it doesn't work, I don't think there's anything that can be done in SciPy to fix this.

**Comment by andyfaff** [comment]
> Maybe the export LDFLAGS=-Wl,-ld_classic workaround works? If so, we can incorporate that flag in our build until the problem is solved.

The workaround works.

> I assume /Users/andrew/miniconda3/envs/blas/bin/../lib/libgfortran.5.dylib does exist?

The file *doesn't exist*.

The linked issue for the gfortran has little to no illumination on the issue.

**Comment by lucascolley** [comment]
what command are you using @Yijia-Jiang ? The linked PR added `-Wl,-ld_classic` link args for `apple-darwin` machines to our build setup.
