### ISSUE TITLE
BUG: a hang on 32-bit Linux with `scipy-openblas32` in CI

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#19381]
Found when working on gh-19380. Reproducer:
```
docker pull quay.io/pypa/manylinux2014_i686
docker run -v $(pwd):/scipy --platform=linux/i386 quay.io/pypa/manylinux2014_i686 /bin/bash -c "cd /scipy && \
        uname -a && \
        python3.9 -m venv test && \
        source test/bin/activate && \
        python -m pip install doit click rich_click pydevtool meson ninja && \
        python -m pip install numpy==1.22.4 cython==0.29.35 pybind11 pytest pytest-timeout pytest-xdist pytest-env 'Pillow<10.0.0' mpmath pythran pooch meson hypothesis scipy-openblas32 && \
        python dev.py build --use-scipy-openblas && \
        python dev.py test -v -s cluster"
```

The 32-bit Linux CI job we have passes on `main` currently - that job is using OpenBLAS `0.3.21.dev`.

The one BLAS function that is called inside `kmeans2` is `sgemm`/`dgemm`: https://github.com/scipy/scipy/blob/8a130d34ed741995b2d98196e5ff24969e8d5ca1/scipy/cluster/_vq.pyx#L46-L53

Could be a bug in that Cython code of course. EDIT: other `cluster` and `linalg` tests are also hanging - it's not a code issue.

**Comment by rgommers** [comment]
Ah, I think there is nothing wrong with either our Cython code or OpenBLAS, but we're getting bitten here by `dlopen`'ing the OpenBLAS shared library with `ctypes` and `RTLD_GLOBAL`. xref https://github.com/MacPython/openblas-libs/pull/87#issuecomment-1277615608 and https://github.com/MacPython/openblas-libs/pull/120.

That job builds `numpy` 1.22.4 from source, and in `main` there's some manual manipulation to put `openblas.so` in `/usr/local/lib/` for the SciPy build - which has a side effect of having the NumPy build picking up that exact same wheel. While in the Docker reproducer above, NumPy fails to find a BLAS library and hence uses `lapack_lite`.

**Comment by rgommers** [comment]
Indeed, tests pass if I build both numpy and scipy against the same `scipy-openblas32`: 
```
docker run -v $(pwd):/scipy --platform=linux/i386 quay.io/pypa/manylinux2014_i686 /bin/bash -c "cd /scipy && \
        python3.9 -m venv venv && \
        source venv/bin/activate && \
        python -m pip install -U pip && \
        python -m pip install doit click rich_click pydevtool meson-python ninja scipy-openblas32 cython==3.0.2 && \
        python -c 'import scipy_openblas32 as o; print(o.get_pkg_config())' > scipy-openblas.pc && \
        export PKG_CONFIG_PATH=/scipy && \
        python -m pip install git+https://github.com/rgommers/numpy.git@debug-linux32-issue --no-build-isolation && \
        echo 'import scipy_openblas32' > venv/lib/python3.9/site-packages/numpy/_distributor_init_local.py && \
        python -m pip install pybind11 pytest pytest-timeout pytest-xdist pytest-env pythran pooch hypothesis && \
        python dev.py build --use-scipy-openblas && \
        python dev.py test -v -s cluster"
```

**Comment by rgommers** [comment]
Regarding the BLAS (and LAPACK) libraries used by NumPy and SciPy installed into the same env:

1. A single BLAS library that both NumPy and SciPy are built against and depend upon is the best situation (conda-forge, Spack, Nix, Homebrew and every Linux distro are in this situation),
2. Both NumPy and SciPy vendoring a name-mangled BLAS library (via `auditwheel` & co) works,
3. One of NumPy/SciPy containing a vendored name-mangled BLAS and the other one using `scipy-openblas32`/`64` works too,
4. Having both using the same `scipy-openblas32`/`64` works too,
5. Having both use _different and non-mangled_ BLAS's does not work, it leads to symbol clashes.

Next steps:
- Getting rid of `tools/openblas_support.py` would be great. This can be done, I think it only needs the ability in `scipy_openblas32` to write out a pkg-config file that doesn't do the `libopenblas_python` thing but contains the normal link flags. Then it's a 1:1 replacement, and we can simply use `pip` instead of the hardcoded logic for downloading the right binary in `openblas_support.py` without changing anything else to how we build wheels.
- After that, I think we need symbol prefixes (maybe `scipywheel_`?) in the scipy-openblas wheels, to avoid the problem with (5) above. I was originally not in favor of symbol prefixes to not make things harder - but I think I was wrong, they're necessary.
  - It's not entirely clear to me if that will be enough - we also have to worry about `libgcc` & co.

The wheels are still a big win already though; upgrading OpenBLAS used to be a pain, and now it comes for free, and we can switch between versions with a familiar `pip install ...` interface.

**Comment by mattip** [comment]
The current pkg-config file is created [here](https://github.com/MacPython/openblas-libs/blob/80fcba37ab19b00d8087c76234f23c53a4fcfff9/local/scipy_openblas64/__init__.py#L58) and can emit whatever flags we choose. Right now it is set up to emit the `64_` suffix and set the numpy define for 64-bit interfaces, and not do that for 32-bit interfaces. 

I think it should be relatively straightforward to package the scipy-openblas sharedobjects/dlls into the scipy wheel. I am not sure why we would need a new prefix since cibuildwheel uses [auditwheel/delocate/devolve](https://cibuildwheel.readthedocs.io/en/stable/options/#repair-wheel-command) to mangle the file names and package them into the wheel the same as now. So if there is currently no conflict, there should be no conflict new conflict.

**Comment by mattip** [comment]
Ahh, I think I see. If both scipy and numpy are installed through wheels, then there is no conflict. The conflict is specifically when one uses the scipy-openblas wheel in development mode, which uses `RT_GLBL` in `_distributor_init` to pre-load the OpenBLAS symbols. Technically we could add prefix symbols to the scipy-openblas builds, it might cause some confusion when debugging.

**Comment by rgommers** [comment]
> The conflict is specifically when one uses the scipy-openblas wheel in development mode,

Yes indeed - and it may also happen if the environment contains a third package which also uses a BLAS library. E.g. a conda env with pytorch installed.

**Comment by rgommers** [comment]
This was fixed by adding a `scipy_` prefix to all symbols in `scipy-openblas32` and `scipy-openblas64`. So closing.
