### ISSUE TITLE
CI, MAINT: known CI issue with NumPy main/latest

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#19406]
Example failure: https://github.com/scipy/scipy/actions/runs/6555137521/job/17803175138?pr=19402

Suspected/related issues:
- https://github.com/data-apis/array-api-compat/pull/63
- and if you add that patch in, then several failures that seem `pybind11`-related, though I'm not 100 % sure on my diagnosis: https://github.com/pybind/pybind11/issues/4886 (update: need a new stable release for that fix, works with their `master` branch)

**Comment by ngoldbaum** [comment]
In the CI log it looks like pybind11 is getting installed from the last pip release in July which doesn't have the fix for this. I bet installing pybind11 from the git repo will fix this.

**Comment by tylerjereddy** [comment]
Ok, that fixes most of the issues, I still get the same failure with `matplotlib/tri/_triangulation.py:124: in get_cpp_triangulation` doing the same thing, so maybe whatever that is needs to get rebuilt with latest `pybind11` branch as well.

Anyway, sounds like the ecosystem has branches with fixes, but probably makes sense to keep this issue/reminder open for now.
