### ISSUE TITLE
BUG: Poor results when using weibull_min.fit distribution

### ISSUE THREAD

**Issue by giuliasaccomano** [scipy/scipy#19407]
### Describe your issue.

Hello!
Here I report some columns of the table I am working on: [table.csv](https://github.com/scipy/scipy/files/13042774/table.csv)

For all other columns (not shown for brevity) the function weibull_min.fit works perfectly, but for the column 'Anisotropy' it does not. There is no error message, only poor results.

I read in another "issues" (https://github.com/scipy/scipy/issues/11806) that there might be some problem with the local minima optimization, but here I just can't force the output. How should I proceed to solve the problem in this case?

### Reproducing Code Example

```python
from scipy.stats import weibull_min
import pandas as pd

data = pd.read_csv('table.csv')

data_anis = data['Anisotropy']
data_elong = data['Elongation']
shape_anis, loc_anis, scale_anis = weibull_min.fit(data_anis, loc=0)
shape_elong, loc_elong, scale_elong = weibull_min.fit(data_elong, loc=0)
print(shape_anis, loc_anis, scale_anis)
print(shape_elong, loc_elong, scale_elong)
```

### Error message

```shell
# poor results 
219739290.20131522 -22334557.974036843 22334558.692912437
# good results
3.3109592283089877 0.10286668213350167 0.559831643287328
```

### SciPy/NumPy/Python version and system information

```shell
1.11.2 1.26.0 sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0)
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "0.29.36",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.13.1",
      "include directory": "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-build-env-ltcmez9y\\overlay\\Lib\\site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2",
      "pc file directory": "c:/opt/64/lib/pkgconfig"
    },
    "lapack": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21.dev",
      "detection method": "pkgconfig",
      "include directory": "/c/opt/64/include",
      "lib directory": "/c/opt/64/lib",
      "openblas configuration": "USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2",
      "pc file directory": "c:/opt/64/lib/pkgconfig"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.10.4",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\cibw-run-j5_khsjf\\cp311-win_amd64\\build\\venv\\Scripts\\python.exe",
    "version": "3.11"
  }
}
```

**Comment by mdhaber** [comment]
Also in that issue: the optimization may be doing the right thing, but the unusual looking parameter values fit the data better than normal-looking numbers. Could you plot the fitted distribution against a histogram?

If you want to put bounds on the parameters, you can use [`scipy.stats.fit`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fit.html).

**Comment by giuliasaccomano** [comment]
Yes, I could plot the histograms:
![image](https://github.com/scipy/scipy/assets/66478057/e2352a6d-316c-41e0-b3b6-849fb2c1748f)

The former plot seems well fitted but Weibull results are strange. 

I am triìying right now to provide and initial guess. I will keep you updated. Thanks

**Comment by giuliasaccomano** [comment]
> Also in that issue: the optimization may be doing the right thing, but the unusual looking parameter values fit the data better than normal-looking numbers. See [#11806 (comment)](https://github.com/scipy/scipy/issues/11806#issuecomment-783754570) and [#11806 (comment)](https://github.com/scipy/scipy/issues/11806#issuecomment-1037853152), for example. This is an inherent "feature" of maximum likelihood estimation for some distributions. Could you plot the fitted distribution against a histogram?
> 
> The simplest thing you can do is provide a guess manually. It looks like you've done that with `loc=0`, but you could try adding a guess for the scale, too. If possible, fix one of the parameters (e.g. `floc=0`, not `loc=0`). Or, if you don't want to fix any but you want to put bounds on the parameters, you can use [`scipy.stats.fit`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fit.html). It will also let you try maximum spacing estimation, which might work better than MLE in this case.



> Also in that issue: the optimization may be doing the right thing, but the unusual looking parameter values fit the data better than normal-looking numbers. See [#11806 (comment)](https://github.com/scipy/scipy/issues/11806#issuecomment-783754570) and [#11806 (comment)](https://github.com/scipy/scipy/issues/11806#issuecomment-1037853152), for example. This is an inherent "feature" of maximum likelihood estimation for some distributions. Could you plot the fitted distribution against a histogram?
> 
> The simplest thing you can do is provide a guess manually. It looks like you've done that with `loc=0`, but you could try adding a guess for the scale, too. If possible, fix one of the parameters (e.g. `floc=0`, not `loc=0`). Or, if you don't want to fix any but you want to put bounds on the parameters, you can use [`scipy.stats.fit`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fit.html). It will also let you try maximum spacing estimation, which might work better than MLE in this case.

Yes, I could plot the histograms:
![image](https://github.com/scipy/scipy/assets/66478057/e2352a6d-316c-41e0-b3b6-849fb2c1748f)

The former plot seems well fitted but Weibull results are strange. 

I am triìying right now to provide and initial guess. I will keep you updated. Thanks

**Comment by giuliasaccomano** [comment]
> > Also in that issue: the optimization may be doing the right thing, but the unusual looking parameter values fit the data better than normal-looking numbers. See [#11806 (comment)](https://github.com/scipy/scipy/issues/11806#issuecomment-783754570) and [#11806 (comment)](https://github.com/scipy/scipy/issues/11806#issuecomment-1037853152), for example. This is an inherent "feature" of maximum likelihood estimation for some distributions. Could you plot the fitted distribution against a histogram?
> > The simplest thing you can do is provide a guess manually. It looks like you've done that with `loc=0`, but you could try adding a guess for the scale, too. If possible, fix one of the parameters (e.g. `floc=0`, not `loc=0`). Or, if you don't want to fix any but you want to put bounds on the parameters, you can use [`scipy.stats.fit`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fit.html). It will also let you try maximum spacing estimation, which might work better than MLE in this case.
> 
> > Also in that issue: the optimization may be doing the right thing, but the unusual looking parameter values fit the data better than normal-looking numbers. See [#11806 (comment)](https://github.com/scipy/scipy/issues/11806#issuecomment-783754570) and [#11806 (comment)](https://github.com/scipy/scipy/issues/11806#issuecomment-1037853152), for example. This is an inherent "feature" of maximum likelihood estimation for some distributions. Could you plot the fitted distribution against a histogram?
> > The simplest thing you can do is provide a guess manually. It looks like you've done that with `loc=0`, but you could try adding a guess for the scale, too. If possible, fix one of the parameters (e.g. `floc=0`, not `loc=0`). Or, if you don't want to fix any but you want to put bounds on the parameters, you can use [`scipy.stats.fit`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fit.html). It will also let you try maximum spacing estimation, which might work better than MLE in this case.
> 
> Yes, I could plot the histograms: ![image](https://user-images.githubusercontent.com/66478057/276634389-e2352a6d-316c-41e0-b3b6-849fb2c1748f.png)
> 
> The former plot seems well fitted but Weibull results are strange.
> 
> I am trying right now to provide an initial guess. I will keep you updated. Thanks

Great! By providing a similar initial guess, it works fine now! Thank you for your help

![image](https://github.com/scipy/scipy/assets/66478057/cf3cd91a-9d3e-4316-84e8-03c70862b74a)
