### ISSUE TITLE
BUG: milp solver gives results violating a constraint

### ISSUE THREAD

**Issue by ericqu** [scipy/scipy#19421]
### Describe your issue.

For a simple problem, the milp solver gives a result that violates a constraint.
See the code below. The fourth constraint ([1,2,0]) should be below 101, although the _xs_ proposed by the solver are 17, 50, 51, and 1*17+2*50, giving 117, above 101.
I tested on two sets of versions/packages described below they both give the same results. 

I am a little new to this optimization package, so I might have misunderstood something in the documentation, if this is the case my apologies. 

### Reproducing Code Example

```python
import numpy as np
import scipy.optimize
from scipy.optimize import milp

c = np.array([ 1, 1, 1])
A = np.array([
    [5, 0, 0], # 5 L                >> No
    [6, 0, 0], # 6 L                >> Yes
    [0, 2, 0], # 0 L + 2 M          >> No
    [1, 2, 0], # 1 L + 2 M          >> No
    [2, 2, 0], # 2 L + 2 M          >> Yes
    [0, 3, 0], #       3 M          >> Yes
    [0, 0, 1], #             1 H    >> No
    [1, 0, 1], # 1 L +       1 H    >> No
    [0, 1, 1], # 0 L + 1 M + 1 H    >> Yes
    [0, 0, 2], # 0 L + 0 M + 1 H    >> Yes
])

b = np.array([-101, 101,    -101,   -101,   101,    101,    -101,   -101,   101,    101 ])

res = milp(c=c, integrality = np.ones_like(c), constraints=scipy.optimize.LinearConstraint(A, b), 
           options={'presolve':False} )

print('x values:', res.x)
print('minimized sum:', res.fun)
print('Status:', res.status)
print(res.message)
print('numpy:', np.__version__, 'scipy:', scipy.__version__)
```

### Error message

```shell
x values: [17. 50. 51.]
minimized sum: 118.0
Status: 0
Optimization terminated successfully. (HiGHS Status 7: Optimal)
numpy: 1.24.3 scipy: 1.10.1

and 

x values: [17. 50. 51.]
minimized sum: 118.0
Status: 0
Optimization terminated successfully. (HiGHS Status 7: Optimal)
numpy: 1.26.0 scipy: 1.11.3
```

### SciPy/NumPy/Python version and system information

```shell
python: 3.11.6, numpy: 1.26.0,  scipy: 1.11.3
python: 3.9.5, numpy: 1.24.3, scipy: 1.10.1
```

**Comment by mdhaber** [comment]
The second argument of [`LinearConstraint`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.LinearConstraint.html) is the lower limit of `A@x`. If you meant to express $Ax < b$, you need `constraints=scipy.optimize.LinearConstraint(A, ub=b)`.
