### ISSUE TITLE
No entry to import `mvnun` subroutine

### ISSUE THREAD

**Issue by mahdi-kz** [scipy/scipy#19441]
### Describe your issue.

Using the last release we have imported and used `mvnun` function from `scipy.stats.mvn` which raises a DepricationWarning.
It is supposed to use it from `scipy.stats` namespace, however, there is no import in [__init__.py](https://github.com/scipy/scipy/blob/6d197d1c5b7cd1184eb1b515b5de4f5a9ac858a2/scipy/stats/__init__.py)
It seems that importing from [__init__.py](https://github.com/scipy/scipy/blob/6d197d1c5b7cd1184eb1b515b5de4f5a9ac858a2/scipy/stats/__init__.py) or [_stats_py.py](https://github.com/scipy/scipy/blob/6d197d1c5b7cd1184eb1b515b5de4f5a9ac858a2/scipy/stats/_stats_py.py) is missed.

### Reproducing Code Example

```python
import scipy.stats.mvn
scipy.stats.mvn(....) raises a warning

and

import scipy.stats
scipy.stats.mvnun(....) raises an AttributeError

from scipy.stats import mvnun raises an ImportError
```

### Error message

```shell
AttributeError: module 'scipy.stats' has no attribute 'mvnun'
```

### SciPy/NumPy/Python version and system information

```shell
1.11.3 1.26.0 sys.version_info(major=3, minor=11, micro=5, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-358nkn7q/overlay/lib/python3.11/site-packages/pythran
    version: 0.14.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp311-cp311/bin/python
  version: '3.11'
```

**Comment by mdhaber** [comment]
It looks like the second line of code, which raises the warning, is intended to be `scipy.stats.mvn.mvnun`?
This is already fixed in main. The new message in this case is:
> DeprecationWarning: `scipy.stats.mvn.mvnun` is deprecated along with the `scipy.stats.mvn` namespace. `scipy.stats.mvn.mvnun` will be removed in SciPy 1.13.0, and the `scipy.stats.mvn` namespace will be removed in SciPy 2.0.0.

**Comment by mahdi-kz** [comment]
Yes, it is addressed in main, however, with the last release, the warning is raised and there is no way to suppress the warning. I want to know how to use this version, import the method, and not get the warning. Do you have a plan to update the latest release 3.11?

**Comment by rkern** [comment]
It is not a public interface, and we don't support it long term. It may disappear any time after scipy 2.0. If you must use it, even under those conditions, use `scipy.stats._mvn.mvnun`.

**Comment by mahdi-kz** [comment]
So, for a stable long term use, you recommend me to wait for the next release. Am I right?

**Comment by mahdi-kz** [comment]
Aah! I got it. Thank you for your prompt support

**Comment by rkern** [comment]
It's relatively self-contained to extract into its own package or vendorize into your own codebase if you have the Fortran compiler toolchain you'd need to build scipy from source.

Eventually, it will be replaced by an updated algorithm that's currently implemented (albeit still private) here: https://github.com/scipy/scipy/blob/main/scipy/stats/_qmvnt.py#L204

We are holding off on replacing `mvnun` with it until we can Pythranize it, which in turn is waiting for necessary improvements to Pythran. But if you need something that's easier to vendorize into your own code, that would probably be it.

**Comment by mahdi-kz** [comment]
Thank you for your kindness and support :-)
