### ISSUE TITLE
BUG: Flatten SciPy lil_matrix without converting to dense to avoid memory error

### ISSUE THREAD

**Issue by mrgransky** [scipy/scipy#19455]
### Describe your issue.

I would like to flatten my sliced array without converting it to dense in order to avoid memory error:

For smaller sizes, I can simply do `mtx.getrowview(0).toarray().flatten()` but for larger sizes, I do not want to convert to dense.

What is the easy and memory efficient approach to flatten a scipy sparse `lil_matrix`?

### Reproducing Code Example

```python
import numpy as np
import scipy
print(np.__version__, scipy.__version__) # numpy: 1.23.5 scipy: 1.11.3

mtx = scipy.sparse.lil_matrix((int(2e8), int(4e9)), dtype=np.float32) # very large lil_matrix    
flat_mtx = mtx.getrowview(0).flatten() # sliced example: row: 0
```

### Error message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'lil_matrix' object has no attribute 'flatten'
```

### SciPy/NumPy/Python version and system information

```shell
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()
1.11.2 1.26.1 sys.version_info(major=3, minor=9, micro=12, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-ucip512m/overlay/lib/python3.9/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp39-cp39/bin/python
  version: '3.9'
```

**Comment by dschult** [comment]
I will take this as a request for a 1d sparse array.
Note that `A.getrowview(j)` gets the jth row as a sparse matrix. So it is most of what you want, but not a 1d array.
What features of a 1d array do you need? You might be able to get them from the 1xN sparse matrix object.

There is currently some progress on a 1d-sparse-array.  #18530 is a start toward that goal. 
It might help me to know what aspects of being `flat` you want. 
Iteration over values? Ability to reshape?  We're definitely including those. 

Are there other features you want the flattened slices to have?

**Comment by mrgransky** [comment]
@dschult I actually have an sparse matrix with this specification:

```
#sp_mtx  # load my sparse matrix from disk
print(f"{type(sp_mtx)} {sp_mtx.shape} {sp_mtx.dtype} byte size[count]: {sum([sys.getsizeof(i) for i in sp_mtx.data])/1e6:.2f} MB")
<class 'scipy.sparse._lil.lil_matrix'> (162837, 26515902) float32 byte size[count]: 4316.62 MB
```
and would like to iterate over each row for some customized mathematical operations, e.g., multiplications, divisions and sum.
Therefore, I though flatten could be easily done in order to apply multiplication to another numpy 1D array for instance.

Right now, I can do `np.squeeze(sp_mat_pkl.getrowview(0).toarray())` which is faster than normal `.flatten()` but I thought it'd be nice to have the method directly from scipy sparse rather than converting to dense first and then squeeze or flatten.

**Comment by perimosocordiae** [comment]
If all you're doing with each row is math, then I would recommend converting your sparse matrix to CSR format (`sp_mat_pkl.tocsr()`). This format has the best support for arithmetic as well as row-wise operations. You may be able to avoid explicitly iterating over rows entirely.

As this is more of a usage question rather than a bug report, I'll close this now.
