### ISSUE TITLE
BUG: optimize._numdiff.approx_derivative fails if the user provided function modifies an argument in place and returns that argument

### ISSUE THREAD

**Issue by Nin17** [scipy/scipy#19463]
### Describe your issue.

I'm trying to optimise a function that modifies one of its arguments in place and returns that modified argument akin to the 'out' kwarg available in many numpy functions, however this fails if a function to calculate the Jacobian is not also provided, as `scipy.optimize._numdiff.approx_derivative` returns a zero array:

### Reproducing Code Example

```python
from scipy.optimize import least_squares, _numdiff
import numpy as np

rng = np.random.default_rng(0)

matrix = rng.random((3, 2))
_x = rng.random(2)
vector = matrix @ _x

_fvec = np.zeros_like(vector)


def residuals(x, A, b, fvec):
    np.matmul(A, x, out=fvec)
    fvec -= b
    # return fvec  # Uncomment this line and it fails if jacobian is not provided
    return fvec.copy()

def jacobian(x, A, b, fvec):
    return A

print(least_squares(residuals, np.ones_like(_x), jac = jacobian, args=(matrix, vector, _fvec)).x)
print(least_squares(residuals, np.ones_like(_x), args=(matrix, vector, _fvec)).x)
print(_x)

print(_numdiff.approx_derivative(residuals, np.ones_like(_x), args=(matrix, vector, _fvec)))
```
Output:
```
[0.60663578 0.72949656]
[0.60663577 0.72949657]
[0.60663578 0.72949656]
[[0.63696169 0.26978671]
 [0.04097352 0.01652764]
 [0.81327024 0.91275558]]
```
Output with the line `return fvec` uncommented:
```
[0.60663578 0.72949656]
[1. 1.]
[0.60663578 0.72949656]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version and system information

```shell
1.11.3 1.24.3 sys.version_info(major=3, minor=11, micro=5, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /Users/chris/anaconda3/include
    lib directory: /Users/chris/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /Users/chris/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /Users/chris/anaconda3/include
    lib directory: /Users/chris/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /Users/chris/anaconda3/lib/pkgconfig
    version: 0.3.21
  pybind11:
    detection method: pkgconfig
    include directory: /Users/chris/anaconda3/include
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: arm64-apple-darwin20.0.0-clang
    linker: ld64
    name: clang
    version: 12.0.0
  c++:
    commands: arm64-apple-darwin20.0.0-clang++
    linker: ld64
    name: clang
    version: 12.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: /var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_1b7r8zpma8/croot/scipy_1696543295098/_build_env/bin/arm64-apple-darwin20.0.0-gfortran
    linker: ld64
    name: gcc
    version: 11.2.0
  pythran:
    include directory: ../../../../../../../../../../../Users/chris/anaconda3/lib/python3.11/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /Users/chris/anaconda3/bin/python
  version: '3.11'
```

**Comment by andyfaff** [comment]
This occurs because `approx_derivative` is directly using the output of `residuals` to calculate differences. Because numpy arrays are passed by reference into functions you're overwriting arrays used by `approx_derivative`.

This isn't a great explanation, but the following example demonstrates what I mean:

``` python
rng = np.random.default_rng(0)
matrix = rng.random((3, 2))
_x = rng.random(2)
vector = matrix @ _x
_fvec = np.zeros_like(vector)

x = np.ones(2)
h0 = np.array([0.001, 0])
h1 = np.array([0, 0.001])

def residuals(x, A, b, fvec):
    np.matmul(A, x, out=fvec)
    fvec -= b
    return fvec

f0 = residuals(x, matrix, vector, _fvec)
print(f0)

f1 = residuals(x + h0, matrix, vector, _fvec)
print(f0, f1)

f2 = residuals(x + h1, matrix, vector, _fvec)
print(f0, f1, f2)
print(id(f0), id(f1), id(f2))
```

```
output
[0.32353617 0.0205883  0.56681494]
[0.32417314 0.02062927 0.56762821] [0.32417314 0.02062927 0.56762821]
[0.32380596 0.02060483 0.56772769] [0.32380596 0.02060483 0.56772769] [0.32380596 0.02060483 0.56772769]
4559091440 4559091440 4559091440
```

If you look at the last two lines of output you see that `f0`, `f1`, `f2` are all equal. Indeed, that's because they're all the same array (same `id` numbers). That's because `_fvec` is being modified in place in `residuals` each time it's called and it's also the array returned by residuals. `approx_derivative` calculates a zero gradient because `f0`, `f1`, `f2` are equal (in fact they're the same array).

Now we come to the *"fix"*. It should be possible for `approx_derivative` to copy the output of the user function, e.g. `f0 = np.copy(residuals(x, matrix, vector, _fvec))`, but is that wasteful for the overwhelming majority of occasion where the output of the function isn't being overwritten in place. This situation seems rare to me, is there a reason why this example can't just return `fvec.copy()`?

**Comment by Nin17** [comment]
Well, I'm was trying to compare using scipy to using minpack, in which the residuals are allocated once and modified in place at each iteration, so was trying to do the equivalent in scipy. This also doesn't work with `leastsq` which calls minpack. I've also made [this stackoverflow question](https://stackoverflow.com/questions/77412923/how-to-modify-an-argument-in-place-and-return-it-in-scipy-optimize-least-squares) about it. As for the "fix", I don't think you'd have to copy the output from the user function every time the function is called, for instance the current implementation for "2-point" does this:
```
    for i in range(h.size):
        if method == '2-point':
            x = x0 + h_vecs[i]
            dx = x[i] - x0[i]  # Recompute dx as exactly representable number.
            df = fun(x) - f0
```
which could equivalently be something like:
```
    _f0 = f0.copy()
    df = np.empty_like(f0)

    for i in range(h.size):
        if method == "2-point":
            x = x0 + h_vecs[i]
            dx = x[i] - x0[i]  # Recompute dx as exactly representable number.
            np.subtract(fun(x), _f0, out=df)
```
which gives the same result for both ways of writing the residual function and has equivalent performance (at least with this example) as the original implementation and copying the residuals in the function.

**Comment by andyfaff** [comment]
It's quite possible that the length of residuals be very large, and for `x` to be very large. In which case making an extra 2D array `f0.copy()` could take up a lot of memory.

What advantage were you hoping to get by modifying the residuals in-place?

**Comment by Nin17** [comment]
`f0` is a 1d array? I was just trying to make a more direct comparison of using the scipy wrappers of minpack and using minpack itself and in minpack you modify the residuals in place, so was trying to do the same in scipy.

**Comment by andyfaff** [comment]
In your case f0 is a 1D array, yes. The trouble is that in the process of calculating `fun(x)` `f0` is overwritten because you're also passing that array into `fun`. That makes the difference 0.

**Comment by Nin17** [comment]
I believe `f0` is [always 1D](https://github.com/scipy/scipy/blob/4d790c14456f72ef7a56aafa0dcc728e5bba22fe/scipy/optimize/_numdiff.py#L476):
```
    def fun_wrapped(x):
        f = np.atleast_1d(fun(x, *args, **kwargs))
        if f.ndim > 1:
            raise RuntimeError("`fun` return value has " "more than 1 dimension.")
        return f

    if f0 is None:
        f0 = fun_wrapped(x0)
    else:
        f0 = np.atleast_1d(f0)
        if f0.ndim > 1:
            raise ValueError("`f0` passed has more than 1 dimension.")
```
Yes, I understand that I'm modifying the array in place...

**Comment by andyfaff** [comment]
It is always 1D. But you're modifying it in place which causes the issue. Why do you need to do that?

**Comment by Nin17** [comment]
>Well, I'm trying to compare using scipy to using minpack, in which the residuals are allocated once and modified in place at each iteration, so was trying to do the equivalent in scipy. This also doesn't work with leastsq which calls minpack.

**Comment by josef-pkt** [comment]
I don't think that scipy or other packages can or should handle this.
We have to rely on values not being modified while the computation needs to hold on to the returns from repeated calls to a user function.

For simple forward difference computation we could theoretically hold on to the previous value, but centered differences or using higher order approximation to the differences or second derivatives always need several calls to the function.

**Comment by Nin17** [comment]
In the minpack python bindings, you modify fvec in place, like you would in fortran: see the [minpack python tests](https://github.com/fortran-lang/minpack/blob/main/python/minpack/test_library.py)

**Comment by josef-pkt** [comment]
python is not fortran
If a function is inlined and hardcoded without options, then it can be optimized for the special hardcoded case.
If we work with different function, then it gets complicated, error-prone and fragile if we cannot rely on "standard" behaviour.
For example adding centered numerical derivatives would be easy in python, but would require dropping the inplace modification in fortran.
(Besides scipy.optimize.least_squares has many other options and methods besides the minpack version and IMO it would be too much work to always make sure that the user functions is never called twice in a row.)

(I spend a lot of time bug hunting in scipy.stats and statsmodels for objects that modify inplace or hold state that might become incorrect. And the source for those bugs are very difficult to spot.)
