### ISSUE TITLE
Bad efficiency of global optimization methods

### ISSUE THREAD

**Issue by fingoldo** [scipy/scipy#19467]
### Describe your issue.

Working on a toy example mentioned in #19185, where I found that local optimization fails, as suggested, I proceeded to using global optimization methods available in Scipy.

To provide more background, the type of curves I want to minimize/maximize relate to cross-validated performances of a machine learning estimator given a particular number of features. Therefore, in my understanding at least, solving this problem will lead to efficient feature selection. Currently, recursive feature elimination in sklearn is implemented by brute force traversal of all possible nfeatures (optionally with a step), that made me wonder why, as most of the time ML performance curves vs nfeatures can have 2 main types of shapes (instantly growing with saturation, if all features are important, or, most realistic, peaking at some value then gradually dropping as noisy features step in more and more).

I tried all global optimizers available in Scipy, and was surprised by their poor performance on my toy problem.

Maybe I am missing something and the community can recommend to me some good settings instead of default?

Otherwise, it might be an indication that current methods need improving.

![image](https://github.com/scipy/scipy/assets/16359856/e985e362-ff6f-4608-8b1d-2e065bc631bf)
![image](https://github.com/scipy/scipy/assets/16359856/789f66b0-937a-4315-a45e-7635dd95f84a)
![image](https://github.com/scipy/scipy/assets/16359856/95cbbd99-cd4d-4c76-a678-67fa242bd116)
![image](https://github.com/scipy/scipy/assets/16359856/a1db74a2-27fd-457e-9a3f-3f7ff9b92cec)
![image](https://github.com/scipy/scipy/assets/16359856/d3ded5e9-138b-4e98-96eb-932eb5acf6c2)
![image](https://github.com/scipy/scipy/assets/16359856/157f0af8-dbf5-415b-a4c0-305fadf105e4)
![image](https://github.com/scipy/scipy/assets/16359856/487495e2-a1c9-4ac5-90e8-4c5497796b9b)

### Reproducing Code Example

```python
import numpy as np
from matplotlib import pyplot as plt
from scipy.optimize import minimize_scalar
from scipy.optimize import direct, differential_evolution, basinhopping, shgo, brute, dual_annealing

someimportant_scores = np.hstack([np.arange(0, 10, 1), np.arange(10, 7, -0.05), np.arange(7, 7.5, 0.001)])
plt.plot(
    someimportant_scores,
)
setting = "only some vars are important"
plt.title(setting)

def return_scores(index: float, scores: Sequence, cache: dict, maximize: bool = False) -> float:
    """Creates a callable object able to return an element from some scores array by requested index.
    Index can possibly be a float, so it gets truncated to an int first.
    Each integer index is tracked in the cache dict to
        1) know how many "true" evals which trigger expensive evaluation call happened
        2) serve as a cache
    """
    true_index = int(index)

    if true_index in cache:
        return cache[true_index]

    if true_index >= len(scores):
        res = scores[-1]
    elif true_index < 0:
        res = scores[0]
    else:
        res = scores[true_index]

    cache[true_index] = res

    return -res if maximize else res


def optimize_scores(scores: Sequence, maximize: bool = True, method: object = minimize_scalar)->None:
    """Finds extremum of some numerical sequence in scores array, plots search path."""
    
    cache = {}
    f = partial(return_scores, scores=scores, cache=cache, maximize=maximize)
    if method == minimize_scalar:
        res = minimize_scalar(f, bounds=[0 - 1, len(scores) + 1], method="bounded", options=dict(disp=True))  # , bracket=[0 - 1, len(scores) + 1]
    else:

        if method == basinhopping:
            res = method(
                f,
                [len(scores)],
            )
        elif method == brute:
            res = method(
                f,
                ranges=[[0 - 1, len(scores) + 1]],
            )
        else:
            res = method(
                f,
                bounds=[[0 - 1, len(scores) + 1]],
            )

    plt.plot(scores)
    plt.scatter(cache.keys(), [f(el) for el in cache.keys()], c="r")
    plt.title(f"{setting}, {method.__name__}, {len(cache.keys())} fevals")
    plt.show()

    return res

for method in (minimize_scalar, direct, shgo, differential_evolution, basinhopping, brute, dual_annealing):
    print(optimize_scores(scores=someimportant_scores, method=method))
```

### Error message

```shell
As you can see, half of the global methods are not even finding a global maximum, another half is using almost as many fevals as there are data points.
```

### SciPy/NumPy/Python version and system information

```shell
1.11.2 1.23.0 sys.version_info(major=3, minor=9, micro=13, releaselevel='final', serial=0)
```

**Comment by dschmitz89** [comment]
Global optimization methods need to be "inefficient" to some extent to avoid local minima. Hyperparameter tuning of machine learning models is an "art" in my opinion and there are dedicated packages to do that with sklearn estimators ([autosklearn](https://github.com/automl/auto-sklearn) or [optuna](https://github.com/optuna/optuna), to name only two).

Although there is definitely room for improvement, I would argue that scipy's global optimizers are quite competitive: have a look at [this benchmark](https://infinity77.net/go_2021/thebenchmarks.html#info-general-results) for example. Therefore I am closing this issue.
