### ISSUE TITLE
BUG: SystemError: initialization of beta_ufunc raised unreported exception

### ISSUE THREAD

**Issue by Surajj4837-th** [scipy/scipy#19476]
### Describe your issue.

I have a 2D array of points and I want to cluster it. I have used the DBSCAN method. The main function is in C++ and the DBSCAN method is in Python. I have written an interface between both. The code is running fine but it gives Segmentation Fault error when I run it to check memory leaks using Valgrind.

So I debugged the Python code and found that just the import call to DBSCAN is throwing the error.

My folder structure is as follows:
Test:
├── CMakeLists.txt
└── src
    ├── Py_Interface
    │   ├── pyhelper.hpp
    │   ├── Py_Integration.cpp
    │   └── Py_Integration.h
    ├── PythonDep
    │   └── Cluster.py
    └── main.cpp

Attached is the zip file of the source code required for reproducing the error.
[Scipy Error.zip](https://github.com/scipy/scipy/files/13262450/Scipy.Error.zip)

valgrind installation:
> sudo apt install valgrind

### Reproducing Code Example

```python
valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=valgrind-out.txt ./Exec
```

### Error message

```shell
Traceback (most recent call last):
  File "/home/suraj/Projects/Scipy Error/build/../src/PythonDep/Cluster.py", line 1, in <module>
    from sklearn.cluster import DBSCAN
  File "/home/suraj/.local/lib/python3.8/site-packages/sklearn/__init__.py", line 83, in <module>
    from .base import clone
  File "/home/suraj/.local/lib/python3.8/site-packages/sklearn/base.py", line 19, in <module>
    from .utils import _IS_32BIT
  File "/home/suraj/.local/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 22, in <module>
    from ._param_validation import Interval, validate_params
  File "/home/suraj/.local/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 15, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/home/suraj/.local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 25, in <module>
    from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
  File "/home/suraj/.local/lib/python3.8/site-packages/sklearn/utils/_array_api.py", line 9, in <module>
    from .fixes import parse_version
  File "/home/suraj/.local/lib/python3.8/site-packages/sklearn/utils/fixes.py", line 19, in <module>
    import scipy.stats
  File "/home/suraj/.local/lib/python3.8/site-packages/scipy/stats/__init__.py", line 485, in <module>
    from ._stats_py import *
  File "/home/suraj/.local/lib/python3.8/site-packages/scipy/stats/_stats_py.py", line 46, in <module>
    from . import distributions
  File "/home/suraj/.local/lib/python3.8/site-packages/scipy/stats/distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "/home/suraj/.local/lib/python3.8/site-packages/scipy/stats/_continuous_distns.py", line 32, in <module>
    import scipy.stats._boost as _boost
  File "/home/suraj/.local/lib/python3.8/site-packages/scipy/stats/_boost/__init__.py", line 1, in <module>
    from scipy.stats._boost.beta_ufunc import (
SystemError: initialization of beta_ufunc raised unreported exception
Segmentation fault (core dumped)
```

### SciPy/NumPy/Python version and system information

```shell
1.10.0 1.24.4 sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
```

**Comment by dschmitz89** [comment]
Could you post a minimal working example? I think it must probably boil down to some parameter edge case for the beta function. Opening zip files is a security risk and strongly discouraged on github.

**Comment by Surajj4837-th** [comment]
I'm trying to upgrade the Scipy version to 1.11.3(the latest stable version) but it is not working. I uninstalled the 1.10.1 and triesd installing again by giving the version then the following error occurred:
```
ERROR: Could not find a version that satisfies the requirement scipy==1.11.3 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.8.0rc1, 1.8.0rc2, 1.8.0rc3, 1.8.0rc4, 1.8.0, 1.8.1, 1.9.0rc1, 1.9.0rc2, 1.9.0rc3, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0rc1, 1.10.0rc2, 1.10.0, 1.10.1)
ERROR: No matching distribution found for scipy==1.11.3
```

I m using Ubuntu 20.04.

**Comment by Surajj4837-th** [comment]
The minimal code example:

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.5 FATAL_ERROR)

project(Exec)
 
find_package(PythonLibs REQUIRED)

include_directories(
"src/Py_Interface")


include_directories(${PYTHON_INCLUDE_DIRS})

add_executable (Exec src/main.cpp src/Py_Interface/Py_Integration.cpp)
target_link_libraries (Exec ${PYTHON_LIBRARIES})
```

main.cpp
```
#include "Py_Interface/Py_Integration.h"

int main()
{
    Py_Wrapper();
}
```

Cluster.py
```
from sklearn.cluster import DBSCAN

def clustering():
    print("Clustering\n")
```

Py_Integration.h
```
#ifndef DL_INTEGRATION_H
#define DL_INTEGRATION_H

#include <Python.h>
#include "pyhelper.hpp"
#include <string>

PyObject *PythonInitialize(std::string script_name, std::string function_name);

void Py_Wrapper();

#endif // DL_INTEGRATION_H

```

Py_Integration.cpp
```
#include "Py_Integration.h"

using namespace std;

void Py_Wrapper()
{
    Py_InitializeEx(0); // Initialize the Python interpreter

    PyObject *PythonDetectorFunction, *PythonDetectorFunctionArguments;
    PythonDetectorFunction = PythonInitialize("Cluster", "clustering"); 

    if (PythonDetectorFunction == NULL)
        PyErr_Print();
    
    PyObject *PythonDetectorFeatureMaps = PyObject_CallObject(PythonDetectorFunction, PythonDetectorFunctionArguments);

    Py_XDECREF(PythonDetectorFunction);
    Py_XDECREF(PythonDetectorFunctionArguments);
    Py_XDECREF(PythonDetectorFeatureMaps);
}

PyObject *PythonInitialize(string script_name, string function_name)
{
    PyObject *pName, *pModule, *pFunc;
    PyRun_SimpleString("import sys, os");
    string PythonCodeImportStatement = "sys.path.append(os.getcwd() + '/../src/PythonDep/')"; // Relative path for the python code
    PyRun_SimpleString(PythonCodeImportStatement.c_str());

    // pNmae is the name of the python script/module to be called
    pName = PyUnicode_FromString(script_name.c_str());
    if (pName == NULL)
        PyErr_Print();

    // Getting the Python module reference inside of the C code
    pModule = PyImport_Import(pName);
    if (pModule == NULL)
        PyErr_Print();

    // Python function reference
    pFunc = PyObject_GetAttrString(pModule, function_name.c_str());
    if (pFunc == NULL)
        PyErr_Print();

    // Refrence count clean-up
    Py_XDECREF(pName);
    Py_XDECREF(pModule);

    return pFunc;
}

```

I have taken pyhelper.hpp from: https://github.com/beno54/Snake-integer/blob/master/pyhelper.hpp
I have posted the directory structure in the issue post above.

**Comment by dschmitz89** [comment]
> 1. I'm trying to upgrade the Scipy version to 1.11.3(the latest stable version) but it is not working. I uninstalled the 1.10.1 and triesd installing again by giving the version then the following error occurred:
> 
> ```
> ERROR: Could not find a version that satisfies the requirement scipy==1.11.3 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.8.0rc1, 1.8.0rc2, 1.8.0rc3, 1.8.0rc4, 1.8.0, 1.8.1, 1.9.0rc1, 1.9.0rc2, 1.9.0rc3, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0rc1, 1.10.0rc2, 1.10.0, 1.10.1)
> ERROR: No matching distribution found for scipy==1.11.3
> ```
> 
> I'm using Ubuntu 20.04.
> 
> 2. Further, I downloaded the zip of the latest version, extracted it, and placed it in the dist-packages folder, it is not detected by Python.

Are you installing scipy via the Ubuntu package manager? `pip install scipy` or `conda install scipy` instead will definitely get you the latest version.

The minimal working example does not contain calls to the boost distributions. We probably need the function you are integrating as that is where the call to boost and the subsequent error occurs.

**Comment by Surajj4837-th** [comment]
The minimal working example gives the error, to be specific just the `from sklearn.cluster import DBSCAN` statement is the exact cause of the error.

**Comment by dschmitz89** [comment]
If importing sklearn causes the issue independent of your code, I would suggest to open an issue in the sklearn GitHub repo. I still find this difficult to untangle.

**Comment by Surajj4837-th** [comment]
I raised the issue here since the last line of the error message points to the scipy module.

**Comment by Surajj4837-th** [comment]
> If importing sklearn causes the issue independent of your code, I would suggest to open an issue in the sklearn GitHub repo. I still find this difficult to untangle.

I raised the same on sklearn forum and the response was to raise the issue on this forum. [Reference](https://github.com/scikit-learn/scikit-learn/issues/27756#issuecomment-1803573076).

**Comment by dschmitz89** [comment]
Ok, then it looks like somehow the boost methods are broken in your scipy installation. How did you install scipy exactly? And it would help if you can test your code with scipy 1.11.

**Comment by Surajj4837-th** [comment]
I have installed scipy using pip3 install command, it by default installs 1.10.1 version:
```
suraj@suraj:~$ pip3 install scipy
Collecting scipy
  Using cached scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
Requirement already satisfied: numpy<1.27.0,>=1.19.5 in ./.local/lib/python3.8/site-packages (from scipy) (1.24.4)
Installing collected packages: scipy
Successfully installed scipy-1.10.1

```
and when I try to upgrade it by following command, it does not upgrade:
```
suraj@suraj:~$ pip3 install --upgrade scipy
Requirement already up-to-date: scipy in ./.local/lib/python3.8/site-packages (1.10.1)
Requirement already satisfied, skipping upgrade: numpy<1.27.0,>=1.19.5 in ./.local/lib/python3.8/site-packages (from scipy) (1.24.4)
```

**Comment by dschmitz89** [comment]
scipy 1.11 requires Python 3.9+, that's why you cannot install a newer version in Python 3.8: https://scipy.github.io/devdocs/release/1.11.0-notes.html. Should have seen it earlier. Please test your code with a newer Python/scipy version and let us know the outcome :).

**Comment by Surajj4837-th** [comment]
I upgraded the system Python to `Python 3.11.6` and still the issue persists.
