### ISSUE TITLE
BUG: wrong output of the stats.beta.fit() function

### ISSUE THREAD

**Issue by BetiseDeCamdray** [scipy/scipy#19470]
### Describe your issue.

i got a problem with the scipy fit error in a case where it should not fail as far as i am concerned.

see code.

### Reproducing Code Example

```python
from scipy.stats import beta
from numpy.random import default_rng
from tqdm import tqdm

def reproduce_scipy_mode_estimation_error(
        peak1=0.25,
        temp1=0.05,
        peak2=0.07,
        temp2=7.21,
        peak3=0.01,
        temp3=86.57,
        seed=362,
):
    """
    This function has been created to reproduce an error of the scipy.fit()
    function.

    Steps:
        -First, this function draw a sample of size 10000 for 3 different modified
        PERT distributions (with their respective peak and temperature).

        -Then processes the 3 samples together (ad hoc process, it could be
        something else I guess). This processed data set is the data of
        interest.

        -Finally, it infers a suitable modified PERT distribution to model
        the processed data.

    This function gets to estimate:
        low_inferred = 0
        mod_inferred = 1.0252528246011596
        max_inferred = 1
        temp_inferred = -0.002286433872501714

    while I set min and max to be 0.0 and 1.0 .
    Moreover, lambda must be strictly positive
    """
    rand_gen = default_rng(seed)

    def convert_PERT_param_into_Beta_param(low, peak, high, temperature):
        _loc = low
        _scale = high - low
        _alpha = 1 + temperature * (peak - low) / (high - low)
        _beta = 1 + temperature * (high - peak) / (high - low)
        return _alpha, _beta, _loc, _scale

    def convert_Beta_param_into_PERT_param(_alpha, _beta, _loc, _scale):
        _low = _loc
        _peak = _loc + (_alpha - 1) / (_alpha + _beta - 2) * _scale
        _high =_loc + _scale
        _scale = _alpha + _beta - 2
        return _low, _peak, _high, _scale

    # insure the conversion is right
    test_param = [1.5, 3.1, 0., 1.]
    output_test = convert_PERT_param_into_Beta_param(*convert_Beta_param_into_PERT_param(*test_param))
    for elm1, elm2 in zip(test_param, output_test):
        print(elm1, elm2)
        assert round(elm1, 9) == round(elm2, 9)


    def draw_a_sample(_alpha, _beta, _loc, _scale, np_random_generator):
        return _loc + _scale * np_random_generator.beta(_alpha, _beta, size=10000)

    # draw samples and get processed data
    sample_1 = draw_a_sample(*convert_PERT_param_into_Beta_param(0, peak1, 1, temp1), rand_gen)
    sample_2 = draw_a_sample(*convert_PERT_param_into_Beta_param(0, peak2, 1, temp2), rand_gen)
    sample_3 = draw_a_sample(*convert_PERT_param_into_Beta_param(0, peak3, 1, temp3), rand_gen)

    data = 1 - (1 - sample_1) * (1 - sample_2 * sample_3)

    # inference among the beta distribution family
    floc = 0
    fscale = 1
    alpha_inferred, beta_inferred, loc_inferred, scale_inferred = beta.fit(data, floc=floc, fscale=fscale, method="mm")

    # convert into PERT param
    low_inferred, mod_inferred, max_inferred, temp_inferred = convert_Beta_param_into_PERT_param(
        alpha_inferred, beta_inferred, loc_inferred, scale_inferred
    )

    # print(low_inferred, mod_inferred, max_inferred, temp_inferred)
    if max_inferred <= mod_inferred:
        print(low_inferred, mod_inferred, max_inferred, temp_inferred)
        print(
            peak1,
            temp1,
            peak2,
            temp2,
            peak3,
            temp3,
            seed,
        )
        raise Exception()

    return low_inferred, mod_inferred, max_inferred, temp_inferred


if __name__ == "__main__":
    reproduce_scipy_mode_estimation_error()
```

### Error message

```shell
no error message, only a wrong output
```

### SciPy/NumPy/Python version and system information

```shell
scipy==1.11.3
numpy==1.24.3
python 3.10.11
windows 

result of command:
$ python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()
1.11.3 1.24.3 sys.version_info(major=3, minor=10, micro=11, releaselevel='final', serial=0)
    name: gcc
    version: 10.3.0
  pythran:
    include directory: C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-qjiwhfk5\overlay\Lib\site-packages/pythran
    version: 0.14.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
Python Information:
  path: C:\Users\runneradmin\AppData\Local\Temp\cibw-run-8hexkyrv\cp310-win_amd64\build\venv\Scripts\python.exe
  version: '3.10'
```

**Comment by mdhaber** [comment]
Please provide a minimal reproducible example (e.g. just the data and the call to the `fit` method). Please provide the output and explain why it is different from what you expect.

**Comment by BetiseDeCamdray** [comment]
I understand through your answer that i may have been not clear enough. Sorry for that, i spent a lot of time to make a clear and reproductible code to help you out... that's why i was brief in the other sections.

in case it was not clear to you, the data are provided because the code provided generate them, with the seed, etc... it should reproduce the same behaviour on your side. if  not, let me know and i'll try to help you reproduce it another way.

i've written the expected output in the docstring of the function:
**expected output**: a peak value (or mode value) between min and max (between low and max, it is the same), and temperature value above 0.

i've also written the output of the fit method (in terms of PERT parameters) in the docstring:
**output**:
low_inferred = 0
mod_inferred = 1.0252528246011596
max_inferred = 1
temp_inferred = -0.002286433872501714

If the modified PERT distribution is not a distribution you are familiar with, it is simply an other possible parametrization of the beta distribution in the special case where alpha>1, beta>1. then instead of min, max, alpha and beta, the parametrization is min, mod, max, temperature with this translation:
min = min
mod = (alpha-1)/(alpha+beta-2)
max = max
temperature = alpha+beta-2
Check this out for furthur info: https://en.wikipedia.org/wiki/PERT_distribution
my code provides the two function to convert the parameters from one convetion to the other one.

There is one thing i have not provided yet, it is the screen shot of my debugger:
![image](https://github.com/scipy/scipy/assets/147074835/36179554-a891-4fa0-bffc-07ec16a4ac8a)

This concerns the function _fit_loc_scale_support line 2657 in file scipy\stats\_distn_infrastructure.py

You can see at line 2726 on the screenshot of my debug session that a,b = 0.,1.. **That is correct.** These values are respectively floc and fscale values i ve passed in argument of the fit() method.

At line 2741, the condition is false because actually a_hat > data_a. That is ok to be so here.

As a consequence the execution runs further until line 2752 and 2753 where loc_hat and scale_hat are set unconsistently with the arguments floc and fscale i've provided. **That's a problem.** loc_hat happens to be negative, As far as i understand what the method should do, loc_hat should be greater than floc (greater than the "a" that appears at line 2726)

I think the problem of the fit function is directly induced by the wrong value taken by loc_hat at line 2752.

**possible solution**
loc_hat and scale_hat should not take value unconsistent with floc and fscale passed as argument of .fit() because i assume (i've not checked that out) that loc_scale is used afterwards to estimate with a max-log-likelihood the parameters of the beta. Since loc_hat is negative here, it is possible for the max-log-likelihood step finds parameters that lead to a distribution with negative mode (=most likely value = peak value (synonyms here)). The mode is precisely the wrong "mod_inferred" value in this execution.

I hope that helps you to understand the issue i've posted. Thank you for answering so quickly!

**Comment by mdhaber** [comment]
I went ahead and dug out what was needed:

```python3
# I created a list `data_global` and added this line to your code
# before the call to `beta.fit`
# data_global.append((data, floc, fscale))

from scipy import stats
import numpy as np

data, floc, fscale = data_global[0]
params = beta.fit(data, floc=floc, fscale=fscale, method="mm")
dist = stats.beta(*params)

i = np.arange(1, 5)[:, np.newaxis]
moments = np.mean(data**i, axis=1)
# raw moments of the data
moments  # array([0.49939921, 0.33279701, 0.24984718, 0.20017233])

# moments of the fitted distribution
for j in i:
  print(dist.moment(j))
# 0.49939883481287894
# 0.3327959694816871
# 0.24954458609611152
# 0.19960995274281085
```
The moments of the data match the moments of the fitted distribution pretty closely, so it looks like `beta.fit` is working as advertised.

**Comment by BetiseDeCamdray** [comment]
Well, i agree with you to say that this seems to prove that beta.fit() works well.
 
I reran my code and the output of the beta.fit() is `alpha, beta, loc, scale = 0.9976558272139538, 1.0000577389135445, 0, 1`. One could indeed say that it is good enough and since alpha<1 it is my mistake to try to convert that into a PERT distribution. I should not because alpha does not satisfy the constraints over the parameters for the conversion to be valid.

The issue i am reporting is not just about the moments (that are fine enough), it is about the way the bounds of the support are computed, and along the way inconsistent computations are done. I've done my best to show how and why. So, i rather disagree to accept that this is fully fine but i'll respect your decision.

**Food for thoughts:**
In the problem i am trying to solve with scipy at the moment, i need to stick to beta distributions with a mode value strictly between 0 and 1. Those are called PERT distribution but whatever. Scipy is currently unable to stick to this setup even when I specify it manually with floc=0 and fscale=1. It may be fine to keep the code as it is and enable the user to add constraints about the location of the mode value (solution 1). It could be also possible to implement the PERT distributions as stand alone distribution (Those are pretty useful in industrial context) (solution 2). Or maybe the fix I pinpointed in the _fit_loc_scale_support() function could also do the job (solution 3).

**I think this is worth to be improved in later versions but you are the one that work hard on scipy so I will abide by your opinion. Thank for your work and your time.**

**Comment by mdhaber** [comment]
> loc_hat and scale_hat should not take value unconsistent with floc and fscale passed as argument of .fit() because i assume **(i've not checked that out)** that loc_scale is used afterwards

Please take a look first.

>  to estimate with a max-log-likelihood the parameters of the beta. 

Not in your example. You're using `method='mm'`. This is method of moments, not maximum likelihood estimation.

If there is still an issue after looking at the code, please provide an example in which the output of the code is incorrect, or please adjust the title of the issue.

**Comment by BetiseDeCamdray** [comment]
I've taken some time to understand further what was going on. Spoiler: _i think final scipy is ok!_

**Theoretically speaking**:
I've taken a closer look to the theoretical problem I was trying to solve. The most likely value was indeed strictly between 0 and 1 (i.e. a beta distribution with parameters a>1 and b>1) but the distribution was very close to a uniform distribution.

**dependence on method used**:
both methods "mm" and "mle" lead to the problem I reported. But I had a code of mine to perform bayesian inference for Beta distribution that coincide exactly with the "mle" conclusions (both failed or none did).

**scipy _fit_loc_scale_support function role**:
I checked further in the code of scipy and finally, even if there was apparently "inconsistent" computations inside _fit_loc_scale_support, the way its output is further used make things go right again.

**conclusion**:
My conclusion on what happened now incriminates the statistical fluctuations. The histogramme of the distribution at stake sampled with only 10000 values could sometime by chance lead scipy.beta.fit() estimate a<1 or b<1 even if the theoretical distribution did not satisfy these inequalities.
So, among the 3 solutions I've proposed only the 1st and the 2nd remain relevant. (i.e. enable user to add constraints on the parameters to fit or add PERT distribution to the available distributions in scipy.)

Thank you for your time!

**Comment by mdhaber** [comment]
(1) is already possible using [`scipy.stats.fit`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fit.html). (2) is already resolved - there has been a long-standing policy not to add alternate parameterizations of existing distributions. The PERT parameterization of beta, in particular, has been discussed a lot on the [mailing list](https://mail.python.org/archives/search?list=scipy-dev%40python.org&q=Pert) already. That said, the policy will probably be reconsidered when https://github.com/scipy/scipy/issues/15928 is resolved, and that work is underway (with considerable progress).

**Comment by BetiseDeCamdray** [comment]
Perfect.

interesting! I was so focused on beta.fit() thinking it was the same as scipy.stats.fit() that i missed the interesting possibilities offered by scipy.stats.fit(). top. thank you.
