### ISSUE TITLE
RFC: Thoughts on making our vendored Cephes a cleaner header only library.

### ISSUE THREAD

**Issue by steppi** [scipy/scipy#19481]
This is a follow up on https://github.com/scipy/scipy/issues/19404, the effort to translate compiled kernels for special functions where SciPy provides its own implementation from Cython into header only NVCC compatible C++.

While translating the function [binom](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.binom.html) for the binomial coefficient of two real arguments in https://github.com/scipy/scipy/pull/19471, it was observed that the current [Cython implementation](https://github.com/scipy/scipy/blob/8a7959d449f46017bef5388f696ce11615176b9f/scipy/special/orthogonal_eval.pxd#L69) makes use of the functions from `Gamma`, `beta`, and `betaln` from our vendored copy of [the Cephes mathematical library](https://github.com/scipy/scipy/tree/main/scipy/special/cephes). At the moment Cephes is not header only, but I think getting it to that point should be straightforward if tedious, and I'd be curious to hear others thoughts on the matter.

Perhaps this should be a separate issue, but regarding "cleaner",  the main problem is that there is a header `cephes_names.h` which defines aliases like `beta` -> `cephes_beta`. The idea here is to give a prefix to each symbol for a cephes function, which is a good idea. Unfortunately, up to now, it hasn't been noticed that this aliases leak into global scope for everything in the same translation unit. When I put `#include "cephes.h"` inside of the C++ header for `binom`, the aliases were getting expanded inside of Boost, causing compilation errors because the signatures of `expm1` are different in Boost vs Cephes. I don't want to ponder what might have happened if all of the signatures were the same.

As a workaround, I wrote a header, https://github.com/scipy/scipy/pull/19471/files#diff-08bc49c27ad8094da8b42c6cffce31b867922eaf105ec5a6d598ba824bb771d8, which undefs all of the aliases, and puts functions from Cephes into a C++ namespace `scipy::special::cephes`. This will work for now, but isn't a long term solution. I think we should fix this problem so that the aliases are only used internally within cephes, and then external code in C would actually call `cephes_beta` etc. External code in C++ could use a namespace instead of the prefix.

Done improperly, it's possible making Cephes special functions inlined inside of headers could cause a harmful impact on build times. Rather than having one header `"cephes.h"` with every function like we have now, I think it would be better to have separate headers for each function (or small group of related functions) and to only include those that are needed in a given file.

This seems like it could be a significant effort, so I'd appreciate any wisdom and guidance on how to best carry it out. I'd suspect we'd want to do things in a piecemeal fashion, only moving functions to headers only as we need them.

Happy to hear your thoughts.

**Comment by izaid** [comment]
Just wanted to +1 this. I think it's annoying work, but important work for things to progress. It should be reasonably straightforward to turn cephes into a header only *C* (not C++) library. At least then it wouldn't block our other current efforts.

**Comment by steppi** [comment]
This was completed here, https://github.com/scipy/scipy/pull/20390.
