### ISSUE TITLE
Query: Where is cdflib used in SciPy code?

### ISSUE THREAD

**Issue by ilayn** [scipy/scipy#19486]
Yesterday, when we were discussing the cdflib on the LFortran repo, I noticed that these are a lot of tiny functions that can be written quickly in Cython. I know we were supposed to switch to Boost implementation at some point but I could not resist anyways so already wrote half of it. I can finish it tonight and send a PR. 

So question is how can I test the implementation against our own code? I can't find any entry points to the fortran code other than the wrappers for C code. Is that it? Can anyone help me with this? 

CC: @steppi @ev-br

**Comment by ev-br** [comment]
At a guess it's used a lot in stats

**Comment by ilayn** [comment]
I see, I somehow couldn't find the import point in stats.

**Comment by ilayn** [comment]
For example, digamma is already in its own place in `special` and `psi_fort.f` is not as good. So probably we already have most of this library available elsewhere. And I can quickly get the remaining parts to Cython so you guys can take over to C++ conversion or switching to Boost. 

How does that sound?

**Comment by ev-br** [comment]
I actually wonder how much breaks in scope if cdflib is completely removed temporarily. This could give a useful data point on what is used and what isn't. The latter I guess can possibly just keep deleted, is it not internal anyway.

**Comment by ilayn** [comment]
Ah OK some special ufuncs are coming from that library. I'll try to make a list out of them

**Comment by ev-br** [comment]
Removing cdflib from meson.build and making the test run pass collection stage,  https://github.com/ev-br/scipy/pull/new/rm_cdflib, generates a bunch of missing function errors. In stats, `$ python dev.py test -s stats`, the fallout is https://gist.github.com/ev-br/de296468e24ccd2671accf70e69f2521.

ISTM this looks scarier than it actually is: apparently we're using less than a dozen distributions from cdflib.   

At a danger of sounding like a broken record, I'd think that the most productive approach could start from checking which of these functions are already available elsewhere (`ndtr` is essentially `erf` from faddeeva, beta functions should be available from boost etc). 
It's full well possible that replacements have glitches in corner cases or some parameter regions.
Then it becomes a matter of what is the best strategy -- -basically it's LBYL vs EADP: do we try to iron out all possible wrinkles first, or do we replace them and see what breaks downstream.
Maybe it's best to do the latter, starting early in the release cycle.

**Comment by ilayn** [comment]
The fallout from your stats has only these 

```
btdtr
chndtr
chndtrix
stdtrit
tklmbda
pdtrik
```

so indeed not so bad. Whatever these are I can create the Cython versions. But I also know that some of them are still in Boost waiting to be implemented.

**Comment by steppi** [comment]
Checking [scipy/special/functions.json](https://github.com/scipy/scipy/blob/main/scipy/special/functions.json), it looks like there are 31 functions that come from cdflib

[bdtrik](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.bdtrik.html)
[bdtrin](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.bdtrin.html)
[btdtria](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.btdtria.html)
[btdtrib](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.btdtrib.html)
[chdtriv](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.chdtriv.html)
[chndtr](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.chndtr.html)
[chndtridf](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.chndtridf.html)
[chndtrinc](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.chndtrinc.html)
[chndtrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.chndtrix.html)
[fdtridfd](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.fdtridfd.html)
[gdtria](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.gdtria.html)
[gdtrib](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.gdtrib.html)
[gdtrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.gdtrix.html)
[nbdtrik](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.nbdtrik.html)
[nbdtrin](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.nbdtrin.html)
[ncfdtr](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.ncfdtr.html)
[ncfdtri](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.ncfdtri.html)
[ncfdtridfd](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.ncfdtridfd.html)
[ncfdtridfn](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.ncfdtridfn.html)
[ncfdtrinc](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.ncfdtrinc.html)
[nctdtr](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.nctdtr.html)
[nctdtridf](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.nctdtridf.html)
[nctdtrinc](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.nctdtrinc.html)
[nctdtrit](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.nctdtrit.html)
[nrdtrimn](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.nrdtrimn.html)
[nrdtrisd](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.nrdtrisd.html)
[pdtrik](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.pdtrik.html)
[stdtr](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.stdtr.html)
[stdtridf](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.stdtridf.html)
[stdtrit](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.stdtrit.html)
[tklmbda](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.tklmbda.html)

Some of this is pretty niche, so not sure how much of it would be available elsewhere.

**Comment by ev-br** [comment]
In my experiment mentioned above, https://github.com/scipy/scipy/compare/main...ev-br:scipy:rm_cdflib?expand=1, I simply removed them all from `functions.json`. Apparently, not all of them are used, in scipy.stats at least.

**Comment by steppi** [comment]
> In my experiment mentioned above, https://github.com/scipy/scipy/compare/main...ev-br:scipy:rm_cdflib?expand=1, I simply removed them all from `functions.json`. Apparently, not all of them are used, in scipy.stats at least.

It makes sense we wouldn't be using a lot of oddball things internally. I wonder how much use they get downstream.

**Comment by steppi** [comment]
I checked statsmodels (just with grep), and it looks like it only uses `chndtr`, `chndtrinc`, `ncfdtr`, `ncfdtri`, `ncfdtrinc`, `nctdtr`, and `stdtr`,

**Comment by ilayn** [comment]
This is very puzzling for me. So there are 

- some ufuncs directly wrapped from Fortran to C.
- Some in stats in a strange way that I have not figure out yet
- And downstream because these are apparently public

But say 

https://github.com/scipy/scipy/blob/80c81df56fa118e9a86b9e0283bf79c3dfbd3969/scipy/special/cdf_wrappers.c#L459

This is not a fortran file so my apologies for my stupidity, I can't understand how things are called yet.

**Comment by steppi** [comment]
Looking at the [meson.build](https://github.com/scipy/scipy/blob/main/scipy/special/meson.build) for `special` it looks like cdflib gets compiled as a static library and the functions are called directly from C.

```
cdflib_lib = static_library('cdflib',
  cdflib_sources,
  fortran_args: [
    _fflag_Wno_maybe_uninitialized,
    _fflag_Wno_unused_label,
    _fflag_Wno_intrinsic_shadow
  ]
)
```

I think things look a little more complicated then they are because of the macros to add error handling, make sure Fortran gets the arguments by reference like it wants them, and to deal with the vagaries of what the Fortran functions should be called when calling from C.

**Comment by steppi** [comment]
> * Some in stats in a strange way that I have not figure out yet

For all but `btdtr` in the list 

```
btdtr
chndtr
chndtrix
stdtr
stdtrit
tklmbda
pdtrik
```

It seems like these are just calls to `special.chndtr` etc...

`btdtr` isn't even in cdflib, it's in cephes. Not sure what's going on there. It's pretty weird.

**Comment by steppi** [comment]
> `btdtr` isn't even in cdflib, it's in cephes. Not sure what's going on there. It's pretty weird.

Oh, wait. Is it just a false positive? I think `btdtr` is just mentioned in the fallout as part of the suggestion

```
AttributeError: module 'scipy.special' has no attribute 'stdtr'. Did you mean: 'btdtr'?
```

**Comment by ilayn** [comment]
> Is it just a false positive? 

Yes I think so. 

I guess some functions are used internally in Cephes and then cephes is providing this stuff to `special` and in turn in `stats`.

**Comment by josef-pkt** [comment]
statsmodels is using some of the special functions like non-central directly from special because the boost implementation used in stats are (or were) buggy for our cases.

The other nice thing is that cdflib has inverse functions (rootfinding for one of the parameters).
AFAIR, that is only used in a few cases in statsmodels (because my power and sample size computation are only for the standard test distributions, normal, t, F, chi2 and their non-central versions.)

Most other distribution `special` functions are indirectly accessed by statsmodels through stats.distributions.

(Aside: one disadvantage of normal cdf in special used by scipy.stats is that it does not evaluate for complex number, while erf does.)

**Comment by ilayn** [comment]
OK I'm almost done with them anyways so let's see what we can do with such code. Then we can remove the ones we don't need. Probably we would use some pxd header and pass it to `cephes` somehow and make it available through public API at the same time.

Strangely enough Cython version is quite fast compared to Fortran (at least in a Jupyter notebook with `%%cython` cells).

I should stop looking at fortran code in the evenings, they are too appealing for killing time.

**Comment by josef-pkt** [comment]
another aside:  I have not looked at the scipy distribution refactor.
If the distribution classes loose `args` in the methods, then I plan to add several wrapper functions for statsmodels to use scipy.special direcctly.

**Comment by ilayn** [comment]
If you want to play with them, a single cython file with no build infra is found at

https://github.com/ilayn/scipy/blob/remove_cdflib/scipy/special/_cdflib.pyx

Tested some of the functions (`betaln`, `erf`, `erfc`, `erfc1`, and `psi` ->which I think is `special.digamma`) and they agree with Wolfram Alpha digit by digit all the way occasionally the last two digits are off and they are quite fast. So I don't think these ones are buggy ones. Or if we had any issues with them probably it is the remaining ones. Don't know how it compares with `cephes` or Boost.

The files starting with `c` are missing because they are mostly Fortran subroutines and not functions. Not very difficult but tedious `GOTO` sphagetti as usual. I'll try to complete the suite as soon as possible. In the meantime, if you can let me know what we should do with these or how to integrate if we are keeping them, that would be great.

**Comment by steppi** [comment]
Awesome @ilayn. Yeah, down the line we should compare these with what's in cephes and Boost and pick the best options to use internally, but it might be better to try to get cdflib out of Fortran as as soon as we can, and just stick with using these for now. As soon as you have something rewritten that is exposed as a public ufunc in special, I can help test it and put together a PR to get it in. After that, if you want to make PRs for  others, I can test and then review and merge. I think we can keep a good pace that way.

**Comment by rgommers** [comment]
Awesome, looks like a lot of progress.

> https://github.com/ilayn/scipy/blob/remove_cdflib/scipy/special/_cdflib.pyx

This looks pretty good. Just to note that I did check for the absence of fused types and Tempita templating, because that is a bit of a headache (C++ would be preferable for that).

**Comment by ilayn** [comment]
The library is just written for doubles so I didn't do any floats. If we can filter out the parts we want to keep I can rearrange things for the remaining set.

**Comment by ilayn** [comment]
> After that, if you want to make PRs for others, I can test and then review and merge. I think we can keep a good pace that way.

Sure thing will do. Just trying to tame the subroutines to functions conversion without hurting the essence of signatures.

**Comment by ilayn** [comment]
Just venting; Found the source of the algorithm, this is the flowchart of `gaminv.f` :)

![image](https://github.com/scipy/scipy/assets/1303842/a5386bcd-f11f-4c73-93cc-1720bee6fcc7)

On other news, sorry for the delay I wasn't expecting this much madness, 10 complicated functions left.

**Comment by steppi** [comment]
> Just venting; Found the source of the algorithm, this is the flowchart of `gaminv.f` :)
> 
> ![image](https://user-images.githubusercontent.com/1303842/282324652-a5386bcd-f11f-4c73-93cc-1720bee6fcc7.png)
> 
> On other news, sorry for the delay I wasn't expecting this much madness, 10 complicated functions left.

Wow. That flowchart is just amazing. It’s crazy how far structured programming takes us in terms of managing complexity, and how obvious it seems only in hindsight. Awesome work.

**Comment by ilayn** [comment]
OK finally, I am done with the translation and I understand how cdflib is used in SciPy. So basically, the fortran files that start with `cdf` have a `which` parameter that selects the knowns and unknowns. Example from `cdfbet`

https://github.com/scipy/scipy/blob/20d3047ac50c85f9319f63df548698a5473a44d4/scipy/special/cdflib/cdfbet.f#L16-L25

Option 3 and 4 here then becomes separately `btdtria` and `btdtrib` and first 2 are not wrapped (not sure why not, maybe wrapped from cephes). 

This separation is happenning in the `cdf_wrappers.c` and `cdf_wrappers.h` and they are renamed into more cryptic names that I think you guys understand their meaning like `btdtria`. 

We can get rid of all that by wrapping `cdf###.f` functions into different functions so we don't need all that 

https://github.com/scipy/scipy/blob/20d3047ac50c85f9319f63df548698a5473a44d4/scipy/special/cdf_wrappers.c#L31-L52

wrapping mechanism. But I don't quite sure how ufuncs want the results. In fact I can write the functions with their wrapped names as separate kernels and don't use any `cdf###`

What do you think?

**Comment by steppi** [comment]
> OK finally, I am done with the translation and I understand how cdflib is used in SciPy. So basically, the fortran files that start with `cdf` have a `which` parameter that selects the knowns and unknowns. Example from `cdfbet`
> 
> https://github.com/scipy/scipy/blob/20d3047ac50c85f9319f63df548698a5473a44d4/scipy/special/cdflib/cdfbet.f#L16-L25
> 
> Option 3 and 4 here then becomes separately `btdtria` and `btdtrib` and first 2 are not wrapped (not sure why not, maybe wrapped from cephes).
> 
> This separation is happening in the `cdf_wrappers.c` and `cdf_wrappers.h` and they are renamed into more cryptic names that I think you guys understand their meaning like `btdtria`.
> 
> We can get rid of all that by wrapping `cdf###.f` functions into different functions so we don't need all that
> 
> https://github.com/scipy/scipy/blob/20d3047ac50c85f9319f63df548698a5473a44d4/scipy/special/cdf_wrappers.c#L31-L52
> 
> wrapping mechanism. But I am not quite sure how ufuncs want the results. In fact I can write the functions with their wrapped names as separate kernels and don't use any `cdf###`
> 
> What do you think?

I think we don’t need any of that wrapping nonsense now. If you make a PR just adding the library I can push some commits to your branch setting up the rest of the stuff up later this week if you like.

**Comment by ilayn** [comment]
Ah let me clarify. As you might have guessed these are Fortran subroutines, hence things are modified in place so you allocate some output vars `o1`, `o2` and send it together with inputs `i1`, `i2`, `i3` 

```Fortran
CALL mysubroutine(i1, i2, i3, o1, o2)
```

And o1, and o2 are populated. C/Python does not support this in place modification unless we use arrays or dicts or whatever that has an internal data structure. When we convert these to functions we can make 4 different funcs or have one and changing input output signatures. 

That's what I meant

**Comment by steppi** [comment]
I see, sorry. Was focused on something else when I wrote that. My vote is just to have 4 functions.

**Comment by josef-pkt** [comment]
separate function sounds fine to me (as it is also currently)

alternative if there are too many extra parameters:

IIUC, my related usage (for inverting cdf function with respect to a parameter argument)
In power and sample size computation, I have one main `power` method (corresponding to cdf or diff of cdf values) and a `solve_power` method, that inverts wrt all other available arguments using rootfinding.
Exactly one keyword has to be None. 
It'still a function with arguments and returns and no inplace modification (in python). My rootfinding is not vectorized, the power function itself is (through using scipy.stats or special).
AFAIR, some R packages use something similar where the parameter to solve for has to be nan.

https://www.statsmodels.org/dev/generated/statsmodels.stats.power.TTestPower.solve_power.html

**Comment by ilayn** [comment]
Ah yes, this is exactly the behavior we are trying to get away from. Not only it introduces lots of acrobatics in the code, but also gets very difficult to guess what is input and what is output. 

Separate function it is then.

**Comment by ilayn** [comment]
I tested many of the functions but it is not that trivial to generate good tests for all of them. Hence if you have any ideas how to test these things I'd be happy to include.

**Comment by steppi** [comment]
I planned to write very thorough tests as part of the review process, since this is a big change. Or I can write a few first and paste them here and you can follow the same recipe for the others maybe.

**Comment by ilayn** [comment]
> I planned to write very thorough tests as part of the review process, since this is a big change. Or I can write a few first and paste them here and you can follow the same recipe for the others.

That sounds great. So then let me finish completely with the cdfs and we do it in one go. I'm really relieved to hear that 😄

> This saved me from writing a large number of methods, but users need to keep track of what arguments they are using.

True but that's very tricky to do it with typed signatures of Cython. All kinds of weird stuff is going on especially if we want to use them for ufuncs.
