### ISSUE TITLE
scipy.signal and scipy.optimize missing library stubs or py.typed marker

### ISSUE THREAD

**Issue by alanwilter** [scipy/scipy#19502]
Using `mypy 1.6.1` and `scipy 1.11.3`.

**Comment by rgommers** [comment]
A bit more context would be helpful here @alanwilter. Are you saying that those modules have stubs and they're missing from the installed `scipy` package? Or is this just a general "scipy isn't fully annotated"?

**Comment by alanwilter** [comment]
Sorry, let me add an example:

`test.py`
```python
import scipy


def objective_function(x: float) -> float:
    return x**2 + 4 * x + 4


def gradient(x: float) -> float:
    return 2 * x + 4


initial_guess = 0.0
result = scipy.optimize.minimize(objective_function, initial_guess, jac=gradient, method="BFGS")

minimum_value, optimal_solution = result.fun, result.x
print(f"Minimum value: {minimum_value}")
print(f"Optimal solution: {optimal_solution}")
```

if I do:

```bash
mypy --strict test.py
test.py:1: error: Skipping analyzing "scipy": module is installed, but missing library stubs or py.typed marker  [import-untyped]
test.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

Using:
```python
from scipy.optimize import minimize
...
result = minimize(objective_function, initial_guess, jac=gradient, method='BFGS')
...
```

Gives a similar `error` with `mypy`.

Perhaps it all my mistake because I thought `scipy` was ready for `mypy`, but it does not seem so.

**Comment by rgommers** [comment]
> Perhaps it all my mistake because I thought `scipy` was ready for `mypy`, but it does not seem so.

Pretty much this. There are some parts with type annotations, and contributions are very welcome. But most of SciPy does not have any annotations yet.

Since we've cleared this up, I'll go ahead and close the issue.
