### ISSUE TITLE
Continuing optimization without restarting

### ISSUE THREAD

**Issue by SNMS95** [scipy/scipy#19522]
Hey everyone, 

Thank for the great support for this package.

I am using scipy.optimize.minimize module and was thinkng if there is a way to continue the optimization from a previous point.

For example, consider `L-BFGS-B`. I can perform optimization for 10 iterations and get the result. However, if I am not satisfied, as I understand, there are only two options,
1. Run the optimization again for longer 
2. Run the optimization from the last found optimal point (treating it as `x0`)

The first is wasteful (for complex optimizations) and the second looses the optimizer's internal state [For LBFGS, this is the hessian approximation built over the past iterations].

It would be nice if there is a way to get the state of the optimizer after the optimization and to feed it to a new instance to continue from where it was left. 

Is there any way to achieve this currently?

```
def lbfgs_update(x_current, opt_state):
    x_new, opt_state = optimize.minimize(fun, x_current, options={'maxiter':1}, state= opt_state)
```

**Comment by dschmitz89** [comment]
The underlying Fortran code does not allow this unfortunately. Other optimizers allow to pass `hess_inv0` for example.

If `L-BFGS-B` gets rewritten, this feature could be kept in mind.

**Comment by SNMS95** [comment]
> The underlying Fortran code does not allow this unfortunately. Other optimizers allow to pass `hess_inv0` for example.
> 
> If `L-BFGS-B` gets rewritten, this feature could be kept in mind.

Thanks a lot!
Are there any plans for such in the near future? :)

**Comment by lucascolley** [comment]
> Are there any plans for such in the near future? :)

It is planned eventually, along with the rest of the Fortran code tracked in gh-18566 - this is a huge undertaking though, and `L-BFGS-B` is marked as "hard", so it may take a while :)
