### ISSUE TITLE
Documentation website SSL certificate expired.

### ISSUE THREAD

**Issue by MialLewis** [scipy/scipy#19538]
### Issue with current documentation:

The SSL certificate for the SciPy documentation domain expired yesterday. Please could you renew it?

It's causing [warnings](https://builds.mantidproject.org/job/pull_requests-conda-packaging/156/consoleFull) on our documentation pipeline which is leading to build failures.

Thanks.

### Idea or request for content:

Renew SSL certificate for `docs.scipy.org`

**Comment by lucascolley** [comment]
See https://github.com/scipy/docs.scipy.org/issues/80
