### ISSUE TITLE
DOC: THe website of the documentation is broken

### ISSUE THREAD

**Issue by 12rambau** [scipy/scipy#19531]
### Issue with current documentation:

I encounter the bug first in the pydata-sphinx-theme build CI as we load your documentation screenshot in the examples (https://readthedocs.org/projects/pydata-sphinx-theme/builds/22569455/).

When I try to manually open the documentation from my browser I get the following error: 

```
Attackers might be trying to steal your information from docs.scipy.org (for example, passwords, messages, or credit cards).
NET::ERR_CERT_DATE_INVALID
```

### Additional context (e.g. screenshots, GIFs)

<img width="960" alt="image" src="https://github.com/scipy/scipy/assets/12596392/cdd03da3-5bea-415e-8e73-878a78807cd7">

**Comment by andyfaff** [comment]
Please see https://github.com/scipy/docs.scipy.org/issues/80#issuecomment-1813688181. We know about this issue.

**Comment by 12rambau** [comment]
sorry for the noise, I didn't know documentation has a dedicated repo.
