### ISSUE TITLE
Is it possible to specify parameter constraints in scipy.odr?

### ISSUE THREAD

**Issue by JSAnandEOS** [scipy/scipy#19552]
I'm interested in using scipy.odr to fit a nonlinear model, but in some cases the fitted parameters become unrealistically large. Before using ODR I used scipy.optimize.curve_fit to fit my models, where I could specify constraints using the "bounds" option, but I now need to use ODR because curve_fit didn't allow for uncertainties in both my y and x to be accounted for in the fit. 

From what I can tell, in scipy I can either have my fit parameters constrained, or have an errors-in-variables model, but not both. Is there any way to do this in scipy, or indeed in Python at all?

**Comment by rkern** [comment]
No, the version of ODRPACK that we wrap does not support constraints.
