### ISSUE TITLE
BUG: Impossible to avoid deprecation warning when pickling/unpickling a scipy.sparse.csc_matrix

### ISSUE THREAD

**Issue by pgunn** [scipy/scipy#19566]
### Describe your issue.

We pickle csc_matrix objects as part of our software pipeline, and are currently trying to reduce deprecation warnings.

Right now it looks like scipy.sparse.csc_matrix objects are still really of the type

`scipy.sparse._csc.csc_matrix`

and so when they're unpickled they hit the deprecation warning. More worryingly, the transition to whenever the name really changes behind the scenes will be abrupt because we can't change our picklefiles in prep for the preferred name.

### Reproducing Code Example

```python
​​>>> empty_csc = scipy.sparse.csc_matrix([0,0])
​​>>> type(empty_csc)
​​<class 'scipy.sparse._csc.csc_matrix'>
```

### Error message

```shell
n/a
```

### SciPy/NumPy/Python version and system information

```shell
scipy 1.11.3, python 3.11.6 (conda)
```

**Comment by stefanv** [comment]
@pgunn I'd like to replicate and address your issue.

With SciPy 1.11.0 and 1.11.4, I'm doing:

```
import scipy
import pickle
empty_csc = scipy.sparse.csc_matrix([0,0])
pickle.loads(pickle.dumps(empty_csc))
```

I don't see a deprecation warning. How does this warning get triggered for you?

**Comment by pgunn** [comment]
Nevermind; our code was doing something weird that was easy to correct. Sorry for the fuss.
