### ISSUE TITLE
scipy.fft.fht - documentation issue

### ISSUE THREAD

**Issue by smcguire88** [scipy/scipy#19573]
### Describe your issue.

In your published documentation for scipy.fft.fht (https://docs.scipy.org/doc/scipy/reference/generated/scipy.fft.fht.html) and scipy.fft.ifht, the formulas you report for the forward and inverse Hankel transforms appear incorrect. For the forward transform, I believe the integral kernel should be written as "a(r) J_u(kr) r dr". For the inverse transform, I believe the integral kernel should be written as "A(k) J_u(kr) k dk". See, for example, the link here:
https://mathworld.wolfram.com/HankelTransform.html
I believe this is just a typo in the documentation but wanted to alert you of it. I also wanted to confirm that the algorithm you developed was based around the correct formula.

### Reproducing Code Example

```python
issue does not concern code
```

### Error message

```shell
issue does not concern code
```

### SciPy/NumPy/Python version and system information

```shell
issue does not concern code
```

**Comment by lucascolley** [comment]
@ntessore mind taking a look?

**Comment by ntessore** [comment]
I get this question so often, it might be best to put a note in the documentation:

The definition as written is not a typo; the DHT and IDHT are commonly defined using $k \\, dr$ and $r \\, dk$, respectively (see for example [Hamilton's excellent reference](https://jila.colorado.edu/~ajsh/FFTLog/fftlog.pdf)). The DHT makes clever use of the convolution theorem for a function of argument $r$, and a kernel of argument $kr = \exp(\ln k + \ln r)$. Defining the integrals using $k \\, dr$ means that, after the logarithmic change of variables, $k \\, dr = kr \\, d{\ln r}$ and we obtain a factor of $kr$ that is absorbed into the kernel. Conversely, using $r \\, dr = r^2 \\, d{\log r}$ would yield a factor of $r^2$ that is absorbed into the function, not the kernel.

Using the definition as it is, one only needs to multiply inputs by $r$ and divide outputs by $k$ to recover the textbook definition of the Hankel transform.

**Comment by lucascolley** [comment]
thanks for the explanation @ntessore ! much appreciated 

@smcguire88 would you like to suggest a note to add to the documentation which would have helped you understand this?

**Comment by smcguire88** [comment]
Thank you for your quick reply. I have no suggestion for a note but, should you wish to add something, I think what you wrote here is quite clear and could be included to avoid any misunderstanding.

**Comment by srinivaspavan9** [comment]
Hi I am interested in contributing to the documentation,
I am trying to set up the project and build the doc using dev.py
but i am getting this error

<img width="482" alt="image" src="https://github.com/scipy/scipy/assets/34889400/d265df9a-a525-431d-ac7e-9c5d4677cec1">

Do i need a 32 bit version of python to build the documentation part or did i do anything wrong ?

I need help

**Comment by lucascolley** [comment]
Hi @srinivaspavan9, could you let us know what steps you have taken so far? In particular, what version of Python do you have? Here are [our instructions for building SciPy from source](http://scipy.github.io/devdocs/building/index.html#building-from-source).

Also, rather than replying on here, it would probably be better to work through this on our Slack space, which you can find at https://scipy.org/community/ (feel free to ping me on there). If that doesn't work for you, please open a new issue here so that anyone else subscribed to this issue doesn't get the noise.
