### ISSUE TITLE
BUG: test_doccer:test_decorator fails with Python 3.13 due to dedented docstring constants

### ISSUE THREAD

**Issue by hroncok** [scipy/scipy#19572]
### Describe your issue.

When I try to build scipy 1.11.3 in Fedora with Python 3.13.0a1+ I see the following test failure:

```
________________________________ test_decorator ________________________________
[gw1] linux -- Python 3.13.0 /usr/bin/python3

    @pytest.mark.skipif(DOCSTRINGS_STRIPPED, reason="docstrings stripped")
    def test_decorator():
        with suppress_warnings() as sup:
            sup.filter(category=DeprecationWarning)
            # with unindentation of parameters
            decorator = doccer.filldoc(doc_dict, True)
    
            @decorator
            def func():
                """ Docstring
                %(strtest3)s
                """
>           assert_equal(func.__doc__, """ Docstring
                Another test
                   with some indent
                """)
E           AssertionError: 
E           Items are not equal:
E            ACTUAL: 'Docstring\nAnother test\n   with some indent\n'
E            DESIRED: ' Docstring\n            Another test\n               with some indent\n            '

scipy/misc/tests/test_doccer.py:86: AssertionError
```

This is likely caused by https://github.com/python/cpython/issues/81283 -- *Automatically dedent docstring constants by default*.

I tried to get around this by asserting the docstrings are equal to manual dostrings, e.g.:

```python
        @decorator
        def func():
            """ Docstring
            %(strtest3)s
            """

        def expected():
            """ Docstring
            Another test
               with some indent
            """
        assert_equal(func.__doc__, expected.__doc__)
```

But I think the dosctring of the original function is dedented first and the substitution happens after; hence the results are not the same as dedented manually constructed docstrings.

I could add if sys.version around the expected value, but I am unsure if that is the proper fix. Before I submit a PR that makes changes to the test, I need to understand how we want this to behave on Python 3.13.

### Reproducing Code Example

```python
run the tests
```

### Error message

```shell
see above
```

### SciPy/NumPy/Python version and system information

```shell
I am no longer able to paste the command above. This is on scipy 1.11.3 with numpy 1.26.0 and Python built from the main branch.
```

**Comment by hroncok** [comment]
> Any chance you can build the docs locally with the dev python version @hroncok?

Sorry, I must have missed this question. Will check.

**Comment by hroncok** [comment]
That still needs pyzmq and greenlet.

**Comment by ev-br** [comment]
Absolutely. 
I suspect these are transitive dependencies of myst-nb. (Does bare sphinx need pyzmq?) 

Also my comment above "this will become a problem in October" is poor wording. Meant to mean "will become a release blocker level problem in October", great to have a forewarning now.

**Comment by hroncok** [comment]
> I suspect these are transitive dependencies of myst-nb.

Yes. The dependency chain is in my comment.

> Does bare sphinx need pyzmq?

No.

**Comment by rgommers** [comment]
Moving this back to 1.14.0, since we do need to solve this in the 1.14.x branch (which will support Python 3.13). Not an actual blocker for 1.14.0, but would be nice to fix soon since it's also needed for adding a 3.13-dev CI job.

**Comment by rgommers** [comment]
gh-20822 added a skip for this test; it should be unskipped and fixed to close this issue.

**Comment by czgdp1807** [comment]
I have started my work on this issue. Will keep updating here.
