### ISSUE TITLE
BUG: Benchmark build with file `dev.py` leads to `invalid syntax` error

### ISSUE THREAD

**Issue by brunolnetto** [scipy/scipy#19571]
### Describe your issue.

I think a good library has good preparation steps.

I (try to) generate a benchmark for my optimization library [`eule`](https://pypi.org/project/eule/). [Following these instructions](https://docs.scipy.org/doc/scipy/dev/contributor/benchmarking.html) led me to the error log presented on a further section.  I hope other developers do not stumble on such as well. 

### Reproducing Code Example

```python
Run command `python dev.py bench`
```

### Error message

```shell
File "dev.py", line 210
    console.print(f'[red bold] {msg}')
                ^
SyntaxError: invalid syntax
```

### SciPy/NumPy/Python version and system information

```shell
scipy: 1.8.1
numpy: 1.24.1

System info:
`Linux falcon 5.15.0-88-generic #98~20.04.1-Ubuntu SMP Mon Oct 9 16:43:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
```

(For some reason, python file with provided code is unable to find INSTALLED scipy. I grepped command run `pip list`, and for sys info from `uname -a`)

**Comment by ev-br** [comment]
Cannot repro:

```
$ mamba activate scipy-dev
(scipy-dev) br@gonzales:~/repos/scipy/scipy$ python dev.py bench
💻  ninja -C /home/br/repos/scipy/scipy/build -j4
ninja: Entering directory `/home/br/repos/scipy/scipy/build'
[4/4] Generating scipy/generate-version with a custom command
Build OK
💻  meson install -C build --only-changed
Installing, see meson-install.log...
Installation OK
SciPy from development installed path at: /home/br/repos/scipy/scipy/build-install/lib/python3.10/site-packages
Running benchmarks for Scipy version 1.12.0.dev0+1915.e1fbf4f at /home/br/repos/scipy/scipy/build-install/lib/python3.10/site-packages/scipy
· Unknown environment type 'mamba'
· Discovering benchmarks
· Running 305 total benchmarks (1 commits * 1 environments * 305 benchmarks)
[  0.00%] ·· Benchmarking existing-py_home_br_mambaforge_envs_scipy-dev_bin_python
[  0.16%] ··· blas_lapack.GetBlasLapackFuncs.time_find_best_blas_type                 ok
[  0.16%] ··· ======== ======== ============ ============ ====== ==========
               dtype1   dtype2   dtype1_ord   dtype2_ord   size            
              -------- -------- ------------ ------------ ------ ----------
                 b        d          C            C         10    66.1±0μs 
                 b        d          C            C        100    250±0μs  
                 b        d          C            C        1000   103±0μs  
                 b        d          C            F         10    283±0μs  
....
```

So first things first:
- can you build/test scipy? `$ python dev.py test`
- if not, can you redo in a fresh virtualenv / conda env?

**Comment by brunolnetto** [comment]
First of all, thanks for blazing-fast answer. Second, I am unfamiliar with mamba, and do not use Conda, but most of the time either package `virtualenv` or package manager `poetry`. Due number greater than 2 ways to manage virtual environments, I kindly ask you to provide the commands to create a local virtual env given required packages described somewhere on this repo.

**Comment by ev-br** [comment]
No idea about `mypy_requirements.txt`, am not surprised that it's incomplete though :-).

IME `virtualenv` is perfectly fine, was a long-time happy user of `vitualenvwrapper`. Standard library `venv` should also work just fine. Not sure about poetry, it has some ideosyncrasies, there was something about it just a couple of days ago.
My experience is to just keep `pip install`-ing things asked for by the build. Click and doit (it's lowercase I not lowercase l BTW) and indeed required by dev.py itself. 

For completeness, here's a pip freeze of a virtualenv which works of just about (was definitely OK a couple of months ago). Most of stuff there comes from matplotlib and jupyter, you don't strictly need those.

```
$ pip freeze
alabaster==0.7.12
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
attrs==21.4.0
Babel==2.10.1
backcall==0.2.0
beautifulsoup4==4.11.1
beniget==0.4.1
bleach==5.0.1
certifi==2022.5.18.1
cffi==1.15.1
cftime==1.6.1
charset-normalizer==2.0.12
click==8.1.3
cloudpickle==2.1.0
commonmark==0.9.1
contourpy==1.0.6
cycler==0.11.0
Cython==0.29.33
debugpy==1.6.3
decorator==5.1.1
defusedxml==0.7.1
docutils==0.18.1
doit==0.36.0
entrypoints==0.4
executing==0.8.3
fastjsonschema==2.16.2
flake8==4.0.1
fonttools==4.33.3
gast==0.5.3
gnureadline==8.1.2
idna==3.3
imagesize==1.3.0
importlib-metadata==4.11.4
importlib-resources==5.9.0
iniconfig==1.1.1
ipykernel==6.16.0
ipython==8.3.0
ipython-genutils==0.2.0
ipywidgets==8.0.2
jedi==0.18.1
Jinja2==3.1.2
jsonschema==4.16.0
jupyter==1.0.0
jupyter-console==6.4.4
jupyter-core==4.11.1
jupyter_client==7.3.5
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.3
kiwisolver==1.4.2
line-profiler==3.5.1
MarkupSafe==2.1.1
matplotlib==3.6.1
matplotlib-inline==0.1.3
mccabe==0.6.1
meson==0.64.0
mistune==2.0.4
nbclient==0.6.8
nbconvert==7.1.0
nbformat==5.6.1
nest-asyncio==1.5.6
netCDF4==1.6.0
ninja==1.10.2.3
notebook==6.4.12
numpy==1.21.1
numpydoc==1.4.0
packaging==21.3
pandas==1.4.3
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.1.1
pkgutil_resolve_name==1.3.10
pluggy==1.0.0
ply==3.11
pooch==1.6.0
prometheus-client==0.14.1
prompt-toolkit==3.0.29
psutil==5.9.2
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
pybind11==2.9.2
pycodestyle==2.8.0
pycparser==2.21
pydata-sphinx-theme==0.9.0
pydevtool==0.2.0
pyflakes==2.4.0
Pygments==2.12.0
pyparsing==3.0.9
pyrsistent==0.18.1
pytest==7.1.2
python-dateutil==2.8.2
pythran==0.11.0
pytz==2022.1
pyzmq==24.0.1
qtconsole==5.3.2
QtPy==2.2.1
requests==2.27.1
rich==12.4.1
rich-click==1.4
-e git+ssh://git@github.com/ev-br/scpdt.git@33f3bb1c619f77e92ca5802016fab3b16c505a99#egg=scpdt
Send2Trash==1.8.0
six==1.16.0
snowballstemmer==2.2.0
soupsieve==2.3.2.post1
Sphinx==5.0.2
sphinx-panels==0.6.0
sphinx-tabs==3.4.1
sphinx_design==0.2.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
stack-data==0.2.0
terminado==0.16.0
tinycss2==1.1.1
tomli==2.0.1
tornado==6.2
traitlets==5.4.0
typing_extensions==4.2.0
urllib3==1.26.9
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==4.0.3
zipp==3.8.0
```

**Comment by ev-br** [comment]
The definitive list of dependencies is here: https://github.com/scipy/scipy/blob/main/pyproject.toml

That said, for development you're using `python dev.py SUBCOMMAND`, and that does not download/install packages like pip does. So I would (and did, more than once) start from a fresh virtualenv, install the required dependencies (numpy, cython, meson, meson-python, pybind11, pythran). Then probably you'd need 
```  
    "rich-click",
    "click",
    "doit>=0.36.0",
    "pydevtool",
```
part of `pyproject.toml`  to run `python dev.py`. This is probably enough to build. To test, you need `pytest`, to run benchmarks you need `asv`.

**Comment by brunolnetto** [comment]
I am not a great fan of installation under demand (try-check-install-repeat). At this point, scipy has become a dish with so many spices, it is bloated to start developing on. xD

Anyhow, I changed two libraries from your list `meson==1.1.0` and `Cython==0.29.35`, due requirement of command run `python dev.py test`. It was not sufficient, still got error below

```
meson.build:80:0: ERROR: Unknown compiler(s): [['gfortran'], ['flang'], ['nvfortran'], ['pgfortran'], ['ifort'], ['ifx'], ['g95']]
```

**Comment by ev-br** [comment]
You'll need C and Fortran compilers indeed: https://docs.scipy.org/doc/scipy/building/index.html
(gcc and gfortran are known to work)

**Comment by brunolnetto** [comment]
Idea: Update dev tutorial somewhere and  add this pip-requirements as you suggested me to install.

Traceback:

```
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency xsimd found: NO (tried pkgconfig and cmake)
Run-time dependency threads found: YES
Library npymath found: YES
Library npyrandom found: YES
pybind11-config found: NO need ['>=2.10.4']
Run-time dependency pybind11 found: NO (tried pkgconfig, config-tool and cmake)

scipy/meson.build:84:15: ERROR: Dependency "pybind11" not found, tried pkgconfig, config-tool and cmake
```

**Comment by ilayn** [comment]
https://docs.scipy.org/doc/scipy/building/index.html#building-from-source-for-scipy-development

Under this section dev requirements are given. It's not a walk in the park when you have this many 3rd party nonpython packages. Hence please take your time. This is a very very nontrivial task you are doing.

**Comment by brunolnetto** [comment]
I tried building from source as suggested:

```
# To build a development version, you need a local clone of the SciPy git repository:
git clone https://github.com/scipy/scipy.git
git submodule update --init
pip install .
```

Even by command run `pip install .`, I received following error output log. 

```
SciPy 1.12.0.dev0
    
      User defined options
        Native files: /tmp/pip-req-build-k8vtzugk/.mesonpy-ncw0x2ca/meson-python-native-file.ini
        buildtype   : release
        b_ndebug    : if-release
        b_vscrt     : md
    
    Found ninja-1.11.1.git.kitware.jobserver-1 at /tmp/pip-build-env-567l5ytg/normal/bin/ninja
    
    ('\x1b[31m',)meson-python: error: Package requires Python version >=3.9, running on 3.8.10
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/brunolnetto/github/scipy/myenv/bin/python3 /tmp/tmp205wijh6 prepare_metadata_for_build_wheel /tmp/tmpdfioxhz7 Check the logs for full command output.
```

Please, take a walk at the park, run you fool. xD , Thanks for the help sofar!

**Comment by ev-br** [comment]
> meson-python: error: Package requires Python version >=3.9, running on 3.8.10

This

**Comment by brunolnetto** [comment]
Is it bad, doctor?

**Comment by rgommers** [comment]
Python 3.8 is too old, the minimum version is 3.9. Please try to read the error messages carefully @brunolnetto. 

_all_ of your issues with using a virtualenv, needing C/C++/Fortran compilers, etc. are either well documented in http://scipy.github.io/devdocs/building/index.html or have a very clear error message. Next you're going to hit needing BLAS/LAPACK, which is nontrivial on Windows - especially if you don't use Conda. 

Please read those docs and error messages carefully, and if and when you still run into problems, ask for help again in a new issue (with the side comments about how everything is bad please). I will close this issue here, because it's all questions that have been answered or things you missed in the docs..
