### ISSUE TITLE
BENCH: spatial.distance.* "non-xdist" benchmarks

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#19596]
As @lgeiger noted at https://github.com/scipy/scipy/pull/19589#issuecomment-1826400845, we may want to consider expanding the `spatial` `asv` benchmarks to include the "single-vector" distance funcs (non-"xdist"). I think this maybe wasn't a priority in the past because how heavily-used the `cdist`/`pdist` flavors are, by comparison.

Probably low priority, but useful for i.e., assessing PRs that affect the single-vector versions.

**Comment by willtryagain** [comment]
hello.
by non xdist single vector do you mean squareform only? or also test for the predicates which check validity and find num observations?

**Comment by tylerjereddy** [comment]
> by non xdist single vector do you mean squareform only? 

I mean distance calculations that are not `pdist` or `cdist`; if you go to the page in the docs for distance calculations (https://scipy.github.io/devdocs/reference/spatial.distance.html#module-scipy.spatial.distance) and scroll down you'll see two sections:

> Distance functions between two numeric vectors u and v. Computing distances over a large collection of vectors is inefficient for these functions. Use pdist for this purpose.

> Distance functions between two boolean vectors (representing sets) u and v. As in the case of numerical vectors, pdist is more efficient for computing the distances between all pairs.

We prioritized benchmarks for `pdist`/`cdist`, so the slower single-vector versions could use some attention, though it probably isn't high-priority since `cdist`/`pdist` are often used for the large performance-critical case (since they accept multiple records/points).
