### ISSUE TITLE
DOC: Adding examples to the DOCSTRING of kstatvar function in the _morestats package

### ISSUE THREAD

**Issue by amohan826** [scipy/scipy#19607]
### Issue with current documentation:

No examples present in this function. I'll be trying to add an example by testing the function with different inputs and outputs. 

https://scipy.github.io/devdocs/reference/generated/scipy.stats.kstatvar.html#scipy.stats.kstatvar

As this is my first issue resolution, kindly help me if I'm doing it wrong anywhere.

**Comment by amohan826** [comment]
@melissawm As suggested by you during previous Sci-py call (Issue #7168 ), I have picked up a function kstatvar in _morestats.py that doesn't have examples in its documentation.  I'm forking this repo now. Will update you with progress.

**Comment by j-bowhay** [comment]
Thanks @amohan826 examples are very much welcome but I will close this issue as we are already tracking it in https://github.com/scipy/scipy/issues/7168
