### ISSUE TITLE
BUG: logm(expm(x)) != x

### ISSUE THREAD

**Issue by harrkee** [scipy/scipy#19602]
### Describe your issue.

Taking a matrix logarithm after a matrix exponential does not return the original array. To make things weirder, if I take the log first, then the exponential, I do correctly recover the original array.

I have attached the array (it is an .npy file, but has been renamed to .zip because the issue creator complained). It is a real-valued, antisymmetric matrix. So its exponential should be special orthogonal, which indeed it is (shown below). So I expect this is a problem with the logm part.

[example_array.zip](https://github.com/scipy/scipy/files/13478317/example_array.zip)

### Reproducing Code Example

```python
import numpy as np
from scipy.linalg import logm, expm

x = np.load("example_array.zip")
print(np.allclose(logm(expm(x)), x))
print(np.allclose(expm(logm(x)), x))

# is the matrix exponential special orthogonal?
u = expm(x)
print(np.allclose(u@u.T, np.eye(10)))
print(np.linalg.det(u))
```

### Error message

```shell
-
```

### SciPy/NumPy/Python version and system information

```shell
1.11.4 1.23.5 sys.version_info(major=3, minor=11, micro=5, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.0
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 14.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 14.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 12.1.0
  pythran:
    include directory: ../../pip-build-env-xp5pbjk1/overlay/lib/python3.11/site-packages/pythran
    version: 0.14.0
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: true
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cibw-run-gft7gyfb/cp311-macosx_arm64/build/venv/bin/python
  version: '3.11'
```

**Comment by ilayn** [comment]
Did you check if the exponential overflows or not? And what do you get from that code block as a result? 

Please don't put zip files for security reasons, prefer gists or any other source where text source can be read.

**Comment by rkern** [comment]
[Matrix logarithms are not unique](https://en.wikipedia.org/wiki/Logarithm_of_a_matrix#Existence). The result you get from `logm(expm(x))` is the principal logarithm where the imaginary component of the eigenvals is restricted to `[-pi, +pi]`. The imaginary components of `eigvals(x)` sometimes go outside of those bounds and so it is not the principal logarithm of `u`. It is expected that `expm(logm(u))` recapitulates `u` but not that `logm(expm(x))` recapitulates `x`.

**Comment by harrkee** [comment]
> Did you check if the exponential overflows or not? And what do you get from that code block as a result?
> 
> Please don't put zip files for security reasons, prefer gists or any other source where text source can be read.

My apologies, I've updated my initial comment to provide the array as a txt file.
There is no overflow in the exponential; the largest element of x is only ~2.6.

**Comment by rkern** [comment]
Yes, the non-uniqueness is still the case for real-valued `x` and `u`. You can confirm that `logm(u)` is a second valid logarithm of `u` (up to numerical accuracy) by comparing `np.allclose(expm(logm(u)), expm(x))`.

`logm(u)` computes the principal logarithm, at least in this case. You can confirm this by looking at `eigvals(logm(u)).imag` and comparing with `eigvals(x).imag`.
