### ISSUE TITLE
BUG: Linprog deprecated

### ISSUE THREAD

**Issue by mariusmarin98** [scipy/scipy#19614]
### Describe your issue.

Method linprog from scipy.optimize doesn't actually detect method = 'highs' and says I am using something else, which won't let me solve LP problems

### Reproducing Code Example

```python
def two_phase_method(c, A, b):

    num_original_vars = len(c)
    num_artificial_vars = len(b)
    A_artificial = np.hstack((A, np.eye(num_artificial_vars)))
    c_artificial = np.hstack((np.zeros(len(c)), np.ones(num_artificial_vars)))

    res_phase1 = linprog(c_artificial, A_eq=A_artificial, b_eq=b, method='highs')
    if not res_phase1.success:
        raise ValueError("No feasible solution found in Phase 1")

    x0_original = res_phase1.x[:num_original_vars]

    res_phase2 = linprog(c, A_eq=A, b_eq=b, method='highs', x0=x0_original)
    return res_phase2
```

### Error message

```shell
`method='{meth}'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
```

### SciPy/NumPy/Python version and system information

```shell
Scipy 1.11.4
Python 3.12
Numpy 1.26.1
```

**Comment by lucascolley** [comment]
Hi @mariusmarin98 , I haven't been able to reproduce the error message. Please can you give us a single call to `linprog`, including the values of the arguments, which gives you this error? There's certainly something strange going on, as the f-string to fill the message with `meth` doesn't seem to be working.
