### ISSUE TITLE
ENH: add best cost function evaluation to differential evolution callback

### ISSUE THREAD

**Issue by FlorianPix** [scipy/scipy#19612]
### Is your feature request related to a problem? Please describe.

During the optimization progress I'd like to monitor the improvement of the cost function.

### Describe the solution you'd like.

Add the cost of the best candidate so far as a parameter to the callback.

### Describe alternatives you've considered.

Print out or overwriting a global variable in the cost function.

**Comment by andyfaff** [comment]
In 1.12 there will be an amended callback which will give all the information you need. In the meantime you can track the best solution so far by a few methods. e.g. you could write a wrapper to track the best solution so far.
