### ISSUE TITLE
DOC: issue in documentation for the callback argument in scipy.optimize.minimize

### ISSUE THREAD

**Issue by seraf-m** [scipy/scipy#19636]
### Issue with current documentation:

Hi,
while testing and learning about the different minimizers available for use in the minimize function, I tried implementing a callback function, and had some problems doing so, mainly because of my unfamiliarity with typing hints in Python.
I do believe however the words in the example call/siganture of the callback function should be inverted - i.e. `callback(intermediate_result: OptimizeResult)`,
 and *not* 
`callback(OptimizeResult: intermediate_result)`.

### Idea or request for content:

The least effort change would indeed be to just invert the concerning words, as it would probably lead someone unfamiliar with type hinting (that is signatures of the type `fun(a: int, b: str,..)` etc. and not the more ordinary `fun(a, b, **kwargs)` to a working solution quicker - even faster if it is not assumed the user did `from scipy.optimize import *` and changing the example to 
`callback(intermediate_result: scipy.optimize.OptimizeResult)`.
Optionally some mention of the function signature using type hinting in the sentence about using introspection to determine the argument passed to the callback would have been educational to someone like me. :)
Other than that, I want to thank you all for the amazing work you do!

### Additional context (e.g. screenshots, GIFs)

![scipy_report](https://github.com/scipy/scipy/assets/77552363/ab8c9beb-8931-4bc1-a75e-df48608888cf)

**Comment by andyfaff** [comment]
Thank you for picking that up @seraf-m. I think that was fixed in #19429
