### ISSUE TITLE
ENH: Add F-test of equality of variances to scipy.stats

### ISSUE THREAD

**Issue by NortaBirdo** [scipy/scipy#19646]
### Is your feature request related to a problem? Please describe.

Hello everyone.

I'd like to suggest to add [F-test of equality of variances](https://en.wikipedia.org/wiki/F-test_of_equality_of_variances) to `scipy.stats`. Dispite the test is sensitive to non-normality of distribution rather other implemented tests in `scipy` (i.e. Levene), the F-test is one of basic statistic test and used widely.

There are plenty search requests like "how to perform an f-test in python" in google and at common developers' platforms and related articles. I listed below some of them:
- [stackoverflow.com](https://stackoverflow.com/questions/21494141/how-do-i-do-a-f-test-in-python), viewed 91k times, has a solution with 58 likes.
- [geeksforgeeks.org](https://www.geeksforgeeks.org/how-to-perform-an-f-test-in-python/)
- [statology.org](https://www.statology.org/f-test-python/)

All these resources copy the same simple idea based on the scipy function.

Moreover, the second common used statistic language - R has [a realisation of the test](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/var.test)

### Describe the solution you'd like.

I propose to add function `f_equality_test`.

Description: Test the null-hypothesis that the two given samples have the same variance.

Parameters:
- x, y, array-like. The sample data, possibly with different lengths. Only one-dimensional samples are accepted

Returns:
- statistic: float. Calculated f-statistic
- pvalue: float. Calculated p-value for the test.

The implementation could be taken from materail of [Dr. Anoop Kumar Singh, Lucknow University ](https://www.lkouniv.ac.in/site/writereaddata/siteContent/202004261258144523Anoop_Applied_ANNOVA.pdf). As far as I know the method is originaly described in Statistical Methods, 8th Edition by George W. Snecdecor, William G. Cochran.
There are many links to author's book, unfortunately I didn't find it in the free access to check.

Shortly:
- calculate s  as sum(x_i - mean (x))/n-1 for the both samples
- calculate degree of freedom for as n-1 for the both samples
- calculate f = larger s / smaller s
- calculate pvalue using scipy.stats.f.cdf

Note:
The test has an assamption that both samples have normal distribution.

**Comment by tupui** [comment]
Thank you @NortaBirdo for the proposal, and sorry for the late reply.

I am closing the issue since we decided not to move forward with it. Please see the linked PR #20810 for the discussion.
