### ISSUE TITLE
ENH: as_quat() and from_quat() seams to be reverse x,y,z,w vs w,x,y,z

### ISSUE THREAD

**Issue by patgadget** [scipy/scipy#19649]
### Is your feature request related to a problem? Please describe.

I was trying to use the quaternion in scipy, and I found out that the format of the quaternion in scipy seams to be in a different order than the wiki page.

On your page:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.from_quat.html
You say:
"Each row is a (possibly non-unit norm) quaternion representing an active rotation, in scalar-last (x, y, z, w) format. Each quaternion will be normalized to unit norm."
but the example seams to have the scalar in front?
```
r = R.from_quat([1, 0, 0, 0])
r.as_quat()
array([1., 0., 0., 0.])
```

At the wiki link that you provide on your doc web page, https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation
, it also says that the format is w, x, y, z
Wikipedia page says:
"We can avoid this by using four Euclidean coordinates w, x, y, z, ..."
 
I am using a ABB robot and the documentation also says that the quaternion is in the format w, x, y, z.
see link: https://developercenter.robotstudio.com/api/robotstudio/api/ABB.Robotics.Math.Quaternion.html
q1, q2, q3, q4
q1 Scalar part: q1, Vector part: q2, q3, q4

### Describe the solution you'd like.

To add a configuration for the quaternion.
same as Euler angle that have the possibility to be configure as 'XYZ' or 'ZYX'
```
Rotation.from_quat(type cls, quat, conf = 'wxyz')
```
Without conf, from_quat could have by default 'xyzw', and this could be backward compatible.

### Additional context (e.g. screenshots, GIFs)

English is not my native language, I could have made a few typo here and there.
Thanks and sorry

**Comment by lucascolley** [comment]
To the enhancement request: this has 4 requests now, with a seemingly working implementation previously reverted and a +0 from a maintainer; seems worth another look?

x-ref gh-14548, gh-15410,  gh-15431
ping @nmayorov @pmla
cc @alspitz @jmw182 @RTnhN

To the supposed example inconsistency: I don't have the knowledge to confirm but I would be surprised if this went unnoticed for five years

**Comment by rkern** [comment]
There's no inconsistency in the example. You get the same quaternion that was put in with `x=1` and the rest 0s. The scalar `w` is simply `0` in both input and output. That's a valid quaternion.

Whether `w` goes at the front or the back is just a matter of convention. Wikipedia's use of `wxyz` is not an indication that the `xyzw` convention doesn't exist or is wrong.

**Comment by patgadget** [comment]
Thanks,,

If quaternion ordering wxyz, or xyzw is just a convention, Euler angle could be XYZ or ZYX is also
but in the as_euler, from_euler we have the possibility to tell scipy the ordering, but not in as_quat, from_quat

Wikipedia alone is not an indication, but this the site that you refer to in the documentation

In my research on the web about the quaternion ordering, I do find more reference to the wxyz than the xyzw
You are right that both convention exist, but it looks like the xyzw is less common in my opinion.

For example, in the github site: https://github.com/clemense/quaternion-conventions
30 use wxyz and 21 use xyzw

I can easilly swap the quaternion myself before or after i receive them from scipy, 
but it would be a nice to have option directly in scipy

Thanks.
Pat

**Comment by patgadget** [comment]
Hi,
This is what i have done to shift / rotate the quaternion

```
def from_xyzw_to_wxyz(quat = [0, 0, 0, 1]):
    return quat[-1:] + quat[:-1]

def from_wxyz_to_xyzw(quat=[1, 0, 0, 0]):
    return quat[1:] + quat[:1]
```

Thanks
Pat

**Comment by scottshambaugh** [comment]
Recommend closing this issue as won’t-do. There are at least 16 permutations of different quaternion conventions (w location being one choice). Switching the ordering is a simple user operation, this can be such a complex topic that I think it’s more important to stick to one convention and be clear about it than to give toggles for all the options. 

See: https://arxiv.org/pdf/1801.07478.pdf, https://www.researchgate.net/publication/278619675_Quaternion_kinematics_for_the_error-state_KF

**Comment by alspitz** [comment]
There are only two: w first or w last. scipy supports different Euler conventions, I don't see why it shouldn't support different quaternion conventions. Ingesting and outputting quaternions between different libraries of different conventions is quite common and having this option would be a great usability improvement.

**Comment by scottshambaugh** [comment]
My point about conventions was not just about ordering, but also several other binary convention choices that can be made (see table 1 of the second link). Quaternion convention mismatch is a  huge source of tricky errors when integrating different systems. 

But the comparison to the Euler angles is fair, I agree now that a `seq = {‘xyzw’, ‘wxyz’}` argument similar to Euler angles would be an easy addition, and the existence of that option might help bring visibility to the default ordering as well.

**Comment by nmayorov** [comment]
Adding arguments `scalar_last=True` (or `scalar_first=False`) to `from_quat` and `as_quat` is reasonable and seamless addition.

@scottshambaugh would you make a PR for that?
