### ISSUE TITLE
gmean() returns `nan` when a 0 value is given a 0 weight?

### ISSUE THREAD

**Issue by pinusm** [scipy/scipy#19647]
### Describe your issue.

When I try to compute the weighted geometric mean of an array that includes 0, and that element is given a weight of 0, I'm getting a RuntimeWarning, and a `nan` result.
This isn't the case when the weight is just slightly larger than zero.

Drilling this down, I reached np.multiply(), but I'm not familiar enough with python/C to dig deeper.. 

### Reproducing Code Example

```python
from scipy.stats import gmean
import sys

print(gmean([1, 1], weights=[1,0]))
# 1.0
print(gmean([0, 1], weights=[1,0]))
# 0.0
print(gmean([1, 0], weights=[1,0]))
# nan
# RuntimeWarning: invalid value encountered in multiply avg = np.multiply(a, wgt,

eps = sys.float_info.epsilon
print(gmean([1, 0], weights=[1, 0+eps]))
# 0.0
```

### Error message

```shell
C:\Users\REDACTED\anaconda3\envs\REDACTED\lib\site-packages\numpy\lib\function_base.py:550: RuntimeWarning: invalid value encountered in multiply
  avg = np.multiply(a, wgt,
```

### SciPy/NumPy/Python version and system information

```shell
1.11.4 1.23.5 sys.version_info(major=3, minor=10, micro=10, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: c:/opt/64/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: c:/opt/64/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  pythran:
    include directory: C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-4cqqe0_2\overlay\Lib\site-packages/pythran
    version: 0.14.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  cross-compiled: true
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
Python Information:
  path: C:\Users\runneradmin\AppData\Local\Temp\cibw-run-6sotklje\cp310-win_amd64\build\venv\Scripts\python.exe
  version: '3.10'
```

**Comment by mdhaber** [comment]
There is a 0 times infinity in the calculation, and it looks like the limit may not be defined. 1.0 would be the appropriate result if 0 weight means "omit this value entirely". Would it be better for it to return 1 when the weight is exactly 0 and return 0 when the weight is `eps`?

**Comment by mdhaber** [comment]
Is there precedent for that convention in a publication or other software library?

**Comment by mdhaber** [comment]
> Also, in `numpy.average` this is the apparent behavior:

I don't think so. `np.average` is the reason `gmean` returns the NaN here.

```python3
import numpy as np
np.average([1, np.inf], weights=[1, 0])
#19628  RuntimeWarning: invalid value encountered in multiply
#  avg = np.multiply(a, wgt,
# nan
```

**Comment by steppi** [comment]
> This is a case for changing `np.average`, and if so, `gmean` would follow suit.

For the sake of consistency, I agree that the behavior should follow that of `np.average`.   @pinusm, do want to submit an issue to NumPy?

**Comment by pinusm** [comment]
I submitted the issue to NumPy.
Not sure whether this should be closed or kept open in pending status, so leaving this up to you.

**Comment by steppi** [comment]
@pinusm, as a heads up, this isn’t a bug.  `nan` is perfectly acceptable answer here since this case leads to an indeterminate expression. You’re asking for a change to another behavior which would also be consistent and acceptable in my opinion. In your NumPy issue, you should try to justify why the change would be worth breaking backward compatibility for.

**Comment by mdhaber** [comment]
I don't think this needs to be tracked here because `gmean` will automatically do what `np.average` does.
