### ISSUE TITLE
CI, MAINT: pre-release job failures with scipy-openblas32

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#19640]
In case it isn't obvious, newer/pre-release versions of `scipy-openblas32` are the source of the failures in that CI job that show linear algebra symbol issues. Example log at: https://github.com/scipy/scipy/actions/runs/7104057689/job/19338202610?pr=18151

I don't think that's too urgent, and Matti is pretty busy I think, so we could always pin temporarily if we want. Or we could try `-DBLAS_SYMBOL_PREFIX=scipy_` compile-time directive (?) based on what he said previously at https://github.com/scipy/scipy/pull/19484. It is easy to reproduce locally at least, so we have good traction on it.

I think a small build system shim might be needed to pass `BLAS_SYMBOL_PREFIX` through perhaps, but I will likely be focused on release duties for a bit longer.

**Comment by rgommers** [comment]
The symptom here is:
```
_fblas.cpython-39-x86_64-linux-gnu.so: undefined symbol: dznrm2_
```

I'll have a look at fixing this up.
