### ISSUE TITLE
eliminate_zeros() does not work when csr_matrix.data is of format np.float16

### ISSUE THREAD

**Issue by rubenahrens** [scipy/scipy#19655]
https://github.com/scipy/scipy/blob/f2ec91c4908f9d67b5445fbfacce7f47518b35d1/scipy/sparse/compressed.py#L907C6-L907C6

**Comment by lucascolley** [comment]
Hi @rubenahrens please can you provide a reproducing example and the error message/unexpected behaviour you see, as well as your SciPy/NumPy/Python versions?

**Comment by perimosocordiae** [comment]
Closing this as "won't fix" as float16 isn't one of our supported dtypes. See gh-20207 and gh-7408 for more context.

**Comment by lesteve** [comment]
OK thanks for your answer! I would guess that some scikit-learn tests were using this without a particularly good reason, but we need to look at in more details.
