### ISSUE TITLE
BUG: memory issues in mannwhitneyu with unbalanced data

### ISSUE THREAD

**Issue by mrogers-phd** [scipy/scipy#19692]
### Describe your issue.

One of our pipelines calls the `mannwhitneyu` method using the "two-sided" alternative.  We've noticed that the method can consume a substantial amount of RAM. For example, in a call with a total of 17,002 values the `mannwhitneyu` call peaks at nearly 24GB of RAM.

There appears to be a memory leak as well.  Sometimes a single call such as the one above will finish despite the huge memory footprint.  However if our pipeline calls it several times, eventually the process fails with an out-of-memory error.

Full disclosure, some of our users provide data that becomes wildly unbalanced, e.g., 2 values in one array and 17,000 in the other (see example code).  I don't know what impact that will have on the method.  We're investigating ways to prevent such unbalanced calls on our end.  However, the issue remains that even with more balanced data this method uses far more memory than one would expect.

### Reproducing Code Example

```python
"""
Example of scipy.stats.mannwhitneyu memory issues
"""
import numpy
from scipy.stats import mannwhitneyu
A = [-0.0123, -0.1023]
B = numpy.random.uniform(low=-1, high=1, size=17000)
# On an M1 Mac with 24GB allocated to Docker containers, this will take
# about 5 minutes before it runs out of memory inside a container:
result = mannwhitneyu(A, B, alternative="two-sided")
```

### Error message

```shell
Killed
```

### SciPy/NumPy/Python version and system information

```shell
Rocky Linux 9
confirmed on scipy version 1.10.0 and 1.11.4
```

**Comment by mdhaber** [comment]
Like many SciPy functions, `mannwhitneyu` doesn't consider the memory limitations of your machine when deciding which method to use. If either of the two samples has fewer than 8 observations, and `method='auto'` (the default), it still chooses the exact method, which can consume large amounts of memory. You can select `method='asymptotic'`, and I don't think you'll have problems, but the result won't necessarily be accurate. 
```python3
result = mannwhitneyu(A, B, alternative="two-sided", method='asymptotic')
# MannwhitneyuResult(statistic=16159.0, pvalue=0.9036158130132622)
```
Your best bet is probably to estimate the p-value using a randomized permutation test. Some of the last digits will fluctuate between individual runs, but in the long term it almost exactly controls the false positive error rate. If that sounds acceptable, I can suggest some code.

**Comment by mrogers-phd** [comment]
Many thanks for your response, and for helping me understand the increasing memory issue.  In our case, we may get every one of the combinations of 1, 2, ..., 8 vs. 17,000, in addition to many others, so I think that explains the big memory hit after ~400 calls or so.  I will try to build an example script in the next day or so to share with you.

Thanks also for the permutation test example.  We did find the `method="asymptotic"` fix yesterday, but it's entirely possible we'll see misleading p-values with those small `A` samples.

**Comment by mrogers-phd** [comment]
I've finally had a moment to create an example (attached below) where the memory footprint grows gradually until it consumes all available memory, at least on a system (Docker image) limited to 16GB.  I believe the same could happen for systems with up to 32GB.

I added some rudimentary timing and ran each `mannwhitneyu` call twice to see the impact of the optimization.  Surprisingly, there appears to be no difference between the two calls.  Perhaps this isn't a fair test of the optimization, but I thought it worth pointing out.

[example.zip](https://github.com/scipy/scipy/files/13717294/example.zip)

**Comment by lucascolley** [comment]
hi @mrogers-phd, please upload the data to a source where the text source can be read, `zip` files are deemed a security risk

**Comment by mrogers-phd** [comment]
Argh.  When I tried to upload just the python script, github asked for a different file type such as `.zip`.  Probably just as simple to show the source itself:
```
#! /usr/bin/env python3
import numpy
import time
from scipy.stats import mannwhitneyu

# Docker image with 16GB memory (host computer has 32GB)
# A (size 2) vs B (size 5000)
#   p-value:  0.77147 (compute time 31.5 secs)
#   2nd call: 0.77147 (compute time 30.8 secs)
# A (size 3) vs B (size 5000)
#   p-value:  0.99235 (compute time 72.7 secs)
#   2nd call: 0.99235 (compute time 73.1 secs)
# A (size 4) vs B (size 5000)
#   p-value:  0.4283 (compute time 92.2 secs)
#   2nd call: 0.4283 (compute time 91.6 secs)
# A (size 5) vs B (size 5000)
# Killed

# Large baseline sample for all comparisons
rng = numpy.random.default_rng(12345)
B = rng.uniform(low=-1, high=1, size=5000)

# Source list for small samples:
#A_source = [-0.0123, -0.1023, 0.00234, 0.1132, 0.321, 0.654, 0.0956, 0.3044]
A_source = rng.uniform(low=-1, high=1, size=10)

for i in range(1, len(A_source)):
    # Create subsets for sizes 2, 3, ...
    A = A_source[:i+1]
    print(f"A (size {len(A)}) vs B (size {len(B)})")

    start = time.time()
    result = mannwhitneyu(A, B, alternative="two-sided")
    elapsed = time.time() - start
    print(f"  p-value:  {result.pvalue:.5g} (compute time {elapsed:.1f} secs)")

    start = time.time()
    repeated = mannwhitneyu(A, B, alternative="two-sided")
    elapsed = time.time() - start
    print(f"  2nd call: {result.pvalue:.5g} (compute time {elapsed:.1f} secs)")
```

**Comment by mdhaber** [comment]
Hmm, something is not working as expected. I'll take a look.

**Comment by mrogers-phd** [comment]
Minor copy/paste error there on the last line  (was `result.pvalue`, should have been `repeated.pvalue`) that I've fixed above, but shouldn't have had an impact on the overall results.

**Comment by mdhaber** [comment]
I will look more carefully, but I see that what I've written before doesn't apply - when the size of either sample is greater than 500, we switch from a recursive implementation to an iterative implementation, which doesn't use the table I was referring to. Apparently this means everything is calculated from scratch, so you don't get the speedup. However, this also means that a growing table doesn't explain why you are out of memory on a second call. 

Instead, I notice that the number of calculations that have to be performed and stored depends on the value of the statistic, so that is my new guess for why you might succeed in one call but not the next. It looks like worst case memory usage is $O(m^2n^2)$ in the recursive case, and if the iterative version is similar, the story might be even worse because it uses a dictionary instead of an array for that storage. I'm traveling now but I'll take a closer look when I can.

**Comment by mrogers-phd** [comment]
In our process we can get p-values anywhere in the range (0,1) and our significance threshold is typically p < 0.01.  From what we've observed so far, the asymptotic method works well, though in rare cases it can produce a significant p-value that is slightly higher than the exact method (e.g., 1e-05 instead of 1e-08).  That may become an issue when we later apply multi-test correction.

**Comment by mdhaber** [comment]
Huh, well the p-values provided by the randomized permutation test are not ever going to be less than the reciprocal of the number of resamples, so you'd have the same problem in that case.

Whether the implementation uses iteration or explicit revision, the algorithm is based on a recursive formula. Currently, every evaluation of the function that is being recursed is cached. Perhaps some analysis of the algorithm would reveal ways of reducing this memory consumption. (Of course, maybe there are other, inherently more memory-efficient algorithms.)

I'm not able to look deeply into that right now, but perhaps there is a different solution in the short term: If you don't need super accurate p-values above your significance threshold but do need the precision of the exact method below the threshold, then you could use the approximate p-value as an estimate and refine it using the exact method only if the p-value is small. Theoretically, at least, the memory (and time) required should be less for small p-values.
