### ISSUE TITLE
BUG: 1.12.0rc1: build failure on windows due to unintentional macro usage in boost

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#19726]
It looks like boost is using an unfortunate choice of template variable name on windows, which conflicts with a macro:
```
In file included from ..\scipy\_lib\boost_math\include\boost/math/policies/policy.hpp:11:
..\scipy\_lib\boost_math\include\boost/math/tools/mp.hpp(171,34): error: expected parameter declarator
  171 | template<typename L, std::size_t I>
      |                                  ^
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\complex.h(63,20): note: expanded from macro 'I'
   63 | #define I          _Complex_I
      |                    ^
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\complex.h(62,29): note: expanded from macro '_Complex_I'
   62 | #define _Complex_I _FCbuild(0.0F, 1.0F)
      |                             ^
```

From https://github.com/conda-forge/scipy-feedstock/pull/262, using the vendored boost.

CC @rgommers @tylerjereddy

**Comment by h-vetinari** [comment]
CC @mborland - if you have any opinions about this.

**Comment by rgommers** [comment]
This does not look like a boost.math issue to me. It's using a template parameter named `I` within a namespace, nothing special there. The question is why a `ucrt/complex.h` define is leaking into here for a conda-forge build, while we don't see this issue in our own CI. C++ has `ccomplex` and `complex.h` headers, but those are not used by boost.math; it does use `complex` and `cmath`. From `policy.hpp` and `config.hpp` it looks like `#include <cmath>` happens before the failing line in `mp.hpp` is hit. So my best guess: based on `clang-cl` version or `CXXFLAGS` used by conda-forge, something goes wrong here.

From the CI log:
```
C++ compiler for the host machine: clang-cl (clang-cl 17.0.6)
C++ linker for the host machine: lld-link lld-link 16.0.6
```
and uses `/std:c++14` (which seems right):
```
252/1618] Compiling C++ object scipy/special/_ufuncs_cxx.cp312-win_amd64.pyd.p/meson-generated__ufuncs_cxx.cpp.obj
FAILED: scipy/special/_ufuncs_cxx.cp312-win_amd64.pyd.p/meson-generated__ufuncs_cxx.cpp.obj 
"clang-cl" "-Iscipy\special\_ufuncs_cxx.cp312-win_amd64.pyd.p" "-Iscipy\special" "-I..\scipy\special" "-I..\scipy\_lib\boost_math\include" "-Iscipy\_lib" "-I..\scipy\_lib" "-I..\scipy\_build_utils\src" "-I..\..\_h_env\Lib\site-packages\numpy\core\include" "-I%PREFIX%\Include" "-DNDEBUG" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W2" "/EHsc" "/std:c++14" "/permissive-" "/O2" "-DCYTHON_CCOMPLEX=0" "-Wno-cpp" "-D_USE_MATH_DEFINES" "-DBOOST_MATH_STANDALONE=1" "-DCYTHON_EXTERN_C=extern \"C\"" "-DSP_SPECFUN_ERROR" "/Fdscipy\special\_ufuncs_cxx.cp312-win_amd64.pyd.p\meson-generated__ufuncs_cxx.cpp.pdb" /Foscipy/special/_ufuncs_cxx.cp312-win_amd64.pyd.p/meson-generated__ufuncs_cxx.cpp.obj "/c" scipy/special/_ufuncs_cxx.cp312-win_amd64.pyd.p/_ufuncs_cxx.cpp
In file included from scipy/special/_ufuncs_cxx.cp312-win_amd64.pyd.p/_ufuncs_cxx.cpp:1206:
In file included from ..\..\_h_env\Lib\site-packages\numpy\core\include\numpy/arrayobject.h:5:
In file included from ..\..\_h_env\Lib\site-packages\numpy\core\include\numpy/ndarrayobject.h:12:
In file included from ..\..\_h_env\Lib\site-packages\numpy\core\include\numpy/ndarraytypes.h:1929:
..\..\_h_env\Lib\site-packages\numpy\core\include\numpy/npy_1_7_deprecated_api.h(14,9): warning: ..\..\_h_env\Lib\site-packages\numpy\core\include\numpy/npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION [-W#pragma-messages]
   14 | #pragma message(_WARN___LOC__"Using deprecated NumPy API, disable it with " \
      |         ^
In file included from scipy/special/_ufuncs_cxx.cp312-win_amd64.pyd.p/_ufuncs_cxx.cpp:1211:
In file included from scipy\special\_ufuncs_cxx_defs.h:7:
In file included from ..\scipy\special\boost_special_functions.h:16:
In file included from ..\scipy\_lib\boost_math\include\boost/math/special_functions/beta.hpp:13:
In file included from ..\scipy\_lib\boost_math\include\boost/math/special_functions/math_fwd.hpp:31:
In file included from ..\scipy\_lib\boost_math\include\boost/math/policies/policy.hpp:11:
..\scipy\_lib\boost_math\include\boost/math/tools/mp.hpp(171,34): error: expected parameter declarator
  171 | template<typename L, std::size_t I>
      |                                  ^
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\complex.h(63,20): note: expanded from macro 'I'
   63 | #define I          _Complex_I
      |                    ^
C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\complex.h(62,29): note: expanded from macro '_Complex_I'
   62 | #define _Complex_I _FCbuild(0.0F, 1.0F)
      |                             ^
```

We don't have `clang-cl` in our CI and this worked in conda-forge for the first Meson build of `1.11.x`, but it's now failing for `1.12.x`. So what changed? Clang version, NumPy version, or SciPy code? `boost.math` didn't change in this time period. `complex.h` probably gets pulled in via the `numpy` includes, so a numpy version change to build against could matter.

**Comment by rgommers** [comment]
Adding one more suspect: Cython version:
```
Cython compiler for the host machine: cython (cython 3.0.7)
```

We've had a bunch of churn in `scipy.special` and `cython` related to complex types (in cython 3.0.6 specifically there was a fix). 

The cython-generated `_ufuncs_cxx.cpp` starts with this kind of thing:
```
#if !defined(CYTHON_CCOMPLEX)
  #if defined(__cplusplus)
    #define CYTHON_CCOMPLEX 1
  #elif (defined(_Complex_I) && !defined(_MSC_VER)) || ((defined (__STDC_VERSION__) && __STDC_VERSION__ >= 201112L) && !defined(__STDC_NO_COMPLEX__))
    #define CYTHON_CCOMPLEX 1
  #else
    #define CYTHON_CCOMPLEX 0
  #endif
#endif
#if CYTHON_CCOMPLEX
  #ifdef __cplusplus
    #include <complex>
  #else
    #include <complex.h>
  #endif
#endif
#if CYTHON_CCOMPLEX && !defined(__cplusplus) && defined(__sun__) && defined(__GNUC__)
  #undef _Complex_I
  #define _Complex_I 1.0fj
#endif
```
(note that this interacts with `-DCYTHON_CCOMPLEX=0` in the compile command).

So I think what's needed here is a process of eliminating changes in each package/version involved, to try and narrow down things, unless we can reason about it.

The `CYTHON_CCOMPLEX=0` define comes from gh-18975 (new in 1.12.0), and may be wrong for C++ code. It gets pulled in because in `scipy.meson.build` we copy `cython_c_args` to `cython_cpp_args`, which was fine before - but I think this define is C-specific (@lysnikolaou any thoughts?). See https://github.com/scipy/scipy/pull/18975#issuecomment-1662476226 in particular, it has to do with `complex.h` inclusion.

**Comment by h-vetinari** [comment]
> So what changed? Clang version, NumPy version, or SciPy code? `boost.math` didn't change in this time period.

Clang didn't change, numpy didn't change, but the boost module changed a little:
```diff
>git diff tags/v1.11.4..tags/v1.12.0rc1 -- scipy/_lib/boost_math
diff --git a/scipy/_lib/boost_math b/scipy/_lib/boost_math
index 298a243cc..6bfe5818a 160000
--- a/scipy/_lib/boost_math
+++ b/scipy/_lib/boost_math
@@ -1 +1 @@
-Subproject commit 298a243ccd3639b6eaa59bcdab7ab9d5f008fb36
+Subproject commit 6bfe5818acdf86432f3e1a78ec5e1d3cdb8c6480
```
details [here](https://github.com/boostorg/math/compare/298a243ccd3639b6eaa59bcdab7ab9d5f008fb36..6bfe5818acdf86432f3e1a78ec5e1d3cdb8c6480).

However, I think the cython suspicion might be more relevant; it's the first release where I've reverted the `cython <3` constraint. I'll try how things look with cython 0.29

**Comment by lysnikolaou** [comment]
> but I think this define is C-specific

Hmm, I'm not sure about this, since I don't have context on how C++ complex types handle the kind of situation described in https://github.com/scipy/scipy/pull/18975#issuecomment-1662476226. If it's the same as in C, then we probably need it in C++ as well.

This looks suspiciously similar to https://github.com/serge-sans-paille/pythran/issues/2157. Could you check whether https://github.com/numpy/numpy/commit/82ba4f400abbc8ef740d57f081d804f8412d231b solves the issue?

**Comment by mborland** [comment]
> > The CYTHON_CCOMPLEX=0 define comes from #18975 (new in 1.12.0), and may be wrong for C++ code. It gets pulled in because in scipy.meson.build we copy cython_c_args to cython_cpp_args, which was fine before - but I think this define is C-specific
> 
> Hmm, I'm not sure about this, since I don't have context on how C++ complex types handle the kind of situation described in [#18975 (comment)](https://github.com/scipy/scipy/pull/18975#issuecomment-1662476226). If it's the same as in C, then we probably need it in C++ as well.
> 
> This looks suspiciously similar to [serge-sans-paille/pythran#2157](https://github.com/serge-sans-paille/pythran/issues/2157). Could you check whether [numpy/numpy@82ba4f4](https://github.com/numpy/numpy/commit/82ba4f400abbc8ef740d57f081d804f8412d231b) solves the issue?

This looks to be on the right track since `_Complex_I` is not defined in C++. After the clang-cl issues in the last release we added it to the Boost.Math CI matrix and have not seen anything like this.

CC: @jzmaddock

**Comment by h-vetinari** [comment]
> I'll try how things look with cython 0.29

Same error persists with cython 0.29.37

**Comment by jzmaddock** [comment]
Haven't checked previous versions, but C++20 says: "The C headers <complex.h> and <tgmath.h> do not contain any of the content from the C standard library and instead merely include other headers from the C++ standard library."

So, even if there is a stray include of complex.h somewhere, it should *not* be defining the macro `I`.

That said, we should probably protect ourselves from such things, given that we also take care over min/max and other things which shouldn't be macros.

Ah... easily reproduced too: https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:44,endLineNumber:4,positionColumn:44,positionLineNumber:4,selectionStartColumn:44,selectionStartLineNumber:4,startColumn:44,startLineNumber:4),source:'%0A%23include+%3Ccomplex.h%3E%0A%0A%23include+%3Cboost/math/special_functions.hpp%3E%0A%0Aint+main()%0A%7B%0A+++return+0%3B%0A%7D%0A%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:49.016808150493,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:vcpp_v19_28_VS16_9_x64,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:3,lang:c%2B%2B,libs:!((name:boost,ver:vcpkg)),options:/W4,overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x64+msvc+v19.28+VS16.9+(Editor+%231)',t:'0')),k:25,l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(editorid:1,fontScale:14,fontUsePx:'0',j:3,wrap:'1'),l:'5',n:'0',o:'Output+of+x64+msvc+v19.28+VS16.9+(Compiler+%233)',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:50.983191849507,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4

**Comment by mborland** [comment]
> Haven't checked previous versions, but C++20 says: "The C headers <complex.h> and <tgmath.h> do not contain any of the content from the C standard library and instead merely include other headers from the C++ standard library."
> 
> So, even if there is a stray include of complex.h somewhere, it should _not_ be defining the macro `I`.
> 
> That said, we should probably protect ourselves from such things, given that we also take care over min/max and other things which shouldn't be macros.

I have a workaround here: https://github.com/boostorg/math/pull/1060 that's not unlike our protection for MINMAX.

**Comment by lysnikolaou** [comment]
> Haven't checked previous versions, but C++20 says: "The C headers <complex.h> and <tgmath.h> do not contain any of the content from the C standard library and instead merely include other headers from the C++ standard library."

This is true as far as I can tell, although many implementation [had relevant bugs(https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59087).

FWIW I still think numpy should not incldue `<complex.h>` in C++ code, even if work-arounds exist and can be used, and 2.0 does not do it anymore after https://github.com/numpy/numpy/pull/25313.

**Comment by mborland** [comment]
Fix has been merged into Boost.Math. Let us know if you still have issues after pulling the updated develop branch.

**Comment by h-vetinari** [comment]
Given the comment from https://github.com/microsoft/STL/issues/4281, perhaps the easiest fix is just to compile with C++17?
> Opened [DevCom-10547133](https://developercommunity.visualstudio.com/t/10547133). UCRT should be already fine if you use C++17 or later modes.

**Comment by h-vetinari** [comment]
> perhaps the easiest fix is just to compile with C++17?

Can confirm that `cpp_std=c++17` gets past the `I` macro issues. However, it then runs into another problem:
```
[1013/1618] Compiling C++ object scipy/fft/_pocketfft/pypocketfft.cp310-win_amd64.pyd.p/pypocketfft.cxx.obj
FAILED: scipy/fft/_pocketfft/pypocketfft.cp310-win_amd64.pyd.p/pypocketfft.cxx.obj 
"clang-cl" "-Iscipy\fft\_pocketfft\pypocketfft.cp310-win_amd64.pyd.p" "-Iscipy\fft\_pocketfft" "-I..\scipy\fft\_pocketfft" "-IC:/bld/scipy-split_1703585124709/_h_env/Library/include" "-I%PREFIX%\Include" "-DNDEBUG" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W2" "/EHsc" "/std:c++17" "/permissive-" "/O2" "-DMS_WIN64=" "/Fdscipy\fft\_pocketfft\pypocketfft.cp310-win_amd64.pyd.p\pypocketfft.cxx.pdb" /Foscipy/fft/_pocketfft/pypocketfft.cp310-win_amd64.pyd.p/pypocketfft.cxx.obj "/c" ../scipy/fft/_pocketfft/pypocketfft.cxx
In file included from ../scipy/fft/_pocketfft/pypocketfft.cxx:19:
../scipy/fft/_pocketfft/pocketfft_hdronly.h(155,15): error: no member named 'aligned_alloc' in the global namespace; did you mean simply 'aligned_alloc'?
  155 |   void *ptr = ::aligned_alloc(align,size);
      |               ^~~~~~~~~~~~~~~
      |               aligned_alloc
../scipy/fft/_pocketfft/pocketfft_hdronly.h(153,14): note: 'aligned_alloc' declared here
  153 | inline void *aligned_alloc(size_t align, size_t size)
      |              ^
1 error generated.
```

That's due to MSFT's [wonderful](https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170) `/Zc:__cplusplus` situation, without which the following does not take effect:
https://github.com/scipy/scipy/blob/60de9b912acef5ba794de177416d6fb7d29486e6/scipy/fft/_pocketfft/pocketfft_hdronly.h#L152-L153

**Comment by h-vetinari** [comment]
> That's due to MSFT's [wonderful](https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170) `/Zc:__cplusplus` situation [...]

... which should normally be [handled](https://github.com/mesonbuild/meson/blob/1.3.0/mesonbuild/compilers/cpp.py#L767-L768) by meson, but that doesn't take effect when using clang-cl (AFAICT)... 😑

**Comment by mborland** [comment]
> > perhaps the easiest fix is just to compile with C++17?
> 
> Can confirm that `cpp_std=c++17` gets past the `I` macro issues. However, it then runs into another problem:
> 
> ```
> [1013/1618] Compiling C++ object scipy/fft/_pocketfft/pypocketfft.cp310-win_amd64.pyd.p/pypocketfft.cxx.obj
> FAILED: scipy/fft/_pocketfft/pypocketfft.cp310-win_amd64.pyd.p/pypocketfft.cxx.obj 
> "clang-cl" "-Iscipy\fft\_pocketfft\pypocketfft.cp310-win_amd64.pyd.p" "-Iscipy\fft\_pocketfft" "-I..\scipy\fft\_pocketfft" "-IC:/bld/scipy-split_1703585124709/_h_env/Library/include" "-I%PREFIX%\Include" "-DNDEBUG" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W2" "/EHsc" "/std:c++17" "/permissive-" "/O2" "-DMS_WIN64=" "/Fdscipy\fft\_pocketfft\pypocketfft.cp310-win_amd64.pyd.p\pypocketfft.cxx.pdb" /Foscipy/fft/_pocketfft/pypocketfft.cp310-win_amd64.pyd.p/pypocketfft.cxx.obj "/c" ../scipy/fft/_pocketfft/pypocketfft.cxx
> In file included from ../scipy/fft/_pocketfft/pypocketfft.cxx:19:
> ../scipy/fft/_pocketfft/pocketfft_hdronly.h(155,15): error: no member named 'aligned_alloc' in the global namespace; did you mean simply 'aligned_alloc'?
>   155 |   void *ptr = ::aligned_alloc(align,size);
>       |               ^~~~~~~~~~~~~~~
>       |               aligned_alloc
> ../scipy/fft/_pocketfft/pocketfft_hdronly.h(153,14): note: 'aligned_alloc' declared here
>   153 | inline void *aligned_alloc(size_t align, size_t size)
>       |              ^
> 1 error generated.
> ```
> 
> That's due to MSFT's [wonderful](https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170) `/Zc:__cplusplus` situation, without which the following does not take effect:
> 
> https://github.com/scipy/scipy/blob/60de9b912acef5ba794de177416d6fb7d29486e6/scipy/fft/_pocketfft/pocketfft_hdronly.h#L152-L153


The standard workaround for MSVC `__cplusplus` situation is:

`#if __cplusplus >= 201703L || (defined(_MSVC_LANG) && _MSVC_LANG >= 201703L)`

**Comment by h-vetinari** [comment]
Yeah, I know, but we don't do this [consistently](https://github.com/search?q=repo%3Ascipy%2Fscipy+%2F__cplusplus%5Cs*%3E%2F&type=code), and meson generally takes care of this for us. It's only that it doesn't do so for clang-cl: https://github.com/mesonbuild/meson/issues/12670

**Comment by mborland** [comment]
> Yeah, I know, but we don't do this [consistently](https://github.com/search?q=repo%3Ascipy%2Fscipy+%2F__cplusplus%5Cs*%3E%2F&type=code), and meson generally takes care of this for us. It's only that it doesn't do so for clang-cl: [mesonbuild/meson#12670](https://github.com/mesonbuild/meson/issues/12670)

See: https://github.com/scipy/scipy/pull/19761

**Comment by h-vetinari** [comment]
> ```
>../scipy/fft/_pocketfft/pocketfft_hdronly.h(155,15): error: no member named 'aligned_alloc' in the global namespace; did you mean simply 'aligned_alloc'?
> ```
> That's due to MSFT's [wonderful](https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170) `/Zc:__cplusplus` situation, without which the following does not take effect:

This was misdiagnosed on my part, sorry for that. The error appears on line 155, which means we're already taking the `__cplusplus >= 201703L` branch:
https://github.com/scipy/scipy/blob/60de9b912acef5ba794de177416d6fb7d29486e6/scipy/fft/_pocketfft/pocketfft_hdronly.h#L152-L161

There are just too many ways in which MSVC is non-compliant, haha (even though I was aware of the aligned_alloc situation...) 😅 

@mborland provided a devcom [link](https://developercommunity.visualstudio.com/t/c17-stdaligned-alloc%E7%BC%BA%E5%A4%B1/468021) in #19761, but in any case, we need to avoid that branch on MSFT for the foreseeable future.

**Comment by h-vetinari** [comment]
Actually, even the dedicated feature test macro `_cpp_aligned_new` is useless, because MSVC [sets](https://godbolt.org/z/KdbjMYqx8) it _despite_ not implementing the standard facilities. I tried using their [replacements](https://learn.microsoft.com/en-us/cpp/build/reference/zc-alignednew?view=msvc-170) as described by the docs:
```diff
--- a/scipy/fft/_pocketfft/pocketfft_hdronly.h
+++ b/scipy/fft/_pocketfft/pocketfft_hdronly.h
@@ -152,12 +152,24 @@ template<> struct VLEN<double> { static constexpr size_t val=2; };
 #if __cplusplus >= 201703L
 inline void *aligned_alloc(size_t align, size_t size)
   {
+// MSVC does not provide the standard aligned allocation functions,
+// yet _still_ sets the feature test macro (__cpp_aligned_new)...
+// They do provide equivalent functionality under another name
+// https://learn.microsoft.com/en-us/cpp/build/reference/zc-alignednew?view=msvc-170
+# if defined(_MSC_VER)
+  void *ptr = _aligned_malloc(align,size);
+# else
   void *ptr = ::aligned_alloc(align,size);
+# endif
   if (!ptr) throw std::bad_alloc();
   return ptr;
   }
 inline void aligned_dealloc(void *ptr)
+# if defined(_MSC_VER)
+    { _aligned_free(ptr); }
+# else
     { free(ptr); }
+# endif
 #else // portable emulation
 inline void *aligned_alloc(size_t align, size_t size)
```
which passes compilation, but then crashes and burns at runtime. 😑

**Comment by h-vetinari** [comment]
So, unless I've made an obvious (or at least fixable) mistake, I think the only remaining option is to unconditionally turn off `aligned_alloc` support in `pocketfft` on windows.

**Comment by mborland** [comment]
> So, unless I've made an obvious (or at least fixable) mistake, I think the only remaining option is to unconditionally turn off `aligned_alloc` support in `pocketfft` on windows.

Your logic looks correct to me so I think removing support on windows is the best bet.

**Comment by h-vetinari** [comment]
So with `cpp_std=c++17` and the updated https://github.com/scipy/scipy/pull/19761 that now completely disables `aligned_alloc` on windows, things look much better (compiles, no crashes), only leaving two very minor tolerance violations:
```
=========================== short test summary info ===========================
FAILED stats/tests/test_distributions.py::TestGenExpon::test_sf_isf[0.125-0.9508674287164001-0.25-5-0.5] - AssertionError: 
Not equal to tolerance rtol=1e-14, atol=0

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 1.55431223e-15
Max relative difference: 1.24344979e-14
 x: array(0.125)
 y: array(0.125)
FAILED stats/tests/test_distributions.py::TestGenExpon::test_cdf_ppf[0.125-0.04913257128359998-0.25-5-0.5] - AssertionError: 
Not equal to tolerance rtol=1e-14, atol=0

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 1.55431223e-15
Max relative difference: 1.24344979e-14
 x: array(0.125)
 y: array(0.125)
= 2 failed, 59028 passed, 2542 skipped, 259 xfailed, 14 xpassed, 7 warnings in 1033.56s (0:17:13) =
```

**Comment by h-vetinari** [comment]
> only leaving two very minor tolerance violations:

Spoke too soon, without AVX512 we get two more; a variant of https://github.com/scipy/scipy/issues/15533, as well as:
```
FAILED optimize/tests/test__differential_evolution.py::TestDifferentialEvolutionSolver::test_L1 - AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0.0005

Mismatched elements: 1 / 13 (7.69%)
Max absolute difference: 0.0005003
Max relative difference: 0.00019409
 x: array([0.999956, 0.999957, 0.99996 , 0.999969, 0.999907, 0.999966,
       0.999856, 0.999926, 0.999909, 2.999611, 2.9995  , 2.999572,
       0.999806])
 y: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 1])
```
unfortunately, 2e-4 for the relative tolerance is pretty bad (if not unacceptable) IMO.

**Comment by andyfaff** [comment]
I think it's acceptable to bump the tolerance on the `differential_evolution` test. The L* tests are designed to test the constraint implementation. As such, it's about the internal machinery as much as the numerical output. It's not the stochastic minimisation that'll be the problem, it's the polishing employed at the end that's not as good as it should be. This polishing is done by SLSQP (because of the constraints). The test fail is saying that SLSQP behaviour isn't as good as it could be. It's only just outside the tolerance, so I'd bump `atol` to 6e-4.

**Comment by h-vetinari** [comment]
So with the following changes, SciPy 1.12.0rc1 builds fine and passes the tests in conda-forge:
* Use `-Dcpp_std=17`
* Backport https://github.com/scipy/scipy/pull/19761
* Keep skip for https://github.com/scipy/scipy/issues/15533
* Bump tolerances in two failing tests (details below)

<details>
<summary>Tolerances patch</summary>

```diff
commit 2ab23928c71697410d45f2c9e97e77b141943737
Author: @h-vetinari <h.vetinari@gmx.com>
Date:   Fri Dec 29 13:34:40 2023 +1100

    loosen tolerances for tests that fail otherwise on windows+MKL

diff --git a/scipy/optimize/tests/test__differential_evolution.py b/scipy/optimize/tests/test__differential_evolution.py
index 6ea6100b4..c3ad7dc2a 100644
--- a/scipy/optimize/tests/test__differential_evolution.py
+++ b/scipy/optimize/tests/test__differential_evolution.py
@@ -1013,9 +1013,9 @@ class TestDifferentialEvolutionSolver:
         x_opt = (1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 1)
         f_opt = -15

-        assert_allclose(f(x_opt), f_opt)
+        assert_allclose(f(x_opt), f_opt, atol=6e-4)
         assert res.success
-        assert_allclose(res.x, x_opt, atol=5e-4)
+        assert_allclose(res.x, x_opt, atol=6e-4)
         assert_allclose(res.fun, f_opt, atol=5e-3)
         assert_(np.all(A@res.x <= b))
         assert_(np.all(res.x >= np.array(bounds)[:, 0]))
@@ -1063,7 +1063,7 @@ class TestDifferentialEvolutionSolver:
                                          seed=1234, constraints=constraints,
                                          popsize=2)

-        assert_allclose(res.x, x_opt, atol=5e-4)
+        assert_allclose(res.x, x_opt, atol=6e-4)
         assert_allclose(res.fun, f_opt, atol=5e-3)
         assert_(np.all(A@res.x <= b))
         assert_(np.all(res.x >= np.array(bounds)[:, 0]))
diff --git a/scipy/stats/tests/test_distributions.py b/scipy/stats/tests/test_distributions.py
index 6268cef88..3aa62e75d 100644
--- a/scipy/stats/tests/test_distributions.py
+++ b/scipy/stats/tests/test_distributions.py
@@ -4130,9 +4130,9 @@ class TestGenExpon:
                               (0.125, 0.9508674287164001, 0.25, 5, 0.5)])
     def test_sf_isf(self, x, p, a, b, c):
         sf = stats.genexpon.sf(x, a, b, c)
-        assert_allclose(sf, p, rtol=1e-14)
+        assert_allclose(sf, p, rtol=2e-14)
         isf = stats.genexpon.isf(p, a, b, c)
-        assert_allclose(isf, x, rtol=1e-14)
+        assert_allclose(isf, x, rtol=2e-14)

     # The values of p in the following data were computed with mpmath.
     @pytest.mark.parametrize('x, p, a, b, c',
@@ -4143,9 +4143,9 @@ class TestGenExpon:
                               (0.125, 0.04913257128359998, 0.25, 5, 0.5)])
     def test_cdf_ppf(self, x, p, a, b, c):
         cdf = stats.genexpon.cdf(x, a, b, c)
-        assert_allclose(cdf, p, rtol=1e-14)
+        assert_allclose(cdf, p, rtol=2e-14)
         ppf = stats.genexpon.ppf(p, a, b, c)
-        assert_allclose(ppf, x, rtol=1e-14)
+        assert_allclose(ppf, x, rtol=2e-14)


 class TestTruncexpon:
```

</details>

**Comment by rgommers** [comment]
Nice @h-vetinari. Those tolerance bumps seem fine to make, do you want to open a PR for those?

For 1.12.x I'd keep `-Dcpp_std=c++17` in conda-forge, it's a bit late to make the chance in the release branch now. We should probably make it in `main` though. WDYT?

**Comment by h-vetinari** [comment]
> Those tolerance bumps seem fine to make, do you want to open a PR for those?

See #19800

> For 1.12.x I'd keep `-Dcpp_std=c++17` in conda-forge, it's a bit late to make the chance in the release branch now. We should probably make it in `main` though. WDYT?

Both points sound reasonable to me!

**Comment by lucascolley** [comment]
> For 1.12.x I'd keep -Dcpp_std=c++17 in conda-forge, it's a bit late to make the chance in the release branch now. We should probably make it in main though.

IIUC we can't fully move to `c++17` yet, so is this just for Windows?

**Comment by h-vetinari** [comment]
> IIUC we can't fully move to `c++17` yet

What blockers are there? When I last looked at this in depth (https://github.com/scipy/scipy/pull/16589), everything was ready for C++17.

**Comment by lucascolley** [comment]
> What blockers are there? When I last looked at this in depth (https://github.com/scipy/scipy/pull/16589), everything was ready for C++17.

You will know better than me. I went from https://docs.scipy.org/doc/scipy/dev/toolchain.html#c-language-standards:

> as of mid-2022, support for the entirety of the C++17 standard library has not yet been completed across all compilers

to its reference, https://en.cppreference.com/w/cpp/compiler_support/17#C.2B.2B17_library_features, which seems to have a few yellow and red boxes still.

But if everything has been covered for SciPy, sure, let's move to 17! I can submit a PR.

**Comment by h-vetinari** [comment]
> I went from https://docs.scipy.org/doc/scipy/dev/toolchain.html#c-language-standards:
> 
> > as of mid-2022, support for the entirety of the C++17 standard library has not yet been completed across all compilers
> 
> to its reference, https://en.cppreference.com/w/cpp/compiler_support/17#C.2B.2B17_library_features, which seems to have a few yellow and red boxes still.

The distinction between language and standard library is important. We can use C++17 as a language version (fully supported by every compiler we use), as long as we don't use the small handful of not-universally-implemented stdlib features.

**Comment by h-vetinari** [comment]
This issue has served its purpose (and actually became a bit too much of a catch-all for issues cropping up in conda-forge). Closing.
