### ISSUE TITLE
CI, MAINT: some easy cleanups for Python version

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#19740]
Just glancing at the CI config code flanking the diffs in a few recent PRs, you can see some places where switching to the stable release makes sense: `git grep -E -i -P "3\.\d[2]-dev"`

```
.github/workflows/linux_meson.yml:        python-version: ['3.10', '3.12-dev']
.github/workflows/linux_meson.yml:            python-version: '3.12-dev'
.github/workflows/linux_meson.yml:      if: matrix.python-version == '3.12-dev'
```

**Comment by andyfaff** [comment]
If this is changed could we have a comment saying something along the lines of "these are the runs which would use python dev versions"? So we know which ones to use for 3.13-dev

**Comment by tylerjereddy** [comment]
Good point, dealing with CPython pre-releases is clearly the purpose of that job, and it even excludes running on maintenance branches, so isn't super useful until the next `3.13-dev` cycle starts anyway.
