### ISSUE TITLE
DOC: Detail what "concatenate" means in the context of `spatial.transform.Rotation.concatenate`

### ISSUE THREAD

**Issue by MichaelBonnet** [scipy/scipy#19774]
### Issue with current documentation:

In [the documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.concatenate.html) for `scipy.transform.Rotation.concatenate`, the description `Concatenate a sequence of Rotation objects.` does not actually explain what "concatenate" or "concatenated" means in this context, making it unclear what the functionality does.

### Idea or request for content:

Define the term and its applications in the documentation. An inexperienced user may assume that concatenation == composition; is this true?

Even better (and in addition), include an example(s) in the main [Rotation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.html) page and or the `concatenate` page.

**Comment by j-bowhay** [comment]
@scottshambaugh maybe you would be interested in clarifying/making a pr?

**Comment by MichaelBonnet** [comment]
> @scottshambaugh maybe you would be interested in clarifying/making a pr?

the issue is, I *am* the inexperienced user. I don't know what `concatenate` is for.

**Comment by scottshambaugh** [comment]
Sure, @j-bowhay, I can whip something up here.
