### ISSUE TITLE
PyBind11 not found...

### ISSUE THREAD

**Issue by prusso630** [scipy/scipy#19789]
### Describe your issue.

After cloning with git the latest repository and running a pip install . I found that the terminal output is not finding pybind11 even thought I have tried installing pybind11 every way I know how to, starting with:

sudo apt install pybind11-dev
sudo apt install python3-pybind11
pip install pybind11
pip install pybind11[global]

Any way to get scipy's installation routine to find pybind11 on:

Distributor ID: Ubuntu
Description: Ubuntu 22.04.3 LTS
Release: 22.04
Codename: jammy

?

I tried to subscribe to the mailing list however I do not seem to be listed as a member there yet after subscribing to it. So far my emails get kicked back to my inbox as not from a member of the group.

### Reproducing Code Example

```python
na
```

### Error message

```shell
pybnd11 not found by pip install .
```

### SciPy/NumPy/Python version and system information

```shell
/usr/bin/env /home/prusso/Downloads/scipy/venv/bin/python /home/prusso/.vscode/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 51867 -- /home/prusso/Downloads/scipy/import\ sys,\ scipy,\ numpy\;\ print\(scipy.py 
Traceback (most recent call last):
  File "/home/prusso/Downloads/scipy/scipy/__init__.py", line 51, in <module>
    from scipy.__config__ import show as show_config
ModuleNotFoundError: No module named 'scipy.__config__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/prusso/Downloads/scipy/import sys, scipy, numpy; print(scipy.py", line 1, in <module>
    import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()
  File "/home/prusso/Downloads/scipy/scipy/__init__.py", line 56, in <module>
    raise ImportError(msg) from e
ImportError: Error importing SciPy: you cannot import SciPy while
    being in scipy source directory; please exit the SciPy source
    tree first and relaunch your Python interpreter.
```

**Comment by lucascolley** [comment]
Hi @prusso630, please could you provide us a minimal working example of commands which reproduce the error message, and the full traceback containing the `pybind11` error?

**Comment by prusso630** [comment]
I got a developer release,to install, unable to reproduce issue started with a fresh installation of Ubuntu. I had to install with pip cython, pythran and pythran-openblas. So far with those packs sudo pip installed I was able to follow the instructions. Also I noticed it seems one also has to sudo apt install python3-pkgconfig to find pybind11 while building SciPy. I hope to get access to mailing list soon I did subscribe.

**Comment by lucascolley** [comment]
> I hope to get access to mailing list soon I did subscribe.

If it is your first time sending a message, your post will be held until approved by a moderator.

**Comment by rgommers** [comment]
> Also I noticed it seems one also has to sudo apt install python3-pkgconfig to find pybind11 while building SciPy

Only for older versions of SciPy and Pybind11 I believe - in the latest version there's also a `pybind-config` script installed in `site-packages/bin` that gets used. `pkg-config` is needed for BLAS/LAPACK, and will then handle `pybind11` as well, but detection of the latter should always work if it's correctly installed.

> unable to reproduce issue started with a fresh installation of Ubuntu.

Thanks for confirming. I'm pretty sure there is no bug here, so I'll close this issue. If you have further problems though, please don't hesitate to comment again.
