### ISSUE TITLE
MAINT: patch when `gmpy2` supports Python 3.12

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#19782]
When `gmpy2` supports Python 3.12, the following lines should be removed, and `python tools/generate_requirements.py` should be ran to update the requirements.

https://github.com/scipy/scipy/blob/ae3ca70a72ef04547fbc28501009246cef5ee6c8/tools/generate_requirements.py#L32-L35

**Comment by rgommers** [comment]
Upstream issue: https://github.com/aleaxit/gmpy/issues/446

**Comment by lucascolley** [comment]
Looks like we can take action on this now: https://github.com/aleaxit/gmpy/releases/tag/gmpy2_2_2_0
