### ISSUE TITLE
MAINT: need stable Pythran release for SciPy 1.12.0 RC2

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#19795]
I'd like to revert the usage of the Pythran GitHub `master` branch before putting SciPy 1.12.0 RC2 out for testing, alongside a few more backport PRs we have merged. So, this is a bookmark/reminder on that. It basically just means that Pythran stable release will automatically pull in `setuptools`.

@serge-sans-paille do you need any help getting a Pythran release out soon-ish? So far, there haven't been any issues with RC1 pointing to your `master` branch.

The line I'll want to adjust after that is: https://github.com/scipy/scipy/blob/maintenance/1.12.x/pyproject.toml#L16

**Comment by h-vetinari** [comment]
There's a release-candidate already: https://github.com/serge-sans-paille/pythran/pull/2167

**Comment by lucascolley** [comment]
this is here!
