### ISSUE TITLE
CI: doc build broken by pip release vs. stale cache in circleci

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#19793]
In CircleCI, we run `pip install numpy cython pybind11 pythran ninja meson` etc., after loading a cached pip.

https://github.com/scipy/scipy/blob/08a5b6ff37b8ac39ce885df1fee737edda80d3fc/.circleci/config.yml#L69-L77

The cache itself is updated _after_ that:
https://github.com/scipy/scipy/blob/08a5b6ff37b8ac39ce885df1fee737edda80d3fc/.circleci/config.yml#L89-L93

This produces failures when the cache (and/or the underlying image?) is out of date:
```
Installing collected packages: ply, ninja, pybind11, numpy, meson, gast, cython, beniget, pythran
Successfully installed beniget-0.4.1 cython-3.0.7 gast-0.5.4 meson-1.3.1 ninja-1.11.1.1 numpy-1.26.2 ply-3.11 pybind11-2.11.1 pythran-0.14.0

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'doc_requirements.txt'

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip

Exited with code exit status 1
```
Seen in https://github.com/scipy/scipy/pull/19735.

**Comment by lucascolley** [comment]
8567df4213957e87f104d7116f780711c3d999ca changed the import path in that workflow. Just a case of needing to merge main I believe.

**Comment by lucascolley** [comment]
Closed this, but feel free to reopen if you think I've missed something @h-vetinari .
