### ISSUE TITLE
BUG: typo in specfun.f?

### ISSUE THREAD

**Issue by jacobwilliams** [scipy/scipy#19813]
### Describe your issue.

In `SUBROUTINE GAM0`, this looks suspicious:

```fortran
        GR=(25)
        DO 20 K=24,1,-1
20         GR=GR*X+G(K)
```

I wonder if that first line should be `GR=G(25)`.

### Reproducing Code Example

```python
na
```

### Error message

```shell
na
```

### SciPy/NumPy/Python version and system information

```shell
na
```

**Comment by ilayn** [comment]
Yes it is a typo but we are not using it. The correct one can be found as `GAMMA2` in the same file.

**Comment by ilayn** [comment]
Looks like we are using this in `scipy.special.lmbda` but apparently I unconsciously fixed it during my C rewrite. I'll send the PR which will fix this soon. Thanks for catching this @jacobwilliams
