### ISSUE TITLE
DOC: remove incorrect sentence about subpackage imports

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#19836]
### Issue with current documentation:

https://scipy.github.io/devdocs/tutorial/index.html#subpackages says that "SciPy subpackages need to be imported separately". This is no longer true! see https://scientific-python.org/specs/spec-0001/

### Idea or request for content:

Remove the incorrect guidance. The lines are https://github.com/scipy/scipy/blob/e7c6a0d1ce504c528ab00d19ddac6bdb1ae1cb36/doc/source/tutorial/index.rst?plain=1#L43-L46

### Additional context (e.g. screenshots, GIFs)

![image](https://github.com/scipy/scipy/assets/51488791/40e8f478-26dc-4287-af2c-5b58b82742c1)

**Comment by ShanDeng123** [comment]
Hey, I can take this one - Though, to be clear, is the full extent of the change to just remove the incorrect guidance, and update the statement

>SciPy is organized into subpackages covering different scientific computing domains. These are summarized in the following table:

To be something more like

>SciPy is organized into subpackages covering different scientific computing domains. SciPy subpackages can be utilized directly via [Lazy Loading](https://scientific-python.org/specs/spec-0001/), and are summarized in the following table:

**Comment by lucascolley** [comment]
thanks @ShanDeng123 ! TBH I don't think we even need to mention Lazy Loading here - it isn't relevant as one of the first things that users will see in the tutorial. The following sounds good to me:

> SciPy is organized into subpackages covering different scientific computing domains, which are summarized in the following table:

**Comment by ShanDeng123** [comment]
Aye aye - Sounds good!

**Comment by aadityab7** [comment]
Hello, sorry I am new here, but is there already a pull request open for this issue?

**Comment by lucascolley** [comment]
> Hello, sorry I am new here, but is there already a pull request open for this issue?

No, feel free to open one!

**Comment by tactipus** [comment]
if anyone needs help, let me know! I'll be watching

**Comment by kru2710shna** [comment]
I understand the issue.

This is my first time doing it. That's how I did- 
Fork the repo. 
clone the repo
and do I need to follow this https://scipy.github.io/devdocs/dev/dev_quickstart.html ??

**Comment by j-bowhay** [comment]
@kru2710shna it looks like there is already an open pr to fix this so it would be best to look at a different issue to avoid duplicating work. Regardless, thank you for your interest in contributing to SciPy.

**Comment by kru2710shna** [comment]
Thanks
