### ISSUE TITLE
ENH: Linear extrapolation for splines in RegularGridInterpolator

### ISSUE THREAD

**Issue by kcharlie2** [scipy/scipy#19840]
### Is your feature request related to a problem? Please describe.

There is not a lot of control over extrapolation for `RegularGridInterpolator`, especially for higher order spline methods. 

For example, extrapolation of cubic or quintic outside the grid boundary often produces undesirable behavior due to the nonzero higher order derivatives. The only other option available to users is to use a fill value.

### Describe the solution you'd like.

It would be great if `RegularGridInterpolator` could do linear extrapolation by holding the first derivative at the grid boundaries. Inside the regular grid boundaries the evaluation would be the same, but outside the boundaries the fit would be linear. This would result in the higher derivatives having discontinuity at the boundaries.

### Describe alternatives you've considered.

I've enabled this in the past by modifying `RegularGridInterpolator` to use the 1d spline derivative information when evaluating points outside the boundary. 

However, this was only possible for the recursive 1d spline architecture in the current version of scipy (1.11).

With upcoming changes in #19633, perhaps it is possible to do this more generally in the n-dimensional splines?

**Comment by ev-br** [comment]
Sounds quite reasonable to explore! 

Can you give some details of what you had in the past, as you say, what is the use case, and what you suggest for the user API? 

I'd expect that for splines, extrapolation is tied to the boundary conditions. 

Also, it'd be great to understand / compare the proposal to wrappers of the sort discussed in 
https://docs.scipy.org/doc/scipy/tutorial/interpolate/extrapolation_examples.html

**Comment by kcharlie2** [comment]
Thanks - I hadn't previously seen that link you posted - that is an excellent resource! It nicely lays out the intended extension of interpolation objects for the end user.

I've implemented something similar for our own usage and thought that general capability might be useful to others, but the link you posted nicely lays out the issues and offers several good similar examples.

Therefore I don't think this proposed feature offers anything new nor could be implemented easily enough to be worth the additional effort.

**Comment by ev-br** [comment]
Examples in that link are from issues opened by users over the years. Additions and other improvements are most welcome.
