### ISSUE TITLE
BUG: error in calculation of p-values in sp.stats.wilcoxon when there are ties in ranked differences

### ISSUE THREAD

**Issue by schekroud** [scipy/scipy#19872]
### Describe your issue.

P-values for one-sided wilcoxon signed-rank tests are inconsistent depending on the ordering of the input for the same test in cases where there are ties in the ranked differences.

Specifically, testing for A>B and B<A should, in theory, give the same p-value for the one-sided tests, but do not give the same p-value in instances where there are ties in the ranked differences and the average rank is assigned (a decimal value).

This problem arises when calculating the 'exact' p-value as the null distribution for a given N is coded as an array requiring integer slicing to get the appropriate p-value. This results in A>B and B<A not actually being the same, despite being the same.

### Reproducing Code Example

```python
var1 = [62, 66, 61, 68, 74, 62, 68, 62, 55, 59]
var2 = [71, 71, 69, 61, 75, 71, 77, 72, 62, 65]
print(stats.wilcoxon(var1, var2, alternative = 'less'))
print(stats.wilcoxon(var2, var1, alternative = 'greater'))
```

### Error message

```shell
n/a
```

### SciPy/NumPy/Python version and system information

```shell
1.11.1 1.24.3 sys.version_info(major=3, minor=11, micro=5, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /Users/sammichekroud/anaconda3/include
    lib directory: /Users/sammichekroud/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /Users/sammichekroud/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /Users/sammichekroud/anaconda3/include
    lib directory: /Users/sammichekroud/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /Users/sammichekroud/anaconda3/lib/pkgconfig
    version: 0.3.21
  pybind11:
    detection method: pkgconfig
    include directory: /Users/sammichekroud/anaconda3/include
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: arm64-apple-darwin20.0.0-clang
    linker: ld64
    name: clang
    version: 12.0.0
  c++:
    commands: arm64-apple-darwin20.0.0-clang++
    linker: ld64
    name: clang
    version: 12.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: /var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_66h0hq6x34/croot/scipy_1691606685645/_build_env/bin/arm64-apple-darwin20.0.0-gfortran
    linker: ld64
    name: gcc
    version: 11.2.0
  pythran:
    include directory: ../../../../../../../../../../../Users/sammichekroud/anaconda3/lib/python3.11/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /Users/sammichekroud/anaconda3/bin/python
  version: '3.11'
```

**Comment by mdhaber** [comment]
> This problem arises when calculating the 'exact' p-value as the null distribution for a given N is coded as an array requiring integer slicing to get the appropriate p-value.

Specifically:
https://github.com/scipy/scipy/blob/5e4a5e3785f79dd4e8930eed883da89958860db2/scipy/stats/_morestats.py#L4166
and

https://github.com/scipy/scipy/blob/5e4a5e3785f79dd4e8930eed883da89958860db2/scipy/stats/_morestats.py#L4175-L4176

`r_plus` should not be rounded down before this calculation if it is legitimately greater than `int(r_plus)`. Well, it's tough to say what *should* happen, since the null distribution `pmf` is calculated under the assumption that there are no ties. So the other way to look at this is that this alternative is calculated correctly, _conservatively_ including the probability mass at `int(r_plus)` since the assumption is violated, and the other alternative should include the extra probability mass in its calculation. But in any case, adjusting the rounding procedure for one of the alternatives is the way to fix this.

There is a rewrite of `wilcoxon` in gh-19770 which can incorporate this.

**Comment by schekroud** [comment]
yep, i also noticed that this is an issue of rounding by coercing to integer, but it makes two tests that *are* equivalent, non-equivalent - happening (at least in my case) because both R+ and R- are being rounded down. For true equivalences of the tests, `int(rplus) + int(rminus) = max_rank` should be forced to be true.

An alternative solution would be to allow individual control of the ranking method used - at the moment, `r = _stats_py.rankdata(abs(d))` doesn't allow any control over how ties are handled (it just uses the `'average'` default in `rankdata`. Being able to specify the method with which ties are handled would get over this too as the issue arises when the test statistic is not an integer
