### ISSUE TITLE
BUG: scipy.stats.skellam.cdf() crashes with large argument

### ISSUE THREAD

**Issue by fancidev** [scipy/scipy#19883]
### Describe your issue.

The following simple program crashes the Python executable.

### Reproducing Code Example

```python
import scipy.stats
scipy.stats.skellam.cdf(0, 0.1, 1e10)
```

### Error message

```shell
Python interpreter crashes without any error message.
```

### SciPy/NumPy/Python version and system information

```shell
Python 3.10.10
Scipy 1.10.1
```

**Comment by lucascolley** [comment]
The interpreter returns `1.0` for me on the current development branch. Can you try with SciPy 1.11.4?

**Comment by fancidev** [comment]
Thanks for checking. Indeed the function works fine with Scipy 1.11.4.
