### ISSUE TITLE
ENH: scipy.stats.gamma.fit: return globally optimal result for arbitrary input

### ISSUE THREAD

**Issue by fancidev** [scipy/scipy#19884]
### Describe your issue.

The below code snippet estimates a gamma distribution using method of moments. The estimated parameters are huge, indicating numerical problem.

Possible fix is to code a closed form MM estimator for gamma when location is fixed, which is straightforward.

### Reproducing Code Example

```python
import scipy.stats
scipy.stats.gamma.fit([1,2,3], floc=0, method="MM")
```

### Error message

```shell
Output:
(450542485.3474188, 0, 4.712838223917787e-09)
```

### SciPy/NumPy/Python version and system information

```shell
SciPy 1.10.1
Python 3.10.10
```

**Comment by lucascolley** [comment]
I can reproduce the given output on `main` currently.

**Comment by mdhaber** [comment]
@lucascolley can you compare the moments of the sample and the fitted distribution? Are there distribution parameters which make them match better?

**Comment by fancidev** [comment]
Thanks for looking into this. I understand fit(MM) uses a numerical procedure in general, but I believe for a library as fundamental as scipy, it is worthwhile to spend a bit more effort in picking good parameters for the optimizer (such as tolerance, scaling, initial guess, etc.)

For the particular case of fitting the gamma distribution with floc=0 (or otherwise given), the MM estimator has a simple closed form:

Let shape parameter be alpha and scale parameter be mu. Then population mean is alpha*mu, and population variance is alpha*mu*mu. By matching sample mean and (biased) sample variance, alpha and mu can be solved immediately.

**Comment by fancidev** [comment]
Let me prepare a pull request after I get the build environment set up.

For ease of reference let me put the formulas for moment estimator of Gamma distribution here. Let $\alpha$, $m$, $\mu$ denote respectively the shape, location, and scale parameter. The population moments are $\mathbb{E}[X]=m+\alpha\mu$, $\mathbb{E}[(X-\mathbb{E}X)^2]=\alpha\mu^2$, $\mathbb{E}[(X-\mathbb{E}X)^3]=2\alpha\mu^3$.

Let the sample moments be $M_1:=\frac1n \sum x_i$, $M_2:=\frac1n \sum (x_i-M_1)^2$, $M_3:=\frac1n \sum (x_i-M_1)^3$. It can be shown that matching the first $r$ non-central moments gives the same result as matching the first $r$ central moments (except that $\mathbb{E}[X]$ is always matched against $M_1$).

**Comment by josef-pkt** [comment]
> It can be shown that matching the first non-central moments gives the same result as matching the first central moments

Those statements work theoretically, but in many case we run into estimation or convergence problems (or numerical precision problems) if the parameterization or objective function has high collinearity in the parameters. 
My guess was that's the problem with using the generic estimation procedure in the current case.

**Comment by fancidev** [comment]
I agree that matching to centered sample moments would be better for a numerical procedure when the sample mean is large, in which case the non-centered moments are mainly driven by the mean.

For the particular case of gamma.fit, I finally launched a debugger and step into the code to see why it fails to fit [1,2,3]. The cause becomes clear: gamma._fitstart made a poor initial guess: it sets the shape parameter to the sample skew, which is zero for this test data. This leads to a huge guess of the shape parameter, and creates trouble for the optimizer.

_fitstart is not used by the MLE code path.
