### ISSUE TITLE
ENH: support custom statistic in scipy.stats.goodness_of_fit

### ISSUE THREAD

**Issue by fancidev** [scipy/scipy#19894]
### Is your feature request related to a problem? Please describe.

I’d like to test whether a non-central chi-square distribution with zero degrees of freedom fits some given data well. This distribution has a probability mass at zero, but is otherwise continuous. The data contains many zeros.

I’d like to call `scipy.stats.goodness_of_fit(ks)` to run the KS test. (I have already wrote the code to implement the distribution to an extent that is good enough for my task.) The KS test is usually applied to continuous distribution, and scipy.stats.ks_test computes the statistic based on the assumption that the distribution is continuous. This leads to the wrong statistic value for mixed (and discrete) distribution, and hence wrong goodness_of_test result. 

### Describe the solution you'd like.

`scipy.stats.goodness_of_fit` function currently only takes string argument for `statistic`, and maps to one of the routines it supports to compute the statistic. I propose to let the function support a callable for the `statistic` argument, with signature f(dist, data). This would allow custom statistics to be supplied and the rest just works nicely.

### Describe alternatives you've considered.

Alternative is for the user to code a bootstrapped goodness of fit test themselves, which is what I did. But since it’s such a simple enhancement that enables much potential usage, I think it’s worth having it in scipy.

**Comment by mdhaber** [comment]
Sure, this is something I considered, but I thought I'd wait for it to be requested. Now it's requested. Great!

For the particular case you mention, what about the KS *statistic* needs to be modified in case of ties? Does the implementation not work properly when there are ties, or is there something about the definition that should be changed for the case of ties? (I know papers exist, but I'd be interested to know which one you're working with.)

**Comment by fancidev** [comment]
The KS statistic is correctly calculated (even if there are ties in the sample) if the distribution being tested against is continuous. The calculation is wrong if the distribution is non-continuous.

The reason is the following. The KS statistic has two parts: D+ and D-. D+ is computed as the difference between EDF and CDF at sample points; this part is fine regardless of the continuity of the CDF. D- _should_ be computed as the difference between the left limit of the EDF and the left limit of the CDF at sample points. The left limit of EDF is the EDF at the previous point (or zero for the first point); this is implemented correctly. The left limit of the CDF is implemented as the CDF value itself — this is only correct for a continuous distribution, and gives wrong result when the CDF jumps at the sample point.

**Comment by fancidev** [comment]
That’s correct.

I also considered a fix for the KS statistic calculation, but find it not straightforward. The current implementation (statistic and p-value) is correct for continuous distribution. For discrete distribution, the statistic calculation can be fixed in a straightforward way, but the (non-bootstrapped) p-value is highly difficult (see #14434); we might just as well return nan. But scipy currently doesn’t support mixed discrete-continuous distribution altogether (see #11291), so the potential fix will not help my particular problem at hand.

**Comment by fancidev** [comment]
Btw, the implementation of AD and CvM test statistic in scipy also only works with continuous distribution.

The formulas for discrete KS, AD and CvM statistics can be derived from their definition; or see e.g. page 362 of Famoye (1998): Bootstrap Based Tests for Generalized Negative Binomial
Distribution. Both are straightforward except that some extra care needs to be taken for discrete AD statistic at the right support of the CDF if it’s finite.

**Comment by fancidev** [comment]
Let me make a pull request this week.

Will take the chance to also add a `method` argument to the `goodness_of_fit` function to allow it to estimate the parameters by non-MLE. The purpose is that for some complex distributions, MLE is slow and `goodness_of_fit` takes a long time to produce a result. Having the possibility to estimate it by MM (which often has simple closed form formulas) can produce a result quicker.

**Comment by mdhaber** [comment]
> Will take the chance to also add

I'm willing to review the custom statistic, but let's start with that. We can talk about the method argument after that.

**Comment by fancidev** [comment]
Seems less straightforward to support custom statistic function than I initially thought, because the `goodness_of_fit` code expects the statistic function to be vectorized, and I’m still struggling to figure out how exactly the function has to be vectorized to be usable…

**Comment by mdhaber** [comment]
Any reducing statistic can pretty easily be wrapped to be vectorized (e.g. [here](https://github.com/scipy/scipy/blob/4edfcaa3ce8a387450b6efce968572def71be089/scipy/stats/_resampling.py#L20)). It won't be as fast as manually vectorizing the statistic, but it will satisfy the interface.

**Comment by fancidev** [comment]
The statistic function takes a frozen dist object and an array as arguments. The frozen dist may freeze array arguments, and acts like `functools.partial`. 

It’s not straightforward to introspect the frozen parameters and “devectorize” them for a  non-vectorized custom statistic function (e.g. `scipy.stats.ks_1samp`) to use; so I’ll proceed by requiring the custom statistic function to take an axis argument and support vectorization.

If it turns out important to support non-vectorized custom statistic later, the support may be added by adding a branch for that.
