### ISSUE TITLE
BUG: `special.nctdtr` broken in main

### ISSUE THREAD

**Issue by bashtage** [scipy/scipy#19896]
### Describe your issue.

`special.nctdtr` does not relturn correct values in main.  Likely cause is incorrect wrapping in #19560.

Additional small bug introduced is that the cythonized code is also returning the incorrect types, e.g., what should be a python `float` (scalar) is being returned as `np.float64` (numpy float64 scalar).

### Reproducing Code Example

```python
froms scipy import special
special.nctdtr(58, -3.8, 1.67)


return `nan`, when is should return something on the order of `0.9999999675827712`
```

### Error message

```shell
No error, just a wrong result bug.
```

### SciPy/NumPy/Python version and system information

```shell
1.13.0.dev0+1181.2353b15 2.0.0.dev0+git20240113.d2f60ff sys.version_info(major=3, minor=12, micro=0, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.1
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../opt/python/cp312-cp312/lib/python3.12/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp312-cp312/bin/python
  version: '3.12'
```
```

**Comment by bashtage** [comment]
Found in statsmodels pre-release testing.

**Comment by ilayn** [comment]
You are the first customer of the Fortran rewrites :) I'll check it.

**Comment by bashtage** [comment]
This looks strange to me:

https://github.com/scipy/scipy/blob/2353b154451fa77ee5f009b696ae82070ed8eab6/scipy/special/_cdflib.pyx#L3563C5-L3563C18

**Comment by ilayn** [comment]
Let me try on main

**Comment by steppi** [comment]
@ilayn 

problem is here

https://github.com/scipy/scipy/blob/736216d5ea2645cb76f4468d02addc2d18acd5c0/scipy/special/_cdflib.pyx#L3571-L3572

it should be

```cython
    if not (-1.e6 <= pnonc <= 1.e6):
        return (0., 0., -3, 1.e6 if pnonc > -1e6 else -1.e6)
```

you should probably check other bound conditions.

**Comment by ilayn** [comment]
It's this line, apparently I tried to be smart but the first one should be negative one million and not one millionth 😞 

https://github.com/scipy/scipy/blob/736216d5ea2645cb76f4468d02addc2d18acd5c0/scipy/special/_cdflib.pyx#L3571

**Comment by steppi** [comment]
> Additional small bug introduced is that the cythonized code is also returning the incorrect types, e.g., what should be a python `float` (scalar) is being returned as `np.float64` (numpy float64 scalar).

This function returns `np.float64` in the latest release for me. Did you really observe this returning a python `float`? Returning `np.float64` shouldn't have anything to do with `cython`. The output type is set in [PyUfunc_FromFuncAndData](https://numpy.org/doc/stable/reference/c-api/ufunc.html#c.PyUFunc_FromFuncAndData) and shouldn't have changed.

**Comment by bashtage** [comment]
` special.nctdtrinc` is also broken and silently returns wrong values.

```
from scipy import special

df, t_stat = (98, 1.5)
alpha = 1/20
alpha_half = alpha / 2
nc_median = special.nctdtrinc(df, 0.5, t_stat)
ci = special.nctdtrinc(df, [1 - alpha_half, alpha_half], t_stat)
print(nc_median)
print(ci)
```

On 1.11.4
```
1.4961639036840118
[-0.47493335  3.46737272]
```

On nightly (1.13.0.dev0+1181.2353b15)

```
1.793278926568212
[9.24724715e+01 9.80628003e-03]
```

**Comment by bashtage** [comment]
It feels like there should be a lot more tests of this.  Given this is a translation, it seems to me that generating some values using random inputs (and some deliberate, i.e., boundaries), computing results from 1.11 (or 1.12), and then making these tests would be a good way to pick up on these bugs.

Do you have coverage of the Cython code from the test suite?  That would be a good place to start when looking if tests are missing.

**Comment by ilayn** [comment]
We have quite a lot of tests but the value ranges are too wide for all possibilities. In fact, the test suite was quite comprehensive in my opinion and it was a challange to make all tests pass but apparently they are still missing corners.

**Comment by ilayn** [comment]
In fact I was expecting a much larger fallout from all stats related package nightlies worldwide but did not happen. This does not mean there are no bugs, obviously not. But I am actually prepared to fix all as they come since a comprehensive test of this much code is almost the same effort of translation there are plenty already notwithstanding.

**Comment by ilayn** [comment]
Ah dangit these are the ones that we still don't have tests that the comments mentions . 

https://github.com/scipy/scipy/blob/736216d5ea2645cb76f4468d02addc2d18acd5c0/scipy/special/tests/test_cdflib.py#L2-L19

I'll try to add some.

**Comment by steppi** [comment]
@ilayn, everywhere that has `twoi *= xi` below, should actually have `twoi = 2.*xi`. A consequence of the Fortran code using `two` for `2.0d0` in `twoi = two*xi`.

https://github.com/scipy/scipy/blob/2a4d6e978baa015935e009cd00537d2ddeee2531/scipy/special/_cdflib.pyx#L4614-L4638

**Comment by steppi** [comment]
All of the `cdftnc_whichX` for `x > 1` have `cumf` in place of `cumtnc`

https://github.com/scipy/scipy/blob/2a4d6e978baa015935e009cd00537d2ddeee2531/scipy/special/_cdflib.pyx#L3612

**Comment by bashtage** [comment]
If there isn't a coverage run in CI, I would strongly urge a coverage run locally. With translations like this, one might expect up to 20 bugs to have been introduce based on the size of the file.  The most direct way to attempt to detect these would be to get 10 100% coverage on the Cython code.

**Comment by ilayn** [comment]
I'll finish those tests, it's actually not as bad. But yeah I was hoping to get some time in between. Didn't add the numpy 2.0 thing in the prediction

**Comment by ilayn** [comment]
> The most direct way to attempt to detect these would be to get 10 100% coverage on the Cython code.

That's hardly possible to achieve. These functions call each other and you have to find the right argument to traverse everything to hit the right branch. A bit of educated brute force would clean up the obvious ones.

**Comment by bashtage** [comment]
> That's hardly possible to achieve. These functions call each other and you have to find the right argument to traverse everything to hit the right branch. A bit of educated brute force would clean up the obvious ones.

It isn't that hard. I have written two projects with a total of around 80k LOC that have 99.5%+ coverage. 

I suspect that the existing test probably hit most of the paths, and so only need coverage for the rest.  One big advantage to using Cython over fortran is improved access to coverage, and a better path to improving coverage.  Unfortunately, it looks like SciPy doesn't do coverage in CI anymore.

**Comment by ilayn** [comment]
What I mean is that, func `a` calls `b`, `c` and then `b` calls `x` and `y`. To actually hit a branch in `x` you have to find a really "special" argument from `a` because that's what we kind of know about. 

The remaining parts are no different than a foreign language to me as I'm not really a special function person. I left the unit test effort to someone interested because translation of Fortran code is already a very annoying work for multitude of reasons. And with this work, our hope is exactly fleshing out things buried under decades of dust while adding minimal number of new bugs like you find . 

Emphasis on the "minimal" 😃

**Comment by bashtage** [comment]
I have also done my share of porting fortran to Cython. I found it very easy to introduce subtle bugs, much like the one that statsmodels found.  IMO, translation should not normally be pursued unless there is a corresponding effort to ensure that the translated lines are covered at a very high rate. 

It is a bad sign of code quality that these bugs were discovered in downstream testing. These are not corner case values, and good test coverage would have caught these before they were merged.

**Comment by ev-br** [comment]
FWIW, I'd +1 to what Ilhan did.
Improving coverage is indeed nice and is certainly on the roadmap (and help would be most appreciated), but IMO it's not a blocker for the port itself.

We either don't touch these Fortran bits and keep carrying them indefinitely, or we iterate and do rely on downstream testing to some degree. As long as scipy (read: Ilhan&Albert, mainly) is responsive and fixes regressions quickly, it is not unreasonable IMO. 

It is actually great that downstream tests main/rc! A pragmatic question is how to make downstream testing easier:
1. Keep things in PRs for longer?
2. Merge PRs quickly to give more time for the downstream testing of the main branch?
3. Make rc phase longer (assuming release candidates get more testing than main?)
4. Nothing works, things will only get found when released, so plan to help the RM with the bugfix releases?
5. As in 2, but revert just before a release for a year or so?

My gut feeling is that 1 is strictly the worst option; and the best option is 2 with 5 if needs be (did 5 work all that well for numpy?).

**Comment by ilayn** [comment]
I think we already established that the test suite was broken and I forgot that comment and we did not know about NumPy 2.0 schedule hence this popped earlier. 

It's not our intention to roll out untested code to world only to get a rainstorm of bug reports if that's what you mean. In fact, this translation when finished had 378 test failures. And it took me a good number of days to bring it down to 0. 

So it is really not that of a grim picture. However, like I said, we should have poked each other about that untested part. Which is as you can see happening only in the `cdftnc` entrance and did not go down because other parts already using the code.

I can assure you no amount of coverage can get you to bit equivalence with the Fortran code because they are fundamentally different and you don't know which variable is initialized which is the fortran bug that was lying there for decades and so on.

Here is a code piece that is considered to be battle tested; https://github.com/scipy/scipy/issues/19813

**Comment by j-bowhay** [comment]
Perhaps the use of hypothesis would be useful in validating the output of these translations (although this is not something I have used myself before)?

**Comment by bashtage** [comment]
> * Keep things in PRs for longer?
> * Merge PRs quickly to give more time for the downstream testing of the main branch?
> * Make rc phase longer (assuming release candidates get more testing than main?)
> * Nothing works, things will only get found when released, so plan to help the RM with the bugfix releases?
> * As in 2, but revert just before a release for a year or so?

Ideally, there would be a smooth path to a change like this. Something like

1. Define a special variables `scipy.options.special.backend = "cython" | "fortran"`
2. Default for `"fortran"` at first release after the Cython translation is merged
3. Continue to run all functions using the fortran backend, and start a deprecation cycle that the fortran code will stop working, and you should open into the cython backend when you are ready
4. After a release or two more upgrade to FutureWarning, and switch the backend to cython by default.
5. After another release or two remove the fortran backend, and make setting the backend FutureWarning
6. After a bit more remove `scipy.options.special.backend`

Yes, this is complicated, but it would get the code out there is a way that wouldn't quickly break packages that aren't actively doing pre-prelease testing. It also encourages downstream packages to start testing without requiring them to install pre-release packages. 

pandas often uses a process like this. One recent and important example is the migration to Copy-on-write, which will be the default in the next major.  It has been available for at least 2 minor releases as opt-in.

IME there has been a relatively high frequency of bugs like this in the past few years from SciPY, at least from the POV of statsmodels. Merged PRs where bugs are only caught because of downstream tests and pre-relrease testing. Quite a few came with the move to Boost which has different edge case treatment. 

This seems like a lot when compared to NumPy.  IIRC the number of bugs in merged code we have found in pre-release testing is either 1 or 0 (but I think 1).

**Comment by bashtage** [comment]
> Improving coverage is indeed nice and is certainly on the roadmap (and help would be most appreciated), but IMO it's not a blocker for the port itself.

I think not expecting high coverage of translated code is a mistake.  It is particularly easy to get coverage when you have two versions of the same code and are translating. It is also very frustrating to have a slew of bugs introduced because of translation errors, which are effectively unavoidable. 

Also, it seems like coverage is no longer part of CI.  Is coverage of the cython code available somewhere like CodeCov? It looks like codecov stopped working 11 months ago.

https://app.codecov.io/gh/scipy/scipy/commits

**Comment by ilayn** [comment]
Ideally, somebody already would have worked on these code in the last 40 years but did not happen. I don't know what to say other than apologies for the trouble. We will try harder not to break things for you. Any help is appreciated to make the transition smoother.

**Comment by josef-pkt** [comment]
Part of the unit testing problem is that scipy.stats has been moving to boost and does not test the related scipy.special functions anymore.
I had switched statsmodels from using distribution in scipy.stats to scipy.special after the boost version for non-central distributions like nct cause problems for statsmodels. That might be one reason that the bug showed up in statsmodels and not in scipy.stats, although statsmodels power functions use many special distribution function that scipy.stats does not need.

**Comment by josef-pkt** [comment]
**update**
AFAICS, statsmodels uses only nct and ncf from scipy.special, essentially all other distributions functions are accessed through scipy.stats.
So, except for those two, whether the statsmodels unit test catch boost or scipy.special depends on scipy.stats.

**Comment by steppi** [comment]
We plan to add comprehensive unit tests for scipy.special this year, and hopefully sooner than later. One of the reasons behind the rewrites out of Fortran is to make it feasible for us to fix bugs and make improvements to these special functions, and we're going to need thorough testing to understand what needs to be improved.

Sorry for merging the cdflib translation before having all functions tested with only weeks before the coming out of band release. We'll try to be more careful from now. Down the road, the outcome will hopefully be a much improved and more thoroughly tested scipy.special.

**Comment by dschmitz89** [comment]
@bashtage @josef-pkt : could you test out if the `stats` version of the noncentral distributions still cause issues? If yes, we can open an issue upstream at Boost. So far, they have been very responsive (see the latest example #20785 ). The discrepancy between `stats` and a`special` truely is a pity.
