### ISSUE TITLE
DEP: remove deprecated imports from privatized modules

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#19905]
This is a follow-up to #18279 resp. https://github.com/scipy/scipy/commit/0581177bfd763a2ef74dd952b302ea4dfffb736c where we've generally promised removal of _incidental_ imports from modules we've made private. The modules themselves are set to be removed with SciPy 2.0.

I'm attempting this in #19904, but wanted to open an issue for discussing any eventual issues.

**Comment by h-vetinari** [comment]
@j-bowhay, I was wondering about `approx_jacobian`, which wasn't touched in #18968, but _did_ appear in the `__all__` of the private module implementation:
https://github.com/scipy/scipy/blob/730010e77319606718b3d50a8fc402ba9cc629bc/scipy/optimize/_slsqp_py.py#L16

However, it is raising a warning currently, and I'm wondering if this is entirely intentional?
```
>>> from scipy.optimize.slsqp import approx_jacobian
<stdin>:1: DeprecationWarning: `scipy.optimize.slsqp.approx_jacobian` is deprecated along with the `scipy.optimize.slsqp` namespace. `scipy.optimize.slsqp.approx_jacobian` will be removed in SciPy 1.13.0, and the `scipy.optimize.slsqp` namespace will be removed in SciPy 2.0.0.
```

If I were to follow through on that warning (see #19904), then `approx_jacobian` would be deleted completely; there are no other [occurrences](https://github.com/search?q=repo%3Ascipy%2Fscipy%20approx_jacobian&type=code).

I ask because outright removal is obviously a different ballpark than privatizing a given module.

**Comment by h-vetinari** [comment]
Another object that would cease to be "officially" importable is `scipy.io.mmio.MMFile`, while the methods for that (`scipy.io.mmio.{mminfo,mmread,mmwrite}`) have "only" moved to the top-level `io` module.
```
<stdin>:1: DeprecationWarning: Please import `mminfo` from the `scipy.io` namespace; the `scipy.io.mmio` namespace is deprecated and will be removed in SciPy 2.0.0.
<stdin>:1: DeprecationWarning: Please import `mmread` from the `scipy.io` namespace; the `scipy.io.mmio` namespace is deprecated and will be removed in SciPy 2.0.0.
<stdin>:1: DeprecationWarning: Please import `mmwrite` from the `scipy.io` namespace; the `scipy.io.mmio` namespace is deprecated and will be removed in SciPy 2.0.0.
<stdin>:1: DeprecationWarning: `scipy.io.mmio.MMFile` is deprecated along with the `scipy.io.mmio` namespace. `scipy.io.mmio.MMFile` will be removed in SciPy 1.13.0, and the `scipy.io.mmio` namespace will be removed in SciPy 2.0.0.
```

**Comment by j-bowhay** [comment]
completed in https://github.com/scipy/scipy/pull/19904
