### ISSUE TITLE
BUG: boolean masking broken for sparse array classes

### ISSUE THREAD

**Issue by ivirshup** [scipy/scipy#19951]
### Describe your issue.

When a boolean mask is too short for the array it is indexing, this should throw an error. For example:
E.g.:

```python
import numpy as np

x = np.arange(25).reshape((5, 5))

x[[True, False]]
```

```pytb
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[6], line 1
----> 1 np.arange(25).reshape((5, 5))[[True, False]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 2
```

This doesn't happen with the sparse array classes (see example below). Instead, the indexer is treated as though it were padded to the correct size with `False`.

The array-api [explicitly states that this should throw an `IndexError`](https://data-apis.org/array-api/latest/API_specification/indexing.html#boolean-array-indexing).

### Reproducing Code Example

```python
from scipy import sparse
import numpy as np

x = np.arange(25).reshape((5, 5))

sparse.csr_array(x)[[True, False]]
```

### Error message

```shell
# Doesn't error, which is the problem
```

### SciPy/NumPy/Python version and system information

```shell
1.12.0 1.26.3 sys.version_info(major=3, minor=11, micro=7, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.1
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-wkrrblds/overlay/lib/python3.11/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp311-cp311/bin/python
  version: '3.11'
```

**Comment by perimosocordiae** [comment]
Do you think this is the root cause of gh-19919?
@ilan-gold FYI

**Comment by perimosocordiae** [comment]
Here's the problem: https://github.com/scipy/scipy/blob/e8b043df1d586d9df9fed96add1a536859f1cb8c/scipy/sparse/_index.py#L366-L369

We should pass the axis size along with `idx` and validate that it matches `len(idx)`. This will require passing the sparse container's shape to the `_unpack_index()` helper function.

**Comment by dschult** [comment]
I've got a branch ready to make a PR with the handling of a single boolean index inside `_validate_indices` instead of inside `_unpack...`. Basically take the first 7 lines of `_unpack` and move it inside the class method.

Should I hold back from submitting that PR?

**Comment by perimosocordiae** [comment]
The issue here `sparse.csr_array(x)[[True, False]]` isn't indexing with an ndarray, so it's not handled by the "single boolean matrix" branch that your PR is moving.

**Comment by ivirshup** [comment]
I actually didn't think about masking with a 2d boolean array when reporting the issue. I had been thinking about using a 1d array to mask a specific axis, which I don't think this PR currently addresses.

I've started a branch on top of https://github.com/scipy/scipy/pull/19956 which address this case:

* https://github.com/scipy/scipy/pull/19957

I'd be up for merging my PR into @dschult's, or even only addressing the case of the 1d mask.

I don't know that I have as strong an opinion on whether the shapes should match in the 2d case. It makes sense that they would have to, but also using mismatched shapes seems to be something that was explicitly tested for, so maybe there's an important use case?

**Comment by ivirshup** [comment]
@perimosocordiae 

> Do you think this is the root cause of [gh-19919](https://github.com/scipy/scipy/issues/19919)?
> @ilan-gold FYI

I don't think this is related to that issue. This is just about boolean indexing, while that issue also occurs with fancy integer indexing:

```python
sparse.csr_array(np.arange(50).reshape(5, 10))[[], []].shape
# (1, 0)
```
