### ISSUE TITLE
DOC: clarify scale parameter of scipy.stats.invgauss

### ISSUE THREAD

**Issue by fancidev** [scipy/scipy#19955]
### Issue with current documentation:

The [doc on scipy.stats.invgauss](https://scipy.github.io/devdocs/reference/generated/scipy.stats.invgauss.html#scipy.stats.invgauss) doesn’t mention how to “back out” the common two-parameter form (mu, lambda) from the one-parameter form. It would be helpful to mention it for the casual user (like me) to be able to use it right away.

### Idea or request for content:

Insert the following paragraph into the documentation:

A common two-parameter form of the inverse Gaussian distribution with parameters (`mu`, `lambda`) is equivalent to `invgamma(mu/lambda, scale=lambda)`.

### Additional context (e.g. screenshots, GIFs)

A [related page](https://docs.scipy.org/doc/scipy/tutorial/stats/continuous_invgauss.html) in SciPy Tutorial provides some hint on the transform needed, but the writing style of that page is more of a “note” for someone who already knows the stuff than a “tutorial” for someone who doesn’t know the stuff.

**Comment by mdhaber** [comment]
We have notes like this in [`scipy.stats.norminvgauss`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.norminvgauss.html), [`scipy.stats.gamma`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gamma.html), and others. In those cases, the PDF of the alternative parameterization is also given, so I'd suggest doing that here. 

This looks simple enough, so I'd be willing to review a PR after gh-19932 if you're interested in submitting it. (One at a time, please.)

> for the casual user (like me)

After opening 5 issues and a PR in a week, you have graduated from casual user : )

**Comment by fancidev** [comment]
Cool, let me make a PR after the other one.

I’ll also like to take a look at the tutorial page and see how it fits with the other distribution docs. I tend to write too much in tutorials; I’ll try not to for this one!
