### ISSUE TITLE
MAINT:BLD:special:Overhaul _ufuncs and cython_special machinery

### ISSUE THREAD

**Issue by ilayn** [scipy/scipy#19964]
As discussed in #19824 

In the Cython file generation of special ufuncs and cython_special libs, comments below mention the rationale

https://github.com/scipy/scipy/blob/e8b043df1d586d9df9fed96add1a536859f1cb8c/scipy/special/_generate_pyx.py#L56-L68

many of the complications we have in the `special` build recipe is due to mixing Fortran and C sources. Now that the rewrite is stabilizing and fortran code is out. This machinery can probably be simplified a lot. 

A personal curiosity is whether we can get rid of the intermediate Cythonization step which unfortunately injects a lot of code and seemingly increases the binary size. 

I am not sure but I think scalar kernels can be linked to ufuncs directly without this C++/cython step

**Comment by izaid** [comment]
This is a very good point, as the SciPy special build is really far too over-complicated. It also connects with a thought I've been having that I want to pitch in here.

Given a scalar kernel, what is the easiest way to turn it into a NumPy ufunc? If we are just going to write C code, then we can use `PyUFunc_FromFuncAndDataAndSignature` directly. If we want to stick with Cython, then something like `@ufunc` would do it quite easily. See https://cython.readthedocs.io/en/latest/src/userguide/numpy_ufuncs.html

The only thing is @ufunc doesn't support gufuncs at the moment, but I suppose that could be added. In some of the other array libraries, like CuPy, gufuncs can be created dynamically to wrap C++ or CUDA code. See https://docs.cupy.dev/en/stable/reference/generated/cupy.ElementwiseKernel.html

Is there anything equivalent for NumPy? What would SciPy like to use for this long term?

I personally have used PyUFunc_FromFuncAndDataAndSignature from the C API to turn C++ kernels into ufuncs, but I'd be keen to use something like @ufunc from Cython if it supported everything I needed.
