### ISSUE TITLE
BUG: stable docs site fails to load JQuery

### ISSUE THREAD

**Issue by drammock** [scipy/scipy#19973]
### Describe your issue.

https://docs.scipy.org/doc/scipy/ (currently showing version 1.12.0) shows "failing to find JQuery" errors in the browser console. One consequence of this is that the version switcher doesn't work.

#### History
Following similar decisions in Bootstrap v5 and Sphinx v6, the pydata sphinx theme dropped JQuery inclusion in version 0.13.0rc1 (2023-02-03).

#### Status
The site footer says the v0.12.0 docs were built with Sphinx 7.2.6 (so sphinx won't be providing Jquery), but it looks like they're still being built with v0.9.x of the theme (which ought to still provide it) so I'm not 100% clear what went wrong.  I also haven't investigated the SciPy docs folder carefully yet.

FWIW, the theme offers some transition guidance here: https://pydata-sphinx-theme.readthedocs.io/en/stable/community/topics/bootstrap.html#dropping-jquery

cc @12rambau who might have ideas.

### Reproducing Code Example

```python
go to https://docs.scipy.org/doc/scipy/ and open the browser console (`F12` on Firefox)
```

### Error message

```shell
Uncaught ReferenceError: $ is not defined
    <anonymous> https://docs.scipy.org/doc/scipy/:183
    <anonymous> https://docs.scipy.org/doc/scipy/:221
[scipy:183:5](https://docs.scipy.org/doc/scipy/)
Uncaught ReferenceError: jQuery is not defined
    <anonymous> https://docs.scipy.org/doc/scipy/_static/scripts/pydata-sphinx-theme.js?digest=92025949c220c2e29695:1
    n https://docs.scipy.org/doc/scipy/_static/scripts/pydata-sphinx-theme.js?digest=92025949c220c2e29695:1
    <anonymous> https://docs.scipy.org/doc/scipy/_static/scripts/pydata-sphinx-theme.js?digest=92025949c220c2e29695:32
    n https://docs.scipy.org/doc/scipy/_static/scripts/pydata-sphinx-theme.js?digest=92025949c220c2e29695:1
    <anonymous> https://docs.scipy.org/doc/scipy/_static/scripts/pydata-sphinx-theme.js?digest=92025949c220c2e29695:26
    n https://docs.scipy.org/doc/scipy/_static/scripts/pydata-sphinx-theme.js?digest=92025949c220c2e29695:1
    <anonymous> https://docs.scipy.org/doc/scipy/_static/scripts/pydata-sphinx-theme.js?digest=92025949c220c2e29695:1
    <anonymous> https://docs.scipy.org/doc/scipy/_static/scripts/pydata-sphinx-theme.js?digest=92025949c220c2e29695:1
[pydata-sphinx-theme.js:1:927](https://docs.scipy.org/doc/scipy/_static/scripts/pydata-sphinx-theme.js?digest=92025949c220c2e29695)
Uncaught ReferenceError: $ is not defined
    <anonymous> https://docs.scipy.org/doc/_static/versionwarning.js:13
```

### SciPy/NumPy/Python version and system information

```shell
n/a, this issue is about the website.
```

**Comment by tupui** [comment]
Thanks @drammock, we actually have started a discussion regarding that JS 😅 #19961 TLDR is that I would like to just remove this and this specific issue would go away doing so.

**Comment by lucascolley** [comment]
I think we're hoping that this will have been fixed by upgrading the theme and using the version switcher from there. So should work for 1.12.1 / 1.13.0 ?

**Comment by tupui** [comment]
@lucascolley what do you mean? JQuery is being dropped from the theme. The code which calls some JSQuery is on our side.

**Comment by lucascolley** [comment]
Yeah makes sense, I was just going off https://github.com/scipy/scipy/issues/18031#issuecomment-1771789663 which suggested that upgrading the theme was needed to fix the version switcher, but sounds like we need to remove the JSQuery on top of what's already been merged.

**Comment by drammock** [comment]
> The code which calls some JSQuery is on our side.

Not entirely, because those docs were still being built with theme v0.9.x, so some of the calls to JQuery are in theme code (you can see that in the errors)

honestly the more I think about this it's probably the theme's fault (or at least, we could have prevented this). When we learned that Sphinx 6 would remove JQuery support, we should have added a pin to keep sphinx at or below v5 (and then later removed that pin once our own code had purged JQuery usage).

Regardless, I *think* it will go away once #16660  is backported, so maybe nothing needs to be done.

**Comment by tupui** [comment]
ah right I was looking at the last message only 👍

**Comment by 12rambau** [comment]
in case you want to add jquery back in the build you can also have a look to https://github.com/sphinx-contrib/jquery

This extention have been created when JQuery was dropped from Sphinx and allows you to postpone searching where the requirement is coming from.

**Comment by mattip** [comment]
FWIW, the version switcher is still broken for me on https://docs.scipy.org/doc/scipy/ on firefox. When I look at the dev tools, I see this where JQuery should be used
```
Uncaught ReferenceError: $ is not defined
```

**Comment by lucascolley** [comment]
I know that we are hoping that the version switcher will be fixed when 1.13.0 is released, now that we have upgraded to a newer version of the theme.

**Comment by tupui** [comment]
I said this a few times, we should consider dissociating the doc release process from the release of the library itself. (And doing so move away from the Enthought server...). The current process is really making our lives complicated for nothing and also adds to the release process complexity. The doc team should have the agency to update the doc without a full blown release.

**Comment by lucascolley** [comment]
Agreed, it would be nice to be able to see if the fix has actually worked before the release goes out and we have to wait until the next release to fix things.

**Comment by tupui** [comment]
Also we are constraining ourselves a lot with the CI credits etc. Like the issue we had for the last year not being able to update. That was just a timeout in the end. So if I would have had access to the doc infra, I would just have uploaded the new version. We don't have to match the repo state 100% for the infra part.
