### ISSUE TITLE
DOC/REL: retroactively add missing expired deprecations to 1.12.0 release notes

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#19974]
As per https://github.com/scipy/scipy/issues/19972#issuecomment-1912626337, the deprecations from gh-19067 didn't make their way into the 1.12.0 release notes.

**Comment by lucascolley** [comment]
@rgommers what action needs to be taken here?

**Comment by lucascolley** [comment]
I can make the PR if it is just changing them from now on. Thoughts @tylerjereddy ?

**Comment by tylerjereddy** [comment]
I suppose we could mention it in gh-19880, although the ship obviously sailed in the previous release so I'm not sure what we'd say. "Hey, this has been gone for a bit and we forgot to tell you!" I think that's been considered bad practice/deprecated for quite some time at least.

Perhaps there will be a `1.12.1` release where we could mention it, but I'm not so sure, the support effort for `1.13.x` series with NumPy 2 may be reasonably high, and then `1.14.x` may be fairly shortly after that unless we delayed for the no GIL/free-threading CPython `3.13` stuff.

**Comment by lucascolley** [comment]
We can also add it to the 1.12.0 release notes right, so that if someone lands on them from the stable docs after 1.13.0 is released then they'll be able to see it.

**Comment by tylerjereddy** [comment]
I suppose we could do that, to get the stable + devdocs pointing to an updated version yeah.

 Editing the GitHub-posted version of the release notes is even easier I think.

**Comment by tylerjereddy** [comment]
So maybe a PR against `main` to update the old `1.12.0` relnotes, editing the GitHub-posted version a little, and a backport PR to `maintenance/1.12.x` which may not actually get another release but doesn't hurt to merge since I already bumped it to `1.12.1.dev0`.
