### ISSUE TITLE
BUG: gcc link to atomic fails on armel: undefined reference to `__atomic_load_n'

### ISSUE THREAD

**Issue by drew-parsons** [scipy/scipy#19982]
### Describe your issue.

PR #17777 added a test for atomic symbols, to define `atomic_dep` for 32 bit ARM systems (armel).
However debian builds are still failing after applying the patch, e.g.https://buildd.debian.org/status/fetch.php?pkg=scipy&arch=armel&ver=1.10.1-9&stamp=1706418236&raw=0
```
...
Checking if "Check atomic builtins without -latomic" : links: NO 
Library atomic found: YES
Checking if "Check atomic builtins with -latomic" with dependency -latomic: links: NO 
Checking if "Check atomic builtins without -latomic" : links: NO (cached)
Library atomic found: YES
Checking if "Check atomic builtins with -latomic" with dependency -latomic: links: NO (cached)
...
[1611/1612] c++ -Iscipy/optimize/_highs/_highs_wrapper.cpython-312-arm-linux-gnueabi.so.p -Iscipy/optimize/_highs -I../scipy/optimize/_highs -I/usr/lib/python3/dist-packages/numpy/core/include -I../scipy/optimize/_highs/cython/src -I../scipy/optimize/_highs/src -I../scipy/_lib/highs/src -I../scipy/_lib/highs/src/io -I../scipy/_lib/highs/src/lp_data -I../scipy/_lib/highs/src/util -I/usr/include/python3.12 -I/usr/include/arm-linux-gnueabi/python3.12 -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++14 -O3 -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -pthread -Wno-class-memaccess -Wno-format-truncation -Wno-non-virtual-dtor -Wno-sign-compare -Wno-switch -Wno-unused-but-set-variable -Wno-unused-variable '-DCMAKE_BUILD_TYPE="RELEASE"' -DFAST_BUILD=ON '-DHIGHS_GITHASH="n/a"' '-DHIGHS_COMPILATION_DATE="2021-07-09"' -DHIGHS_VERSION_MAJOR=1 -DHIGHS_VERSION_MINOR=2 -DHIGHS_VERSION_PATCH=0 -DHIGHS_DIR=/<<PKGBUILDDIR>>/scipy/optimize/_highs/../../_lib/highs -UOPENMP -UEXT_PRESOLVE -USCIP_DEV -UHiGHSDEV -UOSI_FOUND -DNDEBUG -Wno-cpp -MD -MQ scipy/optimize/_highs/_highs_wrapper.cpython-312-arm-linux-gnueabi.so.p/meson-generated__highs_wrapper.cpp.o -MF scipy/optimize/_highs/_highs_wrapper.cpython-312-arm-linux-gnueabi.so.p/meson-generated__highs_wrapper.cpp.o.d -o scipy/optimize/_highs/_highs_wrapper.cpython-312-arm-linux-gnueabi.so.p/meson-generated__highs_wrapper.cpp.o -c scipy/optimize/_highs/_highs_wrapper.cpython-312-arm-linux-gnueabi.so.p/_highs_wrapper.cpp
[1612/1612] c++  -o scipy/optimize/_highs/_highs_wrapper.cpython-312-arm-linux-gnueabi.so scipy/optimize/_highs/_highs_wrapper.cpython-312-arm-linux-gnueabi.so.p/meson-generated__highs_wrapper.cpp.o -Wl,--as-needed -Wl,--allow-shlib-undefined -Wl,-O1 -shared -fPIC -Wl,-z,relro -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wl,--start-group scipy/optimize/_highs/libhighs.a scipy/optimize/_highs/libipx.a scipy/optimize/_highs/libbasiclu.a -Wl,--end-group -Wl,--version-script=/<<PKGBUILDDIR>>/scipy/_build_utils/link-version-pyinit.map -pthread
...
../../.pybuild/cpython3_3.12_scipy/build/scipy/optimize/_linprog_highs.py:20: in <module>
    from ._highs._highs_wrapper import _highs_wrapper
E   ImportError: /<<PKGBUILDDIR>>/.pybuild/cpython3_3.12_scipy/build/scipy/optimize/_highs/_highs_wrapper.cpython-312-arm-linux-gnueabi.so: undefined symbol: __atomic_compare_exchange_8
_ ERROR collecting .pybuild/cpython3_3.12_scipy/build/scipy/integrate/_ivp/tests/test_rk.py _
```
 
PR #17777 added atomic test code (copied below) to scipy/meson.build.  Running it manually  shows that `__atomic_load_n` is not defined in libatomic.so for gcc.  `__atomic_add_fetch` (and `__atomic_compare_exchange_8`) are defined.

Inspecting symbols explicitly:
```
(sid_armel-dchroot)$ nm -D /usr/lib/gcc/arm-linux-gnueabi/13/libatomic.so | grep __atomic_add_fetch
00002640 i __atomic_add_fetch_1@@LIBATOMIC_1.0
00003164 i __atomic_add_fetch_2@@LIBATOMIC_1.0
00003bec i __atomic_add_fetch_4@@LIBATOMIC_1.0
00004684 i __atomic_add_fetch_8@@LIBATOMIC_1.0
(sid_armel-dchroot)$ nm -D /usr/lib/gcc/arm-linux-gnueabi/13/libatomic.so | grep __atomic_compare_exchange_8
000043dc i __atomic_compare_exchange_8@@LIBATOMIC_1.0
(sid_armel-dchroot)$ nm -D /usr/lib/gcc/arm-linux-gnueabi/13/libatomic.so | grep load_n
(sid_armel-dchroot)$ nm -D /usr/lib/gcc/arm-linux-gnueabi/12/libatomic.so | grep load_n
(sid_armel-dchroot)$ nm -D /usr/lib/gcc/arm-linux-gnueabi/11/libatomic.so | grep load_n
(sid_armel-dchroot)$ nm -D /usr/lib/gcc/arm-linux-gnueabi/10/libatomic.so | grep load_n
```
so gcc has never had a `load_n` atomic symbol.

Should the `__atomic_load_n` line in scipy/meson.build be dropped?
Perhaps the test for `__atomic_add_fetch` is sufficient for testing atomic availability?

### Reproducing Code Example

```python
#include <stdint.h>
  int main() {
   struct {
     uint64_t *v;
   } x;
   return (int)__atomic_load_n(x.v, __ATOMIC_ACQUIRE) &
          (int)__atomic_add_fetch(x.v, (uint64_t)1, __ATOMIC_ACQ_REL);
  }
```

### Error message

```shell
(sid_armel-dchroot)$ gcc -L/usr/lib/gcc/arm-linux-gnueabi/13/  -latomic test.c
/usr/bin/ld: /tmp/cc4viOox.o: in function `main':
test.c:(.text+0x18): undefined reference to `__atomic_load_8'
/usr/bin/ld: test.c:(.text+0x40): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
```

### SciPy/NumPy/Python version and system information

```shell
1.10.1 1.24.2 sys.version_info(major=3, minor=11, micro=7, releaselevel='final', serial=0)
/usr/lib/python3/dist-packages/scipy/__config__.py:140: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "13.2.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "0.29.36",
      "commands": "cython3"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "13.2.0",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "13.2.0",
      "commands": "gfortran"
    },
    "pythran": {}
  },
  "Machine Information": {
    "host": {
      "cpu": "armv8l",
      "family": "arm",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "armv8l",
      "family": "arm",
      "endian": "little",
      "system": "linux"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "blas",
      "found": true,
      "version": "3.11.0",
      "detection method": "pkgconfig",
      "include directory": "/usr/include/arm-linux-gnueabi",
      "lib directory": "/usr/lib/arm-linux-gnueabi",
      "openblas configuration": "unknown",
      "pc file directory": "/usr/lib/arm-linux-gnueabi/pkgconfig"
    },
    "lapack": {
      "name": "lapack",
      "found": true,
      "version": "3.11.0",
      "detection method": "pkgconfig",
      "include directory": "/usr/include/arm-linux-gnueabi",
      "lib directory": "/usr/lib/arm-linux-gnueabi",
      "openblas configuration": "unknown",
      "pc file directory": "/usr/lib/arm-linux-gnueabi/pkgconfig"
    }
  },
  "Python Information": {
    "path": "/usr/bin/python3.11",
    "version": "3.11"
  }
}
```

**Comment by drew-parsons** [comment]
At the same time there's some other problem with linking.  The error message also shows
```
/usr/bin/ld: test.c:(.text+0x40): undefined reference to `__atomic_fetch_add_8'
```
even though `__atomic_fetch_add_8` is in /usr/lib/gcc/arm-linux-gnueabi/13/libatomic.so

**Comment by drew-parsons** [comment]
For reference, other packages have had to deal with the same problem, for instance via cmake,
https://github.com/google/highway/pull/1008
https://github.com/vcmi/vcmi/issues/3109
The test symbol there is slightly different.

I'm not sure if cmake make a specific flag for the problem, `HAVE_CXX_ATOMICS64_WITHOUT_LIB`
https://reviews.llvm.org/D132799
perhaps that was defined by llvm not cmake.
 
Resolving the problem for debian is currently impeded by other problems in gcc itself (such that `gcc -latomic test.c` does not resolve), including
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113635
libatomic now needs `libat_test_and_set_1_i2` with gcc13 on armel, but the symbol is missing.

**Comment by rgommers** [comment]
Thanks for the detailed issue description and solution suggestions @drew-parsons.

GCC & co created a bit of a painful mess here. It looks like the short-term solution is indeed to just tweak the symbol being checked to whatever works.

Longer-term, this is best handled at the build system level. I just found https://github.com/mesonbuild/meson/issues/10621, which looks like the right thing to do so we can get rid of the support code for this.

> Should the `__atomic_load_n` line in scipy/meson.build be dropped?
> Perhaps the test for `__atomic_add_fetch` is sufficient for testing atomic availability?

Probably. I unfortunately don't have a great way to test. Any tweak to the symbols that does the job in Debian CI seems acceptable to me.

> [](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113635)
> libatomic now needs `libat_test_and_set_1_i2` with gcc13 on armel, but the symbol is missing.

That link's discussion seems to say that the regression is in GCC 14. Does it actually show up with the latest stable GCC release?

**Comment by drew-parsons** [comment]
Test box is back online, gcc 13.2.0 (13.2.0-13).  The current version of libatomic1 is 14-20240201-2.  So debian is using libatomic from gcc-14.  I guess this is related to the problem (if not the actual source of the problem).

/usr/lib/gcc/arm-linux-gnueabi/13/libatomic.so is provided by libgcc-13-dev 13.2.0-13, but as a symlink to ../../../arm-linux-gnueabi/libatomic.so.1, i.e. /usr/lib/arm-linux-gnueabi/libatomic.so.1.2.0, which is provided by libatomic1 
14-20240201-2

Current behaviour is the same as I first reported: for scipy's atomic test (checking both `__atomic_load_n` and `__atomic_add_fetch`), neither symbol (in `_8` form) is found.  I said that there is no `__atomic_load_n` symbol in the library, but it gets delegated to `__atomic_load_8`, which is available (I had looked for `load_n` rather than just `load`),
```
$ nm -D /usr/lib/gcc/arm-linux-gnueabi/13/libatomic.so | grep load  
000015a4 T __atomic_load@@LIBATOMIC_1.0
000022a0 i __atomic_load_1@@LIBATOMIC_1.0
00002da8 i __atomic_load_2@@LIBATOMIC_1.0
00003910 i __atomic_load_4@@LIBATOMIC_1.0
000041f0 i __atomic_load_8@@LIBATOMIC_1.0
```

So the error message is currently still
```
$ gcc -latomic test1.c 
/usr/bin/ld: /tmp/ccu4FFaE.o: in function `main':
test1.c:(.text+0x18): undefined reference to `__atomic_load_8'
/usr/bin/ld: test1.c:(.text+0x40): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
```
finding neither the load  symbol nor the fetch symbol (as `_8`). But both symbols are present in libatomic.so.

**Comment by drew-parsons** [comment]
The `libat_test_and_set_1_i2` doesn't seem to be directly relevant here (it's not showing up in my tests). I do get a reference to missing `__sync_add_and_fetch_1` from the C++ version of the test (from cmake), if I first compile to *.o and then try to link with `ld -o test3 test3.o -L/usr/lib/gcc/arm-linux-gnueabi/13 -latomic`.  I'm not sure why that is but I think it's a distraction for us here (scipy is invoking C not C++).

**Comment by drew-parsons** [comment]
I think I can see a resolution.  Rookie error in the order of libraries.  This variant compiles successfully, putting `-latomic` last,
```
gcc test1.c -latomic
```
rather than `gcc -latomic test1.c`

I'll confirm we can use this to restore the debian armel build, and then I think we can close this bug.

**Comment by drew-parsons** [comment]
Actually looks like in the meantime it's already been fixed. Build is now successful, 
https://buildd.debian.org/status/fetch.php?pkg=scipy&arch=armel&ver=1.10.1-10&stamp=1706803803&raw=0

I guess it was sorted out in the debian gcc toolchain in the recent updates.  Perhaps gcc-13 just needed a rebuild against libatomic from gcc-14.

So, closing the bug now.

**Comment by rgommers** [comment]
Great, thanks @drew-parsons!
