### ISSUE TITLE
DOC: Boundary conditions in splrep

### ISSUE THREAD

**Issue by mzechmeister** [scipy/scipy#19998]
### Issue with current documentation:

The doc for [`splrep`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.splrep.html#scipy.interpolate.splrep) (v1.12.0) is unclear about the boundary condition type;  only `per` is mentioned.
From the notes in [`CubicSpline`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.CubicSpline.html#scipy.interpolate.CubicSpline) I get that the default in `splrep` corresponds to `'not-a-knot'`.

### Idea or request for content:

Add to the `per` doc, that it defaults to `'not-a-knot'` and that `CubicSpline` provides more options for boundary conditions.

**Comment by ev-br** [comment]
Documentation update PRs are always welcome. Would you be interested in sending one with this update?

**Comment by mzechmeister** [comment]
Ok, I tried. Feel free to revise ;)
