### ISSUE TITLE
angle module returns an import error

### ISSUE THREAD

**Issue by khider** [scipy/scipy#19992]
### Describe your issue.

Error on import `spicy.angle`

Would like to know what's the proper way to import the angle module now. 

### Reproducing Code Example

```python
from spicy import angle
```

### Error message

```shell
ImportError: cannot import name 'angle' from 'scipy' (/home/docs/checkouts/readthedocs.org/user_builds/pyleoclim-util/conda/latest/lib/python3.11/site-packages/scipy/__init__.py)
```

### SciPy/NumPy/Python version and system information

```shell
spicy 0.12.0
python 3.11
```

**Comment by ev-br** [comment]
`from numpy import angle`

**Comment by khider** [comment]
Thank you!
