### ISSUE TITLE
BUG: Problem installing Spicy

### ISSUE THREAD

**Issue by Nazarennno** [scipy/scipy#20025]
### Describe your issue.

I used the following command: pip install spicy
Everything went OK until this happened:

### Reproducing Code Example

```python
Collecting spicy
  Using cached spicy-0.16.0-py2.py3-none-any.whl (1.7 kB)
Collecting scipy (from spicy)
  Using cached scipy-1.12.0.tar.gz (56.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      + meson setup C:\Users\PCYCEL\AppData\Local\Temp\pip-install-y3xkm_k1\scipy_1eb1c6af40d6423f86160b4f342ba83d C:\Users\PCYCEL\AppData\Local\Temp\pip-install-y3xkm_k1\scipy_1eb1c6af40d6423f86160b4f342ba83d\.mesonpy-eqlp7ryj -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\PCYCEL\AppData\Local\Temp\pip-install-y3xkm_k1\scipy_1eb1c6af40d6423f86160b4f342ba83d\.mesonpy-eqlp7ryj\meson-python-native-file.ini
      The Meson build system
      Version: 1.3.1
      Source dir: C:\Users\PCYCEL\AppData\Local\Temp\pip-install-y3xkm_k1\scipy_1eb1c6af40d6423f86160b4f342ba83d
      Build dir: C:\Users\PCYCEL\AppData\Local\Temp\pip-install-y3xkm_k1\scipy_1eb1c6af40d6423f86160b4f342ba83d\.mesonpy-eqlp7ryj
      Build type: native build
      Project name: scipy
      Project version: 1.12.0
      WARNING: Failed to activate VS environment: Could not parse vswhere.exe output

      ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] El sistema no puede encontrar el archivo especificado"
      Running `cl /?` gave "[WinError 2] El sistema no puede encontrar el archivo especificado"
      Running `cc --version` gave "[WinError 2] El sistema no puede encontrar el archivo especificado"
      Running `gcc --version` gave "[WinError 2] El sistema no puede encontrar el archivo especificado"
      Running `clang --version` gave "[WinError 2] El sistema no puede encontrar el archivo especificado"
      Running `clang-cl /?` gave "[WinError 2] El sistema no puede encontrar el archivo especificado"
      Running `pgcc --version` gave "[WinError 2] El sistema no puede encontrar el archivo especificado"

      A full log can be found at C:\Users\PCYCEL\AppData\Local\Temp\pip-install-y3xkm_k1\scipy_1eb1c6af40d6423f86160b4f342ba83d\.mesonpy-eqlp7ryj\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Error message

```shell
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### SciPy/NumPy/Python version and system information

```shell
Python 3.12.1 was used
```

**Comment by andyfaff** [comment]
There is project confusion here, this is the issues book for scipy not spicy.

**Comment by rkern** [comment]
`spicy` is just a (friendly) typo-squat to redirect people to `scipy` (and thus prevent unfriendly typo-squatters from inserting malware there).

Try to install `scipy` directly with `pip`. It's possible that the dependency resolution messed with it being able to find the binary wheel for your platform. Thus it tried to build from source, which is very complicated and requires a lot of compiler tooling that you do not have installed on your system.

**Comment by Nazarennno** [comment]
I see.. I mistyped scipy as spicy lol... Thanks!

**Comment by Nazarennno** [comment]
Now I tried without the typo and the same error happens: 
Collecting scipy
  Using cached scipy-1.12.0.tar.gz (56.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      + meson setup C:\Users\PCYCEL\AppData\Local\Temp\pip-install-3x04vmzm\scipy_f116eb6973004fb9b733cf48001f9010 C:\Users\PCYCEL\AppData\Local\Temp\pip-install-3x04vmzm\scipy_f116eb6973004fb9b733cf48001f9010\.mesonpy-ukh_cben -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\PCYCEL\AppData\Local\Temp\pip-install-3x04vmzm\scipy_f116eb6973004fb9b733cf48001f9010\.mesonpy-ukh_cben\meson-python-native-file.ini

      ERROR: Neither source directory 'C:\\Users\\PCYCEL\\AppData\\Local\\Temp\\pip-install-3x04vmzm\\scipy_f116eb6973004fb9b733cf48001f9010' nor build directory 'C:\\Users\\PCYCEL\\AppData\\Local\\Temp\\pip-install-3x04vmzm\\scipy_f116eb6973004fb9b733cf48001f9010\\.mesonpy-ukh_cben' contain a build file meson.build.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by andyfaff** [comment]
Are you using 32 bit python? If so, then you need to use 64 bit python in order to use the most recent versions of scipy.

**Comment by Nazarennno** [comment]
it was AMD64

**Comment by Nazarennno** [comment]
And yes, the one i used for my project is 32 bit

**Comment by andyfaff** [comment]
Ok, there are no 32 bit wheels available for scipy. You will need to use a 64 bit python interpreter in order to use recent versions of scipy. You won't be able to compile a 32 bit wheel either.

**Comment by rkern** [comment]
Root problem found; closing.

**Comment by Nazarennno** [comment]
thanks finally
