### ISSUE TITLE
TST: prefer `pytest.warns` over `np.testing.assert_warns`

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#20031]
Several SciPy tests (at least in `stats`) attempt to use `np.testing.assert_warns` with a `match` parameter, but [`np.testing.assert_warns`](https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_warns.html) ignores the `match` parameter. For instance, this passes:

```python3
from numpy.testing import assert_warns
import warnings

with assert_warns(UserWarning, match="A"):
    warnings.warn("B", UserWarning)
```

We might expect it to fail because `match` isn't a keyword of `assert_warns`, but that doesn't happen either; `**kwds` is ignored unless `*args` is passed ([code](https://github.com/numpy/numpy/blob/d35cd07ea997f033b2d89d349734c61f5de54b0d/numpy/testing/_private/utils.py#L1771-L1772)). I'll consider opening a report about this at NumPy.

```python3
import pytest
import warnings

with pytest.warns(UserWarning, match="A"):
    warnings.warn("B", UserWarning)

# Failed: DID NOT WARN. No warnings of type (<class 'UserWarning'>,) matching the regex were emitted.
#  Regex: A
#  Emitted warnings: [UserWarning('B')]
```

The recommendation is to replace uses of `np.testing.warns` with `pytest.warns`, at least where a `match` parameter is supposed to be used. (And where it isn't being used, it [should](https://docs.scipy.org/doc/scipy/dev/missing-bits.html#testing-that-expected-exceptions-are-raised). There are a lot of warning messages out there.)

**Comment by WillTirone** [comment]
I can try this one. Are there any files in particular you want to start with, or just everywhere it appears in stats and other modules?

**Comment by mdhaber** [comment]
I'd start with everywhere it appears with a `match` argument, because those are objectively mistakes. I'd consider that - and maybe adding a note of caution against NumPy's assertions to https://docs.scipy.org/doc/scipy/dev/missing-bits.html#testing-that-expected-exceptions-are-raised - would be enough to close the issue. Improving all the error/warning checks (including those that use `pytest`) that don't have a `match` argument is a much bigger undertaking, and not one that I mean to get into. Thanks!

**Comment by WillTirone** [comment]
Sure. So as an example, here's one from `test_stats.py` : 

```python 
def test_constant_input(self):
    # Zero variance input
    # See https://github.com/scipy/scipy/issues/3728
    msg = "An input array is constant"
    with assert_warns(stats.ConstantInputWarning, match=msg):
        r, p = stats.pearsonr([0.667, 0.667, 0.667], [0.123, 0.456, 0.789])
        assert_equal(r, np.nan)
        assert_equal(p, np.nan)
```

And this should become: 

```python 
def test_constant_input(self):
    # Zero variance input
    # See https://github.com/scipy/scipy/issues/3728
    # See https://docs.scipy.org/doc/scipy/dev/missing-bits.html#testing-that-expected-exceptions-are-raised
    msg = "An input array is constant"
    with pytest.warns(stats.ConstantInputWarning, match=msg):
        r, p = stats.pearsonr([0.667, 0.667, 0.667], [0.123, 0.456, 0.789])
        assert_equal(r, np.nan)
        assert_equal(p, np.nan)
```

I'm not actually sure what you mean by "adding a specific recommendation to [The Missing Bits](https://docs.scipy.org/doc/scipy/dev/missing-bits.html#testing-that-expected-exceptions-are-raised) against NumPy's assertions". Like what I have above, or something else?

**Comment by tylerjereddy** [comment]
I'm guessing Matt means to specifically discourage (via a documentation update there) using the NumPy `assert_warns` moving forward, in favor of the more accurate match-enabled pytest functionality. I'm guessing he did not mean to add a comment to the source about it though.

**Comment by WillTirone** [comment]
Ahhh yes, I understand now. Thank you @tylerjereddy!

**Comment by mdhaber** [comment]
@WillTirone Would you be interested in replacing `numpy.assert_raises` and `numpy.assert_warns` with the `pytest` equivalents throughout SciPy and/or NumPy tests? In gh-25989, it sounds like NumPy would consider deprecating these functions if they were replaced throughout the codebase.

**Comment by WillTirone** [comment]
@mdhaber sure, happy to! Do you have a rough timeline for when we want this completed?

**Comment by mdhaber** [comment]
Maybe in time for SciPy 1.14.0? Not urgent.

**Comment by WillTirone** [comment]
Sounds good, I'll take a look and see how prevalent it is.

**Comment by WillTirone** [comment]
Sorry for the delay, have some build issues and traveling at the moment, will get started on it shortly @mdhaber :)

**Comment by WillTirone** [comment]
Once again, sorry for the delay, was very busy with the job hunt. Will start on this soon.
