### ISSUE TITLE
ENH: Adding zgemm3m to scipy.linalg.cython_blas

### ISSUE THREAD

**Issue by gabrielfougeron** [scipy/scipy#20049]
### Is your feature request related to a problem? Please describe.

I have plenty of complex-complex matrix multiplications in my cython code, and I currently use `scipy.linalg.cython_blas.zgemm` to treat them in a nogil environment. I've heard of `zgemm3m` being sometimes able to provide a substantial performance gain, sometimes at the expense of numerical stability.

Was any thought put into including `zgemm3m` in `scipy.linalg.cython_blas` ?
The only reference I could find was this post from 2015 : https://github.com/scipy/scipy/issues/5266

### Describe the solution you'd like.

provide an interface to  `zgemm3m` in `scipy.linalg.cython_blas` similar to `scipy.linalg.cython_blas.zgemm`

### Describe alternatives you've considered.

Live with the dread of performance being left on the table

**Comment by rgommers** [comment]
Hi @gabrielfougeron, thanks for the suggestion. I'm not sure we can do anything with this, since `zgemm3m` is not a standard BLAS function but an extension. MKL and OpenBLAS have it, but reference BLAS and Accelerate don't. So I don't see how we can make it available in a reasonable way.

**Comment by j-bowhay** [comment]
Closing as unfortunately we can't implement this for the reasons above
