### ISSUE TITLE
ENH:linalg: kron does not support nd arrays with n>2

### ISSUE THREAD

**Issue by ricardoV94** [scipy/scipy#20072]
Is this a feature?

> Re. `scipy.linalg.kron`, I'm not sure whether it might not be better to just delegate to `numpy.kron`, unless there are any advantages to `scipy.linalg.kron`. `numpy.kron` works with empty array arguments and also handles n-dimensional arrays, whereas `scipy.linalg.kron` gives some funny results when the number of dimensions is not two:
>
>```python
>linalg.kron(np.empty((1,2,3)), >np.empty((4,5,6))).shape
>(3, 8, 5, 6)  # should be (4, 10, 18)
>```

_Originally posted by @JozsefKutas in https://github.com/scipy/scipy/pull/18673#issuecomment-1590329028_

**Comment by ilayn** [comment]
Hi @ricardoV94, you can continue the discussion in the linked issue. But honestly this is not an actionable query for us. Is yes an answer or no is?

**Comment by ricardoV94** [comment]
> But honestly this is not an actionable query for us. Is yes an answer or no is?

I can't parse this sentence. What do you mean?

I opened an issue to ask whether the behavior is a feature (which I can't quite grasp) or a bug. 

The reason for that is if it's a bug we don't need to worry about supporting the behavior in PyTensor: https://github.com/pymc-devs/pytensor/pull/622#issuecomment-1937710505

**Comment by ilayn** [comment]
I also don't understand your query. The subject says it is broken then text has a question if it is a feature

We don't have any support for nd arrays yet for [`linalg.kron`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.kron.html)

**Comment by ricardoV94** [comment]
Neither the excerpt nor the documentation were clear as to whether the behavior was indeed a bug.

If it's a bug shouldn't you leave the issue opened until is resolved? That PR is addressing something else and AFAICT it's not fixing the issue.

**Comment by ilayn** [comment]
The docs are mentioning that the inputs are expecting 2D arrays with clearly stated dims. If you think it is still not clear then PR is welcome or if you wish to expand to nd arrays too.

**Comment by ricardoV94** [comment]
Thanks, just wanted to double check it's a bug/undefined behavior.

**Comment by ilayn** [comment]
Done

**Comment by lucascolley** [comment]
> The docs are mentioning that the inputs are expecting 2D arrays with clearly stated dims. If you think it is still not clear then PR is welcome

Whereabouts in the docs is this mentioned? I think https://scipy.github.io/devdocs/reference/generated/scipy.linalg.kron.html#scipy.linalg.kron could do with a note to say that the inputs must be 2D.

**Comment by lucascolley** [comment]
@ricardoV94 for future reference, this syntax means that, for example, the shape of the input to `a` must be `M` by `N`, hence it must be 2D. I think the documentation is clear enough once you understand this.

<img width="196" alt="image" src="https://github.com/scipy/scipy/assets/51488791/75e2c667-edf7-40dd-a625-9f4074893ed2">

**Comment by lucascolley** [comment]
cross posting @ricardoV94 's comment from https://github.com/numpy/numpydoc/pull/423

> For context, that was not in fact the source of confusion. The confusion was that it was not mentioned that batch dimensions are not supported, and the function silently returning nonsense for >2D cases.

> The syntax like (..., M, N) usually clarifies core vs batch cases, but the ommission of ellipsis to specify batch dimensions are not allowed/undefined behavior is imo too subtle/insufficient. I think this should always be stated explicitly if not checked by the function, given the widespread expectation that numpy-like code will handle batch dimensions correctly.

Would you like to suggest a change to the documentation @ricardoV94 ?

**Comment by ricardoV94** [comment]
> Would you like to suggest a change to the documentation @ricardoV94 ?

Mentioning the limitation would have been helpful.

An explicit ValueError/NotImplementedError for ndim != 2 may also be worth discussing but I don't know what's scipy policy regarding checks/undefined behavior of that kind.
