### ISSUE TITLE
BUG: spatial: cdist does not give precise results

### ISSUE THREAD

**Issue by HelloWorldLTY** [scipy/scipy#20081]
### Describe your issue.

Hi, I am using cdist to compute the paired cosine similarity of rows of two matrices. However, I found that for the same set od data, the cossim are different, thus my testing results based on wilcoxon also changed.

I wonder if there are any methods I can use to compute cossim precisely.

### Reproducing Code Example

```python
example:

compare_sim = 1 - sp.distance.cdist(feature_new_gene, feature_new_prot, 'cosine')
compare_sim1 = 1 - sp.distance.cdist(feature_new_gene, feature_new_prot, 'cosine')

compare_sim - compare_sim1 

are not very closed to 0.
```

### Error message

```shell
No error, just not precise.
```

### SciPy/NumPy/Python version and system information

```shell
scipy                        1.12.0
```

**Comment by j-bowhay** [comment]
Please provide a self-contained example reproducing the problem. It is virtually impossible for us to debug without:)

**Comment by HelloWorldLTY** [comment]
This error should be caused by my step which generated the feature_new_gene. Sorry to make confuse.
