### ISSUE TITLE
conjugate gradient resulting segmentation fault when using complex values

### ISSUE THREAD

**Issue by ahmad681** [scipy/scipy#20088]
### Describe your issue.

I have a linear system of equations that is being set up using complex numbers. It kept throwing out error as segmentation fault. I thought first it was my code, however, i realized later that linalg.cg() is not working well with complex numbers. (see below)  
So I test the example as in the webpage, and sure it does result in segmentation fault. but with real numbers no issues. 

I checked my scipy version, and I have 1.8.0 

thanks a lot in advance, 

### Reproducing Code Example

```python
>>> import numpy as np
>>> from scipy.sparse import csc_matrix
>>> from scipy.sparse.linalg import cg
>>> P = np.array([[4+1j, 0+2j, 1-1j, 0+1j],
...               [0+2, 5+1j, 0+0j, 0+1j],
...               [1+1j, 0+0j, 3+1j, 2+2j],
...               [0+0j, 0+0j, 2-2j, 4+3j]])
>>> P
array([[4.+1.j, 0.+2.j, 1.-1.j, 0.+1.j],
       [2.+0.j, 5.+1.j, 0.+0.j, 0.+1.j],
       [1.+1.j, 0.+0.j, 3.+1.j, 2.+2.j],
       [0.+0.j, 0.+0.j, 2.-2.j, 4.+3.j]])
>>> A = csc_matrix(P)
>>> A
<4x4 sparse matrix of type '<class 'numpy.complex128'>'
        with 12 stored elements in Compressed Sparse Column format>
>>> b = np.array([-1-0.1j, -0.5+2j, -1-1j, 2+1j])
>>> x, exit_code = cg(A, b, atol=1e-5)
Segmentation fault
```

### Error message

```shell
Segmentation fault
```

### SciPy/NumPy/Python version and system information

```shell
python 3.9.16
numpy 1.22.2 
scipy 1.8.0 


1.8.0 1.21.5 sys.version_info(major=3, minor=9, micro=16, releaselevel='final', serial=0)


and by the way I am using a conda environment, like 4.18 or something like that. 

lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
```

**Comment by lucascolley** [comment]
Hi @ahmad681 , SciPy 1.8.0 is quite old now. Could you try with a more recent version like 1.12.0 and let us know if the problem persists?

**Comment by ahmad681** [comment]
Lucas, thanks a lot, yes that worked perfectly. 
Just one more thing to add, I would like to look at the progress of the residual norm, 

import inspect
def report(resid):
    frame = inspect.currentframe().f_back
    print(frame.f_locals['r']) 
prints out the entire vector, but I want to look at the norm. I don't see a keyword in the source code where I can print this out at every iteration.  
i tried, print(frame.f_locals['np.linalg.norm(r)']), but cannot work of course. 

thank you so much for the great help, much appreciated it.

**Comment by lucascolley** [comment]
I may be misunderstanding the question, but if I understand correctly can you do

```python
frame = inspect.currentframe().f_back
print(np.linalg.norm(frame.f_locals['r']))
```

**Comment by ahmad681** [comment]
yeah I got it, actually got it to work before the thread. I really appreciate the help, thank you so much Lucas. I am all good now.
