### ISSUE TITLE
BUG: interpolat: Derivative Member is broken with the _from_tck method

### ISSUE THREAD

**Issue by DelisleLab** [scipy/scipy#20105]
### Describe your issue.

When I reconstruct a UnivariateSpline using _from_tck, the spline seems to be faithfully reconstructed, but the Derivative Member function no longer works.

### Reproducing Code Example

```python
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import UnivariateSpline

# Example Interpolation

rng = np.random.default_rng()
x = np.linspace(-3, 3, 50)
y = np.exp(-x**2) + 0.1 * rng.standard_normal(50)

k = 3

spline = UnivariateSpline(x, y, k=k , s=0.5)
xs = np.linspace(-3, 3, 1000)
plt.plot(xs, spline(xs), 'g', lw=3)
plt.plot(x, y, 'ro', ms=5)
plt.show()

plt.plot(xs, spline.derivative()(xs), 'b')
plt.title("Derivative")
plt.show()

# Reconstruction seems to break Derivative function

t = spline.get_knots()
t = np.concatenate(([t[0]]*k, t, [t[-1]]*k))
c = spline.get_coeffs()
tck = t,c,k
spl = UnivariateSpline._from_tck(tck)

# Spline values are faithfully reproduced
print("Error in spline reconstruction:", np.max(np.abs(spline(xs) - spl(xs))) )

# But Derivative is undefined
spl.derivative()

quit()
```

### Error message

```shell
ValueError                                Traceback (most recent call last)
Cell In[16], line 1
----> 1 spl.derivative()

File /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/interpolate/_fitpack2.py:582, in UnivariateSpline.derivative(self, n)
    537 def derivative(self, n=1):
    538     """
    539     Construct a new spline representing the derivative of this spline.
    540 
   (...)
    580 
    581     """
--> 582     tck = _fitpack_impl.splder(self._eval_args, n)
    583     # if self.ext is 'const', derivative.ext will be 'zeros'
    584     ext = 1 if self.ext == 3 else self.ext

File /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/scipy/interpolate/_fitpack_impl.py:766, in splder(tck, n)
    764 dt = dt[sh]
    765 # Compute the new coefficients
--> 766 c = (c[1:-1-k] - c[:-2-k]) * k / dt
    767 # Pad coefficient array to same size as knots (FITPACK
    768 # convention)
    769 c = np.r_[c, np.zeros((k,) + c.shape[1:])]

ValueError: operands could not be broadcast together with shapes (2,) (6,)
```

### SciPy/NumPy/Python version and system information

```shell
1.12.0 1.26.3 sys.version_info(major=3, minor=12, micro=1, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.1
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 13.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 13.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 11.3.0
  pythran:
    include directory: ../../../../../../private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-jysqhmwv/overlay/lib/python3.12/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: darwin
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: darwin
Python Information:
  path: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-kj75zacr/cp312-macosx_x86_64/build/venv/bin/python
  version: '3.12'
```

**Comment by ev-br** [comment]
`UnivariateSpline._from_tck`, as the leading underscore indicates, is an implementation detail, private method, and is not meant to be directly callable by users.
There are no guarantees on its behavior or even its very existence.
Therefore, not a bug, and not something we are going to fix.

If you need a spline from knots and coefficients, just construct one directly: `scipy.interpolate.BSpline(t, c, k)`. If you mix it with `UnivariateSpline`, check the result of `get_knots()` --- IIRC it chops off boundary knots. Or, better, use `t, c, k = splrep(x, y, s=...)` and wrap the result into a `BSpline`.

I wonder if there's some resource which suggests this @DelisleLab? 
This is at least the second occurence of this confusion: https://github.com/scipy/scipy/issues/17092

**Comment by nomad-vagabond** [comment]
@ev-br I believe @DelisleLab followed the example from my article
http://vadym-pasko.com/blog/2015/03/06/spline-approx-scipy.html

The article was created before you introduced BSpline class, so by that time I considered `_from_tck` as the only option to recreate splines from the given knot vector, coefficients and degree.

In fact, I still use this method to recreate parametric spline in the client library for [SplineCloud](https://splinecloud.com)

I would appreciate your advice and supervision on how it can be improved.
You can find the source code here: https://github.com/nomad-vagabond/splinecloud-scipy

**Comment by ev-br** [comment]
This is great @nomad-vagabond, thanks for sharing!
Indeed, one motivations for the BSpline abstraction was provide a sane public API to avoid `_from_tck` :-). My suggestions are sketched in https://gist.github.com/ev-br/c76ff4459e1b4b5e4aecc17fe5062d91. Basically, if you want to stay with FITPACK, you can use the functional interface (`splrep`, `splprep`, `splev`). I'd recommend using `make_interp_spline` and `BSpline` for interpolation though, also shown in the gist above.

For your example 2, spline fitting, one can also use `splrep/splprep`. That said, take a look at https://gist.github.com/ev-br/18956b1d638e950e6b987eeb4beb0b2c
`generate_knots` and `make_splrep` are from https://github.com/scipy/scipy/pull/19970, a user review would be most appreciated.
