### ISSUE TITLE
BUG: numerical differences in stats module on osx build (1.12.0)

### ISSUE THREAD

**Issue by bmcfee** [scipy/scipy#20110]
### Describe your issue.

Apologies in advance for the somewhat vague nature of this issue, but I'm migrating a discussion from the discord server over to here in hopes of better diagnosing the problem.

The problem is surfacing in the librosa test suite after updating to scipy 1.12.0 on the osx platform (conda packages).  The code that triggers the issue is rather involved (pyin pitch estimation), but it depends on scipy in only two places: stats.beta.cdf and stats.boltzmann.pmf.

The behavior that I'm seeing is that tests that passed with scipy 1.11.4 now fail in 1.12.0, but only on the osx platform.  The linux and windows builds seem unaffected.  See https://github.com/librosa/librosa/pull/1808 for the PR where this showed up and I attempted to diagnose the issue.  

My best guess at this point is that the divergence is in boltzmann.pmf, but after looking at the compare between 1.11.4 and 1.12.0, I don't see any obvious changes that would affect this function.  Is it possible that something is different in the compiler settings causing trouble?

### Reproducing Code Example

I'm unable to fully debug this and provide a minimal code example because I don't have access to an osx machine.  I'm hoping that a scipy dev familiar with the relevant parts of the code can help to pin this down.  (So far I've been trying to diagnose this through trial and error on github actions, but this is a pretty slow and painful process.)

The code I'm working with has two dependencies on scipy, one here:

https://github.com/librosa/librosa/blob/8dae20c66353190749486abf6b332d93c4ab2b46/librosa/core/pitch.py#L815-L817

I believe this one is not the problem; I've asked a colleague with a mac to verify that the output from beta.pmf is numerically equivalent across versions.

The second dependency is here:

https://github.com/librosa/librosa/blob/8dae20c66353190749486abf6b332d93c4ab2b46/librosa/core/pitch.py#L903-L905

which is called in a loop with varying inputs, and I have not yet been able to verify numerical equivalence.

### Error message

There is no error message, but results are not equivalent across versions or platforms.

### SciPy/NumPy/Python version and system information

This is coming up in github actions, but here's the relevant portions of my conda info:

```
python                    3.12.2          h9f0c242_0_cpython    conda-forge
scipy                     1.12.0          py312h8adb940_2    conda-forge
numpy                     1.26.4          py312he3a82b2_0    conda-forge
```

**Comment by mdhaber** [comment]
When you determine which function is causing the problem and a numerical example to demonstrate it, please let us know. As you note, there have been no changes to these functions in recent versions, and I don't see any changes to the distribute infrastructure that would cause them either. Do you know that magnitude of the differences, or just that something changed (e.g. by 1 ULP)?

**Comment by bmcfee** [comment]
> When you determine which function is causing the problem and a numerical example to demonstrate it, please let us know. As you note, there have been no changes to these functions in recent versions, and I don't see any changes to the distribute infrastructure that would cause them either

Sure, I'll keep trying at it.  But as I noted above, without direct access to a suitable machine, it's going to be pretty difficult.  (Note: I was hesitant to post this issue initially, as I don't have all the information yet, but was prompted to do so after a quick discussion on the scipy community discord.  I understand that vague issues like this are annoying to deal with!)

If there are no changes to the build flags that might cause this, that's good information to have.  Just to be certain, I did just re-run the 1.11.4 and 1.12.0 builds again (still producing divergent behavior), and there are a couple of differences in the build reported by `show_config()`.  (1.11.4 doesn't list the compiler flags, of course, but this might be enough to go on.)  The differences I'm seeing are:

- 1.11.4: cython 0.29.36, pythran 0.14.0
- 1.12.0: cython 3.0.7, pythran 0.15.0

(All else, including blas / lapack etc are identical in the two environments.)

I don't understand enough about how the stats module / class hierarchy is structured to figure this out myself, but is it possible that these differences would result in different generated code?  Or am I just barking up the wrong tree here?

**Comment by ev-br** [comment]
Could you debug print the values of parameters which come into the script.stats functions? I suspect it'd easier to someone with access to a suitable local machine to check/verify/bisect the issue.

**Comment by bmcfee** [comment]
> Could you debug print the values of parameters which come into the script.stats functions? I suspect it'd easier to someone with access to a suitable local machine to check/verify/bisect the issue.

That's going to be a little tricky, as this is occurring in a tight loop over hundreds of steps, each one producing a rather large vector of values to evaluate the pmf at.  (For a bit of added context, the test that I'm seeing fail is a regression test between a numpy vectorized call of a somewhat complex function, and independent calls of the function across slices of the input array.  The inputs are identical in both cases and everything is deterministic and seeded, so there's no reason this should ever fail outside of numerical / floating point weirdness.)

That said, I think I might be onto a lead with this.  The change in pythran version between the two builds is documented here: https://pythran.readthedocs.io/en/latest/Changelog.html , and mentions bumping the xsimd version to revision https://github.com/xtensor-stack/xsimd/commit/a48ab430d4b84ecd5449180ee1c6d2eed67c4191 .  Digging into that commit, there are changes to the exp10 and exp10f implementation that explicitly affect the macos-arm platform.  This might explain why I'm only seeing differences on that platform.  Changes in SIMD stuff does seem relevant to the failure case I'm seeing though, so this might be worth investigating further.

**Comment by andyfaff** [comment]
>  everything is deterministic and seeded

It may be relevant that random numbers are being used in the process (this wasn't mentioned earlier). Bit level reproducibility for random number streams for numpy follows these policies, [NEP19](https://numpy.org/neps/nep-0019-rng-policy.html) and [this](https://numpy.org/doc/stable/reference/random/compatibility.html).

If the tests are designed to obtain bit-level reproducibility, or with tolerances that are set too tightly, then fails can occur if they depend on random number generation.

**Comment by bmcfee** [comment]
Sorry, to clarify: this particular test and code path does not use rng. I was referring to the entire test suite with that remark.

**Comment by rgommers** [comment]
> but it depends on scipy in only two places: stats.beta.cdf and stats.boltzmann.pmf.

If the choice is between these two, that is easy: `boltzmann.pdf` is pure Python, while `beta.cdf` is going to hit the `beta` function from Boost, which we've had lots of issues with before (main issue was gh-18302), in particular on on macOS. The relevant distribution method method is `_pdf`, which looks like:
```python
class beta_gen():
    def _pdf(self, x, a, b):
        with np.errstate(over='ignore'):
            return _boost._beta_pdf(x, a, b)
```

There were fixes upstream which we haven't all included yet I believe, and there is still a known issue with it, as indicated by @mdhaber's comment from two weeks ago: https://github.com/scipy/scipy/pull/19174#issuecomment-1930094648.

I'll have a go at updating to latest Boost.Math for 1.13.0 so you can try if that fixes the issue @bmcfee. Other than that, this isn't really actionable unless a concrete example of `beta.cdf` that is tripping you up here is identified.

**Comment by bmcfee** [comment]
Thanks @rgommers - that's helpful to know.  We have one call to beta and hundreds of calls to boltzmann, so this task just got easier if we can rule out boltzmann.

I've been trying to get a minimal example going via github actions in a dedicated repo, regression-testing against a known output (linux build, 1.12.0).  So far, I'm seeing bitwise equivalence across platforms and versions for beta.cdf output (with the same inputs as in the test that triggered this issue originally), and this leaves me pretty puzzled.

I'm also drilling a bit further down into the test case that started this thread, and as near as I can tell, the stats calls are indeed producing the expected outputs.  The downstream probabilities do match as expected; but the computation that comes after is diverging.  The downstream computation is essentially viterbi decoding written in numpy / numba, but these versions are identical between working and failing environments, hence my confusion.

So it's entirely possible that this has all been a bit of a red herring, but it still doesn't explain why only changing from 1.11.4 to 1.12.0 would trigger this kind of failure.  Unless there's some background interaction between other dependencies that I'm not seeing?

At any rate, thanks for helping me noodle this through.  I think it's probably fine to close this out, but if there are any suggestions of what else might be causing trouble I'd appreciate it.

**Comment by rgommers** [comment]
> So it's entirely possible that this has all been a bit of a red herring, but it still doesn't explain why only changing from 1.11.4 to 1.12.0 would trigger this kind of failure. Unless there's some background interaction between other dependencies that I'm not seeing?

My guess is the version of Clang, XCode SDK, or macOS image in the SciPy 1.12.0 conda-forge build compared to the 1.11.4 build.

**Comment by bmcfee** [comment]
Ok, I think I've got this sorted out now.  It appears that the scipy stats functions were indeed a red herring, and the divergence is actually due to a different openblas versions.  Sorry for the confusion here, and thanks again for the patience and help in diagnosing the problem!

For the record, the issue was that the 1.11.4 build used libopenblas 0.3.25, while 1.12.0 used 0.3.26.  If I pin the environment to 0.3.25 and use scipy 1.12.0, everything works as expected.   I missed this difference before when comparing the `conda list` dumps of the environments because the two packages actually had identical build numbers, so I didn't bother to check the release numbers. :facepalm: 

```diff
< libopenblas               0.3.26          openmp_hfef2a42_0    conda-forge
---
> libopenblas               0.3.25          openmp_hfef2a42_0    conda-forge
```

I'll close this out now.  There's probably something amiss upstream in openblas, but that's going to be a whole other can of worms.  Thanks again!

**Comment by rgommers** [comment]
Ah yes, IIRC there is an issue for test failures with 0.3.26  somewhere, just not sure where (can't find it on the openblas, numpy or scipy feedstocks).

Glad you found it!
