### ISSUE TITLE
BUG: rv_sample _ppf method is not efficient

### ISSUE THREAD

**Issue by LeTristanB** [scipy/scipy#20117]
### Describe your issue.

The implementation of the `_ppf` method on the `rv_sample` class is not as efficient as it could be. This problem becomes apparent when using it with large volume of data. 

I think these [two lines](https://github.com/scipy/scipy/blame/main/scipy/stats/_distn_infrastructure.py#L3979-L3980) are the culprit and could be replaced with the faster and less memory hungry `np.searchsorted(self.qvals, q)`

### Reproducing Code Example

```python
# run in a jupyther notebook to use the handy %timeit magic function
# link to collab notebook with this code: https://colab.research.google.com/drive/1p84VmT-ZIjdYVWJuc66ivzsDbUX9RaFW?usp=sharing

import numpy as np
from scipy.stats import rv_discrete

my_dist = rv_discrete(values=(range(10000), [1/10000]*10000)) #this returns an rv_sample instance
quantiles = np.random.rand(500000)
%timeit my_dist.ppf(quantiles)
# 2.55 s ± 125 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

#Prototype fix
def _ppf(self, q):
  indx = np.searchsorted(self.qvals, q)
  return self.xk[indx]

my_dist.ppf = _ppf.__get__(my_dist)
%timeit my_dist.ppf(quantiles)
# 73.1 ms ± 6.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

### Error message

```shell
No error message, the current output is accurate and works.
```

### SciPy/NumPy/Python version and system information

```shell
1.11.4 1.25.2 sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-c6c8ru56/overlay/lib/python3.10/site-packages/pythran
    version: 0.14.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: true
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp310-cp310/bin/python
  version: '3.10'
```

**Comment by lucascolley** [comment]
PR welcome @LeTristanB !

**Comment by tupui** [comment]
> PR welcome @LeTristanB !

I am not sure though 😅 To be honest the stats team has a lot to do with the new infrastructure and all such issues would basically be irrelevant once we are there. So I don't think we (stats team) would really want to invest must time there especially if as Tirth pointed out, there is currently a better way in SciPy to do that.

**Comment by lucascolley** [comment]
Ah, I misinterpreted the 'something similar' in Tirth's reply as similar to the suggested fix rather than similar to the functionality.

Maybe a docs update to point to the faster code then?

**Comment by LeTristanB** [comment]
Thanks for all the responses :) 

>with the new infrastructure and all such issues would basically be irrelevant

Makes sense 👍. I was going to try making a Pull Request. I tried make one last weekend, but haven't been able to get the required environment working on my windows machine. Since anyway changing this code is pointless, I'll stop here. Do you want to close this issue as not planned?

**Comment by tirthasheshpatel** [comment]
> `DiscreteGuideTable` suggested by Tirth is very efficient, but is not a replacement to the `rv_samle` class. `DiscreteGuideTable` lacks a lot of the methods you'd find on `rv_samle`, like `.mean()`.

The `rv_sample` classes are only inefficient for random variate generation. You can use the `scipy.stats.sampling` methods in conjunction to the rv classes to get the desired behavior:

```python
class my_dist_gen(rv_discrete):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.rng = DiscreteGuideTable([1/10000] * 10000)

  def _get_support(self):
    return 0, 10000

  def _pmf(self, x):
    res = np.full_like(x, fill_value=1/10000, dtype='float64')
    return res

  def _ppf(self, x):
    return self.rng.ppf(x)

  def _rvs(self, size, random_state=None):
    if isinstance(size, tuple) and not size:
      size = None
    return self.rng.rvs(size, random_state=random_state)

my_dist = my_dist_gen(name='my_dist')
```
