### ISSUE TITLE
scipy-openblas issues on macOS

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#20139]
### Describe your issue.

I'm having issues trying to get scipy-openblas to work properly for local development on macOS (as a prelude to using it in a CI entry).

Local usage
------------
Sonoma 14.2.1, M3
If I use the latest version of scipy-openblas (scipy_openblas32-0.3.26.0.4-py3-none-macosx_11_0_arm64.whl) I get a whole load of `ImportError: dlopen(/Users/andrew/Documents/Andy/programming/scipy/build-install/lib/python3.11/site-packages/scipy/linalg/_flapack.cpython-311-darwin.so, 0x0002)` errors, and if I run `otool -L` on the dylib the openblas library is not listed. Using `nm -a` on the dylib indicates that a lot of the BLAS symbols are unresolved.

If I drop back to `scipy-openblas32<=0.3.23.293.2` then the build works, but there are a couple of test fails

> FAILED scipy/special/tests/test_cdflib.py::test_nctdtr_gh19896 - AssertionError: 
FAILED scipy/special/tests/test_cdflib.py::test_nctdtrinc_gh19896 - AssertionError: 

If I repeat the tests on my home machine I get similar behaviour, but a lot more test fails. This might be due to slightly different compiler versions (I have gfortran 13.2.0 and clang-1500.1.0.2.5 on my M3)

CI usage
---------
If I do a similar process (using the pinned scipy-openblas wheel, see [here](https://github.com/andyfaff/scipy/pull/62/files) for run configuration) on a GHA CI using a `macos-14` image the build completes. However the tests reveal segfaults, e.g. [here](https://github.com/andyfaff/scipy/actions/runs/8003061306/job/21857572355#step:4:7668). These segfaults appear to come from tests involving linalg (i.e. OpenBLAS). The specification for the Github actions M1 runners are [here](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md).

I'm wondering what the situation is for scipy-openblas w.r.t using it in CI? A pinned version seems to be fine for Linux.

@mattip

### Reproducing Code Example

```python
https://github.com/andyfaff/scipy/pull/62/files
```

### Error message

```shell
N/A
```

### SciPy/NumPy/Python version and system information

```shell
numpy 1.26.4
python 3.11
```

**Comment by mattip** [comment]
The wheel requires a `scipy_` prefix on the OpenBLAS symbols, and I think some of the code does not use the proper macro to mangle the blas functions. xref #20074 (a different trial of the scipy-openblas wheels) and #19855 (which will use the proper macros).

**Comment by rgommers** [comment]
This should be fixed now that we have `scipy_` symbol prefixes after gh-19855. Can we close this @andyfaff?

**Comment by andyfaff** [comment]
`python dev.py build --with-scipy-openblas && python dev.py test` completes successfully with HEAD and `scipy-openblas32==0.3.28.0.2`. Thanks for the fix and ping.
