### ISSUE TITLE
DOC: Inconsistent naming convention between docs and error messages within scipy.optimize.curve_fit

### ISSUE THREAD

**Issue by sgrieve** [scipy/scipy#20155]
### Issue with current documentation:

When working with `scipy.optimize.curve_fit` I had a typo in my bounds, which led to the following ValueError being raised:

```
ValueError: `x0` is infeasible.
```

Referring back to the documentation, the parameter `x0` is not mentioned, with the terminology used throughout the documentation page being `p0` instead: [Documentation](https://scipy.github.io/devdocs/reference/generated/scipy.optimize.curve_fit.html#scipy.optimize.curve_fit)

Looking through the source code, it seems that `p0` is the preferred terminology within the `curve_fit` method, but `x0` is used in many other places in the code. As far as I can see, the message `x0 is infeasible.` only appears here: https://github.com/scipy/scipy/blob/9c4f6a91c5eb3e797d8b591e502d746128dc1ce2/scipy/optimize/_lsq/least_squares.py#L820

### Idea or request for content:

Assuming my understanding of the code is correct, adding a note to the documentation of `curve_fit` that informs a user that `x0` and `p0` are used interchangeably across the codebase would make the user experience a bit more streamlined.

This could be achieved by adding 

> Note that `x0` may be used interchangeably with `p0`

to line 611 of https://github.com/scipy/scipy/blob/main/scipy/optimize/_minpack_py.py

**Comment by KonstantineTzaferis** [comment]
Can I ask If I can work on this?
It seems like a good chance for a contribution for a newcomer like me.

**Comment by sgrieve** [comment]
Yes, feel free! I probably wouldn't have time to work on a PR for a few months, so if you want to take it on that's great 🚀

**Comment by AtsushiSakai** [comment]
The reason for this confusion is that `[curve_fit](https://scipy.github.io/devdocs/reference/generated/scipy.optimize.curve_fit.html#scipy.optimize.curve_fit)` uses the variable name `p0` for the initial guess, while the functions `least_sq` and `[least_squares](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.least_squares.html)`, which are read internally by `curve_fit`, use the variable `x0` for the initial guess. 
While updating the documentation might be a good idea, I personally think the message "x0 is infeasible" is not very clear. Changing it to "Initial guess of the parameter is infeasible" would make it more understandable, even if it appears in both functions. What do you think? @sgrieve
