### ISSUE TITLE
BUG: special: `factorial2(-1)` equal to `1`, not `0`

### ISSUE THREAD

**Issue by gh85** [scipy/scipy#20167]
### Describe your issue.

Calculate n!!. If n < 0, the return value is 0.
but

### Reproducing Code Example

```python
from scipy.special import factorial2
factorial2(-1)==1
```

### Error message

```shell
none
```

### SciPy/NumPy/Python version and system information

```shell
1.11.1 1.25.1 sys.version_info(major=3, minor=11, micro=7, releaselevel='final', serial=0)
```

**Comment by lucascolley** [comment]
Hi @gh85 , can you reproduce with SciPy version 1.12.0?

**Comment by lucascolley** [comment]
I assumed that @gh85 was saying that `factorial2(-1)==1` returns `True`, while the documentation says that

> If n < 0, the return value is 0

I just checked on `main` and it indeed returns `0`, so if that was the case then it is no longer.

**Comment by h-vetinari** [comment]
Already on 1.11 this returns 0 for `n<0`:
https://github.com/scipy/scipy/blob/1d3a067c2ccd0a6efddeb3194163aa9a3879d26e/scipy/special/_basic.py#L2992-L2993
