### ISSUE TITLE
MAINT/BENCH: Unknown environment type 'mamba'

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#20162]
`> python dev.py bench ...`

```
I will now ask you some questions about this machine to identify it in the benchmarks.

<snip>

· Unknown environment type 'mamba'
· Discovering benchmarks
· Running 1 total benchmarks (1 commits * 1 environments * 1 benchmarks)

<snip>
```

Obviously not really a problem but maybe we can get rid of the warning.

**Comment by rgommers** [comment]
Last I checked, not setting `environment` here wasn't making `asv` happy either:

https://github.com/scipy/scipy/blob/e630ecd9cff5c1b5ba0e4e88de17068bfbaa4f51/benchmarks/asv.conf.json#L55-L61

Not sure if behavior of this setting was improved in `asv` recently or not. @HaoZeke maybe you know off the top of your head?

**Comment by HaoZeke** [comment]
The warning most likely because @lucascolley might not have `libmambapy` installed (a requirement for the `mamba` backend). However the warning is a bit verbose now (is emitted irrespective of if the user actually asked for the `mamba` backend) so that will be fixed in an upcoming bugfix release.

**Comment by lucascolley** [comment]
I still see the warning after

```
mamba install libmambapy
git clean -xdf
python dev.py bench
```

**Comment by HaoZeke** [comment]
> I still see the warning after
> 
> ```
> mamba install libmambapy
> git clean -xdf
> python dev.py bench
> ```

Interesting, could you open an issue on the ASV repo? Also are you on version 0.6.3 (the latest)? We should continue this on the ASV repo. I'll give it a shot too.

**Comment by lucascolley** [comment]
Resolved by installing `conda-build`
