### ISSUE TITLE
Test failures due to `asarray(..., copy=False)` semantics change in numpy main

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#20170]
gh-19997 anticipated this change and fixed most things, however that fix was incomplete (or the NumPy implementation changed after it landed). What is left is now visible in wheel builds ([example log](https://github.com/scipy/scipy/actions/runs/8115464164/job/22183392354)):
```
   ERROR io/_harwell_boeing/tests/test_hb.py - ValueError: Unable to avoid copy ...
  ERROR linalg/tests/test_sketches.py - ValueError: Unable to avoid copy while ...
  ERROR sparse/csgraph/tests/test_shortest_path.py - ValueError: Unable to avoi...
  ERROR sparse/linalg/_isolve/tests/test_iterative.py - ValueError: Unable to a...
```

We need to fix these and then retrigger wheel builds to fix the current nightlies, which are not usable because they were not built against numpy main (see https://github.com/numpy/numpy/issues/25907#issuecomment-1973484113).

Cc @mtsokol for visibility.

**Comment by matthewfeickert** [comment]
@rgommers @mtsokol @tupui As a temporary fix until this Issue get resolved, you could also download the wheels manually from the [nightly build](https://github.com/scipy/scipy/actions/workflows/wheels.yml?query=branch%3Amain+event%3Aschedule) from [yesterday's (2024-02-29) 03:13 CST build](https://github.com/scipy/scipy/actions/runs/8093622449) and then reupload those manually to https://anaconda.org/scientific-python-nightly-wheels/scipy/files. Then once 

If this is a good idea in your mind but are busy enough with trying to fix this I can do this, like I did for the NumPy wheels earlier today.

**Comment by matthewfeickert** [comment]
Given feedback from @stefanv I've uploaded the 2024-02-29 wheels from GitHub Actions, but the `aarch64` and `arm64` wheels are built elsewhere and so still need to be uploaded. If someone can direct me to where those are built I can see if I can still get the 2024-02-29 artifacts and upload them.

**Comment by andyfaff** [comment]
https://cirrus-ci.com/build/6417540230938624

**Comment by matthewfeickert** [comment]
> https://cirrus-ci.com/build/6417540230938624

@andyfaff My understanding is that is the build that was built against the wrong numpy (https://github.com/numpy/numpy/issues/25907#issuecomment-1973484113).

**Comment by matthewfeickert** [comment]
Ah excellent! Thanks very much for pointing this out @andyfaff! I had missed that the `2024-03-01 00:02` was _UTC_, and so the timing of that build was before the `2024-03-01 02:05 UTC` `scientific-python/upload-nightly-action` removal job (obvious in text, yes, but that's me writing it out knowing both times now) that removed the numpy wheels and broke thing. So my apologies, as I overwrote those wheels for no reason. :grimacing:

I've gone ahead and manually downloaded the `2024-03-01 00:02 UTC` wheels and uploaded them to overwrite things again, and so the wheels `aarch64` and `arm64` wheels that were there at the start of 2024-03-01 are now back up and we're back to where we started. :+1: 

<details>
<summary>Example on Apple silicon of all good post upload:</summary>

```console
% micromamba env create --name scipy-numpy-version-check --yes python=3.12 && micromamba activate scipy-numpy-version-check
% python -m pip install --pre --upgrade --index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple scipy
Looking in indexes: https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
Collecting scipy
  Downloading https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/scipy/1.13.0.dev0/scipy-1.13.0.dev0-cp312-cp312-macosx_12_0_arm64.whl (31.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.2/31.2 MB 33.5 MB/s eta 0:00:00
WARNING: Cache entry deserialization failed, entry ignored
Collecting numpy>=1.22.4 (from scipy)
  Downloading https://pypi.anaconda.org/scientific-python-nightly-wheels/simple/numpy/2.0.0.dev0/numpy-2.0.0.dev0-cp312-cp312-macosx_14_0_arm64.whl (5.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 35.0 MB/s eta 0:00:00
Installing collected packages: numpy, scipy
Successfully installed numpy-2.0.0.dev0 scipy-1.13.0.dev0
% python -c "import scipy.special"  # no 'A module that was compiled using NumPy 1.x...', yay!
```

</details>

I will stop touching the wheels now unless I get explicit requests from a SciPy dev to help with something. But it seems that everything should be good in the interim while the wheel building workflow gets fixed. :+1: 

> The macos_arm64 nightlies are specified to be built against [numpy>=2.0.0.dev0](https://github.com/scipy/scipy/blob/e630ecd9cff5c1b5ba0e4e88de17068bfbaa4f51/ci/cirrus_wheels.yml#L71), and have been for a while.

Also, thanks @andyfaff, for securing that in PR https://github.com/scipy/scipy/pull/19217, as that's nice to know the `aarch64` and `arm64` wheel builds are already guarded! :rocket:

**Comment by rgommers** [comment]
Fixed in `main`; wheels are rebuilding in https://github.com/scipy/scipy/actions/runs/8125502787 now.

Thanks @matthewfeickert and @andyfaff for dealing with the missing wheels.

**Comment by rgommers** [comment]
New wheels for aarch64/arm64 just finished building too, so everything should be up-to-date. It'll work until the next breaking change lands in NumPy, and we'll have to go through this once more (probably within the next 48 hours).
