### ISSUE TITLE
BUG: linalg: sqrtm does not perform correctly

### ISSUE THREAD

**Issue by Luciennnnnnn** [scipy/scipy#20178]
### Describe your issue.

I guess the root cause of problem is come from this [PR](https://github.com/lucascolley/scipy/commit/5e53a6bf4b8f3f0a6ab0e8ff2e493d13e9a4ab5f), see this [issue](https://github.com/GaParmar/clean-fid/issues/53).

Personally, I also encounter similar numeral problem when I calculate FID between two folders of images. It is fine when I use scipy 1.10.1, and the resulting matric contain very large imaginary part when I use scipy 1.12.0.

### Reproducing Code Example

```python
a
```

### Error message

```shell
a
```

### SciPy/NumPy/Python version and system information

```shell
a
```

**Comment by lucascolley** [comment]
duplicate of gh-19415 I think

**Comment by Luciennnnnnn** [comment]
@j-bowhay it's hard for me to provide a minimal example, since my use cases includes a lot of things(calculating FID). Yeah, I think this is same as [gh-19415](https://github.com/scipy/scipy/issues/19415), as @lucascolley mentioned.

**Comment by j-bowhay** [comment]
Ok lets close this in favour of https://github.com/scipy/scipy/issues/19415
