### ISSUE TITLE
BUG: ttest_rel and other tests return nan p-value when denominator is 0 but numerator is also 0, rather than 1 or 0.5 (as appropriate)

### ISSUE THREAD

**Issue by sam-data-guy-iam** [scipy/scipy#20179]
### Describe your issue.

scipy.stats.ttest_rel conducts a paired t-test on the differences between two samples of observations.  Letting d_i = a_i - b_i be the pairwise observation differences, the test statistic involves dividing the mean of the d_i by their variance (the variability in the differences).  There are two cases where the denominator variance is 0:
1) the average difference is also 0 (occurs when a = b for all observations)
2) the average difference is not 0 (e.g., b_i = a_i + 2), so average difference is 2
In the first case, ttest_rel reports a p-value of nan since the statistic is 0/0, while in the second case the p-value is 0.0 or 1.0 (depending on the alternative hypothesis).  

In case 1, the two samples are identical, and so it seems to me that the statistic should also be 0, rather than nan, and the p-value should be 1.0 if two-sided and 0.5 if either less/greater, indicating that the results are not significant at all.  Note: the same issue may exist for some other tests conducted in the same way, but I haven't checked.

### Reproducing Code Example

```python
from scipy.stats import ttest_rel, ttest_ind
import numpy as np

a = np.random.uniform(size=50)
# b1 is the same as a, so average difference will be 0 and also the variance will be 0
b1 = a
print(ttest_rel(a, b1))
print(ttest_rel(a, b1, alternative='less'))
# b2 is a + a constant, so average difference will be !=0 and but the variance will be 0
b2 = a + 5
print(ttest_rel(a, b2))
print(ttest_rel(a, b2, alternative='less'))
print(ttest_rel(a, b2, alternative='greater'))

# also, perhaps this is misleading behavior
a1 = np.repeat(1.0, 50)
b3 = a1
# returns nan since there is 0 variance in both samples, even though the mean differences are also 0
print(ttest_ind(a1, b3)) 


# TtestResult(statistic=nan, pvalue=nan, df=49)
# TtestResult(statistic=nan, pvalue=nan, df=49)
# TtestResult(statistic=-inf, pvalue=0.0, df=49)
# TtestResult(statistic=-inf, pvalue=0.0, df=49)
# TtestResult(statistic=-inf, pvalue=1.0, df=49)
TtestResult(statistic=nan, pvalue=nan, df=98.0)
```

### Error message

```shell
no error message was printed
```

### SciPy/NumPy/Python version and system information

```shell
1.12.0 1.25.2 sys.version_info(major=3, minor=11, micro=4, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: c:/opt/64/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: c:/opt/64/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.1
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  pythran:
    include directory: C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-d02me32y\overlay\Lib\site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
Python Information:
  path: C:\Users\runneradmin\AppData\Local\Temp\cibw-run-aug4qibh\cp311-win_amd64\build\venv\Scripts\python.exe
  version: '3.11'
```

**Comment by josef-pkt** [comment]
see #235 when 0/0 case was changed to returning nan.

There are many possible sequences that can lead to 0/0 with arbitrary limits. (Does standard error or difference go faster to zero, or at the same rate?)
Ad hoc arguments just depend on whatever limiting case the discussants have in mind, without agreement.

We never found a reference that would justify a non-nan value for it.

**Comment by mdhaber** [comment]
> Does standard error or difference go faster to zero, or at the same rate?

That was my guess. I saw something similar with skewness of a "constant" sample, I think.

And the result is undefined in the usual references (Mathematica and R).

**Comment by sam-data-guy-iam** [comment]
Ok sorry for wasting your time on this, as you said I see R gives the same answer.  I understand the math reasoning but it seems odd to me that in a given case I can't say that two exactly equal pairwise observations are not significantly different by the p-value.  I suppose the effect sizes should also be NaN but I would need some way to tell the user this so they don't "mistakenly" understand that no conclusion can be drawn from the data.
