### ISSUE TITLE
BUG: Raising scipy.spatial.transform.Rotation to power of 0 adds dimension to underlying numpy.array

### ISSUE THREAD

**Issue by allanerlang** [scipy/scipy#20188]
### Describe your issue.

If I define a scipy.spatial.transform.Rotation and return it as e.g. a quaternion, I get it as a numpy.array of shape (4,). But if I raise it to the zeroth power and return as a quaternion again, I now receive a numpy.array of shape (1,4). The same thing happens for all `as_*()` member functions. 
Is this intended, and if so, why?

### Reproducing Code Example

```python
r = Rotation.from_quat([0, 0, 0, 1])
r.as_quat().shape
(4,)
(r**0).as_quat().shape
(1,4)
```

### Error message

```shell
Not any
```

### SciPy/NumPy/Python version and system information

```shell
1.12.0 1.26.2 sys.version_info(major=3, minor=12, micro=0, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.1
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-tfqmvy7q/overlay/lib/python3.12/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp312-cp312/bin/python
  version: '3.12'
```

**Comment by j-bowhay** [comment]
@scottshambaugh would you be interested in having a look at this?

**Comment by allanerlang** [comment]
It seems to be [this line](https://github.com/scipy/scipy/blob/2447a8d4ddb1d0a4da620fa75592c0a069b1dacd/scipy/spatial/transform/_rotation.pyx#L2644) that causes the change in dimension: 
`if n == 0:
            return Rotation.identity(len(self._quat))`
Changing the code to something along the lines of
`if n == 0:
            return Rotation.identity(0 if self._single else len(self._quat))`
should do the trick, but there is probably a more elegant solution.

**Comment by scottshambaugh** [comment]
Hey @allanerlang good catch! And your solution is pretty much perfect, except that `None` is the arg to pass in instead of `0` to get a single identity rotation. PR is open to fix this and test this category of error.
