### ISSUE TITLE
deprecation warnings for Node.js 16 on GHA wheel build jobs

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#20180]
Wheel build jobs on GitHub Actions are showing the following warning. It'd be great to address those by upgrading the actions:

_**Build wheel for cp39-manylinux x86_64**
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/upload-artifact@v3, conda-incubator/setup-miniconda@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/._

**Comment by andyfaff** [comment]
The upload)download artefact isn't the most straightforward of things and took a little fiddling to get right. Could we do it after branching?

**Comment by rgommers** [comment]
Sure, no hurry at all. Would just be nice to do it before the warning turns into an error.

**Comment by charris** [comment]
Dependabot kept GHA up to date for numpy.
