### ISSUE TITLE
Audit usage of cython memoryviews, add `const` to allow readonly arrays

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#20196]
Starting from Cython >=3.0.8, readonly fused typed memoryviews are finally allowed. Meaning we can add `const`  qualifiers to memoryviews so that readonly arrays do not get rejected. We should audit our usage of memoryviews with fused dtypes and sprinkle `const` pretty much everywhere.
https://github.com/scipy/scipy/pull/20195 gives a representative example.

EDIT: a good way to go about this is one PR per submodule, using a grep like in https://github.com/scipy/scipy/issues/20196#issuecomment-1983133092 to identify files to audit.

- [x] `_lib` (no usage)
- [x] `cluster` (gh-20085)
- [x] `fftpack` (no usage)
- [x] `linalg` (gh-20837)
- [x] `integrate` (no usage)
- [x] `interpolate` (gh-20250, gh-20872)
- [x] `io` (no usage)
- [x] `ndimage` (no usage)
- [x] `optimize` (gh-20265)
- [x] `signal` (gh-20887)
- [x] `sparse` (gh-20873)
- [x] `spatial` (gh-20874)
- [x] `special` (no usage)
- [x] `stats` (gh-20891)

**Comment by lucascolley** [comment]
gh-20085 contains what's needed in `cluster` for the test suite to pass (having JAX support is a handy way to check read-only arrays)

**Comment by Kai-Striega** [comment]
@ev-br I can help out with this, but I'm not quite sure where to start. Any recommended places to look at?

**Comment by ev-br** [comment]
That would be great @Kai-Striega !
I would just grep pyx files by subpackage, along the lines of `$ grep def scipy/optimize  -rn` to list all cython function declarations. For each of those, if it has memoryviews, add `const` to all which are not outputs.

IOW,  `def func(const double[::1] x, double[::1] out)` means that `x` can be a regular or a readonly array, and `out` cannot be readonly.

**Comment by Kai-Striega** [comment]
Great. I'll try to audit what needs to be done tonight/this weekend

**Comment by Kai-Striega** [comment]
@ev-br I've got a question for you: I tried to change the argument ``a`` on this line [line](https://github.com/scipy/scipy/blob/9c98ee762a95cf46d8f91f1c1a5547701538d286/scipy/linalg/_cythonized_array_utils.pyx#L19) to be const-qualified. However I get the following warnings:

```
scipy/linalg/_cythonized_array_utils.cpython-311-darwin.so.p/_cythonized_array_utils.c:21402:79: warning: passing 'const float *' to parameter of type '__pyx_t_5scipy_6linalg_13cython_lapack_s *' (aka 'float *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
    __pyx_f_5scipy_6linalg_13cython_lapack_sgetrf((&__pyx_v_n), (&__pyx_v_n), (&(*((float const  *) ( /* dim=1 */ ((char *) (((float const  *) ( /* dim=0 */ (__pyx_v_a.data + __pyx_t_3 * __pyx_v_a.strides[0]) )) + __pyx_t_4)) )))), (&__pyx_v_n), (&(__pyx_v_piv[0])), (&__pyx_v_info));
                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
scipy/linalg/_cythonized_array_utils.cpython-311-darwin.so.p/_cythonized_array_utils.c:21855:79: warning: passing 'const double *' to parameter of type '__pyx_t_5scipy_6linalg_13cython_lapack_d *' (aka 'double *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
    __pyx_f_5scipy_6linalg_13cython_lapack_dgetrf((&__pyx_v_n), (&__pyx_v_n), (&(*((double const  *) ( /* dim=1 */ ((char *) (((double const  *) ( /* dim=0 */ (__pyx_v_a.data + __pyx_t_3 * __pyx_v_a.strides[0]) )) + __pyx_t_4)) )))), (&__pyx_v_n), (&(__pyx_v_piv[0])), (&__pyx_v_info));
                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
scipy/linalg/_cythonized_array_utils.cpython-311-darwin.so.p/_cythonized_array_utils.c:22310:79: warning: passing 'const __pyx_t_float_complex *' to parameter of type '__pyx_t_float_complex *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
    __pyx_f_5scipy_6linalg_13cython_lapack_cgetrf((&__pyx_v_n), (&__pyx_v_n), (&(*((__pyx_t_float_complex const  *) ( /* dim=1 */ ((char *) (((__pyx_t_float_complex const  *) ( /* dim=0 */ (__pyx_v_a.data + __pyx_t_3 * __pyx_v_a.strides[0]) )) + __pyx_t_4)) )))), (&__pyx_v_n), (&(__pyx_v_piv[0])), (&__pyx_v_info));
                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
scipy/linalg/_cythonized_array_utils.cpython-311-darwin.so.p/_cythonized_array_utils.c:22769:79: warning: passing 'const __pyx_t_double_complex *' to parameter of type '__pyx_t_double_complex *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
    __pyx_f_5scipy_6linalg_13cython_lapack_zgetrf((&__pyx_v_n), (&__pyx_v_n), (&(*((__pyx_t_double_complex const  *) ( /* dim=1 */ ((char *) (((__pyx_t_double_complex const  *) ( /* dim=0 */ (__pyx_v_a.data + __pyx_t_3 * __pyx_v_a.strides[0]) )) + __pyx_t_4)) )))), (&__pyx_v_n), (&(__pyx_v_piv[0])), (&__pyx_v_info));
                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 warnings generated.
```

I understand what the warnings mean. My question is whether we should also ``const`` qualify the relevant functions in the call to lapack?

**Comment by ev-br** [comment]
Ouch. I don't know whether
- cython does sensible things in `if lapack_t is float: ...` selections below https://github.com/scipy/scipy/blob/9c98ee762a95cf46d8f91f1c1a5547701538d286/scipy/linalg/_cythonized_array_utils.pyx#L29
-  lapack bindings are prepared to handle `const float*` arguments. there is no notion of const in F77.

**Comment by Kai-Striega** [comment]
Maybe @ilayn has an opinion here?

**Comment by ilayn** [comment]
Probably you will need the `const` version of that fused type if you want to pass `const lapack_t`. This whole templating business we have is just a neverending chore in my opinion (say, if compared to Rust generics)

So I am tempted to rewrite them spelled out four times for these helper functions rather than dealing with these fake-C constructs of Cython.

**Comment by ilayn** [comment]
Actually since @rgommers triggered me to write more C code instead of Cython in the `scipy.special` rewrites, I think it is better for us to have more C code than Cython for array manipulation funcs. We really don't benefit from Cython which is mostly quick bursts of typed arithmetic and for loops but indeed extensively using arrays and low-level C access. That's both not useful for us and unfair to Cython. 

I still don't have a full grasp of NumPy C API but I think I got the gist of it lately. So feel free to modify things as you see fit. I will circle back to these at some point anyways.

**Comment by rgommers** [comment]
Public Cython API we expose (`cython_blas`, `cython_lapack`, `cython_special`) is the exception to what is actionable in this issue. We tried adding `const` to signatures before, and found it was a backwards compatibility break. Cython considers any change in signature breaking, even if adding `const` in the equivalent C code would be perfectly compatible. So I suggest not touching public Cython API.

**Comment by ilayn** [comment]
> The value we get from boundschecking, from abstracting away pointer arithmetics and refcounting is huge.

Ah, I don't mean to use less Cython. I want to use it where it matters. Let me clarify. I mean there is no significant speed benefit to do array operations in Cython. NumPy is already pretty performant, for many array operations. In fact often, you don't even need to type the numpy arrays. They are already fast enough. 

However if you want to do certain things involving for loops and other ops there is crazy amount of performance that Cython offers. What I meant is that if we really want to get Cython benefits we probably should use it where it matters and not just for minute performance improvements. The function @Kai-Striega mentioned is a good example in my opinion. I wrote it when I did not have any other choice.

I think we are on the same page with your comments anyways. Regarding the two bullet points you mentioned, 

 - Cython is injecting too much code in between and binary size increase. They are really great for C-function binding just do `cimport ... extern ...` and we are good to go. So in that sense we should use more of it. Definitely much easier than `pybind11` or `nanobind`. 
 - If we have to, I would side with using C and not C++. Then it is pretty mundane old-school flat memory with `A[ row*n + col ] = 5.` silliness with all unsafe stuff about C but at least very robust infrastructure/compiler support and backwards compatible language not changing incredibly every 3-5 years.

**Comment by ev-br** [comment]
> I mean there is no significant speed benefit to do array operations in Cython. NumPy is already pretty performant, for many array operations.

Yes, until you need a for loop. We all know it, and you write exactly this below. So no preaching to the choir. My point is that needing a for loop is not a fringe rarity, and it should not be made prohibitively difficult.

Now, for cython producing too fat binaries, that's actually actionable (or at least researcheable). Cool!
- what adds the most fat, what can an author of a cython module do to slim it down?
- cython naturally encourages to mix pure python and typed C-like constructs. A pure guesswork is that it's this pure python which adds to the module size, is this correct?

Flat memory: yes, as long as I can switch the boundschecking on :-). 

For C/C++ : oh beware. THere will be six opinions for every five devs :-). All the more important to formulate guidelines, on a common deniminator, however informal. 

We should probably take this discussion to a separate issue anyway.

**Comment by Kai-Striega** [comment]
Bringing the discussion back to this issue: I think I'm going to leave these functions till last, or at least until we have reached a consensus regarding our use of Cython/C/C++.

**Comment by matusvalo** [comment]
> what adds the most fat, what can an author of a cython module do to slim it down?

See:
* https://cython.readthedocs.io/en/latest/src/userguide/faq.html#how-do-i-reduce-the-size-of-the-binary-modules
* https://github.com/cython/cython/issues/6045
* https://github.com/cython/cython/issues/4425#issuecomment-1966330797

**Comment by rgommers** [comment]
This remains a thing that causes issues, so it'd be good to get it done. I edited the issue description to add a tracker per submodule. If you do one, please ensure to do a whole submodule and then tick it off in the tracker.

Cc @czgdp1807

**Comment by czgdp1807** [comment]
Sure. I will work on it. I think the issue will be completed when all the tasks here are done.

**Comment by czgdp1807** [comment]
I opened 3 PRs today. #20872, #20873, #20874. Let me know if I should work on modifying tests for these `const` additions to make sure someone doesn't undo the `const` additions in future. Other than this I can't think of more benefits of adding/modifying tests. Let me know if I am missing out something.

**Comment by rgommers** [comment]
Nice! I don't think we need tests for that. Removing `const` from anywhere is highly unlikely, and the kind of thing that should be caught from code review. I think we either test read-only arrays structurally across all APIs (which would be a lot of work), or we don't test it unless we have a good reason to (like a bug report).

**Comment by lucascolley** [comment]
> we either test read-only arrays structurally across all APIs

well, good job we are adding array API support and testing with read-only JAX arrays, then 😉

**Comment by czgdp1807** [comment]
`_lib`, `fftpack`, `integrate`, `ndimage`, `special` don't have any array usage in `pyx` files. So this issue is complete from my end.

**Comment by lucascolley** [comment]
`io` too?

**Comment by czgdp1807** [comment]
Yes. I forgot to mention it. `io` too doesn't have any array usage in `pyx` files.

**Comment by lucascolley** [comment]
great, thanks @czgdp1807 ! If we've missed any, JAX should tell us as array API standard support is expanded.

**Comment by rgommers** [comment]
Awesome, thanks for completing this. And yes, JAX will be a nice way to verify without having to write more tests:)
