### ISSUE TITLE
ENH: sparse: Validate dtype on sparse array/matrix creation

### ISSUE THREAD

**Issue by perimosocordiae** [scipy/scipy#20207]
### Is your feature request related to a problem? Please describe.

Due to limitations of the native `sparsetools` module and compiler support for half-float types, we have never supported np.float16 as a data type for `scipy.sparse` arrays (or matrices). (See gh-7408 for details and discussion.)

That said, we don't currently validate the dtype users specify, which leads to confusing errors and several bug reports: gh-2481, gh-7408, gh-8903, gh-13352, gh-19655, and gh-20200.

### Describe the solution you'd like.

In each sparse format's `__init__` method, we could check the input `dtype` against our existing list of supported types: https://github.com/scipy/scipy/blob/2aee5efcbe3720f41fe55f336f492ae0acbecdee/scipy/sparse/_sputils.py#L16-L19

Initially we should probably raise a warning if the given dtype is incompatible, and eventually we may promote this to an error.

**Comment by rmnigm** [comment]
Hello! May I work on this issue? Made a PR with proposed changes.
