### ISSUE TITLE
ENH: signal.bilinear: pobbibly inaccurate coefficients computation

### ISSUE THREAD

**Issue by NielsMortensen** [scipy/scipy#20211]
https://github.com/scipy/scipy/blob/4edfcaa3ce8a387450b6efce968572def71be089/scipy/signal/_filter_design.py#L2150-L2232

Hi this is my first ever use of GitHub.

I tried translating this implementation of the bilinear transform to matlab. 
Once i did, I tested it against matlab's built in bilinear function on a given filter.
The filter it gave had a slightly frequency response at low frequencies (~1dB). 

There might be a small mistake somewhere in there giving rise to this discrepency. 

Somewhere else on the internet, I found another open source implementation of the bilinear transform :
https://savannah.gnu.org/bugs/?60375
I briefly tested it and it obtains the same results as matlab's. 

My suggestion is to make SciPy's implementation closer to savannah's as it seems to work better.

Cheers

**Comment by roryyorke** [comment]
Could you give example inputs with expected outputs?
