### ISSUE TITLE
BUG: test fail in `scipy.optimize.tests.test_linprog.TestLinprogIPDense.test_bug_6139`

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#20216]
### Describe your issue.

In https://github.com/scipy/scipy/pull/20210 I'm attempting to port the macosx_arm64 builds from Cirrus to GHA. However, there's currently a test failing in [TestLinprogIPDense.test_bug_6139](https://github.com/scipy/scipy/actions/runs/8186629091/job/22385400156#step:6:10351).

I think @mdhaber or @Kai-Striega may be the best people to diagnose.

### Reproducing Code Example

```python
Test suite
```

### Error message

```shell
_______________________ TestLinprogIPDense.test_bug_6139 _______________________
  ../venv-test/lib/python3.12/site-packages/scipy/optimize/tests/test_linprog.py:1358: in test_bug_6139
      _assert_success(res, desired_fun=14.95,
          A_eq       = array([[    1.,     0.,     0.],
         [-1000.,     0., -1000.]])
          A_ub       = array([[      -0., -1000000., -1010000.]])
          b_eq       = array([ 5.e+00, -1.e+04])
          b_ub       = array([-10000000.])
          bounds     = (None, None)
          c          = array([1, 1, 1])
          res        =  message: The solution does not satisfy the constraints within the required tolerance of 3.16E-04, yet no errors were ...port.
   success: False
    status: 4
       fun: 14.949999998947106
         x: [ 5.000e+00  4.950e+00  5.000e+00]
       nit: 5
          self       = <scipy.optimize.tests.test_linprog.TestLinprogIPDense object at 0x112a51df0>
  ../venv-test/lib/python3.12/site-packages/scipy/optimize/tests/test_linprog.py:68: in _assert_success
      raise AssertionError(msg)
  E   AssertionError: linprog status 4, message: The solution does not satisfy the constraints within the required tolerance of 3.16E-04, yet no errors were raised and there is no certificate of infeasibility or unboundedness. Check whether the slack and constraint residuals are acceptable; if not, consider enabling presolve, adjusting the tolerance option(s), and/or using a different method. Please consider submitting a bug report.
          atol       = 1e-08
          desired_fun = 14.95
          desired_x  = array([5.  , 4.95, 5.  ])
          msg        = 'linprog status 4, message: The solution does not satisfy the constraints within the required tolerance of 3.16E-04, y...presolve, adjusting the tolerance option(s), and/or using a different method. Please consider submitting a bug report.'
          res        =  message: The solution does not satisfy the constraints within the required tolerance of 3.16E-04, yet no errors were ...port.
   success: False
    status: 4
       fun: 14.949999998947106
         x: [ 5.000e+00  4.950e+00  5.000e+00]
       nit: 5
          rtol       = 1e-08
```

### SciPy/NumPy/Python version and system information

```shell
numpy 2.0.0.dev0, main
```

**Comment by Kai-Striega** [comment]
@andyfaff I'll take a look at it when I come home from work or over the weekend. Feel free to ping me if I haven't replied by Sunday.

**Comment by mdhaber** [comment]
I wouldn't spend too much time on it. Interior point is past the end of its deprecation period; when HiGHS has callback support, it will be removed. If it turns out not to be simple, I think you can disable the the test, since it's reporting a failure and not giving an incorrect result.

**Comment by thalassemia** [comment]
Huh, I saw the same test fail in a new Accelerate CI entry that I added as part of gh-19816. I assumed it was due to the new BLAS library, but I guess that might not be the case if it is also failing with OpenBLAS. The failure disappeared when I switched from an x86 macOS 13 runner to an M1 macOS 14 runner. I do not have an x86 macOS machine to test locally.

**Comment by andyfaff** [comment]
I'll probably skip the test for Darwin greater than a certain version.

**Comment by Kai-Striega** [comment]
I had a quick look but couldn't find anything obvious. I think it's going to be easiest to simply skip the test for now (until `ip` is deprecated)

**Comment by andyfaff** [comment]
Test is now skipped
