### ISSUE TITLE
DOC: Sparse arrays: todense() does not return numpy.matrix

### ISSUE THREAD

**Issue by henry50** [scipy/scipy#20239]
### Issue with current documentation:

The documentation states that the `todense()` method of each of the sparse array classes returns a `numpy.matrix` but they return a `numpy.ndarray`.

### Idea or request for content:

Modify the documentation to state the return type is `numpy.ndarray`.

**Comment by j-bowhay** [comment]
@henry50 would you be interested in opening a PR?

**Comment by dschult** [comment]
See also #18898
