### ISSUE TITLE
ENH: Akima1DInterpolator Extrapolation

### ISSUE THREAD

**Issue by psmd-iberutaru** [scipy/scipy#20247]
### Is your feature request related to a problem? Please describe.

Unlike the CubicHermiteSpline from which the Akima interpolator inherits from, attempting extrapolation with the Akima1DInterpolator returns NaN outside of the original domain. I expected this because of the hard coded `extrapolate=False` on initialization.

I think adding extrapolation capabilities to the Akima1DInterpolator class would make sense. Of the four main 1D splines (CubicSpline, CubicHermiteSpline, PchipInterpolator, and Akima1DInterpolator), Akima is the only one to not support extrapolation.

### Describe the solution you'd like.

Allowing the specification of `extrapolate=True` and exposing a similar extrapolation parameter interface as CubicHermiteSpline is the most natural. Extrapolation should then be handled similarly to all of the other splines in the user's perspective.

### Describe alternatives you've considered.

For my own project purposes, I have been using alternative splines from Scipy. The Akima1DInterpolator (and the modified Akima interpolator per #19696 ) seems to have desirable properties, but the lack of extrapolation is otherwise problematic.

**Comment by ev-br** [comment]
You can switch extrapolation either at call site or globally (this is inherited from Akima1DInterpolator superclass, PPoly):

```
In [1]: import numpy as np

In [2]: from scipy.interpolate import Akima1DInterpolator

In [3]: a = Akima1DInterpolator([1, 2, 3], [4, 5, 6])

In [4]: a(5)
Out[4]: array(nan)

In [5]: a(5, extrapolate=True)
Out[5]: array(8.)

In [6]: a.extrapolate = True

In [7]: a(5)
Out[7]: array(8.)
```

That said, the decision to not have the extrapolate parameter is historic. A pull request adding the `extrapolate=False` parameter to the constructor is welcome.
