### ISSUE TITLE
DOC, MAINT: .jupyterlite.doit.db shows up untracked

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#20264]
Minor point, but should be fixed eventually. `python dev.py doc -j 1` on latest `main` leaves an untracked artifact in the source tree:

```
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	doc/source/.jupyterlite.doit.db
```

A number of other `.doit.db` file patterns are already covered in `.gitignore`.

**Comment by sijopkd** [comment]
Can I please work on this?

**Comment by j-bowhay** [comment]
> Can I please work on this?

Yes that would be great!

**Comment by Aloqeely** [comment]
Any updates on this? I can fix it instead of Sijo if possible

**Comment by sijopkd** [comment]
> Any updates on this? I can fix it instead of Sijo if possible

I will be raising a PR soon.

**Comment by sijopkd** [comment]
@tylerjereddy Thanks for giving an opportunity to do my first issue. Do we want to ignore all the 

> > Any updates on this? I can fix it instead of Sijo if possible
> 
> I will be raising a PR soon.

Here is the PR: https://github.com/scipy/scipy/pull/20280
