### ISSUE TITLE
CI: jupyterlite-shpinx pin breaks recent doc builds

### ISSUE THREAD

**Issue by j-bowhay** [scipy/scipy#20296]
```
ERROR: Could not find a version that satisfies the requirement jupyterlite-sphinx>=0.13.0 (from versions: 0.0.0a0, 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.5.0, 0.6.0, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.11.0, 0.12.0)
ERROR: No matching distribution found for jupyterlite-sphinx>=0.13.0
```
https://app.circleci.com/pipelines/github/scipy/scipy/25562/workflows/9e594859-d918-4a3a-ac1b-ecd35ace68c1/jobs/86348
cc. @steppi

**Comment by steppi** [comment]
Sorry. 0.13.0 had a serious bug and had to be revoked. 0.13.1 is coming out today

**Comment by j-bowhay** [comment]
Thanks for confirming @steppi, I will leave this open for visibility until then

**Comment by melissawm** [comment]
We should probably also use the same pin for https://github.com/scipy/scipy/blob/235602cf350e9aad7bf09ee42ddd7dd4cc4a6550/environment.yml#L47 and https://github.com/scipy/scipy/blob/235602cf350e9aad7bf09ee42ddd7dd4cc4a6550/pyproject.toml#L105
