### ISSUE TITLE
ENH: Support one-based indices

### ISSUE THREAD

**Issue by orenbenkiki** [scipy/scipy#20306]
### Is your feature request related to a problem? Please describe.

I'm trying to share data between Python and Julia. I can do zero-copy sharing of dense arrays w/o a problem. However, Julia uses 1-based indices and Python uses 0-based indices. This means that the 0-based `indptr` and `indices` Python arrays are incompatible with the Julia `colptr` and `rowval` 1-based arrays, forcing a creation of a copy every time data passes between the languages.

### Describe the solution you'd like.

SparseBlas data has a field which specifies whether the indices arrays are 0-based or 1-based. Can scipy be extended to support this as well? This has basically no impact on efficiency (an additional delta added to offset computations, without the need for any branches).

### Describe alternatives you've considered.

I'm also opening an issue in Julia's SparseArrays library asking for the same feature (https://github.com/JuliaSparse/SparseArrays.jl/issues/522). However until at least one of the libraries supports this feature, I'm forced to copy the data (and some of my sparse matrices are very large - 100s of MBs...).

**Comment by perimosocordiae** [comment]
Sorry, this feature request would require a massive overhaul of scipy.sparse to support, as we don't have a centralized code path for index handling.

As a workaround, you could leave the zero row/column empty and treat your scipy.sparse array as if it was 1-indexed (though you'd need to account for the larger shape in some operations). Your `indices` array would be correct as-is for passing to Julia, and your `indptr` array would only need to drop the first entry.

**Comment by orenbenkiki** [comment]
The idea of having a matrix of 1+N by 1+M is a cool workaround. It won't work in my specific use case but may be helpful for others.

I assume this means that slicing a sparse matrix always creates a copy of the 3 arrays? That is, there's no zero-copy "view" concept for sparse matrices? Because if there was such a concept, I could create the 1+N by 1+M matrix and return a view slicing just [1:] out of both columns and rows.
