### ISSUE TITLE
MAINT, BUG (?): pearsonr statistic return type change

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#20324]
Originally reported by @stefanv on mailing list, for an issue that was detected in `skimage`. My local testing suggests that the issue is reproducible for NumPy `1.26.4` and NumPy `2.0.0b1` though, so the reason may be due to a code change we've made directly.

I confirmed locally that the test below passes at `v1.12.0` tag, and fails on `main`. I think Stefan's argument was that the docstring still says `float` for the statistic.

```diff
--- a/scipy/stats/tests/test_stats.py
+++ b/scipy/stats/tests/test_stats.py
@@ -8495,3 +8495,8 @@ class TestExpectile:
         for alpha in np.r_[0, alpha_seq, 1 - alpha_seq[:-1:-1], 1]:
             e_list.append(stats.expectile(x, alpha=alpha))
         assert np.all(np.diff(e_list) > 0)
+
+
+def test_pearsonr_stat_ret_type():
+    res = stats.pearsonr([1, 2, 3], [4, 5, 6])
+    assert isinstance(res.statistic, float)
```

Maybe one of the `stats` folks can comment re: what we might want to do here for `1.13.0`? I'll see if I can bisect this for you folks.

**Comment by tylerjereddy** [comment]
Here's the result of `git bisect` process on the above regression test:

```
ceea3e316ab78e3477004da0c26236105fe3b4d5 is the first bad commit
commit ceea3e316ab78e3477004da0c26236105fe3b4d5
Author: Matt Haberland <mhaberla@calpoly.edu>
Date:   Wed Mar 20 21:43:07 2024 -0700

    ENH: stats.pearsonr: add support for `axis` argument (#20137)

 scipy/stats/_morestats.py       |  16 ++--
 scipy/stats/_stats_py.py        | 187 ++++++++++++++++++++++++++--------------
 scipy/stats/tests/test_stats.py | 101 ++++++++++++++++++++--
 3 files changed, 219 insertions(+), 85 deletions(-)
```

**Comment by mdhaber** [comment]
I'll take a look.

**Comment by lucascolley** [comment]
Yeah, so @stefanv it looks like this commit is not in the 1.13 branch. Was the problem definitely with 1.13.0rc1, or just `main`?

**Comment by stefanv** [comment]
I probably tested on main.
