### ISSUE TITLE
ENH: enable to print message from `scipy.optimize.fmin` etc to something other than stdout

### ISSUE THREAD

**Issue by e-kwsm** [scipy/scipy#20348]
### Is your feature request related to a problem? Please describe.

```python
>>> from scipy.optimize import fmin
>>> _ = fmin(lambda x: x**2, 1, disp=True)
Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 17
         Function evaluations: 34
```

Here the convergence message is printed to stdout, which is not changeable.

https://github.com/scipy/scipy/blob/01ef73eb419ef42943f81b433d559d523eaf5be9/scipy/optimize/_optimize.py#L915-L919

### Describe the solution you'd like.

It is allowed to pass a file-like object:

```python
# default to sys.stdout
fmin(lambda x: x**2, 1, disp=True)
# print to stderr
fmin(lambda x: x**2, 1, disp=True, file=sys.stdout)
# write to a file
with open("a.dat", "w") as file:
    fmin(lambda x: x**2, 1, disp=True, file=file)
```

**Comment by andyfaff** [comment]
Sorry, that stands little chance of getting implemented. You have a few options. The first could be use a callback to direct progress to wherever you like. The second could be to redirect sys.stdout to a file.

**Comment by lucascolley** [comment]
x-ref gh-19915

**Comment by e-kwsm** [comment]
I would be happy if a loggers handles this.
