### ISSUE TITLE
MAINT/DOC: remove outdated note about NumPy imports

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#20344]
The following note is not true anymore, but it is still in the docs: https://scipy.github.io/devdocs/reference/index.html#guidelines-for-importing-functions-from-scipy

![image](https://github.com/scipy/scipy/assets/51488791/040c0d5c-5d19-4b58-8da7-d8003237bd93)

The lines to be removed are: https://github.com/scipy/scipy/blob/cb3ac11209444f9b56454e41abc6a95b63c7ef4b/doc/source/reference/index.rst?plain=1#L87-L92

**Comment by ambersun1234** [comment]
I'll help with this issue
