### ISSUE TITLE
wrong return value

### ISSUE THREAD

**Issue by xxamxam** [scipy/scipy#20360]
in mannwhitneyu criteria earlier U is computed, based on U1, U2 and sidedness of criteria, but U1 returns as result

https://github.com/scipy/scipy/blob/4edfcaa3ce8a387450b6efce968572def71be089/scipy/stats/_mannwhitneyu.py#L501

**Comment by mdhaber** [comment]
This is not a bug. See the documentation.

![image](https://github.com/scipy/scipy/assets/6570539/6660e494-ab1f-49ff-8207-48be95bf6a8e)

Please be sure to read the documentation and follow the template when reporting issues in the future.
