### ISSUE TITLE
DOC: ndimage.convolve: clarify origin parameter description

### ISSUE THREAD

**Issue by AlexanderForrest** [scipy/scipy#20370]
### Issue with current documentation:

https://scipy.github.io/devdocs/reference/generated/scipy.ndimage.convolve.html#scipy-ndimage-convolve

The ndimage.convolve has the parameter origin, which is listed as type int.  

when working with this, it actually appears to take in a sequence with length equal to the number of dimensions.

### Idea or request for content:

clarifying the description to be the same as ndimage.correlate:
https://scipy.github.io/devdocs/reference/generated/scipy.ndimage.correlate.html#scipy.ndimage.correlate

**Comment by j-bowhay** [comment]
@AlexanderForrest would you like to make a PR

**Comment by milindsmart** [comment]
I also ran into this discrepancy - the documentation not listing axis-wise origin (offset) values was very surprising as well.

**Comment by lucascolley** [comment]
if you could add any suggestions over at gh-20408, that would be great @milindsmart
