### ISSUE TITLE
MAINT: special version hex cleanup

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#20385]
Just poking around after gh-20373, I think this can be removed now from `scipy/special/ufunc.h`:

```
#if (PY_VERSION_HEX < 0x030a00f0)
// This function is standard in Python >=3.10, we just add it here for convenience.
inline int PyModule_AddObjectRef(PyObject *module, const char *name, PyObject *value) {
    Py_INCREF(value);
    return PyModule_AddObject(module, name, value);
}
#endif
```

Not sure if the C++ stuff just makes it all obsolete anyway. That's the last remaining usage of `PY_VERSION_HEX` we have.

**Comment by izaid** [comment]
> Just poking around after [gh-20373](https://github.com/scipy/scipy/pull/20373), I think this can be removed now from `scipy/special/ufunc.h`:
> 
> ```
> #if (PY_VERSION_HEX < 0x030a00f0)
> // This function is standard in Python >=3.10, we just add it here for convenience.
> inline int PyModule_AddObjectRef(PyObject *module, const char *name, PyObject *value) {
>     Py_INCREF(value);
>     return PyModule_AddObject(module, name, value);
> }
> #endif
> ```
> 
> Not sure if the C++ stuff just makes it all obsolete anyway. That's the last remaining usage of `PY_VERSION_HEX` we have.

Oh, ok, great! I literally just put that in a couple of weeks ago, but if we are now on Python 3.10 then good stuff.

**Comment by izaid** [comment]
I have removed this in https://github.com/scipy/scipy/pull/20403.
