### ISSUE TITLE
BUG: Problems with new scipy 1.13 RegularGridInterpolator spline interpolation beyond documented behaviour

### ISSUE THREAD

**Issue by moritzhuetten** [scipy/scipy#20387]
### Describe your issue.

With the new scipy 1.13 release, changes to the spline interpolation methods in the `RegularGridInterpolator` were introduced, which are documented, also mentioning longer construction time.
However, using the affected “slinear”, “cubic” and “quintic” in the `RegularGridInterpolator` is slowing down the code drastically in my use case, even leading to errors, as shown below. Also, using the `_legacy` methods did not reproduce the previous behavior, leaving the program stuck in the instantiation of `RegularGridInterpolator`.
Although it might not be possible to reproduce the problem without the exact same data, I would like to mention the problem in case it may occur more widely.

### Reproducing Code Example

```python
Instantiation of RegularGridInterpolator() for 3D dataset.
```

### Error message

```shell
File /opt/homebrew/Caskroom/miniconda/base/envs/test-env/lib/python3.11/site-packages/scipy/interpolate/_rgi.py:298, in RegularGridInterpolator.__init__(self, points, values, method, bounds_error, fill_value, solver, solver_args)
    296     if solver_args is None:
    297         solver_args = {}
--> 298     self._spline = self._construct_spline(method, solver, **solver_args)
    299 else:
    300     if solver is not None or solver_args:

File /opt/homebrew/Caskroom/miniconda/base/envs/test-env/lib/python3.11/site-packages/scipy/interpolate/_rgi.py:309, in RegularGridInterpolator._construct_spline(self, method, solver, **solver_args)
    307 if solver is None:
    308     solver = ssl.gcrotmk
--> 309 spl = make_ndbspl(
    310         self.grid, self.values, self._SPLINE_DEGREE_MAP[method],
    311         solver=solver, **solver_args
    312       )
    313 return spl

File /opt/homebrew/Caskroom/miniconda/base/envs/test-env/lib/python3.11/site-packages/scipy/interpolate/_ndbspline.py:355, in make_ndbspl(points, values, k, solver, **solver_args)
    351     if "atol" not in solver_args:
    352         # avoid a DeprecationWarning, grumble grumble
    353         solver_args["atol"] = 1e-6
--> 355 coef = solver(matr, vals, **solver_args)
    356 coef = coef.reshape(xi_shape + v_shape[ndim:])
    357 return NdBSpline(t, coef, k)

File /opt/homebrew/Caskroom/miniconda/base/envs/test-env/lib/python3.11/site-packages/scipy/interpolate/_ndbspline.py:282, in _iter_solve(a, b, solver, **solver_args)
    280     return res
    281 else:
--> 282     res, info = solver(a, b, **solver_args)
    283     if info != 0:
    284         raise ValueError(f"{solver = } returns {info = }.")

File /opt/homebrew/Caskroom/miniconda/base/envs/test-env/lib/python3.11/site-packages/scipy/_lib/deprecation.py:213, in _deprecate_positional_args.<locals>._inner_deprecate_positional_args.<locals>.inner_f(*args, **kwargs)
    211 extra_args = len(args) - len(all_args)
    212 if extra_args <= 0:
--> 213     return f(*args, **kwargs)
    215 # extra_args > 0
    216 args_msg = [
    217     f"{name}={arg}"
    218     for name, arg in zip(kwonly_args[:extra_args], args[-extra_args:])
    219 ]

File /opt/homebrew/Caskroom/miniconda/base/envs/test-env/lib/python3.11/site-packages/scipy/sparse/linalg/_isolve/_gcrotmk.py:291, in gcrotmk(A, b, x0, tol, maxiter, M, callback, m, k, CU, discard_C, truncate, atol, rtol)
    288 A,M,x,b,postprocess = make_system(A,M,x0,b)
    290 if not np.isfinite(b).all():
--> 291     raise ValueError("RHS must contain only finite numbers")
    293 if truncate not in ('oldest', 'smallest'):
    294     raise ValueError(f"Invalid value for 'truncate': {truncate!r}")

ValueError: RHS must contain only finite numbers
```

### SciPy/NumPy/Python version and system information

```shell
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=64
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.26.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=64
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.26.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 13.2.0
  pythran:
    include directory: ../../../../../../private/var/folders/l_/53d72k7j4zl9kj8fzncsd8hw0000gn/T/pip-build-env-xo17zr8z/overlay/lib/python3.11/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/l_/53d72k7j4zl9kj8fzncsd8hw0000gn/T/cibw-run-95i9ncig/cp311-macosx_arm64/build/venv/bin/python
  version: '3.11'
```

**Comment by ev-br** [comment]
1) the error indicates that `values` have infs or nans. This is indeed a problem, and the fact that it worked previously is an accident, really. 

2) _legacy methods should be exactly identical to what it was in the previous scipy releases. If they are not, it's a bug. Would you please be able to add a minimal reproducible example for us to take a look?

**Comment by moritzhuetten** [comment]
Hi @ev-br , thanks a lot for the quick response. Indeed, I can confirm that the error occurs for (and only for, as far as I see) a dataset with NaNs (and previously, instantiation was possible even with NaNs being present). I will investigate further if I still see a discrepancy in performance for a dataset without NaNs, using the `_legacy` methods. However, if `_legacy` methods should be identical to before also if NaNs are present, I can already tell that it does not seem to be the case for me, and I will see if I can create a minimal data set to reproduce it.

**Comment by moritzhuetten** [comment]
Dear @ev-br , I investigated further and contrarily to what I previously claimed, I see no difference between the `_legacy` methods in scipy 1.13 and the corresponding methods in scipy < 1.13. So everything seems to work as expected and this issue can be closed I guess. However, let me allow to ask two questions:
- As the new spline `RegularGridInterpolator` instantiation may take significantly more time than before for the benefit of faster interpolation afterwards, aren't there case where a different trade-off is desired, i.e., fast instantiation is more important? So to permanently allow to choose the most suitable method in the future?
- Shouldn't it be possible (at one's own risk) to allow interpolation on a grid containing NaNs?

Thanks a lot again for your support!

**Comment by ev-br** [comment]
Thanks for confirming the `_legacy` behavior!

> aren't there case where a different trade-off is desired, i.e., fast instantiation is more important? So to permanently allow to choose the most suitable method in the future?

Sure. Only a user can decide what's most suitable for their specific problem though. The best a library can do is to offer a choice, here between `cubic` or `cubic_legacy` etc.

> Shouldn't it be possible (at one's own risk) to allow interpolation on a grid containing NaNs?

Sure. 
Just keep ising `linear`, `nearest` and `_legacy` methods :-).

Alternatively, you can provide your own `solver` argument. It should look like `sparse.linalg.solve` or iterative solvers from `sparse.linalg`, that's the only requirement.  See https://github.com/scipy/scipy/blob/main/scipy/interpolate/_ndbspline.py#L355
I'm sceptical TBH --- the 'missing value' `nan` semantics is inherently at odds with the 'not-a-number' semantics that scipy.linalg and scipy.interpolate adhere to. But don't let my skepticism discourage you, I'd be happy to be proven wrong. So if you manage to make it work, do let us know!
