### ISSUE TITLE
DOC: optimize.root(method='lm') option

### ISSUE THREAD

**Issue by sdupouy** [scipy/scipy#20392]
### Issue with current documentation:

The option called "epsfcn" in the doc for the `optimise.root(method='lm')` function is actually "eps" in the code.

### Idea or request for content:

Change option name "epsfcn" to "eps" in this doc page [optimize.root-lm](https://docs.scipy.org/doc/scipy/reference/optimize.root-lm.html)

**Comment by AtsushiSakai** [comment]
I checked git history fo this function.
Before this [PR](https://github.com/scipy/scipy/pull/217), which was 12 years ago, the option for the root function was named `epsfcn`, but after this PR, it appears to have been changed to `eps`.
The [`fsolve`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fsolve.html) function is using `epsfcn`. But, [`root(method="hybr")`](https://docs.scipy.org/doc/scipy/reference/optimize.root-hybr.html#optimize-root-hybr) is also using `esp`. 
So, API consistency stand of view, I think we should use `esp` in the `root` function.
