### ISSUE TITLE
DOC: the SciPy website mistakenly believe that the chi2_contingency function returns a Chi2ContingencyResult

### ISSUE THREAD

**Issue by ssh-12** [scipy/scipy#20409]
### Issue with current documentation:

Date: April 03, 2024 Version: 1.13.0

### Idea or request for content:

In practice, the result returned by the chi2_contingency function is a simple tuple.

### Additional context (e.g. screenshots, GIFs)

![screenshot-1712490108323](https://github.com/scipy/scipy/assets/113653067/99645744-d680-4fd3-b2f8-3dbfd6190cfd)

![screenshot-1712490540294](https://github.com/scipy/scipy/assets/113653067/3e4cb0e2-c2fc-4381-80a4-0c09c476c566)

**Comment by mdhaber** [comment]
```
import numpy as np
from scipy.stats import chi2_contingency
table = np.array([[176, 230], [21035, 21018]])
res = chi2_contingency(table)
type(res)  # scipy.stats.contingency.Chi2ContingencyResult
```
https://github.com/scipy/scipy/blob/7dcd8c59933524986923cde8e9126f5fc2e6b30b/scipy/stats/contingency.py#L365
