### ISSUE TITLE
BUG: <Unable to import 'triu' module>

### ISSUE THREAD

**Issue by HP657** [scipy/scipy#20402]
### Describe your issue.

Looking at the example code, unlike version 1.12.0, in version 1.13.0, `ImportError: Cannot import name 'triu' from 'scipy.linalg'(c:\~~\__init__.py).` Such a phenomenon occurred. .

### Reproducing Code Example

```python
import scipy.linalg as la

# example
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# triu useing
result = la.triu(m)
print(result)
```

### Error message

```shell
ImportError: Cannot import name 'triu' from 'scipy.linalg'(c:\~~\__init__.py)
```

### SciPy/NumPy/Python version and system information

```shell
scipy:1.13.0
numpy:1.26.4
python:3.10.14
```

**Comment by ilayn** [comment]
`triu` is deprecated and removed from scipy.linalg. You need to use triu from numpy with 

```python
np.triu(m)
```

**Comment by lucascolley** [comment]
I don't think that there is any occurrence of `la.triu` in the docs - please let us know if I am mistaken @HP657 :)

**Comment by ds-mike** [comment]
Hi @lucascolley or @ilayn, I believe I am facing this issue. Having trouble following the outcome to this issue thread, it looks like this is closed but I believe it is an issue in the latest version of scipy.

Here are the steps to reproduce:
```
python -m venv temp_venv
source temp_venv/bin/activate
pip install scipy==1.13.0
python
Python 3.11.8 (main, Feb 13 2024, 21:57:06) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy.linalg import get_blas_funcs, triu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'triu' from 'scipy.linalg' (<redacted>python3.11/site-packages/scipy/linalg/__init__.py)`
```

Thank you!

**Comment by ilayn** [comment]
Hi @ds-mike See my comment above.

**Comment by ds-mike** [comment]
Oh thanks! It is a [gensim issue](https://github.com/piskvorky/gensim/blob/develop/gensim/matutils.py#L26) that I had missed originally.
