### ISSUE TITLE
Possible typo in computation of hypergeometric function 2F1

### ISSUE THREAD

**Issue by DeliciousHair** [scipy/scipy#20411]
https://github.com/scipy/scipy/blob/579a5bf16e160990b56989c36b31d1f8633c15ca/scipy/special/_hyp2f1.pxd#L456C1-L456C70

I may be wrong about this as I am rather deep in the weeds here, but I think that this line *may* supposed to be:

```
        if fabs((u_prime - w_prime)*(u - 0.5)) < 100*ugh and u > 100:
            result *= exp((u - 0.5)*log1p((u_prime - w_prime)/ugh))
```

That is, `ugh` rather than `wgh` in the first comparison and denominator or the `log1p()` expression.

**Comment by lucascolley** [comment]
cc @steppi

**Comment by steppi** [comment]
@DeliciousHair, thanks for the report. Can you share what lead you into the weeds of these formula, and why you think there's a typo? I recall spending a mind melting day trying to get everything detail right. Using the Lanczos approximation for this gamma ratio seems conceptually easy, but I found handling all cases where the reflection principle may be needed, and for deciding which factor to absorb into the others was incredibly tedious.

At a glance I can tell you that the denominator of the `log1p` expression is not wrong. Without loss of generality, let's assume $u, v, w, x \geq 0.5$, so we don't have to worry about using the reflection principle. Then we are taking the ratio of lanczos prefactors, 

$$\frac{\left(u + g - 0.5\right)^{u - 0.5}}{\left(w + g - 0.5\right)^{w - 0.5}}$$

where $w > u$ and absorbing the $w$ factor into the $u$ factor to as great of an extent as possible. This results in

$$\left[\frac{\left(u + g - 0.5\right)}{\left(w + g - 0.5\right)}\right]^{u - 0.5} \frac{1}{\left(w + g - 0.5\right)^{w - u - 0.5}}$$

and that part of the code is computing the first ratio, which we call

 $$\left(\frac{\text{ugh}}{\text{wgh}}\right)^{u-05}$$.

we can rewrite this as

 $$\left(\frac{\text{wgh} + \text{ugh} - \text{wgh}}{\text{wgh}}\right)^{u-05}$$

Which is just

 $$\left(\frac{\text{wgh} + u - w}{\text{wgh}}\right)^{u-05} = $$


$$\left(1 +\frac{u - w}{\text{wgh}}\right)^{u-0.5} = $$

$$\exp\left(\left(u - 0.5\right)\log\left(1 + \frac{u - w}{\text{wgh}}\right)\right)  = $$

$$\exp\left(\left(u - 0.5\right)\text{log1p}\left(\frac{u - w}{\text{wgh}}\right)\right)$$

which is what's in the code if we ignore the need for the reflection principle, and thus consideration of what I call `u_prime` and `v_prime`.

This expression is useful when `ugh/wgh` is close to 1, and `u` is large, which is what the condition 

```python
if fabs((u_prime - w_prime)*(u - 0.5)) < 100*wgh and u > 100:
```
is checking for, based on a heuristic I copied from here: https://github.com/boostorg/math/blob/15c40fae1610fd83728d75e96d7377fe55f976f7/include/boost/math/special_functions/beta.hpp#L96-L100.

**Comment by steppi** [comment]
No worries! It happens. Also, have you seen the improved C++ version from here: https://github.com/scipy/scipy/pull/20089? I managed to get some solid improvements with a few tweaks and fixing the implementations of some edge-cases. I have two more improvements in mind too that should help this gracefully handle most parameter combinations:

1. First performing the summation forwards until convergence is reached, and then summing backwards from smallest term to largest term to reduce rounding error. This was suggested to me by the author of the `cephes` library which is used internally in SciPy.
2. Perform argument reduction with [Miller's algorithm](https://en.wikipedia.org/wiki/Miller%27s_recurrence_algorithm) to handle large values of $|a|, |b|, |c|$.

I hope to get these things done by late Summer this year.

**Comment by DeliciousHair** [comment]
Thank, I did not see that in fact. Would you be at all offended if I were to brute-force copy it into a rust implementation?

**Comment by steppi** [comment]
> Thank, I did not see that in fact. Would you be at all offended if I were to brute-force copy it into a rust implementation?

Of course not. I encourage it. It's under a BSD 3-clause license after all. I've just done the entirety of cephes into C++ actually: https://github.com/scipy/scipy/pull/20390. I think just put a similar notice to what I put in the cephes files:

https://github.com/scipy/scipy/blob/19de8195296d278d61e3daa7d9f5d0f1fcd33dd4/scipy/special/special/cephes/psi.h#L1-L9

and follow the conditions of the BSD 3-clause license, https://opensource.org/license/bsd-3-clause.

We're actually in the middle of efforts to translate all of special into C++ which can also run on CUDA through conditional compilation, so if you or someone else wanted to brute force translate other things we're working on to make them available in Rust, I'd encourage that too.

**Comment by DeliciousHair** [comment]
Brilliant, and sounds like a great project too! I'd offer to lend a hand but time is always at a premium and my C++ skills are not great. But I will keep an eye on this just in case my circumstances change and I'm able contribute more than just noise.
