### ISSUE TITLE
Can't build scipy-1.11.3: cython compiler cannot compile programs

### ISSUE THREAD

**Issue by Zhang1n** [scipy/scipy#20436]
### Describe your issue.

```
C compiler for the host machine: cc (gcc 10.3.1 "cc (GCC) 10.3.1")
C linker for the host machine: cc ld.bfd 2.37
C++ compiler for the host machine: c++ (gcc 10.3.1 "c++ (GCC) 10.3.1")
C++ linker for the host machine: c++ ld.bfd 2.37
/meson.build:1:0:	ERROR: Cython compiler 'cython’ cannot compile programs
A full log can be found at /root/rpmbuild/BUILD/scipy-1.11.3/.mesonpy-8job81bx/meson-logs/meson-log.txt
Preparing metadata (pyproject.toml)	error
```

After the ''cpython --version'' command is executed , display "cpython" version is 0.29.35

### Reproducing Code Example

```python
meson.get_compiler('cpython')
```

### Error message

```shell
meson.get_compiler('cpython')
```

### SciPy/NumPy/Python version and system information

```shell
meson.get_compiler('cpython')
```

**Comment by lucascolley** [comment]
Can you try using a more recent version of SciPy @Zhang1n ?

**Comment by Zhang1n** [comment]
> Can you try using a more recent version of SciPy @Zhang1n ?



> Can you try using a more recent version of SciPy @Zhang1n ?

**Comment by Zhang1n** [comment]
> Can you try using a more recent version of SciPy @Zhang1n ?

Well, I can try what you say, but I'm actually doing scipy rpm packages, and the latest version may not be able to do it,For example, the Python version is incorrect. My machine may only support Python 3.9, and other dependency packages are incorrectly adapted.

**Comment by Zhang1n** [comment]
> Can you try using a more recent version of SciPy @Zhang1n ?

The reason I am compiling this version of the rpm package is that the latest version of scipy available in the software repositories of other Linux distributions, such as Fedora and CentOS, is 1.11.

**Comment by Zhang1n** [comment]
> Please tell us the OS you're using and the Python version you are building on. A debug process by us would typically use docker to start an image, installing the correct Python version in the easiest way possible, making a venv, pip installing the dependencies, then trying to build from source.
> 
> Other ways of debugging are more difficult and time consuming.

python 3.9
The same error is reported when the source code package is used for compilation.

**Comment by andyfaff** [comment]
And the OS?

**Comment by rgommers** [comment]
This is something very basic that is broken in your environment setup I'm sure. Cython 0.29.35 works just fine with SciPy 1.11.3, there are no known issues. SciPy 1.11.3 builds fine as an RPM too (see, e.g., here for Fedora: https://koschei.fedoraproject.org/package/scipy?collection=f40).

We need full build logs to be able to say more.

**Comment by Zhang1n** [comment]
> This is something very basic that is broken in your environment setup I'm sure. Cython 0.29.35 works just fine with SciPy 1.11.3, there are no known issues. SciPy 1.11.3 builds fine as an RPM too (see, e.g., here for Fedora: https://koschei.fedoraproject.org/package/scipy?collection=f40).
> 
> We need full build logs to be able to say more.

ok thank u,I'll look at more specific reasons.

**Comment by Zhang1n** [comment]
> > This is something very basic that is broken in your environment setup I'm sure. Cython 0.29.35 works just fine with SciPy 1.11.3, there are no known issues. SciPy 1.11.3 builds fine as an RPM too (see, e.g., here for Fedora: https://koschei.fedoraproject.org/package/scipy?collection=f40).
> > We need full build logs to be able to say more.
> 
> ok thank u,I'll look at more specific reasons.

I guess the problem is that the pythran version does not adapt

**Comment by rgommers** [comment]
The `pythran` version in `pyproject.toml` for each release should work. Versions outside the given version constraints in that file may or may not work.

**Comment by andyfaff** [comment]
**please tell us the OS**

**Comment by Zhang1n** [comment]
> **please tell us the OS**

euler

**Comment by rgommers** [comment]
I'll close this issue as invalid. This should all work as expected, and the requested info to be able to help is not being given.
