### ISSUE TITLE
ENH: add one-hot special function or support broadcasting in `signal.unit_impulse`

### ISSUE THREAD

**Issue by NeilGirdhar** [scipy/scipy#20442]
The [one-hot function](https://jax.readthedocs.io/en/latest/_autosummary/jax.nn.one_hot.html) is a useful function in machine learning.  It would be really useful to have it in `scipy.special`, in particular, because of SciPy's commitment to support the Array API.  Adding the function to scipy would mean that users of the Array API, and users of various machine learning libraries (pytorch, tensorflow, jax) could use the function.

I think this function is special because it is one of the only special functions not provided by scipy that I use in my Efax library, the others being `abs_square` ([open issue](https://github.com/numpy/numpy/issues/13179) in NumPy), `softplus` ([being added](https://github.com/scipy/scipy/pull/18605) to SciPy) and `inverse_softplus` (not proposed).

**Comment by NeilGirdhar** [comment]
> Array creation and manipulations are fundamentally much more performant than us non-natively manipulating indices at Cython or Python level.

I'm not sure if it was clear from the issue text, but the reason I'm proposing it for scipy is because of the Array API.  Once it takes hold, for my library to be Array API compliant, it can no longer use the Jax library code.  I will be forced to either write my own functions or use an Array API library.  Since I'm already using SciPy, and since SciPy intends to port most of its special functions to the Array API, I thought it made sense to ask for the function to be added here.

> ```python
> A = np.zeros([len(inds), num_classes])
> A[np.arange(len(inds)), inds] = 1
> ```

As far as I can tell, "fancy indexing" is [not yet supported](https://data-apis.org/array-api/latest/API_specification/indexing.html) by the Array API.  See discussions:
https://github.com/data-apis/array-api/issues/177
https://github.com/data-apis/array-api/issues/410
https://github.com/data-apis/array-api/issues/669

> Array API in my understanding is not meant for adding all missing functions to SciPy but this should probably go into Array API spec. 

The Array API people have consistently said that these kinds of library functions belong outside the Array API.  That may change one day, but for now, I didn't think it was worth even trying to get them to accept this.

> Also if we accept it, it should go to `linalg.special_matrices`

Okay interesting, didn't know about this, thanks.  Now that I think about it, I could do this with [unit_impulse](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.unit_impulse.html) if unit-impulse supported broadcasting in `idx`--not sure if that would be more popular.

**Comment by ilayn** [comment]
> Once it takes hold, for my library to be Array API compliant, it can no longer use the Jax library code.

No it does. You can use exactly what we are doing with first getting the array namespace and check if it has linalg in it and push it there. SciPy is not the lynchpin of anything. This is something Array API folks really need to make it crystal clear in my opinion. SciPy should not (and could not) be the only library providing anything that is missing from the spec. 

> As far as I can tell, "fancy indexing" is [not yet supported](https://data-apis.org/array-api/latest/API_specification/indexing.html) by the Array API.

Then honestly, I don't know how we can implement anything on our side without indexing. There must be more to that discussion but let's wait for other opinions first before I appear like I represent all SciPy folks.

**Comment by ev-br** [comment]
> This is something Array API folks really need to make it crystal clear in my opinion. SciPy should not (and could not) be the only library providing anything that is missing from the spec.

+1.
When it's in the spec, scipy may implement it, not the other way around. 

Until it is the array API spec, we'd need a different argument as to why it's worth including in scipy.

**Comment by ilayn** [comment]
Yes, let me be a bit more specific. So this Array API is made for all supporting libraries right? Not just SciPy. That means all participating libraries should have some sort of a mechanism to distinguish the namespace. We do it typically with code like this (taken from #19260) ; 

```python
    xp = array_namespace(a, b)
    if check_finite:
        a = _asarray(a, check_finite=True, xp=xp)
        b = _asarray(b, check_finite=True, xp=xp)
    if is_numpy(xp):
        return _solve(a, b, lower=lower, overwrite_a=overwrite_a,
                      overwrite_b=overwrite_b, assume_a=assume_a, transposed=transposed)
    unsupported_args = {
        'lower': lower,
        'assume_a': assume_a != 'gen',
        'transposed': transposed
    }
    if any(unsupported_args.values()):
        xp_unsupported_args(unsupported_args)
    if hasattr(xp, 'linalg'):
        dtype = xp.result_type(a, b, xp.float32)
        a = xp.astype(a, dtype)
        b = xp.astype(b, dtype)
        return xp.linalg.solve(a, b)
    a = np.asarray(a)
    b = np.asarray(b)
    return xp.asarray(_solve(a, b))

```

This is a mechanism all participating libraries have to do apparently because otherwise it's just SciPy that can do this. That is what we mean. So we are trying to support Array API but if something is not there, it shouldn't be automatically, "it should go to SciPy". That is I am trying to convey.

**Comment by lucascolley** [comment]
> Or else do you expect a [special function extension](https://data-apis.org/array-api/latest/extensions/index.html) to be specified one day?

See https://github.com/data-apis/array-api/issues/725.

I don't think that the question of whether this could be included in SciPy is unreasonable. For context @NeilGirdhar , see https://github.com/scipy/scipy/issues/19404. @steppi and @izaid are working on making the current implementations in `scipy.special` more portable (mainly for CUDA right now) via C++, with a vision to breaking the module out into a separate package which could see wider use. The goal (as far as I understand) would be for a subset of this module to materialise in the spec as an extension module, and libraries would have a reference implementation in C++ which they could use or take inspiration from.

---

> Already, SciPy has a broad variety of useful functions (including the special functions) that are not in the spec, but will support the Array API. This suggestion is about adding one more useful function.

The concern from SciPy's side is valid - we can't have "one more useful function" turn into "one more useful function" x 50 unfortunately.

---

> This is a mechanism all participating libraries have to do apparently because otherwise it's just SciPy that can do this. That is what we mean. So we are trying to support Array API but if something is not there, it shouldn't be automatically, "it should go to SciPy". That is I am trying to convey.

Indeed, @ilayn is correct here that from the array library interoperability perspective, it doesn't matter whether such a function belonged in SciPy or in a downstream package. The real question is whether this best belongs within the scope of `scipy.linalg.special_matrices`, within the scope of `scipy.special` as it undergoes its current transformation, or downstream (or perhaps upstream, in an extension of the array API spec).

**Comment by NeilGirdhar** [comment]
Makes sense.  Didn't know about the special functions extension!  But I guess from this discussion, this wouldn't belong there.  Not sure where it belongs.

**Comment by izaid** [comment]
> Makes sense. Didn't know about the special functions extension! But I guess from this discussion, this wouldn't belong there. Not sure where it belongs.

Yeah, it's a good question. I think this is really something that should be implemented at the Python level, essentially using what @ilayn put above. Pretty sure it could be done with the array API as it is now, including broadcasting. But where to put it, who knows!
