### ISSUE TITLE
BUG: ModuleNotFoundError: No module named scipy.special._cdflib with SciPy-1.13.0

### ISSUE THREAD

**Issue by connorferster** [scipy/scipy#20451]
### Describe your issue.

When attempting to create an executable with pyinstaller, I was able to create the executable. When I tried to run the executable, I then received a terminal screen with a traceback that ended with the line in the title.

I downgraded the scipy version in my environment to 1.12.0 and the exe worked as expected.

I think this is the same problem encountered here: https://github.com/Nuitka/Nuitka/issues/2807

### Reproducing Code Example

```python
Install scipy 1.13.0 into an empty conda environment, build an executable project that relies on scipy with pyinstaller, run .exe from Windows explorer.
```

### Error message

```shell
ModuleNotFoundError: No module named scipy.special._cdflib with SciPy-1.13.0

(Cannot paste full traceback because it flashes on the launched terminal then disappears)
```

### SciPy/NumPy/Python version and system information

```shell
OS: Windows 10
Python: 3.11.8
Scipy: 1.13.0
```

**Comment by andyfaff** [comment]
That'll probably be a pyinstaller hook that needs updating (i.e. not a scipy bug).

**Comment by andyfaff** [comment]
The fix to the pyinstaller hook is in https://github.com/pyinstaller/pyinstaller/commit/5fe069177c9fda8ae7e362cdaa5b39c5b64fe4f5,

Added in https://github.com/pyinstaller/pyinstaller/pull/8394. So I guess it'll be available in the next pyinstaller release.

(it's not a scipy bug).
