### ISSUE TITLE
BUG: signal.iirfilter: overflow for integer input

### ISSUE THREAD

**Issue by Skylake-dev** [scipy/scipy#20455]
I was playing around with filters and found an integer overflow in this code

https://github.com/scipy/scipy/blob/6881ba29e3a7d1dcadf07454adf663946ccb43f0/scipy/signal/_filter_design.py#L2564-L2568

Minimal code to reproduce:
```python
from scipy.signal import butter

fs = 6250000000     # 6.25 Gs/s
low = 1000000000    # 1 GHz
high = 1100000000   # 1.1GHz

filter = butter(20, Wn=[low, high], btype='pass', fs=fs)

>> ValueError: filter critical frequencies must be greater than 0
```

This is because of the line `Wn = asarray(Wn)` automatically assigns the dtype to int32 and if `fs` is given the scaling step fails
```python
 Wn = asarray(Wn)   # dtype is int32
 if fs is not None: 
     # before Wn = [1000000000 1100000000]
     Wn = 2*Wn/fs
     # after Wn = [ 0.32    -0.33519477], 1.1billion overflows when doing 2*Wn

 if numpy.any(Wn <= 0):    # this returns True and throws error
        raise ValueError("filter critical frequencies must be greater than 0")
```
This problem is not present if the frequency are noted in scientific notation (e.g. `1e9`) since they are converted to float32 by the `asarray` function,  but i think that is worth reporting anyway because the inputs are correct.

The solution could be:

- assign specific dtype during the conversion `Wn = asarray(Wn, dtype=np.float32)`
- do the operations in order `Wn = Wn / (fs / 2)`

I am using the Python 3.12.0,  `scipy==1.13.0` and `numpy==1.26.4`.

**Comment by lucascolley** [comment]
Thanks for the report @Skylake-dev . 

> do the operations in order Wn = Wn / (fs / 2)

This is probably worth doing, regardless of if the dtype behaviour changes.

In general, 'dtype_in == dtype_out' is desirable, unless you have a case where integer input doesn't really make sense and is only supposed to be a shorthand for float input. I'm not sure what the case is here.

**Comment by lucascolley** [comment]
With that said, a PR to reorder the operations is more than welcome if you'd like to contribute!

**Comment by Skylake-dev** [comment]
Thanks for the quick response, i will open the PR
