### ISSUE TITLE
MAINT: more potential cleanups related to version bumps

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#20458]
Minimum NumPy version is high enough to remove

https://github.com/scipy/scipy/blob/efff26b05689a92b3771ec3142c8a2524d78a516/scipy/stats/tests/test_multivariate.py#L3776-L3779

Minimum NumPy version is wrong here (see `pyproject.toml` for truth)

https://github.com/scipy/scipy/blob/efff26b05689a92b3771ec3142c8a2524d78a516/scipy/__init__.py#L67-L69

`pytest` `3.6.0` is six years old and the last stable release prior to it is not functional with our current test suite (I tried with `3.5.1`, it errored out as expected).

https://github.com/scipy/scipy/blob/efff26b05689a92b3771ec3142c8a2524d78a516/scipy/conftest.py#L36-L39
https://github.com/scipy/scipy/blob/efff26b05689a92b3771ec3142c8a2524d78a516/scipy/sparse/tests/test_base.py#L5037-L5040

**Comment by aologan** [comment]
>  Hi new to this. Just wanna make sure I understand. For the one above you want lines 3777 - 3779 removed
> Minimum NumPy version is high enough to remove
>https://github.com/scipy/scipy/blob/efff26b05689a92b3771ec3142c8a2524d78a516/scipy/stats/tests/test_multivariate.py#L3776-L3779

**Comment by lucascolley** [comment]
> Hi new to this. Just wanna make sure I understand. For the one below you want lines 3777 - 3779 removed

Yep, that's right 👍
