### ISSUE TITLE
DOC: some likely changes to release process docs

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#20461]
A few small things I can think of that may need changing/clarifying at: https://scipy.github.io/devdocs/dev/core-dev/index.html#making-a-scipy-release

- [ ] "Propose a release schedule on the scipy-dev mailing list." -> switch to one of the discourse venues now?
- [ ] https://scipy.github.io/devdocs/dev/core-dev/index.html#updating-the-version-switcher -- I think we're allowed to only do this on `main`? Should perhaps be clarified a little, don't think it was needed on the release branch in last cycle.
- [ ] https://scipy.github.io/devdocs/dev/core-dev/index.html#updating-upper-bounds-of-dependencies `setup.py` is gone, so remove that subsection entry
- [ ] "Send an email announcing the release to the following mailing lists:" https://scipy.github.io/devdocs/dev/core-dev/index.html#wrapping-up ; maybe the appropriate discourse venues now? What about `python-announce`, discourse equivalent for that? 

I guess there is an https://discuss.scientific-python.org/c/announcements/20 section vs. project-specific sections, so maybe pick what makes most sense for the notifications. Good to just pick what is desired ahead of time so there's no confusion when I actually have to do it.

Some of the other uses of `setup.py` in `core-dev` doc page can probably be modernized or removed as well. That's seperate from the "distutils equivalents" section somewhere else, where discussion of old vs. new way is maybe still relevant for a bit.

**Comment by lucascolley** [comment]
> Some of the other uses of setup.py in core-dev doc page can probably be modernized or removed as well.

Some of this in gh-20199

**Comment by tupui** [comment]
> https://discuss.scientific-python.org/c/announcements

Yep this is for that 👍 and I also always send a message on Twitter and I think @melissawm does the Mastodon one.

For the version switcher, yes the file on main is used. It allows us to be flexible and add dev versions etc. Otherwise we would need to re upload new docs. Though you know I would like to change our process there, but another discussion.
