### ISSUE TITLE
BUG: `TestNNLS.test_nnls_inner_loop_case1` fails with MKL

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#20470]
This already showed up in the 1.13 [release PR](https://github.com/conda-forge/scipy-feedstock/pull/271) on the conda-forge feedstock, but was deferred at the time. Further [testing](https://github.com/conda-forge/scipy-feedstock/pull/273) showed that it only happens with the MKL-flavour of BLAS/LAPACK, and even more particularly, only in the presence of some AVX512 instructions:

```
_____________________ TestNNLS.test_nnls_inner_loop_case1 _____________________
[gw0] win32 -- Python 3.9.19 %PREFIX%\python.exe
..\_test_env\lib\site-packages\scipy\optimize\tests\test_nnls.py:101: in test_nnls_inner_loop_case1
    dact, _ = nnls(W @ A, W @ k)
        2.23606798,  2.23606798,  1.        ,  1.41421356,  1.73205081,
        1.        ,  1.41421356])
..\_test_env\lib\site-packages\scipy\optimize\_nnls.py:93: in nnls
    raise RuntimeError("Maximum number of iterations reached.")
E   RuntimeError: Maximum number of iterations reached.
        A          = array([[ 5.19615242,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 2.8284271...   , -1.        ],
       [ 2.82842712,  2.82842712,  2.82842712, ...,  2.82842712,
         2.82842712,  2.82842712]])
        atol       = None
        b          = array([   0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,...         11.27887984,    8.05634274,    0.        ,    4.07622283,
          0.        ,    0.        ,    0.        ])
        m          = 67
        maxiter    = None
        mode       = -1
        n          = 67
        rnorm      = 0.0
        x          = array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.      ...       , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

FAILED optimize/tests/test_nnls.py::TestNNLS::test_nnls_inner_loop_case1 - RuntimeError: Maximum number of iterations reached.
```

**Comment by h-vetinari** [comment]
This remains an issue for SciPy 1.13.1, now also on linux (again with MKL). It doesn't seem to appear on the CI agents _without_ AVX512F/AVX512CD (i.e. those with "only" AVX2).

**Comment by rgommers** [comment]
This test was recently added, in gh-20168, and deals with a tiny tolerance to avoid an infinite loop issue. Which is typically the kind of thing that can be affected by SIMD instruction set. In optimize/tests/test_nnls.py`, there is:
```
        # Small perturbations can already make the infinite loop go away (just
        # uncomment the next line)
        # k = k + 1e-10 * np.random.normal(size=N)
```
Could you try bumping up the `1e-10` number to the point where the problem goes away?

**Comment by ilayn** [comment]
I will rewrite this anyways very soon (there are also other minor issues that I did not address for performance etc). 

Having said that, this is a bit of a tricky situation since there is no guarantee that this function should return a result at all times. The old one returns correct result for this particular case but you can trip that one with another problem that the new one solves. Hence it is a bit of a red herring. So whatever makes it go away is OK with me and I'll revert it to original after the rewrite.

**Comment by h-vetinari** [comment]
Can confirm that uncommenting
```
k = k + 1e-10 * np.random.normal(size=N)
```
makes the test pass where it (reproducibly) failed before. 🥳
