### ISSUE TITLE
DEP: deprecate and remove remaining usages of slur-adjacent "trapz"

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#20486]
I am not finding any other appearances of these terms except for `trapz`, which is still allowed as an alias for the trapezoidal distribution and as a `method` option of `quad_vec`. (Those uses don't appear to have been deprecated.)

_Originally posted by @mdhaber in https://github.com/scipy/scipy/pull/20278#pullrequestreview-1944140754_

**Comment by j-bowhay** [comment]
I will address this before the next release if nobody gets there first

**Comment by rgommers** [comment]
thanks @h-vetinari 

> which is still allowed as an alias for the trapezoidal distribution

IIRC we kept it as an undocumented alias when introducing `trapezoidal` to avoid users having to write if-else constructs depending on SciPy version. That is quite a few releases ago, so +1 for the proposal deprecations now.

**Comment by h-vetinari** [comment]
I'm going to close this one as fixed by #20716; we'll track removal in the deprecation meta-issue.

**Comment by j-bowhay** [comment]
@h-vetinari the alias for the trapezoidal distribution still remains

**Comment by h-vetinari** [comment]
Yes, but it got deprecated, which is what this issue was about. I also said that the actual removal (after two releases) can be tracked in the meta-issue.

So I don't see what purpose this issue still serves.

**Comment by h-vetinari** [comment]
Ugh. Why are we not doing these at the same time. Let's deprecate both in 1.14 please

**Comment by j-bowhay** [comment]
> Ugh. Why are we not doing these at the same time. Let's deprecate both in 1.14 please

Politely, I would ask in the future you consider the tone of such comments.

**Comment by h-vetinari** [comment]
The point is not to separate things that go together. If you do one without the other (like for the `special.comb` thing as well), it just creates yet more work. I don't mind _when_ these things land, but it's pointless to split the same deprecation across PRs, much less releases. Let's avoid half measures.

**Comment by j-bowhay** [comment]
> The point is not to separate things that go together. If you do one without the other (like for the `special.comb` thing as well), it just creates yet more work. I don't mind _when_ these things land, but it's pointless to split the same deprecation across PRs, much less releases. Let's avoid half measures.

Of course, we are allowed our own _opinions_ on how things should be done. I am merely asking that we avoid unnecessary emotive language when addressing each other.
