### ISSUE TITLE
DOC: linalg.solve_discrete_lyapunov: dead reference link

### ISSUE THREAD

**Issue by forgi86** [scipy/scipy#20492]
### Issue with current documentation:

Reference [1] of the documentation of solve_discrete_lyapunov (https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve_discrete_lyapunov.html) points to a broken link. 

In any case, I do not see any reference to lyapunov functions in that book (that I found at this link: http://mayoral.iae-csic.org/timeseries2021/hamilton.pdf)

### Idea or request for content:

I have found the direct formula explicitly written down only on Wikipedia: https://en.wikipedia.org/wiki/Lyapunov_equation#Discrete_time

It is also reported in appendix A.2 of this preprint of mine: https://arxiv.org/pdf/2403.14833.pdf

**Comment by j-bowhay** [comment]
PR with any link fixes/documentation improvements well come

**Comment by afraz98** [comment]
I'm new to open source and looking to contribute to this project. Mind if I open a PR?
