### ISSUE TITLE
ENH: constants: Add Muon Gyromagnetic ratio

### ISSUE THREAD

**Issue by robertapplin** [scipy/scipy#20504]
### Is your feature request related to a problem? Please describe.

It would be useful to have the Muon gyromagnetic ratio as a constant in `scipy.constants.physical_constants`. Scipy already has the the gyromagnetic ratios for a neutron and proton. See here: https://docs.scipy.org/doc/scipy/reference/constants.html

### Describe the solution you'd like.

At the moment, I am needing to calculate the gyromagnetic ratio using the following code:

```py
from scipy.constants import elementary_charge, physical_constants

MUON_GYROMAGNETIC_RATIO = physical_constants["muon g factor"][0] * - elementary_charge / (2 * physical_constants["muon mass"][0] * 1e6)  # MHz / T
```

but I would like to do something like

```py
from scipy.constants import physical_constants

MUON_GYROMAGNETIC_RATIO = physical_constants["muon gyromag. ratio in MHz/T"][0]
```

**Comment by rgommers** [comment]
Cc @jakobjakobson13 for input/visibility.

**Comment by jakobjakobson13** [comment]
> Cc @jakobjakobson13 for input/visibility.

That's up to you. I, in my personal opinion, would only include the bare constants provided by CODATA (as it is a "higher" authority and therefore its selection of constants can be considered more "meaningful"/"correct"/"scientifically proven") in scipy.
From a practical point of view, the inclusion of a MUON_GYROMAGNETIC_RATIO is no big deal as it is one line.

**Comment by rgommers** [comment]
Thanks for the proposal @robertapplin and for the feedback @jakobjakobson13.

> I, in my personal opinion, would only include the bare constants provided by CODATA (as it is a "higher" authority and therefore its selection of constants can be considered more "meaningful"/"correct"/"scientifically proven") in scipy.

This has been our stance/policy on other feature requests for `scipy.constants` in the past. It hasn't come up in a few years, but I agree with your opinion here - there is no good way to draw a line otherwise. Hence I will close this issue.
