### ISSUE TITLE
BUG: special.spherical_in: derivative at `z=0, n=1` incorrect

### ISSUE THREAD

**Issue by PicoCentauri** [scipy/scipy#20506]
### Describe your issue.

When calculating the **derivative** of the modified spherical Bessel function of the first kind `scipy.special.spherical_in(n=1, z=0, derivative=True)` for order `n=1` at `z=0` one obtains `0`. However, at the origin this should be `1/3` as one can show analytically or simply verify by comparing the values to a numerical derivative.

The actual values (`derivative=False`) and the derivative for other orders look fine!

![spherical_in_deriv](https://github.com/scipy/scipy/assets/15192133/ebd86690-3646-4452-9b5e-be8c8c5f53b4)

### Reproducing Code Example

```python
from scipy.special import spherical_in
import numpy as np

z = np.linspace(0, 3, int(1e4))
n = 1

values = spherical_in(n, z, derivative=False)
derivatives_numerical = np.gradient(values, z)
derivatives_analytical = spherical_in(n, z, derivative=True)

print("Numerical derivative:", derivatives_numerical[0:4])
print("Analytical derivative:", derivatives_analytical[0:4])
```

### Error message

```shell
None
```

### SciPy/NumPy/Python version and system information

```shell
1.12.0 1.26.4 sys.version_info(major=3, minor=11, micro=9, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.11.1
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 14.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 14.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 12.1.0
  pythran:
    include directory: ../../pip-build-env-ewarq4oq/overlay/lib/python3.11/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cibw-run-73jfxkej/cp311-macosx_arm64/build/venv/bin/python
  version: '3.11'
```

**Comment by izaid** [comment]
This is correct. I initially thought this was related to https://github.com/scipy/scipy/pull/20483#event-12527781530, but it can't be because that was just merged now and this issue is from yesterday. We also hadn't touched the spherical Bessel functions until that PR, so it seems this may have been an issue for a while. Trying to trace it, I found this has actually been wrong since the spherical Bessel functions _were introduced_ into SciPy:

https://github.com/scipy/scipy/commit/6e80abd32930b459666f402e8d648447c4b910fb#diff-fd1a84b3fdbe5f4d5061866329e8b4f770275c45b83021292926d704527fb952R340

Will fix this soon as we can.

**Comment by PicoCentauri** [comment]
Thanks @izaid for sharing this insight. Based on your recent PR and if I tracked this down correctly we have to do some changes here:

https://github.com/scipy/scipy/blob/ac6bcaf00411286271f7cc21e495192c73168ae4/scipy/special/special/sph_bessel.h#L298-L308

I can do this if this is the correct function. I would also like to add a test for the derivative at `0` for all `n` to 

https://github.com/scipy/scipy/blob/ac6bcaf00411286271f7cc21e495192c73168ae4/scipy/special/tests/test_spherical_bessel.py#L145

**Comment by izaid** [comment]
> Thanks @izaid for sharing this insight. Based on your recent PR and if I tracked this down correctly we have to do some changes here:
> 
> https://github.com/scipy/scipy/blob/ac6bcaf00411286271f7cc21e495192c73168ae4/scipy/special/special/sph_bessel.h#L298-L308
> 
> I can do this if this is the correct function. I would also like to add a test for the derivative at `0` for all `n` to
> 
> https://github.com/scipy/scipy/blob/ac6bcaf00411286271f7cc21e495192c73168ae4/scipy/special/tests/test_spherical_bessel.py#L145

That's the correct function, certainly happy if you want to make these changes!
