### ISSUE TITLE
BUG: `eigh` fails for size 1 array with driver=evd

### ISSUE THREAD

**Issue by ogauthe** [scipy/scipy#20512]
### Describe your issue.

Hi! I found that `evd` driver crashes for size-1 array due to lwork computation. Other drivers are fine.

I think the simplest would be to deal with size 1 at the same moment as size 0.

### Reproducing Code Example

```python
import numpy as np
import scipy.linalg as la

a = np.ones((1, 1))
s, u = la.eigh(a, driver="evd")
```

### Error message

```shell
error: (lwork>=(compute_v?1+6*n+2*n*n:2*n+1)) failed for 3rd keyword lwork: dsyevd:lwork=1
```

### SciPy/NumPy/Python version and system information

```shell
python `3.10.10`
numpy `1.23.5`
scipy `1.10.1` # (also present in dev)
```

**Comment by ev-br** [comment]
Yup, the f2py check was too strict. See gh-20516 for a fix.
