### ISSUE TITLE
CI/BLD: Nightly wheel builds failing for macOS x86_64

### ISSUE THREAD

**Issue by thalassemia** [scipy/scipy#20523]
The nightly x86_64 macOS wheel build failed for the past few days because the deprecated macOS 11 runner does not have Clang 14 (gh-20478). This is fixed by gh-20510, but I could also create a separate PR to bump the requested OS version.

Also, I noticed that [the newest aarch64 Linux wheels](https://anaconda.org/scientific-python-nightly-wheels/scipy/files) are from 5 days ago. The Cirrus jobs responsible for building them failed on gh-20510, so the nightlies might also be failing.

**Comment by andyfaff** [comment]
The cirrus cron job runs once a week. Its last build was successful, https://cirrus-ci.com/build/6248358254215168.

I'll make a PR to deal with the macos version now.

**Comment by rgommers** [comment]
> The Cirrus jobs responsible for building them failed on [gh-20510](https://github.com/scipy/scipy/pull/20510), so the nightlies might also be failing.

I've noticed a bunch of connectivity issues on Cirrus CI recently, usually in the cloning step. Not sure what's up with that; the automatic retry that Cirrus does usually works, but not always.
