### ISSUE TITLE
DOC/DEV/MAINT: review distributing section of core-dev guide

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#20552]
As a follow-up to gh-20199, there are some sections of https://scipy.github.io/devdocs/dev/core-dev/index.html#distributing which I don't feel confident updating myself. Some parts are clearly out of date, like a reference to `setup.py`, but the parts about building wheels and supported dependency versions are slightly over my head, hence I have left them alone for now. It would be good to bring them up to date.

I have similarly left the 'releasing' section alone, but it makes sense for the release manager to have discretion over when that is due an update.

**Comment by tupui** [comment]
Pinging you on this now @tylerjereddy as you are in the release process.
