### ISSUE TITLE
DOC: document switch from mailing list to discourse

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#20603]
Putting a milestone on this so that it isn't forgotten.

**Comment by tupui** [comment]
Are you or @melissawm sending a final email to the list? Then we need to put it in read only mode. I can do both if wanted.

**Comment by tupui** [comment]
Fire at will 🍾🙌

**Comment by lucascolley** [comment]
done https://mail.python.org/archives/list/scipy-dev@python.org/message/YC4DMG5JHU3KQARWBVZNQN373IMN3K4B/

**Comment by tupui** [comment]
And done 🎉 I set a bounce message and tested it. I will make a Tweet

**Comment by tupui** [comment]
Closing as I don't think we forgot anything now and no complains so far.

**Comment by lucascolley** [comment]
this isn't done - there are still various references to the mailing list in the docs.

**Comment by tupui** [comment]
ok, I will remove that today then.
