### ISSUE TITLE
BUG: io: `loadmat` does not load the full file

### ISSUE THREAD

**Issue by giulia-pall** [scipy/scipy#20626]
I am loading data.mat into Python using the loadmat function.
I am missing some data, specifically I have 89823 samples in Matlab and I get 83741 samples in Python.
This loading is done at the beginning of the processing, so the data.mat have not been processed yet in any way.
I also do not know if the samples are lost all in the beginning or all at the end or randomly.

No error message is given during the script run.

scipy version: 1.13.0
Python version: 3.11.9

**Comment by matthew-brett** [comment]
Can you share the file?

**Comment by giulia-pall** [comment]
Sorry, I cannot.
It might contain sensitive information.

**Comment by matthew-brett** [comment]
We need to be able to replicate the problem in order to work out what's going on.

**Comment by matthew-brett** [comment]
Perhaps you can strip out everything except the variable in question, and confirm you have the same problem, before sharing.   If not, we will close this issue, but feel free to reopen if you have something we could reproduce with.
