### ISSUE TITLE
DOC: Suggested improvement to interp2d transition guide

### ISSUE THREAD

**Issue by telegraphic** [scipy/scipy#20620]
### Issue with current documentation:

The [current documentation](https://scipy.github.io/devdocs/notebooks/interp_transition_guide.html) does not mention that `interp2d` has a default `kind='linear'` kwarg:

```python
class scipy.interpolate.interp2d(x, y, z, kind='linear', copy=True, bounds_error=False, fill_value=None)
```

while the suggested replacement, `RectBivariateSpline`, has a default `ky=3` kwarg:

```python
class scipy.interpolate.RectBivariateSpline(x, y, z, bbox=[None, None, None, None], kx=3, ky=3, s=0)
```

That is, the default spline degree differs. 

### Idea or request for content:

A simple fix is to note that the default
```python
f = interp2d(x, y, z)
```
uses linear spline, but 
```python
r = RectBivariateSpline(x, y, z.T)
```
uses a cubic spline as default. Explicitly mention the required kwargs that need to be added to `RectBivariateSpline` to make it match the default `interp2d` function.

Maybe add a little table that shows how to get identical results, e.g.

| interp2d | RectBivariateSpline |
|----------|--------------------|
| no kwargs   | kx, ky = 1 | 
| kind='linear' | kx, ky = 1 |
| kind='cubic' | kx, ky = 3 |

Hope this doc suggestion can help others. I suspect the impending deprecation of `interp2d` is going to cause a fair few codes to catch on fire, so really pleased y'all have written the transition guide :pray:.

**Comment by ev-br** [comment]
Would you be interested in sending a pull request with this clarification?

**Comment by ev-br** [comment]
Thank you @telegraphic , your table is now live in the docs!
