### ISSUE TITLE
DOC: Specify cut-off frequency in firwin as half-ampltude vs half-power

### ISSUE THREAD

**Issue by gerazov** [scipy/scipy#20638]
### Issue with current documentation:

The documentation could be made more clear that when designing a filter with `firwin` the cutoff-frequency is half-amplitude, i.e. `20 * np.log10(abs(signal.freqz(b))` gives -6 dB at the cutoff rather than -3 dB.

For IIR desing via `signal.iirdesign` the cutoff is half-power, so -3 dB. This could also be explicitly stated.

### Additional context (e.g. screenshots, GIFs)

```python
import numpy as np
from matplotlib import pyplot as plt
from scipy import signal as sig

fs = 16000
b = sig.firwin(101, 2500, fs=fs)
f, h_fft = sig.freqz(b, fs=fs)
h_amp = 20 * np.log10(np.abs(h_fft))
plt.figure()
plt.plot(f, h_amp)
plt.grid()

b, a = sig.iirfilter(15, 2500, btype="low", fs=fs)
f, h_fft = sig.freqz(b, a, fs=fs)
h_amp = 20 * np.log10(np.abs(h_fft))
plt.plot(f, h_amp)
plt.axis([2100, 2900, -10, 2])
plt.legend(["FIR", "IIR"])
```

<img src="https://github.com/scipy/scipy/assets/15214418/87fedbf9-5470-448a-ac4f-0d45afaeac24" width="400px">

**Comment by zpotthoff** [comment]
Hi, is this issue still open? I'd be happy to work and submit a PR for it.
Thanks!

**Comment by lucascolley** [comment]
Yes, the issue is still open, please feel free to submit a PR @zpotthoff !
