### ISSUE TITLE
ENH: Enable searching in log-space for optimization problems

### ISSUE THREAD

**Issue by willov** [scipy/scipy#20650]
### Is your feature request related to a problem? Please describe.

In certain optimization problems, it has been shown that searching in log-space improves the performance of the optimization (e.g. in [Villaverde 2017](https://academic.oup.com/bioinformatics/article/35/5/830/5078478), Fig. 2C). Today, we have to manually convert the bounds and x0 to log-scale, and wrap the objective function in a function which converts back from log-scale. 

### Describe the solution you'd like.

It would be great if we could provide a keyword argument to the optimizations solvers to instead do this conversion internally. 

### Describe alternatives you've considered.

The current alternative as mentioned is to convert the bounds and objective function manually, which works but is inconvenient. 

### Additional context (e.g. screenshots, GIFs)

Here is an example of the solution today: 

```python
x0 = [100, 10, 1000, 1]

# Convert to log-scale
bounds_log = Bounds([np.log(1e-5)]*len(x0), [np.log(1e5)]*len(x0))
x0_log = np.log(x0)

# Convert back
def obj_log(x):
    obj(np.exp(x))

# Setup objective function
def obj(x):
    # Computationally expensive simulation, and other logic, here
    return f

# Run optimization
res = differential_evolution(func=obj_log, bounds=bounds_log, x0=x0_log)
```

It would be nice if we instead could do something like this: 

```python
x0 = [100, 10, 1000, 1]
bounds = Bounds([1e-5]*len(x0), [1e5]*len(x0))

# Setup objective function
def obj(x):
    # Computationally expensive simulation, and other logic, here
    return f

# Run optimization
res = differential_evolution(func=obj, bounds=bounds, x0=x0, search_in_space='log')   # search_in_space='log' | 'log10' |'linear'
```

Or perhaps even better, also give which indices of x to search in what space, or to specify the space for each parameter. For example (assuming the same x0 as above): ['log10', 'log10', 'log', 'lin'].

**Comment by andyfaff** [comment]
Yes, this is functionality that would be useful. However, I think this kind of thing is better carried out in user space. The changes would probably need to be rolled out over all the minimize methods as well as the global optimizers. That's a large task to do within the existing minimisers. Some sort of wrapper might work well.

**Comment by dschmitz89** [comment]
In addition to what @andyfaff mentioned, some of our optimizers already apply a scaling of the parameter space to the unit cube (at least DIRECT). While in principle a good idea, I agree that auto log scaling is unfeasible with the current code base.

One thing we could do is add an example to the tutorials where this scaling is applied in user land. What do you think?
