### ISSUE TITLE
DOC: A typo in ValueError raised by signal.iirdesign

### ISSUE THREAD

**Issue by budjen-jovan** [scipy/scipy#20683]
### Issue with current documentation:

Currently, in signal.iirdesign there is an error message being thrown:
`
raise ValueError("wp and ws must have one or two elements each, and"
                         f"the same shape, got {wp.shape} and {ws.shape}")
`
There is a missing whitespace between the two strings (github messes up the formatting, I can't figure out how to format this properly.
A resulting error message being thrown is 

> ValueError: wp and ws must have one or two elements each, andthe same shape, got (4,) and (2,)

### Idea or request for content:

Again, looking at the existing solutions in the code (although they are not very consistent about this), I suggest adding a whitespace to the end of the first string or the beginning of the other string. There is a slight styling problem where the two solutions are being used interchangably - it doesn't break functionality in any way, it's just not pretty to look at. I suppose I can fix that, it's trivial, but I'm not sure if that's a change worth doing, do let me know.

**Comment by lucascolley** [comment]
PR welcome if you would like to fix it!

**Comment by budjen-jovan** [comment]
Absolutely, will do in a sec
