### ISSUE TITLE
ENH: Reintroduce Apple Accelerate support

### ISSUE THREAD

**Issue by krono-i2** [scipy/scipy#20691]
### Is your feature request related to a problem? Please describe.

Support for Apple Accelerate framework was dropped due to the old version of LAPACK compatibility provided by Apple.

### Describe the solution you'd like.

Now Apple provides compatibility with LAPACK 3.9.1. See https://developer.apple.com/documentation/accelerate/blas/

**Comment by andyfaff** [comment]
We're already reintroducing it. The next release will have wheels built with accelerate. The ci tests with accelerate, and it's straightforward to build locally with accelerate. Wheels with accelerate support will be for macOS 14.x and up. I can never remember if x is 0 or 3.

**Comment by ilayn** [comment]
Just to remind the reasoning; the more important reason was that Apple dropped support for Accelerate and did not fix any bugs.
