### ISSUE TITLE
ENH: spatial: Matrix multiplication of Rotation

### ISSUE THREAD

**Issue by moradpur** [scipy/scipy#20690]
### Is your feature request related to a problem? Please describe.

In scipy.spatial.transform.Rotation.__mul__ , If p and q are two rotations, and both p and q contain N rotations, each rotation p[i] is composed with the corresponding rotation q[i], and the output contains N rotations which is not suitable for matrix multiplication and machine learning purposes.

### Describe the solution you'd like.

For machine learning purposes, the matrix multiplication of multiple rotations should be possible. I suggest that it gives N*N rotations instead of N Rotation.

### Describe alternatives you've considered.

Instead of changing` __mul__` method you can add matmul method which is available in numpy too. However, using similarity of rotations as `(rotation_1*rotation_2.inv()).magnitude()` and giving a covariance N*N matrix will be a blockbuster feature.

**Comment by scottshambaugh** [comment]
I don't think we should make this change, since it would break standard broadcasting.

Broadcasting is also the way that you can make your desired behavior work, by storing the rotations in numpy arrays. Here's an example of how to get what you're looking for:

```
import numpy as np
from scipy.spatial.transform import Rotation as R

rotations_array_4 = np.array(R.random(4))[:, np.newaxis]  # Shape will be (4, 1)
rotations_array_3 = np.array(R.random(3))
result = rotations_array_4 * rotations_array_3 

print(result.shape)
# prints (4, 3), all Rotation objects
```

**Comment by scottshambaugh** [comment]
Or, to do your blockbuster feature 🙂, you can do the following:
```python
R3 = R.random(3, random_state=0)

rotations_array_3 = np.array(R3)
rotations_array_3_inv = np.array(R3.inv())
result = rotations_array_3[:, np.newaxis] * rotations_array_3_inv

vectorized_magnitude = np.vectorize(lambda x: x.magnitude())
mags = vectorized_magnitude(result)

print(mags)
''' prints out:
[[1.14439170e-16, 2.10407917e+00, 1.50255252e+00],
 [2.10407917e+00, 0.00000000e+00, 2.75493397e+00],
 [1.50255252e+00, 2.75493397e+00, 0.00000000e+00]]
'''
```

**Comment by scottshambaugh** [comment]
@nmayorov thoughts?

**Comment by nmayorov** [comment]
> In scipy.spatial.transform.Rotation.**mul** , If p and q are two rotations, and both p and q contain N rotations, each rotation p[i] is composed with the corresponding rotation q[i], and the output contains N rotations which is not suitable for matrix multiplication and machine learning purposes.

I think the current rules are most suitable for targeted engineering tasks (describe attitude of rotating frames, project or rotate vectors between the frames).

> For machine learning purposes, the matrix multiplication of multiple rotations should be possible. I suggest that it gives N*N rotations instead of N Rotation.

Just changing the `__mul__` rule is clearly not possible. As @scottshambaugh said the required broadcasting can be achieved by working with matrix (or possibly quaterion) representation of rotations.

> Instead of changing __mul__ method you can add matmul method which is available in numpy too. However, using similarity of rotations as (rotation_1*rotation_2.inv()).magnitude() and giving a covariance N*N matrix will be a blockbuster feature.

I believe this is the case where we can confidently recommend to implement the required logic on top what is already provided. I don't see how we can logically fit "outer product" broadcasting rules into `Rotation`.

**Comment by moradpur** [comment]
Actually, I have tried both of these solutions before. The problem is that they are much slower than just doing a for loop over the regular Rotation(single)*Rotation(Multiple).

**Comment by moradpur** [comment]
> Or, to do your blockbuster feature 🙂, you can do the following:
> 
> ```python
> R3 = R.random(3, random_state=0)
> rotations_array_3 = np.array(R3)[:, np.newaxis]
> rotations_array_3_inv = np.array(R3.inv())
> vectorized_magnitude = np.vectorize(lambda x: x.magnitude())
> angles = vectorized_magnitude(rotations_array_3 * rotations_array_3_inv)
> 
> # In one line:
> # angles = np.vectorize(lambda x: x.magnitude())(np.array(R3)[:, np.newaxis] * np.array(R3.inv()))
> 
> print(angles)
> ''' prints out:
> [[1.14439170e-16, 2.10407917e+00, 1.50255252e+00],
>  [2.10407917e+00, 0.00000000e+00, 2.75493397e+00],
>  [1.50255252e+00, 2.75493397e+00, 0.00000000e+00]]
> '''
> ```

**Comment by moradpur** [comment]
@scottshambaugh
Actually, I have tried both of these solutions before. The problem is that they are much slower than just doing a for loop over the regular Rotation(single)*Rotation(Multiple).
