### ISSUE TITLE
BUG: special: algorithmic Error in `ratevl` in `cephes/polevl.h`

### ISSUE THREAD

**Issue by ZhibingSun** [scipy/scipy#20697]
I am a PhD candidate in Applied Math from the University of Waterloo. I was investigating some numerical issues in my research when I found an algorithmic error for the function `ratevl` in `scipy / scipy / special / cephes / polevl.h`. It appears on `line 158`, which should be `i = M - N;` instead of `i = N - M;`. Here I give a brief explanation of what the function does and why there is a bug.
The function `ratevl` on `line 118` evaluates a rational function $\cfrac{P(x)}{Q(x)}$, where $P(x)$ and $Q(x)$ are polynomials of order $M$ and $N$ respectively. For $|x| > 1$, $P(x)$ and $Q(x)$ are evaluated by $\cfrac{1}{x}$ instead of $x$, using Horner's method as referenced on `line 55`.
Here I give a simple example to illustrate. Let $f_2(x) = a_2 x^2 + a_1 x + a_0$ be a second order polynomial. If $|x| > 1$, then the polynomial is evaluated in reverse order as polynomial in $\cfrac{1}{x}$.
That is, $\cfrac{f_2(x)}{x^2} = a_2 + a_1 \cdot\cfrac{1}{x} + a_0 \cdot\cfrac{1}{x^2} = (a_0 \cdot\cfrac{1}{x} + a_1)\cdot \cfrac{1}{x} + a_2$, thus $f_2(x) = ((a_0\cdot \cfrac{1}{x} + a_1)\cdot\cfrac{1}{x} + a_2) \cdot x^2$. In the code, $P(x) = num\textunderscore ans \cdot x^M$, $Q(x) = denom\textunderscore ans \cdot x^N$, thus $\cfrac{P(x)}{Q(x)} = \cfrac{num\textunderscore ans}{denom\textunderscore ans}\cdot x^{M - N}$, and $i$ on `line 158` should be $M - N$, not $N - M$.
In the boost implementation as referenced on `line 55`, it pre-processed to require $P(x)$ and $Q(x)$ to have the same order so that it's not an issue there. As on `line 60`, I believe the piece of code for the function `ratevl` is rewritten instead of copying from the reference directly, which is likely to be a reason for this error.

**Comment by lucascolley** [comment]
Hi @ZhibingSun , as a small ask, could you edit your post to enclose equations in backticks (this symbol `)? That should make it easier to read! (Or you can use $ signs for LaTeX too).

cc @steppi

**Comment by ZhibingSun** [comment]
Hi, I have updated my post as required, and thanks for letting me know that I can enclose equations and use LaTex. Please let me know if I need to provide more information.

**Comment by steppi** [comment]
Thanks for the bug report @ZhibingSun! It looks like this error goes back to when this function was first introduced. It seems no one noticed before you because `ratevl` is only used in one place in SciPy and in that case the numerator and denominator have the same degree.

https://github.com/scipy/scipy/blob/3559245f5438d81aad7dcb1ccfcca84ac3dc2b0f/scipy/special/special/cephes/lanczos.h#L83

Would you like submit a pull request with the fix?

**Comment by ZhibingSun** [comment]
Yes, I would love to contribute. Could you give me some guidance of how to submit a pull request?

**Comment by steppi** [comment]
> Yes, I would love to contribute. Could you give me some guidance of how to submit a pull request?

Great! Start with the [Contributor quickstart](https://docs.scipy.org/doc/scipy/dev/dev_quickstart.html)  in the Developer documentation, and then check out the *Development workflow* section. That should be enough to get started.

**Comment by ZhibingSun** [comment]
I followed `Contributor quickstart guide` and run command upto `python3 dev.py test`, but it gives me error `meson.build:84:0: ERROR: Compiler gfortran cannot compile programs.` I checked that gfortran exists on my system by running gfortran --version, which gives me `NU Fortran (GCC) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`
Could you tell me how I shall proceed?

**Comment by andyfaff** [comment]
Are you on windows or Linux? I suggesting trying to compile a really simple test program (c.f. hello world) to see if the compiler actually works.

**Comment by ZhibingSun** [comment]
I am on M1 mac Ventura 13.6.6.

**Comment by andyfaff** [comment]
How did you install gfortran? I've found homebrew to work.

**Comment by ZhibingSun** [comment]
I installed it from here. `https://github.com/fxcoudert/gfortran-for-macOS/releases`. As I mentioned in my previous post, I ran `gfortran --version` and it works.

**Comment by andyfaff** [comment]
Running that command doesn't necessarily mean that the compiler works. Try compiling and running a test program.

**Comment by fancidev** [comment]
> I followed `Contributor quickstart guide` and run command upto `python3 dev.py test`, but it gives me error `meson.build:84:0: ERROR: Compiler gfortran cannot compile programs.`

I can help you on this one because I use Mac M1 and have exactly the same error. I did some googling and it is related to XCode not adding some toolchain into some environment variable. The fix is to export some environment variable. The exact `export` command I need to check in my home PC and tell you tomorrow.

@ZhibingSun

**Comment by lucascolley** [comment]
<img width="745" alt="image" src="https://github.com/scipy/scipy/assets/51488791/9a63d6f4-7098-4d7c-ac4c-c053e9b3cd3d">

These two lines from http://scipy.github.io/devdocs/building/index.html#system-level-dependencies were enough for me.
