### ISSUE TITLE
CI: scipy installation failing in umfpack tests

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#20714]
### Describe your issue.

See a recent CI log: https://github.com/scipy/scipy/actions/runs/9085915867/job/24970362158?pr=20713

### Reproducing Code Example

```python
n/a
```

### Error message

```shell
n/a
```

### SciPy/NumPy/Python version and system information

```shell
n/a
```

**Comment by tylerjereddy** [comment]
The conda/mamba dependency resolver seems to be using Python `3.12` while that CI matrix entry intentionally specifies `python-version: ["3.11"]`. We do use the GHA script `conda-incubator/setup-miniconda@v3` with `python-version: ${{ matrix.python-version }}`, but perhaps the unpinned `python` version in `environment.yml` is starting to cause issues via `mamba env update -n scipy-dev -f environment.yml`. @h-vetinari is that plausible?

**Comment by h-vetinari** [comment]
> @h-vetinari is that plausible?

Yes. It needs to be pinned to 3.11 once the environment gets created, later updates will not change the python version in the environment unless explicitly asked (and since scikit-umfpack isn't yet [available](https://github.com/conda-forge/scikit-umfpack-feedstock/pull/36) for 3.12, it fails).
