### ISSUE TITLE
DOC: Scipy Documentation Pages Completely Down

### ISSUE THREAD

**Issue by aglaiawong** [scipy/scipy#20742]
### Issue with current documentation:

The documentation page is dead, cannot access to any documentation of scipy. 

### Additional context (e.g. screenshots, GIFs)

![image](https://github.com/scipy/scipy/assets/24940367/f15b93f1-c118-4317-a9bc-37d09445055d)

**Comment by ilayn** [comment]
Can you please remove the last dot from `docs.scipy.org.` and try again

**Comment by aglaiawong** [comment]
No. I didn't input extra full-stop. For example I searched from Google or Bing the for 'scipy genhyperbolic', and get redirected through these links for example: 
```
https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.genhyperbolic.html&ved=2ahUKEwjy0Njm15iGAxWdATQIHXfeADYQFnoECAcQAQ&usg=AOvVaw0PMNl4nkLNa_NBfWsb23gm

https://www.bing.com/ck/a?!&&p=ba903d6d99067eb6JmltdHM9MTcxNTk5MDQwMCZpZ3VpZD0wMTVkYjc0ZC1hMWU0LTZiYWItMDI2OS1hM2M5YTBiYjZhODYmaW5zaWQ9NTIwMw&ptn=3&ver=2&hsh=3&fclid=015db74d-a1e4-6bab-0269-a3c9a0bb6a86&u=a1aHR0cHM6Ly9kb2NzLnNjaXB5Lm9yZy9kb2Mvc2NpcHkvcmVmZXJlbmNlL2dlbmVyYXRlZC9zY2lweS5zdGF0cy5nZW5oeXBlcmJvbGljLmh0bWw&ntb=1

```

And then it gives me this: 
![image](https://github.com/scipy/scipy/assets/24940367/f4b7b183-8c8d-4f7a-a72b-ac7c67faf71f)

**Comment by rkern** [comment]
Both of your search links are working for me. Despite what the browser is saying (to contact the website owners), this is typically a client-side problem, often to do with proxies or antivirus software.
