### ISSUE TITLE
BUG: sparse.csgraph, array types: some functions should expect a fill-value other than zero

### ISSUE THREAD

**Issue by hameerabbasi** [scipy/scipy#20763]
### Describe your issue.

Some [`scipy.sparse.csgraph` routines](https://docs.scipy.org/doc/scipy-1.12.0/reference/sparse.csgraph.html#module-scipy.sparse.csgraph), if they were to work on dense arrays, would expect a fill-value other than zero. For instance, [`scipy.sparse.csgraph.floyd_warshall`](https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.sparse.csgraph.floyd_warshall.html#scipy.sparse.csgraph.floyd_warshall) and other shortest-path algorithms might expect a fill-value of infinity.

`scipy.sparse` objects themselves don't have this issue because they only support zero as a fill-value.

We should make a careful evaluation and update the allowed input fill-values for each function.

The tests at https://github.com/scipy/scipy/blob/c2fccd3e09d60bc1b35d2bdec979bcc330eaaff1/scipy/sparse/csgraph/tests/test_pydata_sparse.py#L30-L41 will need to be adjusted, and so this is a back-compat break from an unreleased version, and also a backport candidate.

### Reproducing Code Example

```python
https://github.com/scipy/scipy/blob/c2fccd3e09d60bc1b35d2bdec979bcc330eaaff1/scipy/sparse/csgraph/tests/test_pydata_sparse.py#L30-L41
```

### Error message

```shell
None
```

### SciPy/NumPy/Python version and system information

```shell
SciPy c2fccd3e09d60bc1b35d2bdec979bcc330eaaff1
```

**Comment by hameerabbasi** [comment]
As an aside, I wasn't clear in my original message, but here it is: This pertains mostly to PyData/Sparse input to `scipy.sparse.csgraph` routines rather than `scipy.sparse` objects themselves (which don't have a fill-value).

**Comment by rgommers** [comment]
> and so this is a back-compat break from an unreleased version, and also a backport candidate.

gh-19796 went into 1.13.0, so it'd be treated like a regular backwards compatibility related change, if there is one. That's not clear to me though - I think this is an internals thing (in the to-from scipy.sparse conversions), and for 1.13.0 there is no correctness issue of the returned result for any pydata sparse array input?

**Comment by hameerabbasi** [comment]
> for 1.13.0 there is no correctness issue of the returned result for any pydata sparse array input?

It depends on what you define as "correct". For example, current `scipy.sparse.csgraph` inputs mostly treat zero, infinity and nan all as "no connection between vertices" for NumPy inputs.

* Zero, to me, is an artifact of `scipy.sparse` arrays/matrices having an implicit fill-value of zero, so the "no connection" parts aren't stored at all. If one were to interpret it without this quirk, it would actually represent zero cost between vertices (which is valid and different from a disconnected pair of vertices).
* NaN is weird, but as long as you define the algorithm such that it treats NaN the same as infinity (using `nanmin` and so on), it's kinda fine.
* Infinity is what makes the most sense to me. No connection mathematically equals infinite cost between vertices.

Right now, we only accept a zero fill-value for `scipy.sparse` inputs, so that's a correctness issue at minimum. To mirror dense arrays, it should accept all three.

But if we were to define correct behaviour from the ground up, I'd only accept infinity as valid.

Caveat: This argument is made for shortest-path algorithms and might need to be adjusted for others.

**Comment by rgommers** [comment]
Okay, I get it now - and I agree `inf` is the most correct thing to do.

I think we can't change the existing behavior, so we should document that `0` entries that are explicit in `scipy.sparse` arrays are treated as `inf`, and the same for `np.ndarray`s with `0` values. 

Then, pydata sparse arrays should match the behavior for `np.ndarray`. And wherever it's possible in the conversion to pydata sparse to insert `inf` instead of `0`, the technically more correct choice can be made.

So no bc-breaking change needed.

**Comment by rgommers** [comment]
@mtsokol is there anything else left to do here after gh-20773?

**Comment by hameerabbasi** [comment]
Should be good to go.
