### ISSUE TITLE
BUG: Build failure on PyPy3.10 7.3.16: `error: ‘Py_Initialize’ was not declared in this scope`

### ISSUE THREAD

**Issue by mgorny** [scipy/scipy#20783]
### Describe your issue.

When building scipy on PyPy3.10 7.3.16, the build fails because of undeclared `Py_Initialize` function. I've reproduced this with 19dcd9fbaaf99cf0020f050b82b7054ef5dbccf6. FWICS none of PyPy headers declare this one.

CC @mattip, @cfbolz

### Reproducing Code Example

```python
# install PyPy3.10 7.3.16
pypy3 -m build -w
```

### Error message

```shell
[850/1383] Compiling C++ object scipy/special/_gufuncs.pypy310-pp73-x86_64-linux-gnu.so.p/_gufuncs.cpp.o
FAILED: scipy/special/_gufuncs.pypy310-pp73-x86_64-linux-gnu.so.p/_gufuncs.cpp.o 
ccache c++ -Iscipy/special/_gufuncs.pypy310-pp73-x86_64-linux-gnu.so.p -Iscipy/special -I../scipy/special -Iscipy/_lib -I../scipy/_lib -I../scipy/_build_utils/src -I../../build-env-9o3hi5jk/lib/pypy3.10/site-packages/numpy/_core/include -I/usr/include/pypy3.10 -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++17 -O3 -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_9_API_VERSION -DSP_SPECFUN_ERROR -MD -MQ scipy/special/_gufuncs.pypy310-pp73-x86_64-linux-gnu.so.p/_gufuncs.cpp.o -MF scipy/special/_gufuncs.pypy310-pp73-x86_64-linux-gnu.so.p/_gufuncs.cpp.o.d -o scipy/special/_gufuncs.pypy310-pp73-x86_64-linux-gnu.so.p/_gufuncs.cpp.o -c ../scipy/special/_gufuncs.cpp
In file included from ../scipy/special/_gufuncs.cpp:1:
../scipy/special/ufunc.h: In function ‘bool SpecFun_Initialize()’:
../scipy/special/ufunc.h:22:5: error: ‘Py_Initialize’ was not declared in this scope; did you mean ‘Py_IsInitialized’?
   22 |     Py_Initialize();
      |     ^~~~~~~~~~~~~
      |     Py_IsInitialized
[853/1383] Compiling C++ object scipy/special/_special_ufuncs.pypy310-pp73-x86_64-linux-gnu.so.p/_special_ufuncs.cpp.o
FAILED: scipy/special/_special_ufuncs.pypy310-pp73-x86_64-linux-gnu.so.p/_special_ufuncs.cpp.o 
ccache c++ -Iscipy/special/_special_ufuncs.pypy310-pp73-x86_64-linux-gnu.so.p -Iscipy/special -I../scipy/special -Iscipy/_lib -I../scipy/_lib -I../scipy/_build_utils/src -I../../build-env-9o3hi5jk/lib/pypy3.10/site-packages/numpy/_core/include -I/usr/include/pypy3.10 -fvisibility=hidden -fvisibility-inlines-hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++17 -O3 -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_9_API_VERSION -DSP_SPECFUN_ERROR -MD -MQ scipy/special/_special_ufuncs.pypy310-pp73-x86_64-linux-gnu.so.p/_special_ufuncs.cpp.o -MF scipy/special/_special_ufuncs.pypy310-pp73-x86_64-linux-gnu.so.p/_special_ufuncs.cpp.o.d -o scipy/special/_special_ufuncs.pypy310-pp73-x86_64-linux-gnu.so.p/_special_ufuncs.cpp.o -c ../scipy/special/_special_ufuncs.cpp
In file included from ../scipy/special/_special_ufuncs.cpp:1:
../scipy/special/ufunc.h: In function ‘bool SpecFun_Initialize()’:
../scipy/special/ufunc.h:22:5: error: ‘Py_Initialize’ was not declared in this scope; did you mean ‘Py_IsInitialized’?
   22 |     Py_Initialize();
      |     ^~~~~~~~~~~~~
      |     Py_IsInitialized
```

### SciPy/NumPy/Python version and system information

```shell
n/a (it didn't build)
```

**Comment by lucascolley** [comment]
cc @izaid @steppi

**Comment by izaid** [comment]
@nickodell It was me who added this. I thought `Py_Initialize()` was needed for C extension modules, but perhaps that's not true. Probably I just copied it accidentally from somewhere.

That said, would be nice to have confirmation that is not needed. Happy to remove it.

**Comment by nickodell** [comment]
@izaid Here is my understanding of the `Py_Initialize()` issue. (Please keep in mind that I have not written any C extension modules for Python, so you should take my comment with a grain of salt.)

There are two ways to use C/C++ and Python together. The first way is to write an extension, i.e. to start in Python and call C code. The second way is to embed the Python interpreter, which starts in C and calls Python. If you are embedding Python, you need `Py_Initialize()`. If you are extending Python, you do not need it.

Here is the section of the docs that I am referencing:

> The one important task that only embedders (as opposed to extension writers) of the Python interpreter have to worry about is the initialization, and possibly the finalization, of the Python interpreter. Most functionality of the interpreter can only be used after the interpreter has been initialized.
> 
> The basic initialization function is [Py_Initialize()](https://docs.python.org/3/c-api/init.html#c.Py_Initialize). This initializes the table of loaded modules, and creates the fundamental modules [`builtins`](https://docs.python.org/3/library/builtins.html#module-builtins), [`__main__`](https://docs.python.org/3/library/__main__.html#module-__main__), and [`sys`](https://docs.python.org/3/library/sys.html#module-sys). It also initializes the module search path (sys.path).

https://docs.python.org/3/c-api/intro.html#embedding-python

My understanding is that SciPy is extending, not embedding Python.

It seems that someone has submitted a PR which removes the line, so we will see if the CPython tests still pass.

**Comment by lucascolley** [comment]
thanks for the explanation @nickodell ! Indeed, CI was happy with the removal.

**Comment by mgorny** [comment]
Thanks. The build with PyPy seems to pass past the problem too now, though I'm not 100% sure because it now fails due to https://github.com/numpy/numpy/pull/26534.
