### ISSUE TITLE
BUG: test_discrete_basic fails on scipy-1.13.1-cp311-cp311-win_arm64

### ISSUE THREAD

**Issue by cgohlke** [scipy/scipy#20801]
### Describe your issue.

`scipy-1.13.1`, built from source against `numpy-2.0.0rc2` and `OpenBLAS-0.3.27` using `LLVM-18.1.6` on Python 3.11 for Windows on ARM64 (`win_arm64`), reproducibly fails the `test_discrete_basic[nbinom-arg14-False]` test (which is actually an amazing result given that this platform is not supported yet).

### Reproducing Code Example

```python
python -c "import scipy;scipy.test()"
```

### Error message

```shell
================================================= test session starts =================================================
platform win32 -- Python 3.11.9, pytest-8.2.1, pluggy-1.5.0
rootdir: C:\Users\gohlke
plugins: anyio-4.3.0, flaky-3.8.1, hypothesis-6.102.6, asyncio-0.23.7, cov-5.0.0, doctestplus-1.2.1, timeout-2.3.1
asyncio: mode=Mode.STRICT
collected 64315 items / 14574 deselected / 49741 selected

_lib\tests\test__gcutils.py ......                                                                               [  0%]
<snip>
stats\tests\test_variation.py ..............................                                                     [100%]

====================================================== FAILURES =======================================================
_______________________________________ test_discrete_basic[nbinom-arg14-False] _______________________________________
C:\Python311-arm64\Lib\site-packages\scipy\stats\tests\test_discrete_basic.py:47: in test_discrete_basic
    check_cdf_ppf(distfn, arg, supp, distname + ' cdf_ppf')
        arg        = (5, 0.5)
        distfn     = <scipy.stats._discrete_distns.nbinom_gen object at 0x0000018FE96DEAD0>
        distname   = 'nbinom'
        first_case = False
        m          = np.float64(5.0)
        rvs        = array([0, 2, 6, ..., 3, 3, 3])
        supp       = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 21])
        v          = np.float64(10.0)
C:\Python311-arm64\Lib\site-packages\scipy\stats\tests\test_discrete_basic.py:198: in check_cdf_ppf
    npt.assert_array_equal(distfn.ppf(cdf_supp0, *arg),
        arg        = (5, 0.5)
        cdf_supp   = array([0.03125   , 0.109375  , 0.2265625 , 0.36328125, 0.5       ,
       0.62304688, 0.72558594, 0.80615234, 0.866577...7547913, 0.98455811, 0.99039459,
       0.99409103, 0.99640131, 0.99782825, 0.99870026, 0.99922806,
       0.99973324])
        cdf_supp0  = array([0.03125   , 0.109375  , 0.2265625 , 0.36328125, 0.5       ,
       0.62304687, 0.72558594, 0.80615234, 0.866577...7547913, 0.98455811, 0.99039459,
       0.99409103, 0.99640131, 0.99782825, 0.99870026, 0.99922806,
       0.99973324])
        distfn     = <scipy.stats._discrete_distns.nbinom_gen object at 0x0000018FE96DEAD0>
        msg        = 'nbinom cdf_ppf'
        supp       = array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 21])
C:\Python311-arm64\Lib\site-packages\numpy\_utils\__init__.py:85: in wrapper
    return fun(*args, **kwargs)
        args       = (array([ 0.,  1.,  2.,  3.,  4.,  5.,  7.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 21....0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 21]), 'nbinom cdf_ppf-roundtrip')
        dep_version = '2.0.0'
        fun        = <function assert_array_equal at 0x0000018FE376F2E0>
        kwargs     = {}
        new_name   = 'desired'
        new_names  = ['actual', 'desired']
        old_name   = 'y'
        old_names  = ['x', 'y']
C:\Python311-arm64\Lib\contextlib.py:81: in inner
    return func(*args, **kwds)
E   AssertionError:
E   Arrays are not equal
E   nbinom cdf_ppf-roundtrip
E   Mismatched elements: 1 / 21 (4.76%)
E   Max absolute difference among violations: 1.
E   Max relative difference among violations: 0.16666667
E    ACTUAL: array([ 0.,  1.,  2.,  3.,  4.,  5.,  7.,  7.,  8.,  9., 10., 11., 12.,
E          13., 14., 15., 16., 17., 18., 19., 21.])
E    DESIRED: array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
E          17, 18, 19, 21])
        args       = (<built-in function eq>, array([ 0.,  1.,  2.,  3.,  4.,  5.,  7.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.,...., 18., 19., 21.]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 21]))
        func       = <function assert_array_compare at 0x0000018FE376F100>
        kwds       = {'err_msg': 'nbinom cdf_ppf-roundtrip', 'header': 'Arrays are not equal', 'strict': False, 'verbose': True}
        self       = <contextlib._GeneratorContextManager object at 0x0000018FE1D57750>
================================================== warnings summary ===================================================
stats/tests/test_qmc.py::TestUtils::test_geometric_discrepancy_mst_with_zero_distances
  C:\Python311-arm64\Lib\site-packages\scipy\stats\tests\test_qmc.py:232: UserWarning: Sample contains duplicate points.
    assert_allclose(qmc.geometric_discrepancy(sample, method='mst'), 0.5)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=============================================== short test summary info ===============================================
FAILED stats/tests/test_discrete_basic.py::test_discrete_basic[nbinom-arg14-False] - AssertionError:
=== 1 failed, 47175 passed, 2398 skipped, 14574 deselected, 155 xfailed, 12 xpassed, 1 warning in 575.70s (0:09:35) ===
Error in sys.excepthook:

Original exception was:
 WARNING: Maximum dimension of Krylov subspace exceeded prior to convergence. T
 ry increasing KMAX.
 neig =  0
```

### SciPy/NumPy/Python version and system information

```shell
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 12:24:25) [MSC v.1938 64 bit (ARM64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()
1.13.1 2.0.0rc2 sys.version_info(major=3, minor=11, micro=9, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2594698540304
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.13.1
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2594698540304
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.13.1
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: clang-cl
    linker: lld-link
    linker args: -Wl,-defaultlib:C:\Programs\LLVM18/lib/clang/18/lib/windows/clang_rt.builtins-aarch64.lib
    name: clang-cl
    version: 18.1.6
  c++:
    commands: clang-cl
    linker: lld-link
    linker args: -Wl,-defaultlib:C:\Programs\LLVM18/lib/clang/18/lib/windows/clang_rt.builtins-aarch64.lib
    name: clang-cl
    version: 18.1.6
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    args: --target=aarch64-pc-windows-msvc
    commands: flang
    linker: lld-link
    linker args: -Wl,-defaultlib:C:\Programs\LLVM18/lib/clang/18/lib/windows/clang_rt.builtins-aarch64.lib,
      --target=aarch64-pc-windows-msvc
    name: flang
    version: 17.0.6
  pythran:
    include directory: C:\Python311-arm64\Lib\site-packages/pythran
    version: 0.16.0
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: windows
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: windows
Python Information:
  path: C:\Python311-arm64\python.exe
  version: '3.11'
```

**Comment by mdhaber** [comment]
@tylerjereddy This was labeled stats, but I'm afraid I'd be unable to debug given that this is about Windows on ARM64. The test notes:
```
    # In very rare cases, the finite precision calculation of ppf(cdf(supp))
    # can produce an array in which an element is off by one.  We nudge the
    # CDF values down by 15 ULPs help to avoid this.
```
So this may be a known issue with the test itself, and we do not typically adjust tests to ensure that they pass on all possible machines. I get more test failures on my own machine, TBH. Is this a wontfix?

**Comment by cgohlke** [comment]
> are you using nbinom in your application?

No, at least not directly.

If this is a known issue with the test, I'm OK to close this issue.

**Comment by mdhaber** [comment]
I'll at least test whether it is close to the boundary. If so, I'll close. Thanks for understanding.

**Comment by mdhaber** [comment]
Actually, in the meantime can you try changing the 15 ULP used in the test to, say, 30? How far do you have to nudge it to make it pass?

**Comment by cgohlke** [comment]
> try changing the 15 ULP used in the test to, say, 30

The test passes with 30 ULP.

> Would you also run this:
> And LMK the output?

```
0.7255859375
6.0
7.0
0.7255859375
6.0
7.0
0.7255859375
6.0
```

![image](https://github.com/scipy/scipy/assets/483428/2a8ef2ee-4a60-4cb2-b4d3-012dcbddc625)

**Comment by mdhaber** [comment]
Thanks. It looks like Boost's `_nbinom_ppf` is bouncing around here, and it so happens that with -15 ULP in particular, it returns 7.0 instead of 6.0. the CDF and PPF are probably both quite accurate and reliable for most inputs, but the test is zooming in on exactly the area where we might have this sort of trouble. I'll let the `scipy.special` folks comment on whether there's anything to be done or whether it's something they'd like to report to Boost, but I'll go ahead and close the issue in the meantime.

**Comment by rgommers** [comment]
> and we do not typically adjust tests to ensure that they pass on all possible machines. 

Eh, this is incorrect. There are exceptions, like very niche platforms that don't implement C99 functions correctly. But beyond that, we consider failures as issues and accept fixes for them. We have countless examples of bumping tolerances when users or distro maintainers report test failures on configurations we don't test.

If the test passes with 30 ULP, we should update the test for that. Either unconditionally, or bump it only on Windows arm64. I haven't looked at the code, but I suspect the former is better since 30 ULP is still very tight.

If you close this kind of thing as wontfix, it just leaves it for the next person to rediscover. I'm reopening, because this is a valid bug report and can be fixed.

> I get more test failures on my own machine, TBH. 

That doesn't annoy you? I really need zero test failures on my configs, so I can review PRs and work on larger-scale topics without noise.

**Comment by WarrenWeckesser** [comment]
Some history, FYI: I added that nudge, originally `10*np.spacing(cdf_supp)`, back in https://github.com/scipy/scipy/pull/17482.  See my comment about it here: https://github.com/scipy/scipy/pull/17482#issuecomment-1328105434 (starting at "Only one test had to be fixed...").

The fudge factor was increased to `15*np.spacing(cdf_supp)` in https://github.com/scipy/scipy/pull/17432, with comments about it at https://github.com/scipy/scipy/pull/17432/files#r1090118460, and reference to the [boost issue](https://github.com/boostorg/math/issues/935) that is still open.

**Comment by mdhaber** [comment]
Ok, we can increase it to 30.

> That doesn't annoy you?

Sure it does. But someone told me years ago that this was normal, and have been under that impression every since. I guess it wasn't you, then. But it sounded right because there are a lot of different machines out there.

I can't even run the full test suite on Windows because `test_import_cycling` hangs. But I'll disable that and file a report.

**Comment by rgommers** [comment]
Yes, let's get those things resolved.

> there are a lot of different machines out there.

The idea is that our CI is representative enough of that very large set of machines/configs, and tolerances are set with reasonable margins so that small variations in how SciPy is built doesn't cause test failures. And if there are recurring/structural problems on some build config, we should add CI coverage for it if we can do so in a reasonable manner.

I think you're using conda envs? Our test suite passes in CI on Windows, but it's possible that we could make things more robust by adding a conda-forge based Windows job.

**Comment by mdhaber** [comment]
The OP also reported "which is actually an amazing result given that this platform is not supported yet". I tried to find out more information about officially supported platforms in our documentation, but I couldn't verify the statement using [Toolchain Roadmap](https://docs.scipy.org/doc/scipy/dev/toolchain.html). What do we consider to be supported?

**Comment by rgommers** [comment]
> What do we consider to be supported?

There is no hard line between supported/unsupported. A few thoughts:
- We have some hard requirements, like "must support C17 and C++17" and "all our dependencies work" that are covered in the toolchain roadmap.
- Beyond that, we have varying levels of support (a la PEP 11, just not written down like that - I may do so for NumPy in the near future):
  - tier 1: we release wheels for a platform on PyPI. That is a long-term commitment, we can't easily not publish such wheels for the next release.
  - tier 2: we test a platform in our CI but don't publish wheels (example: 32-bit Linux)
  - tier 3: we don't test a platform at all but do accept patches for it as long as they are reasonable (example: AIX, PowerPC, Windows on Arm, FreeBSD, Emscripten/Pyodide, etc.)

Windows on Arm64 support is clearly desirable, and we know it's going to become more important over time. It's now in tier 3, and once hosted and free CI support becomes available it'll move into tier 2. If it really takes off, at some point I'd expect we are going to publish wheels for it.
