### ISSUE TITLE
DOC: Discourse release notes character limit

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#20836]
While attempting to post the `1.14.0rc1` release notes/announcement on Discourse: `An error occurred: Body is limited to 32000 characters; you entered 53953.`. I'll probably just link to the full notes for the RC1 post so folks have access to the hashes, etc., but may be good if the limit could be bumped up, or if not let's just document what we want to do in the release process I guess.

**Comment by tylerjereddy** [comment]
cc @stefanv -- probably not a big deal but FYI. In some ways "just linking" is easier for me since I don't have to reformat the markdown/rst shenanigans, though use convenience may be slightly better if I can post/render the full thing.

**Comment by stefanv** [comment]
> cc @stefanv -- probably not a big deal but FYI. In some ways "just linking" is easier for me since I don't have to reformat the markdown/rst shenanigans, though user convenience may be slightly better if I can post/render the full thing.

No problem, I've upped the character limit to 64000.
