### ISSUE TITLE
MAINT/DEV: improve command line clarity of `dev.py`

### ISSUE THREAD

**Issue by fancidev** [scipy/scipy#20848]
### Is your feature request related to a problem? Please describe.

In gh-20844 I was pointed out that `python dev.py test --help` would display the help details for the `test` command. This is actually already pointed out in the first Notes section of the [dev doc](https://docs.scipy.org/doc/scipy/dev/contributor/devpy_test.html). Unfortunately I have used `python dev.py --help test` before, which didn't work.

Let me elaborate what led to my wrong command line to explain why the `dev.py` interface might have been confusing. Running `python dev.py` gives the following output:

<img width="489" alt="Screenshot 2024-05-31 at 7 51 31 PM" src="https://github.com/scipy/scipy/assets/10579828/4b61a83d-596d-4685-b392-4e8a6e07a273">

The first line says

```
Usage: dev.py [OPTIONS] COMMAND [ARGS]...
```

By reading this, I expected "OPTIONS" to be one of `-o`, `--long-opt`, `-o x`, and `--long-opt x`, and `ARG` to be one without leading `-`. So I deduce that `--help` would be an OPTION and therefore come before COMMAND. This is "confirmed" by the next "Options" section in the output that lists `--help` forefront.

Now there indeed is some clue that `--help` could have come after `test`: the sample command on the fourth line says

```
python dev.py --build-dir my-build test -s stats
```

Here `-s stats` does look like an OPTION (as it fits the `-o x` pattern), and it comes after COMMAND. This does ring a bell, but I simply assumed there could be some inconsistencies in the treatment of OPTION vs ARG, or that the order of OPTION is not significant. (For some command line utilities you can put switches before or after the "verb", or even mix OPTIONS and ARGS.)

### Describe the solution you'd like.

To make it easier for a casual user to type the desired command line, I'd propose the following:

1. In the interface, change the command line to `dev.py COMMAND [OPTIONS]` or `dev.py COMMAND [OPTIONS] [ARGS]` if some commands do take (non-switch) args.
2. In the script logic, allow both OPTIONS before COMMAND and OPTIONS after COMMAND, and behave the same regardless of whether an option is given before or after a command.
3. Add an alias `-h` for `--help`.

**Comment by tupui** [comment]
Thanks for the report. I am not sure we have much control on how the CLI works and is documented on that part (need to check) because we are relying on third party dependencies for that. So I would look at the dependencies first (doit and rich cli).

Also I would do only minimal customization for that. In the past we had too many issues maintaining our own scripts. So if there is something to improve, I would push for raising concerns upstream.

**Comment by fancidev** [comment]
Thanks for the info @tupui . I will take a look following your suggestion and feedback.

**Comment by rgommers** [comment]
Note that we're about to switch from `dev.py` to `spin` (see gh-21674), so I think this issue is best closed. After the switch, general UX issues like this one are best reported at https://github.com/scientific-python/spin.
