### ISSUE TITLE
TYP: `_lib.doccer`: add type annotations

### ISSUE THREAD

**Issue by pavyamsiri** [scipy/scipy#20854]
### Is your feature request related to a problem? Please describe.

I noticed that my Python LSP (pyright) was complaining that scipy.io.savemat was an unknown type. After investigating it seems that scipy.io.savemat had a decorator called docfiller that comes from an internal library called doccer.

The library seems to be missing type annotations which may cause type checkers to get confused on decorated functions as it loses information about the parameters and return type.

### Describe the solution you'd like.

Add static type hints to the doccer library and perhaps adjust the docstrings of the functions in doccer to reflect the new type annotations.

### Describe alternatives you've considered.

1. Adjust my own pyright config to ignore the warning.
2. Manually write out the docstrings for the functions in scipy.io._mio where savemat lives.

### Additional context (e.g. screenshots, GIFs)

The standard pyright config does not produce this warning.

Only after setting it to strict type checking mode and then creating a stub for it using pyright --createstub scipy.io does the issue arise, so this might not necessarily be an issue with the decorator but I think it might be helpful to add in types anyway.
![savemat_unknown](https://github.com/scipy/scipy/assets/78515468/d7741c19-de2a-42e3-9f93-b84efe1806ae)

**Comment by lucascolley** [comment]
PRs for adding type annotations are welcome (x-ref https://github.com/scipy/scipy/issues/11749#issuecomment-841520509), there just aren't many people actively working on it. Would you like to submit a PR?

**Comment by pavyamsiri** [comment]
I already filled out some type stubs for my own project. I'll try to get a PR up soon.
