### ISSUE TITLE
MAINT: clean up `sparse._sputils.getdtype` 

### ISSUE THREAD

**Issue by stefanv** [scipy/scipy#20879]
The docstring of `getdtype` is very hard to understand. Provide proper parameter descriptions, and ensure the functionality matches the docstring (it does not currently, but might after #20754).

**Comment by Searchingdays** [comment]
I tried adding the following :

   specified (is None), returns a.dtype. If 'dtype' and 'a'
    are both None, return a numpy data type using the 'default' parameter.
    Furthermore, 'dtype' must not be a np object and must be in supported_dtypes.

 if newdtype not in supported_dtypes:
        raise ValueError("given datatype is not supported")
