### ISSUE TITLE
BUG: sparse.csgraph.dijkstra errors on inputs with int64 or no indices

### ISSUE THREAD

**Issue by larsoner** [scipy/scipy#20904]
Two little bugs I found on the latest pip-pre release (probably in the current release, too, I imagine) on macOS arm64 Python 3.12 at least are below. 

Starting with with imports and sparse matrix creation:
```
import numpy as np
from scipy import sparse
import traceback

adj_mat = sparse.eye(4, format="csr")
```

# Works okay
```
sparse.csgraph.dijkstra(
    adj_mat, False, indices=[1], min_only=True, return_predecessors=True
)
```

# BUG 1: Changing to default indices=None emits a cryptic error

```
sparse.csgraph.dijkstra(
    adj_mat, False, min_only=True, return_predecessors=True
)
#   File "_shortest_path.pyx", line 634, in scipy.sparse.csgraph._shortest_path.dijkstra
# ValueError: cannot reshape array of size 4 into shape (4,4)
```

# BUG 2: doesn't work with int64 indices

```
adj_mat = sparse.csr_array((adj_mat.data, adj_mat.indices.astype(np.int64), adj_mat.indptr.astype(np.int64)))
sparse.csgraph.dijkstra(
    sparse.csr_matrix(adj_mat), False, indices=[1], min_only=True, return_predecessors=True
)
#   File "_shortest_path.pyx", line 620, in scipy.sparse.csgraph._shortest_path.dijkstra
# ValueError: Buffer dtype mismatch, expected 'const int' but got 'long'
```

**Comment by bdpedigo** [comment]
Hi @larsoner - I'm having this `ValueError: Buffer dtype mismatch, expected 'int' but got 'long'` issue (on Mac arm64 Python 3.12 as you said) with scipy 1.13 - 1.14.1. 

I also tried explicitly casting `indices` to every numpy int dtype I could find before passing it in, and still having the same issue. 

Wondering if you have any tips for a temporary fix here until 1.15.0 is released?
