### ISSUE TITLE
How to extract the p-value from the scipy.stats.ranksums result?

### ISSUE THREAD

**Issue by jingydz** [scipy/scipy#20939]
import scipy.stats as ss
...
stat, p =ss.ranksums(d1,d2)
      print stat, p

The scipy p-value returns 0.0. But I want to know the true p value, and I have run it again and again, it always returns 0.0.

**Comment by lucascolley** [comment]
Hi @jingydz , please direct usage questions to either https://stackoverflow.com/questions/tagged/scipy or https://discuss.scientific-python.org/c/user/scipy/30.
