### ISSUE TITLE
MAINT: Premature setting of attributes in `HBInfo` in `scipy.io._harwell_boeing`.

### ISSUE THREAD

**Issue by pavyamsiri** [scipy/scipy#20931]
## Describe your issue.

This isn't really an issue/bug that affects anything as it can only fail if someone used the affected classes in an unintended way, so sorry if this is too small of an issue.

I noticed in scipy/io/_harwell_boeing/hb.py that the `__init__` method of HBInfo takes in a `title` parameter and a `key` parameter that seems to be of type `str | None`.
The method instantly sets the `self.title` and `self.key` attributes to these parameters but then there is a check for when it is `None` upon which the parameters get assigned a new default string value.

The attributes are not updated however to hold this new default value and so the attributes are actually of type `str | None`, but accesses to these attributes assume that the type is `str` and so I think this is a bug.

## Relevant Section of Code

```python
    def __init__(self, title, key,
            total_nlines, pointer_nlines, indices_nlines, values_nlines,
            mxtype, nrows, ncols, nnon_zeros,
            pointer_format_str, indices_format_str, values_format_str,
            right_hand_sides_nlines=0, nelementals=0):
        """Do not use this directly, but the class ctrs (from_* functions)."""
        self.title = title
        self.key = key
        if title is None:
            title = "No Title"
        if len(title) > 72:
            raise ValueError("title cannot be > 72 characters")

        if key is None:
            key = "|No Key"
        if len(key) > 8:
            warnings.warn("key is > 8 characters (key is %s)" % key,
                          LineOverflow, stacklevel=3)
```

## The Fix

The most obvious fix is to move the first two attribute assignments past the `None` checks, like this
```python
    def __init__(self, title, key,
            total_nlines, pointer_nlines, indices_nlines, values_nlines,
            mxtype, nrows, ncols, nnon_zeros,
            pointer_format_str, indices_format_str, values_format_str,
            right_hand_sides_nlines=0, nelementals=0):
        """Do not use this directly, but the class ctrs (from_* functions)."""
        if title is None:
            title = "No Title"
        if len(title) > 72:
            raise ValueError("title cannot be > 72 characters")

        if key is None:
            key = "|No Key"
        if len(key) > 8:
            warnings.warn("key is > 8 characters (key is %s)" % key,
                          LineOverflow, stacklevel=3)
        self.title = title
        self.key = key
```
Alternatively, as the two class constructors `from_data` and `from_file` both pass in strings for `title` and `key` making it impossible for `__init__` to take in `None` values for these parameters, we could also just remove the `None` checks.

**Comment by lucascolley** [comment]
thanks @pavyamsiri , that does look like a small bug. Either solution seems fine, but moving the setting of attributes until after the `None`-value handling seems more in line with what the original author intended IMO. Would you like to submit a PR?

**Comment by pavyamsiri** [comment]
Yes I will soon after I finish testing my change.
