### ISSUE TITLE
TST: tolerance violations with SciPy 1.14.0rc1 on linux-{aarch64,ppc64le}

### ISSUE THREAD

**Issue by h-vetinari** [scipy/scipy#20938]
In https://github.com/conda-forge/scipy-feedstock/pull/277, I see new failures for aarch/ppc.

On linux-aarch64, there are some minor violations of relative tolerance:
```
=========================== short test summary info ============================
FAILED special/tests/test_hyp2f1.py::TestHyp2f1::test_region2[hyp2f1_test_case15] - AssertionError: 
Not equal to tolerance rtol=1e-15, atol=0

Mismatched elements: 1 / 1 (100%)
Max absolute difference among violations: 7.42004997e-11
Max relative difference among violations: 1.24886275e-15
 ACTUAL: array(54749.216391-23078.144721j)
 DESIRED: array(54749.216391-23078.144721j)
FAILED special/tests/test_hyp2f1.py::TestHyp2f1::test_region5[hyp2f1_test_case44] - AssertionError: 
Not equal to tolerance rtol=1.1e-15, atol=0

Mismatched elements: 1 / 1 (100%)
Max absolute difference among violations: 1.24126708e-15
Max relative difference among violations: 1.51901296e-15
 ACTUAL: array(-0.185152+0.795901j)
 DESIRED: array(-0.185152+0.795901j)
= 2 failed, 49224 passed, 2743 skipped, 159 xfailed, 14 xpassed, 106 warnings in 6336.31s (1:45:36) =
```

On linux-ppc64le, the failures are in completely different tests; while also related to tolerance violations, here it looks more like it's about values close to machine precision, and thus the absolute tolerance that would need to be loosened.

``` 
=========================== short test summary info ============================
FAILED optimize/tests/test_differentiate.py::TestDifferentiate::test_vectorization[shape1-6] - AssertionError: 
Not equal to tolerance rtol=1e-07, atol=5e-15

Mismatched elements: 1 / 12 (8.33%)
Max absolute difference among violations: 6.02295991e-15
Max relative difference among violations: 2.00249219e-06
 ACTUAL: array([4.384204e-09, 4.384201e-09, 4.081055e-09, 3.501619e-09,
       2.696714e-09, 1.735705e-09, 6.991865e-10, 3.291873e-10,
       1.270939e-09, 2.059971e-09, 2.647979e-09, 3.007738e-09])
 DESIRED: array([4.384204e-09, 4.384203e-09, 4.081054e-09, 3.501620e-09,
       2.696713e-09, 1.735705e-09, 6.991875e-10, 3.291881e-10,
       1.270939e-09, 2.059969e-09, 2.647979e-09, 3.007732e-09])
FAILED optimize/tests/test_differentiate.py::TestDifferentiate::test_vectorization[shape2-6] - AssertionError: 
Not equal to tolerance rtol=1e-07, atol=5e-15

Mismatched elements: 1 / 12 (8.33%)
Max absolute difference among violations: 6.02295991e-15
Max relative difference among violations: 2.00249219e-06
 ACTUAL: array([4.384204e-09, 4.384201e-09, 4.081055e-09, 3.501619e-09,
       2.696714e-09, 1.735705e-09, 6.991865e-10, 3.291873e-10,
       1.270939e-09, 2.059971e-09, 2.647979e-09, 3.007738e-09])
 DESIRED: array([4.384204e-09, 4.384203e-09, 4.081054e-09, 3.501620e-09,
       2.696713e-09, 1.735705e-09, 6.991875e-10, 3.291881e-10,
       1.270939e-09, 2.059969e-09, 2.647979e-09, 3.007732e-09])
FAILED optimize/tests/test_differentiate.py::TestDifferentiate::test_vectorization[shape3-6] - AssertionError:
Not equal to tolerance rtol=1e-07, atol=5e-15

Mismatched elements: 1 / 12 (8.33%)
Max absolute difference among violations: 6.02295991e-15
Max relative difference among violations: 2.00249219e-06
 ACTUAL: array([4.384204e-09, 4.384201e-09, 4.081055e-09, 3.501619e-09,
       2.696714e-09, 1.735705e-09, 6.991865e-10, 3.291873e-10,
       1.270939e-09, 2.059971e-09, 2.647979e-09, 3.007738e-09])
 DESIRED: array([4.384204e-09, 4.384203e-09, 4.081054e-09, 3.501620e-09,
       2.696713e-09, 1.735705e-09, 6.991875e-10, 3.291881e-10,
       1.270939e-09, 2.059969e-09, 2.647979e-09, 3.007732e-09])
= 3 failed, 49562 passed, 2741 skipped, 160 xfailed, 16 xpassed, 106 warnings in 5716.31s (1:35:16) =
```

In both cases it's possible that this is related to QEMU version and/or details of the underlying host agent. I can skip those tests if necessary, but it would be nicer to fix it properly.

**Comment by mdhaber** [comment]
The second failure is alread addressed in gh-20928 because I encountered the same problem with another array backend.

**Comment by tylerjereddy** [comment]
> The test_differentiate failures are alread addressed in https://github.com/scipy/scipy/pull/20928 because I encountered the same problem with another array backend.

That said, it would of course be preferable not to backport an enhancemet PR to the release branch for the purposes of simple tol adjustments. Are you in favor of manual/temporary shims for that purpose on the release branch?

**Comment by mdhaber** [comment]
Oops didn't see this was about RC1 with the assumption that we need a backport. I can bump that tolerance in a separate PR.

**Comment by dschmitz89** [comment]
Slightly offtopic but do we want to keep supporting PPC architecture? How relevant is that? Without continuous testing, such issues will occur in every release process. I understand we are widely used library but there has to be a tradeoff between required efforts and gains in my opinion.

**Comment by andyfaff** [comment]
`ppc64le` is definitely more niche. With these kinds of targets historical policy has been that we make necessary changes, with the expectation that the downstream consumers help in making the fixes. The expectations have to be correspondingly lower for performance/stability/speed of response.
IMO one advantage of keeping this kind of unofficial support is that it helps keep other targets in a better state.

**Comment by h-vetinari** [comment]
> How relevant is that? Without continuous testing, such issues will occur in every release process.

For better or worse, it's one of the main architectures in conda-forge, so support is important. That doesn't mean that SciPy here _has_ to run CI for PPC on all PRs, but it should mean that we fix issues as they crop up. We've been doing this for a long time (even with PyPy, which used to break even more; now dropped on the feedstock), so I don't think we should change something.
