### ISSUE TITLE
TST: `special.tests.test_support_alternative_backends`: failure with JAX `betainc`

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#20963]
Hypothesis found an edge case in which JAX's `betainc` doesn't agree with SciPy's, and it's causing CI failures.

We need to ~~skip the test to get CI green again~~ (gh-20966) and ~~report the issue to JAX~~ (google/jax#21900). 

~~Suggestions on how to ignore this counterexample?~~ NM there is already a [mechanism for skipping JAX.](https://github.com/scipy/scipy/blob/113b6ca90a22a710590a119680d45595e8df8be3/scipy/special/tests/test_support_alternative_backends.py#L58)

```python3
import matplotlib.pyplot as plt
import numpy as np
from scipy.special import betainc as betainc_scipy
import jax.numpy as xp
from jax.scipy.special import betainc as betainc_jax

a = np.logspace(-40, -1, 300)
b = 1
x = 0.25
plt.loglog(a, betainc_scipy(a, b, x), label='scipy')
plt.loglog(a, betainc_jax(xp.asarray(a), b, x), label='jax')
plt.xlabel('a')
plt.ylabel('betainc(a, 1, 0.25)')
plt.legend()
```
<img width="613" alt="image" src="https://github.com/scipy/scipy/assets/6570539/b3c6a70d-1b5d-496d-b4ef-93a266b46bf1">

**Comment by dschmitz89** [comment]
Cc @jakevdp

**Comment by mdhaber** [comment]
@Zac-HD Hypothesis has made it really easy to test that SciPy is correctly dispatching special function evaluation to other array backends, but occasionally it finds edge case counter-examples that need to be fixed in the underlying backend and not hold up our CI in the meantime. For instance, this issue is about a failure with JAX's `betainc`, but we've also had trouble with other special functions. Currently, we just skip the tests with JAX and these special functions, but is there a better way of ignoring just the known counter-examples? I know we could add `assume`s to avoid these cases manually - but I'm looking for something more convenient. For instance, since there is a decorator to reproduce specific test cases, is there a decorator to ignore specific test cases?

**Comment by Zac-HD** [comment]
Nope, my best advice is to either skip for convenience, or use assume() for more precise exclusions.  Sorry I don't have a better way, but glad it's finding problems for you!

**Comment by rgommers** [comment]
@mdhaber did a new failure show up repeatedly because somehow a seeded random number stream failed, or aren't these hypothesis tests using seeding correctly? All tests must use fixed seeds and the "deterministic" profile for `hypothesis` as defined in `scipy/conftest.py`, so flaky failures ideally should not occur.

Skipping the test isn't the right solution, unless it's a major issue / regression in JAX.

**Comment by mdhaber** [comment]
> Skipping the test isn't the right solution, unless it's a major issue / regression in JAX.

Sure, it was not the *best* solution, but I can see why you did it. gh-20085 was a big PR.

But that's fine, we're improving it now.

**Comment by rgommers** [comment]
@mdhaber I don't understand your reply. The first sentence of your bug report says the test is causing CI failures. If the test was always skipped, there can't be failures on it. I see linked PRs/issues, but there's too many for me to go through them all and guess at the history. What is actually going on here? 

> @mdhaber did a new failure show up repeatedly because somehow a seeded random number stream failed, or aren't these hypothesis tests using seeding correctly?

(that's also why I asked this)

**Comment by mdhaber** [comment]
> @mdhaber I don't understand your reply.

In gh-20085, you merged changes that skipped some tests of `gammainc`, `gammincc`, and `rel_entr`:

https://github.com/scipy/scipy/blob/e984c959f1009e05452b06796721a1d02ed93c16/scipy/special/tests/test_support_alternative_backends.py#L58-L62

I agreed that skipping them completely wasn't the best way to handle it; it would have been a bit better to avoid these edge cases but still test that the function works otherwise with JAX arrays. But since gh-20085 had a lot going on, it is understandable that you chose to go this route for the time being. 

It's fine because the linked PR will fix this issue and probably prevent repeats by using PRNG numbers instead of Hypothesis to generate the arguments to the special functions. Hypothesis is just too good at its job for this use case. If there is a better way to manage the random state using features of `pytest`, I'm open to them.

> I see linked PRs/issues, but there's too many for me to go through them all and guess at the history. 

No problem! It's under control, so no need for you to go through all that.

> What is actually going on here?

It looks like the last run with Hypothesis 6.103.1 passed and the first with 6.103.2, released June 14, failed. Hypothesis doesn't guarantee stability the same tests between versions, so I assume this is what caused the change. If you'd like, you could submit a PR to pin the Hypothesis version, and I'd be happy to review it.
