### ISSUE TITLE
Numpy 2 support?

### ISSUE THREAD

**Issue by lobpcg** [scipy/scipy#20978]
Is numpy 2 supported?

**Comment by nickodell** [comment]
Yes, SciPy 1.13.0 and higher are compatible with NumPy 2.0.

In the future, please use a site like [StackOverflow](https://stackoverflow.com/questions/tagged/scipy) for questions about how to use SciPy.

**Comment by ilayn** [comment]
@nickodell, @lobpcg is the author of lobpcg solver in SciPy so he knows how to use SciPy 😃 

This happens to all of us so no problem in this case but closing things an epsilon slower avoids these cases.

**Comment by nickodell** [comment]
Ah, my bad. I'll be more careful about closing issues in the future.

**Comment by lucascolley** [comment]
@lobpcg you may be looking for https://github.com/numpy/numpy/issues/26191

**Comment by VVD** [comment]
py311-numpy-2.4.3 installed.
It doesn't look like scipy supports this version of numpy:
```
numpy-config found: NO
Run-time dependency numpy found: NO (tried pkgconfig and config-tool)
Message: f2py free-threading disabled; need numpy >=2.1.0.
Message: See https://github.com/mesonbuild/meson/issues/14651

../scipy/meson.build:65:17: ERROR: Command `/usr/local/bin/python3.11 -c 'import os
os.chdir(os.path.join("..", "tools"))
import numpy as np
try:
  incdir = os.path.relpath(np.get_include())
except Exception:
  incdir = np.get_include()
print(incdir)
  '` failed with status -4.

A full log can be found at /tmp/work/usr/ports/science/py-scipy/work-py311/scipy-1.17.1/.mesonpy-0ptmsvqb/meson-logs/meson-log.txt

ERROR Backend subprocess exited when trying to invoke build_wheel
*** Error code 1
```
Build fine with py311-numpy-1.26.4.

**Comment by lucascolley** [comment]
@VVD please open a new issue detailing how you have installed NumPy and SciPy.

**Comment by VVD** [comment]
> [@VVD](https://github.com/VVD) please open a new issue detailing how you have installed NumPy and SciPy.

This is because Numpy 2.x builts with X86_V2 by default, which is not supported by my CPU.
Rebuild Nympy with `-Csetup-args=-Dcpu-baseline="none" -Csetup-args=-Dcpu-baseline-detect="disabled"` fixed this issue.
