### ISSUE TITLE
BUG: scipy.optimize.nnls 1.11.4 version has better performance than the rewritten version with same results

### ISSUE THREAD

**Issue by jonasgitabap** [scipy/scipy#20984]
### Describe your issue.

I updated my code to latest version and recognize that the new nnls version does take much more ressources and time for the same results. Is there maybe a way to access the old version also in the latest version?
my test is using the same data for both cases.
old: duration 2s
<img width="107" alt="image" src="https://github.com/scipy/scipy/assets/85170424/24bc7ac0-8b08-4bfa-8aaa-f0060d960153">
new: duration 2min
<img width="218" alt="image" src="https://github.com/scipy/scipy/assets/85170424/0aafe3ce-2200-44aa-8b55-23bef9f83656">

### Reproducing Code Example

```python
i use latest scikit-learn LinearRegression which calls scipy.optimize.nnls
LinearRegression(positive=True, fit_intercept=True, copy_X=False)
```

### Error message

```shell
Matrix is singular
```

### SciPy/NumPy/Python version and system information

```shell
all latest except scipy==1.11.4 for getting the performant version
```

**Comment by nickodell** [comment]
Can you provide an example dataset which reproduces this issue?

**Comment by jonasgitabap** [comment]
[test_dataset.pkl.zip](https://github.com/user-attachments/files/15892129/test_dataset.pkl.zip)
its ja pkl file inside a dataframe in the right shape, just split without any randomization its a time series problem

**Comment by lucascolley** [comment]
x-ref https://github.com/scipy/scipy/pull/18570#issuecomment-1569053956

**Comment by nickodell** [comment]
Can you clarify: is this bug report about the new `nnls()` taking longer to run, or the `Matrix is singular` error?

Your matrix does appear to be singular. Here is a correlation matrix of your X:

<img width="754" alt="Screenshot 2024-06-18 at 4 07 44 PM" src="https://github.com/scipy/scipy/assets/666402/654e6f89-f0db-4ec1-85fb-509317e7f35d">

Most correlation values are 1 or NaN. The coefficients you extract from this are going to be very noisy.

PS: I just realized I forgot to respond to part of your question:

>Is there maybe a way to access the old version also in the latest version?

No, the old version was removed in SciPy 1.12.0. If you want the old version, you'll need to use SciPy 1.11.4 or earlier.

**Comment by jonasgitabap** [comment]
@nickodell sorry I wasn't clear enough. X = only df['price'] and y = df['epoch_median_iqr'] for example. if you compare it with the old nnls version it gets done with a good r2 score but with the new version i get this error. Is there a way to get around this error by doing some preprocessing?

**Comment by ilayn** [comment]
Hi @jonasgitabap Could you please convert the issue into a code snippet so that we can test it properly? I'm rewriting this new version anyways so this would be a nice test case. But not sure what you are doing hence it would help.

**Comment by jonasgitabap** [comment]
<img width="619" alt="image" src="https://github.com/scipy/scipy/assets/85170424/6f9e0210-45bd-4bb1-b325-6deb8cee4d01">
`import scipy.version
from sklearn.linear_model import LinearRegression
import scipy
import pandas as pd
import time

df: pd.DataFrame = pd.read_pickle(f'path_to_pickle.pkl')
df = df.reset_index()
df = df.set_index(['epoch_id','epoch_median_iqr'])
df = df.drop(columns=['reward_epoch_id', 'low_iqr', 'high_iqr', 'epoch_mean_iqr', 'epoch_mean'])
[test_data.pkl.zip](https://github.com/user-attachments/files/15901547/test_data.pkl.zip)

X_train = df.iloc[:-20]
X_test = df.tail(20)
y_train = df.iloc[:-20].index.get_level_values('epoch_median_iqr')
y_test = df.tail(20).index.get_level_values('epoch_median_iqr')

model = LinearRegression(positive=True, fit_intercept=True, copy_X=False)` 

`start_time = int(time.time()*1000)
model = model.fit(X_train, y_train)
r2_score = model.score(X_test, y_test)
end_time = int(time.time()*1000)
r2_score, scipy.version.version, f'{end_time-start_time}ms'`
