### ISSUE TITLE
ENH: 3.13 wheels

### ISSUE THREAD

**Issue by clin1234** [scipy/scipy#20992]
### Is your feature request related to a problem? Please describe.

I'm attempting to introduce 3.13 wheels for scikit-learn (see scikit-learn/scikit-learn#29292). Per @lesteve, no prebuilt 3.13 wheels are a major blocker, as building from source would time out scikit-learn's CI builds. What's the status?  (Free-threaded builds are nice, but not necessary)

**Comment by lucascolley** [comment]
1.14.0 will support 3.13, and pre-release wheels are available on PyPI. The release date is scheduled for June 25th, but could be delayed. The only known issue for 3.13 at the minute is gh-19572.

As for free-threaded, see gh-20669.

**Comment by rgommers** [comment]
Thanks for asking @clin1234. We can put up nightlies for 3.13 very soon to unblock you - I'll have a look at both numpy and scipy.

**Comment by rgommers** [comment]
Looks like we should add a regular 3.13-pre CI job first. It should pass, since the free-threaded 3.13-pre job passes as well, but still. Then we should be adding back something along the lines of gh-18937 for dev wheels. 

Cc @andyfaff for visibility.

**Comment by andyfaff** [comment]
Trying to add the cp313-dev job in https://github.com/andyfaff/scipy/pull/72. However, first iteration errors out with

```
[79/1383] Compiling C object scipy/special/_ufuncs.cpython-313-x86_64-linux-gnu.so.p/meson-generated__ufuncs.c.o
FAILED: scipy/special/_ufuncs.cpython-313-x86_64-linux-gnu.so.p/meson-generated__ufuncs.c.o 
ccache cc -Iscipy/special/_ufuncs.cpython-313-x86_64-linux-gnu.so.p -Iscipy/special -I../scipy/special -Iscipy/_lib -I../scipy/_lib -I../scipy/_build_utils/src -I../../../../../../opt/hostedtoolcache/Python/3.13.0-beta.2/x64/lib/python3.13/site-packages/numpy/_core/include -I/usr/include/x86_64-linux-gnu/openblas-pthread/ -I/opt/hostedtoolcache/Python/3.13.0-beta.2/x64/include/python3.13 -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c17 -O2 -g -Wno-unused-but-set-variable -Wno-unused-function -Wno-conversion -Wno-misleading-indentation -fPIC -DSP_SPECFUN_ERROR -DNPY_NO_DEPRECATED_API=NPY_1_9_API_VERSION -DCYTHON_CCOMPLEX=0 -Wno-maybe-uninitialized -MD -MQ scipy/special/_ufuncs.cpython-313-x86_64-linux-gnu.so.p/meson-generated__ufuncs.c.o -MF scipy/special/_ufuncs.cpython-313-x86_64-linux-gnu.so.p/meson-generated__ufuncs.c.o.d -o scipy/special/_ufuncs.cpython-313-x86_64-linux-gnu.so.p/meson-generated__ufuncs.c.o -c scipy/special/_ufuncs.cpython-313-x86_6
scipy/special/_ufuncs.cpython-313-x86_64-linux-gnu.so.p/_ufuncs.c: In function ‘__pyx_f_5scipy_7special_11_ellip_harm_lame_coefficients’:
scipy/special/_ufuncs.cpython-313-x86_64-linux-gnu.so.p/_ufuncs.c:10801:3: error: ‘Py_UNICODE’ is deprecated [-Werror=deprecated-declarations]
10801 |   Py_UNICODE __pyx_v_t;
      |   ^~~~~~~~~~
scipy/special/_ufuncs.cpython-313-x86_64-linux-gnu.so.p/_ufuncs.c:10816:3: error: ‘Py_UNICODE’ is deprecated [-Werror=deprecated-declarations]
10816 |   Py_UNICODE __pyx_t_3;
      |   ^~~~~~~~~~
cc1: all warnings being treated as errors
```

Trying to install cython from git to see if that does anything.

**Comment by andyfaff** [comment]
There are already numpy nightlies for cp313.

**Comment by andyfaff** [comment]
Ok, we now have regular linux testing with cp313, that was relatively straightforward to add.

**Comment by rgommers** [comment]
gh-21000 added 3.13 wheels builds; new nightlies are building now and should upload to https://anaconda.org/scientific-python-nightly-wheels/scipy/ in the next 30 minutes or so.

**Comment by lesteve** [comment]
It seems the wheels are indeed there, thanks a lot for this!

**Comment by lesteve** [comment]
It seems the wheels are indeed there, thanks a lot for this :pray:!

**Comment by clin1234** [comment]
> [gh-21000](https://github.com/scipy/scipy/pull/21000) added 3.13 wheels builds; new nightlies are building now and should upload to https://anaconda.org/scientific-python-nightly-wheels/scipy/ in the next 30 minutes or so.

**Comment by EwoutH** [comment]
Tomorrow the Python 3.13 release candidate will be released, which makes 3.13 ABI stable and allows (and encourages) wheels to be uploaded to PyPI.

**Comment by EwoutH** [comment]
3.13 rc1 is released! Tracking for cibuildwheel: https://github.com/pypa/cibuildwheel/pull/1949

What would be fastest feasible course to get wheels on PyPI? Would a 1.14.1 release with 3.13 wheels be possible?

**Comment by lucascolley** [comment]
> Would a 1.14.1 release with 3.13 wheels be possible?

I believe this is the plan, yes.

**Comment by rgommers** [comment]
We need a NumPy 2.1.0rc1 first - probably next week, since there are some hiccups with the OpenBLAS version used by NumPy.

**Comment by EwoutH** [comment]
Thanks! That would be https://github.com/numpy/numpy/issues/27036 right?

**Comment by rgommers** [comment]
Yes indeed, that's the one.

**Comment by EwoutH** [comment]
NumPy 2.1.0rc1 release PR is opened: https://github.com/numpy/numpy/pull/27176
