### ISSUE TITLE
BUG: spsolve prints "dgstrf info" to stdout on singular matrices

### ISSUE THREAD

**Issue by nickodell** [scipy/scipy#20993]
### Describe your issue.

When solving a matrix which is singular, dgstrf exits with a non-zero `info` code to signal that it was called with a singular matrix, and the caller, dgssv, prints out this info code to stdout.

This print does not seem to be possible to turn off. It would be good if we avoided printing to the console, and used warnings/exceptions/return values to signal failure.

Since we already issue a warning for a singular matrix, it seems like we could skip this print if `0 <= info && info <= ncols`.

I originally [saw this on StackOverflow](https://stackoverflow.com/questions/78641125/scipy-sparse-solve-prints-dgstrf-info/). 

This seems to have been caused by https://github.com/scipy/scipy/pull/19284, which added this print statement.

https://github.com/scipy/scipy/blob/1d59ab9813f052d442f5ae460f016b05aaad20a2/scipy/sparse/linalg/_dsolve/SuperLU/SRC/dgssv.c#L236

### Reproducing Code Example

```python
import scipy
import numpy as np


A = scipy.sparse.identity(10, format='csr').tocsr()
A[-1, -1] = 0
b = np.zeros(10)
foo = scipy.sparse.linalg.spsolve(A, b)
print(foo)
```

### Error message

```shell
dgstrf info 10
[nan nan nan nan nan nan nan nan nan nan]
/tmp/ipykernel_2621/3030846931.py:8: MatrixRankWarning: Matrix is exactly singular
  foo = scipy.sparse.linalg.spsolve(A, b)
```

### SciPy/NumPy/Python version and system information

```shell
1.13.1 1.22.4 sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= ZEN MAX_THREADS=64
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas
    openblas configuration: USE_64BITINT=0 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= ZEN MAX_THREADS=64
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.27
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-mnl4e8vy/overlay/lib/python3.10/site-packages/pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp310-cp310/bin/python
  version: '3.10'
```

This issue also occurs in SciPy 1.12.0 - 1.13.1.

**Comment by ilayn** [comment]
Is it possible to fix it upstream and bump the version? That would be the easiest for us. They are typically very responsive.

**Comment by dschmitz89** [comment]
Good news, the SuperLU repo was updated: https://github.com/xiaoyeli/superlu/commit/6cecd12c4680ce77d6ee4ff9eb412b5f8fc0e5f6

We will have to wait until the next SuperLU release probably, not sure if we have used their main branch so far.

Thanks again @xiaoyeli
