### ISSUE TITLE
BUG: Error occurs when packaging with pyinstaller and executing it

### ISSUE THREAD

**Issue by yangwenqian** [scipy/scipy#20997]
### Describe your issue.

Using pyinstaller to package the exe files generated by scipy 1.13.1 and numpy 2.0.0 will result in errors during runtime
.
Packaging is normal, but an error occurred while running exe.

![QQ截图20240620111633](https://github.com/scipy/scipy/assets/3896297/0d46d2b1-395a-4f76-abc0-146f7e2bcfdb)

### Reproducing Code Example

```python
from scipy.interpolate import RectBivariateSpline
```

### Error message

```shell
ModuleNotFoundError: No module named 'numpy.f2py'
```

### SciPy/NumPy/Python version and system information

```shell
Package                   Version
------------------------- --------
altgraph                  0.17.4
numpy                     2.0.0
packaging                 24.1
pefile                    2023.2.7
pip                       24.0
pyinstaller               6.8.0
pyinstaller-hooks-contrib 2024.7
pywin32-ctypes            0.2.2
scipy                     1.13.0
setuptools                70.0.0
```

**Comment by lucascolley** [comment]
`numpy.f2py` still exists in NumPy 2.0 (https://github.com/numpy/numpy/tree/main/numpy/f2py) - can you check that the files are there locally?

**Comment by andyfaff** [comment]
This will be a pyinstaller hook issue, which is not in scipy's domain to fix. I am having no issues on personal projects making pyinstaller exe with numpy2 + scipy.

**Comment by MyGitRepo15** [comment]
Same error!
I downgraded numpy to 1.14 from 2.0 but still shows this error.
How can I solve this error?
