### ISSUE TITLE
DOC: Incorrect documentation for wasserstein_distance_nd() function in scipy/scipy/stats /_stats_py.py

### ISSUE THREAD

**Issue by Wei-kang-Wang** [scipy/scipy#21006]
### Issue with current documentation:

In line 10138 of file ./scipy/scipy/stats/_stats_py.py, it says "Compute the Wasserstein-1 distance between two N-D discrete distributions." it's not correct.

### Idea or request for content:

The correct documentation for this wasserstein_distance_nd() function is "Compute the Wasserstein-2 distance between two N-D discrete distributions." Since by default the distance matrix is defined in line 10328 as: D = distance_matrix(u_values, v_values, p=2), and in this case, the metric norm is actually L2, not L1. So by default, this function actually computes wasserstein-2 distance between two distributions.

**Comment by mdhaber** [comment]
According to Wikipedia:

<img width="892" alt="image" src="https://github.com/scipy/scipy/assets/6570539/dbb98c58-cc90-4e18-9a65-ccf66aae3152">

By default `wasserstein_distance_nd` uses `p=1` with `d` as the Euclidean ($L_2$) norm. 

The Wasserstein-2 distance would involve the distance squared.

**Comment by com3dian** [comment]
Yes we had issue #19858, and I explained it in https://github.com/scipy/scipy/pull/19858#issuecomment-1887337163:

> Thanks @yagizolmez @mdhaber , this is indeed a bit confusing at first glance. The commonly accepted definition of the Wasserstein-p distance defined between two distribution $\nu, \mu$ on a metric space $(M, d)$ is 
> 
> $$
> W_p(\nu, \mu) = (inf_{\gamma \in \Gamma(\nu, \mu)} \ E_{(x, y) \sim \gamma} \ d(x, y)^p )^{1/p}
> $$
> 
> where $\Gamma(\nu, \mu)$ is the set of couplings of $\nu$ and $\mu$, $\gamma$ is a joint distribution and $d$ is the **distance metric of the space**. Therefore as we defautly assume the inputs is on euclidean space, the distance is naturally the euclidean distance (L2 norm). In the [document](https://cran.r-project.org/web/packages/transport/transport.pdf) of `tranport` library in R, page 39, it also mentions
> 
> > The Wasserstein distance of order p is defined as the p-th root of the total cost incurred when
> transporting measure `a` to measure `b` in an optimal way, where the cost of transporting a unit of
> mass from $x$ to $y$ is given as the p-th power $‖x − y‖^p$ of the Euclidean distance.
> 
> So in this code `D = distance_matrix(u_values, v_values, p=2)` we try to get the distance matrix without giving any power so it is simply computing the Wasserstein-1 distance.
> 

In short, the $p$ in wasserstein-p distance is corresponding to the $p$ in the definition of $W_p(\nu, \mu)$, and should not be confused with the $p$ in p-norm or $L^p$ space.

**Comment by mdhaber** [comment]
Thanks! It would be worth adding something near the top of the documentation to prevent additional reports, if you're willing.

**Comment by Wei-kang-Wang** [comment]
Thanks a lot for your clarification @mdhaber  and @com3dian. It's my mistake to confuse between “norm" and "power". If you can add some explanation about the default distance metric in the documentation, it would be more clearer.

**Comment by com3dian** [comment]
> Thanks! It might be worth adding something near the top of the documentation to prevent additional reports, if you're willing.

Sure! I will have some time in July, and I will take a look at this then.
