### ISSUE TITLE
DOC, DEV: release notes `gh_lists` touchups

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#21030]
See https://github.com/scipy/scipy/pull/20986#issuecomment-2185402086 for a few corner cases we still need to handle, but for now the release manger can touch those up manually since the end result is nicer than our old approach.

As noted there, the regex soup is getting messy enough that we may want to `pytest` it for a few cases to avoid "Whac-A-Mole" string parsing.

**Comment by lucascolley** [comment]
Here is an example of an incorrect sanitization:

```
MAINT: `cluster`/`stats`: array API test failures in main 
```

is sanitized to

```
MAINT: ``cluster``\ /`stats``: array API test failures in m``...
```

Taking a look.
