### ISSUE TITLE
BUG: scipy.interpolate.LinearNDInterpolator call _calculate_triangulation with Delaunay triangulation

### ISSUE THREAD

**Issue by Djip007** [scipy/scipy#21043]
### Describe your issue.

There was a re-factor on "interpnd.py" that add a "_calculate_triangulation" function:
- https://github.com/scipy/scipy/blob/main/scipy/interpolate/interpnd.pyx#L304
it is always call from here: 
- https://github.com/scipy/scipy/blob/main/scipy/interpolate/interpnd.pyx#L92

So, now, if LinearNDInterpolator is built with a precomputed Delaunay triangulation, a triangulation is recalculated as if only points had been passed.

This breaks all the code that gives its own triangulation.

### Possible Code Correction

```python
# old code was (V1.11.x):
class LinearNDInterpolator(NDInterpolatorBase):
    def __init__(self, points, values, fill_value=np.nan, rescale=False):
        NDInterpolatorBase.__init__(self, points, values, fill_value=fill_value, rescale=rescale)
        if self.tri is None:
            self.tri = qhull.Delaunay(self.points)


# may be corrected by something like that on NDInterpolatorBase constructor
if (self.tri = None) :  # add control before call _calculate_triangulation.
    self._calculate_triangulation(self.points)
```

### Error message

```shell
No error report, but wrong result.
```

### SciPy/NumPy/Python version and system information

```shell
SciPy 1.12/1.13/1.13.1
```

**Comment by lucascolley** [comment]
indeed this looks like a bug to me, and the suggested fix sounds about right, although I am not familiar with this code. cc @hovavalon @ev-br . Feel free to submit a PR @Djip007 !

**Comment by hovavalon** [comment]
Seems reasonable to me.

**Comment by Djip007** [comment]
> indeed this looks like a bug to me, and the suggested fix sounds about right, although I am not familiar with this code. cc @hovavalon @ev-br . Feel free to submit a PR @Djip007 !

OK I'll will try :wink:   ...

**Comment by lucascolley** [comment]
let us know if you would like any help! https://scipy.org/community/ tells you how you can reach out

**Comment by Djip007** [comment]
Make change en execute "interpolate" tests.
look good for me. 
:crossed_fingers:
