### ISSUE TITLE
BUG: Testsuite fails to start with GCC 14

### ISSUE THREAD

**Issue by glaubitz** [scipy/scipy#21048]
### Describe your issue.

Trying to run the testsuite with GCC 14 fails with:

```
[   17s] Shell debugging temporarily silenced: export LMOD_SH_DBG_ON=1 for Lmod's output
[   18s] Lmod has detected the following error: The following module(s) are unknown:
[   18s] "gnu/14"
[   18s] 
[   18s] Please check the spelling or version number. Also try "module spider ..."
[   18s] It is also possible your cache file is out-of-date; it may help to try:
[   18s]   $ module --ignore_cache load "gnu/14"
[   18s] 
[   18s] Also make sure that all modulefiles written in TCL start with the string
[   18s] #%Module
[   18s] 
[   18s] 
[   18s] 
[   18s] Shell debugging restarted
[   18s] + unset __lmod_sh_dbg
[   18s] + return 1
```

### Reproducing Code Example

```python
Just use GCC 14 as the default C/C++ compiler.
```

### Error message

```shell
[   17s] Shell debugging temporarily silenced: export LMOD_SH_DBG_ON=1 for Lmod's output
[   18s] Lmod has detected the following error: The following module(s) are unknown:
[   18s] "gnu/14"
[   18s] 
[   18s] Please check the spelling or version number. Also try "module spider ..."
[   18s] It is also possible your cache file is out-of-date; it may help to try:
[   18s]   $ module --ignore_cache load "gnu/14"
[   18s] 
[   18s] Also make sure that all modulefiles written in TCL start with the string
[   18s] #%Module
[   18s] 
[   18s] 
[   18s] 
[   18s] Shell debugging restarted
[   18s] + unset __lmod_sh_dbg
[   18s] + return 1
```
```


### SciPy/NumPy/Python version and system information

```shell
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()
1.13.1 1.26.4 sys.version_info(major=3, minor=11, micro=9, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/include/openblas
    lib directory: /usr/lib64/openblas-pthreads
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 ZEN MAX_THREADS=64
    pc file directory: /usr/lib64/pkgconfig
    version: 0.3.26
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /usr/include/openblas
    lib directory: /usr/lib64/openblas-pthreads
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 ZEN MAX_THREADS=64
    pc file directory: /usr/lib64/pkgconfig
    version: 0.3.26
  pybind11:
    detection method: pkgconfig
    include directory: /include
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    args: -O2, -Wall, -U_FORTIFY_SOURCE, -D_FORTIFY_SOURCE=3, -fstack-protector-strong,
      -funwind-tables, -fasynchronous-unwind-tables, -fstack-clash-protection, -Werror=return-type,
      -flto=auto, -g, -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -O2, -Wall, -U_FORTIFY_SOURCE, -D_FORTIFY_SOURCE=3, -fstack-protector-strong,
      -funwind-tables, -fasynchronous-unwind-tables, -fstack-clash-protection, -Werror=return-type,
      -flto=auto, -g, -fno-strict-aliasing
    name: gcc
    version: 13.3.0
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 13.3.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 13.3.0
  pythran:
    include directory: ../../../../../../usr/lib/python3.11/site-packages/pythran
    version: 0.16.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /usr/bin/python3.11
  version: '3.11'

>>>
```
```

**Comment by rgommers** [comment]
Thanks for the report @glaubitz. That does not look familiar. Could you please add the exact commands for how you built scipy and ran the test suite?

**Comment by glaubitz** [comment]
See the openSUSE spec file for `python-scipy` starting from line 250 [1].

> [1] https://build.opensuse.org/projects/devel:languages:python:numeric/packages/python-scipy/files/python-scipy.spec?expand=1

**Comment by rgommers** [comment]
Thanks. The relevant line is:
```
%pytest_arch --pyargs scipy -n auto -m "not (slow or xslow $mark32bit)" -k "not ($donttest)"
```

None of the error messages come from SciPy, so to see if this is a valid bug report we need someone to build and test with GCC 14 in the regular way on an x86-64 Linux machine (e.g., a local `pip install . && python -c "import scipy; scipy.test()"`, or `python dev.py test`), excluding things like loading modules with Lmod. And if it fails, get a traceback or `pytest` output.

**Comment by tylerjereddy** [comment]
I compiled gcc `14.1.0` from source using `spack` on x86_64 Ubuntu Linux, then ran `python dev.py test -j 4` with latest SciPy `main` branch and Python `3.11`, and only found one test failure now described at gh-21059.

Since the original issue comment above seems to have a version `1.13.1` in its config output, I built/tested that version of SciPy from source with gcc `14.1.0` as well and its full suite passed (it didn't even have that one failure).

**Comment by glaubitz** [comment]
Thanks a lot to everyone involved in helping debug this issue. I'm not an expert for Numpy and Scipy at all (despite being a physicist), so I really appreciate for Scipy developers taking the time to look into this.

I assume the original issue I saw is related to Numpy where I am seeing the same error message when trying to run the testsuite. I am currently going through all Python packages in openSUSE Tumbleweed that fail to build with GCC 14.

**Comment by rgommers** [comment]
Thanks for checking @tylerjereddy. I'll close this issue then.

> I assume the original issue I saw is related to Numpy where I am seeing the same error message when trying to run the testsuite

If Tyler got SciPy's test suite to pass, NumPy must be working fine with GCC 14 as well. This really looks like a problem in how OpenSUSE sets up builds, since there's nothing in the error messages that has anything to do with any Python package. It could be completely unrelated, or it could for example be an extra compiler/linker flag that the OpenSUSE build config injects that is problematic.
