### ISSUE TITLE
ENH: Why HiGHs/milp needs more and more memory space when runtime goes by.

### ISSUE THREAD

**Issue by SomaLily** [scipy/scipy#21053]
### Is your feature request related to a problem? Please describe.

This issue is an extension of #20958 .
I've try other solvers, and their consumption of memory is stable -- not higher and higher along runtime.
Why HiGHs/milp performs like this , and can it be fixed?

**Comment by nickodell** [comment]
I don't quite understand the connection to 2095, given that it is a scipy.ndimage issue. Did you mean to link a different issue?

**Comment by SomaLily** [comment]
> I don't quite understand the connection to 2095, given that it is a scipy.ndimage issue. Did you mean to link a different issue?

sorry ... I've fixed it to 20958

**Comment by rgommers** [comment]
@SomaLily why did you close the old issue and opened a new one with no context? As written, this isn't actionable.

**Comment by SomaLily** [comment]
> @SomaLily why did you close the old issue and opened a new one with no context? As written, this isn't actionable.

How about reopen the old issue and ... er,  I don't know how to use github.

**Comment by nickodell** [comment]
@SomaLily, I've reopened the prior issue, and closed this one.
