### ISSUE TITLE
Query: upstreaming `_lib._array_api` discussion

### ISSUE THREAD

**Issue by KelSolaar** [scipy/scipy#21054]
### Is your feature request related to a problem? Please describe.

Hello,

We would like to implement support for the Python Array API standard in Colour as per https://github.com/colour-science/colour/issues/1244. The work you did in [scipy/_lib/_array_api.py](https://github.com/scipy/scipy/blob/main/scipy/_lib/_array_api.py) seems incredibly useful for that purpose.

### Describe the solution you'd like.

We would be keen for the [scipy._lib._array_api](https://github.com/scipy/scipy/blob/main/scipy/_lib/_array_api.py) module to either be made public or, even better, to be moved to its own repository.

### Describe alternatives you've considered.

The alternative would be to copy the code entirely into Colour which seems wasteful.

**Comment by lucascolley** [comment]
hey @KelSolaar ! The plan is to eventually upstream everything in that file that isn't SciPy-specific. Some of it will belong in `array-api-compat` as helpers. Scikit-learn has a similar file with different functions in it, so the upstreaming process should ideally consolidate the two.

There isn't a timescale on this yet though, as the functions in that file are still going through lots of change as we figure out exactly what we need/want.

Which functions in particular would be useful for you right now? We could discuss whereabouts upstream they might belong.

**Comment by lucascolley** [comment]
We won't be making it public though - everything is still very experimental, and most things there would not really belong in the SciPy API.

**Comment by KelSolaar** [comment]
Hey @lucascolley,

Thanks for the fast reply! At first glance we would likely use all those functions:

- `array_namespace`
- `atleast_nd`
- `copy`
- `xp_assert_equal`
- `xp_assert_close`
- `xp_minimum` would also need `xp_maximum`
- `xp_clip`
- `xp_sign`

I suspect that the `is_numpy` one would see good use.

**Comment by lucascolley** [comment]
> `array_namespace`

This function is a SciPy-specific wrapper around https://data-apis.org/array-api-compat/helper-functions.html#array_api_compat.array_namespace.

```python
if not _GLOBAL_CONFIG["SCIPY_ARRAY_API"]:
    # here we could wrap the namespace if needed
    return np_compat

_arrays = [array for array in arrays if array is not None]

_arrays = compliance_scipy(_arrays)

return array_api_compat.array_namespace(*_arrays)
```

I recommend writing your own wrapper for Colour. You could use the same switch of an environment variable or something different at the start. You could replace `compliance_scipy` with whatever input validation you would like for array types.

> `is_numpy`

Likewise here, you should just make your own version, depending on the relative path of your vendored array-api-compat.

```python
def is_numpy(xp: ModuleType) -> bool:
    return xp.__name__ in ('numpy', 'scipy._lib.array_api_compat.numpy')
```

---

> `atleast_nd`

This falls into the category I would describe as "array-api-extra" - array-agnostic functions which sit just on top of the standard, on the borderline between the array-producer and array-consumer library levels. I envision the creation of a new upstream repo to house functions like this; a sort of purgatory between inclusion in the standard, and finding a suitable home in a downstream repo's API.

But, there has been no work towards such a repo yet (that I am aware of).

---

> `xp_minimum`, `xp_maximum`, `xp_clip`, `xp_sign`

These were recently added to the standard (https://data-apis.org/array-api/draft/changelog.html#additions), and are waiting for array-api-compat implementations. They will become available there in due course (https://github.com/data-apis/array-api-compat/issues/127).

> `copy`

I think that we could look into getting this upstreamed to array-api-compat, alongside its subroutine `_asarray`.

---

> `xp_assert_equal`, `xp_assert_close`

These are rather in flux. You are in good company with @ilayn (and myself) in hoping for these to be provided upstream. See gh-21044 for the contemporary discussion on where we would like these to go in SciPy. After that is all decided and implemented, we should also try to consolidate with whatever scikit-learn is using, before we think about trying to upstream.

**Comment by lucascolley** [comment]
cc @ogrisel @betatim for vis

**Comment by rgommers** [comment]
The backlog of APIs to be added to `array-api-compat`, like `minimum`, `copy`, etc., will be worked on very soon - perhaps @asmeurer has already started on it.

For the rest, I think I agree with the answers by @lucascolley and @betatim. A new `array-api-extra` package will be useful and necessary, but right now is a bit too early to consolidate. I'd recommend borrowing from scipy and scikit-learn what you need for the time being.

**Comment by asmeurer** [comment]
Yes, I am working on updating array-api-compat now for 2023 support now. 

I agree that any array functions that aren't part of the standard (like `atleast_nd`) should go in a separate `array-api-extra` package. It's been brought up multiple times before, so we should probably find a more central place to discuss it. Right now, things like that are [out of scope](https://data-apis.org/array-api-compat/#scope) for `array-api-compat`, because I want to keep that library as a compat layer for the standard only.

Helper functions, though, are in scope, and if SciPy has any that aren't already implemented we can move them over. Note that array-api-compat does already have `is_numpy_array` https://data-apis.org/array-api-compat/helper-functions.html. which I think is the same as SciPy's `is_numpy`. Also if there are any features missing from the array-api-compat helpers like `array_namespace` we can add them. I already have [one proposed change](https://github.com/data-apis/array-api-compat/pull/147) to `array_namespace` which is similar to what SciPy is doing in its wrappers. 

Ideally libraries shouldn't need any of their own wrapping code, unless they are really doing things specific to themselves, like SciPy's `SCIPY_ARRAY_API` environment variables or special handling of `numpy.matrix`.

**Comment by lucascolley** [comment]
> Note that array-api-compat does already have is_numpy_array https://data-apis.org/array-api-compat/helper-functions.html. which I think is the same as SciPy's is_numpy.

`is_numpy_array` takes an array as input. SciPy's `is_numpy` takes a `ModuleType` (`xp`).

**Comment by asmeurer** [comment]
I see. I didn't realize doing that way would be more useful, but we can add similar helpers to array-api-compat.

**Comment by lucascolley** [comment]
When generating arrays (which sometimes happens without an array already accessible), it is easier to switch on the namespace than have to generate an array or pass one in to switch on.

**Comment by lucascolley** [comment]
It would probably be good if we could add a warning in the case that a namespace is passed to `is_numpy_array`, and similarly for if an array is passed to `is_numpy`.

**Comment by asmeurer** [comment]
https://github.com/data-apis/array-api-compat/issues/156

**Comment by KelSolaar** [comment]
Thanks a lot for the insights guys, very much appreciated! That certainly gives me a good direction to follow.

**Comment by rgommers** [comment]
Great, glad we have a good way forward. I think this can be closed now. @KelSolaar please do feel free to continue the discussion as needed of course. I think we're all keen to figure this stuff out collectively.
