### ISSUE TITLE
ENH: RBFInterpolator classmethods for loading RBFInterpolator

### ISSUE THREAD

**Issue by CorneSuijkerbuijk** [scipy/scipy#21060]
### Is your feature request related to a problem? Please describe.

The RBFInterpolator takes some time to initialized since a system of equations need to be build and solved. This slows down running time when a lot of RBFInterpolators need to be initialized. 

### Describe the solution you'd like.

Move the code of the current __ init __ method of the RBFInterpolator to a classmethod. Instead, the __ init __ method only contains the attributes that come out of the current __init__ method. Beside of this, another classmethod can be written to load a "pre-initialized" RBFInterpolator which loads faster. 

### Describe alternatives you've considered.

Loading RFBInterpolator with cache.

**Comment by CorneSuijkerbuijk** [comment]
Use case: I have a Python pipeline for processing measurements. This is done with a stateless interface. This means that Python doesn't keep state between pipeline runs, every state info needed for the next pipeline run is stored in data files (json in my case) and loaded again as input in the next pipeline run. Therefore, I have a json file with stored input arguments for the RBFInterpolator. In each pipeline run the RBFInterpolator is initialized with this json file.

Since the` __init__` method initializes as set of attributes. My idea is to store these set of attributes in a json instead of the input arguments of the `__init__` method. If it is possible to initialize the RBFInterpolator with this new json, then building and solving a system of equations (`_build_and_solve_system`) can be skipped which saves runtime.

**Comment by ev-br** [comment]
> This is done with a stateless interface. This means that Python doesn't keep state between pipeline runs, every state info needed for the next pipeline run is stored in data files (json in my case) and loaded again as input in the next pipeline run.

Hm. First and foremost, have you checked that the time spent re-initializing RBF instances is non-negligible? 
If it is indeed the case --- meaning your "runs" do very little work --- then I'd recommend looking into grouping the runs so that a single RBF instance is reused. 

Otherwise, you could probably pickle an instance and save it as a string into your json. In a next run, unpickle it and it should be equivalent to the pre-constructed one.

**Comment by ev-br** [comment]
No follow-up and pickling RBF instances seems to work indeed (a simple demo is under the fold). 
At this stage I do not believe there is a demonstrated need to complicate the RBF interface, and I'm going to close this issue. Thank you @CorneSuijkerbuijk regardless!
Feel free to continue the discussion of course.

<details>

```
In [1]: import numpy as np

In [2]: from scipy.interpolate import RBFInterpolator

In [3]: ndim = 1

In [4]: npts = 5

In [5]: y = np.arange(ndim*npts).reshape(npts, ndim)

In [6]: d = np.arange(npts*3).reshape(npts, 3)

In [7]: rbf = RBFInterpolator(y, d)

In [9]: rbf([[3]])
Out[9]: array([[ 9., 10., 11.]])

In [10]: import pickle

In [11]: p_rbf = pickle.dumps(rbf)

In [12]: type(p_rbf)
Out[12]: bytes

In [13]: u_rbf = pickle.loads(p_rbf)

In [14]: u_rbf([[3]])
Out[14]: array([[ 9., 10., 11.]])
```
</details>
