### ISSUE TITLE
DOC: `optimize.InverseJacobian`: document or deprecate?

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#21088]
`scipy.optimize.InverseJacobian` is public and is listed in the documentation, but it has no docstring.

![image](https://github.com/scipy/scipy/assets/6570539/f660d294-e215-43a5-b986-4f846bc49997)

Should it be documented or deprecated? It is in the legacy section, so I suppose we could also just leave it be. Just thought I'd get another opinion (or a docstring, if someone is willing to write one).

**Comment by melissawm** [comment]
Maybe it should also get a `.. legacy::` note? But it shows up very ugly in the table so it would be nice to document, I think. https://scipy.github.io/devdocs/reference/generated/scipy.optimize.InverseJacobian.html#scipy.optimize.InverseJacobian

**Comment by mdhaber** [comment]
OK, I'd review it. Shouldn't be hard because it is just a wrapper.
