### ISSUE TITLE
BUG: Problems with developer installation in Debian virtualenv

### ISSUE THREAD

**Issue by MikhailRyazanov** [scipy/scipy#21080]
### Describe your issue.

I see the same symptoms as in #19563, but @rgommers said that it's unrelated, so here is a separate, more complete description.

I use the current Debian “testing” distribution, with the following system packages (current versions):
```
python3  3.11.8-1
python3.11  3.11.9-1
python3-virtualenv  20.26.2+ds-1
python3-pip-whl  24.1+dfsg-1
python3-setuptools  68.1.2-2
```
A fresh virtual environment created by `virtualenv` has the following:
```
Package    Version
---------- -------
pip        24.1
setuptools 68.1.2
wheel      0.43.0
```
Then I follow the [Building from source](https://scipy.github.io/devdocs/building/index.html) instructions, installing everything else inside the virtual environment using its `pip`, and do `dev.py build`, which succeeds (besides some Fortran warnings). However, trying to run `dev.py build` again or `dev.py python` fails with an error message
```
RuntimeError: Can't install in non-empty directory: '<...>/build-install'
```

Examining what happens in `dev.py`, I've found that the actual install is made to
```
.../build-install/lib/python3/dist-packages
```
but [`get_site_packages()`](https://github.com/scipy/scipy/blob/3959e8b28a8fdf9f6803fe34bf8f0e34909d840d/dev.py#L328C9-L328C26) trying to find it later gives instead
```
.../build-install/lib/python3.11/site-packages
```
Notice the `dist`/`site` difference (mentioned in the `get_site_packages()` docstring) and the generic `3` instead of specific `3.11` (not mentioned anywhere). Manually creating symlinks between the expected and actual locations seems to produce a usable installation. So it appears that different parts of `dev.py` (or the tools that it uses) construct the installation path by different means, which are not consistent.

This part that is supposed to treat Debian as a special case:
https://github.com/scipy/scipy/blob/3959e8b28a8fdf9f6803fe34bf8f0e34909d840d/dev.py#L342
actually is not executed because in my case there is no `'deb_system'` in `INSTALL_SCHEMES` (I don't know what is supposed to set it). Manually replacing this condition by `True` also seems to make the installation usable but produces several `Please avoid running ``setup.py`` directly.` warnings.

For comparison, the virtual environment itself has its packages in its `lib/python3.11/site-packages`, more consistent with what `get_site_packages()` currently thinks (without `'deb_system'`) rather than the structure currently created inside SciPy's `build-install`.

P.S. With the paths corrected as described above, I see that even if no files were changed, running `dev.py build` or `dev.py python` redoes a complete installation every time. Is this intentional (why?), or there is something else failing to recognize that the installed files are already up-to-date?

### Reproducing Code Example

See above.

### Error message

See above.

### SciPy/NumPy/Python version and system information

SciPy source cloned from GitHub's main branch
`Python 3.11.9 (main, Apr 10 2024, 13:16:36) [GCC 13.2.0] on linux` from Debian “testing”

**Comment by MikhailRyazanov** [comment]
Correction to “redoes a complete installation every time”:

In fact, only `version.py` is rewritten every time, which is not a big deal.

The real problem is that Meson itself forcefully recompiles _all_ the `.py` files every time, adding an unnecessary delay (~5 seconds on my system), which is longer than everything else during an incremental build. This behavior was introduced [here](https://github.com/mesonbuild/meson/commit/0e7fb07f915b7a2b04df209fbacd92aca19c87af#diff-f9f5c32b63cd61b04d0d50553587f2b702a5722394bbd353087b778acdf5c41cR48-R50) (Meson [PR #11530](https://github.com/mesonbuild/meson/pull/11530)) with an option [`python.bytecompile`](https://mesonbuild.com/Builtin-options.html#python-module) that can be set to `-1` to disable, but defaults to `0` (compile bytecode without optimizations). While this bytecode compilation might be useful for the initial build, it is definitely harmful for incremental builds.

**Comment by rgommers** [comment]
Thanks @MikhailRyazanov. Somehow I managed to miss that new `bytecompile` behavior until now, no idea why I didn't notice it and it's that slow for you. Agreed we don't want to use this at all. Will look at at a bit closer, but I think we should default to `-1`.

Also, reading the discussion, there's an issue with it with `--tags`, which we do set to at least `'tests'` for test `.py` files. `meson-python` isn't affected here, since it doesn't run `meson install` at all.

**Comment by tartopohm** [comment]
I have a very similar issue, on Ubuntu, using python3.11 and venv.
The first build went fine.  On trying to run subsequent tests, `dev.py` exits with
```
Traceback (most recent call last):                                                                                                                                                                                
   File ".../scipy/venv/lib/python3.11/site-packages/doit/action.py", line 461, in execute                                                                                                      
     returned_value = self.py_callable(*self.args, **kwargs)                                                                                                                                                       
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                       
   File ".../scipy/dev.py", line 649, in run                                                                                                                                                    
     cls.install_project(dirs, args)                                                                                                                                                                               
   File "../scipy/dev.py", line 549, in install_project                                                                                                                                        
     raise RuntimeError("Can't install in non-empty directory: "                                                                                                                                                   
RuntimeError: Can't install in non-empty directory: '...scipy/build-install' 
```
After symlinking `python3/dist-packages` to `python3.11/site-packages`, as suggested by @MikhailRyazanov, `dev.py` now exits with
```
ImportError: Error importing SciPy: you cannot import SciPy while                                                                                                                                                 
     being in scipy source directory; please exit the SciPy source                                                                                                                                                 
     tree first and relaunch your Python interpreter.  
```
From outside scipy's directory, I can `import scipy`, but not import subpackages.

I don't know if relevant, at the top of my `meson-install.log` are the lines
```
ninja: Entering directory `.../scipy/build'
[1/38] Generating scipy/linalg/_dummy_cython_blas.pxd with a custom command
[2/2] Generating scipy/generate-version with a custom command
fatal: bad revision '^v1.13.0'
```
and then, `Build OK` and `Installation OK`. It is a fresh clone, from a freshly synced fork.

**Comment by fancidev** [comment]
I had the same issue when building from source on Debian 12.5 / Python 3.11.2 / venv. This issue is very helpful!

The environment’s  `distutils.command.install.INSTALL_SCHEMES` apparently does not contain a `deb_system` key, so the special-handling branch is not executed. I was able to “make it work” by replacing that with `sysconfig.get_scheme_names()`, which does contain a `deb_system` key. Not sure how reliable is the fix, but at least it gets things going.
