### ISSUE TITLE
Modifying `_ravel_coords` function used in `reshape` method for 3d `coo_array` objects

### ISSUE THREAD

**Issue by anushkasuyal** [scipy/scipy#21105]
Hi!
I had a question. In _coo.py, a method `reshape` is defined as follows -
```
def reshape(self, *args, **kwargs):
        is_array = isinstance(self, sparray)
        shape = check_shape(args, self.shape, allow_1d=is_array)
        order, copy = check_reshape_kwargs(kwargs)
        # Return early if reshape is not required
        if shape == self.shape:
            if copy:
                return self.copy()
            else:
                return self
        # When reducing the number of dimensions, we need to be careful about
        # index overflow. This is why we can't simply call
        # `np.ravel_multi_index()` followed by `np.unravel_index()` here.
        flat_coords = _ravel_coords(self.coords, self.shape, order=order)
        if len(shape) == 2:
            if order == 'C':
                new_coords = divmod(flat_coords, shape[1])
            else:
                new_coords = divmod(flat_coords, shape[0])[::-1]
        else:
            new_coords = np.unravel_index(flat_coords, shape, order=order)
        # Handle copy here rather than passing on to the constructor so that no
        # copy will be made of `new_coords` regardless.
        if copy:
            new_data = self.data.copy()
        else:
            new_data = self.data
        return self.__class__((new_data, new_coords), shape=shape, copy=False)
```
I am currently attempting to extend _coo.py to 3d, and on calling reshape for a 3d `coo_array` (after having made relevant changes in another files to allow 3-dimensional `coo_array` objects) I got correctly reshaped 3d, 2d, and flattened 1d arrays. The code above uses the function `_ravel_coords`, which is as follows -
```
def _ravel_coords(coords, shape, order='C'):
    """Like np.ravel_multi_index, but avoids some overflow issues."""
    if len(coords) == 1:
        return coords[0]
    # Handle overflow as in https://github.com/scipy/scipy/pull/9132
    if len(coords) == 2:
        nrows, ncols = shape
        row, col = coords
        if order == 'C':
            maxval = (ncols * max(0, nrows - 1) + max(0, ncols - 1))
            idx_dtype = get_index_dtype(maxval=maxval)
            return np.multiply(ncols, row, dtype=idx_dtype) + col
        elif order == 'F':
            maxval = (nrows * max(0, ncols - 1) + max(0, nrows - 1))
            idx_dtype = get_index_dtype(maxval=maxval)
            return np.multiply(nrows, col, dtype=idx_dtype) + row
        else:
            raise ValueError("'order' must be 'C' or 'F'")
    return np.ravel_multi_index(coords, shape, order=order)
```

this function calls `np.ravel_multi_index` since `len(coords)=3` for the 3d array arg.

I'd assume using `np.ravel` would make arrays with dim>2 prone to index overflow. So would you recommend rewriting `_ravel_coords` such that the `len(coords)==3` case is also included? (Just asking so that if that is to be done, I could properly familiarise myself with the order C and F conventions!)

**Comment by perimosocordiae** [comment]
Did you mean to close this issue @anushkasuyal? We do hope to add support for 3d COO arrays at some point.

**Comment by dschult** [comment]
Yes, I think avoiding index overflows would require rewriting `_ravel_coords` -- but if you know you are already using `int64` for your coords arrays you can use `ravel_multi_index`.

I've been playing with ideas along this line for nD sparse arrays. If you'd like to compare notes let me know.

**Comment by anushkasuyal** [comment]
@perimosocordiae I am currently working on nD sparse arrays as part of my internship, and am exploring this in my own work right now!

**Comment by anushkasuyal** [comment]
Thanks @dschult !
