### ISSUE TITLE
MAINT: cirrus wheel upload failure

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#21122]
On main: https://github.com/scipy/scipy/runs/27111407667

```
[WARNING] Distribution "scipy-1.15.0.dev0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl" already exists. Removing.
[ERROR] ('Authentication token has expired', 401)
��������
```

**Comment by rgommers** [comment]
I'll have a look at fixing this up now. The token was added in June 2023 in gh-18661, so looks like it was generated with a 1 year expiration date.

**Comment by rgommers** [comment]
gh-21136 updated the tokens; the run at https://cirrus-ci.com/task/6732568630919168 succeeded and new `aarch64` wheels are up at https://anaconda.org/scientific-python-nightly-wheels/scipy/. So I'll close this issue.
