### ISSUE TITLE
ENH: allow for averaging of top N rather than just single value in NearestNDInterpolator

### ISSUE THREAD

**Issue by PolarBean** [scipy/scipy#21138]
Would it be possible for NearestNDInterpolator to take as an argument N, which would specify to return the average of the top N results. Ideally it could also have an averaging method argument which specifies whether the average should be uniform or distance based, This would bring its function more in line with https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html

Thank you in advance.

**Comment by ev-br** [comment]
Not sure how that is supposed to work, what are _top N results_?

**Comment by j-bowhay** [comment]
Is this not inverse distance weighted interpolation? Is so please feel free to join in the discussion here https://github.com/scipy/scipy/issues/2022

**Comment by ev-br** [comment]
Following up the discussion in https://github.com/scipy/scipy/pull/21139, we're going to keep `NearestNeighborInterpolator` as is, and consider adding new functionality in a separate object. Thanks @PolarBean , @j-bowhay
