### ISSUE TITLE
BUG: dev.py build --debug doesn't produce a debug build

### ISSUE THREAD

**Issue by ngoldbaum** [scipy/scipy#21145]
If I run `python dev.py build --debug` I don't get a debug build. Looking inside `dev.py`, it seems the `debug` option is created but never actually used anywhere:

https://github.com/scipy/scipy/blob/2db21778447442c74132d1be4cf3a4716e68c015/dev.py#L417-L418

I can get a debug build if I compile scipy with the following command:

```
python dev.py build --setup-args="-Dbuildtype=debug"
```

Presumably the debug option needs to do something similar with `setup-args`.

**Comment by rgommers** [comment]
Thanks for the report @ngoldbaum. I suspect it hasn't been noticed because the default is `debugoptimized`; the "how to get a release build" question is more common. I agree though that it'd be useful for `--debug` to yield `-Dbuildtype=debug` (i.e., debug info + `-O0` instead of `-O2`).
