### ISSUE TITLE
RFC: spatial: review calculation formula for Jaccard distance with non-0/1 input

### ISSUE THREAD

**Issue by fancidev** [scipy/scipy#21158]
### Is your feature request related to a problem? Please describe.

When `spatial.distance.jaccard`, `cdist('jaccard')`, or `pdist('jaccard')` is called with input vectors that contain elements that are not equal to `True`, `False`, `0` or `1`, with or without weights, the calculation formula appears ad-hoc and not obviously meaningful.

Concretely, for real vectors $(u_1, \cdots, u_n)$ and $(v_1, \cdots, v_n)$, the Jaccard functions produce a value equal to

$$
\frac{\\#\\{ i \\, |\\, u_i \ne v_i \\}}{\\#\\{ i \\,|\\, u_i v_i \ne 0 \\}}
$$

assuming the denominator is not zero.

*If* the input vectors contained only Boolean or 0/1 values, it would be natural to consider $\\{ 1, 2, \cdots, n \\}$ as the full set of interest, and interpret $u_i = 1$ to indicate that $i$ is in the first set, and $v_i=1$ to indicate that $i$ is in the second set. This seems to agree with the usual definition of Jaccard distance, i.e. (size of) set intersection over (size of) set union.

However, in the above expression, only the denominator is consistent with this interpretation. The numerator counts the number of pairs $(u_i,v_i)$ where $u_i$ and $v_i$ are unequal, even if they're both non-zero. I'm unable to find an interpretation for this treatment, noting that the value $u_i$ (or $v_i$) is *not* a value in the full set (but $i$ is).

### Describe the solution you'd like.

For consistency with Boolean input, I suggest to change the formula to

$$
\frac{\\#\\{ i \\, |\\, u_i \ne 0, v_i = 0 \textrm{ or } u_i=0, v_i \ne 0 \\}}{\\#\\{ i \\,|\\, u_i v_i \ne 0 \\}}
$$

### Describe alternatives you've considered.

A simple workaround for the user is to always convert an input vector to `True`/`False` or `0`/`1`.

Even though this workaround works, I think it would be ideal to fix the consistency when the workaround is not used.

### Additional context (e.g. screenshots, GIFs)

All the other Boolean distance functions _in Python_ adopt "fuzzy" logic formula for non-Boolean inputs, i.e. replacing `an and b` with `a*b` and `not a` with `1-a`. Most of the other Boolean distance functions _in C++_ converts non-Boolean input to 0/1 before doing the calculation, _except_ `dice` which adopts fuzzy logic for the unweighted case and an ad-hoc formula for the weighted case. (Admittedly these details are more than I wanted to know!)

That `Jaccard` is treated specially in the code appears to suggest the treatment might be intentional. But a counter-hint is that the code actually computes the numerator by

```C++
num = (x != y) & ((x != 0) | (y != 0));
```

This is just a disguised version of `x != y`; the part after `&` is redundant. This gives me the feeling that the formula might not have been well thought of after all.

**Comment by jakevdp** [comment]
There is some previous discussion of this in [gh-12174](https://github.com/scipy/scipy/pull/12174) and [gh-14357](https://github.com/scipy/scipy/pull/14357). The second link is a pull request with a proposed fix along the lines of what you suggest here, but it was never merged and has some discussion of why this is a complicated topic.

**Comment by fancidev** [comment]
Thanks for the reference @jakevdp !

Disallowing (non-Boolean) 0/1 input might be a bit far reaching. I think it would be easier to “silently” convert numbers to Booleans.

As for whether $(u_i)$, $(v_i)$ could be treated as _values_ of two sets themselves, I think it’s a bit far too, for example consider `(0,1,2,3)` vs `(1,2,3,4)`, which gives a similarity of zero although intersection / union equals 0.6.

As for compatibility with Matlab/Octave, I checked [MATLAB Documentation](https://www.mathworks.com/help/images/ref/jaccard.html), which supports input vectors with integer values, ranging from say 1 to m. MATLAB treats these integer values as *labels*, and returns an m-*vector* of Jaccard distances, where if I understand correctly the k-th component is the number of pixels labeled as k in both images over the number of pixels labeled as k in either image. This is different from SciPy’s formula.
