### ISSUE TITLE
DOC: `optimize.root_scalar`: arguments incorrectly marked required

### ISSUE THREAD

**Issue by teepeemm** [scipy/scipy#21178]
### Issue with current documentation:

```python
from scipy.optimize import root_scalar

root_scalar(lambda x: x**3-1, x0=2)  # statement 1
root_scalar(lambda x: x**3-1, x0=2, method='newton')  # statement 2
```

Statement 1 raises `ValueError: x1 must not be None for secant`.  This agrees with
https://scipy.github.io/devdocs/reference/optimize.root_scalar-secant.html
but not with the table on
https://scipy.github.io/devdocs/reference/generated/scipy.optimize.root_scalar.html
I'm not sure which is correct.  The secant method needs a second point to get started, but it wouldn't be all that
unreasonable to have `if x1 is None: x1 = x0+1`. 

Statement 2 raises `ValueError: fprime must be specified for newton`.  This disagrees with
https://scipy.github.io/devdocs/reference/optimize.root_scalar-newton.html
and the table on
https://scipy.github.io/devdocs/reference/generated/scipy.optimize.root_scalar.html
I'm not sure what is desired.  Newton's method needs fprime in order to work, but there are ways to approximate fprime.
But if fprime is approximated, is it still correct to call it Newton's method?
And would someone even want to use Newton's method if they don't have fprime, or should they use a different method?

**Comment by lucascolley** [comment]
@mdhaber this comes from gh-17691

**Comment by lucascolley** [comment]
just to check, which version of SciPy are you using @teepeemm ?

**Comment by teepeemm** [comment]
@lucascolley Forgot about that.  This was on 1.13.  Upgrading to 1.14, I no longer get the ValueErrors.  So I think that just leaves the fact that https://scipy.github.io/devdocs/reference/optimize.root_scalar-secant.html should say that `x1` is optional, not required.

**Comment by mdhaber** [comment]
```python3
import scipy
print(scipy.__version__)  # 1.14.0

from scipy.optimize import root_scalar
root_scalar(lambda x: x**3-1, x0=2)
root_scalar(lambda x: x**3-1, x0=2, method='newton')  # statement 2
# both terminate successfully
```

**Comment by nickodell** [comment]
> I'm not sure which is correct. The secant method needs a second point to get started, but it wouldn't be all that
> unreasonable to have `if x1 is None: x1 = x0+1`.

In fact, that's more or less what the current code does. (Though with 1e-4 rather than 1.)

https://github.com/scipy/scipy/blob/d48a13af42c10145b91031ba7a737ac9a439c29e/scipy/optimize/_zeros_py.py#L346-L355
