### ISSUE TITLE
DOC: sparse.linalg: Unify repeated docstrings for iterative solvers

### ISSUE THREAD

**Issue by lobpcg** [scipy/scipy#21183]
### Issue with current documentation:

Multiple functions in the module have common parameters and output and essentially the same docstrings copy pasted multiple times not always complete or consistent.

### Idea or request for content:

Write a single consistent and complete document and use decorators to propagate it to different docstrings in all relevant functions.

### Additional context (e.g. screenshots, GIFs)

See docfiller decorator in ndimage and/or docstring construction in stats/_distn_infrastructure.py

**Comment by j-bowhay** [comment]
Thanks for the suggestion. While there are advantages, as you suggest, decorators have a few disadvantages:
- Increase import time
- Docstrings do not render properly for IDEs

For these reasons, I think it is best to stick with the unfortunate duplication for now.
