### ISSUE TITLE
RFC: Should mutable default arguments be forbidden by the linter?

### ISSUE THREAD

**Issue by nickodell** [scipy/scipy#21208]
### Is your feature request related to a problem? Please describe.

Recently, in #21193, I ran into a bug where if two constraints are created, they can share a BFGS object, which can cause errors or incorrect output. This was caused by a mutable default argument.

In the PR fixing that issue, @rgommers remarked:

>Having a mutable default for a keyword is pretty much always a bug, and that should be caught in code review too.

This made me wonder if there is a linter which can find mutable default arguments. I googled this, and found that our linter, ruff, supports this through rules [B006](https://docs.astral.sh/ruff/rules/mutable-argument-default/) (forbidding the use of lists, dicts, etc in default arguments) and [B008](https://docs.astral.sh/ruff/rules/function-call-in-default-argument/) (forbidding function calls.)

This bug would have been caught by the B008 rule.

### Describe the solution you'd like.

I propose that we turn on B006 and B008, and audit every single use of mutable default arguments in SciPy. I'm willing to do all of this, but I would appreciate help.

This would produce 34 warnings for B006, and 11 warnings for B008. Here is a full list of warnings. I produced this list by editing `tools/lint.toml`, and adding B006 and B008 to the list of warnings. Then, I ran `ruff check --config=tools/lint.toml | grep B00[68]` to get all of the files which would be affected by this change.

```
doc/source/doi_role.py:22:59: B006 Do not use mutable data structures for argument defaults
doc/source/doi_role.py:22:71: B006 Do not use mutable data structures for argument defaults
doc/source/doi_role.py:32:61: B006 Do not use mutable data structures for argument defaults
doc/source/doi_role.py:32:73: B006 Do not use mutable data structures for argument defaults
scipy/_build_utils/_generate_blas_wrapper.py:82:34: B008 Do not perform function call `os.path.join` in argument defaults; instead, perform the call within the function, or read the default from a module-level singleton variable
scipy/_build_utils/_generate_blas_wrapper.py:84:36: B008 Do not perform function call `os.path.join` in argument defaults; instead, perform the call within the function, or read the default from a module-level singleton variable
scipy/_lib/_docscrape.py:140:42: B006 Do not use mutable data structures for argument defaults
scipy/_lib/_docscrape.py:561:60: B006 Do not use mutable data structures for argument defaults
scipy/_lib/_docscrape.py:602:25: B006 Do not use mutable data structures for argument defaults
scipy/cluster/hierarchy.py:3449:36: B006 Do not use mutable data structures for argument defaults
scipy/cluster/hierarchy.py:3449:57: B006 Do not use mutable data structures for argument defaults
scipy/cluster/hierarchy.py:3449:73: B006 Do not use mutable data structures for argument defaults
scipy/cluster/hierarchy.py:3451:46: B006 Do not use mutable data structures for argument defaults
scipy/cluster/hierarchy.py:3451:61: B006 Do not use mutable data structures for argument defaults
scipy/cluster/hierarchy.py:3452:58: B006 Do not use mutable data structures for argument defaults
scipy/integrate/tests/test_quadrature.py:365:62: B008 Do not perform function call `np.ones` in argument defaults; instead, perform the call within the function, or read the default from a module-level singleton variable
scipy/interpolate/tests/test_polyint.py:21:28: B006 Do not use mutable data structures for argument defaults
scipy/io/_idl.py:657:29: B006 Do not use mutable data structures for argument defaults
scipy/ndimage/_interpolation.py:231:60: B006 Do not use mutable data structures for argument defaults
scipy/optimize/_constraints.py:108:57: B008 Do not perform function call `BFGS` in argument defaults; instead, perform the call within the function, or read the default from a module-level singleton variable
scipy/optimize/_lsq/least_squares.py:244:65: B006 Do not use mutable data structures for argument defaults
scipy/optimize/_lsq/least_squares.py:245:70: B006 Do not use mutable data structures for argument defaults
scipy/optimize/_numdiff.py:278:65: B006 Do not use mutable data structures for argument defaults
scipy/optimize/_numdiff.py:705:29: B006 Do not use mutable data structures for argument defaults
scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py:49:32: B008 Do not perform function call `np.empty` in argument defaults; instead, perform the call within the function, or read the default from a module-level singleton variable
scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py:49:52: B008 Do not perform function call `np.empty` in argument defaults; instead, perform the call within the function, or read the default from a module-level singleton variable
scipy/optimize/tests/test_linprog.py:453:47: B006 Do not use mutable data structures for argument defaults
scipy/sparse/linalg/_dsolve/linsolve.py:336:47: B006 Do not use mutable data structures for argument defaults
scipy/sparse/linalg/_dsolve/linsolve.py:404:40: B008 Do not perform function call `type` in argument defaults; instead, perform the call within the function, or read the default from a module-level singleton variable
scipy/sparse/linalg/_dsolve/linsolve.py:499:40: B008 Do not perform function call `type` in argument defaults; instead, perform the call within the function, or read the default from a module-level singleton variable
scipy/spatial/tests/test_distance.py:259:39: B008 Do not perform function call `partial` in argument defaults; instead, perform the call within the function, or read the default from a module-level singleton variable
scipy/spatial/tests/test_distance.py:280:36: B008 Do not perform function call `partial` in argument defaults; instead, perform the call within the function, or read the default from a module-level singleton variable
scipy/special/tests/test_orthogonal_eval.py:43:50: B006 Do not use mutable data structures for argument defaults
scipy/special/tests/test_orthogonal_eval.py:43:62: B006 Do not use mutable data structures for argument defaults
scipy/special/tests/test_orthogonal_eval.py:148:45: B006 Do not use mutable data structures for argument defaults
scipy/special/tests/test_orthogonal_eval.py:148:57: B006 Do not use mutable data structures for argument defaults
scipy/special/utils/datafunc.py:32:36: B006 Do not use mutable data structures for argument defaults
scipy/stats/_axis_nan_policy.py:338:55: B006 Do not use mutable data structures for argument defaults
scipy/stats/_morestats.py:1174:63: B008 Do not perform function call `_BigFloat` in argument defaults; instead, perform the call within the function, or read the default from a module-level singleton variable
scipy/stats/_mstats_basic.py:3196:24: B006 Do not use mutable data structures for argument defaults
scipy/stats/_mstats_extras.py:28:28: B006 Do not use mutable data structures for argument defaults
scipy/stats/_mstats_extras.py:150:31: B006 Do not use mutable data structures for argument defaults
scipy/stats/_mstats_extras.py:264:21: B006 Do not use mutable data structures for argument defaults
scipy/stats/_mstats_extras.py:309:32: B006 Do not use mutable data structures for argument defaults
scipy/stats/_stats_py.py:3680:44: B006 Do not use mutable data structures for argument defaults
```

The disadvantage of turning on these warnings is that some of them are false positives. For example, in `scipy/stats/_morestats.py`, there is a function call to create an object for a default:

https://github.com/scipy/scipy/blob/941d5b08614841a213019990b6ceee83a05d6dcc/scipy/stats/_morestats.py#L1173-L1175

However, this is not a bug, because the object is never modified.

On the other hand, some uses of mutable default arguments are bugs. For example, the use of mutable default arguments in NonlinearConstraint is a bug, as discussed in #21193.

### Points to discuss

1. Is the juice worth the squeeze? Are the false positives worth the bugs that could be found?
2. Should we do the audit before or after turning on the warning in main?

   The advantage of turning the warning on in main first is that it distributes the work - any PR which edits a file will need to solve all mutable default argument warnings in that file before linting will pass.

   The disadvantage is that it might annoy people working on other features, or cause different PRs to have a merge conflict when they fix the same mutable default argument.
3. Suppose we have a case where we're pretty sure that the mutable default is not a bug. Is it better to:
   1. Mark it `# noqa`, or
   2. Replace it with an immutable equivalent/a None value plus an if statement/a singleton, depending on developer intent.

   The first option reduces the risk of an unintended regression, and minimizes the amount of change. The second option prioritizes code quality, and may make the code easier to reason about, but could introduce new bugs if e.g. a tuple acts differently than a list in some contexts.

**Comment by lucascolley** [comment]
> Should we do the audit before or after turning on the warning in main?
>
> The advantage of turning the warning on in main first is that it distributes the work - any PR which edits a file will need to solve all mutable default argument warnings in that file before linting will pass.
> 
> The disadvantage is that it might annoy people working on other features, or cause different PRs to have a merge conflict when they fix the same mutable default argument.

The approach we have taken elsewhere is to fix in one go. Ruff's detection sometimes improves so this may still lead to a distribution of work, but less annoyance upfront. The amount of warnings here should mean that the annoyance from merge conflicts would be minimal.

**Comment by mdhaber** [comment]
Yeah, probably most of these aren't bugs, but I think it would be relatively easy to fix these in one go and begin enforcing the role. Option 3ii is formulaic enough that it seems safe, right?

**Comment by fancidev** [comment]
I think it’s a good idea to enforce the lint check. To avoid noise it could be done *after* fixing those warnings. 34+11 doesn’t sound a lot and sounds quite feasible to fix!

Whether the warning is a false positive is not the most important, in my opinion. The point of these linter rules is that with immutable default arguments, one can be sure the code is free of default-argument-mutation type of bugs *without* having to look into what the code actually does with the default value of the argument.

**Comment by rgommers** [comment]
Agreed with the responses so far: good idea to add the check, and fixing them in one go with 3ii.

**Comment by nickodell** [comment]
Alright, it sounds like there's a consensus that this is worth fixing.

Here's a checklist of currently unfixed issues, organized by module. I'll keep this up-to-date.

- [ ] doc.source
  - [ ] B006: doc/source/doi_role.py:22
  - [ ] B006: doc/source/doi_role.py:22
  - [ ] B006: doc/source/doi_role.py:32
  - [ ] B006: doc/source/doi_role.py:32
- [ ] scipy._build_utils
  - [ ] B008: scipy/_build_utils/_generate_blas_wrapper.py:82
  - [ ] B008: scipy/_build_utils/_generate_blas_wrapper.py:84
- [ ] scipy._lib
  - [ ] B006: scipy/_lib/_docscrape.py:140
  - [ ] B006: scipy/_lib/_docscrape.py:561
  - [ ] B006: scipy/_lib/_docscrape.py:602
- [ ] scipy.cluster
  - [ ] B006: scipy/cluster/hierarchy.py:3449
  - [ ] B006: scipy/cluster/hierarchy.py:3449
  - [ ] B006: scipy/cluster/hierarchy.py:3449
  - [ ] B006: scipy/cluster/hierarchy.py:3451
  - [ ] B006: scipy/cluster/hierarchy.py:3451
  - [ ] B006: scipy/cluster/hierarchy.py:3452
- [ ] scipy.integrate
  - [ ] B008: scipy/integrate/tests/test_quadrature.py:365
- [ ] scipy.interpolate
  - [ ] B006: scipy/interpolate/tests/test_polyint.py:21
- [ ] scipy.io
  - [ ] B006: scipy/io/_idl.py:657
- [ ] scipy.ndimage
  - [ ] B006: scipy/ndimage/_interpolation.py:231
- [ ] scipy.optimize
  - [x] B008: scipy/optimize/_constraints.py:108
  - [ ] B006: scipy/optimize/_lsq/least_squares.py:244
  - [ ] B006: scipy/optimize/_lsq/least_squares.py:245
  - [ ] B006: scipy/optimize/_numdiff.py:278
  - [ ] B006: scipy/optimize/_numdiff.py:705
  - [ ] B008: scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py:49
  - [ ] B008: scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py:49
  - [ ] B006: scipy/optimize/tests/test_linprog.py:453
- [ ] scipy.sparse
  - [ ] B006: scipy/sparse/linalg/_dsolve/linsolve.py:336
  - [ ] B008: scipy/sparse/linalg/_dsolve/linsolve.py:404
  - [ ] B008: scipy/sparse/linalg/_dsolve/linsolve.py:499
- [ ] scipy.spatial
  - [ ] B008: scipy/spatial/tests/test_distance.py:259
  - [ ] B008: scipy/spatial/tests/test_distance.py:280
  - [ ] B006: scipy/special/tests/test_orthogonal_eval.py:43
  - [ ] B006: scipy/special/tests/test_orthogonal_eval.py:43
  - [ ] B006: scipy/special/tests/test_orthogonal_eval.py:148
  - [ ] B006: scipy/special/tests/test_orthogonal_eval.py:148
- [ ] scipy.special
  - [ ] B006: scipy/special/utils/datafunc.py:32
- [ ] scipy.stats
  - [ ] B006: scipy/stats/_axis_nan_policy.py:338
  - [ ] B008: scipy/stats/_morestats.py:1174
  - [ ] B006: scipy/stats/_mstats_basic.py:3196
  - [ ] B006: scipy/stats/_mstats_extras.py:28
  - [ ] B006: scipy/stats/_mstats_extras.py:150
  - [ ] B006: scipy/stats/_mstats_extras.py:264
  - [ ] B006: scipy/stats/_mstats_extras.py:309
  - [ ] B006: scipy/stats/_stats_py.py:3680

**Comment by mdhaber** [comment]
Let's make sure we agree on the approach. I can do it if nobody else wants to.
- Shall we define a `_NoValue` object somewhere central, like `_lib._util`, if it doesn't exist yet? I'd suggest that we use that to avoid the possibility that we pick a value (e.g. `None`) that could means something else for the function.
- Function signature changes from `arg=<mutable_default>` to `arg=_NoValue`
- First line of the function is `arg = <mutable_default> if arg is _NoValue else arg`?

**Comment by ev-br** [comment]
Doi_role is vendored code, and might be lower prio since it's only used for
the doc builds

чт, 18 июл. 2024 г., 20:17 Nick ODell ***@***.***>:

**Comment by j-bowhay** [comment]
> Let's make sure we agree on the approach. I can do it if nobody else wants to.
> 
> 1. Shall we define a `_NoValue` object somewhere central, like `_lib._util`, if it doesn't exist yet? (Probably already does - if you know offhand, LMK.) I'd suggest that we use that to avoid the possibility that we pick a value (e.g. `None`) that could means something else for the function.
> 2. Function signature changes from `arg=<mutable_default>` to `arg=_NoValue`
> 3. First line of the function is `arg = <mutable_default> if arg is _NoValue else arg`?

There is a `_NoValue` we have been using for deprecations
https://github.com/scipy/scipy/blob/fdf15ba134fcfeaba52cf23d9903d43b3da04344/scipy/_lib/deprecation.py#L10-L12

**Comment by mdhaber** [comment]
OK, shall we move it to `_util.py` if it could be valuable here? Thoughts on the rest?

**Comment by j-bowhay** [comment]
Relocating it seems reasonable. One thing to check is I can't remember how nice `_NoValue` looks in the rendered docs compared to `None`. It might be fine I just can't remember!

**Comment by rgommers** [comment]
Please only use `_NoValue` when it is actually necessary (i.e. it matters whether the user explicitly passed `None` or not - which is rare). It indeed renders worse, and also the code is harder to understand. I'd expect that a large majority, mostly likely all cases, can use `None` just like the PR that triggered this issue (gh-21203).

**Comment by nickodell** [comment]
> Let's make sure we agree on the approach. I can do it if nobody else wants to.

Ah, sorry for jumping the gun.
 
> Shall we define a `_NoValue` object somewhere central, like `_lib._util`, if it doesn't exist yet? (Probably already does - if you know offhand, LMK.) I'd suggest that we use that to avoid the possibility that we pick a value (e.g. `None`) that could means something else for the function.

My preference is to keep the API consistent wherever possible. For most cases where SciPy has some default which is automatically created from other arguments or otherwise dynamically constructed, SciPy uses None to signal this. To pick a random example from our docs, [scipy.optimize.minimize](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html) has an argument jac, which defaults to numeric differentiation if not provided. We signal this by setting the default to None.

If we set a default to _NoValue, then we're signaling to users that this is different. In some cases this may be necessary to keep backwards compatibility. In that case it's unavoidable. But my preference, as a matter of style, is to use None unless there's a reason not to.

Here would be my proposed strategy, in order of most preferred solution to least:

1. Determine if the author intended a singleton default value. [Example](https://github.com/scipy/scipy/blob/77060bc96ba19098cf0459fd495065b125e2fb7b/scipy/stats/_morestats.py#L1174). If a singleton is intended, move the function call outside of the function definition to a global variable. Stop here.
2. Determine if the argument can be replaced with an immutable equivalent. [Example](https://github.com/scipy/scipy/blob/77060bc96ba19098cf0459fd495065b125e2fb7b/scipy/stats/_mstats_extras.py#L150). If so, do that. Stop here.
3. Look at the docstring. Look for code which would error if the argument is None, eg. `arg[0]` or `arg.method()`. [Example](https://github.com/scipy/scipy/blob/77060bc96ba19098cf0459fd495065b125e2fb7b/scipy/optimize/_numdiff.py#L278). Determine if None is allowed as an argument value. If providing None as a value is not allowed, replace argument default with None. Use if statement (or ternary if, I don't mind either way) to replace None with the intended default. Stop here.
4. Replace default with _NoValue. This always works, as no functions with mutable defaults currently allow _NoValue as an argument. Use if to replace None with the intended default.

I think 90% of cases could be resolved without _NoValue, but there are probably some cases where we can't prove that any of the other transformations are safe.

>Doi_role is vendored code, and might be lower prio since it's only used for the doc builds

Ah, thanks. Should those just be marked `# noqa: B006`, then?

**Comment by mdhaber** [comment]
`__repr__` is really nice for changing the string representation of an object, but you're welcome to do that instead. I just wanted to make sure that if I put the time in I didn't find out these preferences afterwards.
