### ISSUE TITLE
DOC: stats: `boxcox_normmax` docstring is incorrect about `ymax` default

### ISSUE THREAD

**Issue by nickodell** [scipy/scipy#21229]
### Issue with current documentation:

Here is the current documentation for boxcox_normmax:

>ymax: float, optional
>
>The unconstrained optimal transform parameter may cause Box-Cox transformed data to have extreme magnitude or even overflow. This parameter constrains MLE optimization such that the magnitude of the transformed x does not exceed ymax. **The default is the maximum value of the input dtype.** If set to infinity, [boxcox_normmax](https://scipy.github.io/devdocs/reference/generated/scipy.stats.boxcox_normmax.html#scipy.stats.boxcox_normmax) returns the unconstrained optimal lambda. Ignored when method='pearsonr'.

However, the code does not do this.

```
    if isinstance(ymax, _BigFloat):
        dtype = x.dtype if np.issubdtype(x.dtype, np.floating) else np.float64
        # 10000 is a safety factor because `special.boxcox` overflows prematurely.
        ymax = np.finfo(dtype).max / 10000
        end_msg = f"overflow in {dtype}."
```

Rather than set ymax to the maximum value of the input dtype, it sets it to the maximum value of the input dtype divided by 10000.

### Idea or request for content:

Proposed new phrasing:

>The default is the maximum value of the input dtype divided by 10000.

Here is an alternative phrasing of the same idea. The goal I was going for in this rephrasing is that this documentation sounds too much like "The default is the maximum value of the input divided by 10000," which is wrong.

>The default value is calculated based on the input array's data type, or dtype. It is determined by dividing the dtype's maximum value by 10,000.

Alternatively, it could be argued that this is too complex and not likely to be useful. Instead, we could be to remove this sentence.

**Comment by alex-rimerman** [comment]
I can change that line for you. I think that makes sense.

**Comment by lucascolley** [comment]
I vote for the 'alternative phrasing'

**Comment by nickodell** [comment]
> I can change that line for you. I think that makes sense.

That sounds good. Would you like to send a PR? There is a guide here for making documentation changes: https://docs.scipy.org/doc/scipy/dev/contributor/rendering_documentation.html#contributing-docs

If you have any questions about how to do this, feel free to ask.

**Comment by alex-rimerman** [comment]
Sounds great! Just did the changes and sent the PR.

**Comment by alex-rimerman** [comment]
https://github.com/scipy/scipy/pull/21589

**Comment by nickodell** [comment]
Closing, see discussion in https://github.com/scipy/scipy/pull/21589 for why.
