### ISSUE TITLE
ENH: Add a Python level lapack wrapper for DSYTRS

### ISSUE THREAD

**Issue by graphic-goose** [scipy/scipy#21239]
### Is your feature request related to a problem? Please describe.

I've been prototyping a global RBF solver that can scale to hundreds of thousands or even millions of input points  and as part of that I'm using DSYTRF to perform LDL^T factorisation of the augemented kernel matrix (as I need to account for positive semi-definite matrices, which rules out LL^T), which there's a Python level wrapper for (thanks!). 
However, I found that the triangular solver that can use this factorisation and pivot information (DSYTRS) doesn't have a Python level wrapper. 

### Describe the solution you'd like.

A Python level wrapper for DSYTRS in scipy.linalg.lapack

### Describe alternatives you've considered.

I found that DSYTRS did have a Cython wrapper, though (again, thanks!) so I was able to work around it by creating my own Cython function and a convenience Python function to call it, but it'd certainly be nicer to have a built in Python level wrapper to call.

### Additional context (e.g. screenshots, GIFs)

My Cython wrapper was:
```
# cython: wraparound = False
# cython: boundscheck = False

from scipy.linalg.cython_lapack cimport dsytrs

cpdef lapack_dsytrs(
    char* UPLO,
    int N,
    int NRHS,
    double[::1] A,
    int LDA,
    int[::1] IPIV,
    double[::1] B,
    int LDB,
):
    cdef int INFO
    dsytrs(UPLO, &N, &NRHS, &A[0], &LDA, &IPIV[0], &B[0], &LDB, &INFO)

    return INFO
```

And my Python wrapper for this:
```
    def dsytrs(A: np.ndarray, IPIV: np.ndarray, B: np.ndarray) -> np.ndarray:
    """Convenience function for Scipy's Lapack dsytrs wrapper.

    DSYTRS solves a system of linear equations A*X = B with a real
    symmetric matrix A using the factorization A = U*D*U**T or
    A = L*D*L**T computed by DSYTRF.

    Can handle symmetric semi-definite matrices.

    Parameters
    ----------
    L : np.ndarray
        Lower triangle matrix as factorised by Lapack's dsytrf.
    IPIV : np.ndarray
        Integer array as output by dsytrf.
    B : np.ndarray
        RHS vector.

    Returns
    -------
    X : np.ndarray
        Solution to the linear system.

    """
    UPLO = b"L"

    N = A.shape[0]

    LDA = A.shape[1]

    LDB = B.shape[0]

    NRHS = 1

    # Flatten A into a Fortran column-major array
    A = A.flatten("F")

    B = B.flatten("F")

    # Ensure B is writable
    B = np.ascontiguousarray(B)
    B.flags.writeable 

    info = lapack_dsytrs(
        UPLO,
        N,
        NRHS,
        A,
        LDA,
        IPIV,
        B,
        LDB,
    )

    if not info == 0:
        ValueError('Error solving system.')

    return B
```

**Comment by mdhaber** [comment]
Done. Thanks @graphic-goose @ilayn!

**Comment by graphic-goose** [comment]
Awesome, thanks @mdhaber @ilayn!
