### ISSUE TITLE
DOC: add sphinx-copybutton to the documentation

### ISSUE THREAD

**Issue by mosc9575** [scipy/scipy#21241]
I suggest to add the [sphinx-copybutton](https://sphinx-copybutton.readthedocs.io/en/latest/) to the sphinx extensions.

This would allow to copy code blocks and examples to the clipboard without text prompts. This is super useful to try some code from the documentation and avoids unnecessary editing and removals for the user.

The main change will be in [conf.py](https://github.com/scipy/scipy/blob/main/doc/source/conf.py), where the extension has to be listed.

```
extensions = [
    ...
    'sphinx_copybutton'
    ...
]
```

This extension is used in other projects like `pandas` and `bokeh`, too.

If wanted, I can open a pull request.

**Comment by lucascolley** [comment]
this sounds useful to me!

**Comment by lucascolley** [comment]
feel free to send a pull request @mosc9575 !
