### ISSUE TITLE
DOC: optimize: `newton_krylov` should document assumptions about input/output length

### ISSUE THREAD

**Issue by nickodell** [scipy/scipy#21246]
### Issue with current documentation:

This might be a bug, and it might be intended behavior. I can't quite tell from the documentation.

Here is an example of how to use the `newton_krylov` function.

```
from scipy import optimize


def fun(x):
    return [x[0] + 0.5 * x[1] - 1.0,
            0.5 * (x[1] - x[0]) ** 2]


sol = optimize.newton_krylov(fun, [0, 0])
print(sol)  # [0.66731771 0.66536458]
```

For many root-finding methods in SciPy, one can solve a root-finding problem with a different number of dimensions in the input and output.

For Newton-Krylov, it appears that these must match.

Example:

```
from scipy import optimize


def fun(x):
    return [x[0] + 0.5 * x[1] - 1.0]


sol = optimize.newton_krylov(fun, [0, 0])
print(sol)
```

This creates the following exception.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [40], in <cell line: 8>()
      4 def fun(x):
      5     return [x[0] + 0.5 * x[1] - 1.0]
----> 8 sol = optimize.newton_krylov(fun, [0, 0])
      9 print(sol)

File <string>:6, in newton_krylov(F, xin, iter, rdiff, method, inner_maxiter, inner_M, outer_k, verbose, maxiter, f_tol, f_rtol, x_tol, x_rtol, tol_norm, line_search, callback, **kw)

File ~/.local/lib/python3.10/site-packages/scipy/optimize/_nonlin.py:211, in nonlin_solve(F, x0, jacobian, iter, verbose, maxiter, f_tol, f_rtol, x_tol, x_rtol, tol_norm, line_search, callback, full_output, raise_exception)
    209 # The tolerance, as computed for scipy.sparse.linalg.* routines
    210 tol = min(eta, eta*Fx_norm)
--> 211 dx = -jacobian.solve(Fx, tol=tol)
    213 if norm(dx) == 0:
    214     raise ValueError("Jacobian inversion yielded zero vector. "
    215                      "This indicates a bug in the Jacobian "
    216                      "approximation.")

File ~/.local/lib/python3.10/site-packages/scipy/optimize/_nonlin.py:1501, in KrylovJacobian.solve(self, rhs, tol)
   1499     sol, info = self.method(self.op, rhs, **self.method_kw)
   1500 else:
-> 1501     sol, info = self.method(self.op, rhs, rtol=tol, **self.method_kw)
   1502 return sol

File ~/.local/lib/python3.10/site-packages/scipy/sparse/linalg/_isolve/lgmres.py:122, in lgmres(A, b, x0, rtol, atol, maxiter, M, callback, inner_m, outer_k, outer_v, store_outer_Av, prepend_outer_v)
     15 def lgmres(A, b, x0=None, *, rtol=1e-5, atol=0., maxiter=1000, M=None, callback=None,
     16            inner_m=30, outer_k=3, outer_v=None, store_outer_Av=True,
     17            prepend_outer_v=False):
     18     """
     19     Solve a matrix equation using the LGMRES algorithm.
     20 
   (...)
    120     True
    121     """
--> 122     A,M,x,b,postprocess = make_system(A,M,x0,b)
    124     if not np.isfinite(b).all():
    125         raise ValueError("RHS must contain only finite numbers")

File ~/.local/lib/python3.10/site-packages/scipy/sparse/linalg/_isolve/utils.py:68, in make_system(A, M, x0, b)
     65 A = aslinearoperator(A)
     67 if A.shape[0] != A.shape[1]:
---> 68     raise ValueError(f'expected square matrix, but got shape={(A.shape,)}')
     70 N = A.shape[0]
     72 b = asanyarray(b)

ValueError: expected square matrix, but got shape=((1, 2),)
```

### Idea or request for content:

Assuming this is intended behavior, I would suggest adding a note to the documentation. e.g.

>F function(x) -> f
>
>Function whose root to find; should take and return an array-like object. The length of the returned object must be the same as the length of the input.

### Additional context (e.g. screenshots, GIFs)

I was looking into this because of [this StackOverflow question](https://stackoverflow.com/questions/78781325/suspected-code-error-in-root-function-when-optimizing-with-newton-krylov-from?noredirect=1#comment138907177_78781325), which asks about Newton-Krylov with input and output dimensions being mismatched.

**Comment by Jrmy-rbr** [comment]
Hello, 

Just by curiosity, could you tell me which method works with input and outpout dimension mismatch? I've tried the following methods, and they all crashed at some point when using them with an output dimension that does not match the input dimension:
`root(method=’hybr’), root(method=’lm’), root(method=’broyden1’), root(method=’broyden2’)], root(method=’anderson’), root(method=’linearmixing’), root(method=’diagbroyden’), root(method=’excitingmixing’), root(method=’krylov’), root(method=’df-sane’)`

**Comment by nickodell** [comment]
@Jrmy-rbr

>Just by curiosity, could you tell me which method works with input and outpout dimension mismatch?

Odd - for some reason I thought calling `root()` with no arguments worked, but it does not. Perhaps I was using `root_scalar()`? Anyhow, it seems like the premise of this issue is incorrect.

Good investigation, and thanks for the sanity check.
