### ISSUE TITLE
DOC: `sampling_tdr.rst` failing in CircleCI smoke-tutorials job

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#21250]
Failure from [this log](https://app.circleci.com/pipelines/github/scipy/scipy/28971/workflows/12e90e53-9f1d-4911-894d-4fe6c665204a/jobs/97711):

```
doc/source/tutorial/stats/sampling_srou.rst x                            [ 96%]
doc/source/tutorial/stats/sampling_tdr.rst F                             [100%]

=================================== FAILURES ===================================
__________________________ [doctest] sampling_tdr.rst __________________________
154     527
155     >>> dist2 = StandardNormal()
156     >>> # use the same stream of uniform random numbers
157     >>> rng2 = TransformedDensityRejection(dist2, max_squeeze_hat_ratio=0.999,
158     ...                                    random_state=urng2)
159     >>> dist2.callbacks  # evaluations during setup
160     467
161     >>> dist2.callbacks = 0  # don't consider evaluations during setup
162     >>> rvs = rng2.rvs(100000)
163     >>> dist2.callbacks  # evaluations during sampling
Expected:
    84
Got:
    57

/home/circleci/repo/doc/source/tutorial/stats/sampling_tdr.rst:163: DocTestFailure
=========================== short test summary info ============================
FAILED doc/source/tutorial/stats/sampling_tdr.rst::sampling_tdr.rst
=================== 1 failed, 25 passed, 6 xfailed in 28.12s ===================
```

This tutorial was the first one to be converted to MyST-md (although it is 7 weeks ago, in gh-20303), so perhaps the seeding for the test machinery doesn't work anymore? @melissawm you may be able to say more here?

**Comment by lucascolley** [comment]
at least recently, this failure was hidden by some `smoke-docs` failures (gh-21238), so it may have been failing silently for a little while

**Comment by lobpcg** [comment]
currently keeps failing in the main, e.g., 
https://app.circleci.com/pipelines/github/scipy/scipy/29000/workflows/00568108-1ab8-4942-88f2-c562e26c640e/jobs/97812

**Comment by melissawm** [comment]
I had to double check, but indeed we did not touch this tutorial (yet?): https://github.com/scipy/scipy/commits/main/doc/source/tutorial/stats/sampling_tdr.rst

This is still an rst file. Perhaps this has been silently failing for a while, and the failure is not being flagged by a new config in smoke-tests?

**Comment by ev-br** [comment]
These sampling_*.rst tutorials are problematic in more than one way, can just add the failing one to the xfail list at
https://github.com/scipy/scipy/blob/main/scipy/conftest.py#L413

unless someone is up to fixing the actual problems, that is :-).
