### ISSUE TITLE
BUG: optimize: `DCSRCH.__call__` returns `None` step size when `task[:4] == b"WARN"`

### ISSUE THREAD

**Issue by antoinecollet5** [scipy/scipy#21251]
### Describe your issue.

In the `DCSRCH.__call__` method, introduced in #19060, the steplength becomes `None` if task[:4] == b"WARN"
https://github.com/scipy/scipy/blob/9525f45c1cb9068bcb8e02d8fd81abc0c6f4e4ae/scipy/optimize/_dcsrch.py#L264-L265

In my opinion this should not be the case. For instance, if the steplength equals the maximum steplength, then this assertion is true, and I do not see why it is considered as a failure -> it means the maximum steplength offers the best decrease. If you look at the original minpack2 implementation, a "WARN" is considered a success.

https://github.com/scipy/scipy/blob/f133c27843a36c8fe1c2979b3a072ac4f5a00624/scipy/optimize/minpack2/dcsrch.f#L255

### Reproducing Code Example

```python
import numpy as np
NDArrayFloat = np.typing.NDArray[np.float64]
import scipy as sp

def fun(x: NDArrayFloat) -> float:
    """Scalar function to minimize."""
    return np.sum(x ** 2)

def grad(x: NDArrayFloat) -> NDArrayFloat:
    """Gradient of the function to minimize."""
    return  2 * x

# starting point
x0 = np.array([1.0, -1.0, 0.0])
# search direction = - gradient at the starting point
d = -grad(x0)

def phi(alpha: float) -> float:
    """Return the objective function for a steplength of `alpha`"""
    return fun(x0 + alpha * d)

def dphi(alpha: float) -> NDArrayFloat:
    """Return the gradient of `phi` with respect to alpha."""
    return grad(x0 + alpha * d).dot(d)

# Create an instance of DCSRCH with the step in the interval [0.0, 0.02]
ftol = 1e-4
gtol = 0.9
xtol = 1e-5
stp_max = 0.02
dcsrch = sp.optimize._dcsrch.DCSRCH(
    phi, dphi, ftol, gtol, xtol, 0.0, stp_max
)



steplength, f0, _, task = dcsrch(
    stp_max, maxiter=30
)

# So it is seen as a failure
print(f"task = {task}")
print(f"steplength = {steplength}")

# while there is a deacrease in the objective function
print(f"phi(0.0) = {phi(0.0)}")
print(f"phi({stp_max}) = {phi(stp_max)}")
```

### Error message

```shell
task = b'WARNING: STP = STPMAX'
steplength = None
phi(0.0) = 2.0
phi(0.02) = 1.8432
```

This is not a big decrease, yet, it should not return None.

### SciPy/NumPy/Python version and system information

```shell
pyhton 3.11.5
INFO:root:numpy                       = 1.25.2
INFO:root:scipy                       = 1.13.1
```

**Comment by andyfaff** [comment]
One needs to consider the context in which DCSRCH is being used, see https://github.com/scipy/scipy/pull/19060.

`_dcsrch.py` was introduced as a replacement for the minpack2/dcsrch.f version when used in [`_linesearch.scalar_search_wolfe1`](https://github.com/scipy/scipy/pull/19060/files#diff-6f7f0476ada3c8947c88ec3b9ac87a301de9dddb9b011629b7758d97172922a3). Specifically at the end of the loop we have:

```
    if task[:5] == b'ERROR' or task[:4] == b'WARN':
        stp = None  # failed
```.

i.e. `DCSRCH.__call__` is meant to replace `minpack2/dcsrch.f` AND the loop in `_linesearch.scalar_search_wolfe1`. To replicate the usage of the original fortran code one should create the `DCSRCH` object and use `_iterate` directly.

**Comment by antoinecollet5** [comment]
Then `DCSRCH` is a replacement of [_linesearch.scalar_search_wolfe1](https://github.com/scipy/scipy/pull/19060/files#diff-6f7f0476ada3c8947c88ec3b9ac87a301de9dddb9b011629b7758d97172922a3) and not `minpack2/dcsrch.f` itself.

What I personally do not like about what you propose is that `_iterate` is private and is not supposed to be used. In addition there is no guarantee of backward compatibility with private methods... so my code could be broken in the future.

Maybe `_iterate` should be renamed or wrapped as `dcsrch` ? The main issue is that for all codes using the scipy interface to minpack2, the upgrade is quite messy since replacement functions and classes have been created but do not match the old interface. You have to "guess" the new logic which is not desirable.

**Comment by andyfaff** [comment]
`optimize._dcsrch` is private, and is not expected to be used by external code. Only functions that are directly importable from `optimize` are public.

**Comment by antoinecollet5** [comment]
Hummm, that's a very good point @andyfaff ! So it the end it means that `minpack2` will simply be suppressed without replacement ?

**Comment by antoinecollet5** [comment]
@andyfaff, anyway,  my initial point still holds: 

> if task[:5] == b'ERROR' or task[:4] == b'WARN':
>         stp = None  # failed

I do not really understand this behavior in [_linesearch.scalar_search_wolfe1](https://github.com/scipy/scipy/pull/19060/files#diff-6f7f0476ada3c8947c88ec3b9ac87a301de9dddb9b011629b7758d97172922a3) either.

**Comment by andyfaff** [comment]
When converting dcsrch to Python replication of the former behaviour was important.

**Comment by andyfaff** [comment]
removal of these Fortran codes is the idea.

**Comment by antoinecollet5** [comment]
@andyfaff, ok I understand the work that as been done and this is great job. But what do you think about the behavior of the function ?

**Comment by andyfaff** [comment]
DCSRCH._iterate has the same behaviour as the Fortran code. DCSRCH.__call__ mimics how it was being used by the line search previously.
I.e. there is no changed behaviour when viewed from outside, with no compatibility issues.

**Comment by antoinecollet5** [comment]
Yes I understood that. What I question in the end, is the behavior of the old implementation, and therefore of the new one.

**Comment by ilayn** [comment]
By the way i wrote again all this in C and we can expose it there if need be in the lbfgsb rewrite.
