### ISSUE TITLE
DOC: CosineMixture function in go_benchmark_functions is wrong

### ISSUE THREAD

**Issue by roger-lee-0038** [scipy/scipy#21266]
### Issue with current documentation:

The CosineMixture function in  go_benchmark_functions refers to Jamil's paper, where the expression is wrong. The right expression can be found in ’A Numerical Evaluation of Several Stochastic
Algorithms on Selected Continuous Global Optimization Test Problems‘, with the global maximum at the origin and the maximum value is 0.1N. Negating this expression, we have the global minimum value as  -0.1N at the origin.

**Comment by andyfaff** [comment]
Quite possibly. I found lots of mistakes when I was writing those. But sometimes there's also variation in those problems from article to article.
