### ISSUE TITLE
_fitpack_impl: dfitpack_int need to be changed np.int32

### ISSUE THREAD

**Issue by ZORO-Q** [scipy/scipy#21289]
https://github.com/scipy/scipy/blob/2050d49e6b1fd512bd7eba35d3368bb5678bb7f2/scipy/interpolate/_fitpack_impl.py#L38
https://github.com/scipy/scipy/blob/2050d49e6b1fd512bd7eba35d3368bb5678bb7f2/scipy/interpolate/_fitpack_impl.py#L102-L104
https://github.com/scipy/scipy/blob/2050d49e6b1fd512bd7eba35d3368bb5678bb7f2/scipy/interpolate/_fitpack_impl.py#L211-L213
dfitpack_int need to be changed np.int32 in my code, is my scipy version incorrect?

**Comment by lucascolley** [comment]
Hi @ZORO-Q, please could you follow our bug report template, by providing:

- what code you have run using SciPy
- what results you have
- why the results are unexpected 
- paste the result of `import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()`

**Comment by lucascolley** [comment]
closing due to no reply, but please reopen if you have time to come back and submit a full bug report @ZORO-Q !
