### ISSUE TITLE
TST: ndimage: GPU test failures

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#21292]
@ev-br I just gave the ndimage tests a whirl on GPU. Looks like you covered CuPy and JAX well, but there are *a lot* of failures with PyTorch. We need to figure out how to skip on GPU while still testing CuPy. The crude way to do this is to just add skips for `torch` specifically , which may be the best option for now.

https://gist.github.com/lucascolley/62e223fa893204ffc51da057457a641b

**Comment by ev-br** [comment]
But this is expected, right? GPU tensors cannot be used with numpy-only compiled CPU code. torch.cpu is fine, torch gpu is not and will never be. Ditto for jax on GPU. And it's all ndimage.

**Comment by lucascolley** [comment]
yup, but that doesn't mean we want hundreds of errors when running the test suite - that is what the skip machinery is for. I think I've figured out a decent API for it, will work on a PR.
