### ISSUE TITLE
BUG: odr: pickling is not possible

### ISSUE THREAD

**Issue by TiborVoelcker** [scipy/scipy#21306]
### Is your feature request related to a problem? Please describe.

Pickling most of the `scipy.odr` objects is not possible, as the `__getattr__` method is called when loading the object. At this point, the object does not have any attributes attached.

As the current implementation assumes that `self.meta` exists. As it does not, it enters an infinite loop.

### Describe the solution you'd like.

I would like pickling to work.
I would suggest catching this edge-case by checking if the `meta` attribute is requested in `__getattr__`, and raising an `AttributeError`

**Comment by rkern** [comment]
This one, I endorse. If you have a fix that doesn't cause any backwards compatibility problems, it's worth getting in. Thank you!
