### ISSUE TITLE
BUG: integrate.simpson: `x` param is keyword only

### ISSUE THREAD

**Issue by AnkitBarik** [scipy/scipy#21300]
### Describe your issue.

Hello,

The call signature of `scipy.integrate.simpson` has a strange `*` as the second argument and specifically requires `simpson(y, x=x)` , as opposed to `simpson(y,x)` as was the case in previous scipy versions and as is presently the case for `scipy.integrate.trapezoid`. This extra `*` argument is [not documented](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.simpson.html). I suspect this is a bug? In any case, I think having the default second argument as the `x` array would make a lot more sense and would be in line with the call signature of `trapezoid` for example. Below is a minimal working example.

Thank you,
Ankit 

### Reproducing Code Example

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import numpy as np
from scipy.integrate import simpson

x = np.linspace(0,1,100)
y = x**2

print("Int(y)dx = %.2f" %simpson(y,x))
```

### Error message

```shell
Traceback (most recent call last):
  File "/home/ankit/test.py", line 10, in <module>
    print("Int(y)dx = %.2f" %simpson(y,x))
TypeError: simpson() takes 1 positional argument but 2 were given
```

### SciPy/NumPy/Python version and system information

```shell
1.14.0 1.25.0 sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.10.13/lib/python3.10/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.10.13/lib/python3.10/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64
    pc file directory: /project
    version: 0.3.27.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.10.13/lib/python3.10/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.10.13/lib/python3.10/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64
    pc file directory: /project
    version: 0.3.27.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-vlr41q3a/overlay/lib/python3.10/site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp310-cp310/bin/python
  version: '3.10'
```

**Comment by mdhaber** [comment]
Positional use of the second argument of `simpson` was [deprecated in SciPy 1.12](https://docs.scipy.org/doc/scipy/release/1.12.0-notes.html#id16) and removed in 1.14.

**Comment by ilayn** [comment]
It is the keyword only argument separator https://stackoverflow.com/questions/14301967

**Comment by lucascolley** [comment]
where was the decision made to make `x` keyword only? Typically parameters named `x`, `y`, `z` etc. can be used positionally, while optional parameters with descriptive names are made keyword only.

**Comment by ilayn** [comment]
Git blame says #20554

**Comment by lucascolley** [comment]
aha, I reviewed that 😅 @j-bowhay what do you think about moving the `*` between `x` and `dx`?

**Comment by lucascolley** [comment]
actually the decision on placement of the `*` came from @h-vetinari's previous PR. What do you think @h-vetinari? I can't see any discussion of the placement in that PR.

**Comment by h-vetinari** [comment]
This came from https://github.com/scipy/scipy/commit/b542c83d320bc6eb8ed8074d38cc2b5e0ce39e76, and I don't remember a good reason for the placement of `*` - sorry if it was wrong and please go ahead and change it however necessary.

**Comment by mdhaber** [comment]
I think it is is justifyable as-is, since `x` is optional (`dx` has a default value of `1.0`). The only reason I reopened the issue and deleted my original response was that this did not have a full-year deprecation period (since 1.13 was out of cycle).

**Comment by lucascolley** [comment]
Either way we should make the behaviour of `simpson` and `trapezoid` match up. My vote goes to allowing `x` to be passed positionally given the short (non-descriptive) name, as you say.

@rgommers I remember you writing somewhere about this topic, words to the effect of "it makes sense for descriptive options like `axes=` to be keyword-only, but for non-descriptive options making users write `x=x` seems worse than allowing just `x`", but I can't find it. Anyway, I agreed with that reasoning at the time.

**Comment by fancidev** [comment]
> (That said, it is a little unusual that `x` has such a short name yet is optional, and also that there is a separate argument for scalar `dx`. I can see why that is the case, but also that there are other ways it could have gone.)

It indeed doesn’t look like the optimal design that it accepts both `x` and `dx` but not both at the same time. (The two arguments are dependent rather than orthogonal.) Ideally the `dx` argument would be removed, and users who want that functionality would instead multiply the result by `dx`. Once this argument gets itself in, it’s really hard to remove it due to backward compatibility requirement.

**Comment by fancidev** [comment]
Btw the second paragraph of the [doc] (https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.simpson.html) reads:

  If there are an even number of samples, N, then there are an odd number of intervals (N-1), but Simpson’s rule requires an even number of intervals. The parameter ‘even’ controls how this is handled.
  
But the function is not documented to take an `even` argument.

**Comment by lucascolley** [comment]
gh-21333 - you're 10 hours too late :)

**Comment by lucascolley** [comment]
revisiting before branch: I have opened gh-21979 to allow `x` to be passed positionally.
