### ISSUE TITLE
BUG: Compile time error "cannot overload a member function without a ref-qualifier with a member function with ref-qualifier"

### ISSUE THREAD

**Issue by AgilentGCMS** [scipy/scipy#21325]
### Describe your issue.

I have compiled python and numpy from source on an HPC that has intel oneapi compilers, and now I'm trying to compile scipy from source to take advantage of intel MKL libraries. However, the build fails with a lot of error messages that say "cannot overload a member function without a ref-qualifier with a member function with ref-qualifier". Pasting a portion of the output below, since the full output has a lot of output from build commands and is likely not relevant to the errors encountered.

### Reproducing Code Example

```python
CC=icx CXX=icpx FC=ifx python dev.py build -C-Dblas=mkl-dynamic-lp64-iomp -C-Dlapack=mkl-dynamic-lp64-iomp
```

### Error message

```shell
../../../python/3.12.4/lib/python3.12/site-packages/pythran/pythonic/include/types/ndarray.hpp:438:5: note: previous declaration is here
  438 |     operator[](S const &s) &&;
      |     ^
../../../python/3.12.4/lib/python3.12/site-packages/pythran/pythonic/include/types/ndarray.hpp:495:5: error: cannot overload a member function without a ref-qualifier with a member function with ref-qualifier '&&'
  495 |     operator[](F const &filter) const;
      |     ^
../../../python/3.12.4/lib/python3.12/site-packages/pythran/pythonic/include/types/ndarray.hpp:438:5: note: previous declaration is here
  438 |     operator[](S const &s) &&;
      |     ^
../../../python/3.12.4/lib/python3.12/site-packages/pythran/pythonic/include/types/ndarray.hpp:503:5: error: cannot overload a member function without a ref-qualifier with a member function with ref-qualifier '&&'
  503 |     operator[](F const &filter) const;
      |     ^
../../../python/3.12.4/lib/python3.12/site-packages/pythran/pythonic/include/types/ndarray.hpp:438:5: note: previous declaration is here
  438 |     operator[](S const &s) &&;
      |     ^
15 errors generated.
[380/547] Compiling C object scipy/special/cython_special.cpython-312-x86_64-linux-gnu.so.p/meson-generated_cython_special.c.o
ninja: build stopped: subcommand failed.
Build failed!
```

### SciPy/NumPy/Python version and system information

```shell
$ python -c 'import sys, numpy; print(numpy.__version__, sys.version_info)'
2.0.1 sys.version_info(major=3, minor=12, micro=4, releaselevel='final', serial=0)
```

**Comment by nickodell** [comment]
Can you provide your operating system, the version of the Intel compilers being used, and the version of the Pythran package?

**Comment by AgilentGCMS** [comment]
Operating system: Linux (64 bit)
Intel compiler version: OneAPI 2024.1.0
Pythran version: 0.16.1

**Comment by lucascolley** [comment]
cc @serge-sans-paille

**Comment by rgommers** [comment]
We have a Linux CI job with OneAPI 2024.2.0 compilers and MKL. That seems to work fine. It should have up-to-date `numpy` and `pythran` versions as well (2.0.1 and 0.16.1, respectively). Possibly something that got fixed in OneAPI? Would you be able to test that @AgilentGCMS?

**Comment by serge-sans-paille** [comment]
All scipy kernels are also validated against latest pythran and the package `intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic` from `https://apt.repos.intel.com/oneapi`

**Comment by AgilentGCMS** [comment]
> We have a Linux CI job with OneAPI 2024.2.0 compilers and MKL. That seems to work fine. It should have up-to-date `numpy` and `pythran` versions as well (2.0.1 and 0.16.1, respectively). Possibly something that got fixed in OneAPI? Would you be able to test that @AgilentGCMS?

I'm sorry, what is a Linux CI job? Also, I think upgrading to 2024.2.0 is currently not possible; the admins just upgraded to that one from 2023.1.0 because some users bugged them, so we're stuck with that for a while.

I should say that a slightly earlier version of scipy (1.13.0) compiled fine with oneapi 2023.1.0, and I find it surprising that upgrading to oneapi 2024.1.0 would introduce problems instead of solve them.

**Comment by nickodell** [comment]
> I'm sorry, what is a Linux CI job?

It stands for Continuous Integration. For every new change to SciPy, SciPy is built on a number of platforms, and tested against our test suite. A failure to build, or a failure in the test suite, is generally fixed quickly for all of the platforms we test on. Linux + Intel OneAPI is one such platform which is part of our automated tests, as of two weeks ago.

Other platforms are not automatically tested. We rely on bug reports from users to find out if these are broken.

**Comment by rgommers** [comment]
@AgilentGCMS you can get past this particular failure if you add `-C-Duse-pythran=false` to your build invocation. That may help as a workaround.

**Comment by AgilentGCMS** [comment]
I wanted to add here that I tried building scipy 1.14.0 (i.e., same version which failed above) against numpy 1.26.4 and pythran 0.14.0 using intel oneapi compiler 2023.1.0 (basically our previous config before I tried upgrading), and it succeeded. So whatever failed was due to the interaction between the updated pythran and updated oneapi compilers. 

I then tried going back to oneapi 2024.1, numpy 2.0.1, scipy 1.14.0, but downgraded pythran to 0.14.0. That failed with the same errors as above, `error: cannot overload a member function without a ref-qualifier with a member function with ref-qualifier '&&'`.

Finally, I tried the workaround of @rgommers, disabling the use of pythran altogether. That worked! It also reminded me that I had encountered this problem before, almost a year ago, trying to build recent scipy with intel compilers using the distutils route. The solution back then was to disable the use of pythran with `export SCIPY_USE_PYTHRAN=0`. Given how fickle the interaction of oneapi with pythran is, perhaps this should be one of the first solutions proposed in the docs somewhere for people trying to build scipy with oneapi+pythran?

**Comment by rgommers** [comment]
> Given how fickle the interaction of oneapi with pythran is, perhaps this should be one of the first solutions proposed in the docs somewhere for people trying to build scipy with oneapi+pythran?

That might be useful. We currently don't have any docs on OneAPI though - it'd need a new section on this page I think: http://scipy.github.io/devdocs/building/compilers_and_options.html.
