### ISSUE TITLE
DX/BLD: fatal: bad revision '^v1.13.0'

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#21345]
@rgommers @HarshCasper any idea why I see

```
[1/41] Generating scipy/generate-version with a custom command
fatal: bad revision '^v1.13.0'
```

when building SciPy? The relevant bit of `meson` is

https://github.com/scipy/scipy/blob/87ed0cab1a60f54d5c5223fbd8e99e5545f16204/scipy/meson.build#L282-L293

**Comment by nickodell** [comment]
Looks like the command `git rev-list HEAD ^v1.13.0 --count` is failing.

Does the tag v1.13.0 exist in your repo? Does the command `git rev-parse v1.13.0` show an error?

**Comment by fancidev** [comment]
I see this message for every build, but it seems to have no effect so I always ignored it…

**Comment by lucascolley** [comment]
> `git rev-list HEAD ^v1.13.0 --count`

yes, this produces the same error message.

`git rev-parse v1.13.0` shows:

```
v1.13.0
fatal: ambiguous argument 'v1.13.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by lucascolley** [comment]
I fixed this with the command

```
git fetch upstream --tags
```

**Comment by rgommers** [comment]
This warning showed up in CI logs as well, and is fairly annoying (if harmless). Fixed in gh-21361.
