### ISSUE TITLE
CI: segfault in Accelerate job

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#21348]
From [this CI log](https://github.com/scipy/scipy/actions/runs/10310293783/job/28541742120):

```
scipy/signal/tests/test_array_tools.py ......                            [ 39%]
Fatal Python error: Segmentation fault
...
scipy/signal/tests/test_bsplines.py ......................xXXXxx
```

**Comment by nickodell** [comment]
I'm not able to reproduce this locally with an x86 mac with Accelerate. May be an ARM/Accelerate specific bug.

**Comment by lucascolley** [comment]
this doesn't appear to be showing in other runs of the job, so may be a one-off / flaky thing. I don't see why it would be related to the PR it showed up in.

**Comment by andyfaff** [comment]
I can't see this locally with M1/Accelerate.

**Comment by lucascolley** [comment]
I've re-triggered the job at https://github.com/scipy/scipy/actions/runs/10310293783/job/28603796904

**Comment by lucascolley** [comment]
the job succeeded on the second try, so let's dismiss this as a one-off and hope it doesn't re-occur
