### ISSUE TITLE
CI: Failure of 'Windows tests / no pythran & sdist+wheel, full, py3.11/npPre, pip+pytest'

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#21364]
The CI job `Windows tests / no pythran & sdist+wheel, full, py3.11/npPre, pip+pytest` on github actions has been failing on all pull requests for a while.

The problem appears to be that some of the ufuncs in `special` have been defined to accept an argument of type `long`, which is 32 bit on Windows, but the default integer type on 64 bit Windows is now 64 bit in NumPy 2.0.  So calling those ufuncs with an array of integers with the default integer type results in an error because they can't be safely cast to `long`.

The correct solution is to update all the ufuncs to use type `npy_intp` instead of `long`; see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#windows-default-integer.  This doesn't look like a simple search-and-replace operation.  It will probably involve making some updates to the ufunc code generation tool `scipy/special/_generate_pyx.py` to include the `npy_intp` type as an option.

**Comment by lucascolley** [comment]
x-ref gh-19462, gh-21052

**Comment by WarrenWeckesser** [comment]
This is a consequence of gh-21052, so closing as a dup.
