### ISSUE TITLE
BUG: spatial: Voronoi diagram missing ridges

### ISSUE THREAD

**Issue by Dhmss** [scipy/scipy#21379]
### Describe your issue.

My Voronoi diagram seems wrong, it shows several pairs of closest points that do not share any ridge, just like these points had been ignored.

Points set represents an opened contour, and by design, two adjacent points are likely a pair of closest points and should share a ridge. For instance, the following pairs of point indices have no ridge while it should have: (1010, 1011), (1011, 1012) ... (1046, 1047).

The issue can also be observed by considering the points axial symmetry that is not visible in the Voronoi diagram

- Result plot
![voronoi_issue](https://github.com/user-attachments/assets/f06bfb65-30f8-4ab9-b1f4-5d44e1623f83)

- Points to reproduce
[voronoi_issue_points.txt](https://github.com/user-attachments/files/16600646/voronoi_issue_points.txt)

### Reproducing Code Example

```python
import numpy as np
from matplotlib import pyplot as plt
from scipy.spatial import Voronoi, voronoi_plot_2d

def test_voronoi_issue():
    points = np.loadtxt('voronoi_issue_points.txt')
    vor = Voronoi(points)
    voronoi_plot_2d(vor)
    plt.show()
```

### Error message

```shell
No error, just an unexpected result
```

### SciPy/NumPy/Python version and system information

```shell
1.14.0 1.26.4 sys.version_info(major=3, minor=11, micro=8, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64
    pc file directory: /project
    version: 0.3.27.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64
    pc file directory: /project
    version: 0.3.27.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-bg_opkya/overlay/lib/python3.11/site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp311-cp311/bin/python
  version: '3.11'
```

**Comment by Dhmss** [comment]
In the following code, `missing_ridge` equals zero meaning that all adjacent points actually share a ridge (no missing ridge), but ridges not appearing in the plot seem wrong

`    missing_ridge = 0
    for i in range(points.shape[0] - 1):
        if (i, i + 1) in vor.ridge_dict:
            continue
        if (i + 1, i) in vor.ridge_dict:
            continue
        missing_ridge += 1`

**Comment by Dhmss** [comment]
Here is another case (points attached)
[voronoi_issue_points.txt](https://github.com/user-attachments/files/17057280/voronoi_issue_points.txt)

![image](https://github.com/user-attachments/assets/a7c5c554-126e-4cb6-8f0b-ffbe4943f31e)

**Comment by tylerjereddy** [comment]
I spent some time looking at this today. Broadly speaking, the high degree of collinearity in the data leads me to believe that there are some violations of [general position](https://en.wikipedia.org/wiki/General_position) happening. If generators (input points) to computational geometry algorithms are co-planar or collinear (or very nearly so), algorithms can break down for a variety of reasons.

We use Qhull under the hood for Voronoi diagrams, and it tends to deal with issues related to degeneracy or near degeneracy by either merging or "joggling" -- see here: http://www.qhull.org/html/qh-impre.htm#joggle.

For example, if I take your original generators above, I can restore non-zero Voronoi regions to the "left side" of the diagram by turning on joggling (small random perturbations of your generators that restore general position):

```python
vor = Voronoi(points, qhull_options="QJ")
```

![image](https://github.com/user-attachments/assets/1fea9c0f-9b22-49df-8767-b5aad696075e)

You may also want to consider triangulated output:

```python
vor = Voronoi(points, qhull_options="Qt")
```

![image](https://github.com/user-attachments/assets/e7938f07-1eb8-4a26-8a03-2f62c3cdcd50)

I'm not sure we have enough access to Qhull internals in SciPy to automatically detect large amounts of "merging," but perhaps I can improve the documentation for `voronoi_plot_2d` to include a more concise version of the discussion/suggestions here.
