### ISSUE TITLE
DOC/DEV: direct to building guide from quickstart guide

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#21421]
gh-21397 reported a missing dependency from [the dev quickstart guide](https://scipy.github.io/devdocs/dev/dev_quickstart.html). Quoting myself from that PR:

> This particular section hasn't been updated since last year, and mostly duplicates the info in [scipy.github.io/devdocs/building/index.html](https://scipy.github.io/devdocs/building/index.html#building-from-source-for-scipy-development), which has been updated more recently. While it is somewhat nice to have a shorter version of the instructions, it does result in more maintenance burden overall, so I think we should just point to the Building From Source guide here.

I would be happy to review a PR which rewords the quickstart guide to direct to https://scipy.github.io/devdocs/building/index.html#building-from-source-for-scipy-development for build instructions, rather than giving them directly.

**Comment by musvaage** [comment]
doc/source/building/index.rst

OS and shell

don't see rendered website OS related content here; limited to sh and pwsh

```
$ sed -n '333,355p' scipy/doc/source/building/index.rst
      .. tab-item:: Linux
        :sync: linux

        ::

          python -m venv venv
          source venv/bin/activate

      .. tab-item:: macOS
        :sync: macos

        ::

          python -m venv venv
          source venv/bin/activate

      .. tab-item:: Windows
        :sync: windows

        ::

          python -m venv venv
          .\venv\Scripts\activate
$ 
```

feasibly after activating add to the docs

```
# Check if a new release of pip is available
python -m pip install --upgrade pip
```
