### ISSUE TITLE
BUG: Combining SciPy 1.14.1 and statsmodels 0.14.2 on OSX causes "symbol not found in flat namespace '_npy_cabs'"

### ISSUE THREAD

**Issue by nickodell** [scipy/scipy#21434]
### Describe your issue.

When importing `statsmodels.api`, the following error appears:

```
ImportError: dlopen(/private/var/folders/7v/pg90myg55bs218ff8dpkrfrc0000gn/T/tmp.8CjfzJEYnh/venv/lib/python3.12/site-packages/statsmodels/tsa/statespace/_representation.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_npy_cabs'
```

This issue was [originally reported on StackOverflow](https://stackoverflow.com/questions/78900274/scipy-1-14-1-breaks-statsmodels-0-14-2). I have independently reproduced the failure on OSX, but failed to reproduce it on Linux.

Curiously, this issue only shows up when SciPy 1.14.1 is installed. If SciPy 1.14.0 is installed, this error does not show up. Similarly, if statsmodels 0.14.1 is installed, the issue also goes away.

I'm unsure if this is a bug in statsmodels or SciPy - it seems very strange that a change in another package could cause this kind of error.

`pip freeze` output:

Failing:

```
numpy==2.1.0
packaging==24.1
pandas==2.2.2
patsy==0.5.6
python-dateutil==2.9.0.post0
pytz==2024.1
scipy==1.14.1
six==1.16.0
statsmodels==0.14.2
tzdata==2024.1
```

Working:

```
numpy==2.1.0
packaging==24.1
pandas==2.2.2
patsy==0.5.6
python-dateutil==2.9.0.post0
pytz==2024.1
scipy==1.14.0
six==1.16.0
statsmodels==0.14.2
tzdata==2024.1
```

### Reproducing Code Example

```python
# My minimized reproducer
import statsmodels.api as sm


# Original reproducer
import pandas as pd
import plotly.express as px

if __name__ == "__main__":
    data = {
        "Date": [0, 7, 14, 21, 28],
        "Value": [100, 110, 120, 115, 122]
    }
    df = pd.DataFrame(data)
    px.scatter(df, x="Date", y="Value", trendline="ols")
```

### Detailed Reproduction Instructions

1. Create new virtual environment.
2. Run `pip install scipy==1.14.1 statsmodels==0.14.2`, downloading pre-built binaries. For me this is `scipy-1.14.1-cp312-cp312-macosx_14_0_arm64.whl`.
3. Run either of the reproducers. The reproducer should fail.
4. Run `pip install scipy==1.14.0 statsmodels==0.14.2`
5. Run either of the reproducers. The reproducer should succeed.

### Error message

```shell
Traceback (most recent call last):
  File "/private/var/folders/7v/pg90myg55bs218ff8dpkrfrc0000gn/T/tmp.8CjfzJEYnh/test.py", line 1, in <module>
    import statsmodels.api as sm
  File "/private/var/folders/7v/pg90myg55bs218ff8dpkrfrc0000gn/T/tmp.8CjfzJEYnh/venv/lib/python3.12/site-packages/statsmodels/api.py", line 136, in <module>
    from .regression.recursive_ls import RecursiveLS
  File "/private/var/folders/7v/pg90myg55bs218ff8dpkrfrc0000gn/T/tmp.8CjfzJEYnh/venv/lib/python3.12/site-packages/statsmodels/regression/recursive_ls.py", line 14, in <module>
    from statsmodels.tsa.statespace.mlemodel import (
  File "/private/var/folders/7v/pg90myg55bs218ff8dpkrfrc0000gn/T/tmp.8CjfzJEYnh/venv/lib/python3.12/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 33, in <module>
    from .simulation_smoother import SimulationSmoother
  File "/private/var/folders/7v/pg90myg55bs218ff8dpkrfrc0000gn/T/tmp.8CjfzJEYnh/venv/lib/python3.12/site-packages/statsmodels/tsa/statespace/simulation_smoother.py", line 11, in <module>
    from .kalman_smoother import KalmanSmoother
  File "/private/var/folders/7v/pg90myg55bs218ff8dpkrfrc0000gn/T/tmp.8CjfzJEYnh/venv/lib/python3.12/site-packages/statsmodels/tsa/statespace/kalman_smoother.py", line 11, in <module>
    from statsmodels.tsa.statespace.representation import OptionWrapper
  File "/private/var/folders/7v/pg90myg55bs218ff8dpkrfrc0000gn/T/tmp.8CjfzJEYnh/venv/lib/python3.12/site-packages/statsmodels/tsa/statespace/representation.py", line 10, in <module>
    from .tools import (
  File "/private/var/folders/7v/pg90myg55bs218ff8dpkrfrc0000gn/T/tmp.8CjfzJEYnh/venv/lib/python3.12/site-packages/statsmodels/tsa/statespace/tools.py", line 14, in <module>
    from . import (_initialization, _representation, _kalman_filter,
  File "statsmodels/tsa/statespace/_initialization.pyx", line 1, in init statsmodels.tsa.statespace._initialization
ImportError: dlopen(/private/var/folders/7v/pg90myg55bs218ff8dpkrfrc0000gn/T/tmp.8CjfzJEYnh/venv/lib/python3.12/site-packages/statsmodels/tsa/statespace/_representation.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_npy_cabs'
```

### SciPy/NumPy/Python version and system information

```shell
1.14.1 2.1.0 sys.version_info(major=3, minor=12, micro=5, releaselevel='final', serial=0)
/private/var/folders/7v/pg90myg55bs218ff8dpkrfrc0000gn/T/tmp.8CjfzJEYnh/venv/lib/python3.12/site-packages/scipy/__config__.py:154: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld64",
      "version": "13.3.0",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.16.1",
      "include directory": "../../../../../../private/var/folders/hw/1f0gcr8d6kn9ms0_wn0_57qc0000gn/T/pip-build-env-bjescfad/overlay/lib/python3.12/site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "extraframeworks",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "lapack": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "extraframeworks",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.12.0",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "/private/var/folders/hw/1f0gcr8d6kn9ms0_wn0_57qc0000gn/T/cibw-run-oogm4_8g/cp312-macosx_arm64/build/venv/bin/python",
    "version": "3.12"
  }
}
```

### Architecture

I don't know if this is relevant, but both the original reporter and I are using ARM-based hardware. (An Apple M2 in his case, and the M3 in mine.)

**Comment by nickodell** [comment]
The statsmodels maintainers suggested trying to downgrade NumPy to 2.0.1. The result works, meaning that this issue only happens for the latest NumPy plus the latest SciPy plus the latest statsmodels.

See https://github.com/statsmodels/statsmodels/issues/9333#issuecomment-2305438605 for a detailed list of the configurations I tried.

**Comment by andyfaff** [comment]
From the stacktrace I'm pretty sure that the issue lies in the `statsmodels` space, scipy doesn't appear anywhere there. 

`scipy.special` does use `npy_cabs`, it's defined in `<numpy/npy_math.h>`.

**Comment by nickodell** [comment]
From the investigation done by the statsmodels maintainer, this seems like either a statsmodels issue (in that it depends on the _npy_cabs symbol being exported by another library) or a numpy bug (in that it stops exporting _npy_cabs.) I'm not sure which, at this point.

However, SciPy's involvement seems pretty incidental. Although it does stop exporting the symbol `_npy_cabs` in 1.14.1, that doesn't really seem like part of our public API. For that reason, I'm closing in favor of the statsmodel/numpy issues.

**Comment by rgommers** [comment]
> However, SciPy's involvement seems pretty incidental. Although it does stop exporting the symbol `_npy_cabs` in 1.14.1, that doesn't really seem like part of our public API

This was on purpose at least, I tried hard to clean up symbol visibility issues and only export a single `PyInit_*` symbol from each extension module. I agreed with your conclusion here - not part of our API. I'll comment more on the numpy/statsmodels issues as needed, after looking into the root cause.

**Comment by jikaczmarski** [comment]
> The statsmodels maintainers suggested trying to downgrade NumPy to 2.0.1. The result works, meaning that this issue only happens for the latest NumPy plus the latest SciPy plus the latest statsmodels.
> 
> See [statsmodels/statsmodels#9333 (comment)](https://github.com/statsmodels/statsmodels/issues/9333#issuecomment-2305438605) for a detailed list of the configurations I tried.

Temporary solution for me was `pip install --force-reinstall numpy==2.0.0`
