### ISSUE TITLE
DOC/DEV: replace mambaforge with miniforge

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#21439]
mambaforge is deprecated after miniforge adopted `mamba`, becoming identical to mambaforge. We should replace any guidance to mambaforge in our docs with guidance to miniforge.

**Comment by Kanishk-tiwari-045** [comment]
Hey @lucascolley, I am just starting to get into this open source and stuff, so being a new comer, I would like to solve this "good first issue". Can you please assign this to me?

**Comment by lucascolley** [comment]
Hey @Kanishk-tiwari-045 , feel free to make a PR! (we typically don't assign issues in SciPy)

**Comment by Kanishk-tiwari-045** [comment]
@lucascolley Thanks for your reply. I did raised a PR.
