### ISSUE TITLE
DEV/MAINT: Allow unicode characters `±` and `∞` in source code (for linter)

### ISSUE THREAD

**Issue by fancidev** [scipy/scipy#21447]
### Is your feature request related to a problem? Please describe.

In an ongoing PR (gh-21410), I use the unicode characters `±` and `∞` in Python text string to make the code look a bit "nicer". See for example:

```python
    @pytest.mark.parametrize('rule, x, y, expected', [
        # 3 cases omitted
        (
            "pow(±0, -∞) is +∞ with no exception",
            -1.0, -np.inf, np.inf
        ),
        # 16 cases omitted
    ])
```

However, the linter complains about these characters; see https://github.com/scipy/scipy/actions/runs/10543118657/job/29210700952?pr=21410

### Describe the solution you'd like.

Add `±` and `∞` to the set of "extra" allowed unicode characters in `tools/unicode_check.py`.

### Describe alternatives you've considered.

I can replace `±` with `+/-` and `∞` with `inf` in the code. But I find the unicode characters arguably easier to read when they're shown as text message to the user.

### Additional context (e.g. screenshots, GIFs)

I have no strong opinion on whether `±` and `∞` *should* be accepted by the linter; I just find it *ok* to accept them. If the decision is to disallow them, I can simply modify the reference PR no problem. Just let me know!

**Comment by lucascolley** [comment]
This seems fine to me - @WarrenWeckesser could you give a 👍 as the author of the script?

**Comment by nickodell** [comment]
For reference, these are the characters currently allowed:

 * All ASCII characters
 * The second half of the Latin-1 Supplement: ['À', 'Á', 'Â', 'Ã', 'Ä', 'Å', 'Æ', 'Ç', 'È', 'É', 'Ê', 'Ë', 'Ì', 'Í', 'Î', 'Ï', 'Ð', 'Ñ', 'Ò', 'Ó', 'Ô', 'Õ', 'Ö', '×', 'Ø', 'Ù', 'Ú', 'Û', 'Ü', 'Ý', 'Þ', 'ß', 'à', 'á', 'â', 'ã', 'ä', 'å', 'æ', 'ç', 'è', 'é', 'ê', 'ë', 'ì', 'í', 'î', 'ï', 'ð', 'ñ', 'ò', 'ó', 'ô', 'õ', 'ö', '÷', 'ø', 'ù', 'ú', 'û', 'ü', 'ý', 'þ', 'ÿ']

   This is necessary if you want to be able to spell the names of some contributors or authors. For example, the mannwhitneyu documentation references a paper written by Andreas Löffler.
 * All [box-drawing characters](https://en.wikipedia.org/wiki/Box-drawing_characters).
 * Some miscellaneous symbols: ['®', 'ő', 'λ', 'π', 'ω', '∫', '≠', '≥', '≤', 'μ']

This proposal seems most similar to the ≠, ≥, ≤ characters, which are allowed by current lint rules.

**Comment by WarrenWeckesser** [comment]
I don't see a problem with adding those characters.
