### ISSUE TITLE
MAINT, DOC: make dist pipefail issue

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#21460]
gh-21361 generally simplified the release process, but I did want to confirm that https://github.com/scipy/scipy/pull/21361#discussion_r1731956848 isn't a problem that will affect the release process in any way:

> When I run `make dist` locally on this branch (I still use it to build docs for releases) I see /bin/sh: 1: set: Illegal option -o pipefail on this branch.

> That said, `make dist` still succeeds in the end, and the `sdist` build is also fine on this branch locally, so I'll go ahead and merge and just open a ticket for the pipefail thing just in case so I don't discover an issue during a rel process (if there is one).

If this is irrelevant just close. If we just need some extra shell prefix thing, should be quick to deal with I'd think.

**Comment by thomasjpfan** [comment]
Makefile uses POSIX shell on Linux by default and `/bin/sh` does not have a `set -o pipefail`. You can see the same error running `sh -c "set -o pipefail"`.

Note that `/bin/sh` is bash on macOS, so it does not have an issue there.
