### ISSUE TITLE
DOC: add a CITATION.cff file

### ISSUE THREAD

**Issue by reshamas** [scipy/scipy#21470]
### Suggestion
Add a `CITATION.cff` file to the repo because:  
- it would  be more visible to users
- it would provide the citation in both the APA and BibTeX versions

See example here:  
- video: https://www.linkedin.com/feed/update/urn:li:activity:7232762440747302912/

### [What is a CITATION.cff file?](https://citation-file-format.github.io/)
CITATION.cff files are plain text files with human- and machine-readable citation information for software (and datasets). Code developers can include them in their repositories to let others know how to correctly cite their software.

### References
- SciPy citation: https://scipy.org/citing-scipy/
- CITATION.bib: https://github.com/scipy/scipy/blob/main/CITATION.bib

### Background
- https://citation-file-format.github.io/#/tools-for-working-with-citationcff-files
- https://github.com/citation-file-format/cffconvert

### Examples of `CITATION.cff` files
- ArviZ: https://github.com/arviz-devs/arviz/blob/main/CITATION.cff
- matplotlib: https://github.com/matplotlib/matplotlib/blob/main/CITATION.cff
- pandas: https://github.com/pandas-dev/pandas/blob/main/CITATION.cff
- PyMC: https://github.com/pymc-devs/pymc/blob/main/CITATION.cff 
- scikit-image: https://github.com/scikit-image/scikit-image/blob/main/CITATION.cff
- scikit-learn: https://github.com/scikit-learn/scikit-learn/blob/main/CITATION.cff

**Comment by mdhaber** [comment]
Please see the two previous discussions about this.
gh-14630
gh-11609
Both times, the decision was not to add a citation.cff.

**Comment by reshamas** [comment]
@mdhaber Should we close this issue?

**Comment by melissawm** [comment]
Thanks, @reshamas 🙂
