### ISSUE TITLE
BUG: fft.fft: real-valued array-api-strict inputs fail

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#21507]
### Describe your issue.

`scipy.fft.fft` works with real- or complex-valued inputs on all "real" backends (all I checked: numpy, torch, jax.numpy, cupy). On `array_api_strict`, it errors out with `TypeError: Only complex floating-point dtypes are allowed in fft`. This seems to come from the Array API spec itself, https://data-apis.org/array-api/2023.12/extensions/generated/array_api.fft.fft.html#array_api.fft.fft lists 

```
x (array) – input array. Should have a complex floating-point data type.
```

Regardless of whether the Array API spec is not reasonable here (IMO it's not), `scipy.fft` should definitely not have this limitation.

### Reproducing Code Example

```python
In [1]: import torch

In [2]: from scipy.fft import fft

In [3]: fft(torch.arange(5))
Out[3]: 
tensor([10.0000+0.0000j, -2.5000+3.4410j, -2.5000+0.8123j, -2.5000-0.8123j,
        -2.5000-3.4410j])

In [4]: import jax.numpy as jnp

In [5]: fft(jnp.arange(5))
An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
Out[5]: 
Array([10. +0.j       , -2.5+3.440955j , -2.5+0.8122992j, -2.5-0.8122992j,
       -2.5-3.440955j ], dtype=complex64)

In [6]: import array_api_strict as xp

In [7]: fft(xp.arange(5))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[7], line 1
----> 1 fft(xp.arange(5))

.... snip ...

TypeError: Only complex floating-point dtypes are allowed in fft

```

**Comment by lucascolley** [comment]
Agreed that this is a bug. We should manually case to complex before passing to array-api-strict's fft.

**Comment by ilayn** [comment]
It should dispatch to the real FFT algorithm but not upcast. Otherwise misses out the structure in data.

**Comment by lucascolley** [comment]
> It should dispatch to the real FFT algorithm but not upcast. Otherwise misses out the structure in data.

I hadn't thought about that before. Any opinion @peterbell10 ?
