### ISSUE TITLE
DOC: add note about `args`/`kwargs` to description of callable arguments

### ISSUE THREAD

**Issue by deka27** [scipy/scipy#21504]
### Is your feature request related to a problem? Please describe.

The `approx_fprime` function in `scipy.optimize` currently does not support keyword arguments (`kwargs`) for the objective function `f`. This limitation can lead to errors or warnings when `f` is a keyword-only function, as described in [PEP 3102](https://peps.python.org/pep-3102/).

PEP 3102 introduces the concept of keyword-only arguments in Python, where arguments can be passed only by keyword and not by position. This is increasingly used in modern Python code to improve clarity and prevent errors. However, when such a function is passed to `approx_fprime`, it results in errors because `approx_fprime` only supports positional arguments through `*args`.

### Describe the solution you'd like.

Enhance `approx_fprime` to accept `kwargs` and pass them to the objective function `f`. This would align `approx_fprime` with modern Python practices, reduce potential errors, and improve its flexibility.

The updated signature could look like this:

```python
def approx_fprime(xk, f, epsilon=_epsilon, *args, **kwargs):
    ...
```

## **Example of the Issue**

Consider a function that requires keyword-only arguments:

```python
import numpy as np
from scipy.optimize import approx_fprime

def func_with_kwargs(x, *, a=1.0, b=2.0):
    return a * np.sum(x**2) + b

xk = np.array([1.0, 2.0, 3.0])
epsilon = 1e-8

# This will raise an error because approx_fprime does not support kwargs
grad = approx_fprime(xk, func_with_kwargs, epsilon, 1.0, 2.0)
```

In this case, `func_with_kwargs` cannot be passed to `approx_fprime` without a workaround, such as wrapping it in another function or using `functools.partial`, both of which add unnecessary complexity.

## Benefits
- Compatibility with Modern Python Code: By supporting `kwargs`, `approx_fprime` would be compatible with functions that utilize keyword-only arguments, as per PEP 3102.

- Ease of Use: Users would no longer need to resort to workarounds like wrappers or `functools.partial` to pass keyword arguments, making the function easier to use in a broader range of scenarios.

- Backward Compatibility: The proposed change is backward-compatible, as it would not affect existing code that only uses positional arguments.

## Conclusion
Supporting `kwargs` in `approx_fprime` would make the function more versatile, aligning it with modern Python practices and improving its usability. This enhancement would be particularly beneficial for users working with keyword-only functions, which are becoming more common in the Python ecosystem.

**Comment by andyfaff** [comment]
`approx_fprime` may be superseded in future by the differentiation functionality introduced by @mdhaber. If that happens we'll definitely bear this issue in mind.

In the meantime it'll be easy to add it to `approx_fprime`, but that opens a can of worms - do we add it for the rest of `scipy.optimize`?

As an aside, I don't quite agree with

>  aligning it with modern Python practices and improving its usability

. One could still be using modern Python practices without using kwd only arguments.

**Comment by mdhaber** [comment]
> Re: new differentiation functionality

This ([scipy.differentiate](https://scipy.github.io/devdocs/reference/differentiate.html)) and the other elementwise iterative algorithms are the only functions I know of in which `args` actually *needs* to be accepted by the SciPy function for full functionality (which I won't get into here). So there, I might actually add `kwargs`.

**Comment by fancidev** [comment]
> Ideally, I would prefer to go in the other direction (e.g. deprecate `args` and simply document the alternative), but I realize that this may be too disruptive.

+1 in this direction. If the Python philosophy  is to have one (obvious) way to do one thing, I think the obvious way for this kind of usage is to use a lambda.

**Comment by andyfaff** [comment]
> the (obvious) way for this kind of usage is to use a lambda.

agree, until the function needs to be pickled.

**Comment by mdhaber** [comment]
Then write a one-liner function, right?

**Comment by mdhaber** [comment]
@deka27 How about I leave this open as a documentation request? I'll add a standard note about using a `lambda` into the documentation of functions that accept a callable.

**Comment by deka27** [comment]
Thank you for this thoughtful suggestion. Adding a note about using lambda functions to the documentation sounds like a great idea. It will definitely help users like me understand how to work with these functions better.
