### ISSUE TITLE
BUG: optimize.minimize: `method='Powell'` gives array not scalar

### ISSUE THREAD

**Issue by mesvam** [scipy/scipy#21519]
### Describe your issue.

The OptimizeResult returned by `scipy.optimize.minimize(method='Powell')` expresses the optimal value of the function `fun` as a numpy scalar instead of a python float
```python
> res = scipy.optimize.minimize(lambda x: x**2, 10, method='Powell')
> res.fun
array(1.26217745e-29)
```

This is inconsistent with all the other methods
```python
> res = scipy.optimize.minimize(lambda x: x**2, 10, method='BFGS')
> res.fun
1.7161984122524196e-15
```
and can occasionally downstream issues that are not expecting an object. For example, pandas will interpret the scalar as an object.
```python
> pd.Series(res.fun)
0    1.262177448353619e-29
dtype: object
```

### SciPy/NumPy/Python version and system information

```shell
1.13.1 1.26.4 sys.version_info(major=3, minor=11, micro=9, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/ProgramData/Miniconda3/Library/include
    lib directory: C:/ProgramData/Miniconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_efv75hqhju\croot\scipy_1717521501389\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/ProgramData/Miniconda3/Library/include
    lib directory: C:/ProgramData/Miniconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_efv75hqhju\croot\scipy_1717521501389\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  pybind11:
    detection method: pkgconfig
    include directory: C:/ProgramData/Miniconda3/Library/include
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: clang-cl.exe
    linker: lld-link
    name: clang-cl
    version: 14.0.6
  c++:
    commands: clang-cl.exe
    linker: lld-link
    name: clang-cl
    version: 14.0.6
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.10
  fortran:
    commands: ifort
    linker: xilink
    name: intel-cl
    version: 2021.6.0
  pythran:
    include directory: ..\..\_h_env\Lib\site-packages\pythran
    version: 0.15.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
Python Information:
  path: C:\b\abs_efv75hqhju\croot\scipy_1717521501389\_h_env\python.exe
  version: '3.11'
```

**Comment by nickodell** [comment]
# Issue with provided code

First, a pedantic note about NumPy scalars: technically what Powell is doing here is returning a zero-dimensional array, not a scalar. NumPy scalars are when you have something like `np.float64(1.0)`.

The issue here is that minimize is expecting that your function return a scalar. minimize passes a numpy ndarray as the x parameter, and then `lambda x: x**2` squares that array and returns it. However, minimize is expecting your function to return a scalar value, not an array.

You could fix this like so:

```
scipy.optimize.minimize(lambda x: x[0]**2, 10, method='Powell')
```

# Powell's inconsistency with vector valued functions

Powell's behavior in this situation is odd, though. Here is a comparison of how each optimization method handles the case of a vector-valued function with one value.

Code:

```
from scipy.optimize import minimize, rosen, rosen_der, rosen_hess
import numpy as np

MINIMIZE_METHODS = ['nelder-mead', 'powell', 'cg', 'bfgs', 'newton-cg',
                    'l-bfgs-b', 'tnc', 'cobyla', 'cobyqa', 'slsqp',
                    'trust-constr', 'dogleg', 'trust-ncg', 'trust-exact',
                    'trust-krylov']

x0 = np.zeros(2)
for method in MINIMIZE_METHODS:
    kwargs = {}
    if method in ['newton-cg']:
        kwargs['jac'] = rosen_der
    if method in ['dogleg', 'trust-ncg', 'trust-exact', 'trust-krylov']:
        kwargs['jac'] = rosen_der
        kwargs['hess'] = rosen_hess
    res = minimize(lambda x: np.array([rosen(x)]), x0, method=method, **kwargs)
    print(f"{method:15s} {repr(res.fun):35s} {type(res.fun)}")
```

Table of results:

```
nelder-mead     np.float64(3.6861769151759075e-10)  <class 'numpy.float64'>
powell          array(1.97215226e-31)               <class 'numpy.ndarray'>
cg              2.0085382242752512e-11              <class 'float'>
bfgs            2.8439915001532524e-11              <class 'float'>
newton-cg       8.152784234848952e-15               <class 'float'>
l-bfgs-b        9.138630509774964e-12               <class 'float'>
tnc             9.670760401826812e-12               <class 'float'>
cobyla          np.float64(0.02835910492176066)     <class 'numpy.float64'>
cobyqa          np.float64(2.7259098605249485e-17)  <class 'numpy.float64'>
slsqp           5.772481138875386e-08               <class 'float'>
trust-constr    2.143251041478107e-11               <class 'float'>
dogleg          0.6804401142930896                  <class 'float'>
trust-ncg       7.616368874469718e-09               <class 'float'>
trust-exact     1.1524542070786494e-13              <class 'float'>
trust-krylov    2.480224824852751e-13               <class 'float'>
```

Powell is the odd one out - it is the only zero-dimensional array. Nelder Mead, COBYLA, and COBYQA return NumPy scalars. Everything else returns a Python float.

If you change to optimizing a scalar-valued function, the result is much more consistent.

Code:

```
    # same as before, but change minimize to this
    res = minimize(lambda x: rosen(x), x0, method=method, **kwargs)
```

Table:
```
nelder-mead     np.float64(3.6861769151759075e-10)  <class 'numpy.float64'>
powell          np.float64(1.9721522630525295e-31)  <class 'numpy.float64'>
cg              np.float64(2.0085382242752512e-11)  <class 'numpy.float64'>
bfgs            np.float64(2.8439915001532524e-11)  <class 'numpy.float64'>
newton-cg       np.float64(8.152784234848952e-15)   <class 'numpy.float64'>
l-bfgs-b        np.float64(9.138630509774964e-12)   <class 'numpy.float64'>
tnc             np.float64(9.670760401826812e-12)   <class 'numpy.float64'>
cobyla          np.float64(0.02835910492176066)     <class 'numpy.float64'>
cobyqa          np.float64(2.7259098605249485e-17)  <class 'numpy.float64'>
slsqp           np.float64(5.772481138875386e-08)   <class 'numpy.float64'>
trust-constr    np.float64(2.143251041478107e-11)   <class 'numpy.float64'>
dogleg          np.float64(0.6804401142930896)      <class 'numpy.float64'>
trust-ncg       np.float64(7.616368874469718e-09)   <class 'numpy.float64'>
trust-exact     np.float64(1.1524542070786494e-13)  <class 'numpy.float64'>
trust-krylov    np.float64(2.480224824852751e-13)   <class 'numpy.float64'>
```

# Powell's inconsistency with functions that return a scalar float

What if the objective function returns a Python float?

```
    # same as before, but change minimize to this
    res = minimize(lambda x: float(rosen(x)), x0, method=method, **kwargs)
```

Table of results:

```
nelder-mead     np.float64(3.6861769151759075e-10)  <class 'numpy.float64'>
powell          array(1.97215226e-31)               <class 'numpy.ndarray'>
cg              2.0085382242752512e-11              <class 'float'>
bfgs            2.8439915001532524e-11              <class 'float'>
newton-cg       8.152784234848952e-15               <class 'float'>
l-bfgs-b        9.138630509774964e-12               <class 'float'>
tnc             9.670760401826812e-12               <class 'float'>
cobyla          np.float64(0.02835910492176066)     <class 'numpy.float64'>
cobyqa          np.float64(2.7259098605249485e-17)  <class 'numpy.float64'>
slsqp           5.772481138875386e-08               <class 'float'>
trust-constr    2.143251041478107e-11               <class 'float'>
dogleg          0.6804401142930896                  <class 'float'>
trust-ncg       7.616368874469718e-09               <class 'float'>
trust-exact     1.1524542070786494e-13              <class 'float'>
trust-krylov    2.480224824852751e-13               <class 'float'>

```

And the zero-dimensional array is back. This is strange: it seems perfectly reasonable for the objective function to return a float.

Versions used: SciPy 1.14.1, NumPy 2.1.0. (NumPy changed the way it prints NumPy scalars in 2.0, so you may see different output on 1.26.4.)

# Documentation fixes

In the process of figuring out what the correct type for `res.fun` is, I looked it up in the documentation.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html#scipy.optimize.OptimizeResult

>fun, jac, hess: ndarray
>
>Values of objective function, its Jacobian and its Hessian (if available). The Hessians may be approximations, see the documentation of the function in question.

The `fun` attribute is documented as being an ndarray. That doesn't seem right. Should we change this to be a `float` or `np.float64`?

**Comment by andyfaff** [comment]
> The fun attribute is documented as being an ndarray. That doesn't seem right. Should we change this to be a float or np.float64?

It should be a scalar. It's worth changing in the docstring.

**Comment by andyfaff** [comment]
For back compatibility `optimize` has allowed these kind of objective functions to return a variety of values, so long as it's a single value. Unfortunately this leads to this kind of issue.

**Comment by mesvam** [comment]
> First, a pedantic note about NumPy scalars: technically what Powell is doing here is returning a zero-dimensional array, not a scalar. NumPy scalars are when you have something like `np.float64(1.0)`.
> 
> The issue here is that minimize is expecting that your function return a scalar. minimize passes a numpy ndarray as the x parameter, and then `lambda x: x**2` squares that array and returns it. However, minimize is expecting your function to return a scalar value, not an array.

The pedantry seems well justified in this situation. I don't know if this makes sense implementation-wise, but as least from user perspective, I would expect `res.fun` to be identical to a call of the function on the optimized parameters `f(res.x)`

One reason why you might not want to evaluate `f(res.x)` again yourself is if the objective function is expensive, and since `minimize` must have already evaluated it at the optimal point, it's a bit faster to grab it from `res.fun` instead

**Comment by lucascolley** [comment]
Does it seem reasonable to start raising a deprecation warning and switch this to returning a Python scalar after two releases?

**Comment by andyfaff** [comment]
I don't think a deprecation warning is needed here, just a straight swap to returning float/np.float64/etc.

**Comment by nickodell** [comment]
>I would expect the type of `res.fun` to be identical to the type of a call of the function on the initial parameters `f(x0)`.

The problem with that, from an implementation perspective, is that we never called the function with that value. If x0 is a scalar, then we called the function `f(np.array([x0])`, converting x0 from a scalar to an array first. We don't know if `f(x0)` would result in a scalar or array value.

I agree that it would be better for `res.fun` to be a Python float. But I would prefer the rationale be that `res.fun` is always cast to a Python float, not that the goal is to match `f(x0)`.
