### ISSUE TITLE
DOC: signal.freqz: problem with `fs`

### ISSUE THREAD

**Issue by qqwqqw689** [scipy/scipy#21510]
### Issue with current documentation:

Example
```py
from scipy import signal
import numpy as np
b = signal.firwin(80, 0.5, window=('kaiser', 8))
w, h = signal.freqz(b)
```
The default fs for firwin is 2.But the default fs for freqz is 2*pi.

![image](https://github.com/user-attachments/assets/6ec86e82-713b-46fb-b290-15d85981a519)

So the cutoff frequency in this picture is false.

### Idea or request for content:

I'd like to submit a pr to fix it.😁

**Comment by qqwqqw689** [comment]
the [link](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.freqz.html)

**Comment by DietBru** [comment]
> I'd like to submit a pr to fix it.😁

That would be great,  @qqwqqw689! 

Besides fixing the `fs` parameter, could you also make the right axis label in the plot readable. Doing something like
```
>>> fig, ax1 = plt.subplots(tight_layout=True) 
```
or
```
>>> fig, ax1 = plt.subplots(figsize=(6., 4.))  # enlarge plot a bit
```
might fix that problem.
