### ISSUE TITLE
TST, MAINT: test_matrix_input failing

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#21534]
On latest `main` this fails: `python dev.py test -t scipy/interpolate/tests/test_rgi.py::TestInterpN::test_matrix_input -b all`

This one has an explicit opt-in marker but also uses `matrix` so I'll defer to @ev-br

**Comment by ev-br** [comment]
https://github.com/scipy/scipy/pull/21536 suggests a fix, WDYT?
