### ISSUE TITLE
BUG: TypeError for `import BSpline`

### ISSUE THREAD

**Issue by 2catycm** [scipy/scipy#21546]
### Describe your issue.

from scipy.interpolate import BSpline 
would have a type error. 
![9c19a004-b6c4-411a-8da4-a4a730fa37e6](https://github.com/user-attachments/assets/a48bb597-292a-4418-bb90-3233134e879e)
<img width="573" alt="Snipaste_2024-09-12_02-11-08" src="https://github.com/user-attachments/assets/10edf513-27dc-4b22-843b-d48faf30c81c">

### Reproducing Code Example

```python
from scipy.interpolate import BSpline
```

### Error message

```shell
Type Error
See picture, I cannot copy it out.
```

### SciPy/NumPy/Python version and system information

```shell
1.14
See picture, I cannot copy it out.
```

**Comment by lucascolley** [comment]
Perhaps related to gh-21289, gh-21014

**Comment by lucascolley** [comment]
what is your Python version?

**Comment by yxbian23** [comment]
> what is your Python version?

My python version is 3.10.14, and the scipy version is 1.14.0. However, I still met the same problem as this issue.

**Comment by lucascolley** [comment]
@yxbian23 could you try upgrading to SciPy 1.14.1, and if that doesn't work, tell us more about your system (such as OS, NumPy version, how you installed SciPy)

**Comment by lucascolley** [comment]
Could you try with NumPy 2.1.0?

**Comment by yxbian23** [comment]
> Could you try with NumPy 2.1.0?

I upgraded the NumPy to 2.1.0, but sadly I still got the same error...

**Comment by ev-br** [comment]
I would try to make a fresh empty conda env with only python and `pip install scipy` into it. Does it show the same problem? And repeat with `conda install scipy`, also into a fresh environment.

The suspicion is that something else in your env conflicts with a pip build scipy (and mixing pip and conda binaries is known to have issues sometimes)

**Comment by yxbian23** [comment]
> I would try to make a fresh empty conda env with only python and `pip install scipy` into it. Does it show the same problem? And repeat with `conda install scipy`, also into a fresh environment.
> 
> The suspicion is that something else in your env conflicts with a pip build scipy (and mixing pip and conda binaries is known to have issues sometimes)

Thanks a lot! I created a whole new environment, and using SciPy became fine. I believe there is something else that brought the conflicts. Thanks again~

**Comment by lucascolley** [comment]
Yeah, we've at around 5 bug reports now for the same issue so it would be good to figure out what the culprit is.

**Comment by fealty94** [comment]
I have the same problem today...
My solution is to upgrade numpy from 1.26.4 to 2.0.0.
I think the culprit(?) is numpy version.
Maybe you should make the constraint with numpy version.

**Comment by yxbian23** [comment]
> Great! Is it pip or conda-forge installed scipy? Either way, it'd be interesting to see what causes issues: if you've time, could you install things one by one and see what breaks it? This is most likely something beyond scipy's control, but maybe there's an ecosystem-level issue which can be addressed.

I did some testing (always use pip to install). And I found that in my cluster, it seems that the error in this issue is caused by **the versions of Python**:
1. In my initial attempt, the Python version of the conda environment is 3.10.14, and in that env I met the TypeError;
2. In my final attempt, the Python version of the conda environment is 3.10.6, and in this env everything went just fine.

BTW, all the time my NumPy version is 1.26.4 and the SciPy version is 1.14.1.

**Comment by lucascolley** [comment]
Did your environment also have a mixture of packages from `pip` and `conda`?

**Comment by fealty94** [comment]
> > I have the same problem today...
> 
> Did your environment also have a mixture of packages from `pip` and `conda`?

Yes. I encounter this issue when I install below environment.
https://github.com/princeton-vl/DPVO/blob/main/environment.yml

name: dpvo
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.10
  - pytorch=2.3.1
  - pytorch-scatter=2.1.2
  - pytorch-cuda=12.1
  - torchvision=0.18
  - pip:
    - tensorboard
    - numba
    - tqdm
    - einops
    - pypose
    - kornia
    - numpy==1.26.4
    - plyfile
    - evo
    - opencv-python
    - yacs

**Comment by 2catycm** [comment]
> what is your Python version?

Hi, sorry for late reply. My version is  Python 3.10.14
scipy is 1.14.1
now it seems the code runs successfully.

**Comment by cppt** [comment]
@nickodell thanks.  

```
pip install --upgrade scipy==1.14.1
ERROR: Ignored the following yanked versions: 1.11.0
ERROR: Ignored the following versions that require a different python version: 1.14.0 Requires-Python >=3.10; 1.14.0rc1 Requires-Python >=3.10; 1.14.0rc2 Requires-Python >=3.10; 1.14.1 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement scipy==1.14.1 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.8.0rc1, 1.8.0rc2, 1.8.0rc3, 1.8.0rc4, 1.8.0, 1.8.1, 1.9.0rc1, 1.9.0rc2, 1.9.0rc3, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0rc1, 1.10.0rc2, 1.10.0, 1.10.1, 1.11.0rc1, 1.11.0rc2, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.13.0rc1, 1.13.0, 1.13.1)
ERROR: No matching distribution found for scipy==1.14.1
```

A little leary about attempting to update other packages further more without understanding the underlying cause.  One remedy yesterday, was downgrading numpy to 1.26.3
  

For reference, yesterday (before restarting Spyder), the error message was the below (attempting similar imports):

```
import statsmodels.api as sm
Traceback (most recent call last):

File "/tmp/ipykernel_284942/2479605915.py", line 1, in
import statsmodels.api as sm

File "/home/chris/anaconda3/lib/python3.9/site-packages/statsmodels/api.py", line 78, in
from . import datasets, distributions, iolib, regression, robust, tools

File "/home/chris/anaconda3/lib/python3.9/site-packages/statsmodels/distributions/init.py", line 7, in
from .discrete import (

File "/home/chris/anaconda3/lib/python3.9/site-packages/statsmodels/distributions/discrete.py", line 36, in
genpoisson_p = genpoisson_p_gen(name='genpoisson_p',

File "/home/chris/anaconda3/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 3225, in init
super().init(seed)

File "/home/chris/anaconda3/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 643, in init
self._random_state = check_random_state(seed)

File "/home/chris/anaconda3/lib/python3.9/site-packages/scipy/_lib/_util.py", line 265, in check_random_state
return np.random.mtrand._rand

AttributeError: module 'numpy.random' has no attribute 'mtrand'
```

**Comment by cppt** [comment]
To close the loop here, updated conda/spyder and imports now complete successfully.  Perhaps obviously, must have had a few package incompatibilities.  Appreciate the help

**Comment by cppt** [comment]
To close the loop here, updated conda/spyder and imports now complete successfully.  Perhaps obviously, must have had a few package incompatibilities.  Appreciate the help
