### ISSUE TITLE
DOC: Lack of table of contents in cluster

### ISSUE THREAD

**Issue by BlackHC** [scipy/scipy#21556]
### Issue with current documentation:

This is useless, unfortunately. Am I supposed to click through "Next" to get an overview of the existing classes and sub-packages?

<img width="1021" alt="image" src="https://github.com/user-attachments/assets/0d6b9ff2-0929-4a2b-ab66-b454eb529ce2">

### Idea or request for content:

Please add back a TOC for each package.

**Comment by ilayn** [comment]
Always a pleasure to get constructive comments. 

This is a bug in the documentation since this page should display the ToC which is the case for other submodules.

**Comment by lucascolley** [comment]
Thanks! I agree that a small 'submodules' table with the two entries would be nice here.

**Comment by melissawm** [comment]
@BlackHC would you be interested in sending a PR for this? 😄 Check our contributing guide for more info: https://scipy.github.io/devdocs/dev/contributor/contributor_toc.html

**Comment by czgdp1807** [comment]
I am working on it. Please let me know if someone else has already taken this up. Will send a PR shortly. Will need help in figuring out how the TOC should look like.

cc: @rgommers
