### ISSUE TITLE
QUERY: linalg.ldl: clarify docs?

### ISSUE THREAD

**Issue by joaospinto** [scipy/scipy#21555]
### Describe your issue.

Looks like the `L D L^T` decompositions provided by `scipy` are wrong. See a simple example below.

The attached code yields:
```
array([[1. , 0. , 0. ],
       [1.4, 1. , 0. ],
       [1.2, 0.5, 1. ]])
```
The right output would be:
```
array([[1. , 0. , 0. ],
       [1.2, 1. , 0. ],
       [1.4, 2.0, 1. ]])
```
Note that the correct D is:
```
array([4.5e+01, 1.2e+00, 0.0e0])
```

### Reproducing Code Example

```python
import numpy as np

from scipy.linalg import ldl

M = np.arange(9).reshape([3, 3])
A = M.T @ M
lu, d, perm = ldl(A)

print(lu[perm,:])
```

### Error message

```shell
N/A (not an error, just an incorrect result)
```

### SciPy/NumPy/Python version and system information

```shell
1.14.1 2.1.1 sys.version_info(major=3, minor=12, micro=4, releaselevel='final', serial=0)

Build Dependencies:
  blas:
    detection method: extraframeworks
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: extraframeworks
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 13.3.0
  pythran:
    include directory: ../../../../../../private/var/folders/hw/1f0gcr8d6kn9ms0_wn0_57qc0000gn/T/pip-build-env-bjescfad/overlay/lib/python3.12/site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/hw/1f0gcr8d6kn9ms0_wn0_57qc0000gn/T/cibw-run-oogm4_8g/cp312-macosx_arm64/build/venv/bin/python
  version: '3.12'
```

**Comment by rkern** [comment]
`A` is an indefinite matrix. Pivoting gets used to avoid numerical difficulties, resulting in the nontrivial `perm` permutation. In an LDL decomposition, the `L` and `D` matrices of the pivoted problem in general will not match up with the `L` and `D` matrices of the unpivoted problem. The result you are expecting comes from an unpivoted implementation. The `lu`, `d`, and `perm` outputs all obey the properties demanded of the LDL decomposition (`lu @ d @ lu.T` recovers `A` within numerical error, `lu[perm, :]` is lower triangular with unit diagonals, and `d` is diagonal). I don't think there is a bug here.

**Comment by joaospinto** [comment]
OK, I think there is some confusion here about the definition of an `L D L^T` decomposition.

> The `lu`, `d`, and `perm` outputs all obey the properties demanded of the LDL decomposition (`lu @ d @ lu.T` recovers `A` within numerical error, `lu[perm, :]` is lower triangular with unit diagonals, and `d` is diagonal).

Arguably, this isn't really obeying the properties of an `L D L^T` decomposition; I'd say such properties would be satisfied if `lu @ d @ lu.T` recovers `A` within numerical error with `lu` being lower triangular at the same time.

Maybe calling this function something like `pivoted_ldl` would be more appropriate. But yes, this is not a bug, but rather a matter of definitions (i.e. what should be called an `L D L^T` decomposition).

> `A` is an indefinite matrix.

nit: Technically, indefinite means neither positive semi-definite nor negative semi-definite. `A` is a positive semi-definite matrix, and it most certainly admits a `L D L^T` decomposition. But yes, one of its eigenvalues is `0`, and the other two are positive.

**Comment by ilayn** [comment]
For nonpositive definite matrices there is no guarantee of a LDL decomposition (just like no guarantee of unpivoted LU). Hence partial pivoting strategy is included in all these linalg operations. This is a very established strategy ([Matlab ldl](https://nl.mathworks.com/help/matlab/ref/ldl.html) ). 

When the array is positive definite you can already get triangular factors via Cholesky. Hence LDL is pretty much for nondefinite matrices and as such there is always pivoting involved. Since there is no bug here I'll close this but feel free to continue the discussion.

**Comment by joaospinto** [comment]
> For nonpositive definite matrices there is no guarantee of a LDL decomposition without pivoting (just like no guarantee of unpivoted LU). 

That is not true. Unpivoted L D L^T decompositions are guaranteed to exist for all positive semi-definite matrices. Cholesky decompositions aren’t and require actual positive definiteness.

**Comment by lucascolley** [comment]
Feel free to suggest a documentation improvement @joaospinto !

**Comment by joaospinto** [comment]
Here what I would suggest:
1. If/when possible, rename the function.
2. Clarify that it doesn't actually compute an `L D L^T` decomposition; in fact, based on the current docs, it doesn't even compute a pivoted `L D L^T` decomposition, as `D` can be block-diagonal with block sizes up to `2`.
3. Clarify when such a decomposition is guaranteed to exist, and when `D` is actually guaranteed to be diagonal.
4. Add a mode for computing an unpivoted `L D L^T` decomposition (although I agree that for the vast majority of use cases this should be avoided).

**Comment by ilayn** [comment]
@joaospinto These are all documented already. I think you have a different expectation from this decomposition. It never promises what you are asking for. Here is the exact sentence from the documentation https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.ldl.html

> This function returns a block diagonal matrix D consisting blocks of size at most 2x2 and also a possibly permuted unit lower triangular matrix L

It is a block diagonal so never says it will come out as diagonal. And it clearly says it will be permuted.

If you have any other software that delivers what you want, please let me know and I'll have a look.  We don't provide conditional functions in the sense that it can or cannot deliver a result depending on the input. That's against all the rest of the functions. Only exception is `sqrtm` but that has a very well defined meaning. As mentioned above look at the similar software including matlab. 

> 3 Clarify when such a decomposition is guaranteed to exist, and when D is actually guaranteed to be diagonal.

When the array is positive definite. It is a sufficient but not necessary condition.

> 1 If/when possible, rename the function.

That is not possible.

**Comment by lucascolley** [comment]
(reopened just to make more visible as there is active discussion)

**Comment by nickodell** [comment]
> That is not possible.

We could add a new alias for the function, deprecate the old name, and remove the old name. If we did this, the depreciation would need to comply with our depreciation policy: https://docs.scipy.org/doc/scipy/dev/core-dev/index.html#deprecations

The disadvantage is that this creates code churn in each downstream project using this function. I'm not sure I understand the linear algebra details enough to speak to the advantages.

**Comment by joaospinto** [comment]
> These are all documented already. I think you have a different expectation from this decomposition. It never promises what you are asking for.

The only part of the documentation I'm unhappy about is this:
> Computes the LDLt or Bunch-Kaufman factorization of a symmetric/ hermitian matrix.

^ This doesn't make any sense based on what the function actually does. It should just say:
> Computes a pivoted Bunch-Kaufman factorization of a symmetric/ hermitian matrix.

The subsequent paragraphs are clear and correctly describe the behavior of this function.

Alternatively (which I'd prefer), we should add a setting to specify whether we want an actual pivoted `L D L^T` or a pivoted Bunch-Kaufman factorization. There are certainly use cases where the former is preferred (although I concede that asking for an unpivoted `L D L^T` is perhaps unnecessary).

Looks like there was a related discussion on the Julia forum, lol: https://discourse.julialang.org/t/shouldnt-bunchkaufman-be-actually-named-ldlt/77641

> When the array is positive definite. It is a sufficient but not necessary condition. But the algorithm can still permute to improve conditioning.

I think that is a lacking characterization. I haven't looked in detail, but taking a look [here](https://ntrs.nasa.gov/api/citations/19890018970/downloads/19890018970.pdf) (which, by the way, would not be a bad source to link in the documentation), positive definiteness doesn't seem to be required at all. To be fair, currently, the documentation doesn't mention positive definiteness at all; were it not for the mention of `L D L^T`, I would say this isn't confusing.

> If you have any other software that delivers what you want, please let me know and I'll have a look. We don't provide conditional functions in the sense that it can or cannot deliver a result depending on the input. That's against all the rest of the functions. Only exception is sqrtm but that has a very well defined meaning. As mentioned above look at the similar software including matlab.

As mentioned earlier in this message, it could just be a flag, similarly to the many other options already in this function (`lower`, `hermitian`, etc).

> Same applies for semidefinite Cholesky computations.
Another side-note: not really; actual Cholesky decompositions do not exist for matrices that are symmetric positive semi-definite but not positive definite.

**Comment by rkern** [comment]
I'm fine with adding more information to the docstring about what the function does in which conditions (I don't think it's proper to remove mentions of `L D L^T` because it will compute that under a wide variety of conditions). But IMO, renaming doesn't buy us anything worth the churn.

**Comment by ilayn** [comment]
I don't understand your objection to LDLt.

> This doesn't make any sense based on what the function actually does. It should just say:

Why? LDL is never defined without pivoting. Like I mentioned I did not see any unpivoted version of it and I think this is what your definition is. And I disagree with that. This is pretty much everywhere the same definition. Because almost every software uses the same LAPACK functions. So I need some argument why you want to change its definition.

**Comment by ilayn** [comment]
It literally defines the permutations in the first page of the document you linked

![image](https://github.com/user-attachments/assets/4f0d4fce-5aa6-4786-aeed-86f8740c2936)

**Comment by ilayn** [comment]
> Another side-note: not really; actual Cholesky decompositions do not exist for matrices that are symmetric positive semi-definite but not positive definite.

There is a way to compute semidefinite Cholesky decompositions. Some examples and references are in wiki https://en.wikipedia.org/wiki/Cholesky_decomposition but Golub/van Loan has the proofs.

**Comment by joaospinto** [comment]
> There is a way to compute semidefinite Cholesky decompositions. Some examples and references are in wiki https://en.wikipedia.org/wiki/Cholesky_decomposition but Golub/van Loan has the proofs. The issue is the uniqueness for semidefinite Cholesky. And as I mentioned before numerically this is ill-conditioned hence it is generally not implemented.

You're right about that, I was not aware. Only uniqueness is lost, apparently.

> It literally defines the permutations in the first page of the document you linked

Bunch-Kaufman decompositions are, by definition, pivoted. Not `L D L^T`. `L` is for lower and there is certainly no `P`!

> Why? LDL is never defined without pivoting. Like I mentioned I did not see any unpivoted version of it and I think this is what your definition is. And I disagree with that. This is pretty much everywhere the same definition. Because almost every software uses the same LAPACK functions. So I need some argument why you want to change its definition.

I disagree with this. I agree that it may possibly the the _computational_ standard to implement it with pivoting (but I doubt the standard is to allow 2x2 blocks in `D`). Mathematically speaking, the standard definition of `L D L^T` decompositions doesn't typically account for pivoting. Similarly for Cholesky; e.g., from [wikipedia](https://en.wikipedia.org/wiki/Cholesky_decomposition):

![Screenshot 2024-09-13 at 2 14 08 PM](https://github.com/user-attachments/assets/e6181d15-9c39-4141-9d1f-83169a151d87)

Anyway, I don't think this discussion is being productive. You're the maintainers, feel free to do as you choose. From my perspective, although I'm certainly convinced of the merit of having a pivoted implementation, I'm definitely not convinced that we should be the Bunch-Kaufman factorization `ldl`. It's misleading and error-prone.
