### ISSUE TITLE
DOC: stats.pearsonr: error in notes of API reference

### ISSUE THREAD

**Issue by C-Peiter** [scipy/scipy#21566]
### Issue with current documentation:

I found a minor mistake in the calculation of the p-value, which is documented in the *Notes* section for pearsonr [here](https://scipy.github.io/devdocs/reference/generated/scipy.stats.pearsonr.html#scipy.stats.pearsonr). It says  `p = 2*dist.cdf(-abs(r))`, which would be the `cdf` of a negative number. 

### Idea or request for content:

I think, it should be  `p = 2*dist.cdf(1-abs(r))`

**Comment by mdhaber** [comment]
AFAICT, the documentation is in line with the implementation, and both are correct. 
> which would be the cdf of a negative number.

This is not inherently a problem. In this case, the beta null distribution has been shifted to the support `(-1, 1)`. IIRC, an equivalent way of performing the test would use the t distribution.
