### ISSUE TITLE
DOC: interpolate.interp1d: clarify status and alternatives

### ISSUE THREAD

**Issue by jerabaul29** [scipy/scipy#21571]
### Is your feature request related to a problem? Please describe.

Documentation now states that `scipy`'s `interp1d` is deprecated https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html . However, the main solution pointed to (`numpy`s `interp`) is not providing as much functionality. For example:

- in `scipy.interp1d`, I can build the interpolator class, and then call it several times on different arrays of interpolation points. I guess if the interpolator class is well implemented that it means that I may factor all "pre-processing and preparation" if there is any needed in `scipy.interp1d`, which may be quite a bit more efficient than with `numpy.interp` API which will need to do all of this again and again depending on use cases (?)

- `scipy.interp1d` supports a lot more functionalities, because of the flexible `kind` argument. For example there are cases when one needs nearest interpolation. This is not easily doable as far as I know with the `numpy.interp` function.

It is perfectly fine to me if 1d interpolation is deprecated from `scipy`and moved to `numpy`, but in this case it would be nice to have "at least as much and as good" functionality :) .

I can open a twin issue on `numpy`'s repo :) .

### Describe the solution you'd like.

Keep supporting `scipy`'s 1d interpolation until `numpy`'s one is offering at least as much / good functionality.

### Describe alternatives you've considered.

`numpy`'s interpolation, as recommended by the documentation.

**Comment by ev-br** [comment]
`interp1d` is _not_ deprecated.

It is legacy, which basically means "we believe there are better ways of doing things, consider using them in new code".
Suggestions on how to improve the legacy admonition in the docs are very much appreciated!

For your use cases specifically:

- construct an interpolator for multiple evaluations: the dev docs list an alternative, https://scipy.github.io/devdocs/tutorial/interpolate/1D.html#non-cubic-splines. Suggestion of how to make it more discoverable in the docs are most welcome!
- `kind="nearest`": indeed there's no pre-canned alternative to `interp1d`, and we are going to continue support it. That said, these `interp1d` kinds are basically a pile of overhead on top of `np.searchsorted`, so consider using that directly.

I'm going to relabel this issue as a request for improving the documentation. Help is most welcome and appreciated.
