### ISSUE TITLE
DOC: building: specify `.ps1` for windows example

### ISSUE THREAD

**Issue by musvaage** [scipy/scipy#21576]
The docs have the `pwsh` line executing the activate file instead of the .ps1 file.

```
$ sed -n '331,355p' scipy/doc/source/building/index.rst
    .. tab-set::

      .. tab-item:: Linux
        :sync: linux

        ::

          python -m venv venv
          source venv/bin/activate

      .. tab-item:: macOS
        :sync: macos

        ::

          python -m venv venv
          source venv/bin/activate

      .. tab-item:: Windows
        :sync: windows

        ::

          python -m venv venv
          .\venv\Scripts\activate
$ 
```

doc/source/building/index.rst

```diff
-           .\venv\Scripts\activate
+           .\venv\Scripts\Activate.ps1
```

as per recent output from `pwsh` on Windows

```console
PS C:\Users\bird> python.exe --version
Python 3.12.6
PS C:\Users\bird> python.exe -m venv venv
PS C:\Users\bird> Get-ChildItem venv\Scripts

    Directory: C:\Users\bird\venv\Scripts

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           9/17/2024  5:27 PM           2034 activate
-a---           9/17/2024  5:27 PM            990 activate.bat
-a---           9/17/2024  5:27 PM          26199 Activate.ps1
-a---           9/17/2024  5:27 PM            393 deactivate.bat
-a---           9/17/2024  5:27 PM         108399 pip.exe
-a---           9/17/2024  5:27 PM         108399 pip3.12.exe
-a---           9/17/2024  5:27 PM         108399 pip3.exe
-a---           9/17/2024  5:27 PM         270104 python.exe
-a---           9/17/2024  5:27 PM         258840 pythonw.exe

PS C:\Users\bird>
```

<hr>

Peripheral to the foregoing is noted PowerShell isn't to date a Windows only program.

And the docs aren't specific when commands are provided as to Command Prompt or PowerShell.

The `pyproject.toml` file being updated with some frequency, the following might be considered to implement as being more informative; uppercasing `set` (though cmd.exe is case-insensitive) may emphasise it as a Command Prompt "internal command".

```diff
- # do this instead (which will override this setting)
- # set CIBW_ENVIRONMENT_WINDOWS=PKG_CONFIG_PATH=PWD.replace('\\', '/')
+ # in cmd.exe do this instead (which will override this setting)
+ # SET CIBW_ENVIRONMENT_WINDOWS=PKG_CONFIG_PATH=PWD.replace('\\', '/')
```

**Comment by musvaage** [comment]
@lucascolley 

_cf_: **[How venvs work](https://docs.python.org/3/library/venv.html#how-venvs-work)**

<hr>

@vsajip

`https://github.com/python/cpython/commit/1a6bacb31f7b49c244a6cc3ff0fa7f71a82412ef`

**[doc] Refresh the venv introduction documentation, and correct the st…**
…atement about VIRTUAL_ENV (GH-98350)
pelson and CAM-Gerlach committed on Oct 19, 2022

cpython/Doc/library/venv.rst

suggested update (below) changes PowerShell to pwsh

and (as rendered) for pwsh adds POSIX `./ ` and Windows `.\`

```
+-------------+----------+-----------------------------------------------------+
| Platform    | Shell    | Command to activate virtual environment             |
+=============+==========+=====================================================+
| POSIX       | bash/zsh | :samp:`$ source {<venv>}/bin/activate`              |
|             +----------+-----------------------------------------------------+
|             | fish     | :samp:`$ source {<venv>}/bin/activate.fish`         |
|             +----------+-----------------------------------------------------+
|             | csh/tcsh | :samp:`$ source {<venv>}/bin/activate.csh`          |
|             +----------+-----------------------------------------------------+
|             | pwsh     | :samp:`$ ./{<venv>}/bin/Activate.ps1`               |
+-------------+----------+-----------------------------------------------------+
| Windows     | cmd.exe  | :samp:`C:\\> {<venv>}\\Scripts\\activate.bat`       |
|             +----------+-----------------------------------------------------+
|             | pwsh.exe | :samp:`PS C:\\> .\\{<venv>}\\Scripts\\Activate.ps1` |
+-------------+----------+-----------------------------------------------------+
```

**Comment by lucascolley** [comment]
Feel free to send a PR @musvaage , following CPython sounds like a good idea to me 👍

**Comment by musvaage** [comment]
> following CPython

this should be the fix

```patch
-           .\venv\Scripts\activate
+           venv\Scripts\Activate.ps1
```
<hr>

> _cf_: **How venvs work**

update to table corrected in previous comment

<s>and (as rendered) for pwsh adds POSIX `./` and Windows `.\`</s>

POSIX

to execute example.ps1 in the local directory type the following

./example.ps1

the `./` isn't used when executing a .ps1 file in another directory

/tmp/example.ps1

**Comment by musvaage** [comment]
The table over in the CPython repo has been modified using the executable name only for POSIX.

_cf_: https://github.com/python/cpython/pull/124315#issuecomment-2383794430

It'd be more convenient for packagers if activate.sh replaced activate as a file name allocating for a transition period.
