### ISSUE TITLE
ENH: Update constants to CODATA 2022 recommendation

### ISSUE THREAD

**Issue by Louwrensth** [scipy/scipy#21596]
### Is your feature request related to a problem? Please describe.

The current `scipy.constants` are still following the 2018 CODATA recommendation, which are out of date since the 2022 CODATA recommendation is published (24 May 2024). See https://physics.nist.gov/cuu/Constants/bibliography.html

### Describe the solution you'd like.

Bump the `scipy.constants` module to use the 2022 CODATA recommentation by default, keep the 2018 version available.

### Describe alternatives you've considered.

I see there are some reorganizations afoot regarding this module (i.e. PR #20430 and PR #20055), and I was wondering if the 2022 update need to wait for these PRs first. I'd like to help and add the update myself, but not if it is to be superseded soon ;) It seems to me that after the reorganization it will also be easier to update to 2022.

Please advise.

**Comment by lucascolley** [comment]
cc @jakobjakobson13

**Comment by jakobjakobson13** [comment]
I currently don´t have the time to work further the reorganization of the module but it should be an easy pull request.

That leaves however two issues outstanding: the recalculation of the exact constants and a possible reorganization of the module. The first one should be included as soon as possible in my opinion as the truncated values given in the ascii files are very inprecise whereas the latter one is less urgent and just provides a less bloated_constants.py file (at last if you are just moving the content of the files into dedicated files).
