### ISSUE TITLE
BUG: linalg.expm: converting NaN to int

### ISSUE THREAD

**Issue by andreas-schwab** [scipy/scipy#21618]
pick_pade_structure tries to convert NaN to int which is a big no-no and
results in undefined behaviour

**Comment by ilayn** [comment]
where does it do that?

**Comment by andreas-schwab** [comment]
lm = (int)ceil(log2(temp/normA/coeff[0])/6);

**Comment by andreas-schwab** [comment]
Test case from python-control:

from numpy import array, zeros, linspace
from control.matlab import ss, step
A =  array([[-81.82, -45.45], [ 10.,    -1.  ]])
B =  array([[9.09], [0.  ]])
C =  array([[0, 0.159]])
D = zeros((1, 1))
sys_ss = ss(A, B, C, D)
t = linspace(0, 1000, 1000)
y, _t = step(sys_ss, t)

**Comment by ilayn** [comment]
Is this zero order hold discretized? What is the array that goes into expm? Because this is an overflow issue and should be handled first, not a NaN conversion problem.

**Comment by andreas-schwab** [comment]
normA is 0 and log2 is called with NaN

**Comment by ilayn** [comment]
That should return -inf. Let me check control library first how this model is discretized. We are treating the symptom we need the array that goes into expm.

**Comment by ilayn** [comment]
This model does not go into the expm route. What do you get out of this example? Could you please give a full account of what the issue is?

**Comment by ilayn** [comment]
If that is the array then on main branch I get 

```python
>>> la.expm(np.array([[0.        , 0.        , 0.01694884, 0.01707782],
       [0.        , 0.        , 0.16948837, 0.16925281],
       [0.        , 0.        , 1.        , 1.        ],
       [0.        , 0.        , 0.        , 1.        ]])
array([[0.        , 0.        , 0.01694884, 0.01707782],
       [0.        , 0.        , 0.16948837, 0.16925281],
       [0.        , 0.        , 1.        , 1.        ],
       [0.        , 0.        , 0.        , 1.        ]])
```

**Comment by ilayn** [comment]
This is what I get on main 

```python
In [8]: from scipy.linalg._matfuncs_expm import pick_pade_structure

In [9]: Am = np.empty((5, 4, 4), dtype=float)

In [10]: Am[0] = np.array([[-9.09111111e+03, -5.05000000e+03, 1.01000000e+03,
    ...:    ...: 0.00000000e+00],
    ...:    ...: [ 1.11111111e+03, -1.11111111e+02, 0.00000000e+00,
    ...:    ...: 0.00000000e+00],
    ...:    ...: [ 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
    ...:    ...: 1.00000000e+00],
    ...:    ...: [ 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
    ...:    ...: 0.00000000e+00]])

In [11]: pick_pade_structure(Am)
Out[11]: (13, 11)
```

Could you please check if you are on latest commit on `main`?

**Comment by andreas-schwab** [comment]
11 is the result of UNDEFINED BEHAVIOUR.  You cannot trust it.

**Comment by ilayn** [comment]
Again, we are trying to find the root cause not the solution, I know where to put the guards if there is an overflow/undeflow. That is not the issue. We need to find where things go wrong. You are still fixing the resulting issue. Something is causing an overflow/underflow. So let's stop discussing about undefined behavior and find why it is causing a norm 0 on your machine.

**Comment by andreas-schwab** [comment]
lm = ceil(log2(temp/normA/coeff[0])/6)

temp/normA is 0/0 is NaN

**Comment by ilayn** [comment]
You array is nonzero so normA can't be 0 because if these lines 

https://github.com/scipy/scipy/blob/860a46bf43612d358e2c905649ade2e5a19ecccb/scipy/linalg/_matfuncs_expm.c#L839-L841

**Comment by andreas-schwab** [comment]
The debugger is always right.

**Comment by andreas-schwab** [comment]
11 is the result of UNDEFINED BEHAVIOUR.  This the ULTIMATE SIN in programming!
