### ISSUE TITLE
QUERY: linalg: doubt regarding signatures for `dotu` with Pyodide

### ISSUE THREAD

**Issue by anutosh491** [scipy/scipy#21611]
### Describe your issue.

More of a doubt than a bug

I was executing the following on a pyodide repl
```
>>> import scipy
from scipy.linalg import _fblas as fblas, get_blas_funcs, toeplitz, solve
>>> f = getattr(fblas, 'cdotu', None)
>>> print(f([3j, -4, 3-4j], [2, 3, 1]))
The cause of the fatal error was:
RuntimeError: null function or function signature mismatch
```

This shows a function signature mismatch. 
1) The function being called `call_indirect (param i32 i32 i32 i32 i32 i32) (result i32)`
2) How the function is defined `(func $f2pywrapcdotu_ (;227;) (export "f2pywrapcdotu_") (param $var0 i32) (param $var1 i32) (param $var2 i32) (param $var3 i32) (param $var4 i32) (param $var5 i32) (param $var6 i32) (param $var7 i32) (result i32)`

The first one passes `6` parameters and the second one requires `8`

This raises a confusion about the signatures & definitions for `dotu` and `dotu` wrappers

For eg
https://github.com/scipy/scipy/blob/8048c1e93c6226a6ea3e2395560e6b23f81ff0f8/scipy/linalg/cython_blas_signatures.txt#L6-L7

Though Something that looks correct to me is the following
https://github.com/scipy/scipy/blob/e83749437f2617b19e4d133c80a11183b1486fab/scipy/linalg/fblas_l1.pyf.src#L329

The difference between the two is basically the offsets for the arrays `x` and `y` basically `offx` and `offy`. I think this might be the answer for the 2 missing input parameters that causes the signature mismatch in my example above.

Not sure if I analyzed this correctly and would like some help here

### SciPy/NumPy/Python version and system information

```shell
>>> print(scipy.__version__)
1.12.0
>>> print(np.__version__)
1.26.4
>>> print(sys.version_info)
sys.version_info(major=3, minor=12, micro=1, releaselevel='final', serial=0)
```

**Comment by ev-br** [comment]
Locally on a bog-standard ubuntu linux, self-built main branch:

```
In [1]: from scipy.linalg import _fblas as fblas, get_blas_funcs

In [2]: f = getattr(fblas, 'cdotu', None)

In [3]: f
Out[3]: <fortran function cdotu>

In [5]: f([3j, -4, 3-4j], [2, 3, 1])
Out[5]: (-9+2j)
```

So this is something about pyodide build, not general linalg BLAS wrappers, it looks like.

**Comment by anutosh491** [comment]
Yes this surely works with scipy locally (it is from the tests). Just wasn't sure as to why would there be a signature mismatch because the same example works in pyodide with `dotc` and not with `dotu` (and I don't see any obvious differences in how `dotc` and `dotu` are implemented in scipy)

**Comment by ilayn** [comment]
Actually this is on me being a complete novice and not knowing how SciPy wrappers worked back then, trying to do something nice but modifying written in stone signatures of these functions. I'll find the relevant PR and I know `larfg` is another one Pyodide folks have an issue with that I promised to fix but forgot.

**Comment by ilayn** [comment]
Oh wait this is not one of them. The difference is that SciPy wrapper is converted from a `function` into a `subroutine` due to some segfault issue that this is causing and changed in #20232. 

My mistake mentioned above is still there though.

**Comment by anutosh491** [comment]
Yupp I think this might be different than the `larfg` issue. (I still can't wrap my head around how similarly are dot and dotc   framed as compared to dotu but for some reason only dotu ends up giving this error)

> not knowing how SciPy wrappers worked back then

Also it would be absolutely great if you could educate me on this (maybe point me to something I could read ?). Thanks

**Comment by ilayn** [comment]
Maybe you know this, but just for the sake of complexity; in fortran a `function` returns a value (in dotc this is the xy var that is selected to represent the var to be returned). In C terms, this is equal to 
```C
double dotc(....)
{
...
    return xy;
}
``` 

A `subroutine` is equal to a C function like 
```C
void dotc(..., double* xy)
{
    *xy = ...;
    return;
}
```
 
So now, you have to explicitly pass the variable you want to be computed in the signature. In this case, I don't know why we felt the need to change these in #20232 but that's where the difference comes from. 

> Also it would be absolutely great if you could educate me on this (maybe point me to something I could read ?)

I wish I had something to offer but these wrappers are probably one of our weakest points in SciPy due to many many inconsistencies accumulated over decades, written by different people to do different tasks. I just spent way too much time to have a half-understanding and I would recommend you not killing time on these. We are contemplating on how to fix them anyways hence it would be a dead investment. 

In the meantime, _if you can_, please prefer the Cython ones as they are 100% guaranteed to be compatible with original BLAS/LAPACK signatures with no modifications.

**Comment by anutosh491** [comment]
Thanks for the guidance here @ilayn 

I think this might be the reason to convert the functions to subroutines (https://github.com/scipy/scipy/pull/19816#issuecomment-1970338432)

I went through 2 PRs in particular https://github.com/scipy/scipy/pull/20232 and https://github.com/scipy/scipy/pull/19816
which atleast gave me some idea about the latest changes involved in the BLAS/LAPACK wrapper infrastructure.

Not sure all my doubts are answered but I shall ask here if i encounter any more !
