### ISSUE TITLE
DOC: optimize.root: outdated naming of fprime in `method=’hybr’`

### ISSUE THREAD

**Issue by lukjp** [scipy/scipy#21627]
### Issue with current documentation:

The documentation for `optimize.root(method=’hybr’)`  [https://scipy.github.io/devdocs/reference/optimize.root-hybr.html](https://scipy.github.io/devdocs/reference/optimize.root-hybr.html) contains references to a parameter `fprime` which does not exist for that function. Specifically, these references appear in the description of the parameters `band` and `eps`.  The parameter `fprime` seems to be renamed to `jac` in `optimize.root` in scipy 0.11.

### Idea or request for content:

Replace the two occurrences of `fprime` with `jac` in the documentation for `optimize.root(method=’hybr’)`.

**Comment by lucascolley** [comment]
thanks @lukjp, your analysis sounds correct to me. Would you like to submit a fix? Our contributor docs are at https://scipy.github.io/devdocs/dev/index.html.

**Comment by lucascolley** [comment]
@oceanthunder go ahead! (we don't typically assign issues in SciPy). Our contributor docs are at http://scipy.github.io/devdocs/dev/index.html :)
