### ISSUE TITLE
BLD, MAINT: linker warnings with newer AppleClang/ld

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#21660]
On latest `main` branch with `Apple clang version 16.0.0 (clang-1600.0.26.3)`, with a typical build incantation like `python dev.py build -j 16 --with-accelerate`, this warning gets spammed pretty heavily:

`ld: warning: -ld_classic is deprecated and will be removed in a future release` 

There's some discussion and a link to the official Xcode release notes section here: https://stackoverflow.com/questions/79006466/ld-classic-will-be-deprecated-in-xcode

It looks like increasing the minimum MacOS deployment target is one option, but a quick local grep suggests we have at least one usage of `export MACOSX_DEPLOYMENT_TARGET=10.9`, and IIRC messing with this stuff in our (wheel) builds has been a recipe for discovering new problems.

**Comment by tylerjereddy** [comment]
For some context on the original motivation for using the older linker: gh-19400

**Comment by rgommers** [comment]
We needed `ld_classic` on macOS 14.0; old versions aren't relevant. Things recently got fixed in a new macOS toolchain version, see the discussion at https://github.com/spack/spack/pull/46608. It unclear where it got fixed exactly though, so we almost certainly cannot drop the flag unconditionally.

We probably should switch usage on Apple clang version `>=16.0.0`.

**Comment by andyfaff** [comment]
I think clang 16 corresponds to the latest version of Xcode (16) command line tools. I'm not sure what the minimum version of the tools we can get away with.

**Comment by czgdp1807** [comment]
I am able to reproduce these warnings with `Apple clang version 16.0.0 (clang-1600.0.26.4)`. Thinking of how to fix this? May be worth checking the scene with new linker. There is update from 1600.0.26.3 to 1600.0.26.4. So I will check if something changed in between.
