### ISSUE TITLE
BUG: signal.ShortTimeFFT: inverse tranform error with multichannel input

### ISSUE THREAD

**Issue by tjoubaud** [scipy/scipy#21671]
### Description
I'm not sure if the Short-Time Fourier Transform (STFT) is supposed to work with multichannel input signals. But the legacy ``scipy.signal.stft`` did so I tried. 

The inverse transform from ``ShortTimeFFT.istft`` gives an error with multichannel data, that occurs if the window and FFT size are different.

### Reproducing Code Example
```python
import numpy as np
from scipy.signal import ShortTimeFFT
from scipy.signal.windows import hann

# Window of size 100, and FFT of size 128
my_stf = ShortTimeFFT(win=hann(100), hop=50, fs=1, mfft=128)

# Original multichannel (two channels) input data
original_signal = np.random.random((2, 1000))

# Compute the STFT
short_time_fourier_transform = my_stf.stft(original_signal)

# Compute the inverse STFT
reconstructed_signal = reconstructed_signal = my_stf.istft(short_time_fourier_transform)
```

### Error Message
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Utils\mambaforge\envs\test\Lib\site-packages\scipy\signal\_short_time_fft.py", line 1070, in istft
    xs = self._ifft_func(S[..., :, q_ - self.p_min]) * self.dual_win
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
ValueError: operands could not be broadcast together with shapes (2,128) (100,)
```

### Bug Identification
The error seems to come from the following line of the ``ShortTimeFFT._iff_func`` method:
https://github.com/scipy/scipy/blob/c43875e23dd09bb512a0defefb4cb94568a70459/scipy/signal/_short_time_fft.py#L1628
The slicing is necessary when the window size and the FFT size are different, but it doesn't take the other dimensions into account.
A simple fix would be:
```python
return np.roll(x, p_s, axis=-1)[..., :self.m_num]
```
But it requires to check if everything works after it.

Thanks so much to the team for this project !

**Comment by j-bowhay** [comment]
cc @DietBru

**Comment by tjoubaud** [comment]
Wow thank you so much for the quick fix! 👏

**Comment by DietBru** [comment]
The excellent bug report helped a lot.
