### ISSUE TITLE
BUG: `scipy.linalg.fractional_matrix_power` behaves differently with SciPy 1.14 on macOS

### ISSUE THREAD

**Issue by t-imamichi** [scipy/scipy#21687]
### Describe your issue.

`scipy.linalg.fractional_matrix_power` behaves differently with SciPy 1.14 on macOS (CPU: Apple M1 Max) compared to outcomes with SciPy 1.13 or  Linux.
I guess it is related to the Accelerate library introduced by 1.14 for macOS.

### Reproducing Code Example

```python
import scipy
print("scipy", scipy.__version__)
mat = [[0, -1j], [1j, 0]]
print(scipy.linalg.fractional_matrix_power(mat, 0.5))
```

### Error message

```shell
# macOS 15.0.1, Python 3.12.7, SciPy 1.14.1
scipy 1.14.1
[[ 0.5-0.5j  0.5-0.5j]
 [-0.5+0.5j  0.5-0.5j]]
```

```
# macOS 15.0.1, Python 3.12.7, SciPy 1.13.1
scipy 1.13.1
[[ 0.5+0.5j -0.5-0.5j]
 [ 0.5+0.5j  0.5+0.5j]]
```

```
# RedHat 9.4, Python 3.12.7, SciPy 1.14.1
scipy 1.14.1
[[ 0.5+0.5j -0.5-0.5j]
 [ 0.5+0.5j  0.5+0.5j]]
```

```
# RedHat 9.4, Python 3.12.7, SciPy 1.13.1
scipy 1.13.1
[[ 0.5+0.5j -0.5-0.5j]
 [ 0.5+0.5j  0.5+0.5j]]
```

### SciPy/NumPy/Python version and system information

```shell
1.14.1 2.1.2 sys.version_info(major=3, minor=12, micro=7, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: extraframeworks
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: extraframeworks
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 13.3.0
  pythran:
    include directory: ../../../../../../private/var/folders/hw/1f0gcr8d6kn9ms0_wn0_57qc0000gn/T/pip-build-env-bjescfad/overlay/lib/python3.12/site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/hw/1f0gcr8d6kn9ms0_wn0_57qc0000gn/T/cibw-run-oogm4_8g/cp312-macosx_arm64/build/venv/bin/python
  version: '3.12'
```

**Comment by tylerjereddy** [comment]
@t-imamichi can you confirm a few things:

1) You are installing SciPy using `pip`/PyPI wheels, right?
2) You've claimed different behavior, but not necessarily incorrect behavior--are the new results incorrect or just a different way of representing a similar result? If the new results are incorrect, as might be implied by the `BUG` label, one might expect our testsuite to fail.

I should cc @ilayn -- are these valid permutations of the same result, or are some of the results categorically incorrect here? My linear algebra foo is not strong enough.

**Comment by ilayn** [comment]
Yes in this case they are permutations of a square root. When an array has an eigenvalue on the negative real line, then fractional powers can fall to either side of 0, depending what that architecture decides. 

For dense square roots I'd recommend using `sqrtm` from linalg module though probably the problem is simplified to make a point. The plan is to rewrite `sqrtm` such that the algorithm tries its best to stay in the real domain as much as possible. So it might give a bit more stability but the problem itself is inherently difficult to tackle in floating point number system.

**Comment by t-imamichi** [comment]
@tylerjereddy Thank you for your response.
1. Yes, I installed scipy 1.13.1 and 1.14.1 using pip
2. Exactly. They are not incorrect behavior. The resulting matrices are different as I showed, but they are both root square matrices. I attach a script below to confirm it.

@ilayn Thank you for your suggestion of `sqrtm`. I tried it and found that it behaves same as `fractional_matrix_power` for this matrix. I understand the stability issue due to floating number system is not easy. So, I'm fine to close this issue because it returns a correct square root matrix though it may vary depending on blas library.

```python
import scipy
import numpy as np

print("scipy", scipy.__version__)
mat = [[0, -1j], [1j, 0]]

sqrt = scipy.linalg.fractional_matrix_power(mat, 0.5)
print("fractional_matrix_power")
print(sqrt)
print("sqrt?", np.allclose(sqrt @ sqrt, mat), end="\n\n")
print("eigvals", np.linalg.eigvals(sqrt))

sqrt = scipy.linalg.sqrtm(mat)
print("sqrtm")
print(sqrt)
print("sqrt?", np.allclose(sqrt @ sqrt, mat), end="\n\n")
print("eigvals", np.linalg.eigvals(sqrt))
```

```
# macOS 15.0.1, Python 3.12.7, SciPy 1.14.1
scipy 1.14.1
fractional_matrix_power
[[ 0.5-0.5j  0.5-0.5j]
 [-0.5+0.5j  0.5-0.5j]]
sqrt? True
eigvals [-1.11022302e-16-1.00000000e+00j  1.00000000e+00-8.32667268e-17j]

sqrtm
[[ 0.5-0.5j  0.5-0.5j]
 [-0.5+0.5j  0.5-0.5j]]
sqrt? True
eigvals [0.-1.00000000e+00j 1.-2.77555756e-17j]
```

```
# macOS 15.0.1, Python 3.12.7, SciPy 1.13.1
scipy 1.13.1
fractional_matrix_power
[[ 0.5+0.5j -0.5-0.5j]
 [ 0.5+0.5j  0.5+0.5j]]
sqrt? True
eigvals [8.32667268e-16+1.0000000e+00j 1.00000000e+00-1.2490009e-16j]

sqrtm
[[ 0.5+0.5j -0.5-0.5j]
 [ 0.5+0.5j  0.5+0.5j]]
sqrt? True
eigvals [-5.55111512e-17+1.00000000e+00j  1.00000000e+00+4.16333634e-17j]
```
