### ISSUE TITLE
ENH: interpolate.LinearNDInterpolator option to use boundary values for output instead of returning NaN

### ISSUE THREAD

**Issue by Vetri911** [scipy/scipy#21698]
### Is your feature request related to a problem? Please describe.

the LinearNDInterpolator object returns nan when an out of bounds input is provided. the `fill_value` argument allows a single constant value to be used instead of nan but I'd want the interpolator to return the boundary value.

example of what I currently do to get the boundary value.
 I create an interpolator object as shown below:

```
import numpy as np
from scipy import interpolate

arr_10 = np.linspace(0, 1, 10)
arr_5 = np.linspace(0, 1, 5)
arr_5x10 = np.random.rand(5, 10)

\# Create meshgrid and prepare points and values
grid_10, grid_5 = np.meshgrid(arr_10, arr_5)
points = np.column_stack([grid_5.ravel(), grid_10.ravel()])
values = arr_5x10.ravel()

\# Create the interpolator
interpolator = interpolate.LinearNDInterpolator(points, values)
```

Now if I want the interpolator to return an actual number for any input values I need to use `np.clip()` to clip the inputs so that it stays within the interpolators bounds and return an actual value which is the value at the boundary.

```
# usage
xi = -1
yi = 6
# clip to endpoints because LinearNDInterpolator returns NaN when out of bounds
x_clipped = np.clip(xi, arr_10.min(), arr_10.max())
y_clipped = np.clip(yi, arr_5.min(), arr_5.max())
output = interpolator(x_clipped, y_clipped) 

```

### Describe the solution you'd like.

if there were a flag built into the LinearNDInterpolator called **fill_method='boundary'** that would enable this behavior, it would be convenient

see how I use the `fill_method` to create the interpolator object
```
[setup same as above]

\# Create the interpolator
interpolator = interpolate.LinearNDInterpolator(points, values, fill_method='boundary')
```

when I use the interpolator object below, I don't have to use `np.clip()`
```
xi = -1
yi = 6
output = interpolator(xi, yi)  
```

this is just an example to get the point across on what feature I'm requesting.
 If we don't want to use **fill_method='boundary'**, maybe `bounded_output=True` can be used instead.

### Describe alternatives you've considered.

described in feature request

**Comment by Vetri911** [comment]
The above request would apply to all the other Interpolator objects like `RegularGridInterpolator` too.

**Comment by ev-br** [comment]
Experience tells us that these sorts of extrapolation options are best done on the user side. For instance, you can have an object that wraps a LinearNDInterpolator instance and clips the values just like you've shown.

**Comment by Vetri911** [comment]
Understood.

**Comment by ev-br** [comment]
Let me close this then. Thanks @Vetri911 for starting the conversation! (even if we're going to leave this to users in the end)
