### ISSUE TITLE
ENH: stats: add Cantor distribution under new infrastructure

### ISSUE THREAD

**Issue by fancidev** [scipy/scipy#21708]
### Is your feature request related to a problem? Please describe.

In https://github.com/scipy/scipy/pull/21700 there is discussion about factoring a base class for statistical distributions under the new framework. For such a base class to be fully generic, it would need to cover (mixtures of) continuous, discrete, and [singular distributions](https://en.m.wikipedia.org/wiki/Singular_distribution).

The [Cantor distribution](https://en.m.wikipedia.org/wiki/Cantor_distribution) is a curious example of a singular distribution. Having such a class would help to test/verify the “completeness” of the infrastructure.

### Describe the solution you'd like.

Add a class, `scipy.stats.Cantor`, that represents the Cantor distribution. The class would be derived from a base class to be formed.

### Additional context (e.g. screenshots, GIFs)

Less curious singular distributions exist in higher dimensions. For example, a bivariate normal distribution constructed from two perfectly correlated normal variables.

I’m not aware of any statistical application involving the Cantor distribution. So this enhancement proposal is more for fun. Or, it might be used in school lectures, who knows!

**Comment by kumarpreetilata** [comment]
I believe the proposal to add CantorDistribution class is a strong idea and it has some interesting characteristics that differ from typical distributions, which will also provides the users, access to a wider variety of statistical tools. And indeed can be fun for educational purposes.

import numpy as np
from scipy import stats

class CantorDistribution(stats.rv_continuous):
    """Cantor distribution."""

    def _pdf(self, x):
        """Probability density function of the Cantor distribution."""
        if (x < 0) or (x > 1):
            return 0
        
        # The Cantor distribution is defined on [0, 1]
        # Density is concentrated at points in the Cantor set
        density = 0
        if x in [0.5**k for k in range(1, 11)]:
            density = 1 / (np.log(2) * (2 ** (10)))  # Normalized density at Cantor points
        return density

    def _cdf(self, x):
        """Cumulative distribution function of the Cantor distribution."""
        if x < 0:
            return 0
        if x >= 1:
            return 1
        
        # Count contributions from Cantor set points
        cdf = 0
        for k in range(1, 11):
            if (0.5 ** k) <= x:
                cdf += (1 / 2) ** k
        return cdf

    def _rvs(self, size=1):
        """Random variates of the Cantor distribution."""
        # Randomly select points from the Cantor set
        points = []
        for _ in range(size):
            num = np.random.rand()
            point = 0
            for k in range(10):  # Number of iterations
                if num < 1/3:
                    point += 0  # Take the left segment
                elif num < 2/3:
                    point += 0.5 ** (k + 1)  # Take the middle segment
                num = (num - 1/3) * 3  # Rescale for the next iteration
            points.append(point)
        return np.array(points)

    def mean(self):
        """Mean of the Cantor distribution."""
        return 0.5

    def variance(self):
        """Variance of the Cantor distribution."""
        return 1 / 12

# Instantiate the Cantor distribution
cantor_dist = CantorDistribution(name='cantor')


Let me know if this is what you want.

**Comment by kumarpreetilata** [comment]
import numpy as np
from scipy import stats

class CantorDistribution(stats.rv_continuous):
    #Cantor distribution

    def _pdf(self, x):
        """Probability density function of the Cantor distribution."""
        if (x < 0) or (x > 1):
            return 0
        
        # The Cantor distribution is defined on [0, 1]
        # Density is concentrated at points in the Cantor set
        density = 0
        if x in [0.5**k for k in range(1, 11)]:
            density = 1 / (np.log(2) * (2 ** (10)))  # Normalized density at Cantor points
        return density

    def _cdf(self, x):
        """Cumulative distribution function of the Cantor distribution."""
        if x < 0:
            return 0
        if x >= 1:
            return 1
        
        # Count contributions from Cantor set points
        cdf = 0
        for k in range(1, 11):
            if (0.5 ** k) <= x:
                cdf += (1 / 2) ** k
        return cdf

    def _rvs(self, size=1):
        """Random variates of the Cantor distribution."""
        # Randomly select points from the Cantor set
        points = []
        for _ in range(size):
            num = np.random.rand()
            point = 0
            for k in range(10):  # Number of iterations
                if num < 1/3:
                    point += 0  # Take the left segment
                elif num < 2/3:
                    point += 0.5 ** (k + 1)  # Take the middle segment
                num = (num - 1/3) * 3  # Rescale for the next iteration
            points.append(point)
        return np.array(points)

    def mean(self):
        """Mean of the Cantor distribution."""
        return 0.5

    def variance(self):
        """Variance of the Cantor distribution."""
        return 1 / 12

# Instantiate the Cantor distribution
cantor_dist = CantorDistribution(name='cantor')

**Comment by kumarpreetilata** [comment]
Let me know if thats what you want as class:

    def _pdf(self, x):
        """Probability density function of the Cantor distribution."""
        if (x < 0) or (x > 1):
            return 0
        
        # The Cantor distribution is defined on [0, 1]
        # Density is concentrated at points in the Cantor set
        density = 0
        if x in [0.5**k for k in range(1, 11)]:
            density = 1 / (np.log(2) * (2 ** (10)))  # Normalized density at Cantor points
        return density

    def _cdf(self, x):
        """Cumulative distribution function of the Cantor distribution."""
        if x < 0:
            return 0
        if x >= 1:
            return 1
        
        # Count contributions from Cantor set points
        cdf = 0
        for k in range(1, 11):
            if (0.5 ** k) <= x:
                cdf += (1 / 2) ** k
        return cdf

    def _rvs(self, size=1):
        """Random variates of the Cantor distribution."""
        # Randomly select points from the Cantor set
        points = []
        for _ in range(size):
            num = np.random.rand()
            point = 0
            for k in range(10):  # Number of iterations
                if num < 1/3:
                    point += 0  # Take the left segment
                elif num < 2/3:
                    point += 0.5 ** (k + 1)  # Take the middle segment
                num = (num - 1/3) * 3  # Rescale for the next iteration
            points.append(point)
        return np.array(points)

    def mean(self):
        """Mean of the Cantor distribution."""
        return 0.5

    def variance(self):
        """Variance of the Cantor distribution."""
        return 1 / 12

cantor_dist = CantorDistribution(name='cantor') # Instantiate the Cantor distribution



`

**Comment by steppi** [comment]
I'm -1 for adding this to SciPy. IMO, there are a lot of things which should be given priority over adding distributions which are only interesting as mathematical curiosities. There was talk about having a `scikit-stats` package that could contain third-party distribution implementations using SciPy's new infrastructure, and this could be a good fit there though.

**Comment by fancidev** [comment]
Thanks for the interest @kumarpreetilata. I think your code illustrates the idea well, though there can be details to polish.

One particular point of interest is that your code intends to assign non-zero density to points where the CDF "jumps". I would assign the density to zero. What makes the choice interesting is that it's not an isolated case -- for example in gh-21700 the OP asks the question:

> When there are discrete distributions in the mixture [with continuous distributions], I suppose the PDF at the support values of the discrete distributions will be infinite? And perhaps this class should also have a PMF method, and the PMF at values that are not in the support of a discrete distribution would be zero?

The choice might appear arbitrary (it could return infinity, zero, ValueError, nan, etc), but I think zero is a well-defined choice based on the fact that *any* probability distribution can be decomposed into the mixture of a continuous, a discrete, and a singular distribution. The PDF and PMF would correspond to the continuous and discrete component, respectively.

How is this related to the Cantor distribution in this thread? I'll elaborate in the next comment.

**Comment by josef-pkt** [comment]
I agree with @steppi 

It does not behave like any "usual" distribution, and I don't see any real life application for it.
It will only confuse users who try out distributions without checking the math, and if they do they will just ignore it.

(AFAIR, the only time I learned about Cantor set was as counter example to some probability or measure theory definitions.)

How would you define and compute the expectation of a function w.r.t. the Cantor distribution, or draw a random sample

AFAICS, @kumarpreetilata functions truncate the construction of cantor points. I doubt that that has any useful applications either.

**Comment by fancidev** [comment]
Interesting points! I’d say those are the fun part and in fact quite enlightening.

> It does not behave like any "usual" distribution, and I don't see any real life application for it. It will only confuse users who try out distributions without checking the math, and if they do they will just ignore it.

I agree there’s probably little practical use of the distribution. But I don’t think it would cause much confusion — the CDF plot of Cantor distribution looks just like any empirical distribution, so I don’t foresee anything special in *using* it. (Though there is clearly something special in *writing* it.)

> (AFAIR, the only time I learned about Cantor set was as counter example to some probability or measure theory definitions.)

Quite the opposite — it is a counter example of heuristic reasoning about probability distributions. It is well treated within the framework of probability theory, and that’s why I propose to use it as a “test case” to verify the “completeness” of our new distribution framework — if the framework is compatible with Cantor (I think it is or at least almost is), we can be fairly confident that the framework will be able to handle *any* probability distribution to ever occur.

> How would you define and compute the expectation of a function w.r.t. the Cantor distribution

The mathematical definition is standard and is the same as any other distribution:

$$
\mathbb{E}[g(X)] := \int_{[0,1]} g(x) \mathrm{d} \mu
$$

where $\mu$ is the probability measure and the integral is understood to be a Lebesgue integral.

How it can be evaluated numerically is not more difficult than quadrature, except that where one would plug in the density function for quadrature, one would instead plug in the “average” density (i.e. difference of CDF over  bucket length).

> or draw a random sample

This is a very interesting question and there’s [an answer for it on Cross Validated](https://stats.stackexchange.com/questions/229556/how-to-sample-from-cantor-distribution). The algorithm is surprisingly simple (and I think simpler than computing the CDF).

> AFAICS, @kumarpreetilata functions truncate the construction of cantor points. I doubt that that has any useful applications either.

Since floating point numbers are rational approximations to real numbers, some truncation needs to happen anyway. (This is much like truncating the Taylor series to evaluate sin(x) numerically.) Using merely ten terms is probably not enough for accuracy, and those are the sort of numerical details to polish.

**Comment by mdhaber** [comment]
> I agree there’s probably little practical use of the distribution.

Then it doesn't belong in SciPy.

**Comment by steppi** [comment]
See also the section [deciding on new features](https://docs.scipy.org/doc/scipy/dev/core-dev/index.html#deciding-on-new-features) in the core developer guide.

1. The method is applicable in many fields and “generally agreed” to be useful,

2. It fits the topic of the submodule, and does not require extensive support frameworks to operate,

3. The implementation looks sound and unlikely to need much tweaking in the future (e.g., limited expected maintenance burden),

4. Someone wants to contribute it, and

5. Someone wants to review it.

**Comment by fancidev** [comment]
Thanks for your comments @steppi and @mdhaber.

My intent is less about adding the Cantor distribution itself but more about making sure that the new statistical distribution infrastructure has enough flexibility to support a wide range of custom distributions. Of course such “generality” needs to carefully defined — not too specific to exclude valid use cases, and not too generic to offer no aid to the user. (The old rv_generic framework is too “specific” in this sense since it’s not possible to implement mixed discrete-continuous distribution without hackish “monkey patching”.)

I really like the initiative of the new infrastructure and I’m confident it will enable new possibilities that make `scipy.stats` better. I took the liberty to investigate the “boundary” of the new infrastructure — what kind of distributions are possible to implement under the new framework, without hacking the framework itself? (It seems mixed discrete-continuous distributions are already under the radar of @mdhaber, which is great.)

After much research I arrived at the conclusion that the new infrastructure is really close to, if not yet, supporting *arbitrary* (univariate) probability distributions. I think this is an important point because it implies we will never have to invent a new new framework ever again due to the new framework lacking some feature that cannot be added in a backward compatible way.

How to ensure that generality is not compromised while defining/implementing methods of the new base class (say `_ProbabilityDistribution`)? I think the easiest way is to actually *have* a distribution that relies on the generality being available. If you don’t have a mixed discrete-continuous distribution, you won’t find out something doesn’t work for mixed discrete-continuous distribution. Likewise, if you don’t have a “weird” distribution like Cantor, you won’t know some specification/implementation doesn’t generalize to “weird” distributions.

An alternative to this generality is to state that the new infrastructure only supports mixture of discrete and continuous distributions. I think that will satisfy most practical applications, so is a viable choice. However, I’d still like to advocate for full generality because there is little extra coding effort to spend (if any at all) to go from mixed discrete-continuous to fully general, so why not? If the design is fully general, then it will never have to be revisited again. This probably saves resource in the long run.

I understand the above might be too “forward looking” and lacks traction probably because there’re not yet concrete examples to illustrate the loss of generality (apart from  mixed discrete-continuous distributions which are on the radar). It could have been more intuitively explained if concrete examples are gathered.

Therefore I’m closing this issue right now and we could possibly revisit when specific issues arise. Anyway I hope you could give a thought about singular distribution support when making specifications/implementations.

Thanks for your input!
