### ISSUE TITLE
QUERY: `optimize.least_squares`: can't find global optimum

### ISSUE THREAD

**Issue by MayDay-618** [scipy/scipy#21720]
### Describe your issue.

使用以下代码测试了多组数据，其他数据正常，就这组数据的中心和法矢结果异常
正确的拟合中心结果应为(-81.0599, 224.4439, -59.2489)
正确的拟合法矢应为(0.2408,-0.8741,0.4216)
正确的半径为：90.0844

该程序返回的结果为：
center: [ 13926.13922344 -13792.57983071 -25785.65602216]
radius: 69.93557788915145
normal: [ 0.43364558 -0.41901277 -0.79773417]

### Reproducing Code Example

```python
import numpy as np
import sys
import scipy, numpy;
from scipy.optimize import least_squares

# 设置 NumPy 打印选项
np.set_printoptions(suppress=True)

# 圆柱模型函数: 计算每个点到圆柱轴线的径向距离与半径的差
def cylinder_model(params, points):
    cx, cy, cz, nx, ny, nz, R = params
    x, y, z = points.T  # 提取坐标

    # 向量化处理点和圆柱轴线
    point_vec = np.vstack([x - cx, y - cy, z - cz]).T  # 点到中心的向量
    axis_dir = np.array([nx, ny, nz])  # 轴线方向向量
    axis_dir = axis_dir / np.linalg.norm(axis_dir)  # 确保轴线方向是单位向量

    # 计算点到轴线的径向矢量
    radial_vec = point_vec - np.dot(point_vec, axis_dir)[:, None] * axis_dir
    radial_dist = np.linalg.norm(radial_vec, axis=1)  # 径向距离

    # 返回径向距离与半径的差异
    return radial_dist - R

# 拟合三维圆柱面的函数
def fit_cylinder(points):    
    # 初始猜测: 中心 (cx, cy, cz), 轴线 (nx, ny, nz), 半径 R
    cx_init, cy_init, cz_init = np.mean(points, axis=0)
    nx_init, ny_init, nz_init = 0, 0, 1  # 初始猜测轴线方向为 z 轴
    R_init = np.mean(np.linalg.norm(points[:, :2] - np.array([cx_init, cy_init]), axis=1))  # 粗略猜测半径

    # 初始参数
    initial_params = [cx_init, cy_init, cz_init, nx_init, ny_init, nz_init, R_init]

    # 使用 least_squares 进行拟合
    result = least_squares(cylinder_model, initial_params, args=(points,))
    return result.x  # 返回拟合后的参数

if __name__ == "__main__":
    print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()

    points = np.array([
        [  28.636, -290.326,  -35.387],
        [  17.405, -250.466,  -53.514],
        [   7.018, -208.556,  -71.843],
        [   7.966, -265.457,   25.375],
        [  -6.252, -221.003,    6.872],
        [ -16.585, -184.663,  -10.055],
        [ -59.899, -266.688,   61.332],
        [ -76.227, -226.791,   41.705],
        [ -84.871, -190.207,   24.145],
        [-121.896, -293.137,   42.66 ],
        [-134.328, -252.854,   21.777],
        [-145.383, -214.023,    2.875],
        [-144.795, -330.502,  -15.337],
        [-157.98 , -284.984,  -38.869],
        [-167.874, -249.104,  -60.791],
        [-115.361, -348.159,  -75.986],
        [-126.041, -308.728,  -95.174],
        [-138.138, -268.343, -113.089],
        [ -53.828, -346.446, -100.095],
        [ -65.114, -300.601, -122.835],
        [ -71.478, -265.374, -139.241],
        [   3.049, -320.014,  -84.205],
        [ -12.248, -280.269, -106.856],
        [ -20.556, -240.501, -123.873],
    ])
    # print("points", points)

    # 拟合三维圆柱面
    params = fit_cylinder(points)

    # print(f'结果参数: {params}')
    center = np.array(params[0:3])
    normal = np.array(params[3:6])
    radius = params[6]

    # 计算向量的模
    magnitude = np.linalg.norm(normal)

    # 确保不除以零
    if magnitude == 0:
        unit_vector = normal  # 原向量就是零向量
    else:
        unit_vector = normal / magnitude

    print(f'center: {center}')
    print(f'radius: {radius}')
    print(f'normal: {unit_vector}')
```

### Error message

```shell
无报错，执行结果错误
```

### SciPy/NumPy/Python version and system information

```shell
1.14.1 2.1.2 sys.version_info(major=3, minor=11, micro=5, releaselevel='final', serial=0)
E:\code\python\测试\venv\Lib\site-packages\scipy\__config__.py:154: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "c++"
    },
    "fortran": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "10.3.0",
      "commands": "gfortran"
    },
    "pythran": {
      "version": "0.16.1",
      "include directory": "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-build-env-utnpaygc\\overlay\\Lib\\site-packages/pythran"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "cross-compiled": false
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.27.dev",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-rrcld3x_/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/include",
      "lib directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-rrcld3x_/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/lib",
      "openblas configuration": "OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=24",
      "pc file directory": "D:/a/scipy/scipy"
    },
    "lapack": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.27.dev",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-rrcld3x_/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/include",
      "lib directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-rrcld3x_/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/lib",
      "openblas configuration": "OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=24",
      "pc file directory": "D:/a/scipy/scipy"
    },
    "pybind11": {
      "name": "pybind11",
      "version": "2.12.0",
      "detection method": "config-tool",
      "include directory": "unknown"
    }
  },
  "Python Information": {
    "path": "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\cibw-run-rrcld3x_\\cp311-win_amd64\\build\\venv\\Scripts\\python.exe",
    "version": "3.11"
  }
}
```

**Comment by rkern** [comment]
There is no guarantee that nonlinear optimizers like those used by `least_squares` will reach the global optimum. The initial guess needs to be close (for problem-dependent definitions of "close"). Consider trying to guess the normal vector from the data instead of hard-coding it.

**Comment by nickodell** [comment]
Hello, I helped someone with a similar problem on StackOverflow. The link is here: https://stackoverflow.com/questions/77134139/fit-3d-cylinder-in-a-point-cloud/77334250#77334250

The code at the link works by minimizing a function of the cylinder position and direction, in order to minimize the standard deviation of the distance from the central axis of the cylinder, and the distance between the center of the cylinder and the cylinder position. After finding the cylinder position and direction, it can find R and height, if needed. As mentioned, this problem has local minima, so it uses random restarts with different direction vectors to find the global minimum.

That code is capable of finding a solution to your problem. It is slightly different from what you need, as that person was using Pandas, and you are using NumPy.

Here's how to use this code to solve your problem:

```
import numpy as np
from scipy.optimize import minimize
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt


points = np.array([
    [  28.636, -290.326,  -35.387],
    [  17.405, -250.466,  -53.514],
    [   7.018, -208.556,  -71.843],
    [   7.966, -265.457,   25.375],
    [  -6.252, -221.003,    6.872],
    [ -16.585, -184.663,  -10.055],
    [ -59.899, -266.688,   61.332],
    [ -76.227, -226.791,   41.705],
    [ -84.871, -190.207,   24.145],
    [-121.896, -293.137,   42.66 ],
    [-134.328, -252.854,   21.777],
    [-145.383, -214.023,    2.875],
    [-144.795, -330.502,  -15.337],
    [-157.98 , -284.984,  -38.869],
    [-167.874, -249.104,  -60.791],
    [-115.361, -348.159,  -75.986],
    [-126.041, -308.728,  -95.174],
    [-138.138, -268.343, -113.089],
    [ -53.828, -346.446, -100.095],
    [ -65.114, -300.601, -122.835],
    [ -71.478, -265.374, -139.241],
    [   3.049, -320.014,  -84.205],
    [ -12.248, -280.269, -106.856],
    [ -20.556, -240.501, -123.873],
])


def proj(x, y):
    if x.shape == y.shape:
        # single x vector
        return y * (np.dot(x, y) / np.dot(y, y))
    else:
        # broadcast along x
        return y[np.newaxis, :] * (np.dot(x, y) / np.dot(y, y))[:, np.newaxis]


def scalar_proj(x, y):
    if x.shape == y.shape:
        # single x vector
        return (np.dot(x, y) / np.dot(y, y))
    else:
        # broadcast along x
        return (np.dot(x, y) / np.dot(y, y))[:, np.newaxis]
    
    
def normalize(v):
    norm = np.linalg.norm(v)
    if norm == 0: 
        raise Exception("Division by zero in normalize")
    return v / norm


def distance_from_central_axis(cyl_center, cyl_vec, point_vec):
    cyl_vec = normalize(cyl_vec)
    point_offset = point_vec - cyl_center
    center_to_point = point_offset - proj(point_offset, cyl_vec)
    distance = np.linalg.norm(center_to_point, axis=1)
    return distance


def distance_along_central_axis(cyl_center, cyl_vec, point_vec):
    cyl_vec = normalize(cyl_vec)
    point_offset = point_vec - cyl_center
    signed_distance_along_central_axis = scalar_proj(point_offset, cyl_vec)
    return signed_distance_along_central_axis


def cylinder_radius(cyl_center, cyl_vec, point_vec):
    return np.mean(distance_from_central_axis(cyl_center, cyl_vec, point_vec))


def cylinder_height(cyl_center, cyl_vec, point_vec):
    distance = distance_along_central_axis(cyl_center, cyl_vec, point_vec)
    return np.min(distance), np.max(distance)


def cost_func(x, points):
    a, b, c, d, e, f = x
    cyl_center = np.array([a, b, c])
    cyl_vec = np.array([d, e, f])
    distances = distance_from_central_axis(cyl_center, cyl_vec, points)
    # Minimize variance of distance
    distance_variance_penalty = np.std(distances)
    # Also penalize having center off-center
    off_center_penalty = distance_along_central_axis(cyl_center, cyl_vec, points).mean() ** 2
    return distance_variance_penalty + off_center_penalty


def guess_cyl_vec(points):
    return PCA(n_components=1).fit(points).components_[0]


def find_cyl_center_and_vec(points, n_iter=10):
    
    # Note: this fit is running in a loop because I found that the minimizer
    # got trapped in local minima if provided with a bad initial guess.
    # To compensate for this, run the fit `n_iter` times and pick the best one.
    best = None
    for i in range(n_iter):
        x0 = np.random.normal(size=6)
        # Use mean as position guess instead of random
        x0[0:3] = points.mean(axis=0)
        options = {
            'eps': 1e-9
        }
        res = minimize(cost_func, x0=x0, args=points, options=options, method='BFGS')
        if best is None or res.fun < best.fun:
            best = res
    cyl_center, cyl_vec = best.x.reshape([2, 3])
    cyl_vec = normalize(cyl_vec)
    # Force Z to be non-negative
    if cyl_vec[2] < 0:
        cyl_vec = -cyl_vec
    return cyl_center, cyl_vec


def get_cylinder_points(cyl_center, cyl_vec, radius, height_min, height_max):
    t_height = np.linspace(height_min, height_max, 1000)[:, np.newaxis]
    turns = 10
    t_rot = np.linspace(0, 2*turns*np.pi, 1000)[:, np.newaxis]
    central_axis = cyl_center + t_height * cyl_vec[np.newaxis]
    # Get orthogonal vectors using Gramm-Schmitt
    rotvec1 = np.random.randn(3)
    rotvec1 -= rotvec1.dot(cyl_vec) * cyl_vec
    rotvec1 /= np.linalg.norm(rotvec1)
    rotvec2 = np.cross(cyl_vec, rotvec1)
    cylinder_points = central_axis.copy()
    cylinder_points += radius * np.cos(t_rot) * rotvec1[np.newaxis]
    cylinder_points += radius * np.sin(t_rot) * rotvec2[np.newaxis]
    return cylinder_points


cyl_center, cyl_vec = find_cyl_center_and_vec(points)
radius = cylinder_radius(cyl_center, cyl_vec, points)
height_min, height_max = cylinder_height(cyl_center, cyl_vec, points)

fig = plt.figure(figsize=(8, 8))
ax = fig.add_subplot(111, projection='3d')

ax.scatter(*points.T)
ax.scatter(*get_cylinder_points(cyl_center, cyl_vec, radius, height_min, height_max).T)
plt.show()

print("center", cyl_center)
print("radius", radius)
print("normal", cyl_vec)
```

From this code, I get the following output:

```
center [ -69.70627405 -265.65679521  -39.36944244]
radius 90.0877468692447
normal [ 0.24082703 -0.87418268  0.42167165]
```

Here is a plot of the fit. The blue points represent the input data. The orange points represent the fit.

![Untitled](https://github.com/user-attachments/assets/46069678-7172-45fb-9fc4-cf9c854e4b8d)

**Comment by MayDay-618** [comment]
> 您好，我在 StackOverflow 上帮助遇到类似问题的人。链接在这里：[https://stackoverflow.com/questions/77134139/fit-3d-圆筒-in-a-point-cloud/77334250#77334250](https://stackoverflow.com/questions/77134139/fit-3d-cylinder-in-a-point-cloud/77334250#77334250)
> 
> 链接处的代码通过最小化圆柱位置和方向的函数来工作，以最小化圆柱中心轴距离的标准偏差以及圆柱中心与圆柱位置之间的距离。找到圆柱位置和方向后，就可以找到R和高度（如果需要）。 如上所述，此问题具有局部最小化，因此它使用不同方向管理的随机重启来找到全局最小化。
> 
> 该代码能够找到您问题的解决方案。它与您的需求不同，因为那个人使用的是 Pandas，而您使用的是 NumPy。
> 
> 以下是使用此代码解决您的问题的方法：
> 
> ```
> import numpy as np
> from scipy.optimize import minimize
> from sklearn.decomposition import PCA
> import matplotlib.pyplot as plt
> 
> 
> points = np.array([
>     [  28.636, -290.326,  -35.387],
>     [  17.405, -250.466,  -53.514],
>     [   7.018, -208.556,  -71.843],
>     [   7.966, -265.457,   25.375],
>     [  -6.252, -221.003,    6.872],
>     [ -16.585, -184.663,  -10.055],
>     [ -59.899, -266.688,   61.332],
>     [ -76.227, -226.791,   41.705],
>     [ -84.871, -190.207,   24.145],
>     [-121.896, -293.137,   42.66 ],
>     [-134.328, -252.854,   21.777],
>     [-145.383, -214.023,    2.875],
>     [-144.795, -330.502,  -15.337],
>     [-157.98 , -284.984,  -38.869],
>     [-167.874, -249.104,  -60.791],
>     [-115.361, -348.159,  -75.986],
>     [-126.041, -308.728,  -95.174],
>     [-138.138, -268.343, -113.089],
>     [ -53.828, -346.446, -100.095],
>     [ -65.114, -300.601, -122.835],
>     [ -71.478, -265.374, -139.241],
>     [   3.049, -320.014,  -84.205],
>     [ -12.248, -280.269, -106.856],
>     [ -20.556, -240.501, -123.873],
> ])
> 
> 
> def proj(x, y):
>     if x.shape == y.shape:
>         # single x vector
>         return y * (np.dot(x, y) / np.dot(y, y))
>     else:
>         # broadcast along x
>         return y[np.newaxis, :] * (np.dot(x, y) / np.dot(y, y))[:, np.newaxis]
> 
> 
> def scalar_proj(x, y):
>     if x.shape == y.shape:
>         # single x vector
>         return (np.dot(x, y) / np.dot(y, y))
>     else:
>         # broadcast along x
>         return (np.dot(x, y) / np.dot(y, y))[:, np.newaxis]
>     
>     
> def normalize(v):
>     norm = np.linalg.norm(v)
>     if norm == 0: 
>         raise Exception("Division by zero in normalize")
>     return v / norm
> 
> 
> def distance_from_central_axis(cyl_center, cyl_vec, point_vec):
>     cyl_vec = normalize(cyl_vec)
>     point_offset = point_vec - cyl_center
>     center_to_point = point_offset - proj(point_offset, cyl_vec)
>     distance = np.linalg.norm(center_to_point, axis=1)
>     return distance
> 
> 
> def distance_along_central_axis(cyl_center, cyl_vec, point_vec):
>     cyl_vec = normalize(cyl_vec)
>     point_offset = point_vec - cyl_center
>     signed_distance_along_central_axis = scalar_proj(point_offset, cyl_vec)
>     return signed_distance_along_central_axis
> 
> 
> def cylinder_radius(cyl_center, cyl_vec, point_vec):
>     return np.mean(distance_from_central_axis(cyl_center, cyl_vec, point_vec))
> 
> 
> def cylinder_height(cyl_center, cyl_vec, point_vec):
>     distance = distance_along_central_axis(cyl_center, cyl_vec, point_vec)
>     return np.min(distance), np.max(distance)
> 
> 
> def cost_func(x, points):
>     a, b, c, d, e, f = x
>     cyl_center = np.array([a, b, c])
>     cyl_vec = np.array([d, e, f])
>     distances = distance_from_central_axis(cyl_center, cyl_vec, points)
>     # Minimize variance of distance
>     distance_variance_penalty = np.std(distances)
>     # Also penalize having center off-center
>     off_center_penalty = distance_along_central_axis(cyl_center, cyl_vec, points).mean() ** 2
>     return distance_variance_penalty + off_center_penalty
> 
> 
> def guess_cyl_vec(points):
>     return PCA(n_components=1).fit(points).components_[0]
> 
> 
> def find_cyl_center_and_vec(points, n_iter=10):
>     
>     # Note: this fit is running in a loop because I found that the minimizer
>     # got trapped in local minima if provided with a bad initial guess.
>     # To compensate for this, run the fit `n_iter` times and pick the best one.
>     best = None
>     for i in range(n_iter):
>         x0 = np.random.normal(size=6)
>         # Use mean as position guess instead of random
>         x0[0:3] = points.mean(axis=0)
>         options = {
>             'eps': 1e-9
>         }
>         res = minimize(cost_func, x0=x0, args=points, options=options, method='BFGS')
>         if best is None or res.fun < best.fun:
>             best = res
>     cyl_center, cyl_vec = best.x.reshape([2, 3])
>     cyl_vec = normalize(cyl_vec)
>     # Force Z to be non-negative
>     if cyl_vec[2] < 0:
>         cyl_vec = -cyl_vec
>     return cyl_center, cyl_vec
> 
> 
> def get_cylinder_points(cyl_center, cyl_vec, radius, height_min, height_max):
>     t_height = np.linspace(height_min, height_max, 1000)[:, np.newaxis]
>     turns = 10
>     t_rot = np.linspace(0, 2*turns*np.pi, 1000)[:, np.newaxis]
>     central_axis = cyl_center + t_height * cyl_vec[np.newaxis]
>     # Get orthogonal vectors using Gramm-Schmitt
>     rotvec1 = np.random.randn(3)
>     rotvec1 -= rotvec1.dot(cyl_vec) * cyl_vec
>     rotvec1 /= np.linalg.norm(rotvec1)
>     rotvec2 = np.cross(cyl_vec, rotvec1)
>     cylinder_points = central_axis.copy()
>     cylinder_points += radius * np.cos(t_rot) * rotvec1[np.newaxis]
>     cylinder_points += radius * np.sin(t_rot) * rotvec2[np.newaxis]
>     return cylinder_points
> 
> 
> cyl_center, cyl_vec = find_cyl_center_and_vec(points)
> radius = cylinder_radius(cyl_center, cyl_vec, points)
> height_min, height_max = cylinder_height(cyl_center, cyl_vec, points)
> 
> fig = plt.figure(figsize=(8, 8))
> ax = fig.add_subplot(111, projection='3d')
> 
> ax.scatter(*points.T)
> ax.scatter(*get_cylinder_points(cyl_center, cyl_vec, radius, height_min, height_max).T)
> plt.show()
> 
> print("center", cyl_center)
> print("radius", radius)
> print("normal", cyl_vec)
> ```
> 
> 根据代码中，我得到以下输出：
> 
> ```
> center [ -69.70627405 -265.65679521  -39.36944244]
> radius 90.0877468692447
> normal [ 0.24082703 -0.87418268  0.42167165]
> ```
> 
> 这是一个图。蓝色点表示输入数据。橙色点表示一个值。
> 
> ![无标题](https://private-user-images.githubusercontent.com/666402/377554735-46069678-7172-45fb-9fc4-cf9c854e4b8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMjE1NzksIm5iZiI6MTcyOTIyMTI3OSwicGF0aCI6Ii82NjY0MDIvMzc3NTU0NzM1LTQ2MDY5Njc4LTcxNzItNDVmYi05ZmM0LWNmOWM4NTRlNGI4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQwMzE0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjM3ZDljYjg1MzM0NjBhMjdlYjQ1MWNmZmIwZjNhZTY1MDllMzQxZDAyNmNiNTljMjhkYzM1NWFjY2ZkZmY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.H5jyUQa9_KE5pailOLwjVG_NAZ816SBHP1UZxuyewTM)

Thank you for your help, it solved my problem perfectly.
