### ISSUE TITLE
QUERY: support for RISC-V?

### ISSUE THREAD

**Issue by JocelynPanPan** [scipy/scipy#21732]
Can scipy be installed and used normally on RISC-V architecture?

**Comment by lucascolley** [comment]
There are no official binaries for RISC-V, but if I'm not mistaken there are linux distros who package SciPy for RISC-V

**Comment by rgommers** [comment]
As far as I know SciPy builds fine from source on RISC-V. https://wiki.debian.org/RISC-V may be the place to look at for more details.

As the question is answered, I'll close the issue. Please feel free to continue the conversation of course @JocelynPanPan, or open a new issue if you run into bugs, failing tests or other problems.
