### ISSUE TITLE
DEP: remove `special.btdtr` and `special.btdtri`

### ISSUE THREAD

**Issue by dschmitz89** [scipy/scipy#21759]
### Describe your issue.

Both functions have been announced to be removed in 1.14:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.btdtri.html
https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.btdtr.html

These were originally deprecated in https://github.com/scipy/scipy/pull/17697/commits/40ebe8dac578e03e5ccfd466a9ed4a205496d79d from #17697

**Comment by IamPhytan** [comment]
Hello,

I'm interested in working on this issue. Does it simply require to remove all references to `special.btdr` and `special.btdtri`?

If yes, I will remove the references to these functions that were deprecated in 40ebe8d.

**Comment by dschmitz89** [comment]
@IamPhytan : thanks for your interest to contribute.Yes, essentially it boils down to removing all references to these functions and all tests of them. You will find references in many places as `special` has Cython and Python wrappers for these functions. Looking forward to your PR :).
