### ISSUE TITLE
ENH: interpolation functions: provide an argument to set "admissible neighborhood radius `r`"; when interpolating to location `x`, do not use data from outside `sphere(x, r)`; if no data within this sphere, default to `nan`

### ISSUE THREAD

**Issue by jerabaul29** [scipy/scipy#21755]
### Is your feature request related to a problem? Please describe.

When using interpolate functions, there are some checks about "out of bounds" / "outside of the data", but apart from this, interpolation happens potentially everywhere "inside" the data points.

There are some cases when there may be some "holes" in the data. In such cases, it is a bit scary to interpolate / it may be "unwanted" behavior. For example let us say that a temperature sensor is sampling data roughly every 1 hour, but that there is a 24 hour gap without data. We should probably not interpolate into the "24 hours hole", but rather put NaNs when trying to interpolate "deep" inside the gap.

Would it be relevant / possible to implement some "neighborhood check" / "max neighborhood radius for interpolation" functionality in the interpolation functions? For example saying that interpolation should only take place using data that are withing a `max_abs_dist` distance of the interpolation coordinate target, and that i) data outside of this radius are not used for interpolation, ii) if there are no data within this radius, the interpolated value is nan?

**Comment by ev-br** [comment]
This is not possible in general.

This is way too problem-dependent and interpolator-dependent to implement in `scipy.interpolate`. Your best bet is to formulate exactly what your strategy is and what interpolator you are using, and then you'll need to implement this yourself using general-purpose tools from `scipy.interpolate` (or maybe pandas, if you're imputing missing data).

Some interpolators do support some form of limiting the interpolation window: `NearestNDInterpolator` can use `distance_upper_bound` argument of `cKDTree.query` via `**query_options`; `RBFInterpolator` has the `neighbors` argument; linear interpolators are naturally local. Maybe some of these is useful for your specific problem.

While I'm going to close this feature request, feel free to continue discussing it. The best venues for usage questions though are either Stackoverflow or the Scientific Python discourse forum: both have more eyes than github issues.
