### ISSUE TITLE
BENCH/DEV: Add ``conda-build`` to ``environment.yml`` 

### ISSUE THREAD

**Issue by Kai-Striega** [scipy/scipy#21758]
### Is your feature request related to a problem? Please describe.

I'm unable to use the ``mamba`` command when running the benchmark suite. Please see the warning message in the additional context section.

### Describe the solution you'd like.

Add `conda-build` to the ``environment.yml``  so that we can build the benchmarking suite without warnings

### Describe alternatives you've considered.

Leave it as is, this could lead to issues later on. However, it looks like the tool falls back to conda, so it's not a significant issue at the moment.

### Additional context (e.g. screenshots, GIFs)

```
(scipy-dev) kai@kai-MS-7D32:~/Projects/scipy$ python dev.py bench -t sparse_csgraph_dijkstra
💻  ninja -C /home/kai/Projects/scipy/build -j16
ninja: Entering directory `/home/kai/Projects/scipy/build'
[2/2] Generating scipy/generate-version with a custom command
Build OK
💻  meson install -C build --only-changed --tags runtime,python-runtime,tests,devel
Installing, see meson-install.log...
Installation OK
SciPy from development installed path at: /home/kai/Projects/scipy/build-install/lib/python3.12/site-packages
Running benchmarks for Scipy version 1.15.0.dev0+903.9406182 at /home/kai/Projects/scipy/build-install/lib/python3.12/site-packages/scipy
Couldn't load asv.plugins._mamba_helpers because
No module named 'libmambapy'
· Unknown environment type 'mamba'. Allowed values based on existing plugins are ['existing', 'conda', 'virtualenv']. If you are trying to use `mamba`, you may need to install `conda-build`.
```

**Comment by lucascolley** [comment]
Yeah, I wrote this error message for `asv` :) nice to see it has already been helpful!

Let's fix this as part of gh-21374.
