### ISSUE TITLE
BUG: failure in `scipy/optimize/tests/test_minimize_constrained.py::test_gh11649`

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#21760]
### Describe your issue.

There is a test failure in main causing most CI jobs to fail, e.g. see gh-21744.

### Reproducing Code Example

```python
-
```

### Error message

```shell
================================== FAILURES ===================================
________________________________ test_gh11649 _________________________________

    def test_gh11649():
        bnds = Bounds(lb=[-1, -1], ub=[1, 1], keep_feasible=True)
    
        def assert_inbounds(x):
            assert np.all(x >= bnds.lb)
            assert np.all(x <= bnds.ub)
    
        def obj(x):
            assert_inbounds(x)
            return np.exp(x[0])*(4*x[0]**2 + 2*x[1]**2 + 4*x[0]*x[1] + 2*x[1] + 1)
    
        def nce(x):
            assert_inbounds(x)
            return x[0]**2 + x[1]
    
        def nce_jac(x):
            return np.array([2*x[0], 1])
    
        def nci(x):
            assert_inbounds(x)
            return x[0]*x[1]
    
        x0 = np.array((0.99, -0.99))
        nlcs = [NonlinearConstraint(nci, -10, np.inf),
                NonlinearConstraint(nce, 1, 1, jac=nce_jac)]
    
        res = minimize(fun=obj, x0=x0, method='trust-constr',
                       bounds=bnds, constraints=nlcs)
>       assert res.success
E       AssertionError: assert False
E        +  where False =            message: Constraint violation exceeds 'gtol'\n           success: False\n            status: 4\n              ...enalty: 1.0\n barrier_parameter: 2.048000000000001e-09\n barrier_tolerance: 2.048000000000001e-09\n             niter: 225.success

C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\scipy\optimize\tests\test_minimize_constrained.py:741: AssertionError
```

### SciPy/NumPy/Python version and system information

```shell
main
```

**Comment by andyfaff** [comment]
Sorry, this is down to me. I may have been too trigger happy in merging #21407.

**Comment by andyfaff** [comment]
It had passed these tests previously but the test suite didn't run for some reason after the latest commit.

**Comment by andyfaff** [comment]
I can reproduce the test failure locally.

For that particular test I'm getting the `result.x` as `x : [ 1.000e+00 -9.399e-01]`. At this point the equality constraint function, `nce`, evaluates to `0.0601`. However, the equality constraint is supposed to be equal to 1. This means the constraint violation is 0.9399, which is way outside gtol.

Thus the changes in #21407 are actually picking up a problem.

**Comment by andyfaff** [comment]
With test_gh11649:

- the minimiser says that it's halting on xtol (result.status).
- the equality constraints in the test, as specified by a `NonlinearConstraint`, are nowhere near being met.
-  `res.cg_stop_cond: 2` (Reached the trust-region boundary.)

Given that the equality constraint is nowhere near being met I'd say that we shouldn't be changing the PR that was just merged. The short term fix is probably to change `test_gh11649`, probably by not using the equality constraint.

**Comment by andyfaff** [comment]
I've added a note to #21765 that outlines changed behaviour as a result of #21407. i.e. if the constraint violation is outside `gtol` then the `result.success` will be False. Previously it could've been True. I can see this catching some people by surprise.
