### ISSUE TITLE
QUERY: `optimize.isotonic_regression`: cannot replicate results in Rust or Python

### ISSUE THREAD

**Issue by abstractqqq** [scipy/scipy#21817]
### Describe your issue.

Hi, I am learning about Isotonic regression and PAVA, and I tried to implement the algorithms in Python and Rust, referencing the implementation in Scipy.

The Python impl is almost an identical line-by-line translation of the C++ PAVA code and I cannot see why there is a difference. 

This is the Python impl is posted below. 

With input 
```
ar = np.array([1.5, 1.0, 4.0, 6.0, 5.7, 5.0, 7.8, 9.0, 7.5, 9.5, 9.0])
isotonic_regression(ar)
# Output 
# array([1.25 , 1.25 , 4.   , 5.425, 5.425, 5.425, 7.8  , 8.25 , 8.25 ,  9.25 , 9.25 ])
```
But scipy v1.14 always returns 
```
array([1.25      , 1.25      , 4.        , 5.56666667, 5.56666667,
           5.56666667, 7.8       , 8.25      , 8.25      , 9.25      ,
           9.25      ])
```

I am suspecting that the code (1.14) was shipped with a different c++ compilation than what is on github rn, although I don't have proof at this moment.

### Reproducing Code Example

```python
# Pure Python re-impl of isotonic regression in PAVA
import numpy as np
import numpy.typing as npt

def pava(x: np.ndarray, w: np.ndarray, r: np.ndarray):

    n = len(x)

    r[0] = 0
    r[1] = 1
    b = 0
    xb_prev = x[b]
    wb_prev = w[b]
    for i in range(1, n):
        b += 1
        xb = x[i]
        wb = w[i]
        sb = 0
        if (xb_prev >= xb):
            b -= 1 
            sb = wb_prev * xb_prev + wb * xb
            wb += wb_prev
            xb = sb / wb
            while (i < n - 1 and xb >= x[i + 1]):
                i += 1
                sb += w[i] * x[i]
                wb += w[i]
                xb = sb / wb
            
            while (b > 0 and x[b - 1] >= xb):
                b -= 1
                sb += w[b] * x[b]
                wb += w[b]
                xb = sb / wb
            
        
        x[b] = xb_prev = xb
        w[b] = wb_prev = wb
        r[b + 1] = i + 1
    
    f = n - 1
    for k in range(b, -1, -1):
        t = r[k]
        xk = x[k]
        for i in range(f, t-1, -1):
            x[i] = xk
        
        f = t - 1
    

def isotonic_regression(
    y: npt.ArrayLike,
    *,
    weights: npt.ArrayLike | None = None,
):

    yarr = np.atleast_1d(y)  # Check yarr.ndim == 1 is implicit (pybind11) in pava.
    order = slice(None) # if increasing else slice(None, None, -1)
    x = np.array(yarr[order], order="C", dtype=np.float64, copy=True)
    if weights is None:
        wx = np.ones_like(yarr, dtype=np.float64)
    else:
        warr = np.atleast_1d(weights)
        if not (yarr.ndim == warr.ndim == 1 and yarr.shape[0] == warr.shape[0]):
            raise ValueError(
                "Input arrays y and w must have one dimension of equal length."
            )
        if np.any(warr <= 0):
            raise ValueError("Weights w must be strictly positive.")

        wx = np.array(warr[order], order="C", dtype=np.float64, copy=True)
    n = x.shape[0]
    r = np.full(shape=n + 1, fill_value=-1, dtype=np.intp)
    pava(x, wx, r) # The Python impl is in place 


    return x

```
```


### Error message

```shell
No error message. But results from a line-by-line translation don't agree with current Scipy Output.
```

### SciPy/NumPy/Python version and system information

```shell
1.14.1 1.26.4 sys.version_info(major=3, minor=12, micro=7, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64
    pc file directory: /project
    version: 0.3.27.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.12.4/lib/python3.12/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=64
    pc file directory: /project
    version: 0.3.27.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
...
Python Information:
  path: /opt/python/cp312-cp312/bin/python
  version: '3.12'
```

**Comment by ev-br** [comment]
cc @lorentzenchr

**Comment by WarrenWeckesser** [comment]
You can check the values of the objective function for your solution and for the SciPy solution.  Apparently there is a bug somewhere in your code, because the SciPy solution gives a smaller value.

```
In [10]: ar
Out[10]: array([1.5, 1. , 4. , 6. , 5.7, 5. , 7.8, 9. , 7.5, 9.5, 9. ])

In [11]: ir = isotonic_regression(ar)

In [12]: ir.x
Out[12]: 
array([1.25      , 1.25      , 4.        , 5.56666667, 5.56666667,
       5.56666667, 7.8       , 8.25      , 8.25      , 9.25      ,
       9.25      ])
```

Compute the objective function (i.e. the sum of the squared residuals):

```
In [13]: sum((ir.x - ar)**2)
Out[13]: 1.9016666666666668
```
`v` holds your solution.  The objective function associated with your solution is larger than that of the SciPy solution:
```
In [14]: v = np.array([1.25 , 1.25 , 4.   , 5.425, 5.425, 5.425, 7.8  , 8.25 , 8.25 ,  9.25 , 9.25 ])

In [15]: sum((v - ar)**2)
Out[15]: 1.9618750000000003
```

I have also run the isotonic regression for `ar` with [an implementation that is independent of SciPy](https://github.com/WarrenWeckesser/experiments/tree/main/python/scipy/isotonic-regression), and the result agrees with the SciPy solution.

**Comment by abstractqqq** [comment]
> You can check the values of the objective function for your solution and for the SciPy solution. Apparently there is a bug somewhere in your code, because the SciPy solution gives a smaller value.
> 
> ```
> In [9]: from scipy.optimize import isotonic_regression
> 
> In [10]: ar
> Out[10]: array([1.5, 1. , 4. , 6. , 5.7, 5. , 7.8, 9. , 7.5, 9.5, 9. ])
> 
> In [11]: ir = isotonic_regression(ar)
> 
> In [12]: ir.x
> Out[12]: 
> array([1.25      , 1.25      , 4.        , 5.56666667, 5.56666667,
>        5.56666667, 7.8       , 8.25      , 8.25      , 9.25      ,
>        9.25      ])
> ```
> 
> Compute the objective function (i.e. the sum of the squared residuals):
> 
> ```
> In [13]: sum((ir.x - ar)**2)
> Out[13]: 1.9016666666666668
> ```
> 
> `v` holds your solution. The objective function associated with your solution is larger than that of the SciPy solution:
> 
> ```
> In [14]: v = np.array([1.25 , 1.25 , 4.   , 5.425, 5.425, 5.425, 7.8  , 8.25 , 8.25 ,  9.25 , 9.25 ])
> 
> In [15]: sum((v - ar)**2)
> Out[15]: 1.9618750000000003
> ```
> 
> I have also run the isotonic regression for `ar` with [an implementation that is independent of SciPy](https://github.com/WarrenWeckesser/experiments/tree/main/python/scipy/isotonic-regression), and the result agrees with the SciPy solution.

Ok the objective function test is very insightful... I guess I will spend more time debugging the code.. It is strange because it should be a line-by-line translation of the C++ code..

Anyways. Thanks a look

**Comment by abstractqqq** [comment]
@WarrenWeckesser 

After some long hours of debugging... turns out c++ has some really weird behavior when you increment the i inside a for loop, and this behavior, whether intended or not, plays very well with PAVA in this case

```c++
// prints only 2 and 4
  for (intptr_t i = 1; i < 5; ++i) {
      i = i + 1;
      std::cout << i << "\n";
  }
``` 

Compare with Python (Rust behaves the same as Python)

```python
# 2, 3, 4, 5
for i in range(1, 5):
    i = i + 1
    print(i)

```
