### ISSUE TITLE
RFC: special: Behavior of `gamma` function and related functions at poles.

### ISSUE THREAD

**Issue by steppi** [scipy/scipy#21810]
In https://github.com/scipy/scipy/issues/19071 it came to light the the `gamma` function and related functions in `scipy.special` such as `gammasgn` and `gammaln` have unusual behavior at the poles. Take for instance `gamma`, we find that it equals positive infinity at each of the poles.

```Python
gamma(np.float64("+0"))
# np.float64(inf)

gamma(np.float64("-0"))
# np.float64(inf)

gamma(-1)
# np.float64(inf)

gamma(-2)
# np.float64(inf)

gamma(-3)
# np.float64(inf)
```

despite the sign of infinity at each pole depending on the direction in which `x` approaches the pole.

We also mysteriously have:

```Python
gamma(-np.inf)
# np.float64(-inf)
```

According to the the [C99 standard](https://en.cppreference.com/w/c/numeric/math/tgamma) the proper behavior for `tgamma` at the poles and extreme points is:

1. If the argument is $\pm 0$, $\pm \infty$ is returned.
2. If the argument is a negative integer, NaN is returned.
3. If the argument is $-\infty$, NaN is returned.
4. If the argument is $+\infty$, $+\infty$ is returned
5. If the argument is NaN, NaN is returned.

In SciPy, only the last two cases entries in this bullet list are handled correctly. The implementation we use for the gamma function comes from `cephes`, but I've found that the [original cephes code](https://github.com/jeremybarnes/cephes/blob/60f27df395b8322c2da22c83751a2366b82d50d1/cprob/gamma.c#L350-L358) gets these cases right, and a decision was made to change how `gamma` behaves very early on in SciPy's history, back on March 16th 2002. See [here](https://github.com/scipy/scipy/commit/dbb3d6a4bf4bee31634e9b8747cb0bd6323f6288#diff-99531ff676fcd8b132f9ea5554ebb991d9abaf3748ef6394cb5428347cb64bfc
) if you're curious.

It's hard to say why the behavior of `gamma` at the poles was changed, one speculation I've had is that it makes it so things work out if you have a gamma ratio like `gamma(a)/gamma(b)` and there ends up being a pole in the denominator. Instead one should just do `gamma(a)*rgamma(b)` though. In any case, I think this is a bug. Recently I saw that @h-vetinari had to go through an annoying workaround for this bug in #21801 and just feel like enough is enough. Perhaps some users may have code involving `gamma` ratios which will break, but I think things will be fine if we just add a note to the docstring describing what the old and new behavior is, and recommending the use of `rgamma`. 

I propose we fix this to have `gamma` follow the C99 standard (and also `gammaln` and `gammasgn`) before we branch for 1.15 so @h-vetinari doesn't have to define the following just to get sane behavior from the `gamma` function:

```Python
    def _gamma_no_inf(vals):
        res = gamma(vals)
        # replace infinities coming from gamma function with nan, see #19071;
        # gamma only returns inf for real inputs, so no fix needed for complex inputs
        if isinstance(res, np.ndarray):
            if not _is_subdtype(vals.dtype, "c"):
                # we _do_ keep infinity where input itself was +∞
                keep_as_inf = np.isinf(vals) & (vals > 0)
                res[np.isinf(res) & ~keep_as_inf] = np.nan
        elif np.isinf(res) and not (np.isinf(vals) and (vals > 0)):
            res = np.float64("nan")
        return res
```

**Comment by h-vetinari** [comment]
Thanks for opening this RFC! 🙏 
As I had argued in #19071 some time ago, I think this is clearly a desirable change!
