### ISSUE TITLE
BLD: accelerate detection with GNU toolchain on ARM mac

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#21829]
While investigating gh-21826 on MacOS ARM, I noticed the following build incantation with GNU compiler toolchain version `14.1.0` (from `homebrew`) fails to detect accelerate:

`CC=gcc-14 CXX=g++-14 python dev.py build -j 16 --with-accelerate`

 while forcing use of AppleClang restores this ability to build with accelerate:

`CC=clang CXX=clang++ python dev.py build -j 16 --with-accelerate`

The error message for the former, in an otherwise identical environment and `git clean -xfd` in between build trials is:

```
<snip>
Run-time dependency accelerate found: NO (tried pkgconfig and framework)

scipy/meson.build:222:9: ERROR: Dependency "accelerate" not found, tried pkgconfig and framework

A full log can be found at /Users/treddy/github_projects/scipy/build/meson-logs/meson-log.txt
Meson build setup failed!
```

Let me check on this...

**Comment by tylerjereddy** [comment]
Dissected to `meson` source below, indicating that Apple frameworks can only be found/used with the system compiler. If that's a hard limitation, it is a bit of a weird one at first glance (need platform-native compiler to link platform-native linalg backend?), and the error message is not particularly informative. If there's really nothing we can do about this, perhaps either asking for a better upstream error message, or intercepting the compiler/`accelerate` mismatch on our end to error out more clearly might be useful.

https://github.com/mesonbuild/meson/blob/f0851c9e4b1760c552f7921e6b6a379b006ba014/mesonbuild/dependencies/framework.py#L29-L34

```python
            except MesonException as e:
                if 'non-clang' in str(e):
                    # Apple frameworks can only be found (and used) with the
                    # system compiler. It is not available so bail immediately.
                    self.is_found = False
                    return
```

**Comment by rgommers** [comment]
As noted in https://github.com/scipy/scipy/issues/21826#issuecomment-2463704568, a relevant issue is https://github.com/mesonbuild/meson/issues/13608. I'm sure this can be made to work in Meson, but that issue is already very long and not all that clear. 

I'd say that we shouldn't error out ourselves here, but we can add a warning message if we see that `blas_name` is `accelerate` and a user is building with a non-`clang` compiler, to point to that upstream issue.
