### ISSUE TITLE
BLD: threads.h with MacOS 14.x ARM + gcc 14.2.0

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#21830]
Another thing observed while investigating gh-21826--if building with `gcc 14.2.0` toolchain (from `homebrew`) on MacOS ARM  (OS version `14.7`, alongside OpenBLAS), I see an issue with `fatal error: threads.h: No such file or directory`.

Incantation on latest SciPy `main`: `CC=gcc-14 CXX=g++-14 python dev.py build -j 16`

Build error:

```
<snip>
[129/1274] Generating scipy/linalg/flapack_module with a custom command
[130/1274] Compiling C object scipy/linalg/_flapack.cpython-312-darwin.so.p/meson-generated_..__flapackmodule.c.o
FAILED: scipy/linalg/_flapack.cpython-312-darwin.so.p/meson-generated_..__flapackmodule.c.o 
gcc-14 -Iscipy/linalg/_flapack.cpython-312-darwin.so.p -Iscipy/linalg -I../scipy/linalg -I../../../python_venvs/py_312_scipy_dev/lib/python3.12/site-packages/numpy/_core/include -I../../../python_venvs/py_312_scipy_dev/lib/python3.12/site-packages/numpy/f2py/src -I/opt/homebrew/Cellar/openblas/0.3.28/include -I/Library/Frameworks/Python.framework/Versions/3.12/include/python3.12 -fvisibility=hidden -fdiagnostics-color=always -Wall -Winvalid-pch -std=c17 -O2 -g -Wno-unused-but-set-variable -Wno-unused-function -Wno-conversion -Wno-misleading-indentation -Wno-empty-body -MD -MQ scipy/linalg/_flapack.cpython-312-darwin.so.p/meson-generated_..__flapackmodule.c.o -MF scipy/linalg/_flapack.cpython-312-darwin.so.p/meson-generated_..__flapackmodule.c.o.d -o scipy/linalg/_flapack.cpython-312-darwin.so.p/meson-generated_..__flapackmodule.c.o -c scipy/linalg/_flapackmodule.c
scipy/linalg/_flapackmodule.c:90:10: fatal error: threads.h: No such file or directory
   90 | #include <threads.h>
      |          ^~~~~~~~~~~
compilation terminated.

<snip>
```

There is a complicated NumPy issue about this kind of thing here for example: https://github.com/numpy/numpy/issues/24761

**Comment by tylerjereddy** [comment]
Also relevant is that config stage shows: `Run-time dependency threads found: YES`

**Comment by tylerjereddy** [comment]
The `f2py` patch below restores a successful SciPy build for me locally. This may be consistent with [GNU report](https://www.gnu.org/software/gnulib/manual/html_node/threads_002eh.html#:~:text=This%20header%20file%20is%20missing,%2C%20MSVC%2014%2C%20Android%209.0.) indicating

> This header file is missing on many platforms: glibc 2.27, **macOS 14**, FreeBSD 9.3, NetBSD 8.0, OpenBSD 6.7, Minix 3.1.8, AIX 7.1, HP-UX 11.31, Solaris 11.3, Cygwin 2.2.x, mingw, MSVC 14, Android 9.0.

(emphasis on MacOS 14 I suppose)


```diff
--- a/numpy/f2py/cfuncs.py
+++ b/numpy/f2py/cfuncs.py
@@ -558,7 +558,8 @@ def errmess(s: str) -> None:
       && (__STDC_VERSION__ >= 201112L) \\
       && !defined(__STDC_NO_THREADS__) \\
       && (!defined(__GLIBC__) || __GLIBC__ > 2 || (__GLIBC__ == 2 && __GLIBC_MINOR__ > 12)) \\
-      && !defined(NPY_OS_OPENBSD) && !defined(NPY_OS_HAIKU)
+      && !defined(NPY_OS_OPENBSD) && !defined(NPY_OS_HAIKU) \\
+      && !(defined(__APPLE__) && (__MAC_OS_X_VERSION_MAX_ALLOWED >= 140000 && __MAC_OS_X_VERSION_MAX_ALLOWED < 150000))
 /* __STDC_NO_THREADS__ was first defined in a maintenance release of glibc 2.12,
    see https://lists.gnu.org/archive/html/commit-hurd/2012-07/msg00180.html,
    so `!defined(__STDC_NO_THREADS__)` may give false positive for the existence
```

**Comment by tylerjereddy** [comment]
I'll report upstream in NumPy for consideration--decent chance I'm not quite right here, but at least get it rolling.

**Comment by tylerjereddy** [comment]
Note that while the build is restored with that patch, SciPy doesn't actually pass the testsuite in that scenario. There are some hard crashes locally.. not going there tonight though.

**Comment by rgommers** [comment]
gh-21860 should fix this, also for older NumPy versions (so we don't need to wait for https://github.com/numpy/numpy/pull/27729).
