### ISSUE TITLE
ENH: bring back nnls.f in v1.15.0

### ISSUE THREAD

**Issue by jd-edp** [scipy/scipy#21852]
### Is your feature request related to a problem? Please describe.

I tested the new nnls version written in cython and must say its still slower than the fortran version and is quiet cpu heavy. If you want to split up multiple trainings in many processes you get a complete chaos and nothing is getting finished. I don't know why the nnls.f version is still the best in these things, so it would be easy to bring back the fortran version until there is a new equal version of it.

### Describe the solution you'd like.

bring back nnls.f or a equal fast and low consuming cpu version of it, so I don't have to stick to v1.11.4

**Comment by j-bowhay** [comment]
Cc @ilayn

**Comment by lucascolley** [comment]
could you provide some code and benchmarks which display the slow/heavy behaviour @jd-edp ?

**Comment by h-vetinari** [comment]
> I tested the new nnls version written in cython 

Presumably that refers to #21021, which addressed the very similar #20984.

Can you provide more quantifiable performance metrics? Or better: a reproducer of some code that is fast on 1.11.4 and (still) slow on main.

**Comment by ilayn** [comment]
I checked similar benchmarks on my machine at the time and things were very close to each other. If you are seeing big differences, then might be a cyton thing. 

Or there is a bug remaining that makes the loop spin more.

Either way the code does the same steps so it's probably the second but we need a clean reproducer.

**Comment by ilayn** [comment]
Forgot to mention that this is going to be ported to C anyways since SLSQP is also using it. So it will probably resolve itself in terms of remaining performance differences.

**Comment by maindlt** [comment]
Just in case it is still of interest: we have been using nnls in our galaxy dynamics code for a while and got the following solve times by release:
1.11.4 (Fortran): 1h36m
1.14.1 (Python): 7h02m
1.15.3 (Cython): 7h08m (strange that it's not faster...)
1.16.2 (C): 1h34m

So we are very happy with the new, fast C implementation, keeping the Fortran version available would have saved us much headache after 1.12 came out, though ;-)

**Comment by ilayn** [comment]
Apologies for the screw up. It took quite some time to fix it indeed.

**Comment by jd-edp** [comment]
Yeah i'm also running on the latest version of scipy and its as fast as fortran was. Thank you :)

**Comment by maindlt** [comment]
> Apologies for the screw up. It took quite some time to fix it indeed.

No problem, we figured it out at the end. I think SciPy is terrific package - many thanks for the great job you are doing!!
