### ISSUE TITLE
BUG: `scipy.datasets` failing with Error 403 for readthedocs builds

### ISSUE THREAD

**Issue by byrdie** [scipy/scipy#21879]
### Describe your issue.

I've been using `scipy.datasets` for documentation examples for a while now, and just this morning they started failing during builds on readthedocs.org.

I can't tell if this is a scipy problem or a readthedocs problem yet, although it seems consistent with throttling due to abusive crawlers.

Here is a link to a failing build
https://readthedocs.org/projects/named-arrays/builds/26260565/

### Reproducing Code Example

```python
import scipy.datasets

img = scipy.datasets.ascent()
```

### Error message

```shell
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Cell In[1], line 5
      2 import scipy.datasets
      3 import named_arrays as na
----> 5 img = na.ScalarArray(scipy.datasets.ascent(), axes=("y", "x"))
      7 img_filtered = na.ndfilters.mean_filter(img, size=dict(x=21, y=21))
      9 fig, axs = plt.subplots(
     10     ncols=2,
     11     sharex=True,
     12     sharey=True,
     13     constrained_layout=True,
     14 )

File ~/checkouts/readthedocs.org/user_builds/named-arrays/envs/99/lib/python3.12/site-packages/scipy/datasets/_fetchers.py:71, in ascent()
     66 import pickle
     68 # The file will be downloaded automatically the first time this is run,
     69 # returning the path to the downloaded file. Afterwards, Pooch finds
     70 # it in the local cache and doesn't repeat the download.
---> 71 fname = fetch_data("ascent.dat")
     72 # Now we just need to load it with our standard Python tools.
     73 with open(fname, 'rb') as f:

File ~/checkouts/readthedocs.org/user_builds/named-arrays/envs/99/lib/python3.12/site-packages/scipy/datasets/_fetchers.py:31, in fetch_data(dataset_name, data_fetcher)       
     27     raise ImportError("Missing optional dependency 'pooch' required "
     28                       "for scipy.datasets module. Please use pip or "
     29                       "conda to install 'pooch'.")
     30 # The "fetch" method returns the full path to the downloaded data file.
---> 31 return data_fetcher.fetch(dataset_name)

File ~/checkouts/readthedocs.org/user_builds/named-arrays/envs/99/lib/python3.12/site-packages/pooch/core.py:589, in Pooch.fetch(self, fname, processor, downloader, progressbar)
    586     if downloader is None:
    587         downloader = choose_downloader(url, progressbar=progressbar)
--> 589     stream_download(
    590         url,
    591         full_path,
    592         known_hash,
    593         downloader,
    594         pooch=self,
    595         retry_if_failed=self.retry_if_failed,
    596     )
    598 if processor is not None:
    599     return processor(str(full_path), action, self)

File ~/checkouts/readthedocs.org/user_builds/named-arrays/envs/99/lib/python3.12/site-packages/pooch/core.py:807, in stream_download(url, fname, known_hash, downloader, pooch, retry_if_failed)
    803 try:
    804     # Stream the file to a temporary so that we can safely check its
    805     # hash before overwriting the original.
    806     with temporary_file(path=str(fname.parent)) as tmp:
--> 807         downloader(url, tmp, pooch)
    808         hash_matches(tmp, known_hash, strict=True, source=str(fname.name))
    809         shutil.move(tmp, str(fname))

File ~/checkouts/readthedocs.org/user_builds/named-arrays/envs/99/lib/python3.12/site-packages/pooch/downloaders.py:221, in HTTPDownloader.__call__(self, url, output_file, pooch, check_only)
    219 try:
    220     response = requests.get(url, timeout=timeout, **kwargs)
--> 221     response.raise_for_status()
    222     content = response.iter_content(chunk_size=self.chunk_size)
    223     total = int(response.headers.get("content-length", 0))

File ~/checkouts/readthedocs.org/user_builds/named-arrays/envs/99/lib/python3.12/site-packages/requests/models.py:1024, in Response.raise_for_status(self)
   1019     http_error_msg = (
   1020         f"{self.status_code} Server Error: {reason} for url: {self.url}"
   1021     )
   1023 if http_error_msg:
-> 1024     raise HTTPError(http_error_msg, response=self)

HTTPError: 403 Client Error: Forbidden for url: https://raw.githubusercontent.com/scipy/dataset-ascent/main/ascent.dat
```

### SciPy/NumPy/Python version and system information

```shell
numpy-1.26.4
scipy-1.14.1
pooch-1.8.2
```

**Comment by AnirudhDagar** [comment]
Hi @byrdie, thanks for the issue and detailed explanation. I just tried to reproduce the issue, but it works fine on my end with all the datasets in `scipy.datasets` using the code you provided above. I'm not sure if it was just a GitHub issue or something else, maybe you could try again, and report it back if the issue still persists? Thanks!

**Comment by byrdie** [comment]
Hi @AnirudhDagar, thanks for taking the time to investigate this issue. 

Sorry, I should've clarified more, the code above works fine on my machine and on Google Colab. It only fails on readthedocs.org (after working fine for months), and I'm trying to figure out what's changed.

I just ran my documentation build again and it's still failing with the same problem.

I'm wondering if GitHub has blacklisted readthedocs.org or something like that?

**Comment by lucascolley** [comment]
could you try a similar download from a different package to SciPy to check whether the problem is just with SciPy?

**Comment by byrdie** [comment]
@lucascolley, that sounds like a good idea. Do you know of a file like this? Otherwise I'll hunt around to try and find a good candidate.

**Comment by AnirudhDagar** [comment]
@byrdie it's probably rate limit issues. I don't know why it started happening suddenly, but I also see this locally in one of my other projects which was downloading a dataset from github.

**Comment by byrdie** [comment]
@AnirudhDagar, oh that's interesting, so this is sounding more like a GitHub problem than anything.

Confusingly, I ran the curl test you suggested on readthedocs and it worked, so maybe there's something about the pooch user agent that github doesn't like?
https://named-arrays--99.org.readthedocs.build/en/99/_autosummary/named_arrays.ndfilters.variance_filter.html

**Comment by AnirudhDagar** [comment]
Yes, going by the discussions in other threads (which also started around the time this issue was opened)

From https://github.com/readthedocs/readthedocs.org/issues/11763#issuecomment-2477034172
> Guessing this is GH getting hammered by AI bots, and restricting requests without agents, like the rest of us. 

I'll send a PR to add a downloader with user agent defined in `pooch`, which should fix the issue.
