### ISSUE TITLE
MAINT: smoke-docs failure on main

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#21894]
@ev-br in main we are seeing an error from scipy-doctest:

```
==================================== ERRORS ====================================
_ ERROR collecting build-install/lib/python3.11/site-packages/scipy/_lib/array_api_extra/_typing.py _
/home/circleci/.pyenv/versions/3.11.10/lib/python3.11/site-packages/scipy_doctest/plugin.py:238: in collect
    for test in find_doctests(module, strategy=strategy, name=module.__name__, config=dt_config):
        module     = <module 'scipy._lib.array_api_extra._typing' from '/home/circleci/repo/build-install/lib/python3.11/site-packages/scipy/_lib/array_api_extra/_typing.py'>
        optionflags = 44
        runner     = <scipy_doctest.plugin._get_runner.<locals>.PytestDTRunner object at 0x7f4c7f7f3950>
        self       = <DTModule _typing.py>
        strategy   = 'api'
/home/circleci/.pyenv/versions/3.11.10/lib/python3.11/site-packages/scipy_doctest/frontend.py:80: in find_doctests
    raise ValueError(mesg)
E   ValueError: Missing item!
E   Traceback (most recent call last):
E     File "/home/circleci/.pyenv/versions/3.11.10/lib/python3.11/site-packages/scipy_doctest/util.py", line 245, in get_public_objects
E       obj = getattr(module, name)
E             ^^^^^^^^^^^^^^^^^^^^^
E   AttributeError: module 'scipy._lib.array_api_extra._typing' has no attribute 'Array'
```

The offending file is:

```python
from __future__ import annotations

from types import ModuleType
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    Array = Any  # To be changed to a Protocol later (see array-api#589)

__all__ = ["Array", "ModuleType"]
```

https://github.com/data-apis/array-api-extra/blob/b83ba618f2895fd674da5b464bb8c74def12f393/src/array_api_extra/_typing.py#L1

Where is the bug? Is my use of `if TYPE_CHECKING` and `__all__` valid, or should it be done differently?

**Comment by jorenham** [comment]
If it's in `__all__` then you probably want to remove the `if TYPE_CHECKING`, as that makes it unavailable at runtime.

**Comment by lucascolley** [comment]
Okay. To clarify, this is in a private module. I added it to `__all__` under the impression that that is the convention for "this is meant to be imported by other modules". The only import from another module is also guarded by `if TYPE_CHECKING`.

So just removing the `if TYPE_CHECKING` is more conventional than removing it from `__all__`?

**Comment by jorenham** [comment]
Judging from the `getattr(module, name)` in the error message, it looks as if it's being used at runtime 🤷🏻

**Comment by lucascolley** [comment]
> Judging from the getattr(module, name) in the error message, it looks as if it's being used at runtime 🤷🏻

In which case this may be seen as a bug in scipy-doctest, which is walking around modules looking for docstrings?

**Comment by ev-br** [comment]
Agreed on not putting things into `__all__` if they are not in `dir(...)`.

`"Array"` is in `_typing.__all__`  but it's not importable and is not available from `dir(_typing)`:

```
$ python dev.py ipython
💻  ninja -C /home/br/repos/scipy/scipy/build -j4
ninja: Entering directory `/home/br/repos/scipy/scipy/build'
[1/1] Generating scipy/generate-version with a custom command
Build OK
💻  meson install -C build --only-changed --tags runtime,python-runtime,tests,devel
Installing, see meson-install.log...
Installation OK
Python 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) [GCC 12.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.26.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from scipy._lib.array_api_extra._typing import Array
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 from scipy._lib.array_api_extra._typing import Array

ImportError: cannot import name 'Array' from 'scipy._lib.array_api_extra._typing' (/home/br/repos/scipy/scipy/build-install/lib/python3.12/site-packages/scipy/_lib/array_api_extra/_typing.py)

In [2]: from scipy._lib.array_api_extra import _typing

In [3]: dir(_typing)
Out[3]: 
['Any',
 'ModuleType',
 'TYPE_CHECKING',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'annotations']

In [4]: _typing.__all__
Out[4]: ['Array', 'ModuleType']

```

`scipy_doctest` is not expecting this, and FWIW I don't believe it should. If `__all__` is defined at all, it should not advertise things which are not importable.

**Comment by lucascolley** [comment]
> > added it to all under the impression that that is the convention for "this is meant to be imported by other modules".
> ... but it cannot be imported by other modules.

Perhaps the answer is this?

```python
if TYPE_CHECKING:
    __all__ += 'Array'
```

**Comment by ev-br** [comment]
Yes, I think this is precisely the right answer! This way, `__all__` lists the actual public API of the module for both `TYPE_CHECKING` being True and False.

**Comment by lucascolley** [comment]
thanks all
