### ISSUE TITLE
CI: failure for "Oldest GCC ..." Linux CI job (related to pre-release NumPy)

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#21957]
I noticed the CI failure while reviewing Ralf's PR at gh-21943. It is reproducible locally on Linux with gcc 9.5 and the new NumPy pre-release, `2.2.0rc1`. This CI job builds with the latest NumPy pre-release and then switches to `1.23.5` at test time after building.

Reproduced locally via a build command similar to the CI job in question: `python -m build --wheel --no-isolation -Ccompile-args=-j32`

Failure can be reproduced on `main`, so not related to Ralf's branch:

```
<snip>
Program pythran found: YES 0.17.0 0.17.0 (/home/treddy/python_venvs/py_310_scipy/bin/pythran)
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency xsimd found: NO (tried pkgconfig and cmake)
Run-time dependency threads found: YES

../scipy/meson.build:50:17: ERROR: Command `/home/treddy/python_venvs/py_310_scipy/bin/python -c 'import os
os.chdir(os.path.join("..", "tools"))
import numpy as np
try:
  incdir = os.path.relpath(np.get_include())
except Exception:
  incdir = np.get_include()
print(incdir)
  '` failed with status 1.

A full log can be found at /home/treddy/github_projects/scipy/.mesonpy-dl97fuyc/meson-logs/meson-log.txt

ERROR Backend subprocess exited when trying to invoke build_wheel
```

**Comment by tylerjereddy** [comment]
The version of the GNU compiler/toolchain is irrelevant to reproduction of the issue.

**Comment by tylerjereddy** [comment]
Reported upstream for clarification.

**Comment by tylerjereddy** [comment]
Looks like the explanation is incredibly simple after all, `import numpy as np` fails when `PYTHONOPTIMIZE=2` for the latest NumPy pre-release... I thought I was just getting tired or something...

**Comment by lucascolley** [comment]
> the failing SciPy job needs a local fix though, since it currently pulls in numpy 2.2.0rc1

what is the fix needed here @rgommers ?
