### ISSUE TITLE
DOC: `stats.goodness_of_fit`: improve examples

### ISSUE THREAD

**Issue by Gooda11** [scipy/scipy#21952]
### Issue with current documentation:

   Hello, I feel confused about the description about stats.goodness.fit. Why I got totally different result when using the two commands: 
1. stats.goodness_of_fit(stats.lognorm, data, fit_params= {'loc':0},statistic='ad', n_mc_samples=9999,)
 2.stats.goodness_of_fit(stats.lognorm, data, known_params= {'loc':0},statistic='ad', n_mc_samples=9999,) 

### Idea or request for content:

Maybe more detailed text and examples about fit_params and known_params in goodness_of_fit?

**Comment by mdhaber** [comment]
The distinction is documented pretty succinctly: use `known_params` to specify parameters of the distribution that are *known*; use `fit_params` to specify parameters of the distribution that you *fit* to empirical data.

For example, suppose you are interested in the goodness of fit of a normal distribution.
- Based on knowledge of your problem, you are only interested in considering the family of normal distributions with zero mean. This would be provided via `known_params={'loc': 0}`.
- You also have fit the scale parameter to your data by taking the standard deviation `sigma`. This would be provided via `fit_params={'scale': sigma}`.

What about the existing documentation is causing the confusion?

**Comment by Gooda11** [comment]
Dear, Thanks a lot for your reply and help! But I am confused why I got different results by setting loc as a known parameter of 0, or by setting loc as a fitting parameter of 0. The derived statistics value is different while loc is 0 in both cases?在 2024年11月26日，16:25，Matt Haberland ***@***.***> 写道：﻿
The distinction is documented pretty succinctly: use known_params to specify parameters of the distribution that are known; use fit_params to specify parameters of the distribution that you fit to empirical data.
For example, suppose you are interested in the goodness of fit of a normal distribution.

Based on knowledge of your problem, you are only interested in considering the family of normal distributions with zero mean. This would be provided via known_params={'loc': 0}.
You also have fit the scale parameter to your data by taking the standard deviation sigma. This would be provided via fit_params={'scale': sigma}.

What about the existing documentation is causing the confusion?

**Comment by rkern** [comment]
As he explained, `loc` is not going to be 0 in both cases. When passed in the `fit_params`, `goodness_of_fit` will refit each sample using the value that you passed as an initial guess, not a fixed value.

**Comment by mdhaber** [comment]
I've amended the answer above. Maybe take another look at the last sentence of the second pair of bullets.

There are two things that "known", "fit", and "guessed" have the potential to change:
- the value of the parameter used when generating resamples.
- the value of the parameter used when calculating the statistic (for the original sample and all resamples).

When a parameter is "known", it is used for both. When a parameter is "fitted" to the data, it is *only* used for generating resamples; the parameter always gets fit to the data before calculating the statistic. When a parameter is "guessed", it used not used directly for either; it is just a guess used when fitting with numerical optimization. 

If you want to get the same statistic using `known_params` and `fit_params`, the known parameter have to be the same as the fitted values:
```python3
import numpy as np
from scipy import stats
rng = np.random.default_rng(833679544785446)
x = rng.standard_normal(size=100)
res_known = stats.goodness_of_fit(stats.norm, x, known_params={'loc': np.mean(x), 'scale': np.std(x, ddof=1)}, random_state=rng, statistic=statistic)
print(res_known.statistic)  # 0.04261248791026049
res_fit = stats.goodness_of_fit(stats.norm, x, fit_params={'loc': np.mean(x)}, random_state=rng, statistic=statistic)
print(res_fit.statistic)  # 0.04261248791026049
```

**Comment by Gooda11** [comment]
Dear，Thank you for your explanation. It is clear now.Best regardsJQ在 2024年11月27日，17:21，Matt Haberland ***@***.***> 写道：﻿
I've amended the answer above. Maybe take another look at the last sentence of the second pair of bullets.
There are two things that "known", "fit", and "guessed" have the potential to change:

the value of the parameter used when generating resamples.
the value of the parameter used when calculating the statistic (for the original sample and all resamples).

When a parameter is "known", it is used for both. When a parameter is "fitted" to the data, it is only used for generating resamples; the parameter always gets fit to the data before calculating the statistic. When a parameter is "guessed", it used not used directly for either; it is just a guess used when fitting with numerical optimization.
If you want to get the same statistic using known_params and fit_params, the known parameter have to be the same as the fitted values:
import numpy as np
from scipy import stats
rng = np.random.default_rng(833679544785446)
x = rng.standard_normal(size=100)
res_known = stats.goodness_of_fit(stats.norm, x, known_params={'loc': np.mean(x), 'scale': np.std(x, ddof=1)}, random_state=rng, statistic=statistic)
print(res_known.statistic)  # 0.04261248791026049
res_fit = stats.goodness_of_fit(stats.norm, x, fit_params={'loc': np.mean(x)}, random_state=rng, statistic=statistic)
print(res_fit.statistic)  # 0.04261248791026049
