### ISSUE TITLE
BUG: dsyrk slower than naive numpy matrix-matrix multiplication on matrices with many columns

### ISSUE THREAD

**Issue by NAThompson** [scipy/scipy#22060]
### Describe your issue.

In computation of $$A = X^TX$$ for matrices $$X$$ with many more rows than columns, we can save a considerable amount of computation by leveraging that $$A$$ is symmetric. For instance, if we intend on passing $$A$$ to numpy's Cholesky decomposition routine, we know that only the lower triangular part will be read, and hence we should only _compute_ that part.

This is what `dsyrk` can achieve-and indeed does achieve in many cases. However, I have found that `dsyrk` is slower than the naive `X.T @ X` beyond a certain number of columns, and in cases where `X.T @ X` succeeds in ~1 minute, I could not find the patience to wait for the computation to finish.

Arguably this may be something related to cache accesses, and therefore not a bug. Alternatively, it may be a performance bug in Accelerate (which is my blas backend). Nonetheless, I figured it would be something the community may wish to be made aware of, and even if the maintainers choose to close it should still show up in search results.

### Reproducing Code Example

```python
#!/usr/bin/env python3

import numpy as np
import time
from scipy.linalg.blas import dsyrk

# Generate a random nxm matrix
np.random.seed(42)
rows = 100000
cols = 6000
X = np.random.rand(rows, cols)
print(f"shape of X: {X.shape}")

start = time.perf_counter()
A1 = X.T @ X
end = time.perf_counter()
print(f"Time to compute X^TX via naive numpy: {end - start} seconds")

start = time.perf_counter()
A2 = dsyrk(alpha=1.0, a=X, trans=1, lower=1)
end = time.perf_counter()
print(f"Time to compute X^TX via dsyrk: {end-start} seconds")

rows = 150000
cols = 6000
X = np.random.rand(rows, cols)
print(f"shape of X: {X.shape}")

start = time.perf_counter()
A1 = X.T @ X
end = time.perf_counter()

print(f"Time to compute X^TX via naive numpy: {end - start} seconds")

start = time.perf_counter()
A2 = dsyrk(alpha=1.0, a=X, trans=1, lower=1)
end = time.perf_counter()
print(f"Time to compute X^TX via dsyrk: {end-start} seconds")

rows = 200000
cols = 6000
X = np.random.rand(rows, cols)
print(f"shape of X: {X.shape}")

start = time.perf_counter()
A1 = X.T @ X
end = time.perf_counter()

print(f"Time to compute X^TX via naive numpy: {end - start} seconds")

start = time.perf_counter()
A2 = dsyrk(alpha=1.0, a=X, trans=1, lower=1)
end = time.perf_counter()
print(f"Time to compute X^TX via dsyrk: {end-start} seconds")
```

### Error message

```shell
shape of X: (100000, 6000)
Time to compute X^TX via naive numpy: 13.960469957994064 seconds
Time to compute X^TX via dsyrk: 9.185443250004028 seconds
shape of X: (150000, 6000)
Time to compute X^TX via naive numpy: 20.89068762500392 seconds
Time to compute X^TX via dsyrk: 43.4743921670015 seconds
shape of X: (200000, 6000)
Time to compute X^TX via naive numpy: 29.375022041000193 seconds
Time to compute X^TX via dsyrk: 109.17302662500151 seconds
```

### SciPy/NumPy/Python version and system information

```shell
Python 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info); scipy.show_config()
1.14.1 1.26.4 sys.version_info(major=3, minor=12, micro=3, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: extraframeworks
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: extraframeworks
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    commands: gfortran
    linker: ld64
    name: gcc
    version: 13.3.0
  pythran:
    include directory: ../../../../../../private/var/folders/hw/1f0gcr8d6kn9ms0_wn0_57qc0000gn/T/pip-build-env-bjescfad/overlay/lib/python3.12/site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  cross-compiled: false
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/hw/1f0gcr8d6kn9ms0_wn0_57qc0000gn/T/cibw-run-oogm4_8g/cp312-macosx_arm64/build/venv/bin/python
  version: '3.12'
```

**Comment by rgommers** [comment]
NumPy's `matmul` also call `syrk`, or `gemm`:

https://github.com/numpy/numpy/blob/c81c44a7762503f3616b238c58bc05acefc238ed/numpy/_core/src/umath/matmul.c.src#L162-L163

So it might be one routine vs. the other there. Or the LP64 vs. ILP64 variant of the routine making a difference (NumPy probably uses ILP64, scipy definitely LP64). There may also be differences in how the linked BLAS was built (e.g., max number of threads).

To understand exactly what is happening, you should probably (a) make sure that both `numpy` and `scipy` are linked against the exact same BLAS library, and (b) find out which of the `numpy.matmul`-internal code paths is taken for these input shapes.

**Comment by ilayn** [comment]
`?syrk` is meant for rank-k updates and not for general matmul ops as the name implies. Beyond a certain number of columns `?gemm` will start to win. This is not a bug but just a shortcoming since you will start to lose locality benefits of rank-k.  

This is why [?symm](https://netlib.org/lapack//explore-html/d0/d16/group__hemm_ga83617b92d007d90eda87d135bf08175b.html) or Intel's [`gemmt`](https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-fortran/2024-1/gemmt.html) exist each solving a part of the problem. 

As you pointed out in theory these should provide performance but in reality it is much more complicated to reap that performance from the hardware.
