### ISSUE TITLE
DOC, REL: a few release notes/process issues

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#22077]
1. Although @stefanv increased the character limit a few months (years?) ago, for SciPy `1.15.0rc1` release announcement I ran into the character limit again--`An error occurred: Body is limited to 64000 characters; you entered 132964.` This release was massive--I decided to truncate before the perhaps-less-useful issue/PR lists and just link to the raw release notes file on GitHub from the Discourse announcement: https://discuss.scientific-python.org/t/ann-scipy-1-15-0rc1-please-test/1611
2. Something went wrong with `md5` checksum reporting or generation for the release notes. `sha256` still worked. I guess `md5` as an approach has some issues anyway but this wasn't done intentionally. `grep -E -i -A 10 "md5" README.txt`

```
MD5
~~~

{c}
{c}
{c}
{c}
{c}
{c}
{c}
{c}
```

**Comment by rgommers** [comment]
Leaving out the list of issues and PRs seems perfectly fine, too long to read anyway and the few people who care can follow a link to the list in the release notes in this repo.

**Comment by lucascolley** [comment]
another small thing - `integrate.cubature` didn't make it into the highlights section

**Comment by lucascolley** [comment]
Also https://scipy-community.slack.com/archives/C03JL2YGCNR/p1734140162341749

**Comment by tylerjereddy** [comment]
Right, I fixed a few links in the RST->markdown translations for the GitHub and Discourse versions of the release notes, but not all of them. I can always go back and edit them a bit, though the motivation for that is probably stronger for the final release.

Note that what you see on GitHub/Discourse is already fairly heavily edited--the raw RST is a bit of a disaster in general without some manual intervention.
