### ISSUE TITLE
DOC: PchipInterpolator: missing integrate function

### ISSUE THREAD

**Issue by irezni4uk** [scipy/scipy#22072]
### Issue with current documentation:

Documentation for PchipInterpolator misses integrate function in methods section.
Doc link: https://scipy.github.io/devdocs/reference/generated/scipy.interpolate.PchipInterpolator.html
The function itself is available for this class, it was inherited.
Link: https://scipy.github.io/devdocs/reference/generated/scipy.interpolate.PchipInterpolator.integrate.html

**Comment by j-bowhay** [comment]
Would you be interested in making a pr?

**Comment by Nayan2003** [comment]
i am intrested in this issue..

**Comment by j-bowhay** [comment]
Please feel free to open a pr @Nayan2003
