### ISSUE TITLE
API: unannounced breaking change: `scipy.integrate.AccuracyWarning` removed in `1.15.0rc1`

### ISSUE THREAD

**Issue by jorenham** [scipy/scipy#22094]
It used to live in `scipy.integrate._quadrature`, and wasn't exported in `_quadrature.__all__`, but it somehow it did end up in `scipy.integrate.__init__.__all__` in `scipy==1.14.1`:

### `1.14.1` (last line)

https://github.com/scipy/scipy/blob/6036debefcdc80b5e892c5f7a59c856c80cecd76/scipy/integrate/__init__.py#L12-L25

### `1.15.0rc1`

https://github.com/scipy/scipy/blob/964f0bb6701dc17b51b842382ced0fa2ee318377/scipy/integrate/__init__.py#L12-L25

**Comment by j-bowhay** [comment]
It was removed in  #20864 because the only two functions that emitted it were deprecated and removed. Maybe in hindsight it should go through it's own deprecation cycle although this seemed excessive at the time

**Comment by jorenham** [comment]
Personally, I have no problem with it being removed like this. But it should probably be mentioned in at least the release notes.
