### ISSUE TITLE
QUERY: slowness in recent versions mixing OpenBLAS with `multiprocessing`

### ISSUE THREAD

**Issue by Sayanchk1** [scipy/scipy#22105]
### Describe your issue.

We are facing performance issue while running python 3.11 on jupyterhub 4 with scipy version 1.14.1 . But performance improves drastically when we are using scipy version 1.12.0

### Reproducing Code Example

```python
import numpy as np
import pandas as pd
from statsmodels.tsa.statespace.sarimax import SARIMAX
from scipy import stats
import multiprocessing
import time

# Function to simulate SARIMA fitting and use scipy for statistical test
def sarima_fit_and_test(data, order, seasonal_order):
    # Fit SARIMA model
    model = SARIMAX(data, order=order, seasonal_order=seasonal_order)
    results = model.fit(disp=False)
    
    # Perform a basic statistical test using scipy (e.g., Jarque-Bera test for normality)
    jb_stat, jb_p_value = stats.jarque_bera(results.resid)
    
    # Return the results and p-value of the test
    return results.aic, jb_p_value

# Function to parallelize SARIMA fitting using multiprocessing
def run_parallel_sarima(data, orders, seasonal_orders):
    # Creating a pool of workers
    with multiprocessing.Pool(processes=multiprocessing.cpu_count()) as pool:
        # Prepare tasks for parallel execution
        tasks = [(data, orders[i], seasonal_orders[i]) for i in range(len(orders))]
        
        # Run SARIMA fitting in parallel
        results = pool.starmap(sarima_fit_and_test, tasks)
    
    return results

# Main function to generate synthetic data and run the performance test
def performance_test():
    # Generate synthetic data (e.g., seasonal time series)
    np.random.seed(42)
    n = 200
    trend = np.linspace(10, 50, n)
    seasonal = 10 * np.sin(np.linspace(0, 2 * np.pi, n))
    noise = np.random.normal(0, 1, n)
    data = pd.Series(trend + seasonal + noise)
    
    # Define SARIMA orders to test
    orders = [(1, 1, 1), (2, 1, 2), (1, 1, 2), (2, 1, 1)]
    seasonal_orders = [(1, 1, 1, 12), (1, 1, 2, 12), (2, 1, 1, 12), (1, 0, 1, 12)]
    
    # Record start time for performance testing
    start_time = time.time()
    
    # Run the performance test in parallel
    results = run_parallel_sarima(data, orders, seasonal_orders)
    
    # Output results and total execution time
    for idx, (aic, p_value) in enumerate(results):
        print(f"Model {idx + 1}: AIC = {aic:.4f}, Jarque-Bera p-value = {p_value:.4f}")
    
    print(f"Performance Test Completed in {time.time() - start_time:.2f} seconds")

# Run the performance test
if __name__ == "__main__":
    performance_test()

```

### Error message

```shell
No errors message only slow performance
```

### SciPy/NumPy/Python version and system information

```shell
Scipy=1.14.1
Python =3.11.7
```

**Comment by lucascolley** [comment]
thanks for the report @Sayanchk1 . Could you try to create a more minimal example? In particular, could you isolate calls to `stats.jarque_bera` with example arguments which are slower?

**Comment by mdhaber** [comment]
Running this example:
```python3
import numpy as np
from scipy import stats, __version__
print(__version__)
rng = np.random.default_rng(354872348245694356)
x = rng.standard_normal(100000)
%timeit stats.jarque_bera(x)
```
I'm not seeing an inherent slowdown between versions.
```
# 1.12.0
# 2.92 ms ± 276 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
# 1.13.1
# 2.87 ms ± 99.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
# 1.14.0
# 2.68 ms ± 116 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
I think all that was done between 1.12 and 1.14 is add Array API support. That may have added some small constant overhead to each call (a few microseconds), so if the use case involves many calls to the function, each with very fast execution, that may show up.

**Comment by josef-pkt** [comment]
I don't think it's jarque_bera.

computing jarque_bera takes very little time compared to a SARIMAX fit.

If there is a performance difference with the same statsmodels version, then the more likely candidates are that something or some default settings have changed in scipy.optimize, linalg LAPACK using cython, or multiprocessing.
(Those are the heavily used parts.)

**Comment by nickodell** [comment]
I ran some benchmarks, and I have three observations:

First, most time is spent in `SARIMAX.fit()`, rather than `stats.jarque_bera()`.

Here is a line_profiler trace. 99.7% of time is spent in `SARIMAX.fit()`, and only 0.1% is spent in `stats.jarque_bera()`.

<details>

```
Timer unit: 1e-09 s

Total time: 5.04475 s
File: /tmp/ipykernel_26720/745851670.py
Function: sarima_fit_and_test at line 16

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    16                                           def sarima_fit_and_test(data, order, seasonal_order):
    17                                               # Fit SARIMA model
    18         4    9238970.0    2e+06      0.2      model = SARIMAX(data, order=order, seasonal_order=seasonal_order)
    19         4 5030239040.0    1e+09     99.7      results = model.fit(disp=False)
    20                                               
    21                                               # Perform a basic statistical test using scipy (e.g., Jarque-Bera test for normality)
    22         4    5206788.0    1e+06      0.1      jb_stat, jb_p_value = stats.jarque_bera(results.resid)
    23                                               
    24                                               # Return the results and p-value of the test
    25         4      67678.0  16919.5      0.0      return results.aic, jb_p_value

Total time: 5.04758 s
File: /tmp/ipykernel_26720/745851670.py
Function: run_parallel_sarima at line 28

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    28                                           def run_parallel_sarima(data, orders, seasonal_orders):
    29                                               # Creating a pool of workers
    30                                           #     with multiprocessing.Pool(processes=multiprocessing.cpu_count()) as pool:
    31                                                   # Prepare tasks for parallel execution
    32         1       3045.0   3045.0      0.0      tasks = [(data, orders[i], seasonal_orders[i]) for i in range(len(orders))]
    33         1        252.0    252.0      0.0      results = []
    34         5       3238.0    647.6      0.0      for task in tasks:
    35         4 5047571338.0    1e+09    100.0          results.append(sarima_fit_and_test(*task))
    36                                                   
    37                                                   # Run SARIMA fitting in parallel
    38                                                   
    39                                           #         results = pool.starmap(sarima_fit_and_test, tasks)
    40                                               
    41         1        267.0    267.0      0.0      return results

Total time: 5.04808 s
File: /tmp/ipykernel_26720/745851670.py
Function: performance_test at line 44

Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    44                                           def performance_test():
    45                                               # Generate synthetic data (e.g., seasonal time series)
    46         1      10661.0  10661.0      0.0      np.random.seed(42)
    47         1        230.0    230.0      0.0      n = 200
    48         1      88373.0  88373.0      0.0      trend = np.linspace(10, 50, n)
    49         1      71134.0  71134.0      0.0      seasonal = 10 * np.sin(np.linspace(0, 2 * np.pi, n))
    50         1      44068.0  44068.0      0.0      noise = np.random.normal(0, 1, n)
    51         1     156261.0 156261.0      0.0      data = pd.Series(trend + seasonal + noise)
    52                                               
    53                                               # Define SARIMA orders to test
    54         1        348.0    348.0      0.0      orders = [(1, 1, 1), (2, 1, 2), (1, 1, 2), (2, 1, 1)]
    55         1        216.0    216.0      0.0      seasonal_orders = [(1, 1, 1, 12), (1, 1, 2, 12), (2, 1, 1, 12), (1, 0, 1, 12)]
    56                                               
    57                                               # Record start time for performance testing
    58         1        658.0    658.0      0.0      start_time = time.time()
    59                                               
    60                                               # Run the performance test in parallel
    61         1 5047595388.0    5e+09    100.0      results = run_parallel_sarima(data, orders, seasonal_orders)
    62                                               
    63                                               # Output results and total execution time
    64         5       3268.0    653.6      0.0      for idx, (aic, p_value) in enumerate(results):
    65         4     102996.0  25749.0      0.0          print(f"Model {idx + 1}: AIC = {aic:.4f}, Jarque-Bera p-value = {p_value:.4f}")
    66                                               
    67         1      10877.0  10877.0      0.0      print(f"Performance Test Completed in {time.time() - start_time:.2f} seconds")

```

Warning: I modified the program to run the fit in a serial rather than parallel fashion, so I could use line_profiler. This could change the results, but not enough to make a difference of 1000x.

</details>

The second point I noticed is that this program has a load average higher than the number of CPUs. It is attempting both BLAS level parallelism and process level parallelism at the same time. 

Because of this, it runs much faster if BLAS parallelism is disabled.

I tested this by adding this to the top of your program:

```python
import os
os.environ["OPENBLAS_NUM_THREADS"] = "1"

import numpy as np
import pandas as pd
...
```

Here are my results.

| Version        | OMP_NUM_THREADS | Performance Test (seconds) |
|----------------|-----------------|----------------------------|
| scipy 1.12.0   | Default         | 7.75                       |
| scipy 1.14.1   | Default         | 51.34                      |
| scipy 1.12.0   | 1               | 2.42                       |
| scipy 1.14.0   | 1               | 2.35                       |

Note this not only reduces the size of the performance difference between versions, but that it is actually faster than the original program.

Thirdly, I traced through the statsmodels code, and it is spending most of its time inside `scipy.optimize.fmin_l_bfgs_b`, to fit the model. Specifically, it spends 93% of its time in this function or functions within it. So this is most probably an optimize or BLAS related change between 1.12.0 and 1.13.0.

**Comment by Sayanchk1** [comment]
import numpy as np
from scipy.stats import jarque_bera, kstest, norm
from scipy.optimize import minimize
from scipy.integrate import quad
from scipy.sparse import random as sparse_random
from scipy.sparse.linalg import spsolve
import time

# Helper function to measure execution time
def benchmark(func, *args, **kwargs):
    """
    Run a function and measure its execution time.
    """
    start_time = time.time()
    result = func(*args, **kwargs)
    end_time = time.time()
    elapsed = end_time - start_time
    return elapsed, result

# 1. Test Jarque-Bera on large data
def test_jarque_bera():
    data = np.random.normal(0, 1, 10**6)  # Large dataset
    return benchmark(jarque_bera, data)

# 2. Test Kolmogorov-Smirnov test on large data
def test_kstest():
    data = np.random.normal(0, 1, 10**5)  # Large dataset
    return benchmark(kstest, data, norm.cdf)

# 3. Test numerical integration
def test_integration():
    f = lambda x: np.sin(x)**2
    return benchmark(quad, f, 0, 10**4)  # Large integration bounds

# 4. Test optimization (minimization)
def test_optimization():
    f = lambda x: (x - 2)**2
    x0 = np.array([10])  # Far from minimum
    return benchmark(minimize, f, x0, method='BFGS')

# 5. Test sparse matrix solve
def test_sparse_solver():
    matrix_size = 10**4
    A = sparse_random(matrix_size, matrix_size, density=0.01, format='csr')
    b = np.random.rand(matrix_size)
    return benchmark(spsolve, A, b)

# Main function to run all tests
def main():
    print("Benchmarking SciPy 1.14.1 Performance Issues...\n")

    tests = {
        "Jarque-Bera Test": test_jarque_bera,
        "Kolmogorov-Smirnov Test": test_kstest,
        "Numerical Integration": test_integration,
        "Optimization (BFGS)": test_optimization,
        "Sparse Matrix Solver": test_sparse_solver,
    }

    results = {}
    for test_name, test_func in tests.items():
        print(f"Running {test_name}...")
        elapsed_time, _ = test_func()
        results[test_name] = elapsed_time
        print(f"{test_name} took {elapsed_time:.6f} seconds\n")

    print("\nSummary of Results:")
    for test_name, elapsed_time in results.items():
        print(f"{test_name}: {elapsed_time:.6f} seconds")

if __name__ == "__main__":
    main()

**Comment by Sayanchk1** [comment]
Thanks  @mdhaber @lucascolley for looking into the issue
Thanks @josef-pkt @nickodell for identifying the issue

We tried by adding **os.environ["OPENBLAS_NUM_THREADS"] = "1"** with scipy version 1.14.1 in our project in jupyterlab 4 and python 3.11 and the performance improved drastically

Csn you please confirm if we can use the above config in our project and also can we expect the performance issue to be solved in upcoming 1.15 release?

**Comment by lucascolley** [comment]
I believe you can also set this programmatically following https://github.com/joblib/threadpoolctl?tab=readme-ov-file#setting-the-maximum-size-of-thread-pools

**Comment by nickodell** [comment]
> Can you please confirm if we can use the above config in our project going forward and also can we expect the performance issue to be solved in upcoming 1.15 release?

The environment variable I mention isn't something we added, so we can't comment on whether the people who added it, the OpenBLAS maintainers, will remove it. Nonetheless, it has existed for years, and I would be very surprised if they removed it.

We've released a version of SciPy which is very similar to the planned 1.15.0 release, so you can test if it works with your code. It's available on PyPI now, and you can use the command `pip install scipy==1.15.0rc1` to install the release candidate 1 version of 1.15.0. Be aware that this version may have more bugs than usual.

**Comment by lucascolley** [comment]
I think this problem is described in the blog post https://pythonspeed.com/articles/concurrency-control/ by @itamarst.

> can we expect the performance issue to be solved in upcoming 1.15 release?

If you mean "will we not have to use this config once 1.15.0 is released", I think the answer is no. Hopefully that blog post explains why.

**Comment by lucascolley** [comment]
As for why there is a difference between SciPy versions - does the version of OpenBLAS change when you change versions?

**Comment by rgommers** [comment]
> does the version of OpenBLAS change when you change versions?

It will have, and there were lots of changing related to threading behavior in OpenBLAS. The details are time-consuming to work out, so I'd recommend just going with @nickodell's excellent analysis here - avoiding oversubscription is key. `threadpoolctl` is the recommended way of controlling threading when you're using `multiprocessing`.
