### ISSUE TITLE
BUG/DOC: sparse: ND COO unexpected behaviour 1.15.0rc1

### ISSUE THREAD

**Issue by jorenham** [scipy/scipy#22112]
### Describe your issue.

`csc_array` accepts dense array-likes since 1.15.0rc1, and accepts other `csc_array` instances with `ndim > 2`, but raises a `ValueError` if passed a `coo_array` with `ndim > 2`.

### Reproducing Code Example

```pycon
>>> import numpy as np
>>> from scipy.sparse import coo_array, csc_array
>>> csc_array(np.zeros((2, 3, 4)))
<Compressed Sparse Column sparse array of dtype 'float64'
	with 0 stored elements and shape (2, 3, 4)>
>>> coo_array(np.zeros((2, 3, 4)))
<COOrdinate sparse array of dtype 'float64'
	with 0 stored elements and shape (2, 3, 4)>
>>> csc_array(_)
Traceback (most recent call last):
  File "<python-input-10>", line 1, in <module>
    csc_array(_)
    ~~~~~~~~~^^^
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/scipy/sparse/_compressed.py", line 36, in __init__
    arg1 = arg1.asformat(self.format)
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/scipy/sparse/_base.py", line 456, in asformat
    return convert_method(copy=copy)
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/scipy/sparse/_coo.py", line 339, in tocsc
    raise ValueError(f'Cannot convert. CSC format must be 2D. Got {self.ndim}D')
ValueError: Cannot convert. CSC format must be 2D. Got 3D
```

### Error message

```shell
Traceback (most recent call last):
  File "<python-input-10>", line 1, in <module>
    csc_array(_)
    ~~~~~~~~~^^^
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/scipy/sparse/_compressed.py", line 36, in __init__
    arg1 = arg1.asformat(self.format)
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/scipy/sparse/_base.py", line 456, in asformat
    return convert_method(copy=copy)
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/scipy/sparse/_coo.py", line 339, in tocsc
    raise ValueError(f'Cannot convert. CSC format must be 2D. Got {self.ndim}D')
ValueError: Cannot convert. CSC format must be 2D. Got 3D
```

### SciPy/NumPy/Python version and system information

```shell
1.15.0rc1 2.2.0 sys.version_info(major=3, minor=13, micro=1, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28 DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64
    pc file directory: /project
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas32/include
    lib directory: /opt/_internal/cpython-3.13.0/lib/python3.13/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28 DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=64
    pc file directory: /project
    version: 0.3.28
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.13.6
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.2.1
  pythran:
    include directory: ../../tmp/pip-build-env-fa6gfmf0/overlay/lib/python3.13/site-packages/pythran
    version: 0.17.0
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: linux
Python Information:
  path: /opt/python/cp313-cp313/bin/python
  version: '3.13'
```

**Comment by lucascolley** [comment]
Is this a break? I thought the maximum `ndim` for COO arrays was `2` before this release?

**Comment by jorenham** [comment]
> Is this a break? I thought the maximum `ndim` for COO arrays was `2` before this release?

It's mentioned in the [releaase notes](https://github.com/scipy/scipy/releases/tag/v1.15.0rc1):

> n-D sparse arrays in COO format can now be constructed, reshaped and used for basic arithmetic.

... although it doesn't mention the >=2-d support for CSC  🤔

**Comment by jorenham** [comment]
Oh and I just noticed that indexing a `csc_array` with `ndim > 2` also doesn't seem to work:

```pycon
>>> csc_array(np.ones((2, 3, 4)))[0, 0, 0]
Traceback (most recent call last):
  File "<python-input-17>", line 1, in <module>
    csc_array(np.ones((2, 3, 4)))[0, 0, 0]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/scipy/sparse/_index.py", line 57, in __getitem__
    row, col = index
    ^^^^^^^^
ValueError: too many values to unpack (expected 2)
```

```pycon
>>> csc_array(np.ones((2, 3, 4)))[0, 0]
Traceback (most recent call last):
  File "<python-input-18>", line 1, in <module>
    csc_array(np.ones((2, 3, 4)))[0, 0]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/scipy/sparse/_index.py", line 57, in __getitem__
    row, col = index
    ^^^^^^^^
ValueError: too many values to unpack (expected 2)
```

```pycon
>>> csc_array(np.ones((2, 3, 4)))[0]
Traceback (most recent call last):
  File "<python-input-19>", line 1, in <module>
    csc_array(np.ones((2, 3, 4)))[0]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/scipy/sparse/_index.py", line 57, in __getitem__
    row, col = index
    ^^^^^^^^
ValueError: too many values to unpack (expected 2)
```

**Comment by jorenham** [comment]
So, should I add shape-typing support to `csc_coo` in https://github.com/jorenham/scipy-stubs/pull/349, or will it be reverted to only 2-d (I just finished the >2-d shape-typing support for `coo_array` 😅)

**Comment by lucascolley** [comment]
yeah, I don't think this is documented to work anywhere - is there a specific part of the release notes which seems to be missing?

**Comment by lucascolley** [comment]
Ohh, are these examples of things which worked in 1.14.1?

**Comment by jorenham** [comment]
I haven't seen anything myself either. But there a similar "surprise features" in `scipy.sparse`: `coo_array.tensordot`, which doesn't even have a docstring (I did annotate it though) 🤷🏻

> Ohh, are these examples of things which worked in 1.14.1?

No `csc` and `coo` both didn't support >2-d then. `csc` only supported 2-d, and `coo` either 1-d and 2-d

**Comment by lucascolley** [comment]
Okay, so what specifically is this issue about? Do you think we need to make any changes for 1.15.0?

> But there a similar "surprise features" in scipy.sparse: coo_array.tensordot, which doesn't even have a docstring

That does seem like an oversight, cc @dschult @perimosocordiae

**Comment by jorenham** [comment]
> Okay, so what specifically is this issue about? Do you think we need to make any changes for 1.15.0?
> 
> > But there a similar "surprise features" in scipy.sparse: coo_array.tensordot, which doesn't even have a docstring
> 
> That does seem like an oversight, cc @dschult @perimosocordiae

Either quickly remove it before anyone notices, or fix and document it before `1.15.0` final. 

I only quickly tried out the >2d `csc_matrix` and `coo_matrix.tensordot`. And of the 5 or so things I tried with `csc_matrix`, 2 turned out to be bugged. The `coo_matrix.tensordot` is missing a docstring, and raises a `TypeError` once you pass a 2-tuple or list to its `axes` parameter. The `axes=2` default also causes errors when "tensordotting" two 1-d arrays (sparse or dense doesn't matter), as that requires setting `axes=1`. 

Given that I found these bugs this quickly, then it's likely that more will pop up if looked at more thoroughly.

So maybe it's a bit too ambitious if both will need to be to documented, better tested, and bug-fixed, within the two weeks until the 1.15.0 final releaase? 
At least at this point no-one will notice that they won't be included in the final release, given the missing release notes 🤷🏻

**Comment by lucascolley** [comment]
Are these bugs? Or just undocumented intended behaviour?

**Comment by jorenham** [comment]
> Are these bugs? Or just undocumented intended behaviour?

juging by the error messages themselves, I'd say bugs

**Comment by lucascolley** [comment]
for the example in the top post, I think that is intended behaviour. The >2D support in COO is isolated to COO operations, IIUC. I don't think it is interoperable with other sparse formats yet.

**Comment by jorenham** [comment]
FYI, the `scipy-stubs` stubtest errors after upgrading from 1.14.1 to 1.15.0rc1 might contain more cases like this:
https://github.com/jorenham/scipy-stubs/blob/412f02bd8a916070c979815975aea8a953322e59/.mypyignore-todo

I've fixed more than half of them already, and added the additional api-related changes I encountered along the way in https://github.com/jorenham/scipy-stubs/issues/250.

So since you've been more involved in the release process, maybe it could help to give it a look @lucascolley, in case there out of the ordinary that I have missed 🤷🏻

**Comment by jorenham** [comment]
> for the example in the top post, I think that is intended behaviour. The >2D support in COO is isolated to COO operations, IIUC. I don't think it is interoperable with other sparse formats yet.

Ah ok, I was just assuming that the >2-d support was intentional, and reasoned from there.

But in case of `tensordot`, I don't see how adding a new public method could be considered a bug, as that's not very likely to happen when your cat jumps on your keyboard (although theoretically it isn't impossible).

**Comment by jorenham** [comment]
But after looking at the `csc` code a bit more, I think it's indeed more likely that the >2-d support was unintentional, like you suggested @lucascolley. 
I can imagine that the >2-d `coo` support trojan-horsed itself into `csc` or something.

**Comment by lucascolley** [comment]
Yep, `tensordot` just looks like a lack of documentation. For the other issues, is it just a case of being more explicit in error messages / the release notes about the (limited) extent of the >2D support so far?

**Comment by jorenham** [comment]
> Yep, `tensordot` just looks like a lack of documentation. For the other issues, is it just a case of being more explicit in error messages / the release notes about the (limited) extent of the >2D support so far?

Apart from the lack of documentation, the following errors look kinda buggy to me:

```pycon
>>> a.tensordot(a, axes=1)
<COOrdinate sparse array of dtype 'float64'
	with 3 stored elements and shape (3, 3)>
>>> a.tensordot(a, axes=2)
np.float64(3.0)
>>> a.tensordot(a, axes=(1,))
Traceback (most recent call last):
  File "<python-input-25>", line 1, in <module>
    a.tensordot(a, axes=(1,))
    ~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/scipy/sparse/_coo.py", line 958, in tensordot
    axes_self, axes_other = _process_axes(self.ndim, other.ndim, axes)
                            ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/scipy/sparse/_coo.py", line 1206, in _process_axes
    raise ValueError("axes must be a tuple/list of length 2")
ValueError: axes must be a tuple/list of length 2
>>> a.tensordot(a, axes=(1,2))
Traceback (most recent call last):
  File "<python-input-26>", line 1, in <module>
    a.tensordot(a, axes=(1,2))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/scipy/sparse/_coo.py", line 958, in tensordot
    axes_self, axes_other = _process_axes(self.ndim, other.ndim, axes)
                            ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joren/.pyenv/versions/3.13.1/lib/python3.13/site-packages/scipy/sparse/_coo.py", line 1208, in _process_axes
    if len(axes_a) != len(axes_b):
       ~~~^^^^^^^^
TypeError: object of type 'int' has no len()

```

**Comment by perimosocordiae** [comment]
Thanks for digging into this! 

- CSC should not support ndim > 2, so that's a bug to be fixed.
- tensordot definitely needs documentation, and better axis handling. 

@dschult do you have time for a quick fix PR?

**Comment by lucascolley** [comment]
I just reread the top post and noticed the `csc_array(np.zeros((2, 3, 4)))` line, somehow I missed that - apologies for the noise!

**Comment by dschult** [comment]
Only COO format supports ndim>2.
And tensordot should definitely have documentation. And the axis handling should either be better or raise an exception that says it is not fully developed yet. I'll take a look.

**Comment by dschult** [comment]
The correct annotation for the axes input to tensordot should match the annotation for numpy tensordot. It might also show up better in the [array api standard documentation](https://data-apis.org/array-api/2022.12/API_specification/index.html).
So I think it is ```Union[int, Tuple[Sequence[int], Sequence[int]]]```

But I prefer the description in the docs to the annotation (cuz I don't know enough about annotations to read them).
```
axes : integer_like or length 2 array_like
        * integer_like
          If an int N, sum over the last N axes of `a` and the first N axes
          of `b` in order. The sizes of the corresponding axes must match.
        * (2,) array_like
          Or, a list of two axes sequences to be summed over, first sequence
          applying to `a`, second to `b`. Both elements of array_like must be the same length. 
```
So, `axes=(1,2)` is expected to raise, while `axes=((1,2), (2,0))` is allowed (if the integers are valid for the ndims).

I think we need to fix the CSC (and CSR) constructors to give a reasonable message for nD dense input.
And we need docs for tensordot.

Thanks @jorenham !  It is really helpful for someone to work through each feature of each new function. And annotation require that. But we really should have caught the missing doc_string. :{   Anyway -- That's very much!

**Comment by jorenham** [comment]
that clears things up :)
I'll update the `scipy-stubs` annotations for it 👌🏻
