### ISSUE TITLE
DOC: stats: random variable transition guide launches wrong notebook

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy#22123]
### Issue with current documentation:

Clicking "open as a notebook" on https://scipy.github.io/devdocs/tutorial/stats/rv_infrastructure.html loads `hypothesis_bartlett.ipynb` in JupyterLite, rather than `rv_infrastructure.ipynb`.

### Idea or request for content:

Should load `rv_infrastructure.ipynb` instead. Perhaps the first cell of that notebook needs to change? Currently it contains

```md
```{eval-rst}
.. jupyterlite:: ../../_contents/hypothesis_bartlett.ipynb
   :new_tab: True
```

### Additional context (e.g. screenshots, GIFs)

cc @mdhaber @agriyakhetarpal @melissawm @steppi

**Comment by agriyakhetarpal** [comment]
Thanks for reporting, @lucascolley! It looks like other notebooks are working correctly, I just checked a different one: https://scipy.github.io/devdocs/tutorial/stats/sampling.html and it launches `sampling.ipynb`.

So, it is indeed a quick fix, the directive was mapped to the correct notebook earlier in gh-22025 but, after adding the `jupyterlite_sphinx_strip` tag introduced in gh-22042, this might have been missed when copy-pasting the snippet.
