### ISSUE TITLE
ENH: Quantiles for probability distributions

### ISSUE THREAD

**Issue by galenseilis** [scipy/scipy#22134]
### Is your feature request related to a problem? Please describe.

Quantiles are often of interest for me in computing prediction intervals for resource demand. My context is resource planning in healthcare, which is a context where we're more concerned about a range of possible outcomes rather an average outcome. We want to help everyone if we can, not just the "average person" or people in "average situations".

### Describe the solution you'd like.

Like other methods such as `cdf`, I would like for there to be a `quantile` method.

This is not uniquely defined for purely nominal / categorical random variables, but it is for distributions whose support is totally ordered. 

Here is some discussion of what could be done with purely nominal variables. One option is it have a `NotImplementedError` when the `quantile` method is called, and provide an informative message about a quantile not being uniquely defined for categorical variables. Another, logically independent, option is to allow the user to provide an total ordering on the categories via sequence of contiguous integers.

### Describe alternatives you've considered.

On a given problem I can usually write a solution myself. 

For example, with counting variables you can just start at X=0 and increment x+=1 until you find the first X=x such that the CDF(X>=x) >= p where p is some target probability. 

This is low-hanging fruit for count variables, but a similar algorithm could be devised for integer support by have a further rule that has to decide whether to increment or decrement.

These implementations are perhaps naive, but I think would be a reasonable starting point in the absence of better ideas.

---

Another approach is to use packages other than SciPy. Of course I have considered that, but I kind of want my distribution classes to be a one-stop-shop for extracting properties of said distribution.

### Additional context (e.g. screenshots, GIFs)

I'm willing to make a PR for an easy case, say the Poisson distribution, to get the ball rolling.

**Comment by rkern** [comment]
See the `ppf()` [method of distributions](https://docs.scipy.org/doc/scipy-1.14.1/tutorial/stats/probability_distributions.html#common-methods). It's the inverse of the CDF.

In the coming [new distribution infrastructure](https://scipy.github.io/devdocs/tutorial/stats/rv_infrastructure.html), this will be named somewhat more recognizably as `icdf()`.

**Comment by galenseilis** [comment]
@rkern Thank you! I did not recognize the term "Percent Point Function (PPF)".
