### ISSUE TITLE
Can't pickle `array_namespace` 

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#22138]
### Describe your issue.

I'm experimenting with working in a certain multiprocessing context. I have an object in which I'd like to store an array namespace. However, array namespaces don't appear to be pickleable, which prevents my object being serialised to a pickle. I can work around this, but the workaround will require a large volume of calls to `array_namespace`.

- is there another way of storing the `array_namespace` which is pickleable?
OR
- can the namespace be altered to permit this kind of serialisation?

### Reproducing Code Example

```python
import numpy as np
from scipy._lib._array_api import array_namespace
import pickle

x0 = np.array([1., 2, 3])
xp = array_namespace(x0)
pkl = pickle.dumps(xp)
```

### Error message

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 7
      5 x0 = np.array([1., 2, 3])
      6 xp = array_namespace(x0)
----> 7 pkl = pickle.dumps(xp)

TypeError: cannot pickle 'module' object
```

### SciPy/NumPy/Python version and system information

```shell
HEAD
```

**Comment by ev-br** [comment]
Seems to be propagating from upstream:

```
In [1]: import torch

In [2]: import pickle

In [3]: import numpy as np

In [4]: pickle.dumps(np)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[4], line 1
----> 1 pickle.dumps(np)

TypeError: cannot pickle 'module' object

In [5]: pickle.dumps(torch)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[5], line 1
----> 1 pickle.dumps(torch)

TypeError: cannot pickle 'module' object
```

Googling around seems to indicate it's a known problem, which `dill` works around. But that doesn't have multiprocessing, I suppose.

**Comment by j-bowhay** [comment]
`pathos` is a fork of `multiprocessing` that works with `dill`, I have had success with it previously

**Comment by andyfaff** [comment]
Background is that I'm investigating making the internals of some optimise functionality parallelisable. The majority of people would use multiprocessing so classes and functions need to be pickleable.

**Comment by izaid** [comment]
You can't pickle modules so far as I know. But you can write a write custom pickle implementation on an object with `__getstate__` and `__setstate__`, which could serialize `xp` with a string or something.

**Comment by rgommers** [comment]
Question after a quick glance at gh-22119: I assume the problem is this line?
```python
self.xp = xp = array_namespace(x0)
```
That's probably not ideal because of picking (even without introducing a `workers=` option) - passsing on `xp` in a functional fashion seems preferable. Can't it be propagated normally through function/method calls?

**Comment by andyfaff** [comment]
See #22141 for what I'm looking at. `approx_derivative` can be parallelised in a relatively straightforward manner. It's just that things to do with multiprocessing are fussy about pickling. A lot of the wrappers we use for calling the objective function aren't suitable. I prefer to use a class-based `__call__` pattern that can make use of attributes that a function/method with more arguments.

**Comment by ev-br** [comment]
Would it work to attach a namespace at unpickling time, in `__setstate___` or some such? 
Alternatively, maybe it's something for the Pool object to have and propagate to the workers?

**Comment by andyfaff** [comment]
If `array_namespace` is cheap, then I probably won't have to do anything. `__setstate__`, and `functools.partial` are probably good alternatives.
