### ISSUE TITLE
BUG: `stats._distribution_infrastructure._Domain.symbols` class attribute is shared by instances

### ISSUE THREAD

**Issue by jorenham** [scipy/scipy#22137]
### Describe your issue.

The following **class** attribute is defined in `scipy.stats._distribution_infrastructure._Domain`:

https://github.com/scipy/scipy/blob/e7dfd40c5b1e7f094e0477e85fb0cfeae00bef81/scipy/stats/_distribution_infrastructure.py#L216

Its subclass, `_SimpleDomain`, mutates it in an instance method:

https://github.com/scipy/scipy/blob/e7dfd40c5b1e7f094e0477e85fb0cfeae00bef81/scipy/stats/_distribution_infrastructure.py#L297

... even though `_Domain.__init___` doesn't shadow it (i.e. `self.symbols = ...`):
https://github.com/scipy/scipy/blob/e7dfd40c5b1e7f094e0477e85fb0cfeae00bef81/scipy/stats/_distribution_infrastructure.py#L269-L274

So as far as I can tell, it's directly updated on the class state, and therefore shared between all instances. I don't see why this would be intended behaviour, so I thought I'd let you know.

This is relevant to the current `main` branch, and I spotted this in the `1.15.0rc1` release.

### Reproducing Code Example

```python
...
```

### Error message

```shell
...
```

### SciPy/NumPy/Python version and system information

```shell
irrelevant
```

**Comment by mdhaber** [comment]
Thanks @jorenham. Yeah, I'll want to revisit that system at some point to see if I can simplify things. In the meantime, I think it would be sufficient to just copy it in the `_SimpleDomain` initializer (gh-22139).

**Comment by jorenham** [comment]
I'll update https://github.com/jorenham/scipy-stubs/pull/360 accordingly (remove the `ClassVar`) 👌🏻
