### ISSUE TITLE
DOC: linalg.cossin: improve readability of equation

### ISSUE THREAD

**Issue by j-bowhay** [scipy/scipy#22151]
### Issue with current documentation:

![Screenshot_20241221-071708](https://github.com/user-attachments/assets/145650f3-fc89-4d0e-9f16-1c84b1a435b0)
The alignment makes the equation very difficult to read.

### Idea or request for content:

Either play around with the whitespace to make it clearer or move the extended summary to a notes section and convert the equation to latex. My preference would be for the later

**Comment by ilayn** [comment]
That font is not monospace anymore apparently. It shouldn't have variable width character. In latex it reads terrible if not rendered

**Comment by j-bowhay** [comment]
Even in version 1.5 when this was added it didn't render correctly 
![Screenshot_20241221-083545](https://github.com/user-attachments/assets/7e5ef039-8599-4a4c-a656-9bc5491a03d9)

**Comment by ilayn** [comment]
Something must have changed in the font that docs are getting. The version won't matter because the monospace font it is asking, regular monospace fonts render it correctly including githubs own

![image](https://github.com/user-attachments/assets/e01fa06c-3916-4886-ad13-af2a557b1880)

**Comment by mdhaber** [comment]
I think it's monospaced font, but the characters being used can't line up nicely within a given column. These are not normal dashes and `+` and such.

**Comment by ilayn** [comment]
On my computer I see this, with Firefox 

![image](https://github.com/user-attachments/assets/0f25b9da-693c-474c-92a0-4b2e52b743f3)

So this seems like machine dependent. Can you see which font is used in rendering?

**Comment by ilayn** [comment]
> I think it's monospaced font, but the characters being used can't line up nicely within a given column. These are not normal dashes and + and such.

The whitespaces are not monospaced in Jake's screenshot, since it is already happening on the left hand side X11 X12 line. without dashes or +

**Comment by j-bowhay** [comment]
Hmm interesting, when I view the source on GitHub it is not aligned properly

**Comment by mdhaber** [comment]
They might be characters with vertical lines at different horizontal locations within a given cell.

**Comment by ilayn** [comment]
Then it would just render crooked lines but the total alignment would be preserved. Here the number of whitespace characters are smaller than non-whitespace chars hence they shift to the left depending on how many compared to the middle line.

**Comment by mdhaber** [comment]
Yeah I checked and the vertical bars are the same. Maybe some characters cannot be rendered in monospaced on some machines? It's as though it is mixing monospaced and non-monospaced characters, because sometimes when I replace the bars with normal letters, things begin to line up to the right.

**Comment by ilayn** [comment]
Looks like a fontawesome thing depending on the system. Interesting indeed

**Comment by mdhaber** [comment]
Maybe the solution is to use normal `+ - |` instead of these special characters? We'd see gaps in the lines, but it would align, so worse in the best case but much better in the worst case.

**Comment by ilayn** [comment]
Fine with me, but I still think it's the spaces not the chars that disturbs the rendering. You can change the font in the developer options

**Comment by mdhaber** [comment]
On my Mac it's fine. To test things:
```
────────── # 10 ─ characters
---------- # 10 - characters
││││││││││ # 10 │ characters
|||||||||| # 10 | characters
┼┼┼┼┼┼┼┼┼┼ # 10 ┼ characters
++++++++++ # 10 + characters
┌┌┌┌┌┌┌┌┌┌ # 10 ┌ characters
```

**Comment by ilayn** [comment]
Ah OK then it is indeed the font with its funky char widths

**Comment by mdhaber** [comment]
Maybe it's just mobile then? Because Jake's screenshot is from a cell.

**Comment by j-bowhay** [comment]
I'm guessing this relates to being on a mobile. Thanks for investigating and sorry for the noise!

**Comment by lucascolley** [comment]
FWIW, it renders nicely in monospace for me on Safari on iOS
