### ISSUE TITLE
BUG: integrate_box after scipy.stats. gaussian_kde fit

### ISSUE THREAD

**Issue by riccstef** [scipy/scipy#22203]
### Describe your issue.

I fitted a Gaussian KDE over 3D data. After that I wanted to calculate the probability before and after (0,0,0). The two must sum to 1 but I didn't get that value.

### Reproducing Code Example

```python
kde = gaussian_kde(np.random.randn(3,100))
print(kde.integrate_box(-10*np.ones(3,), np.zeros(3,), maxpts=3000000) + kde.integrate_box(np.zeros(3,), 10*np.ones(3,), maxpts=3000000))
```

### Error message

```shell
Result is around 0.26
```

### SciPy/NumPy/Python version and system information

```shell
1.14.1 1.26.4 sys.version_info(major=3, minor=12, micro=8, releaselevel='final', serial=0)
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-do_lqnow/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-do_lqnow/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=24
    pc file directory: D:/a/scipy/scipy
    version: 0.3.27.dev
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-do_lqnow/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-do_lqnow/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas32/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27.dev DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=24
    pc file directory: D:/a/scipy/scipy
    version: 0.3.27.dev
  pybind11:
    detection method: config-tool
    include directory: unknown
    name: pybind11
    version: 2.12.0
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  c++:
    commands: c++
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
  fortran:
    commands: gfortran
    linker: ld.bfd
    name: gcc
    version: 10.3.0
  pythran:
    include directory: C:\Users\runneradmin\AppData\Local\Temp\pip-build-env-sf8gymnb\overlay\Lib\site-packages/pythran
    version: 0.16.1
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  cross-compiled: false
  host:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
Python Information:
  path: C:\Users\runneradmin\AppData\Local\Temp\cibw-run-do_lqnow\cp312-win_amd64\build\venv\Scripts\python.exe
  version: '3.12'
```

**Comment by mdhaber** [comment]
Isn't this computing the probability mass in only two of the eight octants?

**Comment by riccstef** [comment]
> Isn't this computing the probability mass in only two of the eight octants?
> 
> If you want all of it:
> 
> ```python
> import numpy as np
> from scipy import stats
> kde = stats.gaussian_kde(np.random.randn(3,100))
> print(kde.integrate_box(-10*np.ones(3,), 10*np.ones(3,), maxpts=3000000))  # 1.0000000000000007
> ```

In my understanding integrate_box should provide the CDF from lower to upper, so given a 3D standard normal I provided  [-Inf,0] for all the 3D (triple integral) and this should be half of the domine. I am probably missing some point

**Comment by riccstef** [comment]
Some other strange behaviour. This happens when some lower bound > upper bound:

2D

`import numpy as np
from scipy import stats
kde = stats.gaussian_kde(np.random.randn(2,100))
print(kde.integrate_box([-10,10], [0,0], maxpts=3000000))  # -0.18570840781510511 negative probability`

but in 3D

`import numpy as np
from scipy import stats
kde = stats.gaussian_kde(np.random.randn(3,100))
print(kde.integrate_box([-10,10,0], [0,0,0], maxpts=3000000))  # 0 it is a probability at least`

Also, if you try lower = 10 and upper=-10 for all dimensions you get 1 for 2D and 0 for 3D. To me there is a bug.

**Comment by rkern** [comment]
The triple integral from `[-inf, 0]` in each of the 3 dimensions is not half the domain but 1/8th of the domain, a single octant.

Note that when you integrate "backwards", note that there is a mathematical convention that states that the integral from `b` to `a` is the negative of the integral from `a` to `b`. So the negative answer is correct; the integral of a positive function from `b` to `a` where `b>a` will be negative. The 0 answer in your 3D example comes from the fact that you have equal lower and upper bounds in the 3rd dimension, so you are integrating over no volume.
