### ISSUE TITLE
functions for testing minimization

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#2421]
Would it be useful to gather some of these functions together?  I've noticed they are scattered across the scipy codebase.  I was thinking of something like a scipy/optimize/bench.py module to collect the functions, and add a few new ones.

The functions I have in mind would be smooth functions for minimization and would provide R^N -> R function evaluation, and also the gradient, the hessian, and an evaluation of the hessian-vector product for an arbitrary vector.

But the interface could become a little bit messy.  For example you might want to list one or more local or global mins or argmins for each function.  Maybe someone would also want the roots f(x)=0 when the function is R^1 -> R.  Furthermore, some functions (e.g. Rosenbrock) are parameterized R^N -> R where N can be specified by the user.  Some functions might have box constraints on their domains, or they might have more complicated domain constraints.

**Comment by mdhaber** [comment]
@andyfaff @antonior92  Certainly this has been addressed for global optimization. There  are several benchmark tests for `minimize`, too. Do you think this can be closed?

 (Note: `trust-constr` needs to be added to the list of `method`s that are benchmarked, but that's a separate issue.)

**Comment by andyfaff** [comment]
I think this can be closed, but it would be nice to have all the NIST test cases in the benchmarking suite.

**Comment by antonior92** [comment]
I agree that this can be closed since is a quite old issue and it does have been (partially) addressed over the last years. Even though I do agree with @andyfaff  that there is space for a lot of improvements in benchmarking the optimization methods (i.e. including CUTEst test cases)

**Comment by mdhaber** [comment]
So should there be a new issue (enhancement request) that is more specific?
