### ISSUE TITLE
Special functions for Toeplitz matrices

### ISSUE THREAD

**Issue by lesshaste** [scipy/scipy#2432]
scipy.linalg.toeplitz creates a Toeplitz matrix.  It is also possible to perform some operations on these matrices much faster than on general matrices (see http://en.wikipedia.org/wiki/Toeplitz_matrix#Solving_a_Toeplitz_system).  Is there any plan to add such support? I am particularly interested in determinant computation for example.

**Comment by ilayn** [comment]
See #4302
