### ISSUE TITLE
rmatmat and the sophistication of linear operator objects

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#2434]
The scipy linear operator interface has matvec, rmatvec, and matmat, but it seems to be missing rmatmat (pardon the kerning on that word).

I've noticed that rmatmat has been added independently (or is unremoved?) here
https://github.com/nbarbey/linear_operators/blob/master/linear_operators/interface.py

That fork has some other nifty features, and I also see that this is a thing
http://pchanial.github.io/pyoperators/

**Comment by lobpcg** [comment]
It is very unfortunate that this issue is dead since 2013. rmatmat is a must operation for efficient SVD. https://github.com/scipy/scipy/blob/v1.3.0/scipy/sparse/linalg/eigen/arpack/arpack.py#L1704-L1881 goes around it with reducing it to using rmatvec on every column sequentially. If rmatmat was implemented properly, it would accelerate the code multiple times. No surprise that scikit has implemented it's own SVD solvers, avoiding LinearOperator and svds. 

Could not that trivially be implemented by something like 
`A.T.adj @ X = (X.T.adj @ A).T.adj`

**Comment by rgommers** [comment]
> rmatvec is being implemented as a wrapper to the corresponding user-provided function. Why not to have also rmatmat the same way?

That seems to be what https://github.com/nbarbey/linear_operators/blob/master/linear_operators/interface.py does indeed

**Comment by lobpcg** [comment]
Nice, so why scipy version cuts it off? This is really the only way to do it, and it is already coded...

**Comment by rgommers** [comment]
> Nice, so why scipy version cuts it off? This is really the only way to do it, and it is already coded...

No conscious decision, just no one has done the work. Last update on merging that PyOperators package back is https://github.com/scipy/scipy/issues/2473#issuecomment-18144996. As @argriffing predicted that isn't likely to happen, but we can take parts of it as needed - looks relatively straightforward here.

**Comment by rgommers** [comment]
We don't have a dedicator maintainer for `LinearOperator` unfortunately .....

**Comment by lobpcg** [comment]
You think that https://github.com/nbarbey/linear_operators/blob/master/linear_operators/interface.py may be an update to the current scipy version?

**Comment by rgommers** [comment]
> You think that https://github.com/nbarbey/linear_operators/blob/master/linear_operators/interface.py may be an update to the current scipy version?

Not easily, as discussed in gh-2473 it'd be a lot of work. That's why I was suggesting just taking the `rmatmat` bit, since that does seem easy.

**Comment by lobpcg** [comment]
Of course, I am also only suggesting just taking the rmatmat , since it is practically needed, e.g., in 
https://github.com/scipy/scipy/pull/10830 

@rgommers would you be able to do it?

**Comment by rgommers** [comment]
I _may_ be able to do it on Sunday, but not sure - if someone else wants to try this that'd be great.

**Comment by lobpcg** [comment]
Of course, I am also only suggesting just taking the rmatmat , since it is practically needed, e.g., in 
https://github.com/scipy/scipy/pull/10830 

@rgommers would you be able to do it?

> 
> 
> I _may_ be able to do it on Sunday, but not sure - if someone else wants to try this that'd be great.

Done

**Comment by pv** [comment]
gh-10849 merged
