### ISSUE TITLE
rfftn not included from numpy, scipy's rfft different from numpy's rfft

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#2487]
As discussed here https://github.com/scipy/scipy/pull/337/files#r2227022 , Numpy's rfftn is not included in SciPy.

However, SciPy's version of rfft (2 real results per frequency bin) behaves differently from numpy's (1 complex result per frequency bin), so it may be confusing to just import it side-by-side.

In an old discussion, most people seem to agree that numpy's rfft output is superior:

[[Numpy-discussion] rfft different in numpy vs scipy, Sep 11 2006](http://mail.scipy.org/pipermail/numpy-discussion/2006-September/022977.html)

especially because that format matches the format for complex `fft` and works for N-dimensions, while SciPy's does not:

> the _reason_ why FFTW's r2c routines produce unpacked output is largely because "packed" formats do not generalize well to multi-dimensional FFTs, while the "unpacked" format does.

Does it make sense to replace Scipy's rfft with numpy's?  Or to rename it or make its output behavior an option, with numpy's behavior as default?

Illustration:

```
In [1]: a = [9, -9, 1, 3]

In [2]: numpy.fft.fft(a)
Out[2]: array([  4. +0.j,   8.+12.j,  16. +0.j,   8.-12.j])

In [3]: numpy.fft.rfft(a)
Out[3]: array([  4. +0.j,   8.+12.j,  16. +0.j])

In [4]: numpy.fft.rfftn(a)
Out[4]: array([  4. +0.j,   8.+12.j,  16. +0.j])

In [5]: scipy.fftpack.fft(a)
Out[5]: array([  4. +0.j,   8.+12.j,  16. +0.j,   8.-12.j])

In [6]: scipy.fftpack.rfft(a)
Out[6]: array([  4.,   8.,  12.,  16.])
```

Other confused people:
- [Why does scipy.fftpack.rfft return real values? (SO, 2016)](http://stackoverflow.com/q/34788424/125507)
- [Python scipy.fftpack.rfft frequency bin mapping (SO, 2014)](http://stackoverflow.com/questions/21517998/python-scipy-fftpack-rfft-frequency-bin-mapping)
- [Python scipy.fftpack.rfft frequency bin mapping (DSP.SE, 2014)](http://dsp.stackexchange.com/questions/14175/python-scipy-fftpack-rfft-frequency-bin-mapping)
- [[SciPy-user] Numpy/Scipy rfft transformations do not match?, Feb 28 2009](https://mail.scipy.org/pipermail/scipy-user/2009-February/020130.html)
- [How should I multiply scipy.fftpack output vectors together? (SO, 2013)](http://stackoverflow.com/questions/18537184/how-should-i-multiply-scipy-fftpack-output-vectors-together)

**Comment by fasiha** [comment]
Scipy's rfft probably shouldn't be replaced with Numpy's because of #6012—the latter upcasts everything to float64/complex128 while the former can work with single-precision.

**Comment by endolith** [comment]
Well the important thing is the output format, not the implementation.  Can it be made to output the simpler format while also handling single-precision?

Note that numpy's is somewhat slower:

```
x = randn(65536)

timeit scipy.fftpack.rfft(x)
1000 loops, best of 3: 1.65 ms per loop

timeit numpy.fft.rfft(x)
100 loops, best of 3: 2.77 ms per loop

x = randn(65536).astype('float32')

timeit scipy.fftpack.rfft(x)
1000 loops, best of 3: 1.16 ms per loop

timeit numpy.fft.rfft(x)
100 loops, best of 3: 2.59 ms per loop
```

**Comment by carlodri** [comment]
I found this issue after posting [this question](http://stackoverflow.com/questions/34788424/why-does-scipy-fftpack-rfft-return-real-values) on stackoverlflow. I agree with @endolith that it is quite weird for `scipy.fftpack.rfft` to output two real values per frequency bin, and this is also inconsistent with the output format of `scipy.fftpack.fft` (one complex value per bin). Is there any deep reason for keeping the actual (strange) behavior?

**Comment by Eric89GXL** [comment]
It would be great if we could take care of this for 1.0 at least, so I've optimistically marked it for 0.19.

Could we have an `output='real' | 'complex'` argument that defaults to the current behavior (or deprecates it, maybe changing over on 1.0 release)?

**Comment by endolith** [comment]
I agree it would be good if the default behavior could be changed in 1.0.

**Comment by Eric89GXL** [comment]
@e-q @rgommers (@WarrenWeckesser if you have time) are you okay with this proposal for `scipy.fftpack.rfft`:
1. Add `output='real' | 'complex'` argument
2. Current behavior is like `output='real'`, which returns `[DC, f1_real, f1_imag, f2_real, f2_imag, ...]`
3. Go through a deprecation cycle to get to the new default `output='complex'` as `[DC, f1_complex, f2_complex, ...]` (as in `numpy.fftpack.rfft`) by 1.0?

@endolith do you have time for a PR? I'm not sure what `numpy` does to populate the matrix. You can do something like `out[1:-var1] = arr[1:-var2].view(np.complex128)` and then be careful about DC (copy) and Nyquist (triage based on even/odd) terms to change the output, but I wonder if there is some cleaner/faster way that avoids a memcopy-like operation.

**Comment by WarrenWeckesser** [comment]
+1 for doing *something*. The format returned by `scipy.fftpack.rfft` has always been a nuisance.

An alternative is to create a new function, say `rfftc`, that has the same output format as `numpy.fft.rfft`. The existing function could be left as is, so no deprecation would be necessary.

If the `output` argument is used, it needs a longish deprecation cycle before switching the default from `'real'` to `'complex'`.  `scipy.fftpack.rfft` has been around for a long time, and there could be quite a bit of code out there that uses it.

**Comment by Eric89GXL** [comment]
I'm fine with `scipy.fftpack.rfftc`, and actually slightly prefer it over adding an `output` argument. So we'd need `rfftc` and `irfftc`, which should be okay.

**Comment by endolith** [comment]
So would rfftn stay numpy-only then?

**Comment by endolith** [comment]
Would it make sense to add a scipy.fft submodule that matches numpys? I'm not really sure why these even exist in both packages, when one package is a prerequisite for the other (and scipys is in fortran while numpys is in c).

**Comment by rgommers** [comment]
> So would rfftn stay numpy-only then?

That would be better. Unless the Fortran backed version would be much faster (didn't check but don't think so), there's no reason to duplicate.

> I'm not really sure why these even exist in both packages

History:(

> Would it make sense to add a scipy.fft submodule that matches numpys

I don't see what that would add? Better to resolve differences via the normal mechanisms (add new functions, deprecate, add keywords, ...)

**Comment by endolith** [comment]
> History:(

Well if one implementation is clearly better (or can be made better) than the other, can the other be "soft deprecated"/officially discouraged and focus any improvements on the better one to reduce confusion about which to use?

> I don't see what that would add? 

Then SciPy could have an rfft that's consistent with fft, and an rfftn that's consistent with fftn, without breaking backwards compatibility. (Similar to creating a unified filter API under a new submodule name.) 

Technically "fftpack" refers to the specific fft implementation, not things like Hilbert that SciPy has added to it?

**Comment by rgommers** [comment]
> Well if one implementation is clearly better (or can be made better) than the other, can the other be "soft deprecated"/officially discouraged and focus any improvements on the better one to reduce confusion about which to use?

Indeed, we can add that "soft deprecation" in the docs.

> Then SciPy could have an rfft that's consistent with fft, and an rfftn that's consistent with fftn, without breaking backwards compatibility. (Similar to creating a unified filter API under a new submodule name.) 

The difference is that there are no filters in numpy. We can just say "use the numpy ``rfft`` and ``rfftn`` functions" in the docs. Adding what are basically duplicates in scipy as new functions doesn't then add anything, unless I'm missing your point. 

> Technically "fftpack" refers to the specific fft implementation, not things like Hilbert that SciPy has added to it?

Yeah, it's a terrible name.

**Comment by Eric89GXL** [comment]
> We can just say "use the numpy rfft and rfftn functions" in the docs. Adding what are basically duplicates in scipy as new functions doesn't then add anything, unless I'm missing your point.

To me it does add something. Ideally there would be one place people could go to get their (r)fft(n) functions. Even as a fairly heavy user of these packages I will probably end up writing `from scipy.fftpack import rfftn` at some point, only to be reminded by way of an `ImportError` that I needed to do something else like `from numpy.fft import rfftn`. The drawback to putting `rttfn` or `rfftc` in is duplicated functionality, but the benefit of users having a single a unified location to get core FFT-related functionality (`scipy.fftpack`) would be worth it to me. It's not a big thing, but it would be nice.

Related to `rfftn` missing from `scipy.fftpack`, the function `rfft` exists as both `numpy.fft.rfft` and `scipy.fftpack.rfft` but gives different output for the same input. Again I'd prefer to have `scipy.fftpack.rfftc`, which would behave the same way as `numpy.fft.rfft`, for the same reasons as with `rfftn`. @rgommers by extension from the `rfftn` reasoning, I assume you'd prefer to point people to `numpy.fft.rfft` if they want a one-sided complex (instead of real) output, as opposed to having us implement a duplicate-style `rfftc` function?

**Comment by rgommers** [comment]
I don't have a very strong opinion, but there should be significant benefits to duplication imho. If we add ``rfftc`` which behaves as ``np.fft.rfft`` but then also leave a ``rfft`` in scipy, then that's still horribly inconsistent - you anyway have to be aware of it, and if you are then you may as well go to numpy.

> To me it does add something. Ideally there would be one place people could go to get their (r)fft(n) functions.

If we really want to achieve that, then maybe we should indeed add a ``scipy.fft`` which is designed right, and deprecate all of ``fftpack`` in the docs.

**Comment by Eric89GXL** [comment]
> If we really want to achieve that, then maybe we should indeed add a scipy.fft which is designed right, and deprecate all of fftpack in the docs.

I'm fine with this solution, especially given that the `scipy.fftpack` name is already a misnomer. Then we could just leave `scipy.fftpack` as it is, and make `scipy.fft` from the beginning to be consistent. Would this be your preferred solution, or still a bit overkill compared to instead pointing people to the right places through docs?

**Comment by rgommers** [comment]
Not quite sure, depends how many things we'd want to change. Don't have a good overview right now. We may for example want to get rid of ``convolve``, we have too many of those. It's quite a big job though to get such an exercise first time right, not sure anyone is going to want to invest that time.

**Comment by jakirkham** [comment]
Not sure if someone already mentioned this, but one advantage of the `rfft`/`irfft` functions from SciPy is doing a round trip just works. This is because we know the shape is unchanged by these functions. However with the NumPy versions one needs to provide the shape as it can be ambiguous by at most 1 in the transformed dimension (see linked issue). An example of this is shown below. Not sure if there are other benefits to preserving the shape like this (in-place computation?).

<details>

```python
In [1]: import numpy

In [2]: import numpy.fft

In [3]: import scipy

In [4]: import scipy.fftpack

In [5]: a = numpy.random.random((6, 7, 8, 9))

In [6]: a.shape
Out[6]: (6, 7, 8, 9)

In [7]: numpy.fft.irfft(numpy.fft.rfft(a)).shape
Out[7]: (6, 7, 8, 8)

In [8]: numpy.fft.irfft(numpy.fft.rfft(a), a.shape[-1]).shape
Out[8]: (6, 7, 8, 9)

In [9]: scipy.fftpack.irfft(scipy.fftpack.rfft(a)).shape
Out[9]: (6, 7, 8, 9)
```

</details>
<br>

That said, I agree with others that the behavior of SciPy's `rfft`/`irfftn` functions are not intuitive. At a bare minimum documenting that users try using NumPy's `rfft`/`irfftn` instead would probably be a good idea.

xref: https://github.com/numpy/numpy/issues/8800

**Comment by larsoner** [comment]
I've come around to the (simpler) viewpoint that we should just, for now at least, cross-ref `np.ftt.rfft` from `scipy.fftpack.rfft` et al. I'll try to make a PR for this soon so it makes 1.0.

**Comment by larsoner** [comment]
This one is too big to fix for the impending 1.0 release, so I'm removing the milestone (though I did open a simple doc PR #7781 to help for 1.0)

**Comment by endolith** [comment]
[The benefit of scipy's rfft being faster than numpy's](https://github.com/scipy/scipy/issues/2487#issuecomment-135939343) appears to no longer be true (and this is without the pocketfft update?)

```
x = randn(65536)

timeit scipy.fftpack.rfft(x)
1.31 ms ± 56.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

timeit numpy.fft.rfft(x)
665 µs ± 72.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

x = randn(65536).astype('float32')

timeit scipy.fftpack.rfft(x)
1.13 ms ± 50.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

timeit numpy.fft.rfft(x)
334 µs ± 10.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

x = rand(65537)

timeit scipy.fftpack.rfft(x)
5.22 s ± 177 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

timeit numpy.fft.rfft(x)
29 ms ± 6.42 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

scipy.__version__
Out[9]: '1.2.1'

numpy.__version__
Out[10]: '1.16.2'
```

**Comment by Jeitan** [comment]
I was once a fan of scipy's fftpack *except* for the lack of rfftn and rfft's weird output, because on the machines I used it was way faster and more memory efficient (I profiled it once, and while they both had a memory spike during the fft, numpy's was 2 to 4 times higher than scipy's).  I don't have my profiler up and going atm, but I did do some timing tests on my current machine (Windows 64-bit) and it looks like after the advent of pocketfft, numpy is significantly faster:

This code:
```python
import timeit
import shlex
import numpy
import scipy
import numpy.random as random
import numpy.fft.fftpack as nfftp
import numpy.fft as nfft
import scipy.fftpack as scifftp

setup1 = ('from __main__ import random, nfftp, nfft, scifftp;'
         'x=random.randn(65536);')
setup2 = ('from __main__ import random, nfftp, nfft, scifftp;'
          'x2=random.randn(652,128)')

print('FFT')
print('scipy fftpack')
timeit.main(args=shlex.split(f"""-s'{setup1}' scifftp.fft(x)"""))
print('numpy fftpack')
timeit.main(args=shlex.split(f"""-s'{setup1}' nfftp.fft(x)"""))
print('numpy pockefft')
timeit.main(args=shlex.split(f"""-s'{setup1}' nfft.fft(x)"""))

print('RFFT')
print('scipy fftpack')
timeit.main(args=shlex.split(f"""-s'{setup1}' scifftp.rfft(x)"""))
print('numpy fftpack')
timeit.main(args=shlex.split(f"""-s'{setup1}' nfftp.rfft(x)"""))
print('numpy pockefft')
timeit.main(args=shlex.split(f"""-s'{setup1}' nfft.rfft(x)"""))

print('FFT2')
print('scipy fftpack')
timeit.main(args=shlex.split(f"""-s'{setup2}' scifftp.fft2(x2)"""))
print('numpy fftpack')
timeit.main(args=shlex.split(f"""-s'{setup2}' nfftp.fft2(x2)"""))
print('numpy pockefft')
timeit.main(args=shlex.split(f"""-s'{setup2}' nfft.fft2(x2)"""))

print('FFTN')
print('scipy fftpack')
timeit.main(args=shlex.split(f"""-s'{setup2}' scifftp.fftn(x2)"""))
print('numpy fftpack')
timeit.main(args=shlex.split(f"""-s'{setup2}' nfftp.fftn(x2)"""))
print('numpy pockefft')
timeit.main(args=shlex.split(f"""-s'{setup2}' nfft.fftn(x2)"""))

print('RFFTN')
print('numpy fftpack')
timeit.main(args=shlex.split(f"""-s'{setup2}' nfftp.rfftn(x2)"""))
print('numpy pockefft')
timeit.main(args=shlex.split(f"""-s'{setup2}' nfft.rfftn(x2)"""))

print('Numpy ver')
print(numpy.__version__)
print('Scipy ver')
print(scipy.__version__)
```
Yielded this output:
```
FFT
scipy fftpack
200 loops, best of 5: 1.47 msec per loop
numpy fftpack
100 loops, best of 5: 3.31 msec per loop
numpy pockefft
500 loops, best of 5: 681 usec per loop
RFFT
scipy fftpack
500 loops, best of 5: 908 usec per loop
numpy fftpack
200 loops, best of 5: 1.01 msec per loop
numpy pockefft
2000 loops, best of 5: 154 usec per loop
FFT2
scipy fftpack
20 loops, best of 5: 14.7 msec per loop
numpy fftpack
20 loops, best of 5: 14 msec per loop
numpy pockefft
200 loops, best of 5: 1.55 msec per loop
FFTN
scipy fftpack
20 loops, best of 5: 14.5 msec per loop
numpy fftpack
20 loops, best of 5: 13.9 msec per loop
numpy pockefft
200 loops, best of 5: 1.61 msec per loop
RFFTN
numpy fftpack
50 loops, best of 5: 6.37 msec per loop
numpy pockefft
500 loops, best of 5: 499 usec per loop
Numpy ver
1.16.2
Scipy ver
1.2.1
```

**Comment by rgommers** [comment]
@Jeitan thanks for that feedback. And yes we know, and are planning to switch over to Pocketfft as well soon.

**Comment by endolith** [comment]
So this is fixed in https://github.com/scipy/scipy/pull/10238 right?  The new `scipy.fft.rfft` is the same output as the numpy version, and `scipy.fft.rfftn` has been added?

**Comment by larsoner** [comment]
Yes I think it has been taken care of. Then #10361 moves all `signal` functions to use `scipy.fft` functions rather than `scipy.fftpack` or `numpy.fft`, and I'm going to update #9876 to use `scipy.fft` as well.

**Comment by fasiha** [comment]
Do `scipy.fft` and/or `numpy.fft` now have float32/complex64 support, like `scipy.fftpack`?
