### ISSUE TITLE
BUG: scipy.integrate.odeint ignores Ctrl-C

### ISSUE THREAD

**Issue by cjh57** [scipy/scipy#2515]
On 64-bit Windows 7, version 0.12.01b, installed from the Sourceforge superpack and running python from the command line, pressing Ctrl-C while odeint is running results in a message:

KeyboardInterrupt
odepack.error: Error occurred while calling the Python function named [name of function - I've tried it with several]

but it keeps going! It doesn't even exit when odeint finishes running, it just continues with the Python code as if nothing happened. So if odeint is running inside a tight loop, there is an infinitesimal chance of actually being able to interrupt execution, even when holding Ctrl-C down continuously.

**Comment by WarrenWeckesser** [comment]
I'm closing this issue. If someone finds that this problem persists, we can reopen it.
