### ISSUE TITLE
scipy.interpolate.UnivariateSpline (or a new superclass of it) needs a constructor that recreates a spline object from its knots and coefficients

### ISSUE THREAD

**Issue by jason-s** [scipy/scipy#2580]
Sure, I can pickle/unpickle a UnivariateSpline. But maybe I don't want to, maybe I have security concerns (don't trust arbitrary pickled data), or maybe want a Python-independent method of recording the spline knots and coefficients into a text file / database / whatever, and then later I need to recreate an identically-behaving Spline object.

Could you add a mechanism to create a UnivariateSpline object from the spline knots + coefficients, rather than the raw input data? Maybe this is better served by a new superclass of UnivariateSpline (straw man name: SplineSuperclass), where SplineSuperclass has the following methods:

- `__call__(x[, nu])` 	Evaluate spline (or its nu-th derivative) at positions x.
- `derivatives(x)` 	Return all derivatives of the spline at the point x.
- `get_coeffs()` 	Return spline coefficients.
- `get_knots()` 	Return positions of (boundary and interior) knots of the spline.
- `integral(a, b)` 	Return definite integral of the spline between two given points.
- `roots()` Return the zeros of the spline.

and SplineSuperclass's constructor takes in knots and coefficients, whereas UnivariateSpline does the smoothing to figure out the knots and coeffficients for input data.

**Comment by ev-br** [comment]
```
In [64]: x = np.arange(7)

In [65]: y = x**3

In [66]: from scipy.interpolate import BSpline, splrep

In [67]: spl = BSpline(*splrep(x, y))

In [68]: spl(x) - y
Out[68]: 
array([ -5.50824873e-17,   2.22044605e-16,  -8.88178420e-16,
         7.10542736e-15,   0.00000000e+00,   4.26325641e-14,
         0.00000000e+00])
```

And a `BSpline` instance has essentially all requested methods save `roots`. Enhancement requests for the `BSpline` interface are likely better done via a separate issue.
