### ISSUE TITLE
linkage() function mistakes distance matrix as observation vectors

### ISSUE THREAD

**Issue by hongbo-zhu-cn** [scipy/scipy#2614]
the document for scipy.cluster.hierarchy.linkage() function states that it accepts redundant distance matrix as input:

http://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html
"y : ndarray
A condensed or redundant distance matrix. A condensed distance matrix is a flat array containing the upper triangular of the distance matrix. This is the form that pdist returns. Alternatively, a collection of m observation vectors in n dimensions may be passed as an m by n array."

This feature of accepting redundant distance matrix as input is also introduced by many popular books like "SciPy and NumPy: An Overview for Developers" By Eli Bressert:
http://books.google.co.uk/books?id=c-xzkDMDev0C&pg=PA48&dq=scipy+linkage+input&hl=en&sa=X&ei=4BzUUZqpNoSbPaj3gLgN&ved=0CDgQ6AEwAQ#v=onepage&q=scipy%20linkage%20input&f=false

However, when distance matrix is specified as input to the linkage() function, it is silently considered to be observation vectors. This can be seen by reading the source code :
https://github.com/scipy/scipy/blob/master/scipy/cluster/hierarchy.py

If the input is a 2-dimensional matrix, it is not checked by predicate scipy.spatial.distance.is_valid_dm(). Rather, it is simply taken as observation vectors for hierarchical clustering. It may be also seen from the following example:

``` python
arr = scipy.array([[0,5],[1,5],[-1,5],[0,-5],[1,-5],[-1,-5], [-1.1,-5]])
pd = pdist(arr)
dm = squareform(pd)
linkage(pd)
linkage(dm)  # result is different from the previous 
```

I think this issue has relatively serious consequence if users do not check their clustering results carefully. 

I suggest: either update the documentation for linkage() function to reflect the real functionality, or add a predicate check using scipy.spatial.distance.is_valid_dm() if two dimensional matrix is given as input so distance matrix is processed properly in the linkage() function.

**Comment by Arnold1** [comment]
i have a 20 (number of features) x 8000 (number of samples) matrix.
will i need to calculate the distance matrix (pdist) and pass it to linkage?

**Comment by jolespin** [comment]
Has this been fixed yet?
