### ISSUE TITLE
poisson.pmf returns NaN if mu is 0

### ISSUE THREAD

**Issue by AllenDowney** [scipy/scipy#2618]
The Poisson PMF is well defined when mu is 0, it should be 0 for all k>0 and 1 for k==0.

But poisson.pmf fails (returns NaN) because it computes logpmf and then exponentiates:

    def _logpmf(self, k, mu):
        Pk = k*log(mu)-gamln(k+1) - mu
        return Pk

    def _pmf(self, k, mu):
        return exp(self._logpmf(k, mu))

    >>> scipy.stats.poisson.pmf(0, 0)
    nan
    >>> scipy.stats.poisson.pmf(1, 0)
    nan 
    >>> mu = 0
    >>> k = 1
    >>> scipy.stats.poisson.pmf(k, mu)
    nan
    >>> mu ** k * math.exp(-mu) / math.factorial(k)
    0.0
    >>> k = 0
    >>> mu ** k * math.exp(-mu) / math.factorial(k)
    1.0

**Comment by jcbozonier** [comment]
The Poisson PMF is defined at mu = 0 and for k = 0 it gives you 1 and k >= 1 it is 0. Running into this issue running a bayesian analysis. Any updates?
