### ISSUE TITLE
stats.distributions statistical power of test suite

### ISSUE THREAD

**Issue by josef-pkt** [scipy/scipy#2623]
In PR #2612 Ralf reduced the sample size in the test suite for the distributions.

Even reducing sample size to 100 didn't cause any failures.

Looking at the unittests in test_continuous_basic, mean, var and cdf are verified using statistical tests (t-test, a chisquare test and kstest).

If the sample size is small, then the power of these tests will be small also.
Since we use now fixed seeds in the unit tests, we will not see random failures. 

My guess is that 500 observations is still a good sample size for general unit tests, but will be too small to detect smaller numerical errors. (like the two bugs I found in numpy.random with the kstest.)

**Comment by mdhaber** [comment]
@josef-pkt We went ahead and closed this with gh-15724, but I'd still appreciate your thoughts there in case we missed something.
