### ISSUE TITLE
UnivariateSpline should support multiple y-values per x-point

### ISSUE THREAD

**Issue by Gscorreia89** [scipy/scipy#2638]
I'm experiencing problems with the Scipy interp1d function. I've got arrays with a number of points varying between 16000 and 250000 points. I can create the function for linear interpolation without any problem and I can interpolate a huge array of values on the fly. However if I select kind as cubic the processor just goes into a frenzy, computer almost crashes and memory starts going to almost 10Gb of use!

I'm currently converting a Matlab code to Python/Numpy-SciPy - there cubic interpolation was also used and it is extremely fast aka instantly, so computational efficiency shouldn't be a problem here!

Thanks in advance,

Goncalo

**Comment by ev-br** [comment]
`interp1d` now uses banded linear algebra, so the original issue with memory consumption is gone. As a side effect, `interp1d` now *does* accept multiple y values per x point:

```
In [53]: interp1d(x, np.c_[y, y].T)(x)
Out[53]: 
array([[   0.,    1.,    8.,   27.,   64.,  125.,  216.],
       [   0.,    1.,    8.,   27.,   64.,  125.,  216.]])

In [54]: x = np.arange(7)

In [55]: y = x**3

In [56]: interp1d(x, np.c_[y, y].T)(x)
Out[56]: 
array([[   0.,    1.,    8.,   27.,   64.,  125.,  216.],
       [   0.,    1.,    8.,   27.,   64.,  125.,  216.]])
``` 

In fact, this is `BSpline` and `make_interp_spline` which `interp1d` is now using under the hood, and I'd recommend using these directly. 
I think the issue can be safely closed.
