### ISSUE TITLE
(2D) Interpolation functions should work with complex numbers

### ISSUE THREAD

**Issue by rubenvb** [scipy/scipy#2650]
Right now it is a hassle to interpolate complex-valued data: you need to take care of real and imaginary parts manually. I'm sure this can be done more efficiently in library code than what I am naively doing now.

**Comment by arsenovic** [comment]
yes this is also a problem for me

**Comment by isaacgerg** [comment]
Also an issue for me.  Any plan on fixing this?

**Comment by ev-br** [comment]
Pull requests welcome, I'd say.

**Comment by mforbes** [comment]
While waiting for a PR, at least the docs could be updated to specify that `z` should be a real array.

**Comment by ev-br** [comment]
This seems to work for `interpn` / `RegularGridInterpolator` , see `test_complex` at  https://github.com/scipy/scipy/blob/main/scipy/interpolate/tests/test_interpolate.py#L2435 .
Adding complex value support to FITPACK does not sound worth the hassle.
Let's keep the issue open for gh-15357 and gh-7903 --- once the new methods are added to RGI, the issue can be closed IMO.

**Comment by ev-br** [comment]
Now that gh-15357 is in, I think this can be declared implemented. Closing, thanks all!
