### ISSUE TITLE
ENH: Fold fftconvolve into convolve/correlate functions as a parameter

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#2651]
As mentioned in https://github.com/scipy/scipy/pull/337 and https://github.com/numpy/numpy/issues/1858#issuecomment-9688656, I think `fftconvolve` ~~should be deprecated as a standalone function, and its~~ functionality should be incorporated into `convolve`, `correlate`, `convolve2d`, and `correlate2d`, enabled by a parameter.  The parameter should be able to force one implementation or another, but should also have an "automatic" default that chooses implementation based on the types and sizes of the inputs.

> FFT has several disadvantages: it does not work for object arrays, can be memory hungry, and slower when only a few values of the correlation is needed. https://github.com/numpy/numpy/issues/1858#issuecomment-9688657

(...as well as slower when one input is very small.)

So the automatic mode needs to take into account
* The types of the inputs
* The sizes of the inputs
* The size of the output (`maxlag` parameter https://github.com/numpy/numpy/pull/5978)

Syntax possibilities:

* `fft={True, False, 'auto'}` (as used in the (deprecated) STScI [convolve2d](http://docs.scipy.org/doc/scipy-0.7.x/reference/generated/scipy.stsci.convolve.convolve2d.html)/[correlate2d](http://docs.scipy.org/doc/scipy-0.7.x/reference/generated/scipy.stsci.convolve.correlate2d.html) functions)
* `method={'direct', 'fft', 'heuristic'}`
* `mode={'direct', 'fft', 'auto'}`  (as used in [Intel MKL library](https://software.intel.com/en-us/node/470732#TBL10-16))
* ...

**Comment by WarrenWeckesser** [comment]
FYI: The scikit-image developers are looking into something similar: https://github.com/scikit-image/scikit-image/pull/1792

**Comment by endolith** [comment]
I started to do this at one point, but it was confusing because `convolve` calls `correlate`, while `correlate2d` calls `_convolve2d`.

**Comment by scottsievert** [comment]
+1. I'd like to hide the implementation details from the user and a keyword argument seems to be the right method to allow control.

I'm the author of the scikit-image PR and we've fit a curve for the time ratio. We decide which convolution method to use based on the image and kernel size; maybe that should be the default method?

**Comment by endolith** [comment]
Closed by https://github.com/scipy/scipy/pull/5608.  Thanks, @stsievert !
