### ISSUE TITLE
BUG: step response not accurate at higher orders

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#2652]
A 6th order analog filter appears very distorted in scipy.signal.step compared to Octave:

    z = array([], dtype=float64)
    p = array([-2.8576, -2.8576, -2.8576, -2.8576, -2.8576, -2.8576])
    k = 544.49693870986994
    t_s, y_s = step((z, p, k), T=t)
    plot(t_s, y_s)

![scipy 6th order step response screwed up](https://f.cloud.github.com/assets/58611/846316/58597c0c-f40b-11e2-8e7a-7a5c792c6b31.png)

vs Octave:

    z = []
    p = [-2.8576  -2.8576  -2.8576  -2.8576  -2.8576  -2.8576]
    k = 544.49693870986994
    step(zpk(z, p, k), 8)

![octave step response](https://f.cloud.github.com/assets/58611/846311/305721d2-f40b-11e2-9f2c-f4de4982dc83.png)

Even 4th order filters are visibly inaccurate, settling at 1.02 instead of 1.00, which is not a very high-order filter

**Comment by jason-s** [comment]
which scipy version is this now part of?

**Comment by rgommers** [comment]
gh-4675 is part of the 0.16.0 release: http://docs.scipy.org/doc/scipy/reference/release.0.16.0.html#scipy-signal-improvements
