### ISSUE TITLE
move the linear operator interface towards that of matrices and ndarrays

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#2707]
See https://github.com/scipy/scipy/pull/2692#issuecomment-22284312.

I'd like linear operators to work with my code that expects 2d ndarrays, whenever the code doesn't attempt elementwise access.  But I don't have much of a clue how to implement this, and some possible implementations which could work initially might not be good long-term solutions (e.g. combinatorial explosions of type combinations, brittle inheritance hierarchies, etc.).

**Comment by rgommers** [comment]
I don't think this is actionable, let's close it. Thanks all!
