### ISSUE TITLE
Barycentric interpolation should allow evaluation of derivatives

### ISSUE THREAD

**Issue by davidshepherd7** [scipy/scipy#2725]
The scipy Krogh interpolation class allows the evaluation of derivatives of the interpolating polynomial but the barycentric interpolation class doesn't. No reason is mentioned for this discrepancy.

It should be possible to evaluate the derivatives in a similar manner to the interpolation of function values. This is discussed in section 9.3 of [Barycentric lagrange interpolation by Berrut and Trefethen](http://epubs.siam.org/doi/pdf/10.1137/S0036144502417715) (which is cited by the documentation as the paper for the implementation used).

I am prepared to implement this if needed, but seeing as the maths/algorithm seems fairly simple I am wondering if there is a good but undocumented reason why it hasn't been done already. Do any implementation details prevent it? Is there some subtle numerical stability issue? Or was it just not considered important previously?

**Comment by DaniGlez** [comment]
There is an approach to this issue that AFAIK doesn't run into any numerical issues.

1. Compute the differentiation matrix D of the node set with the Schneider-Werner formula (check, for example, the [CHQZ book](http://www.springer.com/us/book/9783540307259) or other papers/books on the topic)
2. Compute the derivatives of the interpolant at the nodes with the matrix-vector product D·(y values)
3. Interpolate these derivatives again with a barycentric interpolator.

As the derivative of an n-degree Lagrange interpolant is an (n-1)-degree polynomial, it can be exactly recovered by interpolation.

Is this practical for this class?

**Comment by ev-br** [comment]
On the face of it, this sounds reasonable. A draft implementation can be useful though. Are you interested in putting this in a pull request?

**Comment by ev-br** [comment]
To summarize the current status of this enhancement request: 
- The functionality was requested a couple of times over time, but so far nobody stepped in to actually implement it. 
- the paper which is referenced above ---  _Barycentric Lagrange Interpolation_, [Jean-Paul Berrut](https://epubs.siam.org/author/Berrut%2C+Jean-Paul) and [Lloyd N. Trefethen](https://epubs.siam.org/author/Trefethen%2C+Lloyd+N)
https://doi.org/10.1137/S0036144502417715 --- seems to have all the derivations.
- looking over the paper, implementing it seems reasonably straightforward, if requiring some effort.

So, pull requests are welcome.

**Comment by j-bowhay** [comment]
> * The functionality was requested a couple of times over time, but so far nobody stepped in to actually implement it.
> * the paper which is referenced above ---  _Barycentric Lagrange Interpolation_, [Jean-Paul Berrut](https://epubs.siam.org/author/Berrut%2C+Jean-Paul) and [Lloyd N. Trefethen](https://epubs.siam.org/author/Trefethen%2C+Lloyd+N)
>   https://doi.org/10.1137/S0036144502417715 --- seems to have all the derivations.
> * looking over the paper, implementing it seems reasonably straightforward, if requiring some effort.

As far as I could the Berrut and Trefethen paper only provides a method for computing the derivatives at the nodes which is not as general as the functionality offered by KroghInterpolator.

**Comment by DaniGlez** [comment]
> As far as I could the Berrut and Trefethen paper only provides a method for computing the derivatives at the nodes which is not as general as the functionality offered by KroghInterpolator.

Indeed, but you could do barycentric interpolation again on these values and you'd get the correct derivative (up to numerical precision), because the derivative of an Lagrange interpolant is a polynomial of smaller degree and thus it can be represented exactly by the same interpolation scheme. But I guess you'd have to choose how to implement it (compute the derivative interpolant when you get the first call for a derivative? Require an explicit invocation of a function to build it before usage?)

**Comment by j-bowhay** [comment]
> But I guess you'd have to choose how to implement it (compute the derivative interpolant when you get the first call for a derivative? Require an explicit invocation of a function to build it before usage?)

The former makes more sense to me
