### ISSUE TITLE
distribution methods add tmp

### ISSUE THREAD

**Issue by josef-pkt** [scipy/scipy#2823]
Can we add an optional tmp variable to the distribution methods?
Can this be made to work with the new argument parsing of the distribution specific methods?

use case: frozen distributions could store a tmp variable 
(a dict for example, dict won't work because of broadcasting in generic handling?)
see NIG PR for use case
see new multivariate normal for actual (similar) use 

this would be an alternative to temporarily attaching temporary variables as attributes

**Comment by ev-br** [comment]
With https://github.com/scipy/scipy/pull/9900, we went the other way, and removed all storing of intermediate results. Thus closing.
