### ISSUE TITLE
TestLSMR testBidiagonalA fails with more precise summation

### ISSUE THREAD

**Issue by juliantaylor** [scipy/scipy#2843]
I'm working on improving the accuracy of sum in numpy (see https://github.com/numpy/numpy/pull/3685).
When enabling pairwise summation test_lsmr.TestLSMR.testBidiagonalA fails with an error of 5e-7 instead of 5e-8 with naive summation.

The algorithm uses sum via np.linalg.norm, so I replaced the sum in that with an exact summation python provides (math.fsum) and it still fails with about the same error.
So I'm maybe the algorithm itself uses some error compensation method assuming naive sums (or its a coincidence).

Please advise if numpy should not change its sum or if the test can simply be relaxed.

**Comment by pv** [comment]
No test failures in recent years.
