### ISSUE TITLE
Solver for boundary value problems needed

### ISSUE THREAD

**Issue by davidrpugh** [scipy/scipy#2865]
MATLAB has several good solvers for BVPs and it would be nice to have a decent boundary value problem solver included in scipy.integrate. 

One possibility would be to wrap one of the following solvers...

http://people.sc.fsu.edu/~jburkardt/f77_src/bvpsol/bvpsol.f
http://people.sc.fsu.edu/~jburkardt/f77_src/colnew/colnew.f

**Comment by person142** [comment]
Thanks to @nmayorov there's `integrate.solve_bvp` since 0.18.
