### ISSUE TITLE
distribution._stats is not vectorized

### ISSUE THREAD

**Issue by josef-pkt** [scipy/scipy#2876]
discussed in PR gh-2849

two problems
- if moments and specific _stats are not available, then the generic calculation are not vectorize, if statements that assume scalar, and maybe other problems (no vec_moments ?)
- even if the distribution defines _stats that would work vectorized, the generic code has a bug 

(ignoring the first problem)
The second problem is because of the wrong calling sequence in stats, and I guess can be fixed relatively easily:

Warren's example

```
In [44]: invgamma.stats([0.0, 0.5, 1.0], 1, 0.5)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-44-36163480f388> in <module>()
----> 1 invgamma.stats([0.0, 0.5, 1.0], 1, 0.5)

/home/warren/local_scipy/lib/python2.7/site-packages/scipy/stats/distributions.pyc in stats(self, *args, **kwds)
   1612                     mu = self._munp(1.0,*goodargs)
   1613                 out0 = default.copy()
-> 1614                 place(out0,cond,mu*scale+loc)
   1615                 output.append(out0)
   1616 

ValueError: operands could not be broadcast together with shapes (3) (2) 
```

bug:
argsreduce is after the call to ._stats
a=0 is invalid shape parameter in Warren's example
._stats get's the full a (3 elements). When combining with loc and scale in line 1614, loc and scale only have valid args which means 2 elements in this case.

solution: argsreduce needs to go before ._stats.

some explanation
argsreduce is used in all methods to screen out invalid arguments and to broadcast the valid arguments to have common shape before calling the private methods.
The private .__xxx methods then only get valid arguments (that satisfy ._argcheck) and all arguments have the same shape.

In this case a=0 is removed (we set nans in the generic part), the two valid arguments together with loc and scale are broadcasted together.

In this case, the usage of argsreduce after the call to ._stats is screwed up.

We don't have currently any tests for `stats` with vectorized arguments, since this was not working. (enhancement not a bug)

**Comment by mdhaber** [comment]
@ev-br I've tried all the examples here that used to cause errors, and none of them do now. Also, `loc` and `scale` seem to be vectorized.
```
> stats.johnsonsb.stats(a=[1, 2, 3], b=[[4], [5]], loc=np.array([1, 2, 3])[:, None, None], scale=np.array([1, 2])[:, None, None, None])[0].shape
(2, 3, 2, 3)
```
as it should. Same with `reciprocal`, which has shapes-dependent support. Do you happen to know what fixed this? What do you think should be done to close this?

**Comment by mdhaber** [comment]
Seems like this is fixed, so I'll close. Please re-open if there's something I missed!
