### ISSUE TITLE
distributions.ncf numerical issues

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#2877]
- First of all, attempting to integrate `pdf` runs into slight precision issues: 

```
>>> stats.ncf.expect(lambda x: 1, args=(18, 7, 0.41))
/home/br/.local/lib/python2.7/site-packages/scipy/integrate/quadpack.py:293: UserWarning: The algorithm does not converge.  Roundoff error is detected
  in the extrapolation table.  It is assumed that the requested tolerance
  cannot be achieved, and that the returned result (if full_output = 1) is 
  the best which can be obtained.
  warnings.warn(msg)
0.9999974463736788
>>> stats.ncf.cdf(stats.ncf.b, dfn=18, dfd=7, nc=0.41)
1.0
```
- A possibly related issue is that `entropy` is a bit fishy (cf https://github.com/scipy/scipy/issues/2765)

Both of these might be related to the fact that `ncf` does not define explicit `pdf`
- 3rd and 4th moments are fishy: they are calculated by generic code, even though explicit expressions are available in the literature.

**Comment by WarrenWeckesser** [comment]
Well, it has been almost six years since @ev-br commented, maybe it's about time for a reply...

There are some mistakes in the Wolfram page.  There is a typo in the formula for μ₂', where the expression *(n + 1 + 2)* should be *(n₁ + 2)*.  Also, the expression for σ² incorrectly gives the *raw* second moment instead of the *central* second moment.

The "off by three" difference for the kurtosis sounds like the difference between "plain" kurtosis and *excess* kurtosis, which is simply the kurtosis minus 3.

**Comment by mdhaber** [comment]
As reported in [here](https://github.com/scipy/scipy/pull/14655#issuecomment-907809792),
on some platforms
`scipy/stats/tests/test_continuous_basic.py::test_cont_basic[500-200-ncf-arg74` fails with:
```
scipy/integrate/quadpack.py:400: in quad
    warnings.warn(msg, IntegrationWarning, stacklevel=2)
E   scipy.integrate.quadpack.IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
E     the requested tolerance from being achieved.  The error may be 
E     underestimated.
```
Thought this looked similar enough to share this issue.
Note that NCF is implemented in Boost, so it would be relatively easy to wrap now with Boostinator if that works better. @tupui

**Comment by mckib2** [comment]
Please try with Boost-provided `ncf`: gh-15763.  Would be interested to know if that error goes away or we need to replace some usage of the legacy `ncf` functions somewhere else

**Comment by mdhaber** [comment]
```
stats.ncf.expect(lambda x: 1, args=(18, 7, 0.41))  # 0.9999999999972788, no warnings.
```
Also no more `quadpack` error in `scipy/stats/tests/test_continuous_basic.py::test_cont_basic[500-200-ncf-arg74`. LGTM.

**Comment by mdhaber** [comment]
The skewness and kurtosis were garbage before, too. In main:
```
> stats.ncf.stats(18, 7, 0.41, moments='mvsk')
(array(1.43188889),
 array(1.74636847),
 array(1.67785106e+08),
 array(7.2856733e+09))
 
> dfn, dfd, nc = 27, 27, 0.416
> stats.ncf.stats(dfn, dfd, nc, moments='mvsk')
(array(1.09664),
 array(0.20138255),
 array(3.9832508e+10),
 array(-2.32826213e+11))
```

Now:
```
> stats.ncf.stats(18, 7, 0.41, moments='mvsk')
(array(1.43188889), array(1.74636847), array(9.87145096), array(nan))

> dfn, dfd, nc = 27, 27, 0.416
> stats.ncf.stats(dfn, dfd, nc, moments='mvsk')
(array(1.09664), array(0.20138255), array(1.36179204), array(6.70607544))
```

Wolfram alpha says that kurtosis is indeterminate if `dfd` is <=8.
![image](https://user-images.githubusercontent.com/6570539/157809255-0e61e173-9af9-4516-b85c-edf4586a46de.png)
so the `nan` above seems appropriate.
