### ISSUE TITLE
UnboundLocalError in scipy.interpolate.splrep

### ISSUE THREAD

**Issue by p3trus** [scipy/scipy#2883]
The documentation states that 

> There must have been a previous call with task=0 or task=1 for the same set of 
> data.

Doing it results in an UnboundLocalError in the second call

``` python
import numpy as np
from scipy.interpolate import splrep

x = np.arange(100)
y = np.arange(100)

spline1 = splrep(x, y, task=0)
spline2 = splrep(x, y, task=1)
```

with the following traceback

`````` python
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-1-2f4cd8293fca> in <module>()
      6 
      7 spline1 = splrep(x, y, task=0)
----> 8 spline2 = splrep(x, y, task=1)

C:\Python27\lib\site-packages\scipy\interpolate\fitpack.pyc in splrep(x, y, w, xb, xe, k, task, s, t, full_output, per, quiet)
    445         _curfit_cache['iwrk'] = empty((nest,),int32)
    446     try:
--> 447         t=_curfit_cache['t']
    448         wrk=_curfit_cache['wrk']
    449         iwrk=_curfit_cache['iwrk']

UnboundLocalError: local variable '_curfit_cache' referenced before assignment

I guess the error comes from this line(436)

```python
    if task <= 0:
        _curfit_cache = {}
``````

Because of it, I guess the name `_curfit_cache` is always local. An example to show what I mean follows

``` python
d = dict(key=1337)
def will_fail():
    if False:
        d = {}
    t = d['key']

def will_succeed():
    t = d['key']
will_succeed()
will_fail()
```

This will fail with a similar traceback

``` python
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-17-4fbf3d67062c> in <module>()
      8     t = d['key']
      9 will_succeed()
---> 10 will_fail()

<ipython-input-17-4fbf3d67062c> in will_fail()
      3     if False:
      4         d = {}
----> 5     t = d['key']
      6 
      7 def will_succeed():

UnboundLocalError: local variable 'd' referenced before assignment
```

**Comment by clementkng** [comment]
>  one has to remember to not use the mutable cache={} as the default value.

@pv I'm trying to pick up this PR from your proposed solution. I'm guessing the default value should be some sort of immutable dictionary i.e. a `frozenset`, but I'm not sure how SciPy would normally handle immutable dictionaries?

**Comment by pv** [comment]
The solution here is to either deprecate the feature --- it has never worked so nobody uses it.
Or, implement it in a different way that does not store data in a global variable.

**Comment by pv** [comment]
@clementkng: no, it would probably better to have `cache=None` as default and raise an error if the user does not provide it, because the dictionary is needed for storing data that needs to be reused later on.

**Comment by clementkng** [comment]
@pv Should I try removing all uses of the `_curfit_cache` global variable in my update of the existing PR? Or should I simply add support for the `cache` argument in my update?

**Comment by pv** [comment]
The use of global variables should be removed, and replaced by a variable passed in by the user.

**Comment by ev-br** [comment]
Has been fixed in gh-10500
