### ISSUE TITLE
stats.nanmean prints a warning for NaN only arrays

### ISSUE THREAD

**Issue by fuxb** [scipy/scipy#2898]
Example:

ipython

In [1]: from scipy import stats
In [2]: import numpy as np
In [3]: stats.nanmean([np.nan, np.nan])
/usr/lib/python2.7/dist-packages/scipy/stats/stats.py:274: RuntimeWarning: invalid value encountered in double_scalars
  return np.mean(x,axis)/factor
Out[3]: nan

**Comment by WarrenWeckesser** [comment]
The `stats` functions `nanmean`, `nanstd` and `nanmedian` were removed from scipy in version 0.18, so this issue is no longer relevant.
