### ISSUE TITLE
scipy.sparse.linalg.lsqr problems

### ISSUE THREAD

**Issue by felixlen** [scipy/scipy#2900]
There is a problem with lsqr with certain matrices. A minimal example is given by the following:

scipy.sparse.linalg.lsqr(np.array([1,4]),np.array([1]))

which fails due to acond being 0 and therefore having a float division with 0 in test3 = 1/acond. Changing the matrix a bit to scipy.sparse.linalg.lsqr(np.array([1,5]),np.array([1])) works. Matlab lsqr can handle both.

Furthermore is the output print(msg[0]) in the case arnorm==0 annoying. It should only be printed to stdout if show is set.

**Comment by mdhaber** [comment]
This doesn't fail on my machine. It gives the correct answer.

**Comment by felixlen** [comment]
Can confirm this on my machine with current scipy as well.
