### ISSUE TITLE
Feature Request: axis argument for stats.entropy function

### ISSUE THREAD

**Issue by jseabold** [scipy/scipy#2956]
Shouldn't be too much work. Maybe I'll have some time soon.

**Comment by anntzer** [comment]
Kindly bumping the issue.  At least the docs should say which is the default axis (looks like it's the last one?).

**Comment by MichaelMarien** [comment]
@rgommers is this still open and relevant (looking at the date of the original post)? In that case, you can assign it to me, looks straightforward to fix.

**Comment by ilayn** [comment]
@michaelmarien you can go ahead and open a PR by linking to this issue. Assignment is not needed.

**Comment by MichaelMarien** [comment]
Not clear to me where tests can be added? I see most of these helper functions are tested in the context of different distributions. However, the enhancement is about functionality for the `entropy` function in a standalone mode. None of the current helper functions seem to have standalone tests. Do we not add tests for these and if we do, where should they go?

**Comment by rgommers** [comment]
Here are the `stats.entropy` tests: https://github.com/scipy/scipy/blob/master/scipy/stats/tests/test_distributions.py#L1742
