### ISSUE TITLE
hyp1f1 precision issue

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#2957]
Reported on the mailing list a while ago:

    In [7]: scipy.__version__
    Out[7]: '0.14.0.dev-7c99934'

    In [8]: special.hyp1f1(0.5, 1.5, -709.7827128933)
    Out[8]: 0.033264594357227797

    In [9]: special.hyp1f1(0.5, 1.5, -709.7827128934)
    Out[9]: inf

Analysis and suggested fix: http://article.gmane.org/gmane.comp.python.scientific.user/32789

**Comment by nmayorov** [comment]
This issue has been fixed, better to close it.

**Comment by rgommers** [comment]
Also confirmed, closing.
