### ISSUE TITLE
Calculation of standard error is incorrect for scipy.stats.linregress

### ISSUE THREAD

**Issue by zhouheng** [scipy/scipy#2962]
To conduct linear regression of x=(0,1,2,3) and y=(0,2,4.5,6), I use the follow code:

from scipy.stats import  linregress
slope, intercept, r_value, p_value, std_err = linregress((0,1,2,3),(0,2,4.5,6))

and the "std_err" is 0.13228756555322888 (see the image below)
![untitled1](https://f.cloud.github.com/assets/5615115/1273750/8fe312f4-2d55-11e3-8c9e-bf35eb069f2a.png)

But if I calculate it in Matlab using the following code

p=polyfit([0:3],[0,2,4.5,6],1);
f=polyval(p,[0:3]);
std(f-[0,2,4.5,6])

, the answer is 0.2415 (see the image below)
![untitled2](https://f.cloud.github.com/assets/5615115/1273755/c883347c-2d55-11e3-8912-b0dfa16c4a51.png)

. Since I believe in Matlab, I think the calculation of scipy is wrone. So I think it is a bug and report it.

**Comment by NichtJens** [comment]
I have just been fooled by the problem discussed here. I wanted the error of the slope. However, I thought the `stderr` was the standard error of the linear regression. The latter would be what is \sigma_\epsilon here:

https://en.wikipedia.org/wiki/Regression_analysis#Linear_regression

Hence, I used this `stderr` to calculate the slopes' error via the formula for \sigma_\beta_1 in the Wikipedia article. In the current state this obviously leads to a wrong result.

I am pretty certain that the original intent of `stderr` was to provide the error of the linear regression, but it was later changed to the error of the slope, as can be seen here:

https://github.com/scipy/scipy/commit/7cd5cb0670c23c330fb3b4a5a609af021066595f#diff-cc307f50f4eb0f9917b55fdf1dbb9b8cL1664

As you all noticed already, this is also very apparent from the documentation of `stderr`.

From my point of view, the error of the intercept might be as interesting to a user. Therefore, having the more basic measure, the standard error of the whole regression, as a return value has some merit. In general, I would prefer if errors for both parameters would be returned. This would, however, change the number of return values, which might break code.

I think updating the docs according to the suggestion above, would be important - but only as a very first step. The code should actually be changed to return either only the error of the linear regression (as it did before the above cited commit) or the errors of both parameters. I don't see much value in the first error besides being able to calculate the other two, but one could certainly also return all three.

I am sorry if what I just wrote was discussed elsewhere already - I understand that this bug report is rather old. If a decision for any of the above solutions could be made, I would be more than willing to make the needed small changes to the code and submit a pull request.

**Comment by rgommers** [comment]
Thanks @NichtJens. The change you link to is almost 10 years old, so by now we cannot change the implementation anymore for backwards compatibility reasons. The way to go here is to clarify the docs, to be very explicit what is calculated, *and* to show an example of how a user would obtain the standard error of the linear regression.

**Comment by WarrenWeckesser** [comment]
The original issue reported here is about the meaning of the standard error returned by [`linregress`](http://scipy.github.io/devdocs/generated/scipy.stats.linregress.html).  That is now documented as the standard error of the estimated slope.  We also recently added standard error of the estimated intercept to the output of the function.  I'm closing this issue; if there is interest in adding additional calculations to the output of `linregress`, a new issue describing the feature request should be opened.
