### ISSUE TITLE
Rbf last argument of constructor

### ISSUE THREAD

**Issue by marcus21283** [scipy/scipy#2976]
would there be any advantage to allow the first n-1 arguments to be the same shape while the last argument only needs to have the same number of rows but could have multiple columns to represent multiple vectors of values or it is all the same to just create individual Rbf objects?  I have also found that the Rbf object is 2.7 mb for a grid 1530 points for 5 dimensions, thin_plate.  Trying to distribute 3000+ individual Rbf obejcts across 48 engines and the 2.7 mb is really cloging me up.  I end up having to recreate the Rbf object on the fly and discard it, but that is slower than i would like.  Any ohter suggestions on how I can optimize the process of interpolating  3000+ differnet objects?

**Comment by ev-br** [comment]
Looks abandoned for more than five years. Let's close this. Thanks anyway, @marcus21283, Ralf.
