### ISSUE TITLE
scipy.linalg.eig does not handle infinite eigenvalues

### ISSUE THREAD

**Issue by andrenarchy** [scipy/scipy#3054]
When a generalized eigenvalue problem ```A*x=lambda*B*x``` is solved, infinite eigenvalues may occur (if and only if ```B``` is singular). That's why the LAPACK function ```ggev``` (which is used by ```eig```/```_geneig```) returns two scalars ```alpha``` and ```beta``` corresponding to each eigenvalue, see http://www.netlib.org/lapack/lug/node35.html. Three cases may occur
1. If ```beta!=0``` then ```A*x=(alpha/beta)*B*x```.
2. If ```alpha!=0``` then ```B*y=(beta/alpha)*A*y```.
3. If ```alpha==beta==0``` then the matrix pair ```(A,B)``` is singular, see http://www.netlib.org/lapack/lug/node105.html.

Currently ```_geneig``` divides by ```beta``` which may result in a division by zero. A simple example is
```python
from scipy.linalg import eig
eig([[1]], [[0]])
```
This results in:
```python
/usr/lib/python2.7/dist-packages/scipy/linalg/decomp.py:57: RuntimeWarning: divide by zero encountered in true_divide
  w = (alphar + _I * alphai) / beta
/usr/lib/python2.7/dist-packages/scipy/linalg/decomp.py:57: RuntimeWarning: invalid value encountered in true_divide
  w = (alphar + _I * alphai) / beta
Out[2]: (array([ inf+nanj]), array([[ 1.+0.j]]))
```
So this case needs some special treatment. Perhaps it's a good idea to return the ```alphas``` and ```betas``` and let the user decide how to proceed.

**Comment by jrekier** [comment]
+1 
Such feature would be much appreciated.
