### ISSUE TITLE
ndimage.zoom does not work with masked array

### ISSUE THREAD

**Issue by mvogelsb** [scipy/scipy#3058]
#zoom does not respect masked arrays (result is all nan)
#
import numpy as np
import numpy.ma
import scipy.ndimage
a    = numpy.array([1,2,3,4,5,np.nan])
mask = numpy.isnan(a)
b    = numpy.ma.masked_array(a, mask=mask)
print a
print b
print scipy.ndimage.zoom(b,2)

**Comment by rgommers** [comment]
Masked array support in ``ndimage`` seems very much out of scope for that module, and I haven't seen any other questions/requests in this direction, so closing.

**Comment by karlwx** [comment]
I would find support for nan values very helpful. Are there any alternatives to ndimage.zoom out there that could work?

**Comment by karlwx** [comment]
I found a way to make it work well, at least for my applications. 

```python
import numpy as np
from scipy.ndimage import zoom

# given some 2-D data array, data:

if type(data) == np.ma.core.MaskedArray:
    mask = zoom(data.mask.astype('float'), 3) # grab the mask as 1.0 or 0.0, apply the zoom
    mask = np.where(mask>0.5, 1, 0) # if the result is greater than 0.5, the new point would fall in a masked region
    data = zoom(data.data, zoom_factor) # zoom on data
    data = np.ma.masked_array(data, mask=mask) # apply the new mask
else:
    data = zoom(data, 3)
```
