### ISSUE TITLE
brentq, nan returns, and bounds

### ISSUE THREAD

**Issue by jseabold** [scipy/scipy#3089]
I didn't find an issue for this already, but maybe there is one. This was also discussed in [this thread](http://mail.scipy.org/pipermail/scipy-user/2012-July/032578.html). If brentq (I don't know about the other root-finding functions) is given a function that returns a nan, then it bails out and returns 0.0 for the root, even if it's outside the bounds. In my case, one of the bounds returned a NaN. At the very least maybe there should be a check that the bounds return finite values? You can replicate it with this function. It's more complicated than it needs to be, but it does the job. I commented out the check in the function that prevents this behavior.

```
import numpy as np
from scipy import optimize, stats

def func(nobs, p1, p2, alpha, power, r=1., cont=False):
    q1 = 1 - p1
    q2 = 1 - p2

    p_bar = (p1 + r*p2)/(r+1.)
    q_bar = 1 - p_bar

    z_alpha = stats.norm.ppf(1 - alpha/2.)
    z_beta = stats.norm.ppf(power)

    if cont:
        n = nobs + 2/np.abs(p2+p1)
    else:
        n = ((z_alpha * np.sqrt((r+1) * p_bar * q_bar) +
              z_beta * np.sqrt(r * p1 * q1 + p2 * q2))/
             (r*(p2-p1)))**2

    #if nobs < 2/np.abs(p2-p1):
    #    raise ValueError("Cannot evaluate function for nobs smaller than"
    #                     " {}".format(2/np.abs(p2-p1)))

    z_beta = ((np.abs(p2 - p1) * np.sqrt(n - 2/np.abs(p2 - p1)) -
               z_alpha * np.sqrt(2 * p_bar * q_bar))/
              np.sqrt(p1 * q1 + p2 * q2))
    return stats.norm.cdf(z_beta) - power

optimize.brentq(func, 1, 1e6, args=(.7,.85,.05,.8, 1, True), full_output=True)
```

**Comment by Ankitgl** [comment]
Hello @uhohuhoh, 

Did you managed to resolve the "ValueError: f(a) and f(b) must have different signs" error. I am getting the same error and could not resolve it.

Thanks and Regards,
Ankit
