### ISSUE TITLE
Add support for multidimensional univariate splines to scipy.interpolate.UnivariateSpline and subclasses

### ISSUE THREAD

**Issue by ghost** [scipy/scipy#3115]
The [`scipy.interpolate.UnivariateSpline`](http://docs.scipy.org/doc/scipy-dev/reference/generated/scipy.interpolate.UnivariateSpline.html) class and its subclasses only support one-dimensional univariate spline-curves like [`scipy.interpolate.splrep`](http://docs.scipy.org/doc/scipy-dev/reference/generated/scipy.interpolate.splrep.html) does, but not multidimensional univariate splines like [`scipy.interpolate.splprep`](http://docs.scipy.org/doc/scipy-dev/reference/generated/scipy.interpolate.splprep.html).

I would be nice to have an object-oriented model for multidimensional univariate splines, even if not all features of the `scipy.interpolate.UnivariateSpline` class might be available. As far as I can see, at least evaluation and derivation should be available.

**Comment by ev-br** [comment]
> I would be nice to have an object-oriented model for multidimensional univariate splines, even if not all features of the scipy.interpolate.UnivariateSpline class might be available. As far as I can see, at least evaluation and derivation should be available.

And indeed, http://scipy.github.io/devdocs/generated/scipy.interpolate.BSpline.html#scipy.interpolate.BSpline
supports evaluation of differentiation of multidimensional splines.
Closing this one.
