### ISSUE TITLE
BVLS Solver

### ISSUE THREAD

**Issue by jseabold** [scipy/scipy#3130]
Related to #3129. It seems that long ago permission was obtained to use the BVLS routine for bounded least squares in scipy. It might make a nice addition to leastsq [**edit** it's linear only, an extension of nnls]. I can look into wrapping this, if desirable "soon-ish."

http://mail.scipy.org/pipermail/scipy-dev/2008-March/008524.html
http://people.sc.fsu.edu/~%20jburkardt/f_src/bvls/bvls.html

**Comment by ev-br** [comment]
This is being addressed in gh-5110.

**Comment by pv** [comment]
Was added in gh-5110
