### ISSUE TITLE
Odd casting behaviour of signal.filtfilt

### ISSUE THREAD

**Issue by alimuldal** [scipy/scipy#3158]
I've noticed that `signal.filtfilt(b, a, x)` always returns a float64 result, even when `b`, `a` and `x` are all float32 (float16 does not seem to be supported by `lfilter`).

```
import numpy as np
from scipy import signal

x = np.random.randn(1000)
b, a = signal.butter(8, 0.125)

print(signal.filtfilt( b, a, x).dtype)
# np.float64

print(signal.filtfilt( b.astype(np.float32), 
                       a.astype(np.float32), 
                       x.astype(np.float32)).dtype)
# still np.float64
```

Ordinarily this upcasting wouldn't be a big deal, but I'm currently trying to filter some very large arrays, and I'm running into nasty memory issues.

The problem seems to be in `signal.lfilter_zi(b, a)`, which gets called by `filtfilt` and always returns a float64 result regardless of what `dtype` `b` and `a` have.

**Comment by fasiha** [comment]
Can this behavior in `signal.filtfilt` and `signal.lfilter_zi` be fixed? I'll dig into why the latter always returns float64.

**Comment by Eric89GXL** [comment]
Sounds reasonable to me. I think the other filter functions try to retain the filter types. @e-q WDYT?

**Comment by WarrenWeckesser** [comment]
Preserving the dtype makes sense to me, at least when the input is `float32`.   A reasonable goal is for `filtfilt` to do as good a job at preserving the dtype as `lfilter` does.

**Comment by xhain** [comment]
I just ran into this too.
The coefficients from the filter design are already in `float64` - I didn't look at the `filtfilt` code yet, but since they are involved in the calculation of the filtered signal this might be one reason.

Merely casting the coefficients `b, a` to lower precision might cause instability though. So I think the most reasonable thing would be to maintain the type between input and output of `filtfilt`.

Question: How costly is casting back and forth? It might make sense to do the entire filtering operation in `float32` if the input is `float32` to avoid casting back and forth twice.

**Comment by roryyorke** [comment]
Using the attached script, I tested a few filter-related functions in scipy 1.4.1; it seems like the following return float64 when given all float32 arguments:

 - `decimate`
 - `filtfilt`
 - `lfilter_zi`
 - `sos2tf`
 - `sosfilt_zi`
 - `sosfiltfilt`
 
One function, `lfiltic`, returns float32 even when given some float64 arguments, but returns float64 when given all float64 arguments, and float32 when given all float32 arguments.

The following functions behave as expected, or at least as I expect: if any argument is float64, the result is float64, and if all arguments are float32, the result is float32:

 - `lfilter`
 - `savgol_filter`
 - `sosfilt`

```
decimate:
  (f32) -> f64, np.result_type f32
filtfilt:
  (f32,f32,f32) -> f64, np.result_type f32
lfilter_zi:
  (f32,f32) -> f64, np.result_type f32
lfiltic(3):
  (f32,f64,f32) -> f32, np.result_type f64
  (f64,f32,f32) -> f32, np.result_type f64
  (f64,f64,f32) -> f32, np.result_type f64
lfiltic(4):
  (f32,f32,f32,f64) -> f32, np.result_type f64
  (f32,f64,f32,f32) -> f32, np.result_type f64
  (f32,f64,f32,f64) -> f32, np.result_type f64
  (f64,f32,f32,f32) -> f32, np.result_type f64
  (f64,f32,f32,f64) -> f32, np.result_type f64
  (f64,f64,f32,f32) -> f32, np.result_type f64
  (f64,f64,f32,f64) -> f32, np.result_type f64
sos2tf[0]:
  (f32) -> f64, np.result_type f32
sos2tf[1]:
  (f32) -> f64, np.result_type f32
sosfilt_zi:
  (f32) -> f64, np.result_type f32
sosfiltfilt:
  (f32,f32) -> f64, np.result_type f32

Types as expected:
  lfilter[0]
  lfilter[1]
  savgol_filter
  sosfilt[0]
  sosfilt[1]
```

[check_types.zip](https://github.com/scipy/scipy/files/4535185/check_types.zip)

**Comment by ilayn** [comment]
Some of them are inherently not flexible due to calling some underlying C machinery and only available for floats.

**Comment by larsoner** [comment]
@roryyorke would you be up for making a PR to fix some of these? For example fixing `lfilter_zi` and `sosfilt_zi` would probably make fixing `filtfilt` and `sosfiltfilt` pretty easy.

**Comment by larsoner** [comment]
... one option is just to cast the result of `lfilter_zi` and `sosfilt_zi` after they're created, if necessary.
