### ISSUE TITLE
No multi-array broadcasting of ndimage.filters.correlate1d

### ISSUE THREAD

**Issue by mattijn** [scipy/scipy#3161]
Request for multi-array broadcasting of correlate1d. See discussion at SO: http://stackoverflow.com/a/20659646/2459096. scipy.ndimage.filters.correlate1d is currently only restricted to broadcasting of the first array.

**Comment by rgommers** [comment]
single request, no update in 6 years and seems low-prio. And Jaime had a useful answer on StackOverflow. so closing. thanks @mattijn
