### ISSUE TITLE
add `implicit none` to Fortran sources

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#3168]
I'd be surprised if this doesn't smoke out a bunch of obscure bugs.
A recent example is in gh-3155.

**Comment by richardjgowers** [comment]
https://gist.github.com/richardjgowers/46dc6650d80f36ca39c426531db9053e

Ok this is what I used for fftpack, maybe it's useful if any other modules need this

**Comment by ev-br** [comment]
Let's add this to the spring cleaning of stale issues.
