### ISSUE TITLE
Build failure on OS X from vecLib

### ISSUE THREAD

**Issue by fonnesbeck** [scipy/scipy#3194]
On OS X 10.9.1, I'm getting a build error on SciPy from master, apparently related to missing vecLib headers in Xcode. I have the most recent Xcode as well as the command line tools, and typically build SciPy from master every 2 weeks or so. Have not seen this one before:

    building 'arpack_scipy' library
    compiling C sources
    C compiler: gcc-4.2 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -arch x86_64 -arch x86_64 -arch i386 -pipe

    creating build/temp.macosx-10.9-intel-2.7/Users
    creating build/temp.macosx-10.9-intel-2.7/Users/fonnescj
    creating build/temp.macosx-10.9-intel-2.7/Users/fonnescj/Code
    creating build/temp.macosx-10.9-intel-2.7/Users/fonnescj/Code/scipy
    creating build/temp.macosx-10.9-intel-2.7/Users/fonnescj/Code/scipy/scipy
    creating build/temp.macosx-10.9-intel-2.7/Users/fonnescj/Code/scipy/scipy/_build_utils
    creating build/temp.macosx-10.9-intel-2.7/Users/fonnescj/Code/scipy/scipy/_build_utils/src
    compile options: '-Iscipy/sparse/linalg/eigen/arpack/ARPACK/SRC -I/Library/Python/2.7/site-packages/numpy-1.9.0.dev_e770f92-py2.7-macosx-10.9-intel.egg/numpy/core/include -c'
    gcc-4.2: /Users/fonnescj/Code/scipy/scipy/_build_utils/src/wrap_g77_abi_c.c
    In file included from /System/Library/Frameworks/vecLib.framework/Headers/vecLib.h:31,
                     from /System/Library/Frameworks/Accelerate.framework/Headers/Accelerate.h:20,
                     from /Users/fonnescj/Code/scipy/scipy/_build_utils/src/wrap_g77_abi_c.c:1:
    /System/Library/Frameworks/vecLib.framework/Headers/vBasicOps.h:153:23: error: immintri/System/Library/Frameworks/vecLib.framework/Headers/vBasicOps.h:153:23: error: immintri/System/Library/Frameworks/vecLib.framework/Headers/vBasicOps.h:153:23: error: immintri/System/Library/Frameworks/vecLib.framework/Headers/vBasicOps.h:153:23: error: immintri/System/Library/Frameworks/vecLib.framework/Headers/vBasicOps.h:153:23: error: immintrin.h: No such file or directory
    In file included from /System/Library/Frameworks/vecLib.framework/Headers/vecLib.h:31,
                     from /System/Library/Frameworks/Accelerate.framework/Headers/Accelerate.h:20,
                     from /Users/fonnescj/Code/scipy/scipy/_build_utils/src/wrap_g77_abi_c.c:1:
    /System/Library/Frameworks/vecLib.framework/Headers/vBasicOps.h:153:23: error: immintrin.h: No such file or directory
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /var/folders/yc/sh2m97w17_1dsm2bzmcj1v4m0000gn/T//ccpeo1uc.out (No such file or directory)
    In file included from /System/Library/Frameworks/vecLib.framework/Headers/vecLib.h:31,
                     from /System/Library/Frameworks/Accelerate.framework/Headers/Accelerate.h:20,
                     from /Users/fonnescj/Code/scipy/scipy/_build_utils/src/wrap_g77_abi_c.c:1:
    /System/Library/Frameworks/vecLib.framework/Headers/vBasicOps.h:153:23: error: immintrin.h: No such file or directory
    In file included from /System/Library/Frameworks/vecLib.framework/Headers/vecLib.h:31,
                     from /System/Library/Frameworks/Accelerate.framework/Headers/Accelerate.h:20,
                     from /Users/fonnescj/Code/scipy/scipy/_build_utils/src/wrap_g77_abi_c.c:1:
    /System/Library/Frameworks/vecLib.framework/Headers/vBasicOps.h:153:23: error: immintrin.h: No such file or directory
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /var/folders/yc/sh2m97w17_1dsm2bzmcj1v4m0000gn/T//ccpeo1uc.out (No such file or directory)
    error: Command "gcc-4.2 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -arch x86_64 -arch x86_64 -arch i386 -pipe -Iscipy/sparse/linalg/eigen/arpack/ARPACK/SRC -I/Library/Python/2.7/site-packages/numpy-1.9.0.dev_e770f92-py2.7-macosx-10.9-intel.egg/numpy/core/include -c /Users/fonnescj/Code/scipy/scipy/_build_utils/src/wrap_g77_abi_c.c -o build/temp.macosx-10.9-intel-2.7/Users/fonnescj/Code/scipy/scipy/_build_utils/src/wrap_g77_abi_c.o" failed with exit status 1

I am setting the following flags before building:

    export MACOSX_DEPLOYMENT_TARGET=10.9
    export CFLAGS="-arch x86_64"
    export ARCHFLAGS="-arch x86_64"
    export FFLAGS="-static -ff2c"
    export LDFLAGS="-Wall -undefined dynamic_lookup -bundle -arch x86_64"
    export PYTHONPATH="/Library/Python/2.7/site-packages/"
    export CC=gcc-4.2
    export CXX=g++-4.2

**Comment by pv** [comment]
Fixed by gh-4396
