### ISSUE TITLE
Singular matrix C in LSQ subproblem (scpipy) slsqp

### ISSUE THREAD

**Issue by altairtoral** [scipy/scipy#3202]
I'm working with the fmin_slsqp function of scipy and I'm getting the "Singular matrix C in LSQ subproblem (Exit mode 6)" after one or two iterations. Unfortunatelly the documentation for this function is not pretty deep and I have no clue what does this error message means so I can modify my code and keep debugging. I checked the original paper from Dieter Kraft in which the slsqp algorithm is based and found no Matrix C. Could someone pleas point me in the right direction where I could find a formal mathematical description of the exit modes?

Thanks and kind regards.

**Comment by balakumar-s** [comment]
@altairtoral Did you find out the reason? I found online that this error happens when the Hessian is 0( making it a linear program) but my function is continuous and has an Hessian.

**Comment by pv** [comment]
Closing (not actionable)
