### ISSUE TITLE
Scipy.opimize.fmin_powell direc argument syntax unclear

### ISSUE THREAD

**Issue by Void2258** [scipy/scipy#3220]
There is no information on how the direc argument of fmin-powell is supposed to be entered. All the scipy documentation for fmin_powell says is

```
direc : ndarray, optional
           Initial direction set.
```

I thought that by giving direc=(0.1,0.1,1), I was telling it to start with step sizes of 0.1 for the first two fitting parameters and 1 for the third, which are needed in my case since the 3rd parameter is not sensitive to step sizes of 0.1. However, with this code it starts with 0.1 for all of the fitting parameters. If I try direc=(1,0.1,1), it uses an initial step of 1 for all parameters which destroys the fit, as the second parameter has a range of (0,1) and results in a division by zero if it ever goes negative (if the step is 0.1, it sees the bad negative if it hits it and steps back to positive). 

We need a clearer explanation of how this argument works.

**Comment by srtlg** [comment]
Sorry, to re-open this.  I would really prefer Void2258's documentation.  I've just used a single N-elements vector and it kind of worked, only in the special case where `(fx > fx2)` and `if t < 0.0` it breaks.  Which is difficult to understand without this thread.
