### ISSUE TITLE
Feature:Computing jordan normal matrix

### ISSUE THREAD

**Issue by ccsv** [scipy/scipy#3221]
This would either go under numpy.linalg or Scipy in Decompositions.
The Jordan Normal form of a matrix should either be a function or an option for some of the eigen equations.

There has also been request for this on stackoverflow:

http://stackoverflow.com/questions/20312216/compute-jordan-normal-form-of-matrix-in-python-numpy

**Comment by JGameCreation** [comment]
Wouldn't it be possible to introduce some epsilon for the equality of eigenvalues as a parameter? It is slightly complicated by the eigenvalues being complex but it should still be possible.

**Comment by ilayn** [comment]
No unfortunately Jordan forms are not computable in a numerically stable way.
