### ISSUE TITLE
weave inline missing header msvc

### ISSUE THREAD

**Issue by bbudescu** [scipy/scipy#3236]
When trying to use msvc with weave I get the following error:
C:\Python27\lib\site-packages\scipy\weave\blitz\blitz/bzconfig.h(15) : fatal error C1083: Cannot open include file: 'blitz/ms/bzconfig.h': No such file or directory

**Comment by majidaldo** [comment]
yup google led me to this problem. from spearmint using msvc.

**Comment by bbudescu** [comment]
Can't say I remember, but it seems I got the missing file / a replacement from somewhere.

**Comment by majidaldo** [comment]
@bbudescu  thx. i tried that. the compilation progressed but still got an error which i think has to do with 64-bit windows.

sigh. can't believe we still have to deal with this in windows in 2015.

**Comment by person142** [comment]
Closing since weave is no longer a part of SciPy. This issue is now tracked at https://github.com/scipy/weave/issues/7.
