### ISSUE TITLE
corner cases in `numpy.log1p` and friends

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#3242]
A corner case with `np.log1p(np.inf)`  being a `nan` has been reported on Windows:
https://github.com/numpy/numpy/issues/4225

At the same time `scipy.special.log1p(np.inf)` has been reported to return a correct value, `np.inf`, https://github.com/scipy/scipy/pull/3225.

Apparently, `expm1` is affected in a similar way. Possibly `boxcox`/`boxcox1p`. 

An immediate fix in gh-3225 was to replace `np.log1p` with `scipy.special.log1p`. This could/should probably be applied across the whole scipy codebase.

**Comment by person142** [comment]
This was fixed in https://github.com/numpy/numpy/pull/4415 and backported to 1.8 in https://github.com/numpy/numpy/pull/4416. Since the minimum NumPy version for 0.19 is 1.8, this can be closed.
