### ISSUE TITLE
Dead link on documentation

### ISSUE THREAD

**Issue by sieben** [scipy/scipy#3250]
I wanted to consult the source code of interpolate univariate at the following link : 
http://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.UnivariateSpline.html#scipy.interpolate.UnivariateSpline

But the source code gave me a dead link : 
http://docs.scipy.org/doc/scipy/reference/generated/scipy-interpolate-UnivariateSpline-1.py

**Comment by person142** [comment]
I wonder if @pv could shed any light on removing the "Source Code" links? Based on

https://github.com/matplotlib/matplotlib/blob/57e480950238db21b6560dfcac61666ce991a9c7/lib/matplotlib/sphinxext/plot_directive.py#L89

I'm guessing it involves putting

``plot_html_show_source_link = False``

in the right place, but putting it here

https://github.com/scipy/scipy-sphinx-theme/blob/c466764e2231ba132c09826b5b138fffa1cfcec3/conf.py#L51

doesn't seem to do anything for me locally. I wondered if this was because we are perhaps using numpydoc's patched version of `plot_directive` (are we?), but patching the numpydoc source didn't seem to do anything either.

**Comment by pv** [comment]
Yes, it's just a matter of setting the option

**Comment by fepegar** [comment]
Isn't it possible to make them work? I find it convenient to be able to copy the whole piece of code instead of having to do it by chunks.

**Comment by sieben** [comment]
Doing a make linkcheck inside the doc folder would show all similars broken/redirect links

**Comment by rgommers** [comment]
> Isn't it possible to make them work?

It is, and it's handy indeed. I just checked that these ``.py`` files are generated in the place that the link points to with ``make html``. So ``make dist`` is probably doing something slightly different.

> Doing a make linkcheck ...

these are hundreds of autogenerated links, so that doesn't work

**Comment by rgommers** [comment]
okay, had a closer look. nothing is wrong in the code for building the docs. I get the links locally, and also on CircleCI doc builds the ``.py`` files show up and are linked to correctly: https://1000-1460385-gh.circle-artifacts.com/0/home/ubuntu/scipy/doc/build/html-scipyorg/generated/scipy.interpolate.UnivariateSpline.html#scipy.interpolate.UnivariateSpline

The 0.17.0 docs are OK as well: http://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.interpolate.UnivariateSpline.html#scipy.interpolate.UnivariateSpline

The 0.18.0 ones are not though. So I guess it's a case of picking up the wrong version of Sphinx or ``plot_directive`` sometimes. This needs checking for the next release, that at the time of upload of the new docs things are working. Or @ev-br maybe you can check your Sphinx and MPL versions now?

**Comment by ev-br** [comment]
There's some difference between `make html-scipyorg` which generates `build/html-scipyorg/generated/*py` files and `make dist` which does not seem to, at least on my machine. Ralf, when you say you get the links locally, which command do you use? 

I'm using python 2.7, MPL 1.5.1 and sphinx 1.2.3 --- this what was used for build 0.18.0 and 0.18.1. Not sure about 0.17.0 anymore.

**Comment by ev-br** [comment]
In general, I'm not sure how useful these *py files are really, compared to clicking `<<<` several times and copying a text from the page. The files themselves need patching to add `import numpy as np` anyway. (Plus, locating them on the file system; plus a cognitive load of figuring out that they are actually the same as what's on the page)

**Comment by rgommers** [comment]
> Ralf, when you say you get the links locally, which command do you use? 

I was checking ``make html-scipyorg``. Just tried ``make dist``, but it dies horribly thanks to a ``setuptools`` issue. One more thing to fix: the usage of ``bdist_egg`` is a bit outdated....

**Comment by rgommers** [comment]
No build issue, so removing the 0.19.0 milestone. ``>>>`` toggling is not critical for this release
