### ISSUE TITLE
Problems with stats.distributions.genextreme

### ISSUE THREAD

**Issue by ligon** [scipy/scipy#3276]
Some problems with `genextreme` were identified in gh-1294, but were never satisfactorily resolved; problems are also mentioned in gh-3258.  Another problem is that though genextreme should be defined for negative values of the shape parameter, it is not. 

There seem to be issues with the support of the genextreme distribution even for non-negative values of the shape parameter, when loc and/or scale take something other than their default values.

Finally, the distributions `weibull_max`, `gumbel`, and `frechet` all ought to be special cases of genextreme, as the shape parameter is negative/zero/positive, but this equivalence is presently broken.

**Comment by WarrenWeckesser** [comment]
Closing.  As @pbrod noted back in 2014, one can easily verify that `genextreme` works as expected, as long as one understands that the SciPy parameter `c` is the opposite sign of the shape parameter used in the [wikipedia article](https://en.wikipedia.org/wiki/Generalized_extreme_value_distribution) and in texts such as "Modelling Extreme Events" by Embrechts, Klüppelberg and Mikosch, and "An Introduction to Statistical Modeling of Extreme Values" by Stuart Coles.  This less common convention is noted in the docstring of `genextreme`.
