### ISSUE TITLE
Feature: Missing Goodness of Fit test

### ISSUE THREAD

**Issue by ccsv** [scipy/scipy#3291]
So far I looked at many goodness of fit test and found them to be in either either `scipy` or `statsmodel` but there are three that I can't find:
- Hosmer-Lemeshow test http://en.wikipedia.org/wiki/Hosmer-Lemeshow_test
- Cramer-von Mises criterion (1 and 2 sample) http://en.wikipedia.org/wiki/Cram%C3%A9r%E2%80%93von_Mises_criterion
- Shapiro–Francia test
- Jarque–Bera (Not sure but it might be in statsmodel)

Should they be added?

Here is what is already present and where they are found:
Chisquare: `scipy`

Power divergence: `scipy`, `statsmodel`(as power_discrepancy) [Handles  Freeman-Tukey, Pearson, Cressie-Read, Neyman, Log Likelihood (G-test), or Power discrepancy chi ]

Discrete Chi-square test: `statsmodel`

Friedman test: `scipy`

Kolmogorov–Smirnov test: `scipy` (both one and two sample) `statsmodel`(one sample)

Lillifors test: `statsmodel`

Anderson Darling test: `scipy`, `statsmodel`

Shapiro-Wilk test: `scipy`

Jarque–Bera test: `statsmodel`(maybe?)

D'Agostino's K-squared test: `scipy`

**Comment by pvanmulbregt** [comment]
Is there an open request here?
In particular, commentary at the end of the reference http://en.wikipedia.org/wiki/Hosmer-Lemeshow_test suggests that Hosmer-Lemeshow test may have multiple limitations and other tests may now be recommended instead.

**Comment by mdhaber** [comment]
> Is there an open request here?

We still don't have two of the tests listed at the top. But based on some reading, they are not necessarily better than what we do have.

>  But I suspect that there are more, and then you have to go figure out which ones are used more and/or the most relevant.

Agreed. If there is a particular test to be added due to it's superiority over existing tests, let's add it. But I'll close this until we identify that test.

**Comment by chrisb83** [comment]
I agree to close the issue: no need to add the two tests at the moment.
