### ISSUE TITLE
request additional truncate mode for dendrogram

### ISSUE THREAD

**Issue by jctobin** [scipy/scipy#3294]
scipy.cluster.hierarchy.dendrogram truncate_mode='levels' does not have the same inputs as Mathematica's TruncateDendrogram function. The documentation for TruncateDendrogram indicates that it can take two parameters as input (1) whereas truncate_mode='levels' can only take one number as input(2,3). So the two functions may do similar things but they do not correspond to one another. Perhaps I am misunderstanding one or either of the functions, but they seem and respond differently. 

*Mathematica's current TruncateDendrogram allows for more control, so I would recommend adjusting truncate_mode='levels'/allowing two inputs for p.

1.http://reference.wolfram.com/mathematica/HierarchicalClustering/ref/TruncateDendrogram.html
2.http://students.mimuw.edu.pl/~pbechler/spdoc/generated/scipy.cluster.hierarchy.dendrogram.html --scipy documentation
3.https://github.com/bennihepp/yaca/blob/master/src/gui/dendrogram.py --further details of the function

**Comment by rgommers** [comment]
Some of those links don't work anymore, but it's clear that mode ``'mtica'`` does not behave like Mathematica. Also not for a single ``p`` value - Mathematica will display ``p`` *leaves*, while ``dendrogram`` displays ``p`` *levels*. A level includes all nodes with ``p`` merges from the last merge (so typically many more leaves than levels).

So this is an enhancement request for a new truncation mode. It should use ``truncate_mode='level'`` with ``p`` a 2-sequence indicating the lowest and highest level to display. This is not completely trivial to implement; all other modes include start from the final merge.

I cleaned up the docs for ``truncate_mode`` a bit in gh-6643. If someone wants to implement this new mode that sounds fine, but it doesn't look high-prio to me.

**Comment by rgommers** [comment]
this is a low-prio feature request, no need to keep it around. can be searched for if anyone is looking for the Mathematica equivalent. closing, thanks all
