### ISSUE TITLE
mquantiles for numpy.matrix input returning first entries of matrix

### ISSUE THREAD

**Issue by SEichstdt** [scipy/scipy#3324]
The function **mquantiles** in scipy.stats.mstats does not throw an error when the input _a_ is of type numpy.matrix. However, instead of calculating the quantiles, the method returns the first _len(prob)_ values of the sorted matrix.

**Comment by mdhaber** [comment]
I don't think think this will be fixed. 8 years without comment and both `np.matrix` and `mstats` are on their way out.
Would you agree @tirthasheshpatel?

**Comment by tirthasheshpatel** [comment]
Yup, `np.matrix` is long outdated and `mstats` is being replaced by `_axis_nan_policy_factory`. So, +1 for closing such issues.
