### ISSUE TITLE
incorrect p-value for mstats.skewtest()

### ISSUE THREAD

**Issue by bulli92** [scipy/scipy#3328]
`mstats.skewtest` returns an invalid p-value compared to the `stats.skewtest`

Tests have been implemented, but a fix has been postponed due to difficulties in supporting also 2D data.

For further details see discussion here: https://github.com/scipy/scipy/pull/3084

It is suggested to address this problem _after_ the corresponding unittests have been incorporated from the PR in https://github.com/scipy/scipy/pull/3084

**Comment by WarrenWeckesser** [comment]
Is this still an issue? If so, does anyone have an example that demonstrates the problem?

The `assert` statements in this script pass:
```
import numpy as np
from scipy.stats import skewtest
from scipy.stats import mstats


a = np.array([[ 2,  8,  9,  5,  5,  1,  1, 11, np.nan],
              [10,  5,  6,  7,  4,  5,  7,  1, np.nan],
              [ 6,  9,  4,  4,  7,  7,  5,  1, np.nan]])

m = np.ma.masked_array(a, mask=np.isnan(a))

astat, ap = skewtest(a, axis=1, nan_policy='omit')

mstat, mp = mstats.skewtest(m, axis=1)

assert (astat == mstat).all()
assert (ap == mp).all()
```

**Comment by WarrenWeckesser** [comment]
Answering my own question: in https://github.com/scipy/scipy/pull/3084#issuecomment-34868468, @josef-pkt commented that the only problem with `skewtest` was a missing `abs`.  That was fixed back in https://github.com/scipy/scipy/commit/7dd9522a4706675ee6282f680bb1889bffecf486.

So I'm closing the issue.
