### ISSUE TITLE
Add consistent out-of-bounds behaviour to scipy.interpolate

### ISSUE THREAD

**Issue by andreas-h** [scipy/scipy#3350]
Currently, the out-of-bounds behaviour of the various classes/functions in scipy.interpolate is not consistent. Sometimes, there are `bounds_error=False|True` and `fill_value` kwargs, sometimes there's just a `ext` kwarg which takes integer values.

From a user perspective, it would be nice if all interpolation functions/classes _could_ be used with consistent `bounds_error` / `fill_value` semantics.  This could be reached by adding these two kwargs where they're not currently implemented (e.g., splev). Or, we leave the "low-level" FITPACK wrappers alone and just add out-of-bounds behaviour to the newer interfaces, like UnivariateSpline.

**Comment by ev-br** [comment]
PPoly-style classes have a consistent `extrapolate` keyword for a while now. Older classes either have `ext` keyword or are probably frozen by back compat. Seems this is mostly done, let's close this. @andreas-h would you mind?
