### ISSUE TITLE
beta distribution sf

### ISSUE THREAD

**Issue by josef-pkt** [scipy/scipy#3352]
I think we can get the sf and isf of beta directly by using symmetry of arguments, i.e. reverse alpha and beta and use cdf/btdtr  and ppf/btdtri

Not sure how much it helps for precision, just looking at the class and playing with some corner case examples for numpy issue 2056 (problem in rvs for small shape parameters)

**Comment by SwapnilDreams100** [comment]
Hi I wish to contribute to this issue, Its my first time at scipy. Can someone please guide me how to go about it?

**Comment by rgommers** [comment]
@SwapnilDreams100 welcome!

This is not really an easy-fix, I'm sorry. I'd have to really look into the details to give more guidance than the first sentence of the issue description. I suggest picking a different issue.
