### ISSUE TITLE
beta distribution rvs for small shape parameters returns nan

### ISSUE THREAD

**Issue by josef-pkt** [scipy/scipy#3354]
This is the same issue as https://github.com/numpy/numpy/issues/2056

scipy beta.rvs uses numpy

in scipy we could work around the problem by using generic function using ppf for random number generation

This seems to work:

```
>>> stats.beta._size = 1000
>>> x = stats.distributions.rv_continuous._rvs(stats.beta, alpha, beta)
>>> np.isnan(x).sum()
0
>>> (x > 1-1e-10).sum()
161
>>> (x < 1e-10).sum()
839
```

```
>>> alpha, beta
(7.1e-06, 4.22e-05)
>>> alpha / (alpha + beta) * 1000
144.01622718052738
>>> beta / (alpha + beta) * 1000
855.9837728194726
```

**Comment by ev-br** [comment]
I wonder if https://github.com/numpy/numpy/pull/5858 fixes it for numpy 1.10

**Comment by jaimefrio** [comment]
I have closed the numpy issue, it should indeed be fixed.

**Comment by argriffing** [comment]
> This is the same issue as https://github.com/numpy/numpy/issues/2056

.

> I have closed the numpy issue, it should indeed be fixed.

OK, I'll close this corresponding scipy issue.
