### ISSUE TITLE
Please add Sphinx search field to online scipy html docs

### ISSUE THREAD

**Issue by cdeil** [scipy/scipy#3372]
Currently there is no way to run the sphinx search for the [scipy docs](http://docs.scipy.org/doc/scipy-dev/reference/)?

I use this all the time for Sphinx documentation and find it very useful.

Can this be added?

**Comment by JakobJakobson** [comment]
+1

**Comment by JakobJakobson** [comment]
I think this can be closed as #8805 implemented the search field.
