### ISSUE TITLE
reverse Cuthill–McKee algorithm (RCM) for sparse matrices

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#3424]
This is [implemented](https://github.com/qutip/qutip/blob/master/qutip/cy/graph_utils.pyx) using sparse matrices in [qutip](https://github.com/qutip/qutip)([license](https://github.com/qutip/qutip/blob/master/LICENSE.txt)) as [mentioned](http://mail.scipy.org/pipermail/scipy-dev/2014-February/019589.html) on the mailing list and [defined](http://en.wikipedia.org/wiki/Cuthill%E2%80%93McKee_algorithm) on Wikipedia.  The idea is to permute graph vertices to reveal a small graph [bandwidth](http://en.wikipedia.org/wiki/Bandwidth_(matrix_theory)).

It is also [implemented](https://github.com/networkx/networkx/blob/master/networkx/utils/rcm.py) in networkx 1.6+ using graph representations like dicts of dicts that do not drop into cython, so it should be easy to test.

**Comment by perimosocordiae** [comment]
This was added by #3751, so this issue can be closed now.
