### ISSUE TITLE
stats: rename ppf -> icdf or quantile?

### ISSUE THREAD

**Issue by jseabold** [scipy/scipy#3436]
Just a thought. Deprecate the name `ppf` in favor or `icdf` for inverse cdf or `quantile`. I think this is a major pain point for new users of `scipy.stats`. It certainly was, and at times continues to be, for me. I still find `ppf` to be a curious choice even after several years. These latter two terms seem to be much more commonly used.

**Comment by sethtroisi** [comment]
This name change never happened. If it was to happen it would need a new vote / issue.

**Comment by mdhaber** [comment]
Oh what a world it would be!
