### ISSUE TITLE
scipy.special.comb seems to be unnecessarily slow

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#3449]
see http://mail.scipy.org/pipermail/scipy-dev/2014-March/019690.html

I'm not very experienced with Cython but would it make sense to turn this function into a Cython ufunc if it can speed up 10x or more?  I wonder if there could also possibly be a more clever algorithm for computing `comb()` that uses some identities like (n choose k) == (n choose n-k) to use fewer loop iterations or to reduce the size of intermediate quantities in the computation.

**Comment by alvations** [comment]
Another poke at the `comb()`: http://stackoverflow.com/questions/33468821/is-scipy-misc-comb-faster-than-an-ad-hoc-binomial-computation
