### ISSUE TITLE
PchipInterpolator sets slopes at edges differently than Matlab's pchip function

### ISSUE THREAD

**Issue by Stretch97** [scipy/scipy#3453]
I am under the impression that PchipInterpolator is supposed to behave similar to the pchip function in Matlab.  It appears to set the slopes differently at edge knots.  For example, the following code

    import numpy as np
    import scipy.interpolate
    import matplotlib.pyplot as plt
    x = np.array([0.0, 0.1, 0.25, 0.35]);
    y1 = np.array([279.35, 0.5e3, 1.0e3, 2.5e3]);
    y2 = np.array([279.35, 2.5e3, 1.50e3, 1.0e3]);
    pchip_obj1 = scipy.interpolate.PchipInterpolator(x, y1)
    pchip_obj2 = scipy.interpolate.PchipInterpolator(x, y2)
    xi = np.arange(x[0],x[-1],0.001)
    yi1 = pchip_obj1(xi)
    yi2 = pchip_obj2(xi)
    plt.plot(xi,yi1,xi,yi2)

produces the following plot
![scipy_pchip](https://f.cloud.github.com/assets/4099759/2427124/94deccbc-abd6-11e3-9def-994a64fb6daf.png)

Here is the equivalent code in Matlab

    x = [0.0, 0.1, 0.25, 0.35];
    y1 = [279.35, 0.5e3, 1.0e3, 2.5e3];
    y2 = [279.35, 2.5e3, 1.50e3, 1.0e3];
    xi = x(1):0.001:x(end);
    y1i = pchip(x,y1,xi);
    y2i = pchip(x,y2,xi);
    figure;
    plot(xi,y1i,xi,y2i)

and here is the corresponding plot

![matlab_pchip](https://f.cloud.github.com/assets/4099759/2427130/c20dcf4e-abd6-11e3-850a-be5109268abc.png)

Clearly, the green curve has a different slope on the left edge in Scipy than in Matlab.  Similarly, the blue curve has a different slope on the right edge in Scipy than in Matlab.

**Comment by AssafRab** [comment]
l'm not sure they are different, maybe it is only a scaling issue in the y axis. You should compare the estimated parameters.
