### ISSUE TITLE
lfilter doesn't work right with NaNs

### ISSUE THREAD

**Issue by jseabold** [scipy/scipy#3454]
Shouldn't this work?

    from scipy import signal

    x = np.arange(1, 16.)

    x[4] = np.nan
    x[7] = np.nan
    signal.lfilter([0, .75, .25], [1.], x)
    array([ 0.  ,  0.75,  1.75,  2.75,   nan,   nan,   nan,   nan,   nan,
             nan,   nan,   nan,   nan,   nan,   nan])

vs

    signal.convolve(x, [0, .75, .25])
    array([  0.  ,   0.75,   1.75,   2.75,    nan,    nan,    nan,    nan,
              nan,    nan,   9.75,  10.75,  11.75,  12.75,  13.75,  14.75,
             3.75])
On

    [~/src/scipy-skipper/scipy/signal/]
    [10]: from scipy import __version__

    [~/src/scipy-skipper/scipy/signal/]
    [11]: __version__
    [11]: '0.15.0.dev-0a14af8'

**Comment by ewmoore** [comment]
Commenting so this will send emails.  Does #4628 address your concerns @jseabold?

**Comment by ewmoore** [comment]
This was fixed by #4628 and will be in 0.16.  Closing.
