### ISSUE TITLE
netcdf_file.createDimension does not handle numpy.int32 type

### ISSUE THREAD

**Issue by amannucci** [scipy/scipy#3474]
The call sequence for netcdf_file.createDimension(name, length) takes two data types: str and int. However, shouldn't it also take numpy.int32 as well as int for the second argument? I find that passing a numpy.int32 value creates an ill-behaved netcdf file without warning. 

I may be completely offbase here. Perhaps numpy.int32 is rather different than int, but I would have thought them somewhat interchangeable. For example, the argmin() method returns numpy.int32, not int. That's a pretty common function.

**Comment by mckib2** [comment]
I think minimum numpy version is now 1.16.5.  Tested on Python 3.7 numpy==1.16.5 and no longer seems to be an issue so closing
