### ISSUE TITLE
 thread-safe scipy.optimize.leastsq

### ISSUE THREAD

**Issue by greensquirrel** [scipy/scipy#3500]
Hi Scipy developers!

Sturla Molden has suggested to me to open a bug report [0, 1]
I found an old patch [2] but it fails with the master branch :-\
Thank you in advance for fixing it!

[0] http://permalink.gmane.org/gmane.comp.python.scientific.user/35138
[1] http://permalink.gmane.org/gmane.comp.python.scientific.user/35139
[2] https://github.com/scipy/scipy/issues/1240

**Comment by bischofs** [comment]
Any updates/progress on this issue?

**Comment by perimosocordiae** [comment]
I'd like to see this fixed for the 1.0 release. I'll take a look at sending a PR sometime soon.

**Comment by rgommers** [comment]
@perimosocordiae feel free to add a 1.0 milestone to issues/PRs that you find important. Then we won't forget; can always decide later to remove the milestone again.

**Comment by rgommers** [comment]
@perimosocordiae PR still welcome of course, but this is not a blocker so I'm bumping it to 1.1.0 for now.

**Comment by rgommers** [comment]
@perimosocordiae I'm taking the milestone off this one

**Comment by andyfaff** [comment]
@pv is this closeable now? It looks as if it was closed by a combination of #7999 and #8740

**Comment by pv** [comment]
yes, it was fixed
