### ISSUE TITLE
scipy.special inconsistency between bessel functions jn, jv and yn, yv

### ISSUE THREAD

**Issue by rtrwalker** [scipy/scipy#3513]
I've got scipy version 0.13.3 .  scipy.special.jn, (which is bessel function of the first kind, with integer order n) seems to wrap scipy.special.jv (bessel function of the first kind with real order n).  Thus I can call jn(0.5, 1.5) and get the same result as calling jv(0.5, 1.5).  However, for scipy.special.yn (bessel function of the second kind with integer order) any non-integer order is truncated to an integer first so yn(0.5, 1.5) != yv(0.5, 1.5).  I think the behaviour of the two types of function should be the same. In my opinion yn should wrap yv just like jn appears to wrap jv.  Below is some code that demonstrates the offending behaviour.  Note that jn with non-int order does not raise a warning but yn does.

'''

> > > import scipy.special as special
> > > special.jn(1, 1.5),special.jv(1, 1.5)
> > > (0.55793650791009952, 0.55793650791009952)
> > > special.jn(0.5, 1.5),special.jv(0.5, 1.5)
> > > (0.64983807475374777, 0.64983807475374777)
> > > special.yn(1, 1.5),special.yv(1, 1.5)
> > > (-0.41230862697391135, -0.4123086269739113)
> > > special.yn(0.5, 1.5),special.yv(0.5, 1.5)
> > > (0.38244892379775886, -0.0460831658930973)
> > > **main**:1: RuntimeWarning: floating point number truncated to an integer

'''

**Comment by jatentaki** [comment]
Would it make sense to add a documentation note stating that `jn` is just an alias for `jv` and is kept for historical/backwards compatibility reasons? I was seriously dumbfounded when I found that docs on these two functions differ only in citation number, and both those numbers point to the same resource anyway.

This is not a fix to the inconsistency issue by any means, but fixes a related discoverability issue.

**Comment by Chronum94** [comment]
Definitely seconding the idea of explicitly stating that `jn` is an alias for `jv`. There's no difference even in the description and it's uneasily confusing at times. Fix would be quite appreciated and thanks for all of the work on this over the years.

**Comment by person142** [comment]
I'm going to close this one; `jn` has been "soft deprecated" i.e. it no longer appears in the API documentation as of https://github.com/scipy/scipy/pull/8015. So code that already uses `jn` can continue to do so, but the API docs pretend that it doesn't even exist so that users will be pushed towards `jv`.
