### ISSUE TITLE
ENH: axis argument for fftconvolve, convolve, etc.

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#3525]
As mentioned in https://github.com/scipy/scipy/pull/337#issuecomment-11382961, fftconvolve/convolve/correlate/etc could use an axis= parameter.  An example application is computing the CWT in one step.  [nitime's version of fftconvolve](https://github.com/nipy/nitime/blob/master/nitime/utils.py#L973) has this.

**Comment by toddrjen** [comment]
Has there been any progress on this lately?  At least from the documentation, `fftconvolve` doesn't have an `axis` argument yet.

**Comment by Kitchi** [comment]
@toddrjen I completely forgot about this! I got stuck with some issues implementing it and then got busy with some other stuff. I'm willing to give it a go again, but I won't be able to start for the next 2-3 weeks at least. 

If you want to take it up, you're more than welcome! If not, I'll get on it soon.

**Comment by quillan86** [comment]
Has there been any progress on this?

**Comment by rgommers** [comment]
@quillan86 not that I know of

**Comment by toddrjen** [comment]
@Kitchi Could you at least commit your progress so far to your scipy fork?  I might be willing to finish it up depending on the status, but it doesn't seem to be available on your fork right now.

**Comment by toddrjen** [comment]
I have implemented this for fftconvolve in #9190.
