### ISSUE TITLE
cythonize.py does not detect changes in .pxi files

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#3532]
Steps to reproduce:
- make a dummy `.pxi` file
- `include` it into any of the .pyx files
- `python setup.py build`
- change the .pxi file, rerun setup.py.

**Comment by person142** [comment]
I've been wishing for this too. Is there any fundamental obstacle to changing the current build system to be doing something like this in the module-level setups?

```python
from Cython.Build import cythonize
from numpy.distutils.misc_util import Configuration

config = Configuration(...)
ext,  = cythonize('foo.pyx')
cfg = ext.__dict__
... # add extra stuff
config.add_extension(**cfg)
```
From some experimenting it seems like this should detect changes in `pxi` files.

**Comment by rgommers** [comment]
Besides the extra boilerplate, it looks to me like that doesn't handle the use case of shipping C sources and hashes to detect whether those are up-to-date. So it would add Cython as a build time dependency for source releases, which is undesired.

There may be a way around that, but it's probably easier to make ``cythonize.py`` just check for changes in pxi files.

**Comment by person142** [comment]
> it looks to me like that doesn't handle the use case of shipping C sources

Yes... obviously failed to think that through.
