### ISSUE TITLE
BUG: ss2zpk should not convert to tf internally

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#3560]
```
def ss2zpk(A, B, C, D, input=0):
    return tf2zpk(*ss2tf(A, B, C, D, input=input))
```

I believe this has numerical stability problems, same as https://github.com/scipy/scipy/pull/3085

**Comment by jason-s** [comment]
see #5914 for test case

**Comment by sethtroisi** [comment]
Better information in https://github.com/scipy/scipy/issues/5912
