### ISSUE TITLE
sparse hstack/vstack fails with empty matrices

### ISSUE THREAD

**Issue by yha** [scipy/scipy#3572]
```
>>> import numpy as np
>>> from scipy import sparse
>>> sparse.hstack( (sparse.csr_matrix([[1,2]]), np.array([[]])) )
Traceback (most recent call last):

  File "<ipython-input-27-f65b402ca75d>", line 1, in <module>
    hstack( (csr_matrix([[1,2]]), np.array([[]])) )

  File "C:\Python27\lib\site-packages\scipy\sparse\construct.py", line 423, in hstack
    return bmat([blocks], format=format, dtype=dtype)

  File "C:\Python27\lib\site-packages\scipy\sparse\construct.py", line 535, in bmat
    raise ValueError('blocks[:,%d] is all None' % bcol_lengths.argmin())

ValueError: blocks[:,1] is all None
```

The same error occurs with all sparse matrix formats and with vstack.

**Comment by TheIdealis** [comment]
In my applications, I've simply added a condition in vstack and hstack:

```
def hstack(blocks, format=None, dtype=None):
    return bmat([[b for b in blocks if b.shape[1]]], format=format, dtype=dtype)
```
```
def vstack(blocks, format=None, dtype=None):
    return bmat([[b] for b in blocks if b.shape[0]], format='csr', dtype=dtype)
```

**Comment by rbarghou** [comment]
I'm running into this problem when I try to implement a sparse alternative to `scipy.roll`

```python
a = array[shift:, :]
b = array[:shift, :]
c = sparse.vstack((a, b))
```

This throws a value error if one of the slices is empty.

Possible solutions
* Use a custom Error other than ValueError (so I can catch it specifically)
* Include a reference to the empty blocks in the error so that I can replace the blocks with custom logic in exception handling.

**Comment by rgommers** [comment]
> I'm running into this problem when I try to implement a sparse alternative to ``scipy.roll``

A note unrelated to this empty array issue: that's an alias for a numpy function which is only provided for backwards compatibility. Please use ``numpy.roll`` instead.

**Comment by rbarghou** [comment]
Thank you for the quick reply!

Unfortunately, it looks like both `scipy.roll` and `numpy.roll` are both aliases for `numpy.core.numeric.roll` so I'm not sure that it will help to use the numpy alias rather than the scipy one.

**Comment by argriffing** [comment]
>  I'm not sure that it will help to use the numpy alias rather than the scipy one.

I think the idea is to use the alias that is in less danger of becoming deprecated.

**Comment by rbarghou** [comment]
Oh, right.  Thanks.

**Comment by pv** [comment]
IOW, use the name for the function that is listed in the documentation --- [numpy.roll](https://docs.scipy.org/doc/numpy/reference/generated/numpy.roll.html) exists, `scipy.roll` and `numpy.core.numeric.roll` not.

**Comment by pv** [comment]
This seems to be fixed now.
