### ISSUE TITLE
optimize: stepsize in fmin_bfgs is "bad"

### ISSUE THREAD

**Issue by josef-pkt** [scipy/scipy#3581]
The stepsize in fmin_bfgs doesn't look robust when the gradient is large, and results in convergence failures.

I tried a few examples with fmin_l_bfgs_b and didn't have any convergence problems.
(aside: I don't have problems with fmin_slsqp on my computer, but a similar example (with NegativeBinomial) fails on TravisCI.)

Here is a simplified example that is similar to the problems I ran into with statsmodels, and it sounds similar to http://stackoverflow.com/questions/23023851/restricting-magnitude-of-change-in-guess-in-fmin-bfgs/23089696

before scipy 0.13 (including 0.12 IIRC) there were fewer problems with convergence.
One unit test in statsmodels started to fail in 0.13. In some cases I also had problems in scipy 0.12.
The code that uses bfgs is relatively new, and IIRC I never tried with scipy < 0.12.

```
>>> import scipy
>>> scipy.__version__
'0.13.3'
```

The example is just least squares with an exp function. The actual model in statsmodels has the same error structure but different objective functions.

The seeds below create examples that have different failure patterns. Without setting a seed maybe around half of the cases fail.

```
# -*- coding: utf-8 -*-
"""optimization problems with exp function and fmin_bfgs

Problems with exp type models like poisson in statsmodels
see also http://stackoverflow.com/questions/23023851/restricting-magnitude-of-change-in-guess-in-fmin-bfgs/23089696

Created on Fri Apr 25 23:07:41 2014
Author: Josef Perktold
"""

import numpy as np
from scipy import optimize


def error(b, y, x):
    print b
    err = y - np.exp(x.dot(b))
    return (err**2).sum()

def grad(b, y, x):
    err = y - np.exp(x.dot(b))
    grad = -2 * ((err * np.exp(x.dot(b)))[:,None] * x).sum(0)
    return grad

seed = np.random.randint(100000)

#seed = 69391  # nans
#seed = 37587  # nans returns start
#seed = 22644  # nans returns start
#seed = 90799  # nans  going large

#seed = 36269  # no nans, bad result
#seed = 43347  # no nans, bad result

#seed = 77360  # good, but warning
#seed = 14334  # good, but warning
#seed = 56978  # good, but warning
#seed = 97011  # good, but warning

print 'seed =', seed
np.random.seed(seed)

nobs = 500
k = 5
sig_e = 1
b_true = np.random.randn(k)
x = np.random.randn(nobs, k)
y_true = np.exp(x.dot(b_true))
y = y_true + sig_e * np.random.randn(nobs)

b0 = np.ones(k)

#to check gradient
from statsmodels.tools import numdiff as nd
#nd.approx_fprime(b0, error, args=(y,x))

res = optimize.fmin_bfgs(error, b0, fprime=grad, args=(y, x))


print '\nb true'
print b_true
print 'result'
print res
print 'bias'
print res - b_true

print '\ngrad fd'
g_fd = nd.approx_fprime(res, error, args=(y,x), centered=True)
print g_fd
print 'grad'
g = grad(res, y, x)
print g
print '\n grad diff'
print g_fd - g
```

**Comment by js850** [comment]
I have noticed this as well

**Comment by argriffing** [comment]
I always use `l-bfgs-b` instead of `bfgs`, even for unconstrained optimization and when memory is not an issue.  The layers of positional and keyword argument processing added by the `minimize` infrastructure have put a damper on my eagerness to look at this code.

**Comment by pv** [comment]
The code changes between 0.12 and 0.13 in fmin_bfgs are fairly minimal,
so it should be fairly trivial find out what the problem is just by
tracing the execution. The main changes seem to be: initial guess for
the initial step is different, and the "fallback" non-minpack line
search terminates with failure if it fails to find conforming step
length. Encountering the latter condition results to immediate
termination with convergence failure, so that is probably not the issue.

**Comment by pv** [comment]
The cause is indeed in the initial step length; change of `old_old_fval
= old_fval+5000` to `old_old_fval = None` in the beginning of
`_minimize_bfgs`. The "old" approach is not scale invariant either, but
is more sensible for huge gradients.

**Comment by josef-pkt** [comment]
@pv  I didn't manage to trace my way through the stepsize code when I tried previously.
Isn't there a fallback similar to the old fashioned `multiply stepsize by 0.5` if the proposed stepsize "doesn't work"?

**Comment by pv** [comment]
@josef-pkt: yes, the MINPACK search tries step lengths down to 1e-8
(0.5**26), but this is still too large. The other line search does not
have a fixed lower bound, but probably does not deal with nans/infs
sensibly.
.
L-BFGS-B afaics uses an initial step of length 1.0.

**Comment by argriffing** [comment]
a possibly related question http://stackoverflow.com/questions/28477576/overflow-in-scipy-optimizer-with-bfgs

**Comment by pv** [comment]
gh-5536 changed it to use step size ~1, similar to L-BFGS-B.
