### ISSUE TITLE
backward error produced by `lobpcg` does not achieve the specified tolerance

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#3601]
This problem was found by @ysitu in https://github.com/scipy/scipy/issues/3592 after having worked around the original issue.

``` python
>>> n = 10
>>> A = repeat([[-1], [-1]], n, axis=1)
>>> A = spdiags(A, [-1, 1], n, n)
>>> D = spdiags(A * ones(n), [0], n, n)
>>> A = A - D
>>> X = normal(size=(n, 2))
>>> w, V = lobpcg(A, X, tol=1e-8, maxiter=n, largest=False)
>>> w
array([  1.50992209e-08,   9.78869704e-02])
>>> V
array([[-0.31622857, -0.44171354],
       [-0.31623746, -0.39847727],
       [-0.31625788, -0.31623404],
       [-0.31626367, -0.20303984],
       [-0.3162037 , -0.06995005],
       [-0.31617001,  0.06997583],
       [-0.31614704,  0.20306908],
       [-0.31619607,  0.31624893],
       [-0.31627686,  0.39844551],
       [-0.31629637,  0.44167519]])
```

But still, the accuracy of the eigenpairs are unsatisfactory (continuing the above session):

``` python
>>> A * V
array([[  8.89026931e-06,  -4.32362668e-02],
       [  1.15349395e-05,  -3.90069619e-02],
       [ -1.46402151e-05,  -3.09509716e-02],
       [ -6.57476704e-05,  -1.98955903e-02],
       [  2.62713992e-05,  -6.83609474e-03],
       [  1.07180354e-05,   6.83263493e-03],
       [  7.20076047e-05,   1.99134018e-02],
       [  3.17508630e-05,   3.09832696e-02],
       [ -6.12784988e-05,   3.89668997e-02],
       [ -1.95067268e-05,   4.32296793e-02]])
>>> norm(A * V[:, 0], 1) / (norm(A.todense(), 1) * norm(V[:, 0], 1))
2.548370670957575e-05
```

`A` has an eigenpair (0, **_e**_) where **_e**_ is the vector of all ones. Therefore, analytically, the first column of `norm(A * V[:, 0])` should be zero. The backward error produced by `lobpcg` did not achieve the specified tolerance.

**Comment by lobpcg** [comment]
This is a normal and expected behavior of LOBPCG:

1. LOBPCG is not designed for small-size matrices, so testing it for a matrix of size 10 is not a good idea. 

2. LOBPCG is an iterative solver with problem-depended convergence speed. In the example above it runs only for n=10 iterations, which is probably just too small to reach the required tol=1e-8.

The issue can probably be closed.

**Comment by rgommers** [comment]
thanks @lobpcg and @argriffing, closing
