### ISSUE TITLE
wishlist: pep8 and/or pyflakes options for runtests.py

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#3619]
See the off-topic discussion in https://github.com/scipy/scipy/pull/3617.  The idea is to reduce the number of rage-commits required by the pep8 bot.

**Comment by rgommers** [comment]
Makes sense to add to ``runtests.py`` all types of tests that will be run on TravisCI. So also the doc builds.

**Comment by andyfaff** [comment]
@rgommers could we use flake8 instead of pyflakes for this? It makes it easier to exclude files that you don't want to check.

**Comment by rgommers** [comment]
> could we use flake8 instead of pyflakes for this

either one is fine. actually I'm not sure this is a very useful thing to work on, simply `flake8 scipy` in the repo root does the job just fine.

I'd say PR welcome if anyone has a use for this, but no need to keep it open
