### ISSUE TITLE
BUG: np.argwhere fails on sparse inputs

### ISSUE THREAD

**Issue by perimosocordiae** [scipy/scipy#3621]
The documentation for `np.argwhere` states that it is equivalent to `np.transpose(np.nonzero(a))`. The second form works fine with sparse inputs, but `argwhere` throws a strange warning and returns incorrect results.

```
In [1]: import scipy.sparse as ss

In [2]: a = ss.rand(5,5, density=0.3)

In [3]: np.transpose(np.nonzero(a))
Out[3]:
array([[0, 0],
       [0, 1],
       [2, 1],
       [4, 1],
       [3, 2],
       [1, 4],
       [3, 4]], dtype=int32)

In [4]: np.argwhere(a)
/usr/local/lib/python2.7/site-packages/scipy/sparse/base.py:180: RuntimeWarning: tp_compare didn't return -1 or -2 for exception
  if self.shape == (1, 1):
Out[4]: array([[0]])
```

**Comment by rgommers** [comment]
This now works for all sparse matrix formats, because they have ``transpose`` and ``nonzero`` methods which are called by ``np.nonzero`` and ``np.transpose``.
