### ISSUE TITLE
Return Bunch objects from stats functions

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#3665]
Some functions like `linregress` and `theilslopes` return tuples of 4 or 5 results. A `Bunch` pattern would be much cleaner, and also allows adding extra return values easily.

See discussion at https://github.com/rgommers/scipy/commit/6c1048f6416 with @josef-pkt

**Comment by ev-br** [comment]
I should have probably thought about it much earlier, but here's a version of a Bunch which is backwards-compatible:

https://gist.github.com/ev-br/a11e5a25a98c2b0115ed

The bottom line is that this class remembers the values it has been constructed with, and if asked to behave like a tuple, behaves like a tuple of these (and only these!) values with respect to unpacking, slicing and indexing.

The advantage of this is that one can both add new return values *and* unpack it into fixed-length tuples in a backwards-compatible way.

**Comment by rgommers** [comment]
@ev-br that sounds promising. It's too much now for @aeklant's GSoC, but we should keep this issue open and someone can have a look at moving from ``namedtuple``s to ``Bunch``s.

**Comment by rgommers** [comment]
Link to the latest on ``Bunch`` classes: gh-6335. There's a class there that's pretty much complete, just needs a PR.

**Comment by Eric89GXL** [comment]
I can find some time to do that PR first. Should we deprecate `return_*` functions for 1.0 as part of it? (Or preferably for my sake, separately?)

**Comment by clarkfitzg** [comment]
The `Bunch` classes introduce a new data structure / object, which takes more time and effort for users to understand than the common `namedtuple`. Returning a regular Python `dict` would be a nice solution if backwards compatibility weren't an issue.

**Comment by rgommers** [comment]
> The ``Bunch`` classes introduce a new data structure / object, which takes more time and effort for users to understand than the common ``namedtuple``. Returning a regular Python ``dict`` would be a nice solution if backwards compatibility weren't an issue.

I agree that a new class needs some extra time, so converting all existing ``namedtuple``s to ``Bunch`` is not necessarily a good idea. But as soon as we want to add a return value to an existing function, ``Bunch`` is by far the best way to go. That is why we want to introduce it.

> I can find some time to do that PR first. 

Great.

> Should we deprecate ``return_*`` functions for 1.0 as part of it? (Or preferably for my sake, separately?)

Not sure that is worth doing. Definitely not in the same PR.

**Comment by rgommers** [comment]
Just having ``Bunch`` available in ``scipy._lib`` for new use cases would be great.

**Comment by chrisb83** [comment]
I would like to add a new statistical test to `stats` in #9539 and would like to get your view on how to return the results of the test. 

- use a named tuple like for the other tests
- use a Bunch: is there an implementation that could be used? I saw the link http://code.activestate.com/recipes/52308 above + a proposal by ev-br. So it looks like one would still need to agree on an implementation? In particular, the code shared on activestate does not have a __str__ method which is probably needed.
- use a Bunch-like class for hypothesis tests that has certain mandatory keywords (such as name, statistic and null hypothesis + optional fields such as p-value (not mandatory since sometimes there is only a statistic + critical values for confidence levels)). This is similar to the class `htest` in R. One could then define a user-friendly print method like in R: 
```Two-sample Kolmogorov-Smirnov test
data:  x and y
D = 0.16, p-value = 0.1545
alternative hypothesis: two-sided```.
- simply return a dictionary with keys like pval, statistic etc. (also proposed above https://github.com/scipy/scipy/issues/3665#issuecomment-252277701)

**Comment by ilayn** [comment]
It's already in the codebase 

https://github.com/scipy/scipy/blob/0781734e45886567f84d9fc0caa56476a32d82bb/scipy/signal/ltisys.py#L2492

**Comment by rgommers** [comment]
Ah, I totally forgot about that one - IIRC it was added in the `signal.place_poles` PR but in a very minimal incomplete state. The gist of @ev-br is still the most complete thing we have I think.

**Comment by rgommers** [comment]
Or, after some searching, this is the latest: https://github.com/scipy/scipy/pull/6335#issuecomment-231947342

> I would like to add a new statistical test to stats in #9539 and would like to get your view on how to return the results of the test.

If you'd want to pick up the `Bunch` thing that would be ideal. Otherwise `namedtuple` is also fine; it can be turned into a `Bunch` later without backwards compat issues. Not sure about "use a Bunch-like class", that seems extra effort for a temporary / one-off thing.

**Comment by ev-br** [comment]
> The gist of @ev-br is still the most complete thing we have I think.

There's @wolever's implementation somewhere in these issues/PRs which looked more developed if slightly different.

**Comment by chrisb83** [comment]
I see the following issue now:

- to move from named tuple to `Bunch` without breaking backwards compatability, one needs unpacking, i.e. `a, b =  x` must be allowed
- if `Bunch` enables unpacking, it will not help to add extra return without breaking backwards compatability, this is almost the same situation as with named tuple (see https://github.com/scipy/scipy/issues/3665#issuecomment-52546370 above)

Or do I miss something?

**Comment by ev-br** [comment]
One idea was to use the `unpack` keyword to specify the number of item an instance unpacks into when iterated. https://github.com/scipy/scipy/pull/6335#issuecomment-231802174
This number is fixed by backwards compatibility. Other elements are into included into the unpacking or indexing, can only be accessed as attributes.

**Comment by chrisb83** [comment]
OK, I see the point of the `unpack` keyword. Since PR 9539 is a new functionality, I wonder if it would be best to simply use the simple Bunch version that does not allow unpacking. Then one avoids the problem of having to fix the number of values that can be unpacked. and arguably, it is safer to have explicit statements like `p = x.pval`. Or should we aim for consistency, i.e. unpacking should be allowed for the new test as well?

**Comment by ev-br** [comment]
I think API consistency is valuable. It's probably not necessary to do everything in one PR though. A single release window would be nice.

**Comment by WarrenWeckesser** [comment]
There are many enhancements in the works, for `stats` and elsewhere, where we want to increase the number of return values of functions.  I'd like to revive this discussion, so we can start making PRs with such enhancements.

To summarize, we want to return a Bunch-like object that has all the various return values (old and new) as attributes, but for backwards compatibility, we want the return value to also act like the old tuple or namedtuple.

The above gist provided by @ev-br  is one possibility, but it requires overriding many basic methods.  I think the subclass of `tuple` proposed by @wolever in https://github.com/scipy/scipy/pull/6335 is heading in the right direction.  Instead of subclassing `tuple`, I think it would be more effective to subclass the namedtuple type. By subclassing the namedtuple type, we don't have to reimplement all the tuple methods, because an instance of the class *is* a tuple.  It avoids the need for the `unpack` parameter mentioned in https://github.com/scipy/scipy/pull/6335, because the tuple methods are unaware of the additional attributes--unpacking works the same as for a tuple or namedtuple. And by default, a subclass of namedtuple allows additional attributes to be assigned to instances, so it can act like a Bunch.

Here's a prototype of a function called `namedtuple_bunch` that accepts a namedtuple type and returns a subclass of that type with a few extra methods added.  The method `_set_extra_fields` assigns additional attributes to the instance--but only if those attributes don't conflict with the existing names in the namedtuple.  The `__repr__` method is overridden to include the extra fields (if any) in the output.

```
import types


def namedtuple_bunch(namedtuple_type):
    """
    Return a subclass of the given namedtuple type that has
    the method `_set_extra_fields` that allows additional names
    to be added to instances of the type.  The returned type
    is, in effect, a combination of a namedtuple and a Bunch-like
    class.

    The fields added via `_set_extra_fields` do not become part
    of the tuple.  Unpacking, indexing, etc., will refer only to the
    fields that were part of the namedtuple_type.
    """

    def _set_extra_fields(self, **kwds):
        if any(key in self._fields for key in kwds):
            name = namedtuple_type.__name__
            badkey = [key for key in kwds if key in self._fields][0]
            raise RuntimeError(f"attempt to add '{badkey}' as an extra "
                               f"attribute but it already exists in the "
                               f"namedtuple '{name}'")

        self.__dict__.update(kwds)
        self.__dict__.update({'_extra_fields': list(kwds.keys())})

    def __repr__(self):
        s = namedtuple_type.__repr__(self)
        if hasattr(self, '_extra_fields'):
            s = s.rstrip(')')
            s += ', ' + ', '.join([name + '=' + repr(self.__dict__[name])
                                   for name in self._extra_fields])
            s += ')'
        return s

    def __setattr__(self, name, value):
        raise AttributeError("can't set attribute")

    def exec_body(cls):
        cls['_set_extra_fields'] = _set_extra_fields
        cls['__repr__'] = __repr__
        cls['__setattr__'] = __setattr__
        return cls

    cls = types.new_class(namedtuple_type.__name__,
                          bases=(namedtuple_type,),
                          exec_body=exec_body)

    return cls
```
(This could also be implemented by nesting a `class` definition in the function instead of using `types.new_class()`, but there was a minor detail or two in that implementation that I wasn't happy with.)

Here's an example of how it can be used.  Suppose the function `somefunc` currently returns the namedtuple `SomeFuncResult` which has two fields, `z` and `p`:
```
SomeFuncResult = namedtuple('SomeFuncResult', ['z', 'p'])

def somefunc(x, y):
    z = x + y
    p = x/z
    result = SomeFuncResult(z=z, p=p)
    return result
```
We want to add two additional "return values", `w = x - y` and `beta = 1 - p**2`.   Here's the updated implementation of `somefunc`:

```
SomeFuncResult = namedtuple_bunch(SomeFuncResult)

def somefunc(x, y):
    z = x + y
    p = x/z

    # New output to be included as attributes of the
    # return value, but not part of the namedtuple
    w = x - y
    beta = 1 - p**2

    result = SomeFuncResult(z=z, p=p)
    result._set_extra_fields(w=w, beta=beta)
    return result
```
Example in use:
```
In [35]: a = somefunc(3, 5)
```
The repr of the result shows all four attributes:
```
In [36]: a
Out[36]: SomeFuncResult(z=8, p=0.375, w=-2, beta=0.859375)
```
They can all be accessed as attributes:
```
In [37]: a.z
Out[37]: 8

In [38]: a.p
Out[38]: 0.375

In [39]: a.w
Out[39]: -2

In [40]: a.beta
Out[40]: 0.859375
```
But `a` is still a tuple of length 2:
```
In [41]: len(a)
Out[41]: 2
```
Unpacking works as expected for a tuple of length 2:
```
In [42]: z0, p0 = a

In [43]: z0, p0
Out[43]: (8, 0.375)
```
So does slicing:
```
In [44]: a[1:]
Out[44]: (0.375,)
```
That all works because `a` *is* a tuple:
```
In [45]: isinstance(a, tuple)
Out[45]: True
```

What do you think?

**Comment by WarrenWeckesser** [comment]
For a concrete example, I created a pull request that adds a new "return value" to `stats.fisher_exact`: https://github.com/scipy/scipy/pull/12288
I didn't modify any existing tests, and even though I changed the return value to use a subclass of a namedtuple created by `namedtuple_bunch`, the tests all pass (at least locally--the CI test suite just started).

Here's how it looks in action:
```
In [1]: from scipy.stats import fisher_exact

In [2]: result = fisher_exact([[8, 2], [1, 5]])

In [3]: result.pvalue
Out[3]: 0.03496503496503495

In [4]: result.sample_odds_ratio
Out[4]: 20.0

In [5]: result.conditional_odds_ratio
Out[5]: 15.46581971692097
```
The old style still works:
```
In [6]: odds, p = fisher_exact([[8, 2], [1, 5]])

In [7]: odds
Out[7]: 20.0

In [8]: p
Out[8]: 0.03496503496503495
```

**Comment by mdhaber** [comment]
I think the behavior for the end user is spot on. I would prefer if the extra fields could be set during initialization rather than requiring a call to a separate method `_set_extra_fields`. Since the object already knows what the core/original fields are, this should be possible, right?

**Comment by josef-pkt** [comment]
I recently added something similar to statsmodels, currently just a few cases and still experimental 
(I haven't tried a single element tuple yet)

I never cared much about the named tuple case
The main method I added as extra  is `__array__` to be able to use it directly with numpy, and pandas

**Comment by WarrenWeckesser** [comment]
@mdhaber wrote
> I would prefer if the extra fields could be set during initialization ...

I agree.  I'll look into making that work.

**Comment by WarrenWeckesser** [comment]
I just pushed a new version of `namedtuple_bunch()` to https://github.com/scipy/scipy/pull/12288.  The signature is now

    def namedtuple_bunch(typename, fields, extra_fields)

It returns a subclass of the type that is created by `namedtuple(typename, fields)`.  The third argument is the list extra field names that must be specified when an instance is created.  E.g.

```
In [15]: Result = namedtuple_bunch('Result', ['z', 'p'], ['w', 'beta'])

In [16]: result = Result(z=10.1, p=0.25, w=9.5, beta=0.996)

In [17]: result
Out[17]: Result(z=10.1, p=0.25, w=9.5, beta=0.996)
```

By requiring the extra field names to be specified when the *type* is created, the code can check for missing or misspelled parameters when an instance is created:
```
In [18]: result = Result(z=1.23, p=0.1, beta=0.25)
<snip>
TypeError: missing keyword argument 'w'

In [19]: result = Result(z=1.23, p=0.1, w=7, betar=0.25)
<snip>
TypeError: unexpected keyword argument 'betar'
```

**Comment by WarrenWeckesser** [comment]
A potential problem with the proposed Bunch-like  namedtuple created by `namedtuple_bunch` is that instances are not picklable.  I'm not sure how important that is, and I haven't check to see if that is easily fixable.

**Comment by rgommers** [comment]
That seems important, non-picklable objects may give issues with `multiprocessing`. Hopefully not too hard too fix.

**Comment by WarrenWeckesser** [comment]
I tried to get the subclass of `namedtuple` working like we want and also be picklable, but I didn't make any progress.  I'm not saying it is impossible, but I wasn't able to create an object that was a subclass of `tuple` (like `namedtuple` is) and that had added attributes, and could be round-tripped through pickling.  (The `tuple` class is a light class--it doesn't have a `__dict__` attribute, and it doesn't allow `__slots__`.)

My latest version uses a class that has a private attribute, `_tuple`, that holds the tuple that is compatible with the old return values.  A few dunder methods are overridden to delegate to `_tuple` to implement *some* tuple-like behavior.  The code is currently in the pull request https://github.com/scipy/scipy/pull/12288, but that is likely to change over time, so I'll copy it here:
```
import sys as _sys
from keyword import iskeyword as _iskeyword


class _TupleBunch:

    _fields = ()
    _extra_fields = ()

    def __init__(self, **kwds):
        # _validate_kwds isn't strictly necessary, since the code that follows
        # it will raise an exception if the names in kwds are not valid, or if
        # there is a name missing from kwds.
        # The function provides a friendlier error message.
        self._validate_kwds(kwds)
        self.__dict__['_tuple'] = tuple(kwds[name] for name in self._fields)
        for name in self._fields + self._extra_fields:
            self.__dict__[name] = kwds[name]

    def __repr__(self):
        s = (self.__class__.__name__ + '(' +
             ', '.join(f'{name}={self.__dict__[name]!r}'
                       for name in self._fields + self._extra_fields) + ')')
        return s

    def __setattr__(self, name, value):
        # Ensure that all attributes are read-only, and that new attributes
        # can't be added to the object.
        raise AttributeError("can't set attribute")

    def _validate_kwds(self, kwds):
        all_fields = self._fields + self._extra_fields
        for name in kwds:
            if name not in all_fields:
                raise TypeError(f"unexpected keyword argument '{name}'")
        for name in all_fields:
            if name not in kwds:
                raise TypeError(f"missing keyword argument '{name}'")

    # Delegate several dunder methods to self._tuple

    def __eq__(self, other):
        return self._tuple == other

    def __len__(self):
        return len(self._tuple)

    def __getitem__(self, i):
        return self._tuple[i]

    def __hash__(self):
        return hash(self._tuple)


def _validate_names(typename, field_names, extra_field_names):
    """
    Ensure that all the given names are valid Python identifiers that
    do not start with '_'.  Also check that there are no duplicates
    among field_names + extra_field_names.
    """
    for name in [typename] + field_names + extra_field_names:
        if type(name) is not str:
            raise TypeError('typename and all field names must be strings')
        if not name.isidentifier():
            raise ValueError('typename and all field names must be valid '
                             f'identifiers: {name!r}')
        if _iskeyword(name):
            raise ValueError('typename and all field names cannot be a '
                             f'keyword: {name!r}')

    seen = set()
    for name in field_names + extra_field_names:
        if name.startswith('_'):
            raise ValueError('Field names cannot start with an underscore: '
                             f'{name!r}')
        if name in seen:
            raise ValueError(f'Duplicate field name: {name!r}')
        seen.add(name)


def make_tuple_bunch(typename, field_names, extra_field_names=None,
                     module=None):
    if extra_field_names is None:
        extra_field_names = []
    _validate_names(typename, field_names, extra_field_names)

    result = type(typename, (_TupleBunch,),
                  dict(_fields=tuple(field_names),
                       _extra_fields=tuple(extra_field_names)))

    # Note: This code to handle `module` is from the Python source code for
    # namedtuple, in Lib/collections/__init__.py
    #
    # For pickling to work, the __module__ variable needs to be set to the
    # frame where the named tuple is created.  Bypass this step in environments
    # where sys._getframe is not defined (Jython for example) or sys._getframe
    # is not defined for arguments greater than 0 (IronPython), or where the
    # user has specified a particular module.
    if module is None:
        try:
            module = _sys._getframe(1).f_globals.get('__name__', '__main__')
        except (AttributeError, ValueError):
            pass
    if module is not None:
        result.__module__ = module

    return result
```
For example,

```
In [24]: from scipy._lib._bunch import make_tuple_bunch

In [25]: Foo = make_tuple_bunch('Foo', ['z', 'p'], ['w', 'beta'])

In [26]: result = Foo(z=2.5, p=0.75, w=999, beta=0.25)

In [27]: result
Out[27]: Foo(z=2.5, p=0.75, w=999, beta=0.25)

In [28]: result.p
Out[28]: 0.75

In [29]: result.beta
Out[29]: 0.25
```
For unpacking and indexing, it acts like a tuple with length 2:
```
In [30]: z0, p0 = result

In [31]: z0                                                                                                                                
Out[31]: 2.5

In [32]: p0                                                                                                                                
Out[32]: 0.75

In [33]: result[1:]
Out[33]: (0.75,)
```
Verify that we can pickle and unpickle the object:
```
In [34]: import pickle

In [35]: s = pickle.dumps(result)

In [36]: obj = pickle.loads(s)

In [37]: obj
Out[37]: Foo(z=2.5, p=0.75, w=999, beta=0.25)
```

**Comment by WarrenWeckesser** [comment]
I pulled the code for the new return value class out of https://github.com/scipy/scipy/pull/12288 and put it in a new pull request: https://github.com/scipy/scipy/pull/12323.  I think it needs its own PR to avoid mixing discussions of the new object with the discussion of the enhancement to `fisher_exact`.

The unit tests added in that PR verify the properties that I think we want for this object.

**Comment by WarrenWeckesser** [comment]
Over in https://github.com/scipy/scipy/pull/12323, @larsoner added the right magic to make `make_tuple_bunch()` create a picklable Bunch-like object that is a subclass of `tuple`.   Take a look!
