### ISSUE TITLE
Feature Request: Official Vagrant/Puppet Setup Scripts for scipy stack

### ISSUE THREAD

**Issue by diego898** [scipy/scipy#3676]
It would be very helpful to have vagrant/puppet configurations to get a working scipy stack up and running with port forwading so that an ipython notebook can be run on the host (windows) os. This would dramatically decrease setup time and will make it much easier for windows users to get and up and running! 

Thanks!

**Comment by pv** [comment]
Closing (out of scope for scipy library).
