### ISSUE TITLE
idct normalization unexpected?

### ISSUE THREAD

**Issue by pv** [scipy/scipy#3677]
Is this intentional?

```
>>> from scipy.fftpack import dct, idct
>>> import numpy as np
>>> x = np.array([1., 2, 3])
>>> idct(dct(x))
array([  6.,  12.,  18.])
>>> idct(dct(x, norm='ortho'), norm='ortho')
array([ 1.,  2.,  3.])
```

Is it really a convention that `idct` does not have the correct scale factor so that `idct o dct` is an identity operation?

**Comment by peterbell10** [comment]
Just noticed this issue: Is there interest in changing this behavior for `scipy.fft`?  I think that it's an obvious inconsistency with the other FFT functions. It's also worth noting that FFTW doesn't do _any_ normalisation for any of their FFT types.

**Comment by larsoner** [comment]
> Is there interest in changing this behavior for scipy.fft? I think that it's an obvious inconsistency with the other FFT functions. It's also worth noting that FFTW doesn't do any normalisation for any of their FFT types.

Yes it would be nice to have consistency within the module as much as possible. We are creating a new module from scratch so this is our opportunity to fix past mistakes without dealing with deprecation problems.

**Comment by endolith** [comment]
@larsoner 

Isn't it already consistent?

```
>>> from scipy.fftpack import ifft, idct
>>> ifft(np.array([ 30.,  -8.,   6.,  -2.,   6.,  -8.])).real
array([  4.,   3.,   5.,  10.,   5.,   3.])
>>> idct(np.array([ 30.,  -8.,   6.,  -2.]), 1) / 6
array([  4.,   3.,   5.,  10.])
```

The documentation says that `norm='ortho'` is only for compatibility with Matlab?

**Comment by peterbell10** [comment]
```python
>>> idct(np.array([ 30.,  -8.,   6.,  -2.]), 1) / 6
array([  4.,   3.,   5.,  10.])
```

That extra `/ 6` at the end is exactly the inconsistency

**Comment by endolith** [comment]
Ohh

**Comment by peterbell10** [comment]
>Ohh, but norm='ortho' doesn't do the same thing as the /6, so it would need a different default normalization and still support 'ortho'?

Correct, the convention used elsewhere is:
- `norm=None`: forward transform is unnormalised and the inverse transform is divided by `N`.
- `norm='ortho'`: both directions are divided by `sqrt(N)`

**Comment by grlee77** [comment]
> It's also worth noting that FFTW doesn't do any normalisation for any of their FFT types.

FFTW doesn't but the pyFFTW interfaces to FFTW do normalisation as in NumPy/SciPy.

You can also get the default FFTW behavior in PyFFTW if you explicitly create an FFTW object and set `normalise_idft=False` and `ortho=False`. I think it is probably nearly always the case that users want a round-trip transform to give back the same input without scaling, so I doubt it is worth supporting a completely unnormalized case like this in SciPy.
