### ISSUE TITLE
lobpcg module vs. function

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#3686]
(sorry, I somehow created this issue before I meant to...)  Anyway, the `lobpcg` module seems to be clobbered by the `lobpcg` function in scipy.  I think it may not be possible to import the module, and this may cause other weirdness.

For example

```
$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.sparse.linalg.eigen.lobpcg.lobpcg
>>> help(scipy.sparse.linalg.eigen.lobpcg.lobpcg)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute 'lobpcg'
```

**Comment by lobpcg** [comment]
Should be fixed in https://github.com/scikit-learn/scikit-learn/pull/12319, thus can be closed.

**Comment by lobpcg** [comment]
This cannot be apparently resolved without breaking backward compatibility, so the issue can be closed, I guess.

**Comment by rgommers** [comment]
Thanks @lobpcg. We will be solving this as part of gh-14360. So I agree, let's close this.

The correct way to get at the `lobpcg` function has always been `sparse.linalg.lobpcg`, we will hide the other submodules by adding underscores.
