### ISSUE TITLE
Possible off-by-one bug in resample()

### ISSUE THREAD

**Issue by goerz** [scipy/scipy#3723]
The documentation for the `sympy.signal.resample` function states

>   The first sample of the returned vector is the same as the first sample of the input vector.  The spacing between samples is changed from dx to:
> 
> ```
>   dx * len(x) / num
> ```
> 
> where `num` is to be the number of samples of the resampled signal

This strikes me as incorrect. Suppose I have a signal on a time grid of three points:

```
0       1       2
|       |       |        dx = 1.0   len(x) = 3
```

and I want to double sample it:

```
0  0.5  1  1.5  2        dx = 0.5   num = 5
|   |   |   |   |
```

However, the formula in the documentation would indicate dx = 3/5 = 0.6.

Going strictly according to the documentation, it would appear that the output from `resample` was

```
0   0.6  1.2  1.8  2.4
|    |    |    |    |   
```

I should note that the implementation does match the documentation:

```
>>> from scipy import signal
>>> import numpy as np
>>> y = np.zeros(3)
>>> x = np.array([0.0, 1.0, 2.0])
>>> signal.resample(y, 5, x)
(array([ 0.,  0.,  0.,  0.,  0.]), array([ 0. ,  0.6,  1.2,  1.8,  2.4]))
```

So either the resample time grid is incorrect, and in the implementation of `resample` in `scipy/signal/signaltools.py`, the line

```
new_t = arange(0, num) * (t[1] - t[0]) * Nx / float(num) + t[0]
```

should be changed to

```
new_t = arange(0, num) * (t[1] - t[0]) * Nx / float(num+1) + t[0]
```

Or, if the existing behavior is in fact correct, I have a misconception about how Fourier interpolation works (namely that the padding of the spectrum modifies the sample spacing dx, but does not change the range of the signal samples), and I wouldn't see any way to do proper double sampling of a signal.

**Comment by rgommers** [comment]
since this is apparently correct after all, and the `resample` docstring and implementation have been touched multiple times since 2014 (and the docstring looks good), I'll close this. thanks @goerz
