### ISSUE TITLE
scipy.stats.pearsonr: possible bug with zero variance input

### ISSUE THREAD

**Issue by jairideout** [scipy/scipy#3728]
When input with zero variance is provided to `scipy.stats.pearsonr`, a valid correlation coefficient can be returned instead of `np.nan`. Here's a simple example, also showing how `scipy.stats.spearmanr` behaves:

``` python
>>> from scipy.stats import pearsonr, spearmanr
>>> x = [0.667, 0.667, 0.667] # zero variance
>>> y = [0.123, 0.456, 0.789] # has variance
>>>
>>> pearsonr(x, x)
(1.0, 0.0)
>>> spearmanr(x, x)
(nan, nan)
>>>
>>> pearsonr(x, y)
(-2.041651584850628e-16, 1.0)
>>> spearmanr(x, y)
(nan, nan)
```

R's `cor` function returns `NA` for all invocations in the previous example (`x` vs. `x`, `x` vs. `y`, for both pearson and spearman).

I'm not sure if this is a bug or not, but the current behavior of `pearsonr` isn't what I'd expect. If one or both of the inputs has zero variance, I'd expect the output to be undefined (e.g., `np.nan`) as there should be a division-by-zero in the calculations.

**Comment by WarrenWeckesser** [comment]
It would be nice if we could guarantee that when the true variance of one of the inputs was 0, we correctly determined that we were in the 0/0 case and returned `nan` for r.  But even numpy's `var` does not do this currently:

    In [25]: np.var([0.667, 0.667, 0.667])
    Out[25]: 1.232595164407831e-32

See also https://github.com/numpy/numpy/issues/9631.

As I noted in the numpy issue, Welford's algorithm for computing the variance will given exactly 0 when all the elements of the input are the same.  We might consider creating an efficient (i.e. C or Cython) version of the variance that to ensure that this edge case is handled cleanly.
