### ISSUE TITLE
Pchipinterpolator inconvenient as ppoly

### ISSUE THREAD

**Issue by pv** [scipy/scipy#3742]
The encapsulation used in PchipInterpolator makes it difficult to use e.g. the integration features of the piecewise polynomials. Also, there is not public interface for converting the resulting object to a BPoly or PPoly.

The user interface could be improved here. It's also a bit inconsistent with what we did with Akima1D, as that object is directly a *Poly subclass.

**Comment by ev-br** [comment]
This would be fixed by a combination of gh-4701 and gh-4784
