### ISSUE TITLE
No output of scipy.signal.argrelextrema()

### ISSUE THREAD

**Issue by smoneck** [scipy/scipy#3749]
Hey,

I hope that I did not made major flaws but I can not find a mistake. The output of argrelextrema() is always an empty numpy array.

```
import numpy as np
from scipy.signal import argrelextrema

dat = np.genfromtxt("numbers.dat")
print argrelextrema(dat[:], np.greater, order=6)
```

   _(array([], dtype=int64),)_

`numbers.dat` contains a list of 50 testvalues containing a maximum. I also tested several values for the `order` parameter

```
78.75
81.0                                                                                                                                
83.25
85.5
87.75
89.25
91.5
93.0
94.5
96.75
98.25
99.75
101.25
102.0
103.5
104.25
105.75
106.5
107.25
108.0
108.75
108.75
109.5
109.5
109.5
109.5
109.5
109.5
109.5
108.75
108.75
108.0
107.25
106.5
105.75
105.0
104.25
102.75
102.0
100.5
99.0
97.5
96.0
94.5
93.0
90.75
89.25
87.0
84.75
82.5
```

Thanks for any comments!
Stephan

**Comment by pletnes** [comment]
I second this being a bug; two identical values in a row would intuitively result in one (if not two) peaks. The workaround works ok, but does give duplicates, of course. Which is worse - missing a peak or getting a duplicate - might depend on the application, but for me, missing the peak is definitely bad.

**Comment by rgommers** [comment]
agreed, a duplicate is better than nothing. maybe even better is then checking for duplicates and removing one according to some simple rule (like keep the one that has the highest value next to it)

**Comment by lagru** [comment]
This is quite old but I think there is an alternative solution now.

In #8350 the cython function `_argmaxima1d` was introduced which can detect "flat" peaks in 1D arrays. It approximates the center of flat peaks. However, currently this function is "private" but should get exposed with `find_peaks` in #8264.
