### ISSUE TITLE
DOC: document constructors of scipy.signal.lti

### ISSUE THREAD

**Issue by jason-s** [scipy/scipy#3754]
The documentation of scipy.signal.lti leaves quite a bit of ambiguity.

http://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.lti.html

(numerator, denominator) -- should say that the numerator and denominator are each arrays of polynomial coefficients, from lowest to highest degree (or is it the other way around), e.g. [2.4, 0.5, 1.1] represents 2.4 + 0.5x + 1.1x^2.
Probably good to refer to http://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.tf2zpk.html#scipy.signal.tf2zpk since this has a detailed explanation.

(zeros, poles, gain) -- how do you enter pairs of complex zeros and poles?

(A,B,C,D) -- have some text that refers to a state-space representation and explains what format is necessary

---

http://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.lti.freqresp.html#scipy.signal.lti.freqresp

"See scipy.signal.freqresp for details." -- if you're going to say "See X for details" please include a hyperlink to X.

**Comment by rgommers** [comment]
this was addressed in gh-3954
