### ISSUE TITLE
wavfile.write() doesn't write 'fact' chunk for floating-point formats

### ISSUE THREAD

**Issue by mgeier** [scipy/scipy#3778]
This came up in https://github.com/erikd/libsndfile/issues/70:

According to http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/WAVE.html
the WAVE_FORMAT_IEEE_FLOAT format is a non-PCM format and all non-PCM formats "must have a Fact chunk".

When I'm writing 32-bit and 64-bit float files with `scipy.io.wavfile.write()`, the 'fact' chunk is not written:

```python
#!/usr/bin/env python3

import numpy as np
from scipy.io import wavfile

for dtype in 'float32', 'float64':
    wavfile.write(dtype + '.wav', 44100,
                  np.array([[1.0,  -1.0],
                            [0.75, -0.75],
                            [0.5,  -0.5],
                            [0.25, -0.25]], dtype=dtype))
```

Running `sndfile-info` on `float32.wav` and `float64.wav` reveals that they don't have a 'fact' chunk:

```
$ sndfile-info float32.wav 

Version : libsndfile-1.0.25

========================================
File : float32.wav
Length : 76
RIFF : 68
WAVE
fmt  : 16
  Format        : 0x3 => WAVE_FORMAT_IEEE_FLOAT
  Channels      : 2
  Sample Rate   : 44100
  Block Align   : 8
  Bit Width     : 32
  Bytes/sec     : 352800
data : 32
End

----------------------------------------
Sample Rate : 44100
Frames      : 4
Channels    : 2
Format      : 0x00010006
Sections    : 1
Seekable    : TRUE
Duration    : 00:00:00.000
Signal Max  : 1 (0.00 dB)
```

```
$ sndfile-info float64.wav 

Version : libsndfile-1.0.25

========================================
File : float64.wav
Length : 108
RIFF : 100
WAVE
fmt  : 16
  Format        : 0x3 => WAVE_FORMAT_IEEE_FLOAT
  Channels      : 2
  Sample Rate   : 44100
  Block Align   : 16
  Bit Width     : 64
  Bytes/sec     : 705600
data : 64
End

----------------------------------------
Sample Rate : 44100
Frames      : 4
Channels    : 2
Format      : 0x00010007
Sections    : 1
Seekable    : TRUE
Duration    : 00:00:00.000
Signal Max  : 1 (0.00 dB)
```

I cannot upload the WAV files here in this issue, but you can get a 32-bit example at https://gist.github.com/mgeier/7224433#file-stereo-wav.

For comparison, this is how it looks like for a 32-bit float file written with [libsndfile](http://www.mega-nerd.com/libsndfile/) (I'm not saying this is correct, but it's definitely different):

```
$ sndfile-info libsndfile_float32.wav 

Version : libsndfile-1.0.25

========================================
File : libsndfile_float32.wav
Length : 120
RIFF : 112
WAVE
fmt  : 16
  Format        : 0x3 => WAVE_FORMAT_IEEE_FLOAT
  Channels      : 2
  Sample Rate   : 44100
  Block Align   : 8
  Bit Width     : 32
  Bytes/sec     : 352800
fact : 4
  frames  : 4
PEAK : 24
  version    : 1
  time stamp : 1404898642
    Ch   Position       Value
     0   0              1
     1   0              1
data : 32
End

----------------------------------------
Sample Rate : 44100
Frames      : 4
Channels    : 2
Format      : 0x00010006
Sections    : 1
Seekable    : TRUE
Duration    : 00:00:00.000
Signal Max  : 1 (0.00 dB)
```

**Comment by pocketprecision** [comment]
Reading 32-bit float files that stick to the spec and thus contain an (empty) fact chunk also currently fails due to the chunksize being 18 instead of 16 for standard PCM. Relevant code snippet from `read_fmt_chunk(fid)` in `wavfile.py`:

    if comp not in KNOWN_WAVE_FORMATS or size > 16:
        comp = WAVE_FORMAT_PCM
        warnings.warn("Unknown wave file format", WavFileWarning)
        if size > 16:
            fid.read(size - 16)

IMO `size > 16` is not a valid criterion to cast the format to `WAVE_FORMAT_PCM`.  My workaround:

    if comp not in KNOWN_WAVE_FORMATS:
        comp = WAVE_FORMAT_PCM
        warnings.warn("Unknown wave file format", WavFileWarning)

    if size > 16:
        fid.read(size - 16)
        warnings.warn("Unsupported fact chunk ignored", WavFileWarning)

**Comment by pv** [comment]
Several issues were fixed a short while ago, see the code in the master branch.

**Comment by pv** [comment]
Closing (fixed)
