### ISSUE TITLE
cwt should also return complex array 

### ISSUE THREAD

**Issue by jankoslavic** [scipy/scipy#3793]
If the wavelet or data are complex, the function cwt should also return a complex array. Currently, the allocation for the output is performed for real numbers, only.

PS: currently, the cwt gives wrong results (real only) if for example the complex morlet wavelet is used.

regards,
Janko

**Comment by rgommers** [comment]
IIRC the docstring of ``cwt`` was fixed recently for the output shape issue pointed out by @argriffing 

Labeling this as a bug in ``cwt`` for the complex number issue. @jankoslavic I'm sure you're right, but for someone getting started on this it would be helpful to include a code snippet that reproduces the wrong results.

**Comment by jankoslavic** [comment]
Dear @rgommers thank you for looking at this issue. 
I have prepared a snippet here:
https://gist.github.com/jankoslavic/ed46141345a096f663d1

you can see that it behaves correctly the wavelets.cwt dtype is changed to complex:
output = np.zeros([len(widths), len(data)], **dtype=complex**)

**Comment by rgommers** [comment]
Thanks @jankoslavic. Clearly a bug. Needs fixing, but unfortunately this will probably then break some user code that now works. The example in the ``cwt`` docstring for example crashes (MPL doesn't like complex input):

    import numpy as np

    from scipy import signal
    import matplotlib.pyplot as plt


    # Example that doesn't work in 0.16.x with Morlet wavelet
    t = np.linspace(-1, 1, 200, endpoint=False)
    sig  = np.cos(2 * np.pi * 7 * t)
    widths = np.arange(1, 31)
    cwtmatr = signal.cwt(sig, signal.morlet, widths)
    select = 7

    plt.figure()
    plt.plot(t[50:-50], np.abs(cwtmatr[select-1, 50:-50]), label=select)
    plt.plot(t[50:-50], np.real(cwtmatr[select-1, 50:-50]), label='real')
    plt.plot(t[50:-50], np.imag(cwtmatr[select-1, 50:-50]), label='imag')
    plt.legend()


    # Example from docstring with Ricker wavelet
    plt.figure()
    t = np.linspace(-1, 1, 200, endpoint=False)
    sig  = np.cos(2 * np.pi * 7 * t) + signal.gausspulse(t - 0.4, fc=2)
    widths = np.arange(1, 31)
    cwtmatr = signal.cwt(sig, signal.ricker, widths)
    plt.imshow(cwtmatr, extent=[-1, 1, 31, 1], cmap='PRGn', aspect='auto',
               vmax=abs(cwtmatr).max(), vmin=-abs(cwtmatr).max())

    plt.show()

What also needs checking is ``signal.find_peaks_cwt``. It doesn't have any tests for wavelets other than ``ricker`` at the moment. Should be tested with all wavelets in ``ricker`` at least.

**Comment by rgommers** [comment]
I'm not sure what the best fix is here. Possibilities:
- always return a complex array (breaks user code, see example with ricker above)
- only return complex if the input is complex (probably no good, real input + morlet still broken)
- check for nonzero values in output, and if there aren't any then only return real part (very ugly and will break something, I'm just not sure yet what)
- decide that the continuous wavelets in ``signal`` are just junk and throw them all out

Other options, preferences?

**Comment by jankoslavic** [comment]
throwing cwt out would not be a good solution. 

CWT should always give complex result. Please check the eq (1) and (2) in: http://lab.fs.uni-lj.si/ladisk/data/pdf/Damping%20identification%20with%20the%20Morlet-wave.pdf
(origin source is the A Wavelet Tour of Signal Processing, 3rd ed. Stéphane Mallat. Academic Press, dec. 2008.)

**Comment by domengorjup** [comment]
Together with @jankoslavic  we have now resolved some of the issues discussed here by adding a dtype argument to signal.cwt, along with some other additions, such as a Morlet wavelet function, designed to work with signal.cwt. We have opened a pull request (#7076), and would greatly appreciate your comments.

**Comment by domengorjup** [comment]
The build issues our pull request originally had are now resolved.

Our solution is designed not to break any existing code, but would without a doubt benefit from further input by more experienced contributors. I would invite everyone with knowledge on the subject to check it out.

**Comment by jankoslavic** [comment]
Dear @rgommers would you have time to check-out the pull request (#7076)? For our application this looks fine. We have added Morlet2 method to leave the Morlet method untouched. Looking forward to your comments.

**Comment by rgommers** [comment]
@jankoslavic @domengorjup thanks for trying to tackle this, and apologies for the very delayed response - March was an insane month for me, so this fell through the cracks. I'll mark gh-7076 for the next release (1.0), so there'll be a reminder to review it before branching 1.0

**Comment by rgommers** [comment]
gh-7076 is now merged, so closing. Thanks @jankoslavic and @domengorjup
