### ISSUE TITLE
Input parameter 'sym' in scipy.signal.gaussian not causing the effect as documented

### ISSUE THREAD

**Issue by ajkswamy** [scipy/scipy#3799]
Hello

Documentation says that sym in scipy.signal.gaussian toggles the output between being symmetric and periodic. The output is symmetric for either value of sym. Here is the test code:

from scipy import signal
import numpy as np
from matplotlib import pyplot as plt

nPts = 512
std = 32
win1 = signal.gaussian(nPts, std, sym=True)
win2 = signal.gaussian(nPts, std, sym=False)

plt.plot(range(nPts), win1, 'b-x')
plt.plot(range(nPts), win2, 'r-o')
plt.show()

There are small differences in the values of the output sequences generated, but the symmetry of the output is not affected.

Thanks
Ajay

**Comment by rgommers** [comment]
question seems answered and the docstring currently says:
```
sym : bool, optional
    When True (default), generates a symmetric window, for use in filter
    design.
    When False, generates a periodic window, for use in spectral analysis.
```

seems reasonable enough and doesn't look like a bug, so closing
