### ISSUE TITLE
SuperLU is too slow

### ISSUE THREAD

**Issue by qnzhou** [scipy/scipy#3831]
I have noticed that spsolve hangs during solve.  Here are my system setting: 

OS: mac 10.9.4
Python version: 2.7.6
Scipy version: 0.14.0

I have created a simple test script to illustrate the bug:
https://dl.dropboxusercontent.com/u/29899857/scipy_test.zip

With scipy 0.13, the script finishes within seconds:

``` python
  > ./scipy_test.py 
  Before solve
  After solve
  545.636841049
```

However, with scipy 0.14, it hangs after printing "Before solve".  I have tried other matrices as well, besides the simple matrices (diagonal matrix), scipy hangs every time.

I have also observed this problem on Linux systems.

**Comment by argriffing** [comment]
I'm not sure what were the plans mentioned here, but I just thought I'd bump/ping this old discussion...

**Comment by pv** [comment]
Probably the plan is to give sufficient amount of polish to https://github.com/rc/scikit-umfpack
and then make sure scipy.sparse works together with it sensibly.

Alternatively, there might be other license-compatible and more efficient sparse lu codes out there, but this doesn't seem super likely...

**Comment by rc** [comment]
FYI: The umfpack scikit is living: https://scikits.appspot.com/scikit-umfpack

**Comment by nonhermitian** [comment]
Recently, the Anaconda Python distro and Intel distro make use of the Intel MKL by default. It is possible to use ctypes to access the MKL sparse solver. In our work, we see timings many times faster than SuperLU, even when doing single-thread comparisons.

**Comment by pv** [comment]
Yes, and as noted above, UMFPACK is also faster and moreover free software.

**Comment by ev-br** [comment]
Apparently, there are multiple free and non-free alternatives, all external. There's not much to do within scipy, so closing.
