### ISSUE TITLE
for asymmetric matrices csgraph laplacian uses in-degree to compute diagonal but documentation says out-degree

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#3838]
http://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csgraph.laplacian.html

```python
>>> import numpy as np
>>> from scipy.sparse import csgraph
>>> a = np.arange(4).reshape((2,2))
>>> csgraph.laplacian(a)
array([[ 2, -1],
       [-2,  1]])
>>> a
array([[0, 1],
       [2, 3]])
```

I think out-degree is more standard (i.e. make rows sum to zero), or at least this is the only way I've seen it written anywhere else.  For example the networkx directed laplacian implementation uses out-degree.  Scikit-learn seems to use laplacians only of symmetric matrices.

This doesn't really look tested in the unit tests.  I would be surprised if switching in/out degree laplacians would cause them to fail, not that I'm suggesting to do that right now.

**Comment by rgommers** [comment]
@argriffing gh-3827 is merged, so can this be closed?
