### ISSUE TITLE
cKDTree.query_pairs could return a (n, 2) ndarray rather than a set of pairs

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#3840]
While it is mathematically correct to return a set of pairs rather than a list or an ndarray of pairs from `cKDTree.query_pairs`, ndarrays are often more convenient, and the conversion from one to the other can be very costly (in my case, using `np.fromiter` -- the fastest solution I could find) still takes more than twice longer than the call to `query_pairs` itself).
I am hoping that directly building a ndarray rather than a set in the Cython implementation of `query_pairs` would improve this issue.

**Comment by sturlamolden** [comment]
Implemented in https://github.com/scipy/scipy/pull/4890

**Comment by jackd** [comment]
I know this is an old issue, but I was using this functionality until a recent upgrade to scipy, and now it seems to have disappeared (though the documentation still mentions it). Oddly I've scanned older version documentation and that seems to be the case for all versions, and I can't remember what version of scipy my code relied on. I'm very confused... :S

[1.3.0 query_paris docs](https://docs.scipy.org/doc/scipy-1.3.0/reference/generated/scipy.spatial.cKDTree.query_pairs.html#scipy.spatial.cKDTree.query_pairs)
[1.3.0 sparse_distance_matrix docs](https://docs.scipy.org/doc/scipy-1.3.0/reference/generated/scipy.spatial.cKDTree.query_pairs.html#scipy.spatial.cKDTree.sparse_distance_matrix)

**Comment by AtsushiSakai** [comment]
@jackd Hi. I think `cKDTree` of SciPy v1.4.1 still has these functionalities. In my environment, it works correctly.

**Comment by AtsushiSakai** [comment]
I think it is ok to close this issue, because the requested functionalities are provided stil now.
