### ISSUE TITLE
weave.inline fails to pickup recompiled version with force=1

### ISSUE THREAD

**Issue by asmirnov69** [scipy/scipy#3849]
It looks like weave.inline call like given below fails to pick up recompiled version of t.cc:

<pre>
scipy.weave.inline('std::cout &lt;&lt; "Hello, world! " &lt;&lt; ff(12, aa, bb) &lt;&lt; std::endl;', ['aa', 'bb'], type_converters = scipy.weave.converters.blitz, include_dirs = ["."], headers = ['"t.h"'], sources = ['t.cc'], verbose = 2, force = 1)
</pre>

t.cc recompiled according to verbose output. However current and subsequent calls somehow ending up with old version.

I found workaround: reset function_cache to empty dict helps. After that proper version of t.cc is used:

<pre>
scipy.weave.inline_tools.function_cache = {}
</pre>

 Would it be good idea to reset this function_cache in the case of force = 1?

**Comment by person142** [comment]
Closing since weave is no longer a part of SciPy. This issue is now tracked at https://github.com/scipy/weave/issues/7.
