### ISSUE TITLE
io.mmread can not read large matrices (who do not fit in memory)

### ISSUE THREAD

**Issue by huitseeker** [scipy/scipy#3900]
in [`scipy/io/mmio.py`, ca line 462](https://github.com/scipy/scipy/blob/master/scipy/io/mmio.py#L463), in the code path called by `io.mmread` :

``` python
                # TODO use iterator (e.g. xreadlines) to avoid reading
                # the whole file into memory
```

And indeed, there's a brutal memory read [a few lines above](https://github.com/scipy/scipy/blob/master/scipy/io/mmio.py#L455).

The whole MatrixMarket format exists to exchange _large_ sparse matrices. This severely limits the usefulness of the MMFile class.

**Comment by rgommers** [comment]
gh-3970 is still open, and should probably be rebased and merged as is - the bells and whistles aren't needed if it's an improvement. closing this issue, because the PR alone is good enough to have open, no extra info here.

I'll comment on the PR as well.
