### ISSUE TITLE
Sparse matrix slice segmentation fault

### ISSUE THREAD

**Issue by psinger** [scipy/scipy#3908]
I have a large csr_matrix with the following parameters:

In [5]: a.shape
Out[5]: (360417, 360417)

In [6]: a.nnz
Out[6]: 15464020

I generated it the following way:

a = sp.sparse.csr_matrix((values, (i_indices, j_indices)), shape=shape, dtype=np.float32)

where values is a list holding the values, i_indices and j_indeces are also lists holding the corresponding indices.

Everything works fine, I can access all values by e.g., a[0,0] or a[0,3] and so on. I can also do all operations like e.g., a.floor().

However, as soon as I slice the matrix, I get a segmentation fault e.g., causes by a[0,:2].

Any idea?

**Comment by WarrenWeckesser** [comment]
> The referenced issue by pv seems to be the problem.

That problem has been fixed by https://github.com/scipy/scipy/pull/3781, which is in release 0.15.  Can we close this issue?
