### ISSUE TITLE
wavelets: pywavelets integration and api

### ISSUE THREAD

**Issue by aaren** [scipy/scipy#3931]
@rgommers I'm looking at fixing the issues blocking [pywavelets](https://github.com/rgommers/pywt) integration: issues [#19](https://github.com/rgommers/pywt/issues/19), [#38](https://github.com/rgommers/pywt/issues/38) and [#46](https://github.com/rgommers/pywt/issues/46).

Once these are fixed, we can move pywt in. With ~50 public members, the current thinking is to put it in a new wavelets subpackage `scipy.wavelets`. This will mean two wavelets locations, with the other being `scipy.signal.wavelets`. We would then deprecate the discrete functionality in `scipy.signal.wavelets`.

Continuous wavelets need looking at as well and there are a number of existing code bases for this, but an api needs deciding on. Once ready, continuous can be added to `scipy.wavelets` as well and then all of `scipy.signal.wavelets` would be deprecated.

**Comment by rgommers** [comment]
PyWavelets is a well-maintained separate package, and we no longer plan to move it into SciPy. So what's left is to clean up `scipy.signal`. For that we have a roadmap entry:

_Wavelets: what’s there now doesn’t make much sense. Continuous wavelets only at the moment - decide whether to completely rewrite or remove them. Discrete wavelet transforms are out of scope (PyWavelets does a good job for those)._

so closing this. thanks all!
