### ISSUE TITLE
fmin_slsqp crashes without inequalities constraints

### ISSUE THREAD

**Issue by enricouwyo** [scipy/scipy#3988]
If you try to use fmin_slsqp without inequalities constraints it will crash with the following error:

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    fmin_slsqp(func, x0, fprime=jac,f_eqcons=funcceq, fprime_eqcons=funccjac, iter=20)
  File "/usr/lib/python2.7/dist-packages/scipy/optimize/slsqp.py", line 354, in fmin_slsqp
    a = concatenate((a,zeros([la,1])),1) 
ValueError: arrays must have same number of dimensions

On a first investigation it looks like the variable 'la' gets undefined somehow, attempt at fixing this problem have been unsuccessful, suggesting a bigger problem. To replicate the error please use the functions below (taken from the example on the website). Save a file as flowrunanalytic.py with the content below and a file test.py (content further down). Then run ' python test.py  '. 

Python version is 2.7.3, scipy version is the latest available (downloaded on Sunday September 7th).

Any suggestion on how to fix this?

flowrunanalytic.py : 

```python
import numpy as np
def func(x, sign=-1.0):
# Objective function
    return sign*(2*x[0]*x[1] + 2*x[0] - x[0]**2 - 2*x[1]**2)
    
def jac(x, sign=-1.0):

#	Jacobian of the function
     dfdx0 = sign*(-2*x[0] + 2*x[1] + 2)
     dfdx1 = sign*(2*x[0] - 4*x[1])
     return np.array([ dfdx0, dfdx1 ])
     
def funcceq(x):
#	Equality constraint function
		return np.array([x[0]**3 - x[1]])
		
def funccjac(x):
#	Jacobian of equality constrain function
		return np.array([3.0*(x[0]**2.0), -1.0])
		
def funccin(x):
# Inequality constraint function

		return np.array([x[1] - 1])
		
def funccjacin(x):
#	Jacobian of inequality constraint function

		return np.array([0.0, 1.0])
```

test.py: 

```python
import numpy as np
from scipy.optimize import fmin_slsqp
from flowrunanalytic	import func, jac , funcceq, funccjac, funccin, funccjacin
x0 = [ -1.0, 1.0 ]

fmin_slsqp(func, x0, fprime=jac,f_eqcons=funcceq, fprime_eqcons=funccjac, iter=20)
```

**Comment by dlax** [comment]
Cannot reproduce with version 0.14.1.
