### ISSUE TITLE
Problems with Mann Whitney test. Function tiecorrect returns negative values

### ISSUE THREAD

**Issue by Lanumek** [scipy/scipy#4017]
I am trying to perform Mann-Whitney test on a real data set using scipy. I extracted an example where the problem occurs. It seems that the function tiecorrect returns negative value which is the source of problem in my opinion. Here is my case

import scipy.stats

x = [1.] \* 163 + [2.] \* 81 + [3.] \* 40 + [4.] \* 6 + [5.] \* 2
y = [1.] \* 1007 + [2.] \* 362 + [3.] \* 99 + [4.] \* 27 + [5.] \* 13

print scipy.stats.mannwhitneyu(x,y)

I have successfully performed the MW test on the same case using SPSS and R but I would like to figure out how to do with in scipy.

**Comment by josef-pkt** [comment]
I just found by chance the corresponding stats.stackexchange question
http://stats.stackexchange.com/questions/116315/problem-with-mann-whitney-u-test-in-scipy

**Comment by rgommers** [comment]
This now returns `MannwhitneyuResult(statistic=193405.5, pvalue=4.6746515724048606e-05)`. Looks like that was fixed when `tiecorrect` was rewritten in gh-5554
