### ISSUE TITLE
improve accuracy of scipy.stats.gompertz distribution for small x.

### ISSUE THREAD

**Issue by pbrod** [scipy/scipy#4031]
Currently the cdf-ppf round trip for small x return wrong values as shown here:
In [85]: gompertz.ppf(gompertz.cdf(1e-100,1),1)
Out[85]: 0.0

By replacing exp(x)-1 with expm1(x) and log(1+x) with log1p(x) one can improve the accuracy of the gompertz distribution (_logpdf, _cdf and _ppf)  to machine precision for small x.

Replacing  _logpdf, _cdf and _ppf with

    def _logpdf(self, x, c):
        return log(c) + x - c * expm1(x)

    def _cdf(self, x, c):
        return -expm1(-c * expm1(x))

    def _ppf(self, q, c):
        return log1p(-1.0 / c * log1p(-q))

one achieves 
 In [92]: gompertz.ppf(gompertz.cdf(1e-100,1),1)
Out[92]: 1e-100

**Comment by rgommers** [comment]
Thanks @pbrod, fixed in gh-4407.
