### ISSUE TITLE
improve accuracy of scipy.stats.rayleigh distribution for large x

### ISSUE THREAD

**Issue by pbrod** [scipy/scipy#4034]
Currently the sf-isf round trip for large x return wrong values as shown here:
In [85]: rayleigh.isf(rayleigh.sf(9,1),1)
Out[85]: 9.0000752648062754

By replacing exp(x)-1 with expm1(x) and log(1+x) with log1p(x) one can improve the accuracy of the rayleigh distribution (_cdf, _sf, and _ppf) to machine precision for large x.

Replacing _cdf  and _ppf with

    def _cdf(self, r):
        return - expm1(-r * r / 2.0)

    def _sf(self, r):
        return exp(-r * r / 2.0)

    def _isf(self, q):
        return sqrt(-2 * log(q))

    def _ppf(self, q):
        return sqrt(-2 * log1p(-q))

one acheives 
In [86]: rayleigh.isf(rayleigh.sf(9,1),1)
Out[86]: 9.0

**Comment by rgommers** [comment]
Thanks @pbrod
