### ISSUE TITLE
improve accuracy of scipy.stats.truncexpon distribution for small x

### ISSUE THREAD

**Issue by pbrod** [scipy/scipy#4035]
Currently the cdf-ppf round trip for small x return wrong values as shown here:
In [85]: truncexpon.ppf(truncexpon.cdf(1e-100,1),1)
Out[85]: 0.0

By replacing exp(x)-1 with expm1(x) and log(1+x) with log1p(x) one can improve the accuracy of the truncexpon distribution (_pdf, _logpdf, _cdf and _ppf) to machine precision for small x.

Replacing _pdf, _logpdf, _cdf and _ppf with

    def _pdf(self, x, b):
        return exp(-x) / (-expm1(-b))

    def _logpdf(self, x, b):
        return - x - log(-expm1(-b))

    def _cdf(self, x, b):
        return expm1(-x) / expm1(-b)

    def _ppf(self, q, b):
        return - log1p(q * expm1(-b))

one achieves 
In [92]: truncexpon.ppf(truncexpon.cdf(1e-100,1),1)
Out[92]: 1e-100

**Comment by maniteja123** [comment]
@rgommers I think even this is on the similar lines. In the PR #4050 , I think only the test case is updated, but not the implementation of ``ppf``, ``cdf`` in ``truncexpon``. I checked that PR, and it is inactive, but if I tried to pull it and use it, it is way behind master branch. Can I solve this also, just that it is Sunday today, I want to do something useful.

**Comment by rgommers** [comment]
Sure, if you could complete that fix and send it as a new PR that would be helpful.
