### ISSUE TITLE
misc.imsave needs more options

### ISSUE THREAD

**Issue by kandel3** [scipy/scipy#4036]
Hi Folks,

For your consideration, I think it would be very useful if misc.imsave had optional arguments to specify format specific arguments like as JPEG image quality or enabling progressive mode. 

Right now I can't make web friendly files because my JPEGs are too large and don't play well until fully loaded.

In C++ land we do it like this,
    std::vector<int> params;
    params.push_back(IMWRITE_JPEG_PROGRESSIVE);
    cv::imwrite(name, im,params);

Also I believe PIL has this functionality:
http://stackoverflow.com/questions/6788398/how-to-save-progressive-jpeg-using-python-pil-1-1-7

**Comment by MartinThoma** [comment]
@kandel3 It seems to me that this is out of scope. You can save it in a lossless format and then use PIL to do image format specific stuff.

**Comment by rgommers** [comment]
Agreed. We want ``imsave`` to be fairly minimal; anything more than "get an image written as a standard format" (which it does already) probably is best left to https://imageio.github.io/ or other image handling libs.

Since there are several good solutions out there already, closing this.
