### ISSUE TITLE
scipy.interpolate.interp1d  not stable on supporting points with nans

### ISSUE THREAD

**Issue by Maglond** [scipy/scipy#4060]
Dear scipy developers,

the current scipy.interpolate.interp1d linear interpolation propagates nans in the supporting points to the right. The test code:
###### 

import numpy as np
from scipy.interpolate import interp1d

a=np.array([4,50,np.nan,77,88])
bt=np.arange(len(a))
f=interp1d(bt,a)
print f(bt)
###### 

prints the result:
[  4.  50.  nan  nan  88.] 
instead of the expected supporting points a.

Best regards
Kai

**Comment by ev-br** [comment]
Coming back to this ticket after almost five years, I still agree with Alex's calling this off-by-epsilon behavior. If user code needs preserve the input values exactly, then it can interpolate and then replace unwanted nans by input values. More complicated nan handling belongs to a separate layer. Closing. Thanks for the bug report @Maglond , thanks Alex.
