### ISSUE TITLE
Mannwhitneyu with arrays full of nan still reports significance

### ISSUE THREAD

**Issue by jradinger** [scipy/scipy#4067]
Hi,

in my version of scipy (0.14.0) Mannwhitneyu shows a strange behaviour.
Running the Mannwhitneyu on two arrays filled with nan I get a p-value:

import numpy as np
from scipy import stats
a=np.array([np.nan,np.nan,np.nan,np.nan,np.nan])
b=np.array([np.nan,np.nan,np.nan,np.nan,np.nan])
ranked = stats.rankdata(np.concatenate((a,b)))
stats.tiecorrect(ranked)
stats.mannwhitneyu(a,b)
(0.0, 0.0060928901776724055)

here to compare with the results of the t-test:
stats.ttest_ind(a,b)
(nan, nan)

/Johannes

**Comment by andreas-h** [comment]
you mean replace

    x = asarray(x)
    y = asarray(y)

by
    
    try:
        x = asarray(x)
        y = asarray(y)
    except ValueError:
        return np.nan, np.nan

If you agree that's the way to go I can prepare a PR.
