### ISSUE TITLE
`fractional_matrix_power` has problems with integer matrices

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4068]
The bug https://github.com/numpy/numpy/issues/5166 also affects `fractional_matrix_power`.  This class of bugs probably extends to many scipy matrix function implementations whose derivations originally expected 64 bit precision real floating point input matrices.

**Comment by sethtroisi** [comment]
This is an old bug report warning about a well know issue with numpy w.r.t overflow. No need to keep this bug around.
