### ISSUE TITLE
entropy in Scipy

### ISSUE THREAD

**Issue by ashkanamiri** [scipy/scipy#4080]
Hi

I think there is a problem in scipy.stats.entropy and it calculates wrong values for the entropy of a population of samples.

The function "entropy" does not consider widths of histogram bins (refer to http://en.wikipedia.org/wiki/Entropy_estimation#Histogram_estimator). Of course, one can try to provide an array for widths of bins as the argument "qk", however, the function will normalize "qk" to calculate Kullback-Leibler divergence.

It would be nice if you would solve this problem.

**Comment by sariagoudarzvand** [comment]
Any update on this?
@ashkanamiri  were you able to calculate differential entropy?

**Comment by Barbany** [comment]
There's clearly something wrong with this function and it's not only about having a discretized input as someone mentioned above. I tried to compute the entropy of a sequence of ones (with int8 data type if discretization was an issue). Clearly the output should be 0, but instead:
```
>>>import numpy as np
>>>from scipy.stats import entropy
>>>entropy(np.ones(1000, dtype=np.int8), base=2)
9.965784284662083
```

For reproducibility:
* numpy=1.18.1
* scipy=1.4.1

**Comment by vnmabus** [comment]
Couldn't the Vasicek estimator be used for this? It seems simple enough to implement and does not require binned data.

Vasicek, Oldrich (1976), "A Test for Normality Based on Sample Entropy", Journal of the Royal Statistical Society, Series B, 38 (1), JSTOR

**Comment by mdhaber** [comment]
Looks like it to me. Plenty of references, and it looks common to use it just as an entropy estimate (as well as part of a hypothesis test). I think a PR would be welcome!

**Comment by vnmabus** [comment]
Should this be a new function, e.g. `differential_entropy`?

**Comment by mdhaber** [comment]
After some research, I think so. That would avoid confusion with limiting density of discrete points.
