### ISSUE TITLE
deal with nan inputs more consistently

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4086]
Because [IPython](https://github.com/ipython/ipython) + [pandas](https://github.com/pydata/pandas) seems to be becoming the usual interface to the scipy stack, and because pandas uses NaN to mean NA, more of the lower-level projects like scipy are seeing NaN inputs that are not the results of undefined operations.

Debugging these NaN-related problems seems to involve multiple issues that are usually not distinguished in the original bug reports.

1) scipy propagates NaN more than strictly necessary, regardless of NaN semantics
2) scipy complains about NaN creation, but not necessarily about NaN propagation
3) scipy doesn't generally use NaN to mean 'missing data'.

Technically, none of these issues are bugs.  Improving (1) could be helpful to avoid misunderstandings about how scipy treats NaNs, and maybe it would be worth adding more complaints for (2).  I don't think scipy will ever change (3) until a numpy-like layer implements separate NA and NaN.

https://github.com/scipy/scipy/issues/4060
https://github.com/scipy/scipy/issues/4067
https://github.com/scikit-learn/scikit-learn/issues/3782

**Comment by rgommers** [comment]
Discussion on this issue is taking place on gh-571.

**Comment by mdhaber** [comment]
I think this is superseded by gh-14651, which tracks our progress towards consistent `nan_policy` support in stats. Would you agree @tirthasheshpatel?
I'll close this but list it as a related issue in gh-14651.
