### ISSUE TITLE
ENH: Add Fano factor function to scipy.stats

### ISSUE THREAD

**Issue by toddrjen** [scipy/scipy#4092]
Currently, `scipy.stats` has a function `variation`, which computes the coefficient of variation (`std/mean`).  

However, there is a closely-related function called the Fano factor (http://en.wikipedia.org/wiki/Fano_factor).  While the coefficient of variation is `std/mean`, the Fano factor is `var/mean`.  Different random distributions have different Fano factors.  It is particular important as a measure of how well similar a random process is to a Poisson process (which is important for everything from particle detectors to neurons), since a purely Poisson process has a Fano factor of 1.

So I think it would be good to have a `fano` function in `scipy.stats`, to give the counterpart to the `variation` function but more importantly because Poisson processes are critically important to many fields.

**Comment by chrisb83** [comment]
The 3-liner `signaltonoise` has been removed in the meantime (#9097).

**Comment by rgommers** [comment]
no one clearly in favor (more the opposite), and we're removing or discouraging such 1-3 line functions. as `dispersion_index` it makes even less sense to me, the name doesn't mean much. changing my vote to -1.

So let's close this. thanks for proposing though @toddrjen
