### ISSUE TITLE
Clarify Mathieu function documentation

### ISSUE THREAD

**Issue by cimatosa** [scipy/scipy#4096]
Hi, I came across the Mathieu functions and could not get the values from scipy.special.mathieu_cem in accordance with the solutions of the corresponding differential equation.

for q == 0 one should get simply cos(sqrt(a) \* t), but what scipy.special.mathieu_cem returns is more like cos(a \* t). So I assumed that the order parameter a is just defined differently. but then still the solutions for q != 0 do not math. wolfram alpha gives results close to the ones I got from solving the differential equation.

So I conclude the Mathieu functions in scipy are either wrong or do not correspond to the standard definition (see wikipedia, wolfram)

Cheers, Richard

**Comment by mdhaber** [comment]
Will probably require some research, but once the math is understood, doesn't seem like it would be hard to address in the documentation.

**Comment by mdhaber** [comment]
I can see how correspondence with the Mathworld reference is not as obvious, but I found the function to correspond closely with information on Wikipedia.

> for q == 0 one should get simply cos(sqrt(a) * t),

Wikipedia states that they should be proportional to $\cos(nx)$ and $\sin(nx)$.

<img width="1388" alt="image" src="https://github.com/user-attachments/assets/ee1846cd-0e83-4feb-998b-ea33b917d55c">

Indeed, they are, if we recognize `m` to correspond with $n$.

<details>

```python3
import numpy as np
from scipy import special
import matplotlib.pyplot as plt

m = 4
q = 0
x = np.linspace(0, 360, 300)

y, dy = special.mathieu_cem(m, q, x)
plt.plot(x, y)
plt.plot(x, np.cos(m*x/180*np.pi), '--')

y, dy = special.mathieu_sem(m, q, x)
plt.plot(x, y)
plt.plot(x, np.sin(m*x/180*np.pi), '--')

plt.legend(('mathieu_cem', 'cos(mx)', 'mathieu_sem', 'sin(mx)'))
```

</details>

<img width="925" alt="image" src="https://github.com/user-attachments/assets/3d657876-eb90-4cf9-92a4-94429f34ad21">

---

> I was mistaken that 'a' as the characteristic value, corresponds to the order m used by mathieu_cem. It is rather that way, that for a given parameter 'q' we can calculate the characteristic value 'a' such that the solutions become periodic with period 2pi. And with that condition fulfilled, there exists a hole bunch of solutions, named by the integer parameter m.

This is addressed by the definition of $ce_n$ and $se_n$:

<img width="1386" alt="image" src="https://github.com/user-attachments/assets/ae94f371-d21e-4e83-8b9a-e21921690e3f">

---

> There seems to be still some contradictions, because the reference claims for the even functions to have a period of pi, where a simple plot shows that the scipy mathieu functions have 2pi period, both, even and odd

Actually, a plot confirms the property claimed by the reference.

<details>

```python3
import numpy as np
from scipy import special
import matplotlib.pyplot as plt

q = 100
x = np.linspace(0, 360, 300)
y, dy = special.mathieu_cem(np.asarray([1, 3, 5])[:, np.newaxis], q, x)
plt.plot(x, y.T)
plt.legend(('m = 1', 'm = 3', 'm = 5'))
```

</details>

Period $2\pi$ for odd $m$.
<img width="990" alt="image" src="https://github.com/user-attachments/assets/a8358a3d-2cdc-4334-b825-360825fd2572">

Period $\pi$ for even $m$.
<img width="968" alt="image" src="https://github.com/user-attachments/assets/75118f22-c2d7-49a2-b8ba-9edf43ebd292">

---

> Further the value for ce_m(x=0) is actually arbitrary as we have a homogeneous ODE. So where does the actual value for that implementation come from?

<img width="1369" alt="image" src="https://github.com/user-attachments/assets/4fe977c7-cecf-481f-8559-7a523853327b">

---

@j-bowhay, it looks like you began to review gh-17333. I closed it for a few reasons, but would you be interested in either writing or reviewing a PR that added some documentation to the `mathieu_cem` and `mathieu_sem` functions to close this issue? To keep the scope manageable, I think it should:

* identify the differential equation the function solves
* identify the relationship between the arguments of the function and the variables in the differential equation
* reference Wikipedia for other properties and the normalization scheme
* show one example, e.g. of the $\pi$ or $2\pi$ periodicity depending on $m$.

**Comment by j-bowhay** [comment]
I am currently away travelling until next year so unfortunately I have quite limited computer access
