### ISSUE TITLE
scipy.optimize.line_search returned values do not match documentation

### ISSUE THREAD

**Issue by bpires-ualberta** [scipy/scipy#4101]
Hello!  The documentation for `scipy.optimize.line_search` indicates three return values, but a quick code inspection reveals that more values are being returned.

Moreover, `a_0 = None` may happen, even though this is not indicated in the function. 

`scipy.optimize.linesearch.scalar_search_wolfe1` seems to have relevant additional information in its documentation.

Thank you very much again for providing scipy to us.

**Comment by sethtroisi** [comment]
PR merged claiming to fix very old issue.
