### ISSUE TITLE
ndimage._ni_support._normalize_sequence() fails with numpy.int64

### ISSUE THREAD

**Issue by pllim** [scipy/scipy#4106]
Windows 7 64-bit with Anaconda. Traceback in attached screenshot.

```
>>> import numpy as np
>>> import scipy
>>> scipy.__version__
'0.14.0'
>>> from scipy.ndimage._ni_support import _normalize_sequence
>>> x = np.int64(21)
>>> _normalize_sequence(x, 0)
```

Might be related to numpy/numpy#2951 ?
![untitled](https://cloud.githubusercontent.com/assets/2090236/4794882/c8737414-5df7-11e4-93b1-11a18868db41.png)

**Comment by ev-br** [comment]
Fixed in https://github.com/scipy/scipy/pull/5444, closing.
