### ISSUE TITLE
griddata should also accept multi-dimensional lists

### ISSUE THREAD

**Issue by jcummings2** [scipy/scipy#4123]
When using scipy.interpolate.griddata (or more broadly a scipy.interpolate.interpnd.NDInterpolatorBase derived object), the xi parameter should work for multi-dimensional lists. It currently only works for multi-dimensional tuples and single dimensional lists or ndarrays.

See also http://stackoverflow.com/q/23018799/1518546

**Comment by FlorianFranzen** [comment]
The missing support for list can be quite annoying, given that ```numpy.meshgrid(...)``` returns a list, which if passed to ```griddata``` without wrapping it in a ```tuple(...)``` throws a very misleading dimension mismatch error.
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-195-c1d2e11512a7> in <module>()
----> 1 frame_int = griddata(points, values, grid_xy).T

/home/user/.local/lib/python3.5/site-packages/scipy/interpolate/ndgriddata.py in griddata(points, values, xi, method, fill_value, rescale)
    216         ip = LinearNDInterpolator(points, values, fill_value=fill_value,
    217                                   rescale=rescale)
--> 218         return ip(xi)
    219     elif method == 'cubic' and ndim == 2:
    220         ip = CloughTocher2DInterpolator(points, values, fill_value=fill_value,

interpnd.pyx in scipy.interpolate.interpnd.NDInterpolatorBase.__call__()

interpnd.pyx in scipy.interpolate.interpnd.NDInterpolatorBase._check_call_shape()

ValueError: number of dimensions in xi does not match x
```

**Comment by ev-br** [comment]
The matching PR, gh-4124, was closed as a wontfix and this issue was left and forgotten. The discussion in gh-4124 explains why it should not be implemented, the technical detail is this comment:
https://github.com/scipy/scipy/pull/4124#issuecomment-62563338
