### ISSUE TITLE
"Brent" solver dies with UnboundLocalError

### ISSUE THREAD

**Issue by brandon-rhodes** [scipy/scipy#4140]
I am attempting (without success so far) to find the moment of maximum altitude of an Earth satellite passing overhead using the various minimize routines in `optimize` and have encountered the problem that when the Brent solver is started, it dies in the line:

    deltax = rat

in `Brent.optimize` in `optimize.py` because `rat` is not set anywhere in the function above that line. Here is the line in the current version of `optimize.py`:

https://github.com/scipy/scipy/blob/master/scipy/optimize/optimize.py#L1771

Here is a notebook where you can see the live exception (scroll down to `In[133]`):

http://nbviewer.ipython.org/github/brandon-rhodes/astronomy-notebooks/blob/e6ad1e384af03e3ad26f6bce94843df68c8e14b9/Solvers/Earth-Satellite-Passes.ipynb

**Comment by yshahin** [comment]
Is this complete?

**Comment by larsmans** [comment]
You mean fixed?

**Comment by yshahin** [comment]
yeah

**Comment by larsmans** [comment]
Then no. There's a fix in #4155 but that's stalled.
