### ISSUE TITLE
lobpcg "largest" option invalid?

### ISSUE THREAD

**Issue by pv** [scipy/scipy#4174]
The scipy.sparse.linalg.lobpcg docstring claims largest=True computes the largest eigenvalues.
This does not appear to be true, usually it just returns the same as largest=False but in opposite order.

```
>>> A = np.diag(np.arange(1, 100))
>>> x = np.random.rand(99, 6)
>>> w, v = scipy.sparse.linalg.lobpcg(A, x, tol=1e-5, maxiter=20000, largest=False)
>>> w
array([ 1.,  2.,  3.,  4.,  5.,  6.])
>>> w, v = scipy.sparse.linalg.lobpcg(A, x, tol=1e-5, maxiter=20000, largest=True)
>>> w
array([ 6.,  5.,  4.,  3.,  2.,  1.])
```

The proper way to get the largest ones appears to be to apply LOBPCG to -A:

```
>>> w, v = scipy.sparse.linalg.lobpcg(-A, x, tol=1e-5, maxiter=20000, largest=False)
>>> -w
array([ 99.,  98.,  97.,  96.,  95.,  94.])
```

Perhaps best to just remove/deprecate the option, or make it just do the sign flip?

**Comment by pv** [comment]
On a second thought, there's a nasty backward compat issue: `largest=True` is the default value.
Perhaps it's best to just deprecate the `largest` argument altogether (change default value to `None`, and raise deprecation warning if it's not None, saying the argument doesn't actually do anything). It's trivial for the user to do the calculation on `-A` instead.

**Comment by attila-szabo-1** [comment]
The issue is still here. Given ``lobpcg`` works fine on ``-A``, the ``largest`` option should be deprecated or the code modified s.t. it takes the negative of ``A`` first (this shouldn't be hard either).

**Comment by lobpcg** [comment]
The LOBPCG algorithm itself is designed to run only when x is very thin compared to A, i.e., the number of the requested eigenvectors in x is much smaller than the size of the matrix A. To make the code "fool-proof" there is an internal check of the  sizes of x and A, where, if x is not thin, then a standard eigensolver `eigh` is used instead computing all eigenvalues of A but outputting only those requested. There may apparently be a bug in this part of the code, quoted below, not properly handling `largest `option to select the largest eigenvalues from all (may be `eigh`  output is not sorted?) 
 
if (n - sizeY) < (5 * sizeX):
        # Define the closed range of indices of eigenvalues to return.
        if largest:
            eigvals = (n - sizeX, n-1)
        else:
            eigvals = (0, sizeX-1)
        A_dense = A(np.eye(n))
        B_dense = None if B is None else B(np.eye(n))
        return eigh(A_dense, B_dense, eigvals=eigvals, check_finite=False)

**Comment by rc** [comment]
Thanks @lobpcg I will apply the fix.

**Comment by lobpcg** [comment]
> Is the ascending order for the largest eigenvalues what we need - is it consistent with `eigs()`?

Very good question. I have just checked - it is, with the default which='LM' 

We MUST however still fix the lobpcg output order if (n - sizeY) < (5 * sizeX): for largest. Currently they are in ascending order, just coming out of eigh. So the lobpcg line 

      return eigh(A_dense, B_dense, eigvals=eigvals, check_finite=False)

needs proper editing to reverse the order of the output if largest. @rc could you please fix this?

Here is a test to pass for the consistency of the outputs:

     import numpy as np
     from scipy import linalg, sparse
     from scipy.sparse.linalg import lobpcg
     from scipy.sparse import spdiags, issparse
     from scipy.sparse.linalg import lobpcg, eigs
     n = 20
     vals = [np.arange(n, dtype=np.float64) + 1]
     A = spdiags(vals, 0, n, n)
     X = np.random.rand(n, 2)
     eigsl20, vecsl20 = lobpcg(A, X, largest=True, maxiter=100)
     vals20, vecs20 = eigs(A, k=2)
     
     n = 5
     vals = [np.arange(n, dtype=np.float64) + 1]
     A = spdiags(vals, 0, n, n)
     X = np.random.rand(n, 2)
     eigsl5, vecsl5 = lobpcg(A, X, largest=True, maxiter=100)
     vals5, vecs5 = eigs(A, k=2)

**Comment by lobpcg** [comment]
> 
> 
> Thanks @lobpcg I will apply the fix.
> 
> Concerning the symmetry checks - would a warning have a sense here?

The symmetry checks involve nontrivial tolerances for various data types and depend on conditioning of the matrices involved, so difficult to do right. The actual eigensolver uses a lower (or upper) triangular part of the matrices anyway. 

On the other hand, this eigensolver is exactly where lobpcg usually fails, because gramB is not SPD as it should have, so it is good to do something about it. I am yet unsure what exactly to do, and need to collect more info about failures.  LOBPCG fails much more often with np.float32 matrices, so these are good examples to collect the data. I suspect that the lack of symmetry is not the main trouble.

**Comment by rc** [comment]
I have added the proposed test, and (hopefully) fixed the code to pass it.
