### ISSUE TITLE
ENH: scipy.stats to return namedtuples

### ISSUE THREAD

**Issue by clarkfitzg** [scipy/scipy#4192]
It's easier for users to write correct code when they can see the names.

Following pattern from #3991, and discussion from #3665. 

cc @rgommers @WarrenWeckesser @josef-pkt @ev-br 

Here are my notes for a possible naming convention for namedtuple function outputs in scipy.stats:

---

The pattern returned for each element of bayes_mvs is important because it is an estimate with confidence interval. It might be even be worth exposing this one publicly.

bayes_mvs: mean, variance, std_dev
(center, (lower, upper)) -> estimate, minmax

describe: nobs, minmax, mean, variance, skewness, exc_kurtosis
mode: mode, count
sigmaclip: clipped, lower, upper
linregress: slope, intercept, rvalue, pvalue, stderr
anderson: statistic, critical_values, significance_level

Note shapiro doesn't follow the pattern below

**Statistical tests** Includes these functions:
{normaltest, skewtest, kurtosistest, f_oneway, ttest_1samp, ttest_ind, ttest_rel, kstest, ks_2samp, power_divergence, mannwhitneyu, ranksums, wilcoxon, kruskal, friedmanchisquare, ansar, bartlett, levene}

All could share the same output namedtuple:
`Statistic(statistic=X, pvalue=Y)`

spearmanr: correlation, pvalue
pointbiserialr: correlation, pvalue
kendalltau: correlation, pvalue

cumfreq: cumcount, lowerlimit, binsize, extrapoints
histogram: count, lowerlimit, binsize, extrapoints
relfreq: frequency, lowerlimit, binsize, extrapoints

binned_statistic: statistic, bin_edges, binnumber
binned_statistic_2d: statistic, x_edge, y_edge, binnumber
binned_statistic_2d: stat, bin_edges, binnumber

**Comment by rgommers** [comment]
Done in gh-4709, so closing.
