### ISSUE TITLE
Make docs build automatically

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#4214]
Investigate whether it's possible to have them build automatically on readthedoc on every commit to master.
(This came up during Bloomberg event today.)

cc @itziakos, @dimazest

**Comment by pv** [comment]
It's currently building again via this setup https://github.com/pv/scipy-bench-setup/ plus rsync.

**Comment by ev-br** [comment]
Great! Does it automatically work on some machine somewhere?

I wonder if we want to put this into the cloud, was there some sort of discussion about Rackspace when the server went down in the summer 2014. (It's easy for me to say things like this since I know flat nothing about any of these...)

**Comment by rgommers** [comment]
gh-5343 has more links to scripts that can be borrowed.

**Comment by rgommers** [comment]
And some links for Bokeh scripts posted on the ML:

https://github.com/bokeh/bokeh/blob/master/.travis.yml

https://github.com/bokeh/bokeh/blob/master/scripts/build_upload.sh

https://github.com/bokeh/bokeh/blob/master/sphinx/fabfile.py

**Comment by pv** [comment]
The matplotlib approach seems the simplest and best from security POV.

**Comment by pv** [comment]
gh-5383 addresses this via the matplotlib approach.
Updated urls on the doc site accordingly.

**Comment by rgommers** [comment]
Nice, thanks @pv!

The updated urls aren't visible yet on docs.scipy.org, and https://github.com/scipy/docs.scipy.org/commit/21fd04e189 is the only commit I see but it doesn't change urls?

**Comment by pv** [comment]
They are visible on docs.scipy.org for me --- maybe browser cache?

**Comment by rgommers** [comment]
No, I had cleared my browser cache already (I've made that mistake many times). Just tried also on a tablet from which I have never accessed docs.scipy.org before. On both my machine and the laptop I get a view of an empty dir from the Apache server.

**Comment by pv** [comment]
In case you're trying to browse to `https://docs.scipy.org/doc/scipy-dev/` --- there's indeed nothing there, which how it always was. Try https://docs.scipy.org/doc/scipy-dev/reference/

**Comment by pv** [comment]
Ok, the redirects were only added for the https vhost. Should be OK now.
Didn't notice due to https-everywhere...

**Comment by rgommers** [comment]
Thanks, works for me now.
