### ISSUE TITLE
scipy.signal.flattop documentation doesn't list a source for the function

### ISSUE THREAD

**Issue by spott** [scipy/scipy#4234]
There are a whole bunch of flattop window functions for use in signal analysis, a "flattop" isn't descriptive enough, and another source isn't listed.  Does anyone know where this function is from?

**Comment by endolith** [comment]
@spott

> Should scipy.signals contain all those window functions?

Can they be combined into 1 or 2 functions with parameters?  Like instead of if `HFT90D(M=100)`, make it `hft(M=100, N=4, diff=True)`?

**Comment by spott** [comment]
@endolith 

Probably?  I haven't looked at or thought of this for a long time.  I'll try and dig into it this weekend and see what is possible.

**Comment by endolith** [comment]
@spott [Now that we have _cos_win](https://github.com/scipy/scipy/pull/6465#issue-169841440) it would be really easy:  

SFT5M is just `_cos_win(M, [0.209671, 0.407331, 0.281225, 0.092669, 0.0091036])` for instance, taken from Table 5 "Coefficients of Salvatore flat-top window functions".

It might be good to use strings like "SFT5M" to identify the windows?  Then they could be recognized by `get_window()` too, without creating actual functions for each of them.

**Comment by endolith** [comment]
```
flattops = {
    'dantona3': [0.2811, 0.5209, 0.1980],
    'dantona5': [0.21557895, 0.41663158, 0.277263158, 0.083578947,
                 0.006947368],
    'SFT3F': [0.26526, 0.5, 0.23474],
    'SFT4F': [0.21706, 0.42103, 0.28294, 0.07897],
    'SFT5F': [0.1881, 0.36923, 0.28702, 0.13077, 0.02488],
    'SFT3M': [0.28235, 0.52105, 0.19659],
    'SFT4M': [0.241906, 0.460841, 0.255381, 0.041872],
    'SFT5M': [0.209671, 0.407331, 0.281225, 0.092669, 0.0091036],
    'FTSRS': [1.0, 1.93, 1.29, 0.388, 0.028],
    'FTNI': [0.2810639, 0.5208972, 0.1980399],
    'FTHP': [1.0, 1.912510941, 1.079173272, 0.1832630879],
    'HFT70': [1, 1.90796, 1.07349, 0.18199],
    'HFT95': [1, 1.9383379, 1.3045202, 0.4028270, 0.0350665],
    'HFT90D': [1, 1.942604, 1.340318, 0.440811, 0.043097],
    'HFT116D': [1, 1.9575375, 1.4780705, 0.6367431, 0.1228389, 0.0066288],
    'HFT144D': [1, 1.96760033, 1.57983607, 0.81123644, 0.22583558, 0.02773848,
                0.00090360],
    'HFT169D': [1, 1.97441842, 1.65409888, 0.95788186, 0.33673420, 0.06364621,
                0.00521942, 0.00010599],
    'HFT196D': [1, 1.979280420, 1.710288951, 1.081629853, 0.448734314,
                0.112376628, 0.015122992, 0.000871252, 0.000011896],
    'HFT223D': [1, 1.98298997309, 1.75556083063, 1.19037717712, 0.56155440797,
                0.17296769663, 0.03233247087, 0.00324954578, 0.00013801040,
                0.00000132725],
    'HFT248D': [1, 1.985844164102, 1.791176438506, 1.282075284005,
                0.667777530266, 0.240160796576, 0.056656381764, 0.008134974479,
                0.000624544650, 0.000019808998, 0.000000132974],
    }
```

Looks like the amplitudes are not normalized to 1 though.
