### ISSUE TITLE
scipy.optimize.line_search returns None

### ISSUE THREAD

**Issue by samuela** [scipy/scipy#4257]
I'm trying to use the `scipy.optimize.line_search` command but instead of giving me the three values promised by the docs, it gives me `(None, 13, 0, None, 853161.73010506318, None)` with the optimal alpha nowhere to be found.

**Comment by rlucas7** [comment]
@pv This issue is a bit old. Not sure if there are still documentation issues here, if so I'm happy to resolve. Are there still remaining issue(s) to resolve? The first 2 issues listed by @argriffing with links have been merged and the referenced PR has also been merged.
