### ISSUE TITLE
scipy.linalg.interpolative svd  integer overflow

### ISSUE THREAD

**Issue by vmr2117** [scipy/scipy#4275]
I am working with very large sparse matrix (50k x 1.5M) and trying to obtain rank 500 svd.
In the signature for iddr_rsvd.f in scipy/scipy/linalg/interpolative.pyf the intermediate calculation of size for `w` matrix overflows

```
 w((krank+1)*(2*m+4*n)+25*pow(krank,2))
```

https://github.com/scipy/scipy/blob/master/scipy/linalg/interpolative.pyf#L325.

I just built scipy 0.14 by changing the faulty line to 

```
 w((krank+1)*(2ULL*m+4ULL*n)+25*pow(krank,2))
```

and confirmed that it does not overflow.  I am not sure if this is the best way to fix this problem as I have very little experience with f2py. Another possibility is to change the integer types for variable `m` and `n`.

**Comment by ilayn** [comment]
This is a ridiculous thing I am posting after a decade. Apologies for that but we have finally rewritten this fortran code in #20558 it would be great if there is any reproducer of anykind to test it out. Otherwise that PR will close this one
