### ISSUE TITLE
On one of the TravisCI configs, treat numpy deprecation warnings as errors or failures.

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4327]
I'm not sure how to do this, but it would have caught problems in https://github.com/scipy/scipy/pull/4135 before it was merged.

**Comment by argriffing** [comment]
related https://github.com/scipy/scipy/pull/4722#issuecomment-92474899

**Comment by rgommers** [comment]
OK so I guess I changed my opinion after the build issue with numpy 1.10-dev in gh-4719

**Comment by pv** [comment]
I'm not sure catching gh-4719 requires numpy master --- as reported the build fails also on 1.9, on which the no-deprecated-api defines are also present.

**Comment by argriffing** [comment]
@pv I agree https://github.com/scipy/scipy/pull/4722#issuecomment-92472470, and @rgommers has pointed out that there are test failures that are probably not just due to no-deprecated-api.  On the other hand it could be argued to not break the scipy TravisCI every time there is a temporary glitch in the numpy development branch.

**Comment by matthew-brett** [comment]
It seems reasonable to test against numpy master.  Maybe it is inconvenient for us to have to live with test failures, but it gives the numpy devs early warning, and the test failures should be uncommon.

**Comment by argriffing** [comment]
closing; https://github.com/scipy/scipy/pull/5609
