### ISSUE TITLE
add a git workflow FAQ-style entry

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#4334]
to HACKING.rst or similar.
(this actually can be a numpy issue as well).

There seems to be a set of common problems newcomers are facing, and a set of common traps they are falling into: working off the master branch, merge vs rebase, merging the master branch into the feature branch, the need for `git push -f`, `rebase -i` onto a commit too far into the past and so forth.

Numpy workflow guidelines are good, but not very easy for newcomers. There are several nice write-ups scattered in various PRs, but they are not easy to discover (off the top of my head, there were at least two recently, by @rgommers and @ewmoore, and I'm sure there are more).

**Comment by ev-br** [comment]
Here is one, https://github.com/scipy/scipy/pull/4049#discussion_r18455048

**Comment by argriffing** [comment]
https://github.com/scipy/scipy/issues/4469#issuecomment-73295445

**Comment by maniteja123** [comment]
https://github.com/scipy/scipy/pull/4407#issuecomment-71529933
I just saw this issue was updated, and needed the mentioned comment sometime back as a newcomer to git. Probably would help in resolving merge conflicts.

**Comment by jjgreen** [comment]
It would be helpful if maintainers, when suggesting git-related requirements to contributors, used searchable language.  "... could you take over `foo@19d3a`" is not searchable, "could you add my fork at `https://github.com/foo/scipy` as a remote, then cherry-pick `19d3a`..." is.

**Comment by tupui** [comment]
I will close this, we have `useful_git.rst` now and in the long run we are maybe discussing moving all that away to a separate doc. I don't think we need to keep this open as it does not hold more info.
