### ISSUE TITLE
scipy.interpolate.splev segfaults for high degree splines

### ISSUE THREAD

**Issue by insertinterestingnamehere** [scipy/scipy#4343]
I've worked around this issue by using my own spline evaluation code where I needed it, but I figured this might be good to document.

After the imports, either of the following blocks of code causes a segmentation fault.

```
import numpy as np
from scipy.interpolate import splev
from matplotlib import pyplot as plt

def plot_bernstein_poly(n):
    T = np.array([0] * (n+1) + [1] * (n+2), 'd')
    C = np.zeros(len(T) + 2, 'd')
    X = np.linspace(0, 1, 401)
    for i in xrange(n+1):
        C[i] = 1.
        plt.plot(X, splev(X, (T, C, n)))
        C[i] = 0.
    plt.show()

plot_bernstein_poly(21)

def plot_uniform_spline(n):
    T = np.array(range(-n, 2*n+2), 'd')
    C = np.array([0]*(n) + [1] + [0]*(n),'d')
    t = np.linspace(0, n+1, 401)
    plt.plot(t, splev(t, (T, C, n)))
    plt.show()

plot_uniform_spline(21)
```

I've tested this on windows and linux installations built with gcc/gfortran.
It is present in the release versions of scipy and numpy and also present when using numpy 1.8 and scipy .13.3 (debian builds). Oddly enough, it is not present on a recent installation of anaconda for 64 bit windows that I tested, which makes me think it may be compiler dependent. In that case, there appear to be some issues with repeating basis functions for degree 129, but that's an even rarer use case.

As I understand it, splines with orders this high are _very_ rarely used, but I figured it would be good to document this behavior.

Here's the C backtrace

```
#0  0x00007ffff11d47c7 in splev (t=..., n=68, c=..., k=22, x=..., y=..., m=401, e=0, ier=0)
    at scipy/interpolate/fitpack/splev.f:116
#1  0x00007ffff11c0751 in fitpack_spl_ (
    dummy=<error reading variable: Cannot access memory at address 0x35e578ddfd46a130>, 
    args=<error reading variable: Cannot access memory at address 0x35e578ddfd46a128>)
    at scipy/interpolate/src/__fitpack.h:643
```

**Comment by ev-br** [comment]
OK, I don't think we're going to mess with FITPACK's hardcoded limitations, unless someone has a use case and sends a PR. Closing. Thanks Ian.
