### ISSUE TITLE
different ways of building the docs are subtly different

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#4346]
Apparently, slightly different ways of building the docs produce subtly different results. For one, with `make html-scipyorg` plots in docstrings do not render without `>>> plt.plot()`, while with `make html` they do. Discussion in https://github.com/scipy/scipy/pull/4313#discussion_r22368981
(there are other bits and pieces here and there, but I cannot find them right now).

It would be good to converge on a 'canonical' way of building the docs and required versions of Sphinx, numpydoc, plot_directive etc.

**Comment by rgommers** [comment]
@argriffing it doesn't, if you forget that import you get an error in the build log and definitely no plot in either case.

**Comment by ev-br** [comment]
This issue is no longer relevant, `$ python dev.py doc -j10` works fine. Closing
