### ISSUE TITLE
signal.slepian should use definition of digital window

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#4354]
It's now off by a factor of 2: http://dsp.stackexchange.com/questions/2577/a-few-questions-about-slepian-and-generalized-gaussian-windows

The relation between `width` and the `beta` parameter to `kaiser` should be documented. Here's a comparison for Matlab, there it looks like `width = pi * beta`: https://ccrma.stanford.edu/~jos/sasp/Kaiser_DPSS_Windows_Compared.html

There's a factor 2 between the analog and digital versions, maybe the original implementation worked from a description of the analog window?

See discussion on gh-3679.

**Comment by rgommers** [comment]
copied from gh-3679...

Looking at this again, it seems like we anyway need to change backwards compat for gh-2221 - that's clearly a bug. And the analog definition is quite hard to find; certainly much less used than the ``dpss`` version. So I'm changing my mind on this one.

Relation with the kaiser window:

    import numpy as np
    from scipy import signal
    from scipy.fftpack import fft, fftshift
    import matplotlib.pyplot as plt


    num = 51
    alpha = 3.5
    plt.figure()
    slepian_win = signal.slepian(num, width=alpha/(2*num))  # factor 2 for bug in scipy dpss definition
    kaiser_win = signal.kaiser(num, beta=alpha/np.pi)

    plt.plot(np.arange(num), slepian_win, 'r--')
    plt.plot(np.arange(num), kaiser_win, 'b-', lw=2)
    plt.title("Slepian (DPSS) window (BW=%1.1f)" % alpha)
    plt.ylabel("Amplitude")
    plt.xlabel("Sample")

    plt.figure()
    for window in [slepian_win, kaiser_win]:
        A = fft(window, 2048) / (len(window)/2.0)
        freq = np.linspace(-0.5, 0.5, len(A))
        response = 20 * np.log10(np.abs(fftshift(A / abs(A).max())))
        plt.plot(freq, response)
    plt.axis([-0.5, 0.5, -120, 0])

    plt.title("Frequency response of the Slepian window (BW=%1.1f)" % alpha)
    plt.ylabel("Normalized magnitude [dB]")
    plt.xlabel("Normalized frequency [cycles per sample]")

    plt.show()

``width`` is also not the most handy parameter; specifying it as ``M*width`` as both ``nitime`` and ``Matlab`` do makes more sense. Unfortunately we can't change that without breaking backwards compat even more radically.

**Comment by endolith** [comment]
`beta=(2*num)*width/np.pi` doesn't seem exactly correct:

With `width = 0.01`, beta = `63.66`:

![kaiser vs slepian not quite](https://cloud.githubusercontent.com/assets/58611/17454739/4dedab52-5b6f-11e6-992a-8579cdadc47f.png)

but if I manually adjust beta to 78.3:

![better fit](https://cloud.githubusercontent.com/assets/58611/17454740/51df344c-5b6f-11e6-82d0-6fc678da0382.png)

**Comment by Eric89GXL** [comment]
@endolith does that mean that `signal.slepian` is broken in two ways?

I agree that specifying it as done in `nitime` is more convenient. Maybe instead of changing this function we should deprecate it and make a new one -- we could call it `dpss` if we want. It's possible after all that some people rely on the current definition / normalization even if it's wrong.

**Comment by endolith** [comment]
@Eric89GXL Is that 3 ways?
- Amplitude normalization for even length https://github.com/scipy/scipy/issues/2221
- "factor of 2" error in width? https://github.com/scipy/scipy/issues/4354#issue-53258148 or was that fixed in https://github.com/scipy/scipy/pull/3679?
- width not actually being pi * beta? https://github.com/scipy/scipy/issues/4354#issuecomment-238005728

**Comment by Eric89GXL** [comment]
It seems that way :(

I'm not sure if the best thing to do is make a new function, or fix the old one, since it's so buggy. @rgommers any preference?

**Comment by rgommers** [comment]
``dpss`` sounds fine to me. maybe better indeed to deprecate ``slepian``.

**Comment by Eric89GXL** [comment]
@endolith do you know if `dpss_windows` from `nitime` works properly? It is BSD-licensed so we can adapt it as `scipy.signal.dpss`.

**Comment by endolith** [comment]
@Eric89GXL I'm not sure.  It doesn't produce an amplitude-normalized output, so we'd still need to figure that out?  

By trial and error, these values all produce similar plots:

- `signal.slepian`: `width=0.3`
- `signal.kaiser`: `beta=11.2`
- `nitime.algorithms.spectral.dpss_windows`: `NW=3.82`

I'm not sure what the relationship is.
