### ISSUE TITLE
PPoly.antiderivative() produces incorrect output

### ISSUE THREAD

**Issue by terhorst** [scipy/scipy#4355]
I think this was introduced by #4216--the fix described below may make #4225 unnecessary (or wrong).

    >>> p = PPoly([[1, 0.5]], [0, 1, 2])
    >>> p.integrate(0, 2)
    array(1.5)
    >>> q = p.antiderivative()
    >>> q(2) - q(0)
    2.0

I believe the error is at https://github.com/scipy/scipy/blob/v0.14.0/scipy/interpolate/interpolate.py#L820-L821 which enforces that antiderivative(nu) be continuously differentiable of order nu. It should be nu - 1 instead. (For example, an indefinite integral is in C0.)

**Comment by argriffing** [comment]
Thanks @terhorst!  This example has been added to the unit tests and your suggested fixes have been implemented in https://github.com/scipy/scipy/pull/4357.
