### ISSUE TITLE
`scipy.sparse.linalg.factorized` can silently return garbage

### ISSUE THREAD

**Issue by highlando** [scipy/scipy#4371]
Say `Alu` is the *LU* factorization of a sparse matrix `A` of size `(N,N)`. Then `Alu(b)` is supposed to return the solution `x` of the equation `Ax=b` for an `(N,)` array `b`. 

However, for `b` a `(M, )` array, with `M` less than `N`, `Alu(b)` returns a vector, but with values that were taken, obviously, from non allocated memory.

Check this script:

```python
import scipy.sparse as sps
import scipy.sparse.linalg as spsla
import numpy as np

N = 10
M = 5
A = sps.eye(N)
Alu = spsla.factorized(A)

b = np.arange(N)

print Alu(b)
print Alu(b[:M])
```

**Comment by pv** [comment]
Not reproducible on scipy 0.14.0 or current master:
```
...
>>> scipy.__version__
'0.14.0'
>>> print Alu(b[:M])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: b is of incompatible size
```
When reporting bugs, please try also the latest version.

**Comment by highlando** [comment]
I see. I am on 0.13.3. Feel free to close this issue.

**Comment by ev-br** [comment]
closing then
