### ISSUE TITLE
pinv and pinv2 behave differently

### ISSUE THREAD

**Issue by marcotama** [scipy/scipy#4372]
I am working with bidimensional arrays on Numpy. One of my arrays, H, is random, and I want to compute its pseudoinverse. If I use scipy.linalg.pinv2 everything runs smoothly. However, if I use scipy.linalg.pinv, sometimes problems arise.

The problem is that, if the j-th column of H is all 1s, pinv(H) has huge coefficients at the j-th row. This is in turn a problem because, in such cases, np.dot(pinv(H), Y) contains some nan values (Y is an array of small integers).

Now, I am not into linear algebra and numeric computation enough to understand if this is a bug or some precision related property of the two functions. If this is not a bug, please close this issue and I apologize.

I saved the arrays with np.savetxt(fn, a, '%.2e', ';'): please, see https://dl.dropboxusercontent.com/u/48242012/example.tar.gz to find them.

In the provided file, you can see in pinv(H).csv that rows 14, 33, 55, 56 and 99 have huge values, while in pinv2(H) the same rows have more decent values.

(I posted the same question on StackOverflow yesterday, but it did not receive much attention: http://stackoverflow.com/questions/27775986/numpy-scipy-pinv-and-pinv2-behave-differently . I am reposting here just to signal this behaviour and to suggest that it may be documented - I  can survive with pinv2.)

I appreciate your efforts.

**Comment by ewmoore** [comment]
Hi, what version of scipy are you using?  With the file you provided (which gives only barely similar array since it has been clipped to 2 decimal points) I find results that match to ~1e-8 between `pinv` and `pinv2` using scipy 0.14.

**Comment by nazgul17** [comment]
Hi,

sorry I did not provide this information: I am using Python 3.4.1, Numpy
1.9.1 and Scipy 0.14.0.

Apologies for the files as well: I generated some new (different) files
with %f and I dumped them so there is no loss of precision;
you can load them with

import pickle

with open(path, 'rb') as in_f:

     return pickle.load(in_f)


Now the problematic rows in pH.csv are 2, 4 and 35.


I uploaded them in
https://dl.dropboxusercontent.com/u/48242012/example2.tar.gz .

On 8 January 2015 at 09:35, Eric Moore <notifications@github.com> wrote:

> Hi, what version of scipy are you using? With the file you provided (which
> gives only barely similar array since it has been clipped to 2 decimal
> points) I find results that match to ~1e-8 between pinv and pinv2 using
> scipy 0.14.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scipy/scipy/issues/4372#issuecomment-69105056>.
>



-- 
Marco

**Comment by ewmoore** [comment]
Sorry for the delay in getting back to this.  I think the difference you are seeing is that these two functions differ in their `rcond` parameter.  `pinv` uses machine precision (i.e. ~1e-16 for doubles) and `pinv2` use 1e6 times machine precision.  If you try your calculation again and specify a value for `rcond` you'll find nearly equivalent result from the two functions.

It would be nice if there was just one of these functions, but that ship may have sailed.  We could at least add these defaults to the documentation.

**Comment by solarjoe** [comment]
Since there seem to be three methods scipy.linalg.pinv, scipy.linalg.pinv2, numpy.linalg.pinv
the documentation should also state if some are duplicates.
Or if there are cases where one of them is more suitable.

http://stackoverflow.com/a/13265930

**Comment by skjerns** [comment]
Posting this here so that people are informed

Starting from scipy 1.7.0 , `pinv2` is deprecated and also replaced by a SVD solution.

`DeprecationWarning: scipy.linalg.pinv2 is deprecated since SciPy 1.7.0, use scipy.linalg.pinv instead`

That means, `numpy.pinv`, `scipy.pinv` and `scipy.pinv2` now compute all equivalent solutions. They are also equally fast in their computation, with `scipy` being slightly faster.


```Python
import numpy as np
import scipy

arr = np.random.rand(1000, 2000)
res1 = np.linalg.pinv(arr)
res2 = scipy.linalg.pinv(arr)
res3 = scipy.linalg.pinv2(arr)

np.testing.assert_array_almost_equal(res1, res2, decimal=10)
np.testing.assert_array_almost_equal(res1, res3, decimal=10)
```
