### ISSUE TITLE
All tests fail due to bad file permissions

### ISSUE THREAD

**Issue by u55** [scipy/scipy#4375]
Hi scipy developers,

I noticed that the file permissions have changed in the 0.14.1 tarball release.  Regular users no longer have read permission for many of the files, which means that when I build scipy from source and install it myself, by default some of the files are unreadable without elevating my privledges.  For instance, after a fresh scipy install, every single one of the tests fail with a warning similar to:

`ERROR: Failure: PermissionError ([Errno 13] Permission denied: '/usr/lib/python3.4/site-packages/scipy/cluster/tests/test_hierarchy.py')`

Compare the file permissions in the source tarball of version 0.14.1 versus 0.14.0 (here I am showing one of the aforementioned test files):

`$ ls -lh scipy-0.14.1/scipy/cluster/tests/test_hierarchy.py `
`-rw-r----- 1 user user 57K Dec 30 11:46 scipy-0.14.1/scipy/cluster/tests/test_hierarchy.py`

`$ ls -lh scipy-0.14.0/scipy/cluster/tests/test_hierarchy.py `
`-rw-r--r-- 1 user user 57K May  3  2014 scipy-0.14.0/scipy/cluster/tests/test_hierarchy.py`

Was this change to the file permissions intentional?  If so, then is it documented somewhere?  It seems like a bug to me since I have to manually change the file permissions when I build scipy.

Thanks.

**Comment by rgommers** [comment]
Likely unintentional. @pv?

**Comment by u55** [comment]
Note, the file permissions are also problematic in the source tarball of release-candidate version 0.15.0rc1:

`$ ls -lh scipy-0.15.0rc1/scipy/cluster/tests/test_hierarchy.py `
`-rw-r----- 1 user user 35K Dec 15 09:48 scipy-0.15.0rc1/scipy/cluster/tests/test_hierarchy.py`

**Comment by u55** [comment]
Well, I never heard anything on this issue from Pauli (@pv), but I see that he released version 0.15.0 yesterday and it has the correct file permissions.

For example:
`$ ls -lh scipy-0.15.0/scipy/cluster/tests/test_hierarchy.py `
`-rw-r--r-- 1 user user 35K Jan 11 08:27 scipy-0.15.0/scipy/cluster/tests/test_hierarchy.py`

As far as I am concerned, this issue can be closed.
Thanks.

**Comment by pv** [comment]
Fixed in 8e5c9d7480cc72 (in maintenance/0.15.x; pavement.py in master isn't fixed yet)

**Comment by rgommers** [comment]
Hmm, just coming across this. This fix is missing in master, but we haven't had any complaints about this for 0.16.x. @pv do you think we need to push that commit to master?

**Comment by pv** [comment]
Probably best to push it in master, I don't think the permissions come right otherwise.

**Comment by rgommers** [comment]
OK thanks, done.
