### ISSUE TITLE
Mann Whitney U difference in p value between Windows and Mac

### ISSUE THREAD

**Issue by glassnotes** [scipy/scipy#4386]
There appears to be a discrepancy in the calculated p value of the Mann-Whitney U test - after much testing we seem to be able to attribute it to whether we run it on Windows or Mac. Not sure if this is a bug in the code somewhere, or an inevitable difference between the two OSs.

Here is a link to the data set we have been using: https://www.dropbox.com/s/blf5osto696bm4h/intro_to_ds_programming_files.zip
(it is called turnstile_data_master_with_weather.csv and can be found in the directory project_5/average_rides_per_day)

Here is a code snippet:

```
import pandas as pd
import scipy
df_turnstile_weather = pd.DataFrame(pd.read_csv('turnstile_data_master_with_weather.csv'))
U, p = scipy.stats.mannwhitneyu(turnstile_weather['ENTRIESn_hourly'][turnstile_weather.rain ==1],turnstile_weather['ENTRIESn_hourly'][turnstile_weather.rain ==0])
```

We obtained a p value of 0.024999 on Mac, and 0.0193 in Windows. The U values are the same in both cases. Calculations were done in an iPython notebook. The value seems to be independent of the version of any of the software and only on the OS (as far as we can tell). For reference, here are a few of the systems/versions we tried it on:

Mac 10.9.5 :
Python 2.7.5
ipython 2.3.0
numpy 1.9.1
pandas 0.15.1
scipy 0.11.0 (tried 0.14.0 on Mac as well, got the 'normal' Mac value)

Windows (8.1 64 bit, clean python/Anaconda build):
Python 2.7.9
ipython 2.2.0
numpy 1.9.0
pandas 0.14.1
scipy 0.14.0

A second Windows build tested (8.1, 64 bit):
ipython 2.3.1
numpy 1.9.1
pandas 0.15.2
scipy 0.14.0

**Comment by WarrenWeckesser** [comment]
I suspect it is the same problem as discussed in https://github.com/scipy/scipy/issues/3611.  In particular, see the comments from https://github.com/scipy/scipy/issues/3611#issuecomment-42390135 onward.

**Comment by rgommers** [comment]
Issue gh-3611 and related ones have been fixed a long time ago. This CSV file is gone, but assuming this is fixed as well - closing.
