### ISSUE TITLE
Documentation glitsch in sparse.linalg.spilu

### ISSUE THREAD

**Issue by jgostick** [scipy/scipy#4393]
``sp.sparse.spilu()`` returns a ``SuperLU`` object, which has a method called ``solve()``.  According the documentation in the object inspector (using Spyder) it requires named argument ``b``, but in fact the argument name seems to be ``rhs``.

**Comment by rgommers** [comment]
Thanks for the report. Looks indeed like a documentation error. Arguments are named in ``_superluobject.c``:

        static char *kwlist[] = { "rhs", "trans", NULL };

Fix in gh-4416.
