### ISSUE TITLE
Add appveyor for windows testing.

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4403]
I've never used appveyor, but my understanding is that it would automatically answer questions like https://github.com/scipy/scipy/pull/4374#issuecomment-69768585.

**Comment by sturlamolden** [comment]
I don't think it has a Fortran compiler.
http://www.appveyor.com/docs/installed-software

**Comment by ev-br** [comment]
https://github.com/numpy/numpy/pull/5328

**Comment by sturlamolden** [comment]
NumPy does not require Fortran and can be built with Microsoft's VisualStudio tools. Those are on appveyor. SciPy is typically built with gcc and gfortran or icc and ifort. We do not even have a free toolchain able to produce binary 64-bit installers.

**Comment by perimosocordiae** [comment]
Fixed by gh-7616, closing.

**Comment by rscohn2** [comment]
Sample appveyor (and other CI systems) configurations for using intel C++, Fortran, DPC++
https://github.com/oneapi-src/oneapi-ci
