### ISSUE TITLE
Vector-valued constraints in minimize() et al

### ISSUE THREAD

**Issue by pv** [scipy/scipy#4408]
minimize() API currently requires that the constraint functions return scalars.

However, SLSQP and COBYLA both call all constraint functions one-by-one, and reconstruct a vector out of the results. This has non-negligible Python overhead if you have many constraints (e.g. matrix-specified constraints of the form `A x = b` or `B x >= 0`).

It should be made possible that you can just give a single constraint function that computes a vector of values `g_i(x)`, `i=0..n-1` at once in the `g_i(x) >= 0`, `i = 0...n-1` inequality or equality constraints.

**Comment by dlax** [comment]
Isn't it already possible? See `test_minimize_inequality_given_vector_constraints` in `test_slsql.py` which uses a vector-valued inequality constraint `f_ieqcon2`. Or am I missing something?

**Comment by pv** [comment]
Hmm, I misread this stackoverflow post:
https://stackoverflow.com/questions/27851087/matrix-constraints-with-scipy-optimize-minimize
.
The more precise claim seems to be that it breaks if you have more than
one such functions.

**Comment by dlax** [comment]
AFAICT, SLSQP does not break with multiple vector-valued constraints.

About the stackoverflow post, there's arguably something badly defined with the second inequality constraint in `d_` as `b` has shape 2x1 and `A` `2x3` so when `x` (the optimization variable) will get in, it'll have shape `3` (1d array), so the result of this constraint will be `2x2`. Not sure what could be done on our side, but if this user just flattened his `b` array, I'd expect he'd get something correct.

**Comment by edwintye** [comment]
It appears that SLSQP takes in vector constraints but not COBYLA.  When I try to use vector constraints, it throws an ValueError "setting an array element with a sequence" at line 240 in cobyla.py.
