### ISSUE TITLE
MATLAB classdef objects

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#4411]
I found that the julia team has started reverse-engineering the format MATLAB is using to save classdef objects (i.e., MATLAB's "new-style" classes):

http://nbviewer.ipython.org/gist/mbauman/9121961
https://github.com/mbauman/MAT.jl/blob/undoc-classes/src/MAT_v5.jl#L289

I have started to try to reimplement these for scipy's loadmat, but am a bit stuck in loadmat's own arcane code.  My initial work is at https://github.com/anntzer/scipy/tree/matlab-classobj-loader-jl  Is anyone interesting in working with me to get this to work?

**Comment by matthew-brett** [comment]
As the author of the arcane code - yes - that would be great.    How can I best help?  Do you want to try a google hangout or similar to get going?   Or should I look at something first?

**Comment by matthew-brett** [comment]
Oh - you are in Berkeley.  I work in Berkeley too - maybe the easiest is to meet up. 

I started a scipy github wiki page : https://github.com/scipy/scipy/wiki/Reading-mat-file-class-objects

**Comment by sethtroisi** [comment]
As discussed in #4441 classdef loading code is available at https://github.com/anntzer/matloader but an effort to merge this into scipy failed (pure python code was quite slow compared to cython)
