### ISSUE TITLE
Documentation of scipy.signal.cwt error

### ISSUE THREAD

**Issue by villiano** [scipy/scipy#4412]
There is probably an error in the documentation of scipy.signal.cwt:

It is:
Returns:	
cwt: (M, N) ndarray
Will have shape of (len(data), len(widths)).

It should be:
Returns:	
cwt: (M, N) ndarray
Will have shape of (len(widths), len(data)).

**Comment by ev-br** [comment]
Looks correct, care to submit a PR with a fix?

**Comment by villiano** [comment]
Sorry but I am not familiar with this project nor with GitHub in general, can you do that for me?

Thanks
