### ISSUE TITLE
loadmat sets the wrong dtype

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#4422]
For example:
```
$ matlab -nodesktop -r 'm = double([1, 2]); save test.mat m; exit' >/dev/null && python -c 'from scipy.io import loadmat; print(loadmat("test.mat")["m"].dtype)'
uint8
```
This is likely due to automatic compression of numeric data (see MAT file specification, page 1-17).

**Comment by matthew-brett** [comment]
By default scipy loads the data in the type they were saved.  If you want the type with which they would be loaded into the MATLAB workspace, you need the ``mat_dtype`` flag to `loadmat`:

```
mat_dtype : bool, optional
   If True, return arrays in same dtype as would be loaded into
   MATLAB (instead of the dtype with which they are saved).
```

**Comment by matthew-brett** [comment]
By the way, the default is on the assumption that the arrays may be rather large and the user will likely prefer the arrays at their most compact.

**Comment by anntzer** [comment]
I see.  I don't like it, because I would think that the actual format in which the arrays are saved is rather an implementation detail of the format, but I agree it's rather nitpicking.
