### ISSUE TITLE
Incomplete documentation for sparse.linalg.spsolve

### ISSUE THREAD

**Issue by jdreaver** [scipy/scipy#4434]
I apologize in advance for these seemingly trivial issues. 

The documentation for the `b` parameter of `scipy.linalg.spsolve` is incomplete. It states: `The matrix or vector representing the right hand side of the equation. If a vector, b.size must`. Note that the sentence ends prematurely; `b.size` must be what?

Also, I think we should mention that the user needs to install `scikit-umfpack` for the `use_umfpack` parameter to work. From the documentation, I thought that umfpack was somehow used automatically, since the default is `True`. I didn't realize I needed to install `scikit-umfpack` until I read the source code.

I would be glad to open a pull request, but I just need to know what the documentation for `b` should be. Also, it seems that #4420 deals with `spsolve`. Maybe these edits can go along with that PR?

**Comment by argriffing** [comment]
Yes, these are symptoms that umfpack in scipy is not so actively maintained.  Chances are that you will be able to decipher those incomplete docs as well as or better than anyone else!

> Also, it seems that https://github.com/scipy/scipy/pull/4420 deals with `spsolve`. Maybe these edits can go along with that PR?

Please no, I tried to go out of my way to keep the scope of that PR from metastasizing across all of the unmaintained corners of scipy's sparse solvers, so that it may eventually be merged...

**Comment by jdreaver** [comment]
I think [this comment and code](https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/dsolve/linsolve.py#L92-L96) says it all: `b is a vector only if b have shape (n,) or (n, 1)`.

> Please no, I tried to go out of my way to keep the scope of that PR from metastasizing across all of the unmaintained corners of scipy's sparse solvers, so that it may eventually be merged...

Haha, sounds good. I'll make a separate PR.

**Comment by larsmans** [comment]
No need to apologize, thanks for the patch!

**Comment by ev-br** [comment]
seems to be fixed by gh-4436, closing. Please reopen if there's something to fix still
