### ISSUE TITLE
linprog() failure on 0.15.1

### ISSUE THREAD

**Issue by scopatz** [scipy/scipy#4438]
I thought I'd take the new (and exciting) `linprog()` solver for a spin.  On my first attempt trying to run the example problem verbatim, I received a significantly different result. For reference, the documentation says:

```python
>>> c = [-1, 4]
>>> A = [[-3, 1], [1, 2]]
>>> b = [6, 4]
>>> x0_bounds = (None, None)
>>> x1_bounds = (-3, None)
>>> res = linprog(c, A_ub=A, b_ub=b, bounds=(x0_bounds, x1_bounds),
...               options={"disp": True})
>>> print(res)
Optimization terminated successfully.
     Current function value: -11.428571
     Iterations: 2
status: 0
success: True
fun: -11.428571428571429
x: array([-1.14285714,  2.57142857])
message: 'Optimization terminated successfully.'
nit: 2
```

However, when I run this from miniconda python 3, I see:

```python
import scipy
print(scipy.__version__)
from scipy.optimize import linprog
c = [-1, 4]
A = [[-3, 1], [1, 2]]
b = [6, 4]
x0_bounds = (None, None)
x1_bounds = (-3, None)
res = linprog(c, A_ub=A, b_ub=b, bounds=(x0_bounds, x1_bounds),
              options={"disp": True})
print(res)
```

```bash
0.15.1
Optimization terminated successfully.
         Current function value: -22.000000  
         Iterations: 1
  status: 0
       x: array([ 10.,  -3.])
   slack: array([ 39.,   0.])
     nit: 1
 message: 'Optimization terminated successfully.'
     fun: -22.0
 success: True
```

It seems like m version is failing to perform an iteration.  Any thoughts? Is anyone else seeing this?

**Comment by argriffing** [comment]
>  Is anyone else seeing this?

Yes, I see this too. @robfalck?

**Comment by pv** [comment]
Solution looks valid to me and objfun is smaller than in docstring. Is just the docstring result wrong?

**Comment by robfalck** [comment]
The solution is valid and is what another linear programming routine finds.  The docstring is wrong for this one.

**Comment by scopatz** [comment]
Hi all, I agree that the docstring looks wrong for this one. Should be an easy fix the ;)
