### ISSUE TITLE
Typo in scipy.special.expit doc

### ISSUE THREAD

**Issue by hsalamin** [scipy/scipy#4445]
Hello,

The notes at http://docs.scipy.org/doc/scipy/reference/generated/scipy.special.expit.html refer to logit instead of  expit. ("As a ufunc **logit** takes a number of optional keyword arguments." should be "As a ufunc **expit** takes a number of optional keyword arguments.")

Cheers

Hugues

**Comment by larsmans** [comment]
Fixe by @ev-br, thanks!
