### ISSUE TITLE
Incorrect return values in f_oneway

### ISSUE THREAD

**Issue by mortonjt** [scipy/scipy#4457]
Came across this error when trying to build a permutation version of this

Here's the python test I ran

```
>>> import numpy as np
>>> from scipy.stats import f_oneway
>>> a = np.arange(3)
>>> b = np.arange(3)+100
>>> c = np.arange(3)+200
>>> f_oneway(a,b,c)
(30000.0, 9.9970005999000172e-13)
```

Just for the sake of comparison, I ran a R test
```
> df = data.frame(data=c(0:2,100:102,200:202), group=c(1,1,1,2,2,2,3,3,3))
> summary(aov(data~group, data=df))
            Df Sum Sq Mean Sq F value   Pr(>F)    
group        1  60000   60000   70000 2.91e-15 ***
Residuals    7      6       1                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
```
The scipy.stats.f_oneway output differs from R's aov() function

I'm pretty sure that the offending lines are [here](https://github.com/scipy/scipy/blob/e5515c43feda5368794b066fbd15d873a7796bb1/scipy/stats/stats.py#L2421-2423)

That code should actually be

```
for a in args:
        ssbn += ss(a) - square_of_sums(a) / float(len(a))
```

Once someone double checks this, I can submit a PR for this in parallel to my permutation ANOVA test.

**Comment by josef-pkt** [comment]
I checked with statsmodels OLS:

Ii get the same fvalue as scipy.f_oneway

But I get the same fvalue as R if I treat groups as a continuous variable. -> maybe you need to specify `as.factor` in R. (I don't have it open right now to check.)

I think I have verified f_oneway on the NIST test cases which passe except for precision problems in some extreme cases.

**Comment by WarrenWeckesser** [comment]
scipy agrees with Octave and Scilab, too:

Octave:
```
octave:2> anova([0,1,2,100,101,102,200,201,202],[1,1,1,2,2,2,3,3,3])

One-way ANOVA Table:

Source of Variation   Sum of Squares    df  Empirical Var
*********************************************************
Between Groups            60000.0000     2     30000.0000
Within Groups                 6.0000     6         1.0000
---------------------------------------------------------
Total                     60006.0000     8

Test Statistic f          30000.0000
p-value                       0.0000

ans =    9.9964e-13
```

Scilab:
```
-->[f,p] = ftest([0 100 200; 1 101 201; 2 102 202])
 p  =
 
    9.996D-13  
 f  =
 
    30000.  
```

**Comment by WarrenWeckesser** [comment]
R agrees, too, when `as.factor` is used as @josef-pkt suggested:
```
> df = data.frame(data=c(0:2,100:102,200:202), group=as.factor(c(1,1,1,2,2,2,3,3,3)))
> df
  data group
1    0     1
2    1     1
3    2     1
4  100     2
5  101     2
6  102     2
7  200     3
8  201     3
9  202     3
> summary(aov(data~group, data=df))
            Df Sum Sq Mean Sq F value Pr(>F)    
group        2  60000   30000   30000  1e-12 ***
Residuals    6      6       1                   
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
```

**Comment by mortonjt** [comment]
Ok cool.  In that case let me close this issue.

Thank you guys for looking into this so quickly!

**Comment by josef-pkt** [comment]
Thanks Warren for the cross-checking.

There shouldn't be any bugs in scipy.stats anymore except for corner cases. :)
