### ISSUE TITLE
scipy.misc.imresize changes image range

### ISSUE THREAD

**Issue by serge-m** [scipy/scipy#4458]
scipy.misc.imresize changes minimum, mean and maximum values of image. That is not what user can expect. 

Following code (EDIT: updated for removal of ``lena``, so doesn't quite match the opencv version below):

    import numpy as np
    from scipy import misc

    img = np.random.randint(25, 246, 400*400).reshape(400, 400)
    print(img.min(), img.mean(), img.max())
    img2 = misc.imresize(img.astype('uint8'), [1000, 1000])
    print(img2.min(), img2.mean(), img2.max())
    img2 = misc.imresize(img.astype('float32'), [1000, 1000])
    print(img2.min(), img2.mean(), img2.max())

produces following output:

```
(25, 134.83063125000001, 245)
(26, 134.33983000000001, 245)
(1, 126.824645, 255)
```

The changes are very significant. cv2 (opencv) library has better situation:

``` python
import cv2
import scipy.misc
import numpy 

img = scipy.misc.ascent()
print(img.min(), img.mean(), img.max())
img2 = cv2.resize(img.astype('uint8'), dsize=(1000,1000))
print(img2.min(), img2.mean(), img2.max())
img2 = cv2.resize(img.astype('float32'), dsize=(1000,1000))
print(img2.min(), img2.mean(), img2.max())
```

Output:

```
25 124.046783447 245
26 123.920154 244
25.8968 124.044 243.705
```

scipy.version.full_version, scipy.version.git_revision, scipy.version.release is ('0.14.0', 'f2ec91c4908f9d67b5445fbfacce7f47518b35d1', True)

**Comment by pv** [comment]
The default interpretation of floating point images appears to be to scale the data to full uint8 range; the result stays the same even if you multiply the data with some number; see `scipy.misc.bytescale`.

I don't think we will change this behavior due to backward compatibility.
Better documentation would probably be needed.

**Comment by mohamed-ezz** [comment]
That's indeed an annoying problem. It would really help to add a parameter to allow changing this behavior.

**Comment by serge-m** [comment]
@mohamed-ezz I solved the problem switching to OpenCV (cv2 module)

**Comment by curiale** [comment]
I'm totally agree with @mohamed-ezz . It would really help to add a parameter for controlling this behavior.

**Comment by karpathy** [comment]
I've burned myself on this problem 3 separate times now (including just now) over a period of a few years and I keep forgetting about this unintuitive side effect. I frequently want to resize floating-point channels, e.g. convnet features, etc.

At the very least the [imresize documentation](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.misc.imresize.html) is extremely unclear on multiple fronts, e.g.: 

- What type can the image be? (answer: uint8 only, or there are almost certainly unintended consequences)
- "tuple - Size of the output image." the size of the output image. Is the width first or the height first? I keep having to rederive this over and over by trial and error. I remember once chasing down the implementation of this function to discover that the dimensions are in fact switched as one of the first lines of code in that function.
- How are the borders treated exactly? This operation is much more complex than just "Resize an image.", the full documentation of a function called `imresize`.
- The time complexity is not mentioned, but this function is actually quite slow and definitely not recommended for use in real-time applications as my understanding is, it goes through all kinds of PIL conversions back and forth with memory copies.

I would suggest adding more options to this function or at the very least documenting it more thoroughly.

**Comment by person142** [comment]
> I would suggest adding more options to this function or at the very least documenting it more thoroughly.

The function should just be deprecated. It reproduces functionality that `pillow` already provides. The same is true for most of the image-related functions in `misc`. (IIRC `imread` needs to be kept around because of a `pillow` bug.)

**Comment by rgommers** [comment]
Note that this behavior was improved in gh-6578 recently. I've just updated the example in the summary to use ``ascent`` instead of ``lena``, so it works with current master. I get:

    img = scipy.misc.ascent()
    print(img.min(), img.mean(), img.max())
    img2 = scipy.misc.imresize(img.astype('uint8'), [1000, 1000])
    print(img2.min(), img2.mean(), img2.max())
    img2 = scipy.misc.imresize(img.astype('float32'), [1000, 1000])
    print(img2.min(), img2.mean(), img2.max())
    
    ## -- End pasted text --
    0 87.4798736572 255
    0 87.483255 255
    0 87.483255 255

**Comment by rgommers** [comment]
Actually, there's a bunch of comments from @gdooper around https://github.com/scipy/scipy/pull/6578#issuecomment-252435829 with suggestions about this issue. @gdooper's conclusion that his PR didn't affect the behavior here doesn't match what I'm seeing on master right now though.

**Comment by rgommers** [comment]
> The function should just be deprecated. It reproduces functionality that pillow already provides. The same is true for most of the image-related functions in misc. (IIRC imread needs to be kept around because of a pillow bug.)

Are you sure? Last time I checked ``pillow`` wasn't great when dealing with ndarrays, it preferred its own ``Image`` class.

**Comment by gdooper** [comment]
> Note that this behavior was improved in gh-6578 recently. I've just updated the example in the summary to use ascent instead of lena, so it works with current master. I get:

> Actually, there's a bunch of comments from @gdooper around #6578 (comment) with suggestions about this issue. @gdooper's conclusion that his PR didn't affect the behavior here doesn't match what I'm seeing on master right now though.

@rgommers You will have to be careful with what input dataset you use in the summary to show the issue. The problem with using the `ascent` image is that it is already stretched to the range (0, 255). So you won't see the scaling issue with this dataset. The `lena` image had a min and max val of 25 and 245 I believe, so it did get rescaled with `imresize`.

So in the issue summary, I would recommend either:
a) creating `img` from a scaled version of `ascent` so that 0 < img.min() < img.max() < 255
b) creating `img` as a random array with known min and max (e.g. `img = np.random.randint(25, 246, 400*400).reshape(400, 400)`)

**Comment by zijunwei** [comment]
@karpathy 
Are there any recommendations for alternatives of this function?

**Comment by curiale** [comment]
@zijunwei  
I'm using the `zoom (scipy.ndimage.interpolation)` function instead of `imresize`.

**Comment by rgommers** [comment]
> The problem with using the ascent image is that it is already stretched to the range (0, 255).

Thanks @gdooper! Fixed the issue description with your suggestion b.

**Comment by kitovyj** [comment]
I screwed my DNN train image augmentation by implicitly doing that crap... I'm switching to cv2.

**Comment by ypxie** [comment]
It's a really really bad and unexpected behavior, It screwed my network training for two weeks and until I find out that it is this part that went wrong.

**Comment by rgommers** [comment]
@ypxie `imresize` is already deprecated (because of this behavior) in SciPy 1.0, and will be removed in one of the next releases. So please don't use it anymore.
