### ISSUE TITLE
Nested classes cause scipy.spatial.KDTree to be unpickleable

### ISSUE THREAD

**Issue by ericchiang** [scipy/scipy#4463]
```
import pickle

from scipy.spatial import KDTree
import numpy as np

x = np.random.random((5,6))
tree = KDTree(x)
pickle.dumps(tree)
```

this causes the error

```
PicklingError: Can't pickle <class 'scipy.spatial.kdtree.leafnode'>: it's not found as scipy.spatial.kdtree.leafnode
```

After searching around it appears that because kdtree.leafnode is a nested class, pickle cannot pick it up.

Is there a reason KDTree requires so many nested classes? Would it be more advisable not to use nested classes so a KDTree can be transferred between environments?

**Comment by rgommers** [comment]
Nicely timed question: gh-4374 adds pickle support to ``cKDTree`` (which is likely what you want to be using).

**Comment by EricChiang** [comment]
:+1: awesome thanks!

**Comment by sturlamolden** [comment]
Pickling cKDTree only works on Python 3 though. I have no idea why it does not on Python 2. Ideas are welcome.

**Comment by sethtroisi** [comment]
Python 2 is no longer supported.
Example runs in Python 3 with Scipy 1.4.1
