### ISSUE TITLE
TST: residue/residuez/invres/invresz don't have any tests

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#4464]
Unless I'm mistaken, there are no tests for these functions.  Here are some I tried, which all pass mathematically, but may produce different arrays:

From http://www.mathworks.com/help/matlab/ref/residue.html:

This is correct mathematically, but terms are in a different order:

```
b = [ 5, 3, -2, 7]
a = [-4, 0, 8, 3]
r, p, k = residue(b, a)

r == [-1.4167, -0.6653,  1.3320]
p == [ 1.5737, -1.1644, -0.4093]
k == -1.2500
```

Matches:

```
b, a = invres(r, p, k)
b == [-1.25, -0.75,  0.50, -1.75]
a == [ 1.00, -0.00, -2.00, -0.75]
```

From http://www.mathworks.com/help/matlab/math/partial-fraction-expansions.html:

SciPy gives k = [0], which is mathematically the same, but not the same:

```
b = [-4, 8]
a = [1, 6, 8]
r, p, k = residue(b, a)

r == [-12,  8]
p == [ -4, -2]
k == []
```

Matches SciPy:

```
b2, a2 = invres(r, p, k)
b2 == [-4, 8]
a2 == [1, 6, 8]
```

From http://eeweb.poly.edu/iselesni/EL6113/notes/residues.pdf:

Equivalent, but different order and [] vs [0]:

```
num = [4, 1]
den = [1, -1, -2]
r, p, k = residue(num, den)
r == [3, 1]
p == [2, -1]
k == []
```

Complex poles
Same, but different order and [0] vs []:

```
num = [4 ,3]
den = [2, -3.4, 1.98, -0.406]
r, p, k = residue(num, den)
r == [36.25, -18.125 +13.125j, -18.125 -13.125j]
p == [0.7, 0.5 + 0.2j, 0.5 - 0.2j]
k == []
```

Repeated pole
Same except [0] vs []:

```
num = [2, 1]
den = [1, 5, 8, 4]
r, p, k = residue(num, den)
r == [1, 3, -1]
p == [-2, -2, -1]
k == []
```

Matches:

```
r = [5, 6, -7]
p = [3, -4, -1/5]
num, den = invres(r, p, [])
num == [4, -2.8, 84.4]
den == [1, 1.2, -11.8, -2.4]
```

Degree of numerator greater than denominator
Equivalent, but different order:

```
num = [3, -1.1, 0.88, -2.396, 1.348]
den = [1, -0.7, -0.14, 0.048]
r, p, k = residue(num, den)
r == [1, 4, -3]
p == [0.8, -0.3, 0.2]
k == [3, 1]
```

From http://en.wikipedia.org/wiki/Partial_fraction_decomposition:

1 / (x^2 + 2x - 3) =
-1/4 / (x + 3) + 1/4 / (x - 1)

```
b = [1]
a = [1, 2, -3]
r, p, k = residue(b, a)
assert_allclose(r, [-1/4, 1/4])
assert_allclose(p, [-3, 1])
assert_allclose(k, [0])
```

(z^2 - 5) / (z^2 - 1)*(z^2 + 1) =
1/(z+1) - 1/(z-1) + 3j/2/(z+1j) - 3j/2/(z-1j)

```
b = [1, 0, -5]
a = polymul([1, 0, -1], [1, 0, 1])
r, p, k = residue(b, a)
assert_allclose(r, [-3j/2, 3j/2, -1, 1])
assert_allclose(p, [1j, -1j, 1, -1])
assert_allclose(k, [0])
```

From http://faculty.uml.edu/ahmed_abuhajar/documents/ResidueOfRepeatedRoots.pdf

F(s) = (3s^2 + 8s + 6) / (s^3 + 3s^2 + 3s + 1)

```
b = [3, 8, 6]
a = [1, 3, 3, 1]
r, p, k = residue(b, a)
assert_allclose(r, [3, 2, 1])
assert_allclose(p, [-1, -1, -1])
assert_allclose(k, [0])
```

http://www.ws.binghamton.edu/fowler/fowler%20personal%20page/EE301_files/EECE%20301%20Note%20Set%2033a%20PFE%20for%20Z%20Transform.pdf

Positive powers of z digital filters:

No Direct Terms, No Repeated Roots, No Complex Roots
Different order, [] vs [0]:

```
r, p, k = residue([3, -1], [1, -3, 2])
r == [5, -2]
p == [2, 1]
k == []
```

One Direct Term, No Repeated Roots, No Complex Roots
Different order:

```
r, p, k = residue([2, 3, -1], [1, -3, 2])
r == [13, -4]
p == [2, 1]
k == 2
```

Two Direct Terms, No Repeated Roots, No Complex Roots
Different order:

```
r, p, k = residue([7, 2, 3, -1], [1, -3, 2])
r == [69, -11]
p == [2, 1]
k == [7, 23]
```

No Direct Terms, A Double Root, No Complex Roots
Repeated poles are in the correct order, but others are not:

```
r, p, k = residue([2, 3, -1], [1, -5, 8, -4])
r == [-2, 13, 4]
p == [2, 2, 1]
k == []
```

No Direct Terms, No Repeated Roots, Two Complex Roots
Different order:

```
r, p, k = residue([2, 3, -1], [1, -3, 4, -2])
r == [-1 - 3.5j, -1 + 3.5j, 4]
p == [1 + 1j, 1 - 1j, 1]
k == []
```

**Comment by rgommers** [comment]
I see a few tests for ``invres`` in ``test_signaltools.py``, but the rest is indeed untested.

**Comment by rgommers** [comment]
Do you want to put the above tests in a PR?

**Comment by endolith** [comment]
and here are residuez versions:

From http://www.dadisp.com/webhelp/dsphelp.htm#mergedprojects/refman2/SPLGROUP/RESIDUEZ.htm

Unstable system:
Different order

    r, p, k = residuez([1, -1], [1, -5, 6])
    r == [2, -1]
    p == [3, 2]
    k == []

Inverse:
Matches scipy

    r = [2, -1]
    p = [3, 2]
    k = []
    b, a = invresz(r, p, k)
    b == [1, -1]
    a == [1, -5, 6]

3 repeated poles:
Same except [] vs [0]

    r, p, k = residuez([2, 3, 4], [1, 3, 3, 1])
    r == [4, -5, 3]
    p == [-1, -1, -1]
    k == []

Inverse:
**Fails**

    r = [4, -5, 3]
    p = [-1, -1, -1]
    k = []
    b, a = invresz(r, p, k)
    b == [2, 3, 4]
    a == [1, 3, 3, 1]

Numerator greater than denominator:
Different order

    r, p, k = residuez([1, -10, -4, 4], [2, -2, -4])
    r == [-1.5, 0.5]
    p == [2, -1]
    k == [1.5, -1]


From http://faraday.ee.emu.edu.tr/eeng420/ince_ppts/lecture15.pdf


Fails if written as `num = 18`
otherwise matches

    num = [18]
    den = [18, 3, -4, -1]
    r, p, k = residuez(num, den)
    r == [0.36, 0.24, 0.4]
    p == [0.5, -0.3333, -0.3333]
    k == []


Matches:

    r = [0.24, 0.4, 0.36]
    p = [-0.3333, -0.3333, 0.5]
    k = [0]
    num, den = invresz(r, p, k)
    num == [1, 0, 0, 0]
    den == [1, 0.1666, -0.2222, -0.0555]




From http://www.eas.uccs.edu/wickert/ece2610/lecture_notes/PartialFractionExample_solved.pdf

2 real poles
Different order

    A, p, K = residuez([2, 3], polymul([1, -1/2], [1, 1/4]))
    A == [16/3, -10/3]
    p == [0.5, -0.25]
    K == []



From http://www.cpp.edu/~zaliyazici/ece308/matlab-1.pdf


Polarities do not match (does it matter?):

    r, p, k = residuez([1, 2, 1], [1, -1, 0.3561])
    r == [-0.9041 - 5.9928j, -0.9041 + 5.9928j]
    p == [-0.5 - 0.3257j, -0.5000 + 0.3257j]
    k == 2.8082



Octave:
Matches scipy:

    B = [1, -2, 1]
    A = [1, -1]
    r, p, f = residuez(B, A)
    r == [0]
    p == [1]
    f == [1 -1]

Error if `B = 1`, [] vs [0]:

    B = 1
    A = [1, -1j]
    r, p, f = residuez(B, A)
    r == [1]
    p == [1j]
    f == []


Matches:

    B = [1]
    A = [1, -1, .25]
    r, p, f = residuez(B, A)
    r == [0, 1]
    p == [0.5, 0.5]
    f == []

Matches:

    B = [1]
    A = [1, -0.75, .125]
    r, p, f = residuez(B, A)
    r == [-1, 2]
    p == [0.25, 0.5]
    f == []

Matches:

    B = [1, 6, 2]
    A = [1, -2, 1]
    r, p, f = residuez(B, A)
    r == [-10, 9]
    p == [1, 1]
    f == [2]

Matches:

    B = [6, 2]
    A = [1, -2, 1]
    r, p, f = residuez(B, A)
    r == [-2, 8]
    p == [1, 1]
    f == []

Matches:

    B = [1, 6, 6, 2]
    A = [1, -2, 1]
    r, p, f = residuez(B, A)
    r == [-24, 15]
    p == [1, 1]
    f == [10, 2]

Fails:

    B = [1, 6, 6, 2]
    A = [1, -(2+1j), (1+2j), -1j]
    r, p, f = residuez(B, A)
    r == [-2+2.5j, 7.5+7.5j, -4.5-12j]
    p == [1j, 1, 1]
    f == -2j

r is not sorted the same way, but otherwise matches:

    B = [1, 0, 1]
    A = [1, 0, 0, 0, 0, -1]
    r, p, f = residuez(B, A)
    p = p[lexsort((p, angle(p)))]  # sort by angle
    r2 = [0.26180339887499 - 0.19021130325903j,
          0.03819660112501 + 0.11755705045849j,
          0.4,
          0.03819660112501 - 0.11755705045849j,
          0.26180339887499 + 0.19021130325903j]
    p2 = [-0.80901699437495 - 0.58778525229247j,
           0.30901699437495 - 0.95105651629515j,
           1,
           0.30901699437495 + 0.95105651629515j,
          -0.80901699437495 + 0.58778525229247j]
    f2 = []

**Comment by endolith** [comment]
So there are 2 or 3 failures I haven't investigated, and a few minor issues:

- SciPy ordering of terms matches Octave, but not Matlab.  These are mathematically equivalent so it doesn't matter?  For repeated roots the order does match, though, which is necessary.
- Octave, Matlab and DADiSP all return `k=[]` while SciPy returns `k=[0]`.  Mathematically equivalent, but probably should be changed.
- Octave and Matlab accept `b=1` but SciPy fails unless it's written as `b=[1]`

> Do you want to put the above tests in a PR?

I'm not going to right now, so someone else can if they want.

Another bug I noticed:

```
residue([6, 0], [1, 5, 8, 4])
Out[33]: (array([  6.,  12.,  -6.]), array([-2., -2., -1.]), array([ 0.]))

residue([0, 0, 6, 0], [1, 5, 8, 4])
Out[34]: (array([  6.,  12.,  -6.]), array([-2., -2., -1.]), array([ 0.]))

residue([0, 0, 6, 0], [0, 0, 0, 1, 5, 8, 4])
Out[36]: (array([ inf,  inf, -inf]), array([-2., -2., -1.]), array([ 0.]))
```

These should all be identical.  Same for these:

```
residuez([6], [1, 5, 8, 4])
Out[37]: (array([-12.,  12.,   6.]), array([-2., -2., -1.]), array([ 0.]))

residuez([6, 0, 0], [1, 5, 8, 4])
Out[38]: (array([-12.,  12.,   6.]), array([-2., -2., -1.]), array([ 0.]))

residuez([6, 0, 0], [1, 5, 8, 4, 0, 0])
Out[39]:
(array([-12.,  12.,   6.,  nan,  nan]),
 array([-2., -2., -1.,  0.,  0.]),
 array([ 0.]))
```

```
invresz(array([-9.,  3.,  6.]), array([-2., -2., -1.]), [])
Out[55]: (array([ 0.,  0.,  6.]), array([ 1.,  5.,  8.,  4.]))

invresz(array([-9.,  3.,  6.]), array([-2., -2., -1.]), [0])
Out[56]: (array([ 0.,  0.,  6.,  0.]), array([ 1.,  5.,  8.,  4.]))
```

(for negative powers tf like in `residuez` and `invresz`, trailing zeros don't matter, so shouldn't be returned.  for positive powers tf like in `residue`, `invres`, and `tf2__`, leading zeros don't matter.)

```
invres(array([  6.,  12.,  -6.]), array([-2., -2., -1.]), array([ 0.]))
Out[71]: (array([ 6.,  0.]), array([ 1.,  5.,  8.,  4.]))

invres(array([  6.,  12.,  -6.]), array([-2., -2., -1.]), array([ ]))
Out[72]: (array([ 6.,  0.]), array([ 1.,  5.,  8.,  4.]))

invres(array([  6.,  12.,  -6.]), array([-2., -2., -1.]), array([ 0,0]))
Out[73]: (array([ 6.,  0.]), array([ 1.,  5.,  8.,  4.]))
```

**Comment by rgommers** [comment]
SciPy ordering of terms matches Octave, but not Matlab. These are mathematically equivalent so it doesn't matter? For repeated roots the order does match, though, which is necessary.

Agree, doesn't matter so leave as is.

    Octave, Matlab and DADiSP all return k=[] while SciPy returns k=[0]. Mathematically equivalent, but probably should be changed.

Sounds fine to change

    Octave and Matlab accept b=1 but SciPy fails unless it's written as b=[1]

Looks like this can easily be fixed by using ``atleast_1d``.

**Comment by rgommers** [comment]
Might indeed be good to keep this issue about test coverage, and open a new one (or multiple) for the bugs. One issue for multiple functions seems OK, would be good to group the same bugs that affect multiple functions.

**Comment by rgommers** [comment]
Adding the label easy-fix for improving the test coverage.

**Comment by rgommers** [comment]
Nice detective work @endolith!

**Comment by deepakgouda** [comment]
> Polarities do not match (does it matter?):
> 
> r, p, k = residuez([1, 2, 1], [1, -1, 0.3561])
> r == [-0.9041 - 5.9928j, -0.9041 + 5.9928j]
> p == [-0.5 - 0.3257j, -0.5000 + 0.3257j]
> k == 2.8082

@endolith According to the source you have mentioned, python gives the correct output i.e. p=[0.5+0.32572995j,  0.5-0.32572995j]. 

Wrong values are obtained in this case
```
b=[1]
a=[1, -0.7, 0.16, -0.012]
r, p, k= residuez(b, a)
r==[-8, -0.4,  9]
p==[0.2, 0.2, 0.3]
k==[0]
```

**Comment by endolith** [comment]
@deepakgouda 

> @endolith According to the source you have mentioned, python gives the correct output i.e. p=[0.5+0.32572995j, 0.5-0.32572995j].

Python gives p = 0.5±0.326j
The original matlab source gives p=-0.5±0.3257i
