### ISSUE TITLE
Documentation Error in scipy.optimize options for TNC

### ISSUE THREAD

**Issue by efremdan1** [scipy/scipy#4467]
The source code for scipy.minimize (I'm running python 2.7 on Ubuntu if that matters) allows for the user to input "eps," but the documentation (website below and also in the source code) indicates that this is not one of the options for that minimization method.

http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.optimize.show_options.html#scipy.optimize.show_options

**Comment by efremdan1** [comment]
Actually it looks like in _minimize_tnc in tnc.py gives "eps" as an option, so the issue is just with the online documentation.

**Comment by dlax** [comment]
FWIW, this would be solved by #4462.

**Comment by rgommers** [comment]
Fixed now: http://docs.scipy.org/doc/scipy-dev/reference/optimize.minimize-tnc.html
