### ISSUE TITLE
scipy.linalg.norm do not respect matrix sparsity 

### ISSUE THREAD

**Issue by burchanie** [scipy/scipy#4469]
scipy.linalg.norm takes a dense array of matrix/vector entries as an input. If one has a large and sparse matrix, the only correct way for calculating e.g. L1 matrix norm is to convert it to call todense() first. Would be good to have calculation of norms respecting matrix sparsity.

**Comment by ewmoore** [comment]
There is `sparse.linalg.onenormest` for L1 norm.

**Comment by burchanie** [comment]
Thanks for the reference. But its good to have more matrix norms: L2/largest singular value, Frobenius, min singular value similar to linalg.norm etc. I actually need to estimate condition numbers, and just realised there is no easy way.

**Comment by argriffing** [comment]
> Would be good to have calculation of norms respecting matrix sparsity.

This has been on the scipy todo list for a long time (https://github.com/scipy/scipy/issues/545)!

After abstract linear operator PRs like https://github.com/scipy/scipy/pull/4316 and https://github.com/scipy/scipy/pull/4294 are merged I plan to revive https://github.com/scipy/scipy/pull/4095 and also to implement the condition number estimation.  Searching the scipy github for sparse matrix norm PRs/issues I also see https://github.com/scipy/scipy/pull/3303.

**Comment by burchanie** [comment]
Seems you have a plan. I did not look into PRs like #4316 and #4294 yet, but from the discussion in  #3303 it seems it's nearly done.

Do you feel it makes any sense reviving #3303 (if it's quick)? I might be able to spend a little time on that, but since this would be my first commit to scipy, I'll need some basic guidance.

**Comment by argriffing** [comment]
> Do you feel it makes any sense reviving https://github.com/scipy/scipy/pull/3303

Yes, but I'm not great with git/github, so I'm not sure what is the best way to deal with PRs that may or may not be abandoned.  The crudest way would be to make your own new branch and just copy the changes from that PR into your branch, but this would lose the original meta-data.  I'm not sure how much people care about that -- I probably care about it less than I should.

The complication that killed that PR seems to have been complex matrices, which the original contributor probably didn't need.

Another complication is the distinction between np.ndarray vs. np.matrix conventions for `scipy.sparse`, especially if the `axis` keyword is included.  The current behavior includes

```
>>> scipy.sparse.identity(4).sum(axis=1)
matrix([[ 1.],
        [ 1.],
        [ 1.],
        [ 1.]])
```

but I'd guess that no one would want to continue this convention for hypothetical new functions like `norm(scipy.sparse.identity(4), axis=1)`.  On the other hand maybe they do, I don't know.

**Comment by ewmoore** [comment]
Well, one thing to do is to to make a new branch, then do a pull from the existing branch.  You'll likely have to fixup the merge issues to get this to complete.  So
```
[mooreew@xavier scipy2]$ git pull https://github.com/perryism/scipy.git master
remote: Counting objects: 49, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 49 (delta 28), reused 40 (delta 28)
Unpacking objects: 100% (49/49), done.
From https://github.com/perryism/scipy
 * branch            master     -> FETCH_HEAD
Auto-merging scipy/sparse/__init__.py
Auto-merging scipy/sparse/base.py
Auto-merging scipy/sparse/csc.py
Auto-merging scipy/sparse/csr.py
Auto-merging scipy/sparse/data.py
CONFLICT (content): Merge conflict in scipy/sparse/data.py
Auto-merging scipy/sparse/linalg/__init__.py
Auto-merging scipy/sparse/tests/test_base.py
CONFLICT (content): Merge conflict in scipy/sparse/tests/test_base.py
Automatic merge failed; fix conflicts and then commit the result.

```

Another option is to checkout the branch in question, and then do a `git checkout -b new_branch_name`, followed by a rebase.  During the rebase you'll have to correct the same failures that you'd hit using the `pull` based approach.

I don't know that it matters which approach you take, but it's probably worth trying to keep the authorship information intact if you can.

**Comment by sethtroisi** [comment]
`scipy.sparse.linalg.norm` supports more than L1 now.

See https://github.com/scipy/scipy/pull/4671 and https://github.com/scipy/scipy/pull/4505
