### ISSUE TITLE
scipy.sparse non-native endian bug

### ISSUE THREAD

**Issue by sbailey** [scipy/scipy#4476]
scipy.sparse.dia_matrix created with non-native endian input data silently produce crazy wrong answers:

    d = np.ones((3,4))
    offsets = [-1,0,1]
    a = scipy.sparse.dia_matrix( (d.astype('<f8'),offsets), (4,4))
    b = scipy.sparse.dia_matrix( (d.astype('>f8'),offsets), (4,4))

    v = np.arange(4)
    a.dot(v)
    b.dot(v)

On my little-endian machine, a.dot(v) gives the correct answer:

    array([ 1.,  3.,  6.,  5.])

while b.dot(v) silently gives a very incorrect answer:

    array([  3.03865194e-319,   9.11595582e-319,   1.82319116e-318,
             1.51932597e-318])

I have not checked whether this bug affects other types of sparse matrices.

**Comment by pv** [comment]
This change could fix it:
https://github.com/pv/scipy-work/commit/a707ff5ab90c2494d3c8385b237a75e7bc647511

**Comment by v0dro** [comment]
Has this been fixed already?

I'd like to take this up if not .

**Comment by pv** [comment]
The fix liked to above probably does it, but nobody has tested it or
written the necessary tests. If you want to take it up, please go ahead.

**Comment by v0dro** [comment]
Ok will do thanks.
