### ISSUE TITLE
Add ability to load/save HDF5 files

### ISSUE THREAD

**Issue by petebachant** [scipy/scipy#4483]
Something similar to `loadmat`, and `savemat`, but saving to HDF5 would be helpful. I have written these in [another package](https://github.com/petebachant/PXL/blob/b1d39d63460a63c706199c6908b8e4880ad5e035/pxl/timeseries.py#L131), which depends on `h5py` and a somewhat on `pandas`. Would this be appropriate to try to include in a pull request, or is the additional dependency unacceptable?

**Comment by matthew-brett** [comment]
I'm not the person to make that call, but I would have thought it would be acceptable to have some functions that error if an optional h5py dependency is missing.  Depending on both h5py and pandas would be stretching it.  But - would these functions not go better in h5py?

**Comment by rgommers** [comment]
This should be decided on scipy-dev, so I suggest you propose it there @petebachant. I think I agree with @matthew-brett though; I don't see much added value in an optional dependency here. And I wouldn't want to make a choice between ``h5py`` and ``pytables`` anyway.

**Comment by petebachant** [comment]
I also think I agree with @matthew-brett. I didn't even think about adding these to h5py initially, but it seems more logical.
