### ISSUE TITLE
ftol in optimize.fmin fails to work

### ISSUE THREAD

**Issue by x-u** [scipy/scipy#4484]
Please check the question here: http://stackoverflow.com/questions/28167648/seeking-convergence-with-optimize-fmin-on-scipy
I think there is something wrong in the if loop in function "_minimize_neldermead". The correct code should be 
"if (np.absolute(x_old-x).sum() <= 1e-4) and (np.absolute(Q_old-Q).sum() <= 1e-4):"
But I'm not 100% sure since I'm not an expert on this.

**Comment by rgommers** [comment]
In the stackoverflow discussion the conclusion is that the docstring is not wrong but could be made clearer.

**Comment by andyfaff** [comment]
Fixed in #5939.
