### ISSUE TITLE
lobpcg/sparse performance regression Jun 2014?

### ISSUE THREAD

**Issue by pv** [scipy/scipy#4506]
Something seems to have happened around May-Jun 2014:
https://pv.github.io/scipy-bench/#sparse_linalg_lobpcg.Bench.time_sakurai
https://pv.github.io/scipy-bench/#sparse_linalg_lobpcg.Bench.time_mikota

Not sure if this is (i) benchmark artefact, (ii) specific to lobpcg, (iii) general sparse matrix issue.
Might be useful to try to look into...

**Comment by argriffing** [comment]
I think lobpcg is in some kind of limbo.  The meaning of small vs. large eigenvalues is uncertain.  For example
https://github.com/scipy/scipy/issues/4174
https://github.com/scipy/scipy/pull/4188

**Comment by pv** [comment]
I'll be somewhat surprised if it is the symeig/eigh stuff, given that it seemed benign. Maybe a good opportunity to test whether `asv find` actually works :)

**Comment by argriffing** [comment]
The PR https://github.com/scipy/scipy/pull/3594 changed the behavior of the code in response to bug reports, so it would not surprise me that it would affect timings.  I think there are two code paths according to large vs. small number of requested eigenpairs, and I think the two code paths are currently not in agreement at the crossover point.  There are currently open issues and PRs to address this, but the discussion seems no longer active.

**Comment by pv** [comment]
ASV blames ace68447, which is the symeig/eigsh stuff.
Possibly, eigsh has larger overhead than calling LAPACK functions directly?
https://gist.github.com/pv/f5399ea6d8afa5807bea

**Comment by argriffing** [comment]
Is `eigsh` in that PR?

Reading over it, I might blame
`assert_allclose(M.T, M, rtol=rtol, atol=atol, err_msg=str(M.T - M))`
which over-eagerly creates the error message.

**Comment by pv** [comment]
ok,indeed, that sounds more plausible.

**Comment by argriffing** [comment]
I'd be more inclined to make a lobpcg performance PR if `lobpcg` were not broken...

**Comment by argriffing** [comment]
By the way, I think it's really cool that you found this using the new ASV benchmarking!

**Comment by pv** [comment]
If the issue is only lobpcg speed rather than a general sparse speed
issue, then it's lower priority of course.
