### ISSUE TITLE
sparsetools.cxx call_thunk can segfault due to out of bounds if strlen(spec) < MAX_ARGS during cleanup

### ISSUE THREAD

**Issue by LazyKoala** [scipy/scipy#4510]
At: https://github.com/scipy/scipy/blob/master/scipy/sparse/sparsetools/sparsetools.cxx#L420

It shouldn't be accessing spec[j] unchecked. Probably the loop should be modified to iterate through spec like in the other loops in that function.

**Comment by LazyKoala** [comment]
We found this potential segfault using AddressSanitizer.

**Comment by pv** [comment]
Thanks, pretty obvious bug.

**Comment by dakoner** [comment]
Do you need a patch for this?  I hit this recently (also detected w/ ASAN) and would like to see it fixed upstream.  I've tried a similar approach to LazyKoala with success.

**Comment by rgommers** [comment]
@dakoner that would be very helpful, thanks
