### ISSUE TITLE
special.hankel2(0,0) delivers (nan+nan*j) instead of (1+nan*j)

### ISSUE THREAD

**Issue by spors** [scipy/scipy#4517]
When evaulating the zeroth-order Hankel function of second kind at zero

```
In[121]: scipy.special.hankel2(0,0)
Out[121]: (nan+nan*j)
```

the real value is nan instead of 1. Bessel and Neumann function deliver the correct results

```
In[126]: scipy.special.jv(0,0)
Out[126]: 1.0

In[127]: scipy.special.yn(0,0)
Out[127]: -inf
```

The combination of both according to the definition of the Hankel function again the wrong result

```
In[125]: scipy.special.jv(0,0) - 1j*scipy.special.yn(0,0)
Out[125]: (nan+inf*j)
```

**Comment by pv** [comment]
The second result is correct if you follow C99 complex arithmetic:
`nan+infj` is one representation for the complex infinity.

**Comment by ewmoore** [comment]
Checking against two other sources, mpmath produces the same results as
scipy and matlab gives simply nan.
