### ISSUE TITLE
uses_mkl fails sometimes

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [scipy/scipy#4518]
I am compiling scipy on a linux computer.
I am untaring blas and lapack into directories, and then setting up LAPACK_SRC and BLAS_SRC variables.
However, this fails when I try and build scipy.
...

```
  File "scipy/lib/blas/setup.py", line 39, in configuration
    sources += get_g77_abi_wrappers(lapack_opt)
  File "/tmp/foo/scipy-0.15.1/scipy/_build_utils/_fortran.py", line 64, in get_g77_abi_wrappers
    if needs_g77_abi_wrapper(info):
  File "/tmp/foo/scipy-0.15.1/scipy/_build_utils/_fortran.py", line 50, in needs_g77_abi_wrapper
    elif uses_mkl(info) and sys.platform == "darwin":
  File "/tmp/foo/scipy-0.15.1/scipy/_build_utils/_fortran.py", line 39, in uses_mkl
    if r_mkl.search(library):
TypeError: expected string or buffer
```

I can fix this error by ignoring the failures in uses_mkl by a try execpt block like:

```
def uses_mkl(info):
    r_mkl = re.compile("mkl_core")
    libraries = info.get('libraries', '')
    for library in libraries:
      try:
        if r_mkl.search(library):
            return True
      except:
        pass

    return False
```

**Comment by pv** [comment]
Sounds like Python 3, is this the case?

**Comment by joshua-cogliati-inl** [comment]
I have had this happen with both python 3 and python 2.7.

**Comment by joshua-cogliati-inl** [comment]
and if I change it to
```
except:
   print type(library)
```

it will print out
```<type 'tuple'>```
several times.

**Comment by joshua-cogliati-inl** [comment]
An example of what library is when it fails:
```('fblas_src', {'sources': ['/home/jjc/raven_libs/build/BLAS/caxpy.f',...'/home/jjc/raven_libs/build/BLAS/ztrsm.f'], 'language': 'f77'})```
Basically, regular expressions fail when trying to search a tuple.

**Comment by rgommers** [comment]
I think we should deprecate `BLAS_SRC` and `LAPACK_SRC` in numpy, and close this. Building BLAS and LAPACK from source should really be out of scope for numpy, seems quite unhealthy.

**Comment by ilayn** [comment]
Indeed, that was what I was wondering the other day. This dependence is not really needed for NumPy.

**Comment by rgommers** [comment]
Done in https://github.com/numpy/numpy/pull/18348. Will close this issue. "don't do this" is the only advice we can give.
