### ISSUE TITLE
g77_abi_wrappers needed on Linux for MKL as well

### ISSUE THREAD

**Issue by hahnjo** [scipy/scipy#4520]
In `scipy/_build_utils/_fortran.py`, in function `needs_g77_abi_wrapper`, it currently says:

```python
    # XXX: is this really true only on Mac OS X ?
    elif uses_mkl(info) and sys.platform == "darwin":
        return True
```

The check for the platform should be removed, I have only got it to work with the abi_wrappers. Otherwise I got the same segfaults as in #3193 (see also: https://software.intel.com/en-us/articles/mkl-single-dynamic-library-libmkl-rtso-does-not-conform-to-the-gfortran-calling-convention)

Used versions:
scipy 0.15.1
GCC 4.4.7 (RedHat 6.6)
Intel Compiler 15.0.2.164 with Intel MKL

**Comment by pv** [comment]
The intel issue mention only the single dynamic library. Does this apply to whole MKL?

**Comment by hahnjo** [comment]
I at least got segfaults when it was compiled with the dummy wrappers and it worked when using the real wrapper...
