### ISSUE TITLE
Missing header file in wrap_g77_abi_c.c

### ISSUE THREAD

**Issue by hahnjo** [scipy/scipy#4522]
When compiling `scipy/_build_utils/src/wrap_g77_abi_c.c`, I get an error because the header file `Accelerate/Accelerate.h` is not found.

Simply removing the include line makes it compile again. Is this include line needed?

**Comment by pv** [comment]
The include statement is not there in the development version.

**Comment by hahnjo** [comment]
Sorry, didn't check and used bundled 0.15.1
