### ISSUE TITLE
error in site documentation for poisson.pmf() method

### ISSUE THREAD

**Issue by romunov** [scipy/scipy#4526]
[Probability mass function method (`pmf`) for Poisson distribution](http://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.poisson.html#scipy.stats.poisson) claims first argument to be `pmf(x, mu, loc=0)` whereas the actual argument `x` should be `k`, as evident in

```
>>> help(poisson.pmf)
Help on method pmf in module scipy.stats._distn_infrastructure:

pmf(self, k, *args, **kwds) method of scipy.stats._discrete_distns.poisson_gen instance
    Probability mass function at k of the given RV.
    
    Parameters
    ----------
    k : array_like
        quantiles
```

**Comment by ev-br** [comment]
Fixed in gh-4499.

Pauli fixed the automated doc build, so it's available online at
http://docs.scipy.org/doc/ and select scipy(development version)
