### ISSUE TITLE
Inconsistency in fmin_slsqp

### ISSUE THREAD

**Issue by kazemakase** [scipy/scipy#4531]
It seems that `fmin_slsqp` behaves inconsistently when passing `eqcons` and `ieqcons` in contrast to passing `f_eqcons` and `f_ieqcons`.

    import numpy as np
    import scipy as sp
    
    print('Numpy:', np.__version__)
    print('Scipy:', sp.__version__)
    
    from scipy.optimize import fmin_slsqp
    
    
    n = 5
    m = 5
    
    np.random.seed(42)
    y = np.random.randn(n, 1)
    M = np.random.randn(n, m) > 0
    I = np.random.randn(n, m) > 0
    w0 = np.zeros(M.shape[1])
    w0 = np.random.randn(*w0.shape)
    
    
    def objective(w, y=y, M=M):
        return np.sum((y - np.dot(M, w))**2)
    
    def eq_constraints(w, I=I):
        """ Constraint: Iw = 1 """
        return np.dot(I, w) - 1
    
    
    def ieq_constraints(w):
        """ Constraint: w >= 0 """
        return w
    
    
    res = fmin_slsqp(objective, w0, disp=1,
                     eqcons=[lambda w: np.dot(I[i, :], w) - 1 for i in range(n)],
                     ieqcons=[lambda w: w[i] for i in range(m)])
    
    res = fmin_slsqp(objective, w0, f_eqcons=eq_constraints, f_ieqcons=ieq_constraints, disp=1)

This leads to the output:

    Numpy: 1.9.1
    Scipy: 0.14.0
    Singular matrix C in LSQ subproblem    (Exit mode 6)
                Current function value: 18.1957175675
                Iterations: 1
                Function evaluations: 7
                Gradient evaluations: 1
    Iteration limit exceeded    (Exit mode 9)
                Current function value: 22.1615251453
                Iterations: 101
                Function evaluations: 1673
                Gradient evaluations: 101

I don't think this behavior is expected. Instead I would expect both invocations of fmin_slsqp to behave similarly (either reporting a singular matrix in both cases, or exceeding the iteration limit in both cases).

Furthermore, when setting `m` > `n`, the second call raises `ValueError: all the input array dimensions except for the concatenation axis must match exactly` (much like the error reported in #3988).

**Comment by dlax** [comment]
I get:
```
Numpy: 1.8.2
Scipy: 0.14.1
Singular matrix C in LSQ subproblem    (Exit mode 6)
            Current function value: 18.1957175675
            Iterations: 1
            Function evaluations: 7
            Gradient evaluations: 1
Singular matrix C in LSQ subproblem    (Exit mode 6)
            Current function value: 18.1957175675
            Iterations: 1
            Function evaluations: 7
            Gradient evaluations: 1
```

Could you try with scipy 0.14.1?

**Comment by kazemakase** [comment]
I don't have 1.4.1 available in my package managers, but I tried the following combinations:

Arch Linux, numpy 1.9.0, scipy 0.14.0
Arch Linux, numpy 1.9.0, scipy 0.15.1
Arch Linux, numpy 1.9.1, scipy 0.15.1
Windows/Anaconda, numpy 1.9.1, scipy 0.14.0
Windows/Anaconda, numpy 1.8.2, scipy 0.15.1
Windows/Anaconda, numpy 1.9.1, scipy 0.15.1

In each case I got the same difference as above. Since it happens across versions of numpy, scipy and across operating systems I'm not sure where to pinpoint the problem.

**Comment by Andreea-G** [comment]
@kazemakase , there's a bug in your eqcons and ieqcons in the test you gave. It should be
eqcons=[lambda w, i=i: np.dot(I[i, :], w) - 1 for i in range(n)]
ieqcons=[lambda w, i=i: w[i] for i in range(m)]

To see a simpler example run the following:

fun_wrong = [lambda x: x*i for i in range(10)]
[f(1) for f in fun_wrong]
fun_right = [lambda x, i=i: x*i for i in range(10)]
[f(1) for f in fun_right]

The first gives [9, 9, 9, 9, 9, 9, 9, 9, 9, 9] which is not what you'd want, while the second gives [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] as desired.

@dlax , no bug in SciPy in this regard. The results are consistent when this is corrected in eqcons and ieqcons in the test kazemakase provided.

**Comment by pv** [comment]
Closing: bug in user code.
