### ISSUE TITLE
box constraint in scipy optimize cobyla

### ISSUE THREAD

**Issue by edwintye** [scipy/scipy#4532]
I don't really understand why box constraints are not allowed in cobyla, because every box constraint is an inequality constraint , x >= lb  is x - lb >= 0 and x <= lb is ub - x >= 0.

This should be easily accomplished using something along the lines of 

% boxBounds is an numpy.ndarray of shape (len(x0),2)
% x0 is the parameter
cons = list()
for i in range(0,len(x0)):
    cons += ({'type': 'ineq', 'fun': (lambda x,i : x[i]-boxBounds[i,0]), 'args': (i,)},)
    cons += ({'type': 'ineq', 'fun': (lambda x,i : boxBounds[i,1]-x[i]), 'args': (i,)},)

or with two argument where the second is the value of the bound.

**Comment by samuela** [comment]
+1 It's really weird to get an out of bounds result when using everything just as documented:

```python
In [34]: scipy.optimize.minimize(func, 0, method='COBYLA', bounds=[(0, 2 * numpy.pi)])
/Users/samuelainsworth/research/res-venv/lib/python2.7/site-packages/scipy/optimize/_minimize.py:400: RuntimeWarning: Method COBYLA cannot handle bounds.
  RuntimeWarning)
Out[34]: 
     fun: -0.99999999543552442
   maxcv: 0.0
 message: 'Optimization terminated successfully.'
    nfev: 24
  status: 1
 success: True
       x: array(-1.57070078125)
```

The warning is great, but this should at the very least be included in the documentation.
