### ISSUE TITLE
enh: extract second order sensitivity information from results of bfgs-like optimization

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4545]
Suggested by @rmcgibbo http://mail.scipy.org/pipermail/scipy-dev/2015-February/020375.html.  I share the same use-case -- approximating confidence intervals of maximum likelihood parameter estimates when the objective function is a negative log likelihood.

**Comment by pv** [comment]
My comments from the thread apply:

- In principle, this is an OK feature to add even though has some maintenance concerns as the hessian is not an explicitly documented return value.
- You could also record the gradient evaluations and construct the bfgs approximation yourself. This might miss on whatever regularization l-bfgs-b does (I don't know what it does) however.

**Comment by andyfaff** [comment]
I think is closable now, `Optimize.hess_inv` is set by LBFGSB.
