### ISSUE TITLE
enh: wrapped normal distribution

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4548]
The [von Mises](http://en.wikipedia.org/wiki/Von_Mises_distribution) distribution on a circle is already included in `scipy.stats` and can be seen as an approximation of the [wrapped normal distribution](http://en.wikipedia.org/wiki/Wrapped_normal_distribution) which is the circular analogue of the [normal distribution](http://en.wikipedia.org/wiki/Normal_distribution).

I was tempted to implement this wrapped normal distribution in scipy, but its density requires the [jacobi theta function](http://en.wikipedia.org/wiki/Theta_function#Jacobi_theta_function) which I'm not sure is included in `scipy.special`.  Some related Cephes functions are included like [`ellipj`](http://docs.scipy.org/doc/scipy/reference/generated/scipy.special.ellipj.html#scipy.special.ellipj).

**Comment by argriffing** [comment]
Yesterday this was (independently?) proposed as a 2015 GSoC on the mailing list.
http://mail.scipy.org/pipermail/numpy-discussion/2015-February/072351.html

> Implement a set of circular statistics functions comparable to those in R or MATLAB circular statistics toolbox.

**Comment by rgommers** [comment]
This is relevant: gh-4598. Circular distributions aren't supported too well by the generic framework.

**Comment by NeilGirdhar** [comment]
The von-mises distribution is more than just an approximation of the wrapped normal.  Like the normal distribution, the von-mises distribution is an exponential family, which makes it suitable for regression (you can make a generalized linear model out of it) or Bayesian statistics (you can add in the space of natural parameters to accumulate observations).

**Comment by tupui** [comment]
Hi all, closing this as we now have the Von mises distribution 😃
