### ISSUE TITLE
filter out convergence warnings in optimization tests

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4554]
The `optimize` tests now give `RuntimeWarning`s promoted to Exceptions with development versions of numpy.  If someone wants to go through the tests and add converge annotations or filters as suggested in https://github.com/scipy/scipy/pull/4312#issuecomment-75699528 this would be cool.

**Comment by rgommers** [comment]
note that the comment linked above has the pattern to use. More examples can easily be found by searching the tests for use of ``warnings``

**Comment by rgommers** [comment]
preferably this should be done before the next release branch is created.
