### ISSUE TITLE
scipy.sparse.rand raises OverflowError instead of ValueError on win-amd64

### ISSUE THREAD

**Issue by cgohlke** [scipy/scipy#4557]
See also http://stackoverflow.com/questions/28693545/creating-a-large-sparse-matrix-in-scipy-sparse.

Using scipy‑0.15.1 and numpy‑1.8.2+mkl on win-amd64 `scipy.sparse.rand(100000, 100000, 0.0001)` raises `OverflowError: Python int too large to convert to C long` instead of `ValueError: Trying to generate a random sparse matrix such as the product of dimensions is greater than 2147483647 - this is not supported on this machine`

Numpy's mtrand and randomkit use C long data types. Hence the following patch raises the expected ValueError on Windows:

``` diff
diff --git a/scipy/sparse/construct.py b/scipy/sparse/construct.py
index 58a993c..2a2dc3e 100644
--- a/scipy/sparse/construct.py
+++ b/scipy/sparse/construct.py
@@ -694,7 +694,7 @@ def rand(m, n, density=0.01, format="coo", dtype=None, random_state=None):

     tp = np.intc
     if mn > np.iinfo(tp).max:
-        tp = np.int64
+        tp = np.int_

     if mn > np.iinfo(tp).max:
         msg = """\
```

**Comment by argriffing** [comment]
I don't understand, is generating a random sparse matrix such that the product of dimensions is greater than 2147483647 really not supported on that machine?

**Comment by argriffing** [comment]
OK after reading
https://github.com/numpy/numpy/search?q=%22too+large+to+convert+to+c+long%22&type=Issues
I think the root of the problem is that numpy has no way to sample a random integer from a range of more than a few billion on platforms where a C `long` is only 32 bits.  Even on some 64 bit platforms, a C `long` apparently is only 32 bits.

**Comment by rgommers** [comment]
@argriffing I had a look at your two PRs; they don't include this suggested fix right? Shall we just apply the diff above in a separate PR?
