### ISSUE TITLE
odeint messages

### ISSUE THREAD

**Issue by albertotonda** [scipy/scipy#4565]
Inside odeint, there's a block of code:

    if output[-1] < 0:
        print(_msgs[output[-1]])
        print("Run with full_output = 1 to get quantitative information.")
    else:
        if printmessg:
            print(_msgs[output[-1]])

which should be corrected, IMHO: why is the function writing a message to standard output? If it's a warning, it should write it to stderr, or copy it inside the returned message. There should also be an option to "silence" it.

**Comment by rgommers** [comment]
fixed in gh-4662
