### ISSUE TITLE
Mathjax is rendering multiple equations in the docs

### ISSUE THREAD

**Issue by moorepants** [scipy/scipy#4567]
I'm looking at http://docs.scipy.org/doc/scipy/reference/tutorial/fftpack.html#fast-fourier-transforms right now with the lastest Firefox on Ubuntu 14.04 and I see this:

![selection_056](https://cloud.githubusercontent.com/assets/276007/6405650/f2e43556-bdda-11e4-8381-afc25b998c02.png)

Notice that the math is repeated and each repeat has decreasing font.

I can't find any Mathjax issues mentioning this.

**Comment by moorepants** [comment]
Note that this also happens in Chromium.

**Comment by pv** [comment]
I don't see this in chromium 40.0.2214.111 or in firefox 36

**Comment by moorepants** [comment]
Sorry, I have Firefox 35.0.1 and Chromium 39.0.2171.65, not the latest but I think the latest provided by my distro's repositories.

**Comment by moorepants** [comment]
I filed this issue on mathjax's tracker too: https://github.com/mathjax/MathJax/issues/1070

**Comment by ev-br** [comment]
Seems to have been fixed on the MathJax side: https://github.com/mathjax/MathJax/issues/1068, so closing. @moorepants please reopen if the issue persists.
