### ISSUE TITLE
interp1d memory leak

### ISSUE THREAD

**Issue by jwkvam** [scipy/scipy#4568]
I think there may be a memory leak in `interp1d`. I tried running the following script with `interp1d` or `UnivariateSpline`. I simply interpolate many iterations and sample the memory consumed by the process in MB. I'm using conda on osx64 with scipy 0.15.2 and numpy 0.19.1.

```
#!/usr/bin/env python -u
# encoding: utf-8

import numpy as np
from scipy import interpolate
import gc
import os
import psutil

def sample_mem():
    gc.collect()
    process = psutil.Process(os.getpid())
    return process.get_memory_info()[0] / float(2 ** 20)

def make():
    dom = np.arange(100)
    np.random.seed(0)
    ran = np.random.randn(len(dom))
 
    interp_func = interpolate.interp1d(x=dom, y=ran, copy=True, kind='cubic')
    # interp_func = interpolate.UnivariateSpline(x=dom, y=ran, s=0, k=3)
    for i in np.linspace(0, 1, 50):
        shift = interp_func(i)

if __name__=='__main__':
    for i in range(10000):
        make()
        after = sample_mem()
        print(after)
```
This is the result of using `interp1d` interestingly the memory usage flattens out around the 6000th iteration.
![image](https://cloud.githubusercontent.com/assets/86304/6408655/6f3b1192-be0d-11e4-9c1c-f0749285813b.png)
This is the result of using `UnivariateSpline`. Notice how the memory increase are much less significant.
![image](https://cloud.githubusercontent.com/assets/86304/6408656/73c027ca-be0d-11e4-9680-bc796f9b9573.png)

**Comment by ev-br** [comment]
Cannot reproduce it on Ubuntu 12.04 with current master. Modifying your example to print out every 500 iterations only:

```
$ python interp1d_memleak.py 
(0, 25.1328125)
(500, 25.30078125)
(1000, 25.30078125)
(1500, 25.30078125)
(2000, 25.30078125)
(2500, 25.30078125)
(3000, 25.30078125)
(3500, 25.30078125)
(4000, 25.30078125)
(4500, 25.30078125)
(5000, 25.30078125)
(5500, 25.30078125)
(6000, 25.30078125)
(6500, 25.30078125)
(7000, 25.30078125)
(7500, 25.30078125)
(8000, 25.30078125)
(8500, 25.30078125)
(9000, 25.30078125)
(9500, 25.30078125)
```

What happens to your memory consumption if you specify `copy=False`?

**Comment by jwkvam** [comment]
I just tried this on my Ubuntu 14.04 machine and see the same results as you, no memory increase.

If I set `copy=False`, I still see the same results on osx. This is still using both 0.15.1 x64 from conda. Thanks for checking on it @ev-br. I guess feel free to mark this lowest priority, it's not really affecting me because of the work around. Or if there are other simple debugging steps that I could take feel free to let me know.

**Comment by pv** [comment]
Since the memory usage flattens out, it's not a memory leak, and does not indicate a bug. I would suggest closing this issue.

Some plausible explanations: libc malloc not releasing memory immediately, Apple Accelerate allocating some scratch cache memory, etc.

**Comment by jwkvam** [comment]
Makes sense, I'll just close it.
