### ISSUE TITLE
stable implementation of givens rotation

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4571]
I needed this private function:
https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/isolve/lsqr.py#L63

This is like http://en.wikipedia.org/wiki/Givens_rotation.  Also [`symGivens2`](http://deeplearning.net/software/pylearn2/library/expr.html#pylearn2.expr.basic.symGivens2) in pylearn2, and [`planerot`](http://www.mathworks.com/help/matlab/ref/planerot.html) in Matlab.

**Comment by ewmoore** [comment]
Does `scipy.linalg.blas.drotg` work for you?  It doesn't provide the 2-norm of the inputs, but it does give you cosine and sine.  Over in #4249, I also add wrappers around (s,c,d,z)lartg which might be, ultimately, what you really want.

**Comment by argriffing** [comment]
> Does [`scipy.linalg.blas.drotg`](http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.linalg.blas.drotg.html) work for you?

Yes, that looks like it would work.  Thanks!
