### ISSUE TITLE
Sparse compressed major axis slicing with sequence is slow

### ISSUE THREAD

**Issue by lightcatcher** [scipy/scipy#4573]
I have a CSC matrix of shape ``(1000, 100000)`` and density 0.05. The current compressed sequence slicing implementation performs a matrix multiplication, and takes 10-20ms regardless of how many columns are selected. For reference, this is a similar amount of time to a hard drive disk seek.

```python
%timeit X[:, [0, 1, 4000]]
100 loops, best of 3: 11.2 ms per loop

%timeit X[:, np.arange(10000, 20000)]
10 loops, best of 3: 20.9 ms per loop
```
My use case involves taking many small slices of the matrix. I've written my own slicing function which is considerably faster for slicing out small numbers of columns.

```python
def ix(X, col_indices):
    """ computes X[:, col_indices] """
    n_cols = len(col_indices)

    starts = X.indptr[col_indices]
    ends = X.indptr[col_indices + 1]

    indptr = np.hstack((0, (ends - starts).cumsum()))

    idxs = np.fromiter(chain.from_iterable(xrange(starts[i], ends[i]) for i in xrange(n_cols)),
                       dtype=np.int32, count=indptr[-1])

    data = X.data[idxs]
    indices = X.indices[idxs]

    #return data, indices, indptr                                                                                                                                                                                    
    return sp.csc_matrix((data, indices, indptr), shape=(X.shape[0], len(indptr) - 1))
```

Performance:
```python
%timeit mat_prod.ix(Z, np.array([0, 1, 4000]))
10000 loops, best of 3: 160 µs per loop

%timeit mat_prod.ix(Z, np.arange(1000))
100 loops, best of 3: 5.59 ms per loop

%timeit mat_prod.ix(Z, np.arange(2000))
100 loops, best of 3: 11.8 ms per loop
```

The time cost of my method grows linearly in the number of columns selected, and is faster than the existing method when selecting <~2000 columns.

Additionally, when I'm only selecting 3 columns about 65% of the total time is spent in the creation of the CSC matrix in the last line of my method, and 78% of that time is spent in the ``get_index_dtype`` call on line 53 of ``compressed.py`` and the ``self.check_format(full_check=False)`` call on line 88 of the same file. Both of these calls are just sanity checking input, but they slow down my hot inner loop by a factor of 2.

I'm willing to submit PRs with these fixes, but as I've never contributed to scipy before I'd like to make sure this work is wanted. Particularly I want to

1. Use my major axis slicing algorithm for compressed sparse matrices for small sequence length, and then fall back to the existing algorithm for large sequence length.

2. Add a flag to ``_cs_matrix.__init__`` to disable sanity checks for performance purposes (and use this flag where Scipy initializes compressed sparse matrices that it is relatively confident are valid).

Will either of these changes get merged if I submit a PR with them?

**Comment by jaimefrio** [comment]
It is a little convoluted, but you can replace your iterator construct with a vectorized implementation.

You basically want to concatenate several ranges of varying start points and lengths. Having the starts and lengths identified, we can know where each range will start in the output array, and how long this will be. So we can create an array of 1's of the right length, and by carefully doctoring the values in the start positions of each range, get the desired concatenated array calling `cumsum` on it:

```
def concat_ranges(starts, lens):
    starts = np.asarray(starts)
    lens = np.asarray(lens)
    range_starts = lens.cumsum()
    out = np.ones(range_starts[-1], np.intp)
    out[0] = starts[0]
    out[range_starts[:-1]] += starts[1:] - starts[:-1] - lens[:-1]
    return out.cumsum()

>>> concat_ranges([4, 2, 8], [3, 5, 2])
array([4, 5, 6, 2, 3, 4, 5, 6, 8, 9])
```

You will want to time it, but it is very likely going to be faster than your current implementation for large sequence lengths, and may avoid the branching you were proposing.

**Comment by lightcatcher** [comment]
My original performance numbers are from Scipy 0.14, and the current Scipy 0.16dev performance is much better (and within a factor of 2 of my code all cases, and slightly faster than my code in some cases). Because of this, I'm closing this issue.

**Comment by lightcatcher** [comment]
@jaimefrio I discovered http://docs.scipy.org/doc/numpy/reference/generated/numpy.r_.html does slice concatenation.
