### ISSUE TITLE
Conflicting doc statements for scipy.sparse.linalg.eigsh()

### ISSUE THREAD

**Issue by nonhermitian** [scipy/scipy#4579]
In the docs for the scipy.sparse.linalg.eigsh(), it states that this function is suitable for finding the eigenvalues of a Hermitian (complex) sparse matrix, as one would assume.  However in scipy.sparse.linalg.eigen.arpack.arpack.py it states that "There is no Hermetian complex/double complex interface. To find eigenvalues of a Hermetian matrix you must use eigs() and not eigsh()."  I am guessing that the doc string for eigsh() is the correct answer (hopefully since our project has been assuming this for a while now).

**Comment by pv** [comment]
ARPACK does not have a special solver for hermitian matrices. `eigsh` calls `eigs` if the input matrix is complex-valued.

**Comment by nonhermitian** [comment]
Ahh good to know. It might be good to mention the use of eigs in the complex case in the doc strings for eigsh. I can do a pull for this if needed.

**Comment by pv** [comment]
The documentation of the `A` parameter in `eigsh` probably should be updated, too, right now it discusses only real symmetric matrices. I'd remove the whole "Wrapper implementation notes" comment from the beginning --- it doesn't seem to be very useful.

**Comment by AtsushiSakai** [comment]
I think this issue is already addressed in #12338. This PR added this docstring:
https://github.com/scipy/scipy/blob/4cf21e753cf937d1c6c2d2a0e372fbc1dbbeea81/scipy/sparse/linalg/_eigen/arpack/arpack.py#L1364-L1366
So, let's close this. If anything we should do that I'm missing, please reopen this or create a new issue.
