### ISSUE TITLE
scipy.ndimage.filters.convolve documenation is incorrect

### ISSUE THREAD

**Issue by jiskattema** [scipy/scipy#4580]
the meaning of the origin parameter is different:
default value of 0 is equivalent to the center of the filter, and the origin parameter is counted from the center, not from weights[0,0].

#!/usr/bin/env python

import numpy as np
import scipy.ndimage as nd

a = np.zeros([11,11])
a[5,5] = 1.0

b = np.ones([5,5])

print "Without origin: "
print nd.convolve( a, b, mode='constant', cval=0, )

print"With origin (0,0): "
print nd.convolve( a, b, mode='constant', cval=0, origin=(0,0) )

print "With origin (1,1): "
print nd.convolve( a, b, mode='constant', cval=0, origin=(1,1) )

print "With origin (-1,-1): "
print nd.convolve( a, b, mode='constant', cval=0, origin=(-1,-1) )

**Comment by nbaka** [comment]
The equation in the documentation is also incorrect. The correct convolution equation, which is also what is implemented in scipy, is: C_i = \sum_i(I_{i+k-j}W_j) instead I_{i+j-k}W_j .
