### ISSUE TITLE
DOC: optimize: _minimize_scalar_brent does not have a disp option

### ISSUE THREAD

**Issue by perimosocordiae** [scipy/scipy#4582]
The docstring for [_minimize_scalar_brent](https://github.com/scipy/scipy/blob/master/scipy/optimize/optimize.py#L1907) claims to support a `disp` option, but when passed one it raises: `OptimizeWarning: Unknown solver options: disp`.

I'm not sure if there actually is a more verbose mode to toggle here, or if this is simply a documentation error.

**Comment by dlax** [comment]
It's a documentation issue.
