### ISSUE TITLE
sparse.linalg.svds should throw an exception if which not in ['LM', 'SM']

### ISSUE THREAD

**Issue by flaviovdf** [scipy/scipy#4590]
Hi,

Looking into the code for scipy the sparse linear algebra svds, there are two options for the parameter which ('LM', 'SM'). However, I have recently added a bug in my source code by setting which to 'LA' (which is valid in eigsh). 

While this was a lack of attention from my part, it appears that it should be a good practice to throw an exception if the parameter which is not amongst the valid entries. The current code, simple tests:

if which == 'LM':
 ...
else:
 ....

Which in my case lead to computing smallest eigenvalues (the opposite of what I wanted to compute).

**Comment by gmcastil** [comment]
The flaw you are referencing appears to be in the arpack.py module.  Appears fairly straightforward, I'll take a look at it.

**Comment by ev-br** [comment]
Fixed by gh-4620

**Comment by flaviovdf** [comment]
Thank you!
