### ISSUE TITLE
scipy.linalg.block_diag misbehavior with empty array inputs (v0.13.3)

### ISSUE THREAD

**Issue by bskinn** [scipy/scipy#4596]
Apologies if this has been addressed since my SciPy v0.13.3, but inputting empty arrays into `linalg.block_diag` yields nonintuitive outputs (Python v2.7.6):

    >>> scipy.linalg.block_diag([[1,0],[0,1]],[])
    array([[1, 0],
           [0, 1],
           [0, 0]])

    >>> scipy.linalg.block_diag([],[[1,0],[0,1]],[[]])
    array([[ 0.,  0.],
           [ 1.,  0.],
           [ 0.,  1.],
           [ 0.,  0.]])

Progressive assembly of a block-diagonal matrix in a `for` loop, starting from nothing, would be facilitated by a fix here.

**EDIT**, per rgommers's question: I was expecting the following behavior, where an empty matrix contributes no rows or columns to the result:

    >>> scipy.linalg.block_diag([],[[1,0],[0,1]])
    array([[ 1.,  0.],
           [ 0.,  1.]])

I looked at the documentation but was able to find nothing that indicated the design intent of the method in this use case.

**Comment by rgommers** [comment]
Output is still the same for current Scipy master branch

**Comment by rgommers** [comment]
To make sure I understand: did you expect an empty sequence to not add any rows or columns?

**Comment by bskinn** [comment]
It's a minor issue, easily worked around (init to `None` and `if` test to handle the first matrix), but I was expecting to be able to initialize `outmat = []` and then `for submat in mats: outmat = spla.block_diag(outmat, submat)`.

I actually just managed to find again the `reduce` builtin -- had come across it and then forgotten the name -- that might do what I want in a one-liner.

**Comment by levelfour** [comment]
I checked the bug, and I found that the shape of empty matrix like ``np.array([[]])`` returns ``(1,0)``. The original code may be expecting ``(0,0)``. Now the code checks if the given matrix is empty, and if so set shape as ``(0,0)``.

**Comment by bskinn** [comment]
Thanks for the code tweak! That looks good for resolving the misbehavior.

**Comment by rgommers** [comment]
Note: after discussion in gh-4908, the behavior is being changed again in gh-6742
