### ISSUE TITLE
scipy.integrate.nquad should call _OptFunc when called with only a dictionary

### ISSUE THREAD

**Issue by pnjun** [scipy/scipy#4599]
At line 640 of integrate/quadpack.py

```
if isinstance(opts, dict):
opts = [opts] * depth
else:
opts = [opt if callable(opt) else _OptFunc(opt) for opt in opts]
```

`opts = [opts] * depth` should be `opts=[_OptFunc(opts)]*depth`

so that if nquad is called with a dictionary ( instead of a list of dictionaries ) it forms callable list of options.

**Comment by rgommers** [comment]
Hi @pnjun, thanks for the report. Can you supply a code snippet that demonstrates the issue? That helps reproducing it and we can turn it into a regression test?

**Comment by pnjun** [comment]
Unfortunately i deleted the code were i used it, but it was something along the lines of:
```
integrate.nquad(func1, [ [0,R], [0,2*pi], [0,R], [0,2*pi] ], args=(0,0), opts={'epsrel' = 0.0001})
```

**Comment by rgommers** [comment]
OK, thanks @pnjun. 

@BrianNewsom @woodscn any chance one of you can look at this ``nquad`` issue?

**Comment by woodscn** [comment]
I did a quick test, and yep, it looks pretty much exactly like he said. A simple test is 

nquad(lambda x,y:x*y,[[0,1],[0,1]],opts={'epsrel'-0.0001})

This throws a TypeError: 'dict' object is not callable

The fix he proposed should take care of it. I'll see if it's not something more complicated.

**Comment by woodscn** [comment]
I think that should've fixed it in PR #4629. Let me know if there are any issues. 

Thanks @pnjun for the catch!

**Comment by pnjun** [comment]
I'm happy to help =)

**Comment by rgommers** [comment]
Nice, thanks @woodscn
