### ISSUE TITLE
AttributeError: 'module' object has no attribute 'linprog'

### ISSUE THREAD

**Issue by nilswagner** [scipy/scipy#4601]
reading sources... [ 86%] generated/scipy.stats.mstats.kendalltau_seasonareading sources... [ 89%] generated/scipy.stats.rv_continuous.est_loc_scareading sources... [ 90%] generated/scipy.stats.rv_continuous.fit_loc_scareading sources... [ 93%] optimize.linprog-simplex                       
Exception occurred:
  File "/home/nils/git/scipy/doc/source/scipyoptdoc.py", line 62, in _import_object
    obj = getattr(sys.modules[module_name], parts[-1])
AttributeError: 'module' object has no attribute 'linprog'
The full traceback has been saved in /tmp/sphinx-err-Jyz2pk.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
Makefile:120: recipe for target 'latex' failed
make: *** [latex] Error 1

**Comment by pv** [comment]
make clean
