### ISSUE TITLE
cannot import name specfun

### ISSUE THREAD

**Issue by mhamilton723** [scipy/scipy#4602]
When I try to use scikitlearn I encounter the following problem

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-df63d2e4d049> in <module>()
      2 import numpy as np
      3 import matplotlib.pyplot as plt
----> 4 from sklearn.preprocessing import Imputer
      5 import scipy.sparse as sp
      6 from matplotlib.colors import ListedColormap

C:\Anaconda\lib\site-packages\sklearn\preprocessing\__init__.py in <module>()
     22 from .label import MultiLabelBinarizer
     23 
---> 24 from .imputation import Imputer
     25 from ._weights import balance_weights
     26 

C:\Anaconda\lib\site-packages\sklearn\preprocessing\imputation.py in <module>()
      7 import numpy.ma as ma
      8 from scipy import sparse
----> 9 from scipy import stats
     10 
     11 from ..base import BaseEstimator, TransformerMixin

C:\Anaconda\lib\site-packages\scipy\stats\__init__.py in <module>()
    332 from __future__ import division, print_function, absolute_import
    333 
--> 334 from .stats import *
    335 from .distributions import *
    336 from .rv import *

C:\Anaconda\lib\site-packages\scipy\stats\stats.py in <module>()
    179 from scipy.lib.six import callable, string_types
    180 from numpy import array, asarray, ma, zeros, sum
--> 181 import scipy.special as special
    182 import scipy.linalg as linalg
    183 import numpy as np

C:\Anaconda\lib\site-packages\scipy\special\__init__.py in <module>()
    547 
    548 from .basic import *
--> 549 from . import specfun
    550 from . import orthogonal
    551 from .orthogonal import *

ImportError: cannot import name specfun

I have tried updating scipy, scikitlearn, and numpy to the most current version as of 3/5/15  but nothing has helped. Any help would be appreciated. Thanks!

**Comment by rgommers** [comment]
This looks like an issue with how you installed scipy. In the scipy install dir, there should be a file ``specfun.dll`` (or ``specfun.pyd``). so full path for you ``C:\Anaconda\lib\site-packages\scipy\special\specfun.dlll``. Please check if it's there or not. 

Either way, a complete re-install (first cleaning out the install location) should solve the issue.

**Comment by mhamilton723** [comment]
Dear Ralf,

Thank you very much for your help, I have a specfun.pyd but no .dll,
uninstalling and reinstalling with conda has not worked. Is there anywhere
I could download this .dll or perhaps other fixes?

Best,
Mark

**Comment by rgommers** [comment]
If you have a ``.pyd`` then you don't need a ``.dll`` (``.pyd`` is the Python-specific extension for shared libraries on Windows).

If you have that file then I'm not sure what's wrong. Maybe something related to your path (another scipy version somewhere?). Maybe you can try to use a debugger right before where the error occurs to figure out what's going wrong.
