### ISSUE TITLE
Crash in signal.lfilter on nd input with wrong shaped zi

### ISSUE THREAD

**Issue by ewmoore** [scipy/scipy#4612]
```
import numpy as np
from scipy import signal

y, zf = signal.lfilter([1,1], [1.], np.arange(12).reshape((4,3)), 0, [[1]])
```
On Windows 7, python 2.7, scipy 0.15.1 from anaconda64 this crashes.

Running on the same on Linux (python 2.7, scipy 0.15.1, from anaconda64) i get:
```
In [7]: y
Out[7]:
array([[  1.,   1.,   2.],
       [  3.,   5.,   7.],
       [  9.,  11.,  13.],
       [ 15.,  17.,  19.]])

In [8]: zf
Out[8]: array([[ 9.]])
```
Which still seems wrong, shouldn't this fail and complain about a `zi` having the wrong shape? Even if it would take a `(1,1)` shaped `zi` shouldn't the produced `zf` be `(4,1)` in this case?  AFAICT, the handling of initial conditions for multidimensional `x` is not quite right.  For instance, there is also this issue:
```
In [16]: signal.lfilter([1, -1], [1.], np.arange(10).reshape(2,5), 1, [[1],[1],[1],[1]])
Out[16]: 
(array([[ 1.,  1.,  1.,  1.,  1.],
        [ 6.,  1.,  1.,  1.,  1.]]), array([[ -4.00000000e+00],
        [ -9.00000000e+00],
        [  2.52787376e-45],
        [  2.64228486e-58]]))
```
Which gives the same uninitialized junk on both Windows and Linux.  This makes me think the code that does not crash on Linux is just getting lucky and not crashing even though it is still stepping past the array bounds.

**Comment by rgommers** [comment]
that doesn't look good.

    signal.lfilter([1, -1], [1.], np.arange(10).reshape(2,5), 1, [[1],[1],[1],[1]])

segfaults for me on 32-bit linux

**Comment by WarrenWeckesser** [comment]
Looks like the shape of the `zi` argument should be validated before `lfilter` makes the call to `sigtools._linear_filter(b, a, x, axis, zi)`.   For example, if `x` has shape `(m, n, p)` and `axis=1`, then `zi` should have shape `(m, r, p)`, where `r = max(len(a), len(b))-1`.

**Comment by ewmoore** [comment]
Yes, I think that's exactly the problem. I'll have a fix shortly.
