### ISSUE TITLE
Add stats for procrustes

### ISSUE THREAD

**Issue by ElDeveloper** [scipy/scipy#4622]
As per @sturlamolden's [suggestion](https://github.com/scipy/scipy/pull/4540#issuecomment-75690515) in #4540 `scipy.spatial.procrustes` should provide statistical testing:

> Randomization test for p-values and bootstrapping for standard error is the easiest, ...

**Comment by rgommers** [comment]
I don't think we need this, at least it's not high-prio. Closing as we do with many old enhancement requests.
