### ISSUE TITLE
couldn't install scipy  by source code or pip on MacOS 10.10

### ISSUE THREAD

**Issue by yoyohashao** [scipy/scipy#4624]
Dear all,
I feel it's odd that i can install py27-scipy through macports but i never successfully installed scipy through souce code or pip. I thought it would be easy if i install it in anaconda environment but it failed again.

the last lines of my log are ：
‘    don't know how to compile Fortran code on platform 'posix'
    
    building 'dfftpack' library
    
    error: library dfftpack has Fortran sources but no Fortran compiler found
    
    ----------------------------------------
    Command "//anaconda/envs/STAMP/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-RUtlY9/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-D06Mkr-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-RUtlY9/scipy’

any idea is welcome. Thanks

**Comment by matthew-brett** [comment]
I'm guess that Anaconda does not install Fortran for you.

If you were using macports or homebrew or python.org Python, then pip install will install a binary wheel, and you won't need to compile from source.

If you do want to compile from source, you should install a Fortran compiler, it sounds like installing via macports might be the easiest way.

**Comment by yoyohashao** [comment]
Thanks for the reply Matthew. But when I install it via macports:

SEBASTIANs-MacBook-Pro:~ FLFLFLLF$ sudo port install scipy
Password:
Error: Port scipy not found

So what’s the name of scipy in macports? (I already installed py27-scipy via macports, but other softwares are calling for scipy>0.13)

Thanks.

Best,Fang

Fang Liu
PhD Candidate
Rm. 3-410 School of Life Sciences and Biotechnology
Shanghai Jiaotong University
Shanghai,China 200240
https://www.researchgate.net/profile/Fang_Liu37

**Comment by matthew-brett** [comment]
Do you want to install scipy inside Anaconda or inside Macports Python?

If inside Anaconda, I think you want the `conda` command to install scipy, rather than `pip`.

If inside Macports Python, first check that `pip` is the macports pip.  Then install the newest scipy with `pip install -U scipy`.

**Comment by yoyohashao** [comment]
Hi Matthew, I typed pip install -U scipy but again it required Fortran complier. I googled fortran complier but it seemed there were a few complier out there. Do you know how I can install all Fortran compliers at once instead of download&install one by one?
Thanks


Fang Liu
PhD Candidate
Rm. 3-410 School of Life Sciences and Biotechnology
Shanghai Jiaotong University
Shanghai,China 200240
https://www.researchgate.net/profile/Fang_Liu37

**Comment by matthew-brett** [comment]
I suspect that the version of pip that you have is not the macports version, but the Anaconda version, and that is why pip is not picking up the binary wheel but trying to compile from source.

Did you try using 'conda' instead of 'pip'?

**Comment by yoyohashao** [comment]
Hi Matthew, 

Speaking of the pip version,
SEBASTIANs-MacBook-Pro:~ FLFLFLLF$  pip -V
pip 1.5.6 from //anaconda/lib/python2.7/site-packages (python 2.7)
SEBASTIANs-MacBook-Pro:~ FLFLFLLF$ sudo port install py27-pip
--->  Computing dependencies for py27-pip
--->  Cleaning py27-pip
--->  Scanning binaries for linking errors
--->  No broken files found.
SEBASTIANs-MacBook-Pro:~ FLFLFLLF$ pip -V
pip 1.5.6 from //anaconda/lib/python2.7/site-packages (python 2.7)

You were right about it. But after i tried installing via macports, it’s still the anaconda version. What should I do?


Additionally,  I fixed the fortran problem but there’s another problem during Compiling c sources which I just posted in a new issue（https://github.com/scipy/scipy/issues/4625 <https://github.com/scipy/scipy/issues/4625>）. 


Many thanks!
 
Fang Liu
PhD Candidate
Rm. 3-410 School of Life Sciences and Biotechnology
Shanghai Jiaotong University
Shanghai,China 200240
https://www.researchgate.net/profile/Fang_Liu37

**Comment by matthew-brett** [comment]
If you want to work with macports Python, I recommend you take Anaconda off your PATH.  You can do that by editing your `~/.bash_profile` file, removing the line putting Anaconda on your path, saving the file, and then starting a new Terminal window.  You should then get the macpython pip.

**Comment by rgommers** [comment]
<closing the issue because it's a query and not a problem with Scipy - doesn't mean the discussion can't continue>
