### ISSUE TITLE
compling C errors during scipy installation on OS X

### ISSUE THREAD

**Issue by yoyohashao** [scipy/scipy#4625]
Dear all, I started the installation by typing sudo pip install -U scipy, it went well in the beginning untill:

![image](https://cloud.githubusercontent.com/assets/7657231/6612553/6aa74ec8-c8b9-11e4-944e-aa2fdd124652.png)

I have gcc-5.0-bin installed. Can someone tell me what's really wrong and what should I do? Thanks! 

Also I am thinking about wiping out everything related to python and reinstall it because I tend to get troubles from installing python related softwares...I think i will get heart attack if there's a new python problem .....Can someone tell me how to totally clean the python and from which package shall I start? (I couldn't install homebrew due to some unexpected errors and ANACONDA was not the skeleton key)

**Comment by rgommers** [comment]
Did you see scipy.org/install.html and http://scipy.org/scipylib/building/macosx.html?

I would suggest not building from source but using Anaconda (don't know why it doesn't work for you though). If building from source, I would prefer Homebrew. I'm sure it's Gfortran compiler works on OS X 10.10

**Comment by rgommers** [comment]
By the way, never do ``sudo pip``, only ``pip``
