### ISSUE TITLE
Monitoring performance regressions

### ISSUE THREAD

**Issue by pv** [scipy/scipy#4636]
Going through this list may be useful:
https://pv.github.io/scipy-bench/#regressions?sort=3&dir=desc

In particular, some of the changes in scipy.sparse introduced some slowdowns (non-negligible, although non-catastrophic) that may be possible to recover.

**Comment by ev-br** [comment]
Having an rss feed was/is a nice perk. It seems to have been broken at some point: ATM, clicking on a link the feed tries to open links like

http://index.html/#fftpack_basic.Fft.time_fft?commits=d994731cc5ad9bcc4f9ad58da15744b3a2741eb4&idx=6

**Comment by pv** [comment]
This works fine in Thunderbird (or firefox's rss preview), but I think not all rss readers handle relative links correctly.

**Comment by j-bowhay** [comment]
Closing as the link is now out of date so not that useful
