### ISSUE TITLE
mstats.mannwhitneyu and stats.mannwhitneyu return inconsistent pvalues

### ISSUE THREAD

**Issue by pv** [scipy/scipy#4641]
Moved from https://github.com/scipy/scipy.org/issues/89

---

@cshowe

Assuming sample_population and base_population are masked arrays:

mstats.mannwhitneyu(sample_population, base_population)

and

stats.mannwhitneyu(sample_population.compressed(), base_population.compressed())

Return the same mann-whitney statistic but differing p-values.  The pvalue from mstats is twice the pvalue from stats suggesting that the mstats implementation is returning a 2 sided pvalue while the stats implementation returns the 1-sided pvalue - but there's nothing in the scipy documentation to indicate that this is the case.

**Comment by josef-pkt** [comment]
A problem with the `stats` version that hasn't been changed because of backwards compatibility consideration, so far.

Note: The doc string mentions that p-value is one-sided and needs to be multiplied by 2
http://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mannwhitneyu.html

**Comment by pv** [comment]
The mstats docstring doesn't say what is returned, probably it should say that and that it's different from stats

**Comment by josef-pkt** [comment]
Ok, the mstats version need to be made more explicit.

The general pattern is to return 2-sided p-values and the docstrings might not always say so. 
AFAIR, stats.mannwhitneyu is the only exception and returns half of the two-sided p-value.
