### ISSUE TITLE
Bad md5 hash for package - doesn't match the expected hash

### ISSUE THREAD

**Issue by jackiekazil** [scipy/scipy#4658]
$ pip install scipy
Collecting scipy
  Downloading scipy-0.15.1-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (19.0MB)
    90% |############################    | 17.2MB 29kB/s eta 0:01:03  Hash of the package https://pypi.python.org/packages/3.4/s/scipy/scipy-0.15.1-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#md5=d0aaf2da89af160060f1759947457ad6 (from https://pypi.python.org/simple/scipy/) (c2ce80c54490b8daa24ddcc664739744) doesn't match the expected hash d0aaf2da89af160060f1759947457ad6!
  Bad md5 hash for package https://pypi.python.org/packages/3.4/s/scipy/scipy-0.15.1-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#md5=d0aaf2da89af160060f1759947457ad6 (from https://pypi.python.org/simple/scipy/)

**Comment by matthew-brett** [comment]
Works for me - could there be a problem with your connection?

**Comment by pv** [comment]
The md5 hash of the file is correct, so probably there is a problem with your connection.

**Comment by jackiekazil** [comment]
:+1: Good call. I didn't think about that. Ty for the fast reply.
