### ISSUE TITLE
ENH: scipy.io.wavefile.play

### ISSUE THREAD

**Issue by toddrjen** [scipy/scipy#4663]
It would be extremely useful if scipy had a simple, cross-platform function for playing numpy arrays over speakers.  This is a basic function something somewhat lacking in the python ecosystem, compared to, say, Matlab's `wavplay`.  `scipy.io` would be the obvious place for this, although whether it would go in `scipy.io.wavefile` as the title suggests or directly in `scipy.io` is debatable (since it isn't actually a file).

**Comment by WarrenWeckesser** [comment]
I'd say this is out of scope for scipy.  A "simple, cross-platform function for playing numpy arrays over speakers" would be great, but I don't think it belongs in scipy.  I won't close this yet--maybe some other devs feel differently.

**Comment by argriffing** [comment]
I guess it depends on the degree to which scipy is intended to be a Python-themed clone of Matlab.

**Comment by toddrjen** [comment]
If scipy didn't already have the wavefile module, I would agree it is out of place.  However, since that module is present, I think it fits in nicely.  Of course, that is a matter of opinion.

**Comment by rgommers** [comment]
I agree it's out of scope. And I definitely don't think of Scipy as some sort of Matlab clone. ``signal`` is the only package which is really modeled on the Matlab API, and that's mostly historical.

**Comment by rgommers** [comment]
For a package like https://github.com/cournape/talkbox it would be more appropriate.

**Comment by argriffing** [comment]
I've closed this as out of scope for scipy. Here's a python.org wiki link for audio packages https://wiki.python.org/moin/Audio/.
