### ISSUE TITLE
Random normal generator compatible with MATLAB randn

### ISSUE THREAD

**Issue by Felix-neko** [scipy/scipy#4666]
Gentlemen!

I want to port a MATLAB project to Python. In this project random normal (Gaussian) generator is used. In my Python tests I should compare MATLAB and Python results.

I can set fixed random seed in Python and MATLAB scripts, but `numpy.random.normal` and MATLAB `randn` still give different results.

**Cannot we get some other random normal generator to reproduce MATLAB results?**

If it's written in C/C++/FORTRAN, we can even wrap it to Python ourselves, but it should give the same results as MATLAB:

    >> rng(1);
    >> randn(1, 5)
    ans =
       -0.6490    1.1812   -0.7585   -1.1096   -0.8456

**Comment by matthew-brett** [comment]
How about saving the random numbers you need to a `.mat` file from matlab, and having a function `matlab_randn` that feeds them to you on demand?

**Comment by Felix-neko** [comment]
The dumps are rather large and I have to modify the interfaces of my classes to use them instead of a normal generator. Yes, it may be used, but it looks like a real perversion and will slow down the development.

**Comment by pv** [comment]
Matlab afaik uses the ziggurat algorithm for randn. Your easiest option is to implement it yourself.
There is a patch for changing numpy rng to that, https://github.com/numpy/numpy/issues/2047

However, whether using the same algorithm guarantees reproducible results depends on the algorithm (I don't know the details) --- if it relies on floating point operations, the random stream is likely not fully reproducible.

Closing this ticket, this is a numpy issue.

**Comment by ewmoore** [comment]
You're not going to reproduce the random number stream you get from matlab without using matlab.  @matthew-brett's suggestion will probably work if this is just to test your program.
