### ISSUE TITLE
AttributeError: 'module' object has no attribute '_root_anderson_doc'

### ISSUE THREAD

**Issue by nilswagner** [scipy/scipy#4668]
/home/nils/local/lib/python2.7/site-packages/scipy-0.15.1-py2.7-linux-x86_64.egg/scipy/integrate/quadpack.py:352: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  warnings.warn(msg, IntegrationWarning)
reading sources... [ 85%] generated/scipy.stats.mstats.f_value_wilks_lambreading sources... [ 85%] generated/scipy.stats.mstats.kendalltau_seasonareading sources... [ 89%] generated/scipy.stats.rv_continuous.est_loc_scareading sources... [ 89%] generated/scipy.stats.rv_continuous.fit_loc_scareading sources... [ 93%] optimize.root-anderson                         
Exception occurred:
  File "/home/nils/git/scipy/doc/source/scipyoptdoc.py", line 62, in _import_object
    obj = getattr(sys.modules[module_name], parts[-1])
AttributeError: 'module' object has no attribute '_root_anderson_doc'

**Comment by pv** [comment]
You are not building docs against the development version.
