### ISSUE TITLE
Puzzling behaviour in ODE solvers

### ISSUE THREAD

**Issue by Lkgr** [scipy/scipy#4670]
The typical way of using an ODE solver from scipy.integrate.ode would be, according to the doc:
```python
# ...
t_end, dt = 100, 0.01
while r.successful() and r.t < t_end:
   r.integrate( r.t + dt )
   print r.y
```
Following this schema in my script (included at the very end of this post), I get a mostly right end result, that however depends on `dt` in a puzzling way. As a function of `dt` (first column), I get the following results at `t = t_end` (second column):
```
   8.000      22.7823992
   4.000      18.9014660
   2.000      18.9014660
   1.000      18.9014660
   0.500      18.9014660
   0.250      18.9014660
   0.125      18.9014660
   0.120      18.9814415
   0.100      19.0014330
   0.080      18.9814415
   0.040      18.9014660
   0.020      18.9214612
   0.010      18.9014660
```
I find this puzzling because there is no "convergence" with `dt` (as expected), but there is nevertheless an irregular dependance on `dt`. After looking at the documentation of the DOPRI5 Fortran code (the solver used in `ode` to get the above results), I would indeed not expect that the end result depends on `dt`, which is only a way to indicate where you want to output an intermediate solution, and has nothing to do with the numerical step size of the integrator (this step size is entirely managed by the integrator, to yield a solution to a given tolerance). To check this, I downloaded the Fortran DOPRI5 solver, made a small program to perform in Fortran the same computation as the Python script, and got exactly the same end result (18.901482), whatever the interval at which I requested an intermediate solution.

My Python script is the following:
```python
from math import pi, sin, cos
import numpy as np
from scipy.integrate import ode

# physical parameters
L = 100.
e = 0.2
h = 1.1
E = 2.0e5

M  = -0.47833147
Fx = -0.57930329
Fy =  0.03384226

oEI = 12./(E*h*e**3) # 1 / EI

def rhs(s,x,params):
    """ the RHS of the ODE to be integrated
    s is the variable agains which the integration is performed (the curvilinear abscissa)
    x is the vector of [ alpha(s), x(s), y(s) ], i.e., the total rotation, x and y positions
      along the beam
    f is a vector [ M, Fx, Fy ] of the moment/force applied at the end of the beam
    oEI parametrizes the beam's rigidity
    """
    M, Fx, Fy, oEI = params
    return [ ( M - Fx*x[2] + Fy*x[1] )*oEI, 
             cos(x[0]), 
             sin(x[0])     ]
    


def shape(M,Fx,Fy,L,oEI,ds=1.):
    """ that function returns an array which contains the (x(s),y(s)) coordinates
        of points along a beam submitted to a moment M and force Fx, Fy, for
        a beam of length L and "rigidity" oEI. 
    ds designates the curvilinear absissa step between points along the beam
    """
    r = ode(rhs).set_integrator( 'dopri5', rtol=1e-12, atol=1e-12 )
    r.set_initial_value([0., 0., 0.], 0.)
    r.set_f_params( (M,Fx,Fy,oEI) )
    x = [ [0., 0.] ]
    while r.successful() and r.t < L:
        r.integrate(r.t+ds)   
        x.append( r.y[1:] )    
    return np.array(x)

# loop on some "step sizes", and display the corresponding result
for ds in [ 8., 4., 2., 1., 0.5, 0.25, 0.125, 0.12, 0.1, 0.08, 0.04, 0.02, 0.01 ]:
    x = shape( M, Fx, Fy, L, oEI, ds=ds )
    print "{0:8.3f}  {1:14.7f}".format( ds, x[-1,-1]  )
```
I am running Python 2.7.6 on Linux, with scipy 0.13.3 / numpy 1.8.2.

**Comment by pv** [comment]
The final solutions are not all at the same time. Add `print(r.t)` after your while loop, and see the answer.
