### ISSUE TITLE
no such file or directory: dcosqb.c

### ISSUE THREAD

**Issue by sirpercival** [scipy/scipy#4695]
Trying to install scipy via pip or homebrew (both give me the same error) crashes with the above clang error. I'm on Yosemite, trying to install scipy into a virtualenv; I was able to do so before upgrading to Yosemite. Googling led to me uninstalling and reinstalling gcc and libmpc, with no success. Any suggestions?

**Comment by rgommers** [comment]
I've not seen this one before. Can you please put your complete build log in a gist and link to it?

**Comment by rgommers** [comment]
Also, tell us how you installed Python itself, your Fortran compiler, and the output of 

    $ gcc --version
    $ gfortran --version

**Comment by sirpercival** [comment]
Here's the gist: https://gist.github.com/sirpercival/f1e6e56939a79ad5a540

I'm using the version of python included with Kivy. Thanks!

**Comment by rgommers** [comment]
Here's the error:

    f77.sh:f77: scipy/fftpack/src/dfftpack/dcosqb.f     
    /usr/stsci/iraf/iraf/unix/hlib//f77.sh: line 183: /usr/stsci/iraf/iraf/unix/bin.macosx//f2c.e: No such file or directory     
    clang: error: no such file or directory: 'dcosqb.c'
    clang: error: no input files
     
You do have ``gfortran`` installed but also this weird ``f77.sh`` compiler, I've never seen that on OS X:

    Fortran f77 compiler: /usr/stsci/iraf/iraf/unix/hlib//f77.sh -Wall -g -ffixed-form -fno-second-underscore -arch x86_64 -fPIC -O3 -funroll-loops
 
    Fortran f90 compiler: /usr/local/bin/gfortran -Wall -g -fno-second-underscore -arch x86_64 -fPIC -O3 -funroll-loops
 
    Fortran fix compiler: /usr/local/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -arch x86_64 -fPIC -O3 -funroll-loops
 
You need to remove that compiler from your path, so the build starts using ``gfortran`` for Fortran 77 files.
