### ISSUE TITLE
logsumexp with zero scaling factor

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4702]
```python
>>> scipy.misc.logsumexp([-1000])
-1000.0
>>> scipy.misc.logsumexp([-1000, 0], b=[1, 0])
-inf
```

**Comment by maniteja123** [comment]
Could anyone point to the problem faced here. Isn't the output the expected one ?
It matches with the answer of 
 
    >>>a=[-1000,0]
    >>>b=[1,0]
    >>>np.log(np.sum(b*np.exp(a)))
    -inf

**Comment by rgommers** [comment]
This is due to taking the exponent of ``a - max(a)``. So the second element matters (because it's the largest value) even if ``b == 0`` for that element. 

I don't think that this is a bug though. Implementing a special case for ``b == 0`` looks wrong, because ``b`` is expected to be floating point and comparing floating point zero to ``0`` is problematic. Also, the current code is consistent in that the answer is OK when taking the limit of b going to zero from above.

So closing.

**Comment by rgommers** [comment]
@argriffing please reopen if I'm missing your point.

**Comment by argriffing** [comment]
Thanks for the comments. I'm not trying to re-open this issue but I just thought I'd explain the rationale in a bit more detail. Maybe too much detail :) Also I'd thought the original motivation had been from a stackoverflow question but I can't seem to find it.

> Could anyone point to the problem faced here. Isn't the output the expected one ?
It matches with the answer of
> ```
>>>a=[-1000,0]
>>>b=[1,0]
>>>np.log(np.sum(b*np.exp(a)))
-inf
```

One of the purposes of `logsumexp` is to compute the solution more stably than using the naive evaluation.

> This is due to taking the exponent of `a - max(a)`. So the second element matters (because it's the largest value) even if `b == 0` for that element.

Yes this agrees with my understanding of the current implementation in scipy.

> I don't think that this is a bug though.

Right it's not necessarily a bug, just an opportunity to further improve the stability of the evaluation.

> Implementing a special case for `b == 0` looks wrong, because b is expected to be floating point and comparing floating point zero to 0 is problematic.

It is true that exact comparison of floating point numbers is often incorrect. On the other hand, in some cases it makes sense.  For example [`xlogy`](https://github.com/scipy/scipy/blob/maintenance/0.15.x/scipy/special/_xlogy.pxd) uses exact comparison of a floating point coefficient to zero.

> Also, the current code is consistent in that the answer is OK when taking the limit of b going to zero from above.

I'm not completely sure I understand this point, so I'll address two different interpretations.

1) Maybe you mean that `logsumexp([-1000, 0], b=[1, eps])` is OK (in the sense of mathematical correctness) when taking the limit `eps -> 0` from above.  This looks plausible from a plot, but it is not true. For example in the following code the top subplot looks like it is linearly decreasing towards negative infinity as the log of `eps` approaches negative infinity.
``` 
import numpy as np
import matplotlib.pyplot as plt
from scipy.misc import logsumexp
def mkplot(ax, k):
    n = 41
    x1 = np.logspace(-1, -k, num=n)
    x0 = np.ones_like(x1)
    b = np.vstack((x0, x1)).T
    a = np.array([[-k, 0.0]]).repeat(n, axis=0)
    y = logsumexp(a, axis=1, b=b)
    line, = ax.plot(x1, y)
    ax.set_xscale('log')
fig, (ax1, ax2) = plt.subplots(2)
mkplot(ax1, 1000)
mkplot(ax2, 20)
plt.savefig('logsumexp.png')
```
![logsumexp](https://cloud.githubusercontent.com/assets/101416/7350813/77011f34-eccf-11e4-93e2-5d745ad8a41f.png)

But in the bottom subplot (which uses a less numerically taxing value of `a`) you can see that this pattern doesn't hold for the whole domain, and that the limit of the `logsumexp` is finite as `eps -> 0` from above.

2) Maybe you mean that `logsumexp([-1000, 0], b=[1, eps])` is OK when taking the limit of `eps -> 0` from above, in the sense that it is numerically consistent with `logsumexp([-1000, 0], b=[1, 0])` because both give the value `-inf`, and that this consistency is good.

```
>>> logsumexp([-1000.0, 0.0], b=[1.0, np.exp(-740)])
-739.99742066489091
>>> logsumexp([-1000.0, 0.0], b=[1.0, np.exp(-760)])
-inf
>>> logsumexp([-1000.0, 0.0], b=[1.0, 0.0])
-inf
```

The current implementation of the evaluation jumps from about -750 to `-inf` when `eps` becomes smaller than floating point numbers can handle, whereas an alternative implementation would jump from about -750 to the more accurate value of `-1000` when `eps` reaches this threshold. So the alternative implementation would not be less consistent, at least for this example.

**Comment by rgommers** [comment]
Hmm, that is a quite elaborate description of what I meant (I was thinking mostly about 2) and how my interpretation was a bit too fast:)

I'm still not sure if it's worth making a change here, but it's at least worth thinking about it.

**Comment by aarchiba** [comment]
The real selling point is to be able to use b for signs. So normally it's just +1 or -1, but a zero can slip in there, and it shouldn't destroy the precision of all the other values unnecessarily.
