### ISSUE TITLE
scipy 0.15.1 fails to run in solaris 10, "symbol isfinite: referenced symbol not found"

### ISSUE THREAD

**Issue by sergiopasra** [scipy/scipy#4704]
Hello, I'm trying to build latest scipy in solaris 10.

Compiler is GNU gcc 4.9.2. Python is 2.7 from opencsw, Numpy is 1.9.2, successfully compiled and tests passed.

Scipy 0.15.1 compiles, but when I try to run the tests I get the following

$ nosetests-2.7 scipy 

ERROR: Failure: ImportError (ld.so.1: python2.7: fatal: relocation error: file /xxx/scipy-0.15.1/build/lib.solaris-2.10-sun4u.32bit-2.7/scipy/special/_ufuncs.so: symbol isfinite: referenced symbol not found)

The problem seems to be the function isfinite.  Numpy had a similar problem

https://github.com/numpy/numpy/issues/2221

In Solaris 10, isfinite is only defined if the C99 standard is enabled. Python is compiled without it. The file pyconfig.h contains the following:

/* Define to 1 if you have the declaration of `isfinite', and to 0 if you
   don't. */
#define HAVE_DECL_ISFINITE 0

So isfinite is not defined.

If I do nm -gC /xxx/scipy-0.15.1/build/lib.solaris-2.10-sun4u.32bit-2.7/scipy/special/_ufuncs.so I get the following
.... (snip)
000d006c T incob_
000c7048 T incog_
0001bb1c T init_ufuncs
0006d750 T ipmpar_
                 U isfinite
0003c6b8 T it1i0k0_wrap
0003c5ac T it1j0y0_wrap
0003c744 T it2i0k0_wrap
0003c638 T it2j0y0_wrap

So isfinite is undefined, but other related symbols like isnan do not appear.

It seems that scipy/special/cephes/ellik.c uses isfinite, whereas other files in the same directory use npy_isfinite, which is safe

**Comment by ev-br** [comment]
Is this with 0.15.1 or master? These lines have been touched a couple of weeks ago in https://github.com/scipy/scipy/commit/8c2b29bb2896a5da858e5baf1cf334c6aad83d39

**Comment by pv** [comment]
isfinite is not part of C89, and solaris seems obsolete enough to not
have it even as an extension. The master branch switches to the numpy
functions in that case.

**Comment by sergiopasra** [comment]
This is 0.15.1, I will check master to see if it works

**Comment by sergiopasra** [comment]
I confirm that master works.  I'm going to check if 0.15.1 with isfinite change to np_isfinite works

**Comment by sergiopasra** [comment]
If I change isfinite by npy_isfinite in scipy/special/cephes/ellik.c, then scipy 015.1 works

**Comment by ewmoore** [comment]
I guess if we do a 0.15.2 this should go in as well.

**Comment by sergiopasra** [comment]
@ewmoore That would be awesome!

**Comment by rgommers** [comment]
(no 0.15.2, so removing backport-candidate label)

**Comment by pv** [comment]
Confirmed fixed, closing.
