### ISSUE TITLE
kmeans k_or_guess parameter error if guess is not square array

### ISSUE THREAD

**Issue by imtibbet** [scipy/scipy#4705]
The kmeans method in [vq.py](https://github.com/scipy/scipy/blob/2d1bd60e0330bb07880f8eab717e21ee17422245/scipy/cluster/vq.py) has a parameter k_or_guess, which is described as:
```
def kmeans(obs, k_or_guess, iter=20, thresh=1e-5):
...
k_or_guess : int or ndarray
The number of centroids to generate. A code is assigned to
each centroid, which is also the row index of the centroid
in the code_book matrix generated.

The initial k centroids are chosen by randomly selecting
observations from the observation matrix. Alternatively,
passing a k by N array specifies the initial k centroids.
```
When the parameter is not a square ndarray an error is raised:
```
  File "/home/imtibbet/Documents/CS251/src/analysis.py", line 139, in kmeans_numpy
    codebook, bookerror = vq.kmeans(W, K)
  File "/usr/lib64/python2.7/site-packages/scipy/cluster/vq.py", line 501, in kmeans
    result = _kmeans(obs, guess, thresh = thresh)
  File "/usr/lib64/python2.7/site-packages/scipy/cluster/vq.py", line 388, in _kmeans
    obs_code, distort = vq(obs, code_book)
  File "/usr/lib64/python2.7/site-packages/scipy/cluster/vq.py", line 201, in vq
    results = py_vq(obs, code_book)
  File "/usr/lib64/python2.7/site-packages/scipy/cluster/vq.py", line 261, in py_vq
    dist = np.sum((obs[i] - code_book) ** 2, 1)
  File "/usr/lib64/python2.7/site-packages/numpy/matrixlib/defmatrix.py", line 354, in __pow__
    return matrix_power(self, other)
  File "/usr/lib64/python2.7/site-packages/numpy/matrixlib/defmatrix.py", line 171, in matrix_power
    raise ValueError("input must be a square array")
ValueError: input must be a square array
```
Would this be fixable by changing **2 to np.square? Also I think that this parameter should be allowed to be a numpy matrix, which would involve changing the test:
```
if type(k_or_guess) == type(array([])):
```

**Comment by argriffing** [comment]
I think the function should be modified to check or convert the arguments that are documented as type `ndarray`.  The underlying issue is that `np.matrix` cannot generally be [substituted](http://en.wikipedia.org/wiki/Liskov_substitution_principle) for `np.ndarray`, and scipy does not have systematic tests for `np.matrix` inputs.

**Comment by imtibbet** [comment]
What about the squaring?

Also that is a good idea, so instead of the current:
```python
if type(k_or_guess) == type(array([])):
...ndarray stuff...
else:
...int stuff...
```
It should be:
```python
if type(k_or_guess) == type(int):
...int stuff...
else:
k_or_guess = np.asarray(k_or_guess)
...ndarray stuff...
```
Is that right?

**Comment by argriffing** [comment]
> What about the squaring?

The squaring issue is a result of the `np.matrix` mess.  If `M` is a `np.matrix` then `M ** 2` is the matrix square, in the sense of the [matrix multiplication](http://en.wikipedia.org/wiki/Matrix_multiplication) of the matrix `M` with itself.  If `M` is a `np.ndarray` then `M ** 2` is the entrywise square, so like the [hadamard product](http://en.wikipedia.org/wiki/Hadamard_product_(matrices)) of the matrix `M` with itself.  Note that the matrix product `M * M` requires `M` to be a [square matrix](http://en.wikipedia.org/wiki/Square_matrix) whereas the hadamard product `M * M` does not have this requirement.  This distinction is the source of the error message that you've reported.

```python
>>> np.array([[1, 1], [1, 1]]) ** 2
array([[1, 1],
       [1, 1]])
>>> np.matrix([[1, 1], [1, 1]]) ** 2
matrix([[2, 2],
        [2, 2]])
>>> 
>>> np.array([[1, 1, 1], [1, 1, 1]]) ** 2
array([[1, 1, 1],
       [1, 1, 1]])
>>> np.matrix([[1, 1, 1], [1, 1, 1]]) ** 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/numpy/matrixlib/defmatrix.py", line 356, in __pow__
    return matrix_power(self, other)
  File "/numpy/matrixlib/defmatrix.py", line 173, in matrix_power
    raise ValueError("input must be a square array")
ValueError: input must be a square array
```

So the problem you are having is a combination of numpy design quirks/mistakes, a mistake that you've made (passing arguments that technically have a different type than the type documented in the function's docstring), and a lack of defensive programming in the scipy implementation of vq.  I'm working on a scipy patch...

**Comment by imtibbet** [comment]
I understand now, thank you for the explanation. I would also like to point out that the matrix math will also occur if the W parameter is a matrix, even if the k_or_guess is an ndarray. It looks like you have it under control though, thanks so much for your help!

**Comment by argriffing** [comment]
@imtibbet This should now be fixed in https://github.com/scipy/scipy/pull/4707 which has been merged.

**Comment by rgommers** [comment]
fixed, so closing.
