### ISSUE TITLE
Cannot generate random variates from noncentral chi-square distribution with dof less than 1

### ISSUE THREAD

**Issue by xiaoweiz** [scipy/scipy#4720]
I'm using scipy 0.15.1

The random variate generation function of the noncentral chi-square distribution yields error when the parameter _degree of freedom_ (dof)  is less than or equal to 1. For example, 

```python 
import scipy.stats as stats
df = 1.0
nc = 4
stats.ncx2.rvs(df, nc)


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-55-6be68a9d384a> in <module>()
----> 1 stats.ncx2.rvs(1.0, nc, loc=0, scale=1, size=1)

/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.pyc in rvs(self, *args, **kwds)
    833             return loc*ones(size, 'd')
    834 
--> 835         vals = self._rvs(*args)
    836         if self._size is not None:
    837             vals = reshape(vals, size)

/Users/zhangxiaowei/anaconda/lib/python2.7/site-packages/scipy/stats/_continuous_distns.pyc in _rvs(self, df, nc)
   2931     """
   2932     def _rvs(self, df, nc):
-> 2933         return mtrand.noncentral_chisquare(df, nc, self._size)
   2934 
   2935     def _logpdf(self, x, df, nc):

mtrand.pyx in mtrand.RandomState.noncentral_chisquare (numpy/random/mtrand/mtrand.c:15618)()

ValueError: df <= 0
```

A common implementation of the noncentral chi-square random variate generation differs depending on whether the dof is greater than 1 or not. In particular, suppose we want to generate a noncentral chi-square with dof _d_ and noncentrality parameter _v_. 

1. If _d_ is greater than 1, then it can be generated by 
```python
import numpy as np
np.random.chisquare(d-1) + (np.random.standard_normal()+np.sqrt(v))**2
```

2. Otherwise, it can be generated by 
```python
import numpy as np
np.random.chisquare(d + 2*np.random.poisson(v/2.0))
```

I suspect that scipy only implements the first case and ignores the other.

**Comment by xiaoweiz** [comment]
Just found out that scipy uses the implmentation in numpy, which has documented [here](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.noncentral_chisquare.html#numpy.random.noncentral_chisquare) that it only considers the case where degree of freedom greater than 1.

**Comment by rgommers** [comment]
The numpy docstring says ``>=1``, so ``df=1`` shouldn't give an error. Plus ``ValueError: df <= 0`` is a weird error. Can you open a numpy issue for that?

**Comment by rgommers** [comment]
At the end of your message you suggest a possible improvement for ``stats.ncx2.rvs``. Needs deciding on, do we want to do this in ``stats.ncx2`` or should we only consider it if ``np.random.noncentral_chisquare`` gets this enhancement?

**Comment by xiaoweiz** [comment]
The fact that `df=1` raises error may be because the algorithm implemented is the one I suggested above: in this case, it needs to generate a chi-square random variate with `df=0`, which is not well defined in mathematics

**Comment by ev-br** [comment]
I guess the best course of action is to add it to numpy.random and then bundle the compatibity fix  to scipy.stats.ncx2 until it can use the numpy version where it's implemented.

**Comment by ev-br** [comment]
https://github.com/numpy/numpy/pull/5800 merged for numpy 1.10; I don't see a reason to not add it to `stats.ncx2`. @xiaoweiz @behzadnouri

**Comment by xiaoweiz** [comment]
Agree. It should also be an easy fix in `scipy`.

**Comment by ev-br** [comment]
Am adding an easy-fix label then.

**Comment by maniteja123** [comment]
Hi, I just saw this issue. It seems that the code doesn't break for df>0 now and the PR is merged for numpy 1.10. Should the scipy code be changed now or is it just a documentation issue for scipy now since it automatically calls ``np.random.noncentral_chisquare`` which handles the issue.

**Comment by xiaoweiz** [comment]
agree. This can be closed now.

**Comment by maniteja123** [comment]
Thanks for clarifying :)
