### ISSUE TITLE
Feature Request: MDCT and IMDCT

### ISSUE THREAD

**Issue by nils-werner** [scipy/scipy#4723]
[MDCT (DCT type 4)](https://en.wikipedia.org/wiki/Modified_discrete_cosine_transform) is really important for audio compression research but is missing from SciPy. I started looking into fftpack but... oh my, that code is currently way beyond my comprehension.

So I am for now simply putting it out there: It would be really great to have DCT type 4 and MDCT in SciPy.

**Comment by nils-werner** [comment]
OK, I've found and implemented a solution that calculates the MDCT and DCT using an FFT and some twiddling and would be willing to contribute it to scipy. Does code like that qualify to be taken into SciPy and scipy.fftpack?

**Comment by rgommers** [comment]
I can't really judge the MDCT part, but it looks to me like ``dct4`` should be implemented similarly to ``dct1, dct2, dct3`` given how similar they are.

**Comment by rgommers** [comment]
Can you link to your code?

**Comment by nils-werner** [comment]
https://gist.github.com/nils-werner/0e3e9e4a877ad8cccf84

**Comment by nils-werner** [comment]
How that we will get a DCT-IV soon, here is a simple MDCT implementation that makes use of it:

```
import numpy as np
import scipy.fftpack
import scipy.signal
import skimage


def mdct(x, axis=-1):
    x = x.copy()
    idx_to = [slice(None)] * x.ndim
    idx_from = [slice(None)] * x.ndim

    # Fold left quarter in
    idx_to[axis] = slice(x.shape[axis] // 4, x.shape[axis] // 2)
    idx_from[axis] = slice(x.shape[axis] // 4 - 1, None, -1)
    x[tuple(idx_to)] += x[tuple(idx_from)]

    # Fold right quarter in
    idx_to[axis] = slice(x.shape[axis] // 2, 3 * x.shape[axis] // 4)
    idx_from[axis] = slice(None, 3 * x.shape[axis] // 4 - 1, -1)
    x[tuple(idx_to)] -= x[tuple(idx_from)]

    idx_to[axis] = slice(x.shape[axis] // 4, 3 * x.shape[axis] // 4)
    x = x[tuple(idx_to)]

    return scipy.fftpack.dct(x, type=4, axis=axis, norm='ortho')


def imdct(x, axis=-1):
    x = scipy.fftpack.idct(x, type=4, axis=axis, norm='ortho')

    idx_prefix = [slice(None)] * x.ndim
    idx_suffix = [slice(None)] * x.ndim

    # Duplicate left and right halves out, inverse of folding in
    idx_prefix[axis] = slice(x.shape[axis] // 2 - 1, None, -1)
    idx_suffix[axis] = slice(None, x.shape[axis] // 2 - 1, -1)

    return np.concatenate((x[tuple(idx_prefix)], x, -x[tuple(idx_suffix)]), axis=axis)


x = np.random.rand(8 * 32)

# Create overlapping windows of signal. Careful, they are views!
lapped_x = skimage.util.view_as_windows(x, window_shape=64, step=32).squeeze().copy()
lapped_x *= scipy.signal.windows.cosine(64)

spectrum = mdct(lapped_x)
aliased_x = imdct(spectrum)

aliased_x *= scipy.signal.windows.cosine(64)
# Overlap add
out = aliased_x[:-1, 32:] + aliased_x[1:, :32]

# First and last half-frame are discarded, as they would contain uncancellable aliasing
np.allclose(out.ravel(), x[32:-32])  # True
```

**Comment by endolith** [comment]
Am I missing something? transforms.py seems to define the same functions as mdct.py?

**Comment by endolith** [comment]
Ah, DCT Type IV was added in https://github.com/scipy/scipy/pull/8899

**Comment by rgommers** [comment]
We have DCT type 4. A PR for adding MDCT to `signal` is welcome I'd say. No need to keep this enhancement request open though. Thanks all.
