### ISSUE TITLE
GenGamma _munp function fails due to overflow

### ISSUE THREAD

**Issue by ldamewood** [scipy/scipy#4724]
There's a part of the gengamma distribution code that divides two gamma functions. As a result, The mean of the distribution is `nan` for values of `a` > ~170.
```
from scipy import special
import numpy as np
n = -2
a = 200
c = 1.
# Calcuate the mean (gives nan)
print(scipy.stats.distributions.gengamma(a, n, scale=c).mean())
# Function used in _munp (gives nan)
print(special.gamma(a+n*1.0/c) / special.gamma(a))
# Possible fix for large argument values? (gives correct answer)
print(np.exp(special.gammaln(a+n*1.0/c) - special.gammaln(a)))
```

Perhaps this in `scipy/stats/_continuous_distns.py:2041`?
```
    def _munp(self, n, a, c):
        if a > 170 or a+n*1.0/c > 170:
            return np.exp(gamln(a+n*1.0/c) - gamln(a))
        return special.gamma(a+n*1.0/c) / special.gamma(a)
```
But I am unsure if this catches *all* edge cases including positive/negative large/small values of `n` and `c`.

**Comment by josef-pkt** [comment]
The `if` condition will not work because it needs to work for arrays, a, n, c could be arrays 

I think for munp we could just unconditionally use gammaln. We switched to using it at several other places also because of the higher precision.  (in some cases the function can be replaced by special beta, but it doesn't look like that's the case here.)

PR welcome  (with the example as unit test)

**Comment by ewmoore** [comment]
`special.poch(z, m) =  gamma(z + m) / gamma(z)` would also work.

**Comment by argriffing** [comment]
I tried to make a `poch` patch, but the build failed due to https://github.com/scipy/scipy/issues/4719.

**Comment by ewmoore** [comment]
@argriffing, how are you running the build?  I cannot get #4719 to trigger here.

**Comment by ldamewood** [comment]
Good call about the arguments being arrays. `poch` works for me and passes all tests.

**Comment by argriffing** [comment]
@ewmoore  I just ran `runtests.py` after making the `poch` patch on top of scipy master.  It gave the error even after having deleted the build directory.

**Comment by argriffing** [comment]
@ewmoore scipy is just broken for me even on master branch due to that issue.  To reproduce it have you tried using a new numpy?  This could explain why it does not trigger on TravisCI but triggers for me and for the person who reported it.
