### ISSUE TITLE
scipy.interpolate.interp2d has unexpected behavior with Nan values

### ISSUE THREAD

**Issue by mhearne-usgs** [scipy/scipy#4730]
I'm seeing what I would consider to be unexpected behavior from the scipy interpolate.interp2d function when there are NaN values in the input array.  The code snippet below should demonstrate the problem I'm seeing, namely that the interpolated grid has NaN values in all the rows above my little corner of NaN values in the input grid.  Questions:

1) Is this the intended behavior?  If so, why?
2) How can I achieve the results that would be more consistent between rows and columns?

import numpy as np
from scipy import interpolate

nrows = 4
ncols = 4
z = np.arange(0,nrows*ncols,dtype=np.float).reshape((nrows,ncols))
z[-2][0] = np.nan
z[-1][0] = np.nan
z[-2][1] = np.nan
z[-1][1] = np.nan
print z
print
x = np.arange(0,ncols)
y = np.arange(0,nrows)
xi = np.arange(0.5,ncols-1,1.0)
yi = np.arange(0.5,nrows-1,1.0)
f = interpolate.interp2d(x,y,z,kind='linear')
zi = f(xi,yi) #interpolate at the points in between values
print zi 

This returns:

[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [ nan  nan  10.  11.]
 [ nan  nan  14.  15.]]

[[  nan   nan   4.5]
 [  nan   nan   8.5]
 [  nan   nan  12.5]]

Why don't I get:
[[  2.5   3.5   4.5]
 [  nan   nan   8.5]
 [  nan   nan  12.5]]

**Comment by mhearne-usgs** [comment]
Ok, this gets even weirder.  Depending on which corner you fill in with NaN values, you get very different results.  Here are the three other options:

########### Option 2: NaN's in upper right corner############
nrows = 4
ncols = 4
z = np.arange(0,nrows*ncols,dtype=np.float).reshape((nrows,ncols))
z[0][-2] = np.nan
z[0][-1] = np.nan
z[1][-2] = np.nan
z[1][-1] = np.nan
print z
print
x = np.arange(0,ncols)
y = np.arange(0,nrows)
xi = np.arange(0.5,ncols-1,1.0)
yi = np.arange(0.5,nrows-1,1.0)
f = interpolate.interp2d(x,y,z,kind='linear')
zi = f(xi,yi) #interpolate at the points in between values
print zi
####################################################

########### Option 3: NaN's in upper left corner############
nrows = 4
ncols = 4
z = np.arange(0,nrows*ncols,dtype=np.float).reshape((nrows,ncols))
z[0][0] = np.nan
z[0][1] = np.nan
z[1][0] = np.nan
z[1][1] = np.nan
print z
print
x = np.arange(0,ncols)
y = np.arange(0,nrows)
xi = np.arange(0.5,ncols-1,1.0)
yi = np.arange(0.5,nrows-1,1.0)
f = interpolate.interp2d(x,y,z,kind='linear')
zi = f(xi,yi) #interpolate at the points in between values
print zi
####################################################

########### Option 3: NaN's in lower right corner############
nrows = 4
ncols = 4
z = np.arange(0,nrows*ncols,dtype=np.float).reshape((nrows,ncols))
z[-2][-2] = np.nan
z[-2][-1] = np.nan
z[-1][-2] = np.nan
z[-1][-1] = np.nan
print z
print
x = np.arange(0,ncols)
y = np.arange(0,nrows)
xi = np.arange(0.5,ncols-1,1.0)
yi = np.arange(0.5,nrows-1,1.0)
f = interpolate.interp2d(x,y,z,kind='linear')
zi = f(xi,yi) #interpolate at the points in between values
print zi
####################################################

**Comment by pv** [comment]
There's no NaN handling in the code. The behavior is undefined if they
are present.

**Comment by mhearne-usgs** [comment]
Ok, so in the short term I think I would at least recommend noting the NaN behavior in the documentation.

In the medium to long term, I suggest that supporting NaN values in interpolation would be a good thing.  
There are at least 2 packages that handle NaN for the same kind of function:

http://www.mathworks.com/help/matlab/ref/interp2.html 

http://gmt.soest.hawaii.edu/doc/5.1.1/grdsample.html

Operating on the principle of least surprise, I think we would like to impress (or at least not disappoint) users coming from other communities.

I did figure out that I can use interpolate.griddata() as a workaround, although it is roughly 2 orders of magnitude slower.  Here's what that looks like:

z = np.arange(0,16,dtype=np.float).reshape((4,4))
z[-2][0] = np.nan
z[-1][0] = np.nan
z[-2][1] = np.nan
z[-1][1] = np.nan
print z
x,y = np.meshgrid(np.arange(0,4),np.arange(0,4))
print x
print
print y
z = z.flatten()
points = np.zeros((16,2))
points[:,0] = x.flatten()
points[:,1] = y.flatten()
xi = np.arange(0.5,3.0,1.0)
yi = np.arange(0.5,3.0,1.0)
xi,yi = np.meshgrid(xi,yi)
xi = xi.flatten()
yi = yi.flatten()
xnew = np.zeros((len(xi),2))
xnew[:,0] = xi
xnew[:,1] = yi
zi = interpolate.griddata(points, z, xnew, method='linear')
print zi.reshape((3,3))

**Comment by rgommers** [comment]
Marking this as easy-fix task (to add note to docstring that ``interp2d`` doesn't do NaN handling). When this is done, also needs to be done for related functions in ``interpolate``.

**Comment by ev-br** [comment]
Documentation has been updated in gh-6475, so closing. Thanks @smopucilowski , all.
