### ISSUE TITLE
optimize.brute finish option is not compatible with optimize.minimize

### ISSUE THREAD

**Issue by mangecoeur** [scipy/scipy#4733]
`optimize.brute`has the `finish` option to allow you to use a local optimizer to "polish" the final result. The doc suggest `fmin`. However if you want to use the (more general) `minimize` function it doesn't work.

Firstly, the KW option `full_output` is passed which isn't supported, while the option `disp` is passed which is supported by `minimize` but only with a dictionary given to the `options` kwarg (i.e. `options={'disp': disp}`)

Secondly, `brute` doesn't understand the `OptimizeResult` object returned and so crashes.

Since `minimize` is promoted in the docs as the more general function to use over variations of `fmin` it would make sense for `brute` to support using `minimize` for the `finish` option.

**Comment by rgommers** [comment]
That sounds reasonable. Thanks for the suggestion @mangecoeur

**Comment by rgommers** [comment]
PR welcome if someone wants to tackle this.
