### ISSUE TITLE
qr_update bug or incompatibility with numpy 1.10?

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4736]
This reproduces one of the problems mentioned in https://github.com/scipy/scipy/pull/4729.

```python
import numpy as np
import scipy
import scipy.linalg

print 'numpy version', np.__version__
print 'scipy version', scipy.__version__

np.random.seed(1234)
shape = (2, 3)

a = np.random.random(shape)
q, r = scipy.linalg.qr(a)

u = np.random.random((q.shape[0], 1))
v = np.random.random((r.shape[1], 1))

q1, r1 = scipy.linalg.qr_update(q, r, u, v, False)
```

```
numpy version 1.10.0.dev0+8b6effa
scipy version 0.16.0.dev0+b259eaa
Exception ValueError: 'On entry to DGEMM parameter number 10 had an illegal value' in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
```

__Edit__: simplified example

**Comment by rgommers** [comment]
Works fine with numpy 1.9.1. Also maybe relevant: the 1.10-dev build & test on TravisCI was the only config with relaxes strides checking set to true - need to check if with false it still segfaults.

**Comment by argriffing** [comment]
> the 1.10-dev build & test on TravisCI was the only config with relaxes strides checking set to true - need to check if with false it still segfaults.

This is what I'd suspected as well -- until I remembered that this has been added to the travis config in https://github.com/scipy/scipy/pull/4226.  But just now I checked the [travis build](https://travis-ci.org/scipy/scipy/jobs/57391909) to see if it is actually enabled, and for some reason it seems to not be.  I'm not sure what's going on with that.

```
$ python -c 'import numpy as np; print("relaxed strides checking:", np.ones((10,1),order="C").flags.f_contiguous)'
('relaxed strides checking:', False)
```

So now my guess is that `update_qr` is broken for relaxed strides checking and that the TravisCI config for relaxed strides doesn't actually build numpy with that flag.

**Comment by ewmoore** [comment]
I know what the problem is.  I missed this since I thought we had those tests on Travis.

I won't, however, have time to fix this until the first week of May. If this is going to result in master being broken until then, we ought to revert that merge.  The problem this is demonstrating is in _form_qTu if someone else wants to look at it before then.

**Comment by rgommers** [comment]
Let's give it a few days, would be a shame to have to revert it. Any more hints?

**Comment by ewmoore** [comment]
The easiest fix is probably to detect that the second dimension has length 1 and then squeeze that dimension out.  Starting at [line 2241 in _decomp_update.pyx.in](https://github.com/scipy/scipy/blob/master/scipy/linalg/_decomp_update.pyx.in#L1262) maybe change this: 
```
if u1.ndim == 2 and u1.shape[1] != v1.shape[1]:
    raise ValueError('Second dimension of u and v must be the same')
```
to something like this:
```
if u1.ndim == 2:
    if  u1.shape[1] != v1.shape[1]:
        raise ValueError('Second dimension of u and v must be the same')
    elif u1.shape[1] == 1;
        u1 = np.squeeze(u1)
        v1 = np.squeeze(u1)
```
This ought to fix this particular failure in `qr_update`.  It's possible that `qr_insert` has a similar issue, but squeezing out singleton dimensions would work there as well.

The trickier issue is ensuring that everything still works if `q` is `(N,1)` or `r` is `(1,N)`.  My first though here might be to patch the strides to something reasonable in `extract`, but I haven't really thought this through.

I don't recall off hand if there is a test for `(1,1)` shaped `q` and `r`, since this probably has similar issues in all three functions.  The easiest thing for this is probably to special case it.  

These last two cases should probably have tests even if they don't cause failures right now.

**Comment by argriffing** [comment]
By the way, it seems weird that the exception is printed to stderr when the script finishes, instead of being raised as a normal Python Exception.  Does this mean that exceptions could be treated more carefully in the cython blas/lapack wrappers or is this expected?

`Exception ValueError: 'On entry to DGEMM parameter number 10 had an illegal value' in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored`

**Comment by ewmoore** [comment]
There isn't anything we can really do about that. That error message comes
directly from the blas library.  If you look for xerbla discussions, you
can find some stuff that attempts to, on Linux, convert that to a python
exception. But it isn't  cross platform and doesn't always work.

**Comment by rgommers** [comment]
On 32-bit linux I haven't been able to reproduce a segfault; on OS X it's a different one:

    test_decomp_update.TestQRupdate_D.test_fat_rank_p ... ldb must be >= MAX(K,1):
    ldb=-1 K=7ldc must be >= MAX(M,1): ldc=-1 M=7BLAS error: Parameter number 11
    passed to cblas_zgemm had an invalid value

**Comment by rgommers** [comment]
The line 2241 change gets me past that segfault, the next one is indeed in ``form_qTu``:

    test_decomp_update.test_form_qTu('C', 'F', 3, 'f') ... Segmentation fault: 11

**Comment by rgommers** [comment]
And if I then run only the fast tests:
 
    .Python(3082,0x7fff7f3b2300) malloc: *** error for object 0x7fd03af46a88: incorrect
    checksum for freed object - object was probably modified after being freed.
    *** set a breakpoint in malloc_error_break to debug
    Abort trap: 6

**Comment by rgommers** [comment]
Rebuilding numpy and scipy.linalg with ``NPY_RELAXED_STRIDES_CHECKING=0`` fixed something (no segfaults in ``test_decomp_update`` fast tests at least once), still one for slow tests:

    test_decomp_update.TestQRupdate_D.test_neg_strides_economic_rank_1 ... 
    Python(5395,0x7fff7f3b2300) malloc: *** error for object 0x7fc403899938: incorrect
    checksum for freed object - object was probably modified after being freed.
    *** set a breakpoint in malloc_error_break to debug
    Abort trap: 6

For fast tests I then also see this one:

    test_gelss (test_lapack.TestLeastSquaresSolvers) ... Python(5431,0x7fff7f3b2300) malloc: 
    *** error for object 0x7f82db9dbb28: incorrect checksum for freed object - object was 
    probably modified after being freed.
    *** set a breakpoint in malloc_error_break to debug
    Abort trap: 6

**Comment by argriffing** [comment]
> There isn't anything we can really do about that. That error message comes
directly from the blas library.  If you look for xerbla discussions, you
can find some stuff that attempts to, on Linux, convert that to a python
exception. But it isn't  cross platform and doesn't always work.

To me this looks like it has been successfully converted to a python exception (maybe within `lapack_lite/python_xerbla.c`?  Is there a way to know?) but that this has been ignored by some other mechanism (maybe like the one described by the warning box in https://docs.python.org/2/reference/datamodel.html#object.__del__?).  Or should some of the cython functions in `_decomp_update.pyx.in` have exception annotation like http://docs.cython.org/src/userguide/language_basics.html#error-return-values?

**Comment by pv** [comment]
Code in Scipy should be constructed so that lapack errors from xerbla
are never triggered --- depending on compiler/library configuration,
xerbla can just abort the program. (I.e. the question where the stderr
print comes from is sort of moot, as it should be considered equivalent
to crashing the program.)

**Comment by argriffing** [comment]
> I.e. the question where the stderr print comes from is sort of moot, as it should be considered equivalent to crashing the program.

Yes, I was thinking it would be cool to get a traceback if possible, or to abort with a non-zero exit status if possible.  Even if there are some BLAS implementations that just print the error and abort, it would be helpful to not ignore the exceptions from friendlier implementations, especially if it would only require adding something like `except -1` to a cython function declaration.

**Comment by insertinterestingnamehere** [comment]
It's surprising that there is a Python error at all. I would have expected the lapack and blas linked via numpy distutils to use the implementation of xerbla that comes linked as a part of the original BLAS library. I have no idea why the different xerbla is getting called though.

As to adding an except statement in Cython, the proper declaration would be `except *`, and that is known to slow things down as per [the Cython docs](http://docs.cython.org/src/quickstart/cythonize.html#typing-functions). IMHO, it would be much better to link against an xerbla that doesn't raise a Python error at all than having Cython call `PyErr_Occurred` after every call to a BLAS or LAPACK routine. Aside from the overhead of adding all the extra function calls, wouldn't the error checking interfere with calling these routines inside a nogil block? AFAICT calling `PyErr_Occurred` requires the GIL.

**Comment by argriffing** [comment]
> Aside from the overhead of adding all the extra function calls, wouldn't the error checking interfere with calling these routines inside a nogil block? AFAICT calling PyErr_Occurred requires the GIL.

I found a cython PR https://github.com/cython/cython/pull/56 "Acquire the GIL to build the traceback in nogil functions" which sounds like it's trying to avoid or reduce this interference.

**Comment by pv** [comment]
Behavior of xerbla is undefined, so we should not assume anything about it, just ensure such error conditions donot occur.

-------- Alkuperäinen viesti --------
Lähettäjä: Ian Henriksen <notifications@github.com> 
Päivämäärä: 15.04.2015  22.24  (GMT+02:00) 
Saaja: scipy/scipy <scipy@noreply.github.com> 
Kopio: Pauli Virtanen <pav@iki.fi> 
Aihe: Re: [scipy] qr_update bug or incompatibility with numpy 1.10? (#4736) 

It's surprising that there is a Python error at all. I would have expected the lapack and blas linked via numpy distutils to use the implementation of xerbla that comes linked as a part of the original BLAS library. I have no idea why the different xerbla is getting called though.

As to adding an except statement in Cython, the proper declaration would be except *, and that is known to slow things down as per the Cython docs. IMHO, it would be much better to link against an xerbla that doesn't raise a Python error at all than having Cython call PyErr_Occurred after every call to a BLAS or LAPACK routine. Aside from the overhead of adding all the extra function calls, wouldn't the error checking interfere with calling these routines inside a nogil block? AFAICT calling PyErr_Occurred requires the GIL.

**Comment by pv** [comment]
The technical issue here is that python_xerbla was intended only for numpy.linalg, but the symbol leaks out of the shared library inadvertently. It may be possible to avoid this with suitable declarations.

-------- Alkuperäinen viesti --------
Lähettäjä: argriffing <notifications@github.com> 
Päivämäärä: 15.04.2015  23.19  (GMT+02:00) 
Saaja: scipy/scipy <scipy@noreply.github.com> 
Kopio: Pauli Virtanen <pav@iki.fi> 
Aihe: Re: [scipy] qr_update bug or incompatibility with numpy 1.10? (#4736) 

Aside from the overhead of adding all the extra function calls, wouldn't the error checking interfere with calling these routines inside a nogil block? AFAICT calling PyErr_Occurred requires the GIL.

I found a cython PR cython/cython#56 "Acquire the GIL to build the traceback in nogil functions" which sounds like it's trying to avoid or reduce this interference.
