### ISSUE TITLE
the TravisCI config with the numpy relaxed strides flag seems to be broken.

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4737]
This config was added in https://github.com/scipy/scipy/pull/4226 which worked https://travis-ci.org/scipy/scipy/jobs/42922494, but it didn't last long.  See https://github.com/scipy/scipy/pull/4261 https://travis-ci.org/scipy/scipy/jobs/43901091.  It appears to not actually build numpy (7 seconds vs. 168 seconds for the pip install), thereby ignoring the relaxed strides build flag and reporting ('relaxed strides checking:', False).

**Comment by argriffing** [comment]
I think the issue is that the TravisCI environment has changed so that numpy is now preinstalled http://docs.travis-ci.com/user/ci-environment/#Python-VM-images.

**Comment by matthew-brett** [comment]
On dipy - for example - we always install into our own virtualenvs to avoid variations in the travis virtualenvs:

https://github.com/nipy/dipy/blob/master/.travis.yml#L31

**Comment by argriffing** [comment]
Fixed, at least temporarily, by https://github.com/scipy/scipy/pull/4739.

**Comment by ev-br** [comment]
I'd reopen --- if only to track ways of making it more robust. @argriffing please close if you prefer

**Comment by ev-br** [comment]
Here's a naive attempt: gh-4742.

**Comment by ev-br** [comment]
Seems to work now: https://travis-ci.org/scipy/scipy/jobs/58599429 (the PR is unrelated; the fact that the CI status is green despite the segfault is gh-4741). Re-closing.
