### ISSUE TITLE
some errors (due to segfaults?) are not interpreted correctly by the CI

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4741]
The PRs https://github.com/scipy/scipy/pull/4729 and https://github.com/scipy/scipy/pull/4739 are 'green' (indicating that they pass TravisCI tests) even though a config in the TravisCI build matrix aborts early due to an error involving numpy's relaxed strides checking.  I don't know the best way to fix this.

**Comment by rgommers** [comment]
Looks like ``nose`` does nothing special for segfaults now: https://github.com/nose-devs/nose/issues/58. What we do in ``runtests.py`` and in ``numpy.testing.NumpyTestProgram`` looks fine, so probably needs fixing in ``nose``.

**Comment by pv** [comment]
@argriffing log files on those PRs do not appear to show any segfaults?
Can you point to a Travis-CI log that shows (i) a segfault, and (ii)
successful result. The current runtests.py and nose a priori deal
properly with segfaults.

**Comment by rgommers** [comment]
gh-4729 has a segfault with numpy master (python 3.3 build in that PR): https://travis-ci.org/scipy/scipy/jobs/58344068

**Comment by pv** [comment]
That's actually not a segfault --- it seems xerbla is terminating the
process with exit code 0. I don't know if there's any other way to catch
this than to use 'tee' to put the output to a log file, and grep the
logfile afterwards for "On entry to .* parameter number .* had an
illegal value".

**Comment by pv** [comment]
Or even better, grep the output for the final summary message printed by
nose, to ensure the test run has been completed.

**Comment by argriffing** [comment]
> Or even better, grep the output for the final summary message printed by nose, to ensure the test run has been completed.

Maybe require a line that looks similar to
`Ran 17703 tests in 323.961s`

**Comment by argriffing** [comment]
fixed by https://github.com/scipy/scipy/pull/4792
