### ISSUE TITLE
scipy.signal.fftconvolve along speficied axis — cannot you add it?

### ISSUE THREAD

**Issue by Felix-neko** [scipy/scipy#4744]
Gentlemen! I want to filter multidimensional signal with 1D convolutional filter using `scipy.signal.fftconvolve` (along specified axis). Cannot you such an option to specify axes to filter to `scipy.signal.fftconvolve`?

**Comment by rgommers** [comment]
Maybe ``fftconvolve`` could grow an ``axes=None`` argument. It uses ``fftn/ifftn`` under the hood, which support that argument.

**Comment by Felix-neko** [comment]
I hope on that with breath bated.
^__^

**Comment by rgommers** [comment]
PR welcome if you want this to happen soon.

**Comment by jaimefrio** [comment]
Would there be any interest in adding a `'warp'` or `'cyclic'` mode to `fftconvolve`, that didn't do all the extra padding to avoid the kernel wrapping around? Cyclic convolution does have it uses...

**Comment by jaimefrio** [comment]
`'wrap'`, not `'warp'`...

**Comment by Felix-neko** [comment]
Well, just now in our project we use `fftconvolve` with `'full'` mode. But I think that cyclic convolution may be also useful for other users.

**Comment by jaimefrio** [comment]
@Felix-neko, simply adding the axis parameter to `fftconvolve` is a fairly simple change. Do you want to take the opportunity to become a scipy contributor?

**Comment by FRidh** [comment]
See also #3525 for further discussion on this topic. It also includes a reference to an implementation of fftconvolve which supports `axis`.

**Comment by endolith** [comment]
isn't this an exact duplicate of https://github.com/scipy/scipy/issues/3525?
