### ISSUE TITLE
scipy stats fit behaves questionably for distributions with bounded support

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4752]
I think it could be possible to find initial location and scale guesses automatically so that the initial support includes all of the data.  Given the initial shape parameters (default 1.0), I think you can already get the lower and upper bounds of the support (called `a` and `b`) for the default location and scale parameters 0 and 1.  Given `a` and `b`, you could pick initial location and scale parameter values such that the initial support covers all of the data points.  This would be an alternative to the current strategy of picking the initial location and scale parameters so that the mean and variance of the distribution match the mean and variance of the data.

There have been a few discussions about this problem in the past, but just as a concrete example here's a data array that causes problems for several distributions that have bounded support.
```python
>>> import numpy as np
>>> from scipy.stats import uniform
>>> data = [1.01, 1.78, 1.78, 1.78, 1.88, 1.88, 1.88, 2.00]
>>> uniform.fit_loc_scale(data)
(1.249943612210108, 0.99761277557978356)
>>> uniform.fit(data)
(1.7799948270442498, 0.2200056439937767)
>>> 
```

**Comment by josef-pkt** [comment]
IIRC, the test suite has some code that has a better choice of starting values for fit, depending on the support of the distribution, open, half open or closed.  
(GEV (`genextreme` ?) is messy because it depends on the parameters whether the support is half open on the left or on the right, AFAIR)

The distributions have an internal `_fitstart` that could be used to fix this on a distribution specific basis. For example uniform could just specify the estimate for loc= data.min() and scale = np.ptp(data), or something like that (which is also the MLE in that case IIRC).

**Comment by josef-pkt** [comment]
@argriffing  BTW: You have the permission to set and change labels, which you should do when you open an issue.

**Comment by argriffing** [comment]
> The distributions have an internal `_fitstart` that could be used to fix this on a distribution specific basis. For example uniform could just specify the estimate for loc= data.min() and scale = np.ptp(data), or something like that (which is also the MLE in that case IIRC).

Today or this weekend I might try adding this generically (as opposed to fixing on a distribution specific basis).  I think that enough information is programmatically available.  But I may need help with broadcastability issues or with navigating the object oriented stats framework.

Thanks for the hint about `genextreme`.  I guess you mean its support depends on its shape parameters?  Also I'll try to avoid the temptation to add distribution-specific MLE formulas until the generic fitting is improved a bit.

>  BTW: You have the permission to set and change labels, which you should do when you open an issue.

Sorry I've been adding scipy issues without setting these labels... I'll try to remember in the future!

**Comment by argriffing** [comment]
@josef-pkt This might be a dumb question, but what is the best way to compute the lower and upper bounds of the support given the shape parameters?  I'm looking for something like the line
`mu, mu2 = self.stats(*args, **{'moments': 'mv'})`
in `fit_loc_scale`, except which returns a lower and upper bound instead of the first and second moment.  In that line `args` consists of the shape parameters, and I think the location and scale are taken as 0 and 1 for the purpose of computing mean and variance.

**Comment by ev-br** [comment]
@argriffing `self.a` and `self.b`? `a call to _argcheck(self, *args)` fixes them for distributions with parameter-dependent support

**Comment by argriffing** [comment]
@ev-br so like

```python
self._argcheck(*args)
a, b = self.a, self.b
```

in analogy to

```python
mu, mu2 = self.stats(*args, **{'moments': 'mv'})
```

?

**Comment by argriffing** [comment]
@ev-br Thanks, that seems to work. I've opened a PR that uses this to initialize the location and scale guesses.
