### ISSUE TITLE
savemat doesn't work with none type. 

### ISSUE THREAD

**Issue by achatte** [scipy/scipy#4754]
#----------------------------------------------------
#This works
#----------------------------------------------------
import scipy.io as sio
a_dict = {'field1': 0.5, 'field2': 'a string'}
sio.savemat('saved_struct.mat', {'a_dict': a_dict})

#----------------------------------------------------
from pydal import DAL, Field
db = DAL('sqlite://storage.db')
db.define_table('thing',Field('name'))
db.thing.insert(name='Chair')
db.commit()
a = db().db.thing.as_dict();
#a is a dict, you can print out
#Now if you do 
sio.savemat('saved_struct.mat', {'a': a})
#gives you a type error because 
Could not convert None (type <type 'NoneType'>) to array

**Comment by rgommers** [comment]
@achatte it would help if you provide a standalone example that doesn't depend on ``pydal``.

**Comment by musically-ut** [comment]
Potentially a duplicate of https://github.com/scipy/scipy/issues/3488

**Comment by matthew-brett** [comment]
@achatte  - could you try with current scipy master?

**Comment by achatte** [comment]
Ita been resolved
