### ISSUE TITLE
scipy root no bounds

### ISSUE THREAD

**Issue by denfromufa** [scipy/scipy#4761]
Is it possible to specify the bounds on the root using any of the methods in scipy.optimize.root function:

method : str, optional
Type of solver. Should be one of
‘hybr’
‘lm’
‘broyden1’
‘broyden2’
‘anderson’
‘linearmixing’
‘diagbroyden’
‘excitingmixing’
‘krylov’

**Comment by dlax** [comment]
no, it's not possible

**Comment by denfromufa** [comment]
why not?

**Comment by dlax** [comment]
denfromufa a écrit :
> why not?

Because none of the available algorithms can handle bounds.

**Comment by denfromufa** [comment]
I think the documentation should mention this limitation of multidimensional solvers explicitly and recommend to use the scalar solvers such as `scipy.optimize.brentq`

**Comment by dlax** [comment]
denfromufa wrote:
> I think the documentation should mention this limitation of
> multidimensional solvers explicitly and recommend to use the scalar
> solvers such as |scipy.optimize.brentq|

I disagree. And I wouldn't say this is a limitation either, it's just 
not relevant for available algorithms. If someday, a multidimensional 
root finding algorithm supporting bounds (or constraints in general) 
comes in Scipy, it'd certainly be mentioned.

**Comment by DerWeh** [comment]
> I disagree. And I wouldn't say this is a limitation either, it's just
> not relevant for available algorithms.

Why would you say it isn't a limitation?
 If you cannot specify boundaries, the algorithm might give you wrong results, in the sense that they are outside your domain. In practice, I find this to actually be the biggest limitation of `scipy.optimize.root`. It is the reason why the root solver is hardly ever applicable for me.

Are you referring to workarounds like https://stackoverflow.com/a/44043515/6950750 ?
