### ISSUE TITLE
scipy.sparse matrices can not handle sympy multiplication

### ISSUE THREAD

**Issue by mschubert** [scipy/scipy#4764]
The `scipy.sparse` matrix does not seem to support symbolic multiplications that work in `numpy` and `scipy`. Consider the following:

``` python
>>> from sympy.abc import a
>>> import scipy
>>> import scipy.sparse
>>> import numpy
>>>
>>> scipy.matrix(1) * a
1.0*a
>>> numpy.matrix(1) * a
1.0*a
>>> scipy.sparse.csr_matrix(1) * a
TypeError: unsupported operand type(s) for *: 'csr_matrix' and 'Symbol'
>>> scipy.sparse.csr_matrix(1)[0,0] * a
a
```

Now, that the others all work and the element-wise multiplication also works, could this be that there is a check that is a bit too stringent or that this multiplication is not working only because `scipy.sparse` whitelists data types? If so, can this be amended?

Anyway, it would be great if this was working.

**Comment by pv** [comment]
The sparse matrices do not support arbitrary Python objects in them.
Extending this requires some nontrivial changes, as supporting that
would needs to account for refcounting etc.

**Comment by argriffing** [comment]
@pv Would this really require that sparse matrices contain arbitrary Python objects? The element-wise multiplication creates a dense `np.matrix` output, so couldn't matrix multiplication do something similar?

**Comment by pv** [comment]
I assume @mschubert wants to use sparse matrices to manipulate Sympy objects. Adding special cases for returning dense outputs is probably not very useful if this is the goal.

**Comment by mschubert** [comment]
The scenario is the following: I have got a sparse coefficients matrix (20k x 20k, about 20k values != 0) that I multiply with a dense sympy matrix (20k x 1).

Thus, if the result returns a dense matrix of size (20k x 1) that would already help in my case, but not necessarily for others.

**Comment by pv** [comment]
Matrix multiplication also requires dealing with refcounts of Python
objects (and dispatching to appropriate multiplication ops), so also
that is nontrivial.

**Comment by gautam1168** [comment]
Will something be done about this in the near future? I have resorted to converting the sparse matrix to dense before doing sympy multiplication. This works for me because my symbol matrix is small. But it is still an extra detail, and it would be nice if the library handled it. So since you said that this is non-trivial to implement, I am wondering if that means that it won't be done anytime soon.

**Comment by pv** [comment]
As usual, features are added when someone works on them and when they
are ready. The information available on this topic including schedule is
written on this page.

**Comment by larsmans** [comment]
Wouldn't it be easier to add a sparse matrix type to SymPy?

**Comment by rgommers** [comment]
It's not clear we'd still want a PR for this. I think it'd be a lot of churn for little benefit. And new features would likely better be targeted at pydata/sparse. Or in this case, to SymPy itself.

Closing - if that's not quite right, then please reopen/comment.
