### ISSUE TITLE
random ArpackNoConvergence errors

### ISSUE THREAD

**Issue by capybaralet** [scipy/scipy#4765]
I have version 0.14.0

When I run eigs on (e.g.) this matrix, sometimes I get this error, and sometimes not.

from scipy.sparse.linalg import eigs

bad_mat = array([[-0.33321168, -0.42988738,  1.04294134, -0.95111649],
       [ 0.26497105, -1.17402227,  0.64698876,  0.69501389],
       [-0.61462702, -0.78338991, -0.69106617,  0.47770545],
       [-1.35006014, -0.25615259, -0.69010069, -0.82230465]])

eigs(bad_mat,1)

Can anyone reproduce this?  And if so, solve it ;)?

**Comment by argriffing** [comment]
> Can anyone reproduce this?

Yes, I'm not sure what's going on with that.

```python
from __future__ import print_function, division

import numpy as np
import scipy
from scipy.sparse.linalg import eigs, ArpackNoConvergence

print('numpy version:', np.__version__)
print('scipy version:', scipy.__version__)

bad_mat = np.array([
    [-0.33321168, -0.42988738, 1.04294134, -0.95111649],
    [ 0.26497105, -1.17402227, 0.64698876, 0.69501389],
    [-0.61462702, -0.78338991, -0.69106617, 0.47770545],
    [-1.35006014, -0.25615259, -0.69010069, -0.82230465],
    ])

win = 0
fail = 0
for i in range(1000):
    try:
        x = eigs(bad_mat, 1)
        win += 1
    except ArpackNoConvergence as e:
        fail += 1
print('win: ', win)
print('fail:', fail)
```

```
numpy version: 1.9.1
scipy version: 0.16.0.dev0+e92ac8f
win:  533
fail: 467
```

**Comment by argriffing** [comment]
When I use the simpler matrix
```python
M = np.diag([0, 1.4, 1.2j, -1.2j])
```
with the above script I get
```
win:  964
fail: 36
```

**Comment by pv** [comment]
ARPACK uses a random starting vector, if you don't provide it explicitly.

**Comment by pv** [comment]
Does not appear to be a bug, closing.
