### ISSUE TITLE
linalg/_fblas.so: undefined symbol: PyArray_API

### ISSUE THREAD

**Issue by coral1801** [scipy/scipy#4767]
Reposting from here:[OpenBLAS/OpenBLAS#551](https://github.com/xianyi/OpenBLAS/issues/551), as this might be more relevant to scipy. 

  I built openblas(v0.2.14) from source and installed locally, using the instructions from here: http://osdf.github.io/blog/numpyscipy-with-openblas-for-ubuntu-1204-second-try.html. After this I installed numpy and scipy. numpy seems to be fine (tested with testnumpy.py) but scipy gave the following error on import:
site-packages/scipy/linalg/_fblas.so: undefined symbol: PyArray_API

numpy: 1.9.2
scipy:0.15.1
PYTHONPATH points to local install version of latest numpy

Any idea why this might be happening?

**Comment by pv** [comment]
Impossible to tell based on this information -- the most likely reason
is that there's something wrong in your build environment. At least the
full build log (paste to pastebin or gist.github.com), and list of
environment variables (`export` prints them) would be needed to say more.

**Comment by pv** [comment]
Also, you should check that you have numpy properly installed, the scipy version you are trying to import is the one that you are trying to build etc.

**Comment by coral1801** [comment]
The scipy build log is here: 
https://gist.github.com/coral1801/0cd987f2f42d9eb4a8a3

 I used the followiing command to build it: ./setup.py  build --fcompiler=gfortran

Relevant parts of the export output: 
 declare -x BLAS="~/packages/openblas/lib/libopenblas.a"
declare -x LAPACK="~/packages/lapack-3.5.0/liblapack.a"
declare -x LD_LIBRARY_PATH="~/packages/openblas/lib:"
declare -x PYTHONPATH="~/packages/numpy/lib/python2.6/site-packages/:"

I tested numpy installation using: https://gist.github.com/osdf/3842524
Before I do the python import of scipy, I set the python path to include both directories with the latest numpy and scipy.

**Comment by pv** [comment]
(i) Please include all of the output from `export` (you can censor
personal details).
(ii) Do a clean rebuild, i.e. rm -rf the directory and unpack again from
tarball.

**Comment by coral1801** [comment]
(ii) Do a clean rebuild, i.e. rm -rf the directory and unpack again from
tarball.

This fixed it!

The problem, I think was this: I did an initial build without the --fcompiler option which ended up compiling with f77. I later built this again with the gfortran option and because this was not a clean rebuild, caused some issued with the shared object.

Thank you very much pv.
