### ISSUE TITLE
Update contributor list for v0.16

### ISSUE THREAD

**Issue by andreas-h** [scipy/scipy#4774]
I'm in the process of updating the contributor name mapping in `tools/authors.py`.

@ldamewood, @levelfour,  @plafl, @RoyalTS, @terrycojones: I found your full name in your Github profile. Do you agree to have your full name included in the upcoming v0.16 release notes?

@argriffing Are you the person behind the committer "Perry" (e.g., ca35e25)?

@Andreea-G, @axiru, @kshramt, @I--P, @newman101, @perimosocordiae: I could not find your full names in your Github profiles.  Please let me know with which name you want to be listed in the release notes.

**Comment by Axiru** [comment]
El 26/04/15 a las 19:08, Andreas Hilboll escribió:
>
> I'm in the process of updating the contributor name mapping in 
> |tools/authors.py|.
>
> @ldamewood <https://github.com/ldamewood>, @levelfour 
> <https://github.com/levelfour>, @plafl <https://github.com/plafl>, 
> @RoyalTS <https://github.com/RoyalTS>, @terrycojones 
> <https://github.com/terrycojones>: I found your full name in your 
> Github profile. Do you agree to have your full name included in the 
> upcoming v0.16 release notes?
>
> @argriffing <https://github.com/argriffing> Are you the person behind 
> the committer "Perry" (e.g., ca35e25 
> <https://github.com/scipy/scipy/commit/ca35e25d68855861e9ef467b1c470a14de1036a7>)?
>
> @Andreea-G <https://github.com/Andreea-G>, @axiru 
> <https://github.com/axiru>, @Endolith <https://github.com/Endolith>, 
> @kshramt <https://github.com/kshramt>, @I--P 
> <https://github.com/I--P>, @newman101 <https://github.com/newman101>, 
> @perimosocordiae <https://github.com/perimosocordiae>: I could not 
> find your full names in your Github profiles. Please let me know with 
> which name you want to be listed in the release notes.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/scipy/scipy/issues/4774>.
>
I would like to be listed as @axiru.

**Comment by plafl** [comment]
Sure, thanks.

**Comment by terrycojones** [comment]
Full name is fine, thanks!

**Comment by RoyalTS** [comment]
Full name is fine for me as well, thanks!

**Comment by Andreea-G** [comment]
Full name is Andreea Georgescu. Thanks!

**Comment by rgommers** [comment]
People who want their name and/or email to be shown correctly on all repos, this is how to set it up:

    git config --global user.email you@yourdomain.example.com
    git config --global user.name "Your Name Comes Here"

**Comment by perimosocordiae** [comment]
My full name is CJ Carey.

**Comment by Newman101** [comment]
Hi, my full name is Juha Remes.

**Comment by levelfour** [comment]
Full name OK, thank you!

**Comment by kshramt** [comment]
Hi, my full name is Amato Kasahara.

**Comment by I--P** [comment]
On 26/04/2015 19:08, Andreas Hilboll wrote:
>
> @Andreea-G <https://github.com/Andreea-G>, @axiru 
> <https://github.com/axiru>, @Endolith <https://github.com/Endolith>, 
> @kshramt <https://github.com/kshramt>, @I--P 
> <https://github.com/I--P>, @newman101 <https://github.com/newman101>, 
> @perimosocordiae <https://github.com/perimosocordiae>: I could not 
> find your full names in your Github profiles. Please let me know with 
> which name you want to be listed in the release notes.
>
>
Hi,
I'm @I--P, my full name is Irvin Probst. Would you mind to quote my 
employer alongside my name ? Something like Irvin Probst (ENSTA 
Bretagne) ? It's a nonprofit educational institution and I developed 
place_poles on my working time.
Thanks.

**Comment by argriffing** [comment]
> @argriffing Are you the person behind the committer "Perry" (e.g., ca35e25)?

No, I think it's @perryism.

**Comment by ldamewood** [comment]
Yes, please use my full name.

Thank you, 
-Liam Damewood

**Comment by rgommers** [comment]
@andreas-h will you be able to finish this up before Sunday?

**Comment by andreas-h** [comment]
Yes, sure. I'm only waiting for Perry. Already wrote him private mail, no reply so far.

**Comment by perryism** [comment]
Hi, sorry for not being so responsive.  my full name is Perry Lee.   Thanks.
