### ISSUE TITLE
scipy.io.savemat module saves wrong structure mat

### ISSUE THREAD

**Issue by hecaiont** [scipy/scipy#4776]
my enviroment, window7 32bit anaconda spyder
here is my scripts,

---

from netCDF4 import Dataset
import matplotlib.pyplot as plt
import scipy.io as sio 

s = 'http://tds.hycom.org/thredds/dodsC/GLBu0.08/expt_19.1/2012/3hrly' # import data from server
f = Dataset(s, 'r')
v = f.variables

u = v['water_u'][0:1, 0:1, 1413:1651, 3838:4034] # import variables in data
u_xy = u[0,0,:,:] # 4D choose a location range

sio.savemat('savemat.mat', {'mat_u': u}) # save mat file
loadmat_u = sio.loadmat('savemat.mat')['mat_u'] # load mat file
mat_u_xy = loadmat_u[0,0,:,:] # 4D choose a location range 

plt.figure(1)
plt.imshow(u_xy)
plt.colorbar()

plt.figure(2)
plt.imshow(mat_u_xy)
plt.colorbar()

---

figure(1) and figure(2) are different each other

figure(1)
![severim](https://cloud.githubusercontent.com/assets/12151532/7368345/f000516c-ede1-11e4-86a7-5fff485f64bd.png)

figure(2)
![matim](https://cloud.githubusercontent.com/assets/12151532/7368350/f4460212-ede1-11e4-9811-d08e783439ef.png)

i think something wrong with scipy.io.savemat

**Comment by rgommers** [comment]
@elerrora thanks for the report. Looks like some conversion issue where floats get turned into ints. It would help if you could narrow this down further to a smaller self-contained example.

**Comment by yaosailor** [comment]
@hecaiont Thanks to the details.  I have the same problem when I used scipy.io.savemat.

**Comment by tylerjereddy** [comment]
Should be fixed if you use latest NumPy master branch apparently
