### ISSUE TITLE
circmean and others do not appear in the documentation

### ISSUE THREAD

**Issue by aarchiba** [scipy/scipy#4779]
I don't know why, but (for example) the function circmean in scipy/stats/morestats.py does not appear in the generated documentation: http://docs.scipy.org/doc/scipy/reference/stats.html . Neither do the functions circstd or circvar, although other functions in the file do. A few others are missing too.

**Comment by aarchiba** [comment]
See PR #4780

**Comment by ev-br** [comment]
done in gh-4780, closing.
