### ISSUE TITLE
problems with scipy sparse linalg isolve iterative.py when complex

### ISSUE THREAD

**Issue by francispoulin** [scipy/scipy#4788]
When solving a complex system using scipy.sparse.linalg.gmres, I get a segmentation fault.

My sample code is copied below.  

I have tried this on two different computes with the same versions of scipy 0.15.1, the one that has this problem is my ubuntu machine that uses anaconda.  My Mac with anaconda does not have this problem.  And my non-anaconda installation on my ubuntu machine works fine.

```
import numpy as np
import scipy.sparse as sr
import scipy.sparse.linalg as slg

N = 1e5
I = sr.eye(N,format='csr')
A = I + 1j*I
x = np.random.randn(N) + 1j*np.random.randn(N)
b = A.dot(x)

# scipy.gmres
x2 = slg.gmres(A,b)
print np.linalg.norm(x2[0]-x)
```

**Comment by rgommers** [comment]
Can you try to get a gdb traceback (see http://scipy.org/bug-report.html for a basic howto)?

**Comment by ev-br** [comment]
Have reformatted the code for clarity. 
I confirm there's no segfault on a 64 bit ubuntu precise with scipy master (no anaconda).

**Comment by francispoulin** [comment]
I am happy to try and use gdb but I have not used it before.  I tried using gdb python and that didn't work.  

Could you let me know how to execute each line of my python code?

**Comment by rgommers** [comment]
The first step is just ``gdb python`` on the command line. If that already doesn't work then I guess you don't have ``gdb`` installed. Can be installed from your Ubuntu package manager.

If it does work, you get to a prompt labeled ``(gdb)``. Then you want to run a script file with the code that segfaults (``run my_failing_script.py``).

Once that segfaults, you see output like this:

    Program received signal SIGTRAP, Trace/breakpoint trap.
    0x8fe01010 in __dyld__dyld_start ()
    (gdb)

then enter ``c`` and press Enter. Finally enter ``bt`` and Enter.

**Comment by francispoulin** [comment]
Thanks.  I do have it installed and tried running it to find the following result.

It seems to be a problem with mkl.  Maybe I should contact the anaconda people? 

If yes, sorry for the bother.

gdb ~/anaconda/bin/python
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/fpoulin/anaconda/bin/python...done.
(gdb) run test_gmres.py
Starting program: /home/fpoulin/anaconda/bin/python test_gmres.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 29 days
[New Thread 0x7ffff7f0f700 (LWP 32058)]
[New Thread 0x7fffd4cba700 (LWP 32059)]

Program received signal SIGSEGV, Segmentation fault.
0x00007fffdd565eea in mkl_blas_avx_zdotc () from /home/fpoulin/anaconda/lib/python2.7/site-packages/numpy/core/../../../../libmkl_avx.so

**Comment by rgommers** [comment]
That looks like https://github.com/scipy/scipy/issues/4520, which is only fixed in master (and will be in the 0.16.0 release).

**Comment by francispoulin** [comment]
I agree that seems to be it. It explains why it works on my Mac-Anaconda-MKL but not Ubuntu-Anaconda-MKL.  

I don't suppose that 0.16.0 will be released anytime soon?

If that's the case can I install the master?  I would guess I have to remove scipy from pip or conda and then install scipy using git. 

Does that sound like a reasonable thing to do?  If this is a horrible idea please let  me know.

**Comment by rgommers** [comment]
Should be released in June. The Anaconda folks might appreciate it if you let them know about this issue - if they make any updates before 0.16.0 is out then they can apply the fix to 0.15.1.

You can install scipy master, however you have to be a bit careful to build against the Anaconda Python (guess you also have a system Python) and with the right compilers and against MKL. This takes quite a bit of fiddling to get right. You'll need to specify the location to MKL in ``site.cfg``. And which compilers are used by Anaconda I'm not sure about.

**Comment by francispoulin** [comment]
Thanks again.

I did write to them to inform them of this problem in case they didn't know already.  I asked them if they have any advice on how to stall the Master in the mean time. 

Normally, on my ubuntu machine I use my non-anaconda version of python.  I am only trying anaconda because it has the mkl, which seems like a major plus.  I don't suppose one can use this on non-anaconda versions?  

If you say this is complex then there is a lot of room for me to mess up.  If there were instructions somewhere I would be happy to try them out but in the mean time I might have to wait, or see if anaconda can fix it.  They aren't nearly as fast (or good) at getting back to problems as you guys.

Thanks again.

**Comment by rgommers** [comment]
I don't think you can link against the MKL that Anaconda uses. But you could use a trial version from Intel directly if you just want to try it out to test performance differences.

Intel maintains a good set of instructions at https://software.intel.com/en-us/articles/numpyscipy-with-intel-mkl, and is pretty receptive to feedback in case that that doesn't work (it should I think). So you can give that a try.

**Comment by rgommers** [comment]
I'll close this issue, because should be solved in master.
