### ISSUE TITLE
RBF fixup programme

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#4790]
The discussion in https://github.com/scipy/scipy/issues/4523 has specific suggestions on enhancing / fixing scipy RBF code, esp https://github.com/scipy/scipy/issues/4523#issuecomment-74479182 and https://github.com/scipy/scipy/issues/4523#issuecomment-74445097.

**Comment by jjgreen** [comment]
I've created a branch to address this, comments & issues most welcome https://github.com/jjgreen/scipy/tree/RBF_fixup_4790

**Comment by rgommers** [comment]
@jjgreen the one commit I see there now looks fine. Commenting on larger/multiple commits is easier in a PR, so feel free to open one even if your code is still work in progress.

**Comment by jjgreen** [comment]
@rgommers, @pv, @ev-br  : I dug out my copy of Buhmann's "Radial Basis Functions" and have spent a couple of days working through it again. Nowhere can I see mention of a "smoothing parameter" as implemented in the existing code, and implementing the suggested changes and looking at some plots for this smoothing gives me even more concern about this (the smoothing rather than the changes).   Would you know of any reference?

The branch is https://github.com/jjgreen/scipy/tree/RBF_fixup_4790_smoothness_plots ; just adjust the parameter `smooth` in line 63 of

    scipy/interpolate/tests/test_rbf.py

and run the tests to see what I mean ...

**Comment by argriffing** [comment]
I think `epsilon` and `smooth` are like `ell` and `sigma_n` in (the first) equation 3 in http://www.robots.ox.ac.uk/~mebden/reports/GPtutorial.pdf. The title is something about 'Gaussian process regression' instead of 'radial basis functions' but I think the math is similar.

**Comment by argriffing** [comment]
@jjgreen I guess you are referring to https://github.com/jjgreen/scipy/commit/2d24a36a9a028df2e819bef3a5a3a9d4f0c5797d? Could you explain more about what you see vs. what you expect?

**Comment by jjgreen** [comment]
@argriffing - apologies for the delay in replying, my issue was that I was seeing oscillatory behaviour (ringing) for the smoothed interpolant.  




After finally finding a decent reference on this (Holger Wendland, “Computational Aspects of Radial Basis Function Approximation”, in K. Jetter et al. (eds.) Topics in Multivariate Approximation and Interpolation, Elsevier B.V., 2005, 231–256)

**Comment by jjgreen** [comment]
Incidentally, I propose 3 more changes to this module
- deprecate the linear, cubic and quintic function
- add the compactly supported basis functions of Wendland
- add a polynomial term to the interpolant to make the conditionally positive/negative definitely functions (multiquartic, thin-plate) unconditionally positive/negative definitely 

https://github.com/jjgreen/scipy/issues

**Comment by ev-br** [comment]
Ungated version of the reference above: http://www.num-analysis.uni-bayreuth.de/en/publications/2005/Computational_aspects_of_radial_basis_function_approximation/index.html

**Comment by jjgreen** [comment]
@pv, the snippet of code above implements scaling of the smoothing parameter by the largest absolute value of eigenvalue; is that what was meant by your earlier [comment](https://github.com/scipy/scipy/issues/4523#issuecomment-74479182)?

**Comment by jjgreen** [comment]
PR [here](https://github.com/scipy/scipy/pull/5070)

**Comment by ev-br** [comment]
Just recording a thought here. gh-5264 fixed a bug for a corner case where all the points are aligned along one of the axes. In that case, the volume of the bounding box was zero and thus the default value of epsilon was coming out to be zero. gh-5264 fixed that specific bug, but an issue remains: first, the prescription for the default epsilon is not rotationally invariant (eg, all the points are aligned along the x-axis vs some arbitrary line); second, if all the points are *almost* concentrated in a lower dimensional subspace (e.g., along a line + small noise in a perp direction), the default epsilon is going to be too small. 

This all is only to motivate a need to come up with a better heuristics, and I strongly suspect there is literature on this.

**Comment by rgommers** [comment]
This should be addressed by the new `RBFInterpolator` in gh-13595. Closing.
