### ISSUE TITLE
scipy.optimize.minimize returns success on function that returns NaN

### ISSUE THREAD

**Issue by b-v** [scipy/scipy#4793]
def f(x):                                                                        
        return float('nan')

    res = scipy.optimize.minimize(f, 1)
    print(res)

will show ```Optimization terminated successfully.```  and ```success: True```, while obviously the minimum has not be found.

Explicitly setting the method, to, e.g., ```method=Nelder-mead``` does return ```success: False```, which *is* what one would expect.

**Comment by larsmans** [comment]
CG and L-BFGS-B also report success in this case. Powell, SLSQP and TNC report failure.
