### ISSUE TITLE
TypeError in scipy/optimize/_trustregion

### ISSUE THREAD

**Issue by danielsjensen1** [scipy/scipy#4798]
Line 238 of scipy/optimize/_trustregion should have "m.fun" instead of "m()".  The following test case (a variation of scipy/optimize/tests/test_trustregion.py) will throw "TypeError: __call__() takes exactly 2 arguments (1 given)" without the given change:

from scipy.optimize import (minimize, rosen, rosen_der, rosen_hess, rosen_hess_prod)
x0=[-1.2, 1.0]
r = minimize(rosen, x0, jac=rosen_der, hessp=rosen_hess_prod,tol=1e-8, method='trust-ncg',options={'disp': True,'maxiter': 5})

I'm willing to submit a pull request to get it fixed but I've never done one before so I could use some guidance.

**Comment by argriffing** [comment]
@dlax this looks like a problem introduced in https://github.com/argriffing/scipy/pull/2 which was not caught by testing because it occurs only for `disp=True`. I guess there should be 'smoke tests' for that option (possibly across optimization methods) in a way that somehow does not clutter the unit test output.

**Comment by argriffing** [comment]
@danielsjensen1 thanks for this report, I think your proposed solution of changing `m()` to `m.fun` is correct but I'm not sure how the unit tests would work. Maybe you wouldn't need to worry about that and it could be added later in a separate PR?

> I'm willing to submit a pull request to get it fixed but I've never done one before so I could use some guidance.

Great! Here are some official guides:
https://docs.scipy.org/doc/scipy/reference/hacking.html
http://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html

Or try https://github.com/scipy/scipy/pull/4049#discussion_r18455048 which includes a recipe that may be more specific to your situation.

**Comment by dlax** [comment]
I agree with the diagnosis and proposed solution.

**Comment by danielsjensen1** [comment]
I just submitted my first pull request; I wouldn't be surprised if I messed up so let me know and I can probably fix it on Monday.  I can also contribute a unit test based on my first message but I'm not sure how to suppress the output.

**Comment by argriffing** [comment]
Thanks @danielsjensen1!
Fixed in https://github.com/scipy/scipy/pull/4801.
The testing issue has been opened separately as https://github.com/scipy/scipy/issues/4804.
