### ISSUE TITLE
griddata docstring doesn't make any sense

### ISSUE THREAD

**Issue by ellisonbg** [scipy/scipy#4802]
The docstring for `griddata` refers to many different integers:

`D`, `n`, `ndim`, `M`:

```
Interpolate unstructured D-dimensional data.

Parameters
----------
points : ndarray of floats, shape (n, D)
    Data point coordinates. Can either be an array of
    shape (n, D), or a tuple of `ndim` arrays.
values : ndarray of float or complex, shape (n,)
    Data values.
xi : ndarray of float, shape (M, D)
    Points at which to interpolate data.
```

The only one that is defined is `D`, so users have no idea what the others are.

Furthermore the example provided contradicts the docstring as xi is passed as a tuple but the docstring says it must be a ndarray.

**Comment by pv** [comment]
The integers are defined by the shapes of the input arrays.

**Comment by rgommers** [comment]
The ``xi`` description needs to be extended though, looks like it can be both 2-D ndarray or tuple of 1-D arrays.

**Comment by yash14123** [comment]
I wish to work on this . Will be sending the PR.

**Comment by pv** [comment]
Some clarification probably still needed.

**Comment by vedantrathore** [comment]
@pv can you explain more?
