### ISSUE TITLE
rv_continuous.rvs missing from list of scipy.stats methods in docs

### ISSUE THREAD

**Issue by mountaindust** [scipy/scipy#4807]
The link to the doc page for stats.rv_continous.rvs is missing from http://docs.scipy.org/doc/scipy/reference/stats.html

The [doc page](http://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.rvs.html#scipy.stats.rv_continuous.rvs) for stats.rv_continuous is present - it just needs to be linked to!

This bug is also present in the docs for scipy 0.14.

**Comment by ev-br** [comment]
Thanks for the report.
This has been fixed in master and should be available in the next release.
htttp://docs.scipy.org/doc/scipy-dev/reference/generated/scipy.stats.rv_continuous.html
