### ISSUE TITLE
enh: add `median` and `iqr` to continuous distributions

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4808]
These would be the [median](http://en.wikipedia.org/wiki/Median) and [interquartile range](http://en.wikipedia.org/wiki/Interquartile_range), with generic values `ppf(0.5)` and `np.ptp(ppf([0.25, 0.75]))` respectively. For some distributions these could be computed more directly than through the `ppf`, or they could be precomputed.

**Comment by ev-br** [comment]
Do you have a any specifics (however rough) of which distributions have explicit formulas available, so that this would be an improvement over `.ppf(0.5)`?

**Comment by rgommers** [comment]
low-prio if desired at all, so will close this. thanks all
