### ISSUE TITLE
A warning in SLSQP shows up with correct code

### ISSUE THREAD

**Issue by yw5aj** [scipy/scipy#4811]
Environment: Windows 7 64-bit, Python 3.4 64-bit, SciPy version 0.15.1, NumPy version: 1.9.2.

Code to repeat the bug:

``` python
import numpy as np
from scipy.optimize import minimize


def func(x):
    return (x ** 2).sum()


bounds = ((-5, None), (-5, None))
res = minimize(func, np.ones(2), method='SLSQP', bounds=bounds)
```

Reported warning:

> C:\WinPython3\python-3.4.3.amd64\lib\site-packages\scipy\optimize\slsqp.py:338: RuntimeWarning: invalid value encountered in greater
>  bnderr = where(bnds[:, 0] > bnds[:, 1])[0]

Thought: 
In line 330 of `slsqp.py`, it says:

``` python
if bounds is None or len(bounds) == 0:
    xl, xu = array([-1.0E12]*n), array([1.0E12]*n)
```

This check would fail when only part of the tuple is `None`.

**Comment by ewmoore** [comment]
The check on line 330 is fine.  The warning comes from comparing against `NaN`.  The fix here is to either filter the warning or fix this code to stop relying on comparison to `NaN` in the call to `np.where` on line 338 (looks like [337](https://github.com/scipy/scipy/blob/master/scipy/optimize/slsqp.py#L337) in master).

**Comment by pv** [comment]
Note that the best fix to the infinite bounds issue in SLSQP would be to
skip adding the constraint entries to the matrix if the bounds are
infinite, as I think it was done in NLopt
http://ab-initio.mit.edu/wiki/index.php/NLopt

**Comment by endolith** [comment]
Fixed in https://github.com/scipy/scipy/pull/7704 ?

**Comment by pv** [comment]
Yes, this was fixed then.
