### ISSUE TITLE
scipy.stats.distributions.rv_frozen not picklable

### ISSUE THREAD

**Issue by amueller** [scipy/scipy#4816]
```python
from scipy.stats import randint
import pickle
pickle.dumps(randint(1, 20))
```

> TypeError: can't pickle instancemethod objects

**Comment by ev-br** [comment]
Here's a half-finished branch with some pickling support: https://github.com/ev-br/scipy/tree/stats_pickle
I intend to come back to it, or just grab it.

**Comment by ev-br** [comment]
I'm not sure why @sotte closed this one a while ago, but here it is: https://github.com/scipy/scipy/issues/3125
(It's probably indeed easiest to just reconstruct the instance in ___getstate___)

**Comment by amueller** [comment]
Thanks for the reference. I'm swamped enough with scikit-learn issues at the moment so the likelihood of me picking this up is rather small :-/
