### ISSUE TITLE
Tracking backport candidates

### ISSUE THREAD

**Issue by pv** [scipy/scipy#4817]
The Github system doesn't natively offer very simple ways of tracking what is needed to backport.

Suggestions on this regard:
1. Use `backport-candidate` tag, to track both open and closed pull requests/issues, cf. https://github.com/scipy/scipy/pulls?q=is%3Apr+label%3Abackport-candidate+is%3Aclosed  The tag should be removed after all backports are done.
2. Open separate tickets for each backport required to be done.

Now, (1) is quite simple to use in practice, but is not as visible. (2) requires a bit more work, and is more noisy. Probably up to the release manager, but doing (1) also if (2) is done would sound OK to me.

**Comment by rgommers** [comment]
I'm fine with (1). Or otherwise (1) plus open a single issue per bugfix release that says "check all items labeled backport-candidate". (2) is a bit noisy for my taste

**Comment by rgommers** [comment]
Ideally we're rotating the release manager role while keeping the way of working for backports unchanged. So maybe this can go in the to-be-written devguide...

**Comment by rgommers** [comment]
We went with (1). This will be documented in gh-5424, which then closes this issue.

**Comment by rusergeev** [comment]
@rgommers, please close this issue. Thanks!

**Comment by rgommers** [comment]
Thanks @rusergeev, closing.
