### ISSUE TITLE
Current Windows BLAS/LAPACK binaries in numpy-vendor are missing routines

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#4829]
It's that time of the year again:

    g77.exe:f77: build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.f
    build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.f: In subroutine `f2pywrapslange':
    build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.f:29: 
             real work(MAX(m,1))
                       ^
    Invalid declaration of or reference to symbol `max' at (^) [initially seen at (^)]
    build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.f:22: 
            &a, work)
                1
    build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.f:31: (continued):
             slangef2pywrap = wslange(norm, m, n, a, lda, work)
             2
    Invalid declaration of or reference to symbol `work' at (2) [initially seen at (1)]
    build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.f: In subroutine `f2pywrapdlange':
    build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.f:43: 
             double precision work(MAX(m,1))
                                   ^
    Invalid declaration of or reference to symbol `max' at (^) [initially seen at (^)]
    build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.f:36: 
            &a, work)
                1
    build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.f:45: (continued):
             dlangef2pywrap = dlange(norm, m, n, a, lda, work)
             2
    Invalid declaration of or reference to symbol `work' at (2) [initially seen at (1)]
    build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.f: In subroutine `f2pywrapclange':
    build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.f:57: 
             real work(MAX(m,1))
                       ^
    Invalid declaration of or reference to symbol `max' at (^) [initially seen at (^)]
    build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.f:50: 
            &a, work)
                1
    build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.f:59: (continued):
             clangef2pywrap = wclange(norm, m, n, a, lda, work)
             2
    Invalid declaration of or reference to symbol `work' at (2) [initially seen at (1)]
    build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.f: In subroutine `f2pywrapzlange':
    build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.f:71: 
             double precision work(MAX(m,1))
                                   ^
    Invalid declaration of or reference to symbol `max' at (^) [initially seen at (^)]
    build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.f:64: 
            &a, work)
                1
    build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.f:73: (continued):
             zlangef2pywrap = zlange(norm, m, n, a, lda, work)
             2
    Invalid declaration of or reference to symbol `work' at (2) [initially seen at (1)]
    error: Command "C:\MinGW\bin\g77.exe -g -Wall -fno-second-underscore -mno-cygwin -O3 -funroll-loops -DNO_ATLAS_INFO=1 -Ibuild\src.win32-2.7 -IC:\Python27\lib\site-packages\numpy\core\include -IC:\Python27\include -IC:\Python27\PC -c -c build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.f -o build\temp.win32-2.7\Release\build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_flapack-f2pywrappers.o" failed with exit status 1

    Captured Task Output:
    ---------------------

    ---> pavement.bdist_wininst_simple
    ---> pavement.clean
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/paver/tasks.py", line 195, in _run_task
        return do_task()
      File "/usr/local/lib/python2.7/dist-packages/paver/tasks.py", line 192, in do_task
        return func(**kw)
      File "pavement.py", line 446, in bdist_wininst_simple
        _bdist_wininst(options.bdist_wininst_simple.python_version, env)
      File "pavement.py", line 460, in _bdist_wininst
        subprocess.check_call(cmd, env=cfg_env)
      File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
        raise CalledProcessError(retcode, cmd)
    CalledProcessError: Command '['/home/vagrant/.wine/drive_c/Python27/python.exe', 'setup.py', 'build', '-c', 'mingw32', 'bdist_wininst']' returned non-zero exit status 1

Will look at this more tomorrow; if someone more versed in Fortran 77 build issues with g77 wants to fix this or point out what the right way to fix it should be, that would be much appreciated.

**Comment by pv** [comment]
If the variables are subroutine arguments, `work(*)` instead of
`work(MAX...)` is the right thing.

**Comment by rgommers** [comment]
Thanks @pv, that fixed that one. Next is:

    g77.exe:f77: scipy\linalg\_blas_subroutine_wrappers.f
    g77.exe:f77: scipy\linalg\_lapack_subroutine_wrappers.f
    g77.exe:f77: Z:\home\vagrant\repos\scipy\scipy\_build_utils\src\wrap_dummy_g77_abi.f
    g77.exe:f77: Z:\home\vagrant\repos\scipy\scipy\_build_utils\src\wrap_dummy_accelerate.f
    ar: adding 4 object files to build\temp.win32-2.7\libfwrappers.a



    Found executable C:\MinGW\bin\gcc.exe
    C:\MinGW\bin\g77.exe -g -Wall -mno-cygwin -g -Wall -mno-cygwin -shared build\temp.win32-2.7\Release\scipy\linalg\cython_blas.o -LC:\local\lib\atlas\nosse -LC:\MinGW\lib -LC:\MinGW\lib\gcc\mingw32\3.4.5 -LC:\Python27\libs -LC:\Python27\PCbuild -Lbuild\temp.win32-2.7 -lfwrappers -llapack -lblas -lpython27 -lg2c -o build\lib.win32-2.7\scipy\linalg\cython_blas.pyd
    build\temp.win32-2.7/libfwrappers.a(_blas_subroutine_wrappers.o): In function `dsdotwrp_':
    Z:/home/vagrant/repos/scipy/scipy/linalg/_blas_subroutine_wrappers.f:77: undefined reference to `dsdot_'
    collect2: ld returned 1 exit status
    error: Command "C:\MinGW\bin\g77.exe -g -Wall -mno-cygwin -g -Wall -mno-cygwin -shared build\temp.win32-2.7\Release\scipy\linalg\cython_blas.o -LC:\local\lib\atlas\nosse -LC:\MinGW\lib -LC:\MinGW\lib\gcc\mingw32\3.4.5 -LC:\Python27\libs -LC:\Python27\PCbuild -Lbuild\temp.win32-2.7 -lfwrappers -llapack -lblas -lpython27 -lg2c -o build\lib.win32-2.7\scipy\linalg\cython_blas.pyd" failed with exit status 1

Objdump output at https://gist.github.com/rgommers/e06508dfa444b179411c

**Comment by pv** [comment]
Is the BLAS in the Atlas library complete? DSDOT is supposed to be there.

**Comment by rgommers** [comment]
It's supposed to be. I did check that at least in the sources that are checked into numpy-vendor it's there. Didn't check the binaries yet.

**Comment by rgommers** [comment]
Searching for ``dsdot`` in the output of 

    $ wine /home/vagrant/.wine/drive_c/MinGW/bin/objdump.exe -t 
    /home/vagrant/.wine/drive_c/local/lib/atlas/nosse/libblas.a

finds only ``_sdsdot_`` but not ``_dsdot_``:


    sdsdot.o:     file format pe-i386^M
    ^M
    SYMBOL TABLE:^M
    [  0](sec -2)(fl 0x00)(ty   0)(scl 103) (nx 1) 0x00000000 sdsdot.f^M
    File ^M
    [  2](sec  1)(fl 0x00)(ty  20)(scl   2) (nx 1) 0x00000000 _sdsdot_^M
    AUX tagndx 0 ttlsiz 0x0 lnnos 0 next 0^M
    [  4](sec  1)(fl 0x00)(ty   0)(scl   3) (nx 1) 0x00000000 .text^M
    AUX scnlen 0x1e2 nreloc 0 nlnno 0^M
    [  6](sec  2)(fl 0x00)(ty   0)(scl   3) (nx 1) 0x00000000 .data^M
    AUX scnlen 0x0 nreloc 0 nlnno 0^M
    [  8](sec  3)(fl 0x00)(ty   0)(scl   3) (nx 1) 0x00000000 .bss^M
    AUX scnlen 0x0 nreloc 0 nlnno 0^M

**Comment by pv** [comment]
The conclusion then is that the libblas.a file there is incomplete.
DSDOT is part of the API, cf http://www.netlib.org/blas/#_blas_routines
.
Easiest fix is probably just to download the dsdot.f from netlib,
compile it, and use `ar` to insert it to the libblas.a archive.

**Comment by rgommers** [comment]
OK I'll try that. I'm also building now with ``cython_blas`` removed from ``linalg/setup.py`` to see if the Lapack part is complete. If more is missing, then rebuilding it all might make more sense.

**Comment by rgommers** [comment]
And longer term, we might want to upgrade to a newer version anyway?

**Comment by matthew-brett** [comment]
I did a build of ATLAS 3.10.1 for SSE2 on 32 and 64 bit here:

http://nipy.bic.berkeley.edu/scipy_installers/atlas_builds/

I see that we are now down to less than 1 percent of Windows machines without SSE2 for Firefox crash reports:

```
$ python analyze_crashes.py 20150507-pub-crashdata.csv.gz 
20150507-pub-crashdata.csv.gz: 0.81
```

See: https://gist.github.com/matthew-brett/9cb5274f7451a3eb8fc0

I wonder if we can get away with just the SSE2 build now?

**Comment by rgommers** [comment]
Going for SSE2 only would allow Windows wheels (at least until we get fancy new instructions that are optional). 0.8% is still a fair number of users though, given the download stats on SourceForge (~500 .exe installers per day on average). 0.008 * 500 = 4 users a day reporting weird crashes would not be fun....

**Comment by rgommers** [comment]
The first issue is now fixed, the BLAS binaries still need fixing.

**Comment by rgommers** [comment]
Maybe we should experiment with SSE2 though - still provide the superpack on SF but a SSE2-only wheel on Pypi (with clear warnings in all the places we have install info). That'll decrease the pain of trying ``pip install scipy``.

@matthew-brett do you have a build recipe + sources somewhere for that ATLAS build? I'd like to keep those somewhere public, so we can reproduce the whole setup later on. I imagine it was somewhat nontrivial to build correctly?

**Comment by rgommers** [comment]
this is not going to happen tonight, will do a first beta without Windows installers

**Comment by matthew-brett** [comment]
I put the build recipes (I believe they are the ones I used) up at http://nipy.bic.berkeley.edu/scipy_installers/atlas_builds/

I put the code archives up too.   I had to work with Clint Whaley on the phone for a while to get them to build correctly :)  However, I do have a machine that I can automate the builds on.

**Comment by rgommers** [comment]
This should be fixed by https://github.com/numpy/numpy-vendor/pull/3

**Comment by rgommers** [comment]
@matthew-brett you built those ATLAS binaries with gfortran it looks like, so that's incompatible with https://github.com/numpy/numpy-vendor:

    g77.exe:f77: build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_fblas-f2pywrappers.f
    C:\MinGW\bin\g77.exe -g -Wall -mno-cygwin -g -Wall -mno-cygwin -shared build\temp.win32-2.7\Release\build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_fblasmodule.o build\temp.win32-2.7\Release\build\src.win32-2.7\fortranobject.o build\temp.win32-2.7\Release\home\vagrant\repos\scipy\scipy\_build_utils\src\wrap_dummy_g77_abi.o build\temp.win32-2.7\Release\home\vagrant\repos\scipy\scipy\_build_utils\src\wrap_dummy_accelerate.o build\temp.win32-2.7\Release\build\src.win32-2.7\build\src.win32-2.7\scipy\linalg\_fblas-f2pywrappers.o -LC:\local\lib\atlas\sse3_atlas310 -LC:\MinGW\lib -LC:\MinGW\lib\gcc\mingw32\3.4.5 -LC:\Python27\libs -LC:\Python27\PCbuild -Lbuild\temp.win32-2.7 -llapack -lf77blas -lcblas -latlas -lpython27 -lg2c -o build\lib.win32-2.7\scipy\linalg\_fblas.pyd
    C:\local\lib\atlas\sse3_atlas310/libf77blas.a(xerbla.o):xerbla.f:(.text+0x45): undefined reference to `_gfortran_st_write'
    C:\local\lib\atlas\sse3_atlas310/libf77blas.a(xerbla.o):xerbla.f:(.text+0x5c): undefined reference to `_gfortran_transfer_character_write'
    C:\local\lib\atlas\sse3_atlas310/libf77blas.a(xerbla.o):xerbla.f:(.text+0x73): undefined reference to `_gfortran_transfer_integer_write'
    C:\local\lib\atlas\sse3_atlas310/libf77blas.a(xerbla.o):xerbla.f:(.text+0x7b): undefined reference to `_gfortran_st_write_done'
    C:\local\lib\atlas\sse3_atlas310/libf77blas.a(xerbla.o):xerbla.f:(.text+0x8f): undefined reference to `_gfortran_stop_string'
    collect2: ld returned 1 exit status

Also, the build script looks like you built under Cygwin?

**Comment by matthew-brett** [comment]
Yes, I did build with gfortran, and cygwin.  Are you trying to link the
other ATLAS builds with this one?

I don't think Cygwin is a problem, because the resulting binaries don't
link to cygwin.dll.

**Comment by rgommers** [comment]
No, I was trying to build all of scipy with g77 against your ATLAS binary. Mixing g77 + gfortran that way is not the best idea.
