### ISSUE TITLE
Bugs in C code in __quadpack.h

### ISSUE THREAD

**Issue by pv** [scipy/scipy#4831]
This code looks wrong: https://github.com/scipy/scipy/blob/master/scipy/integrate/__quadpack.h#L128

```
  check = PyObject_GetAttrString(func, "argtypes");
  if (!PyTuple_Check(check) || (PyTuple_GET_SIZE(check) != 1) || 
      (PyTuple_GET_ITEM(check, 0) != c_double)) {
    if ((PyTuple_GET_ITEM(check, 0) == c_int) && (PyTuple_GET_ITEM(check, 1) == c_double)){   
      /*If first param is int and second is of double type, we have valid_multivariate */
       ...
       return Valid_Multivariate_Ctype;
    }
    else 
      goto fail;
  }
```

The argument checks are done wrong (PyTuple_GET_ITEM called even if PyTuple_Check fails, etc).

Moreover, the actual argument type used later on is a pointer to a double, not double. The check should check that.

The check at https://github.com/scipy/scipy/blob/master/scipy/integrate/__quadpack.h#L396 should check for equality, not inequality.

This code stores a pointer to a local variable, which is invalid: https://github.com/scipy/scipy/blob/master/scipy/integrate/quadpack.h#L176

The code stores pointers of different types in `global_args` and `storage->args`, e.g. https://github.com/scipy/scipy/blob/master/scipy/integrate/quadpack.h#L170. These variables should be `void*`, not `PyObject*`.

I didn't have time to look at the PR that added these at the time...

**Comment by larsmans** [comment]
There's at least one more mistake: if `limit < 1`, three values are returned regardless of whether `full_output=True`.

**Comment by larsmans** [comment]
And one more. There's a test for thread-safety that is in fact only checking single-threaded reentrancy. The globals in `quadpack.h` are not protected by any locks.

**Comment by larsmans** [comment]
I tried various strategies to fix this, but they all lead to convoluted code. Is there a way to pass a pointer through the Fortran code?

**Comment by pv** [comment]
No. That's why it's convoluted.

**Comment by pitrou** [comment]
> Moreover, the actual argument type used later on is a pointer to a double, not double. The check should check that.

Agreed with this. This makes it difficult or impossible to test using a ctypes-wrapped Python function, since the calling convention becomes completely wrong.

**Comment by dhirschfeld** [comment]
Just been bitten by this as it prevents `scipy.integrate.quad` from being used with numba which (at least for me) would be a killer feature.


> The check at https://github.com/scipy/scipy/blob/master/scipy/integrate/__quadpack.h#L396 should check for equality, not inequality.

@pv - the logic above is repeated 7x in the function and seems to go if it's not a `Callable` and not a `Valid_Ctype` then it implies that it must be a `Valid_Multivariate_Ctype`. Certainly not the clearest way to do the check but I think the inequality comparison is correct?

**Comment by pv** [comment]
The comparison is correct, but writing the inverse would be better style.

**Comment by dhirschfeld** [comment]
Indeed! :stuck_out_tongue_winking_eye:

**Comment by rgommers** [comment]
Hi, anyone interested to try out or review gh-6509? It adds generic infrastructure for low-level callables, which is then used to fix this issue.

**Comment by ev-br** [comment]
I am definitely going to play with this from a user perspective. Will report back, although cannot promise when though.

**Comment by dhirschfeld** [comment]
I'd like to but compiling it on win64 / py35 might be a little tricky.
I don't suppose there are wheels or conda packages lying around from the CI or otherwise?

**Comment by rgommers** [comment]
No Windows CI unfortunately (Appveyor will time out, build is too slow). And yes, it's a pain. Unless you have Intel Fortran I wouldn't try it for Python 3.5 (for 2.7 you may still try MingwPy).

**Comment by FaustinCarter** [comment]
@dhirschfeld I stumbled in here after trying to get numba to play nice with scipy.integrate.quad. I was originally stymied by this bug, but eventually managed to get it working by explicitly specifying the argtypes attribute of the returned ctypes function to be what scipy expects (example below):

```python
import numpy as np
import ctypes as ct
import numba
import scipy.integrate as sint

#Set the signature of the future types function
#The second argument must be a pointer or it won't work right,
#but this will cause problems because of the bug in scipy
#because scipy looks for a double instead of a pointer
c_sig = numba.types.double(numba.types.intc, numba.types.CPointer(numba.types.double))

#Turn the integrand function into a ctypes function
@numba.cfunc(c_sig)
def my_integrand(n, a):
    args = numba.carray(a, n)
    x = args[0]
    b = args[1]
    
    return b*np.exp(-x)/x**2

#Force the argtypes to be what quad expects
my_integrand.ctypes.argtypes = (ct.c_int, ct.c_double)

#Now this will work just fine!
sint.quad(my_integrand.ctypes, 1, np.inf, (2))
```
