### ISSUE TITLE
Can't install scipy with Pip on Windows Python 3.4

### ISSUE THREAD

**Issue by ballatron** [scipy/scipy#4832]
I have upgraded Pip and typed in "pip install scipy." I got numpy to install but not scipy.  I am using Python 3.4 on Windows.

If you could help me out that would be great! Thanks! 

This is the error I get:
    Command "C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:
\\Users\\bspulbe\\AppData\\Local\\Temp\\pip-build-uv5sb3l_\\scipy\\setup.py';exe
c(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n')
, __file__, 'exec'))" install --record C:\Users\bspulbe\AppData\Local\Temp\pip-n
b0t5em5-record\install-record.txt --single-version-externally-managed --compile"
 failed with error code 1 in C:\Users\bspulbe\AppData\Local\Temp\pip-build-uv5sb
3l_\scipy

**Comment by rgommers** [comment]
Can you put the full build log in a gist and link to it? And tell us how you installed Python itself and which compilers you use?

**Comment by ballatron** [comment]
Hi,

here is the gist: https://gist.github.com/ballatron/86ce0fd927cb5c3c4e6a

I have python installed through: https://www.python.org/downloads/.  32-bit, 3.4.3.

I do not think I have a copmiler installed; do you think that may be the problem?

Thanks!

**Comment by rgommers** [comment]
Yes. ``pip`` installs from source, so you need all the compilers and dependencies set up for that. You want to download the superpack installer for Python 3.4 from http://sourceforge.net/projects/scipy/files/scipy/0.15.1/

**Comment by pv** [comment]
The error message tells you what's wrong:
"numpy.distutils.system_info.NotFoundError: no lapack/blas resources found".
.
If you don't know what this means, try asking google, or use precompiled
binaries: http://scipy.org/install.html

**Comment by ballatron** [comment]
Great thanks @rgommers that worked!

**Comment by IFDAAS** [comment]
Greetings all,
easiest way is the following steps:
Fixing scipy for python [ 2.x < python <  3.x ]

1) Downloaded the necessary files from: http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy
2) Download the version of numpy+mkl (needed to run scipy) and then download scipy for your python type (2.x python written as 2x) or (3.x python written as 3x), x is variable. Note you must know whether you have a 32bit or 64bit processor.
4) Create a directory somewhere on your computer, example [C:\DIRECTORY] to install the files numpy+mkd.whl and Scipy.whl
5) Once both file are downloaded, find the location of the file on your computer and move it to the directory you created. 
5) Example first file installation is needed for scipy is in---> C:\DIRECTORY\numpy\numpy-0.0.0+mkl-cp1x-cp1xm-win_amd32.whl
6) Example second file installation is in---> C:\DIRECTORY\scipy\scipy-0.0.0-cp1x-cp1xm-win_amd32.whl
7) Test both modules on your python IDLE as following:
import numpy
import scipy

**the modules are working if no errors are returned.
IFDAAS
