### ISSUE TITLE
gammainc should return 1.0 instead of NaN for infinite x

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4834]
See http://en.wikipedia.org/wiki/Incomplete_gamma_function#Asymptotic_behavior.  Note that `scipy.special.gammainc` is documented as `Incomplete gamma function` but is more specifically the 'regularized lower incomplete gamma function'.

**Comment by argriffing** [comment]
[`gdtr`](http://docs.scipy.org/doc/scipy/reference/generated/scipy.special.gdtr.html) appears to have the same problem.

**Comment by argriffing** [comment]
Here's a PR related to incomplete gamma edge cases https://github.com/scipy/scipy/pull/27.

**Comment by ev-br** [comment]
Has been fixed in gh-5395, closing.
