### ISSUE TITLE
enh: exprel special function

### ISSUE THREAD

**Issue by rmcgibbo** [scipy/scipy#4838]
It would be useful to add the relative exponential function, `exprel`, as a special unfunc. `exprel` is a function to compute `(exp(x)-1)/x` which is accurate for small x.

It's available in the [GSL](https://www.gnu.org/software/gsl/manual/html_node/Relative-Exponential-Functions.html#Relative-Exponential-Functions) and discussed in section 1.14 of "Accuracy and Stability
of Numerical Algorithms" by Higham.

**Comment by argriffing** [comment]
+1 I've wanted this function before, and I've also wanted to know its name.

On the other hand I've heard that the computational problems with computing this function for small x magically disappear if you use `expm1(x)/x`, so a new ufunc would be more of a convenience function.

```python
>>> x = 1e-30
>>> np.expm1(x)/x
1.0
```

**Comment by rmcgibbo** [comment]
oh good point, using `expm1` would probably solve the precision problems too.

I'm looking through the scipy/special directory to try to figure out how I would go about implementing this -- do you have any recommendations of where to look (e.g. an example function). All the various levels of wrapping are nontrivial to figure out.

**Comment by argriffing** [comment]
> do you have any recommendations of where to look (e.g. an example function). All the various levels of wrapping are nontrivial to figure out.

Here's a PR where I tried to add some ufuncs from information theory: https://github.com/scipy/scipy/pull/3981.

If I remember correctly, some of those files may be generated but not as automatically as .c files are generated from .pyx files.  I think you need to run a script, maybe `scipy/special/generate_ufuncs.py`.

Here's a PR that mentions that script: https://github.com/scipy/scipy/pull/2905.

**Comment by rmcgibbo** [comment]
Cool -- thanks. I'll try to figure this out and implement this over the weekend.

public domain implementation to work from: http://www.netlib.no/netlib/slatec/fnlib/exprel.f
there's also an implementation in the gsl, but obviously that's not license compatible. FWIW I think the GSL just uses the taylor expansion when `x` is near zero.

**Comment by rmcgibbo** [comment]
#4839 is merged, so closing this.
