### ISSUE TITLE
enh: aggressive DE strategies

### ISSUE THREAD

**Issue by pavelponomarev** [scipy/scipy#4853]
Hi,
Is it possible to add some aggressive strategies to DE like "current-to-best/1/bin"?
http://www.dii.unipd.it/~alotto/didattica/corsi/Elettrotecnica%20computazionale/DE.pdf
BR, Pavel

**Comment by dlax** [comment]
Sure, patch welcome ;)

**Comment by pavelponomarev** [comment]
After more thorough code examination, and after discussions in #4864 , it seems that implemented DE algorithm in scipy is already aggressive. So, this information must be added to documentation.
So, actually I want to do exactly the opposite right now) - implement possibility for non aggressive mutation strategy, which is more suitable for parallelization. The works on that are under discussion in #4864.

**Comment by argriffing** [comment]
> After more thorough code examination, and after discussions in #4864 , it seems that implemented DE algorithm in scipy is already aggressive

I'll close this issue then.

**Comment by argriffing** [comment]
> information about aggressiveness of the mutation strategy must be added to the documentation of the module.

@pavelponomarev do you want to make a PR to add this clarification?  What about just mentioning in the docstring that the default strategy `best1bin` is relatively aggressive and uses overlapping generations (if this is true)?

**Comment by pavelponomarev** [comment]
@argriffing let's wait results of the discussion in #4864
