### ISSUE TITLE
Porting the rest of cKDTree to C++

### ISSUE THREAD

**Issue by sturlamolden** [scipy/scipy#4855]
I have started the tedious work of porting the rest of cKDTree query methods to C++. The structure is similar to the `query` method that is in C++ in the 0.16 branch (#4374).

The other methods have much more to gain from C++ than query due to substantially larger Python overhead. On my old laptop with AMD Phenom the new query method reduced the query time from 85 seconds to about 3 seconds. The improvement in the other methods is likely to be much better than that.

Right now I have mostly just copied out code and made placeholders for the C++. But the main structure is already there.

It is in this branch on Github:

https://github.com/sturlamolden/scipy/tree/cpp_ckdtree/scipy/spatial/ckdtree

There are other enhancement PRs for cKDTree as well, e.g. #3841 #3840 They deal with issues that is related to Python overhead (e.g. use of Python set). I don't think we need to change `query_pairs` or add alternate version if the Python overhead (Python `int`, Python `set`, Python `list`, refcounting on `ckdtree.Rectangle` classes, etc.) is squashed. Alternate versions with various forms of reduced Python overhead is not needed if we can remove all of it in `query_pairs` et al.

(I am not sure if I should post a WIP PR or wait until it builds correctly so Travis does not have a heart attack.)

**Comment by sturlamolden** [comment]
```query_pair``` is ported over to C++ and works fine. I get a rougly 6x speedup on my Mac. The Python ```set``` has no impact on the performance. ```output_type``` keyword argument selects between a ```set``` and ```ndarray``` as return container.

**Comment by sturlamolden** [comment]
WIP PR: https://github.com/scipy/scipy/pull/4860

**Comment by sturlamolden** [comment]
I have ported ```query_neighbors``` to C++. The single-threaded case is about 14x faster without data prefetching (did not add that yet).

**Comment by sturlamolden** [comment]
```query_ball_point``` is now ported to C++. 

```query_ball_tree``` and ```sparse_distance_matrix``` remains to be ported.

**Comment by sturlamolden** [comment]
More or less completed.

**Comment by sturlamolden** [comment]
The remaining issue now is parallel processing in the query methods that compare two kd-tree objects, ```query_ball_tree()```, ```query_pairs()```, ```count_neighbors()```, and ```sparse_distance_matrix()```.

**Comment by kdunn926** [comment]
If it is still applicable, I'm interested in helping finish this effort. Is there any direction you can offer?

**Comment by sturlamolden** [comment]
We still do not have parallel processing in these methods. We would need to use a fork-join design on the ```traverse``` methods: http://web.engr.oregonstate.edu/~mjb/cs575/Handouts/treealgs.6pp.pdf

The complicating factor is we are not using OpenMP or GCD in SciPy, and hence ```cKDTree``` uses a pool of threads spawned with ```threading.Thread``` in Cython. They release the GIL in C++ to run in parallel. We therefore need to rewrite the ```traverse``` methods as functors that use such a thread pool to do something similar to the mentioned OpenMP code. And on top of that we must make sure that the required synchronisation and restructuring do not impair the speed of the single-threaded version. Perhaps you can find libraries that does this and are compatible with our license? Anyway, if you want to give it a shot, then good luck. Otherwise I suggest we just wait for SciPy to allow OpenMP.

**Comment by sturlamolden** [comment]
Or perhaps you can think of a totally different way of doing this? 

Anyway, I am off to an appointment with my dentist and then I will spend the rest of the day pretending to be James Herriot — which, by the way, can be a lot more rewarding for a veterinary surgeon than to fry my brain thinking about parallel tree traversals in C++ 😂.

**Comment by sturlamolden** [comment]
It is completed so I am closing this issue.
