### ISSUE TITLE
documentation for shape args of `expect` seems inconsistent

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4858]
Although the shape argument of the base class [`expect`](http://docs.scipy.org/doc/scipy-dev/reference/generated/scipy.stats.rv_continuous.expect.html) function is correctly documented as the tuple called `args`, the call signature of the distribution-specific `expect` member functions are less clearly documented.

For the [gamma](http://docs.scipy.org/doc/scipy-dev/reference/generated/scipy.stats.gamma.html) distribution it's a bit misleading that `a` is a shape parameter in `mean` but a length-1 tuple of shape parameters in `expect`
```python
mean(a, loc=0, scale=1)
expect(func, a, loc=0, scale=1, lb=None, ub=None, conditional=False, **kwds)
```
and for the [gausshyper](http://docs.scipy.org/doc/scipy-dev/reference/generated/scipy.stats.gausshyper.html) distribution the documented call signature of `expect` is just incompatible with the actual call signature.
```python
mean(a, b, c, z, loc=0, scale=1)
expect(func, a, b, c, z, loc=0, scale=1, lb=None, ub=None, conditional=False, **kwds)	
```

**Comment by rgommers** [comment]
Documented more clearly in gh-5153. Cannot be changed in a backwards-compatible way, so closing.
