### ISSUE TITLE
docstring contradicts validation for tolerance args in scipy.optimize.bisect

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4863]
http://docs.scipy.org/doc/scipy-dev/reference/generated/scipy.optimize.bisect.html

**Comment by person142** [comment]
I believe this is fixed in master:

http://scipy.github.io/devdocs/generated/scipy.optimize.bisect.html

as compared to the old version:

http://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.optimize.bisect.html

**Comment by rgommers** [comment]
thanks @person142, closing
