### ISSUE TITLE
fmin_l_bfgs_b doesn't preserve dtype

### ISSUE THREAD

**Issue by mblondel** [scipy/scipy#4873]
Program:

``` python
import numpy as np
from scipy.optimize import fmin_l_bfgs_b

rng = np.random.RandomState(0)
X = rng.rand(5, 4).astype(np.float32)
w = rng.rand(4).astype(np.float32)
y = np.dot(X, w)

def func(w):
    print "func", w.dtype
    y_pred = np.dot(X, w)
    ret = 0.5 * np.dot(y - y_pred, y - y_pred)
    return ret

def grad(w):
    print "grad", w.dtype
    y_pred = np.dot(X, w)
    ret = np.dot(X.T, y - y_pred)
    return ret

init = np.zeros_like(w)
sol = fmin_l_bfgs_b(func, init, grad)[0]

print "init", init.dtype
print "sol", sol.dtype
```

Output:

```
func float64
grad float64
func float64
grad float64
[...]
init float32
sol float64
```

Given that my initialization is of type float32 and that func / grad only use operations that preserve the dtype, I would expect the solution to be of type float32 as well.

**Comment by argriffing** [comment]
Just to explain and not necessarily to justify the current behavior, the underlying Fortran implementation uses hardcoded `double precision` so the dtype would not be preserved automatically.
https://github.com/scipy/scipy/blob/master/scipy/optimize/lbfgsb/lbfgsb.f
This is in contrast to the BLAS/LAPACK functions that have float32/float64/complex64/complex128 variants.

**Comment by mblondel** [comment]
I guess there isn't much we can do then. We could cast the final solution in the same dtype as the initialization but that sounds a little bit silly. Maybe we should just improve the docstring to mention that the underlying implementation uses harcoded double precision.

**Comment by wolfgang-noichl** [comment]
> We could cast the final solution in the same dtype as the initialization but that sounds a little bit silly.

It does also not solve the problem. I encountered this because my func/grad require single precision x.
So even if you'd cast the result, everyone who relies on f(x: float32) is still doomed.
Internal typecasts everywhere would also doom performance in a way hard to identify...

**Comment by mblondel** [comment]
As suggested by @ev-br in #5832 

> In principle, I guess, one could copy-paste the Fortran code, replace all double precision with real and write a fused-type cython wrapper to dispatch depending on the input type. This would then be a bit of a project to actually investigate the stability of single-precision maths.

**Comment by andyfaff** [comment]
> It does also not solve the problem. I encountered this because my func/grad require single precision x. So even if you'd cast the result, everyone who relies on f(x: float32) is still doomed.

@wolfgang-noichl would it be possible to expand a bit more on this?

**Comment by andyfaff** [comment]
Am going to close, as converting the LBFGSB fortran code to be able to use SP/DP is likely to be a project requiring a reasonable amount effort for an unclear gain (premature optimisation). If people wish to take up the baton and investigate if this is possible, then they are more than welcome to offer suggestions of how to proceed, or to submit a PR. By closing the issue I'm not saying it's not a pain point.
Note that finite difference calculations for evaluation of gradients should probably be using double precision anyway.

**Comment by wolfgang-noichl** [comment]
> > It does also not solve the problem. I encountered this because my func/grad require single precision x. So even if you'd cast the result, everyone who relies on f(x: float32) is still doomed.
> 
> @wolfgang-noichl would it be possible to expand a bit more on this?

Assume you have a function `f(x)` that you optimize that needs `x` as `float32` numpy array, and may not check the input data type explicitly. So it may fail in a way that you don't even realize it's a type problem. Casting the result doesn't help there at all. Silent casting of `x` is dangerous as well, because it sacrifices performance/space in a very oblique way.

> Note that finite difference calculations for evaluation of gradients should probably be using double precision anyway.

Yeah, but you may well be able to calculate gradients directly, depending on the problem.

I understand why converting the fortran code may be overkill. But what about throwing an exception when called with a type different from `float32`. 

Just in case someone needs a real 32bit LBFGS, I patched pyLBFGS for this back then. It can be found [here](https://github.com/wolfgang-noichl/pylbfgs/tree/proposal-errorhandling-32bit), however, it's only python2. One can easily patch the recent upstream version to float32, though :)
