### ISSUE TITLE
misc.imsave does not work with file type defined

### ISSUE THREAD

**Issue by Mikhail22** [scipy/scipy#4893]
Ubuntu, python 2.7, latest scipy and pil (python-pil) installed.
trying to define file type to save image with custom name 
misc.imsave("somename", img, "bmp") 
returns:
TypeError: imsave() takes exactly 2 arguments (3 given)

On Fedora linux this error also appeared, but was magically solved by installing python-pillow package.
How can it be fixed under Ubuntu? What it the relation with PIL (or pillow?), namely why it has suddenly start working with 3 arguments (on fedora) after installing pillow?

**Comment by rgommers** [comment]
Sounds like Fedora has a more recent version of Pillow. ``misc.imsave`` is quite simple, so this is very likely to be a Pillow issue:

    def imsave(name, arr, format=None):
        im = toimage(arr)
        if format is None:
            im.save(name)
        else:
            im.save(name, format)
        return

**Comment by rgommers** [comment]
Can you double-check the Pillow versions you're using?

**Comment by Mikhail22** [comment]
For ubuntu I can't check now. On fedora 21 I have this in yum history:
Command Line   : install python-pillow python-pillow-devel
Transaction performed with:
    Installed     rpm-4.12.0.1-6.fc21.i686               @updates
    Installed     yum-3.4.3-153.fc21.noarch              @koji-override-0/$releasever
    Installed     yum-metadata-parser-1.1.4-14.fc21.i686 @koji-override-0/$releasever
Packages Altered:
    Dep-Install libjpeg-turbo-devel-1.3.1-5.fc21.i686 @updates
    Install     python-pillow-2.6.2-1.fc21.i686       @updates
    Install     python-pillow-devel-2.6.2-1.fc21.i686 @updates
    Dep-Install zlib-devel-1.2.8-7.fc21.i686          @fedora

Other PC has Ubuntu 14.04. and  I have naively installed the first thing I found for 'pillow' in repos. it was 'python-pil', but I think it was maybe wrong choice. Now I see Pillow's installation recmmends 'python-imaging' package.

**Comment by Mikhail22** [comment]
Tried to install on Ubuntu 14.04 again with apt-get python-imaging package (and all dependencies as stated http://pillow.readthedocs.org/en/latest/installation.html). It installs me also pil automatically:
Setting up python-pil (2.3.0-1ubuntu3) ...
Setting up python-imaging (2.3.0-1ubuntu3) ...

Still I have the same error:
TypeError: imsave() takes exactly 2 arguments (3 given)

**Comment by rgommers** [comment]
Okay, so the error disappeared on Ubuntu for you with Pillow 2.6.2. So if on Ubuntu you also upgrade Pillow to that version and things start to work, I think this can be closed.

**Comment by Mikhail22** [comment]
Sorry, but still no success on Ubuntu. I have uninstalled previous 'python-pil' with apt-get remove, then installed latest version with:
sudo pip install Pillow
...
--------------------------------------------------------------------
    PIL SETUP SUMMARY
    --------------------------------------------------------------------
    version      Pillow 2.8.1
    platform     linux2 2.7.6 (default, Mar 22 2014, 22:59:56)
                 [GCC 4.8.2]
    --------------------------------------------------------------------
    --- TKINTER support available
    --- JPEG support available
    *** OPENJPEG (JPEG2000) support not available
    --- ZLIB (PNG/ZIP) support available
    --- LIBTIFF support available
    --- FREETYPE2 support available
    --- LITTLECMS2 support available
    --- WEBP support available
    --- WEBPMUX support available
    --------------------------------------------------------------------
...

So everything is ok at installation. Still I get same error:
TypeError: imsave() takes exactly 2 arguments (3 given)

So I am not sure what is the problem

**Comment by rgommers** [comment]
OK then this needs some debugging effort from someone who can reproduce the issue. I'm on Ubuntu, so should be able to do that once I install the right Pillow version. Can you confirm that this fails for you (it should, given your description)?

    from scipy import misc
    misc.imsave('tmpname.bmp', misc.ascent(), 'bmp')

**Comment by Mikhail22** [comment]
Yes this fails as well with same error. I must say, I will not probably be good at debugging and reporting, since I am on Ubuntu only twice a week at best. I've encountered this issue only by accident, when I was trying to save an image with custom file name.
