### ISSUE TITLE
scipy.special.hyp2f1 giving more incorrect results

### ISSUE THREAD

**Issue by Vectornaut** [scipy/scipy#4894]
_Possibly related to #3479?_

When _z_ is near 0.95j, evaluating `hyp2f1(1/2., 2/3., 3/2., z)` gives results that are wrong by 60 or 70 orders of magnitude. The bad region has very sharp boundaries. For example, stepping up the imaginary axis with an increment of 0.01j,
- I go from the correct value 0.93 + 0.16j to the incorrect value 4e62 + 4e62j in the step to 0.90j, and
- I go from the incorrect value 4e73 - 2e72j back to the correct value 0.92 + 0.18j in the step from 1j.

The bad region extends away from the imaginary axis, at least out to real part 1/3.

Working example:

``` python
from scipy.special import hyp2f1

for n in range(41):
  z = 0.75j + n*0.01j
  print 'f({}) = {}'.format(z, hyp2f1(1/2., 2/3., 3/2., z))
```

This code gives incorrect results from 0.9j to 1j.

It also prints "Warning! You should check the accuracy" during each evaluation from 0.84j to 1.07j. I can't find any reference to this warning in the documentation.

**Comment by Vectornaut** [comment]
Workaround: SymPy's implementation of hyp2f1 works correctly in this region.

**Comment by argriffing** [comment]
Here are more hyp2f1 failures, inspired by http://stats.stackexchange.com/questions/148192 with the idea to add a beta.logcdf implementation that is more clever than log(beta.cdf).

```python
>>> hyp2f1(1924.74 + 33.7179, 1, 1924.74 + 1, 0.5555555)
26.262715780500489
>>> hyp2f1(1925.74 + 33.7179, 1, 1925.74 + 1, 0.5555555)
-14.591633151887409
```

Wolfram:
```
> 2F1[1924.74 + 33.7179, 1, 1924.74 + 1, 0.5555555]
2.29879...
> 2F1[1925.74 + 33.7179, 1, 1925.74 + 1, 0.5555555]
2.29876...
```

**Comment by steppi** [comment]
This was fixed by gh-14706. The issue was due to the standard transformations not covering the regions around exp(±iπ/3), necessitating the use of another method to evaluate `hyp2f1` in these regions. For instance, on my machine with the latest SciPy I get the following results

```
import scipy.special as sc

from mpmath import mp

result1 = sc.hyp2f1(1/2, 2/3, 3/2, 0.95j)
print(result1)
# (0.9266639083743893+0.16955520843509506j)

result2 = complex(mp.hyp2f1(1/2, 2/3, 3/2, 0.95j))
print(result2)
# (0.9266639083743891+0.16955520843509503j)

print(abs(result1 - result2)/abs(result2))
# 2.375383603658572e-16
```
