### ISSUE TITLE
some scipy ufuncs have inconsistent output dtypes?

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4895]
The `lambertw` function appears to have inconsistent output dtypes:
```python
>>> from scipy.special import lambertw
>>> lambertw(0, 0, 0)
0j
>>> lambertw([0], 0, 0)
array([ 0.+0.j])
>>> lambertw(0, [0], 0)
array([ 0.+0.j], dtype=complex64)
>>> lambertw(0, 0, [0])
array([ 0.+0.j])
```
This behavior is shared by `sph_harm` and is possibly at the root of https://github.com/scipy/scipy/issues/4887.

**Comment by pv** [comment]
Yes, the casts for integer inputs seem to work incorrectly. If any of
the arguments is a float, it will cast correctly. The dtype selection is
done by Numpy, based on the ufunc signatures:
```
>>> sph_harm.types
['llff->F', 'lldd->D', 'ffff->F', 'dddd->D']
>>> sph_harm(0,[0],0,0).dtype
dtype('complex64')
>>> sph_harm(0,[0],[0],0).dtype
dtype('complex128')
>>> sph_harm(0,0,0,0).dtype
dtype('complex128')
```
The above leads to believe that it's a Numpy bug,
https://github.com/numpy/numpy/issues/5895 --- note how the result works
out if there are only scalars, or if one of the latter arguments is an
array. The ufunc loop selector probably fails to consider trailing
scalar arguments to resolve ambiguous dtypes.
.
In the meantime, we probably should just stop generating the float32
rules for the cases where there are integer arguments. It's probably OK
to just change the logic in
scipy/special/generate_ufuncs.py:iter_variants to:
```
    # float32-preserving signatures
    if not ('i' in inputs or 'l' in inputs):
        # Don't add float32 versions of ufuncs with integer
        # arguments, as this can lead to incorrect dtype selection
        # if the integer arguments are arrays, but float arguments are
        # scalars. For instance sph_harm(0,[0],0,0).dtype == complex64
        # This may be a Numpy bug, but we need to work around it.
        # cf. gh-4895, https://github.com/numpy/numpy/issues/5895
        maps = maps + [(a + 'dD', b + 'fF') for a, b in maps]
```

**Comment by rgommers** [comment]
Fixed by gh-4896.
