### ISSUE TITLE
expm is 10x as slow as matlab according to http://stackoverflow.com/questions/30048315

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4897]
This is reported for matrices of size `6 x 6`.

**Comment by sturlamolden** [comment]
```scipy.linalg.expm```calls ```scipy.sparse.linalg.expm```. A version of ``expm``` for dense matrices would likely be faster.

**Comment by sturlamolden** [comment]
Here is an implementation of the "scaling and squaring" method for 4 x 4 matrices using cblas. It should be possible to use this as inspiration to write a general ```expm```method in Cython:
https://github.com/poliu2s/MKL/blob/master/matrix_exponential.cpp

**Comment by argriffing** [comment]
Yes I was looking at this too and I think a lot of the cost is in importing `scipy.sparse.linalg` on the first `expm` call if it has not already been imported.

The matrix exponential code makes some attempt to be efficient for large-ish dense matrices, but it could use some more attention.  It theoretically uses the 2009 scaling and squaring algorithm.  I'll plan to spend more time on it, here are some notes...

---

It could make use of a `max_abs` ufunc if this existed in numpy, and it could use something like a `count_nonzero` for the triangular parts of dense matrices to help check for triangularity, if this is not deemed too trivial.  Maybe like cythonized `count_nonzero_tril(M, k=0)` and `count_nonzero_triu(M, k=0)` or something.  This should at least use `triu_indices` instead of `triu`.  Also the `_ell` function should precompute the values of `abs_c_recip` for various values of `m`, and it should cache matrix-vector calculations of `_onenorm_matrix_power_nnm` to be re-used across calls to `_ell(M, k)` for different values of `k`.

**Comment by wjkaufman** [comment]
Has there been any progress made on this?

**Comment by sturlamolden** [comment]
I do not have Matlab for comparison. Also “as fast as Matlab” is not really a goal, as Matlab is not a gold standard and we are not trying to copy Matlab. 

It is unclear how the benchmarking was done and how much is constant overhead. 

Finally, the real question is if our ```expm``` is too slow for practical use. The post on Stackoverflow does not say.
