### ISSUE TITLE
sparse.linalg.lsqr dimension mismatch although A m-by-n and b m-by-1

### ISSUE THREAD

**Issue by chingchia** [scipy/scipy#4902]
I could not figure out why the following code always gives "dimension mismatch" although A is m-by-n matrix and b is m-by-1 vector.

```
import numpy as np
import scipy.sparse as sparse
from scipy.sparse import linalg 


A = sparse.rand(10000,5000, format="csc")
b = sparse.rand(10000,1,format="csc").todense()

linalg.lsqr(A,b)
```

```
File "/lib/python2.7/site-packages/scipy/sparse/base.py", line 345, in __mul__
    raise ValueError('dimension mismatch')
ValueError: dimension mismatch
```

**Comment by sonnyhu** [comment]
In doc (http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.sparse.linalg.lsqr.html), "b : (m,) ndarray  Right-hand side vector b."  So `b` should be `sparse.rand(10000,0, format="csc").todense()`. Hope this helps.

**Comment by ev-br** [comment]
`.todense()` creates a `np.matrix` which is always two-dimensional. On the other hand, `lsqr` is documented to expect a 1D `ndarray`. If you cast your right-hand-side to one, it seems to work:

```
>>> b = sparse.rand(100, 1, format='csc').toarray()    # notice .toarray() instead of .todense()
>>> b.shape
(100, 1)
>>> b = b.reshape((-1,))
>>> b.shape
(100,)
>>> linalg.lsqr(A, b)
```

Conclusion: not a scipy bug.

**Comment by chingchia** [comment]
Yes you guys are right! Thanks for the help
