### ISSUE TITLE
typo in code of stats tutorial page re "Univariate estimation"

### ISSUE THREAD

**Issue by hayne** [scipy/scipy#4911]
On the page <http://docs.scipy.org/doc/scipy/reference/tutorial/stats.html>
the code in the "Univariate estimation" section has the following lines:
>>> ax.plot(x_eval, kde1(x_eval), 'k-', label="Scott's Rule")
>>> ax.plot(x_eval, kde1(x_eval), 'r-', label="Silverman's Rule")

The second of the above lines should be using 'kde2' instead of 'kde1'.

**Comment by rgommers** [comment]
Indeed. Thanks for the report @hayne.

**Comment by rgommers** [comment]
Looks like that's my fault, will send a PR.
