### ISSUE TITLE
ENH?: M-way repeated measures ANOVA in scipy.stats

### ISSUE THREAD

**Issue by dengemann** [scipy/scipy#4913]
This statistic is often requested in experimental sciences where observational units are repeatedly exposed to different treatments. So far this seems to be missing in the scipy/scikits world. See repeated requests on statsmodels and elsewhere.

Over the last years we impleneted this function in a general maner based on a numpy array API for our M/EEG/ electrophysiology toolbox MNE-Python.
One important catch, this implentation supports 2-D arrays for Y, so it allows you to fit the model to multiple observations at a given sample at the same time.
We use this for neuroimaging purposes, where we often have to deal with mutliple observations and spatio-temporal corralation among the observations per sample.
It's pretty fast, you can fit a model with hundred thousands of observations in less then a few seconds.

Would you be interested in incoroprating this code into scipy?

cf. 
https://github.com/mne-tools/mne-python/pull/2153
https://github.com/dengemann/mne-python/blob/m-way-ranova/mne/stats/parametric.py

cc @josef-pkt

**Comment by rgommers** [comment]
I'm writing a message to the mailing list now to discuss this (related to the ``f_value`` functions). Statsmodels might be a better fit. Or if we add it to Scipy, we need to be very clear on the scope extension. Current ANOVA functionality is quite neglected.

**Comment by tupui** [comment]
Hi all, closing as it's now in Statsmodels.
