### ISSUE TITLE
Signed git tags for releases

### ISSUE THREAD

**Issue by pv** [scipy/scipy#4919]
To provide some extra robustness, we could start using gpg signed git tags for releases.

There's no real cost involved, just writing `git tag -s` instead of `git tag` when (re-)creating the tag and everything should work as previously. Indeed, the v0.15.1 release tag is signed,
```
$ git tag -v v0.15.1
object fcdc3d7b7c1b950d874ac3e890cccde3e2de1c6c
...
gpg: Signature made su 18. tammikuuta 2015 18.41.37 EET using DSA key ID B3B4A560
gpg: Good signature from "Pauli Virtanen <pav@iki.fi>"
gpg:                 aka "Pauli Virtanen <pauli.virtanen@iki.fi>"
```
Does this matter in practice? Hopefully not, but on the other hand it's probably not a bad practice either when doing releases.

**Comment by rgommers** [comment]
+1 to the idea, but then where do we put our public keys?

    $ git tag -v v0.15.1
    object fcdc3d7b7c1b950d874ac3e890cccde3e2de1c6c
    type commit
    tag v0.15.1
    tagger Pauli Virtanen <pav@iki.fi> 1421599297 +0200

    Release 0.15.1
    gpg: Signature made Sun 18 Jan 2015 05:41:37 PM CET using DSA key ID B3B4A560
    gpg: Can't check signature: public key not found
    error: could not verify the tag 'v0.15.1'

**Comment by pv** [comment]
We can follow here standard GPG good practices. Public GPG keys can be
put to public keyservers. See `gpg --send-keys` and `gpg --recv-keys`.
.
Debian also does this: https://ftp-master.debian.org/keys.html
For us, listing the key IDs and fingerprints (`gpg --fingerprint`) on
scipy.org would probably be enough.
.
In addition, there's GPG's web of trust mechanism; fairly complicated
however. Debian probably has good documentation on how to use it.

**Comment by pv** [comment]
In practice, if the key ID and fingerprint are mentioned in the release
announcement mail, and the mail is signed with the same key, that is
already not so easy to forge --- the real release manager would see the
forgery and react to it.

**Comment by rgommers** [comment]
Thanks. I created a public key and uploaded it to a standard keyserver. Will add this to the devguide before closing the issue.

**Comment by juliantaylor** [comment]
there you are :) https://pgp.mit.edu/pks/lookup?search=ralf+gommers&op=index

note that the signed tags should have an annotation containing the version number as unfortunately the name of a tag can be changed without the breaking signature.

here are some docs to key creation:
http://keyring.debian.org/creating-key.html

not only the tags should be signed but also binaries and the PyPI uploads.
For binary uploads one should sign the README.txt containing sha256 checksums of the files, so when one verifies the file containing the checksums one can verify the binaries too. An alternative would be to add detached signature for every file, but that would clutter the download page too much. (this is currently already done for the latest scipy and numpy releases)

Signatures should also be required for PyPI uploads (also already done for scipy). twine is useful to upload signed tarballs generated from some other place like numpy-vendor. https://pypi.python.org/pypi/twine/1.5.0

@matthew-brett I noticed the numpy mac wheels are not signed, can you do so in future?

**Comment by pv** [comment]
IIRC, `git tag -s` prompts you to write the annotation.

gh-4918 automated the readme signing, so it's more difficult to forget now.

I wasn't aware of twine, so previously I've just done the PyPi uploads manually via the web interface (because `setup.py upload` is crap, over HTTP, password in plaintext in a config file), and also generated the `.asc` files manually.

**Comment by rgommers** [comment]
Note: 0.16.0rc1 tag isn't signed, due to me traveling with a laptop that doesn't have my secret key on it. The final release will be signed.

**Comment by rgommers** [comment]
v0.16.0 signed and pushed.

**Comment by rgommers** [comment]
``twine upload -s installers/*.*`` works nicely indeed

**Comment by matthew-brett** [comment]
I'll upload the wheels.   I built them yesterday...​

**Comment by rgommers** [comment]
cross-talk:) I sent you an email about that just now
