### ISSUE TITLE
unexpected zero output values from zoom

### ISSUE THREAD

**Issue by bbudescu** [scipy/scipy#4922]
Last lines / columns of zoomed images seem to have unexpected zero values in some cases.

After running 

``` python
import numpy as np
from scipy.ndimage import zoom
a = zoom(np.ones((110, 72), np.float32), (51. / 110, 40. / 72))
```

`all(a[-1] == 0)` yields `True`

The issue is that after resizing a white image, you don't expect getting a black line at its bottom.

**Comment by aganders3** [comment]
The default `mode` is `'constant'`, which uses a constant value (default is 0.0) for pixels outside the boundaries of the image.

Using another `mode` (e.g. `'nearest'`) may give the result you are expecting:

    In [9]: a = zoom(np.ones((110, 72), np.float32), (51. / 110, 40. / 72), mode='nearest')
    In [10]: all(a[-1] == 0)
    Out[10]: False

**Comment by bbudescu** [comment]
I agree, but that doesn't mean that this is correct behaviour, in my opinion. It seems to me that this might be a bug with the computation of the output size, maybe reminiscent of the change in the way it is computed that you are sometimes warned about (using `round` yields some different sizes than previous versions). Perhaps there is some lack of synchronization between the explicit computation of output size in `zoom`, `get_output` - which is used twice (once in `spline_filter` and once in `zoom` - before and after the explicit computation of the output shape) and `zoom_shift`.

**Comment by rgommers** [comment]
There's a lot of issues and discussions on what the behavior on the edge of images should be. This is probably the most extensive one: https://github.com/scikit-image/scikit-image/issues/1514

**Comment by jacobhilton** [comment]
I think there may be rounding errors that interact badly with this behaviour. For example, I found this result confusing:
```
In [3]: zoom(np.ones(16), [5], order=1, mode='constant')[-10:]
Out[3]: array([1., 1., 1., 1., 1., 1., 1., 1., 1., 0.])
```
(There is no final zero when replacing 5 by 4 for example.)

**Comment by sethtroisi** [comment]
zoom has lots of related bugs describing this with uint8, bool

https://github.com/scipy/scipy/issues/3203
https://github.com/scipy/scipy/issues/7324
https://github.com/scipy/scipy/issues/6713

it's generally gets traced to `interpolate` or `map_coordinate`
