### ISSUE TITLE
BUG: cluster: The `color_list` argument of `dendrogram` is undocumented and ignored.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#4926]
The function `scipy.cluster.hierarchy.dendrogram` has an argument `color_list`, but this argument is not documented in the docstring, and is not used in the code.  In fact, the first use of `color_list` in the `dendrogram` code is 

        color_list = []

**Comment by QuLogic** [comment]
It's weird that it's an argument, because it's documented as a return value.

**Comment by rgommers** [comment]
I agree that it shouldn't be a parameter. Fix in progress.

**Comment by Chrisinger** [comment]
Are you sure that should not be a parameter? I think this is the way to color the dendrogram in other than the standard colors. No other parameter allows to do that.

**Comment by QuLogic** [comment]
No, it does nothing. Please see the description in the commit referenced above.
