### ISSUE TITLE
smooth priors detrending

### ISSUE THREAD

**Issue by AidanRocke** [scipy/scipy#4927]
It appears that scipy doesn't have a function for smooth priors detrending as described by Akaike here: https://statistics.stanford.edu/sites/default/files/AND%20ONR%2040.pdf 

Is this observation correct? I checked scipy.signal.detrend() and I am only given the options of 'constant' or 'linear'.

**Comment by rgommers** [comment]
Correct, don't have this. I think it's more ``statsmodels`` territory than ``scipy.stats`` or ``scipy.signal``. I guess you came to the same conclusion (https://github.com/statsmodels/statsmodels/issues/2429)? I'll close this and comment on the statsmodels issue.

**Comment by AidanRocke** [comment]
I think you're right that statsmodels needs this most.
