### ISSUE TITLE
max rank in sparse.linalg.eigsh

### ISSUE THREAD

**Issue by mblondel** [scipy/scipy#4935]
It's currently not possible to compute the full eigendecomposition with `eigsh`.

``` python
>>> A = rand(5, 4)
>>> AA = np.dot(A.T, A)
>>> from scipy.sparse.linalg import eigsh
>>> eigsh(AA, AA.shape[0])
[...]
ValueError: k must be between 1 and the order of the square input matrix.
```

https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/eigen/arpack/arpack.py#L1506

I think `k >= n` should be replaced by `k > n`.

**Comment by mblondel** [comment]
Or instead of raising an exception, one could do `k = min(k, n)`.

**Comment by pv** [comment]
ARPACK requires k < n.

**Comment by pv** [comment]
In principle, it would be possible to switch to LAPACK dense solver for
the cases ARPACK doesn't handle. For abstract linear operators, this
would require first computing n matrix products to get a dense
representation, so there's some hassle in implementing it. The result
however may still be faster than ARPACK.

**Comment by mblondel** [comment]
Doesn't materializing a dense representation kill the point of a linear operator?

**Comment by pv** [comment]
Calculating full (or nearly full) eigendecompositions negates much of the point of using a linear operators. If you use ARPACK for k=n-1, for example, it will do calculations on nxn matrices anyway --- and because it is optimized for the sparse case, it will not perform well when compared to LAPACK.

**Comment by sethtroisi** [comment]
Fixed by https://github.com/scipy/scipy/pull/7004
Which references a near duplicate issue: https://github.com/scipy/scipy/issues/6430
