### ISSUE TITLE
Docs on extending ndimage need to be updated.

### ISSUE THREAD

**Issue by sirpercival** [scipy/scipy#4938]
There are two things which need to be addressed. First, it should be updated to make use of PyCapsule instead of PyCObject; second, an example using Cython instead of (or in addition to) pure C should also be included.

**Comment by rgommers** [comment]
This is a request for developer documentation right, not user-visible docs? Scipy doesn't have a C/Cython API (except for ``linalg.cython_blas`` and ``linalg.cython_lapack``). We don't have such docs organized for any scipy module. Where had you expected to find this?

**Comment by sirpercival** [comment]
I'm referring to the ["Extending ndimage in C" ](http://docs.scipy.org/doc/scipy/reference/tutorial/ndimage.html#ndimage-ccallbacks) documentation, which is definitely part of the user-visible Scipy documentation. I was able to get something running using advice on stackoverflow [here](http://stackoverflow.com/questions/16441903/creating-a-pycobject-pointer-in-cython), but it doesn't work properly (no idea if it's my code in particular or ndimage/Cython, but probably the former) so I can't really comment on the quality of the advice.

**Comment by rgommers** [comment]
Thanks @sirpercival, I was totally unaware of that. 

This functionality is also untested it looks like, so needs adding tests for C/Cython functions.

**Comment by rgommers** [comment]
If you say it doesn't work correctly, there's a good chance that that's a real bug given that this is basically untested.

**Comment by sirpercival** [comment]
Ah, good to know! Shall I gist my Cython code here?

**Comment by rgommers** [comment]
@sirpercival yes please

**Comment by sirpercival** [comment]
@rgommers here you go! https://gist.github.com/sirpercival/07891ccd966063637d3e

**Comment by rgommers** [comment]
@sirpercival thanks. It's pretty short, so I'll just post it here for everyone to read even easier:

    import numpy as np
    cimport numpy as np
    from cpython.cobject cimport PyCObject_FromVoidPtrAndDesc
    from scipy.ndimage import geometric_transform
    from astropy.modeling import models, fitting

    cdef int _shift_function(double* output_coordinates, double* input_coordinates,
                int output_rank, int input_rank, double* shift_data):
        cdef np.ndarray[double, ndim=1] shift = np.asarray(<double[:3]> shift_data)
        cdef Py_ssize_t ii
        for ii in range(input_rank):
            if ii == 0: input_coordinates[ii] = output_coordinates[ii]
            else: 
                input_coordinates[ii] = output_coordinates[ii] + (shift[0] + \
                                        shift[1]*output_coordinates[0] + \
                                        shift[2]*pow(output_coordinates[0],2))
        return 1


    def undistort_function(np.ndarray[double, ndim=1] shift):
        """This is the function callable from python."""
        cdef double* shift_data = <double*> shift.data
        return PyCObject_FromVoidPtrAndDesc(&_shift_function,
                                            shift_data,
                                            NULL)

    #my code calls geometric_transform from within a method to a cdef class that includes 
    #a bunch of irrelevant stuff, so this is more of an adaptation than an accurate reproduction

    def undistort_image(np.ndarray[double, ndim=2] image,
                        np.ndarray[double, ndim=1] trace_x,
                        np.ndarray[double, ndim=1] trace_y,
                        int fit_degree=2):
      cdef object poly = models.Polynomial1D(fit_degree)
      cdef object fitter = fitting.LinearLSQFitter()
      
      poly = fitter(poly, trace_x, trace_y)
      return geometric_transform(image, undistort_function(poly.parameters))

**Comment by sirpercival** [comment]
Any luck with this? I haven't been able to get it working (honestly I haven't been trying very hard...).

**Comment by rgommers** [comment]
no, no one is working on this as far as I know. I don't think I'll be able to look at this.
