### ISSUE TITLE
sourceforge drama

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4939]
I haven't been following this, but apparently it's a thing.

Here's a related numpy mailing list [thread](http://mail.scipy.org/pipermail/numpy-discussion/2015-May/072992.html). The [reactions](https://github.com/tmux/tmux/commit/d2b35e19cdd61d163d26c4babccc1550e72a9623) to a tmux commit that drops sourceforge have been positive, and a little pitchfork-y. For reference, here are the scipy pages [on sourceforge](http://sourceforge.net/projects/scipy/) and [on pypi](https://pypi.python.org/pypi/scipy/).

**Comment by rgommers** [comment]
Yep, we'll find an alternative. Marking this 0.16.0 to do this asap.

**Comment by tacaswell** [comment]
attn @mdboom @cgohlke mpl should be paying attention to this too.

**Comment by cgohlke** [comment]
I thought sourceforge backed down. See https://sourceforge.net/blog/third-party-offers-will-be-presented-with-opt-in-projects-only/

**Comment by argriffing** [comment]
> See https://sourceforge.net/blog/third-party-offers-will-be-presented-with-opt-in-projects-only/

For what it's worth, I see that scipy was at the top of their list of featured projects on Monday.
https://sourceforge.net/blog/project-of-the-week-june-1-2015-2/

**Comment by mdboom** [comment]
I tried to find a good -- and completely free -- alternative for hosting binaries about 3 years ago and came up empty.  Reading through the e-mail thread, I don't see that clear alternative either.  I'm happy to make the move -- but to what?  (github was an option for a while, but they've dropped the downloads feature).

**Comment by argriffing** [comment]
Would it be appropriate for pydata or numfocus to help with hosting?  On the other hand I don't understand the possible conflicts of interest.  For example I'd guess that if everything else is equal then Continuum and Enthought would rather have people use their installers.

**Comment by matthew-brett** [comment]
I bet Rackspace would help us out.  We're already using the space that Rackspace gave to scikit-learn to host wheels of various sorts.

**Comment by mdboom** [comment]
Rackspace is a good lead.  Is there a contact there or at scikit-learn that would be helpful?

I should clarify, too: at least for matplotlib, the hosting doesn't have to be completely free if there's some sort of moderate and predictable cost.  The thing that would be difficult for us to manage would be pay-for-bandwidth models and the surprises they can cause...

**Comment by rgommers** [comment]
I'm not a fan of setting up our own hosting - too much overhead. There's already way too many servers/sites to admin and too few people to do it.

Why not go Github only? So far I've only seen comments about how Github disabled Downloads, but they've replaced that with Releases already 2 years ago: https://github.com/blog/1547-release-your-software. It's well-documented in various places (https://help.github.com/articles/distributing-large-binaries/), has a sane API (https://developer.github.com/v3/repos/releases/#create-a-release) and can provide download counts (https://help.github.com/articles/getting-the-download-count-for-your-releases/).

**Comment by stonebig** [comment]
From a FailSafe point of view, shouldn't you plan to have always two distinct download organizations ?

**Comment by sebix** [comment]
There are two issues, one is authenticity and integrity, the other is reliability. Both is given for both github and bitbucket. @stonebig do you mean reliability with "FailSafe point of view"? If github fails, we have other problems than temporarily dysfunctional downloads (website for example :) ). As self-hosting costs, this is not really an option for Winpython, we have an estimated monthly traffic of about 7500GB (32700 downloads last month, estimated 230MB per download). I don't know numbers for scipy, but I expect they are significantly lower as the files are usually distributed pre-built by distributors.

OpenShift (by Redhat) has no data transfer / traffic limits, that sounds quite interesting, but it is limited to 1GB of storage.

**Comment by rgommers** [comment]
For Scipy the SF downloads total about 1 TB/month (66 Mb for Windows installers x 3000 downloads/week x 4 weeks/month).

1 GB of storage is not going to cut it for Scipy either.

**Comment by rgommers** [comment]
Two download places: not really important imho, if Github is offline we indeed have bigger issues than downloads.

**Comment by stonebig** [comment]
FailSafe in engineering sense: avoid catastrophic failures.
For example, having the current site as main download and a smaller one as a backup (or check-up) would be nice.
Same for pypi

**Comment by pv** [comment]
The failsafe engineering is outsourced to Github and python.org, and we save costs.
This has not been a problem so far with sourceforge, and I don't think it'll be a problem with github either.

**Comment by juliantaylor** [comment]
before using github it should be inquired what their 'average bandwidth' is that they refer to in their terms of service as the limit for downloads. Given their LFS free bandwidth is a measly 1GB/month, I think it would be weird if we would be able to use 1TB/month via their releases page for free.

**Comment by pv** [comment]
Ok, indeed, I did not realize our download volume is that high. I sent them a query on this.

**Comment by pv** [comment]
Didn't get very useful answers, just that they are not actively limiting the release download bandwidth currently, unlike for LFS.

**Comment by stonebig** [comment]
I can attach 450 Mo of binaries to a github tags https://github.com/winpython/winpython/releases/tag/1.1.20150512, so github is look like a simple FailSafe solution, without multiplicating Websites.

**Comment by stonebig** [comment]
otherwise, pyzo uses bitbucket since 2 years, with no apparent complaints.
https://bitbucket.org/pyzo/pyzo/downloads

**Comment by rgommers** [comment]
@stonebig thanks, that helps.

**Comment by stonebig** [comment]
The true Sourceforge drama is that it can be, and it is again, down since about 20 hours.

**Comment by matthew-brett** [comment]
Their recent record looks pretty bad as well : https://twitter.com/sfnet_ops

**Comment by rgommers** [comment]
SF is up now but refuses to let me create a 0.16.0 folder. So I won't....

https://github.com/scipy/scipy/releases/tag/v0.16.0 looks good.

**Comment by rgommers** [comment]
SF still doesn't let me create a https://sourceforge.net/projects/scipy/files/scipy/0.16.0/ folder, so I'll give up on that for now. Will change the advertised download site in setup.py to https://github.com/scipy/scipy/releases

**Comment by stonebig** [comment]
same issue for my project. Let's hope they will fully recover next week.

**Comment by stonebig** [comment]
since yesterday, sourceforge seems back 100% operationnal

**Comment by rgommers** [comment]
Thanks @stonebig. I have now uploaded everything for 0.16.0 at https://sourceforge.net/projects/scipy/files/scipy/0.16.0. From now on Github Releases should be leading (will fix the download URL in ``setup.py``), but plan to keep the SF page up to date as long as that's low overhead because (a) users might otherwise download an earlier release, and (b) otherwise SF might "re-package" for us.
