### ISSUE TITLE
Add mean Earth radius to constants

### ISSUE THREAD

**Issue by Felix-neko** [scipy/scipy#4943]
Cannot you please add mean earth radius to `constants`?

6,371,000 m is OK.

**Comment by rgommers** [comment]
Is there an authoritative source for this number? And does it make sense to add just this one, or is there a larger set of astronomy related metrics that would make sense?

**Comment by Felix-neko** [comment]
Well, we got it from MATLAB's Phased Array System Toolbox. 
http://www.mathworks.com/help/phased/ref/physconst.html


We need it to calculate reflections from the earth in one of our Python projects.

**Comment by Felix-neko** [comment]
If you want a more complete set, maybe a Particle Data Group constant set will be OK?

Alas, there is no mean Earth radius (only mean equatorial), but the handbook is well-known among scientists.

**Comment by rgommers** [comment]
Hmm, we now have a fairly well-defined set of fundamental physical constants; adding this one because Matlab has it is maybe a bit random. Can you run this by the scipy-dev mailing list?

**Comment by Felix-neko** [comment]
Well, if want a more balanced astronomical constant set, we can take NASA's one.
I think my Earth mean radius was taken from there.

http://nssdc.gsfc.nasa.gov/planetary/factsheet/earthfact.html

And the ones related with Sun and Moon, for example:

http://nssdc.gsfc.nasa.gov/planetary/factsheet/moonfact.html
http://nssdc.gsfc.nasa.gov/planetary/factsheet/sunfact.html

P.S. I don't even know where is the scipy-dev mailing list. Mayby you'll do it? Or give me a link?

**Comment by rgommers** [comment]
Would be great if you could do this @Felix-neko. List info is at http://scipy.org/scipylib/mailing-lists.html

I'm fine with expanding the scope of ``constants`` with those sets of data, because the maintenance overhead will be very low. I could imagine that people may find it too domain specific though and that it would better fit in AstroPy.

**Comment by ewmoore** [comment]
NASA says this about their fact sheets:
```
Most values listed in the factsheets are from the following sources:
  IAU/IAG Working Group Report, 2006
  Astronomical Almanac, 2000, 2001
  Global Earth Physics, American Geophysical Union, 1995
  Astrophysical Quantities, C.W. Allen, 1981, 2000
  Recent journal articles and personal communications
  
Note that the values listed on the factsheets are not "official" values, 
there is no single set of agreed upon values.  They are based on ongoing 
research and as such are under study and subject to change at any time.  
Every effort has been made to present the most up-to-date information, 
but care should be exercised when using these values. 
```

**Comment by aarchiba** [comment]
If you want more constants, Astropy has a reasonable selection, including
an Earth radius, tagged with units:
http://astropy.readthedocs.org/en/latest/constants/index.html

Anne

**Comment by rgommers** [comment]
@aarchiba thanks, that helps. If AstroPy already has them, probably not a good idea to add them to Scipy?

**Comment by jradavenport** [comment]
Agreed, no reason to make redundant constants for everything above the atmosphere if AstroPy is implementing them!

However, I don't know if there is a GeographyPy, etc... but the Earth radius is generally useful for many scientific disciplines, as is `c` and `G`, which SciPy includes.

I vote add `R_earth`

**Comment by tbroiles** [comment]
Was this ever implemented?  This is a very common unit in space physics and I think it brings value to scipy.

**Comment by jradavenport** [comment]
Note that I know of
👍

**Comment by rgommers** [comment]
> but the Earth radius is generally useful for many scientific disciplines, as is c and G, which SciPy includes.

There's an important difference there: ``c`` and ``G`` are fundamental constants, so uniquely defined and shipped as part of CODATA. ``R_earth`` isn't - https://nssdc.gsfc.nasa.gov/planetary/factsheet/earthfact.html alone has 4 different definitions for an earth radius (equatorial, polar, volumetric, and a rounded 6378 km). 

In the absence of follow-up on the mailing list and no consensus, I'm going to close this issue as wontfix.
