### ISSUE TITLE
enh: add a 'rogues' gallery of matrices, especially for unit testing matrix functions

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#4945]
https://github.com/macd/rogues

Some of the scipy matrix functions could benefit from more unit testing or perhaps benchmarking with matrices such as the ones provided by this matrix gallery.

The collection is MIT-licensed according to https://pypi.python.org/pypi/rogues.  On the other hand according to the docs the original sources appear to be [TOMS](http://toms.acm.org/) and GPL'd code (Test Matrix Toolbox) mentioned at the bottom of the web page of the successor toolbox http://www.maths.manchester.ac.uk/~higham/mctoolbox/.  According to licensing folklore, both of those original sources are off-limits to include in scipy for licensing reasons.  I don't know whether the 'rogues' author Don MacMillen has obtained special permission or licensing terms.

**Comment by ewmoore** [comment]
One way to simply move forward would be to run the tests that use these matrices if they are installed, much like the tests that use mpmath.

I agree that the MIT license on the rogues packages seems potentially dubious, particularly since at least the docstrings appear to be verbatim copies of the help text from the relevant matlab files. (I have not checked that this is true)

**Comment by WarrenWeckesser** [comment]
This sounds like a continuation of https://github.com/scipy/scipy/issues/1159; in addition to the matrices mentioned there, we now have `dft`, `helmert` and `invpascal`.

I suspect many of the matrices are easy to implement, so if the license of the "rogues" code is questionable, we could reimplement the most useful ones from scratch.

**Comment by argriffing** [comment]
> I suspect many of the matrices are easy to implement, so if the license of the "rogues" code is questionable, we could reimplement the most useful ones from scratch.

Yes I've started reimplementing a few of them by translating from the more solidly licensed julia implementation from the 'matrixdepot' project from Higham's lab.  Of course there is no guarantee that this will be finished soon or ever. If possible, I'd prefer to put this in a 'matrixdepot' submodule and keep the interface and the cryptic names, even if there is some overlap with less cryptically named functions in `scipy.linalg.special_matrices` that have more pythonic interfaces.

**Comment by matthew-brett** [comment]
More or less repeating what Eric said - but why not add `rogues` as a submodule, and then run tests against the generated matrices with travis?

**Comment by argriffing** [comment]
> why not add `rogues` as a submodule

The license issues...

**Comment by WarrenWeckesser** [comment]
We already have a `special_matrices` module.

**Comment by matthew-brett** [comment]
I don't think putting `rogues` as a submodule is going to make a difference for our license, it is just a shortcut for doing `git clone https://github.com/macd/rogues`.  `rogues` would not be installed with scipy, just for the extended tests.

**Comment by argriffing** [comment]
@matthew-brett Ah, I see. I thought you meant a Python [submodule](https://docs.python.org/2/tutorial/modules.html#packages) but you meant a git [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules).

**Comment by pv** [comment]
I'd still put -1 for gpl-ed git submodules. Having `try: import rogues;
HAVE_ROGUES=True; except: HAVE_ROGUES = False` in tests should however
be fine.

**Comment by WarrenWeckesser** [comment]
This suggestion didn't go anywhere, and there hasn't been any demand for this since 2015, so closing.  If there is interest in extending our collection of special matrices in the future, new issues containing the enhancement requests can be created.
