### ISSUE TITLE
scipy.sparse matrix broken after assign division

### ISSUE THREAD

**Issue by derDavidT** [scipy/scipy#4946]
Sparse matrizes of type numpy.int32 get messed up when using assign division (i.e. `A /= 2.`).
I'm not sure if this is linked to #2128 and #2937.
See code below for details:

```python
# -*- coding: utf-8 -*-
"""
using python 2.7.9
      scipy 0.15.1
Summary:
A) sparse matrizes of type 'numpy.int32' get messed up when using
   assigning division (i.e. '/=')
   regardless of using 'from __future__ import division'
B) normal math (i.e. 'A = A / 2') seems to work
C) sparse matrizes of type 'numpy.float64' seem to work as expected
D) different types of sparse (e.g. DIA vs. COO) get messed up differently
"""

# (de-)activate 'future'-import for more confusion
from __future__ import division
import scipy.sparse as spa

m = 5

# create int sparse matrix
A = spa.spdiags([[1]*m, [-1]*m], [-1, 1], m, m)
print A
A /= 2.  # assign operator does not work!
print A

# create int sparse matrix
B = spa.spdiags([[1]*m, [-1]*m], [-1, 1], m, m)
print B
B = B / 2  # 'normal' operator works
print B

# create float sparse matrix
C = spa.spdiags([[1.]*m, [-1.]*m], [-1, 1], m, m)
print C
C /= 2  # assing operator works
print C

# cast int sparse DIA matrix into COO
D = spa.spdiags([[1]*m, [-1]*m], [-1, 1], m, m)
D = D.tocoo()
print D
D /= 2.  # assign operator does not work!
print D
```

**Comment by argriffing** [comment]
Numpy doesn't like this idea either. I think it's the intended behavior, if in-place operations like `/=` are not allowed to change the array's dtype.
```python
>>> from __future__ import division
>>> import numpy as np
>>> A = np.array([1, 2, 3])
>>> A /= 2.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''
>>> A = A / 2
>>> A
array([ 0.5,  1. ,  1.5])
```

**Comment by derDavidT** [comment]
Thanks for the fast reply. Still, I think an appropiate error should be thrown (as is the case in your example). I guess few people would look at something as inconspicuous as `A /= 2.` when debugging their code. Especially because there are many occasions in which it would work as expected.

**Comment by argriffing** [comment]
Does the numpy example give the error for you?  Which numpy version are you using? Searching for that error, I found https://github.com/matplotlib/matplotlib/issues/1258/ which suggests the behavior changed between numpy 1.6 and 1.7.
```python
>>> from __future__ import division
>>> import numpy as np
>>> np.__version__
'1.6.2'
>>> A = np.array([1, 2, 3])
>>> A /= 2.
>>> A
array([0, 1, 1])
```

**Comment by derDavidT** [comment]
Well, your numpy example yields no error, using numpy 1.9.2.
```python
>>> from __future__ import division
>>> import numpy as np
>>> np.__version__
'1.9.2'
>>> A = np.array([1, 2, 3])
>>> A /= 2.
>>> A
array([0, 1, 1])
```

**Comment by argriffing** [comment]
Hmm I guess the change was more recent.
```python
>>> from __future__ import division
>>> import numpy as np
>>> np.__version__
'1.10.0.dev0+7d86792'
>>> A = np.array([1, 2, 3])
>>> A /= 2.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''
```

**Comment by argriffing** [comment]
Yeah this was changed in https://github.com/numpy/numpy/pull/4671, so I guess it's only in the development version. This [discussion](https://github.com/numpy/numpy/pull/4670) mentions delaying it from 1.9 to 1.10, basically to keep backwards compatibility for a bit longer until libraries have caught up.

**Comment by derDavidT** [comment]
Okay, perfect. So it will be adressed later on. I've closed this issue already; thanks again.

As a sidenote: `numpy` seems to default to float64 (at least `numpy.eye` does). Such behaviour within `scipy.sparse` would be just a tiny bit more user-friendly...

**Comment by argriffing** [comment]
> `numpy` seems to default to float64 (at least `numpy.eye` does). Such behaviour within `scipy.sparse` would be just a tiny bit more user-friendly...

The version that I'm using already does this:
```python
>>> import scipy
>>> scipy.__version__
'0.17.0.dev0+89d32a8'
>>> import scipy.sparse
>>> I = scipy.sparse.eye(5)
>>> I
<5x5 sparse matrix of type '<type 'numpy.float64'>'
        with 5 stored elements (1 diagonals) in DIAgonal format>
>>> I.A
array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])
```

**Comment by derDavidT** [comment]
nice!
