### ISSUE TITLE
Finding Time Dealy using GCC-Phat - contribution doubt

### ISSUE THREAD

**Issue by bhargavvader** [scipy/scipy#4948]
I've been using an implementation of GCC-PHAT to find time delay between two sound files, and then the angle (localisation) using SciPy and NumPy. I can imagine cross correlation and identifying time delay might be useful in general, so I thought I would contribute by helping (or trying) to make them SciPy functions. How do I go about doing this? 
Also, would this be useful at all to SciPy folks or should I just put up my implementation elsewhere?
Also, how do I start contributing if I want to do this?

**Comment by rgommers** [comment]
Hi @bhargavvader, that sounds potentially interesting. It would be good to bring this up on the scipy-dev mailing list (see http://scipy.org/scipylib/mailing-lists.html); that's where decisions on adding new features are made. Some links and context information may help, I had to do a bit of digging.

The original paper from Knapp and Carter (see http://www.xavieranguera.com/phdthesis/node92.html) is heavily cited, which is a good sign. Looking at the citing papers it seems the applicability is broader than just audio correlation from multiple receivers. 

This may also help: http://dsp.stackexchange.com/questions/8732/generalized-cross-correlation

**Comment by rgommers** [comment]
When you send an email to the list, a link to code you already have would also be useful.

**Comment by bhargavvader** [comment]
Cool, I'll do that!

**Comment by rgommers** [comment]
Numpy and the Python stdlib are dependencies of Scipy, so using those is fine. Using fft functions from ``numpy.fft`` or ``scipy.fftpack`` is also fine. Using functions from other packages that aren't already dependencies of Scipy is usually not OK.

**Comment by rgommers** [comment]
And yes, fine to ask that here. On the mailing list would also have been fine.

**Comment by rgommers** [comment]
no update in 4 years, so I'll close this issue. thanks @bhargavvader
