### ISSUE TITLE
DOC: stats: improvement suggestions for tutorial

### ISSUE THREAD

**Issue by OceanWolf** [scipy/scipy#4952]
First of all, I really enjoy reading through the stats tutorial, for the most part it makes a lot of sense.  However when it starts to get into detail I start having problems.  I guess I have a general lack of confidence when it comes to stats, always preferring mechanics.

Thus for me (and perhaps others) would benefit from either a bit more explanation and/or examples and/or a cleanup of the terminology used. For example I stumble reading the `Subclassing rv_discrete` and `T-test and KS-test` sections:
## Subclassing rv_discrete

```
The pvalue in this case is high, so we can be quite confident that our random sample was
actually generated by the distribution
```

Conclusion: a high pvalue means we feel confident about the result.
## T-test and KS-test

```
The pvalue is 0.7, this means that with an alpha error of, for example, 10%, we cannot
reject the hypothesis that...
```

Conclusion: a high pvalue means we **don't** feel confident about the result.

---

Do you see what I mean?  Somewhere there I feel a bit of logic goes missing.  It explains `Why we test`, but it doesn't fully explain `What we test`, which hypothesis do we currently test in the current example?

Also links to wikipedia would help and perhaps a brief (5-10 words) summary to explain the underlying concept of the methods used.

Also other problems, the source links give 404 page not found errors, and the inline source could look a little tidier, these problems though I can help with and will submit a PR as/when I find some time.

Thanks,
OceanWolf

**Comment by ev-br** [comment]
Docs improvements are always welcome
