### ISSUE TITLE
Johnson SB has incorrect name

### ISSUE THREAD

**Issue by gt6989b** [scipy/scipy#4955]
Name parameter of the Johnson SB distribution is supplied as name='johnsonb' instead of name='johnsonsb' in distributions.py line 3850

**Comment by ev-br** [comment]
What version of scipy are you using? distributions.py has been split a couple of releases back, and this particular bug has been fixed in https://github.com/scipy/scipy/commit/13c716e6e027c9d35037b0dbd214f33cc8b6e5bf
