### ISSUE TITLE
Documentation error in `scipy.special.bi_zeros`

### ISSUE THREAD

**Issue by moble** [scipy/scipy#4956]
The documentation for this function says

    Compute the zeros of Airy Functions Bi(x) and Bi’(x), b and b’ respectively, and the associated values of Ai(b’) and Ai’(b).

Those last two should evidently be `Bi` and `Bi'`:

    Compute the zeros of Airy Functions Bi(x) and Bi’(x), b and b’ respectively, and the associated values of Bi(b’) and Bi’(b).

I've checked that the latter is the actual behavior of this function with this code:

```python
import scipy.special as sps
n = 20
bi_z = sps.bi_zeros(n)
for k in range(n):
    bi, bip = bi_z[0][k], bi_z[1][k]
    Bi_bi, Bip_bi = sps.airy(bi)[2:]
    Bi_bip, Bip_bip = sps.airy(bip)[2:]
    assert abs(Bi_bi)  < 3e-12, ('Bi_bi',k,Bi_bi)
    assert abs(Bip_bip) < 5e-11, ('Bip_bip',k,Bip_bip)
    assert abs(Bip_bi-bi_z[3][k]) < 3e-12, ('Bip_bi',k,Bip_bi,bi_z[3][k])
    assert abs(Bi_bip-bi_z[2][k]) < 5e-11, ('Bi_bip',k,Bi_bip,bi_z[2][k])
```

**Comment by ev-br** [comment]
Thanks for the report @moble. Would you be interested in sending a PR with a fix?
Adding a small example along the lines of what you write above could be a nice bonus.

**Comment by moble** [comment]
Sure.  Working on it now.
