### ISSUE TITLE
Docstring for `pbvv_seq` is wrong

### ISSUE THREAD

**Issue by moble** [scipy/scipy#4957]
[The docstring](https://github.com/scipy/scipy/blob/v0.14.0/scipy/special/basic.py#L956) for `pbvv_seq` seems to have been copied from `pbdv_seq`.  It currently says

    Compute sequence of parabolic cylinder functions Dv(x) and their derivatives for Dv0(x)..Dv(x) with v0=v-int(v).

It should say

    Compute sequence of parabolic cylinder functions Vv(x) and their derivatives for Vv0(x)..Vv(x) with v0=v-int(v).

I checked that the function gives the latter behavior with

```python
import numpy as np
import scipy.special as special
N = 10
for z in 10*np.random.random(20)-5:
    assert np.allclose(np.array(special.pbvv_seq(N, z)), np.array([special.pbvv(n, z) for n in range(N+1)]).T, rtol=2e-12, atol=0)
```

**Comment by ev-br** [comment]
Improving the docstring would be great. Here, I suppose, it would be good to rewrite the docstring in the numpydoc format and add a reference to the precise definition (DLMF, A&S).

**Comment by moble** [comment]
Will do.  However, DLMF uses [different notation](http://dlmf.nist.gov/12.1) for the parabolic cylinder functions.  Just from googling around, it looks like this notation might come from [NIST's Dataplot package](http://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/pb.htm).  Would this be the right reference?

(I'm not actually using these functions; I've just been scraping docstrings for an ipython/jupyter notebook [menu plugin I'm making](https://github.com/moble/jupyter_boilerplate), so I don't really know anything about these particular functions.)

**Comment by moble** [comment]
Upon closer inspection, it looks like `specfun` functions come from ["Computation of Special Functions"](http://jin.ece.illinois.edu/specfunc.html) by Zhang and Jin, and docs actually exist in the `specfun/specfun.f`.  Adding all those docstrings is a bit much for me this lovely Sunday afternoon, so I'll just throw in a reference section to each relevant docstring, and make my improvements to the docstrings I was already correcting.
