### ISSUE TITLE
stats.spearmanr - wrong input arguments description

### ISSUE THREAD

**Issue by Sebascn** [scipy/scipy#4965]
In the axis part: 
axis : int or None, optional
        If axis=0 (default), then each column represents a variable, with
        observations in the rows. If axis=0, the relationship is transposed:
        each row represents a variable, while the columns contain observations.
        If axis=None, then both arrays will be raveled.

version 0.15.0

Issue: 
Twice axis=0, plus based on my observation it works the other way round (or correct me please)

I think it should be: 
axis : int or None, optional
        If axis=0 (default), then each ROW represents a variable, with
        observations in the COLUMNS. If axis=1, the relationship is transposed:
        each COLUMN represents a variable, while the ROWS contain observations.
        If axis=None, then both arrays will be raveled.

My code: 
var1 = [1, 1, 1, 1, 1, 2]
var2 = [5, 5, 5, 5, 5, 10]

from scipy.stats import spearmanr
cor, p = spearmanr(var1,var2)

print(cor)
OUTPUT:
1.0
_____

My code2: 
var1 = [1, 1, 1, 1, 1, 2]
var2 = [5, 5, 5, 5, 5, 10]

from scipy.stats import spearmanr
cor, p = spearmanr(var1,var2,0)

print(cor)
OUTPUT:
1.0
_____

My code3: 
var1 = [1, 1, 1, 1, 1, 2]
var2 = [5, 5, 5, 5, 5, 10]

from scipy.stats import spearmanr
cor, p = spearmanr(var1,var2,1)

print(cor)
OUTPUT:
ValueError: axis must be less than arr.ndim; axis=1, rank=1.

**Comment by rgommers** [comment]
@Sebascn this issue is about documentation only right? I'm not sure why you included the ValueError for code3; that's expected (``axis=1`` doesn't work for 1-D inputs).

**Comment by Sebascn** [comment]
I was trying to state that there is twice if axis = 0 instead of once axis = 0 and axis = 1 and I was trying to come up with a proposition of how it should be, what should axis = 0 mean and axis = 1 mean, did u miss that there is actually some typo most likely in the documentation? 

There can be mistake at my side but I really get this feeling.

**Comment by rgommers** [comment]
No, I agree that the docs contain an error and should be fixed. I was just checking if you thought there was a separate second issue in the code itself.

**Comment by Sebascn** [comment]
No, the code 3 was there to prove that my suggestion of what argument should mean columns and what argument should mean rows should be.

**Comment by rgommers** [comment]
Okay, thanks for confirming. Should be straightforward to fix. I'm afraid I won't get around to it for the next weeks though, so a PR would be very welcome.
