### ISSUE TITLE
sparse __lt__  bug

### ISSUE THREAD

**Issue by cgcgbcbc** [scipy/scipy#4973]
```python
from scipy.sparse import dok_matrix
import numpy as np
b = dok_matrix((5,5), dtype=np.float32)
print(b<0)
```
result:
```
Traceback (most recent call last):
  File "sparse_bug.py", line 7, in <module>
    print(b < 0)
  File "scipy/lib/python2.7/site-packages/scipy/sparse/base.py", line 255, in __lt__
    return self.tocsr().__lt__(other)
  File "scipy/lib/python2.7/site-packages/scipy/sparse/compressed.py", line 315, in __lt__
    "Comparing a sparse matrix with a scalar "
  File "scipy/lib/python2.7/site-packages/scipy/sparse/compressed.py", line 291, in _inequality
    return self._binopt(other_arr, op_name)
  File "scipy/lib/python2.7/site-packages/scipy/sparse/compressed.py", line 1103, in _binopt
    indptr, indices, data)
TypeError: Cannot cast array data from dtype('float32') to dtype('int64') according to the rule 'safe'
```

Or this is a bug in `scipy.optimize._linprog` since it use `_count_nonzero(bub < 0)`

version: 
```
numpy==1.9.2
scipy=0.15.1
```

**Comment by argriffing** [comment]
I see this too. A workaround could be to compare vs 0.0 instead of vs. 0?

**Comment by cgcgbcbc** [comment]
> A workaround could be to compare vs 0.0 instead of vs. 0?

That works, but in `scipy.optimize.linprog`, it compare vs `0` no matter what data type is, and I should call `todense()` on the sparse matrix, before pass it to the `linprog` function, and `simplex` method for LP won't work for that case, if the sparse matrix is very large when convert to dense one.

**Comment by emunsing** [comment]
Same issue- this eliminates the benefits of using sparse matrices if you want to use  scipy.optimize.linprog... and I also have some issues getting cvxopt to initialize using a sparse matrix, so I seem to be out of luck...

**Comment by perimosocordiae** [comment]
I just opened a PR which fixes this issue. The relevant changes are in 57e099b283308955b622c0e8ccbaac1d3084fc8e.

**Comment by pv** [comment]
Closing (was fixed).
