### ISSUE TITLE
Non-finite values of hypergeom.logsf and slow evaluation

### ISSUE THREAD

**Issue by joshlk** [scipy/scipy#4982]
For some small survival function values for the hypergeom distribution are evaluated as -inf. For example:

``` python
from scipy.stats import hypergeom

k = 1e4
M = 1e7
n = 1e6
N = 5e4

hypergeom.logsf(k, M, n, N)
-inf

hypergeom.sf(k, M, n, N)
0.0
```

R properly calculates the value (using the same inputs):

``` R
phyper(k, n, M-n, N, lower.tail=FALSE, log.p=TRUE)
-2239.771

phyper(k, n, M-n, N, lower.tail=FALSE, log.p=FALSE)
0
```

The scipy method is also slow compared with the R version. Scipy takes 8.8 ms while R takes 5.7 micro seconds - 100 times faster.

In Scipy, the logsf is calculated by first calculating the sf and then taking the log. The non-log output from Scipy is 0 so taking the log of this is just going to give -inf.

I am not sure how R calculates the value, but a more direct approach might be the following: the log survival function can be calculated via (see: https://en.wikipedia.org/Hypergeometric_distribution - note that the symbols have different meanings in the wiki page):

![image](https://cloud.githubusercontent.com/assets/5648645/8283150/5a62380a-18ed-11e5-8a2d-770a42ade98e.png)

Which equals:
gammaln(1+M-n) + gammaln(1+n) + gammaln(1+M-N) + gammaln(1+N) - (gammaln(2+k) + gammaln(1+M) + gammaln(-k+n) + gammaln(2+k+M-n-N) + gammaln(-k+N)) +
![image](https://cloud.githubusercontent.com/assets/5648645/8283162/6bef1a2a-18ed-11e5-883c-5d7af68a18aa.png)

All that would be required is to implement the hypergeometric series 3F2. The package mpmath have done this and there method is described here: http://fredrikj.net/blog/2014/06/easy-hypergeometric-series-at-unity/

I could implement it if you think this is the right direction

``` python
print scipy.__version__
0.15.1
```

**Comment by argriffing** [comment]
Here's another thread related to numerical issues with the hypergeometric distribution: https://github.com/scipy/scipy/issues/2238.

**Comment by ev-br** [comment]
I wonder how the approach for `3F2(..., 1)` fares in double precision.

**Comment by pv** [comment]
First thing to check for the numerical precision question: for each
summation for-loop in the code, compare the absolute value of the
largest term to the absolute value of the sum. If
abs(sum)<<abs(largest_term), you have a big numerical problem.

**Comment by joshlk** [comment]
Stepping through the _sf function, it creates all pmf values and then sums them. So for the above example it creates an array representing the range of k-values under the tail from k=10001 to k=50000. It then calculates the pmf, however all these values evaluate to 0. So the sum is 0 and the largest term is 0

**Comment by pv** [comment]
Yes. However, I meant the general case in the evaluation of 3F2 via the
method suggested above.

**Comment by joshlk** [comment]
Which sum are you referring to: the sum required to evaluate the 3F2
function or the sum of all the gamma functions plus the 3F2?

On 22 June 2015 at 16:27, Pauli Virtanen <notifications@github.com> wrote:

> Yes. However, I meant the general case in the evaluation of 3F2 via the
> method suggested above.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scipy/scipy/issues/4982#issuecomment-114154135>.
>



-- 
*Josh Levy-Kramer*
Data Scientist @ Starcount



[image: starcount-logo]



*UK Office *+44 (0)203 770 7554 |  *Mobile *0781 7970 736 | *Address:  *Henry
Wood House, 2 Riding House Street, London, W1W 7FA

*Singapore: Office *+65 6595 6254 | *Address**: *The Nomad Offices, Suntec
City 9 Temasek Boulevard 09-01 Suntec Tower Two Singapore 038989

*www.starcount.com* <http://www.starcount.com/>

*Confidentiality*

*The information contained in this e-mail is confidential, may be
privileged and is intended solely for the use of the named addressee.
Access to this e-mail by any other person is not authorised. If you are not
the intended recipient, you should not disclose, copy, distribute, take any
action or rely on it and you should please notify the sender by reply. Any
opinions expressed are not necessarily those of the company.*


*We may monitor all incoming and outgoing emails in line with current
legislation. We have taken steps to ensure that this email and attachments
are free from any virus, but it remains your responsibility to ensure that
viruses do not adversely affect you.*

**Comment by joshlk** [comment]
Ok I will have a look

**Comment by pv** [comment]
All of the sums appearing in `hyper1`, `gammaprod_series` and
`exp_series` on Fredrik's page. Checking numerical stability on already
on a coarse level may require some work as this should be done
analytically (in order to cover the parameter ranges necessary).

**Comment by joshlk** [comment]
Sorry do you mind elaborating on that as I don't think I totally understand
what you mean

On 22 June 2015 at 16:50, Pauli Virtanen <notifications@github.com> wrote:

> All of the sums appearing in `hyper1`, `gammaprod_series` and
> `exp_series` on Fredrik's page. Checking numerical stability on already
> on a coarse level may require some work as this should be done
> analytically (in order to cover the parameter ranges necessary).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scipy/scipy/issues/4982#issuecomment-114161265>.
>



-- 
*Josh Levy-Kramer*
Data Scientist @ Starcount



[image: starcount-logo]



*UK Office *+44 (0)203 770 7554 |  *Mobile *0781 7970 736 | *Address:  *Henry
Wood House, 2 Riding House Street, London, W1W 7FA

*Singapore: Office *+65 6595 6254 | *Address**: *The Nomad Offices, Suntec
City 9 Temasek Boulevard 09-01 Suntec Tower Two Singapore 038989

*www.starcount.com* <http://www.starcount.com/>

*Confidentiality*

*The information contained in this e-mail is confidential, may be
privileged and is intended solely for the use of the named addressee.
Access to this e-mail by any other person is not authorised. If you are not
the intended recipient, you should not disclose, copy, distribute, take any
action or rely on it and you should please notify the sender by reply. Any
opinions expressed are not necessarily those of the company.*


*We may monitor all incoming and outgoing emails in line with current
legislation. We have taken steps to ensure that this email and attachments
are free from any virus, but it remains your responsibility to ensure that
viruses do not adversely affect you.*

**Comment by pv** [comment]
The error estimate for relative rounding error in numerically evaluated
sums is roughly
.
err = eps * abs(max_term) / abs(sum_value)
.
where eps is the machine epsilon (1e-16). For sums where the resulting
value is much smaller than the maximum term, i.e. sums with alternating
signs, all precision can be lost and the result become garbage even if
the expressions are in principle mathematically exact.
.
Now, the question is whether this can happen in the proposed way to
evaluate 3F2. mpmath can work around issues like this just by increasing
the calculation precision, and this is what its hypergeom implementation
does also in practice AFAIK (which is why I'm asking), but it is not
possible to do this in floating point implementation. So to be sure
whether the algorithm is OK on a basic level for fp implementation,
you'd need to check whether you have problematic summations in it. If
you have many parameters, it is not very easy to check for this only by
trying different parameter combinations, but looking at the structure of
the terms summed may give some information.

**Comment by joshlk** [comment]
An easier way would be just to adapt the _sf code to compute _logpmf and then use logsumexp:

```python
from scipy.stats import hypergeom
from scipy.misc import logsumexp
import numpy as np

k = 1e4
M = 1e7
n = 1e6
N = 5e4

# Adapted from:
# scipy.stats._discrete_distns.hypergeom_gen._sf
quant, tot, good, draw = k, M, n, N
k2 = np.arange(quant + 1, draw + 1)
logpmf = hypergeom._logpmf(k2, tot, good, draw)   # Evaluate the log-pmf instead
logsf = logsumexp(logpmf)
print logsf
-2239.77124993
```

In the example above it gives the same answer to R.

**Comment by joshlk** [comment]
Should I make these changes and commit to git?

**Comment by pv** [comment]
@joshlk: yes, that would be helpful. (Please [see here](https://help.github.com/articles/using-pull-requests/) and [here](https://github.com/scipy/scipy/blob/master/HACKING.rst.txt) in case you didn't do it before.)

**Comment by ev-br** [comment]
The logsf precision loss has been fixed in gh-5010: 

```
>>> from scipy.stats import hypergeom
>>> k, M, n, N = 1e4, 1e7, 1e6, 5e4
>>> hypergeom.logsf(k, M, n, N)
-2239.771249927684
```

Performance -wise: [this python loop](https://github.com/scipy/scipy/blob/master/scipy/stats/_discrete_distns.py#L351) can surely be refactored into something more numpy-like.

**Comment by sethtroisi** [comment]
Patch claiming to fix this issue was merged and sample code now produces correct result

**Comment by tylerjereddy** [comment]
If the patch was recent (for upcoming release), please do add the milestone to the closed issue(s).

**Comment by sethtroisi** [comment]
@tylerjereddy I'll try to pay attention, in this case the PR was https://github.com/scipy/scipy/pull/10091 submitted ~10 months ago

I'm doing a triage over the oldest updated bugs so it's unlikely I'll add milestones to many of them.

**Comment by tylerjereddy** [comment]
yeah, thanks, I noticed; if it looks recent maybe just do a quick--it saves me time :)
