### ISSUE TITLE
scipy.optimize.minimize bug with _minimize_slsqp in python3?

### ISSUE THREAD

**Issue by hezooo** [scipy/scipy#4983]
The following code runs perfectly using python 2.7. Running the same code using python3 it crashes.

    import numpy as np
    from scipy.optimize import minimize

    def find_admissible(C, c, D, d):
        """Gibt einen zulaessigen Punkt x mit
            Cx + c = 0  # falls C nicht None
            Dx + d <= 0
        zurueck"""
        def f(x):
            return x.dot(x)

        def g(x):
            return C.dot(x) + c

        def h(x):
            return -D.dot(x) - d

        cons = {'type': 'ineq', 'fun': h}
        if C is not None:
            cons = ({'type': 'eq', 'fun': g}, cons)

        res = minimize(f, np.zeros(2), method='SLSQP', constraints=cons)
        if not res.success:
            print("cannot find admissible point")
            exit()
        return res.x

    def run_test():
        C = np.eye(2)
        c = np.array([0, 0])
        D = np.concatenate((np.eye(2), np.ones((1, 2))))
        d = np.array([0, 0, 0])
        print(find_admissible(C, c, D, d))

    if __name__ == "__main__":
        run_test()

Adding a print(a_eq) to line 394 in _minimize_slsqp in slsqp.py shows, that it seem that the inequality constraints are also taken as equality constraints.

I have tested this with scipy 0.12.0 and scipy 0.13.3.

**Comment by pv** [comment]
Upgrade to 0.14.1 or newer.

**Comment by hezooo** [comment]
Thank you.
