### ISSUE TITLE
Qhull crashes for more than 2**24 points

### ISSUE THREAD

**Issue by pv** [scipy/scipy#4985]
Qhull apparently has limits on how many input points it can handle. Scipy should check that before trying to use it for too big problems.
http://mail.scipy.org/pipermail/scipy-dev/2015-June/020820.html

**Comment by sethtroisi** [comment]
I believe that url points at https://mail.python.org/pipermail/scipy-dev/2015-June/020835.html

Closing this as duplicate of #6820 which has better links and a higher threshold suggestion.
