### ISSUE TITLE
Alternative RandomState-type objects

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#4989]
This is prompted by enhancement request part of https://github.com/scipy/scipy/pull/4984#discussion_r32984650 and general difficulties in adding or changing numpy.random distributions due to strict backwards compat. (https://github.com/numpy/numpy/issues/2047, https://github.com/numpy/numpy/issues/5851 and https://github.com/numpy/numpy/pull/5872 to name a few).

In scipy.stats, distributions accept the `random_state` argument which can be either a`numpy.random.RandomState` instance, or an integer (in which case it's interpreted as a seed to seed a new RandomState). 

We can also extend this to accept an arbitrary callable to be interperted as a duck-typed RandomState instance. This way, 
- we can easily switch the sources of random variates (ziggurats, stick_breaking_dirichlet etc) 
- users can use their own generators

The implementation for us is a trivial two-line addition to a little utility which was copied verbatim from scikit-learn, https://github.com/scipy/scipy/blob/master/scipy/_lib/_util.py#L73.

Implementing such generators is likely much simpler than implementing full-fledged RandomState replacements since each of them only needs one method, named identically to a RandomState method a particular class impersonates: `stick_breaking_dirichlet` only needs to have  `dirichlet` method, `ziggurat_normal` only needs `standard_normal` and so on.

**Comment by ev-br** [comment]
One more ticket which might be relevant: https://github.com/scipy/scipy/issues/2477

**Comment by rgommers** [comment]
If we do it like that, then some work is needed for docs/tests. In the docstring of every distribution that uses ``random_state``, the current description needs to be changed from the generic one to a description of what properties a custom ``random_state`` has to possess for it to work. Then there also needs to be a unit test for each of those distribution, which uses such a ducktyped instance. I think we're using a decent fraction of all methods, so several dozens of classes to modify:

    In [1]: len(dir(np.random.RandomState))
    Out[1]: 66

Alternatively, the utility function could explicitly allow this only for whitelisted distribution names. That means that we'd have to move the utility to ``stats`` and probably that custom ``rv_generic`` subclasses can't be whitelisted.

**Comment by ev-br** [comment]
I don't think we need to go that far. Granted, this somewhat exposes implementation details (which scipy distribution uses which numpy distribution), but I believe we can clearly document that it's a have-to-look-at-the-source-code, use-at-your-own-risk feature and that we are only going to support those generators which we provide ourselves.  

For a user, this is a clear cost-benefit balance and IMO an option of wrapping eg an implementation from GSL or Boost or whatever license-incompatible library (eg, suggestions from #2477 are not AFAICS) can be attractive even in the face of a possible need to work around our changes in scipy (and not that we're very likely to massively change the generation of random variates).

**Comment by rgommers** [comment]
That doesn't really work imho. Either we say it's okay to ducktype, and then we have to make sure not to break user code in the next release, or we say it's not okay.

With custom subclasses of ``stats.gaussian_kde`` we had the same issue. Once code is out there that uses a feature (documented or not), people are going to be unhappy if we break that code.

**Comment by rgommers** [comment]
since gh-10378 we support the new numpy generators. @ev-br can we close this?
