### ISSUE TITLE
Wrap LAPACK.dgesvd for singular value decomposition

### ISSUE THREAD

**Issue by eladnoor** [scipy/scipy#4994]
Currently, scipy only wraps dgesdd, which does essentially the same thing, but makes very mild assumptions about floating point arithmetic. At least in some cases, this approach fails and dgesvd works more robustly.
Also, it seems that other platforms (e.g. Matlab and Octave) use the dgesvd implementation.

http://www.netlib.org/lapack/explore-html/db/db4/dgesdd_8f.html

http://www.netlib.org/lapack/explore-html/d8/d2d/dgesvd_8f.html

**Comment by rgommers** [comment]
The Cython LAPACK wrappers that are new in 0.16.x do wrap ``dgesvd``.

**Comment by rgommers** [comment]
The assumption:

    The divide and conquer algorithm makes very mild assumptions about
     floating point arithmetic. It will work on machines with a guard
     digit in add/subtract, or on those binary machines without guard
     digits which subtract like the Cray X-MP, Cray Y-MP, Cray C-90, or
     Cray-2. It could conceivably fail on hexadecimal or decimal machines
     without guard digits, but we know of none.

Is that really a concern? Do you have an example where the assumption doesn't hold?

**Comment by eladnoor** [comment]
This is curious. I was trying to reproduce the problem I had before but it now seems that my results are essentially the same for both implementations. I'm not sure if something changed since I updated all relevant python packages. Sorry about this.

Regardless, when A has redundancy in the singular values, dgesvd and dgesdd return different representations of the subspaces (of course, the SVD solution is not unique in this case, so this is expected). However, it might be important to have dgesvd available in Numpy for cases where one would like to compare results to Matlab/Octave directly.

I did not find the wrapped _dgesvd_ function in 0.17 [SciPy](http://docs.scipy.org/doc/scipy-dev/reference/linalg.lapack.html#module-scipy.linalg.lapack) while _dgesdd_ is still there. Could you point me to the right place?

**Comment by pv** [comment]
*gesvd is not wrapped on Python level on Scipy 0.17.dev. An ABI-stable
pointer is however exported to Cython, however:
http://docs.scipy.org/doc/scipy-dev/reference/linalg.cython_lapack.html
.
Adding the routine also to scipy.linalg.lapack would in principle be
straightforward; cf.
https://github.com/scipy/scipy/blob/master/scipy/linalg/flapack.pyf.src#L555
Due to historical reasons, these wrappers are not autogenerated, and do
not consequently cover all of LAPACK.

**Comment by Eric89GXL** [comment]
I'm hitting an issue with my code, which uses lots of SVD calls, that I get a fair number of `numpy.linalg.linalg.LinAlgError: SVD did not converge`'s. I'm using Anaconda with MKL, and have [opened an issue with the Anaconda folks] (https://github.com/conda/conda/issues/2244), but I don't know how long it will take them to sort it out.

In the meantime, I'd like to try adding an option to compute SVD using the alternate algorithm. We could add a `kwarg` to `linalg.svd(..., method='dgesdd' | 'dgesvd')` (or really something more human-readable) for it. WDYT? It would be a potential workaround for this issue, and expose the alternative algorithm for people who want to use it.

If that's a no-go, I'd like to at least modify `scipy`, if necessary, to make my own derivative version of `svd` (it's not many lines anyway) that would do it. I take it that adding it to `scipy.linalg.lapack`, as mentioned in @pv's most recent comment, would do it?
