### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by bpacker** [scipy/scipy#4999]
I want to use [Sourcegraph](https://sourcegraph.com) for scipy code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/scipy/scipy. (It should only take 30 seconds.)

Thank you!

**Comment by rgommers** [comment]
That seems to be a useful site. Does anyone see a problem with enabling this?

**Comment by ev-br** [comment]
+1, why not

**Comment by rgommers** [comment]
done

**Comment by rgommers** [comment]
didn't need any Github permissions, so anyone could have done this
