### ISSUE TITLE
Scipy sparse matrices seem to have large overhead

### ISSUE THREAD

**Issue by teh** [scipy/scipy#5004]
I understand that multiplying sparse matrices requires a bit more checking but 100-200x slower seems excessive.  

```
In [14]: import scipy.sparse as sparse
In [15]: m11 = sparse.csc_matrix(numpy.eye(1))
In [16]: m11.dot(m11)
Out[16]: 
<1x1 sparse matrix of type '<type 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Column format>
In [17]: %timeit m11.dot(m11)
1000 loops, best of 3: 181 µs per loop
```

compare to:

```
In [18]: import numpy
In [19]: m11 = numpy.eye(1)
In [20]: m11.dot(m11)
Out[20]: array([[ 1.]])
In [21]: %timeit m11.dot(m11)
The slowest run took 16.23 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 984 ns per loop
```

Running:

```
In [22]: scipy.__version__
Out[22]: '0.15.1'
```

**Comment by argriffing** [comment]
I can confirm this has ~100x overhead for such a small matrix. On my system, nearly half of the slowness is in [`check_format`](https://github.com/scipy/scipy/blob/maintenance/0.16.x/scipy/sparse/compressed.py#L126).

**Comment by perimosocordiae** [comment]
In general, sparse matrices are designed to be big. If the dense version of your matrix fits in L2 cache (for instance), you'll almost always be better off using an ndarray instead.

**Comment by hpaulj** [comment]
I recently tested sparse v dense arrays in a Stackoverflow answer

http://stackoverflow.com/a/36971131/901925

Somewhat to my surprise I found that matrix multiplication with 1000x1000 matrix (`M*M`), sparse was faster even when the density was 50%.

Given their linear algebra roots, sparse matrices do have a good matrix multiplication implementation.  Other things like indexing are quite slow compared to numpy.

**Comment by jaimefrio** [comment]
Your timings include creation of the dense matrix in the dense timing, but not in the sparse, so it doesn't seem a very fair comparison. Onmy system, If you remove that, matrix product of two 1000x1000 matrices with 50% sparsity is 20x faster with dense matrices than with sparse ones.

**Comment by pv** [comment]
IOW, in the ballpark of speedup you usually get from using optimized 
BLAS vs. reference implementation.

**Comment by hpaulj** [comment]
Even if I separate out the `Ma=M.toarray()` it's slower, at least on my system.  That `toarray` takes 50 ms.  But my `np.dot` takes about the same time as `np.einsum`.  I'm just using the stock `numpy/scipy` from recent Ubuntu distribution, so there's no BLAS optimization.  And it's an older laptop with only 2g RAM.
