### ISSUE TITLE
least_squares interface

### ISSUE THREAD

**Issue by pv** [scipy/scipy#5020]
A new `least_squares` interface for LSQ problems is included as a part of gh-5019

However, it should be ensured in the design phase that most important functionality is included in it already from the beginning.

Interface wiki page: https://github.com/nmayorov/bounded-lsq/wiki/Calling-%60leastsq%60-via-generic-interface as regards for MINPACK compatibility.

Suggestions presented so far:

- global optimizers should be supported
- LBFGSB

**Comment by ev-br** [comment]
One thing to consider is where to draw the line between `curve_fit` and `least_squares`, and how to avoid duplication of functionality between the two. 
One option is to keep `least_squares` lean and add new fancy functionality to `curve_fit` only.

**Comment by ev-br** [comment]
As far as general optimizers are concerned, it would be helpful to detail the advantages of adding them to the least_squares wrapper, as compared to calling them through the optimize.minimize layer.

**Comment by andyfaff** [comment]
W.r.t curve fitting functionality in scipy I see the following areas for improvement at the moment.  This is where my interest in least squares lies. I don't know enough about other use cases of `leastsq`, apart from curve fitting.

1. curve fitting has no global minimisers available.
2. there is no way of doing constrained fitting at the moment (`least_squares` is doing this?). Constrained fitting needs work with (1) (i.e. can work with scalar minimizers). Constrained fitting requires a mixture of upper/lower bounds, as well as mathematical relationships between parameters.
3. no easy mechanism for co-refinement (fitting multiple datasets with multiple fit functions, but the parameter vectors could have shared parameters)
4. I'd like to see an easy way of setting up an MCMC exploration of parameter posteriors in a regression situation.
5. It's nice to be able to release and hold parameters. Perhaps you want to try refitting the data with certain parameters held. The difficulty here is that you don't want to have to rewrite the fit function every time.
6. ...

The lmfit package is great for curvefitting, providing the machinery to achieve the above.  However, at the same time I think it's something that scipy should be able to do better.  I guess my eventual hope would be that (the functionality of) lmfit could be merged into scipy somehow.

**Comment by ev-br** [comment]
Whoa, that's a serious wish list :-).

Let's keep the scope of this issue manageable.
Replicating lmfit's functionality is definitely out of scope for @nmayorov 's GSoC. What's proposed in gh-5019 is not a swiss-knife-one-stop-shop curve fitting routine; it's an interface for specialized least squares algorithms. This way, your points 3-6 are clearly out of scope for now (by all means, let's discuss them separately if you have specific suggestions!). 

Item 2: yes, it handles bounds natively. Algebraic constraints between parameters, it does not, and I'm not sure it should (it sounds like it's more sympy/lmfit turf to me). Do you have a spec for how these should be specified?

Item 1: like I was saying, I don't see an advantage of adding `differential_evolution` or `basinhopping` into the least_squares interface. Do you?

**Comment by andyfaff** [comment]
>
> Whoa, that's a serious wish list :-).
>
>  I do wish that curvefitting in scipy could take steps forward :-).

> Replicating lmfit's functionality is definitely out of scope for @nmayorov
> <https://github.com/nmayorov> 's GSoC. What's proposed in gh-5019
> <https://github.com/scipy/scipy/pull/5019> is not a
> swiss-knife-one-stop-shop curve fitting routine; it's an interface for
> specialized least squares algorithms. This way, your points 3-6 are clearly
> out of scope for now (by all means, let's discuss them separately if you
> have specific suggestions!).
>
Totally understand, I just wanted to mention things like this, as it's in a
sort-of-related area.

> Item 2: yes, it handles bounds natively. Algebraic constraints between
> parameters, it does not, and I'm not sure it should (it sounds like it's
> more sympy/lmfit turf to me). Do you have a spec for how these should be
> specified?
>
It is worthwhile having a look at lmfit and examining how it does naive
constraints (by which I mean upper and lower bounds). It seems to work
really well.

> Item 1: like I was saying, I don't see an advantage of adding
> differential_evolution or basinhopping into the least_squares interface.
> Do you?
>
No, it's probably not worth it.

**Comment by ev-br** [comment]
Cross-ref https://github.com/scipy/scipy/pull/5044, which adds large-scale features.

**Comment by ev-br** [comment]
> It is worthwhile having a look at lmfit and examining how it does naive
constraints (by which I mean upper and lower bounds). It seems to work
really well.

Yes,  Nikolay did this. From a practical point of view, the benchmarks linked in the OP, https://github.com/scipy/scipy/pull/5019, show that more often than not, his methods outperform leastsqbound (which uses precisely same transformation as lmfit). (The mathematical content of at least trf is much more solid, too)

**Comment by ev-br** [comment]
OK, unless I misread, it seems that the agreement is to keep global optimizers and L-BFGS-B separate. I should not that the implementation moved quite a lot, and interface followed a bit, with the addition in gh-5044 (which is now the main PR) of large-scale LSQ and modified loss functions.

Also there is a parallel activity for *linear* least squares, gh-5110, so it makes sense to consider these two interfaces together. 

One minor but potentially sticky point is the way the bounds are specified. One can either require a sequence of pairs `(lb_i, ub_i)` for each variable, or a pair of array_likes, `(lb, ub)`. `optimize.minimize` does the former, while `least_squares` does the latter. The reasoning for the latter is that for, e.g., n=10000 variables confined to a hypercube `[0, 1]^n`, it's nicer to write `bounds=(0, 1)` than `bounds=[(0, 1)]*n`.  And it gets nicer still if, say, all `n` variables are non-negative but the upper bounds are different.

A suggestion to unify the specification: https://github.com/scipy/scipy/pull/5110#issuecomment-127737695

**Comment by pv** [comment]
Resolved in 0.17.0
