### ISSUE TITLE
Implemented special function InvEi(x) -- no time to add & write unit tests

### ISSUE THREAD

**Issue by vhaasteren** [scipy/scipy#5021]
Hi all,

I needed a special function (Inverse exponential InvEi) a while ago, and I tracked down this 1980's paper that has a machine precision implementation. The professor gave me his old original FORTRAN code. I ported it, it is now in scipy/special/specfun.f, but I am not able to do a proper merge with unit tests (no Mathematica, and it is of low priority for me).

Is anyone willing to properly push it up? I have saved my function in my own branch on https://github.com/vhaasteren/scipy/tree/eixinv

Below is the function docstring. Cheers,

Rutger

C       ============================================
C       Purpose: Compute inverse exponential
C                integral INVEIX
C       Input  : X  --- Argument of INVEIX
C       Output:  XINVEI --- InvEi(x)
C       ============================================

**Comment by pv** [comment]
Question: where does this code originate? If it is not written by you, we would need a license statement from the original author or proof that the code is public domain before this can be considered.

**Comment by vhaasteren** [comment]
The code was originally written by Dr. Petr Pecina <petr.pecina@mail.asu.cas.cz>. When I requested his code back in February, I asked him whether I could modify the code and donate it to scipy, to which he answered affirmatively. I can ask for a more formal written statement, if that is required? He was not very quick by email, though...

**Comment by pv** [comment]
Yes, in today's world we have to take these things seriously, even if it feels silly to do it for what's mostly Chebyshev coefficients. If the original author has a written statement that (i) he wrote the code, and (ii) intends it to be included it in scipy may be good enough (this would need to be included in the file itself). However, it would be better to have an explicit license statement; one of the simplest options is to take something like http://opensource.org/licenses/BSD-3-Clause and fill in the blanks <YEAR> and <OWNER>.

**Comment by vhaasteren** [comment]
No problem, I will see if I can arrange something like that.

**Comment by vhaasteren** [comment]
Update: I still have not heard back from the original author. Is it acceptable if I re-implement the function, using the same coefficients of course? It is all detailed in his paper (except that the coefficients are not listed on paper -- for as far as I can see).

**Comment by rgommers** [comment]
@vhaasteren yes, if you re-implement the code and only use the coefficients from the paper then there is no license issue.

**Comment by person142** [comment]
Closing this-if someone has a PR then we can review it, but I don't know that we need this to stay open as an issue (especially for a relatively uncommon function).
