### ISSUE TITLE
Cholesky does not throw exception with complex diagonal entries

### ISSUE THREAD

**Issue by ChadFulton** [scipy/scipy#5029]
The Cholesky decomposition is only defined for Hermitian positive-definite matrices, and in particular matrices with real diagonal entries. If a matrix with complex diagonal entries is passed, the `cholesky` routines silently ignore the complex parts.

Example:

```python
>>> import numpy as np
>>> np.linalg.cholesky([[9+5j]])
array([[ 3.+0.j]])
>>> from scipy import linalg
>>> linalg.cholesky
(array([[ 3.+0.j]]), False)
```

In some cases (e.g. negative diagonals) an exception is thrown, and in other cases (e.g. non-symmetric matrices, see #2337) an exception is not thrown. I guess all of the exceptions emanate from LAPACK *potrf, and a complex diagonal entry doesn't trigger an exception there.

Nonetheless, MATLAB does raise an error on matrices with complex diagonals:

```MATLAB
>>> chol(9+5j)
Error using chol
Matrix must be positive definite with real diagonal.
```

Regardless of whether or not this is something that needs to be fixed, I thought it worth reporting the issue.

See https://github.com/statsmodels/statsmodels/issues/2514 for some discussion about this in the context of complex-step derivatives.

**Comment by pv** [comment]
In general, all routines that expect input with certain properties
(triangular, hermitian, symmetric, etc) assume them without checking
they are satisfied.

**Comment by ChadFulton** [comment]
Thanks, I guess we'll just leave it at that then.
