### ISSUE TITLE
scipy.optimize.minimize error messages are printed to stdout rather than stderr

### ISSUE THREAD

**Issue by mgymrek** [scipy/scipy#5037]
For example: https://github.com/scipy/scipy/blob/master/scipy/optimize/lbfgsb/lbfgsb.f#L2551
It would make more sense for these messages to be printed to stderr. This could probably be accomplished by changing all the `write(6,...)` etc. statements to `write(0,...)`.

**Comment by larsmans** [comment]
While we're at it, we could also remove the `iterate.dat` files from LBFGS. I find those all over my homedir every time I use that algorithm.

**Comment by larsmans** [comment]
Would you care to submit a patch for your proposed change?

**Comment by sumitbinnani** [comment]
@larsmans @ev-br @mgymrek 
Is anyone working on the patch? If not, I would be happy to contribute :-)

**Comment by larsmans** [comment]
I'm not.

**Comment by ev-br** [comment]
Not to my knowledge, no. Patch welcome.

**Comment by sumitbinnani** [comment]
@ev-br 
Did not realize that the code was in FORTRAN (and assumed that it was in python). However, have tried to address the issue by reading basics of FORTRAN and understanding the output message. Kindly review.

Thanks,
Sumit

**Comment by ev-br** [comment]
Fixed in https://github.com/scipy/scipy/pull/5340.
