### ISSUE TITLE
todense implementation for numpy.matrix

### ISSUE THREAD

**Issue by musically-ut** [scipy/scipy#5038]
This is a request for a code review of a feature that I am working on for numpy.

I have implemented `numpy.matrix.todense` in this pull request: https://github.com/numpy/numpy/pull/6066 
The associated issue and the use case are explained in this issue: https://github.com/numpy/numpy/issues/6060

I **don't think** that it effects `scipy` directly in anyway. Nevertheless, it would be great if someone familiar with `scipy` could comment on that issue with improvements or a simple LGTM.

Thanks!

**Comment by musically-ut** [comment]
Bump! :)

**Comment by argriffing** [comment]
If it's merged, https://github.com/scipy/scipy/pull/5062 should fix your original problem in a different way.

In 5 days no one has answered your review request, so I'll just add 2c. Personally I have mixed feelings about adding scipy.sparse member functions to np.matrix. On one hand it facilitates duck-typed code, but on the other hand there are enough differences between scipy.sparse and np.matrix which I don't imagine will be resolved in the foreseeable future that I'm not sure that writing code in this style should be encouraged.

**Comment by musically-ut** [comment]
@argriffing Thanks for the response and #5062. I think it is a good change to have irrespective of whether https://github.com/numpy/numpy/pull/6066 gets merged in.

About encouraging duck-typing, I thought that if there was one function which would make sense to have on both objects, it is `.todense` because the intention there is pretty clear. I am sure that there are examples when such a difference would cause subtle performance problems. If someone is using sparse matrices, they probably care more about performance than writing implementation agnostic code.

Moreover, I understand that the `numpy` team isn't too keen on adding features to `numpy.matrix` and the utility of this particular addition can be argued either way. I'll not belabor it anymore.
