### ISSUE TITLE
Cubic interpolation: On entry to DGESDD parameter number 12 had an illegal value

### ISSUE THREAD

**Issue by f0a** [scipy/scipy#5039]
```fi = interpolate.interp1d(np.random.rand(10), np.random.rand(10), kind='cubic')```

raises (scipy 0.15.1):
```
ValueError                                Traceback (most recent call last)

----> 1 fi = interpolate.interp1d(np.random.rand(10), np.random.rand(10), kind='cubic')

.../python3.4/site-packages/scipy/interpolate/interpolate.py in __init__(self, x, y, kind, axis, copy, bounds_error, fill_value, assume_sorted)
    431         else:
    432             minval = order + 1
--> 433             self._spline = splmake(x, y, order=order)
    434             self._call = self.__class__._call_spline
    435 

.../python3.4/site-packages/scipy/interpolate/interpolate.py in splmake(xk, yk, order, kind, conds)
   2136     # the constraint matrix
   2137     B = _fitpack._bsplmat(order, xk)
-> 2138     coefs = func(xk, yk, order, conds, B)
   2139     return xk, coefs, order
   2140 

.../python3.4/site-packages/scipy/interpolate/interpolate.py in _find_smoothest(xk, yk, order, conds, B)
   1826         B = _fitpack._bsplmat(order, xk)
   1827     J = _fitpack._bspldismat(order, xk)
-> 1828     u, s, vh = scipy.linalg.svd(B)
   1829     ind = K-1
   1830     V2 = vh[-ind:,:].T

.../python3.4/site-packages/scipy/linalg/decomp_svd.py in svd(a, full_matrices, compute_uv, overwrite_a, check_finite)
    104     # perform decomposition
    105     u,s,v,info = gesdd(a1, compute_uv=compute_uv, lwork=lwork,
--> 106                        full_matrices=full_matrices, overwrite_a=overwrite_a)
    107 
    108     if info > 0:

ValueError: On entry to DGESDD parameter number 12 had an illegal value
```

**Comment by ev-br** [comment]
Can you provide a reproducible example please --- if using random numbers, please use `np.random.seed`.  Also when you have a reproducible example, please repeat with sorted `x` values.

**Comment by f0a** [comment]
I get the same error with 
```fi = interpolate.interp1d([1,2,3,4], [1,2,3,4], kind='cubic')```
This is likely a lapack bug (version 3.0.3); I can't reproduce the error on systems with more recent lapack versions.

**Comment by argriffing** [comment]
Maybe related to https://github.com/scipy/scipy/issues/3868?

**Comment by ev-br** [comment]
Thanks for the reproducer.
I cannot reproduce the bug on my (not quite bleeding edge) system with lapack 3.3.1.
If it's a lapack bug, there's not much we can do I guess. 

I looked at the matrix B from the traceback you pasted above( it's 
https://github.com/scipy/scipy/blob/master/scipy/interpolate/interpolate.py#L1957). It looks finite, condition number is around 2. Since there are systems around where this fails, maybe an actionable item for us would be to add a test with svd-ing this matrix directly (+a link to this issue and the interp1d call as a comment), so that we can detect such systems more easily.

**Comment by ev-br** [comment]
gh-5039 adds the test which should fail in the same way, can you check that @f0a 

Debugging it further would require a fortran reproducer, which is not hard to write, but it does not seem to be very useful as long as the problem is not present in newer LAPACK versions.
