### ISSUE TITLE
scipy.optimize.curve_fit produces wrong results when used with list and does not throw an error!!!!

### ISSUE THREAD

**Issue by afrutig** [scipy/scipy#5042]
Extremely negligent bug!! curve_fit accepts lists but does the fitting completely wrong. This needs to be fixed asap. Only numpy arrays give the right result, at least throw an exception if one tries to use lists.

**Comment by WarrenWeckesser** [comment]
What version of scipy are you using?  Could you provide a self-contained example that demonstrates the problem?

**Comment by dlax** [comment]
I believe this got fixed in commit 856e3963486e7ab0358ad1f036e44855fb0d753f which appears in any version of scipy from 0.14.
