### ISSUE TITLE
Differential evolution is extremely slow for high-dimensional problems

### ISSUE THREAD

**Issue by michalgregor** [scipy/scipy#5046]
Differential evolution takes very long to compute even a single generation when used on a high-dimensional problem, e.g. with 25 dimensions.

I suspect it might have something to do with these lines:

```python
self.population = np.zeros((popsize * parameter_count,
                                    parameter_count))
```

and

```python
        self.population_energies = np.ones(
            popsize * parameter_count) * np.inf
```
which seem to multiply the size of the population with the number of parameters and this, in turn increases the required number of evalutations: e.g. from 200 for a population with 200 individuals to 200*25.

Is there a good reason for this multiplication? And if so, how else can we fix the behaviour?

**Comment by pavelponomarev** [comment]
It is probably a misleading naming of the variable. Better naming would be `popmul` instead of `popsize`. The total population size is calculated using current variable names as `popsize * parameter_count` as it is described in the docstrings.

**Comment by michalgregor** [comment]
Oh, I see. I have missed that one, sorry.

Since it would probably be impractical to rename a keyword argument I guess there is nothing we can do about it.

**Comment by pavelponomarev** [comment]
Well, it is of course impractical, but I feel that DE realization requires substantial redesign. It is sometimes must be done. Please follow #4864, maybe you could contribute something as a real user of this algorithm.
