### ISSUE TITLE
scipy.constants outdated: CODATA 2014 are now available

### ISSUE THREAD

**Issue by hansharhoff** [scipy/scipy#5047]
The official CODATA recommendations have been updated recently:
http://physics.nist.gov/cuu/Constants/index.html

The values in scipy should be probably updated to use the newer values.

**Comment by rgommers** [comment]
Indeed, good point @hansharhoff . PR welcome.

**Comment by pizzathief** [comment]
er.. hi, I've done this, the scipy tests passed on my machine, but the travis CI build failed, was wondering how I can get access to the logs so I can find out what happened and fix it.

**Comment by LuciusV** [comment]
scipy 0.16.1 still uses old 2010 values
