### ISSUE TITLE
BUG: Upper tail accurracy lost in genpareto.logsf.

### ISSUE THREAD

**Issue by pbrod** [scipy/scipy#5048]
In the maintanence dcc44e2428d4a046ce3ddce9466175373a52065b the genpareto._logsf method was removed. The effect of this removal is that the  upper tail accuracy of genpareto.logsf is completely lost. It is very important to keep this accurracy when doing extreme value analysis.

Therefore I would propose to undo the removal of the _logsf method:

    def _logsf(self, x, c):
            return _lazywhere((x == x) & (c != 0), (x, c),
                lambda x, c: -special.log1p(c*x) / c,
                -x)

**Comment by WarrenWeckesser** [comment]
Per, thanks for reporting the problem.  Here's an example.

In scipy 0.15.1:

```
In [1]: from scipy.stats import genpareto

In [2]: genpareto.logsf(1e10, .01, 0, 1)
Out[2]: -1842.0680753952365
```

But in `0.17.0.dev0+847b473`, we get:

```
In [4]: genpareto.logsf(1e10, .01, 0, 1)
/Users/warren/local_scipy/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:843: RuntimeWarning: divide by zero encountered in log
  return log(self._sf(x, *args))
Out[4]: -inf
```

It would be nice to get this fixed and backported to 0.16.
