### ISSUE TITLE
scipy.signal.sigtools._convolve2d: ComplexWarning: Casting complex values to real discards the imaginary part

### ISSUE THREAD

**Issue by avtomaton** [scipy/scipy#5055]
How to reproduce:
call  
`scipy.signal.sigtools._convolve2d([[2, 2, 2], [1, 2, 3], [0, 1, 0]], [[0.5], [0.5]], 1, 0, 0, 0)`  

`flip=1` is necessary, with `flip=0` warning doesn't appear.

**Comment by rgommers** [comment]
that warning no longer appears, so seems fixed.
