### ISSUE TITLE
sparse matrix element-wise multiplying dense matrix returns dense matrix

### ISSUE THREAD

**Issue by dawenl** [scipy/scipy#5056]
When a scipy sparse matrix element-wise multiples a dense ndarray, the returned matrix is of type matrix, which seems very inefficient, given that it is obviously a sparse matrix.

```
In [90]: A = scipy.sparse.csr_matrix((5, 5))

In [93]: B = np.random.randn(5, 5)

In [96]: C = A.multiply(B)

In [98]: type(C)
Out[98]: numpy.matrixlib.defmatrix.matrix

In [100]: C
Out[100]: 
matrix([[-0., -0.,  0.,  0.,  0.],
        [ 0.,  0., -0., -0., -0.],
        [ 0., -0.,  0.,  0., -0.],
        [-0., -0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -0., -0.]])
```

Is there any reason behind this that I am missing?

**Comment by perimosocordiae** [comment]
I had a pull request aimed at solving this problem, but I forgot to follow up on it: #4133.

I'll look into fixing it now.

**Comment by perimosocordiae** [comment]
Ok, PR #5057 is pending with a fix.

**Comment by dawenl** [comment]
That's awesome. Thanks a lot!

**Comment by larsmans** [comment]
The thing is that a sparse-dense matrix product is not "obviously" sparse:

```py
>>> A = csr_matrix(np.diag(np.arange(4) + 1))
>>> B = np.random.randn(4, 4)
>>> A * B
array([[ 0.52486115, -0.10865103, -1.20444296,  0.04722824],
       [-1.65310597,  1.30730895, -0.84056326, -1.15086646],
       [ 1.04445601,  5.14768672, -2.13246767, -0.10959839],
       [-1.54380663, -1.02258375, -1.81889132, -2.52211866]])
```

**Comment by dawenl** [comment]
What I mean is element-wise multiplication which is obviously sparse, not matrix multiplication.

**Comment by larsmans** [comment]
Ah! Sorry for the noise, missed that in your original post.

**Comment by perimosocordiae** [comment]
PR #5057 merged, so this issue can be closed now.

**Comment by dawenl** [comment]
Great. Thanks for the help!

**Comment by jluttine** [comment]
I don't think this issue has been fixed when broadcasting occurs. I'm running SciPy 0.18.1 and I get the following outputs:

```
>>> from scipy import sparse

>>> sparse.eye(4,3).multiply(np.ones((4,3)))
<4x3 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in COOrdinate format>

>>> sparse.eye(4,1).multiply(np.ones((4,3)))
matrix([[ 1.,  1.,  1.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])

sparse.eye(4,1).multiply(np.ones((1,3)))
matrix([[ 1.,  1.,  1.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])
```

I think all these should return sparse matrix results.

**Comment by rgommers** [comment]
@jluttine there's a proposed fix in gh-6750. Can you please check that things work as expected with that PR?
