### ISSUE TITLE
ImportError: cannot import name RegularGridInterpolator

### ISSUE THREAD

**Issue by sun031** [scipy/scipy#5063]
I am going to use this function, but I try to import the function, it gives the import error. I can import griddata and RectBivariateSpline properly, but not RegularGridInterpolator and interpn. Many thanks.

Here is my command in ipython:
from scipy.interpolate import RegularGridInterpolator

**Comment by pv** [comment]
Note "New in version 0.14" as explained in the documentation.

**Comment by sun031** [comment]
Yes, there are some introductions on the new feature. My problem is that the module cannot be imported. Something wrong with my installation or else? Thanks very much.
