### ISSUE TITLE
curve_fit, analytic Jacobian and weights

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#5068]
`curve_fit` accepts generic kwargs, and sends them directly to `leastsq`. This way one can, in principle, supply an analytic Jacobian for the fit function. However, if also uncertainties are supplied, `sigma is not None`, the Jacobian needs to be scaled, https://github.com/scipy/scipy/blob/v0.15.1/scipy/optimize/minpack.py#L450

The fix is similar to https://github.com/lmfit/lmfit-py/pull/234 and https://github.com/jjhelmus/leastsqbound-scipy/pull/7.

(found by @nmayorov).

**Comment by kaichogami** [comment]
@ev-br I would like to work on this, if this is still open.

**Comment by ev-br** [comment]
go for it

**Comment by kaichogami** [comment]
It might take me quite a amount of time before I solve this as I don't understand a lot of things. If its on priority or someone else wants to work on it, please create a PR.
Thank you!
