### ISSUE TITLE
UnivariateSpline: interpolator(a) raises error, but interpolator.integrate(a,b) does not

### ISSUE THREAD

**Issue by oceanEngineer** [scipy/scipy#5074]
I would like to create an interpolator which also integrates. The UnivariateSpline class seems like a simple solution to this problem. 

My problem is that I would like it to return nan values outside of the bbox range. I came up with a solution involving a try/except statement. This works for the original interpolator function, but not for its integral (!)

My hacky solution is to evaluate the interpolator to catch the error, but then evaluate the integral. This seems like a bug to me though, so I thought I would report it. 

At the same time, I will ask if there is a better way to perform this operation.

```
x=np.r_[0:10:10j]
interpolator=UnivariateSpline(x, x, k=1, ext=2)
xNew=np.r_[5:15:10j]

integral=[]
for d in xNew:
    # fill extrapolated values with nan
    try:
        _=interpolator(d)
        integral.append(interpolator.integral(0,d))
    except ValueError:
        integral.append(np.nan)
```

**Comment by ev-br** [comment]
These sorts of usage questions are more appropriate for scipy-user mailing list or StackOverflow. 
That being said, both tasks you're mentioning can be done with e.g., function-based spline interface:

```
In [1]: import numpy as np

In [2]: from scipy.interpolate import splev, splrep, splantider

In [3]: def interpolator(x, tck, bbox):
   ...:     x0, x1 = bbox
   ...:     res = splev(x, tck)
   ...:     res[(x < x0) | (x > x1)] = np.nan
   ...:     return res
   ...: 

In [4]: x = np.linspace(0, 10, 11)

In [5]: xnew = np.linspace(5, 15, 11)

In [6]: tck = splrep(x, x, k=1)

In [7]: interpolator(xnew, tck, [0, 10])
Out[7]: array([  5.,   6.,   7.,   8.,   9.,  10.,  nan,  nan,  nan,  nan,  nan])

In [8]: tck_a = splantider(tck)

In [9]: interpolator(xnew, tck_a, bbox=[0, 10])
Out[9]: 
array([ 12.5,  18. ,  24.5,  32. ,  40.5,  50. ,   nan,   nan,   nan,
         nan,   nan])
```

This issue tracker is intended for reporting bugs or feature requests. I don't see either in what you wrote, so I'm closing this. Please open a new issue if you have believe you've found a bug or there is a specific feature you want to request.
