### ISSUE TITLE
saving sparse matrix with all zeros columns when it is loaded again lose that columns in the original shape

### ISSUE THREAD

**Issue by frarito** [scipy/scipy#5080]
Hi all, 
I'm experiencing some issues with sparse matrix. The situation is the following: I generate a matrix (dense) and do it sparse (csr_matrix), I save the data, indices and indptr elements but when I want to load that elements to reconstruct my matrix it has less columns. I figure out that this is because some columns are all zeros, but this is wrong because what I want is the original shape and the sparse don't preserve that.
If something is not understood, please let me know.
Regards,
Franco

**Comment by WarrenWeckesser** [comment]
How do you save the sparse data?  Could you include a self-contained example (something we can copy and run) that demonstrates the issue?

**Comment by frarito** [comment]
Hi Warren,
I give you some examples:

import numpy
import os
import scipy
import scipy.sparse
import scipy.stats
import scipy.linalg
from scipy.sparse import vstack
from scipy.sparse import hstack

#Example 1

a = numpy.zeros((10,9))
a[:,4]=1
a
array([[ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.]])

a_sparse =  scipy.sparse.csr_matrix(a)

numpy.save('a_data',a_sparse.data)
numpy.save('a_indices',a_sparse.indices)
numpy.save('a_indptr',a_sparse.indptr)

data = numpy.load('a_data.npy')
indices = numpy.load('a_indices.npy')
indptr = numpy.load('a_indptr.npy')

a_sparse_2 = scipy.sparse.csr_matrix((data,indices,indptr))
a_sparse_2.shape

a_sparse_2.toarray()
array([[ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.]])

a_sparse_2 = scipy.sparse.csr_matrix((data,indices,indptr),(10,9))
a_sparse_2.toarray()
array([[ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.]])

#Example 2:

a = numpy.zeros((10,9))
a[:,4]=1
a[:,7]=1
a
array([[ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.]])

a_sparse =  scipy.sparse.csr_matrix(a)

numpy.save('a_data',a_sparse.data)
numpy.save('a_indices',a_sparse.indices)
numpy.save('a_indptr',a_sparse.indptr)

data = numpy.load('a_data.npy')
indices = numpy.load('a_indices.npy')
indptr = numpy.load('a_indptr.npy')

a_sparse_2 = scipy.sparse.csr_matrix((data,indices,indptr))
a_sparse_2.shape

a_sparse_2.toarray()
array([[ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.]])

a_sparse_2 = scipy.sparse.csr_matrix((data,indices,indptr),(10,9))
a_sparse_2.toarray()
array([[ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.]])

#Example 3:

a = numpy.zeros((10,9))
a[:,8]=1
a[:,4]=1
a
array([[ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.]])

a_sparse =  scipy.sparse.csr_matrix(a)

numpy.save('a_data',a_sparse.data)
numpy.save('a_indices',a_sparse.indices)
numpy.save('a_indptr',a_sparse.indptr)

data = numpy.load('a_data.npy')
indices = numpy.load('a_indices.npy')
indptr = numpy.load('a_indptr.npy')

a_sparse_2 = scipy.sparse.csr_matrix((data,indices,indptr))
a_sparse_2.shape
(10, 9)

a_sparse_2.toarray()
array([[ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.]])

I hope they help you understand the problem.

Regards,
Franco

**Comment by pv** [comment]
If you think about what the CSR format arrays you save contain, it's
clear they do not contain full information of the shape of the array.
You need to also save a_sparse.shape in addition to the data arrays.
