### ISSUE TITLE
linalg lsqr libraries not found on OSX for v0.16

### ISSUE THREAD

**Issue by michaelaye** [scipy/scipy#5092]
I get this image not found error when trying to import lsqr from linalg:
```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-a4c2463c7356> in <module>()
----> 1 from scipy.sparse.linalg import lsqr as sparse_lsqr

/Users/klay6683/miniconda3/lib/python3.4/site-packages/scipy/sparse/linalg/__init__.py in <module>()
    107 from __future__ import division, print_function, absolute_import
    108 
--> 109 from .isolve import *
    110 from .dsolve import *
    111 from .interface import *

/Users/klay6683/miniconda3/lib/python3.4/site-packages/scipy/sparse/linalg/isolve/__init__.py in <module>()
      4 
      5 #from info import __doc__
----> 6 from .iterative import *
      7 from .minres import minres
      8 from .lgmres import lgmres

/Users/klay6683/miniconda3/lib/python3.4/site-packages/scipy/sparse/linalg/isolve/iterative.py in <module>()
      5 __all__ = ['bicg','bicgstab','cg','cgs','gmres','qmr']
      6 
----> 7 from . import _iterative
      8 
      9 from scipy.sparse.linalg.interface import LinearOperator

ImportError: dlopen(/Users/klay6683/miniconda3/lib/python3.4/site-packages/scipy/sparse/linalg/isolve/_iterative.so, 2): Library not loaded: /usr/local/gfortran/lib/libquadmath.0.dylib
  Referenced from: /Users/klay6683/miniconda3/lib/python3.4/site-packages/scipy/sparse/linalg/isolve/_iterative.so
  Reason: image not found
```
When downgrading to 0.15.1 the error disappears.

System: OSX 10.10.4, iMac 5k
Package Manager: miniconda. 
Note: I found this trying to use DBSCAN from scikit-learn.cluster, so that is broken due to this, too.

**Comment by matthew-brett** [comment]
Can you raise this with the miniconda team?  We don't maintain the conda packages for scipy.

**Comment by michaelaye** [comment]
Sure thing, just didn't know if that's a miniconda thing or scipy itself. There are by now already (Mini)conda GH issues about scipy probs with 0.16. You can close this if appropriate.

**Comment by matthew-brett** [comment]
I think you've found a conda packaging problem here, where you need a gfortran dynamic library and it is not installed.  I would be very surprised if the OSX wheel do ship and maintain has the same problem, but please do test and let us know:

```
pip install numpy scipy
python -c 'from scipy.sparse.linalg import lsqr as sparse_lsqr'
```

I believe you can install pip from miniconda, and that you have to make sure that your selected conda environment does not already have numpy or scipy.  I'm afraid I am a Python.org Python / virtualenv person myself.

**Comment by rgommers** [comment]
Here's a conda issue that looks the same: https://github.com/conda/conda/issues/1467

**Comment by michaelaye** [comment]
Fixed by https://github.com/ContinuumIO/anaconda-issues/issues/392
