### ISSUE TITLE
Failed import of scipy.special: “Symbol not found: ___addtf3”

### ISSUE THREAD

**Issue by williamgilpin** [scipy/scipy#5093]
Attempting to import from scipy.special 
    
    from scipy.special import legendre

Results in the following traceback:

    ImportError: 
    dlopen(/Users/william/miniconda/envs/myenv/lib/python3.4/site-packages/scipy/special/_ufuncs.so, 2): Symbol not found: ___addtf3
    Referenced from: /Users/william/miniconda/envs/prakenv/lib/python3.4/site-packages/scipy/special/_ufuncs.so
    Expected in: /usr/lib/libSystem.B.dylib

This occurs in both Python 2.7 and Python 3.4 miniconda environments. Reverting to scipy 0.15.0 resolves the issue. I'm running OSX Yosemite on a 2014 Macbook Pro. Thank you very much for any advice.

**Comment by rgommers** [comment]
@williamgilpin thanks for the report.

I think it's the same packaging issue as gh-5092, and as https://github.com/conda/conda/issues/1467. Should be solved by the conda team, so closing this issue.

**Comment by williamgilpin** [comment]
You're right, further examination revealed that this was a conda issue. Closing all active conda environments, updating miniconda, reopening the environments, and the removing and re-installing the latest version scipy fixed the issue. Thanks very much for your help with this.

**Comment by rgommers** [comment]
Thanks for confirming that.
