### ISSUE TITLE
linalg.eigh failing for moderate matrices

### ISSUE THREAD

**Issue by guillean** [scipy/scipy#5095]
Running SciPy's `linalg.eigh` on multiple machines yields results different from the correct ones by `linalg.eig`. Simple code to reproduce this is, in Python 3.4

```python
import numpy as np
from scipy import linalg

M = np.random.random((100,100))
M += M.T

v_1 = sorted(linalg.eigh(M)[0])
v_2 = sorted(linalg.eigvals(M))

print(v_1)
print(v_2)
print(np.allclose(v_1, v_2)) # Returns false
```

I ran the code on three different computers, two running Python 3.4, NumPy version 1.8.2, SciPy version 0.13.3; the other running Python 3.4, NumPy version 1.9.2, SciPy version 0.17.0 (dev).

The original bug was reported [in this StackOverflow thread](http://stackoverflow.com/questions/31664776/numpys-eigh-and-eig-yield-inconsistent-eigenvalues).

**Comment by insertinterestingnamehere** [comment]
This is caused by https://github.com/numpy/numpy/issues/6119. The array `M` isn't actually symmetric when you call `eigh`, so the algorithm for symmetric matrices should give incorrect answers.

**Comment by guillean** [comment]
Ah, I see. But, even so, the original problem isn't fully solved. On my machine, I'm getting very different values between `eigh` and `eig` using the following code:

```python
import numpy as np
from math import *
from scipy import sparse, linalg

# Variable declarations and such (pre-computed)
Ne, Np = 256, 8
N = Ne*Np - Ne + 1
domain_size = 4/Ne


x = np.array([-0.015625  , -0.01362094, -0.00924532, -0.0032703 ,  0.0032703 ,
    0.00924532,  0.01362094,  0.015625  ])
w = np.array([ 0.00055804,  0.00329225,  0.00533004,  0.00644467,  0.00644467,
    0.00533004,  0.00329225,  0.00055804])
dmat = np.array([[ -896.        ,  1212.00631086,  -484.43454844,   275.06612251,
     -179.85209531,   124.26620323,   -83.05199285,    32.        ],
   [ -205.43460499,     0.        ,   290.78944413,  -135.17191772,
       82.83085126,   -55.64467829,    36.70818656,   -14.07728095],
   [   50.7185076 ,  -179.61445086,     0.        ,   184.03311398,
      -87.85829324,    54.08144362,   -34.37053351,    13.01021241],
   [  -23.81762789,    69.05246008,  -152.20398294,     0.        ,
      152.89115899,   -72.66291308,    42.31407046,   -15.57316561],
   [   15.57316561,   -42.31407046,    72.66291308,  -152.89115899,
        0.        ,   152.20398294,   -69.05246008,    23.81762789],
   [  -13.01021241,    34.37053351,   -54.08144362,    87.85829324,
     -184.03311398,     0.        ,   179.61445086,   -50.7185076 ],
   [   14.07728095,   -36.70818656,    55.64467829,   -82.83085126,
      135.17191772,  -290.78944413,     0.        ,   205.43460499],
   [  -32.        ,    83.05199285,  -124.26620323,   179.85209531,
     -275.06612251,   484.43454844, -1212.00631086,   896.        ]])

# More declarations
x_d = np.zeros(N)
w_d = np.zeros(N)
dmat_d = np.zeros((N, N))

for i in range(Ne):
    x_d[i*(Np-1):i*(Np-1)+Np] = x+i*domain_size
    w_d[i*(Np-1):i*(Np-1)+Np] += w
    dmat_d[i*(Np-1):i*(Np-1)+Np, i*(Np-1):i*(Np-1)+Np] += dmat

peq = (np.cos((x_d-2)*pi/4))**2

# Normalization
peq = peq/np.sum(w_d*peq)
p0 = np.maximum(peq, 1e-10)
p0 /= np.sum(p0*w_d)

# Make efficient matrix that can be built
K = sparse.lil_matrix((N, N))

# Calculate K matrix (<i|pHp|j> in the LGL-nodes basis)
for i in range(Ne):
    idx_s, idx_e = i*(Np-1), i*(Np-1)+Np
    K[idx_s:idx_e, idx_s:idx_e] += dmat.T.dot(np.diag(w*p0[idx_s:idx_e])).dot(dmat)

# Re-make matrix for efficient vector products
K = sparse.csr_matrix(K)

# Make matrix for <i|p|j> in the LGL basis as efficient diagonal sparse matrix
S = sparse.diags(p0*w_d, 0)

# Solve the generalized eigenvalue problem: Kc = lSc for hermitian matrices K and S
lQ, Q = linalg.eigh(K.todense(), S.todense())
_lQ, _Q = linalg.eig(K.todense(), S.todense())

lQ.sort()
_lQ.sort()

if not np.allclose(lQ, _lQ):
    print(lQ)
    print(_lQ)
```

does `dmat.T` also have odd behavior here? Or does it make a copy once the `dot` operation is performed? (I'd imagine the dot operation is well-behaved, here)

**Comment by guillean** [comment]
And, for additional reference, here's the BLAS linkage and such:
```bash
blas_opt_info:
    extra_compile_args = ['-msse3', '-DAPPLE_ACCELERATE_SGEMV_PATCH', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    define_macros = [('NO_ATLAS_INFO', 3)]
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
lapack_opt_info:
    extra_compile_args = ['-msse3', '-DAPPLE_ACCELERATE_SGEMV_PATCH']
    define_macros = [('NO_ATLAS_INFO', 3)]
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
```

**Comment by insertinterestingnamehere** [comment]
Hmm. The code you've posted appears to be error-free on my machine, but I use OpenBLAS, not Accelerate. I'm not surprised that there are some issues here though. The array `K` has a condition number around `1E17`.

**Comment by guillean** [comment]
Huh, interesting. But then why does it fail to converge to reasonable values? Like, it's not just far off by a few decimals, but it gives me completely wrong eigenvalues (e.g. numbers on the order of -10^23 for positive semi-definite matrices)---which is why it's odd. I guess I'll just recompile SciPy with OpenBLAS support and be done with it.

**Comment by guillean** [comment]
After compiling NumPy to be linked with OpenBLAS, I'm still getting the same error margins; if not the same numbers as Accelerate/MKL---I'm completely at a loss with what to do.

**Comment by argriffing** [comment]
I can't reproduce this problem. On my system with OpenBLAS the generalized eigenvalues computed with eig and eigh agree. The input matrices appear to meet the documented requirements (both are hermitian, and the second one is also positive definite). As @insertinterestingnamehere has mentioned, the first input matrix is singular but it's not clear to me that this should be a problem.
```
2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
numpy version: 1.10.0.dev0+9232200
scipy version: 0.17.0.dev0+89d32a8
```

**Comment by guillean** [comment]
Re-installing MKL and linking to Accelerate seems to have done the trick, but it's still odd that it didn't converge at all, before. Re-running the test on Py3.4 works beautifully, but I still get incorrect values for 2.7.

**Comment by rgommers** [comment]
This should be closed as not a bug, right?

**Comment by guillean** [comment]
I'm still unsure what was causing the error, but if it's not reproducible then we might as well close it.

**Comment by pv** [comment]
All the eigenvalue computations are done by LAPACK, whose [known bug list is here](http://www.netlib.org/lapack/Errata/index2.html) --- DSYEVD is the relevant routine for this case. In general, linear algebra computations giving wrong results are not fixable by us, they need to be fixed in LAPACK instead --- or in Accelerate/MKL whichever has the issue.

**Comment by guillean** [comment]
@pv All right, I'll just close this issue then. Yes, it seemed to be that LAPACK was failing since after recompiling everything to the newest version (not the one that shipped with my Mac which was ~2014), eigh worked as expected.
