### ISSUE TITLE
inefficient median calculation in scipy.stats.binned_statistic_dd

### ISSUE THREAD

**Issue by dshean** [scipy/scipy#5100]
The binned_statistic functions are excellent - a great resource for reducing large geospatial point datasets.  I've found that the binned_statistic_2d is very efficient when the stat is mean, std, count or sum.  
However, the median calculation is very inefficient.  
I glanced at the source, and I believe the median and the generic statistic functions are being computed for every single bin, regardless of whether those bins actually contain points.  It seems like it should be trivial to limit these stats to bins with count > 0.  
It would also be nice to have efficient 'min' and 'max'  stats available as options, instead of the user passing as a function.

**Comment by rgommers** [comment]
It will only get significantly faster if most bins are empty, but indeed doesn't seem too hard to do. Adding ``'min'`` and ``'max'`` also makes sense to me. 

Marking this as an easy-fix enhancement - pull requests welcome.

**Comment by souravsingh** [comment]
@rgommers Is the issue fixed?

**Comment by rgommers** [comment]
It is indeed fixed, thanks for the ping @souravsingh
