### ISSUE TITLE
Docs suggest scipy.sparse.linalg.expm_multiply supports LinearOperator but it doesn't

### ISSUE THREAD

**Issue by wschudy** [scipy/scipy#5103]
According to [the docs](http://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.expm_multiply.html#scipy.sparse.linalg.expm_multiply) the first parameter to expm_multiply is a "transposable linear operator", which presumably includes LinearOperator. However expm_multiply actually appears to accept numpy arrays or scipy sparse matrices only. For example:

``` python
import numpy as np
import scipy.sparse.linalg as spsl
spsl.expm_multiply(spsl.aslinearoperator(np.array([[2]])), np.array([1]))
```

fails because [_trace()](https://github.com/scipy/scipy/blob/v0.16.0/scipy/sparse/linalg/_expm_multiply.py#L31) assumes its parameter is either a numpy array or a scipy sparse matrix.

It seems expm_multiply uses the trace, 1-norm and infinity-norm of its parameter, none of which are available for LinearOperator. <del>Fixing this bug by supporting LinearOperator would therefore require some non-trivial algorithm design so you may want to fix the documentation now and defer adding LinearOperator support until later.</del>

**Comment by wschudy** [comment]
Actually this bug is easier to fix that it appeared at first. Let `M` be the matrix being exponentiated. There’s already code for estimating the 1-norm using only matrix-vector products (which is applied to powers of `M`) so unless exact one-norm is needed for `M` itself that should work fine. The infinity-norm isn’t used on `M` so that’s not an issue. The biggest issue appears to be computing the trace of `M`. I can think of two ways to find the trace. One option is to ask `LinearOperator` implementations used with `expm_multiply` to provide a `trace()` method. I’d guess that many `LinearOperator` implementations can compute the trace about as easily as they can compute matrix/vector products; for example it’s easy to find the trace of matrices with a known low rank representation. If an approximate trace is ok (which seems likely but I haven’t read the papers) another option is to use the following unbiased estimator of the trace:
```python
import math
import numpy as np
def EstimatedTrace(A, k):
  n = A.shape[1]
  rand_mat = np.random.randn(n, k)
  # Normalize columns of rand_mat to have norm sqrt(n)
  rand_mat *= (math.sqrt(n) / np.linalg.norm(rand_mat, axis=0))
  # TODO: if A.dot(rand_mat) returns a np.matrix or scipy.sparse matrix
  # the multiplication won't be compentwise as desired
  return (A.dot(rand_mat) * rand_mat).sum()/k
```
In addition to the trace issue there are a couple of minor issues that are presumably easy to fix, including that `_SumLinearOperator` and `_PowerLinearOperator` don't support transpose. BTW the lack of transpose for `_PowerLinearOperator` actually breaks `expm_multiply` even if it's given a numpy matrix as argument; I would guess that this wasn't noticed because [this branch] (https://github.com/scipy/scipy/blob/v0.16.0/scipy/sparse/linalg/_expm_multiply.py#L427) may not be executed very often. If this is the case I'd suggest adding line coverage analysis to your unit tests to catch untested code like this.

**Comment by larsmans** [comment]
The trace can also be computed explicitly, using (naive implementation)

```py
def trace(x):
    tr = 0
    for i in xrange(x.shape[0]):
        v = np.zeros(x.shape[0])
        v[i] = 1
        tr += x.dot(v)[i]
    return tr
```

It's probably smarter to add a `_trace` method for this, though.

**Comment by larsmans** [comment]
Ping @argriffing.

**Comment by argriffing** [comment]
@wschudy I see you're right, it doesn't work for abstract linear operators so the docs should be changed.  Looking at the publication http://eprints.ma.man.ac.uk/1591/01/covered/MIMS_ep2010_30.pdf I see that the algorithm does ask for the trace.  This is efficient for already-dense matrices, and scipy.sparse matrices have `.diagonal()`.  I understand and agree with the point that for a low rank linear operator the trace can be relatively efficiently computed (because the trace is the sum of eigenvalues, and a low rank matrix has only a few nonzero eigenvalues).  I don't think scipy has an interface for abstract linear operators with a known trace or spectrum; for example https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/interface.py doesn't include 'trace' or 'eigen'-anything.

@larsmans To be honest, I'm not caught up with the latest scipy linear operator 'best practices'.  For example I wasn't completely following the details of https://github.com/scipy/scipy/pull/4087, and I didn't even try to follow the relevant numpy mega-thread https://github.com/numpy/numpy/issues/5844. In my opinion it would be nice if scipy would adopt some battle-tested abstract linear operator interface, but of course this may require more volunteer work than is available.

**Comment by wschudy** [comment]
1. Looking at the paper, the trace is only used as a heuristic to find a shift mu such that || (A - mu*I)^p ||_1 is small, which reduces runtime. So an approximate trace (or an alternate heuristic to find mu) is fine.

2. @larsmans: using n matrix-vector multiplies to calculate the trace would dominate the overall runtime for many applications. An approximation is better.

3. IIRC the limit as p goes to infinity of || M^p ||^(1/p) is the spectral_radius(M) for all matrix norms. So one reasonable heuristic for mu would be the average of the smallest and largest eigenvalue as estimated using Arnoldi iteration with big tolerances. The existing scipy.sparse.linalg.eigs doesn't have the right interface for this but for this application most of the fanciness in ARPACK may not be needed and naive Arnoldi with a dozen or so iterations may work?

**Comment by nmayhall-vt** [comment]
I've recently run into this problem, and I'm wondering if any progress has been made since this issue was raised. It seems like giving LinearOperator the option to define it's own trace should solve the problem (but I'm not very experienced with this interface). I'm using Scipy version 1.1.0.

**Comment by dkafri** [comment]
Hello from the future! I have also just run into this problem. I'm using Scipy version 1.5.1.  Are there any workarounds?

**Comment by chiwhalee** [comment]
I run into this problem also. expm_multply should be useful in many occasions, provided an abstract LinearOperator interlace is supported.   @argriffing

**Comment by pdcook** [comment]
This seems to still be an issue nearly 6 years later - are there any plans to fix this in the next version? @argriffing

**Comment by rgommers** [comment]
There's a fix in gh-14143, it'd be great if someone could help test/review it.
