### ISSUE TITLE
Bizarre behavior of stats.poisson.cdf

### ISSUE THREAD

**Issue by SodiumHydroxide** [scipy/scipy#5107]
There seems to be a sudden value jump, or discontinuity, at mu=1 in the Poisson distribution's cumulative distribution function as implemented in scipy.

`from __future__ import division`
`from scipy.stats import poisson`

`poisson.cdf( 0.9999 , 0.9999/64. )`
**0.98449797528229299**
`poisson.cdf( 0.99999 , 0.99999/64. )`
**0.98449659083298868**
`poisson.cdf( 0.999999 , 0.999999/64. )`
**0.98449645238816541**
`poisson.cdf( 1. , 1./64. )`
**0.9998791938336179**

**Comment by WarrenWeckesser** [comment]
The Poisson distribution (https://en.wikipedia.org/wiki/Poisson_distribution) is a discrete distribution.  Only the integer part of mu is considered, e.g.:

```
In [245]: poisson.cdf(0, 1.0/64)
Out[245]: 0.98449643700540845

In [246]: poisson.cdf(0.5, 1.0/64)
Out[246]: 0.98449643700540845

In [247]: poisson.cdf(0.99999999, 1.0/64)
Out[247]: 0.98449643700540845

In [248]: poisson.cdf(1, 1.0/64)
Out[248]: 0.9998791938336179

In [249]: poisson.cdf(1.1, 1.0/64)
Out[249]: 0.9998791938336179
```
