### ISSUE TITLE
boxcox transform edge cases could use more care

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#5112]
See http://stackoverflow.com/questions/31833962.

According to the scipy docs, the `boxcox` data transform tries to find a maximum likelihood value of lambda if none is provided. But it doesn't seem to handle edge cases or bad inputs well.

``` python
>>> import numpy as np
>>> from scipy.stats import boxcox                                              
>>> boxcox(np.array([1.0, 1.0, 2.0, 3.0, 5.0])) # maybe OK? But docs say lambda is non-negative...
(array([ 0.        ,  0.        ,  0.63539331,  0.95825835,  1.32030256]), -0.25477193181221375)
>>> boxcox(np.array([[1.0, 1.0, 2.0, 3.0, 5.0]])) # traceback in the optimization
>>> boxcox(np.array([1.0, 1.0, 1.0])) # low-level warnings, and an arbitrary lambda is returned
```

**Comment by WarrenWeckesser** [comment]
@argriffing wrote:

>
    >>> boxcox(np.array([1.0, 1.0, 2.0, 3.0, 5.0])) # maybe OK? But docs say lambda is non-negative...
    (array([ 0.        ,  0.        ,  0.63539331,  0.95825835,  1.32030256]), -0.25477193181221375)
This is OK.  While the input array `x` must have strictly positive values, the transformed array may have values less than or equal to zero, and lambda can be negative.

The first line of the docstring is

    Return a positive dataset transformed by a Box-Cox power transformation.

which might be confusing.  The data that is *returned* is not necessarily positive; it is the input that must be positive.  This could be rephrased to be less ambiguous.

The second example is

    >>> boxcox(np.array([[1.0, 1.0, 2.0, 3.0, 5.0]])) # traceback in the optimization

That still raises an exception:

    ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

The description of `x` in the docstring says "Should be 1-dimensional" and  in fact, passing a 2-d array causes that error.  It would be nice if the function validated the shape, and gave a more informative error message in the exception.  And really, the docstring should be edited to replace "Should be..." with "Must be...".

The input in the last example is an array in which all the values are the same:

    >>> boxcox(np.array([1.0, 1.0, 1.0])) # low-level warnings, and an arbitrary lambda is returned

The behavior hasn't changed:

```
In [9]: boxcox(np.array([1.0, 1.0, 1.0]))                                       
/Users/warren/miniconda36/lib/python3.6/site-packages/scipy-1.3.0.dev0_-py3.6-macosx-10.7-x86_64.egg/scipy/stats/morestats.py:910: RuntimeWarning: divide by zero encountered in log
  return (lmb - 1) * np.sum(logdata, axis=0) - N/2 * np.log(variance)
/Users/warren/miniconda36/lib/python3.6/site-packages/scipy-1.3.0.dev0_-py3.6-macosx-10.7-x86_64.egg/scipy/optimize/optimize.py:1959: RuntimeWarning: invalid value encountered in double_scalars
  tmp1 = (x - w) * (fx - fv)
/Users/warren/miniconda36/lib/python3.6/site-packages/scipy-1.3.0.dev0_-py3.6-macosx-10.7-x86_64.egg/scipy/optimize/optimize.py:1960: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
Out[9]: (array([0., 0., 0.]), 4.208073920827584)
```
The log likelihood function computes the log of the variance of the transformed data.  If the data is constant, the variance is 0, so computing the log of the variance generates an error.

If the input array is constant, the function should probably just raise an exception.  The Box-Cox transformation tries to make the data more normal.  If the input values are all the same, there is nothing it can do.

**Comment by WarrenWeckesser** [comment]
I've tagged this as a "good first issue" because the changes needed (in my opinion, anyway) are pretty clear:
* Improve the docstring to remove any ambiguity or possible confusion.
* Raise an error with a useful message if `x.ndim` is not 1.
* Raise an error with a useful message if all the values in `x` are the same.
