### ISSUE TITLE
confidence interval for nnls

### ISSUE THREAD

**Issue by licode** [scipy/scipy#5115]
Is there any way to output confidence interval of fitting parameters from scipy.optimize.nnls  http://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.optimize.nnls.html ?

**Comment by ev-br** [comment]
This tracker is for development *of* scipy, not for questions about *using* scipy.
These sorts of usage questions are best asked on scipy-user mailing list or StackOverflow --- there are more eyes there, hence there's a better chance of having a meaningful answer. I'm thus closing this issue.

That being said, I do not think `nnls` supports this out of the box. One simple thing you can do right now is to generate a set of synthetic problems consistent with errorbars of your input data. By solving these synthetic problems you get a distribution of the results, which you can analyze in any way you wish. Whether this makes sense or not in your particular situation, I've no idea, so YMMV.
