### ISSUE TITLE
scipy.signal.lfilter crashes on sample-by-sample filtering in scipy 0.16.0

### ISSUE THREAD

**Issue by jtorniainen** [scipy/scipy#5116]
Hi,

I have a piece of code that reads samples from a data source and filters them with a FIR filter as they arrive. This sample-by-sample filtering worked in scipy 0.15.0 but stopped working as I updated to 0.16.0 

This problem can be replicated with the following script:
```python
from scipy import zeros, signal, random

def filter_sbs():
    data = random.random(2000)
    b = signal.firwin(150, 0.004)
    z = signal.lfilter_zi(b, 1)
    result = zeros(data.size)
    for i, x in enumerate(data):
        result[i], z = signal.lfilter(b, 1, [x], zi=z)
    return result

if __name__ == '__main__':
    result = filter_sbs()
```
As stated the above script executes without error under scipy 0.15.0 but in the
newer version it produces this error

```
Traceback (most recent call last):
  File "filter_debug2.py", line 14, in <module>
    result = filter_sbs()
  File "filter_debug2.py", line 10, in filter_sbs
    result[i], z = signal.lfilter(b, 1, [x], zi=z)
  File "/usr/local/lib/python3.4/dist-packages/scipy/signal/signaltools.py", line 956, in lfilter
    out[ind] += zi
ValueError: non-broadcastable output operand with shape (1,) doesn't match the broadcast shape (149,)
 ```

Additional information
OS:				#1 SMP Debian 3.16.7-ckt11-1 (2015-05-24)
Python version: 3.4.3
SciPy version:  0.16.0

**Comment by ewmoore** [comment]
Thanks for reporting this.  There is a fix in PR #5118.
