### ISSUE TITLE
freqz for sos input

### ISSUE THREAD

**Issue by cle1109** [scipy/scipy#5138]
I saw there is some discussion going on in #3259 about supporting other input formats in addition to `b, a`. I couldn't figure out if something has already been decided, but I think supporting `sos` filters is really important. I already implemented a `sosfreqz` function that accepts a `sos` matrix and basically forwards the calculations to `freqz`. Are you guys interested? If yes, I could create a PR.

**Comment by pv** [comment]
cf https://github.com/scipy/scipy/pull/4465

**Comment by cle1109** [comment]
Ah, I didn't see that - thanks, I'll comment over there.
