### ISSUE TITLE
0.16.0 fails to build on OS X; can't find Python.h

### ISSUE THREAD

**Issue by tdsmith** [scipy/scipy#5154]
I'm having trouble building scipy 0.16.0 for Homebrew. The Python includes directory doesn't seem to be added to the compiler search path.

Here is a transcript of a failed build: https://gist.github.com/tdsmith/2bd137bf0c502be96746#file-01-python-L4146-L4158

I've tried building this a few ways and I think I'm seeing this building within Homebrew against both system Python and Homebrew Python, with versions of numpy which both do and do not contain the patch in numpy/numpy#5866, but I may be confused.

0.15.1 is building fine. I'll keep looking but I wanted to see if y'all had any insight before I got too deep in the weeds.

**Comment by rgommers** [comment]
It looks like ``fwrappers`` which was added in 0.16.0 in ``scipy/linalg.setup.py`` is the only lib built with ``add_library`` that needs Python.h

I can't reproduce the issue with my older Homebrew install. Can you try if this fixes it: https://github.com/rgommers/scipy/commit/92a47a38e67f13ad72151e046fbc2c72c336edfe ?

**Comment by tdsmith** [comment]
It does fix the build. Weirdly, this happens while building against system Python, which shouldn't be exposed to our distutils.cfg. This error shows up on the test bot and I can reproduce it on my machine but  we got a pull request for scipy 0.16.0 from someone who wasn't having any trouble.

**Comment by tdsmith** [comment]
-- Thanks for your quick response! Do you think this is the right solution?

**Comment by rgommers** [comment]
I suspect something could be improved in ``numpy.distutils`` as well, but the problem is that any fixes there aren't useful - we need to support older numpy versions. So yes, I think this is the way to go. I'll submit a PR.

**Comment by rgommers** [comment]
I'm not sure if the ``distutils.cfg`` usage in Homebrew is reversible? That would be an even faster fix, so Scipy 0.16.0 starts building again (my fix can only land in 0.16.1).

**Comment by tdsmith** [comment]
This doesn't seem related to our distutils.cfg problems; I can reproduce this with Apple's system python, which doesn't look at our distutils.cfg, and an unpatched numpy 1.9.2.

A delay until a fix lands probably isn't urgent; nobody's complained about build failures on Homebrew with a self-installed numpy because those users are all getting wheels.

Thanks again; I'll add this patch to our formula.

**Comment by rgommers** [comment]
@tdsmith okay, sounds good then. I'm not sure then why I can't reproduce it and others haven't seen this either. But if my patch makes the problem go away, that's good enough for me right now.
