### ISSUE TITLE
Spyder, scipy.sparse.linalg librarie problem

### ISSUE THREAD

**Issue by PabloPacheco** [scipy/scipy#5157]
hi
i am trying to use in Spyder v2.2.5 the function scipy.sparse.linalg.linsolve, but it is not recognized. It is possible to get it? or exist another way alternative to Spyder to use this function?

**Comment by argriffing** [comment]
That's a module not a function. Maybe try [`spsolve`](http://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.spsolve.html#scipy.sparse.linalg.spsolve)?
