### ISSUE TITLE
stats.poisson error when using large arrays

### ISSUE THREAD

**Issue by nvulic** [scipy/scipy#5159]
Hi, I'm using the scipy.stats.poisson.isf and scipy.stats.poisson.sf functions and get incorrect values when I use a large array for my inputs. Specifically, the call 
prob = scipy.stats.poisson.sf(min_counts, expected)
includes arrays which are each 1D vectors of length ~20,000. The probabilities I get should eventually reach 1.0 but always max. out around 0.5. I've checked individual values using a single call to the function and get the required probability of 1.0. I haven't read that there is a limit to the size of an array you can use to scipy.stats functions. Thanks, 
-Neven

import scipy.stats

Python 2.7.8
>>> scipy.version.version
'0.14.0'
>>> numpy.version.version
'1.9.0'

**Comment by WarrenWeckesser** [comment]
There shouldn't be a limit.  Please include code that we can run to reproduce the problem.

**Comment by nvulic** [comment]
Hi, I've pasted the code I used below, but it requires 2 images that I read in that are very large files, they are approximately 5000 by 5000 pixels. I have made these images available at the following dropbox link:
https://www.dropbox.com/sh/nief0qasmnczngn/AABU9l9ZUDRP_Aa9Ntbskjxra?dl=0
FYI I run the code on a computing cluster (website: sharcnet.ca), thanks.

CODE:

#!/usr/bin/python

#  http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.poisson.html

#  Do this for multiple energy bands [i.e. read in images for 0.5-2, 2-8, etc.]

#======================================================================
#  Data products required:
#   Exposure Map - Units: cm^2 * s * cts / photon --- exptime AFTER accounting for instrumental effects i.e. eff area, cts/phot
#   Background Map - Units: cts / pixel   --- IF background map can be appropriately made to account for varying PSF [or just assume an approximation?] then calculate sensmap for ENTIRE M31 field
#======================================================================


#from __future__ import division # confidence high
import os, sys

sys.path.append("/gwork/nvulic/soft/python-pkgs/lib/python2.7/site-packages/")  #  Need this to import mangle - not set in the gcc module loaded and .cshrc not sourced on python startup


import numpy
import pywcs
import pyfits
import re
import mangle
import scipy.stats



lgflux_range = numpy.linspace(-18, -10, 801)    #  declare flux range and number of elements
bin_lgflux=0.01
area = numpy.zeros((1801), dtype=numpy.float64)
area_cntrate = numpy.zeros((1801), dtype=numpy.float64)
pixsize=1.0/2.033   #  Chandra pixel scale in arcsec
apix=pixsize * pixsize / 3600.0 / 3600.0   #  Chandra pixel scale in degrees
binning=1
BAND="full"
p2e=2.96015419638e-09
prefix_dir="/gwork/nvulic/M31_counts_images/sensitivity_map/"

OUT = open (prefix_dir+"temp-calcs/m31"+BAND+"_sens_flux.acurve","w")


image_exp=[]
image_bkg=[]
image_wcs=[]
image_max_x=[]
image_max_y=[]


hdulist = pyfits.open(prefix_dir+"acis_i_s_band1_merged_emap.fits")

wcs_current=pywcs.WCS(hdulist[0].header)
image_wcs.append(wcs_current)
image_wcs=numpy.asarray(image_wcs)
image_max_x.append(hdulist[0].header['NAXIS1'])    #  Gives the max pixel value (size) from the exposure map
image_max_y.append(hdulist[0].header['NAXIS2'])


expmap = hdulist[0].data  #  access the data from the exposure map - make sure block 0 is the data
hdulist.close()
mask=expmap>0  

hdulist = pyfits.open(prefix_dir+"temp-calcs/bkg_map_dmimgpm.fits")

bkgmap = hdulist[0].data  #  access the background map that is identical in size to the expmap - store in bkgmap
hdulist.close()
mask2=bkgmap>0  


image_exp=numpy.asarray(image_exp)
image_bkg=numpy.asarray(image_bkg)
image_wcs=numpy.asarray(image_wcs)
image_max_x=numpy.asarray(image_max_x)
image_max_y=numpy.asarray(image_max_y)



xy=[]

#  MASKING - what does the binning do? excludes 10 of 11 pixels along x and y axes throughout

for ix in numpy.arange(1,image_max_x,binning):       #  loop through every pixel in the given image with given binning
    for iy in numpy.arange(1,image_max_y,binning):

        if (mask[iy-1,ix-1]) and (mask2[iy-1,ix-1]): # numbering starts from 0, pixels (image_max_x/y) from 1. --- if expmap>0 at the (x,y) pixel location then:

        #  INCLUDE bkgmap mask as well - if any bkgmap values = 0 and expmap >0 then exclude.

            xy.append((ix,iy))     #  Add the pixel location (x,y) to the xy array, which is an array of pixel locations

            #print ix, iy, expmap[iy-1,ix-1]


wcs = image_wcs      #  access the WCS values for the current image
xy_coord = numpy.array(xy, dtype=numpy.int)     #  store the pixel locations to be masked as an integer array - 2 cols (x,y)


#  Include ALL X [:,0] & Y [:,1] values and subtract since xy_coord was pixel values 1 to max_x/y

x_active=xy_coord[:,0]-1    #  store co-ordinates for masking (only those that are TRUE)
y_active=xy_coord[:,1]-1    #  exclude all values that fall on point sources?

#  haven't transposed the images yet so do it now
bg= bkgmap[y_active, x_active]    #  image arrays are indexed [y,x] (-1 already taken into account just above)
exp=expmap[y_active, x_active]    #  only includes the pixel locations that don't have point sources i.e. masked image
        


ilgflux=-int(lgflux_range[0]/bin_lgflux)     #  length of 1, value is = 1800 (+ve integer)
    #  area has 1801 elements vs. 801 for the flux range

#  The code is looping through EACH VALUE in image_exp of the exposure map currently
    
for lgflux in lgflux_range:                #  each flux in the range logf=-18 to -10 (801 elements) -- lgflux = log(flux)
    

        expected = 10**(lgflux) / p2e * 0.7 * exp + bg       #  T = total source cts in a detection cell = S + B = {eqn (5) of MNRAS 2008 Georgakakis, A.} + {bg} --- --- --- expected = {f_x * (1/p2e) * eta * t_exp} + bg
        #  I estimate the expected number of counts that this flux will produce over the CCD array. Note that exp, bg and hence expected are 2-d arrays (images). exp is for the exposure map, bg is for the background map, p2e is the count to flux coversion factor and 0.7 is the detection cell encircled energy fraction.
        #  This means that the calculation is essentially done for ALL fluxes in the range logf=-18 to -10 --- an image (expected array) is made for EACH flux and the number of cts estimated [turns out to be a distribution that peaks near the EXPECTED cts for THAT specific pixel!]

        #  then you estimate the minimum counts for detection, which simple the poisson probablity. Note that bg and hence min_counts are 2-d arrays.
        
        min_counts = scipy.stats.poisson.isf(0.001, bg)    #  4e-6 is the pns value they use - mine should be 0.001?

        #  The min_counts is based only off the background map and the Poisson prob.

        #  and finally you estimate the probablity that the flux will produce counts above min_counts
        #  NOTE: min_counts is taken to be an integer, no difference in prob whether 1.0 or 1.9

        prob = scipy.stats.poisson.sf(min_counts, expected)

        #  the area curve is then the sum of the prob array:
        area[ilgflux]  = area[ilgflux]+ prob.sum()    #  ADD prob to the array as you loop through the various fluxes
        #  aray 1801 elements-successive values stored (only elements from 1000-1800 used ) as ilgflux decreased at end of loop
        #  area : is an array of the probability that a given flux would be detected = area curve! [800 values of fluxes]
        #  NOTE: area added consecutively for however many images you have that you are analyzing (10 images, 10 prob. values added for EACH flux)
        

        ilgflux=ilgflux-1

        
ilgflux=-int(lgflux_range[0]/bin_lgflux)    #  reset ilgflux to max value of 1800
for lgflux in lgflux_range:

    #  Stores output for area curve of ALL images processing at each flux in the flux range
    print>>OUT, "%7i %10.3f %10.3e" % (ilgflux, lgflux, area[ilgflux] * apix * binning * binning)

    ilgflux=ilgflux-1     #  store values backwards from 1800 to 1000 (indexes)

print "DONE"
OUT.close()
sys.exit(0)

**Comment by WarrenWeckesser** [comment]
Thanks.  A lot of that code looks irrelevant to the issue.  Any chance you could pull out one set of data that causes the surprising result in the call to the `sf` method? Maybe just print the arguments to a file (or even the terminal) when you get the unexpected result.

**Comment by nvulic** [comment]
I found the error (in my code) thanks for all your help!
