### ISSUE TITLE
Implement Owen's T function and use it in stats.skewnorm

### ISSUE THREAD

**Issue by Quantum-cross** [scipy/scipy#5160]
It would be nice to have an implementation of the [skew-normal](https://en.wikipedia.org/wiki/Skew_normal_distribution) distribution in scipy. I spent an entire day trying to generate random numbers from a skew-normal distribution in python (when Mathematica could do 50,000 in 6ms, I could only manage 2 minutes). I finally found [this implementation on the mailing list](http://permalink.gmane.org/gmane.comp.python.scientific.user/33310) and using that I could generate a set in 11ms!

In that implementation there is also an implementation of [Owen's T function](https://en.wikipedia.org/wiki/Owen%27s_T_function). This is used in the CDF of the skew-normal distribution. If the skew-normal is implemented, this function might as well go into scipy.special as it is an [important function in statistics](why).

I'm no expert, but the [implementation](http://permalink.gmane.org/gmane.comp.python.scientific.user/33310) seems well developed with tests, and comes with a license.
Thanks for taking the time to consider my request! I love scipy :)

**Comment by ewmoore** [comment]
If the code you linked was written by looking at R's sn package (GPL), then we can't use it in scipy, since it isn't license compatible.  Boost has Owen's T function, which could be converted and used.

**Comment by ewmoore** [comment]
As to generating random numbers using that distribution, [this](http://azzalini.stat.unipd.it/SN/faq-r.html) page's solution B seems fairly straightforward.

**Comment by dnlbunting** [comment]
I should be able to have a go at implementing this

**Comment by robcross** [comment]
Awesome! It would still be greatly appreciated :)

**Comment by dnlbunting** [comment]
So implementing solution B from @ewmoore's link we can beat mathematica and generate 50,000 samples in 5ms. I just have to tidy it up then I'll make a PR

**Comment by dnlbunting** [comment]
Made a PR for this now #5627

**Comment by ev-br** [comment]
gh-5627 has been merged. It implements skewnorm with a generic cdf, rather than the Owens function.

**Comment by person142** [comment]
Removing the `special` tag since that part is complete.

**Comment by sethtroisi** [comment]
```
import scipy.stats

shape = (1, 50000)
%time x = scipy.stats.skewnorm.rvs(a=0.75, size=shape)
%timeit x = scipy.stats.skewnorm.rvs(a=0.75, size=shape)
```
```
CPU times: user 9.21 ms, sys: 0 ns, total: 9.21 ms
Wall time: 10.9 ms
100 loops, best of 3: 5.59 ms per loop
```

Owen's T function was implemented
And skewnorm seems pretty fast.

---

@ev-br @dnlbunting In #5627 you said 
> "What I haven't done is implement Owen's T function, which would likely improve the speed/accuracy of the cdf function a bit compared to the default integration in _distn_infrastructure currently used." 

Now that Owen's T function is implemented would it be worth revisiting this?

**Comment by sethtroisi** [comment]
Nevermind this was already done in https://github.com/scipy/scipy/pull/8473
