### ISSUE TITLE
RIFF header vs Scipy for odd length payloads

### ISSUE THREAD

**Issue by dodomac** [scipy/scipy#5175]
Hi, the RIFF specification states;

http://www.kk.iij4u.or.jp/~kondo/wave/mpidata.txt (definitive guide?)

     ckSize    A 32-bit unsigned value identifying the
               size of ckData. This size value does not
               include the size of the ckID or ckSize
               fields or the pad byte at the end of
               ckData.
     ckData    Binary data of fixed or variable size. The
               start of ckData is word-aligned with
               respect to the start of the RIFF file. If
               the chunk size is an odd number of bytes, a
               pad byte with value zero is written after
               ckData. Word aligning improves access speed
               (for chunks resident in memory) and
               maintains compatibility with EA IFF. The
               ckSize value does not include the pad byte.

     <WORD>    16-bit unsigned        unsigned int
               quantity in Intel
               format

However, if I do this and read my HFP wav file via scipy,
<pre>framerate, data = scipy.io.wavfile.read(filepath)</pre>

 it complains with;
<pre>string size must be a multiple of element size</pre>

A bit more debugging added to my test code and numpy (multiarray/ctors.c) gives:

<pre>
Sample file is 16 bits, note that 24 bit samples do not work in scipy
Got error type "ValueError"
Analysis of the wav file encountered a problem: "slen: 48683, itemsize: 2 - string size must be a multiple of element size"
</pre>

i.e. my payload length is odd, reflecting the actual payload as per the the spec. The length of the file reflects the additional pad byte.

So for odd length payloads; 
* we have the spec saying do not add the pad byte to the payload length, but only to the file length, 
* scipy likes the payload length to be even.
* If I add the pad byte to to the payload length and the file length, scipy is happy.
* If I want to follow the spec then no one can load my files into scipy.

Am I misunderstanding something?

What is the correct thing to do in this case?
* Follow the spec
* Follow scipy
* Fix scipy

I believe it should be to fix scipy unless I am looking at the wrong spec.

I have tried this on scipy version 0.16.0 on Ubuntu 14.04 LTS

**Comment by WarrenWeckesser** [comment]
On the mailing list, I asked for clarification of what an "HFP" file is.  Are you referring to the files used in the "Head First Programming" book at http://examples.oreilly.com/9780596802387/ ?

We really need a reproducible example to help debug the problem (if there is, in fact, a problem).  At this point, I'm not convinced there is a problem.  If (as confirmed in an email on the mailing list) the data is 16 bit, how can `ckSize` (the payload data length, in bytes) be odd?

**Comment by dodomac** [comment]
Hello,

Sorry for not replying on this as I got moved onto other work and haven't had time to revisit this as it didn't occur often.

Yes the payload is HFP audio and 16 bit, and yes you are right it should never be odd. I believe now the problem occurs earlier in legacy code that records a sound played over Bluetooth using HCI dump, then takes this data and adds the RIFF. It is very crude for handling incoming audio data as it also encodes any noise it receives and hence ends up with an odd payload.

What is a better way to record HFP audio received over Bluetooth? We are using pulse audio and bluez on Ubuntu 12.04 LTS.

Thanks,
Joseph

**Comment by WarrenWeckesser** [comment]
Thanks for the update.   It sounds like the problem is a bug in the code that creates the RIFF, and not a scipy issue.

> What is a better way to record HFP audio received over Bluetooth? We are using pulse audio and bluez on Ubuntu 12.04 LTS.

That sounds like a question for a programming forum.  Perhaps you could try asking on the mailing list, or on a site such as stackoverflow, the Ubuntu forums, or a DSP forum.
