### ISSUE TITLE
Rbf interpolation - use only K nearest neighbors

### ISSUE THREAD

**Issue by denfromufa** [scipy/scipy#5180]
Rbf gets impractical for more than 3..4 dimensions, because all pairs of distances are tracked (>10k points). Is it possible to speed up and reduce memory consumption for Rbf by using only K closest neighbors from KDTree?

**Comment by denfromufa** [comment]
Here is the implementation I was looking for:

https://gist.github.com/mfouesneau/7611835b3a6fb69de6cb

**Comment by ev-br** [comment]
Cross-ref https://github.com/scipy/scipy/pull/5070 for looking at/fixing up Rbf interpolation. @jjgreen

**Comment by denfromufa** [comment]
I looked at cross-ref #5070 and it seems to be completely independent from this feature request. if @mfouesneau would allow to merge his code into scipy, that would be great!

**Comment by mfouesneau** [comment]
Sure please do. You might want to replace the KDTree with an approximative nearest neighbor search for large datasets.

**Comment by Ethunxxx** [comment]
Is there any update on this topic?

**Comment by rgommers** [comment]
done in gh-13595, closing
