### ISSUE TITLE
linalg.eig returns complex eigenvalues and linalg.eigh raises exception

### ISSUE THREAD

**Issue by cle1109** [scipy/scipy#5182]
I stumbled upon a generalized eigenvalue problem where `linalg.eig` returns complex eigenvalues and `linalg.eigh` raises an exception:

    numpy.linalg.linalg.LinAlgError: the leading minor of order 64 of 'b' is not positive definite. The factorization of 'b' could not be completed and no eigenvalues or eigenvectors were computed.

I call the functions with two input arguments `sigma1` and `sigma1 + sigma2` (both arguments are symmetric). Therefore, the eigenvalues should be real, but they're complex in the case of `eig`. This might be due to numerical errors, which is not unexpected. However, I don't understand why `eigh` raises an exception in this case.

For reference, MATLAB's `eig` function works as expected and returns real eigenvalues.

Is there a preferred way I can share the two matrices `sigma1` and `sigma2` to reproduce this issue?

**Comment by pv** [comment]
These computations are performed by LAPACK, and the results and errors
are due to it. eigh(..., turbo=True) is DSYGVD, eigh(..., turbo=False)
is DGSYGV, eig is DGGEV. You may want to check your Scipy binary uses a
new enough version. (Matlab also uses LAPACK, but not necessarily
exactly the same version.)

**Comment by pv** [comment]
Note that this bug report is currently not actionable. It would be necessary to provide a self-contained test program and data files that exhibits the error.

**Comment by cle1109** [comment]
Yes - I have the example matrices stored as a .mat file - is there a preferred way of sharing such data here?

**Comment by pv** [comment]
Github issues don't support attachments. The easiest way probably is that you create a repository on github, upload the program+files there, and then paste a link to it here.

**Comment by cle1109** [comment]
OK, good idea. Here is the link: https://github.com/cle1109/testeig

**Comment by pv** [comment]
The test program works OK with LAPACK 3.5.0 / OpenBLAS 0.2.12.
However, the eigenvalues reported by eig and eigh differ, so something is probably still problematic.

**Comment by pv** [comment]
The problem here is probably that `s2` is not positive definite, which is required by `eigh`.
The results from `eig` appear to match matlab.

**Comment by pv** [comment]
If you can confirm that the real part of the eigenvalues is computed correctly by `eig` and that the imaginary parts are ~ rounding error, then it appears there's no apparent bug.

**Comment by cle1109** [comment]
I'll check that in a minute. However, I still found it strange that `eigh` doesn't work, because it doesn't require positive definite inputs (or does it?).

**Comment by pv** [comment]
eigh and the underlying LAPACK routines require PD inputs, cf
https://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.linalg.eigh.html
 (although it appears there's been some editing mishap and it reads
"definite positive"...)

**Comment by cle1109** [comment]
OK, got it. I compared the eigenvalues from MATLAB and `eigh`, and `np.isclose` is `True` for all but one eigenvalue, namely the third. The difference here is -0.00014362782820176445.

**Comment by cle1109** [comment]
Since this is the expected behavior of `eigh`, I'll close this issue. Thanks for your help!
