### ISSUE TITLE
Some? wheels don't express a numpy dependency

### ISSUE THREAD

**Issue by tdsmith** [scipy/scipy#5184]
Installing scipy from a wheel from PyPI with `pip install scipy` in an empty virtualenv on OS X, numpy is not installed as a dependency of scipy. I suspect this is because setup.py is not executed on the client when installing from a wheel, and the conditional logic that detects whether installing numpy is necessary finds numpy on the wheel builder, so the dependency is not encoded in the wheel metadata. scipy-0.16.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl is affected but I imagine that's generally the case.

I would have suggested that numpy should always be an install_requires dependency but from comments in setup.py it looks like there may be reasons not to do that?

**Comment by josef-pkt** [comment]
We had several discussions about this, and the main reason not to specify a numpy requirement if numpy is already installed, is that we don't want to trigger an automatic update of numpy. Automatic updates of requirements was, and I guess still is, the default behavior of pip.

numpy is too important for many packages to change the version without explicit instructions by the user.

(I don't know if that's the specific issue here.)

**Comment by pv** [comment]
The bdist* commands probably should however always add numpy to
install_requires.
.
All this is brittle, and I'm not sure if we should just tell people to
remember to add `--no-deps` when using `pip --upgrade`.

**Comment by josef-pkt** [comment]
IMO, when there is no good or perfect solution, then it's better to make the error on being too cautious. 

I got burned often enough before I started to remember the `--no-deps` option when using pip. But I'm not really up to date on distribution issues, since I have been avoiding those for a while now.

**Comment by tdsmith** [comment]
I guess that means that pip install --upgrade scipy has different behaviors wrt numpy depending on how scipy was installed and, if from an sdist, the python environment at the time of installation. (My personal preference would be that scipy consistently behaves like other Python packages. Better the devil you know!)

**Comment by rgommers** [comment]
@tdsmith the devil you know is something that >90% of the userbase has zero knowledge of. So I'd rather annoy the people who know how to fix the issue by themselves.

Here is the actual issue: https://github.com/pypa/pip/issues/59. I doubt anyone will convince the pip developers at this point of the error of their ways no matter how many people add +1 to an issue like that. 

Until either pip finally gets sane behavior or we have OS X + Windows wheels that are completely reliable for numpy and scipy (a long way off on Windows I'm afraid) I'm unwilling to use ``install_requires``.

**Comment by rgommers** [comment]
@pv ``bdist_wheel`` is probably the only relevant ``bdist`` command by now, and you do have a point that adding numpy to install_requires in that case now is OK. It will make things work smoother for the OS X wheels that we do have.

**Comment by rgommers** [comment]
Adding the 0.17.0 milestone to not forget about that for the next release.

**Comment by rgommers** [comment]
Hmm:

    $ pip install scipy
    Collecting scipy
      Using cached scipy-0.16.1.tar.gz
    Building wheels for collected packages: scipy
      Running setup.py bdist_wheel for scipy

that kind of defeats the argument that it only affects OS X (only platform we have wheels for).

**Comment by rgommers** [comment]
Attempt at a fix in gh-5477
