### ISSUE TITLE
Unable to import the latest scipy (conda install)

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [scipy/scipy#5185]
I am currently unable to import scipy in a conda Python 3.4.3 environment in Linux
![screen shot 2015-08-26 at 2 57 21 pm](https://cloud.githubusercontent.com/assets/1993919/9503114/11416b20-4c03-11e5-91da-8d96f61002c7.png)

`Linux SMP Tue Aug 21 17:10:18 EDT 2012 x86_64 x86_64 x86_64 GNU/Linux`

Full `pip freeze` [here](https://gist.github.com/amelio-vazquez-reina/57a73b5db8f11a54777a)

**Comment by pv** [comment]
Support for Anaconda packages is provided on the corresponding issue
tracker:
https://github.com/ContinuumIO/anaconda-issues/issues

**Comment by amelio-vazquez-reina** [comment]
Thanks @pv I appreciaate it. Closing here then

**Comment by pv** [comment]
Or, it appears they tell you to use their mailing list
https://groups.google.com/a/continuum.io/forum/?fromgroups#!forum/anaconda
