### ISSUE TITLE
missing functions in scipy.signal listed in documentation

### ISSUE THREAD

**Issue by idkwtp** [scipy/scipy#5196]
http://docs.scipy.org/doc/scipy/reference/signal.html
under the Spectral Analysis section of the scipy.signal documentation online 7 functions are shown. I've updated to the latest version of scipy, but only the four of those functions exist in it; periodogram, welch, lombscargle, and vectorstrength. csd, coherence, and spectrogram are missing.

**Comment by pv** [comment]
You are probably using a different version of Scipy. That the
documentation for these functions is there indicates also the functions
are there.
