### ISSUE TITLE
BUG: linprog returns incorrect (suboptimal) solution scipy.optimize defect

### ISSUE THREAD

**Issue by amwamw** [scipy/scipy#5211]
```python
from scipy.optimize import linprog
"""
max z = 2x + 3y + 2z
st
2x + y + z <= 4
x + 2y + z <= 7
z          <= 5
x,y,z >= 0
"""
A=[[2,1,2],[1,2,1],[0,0,1]]
b=[4, 7, 5]
c=[-2, -3, -2]

res = linprog(c,A_ub=A, b_ub=b,bounds=(0,None),options={"disp": True})
print(res)
```

**returns**
<pre>
Optimization terminated successfully.
         Current function value: -10.666667  
         Iterations: 2
  status: 0
   slack: array([ 0.,  0.,  5.])
       x: array([ 0.33333333,  3.33333333,  0.        ])
 message: 'Optimization terminated successfully.'
     fun: -10.666666666666666
     nit: 2
 success: True
</pre>

**issue**

The above solution: <pre>10.66 at [0.33, 3.33, 0]</pre> is a __suboptimal__ corner point feasible solution.

The optimal solution should be <pre>11 at [0, 3, 1]</pre>

This correct optimal solution was confirmed using Mathematica's *LinearProgramming* function and visually:

<img width="464" alt="untitled-1" src="https://cloud.githubusercontent.com/assets/14061893/9590648/e5165978-502d-11e5-9076-725c5840d35f.png">

**Comment by pv** [comment]
The solution you state is correct does not satisfy `A*x <= b`.
Indeed, `x=[0, 3, 1]; np.array(A).dot(x) == [5, 7, 1]`
but `b = [4, 7, 5]`.

**Comment by pv** [comment]
Indeed, you have a typo in your A matrix. If you write it actually correctly, it gives the expected solution.
