### ISSUE TITLE
Math error: expm, sinm, cosm, etc. all computes wrongly in scipy.linalg

### ISSUE THREAD

**Issue by xuancong84** [scipy/scipy#5215]
I am not sure whether the implementer knows how to compute these infinite polynomial functions for matrices or not.

The standard Lie algebra arithmetic is as follows:
1. you diagonalize the input matrix using SVD, A=U*S*V', make sure that V'*U=I (identity)
2. apply the function (e.g., sin, cos, exp, etc) on every diagonal elements of S to obtain func[S], taking note that exp[S] is NOT the same as the element-wise exponential function, exp(S), because in element-wise exp(S), off-diagonal elements will become 1 since exp(0)=1
3. compute final result, expm(A)=U*exp[S]*V'
Use Matlab or Mathematica to verify the results.

The Lie Algebra arithmetic is derived according to Taylor expansion, for example:
expm(A)=1+A+A^2/2!+A^3/3!+A^4/4!+...
where A can be a matrix, and the series will always converge because the denominator is a factorial.
As a result, A^2=(U*S*V')*(U*S*V')=U*(S^2)*V' since V'U=I, and so on.
Thus, funcm(A) = U * func[S] * V', where func[S] means apply func on every diagonal elements of S while keeping off-diagonal elements 0.

**Comment by pv** [comment]
What you describe is a naive way to do the computation. Neither Scipy
nor Matlab does the calculation that way. If you claim the
implementation gives incorrect results, please give an example matrix.

**Comment by pv** [comment]
It appears to be the same:
```
>>> import numpy as np
>>> from scipy.linalg import cosm, sinm
>>> A = np.random.rand(30,30)
>>> x = 2*sinm(A).dot(cosm(A))
>>> y = sinm(2*A)
>>> abs(x-y).max()
1.7763568394002505e-15
```

**Comment by xuancong84** [comment]
Sorry, I made a mistake, I have completely changed the description and the title, the problem is that sinm(A) return a 2D array even if A is matrix. It confuses me.

**Comment by pv** [comment]
Ok, indeed, most of the functions do not preserve the ndarray vs. matrix input class.

**Comment by xuancong84** [comment]
Is it possible to check the input type for sinm(), expm(), etc? If the input is of matrix type, then return a matrix; if the input is a 2D array, then return a 2D array. That makes more sense. Otherwise, after every sinm(A), I have to wrap it by matrix(sinm(A)).
To users, sinm(2*A)==2*sinm(A)*cosm(A) makes more sense than sinm(2*A)==2*matrix(sinm(a))*matrix(cosm(a)), isn't it?
