### ISSUE TITLE
A suggestion: on the selection between element-wise operation and matrix-algebra operation

### ISSUE THREAD

**Issue by xuancong84** [scipy/scipy#5219]
From the issues:
- 1. in scipy.linalg: sinm(2 * A) does not equal to 2 * sinm(A) * cosm(A), but equals to 2 * matrix(sinm(A)) * matrix(cosm(A))
- 2. in real applications, for sin(A), where A can be a number, a n-dim array, or a matrix. Given any expression of A, when we change A's type from a number into a matrix, we also need to replace in the expression all function names from sin() into sinm() correspondingly, which is inconvenient, and sometimes cause errors if the user is not familiar
- 3. functions like sin, cos, etc., have their element-wise version, sin() and the corresponding matrix version, sinm(), but for multiplication and division * and /, A * B is matrix multiplication, but A/B is element-wise division, which seems to be self-inconsistent

I would like to make the following suggestions:
- 1. keep the current versions of sinm, cosm, etc functions
- 2. overload the sin, cos, exp, etc functions such that: if the input is a number, return a number; if the input is a n-dim array, perform element-wise arithmetic and return a n-dim array; if the input is a matrix, perform matrix algebra (i.e. sinm, cosm, expm, etc) and return a matrix
- 3. the same rule applies to multiplication and division, where A/B should be A * inv(B) if A and B are both matrices. Currently, when A and B are both matrices, A * B is matrix multiplication, but A/B is an element-wise division, which is self-inconsistent. Element-wise arithmetic should apply only if at least one of A and B is an n-dim array

The main self-inconsistency lies in that, the selection between element-wise operation and matrix-algebra operation:
- a) for functions like sin(), exp(), etc, it is done by appending a 'm' to the function name
- b) for multiplication * and functions like pow(), etc, it is done by checking whether the input is an n-dim array or a matrix
- c) for division, it is always element-wise regardless of input type

Thus, I feel that it is better to use the same rule (i.e. b) to perform the selection for all cases, that would make life easier.

Will this modification break too many existing packages?

**Comment by ewmoore** [comment]
The best way to avoid these inconsistencies is to avoid using `np.matrix`. To perform matrix multiplication, this means calling the `dot` function or ndarray method; in Python 3.5, you'll be able to use the `@` operator.  

I'd suggest taking this to the numpy discussion list.  There doesn't appear to by any actionable items here for scipy.  `np.matrix` is provided by numpy and all or essentially all of `scipy.linalg` returns arrays when given `np.matrix`.  I'm tempted to close this, but I'll hold off for a while if others wish to comment.

**Comment by pv** [comment]
The only actionable thing currently on scipy side would be to be
consistent in returning np.matrix output for np.matrix input.

**Comment by xuancong84** [comment]
If afraid of breaking existing package dependencies, 1 possibility is to implement new functions under scipy.linalg, i.e., scipy.linalg.sin, scipy.linalg.cos, scipy.linalg.exp, which gives matrix-in-matrix-out under matrix algebra, array-in-array-out under element-wise algebra, and number-in-number-out under standard algebra.
This would minimize the chance of incompatibility.

**Comment by larsmans** [comment]
The consensus in the NumPy/SciPy community is that `np.matrix` was a mistake and should not be used in new code. The confusion is real, but it can only get worse if we introduce more code that handles `np.matrix` specially.

I'm also not for @pv's suggestion. Existing code might rely on these functions returning `ndarray` even if the input is (inadvertently) an `np.matrix`.

**Comment by xuancong84** [comment]
@larsmans , @pv , I hope instead of complaining how bad is np.matrix or how bad is someone's suggestion, we should try to figure out a good solution, convenient to use. So, when the input is a nxn math object, how can existing operators and functions distinguish between element-wise operation and matrix operation?
By checking whether the input is an ndarray or matrix, or by checking whether the function name ends with 'm'? The existing solution, i.e. a), b), c) in the main post, is definitely not a good solution for users, because it is not consistent throughout, some use this, some use that, some use none. In particular, the * / operators cannot append a 'm'.
If you do not have time to implement, that does not mean you should try to reject others' suggestions. So what is the ideal solution in your mind?

**Comment by pv** [comment]
@xuancong84: you are jumping into a discussion that has been discussed before. The current approach used by most is to use ndarrays only.

**Comment by pv** [comment]
In principle, there could be room for a separate matrix object, but the user and developer experience so far with np.matrix has not been particularly good. The current design is however fixed in place due to backward compatibility issues, so the best option for new design would be to start from scratch. So far, nobody has made concrete suggestions, probably partly due to the fact that the ndarray-only works fine for most purposes.

**Comment by rgommers** [comment]
Nothing is going to happen here, so closing the issue,

@xuancong84 if you want to know more about the history, look at the "deprecate numpy.matrix" thread from February 2014 on the numpy mailing list. Also, Python 3.5 introduces the ``@`` operator which is a matrix multiplication operator for numpy arrays.
