### ISSUE TITLE
Discrepancies in scipy.optimize.minimize(method='L-BFGS-B')

### ISSUE THREAD

**Issue by benedictjheinen** [scipy/scipy#5231]
This page (http://docs.scipy.org/doc/scipy/reference/optimize.minimize-lbfgsb.html) describes the solver options one can pass to the L-BFGS-B' method of scipy's optimization package.

The docs mention two options for solver tolerance (although only one in the example), the one I would have preffered to use is 'factr', where the solver exits when: (f^k - f^{k+1})/max{|f^k|,|f^{k+1}|,1} <= factr \* eps (where epsilon is machine precision). However when I run my code is get a warning:

OptimizeWarning: Unknown solver options: factr

So I presumed this option has been deprecated in favour of ftol (not sure why it would be though?). ftol being a specified number (i.e. diff <= n rather than <= n \* machine_error).

That's fine by me, however the exit message I get for the solver is

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH

which suggests the L-BFGS-B routine is still using some value of factr which I do not know, and seemingly can't specify.

**Comment by dlax** [comment]
Yes, `factr` option got replaced by `ftol` to be more consistent with other solvers and avoid playing with machine epsilon. The documentation is wrong here and reference to this option should be dropped.

**Comment by benedictjheinen** [comment]
@dlax I'm not sure this is simply a documentation issue as the solver convergence messages also refer to factr, suggesting the value (perhaps a default set internally) is still used over ftol. e.g.
CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH

**Comment by benedictjheinen** [comment]
Line 489 in lbfgsb.py sets factr to be 1e7. There are also docstring references to the option (e.g. line 82)

**Comment by pv** [comment]
You should interpret `ftol = factr * eps`.

**Comment by pv** [comment]
Line 489 is dead code.

**Comment by benedictjheinen** [comment]
@pv are you referring to line 250: factr = ftol / np.finfo(float).eps ?
So the tolerance one sets through ftol is used by the code (only converted to a factor of the machine precision)?

This should definitely be made clear in the docs and cleaned up in the code
