### ISSUE TITLE
found a compat hack to support the unsupported numpy 1.5.x

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#5237]
Scipy requires numpy 1.6+ now so this could be removed by someone who knows more about numpy dtypes than I do.
https://github.com/scipy/scipy/blob/maintenance/0.16.x/scipy/sparse/sputils.py#L51

**Comment by argriffing** [comment]
These compatibility fixes had been added in https://github.com/scipy/scipy/pull/2678.

**Comment by matthew-brett** [comment]
Xxx X xxxx

**Comment by larsmans** [comment]
Added a patch for this to #5072.
