### ISSUE TITLE
Precompiled wheel for Python 3.5

### ISSUE THREAD

**Issue by willingc** [scipy/scipy#5242]
Python 3.5 was released today. I'm posting this as a reminder (or helpful tip) for those trying to `pip install scipy` for Python 3.5. You may need to build scipy from source until a  precompiled wheel is available on PyPi. 

Additional detail: https://bugs.python.org/issue25088

**Comment by rgommers** [comment]
@willingc thanks for the reminder. There is work in progress; once there are 3.5 OS X wheels for Numpy (any day now for Numpy1.10.0, @matthew-brett is working on it right now), the Scipy ones will follow.

Note though that there will not be any Windows wheels for the foreseeable future; the switch of MSVC runtime means that we cannot at the moment use the standard MinGW toolchain to build the scientific Python stack.

**Comment by willingc** [comment]
@rgommers Thanks for the update and the work (Yay, @matthew-brett :cake:).
