### ISSUE TITLE
Updating the FAQ regarding FITS

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#5243]
The FAQ (http://www.scipy.org/scipylib/faq.html) is apparently not hosted here but I don't know where else to file this, so...

Section "I want to load data from a text file. How do I make this code more efficient?", regarding the FITS format: the pyfits package is no longer independently developed and has been subsumed into the astropy project.

**Comment by pv** [comment]
cf https://github.com/scipy/scipy.org

**Comment by anntzer** [comment]
Superseded by scipy/scipy.org#105
