### ISSUE TITLE
signal.welch returns nan for non-nan data

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#5244]
The array at https://www.dropbox.com/s/vsegmo851wuqnsp/testdata.npy?dl=0 contains no nan, but `signal.welch` returns `nan` for its PSD.  Interestingly, `matplotlib.mlab.psd` (which is I believe the original implementation from which `signal.welch` was adapted) handles it fine.

**Comment by ewmoore** [comment]
There may not be any `nan`s in your data, but there are a number of non-finite values.
```
In [18]: d = np.load('../../junk/testdata.npy')

In [19]: np.all(np.isfinite(d))
Out[19]: False

In [20]: d[np.logical_not(np.isfinite(d))]
Out[20]:
array([-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
       -inf, -inf])
```

This is why you get an all `nan` output.  I'm not sure what matplotlib is doing here to make this work, but I don't know that I'm on board with silently changing `inf` to something else.  I guess `welch` and friends could grow a `check_finite` flag as all of the linear algebra routines use.

Let me ask you this, what do you expect to have happen when computing the power spectra of data containing `inf`?

**Comment by anntzer** [comment]
My bad, I simply didn't think about checking for infinities.  So I will file a bug on matplotlib's side instead.
I don't actually think `check_finite` is that necessary.  Feel free to close this, or keep it open if you think `check_finite` is a good idea.

**Comment by e-q** [comment]
I think the current behavior is ok, but if anyone disagrees, feel free to respond/reopen.
