### ISSUE TITLE
wishlist: root finding with box constraints

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#5249]
Every now and then I find myself sorely missing an analog of `brentq` for D>1.
`fsolve` is great, but it does not allow bounds, and that's limiting.  Since `fsolve` wraps MINPACK's `_hybr` and `_hybrj` and these two look very similar to `lmder` and `lmdif`, it seems <s>rather straightforward</s> doable to adapt the least-squares algorithms from gh-5044 (which generalize the latter) to root finding.

**Comment by nmayorov** [comment]
`least_squares` is perfectly suitable for root finding, I included an [example](http://scipy-cookbook.readthedocs.org/items/discrete_bvp.html) to the tutorial. 

As far as I understand, all approaches of solving the systems based on minimizing the sum of squares. From the documentation of `hybrj`, it uses "a modification of the Powell hybrid method", also known as dogleg. So use `method='dogbox'` --- and here you go) 

Maybe I'm not 100% right, but it seems like there is no difference whatsoever in practical approaches of solving least squares and systems of equations. Yes, these methods can converge to a local minimum, but what can you do (bounds should help to overcome that too).

**Comment by ev-br** [comment]
Do you understand the difference in e.g. minpack's `hybr` and `lmdif` routines? From a cursory glance they seem to be very similar but subtly different. Naively I'd expect that deep down inside the root-finding routine is indeed  minimizing the sum of squares of left-hand sides, but then for instance convergence criteria can somewhat differ.

**Comment by nmayorov** [comment]
Yes, as I wrote `hybr` uses dogleg (you can find a call to `dogleg` subroutine) algorithm for solving trust-region problems, assuming that Jacobian for a proper system of equations has full rank. The benefit of this is reduced complexity of each step (compute steps one time, then decrease a trust-region radius until a good agreement for quadratic model is established). Other than that, algorithm's logic should be almost the same as `lmder` (I don't insist that they are 100% equivalent, but I'm sure that the differences are not significant).

And you are right, that `ftol` convergence criteria might be changed. Also, if the sum of squares is not close to zero, the algorithm can produce a different message, like `Solution not found, try different starting point`.

So making root-finding procedure on top of `least_squares` is like adding syntax-sugar or something like that. I'm not convinced that is's really worth it (maintain wise) to introduce such a new function.

**Comment by ev-br** [comment]
This has run its course. Closing.
