### ISSUE TITLE
scipy.signal.lsim2 returns a wrong result for some transfer functions

### ISSUE THREAD

**Issue by jfosorio** [scipy/scipy#5255]
## Description

 The function _lsim2_ return wrong results for certain transfer functions. I notice that just by slightly changing the parameters of the transfer function the result returned was correct again. This behaviour happened around 4 out of 100 times  when I has evaluating random variations of a particular system. 

I have done some experiments changing the tolerance of the ode system under _lsim2_ but I did not succeed in having consistent results. I observed also that the function _lsim_ do not return the wrong result at least for the system I was evaluating. 
## Software
- scipy 0.16.0
- anaconda 2.3.0
- python 2.710
- x86x64( on darwin, but I have observed similar behaviour in on a windows machine)
## Code example

The following code shows two different transfer functions that are identical to the 8th more significant bit, one of them returns the wrong result, H, and the other one, H2, does not. 

``` python
import scipy.signal.ltisys as lti
from scipy.signal import sawtooth
import matplotlib.pyplot as plt
import numpy as np

Tchirp = 35e-6
ts = 9.50013571622e-10
t = np.arange(0, 5*Tchirp, ts)
#t = np.linspace(0, 1.9*Tchirp, num=round(2*Tchirp/1e-9))
BW = 500e6
fmcw = 500e6*sawtooth(2*np.pi*t/Tchirp)
Navg = 160.41666666666669

H = lti.lti(
    [ 3.35856979991219650e+23,
     2.200856866394299333e+29],
    [
    1.0000000000000000000e+00, 
    1.0952512602246981859e+08,
    8.3901936551890375000e+14,
    2.0936539012439662920e+21,
    1.3719627219081343178e+27       
    ])

H2 = lti.lti(
    [ 3.3585698e+23,
     2.20085687e+29],
    [
    1.00000000e+00, 
    1.09525126e+08,
    8.39019366e+14,
    2.09365390e+21,
    1.37196272e+27       
    ])
t, yH_lsim2, xout = lti.lsim2(H, U=fmcw/Navg, T=t)
t, yH_lsim, xout = lti.lsim(H, U=fmcw/Navg, T=t)
t, yH2_lsim2, xout = lti.lsim2(H2, U=fmcw/Navg, T=t)
```

The result of the these three calls to the functions is shown in the added plot. The result called **H2 lsmi2** is obviously wrong. 

![3f9oey2llfjkjzvnp0wuukopnqrocaguukqppnliqimllfjjpcwfukoppzjkiwullfjkjzuwf0oppzrkki0ulfjkkzvuwlwopzrskqn p1ziy9ida001aaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/815690/9889352/5c55a066-5bfa-11e5-91a9-b22762721002.png)
## Annex: Plotting

``` python
plt.plot(t/1e-6, fmcw/1e6, label = 'ideal')
plt.plot(t/1e-6, yH_lsim2/1e6, label = 'H lsim2')
plt.plot(t/1e-6, yH_lsim/1e6, label = 'H sim')
plt.plot(t/1e-6, yH2_lsim2/1e6, label = 'H2 lsmi2')
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
plt.show()
```

**Comment by rgommers** [comment]
@jfosorio thanks for the clear bug report. ``lsim`` was rewritten for 0.16.0 and is now more correct and much faster than ``lsim2``. The longer term plan is to get rid of ``lsim2`` completely (and ``impulse2`` / ``step2``), but in the meantime we could alias the ``*2`` versions to the better versions.

@jfosorio @WarrenWeckesser do you see any issues with that?

**Comment by WarrenWeckesser** [comment]
FWIW: Don't forget that `lsim2` is documented to be a wrapper of `scipy.integrate.odeint`.  While `odeint` is pretty robust, the underlying solver LSODA isn't really designed to handle such a discontinuous input.  The adaptive step size algorithm of LSODA is probably being "fooled" by the initial linear ramp, and then goes off the rails at the first discontinuity.

You can workaround this by passing additional keyword arguments to `lsim2` that are passed on to `odeint`.  In this case, tightening up the absolute error tolerance fixes the computation:

    t, yH2_lsim2, xout = lti.lsim2(H2, U=fmcw/Navg, T=t, atol=1e-9)

As I've said elsewhere, getting rid of `lsim2`, `impulse2` and `step2` is a good idea; the hard part is making versions of these that "just work" with as wide a variety of inputs as possible.

**Comment by jfosorio** [comment]
Thanks for the explanation. I wrote the issue as a way to keep things documented. @WarrenWeckesser the error happens just before the discontinuity, that was the reason I find it intriguingly .

**Comment by sethtroisi** [comment]
Visually there seems to be less error which matches @rgommers Oct 9 comment.

![Screenshot from 2020-05-13 14-12-56](https://user-images.githubusercontent.com/10172976/81866317-dea57200-9523-11ea-8574-7f3fd5ab1944.png)

I'm closing this as fixed given less visual error and @rgommers statement that `lsim` was improved (without searching for a PR).

**Comment by ilayn** [comment]
Not only the ode solver but LTI object needs scaling here. Easiest ist to write the dynamics in microseconds such that coefficients get back regular order of magnitude.
