### ISSUE TITLE
passing a function with keyword only arguments and no initial guess to curve_fit

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#5256]
```
from scipy.optimize import curve_fit

def func(x, a, *, b=1):
    return a * x + b

print(curve_fit(func, [0, 1, 2], [2, 3, 4]))
```

This fails because `curve_fit` tries to determine the number of arguments using `inspect.getargspec` (`ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them`).  I'd suggest either defaulting to optimizing over all non-keyword-only arguments (which keeps compatibility with the case of "standard" optional arguments, which are also optimized over), or throwing a more explicit error (because there isn't much to do anyways if the function has a keyword-only argument without a default value).

**Comment by ev-br** [comment]
With gh-5248, the error is more explicit (at least on python 3.3+).

`TypeError: f() missing 1 required keyword-only argument: 'b'`.

Note that keyword-only arguments do not work with default values either: 

```
>>> def f(x, a, *, b):
...    return a*x + b
>>> curve_fit(f, [0, 1, 2], [2, 3, 4], p0=[1, 2])
Traceback (most recent call last):
...
     return function(xdata, *params) - ydata
TypeError: f() takes 2 positional arguments but 3 were given
```

**Comment by anntzer** [comment]
It is reasonable that keyword-only arguments do not work, because they are technically unordered (e.g. `def f(*, a, b):` and `def f(*, b, a):` have the same signature).

**Comment by ev-br** [comment]
OK, let's consider this an enhancement request "teach curve_fit how to deal with keyword-only arguments". For this, we'll need to:
 - overload `p0` to accept either an array_like or a mapping of {var name: initial value}.
 - detect keyword-only args in the signature and generate initial values as a dict to be unpacked.
 - something is to be done with return values in presence of unordered keywords. popt  can be OK (return a dict or OrderedDict), pcov might be trickier.

An alternative is, of course, declare that we don't want to mess with any of that and document that keyword-only args are not supported.

**Comment by sethtroisi** [comment]
The original code snippet now runs; it doesn't fit `b` but that seems expected.

I believe this can be closed.
