### ISSUE TITLE
scipy.misc.resize doesnt work properly in linux, which works fine in windows

### ISSUE THREAD

**Issue by tyana6472** [scipy/scipy#5257]
This is the error I'm getitng..w is float 
 image = sp.misc.imresize(image,w)
  File "/usr/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 420, in imresize
    imnew = im.resize(size, resample=func[interp])
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1334, in resize
    im = self.im.resize(size, resample)
TypeError: must be 2-item sequence, not float

**Comment by tyana6472** [comment]
scipy version 0.13.3

**Comment by rgommers** [comment]
@tyana6472 could you provide an example that reproduces this issue? You can load ``scipy.misc.ascent`` as an image. Also, what PIL version do you have?

**Comment by anaviltripathi** [comment]
Same issue with me too. I am writing the following:
im = misc.imread(image, flatten=1)
im = misc.imresize(im, 50)

Below is the error trace:
  File "/usr/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 420, in imresize
    imnew = im.resize(size, resample=func[interp])
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1334, in resize
    im = self.im.resize(size, resample)
TypeError: must be 2-item sequence, not float

**Comment by anaviltripathi** [comment]
Works fine when using fractional values instead of int. For example this executes just fine:
im = misc.imread(image, flatten=1)
im = misc.imresize(im, 0.5)

So I believe percentage is not working although fraction works just fine.

**Comment by anaviltripathi** [comment]
I fixed this issue in my copy. I checked it in the master branch and found that it has already been fixed so this issue should be closed.

**Comment by ev-br** [comment]
closing then.
