### ISSUE TITLE
Typo causing an error in splrep

### ISSUE THREAD

**Issue by vanpact** [scipy/scipy#5260]
Hello everybody!
So, basically, [line 512 of the file fitpack.py in scipy.interpolate](https://github.com/scipy/scipy/blob/master/scipy/interpolate/fitpack.py#L512) is:
```python
warnings.warn(RuntimeWarning(+_iermess[ier][0]))
```

The '+' is causing a TypeError:
```
TypeError: bad operand type for unary +: 'str'
```

I think it is a typo and the '+' should be removed:
```python
warnings.warn(RuntimeWarning(_iermess[ier][0]))
```

**Comment by ev-br** [comment]
Indeed. Do you care to submit a fix?

**Comment by ev-br** [comment]
Fixed in gh-5261
