### ISSUE TITLE
Default epsilon in rbf.py fails for colinear points

### ISSUE THREAD

**Issue by njwilson23** [scipy/scipy#5263]
Commit ce66e32b3efb3fd4756700cce3db81c4d76bd605 changed the default epsilon used by the Rbf interpolator. Unfortunately, this choice raises a ValueError for colinear points lying along an axis, because the min and max "difference" is the same, causing a divide by zero.

For example, trying

```python
from scipy.interpolate import Rbf
Rbf([1,2,3], [4,4,4], [2,5,8])
```
will fail. This is because line 205-207 [1] has
```python
ximax = np.amax(self.xi, axis=1)
ximin = np.amin(self.xi, axis=1)
self.epsilon = np.power(np.prod(ximax - ximin)/self.N, 1.0/dim)
```
In the example above, `ximax=[3,4]` and `ximin=[1,4]`, so the product of their difference is zero.

I suspect that the default could be adjusted in a way that doesn't raise an exception. The current version uses the volume of a bounding (hyper)cube, but the example is a case where this cube is zero. What about just dropping zeros before `np.prod`?

[1] https://github.com/scipy/scipy/blob/adbf5a6b7f3f32b2fdfb456582b98d0af9a12838/scipy/interpolate/rbf.py#L207

**Comment by ev-br** [comment]
Fixed by gh-5264, closing.
