### ISSUE TITLE
Qhull object missing volume attribute.

### ISSUE THREAD

**Issue by hgzm** [scipy/scipy#5277]
Hi all,
When creating a ConvexHull object from a set of points I can get most of its attributes such as vertices, simplices, equations... but I cannot get neither the area nor the volume.  In fact, if I try to get their values using for instance, chull_test.volume (where chull_test is a ConvexHull object) what I get is:
AttributeError: 'ConvexHull' object has no attribute 'volume'

Thanks for your help,

Hector

**Comment by pv** [comment]
The documentation you are looking at probably does not correspond to the version of Scipy you have installed. The volume attribute is not present in released versions so far.
