### ISSUE TITLE
1d scipy.signal.convolve much slower than numpy.convolve

### ISSUE THREAD

**Issue by juliantaylor** [scipy/scipy#5280]
`scipy.signal.convolve` is freakishly slow for simple 1d cases, np.convolve outclasses it by huge factors and produces the same results:

```
d = np.random.normal(size=232523)
k = np.random.normal(size=5)

%timeit np.convolve(d, k)
%timeit scipy.signal.convolve(d, k)

print (np.convolve(d, k) == scipy.signal.convolve(d, k)).all()
print (np.convolve(d, k, mode="same") == scipy.signal.convolve(d, k, mode="same")).all()
print (np.convolve(d, k, mode="full") == scipy.signal.convolve(d, k, mode="full")).all()
```

```
1000 loops, best of 3: 519 µs per loop
10 loops, best of 3: 26.2 ms per loop
True
True
True
```

as numpy is generally likely to be more optimized than scipy, scipy should probably just dispatch the 1d convolve to numpy.
Also scipy does not seem to release the GIL for the convolution.

**Comment by WarrenWeckesser** [comment]
Don't forget about `scipy.ndimage.convolve` and `scipy.ndimage.convolve1d`.  In some cases, `convolve1d` is faster than numpy's `convolve`, and it has the added feature of providing an `axis` argument.

Several years ago I created a comparison of a few `convolve` methods on the scipy wiki:
    http://www.scipy.org/Cookbook/ApplyFIRFilter

(The wiki appears to be down at the moment.)

**Comment by juliantaylor** [comment]
hm I don't see how convolve1d can be faster than numpy, numpys implementation hasn't got much optimization room left, for large kernels it uses BLAS, for small kernels its heavily optimized to not waste any registers.

**Comment by juliantaylor** [comment]
though thats a bit off topic, fixing signal.convolve for 1d data is quite simple and it pretty much can't get any slower than it is now.

**Comment by WarrenWeckesser** [comment]
Agreed.  And it looks like the same is true for `numpy.correlate` and `scipy.signal.correlate`.
