### ISSUE TITLE
compiling scipy with sun CC compiler

### ISSUE THREAD

**Issue by camelccc** [scipy/scipy#5281]
ckdtree.pyx uses infinity as a name, which sems to cause multiple definitions due to a name clash when the c compiler is called on this platform
once the name of the infinity variable in ckdtree.pyx was changed, along with adjusting ckdtree_cpp_methods.h it compiles.
The use of the name infinity in this way seems rather silly

**Comment by charris** [comment]
Could you put together a pull request?

**Comment by larsmans** [comment]
#5293 should fix this, @camelccc can you verify?
