### ISSUE TITLE
Documentation missing links to stubs when built with Sphinx 1.3.1

### ISSUE THREAD

**Issue by jjhelmus** [scipy/scipy#5283]
Building the SciPy documentation using `make html` and Sphinx version 1.3.1 produces Reference pages which are missing links to function/class stubs which are imported from other modules into sub-packages.  The number of warnings indicating that a document isn't included in any toctree increases substantially as compared to Sphinx 1.2.3 (~300 to  ~1800). 

For example links to `scipy.stats.contingency.expected_freq` are created since these are not imported into scipy.stats but links to `scipy.stats.alpha`, `scipy.stats.anglit`, etc are not created.
The documentation builds as expected using Sphinx 1.2.3.

[Gist of stats.html](https://gist.github.com/jjhelmus/39550ba9cffdca8d6650) produced for SciPy 0.16.0 using Sphinx 1.3.1, [rendered](https://rawgit.com/jjhelmus/39550ba9cffdca8d6650/raw/afd85b6f06090e4e049e53684cd3d2a39c1b76eb/stats.html).

[Gist of stats.html](https://gist.github.com/85446a2ccaaadbc08472) produced for SciPy 0.16.0 using Sphinx 1.2.3, [rendered](https://rawgit.com/jjhelmus/85446a2ccaaadbc08472/raw/5821fe3b2128f145f08bd9c496a1771246b41e06/stats.html).

This may be in issue in numpydocs rather than scipy. I'd be happy to report this issue there if appropriate.

**Comment by jjhelmus** [comment]
This has been reported and addressed, see sphinx-doc/sphinx#1822.  Should be fixed when Sphinx 1.4 is released.

**Comment by rgommers** [comment]
thanks for digging up the real source of the problem @jjhelmus. Closing this issue then.
