### ISSUE TITLE
Documentation for scipy.signal.TransferFunction matches neither implementation, matlab, nor conventional definition of fractions

### ISSUE THREAD

**Issue by eric-wieser** [scipy/scipy#5287]
It says:

> Represents the system as the transfer function `H(s)=\sum_i b[i] s^i / \sum_j a[j] s^i`, where `a` are elements of the numerator num and `b` are the elements of the denominator den.

This seems contrary to the normal definition of `numerator / denominator`

**Comment by eric-wieser** [comment]
Additionally, this seems to suggest that this code:

```python
TransferFunction([1, 2], [3, 4, 5])
```

Represents the function

```
1 + 2s
------
3 + 4s + 5s^2
```

Yet appears to actually produce the function
```
s  + 2
------
3s^2 + 4s + 5
```

**Comment by rgommers** [comment]
@eric-wieser thanks for the report. Documentation is wrong, fix in gh-5418.
