### ISSUE TITLE
scipy.signal.cwt() doc typo

### ISSUE THREAD

**Issue by kousu** [scipy/scipy#5290]
cwt() contradicts itself, e.g. at http://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.cwt.html:
```
        The first argument is the number of points that the returned vector
        will have (len(wavelet(width,length)) == length).
```
Is it        `len(wavelet(length,width)) == length` or the other way around?

**Comment by rgommers** [comment]
Fixed in gh-5290. Thanks for the report @kousu
