### ISSUE TITLE
scipy 0.16.0 installation failed 

### ISSUE THREAD

**Issue by cosmos2006** [scipy/scipy#5300]
I got the following error while installing scipy from tar ball. I am using "3.6.1-1.fc17.x86_64" linux.

error: Command "/usr/bin/gfortran -Wall -g -L/usr/local/lib -L/sw/lib build/temp.linux-x86_64-2.7/scipy/cluster/_vq.o -L/usr/lib64/atlas -L/usr/lib64 -Lbuild/temp.linux-x86_64-2.7 -llapack -lptf77blas -lptcblas -latlas -lpython2.7 -lgfortran -o build/lib.linux-x86_64-2.7/scipy/cluster/_vq.so" failed with exit status 1

Please help

**Comment by pv** [comment]
Paste the whole build log to gist.github.com and link here.

**Comment by cosmos2006** [comment]
Please find the logfile of scipy installation failure
https://gist.github.com/cosmos2006/7637b3568973a0b2cc44

**Comment by pv** [comment]
Try unsetting environment variables controlling compiler options, such
as LDFLAGS etc.

**Comment by cosmos2006** [comment]
Following single command completed the installation.

> unset LDFLAGS

Thanks for the prompt response.

Regards
cosmos
