### ISSUE TITLE
scypi.io import issue 

### ISSUE THREAD

**Issue by WalterGoedecke** [scipy/scipy#5302]
I have an error with scipy.io within a django application. While I can import scipy, importing scipy.io gives the error: 
undefined symbol: _PyTraceback_Add

I'm using python 3.4 within a virtual environment. I've uninstalled and reinstalled scipy, but no difference. The error is computer specific; I can't determine if a dependency is missing. scipy.io does work within anaconda3, though.

**Comment by pv** [comment]
This does not appear to be a bug report.
You can ask e.g. on stackoverflow.com or superuser.com if you want help with installation issues etc.
