### ISSUE TITLE
Documentation of 'hybr' and 'lm' inconsistent in optimize.root

### ISSUE THREAD

**Issue by bjodah** [scipy/scipy#5309]
'lm':
http://docs.scipy.org/doc/scipy/reference/optimize.root-lm.html#optimize-root-lm

options contain `func` which I guess is redundant since `fun` is already in the signature of `root()`.
The user really should not be allowed to specify both `fun` and `func`

'hybr':
http://docs.scipy.org/doc/scipy/reference/optimize.root-hybr.html#optimize-root-hybr

same thing applies here, and here the documentation talks about a parameter `fprime`
https://github.com/scipy/scipy/blob/master/scipy/optimize/minpack.py#L176

which is not visible in the signature in the documentation (another name for the Jacobian callback `jac`).

EDIT: furthermore, `hybr` has an undocumented option `full_output`

**Comment by rgommers** [comment]
The ``full_output`` option for ``'hybr'`` was fixed in gh-5373. The other things look straightforward, adding easy-fix label.

**Comment by VinaySingh035** [comment]
do we only need to edit the "func" to "fun" at all the places it is used in the optimize.root.py file.

Being a newbie would be good to start to contribute  to this project.

**Comment by goelakash** [comment]
So which files are to be changed here?

**Comment by rgommers** [comment]
If you see the text in the html docs, you can search for that:

    $ grin "Solve for least squares with Levenberg-Marquardt"
    ./scipy/optimize/_root.py:
      216 :     Solve for least squares with Levenberg-Marquardt

**Comment by goelakash** [comment]
I got the same page, but I couldn't find how the documentation is generating this function definition:

`scipy.optimize.root(fun, x0, args=(), method='lm', jac=None, tol=None, callback=None, options={'col_deriv': 0, 'diag': None, 'factor': 100, 'gtol': 0.0, 'eps': 0.0, 'func': None, 'maxiter': 0, 'xtol': 1.49012e-08, 'ftol': 1.49012e-08})`

**Comment by pv** [comment]
cf https://github.com/scipy/scipy/blob/master/doc/source/scipyoptdoc.py

Internal solver parameters (such as func probably) should be changed to add a prefix `_`  in the `_minimize_*` functions so that they don't appear in the documentation.

**Comment by pv** [comment]
Or more precisely, it should be fixed just by renaming `func` -> `fun` in the `_root_lm` function.
