### ISSUE TITLE
broyden1 fails with scalar valued function

### ISSUE THREAD

**Issue by venuur** [scipy/scipy#5310]
The following use of scipy.optimize.broyden1 fails with an error on vector lengths:
    
    >>> def f(x):                                                                                                                                        
    ...        return [max(-1 + x[0] + x[1], 0)**2 + x[0] - x[1]]                                                                  
    >>> x = scipy.optimize.broyden1(f,[1,1])
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "<string>", line 8, in broyden1
      File "/usr/lib64/python2.7/site-packages/scipy/optimize/nonlin.py", line 330, in nonlin_solve
        jacobian.update(x.copy(), Fx)
      File "/usr/lib64/python2.7/site-packages/scipy/optimize/nonlin.py", line 685, in update
        self._update(x, f, dx, df, norm(dx), norm(df))
      File "/usr/lib64/python2.7/site-packages/scipy/optimize/nonlin.py", line 997, in _update    
        d = v / vdot(df, v)
    ValueError: vectors have different lengths 

Changing the definition of f leads to scipy.optimize.broyden1 executing correctly:

    >>> def f(x):                                                                                                                                        
    ...        return [max(-1 + x[0] + x[1], 0)**2 + x[0] - x[1], 0]                                                                  
    >>> x = scipy.optimize.broyden1(f,[1,1])
    >>> x                                                                                                                                                
    array([ 0.61803401,  1.        ])

**Comment by dlax** [comment]
Yes `broyden1` (as other multidimensional root solving methods) solves a system of `n` nonlinear equations against a vector of `n` elements.
