### ISSUE TITLE
spdiags has non-intuitive behavior for non-square matrices

### ISSUE THREAD

**Issue by kbrose** [scipy/scipy#5312]
scipy.sparse.spdiags behaves in a way that I find unintuitive for non-square matrices.

Consider the following:
```python
>>> import numpy as np
>>> from scipy import sparse
>>> scipy.sparse.spdiags(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), [0, 1, 2], 3, 5).A
array([[1, 5, 9, 0, 0],
       [0, 2, 6, 0, 0],
       [0, 0, 3, 0, 0]])
```

I understand that this is more of a conventional decision than a true right vs. wrong decision, but I think the proper sequence should be

```python
>>> import numpy as np
>>> from scipy import sparse
>>> scipy.sparse.spdiags(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), [0, 1, 2], 3, 5).A
array([[1, 4, 7, 0, 0],
       [0, 2, 5, 8, 0],
       [0, 0, 3, 6, 9]])
```

**Comment by pv** [comment]
I do not think the behavior can be changed any more. `scipy.sparse.diags` should be more intuitive.
