### ISSUE TITLE
Implementation error in scipy.interpolate.PchipInterpolator

### ISSUE THREAD

**Issue by zuoliang** [scipy/scipy#5326]
I compared the *PCHIP 1-d monotonic cubic interpolation* as implemented by **scipy.interpolate.PchipInterpolator** with the [NAG C implementation] (http://nag.com/numeric/cl/nagdoc_cl25/html/e01/e01bec.html), as well as the R package [pracma](https://cran.r-project.org/web/packages/pracma/index.html).  The output from the scipy.interpolate.PchipInterpolator do not match with those from NAG implementation and pracma implementation.

Following is the test code

```python
import numpy as np
from scipy import interpolate
from StringIO import StringIO

dataStr = '''
  7.99   0.00000E+0
  8.09   0.27643E-4
  8.19   0.43750E-1
  8.70   0.16918E+0
  9.20   0.46943E+0
 10.00   0.94374E+0
 12.00   0.99864E+0
 15.00   0.99992E+0
 20.00   0.99999E+0
'''
data = np.loadtxt(StringIO(dataStr))
pchip = interpolate.PchipInterpolator(data[:,0], data[:,1])

resultStr = '''
   7.9900       0.0000
   9.1910       0.4640
  10.3920       0.9645
  11.5930       0.9965
  12.7940       0.9992
  13.9950       0.9998
  15.1960       0.9999
  16.3970       1.0000
  17.5980       1.0000
  18.7990       1.0000
  20.0000       1.0000
'''
result = np.loadtxt(StringIO(resultStr))
np.allclose(result[:,1], pchip(result[:,0]), atol=5E-5)
```
Both [`dataStr`](http://nag.com/numeric/cl/nagdoc_cl25/examples/data/e01bece.d.html) and [`resultStr`](http://nag.com/numeric/cl/nagdoc_cl25/examples/baseresults/e01bece.r.html) are based on documentation from NAG.

The error is due to the wrong expression of `w1` and `w2` in **scipy\interpolate\_monotone.py** on line 120 and 121, respectively.  They should be swaped, i.e.,

```python
w2 = 2*hk[1:] + hk[:-1]
w1 = hk[1:] + 2*hk[:-1]
```
Once this correction is made, the test script can pass.

**Comment by ev-br** [comment]
Thanks for the report.
This seems to have been noticed before https://github.com/scipy/scipy/issues/3453#issuecomment-37851669
