### ISSUE TITLE
ENH: full_output option not available in scipy.integrate.nquad

### ISSUE THREAD

**Issue by woodscn** [scipy/scipy#5330]
Hey everyone,

I need a design consult. I'm trying to enable the use of the quad full_output option when using nquad, and I'm trying to come up with a good way to manage all of the data that comes back from using something like that. Any suggestions are welcome.

scipy.integrate.quad provides the keyword argument full_output. When set to True, this returns an additional dict full of useful information about the internal state of the integrator, which can be used to get a better picture of exactly what the adaptive integration did. The source for quad explains this in detail.

scipy.integrate.nquad is a recursive call to quad, which allows you to evaluate multidimensional integrals. It's a bit of a low-level interface, but it scales pretty well. The full_output option was never implemented in nquad, because it's not obvious what the behavior or the output should be; even on a 2-dimensional integral, the amount of data is at least 21 times the 1-dimensional case, and usually more.

The problem seems to lie in how to reduce the data, and what use-cases to design for. Some parts of the return data are simple to reduce, such as 'neval', which can give the total number of function evaluations required by the integrator. For others, such as the detailed information on adaptive subdivisions, it's less obvious how to reduce and consolidate the information in a way that is generally useful.

Unfortunately, just saving everything seems problematic. I tried just making a list of all of the infodict objects from the various invocations of quad, and ended up with 1.3MB (pickled) for a 2-D problem. To me, that seems too high, for something that has to be maintained in memory until the end.

So, to my mind, I need to either pick a specific way to reduce the data down to something manageable, knowing that might not be appropriate for everyone's use cases, or I need to find a better way to simply save everything. So, any ideas?

N

**Comment by woodscn** [comment]
I was able to get some more data on this. Using the simple method, I end up with 
dimensions     size (MB)
---------------     -----
2                     1.3
3                     15.3
4                     3300    (Couldn't actually pickle to a file; had to pickle to a bytes object and use len())

Since nquad is usable up to about 5, maybe 6 dimensions, this is a problem.

**Comment by woodscn** [comment]
I was able to get some more data on this. Using the simple method, I end up with 

dimensions | size (MB)
--------------- | -----
2                 | 1.3
3                 | 15.3
4                 | 3300    

(Couldn't actually pickle 4-D to a file; had to pickle to a bytes object and use len())

Since nquad is usable up to about 5, maybe 6 dimensions, this is a problem.

**Comment by woodscn** [comment]
This is essentially a problem of large quantities of data. What is the feeling about using h5py as an optional dependency, and raising an error if someone tries to use full_output=True without having it installed?

**Comment by ev-br** [comment]
FWIW as long as h5py imports are conditional only, I don't see a problem. (And I'm back to the peanut gallery)

**Comment by rgommers** [comment]
Note that also in ``dblquad`` and ``tplquad`` the ``full_output`` argument isn't implemented, for the same reason I assume. I can see how the full output may be useful, so seems OK to add but I think must be added to all 3 functions at the same time imho.

Some other questions/thoughts:
- Even with ``h5py`` you will still get huge files for a 4-D integral right?
- How easy will it be to interpret the output for an average user? If it's too complex to visualize then the feature may not see much use.
- Would you always need the full output of integration in all dimensions? Maybe it makes sense to have an interface that says "give me the full output of integration over dimension 2 only" or "give me all the warning messages only". This would allow basically data pruning on the fly.
- A conditional dependency would be ok if really needed.

**Comment by woodscn** [comment]
> On Oct 10, 2015, at 4:26 PM, Ralf Gommers <notifications@github.com> wrote:
> 
> Note that also in dblquad and tplquad the full_output argument isn't implemented, for the same reason I assume. I can see how the full output may be useful, so seems OK to add but I think must be added to all 3 functions at the same time imho.
> 
My thought was always to make dblquad and tplquad just thin wrappers around nquad, anyway, so it shouldn't be too difficult to make the option available. 

> Some other questions/thoughts:
> 
> Even with h5py you will still get huge files for a 4-D integral right?
Yes. Maybe even bigger, now that I'm further along in testing. Obviously, that's problematic. Any eventual PR would need some kind of performance analysis, I think. At least the h5py stuff is a big file on disk, rather than a big file in RAM. 
> How easy will it be to interpret the output for an average user? If it's too complex to visualize then the feature may not see much use.
It depends what you want to visualize. For instance, I want to know all of the points where the function was evaluated, but someone else might be interested in the localized error for all of the adaptive bisections. The way it's written right now, it's basically a memory dump of everything, more or less as received. Not really user-friendly, but a good foundation to build on. 
> Would you always need the full output of integration in all dimensions? Maybe it makes sense to have an interface that says "give me the full output of integration over dimension 2 only" or "give me all the warning messages only". This would allow basically data pruning on the fly.
Probably you would usually want a limited subset of the data, honestly. It seems that designing an interface like that would be a challenge, though.

**Comment by woodscn** [comment]
Yuck. A 4-D HDF5 file is almost 6GB, and it takes a LONG time to run the integration while writing that data. As mentioned, the RAM usage is reduced, but I'm starting to wonder if my "Save everything and let the user figure out what to do with it" approach might just be untenable for this problem, at least for > 3-D. 

An alternative is to come up with a selection of options that reduce the data in place, and can be used independently. 'neval' is an obvious one, but you could also have an 'integration_points' option that returns a numpy array of the points where the function was sampled, an 'intervals' option that gets you the integration subdivisions for a given level, and so on. The downside of this approach is that anyone who wants to get a different data output ends up having to hack the scipy code, rather than analyzing output.

@rgommers idea is interesting, since it seems it would provide some kind of middle ground, letting people pick and choose the data they want. Not sure how to handle the interface or output, though.

**Comment by woodscn** [comment]
PR #5906 takes care of the simple parts of this issue. The more complex bits are probably out of scope for SciPy at present.
