### ISSUE TITLE
sqrtm on a diagonal matrix can warn "Matrix is singular and may not have a square root."

### ISSUE THREAD

**Issue by bubaflub** [scipy/scipy#5336]
Hello,

Not sure if this is a real bug, a clarification for the documentation, or simply expected behavior.  This may be related to issue #4866.

I was using the sqrtm function on a diagonal matrix and I got the warning

```
Matrix is singular and may not have a square root.
```

While the resulting output is correct, it was a bit surprising to see that warning message.  Calculating the square root of a diagonal matrix is just the square root of every item on the diagonal, right?

Example:

```
>>> a = scipy.diag([2, 1, 0])
>>> scipy.linalg.sqrtm(a)
Matrix is singular and may not have a square root.
array([[ 1.41421356,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])
```

**Comment by argriffing** [comment]
> Calculating the square root of a diagonal matrix is just the square root of every item on the diagonal, right?

Yes this is correct.

If I recall correctly the scipy sqrtm function gives bad output for some matrices that technically have a square root, but these incorrectly handled matrices are all singular. So if it sees any singular matrix it spams this warning. Unlike Matlab, in general scipy isn't clever about autodetecting the structure of matrices and dispatching to custom implementations for matrices with that structure.  And unlike in Julia, numpy matrices do not carry around type info about their structure but only about their element type.

**Comment by bubaflub** [comment]
> So if it sees any singular matrix it spams this warning.

Ok, so this is known behavior.

How shall we proceed?  We could:

  1. Close the issue.
  1. Update [the docs](http://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.linalg.sqrtm.html) noting the issue.
  1. Change sqrtm to check for diagonal matrices

I'm fine with dropping the issue entirely.  Adding some checks to sqrtm doesn't seem right to me - anyone who uses that function would pay the overhead of that check and it seems inconsistent with the way scipy currently works.  I could open a pull request that adds some information to the generated docs about this warning and put in a few examples.  Does that sound good?

**Comment by argriffing** [comment]
I see the matrix is also positive semidefinite so I'll just link this here https://github.com/scipy/scipy/pull/3556, but this doesn't answer the question of how to proceed.

**Comment by SoumitraAgarwal** [comment]
Adding to what @bubaflub said, I believe that this issue has been raised 2-3 times and thus deserves a sentence in the documentation. Other than that, changing the sqrtm function shouldnt be nessc. as it gives the required output and the warning is only suggestive.
