### ISSUE TITLE
Formula in documentation for correlate is wrong

### ISSUE THREAD

**Issue by gauss256** [scipy/scipy#5337]
The documentation for signal.correlate says that is based on the formula (just showing 1d version here for simplicity)

![SciPy correlate formula](http://i.imgur.com/vW39Jt0.jpg)

The correct formula is more like what is in the MATLAB:

![MATLAB correlate formula](http://i.imgur.com/g8WA5Pv.jpg)

But what you really want to know is what the indices actually mean in the function result. This is more complicated, and probably there is a more elegant way to say this, but here goes:

![Full correlation formula](http://i.imgur.com/5aQovIm.jpg)

**Comment by rgommers** [comment]
@gauss256 thanks, documentation clarifications are very welcome. Could I interest you in submitting your proposed improvements to the ``correlate`` docstring as a pull request?

**Comment by gauss256** [comment]
Hi Ralf,

Never done anything like that, but I'll give it a shot. I'm kind of deep
into getting the details of this particular function right, so it would be
good for me to capture what I've figured out before I forget it!

If you happen to know the exact file I should be looking at, it would help
get me started if you could point me to it. If not, I'm sure I can figure
it out.

Thanks,
Bruce

**Comment by ev-br** [comment]
Starting from the dev docs (it's often easiest to just search for "scipy <function name>" ) http://docs.scipy.org/doc/scipy-dev/reference/generated/scipy.signal.correlate.html#scipy.signal.correlate, you can click on the [source] link next to the function signature, which gives the source code of the function:
https://github.com/scipy/scipy/blob/master/scipy/signal/signaltools.py#L79-L193

The docstrings gets converted into an HTML docs entry verbatim.

**Comment by gauss256** [comment]
Thanks!

**Comment by rgommers** [comment]
@gauss256 note that there are 2 ways to submit pull requests:
- what @ev-br just told you (the easiest for simple changes like editing one docstring)
- to work with Git and your own fork of Scipy (more flexible, see http://docs.scipy.org/doc/numpy-dev/dev/)

So while I second @ev-br's suggestion, it's good that you know there's a more powerful/flexible way just in case your first contribution gets you interested in digging deeper:)

Let us know if you need any help.

**Comment by ev-br** [comment]
Fixed in https://github.com/scipy/scipy/pull/6971, closing.
