### ISSUE TITLE
wilcoxon crash when given 0?

### ISSUE THREAD

**Issue by kingjr** [scipy/scipy#5339]
The wilcoxon function crashes in v 0.16.0 if it's given an zero array:

```
from scipy.stats import wilcoxon
wilcoxon([0.] * 30)
```

returns

```
ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (0,)
```

Perhaps a specific error message should be added for such cases? Or just return `WilcoxonResult(stats=0., p=1.)`?

**Comment by rgommers** [comment]
With Scipy master I get:

    In [1]: from scipy.stats import wilcoxon

    In [2]: wilcoxon([0.] * 30)
    /home/rgommers/Code/scipy/scipy/stats/morestats.py:2321: UserWarning: Warning: sample size too small for normal approximation.
      warnings.warn("Warning: sample size too small for normal approximation.")
    /home/rgommers/Code/scipy/scipy/stats/morestats.py:2345: RuntimeWarning: invalid value encountered in double_scalars
      z = (T - mn - correction) / se
    Out[2]: WilcoxonResult(statistic=0.0, pvalue=nan)

So it's already fixed.
