### ISSUE TITLE
Update dev version docs continuously

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#5343]
It shouldn't be difficult to do the following:
- build html and pdf docs each time we merge a PR on TravisCI
    - we now don't build merge commits, which is fine, so these new builds would be only for the docs
- upload those docs to the doc server
    - alternatively, upload to Github pages and change the links to point to Github only for the development version docs

Here are some scripts to steal: https://groups.google.com/forum/#!topic/scikit-image/VGhf4dNmE2o

**Comment by ev-br** [comment]
cross-ref: https://github.com/scipy/scipy/issues/4214

**Comment by rgommers** [comment]
Oops. I searched, but not hard enough. Closing this as duplicate.
