### ISSUE TITLE
ndimage.interpolation.rotate unusable

### ISSUE THREAD

**Issue by maxmunzel** [scipy/scipy#5357]
ndimage.interpolation.rotate 's  first argument is called 'input'. Thats why the python interpreter tries to call .shape[axes[1]] on the --build in type-- input (checked that using pdb). simply renameing the argument would probably fix the issue.

 >>> import scipy.ndimage.interpolation as ndi
>>> import numpy as np
>>> a = np.array((1,2))
>>> angle = 1
>>> rotate(a, angle)
>>> ndi.rotate(a, angle)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/littlebird/anaconda3/lib/python3.4/site-packages/scipy/ndimage/interpolation.py", line 644, in rotate
    ix = input.shape[axes[1]]
IndexError: tuple index out of range
>>> 

Just to be clear, what I'm talking about:
https://github.com/scipy/scipy/blob/adbf5a6b7f3f32b2fdfb456582b98d0af9a12838/scipy/ndimage/interpolation.py

**Comment by tacaswell** [comment]
That does not seem right.  In python you are allowed to shadow built-in types in the local namespace.

If this _was_ due to trying to use the builtin, you would get this exception:

```python
In [57]: input
Out[57]: <function input>

In [58]: input.shape
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-58-06f610d79197> in <module>()
----> 1 input.shape

AttributeError: 'builtin_function_or_method' object has no attribute 'shape'


```

Can you provide a minimal working example that demonstrates the bug?  

The `rotate` method is tested [here](https://github.com/scipy/scipy/blob/adbf5a6b7f3f32b2fdfb456582b98d0af9a12838/scipy/ndimage/tests/test_ndimage.py#L2132)

**Comment by maxmunzel** [comment]
Hi,
i did further testing and have to agrre with you. (in the middle of .rotate()'s routines, input refers to the build-in, rather than to the argument once or twice and I didn't continue to trace it to the crash at that point *slaps face*) The problem was the fact that I was using 2-D Arrays with shape(1,2), that caused rotate to crash. But even with shape(2,1) they behave... ...interesting. 

This may be just me misusing the class, but I attached my test script. 

```python
import numpy as np
import scipy.ndimage.interpolation as sni
import pdb
a = np.array((1.5, 3.4))
b = a.reshape(2, 1)
print("a:")
print(a)
print("")
print("b:")
print(b)
print("")

print(sni.rotate(b, 0.5))
print(sni.rotate(a, 0.5))
```
```
$ python3 test.py
a:
[ 1.5  3.4]

b:
[[ 1.5]
 [ 3.4]]

[[ 0.]
 [ 0.]]
Traceback (most recent call last):
  File "<stdin>", line 15, in <module>
  File "/Users/littlebird/anaconda3/lib/python3.4/site-packages/scipy/ndimage/interpolation.py", line 644, in rotate
    ix = input.shape[axes[1]]
IndexError: tuple index out of range

```

**Comment by tacaswell** [comment]
The problem is that `a` is not a `(1, 2)` shaped array, it is a `(2, )` shaped array.

```python
>> a = np.array((1.5, 3.4))
>> a.shape
(2, )
```

There are a bunch of way to add extra axis to arrays (`reshape`, `atleast_2d`, fancy slicing), which one is correct for you is going to depend on your application.

**Comment by pv** [comment]
This seems not a bug then.
