### ISSUE TITLE
Empty slicing of a sparse matrix should raise better error

### ISSUE THREAD

**Issue by MechCoder** [scipy/scipy#5361]
Would it be better to have a more friendly error when a sparse matrix is sliced with an empty mask.

    import numpy as np
    from scipy import sparse
    X_csr = sparse.csr_matrix(np.random.rand(10, 10))
    mask = np.zeros(10, dtype=bool)
    X_csr[mask, :]
    ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by argriffing** [comment]
I don't see this error with newish numpy and scipy.
```python
>>> import numpy as np
>>> from scipy import sparse
>>> np.__version__
'1.11.0.dev0+972dbd0'
>>> import scipy
>>> scipy.__version__
'0.17.0.dev0+8d7e701'
>>> X_csr = sparse.csr_matrix(np.random.rand(10, 10))
>>> mask = np.zeros(10, dtype=bool)
>>> X_csr[mask, :]
<0x10 sparse matrix of type '<type 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>
```

**Comment by WarrenWeckesser** [comment]
It works for me, too, using scipy `'0.17.0.dev0+619d5b7'` and numpy 1.10.1.  @MechCoder, which versions of scipy and numpy are you using?

**Comment by MechCoder** [comment]
I updated `scipy` and it works. Can you let me know where in the codebase you have handled this, so that I can patch up `safe_mask` in sklearn the same way?

Thanks.
