### ISSUE TITLE
FAIL: test_orthogonal.test_j_roots, test_orthogonal.test_js_roots

### ISSUE THREAD

**Issue by rohitjamuar** [scipy/scipy#5363]
I see these failures on Ubuntu 14.04.2 LTS (x86_64) with Numpy-1.9.2 and Scipy-0.16.0, compiled with icc-15.0.3:
```
======================================================================
FAIL: test_orthogonal.test_j_roots 
vgq(rf(0.5, -0.5), ef(0.5, -0.5), wf(0.5, -0.5), -1., 1., 25, atol=1e-13)
----------------------------------------------------------------------
AssertionError:
Not equal to tolerance rtol=1e-15, atol=1e-13

(mismatch 100.0%)
 x: array([[  1.000000e+00,   1.071811e-13,  -1.051287e-13,   1.027752e-13,
         -9.987623e-14,   9.682406e-14,  -9.338675e-14,   9.002237e-14,
         -8.710329e-14,   8.338669e-14,  -7.911253e-14,   7.485234e-14,...
 y: array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,...

======================================================================
FAIL: test_orthogonal.test_js_roots 
vgq(rf(1, 0.5), ef(1, 0.5), wf(1, 0.5), 0., 1., 25, atol=1e-13)
----------------------------------------------------------------------

AssertionError:
Not equal to tolerance rtol=1e-15, atol=1e-13

(mismatch 100.0%)
 x: array([[  1.000000e+00,   1.071811e-13,  -1.050949e-13,   1.027831e-13,
         -9.989439e-14,   9.682856e-14,  -9.331403e-14,   9.018995e-14,
         -8.707046e-14,   8.322614e-14,  -7.916400e-14,   7.499160e-14,...
 y: array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,...

======================================================================
FAIL: test_orthogonal.test_js_roots 
vgq(rf(68.9, 2.25), ef(68.9, 2.25), wf(68.9, 2.25), 0., 1., 5, atol=2e-14)
----------------------------------------------------------------------
AssertionError:
Not equal to tolerance rtol=1e-15, atol=2e-14

(mismatch 100.0%)
 x: array([[  1.000000e+00,  -3.070229e-14,   1.971582e-14,  -8.322740e-15,
         -1.146759e-15],
       [ -3.070229e-14,   1.000000e+00,  -2.023995e-14,   1.201997e-14,...
 y: array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],...
```

When the compilation is done by icc with `-O3` and `-fp-model strict` compiler flags, the tests pass.
But when the compilation is done without `-fp-model strict` flag - which means fast math optimizations, tests fail.  For tests with `atol=1e-13`, increasing it to `1.5e-13` makes the tests pass. For the test with `atol=2e-14`, increasing it to `3.5e-14`, fixes the test. Should the tolerance-level be reconsidered for these cases?

**Comment by argriffing** [comment]
Just linking the corresponding mailing list [message](https://mail.scipy.org/pipermail/scipy-dev/2015-October/020966.html) and the earlier PR that relaxed tolerances https://github.com/scipy/scipy/pull/4243.

**Comment by rgommers** [comment]
Normally if we find a platform or compiler for which the tests fail it's OK to bump the tolerances. I'm not sure in this case though how far @pv wants to bump these ones, or about the compiler flag (no ``-fp-model strict`` is like the user saying that reduced floating point accuracy is ok right?).

**Comment by rohitjamuar** [comment]
@rgommers Disabling `-fp-model strict` does not necessarily imply reduced accuracy. It enables value unsafe optimizations and does not guarantee correct handling of FP environment - more details [here](https://software.intel.com/sites/default/files/article/164389/fp-consistency-102511.pdf).

**Comment by pv** [comment]
Much of scipy.special regards 1e-12 relative accuracy to be sufficient, so I don't see particular problems in bumping the tolerances here.

**Comment by rgommers** [comment]
Will close this when it has landed in 0.16.x as well.

**Comment by rgommers** [comment]
backported in 9605c94

**Comment by VictorRodriguez** [comment]
Hi, question , was it fixed ? 

I still can see the error : 

tmp$ python test_orthogonal.py
.......................F.
======================================================================
FAIL: test_orthogonal.test_roots_genlaguerre
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/test_orthogonal.py", line 711, in test_roots_genlaguerre
    vgq(rootf(0.1), evalf(0.1), weightf(0.1), 0., np.inf, 100, atol=1e-13)
  File "/tmp/test_orthogonal.py", line 287, in verify_gauss_quad
    assert_allclose(vv, np.eye(N), rtol, atol)
  File "/usr/lib/python2.7/site-packages/numpy/testing/utils.py", line 1411, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/lib/python2.7/site-packages/numpy/testing/utils.py", line 796, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-15, atol=1e-13

(mismatch 0.3%)
 x: array([[  1.000000e+00,  -7.418044e-15,  -5.787505e-15, ...,
         -1.476561e-16,  -8.163852e-17,  -1.531694e-17],
       [ -7.418044e-15,   1.000000e+00,  -4.461875e-15, ...,...
 y: array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],...

----------------------------------------------------------------------
Ran 25 tests in 0.552s

FAILED (failures=1)
