### ISSUE TITLE
fsolve & root incorrect function-call count

### ISSUE THREAD

**Issue by mcr222** [scipy/scipy#5369]
The functions in scipy.optimize fsolve and root both return a wrong number function evaluations in the information they return.

Concretely, they fail to count 2 function evaluations they do for checking purposes:
from the minpack code -> es = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
and another that I didn't find (probably in compiled code).

Someone already noticed a few years ago:
https://mail.scipy.org/pipermail/scipy-dev/2010-November/015765.html

So this two extra function evaluations should be counted (or at least added to the documentation as two extra function evaluations for checking purposes).

And related to this: For applications where the cost of the function evaluations is high these function evaluations should be avoided (or optional).

The code that uncovers the bug:

```
from scipy import optimize

counter=0

def zero_f(y):
    global counter
    counter += 1
    return y**2-3

counter=0
x, infodict, ier, mesg = optimize.fsolve(zero_f,100, full_output = True)
print(counter)
print ("func ev: " + str(infodict["nfev"]))

counter=0
optObject = optimize.root(zero_f,100)
print(counter)
print("func ev: " + str(optObject.nfev))
```

**Comment by mdhaber** [comment]
This is pretty low-hanging fruit. Here are some notes to make it easier.

This code makes it easy to see where each function call is made from.

<details>

```python3
from scipy import optimize

def zero_f(y):
    zero_f.counter += 1
    if zero_f.counter == 1:  # see stack trace after first evaluation
        raise Exception()
    return y**2-3

# zero_f.counter = 0
# x, infodict, ier, mesg = optimize.fsolve(zero_f, 100, full_output = True)
# print(zero_f.counter)
# print ("func ev: " + str(infodict["nfev"]))

zero_f.counter = 0
res = optimize.root(zero_f, 100, method='lm', options={'maxfev': 3})
print(zero_f.counter)
print("func ev: " + str(res.nfev))
```

</details>

For `root`, methods `hybr` and `lm` have the problem. (`df-sane` seems to return the correct count, and the rest don't seem to return `fev`.)

One of the calls that isn't counted is:
https://github.com/scipy/scipy/blob/656076ca6b490f587e9bd9c4cd10cb259a687c5b/scipy/optimize/_minpack_py.py#L24

The other seems to be in ` _minpack._hybrd` or `_minpack._lmdif` itself.

Option 1: Just update the number of function evaluations. 

https://github.com/scipy/scipy/blob/656076ca6b490f587e9bd9c4cd10cb259a687c5b/scipy/optimize/_minpack_py.py#L265-L274 would be a reasonable place for `hybr`, and there is a similar place in . It would fix both `fsolve` and `root` `method='hybr'` if the `OptimizeResult` were corrected before being returned. There would need to be a similar change in `leastsq` to correct `root` for `method='lm'`.

Option 2: In `root` and `fsolve`, wrap the function to count the number of evaluations. Ignore the count provided by the solvers; just populate the OptimizeResult with `nfev` as counted by the wrapper.

I'd be happy to review a PR. I'd also be happy to submit a PR if someone else is willing to review.

**Comment by TimButters** [comment]
I've raised a PR to address this ([#20281](https://github.com/scipy/scipy/pull/20281)). @mdhaber, if you're still happy to review, it would be good to get your feedback.
