### ISSUE TITLE
sph_harm issues

### ISSUE THREAD

**Issue by Eric89GXL** [scipy/scipy#5376]
Kind of similar to #4887, I found an inconsistency in `sph_harm`, but it appears on Python 3.4 (e.g., on Anaconda scipy=0.16 or scipy=0.15) but not on Python 2.7 with equivalent `numpy`/`scipy` versions. Running this command in a Python 3.4 Anaconda virtual environment I get:
```
$ python -c "from scipy.special import sph_harm; print(sph_harm(1, 1, 1., 1.))"
(-0.290723302201-2.02129965364e-310j)
```
But the correct result is what I get on Python 2.7 (verified using calculations from [here] (https://github.com/mne-tools/mne-python/blob/master/mne/preprocessing/maxwell.py#L251):
```
(-0.157078470549-0.24463522341j)
```
It does work on my system Python3 when using the Ubuntu-packaged scipy 0.14.1:
```
(-0.15707847054880641-0.24463522340968866j)
```
And when I build `scipy` myself, latest `master` with MKL or `maintenance/0.16.x` using system BLAS, they both give the same correct result:
```
(-0.157078470549-0.24463522341j)
```
Any idea why it could break for 3.4 and not 2.7? And only some builds (apparently Anaconda)? This is a weird one.

cc @jennystone @argriffing since you were on the last PR merge related to this
cc @wronk

**Comment by pv** [comment]
Whatever compiler they are using has miscompiled the Cython-generated routine
`__pyx_f_5scipy_7special_8sph_harm_sph_harmonic`
so that it returns the wrong value.
Probably only the anaconda guys can help you out with this.

**Comment by Eric89GXL** [comment]
Cool, I'll bother them instead. Is it easy to describe how did you isolated the problem to that function?

**Comment by pv** [comment]
That's the innermost function that actually does the calculation.
Although the debug symbols are missing, you can see on `fin` from that function that the returned value has the incorrect imaginary part.

**Comment by Eric89GXL** [comment]
Thanks!

**Comment by WarrenWeckesser** [comment]
This was also noted on stackoverflow: http://stackoverflow.com/questions/33149777/scipy-spherical-harmonics-imaginary-part
