### ISSUE TITLE
gfortran: error: unrecognized command line option ‘-ffpe-summary=invalid,zero’

### ISSUE THREAD

**Issue by nilswagner** [scipy/scipy#5380]
I cannot build scipy from trunk...

creating build/lib.linux-x86_64-2.7/scipy/_lib
copying scipy/_lib/decorator.py -> build/lib.linux-x86_64-2.7/scipy/_lib
copying scipy/_lib/_tmpdirs.py -> build/lib.linux-x86_64-2.7/scipy/_lib
copying scipy/_lib/_numpy_compat.py -> build/lib.linux-x86_64-2.7/scipy/_lib
copying scipy/_lib/_testutils.py -> build/lib.linux-x86_64-2.7/scipy/_lib
copying scipy/_lib/_gcutils.py -> build/lib.linux-x86_64-2.7/scipy/_lib
copying scipy/_lib/_version.py -> build/lib.linux-x86_64-2.7/scipy/_lib
copying scipy/_lib/_util.py -> build/lib.linux-x86_64-2.7/scipy/_lib
copying scipy/_lib/__init__.py -> build/lib.linux-x86_64-2.7/scipy/_lib
copying scipy/_lib/setup.py -> build/lib.linux-x86_64-2.7/scipy/_lib
copying scipy/_lib/six.py -> build/lib.linux-x86_64-2.7/scipy/_lib
running build_clib
customize UnixCCompiler
customize UnixCCompiler using build_clib
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
customize Gnu95FCompiler
customize Gnu95FCompiler using build_clib
building 'dfftpack' library
compiling Fortran sources
Fortran f77 compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O2 -march=x86-64 -DMS_WIN64 -mtune=generic -msse2 -mlong-double-64 -ffpe-summary=invalid,zero
Fortran f90 compiler: /usr/bin/gfortran -Wall -fno-second-underscore -fPIC -O2 -march=x86-64 -DMS_WIN64 -mtune=generic -msse2 -mlong-double-64 -ffpe-summary=invalid,zero
Fortran fix compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -fno-second-underscore -fPIC -O2 -march=x86-64 -DMS_WIN64 -mtune=generic -msse2 -mlong-double-64 -ffpe-summary=invalid,zero
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/scipy
creating build/temp.linux-x86_64-2.7/scipy/fftpack
creating build/temp.linux-x86_64-2.7/scipy/fftpack/src
creating build/temp.linux-x86_64-2.7/scipy/fftpack/src/dfftpack
compile options: '-I/home/nils/local/lib64/python2.7/site-packages/numpy/core/include -c'
gfortran:f77: scipy/fftpack/src/dfftpack/dsinti.f
gfortran: error: unrecognized command line option ‘-ffpe-summary=invalid,zero’
gfortran: error: unrecognized command line option ‘-ffpe-summary=invalid,zero’
error: Command "/usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O2 -march=x86-64 -DMS_WIN64 -mtune=generic -msse2 -mlong-double-64 -ffpe-summary=invalid,zero -I/home/nils/local/lib64/python2.7/site-packages/numpy/core/include -c -c scipy/fftpack/src/dfftpack/dsinti.f -o build/temp.linux-x86_64-2.7/scipy/fftpack/src/dfftpack/dsinti.o" failed with exit status 1

**Comment by pv** [comment]
Where does the strange command line option come from. It does not come from Scipy.

**Comment by pv** [comment]
Seems to be numpy issue https://github.com/numpy/numpy/issues/6495, forwarded there.

**Comment by pv** [comment]
@nilswagner: please leave your gfortran version and OS information on the comments in that numpy bug, thanks!

**Comment by charris** [comment]
@nilswagner Can you try with current numpy master? The problem should be fixed.
