### ISSUE TITLE
[Suggestion] Function greater_close and less_close

### ISSUE THREAD

**Issue by cy18** [scipy/scipy#5390]
I think this would be useful and easy to implement.

    greater_close(a, b)=greater_equal(a, b) | isclose(a, b)
    less_close(a, b)=less_equal(a, b) | isclose(a, b)
    
I'm not sure is it useful enough to be a part of scipy. If so, I will try to implement them and make a pull request. 

Another similar functions are greater_no_close and less_no_close, they will return false if a and b are close in an given error.

**Comment by josef-pkt** [comment]
I think this would belong to numpy.

What's the broadcasting here, is this elementwise? I don't find an existing function `is_close`

I'm using elementwise inequality comparison with noise margin like this in several places, with ad-hoc closeness, like `x < y + 1e-8` or weak inequality. I use `all` version almost exclusively in the assert version `numpy.testing.assert_allclose`

**Comment by cy18** [comment]
Oh, it's isclose
