### ISSUE TITLE
Numpy 1.10 breaks scipy.io.netcdf_file()

### ISSUE THREAD

**Issue by weatherfrog** [scipy/scipy#5397]
Numpy 1.10.* seems to have broken something in ``scipy.io.netcdf_file``. The following code fails silently and leads to extensive memory usage (several GBs). It works as expected with numpy <= 1.9.
```python
from scipy.io import netcdf_file

nc = netcdf_file("data.nc")
```
It does not happen with all netcdf files, though. Here you can download a netcdf3 file that reproduces the error (be prepared to hit Ctrl+C before your memory is exhausted):
https://github.com/weatherfrog/notebooks/blob/master/data.nc?raw=true
Tested with Python 2.7/3.4 on Linux and OS X (64 Bit). ``scipy.__version__ == '0.16.0'``.

**Comment by charris** [comment]
I wonder if this is related to #6467? The report there is of slowdowns, not memory consumption though. A fix for that has been merged, is it possible that you can test with the current 1.10.x branch?

**Comment by weatherfrog** [comment]
I will test with current 1.10.x branch and report back...

**Comment by weatherfrog** [comment]
Tested again with numpy 1.10.4 (scipy 0.17.0). Bug is gone. So I'll close this issue.

**Comment by rgommers** [comment]
thanks @weatherfrog
