### ISSUE TITLE
linprog returns solution that violates inequality constraint

### ISSUE THREAD

**Issue by akxlr** [scipy/scipy#5400]
I am finding that `optimize.linprog` returns a solution that violates one of the inequality constraints. The code below shows the issue. I could not attach the data here so the full example with input matrices is at https://github.com/akxlr/linprog_example.

```
import numpy as np
import scipy as sp
from scipy import optimize

print(np.__version__)
print(sp.__version__)

A_ub = np.loadtxt("A_ub.txt")
b_ub = np.loadtxt("b_ub.txt")
c = np.loadtxt("c.txt")

res = optimize.linprog(c, A_ub, b_ub)
print(res)

print(np.dot(A_ub, res["x"]) <= b_ub)
```

Output (note the `False`):

```
$ ipython3 linprog.py
1.9.2
0.16.0
     fun: -190.60270595672296
 message: 'Optimization terminated successfully.'
  status: 0
       x: array([  2.97493693e+02,   1.00000000e+02,   1.46656947e+01,
         1.00000000e+02,   1.00000000e+02,   0.00000000e+00,
         1.00000000e+02,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   8.43343053e-03,   1.35133800e-03,
         2.75978408e-02,   0.00000000e+00,   2.46647019e-02,
         2.57472418e+02])
     nit: 13
   slack: array([  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   8.53343053e+01,   0.00000000e+00,
         0.00000000e+00,   1.00000000e+02,   0.00000000e+00,
         9.00000000e+02,   9.00000000e+02,   9.00000000e+02,
         9.00000000e+02,   9.00000000e+02,   9.00000000e+02,
         8.43343053e-03,   1.35133800e-03,   2.75978408e-02,
         0.00000000e+00,   2.46647019e-02,   2.57472418e+02,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         1.00000000e+02,   0.00000000e+00,   2.57468078e+06])
 success: True
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False  True
  True  True  True]
```

Am I doing something wrong or is this a bug?

**Comment by argriffing** [comment]
> Am I doing something wrong or is this a bug?

It seems like a bug in the implementation or a numerical problem in the algorithm. Maybe the scipy linprog code should be modified to check that the output is internally consistent before returning.

Here's the same example in a self-contained script:
```python
from __future__ import print_function, division

import numpy as np
import scipy
from scipy import optimize

print('numpy version', np.__version__)
print('scipy version', scipy.__version__)

A_ub = np.array([
    [1, -2.99, 0, 0, -3, 0, 0, 0, -1, -1, 0, -1, -1, 1, 1, 0, 0, 0, 0],
    [1, 0, -2.9, -3.1, 0, -3, 0, -1, 0, 0, -1, 0, -1, 0, 0, 1, 1, 0, 0],
    [1, 0, 0, -3.1, 0, 0, -3, -1, -1, 0, -1, -1, 0, 0, 0, 0, 0, 1, 1],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1],
    [0, 1.99, -1, -1, 0, 0, 0, -1, 1/9, 1/9, 0, 0, 0, -10000, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 2, -1, -1, 0, 0, 0, -1, 1/9, 1/9, 0, -10000, 0, 0, 0, 0],
    [0, -1, 1.9, 2.1, 0, 0, 0, 1/9, -1, -1, 0, 0, 0, 0, 0, -10000, 0, 0, 0],
    [0, 0, 0, 0, -1, 2, -1, 0, 0, 0, 1/9, -1, 1/9, 0, 0, 0, -10000, 0, 0],
    [0, -1, -1, 2.1, 0, 0, 0, 1/9, 1/9, -1, 0, 0, 0, 0, 0, 0, 0, -10000, 0],
    [0, 0, 0, 0, -1, -1, 2, 0, 0, 0, 1/9, 1/9, -1, 0, 0, 0, 0, 0, -10000]])

b_ub = np.array([
    0.0, 0, 0, 100, 100, 100, 100, 100, 100, 900, 900, 900, 900, 900,
    900, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

c = np.array([-1.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0])

res = optimize.linprog(c, A_ub, b_ub)
print(res)

print(np.dot(A_ub, res["x"]) <= b_ub)
```

```
numpy version 1.11.0.dev0+972dbd0
scipy version 0.17.0.dev0+afd7fb8
  status: 0
   slack: array([  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   8.53343053e+01,   0.00000000e+00,
         0.00000000e+00,   1.00000000e+02,   0.00000000e+00,
         9.00000000e+02,   9.00000000e+02,   9.00000000e+02,
         9.00000000e+02,   9.00000000e+02,   6.42527582e+02,
         8.43343053e-03,   1.35133800e-03,   2.75978408e-02,
         0.00000000e+00,   2.46647019e-02,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         1.00000000e+02,   0.00000000e+00,   2.14071981e+02])
 success: True
     fun: -190.60270595672296
       x: array([  5.54966111e+02,   1.00000000e+02,   1.46656947e+01,
         1.00000000e+02,   1.00000000e+02,   0.00000000e+00,
         1.00000000e+02,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         2.57472418e+02,   8.43343053e-03,   1.35133800e-03,
         2.75978408e-02,   0.00000000e+00,   2.46647019e-02,
         0.00000000e+00])
 message: 'Optimization terminated successfully.'
     nit: 13
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False  True
  True  True  True]
```

cc @robfalck

**Comment by argriffing** [comment]
The result is similar if some constraints are rewritten as bounds.
```python
from __future__ import print_function, division
import numpy as np
from scipy import optimize

bounds = [
        (0, None),
        (0, 100), (0, 100), (0, 100), (0, 100), (0, 100), (0, 100),
        (0, 900), (0, 900), (0, 900), (0, 900), (0, 900), (0, 900),
        (0, None), (0, None), (0, None), (0, None), (0, None), (0, None)]

A_ub = np.array([
    [1, -2.99, 0, 0, -3, 0, 0, 0, -1, -1, 0, -1, -1, 1, 1, 0, 0, 0, 0],
    [1, 0, -2.9, -3.1, 0, -3, 0, -1, 0, 0, -1, 0, -1, 0, 0, 1, 1, 0, 0],
    [1, 0, 0, -3.1, 0, 0, -3, -1, -1, 0, -1, -1, 0, 0, 0, 0, 0, 1, 1],
    [0, 1.99, -1, -1, 0, 0, 0, -1, 1/9, 1/9, 0, 0, 0, -1e4, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 2, -1, -1, 0, 0, 0, -1, 1/9, 1/9, 0, -1e4, 0, 0, 0, 0],
    [0, -1, 1.9, 2.1, 0, 0, 0, 1/9, -1, -1, 0, 0, 0, 0, 0, -1e4, 0, 0, 0],
    [0, 0, 0, 0, -1, 2, -1, 0, 0, 0, 1/9, -1, 1/9, 0, 0, 0, -1e4, 0, 0],
    [0, -1, -1, 2.1, 0, 0, 0, 1/9, 1/9, -1, 0, 0, 0, 0, 0, 0, 0, -1e4, 0],
    [0, 0, 0, 0, -1, -1, 2, 0, 0, 0, 1/9, 1/9, -1, 0, 0, 0, 0, 0, -1e4]])

b_ub = np.array([0.0, 0, 0, 0, 0, 0, 0, 0, 0])
c = np.array([-1.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0])

res = optimize.linprog(c, A_ub, b_ub, bounds=bounds)
print(res)
print(np.dot(A_ub, res["x"]) <= b_ub)
```

```
status: 0
   slack: array([   0.        ,    0.        ,    0.        ,    0.        ,
          0.        ,    0.        ,  100.        ,    0.        ,
        214.07198108,    0.        ,   85.33430528,    0.        ,
          0.        ,  100.        ,    0.        ,  900.        ,
        900.        ,  900.        ,  900.        ,  900.        ,
        642.52758155])
 success: True
     fun: -190.60270595672296
       x: array([  5.54966111e+02,   1.00000000e+02,   1.46656947e+01,
         1.00000000e+02,   1.00000000e+02,   0.00000000e+00,
         1.00000000e+02,   0.00000000e+00,   0.00000000e+00,
         0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         2.57472418e+02,   8.43343053e-03,   1.35133800e-03,
         2.75978408e-02,   0.00000000e+00,   2.46647019e-02,
         0.00000000e+00])
 message: 'Optimization terminated successfully.'
     nit: 13
[ True  True  True  True False  True  True  True  True]
```

**Comment by argriffing** [comment]
I wasn't able to determine whether it's a problem with the intended algorithm or with the implementation, but I'll give some uninteresting details and a not very nice workaround.

There's a default 'tolerance' of 1e-12 in the linprog code.  In the first few iterations the code is doing something like subtracting two 'equal' floats and getting 2e-16 which it multiplies by 10000 to get 2e-12 exceeding the tolerance.  If you tell it to interpret 2e-12 as zero by calling `optimize.linprog(c, A_ub, b_ub, options=dict(tol=1e-11))` then on my system the optimizer finds a more reasonable solution that meets the bounds more closely.

**Comment by mdhaber** [comment]
I just posted a solution to #6690 that doesn't seem to apply here; I can't find any obvious redundancy in the formulation of this problem.

I have been working on an interior point option for linprog which also has some issues when a problem formulation includes redundancy, but for this problem my code reports a solution:
```
    fun: -106.63507541835018
       x: array([  3.09979335e+02,   3.34425911e+00,   3.19095684e-09,
         1.00000000e+02,   1.00000000e+02,   6.80740683e-08,
         7.10465111e-08,   3.33763897e-10,   3.35456317e-10,
         1.67724261e-10,   3.33804658e-10,   3.35422753e-10,
         3.35399710e-10,   3.33770323e-10,   2.00000003e-02,
         2.06655744e-02,   3.35425607e-10,   2.06655744e-02,
         3.35402547e-10])
```
that is at least feasible:

```python
x = np.array([  3.09979334e+02,   3.34425902e+00,   4.22329535e-10,
         1.00000000e+02,   1.00000000e+02,   9.04242011e-09,
         9.21073592e-09,   8.39401108e-10,   1.66960794e-13,
         1.17096079e-10,   1.53797198e-14,   3.72600102e-10,
         3.52675737e-15,   3.51872260e-09,   2.00000014e-02,
         2.06655742e-02,   1.01961977e-19,   2.06655741e-02,
         2.75108801e-16])
print("Obeys Inequality Constraints: ", np.all(np.dot(A_ub, x) <= b_ub))
bounds =np.array([(tup[0],np.inf) if tup[1] == None else tup for tup in bounds])
print("Obeys Lower Bound Constraints: ",np.all(x >= bounds[:,0]))
print("Obeys Upper Bound Constraints: ",np.all(x <= bounds[:,1]))
```
(Can somebody check for optimality against another linear program solver?)

I take these as evidence that the solution proposed for #6690 will not fix this.

**Comment by mdhaber** [comment]
1. For linprog's solution `res`,the dot product of the objective and solution vectors `c.dot(res.x)` is `117.1720022088121`, which is not even close to `res.fun` (`-190.60270595672296`). So not only are the constraints not satisfied, but the objective function value is completely wrong.

2. Turning on the undocumented option for Bland's (anticycling) rule fixes the problem. 
```python
res = optimize.linprog(c,A_ub,b_ub,bounds=bounds,options={"bland":True})
print("Satisfies constraints: ",np.all(np.dot(A_ub,res.x) - b_ub < 1e-9))
print("Objective correct: ", np.allclose(c.dot(res.x),res.fun))
```
So turning on Bland's rule results in a solution that satisfies the constraints and is likely optimal, as it agrees with the output of the interior point code.

A partial solution would be to mention Bland's rule (and `tol`) in the documentation. It would also be easy to do a check that the reported solution is feasible and return an error code if it's not.

I consider this only a partial solution because there might still be a bug lurking. Bland's rule is intended to prevent cycling caused by degeneracy. It fixes the present issue, which suggests that the root cause of the present issue is degeneracy in the problem. But without Bland's rule, we don't experience cycling, rather we get erroneous termination, a bogus objective value, and unsatisfied constraints. I can implement the partial fix, but can somebody more familiar with simplex investigate further?

**Comment by mdhaber** [comment]
The behavior for #5400 with `method = 'simplex'` has changed after recent bug fixes. It's definitely better in a lot of ways, but perhaps it is still not perfect.

Now, with either pivoting method, presolve on or off, and default `tol`, it fails to find a basic feasible solution and (thus correctly) reports failure. I guess that's OK?

If we make `tol` less stringent, say 1e-6, `linprog` actually returns the correct solution (again, with either pivoting method, presolve on or off). That's great!

Finally, for certain tolerance value ranges, `linprog` now raises a `ValueError`. For instance, `tol = 1e-11` gives this error for all combinations of presolve and Bland's rule. Sorry to bring it up again now, especially since we probably discussed it before - but is this the behavior we wanted here? Why not just a failure status in a returned `OptimizeResult?

Also, the test `test_bug_5400` could be stronger. Currently, it only checks that there is a warning about the small pivot value. I think we should also check the exit status, at least.

Sorry if it looked like this was done. What do you think, @kai-striega? Is this what we want the behavior to be? If we decide it should be different, I can try making the changes if you're getting tired of this one ; )

**Comment by Kai-Striega** [comment]
@mdhaber We expected the value error to occur (see your comment on 31/07 #9076 ). The different outcomes for tolerance ranges depend on how much simplex "explodes" after phase one simplex.

If the pseudo-objective function evaluates to be slightly greater than `tol`, simplex returns ``status=2 `` (problem is infeasible). ``_post_solve`` converts the problem to standard where, if the explosion is small "enough" the solution becomes feasible again.

```
 elif status == 2 and is_feasible:
        # Occurs if the simplex method exits after phase one with a very
        # nearly basic feasible solution. Postsolving can make the solution
        #basic, however, this solution is NOT optimal
        raise ValueError(message)
```

A similar division occurs, but, during the pivot, this is **not** erroneous but a result of the chosen 
tolerance value. In some particular problems (e.g. in ``5400``) the solution remains basic/feasible but is "scaled" (probably not the best analogy) incorrectly. I'm not really sure if we can/should return more than an error; ``simplex`` never fails (i.e. `status==0`), the tolerance is never exceeded and a BFS is returned **but** this solution is incorrect and the above tests don't catch it.
