### ISSUE TITLE
BUG: ndimage.label() function doesn't checks for byteswapped or unalligned arrays.

### ISSUE THREAD

**Issue by aman-iitj** [scipy/scipy#5402]
The ndimage.label() function implementation doesn't checks for byteswapping or alignment of arrays. This can be corrected using PyArray_FROM_OF API. Documentation can be seen here: https://docs.scipy.org/doc/numpy-1.3.x/reference/c-api.array.html

**Comment by aman-iitj** [comment]
@rgommers Can you please confirm this issue.

**Comment by rgommers** [comment]
@aman-iitj I had a look at ``_label`` in ``_ni_label.pyx``, but it's not immediately obvious to me that the used iterators need those checks. If you're correct then it shouldn't be too hard to construct an example that breaks, right?

**Comment by cdouglass** [comment]
@rgommers I found this issue while poking around for stuff related to #7388, and attempted to produce failing examples by inserting the following tests into `scipy/ndimage/tests/test_measurements.py`:

```def test_label_with_nonnative_output_dtype():
    data = np.array([[3, 2], [0, 0]]) 
    for out in [np.empty_like(data),
                np.empty_like(data).astype(data.dtype.newbyteorder())]:
        n = ndimage.label(data, output=out)
        assert_array_almost_equal(out, [[1, 1], [0, 0]]) 
        assert_equal(n, 1)

def test_label_with_nonnative_output_ndarray():
    data = np.array([[3, 2], [0, 0]]) 
    for dtype in [data.dtype, data.dtype.newbyteorder()]:
        out, n = ndimage.label(data, output=dtype)
        assert_array_almost_equal(out, [[1, 1], [0, 0]]) 
        assert_equal(n, 1)
```
Both non-native cases raised the Cython error [ValueError: Big-endian buffer not supported on little-endian compiler](https://github.com/cython/cython/blob/master/Cython/Utility/Buffer.c#L624) on my machine, tracing back to `File "_ni_label.pyx", line 98, in _ni_label.get_read_line (scipy/ndimage/src/_ni_label.c:7438)`, so there does not seem to be a way for endianness issues to cause bad results here.

I am less clear on how to verify absence of alignment bugs, but the Cython function raising that `ValueError` does also appear to do some sort of alignment checking. Given this plus the absence of known broken examples I suspect this issue can be closed.

**Comment by rgommers** [comment]
Thanks @cdouglass! I agree, let's close this - things look fine, and if there's a subtle issue left somewhere then eventually we'll get a reproducible example for it.
