### ISSUE TITLE
scipy not want to be install with pip2.7 and pip3.4

### ISSUE THREAD

**Issue by catafest** [scipy/scipy#5406]
Seam the scipy not want to be install if I used pip2.7 and pip3.4

python 3.4.1 version told me : 

	Command "c:\python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Us
	ers\\catafest\\AppData\\Local\\Temp\\pip-build-vh3jr0t9\\scipy\\setup.py';exec(co
	mpile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __
	file__, 'exec'))" install --record C:\Users\catafest\AppData\Local\Temp\pip-t7hmh
	ukb-record\install-record.txt --single-version-externally-managed --compile" fai
	led with error code 1 in C:\Users\catafest\AppData\Local\Temp\pip-build-vh3jr0t9\
	scipy

and python 2.7.6 told me also : 

	    ----------------------------------------
	Command "c:\python27\python.exe -c "import setuptools, tokenize;__file__='c:\\us
	ers\\catafest\\appdata\\local\\temp\\pip-build-_cznax\\scipy\\setup.py';exec(comp
	ile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __fi
	le__, 'exec'))" install --record c:\users\catafest\appdata\local\temp\pip-bhwil1-
	record\install-record.txt --single-version-externally-managed --compile" failed
	with error code 1 in c:\users\catafest\appdata\local\temp\pip-build-_cznax\scipy
	c:\python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py
	:90: InsecurePlatformWarning: A true SSLContext object is not available. This pr
	events urllib3 from configuring SSL appropriately and may cause certain SSL conn
	ections to fail. For more information, see https://urllib3.readthedocs.org/en/la
	test/security.html#insecureplatformwarning.
	  InsecurePlatformWarning

**Comment by pv** [comment]
Please see: https://scipy.org/install.html

Installing via pip on windows is not supported (unless you know how to set up fortran compilers on windows).
