### ISSUE TITLE
DOC bug: brent bracket is a,b

### ISSUE THREAD

**Issue by josef-pkt** [scipy/scipy#5408]
The `brent` doc string says `brack` is (a, c) for the bracket search, but from `bracket` it looks like it's (a,b) and `bracket` looks for `c`.

I'm using brent for the first time, and use 2-point bracket. I got weird results when I provide expected (a,c), but good results if I provide expected (a, b)

**Comment by rgommers** [comment]
I think the documentation is correct but that it's a bug in ``Brent.get_bracket_info``:

        elif len(brack) == 2:
            xa, xb, xc, fa, fb, fc, funcalls = bracket(func, xa=brack[0],
                                                       xb=brack[1], args=args)
 
Should be ``xb=brack[2]``. Disclaimer: I only had a very quick look.

**Comment by person142** [comment]
I think the code is fine (when ```len(brack) == 2``` the two entries should be the endpoints for the bracket search). The documentation for ```bracket``` and ```brent``` uses different notation, which is confusing. Submitted a pr which hopefully makes things clearer.

**Comment by josef-pkt** [comment]
AFAICS, the bracket search for xc continuous above xb
https://github.com/person142/scipy/blob/gh-5408/scipy/optimize/optimize.py#L2106

@rgommers   I don't think we can consider definitions a bug.
In your code snippet `xb=brack[2]` doesn't work because this is for the case when brack only has two elements. The question is whether these are (a,b) or (a,c)   for a<b<c as target.

I also didn't try to figure out more than to get to the line with `xc = xb + _gold * (xb - xa)`  with `_gold = 1.618034`

**Comment by josef-pkt** [comment]
my example had f(brack[0) == f(brack[1])  and I thought brent/bracket will look for a point inside, instead it looks like it was looking above brack[1].  
My code is pretty convoluted right now, and I don't have a simple example yet, and I don't have enough unit tests yet for the individual parts, to know whether my guesses are correct.

**Comment by rgommers** [comment]
> In your code snippet xb=brack[2] doesn't work ...

Indeed, sorry for the noise. Will go have a look at the PR.
