### ISSUE TITLE
FAIL: test_fftpack_import (test_import.TestFFTPackImport)

### ISSUE THREAD

**Issue by WoMax** [scipy/scipy#5421]
Hello,

after finishing scipy.test('full') I got 1 failure:

FAIL: test_fftpack_import (test_import.TestFFTPackImport)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/maks/PycharmProjects/_virtualenv/data/lib/python3.4/site-packages/scipy/fftpack/tests/test_import.py", line 30, in test_fftpack_import
    "{} contains an import from fftpack".format(path))
  File "/home/maks/PycharmProjects/_virtualenv/data/lib/python3.4/site-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError: /home/maks/PycharmProjects/_virtualenv/data/lib/python3.4/site-packages/scipy/scipy/fftpack/realtransforms.py contains an import from fftpack

**Comment by rgommers** [comment]
Interesting. The check at https://github.com/scipy/scipy/blob/master/scipy/fftpack/tests/test_import.py#L25 should ensure that the files in ``scipy/fftpack/`` aren't checked for this.

I can't reproduce this, so could you help to debug this? If you put the assert in a try-except and then in the except check what the values of ``base``, ``path`` and ``path.parents`` are, then it should be understandable why 

    if base / "fftpack" in path.parents:
        continue

doesn't work on your system.

**Comment by WoMax** [comment]
Thx for quick answer.

Yeah, with your help I found the reason.

In my case:
base / "fftpack" = '/home/maks/PycharmProjects/_virtualenv/data/lib/python3.4/site-packages/scipy/fftpack'

meanwhile path to realtransforms.py is: '/home/maks/PycharmProjects/_virtualenv/data/lib/python3.4/site-packages/scipy/scipy/fftpack/realtransforms.py'

**Comment by rgommers** [comment]
That's weird. So do you have a duplicate set of files in ``site-packages/scipy/`` or ``site-packages/scipy/scipy/``? Seems like an install issue then. Normally in ``site-packages`` you only have ``scipy/`` not ``scipy/scipy/``.

**Comment by WoMax** [comment]
I made installation of scipy from source inside site-packages folder. Maybe it was wrong?

Here is my listing of files:

(data)maks@maks-1215N:~/PycharmProjects/_virtualenv/data/lib/python3.4/site-packages/scipy$ ls
benchmarks       cythonize.dat    _lib         pavement.py       sparse
BENTO_BUILD.txt  doc              LICENSE.txt  __pycache__       spatial
bento.info       fftpack          linalg       README.rst        special
bscript          HACKING.rst.txt  linalg.pxd   runtests.py       stats
build            __init__.py      MANIFEST.in  scipy             THANKS.txt
_build_utils     INSTALL.rst.txt  misc         setupegg.py       tools
cluster          integrate        ndimage      setup.py          tox.ini
__config__.py    interpolate      odr          signal            version.py
constants        io               optimize     site.cfg.example

(data)maks@maks-1215N:~/PycharmProjects/_virtualenv/data/lib/python3.4/site-packages/scipy/scipy$ ls
bento.info    fftpack      io          misc      __pycache__  spatial     weave
_build_utils  __init__.py  _lib        ndimage   setup.py     special
cluster       integrate    linalg      odr       signal       stats
constants     interpolate  linalg.pxd  optimize  sparse       version.py

**Comment by rgommers** [comment]
That explains it. Yes, you should never do that. The best way to install into site-packages is with ``pip``. There are source releases on PyPi, so ``pip install scipy --user`` (or ``--prefix=...`` instead of ``--user`` for a custom location) will work. If you're installing from a git checkout or a manually downloaded source tree then you can just do ``pip install . --user``.

**Comment by WoMax** [comment]
No, pip did not install scipy in virtualenv on Ubuntu. It just hanging more then one hour with log "Running setup.py install" in my terminal without installing. 

Also I found described similar problem on stackover: http://stackoverflow.com/questions/2213551/installing-scipy-with-pip

Then i tried to use easy-install, and it installed scipy, but during instalation there was many errors.

And only when I made instalation from source according this instruction: 

https://github.com/scipy/scipy/blob/master/INSTALL.rst.txt#installation
 
everything was okay (besides this failure with fftpack).

So right solution for my problem is: installing from source, but folder with source should not to be in site-packages folder. Then instalation will be done properly (scipy will be installed in site-packages folder without duplicates)

After testing I got zero failures.

I think problem instalation scipy using pip it's a bug and needs fixing.

**Comment by rgommers** [comment]
> So right solution for my problem is: installing from source, but folder with source should not to be in site-packages folder. 

Indeed, that will work. The main reason we recommend ``pip`` over ``python setup.py install`` is that the former keeps track of installed files so you get a reliable uninstall option.

> No, pip did not install scipy in virtualenv on Ubuntu. It just hanging more then one hour with log "Running setup.py install" in my terminal without installing.
>
 > Also I found described similar problem on stackover: http://stackoverflow.com/questions/2213551/installing-scipy-with-pip

That's a very old bug report. There shouldn't be issues with ``pip`` anymore (it's tested daily on TravisCI). So it's probably something in your environment.

**Comment by rgommers** [comment]
Note: don't ever use ``easy_install``. It's so outdated and broken that you should avoid it at all cost. It may or may not work if you try, but ``easy_install`` is not supported by Numpy or Scipy anymore.
