### ISSUE TITLE
QUADPACK bug in integral over large intervals

### ISSUE THREAD

**Issue by pv** [scipy/scipy#5428]
Consider:  \int_a^b x^{-3} = (a^{-2} - b^{-2})/2

```
>>> from scipy.integrate import quad
>>> quad(lambda x: 1./x**3, 1e2, 1e6)
(4.999999950022993e-05, 1.4504531443149906e-09)
>>> quad(lambda x: 1./x**3, 1e2, 1e7)
(2.449563049046922e-10, 1.9657280786576196e-09)
```

Total loss of precision. Running it the first time, it emits a warning:

```
scipy/integrate/quadpack.py:321: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  warnings.warn(msg, IntegrationWarning)
```

However, in interactive use the warning is easy to miss/ignore as it disappears the second time.
It appears the warning actually means serious business.

Appears to be a QUADPACK bug: Octave behaves the same way:

```
>> quad(@(x) 1./x.^3, 1e2, 1e6)
ans =    5.0000e-05
>> quad(@(x) 1./x.^3, 1e2, 1e7)
ans =    5.7145e-09
```

Of course, it's not possible to integrate all functions, but this is a relatively simple case where the adaptive integration error estimation appears to be off by quite much.

Reducing epsabs can bump up the failure threshold to `1e10`.

**Comment by josef-pkt** [comment]
General policy: Can we make more of these runtime warning to warn always.
statsmodels uses custom warnings that we can set to always (at least in more recent code)

It would be good, if you can fix it as a bug, but in some cases the user still has to adjust.

```
>>> quad(lambda x: 1./x**3, 1e2, np.inf)
(4.999999999999971e-05, 2.359863313725895e-11)
```

**Comment by mdhaber** [comment]
@ev-br here's another one along the lines of gh-11579. Hopefully gh-17835 helps with these. What do you think about the suggestion above to make the warnings appear every time?

**Comment by ev-br** [comment]
FWIW I don't think the library should mess with the warnings, even if the default "warn once" behavior is unfortunate.

**Comment by mdhaber** [comment]
Ok, I think this is closed then. 
If there are new reports of the same problem, I'd suggest that users support the inclusion of https://github.com/jacobwilliams/quadpack in SciPy and suggest improvements to that version of quadpack.
