### ISSUE TITLE
Python3 : Numpy scalar types "not iterable"; specific instance ndimage.filters.gaussian_filter

### ISSUE THREAD

**Issue by QCaudron** [scipy/scipy#5430]
With some toy code to produce Perlin noise, I came across a discrepancy between Python 2 and Python 3 behaviour. This applies for numpy 1.10.1 and scipy 0.16.0, under Python 2.7.10 and Python 3.4.3.

    X = np.random.normal(size=(256, 256))
    perlin = perlin = np.zeros_like(X)

    for i in 2**np.arange(6) :
        perlin += nd.filters.gaussian_filter(X, i, mode="wrap") * i**2

This works great under Py2. For Py3, I have to cast `i` as `int(i)` in the call to `gaussian_filter`, or I get `TypeError: 'numpy.int64' object is not iterable`.

I'm unsure if this has been seen before; sorry if so. Any thoughts appreciated.

**Comment by person142** [comment]
It looks like the issue occurs in ```ndimage._ni_support._normalize_sequence```, which contains the following snippet:
```python
if isinstance(input, integer_types + (float,)):
    normalized = [input] * rank
else:
    normalized = list(input)
```
In python 3 the input is being sent to the ```else``` clause, which raises the error (the value of ```integer_types``` is python-version dependent). Will try to learn more.

Also, possibly related: https://github.com/numpy/numpy/issues/2951

**Comment by charris** [comment]
I'll guess that `2` is converted to `int64` because it is a long int in Python 3. One solution might be to use `numbers.Integral` instead of integer_types, that should get all the numpy integer types.

**Comment by person142** [comment]
That's a nice solution (changing it to
```python
if isinstance(input, (Integral, float)):
```
fixes the issue), but it wouldn't work for numpy < 1.9 or python < 2.6, right? Would it be okay to break the back-compatibility? (Scipy's \__init__ file currently warns that numpy >= 1.6.2 is recommended, not sure about recommended python version.)

Perhaps the definition of ```integer_types``` could be further refined to use ```numbers.Integral``` when it's available and do something more complicated when it's not (with the aim of being easily able to remove the complicated parts when old versions get deprecated)?

**Comment by rgommers** [comment]
Python < 2.6 we already don't support, so that's not an issue. And 2.6 itself will go at some point in the near future I expect - Matplotlib already dropped support for it I just read.

Things need to work for numpy's before 1.9 though. We can drop 1.6.2 support soon when needed, but dropping also 1.7 and 1.8 support is a bit too much.

**Comment by rgommers** [comment]
However, if something that's broken now can be fixed easily by a >=1.9 feature, then it may be OK to do ``if npversion >= 1.9 then use_working_code else dont_change_a_thing``. I didn't look into this issue, so not sure if a fix for older numpy's is that hard, but a partial fix is better than no fix.

**Comment by person142** [comment]
This issue also affects ```interpolate.BPoly.from_derivatives``` (AFAICT there are only three functions which use ```integer_types```, the remaining one is ```io.netcdf_file._write_values```, which appears to be fine.) The issue with ```BPoly.from_derivatives``` can be seen by running
```python
x = np.linspace(0, 1)
order = np.int64(1)
p = BPoly.from_derivatives([0, 1], [[1, 2], [3, 4]], orders=order)
```
which will raise the same ```TypeError```. Running it with ```orders = 1``` works fine. To me the best fix for ```_normalize_sequence``` seems to be
```python
if hasattr(input, '__iter__'):
    normalized = list(input)
else:
    normalized = [input] * rank
```
with a similar fix for ```BPoly.from_derivatives```. Will write a patch for people to look at.

**Comment by person142** [comment]
(While the ```numbers.Integral``` solution feels more elegant to me, testing for an ```__iter__``` method should work for all versions of numpy.)
