### ISSUE TITLE
mstats.plotting_positions should return arrays of the same shape as the input data

### ISSUE THREAD

**Issue by jhamman** [scipy/scipy#5432]
The [`plotting_positions`](http://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.mstats.plotting_positions.html#scipy.stats.mstats.plotting_positions) function in `mstats` is returning a flattened masked array of the same size but different shape than the input data.  This behavior is different than many of the other non-reduction functions in the stats/mstats module.

``` python
In [1]: import numpy as np

In [2]: from scipy.stats.mstats import rankdata, plotting_positions

In [3]: x = np.random.random((4, 5, 6))

In [4]: rankdata(x).shape
Out[4]: (4, 5, 6)

In [5]: plotting_positions(x).shape
Out[5]: (120,)
```

It should be simple enough to reshape the data after the 1d operation is complete:

``` Python
    shape = data.shape
    data = ma.array(data, copy=False).reshape(1,-1)
    n = data.count()
    plpos = np.empty(data.size, dtype=float)
    plpos[n:] = 0
    plpos[data.argsort()[:n]] = ((np.arange(1, n+1) - alpha) /
                                 (n + 1.0 - alpha - beta))
    return ma.array(plpos, mask=data._mask).reshape(shape)
```

**Comment by josef-pkt** [comment]
It's not clear to me how this should be fixed.
The current version seems to correspond to axis=None.

The default in scipy.stats is axis=0, and if I see a multi dimensional return I would expect that the calculations are done along an axis. 
I would find it misleading in stats, if the function takes and returns nd, but treats it as a single array (axis=None), because this is not an elementwise operation.

**Comment by jhamman** [comment]
@josef-pkt - I see what you are getting at.  Do we agree that the current behavior isn't optimal?  My preferred behavior would be to take the `axis=0` approach.

**Comment by josef-pkt** [comment]
For consistency with the rest of stats, I would also prefer proper axis handling with axis=0 the default.
I can think of examples for both usecases, axis=0 and axis=None, depending on whether we want joint or separate samples.

The main issue is backwards compatibility which would be broken here with either solution. I leave those decisions to @rgommers

**Comment by jhamman** [comment]
@ev-br, @rgommers, and @josef-pkt - 

Just pinging this issue.  I'd be willing to try to put together a fix here if we can get consensus on the path forward.

**Comment by ev-br** [comment]
Sorry for the radio silence on this @jhamman. ISTM that adding an axis kwarg would make sense. The default would need to stay `axis=None` for backwards compat, but then you could specify `axis=0` explicitly.

**Comment by mdhaber** [comment]
Tracking this in gh-14651 with all the other functions that could use an `axis` argument.
