### ISSUE TITLE
Add error message to fmin_slsqp when Objective function returns a list/array (or possible bug)

### ISSUE THREAD

**Issue by edwardsmith999** [scipy/scipy#5433]
`scipy.optimize` `fmin_slsqp` raises an error when the Objective function does not return a scalar. The following cryptic error message is returned:

```
"Scipy fmin_slsqp error failed in converting 8th argument `g' of _slsqp.slsqp to C/Fortran array”
```

If the Objective function is expected to return a scalar, could a check be added and a more transparent error message included (and maybe the `fmin_slsqp/minimisation` documentation could state the form of the Objective function). If this is not the correct behaviour, perhaps this is a bug in wrapper to the fortran code called by `slsqp`?

A minimal example which reproduces the error on scipy version '0.15.0'

```
from scipy.optimize import fmin_slsqp 
#Function which return more than a single scalar argument
def fn(x):
    return [0.,2.]
x = [1.,3.,4.]
minsoln = fmin_slsqp(fn, x)
```

This has led to a number of forum posts with no solution, e.g (http://stackoverflow.com/questions/28733897/scipy-fmin-slsqp-error-failed-in-converting-8th-argument-g-of-slsqp-slsqp-to), (http://stackoverflow.com/questions/16108877/scipy-error-using-optimization-module-failure-converting-array-to-fortran) and (http://numpy-discussion.10968.n7.nabble.com/minimize-Algorithmen-Problem-with-boundarys-td37709.html)

Apologies if this is not clear/in the right format, this is my first bug report.

**Comment by pv** [comment]
Yes, the error message is cryptic, and a more clear one would be more helpful.

**Comment by b-carter** [comment]
I'm happy to take a look/improve this. I see in the spec for `_minimize_slsqp` that `func` must be scalar.

Would it make sense to check the return type after each call to the objective function? Doing so would detect when the return type is off but at a potential performance hit. Alternatively, it can check some x-value initially, and then give a clear error if the output is non-scalar, though if the objective function is buggy and returns non-scalar for only some x, then this wouldn't check all cases and the error would still be cryptic. Maybe it would be better to just improve the `fmin_slsqp` documentation. Thoughts?

**Comment by Darthholi** [comment]
Today I have encountered the bug and I would be really happy if You could improve it - the standard for numerical algorithms is to do these checks against x0 value. 
If the objective function is buggy, then it would involve a lot of work to do this right and it would slow down the whole process ..., But usually the x0 values are randomized, so in the end the buggy-function-creator would notice both these error messages.

**Comment by person142** [comment]
Sorry @b-carter it looks like your message slipped through the cracks. If you're still interested in looking at this--I'll second what @Darthholi said; probably best to just check against the `x0` value. Though documentation clarifications are always a good thing too!

**Comment by edwardsmith999** [comment]
Hi @b-carter, sorry I missed this too.  The basic error check initially (random as suggested by @Darthholi) is good too but, as you say, will not prevent this message in general. Is it possible to catch this error in the `fmin_slsqp` python wrapper if it occurs, then use these values to test the return of the function to give a clear message? If not, I think a change to the `fmin_slsqp` documentation to clarify the required  objective functional form is the best we can do (and useful as there is currently no explicit requirements given there).

**Comment by person142** [comment]
> Is it possible to catch this error in the `fmin_slsqp` python wrapper if it occurs

Yes--as is typical of wrapped Fortran 77 code all function evaluations take place on the python side (because there's no way to pass a in function pointer). See

https://github.com/scipy/scipy/blob/v0.18.1/scipy/optimize/slsqp.py#L367

**Comment by edwardsmith999** [comment]
The error catching would be cumbersome, you'd need to change line [410](https://github.com/scipy/scipy/blob/v0.18.1/scipy/optimize/slsqp.py#410) to something like,

    class ObjectiveFnException(Exception):
        pass

    try:
        slsqp(m, meq, x, xl, xu, fx, c, g, a, acc, majiter, mode, w, jw)
    except Exception as e:
        raise ObjectiveFnException("Error -- objective function should "
                                    +"return a scalar but instead returns " 
                                    + str(fx) + " for input " + str(x)) 

This would only catch F2PY general type `_slsqp.error` so, in addition, some form of specific exception would need to be defined in the F2PY wrapper (if possible??).

A random x0 initial check is probably the best way to go.

**Comment by person142** [comment]
Might be missing something, but why couldn't you do something like

```python
fx = func(x)
try:
    float(fx)
except:
    raise ValueError("objective function must return a scalar")
```
Almost certainly I have missed some subtleties, but I suspect that the general idea would work.

**Comment by edwardsmith999** [comment]
You're right, it'd certainly work and something like this was one of the suggestion of b-carter above, with the concern being the performance hit of evaluating each time. I wondered if `try, except` [could avoid](http://stackoverflow.com/questions/2522005/cost-of-exception-handlers-in-python) this performance hit.

**Comment by person142** [comment]
Ah yes, should have reread @b-carter's post more carefully. TBH, on a serious problem the slowdown from the check is probably negligible compared to the cost of evaluating the objective function/its derivative and doing the linear algebra in the optimization step. So I'd say go for the check and just run the global optimization benchmarks to make sure it doesn't slow things down.

Or just check the initial point--so long as it's done without an extra objective function call. That likely will slow things down. Either way sounds okay to me.

**Comment by b-carter** [comment]
Checking a few resources online, it seems that try-except is relatively inexpensive in Python (if we're not calling the except block often, which we shouldn't be, and if we do, the function is done, anyway), so I think that just adding the try-except would be easiest and probably negligible in terms of performance. I can submit a PR later on today if everyone agrees that it's the way to go?

But a part of me also feels that this is kind of "hacky" in some way, so I'm not entirely convinced.

**Comment by person142** [comment]
I think a PR would be great. I don't think it's hacky--in fact I think it's rather pythonic. It allows for new mystery types to be fed into the function so long as they possess a `__float__` method. (Well, assuming we move the function evaluation into the `try` and make it something like `fx = float(f(x))`.)

**Comment by edwardsmith999** [comment]
I agree a PR would be great, it is certainly an improvement on the current situation. I liked the idea of a `try, except` for the main function on the "easier to ask for forgiveness than permission" mantra of python; but given the lack of clear error from `slsqp` the check on the float convert suggested by person142 is best.

**Comment by Dark-Vador22** [comment]
I obtained the same cryptic error when (falsely) defining the Jacobian of my objective function as diagonal matrix  - np.diag(...). It took some time to figure out what is going on and it might be useful to implement similar changes on that issue... ?
