### ISSUE TITLE
scipy.optimize.basinhopping: accept_test returning numpy.bool_ raises an error

### ISSUE THREAD

**Issue by dEvasEnApati** [scipy/scipy#5440]
Dear Scipy team

When using scipy.optimize.basinhopping, if the accept_test function returns an object of type numpy.bool_, an error occurs. Is this an intentional feature? If not, I think it can be removed allowing accept_test to return numpy.bool_ object.

Thanks
Ajay

**Comment by dlax** [comment]
Indeed, it seems that this is not handled. According to the [code](https://github.com/scipy/scipy/blob/master/scipy/optimize/_basinhopping.py#L124), this function should return an instance of `bool` or a string with a "special value". And it appears that `numpy.bool_` is not an instance of bool. Perhaps this could be better handled without those `instance` calls.

**Comment by andyfaff** [comment]
How about:

    if testres == 'force_accept':
        ...
    elif testres is True:
        ...
    else:
        ...

**Comment by dlax** [comment]
Andrew Nelson wrote:
> How about:
>
> |if testres == 'force_accept': ... elif testres is True: ... else: ... |
>


Not so much better. `np.bool_(True) is not True`.

As a general rule, a function should return a value of the same type 
(i.e. bool here). If you want another behavior, use an exception.
