### ISSUE TITLE
ODE solver scipy.integrate.odeint does not support scipy.sparse matrices for Jacobian

### ISSUE THREAD

**Issue by mcr222** [scipy/scipy#5447]
In ODE solver **scipy.integrate.odeint(func, y0, t, args=(), Dfun=None...)**, Dfun (Jacobian of func) parameter does not accept sparse matrices. 

**Dfun parameter only accepts dense matrices.** If Dfun parameter is a function that returns a sparse matrix this error is thrown: *ValueError: object of too small depth for desired array*

In the code example below any sparse matrix is rejected (sparse.coo_matrix(), sparse.bsr_matrix(), sparse.csc_matrix()...). The function works when a dense matrix is used (use *return J* instead of *return Jsparse* in the code).

Being able to use sparse matrices in Dfun would be extremely useful for large ODE systems, where Jacobian matrices tend to be very sparse (and computations take a long time with full matrices).

```
from scipy import integrate
from scipy import sparse
import numpy as np

def VDPOLf(y,t):
    epsilon=1e-6
    second_dim=1/epsilon*(((1-y[0]**2)*y[1])-y[0])
    return np.array([y[1],second_dim])

def VDPOLgrad(y,t):
    epsilon=1e-6
    matrix12=1/epsilon*(-2*y[0]*y[1]-1)
    matrix22=1/epsilon*(1-y[0]**2)
    J = np.array([[0,1],[matrix12,matrix22]])
    Jsparse = sparse.coo_matrix(J)
    return Jsparse


exactSolution, infodict = integrate.odeint(VDPOLf, np.array([2.,0.]), [0,1], Dfun= VDPOLgrad,
                                            atol=1e-5, rtol=1e-5, mxstep=10000, full_output = True)
```

**Comment by rgommers** [comment]
``odeint`` doesn't know anything about sparse matrices, so this isn't going to fly. hence closing this issue. perhaps someone has a suggestion for another package to use for this?

**Comment by WarrenWeckesser** [comment]
`odeint` can handle a *banded* Jacobian, but not a general sparse matrix.
