### ISSUE TITLE
Error in scipy.integrate.nquad when using variable integration bounds and parametric arguments

### ISSUE THREAD

**Issue by woodscn** [scipy/scipy#5452]
Discovered this today. Working on a fix.
```
>>> from scipy.integrate import nquad
>>> ranges0 = lambda x: [x, 2 * x]
>>> ranges = [ranges0, [1, 2]]
>>> args = 1, 2
>>> func = lambda x0, x1, t0, t1: x0 + x1 + t0 + t1
>>> nquad(func, ranges, args=args)
...
TypeError: <lambda>() takes 1 positional argument but 3 were given
```
Essentially, nquad tries to pass the full parameter list (x0, x1, t0, t1) to the range functions. There are a number of ways to solve this.
- Apply ```args``` at the beginning of the integration using ```partial``` or similar. 
- Change the ```nquad``` API to require that range (and opts) functions accept the full parameter list.
- Silently convert range functions to f(*args), which will ignore the extra arguments. 

Some pros/cons of each:
- Applying ```args``` early is simple, but it makes it harder for someone to optimize by passing a Cython function.
- Changing the API is never good, though it seems unlikely that this will affect many since no one has reported problems with ```ranges``` and ```args``` before, and nothing that wasn't already broken would change.
- Silent conversion is what we do already when ```nquad``` is given constant ranges. This would prevent anyone from using parametric ```ranges``` or ```opts```, which aren't supported anyway.

My inclination is to take the second option. Thoughts? Other solutions I've missed?

**Comment by woodscn** [comment]
I should mention that the actual API wouldn't change. Only the documented API would, to accurately reflect what the code is already doing.

**Comment by rgommers** [comment]
@woodscn in gh-5906 you said that that PR addresses this issue, but that doesn't seem to be the case. Right?

**Comment by rgommers** [comment]
Oh right, I see what you meant now - the ``ranges`` parameter documentation changed in gh-5906 (option 2), so the example above still doesn't work.

**Comment by rgommers** [comment]
Why wouldn't you want to take the ``*args`` approach? That would not break anything and fix the example above, if I understand correctly. That's also what you did for ``dblquad`` and ``tplquad`` it looks like. And it seems nicer to just take the parameter for the dimension over which you are integration in a ``ranges`` callable, rather than that dimension plus all inner ones.

**Comment by woodscn** [comment]
Sorry, I'm not totally clear on this. Are you referring to option 3? I'll assume so. 

I don't think there was any particular reason, other than that it was easier to change the documentation rather than the code. I'm not entirely sure what you meant at the end ("It seems nicer..."). The parameters t0, t1, don't correspond to any particular dimension, and they would all have to be passed in at every level anyway.

**Comment by rgommers** [comment]
> Sorry, I'm not totally clear on this. Are you referring to option 3? I'll assume so. 

Indeed.

> The parameters t0, t1, don't correspond to any particular dimension, and they would all have to be passed in at every level anyway.

OK, I looked a bit closer and understand now. Maybe explicit is better than implicit here, so adjusting the docs looks fine to me. It's hard enough to understand from the code what gets passed to a range callable. I'll close this issue as fixed then.

**Comment by rgommers** [comment]
Thanks @woodscn

**Comment by woodscn** [comment]
If you'd like me to go back over it in the future, I can. For now, I think the memory leaks etc. in the C code bug me more. :-\

**Comment by rgommers** [comment]
> If you'd like me to go back over it in the future, I can.

No, I think it's fine. What probably would be helpful though is some comments in ``_NQuad.integrate`` that explain the recursive calls, ``depth`` and what gets passed to ``fn_range``.

> For now, I think the memory leaks etc. in the C code bug me more. 

definitely

**Comment by woodscn** [comment]
Tried to implement option 3 in response to #6458, but this turned out to be hard. Basically, at some point, you have to know the function signature of whatever range or opt function you're calling, and there's no obvious way to get that (I.e. Number of range variables, number of arg variables) without requiring the user to specify it in some way. As a result, I fixed things specifically in dblquad, and moved on.
