### ISSUE TITLE
Error in scipy.integrate.nquad when using variable integration bounds

### ISSUE THREAD

**Issue by woodscn** [scipy/scipy#5453]
Apparently variable integration bounds in general have problems in ```nquad```. Here's another one. 
```
>>> ranges = [lambda x: [x, 2*x], [1, 2]]
>>> func = lambda x, y: x**2*y
>>> func2 = lambda y, x: x**2*y
>>> nquad(func, ranges)
(14.466666666666667, 4.1268615863688816e-13)
>>> nquad(func2, ranges)
(9.3, 2.6529824483799947e-13)
```
Unfortunately, ```nquad``` is mixing up the order of the integration bounds. The equivalent Mathematica code give the correct answers:
```
f[x_, y_] := x^2 y
N[Integrate[f[x, y], {x, 1, 2}, {y, x, 2 x}]]
N[Integrate[f[y, x], {x, 1, 2}, {y, x, 2 x}]]
9.3
14.4667
```
#5452

**Comment by woodscn** [comment]
Nope, nevermind. This one here is correct. The definition of ranges is confusing, since it's actually lambda y.

**Comment by ewmoore** [comment]
@woodscn, since you wrote `nquad` and were confused, are there some changes to the docstring, examples or tutorial that would make this clearer? I haven't used `nquad`, but if it's confusing you here some time after you wrote it, I'll bet the docs could be better.

**Comment by woodscn** [comment]
Maybe. Part of the problem is that I'm trying to interface it with ```tpl_quad```, where the interface is reversed. Let me work out those difficulties, and maybe that will suggest a better way forward.

**Comment by woodscn** [comment]
Yeah, I really think that the problems arose from trying to juggle the two different interfaces (tplquad's is especially confusing). Taking a problem that was written for one order of integration, with a specific set of variables, and then trying to use that in a completely different function was painful, and required a lot of careful work bookkeeping with variables. 

One take-away here for me was that the tplquad interface is super confusing. Should we start a conversation about deprecating tplquad?
