### ISSUE TITLE
Call to gcc failed during installation

### ISSUE THREAD

**Issue by dabliss** [scipy/scipy#5454]
Hi all,

I just attempted to install scipy from the most recent commit on the master branch.  This is the bottom of the (somewhat cryptic) error I received:

```
build/src.linux-i686-2.7/scipy/optimize/lbfgsb/_lbfgsbmodule.c: At top level:
build/src.linux-i686-2.7/scipy/optimize/lbfgsb/_lbfgsbmodule.c:184:12: warning: ‘f2py_size’ defined but not used [-Wunused-function]
 static int f2py_size(PyArrayObject* var, ...)
            ^
error: Command "i686-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DNO_ATLAS_INFO=1 -DNPY_NO_DEPRECATED_API=NPY_1_9_API_VERSION -Ibuild/src.linux-i686-2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c build/src.linux-i686-2.7/scipy/optimize/lbfgsb/_lbfgsbmodule.c -o build/temp.linux-i686-2.7/build/src.linux-i686-2.7/scipy/optimize/lbfgsb/_lbfgsbmodule.o" failed with exit status 1
```

Anyone have any idea what this means?

Note the failure occurs when I try to install from commit `729e5fb023`.  I will update this with the most recent commit that doesn't fail for me as soon as I can find it.

**Comment by dabliss** [comment]
It appears this error was due to my not having deleted the build directory from a previous installation.  So I'm closing . . .

**Comment by dowenrei** [comment]
@dabliss I'm getting the same error too. How should I check if I have the previous installation?
As I have run `pip uninstall scipy` in my raspberry pi
