### ISSUE TITLE
griddata - new interpolation method='rbf'

### ISSUE THREAD

**Issue by denfromufa** [scipy/scipy#5456]
Why not to include `rbf` as one of interpolation methods to `griddata`? `LinearNDInterpolator` can have significant error when interpolating data with curvatures between piece-wise linear sections formed by simplices. `rbf` options such as `function`, `epsilon`, etc.  can be passed as dictionary to `method`.

**Comment by ev-br** [comment]
I guess you'd need to give a bit more motivation on how it is an improvement over using Rbf directly.

**Comment by denfromufa** [comment]
the motivation is that the interpolator and interpolation happen in one step, and griddata lacks interpolation with non-linear options in 3+ dimensions, which rbf can provide. It is just convenience when switching between LinearNDInterpolator and rbf.

**Comment by rgommers** [comment]
Let's call this rejected - please use the new `RBFInterpolator` directly.
