### ISSUE TITLE
document whether polynomial coefficients are used in descending or ascending order of degree

### ISSUE THREAD

**Issue by jason-s** [scipy/scipy#5463]
[tf2ss](https://github.com/scipy/scipy/blob/master/scipy/signal/ltisys.py#L49) says 

    Parameters
    ----------
    num, den : array_like
        Sequences representing the numerator and denominator polynomials.
        The denominator needs to be at least as long as the numerator.
    Returns
    -------
    A, B, C, D : ndarray
        State space representation of the system, in controller canonical
        form.

Suggest changing to 

        Sequences representing the coefficients of numerator and denominator
        polynomials, in order of descending degree.

I can tell from the example in the latest source code (I guess this is new, the [0.16.0 docs](http://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.signal.tf2ss.html) don't include that) that it's descending because s^2 + 3s + 3 is represented by [1,3,3]

**Comment by jason-s** [comment]
This applies to all functions in scipy requiring polynomial coefficients. (ltisys.py includes a number of other functions like `lsim2()` and `step()` that take `(num, den)` inputs.)

**Comment by rgommers** [comment]
Agreed. The example does make it clear, but adding "descending order" will be helpful.

**Comment by andyfaff** [comment]
It's a bit unfortunate that the coefficients are in descending degree. The `numpy.polynomial` submodules are all in increasing order, which is more logical (index in array is the same as degree). A newer version of this code could even use Polynomial instances as input?
In general does scipy use descending or ascending order?

**Comment by rgommers** [comment]
In general: there's not that many polynomials around in Scipy, and I suspect that for those that are the authors didn't look at consistency with the rest of Scipy. So it's all fairly arbitrary.

Agree that ascending order would be better, but don't see how to change that here.

**Comment by WarrenWeckesser** [comment]
scipy's use of the decreasing convention predates the existence of the numpy `polynomial` class.  scipy is consistent with the older `numpy.poly1d` class.

Adding a line to the relevant docstrings about the order is a great idea.
