### ISSUE TITLE
macro documentation for weave.inline

### ISSUE THREAD

**Issue by Fredr1kh** [scipy/scipy#5464]
when writing C-code for inline and using arrays, it would be nice to actually be able to look up the documentation and see that inline defines a macro for the array passed in to it.

example
#define U2(i,j) (*((double*)(u_array->data + (i)*Su[0] + (j)*Su[1])))

**Comment by argriffing** [comment]
weave has been moved into a separate repo https://github.com/scipy/weave

**Comment by Fredr1kh** [comment]
Added a pull request for a rough draft to the weave repo on the macro
