### ISSUE TITLE
gaussian_kde hangs on arm/odroid

### ISSUE THREAD

**Issue by dgorissen** [scipy/scipy#5470]
Python 2.7.9 with Scipy 0.14.1 on an odroid XU4 with Ubuntu vivid
The following line in my script simply hangs on an odroid but works fine on a regular linux box

kd = stats.gaussian_kde(x, bw_method="scott")

x is ~100 1D points.

Switching to the scikit-learn density estimator works but I would prefer to stick with scipy

**Comment by dgorissen** [comment]
I worked around this by using the scikit-learn implementation of KDE but then I found signal.decimate() and signal.butter() were giving the same problem. This was using the standard python-numpy, python-scipy packages that come with 15.04. 

Hence I removed the ubuntu python-numpy/scipy packages, created a clean virtualenv, overcame #5574 by installing numpy 1.9.2. Now the following code generates a BUS error.

```
>>> x=range(100)
>>> stats.gaussian_kde(x)

Under gdb:

Program received signal SIGBUS, Bus error.
0xb659f28a in drot_k () from /usr/lib/libopenblas.so.0
(gdb) bt
#0  0xb659f28a in drot_k () from /usr/lib/libopenblas.so.0
#1  0xb6b9a836 in DOUBLE_dot (a=<optimized out>, stridea=<optimized out>, b=<optimized out>, strideb=<optimized out>, 
    res=0x64, n=100, tmp=0x60c038) at numpy/core/blasdot/_dotblas.c:101
#2  0x0000000c in ?? ()
```

Wanted to try decimate() and found that simply importing signal kills everything:

```
>>> from scipy import signal

Program received signal SIGILL, Illegal instruction.
dl_open_worker (a=<optimized out>) at dl-open.c:579
579	dl-open.c: No such file or directory.
(gdb) bt
#0  dl_open_worker (a=<optimized out>) at dl-open.c:579
#1  0xb6fe2744 in _dl_catch_error (objname=0xbeffdc4c, objname@entry=0xbeffdc6c, errstring=0xbeffdc50, 
    errstring@entry=0xbeffdc70, mallocedp=0xbeffdc4b, mallocedp@entry=0xbeffdc6b, operate=0xb6fe56f1 <dl_open_worker>, 
    args=0xbeffdc54, args@entry=0xbeffdc74) at dl-error.c:187
#2  0xb6fe5304 in _dl_open (file=<optimized out>, mode=-2147483646, caller_dlopen=0xc4017 <_PyImport_GetDynLoadFunc+206>, 
    nsid=<optimized out>, argc=1, argv=0xbefff574, env=0x3c2a20) at dl-open.c:663
#3  0xb6ea2abc in dlopen_doit (a=0xbeffdeb8) at dlopen.c:66
#4  0xb6fe2744 in _dl_catch_error (objname=0x2dd534, errstring=0x2dd538, mallocedp=0x2dd530, 
    operate=0xb6ea2a65 <dlopen_doit>, args=0xbeffdeb8) at dl-error.c:187
#5  0xb6ea2f18 in _dlerror_run (operate=0xb6ea2a65 <dlopen_doit>, args=args@entry=0xbeffdeb8) at dlerror.c:163
#6  0xb6ea2b4a in __dlopen (
    file=0x5b13c0 "/home/dgorissen/venvs/orangspy/local/lib/python2.7/site-packages/scipy/special/_ellip_harm_2.so", 
    mode=<optimized out>) at dlopen.c:87
#7  0x000c4016 in _PyImport_GetDynLoadFunc ()
#8  0x000c3a66 in _PyImport_LoadDynamicModule ()
#9  0x00054aca in ?? ()
```

```
~$ pip freeze
numpy==1.9.2
scipy==0.16.1
wheel==0.24.0
```

Exited the virtualenv, re-installed the python-numpy/scipy packages via apt and there I find that importing signal and calling decimate works. But guassian_kde fails with a different error:

```
>>> x = range(100)
>>> stats.gaussian_kde(x)

Program received signal SIGSEGV, Segmentation fault.
0xb65529c0 in damin_k () from /usr/lib/libopenblas.so.0
(gdb) bt
#0  0xb65529c0 in damin_k () from /usr/lib/libopenblas.so.0
#1  0xb65a5ab8 in dgetf2_k () from /usr/lib/libopenblas.so.0
#2  0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
Other than upgrading to 15.10 and hoping that works Im loss as to what else to try to get a working scipy environment..

**Comment by pv** [comment]
Looks like openblas issues.
Please reopen if you manage to reproduce them with refblas.

**Comment by dgorissen** [comment]
Thanks for the fast reply. Sorry for the stupid question but how would I try with the reference blas? I tried unsintalling the openblas ubuntu packages then creating a new venv and installing numpy. But then on import it complains with

ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

How do I tell it to use the reference blas?

**Comment by pv** [comment]
Uninstall libopenblas and install libblas via apt-get, and recompile/reinstall all packages you compiled yourself.

**Comment by dgorissen** [comment]
Its eaten up a whole day but that (removing openblas and reverting to standard blas) seems to have solved all my issues. Many thanks @pv.
