### ISSUE TITLE
1D root-finding interface and documentation could be improved

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#5481]
Currently on the reference guide for `scipy.optimize`:

```
brentq(f, a, b[, args, xtol, rtol, maxiter, ...])   Find a root of a function in given interval.
brenth(f, a, b[, args, xtol, rtol, maxiter, ...])   Find root of f in [a,b].
ridder(f, a, b[, args, xtol, rtol, maxiter, ...])   Find a root of a function in an interval.
bisect(f, a, b[, args, xtol, rtol, maxiter, ...])   Find root of a function within an interval.
newton(func, x0[, fprime, args, tol, ...])  Find a zero using the Newton-Raphson or secant method.
```

Uh?

Also, the docs for `brenth` say "Generally on a par with the brent routine" which I guess really meant `brentq`.

The docs of `brent{h,q}` and `bisect` refer to themselves in their `See also` section (haven't checked for others).

I would suggest providing a unified interface `root1d`, similar to `minimize` and `root`, although I'd favor returning a RootResult by default like `minimize` but unlike `root`.

**Comment by rgommers** [comment]
Or ``root_scalar``, like ``minimize_scalar``. Either way, I agree a unified interface here would be nice.

Link to the html docs showing the issue: http://docs.scipy.org/doc/scipy/reference/optimize.html#scalar-functions

**Comment by person142** [comment]
I wrote an interface; would it be appropriate to submit it as a WIP pull request for people to look at or should it be discussed on the mailing list first?

**Comment by sethtroisi** [comment]
#5504 was superseded by #8890 which added `scipy.optimize.root_scalar`
https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.root_scalar.html
