### ISSUE TITLE
minor 'iprint' documentation error in scipy.optimize.minimize L-BFGS-B

### ISSUE THREAD

**Issue by benureau** [scipy/scipy#5482]
The documentation of L-BFGS-B (http://docs.scipy.org/doc/scipy/reference/optimize.minimize-lbfgsb.html) lists `iprint` as an argument in the signature, but it is missing in the description of the arguments, probably replaced by the seemingly redundant `disp`, itself there twice under two different types (bool and int).

**Comment by rgommers** [comment]
Indeed. Also the order of documented items in the options dict doesn't match the signature on that html doc page.

**Comment by mbrubake** [comment]
The documentation here is still incorrect.  In fact, it looks like the iprint variable is actually completely ignored if disp is set.  This is documented in ``scipy/optimize/lbfgsb.py`` but I haven't verified that and the documentation should be propagated up to the userfacing side.  Also,  it would be nice if there was a way to print out the convergence information without getting the iteration info.  From what I can read that's actually not possible right now.

**Comment by andyfaff** [comment]
Added a PR to close this.

>  In fact, it looks like the iprint variable is actually completely ignored if disp is set. This is documented in scipy/optimize/lbfgsb.py 

This is correct. If disp is not None it overrides iprime.

**Comment by andyfaff** [comment]
Fixed in #10703
