### ISSUE TITLE
RootResults not mentioned in reference guide, and could use better __str__

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#5483]
RootResults should be mentioned in the reference guide (like OptimizationResult), and have a `__str__` like OptimizationResult.

**Comment by rgommers** [comment]
Agreed. It's very odd though that ``root`` itself returns an ``OptimizeResult`` and the various scalar root-finding methods a ``RootResult``.

**Comment by anntzer** [comment]
If there was no back-compatibility issues I would suggest returning the same OptimizeResult for all of these functions but I guess it's not going to happen...
(Also, for nitpicking, one may wonder why it's OptimizeResult but RootResults (plural).)

**Comment by mikofski** [comment]
related to #4204 which adds the docstring, but not the reference in the documentation
