### ISSUE TITLE
ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got ( -2135071796,)  in decomp_svd.py

### ISSUE THREAD

**Issue by wresch** [scipy/scipy#5489]
I maintain Anaconda python environments. For some of them I use stock anaconda numpy/scipy/scikit-learn (which is linked against lapack/atlas/cblas for numpy 1.9.2 and openblas for numpy 1.10), for others i compile myself against MKL with the intel compilers (2015.1.133). Only with the version compiled with icc/ifort against MKL do i get the following error:

```
Python 2.7.9 |Continuum Analytics, Inc.| (default, Apr 14 2015, 12:54:25)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import numpy as np
>>> from sklearn.decomposition import FastICA
>>> ncomps = 30
>>> rng = np.random.RandomState()
>>> a = np.random.random([28430, 26831])
>>> ica = FastICA(n_components=ncomps, random_state=rng)
>>> ICs = ica.fit_transform(a).T
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Anaconda/envs/py2.7.9/lib/python2.7/site-packages/sklearn/decomposition/fastica_.py"
, line 504, in fit_transform
    return self._fit(X, compute_sources=True)
  File "/usr/local/Anaconda/envs/py2.7.9/lib/python2.7/site-packages/sklearn/decomposition/fastica_.py"
, line 475, in _fit
    compute_sources=compute_sources, return_n_iter=True)
  File "/usr/local/Anaconda/envs/py2.7.9/lib/python2.7/site-packages/sklearn/decomposition/fastica_.py"
, line 302, in fastica
    u, d, _ = linalg.svd(X, full_matrices=False)
  File "/usr/local/Anaconda/envs/py2.7.9/lib/python2.7/site-packages/scipy/linalg/decomp_svd.py", line
106, in svd
    full_matrices=full_matrices, overwrite_a=overwrite_a)
ValueError: failed to create intent(cache|hide)|optional array-- must have defined dimensions but got (
-2135071796,)

>>> np.__config__.show()
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/Anaconda/envs/py2.7.9/lib/intel_mkl']
    define_macros = [('SCIPY_MKL_H', None)]
    include_dirs = ['/usr/local/Anaconda/envs/py2.7.9/include/intel_mkl']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/Anaconda/envs/py2.7.9/lib/intel_mkl']
    define_macros = [('SCIPY_MKL_H', None)]
    include_dirs = ['/usr/local/Anaconda/envs/py2.7.9/include/intel_mkl']
openblas_lapack_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/Anaconda/envs/py2.7.9/lib/intel_mkl']
    define_macros = [('SCIPY_MKL_H', None)]
    include_dirs = ['/usr/local/Anaconda/envs/py2.7.9/include/intel_mkl']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/Anaconda/envs/py2.7.9/lib/intel_mkl']
    define_macros = [('SCIPY_MKL_H', None)]
    include_dirs = ['/usr/local/Anaconda/envs/py2.7.9/include/intel_mkl']
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/usr/local/Anaconda/envs/py2.7.9/lib/intel_mkl']
    define_macros = [('SCIPY_MKL_H', None)]
    include_dirs = ['/usr/local/Anaconda/envs/py2.7.9/include/intel_mkl']
>>> import scipy
>>> scipy.__config__.show()                                              
lapack_opt_info:                                                         
    libraries = ['mkl_rt', 'pthread']                                    
    library_dirs = ['/usr/local/Anaconda/envs/py2.7.9/lib/intel_mkl']    
    define_macros = [('SCIPY_MKL_H', None)]                              
    include_dirs = ['/usr/local/Anaconda/envs/py2.7.9/include/intel_mkl']
blas_opt_info:                                                           
    libraries = ['mkl_rt', 'pthread']                                    
    library_dirs = ['/usr/local/Anaconda/envs/py2.7.9/lib/intel_mkl']    
    define_macros = [('SCIPY_MKL_H', None)]                              
    include_dirs = ['/usr/local/Anaconda/envs/py2.7.9/include/intel_mkl']
openblas_lapack_info:                                                    
  NOT AVAILABLE                                                          
lapack_mkl_info:                                                         
    libraries = ['mkl_rt', 'pthread']                                    
    library_dirs = ['/usr/local/Anaconda/envs/py2.7.9/lib/intel_mkl']    
    define_macros = [('SCIPY_MKL_H', None)]                              
    include_dirs = ['/usr/local/Anaconda/envs/py2.7.9/include/intel_mkl']
blas_mkl_info:                                                           
    libraries = ['mkl_rt', 'pthread']                                    
    library_dirs = ['/usr/local/Anaconda/envs/py2.7.9/lib/intel_mkl']    
    define_macros = [('SCIPY_MKL_H', None)]                              
    include_dirs = ['/usr/local/Anaconda/envs/py2.7.9/include/intel_mkl']
mkl_info:                                                                
    libraries = ['mkl_rt', 'pthread']                                    
    library_dirs = ['/usr/local/Anaconda/envs/py2.7.9/lib/intel_mkl']    
    define_macros = [('SCIPY_MKL_H', None)]                              
    include_dirs = ['/usr/local/Anaconda/envs/py2.7.9/include/intel_mkl']

>>>
```

Could there maybe be some implementation dependent 32 bit int overflow in the fortran code? There is no error when slighly decreasing the matrix size:

```
>>> import numpy as np
>>> from sklearn.decomposition import FastICA
>>> ncomps = 30
>>> rng = np.random.RandomState()
>>> a = np.random.random([28430, 26708])
>>> ica = FastICA(n_components=ncomps, random_state=rng)
>>> ICs = ica.fit_transform(a).T
```

works without issues

numpy: 1.9.2
scipy: 0.15.1 and 0.16.1

**Comment by pv** [comment]
The work array size required by LAPACK DGESDD for this matrix exceeds 32-bit signed integer range, so the problem cannot be solved by 32-bit MKL. Currently, 64-bit LAPACK is not supported (there's no standard interface, so cross-platform/cross-library/cross-compiler support is an issue).

**Comment by black-puppydog** [comment]
I have the same problem actually. I am not sure how to read your comment @pv. Do you mean it is unsupported and difficult or that it will flat-out not work?
I tried linking my numpy to mkl_intel_ilp64 before (and failed badly) and after reading this I am unsure if I should retry.

**Comment by wresch** [comment]
I was just about to try using ILP64 since https://software.intel.com/en-us/articles/numpyscipy-with-intel-mkl seems to indicate that this might be possible. But based on your comment (and the fact that the `-i8` flag which changes to ILP64 is commented out in the 1.9.3 sources (https://github.com/numpy/numpy/blob/v1.9.3/numpy/distutils/fcompiler/intel.py) it seems that this will not work.

**Comment by black-puppydog** [comment]
Oh, please don't base your expectations on my fail :D
I followed a lot of instructions, among which also [these](https://gehrcke.de/2014/02/building-numpy-and-scipy-with-intel-compilers-and-intel-mkl-on-a-64-bit-machine/), which (IMHO correctly) point out that the compiler classes are quite unorderly, with defaults being set in class attributes, then immediately overriden in `__init__` and all kinds of things like that.
I did manage to get numpy to compile against a regular `mkl_rt` but not against the ilp64 version, and I also didn't manage to use the intel compilers for it. I keep telling myself that it's just complicated and that that is also why it is so difficult to provide a working compilation framework out of the box. But it might very well just be my incompetence, too :P

**Comment by wresch** [comment]
OK, i actually managed to compile numpy/scipy with ILP64 with the intel compilers. numpy passes all tests and scipy has the same 3 failures that occur when not using ILP64 (they were reported elsewhere). However, the test from above still fails, so no cigar.

**Comment by pv** [comment]
Yes, there's no support for LAPACK64 currently --- it needs matching integer type changes in the wrapper routines, and these don't occur automatically, since there's no code to detect if it's lapack32 or 64. Moreover, the symbol names can be different (for openblas iirc depends on compilation options), which also would need adjustment.

All this is probably solvable --- what basically would need to be done is to write the part in the build system that detects 64-bit lapack / makes it configurable, potentially including symbol name changes. This is not so straightforward, since there's no very clear standard, afaik. Those interested to work on this should look into `numpy.distutils.system_info`, and look into how f2py selects integer types on C side. Then, make the necessary changes in `scipy/linalg/setup.py`.

The cython_blas/lapack however need to be still linked vs. default 32-bit lapack since it's in the api, but the f2py'd wrapper routines can be changed.

**Comment by wresch** [comment]
OK, thanks @pv. I'd say i can help, but I clearly don't know the innards of numpy/scipy well enough to even pretend...
