### ISSUE TITLE
deprecated lapack routines

### ISSUE THREAD

**Issue by jschueller** [scipy/scipy#5501]
In lapack 3.6.0 [1], these routines are deprecated:
CGEGS   CGEGV   CGELSX  CGEQPF  CGGSVD
CGGSVP  CLAHRD  CLATZM  CTZRQF
DGEGS   DGEGV   DGELSX  DGEQPF  DGGSVD
DGGSVP  DLAHRD  DLATZM  DTZRQF
SGEGS   SGEGV   SGELSX  SGEQPF  SGGSVD
SGGSVP  SLAHRD  SLATZM  STZRQF
ZGEGS   ZGEGV   ZGELSX  ZGEQPF  ZGGSVD
ZGGSVP  ZLAHRD  ZLATZM  ZTZRQF
It seems to me they are not used in the scipy context, I propose to remove their cython bindings.
[1] http://www.netlib.org/lapack/lapack-3.6.0.html

**Comment by pv** [comment]
duplicate gh-5266
