### ISSUE TITLE
args keyword not handled in optimize.curve_fit

### ISSUE THREAD

**Issue by shortda** [scipy/scipy#5502]
as far as I can tell, any time a user calls optimize.curve_fit with the args keyword they will receive the error 

```
TypeError: leastsq() got multiple values for keyword argument 'args'
```

There's an [old issue](https://github.com/scipy/scipy/issues/1940) dealing with the same error for the full_output keyword in curve_fit. The issue here is the same; the [docs](http://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.curve_fit.html#scipy.optimize.curve_fit) say additional keyword arguments like args should go straight to leastsq, but the curve_fit implementation passes an args keyword when it calls leastsq (line 555 in my minpack.py). If the user tries to use args then curve_fit will actually call leastsq with two args keywords.

**Comment by ev-br** [comment]
Can you please give a runnable example which demonstrates the problem?

**Comment by WarrenWeckesser** [comment]
I don't think `curve_fit` is designed to handle an `args` keyword.  It is not clear how `args` should be used.  The docstring of `curve_fit` says additional keyword arguments are passed on to the underlying solver.  If the solver gets the `args` keyword, it passes it on the function being fit.   But the function to be fit was created by `curve_fit`.   The parameters after the first argument of the user's function `f` become the first and only argument (as a vector) of the wrapper of `f` created by `curve_fit`.   The `args` argument does not fit in to that design.

Without a clear specification of how `args` *should* be handled, `curve_fit` should probably raise an error whose message clearly says that `args` is not accepted.

**Comment by mdhaber** [comment]
@guido-granda Do you mean that you want to use it like:

```
def func(x, a, b):
    return a * x + b

popt, pcov = sco.curve_fit(func, xdata, ydata, p0=[1], args=(1,))
```
that is, b is supposed to be fixed at a value of 1 and is supposed to be adjusted to fit the curve?

I think then you can simply create a new function or lambda function just before you call `curve_fit`, like:

```
def func(x, a, b):
    return a * x + b

b = 1
def func2(x, a):
    return func(x, a, b)
popt, pcov = sco.curve_fit(func, xdata, ydata, p0=[1])
```
Right?

**Comment by rgommers** [comment]
Changing this to _defect_, can be fixed by @WarrenWeckesser's suggestion:

> Without a clear specification of how args should be handled, `curve_fit` should probably raise an error whose message clearly says that `args` is not accepted.

**Comment by peytondmurray** [comment]
I'll point out that the `curve_fit` docstring specifies the accepted call signature of the fitting function:

> The model function, f(x, ...).  It must take the independent
>        variable as the first argument and the parameters to fit as
>        separate remaining arguments.

so by definition `f(x, ...)` should not accept any other arguments which are not fit parameters.

#10924 adds a check for `args` in the keyword arguments passed to `curve_fit` along with a test. Let me know if my implementation can be improved.
