### ISSUE TITLE
scipy.cluster.hierarchy.linkage() redundant distance matrix is mistreated 

### ISSUE THREAD

**Issue by Burning-Daylight** [scipy/scipy#5508]
Accordind to the documentation scipy.cluster.hierarchy.linkage() can take a redundant distance matrix as an input:
>y : ndarray
>    A condensed or redundant distance matrix. ...

In fact redundant matrix is treated as a collection of observation vectors.
Example code to reproduce the problem:

```python
import scipy.cluster as cluster
from scipy.spatial.distance import squareform

condensed=[1.0,2.0,3.0,1.5,2.7,0.15]
full=squareform(condensed)

Z_c=cluster.hierarchy.complete(condensed)
Z_f=cluster.hierarchy.complete(full)

print("distance matrix condensed: {}".format(condensed))
print("distance matrix full:\n{}".format(full))
print("Z condensed:\n{}".format(Z_c))
print("Z full:\n{}".format(Z_f))
```
gives:

>distance matrix condensed: [1.0, 2.0, 3.0, 1.5, 2.7, 0.15]
>distance matrix full:
>[[ 0.    1.    2.    3.  ]
>[ 1.    0.    1.5   2.7 ]
> [ 2.    1.5   0.    0.15]
> [ 3.    2.7   0.15  0.  ]]
>Z condensed:
>[[ 2.    3.    0.15  2.  ]
> [ 0.    1.    1.    2.  ]
> [ 4.    5.    3.    4.  ]]
> Z full:
> [[ 0.          1.          1.52970585  2.        ]
> [ 2.          3.          1.57638828  2.        ]
> [ 4.          5.          4.93077073  4.        ]]

**Comment by argriffing** [comment]
This reminds me of https://github.com/scipy/scipy/issues/2614. I'd thought a PR was merged to fix this, but I guess not.

**Comment by rgommers** [comment]
closed by gh-6342
