### ISSUE TITLE
Documentation for scipy.integrate.ode incorrectly labels set_jac_params

### ISSUE THREAD

**Issue by pgr** [scipy/scipy#5509]
Quick one - Under Parameters on:

http://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.integrate.ode.html#scipy.integrate.ode

Parameters: 
f : callable f(t, y, *f_args) [...] f_args is set by calling set_f_params(*args)
jac : callable jac(t, y, *jac_args) [...] jac_args is set by calling set_f_params(*args)

set_jac_params is presumably what is called to set the jacobian parameters.

**Comment by rgommers** [comment]
indeed looks like a typo.
