### ISSUE TITLE
Doc: find_peaks_swc

### ISSUE THREAD

**Issue by aolsux** [scipy/scipy#5510]
The documentation for `find_peaks_swc` wavelet parameter is wrong and/or misleading:
- the wavelet function needs to take two parameters, the number of points and the width (as does `ricker`).
- Why/how should it be normalized? Looking at `ricker(N,w).sum()`: The result depends on `N` and `m`. It is zero (not unity) if `N` is about `10*w`.

**Comment by rgommers** [comment]
Thanks for reporting this @aolsux. First point is easy to fix. I'm not sure about the normalization, that needs looking into.

**Comment by aolsux** [comment]
I tried to use a custom wavelet function and therefore, I have had a (short) look at the cited paper. Since the peaks that i wanted to find are not symmetric, I tried an asymmetric wavelet (A*t*exp(-gamma*t)) which was normalized to unity (`return y/y.sum()`). While the CWT matrices looked quite good for some of my tests, the ridge detection and filtering for those matrices was a complete mess. I ended up using the default ricker wavelet, which yielded best results.
I achieved some improvements with my own wavelet if i smoothed the cwt matrix before ridge detection with `scipy.ndimmage.gaussian_filter`. If interested, I think I could post some of the results here (If I find time :hourglass: ...).

**Comment by aolsux** [comment]
I also created a patch to fix it (partially). #5538

**Comment by rgommers** [comment]
Thanks for the PR. Posting the details of what you found here would be useful.

**Comment by aolsux** [comment]
Since the documentation thing is fixed, I'm closing this issue. If i find time i will reopen a new one related to the functionality of find_peaks.

**Comment by rgommers** [comment]
thanks @aolsux
