### ISSUE TITLE
scipy.stats.expon.rvs(scale=np.array([10.0, 10.0, 10.0]))  generate same values

### ISSUE THREAD

**Issue by colinfang** [scipy/scipy#5513]
```{python}
np.random.seed(1)
scipy.stats.expon.rvs(scale=np.array([10.0, 0.1, 10.0]))
array([ 5.39605837,  0.05396058,  5.39605837])
```

Notice the 1st and 3rd values are equal.

Is it made by design? I felt it is very unintuitive that `rvs` can generate fixed results.

**Comment by argriffing** [comment]
This reminds me of https://github.com/scipy/scipy/issues/2069.

**Comment by pv** [comment]
Looks like this is the same as that.
