### ISSUE TITLE
scipy.misc.comb(exact=True) does not follow documentation, can lead to errors

### ISSUE THREAD

**Issue by potash** [scipy/scipy#5529]
The documentation says that `comb(n,k,exact=True)` returns a `long` object. However, in practice, if the result fits in int, it returns the dtype that was passed. This easily leads to errors because, while `int*int` will be promoted to long when necessary, `int64*int64` will simply overflow. For example:

```python
> n,k = 50,25
> comb(n,k, exact=True)*comb(n,k, exact=True) # int*int
15979641419960227387050813504L
```

```python
> n,k = np.int64(50),np.int64(25)
> comb(n,k, exact=True)*comb(n,k, exact=True) # int64*int64
2822563473451378752
```

The easy solution is to do what the documentation says: if `exact==True` return long.

**Comment by pv** [comment]
That bug is not present in scipy >= 0.14.
