### ISSUE TITLE
Rename "do_compression" to "compress" 

### ISSUE THREAD

**Issue by rohanp** [scipy/scipy#5531]
Rename the "do_compression" named argument to "compress"  in [scipy.io.savemat](http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.io.savemat.html)

Renaming would make it more concise and the meaning would be unchanged.

**Comment by pv** [comment]
It's also a cosmetic change that breaks backwards compatibility, so the costs are probably more than benefits.
