### ISSUE TITLE
scipy-0.16.1 really slow on travis CI

### ISSUE THREAD

**Issue by kootenpv** [scipy/scipy#5532]
It's taking an insane amount of time to:

    Building wheels for collected packages: scipy, pandas, scikit-learn, deap, bitstring
     Running setup.py bdist_wheel for scipy

What could be wrong?

Specifically using this .travis.yml https://github.com/kootenpv/xtoy/blob/master/.travis.yml

With requirements.txt as:

    numpy
    scipy
    pandas
    scikit-learn>=0.17
    deap
    bitstring
    tox

**Comment by matthew-brett** [comment]
I guess you aren't using the pre-built wheels here : 

http://travis-wheels.scikit-image.org/

?  In that case, travis will have to build all these wheels from source, at least the first time you run, so it will take a loong time.

**Comment by pv** [comment]
Building from source takes time, so things seem to be working as intended.

**Comment by kootenpv** [comment]
Could you give me advice how I would install scipy using wheels for multiple python (27,33,34,35) while wanting to support the latest scipy? 
I'm probably not using the right terms to google.

**Comment by pv** [comment]
Here's one example: https://github.com/scikit-umfpack/scikit-umfpack/blob/master/.travis.yml

**Comment by pv** [comment]
Oh, you wanted wheels --- use `--trusted-host` and `--find-links` to specify the location in pip.

**Comment by kootenpv** [comment]
@pv Thanks a lot for your answer, but it still isn't really clear to me where I should put it to look for the links specific to the python versions and to the latest scipy?

**Comment by rgommers** [comment]
Easiest is to look at how other packages that depend on scipy do things. Here's a pip based solution:
https://github.com/nipy/nipy/blob/master/.travis.yml#L62
https://github.com/nipy/nipy/blob/master/tools/travis_tools.sh#L2
(wheels from http://travis-wheels.scikit-image.org/)

And here a conda based one:
https://github.com/statsmodels/statsmodels/blob/master/.travis.yml#L87
