### ISSUE TITLE
use OrderedDict in io.netcdf

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#5537]
See https://github.com/scipy/scipy/pull/5228#issuecomment-159407562. It's in the `pupynere.py` file in the given CVS link; can be easily synced to scipy.

**Comment by souravsingh** [comment]
I would like to help in this issue.How Do I do it?

**Comment by maniteja123** [comment]
It seems that this gh-5558 closes this. I found this when I was looking at the easy fix issues.
