### ISSUE TITLE
lstsq related test failures on windows binaries from numpy-vendor

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#5539]
I see circa 14 test failures which all look like this:

```
======================================================================
ERROR: test_simple_rows (test_basic.TestPinv)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\scipy\linalg\tests\test_basic.py", line 999, in test_simple_rows
    a_pinv = pinv(a)
  File "C:\Python27\lib\site-packages\scipy\linalg\basic.py", line 959, in pinv
    x, resids, rank, s = lstsq(a, b, cond=cond, check_finite=False)
  File "C:\Python27\lib\site-packages\scipy\linalg\basic.py", line 867, in lstsq
    raise LinAlgError("internal gelsd driver lwork query error,"
LinAlgError: internal gelsd driver lwork query error,required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Use a different lapack_driver when calling lstsq or upgrade LAPACK.
``` 

This is on a venerable Windows XP laptop with binaries built with numpy-vendor.

**Comment by rgommers** [comment]
Hmm, not good. This is with ATLAS 3.8.2, so the error message is probably misleading.

Do the tests pass if you change back to the old situation with ``lapack_driver=gelss``?

**Comment by rgommers** [comment]
I didn't see this on Wine, but maybe I haven't tested with a recent enough version of master. This was merged just last week IIRC.

**Comment by rgommers** [comment]
Ah, ignore that. ATLAS version != LAPACK version. ATLAS 3.8.2 is from 2007.

**Comment by ev-br** [comment]
Reran the tests on Wine too. The failures are still there, all 80-odd of them (lstsq is quite heavily used in scipy itself, it seems).

**Comment by pv** [comment]
`lstsq` should check for the issue on first call, and change the default value accordingly.
Only explicitly given `lapack_driver` argument should result to the error.
