### ISSUE TITLE
Could we add solve method as convenience function to IdentityOperator?

### ISSUE THREAD

**Issue by astudillor** [scipy/scipy#5544]
Just a  convenience function for compatibility class scipy.sparse.linalg.SuperLU.
I'm programming iterative method, then when a preconditioner is provided, this can be an object with a method solve(x), for example, scipy.sparse.linalg.spilu . When no preconditioner is given, I would  like to use the IdentityOperator class

**Comment by rgommers** [comment]
sorry this didn't get a reply earlier. `sparse.linalg.interface.IdentityOperator` does not have a `solve` method, but neither does `LinearOperator`.  `spilu` is a function not a class, so doesn't have a `solve` method either. 

the motivation seems a bit unclear, and I don't think this is desired. so I'll close this issue. thanks @astudillor
