### ISSUE TITLE
can't import numpy.distutils.core when I am trying to build my own package with scipy/numpy

### ISSUE THREAD

**Issue by esn89** [scipy/scipy#5552]
I have a setup.py which lists setup_requires=['numpy']
and in the install_requires=['numpy', 'scipy', 'other packages'].

I uploaded that onto my devpi server and when it came time to `pip install` the package, it kept saying that the wheel group for scipy won't build as it can't import 'numpy.distutils.core'. 

I thought all this time the whole point of setup_requires=['numpy'] was to ensure that numpy is installed and present during the installation of 'install_requires'.

Further reading shows that:  a similar issue has been reported and even a PR has been made, and merged:  https://github.com/scipy/scipy/pull/453

If it has been merged, how come scipy is still throwing this issue?

**Comment by pv** [comment]
Fixing this issue requires changes in pip. There's no way to specify build time dependencies in pip currently.  `setup_requires=['numpy']` is not useful here, because numpy needs to be installed before setup.py is run.

gh-453 is a workaround that helps if pip installs packages in dependency order, which only newer pip versions do systematically.

**Comment by esn89** [comment]
@pv 
So if I understand you correctly, and to confirm:

gh-453 has already been merged into master, BUT i will need to grab a newer version of pip to ensure that it follow the order of packaging?

**Comment by pv** [comment]
That's my understanding of the situation.

**Comment by esn89** [comment]
@pv btw, 

would it work if i built a binary wheel of numpy and then used that, that way, numpy wouldn't have to be built

**Comment by rgommers** [comment]
Installing numpy first would help; building a numpy wheel first probably does not. Not sure without something to try, but probably ``setup_requires='numpy'`` in scipy's setup.py would make this work. (not that that's ok to add right now)

**Comment by rgommers** [comment]
Since gh-5477 we're adding `setup_requires='numpy'` to all wheels, and IIRC we've had a couple of other fixes since then as well. So closing.
