### ISSUE TITLE
optimize.bisect does not acheive desired tolerance

### ISSUE THREAD

**Issue by person142** [scipy/scipy#5555]
The function `optimize.bisect` has a parameter for absolute tolerance `xtol` and a parameter for relative tolerance `rtol`. I would expect the computed root `res` and the exact root `r` to satisfy `abs(res - r) <= xtol + rtol*res`, but this is not the case:

```python
from scipy.optimize import bisect
from numpy import finfo

root = 0.1
def f(x):
    return x - root

xtol = 1e-12
rtol = 2*finfo(float).eps
res = bisect(f, -1e8, 1e8, xtol=xtol, rtol=rtol)
tol = xtol + rtol*res

print abs(res - root) <= tol
```
returns `False`. If in the above `bisect` is replaced by `brentq`, `brenth`, or `ridder` we get `True`. The issue is that the tolerance is set to be `tol = xtol + rtol*(fabs(xa) + fabs(xb))` for `xa`, `xb` the endpoints of the initial interval and then never changed throughout the routine, where it should be updated at each step with the current interval (as is done in the other methods). This means that if the endpoints of the initial interval are much larger than the root we lose accuracy.

Will submit a pull request soon with a proposed fix.

**Comment by ev-br** [comment]
Why closing this?

**Comment by person142** [comment]
I think the origin of the tolerance currently used in `bisect` is Press's "Numerical Recipies". The tolerance I was proposing is the tolerance used by Brent in his original paper on Brent's method (and more in the style of functions like `numpy.allclose`). It's worth noting that "Numerical Recipies" sticks with Brent's original method of defining the tolerance in their algorithm.

The point of all that was that it seems both methods of defining the tolerance are used. (Maybe worth noting that all of the functions `brentq`, `brenth`, `bisect`, and `ridder` could equally well be coded to use either one.) So it's not really fair to call this an *issue*, though admittedly I have a preference for Brent's version. It would probably be nice to document within `brentq`, `brenth`, `bisect`, and `ridder` what method is being used to compute the tolerance (IIRC they currently all say the same thing currently), but that's a different issue from what I was mentioning here.

**Comment by charris** [comment]
And here I was hoping for a fix ;) I think difference may have come about because bisect was already a python routine before the others were added. It was maybe fourteen years ago, so my memory is a bit dim. Anyway, reopening this.

**Comment by person142** [comment]
Ah, then I should probably reopen my pull request.
