### ISSUE TITLE
doc: scipy.stats.burr pdf issue

### ISSUE THREAD

**Issue by JKNA** [scipy/scipy#5560]
In doc, it is stated as 

    burr.pdf(x, c, d) = c * d * x**(-c-1) * (1+x**(-c))**(-d-1)

However, it has to be

    burr.pdf(x, c, d) = c * d * x**(c-1) * (1+x**(c))**(-d-1)

check: https://en.wikipedia.org/wiki/Burr_distribution

I haven't check the code implementation, but only the doc. Therefore, we should revise code if wrongly implemented.

**Comment by WarrenWeckesser** [comment]
@JKNA  Thanks for looking into this.  There are actually several different "Burr distributions"; see http://onlinelibrary.wiley.com/doi/10.1002/0471667196.ess0189.pub2/abstract.  By inspection of the table in the link, it is apparent that scipy implements the *Burr Type III* distribution, and you are expecting the Type XII distribution.

The `burr` docstring should mention that it implements the Type III distribution, so I added the "Documentation" label to this issue.

We should also add the Type XII distribution to scipy.

**Comment by JKNA** [comment]
@WarrenWeckesser Thanks for the remark and revision. Indeed it is Type III. I thought only the Type XII since it is familiar to me. (As far as I know, it is generally used.)

**Comment by JKNA** [comment]
@WarrenWeckesser Thanks for the comment and correction. Indeed it is that scipy implements Type III. I expected Type XII since that's familar to me. (As far as I know, Type XII is the generally used one.)

**Comment by WarrenWeckesser** [comment]
I created a pull request to include a note about `stats.burr` being the Type III Burr distribution: https://github.com/scipy/scipy/pull/5588

**Comment by WarrenWeckesser** [comment]
...and I created an issue with a request for an implementation of the Type XII distribution: https://github.com/scipy/scipy/issues/5589
