### ISSUE TITLE
mark some `least_squares` tests as slow 

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#5565]
Re-enabling tests for `least_squares` makes the `optimize` test run slower by almost a factor of three. Some tests can probably use too large problem sizes and some are likely best marked as `@slow`. 

cross-ref https://github.com/scipy/scipy/pull/5556

**Comment by andyfaff** [comment]
Looks like there are no disabled tests, or tests marked slow in `test_least_squares.py`. Can this issue be closed @ev-br?

**Comment by ev-br** [comment]
Yup, the runtime turned out to be tolerable after all :-).
