### ISSUE TITLE
inconsistent reporting of the number of evaluations in `least_squares`

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#5566]
Splitting it off from https://github.com/scipy/scipy/pull/5556#issuecomment-160415247
It seems that the way the number of function evaluations is reported (and capped) by least-squares routines is somewhat inconsistent: some count the evaluations spent estimating the derivatives as "function evaluations", some keep track of them separately. 

Consider: 

```
In [3]: def f(x):
   ...:     f.count += 1
   ...:     return x - 1.
   ...: 

In [4]: f.count = 0

In [5]: least_squares(f, np.array([5., 5.]))
Out[5]: 
 active_mask: array([ 0.,  0.])
        cost: 0.0
         fun: array([ 0.,  0.])
        grad: array([ 0.,  0.])
         jac: array([[ 1.,  0.],
       [ 0.,  1.]])
     message: '`gtol` termination condition is satisfied.'
        nfev: 2
        njev: 2
  optimality: 0.0
      status: 1
     success: True
           x: array([ 1.,  1.])

In [6]: f.count
Out[6]: 6
```

Naively, I'd expect that `nfev` is equivalent to f.count modulo maybe one or two evaluations during setup. 
Moreover, 

```
In [7]: f.count = 0

In [8]: least_squares(f, np.array([5., 5.]), method='lm')
Out[8]: 
 active_mask: array([0, 0])
        cost: 0.0
         fun: array([ 0.,  0.])
        grad: array([ 0.,  0.])
         jac: array([[ 1.,  0.],
       [ 0.,  1.]])
     message: '`xtol` termination condition is satisfied.'
        nfev: 7
        njev: None
  optimality: 0.0
      status: 3
     success: True
           x: array([ 1.,  1.])

In [9]: f.count
Out[9]: 14
```

These could probably be made consistent.

**Comment by andyfaff** [comment]
Naively I would expect `nfev == f.count`.

**Comment by nmayorov** [comment]
1. Regarding the first example: we discussed it at some point and decided to make `nfev` for new methods consistent between analytical and finite difference Jacobian (and with MATLAB). And I still prefer this decision. That is switching between analytical to fin. diff. Jacobian doesn't significantly change the number of `nfev` required for convergence.

2. Regarding the second example: there are extra evaluations in different places (computing Jacobian after MINPACK terminates is the main one), `nfev=7` comes from MINPACK directly (he counts them when estimating Jacobian, although seems like he returns one evaluation less).

The idea was to keep `nfev` as the measure of optimization method effectiveness (like iterations). It is theoretically possible to adjust / recompute values passed to MINPACK and returned from it, but it looks like unnecessary magic.

I would suggest to keep the things as they are now, but explain everything clearly in documentation of `max_nfev` parameter.

**Comment by rgommers** [comment]
sounds reasonable. @ev-br do you agree with @nmayorov's suggestion of updating the documentation of `max_nfev`?

**Comment by ev-br** [comment]
(totally forgot about it). Sure, let's keep the status quo.
