### ISSUE TITLE
lstsq test failure after lapack_driver change

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#5571]
From gh-5569: 

Note that the one TravisCI failure is ``FAIL: test_random_exact (test_basic.TestLstsq)`` (for ``driver=None``). Nothing should have changed there, TravisCI has a new enough ATLAS. So we'll need to look into that one.

Probably due to gh-5550.

**Comment by ev-br** [comment]
I'm inclined to jump bump the test tolerance, which is manipulated anyway.
