### ISSUE TITLE
Suspected underflow issue with sign check in bisection method

### ISSUE THREAD

**Issue by MarcoForte** [scipy/scipy#5584]
I believe there is a minor issue with the way in which it's checked whether variables have the same sign. 
Some instances of this issue appear in https://github.com/scipy/scipy/blob/master/scipy/optimize/Zeros/bisect.c
In particular the lines

``` c
 if (fa*fb > 0) {
        params->error_num = SIGNERR;
        return 0.;
    }
```

The problem arises when the values are small so multiplying them causes underflow to zero, 
the example below evaluates to false even though they both have the same sign. 10^{-162}*10^{-162} = 10^{-324} > 10^{-323} = the smallest double float above zero.

``` c
pow(10,-162)*pow(10,-162) > 0 /*= False/*
```

It can be resolved by using [signbit](http://en.cppreference.com/w/cpp/numeric/math/signbit)
and writing the below instead

``` c
 if (signbit(fa)==signbit(fb)) {
        params->error_num = SIGNERR;
        return 0.;
    }
```

**Comment by person142** [comment]
Possibly worth noting that `brentq`, `brenth`, and `ridder` will all have the same problem. (But also the same fix!)

**Comment by WarrenWeckesser** [comment]
Looks like a reasonable change, but in code such as this in `bisect.c`:

```
    if (fa*fb > 0) {
        params->error_num = SIGNERR;
        return 0.;
    }
    if (fa == 0) {
        return xa;
    }
    if (fb == 0) {
        return xb;
    }
```
the tests for `fa == 0` and `fb == 0` should made *before* the sign comparison `signbit(fa) == signbit(fb)`, otherwise a case such as `fa = 0.0` and `fb > 0` (or `fa = -0.0` and `fb < 0`, etc.) will result in a `SIGNERR`.

**Comment by ewmoore** [comment]
@MarcoForte, did you actually hit this?  AFAICT, this is more poor practice than a bug.  When underflow occurs the sign of zero is still correct. 
```
In [1]: from scipy import optimize as o

In [2]: o.bisect(lambda x: x, -1e-200, 1e-200, full_output=True)
Out[2]:
(0.0,       converged: True
            flag: 'converged'
  function_calls: 3
      iterations: 1
            root: 0.0)

In [3]: 1e-200 * -1e-200
Out[3]: -0.0

```
I don't see any problem changing the code though FWIW.

**Comment by ewmoore** [comment]
I suppose this probably requires IEEE floats, but I think lots of things probably become brittle in the scipy stack if you don't have them.

**Comment by mdhaber** [comment]
Re: https://github.com/scipy/scipy/issues/5584#issuecomment-188306551, yes, this bug is real. See tests in gh-17664; they fail without the patch.
