### ISSUE TITLE
scipy.signal.firwin2 does not normalize output properly

### ISSUE THREAD

**Issue by zer0hedge** [scipy/scipy#5585]
I believe the code below should return `numpy.ones(numtaps)` for any value of numtaps:

    numtaps=4
    signal.firwin2(numtaps, [0.0, np.finfo(float).eps, 1], [1.0, 0.0,0.0], window=None)

In fact, it doesn't. Furthermore, the output is rather mysteriously changing when you start incrementing `numtaps`.  

It appears, that in order to be correct the output needs to be multiplied by the `2*(nfreqs-1)` coefficient, where `nfreqs` is calculated as follows (taken from the source code of `firwin2`): 

    nfreqs = 1 + 2 ** int(ceil(np.log2(numtaps)))

Looking at the source code you can see that  output is essentially created by the line below in our case (i.e. there is no window):

      out_full = irfft(fx2)

According to the [Discrete Fourier Transform (numpy.fft)](http://docs.scipy.org/doc/numpy-1.10.0/reference/routines.fft.html#normalization), the output of `irfft` is scaled by 1/n or in our case,  by `2*(nfreqs-1)`.

So it seems that the line above in the source code need to be replaced by: 

      out_full = 2*(nfreqs-1)*irfft(fx2)

**Comment by WarrenWeckesser** [comment]
Before getting into any details, I'd like to understand what you are doing.  Your example attempts to create a low-pass filter with a gain of 1 at frequency 0, and a gain of 0 at a frequency of `np.finfo(float).eps`, with only 4 taps.  Is that really your goal?

Why do you expect the coefficients to be all 1s?  The filter with coefficients [1, 1, 1, 1] has a gain of *4* at frequency 0.

**Comment by zer0hedge** [comment]
I've created this example to illustrate the issue. Your example illustrates another issue with `firwin2` but there is an easy workaround for it.  So, to be precise, it is the rectangular window with 4 taps  gives gain of 4 at frequency 0. If you use another window (i.e. hamming)  you will get a different gain, so one more (apart from `2*(nfreqs-1)`) normalizaiton is actually needed. Otherwise, you will have to change `gain` parameter every time you change window. 

The workaround I mentioned is to do this 'window-related' normalizaiton outside of the `firwin2` code (i.e. just divide by `numtaps` in the above example to get the Moving Average filter). 

But `2*(nfreqs-1)` issue needs to fixed internally  since it is not clear from outside of 'firwin2'  how this coefficient is calculated within `firwin2`

**Comment by WarrenWeckesser** [comment]
Sorry, but I don't really understand what you think is wrong.  I *think* you might be misunderstanding the `window` argument and what `firwin2` computes.  `firwin2` does not return a window; it returns the coefficients of a FIR filter whose frequency response approximates the design given by the `freqs` and `gain` arguments.  The `window` which multiplies the "ideal" filter coefficients provides a way to control the trade-off between spectral leakage and the width of the central lobe in the frequency response.

**Comment by zer0hedge** [comment]
I believe that `firwin2` should  implement the math described for example in Chapter 7.2 Design of FIR Filters by Windowing  in "Discrete-Time Signal Processing" by A. Oppenheim. 'multiplication' of the "ideal" filter by window has a well-defined effect in the frequency domain (H_d  is the "ideal" filter frequency response, while H(e^(j\omega) is the response of the filter to be returned by `firwin2`):
![image](https://cloud.githubusercontent.com/assets/10581244/11615247/dcc8e67e-9c6c-11e5-84ed-a85077be1919.png)
My example demonstrates that `firwin2` does not work correctly even for the simple case.
One more example:
![image](https://cloud.githubusercontent.com/assets/10581244/11615302/1af7961a-9c6e-11e5-9ce5-54b379a87823.png)
Gain at 0 frequency is wrong
