### ISSUE TITLE
gammaln documentation is misleading

### ISSUE THREAD

**Issue by nmayorov** [scipy/scipy#5590]
The [claim](http://scipy.github.io/devdocs/generated/scipy.special.gammaln.html#scipy.special.gammaln) that `gammaln` computes "Logarithm of *absolute value* of gamma function" is not true:

```
>>> import numpy as np
>>> from scipy.special import gamma, gammaln
>>> z = 1 + 1j
>>> gammaln(z)
(-0.65092319930185738-0.30164032046753375j)
>>> np.log(np.abs(gamma(z)))
-0.65092319930185738
>>> np.log(gamma(z))
(-0.65092319930185749-0.30164032046753381j)
```

So `gammaln` actually computes `ln(gamma(z))` which is more useful than what it announces. Better to correct documentation, so it won't scare away people.

**Comment by WarrenWeckesser** [comment]
:+1: 

Note that the behavior of `gammaln` depends on whether the argument is complex or real:

```
In [36]: gammaln(-0.9)
Out[36]: 2.3580731673920328

In [37]: gammaln(-0.9 + 0j)
Out[37]: (2.3580731673920319-3.1415926535897931j)

In [38]: gammaln(-1)
Out[38]: inf

In [39]: gammaln(-1 + 0j)
Out[39]: (1.0000000000000001e+300+0j)
```

**Comment by WarrenWeckesser** [comment]
Note that the claim about the absolute value is true for *real* inputs:

```
In [29]: x = -2.3

In [30]: gammaln(x)
Out[30]: 0.3695666634550081

In [31]: np.log(np.abs(gamma(x)))
Out[31]: 0.3695666634550081

In [32]: np.log(gamma(x))
/Users/warren/anaconda/bin/ipython:1: RuntimeWarning: invalid value encountered in log
  #!/bin/bash /Users/warren/anaconda/bin/python.app
Out[32]: nan
```

**Comment by nmayorov** [comment]
That's a good investigation. Now it's clear what should be in the doc.
