### ISSUE TITLE
Documentation: Typo in doc for scipy.spatial.distance.squareform

### ISSUE THREAD

**Issue by EmperorDali** [scipy/scipy#5597]
There is a typo in the documentation for scipy.spatial.distance.squareform, available at

http://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.squareform.html

In Notes 2, the formula

v[{n choose 2}-{n-i choose 2} + (j-u-1)] 

is incorrect - the variable u should be an i. The correct formula appears in Notes 1.

**Comment by maniteja123** [comment]
I remember creating this PR #4634 to solve this issue.

**Comment by manipalsingh013** [comment]
@EmperorDali I have created a pull request for this #5771 
(can you tell me some issues to work on, I'm new here but I want to contribute)

**Comment by rgommers** [comment]
@maniteja123 your PR still needs work to address Jaime's comment it looks like. Maybe you want to finish it up?

**Comment by maniteja123** [comment]
@rgommers Really sorry that I kept it pending till now. I couldn't decide on what was the best documentation there and thus left it. It would be great if you could give your suggestions in the PR. Will wind it ASAP then.

**Comment by yash14123** [comment]
Would like to take this up. :)

**Comment by maniteja123** [comment]
Hi @yash14123 , there is a PR which is addressing the issue. I was waiting for some feedback there. If you don't mind, could you work on other easy fix issues. Thanks :)

**Comment by yash14123** [comment]
@maniteja123 No problems. It would be great if you try to provide a reference to the issue in your PR commit so others can know it is being worked on. Otherwise there was no way for me to understand that.
All the best ! :)

**Comment by maniteja123** [comment]
Actually there was an issue #4472 which was about the same issue. Sorry about the confusion.

**Comment by abhinuvpitale** [comment]
I think this issue can be closed.
