### ISSUE TITLE
sparse.linalg factorizations slow for small k due to default ncv value

### ISSUE THREAD

**Issue by jcmgray** [scipy/scipy#5612]
```eigs```, ```eigsh```, ```svds``` all default to using ```2 * k + 1``` for the number of lanczos vectors ```ncv```. This is fine for ```k > ~5``` or so but drastically slows the algorithm down for small ```k``` (e.g. k=2 or 1 slower than k=6!) and often means the convergence fails. The problem is worse for dense matrices (these sparse methods are actually very useful for dense matrices as well). 

The optimum value depends on ```n, k,```, the sparsity and other factors, but should generally should be ```>= 10```. Matlab apparently uses 20 as its minimum for equivalent functions but this might be a bit high for small sparse matrices. 

There might be a method of choosing ```ncv``` intelligently? But setting it to at minimum ```10``` would be a quick fix.

**Comment by amilsted** [comment]
As noted in my (duplicate) bug report (see above :), the current ncv default can also result in *wrong* results.
