### ISSUE TITLE
Solution for low accuracy of simps with even number of points

### ISSUE THREAD

**Issue by martijnzm** [scipy/scipy#5618]
# problem

The Simpson's rule is suitable for arrays with an odd number of points. The current implementation allows for even number of points by integration the first or last interval using the trapezium rule, which is highly inaccurate.
# solution

In case of an even number n points the integral over the first n-1 points can be calculated using the normal Simpson scheme, i.e. the weights are 1/12_(2, 8, 2) over all intervals of three points. To calculated the contribution of the last interval, the 2nd order polynomial fit over the last 3 points is integrated over the interval between the last 2 points. This results in a weight scheme of 1/24_[-1, 8, 5] for the last inverval.
# result

Accuracy with n+1 points is better than with n points, even if n+1 is even. This is demonstrated for int_0^pi sin(x) dx in the attached code.

[BetterSimps.txt](https://github.com/scipy/scipy/files/70330/BetterSimps.txt)

**Comment by rgommers** [comment]
Adding the code as comment here, with hard tabs fixed:

    from numpy import ones_like, zeros_like, array

    def Simpson(y, x):
        """ Calculate the integral of y(x) over x using the trapezium rule

        If the length of x and y is odd, the normal trapezium rule is used.
        I the even case the sub integral last interval is calculated using a 2nd order interpolation
        over the last three points. In this case the weights for the interval are then (-1, 8, -5)/12
        and for all others (2 8 2)/12 as for the normal Simpson's rule. The weight scheme for the total
        integral is then:
           [..., 2, 8, 2, 0, 0, 0], [..., 0, 0, 2, 8, 2, 0] + 1/2*[..., 0, 0, 0, -1, 8, 5] = [..., 4, 8, 4, 15/2, 6, 5/2]
        The coefficients can also be derived from the tailer polynomial around the the last but one
        data point with the first derivative calculated using the midpoint rule (df/dx = (f(x+dx)-f(x-dx))/2dx
        and the second using standard method (d2f/dx2 = (f(x+dx) - 2f(x) + f(x-dx))/dx**2
        """

        # x has to be equally spaced
        dx = x[1]-x[0]

        # index of the last odd point
        l = len(x)-1 if len(x)%2 == 1 else len(x)-2

        w = zeros_like(x)
        w[0], w[l] = 2, 2
        w[1:l:2] = 8
        w[2:l-1:2] = 4
        # Add the contriubtion of the last interval in case there is an even number of points
        if len(x) % 2 == 0:
            w[-3:] += array([-1.0, 8, 5])/2

        I = dx/6 * sum(w*y)
        return(I)


    if __name__ == "__main__":
        from numpy import linspace, pi, sin
        from scipy.integrate import simps
        print("%2s\t%12s\t%12s\t%12s\t%12s" % ("n", "I(numpy)", "Err(numpy)", "I(curr)", "Err(curr)"))
        for i in range(5, 13):
            t  = linspace(0, pi/2, i)
            I1 = simps(sin(t), t)
            I2 = Simpson(sin(t), t)
            print("%2i\t%12.7f\t%12.7f\t%12.7f\t%12.7f" % (i, I1, I1-1, I2, I2-1))

**Comment by rgommers** [comment]
@martijnzm you're very welcome to submit a pull request that improves ``integrate.simps``.

**Comment by martijnzm** [comment]
Do I need to retain the old behaviour for sake of compatibility? I suggest removing the trapezium rule related code and accept but ignore the "even" option.

**Comment by rgommers** [comment]
> Do I need to retain the old behaviour for sake of compatibility? I suggest removing the trapezium rule related code and accept but ignore the "even" option.

That makes sense to me - it then doesn't change the API, so no existing code will break.

> Is labelling this issue as defect not a little exaggerated? The current code works perfectly with an odd number of points and many users will know the limitations Simpsons rule.

``defect`` is not something dramatic - things are either a defect or an enhancement, and can be about small things. Looking at the awful docstring notes on ``even``, the clumsy API and the low accuracy, I think ``defect`` is the right label....

**Comment by mdhaber** [comment]
gh-9871 suggested a combination of the 1/3 and 3/8 rules, so I thought I'd bring that idea over here. I haven't looked into its merits.
