### ISSUE TITLE
Test: segmentation fault when testing `test_random_exact (test_basic.TestLstsq)`

### ISSUE THREAD

**Issue by FRidh** [scipy/scipy#5620]
A segmentation fault occurs when I try to run the test `test_random_exact (test_basic.TestLstsq)` on Nix/NixOS.
- happens with Python 2.7, 3.4 and 3.5
- numpy 1.10.2
- OpenBLAS 0.2.15

**Comment by ev-br** [comment]
Which scipy commit -- before or after https://github.com/scipy/scipy/pull/5550?
(Ideally, try the rc).
If the problem is present in the rc -- which svd driver segfaults? Does it still segfault if you take OpenBLAS out of the picture, does NixOS have ATLAS?

**Comment by FRidh** [comment]
Ah stupid me. Yes, this was with the RC.
I'll have a look if linking to Atlas is still possible.

**Comment by rgommers** [comment]
Just figured out that this test was run with different random numbers each time (see gh-5661). Is this segfault reproducible or did it just happen once?

**Comment by FRidh** [comment]
I just tested again (without gh-5661). It fails with OpenBlas, but passes with Atlas+Lapack

**Comment by ev-br** [comment]
So it looks like an OpenBlas issue then? In that case, I guess gh-5661 would be helpful in catching a test case for reporting it to OpenBlas.

**Comment by FRidh** [comment]
Unfortunately the segfault occurs also with rc2. Indeed, it seems OpenBlas related.

**Comment by FRidh** [comment]
For now we reverted back to openblas 0.2.14 on Nix. Since it seems openblas related I'm closing this.
