### ISSUE TITLE
Test for lstsq randomly failed

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#5629]
I believe [this](https://travis-ci.org/scipy/scipy/jobs/98746693) is just a random failure from having the tolerance too tight, and not due to [anything I did in fftpack](https://github.com/scipy/scipy/pull/4607):

```
======================================================================
FAIL: test_random_exact (test_basic.TestLstsq)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/scipy/scipy/build/testenv/lib/python2.6/site-packages/scipy/linalg/tests/test_basic.py", line 913, in test_random_exact
    err_msg="driver: %s" % lapack_driver)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/numpy/testing/utils.py", line 1168, in assert_allclose
    verbose=verbose, header=header)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/numpy/testing/utils.py", line 636, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=2.22045e-13, atol=2.22045e-13
driver: gelsd
(mismatch 100.0%)
 x: array([[ 0.43707672,  0.70677524,  0.22780903],
       [ 0.30783752,  0.00102895,  0.99964489],
       [ 0.38192615,  0.72402014,  0.12982997],...
 y: array([[ 0.43707672,  0.70677524,  0.22780903],
       [ 0.30783752,  0.00102895,  0.99964489],
       [ 0.38192615,  0.72402014,  0.12982997],...
```

I don't know the package enough to fix the tolerance.

**Comment by ev-br** [comment]
Does the base of your PR include https://github.com/scipy/scipy/pull/5572? Maybe rebase on master to see if it does the trick.

**Comment by endolith** [comment]
Yes it is already based on master

**Comment by endolith** [comment]
that PR changes the tolerance for line 907, but this is in line 913, if dtype is not np.float32

**Comment by endolith** [comment]
I modified nothing but a docstring and that build passed: https://travis-ci.org/scipy/scipy/builds/98929537

**Comment by rgommers** [comment]
Hmm, not quite clear what to bump the tolerances to unless this becomes a reproducible error. All PRs except this one seem to pass. The reported segfault in gh-5620 for the same test does point to a real issue here though.

**Comment by endolith** [comment]
Is there a way to run a test over and over again until it fails?

**Comment by rgommers** [comment]
You can run a single test with ``runtests.py``, but to run it over and over the easiest is probably to copy-paste it into a separate file and put it inside a for-loop.

**Comment by rgommers** [comment]
Here's the same failure again (from today, in another PR): https://travis-ci.org/scipy/scipy/jobs/99922506

**Comment by rgommers** [comment]
Found the issue, see gh-5661. I assume these occasional test failures were caused by near-singular matrices or something like that. It happened once for each test in many test runs, so let's not worry about it until something reproducible shows up.
