### ISSUE TITLE
Simple cubic spline interpolation?

### ISSUE THREAD

**Issue by nmayorov** [scipy/scipy#5637]
Hi!

How about adding a very simple cubic spline interpolator without concepts of B-splines, knots and so on?

Specifically I'm talking about piecewise cubic polynomials between given `x[i]` as described here https://en.wikiversity.org/wiki/Cubic_Spline_Interpolation and what provided in MATLAB http://www.mathworks.com/help/matlab/ref/spline.html

The idea is to put it in `Univariate interpolation` section as a counterpart to `PchipInterpolator` and `Akima1DInterpolator`. I think that a user would generally expect to find this simple interpolation algorithm here, but instead he gets quite complicated B-spline magic. 

I would be happy to work on the implementation too.

**Comment by sturlamolden** [comment]
Sounds like a good idea. I actually thought we had cubic splines. But if we don't, that clearly has to be remedied.

**Comment by nmayorov** [comment]
For clarification: you can get a cubic spline using [`InterpolatedUnivariateSpline`](http://scipy.github.io/devdocs/generated/scipy.interpolate.InterpolatedUnivariateSpline.html#scipy.interpolate.InterpolatedUnivariateSpline). But what it does is not what people usually learn about cubic splines. Questions I immediately had: 
1. Where are these coefficients of cubic polynomials for each segment?
2. What are knots? Why they don't match my `x[i]`?

Turned out that B-splines operate in quite a different way, which I'm sure has a lot of advantageous. But if you want to know the interpolating function between `x[i]` and `x[i+1]`  explicitly, you probably want to use standard cubic splines.

**Comment by charris** [comment]
B-Splines are good for fitting as they don't require continuity constraints, and for equally spaced points they have a nice Fourier transform (powers of sinc). However, for a simple interpolation through fixed sample points with cubics they may be overkill. The number of people who know about b-splines as opposed to "ordinary" splines is also significantly less, so in my experience there can be communication problems when b-splines are used... I'm happy with b-splines myself, but there may be room for simple cubic splines, or maybe a conversion from b-splines to piecewise polynomials of the traditionaly sort.

@nmayorov You probably need to explicitly specify the knots. IIRC, the software package scipy uses tries to choose optimum knot locations by default and can find itself in strange territory. Finding optimum knot locations is an open problem even today...

**Comment by sturlamolden** [comment]
Cubic splines are easy to understand and simple to use. Also IIRC they are easily fitted by solving a tridiagonal system, which we can do with LAPACK *gttrs subroutines.

**Comment by ev-br** [comment]
The functionality exists today in a form of `tck = splrep(x, Y, s=0); p = PPoly.from_spline(tck)`. The trick is to use s=0. Could it be any more obvious, right? :-). 

gh-3174 takes spline fitting out of the picture so that it's `spl= make_interp_spline(x, y)` gives you an object with knots and coefficients, and converting to the power basis, `p = PPoly.from_spline(spl), still works. There might be room for adding a special code path for make_interp_spline with knots at data points (tridiag linear system and all).

IMO, the functionality is there, but the exposure has lots to be desired.

**Comment by nmayorov** [comment]
@ev-br, I tried your recipe like this:

```
x = np.array([0, 1, 2, 3, 4], dtype=float)
y = np.array([0, 2, 3, -1, 10], dtype=float)
tck = splrep(x, y, s=0)
p = PPoly.from_spline(tck)
print(p.x)

[ 0.  0.  0.  0.  2.  4.  4.  4.  4.]
```

Well, again I'm very confused... 

I'm not saying that something is wrong in implementation of FITPACK's B-splines, but it is designed with a different goal in mind, and you need to be pretty involved in the topic to really get how it works and what it returns. 

So I still want to implement `CubicSplineInterpolator` for simple purposes.

**Comment by pv** [comment]
splrep runs adaptive knot selection, which is not what is usually expected. splmake might be more expected, but its implementation is not ok (full matrices), and `make_interp_spline` in gh-3174 is also more naive/predictable here iirc.

**Comment by ev-br** [comment]
Yes, it takes a while to get used to the fitpack representation (it surely did take me a while to).

[Shrug].

It might be fine to have a factory function creating a PPoly instance (or a PPoly subclass similar to Akima1DInterpolator,) which constructs the coefficients as an interpolating cubic spline directly in the piecewise polynomial basis. `linalg.solve_banded` handles tridiag systems from version 0.16 IIRC. 

If this is added, I) it should be very clearly documented as working in the pp basis, 2) some thought should be given upfront on handling boundary conditions. These should be transparent to users.

**Comment by ev-br** [comment]
Implemented in gh-5653, so closing. BTW Nikolay, do you know about this but if GH magic: https://help.github.com/articles/closing-issues-via-commit-messages/
