### ISSUE TITLE
finish up size 0 vector handling in cKDTree

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#5639]
Still todo after the merge of gh-5625: 

- remove ``converter.h``
- check if there's a test for size 0 input, and add one if it doesn't exist

**Comment by sturlamolden** [comment]
I can bullet proof the Cython code against size-0 arrays if you prefer. Three tiny changes are required. 

A test will mean trying the range query methods with ```r``` larger than the maximum distance between the kd-tree data and the query points.

**Comment by sturlamolden** [comment]
I will open a PR in an hour or so.

**Comment by rgommers** [comment]
sounds good to me

**Comment by sturlamolden** [comment]
PR posted

**Comment by rgommers** [comment]
Fixed in gh-5645, closing.
