### ISSUE TITLE
Scipy.stats.gamma.pdf is incorrect for x = 0

### ISSUE THREAD

**Issue by tewindavis** [scipy/scipy#5646]
I am using v 0.16.0 on a windows machine.

The support for the pdf of a gamma distribution is $x >0$.  For $x = 0$, gamma.pdf returns infinity.  This is inconsistent with the axioms of probability (at least to my knowledge).  

I would be happy to fix this, just give me the go ahead.

Best,
Tyler

**Comment by ev-br** [comment]
`pdf` is the probability *density*. Gamma pdf indeed has an integrable singularity at zero for k<1 (cf https://en.m.wikipedia.org/wiki/Gamma_distribution)

**Comment by tewindavis** [comment]
>*density*
Aha.  Great point.  Sorry to trouble you.

**Comment by ev-br** [comment]
No worries, we all have been there :-).
