### ISSUE TITLE
signal.freqresp should be more accurate for zpk or sos input

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#5648]
Currently `freqresp` uses `freqs` internally, so everything is internally converted to numerically unstable transfer functions.  It could be better-behaved for zpk input by processing the `h = polyval(b, s) / polyval(a, s)` part in second-order sections.

```
N = 127

b, a = butter(N, 100, analog=True)
w, h = freqs(b, a)
plot(w, 20*log10(abs(h)), label='ba freqs')

zpk = butter(N, 100, analog=True, output='zpk')
w, h = freqresp(zpk)
plot(w, 20*log10(abs(h)), label='zpk freqresp')

legend()
```

![bad butterworth](https://cloud.githubusercontent.com/assets/58611/12072755/9c375e04-b0be-11e5-963f-97387067ccdd.png)

zpk version should not have that bump at fc.

https://github.com/scipy/scipy/issues/3259#issuecomment-168352921

**Comment by endolith** [comment]
started to do this but it depends on analog zpk2sos https://github.com/scipy/scipy/issues/5668

**Comment by e-q** [comment]
For zpk, wouldn't it be easiest to do:

<img width="440" alt="zpk_freqresp" src="https://cloud.githubusercontent.com/assets/6894112/14407188/959078f2-fe74-11e5-891b-b517b9d2a279.png">

**Comment by endolith** [comment]
hmm good point.  the function just returns complex h, though, so there would be no magnitude or angle needed.

**Comment by rgommers** [comment]
Now that gh-6059 is merged, is the rest of this issue covered by gh-5668 or is there more?

**Comment by e-q** [comment]
@rgommers, yes I think so. I'll close this
