### ISSUE TITLE
Typo in documentation and confusing docstring

### ISSUE THREAD

**Issue by Nodraak** [scipy/scipy#5664]
[This line](https://github.com/scipy/scipy/blob/v0.16.1/scipy/signal/ltisys.py#L505) contains `H(s)=\sum_i b[i] s^i / \sum_j a[j] s^i` ([here](http://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.TransferFunction.html) is the doc). The power of the second `s` is inconsistent and I guess it should be a `j` and not an `i`.

-----

Moreover, the docstring state that :
> where `a` are elements of the numerator `num` and `b` are the elements of the denominator `den`.

IMO this is very confusing because scipy uses already `a` as the denominator and `b` as the numerator in a lot of functions, for exemple in [scipy.signal.butter()](https://github.com/scipy/scipy/blob/v0.16.1/scipy/signal/filter_design.py#L1853) ([here](http://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.butter.html) is the doc).

Therefore my proposal is to stick with `a` as the denominator and `b` as the numerator.

-----

Maybe I misunderstood otherwise I would be glad to make a Pull Request.

**Comment by endolith** [comment]
yes, the text isn't even consistent with itself because b is on the top of the fraction.

**Comment by endolith** [comment]
oh it's already been fixed.   see https://github.com/scipy/scipy/blob/master/scipy/signal/ltisys.py#L581 and http://scipy.github.io/devdocs/generated/scipy.signal.TransferFunction.html

**Comment by Nodraak** [comment]
You are right, I was looking at the docs and code from v0.16, my bad.
So nothing to do here, I close.
