### ISSUE TITLE
Need zpk2sos for analog filters

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#5668]
As described in https://github.com/scipy/scipy/pull/3717#issuecomment-142460019, zpk2sos does not work for analog filters since the coefficients of each stage are different.  

`b, a = butter(1, 1, analog=True)` produces b = [1], a = [1, 1]  → H(s) = 1/(s+1)

`sos = tf2sos(b, a)` produces `[1, 0, 0, 1, 1, 0]`

this stage is b = [1, 0, 0], a = [1, 1, 0] → H(s) = s^2/(s^2+s) = s/(s+1) which is not the same as above.  For digital filters, trailing zeros don't matter, but for analog filters, they do, and _leading_ zeros don't matter.  The correct result should be `[0, 0, 1, 0, 1, 1]`

So docstring should probably say it's not meant for analog at all for now?

and add analog=True to zpk2sos?

**Comment by endolith** [comment]
So I think it just needs to pair things in the S plane instead of Z plane (prioritize closeness to vertical axis rather than unit circle) and then produce positive powers tf instead of negative?

**Comment by jason-s** [comment]
Not sure that `zpk2sos` is the right place for continuous-time systems; the [MATLAB function `zp2sos`](http://www.mathworks.com/help/signal/ref/zp2sos.html) is meant only for discrete-time systems.

I would rather see this functionality in `zpk2ss` (see #5912)

**Comment by endolith** [comment]
Well matlab has 2 functions `tf2zpk` and `tf2zp`, but scipy's [`tf2zpk`](http://scipy.github.io/devdocs/generated/scipy.signal.tf2zpk.html) behaves like matlab's `tf2zp`, so consistency with matlab has never been there to begin with.  See https://github.com/scipy/scipy/pull/4872

Anyway, the functionality needs to be implemented, whether it's ultimately used in `zpk2sos` or `zpk2ss`.  I'd rather see it as an option in both.

**Comment by Eric89GXL** [comment]
Just a reminder that when we take care of this, then `bessel` filters (#5279) should be improved

**Comment by endolith** [comment]
@Eric89GXL That's no longer needed because of https://github.com/scipy/scipy/pull/6279#issuecomment-233497450

(zpk2sos for analog still is, though)
