### ISSUE TITLE
incorrect sign in convolve (from scipy.ndimage) doc

### ISSUE THREAD

**Issue by kolegram** [scipy/scipy#5671]
the formula provided in the doc of scipy.ndimage.convolve is
C_i = Sum_j I_{i+j-k} W_j. if k is the coordinate of the center of the kernel W, it should be written
C_i = Sum_j I_{i-j+k} W_j no ?

**Comment by person142** [comment]
Yep you're right, doing
```python
x = [0, 1, 0]
w = [0, 0, 1]
convolve(x, w, mode='constant')
```
gives ```[0, 0, 1]```, not ```[1, 0, 0]```. The relevant part of the code for the reflection is:

https://github.com/scipy/scipy/blob/v0.16.1/scipy/ndimage/filters.py#L532

**Comment by person142** [comment]
@rgommers or @ev-br: this issue was already fixed in master by 71c0f0, so it can be closed.

**Comment by ev-br** [comment]
Closing then. Thanks @person142
