### ISSUE TITLE
Residual Variance > 1.0 ?

### ISSUE THREAD

**Issue by wfbradley** [scipy/scipy#5674]
My understanding is that residual variance should always fall between 0.0 and 1.0 inclusive (see, e.g., [Fraction of Variance Unexplained](https://en.wikipedia.org/wiki/Fraction_of_variance_unexplained).  However, when I run orthogonal distance regression through SciPy, I sometimes find a residual variance >1.0; this produces negative R^2 values (!).

I have observed values around 1.1, which are too large for numerical precision to be the culprit.

I am including a minimal code snippet below; it produces random regressions, and in about 15-20% of the cases, the residual variance is greater than 1.0.

```
import numpy as np
import scipy.odr as odr

def tls_linear(B, x):
    return B[0]*x + B[1]

N=1000
tls_model = odr.Model(tls_linear)

print "Residual Variance > 1.0 ?"
for i in xrange(100):
    x=np.random.randn(N)
    y=np.random.randn(N)
    tls_data = odr.RealData(np.transpose(x), y)
    my_tls = odr.ODR(tls_data, tls_model, beta0=[1., 0.])
    tls_output = my_tls.run()
    res_var=tls_output.res_var
    if res_var>1.0:
        print '%d:  %f'%(i,res_var)
```

**Comment by wfbradley** [comment]
Ah, I see that I misunderstood the interpretation of ".res_var"; it is the sum of squares of the error divided by the degrees of freedom, which is >=0 but not necessarily <=1.

**Comment by rgommers** [comment]
No worries, thanks for following up on it.
