### ISSUE TITLE
fail on TestMultivariateCtypesQuad with numpy1.10.2 win32 on windows 7 64 bit

### ISSUE THREAD

**Issue by stonebig** [scipy/scipy#5675]
I notice this error (cgohlke wheels):

Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.

> > > import scipy;scipy.test()
> > > Running unit tests for scipy
> > > NumPy version 1.10.2
> > > NumPy relaxed strides checking option: False
> > > NumPy is installed in D:\WinPython\basedir34\buildQt5\winpython-3.4.4\python-3.4.4\lib\site-packages\numpy
> > > SciPy version 0.17.0rc1
> > > SciPy is installed in D:\WinPython\basedir34\buildQt5\winpython-3.4.4\python-3.4.4\lib\site-packages\scipy
> > > Python version 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]
> > > nose version 1.3.7

```
======================================================================
FAIL: test_improvement (test_quadpack.TestMultivariateCtypesQuad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\WinPython\basedir34\buildQt5\winpython-3.4.4\python-3.4.4\lib\site-packages\numpy\testing\decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "D:\WinPython\basedir34\buildQt5\winpython-3.4.4\python-3.4.4\lib\site-packages\scipy\integrate\tests\test_quadpack.py", line 134, in test_improvement
    assert_(fast < 0.5*slow, (fast, slow))
  File "D:\WinPython\basedir34\buildQt5\winpython-3.4.4\python-3.4.4\lib\site-packages\numpy\testing\utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError: (0.015599966049194336, 0.031199932098388672)

----------------------------------------------------------------------
Ran 20177 tests in 982.734s

FAILED (KNOWNFAIL=98, SKIP=1675, failures=1)
```

seems a follow-up of https://github.com/scipy/scipy/issues/4152 ?

**Comment by rgommers** [comment]
Is this failure repeatable? It's very borderline, ``fast`` is almost 2x faster than ``slow`` - maybe be should simply make the test run a bit longer to have less run-2-run variation.

**Comment by stonebig** [comment]
It's just a remark.
I suppose very few (if any) real user of this function are still on Win32.

**Comment by rgommers** [comment]
Well, it's been reported twice now, so I'd like to make the test a bit more robust. In this case I think the functionality is fine (using ``ctypes`` is almost twice as fast) but the test fails anyway.

**Comment by pv** [comment]
This was fixed.
