### ISSUE TITLE
Deprecate or discourage signal.step2 signal.impulse2 signal.lsim2

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#5676]
As described in comments:

https://github.com/scipy/scipy/issues/2652#issuecomment-21461674
https://github.com/scipy/scipy/pull/4675#issuecomment-96399789

The docstrings should at least say which functions are no longer recommended and how to replace them.

http://scipy.github.io/devdocs/generated/scipy.signal.step.html
http://scipy.github.io/devdocs/generated/scipy.signal.step2.html
http://scipy.github.io/devdocs/generated/scipy.signal.impulse.html
http://scipy.github.io/devdocs/generated/scipy.signal.impulse2.html
http://scipy.github.io/devdocs/generated/scipy.signal.lsim.html
http://scipy.github.io/devdocs/generated/scipy.signal.lsim2.html

**Comment by rgommers** [comment]
Agreed, makes sense to deprecate the ``*2`` functions. Needs proposing on the mailing list and doing for the next release I think.

**Comment by rgommers** [comment]
There's at least one issue with ``lsim`` not present in ``lsim2`` (gh-5886), so let's postpone this till after 0.18.0.

**Comment by h-vetinari** [comment]
Just stumbled over this after reflecting on the review in #15796 - currently `lsim` with non-uniform timesteps ([deprecated](https://github.com/scipy/scipy/issues/15755)) defers to `lsim2`. If we execute that deprecation, we'll have to point people to `lsim2`, which seems counter to what Ralf's [comment](https://github.com/scipy/scipy/pull/4675#issuecomment-96399789) was saying.

So should we rather:
* replace `lsim` with the logic of `lsim2` (with keeping but deprecating legacy behaviour where differences exist)
* deprecate `lsim2`

???

**Comment by h-vetinari** [comment]
@rgommers could you opine here?

**Comment by rgommers** [comment]
I think we want to update `lsim` to be the same as `lsim2` if there's still a difference, and then deprecate `lsim2`. Ending up with the better names is very much desirable.

**Comment by h-vetinari** [comment]
Thanks. I updated #15755 to reflect this

**Comment by h-vetinari** [comment]
This was fixed by #15929
