### ISSUE TITLE
BUG: Akima1DInterpolator may return nans given multidimensional input

### ISSUE THREAD

**Issue by nmayorov** [scipy/scipy#5683]
Here is an example:

```
import numpy as np
from scipy.interpolate import Akima1DInterpolator
x = np.array([0, 1, 2])
y = np.vstack((x, x**2)).T
ak = Akima1DInterpolator(x, y)
print(ak.c)

array([[[ nan,   0.],
        [ nan,   0.]],

       [[ nan,   1.],
        [ nan,   1.]],

       [[ nan,   0.],
        [ nan,   2.]],

       [[  0.,   0.],
        [  1.,   1.]]])
```

The algorithm needs to consider some cases separately (as with linear ramp in the example above), but the broadcasting for these cases is implemented somewhat incorrectly.

**Comment by ev-br** [comment]
fixed in gh-5684.

BTW @nmayorov this github feature is sometimes handy, https://help.github.com/articles/closing-issues-via-commit-messages/
