### ISSUE TITLE
No _sparsetool.py file exists under folder scipy/scipy/sparse/

### ISSUE THREAD

**Issue by Kriscoco** [scipy/scipy#5685]
Can't '''from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks...''' located on Line 13&14 in csr.py

**Comment by pv** [comment]
It is a compiled module.

**Comment by Kriscoco** [comment]
Aha~ Thank you pv, I thought it's a bug. But once I use the csr.py, it always encounter the following error: 
>from .csr import *
>File "D:\Python27\lib\site-packages\scipy\sparse\csr.py", line 13, in <module>
>from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
>ImportError: No module named _sparsetools

So, how can I fix it? Thanks a lot... I got stuck in it for the whole day.

**Comment by pv** [comment]
If you are just trying to install Scipy, please follow these instructions:
https://scipy.org/install.html
