### ISSUE TITLE
fftpack test failure in test_import

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#5694]
Reported by Derek Homeier on scipy-dev list (https://mail.scipy.org/pipermail/scipy-dev/2016-January/021173.html)

```
I found a single error trying to decode as ascii instead of unicode on running the tests for the
Python3 versions within the package build system, which occurs in general when LANG is not set,
or set to ‘C’ in the environment:

Running unit tests for scipy
NumPy version 1.10.4
NumPy relaxed strides checking option: False
NumPy is installed in /sw/lib/python3.5/site-packages/numpy
SciPy version 0.17.0rc2
SciPy is installed in /scratch.noindex/fink.build/root-scipy-py35-0.17.0rc2-1/sw/lib/python3.5/site-packages/scipy
Python version 3.5.1 (default, Jan  8 2016, 14:14:02) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
nose version 1.3.7
…
......................................................
======================================================================
ERROR: test_fftpack_import (test_import.TestFFTPackImport)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch.noindex/fink.build/root-scipy-py35-0.17.0rc2-1/sw/lib/python3.5/site-packages/scipy/fftpack/tests/test_import.py", line 29, in test_fftpack_import
    for line in file),
  File "/scratch.noindex/fink.build/root-scipy-py35-0.17.0rc2-1/sw/lib/python3.5/site-packages/scipy/fftpack/tests/test_import.py", line 28, in <genexpr>
    assert_(all(not re.fullmatch(regexp, line)
  File "/sw/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 351: ordinal not in range(128)

----------------------------------------------------------------------
Ran 20182 tests in 279.411s

FAILED (KNOWNFAIL=97, SKIP=1647, errors=1)
```

The test is here: https://github.com/scipy/scipy/blob/master/scipy/fftpack/tests/test_import.py,
it was added in https://github.com/scipy/scipy/pull/5295.

From  a cursory glance it seems that it's the test which needs fixing.

**Comment by dhomeier** [comment]
Probably, yes. Looks like it is barfing on the first utf-8 encoded file it opens (here `scipy/io/__init__.py`) when it has to match a line with non-ascii characters. So I guess one needs to tell `re` to always use a utf-8 compatible encoding (assuming all non-ascii source files are using some kind of utf-8) instead of taking the default from the environment.
Ideally, I suppose the encoding would be set individually for each file by first parsing its header string...

**Comment by dhomeier** [comment]
Ah, it actually seems to be already the opening that's failing. So changing that to
```
    with path.open(encoding="utf-8") as file:
```
"fixes" the issue. Just wondering now how one is supposed to use the encoding string in the file to open it with the right encoding...

**Comment by ev-br** [comment]
I wonder if we could just paper over the root cause

```
$ git diff test_import.py
diff --git a/scipy/fftpack/tests/test_import.py b/scipy/fftpack/tests/test_import.py
index 7562ca6..bd85993 100644
--- a/scipy/fftpack/tests/test_import.py
+++ b/scipy/fftpack/tests/test_import.py
@@ -24,10 +24,19 @@ if sys.version_info >= (3, 4):
             for path in base.rglob("*.py"):
                 if base / "fftpack" in path.parents:
                     continue
-                with path.open() as file:
-                    assert_(all(not re.fullmatch(regexp, line)
-                                for line in file),
-                            "{0} contains an import from fftpack".format(path))
+                try:
+                    with path.open() as file:
+                        assert_(all(not re.fullmatch(regexp, line)
+                                    for line in file),
+                                "{0} contains an import from fftpack".format(path))
+                except UnicodeDecodeError:
+                    # gosh darn
+                    with path.open(encoding="utf-8") as file:
+                        assert_(all(not re.fullmatch(regexp, line)
+                                    for line in file),
+                                "{0} contains an import from fftpack".format(path))
```

**Comment by matthew-brett** [comment]
Sorry to be dumb - but don't we know the encoding of all these files in the test directory?  Or, more specifically, is it not true to say that we can assume that all the files are UTF-8 (or ASCII)?

**Comment by dhomeier** [comment]
Yes, I had thought about implementing a `try:` as well, but in either case we have to assume anything that's not ASCII is UTF-8 (or indefinitely extend the `try`s), and it feels to me like testing for the exception will be rather costlier than opening everything as UTF-8 right away (if there is any penalty at all to the latter).

As a matter of fact, all source files I could find with an encoding specified are
```
./scipy/io/__init__.py:# -*- encoding:utf-8 -*-
./tools/authors.py:# -*- encoding:utf-8 -*-
./tools/gh_lists.py:# -*- encoding:utf-8 -*-
```
and the ones in `tools` don't go into the library (at least they are not in `Path(scipy.__file__).parent`).

**Comment by ev-br** [comment]
@dhomeier Does removing the encoding shebang from `io/__init__.py` fix the issue on your machine? If it does, please send a PR :-).

Author lists need to use Unicode, but the rest of the code base does not (AFAICS we don't use it anywhere and this issue is the first one we had so far).

**Comment by dhomeier** [comment]
With just removing the header line it raises the error on reading the guilty characters (which are the trademark ®s of MATLAB and IDL, so it's all evil proprietary software's fault ;-).
I don't know if there is a general scipy rule against using non-ASCII text in the Python source; otherwise you'd perhaps have to discuss with the persons in charge of `io` (@matthew-brett, any comments?) if it's worth just putting literal `(R)`s in there.
Personally I find it reasonable to treat all files as UTF-8, if in doubt (there might always come up the occasion of including personal names or other non-ASCII strings).

**Comment by matthew-brett** [comment]
No objection from me for removing the trademark characters - but UTF-8 seems pretty reasonable as a default.

**Comment by ev-br** [comment]
> Yes, I had thought about implementing a try: as well, but in either case we have to assume anything that's not ASCII is UTF-8 (or indefinitely extend the trys), and it feels to me like testing for the exception will be rather costlier 

In general, I don't think we should worry too much about optimum performance *in tests* (unless there is an actual pressing need, that is). In this particular case: The try branch is essentially cost-free. The except branch is going to be only used once as your analysis shows. Thus I don't believe there is a need to worry about performance. 

Either way, I don't have a preference of whether to remove three characters from `io.__init__` or to add five lines to a test (two of which should be comments :-)). Would you be interested in implementing either of these @dhomeier ? Otherwise I'd do it, does not matter to me.

**Comment by dhomeier** [comment]
Just had in mind that @rgommers had already reported the original test to be somewhat slow, but it the `try:` does not cost anything, all the better. I'd go for modifying the test then, because

1. whichever solution we pick, the convention would have to be communicated to everyone to make absolutely sure this does not happen in the future - i.e. either no python files with non-ASCII encoded are allowed in the scipy source tree at all, or `.py` files should always be opened with UTF-8 encoding (or at least when plain ASCII fails).

2. this would most closely reproduce the previous behaviour in all environments with a UTF-8 `LANG` setting.

**Comment by anntzer** [comment]
For info, the "proper" way to open a source taking the encoding modeline into account is https://docs.python.org/3/library/tokenize.html?highlight=encoding#tokenize.detect_encoding
I guess I should have known that.

**Comment by dhomeier** [comment]
Good to know. So
```
   with tokenize.open(path.as_posix()) as file:
```
fixes it as well. I am only worried how the `path.as_posix()` will behave on Windows - `tokenize.open()` only accepts a file name, not a `PosixPath` object, but perhaps `str(path)` would be the better way to go?

**Comment by anntzer** [comment]
You should just call `str(path)` (https://docs.python.org/3/library/pathlib.html#operators).

**Comment by dhomeier** [comment]
Of course,
Simple is better than complex.

**Comment by ev-br** [comment]
fixed in gh-5720, closing
