### ISSUE TITLE
Upgrade installation error of scipy-0.16.1

### ISSUE THREAD

**Issue by aewhatley** [scipy/scipy#5698]
When I try to upgrade my version of scipy to 0.16.1, I get a long and cryptic error message. I am running Python 3.5 (Anaconda) on Windows.

C:\Users\Alexander>pip install --upgrade scipy
Collecting scipy
  Using cached scipy-0.16.1.tar.gz
Building wheels for collected packages: scipy
  Running setup.py bdist_wheel for scipy
  Complete output from command C:\Users\Alexander\Anaconda3\python.exe -c "impor
t setuptools;__file__='C:\\Users\\ALEXAN~1\\AppData\\Local\\Temp\\pip-build-pp9v
m9ac\\scipy\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'),
 __file__, 'exec'))" bdist_wheel -d C:\Users\ALEXAN~1\AppData\Local\Temp\tmpfkgc
xviqpip-wheel-:
  lapack_opt_info:
  openblas_lapack_info:
    libraries openblas not found in ['C:\\Users\\Alexander\\Anaconda3\\lib', 'C:
\\', 'C:\\Users\\Alexander\\Anaconda3\\libs']
    NOT AVAILABLE

  lapack_mkl_info:
  mkl_info:
    libraries mkl,vml,guide not found in ['C:\\Users\\Alexander\\Anaconda3\\lib'
, 'C:\\', 'C:\\Users\\Alexander\\Anaconda3\\libs']
    NOT AVAILABLE

    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas,tatlas not found in C:\Users\Alexander\Anaconda3\lib
    libraries lapack_atlas not found in C:\Users\Alexander\Anaconda3\lib
    libraries tatlas,tatlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries tatlas,tatlas not found in C:\Users\Alexander\Anaconda3\libs
    libraries lapack_atlas not found in C:\Users\Alexander\Anaconda3\libs
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
    libraries satlas,satlas not found in C:\Users\Alexander\Anaconda3\lib
    libraries lapack_atlas not found in C:\Users\Alexander\Anaconda3\lib
    libraries satlas,satlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries satlas,satlas not found in C:\Users\Alexander\Anaconda3\libs
    libraries lapack_atlas not found in C:\Users\Alexander\Anaconda3\libs
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\Alexander\Anaconda3\
lib
    libraries lapack_atlas not found in C:\Users\Alexander\Anaconda3\lib
    libraries ptf77blas,ptcblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\Alexander\Anaconda3\
libs
    libraries lapack_atlas not found in C:\Users\Alexander\Anaconda3\libs
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
    libraries f77blas,cblas,atlas not found in C:\Users\Alexander\Anaconda3\lib
    libraries lapack_atlas not found in C:\Users\Alexander\Anaconda3\lib
    libraries f77blas,cblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries f77blas,cblas,atlas not found in C:\Users\Alexander\Anaconda3\libs

    libraries lapack_atlas not found in C:\Users\Alexander\Anaconda3\libs
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  lapack_info:
    libraries lapack not found in ['C:\\Users\\Alexander\\Anaconda3\\lib', 'C:\\
', 'C:\\Users\\Alexander\\Anaconda3\\libs']
    NOT AVAILABLE

  lapack_src_info:
    NOT AVAILABLE

    NOT AVAILABLE

  C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\system_info.py:
1552: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    warnings.warn(AtlasNotFoundError.__doc__)
  C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\system_info.py:
1563: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    warnings.warn(LapackNotFoundError.__doc__)
  C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\system_info.py:
1566: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    warnings.warn(LapackSrcNotFoundError.__doc__)
  Running from scipy source directory.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\ALEXAN~1\AppData\Local\Temp\pip-build-pp9vm9ac\scipy\setup.py
", line 253, in <module>
      setup_package()
    File "C:\Users\ALEXAN~1\AppData\Local\Temp\pip-build-pp9vm9ac\scipy\setup.py
", line 250, in setup_package
      setup(**metadata)
    File "C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\core.py
", line 135, in setup
      config = configuration()
    File "C:\Users\ALEXAN~1\AppData\Local\Temp\pip-build-pp9vm9ac\scipy\setup.py
", line 175, in configuration
      config.add_subpackage('scipy')
    File "C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\misc_ut
il.py", line 1002, in add_subpackage
      caller_level = 2)
    File "C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\misc_ut
il.py", line 971, in get_subpackage
      caller_level = caller_level + 1)
    File "C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\misc_ut
il.py", line 908, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\setup.py", line 15, in configuration
      config.add_subpackage('linalg')
    File "C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\misc_ut
il.py", line 1002, in add_subpackage
      caller_level = 2)
    File "C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\misc_ut
il.py", line 971, in get_subpackage
      caller_level = caller_level + 1)
    File "C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\misc_ut
il.py", line 908, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\linalg\setup.py", line 20, in configuration
      raise NotFoundError('no lapack/blas resources found')
  numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

  ----------------------------------------
  Failed building wheel for scipy
Failed to build scipy
Installing collected packages: scipy
  Found existing installation: scipy 0.16.0
    Uninstalling scipy-0.16.0:
      Successfully uninstalled scipy-0.16.0
  Running setup.py install for scipy
    Complete output from command C:\Users\Alexander\Anaconda3\python.exe -c "imp
ort setuptools, tokenize;__file__='C:\\Users\\ALEXAN~1\\AppData\\Local\\Temp\\pi
p-build-pp9vm9ac\\scipy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(
__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\
Users\ALEXAN~1\AppData\Local\Temp\pip-v7e801m3-record\install-record.txt --singl
e-version-externally-managed --compile:
    lapack_opt_info:
    openblas_lapack_info:
      libraries openblas not found in ['C:\\Users\\Alexander\\Anaconda3\\lib', '
C:\\', 'C:\\Users\\Alexander\\Anaconda3\\libs']
      NOT AVAILABLE

    lapack_mkl_info:
    mkl_info:
      libraries mkl,vml,guide not found in ['C:\\Users\\Alexander\\Anaconda3\\li
b', 'C:\\', 'C:\\Users\\Alexander\\Anaconda3\\libs']
      NOT AVAILABLE

      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas,tatlas not found in C:\Users\Alexander\Anaconda3\lib
      libraries lapack_atlas not found in C:\Users\Alexander\Anaconda3\lib
      libraries tatlas,tatlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries tatlas,tatlas not found in C:\Users\Alexander\Anaconda3\libs
      libraries lapack_atlas not found in C:\Users\Alexander\Anaconda3\libs
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries satlas,satlas not found in C:\Users\Alexander\Anaconda3\lib
      libraries lapack_atlas not found in C:\Users\Alexander\Anaconda3\lib
      libraries satlas,satlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries satlas,satlas not found in C:\Users\Alexander\Anaconda3\libs
      libraries lapack_atlas not found in C:\Users\Alexander\Anaconda3\libs
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in C:\Users\Alexander\Anaconda
3\lib
      libraries lapack_atlas not found in C:\Users\Alexander\Anaconda3\lib
      libraries ptf77blas,ptcblas,atlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries ptf77blas,ptcblas,atlas not found in C:\Users\Alexander\Anaconda
3\libs
      libraries lapack_atlas not found in C:\Users\Alexander\Anaconda3\libs
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries f77blas,cblas,atlas not found in C:\Users\Alexander\Anaconda3\li
b
      libraries lapack_atlas not found in C:\Users\Alexander\Anaconda3\lib
      libraries f77blas,cblas,atlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries f77blas,cblas,atlas not found in C:\Users\Alexander\Anaconda3\li
bs
      libraries lapack_atlas not found in C:\Users\Alexander\Anaconda3\libs
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    lapack_info:
      libraries lapack not found in ['C:\\Users\\Alexander\\Anaconda3\\lib', 'C:
\\', 'C:\\Users\\Alexander\\Anaconda3\\libs']
      NOT AVAILABLE

    lapack_src_info:
      NOT AVAILABLE

      NOT AVAILABLE

    C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\system_info.p
y:1552: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\system_info.p
y:1563: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      warnings.warn(LapackNotFoundError.__doc__)
    C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\system_info.p
y:1566: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      warnings.warn(LapackSrcNotFoundError.__doc__)
    Running from scipy source directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ALEXAN~1\AppData\Local\Temp\pip-build-pp9vm9ac\scipy\setup.
py", line 253, in <module>
        setup_package()
      File "C:\Users\ALEXAN~1\AppData\Local\Temp\pip-build-pp9vm9ac\scipy\setup.
py", line 250, in setup_package
        setup(**metadata)
      File "C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\core.
py", line 135, in setup
        config = configuration()
      File "C:\Users\ALEXAN~1\AppData\Local\Temp\pip-build-pp9vm9ac\scipy\setup.
py", line 175, in configuration
        config.add_subpackage('scipy')
      File "C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\misc_
util.py", line 1002, in add_subpackage
        caller_level = 2)
      File "C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\misc_
util.py", line 971, in get_subpackage
        caller_level = caller_level + 1)
      File "C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\misc_
util.py", line 908, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\misc_
util.py", line 1002, in add_subpackage
        caller_level = 2)
      File "C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\misc_
util.py", line 971, in get_subpackage
        caller_level = caller_level + 1)
      File "C:\Users\Alexander\Anaconda3\lib\site-packages\numpy\distutils\misc_
util.py", line 908, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

    ----------------------------------------
  Rolling back uninstall of scipy
Command "C:\Users\Alexander\Anaconda3\python.exe -c "import setuptools, tokenize
;__file__='C:\\Users\\ALEXAN~1\\AppData\\Local\\Temp\\pip-build-pp9vm9ac\\scipy\
\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace
('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\ALEXAN~1\AppData\L
ocal\Temp\pip-v7e801m3-record\install-record.txt --single-version-externally-man
aged --compile" failed with error code 1 in C:\Users\ALEXAN~1\AppData\Local\Temp
\pip-build-pp9vm9ac\scipy

**Comment by rgommers** [comment]
The issue is given away by this line:

    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

To build scipy from source, you need to have BLAS/LAPACK installed (including dev headers). Note that on Windows installing from source is quite hard, and unless you know what you're doing I would not try it. If you want to try anyway: Intel MKL + Intel compilers is your best bet.
