### ISSUE TITLE
bounds API differ between least_squares and minimize

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#5700]
Both the already existing `optimize.minimize` and the soon-to-be-released `optimize.least_squares` can take a `bounds` argument (for bounded minimization).  `minimize` takes a sequence of `(min, max)` pairs corresponding to each variable (and uses `None` for no bound -- actually `np.inf` also works, but triggers the use of a bounded algorithm), whereas `least_squares` takes a pair of sequences, resp. the mins and the maxs for each variable (and uses `np.inf` for no bound).

It would be nice to keep the same API in both cases, which would mean using a sequence of `(min, max)` pairs in `least_squares` (I actually prefer `np.inf` rather than `None` for no bound so I won't argue on that part).

I apologize for bringing up yet another (relatively minor) issues so close to the release.  Unfortunately, it seems difficult to catch these before the release (I stumbled on `least_squares` somewhat by accident and I'm sure it's mostly unknown right now), and after the release there are backwards compatibility issues.  I wonder if a Provisional API mechanism would be suitable?

PS: In any case, this function works great and has already been quite helpful in my work.  Thanks!

@nmayorov @ev-br

**Comment by nmayorov** [comment]
First, I'm very glad that `least_squares` was helpful to you! (Maybe you can share examples of usage?)

This question of bounds API did arise previously. Admittedly I made this choice mostly by myself. I had 2 things in mind.

1.  Let `lb=[-1, -2]` and `ub=[2, 5] `. Now one can specify bounds in 4 different ways:
```
1. bounds = (lb, ub)
2. bounds = (-np.inf, ub) (can be a finite number instead of inf)
3. bounds = (lb, np.inf)
4. bounds = (0, 10)
```
All of them are logical and consistent with each other (and all cases are clearly covered in the documentation).

If we change it to `minimize'` style:
```
1. bounds = zip(lb, ub)
2. bounds = (-np.inf, ub)
3. bounds = (lb, np.inf)
4. bounds = (0, 10)
```
While 1 and 4 are fine, 2 and 3 are not really consistent and may be confusing, but on the other case they are useful. I also admit that case 1 feels slightly more intuitive (for me at least) when done in `minimize'` style.
2. I really didn't like `None`, it doesn't fit into "array style" of doing things in numpy/scipy.

So I decided to abandon API compatibility and make a version which I think is generally better. I realize this is a questionable decision. 

More opinions on this issue are welcome.

**Comment by anntzer** [comment]
I think you meant, for minimize's style:
1. zip(lb, ub)
2. zip(repeat(-np.inf), ub)
3. zip(lb, repeat(np.inf))
4. [(0, 10)] * nparams
I actually didn't notice that you implementation allows scalar bounds to be broadcasted (I guess I didn't even think about this possibility), it's certainly a plus.
I'll defer to your judgment or @ev-br's.  Feel free to close the issue.

**Comment by nmayorov** [comment]
I was a bit unclear. I meant that if we want to allow the same convenient broadcasting with `minimize'` style, then we can implement these options literally as I wrote, it looks possible with some quirky logic.

**Comment by larsmans** [comment]
If I were to design an API for bounds-constrained optimization from scratch, I would use the pair-of-sequences API too. It matches NumPy broadcasting conventions.

**Comment by nmayorov** [comment]
Suggest to close it. API is now settled and generally approved by several people.

**Comment by anntzer** [comment]
Agreed.
