### ISSUE TITLE
scipy.optimize.linprog result is with negative sign when maximizing

### ISSUE THREAD

**Issue by niekas** [scipy/scipy#5711]
When I try to maximize, the result (fun) value is with negative sign, though ```x``` values are correct.
Here is maximization problem example: http://www.phpsimplex.com/simplex/page2.php?o=max&x1=30&x2=25&rt=3&v=2&l=en&r1_1=2&r1_2=1&d1=-1&y1=40&r2_1=1&r2_2=3&d2=-1&y2=45&r3_1=1&r3_2=&d3=-1&y3=12&Submit=Continue Its:

```
max f(x,y) = 30x + 25y
subject to:
2x + 1y <= 40
1x + 3y <= 45
1x + 0y <= 12
x, y >= 0
```
Since I am maximizing: 
```
>>> c = [-30, -25]
>>> A = [[2, 1], [1, 3], [1, 0]]
>>> b = [40, 45, 12]
>>> bounds = [(0, None), (0, None)]
>>> res = linprog(c, A_ub=A, b_ub=b, bounds=bounds, options={"disp": True})
Optimization terminated successfully.
         Current function value: -635.000000 
         Iterations: 2
>>> print(res)
  status: 0
   slack: array([ 5.,  0.,  0.])
 success: True
     fun: -635.0
       x: array([ 12.,  11.])
 message: 'Optimization terminated successfully.'
     nit: 2
```

The online solver states that solution is: 635, but the scipy.optimize.linprog solver returns solution -635. Why the result is with negative sign, when maximizing?

**Comment by argriffing** [comment]
You're looking for X that maximizes f(X), and you've correctly reformulated the problem as looking for X that minimizes g(X) = -f(X). The linprog solver is reporting X and g(X). If you want f(X), you have to take the negative of the g(X) value that linprog reports.

**Comment by niekas** [comment]
Sorry my bad.
