### ISSUE TITLE
Segfault when running scipy.linalg tests

### ISSUE THREAD

**Issue by jjakeman** [scipy/scipy#5712]
When I run
python -c "import scipy.linalg as m; m.test('full', verbose=3)"
a segfault occurs. There also seems to be a problem in other tests which print messages like

0-th dimension must be fixed to 3 but got 15

I get the following print out

Running unit tests for scipy.linalg
NumPy version 1.10.2
NumPy relaxed strides checking option: False
NumPy is installed in /home/jdjakem/python-virtual-env/2.7/lib/python2.7/site-packages/numpy
SciPy version 0.16.1
SciPy is installed in /home/jdjakem/python-virtual-env/2.7/lib/python2.7/site-packages/scipy
Python version 2.7.3 (default, Jan 24 2013, 14:20:14) [GCC 4.4.6 20120305 (Red Hat 4.4.6-4)]
nose version 1.3.6
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
nose.config: INFO: Excluding tests matching ['f2py_ext', 'f2py_f90_ext', 'gen_ext', 'pyrex_ext', 'swig_ext']
test_check_finite (test_basic.TestDet) ... ok
test_random (test_basic.TestDet) ... ok
test_random_complex (test_basic.TestDet) ... ok
test_simple (test_basic.TestDet) ... ok
test_simple_complex (test_basic.TestDet) ... ok
test_check_finite (test_basic.TestInv) ... ok
test_random (test_basic.TestInv) ... ok
test_random_complex (test_basic.TestInv) ... ok
test_simple (test_basic.TestInv) ... ok
test_simple_complex (test_basic.TestInv) ... ok
test_check_finite (test_basic.TestLstsq) ... ok
test_random_complex_exact (test_basic.TestLstsq) ... ok
test_random_complex_overdet (test_basic.TestLstsq) ... ok
test_random_exact (test_basic.TestLstsq) ... ok
test_random_overdet (test_basic.TestLstsq) ... ok
test_random_overdet_large (test_basic.TestLstsq) ... ok
test_simple_exact (test_basic.TestLstsq) ... ok
test_simple_overdet (test_basic.TestLstsq) ... ok
test_simple_overdet_complex (test_basic.TestLstsq) ... ok
test_simple_underdet (test_basic.TestLstsq) ... ok
test_basic.TestMatrixNorms.test_matrix_norms ... ERROR
test_basic.TestOverwrite.test_det ... ok
test_basic.TestOverwrite.test_inv ... ok
test_basic.TestOverwrite.test_lstsq ... ok
test_basic.TestOverwrite.test_pinv ... ok
test_basic.TestOverwrite.test_pinv2 ... ok
test_basic.TestOverwrite.test_pinvh ... ok
test_basic.TestOverwrite.test_solve ... ok
test_basic.TestOverwrite.test_solve_banded ... ok
test_basic.TestOverwrite.test_solve_triangular ... ok
test_basic.TestOverwrite.test_solveh_banded ... ok
test_check_finite (test_basic.TestPinv) ... ok
test_simple_cols (test_basic.TestPinv) ... ok
test_simple_complex (test_basic.TestPinv) ... ok
test_simple_real (test_basic.TestPinv) ... ok
test_simple_rows (test_basic.TestPinv) ... ok
test_simple_singular (test_basic.TestPinv) ... ok
test_nonpositive (test_basic.TestPinvSymmetric) ... ok
test_simple_complex (test_basic.TestPinvSymmetric) ... ok
test_simple_real (test_basic.TestPinvSymmetric) ... ok
test_20Feb04_bug (test_basic.TestSolve) ... ok
test_check_finite (test_basic.TestSolve) ... ok
test_nils_20Feb04 (test_basic.TestSolve) ... ok
test_random (test_basic.TestSolve) ... ok
test_random_complex (test_basic.TestSolve) ... ok
test_random_sym (test_basic.TestSolve) ... ok
test_random_sym_complex (test_basic.TestSolve) ... ok
test_simple (test_basic.TestSolve) ... ok
test_simple_complex (test_basic.TestSolve) ... ok
test_simple_sym (test_basic.TestSolve) ... ok
test_simple_sym_complex (test_basic.TestSolve) ... ok
test_1x1 (test_basic.TestSolveBanded) ... ok
test_bad_shape (test_basic.TestSolveBanded) ... ok
test_check_finite (test_basic.TestSolveBanded) ... ok
test_complex (test_basic.TestSolveBanded) ... ok
test_real (test_basic.TestSolveBanded) ... ok
test_tridiag_complex (test_basic.TestSolveBanded) ... ok
test_tridiag_real (test_basic.TestSolveBanded) ... ok
test_axis_args (test_basic.TestSolveCirculant) ... ok
test_basic1 (test_basic.TestSolveCirculant) ... ok
test_basic2 (test_basic.TestSolveCirculant) ... ok
test_basic3 (test_basic.TestSolveCirculant) ... ok
test_complex (test_basic.TestSolveCirculant) ... ok
test_random_b_and_c (test_basic.TestSolveCirculant) ... ok
test_singular (test_basic.TestSolveCirculant) ... ok
test_01_complex (test_basic.TestSolveHBanded) ... ok
test_01_float32 (test_basic.TestSolveHBanded) ... ok
test_01_lower (test_basic.TestSolveHBanded) ... ok
test_01_upper (test_basic.TestSolveHBanded) ... ok
test_02_complex (test_basic.TestSolveHBanded) ... ok
test_02_float32 (test_basic.TestSolveHBanded) ... ok
test_02_lower (test_basic.TestSolveHBanded) ... ok
test_02_upper (test_basic.TestSolveHBanded) ... ok
test_03_upper (test_basic.TestSolveHBanded) ... ok
test_1x1 (test_basic.TestSolveHBanded) ... ok
test_bad_shapes (test_basic.TestSolveHBanded) ... ok
test_check_finite (test_basic.TestSolveHBanded) ... ok
test_tridiag_01_complex (test_basic.TestSolveHBanded) ... ok
test_tridiag_01_float32 (test_basic.TestSolveHBanded) ... ok
test_tridiag_01_lower (test_basic.TestSolveHBanded) ... ok
test_tridiag_01_upper (test_basic.TestSolveHBanded) ... ok
test_tridiag_02_complex (test_basic.TestSolveHBanded) ... ok
test_tridiag_02_float32 (test_basic.TestSolveHBanded) ... ok
test_tridiag_02_lower (test_basic.TestSolveHBanded) ... ok
test_tridiag_02_upper (test_basic.TestSolveHBanded) ... ok
test_tridiag_03_upper (test_basic.TestSolveHBanded) ... ok
solve_triangular on a simple 2x2 matrix. ... ok
solve_triangular on a simple 2x2 matrix. ... ok
solve_triangular on a simple 2x2 complex matrix ... ok
test_basic.TestVectorNorms.test_overflow ... FAIL
test_basic.TestVectorNorms.test_stable ... FAIL
test_basic.TestVectorNorms.test_types ... FAIL
test_basic.TestVectorNorms.test_zero_norm ... ok
test_summ_wrong_side (test_blas.TestBLAS3Symm) ... ok
test_symm (test_blas.TestBLAS3Symm) ... ok
SYMM only considers the upper/lower part of A. Hence setting ... ok
test_syr2k (test_blas.TestBLAS3Syr2k) ... ok
test_syr2k_wrong_c (test_blas.TestBLAS3Syr2k) ... 0-th dimension must be fixed to 3 but got 15
ok
test_syrk (test_blas.TestBLAS3Syrk) ... ok
test_syrk_wrong_c (test_blas.TestBLAS3Syrk) ... 0-th dimension must be fixed to 3 but got 5
ok
test_axpy (test_blas.TestCBLAS1Simple) ... ok
test_amax (test_blas.TestFBLAS1Simple) ... ok
test_asum (test_blas.TestFBLAS1Simple) ... FAIL
test_axpy (test_blas.TestFBLAS1Simple) ... ok
test_complex_dotc (test_blas.TestFBLAS1Simple) ... Segmentation fault (core dumped)

**Comment by rgommers** [comment]
Hi @jjakeman, can you please tell us how you installed scipy, what compilers (C and Fortran) you used and what BLAS/LAPACK you're using?

**Comment by jjakeman** [comment]
Hi Ralf,
Thank you for your speedy reply. After submitting the ticket I reinstall Numpy and then Scipy making note of what compilers were used. However in doing so the error disappeared and my tests now pass. I consider this issue resolved.

Thanks again 
John

**Comment by argriffing** [comment]
This probably does not address the sporadic errors in this issue, but does LAPACK use an RNG internally for some functions? I'm pretty sure that ARPACK does, but I'm not sure about BLAS/LAPACK. If so, can its seed be controlled by numpy/scipy?

**Comment by pv** [comment]
LAPACK at least has RNG cf. slarnv et al., but I don't think there's
internal state the few routines using them seem to use a fixed seed.
(Since there are no SAVE variables, where would the rng state even be
stored? *lacon seem to be the only place with save variables, but I
don't see it using the rng.)
