### ISSUE TITLE
scipy.linalg.eig produces uncontrollably inconsistent results

### ISSUE THREAD

**Issue by bramson** [scipy/scipy#5714]
Left eigenvectors found from scipy.linalg.eig differ significantly from computer to computer and from run to run.  (Running example can be found here: http://stackoverflow.com/questions/34744342/preventing-scipy-eigenvectors-differing-from-computer-to-computer)  This is probably (as far as I can tell) due to the random seed used by LAPACK, but there is no way (I can find) to specify that seed so that the output from scipy.linalg.eig is consistent. It would be great if you could add a parameter to set that and/or make the results of the function's eigenvector finder not sensitive to which computer it is run on and when it is run.

**Comment by rgommers** [comment]
This isn't (easily) possible nor needed. The returned eigenvectors can depend on platform, LAPACK version, etc. Your application should not depend on the returned values, only on the property that they're eigenvectors.
