### ISSUE TITLE
pip-compile does not show numpy as requirement

### ISSUE THREAD

**Issue by cancan101** [scipy/scipy#5715]
Because of how [`build_requires` is determined](https://github.com/scipy/scipy/blob/4b654371f1aaa9799b8592aadcd3fb130cb31300/setup.py#L204-L213), `pip-compile` does not see `numpy` as a requirement of `scipy`.

**Comment by taion** [comment]
It's not just `pip-compile`. If you do `pip install scikit-learn` in a fresh virtualenv, when a wheel is available, you end up with an install that has `scikit-learn` but not `numpy` or `scipy`.

**Comment by taion** [comment]
Similarly, on OS X, if I try to `pip install scipy` in a fresh virtualenv, I end up with only `scipy` installed, but not `numpy`.

**Comment by perimosocordiae** [comment]
This was a conscious decision. See [this comment](https://github.com/scipy/scipy/issues/5184#issuecomment-135120996) for more details.

**Comment by taion** [comment]
What do you think of using e.g. `extras_require` to make a `scipy[pip]` package that unconditionally lists `numpy` as a dependency? This would provide a better experience for users on a standard virtualenv/requirements toolchain for setting up environments.

**Comment by rgommers** [comment]
As long as the very basic ``build_requires`` isn't even implemented by ``pip``, and the ``--upgrade`` behavior remains completely wrong (the ``pip-compile`` guys also [just ran into this](https://github.com/nvie/pip-tools/issues/290)), I think it would be a bad idea to use even more experimental features like extras.

**Comment by rgommers** [comment]
I never heard of ``pip-compile`` before, and I guess I'm not the only one. It's one of the two commands provided by https://github.com/nvie/pip-tools

**Comment by rgommers** [comment]
This should be in our FAQ by now, but: using ``build_requires`` unconditionally depends on ``pip`` changing its upgrade behavior: https://github.com/pypa/pip/issues/59#issuecomment-166681643

**Comment by rgommers** [comment]
So closing as wontfix for now.
