### ISSUE TITLE
scipy.odr doesn't return any error/warning if empty input

### ISSUE THREAD

**Issue by erwanp** [scipy/scipy#5721]
In the code below, scipy.odr is run on an empty data set. 

```
from scipy.odr import Model, RealData, ODR

def f(B, x):
    '''Linear function y = m*x + b'''
    return B[0]*x + B[1]

linear = Model(f)
dat = RealData([], [])
odr_fit = ODR(dat, linear, beta0=[0.02, 0.0])
out = odr_fit.run()   # should trigger some kind of warnings
out.pprint()
```
I expected the function to return an error, or at least a warning. Instead, `out.beta` returns the initial conditions.  I can't think of any case where this can be a wanted behaviour. `out.pprint()` does print that the convergence reason is `N < 1`, but it requires carefully reading the `out.pprint()` argument each time (in any kind of batch processing this isn't possible)  

As a general suggestion, Is it possible to have an easy way access to the convergence status (`out.converged = True/False`) ?

(I'm currently parsing the `out.stopreason` variable looking for Convergence but something more obvious could be helpful)

**Comment by gfyoung** [comment]
Based on the information you would get from this <a href="https://github.com/scipy/scipy/blob/81c096001974f0b5efe29ec83b54f725cc681540/scipy/odr/odrpack.py#L89-L164">method here</a>, what do you define as `convergence` exactly?
