### ISSUE TITLE
Limits of quad integration in scipy with np.inf

### ISSUE THREAD

**Issue by yuriShafet** [scipy/scipy#5735]
Code:
```
from scipy.integrate import quad
import numpy as np
from scipy.stats import norm

def integrand(x):
    return x*norm.pdf(x, 800, 1)
print quad(integrand, norm.ppf(0.05, 800,1), norm.ppf(0.95, 800,1))
print quad(integrand, -np.inf, np.inf)

(719.9999999999894, 5.913323331834147e-11)
(0.0, 0.0) 
```
Is this normal Behavior? 

By the way, when mean is small( for example 2) , it works fine - both integrals results are very close.

**Comment by josef-pkt** [comment]
I don't know what's "normal", but this is a known behavior. (I ran into it a few times.)
It's like finding a needle in an infinite haystack. 
The default search sees mostly the range with values equal to zero and does not find out that the function has the bump around 800.

Either we need to specify the bounds, or translate the bump to be around zero (e.g. x - 800). I don't know if integrate quad has other tricks if we use non-default options or keywords

**Comment by ewmoore** [comment]
Is this normal behavior?  Well, its not unexpected.  How is `quad` to know that your function is only nonzero for a small range of `x` values around 800 when you've told it that the entire real line counts?  When integrating over the full line quadpack splits around 0, so when the mean is small this allows it to find some nonzero values to integrate.  When the mean is large this fails. If you really must use infinite bounds, you can try shifting your integrand back toward 0.
```
integrate.quad(lambda x: stats.norm.pdf(x+800, 800, 1)*(x+800), -np.inf, np.inf)
Out[28]: (800.0000000000018, 8.142559425784547e-06)
```
But if you know enough about the function you are integrating to do this, you probably know enough to pick a better set of bounds in the first place.

The calculation you're trying to do is usually written `stats.norm.mean(800, 1)`.

**Comment by ewmoore** [comment]
Closing as there isn't anything actionable here.
