### ISSUE TITLE
BUG: *syrk functions ignore overwrite option

### ISSUE THREAD

**Issue by jakirkham** [scipy/scipy#5738]
There seems to be an overwrite option that doesn't work for these functions. Example below

    >>> import numpy as np
    >>> from scipy.linalg import blas
    >>> a = np.random.random((100,100))
    >>> c = np.zeros((100,100))
    >>> blas.dsyrk(1.0, a, c=c, overwrite_c=True)
    array([[ 33.19339651,  24.12943429,  26.71785963, ...,  24.73044741,
             22.97901315,  22.99444606],
           [  0.        ,  32.83715648,  24.07729365, ...,  24.73987735,
             23.78197391,  21.39989852],
           [  0.        ,   0.        ,  37.33024914, ...,  26.96535023,
             24.00661787,  22.97043113],
           ..., 
           [  0.        ,   0.        ,   0.        , ...,  35.66241571,
             23.48535436,  22.59825865],
           [  0.        ,   0.        ,   0.        , ...,   0.        ,
             30.79795771,  21.66025167],
           [  0.        ,   0.        ,   0.        , ...,   0.        ,
              0.        ,  28.62412903]])
    >>> c
    array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
           [ 0.,  0.,  0., ...,  0.,  0.,  0.],
           [ 0.,  0.,  0., ...,  0.,  0.,  0.],
           ..., 
           [ 0.,  0.,  0., ...,  0.,  0.,  0.],
           [ 0.,  0.,  0., ...,  0.,  0.,  0.],
           [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

**Comment by pv** [comment]
Generally, the overwrite options mean that the input array may be overwritten, not that they are guaranteed to be.

The functions always return the result arrays.

**Comment by ewmoore** [comment]
FWIW, the overwrite option requires that c be fortran ordered.  So
```
In [150]: a = np.random.random((5,5))

In [151]: c = np.zeros((5,5))

In [152]: linalg.blas.dsyrk(1.0, a, c=c.T, overwrite_c=True)
Out[152]: 
array([[ 1.584339  ,  0.93694834,  0.77466281,  1.29040001,  2.10473892],
       [ 0.        ,  1.01464741,  1.00492064,  1.03302596,  1.74079086],
       [ 0.        ,  0.        ,  1.07764925,  0.90634314,  1.72147965],
       [ 0.        ,  0.        ,  0.        ,  1.32449458,  1.94092007],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  3.57297992]])

In [153]: c
Out[153]: 
array([[ 1.584339  ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.93694834,  1.01464741,  0.        ,  0.        ,  0.        ],
       [ 0.77466281,  1.00492064,  1.07764925,  0.        ,  0.        ],
       [ 1.29040001,  1.03302596,  0.90634314,  1.32449458,  0.        ],
       [ 2.10473892,  1.74079086,  1.72147965,  1.94092007,  3.57297992]])
```
Works just fine.  This is true for essentially anything that uses f2py to wrap fortran code.

**Comment by jakirkham** [comment]
Ok, so then I probably did something wrong. However, it would help if this could be documented. ( http://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.blas.dsyrk.html#scipy.linalg.blas.dsyrk )

**Comment by jakirkham** [comment]
Also, a warning could be generated if the order is wrong. I'd just like to get a clue as to what I am doing wrong.

**Comment by pv** [comment]
Those are wishlist items for f2py (resides in numpy).

The documentation issue can maybe be resolved by adding general comments on this page:
https://docs.scipy.org/doc/scipy/reference/linalg.blas.html

**Comment by jakirkham** [comment]
Could you please list the related issues?

**Comment by jakirkham** [comment]
Added doc issue ( https://github.com/scipy/scipy/issues/5739 ).

**Comment by pv** [comment]
I'm not sure whether there are existing issues for f2py for these.
