### ISSUE TITLE
DOC: Explain constraints on `blas` module functions with ovewrite option

### ISSUE THREAD

**Issue by jakirkham** [scipy/scipy#5739]
Turns out the overwrite option, when provided, does not work in all cases. So, it would be nice to clarify that this requires a Fortran array of the right type.

**Comment by pv** [comment]
It only means the arrays may be overwritten (usually if memory order and data type allows it).

**Comment by jakirkham** [comment]
I guess a warning with some explanation as to why would be helpful as well.

**Comment by ilayn** [comment]
Should we include a hard coded explanation for these keyword usage?

**Comment by pv** [comment]
I guess here:

https://docs.scipy.org/doc/scipy/reference/linalg.blas.html
https://docs.scipy.org/doc/scipy/reference/linalg.lapack.html

**Comment by ilayn** [comment]
Yes. That's what I had in mind.
