### ISSUE TITLE
move to setuptools for next release

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#5745]
Not too happy about this, but we'll have to make this switch for the next release. Mainly due to dev versions with PEP 440 compliant filenames aren't supported by plain distutils. Change should be along the same lines as that for numpy: https://github.com/numpy/numpy/pull/6895

**Comment by ev-br** [comment]
Ralf, do you want to pursue this for 0.18?

**Comment by rgommers** [comment]
Yes, I do. Will try to get this one done asap.
