### ISSUE TITLE
Resampling using polyphase filtering

### ISSUE THREAD

**Issue by Eric89GXL** [scipy/scipy#5746]
Now that upfirdn polyphase filtering is implemented, it should be possible to do upfirdn-based resampling. Hopefully this will be faster than the current FFT-based method.

I don't actually know the correct way to do upfirdn-based resampling, but it looks like Octave does [something reasonable] (http://octave.sourceforge.net/signal/function/resample.html) that is similar to [what MATLAB does] (http://www.mathworks.com/help/signal/ref/resample.html). Although I can't work from the Octave's GPL code, I think I could read the book chapter / equations referenced in the GPL code, and work from that:

http://sourceforge.net/p/octave/signal/ci/default/tree/inst/resample.m

Does that sound about right from a licensing standpoint @WarrenWeckesser @rgommers?

@sirtom67 do you have any other starting points (code or suggesting reading) other than Oppenheim and Schafer (Discrete-time signal processing)? I think I have a copy of that book kicking around somewhere...

**Comment by sirtom67** [comment]
The matlab resample command just does the following:
1) design a low-pass FIR filter with the proper cutoff frequency and some
reasonable rules for setting the length to get a filter that isn't too long
2) call upfirdn
3) get rid of precursor and postcursor filtering tails to remove delay

IIRC, the matlab command used fir1 with a kaiser window. Similar
functionality exists in scipy.signal.

**Comment by Eric89GXL** [comment]
Good to hear, that's what I had gathered from reading the documentation of MATLAB and Octavie. MATLAB apparently uses `firls` but I remember someone saying (mailing list somewhere?) that `firwin` or `firwin` could be used instead in `scipy`. I'll track down Oppenheim and Shafer to get the details right, then.

**Comment by rgommers** [comment]
> I don't actually know the correct way to do upfirdn-based resampling, but it looks like Octave does something reasonable that is similar to what MATLAB does. Although I can't work from the Octave's GPL code, I think I could read the book chapter / equations referenced in the GPL code, and work from that:
>
> http://sourceforge.net/p/octave/signal/ci/default/tree/inst/resample.m
>
> Does that sound about right from a licensing standpoint @WarrenWeckesser @rgommers?

Sorry, seeing the question only now. Yes, that's perfectly fine.
