### ISSUE TITLE
[doc] missing data index value in KDTree, cKDTree

### ISSUE THREAD

**Issue by Carreau** [scipy/scipy#5750]
cKDtree [says](https://github.com/scipy/scipy/blob/ad02ef083824d195f04f267b141716e0f047197f/scipy/spatial/ckdtree.pyx#L622) `Missing neighbors are indicated with self.n.` though `self.n` is not documented (AFAICT as being `len(data)`

KDTree [does not mention](https://github.com/scipy/scipy/blob/master/scipy/spatial/kdtree.py#L432-L434) anything about missing indices, but seem to do the same.

**Comment by rgommers** [comment]
Documenting ``n`` as a public attribute would be good. And also checking for other missing attributes in the docs.

**Comment by gfyoung** [comment]
Ignore that commit.  I meant to address #5751.  Can look at this one in a separate PR though.

**Comment by goelakash** [comment]
I would like to work on this. So: 

1. adding a mention of `n` as equivalent to size of tree in attribute list in both kdtree,py and ckdtree.pyx
2. adding "Missing parameters are indicated by self.n" in KDTree.py 

anything else that should/shouldn't be done?

**Comment by rgommers** [comment]
@goelakash sure, you're welcome to work on this. Don't bother with ``KDTree`` though, only ``cKDTree`` - we're going to be deprecating the former. I think what's needed here is adding a list of all public attributes in the main ``cKDTree docstring with an explanation of what they're for. See https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#class-docstring for the ``Attributes`` format.

**Comment by rgommers** [comment]
Fixed in gh-6939, thanks all.
