### ISSUE TITLE
KDtree/cKDtree add `seealso`  ?

### ISSUE THREAD

**Issue by Carreau** [scipy/scipy#5751]
KDtree/cKDtree do not reference each-other. 

is adding a `:seealso:` be useful ?

Any reason when using KDtree not to use cKDtree automatically when available ?

**Comment by rgommers** [comment]
Yes. Although we'd like to make ``KDTree`` a simple alias of ``cKDTree`` in the near future I think (and after that remove the duplication by deprecating one) but until then this would improve the docs.

**Comment by rgommers** [comment]
and for who picks this up, it's this in numpy docstring format:

    See Also
    --------
    cKDTree : <one-liner explanation...>
