### ISSUE TITLE
DOC: solve_discrete_lyapunov equation puts transpose in wrong place

### ISSUE THREAD

**Issue by arvoelke** [scipy/scipy#5752]
The equation in the docs says `A' X A - X = -Q` when it should really be `A X A' - X = -Q`. This makes it not only consistent with the literature, but also matches the computed result:

```
from scipy.linalg import solve_discrete_lyapunov

a = np.asarray([[1, 0.5], [1, 0]])
q = np.asarray([[1, 0], [0, 1]])

x = solve_discrete_lyapunov(a, q)
print np.allclose(np.dot(a.T, np.dot(x, a)) - x, -q)
print np.allclose(np.dot(a, np.dot(x, a.T)) - x, -q)
```

The first line (which uses the currently documented equation) prints `False`, while the second (which puts the transpose in the correct place) prints `True`.

**Comment by pv** [comment]
gh-5781
