### ISSUE TITLE
signal.tf2ss doesn't handle SIMO transfer functions

### ISSUE THREAD

**Issue by arvoelke** [scipy/scipy#5753]
The routine `signal.ss2tf` will return a list of numerator polynomials, one for each output in the state-space representation. However, `signal.tf2ss` is unable to invert this in 0.17.0rc2, although it seems to attempt to do so in the codebase.

This problem is immediately visible when discretizing a SIMO transfer function:

```
tf = ([[1, 0], [1, 1]], [1, 1])
print scipy.signal.cont2discrete(tf, 0.01)
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-32-d3238586ff06> in <module>()
      1 tf = ([[1, 0], [1, 1]], [1, 1])
      2 #ss = scipy.signal.tf2ss(*tf)
----> 3 print scipy.signal.cont2discrete(tf, 0.01)
      4 
      5 ss = scipy.signal.tf2ss(*tf)

c:\users\aaron\appdata\local\enthought\canopy\user\lib\site-packages\scipy\signal\cont2discrete.pyc in cont2discrete(sys, dt, method, alpha)
     78         sysd = cont2discrete(tf2ss(sys[0], sys[1]), dt, method=method,
     79                              alpha=alpha)
---> 80         return ss2tf(sysd[0], sysd[1], sysd[2], sysd[3]) + (dt,)
     81     elif len(sys) == 3:
     82         sysd = cont2discrete(zpk2ss(sys[0], sys[1], sys[2]), dt, method=method,

c:\users\aaron\appdata\local\enthought\canopy\user\lib\site-packages\scipy\signal\ltisys.pyc in ss2tf(A, B, C, D, input)
    272 
    273     # Check consistency and make them all rank-2 arrays
--> 274     A, B, C, D = abcd_normalize(A, B, C, D)
    275 
    276     nout, nin = D.shape

c:\users\aaron\appdata\local\enthought\canopy\user\lib\site-packages\scipy\signal\ltisys.pyc in abcd_normalize(A, B, C, D)
    208     A = _restore(A, (p, p))
    209     B = _restore(B, (p, q))
--> 210     C = _restore(C, (r, p))
    211     D = _restore(D, (r, q))
    212 

c:\users\aaron\appdata\local\enthought\canopy\user\lib\site-packages\scipy\signal\ltisys.pyc in _restore(M, shape)
    163     else:
    164         if M.shape != shape:
--> 165             raise ValueError("The input arrays have incompatible shapes.")
    166         return M
    167 

ValueError: The input arrays have incompatible shapes.
```

For transfer functions, `signal.cont2discrete` converts the system to state-space, discretizes it, and then converts it back. The first step in particular is the issue, since there seem be a number of issues with `t2fss` when given a SIMO transfer function :
 - tf2ss incorreclty squeezes the D matrix (and this mistake was actually acknowledged on [this line of test code](https://github.com/scipy/scipy/blame/master/scipy/signal/tests/test_ltisys.py#L260))
    ```
    >>> tf = ([[1, 2], [1, 1]], [1, 2])
    >>> print scipy.signal.tf2ss(*tf)[3].shape
    (2L,)
    ```

 - For larger orders, the resulting system has wrong dimensionality
    ```
    >>> tf = ([[1, 0, 1], [1, 1, 1]], [1, 1, 1])
    >>> print [s.shape for s in scipy.signal.tf2ss(*tf)]
    [(2L, 2L), (2L, 1L), (2L, 2L), (2L,)]
    ```

 - And in some cases, it fails:
   ```
    >>> tf = ([[1, 2, 3], [1, 2, 3]], [1, 2, 3, 4])
    >>> print scipy.signal.tf2ss(*tf)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-73-efb39b6e8c65> in <module>()
      6 
      7 tf = ([[1, 2, 3], [1, 2, 3]], [1, 2, 3, 4])
----> 8 print scipy.signal.tf2ss(*tf)
      9 
     10 #print scipy.signal.cont2discrete(tf, 0.01)

c:\users\aaron\appdata\local\enthought\canopy\user\lib\site-packages\scipy\signal\ltisys.pyc in tf2ss(num, den)
    129     A = r_[frow, eye(K - 2, K - 1)]
    130     B = eye(K - 1, 1)
--> 131     C = num[:, 1:] - num[:, 0] * den[1:]
    132     return A, B, C, D
    133 

ValueError: operands could not be broadcast together with shapes (2,) (3,) 
```

**Comment by gfyoung** [comment]
Just for reference, could you specify what the <u>correct</u> outputs should be in all of your examples?  I think I know what is broken.  However, I am not an expert in this area, so I would like to confirm so I know exactly how to proceed.

**Comment by arvoelke** [comment]
After looking at this more closely, it doesn't seem like the codebase attempts to support this, and doing so would be nontrivial. In general the relationship between a MIMO transfer function (described by a matrix of transfer functions, where each entry is a transfer function from one input to one output) and the state-space realization requires a partitioning of state into separate subsystems for each transfer function. It seems like having tools for minimal/balanced realizations and model-order reduction are kind of a prerequisite for doing meaningful things in this case.

I've been working towards this direction in my own repository, and can discuss more about potentially getting some of it into scipy if others are interested. But I don't believe this will be an easy change at all. 

Perhaps the right thing to do here would be to issue an error if  `tf2ss` is called with multiple numerator polynomials, so that people don't make the same mistake as I did of assuming it handles SIMO just because `ss2tf` gives you a numerator polynomial for each output.

**Comment by gfyoung** [comment]
A little too late.  I just got it too work :)
