### ISSUE TITLE
p-value computation in scipy.stats.kendalltau() in broken in the case of ties

### ISSUE THREAD

**Issue by vigna** [scipy/scipy#5755]
The null statistics for kendall's τ is [very different](https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient#Significance_tests) in the case of ties. Presently, the code computes τ and then applies the null statistics for the tieless case to the general case, leaving people [really puzzled](http://stats.stackexchange.com/questions/71026/kendall-tau-b-correlation-coefficient-becomes-more-significant-with-many-additio).

I have created a [pull request](https://github.com/scipy/scipy/pull/5754) that improves performance and fixes a few problems, putting again the code in line with that we developed at the LAW (which was used in 2009). In doing so, I set up things so that a p-value of NaN is returned in case of ties, as the present situation is most dangerous.

I'm ready to help to modify the code so that it computes the pieces of information that the real null statistic needs, but I need a statistician to check the theoretical part. (IANS)

**Comment by vigna** [comment]
As a side note, mstats_basic.kendalltau() computes the p-value for the case of ties using the distribution I discussed above. The results are of course most puzzling:

    scipy.stats.kendalltau([1,0,0],[0,0,1])
    KendalltauResult(correlation=-0.5, pvalue=0.43342194319179717)

    mstats_basic.kendalltau([1,0,0],[0,0,1])
    KendalltauResult(correlation=-0.5, pvalue=0.47950012218695348)

**Comment by vigna** [comment]
Presently https://github.com/scipy/scipy/pull/5754 contains a correct implementation of the computation of the p-value in the case of ties.

**Comment by vigna** [comment]
#5754 has been closed as #5548 is more suitable to Python/Scipy.

**Comment by ev-br** [comment]
Fixed by gh-6677, closing.
