### ISSUE TITLE
BUG: Incorrect complex output of signal.spectrogram

### ISSUE THREAD

**Issue by e-q** [scipy/scipy#5757]
This one is my fault. Back when I adapted the matplotlib algorithm for PSD/CSD/coherence/spectrogram calculations in #4682, I didn't write any tests or pay much attention for some of the output modes of `_spectral_helper`, like `complex` or `angle`, since none of the functions I was writing used those modes. 
#5172 added the mode kwarg for spectrogram, which is great, but has brought some bugs to light. For instance, I would expect to be able to do something like the following

```
_, _, p = spectrogram(x, mode='psd')
_, _, c = spectrogram(x, mode='complex')
pc = np.conj(c)*c
assert_allclose(p, pc)
```

This currently does not pass. I'm working on a PR that will fix this and increase the test coverage of `_spectral_helper`, which I'll put up in the next few days.

**Comment by e-q** [comment]
Thinking about this a little more, it's a little weird to ask for complex or phase output in a spectrogram way, i.e. various FFT segments. Monochromatic signals will result in a varying phase over segments if the interval between segments is not a factor of the signal's period, which will almost generically be the case. So, for any realistic signal, the results will be all over the place. 

In maplotlib.mlab, these modes are only accessible by functions that only compute one FFT segment (i.e. `nperseg=len(x)`, which makes sense. 

The only thing I can imagine the complex spectrogram output being useful for (which, incidentally is how I stumbled across this) is for computing many permutations of PSDs and CSDs, so you don't have to repeat FFTs. The phase washes out in the PSD, and the CSD only cares about the relative phases of the signals, so the issue I described above doesn't matter.

I'm interested to hear what people think should happen. Should the `complex` kwarg and it's ilk be removed? Constrained to only work for a single FFT segment?

**Comment by rgommers** [comment]
Hmm, looks like I was too quick in merging gh-5172. I think you're right that there's not much use for those modes. @FRidh do you have an application for these added modes?

Cross-checked with Matlab, it doesn't have these modes. It does have a ``'power'`` one that tries to correct for noise in each segment: http://nl.mathworks.com/help/signal/ref/spectrogram.html#inputarg_spectrumtype

**Comment by FRidh** [comment]
Not really. I just noticed they were missing. I agree with @e-q that the complex spectrum can be convenient to keep.

**Comment by rgommers** [comment]
So if we keep ``complex``, then the todo here would be something like:

- add an example for ``complex`` and a sentence on what it's good for.
- add the example also as a unit test
- remove the other modes, and add a note in the 0.18.0 release notes under backwards incompatible changes.

**Comment by Eric89GXL** [comment]
@rgommers that sounds like a good plan to me

**Comment by endolith** [comment]
> Thinking about this a little more, it's a little weird to ask for complex or phase output in a spectrogram way, i.e. various FFT segments. Monochromatic signals will result in a varying phase over segments if the interval between segments is not a factor of the signal's period, which will almost generically be the case. So, for any realistic signal, the results will be all over the place.

But the [derivative of the phase is meaningful](https://gist.github.com/endolith/990ad1d350c3eeec3a9d) (frequency offset within a bin) and ampl/phase information is required for applications like [phase vocoder](http://www.ee.columbia.edu/ln/rosa/matlab/pvoc/), time-localized filtering, or other time-frequency manipulations.

> In maplotlib.mlab, these modes are only accessible by functions that only compute one FFT segment (i.e. nperseg=len(x), which makes sense.

matplotlib is only for plotting though.  [I would like scipy to be able to do general TFD manipulation](http://stackoverflow.com/q/2459295/125507).   Is that not what _spectral_helper is for?

**Comment by e-q** [comment]
Good points, I hadn't considered the phase derivate information. (As an aside, the reference to matplotlib is relevant only in that `matplotlib.mlab` contains the code that became scipy's `_sepctral_helper` and included this `mode` kwarg.)

gh-5908 currently keeps `spectrogram`'s `mode='complex'` capability, which indeed returns a discrete short time fourier transform; I should edit the docstring to make this more clear, I didn't appreciate this fact until now.

However, we do not currently have an inverse function written. Taking care of overlapping segments seems to have some subtleties to to it, according to the SO thread you linked to (or maybe the subtlety is in the right choice of `noverlap` for a given window function and length to reduce the effect of aliasing on the inverse transform output?)

Maybe the right thing to do is to go back to `spectrogram` calling `_spectral_helper` with `mode='psd'`, and create new functions for `stft` (using `mode='complex') and `istft` function (with some new code).

**Comment by cboschen** [comment]
I am using spectrogram to evaluate a complex signal and not seeing any of the signal that I would expect to see in the positive frequency region.   See plot attached, the positive frequencies in the first part of the sweep are missing!  Is this the known bug described in this issue# or operator error?  I am using Python 2.7 and am using the spectrogram command as follows: 

    freq, time, spect = signal.spectrogram(multOut, fs)

fs is my sampling rate of 100e6, and multOut is my complex valued signal, which has two tones sweeping over time.

![capture](https://cloud.githubusercontent.com/assets/19955532/16086257/ebeb6840-32ec-11e6-8756-f11d9e073ae0.PNG)

**Comment by e-q** [comment]
It's hard to say without seeing how that plot was produced, but I do have a guess. It looks like the upper sideband frequency is close to zero at the start of the time series. Be default, `spectrogram` detrends each window segment by subtracting the mean signal value in that segment, which can reduce the apparent magnitude of very low frequency signals (see the `detrend` keyword argument)

To be more certain, it would be helpful if you could post a [gist](gist.github.com) that reproduces this problem.

**Comment by ev-br** [comment]
#6058 apparently needs a wee bit more time to get ready, so re-milestoning this

**Comment by petspats** [comment]
@cboschen @e-q 
I ran into same problem. Basically if i just plot sine at +frequencies i see nothing, however works fine if sine is at -frequencies. Detrend disabled had no effect.

Quick test:
```python
%matplotlib inline
import numpy as np
from scipy.signal import spectrogram, periodogram
import matplotlib.pyplot as plt

fs = 500
# NOTE: CHANGE TO -100 AND IT WORKS!
freq = 100
time = np.linspace(0, 1, fs*1, endpoint=False)

phase_angle = 2*np.pi*freq*time*1j
ref = np.exp(phase_angle)

# this works always
f, Pxx_den = periodogram(ref, fs)
plt.semilogy(f, Pxx_den)
plt.show()

# works for -frequencies only!
f, t, Sxx = spectrogram(ref, fs)
plt.pcolormesh(t, f, Sxx)
plt.show()
```

Workaround:
Use matplotlib instead.
http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.specgram

**Comment by karhohs** [comment]
@e-q 
> Maybe the right thing to do is to go back to spectrogram calling _spectral_helper with mode='psd', and create new functions for stft (using mode='complex') and istft (with some new code).

Is the stft branch of your scipy fork operational? Do you know when you'll be submitting a pull request?

**Comment by e-q** [comment]
@cboschen @petspats: This actually is a problem with the plotting, rather than the calculation. It looks like `pcolormesh` doesn't like the ordering of the frequency vector. Using `fftshift` fixes the posted example. I.e.

```python
f, t, Sxx = spectrogram(ref, fs)
fftshift(f)
Sxx = fftshift(Sxx, axes=0)
plt.pcolormesh(t, f, Sxx)
```

@karhos: The relevant PR is gh-6058. The `stft` code itself seems to work well, we just need to modify some of the `scipy.fftpack` code to avoid unnecessary up-casting of 32-bit data.
