### ISSUE TITLE
Allow Source Builds on Cygwin64

### ISSUE THREAD

**Issue by gfyoung** [scipy/scipy#5759]
When ```setup.py``` tries building the ```fftpack``` and ```dfftpack``` files, it automatically builds them into the ```x86``` architecture, making them incompatible with ```Cygwin64```.  Related to ```numpy``` issue <a href="https://github.com/numpy/numpy/issues/7104">#7104</a>.

**Comment by rgommers** [comment]
There's nothing in https://github.com/scipy/scipy/blob/master/scipy/fftpack/setup.py or other scipy setup.py files that can be responsible for this kind of thing. It's all coming from distutils and numpy.distutils. So not a scipy bug. I suggest to keep thttps://github.com/numpy/numpy/issues/7104 for all these Cygwin issues.

**Comment by gfyoung** [comment]
Ah, okay.  Good to know, thanks for the info!  That will make things a little easier if I can just focus on ```numpy```.
