### ISSUE TITLE
Floating point error for derivative of legendre if n > 85 and 

### ISSUE THREAD

**Issue by carolynlphillips** [scipy/scipy#5769]
```
import scipy
import scipy.special as sp
import numpy as np
print scipy.__version__

np.seterr(invalid='raise')

n=86
testP =sp.legendre(n)
testPprime = testP.deriv(1)
print "Test Legendre ",n, testP(0)
print "Test Legendre (Derivative) ",n, testPprime(0)
```

Generates
```
0.16.0
Test Legendre  86 -0.0857883629175
Test Legendre (Derivative)  86
Traceback (most recent call last):
  File "example_scipyproblem.py", line 12, in <module>
    print "Test Legendre (Derivative) ",n, testPprime(0)
  File "/pathto/anaconda/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 1137, in __call__
    return polyval(self.coeffs, val)
  File "/pathto/anaconda/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 680, in polyval
    y = y * x + p[i]
FloatingPointError: invalid value encountered in double_scalars
```

**Comment by pv** [comment]
`legendre` returns the polynomials in the power basis, and order 86 is too high to be represented in a numerically stable way there. Floatingpointerror in this case is correct behavior.

Please see the warning here: http://docs.scipy.org/doc/scipy/reference/special.html#orthogonal-polynomials

**Comment by ewmoore** [comment]
The answer here is to not use `special.legendre` and similar.  They work in the power basis are are unstable when working with high orders.  This doesn't apply to the `special.eval_legendre` and similar functions.  For working with legendre series you should use `numpy.polynomial.legendre.Legendre`.

```
In [83]: l86 = np.polynomial.legendre.Legendre(86*[0,] + [1,])

In [84]: l86prime = l86.deriv()

In [85]: l86([0, 0.2, 0.4])
Out[85]: array([-0.08578836, -0.01200776,  0.04541519])

In [86]: special.eval_legendre(86, [0, 0.2, 0.4])
Out[86]: array([-0.08578836, -0.01200776,  0.04541519])

In [87]: l86prime([0, 0.2, 0.4])
Out[87]: array([ 0.        , -7.57899006, -7.2800683 ])

In [88]: leg_prime_check = lambda n, x: n*(special.eval_legendre(n, x)*x - special.eval_legendre(n-1, x)) / (x**2 - 1)

In [89]: leg_prime_check(86, np.array([0, 0.2, 0.4]))
Out[89]: array([ 0.        , -7.57899006, -7.2800683 ])
```

Perhaps it's time we explicitly deprecate `special.legendre` and friends?

**Comment by pv** [comment]
Deprecation could be useful, but I think should be done only when there's something better to offer.
(-> open new issue?)

**Comment by pv** [comment]
Also, a warning about the order limitations could be added to the docstrings of the individual poly functions, not only on the main page.
