### ISSUE TITLE
Incorrect output of scipy.optimize.brute with slices, due to finish not respecting bounds

### ISSUE THREAD

**Issue by HubertHolin** [scipy/scipy#5773]
Executing the following script outputs `[  1.09315092e+49  -3.01363994e+50  -3.42309008e+50]`, which is quite unexpected:

```
import numpy
import scipy.optimize

def f(var):
	x, y, z = var
	return x+y+z

rranges = (slice(0,3,1),slice(0,3,1),slice(0,3,1))

xmin, Jmin, grid, Jout = scipy.optimize.brute(f, rranges, full_output = True)

print(xmin)
```

The example on the documentation page (http://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.brute.html#scipy.optimize.brute) does work as advertised. What am I missing?

Hubert Holin

Python 3.5.1 (default, Jan 28 2016, 15:52:46) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin

numpy-1.10.4

scipy-0.18.0.dev0+4f37300 SHA:4f37300e3e3558105b187d3e143f45f3bbca6d1d

**Comment by HubertHolin** [comment]
The same incorrect behaviour also happens with tuples instead of slices, _i.e._ with `rranges = ((0,3),(0,3),(0,3))` (and `Ns= 4`) instead of with `rranges = (slice(0,3,1),slice(0,3,1),slice(0,3,1))` in the example above.

Hubert Holin

**Comment by pv** [comment]
The function does not have a minimum, so the finish step (default: nelder-mead) goes haywire.

**Comment by HubertHolin** [comment]
Yes, definitely, using `finish=None` does work. However, the function does have a global minimum on the (closed) domain: `(0,0,0)`, where the value is `0`, so perhaps at least the documentation should point out this corner case…

Merci

Hubert Holin
