### ISSUE TITLE
Generated documentation is out of date

### ISSUE THREAD

**Issue by amcameron** [scipy/scipy#5774]
The exponents in the denominators of the Freedman–Diaconis and Scott estimators are shown incorrectly in the typeset maths on this page:
http://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.histogram.html

The offending lines of source code were corrected in commit [41de3c2d8c84dbfa406ccb77dd67d55f555bee8a](https://github.com/numpy/numpy/commit/41de3c2d8c84dbfa406ccb77dd67d55f555bee8a) in December, and incorporated on the maintenance/1.11.x branch, but the generated documentation doesn't yet reflect this, having been last updated in October.

**Comment by pv** [comment]
Better place to file this bug, so that people who might do something about it read it: https://github.com/numpy/numpy/
There's no automation in place for numpy.

**Comment by amcameron** [comment]
Cheers; I'll repost it there. Thank you.

**Comment by amcameron** [comment]
For posterity: https://github.com/numpy/numpy/issues/7136
