### ISSUE TITLE
tests don't run in 'develop' mode anymore with numpy master

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#5778]
See https://github.com/numpy/numpy/pull/7099/files#r51348007

Needs fixing by setting `raise_warnings` correctly in `scipy/__init__.py`

**Comment by njsmith** [comment]
Started in #5641

**Comment by rgommers** [comment]
Thanks, completely forgot about that PR.

**Comment by rgommers** [comment]
no longer relevant after the Pytest switch - there's no longer a `raise_warnings` keyword. Current behavior is fine.
