### ISSUE TITLE
scipy.amin() doesn't work with sparse matrix

### ISSUE THREAD

**Issue by cossio** [scipy/scipy#5785]
Try the following code:

` m = scipy.sparse.diags([1.0, -2.0, 1.0], [-1, 0, 1], shape=(4,4), format='csc')`
` scipy.amin(m) `

The last statement results in a 

> TypeError: min() got an unexpected keyword argument 'out'

However, scipy.amin(m.todense()) gives the correct result, indicating that this is a problem with sparse matrices.

**Comment by rgommers** [comment]
Hi @cossio, note that pretty much everything in the main ``scipy`` namespace is a ``numpy`` function. Those are only still there for historical (backwards compatibility) reasons.

And ``numpy`` simply doesn't know about sparse matrices. So the error is expected - hence closing this issue.

**Comment by cossio** [comment]
Is there something similar to amin() that works for sparse matrices in scipy?

**Comment by rgommers** [comment]
sparse matrices have a ``min`` method

**Comment by cossio** [comment]
If I run:

`m = scipy.sparse.diags([1.0, -2.0, 1.0], [-1, 0, 1], shape=(5, 5))`

I don't see a `min` method inside `m`. I am using v0.14.1.

**Comment by rgommers** [comment]
Looks like they exist only for CSR and CSC matrices (which are the fastest and most feature-complete ones):

    In [12]: x = sparse.csr_matrix(1)

    In [13]: x.min()
    Out[13]: 1

**Comment by perimosocordiae** [comment]
`.min()` and `.max()` are implemented for COO and BSR formats as well. It's on my wishlist to get those methods implemented for DIA format, but it hasn't happened yet.
