### ISSUE TITLE
kmeans2: "ValueError: unknown init method uniform"

### ISSUE THREAD

**Issue by ahojnnes** [scipy/scipy#5786]
There is a discrepancy between the docstring and the implementation of `kmeans2`. The method `uniform` does not seem to be implemented.

**Comment by gfyoung** [comment]
Which doc are you reading?  `master`correctly documents that it is not supported <a href="https://github.com/scipy/scipy/blob/dd527ad940cba29153c289676f7f449020f5e488/scipy/cluster/vq.py#L700" target="_blank">here</a>.

**Comment by ahojnnes** [comment]
I might have missed the (unsupported) but why is it even listed then?
This is confusing...

**Comment by gfyoung** [comment]
That is a fair point.  I suspect it's because they're planning to implement at some point?

**Comment by rgommers** [comment]
I think it should be removed. Clearly the original author never got around to this and is not going to implement this anymore.
