### ISSUE TITLE
Extracting bounds from a scipy rvs object

### ISSUE THREAD

**Issue by MechCoder** [scipy/scipy#5802]
Hi,

Is there a way to extract the bounds from a scipy rvs object. The documentation seems to `a` and `b` give the upper and lower bounds but this does not work when the scales are changed. For example.

```
rv = uniform(loc=-5, scale=5)
rv.a
0.0
rv.b
1.0
```

I would expect -5 and 0 or is this a wrong way to extract the bounds?

**Comment by ev-br** [comment]
`a` and `b` attributes of frozen instances relate to the standardized distributions, just like the non-frozen ones:

```
>>> x = np.linspace(-6, 1, 21)
>>> stats.uniform.a, stats.uniform.b
(0.0, 1.0)
>>> stats.uniform.pdf(x, loc=-5, scale=5)
array([ 0. ,  0. ,  0. ,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,
        0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0. ,  0. ,  0. ])

>>> rv = stats.uniform(loc=-5, scale=5)
>>> rv.a, rv.b
(0.0, 1.0)
>>> rv.pdf(x)
array([ 0. ,  0. ,  0. ,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,
        0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0. ,  0. ,  0. ])
```

The bounds with non-standard loc and scale are then `rv.a * scale + loc` and `rv.b * scale + loc`.

**Comment by rgommers** [comment]
question seems answered, so closing
