### ISSUE TITLE
sparse.linalg.eigs() set default ncv

### ISSUE THREAD

**Issue by amilsted** [scipy/scipy#5809]
The current default ncv parameter for sparse.linalg.eigs() often leads to wrong answers.

In the _ArpackParams class constructor, the ncv parameter is set to the bare minimum of 2*k + 1 (where k is the number of requested eigenvalues). 
`
        if ncv is None:
            ncv = 2 * k + 1
`
This is often insufficient to obtain convergence of the requested eigenvalues, with different eigenvalues being returned instead.

To avoid this issue, MATLAB and Julia both use a minimum of ncv=20 by default (see [MATLAB's "p" option](http://de.mathworks.com/help/matlab/ref/eigs.html)). I think scipy would benefit from doing the same:
`
        if ncv is None:
            ncv = min(20, 2 * k + 1)
`
I think the small memory usage increase (ncv * size of a Krylov vector) is well worth it for correctness of the answers in cases like mine (see attachment). Also, as an added bonus, the speed of convergence can be greatly enhanced.

I've attached a demonstration in the form of an ipython notebook, including test data:
[ARPACK_test.zip](https://github.com/scipy/scipy/files/118285/ARPACK_test.zip)

**Comment by pv** [comment]
duplicate gh-5612
