### ISSUE TITLE
scipy.spatial.ckdtree with query_pairs(output_type="ndarray") fails if no pairs were found

### ISSUE THREAD

**Issue by mimakaev** [scipy/scipy#5812]
Without "ndarray" argument query_pairs returns an empty set as expected

**Comment by larsmans** [comment]
Can you post a [minimal example](http://www.sscce.org/) that reproduces the issue?

**Comment by mimakaev** [comment]
Actually, it is fixed in the current github version. It does still exist in Anaconda. The code that breaks it is below. 

from scipy.spatial import cKDTree
x = [(0,0,0),(0,0,1),(0,1,0),(1,0,0)]
tree = cKDTree(x)
tree.query_pairs(0.9, output_type="numpy")

**Comment by rgommers** [comment]
great, thanks for following up @mimakaev
