### ISSUE TITLE
EHN: Making .to*() functions for sparse matrices consistent.

### ISSUE THREAD

**Issue by musically-ut** [scipy/scipy#5822]
The method `.tocsr` exists on all sparse matrices. However, if the matrix originally is a CSR matrix, the method can be called with the parameter `copy`, which copies the data instead of returning `self`. Similarly, only the `.tocoo` method of a COO matrix accepts the `copy` parameter while the same method on other matrices does not. This creates inconsistent API.

This can be resolved in two ways:

 1. Taking away the `copy` argument from the `.tocsr`, `.tocoo`, etc. methods (after putting it behind a deprecation warning). This would mean that calls to `csr_mat.tocsr(copy=True)` would need to be replaced with `csr_mat.copy().tocsr()`.
 2. Adding the same argument to every other method. This would mean that the call `.tocsr(copy=True)` works for both CSR and non-CSR matrices in the same way. This will preserve backwards compatibility.

Both issues make the API more consistent. Any thoughts?

**Comment by perimosocordiae** [comment]
I like option two better. It's better for back compatibility, and it admits more efficient code.

**Comment by jakevdp** [comment]
+1 on option 2

**Comment by musically-ut** [comment]
After some more thinking, I actually am leaning towards option 1.

If we go forward with option 2, we'll have to throw an error if `copy=False` is passed to a conversion method on a matrix which _cannot_ be transformed to the other form without copying the data.

**Comment by jakevdp** [comment]
I'm not sure we'll have to throw an error in that case. I was thinking it would behave the same way as [this sklearn function](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/utils/validation.py#L301) ``copy=True`` implies a forced copy in all cases, ``copy=False`` implies a copy only if necessary.

**Comment by musically-ut** [comment]
Interesting, I didn't know how `sklearn` dealt with it. 

However, to preserve backwards compatible behavior in this case, the default value of `copy` parameter would always be `True` except when the type of conversion is to the same type as the original array. I am not sure how I feel about that and I can swing either way.

As a sidenote, should a warning be produced if a copy is made and `copy` was explicitly set to `False`?

**Comment by jakevdp** [comment]
> However, to preserve backwards compatible behavior in this case, the default value of copy parameter would always be True except when the type of conversion is to the same type as the original array. I am not sure how I feel about that and I can swing either way.

I think ``copy=True`` for everything would be fine. Are there any cases currently where the conversion is done as a view rather than a copy?

> As a sidenote, should a warning be produced if a copy is made and copy was explicitly set to False?

No: if the option is documented the same way as the scikit-learn example, I don't think a warning is necessary. ``copy=True`` would mean "force a copy even if not necessary". ``copy=False`` would mean "return a view if possible, otherwise copy the data". Plus, in my experience warnings are annoying and mostly ignored by the user.

**Comment by perimosocordiae** [comment]
The backwards compatible solution would be to default to `copy=False` everywhere.

We could do a better job of documenting this, but the `copy` parameter really just means that the user needs a new matrix, even if the format is unchanged. If `False`, it means that the user wants the most efficient conversion possible.

**Comment by jakevdp** [comment]
> The backwards compatible solution would be to default to ``copy=False`` everywhere.

Ah, right. Thanks.

**Comment by musically-ut** [comment]
`copy=False` appears to be a reasonable default for all cases on a cursory look. I'll try to implement this and see if I run into any issues.

Thanks!

**Comment by larsmans** [comment]
+1 for what @jakevdp and @perimosocordiae said. Note that SciPy also already does this in several places, except with the inverse parameter name: `scipy.fftpack.fft` has an `overwrite_x` that allows it to use the input as scratch space if `True`, without the promise of doing an in-place operation. `linalg` has more examples of this.
