### ISSUE TITLE
Bug in L-BFGS-B minimize?

### ISSUE THREAD

**Issue by wilmerhenao** [scipy/scipy#5832]
Hi. I think I found a bug. Good news is that I think I know where it's coming from.
I'm calling function minimize with argument method='l-bfgs-b'. I get an error like this:

```
_________________________________________________________________________
  File "/home/wilmer/Dropbox/Research/VMAT/VMATwPenCode/greedyVMAT.py", line 679, in solveRMC
    res = minimize(calcObjGrad, data.currentIntensities, method='L-BFGS-B', jac = True, bounds=[(0, None) for i in range(0, data.numbeams)], options={'ftol':1e-6, 'disp':5,'maxiter':1000})
  File "/usr/lib/python3.5/site-packages/scipy/optimize/_minimize.py", line 444, in minimize
    callback=callback, **options)
  File "/usr/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 311, in _minimize_lbfgsb
    isave, dsave)
ValueError: failed to initialize intent(inout) array -- input not fortran contiguous
__________________________________________________________________________
```

I just spent a couple of hours banging my head against my laptop. Here's the solution. The solution was my function calcObjGrad returns a value f and a gradient. Instead of returning gradient I should be returning the transpose of a gradient.

Maybe this problem is not limited to 'L-BFGS-B'? Or maybe it was pointed out in the documentation somewhere in which case, I apologize and please ignore.

**Comment by dlax** [comment]
Depends on what you mean by "transpose" of the gradient... Usually, given the objective function `f(x)` where `x` is a vector (1-dimension, shape `(n, )`) and `f` returns a scalar, the gradient has the shape of `x` and is a vector (1-dimension), so transpose is somehow meaningless.

**Comment by argriffing** [comment]
> `self.scipygradient = (np.asmatrix(self.mygradient) * self.GradientIntermediate).transpose()`

In theory, numpy matrices are great...

**Comment by argriffing** [comment]
For debugging it may help to know the types and shapes of the objects passed to `minimize` and of the objects returned by the callback function.

**Comment by odellus** [comment]
I'm using Ubuntu 16.04 with scipy-0.18.1 installed with pip.

Here's a "minimal" reproducible example of the problem I'm having.
https://gist.github.com/odellus/505fe9d1ec8f501c797441bdffaac1b5

If I switch out `fmin_cg ` for `fmin_l_bfgs_b` it starts working, but in it's current state I get the error
```
Traceback (most recent call last):
  File "my_atari_ram_policy.py", line 243, in <module>
    test_AtariRAMPolicy()
  File "my_atari_ram_policy.py", line 240, in test_AtariRAMPolicy
    res = opt.fmin_l_bfgs_b(fpen, theta, fprime=fgradpen, maxiter=20)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 193, in fmin_l_bfgs_b
    **opts)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/lbfgsb.py", line 321, in _minimize_lbfgsb
    isave, dsave, maxls)
ValueError: failed to initialize intent(inout) array -- expected elsize=8 but got 4
```

**Comment by ev-br** [comment]
Could you trim the example a bit further, to remove the dependency on TensorFlow at least.

**Comment by ev-br** [comment]
In fact, if I start playing the guessing game, the error message

> ValueError: failed to initialize intent(inout) array -- expected elsize=8 but got 4

looks to be hinting that you have some 32-bit floats somewhere, while Fortran code expects `real*8`, i.e. C double. And indeed, you have some `tf.float32` in your code. So the guess is that the error goes away if you change those to `tf.float64` or something to that effect.

**Comment by odellus** [comment]
That does fix the issue, but I'd really like to be able to hand single precision floats to `fmin_l_bfgs_b` if possible since they're computed so much faster on the GPU. Maybe I need to read up on Nocedal and Wright some more to see why this , but it doesn't seem like an unreasonable expectation. 

Feature request?

**Comment by odellus** [comment]
Also, many thanks.

**Comment by ev-br** [comment]
Looks similar to https://github.com/scipy/scipy/issues/4873 (hence *different* from the OP). In principle, I guess, one could copy-paste the Fortran code, replace all `double precision` with `real` and write a fused-type cython wrapper to dispatch depending on the input type. This would then be a bit of a project to actually investigate the stability of single-precision maths.

**Comment by odellus** [comment]
Exactly. I think I'll take a look into how `fmin_cg` and other `fmin_*` functions handle both single and double precision since I'm new to SciPy development, but I might have time tackle it if you folks have other priorities at the moment.

**Comment by ev-br** [comment]
@odellus sure thing!

**Comment by andyfaff** [comment]
LBFGSB uses finite differences to calculate the jacobian if no callable is provided to the function. 
The estimation of gradient by finite differences really requires double precision to work in a reasonable fashion across a range of problems. Whilst SP might be ok for some things they'll be in the minority, and if conversions to double weren't made there would soon be issues being raised by people using SP on problems were DP was required.
Also, the fortran code for LBFGSB is all setup for double precision calculation, and changing it would be a big job, and not necessarily result in improved behaviour.
Thus, the development effort needed to make a change probably outweighs the gain. OP may find that casting to SP before objective/jac calculation on a GPU, then recasting to DP might work satisfactorily.
