### ISSUE TITLE
docstring of stats.binom_test() needs an update

### ISSUE THREAD

**Issue by srvanrell** [scipy/scipy#5833]
The docstring of `stats.binom_test()` does not include a description of the parameter `alternative` and its possible values. Nevertheless, the function knows how to handle the values of `alternative` (https://github.com/scipy/scipy/blob/master/scipy/stats/morestats.py#L1978).

If a user that want to use the `binom_test()` function reads the docs, he may feel disappointed (as it happened to me before I saw the source code)

I think that the docstring needs an update, don't you?

**Comment by maniteja123** [comment]
Hi, I am not a dev but it seems that the ``alternative`` keyword was added to hypothesis tests in this [PR](https://github.com/scipy/scipy/pull/4899). I suppose that the updation of documentation was missed somehow. It would be helpful if you can send a PR with doc update if interested. Thanks.

**Comment by srvanrell** [comment]
Done. PR #5834

**Comment by ev-br** [comment]
Fixed in https://github.com/scipy/scipy/pull/5834, closing.
