### ISSUE TITLE
Wishlist/ENH: implement the principle branch of log gamma

### ISSUE THREAD

**Issue by person142** [scipy/scipy#5840]
I know there's ``special.gammaln``. But it computes ``ln(gamma(x))``, which is not the principle branch of log gamma, see

http://mathworld.wolfram.com/LogGammaFunction.html

For more details see e.g.

https://cs.uwaterloo.ca/research/tr/1994/23/CS-94-23.pdf

 From here on out I'll denote the principle branch by ``loggamma``. ~~Implementing ``loggamma`` would (hopefully) be easy~~ because the two functions are very close:

``loggamma(x) = log(gamma(x)) + 2*pi*i*ceil(x/2 + 1)``.

But if they're so close, why is it worth adding the function? As things currently stand, ``np.exp(gammaln(x))`` is *not* always equal to ``gamma(x)``: there are phase factors that one has to keep track of. (Try it with ``x = -10.1``!) This makes working in log space annoying and is probably not what users expect to happen. On the other hand, ``np.exp(loggamma(x))`` is always equal to ``gamma(x)``. There's a similar story for other identities like ``loggamma(x + 1) = log(x) + loggamma(x)``. Also, the branch cuts of ``gammaln`` are very complicated (see above mathworld link) compared to those of ``loggamma``, which has a single branch cut on the negative real axis.

In fact, I would go so far as to say that it's sensible to add a new function called ``loggamma`` and deprecate ``gammaln``.

If people think this is a good idea, I'd be glad to work on it.

**Edit**: the above identity only holds for ``x < 0``, so the implementation is more complicated than I was making it seem.

**Comment by pv** [comment]
loggamma & gammasgn enable working in real domain.

**Comment by person142** [comment]
The angles for arguments to ``loggamma`` are taken to be in ``(-pi, pi]`` so that the function works fine on the entire real line and has a discontinuity on the negative real axis. (This is how mpmath does it for example.) In general on the real line one should have ``exp(loggamma(x)) = gammasgn(x)*exp(gammaln(x))``.

But probably calls for deprecation were hasty.

**Comment by pv** [comment]
I mean that loggamma necessarily returns complex-valued results for real inputs. `exp(loggamma(x))` is real-valued only to fp precision, because pi is not exactly representable.

**Comment by person142** [comment]
Ah, now I see what you mean.

**Comment by pv** [comment]
That being said, I don't see problems with adding `loggamma` for the primary branch.
