### ISSUE TITLE
Segmentation fault in scipy.sparse.linalg.svds()

### ISSUE THREAD

**Issue by pminervini** [scipy/scipy#5846]
Hello everyone,

I am experiencing a "Segmentation fault" error when running the following snippet:

```python
import numpy as np

import scipy.sparse as sparse
import scipy.sparse.linalg as linalg

import concurrent.futures


def go():
    nb_rows, nb_cols, k = 100, 100, 10
    S = sparse.lil_matrix((nb_rows, nb_cols))

    rows, cols = np.random.randint(2, size=(nb_rows, nb_cols)).nonzero()
    S[rows, cols] = 1

    U, S, Vt = linalg.svds(S.tocsr(), k=k)


with concurrent.futures.ThreadPoolExecutor(max_workers=10) as executor:
    for i in range(1024):
        executor.submit(go)
```

Here's the output:

```bash
$ python3.5 threads.py 
Segmentation fault
```

**Comment by ewmoore** [comment]
I don't think arpack is thread safe.  It uses a number of fortran save statements to preserve variables across calls.

**Comment by pminervini** [comment]
Thank you @ewmoore for your answer. I've "temporarily" fixed the problem by using a `ProcessPoolExecutor` in place of a `ThreadPoolExecutor`, but I'm still deeply interested in making the code above thread-safe.

**Comment by pv** [comment]
@pminervini: the short answer is that the ARPACK Fortran code cannot be run in multiple threads at the same time. It can be made thread safe with locks, but the only one thread will run at a time.

**Comment by pv** [comment]
Locks added in gh-5846

**Comment by marscher** [comment]
Isn't it possible to ensure only one thread has "access" to the fortran interface without using locks? Lets say one wants to run other simple tasks while diagonalizing a huge matrix - this is not possible any more by means of #5848.
