### ISSUE TITLE
Error in scipy.linalg.expm for complex matrix with shape (1,1)

### ISSUE THREAD

**Issue by danielru** [scipy/scipy#5853]
When using the function `scipy.linalg.expm` for complex matrices of shape `(1,1)`, some values result in a `IndexError: too many indices for array` error. A minimum example reproducing the error is given below.

This is with Anaconda `Python 2.7.11 :: Continuum Analytics, Inc.` and SciPy version `0.17.0`.

Note that only the value of the single matrix entry changes slightly.

**Minimum example**:

from scipy import sparse
from scipy.sparse import linalg 
v_works = -2.02683397006j
v_error = -2.12817566856j
M_works = sparse.csc_matrix([[v_works]], dtype='complex') 
M_error = sparse.csc_matrix([[v_error]], dtype='complex')
print linalg.expm(M_works)
print linalg.expm(M_error)

**Comment by ewmoore** [comment]
Given that the matrix exponential of a 1x1 matrix is trivial, the fix is probably to check this special case early on in `expm`

**Comment by danielru** [comment]
What I found very surprising is that the error depends on the *value* in the matrix. Any idea why this is? A breakdown of the Pade approximation or something?
