### ISSUE TITLE
Specify Nelder-Mead initial simplex

### ISSUE THREAD

**Issue by AdriaanRol** [scipy/scipy#5856]
When using the scipy.optimize "nelder-mead" method it is currently not possible to specify the initial simplex values. Instead scipy automatically sets this to be (1+0.05)*x0. If a priori information on the optimization problem is available it makes sense  to specify this. 

I have found several pull-requests in scipy that address this issue (#3974, #3634, and #3729) but none of these have been merged and all have not been edited for more than half a year. 

Is there reason these did not get merged? If so what would be required for something to be merged into a main scipy release?

(If an issue is not the way to raise a discussion, my apologies. It appears the link to the mailinglist on the main page is broken)

**Comment by pv** [comment]
gh-3974 was not finished (no tests), the other two have been sitting waiting for comments after the first round of comments, probably partly due to the needs-work label having not been removed.

Looking at them now, gh-3729 introduces some code duplication that's probably not fully necessary, for gh-3634 one needs to decide if that way is a good way to specify the simplex.

**Comment by AdriaanRol** [comment]
@pv Thanks for the quick reply. Looking at the code I would say that  #3729 is probably the best way to specify a simplex as it is more explicit than #3634. 

However I agree that #3729 introduces an unneeded extra function. 

Is there anything I can do to speed up this process? Like commiting to the existing pull-request. And if so is there a way to prevent this from waiting half a year for a new round of comments?

**Comment by pv** [comment]
The technical approach of gh-3634, just adding a new option to `_minimize_neldermead` and making minimal code changes in the function body, and the more explicit simplex parameterization of gh-3729 seems to me the right thing. The user probably understands that the initial simplex overrides a specified value of x0.

A new PR along those lines could get the ball rolling again. I'm not sure if any volunteer-only open source project has solved the problem of long patch backlogs, but at least 30+ PRs were merged last week.

**Comment by rgommers** [comment]
> (If an issue is not the way to raise a discussion, my apologies. It appears the link to the mailinglist on the main page is broken)

You mean the lists here right: http://scipy.org/scipylib/mailing-lists.html? The mail server was under spam attack a few days ago, it normally works fine. The scipy-dev list would normally be the right channel, but this works too.

**Comment by andyfaff** [comment]
Sorry, should've closed it... should this be added to the release notes?
