### ISSUE TITLE
TESTS: Some tests have shebangs 

### ISSUE THREAD

**Issue by FRidh** [scipy/scipy#5871]
Some tests have shebangs. Many don't. Is there a particular reason for this? Just convenience so you don't have to type `python test_foo.py`? Or just because it once was like that?
https://github.com/scipy/scipy/blob/master/scipy/linalg/tests/test_lapack.py

**Comment by rgommers** [comment]
I think it was there for convenience, but it's used rarely and so wasn't added to newer test files. Doesn't matter too much either way, although consistency is always nice.

**Comment by pv** [comment]
Answered, so closing --- not an issue that needs to be necessarily tracked.
