### ISSUE TITLE
DeprecationWarnings in signaltools on python 3.5

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#5874]
Running scipy tests on python 3.5 throws a bunch of these warnings:

```
/home/br/repos/scipy/build/testenv/lib/python3.5/site-packages/scipy/signal/signaltools.py:1899: DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.
  g_ = gcd(up, down)
```

`git blame` indicates ab803339 which went in as a part of https://github.com/scipy/scipy/pull/5749. 

@Eric89GXL, any suggestions?

**Comment by Eric89GXL** [comment]
Argh, Py35 issue. I'll have to look into whether six provides a wrapper, or
if we need to triage based on version manually (unless there is an
equivalent gcd in math on 2.7), unless someone has a better idea.

**Comment by rgommers** [comment]
It's not in ``six``. Just 

    if sys.version_info[0] < 3:
        from fractions import gcd
    else:
        from math import gcd

in signaltools.py should do the job.

**Comment by udiboy1209** [comment]
I'd like to contribute :)

**Comment by Eric89GXL** [comment]
Feel free to open a PR of you have time, I haven't started on it yet
