### ISSUE TITLE
Row-wise multiplication for sparse matrices

### ISSUE THREAD

**Issue by hlin117** [scipy/scipy#5881]
#It would be nice if row-wise multiplication was implemented for sparse arrays. For example, this works for normal, numpy arrays:

```
>>> import numpy as np
>>> arr1 = np.array([[0, 0, 1], [1, 0, 1], [0, 1, 0]])
>>> arr2 = np.array([1, 2, 3]).reshape(-1, 1)
>>> arr1 * arr2
array([[0, 0, 1],
       [2, 0, 2],
       [0, 3, 0]])
```

As soon as you bring out sparse matrices though, you have different results:

```
>>> from scipy.sparse import coo_matrix
>>> arr1 = coo_matrix([[0, 0, 1], [1, 0, 1], [0, 1, 0]])
>>> arr2 = np.array([1, 2, 3]).reshape(-1, 1)
>>> arr1 * arr2
array([[3],
       [4],
       [2]])
```

This is an API change. But it would be nice to see some consistency between numpy array operations and scipy sparse array operations.

**Comment by jaimefrio** [comment]
`*` triggers matrix multiplication, you want to use the sparse array's `.multiply()` method, i.e.:

```
>>> arr1.multiply(arr2)
matrix([[0, 0, 1],
        [2, 0, 2],
        [0, 3, 0]])
```

I'm closing this, but feel free to reopen or comment if the answer is unclear.

**Comment by hlin117** [comment]
Wow that's interesting, I didn't know this method existed, thanks for showing me.

On a related note, I tried `np.multiply(arr1, arr2)` and got some weird results:

```
>>> np.multiply(arr1, arr2)
>>>
array([[ <3x3 sparse matrix of type '<type 'numpy.int64'>'
	with 4 stored elements in COOrdinate format>],
       [ <3x3 sparse matrix of type '<type 'numpy.int64'>'
	with 4 stored elements in COOrdinate format>],
       [ <3x3 sparse matrix of type '<type 'numpy.int64'>'
	with 4 stored elements in COOrdinate format>]], dtype=object)
```

I think that's undesired behavior.

**Comment by thomasahle** [comment]
@hlin117 This seems to be because numpy doesn't really understand scipy matrices. They just consider them regular python objects. I'm not sure they have any plans to change this.
