### ISSUE TITLE
Sparse implementation of argmax would be useful

### ISSUE THREAD

**Issue by jimmycallin** [scipy/scipy#5883]
Currently, there is no argmax implementation for sparse matrices, and after studying the code of the dense argmax implementation, I couldn't figure out a non-trivial way to implement it myself. 

I asked this question on StackOverflow about half a year ago, which lead to a potentially useful answer: http://stackoverflow.com/questions/30742572/argmax-of-each-row-or-column-in-scipy-sparse-matrix

Thanks for Scipy, by the way!

**Comment by perimosocordiae** [comment]
I agree that a sparse argmax would be useful. The SO responses look like fairly good starting points.

**Comment by jimmycallin** [comment]
@perimosocordiae Yay, thanks!!!
