### ISSUE TITLE
silence DeprecationWarnings in scipy.special

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#5884]
There's several of 

```
/home/br/virtualenvs/scipy/lib/python3.5/site-packages/numpy/lib/utils.py:139: DeprecationWarning: `sph_yn` is deprecated!
scipy.special.sph_yn is deprecated in scipy 0.18.0. Use scipy.special.spherical_yn instead. Note that the new function has a different signature.
  warnings.warn(depdoc, DeprecationWarning)
```

A fix should be to filter out the warnings in the tests, similar to https://github.com/scipy/scipy/issues/5877

**Comment by maniteja123** [comment]
Just a doubt, when I run ``python runtests.py`` none of these DeprecationWarning showed up. Also, when the new vectorized special functions were added, they seem to be filtered in the tests in special.
