### ISSUE TITLE
DeprecationWarnings in stats on python 3.5

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#5885]
```
/home/br/repos/scipy/build/testenv/lib/python3.5/site-packages/scipy/stats/tests/test_stats.py:101: DeprecationWarning: Please use assertRaisesRegex instead.
```

Apparently, `assertRaisesRegexp` was renamed to `assertRaisesRegex`:  https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaisesRegexp

**Comment by maniteja123** [comment]
Would it be better to check the version of python and then call the new function ?

**Comment by ev-br** [comment]
`np.testing.assert_raises_regex` seems to fit the bill (I did not check anything other than `from numpy.testing import assert<TAB>` in IPython)

**Comment by maniteja123** [comment]
Thanks, Indeed the function ``np.testing.assert_raises_regex`` seems to handle this deprecation change across python versions.

**Comment by yash14123** [comment]
@maniteja123 Can you help me understand the problem here? I didn't quite get it. I wish to fix this.

**Comment by maniteja123** [comment]
Hi, the function ``assertRaisesRegexo`` was renamed to ``AssertRaisesRegex`` in Python 3.5 and raises a DeprecationWarning when used. The numpy util function ``np.testing.assert_raises_regex`` seemed to be checking for version of python and call the appropriate function. So if we use this function [here](https://github.com/scipy/scipy/blob/master/scipy/stats/tests/test_stats.py#L100) the DeprecationWarning will be silenced when the tests are run. Hope it helps !
