### ISSUE TITLE
 #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"

### ISSUE THREAD

**Issue by datomnurdin** [scipy/scipy#5889]
I got this error message when trying to install Scipy via command line on Centos 7

```
sudo easy_install scipy
```

Error message

```
In file included from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1728:0,
                 from /usr/lib64/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from scipy/sparse/sparsetools/sparsetools.h:5,
                 from scipy/sparse/sparsetools/csr.cxx:4:
/usr/lib64/python2.7/site-packages/numpy/core/include/numpy/npy_deprecated_api.h:11:2: warning: #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
  ^
```

Please advice. Thank you.

**Comment by rgommers** [comment]
That's not an error message but a warning.

**Comment by rgommers** [comment]
And please don't install with ``sudo``. Or use ``easy_install`` - we don't support that (although it should work), use ``pip``.

**Comment by datomnurdin** [comment]
BTW it's not responding after a few hours..

**Comment by rgommers** [comment]
> BTW it's not responding after a few hours..

Compiling ``sparsetools`` is extremely slow, and takes a lot of memory. With 2 Gb it can easily take half an hour, depending on cpu etc. Do you just have an old computer with little memory?

**Comment by 2sn** [comment]
I see the same message for some of my codes - what does trigger it, how can track this down (not clear to me from the message), and how to fix it?

**Comment by rgommers** [comment]
It's triggered by default if you include numpy. To remove the build warnings, you have to 

1. Remove deprecated macros if you use those (see https://github.com/numpy/numpy/blob/master/tools/replace_old_macros.sed)
2. define ``NPY_NO_DEPRECATED_API``. For an example, see https://github.com/scipy/scipy/blob/master/scipy/signal/setup.py#L19

**Comment by jxmorris12** [comment]
This bug is still a problem.

**Comment by rgommers** [comment]
It's not a bug, it's a harmless compile warning.

**Comment by 2sn** [comment]
Unfortunately it floods [i]python screen output.

**Comment by rgommers** [comment]
It's a compile time warning, you should never see that in ipython. If you do, can you please open a new issue with a reproducible example?

**Comment by MaximusIndus** [comment]
Well i guess it also leads to gcc failure -

talib/_ta_lib.c:254597: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__Pyx_PyInt_As_TA_RangeType'
    error: command 'gcc' failed with exit status

**Comment by ekhaydarov** [comment]
@quantum6 where would that need to be placed?

**Comment by CubeSatboi** [comment]
Yes can someone please respond to ekhaydarov, would be helpful for many people I'm sure

**Comment by rgommers** [comment]
1. It is a warning only as I said above
2. If GCC is erroring on it, that's either because you're compiling SciPy with `-Werror` or because somehow you're trying to compile some code that does use the deprecated API
3. you can disable it by setting the `NPY_NO_DEPRECATED_API` environment variable to `0`.
4. the SciPy build output itself can only be completely cleaned up once Cython only uses non-deprecated API. that should be in the next main release, Cython 3.0

**Comment by rgommers** [comment]
and if you are getting a SciPy build failure for a normal build (`python setup.py install` or equivalent), please open a new issue and provide details to reproduce (OS, compilers, etc.).

**Comment by wstkisters** [comment]
> @quantum6 where would that need to be placed?

Pass define_macros=[("NPY_NO_DEPRECATED_API", "NPY_1_7_API_VERSION")] as an option to the distutils.extension.Extension constructor in your setup.py

**Comment by quantum6** [comment]
https://blog.csdn.net/quantum7/article/details/86574189
ignore chinese, you kan read code and modify.
