### ISSUE TITLE
Undefined behavior when using scipy.interpolate.RegularGridInterpolator for 1-point axes?

### ISSUE THREAD

**Issue by brendan-k-wells** [scipy/scipy#5890]
I think I've found some undefined behavior in scipy.interpolate.RegularGridInterpolator. When defining the set of points, if one of the axes has only a single value in the array, the results of a linear interpolation are all "nan". For instance:

```
import numpy as np
from scipy.interpolate import RegularGridInterpolator

def f(x,y):
    return x+y

x = np.linspace(1, 1, 1)
y = np.linspace(1, 10, 10)
data = f(*np.meshgrid(x, y, indexing='ij', sparse=True))

my_interpolating_function = RegularGridInterpolator((x, y), data)
print my_interpolating_function(np.array([[1,1], [1,5], [1,10]]))
```

returns
`[ nan  nan  nan]`
The results of a nearest neighbor interpolation is _not_ a series of `nan`s for reasons described below:

```
...
print my_interpolating_function(np.array([[1,1], [1,5], [1,10]]), method='nearest')
```

returns
`[  2.   6.  11.]`

I believe this behavior is caused by a line in RegularGridInterpolator._find_indices (1743 in my version):

```
...            
                      norm_distances.append((x - grid[i]) /
                                  (grid[i + 1] - grid[i]))
...
```

If there is only one element in the grid array, then an `nan` is appended to `norm_distances`. For the linear interpolation, the value of `nan` is used to compute the weight of each index, which propagates through the code. For the nearest neighbor interpolation, the `nan` is compared against `0.5`, automatically returning `False`, which always chooses the `i+1` index.

I don't know what's the best resolution, but a few ideas occur to me: The code could have a special case for 1-point axes and return a number based on interpolation among the other ones. Or, if users aren't supposed to pass 1-point axes, an exception could be thrown. If nothing else, this behavior could be documented.

Hope that makes sense. Thanks!

**Comment by emerilin** [comment]
It seems this is [here](https://github.com/scipy/scipy/blob/b2eea7c5f81d114957a67cb462749a45bb1703b4/scipy/interpolate/interpolate.py#L2296) in the latest version.

I have an idea for implementing solution 1 in my final paragraph, if you're interested in that approach.

**Comment by rgommers** [comment]
To me this looks like the expected behavior; it's consistent with how other linear interpolators behave.

A grid with an axis of size 1 still works with ``method='nearest'`` as you show above, so raising an error is probably not the best idea. I'd vote for documenting: adding a note to the ``Notes`` section or a small example.

**Comment by ev-br** [comment]
I agree, it's not undefined even if not very useful behavior.

Raising an error wouldn't be very useful either IMO. If there is a way to fix this corner case without complicating the internals too much, I personally would not be opposed to making it skip length-1 axes. Otherwise, documenting the status quo would be nice.

**Comment by pv** [comment]
Strictly speaking, it's extrapolation. The rectangulargridinterpolator appears to extrapolate by default when bounds_error=False, and there's a relatively simple extension to extrapolation in this case.

So the size-1 dimensions could also be special cased in _find_indices, probably by just setting the corresponding norm_distance value to 0.
