### ISSUE TITLE
CJY01:: possible bugs J0/J0' in asymptotic expansion

### ISSUE THREAD

**Issue by gaming-hacker** [scipy/scipy#5896]
i compared this with my own routine and A&S and online calculator.  it appears the asymptotic expansion is incorrect. J0 and J0', complex arg.

can someone else verify the results.  i'll mine after so the results are biased.
inputs
argZ (-10.00000000000000  -10.00000000000000*I)
argZ (-10.00000000000000  -1.00000000000000*I)
argZ (20.00000000000000 + 20.00000000000000*I)
argZ (40.00000000000000 + 40.00000000000000*I)

**Comment by pv** [comment]
Please paste the results that you got and think are incorrect.
I do not see any error at those points.

**Comment by pv** [comment]
Perhaps you mean that the CJY01 routine from specfun.f gives wrong results
--- that can indeed be the case. However, this routine is not used in Scipy, the complex values are computed by via the amos rotutines.

**Comment by pv** [comment]
Closing because cjy01 is unused routine --- please reopen if I understood wrong.
