### ISSUE TITLE
Order of convolve inputs shouldn't matter

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#5897]
Reading through https://github.com/scipy/scipy/pull/5608 I noticed that the docstring still says "if sizes of `in1` and `in2` are not equal then `in1` has to be the larger array", but [convolution is commutative](https://en.wikipedia.org/wiki/Convolution#Properties), so it shouldn't matter at all which order the inputs are in, yet it does because it goes through `_check_valid_mode_shapes()`:

```
convolve([2, 3, 4, 5], [1], 'full')
Out[45]: array([2, 3, 4, 5])

convolve([1], [2, 3, 4, 5], 'full')
Out[46]: array([2, 3, 4, 5])

convolve([2, 3, 4, 5], [1], 'valid')
Out[47]: array([2, 3, 4, 5])

convolve([1], [2, 3, 4, 5], 'valid')
Traceback (most recent call last):
...
ValueError: in1 should have at least as many items as in2 in every dimension for 'valid' mode.
```

I changed this partially in https://github.com/scipy/scipy/pull/3664 but I guess the `swapped_inputs` logic should apply to the entire function, and drop the `valid` mode size check?

I don't see why this should restrict `correlate`, either.  I think `valid` mode still makes sense regardless of which input is larger?  The output is just reversed and conjugated if you swap the inputs?

**Comment by stsievert** [comment]
Hm, this doesn't make sense given `conv(a, b) == conv(b, a)`. This has been an issue I've run into the past and managed myself... I definitely wouldn't mind this being fixed!

**Comment by endolith** [comment]
Yeah I've thought about it and there's no reason why valid mode should care about the size of the inputs, for either convolve or correlate.  It's probably just a holdover from the original implementation that only worked with first bigger than last.

Should be:

- convolve([1, 2, 3], [4, 5], 'valid') == convolve([4, 5], [1, 2, 3], 'valid') == [13, 22]
- correlate([1, 2, 3], [4, 5], 'valid') == [14, 23]
- correlate([4, 5], [1, 2, 3], 'valid') == [23, 14]

**Comment by endolith** [comment]
@cournape added https://github.com/scipy/scipy/commit/14b1f164be0d92944a02d5853c25ea6264ff6131 in 2009 which says 

> 'valid' mode if b.size > a.size does not make sense with the new behavior

Is there some argument against this that I'm missing?

```
convolve(ones(4), ones(2), 'valid') == [2, 2, 2]
convolve(ones(2), ones(4), 'valid') == [2, 2, 2]

convolve(ones((4,5)), ones((2,3)), 'valid') == 
      [[ 6.,  6.,  6.],
       [ 6.,  6.,  6.],
       [ 6.,  6.,  6.]]

convolve(ones((2,3)), ones((4,5)), 'valid') == 
      [[ 6.,  6.,  6.],
       [ 6.,  6.,  6.],
       [ 6.,  6.,  6.]]

correlate(ones(3,2), ones(2,3), 'valid') == [] or raise an exception
correlate(ones(2,3), ones(3,2), 'valid') == [] or raise an exception
```

I changed this test in https://github.com/endolith/scipy/commit/ad088e09eab8aee7424cc22de36f5fdcd853c61a
