### ISSUE TITLE
interpolate.interp1d crashes using float128

### ISSUE THREAD

**Issue by kaufman** [scipy/scipy#5898]
this seems to be a consequence of using np.interp in 0.17.0
0.16 doesn't have this issue.

**Comment by ev-br** [comment]
Thanks for the report. 

Indeed, here's a regression of 0.17.0:

```
In [15]: x = np.arange(10, dtype=np.float128)

In [16]: y = x**2

In [17]: i = interp1d(x, y)

In [18]: i(1.0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)

<...snip...>
interp(x, xp, fp, left, right, period)
   1269             return compiled_interp([x], xp, fp, left, right).item()
   1270         else:
-> 1271             return compiled_interp(x, xp, fp, left, right)
   1272     else:
   1273         if period == 0:

TypeError: Cannot cast array data from dtype('float128') to dtype('float64') according to the rule 'safe'
```

If you get an actual crash, please share a reproducible example. 

To fix it, one would probably need to add an extra condition to 
https://github.com/scipy/scipy/blob/master/scipy/interpolate/interpolate.py#L467

Would you be interested in submitting a PR with the fix @kaufman ?

**Comment by rgommers** [comment]
@ev-br I've created the ``0.17.1`` milestone, so we can add any regressions to that. Doesn't mean we have to make that release, but experience shows that we probably will:)

**Comment by kaufman** [comment]
You're correct. "crash" was a bit hyperbolic. I get the same exception. I'll let those more familiar with the code handle the patch.

**Comment by ev-br** [comment]
Thanks Ralf. I agree it's about time we start collecting candidates for the point release. I'll mark some more :-)

**Comment by ev-br** [comment]
@kaufman  Could you check that https://github.com/scipy/scipy/pull/5902 fixes the issue for you?

**Comment by weiguangcui** [comment]
The same issue is showing up in `_fitpack._spl_()` function when I do `spline()` a np.float128 array:
```
File ~/.local/lib/python3.8/site-packages/scipy/interpolate/_fitpack2.py:380, in UnivariateSpline.__call__(self, x, nu, ext)
    378     except KeyError as e:
    379         raise ValueError("Unknown extrapolation mode %s." % ext) from e
--> 380 return _fitpack_impl.splev(x, self._eval_args, der=nu, ext=ext)

File ~/.local/lib/python3.8/site-packages/scipy/interpolate/_fitpack_impl.py:591, in splev(x, tck, der, ext)
    589 shape = x.shape
    590 x = atleast_1d(x).ravel()
--> 591 y, ier = _fitpack._spl_(x, der, t, c, k, ext)
    593 if ier == 10:
    594     raise ValueError("Invalid input data")

TypeError: Cannot cast array data from dtype('float128') to dtype('float64') according to the rule 'safe'
```

**Comment by weiguangcui** [comment]
Should I open a new issue?

**Comment by ev-br** [comment]
Please do.
