### ISSUE TITLE
Suboptimal convergence of Halley's method?

### ISSUE THREAD

**Issue by Juanlu001** [scipy/scipy#5922]
While trying out the Halley's method added in #20, I think I have found that the current implementation does not reach cubic convergence.

(_Note: This is a WIP issue, since I admit that this example is [by no means short or self-contained](http://sscce.org/), but I am willing to provide a better example and narrow down the issue as soon as I meet a couple of deadlines_)

This is the code I'm testing:

https://github.com/Juanlu001/poliastro/blob/6483c27/src/poliastro/iod/izzo.py#L174-L210

And this is the program I'm using:

``` python
from poliastro.iod import izzo

def main(M, x_ref, ll_ref):
    T_ref = izzo._tof_equation(x_ref, 0.0, ll_ref, M)
    print(M, T_ref)
    for ii in range(1, 8):
        try:
            x, _ = next(izzo._find_xy(ll_ref, T_ref, M, numiter=ii, rtol=1e-30))
        except RuntimeError as e:
            x = float(e.args[0].split()[-1])
            print(ii, x_ref, x, (x - x_ref) / x_ref)

if __name__ == '__main__':
    main(1, -0.24, 0.5)
```

When using the available SciPy implementation, these are the results. Notice that the last column is the relative error with respect to the known solution:

```
$ python convergence.py
1 5.58044804471
1 -0.24 -0.4031436981968586 0.6797654091535775
2 -0.24 -0.1769754549412486 -0.2626022710781308
3 -0.24 -0.2404985599237051 0.0020773330154380083
4 -0.24 -0.2399999996742607 -1.3572470693630953e-09
5 -0.24 -0.2400000000000002 9.251858538542972e-16
```

And with [the formula from Wikipedia](https://en.wikipedia.org/wiki/Halley's_method#Method), these are the results:

```
$ python convergence.py
1 5.58044804471
1 -0.24 -0.265113577401703 0.10463990584042918
2 -0.24 -0.240021887866687 9.1199444529159e-05
3 -0.24 -0.240000000000016 6.672902970924119e-14
4 -0.24 -0.2400000000000002 9.251858538542972e-16
```

I guess the last iteration is subject to truncation error.

**Comment by pv** [comment]
It's a different Halley method, https://de.wikipedia.org/wiki/Halley-Verfahren

I'm not sure if you can say much about cubic convergence based on 4 data points, but otoh I did not go through the derivation in detail. The negative discriminant handling may be ad hoc.

**Comment by Juanlu001** [comment]
In principle both are cubic, so they should exhibit similar behavior. I don't know how to obtain more information in double precision since the values go to zero very quickly, I am open to suggestions.

**Comment by pablogsal** [comment]
Puedes calcular el resto de Lagrance y ver que es de orden 4º: 
http://mathworld.wolfram.com/LagrangeRemainder.html

Quizá necesites el teorema del valor medio para evaluarlo, pero al menos te da una idea de si esta convergiendo a 3º orden.

**Comment by mikofski** [comment]
address in #8357 use [traditional Halley's form](https://en.wikipedia.org/wiki/Halley%27s_method)

    dx = - 1 / (fder / fval - fder2 / fder / 2) = - 2 * fval * fder / (2 * fder ** 2 - fval * fder2)

where the latter version avoids overflow issues
