### ISSUE TITLE
ImportError: No module named ndimage

### ISSUE THREAD

**Issue by ashirsat** [scipy/scipy#5923]
I am trying to import ndimage from spicy like
`from scipy import ndimage`

it gives me an error stating that 

> Import Error: No module named ndimage

Please let me know how to resolve this issue

**Comment by rgommers** [comment]
Your install is incomplete or somehow messed up. You can see where scipy is installed with::

    >>> import scipy
    >>> scipy.__file__

Complete reinstallation may fix it. Please provide details on how you installed if you need more help

**Comment by ashirsat** [comment]
`import scipy
>>> scipy.__file__
'/usr/local/lib/python2.7/site-packages/scipy/__init__.pyc'`

I see that scipy is installed in the correct location.

I installed scipy using ports

`sudo port install py27-scipy`
