### ISSUE TITLE
scipy.ndimage.rotate() creates values outside input range

### ISSUE THREAD

**Issue by makeyourownneuralnetwork** [scipy/scipy#5925]
I am using the scipy.ndimage.rotate() functions to rotate bumpy arrays. These arrays are in fact bitmaps of the well-known MNIST data set.

I have noticed that the resultant array has values that out outside the range of the original array.

The following python notebook at github shows this:
[https://github.com/makeyourownneuralnetwork/makeyourownneuralnetwork/blob/master/part2_mnist_data_set_with_rotations.ipynb](https://github.com/makeyourownneuralnetwork/makeyourownneuralnetwork/blob/master/part2_mnist_data_set_with_rotations.ipynb)

You can see the input array had a range **0.01 to 1.00**. You can then see that the rotated image has values as low as **-0.095 and as high as 1.173**.

This seem quite wrong!

I can understand that the underlying operations involve interpolation - but this would result in values amongst the existing values, not above or below.

I had a quick look at the source code but my skills are not high enough to spot the core problem.

**Comment by pv** [comment]
What you are expecting is *monotonic* interpolation. Many image interpolation methods however are not monotonic --- eg. bicubic splines are not. With scipy.ndimage, use bilinear interpolation if you require monotonicity.

**Comment by makeyourownneuralnetwork** [comment]
thanks
