### ISSUE TITLE
unicode vs. string comparison in scipy.stats.binned_statistic_dd

### ISSUE THREAD

**Issue by lzkelley** [scipy/scipy#5927]
I'm getting an error where `scipy.stats.binned_statistic_dd` isn't recognizing that the `statistic` parameter I'm passing is 'count' [when it does the string comparison](https://github.com/scipy/scipy/blob/master/scipy/stats/_binned_statistic.py#L469).

I'm assuming this has something to do with a `unicode` vs. `str` type issue --- I'm using python2.7 with `from __future__ import unicode_literals`.  Should this be changed to an equality comparison?  i.e.

    if(statistic != 'count' and Vlen != Dlen):

instead of 

    if(statistic is not 'count' and Vlen != Dlen):

**Comment by Eric89GXL** [comment]
My understanding is that you shouldn't use "is" but "==" for string
comparisons for this sort of thing, yeah.

**Comment by andyfaff** [comment]
@lzkelley, this is addressed in #5935. Do you have a test for this?
