### ISSUE TITLE
faster implementation of ks_2samp

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#5936]
It is possible to improve the performance of `scipy.stats.ks_2samp` by cythonizing the loop, rather than by relying on (a slightly wasteful) searchsorted.

Not making a PR, mostly because I see that in the same package, `vonmises_cython` has its C source mentioned in `setup.py` rather than relying e.g. on `cythonize`, and I'm a bit lazy to figure out how exactly to modify `setup.py`.  Feel free to adopt the code and make a PR out of it.

`_stats.pyx`
```
#cython: boundscheck=False
#cython: nonecheck=False
#cython: wraparound=False
#cython: cdivision=True
from libc cimport math


ctypedef fused real:
    short
    int
    long
    float
    double


cpdef double ks_2samp(real[:] data1, real[:] data2):
    cdef:
        size_t i = 0, j = 0, n1 = data1.shape[0], n2 = data2.shape[0]
        real d1i, d2j
        double d = 0, maxd = 0, inv_n1 = 1. / n1, inv_n2 = 1. / n2
    while i < n1 and j < n2:
        d1i = data1[i]
        d2j = data2[j]
        if d1i <= d2j:
            d += inv_n1
            i += 1
        if d1i >= d2j:
            d -= inv_n2
            j += 1
        maxd = max(maxd, math.fabs(d))
    return maxd
```

`stats.py`
```
diff --git a/scipy/stats/stats.py b/scipy/stats/stats.py
index 88a8a40..2bff88b 100644
--- a/scipy/stats/stats.py
+++ b/scipy/stats/stats.py
@@ -4363,10 +4363,8 @@ def ks_2samp(data1, data2):
     data2 = np.sort(data2)
     n1 = data1.shape[0]
     n2 = data2.shape[0]
-    data_all = np.concatenate([data1, data2])
-    cdf1 = np.searchsorted(data1, data_all, side='right') / (1.0*n1)
-    cdf2 = np.searchsorted(data2, data_all, side='right') / (1.0*n2)
-    d = np.max(np.absolute(cdf1 - cdf2))
+    from . import _stats
+    d = _stats.ks_2samp(data1, data2)
     # Note: d absolute not signed distance
     en = np.sqrt(n1 * n2 / float(n1 + n2))
     try:
```
Note that this will break code that tries to run `ks_2samp` on ndarrays with non-real but still orderable dtype (e.g. complexes or strings), but given that that was returning nonsensical results before, I think that's not an issue.

A quick test by hand suggests a ~33% performance gain on arrays of size ~10^4-10^5.

**Comment by pv** [comment]
You can just plop the pyx file in the directory and refer to the .c file in setup.py.
It will be magically generated.

**Comment by ev-br** [comment]
Done in gh-5938, closing.
