### ISSUE TITLE
killed by the optimization function

### ISSUE THREAD

**Issue by rylanchiu** [scipy/scipy#5950]
I have a data set including more than 200,000 ratings, 20,000 users and 4,000 items. I aggregate it to a sparse matrix and assign the value where is `nan` to the average value(as the tutorial of pymc3 said). And then I tried to optimize the latent attributes of matrix `U` and `V` with the `find_map` function provided by Scipy. But no matter which function I used(BFGS, L-BFGS, NEWTON, etc), it is killed on the half way:

    [1]    44043 killed     python pmf2.py

Could you please tell me how to deal with this problem? To reduce the use of computation resource? I am using os x 10.10 and my computer has 16GB ram. Thank you in advance!

**Comment by andyfaff** [comment]
Unfortunately you're not really providing enough details for us to help you. Perhaps post a link to the pmf2.py and someone may be able to look at it.

**Comment by rylanchiu** [comment]
@andyfaff  here is the pmf2.docx. Thanks!
[Uploading pmf2.docx…]()

**Comment by andyfaff** [comment]
Please post a link to a gist of the python script, not a link to a doc file

**Comment by rylanchiu** [comment]
@andyfaff https://gist.github.com/macks22/00a17b1d374dfc267a9a

**Comment by andyfaff** [comment]
That looks pretty complicated. Is that the smallest piece of code that can reproduce the problem? I might defer to others who can delve into it.

**Comment by dlax** [comment]
@rylanchiu your problem indeed looks fairly complex. Maybe try using a debugger or profile your code to get more details. It's not even clear that this is a problem in scipy.

**Comment by pv** [comment]
It's fmin_powell, which is pure-Python. Closing (unlikely to be a scipy bug, and no repro).
Feel free to continue discussion though, or reopen if more info appears.

**Comment by rylanchiu** [comment]
@pv  Thanks for reply! But I have changed to `scipy.optimize.fmin_l_bfgs_b`, the problem still exists. How can I solve it? Thanks a lot!
