### ISSUE TITLE
Massive performance regression in cKDTree.query with L_inf distance in scipy 0.17

### ISSUE THREAD

**Issue by segasai** [scipy/scipy#5953]
Hi,

While running some of my own code, I noticed a major slowdown in scipy 0.17 which I tracked to the cKDtree.query call with L_inf distance.
I did a git bisect and tracked the commit that caused the issue -- the commit is :
58a10c2688398ab440de8d6d7b5fba29671df182
Here is the example program that finishes in ~ 10 seconds before this commit and pretty much never finishes after it
```
import scipy.spatial.ckdtree
import numpy as np
arr1 = np.random.uniform(size=(6000000, 3))
tree2 = scipy.spatial.ckdtree.cKDTree(arr1)
distances, ind = tree2.query(arr1, 1, p=np.inf)
```
I also checked that if I change the distance from L_inf to L_2, then program finishes pretty quickly. I also tried to stop the program with gdb a few times to see where the code is mostly spending the time on and it seems to be here scipy/spatial/ckdtree/src/query.cxx:311. I also tried to dig into the problematic commit but I don't know enough about ckdtree internals to suggest a patch. 

Thanks, 
 Sergey

If relevant, I'm seeing this issue on a both systems that I tried  64bit RHEL6.7 with gcc 4.4 and Debian 7.9 with gcc-4.7. In all the cases it is python 2.7

**Comment by ev-br** [comment]
cc @sturlamolden @rainwoodman

**Comment by sturlamolden** [comment]
The commit in question is the one that adds periodic space query. 

Line 311 was not in that commit, and there is no way cKDTree is spending most of its time on a ```__builtin_prefetch```.

**Comment by ev-br** [comment]
I suspect a reproducible examle might help.The OP does not seed the random number generator, are you comparing the runs on the same dataset?

**Comment by segasai** [comment]
@ev-br 
The original example that I was preparing for the bug report had a fixed dataset, but then I discovered that the same problem happens on random datasets of similar size (~ 6 million points in 3D). And as far as I am aware the regression is easily reproducable. I've just tried the example that I gave on my laptop (i didn't check it before)(gcc 4.6 64bit Ubuntu 12.04), and with scipy-0.17 my test program didn't finish after 2 min, while with scipy-0.16.1 it finished in ~ 30 seconds.  
And obviously the problem persists if I stick np.random.seed(1) in the program -- so it is not related to a particularly weird point distribution.

**Comment by segasai** [comment]
@sturlamolden 
The fact that the line 311 wasn't part of the commit doesn't prove anything, as the periodic boundary commit did make several changes that specifically dealt with p=np.inf case (and there is no doubt that that the offending commit was 58a10c2 as I did git bisect). And if it helps here is the typical gdb backtrace that I encounter when try to stop the running process

```
#0  0x00007fd3c8969ad8 in point_point (k=0, y=0x7fd3be25ef58, 
    x=0x7fd3c3898e08, tree=<optimized out>)
    at scipy/spatial/ckdtree/src/distance.h:21
#1  distance_p (upperbound=-0, k=3, y=0x7fd3be25ef58, x=0x7fd3c3898e08, 
    tree=<optimized out>, p=<optimized out>)
    at scipy/spatial/ckdtree/src/distance.h:180
#2  query_single_point<BaseMinkowskiDistPinf<Dist1D> > (
    self=self@entry=0x7fd3c6dfa118, result_distances=0x7fd3b86d0528, 
    result_indices=0x7fd3b5909528, x=x@entry=0x7fd3be25ef58, k=k@entry=1, 
    eps=6.9439620697216583e-310, eps@entry=0, p=p@entry=inf, 
    distance_upper_bound=-0, distance_upper_bound@entry=inf)
    at scipy/spatial/ckdtree/src/query.cxx:311
#3  0x00007fd3c89728ee in query_knn (self=0x7fd3c6dfa118, dd=0x7fd3b86d0010, 
    ii=0x7fd3b5909010, xx=<optimized out>, n=6000000, k=1, eps=0, p=inf, 
    distance_upper_bound=inf) at scipy/spatial/ckdtree/src/query.cxx:511
```
...

The reason I mentioned the line 311 is that it seems to be in the part of code that is commented as /* brute force */ which I thought probably points at the cause of the problem (just IMO)

**Comment by sturlamolden** [comment]
Oh, sorry. In 0.17 L311 is the distance function, not the prefetch, which makes more sence. It did change to use C++ templates instead of a conditional branch on L_p. Replacing millions of conditional branches with nothing should not make the code slower. That is, unless there is something with your compiler that prevents it from inlining the template code.

**Comment by segasai** [comment]
@sturlamolden No problem.
I think the compiler theory is also unlikely, given that I see the same issue with at least 3 different compilers (gcc 4.4, 4.6 4.7). But also I think a lot of "templatisation" of scipy.spatial-0.17 happened after the 58a10c2 commit so it is not the cause of the problem

**Comment by sturlamolden** [comment]
It seems https://github.com/scipy/scipy/commit/58a10c2688398ab440de8d6d7b5fba29671df182 is slightly changing the logic for non-periodic queries, and for L_inf particularly. That might be the reason, but I don't know. We used templates to avoid this, but if not all of it is gone I will have to undo some of the changes made by @rainwoodman

**Comment by rainwoodman** [comment]
I feel sorry we didn't catch it with the benchmarks!

I wonder if this is as slow as in the current head. It should be fixable. I'll take a look!

**Comment by sturlamolden** [comment]
I am looking too, but I am not sure what it might be yet. Perhaps it is related to the side distances (note the difference in handling for L_inf).

**Comment by rainwoodman** [comment]
Interestingly, the periodic case is way faster than the non-periodic case for p=inf!

**Comment by rainwoodman** [comment]
Line 385:
```
                npy_float64 tmp = x[split_dim] - split;
                if(NPY_LIKELY(p == 2)) {
                    inf2->side_distances()[split_dim] = tmp * tmp;
                } else {
                    inf2->side_distances()[split_dim] = std::pow(dabs(tmp), p);
                }

```

**Comment by rainwoodman** [comment]
I think this is fixed. 

With 73bb048 p=inf and p=2 spends roughly the same amount of time. 

Shall we back port this? I am thinking of adding a new benchmark not have enough time right away.

**Comment by sturlamolden** [comment]
The original code had this:

```
           else if (p == infinity) {		
                 /*		
                  * we never use side_distances in the l_infinity case		
                  * so skip filling it in		
                  * inf2->side_distances[inode->split_dim] 		
                  *     = dabs(inode->split-x[inode->split_dim])		
                  */		
                 far_min_distance = dmax(min_distance, 		
                                         dabs(split-x[split_dim]));		
```
And then
```
            it2.priority = far_min_distance;		
```

**Comment by sturlamolden** [comment]
Ok, ```adjust_min_distance``` does the ```dmax``` operation now.

**Comment by sturlamolden** [comment]
I think https://github.com/scipy/scipy/commit/73bb048f8830b1228f6e6c1b22778a7488c54f94 looks correct.

**Comment by segasai** [comment]
I can confirm that  73bb048 fixes the problem for me as well. Thanks !

**Comment by rainwoodman** [comment]
@sturlamolden be aware -- I recall I didn't convert it to templates in the first round because the logic in query.cxx looked sufficiently different from other files.

**Comment by sturlamolden** [comment]
Sure, but I know how to fix it so I'll take care of it 😊

**Comment by sturlamolden** [comment]
I will just add a couple of const members to the template structs and use a conditional branch on those  instead of ```p``` and ```raw_boxsize_data```. The the compiler will optimize it away.

**Comment by sturlamolden** [comment]
@rainwoodman We need a PR for https://github.com/scipy/scipy/commit/73bb048f8830b1228f6e6c1b22778a7488c54f94 into scipy/master.

**Comment by rainwoodman** [comment]
I'm on it.

**Comment by rainwoodman** [comment]
Yes new PR at https://github.com/scipy/scipy/pull/5957
