### ISSUE TITLE
Complex conjugates in correlate()

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#5954]
I don't know when this was introduced, but there's a discrepancy in handling of complex conjugates in scipy 0.17.0:

```
    scipy.signal.correlate(1j, 2j)              (-2+0j)
    scipy.signal.correlate([1j], [2j])          array([ 2.+0.j])
    scipy.signal.correlate([[1j]], [[2j]])      array([[ 2.+0.j]])
    scipy.signal.correlate2d([[1j]], [[2j]])    array([[-2.+0.j]]) 
    numpy.correlate([1j], [2j])                 array([ 2.+0.j])
```

Wikipedia's definition of cross-correlation is:

![(f \star g)[n]\ \stackrel{\mathrm{def}}{=} \sum_{m=-\infty}^{\infty} f^*[m]\ g[m+n]](https://cloud.githubusercontent.com/assets/58611/13658199/d65369d4-e642-11e5-8276-145f57f8bba9.png)

which matches Wolfram's:

![[f*g](t)=int_(-infty)^inftyf^_(-tau)g(t-tau)dtau](https://cloud.githubusercontent.com/assets/58611/13658313/ed83fa96-e643-11e5-826b-f969c5a0ac2e.gif)

so this would mean conjugating the 1j into -1j and then multiplying it to get +2 as the correct output.

but then correlate(1j, 2) should equal 1j.conj() \* 2 = -1j \* 2 = -2j, which none of these agree with:

```
    scipy.signal.correlate(1j, 2)           2j
    scipy.signal.correlate([1j], [2])       array([ 0.+2.j])
    scipy.signal.correlate([[1j]], [[2]])   array([[ 0.+2.j]])
    scipy.signal.correlate2d([[1j]], [[2]]) array([[ 0.+2.j]])
    numpy.correlate([1j], [2])              array([ 0.+2.j])
```

**Comment by endolith** [comment]
Can someone run similar things in matlab and see which way it calculates?

**Comment by e-q** [comment]
MATLAB r2015b
```
> xcorr([1j, 0], [2j, 0])

ans =
     0     2     0

> xcorr([1j, 0], [2, 0])

ans =
  Column 1
                          0 +                     0i
  Column 2
                          0 +                     2i
  Column 3
                          0 +                     0i

> xcorr([1, 0], [2j, 0])

ans =
  Column 1
                          0 +                     0i
  Column 2
                          0 -                     2i
  Column 3
                          0 +                     0i
```
```
>> conv([1j, 0], [2j, 0])

ans =
    -2     0     0

>> conv([1j, 0], [2, 0])

ans =
  Column 1
                          0 +                     2i
  Column 2
                          0 +                     0i
  Column 3
                          0 +                     0i

>> conv([1, 0], [2j, 0])

ans =
  Column 1
                          0 +                     2i
  Column 2

                          0 +                     0i
  Column 3
                          0 +                     0i

```

**Comment by endolith** [comment]
So we can either change everything to match book definitions and become inconsistent with other software, or just change correlate 0d and correlate2d to make them consistent internally, and add Notes explaining the discrepancy

**Comment by Eric89GXL** [comment]
Any explanation from Octave or MATLAB docs about their convention?

**Comment by endolith** [comment]
They both define what they're doing, but don't give a reason why they swapped which input gets conjugated.

http://www.mathworks.com/help/signal/ref/xcorr.html#bubr0in
http://www.mathworks.com/help/signal/ref/xcorr2.html#buwgc15

I looked for refs and found one source that conjugates the second input:
http://web.eecs.umich.edu/~fessler/course/451/l/pdf/c2.pdf

And another that conjugates first:
http://www.ee.ic.ac.uk/hp/staff/dmb/courses/E1Fourier/00800_Correlation.pdf

but most book refs I found don't mention the conjugation at all, they deal only with real signals.

So I think it's fine to leave it as is, but fix scipy.signal.correlate 0d and correlate2d to be consistent, and explain the convention in the docstrings.

**Comment by Eric89GXL** [comment]
Agreed, it seems like they should at least be internally consistent.

**Comment by endolith** [comment]
Actually now that I look at this again, more carefully, all of the definitions I can find are equivalent, they just have minus or plus signs making them look different.  So correlate is correct for ND inputs, incorrect for 0d inputs, and correlate2d is incorrect. 

The complex conjugate exists to make sure the output is positive when the inputs have the same sign and the same imaginary sign.  So `correlate(3, 4)` should be positive, and `correlate(3j, 4j)` should also be positive.
