### ISSUE TITLE
ENH: expose scalar versions of scipy.special functions to cython

### ISSUE THREAD

**Issue by person142** [scipy/scipy#5964]
It would be nice to have access to the scalar versions of scipy's special functions from cython. One use case for this is any kind of series whose terms involve special functions already in scipy. The advantage of accessing the scalar functions directly is speed; for example consider adding the following (very silly) file to to special:

```cython
from _hyp0f1 cimport _hyp0f1_real # the raw cython function
from ._ufuncs import hyp0f1 # the scipy ufunc


def _hyp0f1_real_test():
   cdef int i
   for i in range(1000):
       _hyp0f1_real(1, 1e-8)

def hyp0f1_test():
    cdef int i
    for i in range(1000):
        hyp0f1(1, 1e-8)
```
The timings come out to be something like:
```
In [1]: from scipy.special import hyp0f1_test, _hyp0f1_real_test

In [2]: %timeit hyp0f1_test()
100 loops, best of 3: 2.5 ms per loop

In [3]: %timeit _hyp0f1_real_test()
10000000 loops, best of 3: 60.8 ns per loop
```

All the necessary data is already in ``generate_ufuncs.py``, so it shouldn't be too hard to generate cython code which exposes the scalar versions of the functions. By using fused types it should be possible to keep the ufunc and scalar interfaces similar.

If folks think this is a good idea I'd be happy to implement it.

**Comment by insertinterestingnamehere** [comment]
That sounds like a great idea to me. It looks like it would be a very helpful feature that would be reasonable to build and maintain.

**Comment by ev-br** [comment]
https://github.com/scipy/scipy/issues/3449 sounds related
