### ISSUE TITLE
sparse matrix documentation mixes `nnz` and `getnnz`

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#5981]
E.g. http://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.sparse.csr_matrix.html
In the Attributes section, one has:

> nnz	Get the count of explicitly-stored values (nonzeros) :Parameters: axis : None, 0, or 1 Select 
> between the number of values across the whole matrix, in each column, or in each row.

First, it seems to need the full stop after (nonzeros) to render correctly (same for `getnnz`). Second, the list of Parameters seems to duplicate the one for `getnnz`.

**Comment by perimosocordiae** [comment]
I believe this has been fixed in master, by 62fc5bb4742b529eba1dd52912c91bbaced19124.

**Comment by ev-br** [comment]
Indeed. Thanks for pointing this out!
