### ISSUE TITLE
Keyword collision in scipy.stats.levy_stable.interval

### ISSUE THREAD

**Issue by FlorianWilhelm** [scipy/scipy#5982]
If you check the [methods documentation](http://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.levy_stable.html#scipy.stats.levy_stable) of the Levy-stable continuous random variable you will see `interval(alpha, alpha, beta, loc=0, scale=1)`. The problem is here that the first parameter for `interval` itself is named `alpha` and in the case of the Levy-stable distribution the first shape parameter is also called `alpha`. This makes it really problematic if you use keyword arguments when calling `interval` for a user-selected distribution. The only way out of it is renaming the the first parameter of `interval` or maybe less breaking is renaming the shape parameters of `levy_stable`.

**Comment by ev-br** [comment]
An unintended consequence of retrofitting keyword args to distributions. Sigh. 
Given that both `interval` and `levy_stable` are quite esoteric, I'm wondering if it's not best to just add a cautionary note somewhere (levy_stable, likely).

**Comment by FlorianWilhelm** [comment]
@ev-br I am not sure the note would suffice since what happens if you write code that let's the user choose an arbitrary distribution from scipy.stats? That's how I found out about this collision. Why is ``interval`` esoteric? I use it to find out about the support of a distribution? Is there a better for to do so?

**Comment by rgommers** [comment]
As reported in gh-6920, ``ksone`` also has such an issue: ``moment(n, n, loc=0, scale=1)``.

**Comment by rgommers** [comment]
The normal use of ``levy_stable.interval`` and ``ksone.moment`` is not broken, you'd have to use an unusual style of calling these methods to get an exception.

Still, would be nice to have it fixed. Possible approach:

- write a test that parses the ``Methods`` section of all distribution docstrings and checks those for name collisions (there may be more that haven't been spotted yet).
- Rename the ``alpha`` parameter of ``levy_stable``.
- Rename the ``n`` parameter of ``ksone``.
- Add a note about backwards incompatible changes to the release notes.

**Comment by mdhaber** [comment]
@rgommers For the test that parses the Methods section, did you intend for this to be in the SciPy test suite or something we run offline? If in the test suite, how would you suggest going about parsing? (If offline, there are plenty of docstring parsing tools available.)

@bsdz Would it be OK to change the name of the `alpha` shape parameter for `levy_stable`?

**Comment by mdhaber** [comment]
This compares the shapes to the arguments of public methods, I think.
```python3
from numpydoc.docscrape import NumpyDocString
from scipy.stats._distr_params import distcont, distdiscrete
from scipy import stats

distnames = set(distdata[0] for distdata in distcont)
methods = ('rvs, pdf, logpdf, cdf, logcdf, sf, logsf, ppf, isf, moment, '
           'stats, entropy, expect, median, mean, std, var, interval, '
           '__call__, fit, fit_loc_scale, nnlf, support').split(', ')
for distname in distnames:
    for methodname in methods:
        dist = getattr(stats, distname)
        method = getattr(dist, methodname)
        try:
            params = NumpyDocString(method.__doc__)['Parameters']
        except TypeError as e:
            print(f"I'm having trouble with {distname}.{methodname}")
        param_names = set(param.name for param in params)

        if not dist.shapes:
            continue
        shape_names = dist.shapes.split(', ')
        intersection = param_names.intersection(shape_names)
        if intersection:
            print(distname, methodname, intersection)

distnames = set(distdata[0] for distdata in distdiscrete)
methods = ('rvs, pmf, logpmf, cdf, logcdf, sf, logsf, ppf, isf, moment, '
           'stats, entropy, expect, median, mean, std, var, interval, '
           '__call__, support').split(', ')
for distname in distnames:
    for methodname in methods:
        dist = getattr(stats, distname)
        method = getattr(dist, methodname)
        try:
            params = NumpyDocString(method.__doc__)['Parameters']
        except TypeError as e:
            print(f"I'm having trouble with {distname}.{methodname}")
        param_names = set(param.name for param in params)

        if not dist.shapes:
            continue
        shape_names = dist.shapes.split(', ')
        intersection = param_names.intersection(shape_names)
        if intersection:
            print(distname, methodname, intersection)
```
produces:
```
I'm having trouble with gumbel_r.fit
I'm having trouble with norm.fit
I'm having trouble with uniform.fit
I'm having trouble with invgauss.fit
I'm having trouble with pearson3.fit
I'm having trouble with erlang.fit
I'm having trouble with pareto.fit
ksone moment {'n'}
I'm having trouble with logistic.fit
I'm having trouble with expon.fit
I'm having trouble with lognorm.fit
I'm having trouble with laplace.fit
levy_stable interval {'alpha'}
I'm having trouble with rayleigh.fit
I'm having trouble with wald.fit
kstwo moment {'n'}
I'm having trouble with beta.fit
I'm having trouble with gumbel_l.fit
hypergeom moment {'n'}
binom moment {'n'}
nbinom moment {'n'}
nhypergeom moment {'n'}
yulesimon interval {'alpha'}
betabinom moment {'n'}
```
Is this catching what we want it to, @rgommers ? Did you want it to run in the test suite? 
I think the issues with `fit` are when the overrides don't have a formal docstring. Perhaps they should inherit the docstring of `rv_continuous`?

**Comment by rgommers** [comment]
> @rgommers For the test that parses the Methods section, did you intend for this to be in the SciPy test suite or something we run offline?

As part of the refguide checker.

**Comment by bsdz** [comment]
I don't feel it would be major issue perhaps renaming it to alpha_ perhaps. It would be a breaking change and, of course, less user friendly.

**Comment by mdhaber** [comment]
How about `a` and `b` instead of `alpha` and `beta`.

**Comment by mdhaber** [comment]
Rather than changing the shape parameter name `n` of those seven distributions, I'd suggest changing the name of the parameter `n` of the `scipy.stats.rv_continuous.moment` method to either `moment`, for consistency with the parameter name `moment` in [`scipy.stats.moment`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.moment.html), or `order`, which would also be a reasonable name.

We could also consider changing the name of parameter `alpha` of `rv_continuous` to `significance`.

Since these are the first arguments of the methods, they may be less likely to be specified as keywords. If that's true, perhaps this would be less disruptive to users than changing the shape parameter names of some very common distributions. (Full disclosure, I'm thinking of what headache it would be to change all the documentation and tutorials of these distributions to reflect a shape parameter name change - especially `n`. I imagine changing a parameter name of the methods would be much easier as they are probably not often used as keywords in SciPy code.)

Shall I propose this on the mailing list?

(Happy to push this forward a bit by e.g. drafting the test in gh-13490, but if it gets very messy, I might not see this through to completion any time soon. It's looking like the cost/benefit of addressing this issue will be unfavorable, and it's been waiting quite patiently for the past few years, so perhaps it doesn't need to be a top priority.)

**Comment by mdhaber** [comment]
Closed by gh-13490.
