### ISSUE TITLE
KS test issue

### ISSUE THREAD

**Issue by ignotur** [scipy/scipy#5988]
Working with function 
stats.kstest(x_samp, 'uniform', N=len(x_samp), alternative='two-sided', mode='approx')
I noticed that it return for D value result which I do not expect to see sometimes. According to Kolmogorov 1933 article, for example http://www.dtic.mil/dtic/tr/fulltext/u2/a253575.pdf
the function should use same CDF for D+ and D-, in reality it is written in scipy/scipy/stats/stats.py:
at 3917 line and further:
           if alternative in ['two-sided', 'greater']:
            Dplus = (np.arange(1.0, N + 1)/N - cdfvals).max()
            if alternative == 'greater':
                return KstestResult(Dplus, distributions.ksone.sf(Dplus, N))

```
    if alternative in ['two-sided', 'less']:
        Dmin = (cdfvals - np.arange(0.0, N)/N).max()
        if alternative == 'less':
            return KstestResult(Dmin, distributions.ksone.sf(Dmin, N))


    if alternative == 'two-sided':
        D = np.max([Dplus, Dmin])
```

Which means that in D+ case CDF goes from 1/N till 1 and in D- case it goes from 0 till 1. That is why it is not equivalent to max(abs(Dplus)) or to max(abs(Dmin))

**Comment by josef-pkt** [comment]
AFAIR:
There were some mailing list thread on this 7 or 8 years ago, and there was a correction in the NIST notes.

The point in the calculation is to look at the right points in the step functions.
I assume the current code is correct, but don't remember any details.

**Comment by pvanmulbregt** [comment]
Is this still an concern? 
Is there an example which shows an unexpected value for D returned by `kstest`?

**Comment by rgommers** [comment]
no response and we've had improvements in `kstest` since 2016, so closing. thanks all
