### ISSUE TITLE
MIMO package for Python control?

### ISSUE THREAD

**Issue by ed06b008** [scipy/scipy#6003]
Does anyone know a python control package to analyse output for a MIMO system?

I tried lsim2 and it does not work for the following reason I guess ( the following lines are taken from source code of scipy.signal.lsim2:
tout, yout, xout = scipy.signal.lsim2(system, U=[signal1,signal2],T=T)

T = atleast_1d(T)
if len(T.shape) != 1:
       raise ValueError("T must be a rank-1 array.")

if U is not None:
       U = atleast_1d(U)
               if len(U.shape) == 1:
                       U = U.reshape(-1, 1)
                sU = U.shape
                if sU[0] != len(T):
                        raise ValueError("U must have the same number of rows "
                             "as elements in T.")

If anyone knows how to fix it, please help!

Thanks

**Comment by e-q** [comment]
Check out the `python-control` package: 
- http://python-control.readthedocs.org/en/latest/index.html
- https://github.com/python-control/python-control

Though I have not used it for this reason myself, the documentation mentions the ability to simulate MIMO forced responses: http://python-control.readthedocs.org/en/latest/control.html#time-domain-simulation

It's BSD licensed, as far as I am aware, so it could be nice to get some of it into `scipy.signal`...
