### ISSUE TITLE
Dirichlet doesn't accept its own random variates as input to pdf

### ISSUE THREAD

**Issue by NeilGirdhar** [scipy/scipy#6006]
```

In [1]: import scipy.stats as ss

In [2]: d = ss.dirichlet([1,3,4])

In [3]: d.pdf(d.rvs())
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-a6f3762e83cf> in <module>()
----> 1 d.pdf(d.rvs())

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/stats/_multivariate.py in pdf(self, x)
   1365
   1366     def pdf(self, x):
-> 1367         return self._dist.pdf(x, self.alpha)
   1368
   1369     def mean(self):

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/stats/_multivariate.py in pdf(self, x, alpha)
   1260         """
   1261         alpha = _dirichlet_check_parameters(alpha)
-> 1262         x = _dirichlet_check_input(alpha, x)
   1263
   1264         out = np.exp(self._logpdf(x, alpha))

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/stats/_multivariate.py in _dirichlet_check_input(alpha, x)
   1079                          "of entries as, or one entry fewer than, "
   1080                          "parameter vector 'a', but alpha.shape = %s "
-> 1081                          "and x.shape = %s." % (alpha.shape, x.shape))
   1082
   1083     if x.shape[0] != alpha.shape[0]:

ValueError: Vector 'x' must have either the same number of entries as, or one entry fewer than, parameter vector 'a', but alpha.shape = (3,) and x.shape = (1, 3).

In [4]: n = ss.norm()

In [5]: n.pdf(n.rvs())
Out[5]: 0.16964393208168185
```

**Comment by NeilGirdhar** [comment]
Every distribution should pass this test:

```
for size in [None, 1, 2]:
    d.pdf(d.rvs(size=size)).shape == (() if size is None else (size,))

**Comment by ev-br** [comment]
Related discussion, starting from https://github.com/scipy/scipy/pull/4984#discussion_r32984650

**Comment by NeilGirdhar** [comment]
@ev-br Thanks for the link.  Sorry for not searching properly before my submission.  I do think this change and my other recent bug report should be made to keep `dirichlet` consistent with `multidimensional_normal`.

**Comment by ev-br** [comment]
Agreed, this would be nice. If you can find a way of fixing it in a backwards-compatible way, that is :-).

**Comment by NeilGirdhar** [comment]
@ev-br How can changing the behaviour be backwards compatible?  In my own code, I did this:

```
class dirichlet_replacement(ss._multivariate.dirichlet_frozen):

    def rvs(self, size=None, random_state=None):
        # This somehow fixes the behaviour of rvs.
        return super().rvs(size=size, random_state=random_state)

    def pdf(self, x):
        if len(x.shape) == 2:
            return super().pdf(x.T)
        return super().pdf(x)
```

**Comment by NeilGirdhar** [comment]
I think you're going to have to at some point have a deprecation cycle if necessary and then change the behaviour.

**Comment by ev-br** [comment]
> I think you're going to have to at some point have a deprecation cycle 

Exactly! The question is only the details of how to do it in a least disruptive way. Help is appreciated :-)

**Comment by NeilGirdhar** [comment]
@ev-br How can I help?  I have no experience with your project, so I don't know how you've done deprecation cycles in the past.

**Comment by ev-br** [comment]
Generally, I think we'd need to either add a keyword (https://github.com/scipy/scipy/pull/4984#discussion_r33011011 with default value being the old behavior) or a new class (`dirichlet2` for a want of better name), make the old one raise a `DeprecationWarning` for at least a release or two, then remove the old one and rename the new one. 

See, it's a prolonged affair :-). But the sooner it's started, the better IMO. 

My preference would be to add a new class. This can also get other enhancements later on (stick breaking dirichlet, possibility of having some concentration values being zero etc). 

Would you be tempted to send a PR?

**Comment by NeilGirdhar** [comment]
@ev-br Sure, I'll look into it.  Would you be able to help me if I have questions?

**Comment by ev-br** [comment]
Of course. No guarantees for specific time or time-to-responce, but time-for-open-source permitting, definitely.

**Comment by NeilGirdhar** [comment]
@ev-br that sounds like my schedule too ;)

**Comment by mdhaber** [comment]
@ev-br I think this can be considered a bug. I think it's better to just fix it now with a message in the release notes than to let the bug persist for another six years : ) Still think we need a deprecation cycle or shall we just go for it?

**Comment by NeilGirdhar** [comment]
@mdhaber Wooohoo!  Thanks for fixing this.  Does your pull request work for this https://github.com/scipy/scipy/issues/6006#issuecomment-202158618?

**Comment by tirthasheshpatel** [comment]
> Wouldn't it make sense to repair this bug before introducing another distribution that would have to be deprecated?

I think gh-7689 is clearly a bug and deprecation should not be necessary in theory. Although, it also has been the behavior of many methods of several multivariate distributions for a long time so there might be genuine concerns of backward-compatibility.

@mdhaber @tupui @Kai-Striega @chrisb83 Should we consider this a bug and fix it without maintaining back-compat or should we first deprecate and then change the behavior?

**Comment by mdhaber** [comment]
I had in mind to propose just fixing it to the mailing list.
The concern about resolving it in a backward compatible way is likely why the bug has persisted despite being reported five years ago. Probably better to just go for it and ask users to add `np.squeeze` to the output if they need it to work how it used to.

But it would probably be better if the `size` bug were fixed in this new distribution regardless, yes. Sounds like we have a little extra time before branching to work with.

**Comment by NeilGirdhar** [comment]
@mdhaber Would it be possible to make `multivariate_beta` vectorized like all of the scalar distributions?

**Comment by mdhaber** [comment]
I agreed above that we should correct `rvs` at the same time, although that will complicate [this](https://github.com/scipy/scipy/pull/16042#issuecomment-1137227051) further : /

Adding vectorization is something that has been requested for many multivariate distributions, and it is an enhancement that can be added in a backward-compatible way at any time, so it's orthogonal to adding `multivariate_beta` . 
(Just to be clear - what do you mean by vectorization? Currently, `pdf` accepts 2D `x`. Do you mean accept ND `x`?)

**Comment by NeilGirdhar** [comment]
> Adding vectorization is something that has been requested for many multivariate distributions, and it is an enhancement that can be added in a backward-compatible way at any time...

Yes, you're right.

> (Just to be clear - what do you mean by vectorization? Currently, pdf accepts 2D x. Do you mean accept ND x?)

The distribution parameter `alpha` itself should be able to be N-dimensional.  For example, if it has shape `(5,3 7)`, that should represent a 5 by 3 matrix of Dirichlet distributions, each of which has 7 parameters.  This is analogous to vectorization of scalar distributions.

**Comment by mdhaber** [comment]
> This is a different question than what pdf accepts.

Yes, I see. This is the same sort of "vectorization" requested in gh-14958, gh-15627, gh-13450, gh-11422, right? 

Would a concise generalization be "Vectorize multivariate distributions w.r.t. shape parameters?"?

**Comment by NeilGirdhar** [comment]
> Would a concise generalization be "Vectorize multivariate distributions w.r.t. shape parameters?"?

I guess you mean the shapes of the parameters?  In that case, yes.  (_Shape parameters_ are a technical term in statistics.)

**Comment by NeilGirdhar** [comment]
> For example, I think df is a shape parameter of multivariate_t

It is.

> and https://github.com/scipy/scipy/issues/15627 wants to vectorize w.r.t. df (i.e. pass in many separate df values and process them in parallel).

I think all of the parameters should have the same shape prefix.  Scalar parameters would have no suffix, vector parameters would have one dimension of suffix, square-matrix parameters would have two dimensions of suffix, etc.

**Comment by mdhaber** [comment]
Yup.

**Comment by mdhaber** [comment]
> Almost. The testcase with size=1 fails but it's whole other issue: https://github.com/scipy/scipy/issues/7689 (pdf uses np.squeeze so all the dimensions with 1 get reduced)

gh-7689 only mentions the `squeeze` use in `rvs`. I didn't know about the `pdf` squeeze : /  We really should fix both. If we can't, I'm afraid we should delay the release of `multivariate_beta`.
