### ISSUE TITLE
scipy.special.kl_div not available in 0.14.1

### ISSUE THREAD

**Issue by scientist1642** [scipy/scipy#6008]
scipy.special.kl_div not available in 0.14.1, even though [documentation](http://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.special.kl_div.html#scipy.special.kl_div) states it's new from 0.14.0

**Comment by WarrenWeckesser** [comment]
That looks like a mistake in the docstring.  The release notes say it was added in 0.15: http://docs.scipy.org/doc/scipy/reference/release.0.15.0.html#scipy-special-improvements

**Comment by scientist1642** [comment]
hm right, the same should also be true for `entr` and `rel_entr`.
