### ISSUE TITLE
The von-Mises entropy is broken

### ISSUE THREAD

**Issue by NeilGirdhar** [scipy/scipy#6011]
`ss.vonmises(2, 0).entropy()`

Should be 1.2663212919642859, but gives some crazy error instead that suggests that the calculation is being done numerically.  The calculation should be done analytically:

```
from scipy.special import iv

                kappa = scipy_distribution.args[0]
                scipy_entropy = (
                    -kappa * iv(1, kappa) / iv(0, kappa)
                    + math.log(2 * math.pi * iv(0, kappa)))
```

**Comment by argriffing** [comment]
Another distribution to look at is the `vonmises_line` distribution which gives that entropy. As background, the scipy stats infrastructure originally assumed that every distribution is a location-scale family continuous on R or discrete on Z, possibly with upper or lower support bounds. Distributions on more complicated domains (circles, spheres, R^N, subspaces in R^N, discrete or finite sets that are not consecutive integers, distributions whose support is a function of the parameters, etc.) are ... less supported.

**Comment by NeilGirdhar** [comment]
@argriffing What's the difference between the von mises and the von mises line?  Also I've added the appropriate code for the entropy.

**Comment by NeilGirdhar** [comment]
@ev-br Seems more like a bug than an enhancement :)

**Comment by ev-br** [comment]
Indeed, https://github.com/scipy/scipy/blob/master/scipy/stats/_continuous_distns.py#L4467 can grow the `_entropy` method. BTW, you can use `i0` and `i1` instead of `iv(0, z)` and `iv(1, z)`.

**Comment by NeilGirdhar** [comment]
@ev-br Ah, good point!  In my code, I coded the VonMises Fisher distribution for which k can be larger.

**Comment by NeilGirdhar** [comment]
@ev-br Might as well do a quick pull request to get my feet wet.

**Comment by ev-br** [comment]
> discrete or finite sets that are not consecutive integers,  are ... less supported.

those with the support on a finite set of non-consecutive integers should be fine now :-).

**Comment by argriffing** [comment]
@NeilGirdhar I think that both `vonmises` and `vonmises_line` are partial hacks around the lack of circular distributions in scipy. In particular I think the scipy `vonmises` distribution has [-inf, inf] support, and the scipy `vonmises_line` distribution has [-pi, pi] support, and both are treated as location-scale distributions over all or part of the real line.

This has some fundamental problems. If you want vonmises_pdf(x) to automatically wrap around the circle, you might implement it as a continuous distribution on the whole real line [-inf, inf]. But this conflicts, for example, with the part of the stats infrastructure that assumes the integral over the support should be 1. In my opinion the best way to fix this is to decide how circular distributions work and add this interface to scipy stats.

**Comment by NeilGirdhar** [comment]
@argriffing That sounds like too big a project for me although I agree that having good design moving forward is critical.

Also, I'm not sure I agree with this view of all distributions being location-scale.  The reason that I've found these last few bugs is that I've written a mini stats library for myself that I was comparing with scipy's in my testing.  My library contains only exponential families and has natural and expectation parametrizations for each.  This is a natural way of working with exponential families.  It allows Bayesian inference (merely addition in natural parameter space), generalized linear models, combining multiple observations (averaging in the expectation parameter space).

**Comment by NeilGirdhar** [comment]
FYI: #6013 

@argriffing 
@ev-br

**Comment by argriffing** [comment]
here's an astropy PR for circular statistics https://github.com/astropy/astropy/pull/4472

**Comment by ev-br** [comment]
Fixed in https://github.com/scipy/scipy/pull/6013. I'll close this, let's concentrate the discussion of circular distributions in, for instance, https://github.com/scipy/scipy/issues/4598.
