### ISSUE TITLE
aborted import whosmat and loadmat modules in python2.7.11

### ISSUE THREAD

**Issue by dreamplee** [scipy/scipy#6015]
when i write   (from scipy.io import loadmat,  whosmat),it's  ok with no mistakes.
but  when i write (import loadmat),the result is  No module named loadmat

from scipy.io import loadmat,  whosmat
import loadmat,whosmat
Traceback (most recent call last):
  File "<string>", line 1, in <fragment>
ImportError: No module named loadmat

appreciate your answer
thank you

**Comment by andyfaff** [comment]
This simply means that there is no package called `loadmat` in your pythonpath. However, the first import did seem to work. Once you've done that you should be able to use `scipy.io.loadmat`
