### ISSUE TITLE
Wilcoxon signed-rank test with zero_method="pratt" or "zsplit" produces an error

### ISSUE THREAD

**Issue by MrMallIronmaker** [scipy/scipy#6017]
I just ran `sudo pip install --upgrade scipy` on Ubuntu 14.04 about ten minutes ago, so I believe this is the current version of SciPy.

When using the "pratt" or "zsplit" flag, the one-array version of Wilcoxon returns an uninformative error. Either this is a bug in the code or a poor error message. I am not a statistician; perhaps providing the list of differences and Pratt's method is a meaningless request.

```
>>> from scipy.stats import wilcoxon
>>> arr = [1, 2, 3, 0, -1, 3]
>>> wilcoxon(arr, zero_method='wilcox')
/usr/local/lib/python2.7/dist-packages/scipy/stats/morestats.py:2384: UserWarning: Warning: sample size too small for normal approximation.
  warnings.warn("Warning: sample size too small for normal approximation.")
WilcoxonResult(statistic=1.5, pvalue=0.10247043485974937)
>>> wilcoxon(arr, zero_method='pratt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/scipy/stats/morestats.py", line 2385, in wilcoxon
    r = stats.rankdata(abs(d))
TypeError: bad operand type for abs(): 'list'
```

Note that this works correctly for the two-array case.

```
>>> wilcoxon(arr, [2, 1, 3, 0, 2, 1], zero_method='pratt')
WilcoxonResult(statistic=8.5, pvalue=0.67414165499270484)
```

If this is a bug, I would love to contribute to SciPy in a small way by fixing it, as long as the community here can provide me with SciPy's processes and standards for doing so.

**Comment by e-q** [comment]
Hi, thanks for reporting this! 

Looking at the (ubuntu pages)[http://packages.ubuntu.com/trusty/python-scipy], it looks like you may be using scipy v0.13, whereas the latest release is v0.17. If you're interested in running the latest versions of numpy/scipy/etc., the ubuntu repositories generally aren't your best bet.

Nevertheless, on my machine with the latest state, I get the same error message. This might be able to be fixed by a call to `np.asarray` somewhere, but I'm not personally familiar with the stats module.

You can find information about contributing in the HACKING.rst.txt file in the root folder of the repository, give it a read and give it a shot!

**Comment by ev-br** [comment]
From a quick glance (I'm not very familiar with this code either, so take it with a grain of salt), it seems that indeed, there's an `asarray` call missing in this line: https://github.com/scipy/scipy/blob/v0.17.0/scipy/stats/morestats.py#L2371
(Note that two-sample code path has asarrays).

PR welcome, I'd say.

**Comment by MrMallIronmaker** [comment]
Two questions: I've looked at the NumPy testing guidelines linked by a SciPy page, but it said the tests for a specific file are located in a test_[filename] file. There isn't one for morestats.py, there, so is it in a different part of the repository, or does it not exist?

Second, what's the best way to informally test the code? I can't import from the scipy directory, so I tried building with setup.py, but I need to download Cython. Is there some way to compile and run just the stats submodule, or do I need to download and install Cython?

**Comment by MrMallIronmaker** [comment]
Two questions: I've looked at the NumPy testing guidelines linked by a SciPy page, but it said the tests for a specific file are located in a test_[filename] file. There isn't one for morestats.py, there, so is it in a different part of the repository, or does it not exist?

Second, what's the best way to informally test the code? I can't import from the scipy directory, so I tried building with setup.py, but I need to download Cython. Is there some way to compile and run just the stats submodule, or do I need to download and install Cython?

**Comment by ev-br** [comment]
```
$ grep -n "pratt"  scipy/stats/tests/*py
scipy/stats/tests/test_morestats.py:1152:    T, p = stats.wilcoxon(x, y, "pratt")
```
(this rule is not strictly enforced)

Yes, you need cython to build an unreleased scipy version. Installing it can as easy as `pip install cython --user`. Once you have it, one easy way to run tests is `$ python runtests.py -s <submodule>` or `$ python runtests.py -t <path-to-test-file>`.

**Comment by maniteja123** [comment]
Hi, for the first question there is a test file for morestats at [test_morestats.py](https://github.com/scipy/scipy/blob/v0.17.0/scipy/stats/tests/test_morestats.py)

To run the tests you could use ``python runtests.py`` from the root folder and ``python runtests.py --help`` to understand the usage.

Please do correct me if I am missing something. Hope it helps.

**Comment by ev-br** [comment]
Fixed by https://github.com/scipy/scipy/pull/6070
