### ISSUE TITLE
Cannot install scipy

### ISSUE THREAD

**Issue by quasemsm** [scipy/scipy#6023]
`Collecting scipy
  Using cached scipy-0.17.0.tar.gz
Installing collected packages: scipy
  Running setup.py install for scipy ... error
    Complete output from command c:\users\sadiq\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Sadiq\\AppData\\Local\\Temp\\pip-build-0ymsfffq\\scipy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Sadiq\AppData\Local\Temp\pip-1pd4786y-record\install-record.txt --single-version-externally-managed --compile:
    lapack_opt_info:
    openblas_lapack_info:
      libraries openblas not found in ['c:\\users\\sadiq\\appdata\\local\\programs\\python\\python35-32\\lib', 'C:\\', 'c:\\users\\sadiq\\appdata\\local\\programs\\python\\python35-32\\libs']
      NOT AVAILABLE

    lapack_mkl_info:
    mkl_info:
      libraries mkl,vml,guide not found in ['c:\\users\\sadiq\\appdata\\local\\programs\\python\\python35-32\\lib', 'C:\\', 'c:\\users\\sadiq\\appdata\\local\\programs\\python\\python35-32\\libs']
      NOT AVAILABLE

      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    c:\users\sadiq\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\system_info.py:635: UserWarning: Specified path C:\projects\np-wheel-builder\atlas-builds\atlas-3.10.1-sse2-32\lib is invalid.
      warnings.warn('Specified path %s is invalid.' % d)
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    c:\users\sadiq\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\system_info.py:1552: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    lapack_info:
      libraries lapack not found in ['c:\\users\\sadiq\\appdata\\local\\programs\\python\\python35-32\\lib', 'C:\\', 'c:\\users\\sadiq\\appdata\\local\\programs\\python\\python35-32\\libs']
      NOT AVAILABLE

    c:\users\sadiq\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\system_info.py:1563: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      warnings.warn(LapackNotFoundError.__doc__)
    lapack_src_info:
      NOT AVAILABLE

    c:\users\sadiq\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\system_info.py:1566: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      warnings.warn(LapackSrcNotFoundError.__doc__)
      NOT AVAILABLE

    Running from scipy source directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Sadiq\AppData\Local\Temp\pip-build-0ymsfffq\scipy\setup.py", line 265, in <module>
        setup_package()
      File "C:\Users\Sadiq\AppData\Local\Temp\pip-build-0ymsfffq\scipy\setup.py", line 262, in setup_package
        setup(**metadata)
      File "c:\users\sadiq\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\Sadiq\AppData\Local\Temp\pip-build-0ymsfffq\scipy\setup.py", line 182, in configuration
        config.add_subpackage('scipy')
      File "c:\users\sadiq\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\misc_util.py", line 1002, in add_subpackage
        caller_level = 2)
      File "c:\users\sadiq\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\misc_util.py", line 971, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\users\sadiq\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\misc_util.py", line 908, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "c:\users\sadiq\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\misc_util.py", line 1002, in add_subpackage
        caller_level = 2)
      File "c:\users\sadiq\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\misc_util.py", line 971, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\users\sadiq\appdata\local\programs\python\python35-32\lib\site-packages\numpy\distutils\misc_util.py", line 908, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

    ----------------------------------------
Command "c:\users\sadiq\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Sadiq\\AppData\\Local\\Temp\\pip-build-0ymsfffq\\scipy\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Sadiq\AppData\Local\Temp\pip-1pd4786y-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Sadiq\AppData\Local\Temp\pip-build-0ymsfffq\scipy\`

I'm getting this error when I try to use pip install for scipy

**Comment by pv** [comment]
The error message says what is wrong. See installation and build instructions, or ask/search on stackoverflow.com
