### ISSUE TITLE
Replace approx_grad with _numdiff.approx_derivative in scipy.optimize

### ISSUE THREAD

**Issue by pv** [scipy/scipy#6026]
It would be better to use the more carefully written `approx_derivative` instead of <s>`approx_grad`</s>`approx_fprime` in the various points in scipy.optimize where numerical differentiation is required.

One particular issue is that `approx_grad` does not respect bounds, may evaluate the function outside them, whereas `approx_derivative` has special handling at the boundaries.

**Comment by andyfaff** [comment]
@pv do you mean replace `approx_fprime` by `approx_derivative`? I can't find an `approx_grad` function in scipy.

**Comment by andyfaff** [comment]
If so, then there are a few caveats:

- `approx_fprime` uses absolute steps, `approx_derivative` uses relative steps
- `approx_fprime` only does forward differences, `approx_derivative` either does 2-point forward/backward or central differences

The first would make it hard to retain backcompatibility for things like `_minimize_bfgs`, where epsilon is given as an absolute difference. The epsilon argument would have to be deprecated, and a relative step, `rel_step` given instead. After a couple of releases one could remove the old argument. Alternatively the epsilon could be used to work out a `rel_step`, which seems a backwards way of doing it (why not rely on `approx_derivative` to calculate the correct scaled step).

The second regards 2 or 3 point differences, using central differences is more accurate, but would lead to more function evaluations.

Or is it solely to escape the behaviour at the bounds?

**Comment by pv** [comment]
Yes, I meant `approx_fprime`, which is quite primitive, so something more carefully thought out could be better.

The `jac` argument currently accepts keywords `'2-point'` etc. for the 'trust-constr' method, but not others. Perhaps we could extend this interface to cover all of the methods (with the same option keywords), leaving `'legacy'` (or something more descriptive of what approx_fprime does) as the current behavior.
