### ISSUE TITLE
stats.gamma.rvs and stats.invgamma.rvs with a = array

### ISSUE THREAD

**Issue by SsnL** [scipy/scipy#6027]
I'm trying to generate samples, each from a different InvGamma parametrized by an element of a vector. 

I noticed that code like <code>stats.gamma.rvs(a = [1, 2, 1])</code> works. But <code>stats.invgamma.rvs(a = [1, 2, 1])</code> doesn't. The latter seems always returning the same sampled value for same <code>a</code> value. e.g.

    >>> stats.gamma.rvs(a=[1, 2, 1])
    array([ 1.49462003,  1.92958171,  1.33492367])
    >>> stats.gamma.rvs(a=[1, 2, 1])
    array([ 0.68224146,  3.02514239,  0.45524092])
    >>> stats.gamma.rvs(a=[1, 2, 1])
    array([ 0.4607998 ,  0.18466327,  0.00676726])
    >>> stats.invgamma.rvs(a=[1, 2, 1])
    array([ 4.12538305,  1.15416349,  4.12538305])
    >>> stats.invgamma.rvs(a=[1, 2, 1])
    array([ 2.09118734,  0.75781348,  2.09118734])
    >>> stats.invgamma.rvs(a=[1, 2, 1])
    array([ 0.54840464,  0.30519084,  0.54840464])
    >>> stats.invgamma.rvs(a=[1, 2, 1])
    array([ 5.2418866 ,  1.33173132,  5.2418866 ])

**Comment by WarrenWeckesser** [comment]
@SsnL Thanks for reporting the problem.  You can find more detail at the original report here: https://github.com/scipy/scipy/issues/2069
