### ISSUE TITLE
Wrong link in f_oneway

### ISSUE THREAD

**Issue by BiYonic** [scipy/scipy#6035]
Hi there,
I am not sure whether this is the right spot to post this:
There is a link in the description of the one-way-Anova test which is not working.
The reference [R389] has a double "http" which leads not to the page it should.
Basically the link should be 
`http://www.biostathandbook.com/onewayanova.html`
 instead of http://http://www.biostathandbook.com/onewayanova.html
Greetings,
Bi

**Comment by ev-br** [comment]
Thanks for the report. If you (or anyone else) submits a PR with the fix, it'll be gladly accepted :-). These sorts of things can even be done in Github online editor.
