### ISSUE TITLE
Incorrect edge case in scipy.stats.triang.pdf

### ISSUE THREAD

**Issue by tpudlik** [scipy/scipy#6036]
When `c = 1`, the pdf of the triangular distribution should just be `f(x) = 2x`.  But as of version 0.17, [the pdf is computed using the formula](https://github.com/scipy/scipy/blob/v0.17.0/scipy/stats/_continuous_distns.py#L4121),

```
where(x < c, 2*x/c, 2*(1-x)/(1-c))
```

which incorrectly returns `nan`, rather than 2, in the case `x = 1`, `c = 1`.

**Comment by tpudlik** [comment]
The cdf has the same problem.

**Comment by ev-br** [comment]
`_lazywhere( c != 0, (x, c), lambda x, c: np.where(x < c, ..., ...), f2=lambda x: 2*x )`

**Comment by tpudlik** [comment]
I tried this approach, but it fails the `test_continous_basic.test_cont_basic.check_cmplx_deriv` test due to a difference in behavior between `where` and `_lazywhere` (which is a bug in the latter, maybe?).  I made a separate issue for it, https://github.com/scipy/scipy/issues/6043.

**Comment by ev-br** [comment]
Yup, that's a bug --- there's a fix in https://github.com/scipy/scipy/pull/5869.
