### ISSUE TITLE
InterpolatedUnivariateSpline include k=0 and fill_value? [enhancement]

### ISSUE THREAD

**Issue by miktoki** [scipy/scipy#6041]
`interp1d` has the posibility of setting interpolation kind `k=0`(ie. nearest neighbour) while [Interpolated]UnivariateSpline does not support this. In addition, `interp1d` has a `fill_value` which can be specified by the user.

I see how this may seem superfluous, but in my experience interp1d underperforms by several orders of magnitude and scales very poorly. 

Is there any chance of adding these features to InterpolatedUnivariateSpline?

**Comment by ev-br** [comment]
fill_value: `UnivariateSpline` has the `ext` keyword, http://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.UnivariateSpline.html
you can use 'zeros' or 'const'. 

`k=0` is a degenerate case, which, AFAIU, FITPACK does not handle.
Note that https://github.com/scipy/scipy/pull/3174 should handle `k=0`, and I think it's better to finish it up than bolt things on `UnivariateSpline`

**Comment by miktoki** [comment]
`k=0` : I was not aware of the efforts being done there. Great that it is already looked into.

fill_value: `ext` does not quite encompass the all the use cases of fill_value AFAIU. 
As an example one cannot guarantee that 'zeros' is outside the codomain, and 'const' is at best  at the edge of it.

**Comment by ev-br** [comment]
While of course the interface of `UnivariateSpline` is not set in stone, and we can consider a pull request if there's one, I am not sure why you want to add *more* to the FITPACK spline wrappers if it's quite straightforward to do in the user code. Like (untested):

```
class MySpline(object):
    def __init__(self, x, y, fill_value=np.nan):
         self.x, self.y = map(np.atleast_1d, (x, y))
         self.fill_value = fill_value
         self._spl = UnivariateSpline(x, y, s=0)

   def __call__(self, xp):
         out = self._spl(xp)
         out[(xp < self.x[0]) | (xp > self.x[-1])] = fill_value
         return  out
```

**Comment by miktoki** [comment]
Fair point. I think that should be sufficient for most use cases.
