### ISSUE TITLE
Possible bug in scipy.sparse.linalg.expm

### ISSUE THREAD

**Issue by nonhermitian** [scipy/scipy#6045]
I belive that there is an issue with the sparse expm function as the size of the sparse matrix increases.  A simple tridiagonal sparse matrix does not agree with the dense expm result, with an error diverging as the size `N` of the matrix increases:

```python
import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla
import scipy.linalg as la

N=30

diag = np.arange(-N, N+1, dtype=float)
A = sp.diags(diag, 0, format='csc', dtype=float)

N = 2*N+1
diags = [np.ones(N-1,dtype=int),np.ones(N-1,dtype=int)]
B = sp.diags(diags,[1,-1],format='csc', dtype=float)

C = A + B

out = spla.expm(C)
 
ans = la.expm(C.toarray())
 
print(np.abs(out-ans).max())
```

For N=30, the max difference is ~0.014, where as going with N=50 gives a max difference of 74448896.

**Comment by argriffing** [comment]
Thanks for reporting this. That's a large absolute difference, but if the entries of the matrix exponential are themselves very large then there is a limit to how well you can expect to do with 64 bit floats. When N=50 the largest entry looks like 7e21 or something and I see a maximum relative (as opposed to absolute) difference of like 1e-13. With double precision you can't expect more than around 1e-16, so to me this is not a clear indication of a bug. That said, the scipy expm implementation could still use more work and testing.

**Comment by nonhermitian** [comment]
I would agree that this is not really an issue and can be closed.  In fact, it seems that the Scipy method behaves a bit better than the Matlab implementation at larger dimensions.

**Comment by argriffing** [comment]
The Matlab implementation is catching up!
https://nickhigham.wordpress.com/2016/03/08/the-improved-matlab-functions-expm-and-logm/
