### ISSUE TITLE
ordqz: specification of sort function doesn't match documentation

### ISSUE THREAD

**Issue by albop** [scipy/scipy#6055]
Following up on #6044 

The function `scipy.linalg.ordqz(A,B,sort='lhp')` accepts a `sort` argument which takes either a string or a callable. According to the documentation, this function takes three real arguments if `A` and `B` are real or two complex ones, if `A` and `B` are complex.

However:

```python
import numpy
import scipy.linalg
A = numpy.random.random( (10,10) )
B = numpy.random.random( (10,10) )
def sort(alphar, alphai, beta): (beta**2<=alphar**2+alphai**2) 
scipy.linalg.ordqz(A,B,sort=sort)
```

fails with the following error:

```
/home/pablo/.local/anaconda3/lib/python3.5/site-packages/scipy/linalg/_decomp_qz.py in ordqz(A, B, sort, output, overwrite_a, overwrite_b, check_finite)
    311 
    312     sfunction = _select_function(sort)
--> 313     select = sfunction(alpha, beta)
    314 
    315     tgsen, = get_lapack_funcs(('tgsen',), (AA, BB))

TypeError: sort() missing 1 required positional argument: 'beta'
```

It works if sort is defined with two arguments instead:
```scipy.linalg.ordqz(A,B,sort=lambda alpha, beta: alpha>beta)```

This is in itself surprising since in that case alpha and beta should be complex and one would expect the comparison to raise an error but no error is raised even if A and B are complex. Not sure whether this is a problem or not.

**Comment by person142** [comment]
@albop: hopefully #6454 clarifies things. As for the last example with

``sort = lambda alpha, beta: alpha > beta``:

this is a feature of how numpy does comparisons. For example:

```python
>>> import numpy as np
>>> 1 + 1j < 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unorderable types: complex() < int()
>>> np.ones(1) + 1j < 2*np.ones(1)
array([ True], dtype=bool)
```
