### ISSUE TITLE
import scipy.ndimage    ImportError: DLL load failed: 找不到指定的模块。

### ISSUE THREAD

**Issue by WT68696** [scipy/scipy#6064]
As title,ImportError: DLL load failed: 找不到指定的模块(Cannot find appointed module)。

**Comment by insertinterestingnamehere** [comment]
Which Python version are you using? How did you install scipy?

**Comment by pv** [comment]
Typical guess: on Windows, using Gohlke's binaries, but did not install
all the necessary parts explained on Gohlke's page.

**Comment by WT68696** [comment]
@insertinterestingnamehere My PC system is WIn8.1 64bit,while Python2.7 is 32bit,I download Scipy from Gohlke's binaries,get a whl file(scipy-0.17.0-cp27-none-win32.whl) and "pip install ***.whl" in CMD,Sir.

**Comment by WT68696** [comment]
@pv I download Scipy from Gohlke's binaries,get a whl file(scipy-0.17.0-cp27-none-win32.whl) and "pip install ***.whl" in CMD.But I don't know how to unstall Numpy-MKL and Visual C runtime.

**Comment by pv** [comment]
The full instructions to do that can be found on Gohlke's site.

**Comment by WT68696** [comment]
@pv I cannot thank you more for your generous help !

**Comment by animalize** [comment]
How about give a friendly prompt like this:  

> Maybe your system lack of Visual C++ 201X Redistributable, please install it from http://download.microsoft.com....

pseudocode:
```
except ImportError:
    if system is MS-Windows:
        if python-version is 2.7:
            print(need VC 2008 runtime)
        elif python-version is 3.0~3.4:
            print(need VC 2010 runtime)
        elif python-version is 3.5:
            print(need VC 2015 runtime)
```

**Comment by pv** [comment]
Suggestions on how Gohlke should improve the files he distributes should be addressed to him, I don't think he follows this discussion.
