### ISSUE TITLE
init_c_multivariate() stores pointer to local variable

### ISSUE THREAD

**Issue by pitrou** [scipy/scipy#6068]
In `scipy/integrate/quadpack.h`, function `init_c_multivariate` stores a pointer to `n_args_ref` in the global variable `global_n_args`. Unfortunately `n_args_ref` is a local variable which very soon goes out of scope, so later dereferencing `global_n_args` produces a nonsensical value.

**Comment by pv** [comment]
Duplicate of https://github.com/scipy/scipy/issues/4831

**Comment by pitrou** [comment]
Oops :)
