### ISSUE TITLE
scipy.io.loadmat segfaults on some truncated mat files

### ISSUE THREAD

**Issue by eli-b** [scipy/scipy#6072]
On Ubuntu 15.10, with scipy.version.full_version 0.14.1, scipy.version.git_revision f9fbd6ccdbfb26698dbaa55bff3b00022ca6d31d.

To reproduce:

    import scipy.io

    scipy.io.loadmat('segfault.mat')

The attached (zipped) matfile is the shortest prefix of my matfile that reproduces the error.

Truncated files can be created by a corrupt download, so this scenario isn't merely theoretical. In fact, that's how I came upon it.

[segfault.mat.zip](https://github.com/scipy/scipy/files/222146/segfault.mat.zip)

**Comment by ev-br** [comment]
Still segfaults with current master (0edf2bac85af78ddbde392f1ddf69d7edef37832).

**Comment by pv** [comment]
Fix in gh-6209
