### ISSUE TITLE
PDF Equation for Burr and Fisk distributions is wrong

### ISSUE THREAD

**Issue by alceufc** [scipy/scipy#6073]
In `_continuous_distns.py` [1] the method `burr_gen._pdf()` specifies the PDF of the Burr distribution, which is also used by the Fisk distribution (`fisk_gen._pdf()`).

The current PDF is `c*d*(x**(-c-1.0))*((1+x**(-c*1.0))**(-d-1.0))`, however, the sign of the first `c` is wrong. 

The PDF should be: `c*d*(x**(c-1.0))*((1+x**(-c*1.0))**(-d-1.0))`.

This can be verified in Equation 53 of the paper referenced in the class documentation [2].

[1] scipy/scipy/stats/_continuous_distns.py
[2] Burr, I. W. "Cumulative frequency functions", Annals of Mathematical Statistics, 13(2), pp 215-232 (1942).

**Comment by josef-pkt** [comment]
My guess is that it's a typo in the paper and not the code. (brief visual check x**(-c-1) is the derivative of x**(-c) in the cdf)

check if it integrates to 1.

**Comment by alceufc** [comment]
Please note that the Wikipedia articles for the [Burr](https://en.wikipedia.org/wiki/Burr_distribution) and [Fisk](https://en.wikipedia.org/wiki/Log-logistic_distribution) distributions use parameters as in the paper.

Of course, the Wikipedia articles could also be wrong.

**Comment by josef-pkt** [comment]
AFAIK the unit tests verify that it integrates to 1.
It's very unlikely that after switching a sign the pdf still integrates to 1.

easy to check.

**Comment by ev-br** [comment]
```
In [13]: quad(lambda x: stats.fisk.pdf(x, c=3), 0, np.inf)
Out[13]: (1.0, 5.463878275148312e-10)

In [14]: quad(lambda x: -stats.fisk.pdf(x, c=1), 0, np.inf)
Out[14]: (-1.0, 1.1102230246251565e-14)
```

> AFAIK the unit tests verify that it integrates to 1.

https://github.com/scipy/scipy/blob/master/scipy/stats/tests/test_continuous_basic.py#L211 and https://github.com/scipy/scipy/blob/master/scipy/stats/tests/common_tests.py#L23

**Comment by josef-pkt** [comment]
compared to wikipedia burr, the `c` looks defined with a different sign

but there is also a `burr12` which looks the same as the wikipedia definition.

**Comment by josef-pkt** [comment]
see also gh-5560
(I thought this sounds familiar)

**Comment by alceufc** [comment]
Yes, reading the documentation it appears that the burr distribution from Scipy corresponds to Equation 11 of the paper (Burr III). That means that `burr_gen._pdf()` is correct.

I am trying to figure out if it is correct to use the Burr III to compute the Fisk distribution or if it is necessary to be the Burr XII.

**Comment by josef-pkt** [comment]
cdf in wikipedia for fisk log-logistic has `-beta` in the first definitions, which in my reading mean beta is the c in scipy burr_gen.

**Comment by alceufc** [comment]
Here is the Fisk (log-logistic) PDF using the same Equation from Wikipedia (c corresponds to the beta parameter). Note that it also integrates to 1.0.

```
In [23]: loglogistic = lambda x, c: c * x**(c-1) * (1 + x**(c))**(-2)
In [24]: integrate.quad(lambda x: loglogistic(x, c=1), 0, np.inf)
Out[24]: (1.0, 1.1102230246251565e-14)
```

**Comment by josef-pkt** [comment]
Burr 3 is in Dagum in Wikipedia, and fisk is a special case of either Burr 3 or 12 (Sing-Maddala)
https://en.wikipedia.org/wiki/Log-logistic_distribution#Related_distributions

(if X is Burr 3 then 1 / X is Burr 12, so it's a case where both signs X**1 and X**(-1) make it into a proper distribution)

**Comment by alceufc** [comment]
@josef-pkt thank you for the attention and for clarifying. They are indeed the same:

```
In [34]: integrate.quad(lambda x: loglogistic(x, c=1) - stats.fisk.pdf(x, c=1), 0, np.inf)
Out[34]: (-1.426214455323933e-17, 1.2206568132920441e-16)
```

**Comment by maniteja123** [comment]
Hi, just my two cents though the issue is closed. The discussion here might help. #5589 #5654. The PDF and CDF becomes the same when d=1.
