### ISSUE TITLE
Bug in computation of dtype for sum or product linear operators

### ISSUE THREAD

**Issue by tbetcke** [scipy/scipy#6078]
The routine _get_dtype in scipy.sparse.linalg.interface has a mutable keyword argument to which in the routine the dtypes of the input operators are appended. This has the effect that dtypes are not always correctly computed. For example, if first a sum of two complex operators is computed, and then the sum of two real operators, the sum of the real operators also gets the type 'complex128' since this is still stored in the mutable dtypes list from the first addition.

Possible solution: Make the dtypes keyword argument non-optional, and modify the calls to _get_dtype in the other routines of the module correspondingly.

**Comment by ev-br** [comment]
A short reproducer would be helpful. A PR with a fux and a test would be even better.

**Comment by tbetcke** [comment]
Here is an example that reproduces the error:

```
from scipy.sparse.linalg import LinearOperator
from scipy.sparse.linalg import aslinearoperator
import numpy as np

mat_complex = np.random.rand(2,2) + 1j * np.random.rand(2,2)
mat_real = np.random.rand(2,2)

complex_operator = aslinearoperator(mat_complex)
real_operator = aslinearoperator(mat_real)

sum_complex = complex_operator + complex_operator
sum_real = real_operator + real_operator

print(sum_complex.dtype)
print(sum_real.dtype)
```
The output is:
```
complex128
complex128
```
If you take out the complex sum then the real sum gets the correct type.

In what format do you require a patch and a fix?

**Comment by simongibbons** [comment]
A simpler fix would be, I think, to just change `_get_dtype` to be

    def _get_dtype(operators, dtypes=None):
        if dtypes == None:
            dtypes = []
        ......

**Comment by tbetcke** [comment]
Yes, I agree. That would do it.

On 21 April 2016 at 10:32, Simon Gibbons <notifications@github.com> wrote:

> A simpler fix would be, I think, to just change _get_dtype to be
>
> def _get_dtype(operators, dtypes=None):
>     if dtypes == None:
>         dtypes = []
>     ......
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/scipy/scipy/issues/6078#issuecomment-212829891>
>



-- 
Dr. Timo Betcke
Reader in Mathematics
University College London
Department of Mathematics
E-Mail: t.betcke@ucl.ac.uk
Tel.: +44 (0) 20-3108-4068
Fax.: +44 (0) 20-7383-5519
