### ISSUE TITLE
csc_matrix fails on unsorted coordinates when using 64 bit indicies

### ISSUE THREAD

**Issue by dfreese** [scipy/scipy#6079]
For me the following three function calls work:

    csc_matrix(((1.0, 1.0, 1.0), ((0, 1, 2), (0, 0, 0))), shape=(2**31, 1))
    coo_matrix(((1.0, 1.0, 1.0), ((0, 2, 1), (0, 0, 0))), shape=(2**31, 1))
    csc_matrix(((1.0, 1.0, 1.0), ((0, 2, 1), (0, 0, 0))), shape=(2**31-1, 1))`

But the following fails:

    csc_matrix(((1.0, 1.0, 1.0), ((0, 2, 1), (0, 0, 0))), shape=(2**31, 1))

The following line (998) in sparse/compressed.pyc produces a "ValueError: could not convert integer scalar"

    fn(M, N, self.indptr, self.indices, self.data)
   
which is called when running the following in sparse/coo.pyc (line 297):

    A.sum_duplicates()

It seems to something with the indices not being sorted.

I tested this on scipy 0.17.0 and python 2.7.9

**Comment by perimosocordiae** [comment]
I can't reproduce this on master. If you can, try updating and check if the same issue occurs on your end.

**Comment by dfreese** [comment]
Check it against master (66e7ff0) and it works now.  Sorting will work in the meantime.
