### ISSUE TITLE
__init__ called twice when subclassing from LinearOperator

### ISSUE THREAD

**Issue by tbetcke** [scipy/scipy#6082]
When subclassing from LinearOperator in scipy.sparse.linalg.interface the __init__ routine of the subclass is called in the overridden __new__ method of the LinearOperator. However, __init__ is also called implicitly by the runtime system of the linear operator, meaning that this routine is called twice.

Possible solution: Remove the call to __init__ at the end of the __new__ method in LinearOperator.

**Comment by simongibbons** [comment]
This has already been fixed on master in this (merged) pull request https://github.com/scipy/scipy/pull/5894

I think it is scheduled to be included in the 0.18 release.
