### ISSUE TITLE
Multiple float96 wav file test failures on 32-bit Linux

### ISSUE THREAD

**Issue by matthew-brett** [scipy/scipy#6090]
On Linux 32-bit, with current scipy master, commit 3d2e725, I get multiple failures of type:

```
======================================================================
ERROR: test_wavfile.test_write_roundtrip(False, 8000, dtype('>f12'), 1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mb312/.virtualenvs/test/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/mb312/dev_trees/scipy/scipy/io/tests/test_wavfile.py", line 107, in _check_roundtrip
    rate2, data2 = wavfile.read(tmpfile, mmap=mmap)
  File "/home/mb312/dev_trees/scipy/scipy/io/wavfile.py", line 251, in read
    "has {}-bit data.".format(bit_depth))
ValueError: Unsupported bit depth: the wav file has 96-bit data.
```

I guess that the test is assuming that wav files support the float types that numpy / scipy supports, but the weird float96 (80 bit floats padded out to 96 bits) is causing problems?

**Comment by endolith** [comment]
Is this the same issue as https://github.com/scipy/scipy/pull/6184 ?

Do float96 wav files even exist?  I've never heard of them.

For `WAVE_FORMAT_PCM`, WAV format supports arbitrary number of `BitsPerSample` (up to 0xffff = 65536-bit? which is silly)

But for floating point, it specifies `WAVE_FORMAT_IEEE_FLOAT` instead, and [IEEE floats only exist in 16, 32, and 64, apparently](https://en.wikipedia.org/wiki/IEEE_floating_point#Basic_and_interchange_formats)?

http://www-mmsp.ece.mcgill.ca/documents/audioformats/wave/wave.html says:

> Non-PCM Formats
> ...
>  For float data, full scale is 1. The bits/sample would normally be 32 or 64.

**Comment by rgommers** [comment]
> Is this the same issue as #6184 ?

Yes, that's the PR to fix these test failures.

**Comment by rgommers** [comment]
> Do float96 wav files even exist? I've never heard of them.

No, don't exist AFAIK.
