### ISSUE TITLE
Spence function test errors on 32-bit Linux

### ISSUE THREAD

**Issue by matthew-brett** [scipy/scipy#6091]
Testing on Ubuntu 12.04 32-bit with current scipy, numpy=1.11.0, using openblas or default system blas / lapack:

```
======================================================================
FAIL: Check against known values of Spence's function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mb312/.virtualenvs/test-bare/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/mb312/dev_trees/scipy/scipy/special/tests/test_spence.py", line 33, in test_special_points
    FuncData(spence, dataset, 0, 1, rtol=1e-14).check()
  File "/home/mb312/dev_trees/scipy/scipy/special/_testutils.py", line 292, in check
    assert_(False, "\n".join(msg))
  File "/home/mb312/.virtualenvs/test-bare/local/lib/python2.7/site-packages/numpy/testing/utils.py", line 71, in assert_
    raise AssertionError(smsg)
AssertionError: 
Max |adiff|: 3.1172e-05
Max |rdiff|: 3.79006e-05
Bad results (1 out of 9) for the following points (in output 0):
                        (2+0j) =>       (-0.8224358614416541-0j) !=       (-0.8224670334241132+0j)  (rdiff          3.790058591075579e-05)
```

It is reasonable to relax the test threshold?

**Comment by person142** [comment]
Not by that much. If it's getting ``1e-14`` on some machines but only ``1e-5`` on others I'd like to know why. Are you running the tests in ``test_mpmath``? If not, would you mind running ``test_spence_circle`` and telling me the result?

**Comment by person142** [comment]
Here's what I think is happening. The series being used converges slowly at 2, so it requires a lot of terms. The denominator of each term involves an integer multiplication which is overflowing on a 32 bit int. Will fix tomorrow, but might have to ask for your help with testing since I don't have access to any 32 bit systems.

**Comment by matthew-brett** [comment]
Thanks for looking at this.   Do you have access to docker - maybe via a VM?  I can give you a script to reproduce it if so.

**Comment by pv** [comment]
@Josh: virtual machines are probably the easiest way to get access to
32-bit systems. Eg. Linux on virtualbox is relatively straightforward.
