### ISSUE TITLE
Precision error on Linux 32 bit with openblas

### ISSUE THREAD

**Issue by matthew-brett** [scipy/scipy#6093]
Testing with current openblas (0.2.18) and current scipy on 32-bit Linux gives this error:

```
======================================================================
FAIL: test_orthogonal.test_la_roots
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mb312/.virtualenvs/test/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/mb312/dev_trees/scipy/scipy/special/tests/test_orthogonal.py", line 722, in test_la_roots
    vgq(rootf(50), evalf(50), weightf(50), 0., np.inf, 100, atol=1e-13)
  File "/home/mb312/dev_trees/scipy/scipy/special/tests/test_orthogonal.py", line 286, in verify_gauss_quad
    assert_allclose(vv, np.eye(N), rtol, atol)
  File "/home/mb312/dev_trees/numpy/numpy/testing/utils.py", line 1391, in assert_allclose
    verbose=verbose, header=header)
  File "/home/mb312/dev_trees/numpy/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-15, atol=1e-13

(mismatch 0.08%)
 x: array([[  1.000000e+00,   4.552139e-16,  -4.564824e-16, ...,
          1.224186e-16,   1.877534e-16,  -1.530426e-17],
       [  4.552139e-16,   1.000000e+00,   1.328770e-15, ...,...
 y: array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],...
```

See also: https://mail.python.org/pipermail/wheel-builders/2016-April/000112.html

This looks like a small precision error.  Would it be reasonable to relax the threshold slightly for the test?

**Comment by pv** [comment]
Probably OK to relax.

**Comment by matthew-brett** [comment]
Test still failing on maintenance/0.18.x - is that expected ?

https://travis-ci.org/MacPython/scipy-wheels/jobs/143261634#L368

**Comment by ev-br** [comment]
Grrr, I expected that the precision bump in gh-6293 was enough.

**Comment by ev-br** [comment]
gh-6360 bumps it a bit more

**Comment by pv** [comment]
The AssertionError raised by "assert_allclose" probably should be 
changed to include the amount of violation, in addition to saying what 
the tolerances are. ("Not equal to tolerance rtol=1e-15, atol=1e-13; 
maximum deviation was rdiff=xxx, adiff=yyy")

**Comment by ev-br** [comment]
> The AssertionError raised by "assert_allclose" probably should be
changed to include the amount of violation, in addition to saying what
the tolerances are. ("Not equal to tolerance rtol=1e-15, atol=1e-13;
maximum deviation was rdiff=xxx, adiff=yyy")

sounds like an easy-fix issue for numpy?

**Comment by ev-br** [comment]
and indeed https://travis-ci.org/MacPython/scipy-wheels/builds/143412079 seems to pass now
