### ISSUE TITLE
Barycentric transforms test error on Python3, 32-bit Linux

### ISSUE THREAD

**Issue by matthew-brett** [scipy/scipy#6101]
I am getting a test error on 32-bit Linux and Python 3

```
======================================================================
FAIL: test_qhull.TestUtilities.test_more_barycentric_transforms
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/bongoslave/manylinux-3_4-ubuntu-32/build/venv/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/buildslave/bongoslave/manylinux-3_4-ubuntu-32/build/venv/lib/python3.4/site-packages/scipy/spatial/tests/test_qhull.py", line 375, in test_more_barycentric_transforms
    unit_cube_tol=1500*eps)
  File "/home/buildslave/bongoslave/manylinux-3_4-ubuntu-32/build/venv/lib/python3.4/site-packages/scipy/spatial/tests/test_qhull.py", line 303, in _check_barycentric_transforms
    assert_(ok.all(), "%s %s" % (err_msg, np.where(~ok)))
  File "/home/buildslave/bongoslave/manylinux-3_4-ubuntu-32/build/venv/lib/python3.4/site-packages/numpy/testing/utils.py", line 71, in assert_
    raise AssertionError(smsg)
AssertionError: ndim=4 (array([11618], dtype=int32),)
```

See:

* http://nipy.bic.berkeley.edu/builders/manylinux-3.4-ubuntu-32/builds/0/steps/shell_11/logs/stdio
* http://nipy.bic.berkeley.edu/builders/manylinux-3.5-ubuntu-32/builds/0/steps/shell_11/logs/stdio

These tests were running a scipy 0.17.0 manylinux wheel, but @ogrisel also reproduced using a fresh build.  Quoting from his [email](https://mail.python.org/pipermail/wheel-builders/2016-April/000116.html):

"""
I can reproduce the exact same error on a fresh ubuntu/trusty32
vagrant box with numpy 1.11.0 and scipy 0.17.0 built from source with
system Python 3.4.3, libopenblas-dev 0.2.8-6ubuntu1, liblapack-dev
3.5.0-2ubuntu1 and gfortran 4.8.2-1ubuntu6.

https://atlas.hashicorp.com/ubuntu/boxes/trusty32

```
mkdir trusty32 && cd trusty32
vagrant init ubuntu/trusty32
# edit Vagrantfile to set virtualbox VM memory to 4096
vagrant up --provider virtualbox
vagrant ssh
```
"""

**Comment by matthew-brett** [comment]
I can also replicate on latest scipy trunk with:

```
docker run -ti --rm -v $PWD:/io f69m/ubuntu32:14.04 /bin/bash
source /io/install-scipy.sh
```

Where `install-scipy.sh` is:

```
apt-get update
apt-get install -y python3-dev python3-pip libopenblas-dev liblapack-dev gfortran git
pip3 install Cython --install-option="--no-cython-compile"
pip3 install numpy nose
git clone https://github.com/scipy/scipy
cd scipy
pip3 install .
cd ..
nosetests scipy.spatial
```

**Comment by ev-br** [comment]
Just as a data point, this failure was seen in https://github.com/scipy/scipy/issues/5542 when building in wine in a 32-bit ubunutu VM with numpy-vendor setup.

**Comment by ev-br** [comment]
Here's the test that fails: https://github.com/scipy/scipy/blob/master/scipy/spatial/tests/test_qhull.py#L372

Note that the next one, *check with yet larger perturbations*, is disabled on 32-bit platforms with a comment *test numerically unstable, and reported to fail on 32-bit installs*. 

I wonder if this one should also be disabled on 32-bit platforms.
