### ISSUE TITLE
a import error in scipy-0.16.1-win32-superpack-python2.7

### ISSUE THREAD

**Issue by strange-jiong** [scipy/scipy#6103]
in scipy\sparse\linalg\isolve line 11
from scipy.lib.decorator import decorator

should be  from scipy._lib.decorator import decorator

**Comment by ev-br** [comment]
Thanks.
Do you happen to have an reproducible example of something that actually fails because of this?
Without one, this report is not actionable, I'm afraid.

**Comment by pv** [comment]
Probably can be closed --- likely mixed up files from different Scipy 
versions. (There's no line `from scipy.lib.decorator import decorator` 
in Scipy currently or in 0.16.1.)

**Comment by strange-jiong** [comment]
scipy\sparse\linalg\isolve\iterative.py  line 11

`from scipy._lib.decorator import decorator`

**Comment by ev-br** [comment]
In master, it's different, https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/isolve/iterative.py#L11
And the decorator import above looks fine. Please add a runnable example which breaks if you have one. Thanks!
