### ISSUE TITLE
cKDtree slowdown in version 0.17 with dupicate points in tree

### ISSUE THREAD

**Issue by yoachim** [scipy/scipy#6108]
I'm seeing a slowdown in cKDtree after upgrading from 0.15.1 to 1.17.0.  It looks takes much longer to construct the tree if there are repeat points. Here's a gist I made that shows the problem (I used healpy, sorry):
https://gist.github.com/yoachim/d3385c783eec38dce1aa8e1219b75c9e

Before upgrade, I get:
```
scipy version 0.15.1
random positions  60.2701401711 seconds
repeat positions  58.5178990364 seconds
```
after:
```
scipy version 0.17.0
random positions  61.2154760361 seconds
repeat positions  336.582792997 seconds
```

**Comment by ev-br** [comment]
ping @sturlamolden @rainwoodman

**Comment by sturlamolden** [comment]
I think it was 0.16 that did this. Basically it is a problem with using quickselect on presorted data. Construct with ```balanced_tree=False``` to avoid this. Perhaps we should use this as default. We also have this problem when constructing a kd-tree from grid data. However, ```balanced_tree=False``` will in most cases result in a slower search, sometimes substantially slower.

**Comment by sturlamolden** [comment]
Use ```balanced_tree=False``` and ```compact_nodes=False``` to get the exact same behavior as 0.15.1. However, in most cases none of those are beneficial for the query time(s), and the query time(s) are in most use cases orders of magnitude larger than the construction times. In most use cases we only care about the query times.

**Comment by ev-br** [comment]
I'd recommend adding these explanations to the Notes section of the docstring or expanding the tutorial.

**Comment by yoachim** [comment]
Thanks @sturlamolden, that got things sped back up.  I think I just had a weird case where I'm dominated by repeat points in the tree.
