### ISSUE TITLE
LU decomposition of  a sparse matrix 

### ISSUE THREAD

**Issue by geohadab** [scipy/scipy#6110]
I have sparse matrix that I decompose by splu in scipy and I looked at the sparsity pattern and it looked strange. I used same matrix and applied LU decomposition in matlab and I looked at the sparsity pattern and it is different 

[sparse.py.tar.gz](https://github.com/scipy/scipy/files/240510/sparse.py.tar.gz)

python sparsity pattern
![figure_1](https://cloud.githubusercontent.com/assets/6843773/14885833/62c33036-0d56-11e6-8dd0-6170473b306a.png)

**matlab sparsity pattern**
Download CastleImage matlab function and run the following code 

[CastleImage.m.tar.gz](https://github.com/scipy/scipy/files/240520/CastleImage.m.tar.gz)

` [G,a] = CastleImage;
[L,U] = lu(sparse(G),0);
spy(L)`
![matlab](https://cloud.githubusercontent.com/assets/6843773/14885893/a864b43e-0d56-11e6-8e4e-5cad79008adc.jpg)

**Comment by pv** [comment]
That does not mean much --- the permutations can be different.
The relation `Pr.T * (lu.L * lu.U) * Pc.T == A` still applies.
