### ISSUE TITLE
Expected value of normal distribution with lower bound lower than lower bound

### ISSUE THREAD

**Issue by schlork** [scipy/scipy#6127]
This is very easy to reproduce by doing:
`scipy.stats.norm.expect(loc=1,lb=1)`
which will result in something around `0.89 < 1 = lb`.

Thats kind of crucial since it it a very simple function.

Cheers!

**Comment by pv** [comment]
Look at what the documentation says it calculates:
```
                     ubound
             E[x] = Integral(f(x) * dist.pdf(x))
                     lbound
```
with default `f(x) = x`. Obviously, this can be smaller than lbound.

**Comment by ev-br** [comment]
Let's double-check it: 
```
>>> stats.norm.expect(lb=1)
0.24197072451914342

>>> np.exp(-0.5) / np.sqrt(2. * np.pi)
0.24197072451914337
```

The second line is the result of changing the variables in the integral `\int_{1}^{\infty} x exp(-x^2 / 2) dx` (and the denominator is the normalization factor).

**Comment by josef-pkt** [comment]
as additional explanation, there is a `conditional` option to compute the expectation using the conditional distribution instead of the original:

```
>>> from scipy import stats
>>> stats.norm.expect(lb=1)
0.24197072451914342

>>> stats.norm.expect(lb=1, conditional=True)
1.5251352761609815
>>> stats.norm.expect(lb=1) / stats.norm.sf(1)
1.5251352761609815
>>> stats.truncnorm(1,np.inf).mean()
1.5251352761609811
```

**Comment by schlork** [comment]
Very good, now I understand. Thanks a lot for the help and comments!
