### ISSUE TITLE
Error in dot method of sparse COO array, when used with numpy arrays with 0 columns.

### ISSUE THREAD

**Issue by torosdahl** [scipy/scipy#6128]
If A is sparse array in COO format of shape (M,N) and B is a numpy array of shape (N,0), then A.dot(B) throws an IndexError in dot. 

One would expect it to return an empty array of shape (M,0). This is for instance the case if A is a sparse matrix in CSR format or a numpy array.

To reproduce:

    import scipy.sparse as sp
    import numpy as np
    sp.csr_matrix(np.eye(3,2)).dot(np.eye(2,0)).shape  # Works, (3,0)
    sp.coo_matrix(np.eye(3,2)).dot(np.eye(2,0))  # Throws error

**Comment by perimosocordiae** [comment]
Yep, that's a bug. I'll open a PR with the fix soon.
