### ISSUE TITLE
ENH: CircleCI for doc building

### ISSUE THREAD

**Issue by Eric89GXL** [scipy/scipy#6129]
The CircleCI service can be used to build docs for each PR, leaving behind artifacts like doc build results. See from a PR build for another repo:

https://circle-artifacts.com/gh/mne-tools/mne-python/907/artifacts/0/home/ubuntu/mne-python/doc/_build/html/index.html

It seems like it would make reviewing PRs that touch docs (e.g., #3954) easier to review.

I'm up for trying to implement this if people think it's worthwhile.

**Comment by ev-br** [comment]
Yeah, demystifying the relation between docstrings and the html docs on a PR level would be nice IMO.
