### ISSUE TITLE
Segfault in map_coordinates

### ISSUE THREAD

**Issue by atbd** [scipy/scipy#6131]
Hello,
My code produces segfault in the map_coordinates function (when it calls _nd_image.geometric_transform). It seems this segfault is linked to the values/size of coordinates array.

```
numpy.__version__ = 1.7.1 
scipy.__version__ = 0.12.1 
test on 64bits linux (kernel 3.10)
```

To reproduce:
```python
im = np.random.random((48000, 5984))
gr = (np.random.random((255492992,2)) * 50000).astype('f')
map_coordinates(im,gr.T,order=3,mode='constant',cval=np.nan,output=np.float64)
```

**Comment by ev-br** [comment]
Is it really a segfault? On my machine, it fails with a MemoryError on the second line. Which is as graceful as it can get, I'd say.

**Comment by atbd** [comment]
Yes, it is. You need at least 4,5Gb just for im and gr plus few Gb for map_coordinates which generates some arrays.

I don't have access to my work machine until may, 9th but I checked my original data with scipy-current and the segfault is still present. Unfortunately I cannot reproduce it with random matrixes on current.

I'll check this bug in depth next week with gdb on scipy-current.

**Comment by atbd** [comment]
I debugged my code with gdb on scipy-0.12, the segfault is in the NI_GeometricTransform function. The value of idxs[hh] seems to be too big.

```
Catchpoint 2 (signal SIGSEGV), 0x00007fffea717294 in NI_GeometricTransform (input=<optimized out>, map=<optimized out>, map_data=<optimized out>, matrix_ar=<optimized out>,
    shift_ar=<optimized out>, coordinates=<optimized out>, output=0x729a060, order=3, mode=4, cval=<optimized out>) at scipy/ndimage/src/ni_interpolation.c:592
592                         CASE_INTERP_COEFF(coeff, pi, idxs[hh], Float64);
(gdb) l
587                         CASE_INTERP_COEFF(coeff, pi, idxs[hh], Int8);
588                         CASE_INTERP_COEFF(coeff, pi, idxs[hh], Int16);
589                         CASE_INTERP_COEFF(coeff, pi, idxs[hh], Int32);
590                         CASE_INTERP_COEFF(coeff, pi, idxs[hh], Int64);
591                         CASE_INTERP_COEFF(coeff, pi, idxs[hh], Float32);
592                         CASE_INTERP_COEFF(coeff, pi, idxs[hh], Float64);
593                     default:
594                         PyErr_SetString(PyExc_RuntimeError,
595                                                         "data type not supported");
596                         goto exit;
```
```
#define CASE_INTERP_COEFF(_coeff, _pi, _idx, _type) \
case t ## _type:                                    \
    _coeff = *(_type*)(_pi + _idx);                   \
    break;
```
I tried to reproduce it with scipy-0.17 and current but the bug has been corrected on those versions.

**Comment by ev-br** [comment]
Thanks for checking. By now scipy 0.12 is really recommended to upgrade from.
