### ISSUE TITLE
Failures with latest MKL

### ISSUE THREAD

**Issue by Eric89GXL** [scipy/scipy#6132]
Intel just released the 16.0.3 Parallel studio, and I now have a bunch of test failures of the form:
```
======================================================================
ERROR: test_decomp_update.TestQRinsert_D.test_Mx1_economic_p_col
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/larsoner/custombuilds/nose/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/linalg/tests/test_decomp_update.py", line 881, in test_Mx1_economic_p_col
    q1, r1 = qr_insert(q, r, u, col, 'col', overwrite_qru=False)
  File "scipy/linalg/_decomp_update.pyx", line 1816, in scipy.linalg._decomp_update.qr_insert (scipy/linalg/_decomp_update.c:28082)
  File "scipy/linalg/_decomp_update.pyx", line 2132, in scipy.linalg._decomp_update.qr_insert_col (scipy/linalg/_decomp_update.c:31692)
ValueError: The 7th argument to ?geqrf was invalid
```
I read in their release notes that they made some checks more strict, this must be the effect.

**Comment by ewmoore** [comment]
I'll look into this.  Can you post the full log somewhere?

**Comment by Eric89GXL** [comment]
[Done] (https://gist.github.com/Eric89GXL/9d0ce7b04ad9a992da8412ed485be8db). Note that there are a couple of other failures at the end that also came up with my latest build, but they also happened when I built with 16.0.2 so I don't think they're related to this GEQRF issue.

**Comment by pv** [comment]
the 7th argument is lwork. maybe add print statements printing the
computed lwork and the size integer-valued input arguments for *qeqrf,
to verify the issue is not in mkl (e.g. wrong value returned from lwork
query).

**Comment by Eric89GXL** [comment]
After some fairly ugly hacks I was able to print out a few variables from `qr_block_col_insert` in the `if m >= n` block, first [after the] (https://github.com/scipy/scipy/blob/master/scipy/linalg/_decomp_update.pyx.in#L728) `geqrf` call, and then again [after the] (https://github.com/scipy/scipy/blob/master/scipy/linalg/_decomp_update.pyx.in#L733) `lwork = to_lwork(c, s)` call, since I'm pretty sure that's where one of the failures is:
```
test_decomp_update.TestQRinsert_D.test_Mx1_economic_p_col ... 
Intel MKL ERROR: Parameter 5 was incorrect on entry to ZGEQRF.


m=8
n=4
k=0
p=3
info=-5
lwork=0


Intel MKL ERROR: Parameter 8 was incorrect on entry to ZUNMQR.


m=8
n=4
k=0
p=3
info=-8
lwork=0


Intel MKL ERROR: Parameter 7 was incorrect on entry to ZGEQRF.
ERROR

======================================================================
ERROR: test_decomp_update.TestQRinsert_D.test_Mx1_economic_p_col
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/larsoner/custombuilds/nose/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/larsoner/custombuilds/scipy/scipy/linalg/tests/test_decomp_update.py", line 881, in test_Mx1_economic_p_col
    q1, r1 = qr_insert(q, r, u, col, 'col', overwrite_qru=False)
  File "scipy/linalg/_decomp_update.pyx", line 1822, in scipy.linalg._decomp_update.qr_insert (scipy/linalg/_decomp_update.c:28062)
  File "scipy/linalg/_decomp_update.pyx", line 2131, in scipy.linalg._decomp_update.qr_insert_col (scipy/linalg/_decomp_update.c:31473)
ValueError: The 7th argument to ?geqrf was invalid

----------------------------------------------------------------------
Ran 1 test in 0.035s
```
For both ZGEQRF and ZUNMQR, the input it's complaining about (5 and 8, respectively) is `tau`.

Is that helpful?

**Comment by ewmoore** [comment]
Yes.  I'm fairly certain that the issues is passing a null pointer in to the tau parameter.  This worked earlier (and in other lapacks) since tau isn't referenced when computing lwork.  I'll submit a PR with a fix later today or tomorrow.

**Comment by Eric89GXL** [comment]
Thanks, I'm happy to pull and test when you have it.

**Comment by ewmoore** [comment]
See #6135.

**Comment by cgohlke** [comment]
FWIW, I opened a premier support issue with Intel on 5/3/2016.

**Comment by Eric89GXL** [comment]
@cgohlke is it related to this? Can you link to it?

I [raised an issue with them related to SVD failures] (https://software.intel.com/en-us/comment/1870828) in case anyone is curious.

**Comment by cgohlke** [comment]
Yes, it is the same issue. Scipy 0.17.0 fails 52 tests when run with MKL 11.3.3 on Windows. I can not link to the issue because it is private (the Intel forum rejected my post as spam).
I will test #6135 now and report back.

**Comment by Eric89GXL** [comment]
I mean can you share a link here to the post on Intel's site?
