### ISSUE TITLE
Error in Cosmo Transitions when calling scipy

### ISSUE THREAD

**Issue by nmu003** [scipy/scipy#6133]
I am running a program called Vevacious, which is a python/C++ code for finding the minima of an important function in supersymmetry (physics) and calculating transition times between minima. Vevacious calls another program called Cosmo Transitions (CT) to calculate these transition times, which itself calls scipy. Vevacious worked without issue using an older version of scipy a few years back, but it seems that the newest versions of scipy cause problems. CT crashes with error message 

<<   File "/usr/local/lib/python2.7/site-packages/scipy/optimize/zeros.py", line 429, in brentq

    r = _zeros._brentq(f,a,b,xtol,rtol,maxiter,args,full_output,disp)

ValueError: f(a) and f(b) must have different signs
>>. 

I am running scipy version 0.16.1. If anyone has any ideas about what this might mean, or any advice to help me dig a little deeper to give a better diagnostic of what is actually happening, I would greatly appreciate it!

**Comment by ev-br** [comment]
You can trigger this error by doing just like it says on the box:

```
>>> def f(x):
...    return x**2 + 1
... 
>>> from scipy.optimize import brentq
>>> brentq(f, 0, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/br/virtualenvs/scipy/lib/python3.5/site-packages/scipy/optimize/zeros.py", line 442, in brentq
    r = _zeros._brentq(f,a,b,xtol,rtol,maxiter,args,full_output,disp)
ValueError: f(a) and f(b) must have different signs
```

Or, if you did not separate the roots properly,

```
>>> brentq(lambda x: x**3, 2, 3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module> 
  File "/home/br/virtualenvs/scipy/lib/python3.5/site-packages/scipy/optimize/zeros.py", line 442, in brentq
    r = _zeros._brentq(f,a,b,xtol,rtol,maxiter,args,full_output,disp)
ValueError: f(a) and f(b) must have different signs
```

To debug this, I'd set up two virtualenvs with new and old (i.e., working) versions of all dependencies (numpy, scipy etc), set a breakpoint just before the error and walk it in pdb in parallel.

So far, there is no evidence that this is actually a scipy bug, so I'm going to close this. Feel free to keep discussing it here (even though you might find a broader readership in Stackoverflow or scipy-user mailing list). 
Please reopen if there is a reproducer which shows a scipy bug.
Good luck with debugging it!
