### ISSUE TITLE
T test does not handle nans

### ISSUE THREAD

**Issue by brunomorvan** [scipy/scipy#6134]
The bug is in line 3885, in file scipy/scipy/stats/stats.py :

```
[contains_nan, nan_policy = (_contains_nan(a, nan_policy) or
                            _contains_nan(b, nan_policy))
```
must be

```
contains_nan             = _contains_nan(a, nan_policy)[0] or
                            _contains_nan(b, nan_policy)[0]
```

since logic apply good only on Boolean values.

See [http://stackoverflow.com/questions/37022888/t-test-in-scipy-with-nan-values/37026951](url)
for an exemple.

**Comment by ev-br** [comment]
To clarify, here's a reproducer:

```
>>> vstr = """0   1.714286  0.000000
... 1   4.275862  4.000000
... 2   0.500000  4.625000
... 3   1.000000  0.000000
... 4   1.000000  4.000000
... 5   1.142857  1.000000
... 6   2.000000  1.000000
... 7   9.416667  1.956522
... 8   2.052632  0.571429
... 9   2.100000  0.166667
... 10  0.666667  0.000000
... 11  2.333333  1.705882
... 12  2.768145       NaN
... 13  0.000000       NaN
... 14  6.333333       NaN
... 15  0.928571       NaN"""
>>> xxx = np.asarray([[ float(x) for x in _.split()] for _ in vstr.splitlines()])
>>> from scipy import stats
>>> stats.ttest_ind(xxx[:, 1], xxx[:, 2], nan_policy='raise')      # should have raised an error!
Ttest_indResult(statistic=array(nan), pvalue=nan)
>>> stats.ttest_ind(xxx[:, 1], xxx[:, 2], nan_policy='omit')  
Ttest_indResult(statistic=array(nan), pvalue=nan)
```

The result of `nan_policy="omit"` should be, I believe, equivalent to 
```
>>> mask = np.isnan(xxx[:, 2])
>>> stats.ttest_ind(xxx[:, 1][~mask], xxx[:, 2][~mask])
Ttest_indResult(statistic=array(0.8875246471860921), pvalue=0.38439692093551037
```

I'm surprised this has not been caught by the tests.

**Comment by ev-br** [comment]
I'd like to have this fixed for 0.17.1 --- so that this bug is the last blocker for the 0.17.1 release. (Again.)

**Comment by ev-br** [comment]
The fix in the OP is incomplete: `_contains_nan` returns `nan_policy` on purpose: If the nan check fails, it returns the default nan_policy 'omit' instead of what was passed in.

The check needs to combine not only `contains_nan`s for two arrays but also have a stanza similar to 
```
if nan_policy_a == 'omit' or nan_policy_b == 'omit':
      nan_policy = 'omit'
```

**Comment by ev-br** [comment]
The fix is needed in these three functions: `ttest_ind, ttest_rel, kendaltau`
Would you be interested in a PR @brunomorvan ?
The fix would need to include regression tests for all three functions.

**Comment by ev-br** [comment]
Start of the fix is here: https://github.com/scipy/scipy/pull/6148

Note that the fix via pandas suggested on SO drops nans in *both* arguments, while R seems to only drop NAs themselves.
@josef-pkt @rgommers @WarrenWeckesser @argriffing would appreciate your input on the best way to handle nans. ISTM we can make it right without worrying about backwards compat in 0.17.1 since nan_policy is new in 0.17.1.
