### ISSUE TITLE
Failures on `master` with MKL

### ISSUE THREAD

**Issue by Eric89GXL** [scipy/scipy#6136]
I have a couple of failures on `master` when building with MKL:
```
======================================================================
ERROR: test_nonlin.TestNonlin.test_problem_nonlin(<function F4_powell at 0x7f57dfaf1500>, <function newton_krylov at 0x7f57ec2de140>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/larsoner/custombuilds/nose/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/optimize/tests/test_nonlin.py", line 105, in _check_nonlin_func
    x = func(f, f.xin, f_tol=f_tol, maxiter=200, verbose=0)
  File "<string>", line 8, in newton_krylov
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/optimize/nonlin.py", line 347, in nonlin_solve
    raise NoConvergence(_array_like(x, x0))
NoConvergence: [ 0.00196136  0.05025112]

======================================================================
FAIL: test_nonlin.TestNonlin.test_problem_root(<function F4_powell at 0x7f57dfaf1500>, 'krylov')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/larsoner/custombuilds/nose/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/larsoner/.local/lib/python2.7/site-packages/scipy/optimize/tests/test_nonlin.py", line 111, in _check_root
    assert_(np.absolute(res.fun).max() < f_tol)
  File "/home/larsoner/.local/lib/python2.7/site-packages/numpy-1.12.0.dev0+1fc180b-py2.7-linux-x86_64.egg/numpy/testing/utils.py", line 63, in assert_
    raise AssertionError(smsg)
AssertionError
```
Are these known errors? If not, I can try to do a `git bisect` to see where they arose.

**Comment by ev-br** [comment]
@cgohlke did these show up in your testing of #6135 on Windows?

**Comment by cgohlke** [comment]
No, but I did only test #6135 with scipy-0.17.0 and Python 3.5.

**Comment by Eric89GXL** [comment]
I still have these failures on `master`. I have verified they do not exist on 0.17, so this is a regression. From `git bisect` I've isolated it to this commit by @pv:

https://github.com/scipy/scipy/commit/62fa198d41c434ff49692cc3bed15e0dba1c61be

@pv any idea why this might have broken things on my MKL build? It might be an Intel bug I suppose.

**Comment by pv** [comment]
The QR update approach IIRC increases the accumulated rounding error 
somewhat. Perhaps this is even larger with MKL (does MKL have different 
accuracy vs. speed modes?).

**Comment by Eric89GXL** [comment]
I don't know of any accuracy vs speed tweaks in MKL. I've never had to set any, at least, so I should be using the defaults if there are any.

I can confirm that reverting `scipy/sparse/linalg/isolve/lgmres.py` in `master` gets tests passing again. Do you think we should revert, should we tweak the failing tests to be less sensitive to rounding error, or is there another option?

**Comment by pv** [comment]
I would simply disable the failing tests.

**Comment by Eric89GXL** [comment]
You mean I should do it locally, or we should do it for the repo?

Doing it locally doesn't seem like a very good solution, since other people might also hit the issue.

Doing it for the repo doesn't seem that great, since the tests were presumably put there in the first place for a reason. Perhaps they were too sensitive to numerical error, but it seems like we could fix them.

Why just disable them? For expediency?

**Comment by pv** [comment]
Disable them because the converge is likely sensitive to rounding error, and so the failure may not indicate very much.

If you plot the residuals on a machine where it works, you see that the convergence is very slow for the first 100+ iterations and the number of iterations required is close to the maxiter=200: https://gist.github.com/pv/3a704c54b6b628762fc3afdfbfb55cc3
Now, it may be of interest to compare this result to what you get with MKL, and check if it works if you increase maxiter above 200.

**Comment by Eric89GXL** [comment]
Looks like it's quite different from yours:

![figure_1](https://cloud.githubusercontent.com/assets/2365790/15835570/97d08244-2bfe-11e6-805e-464365fa2c18.png)

And with the old `lgmres.py` it's very similar:

![old](https://cloud.githubusercontent.com/assets/2365790/15835636/de0d74f6-2bfe-11e6-891d-6c3633635809.png)

So I suspect there is some uglier underlying bug.

**Comment by pv** [comment]
Probably fixed in gh-6214 --- it's indeed a bug.

**Comment by Eric89GXL** [comment]
Great, I should be able to try tonight or tomorrow

**Comment by rgommers** [comment]
fixed by gh-6214, closing.
