### ISSUE TITLE
Request: transformation functions - Yeo-Johnson

### ISSUE THREAD

**Issue by mmesgarpour** [scipy/scipy#6141]
It would be great if you could expand on the transformation functions. 

At the moment BoxCox, center, scale and range are supported and a handful other from scikit-learn. However, some popular models, such as Yeo-Johnson, are missing.

Thanks.

References:
Kuhn and Johnson (2013), Applied Predictive Modeling, Springer
Kuhn (2008), Building predictive models in R using the caret

**Comment by ev-br** [comment]
As discussed on SO, http://stackoverflow.com/questions/37037837/python-library-yeo-johnson-tranformation, this is quite easy to do from the user side. You might need to add some motivation of why this is a worthy add to the library. If this is reasonably widely used, we can add it; if it's a one-shot thing, then it belongs to the user code.

**Comment by mmesgarpour** [comment]
Thanks for the quick reply. 
I agree with your view, it is not a priority, and it is very hard to say how popular it is. 
Thanks

**Comment by vwood** [comment]
Why was this never done? The linked question only contains the actual transform, which while trivial is useless without a function as stats.boxcox() to find lambda. This is not 'easy to do from the user side'

**Comment by rgommers** [comment]
> Why was this never done?

Because no one argued for its including here, which would be step 1. And no one stepped up to actually implement this, which would be step 2.

**Comment by mattspinelli** [comment]
> Because no one argued for its including here, which would be step 1. And no one stepped up to actually implement this, which would be step 2.

This would be helpful anytime we have a mix of negative and positive values (Box-Cox works only for all positive or all negative). The fact it's inclusion is already available in R suggests it's a helpful function for statistics. As to step 2, I don't have time to contribute right away, but I might be able to later.

**Comment by NicolasHug** [comment]
I implemented the Yeo-Johnson transform in scikit-learn (scikit-learn/scikit-learn#11520). It will be released with version 0.20.

The implementation is based on that of `scipy.stats.boxcox` and uses the brent solver with MLE. 

Would it be a welcome addition to scipy? If yes, I could work on this.

Like previously mentioned, Yeo-Johnson can deal with negative values while Box-Cox cannot, which is the main reason it was included in scikit learn.

**Comment by josef-pkt** [comment]
It would also be useful for statsmodels (although it looks like I never opened an issue for it)
So, I'm in favor of getting it into scipy.

**Comment by rgommers** [comment]
PR welcome seems to be the consensus:)
