### ISSUE TITLE
segfault in linkage with incomplete data

### ISSUE THREAD

**Issue by gregory-marton** [scipy/scipy#6143]
The following produces a nice heatmap:
```
import pandas
df = pandas.DataFrame([['foo', 'foo', 1],
                       ['foo', 'bar', 0],
                       ['foo', 'caz', .2],
                       ['bar', 'foo', 0],
                       ['bar', 'bar', 1],
                       ['bar', 'caz', .5],
                       ['caz', 'foo', .2],
                       ['caz', 'bar', .5],
                       ['caz', 'caz', 1]])
import seaborn
seaborn.clustermap(df, pivot_kws={'index': df.columns[0], 
                                  'columns': df.columns[1], 
                                  'values': df.columns[2]})
```

The following produces a nice segfault:
```
import pandas
df = pandas.DataFrame([['foo', 'foo', 1],
                       ['foo', 'bar', 0],
                       ['foo', 'caz', .2],
#                       ['bar', 'foo', 0],
                       ['bar', 'bar', 1],
                       ['bar', 'caz', .5],
                       ['caz', 'foo', .2],
                       ['caz', 'bar', .5],
                       ['caz', 'caz', 1]])
import seaborn
seaborn.clustermap(df, pivot_kws={'index': df.columns[0], 
                                  'columns': df.columns[1], 
                                  'values': df.columns[2]})
```

Commenting out any subset of the complete square matrix above that doesn't trigger the too-few-elements guard causes a segfault. My gdb gave the following backtrace:
```
#0  0x00007fffe4f89110 in __pyx_pf_5scipy_7cluster_10_hierarchy_22linkage (__pyx_self=<optimized out>, __pyx_v_method=0, __pyx_v_n=2, 
    __pyx_v_Z=<optimized out>, __pyx_v_dists=...) at scipy/cluster/_hierarchy.c:8851
#1  __pyx_pw_5scipy_7cluster_10_hierarchy_23linkage (__pyx_self=<optimized out>, __pyx_args=<optimized out>, __pyx_kwds=<optimized out>)
    at scipy/cluster/_hierarchy.c:8519
```

**Comment by gregory-marton** [comment]
My colleague @riastradh-probcomp adds:
```
hierarchy.py", line 1412, in is_valid_linkage
    name_str)
ValueError: Linkage 'Z' contains negative indices.
```

**Comment by rgommers** [comment]
Thanks for the report @gregory-marton. If the issue occurred with 0.17.0 it's probably still present.

**Comment by rgommers** [comment]
This doesn't segfault anymore, but gives 

    /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/seaborn/matrix.py in _calculate_linkage_scipy(self)
        570 
        571         pairwise_dists = distance.pdist(self.array, metric=self.metric)
    --> 572         linkage = hierarchy.linkage(pairwise_dists, method=self.method)
        573         del pairwise_dists
        574         return linkage

    /Users/rgommers/Code/scipy/scipy/cluster/hierarchy.py in linkage(y, method, metric)
        682 
        683     if not np.all(np.isfinite(y)):
    --> 684         raise ValueError("`y` must contain only finite values.")
        685 
        686     n = int(distance.num_obs_y(y))

    ValueError: `y` must contain only finite values.

**Comment by rgommers** [comment]
The values that ``seaborn.clustermap`` feeds to ``distance.pdist`` and ``linkage`` contain a NaN:

    >>> self.data

    1    bar  caz  foo
    0                 
    bar  1.0  0.5  NaN
    caz  0.5  1.0  0.2
    foo  0.0  0.2  1.0

**Comment by rgommers** [comment]
What's left now is an issue in ``seaborn``. The problem is that it converts the DataFrame to square form, which with incomplete data means there are NaNs. At https://github.com/mwaskom/seaborn/blob/master/seaborn/matrix.py#L733 it constructs ``data2d`` for that, and straight after a ``mask`` attribute to take care of the NaNs for plotting. However, the mask is not applied before sending data to ``pdist``.

**Comment by rgommers** [comment]
I've commented on https://github.com/mwaskom/seaborn/issues/449, there's nothing else to fix here now that we get an understandable exception. ``seaborn.clustermap`` should internally take care not to send an array containing NaNs to ``pdist`` and ``linkage``.

Thanks @gregory-marton for the report.
