### ISSUE TITLE
Re: stable evaluation of expit

### ISSUE THREAD

**Issue by colinfang** [scipy/scipy#6145]
Based on  #3386, `special.expit` is implemented like

```
if x < 0
    a = exp(x) 
    a / (1 + a) 
else 
    1 / (1 + exp(-x))
```

However, in other languages/frameworks (such as Julia, R), it is simply implemented as

`1 / (1 + exp(-x))`

I don't think it has numerical instability at `x < 0`.

According to IEEE, `exp(800)` would emit `Inf`, which is OK as `1 / (1 + exp(800) = 1 / Inf = 0`. In such case the other brance doesn't provide with extra precisions. `exp(-800) / 1 + exp(-800) = 0`

**Comment by argriffing** [comment]
That PR flipped the inequality on the first line; prior to that PR, the implementation failed for large `x`. Maybe you're right, and the first branch of the conditional could just be removed.

**Comment by argriffing** [comment]
> in other languages/frameworks (such as Julia, R), it is simply implemented as

By the way, in general it's not cool to read R code and implement it in scipy; it's against licensing terms.

**Comment by colinfang** [comment]
nvm, in c `exp(800)` overflows and triggers an error.

**Comment by argriffing** [comment]
it seems to work OK in https://github.com/scipy/scipy/pull/6146 and passes tests

**Comment by colinfang** [comment]
Sry, I was confused about c & c++ exception... There is no exception in C.
