### ISSUE TITLE
How can I call lapack routine dstev from scipy

### ISSUE THREAD

**Issue by coolplay** [scipy/scipy#6149]
In Scipy, I can directly access lapack routines, like `zheev`, with `scipy.linalg.lapack.zheev`. But it seems not working with some lapack routines like [dstev](http://www.netlib.org/lapack/explore-html/d7/d48/dstev_8f.html), which is used to diagonalize real, symmetric tridiagonal matrix.

Any comment is appreciated.

**Comment by pv** [comment]
The short answer is that if it's not there, you can't. Before someone
contributes the f2py wrapper code to Scipy.

**Comment by coolplay** [comment]
Thanks, but would it be a good idea to expose all driver routines in lapack to `scipy.linalg.lapack`.

**Comment by pv** [comment]
Yes. But as long as Scipy's annual budget is $0, it will depend on someone sending a PR for it.
