### ISSUE TITLE
mannwhitneyu p values doubled from Scipy 0.16 to 0.17?!

### ISSUE THREAD

**Issue by Wainberg** [scipy/scipy#6156]
Scipy 0.17 added an 'alternative' keyword to mannwhitneyu which can be 'two-sided' (default), 'greater', or 'less', as mentioned in the [release notes](http://docs.scipy.org/doc/scipy/reference/release.0.17.0.html).  However, the default in 0.16 was one-sided, where the direction (greater or less) was selected based on the data (this is [problematic](http://stats.stackexchange.com/a/125027/54578)).  This change in the default behaviour was not documented, and would result in end users seeing their p values double when upgrading from 0.16 to 0.17.  The [current documentation](http://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mannwhitneyu.html) does not mention the new option and still lists the default as being one-sided.

**Comment by josef-pkt** [comment]
This has been fixed in #6100 and should be in 0.17.1

Note: the reason the "appalling" behavior is there because of backwards compatibility, At least there are now proper p-values if an alternative is specified.

**Comment by Wainberg** [comment]
Thanks, sorry I didn't look through the pull requests before posting this.  It looks like the documentation will also be corrected (https://github.com/scipy/scipy/pull/6034).
