### ISSUE TITLE
Linux wheels not published for 0.17.1

### ISSUE THREAD

**Issue by jamesatha** [scipy/scipy#6157]
When will the linux wheels be published? I'm having errors with not having a fortran compiler and the MKL library (this is when installing through anaconda). Having the wheels published should help

**Comment by ev-br** [comment]
They will be built when someone builds them :-). FWIW, don't know how and I'm not able to invest any non-trivial amount of time into it at the moment.

To the best of my knowledge, the linux wheel build process is not automated. The best way forward is probably to set up a build infrastructure similar to https://github.com/MacPython, where release managers would be able to trigger wheel builds. (Thank you Matthew for setting it up.)

**Comment by matthew-brett** [comment]
I just triggered a build here : https://travis-ci.org/matthew-brett/manylinux-builds/builds/129840832

I did this by editing the scipy version here : https://github.com/matthew-brett/manylinux-builds/blob/master/build_stack.sh#L11

If the builds work, and the tests pass, then they should appear at http://ccdd0ebb5a931e58c7c5-aae005c4999d7244ac63632f8b80e089.r77.cf2.rackcdn.com in the next hour or so.

I've made you (Evgeni) a collaborator on that repo in case you can do any work there.  @ogrisel is an expert - maybe you can help?   Sorry, I'm in Cuba at the moment, internet is tough.

**Comment by matthew-brett** [comment]
Evgeni - I see the build is running slowly - I guess it will take a few hours.  On the other hand, it would be good to assure ourselves that the build passes the tests.

I have also built binaries for scipy 0.17.1 up at http://nipy.bic.berkeley.edu/manylinux/  .  These I have not tested.   If you can install from there and test, and the tests pass, I guess these binaries are fine too...

**Comment by ev-br** [comment]
I tested the python 3.5 wheel from  http://nipy.bic.berkeley.edu/manylinux/ and *tests pass on my machine* (tm).  So these wheels are likely fine --- thanks Matthew! 
Some more testing would be nice though before we upload them to pypi to make them default.

**Comment by ogrisel** [comment]
I just created a new venv with ubuntu's 14.04 default system python 3.4 and pip installed -f  https://nipy.bic.berkeley.edu/manylinux/ numpy scipy and the full test suite pass.

I will now run the tests with the system python 2.7.

**Comment by ogrisel** [comment]
For Python 2.7:

```
OK (KNOWNFAIL=132, SKIP=1830)
```

**Comment by matthew-brett** [comment]
Meanwhile the tests passed on the manylinux-builds travis-ci run, and are as expected over at http://nipy.bic.berkeley.edu/builders, so the uploaded wheels at

https://d9a97980b71d47cde94d-aae005c4999d7244ac63632f8b80e089.ssl.cf2.rackcdn.com/

(and also http://ccdd0ebb5a931e58c7c5-aae005c4999d7244ac63632f8b80e089.r77.cf2.rackcdn.com/) should be good to go.  Probably the ones a nipy.bic.berkeley.edu will be OK as well.

**Comment by ev-br** [comment]
Meanwhile I've manually uploaded the wheels from https://nipy.bic.berkeley.edu/manylinux/
Let's keep the fingers crossed :-).

Thanks @matthew-brett @ogrisel

**Comment by ogrisel** [comment]
@matthew-brett what is your plan w.r.t. making it easier for upstream to generate their own wheels themselves? Do you think we should extend the scripts used by https://github.com/macpython such as https://github.com/macpython/scipy-wheels to be able to generate both OSX and linux wheels with the same github repo?

**Comment by matthew-brett** [comment]
That was one idea - the other was to see whether it was practical to generate the wheels as part of the standard travis-ci test grid, maybe with a upload only on tag.    The idea would be to routinely generate the wheels, and test against them, but only upload on tag.  What do you think?

**Comment by ogrisel** [comment]
I am not sure: for scikit-learn we generate the windows wheels using appveyor to a temporary storage container and as a release manager I use [wheelhouse-uploader](https://github.com/ogrisel/wheelhouse-uploader) to download all the wheels of a specific releases for windows, mac osx and in the future linux and then manually do a single call to `twine upload dist/*` to upload all the wheels and the sdist tarball to PyPI at once to make the release.

Otherwise there is no easy way to synchronize the release of all the wheels + source.

**Comment by rgommers** [comment]
Upload on tag to travis-dev-wheels.scipy.org, and then just letting the release manager use wheelhouse-uploader sounds like a better option than either the MacPython way or direct on-tag-upload-to-pypi I think.

**Comment by rgommers** [comment]
Very nice wheel machinery by the way Matthew - that came together pretty quickly!

**Comment by matthew-brett** [comment]
I spent some time following Olivier's suggestion - the MacPython scipy-wheels repo now builds and tests manylinux 32- and 64-bit wheels:

* https://travis-ci.org/MacPython/scipy-wheels
* https://github.com/MacPython/scipy-wheels

It's using some common build machinery, in a submodule, here:

* https://github.com/matthew-brett/multibuild

This is flexible enough to handle numpy, scipy, matplotlib and astropy builds, but it's still a work in progress.
