### ISSUE TITLE
Artefacts in griddata result with anisotropic grids

### ISSUE THREAD

**Issue by mjsv** [scipy/scipy#6159]
I was trying to interpolate 2D XYZ data sets that are dense along one axis and sparse along the other. Finally I calculated the gradient of the interpolated result and discovered some nasty numerical artefacts. 

Below you see the row-wise numpy.diff of a 101x101 XYZ test dataset:
![original](https://cloud.githubusercontent.com/assets/1859677/15251552/45d567f2-192a-11e6-8721-165ea6fb3c29.png)

From this dataset I draw vertical lines at row indices 0, 50 and 100, interpolate those onto the same XY grid that was used to generate the original dataset and take the diff again. The result is shown below and it looks as expected. The contours are straighter than in the above image.
![output](https://cloud.githubusercontent.com/assets/1859677/15251553/45e6d5be-192a-11e6-9559-871bc0270dfa.png)

Now I repeat this again but this time I truncate the Y range of the grid, effectively sampling with a finer grid. The result is shown below and artefacts appear between the three original vertical lines.
![output_trunc](https://cloud.githubusercontent.com/assets/1859677/15251554/46027f80-192a-11e6-9930-caed72c9febc.png)

Below is a script that demonstrates the effect. I ran it against three different versions of Scipy, all showing the same behaviour.

```python
import numpy as np
from scipy.interpolate import griddata

import matplotlib.pyplot as plt

def func(x,y,m,s):
    return np.exp(-((x-m)**2 + (y-m)**2) / s**2)

if __name__ == '__main__':
    W = 33 # half-width
    N = 101 # number of points
    pw = 0.9
    pn = 1

    x = np.linspace(-W,W,N)
    y = np.linspace(-W,W,N)
    X,Y = np.meshgrid(x,y)
    Z = func(X,Y,25,50) + func(X,Y,-25,50)

    plt.figure(0)
    plt.pcolormesh(X[:-1,:], Y[:-1,:]
                   , np.diff(Z, axis=0))
    plt.xlim(-W, W)
    plt.ylim(-W, W)
    plt.title("Original data")

    gx = np.linspace(-W, W, N)
    gy = np.linspace(-W, W, N)
    gX, gY = np.meshgrid(gx, gy)
    slc = slice(0,None,50)
    gZ = griddata((X[:,slc].ravel(), Y[:,slc].ravel())
                  , Z[:,slc].ravel()
                  , (gX, gY)
                  , method='linear')

    plt.figure(2)
    plt.pcolormesh(gX[:-1,:], gY[:-1,:]
                   ,np.ma.masked_invalid(np.diff(gZ, axis=0)))
    plt.xlim(-W, W)
    plt.ylim(-W, W)
    plt.title("Interpolation of 3 vertical lines on original grid")

    gy = np.linspace(-pw*W, pw*W, pn*N)
    gX, gY = np.meshgrid(gx,gy)
    gZ2 = griddata((X[:,slc].ravel(), Y[:,slc].ravel())
                  , Z[:,slc].ravel()
                  , (gX, gY)
                  , method='linear')

    plt.figure(3)
    plt.pcolormesh(gX[:-1,:], gY[:-1,:]
                   , np.diff(gZ2, axis=0))
    plt.xlim(-W, W)
    plt.ylim(-W, W)
    plt.title("Interpolation of 3 vertical lines on vertically truncated grid")

    plt.show()


```

**Comment by pv** [comment]
That is an expected property of the interpolation method. The 
interpolant is piecewise linear `a + b x + c y` on triangles. There's no 
guarantee that you get a smooth approximation to the gradient (or diff) 
from this.
```
from scipy.interpolate import LinearNDInterpolator
ip = LinearNDInterpolator((X[:,slc].ravel(), Y[:,slc].ravel()), 
Z[:,slc].ravel())
gZ2 = ip(gX, gY)
delaunay_plot_2d(ip.tri)
```
should help to explain the structure.

**Comment by pv** [comment]
Since your data is on a regular grid, you should use 
`scipy.interpolate.interpn` instead of `griddata`.
