### ISSUE TITLE
fmin_l_bfgs_b returns inconsistent results (fmin ≠ f(xmin)) and can return arbitrarily bad results when stopped by maxfun

### ISSUE THREAD

**Issue by jonasrauber** [scipy/scipy#6162]
## Problem
scipy.optimize.fmin_l_bfgs_b returns inconsistent results and can return arbitrarily bad results even when better ones have been seen before.

See this minimal working example: https://gist.github.com/jonasrauber/41da8b80342c437ecc3e41c743aff98f

## Reason
If the number of function evaluations reaches maxfun, the algorithm returns the function value returned by last function call as fmin and the x that would be used for the next function call as xmin. Both are wrong, because they are from within the line search and thus neither the current nor the next function call are guaranteed to represent the optimum of the function evaluations done so far.

## Solution
Instead, the algorithm should only return results of completed iterations, i.e. by either restoring xmin and fmin of the last completed iteration or completing the current iteration despite reaching maxfun.

**Comment by argriffing** [comment]
cc @dmcooke

**Comment by argriffing** [comment]
> Instead, the algorithm should only return results of completed iterations, i.e. by either restoring xmin and fmin of the last completed iteration or completing the current iteration despite reaching maxfun.

@jonasrauber I've implemented the latter option in https://github.com/scipy/scipy/pull/6240.

**Comment by argriffing** [comment]
> the algorithm should only return results of completed iterations

This has now been merged!
