### ISSUE TITLE
String format issue in constructor of LinAlgError

### ISSUE THREAD

**Issue by WKarel** [scipy/scipy#6168]
In scipy.linalg.basic, line 174, there is:

LinAlgError("singular matrix: resolution failed at diagonal %s" %  info-1)

The modulo operator has higher precedence than the (binary) minus operator, and thus this is evaluated as:
LinAlgError( ( "singular matrix: resolution failed at diagonal %s" %  info ) -1)

resulting in:
TypeError: unsupported operand type(s) for -: 'str' and 'int'

Braces around
info-1
should fix that.

SciPy 0.17.1, Python 3.5.1, Win 7 x64

**Comment by ev-br** [comment]
Would you be interested in sending a PR with a fix?

**Comment by ev-br** [comment]
In fact, it appears to have been fixed in master: https://github.com/scipy/scipy/blob/master/scipy/linalg/basic.py#L174. Git blame points to https://github.com/scipy/scipy/pull/5472.

Thanks for reporting it @WKarel.
