### ISSUE TITLE
scipy.linalg.expm gives incorrect results

### ISSUE THREAD

**Issue by javicc** [scipy/scipy#6171]
for example:

```
import numpy as np
from scipy.linalg import expm

A = np.matrix([[ 1, 0], [ 1, 1]])
Iden = expm(A) * expm(-1*A)
print(Iden)
```

[[ 1.  0.]
 [-1.  1.]]

**Comment by WarrenWeckesser** [comment]
The problem is that when given a `matrix` object, `expm` returns a numpy array.  With numpy arrays, `*` is elementwise multiplication, not matrix multiplication.  The `dot` method performs matrix multiplication:

```
In [668]: A = np.matrix([[ 1, 0], [ 1, 1]])

In [669]: expm(A).dot(expm(-1*A))
Out[669]: 
array([[ 1.,  0.],
       [ 0.,  1.]])
```

**Comment by javicc** [comment]
Thank you very much for your help
