### ISSUE TITLE
scipy.interpolate.lagrange implemented through coefficients

### ISSUE THREAD

**Issue by lzlarryli** [scipy/scipy#6173]
Currently `scipy.interpolate.lagrange` is implemented through multiplying `numpy.poly1d` factors. Thus the interpolant is saved and evaluated through polynomial coefficients. This is not robust even for a small number of nodes. For example, in my collocation ODE solver, the coefficients can blow up or the interpolant loses accuracy even with 3 nodes (at Gauss points of order 6), when the interval for the interpolant is small. 

The following is a proposal for a robust lagrange interpolant. The main difference is that the interpolant is saved and evaluated as linear factors not as polynomial coefficients. It offers robustness (avoid coefficient under- and over-flow) and superior interpolation accuracy with comparable speed. But, it is less accurate for far extrapolation (which is of questionable use) and loses the nice `numpy.poly1d` interface (like root, derivative, integrals, etc). Thus `robust_lagrange` might be nice to have as a separate function in addition to `scipy.interpolate.lagrange`.

``` python
import numpy
from scipy.interpolate import lagrange
from scipy.stats import describe

def robust_lagrange(x, y):
    x = numpy.array(x)
    @numpy.vectorize
    def interp(xn):
        dn = xn - x
        r = 0
        for i in range(len(x)):
            d = x[i] - x
            L =   numpy.product(dn[0:i] / d[0:i]) \
                * numpy.product(dn[i+1:] / d[i+1:])
            r = r + L * y[i]
        return r
    return interp

def accuracy_test(name, y1, y2):
    stats = describe(numpy.abs(y1 - y2))
    print('Error for {}'.format(name))
    print('   range:    {}'.format(stats.minmax))
    print('   mean:     {}'.format(stats.mean))
    print('   variance: {}'.format(stats.variance))

# a nasty interpolation problem on a tiny interval
# the correct result is just a line
small = 1e-10
x = [0, small, 2*small, 3*small, 4*small, 5*small, 6*small]
y = [0,     1,       2,       3,       4,       5,       6]

# create the interpolants
f = lagrange(x, y)
g = robust_lagrange(x, y)

print('--- Interpolation accuracy test ---')
z = numpy.linspace(0, 6*small, 10000)
exact = z / small
accuracy_test('scipy interpolant', exact, f(z))
accuracy_test('factored interpolant', exact, g(z))
print()

print('--- Extrapolation accuracy test ---')
z = numpy.linspace(1e-10, 1e-9, 10000)
exact = z / small
accuracy_test('scipy interpolant', exact, f(z))
accuracy_test('factored interpolant', exact, g(z))
print()
```

**Comment by pv** [comment]
Is this different/better from/than BarycentricInterpolator?

**Comment by lzlarryli** [comment]
@pv: It is different and easier from `BarycentricInterpolator`. In sum, compared to the base `lagrange`, `BarycentricInterpolator` is more accurate while `robust_lagrange` is more robust against under- and overflows. 

`BarycentricInterpolator` still saves some computed weights. The problem is that the weight computation involves divisions like $wj/(x_j-x_i)$, which can still overflow when the interval itself is small. The `robust_lagrange` here just saves the nodes and the function values in the closure and never save quantities obtained through division, thus circumvent this problem.

But yours is a very good point. Maybe a scaled version of `BarycentricInterpolator` will take the best of the both (ie, scale x so that the inner `BarycentricInterpolator` always runs on the unit interval)?

**Comment by ev-br** [comment]
OK, it is way too late to change the way `lagrange` works, even if the current implementation is not really up to scratch.  Adding one more way to represent a Lagrange interpolating polynomial is not really desirable. Updating the `BarycentricInterpolator`  or picking up gh-4674 would be nice. Are you interested in any of these @lzlarryli ?

**Comment by lzlarryli** [comment]
Thank you for reminding me of this:-) I can try to implement the normalized version according to Sec 7 of https://people.maths.ox.ac.uk/trefethen/barycentric.pdf.

I am not familiar with the rational interpolant mentioned in [gh-4674](https://github.com/scipy/scipy/pull/4674). But I can take a look as well. That would probably be a different step though.

**Comment by ev-br** [comment]
Great, looking forward for a PR! Or two :-)

**Comment by j-bowhay** [comment]
I think this could be closed as I am not sure there is anything actionable out of this issue.

> Thank you for reminding me of this:-) I can try to implement the normalized version according to Sec 7 of https://people.maths.ox.ac.uk/trefethen/barycentric.pdf.

Section 7 of the Trefethen paper deals with numerical stability. There are two points of discussion:
1. Underflow and overflow when calculating weights
2. Dealing with when $x=x_k$

Point 1 was addressed in #14255 and point 2 is already handled in the existing code.
https://github.com/scipy/scipy/blob/2e5883ef7af4f5ed4a5b80a1759a45e43163bf3f/scipy/interpolate/_polyint.py#L659-L665

Therefor I'm not sure there is anything left to do here.

**Comment by lzlarryli** [comment]
@j-bowhay Totally agree. Thank you so much for fixing this.
(My own feeble attempt to fix this has been delayed by my inability to compile scipy on my Mac M1.........)

**Comment by j-bowhay** [comment]
> @j-bowhay Totally agree. Thank you so much for fixing this.

Can't take any credit for the fix here, just going through issues!

> (My own feeble attempt to fix this has been delayed by my inability to compile scipy on my Mac M1.........)

Other than the documentation, there is a [slack group](scipy-community.slack.com) and a monthly new contributors meeting (announced on the mailing list) where I am sure there are plenty of people who would help if you have exhausted the documentation :smile:
