### ISSUE TITLE
linkage currently set to not handle minkowski distances

### ISSUE THREAD

**Issue by mlewis1729** [scipy/scipy#6174]
Hello,

So I noticed in the linkage code that the distance matrix is obtained with a call to

`distance.pdist(y, metric)`

where metric is the metric passed into linkage by the user. However, there are some metrics, for example the Minkowski metric, where subsequent parameters are needed (namely p). Is there a way to pass in extra parameters to linkage to utilize metrics such as that?

Thanks,
MIke

**Comment by rgommers** [comment]
You can define your own function that wraps an existing metric and provides the extra parameter(s) needed. Not super user-friendly, but it's only one or two extra lines. ``functools.partial`` may come in handy here.
