### ISSUE TITLE
Kernel Density Estimation (KDE)

### ISSUE THREAD

**Issue by innisfree** [scipy/scipy#6176]
The KDE functionality is a bit limited. We have `gaussian_kde` with basic rules of thumb for selecting the bandwidth. It doesn't utilize any sophisticated tricks (e.g. FFT) thus is quite slow, doesn't support weighted samples, doesn't support kernel shapes other than Gaussian, and doesn't implement more sophisticated algorithms for estimating the bandwidth. In its favour, it does support multivariate KDE.

Weighted samples were implemented here in a modified `gaussian_kde`: https://gist.github.com/tillahoffmann/f844bce2ec264c1c8cb5 by @tillahoffmann

Is anything happening on this? It could require some expertise on the stats side, as well as a bit of work coding. I know there are other implementations of KDE, but none that seems complete. I don't think there is a simple library that already implements KDE in a particularly complete way.

**Comment by jakevdp** [comment]
Other packages have different KDE implementations with various advantages. A few years ago I compared a bunch of them [here](https://jakevdp.github.io/blog/2013/12/01/kernel-density-estimation/)

**Comment by innisfree** [comment]
Cool. Statsmodels actually looks pretty complete. Maybe `gauss_kde` won't be further developed, then?

**Comment by josef-pkt** [comment]
statsmodels kde is not complete. We have a huge PR waiting for merge with a separate new implementation.

**Comment by innisfree** [comment]
Oh I see. By complete, I meant the functions/options in statsmodels kde looked comprehensive. There's probably little point discussing development of KDE in scipy by extending `gaussian_kde` if the same functionality is being implementing already in `statsmodels`?

**Comment by josef-pkt** [comment]
There are still improvments that could be done to gaussian_kde itself, maybe put it into cython if there is a good speedup, add robust covariance or standard errors for the bandwidth, and maybe some other things. 

However, for other approaches, I think scikit-learn and statsmodels are the better place. scikit-learn has nearest neighbor approaches and whatever Jake compared.
Statsmodels is trying for the "complete" support. Different kernels, different built-in bandwidth choices, various bounds handling methods, non-continuous variables, integration with kernel regression and so on. (One problem in statsmodels is the lack/bottleneck of reviewers for merging PRs.)

**Comment by josef-pkt** [comment]
One advantage of scipy's gaussian_kde is still that it works for higher dimensional cases, where fft and nearest neighbor approaches are either expensive or don't work so well. The current gaussian_kde is pretty dimension agnostic, AFAIU.

**Comment by innisfree** [comment]
I've implemented a fast Fourier transform version of `gaussian_kde` that supports weighted samples for one of my own codes:

https://github.com/michaelhb/superplot/blob/master/superplot/statslib/kde.py

I began from 

 https://gist.github.com/tillahoffmann/f844bce2ec264c1c8cb5

(which I didn't author)

It's probably not ready to be pulled into `scipy` now, and I made some relatively changes, including removing a few class attributes.  What's the best way to develop this into `scipy`?

**Comment by tillahoffmann** [comment]
You could fork the scipy repository and submit a pull request making sure that your implementation is fully backwards compatible. In particular,

* weights are optional
* all the functions such as `resample`, `integrate_box` etc are implemented
* make sure all tests pass when you run https://github.com/scipy/scipy/blob/master/scipy/stats/tests/test_kdeoth.py

**Comment by innisfree** [comment]
> all the functions such as resample, integrate_box etc are implemented

Hmm I see, that could be painful.

**Comment by rgommers** [comment]
Backwards compatibility is indeed required. With that requirement met, improvements are welcome of course. 

This is more a mailing list type discussion than an issue, so I'll close it. But feel free to continue discussing of course.

**Comment by innisfree** [comment]
OK, no worries. 

The subclass test `_kde_subclass1` (https://github.com/scipy/scipy/blob/master/scipy/stats/tests/test_kdeoth.py#L108) means you cannot add any other attributes in `__init__`, as they'll be missing in that subclass.  E.g. I obviously want to add a `self.weights` and a `self.fft` for my weight and fast Fourier transform options.

That seems a bit restrictive?!

**Comment by rgommers** [comment]
It is indeed a bit restrictive - that's the penalty of success for any widely used library:)

In this case, why would you need to set those attributes in ``__init__`` instead of in ``evaluate`` or a new method that's used by ``evaluate`` and/or ``integrate_*``?

**Comment by innisfree** [comment]
Honestly, I think it's a penalty of legacy support for poorly planned APIs.

> In this case, why would you need to set those attributes in `__init__` instead of in evaluate or a new method that's used by `evaluate` and/or `integrate_*`?

1. The other option, `bw_method`, and the data itself is declared in `__init__`. Why on earth would further options and the optional weights for the very same data be entered in evaluate?
2. The weights affect the computation of the covariance, which at present is calculated once `__init__`,  not once per call in `__run__`. The FFT also has overhead that should be calculated once only. 

The legacy support will severely hamper further development.

**Comment by rgommers** [comment]
> The other option, ``bw_method``, and the data itself is declared in ``__init__``. Why on earth would further options and the optional weights for the very same data be entered in evaluate?

Well, for backwards compat. And there are other options than in ``evaluate``, like making ``weights`` a property with a default of all 1's that is fully backwards compatible for all subclasses.

> The weights affect the computation of the covariance, which at present is calculated once ``__init__``, not once per call in ``__run__``. The FFT also has overhead that should be calculated once only. 

That's all fixable. Yes, it takes quite a bit more effort than writing code from scratch. But you'll find that that's the case for pretty much any change you'd like to contribute to Scipy or a similar such library.

The more important question here is whether the addition with FFTs makes sense for Scipy. Your code currently does only 1-D and 2-D; a 1-D fft KDE is already present in statsmodels. ``gaussian_kde`` mainly has advantages for higher dimensions and when needing the ``integrate_`` methods, both of which your code doesn't support right now. So maybe it would be better to check what your implementation does better than the statsmodels one, and improve ``statsmodels``?

**Comment by innisfree** [comment]
> And there are other options than in evaluate, like making weights a property with a default of all 1's that is fully backwards compatible for all subclasses.

That's not an option, that's why the subclass tests are ridiculously restrictive.  I could not add a 

        if weights is None:
            self. weights = equally weighted
        else:
            ...

to init and later use the reference self.weights in other mandatory attributes of the class. The subclasses completely override init. Yes, there are awful ways around this, but it's an obstacle to writing simple code.

My FFT code could probably easily be generalised to arbitrary dimensions (as long as the scipy signals fftconvolution works for higher dims). But FFT requires evenly spaced samples so histograms first, which gets inefficient in high dimensions. The weights should work in arbitrary dimensions.

I don't think the stats models KDE is actually in great shape, and don't see why we guassian_kde shouldn't support weights or FFT (even if there were other finished implementations, which there aren't). 

I guess the message is development of gaussian_kde is difficult because of legacy support and unwanted because of statsmodels

**Comment by rgommers** [comment]
That's not a property. I meant something like:

    diff --git a/scipy/stats/kde.py b/scipy/stats/kde.py
    index 35e7596..4e74c27 100644
    --- a/scipy/stats/kde.py
    +++ b/scipy/stats/kde.py
    @@ -162,13 +162,26 @@ class gaussian_kde(object):
         >>> plt.show()
     
         """
    -    def __init__(self, dataset, bw_method=None):
    +    def __init__(self, dataset, bw_method=None, weights=None):
             self.dataset = atleast_2d(dataset)
             if not self.dataset.size > 1:
                 raise ValueError("`dataset` input should have multiple elements.")
     
             self.d, self.n = self.dataset.shape
             self.set_bandwidth(bw_method=bw_method)
    +        if weights is not None:
    +            self._weights = weights / np.sum(weights)
    +
    +    @property
    +    def weights(self):
    +        """Get the weights per point.
    +
    +        Can be given by user during instantiation, otherwise weights are all 1.
    +        """
    +        try:
    +            return self._weights
    +        except AttributeError:
    +            return np.ones_like(self.dataset, dtype=float) / self.n

> I guess the message is development of gaussian_kde is difficult because of legacy support and unwanted because of statsmodels

It's not unwanted, but you have to understand that we want to add things that are an improvement to scipy without downsides. So:

- breaking existing user code is a no-go
- trade-offs like "we add weights, but only for ``evaluate`` and not for ``integrate_``" are also not great.
