### ISSUE TITLE
Typo in scipy.spatial.distance.cdist docs

### ISSUE THREAD

**Issue by innisfree** [scipy/scipy#6189]
http://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html
https://github.com/scipy/scipy/blob/v0.17.1/scipy/spatial/distance.py#L1778-L2294

The cdist doc string defines the Mahalanobis distance without a square root. See e.g.

https://en.m.wikipedia.org/wiki/Mahalanobis_distance

The function called by cdist is itself correct and correctly documented

https://github.com/scipy/scipy/blob/v0.17.1/scipy/spatial/distance.py#L541

**Comment by rgommers** [comment]
Thanks @innisfree. Looks like this was already noticed in gh-4815, but then lost in the discussion.

Would you like to send a PR to fix this?
