### ISSUE TITLE
lstsq() and others detect numpy.complex256 as real

### ISSUE THREAD

**Issue by misho88** [scipy/scipy#6194]
For example:
```
>>> A = np.array([[1,2,3],[4,5,6],[7,8,9]])
>>> b = [3,2,1]
>>> dt=np.complex256; la.lstsq(array(A, dtype=dt), array(b, dtype=dt), lapack_driver='gelsd')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-45-1282c50dbc51> in <module>()
----> 1 dt=np.complex256; la.lstsq(array(A, dtype=dt), array(b, dtype=dt), lapack_driver='gelsd')

/usr/lib/python3.5/site-packages/scipy/linalg/basic.py in lstsq(a, b, cond, overwrite_a, overwrite_b, check_finite, lapack_driver)
    867         elif driver == 'gelsd':
    868             if real_data:
--> 869                 lwork, iwork = _compute_lwork(lapack_lwork, m, n, nrhs, cond)
    870                 if iwork == 0:
    871                     # this is LAPACK bug 0038: dgelsd does not provide the

ValueError: too many values to unpack (expected 2)
```

Choosing a driver that skips this check works fine, casting the complex256 to a complex128 along the way as expected:

```
>>> dt=np.complex256; la.lstsq(array(A, dtype=dt), array(b, dtype=dt), lapack_driver='gelsy')

(array([-1.94444444+0.j, -0.11111111+0.j,  1.72222222+0.j]),
 array([], dtype=complex128),
 2,
 None)
```

Tracing through this got me to line 217 of scipy/linalg/blas.py, which should probably change from
`    if dtype.char not in 'fdFD':`
to
`    if dtype.char not in 'fdgFDG':`
unless that's going to break something else.

**Comment by ev-br** [comment]
Is complex256 really a thing? Given that float128 is not really a thing either (or is it). Just passing complex256 through as blas-compatible dtype does not sound right because blas routines only have two complex variants,  c- and z-.
@ewmoore could you weigh in here?

**Comment by pv** [comment]
It's long double, size depends on platform. The routines should downcast 
it to double, as AFAIK they usually do since BLAS has only float/double.
