### ISSUE TITLE
tox deps: install both numpy and scipy

### ISSUE THREAD

**Issue by dalitang** [scipy/scipy#6199]
Hi,

I got an issue when put both numpy&scipy to tox.ini for my test:

[tox]
envlist = py27
skipsdist = true

[testenv]
setenv =
    PYTHONPATH = .
commands = py.test -s -v ..........

deps = numpy
       scipy
       pytest
       matplotlib
       openpyxl

tox will always install scipy first which will go for numpy installation dependence. 

Is there any way to force numpy before scipy?

Thanks.

**Comment by rgommers** [comment]
This should work already with a recent scipy version. numpy is added to ``install_requires`` and ``setup_requires`` if it is not present already. Can you put the full log from tox in a gist and link to it?

**Comment by pv** [comment]
No reply, so closing.
