### ISSUE TITLE
Benchmarking global optimization on python2

### ISSUE THREAD

**Issue by sgubianpm** [scipy/scipy#6200]
When running the current SciPy benchmark implementation with python2 (SciPy 0.18.0 to be released), I do:
`export SCIPY_XSLOW=1 ; python runtests.py --bench optimize`
I get the following error:
`For parameters: 'AMGM', 'success%', 'DE'
Traceback (most recent call last):
File "/opt/python2-science/lib/python2.7/site-packages/asv/benchmark.py", line 685, in <module>
result = benchmark.do_run()
File "/opt/python2-science/lib/python2.7/site-packages/asv/benchmark.py", line 405, in do_run
return self.run(*self._current_params)
File "/opt/python2-science/lib/python2.7/site-packages/asv/benchmark.py", line 553, in run
return self.func(*param)
TypeError: track_all() takes exactly 5 arguments (4 given)`

I was wondering if I do something stupid or do you think there is an issue here?
With python3, I get the issue mentioned in #6197 by @andyfaff

**Comment by pv** [comment]
You may need asv version from git master (not 0.1.1 from pypi).

**Comment by sgubianpm** [comment]
@pv: Thanks a lot. I will try this.

**Comment by andyfaff** [comment]
This is fixed in asv/master. Please see #6388 for modifications to allow the benchmarking to worm on Python 3
