### ISSUE TITLE
Radial Basis Function memory usage?

### ISSUE THREAD

**Issue by adalast** [scipy/scipy#6201]
I am sure that this is probably not a bug, but I have been attempting to use the RBF functions of SciPy to interpolate a sparsely populated image file as a part of my research for my Master's degree.  I have gotten the method working as a prototype, but if I attempt to use it on an image larger than 200x200 px I very quickly run out of memory as it is processed.  I was hoping that there may be some memory optimization option that I have been unable to find, or if there is not, is there a way that I could add one?  Here is the file I am working with and an example of my input, and output, and a file that it crashes on.
[mapInterpolation.txt](https://github.com/scipy/scipy/files/294666/mapInterpolation.txt)
![occ200](https://cloud.githubusercontent.com/assets/452159/15731261/b4310910-2841-11e6-800d-3fa03ca23c1b.png)
![occ200interpolated radial](https://cloud.githubusercontent.com/assets/452159/15731260/b4310168-2841-11e6-96f4-6957e71cb1f6.png)
![occ500](https://cloud.githubusercontent.com/assets/452159/15731289/e3b2e29e-2841-11e6-95ad-7f504bb1db78.png)

**Comment by rgommers** [comment]
I don't see anything you're missing, but 200x200 points is not a lot. It would be helpful if you reduced your example to only what you really need to reproduce the memory error, and paste that code in this issue.

**Comment by pv** [comment]
N=200x200=40000 is a lot for RBF, which does global fitting and needs to 
solve a NxN linear system.

**Comment by ev-br** [comment]
One simple thing to check would be if it helps to lazily compute `self.A`  instead of storing it on an instance:
https://github.com/scipy/scipy/blob/master/scipy/interpolate/rbf.py#L221
