### ISSUE TITLE
Correlated stats.norm.rvs when passed 

### ISSUE THREAD

**Issue by ambevill** [scipy/scipy#6205]
I would expect that if I pass an array of N `loc` values into `rvs`, it would sample the values independently. Instead, `rvs` returns an N-array of the same random number, shifted and scaled according to the corresponding value in the `loc` array. For example:

```
from scipy import arange, zeros, __version__
from scipy.stats import norm

print(__version__)
print(norm.rvs(size=3))
print(norm.rvs(zeros(3)))
print(norm.rvs(arange(3)))

```
will output
```
0.17.1
[-0.44117927 -2.20215922  0.52281674]
[ 0.21769148  0.21769148  0.21769148]
[-0.02990758  0.97009242  1.97009242]
```
The first printed array is the behavior I expect: the numbers are uncorrelated. The other two arrays are clearly correlated. I don't observe a similar problem in scipy.stats.poisson.rvs:

```
from scipy import array
from scipy.stats import poisson

print(poisson.rvs(array((10, 10, 20, 20))))
```
will output
```


[10  6 28 26]
```

**Comment by WarrenWeckesser** [comment]
Thanks for reporting the problem.  This is a known bug: https://github.com/scipy/scipy/issues/2069
