### ISSUE TITLE
Is there a method to cap shortest path search distances?

### ISSUE THREAD

**Issue by shongololo** [scipy/scipy#6218]
I am using csgraph.shortest_path to return an all-pairs distance and predecessor array.

Is there a manner to cap the search distance?

If not, is this something that could be added?

**Comment by shongololo** [comment]
I see that the dijkstra shortest path method does have a limit input which will work for my purposes.

I would close this except that it seems that the limit flag is missing from the method heading.

**Comment by Eric89GXL** [comment]
Indeed it is missing, I'll open a PR momentarily to fix it
