### ISSUE TITLE
setup.py -j8 or NPY_NUM_BUILD_JOBS doesn't seem to parallelize builds

### ISSUE THREAD

**Issue by tdsmith** [scipy/scipy#6225]
Passing -j8 to `setup.py build` or `setup.py build_ext`, or setting NPY_NUM_BUILD_JOBS to "8", doesn't seem to parallelize the scipy build process for me; watching CPU usage in Activity Monitor through a complete build it looks like one core is being pegged but none of the others are being used. I'm on OS X:

```
CPU: 8-core 64-bit haswell
Clang: 7.3 build 703
OS X: 10.11.4-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
GCC (gfortran): 6.1.0
```

Numpy in the build environment is 1.11.0; the scipy version under build is 0.17.1.

Should I expect to see the build parallelize at some point?

**Comment by pv** [comment]
It iirc parallelizes only inside a single module unit, and scipy mostly
consists of single-file modules, so it's not expected to have a big effect.

**Comment by tdsmith** [comment]
Great; thanks!

**Comment by AlJohri** [comment]
@pv does the `NPY_NUM_BUILD_JOBS` option also work with scipy? or is only the `-j` option supported?
