### ISSUE TITLE
ENH: improve accuracy for rayleigh.logpdf and rayleigh.logsf for large x-values

### ISSUE THREAD

**Issue by pbrod** [scipy/scipy#6227]
The accuracy for large x-values for rayleigh.logpdf and rayleigh.logsf is poor:

    >>> import scipy.stats as ss
    >>> ss.rayleigh.logpdf(50)
    -inf
    >>> >>> ss.rayleigh.logsf(50)
    -inf

The values should have been -1246.0879769945718 and -1250.0, respectively.
Replacing the _logpdf and _logsf method with the following:

    def _logpdf(self, r):
        rr2 = r * r / 2.0
        return _lazywhere(rr2 != inf, (r, rr2), lambda r, rr2: log(r) - rr2, -rr2)

    def _logsf(self, r):
        return -0.5 * r**2

one gets the correct values:

    >>> ss.rayleigh.logpdf(50)
    -1246.0879769945718
    >>> >>> ss.rayleigh.logsf(50)
    -1250.0

**Comment by argriffing** [comment]
Partially addressed in https://github.com/scipy/scipy/pull/6237. The specific numerical example in this issue has been added to the unit tests, but more extreme cases like `logpdf(np.inf)` are not yet addressed.

**Comment by ev-br** [comment]
#6246 fixed the last remaining corner case, it seems.

```
In [5]: rayleigh.logpdf(float('inf'))
Out[5]: -inf

In [6]: rayleigh.logpdf(np.inf)
Out[6]: -inf
```
Closing.
