### ISSUE TITLE
ENH: improve accuracy of ppf cdf roundtrip for gumbel_l

### ISSUE THREAD

**Issue by pbrod** [scipy/scipy#6228]
The accuracy of the gumbel_l ppf and cdf functions is poor for large negative x as exemplified here:

    >>> import numpy as np
    >>> import scipy.stats as ss
    >>> x = np.linspace(-100, -4)
    >>> (ss.gumbel_l.ppf(ss.gumbel_l.cdf(x))-x)/x
    array([             inf,              inf,              inf,
                    inf,              inf,              inf,
                    inf,              inf,              inf,
                    inf,              inf,              inf,
                    inf,              inf,              inf,
                    inf,              inf,              inf,
                    inf,              inf,              inf,
                    inf,              inf,              inf,
                    inf,              inf,              inf,
                    inf,              inf,              inf,
                    inf,              inf,  -1.52608162e-02,
         1.00926224e-04,   5.04405205e-04,  -1.22679122e-06,
        -3.82136386e-06,  -3.94631612e-07,  -5.56583419e-08,
        -9.00121598e-09,   3.31592421e-09,   4.64076847e-10,
        -7.81227413e-11,  -1.62509384e-11,  -2.56347474e-12,
         2.74780964e-13,  -9.17172674e-14,  -1.17775205e-14,
         2.68278550e-15,   6.66133815e-16])

By replacing the _cdf and _ppf methods with

    def _cdf(self, x):
        return -expm1(-exp(x))

    def _ppf(self, q):
        return log(-log1p(-q))

one will obtain full machine accuracy as shown here:

    >>> (ss.gumbel_l.ppf(ss.gumbel_l.cdf(x))-x)/x
    array([-0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
             -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
             -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
             -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.])

One should also consider replacing the _logsf and _sf methods with

    def _logsf(self, x):
        return -exp(x)

    def _sf(self, x):
        return exp(-exp(x))

in order to improve the accuracy for those methods as well.

**Comment by rgommers** [comment]
Thanks @pbrod, nice set of related improvements in this and other recent issues!

**Comment by pbrod** [comment]
Thanks.
