### ISSUE TITLE
scipy.sparse.diags does not handle empty diagonal (IndexError: list index out of range)

### ISSUE THREAD

**Issue by roessland** [scipy/scipy#6232]
``` python
import scipy.sparse
scipy.sparse.diags([], 0)
```

Expected result: 0x0 sparse matrix

Actual result:

``` python
/home/shomea/a/andreros/anaconda3/envs/py27/lib/python2.7/site-packages/scipy/sparse/construct.pyc in diags(diagonals, offsets, shape, format, dtype)
    138         # now check that there's actually only one diagonal
    139         try:
--> 140             iter(diagonals[0])
    141         except TypeError:
    142             diagonals = [np.atleast_1d(diagonals)]

IndexError: list index out of range
```

I havent looked too much into the code, but changing line 141 to `except (TypeError, IndexError)` seems like a quick fix.

Python 2.7.11 |Anaconda 2.4.0 (64-bit)| (default, Dec  6 2015, 18:08:32)  
scipy.**version** '0.16.1'  
numpy.**version** '1.10.4'

**Comment by perimosocordiae** [comment]
I can confirm that this still happens on the master branch. I submitted a PR (linked above) with a fix.

**Comment by pv** [comment]
This was fixed.
