### ISSUE TITLE
hypergeom documentation may be very unintuitive.

### ISSUE THREAD

**Issue by zfrenchee** [scipy/scipy#6233]
In [hypergeom](https://github.com/scipy/scipy/blob/v0.14.0/scipy/stats/_discrete_distns.py#L251) the [documentation](http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.hypergeom.html) reads: 
``` 
  The probability mass function is defined as::
        pmf(k, M, n, N) = choose(n, k) * choose(M - n, N - k) / choose(M, N),
                                       for max(0, N - (M-n)) <= k <= min(n, N)
 ```

I'm quite certain that `choose(n, k)` means here "choose from n, k objects" as opposed to the more intuitive "choose n objects from k". I.e. 'choose(n, k) means [k choose n](http://www.wolframalpha.com/input/?i=k+choose+n) and not [n choose k](http://www.wolframalpha.com/input/?i=n+choose+k). 

First, is that correct? 

Second, if so, what on earth motivated that syntax in the documentation? I feel it is **painfully** unintuitive. Is it just the way I learned probability or does this need fixing?

**Comment by tpudlik** [comment]
I believe you are not correct.

The formula for the pmf given in `hypergeom` agrees with that on [Wikipedia](https://en.wikipedia.org/wiki/Hypergeometric_distribution) if you assume,

* That the notation `choose(n, k)` means "n choose k", or `n!/(k! (n-k)!)`, as usual.
* That the parameter `M` denotes the total population, `n` the number of successes in the population, and `N` the number of draws (as is implied by the dog example in the documentation).  That is, the mapping from the symbols used in the SciPy documentation to the ones used by Wikipedia is `M -> N, n -> K, N -> n`.  Note that both use the symbol `N`, but to denote different things!

That being said, I agree that the documentation should be clarified.  In particular, the shape parameters should probably be individually defined in the function signature, and the existence of other conventions should be noted.  I'll take a stab at it.

**Comment by zfrenchee** [comment]
@tpudlik Looks like you clarified the documentation so we can probably close this issue. Thanks!
