### ISSUE TITLE
BUG: alpha.pdf and alpha.logpdf returns nan for x=0

### ISSUE THREAD

**Issue by pbrod** [scipy/scipy#6235]
The alpha distribution  return nan for x=0 as exemplified here:

    >>> import numpy as np
    >>> import scipy.stats as ss
    >>> ss.alpha.pdf(0,2)
    nan
    >>> ss.alpha.logpdf(0,2)
    nan

The correct value is 0, because it is outside the support of the distribution (0 < x).
The fault lies apparently in line 1582 and 1624 in the pdf and logpdf method:

https://github.com/scipy/scipy/blob/v0.17.1/scipy/stats/_distn_infrastructure.py#L1582
https://github.com/scipy/scipy/blob/v0.17.1/scipy/stats/_distn_infrastructure.py#L1624

which incorrectly includes x==0 in the support of the distribution.

One solution is to delegate the support mask calculation to a function
and replace L1582 and L1624 in the pdf and logpdf method with:

       cond1 = (scale > 0) & self._support_mask(x)
   
The default support mask function in rv_continous should be:

    def _support_mask(self, x)
        return (self.a<=x) | (x<=self.b)

while the support mask function for the alpha distribution should be:

    def _support_mask(self, x)
        return self.a<x

This issue is connected to #6167

**Comment by pbrod** [comment]
The beta distribution has support in in the open set 0 < x < 1, but handles the cornercase x=0 and x=1 in the _logpdf method.

**Comment by pbrod** [comment]
Other distributions that have the same problem (return nan  for the pdf evaluated at x=0):
 * burr
 * invgamma
 * invgauss
 * invweibull
 * johnsonsb
 * levy
 * levy_l
 * powerlognorm
 * wald

Other distributions that have similar problem: returns a value even though the support of the distribution is given as 0<x:
 * gengamma.pdf(0, 1)

**Comment by pbrod** [comment]
It appers that gengamma is defined from 0<=x

**Comment by rgommers** [comment]
Fixed in gh-6246, closing.
