### ISSUE TITLE
Inconsistency / duplication for imread and imshow, imsave

### ISSUE THREAD

**Issue by MartinThoma** [scipy/scipy#6242]
## The issue
- [`imread`](http://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.imread.html#scipy-ndimage-imread) is in scipy.ndimage and [`scipy.misc.imread`](http://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imread.html)
- [`imshow`](http://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imshow.html) and [`imsave`](http://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imsave.html) are in scipy.misc

This seems inconsistent / unlogical from a users perspective.

## Proposed solution

Moving some to [`scipy.ndimage`](http://docs.scipy.org/doc/scipy/reference/ndimage.html#utility) and others to [`scipy.io`](https://docs.scipy.org/doc/scipy/reference/io.html):
- [ ] `scipy.misc.imshow` → `scipy.ndimage.imshow`
- [ ] `scipy.ndimage.imread`, `scipy.misc.imread` → `scipy.io.imread`
- [ ] `scipy.misc.imsave` → `scipy.io.imwrite`
- [x] `scipy.misc.imfilter` → `scipy.ndimage.imfilter`
- [x] `scipy.misc.imresize` → `scipy.ndimage.imresize`
- [x] `scipy.misc.imrotate` → `scipy.ndimage.imrotate`
- [ ] `scipy.misc.ascent` → `scipy.ndimage.ascent`
- [ ] `scipy.misc.face` → `scipy.ndimage.face`

I'm not sure about the remaining `bytescale`, `fromimage`, `toimage`.

## What needs to be done
- Moving the code from `pilutil.py` to `io.py` (and importing the functions from `io.py` in `pilutil.py`)
- Adding deprecation warnings to `pilutil.py`
- Adjusting tests
- Adjusting documentation

**Comment by rgommers** [comment]
I agree, all image related things in ``misc`` should be moved to ``ndimage``.

**Comment by MartinThoma** [comment]
I'm not quite sure how this should be done. The simplest way would be to just add it to ndimage like this: https://github.com/MartinThoma/scipy/commit/345a44710c8a733fd09b7151d6af257653376671

However, I guess `imshow` and `imsave` should be removed from `scipy.misc`, a deprecation warning should be added (like https://github.com/scipy/scipy/blob/master/scipy/stats/stats.py#L1720) and the tests / docs probably have to be adjusted. Right?

**Comment by rgommers** [comment]
Correct, a deprecation warning like that is needed. MartinThoma@345a447 works, but that way it's hard to add a deprecation warning that shows up in ``misc`` but not in ``ndimage``. It may be better to move the implementation over to ``ndimage``, and import it in ``misc`` like:

    from ndimage import imsave
    imsave = np.deprecate(imsave, message='misc.imsave is deprecated in Scipy 0.19.0')

**Comment by rgommers** [comment]
Thinking about ``imshow``, I'd rather get rid of that completely actually. That really doesn't belong in scipy, and the implementation is very odd (trying to save a png to disk before showing it??). 

For deprecations, those need to be discussed on the scipy-dev mailing list. Maybe you can make the proposal there to move ``imsave`` (and ``ascent``, ``face`` and other still useful ``im*`` functions?) to ``ndimage`` and deprecate the not useful stuff?

**Comment by WarrenWeckesser** [comment]
> Thinking about imshow, I'd rather get rid of that completely actually.

+1

The names and "home" of the im* functions was also discussed on the mail list; see the thread starting here: https://mail.scipy.org/pipermail/scipy-dev/2015-November/021032.html

I still think it makes more sense to move these to scipy.io (and possibly rename them while we're at it).

A move has also been suggested in https://github.com/scipy/scipy/issues/2442, and renaming was proposed in https://github.com/scipy/scipy/pull/5458

**Comment by MartinThoma** [comment]
Actually, I like `imshow`. It is the most convenient way I know to quickly figure out what is going on in an array. (However, imsave is not that much more inconvenient).


> For deprecations, those need to be discussed on the scipy-dev mailing list. Maybe you can make the proposal

I've just subscribed at the mailing list, but I didn't receive a mail so far.

**Comment by WarrenWeckesser** [comment]
Here's a more convenient link to the mailing list thread from November: http://thread.gmane.org/gmane.comp.python.scientific.devel/20063

**Comment by WarrenWeckesser** [comment]
> imread is in scipy.ndimage

`imread` is also in `scipy.misc`, and in fact, that's where the implementation is.  In https://github.com/scipy/scipy/commit/d00861911e012bfc70cace4f0d88f6bea01a307b, the duplicate code in `scipy.misc.imread` and `scipy.ndimage.imread` was eliminated by having the `ndimage` version call the `misc` version.

**Comment by WarrenWeckesser** [comment]
To be clear, when I said

> I still think it makes more sense to move these to scipy.io

I meant just `imread` and `imsave`.  The functionality of `imfilter` and `imresize` definitely belongs in `ndimage`, but these are just wrappers of Pillow functions, so they probably don't handle *n-dimensional* arrays like all the `ndimage` functions do.  I don't know if that inconsistency is enough to warrant simply deprecating them, and making similar functionality available in `ndimage` that *can* handle n-dimensional arrays.  Anyway, +1 for the continued clean up in `scipy.misc`.

**Comment by rgommers** [comment]
Outcome of gh-5458: if we move ``imsave`` there's a preference to rename it to ``imwrite``.

**Comment by MartinThoma** [comment]
Does somebody else want to do it? If not, I'll try it in the next week and make a WIP pull request (and there will certainly be something to be done as I'm quite uncertain what to do there)

(Is this probably something that should be added to https://github.com/scipy/scipy/milestone/32?)

**Comment by rgommers** [comment]
> (Is this probably something that should be added to https://github.com/scipy/scipy/milestone/32?)

I'll mark your PR for 1.0, would be good to get this done. Not a blocker though.

**Comment by MartinThoma** [comment]
@WarrenWeckesser I currently tend to do the following and I would like to hear your thoughts about this:

Moving some to [`scipy.ndimage`](http://docs.scipy.org/doc/scipy/reference/ndimage.html#utility) and others to [`scipy.io`](https://docs.scipy.org/doc/scipy/reference/io.html):
- `scipy.misc.imshow` → `scipy.ndimage.imshow`
- `scipy.ndimage.imread`, `scipy.misc.imread` → `scipy.io.imread`
- `scipy.misc.imsave` → `scipy.io.imwrite`
- `scipy.misc.imfilter` → `scipy.ndimage.imfilter`
- `scipy.misc.imresize` → `scipy.ndimage.imresize`
- `scipy.misc.imrotate` → `scipy.ndimage.imrotate`
- `scipy.misc.ascent` → `scipy.ndimage.ascent`
- `scipy.misc.face` → `scipy.ndimage.face`

I'm not sure about the remaining `bytescale`, `fromimage`, `toimage`.

Escpecially:

1. Should `scipy.misc.imshow` be moved or removed?
2. Should `scipy.misc.imfilter`, `scipy.misc.imresize`, `scipy.misc.imrotate` be moved ore removed?
3. Should something be done with `bytescale`, `fromimage`, `toimage`?

**Comment by rgommers** [comment]
We've decided against moving it all, deprecating it instead - see gh-7869. Closing this issue. Thanks all
