### ISSUE TITLE
Image for examples in scipy.ndimage

### ISSUE THREAD

**Issue by MartinThoma** [scipy/scipy#6243]
I miss graphical examples in the documentation of [`scipy.ndimage`](http://docs.scipy.org/doc/scipy/reference/ndimage.html).

Would it be ok to use

```python
>>> from skimage import data
>>> img = data.astronaut()
```

in the examples? Or could probably something similar be added to `scipy.ndimage`? In case image rights are a problem, I made a couple of [CC0 images](https://commons.wikimedia.org/wiki/Category:Quality_images_by_Martin_Thoma).

How could I make the images appear in the documentation?

**Comment by rgommers** [comment]
There are a couple of images in ``misc``, for example http://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.ascent.html. Better to use those than requiring ``skimage`` to be present just to build the docs.

The images will appear automatically if you create them and add ``plt.show()``. Example: http://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.remez.html#scipy.signal.remez

**Comment by rgommers** [comment]
Improvements to ``ndimage`` examples are very welcome by the way! Are you working on that?
