### ISSUE TITLE
Support for user defined distorsion/distance function in cluster.vq

### ISSUE THREAD

**Issue by stefraynaud** [scipy/scipy#6244]
It would make the k-means classification more generic if the user can provide its own distorsion function to replace current one, which corresponds to the the euclidian distance function.

**Comment by rgommers** [comment]
That distance is computed here: https://github.com/scipy/scipy/blob/master/scipy/cluster/_vq.pyx#L123. So hidden fairly low-level and performance critical. Not easy to replace with a user-defined function it looks like. Did you think of how to do this, and how large do you think the benefits are?

**Comment by rgommers** [comment]
The scikit-learn ``KMeans`` implementation also doesn't provide this I think. It's not an often-requested feature.

**Comment by stefraynaud** [comment]
You're right, there are too much low level code places in the pyx files where the euclidian distance is used, both in in spicy.cluster and sklearn.cluster.
The python codes of sklearn.cluster use the euclidian_distance at some levels, but here is not such feature with the pyx codes.
And I can't tell you how large would be the benefit since it is a very particular request of mine.

**Comment by rgommers** [comment]
Thanks @stefraynaud. I'm inclined to close this issue then. Do you mind?

**Comment by stefraynaud** [comment]
Yep, you can.
Thanks for your insight.
