### ISSUE TITLE
Unable to validate scipy.stats.beta.fit 

### ISSUE THREAD

**Issue by rajgupt** [scipy/scipy#6248]
I'm trying to check the MLE method used in Distribution fitting for beta distribution.
Sometimes, Likelihood value is coming less than that of original beta distribution used to generate the sample.

**Note: This check is coming fine in case of normal distribution**

``` python
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import beta
from pylab import plot,show,hist,figure,title


def likelihood(dist, sample):
    '''Calculate Likelihood Function'''
    return sum(dist.logpdf(sample))


a, b = 1, 2

sample = beta.rvs(a, b, size=100)
a1, b1, loc1, scale1 = beta.fit(sample)

# initial guess - method of moments
# ref: [source](https://github.com/scipy/scipy/blob/master/scipy/stats/_continuous_distns.py#L488)
xbar = sample.mean()
fac = xbar * (1 - xbar) / sample.var(ddof=0) - 1
a0 = xbar * fac
b0 = (1 - xbar) * fac

dist_original = beta(a, b)
dist_init = beta(a0, b0)
dist_fit = beta(a1, b1)

print "Likelihood Value of Sample as per original model" \
      " %f" % likelihood(dist_original, sample)

print "Likelihood Value of Sample as per initial model" \
      " %f" % likelihood(dist_init, sample)

print "Likelihood Value of Sample as per fitted model" \
      " %f" % likelihood(dist_fit, sample)

fig, ax = plt.subplots(1, 1)
hist(sample, normed=1, alpha=.3)
sample = np.sort(sample)
ax.plot(sample, beta.pdf(sample, a, b),
        'r-', lw=5, alpha=0.6, label='beta pdf')

ax.plot(sample, beta.pdf(sample, a0, b0),
        'b--', lw=5, alpha=0.6, label='beta pdf')

ax.plot(sample, beta.pdf(sample, a1, b1),
        'b-', lw=5, alpha=0.6, label='beta pdf')

plt.show()
```

**Output**
```
Likelihood Value of Sample as per original model 24.998001
Likelihood Value of Sample as per initial model 25.620731
Likelihood Value of Sample as per fitted model 21.563493
```
![image](https://cloud.githubusercontent.com/assets/6607313/15987471/2ae91a72-3047-11e6-9c19-8ca2a9735999.png)

Looking at the [source](https://github.com/scipy/scipy/blob/master/scipy/stats/_continuous_distns.py#L488), I found that initial guess uses method of moment. Please have a look and confirm if I'm checking it correctly or not.

**Comment by argriffing** [comment]
Here's a PR related to the beta MLE https://github.com/scipy/scipy/pull/2519

**Comment by WarrenWeckesser** [comment]
I haven't looked too closely at this, but I did note that you used the `fit` method like this:

    a1, b1, loc1, scale1 = beta.fit(sample)

You then created `dist_fit` with

    dist_fit = beta(a1, b1)

You haven't included `loc1` and `scale1`, so `dist_fit` will not be the distribution associated with the parameters returned by `beta.fit(sample)`.

**Comment by argriffing** [comment]
I think @WarrenWeckesser's comment solves the issue. With `np.random.seed(1234)` and using `beta(a1, b1, loc=loc1, scale=scale1)` I get
```
(log) Likelihood Value of Sample as per original model 23.226052
(log) Likelihood Value of Sample as per initial model 23.804802
(log) Likelihood Value of Sample as per fitted model with bug 21.949649
(log) Likelihood Value of Sample as per fitted model without the bug 28.922899
```

**Comment by argriffing** [comment]
This isn't a problem with scipy, so I'm going to close the issue.
