### ISSUE TITLE
Why isn't polyorder optional and calculated by the savgol_filter itself ?

### ISSUE THREAD

**Issue by rishabh135** [scipy/scipy#6256]
I am a relatively newbie to optimization tests , but one thing I could not understand that why do we need to give polyorder to the savgol_filter in scipy package , considering that it will be always less than the window size and can be optimally set by using the FTest , why is user forced to give it which in my humble opinion reduces the chances of finding the optimal smoothened curve ?

**Comment by nmayorov** [comment]
The option to set `polyorder` explicitly looks useful and I believe it is a conventional approach to this algorithm. What you are talking about could be a good enhancement. Will you try to implement it and send a pull request? It can be fit in as a special keyword `polyorder='auto'` (or something like that).

And perhaps you can give us more details about this optimal selection?

**Comment by WarrenWeckesser** [comment]
I agree with @nmayorov; this sounds like an interesting enhancement.  Links to references where this approach is discussed would be appreciated.

**Comment by WarrenWeckesser** [comment]
Both @nmayorov and I agree that this sounds interesting, but to be in scope for SciPy, there should preferably be published references that we can cite that defines the method.  I'm closing this issue, but that doesn't mean we can't someday revisit this topic.
