### ISSUE TITLE
bayes_mvs doctest stringency

### ISSUE THREAD

**Issue by argriffing** [scipy/scipy#6259]
The doctests added in https://github.com/scipy/scipy/pull/5065 are more strict than the corresponding unit tests.

I don't know the best way to fix this. One way could be to somehow mark the examples as non-executable. Another could be to print fewer digits in the doc examples. Another way could be to not do anything, or rather to keep changing the doctests each time an insignificant change is made to a related stats function.

**Comment by rgommers** [comment]
+1 for fewer digits. use ``...`` instead: https://docs.python.org/2.7/library/doctest.html#doctest.ELLIPSIS

**Comment by argriffing** [comment]
fixed in https://github.com/scipy/scipy/pull/6258
