### ISSUE TITLE
Fortran dqrsl subroutine

### ISSUE THREAD

**Issue by tgsmith61591** [scipy/scipy#6266]
I can see that the `dqrsl` Fortran odrpack subroutine is defined in [odr submodule](https://github.com/scipy/scipy/blob/master/scipy/odr/odrpack/d_lpkbls.f#L1160), however, I'm unable to call it:

```
>>> from scipy.linalg.lapack import get_lapack_funcs
>>> get_lapack_funcs(('qrsl',))
ValueError                                Traceback (most recent call last)
<ipython-input-15-20064bd61adb> in <module>()
----> 1 gl(('qrsl',))

//anaconda/lib/python2.7/site-packages/scipy/linalg/lapack.pyc in get_lapack_funcs(names, arrays, dtype)
    442     return _get_funcs(names, arrays, dtype,
    443                       "LAPACK", _flapack, _clapack,
--> 444                       "flapack", "clapack", _lapack_alias)
    445 
    446 

//anaconda/lib/python2.7/site-packages/scipy/linalg/blas.pyc in _get_funcs(names, arrays, dtype, lib_name, fmodule, cmodule, fmodule_name, cmodule_name, alias)
    255         if func is None:
    256             raise ValueError(
--> 257                 '%s function %s could not be found' % (lib_name, func_name))
    258         func.module_name, func.typecode = module_name, prefix
    259         func.dtype = dtype

ValueError: LAPACK function dqrsl could not be found
```

I'm trying to build a function that operates similar to R caret's `findLinearCombos`, which uses the `dqrsl` subroutine. I'm sure I'm just doing something stupid... any pointers?

**Comment by pv** [comment]
dqrsl is not a lapack routine, so `get_lapack_funcs` is not supposed to know about it.

**Comment by tgsmith61591** [comment]
Ok, well is it accessible at all?

**Comment by pv** [comment]
No --- I don't see why you expect it is accessible?

**Comment by tgsmith61591** [comment]
Numerous other Fortran subroutines are, hence my question.

**Comment by pv** [comment]
The more complete answer is that dqrsl is from an old obsolete linalg library.
The corresponding lapack routines iirc are dgeqrf/dgels.

**Comment by tgsmith61591** [comment]
Perfect. Thank you very much!
