### ISSUE TITLE
Broken lync on the documentation web site

### ISSUE THREAD

**Issue by mhooreman** [scipy/scipy#6268]
Hello,

I found that the Scipy Reference Guide PDF ([http://docs.scipy.org/doc/scipy/scipy-ref-0.16.1.pdf](http://docs.scipy.org/doc/scipy/scipy-ref-0.16.1.pdf)) on [http://docs.scipy.org/doc/](http://docs.scipy.org/doc/) is broken.

I have not found any good contact to tell it, so I guess that this project should do the trick. Pardon me if that's not the case

Best regards.

**Comment by argriffing** [comment]
I see that's true for all links to files in the 'latest releases' section.

**Comment by pv** [comment]
Fixed in https://github.com/scipy/docs.scipy.org/commit/84ff3f7b9a39af915c15a6b965a7272bfbb29f9d

**Comment by mhooreman** [comment]
Thanks
