### ISSUE TITLE
Scipy interp1d 'nearest' not working for high values on x-axis

### ISSUE THREAD

**Issue by karischoonbee** [scipy/scipy#6318]
# works:
```
hyp_f = interp1d(timestamps-timestamps[0], result, kind = 'nearest')
ts = np.arange(timestamps[0]-timestamps[0],timestamps[-1]-timestamps[0],1)
hyp = hyp_f(ts)
```
> hyp looks like result

# doesn't work:
```
hyp_f = interp1d(timestamps, result, kind = 'nearest')
ts = np.arange(timestamps[0],timestamps[-1],1)
hyp = hyp_f(ts)
```
> hyp is only zeros

scipy 0.17.0
[result.zip](https://github.com/scipy/scipy/files/334445/result.zip)

**Comment by ev-br** [comment]
Please show the values of the arrays `timestamps` and `result`.

**Comment by karischoonbee** [comment]
It's in the attached .csv file

**Comment by ev-br** [comment]
Taking `x` and `y` from the attached csv file,

```
In [72]: ii = interp1d(x, y, kind='nearest')

In [73]: xp = np.arange(x[0], x[-1], 500)

In [74]: ii(xp)
Out[74]: 
array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  2.,  2.,  2.,
        1.,  3.,  1.,  1.,  2.,  2.,  2.,  2.,  1.,  1.,  2.,  1.,  1.,
        3.,  3.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  1.,  1.,  1.,  1.,
        0.,  3.,  3.,  3.,  1.,  1.,  1.,  1.,  1.,  1.,  3.,  3.,  3.,  0.])

In [75]: (ii(np.arange(x[0], x[-1])) == 0).all()
Out[75]: False

In [76]: np.sum(ii(np.arange(x[0], x[-1])) !=0)
Out[76]: 21810
```

even though the array print formatting only shows zeros

```
In [76]: ii(np.arange(x[0], x[-1]))
Out[76]: array([ 0.,  0.,  0., ...,  0.,  0.,  0.])
```

Please verify that you actually have all zeros. If this is really the case, please reopen the ticket and add details on your environment, operating system and how you installed scipy.

**Comment by karischoonbee** [comment]
![1](https://cloud.githubusercontent.com/assets/2316021/16377242/2e008df6-3c65-11e6-8a3b-ebe66c980a19.PNG)
![2](https://cloud.githubusercontent.com/assets/2316021/16377243/30ffb4e6-3c65-11e6-899d-aa92f35425f5.PNG)

Windows 10. Anaconda2 4.0.0 x86_64

The same function has been running in production on OSX and Linux without problem.

**Comment by karischoonbee** [comment]
Not sure how to reopen the ticket without creating a new one?

Other interpolation methods than 'nearest' works.

**Comment by ev-br** [comment]
Aha, so it's something specific to Anaconda/Windows. Would you be able to debug it a bit? This code is pure python, https://github.com/scipy/scipy/blob/master/scipy/interpolate/interpolate.py#L558

I would locate the installation (`>>> import scipy; print scipy.__file__`) and then insert a breakpoint (`import pdb; pdb.set_trace()`) to the `_call_nearest` method above. Then step through it and check what's going wrong.
I cannot do it myself since on my Linux machine it does not fail.

**Comment by karischoonbee** [comment]
Okay, it only seems to happen when `timestamps` is of type int, not when it's a float... so if you read it directly from that file it will work. 

The issue is with `self.x_bds` at line 464 in interpolate.py which causes an overflow.

**Comment by ev-br** [comment]
Nice detective work!

Since this seems easy (if annoying) to work around on the user side, I'd suggest keeping code as is in the name of backwards compatibility --- who knows what will break if we change the dtype of the output.
Maybe it's worth a short note in the docstring. Would you be interested in a PR?

**Comment by karischoonbee** [comment]
I don't think you'd need to change the dtype of the output, maybe just explicitly convert the input x values to a float array before computing the interpolation function?

**Comment by ev-br** [comment]
Would it fix it to compute `self.x_bds` in floating-point or rearrange the computation, e.g.`(x+ y)/2 = x + (y-x) /2`

**Comment by karischoonbee** [comment]
x/2 + y/2 is a good option

**Comment by ev-br** [comment]
OK, my worries about output dtypes were unfounded, it seems to be always float. And here's what I think is a simpler test case for the same problem:

```
In [21]: x = np.array([0, 50, 127], dtype=np.int8)

In [22]: x
Out[22]: array([  0,  50, 127], dtype=int8)

In [23]: ii = interp1d(x, x, kind='nearest')

In [24]: ii(x)
Out[24]: array([ 127.,  127.,  127.])

In [26]: ii(x).dtype                          # float, even though the input is int8
Out[26]: dtype('float64')

In [27]: interp1d(x.astype(float), x.astype(float), kind='nearest')(x)
Out[27]: array([   0.,   50.,  127.])
```

Pull requests welcome.

**Comment by karischoonbee** [comment]
https://github.com/scipy/scipy/pull/6323/commits

Hope this is ok!

**Comment by ev-br** [comment]
Does not seem release critical, so I'm detaching the milestone.

**Comment by ev-br** [comment]
closed by gh-6351
