### ISSUE TITLE
scipy.test failed with the output"Arrays are not almost equal to 2 decimals"

### ISSUE THREAD

**Issue by yechaochen** [scipy/scipy#6329]
I try the scipy.test in vmware.I have installed anaconda and run apt-get to installed the following packages:gfortran,libopenblas-dev,liblapack-dev,libatlas-base-dev. 
I have finded the version of numpy is 0.16.0 and I run the command `python -c "import scipy;scipy.test()".` But there is  an error:"Arrays are not almost equal to 2 decimals" 
Arrays are not almost equal to 2 decimals

FAIL: test_weighting (test_stats.TestHistogram)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anaconda/lib/python2.7/site-packages/scipy/stats/tests/test_stats.py", line 892, in test_weighting
    decimal=2)
  File "/home/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 886, in assert_array_almost_equal
    precision=decimal)
  File "/home/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 708, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 2 decimals

(mismatch 40.0%)
 x: array([   4. ,    0. ,    4.5,   -0.9,    0. ,    0.3,  110.2,    0. ,
          0. ,   42. ])
 y: array([   4. ,    0. ,    4.5,   -0.9,    0.3,    0. ,    7. ,  103.2,
          0. ,   42. ])

----------------------------------------------------------------------
Ran 18458 tests in 259.062s

Can anyone tell me how to solve it!

**Comment by ev-br** [comment]
> version of numpy is 0.16.0 

Is this a typo. Did you mean numpy 1.6.0 or scipy 0.16. Either way, both are recommended to upgrade from.

Please upgrade scipy (master or 0.18.0rc1) and check if the problem persists.
