### ISSUE TITLE
Segmentation fault when importing scipy.stats

### ISSUE THREAD

**Issue by jbloom** [scipy/scipy#6344]
I am using an Anaconda distribution of Python:

     Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) 
     [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2

When I try to import `scipy.stats`, I get a segmentation fault. This happens with `scipy` versions 0.16.0, 0.17.0, and 0.17.1 (I have not tried additional versions).

**Comment by pv** [comment]
You should contact Anaconda support channels --- this does not appear to be an issue with Scipy upstream.
