### ISSUE TITLE
Barycentric transforms test failures on 32-bit linux

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#6348]
Original report: https://github.com/scipy/scipy/issues/6101.
gh-5605 disabled a part of the test, and gh-6347 disables more.

It would be nice to double-check where the root of the problem is: is it the test, or is it something in scipy wrappers, or is there an instability upstream in QHull. 
EDIT: The answer is likely https://github.com/scipy/scipy/issues/2997#issuecomment-26679262

**Comment by rgommers** [comment]
> The answer is likely #2997 (comment)

That sounds right, so close this issue again?

**Comment by ev-br** [comment]
I guess I was wondering  whether gh-6101 was additional to gh-5605. I.e. if gh-5605 fixed all failures you saw on 32 bit linux, and then there's gh-6101 which fails for Matthew but does not fail for you, maybe there's something more to it. But yeah, maybe it's just paranoia.
