### ISSUE TITLE
Incorrectly escaped PATH in scipy.filter

### ISSUE THREAD

**Issue by nippoo** [scipy/scipy#6353]
```
from scipy import signal

  File "c:\users\peter\miniconda3\envs\phy\lib\site-packages\scipy\__init__.py", line 98, in <module>
    from scipy.__config__ import show as show_config
  File "c:\users\peter\miniconda3\envs\phy\lib\site-packages\scipy\__config__.py", line 5
    lapack_opt_info={'library_dirs': ['C:\Users\Peter\Miniconda3\envs\phy\\Library\\lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['C:\Users\Peter\Miniconda3\envs\phy\\Library', 'C:\Users\Peter\Miniconda3\envs\phy\\Library\\include', 'C:\Users\Peter\Miniconda3\envs\phy\\Library\\lib'], 'libraries': ['mkl_lapack95_lp64', 'mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']}
                                     ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

The package works perfectly when installed in `C:\Miniconda\envs\` but as soon as it's in `C:\Users\foobar\` then it detects `\U` as the Unicode escape sequence and doesn't work.

This might be an issue with the conda packaging, so let me know if I should report it there...

**Comment by rgommers** [comment]
That looks like a scipy not a conda issue. Or maybe yet another thing Python 3 does not actually do better with string handling.

How exactly did you install Scipy? Is it from the ``defaults`` channel or from conda-forge?

**Comment by rgommers** [comment]
It's pretty weird that no one reported this previously. I double checked that ``numpy.distutils`` writes full paths to ``__config__.py``, and that just doesn't work on Python 3.x without double backslashes:

    >>> lapack_opt_info={'library_dirs': ['/usr/lib/atlas-base/atlas']}
    >>> lapack_opt_info={'library_dirs': ['C:\Users\does\this\work']}
      File "<stdin>", line 1
    SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in 
    position 2-3: truncated \UXXXXXXXX escape

Your path string is odd by the way, there's a mix of single and double ``\``s in ``'C:\Users\Peter\Miniconda3\envs\phy\\Library\\lib']``. So maybe there's some merging of a string for the conda env and the rest of the path going on, with the former having an issue misusing ``os.path`` functions or something.

**Comment by nippoo** [comment]
Just installed it from the regular defaults channel. `conda install scipy`. (Actually installed it from an `environments.yml` file using `conda env create -n phy` for all that matters). Yeah, the path is odd - I did notice...

**Comment by rgommers** [comment]
Can you show the whole contents of your ``numpy/__config__.py`` file? If only your MKL paths are a mix between ``\`` and ``\\``, then it may be this bit in ``mkl_info``: https://github.com/numpy/numpy/blob/master/numpy/distutils/system_info.py#L993. Uses ``os.sep.join`` instead of ``os.path.join``, and I suspect that that gives ``\`` separators on Windows (can't check).

**Comment by pv** [comment]
This looks like numpy.distutils issue, which is what writes that file. And it uses `"%r"` to escape strings, so it should work...

I've been using conda under c:\users for a while, and it works, so I guess this issue is no longer relevant.
