### ISSUE TITLE
wrapcauchy frozen pdf seems broken for non-zero location parameter

### ISSUE THREAD

**Issue by babaMar** [scipy/scipy#6356]
How does the shift of the location parameter is handled by wrapcauchy.pdf()? 

Here's an illustration that shows the pdf for 0, 0.2, pi/2, pi. Though the "tail" scales good, at the beginning of the interval it gives zeros up to the `loc` value. 

`In [17]: from scipy.stats import wrapcauchy
`
`In [18]: x = np.linspace(0., 2*np.pi, 100)
`
`In [43]: plt.plot(x, wrapcauchy.pdf(x, 0.7, loc=0.), lw=2)
`
`In [44]: plt.plot(x, wrapcauchy.pdf(x, 0.7, loc=0.2), lw=2)
`
`In [45]: plt.plot(x, wrapcauchy.pdf(x, 0.7, loc=3.14), lw=2)
`
`In [46]: plt.plot(x, wrapcauchy.pdf(x, 0.7, loc=3.14/2), lw=2)
`

![wrapc](https://cloud.githubusercontent.com/assets/20344561/16668686/502d9e48-4492-11e6-9c60-8966195d9217.png)

I've checked wrapcauchy.rvs() and it behaves bad as well.

![wrapcs](https://cloud.githubusercontent.com/assets/20344561/16668896/27c13e5a-4493-11e6-9027-980522720461.png)

**Comment by ev-br** [comment]
This is expected if suboptimal. The loc-scale transformation works as explained in the docs:
http://docs.scipy.org/doc/scipy-0.17.1/reference/generated/scipy.stats.wrapcauchy.html#scipy.stats.wrapcauchy

> The probability density above is defined in the “standardized” form. To shift and/or scale the distribution use the loc and scale parameters. Specifically, wrapcauchy.pdf(x, c, loc, scale) is identically equivalent to wrapcauchy.pdf(y, c) / scale with y = (x - loc) / scale.

Compare to e.g., a uniform distribution:

```
In [22]: from scipy.stats import uniform

In [23]: ax.plot(x1, uniform.pdf(x1, loc=0), lw=2)
Out[23]: [<matplotlib.lines.Line2D at 0x7ff8a4b2f0b8>]

In [24]: ax.plot(x1, uniform.pdf(x1, loc=0.5), lw=2)
Out[24]: [<matplotlib.lines.Line2D at 0x7ff8a49f7630>]

In [25]: ax.plot(x1, uniform.pdf(x1, loc=0.7), lw=2)
Out[25]: [<matplotlib.lines.Line2D at 0x7ff8a49f3b38>]

In [26]: ax.set_ylim([0, 1.1])
Out[26]: (0, 1.1)
```

**Comment by ev-br** [comment]
The bottom line is that scipy.stats distributions are defined on a real line. You likely expected a circlular distribution, but these are not (yet?) implemented in scipy. There is a feature request for those, see e.g.
https://github.com/scipy/scipy/issues/4598, https://github.com/scipy/scipy/issues/4548, and it's going to take someone to implement it (would you be interested?)

**Comment by babaMar** [comment]
I see. Yes I expected a circular distribution.
