### ISSUE TITLE
scipy 0.17.1 piecewise cubic hermite interpolation does not return roots

### ISSUE THREAD

**Issue by kaufmanno** [scipy/scipy#6357]
The root method fails and returns an error with the scipy PchipInterpolator piecewise cubic hermite interpolation.
see [this question on stackoverflow](http://stackoverflow.com/questions/38234448/roots-of-piecewise-cubic-hermite-interpolator-with-python/38235352#38235352)

**Comment by ev-br** [comment]
Thanks for reporting it. The fix seems to be reasonably easy: `self._bpoly` in the `roots` method should be just `self`. And it needs  a test --- the very reason the bug slipped through the `pchip` refactor is that it was not tested.

Would you be interested in sending a PR?

**Comment by kaufmanno** [comment]
Dear Evgeni,

First of all, thank you for your quick and useful reply to my question!

I am willing to help even if I am still learning to work in large collaborative environments and am not yet always sure of the right way to do it...

Should I first clone the entire scipy repository (0.17.1 ?), then make the changes to the roots method and finally make a pull request on github?

Cheers,

Olivier

P.S. I am currently working on this project on my spare time, and it could take me a few days before this is done...

________________________________

Thanks for reporting it. The fix seems to be reasonably easy: self._bpoly in the roots method should be just self. And it needs a test --- the very reason the bug slipped through the pchip refactor is that it was not tested.
Would you be interested in sending a PR?

**Comment by ev-br** [comment]
No worries, we're all volunteers here :-).

> Should I first clone the entire scipy repository (0.17.1 ?), then make the changes to the roots method and finally make a pull request on github?

Yes. No need to work off 0.17.1 though --- all pull requests start off the master branch. Some will get backported to maintenance branches, but there is little chance that anything will happen in 0.17.x.

For general description of the recommended workflow see e.g. http://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html
(it's for numpy; but for scipy it's very similar.)

And don't worry about DoingThingsTheRightWay --- we all started somewhere. If you get stuck, ping this issue or a new one, or scipy-dev mailing list.
