### ISSUE TITLE
imsave is transposing my data

### ISSUE THREAD

**Issue by gkiar** [scipy/scipy#6361]
Hi,

I'm attempting to save out `png` images with [`imsave`](https://github.com/scipy/scipy/blob/v0.17.1/scipy/misc/pilutil.py#L158-L200), but am noticing that my data seems to be getting transposed and I'm unsure why. Here is an example:

```{python}
>>> print mydata.shape
(182, 218)
>>> imsave(filename.png, mydat.astype('float32'))
```
Then, when I do the following in terminal, this is what I get:
```{linux}
$ identify filename.png
filename.png PNG 218x182 218x182+0+0 8-bit PseudoClass 256c 9.75KB 0.000u 0:00.000
```

Any ideas why this is happening? Thanks!

**Comment by WarrenWeckesser** [comment]
The shape of a 2-d numpy array is `(num_rows, num_cols)`, or, in other words, `(height, width)`.  Imagemagick reports image sizes as `width x height`.

**Comment by gkiar** [comment]
That makes sense - I should've looked closer at the documentation. Thank you!
