### ISSUE TITLE
scipy.optimize.minimize mutating x0 shape on final pass using BFGS method with gradient function

### ISSUE THREAD

**Issue by jyting** [scipy/scipy#6364]
Hi,

I noticed today that scipy.optimize.minimize is changing the shape of the x0 I initially passed in from (3,) to (3,3) in a later run, and I haven't been able to figure out why/is breaking my usage of it. I may be mistaken in that this is intended, but nothing on the docs explains what this output is. Note that running this without using the gradient (jacobian function) and using the objective function SQE_NLL as is works perfectly fine.

My usage of it is as follows:

    x0 = [1.0, 1.0, 1.0] # initial guess
    res = minimize(self.SQE_NLL, x0, method='bfgs', jac=self.SQE_der)
    
    # Args is an array to allow for scipy.optimize
    def SQE_NLL(self, args):
        [f_err, l_scale, n_err] = args
        print("sqe nll n_err {}".format(n_err))
        print(args)
        L = linalg.cholesky(self.K(self.X, self.X, f_err, l_scale, n_err))
        alpha = linalg.solve(L.T, (linalg.solve(L, self.y))) # save for use with derivative func
        return (
            0.5 * self.y.T.dot(alpha) + 
            np.matrix.trace(L) + # sum of diagonal
            L.shape[0]/2 * math.log(2*math.pi)
        )

    def SQE_der(self, args)
        [f_err, l_scale, n_err] = args
        #TODO use alpha calculated from SQE_NLL
        L = linalg.cholesky(self.K(self.X, self.X, f_err, l_scale, n_err))
        alpha = linalg.solve(L.T, (linalg.solve(L, self.y))) # save for use with derivative func
        aaT = alpha.dot(alpha.T)
        K_inv = alpha/self.y
        dK_dtheta = np.gradient(self.K(self.X, self.X, f_err, l_scale, n_err))[0]

And for the most part, it works fine, where the x0 argument retains its (3,) shape, but after several tens of iterations, the shape suddenly changes to (3,3), as such:
`
[[ 1.49507027  1.          1.        ]
[ 1.          1.49507027  1.        ]
[ 1.          1.          1.49507027]]
`

**Comment by pv** [comment]
Please provide a self-contained runnable example demonstrating the failure.

**Comment by jyting** [comment]
Hi pv,

You can find a self-contained runnable example in the following pastebin:
http://pastebin.com/ZRpXVuCj

Please see lines 29-31 - it currently works as expected without providing the Jacobian function, but not otherwise.

**Comment by jyting** [comment]
Hi pv,

You can find a self-contained runnable example in the following pastebin:
http://pastebin.com/ZRpXVuCj

On line 91, it prints the arguments being passed to the function (which in the given example should be an array of 3 elements, representing the hyperparameters of the squared exponential function) - but at some point, it becomes the 3x3 array.

If you comment out line 31 (using Jacobian function) and instead use line 30 (no Jacobian function, just using first differences), the issue does not surface.

Thanks.

**Comment by person142** [comment]
Hey @jyting, I see that in the code you linked your `SQR_der` function (i.e. the Jacobian):

```python
def SQE_der(self, args):
    ...
    return der.all()
```
returns a boolean, which doesn't seem like what it should be doing. If one gets rid of the `all()` then on the first iteration it returns an array of shape `(1, 1)`, which also isn't right. (`x0` is of shape `(3,)`.)

Closing because it seems like there are still some bugs to sort out on your end, but feel free to continue the discussion.
