### ISSUE TITLE
Periodic splines hidden in splrep

### ISSUE THREAD

**Issue by puiseux** [scipy/scipy#6366]
I spent a lot of time looking for periodic splines in scipy, my goal being to draw a **close** and **smooth** **parametric** **spline** in (x,y) plane that interpolate (or adjust) a given familly of points 
_P[i] = (X[i], Y[i]), 0<=i<N_. 
Such a 2d-spline should be a **couple** of spline functions 
_(sx(t), sy(t)), t in [0,1]_,  
satisfying (sx(0),sy(0)) = (sx(1),sy(1)) and (sx'(0),sy'(0))=(sx'(1),sy'(1)).
An easy way to do this is to build two 1d **periodic** splines  _sx(t)_ and _sy(t)_ using parameter `per=True` in  `splrep`.
Unfortunatly i could not find any object oriented class able to achieve this. 
I have the feeling that it could be easy to improve `UnivariateSpline` class so that it can do it, that's why I open this issue.
Actually I roughly wrote and use this class :
```
class PeriodicSpline(object):
    """Spline parametrique (sx(t),sy(t)) interpolant ou ajustant une famille de points (x[i], y[i]) 0<=i<=N.
    See also : splrep"""
    def __init__(self, x, y, k=3, s=0):
        if y[-1] != y[0] :
            raise ValueError(u'Pour une spline periodique, les premiere (%.3f)\
                      et derniere (%.3f) valeurs doivent être identiques'%(y[0],y[-1]))
        self.k = k
        self.s = s
        #Not sure i have to store x and y
        self.x = x 
        self.y = y
        try : 
            self.tx, self.cx, self.kx = splrep(x, y, s=s, k=k, per=True)#per=True for periodic spline
        except TypeError as msg:
            print>>sys.stderr, msg
    
    def __call__(self, x):
        return splev(x, (self.tx, self.cx, self.kx))
```
and finally a test of this class compared with `InterpolatedUnivariateSpline` and `Rbf` : 
```
def testPeriodicSpline():
    import matplotlib.pyplot as plt
    P = np.asarray([(0, 1.0), (0.3,0.7), (1.0, 0), (2.0, 0),
                    (5.0, 0.2), (7.0, 0.50)])
    x = P[:,0]
    y = P[:,1]
    try : 
        s = PeriodicSpline(x, y, k=3, s=0)
    except ValueError as msg :
        print msg
    P = np.asarray([(0, 1.0), (0.3,0.7), (1.0, 0), (2.0, 0),
                    (5.0, 0.2), (7.0, 1.0)])
    x = P[:,0]
    y = P[:,1]
    dx = (x[-1]-x[0])/200.0
    s = InterpolatedUnivariateSpline(x,y)
    xi = np.arange(x[0], x[-1]+dx, dx)
    yi = s(xi)

    plt.subplot(3, 1, 1)
    plt.plot(x, y, 'bo', xi, yi, 'g')
    plt.title('InterpolatedUnivariateSpline')
    sx = Rbf(x, y, function='cubic')
    yi = sx(xi)

    plt.subplot(3, 1, 2)
    plt.plot(x, y, 'bo', xi, yi, 'g')
    plt.title('Rbf')
    
    sx = PeriodicSpline(x, y, k=3, s=0)
    yi = sx(xi)
    plt.subplot(3,1,3)
    plt.plot(x, y, 'bo', xi, yi, 'g')
    plt.title("PeriodicSpline")
    plt.show()


```

**Comment by haphaeu** [comment]
Didn't quite follow what your concern is. In the introduction you mention **closed** parametric splines. In such case, the values in x might not be unique, which means you'll have to interpolate x and y separately, as you've mentioned, sx(t), sy(t), 0<t<1. But your example code doesn't represent that?

Something like below would satisfy the conditions you want.

```
import numpy as np
import matplotlib.pyplot as plt
import scipy.interpolate as itp

P = np.asarray([(0, 0), (0.3, 0.7), (1.0, 0), (2.0, 0), (5.0, 0.2), (7.0, 0.5)])
x = P[:, 0]
y = P[:, 1]
# Repeat first point for a closed curve
x = np.append(x, x[-1])
y = np.append(y, y[-1])

# Fits a parametric spline for both x and y
t = np.linspace(0, 1, len(x))
tckx = splx = itp.splrep(t, x, per=True)
tcky = sply = itp.splrep(t, y, per=True)

# Plot points for spline
plt.plot(x, y, 'ro', ms=5)
ts = np.linspace(0, 1, 1000)
plt.plot(itp.splev(ts, tckx), itp.splev(ts, tcky), 'g', lw=3, alpha=0.7)
plt.show()
```

**Comment by puiseux** [comment]
Yes, you are right, my code doesn't reach my primary goal.
To be complete, I have to built 2 periodic splines, `sx=PeriodicSpline(t,x)` and `sy=PeriodicSpline(t,y)`,  parameter `t` can be normalized curviline absciss. And the result is a **parametric, smooth and  closed curve**  P(t) =(sx(t), sy(t)), exactly as you suggest.

What I meant here is : I had great difficulty in finding periodic splines in scipy. (probably i am not a good reader of documentation ;) )

I was looking for something like `class PeriodicSpline()`, with oriented object interface.

I only want to suggest that it could be a useful improvement if a (robust) class like my poor `PeriodicSpline` was visible in scipy, like `UnivariateSpline`, or `InterpolatedUnivariateSpline`.

**Comment by haphaeu** [comment]
I see, it is clear now. Agree that such object would be convenient to have.

**Comment by ev-br** [comment]
You can use `splprep` for parametric splines. 
It also accepts the `per` keyword for closed curves. See, e.g., this SO question. http://stackoverflow.com/questions/33962717/interpolating-a-closed-curve-using-scipy

Alternatively, you can use the new `CubicSpline` object (which uses a different algorithm), and also it has a built-in support for periodic splines.
http://scipy.github.io/devdocs/generated/scipy.interpolate.CubicSpline.html#scipy.interpolate.CubicSpline
To use this until scipy 0.18.0 is released, you can either grab the current master, or install a release the release candidate (`pip install --pre` or equivalent.)

**Comment by puiseux** [comment]
Great ! 
Exactly what i was looking for. 
The exact command is
```
$ pip install --pre --upgrade scipy
... Successfully uninstalled scipy-0.17.1
Successfully installed scipy-0.18.0rc2
```

**Comment by ev-br** [comment]
Glad that it worked for you. 
It seems to me there is no actionable item here. I'll close the issue then, feel free to keep discussing if needed (however SO or scipy-user mailing lists might give you more visibility.)
