### ISSUE TITLE
scipy.optimize.minimize Erroneous appearance of "ValueError: The truth value of an array with more than one element is ambiguous"

### ISSUE THREAD

**Issue by jyting** [scipy/scipy#6367]
From the same code block as my [issue 6364](https://github.com/scipy/scipy/issues/6364), an error appears complaining about arrays with more than value being ambiguous. However, as you can see, both the SQE_der and SQE_NLL functions only return a single value. Note that running this without using the gradient (jacobian function) and using the objective function SQE_NLL as is works perfectly fine.

The error trace is as follows:
    Traceback (most recent call last):
    File "loaddata.py", line 87, in <module>
        gp.fit(X, y)
    File "/home/justinting/programming/bhm/ML/gp.py", line 29, in fit
        res = minimize(self.SQE_NLL, x0, method='bfgs', jac=self.SQE_der)
    File "/usr/lib/python3.5/site-packages/scipy/optimize/_minimize.py", line 441, in minimize
        return _minimize_bfgs(fun, x0, args, jac, callback, **options)
    File "/usr/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 865, in _minimize_bfgs
        old_fval, old_old_fval)
    File "/usr/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 706, in
_line_search_wolfe12
        old_fval, old_old_fval)
    File "/usr/lib/python3.5/site-packages/scipy/optimize/linesearch.py", line 282, in
line_search_wolfe2
        phi, derphi, old_fval, old_old_fval, derphi0, c1, c2, amax)
    File "/usr/lib/python3.5/site-packages/scipy/optimize/linesearch.py", line 379, in
scalar_search_wolfe2
        if (phi_a1 > phi0 + c1 * alpha1 * derphi0) or \
  ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

    x0 = [1.0, 1.0, 1.0] # initial guess
    res = minimize(self.SQE_NLL, x0, method='bfgs', jac=self.SQE_der)

    def SQE_der(self, args):
        if len(args.shape) != 1:
            args = args[2]

        [f_err, l_scale, n_err] = args
        L = linalg.cholesky(self.K(self.X, self.X, f_err, l_scale, n_err))
        alpha = linalg.solve(L.T, (linalg.solve(L, self.y))) # save for use with derivative func
        aaT = alpha.dot(alpha.T)
        K_inv = alpha/self.y
        dK_dtheta = np.gradient(self.K(self.X, self.X, f_err, l_scale, n_err))[0]
        der = 0.5 * np.matrix.trace((aaT - K_inv).dot(dK_dtheta))
        print('got here der {}'.format(der))
        return der.any()

    def SQE_NLL(self, args):
        # TODO fix - get around buggy scipy
        if len(args.shape) != 1:
            args = args[2]

        [f_err, l_scale, n_err] = args
        L = linalg.cholesky(self.K(self.X, self.X, f_err, l_scale, n_err))
        alpha = linalg.solve(L.T, (linalg.solve(L, self.y))) # save for use with derivative func
        nll = (
            0.5 * self.y.T.dot(alpha) + 
            np.matrix.trace(L) + # sum of diagonal
            L.shape[0]/2 * math.log(2*math.pi)
                )
        return nll.any()

**Comment by pv** [comment]
Please reduce the failure to standalone code that can just be run.
.
The most likely explanation for the failure currently is an error in 
your own code, so please double check it.

**Comment by jyting** [comment]
Hi pv,

At this stage, I've debugged the two functions being used in minimize, and both only ever return floats by themselves - though I definitely can't rule out that I've missed something else.

You can find a self-contained runnable example in the following pastebin:
http://pastebin.com/ZRpXVuCj

Please see lines 29-31 - it currently works as expected without providing the Jacobian function, but not otherwise.

**Comment by pv** [comment]
The issue seems to be that `SQE_der` returns a 1x1 matrix, but it's expected to return the len=3 vector containing the gradient.

**Comment by jyting** [comment]
@pv Thanks for pointing that out - I have since discovered as such and came back to close this issue.
