### ISSUE TITLE
Additional morphological operations

### ISSUE THREAD

**Issue by OmriTreidel** [scipy/scipy#6371]
Some morphological operations such as `pruning`, `thinning` etc are usful for regularizing edges after edge detection that would be great to have as part of morphology.

**Comment by ev-br** [comment]
A line needs to be drawn somewhere between `ndimage` and scikit-image, http://scikit-image.org/docs/dev/api/skimage.morphology.html

**Comment by jakirkham** [comment]
I think those are restricted to 2-D (in some cases 3-D) though; whereas, the one's in SciPy are truly N-D. Not saying that should be the division, but that is the way things are now.

**Comment by rgommers** [comment]
@jni will scikit-image stay restricted to 2-D/3-D for morphology operations? do you have an opinion on where this should go?

**Comment by jni** [comment]
I think @jakirkham's assertion is incorrect: most of our basic morphological operators are actually thin wrappers around ndimage (dilation, erosion, etc), so they are automatically nD. Other morphological operations that we've implemented, such as watershed, are nD. Our *rank* filters are 2D only, but the goal is to go fully nD wherever possible.

We'd certainly welcome additional morphological operators in scikit-image.

**Comment by rgommers** [comment]
> We'd certainly welcome additional morphological operators in scikit-image.

Thanks @jni. Then I'd say that's the preferred option. `ndimage` code isn't exactly easy to add to or maintain, and in scikit-learn new additions will not only be easier but likely better maintained. 

So let's close this.

**Comment by jakirkham** [comment]
> I think @jakirkham's assertion is incorrect

Sorry, I think that rather old comment is based on my understanding of an older state of scikit-image. Am not surprised to hear things have improved in the intervening time 🙂
