### ISSUE TITLE
Code bug in documentation for Structured Arrays (with fix)

### ISSUE THREAD

**Issue by ianozsvald** [scipy/scipy#6372]
The demo code at https://docs.scipy.org/doc/numpy-1.10.1/user/basics.rec.html in the 3rd code block is incorrect.

The fix is to replace `y=x['foo']` to `y=x['bar']`. As it stands the remainder of the 3rd & 4th code blocks are incorrect. 

I've glanced over the rest of the page and the other code blocks look fine (this wasn't a thorough test, just an eyeball).

I'm using:
* Anaconda (on a 64bit Intel laptop)
* Python 3.5
* numpy 1.10.4 

```
# The start of the documentation is fine
>>> x = np.array([(1,2.,'Hello'), (2,3.,"World")],
   dtype=[('foo', 'i4'),('bar', 'f4'), ('baz', 'S10')])
>>> x
array([(1, 2.0, b'Hello'), (2, 3.0, b'World')], 
      dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

# My code diverges from the demo
>>> y = x['foo']
>>> y
array([1, 2], dtype=int32) # doc states `array([ 2.,  3.], dtype=float32)` which must be wrong
```

**Comment by ianozsvald** [comment]
IGNORE - this is fixed in the 1.11 docs, sorry to have caught that only after filing the bug!

**Comment by rgommers** [comment]
No worries, thanks for reporting.

**Comment by rgommers** [comment]
Wrong repo by the way - those are numpy docs so https://github.com/numpy/numpy/issues would have been the place to go to.

**Comment by ianozsvald** [comment]
@rgommers doh! I know where to go next time, cheers!
