### ISSUE TITLE
Documentation of scipy.signal.cascade may need work.

### ISSUE THREAD

**Issue by madphysicist** [scipy/scipy#6373]
The docs at http://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.cascade.html#scipy.signal.cascade appear to have some inconsistencies. There is a vector `gk` mentioned in the `x` and `psi` docs that does not appear anywhere else. Also, the docs for `psi` mention that `phi(x) = ...`, not `psi(x) = ...`.

I do not know enough about wavelets to know how to fix.

**Comment by ev-br** [comment]
`cascade` is deprecated, along with the rest of the wavelet functionality.
