### ISSUE TITLE
expm_multiply, complex matrices not working using start,stop,ect...

### ISSUE THREAD

**Issue by weinbe58** [scipy/scipy#6377]
Hi,

There is a bug with expm_multiply. If I just use a complex matrix and vector the function returns the correct vector but when I use the linear grid feature it seems to be casting the vector to a float while iterating through the grid points:

site-packages/scipy/sparse/linalg/_expm_multiply.py:568: ComplexWarning: Casting complex values to real discards the imaginary part
X[0] = _expm_multiply_simple_core(A, B, t_0, mu, m_star, s)
site-packages/scipy/sparse/linalg/_expm_multiply.py:654: ComplexWarning: Casting complex values to real discards the imaginary part
K[p] = h * A.dot(K[p-1]) / float(p)
site-packages/scipy/sparse/linalg/_expm_multiply.py:663: ComplexWarning: Casting complex values to real discards the imaginary part
X[k + id] = np.exp(kh*mu) * F

I'm using scipy 0.17.1.

**Comment by WarrenWeckesser** [comment]
Do you have an example that we can run to reproduce the problem?

**Comment by WarrenWeckesser** [comment]
OK, I can reproduce this:

Here's an `A` and `B`.  `B` is complex:
```
In [19]: A
Out[19]: 
matrix([[ 1. ,  0. ],
        [ 0.5,  2. ]])

In [20]: B
Out[20]: 
matrix([[ 1.+0.j,  1.+1.j],
        [ 0.+0.j,  0.+1.j]])
```

`expm_multiply(A, B)` works:

```
In [21]: expm_multiply(A, B)
Out[21]: 
matrix([[ 2.71828183+0.j        ,  2.71828183+2.71828183j],
        [ 2.33538714+0.j        ,  2.33538714+9.72444323j]])
```

But using `start`, `stop` and `num` causes a problem with the complex values:

```
In [22]: expm_multiply(A, B, start=0, stop=1, num=2)
/Users/warren/miniconda3scipy/lib/python3.5/site-packages/scipy-0.19.0.dev0+12bff57-py3.5-macosx-10.6-x86_64.egg/scipy/sparse/linalg/_expm_multiply.py:568: ComplexWarning: Casting complex values to real discards the imaginary part
  X[0] = _expm_multiply_simple_core(A, B, t_0, mu, m_star, s)
Out[22]: 
array([[[ 1.        ,  1.        ],
        [ 0.        ,  0.        ]],

       [[ 2.71828183,  2.71828183],
        [ 2.33538714,  2.33538714]]])

In [23]: import scipy

In [24]: scipy.__version__
Out[24]: '0.19.0.dev0+12bff57'
```

**Comment by nonhermitian** [comment]
I believe that changing the dtype in lines #556 and #609 to `dtype=A.dtype` fixes the issue.
