### ISSUE TITLE
Adding a multistart algorithm to global optimizers in scipy.optimize

### ISSUE THREAD

**Issue by fabianrost84** [scipy/scipy#6381]
I regularly come across the following task: To find a the global minimum of a function I run local optimizers from multiple random initial guesses. For some situations, e.g. fitting parameters in systems biology, it was found that this type of algorithm performs better than others ([Raue et al., 2013](http://dx.doi.org/10.1371/journal.pone.0074335)). I wonder if there is any interest to include such an algorithm into `scipy`. I wrote some code, documentation and 2 examples here:
http://nbviewer.jupyter.org/github/fabianrost84/multistart-minimize/blob/master/multistart-minimize.ipynb

**Comment by andyfaff** [comment]
This is possibly something that would've been better to raise on the mailing list first. There are several approaches to the type of problem you described. Firstly (and probably best), you can use one of the global optimizers, `optimize.basinhopping` or `optimize.differential_evolution`, they are designed for this very task. They will be a lot more effective than brute search followed by local minimisation as the dimensionality of the problem increases. 
Remember that you can do brute search and polish using the `optimize.brute`, although the grid search is done over a regular grid. 
Finally, and this is not well known, you can do a brute search and polish (of the best solution) with `differential_evolution`. Here the brute search would examine the problem space by [latin hypercube](https://en.wikipedia.org/wiki/Latin_hypercube_sampling) sampling. You would probably want to increase the `popsize` by a bit. By setting `maxiter` to 0 no evolution is done on the population, and the best solution from the hypercube sampling would be polished with L-BFGS-B.

I do appreciate that isn't the same as performing a local minimisation of all the brute search locations, but I don't think that is going to outperform `differential_evolution` or `basinhopping` in the first place. `basinhopping` does do a local minimisation step as part of it's operation anyway.

**Comment by fabianrost84** [comment]
Thanks for the feedback @andyfaff . I'll adress your points, but I'll raise it on the mailing listas you suggest. Therefore, I close the issue here until it is discussed there.

**Comment by endolith** [comment]
Agreed that this should be added.  None of the alternatives mentioned sound like adequate substitutes, and this can also be parallelized easily.  Here's a simple implementation based on https://github.com/scipy/scipy/pull/7819

``` python
def multistart(func, ranges, niter=100, minimizer_kwargs=None, disp=False,
               niter_success=None, seed=None):
    ranges = np.asarray(ranges)

    # set up the np.random.RandomState generator
    rng = check_random_state(seed)

    if minimizer_kwargs is None:
        minimizer_kwargs = dict()

    if niter_success is None:
        niter_success = niter + 2

    # Generate starting points uniformly within ranges
    samples = rng.rand(niter, len(ranges))
    samples = samples * (ranges[:, 1] - ranges[:, 0]) + ranges[:, 0]

    best_fun = float('inf')
    # TODO: Should initialize best_res with a dummy
    # in case none of the results are Valid

    for n, x0 in enumerate(samples):
        res = scipy.optimize.minimize(func, x0, **minimizer_kwargs)
        if res.success is not InvalidResult and res.fun < best_fun:
            best_fun = res.fun
            best_res = res
            best_n = n
        if disp:
            print(n, x0, res.fun, best_fun)
        if n - best_n >= niter_success:
            if disp:
                print('No better minima found after', n - best_n,
                      'steps. Halting.')
            break
    if disp:
        print('Best minimum found on trial', best_n)

    return best_res
```

I've parallelized this with `multiprocessing` before, too, but that would need more work to make it user-friendly

That paper says latin hypercube multistart works better than random sampling, so that would be a good option to add as well.

**Comment by theo20** [comment]
@endolith Can you please tell me how Latin Hypercube can be combined with multi-start?

**Comment by endolith** [comment]
@theo20 Multistart just means that you start an optimizer multiple times at different starting points. These starting points can either be randomly selected or they can be generated from a latin hypercube, which is guaranteed to be more uniform than random sampling (or you can do latin hypercube and then shift them randomly within their local neighborhood, etc.)  

I think one paper I was looking at recommended a 3-stage optimizer:

1. Multistart
2. Basin-hopping
3. Local optimizer like BFGS

So perhaps we could have a `multistart`, and then `basinhopping` could be plugged into it as the local minimizer, etc.

**Comment by chernals** [comment]
@endolith Do you remember that reference? Could you share, this looks quite interesting for what I am doing.

**Comment by endolith** [comment]
@chernals No, and I can't find it.  Maybe I misunderstood something.

**Comment by theo20** [comment]
@endolith Many thanks for your reply. I see an example of basinhopping that uses the gradient of a function. Do you know if I can use basinhopping without using the gradient? I have a black-box function. Thanks.

**Comment by endolith** [comment]
@theo20 The default local minimizer doesn't require a gradient.  http://scipy.github.io/devdocs/generated/scipy.optimize.basinhopping.html
