### ISSUE TITLE
minimize with COBYLA constraints not respected

### ISSUE THREAD

**Issue by remitod** [scipy/scipy#6383]
When I log the values passed to the objective function in the minimize method, I see that they do not respect my constraints... 

I want them to be greater than 0 and the sum < 1, so I wrote these constraints:

```
constraints = ({'type': 'ineq', 'fun': lambda x: 1 - (x[0] + x[1])},
                {'type': 'ineq', 'fun': lambda x: x[0]},
                {'type': 'ineq', 'fun': lambda x: x[1]})
```

Did I do something wrong or is there a bug?

Here is my question on StackOverflow with full example: http://stackoverflow.com/questions/38356781/numpy-minimize-cobyla-constraints

Thank you!

**Comment by pv** [comment]
You must always check that `output.success` is True.
If the solver does not converge, it is not guaranteed the constraints are satisfied.

**Comment by remitod** [comment]
I checked and It does converge apparently, since output.success == True for every iteration...

**Comment by pv** [comment]
For the code you gave in the stackoverflow piece, it gives `output.success == False`.
If it's true for you, you are probably using an older version of scipy.

**Comment by remitod** [comment]
I am indeed working with an older version of Scipy, didn't know there could be such as difference... Thank you for your help!
