### ISSUE TITLE
BUG: Discrepancy in ellipord or ellip

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#6384]
As mentioned in https://github.com/scipy/scipy/pull/6328#issuecomment-231899630 there's some numerical error or something in `ellipord` or `ellip` (or maybe `sosfreqz`?)

These operations should produce a filter that is strictly below -150 dB at frequencies below 0.25, but it only reaches -147:

```
N, Wn = ellipord(0.3, 0.25, .5, 150)
sos = ellip(N, .5, 150, Wn, 'high', output='sos')
w, h = sosfreqz(sos)
dB = 20*np.log10(np.abs(h))
w /= np.pi
plot(w, dB)
```

![shouldn't go over -150 db](https://cloud.githubusercontent.com/assets/58611/16750592/de17c59c-47a0-11e6-8ad6-b2eb7020f9ed.png)

**Comment by rgommers** [comment]
On 32-bit Linux, Python 2.7 and current master I get:

    In [1]: from scipy.signal import *

    In [2]: N, Wn = ellipord(0.3, 0.25, .5, 150)

    In [3]: sos = ellip(N, .5, 150, Wn, 'high', output='sos')
    /home/rgommers/Code/scipy/scipy/signal/filter_design.pyc in ellipap(N, rp, rs)
       3299     ck1p = numpy.sqrt(1 - ck1 * ck1)
       3300     if ck1p == 1:
    -> 3301         raise ValueError("Cannot design a filter with given rp and rs"
       3302                          " specifications.")
       3303 

    ValueError: Cannot design a filter with given rp and rs specifications.

will send a PR to mark that test as knownfail, and replace it with values that don't error.
