### ISSUE TITLE
Nelder-mead documentation incorrect

### ISSUE THREAD

**Issue by isaacgerg** [scipy/scipy#6385]
http://docs.scipy.org/doc/scipy/reference/optimize.minimize-neldermead.html#optimize-minimize-neldermead

Lists xtol as the parameter which it should be xatol.

**Comment by pv** [comment]
This has been fixed some time ago.
https://scipy.github.io/devdocs/optimize.minimize-neldermead.html#optimize-minimize-neldermead

**Comment by isaacgerg** [comment]
thanks.  i just looked at the most recent docs and saw the issue.  I didnt
know the devdocs are online.
