### ISSUE TITLE
Memory error with scipy 

### ISSUE THREAD

**Issue by winash12** [scipy/scipy#6392]
I get a memory error with scipy interpolate

Traceback (most recent call last):
 File "contour.py", line 34, in <module>
 rbf = scipy.interpolate.Rbf(x, y, data, function='linear')
 File "/usr/local/lib/python3.4/dist-packages/scipy/interpolate/rbf.py", line 200, in __init__
 r = self._call_norm(self.xi, self.xi)
 File "/usr/local/lib/python3.4/dist-packages/scipy/interpolate/rbf.py", line 231, in _call_norm
 return self.norm(x1, x2)
 File "/usr/local/lib/python3.4/dist-packages/scipy/interpolate/rbf.py", line 118, in _euclidean_norm
 return np.sqrt(((x1 - x2)**2).sum(axis=0))
 MemoryError

My array size is only 567. I have 8 GB of memory. I can post the code if necessary.

**Comment by maniteja123** [comment]
Hi, I am not sure if I know a plausible reason with my knowledge but it would be helpful if you can post the code if possible so that we can check if the MemoryError can be reproduced and try to figure out the cause. Thanks!

**Comment by winash12** [comment]
`grbs = pygrib.open('20000')


grb = grbs.select(name='Geopotential',level=500)[0]
data = grb.values

hgt = [x/10 for x in data]
lat,lon = grb.latlons()

lon,lat = np.meshgrid(lon, lat,sparse=True,copy=False)

m=Basemap(projection='mill',lat_ts=10,llcrnrlon=lon.min(), \
urcrnrlon=lon.max(),llcrnrlat=lat.min(),urcrnrlat=lat.max(), \
      resolution=None)


 x,y = m(lon,lat)

 rbf = scipy.interpolate.Rbf(x, y, data, function='linear')
 zi = rbf(x, y)`

**Comment by maniteja123** [comment]
Sorry for so my ignorance but is '20000' a filename because that is what I understand from the docs ? Would it be possible to get the data ? Also can you see [this thread](https://mail.scipy.org/pipermail/scipy-user/2009-April/020607.html). If I understand the discussion there correctly, Rbf uses all the data points for interpolation and might be slow. But having said that, someone experienced should comment here to actually diagnose the problem rather than me trying to figure it out. Sorry that I couldn't be more helpful here.

**Comment by winash12** [comment]
It is a file yes. It is a big file. Do you want me to upload it ?

**Comment by maniteja123** [comment]
That would be nice but I suppose it's not preferable to upload it here. In case it is not publicly available data, it would probably be better to upload it somewhere else and share the link.

**Comment by pv** [comment]
Please show the output from
```
print(x.shape, y.shape, data.shape)
```
added before call to scipy.interpolate.Rbf.

**Comment by winash12** [comment]
x.shape = (1, 224961)
y.shape =  (224961, 1) 
data.shape = (561, 401)

**Comment by pv** [comment]
561*401 = 224961 is too big for Rbf. Your data is on a grid, so use a 
method designed for that.
