### ISSUE TITLE
scipy.signal.bspline (and cubic) returns wrong result

### ISSUE THREAD

**Issue by nchouika** [scipy/scipy#6393]
I noticed two different issues. The important one is the following:

``` python
import scipy.signal as sig

sig.cubic(-1.1)
Out[65]: array(0.12149999999999996)

sig.bspline(-1.1,3)
Out[66]: array(0.0)
```

For values x < -1, bspline(x,3) returns 0.0 but it shouldn't. cubic(x) returns the correct value (I guess).

I also noticed strange behaviour (not sure if wanted) when using integers and not floats:

``` python
sig.cubic(1)
Out[70]: array(0)

sig.cubic(1.)
Out[71]: array(0.16666666666666666)

sig.bspline(1.,3)
Out[72]: array(0.16666666666666666)

sig.bspline(1,3)
Out[73]: array(0)
```

Both functions return 0 when dealing with integers...

Also, why doesn't it return a result with the same shape as the argument (i.e. a scalar here)?

Hope it helps, and thank you for the good work!

Using Python 3.5.1, numpy 1.11.0, scipy 0.17.1.

**Comment by sethtroisi** [comment]
Test cases from #6846 were eventually merged as part of #9035

`sig.cubic` matches `sig.bspline` result in the first example.
