### ISSUE TITLE
scipy.special.genlaguerre doesn't always accept numpy arrays for n or alpha

### ISSUE THREAD

**Issue by tylerharvey** [scipy/scipy#6395]
When passed a numpy array for n or alpha, genlaguerre inconsistently evaluates conditionals to check for valid values of n and alpha:
in orthogonal.py:
in function genlaguerre():
434:    if any(alpha <= -1):
435:        raise ValueError("alpha must be > -1")
436:    if n < 0:
437:        raise ValueError("n must be nonnegative.")
in la_roots(), which is called by genlaguerre():
406:    if n < 1 or n != m:
407:        raise ValueError("n must be a positive integer.")
408:    if alpha < -1:
409:        raise ValueError("alpha must be greater than -1.")

It looks like the documentation should probably be updated to clarify that n must be a scalar value, as the function would need to be completely rewritten to allow for numpy arrays, but line 408 could be rewritten to be consistent with 434.

Thanks for supporting obscure polynomials!

**Comment by pv** [comment]
Note that if you need just values of the polynomial and not its power 
basis representation, use eval_genlaguerre instead.
