### ISSUE TITLE
Add ability to use left and right censored data in the .fit() methods for each continuous_rv distribution

### ISSUE THREAD

**Issue by derrynknife** [scipy/scipy#6399]
It would be excellent if the MLE estimation for each continuous distribution had the ability to use left or right censored data in the fit method.

Left, and to a larger extent, Right censored data are an important part of survival analysis and reliability engneering

**Comment by ev-br** [comment]
What are left/right censored data?

**Comment by edwardreed81** [comment]
Right censored data is when you have a individual for whom you haven't observed an event (death or whatever). Left censored data is when you have individuals for whom you didn't observe birth.

Consider a simple case of studying human mortality and you have a dataset of birth and death records for a given population.

Right censored data would be the age of the individuals still alive at the end of the study period. I think this is probably easiest to implement.
Left censored data would be individuals for whom you don't know their birth date (incomplete data?), but do know their death date.

The ability to fit distributions using this data is fairly standard in survival analysis and is implemented in Python for a couple basic distributions by the excellent [lifelines](https://github.com/CamDavidsonPilon/lifelines) project. It would be very useful to be able to easily use this sort of data for any of the distributions in scipy.stats.

**Comment by slightlynybbled** [comment]
I'm in the same boat.  I'm an engineer trying to use the models, but I can't seem to find the most straightforward method of utilizing censored data.

**Comment by rgommers** [comment]
Support for censored data in the `fit` method of continuous distributions is now on our [roadmap](http://scipy.github.io/devdocs/roadmap-detailed.html). It's fairly likely to materialize over the next year. 

I'll close this issue since it's now on the roadmap so it's clear we'd like to have this.

**Comment by jtlz2** [comment]
@rgommers The roadmap link gives a 404 - any update?

**Comment by rgommers** [comment]
http://scipy.github.io/devdocs/dev/roadmap-detailed.html

**Comment by derrynknife** [comment]
For all those who might be interested. I have created a package dedicated to this and other survival analysis related problems. Still developing, but can be used until scipy gets this functionality. Package is [SurPyval](https://github.com/derrynknife/SurPyval)
