### ISSUE TITLE
Sparse csr matrix returns nan on 0.0/1.0

### ISSUE THREAD

**Issue by nazgul17** [scipy/scipy#6401]
I spotted an unexpected behavior in scipy.sparse.csr_matrix, which seems a bug to me. Can anyone confirm that this is not normal? I am not an expert in sparse structures so I may be misunderstanding proper usage.

    >>> import scipy.sparse
    >>> a=scipy.sparse.csr_matrix((1,1))
    >>> b=scipy.sparse.csr_matrix((1,1))
    >>> b[0,0]=1
    /home/marco/anaconda3/envs/py35/lib/python3.5/site-packages/scipy/sparse/compressed.py:730: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
      SparseEfficiencyWarning)
    >>> a/b
    matrix([[ nan]])

On the other hand, numpy properly handles this:

    >>> import numpy as np
    >>> a=np.zeros((1,1))
    >>> b=np.ones((1,1))
    >>> a/b
    array([[ 0.]])

Context:

    Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
    >>> scipy.__version__
    '0.17.1'
    >>> scipy.__numpy_version__
    '1.11.1'
    >>> np.__version__
    '1.11.1'

For reference, I posted a question on StackOverflow (before posting here) at: http://stackoverflow.com/questions/38516694/scipy-sparse-csr-matrix-returns-nan-on-0-0-1-0

**Comment by perimosocordiae** [comment]
Confirming that this is a bug. It's located in the `_divide_sparse` method in [`scipy/sparse/compressed.py`](https://github.com/scipy/scipy/blob/0a03211f8a855b11ca6ae2dc9c4f6802063e308e/scipy/sparse/compressed.py#L1094), but I haven't looked into the exact cause at this time.

**Comment by perimosocordiae** [comment]
Looks like the statement in the comment isn't quite correct: values outside `self`'s sparsity pattern should always be NaN, but `r`'s sparsity pattern isn't necessarily a superset of `self`'s because `_binopt` trims away extra zeros.
