### ISSUE TITLE
_unequal_var_ttest_denom causes ZeroDivisionError in early samples

### ISSUE THREAD

**Issue by cheribral** [scipy/scipy#6409]
I am using python2.7 on CentOS 7, the latest version of scipy from pip.

def _unequal_var_ttest_denom(v1, n1, v2, n2):

When v2 (standard deviation from sample two passed from ttest_ind_from_stats) is 0, the context manager has no effect, and the code halts on a ZeroDivisionError exception. I've worked around it by modifying the code to catch the exception and assign df to np.nan, but not sure what should really be happening here.

**Comment by ev-br** [comment]
Can you add a self-contained example which reproduces the problem please?

**Comment by cheribral** [comment]
Sure, here you go:
```
Python 2.7.5 (default, Nov 20 2015, 02:00:19) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy import stats
>>> stats.ttest_ind_from_stats(0.0,0.0,6.0,0.0,0.0,6.0,False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/scipy/stats/stats.py", line 3754, in ttest_ind_from_stats
    std2**2, nobs2)
  File "/usr/lib64/python2.7/site-packages/scipy/stats/stats.py", line 3680, in _unequal_var_ttest_denom
    df = (vn1 + vn2)**2 / (vn1**2 / (n1 - 1) + vn2**2 / (n2 - 1))
ZeroDivisionError: float division by zero
```

**Comment by ev-br** [comment]
Thanks.
What would you expect the function to do given this input?

**Comment by cheribral** [comment]
Based on the code and scipy documentation, I'm assuming that since the errstate context manager is used with divide='ignore', raising a ZeroDivisionError exception isn't intended.  Also, df is tested with isnan() in the next step, so it appears things were meant to continue under zero division conditions.

To answer your question more directly, I would expect the function to return with df=1.

**Comment by WarrenWeckesser** [comment]
A fix for this is in https://github.com/scipy/scipy/pull/13366.
