### ISSUE TITLE
algebraic sorting in sparse.linalg.eigsh fails for hermitian input

### ISSUE THREAD

**Issue by ltalirz** [scipy/scipy#6410]
I am using `scipy.sparse.linalg.eigsh` on hermitian matrices, asking for the (necessarily real) eigenvalues to be sorted algebraically, starting from the smallest eigenvalue (`which='SA'`).

It seems that for certain matrix sizes and for certain (comparatively large) number of requested eigenvalues/eigenvectors, the sorting breaks down (and it does so without warning).

The code below sets up a sparse real symmetric matrix, once using a real and once a complex representation (with zero imaginary part). It then computes the first k eigenvalues (printing only the first three).
The real version works fine.
For the complex version, eigenvalue ordering breaks down for large enough k (but still significantly below the dimension of the matrix).

```python
import scipy.sparse as sp
import scipy.sparse.linalg as spla

n=101

print("First three eigenvalues for real symmetric input")
t_real = sp.diags([ 1, -2, 1],[-1,0,1], shape=(n,n))
for k in [n/3,n/2,n-3,n-2]:
    eva, evc = spla.eigsh(t_real, k=k, which='SA')
    print("k = {}: {}".format(k, eva[:3]))

print("First three eigenvalues for real symmetric input")
print("(but stored as complex array).")
t_cplx = sp.diags([ 1+0J, -2+0J, 1+0J],[-1,0,1], shape=(n,n))
for k in [n/3,n/2,n-3,n-2]:
    eva, evc = spla.eigsh(t_cplx, k=k, which='SA')
    print("k = {}: {}".format(k, eva[:3]))
```

outputs

````
$ python mwe.py
First three eigenvalues for real symmetric input
k = 33: [-3.99905144 -3.99620666 -3.99146835]
k = 50: [-3.99905144 -3.99620666 -3.99146835]
k = 98: [-3.99905144 -3.99620666 -3.99146835]
k = 99: [-3.99905144 -3.99620666 -3.99146835]
First three eigenvalues for real symmetric input
(but stored as complex array).
k = 33: [-3.99905144 -3.99620666 -3.99146835]
k = 50: [-2.06159012 -2.12312181 -2.18453672]
k = 98: [-0.01515898 -0.02366906 -0.0340538 ]
k = 99: [-0.00853165 -0.01515898 -0.02366906]
```

Note: When using complex arrays, the problem seems to be just the *ordering* of the eigenvalues (i.e. the actual smallest algebraic eigenvalues are still contained in the list).


I am using python 2.7.12, scipy 0.17.1

**Comment by pv** [comment]
The order is different since complex-valued matrices are computed via 
the nonsymmetric ZNAUPD/ZNEUPD mode 'SR', which behaves differently. 
Note that the documentation of eighs does not claim the eigenvalues are 
ordered.

**Comment by ltalirz** [comment]
> Note that the documentation of eighs does not claim the eigenvalues are
ordered.

Oh, you are right - sorry I didn't notice! I guess I was just used to this behavior from linalg.eigh and then found the same behavior with eigsh with `which='SA'` for some choices of parameters, while not for others.

One might consider adding a warning to the documentation of `which` (something like "Note: eigenvalues will not be ordered in general.") but I admit that just considering the other options for `which` should probably lead the reader to this conclusion as well.

Thanks for the quick feedback, the issue can be closed.
