### ISSUE TITLE
import scipy.stats fails   (Reason: image not found)

### ISSUE THREAD

**Issue by capybaralet** [scipy/scipy#6412]
I'm on a mac.
Version '0.17.1'

In [4]: import scipy.stats
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-b66176eb2d0a> in <module>()
----> 1 import scipy.stats

/Users/david/anaconda/lib/python2.7/site-packages/scipy/stats/__init__.py in <module>()
    336 from __future__ import division, print_function, absolute_import
    337 
--> 338 from .stats import *
    339 from .distributions import *
    340 from .morestats import *

/Users/david/anaconda/lib/python2.7/site-packages/scipy/stats/stats.py in <module>()
    178 from scipy._lib.six import callable, string_types
    179 from numpy import array, asarray, ma, zeros
--> 180 import scipy.special as special
    181 import scipy.linalg as linalg
    182 import numpy as np

/Users/david/anaconda/lib/python2.7/site-packages/scipy/special/__init__.py in <module>()
    625 from __future__ import division, print_function, absolute_import
    626 
--> 627 from ._ufuncs import *
    628 
    629 from .basic import *

ImportError: dlopen(/Users/david/anaconda/lib/python2.7/site-packages/scipy/special/_ufuncs.so, 2): Library not loaded: /usr/local/lib/libgcc_s.1.dylib
  Referenced from: /Users/david/anaconda/lib/python2.7/site-packages/scipy/special/_ufuncs.so
  Reason: image not found

**Comment by matthew-brett** [comment]
How did you install scipy?

**Comment by pv** [comment]
Closing (no reply, apparent installation issue)

**Comment by capybaralet** [comment]
Hey sorry for the late reply.
I just uninstalled and installed with conda, and I have (I think) the same error:

Davids-MacBook-Air-3:CS188.1x-Project3 david$ conda uninstall scipy
Fetching package metadata .......
Solving package specifications: ..........

Package plan for package removal in environment /Users/david/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    readline-6.2               |                2         274 KB
    setuptools-23.0.0          |           py27_0         456 KB
    wheel-0.29.0               |           py27_0          81 KB
    pip-8.1.2                  |           py27_0         1.5 MB
    ------------------------------------------------------------
                                           Total:         2.3 MB

The following NEW packages will be INSTALLED:

    wheel:      0.29.0-py27_0               

The following packages will be REMOVED:

    scipy:      0.18.0-np111py27_0          

The following packages will be UPDATED:

    pip:        1.5.6-py27_0       <unknown> --> 8.1.2-py27_0 
    setuptools: 5.8-py27_0         <unknown> --> 23.0.0-py27_0

The following packages will be SUPERCEDED by a higher-priority channel:

    readline:   6.2-2              <unknown> --> 6.2-2        

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
readline-6.2-2 100% |###############################################################################################################################################| Time: 0:00:00 434.96 kB/s
setuptools-23. 100% |###############################################################################################################################################| Time: 0:00:00 619.02 kB/s
wheel-0.29.0-p 100% |###############################################################################################################################################| Time: 0:00:00 243.52 kB/s
pip-8.1.2-py27 100% |###############################################################################################################################################| Time: 0:00:03 424.28 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################################################################################################################################| 100%
Davids-MacBook-Air-3:CS188.1x-Project3 david$ conda install scipy
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /Users/david/anaconda:

The following NEW packages will be INSTALLED:

    scipy: 0.18.0-np111py27_0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##################################################################################################################################################################| 100%










Davids-MacBook-Air-3:CS188.1x-Project3 david$ ipython
improt sPython 2.7.12 |Anaconda 2.1.0 (x86_64)| (default, Jul  2 2016, 17:43:17) 
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import scipy
sc
In [2]: import scipy.stats
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-b66176eb2d0a> in <module>()
----> 1 import scipy.stats

/Users/david/anaconda/lib/python2.7/site-packages/scipy/stats/__init__.py in <module>()
    342 from __future__ import division, print_function, absolute_import
    343 
--> 344 from .stats import *
    345 from .distributions import *
    346 from .morestats import *

/Users/david/anaconda/lib/python2.7/site-packages/scipy/stats/stats.py in <module>()
    171 from scipy._lib._version import NumpyVersion
    172 from numpy import array, asarray, ma, zeros
--> 173 import scipy.special as special
    174 import scipy.linalg as linalg
    175 import numpy as np

/Users/david/anaconda/lib/python2.7/site-packages/scipy/special/__init__.py in <module>()
    634 from __future__ import division, print_function, absolute_import
    635 
--> 636 from ._ufuncs import *
    637 
    638 from .basic import *

ImportError: dlopen(/Users/david/anaconda/lib/python2.7/site-packages/scipy/special/_ufuncs.so, 2): Library not loaded: /usr/local/lib/libgcc_s.1.dylib
  Referenced from: /Users/david/anaconda/lib/python2.7/site-packages/scipy/special/_ufuncs.so
  Reason: image not found

In [3]: scipy.__file__
Out[3]: '/Users/david/anaconda/lib/python2.7/site-packages/scipy/__init__.pyc'

**Comment by matthew-brett** [comment]
I suppose this must be an Anaconda install issue.  Would you mind reporting over at https://github.com/ContinuumIO/anaconda-issues/issues ?

**Comment by oztalha** [comment]
I got the same error, despite I had installed scipy via pip3. Uninstalling and reinstalling solved the problem. The issue was due to that I installed xcode command line tools (which I believe updated the clang) after installing scipy.

**Comment by andyharless** [comment]
What worked for me:
`conda config --add channels conda-forge`
`conda install libgfortran=3.0.0=0`
See [this thread](https://github.com/conda-forge/numpy-feedstock/issues/47).  Apparently libgfortran 3.0.1 is missing something.

**Comment by felixm3** [comment]
Uninstalling and reinstalling scipy worked for me.
