### ISSUE TITLE
scipy.stats.dirichlet computes multivariate gaussian differential entropy??

### ISSUE THREAD

**Issue by capybaralet** [scipy/scipy#6413]
The docs seem to be wrong here:
"entropy(alpha)	Compute the differential entropy of the multivariate normal."

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.dirichlet.html

**Comment by ev-br** [comment]
Clearly an copy-paste error which slipped past reviews. Would you be interested in a PR with a fix?
