### ISSUE TITLE
scipy.stats.kendaltau with nan_policy='omit' is slow

### ISSUE THREAD

**Issue by gmonkman** [scipy/scipy#6416]
I am using scipy.stats.kendaltau with nan_policy='omit' (good addition), which I call multiple times as i'm doing permutation testing.

Previously I was doing some preprocessing to remove ndarray nans on a fairly modest pair of 2d ndarrays (118x77), but switched having noticed the feature. The performance of nan_policy='omit' is much less than my ndarray 'hacks' to remove my nans + running kendalltau without nan_policy='omit'  (this isn't intended as a boast!).

I have uploaded a screencap profiling the two calls in Visual Studio (time is in milliseconds).

![tau](https://cloud.githubusercontent.com/assets/15924596/17154260/24d2bc52-5378-11e6-8d23-0a01edd1b202.jpg)

**Comment by WarrenWeckesser** [comment]
Do you realize that if `nan_policy` is `'propagate'`, and there is a `nan` in the input, the function basically returns *immediately* without doing any computation?  Check the return values in your two cases.  I expect you'll see that in the `'propagate` case, the return value is `KendalltauResult(correlation=nan, pvalue=nan)`.

**Comment by gmonkman** [comment]
Yup, good point! However, the absolute time is slow - >4s. Another screenshot comparing matrix with no-nans and one with nans. However you cut it >4s is slow for max of 12k paired values.

Appreciate that not many people do permutation testing and are prepared to wait for 4 seconds, although i'll go back to removing the nans in my code then use propagate.

![tau1](https://cloud.githubusercontent.com/assets/15924596/17167997/d6668bce-53d7-11e6-8b50-ad48eb5da370.JPG)

**Comment by ev-br** [comment]
Something's amiss with the last set of your timings:

```
In [66]: x = np.arange(118*77, dtype=float).reshape(118, 77)

In [67]: y = x.copy()

In [68]: %timeit stats.kendalltau(x, y, nan_policy='propagate')
1000 loops, best of 3: 1.76 ms per loop

In [69]: %timeit stats.kendalltau(x, y, nan_policy='omit')
1000 loops, best of 3: 1.77 ms per loop
```

However, if there is a `nan`, things do get much worse:

```
In [70]: x[-1] = np.nan

In [71]: stats.kendalltau(x, y, nan_policy='omit') 
Out[71]: KendalltauResult(correlation=1.0, pvalue=0.0)

In [72]: %timeit stats.kendalltau(x, y, nan_policy='omit')         # ouch
1 loop, best of 3: 6.62 s per loop
 ```

However, this does not have to be like that:

``` 
In [91]: %%timeit
mask = x == x
stats.kendalltau(x[mask], y[mask], nan_policy='propagate')
   ....: 
1000 loops, best of 3: 1.79 ms per loop
```

The code path which seems slow is this:
https://github.com/scipy/scipy/blob/master/scipy/stats/stats.py#L3523
So likely there's something to improve in mstats.kendalltau

**Comment by ev-br** [comment]
> So likely there's something to improve in mstats.kendalltau

Oh yes, there is: https://github.com/scipy/scipy/blob/master/scipy/stats/mstats_basic.py#L497

The stats version got substantially improved recently in https://github.com/scipy/scipy/pull/5548; it would be a nice project to bring the improvements over to the mstats version (or just do preprocessing in the stats.kendalltau without delegating to mstats). Is it something you'd be interested in looking at @gmonkman ?

**Comment by gmonkman** [comment]
Soz, I wasnt very clear on the last test. The first 'propogate' test used a matrix with nans, where the second 'omit' was as show.

I'm afraid my python is currently too weak to consider delving into the depths of mstats_basic.py however, if the issue is still active in a month or two, I will have a closer look.

**Comment by mdhaber** [comment]
Just thought I'd mention that this problem still seems to exist in master.

**Comment by mdhaber** [comment]
gh-14651 will reimplement `nan_policy` and masked array support for `kendalltau` in a way that will fix this. For `axis=None` - which is how `kendalltau` works right now - it will have essentially the same performance as in @ev-br's [comment](https://github.com/scipy/scipy/issues/6416#issuecomment-236058503). I added this to the list of related issues in gh-14651, so I'll close this one.
