### ISSUE TITLE
scipy.misc.imresize converts images to uint8

### ISSUE THREAD

**Issue by bbrister** [scipy/scipy#6417]
Scipy version 0.17.1
PIL version 1.1.7

Here is an example program:

```
import scipy.misc
import scipy.ndimage
import numpy as np

im1 = np.array([[0.5, 0.5], [0.5, 0.5]])
im2 = scipy.ndimage.zoom(im1, 1.0)
im3 = scipy.misc.imresize(im1, im1.shape)

```

After running this code, im2 is identical to im1, while im3 is an array of all zeros, of type uint8. This can lead to really egregious bugs. For example, many medical images use 12 bits per pixel, and converting to 8 bits can cause unacceptable loss of fidelity.

**Comment by person142** [comment]
The function `imresize` accepts a `mode` keyword which has to be `L`, `P`, `F`, or `I`, i.e. the subset of pil(low) modes:

http://pillow.readthedocs.io/en/3.0.x/handbook/concepts.html#concept-modes

which are supported by `scipy.misc.toimage`. It appears that if `mode` is `None` then it is later converted to `L`, which should be clarified in the docs, as should the supported modes. The closest thing to the original image the function would support is

`im3 = scipy.misc.imresize(im1, im1.shape, mode='F')`,

which would return `im1` with its entries converted to `float32`.

**Comment by bbrister** [comment]
Thanks, this clarifies things. Wouldn't it be better to select a default mode based on the type of the input? In the above example I would expect the default mode to be 'F'. That would probably eliminate most of the issues for people who are not aware of PIL modes.

**Comment by person142** [comment]
Yes, I reckon it would be. The current behavior comes from a call to `scipy.misc.toimage` done at the beginning of the function, and the equivalent pil(low) function:

https://pillow.readthedocs.io/en/latest/reference/Image.html#PIL.Image.fromarray

does convert based on types, i.e.
```python
import numpy as np
from PIL import Image

im = Image.fromarray(np.array([[0.5, 0.5], [0.5, 0.5]]))
```

works how you think it will. It probably won't be possible to change the default behavior because of back-compatibility, however.

TBH I'm not sure why these functions are here; since it requires that pil(low) be installed why not just use it directly? Perhaps someone who's been around longer remembers the idea behind the design?

**Comment by pv** [comment]
Those functions are ancient stuff --- if it doesn't seem to make sense 
then it probably doesn't.

**Comment by pv** [comment]
They're from 2002, so they indeed predate PIL.fromarray (fromimage used 
to interpret the raw image data).

**Comment by person142** [comment]
@pv: objections to deprecating when there's a drop-in Pillow replacement?

**Comment by soodabehzz** [comment]
@person142 : When I use mode parameter , i get an error (**ValueError, Mode is unknown or incompatible with input array shape**.) 
How can I solve this issue?
Thanks

**Comment by person142** [comment]
Hard to say without a stand-alone code sample. If there's a bug distinct from this issue then it would be better to open a new issue.

**Comment by soodabehzz** [comment]
`from scipy import misc`
`image = misc.imread('/home/ictc/lamem/images/00000162.jpg')`
`image = misc.imresize(image, img_size, interp='bilinear', mode = 'F')`
in the last line of code I got this error : `ValueError, Mode is unknown or incompatible with input array shape`

I checked the code of imresize function and I know it can't get the 'F' value for mode parameter but when I was searching, there were a lot of sample code that used imresize func by this parameter and of course F value. 
My problem is I want imresize not to convert my image to uint8. 
I used resize of opnecv library as alternative but it was completely different from imresize in matlab. 
I want an alternative that  result of it is the same as matlab function. 
Thanks in advance

**Comment by mtobeiyf** [comment]
@soodabehzz Same error here. Did you find any solutions?

**Comment by soodabehzz** [comment]
@mtobeiyf The best answer is "resize function" from Opencv library, but it's not the same as imresize in matlab. At least it doesn't convert image to uint8.

**Comment by cdouglass** [comment]
Is this the same issue as #5305?

**Comment by rgommers** [comment]
> The best answer is "resize function" from Opencv library, but it's not the same as imresize in matlab. At least it doesn't convert image to uint8.

Scikit-image also has a good resize function: http://scikit-image.org/docs/dev/api/skimage.transform.html#skimage.transform.resize

> Is this the same issue as #5305?

Looks like they have the same root cause (``toimage``), but the solutions may be different so good to keep both issues open I think.

**Comment by rgommers** [comment]
> Edit: previous discussion about deprecating this stuff in #5289

The most relevant discussion on what to do with this set of functions is gh-6242

**Comment by thuyang** [comment]
same error here.

**Comment by rgommers** [comment]
Too many people are running into this - changed label to ``defect`` and marked for 1.0 to do something about.

**Comment by psgl** [comment]
It seems like a design problem. Image resizing should not fiddle around with the image's type, unless explicitly requested by the user. Furthermore, when the user asks for type conversion, the function should only cast the values, not rescale them (unless, again, explicitly requested by the user).
To the best of my knowledge, this is the convention in the computer vision/image processing community.

**Comment by larsoner** [comment]
Perhaps we should deprecate these functions, with a long time window (1.2?). It seems like there are better alternatives, especially given that these depend on `pillow` anyway.

@psgl are you happy with what `pillow` and/or `scipy.ndimage.zoom` does?

**Comment by psgl** [comment]
​I'm unaware of `pillow`'s behavior (I've been using OpenCV in C++ for most of my career). I also haven't got the chance to use `scipy.ndimage.zoom`, but from the documentation it is apparent that the internal calculations should be done in floats. Whether the return type is kept as floats or converted back to the original type is a matter of design (personally, in the case of `scipy.ndimage.zoom`, I'd keep it as floats). ​As long as the type of the returned array is _explicitly stated_ in the documentation, 99% of the user's confusion (and hence, frustration) would be avoided.

The issue with `scipy.misc.resize` is that the `mode` parameter has the default of `'None'`, which leads the user to understand nothing changes, as far as type is concerned. A quick fix could be changing the default from `'None'` to `'L'`, which is what actually happens in the internal call to `toimage()`. In the long run, `'None'` should return to be the default.

**Comment by rgommers** [comment]
> A quick fix could be changing the default from 'None' to 'L', which is what actually happens in the internal call to toimage().

This is true for 2-D images, not for 3-D. So we can't explicitly change to ``mode='L'``. We can put clear warnings about both casting and bytescaling in the docs though. That would avoid most of the pain.

I'm working on this now.

**Comment by rgommers** [comment]
Deprecations and doc warnings in gh-7869
