### ISSUE TITLE
[Feature Request]Bayesian Optimization

### ISSUE THREAD

**Issue by zh19970205** [scipy/scipy#6418]
bayesian optimization(https://en.wikipedia.org/wiki/Bayesian_optimization) is a dynamic global optimization algorithm, by getting which sampled point to calculate next step to have best expect improvement, which is useful when calculating is expensive.

there is implementation in github
- https://github.com/Yelp/MOE
- https://github.com/HIPS/Spearmint

but for users, it is not easy to install

**Comment by innisfree** [comment]
To be clear, this is an alternative to the algorithms implemented in scipy.optimize? http://docs.scipy.org/doc/scipy/reference/optimize.html
