### ISSUE TITLE
scipy.linalg.solve_banded overwrites input 'b' when the inversion matrix is 1x1

### ISSUE THREAD

**Issue by lciti** [scipy/scipy#6421]
I am using `scipy.linalg.solve_banded` to solve a problem `x = A\b` and I noticed a problem when `A` has only 1 column.

The following code shows that `b` gets overwritten in this case (`K=1`), while the code works fine for other cases (e.g., `K=2`):
```
K = 1
b = np.random.standard_normal([K, 10000])
b_copy = b + 0
U = np.array([[0,1.],[2.,3.]])
sp.linalg.solve_banded((0,1), U[:,:K], b)
np.sum((b - b_copy)**2)
```

I think the problem is the following section of `scipy.linalg.solve_banded`:
```
    if a1.shape[-1] == 1:
        b2 = np.array(b1, copy=overwrite_b)
        b2 /= a1[1, 0]
        return b2
```
I think `copy=overwrite_b` should be `copy=not overwrite_b`.

**Comment by ev-br** [comment]
Thanks! 
Are you intetested in sending a pull request with a fix? That would put you on the author list for the next release.

**Comment by ev-br** [comment]
Fixed by gh-6421, closing.
