### ISSUE TITLE
Documentation incorrect for scipy.interpolate.interp2d

### ISSUE THREAD

**Issue by EmperorDali** [scipy/scipy#6423]
The docstring for `scipy.interpolate.interp2d` appears to be incorrect.

http://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.interpolate.interp2d.html

`interp2d` returns an interpolating object, but the docstring lists the function as returning an ndarray of interpolated values.

**Comment by ev-br** [comment]
Yup, it could/should be made consistent with the docstring of `interp1d`. Are you interested in sending a pull request?

**Comment by EmperorDali** [comment]
Yeah, I can take a look at it this weekend. Do you need to 'assign' this bug to me?

**Comment by ev-br** [comment]
We typically don't bother formally assigning things to people. Looking forward for the PR!

**Comment by smopucilowski** [comment]
Commit 0fbef6d6a5953a8a08c3eb7cb620dcc4285d946d resolved this documentation issue.

**Comment by andyfaff** [comment]
Closing because it is addressed in master
