### ISSUE TITLE
gmpy2 installation in the travis-ci build is broken?

### ISSUE THREAD

**Issue by skirpichev** [scipy/scipy#6426]
In [my project](https://github.com/diofant/diofant/pull/292) I used literally your code snippet for building gmpy2 deps:
```
        # Install gmpy2 dependencies
        - mkdir -p $HOME/.local
        - wget ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.2.tar.gz
        - tar xzvf mpc-1.0.2.tar.gz
        - pushd mpc-1.0.2
        - ./configure --prefix=$HOME/.local
        - make
        - make install
        - popd
        - export CPATH=$HOME/.local/include
        - export LIBRARY_PATH=$HOME/.local/lib
```

Unfortunately, it seems this doesn't work, see [build log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/147931278/log.txt): line "ground types: python" clearly shows that builtin python integers are used.

Probably, you should set LD_LIBRARY_PATH=$HOME/.local/lib, this fixes problem in my case, see [log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/147935643/log.txt).

I can prepare this trivial fix, but part of the problem is that you don't check that mpmath's uses gmpy.  At least you could print mpmath.libmp.BACKEND.

**Comment by ev-br** [comment]
This would be welcome --- both a diagnostic print (like we do with numpy relaxed stride checking) and a fix. Thanks!
