### ISSUE TITLE
scipy.linalg.eigsh cannot get all eigenvalues

### ISSUE THREAD

**Issue by dswah** [scipy/scipy#6430]
I cannot seem to grab all the eigenvalues of a sparse matrix. I am limited to shape(matrix)[0] - 1 eigenvalues.

For instance when i do:

```
A = scipy.sparse.diags([2,1], shape=(2,2))
scipy.sparse.linalg.eigsh(A, k=2, return_eigenvectors=False)
```

i get the error:

```
1519     n = A.shape[0]
1520 
1521     if k <= 0 or k >= n:
1522         raise ValueError("k must be between 1 and the order of the "
1523                          "square input matrix.")
```

shouldn't line 1521 read:

```
if k <= 0 or k > n:
```

?

if i do the same using dense version it works:

```
A = scipy.sparse.diags([2,1], shape=(2,2)).todense()
np.linalg.eigvals(A)
```

returns 

```
array([ 2.,  1.])
```

**Comment by pv** [comment]
The restriction is correct, it's a limitation of ARPACK.

**Comment by pv** [comment]
The routine of course could automatically convert to dense and call 
`eigs` --- this is what e.g. Octave does.

**Comment by dswah** [comment]
ah ok! that is interesting. 

is this limitation a result of doing computations with sparse representations?

**Comment by pv** [comment]
No, it's a peculiarity of the particular lanczos/arnoldi implementation.

**Comment by amanp10** [comment]
I would like to work on it.

**Comment by pv** [comment]
Go ahead --- note that there is no need to ask or announce beforehand 
what you are working on, if there's no existing pull request it's 
probably safe to assume nobody else has started on it.

**Comment by amanp10** [comment]
If I am getting it right, I am supposed to add few lines of code in `eigs` and `eigsh` so that if user passes `k=N` or (`k=N-1` for `eigs`) it should automatically call `np.linalg.eigvals()` after converting the array to dense. Am I right?

**Comment by pv** [comment]
Yes, or eig() if eigenvectors are wanted.

**Comment by amanp10** [comment]
I feel a warning should be raised telling the user about the limitations of `k` and that `eig()` is being is used instead of `eigs()` etc. Also, only right eigenvectors are to be returned I suppose, as user has not mentioned either left or right.
