### ISSUE TITLE
Figure out ABI break policy for scipy.special Cython API

### ISSUE THREAD

**Issue by pv** [scipy/scipy#6440]
We may want to change function signatures in scipy.special Cython API, e.g. extend to complex domain. If signatures are changed, this translates to an ABI break --- modules need to be re-Cythonized in order to work with revised signatures (using wrong version raises an exception, not segfault, if you try to use it with a function with changed signature --- so changes in general are well-behaved and localized).

There needs to be a policy on how to deal with this in upcoming releases. Should the ABI be changed at all? Do we need to mark the feature "experimental" for the next few releases and allow more flexible ABI policy?

I would suggest: we mark the feature experimental for now in the documentation for the next few releases, and explain there that (i) we allow ABI breaks between releases, and (ii) modules need to be re-Cythonized. After the next few releases: (iii) we start renaming the Cython API functions when signatures change.

**EDIT**: it seems the Cython import mechanism preserves ABI compatibility, as long as signatures are only *added* --- so we can probably instead go forward with just requiring strict ABI compatibility.

**Comment by ev-br** [comment]
+1 for marking it experimental.

**Comment by josef-pkt** [comment]
As potential down stream package maintainer:

+1 for marking it experimental, IMO correct longterm solution is better than avoiding short term pain.

I don't know much about the cython details
question: Will there be double and complex version separate as in LAPACK or are this fused types or something like that for the same function providing all supported dtypes.

(Aside: We are trying compilation of statsmodels extensions conditional on the scipy version in the next release 0.9 to use different cython LAPACK interfaces, but I expect we will need this only for a small number of releases. This hasn't bee merged and widely tested yet.)

**Comment by pv** [comment]
It's fused types, why adding more supported signatures needs recompilation.

**Comment by josef-pkt** [comment]
A more longer term question:

I think breaking ABI is ok during experimental introduction of the feature.
However, IIUC, with fused types you would have to break ABI also later if any new dtypes are supported.

Can we expect that this will be finished within a few releases?
Or do we need a different longterm policy to avoid ongoing ABI breaks?

**Comment by pv** [comment]
My long-term suggestion was to start renaming functions when dtypes are changed and maintain strict ABI compatibility.

**Comment by josef-pkt** [comment]
sounds good to me

on last clarification that I just thought of:

The recythonizing is required if any of the scipy.special cython api functions are used?
Those functions are not split up so that recythonizing is needed only on a function by function basis (recythonize only if the specific function used by downstream has been changed)

**Comment by pv** [comment]
It is required if you use a function from scipy.special.cython_special AND the signature of that specific function was changed.

**Comment by pv** [comment]
Sorry, let me correct: it seems the Cython import mechanism works in a way so that *adding* signatures is actually safe --- so the ABI is probably less of an issue.

**Comment by pv** [comment]
Closing.

**Comment by rth** [comment]
It would help if the scipy ABI compatibility policy was officially documented.  (Unless it is and I missed it).

For instance,  that would affect packages built on conda-forge that `cimport` scipy (e.g. https://github.com/conda-forge/staged-recipes/pull/4808#issuecomment-361775087)

**Comment by rgommers** [comment]
@rth I don't think it is documented now. Probably better to open a new issue for that, comments on closed issues tend to disappear in the noise.
