### ISSUE TITLE
scipy.spatial : In incremental mode volume is not recomputed

### ISSUE THREAD

**Issue by haudren** [scipy/scipy#6442]
This bug is quite straightforward, but I am unsure if it comes from the scipy bindings for `volume` I proposed some time last year or if it comes from Qhull itself.

Each time points are added to an incremental convex hull, its volume is not updated. Maybe even worse, the volume is not updated on closing the hull.

I wrote a [quick test](https://gist.github.com/haudren/926737aa11fe1f7f73b0ea81b9fa1386) that compares:
- Computing the hulls directly (:ok_hand:)
- Computing incrementally (:thumbsdown:)
- Computing incrementally with restart (:ok_hand:)

```python
3 point hull volume : 0.5
3 point incremental hull volume : 0.5
4 point hull volume : 1.0
4 point incremental hull volume : 0.5
Incremental hull closed volume : 0.5
Incremental hull volume with restart : 1.0
```

**Comment by pv** [comment]
Probably because `qh_getarea` has `if (qh->hasAreaVolume) return;` in 
the beginning. This flag should be cleared in `_QHull.volume_area`.

**Comment by haudren** [comment]
Indeed this seems to have fixed it ! However, I think I introduced a bug somewhere else, I'll submit a PR when it's fixed and I have tests.
