### ISSUE TITLE
KDTree and cKDTree gives different behaviour using data with lots of identical points.

### ISSUE THREAD

**Issue by ezietsman** [scipy/scipy#6444]
cKDTree seems to take very long to complete compared to KDTree for larger numbers of identical coordinates.

To reproduce:

    import numpy as np
    from scipy.spatial import cKDTree, KDTree

    xy = np.random.rand(100000).reshape(-1, 2)
    xy[0:1000]  = 0

    %timeit KDTree(xy)
    # 10 loops, best of 3: 150 ms per loop

    %timeit cKDTree(xy)
    # 1 loop, best of 3: 655 ms per loop

    xy[0:2000]  = 0
    %timeit KDTree(xy)
    # 10 loops, best of 3: 157 ms per loop

    %timeit cKDTree(xy)
    # 1 loop, best of 3: 5.15 s per loop

I'm running scipy 0.18.0 on osx.

**Comment by ev-br** [comment]
This sounds related to https://github.com/scipy/scipy/issues/6108. 

```
In [18]: xy = np.random.rand(100000).reshape(-1, 2)

In [19]: xy[0:2000]  = 0

In [20]: %timeit KDTree(xy)
1 loop, best of 3: 201 ms per loop

In [21]: %timeit cKDTree(xy)
1 loop, best of 3: 6.54 s per loop

In [22]: %timeit cKDTree(xy, balanced_tree=False)
100 loops, best of 3: 8.88 ms per loop
```

I still think there's an opportunity to improve the documentation, either the API docs (the cKDTree docstring) or the corresponding tutorial. Or add a notebook to Scipy cookbook.

**Comment by ezietsman** [comment]
Ah yes. Looks like it. I think the docstring should contain this information, esp since the behaviour is different from KDTree.

Thanks A Lot.

**Comment by ev-br** [comment]
A documentation-only pull request would be welcome.

**Comment by ezietsman** [comment]
Sure, I'll make one and send it through.
