### ISSUE TITLE
Doubt in Mahalanobis distance formula

### ISSUE THREAD

**Issue by kskrishnasangeeth** [scipy/scipy#6445]
Hi All,
I stepped through how Mahalanobis distance is calculated in `scipy.spatial.distance`

I could see the below implementation.

```
def mahalanobis(u, v, VI):
    u = _validate_vector(u)
    v = _validate_vector(v)
    VI = np.atleast_2d(VI)
    delta = u - v
    m = np.dot(np.dot(delta, VI), delta)
    return np.sqrt(m)
```

What is confusing me is that in the original formula [1] , there is  a `transpose` applied on the second `delta`. That seems to be missing in the line 

` m = np.dot(np.dot(delta, VI), delta)`

Can some one please clarify on this ?

[1] http://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html

**Comment by person142** [comment]
Perhaps this will help:

```python
>>> x, y = np.ones(10), np.ones(10)
>>> x.shape, y.shape
((10,), (10,))
>>> np.dot(x, y)
10.0
>>> x, y = x.reshape(1, 10), y.reshape(1, 10)
>>> x
array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])
>>> y
array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])
>>> np.dot(x, y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: shapes (1,10) and (1,10) not aligned: 10 (dim 1) != 1 (dim 0)
>>> np.dot(x, y.T)
array([[ 10.]])
```

IOW the documentation is thinking of the inputs as row vectors, which correspond to numpy arrays of shape `(1, n)`, but by default numpy creates arrays of shape `(n,)`, and on such arrays `dot` computes their dot product.

**Comment by person142** [comment]
Closing as there's no bug here; it's a difference in notation.
