### ISSUE TITLE
ENH: Zenodo?

### ISSUE THREAD

**Issue by Eric89GXL** [scipy/scipy#6446]
[Zenodo] (https://zenodo.org/) makes it easy for software releases to automatically have citable DOIs, e.g. the rightmost link at the top of the [MNE-Python README] (https://github.com/mne-tools/mne-python/blob/master/README.rst).

I'm happy to add this for SciPy -- sound useful?

**Comment by ev-br** [comment]
+1 from me.

How do you guys handle it: 
- Do you get a DOI for each release?
- How do you keep the list of DOI for past releases? (somewhere in the docs?)

**Comment by Eric89GXL** [comment]
> Do you get a DOI for each release?

Any commit that gets tagged on GitHub gets a DOI.

> How do you keep the list of DOI for past releases? (somewhere in the docs?)

We don't, but a simple search on the Zenodo site works okay:

https://zenodo.org/search?ln=en&p=mne-python&action_search=

**Comment by ev-br** [comment]
DOI-ing all tags sounds good to me.
I've a slight preference towards adding a DOI to the release notes as well, so that the release notes serve as the source of the ground truth about a release.

Could you ping the scipy-dev mailing list, too? Allegedly there are many people who are subscribed to the list but not GH issues.

**Comment by rgommers** [comment]
+1 for a DOI for every released version. Not sure about DOIs for alpha/beta/rc, or for other tags we may want to use in the future. Does that add value?

**Comment by Eric89GXL** [comment]
I don't actually have permissions to do it (probably need to be an owner), but someone with perms can go to https://zenodo.org/account/settings/github/ and turn on the `scipy/scipy` switch.

**Comment by rgommers** [comment]
I tried this a few days ago, but apparently you only get one chance to enable the scipy/scipy repo (on first login with your Github credentials). I missed that, and now I can't seem to find any way to enable this repo anymore. 

@pv want to do the honors here?

**Comment by tylerjereddy** [comment]
+1 
One unfortunate issue in some academic fields is that methodological details often get bumped to the supporting information of the manuscript, so the software citations often don't get indexed. Still, I think it is a good idea and can help justify the time spent on open source.

**Comment by pv** [comment]
Zenodo is now enabled. The hook it installed won't create DOIs for past releases automatically, however.

The current release can be uploaded manually. This wants an author list. I wonder what the automatic hook puts in the author list? I don't have time for this right now, so I suggest someone else does the manual upload of 0.18.0.

**Comment by pv** [comment]
Maybe the author list has to be the same as in release notes. Release manager first, the rest in alphabetical or commit count (`git shortlog -a -s -n`) order (first permuted to last author)?

**Comment by pv** [comment]
Ok, I'll create instead a new release tag with the same content as 0.18.0, so that zenodo does its magic --- scikit-learn did that, cf. https://github.com/scikit-learn/scikit-learn/releases/tag/0.17.1-1

**Comment by pv** [comment]
Here we go:

[![DOI](https://zenodo.org/badge/23917/scipy/scipy.svg)](https://zenodo.org/badge/latestdoi/23917/scipy/scipy)

Some points to note:

- Zenodo creates the initial DOI for the content you put in when you create the release. So best to make sure everything is in before creating it on github.

- It's possible to edit it manually later, but there's some sort of delay before the information updates. 

- Zenodo also generates author list automatically, apparently by commit count or some such metric, which may not be representative. It also does not include everyone, but only the 20 somesuch first entries. 

- People without correctly identified github account (Travis!) are excluded. I added him manually to the author list, but either it's still within the update delay or it doesn't work.

- I'm not sure if someone else than me can now edit the minted DOIs. Maybe someone knows?

**Comment by rgommers** [comment]
Thanks Pauli.

> I'm not sure if someone else than me can now edit the minted DOIs. Maybe someone knows? 

Don't see a way to edit anything, and Google isn't helping either.

> Entering the 500-people author list to their somewhat crappy web UI will not be fun.

No, that won't be much fun. Also not too sure of the value, and if we need all contributors ever instead of only those that contributed to the tagged release.

**Comment by ev-br** [comment]
Thanks a lot Pauli!

Would you clarify how this works when there's a new tag. Does a DOI get issued automatically (and then is there a way to prevent it, for, e.g. an rc tag), or is there some manual action which needs to be done after the tag is created?

**Comment by Eric89GXL** [comment]
The DOIs get created with every GitHub tag I think, but you might be able to delete them. If not, they can be ignored, too.

**Comment by ev-br** [comment]
And indeed, the webhook works and a DOI has been minted for 0.18.1 automagically (unless someone actually did something manual; anyone?)

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.154391.svg)](https://doi.org/10.5281/zenodo.154391)

**Comment by pv** [comment]
I didn't do anything, so it's probably working automatically. I'm not 
sure if they revised the author list generation algorithm or if it uses 
the previous one, but now Travis seems to be listed.

**Comment by Eric89GXL** [comment]
Sounds good. I'll go ahead and close this, then.
