### ISSUE TITLE
Documentation for scipy.cluster.hierarchy.to_tree is confusing / wrong

### ISSUE THREAD

**Issue by John-Jumper** [scipy/scipy#6451]
At http://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.to_tree.html#scipy.cluster.hierarchy.to_tree, the documentation says "The reference r to the root ClusterNode object is returned." but later specifies the return value as "L : list The pre-order traversal."  While you can certainly construct a pre-order traversal from the root node, these are different objects.

Best regards,
John Jumper

**Comment by rgommers** [comment]
Thanks for the report @John-Jumper. This should be fixed by gh-6621.
