### ISSUE TITLE
cannot import name cython_special

### ISSUE THREAD

**Issue by VictorRodriguez** [scipy/scipy#6452]
Hi I am trying to run the benchmarks however I get the following error: 

>>> from scipy.special import cython_special
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name cython_special

I already have scipy with pip installed as well as numpy

**Comment by person142** [comment]
The module ``cython_special`` is not in a released version of scipy. If you want to run those benchmarks you will need to build scipy against the git master branch.

**Comment by person142** [comment]
@VictorRodriguez: apologies, there is a bug here. Hopefully fixed in https://github.com/scipy/scipy/pull/6479.
