### ISSUE TITLE
Error in scipy.integrate.dblquad when using variable integration bounds and parametric arguments

### ISSUE THREAD

**Issue by jobovy** [scipy/scipy#6458]
Similar to #5452, ``dblquad`` fails when called with ``args`` because the ``args`` get passed to the range function in ``nquad``, even though the range functions are supposed to not have additional arguments (as per the documentation):
```
>>> from scipy.integrate import dblquad
>>> g= lambda x: x
>>> h= lambda x: 2 * x
>>> args = 1, 2
>>> func = lambda x0, x1, t0, t1: x0 + x1 + t0 + t1
>>> dblquad(func, 1, 2, g, h, args=args)
TypeError: <lambda>() takes exactly 1 argument (3 given)
```
This example works in ``0.16.0`` (the version I have installed) and I think the changes in #5906 are to blame.

I would suggest fixing this in a way that restores the old ``dblquad`` API. ``tplquad`` likely has the same issue, but I haven't checked.

**Comment by ev-br** [comment]
@woodscn: ping

**Comment by woodscn** [comment]
Thanks for the heads up. The API for dbl- and tpl-quad should have remained unchanged. I'll look into it.

**Comment by woodscn** [comment]
I have a fix. Does anyone have the output from the given problem, so I can set up a test?

**Comment by woodscn** [comment]
Eh, nevermind. Easy enough to come up with.

**Comment by ev-br** [comment]
```
In [2]: >>> from scipy.integrate import dblquad

In [3]: >>> g= lambda x: x

In [4]: >>> h= lambda x: 2 * x

In [5]: >>> args = 1, 2

In [6]: >>> func = lambda x0, x1, t0, t1: x0 + x1 + t0 + t1

In [7]: >>> dblquad(func, 1, 2, g, h, args=args)
Out[7]: (10.333333333333334, 1.1472304587793286e-13)

In [8]: import scipy

In [9]: scipy.__version__
Out[9]: '0.17.1'
```

**Comment by ev-br** [comment]
Fixed in gh-6492, closing.

**Comment by shantanu9847** [comment]
Hello,
I seem to have run into the same problem in 
 scipy.__version__ '0.18.0'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/scipy/integrate/quadpack.py", line 495, in dblquad
    return nquad(func, [lambda x: [gfun(x), hfun(x)], [a, b]], args=args)
  File "/usr/local/lib/python2.7/site-packages/scipy/integrate/quadpack.py", line 705, in nquad
    return _NQuad(func, ranges, opts, full_output).integrate(*args)
  File "/usr/local/lib/python2.7/site-packages/scipy/integrate/quadpack.py", line 760, in integrate
    **opt)
  File "/usr/local/lib/python2.7/site-packages/scipy/integrate/quadpack.py", line 315, in quad
    points)
  File "/usr/local/lib/python2.7/site-packages/scipy/integrate/quadpack.py", line 380, in _quad
    return _quadpack._qagse(func,a,b,args,full_output,epsabs,epsrel,limit)
  File "/usr/local/lib/python2.7/site-packages/scipy/integrate/quadpack.py", line 749, in integrate
    low, high = fn_range(*args)
TypeError: <lambda>() takes exactly 1 argument (3 given)

**Comment by rgommers** [comment]
@shantanu9847 upgrading to scipy 0.18.1 or 0.19.0 should fix your issue.
