### ISSUE TITLE
Memory leak in scipy.integrate.nquad when using ctypes

### ISSUE THREAD

**Issue by bsesar** [scipy/scipy#6468]
Hi all,

It seems nquad has a memory leak when integrating a function implemented using ctypes. Here is the code that can be used to replicate this issue:

Save this as testlib.c:

`//testlib.c`
`# include <math.h>`
`double f(int n, double args[n]){`
`    return pow(args[0], 2) - exp(args[1]) * args[2]; //corresponds to x0 - x1 * x2`
`}`

Compile the function:

`gcc -shared -o testlib.so -fPIC testlib.c`

Run this in Python:

`import ctypes`
`from scipy import integrate`

`lib = ctypes.CDLL('./testlib.so')`
`func = lib.f`
`func.restype = ctypes.c_double`
`func.argtypes = (ctypes.c_int, ctypes.c_double)`

`while True:`
`    integrate.nquad(func, [[0, 10], [-10, 0], [-1, 1]])`

and use "top" to watch how the memory usage grows.

Any chance for a quick fix?

Cheers,

Brani

**Comment by bsesar** [comment]
I apologize, this is the first time I'm submitting a bug through github. The above line should read
`#include <math.h>`

**Comment by pv** [comment]
I think this is a duplicate report of a known issue (please search the 
issues if there's a duplicate).

**Comment by bsesar** [comment]
Correct, this is a duplicate report. Sorry about that.
