### ISSUE TITLE
error message for stats.invwishart

### ISSUE THREAD

**Issue by idc9** [scipy/scipy#6471]
The scale argument to stats.invwishart must be positive definite (see documentation http://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.stats.invwishart.html). The error message, however, that is returned for a non-positive definite matrix could me more clear. 

When I run the following code 

```
df = 2
scale = [[1, 1], [0, -1]]
stats.invwishart.rvs(df=df, scale=scale)
```

I get the following error message

> LinAlgError: 2-th leading minor not positive definite

When I first encountered this error message it I was not entirely sure what the problem was. A better error message might read something like

> ValueError: Scale matrix must be positive definite

I'm using scipy version 0.17.0.

**Comment by ev-br** [comment]
It's probably easy enough to catch the a LinAlgError and reraise. Whether it's worth it, I don't know. Maybe consider adding a note to the docstring instead.
