### ISSUE TITLE
scipy.stats.invwishart does not check if scale matrix is symmetric 

### ISSUE THREAD

**Issue by idc9** [scipy/scipy#6472]
The scale matrix argument for scipy.stats.invwishart should be symmetric, but it does not currently throw an error or warning. See documentation http://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.stats.invwishart.html 

> the scale matrix, which must be symmetric

The following code runs fine but should throw an error

``` python
df = 2
scale = [[1, 1], [0, 1]]
stats.invwishart.rvs(df=df, scale=scale)
```

I'm using scipy version 0.17.0.

**Comment by ev-br** [comment]
I think we should loosely follow lapack and simply document which triangle is being ignored (upper or lower).  @ChadFulton?
