### ISSUE TITLE
SCIPY for WIN32 and Python 3.4 does not install

### ISSUE THREAD

**Issue by luhler** [scipy/scipy#6473]
I have  Python 3.4 installed. I am trying to install from the file: scipy-0.16.0-win32-superpack-python3.4.exe.

The install indicates there is no reference  to Python 3.4 in the Registry and I can go no further.

**Comment by pv** [comment]
You need the Python 3.4 from Python.org.

**Comment by rgommers** [comment]
Specifically, the 32-bit python.org installer. You probably have a 64-bit Python installed; we have no binaries for those.
