### ISSUE TITLE
Endless loop for a Golden Search algorithm

### ISSUE THREAD

**Issue by itdxer** [scipy/scipy#6476]
Hi,

Recently I started catching one issue with the Golden Search algorithm. The problem is that in some cases when I use Golden Search I catch an infinite loop. Here is a small program that reproduce this issue.

``` python
from scipy.optimize import golden
golden(lambda x: 0)
```

I've tried to debug the code and it looks like that x0, x1, x2 and x3 variables reaches certain computational limit (like `10 ** -314`) and they are not updating anymore. It could be solved if I set up `tol=1` (or even higher), but it doesn't look like a right way of doing it.

I've tried to set up `maxiter` option in the [minimize_scalar](http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.optimize.minimize_scalar.html#scipy.optimize.minimize_scalar) function, but it looks like it works only for the Brent algorithm. Actually, I don't even see `maxiter` in the `_minimize_scalar_golden` function.

I think there at least would be useful to add `maxiter` in the `_minimize_scalar_golden` function. In addition I think there might be useful to change the while loop condition from:

``` python
while (numpy.abs(x3 - x0) > tol * (numpy.abs(x1) + numpy.abs(x2))):
```

to

``` python
while numpy.abs(x2 - x1) > tol:
```

In the first case `tol` parameter is not really intuitive and it's not always converge. Seconds case is much more intuitive for me, because in that way it's clear that tolerance shows how close approximation should be to the real minimum. For instance, if I choose `tol` equal to `0.1` it means that I don't care too much about the accuracy and if the real minimum let say equal to `1.5` then I would be happy to have minimum approximation somewhere between `1.4` and `1.6`.

You might have a better idea that can help to fix this issue. I'll be happy to help you with this problem.

Looking forward to your reply.

**Comment by itdxer** [comment]
I'm using scipy==0.17.0, numpy==1.10.4 and Python 3.4.3

**Comment by ev-br** [comment]
I think adding `maxiter` to the loop would be a straightforward improvement.

**Comment by person142** [comment]
@itdxer: the parameter `xtol` is the allowed relative error (or claims to be, haven't checked), and this is a useful measure of convergence. But absolute error (i.e. the convergence criterion you proposed) is more useful in some situations, so some Scipy functions allow the use of a mixture of the two a la `numpy.allclose`. See for example

https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.brentq.html

or

https://github.com/scipy/scipy/pull/6449

Doing that here seems reasonable.

**Comment by itdxer** [comment]
Brent function tracks number of iterations that it takes to perform. I think it is useful to add the same functionality to golden search algorithm. The problem is that It's hard to track number of iterations with a for-loop. The for-loop with xrange iterator will increase number of iterations each time when the for-loop starts, but since we have if statement inside the loop it means that we don't know in advance if the loop step will be executed or not, because break statement can interrupt even though for-loop increased iterator.

```python
nit = 0  # in case if maxiter = 0
for i in xrange(maxiter):
    if some_condition:
        nit = i
        break
    # do something
    nit = i + 1
```

As you can see variable ``i`` cannot track both cases (when number of iterations equal 0 or 1). With a for-loop it's harder to track exact number of finished iterations since we need to track whether loop were finished or not.

I think that this solution should be simpler and easier to understand.

```python
nit = 0
while some_condition:
    if nit >= maxiter:
        break
    # do something
    nit += 1  # We increase number of iterations, because we finished iteration
```

**Comment by person142** [comment]
Why not just have `i` serve only as an index variable which is unrelated to `nit`?

i.e.
``` python
nit = 0
for i in xrange(maxiter):
    ...
    nit += 1
```

**Comment by itdxer** [comment]
That's a good idea. I didn't think about it.

**Comment by person142** [comment]
That `else` is silly though... (will give you the wrong count if `maxiter` is exceeded). Should have just set `nit = 0` at the start of the loop.

**Comment by itdxer** [comment]
I've added pull request to fix this issue. https://github.com/scipy/scipy/pull/6489

**Comment by aarchiba** [comment]
Completely aside from a maxiter argument, the algorithm should detect when the values are no longer changing and stop.

**Comment by aarchiba** [comment]
Endless loops can only happen if the new point equals the previous middle point, that is, if x1==x2 within the loop; if this occurs then an endless loop always follows. So the algorithm can safely check this condition and break.

**Comment by pv** [comment]
@aarchiba: are you sure an endless loop always follows? On each iteration, `x0` (or `x3`) is discarded and `x2` (or `x1`) interpolated between `x1,x3` (or `x2,x0`). So it seems to me the interval continues shrinking (on ~every second iteration), unless floating point rounding error occurs (as in this bug report).

**Comment by itdxer** [comment]
Are there any problems with final fix? I just what to know if there is something that I can do to close this issue.

**Comment by pv** [comment]
@itdxer: see the comments at gh-6489

**Comment by itdxer** [comment]
Pull request #6847
