### ISSUE TITLE
scipy compilation issues with openblas on mac os x

### ISSUE THREAD

**Issue by climberpi** [scipy/scipy#6486]
Hi guys. I try to compile numpy and scipy with OpenBLAS on Mac OS X, and I changed the site.cfg file. It works for numpy, but for scipy it doesn't work. Errors are as below. 

>     /usr/local/bin/gfortran -Wall -g -arch x86_64 -Wall -g -undefined dynamic_lookup -bundle build/temp.macosx-10.6-intel-3.5/scipy/integrate/_quadpackmodule.o -L/opt/OpenBLAS/lib -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin14/5.1.0 -Lbuild/temp.macosx-10.6-intel-3.5 -Wl,-rpath="/opt/OpenBLAS/lib" -lquadpack -lmach -lopenblas -lopenblas -lgfortran -o build/lib.macosx-10.6-intel-3.5/scipy/integrate/_quadpack.cpython-35m-darwin.so
    ld: unknown option: -rpath=/opt/OpenBLAS/lib
    collect2: error: ld returned 1 exit status
    ld: unknown option: -rpath=/opt/OpenBLAS/lib
    collect2: error: ld returned 1 exit status
    error: Command "/usr/local/bin/gfortran -Wall -g -arch x86_64 -Wall -g -undefined dynamic_lookup -bundle build/temp.macosx-10.6-intel-3.5/scipy/integrate/_quadpackmodule.o -L/opt/OpenBLAS/lib -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin14/5.1.0 -Lbuild/temp.macosx-10.6-intel-3.5 -Wl,-rpath="/opt/OpenBLAS/lib" -lquadpack -lmach -lopenblas -lopenblas -lgfortran -o build/lib.macosx-10.6-intel-3.5/scipy/integrate/_quadpack.cpython-35m-darwin.so" failed with exit status 1

It seems that this issue caused by the difference of rpath option between OS X and linux, but how to change something and make this thing work?
http://stackoverflow.com/questions/26472590/ld-unknown-option-rpath-libs-linking-error-while-building-openframework

**Comment by climberpi** [comment]
After I read site.cfg.example carefully, I figured out the problem. 

Scipy use the same tool of numpy for some external libraries, and generated instructions from installed numpy library, i.e. numpy/distutils/fcompiler/gnu.py or numpy/distutils/fcompiler/intel.py . It depends on whether you are using Intel mkl or not. 

And then, use "," instead of "=" after "rpath" in the file gnu.py as below: 
`    def runtime_library_dir_option(self, dir):
        return '-Wl,-rpath**=**"%s"' % dir`
Now: 
`    def runtime_library_dir_option(self, dir):
        return '-Wl,-rpath**,**"%s"' % dir`

Also we can use `pip3 show numpy` to get the location of numpy codes on local computer.

**Comment by rgommers** [comment]
@climberpi I'm not sure that I follow 100%, but if a specific example in ``site.cfg.example`` for OS X would have helped you here, we can add that. If so, can you propose a text?

**Comment by rgommers** [comment]
If you're debugging, never trust what a tool like ``pip`` tells you if you want to be sure:) Something like ``python -c "import numpy; print(numpy.__file__)"`` is more fool-proof.

**Comment by climberpi** [comment]
@rgommers Thanks for reply. Actually it is almost irrelevant with site.cfg, this issue just caused by the **rpath** option during the compiling process. For Linux, it should be **rpath=somepath**; and for OS X, it should be **rpath,somepath**, as [the StackOverflow question ](http://stackoverflow.com/questions/26472590/ld-unknown-option-rpath-libs-linking-error-while-building-openframework)I mentioned above. 
Numpy's distutils generate these things, and maybe you can add some codes in numpy/distutils/fcompiler/gnu.py, and make it generates these things depend on operating systems.
