### ISSUE TITLE
interp1d (kind=zero) returns wrong value for rightmost interpolation point

### ISSUE THREAD

**Issue by gablank** [scipy/scipy#6490]
```python
import scipy
from scipy.interpolate import interp1d

f1 = interp1d([0, 1],       [0.0, 1.0],           kind='zero')
f2 = interp1d([0, 1, 2],    [0.0, 1.0, 2.0],      kind='zero')
f3 = interp1d([0, 1, 2, 3], [0.0, 1.0, 2.0, 3.0], kind='zero')

print(f1([0, 1]))
print(f2([0, 1, 2]))
print(f3([0, 1, 2, 3]))

print(scipy.__version__)

# Output:
# [ 0.  0.]
# [ 0.  1.  1.]
# [ 0.  1.  2.  2.]
# 0.17.1

# Expected output:
# [ 0.  1.]
# [ 0.  1.  2.]
# [ 0.  1.  2.  3.]
# 0.17.1
```

**Comment by ev-br** [comment]
You can use `kind="nearest"` instead:

```
In [3]: interp1d([0, 1, 2], [0, 1, 2], kind='nearest')([0, 1, 2])
Out[3]: array([ 0.,  1.,  2.])
```

**Comment by gablank** [comment]
Thanks for the suggestion, but this is still a bug and therefore should be fixed. Or do you mean it's not a bug?

**Comment by ev-br** [comment]
It certainly is a bug, and apparently a known one even: https://github.com/scipy/scipy/blob/master/scipy/interpolate/tests/test_interpolate.py#L310

**Comment by andyfaff** [comment]
Is it worth putting a reference to the known bug in the interp1d code? I
wouldn't have thought to look for known bugs in the test suite.
Also, it's not clear to me the rationale for having a test with knownfail
instead of fixing the bug. Are knownfails supposed to be addressed in a
certain time frame?

**Comment by ev-br** [comment]
Fixing it would probably involve looking at splmake/spleval. Alternatively, this bug disappears if gh-3174 is merged, since the latter ditches both.

**Comment by ev-br** [comment]
Has been fixed in master:

```
>>> import scipy
>>> from scipy.interpolate import interp1d
>>> 
>>> f1 = interp1d([0, 1],       [0.0, 1.0],           kind='zero')
>>> f2 = interp1d([0, 1, 2],    [0.0, 1.0, 2.0],      kind='zero')
>>> f3 = interp1d([0, 1, 2, 3], [0.0, 1.0, 2.0, 3.0], kind='zero')
>>> 
>>> print(f1([0, 1]))
[ 0.  1.]
>>> print(f2([0, 1, 2]))
[ 0.  1.  2.]
>>> print(f3([0, 1, 2, 3]))
[ 0.  1.  2.  3.]
>>> 
>>> print(scipy.__version__)
0.19.0.dev0+c636ba3
```

Thanks for the report @gablank.
