### ISSUE TITLE
Segmenation fault in scipy 0.18.0 in ubuntu 16.10

### ISSUE THREAD

**Issue by anh-tong** [scipy/scipy#6496]
I recently upgrade my ubuntu and try to run scipy but it does not work. I try run the test of scipy

`/opt/anaconda/bin/python -c "import scipy; scipy.test('full',verbose=10)"`

Here is the output

`Running unit tests for scipy
NumPy version 1.11.1
NumPy relaxed strides checking option: False
NumPy is installed in /opt/anaconda/lib/python2.7/site-packages/numpy
SciPy version 0.18.0
SciPy is installed in /opt/anaconda/lib/python2.7/site-packages/scipy
Python version 2.7.12 |Anaconda 2.3.0 (64-bit)| (default, Jul  2 2016, 17:42:40) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
nose version 1.3.7
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
Segmentation fault (core dumped)
`

**Comment by matthew-brett** [comment]
Do you get the same behavior installing scipy via pip?  From source?

**Comment by anh-tong** [comment]
I installed scipy via pip. I tried previous versions and got the same output. Is there anyway to debug? I have no clue of what causes this.

**Comment by matthew-brett** [comment]
Could you try installing scipy using Debian Python rather than Anaconda?  I wonder whether it is an incompatibility between Anaconda and the stock scipy binary.

**Comment by anh-tong** [comment]
Scipy from Debian works. Thank you for your suggestion.

**Comment by matthew-brett** [comment]
I was hoping you might be able to test a pip install of scipy against Debian Python.  For example, this worked for me in an Ubuntu 16.10 Docker container:

```
apt-get update
apt-get install -y python wget
# Install pip into user account
wget https://bootstrap.pypa.io/get-pip.py
/usr/bin/python get-pip.py --user
# Put user account bin directory on PATH
export PATH=$HOME/.local/bin:$PATH
# Install and run tests
pip install numpy scipy nose
/usr/bin/python -c "import scipy; scipy.test('full')"
```

**Comment by anh-tong** [comment]
This works too when I uninstalled Debian scipy and installed it by pip..

**Comment by matthew-brett** [comment]
Great - thanks for testing.    Maybe this is a clash between scipy pip working with numpy or Python with Anaconda.  You might consider raising a issue over at https://github.com/ContinuumIO/anaconda-issues/issues to see whether they've got any ideas about what's going on.
