### ISSUE TITLE
DOC: comb and binom take complex numbers

### ISSUE THREAD

**Issue by endolith** [scipy/scipy#6501]
In https://github.com/scipy/scipy/pull/6020#issuecomment-204186578 it was said that factorial "shouldn't" accept floats, since that's what gamma is for, and the extension doesn't work for negative floats:

```
factorial(4.3)
Out[39]: array(38.07797644995235)
```

[is correct](http://www.wolframalpha.com/input/?t=ietb01&i=factorial%284.3%29)

```
factorial(-4.3)
Out[40]: array(0.0)
```

is [not correct](http://www.wolframalpha.com/input/?t=ietb01&i=factorial%28-4.3%29).  it should be 0.43851739219

https://en.wikipedia.org/wiki/Factorial#Extension_of_factorial_to_non-integer_values_of_argument

`comb()` and `binom()` also accept floats:

```
>>> comb(5.25, 3)
12.0859375
>>> binom(5.25, 3)
12.0859375
>>> (5.25 * 4.25 * 3.25)/(3*2)
12.0859375
```

http://www.wolframalpha.com/input/?i=comb(5.25,3) = 12.0859375

```
comb(6, 3.8)
Out[341]: 16.651879766686584

poch(6-2.8, 3.8)/factorial(3.8)
Out[340]: 16.651879766686587
```

www.wolframalpha.com/input/?i=comb(6,3.8) = 16.6519...

but they don't accept complex.

https://en.wikipedia.org/wiki/Binomial_coefficient#Generalization_and_connection_to_the_binomial_series

http://www.johndcook.com/blog/binomial_coefficients/

Should this be documented, or ignored like `factorial`?  `comb(N/2, N//2)` for odd `N` makes one of my formulas simpler, but docstring says int only.

**Comment by pv** [comment]
The zero return from `factorial` is defined in the docstring. Not sure why it's like this, but I would not change it any more. `comb` is similarly "integer-only" and has the weird edge cases --- the `exact=True` modes also seem to truncate arguments to integers.

`binom` on the hand has a proper complex analytic extension, so adding complex-valued support to is is possible. The problem here is in writing the algorithm for evaluating it in a stable way, which was not completely simple even on the real line.

**Comment by pv** [comment]
The simplest approach is probably to first write the evaluation algorithm for the complex beta function, and then use connection `binom(n, k) = 1/beta(1 + n - k, 1 + k)/(n + 1)`, and using taylor expansion for `|n|<<|k|`.

**Comment by liteanu** [comment]
comb gives a different answer when exact=True vs False when the arguments are non-int. Shouldn't comb consistently truncate or return 0 or give a warning if sent non-int args?

**Comment by h-vetinari** [comment]
> comb gives a different answer when exact=True vs False when the arguments are non-int. Shouldn't comb consistently truncate or return 0 or give a warning if sent non-int args?

This has been tackled by https://github.com/scipy/scipy/pull/15359.

Regarding the factorial functions, the questions of how to deal with the various extensions (e.g. `factorial(-4.3)`) is discussed more comprehensively in #15600, so closing this issue.
