### ISSUE TITLE
Computing Eigenvalues in an Interval with LAPACK

### ISSUE THREAD

**Issue by apapanico** [scipy/scipy#6502]
Hi,
In LAPACK, the routines `-evr` can be used to compute eigenvalues on an interval by specifying `range='V'` and then giving the upper and lower bounds `vl` and `vu`.  See for example: [LAPACK::dsyevr](http://www.netlib.org/lapack/lapack-3.1.1/html/dsyevr.f.html).

Since there is no high level function to do this (I wouldn't mind working on a contribution if need be), I started looking at the SciPy low level functions, in particular [SciPy::dsyevr](http://docs.scipy.org/doc/scipy-0.18.0/reference/generated/scipy.linalg.lapack.dsyevr.html#scipy.linalg.lapack.dsyevr).  Just to be complete, there were bugs with some of these eigenvalue routines but they appear to be fixed (see: #1686).

The signature for SciPy's `dsyevr` wrapper does not include `vl` and `vu` even though you can specify `range='V'`.  That's because [here](https://github.com/scipy/scipy/blob/maintenance/0.18.x/scipy/linalg/flapack.pyf.src#L2574), the F2Py wrapper for `dsyevr` has the two parameters `vl` and `vu` hidden and fixed rendering them unusable (I know little to nothing about Fortran and F2Py so I'm going off the note at the end of the section [The Smart Way](http://docs.scipy.org/doc/numpy-dev/f2py/getting-started.html#the-smart-way) in the f2py tutorial).  I traced the code to the commit c8ba75aa0af47aa01fe17d319048c43c80ca23b6 from 2008 written by @otizonaizit.

So I guess it boils down to, why is this feature suppressed and can/should it be brought back?  I am in the process of working on edits now but would appreciate feedback.

**Comment by apapanico** [comment]
I submitted a pull request that fixes this.  Some basic testing on a local build demonstrated it is operational:
```
>>> import numpy as np
>>> A = np.random.random((5,4))
>>> A = np.dot(A.T, A)
>>> u,s,v = np.linalg.svd(A)
>>> print(s)
[ 8.14912581  0.81319248  0.37577892  0.02414881]
>>> from scipy.linalg.lapack import dsyevr
>>> dsyevr(A, range='V', vl=.7, vu=.9)
(array([ 0.81319248,  0.        ,  0.        ,  0.        ]),
 array([[-0.18613659,  0.        ,  0.        ,  0.        ],
        [-0.50069785,  0.        ,  0.        ,  0.        ],
        [ 0.00689406,  0.        ,  0.        ,  0.        ],
        [ 0.84534449,  0.        ,  0.        ,  0.        ]]),
 0)
>>> print(dsyevr.__doc__)
w,z,info = dsyevr(a,[jobz,range,uplo,vl,vu,il,iu,lwork,overwrite_a])

Wrapper for ``dsyevr``.

Parameters
----------
a : input rank-2 array('d') with bounds (n,n)

Other Parameters
----------------
jobz : input string(len=1), optional
    Default: 'V'
range : input string(len=1), optional
    Default: 'A'
uplo : input string(len=1), optional
    Default: 'L'
overwrite_a : input int, optional
    Default: 0
vl : input float, optional
    Default: 0
vu : input float, optional
    Default: 1
il : input int, optional
    Default: 1
iu : input int, optional
    Default: n
lwork : input int, optional
    Default: 26*n

Returns
-------
w : rank-1 array('d') with bounds (n)
z : rank-2 array('d') with bounds (n,m)
info : int
```

**Comment by otizonaizit** [comment]
Hi, I am the author of the original wrappers for those LAPACK routines. If I remember correctly, the reason for hiding the eigenvalues in an interval option was simply that the original implementation of `scipy.linalg.eigh` did not even allow to limit the number of eigenvalues/eigenvectors returned. I needed only the possiblity to define the indices of the eigenvalues and not the range, and the result is the option `eigvals` to `scipy.linalg.eigh`. I think that your wrapper is too generic. You should not allow setting from Python the values of things like `lwork`: a wrong value there and the user can generate a segfault from Python, which is a no-no. 
So I think you could just "unhide" only the parameters you need, wrap additionaly the single-precision and the complex routines (`ssyevr` and `cheevr`), and improve the signature of `scipy.linalg.eigh`, so that an interval of eigenvalues can be specified. The exact signature I think is going to need a discussion on the mailing-list…

**Comment by apapanico** [comment]
Thanks @otizonaizit and @pv for the help.  

@otizonaizit: Thanks for the insight.  I just looked at `scipy.linalg.eigh`.  I had thought the `-evr` methods were not in use but I must have been thinking of something else.  Anyhow, here are my thoughts and please offer up any corrections:

### Some Background
Here is the original signature for ssyevr on [line 2534](https://github.com/scipy/scipy/blob/master/scipy/linalg/flapack.pyf.src#L2534) in `scipy/linalg/flapack.pyf.src`:
```
subroutine ssyevr(jobz,range,uplo,n,a,lda,vl,vu,il,iu,abstol,m,w,z,ldz,isuppz,work,lwork,iwork,liwork,info)
    ! Standard Eigenvalue Problem
    ! simple/expert driver: all eigenvectors or optionally selected eigenvalues
    ! algorithm: Relatively Robust Representation
    ! matrix storage
    ! Real - Single precision
    character intent(in) :: jobz='V'
    character intent(in) :: range='A'
    character intent(in) :: uplo='L'
    integer intent(hide) :: n=shape(a,0)
    real intent(in,copy,aligned8),dimension(n,n) :: a
    integer intent(hide),depend(n,a) :: lda=n
    real intent(hide) :: vl=0
    real intent(hide) :: vu=1
    integer optional,intent(in) :: il=1
    integer optional,intent(in),depend(n) :: iu=n
    real intent(hide) :: abstol=0.
    integer  intent(hide),depend(iu) :: m=iu-il+1
    real intent(out),dimension(n),depend(n) :: w
    real intent(out),dimension(n,m),depend(n,m) :: z
    integer intent(hide),check(shape(z,0)==ldz),depend(n,z) :: ldz=n
    integer intent(hide),dimension(2*m) :: isuppz
    integer intent(in),depend(n) :: lwork=26*n
    real  intent(hide),dimension(lwork) :: work
    integer intent(hide),depend(n):: liwork=10*n
    integer intent(hide),dimension(liwork) :: iwork
    integer  intent(out) :: info
end subroutine ssyevr
```

Obviously there is the part I am trying to fix:
```
    real intent(hide) :: vl=0
    real intent(hide) :: vu=1
```
But regarding `lwork`, it was already opened as an input.
```
    integer intent(in),depend(n) :: lwork=26*n
```
From the SSYEVR [documentation](http://www.netlib.org/lapack/lapack-3.1.1/html/ssyevr.f.html):
```
*  LWORK   (input) INTEGER
*          The dimension of the array WORK.  LWORK >= max(1,26*N).
*          For optimal efficiency, LWORK >= (NB+6)*N,
*          where NB is the max of the blocksize for SSYTRD and SORMTR
*          returned by ILAENV.
*
*          If LWORK = -1, then a workspace query is assumed; the routine
*          only calculates the optimal sizes of the WORK and IWORK
*          arrays, returns these values as the first entries of the WORK
*          and IWORK arrays, and no error message related to LWORK or
*          LIWORK is issued by XERBLA.
```
The usage of `LWORK=-1` is in fact referenced in the `scipy.linalg.eigh` definition on [line 377](https://github.com/apapanico/scipy/blob/6fe5a08c207e92551838868031a60fb4c38fbe60/scipy/linalg/decomp.py#L377):
```
    #  Use '*evr' routines
    # FIXME: implement calculation of optimal lwork
    #        for all lapack routines
```
Moreover, this approach of passing `lwork=-1` to create a safe and optimal call is actually utilized for the QR decompositions.  See [line 13](https://github.com/apapanico/scipy/blob/6fe5a08c207e92551838868031a60fb4c38fbe60/scipy/linalg/decomp_qr.py#L13)  in `scipy/linalg/decomp_qr.py`.

### Modifications
Okay, so that covers the background.  Here is the new signature I wrote.  This is the updated version in the PR which corrects the ordering and uses prefixes to handle single and double at the same time (there is a similar setup for the `-heevr` methods):

```
subroutine <prefix2>syevr(jobz,range,uplo,n,a,lda,il,iu,abstol,m,w,z,ldz,isuppz,work,lwork,iwork,liwork,info,vl,vu)
    ! Standard Eigenvalue Problem
    ! simple/expert driver: all eigenvectors or optionally selected eigenvalues
    ! algorithm: Relatively Robust Representation
    ! matrix storage
    ! Real - Single/Double precision

    fortranname <prefix2>syevr
    callstatement (*f2py_func)(jobz,range,uplo,&n,a,&lda,&vl,&vu,&il,&iu,&abstol,&m,w,z,&ldz,isuppz,work,&lwork,iwork,&liwork,&info)
    callprotoargument char*,char*,char*,int*,<ctype2>*,int*,<ctype2>*,<ctype2>*,int*,int*,<ctype2>*,int*,<ctype2>*,<ctype2>*,int*,int*,<ctype2>*,int*,int*,int*,int*

    character intent(in) :: jobz='V'
    character intent(in) :: range='A'
    character intent(in) :: uplo='L'
    integer intent(hide) :: n=shape(a,0)
    <ftype2> intent(in,copy,aligned8),dimension(n,n) :: a
    integer intent(hide),depend(n,a) :: lda=n
    <ftype2> optional,intent(in) :: vl=0
    <ftype2> optional,intent(in) :: vu=1
    integer optional,intent(in) :: il=1
    integer optional,intent(in),depend(n) :: iu=n
    <ftype2> intent(hide) :: abstol=0.
    integer  intent(hide),depend(iu) :: m=iu-il+1
    <ftype2> intent(out),dimension(n),depend(n) :: w
    <ftype2> intent(out),dimension(n,m),depend(n,m) :: z
    integer intent(hide),check(shape(z,0)==ldz),depend(n,z) :: ldz=n
    integer intent(hide),dimension(2*m) :: isuppz
    integer intent(in),depend(n) :: lwork=26*n
    <ftype2>  intent(hide),dimension(lwork) :: work
    integer intent(hide),depend(n):: liwork=10*n
    integer intent(hide),dimension(liwork) :: iwork
    integer  intent(out) :: info
end subroutine <prefix2>syevr
```
The key differences are:

1. Obviously `vl` and `vu` are added:
```
    <ftype2> optional,intent(in) :: vl=0
    <ftype2> optional,intent(in) :: vu=1
```
2. In the wrapper signature, `vl` and `vu` are appended to the END of the signature
3. `fortranname`, `callstatement`, and `callprotoargument` are used to call the wrapped routine with the arguments in the order as LAPACK specifies.  

Here is the new signature of the Python function with proper ordering except for the parameter `overwrite_a`.  I don't know what to do about that because it's not part of the wrapper routine or wrapped routine signature and nothing in the LAPACK documentation mentions overwrite.
```
>>> print(ssyevr.__doc__)
w,z,info = ssyevr(a,[jobz,range,uplo,il,iu,lwork,vl,vu,overwrite_a])

Wrapper for ``ssyevr``.

Parameters
----------
a : input rank-2 array('f') with bounds (n,n)

Other Parameters
----------------
jobz : input string(len=1), optional
    Default: 'V'
range : input string(len=1), optional
    Default: 'A'
uplo : input string(len=1), optional
    Default: 'L'
overwrite_a : input int, optional
    Default: 0
il : input int, optional
    Default: 1
iu : input int, optional
    Default: n
lwork : input int, optional
    Default: 26*n
vl : input float, optional
    Default: 0
vu : input float, optional
    Default: 1

Returns
-------
w : rank-1 array('f') with bounds (n)
z : rank-2 array('f') with bounds (n,m)
info : int
```

### Final Thoughts
1. The definition for `lwork` should be improved using `check(lwork==-1 || lwork >=26*n)`
2. `safe_call` from `scipy/linalg/decomp_qr.py` could be provided more generally. 
3. `scipy.linalg.eigh` could eventually incorporate this new wrapper.  I'm just trying to get the low-level wrapper running.
4. I don't know what can be done about the parameter `overwrite_a` still being at the end.  I see SciPy typically uses keyword arguments for these functions but obviously that's not 100% reliable.  Before I could get the signature working to reorder the arguments, I tried creating a new low-level function `-evr_vrng` that wrapped `-evr` but was specifically designed to handle the value range use case.  That might be the way to go to avoid breaking the signature on `-evr`.

**Comment by pv** [comment]
The blas/lapack wrappers are intended to be very low-level, and I think it's OK to allow segfaulting parameter combinations. Indeed, it is well possible to write segfaulting code currently using several of the wrappers.

For the special case of lwork: instead of using it for the lwork=-1 query mode, it's best to write a separate entry point (see the *_lwork functions there) --- this avoids needless copying and/or allocation of arrays.

**Comment by pv** [comment]
To reorder the overwrite_a flag, you'd need to write a small wrapper function in Python, and monkeypatch it at import time, e.g. `_flapack.dsyevr = my_dsyevr` like assignments in `__init__.py` or some other suitable place. (This way it is could also be possible to avoid the callstatement reordering.)

**Comment by apapanico** [comment]
Oo, I like both those ideas.  Thanks.  That would also help fix this bug:

```
>>> ssyevr(A, range='A', il=1, iu=2)
Out[4]: 
(array([ 0.04227656,  0.21443589,  0.73784077,  7.0965848 ], dtype=float32),
 array([[-0.36748636, -0.25646007],
        [ 0.68119341, -0.47197112],
        [-0.6013037 , -0.10166021],
        [ 0.19840148,  0.83733898]], dtype=float32),
 0)
```
All eigenvalues/vectors are desired but the LAPACK routine is truncating the eigenvectors while not truncating the eigenvalues.  These values should be ignored according to the documentation:
```
*  IL      (input) INTEGER
*  IU      (input) INTEGER
*          If RANGE='I', the indices (in ascending order) of the
*          smallest and largest eigenvalues to be returned.
*          1 <= IL <= IU <= N, if N > 0; IL = 1 and IU = 0 if N = 0.
*          Not referenced if RANGE = 'A' or 'V'.
```
