### ISSUE TITLE
Wrong error message for ttest_ind

### ISSUE THREAD

**Issue by nazgul17** [scipy/scipy#6512]
When calling scipy.stats.ttest_ind, if nan_policy is not 'propagate', 'raise' or 'omit', a ValueError is raised with the following message: nan_policy must be either 'propagate', 'raise', or 'ignore'

The message should say 'omit' instead of 'ignore'.

Lines 242-244, inside method _contains_nan, of scipy/stats/stats.py are guilty:
```
    if nan_policy not in ('propagate', 'raise', 'omit'):
        raise ValueError("nan_policy must be either 'propagate', 'raise', or "
                         "'ignore'")
```

**Comment by WarrenWeckesser** [comment]
Thanks for reporting the issue.  This was fixed back in February (https://github.com/scipy/scipy/commit/2b074a95d8a54f43e3c682d743345e486204117e), and the fixed code is in release 0.18.0.
