### ISSUE TITLE
Bug in scipy.stats.relfreq and scipy.stats.cumfreq

### ISSUE THREAD

**Issue by KeyWeeUsr** [scipy/scipy#6513]
``` python
rel = scipy.stats.relfreq([0,0,0,0,1], numbins=2)
nrel = scipy.stats.relfreq([0,0,5,0,1], numbins=3)
rel[0], nrel[0]
(array([ 0.8,  0.2]), array([ 0.8,  0. ,  0.2]))

c = scipy.stats.cumfreq([0,0,0,0,1], numbins=2)
nc = scipy.stats.cumfreq([0,0,5,0,1], numbins=3)
c[0], nc[0]
(array([ 4.,  5.]), array([ 4.,  4.,  5.]))

```

As you can see, if I increase `numbins`, nothing changes and it should. If I increase it to `numbins=4`, the result is this for `relfreq` and similar for `cumfreq`:

``` python
array([ 0.6,  0.2,  0. ,  0.2])
```

I work with `scipy (0.18.0)` and `numpy (1.11.1+mkl)`

**Comment by WarrenWeckesser** [comment]
You have to look at the actual bins used by `relfreq` and `cumfreq`.  Consider your `relfreq` examples:

```
In [33]: relfreq([0,0,0,0,1], numbins=2)
Out[33]: RelfreqResult(frequency=array([ 0.8,  0.2]), lowerlimit=-0.5, binsize=1.0, extrapoints=0)
```

The edges of the bins are [-0.5, 0.5, 1.5].  The four 0s fall in the first bin, and the value 1 falls in the second bin.  That gives the result `[0.8, 0.2]`.

```
In [34]: relfreq([0,0,5,0,1], numbins=3)
Out[34]: RelfreqResult(frequency=array([ 0.8,  0. ,  0.2]), lowerlimit=-1.25, binsize=2.5, extrapoints=0)
```

In this case, the edges of the bins are [-1.25, 1.25, 3.75, 6.25].  So the three 0s and 1 fall in the first bin, and the value 5 falls in the last bin.  That matches the actual output, `[0.8, 0.0, 0.2]`.

You can override the upper and lower limits of the bin edges with the argument `defaultreallimits`.

I'm closing the issue, but please comment if you still think something is wrong.

**Comment by KeyWeeUsr** [comment]
Probably I misunderstood how these functions work. I was expecting `numbins` behave like a count of unique values in the input array. After I read your reply, do I think correctly that to achieve [this](https://en.wikipedia.org/wiki/Frequency_(statistics)#Types_of_frequency) behavior I need to set `numbins = len(<array>) + 1` to get `binsize == 1.0`? Then the `0.0` values in `frequency` array represent the count of values from this array - `[0, 1, 2, 3, ...]`, right?

**Comment by WarrenWeckesser** [comment]
For an input `a` that is all integers, to get the relative frequency of the occurrences of the integers in {0, 1, ..., a.max()}, you could use `relfreq(a, defaultreallimits=(0, a.max()+1), numbins=a.max()+1)`.

```
In [55]: a = np.array([0, 0, 0, 0, 1])

In [56]: relfreq(a, defaultreallimits=(0, a.max()+1), numbins=a.max()+1)
Out[56]: RelfreqResult(frequency=array([ 0.8,  0.2]), lowerlimit=0, binsize=1.0, extrapoints=0)

In [57]: a = np.array([0, 0, 5, 0, 1])

In [58]: relfreq(a, defaultreallimits=(0, a.max()+1), numbins=a.max()+1)
Out[58]: RelfreqResult(frequency=array([ 0.6,  0.2,  0. ,  0. ,  0. ,  0.2]), lowerlimit=0, binsize=1.0, extrapoints=0)
```

But for that case, I think it would be simpler to use `numpy.bincount` (http://docs.scipy.org/doc/numpy/reference/generated/numpy.bincount.html):

```
In [64]: a = np.array([0, 0, 0, 0, 1])

In [65]: np.bincount(a)/float(len(a))
Out[65]: array([ 0.8,  0.2])

In [66]: a = np.array([0, 0, 5, 0, 1])

In [67]: np.bincount(a)/float(len(a))
Out[67]: array([ 0.6,  0.2,  0. ,  0. ,  0. ,  0.2])
```
