### ISSUE TITLE
use pip install scipy, but not find savgol_filter 

### ISSUE THREAD

**Issue by shiweihappy** [scipy/scipy#6516]
use pip install scipy, but not find savgol_filter, my scipy version is 0.18.

`from scipy.signal import savgol_filter`

error is : savgol_filter is not find

**Comment by matthew-brett** [comment]
Works for me on OSX and Linux - what platform are you on?  How did you install your Python?

**Comment by shiweihappy** [comment]
@matthew-brett 

system: OS X EI Capitan 10.11.6
python version: Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
python use system default

scipy install :  `pip install scipy`
scipy version:   scipy (0.18.0)

**Comment by matthew-brett** [comment]
Aha - yes - I think you'll find that the system default Python ignored your pip install of scipy - see : https://github.com/MacPython/wiki/wiki/Which-Python#why-you-should-not-use-system-python-for-osx

I recommend you use homebrew Python instead, or Python.org Python.

**Comment by shiweihappy** [comment]
@matthew-brett , thank you very much,  i will try it.

**Comment by person142** [comment]
@shiweihappy I wonder if @matthew-brett's advice fixed your problem?
