### ISSUE TITLE
DOC: release: No link to 0.18.0 release notes

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#6518]
I just noticed that at http://docs.scipy.org/doc/scipy/reference/release.html, there is no link to the 0.18.0 release notes.

**Comment by ev-br** [comment]
cross-ref https://github.com/scipy/docs.scipy.org/pull/6#issuecomment-237297984

**Comment by pv** [comment]
Fixed manually and in gh-6455

**Comment by WarrenWeckesser** [comment]
Thanks!
