### ISSUE TITLE
scipy.stats.entropy does *not* calculate the KL divergence

### ISSUE THREAD

**Issue by djstrouse** [scipy/scipy#6521]
As stated in the documentation for scipy.stats.entropy, the KL divergence is S = sum(pk * log(pk / qk), axis=0). However, by calling scipy.special.kl_div, there are extra linear terms in there (pk - qk) that should not be there. The fix is easy: replace the call to scipy.special.kl_div with scipy.special.rel_entr.

**Comment by mirca** [comment]
It turns out that ``entropy`` results do not change either using ``scipy.special.kl_div`` or ``scipy.special.rel_entr`` in because the ``- x + y`` part in ``kl_div`` sums to ``0``.

However, it should matter in performance, so I'm opening a PR to fix this.

**Comment by ev-br** [comment]
Could you check that it actually matters performance-wise? Both kl_div and rel_entr are ufuncs, so it's likely washed out by the python overhead.
