### ISSUE TITLE
documentation: scipy.stats.mode

### ISSUE THREAD

**Issue by zieglerk** [scipy/scipy#6526]
In the docstring for `scipy.stats.mode` the sentence that describes the behavior for multi-modal arrays is not consistent with the code. 

The docstring states:

> If there is more than one such value, only the first is returned.

While the code returns the *smallest* of several such values. In the case of the examples:

```
>>> a = np.array([[6, 8, 3, 0],
...               [3, 2, 1, 7],
...               [8, 1, 8, 4],
...               [5, 3, 0, 5],
...               [4, 7, 5, 9]])
>>> from scipy import stats
>>> stats.mode(a)
(array([[3, 1, 0, 0]]), array([[1, 1, 1, 1]]))
```

Here, not the first modal value (6) is returned, but the smallest (3).

I suggest to replace `first` by `smallest` in the docstring.

**Comment by rgommers** [comment]
fixed in gh-6592. thanks for the report @zieglerk
