### ISSUE TITLE
Can't install scipy package!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [scipy/scipy#6529]
I'm pretty new to python. Not coding, just python and it's whole package management. So I have no idea what's going on or what I'm doing wrong.

For the life of me, I can't install scipy: https://gist.github.com/anonymous/7544a47921f1437a045bdaa83aa84302

**Comment by pv** [comment]
Please read the instructions: http://scipy.org/install.html
For user support, you can ask on stackoverflow.com.
