### ISSUE TITLE
scipy.stats.invgauss lower bound and entropy

### ISSUE THREAD

**Issue by gbellesia** [scipy/scipy#6531]
I noticed that the lower bound scipy.stats.invgauss.a is set to zero by default.
However the inverse gaussian distribution is defined for x>0 to infinity. Not sure if this can be critical or not.

Also, scipy.stats.ingauss.entropy(p1,p2,p3), where for example p1,p2,p3 are generated from scipy.stats.fit(dataset), gives sometimes negative values. Examples of such parameter sets [p1,p2,p3] are:
[12.4752405097, 0.00554333304921, 0.0531686967492] ==> entropy = -0.208085178894
[10.7519430285 0.00540568945651 0.063028093063] ==> entropy = -0.0995204250864

To double check I performed a fit on the same ensemble of datasets using "expon" and always get the right entropy (I am comparing with the analytical formula for the exponential distribution: 1+ln(scale))

Thank you

**Comment by ev-br** [comment]
invgauss seems to be OK at x=0:

```
In [19]: invgauss.pdf([-1e-2, 0, 1e-2], mu=1)
Out[19]: array([  0.00000000e+00,   0.00000000e+00,   2.08117682e-19])
```

For the entropy, please clarify what is the issue. Ideally, please add a small example which we can run.

**Comment by gbellesia** [comment]
if you look at the formula:

`invgauss.pdf(x, mu) = 1 / sqrt(2*pi*x**3) * exp(-(x-mu)**2/(2*x*mu**2))`

for `x-->0` the limit goes as `x^(-3/2)*exp(-x)`.

This limit does not exist as far as I can tell (left and right limits are different). That's where my concern comes from. If the scipy invgauss implementation is well defined for x=0 it means that something in the same implementation modifies the inverse gaussian and makes it well defined for x=0.

Regarding the negative entropy, I am attaching a few lines of code that I am running on jupyter notebook:

`import numpy as np`
`import scipy.stats as st`
`import matplotlib.pyplot as pt`
`%matplotlib inline`
`x = np.linspace(0,30,100000)`

`pdf_fitted_ig = st.invgauss.pdf(x,12.4752405097, 0.00554333304921, 0.0531686967492)`

These fitted parameters come from a dataset. The nature of the dataset is not really relevant here.

`plt.axis((0,0.1,0,10))`
`plt.plot(x,pdf_fitted_ig)`

As you can see the function looks fine.
Here I am printing the entropy for the inverse gaussian with the problematic parameter set

`print st.invgauss.entropy(12.4752405097, 0.00554333304921, 0.0531686967492)`

and the entropy for an exponential fit of the same dataset plus the analytical result 
for the entropy of an exponential distribution with the fitted scale

`st.expon.entropy(0.00629406167874,0.662525071614),1.0+np.log(0.662525071614)`

I hope this clarifies, thanks.

**Comment by WarrenWeckesser** [comment]
> if you look at the formula:
>
> invgauss.pdf(x, mu) = 1 / sqrt(2*pi*x**3) * exp(-(x-mu)**2/(2*x*mu**2))
>
> for x-->0 the limit goes as x^(-3/2)*exp(-x).

The shape parameter `mu` is assumed to be greater than 0, so as `x` goes to 0, the limit goes as `x^(-3/2)*exp(-1/(2*x))`.  The exponential term crushes that puny negative power like a bug, and the limit is 0.

**Comment by WarrenWeckesser** [comment]
The `entropy()` method computes the *differential entropy* (https://en.wikipedia.org/wiki/Differential_entropy).  The differential entropy of a distribution can be negative.  As an example, the wikipedia article notes that the differential entropy of the uniform distribution on [0, 1/2] is -log(2).  Here's that calculation in scipy:

```
In [56]: from scipy.stats import uniform

In [57]: uniform.entropy(0, 0.5)
Out[57]: array(-0.6931471805599453)
```

I'm closing the issue, but feel free to continue the discussion or even reopen the issue if you still think something is wrong.

**Comment by gbellesia** [comment]
Thank you for your time Warren. I apologize as I didn't realize it was the differential entropy that was calculated. What you say makes sense.

However,  just for the sake of discussion, I don't see how the fact that mu>0 affects the limit since the numerator of the exponential is always negative for x>0.
Since you mentioned wikipedia (https://en.wikipedia.org/wiki/Inverse_Gaussian_distribution) you will see that in the definition of the inverse gaussian all the parameters are defined as > 0 and so is x.

Also, I just checked some of the historical papers on the inverse gaussian (Mathematical Biosciences, 3, 191-204 (1968) and references therein) In those papers you may find definitions that explicitly set its value to zero outside of the "domain" defined by lambda,mu,x > 0. So I guess that, at the end of the day, it's fine to make it zero when x=0 :)

**Comment by WarrenWeckesser** [comment]
> However, just for the sake of discussion, I don't see how the fact that mu>0 affects the limit since the numerator of the exponential is always negative for x>0.

The expression in the exponent is `-(x - mu)**2 / (2*mu**2*x)`.  As x goes to 0, the numerator goes to `-mu**2`, which cancels the `mu**2` in the denominator, so overall the expression in the exponent acts like `-1/(2*x)`.

In hindsight, it probably wasn't necessary to state that `mu > 0`, when all I really cared about was `mu != 0`, and it is probably obvious that `mu` cannot be 0.  If `mu == 0`, the whole expression is not well defined.

**Comment by WarrenWeckesser** [comment]
> In those papers you may find definitions that explicitly set its value to zero outside of the "domain" defined by lambda,mu,x > 0

Ah.  I took it to be understood that that was the case.  All the distributions follow that convention.  The "support" is the part of the domain where the PDF is positive; see https://en.wikipedia.org/wiki/Support_(mathematics).  Outside of the support, the PDF is, by definition, 0.

**Comment by bellesig** [comment]
yes, you're right about the limit ... my mistake. thanx
