### ISSUE TITLE
Scipy Sparse (csr) Matrix Indexing obtains AttributeError: format not found

### ISSUE THREAD

**Issue by yszorro** [scipy/scipy#6533]
**I got a scipy.sparse.csr.csr_matrix and want to select part of the rows with boolean index. However, I got the AttributeError. Could anyone please help on this? I am using anaconda 4.1.1**

**When I executed the following codes:**

print type(xtr)
print type(idxtmp)  
print xtr[0,:]
print idxtmp[0:5]
xtr = xtr[idxtmp] 

**I got the following results and error:**

\<class 'scipy.sparse.csr.csr_matrix'\>
\<type 'numpy.ndarray'\>
  (0, 0)	0.0
  (0, 1)	0.0
  (0, 2)	899.0
  (0, 3)	3315.0
  (0, 4)	942.0
[ True  True  True  True  True]

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
\<ipython-input-25-d8ad445241ff\> in \<module\>()
      3 print xtr[0,0:5]
      4 print idxtmp[0:5]
----> 5 xtr = xtr[[0,1],:]

/usr/local/anaconda2/lib/python2.7/site-packages/scipy/sparse/csr.pyc in __getitem__(self, key)
    296             if isintlike(col) or isinstance(col,slice):
    297                 P = extractor(row, self.shape[0])     # [[1,2],j] or [[1,2],1:2]
--> 298                 extracted = P * self
    299                 if col == slice(None, None, None):
    300                     return extracted

/usr/local/anaconda2/lib/python2.7/site-packages/scipy/sparse/base.pyc in __mul__(self, other)
    317             if self.shape[1] != other.shape[0]:
    318                 raise ValueError('dimension mismatch')
--> 319             return self._mul_sparse_matrix(other)
    320 
    321         try:

/usr/local/anaconda2/lib/python2.7/site-packages/scipy/sparse/compressed.pyc in _mul_sparse_matrix(self, other)
    476 
    477         major_axis = self._swap((M,N))[0]
--> 478         other = self.__class__(other)  # convert to this format
    479 
    480         idx_dtype = get_index_dtype((self.indptr, self.indices,

/usr/local/anaconda2/lib/python2.7/site-packages/scipy/sparse/compressed.pyc in __init__(self, arg1, shape, dtype, copy)
     26 
     27         if isspmatrix(arg1):
---> 28             if arg1.format == self.format and copy:
     29                 arg1 = arg1.copy()
     30             else:

/usr/local/anaconda2/lib/python2.7/site-packages/scipy/sparse/base.pyc in __getattr__(self, attr)
    523             return self.getnnz()
    524         else:
--> 525             raise AttributeError(attr + " not found")
    526 
    527     def transpose(self):

AttributeError: format not found

**Even when I tried xtr = xtr[[0,1],:], I got the same error...**

**Comment by perimosocordiae** [comment]
I can't reproduce this error locally. Try upgrading your installed version of scipy.

**Comment by yszorro** [comment]
Hi perimosocordiae,

    I upgraded the scipy to the latest version but got a new error (attached). Is there any other way to fix it? Thanks.
![2016-09-02 13 10 59](https://cloud.githubusercontent.com/assets/21538638/18199745/54421652-7134-11e6-9ffe-9088a7c75a91.png)

**Comment by perimosocordiae** [comment]
The `SystemError` indicates that this may be a problem with your Python interpreter, not Scipy. If you're still stuck, try asking on StackOverflow.

**Comment by pv** [comment]
Also that the line numbers don't match to the code shown indicates that something is wrong with the scipy installation.

**Comment by robertlayton** [comment]
I had a very similar problem, and this was the only reasonable link on Google, so I'll put my fix here. Basically, if you have this problem, you may be trying to load sparse matrices created in a previous version of scipy. My version numbers were "created with 0.18" and "trying to load with 0.19". Downgrading to 0.18 fixed the issue.

**Comment by perimosocordiae** [comment]
@robertlayton loading what, from where?

**Comment by robertlayton** [comment]
Private project unfortunately so I can't share code or files, but it was a sparse matrix from scikit-learn. Our servers are 0.18, but auto-updating had some dev machines on 0.19.

**Comment by perimosocordiae** [comment]
Ah, if it was saved using scikit-learn it was probably pickled, which unfortunately isn't the most stable way to store objects. Nothing fundamental changed for sparse matrix formats in 0.19, though, so I'm curious what caused the failure to de-serialize.

**Comment by randomtutu** [comment]
i uesed to meet the same bug when i load the data ,created in ubantu, in windows.
i fix this problem by create the same data in the windows and reload it in windows
