### ISSUE TITLE
loggamma ignores the sign of zero

### ISSUE THREAD

**Issue by stevengj** [scipy/scipy#6536]
In scipy 0.18.0, I noticed that `loggamma` ignores the sign of zero in the imaginary part when choosing the branch cut, which seems wrong:
```
>>> scipy.special.loggamma(-3.4 + 0.0j)
(-1.1211918156538432-12.566370614359172j)
>>> scipy.special.loggamma(complex(-3.4, -0.0))
(-1.1211918156538432-12.566370614359172j)
>>> scipy.special.loggamma(-3.4 - 1e-16j)
(-1.1211918156538432+12.566370614359172j)
```
I believe the imaginary part in the second return value should be positive.   Otherwise you violate the identity `loggamma(z) = conj(loggamma(conj(z)))`.

(I noticed this when I was implementing a new `lgamma` function for Julia, validating against the one in SciPy and the one in Mathematica, and I was checking corner cases of the branch cuts: JuliaLang/julia#18330.)

**Comment by person142** [comment]
I recall that I was trying to be consistent with mpmath:
```python
>>> mpmath.loggamma(-3.4 + 0j)
mpc(real='-1.1211918156538383', imag='-12.566370614359172')
>>> mpmath.loggamma(-3.4 - 0j)
mpc(real='-1.1211918156538383', imag='-12.566370614359172')
```
and also with how numpy handles the branch cut in log:
```python
>>> np.log(-1 + 0j)
3.1415926535897931j
>>> np.log(-1 - 0j)
3.1415926535897931j
```
though I do recall finding it weird that these functions behaved in this way. (Presumably numpy is copying C, which also doesn't distinguish between negative zero and zero in `clog`.)

**Comment by stevengj** [comment]
@person142, unfortunately in Python `-3.4 - 0j` does *not* produce a `-0.0` imaginary part.  You have to do `complex(-3.4,-0.0)`.   And numpy *does* handle the branch cut in the log correctly:
```
>>> numpy.log(complex(-1,+0.0))
3.1415926535897931j
>>> numpy.log(complex(-1,-0.0))
-3.1415926535897931j
```

**Comment by stevengj** [comment]
I just checked, and `clog` (at least on my machine) also *does* correctly distinguish ±0.0 in the imaginary part for the branch cut.

**Comment by person142** [comment]
I just screwed it up then. :-)

**Comment by pv** [comment]
The big picture is following C99 standard that IIRC respects sign of zero vs branch cuts.

**Comment by stevengj** [comment]
It's more of an IEEE thing than C99 per se, and pre-dates C99 by quite a bit.  See ["Branch Cuts for Complex Elementary Functions, or Much Ado About Nothing's Sign Bit"](https://people.freebsd.org/~das/kahan86branch.pdf) in *The State of the Art in Numerical Analysis*, (eds. Iserles and Powell), 1987.
