### ISSUE TITLE
Two versions of Chebyshev polynomials

### ISSUE THREAD

**Issue by person142** [scipy/scipy#6539]
In `special` there is `chebyt`:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.chebyt.html#scipy.special.chebyt

and `chebyc`:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.chebyc.html#scipy.special.chebyc

both of which compute Chebyshev polynomials of the first kind; the only difference is that `chebyt` returns polynomials on the interval `[-1, 1]` and `chebyc` on the interval `[-2, 2]`. They have both been there for a long time (https://github.com/scipy/scipy/commit/ab1d4868ec3c2c885419d86d928a696cfb3fadb3). There is a similar story with `chebyu` and `chebys`. AFAICT `chebyt`/`chebyu` are the more common parameterizations (I can't find any references to their alternatives); does anyone know why the other forms exist? Should they be deprecated?

**Edit**: if something is done about https://github.com/scipy/scipy/issues/1777 then we would get arbitrary intervals.

**Comment by ewmoore** [comment]
The reference is Abramowitz and Stegun. I think if we were starting from
scratch I'd agree with you but given that they've been there for so long,
and the need to deprecate them, I think we should leave them alone. The
hassle for us and anyone using them is worth the tiny gain we would get.

**Comment by person142** [comment]
Hm, I should have looked in A&S. They don't appear to have kept up the notation in the DLMF, or at least I don't see them here: http://dlmf.nist.gov/18.3.

Thanks for the reference, closing since I mostly just wanted to know the history.
