### ISSUE TITLE
Test runner does not run scipy._lib/tests?

### ISSUE THREAD

**Issue by pv** [scipy/scipy#6541]
Running `python runtests.py` does not appear to run tests under `scipy._lib`.
However, `python runtests.py -s _lib` does run them.

This probably has to do with nose & submodule having underscore prefix.

**Comment by pv** [comment]
I don't remember an easy fix however. Easiest would be to move the `tests` directory elsewhere...

**Comment by pv** [comment]
The problem is a hardcoded check for the underscore prefix: https://github.com/nose-devs/nose/blob/master/nose/loader.py#L169 There's a comment in the nose code saying it's "going to be removed", but that comment has been there since 2008, unlikely to be fixed :(

**Comment by ev-br** [comment]
https://github.com/scipy/scipy/pull/5556, esp https://github.com/scipy/scipy/pull/5556#issuecomment-161049212

**Comment by pv** [comment]
Workaround in gh-6544 --- doing the same is in principle possible but somewhat clumsier in submodules (the extra paths need to be added both in `scipy.test` and `scipy.submodule.test`.)
