### ISSUE TITLE
medfilt2d throwing error on valid input

### ISSUE THREAD

**Issue by chrisspen** [scipy/scipy#6542]
The [docs](http://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.medfilt2d.html#scipy.signal.medfilt2d) for medfilt2d claim the filter accepts a "A 2-dimensional input array", but this is not the case:

    >>> from scipy.signal import medfilt2d
    >>> from numpy import array, int32
    >>> a = array([[1,40,1],[2,80,2]], np.int32)
    >>> medfilt2d(a)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/project/.env/local/lib/python2.7/site-packages/scipy/signal/signaltools.py", line 842, in medfilt2d
        return sigtools._medfilt2d(image, kernel_size)
    ValueError: 2D median filter only supports Int8, Float32, and Float64.

Why is this error thrown? My array is 2 dimensional, and the type is one of those listed as acceptable.

**Comment by WarrenWeckesser** [comment]
> ... the type is one of those listed as acceptable.

Your array has type `int32`.  The types listed as acceptable as `int8`, `float32` and `float64`.  (I don't know why the error message capitalizes those type names.)

**Comment by WarrenWeckesser** [comment]
However, if you change the data type of your array to `int8`, you get the same error message, so something is definitely wrong:

```
In [9]: a = array([[1,40,1],[2,80,2]], np.int8)

In [10]: medfilt2d(a)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-38125d9c044b> in <module>()
----> 1 medfilt2d(a)

/Users/warren/miniconda3scipy/lib/python3.5/site-packages/scipy-0.19.0.dev0+1cd4ab9-py3.5-macosx-10.6-x86_64.egg/scipy/signal/signaltools.py in medfilt2d(input, kernel_size)
   1173             raise ValueError("Each element of kernel_size should be odd.")
   1174 
-> 1175     return sigtools._medfilt2d(image, kernel_size)
   1176 
   1177 

ValueError: 2D median filter only supports Int8, Float32, and Float64.
```

**Comment by WarrenWeckesser** [comment]
It accepts an array of *unsigned* 8 bit integers:

```
In [34]: a = array([[1,40,1],[2,80,2]], np.uint8)

In [35]: medfilt2d(a)
Out[35]: 
array([[0, 1, 0],
       [0, 1, 0]], dtype=uint8)
```

So it looks like, at a minimum, the error message should be fixed, and the acceptable types should be noted in the docstring.

**Comment by chrisspen** [comment]
Yep, oversight on my part. Sorry.

**Comment by WarrenWeckesser** [comment]
> Yep, oversight on my part.

Despite the oversight, there is in fact a problem.  Type `int8` is  not accepted, but `uint8` is.  See my previous comment.

**Comment by sriki18** [comment]
I can fix the documentation to make it say `2D median filter only supports uint8, float32, and float64.` and also . I might also be able to fix it to accept `int8`, but I'm not familiar with how some of the logistics work out. I should perhaps write a unit test to begin with. Can I build only a portion of the library instead of the whole thing, to save time?

**Comment by WarrenWeckesser** [comment]
The "easy fix" is to fix the documentation.  That would be fine.  Modifying the code to accept another data type *might* be easy, or it could turn out to be much more involved than you initially expect.  If you are interested, you could first create a pull request to fix the documentation to reflect the current behavior.  Then look into enhancing the function to accept `int8` (or even other data types).

>  Can I build only a portion of the library instead of the whole thing, to save time? 

I'm not sure.  It would be nice, but I haven't tried it.  Does anyone else out there know if this is possible?

**Comment by person142** [comment]
Typically running the submodule-level `setup.py` files works fine, though maybe there's a better way to do it.

**Comment by pv** [comment]
Note that when rebuilding, it only rebuilds changed parts --- so 
compiling whole Scipy takes a long time only the first time.

**Comment by sriki18** [comment]
Thank you all for the help. I was editing a C file and this required a rebuild. (When modifying Python files, I already used the in-place build as explained in `HACKING.rst.txt`. So any changes are directly reflected without the need to rebuild). Indeed, only the changed parts are rebuilt. 

I'm submitting a PR at the moment for the documentation fix. If I am able to make the function accept other data arguments, I will send another PR.

**Comment by person142** [comment]
The documentation is fixed in gh-6598. Closing since extending to more dtypes seems like a different issue.
