### ISSUE TITLE
How do I call basinhopping in scipy.stats.t.fit()?

### ISSUE THREAD

**Issue by amirsani** [scipy/scipy#6547]
I would like to call basinhopping as the optimizer for scipy.stats.rv_continuous.fit. How do I do this?

Here is some example code:
from scipy import stats,optimize
import numpy as np
np.random.seed(0)
x = [ stats.t.rvs(9) for i in range(250)]
shape, location, scale = stats.t.fit(x)
print "Shape:" + str(shape)

Thank you,

Amir

**Comment by pv** [comment]
Help for usage questions is available on stackoverflow.com, this issue 
tracker is intended for reporting bugs.

**Comment by amirsani** [comment]
Thanks
