### ISSUE TITLE
Homebrew can install most of the SciPy stack

### ISSUE THREAD

**Issue by toastedcornflakes** [scipy/scipy#6558]
It is stated in the [documentation](https://scipy.org/install.html#homebrew) that homebrew can't install the whole SciPy stack.

However, after tapping the correct repository (`brew tap homebrew/python`), the base packages are available for installation with

    brew install python numpy scipy matplotlib

Is this install sufficient to be in the docs, or are the missing packages (ipython, pandas, sympy, nose) compulsory? If I remember correctly, those don't require binary packages and can be obtained from pip.

Thank you.

**Comment by matthew-brett** [comment]
Thanks for pointing that out.   I believe it is also possible to install the entire scipy stack with pip on OSX and Linux now, so that should also go in the doc.

**Comment by matthew-brett** [comment]
Consider reviewing https://github.com/scipy/scipy.org/pull/178?

**Comment by rgommers** [comment]
PR merged, so closing. Thanks @toastedcornflakes @matthew-brett
