### ISSUE TITLE
scipy.signal.find_peaks_cwt() claims to argument as sequence, but requires it to be array

### ISSUE THREAD

**Issue by ddasilva** [scipy/scipy#6560]
Docs say `widths` can be a sequence:
http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.signal.find_peaks_cwt.html

But the code generates an exception if you pass a list. Comes from `signal/_peak_finding.py` line 510 where an array operation is used before it is converted to an array:
https://github.com/scipy/scipy/blob/master/scipy/signal/_peak_finding.py#L510

Anyway, should be as simple as putting `widths = np.asarray(widths)` at the head of the method.

**Comment by ddasilva** [comment]
While I'm at it, would a patch be welcome to make this function return an array instead of a list? Ran into the unpleasant/confusing `TypeError: only integer arrays with one element can be converted to an index` when trying to use it's return value as an array.

**Comment by rgommers** [comment]
Hi @ddasilva, thanks for reporting that. And yes, a patch for both issues would be very welcome.

I see also that the ``Returns`` section of the docstring is missing.

When you change the list to array, a note in the docstring and in the backwards incompatible changes section of ``doc/release/0.19.0-notes.rst`` will be needed.

**Comment by ddasilva** [comment]
Thanks @rgommers. I opened PR #6561 and all checks have passed.
