### ISSUE TITLE
Coverage of spectral functions could be improved

### ISSUE THREAD

**Issue by jmacfarlane** [scipy/scipy#6565]
Several spectral analysis functions (`periodogram`, `welch`, `csd`, etc.) produce incorrect results when the parameter `scaling` is set to `'spectrum'`.

The following modified version of the current test case should work:
```Python
import numpy as np
from scipy.signal import welch

x = np.zeros(16)
x[0] = 1
x[8] = 1
fs = 16.0
f, p = welch(x, fs=fs, nperseg=8, scaling='spectrum')
g, q = welch(x, fs=fs, nperseg=8, scaling='density')
assert np.allclose(p, q*fs)
```

The issue looks like a simple typo in the scaling factor.

**Comment by jmacfarlane** [comment]
PR #6565 is a proposed fix

**Comment by e-q** [comment]
The power spectrum and power spectral density are not generically related
just by the sampling frequency, so the test case you propose isn't the
right criteria. The actual relationship depends on the equivalent noise
bandwidth of the windowing, which is only really equal to the sampling rate
for a rectangular window.

As a test, try calculating the power spectrum of a noiseless sinusoid that
falls exactly on an FFT bin with different window functions, in both the
master branch and your PR. You'll find in your branch that the peak height
depends on the windowing, which is not correct behavior.

However, this does bring a gap in test coverage to light, which I'll fix as
soon as I can.

**Comment by jmacfarlane** [comment]
I apologize.  I was looking at the code and the term `win.sum()**2` in the spectrum scaling factor didn't seem meaningful to me and seemed like it was meant to be the power of the window `(win*win).sum()`.  It's clear that my test case above and proposed fix are quite wrong.  I should have investigated further before assuming the current code was wrong.  I appreciate you being so polite about it.

**Comment by Eric89GXL** [comment]
That's alright @jmacfarlane, thanks for looking into the code, and don't hesitate to bring up (or fix) any other issues you see. 

I'll re-title the issue so that @e-q has a friendly reminder about coverage

**Comment by jmacfarlane** [comment]
The above test is incorrect, but perhaps we can change some of the parameters used for the tests for added coverage.  Especially using a non-default window in `TestPeriodogram.test_real_spectrum`.

**Comment by jmacfarlane** [comment]
Though, it can be argued that this isn't necessary because the welch and csd tests technically cover the same code.

**Comment by rgommers** [comment]
Looks like this is completely addressed (please reopen if I missed something) by gh-6664, so closing. Thanks @jmacfarlane @e-q
