### ISSUE TITLE
add a show_methods helper to scipy.optimize to list available methods

### ISSUE THREAD

**Issue by inoryy** [scipy/scipy#6568]
Currently there's no clean way to tell which methods are available. A simple solution would be to implement a `show_methods` helper function that returns a list of currently available optimization methods.

Use case: providing a wrapper over `scipy.optimize.minimize` with support for multiple scipy versions.

**Comment by pv** [comment]
help(scipy.optimize) and help(scipy.optimize.minimize) probably contain
this info

12.9.2016 8.20 "Roman Ring" <notifications@github.com> kirjoitti:

**Comment by Inoryy** [comment]
Sorry, I meant an API helper, so the returned data would be a python list.

**Comment by pv** [comment]
Sounds reasonable. This could also be just a global variable, 
MINIMIZE_METHODS = (...) or so.

**Comment by sethtroisi** [comment]
`dir(scipy.optimize)` will give you a python list (it will be strings)

**Comment by mdhaber** [comment]
@inoryy it's been a while, but if you're still interested, the path forward would be to send an email to the scipydev mailing list: https://svn.scipy.org/scipylib/mailing-lists.html. if response is positive, this would be easy enough to do.

**Comment by mdhaber** [comment]
Closing because this needs a mailing list post to happen, but feel free to reopen when it does.
