### ISSUE TITLE
wrong eigenvalues when using eigh

### ISSUE THREAD

**Issue by florian98765** [scipy/scipy#6573]
hello, 

i am writing a code to calculate eigenvalues for a large operator (created by coupled FEM and BEM matrices). For testing reasons I setup the full dense matrix and tried to compare the iterative eigensolvers with the direct ones. 

interestingly, the results of ```eigh``` differs significantly from the results of the other three tested methods (```eig```, ```eigs```, ```eigsh```). Maybe the matrix is not perfectly hermitian, but then it should also influence the sparse hermitian solver, right? 

Here is the test code that is used: 
```python
import numpy as np
from scipy.linalg import eig, eigh
from scipy.sparse.linalg import eigs, eigsh

M = 1j*np.loadtxt('matrix.txt')

evals, evecs = eigs(M, k=10, which='SM', tol=1e-2)
print "eigs: ", evals[0].real
evals, evecs = eigsh(M, k=10, which='SM', tol=1e-2)
print "eigsh:", evals[0].real
evals, evecs = eig(M)
print "eig:  ", np.min(np.abs(evals))
evals, evecs = eigh(M)
print "eigh: ", np.min(np.abs(evals))
```

which leads to the following results:
```
eigs:  49322207530.8
eigsh: 49322207814.7
eig:   49322207864.7
eigh:  12476547368.3
```

The used matrix can be found here:
[matrix.txt](https://github.com/scipy/scipy/files/469917/matrix.txt)

greetings
FloB

**Comment by pv** [comment]
eigh requires hermitian matrix. Your matrix is not hermitian.

**Comment by WarrenWeckesser** [comment]
> Maybe the matrix is not perfectly hermitian...

Not "maybe".  The matrix is definitely not hermitian, not even close.

**Comment by WarrenWeckesser** [comment]
> ...but then it should also influence the sparse hermitian solver, right? 

The real parts of the eigenvalues returned by `scipy.sparse.linalg.eigs` and `scipy.sparse.linalg.eigsh` are the same, but that might be an accident that depends on how the algorithm in `scipy.sparse.linalg.eigsh` handles a non-hermitian matrix.  The imaginary parts of the actual eigenvalues have nontrivial imaginary parts:

```
In [106]: import scipy.sparse.linalg as ssla

In [107]: ssla.eigs(m, k=10, which='SM', tol=1e-2)[0]
Out[107]: 
array([ -4.93222067e+10 +2.22816114e+06j,
        -8.64560126e+10 -1.13290734e+08j,
        -9.37157639e+10 +7.58266103e+07j,
        -1.20548525e+11 -3.38778196e+07j,
        -1.82062488e+11 -8.70686752e+07j,
         4.93222065e+10 +2.22551091e+06j,
         8.64556754e+10 -1.13424909e+08j,
         9.37159001e+10 +7.53959287e+07j,
         1.20548473e+11 -3.39701467e+07j,   1.82077795e+11 -1.22887426e+08j])

In [108]: ssla.eigsh(m, k=10, which='SM', tol=1e-2)[0]
Out[108]: 
array([  4.93222081e+10,   1.20548547e+11,   9.37158481e+10,
         8.64560303e+10,   1.82057094e+11,  -4.93222081e+10,
        -8.64560266e+10,  -9.37158532e+10,  -1.20548548e+11,
        -1.82076780e+11])
```

I'm closing the issue.  If you are going to use `eigh` or `eigsh`, be sure your input is hermitian.
