### ISSUE TITLE
scipy.linalg.inv does not complete. cpu hog

### ISSUE THREAD

**Issue by bpinsard** [scipy/scipy#6574]
I have an algorithm that makes heavy use of scipy.linalg.inv (Kalmann filtering).
Once in a while, the inversion takes infinite time (the size is not the matter here) and takes a stable amount of CPU.
As I have to kill python to stop it, I have been saving the matrix (numpy format) before every call to inv(), so as when it crashes I can reload it to do more tests.
When I reload this matrix, and call inv, it does not reproduce the bug, I also ran 1000 iterations of inv on it, no bug. So this is not matrix peculiarity problem.
I know that it is more an issue related to BLAS library (or the wrapping in scipy), but I wonder if you had an idea. It might be specific to my environment, if you need any further information on version/BLAS/OS... tell me.
I also switched to numpy.linalg.inv which, if I am right, does not uses the same BLAS function, and the bug doesn't occur, but it is slightly slower, as documented elsewhere.

Thanks

**Comment by ilayn** [comment]
Are you using `check_finite=False` at any place? Let me reemphasize, never ever use inv unless you really need to see it (especially in Kalman filtering if you are inverting R). 

For backslash operator of matlab `A\B` use `np.linalg.solve(A,B)` for square systems and `np.linalg.leastsq` for rectangular cases. 

For forward slash operator `A/B`, it is the annoying `np.linalg.solve(B.T,A.T).T`

**Comment by bpinsard** [comment]
No, I am not disabling the sanity check.
To solve my problem, I moved to Anaconda which uses MKL, also provides better performances.
I am just suprised that nobody had the same problem.

I will look in the other way to compute you mention, thanks.

**Comment by pv** [comment]
Closing, I think there's not much we can do to address bugs in LAPACK/BLAS implementations.
