### ISSUE TITLE
Behavior of stats.ks_2samp for ties needs investigating

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#6575]
From gh-6545, which reverted gh-5938:
- gh-5938 changed ks_2samp for scipy 0.18.0,
- the change was supposed to be a moderate speed up only, but it changed the behavior in case of ties in the data
- both "old" (0.17.0) and "new" (0.18.0) behavior is somewhat ad hoc, and the "new" is not clearly better than the "old"

The correct behavior for ties needs to be figured out. There's relevant discussion on gh-6435. 

Once the behavior for ties is resolved, the Cython implementation of `ks_2samp` that was removed in gh-6545 may be useful again.

**Comment by pvanmulbregt** [comment]
What is the open action here?  AFAICT, the current implementation 

https://github.com/scipy/scipy/blob/affd5d62ff9a6746f80513e778c69c7642f0187b/scipy/stats/stats.py#L4884-L4887

using a difference of two `np.searchsorted(, , side='right')` calls handles ties correctly. Or are there simple counter-examples?

**Comment by mdhaber** [comment]
For the examples I've tried, the statistic calculation matches that of R's `ks.test`, but the p-value (neither exact nor asymptotic) does not. 

R's `ks.test` warns "cannot compute exact p-value with ties".
```R
x <- c(1, 1.01, 3, 4)
y <- c(1.01, 0.5, 0.25)  # try 1.02 instead of 1.01
ks.test(x, y)
```

SciPy p-value agrees with R's p-value when the first entry of `y` is 1.02. When the first entry of `y` is changed to 1.01 (tie), the statistic doesn't change in either software, but the p-value changes in R (and only R). 

So it seems that there is a tie correction to the asymptotic p-value calculation that SciPy does not have.

**Comment by mdhaber** [comment]
I investigated again. I think there were two parts here:

1. Do the right thing when there are ties.
2. Possibly use code from gh-6545 in the future.

Regarding 1, `ks_2samp` is pretty explicit about being for samples from continuous distributions, so ties are out of the current scope. In any case, our statistic calculation seems to agree with R's `ks.test`, so short of fulfilling gh-14434 (KS test for discrete distributions), I think this is resolved.

Regarding 2, *if* we wanted to compile the code for a modest speed increase, I think we'd use Pythran now. That said, I would probably be -0.5 even on that - the performance increase seems modest at best, but it does make the function a little harder to work with. Moreover, translating to array API Python calls would be more valuable, and that is tracked in gh-20544.

So I think it's safe to close this one and leave gh-14434 and gh-20544 open.
