### ISSUE TITLE
Cannot import scipy.interpolate into matlab

### ISSUE THREAD

**Issue by jackStalnaker** [scipy/scipy#6580]
As noted [here](http://www.mathworks.com/help/matlab/matlab_external/limitations-to-python-support.html), Matlab's Python support fails when attributes begin with an underscore. Attempting to import scipy.interpolate fails under matlab when attempting to import fitpack.py, which contains a number of names beginning with underscores.

Steps to reproduce:
In matlab:
py.importlib.import_module('scipy.interpolate.fitpack')

produces the message:
Error using interpolate><module> (line 21)
Python Error: ImportError: cannot import name fitpack

Error in __init__><module> (line 158)
from .interpolate import *

Error in __init__>import_module (line 37)
    __import__(name)

Versions:
Python 2.7
Matlab 2015b

**Comment by pv** [comment]
Please report bugs in Matlab Python support to Matlab.

**Comment by pv** [comment]
(1) It not clear that it is actually due to the underscores.
(2) We will not change the policy due to a bug in Matlab's Python 
implementation.

**Comment by pv** [comment]
In particular, the page you link appears to talk about what is supported 
in some Python interface wrapper in Matlab, not about what is permitted 
in source files. The more likely reason for import failure is 
incompatibility in the compiled modules. That is an user support 
question, and best asked on stackoverflow.com

**Comment by Eric89GXL** [comment]
Even if it is the underscores, I suspect that there are a lot of bits of code that would have to change to be non-underscore-start compliant.

**Comment by pv** [comment]
Yes, but if it fails due to underscores, then Matlab's "Python support" 
does not actually support the Python language but some strange subset 
only --- which I find hard to believe.

**Comment by zym1010** [comment]
@jackStalnaker  while this is off topic, I think the Python API for MATLAB is probably more complete than MATLAB API for Python. If you don't have strong language preference, maybe you can switch around.

**Comment by person142** [comment]
I think we're safe to close this--apologies to @jackStalnaker but:

- As @pv pointed out it's probably not the underscores, and in that case there's not much we can do (don't see how we would debug a closed-source application).
- If it is the underscores, then (also as @pv pointed out) Matlab has a problem. In python underscores are commonly accepted to mean that an attribute is private*,  so there's a whole lot of python code out there that wouldn't work. It doesn't make sense to move away from established python conventions to adopt Matlab python conventions.

*see e.g. https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles
