### ISSUE TITLE
Doc - structured array - introduction

### ISSUE THREAD

**Issue by Francois888** [scipy/scipy#6584]
on page : http://docs.scipy.org/doc/numpy-1.10.1/user/basics.rec.html
Structured array - Introduction
In the example : "Conveniently, one can access any field of the array by indexing using the string that names that field."
>>> y = x['foo'] should be >>> y = x['bar'] (the actual name of the "second" field which is addressed along the example.
Additionally, this has to be updated at several places on the page.

**Comment by person142** [comment]
Hey @Francois888, it looks like you have the wrong bug tracker--this should be reported to numpy:

https://github.com/numpy/numpy
