### ISSUE TITLE
improve the documentation of orthogonal polynomials

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#6586]
gh-6540 improved the documentation of orthogonal polynomials. As a follow-up, we should
- [ ] update `eval_*` docstrings
- [ ] cross-link functions returning `orthopoly1d` objects, and their corresponding `eval_*` and `*_roots`.
- [ ] document the `orthopoly1d` object itself and add clear usage guidelines (e.g. which operations
    convert to power basis)
- [ ] clarify the relation to newer `numpy.polynomial`s

Alternatively, maybe we want to even deprecate `np.poly1d`-based polynomials in favor of `np.polynomial`s.

**Comment by person142** [comment]
> Alternatively, maybe we want to even deprecate np.poly1d-based polynomials in favor of np.polynomials

Big +1 from me. If we do this then we should also extend the `*_eval` and `*_roots` functions so that they support arbitrary intervals and link that up with the `window` attribute of `Polynomial`

**Comment by pv** [comment]
The poly1d-based orthopoly could be removed, it's dangerous for naive users and not useful for people who know about it...

**Comment by person142** [comment]
> not useful for people who know about it...

That's a good point. I might like removing `orthopoly1d` and replacing it with nothing over replacing it with something based on `np.polynomial`.

**Comment by person142** [comment]
At this point I think I'm at "orthopoly1d is beyond saving and we shouldn't put any more work into it", so I think I'm going to close this. (I think the update the `eval_*` docstrings part has been done in various pieces, culminating with the recent special docs improvments.)
