### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by pylang** [scipy/scipy#6602]
https://docs.scipy.org/doc/scipy/reference/tutorial/integrate.html

An example in the docs for `scipy.integrate.quad` is 

![image](https://cloud.githubusercontent.com/assets/10778668/18704219/16fffb7e-7fb7-11e6-931e-295b580cb649.png)

However, the `integrand` function is written:

![image](https://cloud.githubusercontent.com/assets/10778668/18704258/3c324f3c-7fb7-11e6-98f0-ba04a690dc16.png)

where `x` appears to be missing a square, i.e. we expect `return (a * x**2) + b` .  Either the latex should be written to reflect the code, or vice versa.

Many thanks.

**Comment by andyfaff** [comment]
Thanks for reporting this. The code for this is [here](https://github.com/scipy/scipy/blob/master/doc/source/tutorial/integrate.rst). This should be an easy fix and I'd encourage you to submit a PR, it's a great way to further your involvement in scipy. You can find details on how to get at start at https://docs.scipy.org/doc/scipy/reference/hacking.html
