### ISSUE TITLE
Incorrect docs for comparator argument of argrelextrema

### ISSUE THREAD

**Issue by jbradt** [scipy/scipy#6604]
In the [documentation for `scipy.signal.argrelextrema`](http://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.argrelextrema.html), the `comparator` argument is described as follows:

> comparator : _callable_
> Function to use to compare two data points. **Should take 2 numbers as arguments.**
> [Emphasis added]

In reality, the comparator function must take two arrays, and not two numbers. The documentation should probably reflect this.

**Comment by rgommers** [comment]
Thanks for the report @jbradt. Should be fixed by gh-6608.
