### ISSUE TITLE
Link to source code of examples of interpolate.griddata is broken

### ISSUE THREAD

**Issue by fepegar** [scipy/scipy#6614]
In the documentation of [interpolate.griddata](http://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.griddata.html) there is a [broken link to the source code](http://docs.scipy.org/doc/scipy/reference/generated/scipy-interpolate-griddata-1.py) of the examples.

**Comment by person142** [comment]
This is essentially the same issue as https://github.com/scipy/scipy/issues/3250--note that to get the source code you can click the `<<<` button in the upper right corner of the example and then copy-paste.

**Comment by pv** [comment]
Closing as duplicate.
