### ISSUE TITLE
splrep and splprep inconsistent

### ISSUE THREAD

**Issue by ChristophKirst** [scipy/scipy#6618]
The tck objects returned from splprep and splrep are inconsistent in the c part,
splrep returns a c array with k+1 zeros at the end while splprep does not
see simple sample code here:

```
import numpy as np
from scipy.interpolate import splprep, splev, splrep

s = np.linspace(0,1,50) \* 2 \* np.pi;
xy = np.vstack([np.sin(s), np.cos(s)]).T;
xy.shape

tck,u = splprep(xy.T, s= 0)

x = xy[:,0];
tck1d = splrep(u, x, s = 0);
xs = splev(u, tck1d)

tck[0]
tck1d[0]

tck[1][0].shape
tck1d[1].shape
```

potential fix: 
splrep uses dfitpack.curfit / dfitpack.percur
while splprep uses _fitpack._parcur

**Comment by pv** [comment]
Does this cause a problem? Changing the behavior is strictly speaking a backward compatibility break. The extra zero padding is iirc not necessary, as it is just for convenience in making the coefficient array the same size as knots.

**Comment by ChristophKirst** [comment]
Its inconsistent and causes a problem when you have a multi-dim spline and simply want to change some of the spline parameter corresponding to a single dimension or for example
want to combine several 1d splines to a multi dim spline etc...

While the knot and c array in the splrep are consistent as you say, for the splprep this
is not the case in the present version.
 
Its not a problem per se as one can of course remove the zero padding. But it then should be at least clearly documented to avoid people digging into the scipy code to figure out whats going wrong.
Its interesting that splev does not seem to have a problem with the difference c array sizes.

I cannot judge comp-ability issues, but would be nice to have something consistent.

**Comment by ChristophKirst** [comment]
ps: anaother inconsistency is the default mode evaluation of the smoothig parameter:

while in the splrep without weights and s=None 
s=0 is used
while for the same setting in splprep 
s=... > 0 is used 

leading again to inconsistent outputs for 'the same inputs' to both routines...

Again a minor issues but you might want to document or change this ...

**Comment by ev-br** [comment]
FWIW, I'd suggest just documenting it and accepting that `splprep` is an odd one out.  

Ideally, cross-link to `BSpline` which does does not require zero-padding:
http://scipy.github.io/devdocs/generated/scipy.interpolate.BSpline.html#scipy.interpolate.BSpline

**Comment by ev-br** [comment]
Am tentatively labelling it as an easy-fix for the documentation.

**Comment by ashwinpathak20** [comment]
I would like to work on it, I need to change the documentation of splprep right?
