### ISSUE TITLE
API discussion: Riccati, Lyapunov and Sylvester solver function names 

### ISSUE THREAD

**Issue by ilayn** [scipy/scipy#6622]
Now that the solver is more general. I would like to draw the core team's attention to the API : 

Currently, the solvers are named as 

```
sp.linalg.solve_continuous_are
sp.linalg.solve_discrete_are

sp.linalg.solve_lyapunov
sp.linalg.solve_discrete_lyapunov

sp.linalg.solve_sylvester
```

I think this naming is not very consistent for a few reasons. 
1. If continuous/discrete is adopted then lyapunov is missing a `continuous` version. 
2. If function name is first on the continuous then are shouldn't have `continuous`. 
3. Continuous/discrete are not adjectives of the equation but the origin of these equations. Hence the name actually comes from continuous/discrete-time algebraic Riccati/Lyapunov Equations. 
4. If the matlab legacy is sought after then they should have been `care` and `dare`  however that is a historical artifact of 8.3 file naming standard back in the day. So they are not so obvious to the users coming from matlab. If we don't care about matlab legacy (which is the camp I'm in) then we don't need to make this distinction at all since there is not much logic in matlab's distinction other than outdated convenience. 
5. If there will be a Cholesky based solution (when the constant term is a product (`Q = B.T @ B` and so on) then the names would be a mess just as matlab has now with `care, dare, lyap,dlyap, lyapchol`. For example, robust control people also introduced the following commands `ric,dric, aresolv,ric_eig,ric_schr` all related to Riccati solutions and it is a total mayhem of horrible names. 

As an example, my suggestion would be combining at least the Lyapunov and Riccati solvers into two function calls which bifurcate internally with a `form` or `type` keyword:  

```
sp.linalg.solve_lyapunov(...., form='c')
sp.linalg.solve_riccati(...,form='d')
```

so an additional keyword. But of course it's just a suggestion. I'm not sure if it is a good idea to add yet another keyword. For me verbosity is something good but I know many people don't feel like it. 

I don't have much experience about the SciPy API. Note that, the discrete time Sylvester is missing. Mostly because in matlab the Sylvester solvers are embedded in `lyap` and `dlyap` solver APIs and very recently separated (2014a) as an additional function and again only the continuous part. 

I would like to update the `solve_continuous_are`, `solve_lyapunov` and CAREX tests but I'd like to get your opinion about it first before getting on with them.

**Comment by rgommers** [comment]
> 1. If continuous/discrete is adopted then lyapunov is missing a continuous version.
2. If function name is first on the continuous then are shouldn't have continuous. 

Yeah, that's an inconsistency - an oversight when we added these functions 4 years ago.

> 4. If the matlab legacy is sought after then they should have been care and dare however that is a historical artifact of 8.3 file naming standard back in the day. So they are not so obvious to the users coming from matlab. If we don't care about matlab legacy (which is the camp I'm in) then we don't need to make this distinction at all since there is not much logic in matlab's distinction other than outdated convenience. 

We don't care about Matlab names much. It's useful to indicate if a SciPy function is equivalent to a Matlab one with a different name (in the Notes section for example), but we prefer clear names rather than all the nondescriptive 4-6 letter names Matlab uses.

>     ``sp.linalg.solve_lyapunov(...., form='c')``
    ``sp.linalg.solve_riccati(...,form='d')``
so an additional keyword. But of course it's just a suggestion. I'm not sure if it is a good idea to add yet another keyword. 

The discrete and continuous versions of ``*_lyapunov`` and ``*_riccati`` have no code in common. So at this point I'm not sure that we gain much by adding a ``form='c'`` keyword.

> Note that, the discrete time Sylvester is missing.

That can be added I'd say if there is interest (as ``solve_discrete_sylvester`` most likely).

I would either go for a simple way to make things consistent, changing as little as possible, or leave things as is. For example, introduce:

    linalg.solve_continuous_lyapunov
    linalg.solve_continuous_sylvester

and leave ``linalg.solve_lyapunov`` and ``linalg.solve_sylvester`` as aliases that are not mentioned in the refguide.

**Comment by ilayn** [comment]
> and leave linalg.solve_lyapunov and linalg.solve_sylvester as aliases that are not mentioned in the refguide.

Indeed, that's a sensible way to do it. I don't actually have any preference as long as it is consistent. You guys have way more experience with user opinions and behavior so I'll just wait for more people chime in. 

I would appreciate if anyone let me know the location for the alias definitions for the future

**Comment by person142** [comment]
+1 to @rgommers suggestion.

> I would appreciate if anyone let me know the location for the alias definitions for the future

I might be misunderstanding the question, but you'd put the alias in the same file that the original function was defined in, e.g. stick `solve_lyapunov = solve_continuous_lyapunov` in there.

**Comment by ilayn** [comment]
So shall I assume this is issue is resolved then ? @pv ? Or others that I'm not aware of ?

**Comment by pv** [comment]
Sounds good to me to use the exact field-specific names. I've seen 
variants of AX+/-BX=C being called just "sylvester equation", but that 
may be just "corruption" of the main definition.

**Comment by ilayn** [comment]
@pv Probably you have the second syntax of [`dlyap`](nl.mathworks.com/help/control/ref/dlyap.html) and [`lyap`](nl.mathworks.com/help/control/ref/lyap.html) 

By the way, do I need to add the aliases into the `__[all]__`?

**Comment by person142** [comment]
> By the way, do I need to add the aliases into the `__all__()`?

Yes-otherwise the `from _solvers import *` in `__init__.py` won't pick them up.
