### ISSUE TITLE
incorrect handling of nan by RegularGridInterpolator

### ISSUE THREAD

**Issue by ghost** [scipy/scipy#6624]
RegularGridInterpolator does not seem to handle nans correctly when the interpolation method is nearest-neighbor. Sample script follows below.

--Bram
### 

import numpy as np
from scipy.interpolate import RegularGridInterpolator

f = RegularGridInterpolator(([1,2,3],), [10,20,30], bounds_error=False, fill_value=-999, method='linear')

print f([1]), f([0]), f([np.nan])
'# [ 10.] [-999.] [ nan]: correct handling'

f = RegularGridInterpolator(([1,2,3],), [10,20,30], bounds_error=False, fill_value=-999, method='nearest')

print f([1]), f([0]), f([np.nan])
'# [ 10.] [-999.] [ 30.] --> last value should be nan I guess...'

**Comment by ev-br** [comment]
Indeed `f(nan)` should be `nan`. The offender is

```
In [2]: np.searchsorted([1, 2, 3, 4], np.nan)
Out[2]: 4
```

I'll send a fix shortly.
