### ISSUE TITLE
Incorrect parameter name in binomial documentation 

### ISSUE THREAD

**Issue by svendx4f** [scipy/scipy#6628]
The [scipy binomial distribution](http://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.binom.html#scipy.stats.binom) documents that the random variable argument for most function is `x` 

e.g.: 
> pmf(x, n, p, loc=0)	Probability mass function.

Whereas a quick test validates that the real name is `k`: 

```
In [1]: from scipy import stats

In [2]: stats.binom.pmf(x=4, n=10, p=.3)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-f50f8123c586> in <module>()
----> 1 stats.binom.pmf(x=4, n=10, p=.3)

TypeError: pmf() takes at least 2 arguments (1 given)

In [3]: stats.binom.pmf(k=4, n=10, p=.3)
Out[3]: 0.20012094900000013
```

I'm not familiar with the way the documentation is generated for scipy, though I am guess this is just a matter of renaming `x` into `k` in the `binom_gen` function, [here](https://github.com/scipy/scipy/blob/master/scipy/stats/_discrete_distns.py#L52) ? 

If somebody could confirm that, I'm happy to submit the corresponding PR :)

**Comment by ev-br** [comment]
It seems to me that here it's better to change the docs to match code. https://github.com/scipy/scipy/blob/master/scipy/stats/_distn_infrastructure.py#L68 and below for cdf, SF, logcdf and logsf.

**Comment by svendx4f** [comment]
Oh, that's where the doc comes from! Thanks!

But both the documentation you pointed to and the code I pointed to mention `x` as variable name, whereas `k` seems to be the expected variable name we have to pass to that function. 

=> I guess we should change it at both places ? Or that might break some dependent code? Do you have an idea where this `k` comes from?

**Comment by ev-br** [comment]
Public methods of discrete distributions are defined with `k` as a variable:  `def pmf(self, k, *args, **kwds):` https://github.com/scipy/scipy/blob/master/scipy/stats/_distn_infrastructure.py#L2797
I suppose we should keep the signatures of these public functions intact and change the docs. Signatures of underscored methods, `_pmf` et al are probably irrelevant, but maybe better keep them as well, just to minimize the churn.

Generation of the docs is a little messy as they are assembled from individual bits and pieces, see `docdict` and `docdict_discrete`, https://github.com/scipy/scipy/blob/master/scipy/stats/_distn_infrastructure.py#L227

**Comment by ev-br** [comment]
fixed by gh-6631, closing.
