### ISSUE TITLE
no fsolve in scipy

### ISSUE THREAD

**Issue by profmsaeed** [scipy/scipy#6639]
in scipy package ver. 0.18.1 for windows there is no fsolve

**Comment by rgommers** [comment]
@profmsaeed we'll need some more info to be able to help you. What code are you executing exactly, and how did you install scipy?

**Comment by profmsaeed** [comment]
'from scipy.optimize import fsolve' returns 'unresolved import fsolve.
I installed scipy wheel file downloaded from 'http://www.lfd.uci.edu/~gohlke/pythonlibs/ ' with pip

**Comment by rgommers** [comment]
``from scipy.optimize import fsolve`` should work. No Windows here, so can't test that wheel. @cgohlke there is possibly an issue with your 0.18.1 wheel.

There's nothing to fix in Scipy and we can't fix that wheel here, so closing this issue.

Thanks for the report @profmsaeed

**Comment by profmsaeed** [comment]
Ok

**Comment by cgohlke** [comment]
Works for me. `unresolved import` sounds like there is a problem with the IDE environment. Python would throw a `ImportError`.
