### ISSUE TITLE
`clange_` not found while importing `lsqr`

### ISSUE THREAD

**Issue by Rholais** [scipy/scipy#6642]
Paths of `BLAS`, `LAPACK` and `ATLAS` are well defined.

> Python 3.4.3 (default, Jan 26 2016, 02:25:35)
> [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from scipy.sparse.linalg import lsqr
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/uac/gds/hcli/.local/lib/python3.4/site-packages/scipy-0.18.1-py3.4-linux-x86_64.egg/scipy/sparse/linalg/__init__.py", line 112, in <module>
>     from .isolve import *
>   File "/uac/gds/hcli/.local/lib/python3.4/site-packages/scipy-0.18.1-py3.4-linux-x86_64.egg/scipy/sparse/linalg/isolve/__init__.py", line 6, in <module>
>     from .iterative import *
>   File "/uac/gds/hcli/.local/lib/python3.4/site-packages/scipy-0.18.1-py3.4-linux-x86_64.egg/scipy/sparse/linalg/isolve/iterative.py", line 7, in <module>
>     from . import _iterative
> ImportError: /uac/gds/hcli/.local/lib/python3.4/site-packages/scipy-0.18.1-py3.4-linux-x86_64.egg/scipy/sparse/linalg/isolve/_iterative.cpython-34m.so: undefined symbol: clange_
> 

I was wondering how I could solve this problem?

**Comment by rgommers** [comment]
how did you install scipy, and where did you get your BLAS/LAPACK from?

**Comment by Rholais** [comment]
@rgommers  I installed scipy from source with ATLAS

**Comment by pv** [comment]
The error sounds like the LAPACK you have installed/built is missing some standard parts.
If so, it's not really a bug in Scipy and better discussed e.g. on stackoverflow etc.

**Comment by rgommers** [comment]
agreed, not much we can do except recommend finding a better ATLAS package

**Comment by Rholais** [comment]
@rgommers  I was wondering if you could recommend an ATLAS package?

**Comment by rgommers** [comment]
@Rholais not sure, sorry (never been a Red Hat / CentOS user). A quick Google search doesn't seem to turn up much.

**Comment by Rholais** [comment]
@rgommers  indeed, I'll keep on investigating that. Anyway, thank you guys! @pv

**Comment by Rholais** [comment]
@rgommers  Fixed by using `OpenBLAS` but it seems to be less efficient.

**Comment by rgommers** [comment]
Overall OpenBLAS will give you at least as good performance as ATLAS.

**Comment by Rholais** [comment]
@rgommers  thanks for your kind recommendation!
