### ISSUE TITLE
Confusing documentation for `scipy.special.sph_harm`

### ISSUE THREAD

**Issue by EmperorDali** [scipy/scipy#6657]
The [documentation](http://docs.scipy.org/doc/scipy/reference/generated/scipy.special.sph_harm.html#scipy.special.sph_harm) for `scipy.special.sph_harm` states that this function computes 

> Y_n^m(\theta,\phi) = \sqrt{\frac{2n+1}{4\pi}\frac{(n-m)!}{(n+m)!}} e^{im\theta}P_n^m(\cos(\phi))

I am not an expert in spherical harmonics, but to my eyes this notation imples that `scipy` is computing spherical harmonics _without_ the [Condon-Shortley phase](https://en.wikipedia.org/wiki/Spherical_harmonics#Condon.E2.80.93Shortley_phase) factor.  

However, `scipy` is actually computing the spherical harmonics _with_ CS phase:

> sph_harm(1,1,0,np.pi/2)
> (-0.3454941494713355+0j)

compare this to 

> Y_1^1(\theta,\phi) = \sqrt{\frac{3}{4\pi}}e^{i\theta}(-1)(1-\cos(\phi))^2

which is a spherical harmonic _with_ CS phase, [see table here](https://en.wikipedia.org/wiki/Table_of_spherical_harmonics#Spherical_harmonics)

Presumably this is because `scipy` includes the CS phase factor with the associated Legendre function `scipy.special.lpmv`. I believe this is another convention that is used, however the documentation for `scipy.special.lpmv` doesn't state what exactly is being computed.

We should 1) update the documentation for `lpmv` to indicate that the function computes the associated Legendre polynomials with CS phase 2) add a note to the documentation for `sph_harm` indicating that the function returns spherical harmonics with CS phase.

**Comment by Eric89GXL** [comment]
Sounds good to me. We should also 3) add tests for this to be sure, via manual evaluation of the equation and/or cross-checking with other packages. Do you have time to make a PR?

**Comment by person142** [comment]
Hey @EmperorDali note that the wiki page defines

`Y_1^1(theta, phi) = stuff*exp(i*phi)*sin(theta)`

whereas SciPy defines

`Y_1^1(theta, phi) = stuff*exp(i*theta)*sin(phi)`.

If I flip the arguments in your example I get

```python
>>> sph_harm(1, 1, np.pi/2, 0)
(-0+0j)
```
which matches the wiki expression. So I think everything defined correctly in the documentation.

**Comment by Eric89GXL** [comment]
Oh great, the multiple definitions of spherical harmonics strike again...

**Comment by ev-br** [comment]
Given the amount of confusion this generates over the years, it'd probably be good to add an explicit form of the low-order harmonics (m=1, l=-1, 0, 1) and mention the Condon-Schockley phase.

**Comment by person142** [comment]
And while someone was working on that, they could also add a full definition of `lpmv` and mention the Condon-Shortley phase (or lack thereof) there too.

**Comment by EmperorDali** [comment]
@person142 I don't agree with what you wrote. Note that when I copied Y_1^1 from the table to my first post I interchanged \theta and \phi, to match `scipy`'s convention.

If you look at my post, you'll see I did `stuff*exp(i*theta)*sin(phi)`, both in `scipy` code and in direct computation by `Y_1^1`

**Comment by person142** [comment]
Ah, I worked directly from the wiki page and missed that. Apologies.

The function `lpmv` is in `specfun`, so I cracked open Zhang and Jin who indeed define

`P_v^m(x) = (-1)^m (1 - x^2)^{m/2} (d^m/dx^m) P_v(x)`.

**Comment by person142** [comment]
The refguide for the Legendre functions could also use some improvements:

https://scipy.github.io/devdocs/special.html#legendre-functions

In particular it's difficult to figure out the differences between the functions at a glance. Also, given the names of the functions (consider `lpmv` and `lpmn`, neither of which are very descriptive) I'd say that adding some aliases would be a good idea.

**Comment by Eric89GXL** [comment]
Yes it could be cleaned up a bit. I'll see if I can find some time to do it.
