### ISSUE TITLE
mode asks for 'ignore' in error, but wants 'omit'

### ISSUE THREAD

**Issue by Gijs-Koot** [scipy/scipy#6660]
In

    >> scipy.stats.mode(np.array([2, 3, np.nan]), nan_policy='ignore')

Out

    >> ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-147-a841bca3e462> in <module>()
    ----> 1 mode(np.array([2, 3, np.nan]), nan_policy='ignore')

    /home/gijs/anaconda3/lib/python3.5/site-packages/scipy/stats/stats.py in mode(a, axis, nan_policy)
    636         return np.array([]), np.array([])
    637 
    --> 638     contains_nan, nan_policy = _contains_nan(a, nan_policy)
    639 
    640     if contains_nan and nan_policy == 'omit':

    /home/gijs/anaconda3/lib/python3.5/site-packages/scipy/stats/stats.py in _contains_nan(a, nan_policy)
    241 def _contains_nan(a, nan_policy='propagate'):
    242     if nan_policy not in ('propagate', 'raise', 'omit'):
    --> 243         raise ValueError("nan_policy must be either 'propagate', 'raise', or "
    244                          "'ignore'")
    245     try:

    ValueError: nan_policy must be either 'propagate', 'raise', or 'ignore'

Version

    scipy.__version__
    '0.17.1'

**Comment by person142** [comment]
Looks fixed in master:

``` python
>>> from scipy import stats
>>> import numpy as np
>>> stats.mode(np.array([2, 3, np.nan]), nan_policy='ignore')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Josh/Projects/scipy-dev/python3/scipy/scipy/stats/stats.py", line 424, in mode
    contains_nan, nan_policy = _contains_nan(a, nan_policy)
  File "/Users/Josh/Projects/scipy-dev/python3/scipy/scipy/stats/stats.py", line 237, in _contains_nan
    ', '.join("'%s'" % s for s in policies))
ValueError: nan_policy must be one of {'propagate', 'raise', 'omit'}
>>> import scipy
>>> scipy.__version__
'0.19.0.dev0+91f74c9'
```

**Comment by person142** [comment]
Closing since it's fixed in master--let me know if I missed something. Thanks for the report @Gijs-Koot!

**Comment by Gijs-Koot** [comment]
Thanks, didn't realize I was that far behind already. :+1:
