### ISSUE TITLE
MemoryError when decimating large array

### ISSUE THREAD

**Issue by cbrnr** [scipy/scipy#6669]
I want to decimate a relatively large float64 array of shape (60, 3904880). However, I get a `MemoryError` exception on a Linux 64bit machine with 8GB of RAM (line 3092 in `signaltools.py`: `y = lfilter(system.num, system.den, x, axis=axis)`). Converting the data to `float32` doesn't help either, so I was wondering if there is a way to perform decimation (or more generally, filtering) in a way that minimizes memory requirements (e.g. blockwise)?

**Comment by rgommers** [comment]
There's no blocked algorithm AFAIK. However, in your case it probably helps to filter in a for-loop over the first dimension of your data; reduces the input size to ``lfilter`` by a factor 60 (probably without affecting speed significantly). The filtering is 1-D, so doing a 2-D array in one go is basically a simple convenience.

**Comment by cbrnr** [comment]
OK thanks, I'll try that. Seems to be a special use case anyway, so no need to extend `lfilter` or `decimate` with an argument that lets you split an array into blocks (which would only make sense for memmaps anyway).

**Comment by Eric89GXL** [comment]
resample_poly should only allocate the necessary destination space (and
only do the necessary computations). Not sure if we ever made decimate wrap
to it under the hood...

**Comment by cbrnr** [comment]
@Eric89GXL can I use `resample_poly` to perform downsampling? Does it include an anti-aliasing filter? Is this different in `resample`? I thought `decimate` is just `resample` with an added zero-phase anti-aliasing filter...

**Comment by Eric89GXL** [comment]
> can I use resample_poly to perform downsampling? Does it include an anti-aliasing filter? Is this different in resample? I thought decimate is just resample with an added zero-phase anti-aliasing filter...

Yes you can use it, it applies a FIR filter. Are you on 0.18? PR #5975 made it so that `decimate` actually calls `resample_poly` when using a FIR filter for downsampling.

Note that these functions operate a bit differently from `resample`, which uses FFT-based resampling. They will have different behaviors at the edges of the signals, and different ringing characteristics.
