### ISSUE TITLE
Scipy on aarch64 android specifically termux

### ISSUE THREAD

**Issue by its-pointless** [scipy/scipy#6670]
I have a gfortran compiler and tried making scipy it largely works but it does segfault on test_dense. You might be interested.

**Comment by rgommers** [comment]
if you give us all the details on how you compiled (OS, Python version, build command, compiler versions), the verbose output of running the tests, and ideally a GDB traceback, then yes.

**Comment by pv** [comment]
... and the details of what BLAS and LAPACK was used, whether also the 
LAPACK test suite crashes etc.

**Comment by its-pointless** [comment]
Sorry im using openblas gcc 6.2 https://github.com/its-pointless/gcc_termux

**Comment by pv** [comment]
Please also provide the other information asked above.

**Comment by person142** [comment]
Closing since this isn't actionable as is--we need the extra info.
