### ISSUE TITLE
return value of scipy.optimize.minimize not consistent for 1D

### ISSUE THREAD

**Issue by solarjoe** [scipy/scipy#6673]
For 1D problems some optimizers return the result as a scalar (Powell, COBYLA), some
as a list with one element.

There are other optimizers that need the Jacobian, I did not check them.

``` python
from scipy.optimize import minimize, rosen

o = ['Nelder-Mead', 'Powell', 'CG',  'BFGS', 'L-BFGS-B',
      'TNC', 'COBYLA', 'SLSQP']

for k in o:

    x0 = [1.3] #, 0.7, 0.8, 1.9, 1.2]
    res = minimize(rosen, x0, method=k, tol=1e-6)

    print(k, res.x)

print()

for k in o:

    x0 = 1.3 #, 0.7, 0.8, 1.9, 1.2]
    res = minimize(rosen, x0, method=k, tol=1e-6)

    print(k, res.x)

print()

for k in o:

    x0 = [1.3, 0.7]
    res = minimize(rosen, x0, method=k, tol=1e-6)

    print(k, res.x)

```

**Comment by person142** [comment]
ISTM the most consistent thing would be to return an array in all cases. In that case the culprits are 'POWELL' (always returns a scalar) and 'COBYLA' (returns a scalar if given a scalar).

**Comment by innisfree** [comment]
Other than updating the docs to make this clear, I can't see what you can do here without breaking backwards compatibility?

**Comment by person142** [comment]
The documentation for `OptimizeResult`:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html#scipy.optimize.OptimizeResult

says that `res.x` is an ndarray. Also I just noticed that

```python
>>> res = minimize(lambda x: x**2, 0.1, method='POWELL')
>>> res.x
array(4.163336342344337e-17)
>>> res = minimize(lambda x: x**2, 0.1, method='COBYLA')
>>> res.x
array(0.00010234375000000536)
```
so they are returning arrays; this would just be changing their shape to 1x1. (Importantly, `float(res.x)` works in either case.)

This makes me feel like it would be an acceptable back-compat break to make them all return 1x1 arrays. But maybe others are more conservative?

**Comment by innisfree** [comment]
My guess is that backwards compatibility consistent, uniform return types here.  Does anyone know for sure is this breaks any unit tests? Even if it doesn't it still breaks back-compat. This needs a decision.

**Comment by samuela** [comment]
While we may not want to break backwards compatibility right now, this is definitely something that should be made consistent in a future version release.

**Comment by mdhaber** [comment]
It looks like this is already fixed, and there is already a test
https://github.com/scipy/scipy/blob/3123229c02fc2f31a368098b81a17f8723c209ab/scipy/optimize/tests/test_optimize.py#L2433

A snipped that can be run locally to confirm:
```python3
import numpy as np
from scipy import optimize
from scipy.optimize._minimize import MINIMIZE_METHODS, MINIMIZE_SCALAR_METHODS

def f(x, a):
    return x**2 + a.sum()

def df(x, a):
    return 2*x

def ddf(x, a):
    return 2

a = np.array([-1, -2])

for method in MINIMIZE_METHODS:

    kwargs = {'fun': f, 'x0': 1, 'args': a, 'method': method}
    if method in {'newton-cg', 'dogleg', 'trust-ncg',
                  'trust-exact', 'trust-krylov'}:
        kwargs['jac'] = df
        kwargs['hess'] = ddf

    res = optimize.minimize(**kwargs)
    assert res.x.shape == (1,)
    print(res.x)
```
