### ISSUE TITLE
Add unicode characters for scipy.constants

### ISSUE THREAD

**Issue by Phyks** [scipy/scipy#6674]
Hi,

Since Python 3 supports [non-ASCII identifiers](https://www.python.org/dev/peps/pep-3131/), it could be useful to add unicode characters alternatives for the [constants names](http://docs.scipy.org/doc/scipy/reference/constants.html).

Typically, something like 

```python
π = scipy.constants.pi
ħ = scipy.constants.hbar
ε_0 = scipy.constants.epsilon_0
[...]
```

Since Jupyter notebook has shortcuts to type these Unicode characters, and they are valid identifiers, it could be used to improve code readability at small cost. Of course, this should not be included under Python < 3, where these identifiers are not valid, and the old constants names should remain for compatibility. These unicode names could be aliases.

What do you think about it? Thanks!

**Comment by rgommers** [comment]
Hi @Phyks, thanks for the suggestion. Maybe in the future we can do this, but I don't think we should include any code that doesn't work for all supported Python versions.
