### ISSUE TITLE
dendrogram plot

### ISSUE THREAD

**Issue by Arnold1** [scipy/scipy#6678]
Hi,

how can you plot a dendrogram using scipy and forward the plot to matplotlib? can someone tell me why my created dendrogram is not a tree structure? is the problem in scipy dendrogram or somewhere else?
http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.cluster.hierarchy.dendrogram.html

i adapted the following example: http://matplotlib.org/xkcd/examples/user_interfaces/embedding_in_qt.html
here a fully plot example: https://gist.github.com/Arnold1/f5bf032a227247f413e8b056a61ba0d8
and got fancy_dendrogram from here:
https://joernhees.de/blog/2015/08/26/scipy-hierarchical-clustering-and-dendrogram-tutorial/

```
class MyMplCanvas(FigureCanvas):
  """Ultimately, this is a QWidget (as well as a FigureCanvasAgg, etc.)."""
  def __init__(self, title, xlabel, ylabel, linkage_matrix, cut_off, parent=None, width=5, height=4, dpi=100):
    fig = Figure(figsize=(width, height), dpi=dpi)
    self.axes = fig.add_subplot(111)
    # We want the axes cleared every time plot() is called
    self.axes.hold(True)

    self.compute_initial_figure(title, xlabel, ylabel, linkage_matrix, cut_off)

    #
    FigureCanvas.__init__(self, fig)
    self.setParent(parent)

    FigureCanvas.setSizePolicy(self,
      QSizePolicy.Expanding,
      QSizePolicy.Expanding)
    FigureCanvas.updateGeometry(self)

  def compute_initial_figure(self):
    pass

class MyStaticMplCanvas(MyMplCanvas):
  def compute_initial_figure(self, title, xlabel, ylabel, linkage_matrix, cut_off):

    self.fancy_dendrogram(
      linkage_matrix,
      leaf_rotation=90., # rotates the x axis labels
      leaf_font_size=8., # font size for the x axis labels
      show_contracted=False,
      #annotate_above=10,
      max_d=cut_off,  # plot a horizontal cut-off line
    )

  def fancy_dendrogram(self, *args, **kwargs):
      max_d = kwargs.pop('max_d', None)
      if max_d and 'color_threshold' not in kwargs:
          kwargs['color_threshold'] = max_d
      annotate_above = kwargs.pop('annotate_above', 0)

      ddata = dendrogram(*args, **kwargs)

      if not kwargs.get('no_plot', False):
          self.axes.set_title('Hierarchical Clustering Dendrogram (truncated)')
          self.axes.set_xlabel('sample index or (cluster size)')
          self.axes.set_ylabel('distance')
          for i, d, c in zip(ddata['icoord'], ddata['dcoord'], ddata['color_list']):
              x = 0.5 * sum(i[1:3])
              y = d[1]
              if y > annotate_above:
                  self.axes.plot(x, y, 'o', c=c)
                  self.axes.annotate("%.3g" % y, (x, y), xytext=(0, -5),
                               textcoords='offset points',
                               va='top', ha='center')
          if max_d:
              self.axes.axhline(y=max_d, c='k', linestyle='--', color='red')
      return ddata
```

here is the output:
<img width="1184" alt="screen shot 2016-10-13 at 5 52 15 am" src="https://cloud.githubusercontent.com/assets/3844226/19336134/3a32ac0a-9109-11e6-9c84-424256d6f03f.png">

my dendrogram just has single points and not a tree structure.... is the problem in scipy dendrogram or somewhere else?

i expected the dendrogram to have the same style as here: https://joernhees.de/blog/2015/08/26/scipy-hierarchical-clustering-and-dendrogram-tutorial/

**Comment by rgommers** [comment]
I don't see the data to reproduce this, and I also don't see any error in your code. ``fancy_dendrogram`` seems fine. When you call that standalone (without the MPL canvas), do you get the horizontal and vertical lines?

**Comment by Arnold1** [comment]
@rgommers let me create a simple example to reproduce it.

**Comment by Arnold1** [comment]
bug fixed:

```
  def fancy_dendrogram(self, *args, **kwargs):
    kwargs['ax'] = self.axes
    ...
```

could you tell me why that is required?

**Comment by rgommers** [comment]
Something complex in matplotlib. You were mixing Matplotlib elements with the ``pylab`` API, which is never good. From the ``dendrogram`` docstring:

         ax : matplotlib Axes instance, optional
             If None and `no_plot` is not True, the dendrogram will be plotted
             on the current axes.  Otherwise if `no_plot` is not True the
             dendrogram will be plotted on the given ``Axes`` instance. This can be
             useful if the dendrogram is part of a more complex figure.

Thanks for the update, closing.

**Comment by Arnold1** [comment]
thanks for help. what is your recommended way to plot a dendrogram with pyqt?

**Comment by rgommers** [comment]
there's nothing really special about a dendrogram, so just put it in a canvas like you would for any other figure
