### ISSUE TITLE
cannot build scipy (0.18.1) on AIX (xlc_r, xlC_r and xlf)

### ISSUE THREAD

**Issue by aixtools** [scipy/scipy#6685]
Environment:
AIX 6.1, xlc v11, xlf v15
python 2.7.12
lapack 3.6.1 (static)

-- pip list --
Cython (0.24.1)
numpy (1.11.2)
pandas (0.19.0)
pip (8.1.1)
python-dateutil (2.5.3)
pytz (2016.7)
setuptools (20.10.1)
six (1.10.0)

scipy-0.18.1

python setup.py build

Question: what changes the symbol so that an extra _ is expected (e.g., a #define macro somewhere)?

Currently ends with:
/opt/lib/python2.7/config/ld_so_aix /opt/IBM/xlf/15.1.2/bin/xlf95 -bI:/opt/lib/python2.7/config/python.exp -bshared -F/tmp/tmp4qpCeS/2QOsK5_xlf.cfg build/temp.aix-6.1-2.7/scipy/cluster/_vq.o -L/usr/lib -Lbuild/temp.aix-6.1-2.7 -llapack -llapack -lblas -lblas -o build/lib.aix-6.1-2.7/scipy/cluster/_vq.so
ld: 0711-317 ERROR: Undefined symbol: .sgemm_
ld: 0711-317 ERROR: Undefined symbol: .dgemm_
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
ld: 0711-317 ERROR: Undefined symbol: .sgemm_
ld: 0711-317 ERROR: Undefined symbol: .dgemm_
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
error: Command "/opt/lib/python2.7/config/ld_so_aix /opt/IBM/xlf/15.1.2/bin/xlf95 -bI:/opt/lib/python2.7/config/python.exp -bshared -F/tmp/tmp4qpCeS/2QOsK5_xlf.cfg build/temp.aix-6.1-2.7/scipy/cluster/_vq.o -L/usr/lib -Lbuild/temp.aix-6.1-2.7 -llapack -llapack -lblas -lblas -o build/lib.aix-6.1-2.7/scipy/cluster/_vq.so" failed with exit status 8

both .sgemm and .dgemm are defined in /usr/lib/libblas.a (but not as .sgemm_ and .dgemm_)

root@x065:[/data/prj/python/pipbuilds/scipy-0.18.1]nm -Ae /usr/lib/libblas\* | grep -E " .[sd]gemm" | grep -v " U "
/usr/lib/libblas.a[dgemm_64.o]: .dgemm               T           0
/usr/lib/libblas.a[dgemmU_64.o]: _dgemm               D        1336          24
/usr/lib/libblas.a[dgemmU_64.o]: _dgemm               d        1312           8
/usr/lib/libblas.a[sgemm_64.o]: .sgemm               T           0
/usr/lib/libblas.a[sgemmU_64.o]: _sgemm               D        1344          24
/usr/lib/libblas.a[sgemmU_64.o]: _sgemm               d        1312           8

FYI: this is a 64-bit build for all modules!

Had it been 32-bit the 'linking' would have been the same:
root@x065:[/data/prj/python/pipbuilds/scipy-0.18.1]nm -X32 -Ae /usr/lib/libblas\* | grep -E " .[sd]gemm" | grep -v " U "
/usr/lib/libblas.a[dgemm.o]: .dgemm               T           0
/usr/lib/libblas.a[dgemmU.o]: _dgemm               D        1260          12
/usr/lib/libblas.a[dgemmU.o]: _dgemm               d        1248           4
/usr/lib/libblas.a[sgemm.o]: .sgemm               T           0
/usr/lib/libblas.a[sgemmU.o]: _sgemm               D        1264          12
/usr/lib/libblas.a[sgemmU.o]: _sgemm               d        1248           4

**Comment by rgommers** [comment]
``scipy.cluster has some special handling for ``sgemm`` and ``dgemm`` in ``scipy/cluster/cluster_blas.*``. That is from before the introduction of Cython bindings in ``scipy.linalg``. Can you check if that is the only issue by just removing the cluster package and the line ``config.add_subpackage('cluster')`` in ``scipy.setup.py``? If it is, we can fix that. But it could also be that it's just the first BLAS usage you're hitting and the ``linalg`` build also won't work.

**Comment by aixtools** [comment]
Rebuilt test system to try again...
a) after install of AIX and install of python, plus numpy

need to add
 'CXX': 'xlC_r',
to
$prefix/lib/python2.7/.sysconfigdata.py

This is just something for "google" to find - for this error message:

  File "/opt/lib/python2.7/site-packages/numpy/distutils/ccompiler.py", line 516, in CCompiler_cxx_compiler
    cxx.compiler_so = [cxx.compiler_cxx[0]] + cxx.compiler_so[1:]

Also, I think it was for scipy, I also had to build the libraries /usr/lib/liblapack.a and /usr/lib/libtmglib.a (i.e., an lapack dependency needed to be resolved) - as these (on my system) are static libraries - they will never show as a dependency that needs to be installed.

With "cluster" removed as you suggest - this is as far as we get:

building 'scipy.integrate._quadpack' extension
compiling C sources
C compiler: xlc_r -I/opt/include -O3 -qmaxmem=-1 -qarch=pwr5 -q64 -I/opt/buildaix/includes -DNDEBUG

compile options: '-DNO_ATLAS_INFO=1 -I/opt/lib/python2.7/site-packages/numpy/core/include -I/opt/include/python2.7 -c'
xlc_r: scipy/integrate/_quadpackmodule.c
"scipy/integrate/quadpack.h", line 69.12: 1506-1332 (W) A function with return type "double(*)(double)" may not return a value of type "void*".
"scipy/integrate/quadpack.h", line 112.20: 1506-068 (W) Operation between types "void*" and "double(*)(double)" is not allowed.
"scipy/integrate/quadpack.h", line 113.20: 1506-068 (W) Operation between types "void*" and "double(*)(double)" is not allowed.
"scipy/integrate/quadpack.h", line 116.30: 1506-068 (W) Operation between types "double(*)(double)" and "void*" is not allowed.
"scipy/integrate/quadpack.h", line 122.30: 1506-068 (W) Operation between types "double(*)(double)" and "void*" is not allowed.
"scipy/integrate/quadpack.h", line 160.20: 1506-068 (W) Operation between types "void*" and "double(*)(int,double*)" is not allowed.
"scipy/integrate/quadpack.h", line 162.16: 1506-068 (W) Operation between types "struct _object*" and "double*" is not allowed.
"scipy/integrate/quadpack.h", line 165.26: 1506-068 (W) Operation between types "double(*)(int,double*)" and "double(*)(double)" is not allowed.
"scipy/integrate/quadpack.h", line 197.21: 1506-068 (W) Operation between types "double(*)(int,double*)" and "void*" is not allowed.
"scipy/integrate/quadpack.h", line 199.17: 1506-068 (W) Operation between types "double*" and "struct _object*" is not allowed.
/opt/lib/python2.7/config/ld_so_aix /opt/IBM/xlf/15.1.2/bin/xlf95 -bI:/opt/lib/python2.7/config/python.exp -bshared -F/tmp/tmpiFeREG/9nU7PW_xlf.cfg build/temp.aix-6.1-2.7/scipy/integrate/_quadpackmodule.o -L/usr/lib -Lbuild/temp.aix-6.1-2.7 -lquadpack -lmach -llapack -llapack -lblas -lblas -o build/lib.aix-6.1-2.7/scipy/integrate/_quadpack.so
ld: 0711-317 ERROR: Undefined symbol: .dgtsv_
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
ld: 0711-317 ERROR: Undefined symbol: .dgtsv_
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
error: Command "/opt/lib/python2.7/config/ld_so_aix /opt/IBM/xlf/15.1.2/bin/xlf95 -bI:/opt/lib/python2.7/config/python.exp -bshared -F/tmp/tmpiFeREG/9nU7PW_xlf.cfg build/temp.aix-6.1-2.7/scipy/integrate/_quadpackmodule.o -L/usr/lib -Lbuild/temp.aix-6.1-2.7 -lquadpack -lmach -llapack -llapack -lblas -lblas -o build/lib.aix-6.1-2.7/scipy/integrate/_quadpack.so" failed with exit status 8
root@x065:[/data/prj/python/pipbuilds/scipy-0.18.1]

With -bnoquiet added the messages end with:

ld: 0711-318 ERROR: Undefined symbols were found.
        The following symbols are in error:
 Symbol                    Inpndx  TY CL Source-File(Object-File) OR Import-File{Shared-object}
                              RLD: Address  Section  Rld-type Referencing Symbol
 ----------------------------------------------------------------------------------------------
 .dgtsv_                   [42]    ER PR scipy/integrate/quadpack/dqc25f.f(build/temp.aix-6.1-2.7/libquadpack.a[dqc25f.o])
                                   00000d3c .text    R_RBR    [6]     .dqc25f_
                                   00001750 .text    R_RBR    [6]     .dqc25f_
ER: The return code is 8.

FYI: there are also many "warning" messages about mismatched pointer types, etc., but shall worry about those when it finally get so far that "check" can be run.
nm -X64 -Ae /usr/lib/libblas* | grep -E "dgtsv"

returns nothing...

**Comment by aixtools** [comment]
After review - this issue does not seem to be related to numpy #8173 - and should remain open.
I shall use some different flags to provide more detailed compiler output (source file with messages inserted). If I can find a solution on my own I shall post that, otherwise your assistance will be appreciated.

**Comment by aixtools** [comment]
Have to rebuild a test system with all compilers. Will verify status of building scipy when I do.

**Comment by rgommers** [comment]
@aixtools thanks. You may want to use latest master, I just merged gh-11139 which may have fixed this issue.

**Comment by aixtools** [comment]
Will do.

**Comment by aixtools** [comment]
Will see about rebuilding test system today. This is a module that will make an excellent wheel, once all the bits needed get merged into CPython and pypa!

**Comment by rgommers** [comment]
That sounds good! Is there a standard AIX wheelhouse? I don't think AIX wheels can go on PyPI.

**Comment by aixtools** [comment]
a) replied by email. short answer: wheels do not exist (yet) for AIX. Ongoing project to get them available (for all).

b) did not download master - instead tried `pip download scipy` and ran into other issues - that I'll start looking into:

Testing with AIX 7.1 and Python3.9 (a1); xlcv16 and xlf15 (but not gotten to needing xlf yet).

```
root@x069:[/python]pip3 download scipy
Collecting scipy
  Downloading https://files.pythonhosted.org/packages/a7/5c/495190b8c7cc71977c3d3fafe788d99d43eeb4740ac56856095df6a23fbd/scipy-1.3.3.tar.gz (23.8MB)
     |################################| 23.8MB 20kB/s
  Saved ./scipy-1.3.3.tar.gz
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/bin/python3.9 /opt/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-6p45kpel/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools 'Cython>=0.29.13' 'numpy==1.13.3; python_version=='"'"'3.5'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.5'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"''
       cwd: None
  Complete output (64 lines):
  Ignoring numpy: markers 'python_version == "3.5" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.8" and platform_system != "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.5" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
  Collecting wheel
    Downloading https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl
  Collecting setuptools
    Downloading https://files.pythonhosted.org/packages/54/28/c45d8b54c1339f9644b87663945e54a8503cfef59cf0f65b3ff5dd17cf64/setuptools-42.0.2-py2.py3-none-any.whl (583kB)
  Collecting Cython>=0.29.13
    Downloading https://files.pythonhosted.org/packages/9c/9b/706dac7338c2860cd063a28cdbf5e9670995eaea408abbf2e88ba070d90d/Cython-0.29.14.tar.gz (2.1MB)
      ERROR: Command errored out with exit status 1:
       command: /opt/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5uhkkyuz/Cython/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5uhkkyuz/Cython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
           cwd: /tmp/pip-install-5uhkkyuz/Cython/
      Complete output (43 lines):
      running egg_info
      creating pip-egg-info/Cython.egg-info
      writing pip-egg-info/Cython.egg-info/PKG-INFO
      writing dependency_links to pip-egg-info/Cython.egg-info/dependency_links.txt
      writing entry points to pip-egg-info/Cython.egg-info/entry_points.txt
      writing top-level names to pip-egg-info/Cython.egg-info/top_level.txt
      writing manifest file 'pip-egg-info/Cython.egg-info/SOURCES.txt'
      Unable to find pgen, not compiling formal grammar.
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-5uhkkyuz/Cython/setup.py", line 228, in <module>
          setup(
        File "/opt/lib/python3.9/site-packages/setuptools/__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "/opt/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/opt/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/opt/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/opt/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 296, in run
          self.find_sources()
        File "/opt/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
          mm.run()
        File "/opt/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 534, in run
          self.add_defaults()
        File "/opt/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
          sdist.add_defaults(self)
        File "/opt/lib/python3.9/distutils/command/sdist.py", line 228, in add_defaults
          self._add_defaults_ext()
        File "/opt/lib/python3.9/distutils/command/sdist.py", line 311, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "/opt/lib/python3.9/distutils/cmd.py", line 299, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/opt/lib/python3.9/distutils/cmd.py", line 107, in ensure_finalized
          self.finalize_options()
        File "/tmp/pip-install-5uhkkyuz/Cython/Cython/Distutils/build_ext.py", line 20, in finalize_options
          self.distribution.ext_modules[:] = cythonize(
        File "/tmp/pip-install-5uhkkyuz/Cython/Cython/Build/Dependencies.py", line 959, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/tmp/pip-install-5uhkkyuz/Cython/Cython/Build/Dependencies.py", line 752, in create_extension_list
          elif isinstance(patterns, basestring) or not isinstance(patterns, collections.Iterable):
      AttributeError: module 'collections' has no attribute 'Iterable'
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/bin/python3.9 /opt/lib/python3.9/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-6p45kpel/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- wheel setuptools 'Cython>=0.29.13' 'numpy==1.13.3; python_version=='"'"'3.5'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.13.3; python_version=='"'"'3.6'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.14.5; python_version=='"'"'3.7'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system!='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.5'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.6'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.16.0; python_version=='"'"'3.7'"'"' and platform_system=='"'"'AIX'"'"'' 'numpy==1.17.3; python_version>='"'"'3.8'"'"' and platform_system=='"'"'AIX'"'"'' Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@x069:[/python]

```

**Comment by aixtools** [comment]
Update: almost... will try with "master" tomorrow. But looks like something with numpy now (sigh)

with scipy-1.3.3 got as far as:

```
creating /tmp/tmpo0yudqk9/tmp/tmpo0yudqk9
compile options: '-MMD -MF /tmp/tmpo0yudqk9/file.c.d -c'
xlc_r: /tmp/tmpo0yudqk9/file.c
/opt/IBM/xlC/16.1.0/bin/.orig/xlc_r: 1501-208 (S) command option D is missing a subargument
customize UnixCCompiler using build_ext
Traceback (most recent call last):
  File "/python/scipy-1.3.3/./setup.py", line 505, in <module>
    setup_package()
  File "/python/scipy-1.3.3/./setup.py", line 501, in setup_package
    setup(**metadata)
  File "/opt/lib/python3.9/site-packages/numpy/distutils/core.py", line 171, in setup
    return old_setup(**new_attr)
  File "/opt/lib/python3.9/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/opt/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/lib/python3.9/site-packages/numpy/distutils/command/build.py", line 47, in run
    old_build.run(self)
  File "/opt/lib/python3.9/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/opt/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/lib/python3.9/site-packages/numpy/distutils/command/build_ext.py", line 210, in run
    self._cxx_compiler = compiler.cxx_compiler()
  File "/opt/lib/python3.9/site-packages/numpy/distutils/ccompiler.py", line 92, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
  File "/opt/lib/python3.9/site-packages/numpy/distutils/ccompiler.py", line 685, in CCompiler_cxx_compiler
    cxx.compiler_so = [cxx.compiler_cxx[0]] + cxx.compiler_so[1:]
IndexError: list index out of range


```

**Comment by rgommers** [comment]
That's new, could be a `distutils` or `numpy.distutils` thing.

We got the feedback from IBM that they care much more about GCC, so I don't think many people test with XLC anymore.

**Comment by aixtools** [comment]
This depends on who you talk to is my experience.

GCC is a great compiler, but it also requires a run/time environment
that is not native to AIX. And that additional run/time environment is
not as dedicated to being ABI compatible as the environment provided by
IBM AIX. So, while using GCC as a developer makes life easy / it makes
life miserable for the admin who is responsible for maintaining security
and OSS updates with packagers using different versions of gcc, over
time, and-or because there are multiple packages being maintained by
multiple people, each who use, for various reasons, a different version
of gcc.

For stability - xlc is still my preferred compiler. Packages that can
only be compiled by gcc (i.e., not by xlc) are packages I tend to
backlist. I would have to create a special system administration policy
to support it.

On 12/11/2019 2:58 AM, Ralf Gommers wrote:
>
> That's new, could be a |distutils| or |numpy.distutils| thing.
>
I'll try again this evening: with Python-3.7.5 (will fix the hiccup with
Cython, and make sure xlC is installed, in the hopes that CXX will be
filled in by the build process. I tried removing and then rebuilding
numpy after manually adding CXX to the sysconfig file - so I am not sure
where/by whom it is not being seen.

Question: does scipy also need xlC (aka C++)?

Regards,

Michael

**Comment by rgommers** [comment]
Yes, you need both a C and a C++ compiler (and Fortran as well).

**Comment by aixtools** [comment]
As life - and numpy - has moved on, I'll close this issue for now - and open a new one later - with new AIX and python levels in any case. I also package Python for AIX - and am using wheels aka Python bdist for packaging things like numpy - which, I hope, will open up the availability of packages on AIX - especially those that require multiple compilers - to build.

**Comment by rgommers** [comment]
Thanks @aixtools!
