### ISSUE TITLE
sicpy.ndimage.zoom returns artefacts and boundaries in some cases

### ISSUE THREAD

**Issue by matthias-k** [scipy/scipy#6713]
I just ran into some strange behaviour of `scipy.ndimage.zoom` which I did not expect from the documentation. I am not sure whether it is a bug or me missunderstanding the expected behaviour. Here is my example:

``` python
>>> from scipy.ndimage import zoom
>>> img = np.ones((768, 1024))
>>> zoom(img, (0.125, 0.125), order=1)

array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       ..., 
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])
```

Is there something I am missing here or is this bug?

**Comment by rgommers** [comment]
Looks like a bug. ``zoom`` seems to think the last row is outside the array:

    >>> >>> zoom(img, (0.125, 0.125), order=1, cval=np.nan)
    array([[  1.,   1.,   1., ...,   1.,   1.,   1.],
           [  1.,   1.,   1., ...,   1.,   1.,   1.],
           [  1.,   1.,   1., ...,   1.,   1.,   1.],
           ..., 
           [  1.,   1.,   1., ...,   1.,   1.,   1.],
           [  1.,   1.,   1., ...,   1.,   1.,   1.],
           [ nan,  nan,  nan, ...,  nan,  nan,  nan]])

**Comment by rgommers** [comment]
There are at least 4 other issues about ``ndimage.zoom``. It needs a bit of a rewrite it looks like.

**Comment by adivijaykumar** [comment]
@rgommers could you let me know what the other issues are? Could try working on it.

**Comment by rgommers** [comment]
@adivijaykumar yes those are the ones. A word of warning: the ``ndimage`` C code is not easy to understand, so only try to work on this one if you're comfortable in C.
