### ISSUE TITLE
Why I can not install scipy successfully on my windows system laptop?

### ISSUE THREAD

**Issue by peipeihan** [scipy/scipy#6720]
I install pip and numpy first. Then I download the scipy-0.18.0 package from github scripy and execute python -m pip install scipy but it turns out there is error in the file I download. Would anybody help with this problem? Thank you very much.
![scipy error](https://cloud.githubusercontent.com/assets/22327262/19661698/973d6de8-99e9-11e6-8096-90e43adce357.png)

**Comment by person142** [comment]
You can't currently install SciPy on Windows using pip; see https://github.com/scipy/scipy/issues/5461. For methods of installing that will work see https://scipy.org/install.html.
