### ISSUE TITLE
Possible error in scipy.stats.linregress

### ISSUE THREAD

**Issue by sgordon20** [scipy/scipy#6738]
I have used this routine on a simple dataset to create a linear regression.  The answer I get is different from the one obtained using MATLAB and SPSS.  Is there an error in the code?
The dataset is attached with the first variable is IBI (Y) and the second is TSS_MAX (x).  Also attached is the SPSS and linregress results as PDF files.

[scipyCodeoutput.pdf](https://github.com/scipy/scipy/files/560015/scipyCodeoutput.pdf)
[spss_output_paint.pdf](https://github.com/scipy/scipy/files/560016/spss_output_paint.pdf)
[paintcr2.pdf](https://github.com/scipy/scipy/files/560017/paintcr2.pdf)

**Comment by WarrenWeckesser** [comment]
Numpy arrays (just like python lists) use zero-based indexing.  This code:

    IBI=paintcr2csv[1:10,0]
    TSS_MAX=paintcr2csv[1:10,1]

discards the first row of `paintcr2csv`.  You could change that to

    IBI = paintcr2csv[:10,0]
    TSS_MAX = paintcr2csv[:10,1]

if you want just the first 10 rows of the array.

Here's the result of `linregress` using all 10 samples:

```
In [10]: x = np.array([15, 13, 24, 43, 55, 52, 62, 60, 78])

In [11]: y = np.array([51, 56, 52, 47, 37, 44, 44, 36, 35])

In [12]: linregress(x, y)
Out[12]: LinregressResult(slope=-0.30412621359223302, intercept=58.250970873786407, rvalue=-0.91415542657021986, pvalue=0.00056068311341998637, stderr=0.050971781908560367
```
That matches the SPSS output.
