### ISSUE TITLE
Problems with website

### ISSUE THREAD

**Issue by mdenhoedt** [scipy/scipy#6747]
The website [https://www.scipy.org/](https://www.scipy.org/) has certificate problems. Both Firefox 49.0.2 and Internet Explorer 11 are giving me this warning.

**Comment by rgommers** [comment]
Thanks for the report @mdenhoedt. The open issue for that on the ``scipy.org`` repo is https://github.com/scipy/scipy.org/issues/187. Is being worked on now.
