### ISSUE TITLE
scipy.org down?

### ISSUE THREAD

**Issue by libbkmz** [scipy/scipy#6749]
What's happened with scipy.org? 
```
wget -S -O /dev/null http://scipy.org
--2016-11-01 17:02:47--  http://scipy.org/
Resolving scipy.org (scipy.org)... 50.17.248.72
Connecting to scipy.org (scipy.org)|50.17.248.72|:80... failed: Connection refused.
```

I can't access docs from google, which is really annoying...
Do you need help?

**Comment by person142** [comment]
Issue tracking this is here: https://github.com/scipy/scipy.org/issues/187.

Note that you can still access the dev version of the docs: https://scipy.github.io/devdocs/.
