### ISSUE TITLE
interpolate.griddata shifts data northwards, is it a bug?

### ISSUE THREAD

**Issue by d1mach** [scipy/scipy#6752]
Results from interpolate.griddata appear shifted northwards.

Top picture shows true distribution of the data
![scatter](https://cloud.githubusercontent.com/assets/11075246/19929071/3001c190-a134-11e6-94a3-3f0b1d3a7bbc.png)
Bottom picture shows the distribution returned by interpolate.griddata
![interpolate](https://cloud.githubusercontent.com/assets/11075246/19929070/30009e32-a134-11e6-9b46-f1bad39fb494.png)

Here is a link to an [IPython notebook](https://gist.github.com/d1mach/6bbe5c5351f32c5ac74e4dfa8e42b356) that illustrates the issue

**Comment by pv** [comment]
Double check that you are using imshow correctly (e.g. not transposing 
the image etc).

**Comment by d1mach** [comment]
In reply to @pv comment. If you mean that the orientation of the picture might be wrong then here is a picture with two boxes that shows that the orientation is correct and there is something different going on.
![interpolate_ab](https://cloud.githubusercontent.com/assets/11075246/19956670/d944e39e-a1c1-11e6-9fab-ceb79ca49fa9.png)
Again the same points plotted with scatter fit well.
![scatter_ab](https://cloud.githubusercontent.com/assets/11075246/19956704/1ee603c4-a1c2-11e6-9f41-0b5810e57811.png)

**Comment by pv** [comment]
I don't think this is a bug in griddata. If you do
```
plt.clf()
plt.pcolormesh(mapx, mapy, mapdata)
plt.scatter(lons, lats, values)
```
you see the squares align.

**Comment by d1mach** [comment]
Indeed, visualizing with pcolormesh using
 ```
meshx,meshy = m(mapx,mapy)
plt.pcolormesh(meshx,meshy,mapdata)
```
the results properly align.
