### ISSUE TITLE
unexpected inversion in fisher_exact p-values over small range of arguments

### ISSUE THREAD

**Issue by patena** [scipy/scipy#6758]
I ran into a case of fisher_exact p-values going slowly up and then sharply down and slowly up again, over a uniform range of a single argument.  I'm fairly sure this shouldn't be happening.  Am I misusing the function somehow, or is this a real error?

```
>>> for x in range(1338,1356): print scipy.stats.fisher_exact([[0, x], [2369, 699722]])
... 
(0.0, 0.02787009907791051)
(0.0, 0.02791103203574459)
(0.0, 0.027952350965163682)
(0.0, 0.027994055770513251)
(0.0, 0.028036146824929845)
(0.0, 0.028078624032413353)
(0.0, 0.028121487508106453)
(0.0, 0.017484170648664931)
(0.0, 0.017484101168458062)
(0.0, 0.017484299162895015)
(0.0, 0.017484764558238983)
(0.0, 0.01748549734269924)
(0.0, 0.017486497556017597)
(0.0, 0.017487765173154451)
(0.0, 0.017489300176743185)
(0.0, 0.017491102560909973)
(0.0, 0.017493172361352043)
(0.0, 0.017495509613732918)
```
(scipy 0.14.1, in python 2.7.10 and 3.4.3+)

**Comment by josef-pkt** [comment]
I'm pretty sure that's the expected behavior.
Because of the discreteness of the sample space, exact statistics have the sawtooth patternm e.g. the power function w.r.t sample size. 

The easiest would be to check with R or another package for this example.

**Comment by patena** [comment]
Wow, you're right - I checked in R and got the same result. I had no idea the correct results could look so strange. Sorry about the unnecessary bug report, then.
