### ISSUE TITLE
CI on OS X

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#6760]
At the moment, our CI is *nix only. While OS X specific issues are relatively rare, and we typically find those only when someone reports a problem.

Thanks to Matthew, there is an OS X CI facility on TravisCI, https://github.com/MacPython/scipy-wheels 
It however is only set up to build the master branch, and is meant to upload the build artefacts for consumption downstream --- neither of which is particularly suitable for troubleshooting. 

We probably want something lightweight: either an entry in our .travis.yml so that we check each push of each PR, or a separate repo where we could trigger an OS X build when need arises.

**Comment by Eric89GXL** [comment]
I don't know of any CI services that allow OSX builds for free.

**Comment by ev-br** [comment]
So @matthew-brett pays for running the build services for the whole scipy stack? Wow.

**Comment by matthew-brett** [comment]
:) - the OSX builds are free too.   You can add OSX builds to the current `.travis.yml` matrix by using the ``os: osx`` setting.  See the scikit-image travis setup for an example:

https://github.com/scikit-image/scikit-image/blob/master/.travis.yml

**Comment by pv** [comment]
I guess nothing stops us from adding an always on OSX target to travis 
(or switching one of the current ones to osx).

**Comment by Eric89GXL** [comment]
Excellent! I wonder when they made that change. Time to update a bunch of repos...

**Comment by andyfaff** [comment]
The conda forge project use a travis and appveyor setup to make osx and windows conda packages and upload the artefacts.  Its definitely worth adding an OSX target, is there much headspace left on how much travis resource we can play with?

**Comment by rgommers** [comment]
Yes. We have had issues with the runtime of the full test suite timing out, but I don't think there's an issue with adding more entries to the build matrix.

**Comment by andyfaff** [comment]
Shame we can't run windows CI tests as well.

**Comment by jakevdp** [comment]
CircleCI supplies free Windows builds, I believe.

**Comment by rgommers** [comment]
> CircleCI supplies free Windows builds, I believe.

no Fortran compiler .....

**Comment by jakevdp** [comment]
> no Fortran compiler .....

Ah, right.

I think I recall someone saying they use a docker image on CircleCI in order to compile Fortran, but I can't recall at the moment who or where that was...

**Comment by andyfaff** [comment]
Closed by #7607
