### ISSUE TITLE
Documentation for scipy.spatial.Delaunay is partially incorrect

### ISSUE THREAD

**Issue by keuj6** [scipy/scipy#6764]
If I am not mistaking, the final explanation on how to calculate barycentric coordinates is flawed. It can easily be proved by taking twice the same point
`p = np.array([(0.1, 0.2), (0.1, 0.2)])
b = tri.transform[1,:2].dot(p - tri.transform[1,2])
np.c_[b, 1 - b.sum(axis=1)]`
returns two different sets of barycentric coordinates : [.1, .2, .7] & roughly [0, 0, 1].
The correct formulas should rather be :
`b = tri.transform[1,:2].dot(np.transpose(p - tri.transform[1,2]))
np.c_[np.transpose(b), 1 - b.sum(axis=0)]`
answer is [ 0.10,  0.09,  0.81] for both, which is more logical

**Comment by pv** [comment]
Yes, it seems incorrect (you can also see that for 3 points the shapes 
don't match).

**Comment by keuj6** [comment]
Indeed, this is actually how I discovered this.
How do we proceed next to propose a description update?

**Comment by person142** [comment]
@keuj6 if you're interested in doing it, just make the changes you think are necessary here

https://github.com/scipy/scipy/blob/master/scipy/spatial/qhull.pyx#L1693

and send us a PR.

**Comment by keuj6** [comment]
Thank you for the guidance @person142
