### ISSUE TITLE
scipy.special precision

### ISSUE THREAD

**Issue by andrewisonfire** [scipy/scipy#6766]
How can i change precision of calculation of scipy.special.kv() or another special functions?
for example, I need a precision 8 bytes or more, but I got less.
there is no information about in in documentation,or i did not find it :(

**Comment by pv** [comment]
The calculations always work in double precision, and the precision 
cannot be changed. For some functions, the accuracy is further limited 
by algorithm choices in some parameter regions.
.
If you need arbitrary precision (but slower) evaluation, use `mpmath` 
http://mpmath.org/

**Comment by person142** [comment]
Closing--we do not currently have ambitions to include arbitrary precision versions of routines. (There's enough to be done with the double precision routines for now.)
