### ISSUE TITLE
`scipy.optimize.curve_fit`'s undocumented `return_full` keyword doesn't work with bounded problems

### ISSUE THREAD

**Issue by david-hoffman** [scipy/scipy#6772]
scipy's `curve_fit` has a useful, but undocumented, keyword `return_full`. When this keyword is set to `True` the function will return extra information that is useful for debugging and adding functionality to one's own code. However, the keyword doesn't work with bounded problems. This is because bounded problems are solved by `least_squares` and unbounded problems are solved by `leastsq` and `least_squares` returns an `OptimizeResult` which is different from what is returned by `leastsq`.

**Comment by ev-br** [comment]
Thanks for the report. I guess it's possible to return the whole OptimizeResult if `full_output is True` and bounds are not None.

**Comment by david-hoffman** [comment]
or the output of `leastsq` could be packed into an `OptimizeResult` so that the return is the same in all cases.

**Comment by ev-br** [comment]
> or the output of leastsq could be packed into an OptimizeResult so that the return is the same in all cases.

If we were starting from scratch, then yes. Otherwise no, for it breaks backwards compatibility for a not-good-enough reason.

**Comment by pv** [comment]
It can be re-packed into OptimizeResult in curve_fit, however.

**Comment by david-hoffman** [comment]
Yes I meant what @pv suggested. If that's still unacceptable than one could do it the other way around: repackage the `OptimizeResult` returned by `least_squares` into the same format as `leastsq`:

    infodict = dict(nfev=res.nfev, fvec=res.fun, fjac=res.jac, ipvt=None, qtf=None)
    ier = res.status
    errmsg = res.message

Where `res` is the `OptimizeResult` returned by `least_squares` and the `None`'s would be replaced by appropriate values.
