### ISSUE TITLE
scipy.ndimage.filters.convolve, incorrect formula in description

### ISSUE THREAD

**Issue by SVRaph** [scipy/scipy#6783]
The documentation of the function `scipy.ndimage.filters.convolve` says that it computes:
> `C_i = \\sum_j{I_{i+j-k} W_j}`
while this is the correlation formula. And indeed the weight are inverted in `_correlate_or_convolve`. I think the corresponding formula should be:
> `C_i = \\sum_j{I_{i-j+k} W_j}`
Am I wrong ?

**Comment by ev-br** [comment]
This seems to have been fixed in master,
http://scipy.github.io/devdocs/generated/scipy.ndimage.convolve.html#scipy.ndimage.convolve

**Comment by SVRaph** [comment]
sorry, my bad. I didn't check I was looking at an ancient version. Mondays are hard...

**Comment by ev-br** [comment]
@SVRaph No problem! Thanks for double-checking it.
