### ISSUE TITLE
scipy.special.ellipe(x): error of convergency

### ISSUE THREAD

**Issue by cybertib** [scipy/scipy#6784]
Dear all, 

By comparing complete elliptic integral special.ellipe(x) function, I found the followings: 
* ellipe(0.) = pi / 2 #Valid 
* ellipe(1.) = 0. #Valid 
* ellipe(0.5) = 1.3506438810476755 #Maple gives: 1.46746220933942715545979526699
* ellipe(0.3) = 1.4453630644126654 #Maple gives: 1.53483346492324904164530353748

Hence, it appears that convergence of the integration is erroneous for this function.

Version of Python 2.7: anaconda 4.0.0
Version of SciPy '0.16.0'
Version of NumPy '1.10.1'

Note: taking m=k^2=1 is not sensitive to the convention, hence **this cannot be related to different conventions** taken for defining E(k). See #3618. 

Definition given by scipy:
> This function is defined as math:: E(m) = \int_0^{\pi/2} [1 - m \sin(t)^2]^{1/2} dt

Definition given in Wikipedia: 
> E(k)=\int_0^\tfrac{\pi}{2} \sqrt{1-k^2 \sin^2\theta}\ d\theta

Best regards, 
Thibault

**Comment by pv** [comment]
There are different conventions for the argument of the elliptic
function. I think the results are correct for the convention used here:
.
>>> quad(lambda t: sqrt(1 - 0.5 * sin(t)**2), 0, pi/2)
(1.3506438810476755, 4.601927892172075e-14)
>>> quad(lambda t: sqrt(1 - 0.3 * sin(t)**2), 0, pi/2)
(1.4453630644126654, 1.6046753530537143e-14)

**Comment by pv** [comment]
If you disagree, please provide data points and reopen.

**Comment by WarrenWeckesser** [comment]
Also note that scipy uses the same convention as Wolfram Alpha: https://www.wolframalpha.com/input/?i=EllipticE%5B0.5%5D
