### ISSUE TITLE
cannot create Hermite polynomials with n>63

### ISSUE THREAD

**Issue by tigran123** [scipy/scipy#6797]
As the subject says. Here is the session log that shows the issue:

```
$ ipython3
Python 3.5.2 (default, Sep 19 2016, 19:31:40) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import scipy.special

In [2]: p = scipy.special.hermite(63)

In [3]: q = scipy.special.hermite(64)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-4a58861fd605> in <module>()
----> 1 q = scipy.special.hermite(64)

/usr/local/lib/python3.5/site-packages/scipy/special/orthogonal.py in hermite(n, monic)
    970     kn = 2**n
    971     p = orthopoly1d(x, w, hn, kn, wfunc, (-inf, inf), monic,
--> 972                     lambda x: eval_hermite(n, x))
    973     return p
    974 

/usr/local/lib/python3.5/site-packages/scipy/special/orthogonal.py in __init__(self, roots, weights, hn, kn, wfunc, limits, monic, eval_func)
    143             kn = 1.0
    144         self.__dict__['normcoef'] = mu
--> 145         self.__dict__['coeffs'] *= kn
    146 
    147         # Note: eval_func will be discarded on arithmetic

TypeError: ufunc 'multiply' output (typecode 'O') could not be coerced to provided output parameter (typecode 'd') according to the casting rule ''same_kind''
```

As you see, I can successfully create Hermit polynomial of degree 63, but not 64. This is a serious limitation as I need them for n up to about 300 or so.

**Comment by charris** [comment]
You might try the numpy hermite package as a temporary measure, see https://docs.scipy.org/doc/numpy/reference/routines.polynomials.package.html.

**Comment by charris** [comment]
Which scipy version?

**Comment by pv** [comment]
If you need to evaluate hermite polynomial values, use `eval_hermite`. If you need the roots, use `h_roots`.

For any other use you might have for the object returned by `hermite(n)`, order 64 is too high to deal in power basis, so you need to use numpy's hermite package instead for those use cases.

**Comment by person142** [comment]
Also this is fixed in master by https://github.com/scipy/scipy/pull/6723.

**Comment by person142** [comment]
And a hearty second to

> use numpy's hermite package instead for those use cases

`special.hermite` really shouldn't be used.

**Comment by tigran123** [comment]
Thank you, the `numpy.polynomial.hermite.hermval` (v1.11.1) calculates it up to n=267 and fails on n=268, but this should be enough for my purposes. My the version of scipy I am using is 0.18.1.

**Comment by charris** [comment]
If you want to work with series, look into the `numpy.polynomial.Hermite` class.
```
In [1]: from numpy.polynomial import Hermite as H

In [2]: p = H.basis(200)

In [4]: p(10)
Out[4]: -4.7005387186273366e+238

In [5]: p = H([1,2,3]) # H_0 + 2*H_1 + 3*H_2

In [6]: p(10)
Out[6]: 1235.0
```

**Comment by charris** [comment]
If all you need more precision for the polynomial value and speed isn't a worry, you can use mpmath for high precision floating math.
```
In [1]: from numpy.polynomial import Hermite as H

In [2]: from mpmath import mp

In [3]: mp.dps = 50

In [4]: p = H.basis(300)

In [5]: p(mp.mpf(10))
Out[5]: mpf('2.4201725642444760462645654047603738271429748006678641e+373')
```
This won't work for roots, however. That could probably be fixed by using a different root finder.
