### ISSUE TITLE
Segmentation fault in pip wheel of scipy 0.18.1 - scipy.linalg.blas

### ISSUE THREAD

**Issue by jason-neal** [scipy/scipy#6813]
I get a segmentation fault with the pip wheel of version 0.18.1.
This is in a new conda environment. 
Installing scipy 0.18.1 with conda works fine.

Using the pip version I think I have narrowed it down to scipy.linalg.blas. 
```
> python -c "import  scipy.linalg"
Segmentation fault (core dumped)
```

Using verbose the last lines of the output are
```
> python -v -c "import  scipy.linalg"
...
...
import scipy.linalg.misc # precompiled from /home/user/anaconda2/envs/obstools/lib/python2.7/site-packages/scipy/linalg/misc.pyc
# /home/user/anaconda2/envs/obstools/lib/python2.7/site-packages/scipy/linalg/blas.pyc matches /home/user/anaconda2/envs/obstools/lib/python2.7/site-packages/scipy/linalg/blas.py
import scipy.linalg.blas # precompiled from /home/user/anaconda2/envs/obstools/lib/python2.7/site-packages/scipy/linalg/blas.pyc
dlopen("/home/user/anaconda2/envs/obstools/lib/python2.7/site-packages/scipy/linalg/_fblas.so", 2);
Segmentation fault (core dumped)
```
It does the same thing trying to run the test suite.
```
python -c "import scipy; scipy.test('full')"
Running unit tests for scipy
NumPy version 1.11.2
NumPy relaxed strides checking option: False
NumPy is installed in /home/user/anaconda2/envs/obstools/lib/python2.7/site-packages/numpy
SciPy version 0.18.1
SciPy is installed in /home/user/anaconda2/envs/obstools/lib/python2.7/site-packages/scipy
Python version 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
nose version 1.3.7
Segmentation fault (core dumped)
```

**Comment by person142** [comment]
Which OS? Does 0.17.1 work?

**Comment by jason-neal** [comment]
Fedora 23
```
$ uname -a
Linux localhost.localdomain 4.7.10-100.fc23.x86_64 #1 SMP Wed Oct 26 23:29:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
No 0.17.1 does not work (when installed from pip) or other versions< 0.17. I think I tried 0.11, 0.12, 0.15, 0.16.

When I install using `pip install scipy --no-binary :all:` then it works without segmentation fault.

**Comment by pv** [comment]
Possibly due to combination with conda --- maybe trying to mix mkl and 
openblas causes problems.

**Comment by rgommers** [comment]
> Possibly due to combination with conda --- maybe trying to mix mkl and openblas causes problems.

That, or the Python builds maybe. Either way, the answer here is "don't do that" I think. If you're using conda, use the scipy in either the ``defaults`` or ``conda-forge`` conda channel. Or build scipy from source if you need to, but never use a wheel from PyPI.
