### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by maxhup010** [scipy/scipy#6815]
I have windows 10, python 3.5.2 and also numpy installed, but scipy doesn't want to do it. I ran "pip install scipy".

error in cmd

Command "c:\users\max\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Max\\AppData\\Local\\Temp\\pip-build-pwxp9oon\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Max\AppData\Local\Temp\pip-wry9olcr-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Max\AppData\Local\Temp\pip-build-pwxp9oon\scipy\

Thanks

**Comment by person142** [comment]
Can't install SciPy on Windows using `pip`. See https://github.com/scipy/scipy/issues/5461. See also the installation instructions: https://www.scipy.org/install.html.

**Comment by ilayn** [comment]
For windows I think the only painless way is to use [C. Gohlke's builds.](http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy)

**Comment by rgommers** [comment]
The recommended way on Windows is to install a distribution (like Anaconda). That's by far the easiest. See http://scipy.org/install.html
