### ISSUE TITLE
Unable to use scipy.stats.multivariate_normal

### ISSUE THREAD

**Issue by frapoleon** [scipy/scipy#6816]
I have installed scipy before, but unable to find a module named multivariate_normal. I guess it is because I didn't upgrade scipy. But when I use pip install scipy --upgrade, it returns error 13: Permission denied - /usr/local/lib/python2.7. How can I fix it? I am using Mac. Thanks a lot!

**Comment by rgommers** [comment]
Hi @frapoleon, see my answer on the numpy issue you just opened.

**Comment by rgommers** [comment]
For next time: note that this is not an issue, so the scipy-user mailing list would have been more appropriate.

**Comment by frapoleon** [comment]
Sorry about that. Thank you so much.
