### ISSUE TITLE
signal.spectrogram doesn't change nperseg to length of window

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#6817]
From the mailing list, an issue with ``nperseg`` not adjusting to ``window`` in ``signal.spectrogram`` (https://mail.scipy.org/pipermail/scipy-dev/2016-November/021620.html):

    from scipy.io import wavfile
    from scipy.signal import slepian # i.e. 'DPSS' window used for FFT
    from scipy.signal import spectrogram

    FFT_SIZE = 512
    FFT_OVERLAP = FFT_SIZE - 32
    win_dpss = slepian(FFT_SIZE, 4/FFT_SIZE) #shape =

    [rate,data] = wavfile.read('a_file_you_have.wav')
    f,t,spec = spectrogram(data, rate, window=win_dpss, noverlap=FFT_OVERLAP)

**Comment by NickleDave** [comment]
@rgommers @Eric89GXL working on a fix now

**Comment by e-q** [comment]
Fixed by 93a0ea9
