### ISSUE TITLE
The requested URL /doc/scipy/reference/generated/scipy-integrate-odeint-1.py was not found on this server.

### ISSUE THREAD

**Issue by sebasped** [scipy/scipy#6821]
Broken documentation link:

https://docs.scipy.org/doc/scipy/reference/generated/scipy-integrate-odeint-1.py

On doc web page:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.odeint.html#scipy.integrate.odeint

**Comment by person142** [comment]
Duplicate of https://github.com/scipy/scipy/issues/3250, so closing. Thanks for the report @sebasped.
