### ISSUE TITLE
Incoherent result 

### ISSUE THREAD

**Issue by MarwanG** [scipy/scipy#6822]
When comparing 2 lists for example [1,1,1,1] and [1,1,1,1] the expected kendall tau result as far as i know should be 1 however when running stats.kendalltau the result is nan.

**Comment by josef-pkt** [comment]
x and y in a 2-d diagram is just a point, the slope of a correlation is not determined.

```
>>> np.corrcoef(np.ones(5), np.ones(5))
array([[ nan,  nan],
       [ nan,  nan]])
```

same should be true for other correlation/association measures like kendalltay
