### ISSUE TITLE
hierarchical clustering in scipy 0.18.1 causes segmentation fault due to missing file scipy/cluster/_hierarchy.c

### ISSUE THREAD

**Issue by PDiracDelta** [scipy/scipy#6825]
debugging with gdb, it output
```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007fffde0d4e2f in __pyx_pf_5scipy_7cluster_10_hierarchy_24nn_chain (__pyx_self=<optimized out>, __pyx_v_method=<optimized out>, __pyx_v_n=<optimized out>, __pyx_v_dists=...)
    at scipy/cluster/_hierarchy.c:10249
10249	scipy/cluster/_hierarchy.c: No such file or directory.
```
I'm quite new to debugging such issues. I've never had a segmentation fault before.

**Comment by person142** [comment]
Please provide a short, self-contained example demonstrating the problem or we can't do much about it. The segfault is probably unrelated to the missing file--presumably the file is missing because you just installed binaries.

**Comment by PDiracDelta** [comment]
It seems like the problem went away when I used the 'single' method instead of the 'ward' method using the scipy.cluster.hierarchy.linkage function.
This works fine for me, so I don't need further assistance.
How do you suggest I proceed with this Issues? Delete it?
It is hard for me to provide a self-contained example, but the line which produced the problem was
`linkage(intensities.T, method='single')`
where intensities is a (3000x6) numpy ndarray

**Comment by person142** [comment]
Segfaults are bad so it would be good to figure out what's going on. You could stick the array in a gist and link to it here. (Does it contain any NaNs or Infs? A segfault related to that was fixed recently.)

**Comment by mp4096** [comment]
I also suspect that the distance matrix contains `nan`s or `inf`s. This issue was discussed in #5142 and then again in #6774.

**Comment by mp4096** [comment]
But of course it can be something different, so an example would be surely helpful!

**Comment by PDiracDelta** [comment]
It did contain NaNs, I suppose that that would be the error.
This has been on my todo-list but I don't have time right now to figure out how to give you guys an understandable though elaborate example, so I'll have to let it rest for now :( thanks anyways!
