### ISSUE TITLE
Need references for stats.skewtest implementation

### ISSUE THREAD

**Issue by borundev** [scipy/scipy#6829]
I have encountered at least one instance of a function whose source is missing. 'skewtest' uses a pretty non-trivial expression to calculate some statistic that is checked against a standard normal for the p-value but it is not at all obvious what that statistic is and why it is being used. In this case it would be good to add a reference.

**Comment by rgommers** [comment]
@borundev you're right, ideally we would have references for every function that implements a nontrivial algorithm. Improving this is an ongoing process (we came from a place where we had 3000 functions and only minimal docstrings for them ~6 years ago).

A general issue about this isn't super productive, so I'll change the title to be specific about ``skewtest``. That's an easy-fix one for someone to do a literature search and find some good references.

**Comment by gavin74** [comment]
@rgommers 
I found a reference for skewtest. I added it to the docstring. Submitting a pull request (hope I did this right, it is my first contribution, let me know if I messed up).

**Comment by rgommers** [comment]
Thanks @gavin74! The mechanics of making a PR and the commit message went well. The tests failed though because of some formatting issue - I'll comment on the PR on how to fix that.
