### ISSUE TITLE
signal.bsplines test

### ISSUE THREAD

**Issue by cynthia-rempel** [scipy/scipy#6835]
Happy Holidays!

Wrote a test-suite for scipy.signal.bsplines

Ran it from the scipy/scipy/signal/tests directory...

It yields a 99% coverage rating and a 94% mutation coverage rating (using cosmic-rays)...
Used pylint to correct the formatting...

The test oracle right now are the results I got when running the functions in an interpreter... so they'll only catch changes in the code...

Really appreciate all you do!

[test_bsplines.zip](https://github.com/scipy/scipy/files/635850/test_bsplines.zip)

**Comment by rgommers** [comment]
Hi @cynthia-rempel, thank you that looks promising! Could you please submit your changes as a pull request rather than a zipped file? If you've never done that before, here's a walkthrough: https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html#basic-workflow

I had a look at your code - the main thing to change would be to use numpy functions to generate the test arrays rather than hardcode them (which is verbose and hard to change). For example, this:

        # data for testing complex branch generated by
        # (numpy.random.rand(7,7)*10000).astype(int)/1000.0 +
        # (numpy.random.rand(7,7)*10000).astype(int)*1j/1000.0
        cplx = array([[5.665+4.273j, 5.101+0.498j, 9.287+9.575j, 7.464+6.337j,
                       3.747+5.486j, 4.143+9.162j, 4.786+6.852j],
                      [4.388+7.543j, 3.901+7.127j, 4.401+3.034j, 
        ....

should be:

    np.random.seed(12457)
    cplx = (np.random.rand(7,7)*10000).astype(int)/1000.0 +
           (np.random.rand(7,7)*10000).astype(int)*1j/1000.0

**Comment by Eric89GXL** [comment]
Also, any idea how long the tests take? It's good if they don't add too much time to the test suite.

**Comment by cynthia-rempel** [comment]
@rgommers Thanks for the feedback, and getting back to me so quickly! I will work on making the changes... on the cbspline_eval and qbspline_eval tests, do you want me to use the r_ function (instead of the regularly spaced matrices)?

@Eric89GXL The test_bsplines.py takes approx two seconds on a clearance laptop...
I suspect the desired changes won't add much time...
If it helps, on most of the functions I experimented until I found the smallest arrays that got the desired coverage properties...
Please let me know if there's anything else I can answer about the test-suite...

**Comment by Eric89GXL** [comment]
You do not need to reorder your EEG channels so don't do `do_ch_fix=True`

**Comment by Eric89GXL** [comment]
Whoops wrong thread

**Comment by Eric89GXL** [comment]
> If it helps, on most of the functions I experimented until I found the smallest arrays that got the desired coverage properties...

That's good, then. Just want to make sure it stays fast if possible.

**Comment by rgommers** [comment]
this was merged in gh-9035
