### ISSUE TITLE
spearmanr fails when nan_policy='omit' is set

### ISSUE THREAD

**Issue by Xparx** [scipy/scipy#6841]
Hi,
I think I tracked down this issue to `_chk_asarray`, I found the issue here: 
Statistics Review: _chk_asarray (Trac #44) #571 (not sure how to link) that seems to touch on the same issue but it's quite a while ago.

the background to my issue and example is the following

Versions:
python 3.5.2
scipy (0.18.1)
numpy (1.11.2)
pandas (0.19.1)

I'm trying to calculate rank correlation for columns of a data frame

    from scipy.stats import spearmanr
    import numpy as np
    import pandas as pd

    df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))
    df[df > 50] = np.nan
    r,p = spearmanr(df,nan_policy='omit')

This will produce the error:

    TypeErrorTraceback (most recent call last)
    <ipython-input-525-49ab94b898f6> in <module>()
    ----> 1 r,p = spearmanr(df,nan_policy='omit')
    
    /home/andreas/.virtualenvs/default3/lib/python3.5/site-packages/scipy/stats/stats.py in spearmanr(a, b, axis, nan_policy)
       3309     if contains_nan and nan_policy == 'omit':
       3310         a = ma.masked_invalid(a)
    -> 3311         b = ma.masked_invalid(b)
       3312         return mstats_basic.spearmanr(a, b, axis)
       3313 
    
    /home/andreas/.virtualenvs/default3/lib/python3.5/site-packages/numpy/ma/core.py in masked_invalid(a, copy)
       2338         cls = type(a)
       2339     else:
    -> 2340         condition = ~(np.isfinite(a))
       2341         cls = MaskedArray
       2342     result = a.view(cls)
    
    TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

Sending in the values of `df.values` does not solve the issue. It looks to me as if the nan checking function fails when supplied with nan values.
What is the issue here and can it be solved for my case.
`nan_policy` would indicate to me that it should be able to handle nan values.
Am I using the wrong nan value?
Running the mask function independently does not fail

    a = np.ma.masked_invalid(df)

neither does isfinite

    ~(np.isfinite(df))

which makes me really perplexed. It looks like the data poinds are changed somewhere in the process

**Comment by ev-br** [comment]
Indeed, it fails on `b=None` and on trying to do `np.ma.masked_invalid(None)`. 

```
3295 ->	        b = ma.masked_invalid(b)
3296 	        return mstats_basic.spearmanr(a, b, axis)
3297 	
3298 	    if a.size <= 1:
3299 	        return SpearmanrResult(np.nan, np.nan)
3300 	    ar = np.apply_along_axis(rankdata, axisout, a)
(Pdb) contains_nan
True
(Pdb) p a is None
False
(Pdb) p b is None
True
```

Seems reasonably easy to fix. Pull requests welcome, I'd say.

**Comment by Don86** [comment]
Hi, I'm new to contributing in general, and would like to work on this. 

This works, though:
```a = np.array([1, 2, 3, 4, 5])
b = np.array([6,6,5,7,np.nan])
r,p = spearmanr(a, b, nan_policy='omit')
print(r, p)

>> 0.35 0.6499999999999996
```
But these don't, where a and b are stuck together into some kind of 2 x 5 structure:
```data = np.array([a, b]).T
df = pd.DataFrame(data, columns=list('AB'))
r,p = spearmanr(data, nan_policy='omit')
>> (same error as OP)
r,p = spearmanr(df, nan_policy='omit')
>> (same error as OP)
```
Perhaps spearmanr doesn't know how to accept a 2D structure.

**Comment by Don86** [comment]
Testing `spearmanr` with 2-dimensional parameters (i.e. 2 variables: "height" and "weight"), it works, though I'm not sure how those numbers were produced.

```
a = np.array([[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]]).T
b = np.array([[6,6,5,7,np.nan], [60, 40, 30, 80, np.nan]]).T
r,p = spearmanr(a, b, nan_policy='omit')
print(r, p)
>> 0.827380952381 0.011251666419077799
```
If I stick `hstack` a and b into a single dataframe and try `spearmanr` as before, it throws an error. Indeed, from the docs:

```
Parameters
----------
a, b : 1D or 2D array_like, b is optional
        One or two 1-D or 2-D arrays containing multiple variables and
        observations. When these are 1-D, each represents a vector of
        observations of a single variable. For the behavior in the 2-D case,
        see under ``axis``, below.
```

i.e. it seems that `spearmanr` can accept two multi-dimensional arrays, i.e. a and b can have multiple params each, but not a and b concatenated. Not sure if this is the desired behaviour?

**Comment by ev-br** [comment]
Fixed by https://github.com/scipy/scipy/pull/6850
