### ISSUE TITLE
argrelmin/argrelmax fail with smooth data and plateaus

### ISSUE THREAD

**Issue by Chris7** [scipy/scipy#6848]
There are certain cases that argrelmin/max will fail due to the comparator being used. For instance:

```
from scipy.signal import argrelmin, argrelmax
import numpy as np
x = np.array([1,2,3,3,2,1])
print(argrelmax(x))
```
returns `(array([], dtype=int64),)`

This happens because the comparator is np.greater. Should this be fixed to provide some resolution or is this the desired behavior?

**Comment by person142** [comment]
Essentially the same issue as https://github.com/scipy/scipy/issues/3749.

**Comment by Chris7** [comment]
Here is some code that fixes this:

```

**Comment by Chris7** [comment]
Bah, sorry for the dupe @person142. Feel free to close/reference this from there if you wish.

**Comment by ilayn** [comment]
@Chris7 Since it is referenced already, you can close this one yourself anyways.

**Comment by person142** [comment]
The other doesn't mention `argrelmax` or `argrelmin`, so IMO it's not unreasonable to leave both open so long as they are linked (even though fixing `_boolrelextrema` fixes both). @Chris7 re

> Here is some code that is one possible fix

any interest in turning that into a PR?

**Comment by Chris7** [comment]
I can try. I don't know how I can really translate it to the multi-dimensional case. Since what I am in effect doing is popping out the duplicates, that will quickly fail once I am working with anything > 1d.

**Comment by lagru** [comment]
There is now an alternative to `_boolextrema` for the 1D case: `_argmaxima1d` introduced in #8350. It approximates the center of flat maxima. I think that function could cover the >1D case with a few small changes as well.
