### ISSUE TITLE
Request:-New Optimization Algorithms

### ISSUE THREAD

**Issue by euler16** [scipy/scipy#6853]
Are algorithms such as Ant Colony Optimization,  AntLion Optimization, Whale Optimization implemented or being implemented in Scipy?  If no wouldn't it be great if we have them in Scipy?

**Comment by euler16** [comment]
MATLAB has them in form of toolbox (not free).

**Comment by josef-pkt** [comment]
My impression when I was looking at the matlab fileexchange in the past, was that there are too many animals looking for food.

Is there somewhere a good overview over how good those search algorithms are and for which applications they are appropriate?

(For statsmodels, I was looking again at cases with global random search but locally smooth(ed) optimization.)

**Comment by euler16** [comment]
These are relatively new algorithm and hence such studies at present probably don't exist.  But taking into account the number of citations and utility of such algos in the field of optimization I think we should have them as part of scipy. Major stochastic algorithms like GAs have a very large impact factor and Python currently doesn't provide them as off the shelf algorithms.

**Comment by euler16** [comment]
The papers (of these algorithms) provide examples related to design of machine parts, construction of bridges etc.

**Comment by rgommers** [comment]
These kinds of evolutionary algorithms have several dedicated packages. DEAP (https://github.com/deap/deap) is the best and most actively maintained one AFAIK. There are several others, see http://esa.github.io/pygmo/ and  http://scipy.org/topical-software.html#optimization.

It seems out of scope for SciPy.  AntLion Optimization and Whale Optimization are also too new and not widely used enough to be considered. Ant Colony Optimization would meet that bar, but it looks to me like it should go into DEAP instead.

**Comment by rgommers** [comment]
out of scope, closing this issue
