### ISSUE TITLE
Support PEP 519 in I/O functions

### ISSUE THREAD

**Issue by mruffalo** [scipy/scipy#6854]
As per [PEP 519](https://www.python.org/dev/peps/pep-0519/), Python 3.6 includes a protocol to specify that an object is "path-like", and builtin/standard library code has been updated to handle anything with a `__fspath__` attribute (including `pathlib.Path` objects and the `DirEntry` objects returned by `os.scandir`). Most notably, the `__builtins__.open` function can now be given anything path-like.

Many projects like SciPy, NumPy, Pandas, etc., have convenience I/O functions which accept filenames in addition to open file-like objects, and in most cases one can get "free" support for the changes in PEP 519 by simply passing whatever the user provides to `open` instead of checking membership in a small set of allowed types. This may be a slight behavior change in which exception is raised from where, if letting `open` throw a `TypeError` for an unsupported type, instead of a specific I/O function raising its own exception for something apparently unsupported.

If feasible, it would be great to modify the I/O functions in SciPy to simply pass any unknown types to `open` instead of rejecting them -- one doesn't have to worry about which version of Python is being used, or whether `hasattr(os, 'fspath')` or anything like that. `open` will handle what it can, and throw a `TypeError` if appropriate, according to the capabilities of whatever version of Python someone is using.

Any opinions about this?

**Comment by pv** [comment]
fixed in gh-6855
