### ISSUE TITLE
[BUG] shift return the wrong result of zero array

### ISSUE THREAD

**Issue by shuokay** [scipy/scipy#6856]
![image](https://cloud.githubusercontent.com/assets/5029591/21167883/a7958116-c1ea-11e6-88e0-d397e1920d45.png)

**Comment by Eric89GXL** [comment]
That looks correct to numerical precision. Is the concern the near-zero values that aren't truly zero? If so I think this is more of a documentation issue than a bug.

**Comment by shuokay** [comment]
Get it, thanks
