### ISSUE TITLE
optimize.minimize with SLSQP returns wrong result if starting point is outside one sided bounds

### ISSUE THREAD

**Issue by jaimefrio** [scipy/scipy#6859]
`scipy.optimize.minimize` with `method='slsqp'` has trouble respecting the `bounds=` kwarg when the starting point is outside the bounds and one of the bounds is not specified:

```
def f(x):
  """Minimum is at x = 1."""
  x, = x
  return x*x - 2*x + 1

# One bound not specified and starting point is outside bounds, FAILS
optimize.minimize(f, [10], method='slsqp', bounds=[(None, 0)])  # FAILS, x = 1
optimize.minimize(f, [-10], method='slsqp', bounds=[(2, None)])  # FAILS, x = 1

# One bound not specified and starting point is within bounds, OK
optimize.minimize(f, [-10], method='slsqp', bounds=[(None, 0)])  # OK, x = 0
optimize.minimize(f, [10], method='slsqp', bounds=[(2, None)])  # OK, x = 2

# Both bounds specified, regardless of where starting point is given, OK
optimize.minimize(f, [-0.5], method='slsqp', bounds=[(-1, 0)])  # OK, x = 0
optimize.minimize(f, [10], method='slsqp', bounds=[(-1, 0)])  # OK, x = 0
```

In all cases the `.success` argument of the return is set to `True`, even if the bounds constraints are not fulfilled.

Things seem to work just fine if the bounds are expressed through the `constraints=` kwarg:

```
def g(x):
  """Impose x <= 0 constraint."""
  x, = x
  return -x
  
optimize.minimize(f, [10], method='slsqp',
                  constraints={'type': 'ineq', 'fun': g})  # OK, x = 0

def g(x):
  """Impose x >= 2 constraint."""
  x, = x
  return x - 2
  
optimize.minimize(f, [-10], method='slsqp',
                  constraints={'type': 'ineq', 'fun': g})  # OK, x = 2
```

I have started looking into this myself, but there doesn't seem to be any obvious mishandling of the bounds, and I don't really understand what is going on deep inside the Fortran code. Anyone more knowledgeable can give me some pointers on what to look for?

**Comment by pv** [comment]
Probably good idea to check if NLOPT's C-translated and bugfixed version 
of SLSQP has these issues: 
http://ab-initio.mit.edu/wiki/index.php/NLopt_Algorithms#SLSQP
.
Namely, instead of trying to fix the fortran code, it could be more 
useful to make use of the C code (according to Steven the version in 
nlopt is still under BSD).

**Comment by jaimefrio** [comment]
NLOPT does not allow the starting point to be outside the bounds. Or so it seems from the very uninformative ValueError it spits out when that is the case.

Does that seem like a desirable behavior for SciPy?

**Comment by pv** [comment]
We could easily clip the starting point inside the bounds. That would be 
the simplest fix --- although I don't currently understand why starting 
point outside of bounds is problematic.

**Comment by jaimefrio** [comment]
By clipping you mean modifying the starting point so it is at the closest bound whenever it is outside?

Sounds like a reasonable thing to do, but should probably not be done without at least warning the user.

Should we do this as well for other methods accepting bounds, or just for SLSQP?
