### ISSUE TITLE
`scipy.interpolate.griddata` fails for readonly arrays

### ISSUE THREAD

**Issue by david-zwicker** [scipy/scipy#6864]
A call `griddata` fails if either the `x` or the `xi` array is read-only. A minimal example reproducing the problem is

```
import numpy as np
from scipy import interpolate

x0 = 10 * np.random.randn(100, 2)
y0 = np.random.randn(100)
x1 = np.random.randn(3, 2)

x0.flags.writeable = False
# x1.flags.writeable = False

interpolate.griddata(x0, y0, x1)
```

As discussed [on Stackoverflow](http://stackoverflow.com/q/41191911/932593), this might be due to the underlying cython implementation which requires a writeable array to create a memory view. I find it strange that this is a requirement on the cython side, but in any case scipy should not throw an array but probably create a (writeable) copy of the array. I could also live with temporarily modifying the `writeable` attribute, but this looks less clean to me.

**Comment by person142** [comment]
Always copying the array doubles memory use, most of the time unnecessarily.

**Comment by david-zwicker** [comment]
I didn't want to imply that you should always do this – you could only make the copy if the array is read-only. It's arguably better to make a copy of the array instead of throwing an exception, which is what currently occurs when the array is read-only.

**Comment by pv** [comment]
Or, make a writeable view under the knowledge that the array won't
actually be written to.

**Comment by ev-br** [comment]
Seems to have been fixed at some point:

```
In [2]: import numpy as np
   ...: from scipy import interpolate
   ...: 
   ...: x0 = 10 * np.random.randn(100, 2)
   ...: y0 = np.random.randn(100)
   ...: x1 = np.random.randn(3, 2)
   ...: 
   ...: x0.flags.writeable = False
   ...: # x1.flags.writeable = False
   ...: 
   ...: interpolate.griddata(x0, y0, x1)
Out[2]: array([-0.22110542, -0.56688331, -0.34818215])

In [3]: import scipy

In [4]: scipy.__version__
Out[4]: '1.7.1'
```
