### ISSUE TITLE
bessel functions

### ISSUE THREAD

**Issue by ordirules** [scipy/scipy#6865]
I would assume these two print statements to be equivalent:
```python 
import numpy as np
from scipy.special import j1
x = .1
print(j1(x))
print((np.sin(x)/x**2 - np.cos(x)/x))
```
Output is (they're not):
```
0.440050585745
0.30116867894
```

[Bessel function j1](https://en.wikipedia.org/wiki/Bessel_function)

There is no documentation as to what the Bessel function should be (i.e. if some constant prefactors are added). Either documentation needs to be improved or function fixed (if this is indeed an error). Any suggestions?

thanks!

julien

**Comment by person142** [comment]
`np.sin(x)/x**2 - np.cos(x)/x` is the first spherical Bessel function, which is related to the Bessel functions of the first kind of order `3/2`. See `spherical_jn`.

**Comment by ordirules** [comment]
Thanks!

Perhaps it's a good chance to add a small line of documentation? (See Also, etc)

**Comment by Eric89GXL** [comment]
Documentation clarifications are always welcome, do you have time to make a
PR?

**Comment by ordirules** [comment]
Added (see PR above). The following text would have made it easier for me, but there may be better wording. thanks!
