### ISSUE TITLE
Currently in gaussian_kde, the logpdf function is calculated directly from the pdf method, which means they get numerical underflow at the same time. Would it make sense to make logpdf be separate so that doesn't happen?

### ISSUE THREAD

**Issue by limoklan** [scipy/scipy#6869]
For high dimensional distributions, the probability density function (pdf) can very quickly get numerical underflow. The log of the pdf value should obviously not overflow as quickly, which is useful when you want to work with high dimension datasets and do stuff like finding maximae. The problem is currently the `gaussian_kde.logpdf` method simply returns `np.log(self.evaluate(x))`, which means that as soon as the normal pdf underflows, so does logpdf. So would you perhaps consider making logpdf do a separate calculation to get rid of that problem? Or is that even possible to do in KDE?

**Comment by ev-br** [comment]
Would be good idea, I'd say. Are you interested in a sending a PR?

**Comment by limoklan** [comment]
Not any time soon, I'm very busy at the moment unfortunately, not to mention I'm not exactly a pro here. Also, upon further reading, I'm starting to wonder if this would even be very useful. Perhaps someone with more experience could weigh in here, but actually for high dimensional samples of points (at least the kind I was working with when I encountered the problem), the curse of dimensionality would probably mean you can't get much use out of the kde anyway. That's why I closed it, it should perhaps be treated as a very tentative suggestion, and if someone with more experience thinks it makes sense then it would be good to implement I guess.

**Comment by rkern** [comment]
It shouldn't be too hard to implement now that we have `logsumexp()`.

**Comment by ev-br** [comment]
Closing as done in gh-6874
