### ISSUE TITLE
Python stopped working (Segfault?) with minimum/maximum filter and all-zero-footprint

### ISSUE THREAD

**Issue by MSeifert04** [scipy/scipy#6876]
Just out of coincidence I got a crash with minimum and maximum filter of the `ndimage` package in scipy 0.18.1:

```
arr = np.random.randint(0, 100, (100, 100))
kernel = np.zeros((3, 3), bool)
maximum_filter(arr, footprint=kernel)  # Crash

minimum_filter(arr, footprint=kernel)  # Crash
```

probably not the smartest move to pass in an all-zero-footprint but an Exception would fit better.

**Comment by ev-br** [comment]
Thanks for the report. https://github.com/scipy/scipy/pull/6877 should fix it

**Comment by MSeifert04** [comment]
Thank you! I can confirm that the change fixes the error for me.
