### ISSUE TITLE
differential_evolution: add seed individuals

### ISSUE THREAD

**Issue by ZacDiggum** [scipy/scipy#6879]
I think it would be very handy if the user was able to provide one or more 'first guess' individuals for the initial seed population in order to speed up convergence in large (real world) search spaces with heavily varying gradients. Would it be hard to add that feature?

**Comment by ZacDiggum** [comment]
@rgommers @dlax 
I've put something together that allows for a single seed individual by overwriting the first individual of the initialized population. Nothing fancy. Should I PR or could you make some suggestions for that feature?

**Comment by andyfaff** [comment]
Initialization of population is currently specified by the init keyword.
The right way of seeding the population by specified individuals is for the
init keyword to also accept an array.

Note that the population members are scaled to a value between 0 and 1.

**Comment by dlax** [comment]
ZacDiggum a écrit :
> @rgommers <https://github.com/rgommers> @dlax <https://github.com/dlax>
> I've put something together that allows for a single seed individual by
> overwriting the first individual of the initialized population. Nothing
> fancy. Should I PR or could you make some suggestions for that feature?
>

It'd help if you could first show us an example code of this feature. If
we are about to expose the `DifferentialEvolutionSolver` API (#6878),
it's a good time to discuss this as well.

**Comment by ZacDiggum** [comment]
I've added a `p0` kwarg to `DifferentialEvolutionSolver`'s `__init__()` and `differential_evolution()` and put the following lines after the original initialization (after line 418):
```
# after population initialization is done, the first individual is
# replaced by an optional and valid user-provided 'first guess' p0
if p0 is not None:
    p0 = np.array(p0, dtype='float')
    if p0.ndim != 1:
        raise ValueError("Only one first guess is allowed for now.")
    elif len(p0) != np.size(self.population, 1):
    raise ValueError('p0 should be a sequence containing '
                               'real values for each value in x')
    elif np.any(self.limits[0]>p0) or np.any(self.limits[1]<p0):
        raise ValueError('p0 is out of bounds')
    else:
        self.population[0] = self._unscale_parameters(p0)
```
As I said, nothing fancy. I attached a zip file containing the altered `_differentialevolution.py` (including the changes to `callback()`) and a curve fitting script based on `differential_evolution()`.
[curve_fit_de.zip](https://github.com/scipy/scipy/files/681518/curve_fit_de.zip)

**Comment by andyfaff** [comment]
There's no need to add an extra p0 keyword. The init keyword can be used
for this.

**Comment by ZacDiggum** [comment]
> The init keyword can be used for this.

Do you think of something like `init=('latinhypercube',p0)`?
Btw, is one seed individual enough or should it be more?

**Comment by dlax** [comment]
I think this would be doable without any additional development with the API I'm working on for #6878:

```
with DifferentialEvolutionSolver(...) as solver:
   solver.population[0] = p0
   # run optimization
```

the idea is that entering the context would trigger population initialization, so it's quite easy to modify the population later on and before running the optimization loop.

@ZacDiggum would that work for you?

**Comment by andyfaff** [comment]
No. Instead of giving a string to init one will give an array.

`init=p0`

Where p0 is an array. In __init__ there is some code which tests which
string was used for the init keyword. This section will also test if an
array-like object was passed in.
If an array like object was provided then initialization will be started
using Latin hyper squares. Then the population array will be partially or
fully overridden by the provided array. This must be done before population
energies are calculated for the first time. The provided array can be 1 or
2d. If 1d then the number of elements must be the same as the problem
dimension. If 2d then the number of columns must be the same as the problem
dimension.

**Comment by ZacDiggum** [comment]
@dlax Sure would! Your new API looks very promising! I'll wait for your first draft.
@andyfaff  You mean init would default to 'latinhypercube' if an array is provided? Is 'random' necessary after all?
Off topic: what happened to parallel evaluation (#5141)? If @dlax's API is final, maybe we could give that one another try...

**Comment by andyfaff** [comment]
I chimed in too early. Let's wait for @dlax api.

The parallelisation effort is stalled at the moment. I think it needs
significant refactoring, which is something I can do.
