### ISSUE TITLE
gaussian_kde.evaluate correcting column vector

### ISSUE THREAD

**Issue by evgenyzhurko** [scipy/scipy#6883]
In what case this [`if statement`](https://github.com/scipy/scipy/blob/2a0d86f21402302bae2d81e85c1ee5532c8ac604/scipy/stats/kde.py#L198) equals `True`?
Example
```
>>> a
array([[-1.99218767, -1.39697254, -0.03312235, -0.09027249,  0.61710745,
         1.64725294,  0.25709321, -0.6765234 , -1.55798244, -0.589371  ]])
>>> g = gaussian_kde(a)  
>>> b = a.T + np.random.rand()
>>> b
array([[-1.89146126],
       [-1.29624612],
       [ 0.06760406],
       [ 0.01045392],
       [ 0.71783386],
       [ 1.74797936],
       [ 0.35781962],
       [-0.57579699],
       [-1.45725603],
       [-0.48864459]])
>>> g.evaluate(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/scipy-0.19.0.dev0_2a0d86f-py2.7-linux-x86_64.egg/scipy/stats/kde.py", line 205, in evaluate
    raise ValueError(msg)
ValueError: points have dimension 10, dataset has dimension 1
```
I think that this `if` should correct error in example, isn't it?

**Comment by rgommers** [comment]
In your example ``b`` is a column vector. The comment below the if statement says it's for row vectors. In your example, ``g.evaluate(b.T)`` does not give a ValueError.

**Comment by evgenyzhurko** [comment]
Yes, you're right, but this [if statement](https://github.com/scipy/scipy/blob/2a0d86f21402302bae2d81e85c1ee5532c8ac604/scipy/stats/kde.py#L197) isn't `True` in this case. I want to find example when this [if statement](https://github.com/scipy/scipy/blob/2a0d86f21402302bae2d81e85c1ee5532c8ac604/scipy/stats/kde.py#L198) is `True`.

**Comment by rgommers** [comment]
I re-read this but I'm not sure what to do here. @evgenyzhurko if there's an actual bug or documentation issue, can you elaborate on your question?

**Comment by evgenyzhurko** [comment]
@rgommers You was right, that i should provide a row vector for this function. It was my fault that i provided column vector to this function. I'll close this issue. Thanks for explanation.
