### ISSUE TITLE
[feature request] Add wavelet synchrosqueezed transform to SciPy

### ISSUE THREAD

**Issue by gabsee** [scipy/scipy#6888]
Is anyone savvy enough to add the new **Wavelet Synchrosqueezed Transform (wsst)** (including inverse **iwsst**) to SciPy?

WSST has recently been implemented in MATLAB (R2016a): https://au.mathworks.com/help/wavelet/ref/wsst.html

The method is based on these two papers:
1. [I. Daubechies, I., J. Lu, and H. T. Wu. "Synchrosqueezed Wavelet Transforms: an Empricial Mode Decomposition-like Tool", Applied and Computational Harmonic Analysis. Vol. 30(2), pp. 243–261.](http://www.sciencedirect.com/science/article/pii/S1063520310001016)
2. [Thakur, G., E. Brevdo, N. S. Fučkar, and H. T. Wu. "The Synchrosqueezing algorithm for time-varying spectral analysis: robustness properties and new paleoclimate applications." Signal Processing. Vol. 93, pp. 1079–1094.](http://arxiv.org/pdf/1105.0010)

The second one contains the algorithm and is available from arxiv.

I have used this method a few times for research projects and it is fantastic! However, I am new to Python, so am unable to implement this (just yet). Availability of wsst/iwsst in SciPy would convince me to give up Matlab for good.

Many thanks for considering :)

**Comment by rgommers** [comment]
Seems interesting. It's out of scope for SciPy though, should go into PyWavelets. I'll open an enhancement request there and Cc you on it.
