### ISSUE TITLE
scipy.stats.mannwhitneyu of empty sets gives p=0.0 and does not raise exception

### ISSUE THREAD

**Issue by erichu8** [scipy/scipy#6897]
`U,pval=scipy.stats.mannwhitneyu([],[])
`

gives U=0.0 and
**pval=0.0**

Other software raise an error and probably scipy should too.

**Comment by rgommers** [comment]
Yeah ``mannwhitneyu`` has problems - there's 11 open issues about it. A rewrite in progress is gh-4933, but that has stalled.
