### ISSUE TITLE
Scipy Optimize Error

### ISSUE THREAD

**Issue by poserleader** [scipy/scipy#6899]
I'm trying to maximize/minimize a function with two variables using Lagrange Multiplier method, below is my code

```
import numpy as np
from scipy.optimize import fsolve

Sa = 200
Sm = 100
n = 50000

mu1 = 400
sigma1 = 25

mu2 = 120
sigma2 = 10

f = 0.9


def func(X):
    u1 = X[0]
    u2 = X[1]
    L = X[2] # this is the multiplier. lambda is a reserved keyword in python

    'function --> f(u1,u2) = u1**2 + u2**2'
    'constraint --> g(u1,u2) = (Snf/a)**1/b = n'

    Snf = Sa/(1-Sm/(sigma1*u1 + mu1))
    a = ((f*(sigma1*u1 + mu1))**2)/(sigma2*u2 + mu2)
    b = -1/3*(f*(sigma1*u1 + mu1))/(sigma2*u2 + mu2)
    return (u1**2+u2**2  - L * ((Snf/a)**1/b) - n)


def dfunc(X):
    dLambda = np.zeros(len(X))
    h = 1e-3 # this is the step size used in the finite difference.
    for i in range(len(X)):
        dX = np.zeros(len(X))
        dX[i] = h
        dLambda[i] = (func(X+dX)-func(X-dX))/(2*h);
    return dLambda

# this is the max
X1 = fsolve(dfunc, [1, 1, 0])
print (X1, func(X1))

# this is the min
X2 = fsolve(dfunc, [-1, -1, 0])
print (X2, func(X2))
```

When I try to do a simple function as the constraint such as u1+u2=4 or u1^2+u2^2 = 20, it works just fine , but when I try my actual constraint function it always gives this error, is there a reason why?? Thanks for the help

    C:\Python34\lib\site-packages\scipy\optimize\minpack.py:161: RuntimeWarning: 
    The iteration is not making good progress, as measured by the improvement from the last five 
    Jacobian evaluations.
    warnings.warn(msg, RuntimeWarning)

**Comment by stsievert** [comment]
`fsolve` is having a hard time finding the roots given those constraints. My first thought is to pass in `fprime`, a function to compute the Jacobian.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fsolve.html

> always gives this error

That's a warning.

**Comment by ev-br** [comment]
Usage questions and support requests like this are best asked on Stackoverflow or scipy-user mailing list. The audience of either channels is larger, and this tracker is primarily used for bug reports. Since I don't believe this is a bug, I'm going to close this. If you do believe there is a bug to fix, please add more details.
