### ISSUE TITLE
linear_sum_assignment with infinite weights

### ISSUE THREAD

**Issue by kaba2** [scipy/scipy#6900]
### Error

The following code crashes:

    import numpy
    import scipy.optimize
    
    costSet = numpy.array(
        [[numpy.inf, 1, numpy.inf], 
        [numpy.inf, 3, numpy.inf], 
        [2, numpy.inf, 3]])
    scipy.optimize.linear_sum_assignment(costSet)

The error message is:

    _hungarian.py:144: RuntimeWarning: invalid value encountered in subtract 
    state.C -= state.C.min(axis=1)[:, np.newaxis]

### Motivation

I use infinite weights to denote pairs that are not allowed to make. This reflects an incomplete bipartite graph.

### Variations

The code already works with infinities in some cases. At first it seems that having a column (or row) of infinities is the problem, since this seems to produce the warning. The example above shows that the problem is more general.

### Workaround

Let M be the maximum of the finite costs in the cost-matrix. We can simulate infinity by replacing it with Q = (2M + 1), say. Any distinct value greater than M will do. This itself is not yet enough, since a choice of Q blocks later assignments for that index. 

The blocking-problem is solved by padding the cost-matrix to a square with Q. Then, if a matching contains a pair with cost Q, it is because there are no better solutions. On the other hand, because the matrix is square, there is enough space to move the Q-match from blocking finite-cost pairs.

Finally, non-allowed pairs are thrown away from the matching.

This seems a valid workaround; example code below. If so, it should be possible to embed this behavior implicitly directly into the Hungarian algorithm, so that the cost-matrix need not be explicitly extended.

```python
def minimumWeightMatching(costSet : numpy.ndarray) -> list:
    '''
    Computes a minimum-weight matching in a bipartite graph
    (A union B, E).

    costSet:
    An (m x n)-matrix of real values, where costSet[i, j]
    is the cost of matching the i:th vertex in A to the j:th 
    vertex of B. A value of numpy.inf is allowed, and is 
    interpreted as missing the (i, j)-edge.

    returns:
    A minimum-weight matching given as a list of pairs (i, j), 
    denoting that the i:th vertex of A be paired with the j:th 
    vertex of B.
    '''

    m, n = costSet.shape
    nMax = max(m, n)

    # Since the choice of infinity blocks later choices for that index, 
    # it is important that the cost matrix is square, so there
    # is enough space to shift the choices for infinity to the unused 
    # part of the cost-matrix.
    costSet_ = numpy.full((nMax, nMax), numpy.inf)
    costSet_[0 : m, 0 : n] = costSet
    assert costSet_.shape[0] == costSet_.shape[1]

    # We allow a cost to be infinity. Since scipy does not
    # support this, we use a workaround. We represent infinity 
    # by M = 2 * maximum cost + 1. The point is to choose a distinct 
    # value, greater than any other cost, so that choosing an 
    # infinity-pair is the last resort. The 2 times is for large
    # values for which x + 1 == x in floating point. The plus 1
    # is for zero, for which 2 x == x.
    try:
        practicalInfinity = 2 * costSet[costSet < numpy.inf].max() + 1
    except ValueError:
        # This is thrown when the indexing set is empty;
        # then all elements are infinities.
        practicalInfinity = 1

    # Replace infinitites with our representation.
    costSet_[costSet_ == numpy.inf] = practicalInfinity

    # Find a pairing of minimum total cost between matching second-level contours.
    iSet, jSet = scipy.optimize.linear_sum_assignment(costSet_)
    assert len(iSet) == len(jSet)

    # Return only pairs with finite cost.
    return [(iSet[k], jSet[k]) 
        for k in range(len(iSet)) 
        if costSet_[iSet[k], jSet[k]] != practicalInfinity]
```

**Comment by rgommers** [comment]
After gh-7031 all inputs with infinite weight raise an error. So this issue is a feature request to add (robust) support for infinite weights. Could probably be done fairly easily, by translating ``inf``s to large values.

**Comment by demin-dmitriy** [comment]
@Kaba2, your choice of Q is not correct.
First, we can't just choose any value bigger than M, e.g. `Q = M+1`. For example, for matrix
```
0  9
9 inf
```
algorithm will chose wrong assignment.

Second, `Q = 2 * M + 1` is better, and will work correctly, if there is only one infinity value in matrix. However, it will fail, if there is more than one, for example:
```
 0   inf  100
100   0   inf
inf  100  inf
```

**Comment by louisabraham** [comment]
Hi, I think this version works (at least on paper):

```python
def linear_sum_assignment_with_inf(cost_matrix):
    cost_matrix = np.asarray(cost_matrix)
    min_inf = np.isneginf(cost_matrix).any()
    max_inf = np.isposinf(cost_matrix).any()
    if min_inf and max_inf:
        raise ValueError("matrix contains both inf and -inf")

    if min_inf or max_inf:
        values = cost_matrix[~np.isinf(cost_matrix)]
        m = values.min()
        M = values.max()
        n = min(cost_matrix.shape)
        # strictly positive constant even when added
        # to elements of the cost matrix
        positive = M - m + np.abs(M) + np.abs(m) + 1
        if max_inf:
            place_holder = (M + (n - 1) * (M - m)) + positive
        if min_inf:
            place_holder = (m + (n - 1) * (m - M)) - positive

    cost_matrix[np.isinf(cost_matrix)] = place_holder
    return linear_sum_assignment(cost_matrix)
```

`place_holder` is chosen such that if its value is selected then the cost will be more (resp. less) than any other solution that doesn't select it. I took `positive` so that the comparisons will yield exact results, but I'm not 100% sure.
