### ISSUE TITLE
Adding support for idx (MNIST) files

### ISSUE THREAD

**Issue by datapythonista** [scipy/scipy#6910]
I'm not sure about the popularity of the idx format for storing matrices, but being used by the popular MNIST dataset [1], I think there is many people who would like to have support for this format from scipy.

I saw in the scipy IO documentation [2] that "SciPy has many modules, classes, and functions available to read data from and write data to a variety of file formats."

Given that there exist at least 4 different projects in pypi to parse the idx format (mostly because of the MNIST repository), I think having something such as scipy.io.loadidx and scipy.io.saveidx could be useful.

I wouldn't mind submitting a pull request if you consider this a useful feature.

1. http://yann.lecun.com/exdb/mnist/
2. https://docs.scipy.org/doc/numpy/reference/routines.io.html

**Comment by rgommers** [comment]
The MNIST data is available in many formats here: http://mldata.org/repository/data/viewslug/mnist-original/ (that's also where ``sklearn`` grabs it from).

Imho there needs to be usage beyond a single dataset to be of interest for inclusion in ``scipy.io``. Are you aware of any other use cases?

**Comment by datapythonista** [comment]
Thank you for the link, it's good to know.

While looking like a standard format to me, I'm not aware or couldn't find other datasets using this format. I agree that it doesn't make sense to add support for the format only to be able to open the MNIST dataset. IMO, the format is the simplest way to save a matrix in its binary representation, that's why I think it could be useful (not just to open that dataset, but let users save in this format).

I think the decision should be made taking into consideration other formats too, such as hdf5 [1]. Which I think it's much more standard, but more complex too.

IMHO, supporting different formats at scipy level, will save the community from implementing different projects for them (as I mentioned before, there are 4 that implement the IDX format). And let other projects such as scikit-learn or other, leverage them, as scipy is a dependency for most of the python data packages. But it's up to you guys, if you find it's a good idea, I'm happy to contribute code.

1. https://support.hdfgroup.org/HDF5/doc/H5.format.html

**Comment by rgommers** [comment]
> IMO, the format is the simplest way to save a matrix in its binary representation, 

There already is such a simple standard format which is widely used: the ``.npy`` format (produced by ``np.save``).

**Comment by datapythonista** [comment]
Fair enough. I agree that is probably not that useful to add idx support at this point (unless it becomes more popular). Thanks for your comments.
