### ISSUE TITLE
Problem in passing drop_rule to scipy.sparse.linalg.spilu

### ISSUE THREAD

**Issue by renemilk** [scipy/scipy#6917]
While trying to use ```scipy.sparse.linalg.spilu``` we've discovered a problem when trying to pass a ```drop_rule```. It seems to reject both a ```bytes``` and a ```str``` object with a ```TypeError```.
[Demo code](https://gist.github.com/renemilk/7e88fc664d1ddc54d2a60b35adc35a33)

Currently our only solution is to not pass ```drop_rule``` at all. Tested on python 3.5.2 and both scipy 0.18.1 and current master.

**Comment by pv** [comment]
Should be fixed in gh-7009
