### ISSUE TITLE
duplicate arg names for ksone and levy_stable methods

### ISSUE THREAD

**Issue by d10genes** [scipy/scipy#6920]
From the documentation some methods have duplicate arg names:

[ksone](http://scipy.github.io/devdocs/generated/scipy.stats.ksone.html#scipy.stats.ksone
)

    moment(n, n, loc=0, scale=1)

[levy_stable](http://scipy.github.io/devdocs/generated/scipy.stats.levy_stable.html#scipy.stats.levy_stable)

    interval(alpha, alpha, beta, loc=0, scale=1)

The latter was reported in #5982

**Comment by rgommers** [comment]
Thanks for the report @d10genes. Let's add ``ksone`` to gh-5982 and close this issue as a duplicate. I'll comment there on the issue itself.
