### ISSUE TITLE
[Feature request] Random unitary matrix

### ISSUE THREAD

**Issue by lesshaste** [scipy/scipy#6921]
scipy already has support for creating a random orthogonal matrix at https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ortho_group.html .  For quantum applications a more common task is to create a random (complex valued) unitary matrix.  

In matlab this is done as follows:

```
function U = randU(n)
X = (randn(n) + i*randn(n))/sqrt(2);
[Q,R] = qr(X);
R = diag(diag(R)./abs(diag(R)));
U = Q*R;
```

It would be great if this functionality could be added to scipy.

**Comment by rgommers** [comment]
This might be doable in a simple way with the current ``ortho_group``, not sure. @philipdeboer maybe you can comment?

**Comment by philipdeboer** [comment]
That seems feasible, yes. I will try to take a closer look at it in a few days.

**Comment by philipdeboer** [comment]
It will be straight-forward to add.

lesshaste, one thing I noted is that the ortho-group generates exactly as many random numbers as needed, while a simpler approach using qr would require more random numbers up front. Is there an analogous issue for unitary matrices? Ie, can we do it with fewer than the 2 * n**2 random numbers used above?

**Comment by lesshaste** [comment]
It's a good question but sadly I don't know the answer.  There is for example http://home.lu.lv/~sd20008/papers/essays/Random%20unitary%20[paper].pdf but I am not sure it has the answer to your question.

**Comment by akhmerov** [comment]
FYI: https://gitlab.kwant-project.org/kwant/kwant/blob/master/kwant/rmt.py#L163 if you need a ready implementation right now.

**Comment by philipdeboer** [comment]
I finally got around to pushing a proposal. I am not very happy with the tests though, from a mathematical point of view. They are not very thorough.

https://github.com/scipy/scipy/pull/7027
