### ISSUE TITLE
pip install scipy on windows 

### ISSUE THREAD

**Issue by h4k1m0u** [scipy/scipy#6925]
Hi,

I'm just wondering why `numpy` can be installed on Windows using `pip`, while for `scipy` it seems that it requires a compilation?

Are there any plans to make this command work on windows on the future: `pip install scipy`?

Thanks.

**Comment by ev-br** [comment]
Duplicate of https://github.com/scipy/scipy/issues/5461 and https://github.com/scipy/scipy/issues/6619. Not sure what the status of the MinGW effort is though.
