### ISSUE TITLE
scipy port of chebfun?

### ISSUE THREAD

**Issue by jason-s** [scipy/scipy#6928]
I'm looking for a Python library that can compute best rational approximations given numerical data (similar to Chebyshev polynomial approximation but for rational functions) and I ran across the [MATLAB Chebfun library](https://github.com/chebfun/chebfun) (see also http://www.chebfun.org/ ) which looks very promising, and is BSD-licensed. This is a library with a long history, facilitated by the legendary Nick Trefethen. (see https://people.maths.ox.ac.uk/trefethen/cacm.pdf)

There is already a port called [pychebfun](https://github.com/pychebfun/pychebfun) but it is GPLv2 licensed.

If anyone is interested perhaps they could either port Chebfun to scipy, or convince the maintainers of pychebfun to submit as part of scipy and [convert licensing so it is compatible with the scipy license](https://github.com/pychebfun/pychebfun/issues/4).

**Comment by person142** [comment]
Whether or not SciPy is the right place for this is open to interpretation. For example, Chebyshev approximations already reside in NumPy. (Which is maybe due to history, but that's how it is.)

**Comment by charris** [comment]
IIRC, chebfun defines functions by their values at a large number of discrete points and gains speed by using the discrete cos transform. Differential operators and such, together with their boundary conditions, are represented as matrices. I haven't looked at the project since it came out (2002), but I don't believe it does rational approximation. That was a long time ago, however, so such facilities may now be available.

**Comment by ev-br** [comment]
> compute best rational approximations given numerical data

There's  https://github.com/scipy/scipy/pull/4674, does it fit the bill?

**Comment by rgommers** [comment]
Cross-linking with gh-6929, which has a link to an implementation of one chuebfun method.

**Comment by jason-s** [comment]
>For example, Chebyshev approximations already reside in NumPy. (Which is maybe due to history, but that's how it is.)

And that's how it should be. The `numpy.polynomial.chebyshev` module is good and should stay as is. They are different than chebfun objects, which have a much richer set of operations, and which benefit from the work done by Nick Trefethen and his group. He's basically the Einstein of numerical analysis.

>but I don't believe it does rational approximation. 

It does, it has the [cf](https://github.com/chebfun/chebfun/blob/development/%40chebfun/cf.m) method.

**Comment by jason-s** [comment]
>>compute best rational approximations given numerical data

>There's #4674, does it fit the bill?

Yes and no. #4674 uses Pade approximations (I think? not sure). Pade approximations are the rational analogue to Taylor series, which rely on the analyticity of a function around a single point to use its derivatives. Similarly, Carathéodory-Fejér rational approximations are the rational analogue to Chebyshev approximation, which seeks to approximate a function over an interval, yielding roughly minimax error over the interval.

A good numerical library would need both. [Chebfun says this](http://www.chebfun.org/docs/guide/guide04.html#48-rational-approximations):

>Chebfun contains four different programs, at present, for computing rational approximants to a function f. We say that a rational function is of type (m,n) if it can be written as a quotient of one polynomial of degree at most m and another of degree at most n.

**Comment by pv** [comment]
Re: rational approximations.
They are imho in scope for scipy.
There are two things: efficient representation and construction. #4674
needs work, since the barycentric repr used has bad accuracy for
extrapolation (chebfun guys jave a paper on this).

6.1.2017 0.47 "Jason Sachs" <notifications@github.com> kirjoitti:

**Comment by person142** [comment]
I'm going to close this; if we really want a SciPy port of Chebfun then we're going to need

(1) A champion
(2) A roadmap

and Github issues are not a particularly great place for roadmaps.

There are also other smaller additions discussed here that we could implement, but those are IMO best addressed through (maybe) separate issues, or even better separate mailing list discussions of concrete work to be done followed by PRs.
