### ISSUE TITLE
scipy implementation of Carathéodory-Fejér method for approximating with rational function

### ISSUE THREAD

**Issue by jason-s** [scipy/scipy#6929]
See http://eprints.maths.ox.ac.uk/926/1/NA-10-03.pdf. MATLAB implementation in https://github.com/chebfun/chebfun/blob/34f92d12ca51003f5c0033bbeb4ff57ac9c84e78/%40chebfun/cf.m (BSD-licensed); I tried to port (I know MATLAB reasonably well) but I'm stuck in the mud trying to understand what it's doing in places, like the `vscale` method.

See also http://www.chebfun.org/examples/approx/CF30.html which contains an earlier, less complicated version.

**Comment by jason-s** [comment]
whee! I was able to get the CF30 function working, by comparing the Matlab code executed running in Octave (I don't have Matlab).

see https://gist.github.com/jason-s/81c57b337ebc39da9eaa30d239116a52 -- I hereby release this to scipy per the SciPy license, in case you find this useful.

**Comment by person142** [comment]
I'm going to close this; I think it comes under the category of "things we would probably accept a PR for" (though it should still be proposed on the mailing list first), but we don't want to keep issues around for every such thing.
