### ISSUE TITLE
uniform_filter1d appears to truncate rather than round when output type is int (ish) 

### ISSUE THREAD

**Issue by pootle** [scipy/scipy#6930]
This means that operations on masks (which are boolean) can exhibit bizarre behaviour, as computed values like 0.999999999 end up as False (zero).

in particular using a range of sizes from 3-10, size= 6 and size=7 will never yield True, even though size = 8 does.

Succinctly described by Warren Weckesser on StackOverflow [here](http://stackoverflow.com/questions/41489650/using-scipy-ndimage-uniform-filter-to-find-stars-in-astro-photo-but-puzzled-by) in answer to my question..

While it is reasonable to expect some minor errors from precision issues, converting some values of 1.00000000e+00 to False and other values to True seems to be stretching 'imprecise' beyond its elastic limit.

Here is Warren's code that demonstrates this:

```
Here's a small one-dimensional input:
In [416]: x
Out[416]: array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0])
Apply uniform_filter1d with increasing sizes:

In [417]: from scipy.ndimage.filters import uniform_filter1d

In [418]: uniform_filter1d(x, 3)
Out[418]: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [419]: uniform_filter1d(x, 4)
Out[419]: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [420]: uniform_filter1d(x, 5)
Out[420]: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [421]: uniform_filter1d(x, 6)
Out[421]: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [422]: uniform_filter1d(x, 7)
Out[422]: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [423]: uniform_filter1d(x, 8)
Out[423]: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [424]: uniform_filter1d(x, 9)
Out[424]: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

```

**Comment by jotasi** [comment]
This is due to floating arithmetic. The [underlying function](https://github.com/scipy/scipy/blob/master/scipy/ndimage/src/ni_filters.c#L292-L360) uses doubles to compute the elements of the result array. The window is moved by adding:
(nextValueAfterWindow-leftMostValueInWindow)/windowSize
Afterward, the result array is converted to the correct dtype which then truncates to integer values in this case which can result in wrong results when we get values very slightly below the next integer.
I'd love to do some work on this but I'm not really sure where to tackle this. One way would be to rewrite the linked function and to include dtype awareness such that integer arithmetic is used for ints instead to prevent rounding errors from happening.

**Comment by pootle** [comment]
Yes, I suspect dtype awareness is probably the right answer, being able to use ints could also yield a significant performance gain especially on ARM or other less floating point proficient machines. 

My current workaround is to get the result back as a float and compare with .99 as I only want the case where I have a contiguous row of True - I am working on an array of bool.

I was also thinking about the specific case of bools (which is where I found the problem - I am processing an array generated by a boolean comparison. I suspect that for bools in particular the entire window should be True to yield a True result, but I'm not sure what the correct mathematical approach should be.

**Comment by stefanv** [comment]
We've had a bug in scikit-image's `threshold_minimum`, resulting from:

```
ndif.uniform_filter1d([46, 37, 45, 42, 51, 52, 51, 52, 60, 55], 3)
```

reporting different outputs on 32-bit and 64-bit platforms:

```
array([43, 42, 41, 45, 48, 51, 51, 54, 55, 56])
array([43, 42, 41, 46, 48, 51, 51, 54, 55, 56])
```

Do you think this issue is related?

**Comment by rgommers** [comment]
@stefanv yes related, verified that your example is fixed by gh-7516

**Comment by stefanv** [comment]
Great, thank you @rgommers and @jaimefrio!
