### ISSUE TITLE
dunn post-hoc test missing [new feature request]

### ISSUE THREAD

**Issue by ybayle** [scipy/scipy#6935]
Hi,
Thank you for your awesome work which I regularly use!
Unfortunately after a [Kruskal-Wallis H-test](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kruskal.html) for independent samples I need to perform a Dunn test which is not already present and does not exist at all in Python (I only managed to found an R implementation [cf this link](https://cran.r-project.org/web/packages/dunn.test/index.html)).

**Comment by josef-pkt** [comment]
Do you have a link or reference for Dunn's test? I don't remember which test it is.

multiple testing corrections and multiple comparison are in statsmodels. I might have ignored Dunn's test because it doesn't maintain the size (i.e. overrejects).
But there are also some multiple comparison, post-hoc test for rank based methods in a statsmodels issue discussion and some gists.

**Comment by rgommers** [comment]
One of the few mentions I can find is https://en.wikipedia.org/wiki/Kruskal%E2%80%93Wallis_one-way_analysis_of_variance. That also says Conover-Iman is a more powerful test, so probably should have that too somewhere.

@josef-pkt there are references in the R docs linked to above:
```
Benjamini, Y. and Hochberg, Y. 1995. “Controlling the False Discovery Rate: A Practical and Pow-
erful Approach to Multiple Testing.”
Journal of the Royal Statistical Society. Series B (Method-
ological)
. 57: 289–300.
Benjamini, Y. and Yekutieli, D. 2001.  “The control of the false discovery rate in multiple testing
under dependency.”
Annals of Statistics
. 29: 1165–1188.
Dunn,  O.  J.  1961.   “Multiple  comparisons  among  means.”
Journal of the American Statistical
Association
. 56: 52–64.
Dunn, O. J. 1964. “Multiple comparisons using rank sums”.
Technometrics
. 6: 241–252.
```

**Comment by rgommers** [comment]
Looks like this would fit better in ``statsmodels`` than in ``scipy.stats``?

**Comment by ybayle** [comment]
Here are some links:

- [stackexchange](https://stats.stackexchange.com/questions/107945/multiple-comparisons-in-a-non-parametric-test)
- [official R package](https://cran.r-project.org/web/packages/dunn.test/index.html)

Beside to Dunn there are Conover-Iman and Dwass-Steel-Citchlow-Fligner tests which are not include  in scipy.

**Comment by josef-pkt** [comment]
ok, this might be https://github.com/statsmodels/statsmodels/issues/852 starting with discussion by alimuldal
His gist after some discussion is at https://gist.github.com/alimuldal/fbb19b73fa25423f02e8
the discussion there switched mostly to kruskal nemenyi test

currently implemented in statsmodels are multiple pvalue corrections including FDR and tukey HSD multiple comparison.

I think the multiple comparison functions can live in statsmodels without duplicate code in scipy.stats.

**Comment by josef-pkt** [comment]
checking the R pdf

```
p.adjustment.methods
# c("none", "bonferroni", "sidak", "holm", "hs", "hochberg", "bh", "by")
```

Those and more are all available in statsmodels. They are just "generic" p-value corrections, while using the distribution from tukey hsd uses the assumption of independent samples for the p-values or critical values.
There is also a MultipleComparison class in statsmodels which has a unadvertised rank and generic pairwise comparison feature. But it does not impose common variance.

So, this definitely looks like statsmodels territory.

**Comment by rgommers** [comment]
Thanks Josef. I agree, so closing this issue. Feel free to continue discussing here, or move over to the statsmodels issue tracker.
