### ISSUE TITLE
interp2d function crashes python

### ISSUE THREAD

**Issue by herronELLINGTON** [scipy/scipy#6949]
I generate a "interp2d" function. I then try to pass in large pandas series objects and it crashes.   If I create a loop and ask this function one point at a time it works but it is slow.   Can someone help me get a fast method working?

Thanks,
--Liam

[SciPyInterp2dCrash.zip](https://github.com/scipy/scipy/files/694841/SciPyInterp2dCrash.zip)

**Comment by pv** [comment]
How does it crash? What is the error message?

**Comment by herronELLINGTON** [comment]
[CrashDebugError.docx](https://github.com/scipy/scipy/files/694859/CrashDebugError.docx)

python.exe crashes and I click "Debug the program".   I attached the visual studio error messages and call stack.

**Comment by herronELLINGTON** [comment]
Any ideas?  Has anyone been able to reproduce the crash I am seeing?

**Comment by person142** [comment]
Yes, I can reproduce it. If I pass in the underlying arrays instead of the Pandas dataframes then I see this message:
```
_fitpack_impl.py:975: RuntimeWarning: No more knots can be added because the additional knot would
coincide with an old one. Probable cause: s too small or too large
a weight to an inaccurate data point. (fp>s)
	kx,ky=1,1 nx,ny=4,4 m=88 fp=643518.400213 s=0.000000
  warnings.warn(RuntimeWarning(_iermess2[ierm][0] + _mess))
```

If you could pare down the example to something that can be reasonably copy-pasted into a comment then it would make it easier for people to take a look.

**Comment by mjlm** [comment]
I have the same problem.

Here is a minimal example:

```
import numpy as np
from scipy.interpolate import interp2d

# Example case: We have a 512 by 512 pixel image:
img = np.random.randn(512, 512)
grid_vec = np.linspace(1, 512, 512)
interp_fun = interp2d(grid_vec, grid_vec, img)

# Lets say we want to evaluate the pixel values in some new grid
# (simulated here as a 512 by 512 grid of random locations):
x_query = np.random.rand(512**2) * 512
y_query = np.random.rand(512**2) * 512

# This will crash python (hard crash, no error message):
img_interp = interp_fun(x_query, y_query)
```

This shouldn't even need that much memory. I use Matlab's interp2 function like that all the time. I'm wondering if I'm using scipy.interpolate.interp2d correctly here.

**Comment by ev-br** [comment]
Can you add `np.seed` to your example, so that it's reproducible?

**Comment by pv** [comment]
This last example calls `interp2d(x_query, y_query)` and tries to produce a 262144 x 262144 result. This would take 0.5 TB of memory, so probably this was not what was intended.

**Comment by pv** [comment]
Similarly, the first example above tries to produce a 88372x88372 array as a result, which would take 62GB. 

However, neither of these should crash, but raise a MemoryError instead.
