### ISSUE TITLE
 Cannot pickle the result of SciPy linear regression

### ISSUE THREAD

**Issue by mangecoeur** [scipy/scipy#6954]
Although `linregress` returns a regular `namedtuple`, it is not pickleable:

```python
import pickle
import numpy as np
from scipy import stats

x = np.arange(0, 10, 0.4)
y = 2 * x + np.random.uniform(size=len(x))
result = stats.linregress(x,y)

pickle.dumps(result)
```

gives

`PicklingError("Can't pickle <class 'scipy.stats._stats_mstats_common.LinregressResult'>: attribute lookup LinregressResult on scipy.stats._stats_mstats_common failed"`

One issue this causes is making it impossible to use in with multiprocessing in joblib ( see https://github.com/joblib/joblib/issues/477), since the regression results cannot be sent back from workers.

I believe this may be caused by the `LinregressResult` being defined inside the linregress function instead of at the module level.

**Comment by lesteve** [comment]
```py
from scipy.stats._stats_mstats_common import LinregressResult
```

although `LinregressResult` is defined in `scipy/stats/_stats_mstats_common.py`: https://github.com/scipy/scipy/blob/3e2351538d7871641b700c998500a1664e5ebb69/scipy/stats/_stats_mstats_common.py#L10.

It does ring a bell that this kind of things can happen when you have circular imports ...

**Comment by pv** [comment]
It's probably already fixed only on master, but not in released versions.

**Comment by lesteve** [comment]
> It's probably already fixed only on master, but not in released versions.

Fixed in master indeed. It did not occur to me that I was looking at the source in master and testing on the released version ...

**Comment by ev-br** [comment]
Indeed, it's fixed in master, so closing. Thanks for the report @mangecoeur , @lesteve 

```
In [1]: import pickle

In [2]: import scipy

In [3]: scipy.__version__
Out[3]: '0.19.0.dev0+d2a8637'

In [4]: from scipy.stats import linregress

In [5]: r = linregress([1, 2, 3], [4, 5, 6])

In [6]: pickle.dumps(r)
Out[6]: "ccopy_reg\n_reconstructor\np0\n(cscipy.stats._stats_mstats_common\nLinregressResult\np1\nc__builtin__\ntuple\np2\n(cnumpy.core.multiarray\nscalar\np3\n(cnumpy\ndtype\np4\n(S'f8'\np5\nI0\nI1\ntp6\nRp7\n(I3\nS'<'\np8\nNNNI-1\nI-1\nI0\ntp9\nbS'\\x00\\x00\\x00\\x00\\x00\\x00\\xf0?'\np10\ntp11\nRp12\ng3\n(g7\nS'\\x00\\x00\\x00\\x00\\x00\\x00\\x08@'\np13\ntp14\nRp15\ng3\n(g7\nS'\\x00\\x00\\x00\\x00\\x00\\x00\\xf0?'\np16\ntp17\nRp18\ng3\n(g7\nS'R\\x06\\xbd\\xb0i\\xbf\\xd8='\np19\ntp20\nRp21\ng3\n(g7\nS'\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00'\np22\ntp23\nRp24\ntp25\ntp26\nRp27\n."

In [7]: rr = pickle.loads(pickle.dumps(r))

In [8]: rr
Out[8]: LinregressResult(slope=1.0, intercept=3.0, rvalue=1.0, pvalue=9.0031631615710586e-11, stderr=0.0)

In [9]: rr == r
Out[9]: True

In [10]: r
Out[10]: LinregressResult(slope=1.0, intercept=3.0, rvalue=1.0, pvalue=9.0031631615710586e-11, stderr=0.0)
```
