### ISSUE TITLE
chunk ID

### ISSUE THREAD

**Issue by cheerjam** [scipy/scipy#6958]
hi 
I create my wave file by logic pro ,and when I open it with scipy wavefile read function,warning appears.I debug it and find that the wave file has a chunk id "LGWV",so that the code cannot recognize it ,is there any solution? Thx!

        while (fid.tell() < fsize):
            # read the next chunk
            chunk_id = fid.read(4)
            if chunk_id == b'fmt ':
                size, comp, noc, rate, sbytes, ba, bits = _read_fmt_chunk(fid)
            elif chunk_id == b'fact':
                _skip_unknown_chunk(fid)
            elif chunk_id == b'data':
                data = _read_data_chunk(fid, comp, noc, bits, mmap=mmap)
            elif chunk_id == b'LIST':
                # Someday this could be handled properly but for now skip it
                _skip_unknown_chunk(fid)
            else:
                warnings.warn("Chunk (non-data) not understood, skipping it.",
                              WavFileWarning)
                **_skip_unknown_chunk(fid)**

**Comment by pv** [comment]
Just ignore the warning or suppress it via Python's warnings module.
