### ISSUE TITLE
scipy.interpolate.LSQUnivariateSpline - check for increasing array x ?

### ISSUE THREAD

**Issue by psiehr** [scipy/scipy#6959]
[LSQUnivariateSpline](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.LSQUnivariateSpline.html)
Documentation: 
x : (N,) array_like
Input dimension of data points – **must be increasing**

--- 
In my opinion this should throw an error, if not true. 
I just had the case where I got a solution very, very close to the correct solution. 
And I noticed that only by accident.
some_spline1.get_coeffs() -> [-0.25356015 -0.2431301  -0.22818767  0.22818767  0.2431301   0.25356015]
some_spline2.get_coeffs() -> [-0.23886737 -0.26614876 -0.18187211  0.17906816  0.28409979  0.23533798]

Here is a minimal example, in which you can see what happens if you insert a non-increasing array.
Assume fitting a curve through some measured values, where you have several (here: 2) y-values for the same x-value.

```python
# -*- coding: utf-8 -*-

from scipy.interpolate import *
import scipy
import numpy as np
import matplotlib.pyplot as plt

# Data:  f(x) = x
# Distortion: +/- 0.5   ->  f(0) = -0.5 / 0.5
x1 = np.array([-1, -1, 0, 0, 1, 1])
x2 = np.array([-1, 0, 1, -1, 0, 1])
y1 = np.array([-0.5, -1.5, 0.5, -0.5, 1.5, 0.5])
y2 = np.array([-0.5, 0.5, 1.5, -1.5, -0.5, 0.5])

# Fit
t = [0.0]
spl1 = scipy.interpolate.LSQUnivariateSpline(x1, y1, t, k=1)
spl2 = scipy.interpolate.LSQUnivariateSpline(x2, y2, t, k=1)

# Plot
fig = plt.figure(1)
plt.plot(
    x1,
    y1,
    color='w',
    marker='o',
    fillstyle='full',
    markeredgecolor='k',
    markersize=16,
    markeredgewidth=2.0,
    linewidth=2.5,
    label='data1')
plt.plot(
    x2,
    y2,
    color='w',
    marker='x',
    fillstyle='full',
    markeredgecolor='k',
    markersize=16,
    markeredgewidth=2.0,
    linewidth=2.5,
    label='data2')
xplot = np.linspace(-2, 2, 50)
plt.plot(xplot, spl1(xplot), color='r')
plt.plot(xplot, spl2(xplot), color='b')

plt.show()
```

In the plot the red curve is correct.
What happened to the blue one? 

Since t=[0.0] the function  LSQUnivariateSpline should split the input array x1 and x2 in two intervals (I_1, I_2) at the first appearance of 0.0.  
For x1:  x1 = [-1, -1, 0, 0, 1, 1]   -> I_1=[-1, -1, 0],  I_2=[0, 0, 1, 1]
For x2:  x2 = [-1, 0, 1, -1, 0, 1]   ->  I_1=[-1, 0], I_2=[0, 1, -1, 0, 1]

I am not sure if this is true.

Note that there is a little wiggle in the blue curve around x=0. 
No explanation for that so far.

![figure_1](https://cloud.githubusercontent.com/assets/14997999/21932662/02a233fa-d9a2-11e6-9f9b-12b0f6460ce1.png)

**Comment by ev-br** [comment]
Fixed by https://github.com/scipy/scipy/pull/7030, closing.
