### ISSUE TITLE
serious bug in minimize_scalar when method='Bounded'

### ISSUE THREAD

**Issue by y0m0y** [scipy/scipy#6960]
>>> import scipy.optimize as optm
>>> def ff(x): return 5*x-1 if x<0.2 else 0
... 
>>> optm.minimize_scalar(ff,bounds=(0,1), method='Bounded')
     fun: 0
 message: 'Solution found.'
    nfev: 25
  status: 0
 success: True
       x: 0.99999403913901341

The obvious correct answer is that the minimum is at x=0 with the function value being -1. Note the fact ff(x) is not differentiable here is not crucial, it happened to me for a smooth function with a flat plateau.

**Comment by pv** [comment]
Local minimizers return local minima. Any point on a flat plateau is a
local minimum.

**Comment by y0m0y** [comment]
This could happen to an increasing function with almost zero slopes. The example shows at least the code is fragile. I, perhaps most people, would expect the code to test whether the two endpoints are local minima, eg. evaluate at x0 and x0+delta. That was one of the reasons I chose this particular method versus other methods. I hope this improvement, which is simple to code, will be made in future releases, so that what tripped me won't happen to other people. Thank you.
