### ISSUE TITLE
Scipy contains shebang pointing to /usr/bin/python and /bin/bash which are problematic

### ISSUE THREAD

**Issue by ssalonen** [scipy/scipy#6961]
Hi

We are packaging scipy pre-installed in a virtualenv using a rpm. RPM has a "convenient" feature to automatically scan for script files with shebang and adding those as requirements of the resulting rpm. For more information, see [this blog post](http://www.legendiary.at/2013/03/20/rpmbuild-shebang-auto-required-packages/).

Most of the scipy scripts use

````bash
#!/usr/bin/env python
````

which rpm resolves to whatever is in the PATH.

However, some of the packages point to hard-coded path of python:
````bash
$ grep '^#!' **/*.py|grep -v '/usr/bin/env python'
scipy/special/generate_ufuncs.py:#!/usr/bin/python
scipy/special/tests/test_basic.py:#!   Means test is segfaulting
scipy/special/utils/makenpz.py:#!/bin/bash
tools/win32/detect_cpu_extensions_wine.py:#!/usr/bin/python
````

I would propose that the above scripts (excluding `test_basic.py` which does not really have a shebang) would be changed to use `#!/usr/bin/env python` and `#!/usr/bin/env bash`, as approriate. 

This change would make the rpm process resolve python and bash using whatever is in the path. For example, with CentOS 6, the system python (in `/usr/bin/python`) is python 2.6, although the `python` in PATH could very well be `python2.7` or newer. In our case the virtualenv is activated during the build, and thus `#!/usr/bin/env python` would resolve to the correct interpreter.

The additional benefit is that the scripts are more cross-platform.

I'm willing to submit a pull requests if you agree with the fix?

Best,
Sami Salonen

Numpy issue of the same topic: https://github.com/numpy/numpy/issues/8472
Pandas issue of the same topic: https://github.com/pandas-dev/pandas/issues/15131

**Comment by pv** [comment]
There's probably no problem in doing that. Note however that those
scripts are never run unless you are doing development.

**Comment by ssalonen** [comment]
Thanks for the quick response!

Yeah, I understand they are meant for development only. I believe they are still marked to be installed and thus cause the described issue with our way of rpm packaging...

I will come back with PR.

Best
Sami

**Comment by pv** [comment]
At the same time, you can perhaps remove all shebang lines from the "test_*.py" files --- these files should never have executable bit set.

**Comment by ssalonen** [comment]
PR submitted with the proposed changes.
