### ISSUE TITLE
Scipy cannot find openblas binaries on windows

### ISSUE THREAD

**Issue by AtheMathmo** [scipy/scipy#6969]
Hey!

I'm trying to install scipy on windows. I downloaded the [openblas windows binaries](http://www.openblas.net/) and linked to them in my system path: (`C:\Program Files\OpenBLAS\bin;C:\Program Files\OpenBLAS\lib`).  I'm under the impression that [openblas should include LAPACK](https://github.com/xianyi/OpenBLAS/issues/203). However when I try to install scipy I see the following error:

```
raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
```

I've spent a while digging around but haven't really found any relevant information that might help. If I can answer any other questions please let me know.

**Comment by pv** [comment]
Please read https://www.scipy.org/install.html and https://www.scipy.org/scipylib/building/
If those don't help, you can ask a question on stackoverflow.com

**Comment by AtheMathmo** [comment]
I've read both of these, but thank you for providing them.

At this point it seems easier to remove my existing python environment and go with Anaconda. Feel free to close this issue.

**Comment by rgommers** [comment]
That's definitely easier, especially on Windows.
