### ISSUE TITLE
Weird behavior for sparse multiply with dense.

### ISSUE THREAD

**Issue by shawnjhenry** [scipy/scipy#6981]
Hi,

I have a large `csr_matrix` `X` of size 25000x392000 with about 0.08% non-zero entries, and I have a dense vector `v` of size 1x392000 and I want to multiply each row of `X` by.  I would expect this to be extremely fast since row indexing for csr is fast, but I keep getting `Killed: 9` when calling `X.multiply(v)`.  I verified that three other methods of doing this multiply (creating a diagonal `lil_matrix` from `v` and using a matrix multiplication, doing the row-wise multiply manually in python to construct the `data` matrix for the output `csr_matrix`, and converting `v` to a `csr_matrix` before calling `X.multiply(v)`) all work. 

I assume that the issue is that it's trying to allocate a 25000x392000 dense matrix for the output, but that behavior doesn't make any sense.  An element-wise multiply between a sparse matrix and *anything* will still be sparse.  Can anyone verify that this is actually the issue and, if so, if it might be possible to change the behavior of `multiply` to have sparse output for all input types?  The second method I mentioned above is, by far, the fastest, but I suspect it could be even faster if it happened in the backend.

Thanks,
Shawn

**Comment by person142** [comment]
Fixed by https://github.com/scipy/scipy/pull/6750?

**Comment by shawnjhenry** [comment]
I don't think so, unless it's not in the latest stable release.  I just upgraded and had the same issue.  I haven't used SciPy much - are there nightlies I could try that might have the fix?

**Comment by perimosocordiae** [comment]
It's not in the latest stable release yet.

Luckily, the 0.19 release is coming soon™️, so you can either:
 - wait a bit (a few weeks, probably) and get the fix then
 - build scipy from the current master branch
 - copy the changes from gh-6750 directly into your installed `scipy/sparse/compressed.py` file

(The last option is a hack, of course, but it avoids having to set up the required tools for building scipy from source.)

**Comment by shawnjhenry** [comment]
I think for now using my python indexing hack will be sufficiently fast to achieve what I want for now.  I will have to remember to change it when 0.19 comes out.  Thanks for the info!
