### ISSUE TITLE
ode: state vector returned to solout is not copy

### ISSUE THREAD

**Issue by gauteh** [scipy/scipy#6987]
Hi, I do not know if this is intentional, but it caused quite a bit of confusion. I tried to save the output of the dopri5 solver using the `ode()` interface and `set_solout ()`.  

The y that is passed to solout and which I stored in a list seems to be a reference that keeps getting updated. If I do not make a copy of it before storing it in the list the previous entries may get changed by the integrator in the next integration steps.

**Comment by gauteh** [comment]
Right, so I discoverd that expoliting this is the only way to update the current state vector from within solout (during event detection). I though I could use set_initival_values, but it seems to be ignored.

**Comment by j-bowhay** [comment]
Closing as this code is legacy and also passing copies would be too costly to performance
