### ISSUE TITLE
Apparent unstable behavior on even ordered splines only

### ISSUE THREAD

**Issue by str4w** [scipy/scipy#6988]
Hi,

While experimenting with various orders of interpolation, it appears that the even ordered interpolants are much more unstable than the odd ordered.   I don't know why that would be.  Here is a minimal example - admittedly, the data is quantized.  Nonetheless, the cubic and quintic interpolators do something I think is reasonable with it, and the quadratic and quartic bounce around a lot in the flat areas.

Code to reproduce:
```
"""
Demonstrate unstable behavior in even ordered spline fits
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d

data=[140, 148, 140, 148, 140, 148, 132, 148, 148, 156, 156, 164, 164, 172,
      164, 172, 172, 172, 172, 172, 172, 172, 172, 164, 172, 164, 164, 164,
      164, 156, 156, 156, 156, 148, 148, 140, 140, 140, 140, 140, 132, 132,
      124, 124, 116, 116, 108, 108, 108, 108, 100, 100, 100, 100,  92,  92,
      92,  92,  92,  92,  84,  92,  84,  84,  92,  84,  76,  84,  84,  68,
      60,  68, 60,  60,  60,  68,  52,  52,  52,  44]

xs=np.asarray(range(len(data))) 
ys=np.asarray(data) 
f2=interp1d(xs,ys,kind='quadratic')
f3=interp1d(xs,ys,kind='cubic')
f4=interp1d(xs,ys,kind=4)
f5=interp1d(xs,ys,kind=5)

xout=np.linspace(10,len(data)-10,100)
y2=f2(xout)
y3=f3(xout)-15
y4=f4(xout)-30
y5=f5(xout)-45

plt.plot(xs,ys,'bo',xout,y2,'r-',xout,y3,'g-',xout,y4,'m-',xout,y5,'k-')
plt.title("Different orders of interpolation")
plt.legend(["data","2nd","3rd","4th","5th"])
plt.show()
```
![figure_1](https://cloud.githubusercontent.com/assets/1618555/22404603/51f9d6b2-e602-11e6-8947-67db79b709b1.png)

**Comment by pv** [comment]
Is this a known property of even-order B-spline interpolants? Docstring
of splrep contains the statement "Even values of k should be avoided
especially with small s values." --- for interpolation s=0, although
interp1d computes the interpolants in a different way, not using splrep.

**Comment by ev-br** [comment]
I think it's not only b-splines, even order ppform interpolators would oscillate just the same. Having flat sections does not help either. This could be a nice tutorial type topic. Are you interested in working on one @str4w ?

**Comment by str4w** [comment]
Sure in principle, although it sometimes takes me a while to find time to complete these things.  What did you have in mind? Also, what exactly do you mean order ppform?

**Comment by ev-br** [comment]
"even order ppform", poor wording, sorry. A spline representation in the piecewise polynomial basis (as opposed to the b-spline basis), where the polynomials are of even order.

My off-the-cuff suggestion was to add some discussion to the interpolate tutorial or as a separate notebook to the SciPy Cookbook (which is a separate repo)

**Comment by str4w** [comment]
It's a good idea, and perusing these notebooks has helped me understand what I ought to have used instead of scipy interpolate.  In the meantime, I put together a notebook showing some examples.  

https://github.com/str4w/StrangeInterpolators/blob/master/Strange%20Interpolators.ipynb

My current understanding amounts to a bunch of examples of behaviour I don't really understand, which of limited help to anyone.  If and when I get further, I'll send a pull request to those doc sites.

**Comment by ev-br** [comment]
So, to summarize the issue (and illustrations in the linked notebook): even order splines are prone to oscillations. Having flat sections does not help, too. With flat or almost flat sections and sharp jumps need to watch out for oscillations even for odd-order splines: the requirement that the 2nd derivative is continuous makes it difficult for the spline to "absorb" large changes in the 2nd derivative, it effectively spreads it over --- which leads to oscillations. A possible user solution is to use monotone interpolants (Pchip or Akima1D) which do not impose constraints on the second derivative.

All in all, other then mentioning it in the documentation, in general terms (which I'll do elsewhere), there is not much we can do here. So let's close and add a label to make it hopefully more discoverable. Thanks @str4w anyway!
