### ISSUE TITLE
Scipy wheel tests timing out on OSX - suggestions?

### ISSUE THREAD

**Issue by matthew-brett** [scipy/scipy#6989]
The standard (not full) scipy tests are timing out on travis-ci:

https://travis-ci.org/MacPython/scipy-wheels/jobs/196506688#L259

Does anyone have a feeling for which tests I should skip to give them a better chance of getting in under the time limit?

**Comment by ev-br** [comment]
Yeah, we're started hitting the time limit of the full test suite on regular CI jobs too. Might be time to have a look timings per submodule.
Off the top of my head, there is a test in stats checking the broadcasting of `rvs`. Some distributions are *very* slow, probably could be marked as such. Also there was some work on `linalg.solve`, maybe check the size of matrices.

**Comment by ilayn** [comment]
For `linalg.solve`, the number of tests are increased but they are mostly 10x10 linear eq problems which are pretty fast. Except the last test named `test_all_type_size_routine_combinations()`. It generates 1000x1000 matrices and solves  `Ax = b` for 16 times. On my machine, that adds up to about a second. 

Please let me know if it is dragging on TravisCI setup.

**Comment by andyfaff** [comment]
If we have the machinery to print out the test time for each module I can
run the tests on my home machine to figure out what's tardy.

**Comment by rgommers** [comment]
We don't have machinery AFAIK, but in the past the culprits were usually obvious by just running tests with ``verbose=2`` and writing down names of tests that take long enough that you can read them. primitive but it works

**Comment by andyfaff** [comment]
Just gone through all the modules on my computer (Quadcore 10.12.3).
Running tests as `python runtests.py -s stats`, off master in Python 3.5.2. `stats` is the worst time offender, taking 4 times as long as the next. `scipy.integrate` has one failure (#7038). `scipy.sparse` has lots of errors then segfaults, so I can't test that fully.

cluster	2.272
constants	0.03
fftpack	3.539
integrate	3.013
interpolate	4.029
io	4.228
linalg	11.39
misc	0.298
ndimage	2.097
odr	0.029
optimize	13.628
signal	7.357
sparse	
spatial	14.889
stats	65.995

**Comment by rgommers** [comment]
You're missing ``special`` - that's probably the worst one with ``test('full')`` because of the extended testing against ``mpmath``.

**Comment by rgommers** [comment]
And for all modules it's the time taken by ``test('full')`` that matters here for the CI timeouts.

**Comment by andyfaff** [comment]
The test:

`test_continuous_basic.test_rvs_broadcast(<scipy.stats._continuous_distns.gausshyper_gen object at 0x10a957f98>, 'gausshyper', [array([[[ 13.7637716]]`

seems to be a bad offender

**Comment by ev-br** [comment]
I think we could just skip the test for this distribution.

**Comment by andyfaff** [comment]
I've just come across the `nose-timer` package, available from PyPI. This is normally invoked as `nosetests --with-timer`, but to do that I'm going to have to navigate to each test subdirectory in scipy source directory (unless anyone knows otherwise).
How do I get the full tests to run with `nosetests`, not just the fast ones?

**Comment by Eric89GXL** [comment]
In `HACKING.txt` there is mention of using `SCIPY_XSLOW`, but that's not what we're talking about here.

The `numpy.testing.decorators.slow` just sets `x.slow = True`, so things like `nosetests -a "slow"` should at least allow you to run only the slow tests. So if you're working with `nose` directly you can probably do that.

If using `runtests.py` it looks like you can use `--mode full`.

**Comment by ev-br** [comment]
https://github.com/scipy/scipy/pull/7040 disables two worst offenders in `test_rvs_broadcast`. On my laptop the wallclock time change is round about 60s -> 1.2s.

**Comment by andyfaff** [comment]
[Test times for the sparse module](https://gist.github.com/andyfaff/6c9d66301ce926282c4a25613747a93e). Run by `nosetests --with-timer -A slow` and `nosetests --with-timer` from within the `scipy/sparse/tests` directory. I'll run the rest of the modules tonight.

**Comment by perimosocordiae** [comment]
The `test_setdiag` method has some pretty impressive combinatorial explosion, and it gets run for each sparse matrix class (including non-canonical variants). I've opened a PR which pares it down a bit.

**Comment by andyfaff** [comment]
[slow stats tests](https://gist.github.com/andyfaff/d90e9ccb7c8b60ca448baebb06dd6f0d)
[fast stats tests](https://gist.github.com/andyfaff/24cc4ddde4149b77bfba3a98652880b4#file-stats_tests_fast)

**Comment by andyfaff** [comment]
[fast spacial tests](https://gist.github.com/andyfaff/71c00ed5530fce1dda69ae4eea99554a) - `test_qhull.TestUtilities.test_more_barycentric_transform` takes ~15s.
[slow spacial tests](https://gist.github.com/andyfaff/c132b5d8bcc025a55735d934d0996deb)

**Comment by rgommers** [comment]
Nice, thanks @andyfaff. I seem to remember having tried ``nose-timer`` in the past and it not working, but works quite well now.

**Comment by andyfaff** [comment]
It'd be nice to be able to do that via runtests.py though.

**Comment by rgommers** [comment]
> It'd be nice to be able to do that via runtests.py though.

Agreed. Cleaning up the test names in the ``nose-timer`` output (``stats`` tests have super long names) and having an easy way to see per-module and overall top times would be useful too. I'll add it to the GSoC pytest idea in case no one gets around to it earlier.

**Comment by andyfaff** [comment]
I'm not quite clear on the rationale for transitioning to pytest. Not sure if `nose-timer` is solely designed for nose or if it could be modified to work with pytest. It's MIT/BSD licenced and a single file, so we could probably vendor it if necessary.

**Comment by rgommers** [comment]
> I'm not quite clear on the rationale for transitioning to pytest

Because ``nose`` is unmaintained, and the follow-up effort ``nose2`` also doesn't have good momentum. https://github.com/scipy/scipy/wiki/GSoC-2017-project-ideas#make-the-scipy-test-suite-work-with-pytest

I'm less familiar with ``pytest``, but I'd expect it to have similar functionality as ``nose-timer`` available.

**Comment by Eric89GXL** [comment]
Looks like it's built in directly with `--durations`:

http://doc.pytest.org/en/latest/example/simple.html#profiling-test-duration

**Comment by ev-br** [comment]
To echo what Ralf is saying: to me, it's a transition to pytest specifically; it's just looking for an alternative for when nose no longer runs on e.g. next python version. And just so happens that pytest is nearly the only option --- or do you see better ones @andyfaff ?

**Comment by Eric89GXL** [comment]
If we are looking at `nose` alternatives, I can add that I once changed a codebase over from `nose` to `py.test`, and most of the tests themselves did not require any modification. It's also nice long term because you can simply do e.g. `assert a == b` and `py.test` is smart enough to give some nice output, but you can also choose to continue with `assert_equal` if you want.

**Comment by andyfaff** [comment]
@ev-br, I know a lot less about testing frameworks than you. Pytest sounds
fine to me.

**Comment by andyfaff** [comment]
Are we good to close this now?

**Comment by matthew-brett** [comment]
I solved my original problem by dropping the i386 builds from the OSX wheel recipe.  I guess the remaining question is - is there more that should be done to speed up the tests?

**Comment by rgommers** [comment]
> is there more that should be done to speed up the tests?

I think yes - would like to include building better diagnostics a part of the proposed GSoC project. Now we never detect people adding slow tests in PRs, and only find out when TravisCI build matrix entries start timing out.

**Comment by rgommers** [comment]
With https://github.com/numpy/numpy/pull/9268 it's now possible to use ``nose-timer`` from within ``scipy.test()``.

``$ python -c "import scipy as s; s.test(extra_argv=['--with-timer', '--timer-top-n', '40'])"`` gives:

    [success] 4.16% test_kdeoth.test_kde_2d: 10.4043s
    [success] 4.01% test_circular_imports.test_importing_submodules: 10.0241s
    [success] 3.76% test_linsolve.TestSpsolveTriangular.test_random: 9.3941s
    [success] 3.21% test_basic.TestSolve.test_all_type_size_routine_combinations: 8.0365s
    [success] 1.68% test_kdtree.test_ckdtree_box: 4.1913s
    [success] 1.34% test_basic.TestLstsq.test_random_complex_exact: 3.3539s
    [success] 1.27% test_kdtree.test_ckdtree_count_neighbous_multiple_r: 3.1757s
    [success] 1.08% test_lsq_linear.TestTRF.test_sparse_bounds: 2.7055s
    [success] 1.06% test_multivariate.TestMultivariateNormal.test_broadcasting: 2.6459s
    [success] 1.01% test_ivp.test_integration_sparse_difference: 2.5286s
    [success] 0.95% test_distance.TestCdist.test_cdist_calling_conventions: 2.3696s
    [success] 0.95% test_least_squares.TestTRF.test_with_bounds: 2.3655s
    [success] 0.88% test_mpmath.test_beta: 2.1963s
    [success] 0.86% test_mstats_basic.TestCorr.test_kendalltau: 2.1471s
    [success] 0.83% test_basic.TestLstsq.test_random_exact: 2.0681s
    ...

And ``$ python -c "import scipy as s; s.test('full', extra_argv=['--with-timer', '--timer-top-n', '40'])"`` gives:


    [success] 2.59% test_mpmath.TestSystematic.test_betainc: 18.8465s
    [success] 1.57% test_mpmath.TestSystematic.test_besselk_complex: 11.4441s
    [success] 1.47% test_mpmath.TestSystematic.test_ellipeinc_largephi: 10.6773s
    [success] 1.45% test_kdeoth.test_kde_2d: 10.5660s
    [success] 1.44% test_mpmath.TestSystematic.test_erfc: 10.4603s
    [success] 1.33% test_mpmath.TestSystematic.test_ellipkinc_largephi: 9.7023s
    [success] 1.31% test_mpmath.TestSystematic.test_gamma_complex: 9.5356s
    [success] 1.28% test_mpmath.TestSystematic.test_e1_complex: 9.3317s
    [success] 1.28% test_linsolve.TestSpsolveTriangular.test_random: 9.3143s
    [success] 1.27% test_mpmath.TestSystematic.test_bessely_complex: 9.2363s
    [success] 1.22% test_cdflib.TestCDFlib.test_chndtrix: 8.8526s
    [success] 1.18% test_circular_imports.test_importing_submodules: 8.5881s
    [success] 1.08% test_mpmath.TestSystematic.test_besseli_complex: 7.8567s
    [success] 1.06% test_basic.TestSolve.test_all_type_size_routine_combinations: 7.6842s
    [success] 1.04% test_continuous_basic.test_moments(<scipy.stats._continuous_distns.skew_norm_gen object at 0xa8a1156c>, (4.0,), array( 0.77406172), array( 0.40082845), 'skewnorm'): 7.5791s
    [success] 1.01% test_mpmath.TestSystematic.test_rgamma_complex: 7.3574s
    [success] 0.98% test_mpmath.TestSystematic.test_struveh: 7.1362s
    [success] 0.94% test_mpmath.TestSystematic.test_erfc_complex: 6.8292s
    [success] 0.86% test_mpmath.TestSystematic.test_legenp_complex_2: 6.2849s
    [success] 0.86% test_mpmath.TestSystematic.test_legenp_complex_3: 6.2344s
    [success] 0.79% test_mpmath.TestSystematic.test_ellipeinc: 5.7348s
    [success] 0.77% test_mpmath.TestSystematic.test_erfi_complex: 5.5759s
    [success] 0.76% test_stats.TestFisherExact.test_large_numbers: 5.5492s
    [success] 0.75% test_mpmath.TestSystematic.test_erf_complex: 5.4853s
    [success] 0.75% test_mpmath.TestSystematic.test_besselj_complex: 5.4764s
    [success] 0.74% test_decomp.TestSVDVals.test_crash_2609: 5.3876s
    [success] 0.74% test_mpmath.TestSystematic.test_cospi_complex: 5.3868s
    [success] 0.73% test_mpmath.TestSystematic.test_beta: 5.2860s
    [success] 0.72% test_mpmath.TestSystematic.test_legenp: 5.2741s
    [success] 0.72% test_mpmath.TestSystematic.test_jacobi_int: 5.2541s
    [success] 0.72% test_mpmath.TestSystematic.test_ellipkinc: 5.2164s
    [success] 0.69% test_mpmath.TestSystematic.test_binom: 5.0314s
    [success] 0.67% test_mpmath.TestSystematic.test_expm1_complex: 4.9052s
    [success] 0.66% test_continuous_basic.test_cont_basic_slow(<scipy.stats._continuous_distns.genexpon_gen object at 0xa8a5298c>, 0.5, (9.13259764654189, 16.23195660059063, 3.2819552690843983), (0, 1), [<bound method genexpon_gen.pdf of <scipy.stats._continuous_distns.genexpon_gen object at 0xa8a5298c>>, <bound method genexpon_gen.logpdf of <scipy.stats._continuous_distns.genexpon_gen object at 0xa8a5298c>>, <bound method genexpon_gen.cdf of <scipy.stats._continuous_distns.genexpon_gen object at 0xa8a5298c>>, <bound method genexpon_gen.logcdf of <scipy.stats._continuous_distns.genexpon_gen object at 0xa8a5298c>>, <bound method genexpon_gen.logsf of <scipy.stats._continuous_distns.genexpon_gen object at 0xa8a5298c>>]): 4.8259s
    [success] 0.65% test_mpmath.TestSystematic.test_sinpi_complex: 4.7667s
    [success] 0.63% test_mpmath.test_spence_circle: 4.6083s
    [success] 0.63% test_mpmath.TestSystematic.test_spence_complex: 4.5671s
    [success] 0.61% test_basic.TestBessel.test_iv_cephes_vs_amos_mass_test: 4.4555s
    [success] 0.60% test_mpmath.TestSystematic.test_wrightomega: 4.3366s
    [success] 0.57% test_mpmath.TestSystematic.test_gegenbauer_int: 4.1678s

**Comment by rgommers** [comment]
The ``mpmath`` tests take close to 50% of the total test suite runtime. We can make them a lot faster by reducing the number of points tested by default, for example using ``n=500`` instead of ``n=5000`` in the ``MpmathData.__init__`` signature reduces times of the ``special tests by about 60%. So we could do that in the ``'full'`` tests by default, and run with ``n=5000`` in a separate TravisCI build matrix entry.

Thought? Other ways of speeding up those tests?

**Comment by pv** [comment]
That's possible. You can e.g. make it use a smaller `n` unless 
SCIPY_XSLOW environment variable is set, like the 
scipy._lib._testutils.xslow decorator does, so that we don't increase 
the number of test tuning flags available. Maybe something like:
.
```
     try:
         is_xslow = int(os.environ.get('SCIPY_XSLOW', '0'))
     except ValueError:
         is_xslow = False

     # Use fewer points if XSLOW is not set.
     n = 5000 if is_xslow else 100
```

**Comment by pv** [comment]
Majority of time I think is spent inside mpmath, so it cannot be sped up 
except by precomputing and storing the mpmath results, or computing 
fewer results. The results probably would have to be checked in the 
repository, which I wouldn't want to start doing.

**Comment by rgommers** [comment]
Thanks @pv. Reusing ``SCIPY_XSLOW`` makes sense, will try now.

**Comment by pv** [comment]
Maybe it makes sense to add `--xslow` to runtests.py or something.

**Comment by rgommers** [comment]
Yes. And ``--timer`` as well.

**Comment by rgommers** [comment]
Time gain is not linear in number of points: n=5000 to 500 is ~60% speedup, and then 500 to 100 is only another ~15%. So going with 500 I think.
