### ISSUE TITLE
Division by zero in linregress()

### ISSUE THREAD

**Issue by ebw44** [scipy/scipy#6991]
If the size of the data used for the regression is 2, line 107 of _stats_mstats_common.py
raise an exception (or a warning) because df is zero. One fix could be to have sterrest equal 0 in that case as the linear regression would be exact. 

PS: It could look overkill to use a linear regression when you have two points, but there is also no reason to have a special case.

**Comment by ev-br** [comment]
Fixed in gh-7007.
