### ISSUE TITLE
memory leak in scipy.signal.welch

### ISSUE THREAD

**Issue by y0va** [scipy/scipy#6993]
With version 0.16.0 the attached code uses excessive memory and becomes very slow. With Scipy 0.15.1 the code is running smoothly.

[fftglob.py.txt](https://github.com/scipy/scipy/files/743044/fftglob.py.txt)

**Comment by e-q** [comment]
I am not able to run your attached code without the relevant data files. I've run the following code locally to try and reproduce this:

```python
import time
import numpy as np
from scipy.signal import welch

nsamp = 10**6
nperseg = 1000
niter = 300
x = np.random.randn(nsamp)

start_time = time.time()
for _ in range(niter):
    _ = welch(x, nperseg=nperseg)

end_time = time.time()
print('{} sec'.format(end_time - start_time))
raw_input() # Check process memory usage here
```

I only tried two iteration sizes, but don't see any evidence of slowdown or memory leakage.

Version |`niter` | Final Memory Footprint (MB) | Execution time (sec) | Time per iter(ms)|
-|-|-|-|-|
0.15.1| 300 | 32 | 49 | 133 
0.15.1| 1000 | 32 | 177 | 177 
0.16.0| 300 | 50  | 19 | 63
0.16.0| 1000 | 50  | 60 | 60

If you are able to upload some data somewhere, or write a self-contained example that shows the issue, we can reopen the issue and continue investigating.

**Comment by y0va** [comment]
Sorry for not providing the data. You can find the headerless wav
files I used here:

https://datengarten.allmende.io/public.php?service=files&t=ee8dbb652dc32f85334c2c57107bbe84

Am Tue, 31 Jan 2017 14:03:39 -0800
schrieb Eric Quintero <notifications@github.com>:

> I am not able to run your attached code without the relevant data
> files. I've run the following code locally to try and reproduce this:
> 
> ```python
> import time
> import numpy as np
> from scipy.signal import welch
> 
> nsamp = 10**6
> nperseg = 1000
> niter = 300
> x = np.random.randn(nsamp)
> 
> start_time = time.time()
> for _ in range(niter):
>     _ = welch(x, nperseg=nperseg)
> 
> end_time = time.time()
> print('{} sec'.format(end_time - start_time))
> raw_input() # Check process memory usage here
> ```
> 
> I only tried two iteration sizes, but don't see any evidence of
> slowdown or memory leakage.
> 
> Version |`niter` | Final Memory Footprint (MB) | Execution time (sec)
> | Time per iter(ms)| -|-|-|-|-|
> 0.15.1| 300 | 32 | 49 | 133 
> 0.15.1| 1000 | 32 | 177 | 177 
> 0.16.0| 300 | 50  | 19 | 63
> 0.16.0| 1000 | 50  | 60 | 60
> 
> If you are able to upload some data somewhere, or write a
> self-contained example that shows the issue, we can reopen the issue
> and continue investigating.
> 
>

**Comment by y0va** [comment]
On another machine running ubuntu 14.04 python terminates with this error using scipy 0.16.0: 
[ubuntu14.04.txt](https://github.com/scipy/scipy/files/744549/ubuntu14.04.txt)
But runs smoothly with scipy 0.15.1

**Comment by y0va** [comment]
This one kills my system. Seems to be because of the setting nfft. I need it to be set to samplerate=44100.




```
import time
import numpy as np
from scipy.signal import welch

nsamp = 10**6*3
nperseg = 512
nfft=20000
niter = 300

x = np.random.randn(nsamp)
for i in range(1000) : print x[i]
start_time = time.time()
welch(x, nperseg=nperseg,nfft=nfft, axis=0)

end_time = time.time()
print('{} sec'.format(end_time - start_time))
raw_input() # Check process memory usage here
```

**Comment by person142** [comment]
@y0va probably good to try with more recent versions of SciPy (0.18.1 or master) to make sure the problem is still present.

**Comment by pv** [comment]
It's still present --- I guess the issue is that it tries to take fft of 
a huge array.

**Comment by y0va** [comment]
@e-q perhaps you want to reopen the issue?

**Comment by e-q** [comment]
@pv is right. Prior to 0.16, the mean PSD was calculated on a running basis. I.e. taking FFTs of the windowed segments one at a time, and adding them to a running cumulative sum, and dividing at the end. However, this method is unsuitable for calculating things like spectrograms where we want to keep the time information. 

In 0.16, we changed to an algorithm that uses numpy striding tricks to create a 2d array of the input data efficiently, and only calls the FFT function once. This is generally quite a bit faster, but at the cost of storing the 2D FFT array, which is probably what you ran into.  So, I wouldn't say that this is a memory leak, but rather that the code is more memory hungry now. 

With `nsamp = 10**6*3, nperseg = 512, nfft=20000`, you end up with something on the order of a hundred million floats, which uses a few gigabytes of memory.One workaround could be to segment up the input data upfront, and then average the output of `welch` on each segment.

I get the impression from your code examples, however, that you may be trying to use the `nfft` keyword argument to specify the sampling frequency of the input data. However, the `fs` argument should be used for this. `nfft` is used to specify if a padded/oversampled FFT is desired; if you're looking for loudest frequencies, as appears to be the case in your first code attachment, I don't think oversampling is going to win you much.
