### ISSUE TITLE
Python crashes for special.spherical_ functions with complex argument 

### ISSUE THREAD

**Issue by chohner** [scipy/scipy#7002]
Hello!

I'm experiencing hard python crashes on specific windows + python combinations when executing the spherical bessel functions with complex arguments. This has been discovered on appveyor and can be reproduced on a completely fresh miniconda install on my local windows machine (win 10, 64 bit).

Affected are as far as I can tell 64bit windows machines with Python 3.5 and 3.6. 32 Bit installations as well as the 64 Bit installation of Python 3.4 are fine, same as all versions on OSX and Unix.

You can use the following snippet and use any of  `spherical_jn`, `spherical_yn`, `spherical_in`, `spherical_kn`, as well as derivative `False` and `True`.

```
from scipy import special `spherical_kn`
special.spherical_jn(1, 1+1j, derivative=True)
```

**Comment by pv** [comment]
Which scipy version? Which binaries? Is it reproducible only with 
Anaconda binaries? How about Gohlke's?

**Comment by chohner** [comment]
Tested with Gohlke's binaries and both `3.5` and `3.6` 64 bit run fine, so this is a problem with the conda builds.

**Comment by pv** [comment]
Then probably should be reported to Continuum, so that they can fix theirs.

**Comment by qli14** [comment]
I
