### ISSUE TITLE
scipy

### ISSUE THREAD

**Issue by MadushanPathirana** [scipy/scipy#7003]
i use python 3.6 i cant install scipy
 plz suggest me a easy way

**Comment by person142** [comment]
Installation instructions are here:

https://www.scipy.org/install.html

Note that the bug tracker isn't really the place to discuss user issues, though if you think there's a bug of course we want to hear about it. (Would need many more details though--operating system, which method you are using, etc.)

**Comment by MadushanPathirana** [comment]
Thank you very much. How ever i able to install it with anaconda.

On Feb 5, 2017 23:23, "Josh Wilson" <notifications@github.com> wrote:

Closed #7003 <https://github.com/scipy/scipy/issues/7003>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/scipy/scipy/issues/7003#event-949500670>, or mute the
thread
