### ISSUE TITLE
linear_sum_assignment in scipy.optimize never return if one of the assignments must have a cost of Infinity

### ISSUE THREAD

**Issue by Zsw007** [scipy/scipy#7005]
[StackOverflow](http://stackoverflow.com/questions/42035999/why-does-linear-sum-assignment-in-scipy-optimize-never-return-if-one-of-the-assi) recommended that I report this as a bug.

When using `scipy.optimize.linear_sum_assignment`, if the cost matrix of the bipartite graph is set up in a way such that one of the assignments must have a cost of infinity, the algorithm will simply never return, and hang there forever.

In the following example, the second vertex in the first set will always have a cost of infinity regardless of which vertex in the second set it is matched with. This will cause the program to hang and never print anything.

```
cost = np.array([[np.inf, np.inf, 4], 
                 [np.inf, np.inf, np.inf], 
                 [np.inf, 4, np.inf]])
row_ind, col_ind = linear_sum_assignment(cost)
print(cost)
print(col_ind)
print(cost[row_ind, col_ind].sum())
```

Yet, I would expect that we should nonetheless be able to find an assignment. For example, the second vertex in the first set can still be matched with the first vertex in the second set. We would then have a `col_ind` of `[2 0 1]` and a total cost of assignment of infinity.

I would also like to note that the following cost matrix will also result in the program not printing anything, so it is insufficient to simply ensure that every row have at least 1 non-infinite cost.

```
cost = np.array([[np.inf, np.inf, 4], 
                 [np.inf, 4, np.inf], 
                 [np.inf, 4, np.inf]])
```

Finally, the following cost matrix is fine

```
cost = np.array([[np.inf, np.inf, 4], 
                 [4, np.inf, np.inf], 
                 [np.inf, 4, np.inf]])
```

and results in the following output.

```
[[ inf  inf   4.]
 [  4.  inf  inf]
 [ inf   4.  inf]]
[2 0 1]
12.0
```

I am running SciPy 0.18.1 on Python 3.5.2 on Anaconda 4.2.0.

**Comment by WarrenWeckesser** [comment]
@Zsw007 Thanks for reporting the problem.

The problem exists in the current master branch, too.  As shown in the following, I get a warning, and the function doesn't return:

```
In [1]: import scipy

In [2]: scipy.__version__
Out[2]: '0.19.0.dev0+5fcec9e'

In [3]: from scipy.optimize import linear_sum_assignment

In [4]: cost = np.array([[np.inf, np.inf, 4], 
   ...:                  [np.inf, np.inf, np.inf], 
   ...:                  [np.inf, 4, np.inf]])

In [5]: row_ind, col_ind = linear_sum_assignment(cost)
/Users/warren/miniconda3scipy/lib/python3.5/site-packages/scipy-0.19.0.dev0+5fcec9e-py3.5-macosx-10.6-x86_64.egg/scipy/optimize/_hungarian.py:144: RuntimeWarning: invalid value encountered in subtract
  state.C -= state.C.min(axis=1)[:, np.newaxis]
```

**Comment by WarrenWeckesser** [comment]
Ping @larsmans, if you have a moment to take a look.

**Comment by rgommers** [comment]
fixed by gh-7031
