### ISSUE TITLE
Intro Docs Typo?

### ISSUE THREAD

**Issue by pylang** [scipy/scipy#7006]
On the [`scipy.integrate` tutorial page](https://docs.scipy.org/doc/scipy-0.18.1/reference/tutorial/integrate.html), there are a few typos:

1. The latex for `quad` suggests the first `x` term should be squared:

`I(a,b)=\int_{0}^{1} ax^2+b \, dx`

But the example evaluates the integrand as `x` alone:
```
>>> def integrand(x, a, b):
...     return a * x + b
```
To reflect the `integrand` function, I believe the latex should be corrected to:

`I(a,b)=\int_{0}^{1} ax+b \, dx`

2. In the same example, the value of `I` should be returned in the end, not reassigned, i.e.
```
...
>>> I = (2.0, 2.220446049250313e-14)
```
should be
```
...
>>> I 
(2.0, 2.220446049250313e-14)
```

**Comment by person142** [comment]
Yep, it's been fixed in master:

https://scipy.github.io/devdocs/tutorial/integrate.html
