### ISSUE TITLE
possible speed improvment in rv_continuous.fit()

### ISSUE THREAD

**Issue by kokorev** [scipy/scipy#7011]
Around 80% of rv_continuous.fit() execution time is consumed by a sum() function. Replacing line
`n_bad = sum(cond0)`
with line:
`n_bad = cond0.sum()`
in scipy.stats._distn_infrastructure.rv_continuous._nnlf_and_penalty() gives huge speed improvement in running .fit() in showcase below (scipy 0.18.1, python 3.5).

```
import scipy.stats
import numpy as np
import time
x_arr = [np.random.rand(10000) for i in range(10)]
t0 = time.process_time()
for x in x_arr:
    param = scipy.stats.gamma.fit(x)
t1 = time.process_time()
print("it took %5.2f seconds "%(t1-t0))
```

It takes 38.14 seconds with the standard line and 1.34 seconds with suggested replacement.
I did `scipy.test('full')` and modification does not seem to break any unit tests.

**Comment by ev-br** [comment]
Are you interested in sending a PR with the fix?

**Comment by kokorev** [comment]
I've done a PR

**Comment by ev-br** [comment]
Thanks for the PR! (it's gh-7012).

We typically keep issues open until the fix is merged, so I reopened it. A nice bit of github magic: if you write "closes gh-XXXX" in the text of a PR or a commit message, the issue will get closed automatically when the PR is merged.

**Comment by ev-br** [comment]
Fixed by gh-7012
