### ISSUE TITLE
Documentation for handling strings with numpy

### ISSUE THREAD

**Issue by lravindr** [scipy/scipy#7013]
The string is treated as python 2.x is treated as a string type and a byte array type. In python 3.x plaintext is only as a string type. Some of the examples [1](https://github.com/numpy/numpy/issues/8498), [2](https://docs.scipy.org/doc/numpy/user/basics.io.genfromtxt.html) would not work in Python 3.x interpreters. Such an issue was raised in as a [numpy issue] (https://github.com/numpy/numpy/issues/8498). 

I would like to contribute towards fixing this documentation. This would be my first contribution. We should fix the documentation to each of the example pages or add to the FAQ for possible issues when moving between the two interpreters. Which one would be the preferred method?

**Comment by ev-br** [comment]
You might get a better responce in the numpy issue tracker or numpy-discussion mailing list.

**Comment by lravindr** [comment]
Ok. Got it. I did find that the .rst file associated with the documentation is part of the numpy project.
