### ISSUE TITLE
Test failure with Python 3.5 and numpy master

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#7015]
The following test failure has occurred in several recent pull requests.  The error occurs with Python 3.5 using the build of the numpy master branch:
```
$ python -u $OPTIMIZE runtests.py -g -m $TESTMODE $COVERAGE $USE_WHEEL_BUILD |& tee runtests.log
Running unit tests for scipy
NumPy version 1.13.0.dev0+98b3127
NumPy relaxed strides checking option: True
NumPy is installed in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/numpy
SciPy version 0.19.0.dev0+62c0d64
SciPy is installed in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/scipy
Python version 3.5.2 (default, Jan 17 2017, 02:57:44) [GCC 4.6.3]
nose version 1.3.7
<snip>
======================================================================
FAIL: test_continuous_basic.test_cont_basic(<scipy.stats._continuous_distns.genextreme_gen object at 0x7f5e20f8ccc0>, (-0.1,))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/scipy/stats/tests/common_tests.py", line 109, in check_edge_support
    npt.assert_equal(distfn.cdf(x, *args), [0.0, 1.0])
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/numpy/testing/utils.py", line 342, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/numpy/testing/utils.py", line 852, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/numpy/testing/utils.py", line 725, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(shapes (2, 1), (2,) mismatch)
 x: array([[ 0.],
       [ 1.]])
 y: array([ 0.,  1.])

----------------------------------------------------------------------
```

In https://github.com/scipy/scipy/pull/7012, @charris said "I don't recall anything obvious that could have changed the shapes..."

**Comment by charris** [comment]
Unfortunately, the traceback is incomplete and the location of the actual test that failed is unknown. Would help if there was an error message attached to the error that at least printed out the failing distribution.

I note that this uses the NumPy wheel. I believe there has been some recent work on the NumPy  development wheel. @matthew-brett Any possible connection?

**Comment by charris** [comment]
I'll guess this is related to boolean indexing.

**Comment by charris** [comment]
Note the change in dimensions.
```
In [3]: array([1,2])[array(True)].shape
Out[3]: (1, 2)

In [4]: array([1,2])[:,array(True)].shape
Out[4]: (2, 1)

In [5]: np.__version__
Out[5]: '1.13.0.dev0+eefc4b8'
```
Would be good to know what is happening before the call to `check_edge_support`.

**Comment by WarrenWeckesser** [comment]
The problem is caused by this change in numpy:

numpy '1.11.2':

```
In [9]: np.finfo(float).machar.xmin
Out[9]: array(2.2250738585072014e-308)
```

numpy '1.13.0.dev0+98b3127':

```
In [18]: np.finfo(float).machar.xmin
Out[18]: array([  2.22507386e-308])
```

Note that in the second case, the value is a *one-dimensional* array, while in the old numpy it is a 0-dimensional array (i.e. a "scalar array").

That value, called `_XMIN` in the scipy code, is used as part of a `where()` expression when `genextreme` checks its arguments and assigns the values `genextreme.a` and `genextreme.b`.  Because the  new numpy gives a 1-d array, the values assigned to the support limits become 1-d arrays.  If these are then combined as they are in the test using `x = [genextreme.a, genextreme.b]`, the result is an array with shape `(2, 1)`.

**Comment by charris** [comment]
Oh, nice find. Now I have a valid reason to ping @matthew-brett ;) Should be easy to fix. We also need some tests for that.

**Comment by charris** [comment]
I opened a NumPy issue for this.

**Comment by WarrenWeckesser** [comment]
Not that we can't wait for an update to numpy, but it looks like we could avoid the problem by changing the code in `scipy/stats/_constants.py` from

    _XMAX = np.finfo(float).machar.xmax
    _XMIN = np.finfo(float).machar.xmin

to

    _XMAX = np.finfo(float).max
    _XMIN = np.finfo(float).tiny

Those values are type `numpy.float64` in older numpy and in the numpy master branch.
I have no preference, but I'll add that the `.max` and `.tiny` attributes are well-documented, so this isn't a hackish work-around that we would have to undo later.
