### ISSUE TITLE
sigma argument in 'scipy.optimize.curve_fit' can't be a function

### ISSUE THREAD

**Issue by hal-314** [scipy/scipy#7016]
scipy.optimize.curve_fit function has the useful sigma parameter to specify uncertainties in the data. The inverse of this parameter is used as weighs in the least-square problem.

However, if the uncertainties of the data are dependent with the parameters of the model function f ( data = f(x, *params) + eps ) , curve_fit function can't resolve the problem. In order to support this scenario, sigma parameter have to accept a weighting function. This functions would accept the same parameters than the model function.

If there are consensus, I would be happy to create a PR because I faced this exact problem in my work and I modified curve_fit to add this feature.

**Comment by josef-pkt** [comment]
Can you provide an example to understand better?

IIUC, then this would not be a least squares problem anymore separable in y and prediction function. You would have to minimize with respect to the prediction parameters and the parameters in the variance function.

**Comment by rgommers** [comment]
question answered, so closing.

**Comment by AlexSlow94** [comment]
If I am not wrong, I think I may have an example of the situation described by @hal-314. 
Suppose that one wants to minimise the weighted least squares function: 
$\sum \frac{y_i-f(x_i,\theta)^2}{\sigma_i^2} $ .
`np.sum( (y-f(x,*params) / sigma)**2)`
If the set of $y_i$ comes from, e.g., Poisson distributions (centered at their "true" values), it is possible to make as an approximation the substitution $\sigma_i^2=y_i$. 
However, another choice could be made by making the substitution $\sigma_i^2=f(x_i,\theta)$ (`sigma=f(x,*params)`) (see for example G. Cowan, Statistical Data Analysis, paragraph 7.4). 
Can curve_fit or generally the Levenberg-Marquardt algorithm handle this situation? 
Sorry for the Latex-style writing of expressions, I am new and I don't know how to write them.
