### ISSUE TITLE
Hilbert function returned the image part value is 0

### ISSUE THREAD

**Issue by xiangjan** [scipy/scipy#7019]
look below code :
def myHilbert(Signal):
    AnalSignal = sp.signal.hilbert(Signal)
    EnvSignal = abs(AnalSignal)
    AngSignal = np.angle(AnalSignal)

In function scipy.signal.hilbert, I know the function returns complex number. But, with different inputs, sometimes its returns 0 image part complex number. the real part result is the same with matlab function(hilbert). 
this is the input file : [link](https://www.dropbox.com/s/a54606a6klerd28/FiltAcc4.mat?dl=0)

**Comment by xiangjan** [comment]
The reading file code is:
import scipy.io as sio

temp=sio.loadmat('FiltAcc4.mat')
Signal = temp['filtAcc4']
myHilbert(Signal)

**Comment by pv** [comment]
This is because `filtAcc4.shape == (99970, 1)` and the transform is 
computed along the *last* axis. signal.hilbert works correct.
The issue is in your code (eg needs filtAcc4.squeeze()).

**Comment by xiangjan** [comment]
Thank you for @pv comment.
