### ISSUE TITLE
scipy.block_diag with empty arrays

### ISSUE THREAD

**Issue by KarachoKid** [scipy/scipy#7045]
This is related to #4596 concerning the behavior of scipy.linalg with empty arrays. The present implementation ignores empty arrays only if their shape is (1,0). This produces

a=[]
b=[1]
c=[]
In: block_diag(a,b,c)
Out: [[1]]

a=np.zeros((1,0))
b=[1]
c=np.zeros((1,0))
In: block_diag(a,b,c)
Out: [[1]]

a=np.zeros((2,0))
b=[1]
c=np.zeros((2,0))
In: block_diag(a,b,c)
Out: ValueError: could not broadcast input array from shape (2,0) into shape (0,0)

My expectation would have been:

In the first case:
Out: [[1]]

In the second case:
Out: [[0],[1],[0]]

In the third case:
Out: [[0],[0],[1],[0],[0]]

**Comment by person142** [comment]
This is fixed in master: https://github.com/scipy/scipy/pull/6742.
