### ISSUE TITLE
Documenting _argcheck for rv_discrete

### ISSUE THREAD

**Issue by cynddl** [scipy/scipy#7050]
In the documentation for ``rv_continuous``, there is a clear note that only positive arguments are valid by default. However, such note is missing for ``rv_discrete``. This is quite unintuitive and I would have like to be warned of that behavior instead of getting a ``ValueError: Domain error in arguments.`` exception.

While I understand it's not always a good idea to duplicate documentation, I think it'd be worth it to add a small note in the ``rv_discrete`` to remind readers of this fact, instead of just saying: “*This class is similar to rv_continuous*”.

I'm happy to send a pull request to support this issue.

**Comment by ev-br** [comment]
Yes, one can almost duplicate the paragraph from the `Notes` section of `rv_continuous` in the notes of `rv_discrete`, https://github.com/scipy/scipy/blob/master/scipy/stats/_distn_infrastructure.py#L2596

I'll happily review a pull request.

**Comment by deeptavker** [comment]
Old : This class is similar to `rv_continuous`, the main differences being:

New : This class is similar to `rv_continuous`. Whether a shape parameter is valid is decided by an ``_argcheck`` method (which defaults to checking that its arguments are strictly positive.)
The main differences are : 

I'd be happy to send a pull request if these changes are approved.

**Comment by cynddl** [comment]
Thanks @deeptavker for the change and @ev-br for the fast response! 👍
