### ISSUE TITLE
Errors in special.bdtri and special.bdtr for non-integer k values

### ISSUE THREAD

**Issue by dazgit** [scipy/scipy#7058]
Assuming the incomplete beta function and its inverse are correct, the functions bdtri(n,k,y) and bdtr(k,n,p) give the wrong values for non-integer k (```scipy.__version__ == 0.18.1```)
Test code:
```
from scipy.special import bdtrik, bdtri, bdtr, betainc, betaincinv
import numpy as np
for n in range(2,9):    
    p = 0.05
    y = 0.95
    k = bdtrik(y, n, p)
    print n, k, bdtr(k,n,p), betainc(n-k,k+1,1-p), bdtri(k,n,y), 1 - betaincinv(n-k,k+1,y)
    k = np.ceil(k)
    print n, k, bdtr(k,n,p), betainc(n-k,k+1,1-p), bdtri(k,n,y), 1 - betaincinv(n-k,k+1,y) 
```
Outputs:

| n | k | y = bdtr(k,n,p) | y = betainc(n-k,k+1,1-p) | p = bdtri(k,n,y) | p = 1 - betaincinv(n-k,k+1,y) | 
| - | - | ----------- | -------------------- | ------------ | ------------------------- | 
 | 2.0 | 0.2142 | 0.9025 | 0.95 | 0.0253 | 0.05 | 
 | 2.0 | 1.0 | 0.9975 | 0.9975 | 0.2236 | 0.2236 | 
 | 3.0 | 0.3902 | 0.8574 | 0.95 | 0.017 | 0.05 | 
 | 3.0 | 1.0 | 0.9928 | 0.9928 | 0.1354 | 0.1354 | 
 | 4.0 | 0.5456 | 0.8145 | 0.95 | 0.0127 | 0.05 | 
 | 4.0 | 1.0 | 0.986 | 0.986 | 0.0976 | 0.0976 | 
 | 5.0 | 0.6876 | 0.7738 | 0.95 | 0.0102 | 0.05 | 
 | 5.0 | 1.0 | 0.9774 | 0.9774 | 0.0764 | 0.0764 | 
 | 6.0 | 0.8202 | 0.7351 | 0.95 | 0.0085 | 0.05 | 
 | 6.0 | 1.0 | 0.9672 | 0.9672 | 0.0628 | 0.0628 | 
 | 7.0 | 0.9457 | 0.6983 | 0.95 | 0.0073 | 0.05 | 
 | 7.0 | 1.0 | 0.9556 | 0.9556 | 0.0534 | 0.0534 | 
 | 8.0 | 1.0655 | 0.9428 | 0.95 | 0.0464 | 0.05 | 
 | 8.0 | 2.0 | 0.9942 | 0.9942 | 0.1111 | 0.1111 |

**Comment by pv** [comment]
bdtri probably just truncates k to floor(k). I get
```
 >>> bdtri(0.3, 2, 0.7)
/home/pauli/bin/ipython:1: RuntimeWarning: floating point number 
truncated to an integer
   #!/usr/bin/python3
0.16333997346592444
```
The function likely is meant to be used only for integer k.

**Comment by dazgit** [comment]
It appears so, since bdtri(0.3,3,0.7) returns the same values as bdtri(0,3,0.7), but the documentation ([https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.bdtri.html](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.bdtri.html)) states k is a float and that it's calculated using the incomplete beta function relation. 

If it's meant to have k as an integer it should really raise an exception rather than a runtime warning, especially given that btdrik returns k as a float.

**Comment by ev-br** [comment]
Indeed, these seem to just truncate to integers:

https://github.com/scipy/scipy/blob/master/scipy/special/generate_ufuncs.py#L91 and https://github.com/scipy/scipy/blob/master/scipy/special/_legacy.pxd#L61

**Comment by pv** [comment]
I think the plan was to either deprecate calling with float type args 
altogether, or return nans for non-integer floats. The former likely 
will break 3rd party code, but the latter probably is fine.

**Comment by dazgit** [comment]
maybe supporting non-integer floats using the formulae currently stated in the documentation is more consistent, since both bdtrik and bdtrin return float k and n (very convenient as sometimes one might want to ceil other times floor). 
```y == bdtr(bdtrik(y,n,p),n,p)``` and ```p == bdtri(bdtrik(y,n,p), n , y)``` just seems right :)

**Comment by pv** [comment]
Yes, it would be consistent, but the algorithm is not implemented for 
floats so there's digging to do to make it work (and it's low priority).
