### ISSUE TITLE
pvalues in scipy.stats.linregress

### ISSUE THREAD

**Issue by picrin** [scipy/scipy#7074]
When computing the p-value of null hypothesis that linear regression gradient = 0, why does scipy use Wald Statistic followed by a t-test, as opposed to Wald Statistic followed by a Wald test?

1. I was unable to find any discussion on the mailing list about this design detail.
2. I suggest that documentation includes information about this design detail.

The following code performs linear regression on two random 5-element vectors using scipy:

    import scipy.stats
    import random
    
    # Draw some random X and Y
    sampleSize = 5
    X = [random.uniform(0, 1) for i in range(sampleSize)]
    Y = [random.uniform(0, 1) for i in range(sampleSize)]
    
    # named tuple for scipy's linear regression
    resultScipy = scipy.stats.linregress(X, Y)
    
    print(resultScipy)

Example output is:

    LinregressResult(slope=-0.36654925096390012, intercept=0.67985896267369861, rvalue=-0.32357812225448918, pvalue=0.59531436421063166, stderr=0.61883685654551934)

I wanted to know what statistical test scipy uses to compute the p-value, in this case `0.59531436421063166`. Note that the scipy's documentation isn't particularly enlightening:

> **p-value**: *float*
>
> two-sided p-value for a hypothesis test whose null hypothesis is that the slope is zero.

After reading some of the scipy's code, I can understand & reproduce scipy's behaviour:

    import random
    import math
    import collections
    import scipy.stats
    import scipy.stats.distributions as distributions
    import numpy as np
    import sys
    
    # Draw some random X and Y
    sampleSize = 5
    X = [random.uniform(0, 1) for i in range(sampleSize)]
    Y = [random.uniform(0, 1) for i in range(sampleSize)]
    
    # Compute their average
    avgX = sum(X)/sampleSize
    avgY = sum(Y)/sampleSize
    
    # Partial steps to compute estimators of linear regression parameters.
    XDiff = [X_i - avgX for X_i in X]
    XDiffSquared = [i*i for i in XDiff]
    YDiff = [Y_i - avgY for Y_i in Y]
    
    # B1 is the estimator of slope.
    # B0 is the estimator of intercept.
    # r is the estimator of Y given X.
    B1 = sum(x * y for x, y in zip(XDiff, YDiff)) / sum(XDiffSquared)
    B0 = avgY - B1*avgX
    r = lambda x: B0 + B1*x
    
    # Partial steps to compute Wald Statistic.
    errs = [y - r(x) for x, y in zip(X, Y)]
    errStd = math.sqrt((1/(sampleSize-2))*(sum([err**2 for err in errs])))
    XStd = math.sqrt((1/(sampleSize))*sum([diff**2 for diff in XDiff]))
    stdB1 = errStd / (XStd * math.sqrt(sampleSize))
    
    # Wald Statistic.
    W = (B1 - 0)/stdB1
    
    # pvalue of Wald Test of B1 = 0.
    pvalueWald = 2*scipy.stats.norm.cdf(-abs(W))
    
    # pvalue of T test of B1 = 0.
    pvalueT = 2*distributions.t.sf(abs(W), sampleSize - 2)
    
    # named tuple for our linear regression, with p-value coming from Wald Statistic
    LinregressResult = collections.namedtuple("LinregressResult", ["slope", "intercept", "rvalue", "pvalue", "stderr"])
    resultWald = LinregressResult(slope=B1, intercept=B0, rvalue=None, pvalue=pvalueWald, stderr=stdB1)
    
    LinregressResult = collections.namedtuple("LinregressResult", ["slope", "intercept", "rvalue", "pvalue", "stderr"])
    resultT = LinregressResult(slope=B1, intercept=B0, rvalue=None, pvalue=pvalueT, stderr=stdB1)
    
    # named tuple for scipy's linear regression
    resultScipy = scipy.stats.linregress(X, Y)
    
    print(resultWald)
    print(resultT)
    print(resultScipy)

It appears that scipy first computes the Wald Statistic on the estimator of the slope (gradient), followed by a `(sampleSize - 2)` degree of freedom t-test.

Why is the p-value computed in such way? My [go-to statistics textbook](https://www.amazon.com/All-Statistics-Statistical-Inference-Springer/dp/0387402721) by Larry Wasserman, suggests that I compute the p-value of linear regression in a different way, by computing Wald Statistic, followed by a Wald test.

The two tests give very different results when the sample size is small and the slope is extreme, with Wald's test p-values being consistently lower than t-test's (even by orders of magnitude).

[![plot of Wald test vs t-test][1]][1]
[![enter image description here][2]][2]

If scipy underreports very small p-values, this would have a big effect on fields, where very small p-values are very important (like high-throughput genomic data).

  [1]: https://i.stack.imgur.com/9hSXd.png
  [2]: https://i.stack.imgur.com/CH01K.png

**Comment by josef-pkt** [comment]
They are both wald tests, they just differ in the distribution of the test statistic.

The t-distribution is the exact (IIRC) distribution if the residuals are normally distributed. Even when they are not normally distributed, then the t-distribution with the degrees of freedom correction is a better approximation to the true distribution of the test statistic in small samples.
Normal and t distribution are the same asymptotically as the sample size increases, so both give the same answer in large samples, but using the normal distribution in small samples should usually result in over-rejection, i.e. we reject the null hypothesis more often than a given p-value/type-1 error threshold, like 0.05.

For more information this would be a stats.stackexchange question.

related aside: statsmodels allow users to choose between t and normal distribution (or F and chisquare for joint hypotheses). In many cases we have only the asymptotic theory with the normal distribution, but in practice in many cases wald test based on t distribution has better size in small samples than based on the normal distribution.

Using t-distribution for linear regression is "standard textbook" result, but I never read anything by Wasserman.

**Comment by picrin** [comment]
Thanks Josef,

that clears up a lot. I can vaguely recall seeing an argument for the t-distribution being the exact distribution if the residuals are normally distributed.

This has already been a [stats.stackexchange.com question](http://stats.stackexchange.com/questions/262834/why-does-scipy-use-wald-statistic-t-test-as-opposed-to-wald-statistic-wald-t) since yesterday, but it hasn't attracted much attention.

Regarding your "increased type 1 error" comment:

> using the normal distribution in small samples should usually result in over-rejection, i.e. we reject the null hypothesis more often than a given p-value/type-1 error threshold, like 0.05.

This is exactly what I've been seeing in the graphs attached in the post above

> Using t-distribution for linear regression is "standard textbook" result, but I never read anything by Wasserman.

Would you be able to recommend any mathematical statistics textbook?

Would you support rephrasing the scipy.stats.linregress documentation to include this information about test statistic used?

Perhaps something like this:

> **pvalue** : *float*
> 
> two-sided p-value for a hypothesis test whose null hypothesis is that the slope is zero, using Wald Test with t-distribution of the test statistic.

**Comment by josef-pkt** [comment]
> Perhaps something like this: ...

sounds good to me, you could make a PR to improve it.

> Would you be able to recommend any other mathematical statistics textbook?

Unfortunately not. I haven't looked at general statistics books in a long time. I have some general econometrics text books that are in the range of 1000 pages. Otherwise, I'm only reading books on specific topics or overview articles or chapters (handbook chapters are usually heavier to read than text books but skip some of the verbosity that I don't need.)

20 pages for linear and logistic regression is very small. There are many text books that cover linear and generalized linear (logistic, poisson, ...) in more detail.

**Comment by picrin** [comment]
Thanks for all the help, here's the PR: #7137
