### ISSUE TITLE
setup.py clean error is confusing after pip build failure

### ISSUE THREAD

**Issue by matthew-brett** [scipy/scipy#7097]
When the pip build fails, the build log now finishes with:

```
  Complete output from command /Users/mb312/.virtualenvs/sp-dev/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/7c/83k0tt1s7znc6_sq9hvwqr2w0000gp/T/pip-_zi5y6lv-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  
  `setup.py clean` is not supported, use one of the following instead:
  
    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)
  
  Add `--force` to your command to use it anyway if you must (unsupported).
```

This is a bit confusing, because the source of the ``setup.py clean`` is pip itself.   Maybe re-enable?

**Comment by rgommers** [comment]
Grr. Why is pip even attempting to clean, given that it insists on building in a tmpdir that it deletes anyway. Note that ``clean`` is actually broken (gh-6410 is one, but it's bad in more ways) so maybe we can see if pip devs are willing to drop the clean step?

**Comment by matthew-brett** [comment]
Sounds reasonable to me.

**Comment by matthew-brett** [comment]
For now, worth replacing with a big fat warning?

**Comment by peterbell10** [comment]
>Note that clean is actually broken (gh-6410 is one, but it's bad in more ways) 

For the record, the issue is in numpy/numpy#6410

**Comment by sethtroisi** [comment]
I looked at a recent mac and windows failure and didn't see this. Has anyone seen this recently? I did a quick grep over git log messages and PR and didn't find anything that would have fixed this on the SciPy side.

**Comment by rgommers** [comment]
I can't remember this being fixed nor seeing this recently. I think it disappeared because `pip` switched to isolated builds by default, and is therefore not trying to clean anymore. 

Let's close, and deal with this if we ever see it again.

**Comment by andyfaff** [comment]
I reckon setup.py clean would rarely be used

**Comment by funcelotwork** [comment]
> I looked at a recent mac and windows `pip install` failure and didn't see this. Has anyone seen this recently? I did a quick grep over git log messages and PR and didn't find anything that would have fixed this on the SciPy side.

i got exactly the same code working on mac and failig on ubuntu


```
Building wheel for PyYAML (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/user/GitHub/LabsAPI/venv/labsapi/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ppexr0cb/PyYAML/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ppexr0cb/PyYAML/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-iql4ty6o
       cwd: /tmp/pip-install-ppexr0cb/PyYAML/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

```
