### ISSUE TITLE
Implement beta binomial distribution

### ISSUE THREAD

**Issue by PikalaxALT** [scipy/scipy#7102]
The beta binomial distribution is a generalized version of the binomial in which the proportion parameter is sampled from a beta distribution.  This has wide applications in bioinformatics and computational biology where events appear to be binomial in nature but the observed variance is greater than can be inferred from a binomial model alone.  For my own use, I have written a [temporary module](https://gist.github.com/PikalaxALT/6e2a39ce689764b5c53a97c0a6aa7e18) which defines a `betabinomgen` object from a scipy discrete distribution.  However, the cdf and sf functions are imprecise since they use fixed-width bins; and the ppf is a brute force approach.  An alternative would be to invoke the appropriate hypergeometric function as suggested by Wikipedia, however this particular hypergeometric function does not appear to be implemented currently.

Related: Beta negative binomial

**Comment by yoavram** [comment]
👍

Is there a road map on how to proceed? 
Perhaps a good benchmark is the [R implementation](https://rdrr.io/rforge/TailRank/src/R/beta-binomial.R)?

Minor performance note - your pmf implementations is:
```py
    def _logpmf(self, x, n, a, b):
        k = floor(x)
        combiln = gammaln(n + 1) - (gammaln(k + 1) + gammaln(n - k + 1))
        return combiln + betaln(k + a, n - k + b) - betaln(a, b)
```

A roughy 3-fold faster (according to my tests) approach is:

```py
    def _logpmf(self, x, n, a, b):
        k = floor(x)
        return gammaln(n+1) + gammaln(k+a) + gammaln(n-k+b) + gammaln(a+b) - 
           (gammaln(k+1) + gammaln(n-k+1) + gammaln(a) + gammaln(b) + gammaln(n+a+b))
```

They seem to produce the same results, as far as `np.allclose` is concerned.

**Comment by egafni** [comment]
+1

**Comment by pvanmulbregt** [comment]
As you note the Wikipedia page https://en.wikipedia.org/wiki/Beta-binomial_distribution uses the `3F2(a, b, k)` hypergeometric function for the CDF/SF, and `3F2()` is not in SciPy. The gist compensates for this by making 10,000 calls to the CDF of the Binomial distribution `bdtr()`, and 10,000 calls to the CDF of the beta distribution `btdtr()`.  That might be computationally expensive.  
Do you have any comparisons of this approach with other approaches?  Are 10,000 evaluations always needed to ensure sufficient accuracy?

**Comment by yoavram** [comment]
There's another [R implementation](https://github.com/swihart/rmutil/blob/master/R/dist.r)

**Comment by pv** [comment]
You should not read R implementations, covered by GPL, if you are
writing a replacement with difference license.

**Comment by IandJMSmith** [comment]
I have translated some code of mine into a python module - mystats.py. The python is doubtless execrable but the calculations for cdf and sf for BetaBinomial and BetaNegativeBinomial are good. 
[mystatspy.txt](https://github.com/scipy/scipy/files/2339659/mystatspy.txt)

Happy to leave you to play with it and answer any questions you may have.
