### ISSUE TITLE
scipy.misc.comb returns float, not int

### ISSUE THREAD

**Issue by nschloe** [scipy/scipy#7110]
[Documentation](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.misc.comb.html) says that `scipy.misc.comb` returns `int` – as it should be –, but really it returns a float.

MWE:
```
from scipy.misc import comb
print(type(comb(1, 1)))
```
Output:
```
<type 'numpy.float64'>
```

**Comment by person142** [comment]
The documentation is certainly incorrect, but note that you can get an `int` by doing

`comb(1, 1, exact=True)`.

**Comment by person142** [comment]
Fixed by https://github.com/scipy/scipy/pull/7113.
