### ISSUE TITLE
scipy.sparse.linalg._count_nonzero() unnecessarily eats a lot of memory

### ISSUE THREAD

**Issue by bill10** [scipy/scipy#7118]
I got an memoryerror when using the expm() for sparse matrices, and traced down to this function that is causing the memory issue.

    def _count_nonzero(A):
        # A compatibility function which should eventually disappear.
        #XXX There should be a better way to do this when A is sparse
        #    in the traditional sense.
        if isspmatrix(A):
            return np.sum(A.toarray() != 0)
        else:
            return np.count_nonzero(A)

The line return np.sum(A.toarray() != 0) is using all the memory as it tries to convert a sparse matrix to an array, which is against the purpose of using sparse matrix. So why not using something like

    return np.count_nonzero(A.data)

Maybe I am missing something. Any thought? Thank you!

**Comment by perimosocordiae** [comment]
Good catch. It seems this helper function was only used in rare cases (with explicit zeros in the sparse lower triangle), so it managed to slip by unnoticed. The pull request I just submitted should fix the problem.

**Comment by bill10** [comment]
great! thx
