### ISSUE TITLE
can't use `factr` option to `scipy.optimize.minimize('L-BFGS-B')`

### ISSUE THREAD

**Issue by jbloom** [scipy/scipy#7121]
The docs for the LBFGSB minimization describe the `factr` option, which is useful for controlling the absolute tolerance (relative to machine precision) of the optimization.

However, actually passing this option in the `options` dictionary doesn't work, and gives a warning that is an invalid option.

This is version `0.18.1`.

**Comment by andyfaff** [comment]
Please see #5231

**Comment by jllanfranchi** [comment]
I have submitted a PR to clean up the documentation to make clear that the two different interfaces to L-BFGS-B expose different options (`ftol` in the case of `minimize(...)` and `factr` in the case of `fmin_l_bfgs_b(...)`).

However, it might not be a terrible idea (depending upon your code aesthetics) to expose _both_ options for _both_ interfaces. This could work by enforcing consistency between the two options if they are _both_ provided, e.g. via `np.allclose(... rtol=eps)`. If only one is provided, then the other can be derived from it (if the other is needed).

If that option is desirable, then this issue should be reopened, and #7252 can be closed. Resolving #7121 then would entail changing the docs yet again, but at least in the meantime the docs will reflect the actual behavior of the code.
