### ISSUE TITLE
Impossible to know number of dimensions in c function used by nquad?

### ISSUE THREAD

**Issue by iljah** [scipy/scipy#7125]
Copy of http://stackoverflow.com/questions/42536982. In short, documentation for using a c function states:
```
f(int n, double args[n])
where n is the number of extra parameters and args is an array of doubles of the additional parameters.
```
so is it impossible to know from within the c function how many dimensions are being integrated so that correct number of args is used? The provided example doesn't use n but assumes args[0]...args[2] can be used.

**Comment by pv** [comment]
IIRC n is the number of dimensions.

**Comment by pv** [comment]
But this should be more clear in scipy 0.19.0 (to be released soon).
https://scipy.github.io/devdocs/generated/scipy.integrate.nquad.html#scipy.integrate.nquad

**Comment by iljah** [comment]
Thanks, so ```extra parameters``` really means coordinates? Dev docs still mention ```args``` but there is no such parameter anymore.
