### ISSUE TITLE
Constrained Optimisation in Scipy

### ISSUE THREAD

**Issue by antonior92** [scipy/scipy#7128]
Hello, my name is Antonio and I am a Brazilian electrical engineer currently pursuing my master degree. I have contributed to ``scipy.optimize`` and ``scipy.signal`` implementing functions ["iirnotch", "irrpeak"](https://github.com/scipy/scipy/pull/6404) and the method ["trust-region-exact"](https://github.com/scipy/scipy/pull/6919) (under revision). I am interested in applying for the Google Summer of Code 2017 to work with the Scipy optimisation package.

My proposal is to improve ``scipy.optimize`` adding optimisation methods that are able to deal with non-linear constraints. Currently the only implemented methods able to deal with non-linear constraints are the FORTRAN wrappers ``SLSQP`` and ``COBYLA``.

``SLSQP`` is a sequential quadratic programming  method and ``COBYLA`` is a derivative-free optimisation method, they both have its limitations: ``SLSQP``is not able to deal with sparse 
hessians and jacobians and is unfit for large-scale problems and ``COBYLA``, as other derivative-free methods, is a good choice for optimise noisy objective functions, however usually presents a poorer performance then derivative-based methods when the derivatives are available (or even when they are computed by automatic differentiation or finite diferences).

I have opened this issue in order to discuss what methods would be better suited for ``scipy.optimize`` so I could include them in my proposal and also to discuss about possible mentors to this project.

Interior-point methods have proved to be  successful for nonlinear optimisation and are very powerful algorithms for large-scale  problems and usually are able to deal with medium/small problems reasonably well too. That way I think a nonlinear interior point method would be a good choice.

Maybe a sequential quadratic programming method implemented in Python could also be included in my proposal... Furthermore, I think it is important that those methods  provide different options for approximate the Hessian (Provided by the user, approximated by quasi-Newton methods, finite differences...).

I would much appreciate any feedback or any idea for this project.

**Comment by rgommers** [comment]
Hi Antonio, thanks for your interest! This seems like a good topic for GSoC. I suggest to post this to the scipy-dev mailing list - more people will see it.

Regarding interior point methods, did you see https://github.com/scipy/scipy/pull/7123?

@mdhaber any thoughts on this GSoC idea, or interest in co-mentoring?

**Comment by antonior92** [comment]
Thanks for the response! I took notice of #7123 and maybe I can try to reuse, when possible, code and structure implemented in this PR. My proposal, however, is to focus on methods with nonlinear objective function and nonlinear constraints. I will add a thread to the mailing list about this, so I can reach more people.

**Comment by mdhaber** [comment]
I think this is a very good idea and I am interested in co-mentoring. I think it would go well together with summer work on `scipy.diff`.

**Comment by antonior92** [comment]
@mdhaber @nmayorov I have finished the first draft of my GSoC proposal:
https://www.dropbox.com/s/2ce5vmfbq0thrlr/GSoC2017.pdf?dl=0
What do you guys think? Any suggestions

**Comment by mdhaber** [comment]
I think your proposal is well thought-out and realistic in terms of
timeframe (with concentrated effort). Your other contributions suggest that
you are well-prepared for the work. I agree with the focus on an
interior-point method and leaving the SQP implementation as optional, as
interior-point and SQP are the major competitors and minimize already has
an SQP method. It is difficult to provide a bulletproof justification for a
particular algorithm variant, but your attempt is reasonable, and it's hard
to argue with an algorithm with 1000+ citations that's used in a modern
commercial solver.

If EQP is the really expensive part of this interior point method, then the
choice of EQP algorithm needs about as much justification as the choice of
NLP algorithm. Can you give a little background on algorithms for EQP and
justify your choice of algorithm (projected CG) and particular variant
(reference 14)?

I like that you have identified that other methods could benefit from the
preconditioner, and I would certainly file those as proposed enhancements
on github, but I would advise against getting side-tracked by actually
implementing those changes in the first two weeks. Perhaps they can be
optional components at the end (with higher priority than SQP
implementation, if you like)?

Should your EQP solver be exposed to users as, say, scipy.optimize.eqprog?
Again, I don't suggest that you add these into the primary schedule, but if
you have ideas here, please suggest these as optional components and offer
to file these as proposed enhancements on github.

It sounds like the structure of this nonlinear interior-point method will
be similar to that of the interior-point method for linear programming
(#7123). I'll have to take a closer look to see whether it would be
appropriate for the two to share code.

Up until the Hessian approximation section, derivatives aren't mentioned.
What derivatives are needed? Besides the Hessian, what options do you
suggest for calculating/approximating them? You might want to take a look
at the threads about the proposed scipy.diff. Would your code benefit from
automatic derivatives? This might provide additional motivation for the
proposed integration of Numdifftools/AlgoPy....

I saw the discussion about CUTEst; this sounds like a good way to
benchmark. Comparing to IPOPT (and existing minimize methods) is also a
good idea.  Currently you've listed benchmarking quite late - and that's
fine for formal performance comparisons - but you'll need some test EQP and
NLP problems during development.

If you were to get to SQP, the new interior-point LP code (#7123) might be
helpful as the main routine already can use sparse techniques (although I
have yet to add sparse support to presolve, so currently it requires dense
array input and converts to a sparse matrix after presolve. I'll get to
that...).

Do you propose to implement those recent ideas on infeasibility detection?
How will your code terminate in this cases? Will these be distinguishable
from failure to converge for other reasons? Thoughts on unbounded problems?

**Comment by nmayorov** [comment]
Matt made excellent points, I will capitalize on them.

> If EQP is the really expensive part of this interior point method, then the
choice of EQP algorithm needs about as much justification as the choice of
NLP algorithm. Can you give a little background on algorithms for EQP and
justify your choice of algorithm (projected CG) and particular variant
(reference 14)?

That is so true. Also as it is the core internal solver the implementation details will matter as well. I mean that it should be implemented rather efficiently (maybe using Cython ). And I believe there should be some distinction between sparse and dense problems, at least in linear algebra routines involved (or maybe in the core EQP algorithm as well). 

It is a really nice idea to start with a simpler and essential sub-problem and it is better to start well, so focus on this part more. Looking forward to the update.

I agree with Matt about leaving preconditioners as an afterthought. If it makes sense to implement it generic enough, then it's a good idea to make it public.

> Up until the Hessian approximation section, derivatives aren't mentioned.
What derivatives are needed? Besides the Hessian, what options do you
suggest for calculating/approximating them? You might want to take a look
at the threads about the proposed scipy.diff. Would your code benefit from
automatic derivatives? This might provide additional motivation for the
proposed integration of Numdifftools/AlgoPy....

My understanding is that Antonio's work should be self-contained. So while having automatic derivatives or full-fledged package for numerical derivatives would be awesome, I believe we can't consider it for this project. In other words, Antonio has to write his own code for everything which is not part of `scipy` at this point.

As I understand we need the gradient approximation and the full Hessian approximation (when a user wants that approach). For the Hessian approximation there are two options: approximate knowing gradient analytically and approximate from the function directly. The last option might be impractical.

Overall it looks like a lot of work. So might it be a good idea to require analytic gradients / Hessians from a user at this stage? Or does Antonio ready to develop all the code for numerical differentiation? (there is something to reuse in `scipy.optimize`)  @mdhaber @antonior92 what do you think?

----

I think I'll stop here for now so not to burden Antonio with a lot of text.

**Comment by nmayorov** [comment]
Update thoughts about finite difference approximation. If we rule out approximating the Hessian from the function only, then there is `scipy.optimize._numdiff` which should do the job for the gradient and "the Hessian from the analytic gradient". It supports sparse differencing given the sparsity structure. But it isn't really optimized for speed or parallel execution or anything like that, just straightforward Python code. Also perhaps something special is required for nonlinear constrained optimization problems.

So consider whether you want to reuse it (with possible enhancements) or want to write something new or prefer to go without numerical differentiation (at least before the main algorithm is finished).

**Comment by mdhaber** [comment]
Thanks, Nikolay!

I agree that it's too much work for Antonio to write general-use
differentiation code in addition to the interior point method all in one
summer. I didn't mean to suggest that he should write any new code for
evaluating derivatives himself. I think he should start by requiring
analytic gradients and look into Hessian approximations later on, as he
proposed.

But I also think that an NLP solver that can't get its own derivatives is
impractical to use. So I do think he should consider how his interior-point
code would be extended (later on) to utilize alternative derivative
options, because this is something that *really* needs to happen at some
point, IMO, for the interior-point code to reach its potential. (As a
placeholder he might provide for the use of scipy.optimize._numdiff, again
considering that this is not the final solution.)

So I guess my recommendation is: mention in the proposal where the
derivatives will come from initially, and acknowledge that improved options
for the derivatives would be important future work.

If proposals for both the NLP solver and scipy.diff are accepted, I think
there can be some communication between the projects and they can help
shape one another.

**Comment by antonior92** [comment]
Thanks Nikolay and Matt for the great comments.

I answer them bellow:

**Comment by antonior92** [comment]
> If EQP is the really expensive part of this interior point method, then the
> choice of EQP algorithm needs about as much justification as the choice of
> NLP algorithm. Can you give a little background on algorithms for EQP and
> justify your choice of algorithm (projected CG) and particular variant
> (reference 14)?

The projected CG is a very natural choice: it was used on the original paper, it is 
able to deal with indefinite Hessians and furthermore, as other CG methods it deals
naturally with sparse structures and allows "Hessian-free" implementations (you don't 
need to provide the Hessian, only the Hessian-vector product).

**Comment by antonior92** [comment]
> I like that you have identified that other methods could benefit from the
> preconditioner, and I would certainly file those as proposed enhancements
> on github, but I would advise against getting side-tracked by actually
> implementing those changes in the first two weeks. Perhaps they can be
> optional components at the end (with higher priority than SQP
> implementation, if you like)?

Make sense! I will move them to the end.

**Comment by antonior92** [comment]
> Should your EQP solver be exposed to users as, say, scipy.optimize.eqprog?

EQP solvers are much more restricted than solvers capable of solving full QP problems (problems containing equality and inequality constraints). So I don't know if this solver would be of much use for the users...

**Comment by antonior92** [comment]
> Up until the Hessian approximation section, derivatives aren't mentioned.
> What derivatives are needed? Besides the Hessian, what options do you
> suggest for calculating/approximating them? You might want to take a look
> at the threads about the proposed scipy.diff. Would your code benefit from
> automatic derivatives? This might provide additional motivation for the
> proposed integration of Numdifftools/AlgoPy....
>
> So I guess my recommendation is: mention in the proposal where the
> derivatives will come from initially, and acknowledge that improved options
> for the derivatives would be important future work.

This method require first and second derivatives. Using quasi-Newton approximations
the second derivatives are no logger needed.

The use of finite difference and automatic differentiation would certainly improve the usability of the method

**Comment by antonior92** [comment]
I will answer to the rest latter....

**Comment by antonior92** [comment]
Going back to what I was saying, I think how to compute the derivatives is a question I am not  addressing properly in my proposal. Demand the user to provide them should not be the long term plan and I see two different approaches that are more or less contained in your comments:

1) The first option is to do as in Matt's comment and: "mention in the proposal where the
derivatives will come from initially, and acknowledge that improved options
for the derivatives would be important future work." 
2) The second approach is to do a more self contained work and include some options to estimate the derivatives. I think automatic differentiation is out of the scope of this project, so it would be something in the line of finite differences.

Both options have some advantages, the option (1) will allow me to have more time to work on the methods, besides that, if ``scipy.diff`` come out soon it could solve the problem in more a consistent way.  Option (2) will result in a more complete method for the user, more self-contained  and independent from the development of other Scipy packages. 

If I go for option (2) I could remove the implementation of the SQP method from my proposal and add the calculation of derivatives as optional work.


----------------

About the reuse of ``scipy.optimize._numdiff``: it can be useful for computing the jacobin matrices of the constraints of the NLP problem. It is not ideal for the seconds derivative, because the Hessian symmetry is not taken into account by the method. So I would probably have to do some modifications to it.

**Comment by nmayorov** [comment]
I suggest to implement numerical derivatives as the part of the project. My arguments:

1. The workflow is more straightforward, you are in charge of everything.
2. For me it is not very clear what will become a part of `scipy.diff` (and when). My understanding is it should contain methods to compute derivatives accurately using advanced methods. But for numerical optimization accuracy is not ultimately important, it is more about a balance between accuracy and speed. For example, forward differencing might be often sufficient and there are special studies about how optimization behaves with such secant approximation.
3. It can be a place to finally introduce `approx_derivative`, `check_derivative` as public functions to `optimize` module. And additionally introduce a new quality function for the Hessian approximation. The names should be something like: `num_jac`, `num_hess`, `check_jac`, `check_hess`.
4. Having those functions we can eliminate other subpar implementations from `optimize`, they will also serve for future well.

So I suggest to devote a part of your proposal to numerical differentiation (mainly focusing on the Hessian) instead of SQP solver.

**Comment by nmayorov** [comment]
> The projected CG is a very natural choice: it was used on the original paper, it is
able to deal with indefinite Hessians and furthermore, as other CG methods, it deals
naturally with sparse structures and allows "Hessian-free" implementations (you don't
need to provide the Hessian, only the Hessian-vector product).

I believe also having a direct method for small/medium-sized problems with dense Hessian is useful and it can be positive for a practical performance. In other words using an iterative method every time is sort of against the spirit of numerical methods. 

What do you think? Can you propose another solution?

**Comment by antonior92** [comment]
Thanks for both suggestions Nikolay! I will go for both of them
- I will remove the SQP method from my proposal and add numerical derivatives (for sparse structures) as part of the project. Since you have already implemented it for the Jacobian matrix I would have only to focus in the Hessian. I am thinking in some graph colouring scheme in the line of [1].
- I wil add the Null-Space method as an EQP solver. It doesn't seems hard to implement and I think you have a point about it.

I will add this modifications to the document as soon as possible.


[1] Coleman, T. F., & Moré, J. J. (1984). Estimation of sparse Hessian matrices and graph coloring problems. Mathematical Programming, 28(3), 243-270.

**Comment by nmayorov** [comment]
Just a reminder that you must not miss official deadlines for the GSoC. April 3 is the date. Are you already checking their site?

**Comment by antonior92** [comment]
Thank you for the reminder! :)

 I have already gone throught the initial submission steps... I am just  finishing my proposal and I will submit the final version in due time.

**Comment by antonior92** [comment]
@rgommers @nmayorov @mdhaber I am looking forward to work with you all during my Google Sumer of Code project. :)

During the community bonding period I expect to refine my proposal and figure out how to proceed with the small details of the algorithm I intend to implement. Furthermore, I am already help revising PR #7292 and hope to be able to help in others ways as well.

I created a repository with my proposal https://github.com/antonior92/GSoC2017-Scipy for easy reference.

**Comment by rgommers** [comment]
Nice @antonior92, good idea to put your proposal in a repo given that Google doesn't make the full proposal public. And congratulations on getting accepted! 

> Furthermore, I am already help revising PR #7292 and hope to be able to help in others ways as well.

I've been following that from a distance - this kind of interaction is great. I'd say go ahead and review or comment on anything that seems relevant and catches your interest.

**Comment by mdhaber** [comment]
Congratulations, @antonior92 <https://github.com/antonior92>! I'm really
looking forward to this, too. I stopping working on an optimal control
project in part due to difficulties with the existing minimize function, so
I'm excited to help improve it!

Those sound like great ways to use the community bonding period, since
you're already quite familiar with the community.

Also, while you have some formal benchmarking time set aside after the
first few weeks, now might be a good time to write - or at least collect
the problems for - some informal test code to work with as you're
implementing the EQP and NLP code. I find that the process of writing test
code for functions helps me refine my plan for implementing them.

**Comment by antonior92** [comment]
I liked the idea: I will start implementing some informal test code and I think it will help me see the big picture... Thanks for the suggestion!

**Comment by ilayn** [comment]
As another control guy mostly working with LMIs, this is indeed pretty nice initiative! Will be keeping an eye on this for sure.
