### ISSUE TITLE
Discontinuity of a scipy special function

### ISSUE THREAD

**Issue by lcanon88** [scipy/scipy#7133]
I'm trying to calculate something by using the parabolic cylinder function which scipy provides.
Here is my code.

```
import numpy as np
import scipy.special as ssp
import matplotlib.pyplot as plt

num = int(1e3)
x = np.linspace(-5, 5, num)
y1 = np.zeros(num)
y2 = np.zeros(num)

for m in range(num): 
    y1[m] = ssp.pbwa(0, x[m])[0]
    y2[m] = ssp.pbwa(0, x[m])[1]
    
plt.plot(x, y1, 'k')
plt.plot(x, y2, 'b')
```
If you run it, you can see two graphs.

![image](https://cloud.githubusercontent.com/assets/26239612/23640261/e40d8018-032f-11e7-96da-364a6b3956b7.png)

Black line for W(0, x) and blue line for W'(0, x) where W(a, x) denotes the parabolic cylinder function
(Refer to 12.14 of the link : http://dlmf.nist.gov/12)

Strange is that there does not exist a discontinuity for W'(0, x) at x = 0.
Thus, I think it should be fixed as soon as possible.

**Comment by person142** [comment]
The issue is that the SciPy wrapper of the `specfun` function forgets to use the chain rule. In particular, the documentation for the `specfun` routine says:

```fortran
        SUBROUTINE PBWA(A,X,W1F,W1D,W2F,W2D)
C
C       ======================================================
C       Purpose: Compute parabolic cylinder functions W(a,±x)
C                and their derivatives
C       Input  : a --- Parameter  ( 0 ≤ |a| ≤ 5 )
C                x --- Argument of W(a,±x)  ( 0 ≤ |x| ≤ 5 )
C       Output : W1F --- W(a,x)
C                W1D --- W'(a,x)
C                W2F --- W(a,-x)
C                W2D --- W'(a,-x)
C       Routine called:
C               CGAMA for computing complex gamma function
C       ======================================================
```

but the source (Zhang and Jin) consider `W(a, -x)` to be its own special function, so when they say `W'(a, -x)` they actually mean `[W(a, -x)]'`. Then the SciPy wrapper does this:

```c
/* if x > 0 return w1f and w1d.
    otherwise return w2f and w2d (after abs(x))
*/
int pbwa_wrap(double a, double x, double *wf, double *wd) {
  int flag = 0;
  double w1f, w1d, w2f, w2d;
   
  if (x < 0) {x=-x; flag=1;}
  F_FUNC(pbwa,PBWA)(&a, &x, &w1f, &w1d, &w2f, &w2d);
  if (flag) {
    *wf = w2f;
    *wd = w2d;
  }
  else {
    *wf = w1f;
    *wd = w1d;
  }
  return 0;
}
```
i.e. when `x < 0` it returns `-W'(a, x)`. So for example we have:

```python
>>> import scipy.special as sc
>>> sc.pbwa(0, -1e-8)
(1.0227656770019602, 0.48887053372341982)
>>> sc.pbwa(0, 1e-8)
(1.0227656672245493, -0.48887053372341982)
```

Another fun easter egg is:

```python
>>> sc.pbwa(0, 0)
Segmentation fault: 11
```

**Comment by lcanon88** [comment]
Thanks alot for your help.
