### ISSUE TITLE
Fitting a bessel-function using odr gives numerical error

### ISSUE THREAD

**Issue by TheLazyBum** [scipy/scipy#7134]
Hello everyone,

I have a problem fitting a function including a bessel function in it by using pythons odr. The code is:

```
import numpy as np
import matplotlib.pyplot as plt
import scipy.odr as sc
import scipy as sp


b_2=5*10**(-4)
i_b=0.002
x_bildweite_3=1.550
x=np.arange(0,44.5,0.5)
u_x=11.75
i=np.array([0.77,3.6,5.3,1.8,3.4,4.5,3.9,2.2,0.88,2.6,8.4,16,22,21,14,9.3,27,90,21,370,610,810,1060,1100,1100,1010,800,530,310,170,70,24,11,14,17.5,16,10.5,4.6,1.6,1.5,3,1.1,3.5,2.35,0.99,0.35,0.6,1.5,1.5,1.3,0.73,0.27,0.15,0.35,0.64,0.27,0.55,0.28,0.092,0.119,0.275,0.4,0.4,0.3,0.125,0.042,0.078,0.17,0.265,0.24,0.15,0.159,0.028,0.072,0.14,0.18,0.15,0.089,0.03,0.02,0.055,0.1,0.115,0.09,0.019,0.0109,0.016,0.045,0.075])
u_i=i**0.5

def m(q,x):
    i_0,x_0,g_1=q
    return   4*i_0*(sp.special.j1(x,g_1*(x-x_0))/(g_1*(x-x_0)))**2+i_b

model_m=sc.Model(m)
data_m=sc.RealData(x,i,sx=u_x,sy=u_i)
odr_m=sc.ODR(data_m,model_m,beta0=[1,1,1])
out_m=odr_m.run()
out_m.pprint()
print("Bestimmtheitsmaß =", out_m.sum_square_eps)
x_fit_m=np.linspace(0,10)
y_fit_m=m(out_m.beta,x_fit_m)
plt.yscale('log',nonposy='clip')
plt.plot(x,i,linestyle='None',marker='x')
plt.plot(x_fit_m, y_fit_m)
plt.xlabel("$\mathcal{k}$")
plt.ylabel("x-x0 [mm]")
plt.title("Fit zur Spaltbreitenbestimmung")
plt.show()
```
It says it's halting because of "Numerical error detected"
I need to finish this today...

**Comment by mlliarm** [comment]
Hello, apologies for the late reply, but I'm new here.

If the error persists, please do mention the version of Python, NumPy, SciPy and matplotlib you have installed.

On my Ubuntu 16.04, using Python '2.7.12', NumPy '1.12.0', SciPy '0.19.0', matplotlib '2.0.0' after running your code (along with using only unicode characters, I took the liberty to insert some spaces here and there, http://pastebin.com/SUcmKGZ1) I got the following error messages:

```
Traceback (most recent call last):
  File "besselprob.py", line 28, in <module>
    odr_m = sc.ODR(data_m, model_m, beta0 = [1, 1, 1])
  File "/home/milia/.venvs/scipy2/local/lib/python2.7/site-packages/scipy/odr/odrpack.py", line 768, in __init__
    self._check()
  File "/home/milia/.venvs/scipy2/local/lib/python2.7/site-packages/scipy/odr/odrpack.py", line 829, in _check
    res = self.model.fcn(*arglist)
  File "besselprob.py", line 24, in m
    return   4 * i_0 * (sp.special.j1(x, g_1 * (x - x_0)) / (g_1 * (x - x_0)))**2 + i_b
AttributeError: 'module' object has no attribute 'special'
```
It seems that scipy (abbreviated as 'sp') has no method 'special' under it. Something that can be seen if you use IPython ([printscreen](https://drive.google.com/file/d/0B4ai-gEVsMLlNkFIT2U1NTNyMjg/view?usp=sharing)).

Ok, I  got it.

Instead of 

```
import scipy as sp
```

write

```
import scipy.special as sp
```

Now you can invoke the methods of ```special```.

And in your function ```m(q,x)``` replace:

```    return   4 * i_0 * (sp.specialj1(x, g_1 * (x - x_0)) / (g_1 * (x - x_0)))**2 + i_b```

with

```    return   4 * i_0 * (sp.j1(x, g_1 * (x - x_0)) / (g_1 * (x - x_0)))**2 + i_b```

Now it works (faster in Python2 than in Python3) and it gives a nice plot.

**Comment by TheLazyBum** [comment]
Thank you so far.

I started using Anaconda because the GUI helps me really much at learning, so I don't exaclty know the versions of the packages I am using. How can I check this?

**Comment by rkern** [comment]
It's not a problem with the versions, don't worry. You probably executed this code in an interpreter session where you had already imported `scipy.special` explicitly. When a subpackage is imported, it gets added to the namespace of its parent package, and so would have been available to your code as `sp.special`.

By the way, as a matter of style, I don't recommend using any of the short aliases for scipy. `import numpy as np` is fine, but the others are unnecessary.

```
import numpy as np
from scipy import odr
from scipy.special import j1
```

The problem has more to do with that `RuntimeWarning: divide by zero encountered in divide` warning before the final error. Note that you are dividing by `(x-x_0)` in there. Your initial value of `x_0` is `1.0` and one of the elements of `x` is definitely `1.0`. That's going to create an `inf`, and the outer ODR subroutine flags that as the result of a numerical error (it probably creates a `NaN` later in the algorithm).

**Comment by person142** [comment]
Sounds like this can be closed then.
