### ISSUE TITLE
The dirichlet distribution unnecessarily rejects probabilities equal to zero.

### ISSUE THREAD

**Issue by francoiscoste** [scipy/scipy#7136]
Hi and thanks for all the work on these libraries!

I think that there is a bug in scipy.stats: the dirichlet distribution rejects unnecessarily probabilities equal to zero.
To reproduce the bug:

```
import scipy as sp
import scipy.stats as stats
print("scipy version:",sp.__version__)
d = stats.dirichlet([1,5,8])
d.pdf([0,0,1])

```
that yields:

```
scipy version: 0.18.0
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
...
/usr/lib64/python3.5/site-packages/scipy/stats/_multivariate.py in _dirichlet_check_input(alpha, x)
   1097 
   1098     if np.min(x) <= 0:
-> 1099         raise ValueError("Each entry in 'x' must be greater than zero.")
...
ValueError: Each entry in 'x' must be greater than zero.

```
This test is too strict here. Each entry in 'x' is a probability and must be greater _or equal_ to zero.

Remarks:

- _multivariate.py does not seem to have changed in new version of scipy so I expect the bug to remain in the new versions
- This issue should not be confused with issue #4953 on concentration parameters
- Changing the code to 
`np.min(x) < 0`

yield a new error in function `_lnB(alpha)`:
```
/usr/lib64/python3.5/site-packages/scipy/stats/_multivariate.py:1227: RuntimeWarning: divide by zero encountered in log
  return - lnB + np.sum((np.log(x.T) * (alpha - 1)).T, 0)
/usr/lib64/python3.5/site-packages/scipy/stats/_multivariate.py:1227: RuntimeWarning: invalid value encountered in multiply
  return - lnB + np.sum((np.log(x.T) * (alpha - 1)).T, 0)

```
so the patch has to be propagated...

**Comment by francoiscoste** [comment]
Actually, x cannot be zero if alpha is smaller than 1 (I did not care about this case above), but the issue remains that x can be zero if alpha is greater or equal to 1.
François

**Comment by ev-br** [comment]
At least Wikipedia defines both x and alpha as strictly larger then zero. R seems to do the same: http://www.stat.washington.edu/~rje42/lca/html/Dirichlet.html
So we are not too much out of line here :-).

That being said, a PR with a fix and tests is welcome.

**Comment by rkern** [comment]
Actually, from that documentation, it looks like R allows `x_i==0` under the clause `and zero otherwise`.

**Comment by pvanmulbregt** [comment]
Some parts of the Wikipedia page https://en.wikipedia.org/wiki/Dirichlet_distribution have x greater than zero and other parts have x greater than or equal to zero.  Describing some behaviors is easier if not worrying about x being zero, as that would require separating the cases where alpha >= 1 and 0<alpha<1.  The PR just extends allowable domain from the open interval (0,1) to the closed [0, 1] interval if alpha>=1.
