### ISSUE TITLE
scipy.special.binom loss of precision due to floating point 

### ISSUE THREAD

**Issue by AlexanderFraebel** [scipy/scipy#7158]
When using scipy.special.binom for moderately large inputs loss of precision develops due to floating point error. I'm not aware of any situation in which floating point values for binomial coefficients are actually needed. Shouldn't there at least be an option to calculate integer binomial coefficients to arbitrary precision in scipy?

**Comment by pv** [comment]
Use `scipy.special.comb` if you want exact integer calculations.
Binomial coefficients occur frequently in special functions and there 
floating point implementation is important also for non-integer values 
are needed.
