### ISSUE TITLE
Splines

### ISSUE THREAD

**Issue by dlmccaffrey** [scipy/scipy#7162]
For ```InterpolatedUnivariateSpline()``` (and similar situations for the other spline functions), are natural or clamped boundary conditions used?

**Comment by ev-br** [comment]
Likely, not. I *think* FITPACK uses not-a-knot conditions. `CubicSpline` and `BSpline/make_interp/lsq_spline` offer better control of the boundary conditions.

Not a bug, so closing. Please use scipy-user mailing list or StackOverflow for usage questions.
