### ISSUE TITLE
TST: SciPy tests fail on NumPy master

### ISSUE THREAD

**Issue by person142** [scipy/scipy#7164]
Build for https://github.com/scipy/scipy/pull/7163 is failing on NumPy master, log is here:

https://travis-ci.org/scipy/scipy/jobs/210291175

There are lots of errors of the form

```
  File "mtrand.pyx", line 4876, in mtrand.RandomState.permutation (numpy/random/mtrand/mtrand.c:39838)
  File "mtrand.pyx", line 4822, in mtrand.RandomState.shuffle (numpy/random/mtrand/mtrand.c:39471)
  File "mtrand.pyx", line 4825, in mtrand.RandomState.shuffle (numpy/random/mtrand/mtrand.c:39423)
TypeError: 'range' object does not support item assignment
```
which appear to be unrelated to the PR. Guessing the problem is https://github.com/numpy/numpy/commit/cf349c91e22b2195b32290f14777be79acc9af15. A NumPy issue might be more appropriate...

**Edit**: @charris created a NumPy issue: https://github.com/numpy/numpy/issues/8776

**Comment by rkern** [comment]
Yes, a NumPy issue (or PR!) should be created. Python 3 `range` iterables need a special case to expand them into a full mutatable sequence before passing them on to the rest of the method.

**Comment by person142** [comment]
Fixed in NumPy master now.
