### ISSUE TITLE
scipy.org and docs.scipy.org appear to be down

### ISSUE THREAD

**Issue by b-r-oleary** [scipy/scipy#7167]
FYI, the scipy.org and documentation site docs.scipy.org appear to be down right now.

**Comment by willingc** [comment]
Yes, it is down for me too.

**Comment by willingc** [comment]
FYI @pv @rgommers

**Comment by rkern** [comment]
Known issue. People are on it. Tracked here: numpy/numpy#8779

**Comment by willingc** [comment]
Thanks @rkern 👍
