### ISSUE TITLE
Will it be possible to add  LDL' factorization for Hermitian indefinite matrices in scipy.linalg

### ISSUE THREAD

**Issue by CodingThinking** [scipy/scipy#7169]
When working with Hermitian matrices,  LDL' factorization for Hermitian indefinite matrices is usually reqired. But I can't find it in scipy.linalg. So, will it be possible to add  LDL' factorization for Hermitian indefinite matrices in scipy.linalg in the futrue?

**Comment by rgommers** [comment]
Please have a look at PR gh-6831. Any testing/feedback on that PR would be very welcome.

**Comment by ilayn** [comment]
Indeed, if you have LAPACK version 3.5.0 and higher, it would be really good to have some feedback.
