### ISSUE TITLE
Is SciPy website under any maintenance? Can't open it since yesterday!

### ISSUE THREAD

**Issue by nicholashub** [scipy/scipy#7172]

**Comment by person142** [comment]
Already being tracked here: https://github.com/numpy/numpy/issues/8779.

**Comment by nicholashub** [comment]
Just wonder if there is any mirror website to access the old version?

**Comment by WarrenWeckesser** [comment]
The Internet Archive has a snapshot of the 0.18.1 documentation: http://web.archive.org/web/20161216070200/https://docs.scipy.org/doc/scipy/reference/
