### ISSUE TITLE
Document site for scipy shows me internal error

### ISSUE THREAD

**Issue by LeeKyungMoon** [scipy/scipy#7176]
Is it because of my computer or network state  OR the site is now really dead?

I fount this situation with this [url](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.optimize.minimize.html) (because I needed to reference scipy.optimize.minimize function)

**Comment by JelteF** [comment]
The site is also down for me

**Comment by rkern** [comment]
Tracked here: numpy/numpy#8779
