### ISSUE TITLE
scipy.org site is down, cannot you fix it?

### ISSUE THREAD

**Issue by Felix-neko** [scipy/scipy#7177]
Me and my students are starving without your manuals, please help us!!!

^__^

**Comment by Rubenkl** [comment]
Agree!!

**Comment by gp1313** [comment]
Agree!!!!

**Comment by ev-br** [comment]
If you build the docs and upload them somewhere public, please make the location of this unofficial mirror known.

**Comment by Moisan** [comment]
The [wayback machine has SciPy 0.18.1 documentation](http://web.archive.org/web/20161216070200/https://docs.scipy.org/doc/scipy/reference/).

**Comment by ben-albrecht** [comment]
It looks like this is a known issue -- see https://github.com/numpy/numpy/issues/8779 for more details.

**Comment by Naereen** [comment]
Just to precise, the scipy.org website is up, only the docs.scipy.org seems blocked (500 internal server error). No hurry, the world will survive without the docs :smile:

Good luck to the nice sysadmin! Thanks in advance!

**Comment by mlliarm** [comment]
A proxy server should solve your issue:

[SciPy 0.19.0 via hide.me proxy](https://proxy-nl.hideproxy.me/go.php?u=N%2BHrt7pFDYHRh2aGPtIvZzMFS6xVqWjVuiJ8V192lT4qJMR3Yvl0&b=5&f=norefer)
