### ISSUE TITLE
Add guidance on error/warning/exception handling patterns and best practices

### ISSUE THREAD

**Issue by thunderfish24** [scipy/scipy#7183]
I could not easily find information on what to expect from scipy in terms error/warning/exception handling patterns and best practices, either as a consumer or a contributor.

I looked here: http://scipy.github.io/devdocs/hacking.html
and here: http://scipy.github.io/devdocs/dev/index.html

**Comment by person142** [comment]
Not sure what you mean. Maybe an example would help?

**Comment by thunderfish24** [comment]
So numpy has settings for how to handle floating point errors [here](https://docs.scipy.org/doc/numpy/reference/routines.err.html). In a "typical" scipy routine, what should cause a warning vs. an exception, and what about returning a separate error value/boolean from a computation vs. simply having a nan for the output to signify something went wrong? How can the python logger be leveraged effectively, if desired? What design pattens allow a scipy consumer flexibility in detecting, handling, and logging warnings and errors?

**Comment by josef-pkt** [comment]
I have never seen any written down or spelled out policy for this.

based on my experience:

- numpy still applies, e.g. Zero Division Warnings in any code depend on the numpy settings
- incorrect user input that is not usable raises an Exception, ValueError or similar, This can be either explicit in the scipy function or via numpy if for example shapes don't match.
- vectorized functions return np.nan in positions that cannot be computed to a specific value
- np.inf is mostly just a regular float and not a value to check for
- optional checks can raise if condition applies, e.g. isfinite check in linalg or nan_policy now in stats
- specific computational problems like nonconvergence in optimize or integration problems might just issue a specific warning

basic principle: 
If the user input is ambiguous or there no useful computations can be performed, then raise.  
If there is a problem, but the computation still contains useful information, then warn or return nan and let the users check it. (e.g. nonconvergence or vectorized)

**Comment by person142** [comment]
Also a note on

> So numpy has settings for how to handle floating point errors

As of 0.19 `scipy.special` has a similar style of error handling:

https://scipy.github.io/devdocs/special.html#error-handling

**Comment by person142** [comment]
Also as this isn't a bug the mailing list would probably be a more appropriate place for this discussion.

**Comment by thunderfish24** [comment]
Thanks for your feedback here. I'm looking into the mailing list option for ideas around formulating best practices.

**Comment by josef-pkt** [comment]
The dev mailing list would be the appropriate location to discuss whether this can or should be spelled out. My impression is that it is largely an implicit policy.

(related aside: statsmodels is suffering from "organic growth" in this area without systematic review or policy and insufficient unit tests for flags, warnings and exceptions if problems show up https://github.com/statsmodels/statsmodels/issues/3520
scipy is much better but I would expect that it still has some inconsistencies)
