### ISSUE TITLE
Dev wheels not uploaded?

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#7188]
https://github.com/pandas-dev/pandas/pull/15689#issuecomment-287102737 noticed that out wheels on http://travis-dev-wheels.scipy.org/ are from June. Did something break in the upload machinery?

**Comment by pv** [comment]
Relevant travis log:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/210116723/log.txt

**Comment by jreback** [comment]
thanks @ev-br

**Comment by pv** [comment]
Out of date issue, no problem no longer.
https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com
