### ISSUE TITLE
interpolation.map_coordinates() infinite loop

### ISSUE THREAD

**Issue by shapovalov** [scipy/scipy#7189]
I am not sure if the function supports multiple-channel images. I tried to test it with the code:
```
tmp = np.ones((5,4,3))
sp.ndimage.interpolation.map_coordinates(tmp, np.array([[1,1,None]]).T)
```
which seems to enter an infinite loop. Probably it should not, regardless of support of that feature.

**Comment by person142** [comment]
Could you make that example self-contained (what is `tmp`)?

**Comment by shapovalov** [comment]
Sorry, formatting issue. It’s fine now.

**Comment by pv** [comment]
That results to
```
Traceback (most recent call last):
     ...
RuntimeError: coordinate array data type not supported
```

**Comment by shapovalov** [comment]
For me, it never stops. 
I use OSX, Python 3.5.1, numpy 1.10.4, scipy 0.17.0.

**Comment by ev-br** [comment]
I can confirm that it hangs with scipy 0.17.1 and 0.18.0, but produces the same error as for Pauli above with the -dev version. Time to upgrade?

**Comment by shapovalov** [comment]
Same problem with 0.19.0, but if it has been fixed later, great.

**Comment by pv** [comment]
Appears to have been fixed.
