### ISSUE TITLE
New implementation of NNLS

### ISSUE THREAD

**Issue by alexfields** [scipy/scipy#7194]
I made [a new implementation of NNLS](http://github.com/alexfields/nnls) that is faster and more memory efficient in some cases, e.g. when `A` is sparse. The core algorithm is the same as the previous FORTRAN implementation but the function arguments are slightly different (instead of `A` and `b`, pass `A.T.dot(A)` and `A.T.dot(b)`).

This is perhaps related to #5165 although unlike that implementation, the results here are in general within tolerance of the results from the original FORTRAN `nnls` function. This version is written in pure numpy. For dense inputs, the original FORTRAN implementation is likely faster, but there can be significant speedup (and lower memory footprint) for sparse `A`, in the common case that `A` has many more rows than columns.

Would this be appropriate for inclusion in scipy.optimize?

**Comment by nmayorov** [comment]
Sparse solver is already implemented in `lsq_linear`, with options to specify lower and upper bounds on the variables. I'm not sure it would make sense to include another similar functionality.

**Comment by pv** [comment]
Closing, please reopen if there's something to do here.

**Comment by alexfields** [comment]
Sorry for slow response...
You are correct that `lsq_linear` offers some similar functionality, but by that argument I fail to see why `nnls` is included at all. `lsq_linear` uses a totally different algorithm compared to `nnls`. My implementation of `nnls` is close to the FORTRAN version, and as far as I can tell delivers identical results, but in some contexts can be faster with lower memory footprint. `lsq_linear` does not always deliver identical results to `nnls`.

**Comment by nmayorov** [comment]
`nnls` was added quite a long time ago an `lsq_linear` is a recent addition.

Am I correct that you propose an algorithm which follows the same main loop as original `nnls` but applies iterative linear solvers? I guess it can be included, if 

1. You rewrite it using `scipy.linalg.sparse.LinearOperator`.
2. Fit it into the existing `nnls` function.
3. Provide some reference or thorough explanation why it works + tests of course.
