### ISSUE TITLE
Logistic regression with fmin_bfgs

### ISSUE THREAD

**Issue by ali73** [scipy/scipy#7197]
Hi there.
I'm having a problem with scipy.optimize.fmin_bfgs function:
I am trying to do some logistic regression and here are  my cost function and hypothesis function and gradient :
`

    import numpy as np
    from matplotlib import pyplot as pplot
    import scipy.optimize
    def hypothesis(Theta, X):
        temp = Theta.dot(X)
        return 1 / (1 + np.e ** (temp * -1))

    def cost_fucntion(Theta, X, Y):
        result = []
        for x, y in zip(X, Y):
            hypo = hypothesis(Theta, x)
            temp = -1 * y * np.log10(hypo) - (1 - y) * (np.log10(1 - hypo))
            result.append(temp)
        return sum(result) / len(X)

    def gradient(Theta, X, Y):
        grad = []
        length = len(Theta)
        for i in range(length):
            tmp = 0
            for x, y in zip(X, Y):
                tmp += (((hypothesis(Theta, x) - y) * (x[i])) / length)
            grad.append(tmp)
        return np.array(grad)`
    
Then I read data from file and normalize them and these are all ok.But when I try to use fmin_bfgs function the return value from bfgs is the exact theta that I pass to it as argument in both these ways of calling:
` Theta = scipy.optimize.fmin_bfgs(cost_fucntion, theta, gradient, args=(EInput, Gold))`
and 
`        myTheta = scipy.optimize.fmin_bfgs(cost_fucntion, theta, args=(EInput, Gold))`
And I get this message at the end :
`        
         Optimization terminated successfully.
         Current function value: 0.203524
         Iterations: 16
         Function evaluations: 630
         Gradient evaluations: 21`

**Comment by pv** [comment]
Usage questions are best asked on stackoverflow.
Tou gradient function does not look right.
