### ISSUE TITLE
Permission denied error on scipy install using pip

### ISSUE THREAD

**Issue by viv1ag** [scipy/scipy#7201]
Dear concern,

I am not able to install SCIPY using PIP on Window7. See below error:
_IOError: [Errno 13] Permission denied: 'c:\\users\\agarwalv\\appdata\\local\\tem
p\\pip-build-xovn5r\\scipy\\tools/ci/devdocs-deploy.key.enc'_

Screen shot of command prompt is also attached for further investigation.
![scipy install](https://cloud.githubusercontent.com/assets/878291/24093441/d99ddd18-0d79-11e7-9a4f-01f628537607.JPG)

Please help here; I was not able to get any useful information on Goggle regarding the same.

Thanks,
Vivek Agarwal

**Comment by e-q** [comment]
Scipy cannot be installed via pip on windows, see [the installation instructions](https://scipy.org/install.html), gh-5461, and many more.

**Comment by viv1ag** [comment]
Oh sorry & thanks for pointing me other useful links. I have successfully installed scipy on window using this link: http://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy
