### ISSUE TITLE
`integrate.quad` fails silently on pulse type functions with long zero tails

### ISSUE THREAD

**Issue by benjaminrose** [scipy/scipy#7204]
Looking at a function like a step function but reversed in x (y = 1 if x is less than or equal to 0) `integrate.quad` has a silent failure. Here is a simple example of the failure.

```python
>>> from scipy import integrate
>>> y = lambda x: 1 if x<=0 else 0
>>> integrate.quad(y, -1, 1)
(1.0, 1.1102230246251565e-14)     # perfect!
>>> integrate.quad(y, -1, 100)
(1.0000000002199108, 1.0189464580163188e-08)     # we lost precision
>>> integrate.quad(y, -1, 10000)
(0.0, 0.0)    # this is not correct
```

With more and more trailing zero's in the function, it gets harder for `quad` to find the non-zero values at the start. 

This issue might be related to the issue about QUADPACK losing precision when used over large intervals, #5428. Pulse functions are also discussed in #4264, but there they are using `integrate.simps`, and integration does appear to work with sample-based methods (like `.romb` and `.simps`) assuming you correctly samples the pulse. 

We may just want to add this limitation to the documentation (along with an example as desired in #7168) rather than try to find a generic way to fix it.

**Comment by person142** [comment]
> We may just want to add this limitation to the documentation

I think this is the way to go. Expecting a quadrature routine to find the support of the function it's supposed to be integrating is not a reasonable expectation.

**Comment by benjaminrose** [comment]
Should I add this comment to the notes section of the documentation or as an example?

**Comment by pv** [comment]
Maybe an example?
.
It's probably not so easy to give a precise statement on when the method 
will work --- the issue is probably not only in finding the support but 
also in finding sharp features in general.
