### ISSUE TITLE
Memory use in integrate.quad in scipy-0.19.0

### ISSUE THREAD

**Issue by Dih5** [scipy/scipy#7214]
After updating Scipy to 0.19.0 I have experienced an increase in memory consumption which seems to be related to integrate.quad. The following code calculates some quadratures and checks the available RAM before and after:
```Python
import numpy as np
from scipy.integrate import quad
import psutil
import gc

xx_max = np.linspace(1,1000,num=100)
print("Memory available: %f GiB"%(psutil.virtual_memory().available/1024.**3))
[[quad(lambda x:x**2,0,x) for x in xx_max] for _ in range(3000)]
print("Memory available after quad: %f GiB"%(psutil.virtual_memory().available/1024.**3))
gc.collect()
gc.collect()
gc.collect()
print("Memory available after garbage collecting: %f GiB"%(psutil.virtual_memory().available/1024.**3))
```
When I run this with scipy 0.19 I find my system losses around 1GiB, while this does not happen if I use the prior release instead. The memory is freed after the process exists, but asking the garbage collector to do its work does not help.
The system I used is a 64-bit Arch Linux, using both python2 and python3 from clean virtualenvs.

**Comment by pv** [comment]
Fix in gh-7214

**Comment by guillochon** [comment]
@pv Could release this as a patch for scipy ASAP? It's a pretty major leak that makes 0.19.0 completely unusable for me (I've banned the version in my install stacks).

**Comment by rgommers** [comment]
@guillochon a 0.19.1 release will be out shortly, sorry for the delay
