### ISSUE TITLE
Transpose of a sparse matrix

### ISSUE THREAD

**Issue by ds2268** [scipy/scipy#7218]
When I create for example a csr_matrix like [here](https://docs.scipy.org/doc/scipy-0.16.1/reference/generated/scipy.sparse.csc_matrix.html) and then transpose this matrix. All the indices of the rows are 0.

For example:

A = [[1, 0, 2],
       [1, 0, 3],
       [4, 5, 6]] 

type(A) = <class 'scipy.sparse.csr.csr_matrix'>

A[0].indices -> array([0, 2], dtype=int32)

A.T[0].indices -> array([0, 0, 0], dtype=int32)

instead of array([0, 1, 2], dtype=int32)

Is there anything that I am doing wrong or is this a bug ? :)

**Comment by pv** [comment]
The transpose is a CSC matrix.

**Comment by ds2268** [comment]
Is then there any nicer way to get the same compared to:

(A.T).tocsr() -> this works fine

**Comment by perimosocordiae** [comment]
Nope, that's the recommended approach if you want to get the transpose in CSR format.
