### ISSUE TITLE
String Formatting Issue in LinearOperator.__init__

### ISSUE THREAD

**Issue by ben-e-whitney** [scipy/scipy#7220]
Running
```
scipy.sparse.linalg.LinearOperator(shape=(1, 1, 1), matvec=lambda v: v)
```
causes a `TypeError` to be raised in the course of raising a `ValueError` for the invalid `shape`. The cause is the unpacking of `shape` in the formatting of the `ValueError`'s error message:
```
raise ValueError("invalid shape %r (must be 2-d)" % shape)
```
We can avoid the `TypeError` by wrapping `shape` in a tuple:
```
raise ValueError("invalid shape %r (must be 2-d)" % (shape,))
```

**Comment by WarrenWeckesser** [comment]
Thanks for reporting the problem.  Would you be interested in submitting a pull request with the fixed code?

**Comment by ben-e-whitney** [comment]
Yes. A quick search of the codebase turns up some other places where the same pattern is used. Should I change those (assuming I can produce errors) in the same pull request, or open new issues?

**Comment by WarrenWeckesser** [comment]
Thanks!  Fixing several similar problems in one pull request sounds fine.
