### ISSUE TITLE
Cannot install SCIPY for Python 3.4 using PIP

### ISSUE THREAD

**Issue by kiann00** [scipy/scipy#7221]
Hello, I have managed to install Python 3.4, and Numpy using PIP install.

For some reason, I cannot get scipy to install/run properly. I use 'pip install scipy' , and I get the following error below.

Can someone advise? My machine is 64-bit Windows 10.

Kind regards

C:\Python34>pip install scipy
Collecting scipy
  Using cached scipy-0.19.0.zip
Installing collected packages: scipy
  Running setup.py install for scipy ... error
    Complete output from command c:\python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Kiann\\AppData\\Local\\Temp\\pip-build-0gb8i_zm\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Kiann\AppData\Local\Temp\pip-18a4dpkj-record\install-record.txt --single-version-externally-managed --compile:
Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)

    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['c:\\python34\\lib', 'C:\\', 'c:\\python34\\libs']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['c:\\python34\\lib', 'C:\\', 'c:\\python34\\libs']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    c:\python34\lib\site-packages\numpy\distutils\system_info.py:1051: UserWarning: Specified path C:\projects\numpy-wheels\windows-wheel-builder\atlas-builds\atlas-3.11.38-sse2-64\lib is invalid.
      pre_dirs = system_info.get_paths(self, section, key)
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    c:\python34\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
      libraries lapack not found in ['c:\\python34\\lib', 'C:\\', 'c:\\python34\\libs']
      NOT AVAILABLE

    c:\python34\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE

    c:\python34\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE

    Running from scipy source directory.
    non-existing path in 'scipy\\integrate': 'quadpack.h'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Kiann\AppData\Local\Temp\pip-build-0gb8i_zm\scipy\setup.py", line 416, in <module>
        setup_package()
      File "C:\Users\Kiann\AppData\Local\Temp\pip-build-0gb8i_zm\scipy\setup.py", line 412, in setup_package
        setup(**metadata)
      File "c:\python34\lib\site-packages\numpy\distutils\core.py", line 135, in setup
        config = configuration()
      File "C:\Users\Kiann\AppData\Local\Temp\pip-build-0gb8i_zm\scipy\setup.py", line 336, in configuration
        config.add_subpackage('scipy')
      File "c:\python34\lib\site-packages\numpy\distutils\misc_util.py", line 1001, in add_subpackage
        caller_level = 2)
      File "c:\python34\lib\site-packages\numpy\distutils\misc_util.py", line 970, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\python34\lib\site-packages\numpy\distutils\misc_util.py", line 907, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "c:\python34\lib\site-packages\numpy\distutils\misc_util.py", line 1001, in add_subpackage
        caller_level = 2)
      File "c:\python34\lib\site-packages\numpy\distutils\misc_util.py", line 970, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\python34\lib\site-packages\numpy\distutils\misc_util.py", line 907, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

    ----------------------------------------
Command "c:\python34\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Kiann\\AppData\\Local\\Temp\\pip-build-0gb8i_zm\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Kiann\AppData\Local\Temp\pip-18a4dpkj-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Kiann\AppData\Local\Temp\pip-build-0gb8i_zm\scipy\

**Comment by pv** [comment]
Cannot use pip for scipy on Windows. See https://scipy.org/install.html

**Comment by kiann00** [comment]
Hi, I tried using Anaconda to install Scipy then. But then I can't seem to access Scipy using the Python shell (3.4) and have to use Anaconda specifically.

Is there anyway to install Scipy such that it doesn't need to go via Anaconda?

Kind regards

**Comment by person142** [comment]
https://scipy.org/install.html#windows-packages

**Comment by dmr** [comment]
I receive the same error on debian with a custom python3.6.1 installation --> Which library is providing the "quadpack.h"-files?

**Comment by anne1994** [comment]
non-existing path in 'scipy\\integrate': 'quadpack.h'

**Comment by rgommers** [comment]
@dmr @anne1994 that's weird, may point to an actual problem. Can you please share a full build log (put in a gist and link to it)?

**Comment by anne1994** [comment]
@rgommers the only way it worked on my windows is by installing the entire anaconda packages 

my errors : https://gist.github.com/anne1994/277b69fa8b7b1e0a7c4cbaca08fa1dd6

**Comment by luirink** [comment]
i got the same issue with quadpack.h. I am working on ubuntu...

**Comment by rgommers** [comment]
@anne1994 ``quadpack.h`` is not the issue here. This is the end of your build log:

    non-existing path in 'scipy\\integrate': 'quadpack.h'
        Traceback (most recent call last):
    ....
          File "scipy\linalg\setup.py", line 20, in configuration
            raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

The first line is just a warning. The traceback correctly points out the real issue: "no lapack/blas resources found". So you have to install the ``atlas`` and ``atlas-dev`` packages (or another BLAS/LAPACK if you prefer). See https://scipy.org/scipylib/building/linux.html#installation-from-source

**Comment by mablexum** [comment]
same error with you,Resolved by using this command:
python -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose
