### ISSUE TITLE
special.wrightomega test failure using numpy's master branch

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#7227]
The test suite using numpy's master branch has failed in several recent pull requests (https://github.com/scipy/scipy/pull/7222, https://github.com/scipy/scipy/pull/7211, https://github.com/scipy/scipy/pull/7190).  Here's the relevant output of the test:

```
======================================================================
FAIL: test_wrightomega.test_wrightomega_inf_branch
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/numpy/testing/utils.py", line 368, in assert_equal
    assert_equal(actuali, desiredi)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/numpy/testing/utils.py", line 393, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: -0.0
 DESIRED: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/scipy/special/tests/test_wrightomega.py", line 26, in test_wrightomega_inf_branch
    assert_equal(res, 0)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/numpy/testing/utils.py", line 370, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: -0j
 DESIRED: 0

----------------------------------------------------------------------
Ran 24211 tests in 515.918s

FAILED (KNOWNFAIL=91, SKIP=1881, failures=1)
```

**Comment by WarrenWeckesser** [comment]
I haven't looked into the details, but I suspect the problem is related to https://github.com/numpy/numpy/pull/8388

Consider this, using numpy 1.12.1:

```
In [10]: from numpy.testing import assert_equal

In [11]: assert_equal(np.array(-0.0), 0)

In [12]: assert_equal(-0.0, 0)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-12-8315da2bce84> in <module>()
----> 1 assert_equal(-0.0, 0)

/Users/warren/miniconda3scipy/lib/python3.5/site-packages/numpy/testing/utils.py in assert_equal(actual, desired, err_msg, verbose)
    410         elif desired == 0 and actual == 0:
    411             if not signbit(desired) == signbit(actual):
--> 412                 raise AssertionError(msg)
    413     # If TypeError or ValueError raised while using isnan and co, just handle
    414     # as before

AssertionError: 
Items are not equal:
 ACTUAL: -0.0
 DESIRED: 0
```

If something is now returning the scalar -0.0 instead of np.array(-0.0), a test could fail that previously passed.

**Comment by WarrenWeckesser** [comment]
Here's the difference:

**numpy 1.12.1**

```
In [3]: from numpy.testing import assert_equal

In [4]: assert_equal(np.complex128(-0j), 0)
```
The assertion succeeds.

**numpy '1.13.0.dev0+c25db39'**

```
In [20]: from numpy.testing import assert_equal

In [21]: assert_equal(np.complex128(-0j), 0)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/Users/warren/miniconda3numpy/lib/python3.5/site-packages/numpy-1.13.0.dev0+c25db39-py3.5-macosx-10.6-x86_64.egg/numpy/testing/utils.py in assert_equal(actual, desired, err_msg, verbose)
    366         try:
--> 367             assert_equal(actualr, desiredr)
    368             assert_equal(actuali, desiredi)

/Users/warren/miniconda3numpy/lib/python3.5/site-packages/numpy-1.13.0.dev0+c25db39-py3.5-macosx-10.6-x86_64.egg/numpy/testing/utils.py in assert_equal(actual, desired, err_msg, verbose)
    392             if not signbit(desired) == signbit(actual):
--> 393                 raise AssertionError(msg)
    394     # If TypeError or ValueError raised while using isnan and co, just handle

AssertionError: 
Items are not equal:
 ACTUAL: -0.0
 DESIRED: 0

During handling of the above exception, another exception occurred:

AssertionError                            Traceback (most recent call last)
<ipython-input-21-8adfca176832> in <module>()
----> 1 assert_equal(np.complex128(-0j), 0)

/Users/warren/miniconda3numpy/lib/python3.5/site-packages/numpy-1.13.0.dev0+c25db39-py3.5-macosx-10.6-x86_64.egg/numpy/testing/utils.py in assert_equal(actual, desired, err_msg, verbose)
    368             assert_equal(actuali, desiredi)
    369         except AssertionError:
--> 370             raise AssertionError(msg)
    371 
    372     # Inf/nan/negative zero handling

AssertionError: 
Items are not equal:
 ACTUAL: (-0-0j)
 DESIRED: 0
```

So this looks like a numpy bug.

**Comment by WarrenWeckesser** [comment]
The numpy issue is https://github.com/numpy/numpy/issues/8848

**Comment by gfyoung** [comment]
Indeed, when comparisons involve complex numbers, we extract the real and imaginary parts and compare separately.  However, my PR changed the behavior to return scalar when scalar inputs were provided instead of `array`, which I thought was more intuitive.  Seems like that change revealed an old decision back in `numpy` to render `-0.0` different `0` but somehow that `np.array(-0.0)` is the same as `0`?  Wacky stuff...

In any case, I imagine that most of the discussion will continue in the associated `numpy` issue, so if people want to chime in from the `scipy` end, by all means.

**Comment by gfyoung** [comment]
I looked at the failing test to see what you were testing out, and it seems that you are also checking the sign-bit.  So while `numpy` does have its own set of inconsistencies that I discussed <a href="https://github.com/scipy/scipy/issues/7227#issuecomment-289380073">above</a>, I wonder if a temporary patch for `scipy` is to do the following:
~~~python
assert_(res == 0)
~~~
As it seems like you are just checking for value (and not the sign-bit), this assertion will do just fine in terms of ignoring the signed parts of the real / imaginary parts.

**Comment by person142** [comment]
> I wonder if a temporary patch for scipy is to do the following

Since this is pretty clearly a NumPy bug, I'd rather let things be fixed over there than make changes here, especially since the changes will only fix things on the current master branch and won't help compatibility of older versions of SciPy against new NumPy.

**Comment by gfyoung** [comment]
Well, not sure if we can classify this as a bug, because the code that is causing this test to fail was explicitly committed about eight years ago.  Also, my proposal at the very least will get things moving again on the `scipy` (with regards to PRs), as the "patch" for the `numpy` behavior isn't exactly clear.

**Comment by WarrenWeckesser** [comment]
In numpy 1.12.1 and older versions, it looks like the assertion `assert_equal(z, 0)` is "fussy" when `z` is a *real* scalar, but "sloppy" when `z` is an array or a complex scalar.

In numpy 1.12.1, the following raise an `AssertionError`:
```
assert_equal(-0.0, 0)
assert_equal(np.float64(-0.0), 0)
```
but these do not:
```
assert_equal(-0j, 0)
assert_equal(complex(-0.0, 0.0), 0)
assert_equal(complex(0.0, -0.0), 0)
assert_equal(complex(-0.0, -0.0), 0)
assert_equal(np.complex128(-0j), 0)

assert_equal(np.array(-0.0), 0)
```

In version '1.13.0.dev0+c25db39' of numpy, the complex cases above now raise the assertion error, but `assert_equal(np.array(-0.0), 0)` still does not.

I don't know how this will be resolved in numpy, but the difference in behavior with real and complex scalars does look like a bug.  I doubt the behavior of `assert_equal` with real scalars will change, so the most likely result is either "no change--we're stuck with this funky behavior to maintain backwards compability" or the tests with complex scalars become fussy (as in version '1.13.0.dev0+c25db39').  In the latter case, we'll have to fix the scipy test.

I suggest we change the `wrightomega` test anyway.  Either we change that one line to `assert_(res == 0)` as @gfyoung suggests (or perhaps `assert_equal(np.abs(res), 0)`), or rewrite the test such that it only uses real arguments in `assert_equal`.  The test would still be readable (i.e. we're not writing awkward code to handle different numpy behaviors), and should be compatible with old and new versions of numpy.

I'll create a pull request so we have some actual code to consider.

**Comment by gfyoung** [comment]
@WarrenWeckesser : All of those inconsistencies you pointed out boil down to the fact that `-0.0` and `0` are not considered the same under `assert_equal` because of the sign-bit.  Now why `np.array(-0.0)` and `0` are the same is unclear, but given how ingrained that behavior is, it might take some time before `numpy` resolves this inconsistency.

**Comment by WarrenWeckesser** [comment]
Either of these works with the development version of numpy:
```
def test_wrightomega_inf_branch_alt1():
    pts = [complex(-np.inf, np.pi/4),
           complex(-np.inf, -np.pi/4),
           complex(-np.inf, 3*np.pi/4),
           complex(-np.inf, -3*np.pi/4)]
    for p in pts:
        res = sc.wrightomega(p)
        assert_equal(np.abs(res), 0)  # <<< one line changed
        if abs(p.imag) <= np.pi/2:
            assert_(np.signbit(res.real) == False)
        else:
            assert_(np.signbit(res.real) == True)
        if p.imag >= 0:
            assert_(np.signbit(res.imag) == False)
        else:
            assert_(np.signbit(res.imag) == True)


def test_wrightomega_inf_branch_alt2():
    pts = [complex(-np.inf, np.pi/4),
           complex(-np.inf, -np.pi/4),
           complex(-np.inf, 3*np.pi/4),
           complex(-np.inf, -3*np.pi/4)]
    expected_results = [complex(0.0, 0.0),
                        complex(0.0, -0.0),
                        complex(-0.0, 0.0),
                        complex(-0.0, -0.0)]
    for p, expected in zip(pts, expected_results):
        res = sc.wrightomega(p)
        # We can't use assert_equal(res, expected) because in older versions of
        # numpy, assert_equal doesn't check the sign of the real and imaginary
        # parts when comparing complex zeros. It does check the sign when the
        # arguments are *real* scalars.
        assert_equal(res.real, expected.real)
        assert_equal(res.imag, expected.imag)
```
I find the second one easier to read.  Anyone else have a preference?
