### ISSUE TITLE
Sparse COO.toarray fails if nnz > 2**31

### ISSUE THREAD

**Issue by rth** [scipy/scipy#7230]
While handling of sparse arrays with more that 2**31 non zero elements was enabled in #442, it looks like the conversion from CSR to a dense array still fails in this case with an error in `coo_todense` .

```py
In [1]: import scipy.sparse
     .. import numpy as np
     .. X = scipy.sparse.csr_matrix(np.ones((2**16, 1)))
     .. X
Out[1]:
# <65536x1 sparse matrix of type '<class 'numpy.float64'>'
#        with 65536 stored elements in Compressed Sparse Row format>

In [2]: (X*X[:2**15-1].T).toarray()
Out[2]:
array([[ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       ...,
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.]])

In [3]: (X*X[:2**15].T).toarray()
ValueError                                Traceback (most recent call last)
<ipython-input-6-ee8192b524ea> in <module>()
----> 1 (X*X[:2**15].T).toarray()

/home/ec2-user/miniconda3/envs/test-env/lib/python3.6/site-packages/scipy/sparse/compressed.py in toarray(self, order, out)
    918     def toarray(self, order=None, out=None):
    919         """See the docstring for `spmatrix.toarray`."""
--> 920         return self.tocoo(copy=False).toarray(order=order, out=out)
    921
    922     ##############################################################

/home/ec2-user/miniconda3/envs/test-env/lib/python3.6/site-packages/scipy/sparse/coo.py in toarray(self, order, out)
    256         M,N = self.shape
    257         coo_todense(M, N, self.nnz, self.row, self.col, self.data,
--> 258                     B.ravel('A'), fortran)
    259         return B
    260

ValueError: could not convert integer scalar
```
**Note:** approximately 64 GB RAM is necessary to run this example.
 
Using numpy 1.12.1 and scipy 0.18.1 on Linux.

What would be the advised workaround in this case to convert a CSR array to a dense array? something along the lines of the function below? 

```py 
def csr_to_array_fallback(X):
    if X.format != 'csr':
        raise ValueError
    row_indices = np.zeros(len(X.indices), dtype='int32')
    indptr = X.indptr 
    for idx in range(len(indptr) - 1):
        row_indices[indptr[idx]:indptr[idx+1]] = idx
    Y = np.zeros(X.shape, dtype=X.dtype)
    Y[row_indices, X.indices] = X.data 
    return Y 
```

I believe this is, in particular, causing the following issues in scikit-learn,
  - http://stackoverflow.com/questions/42543125/could-not-convert-integer-scalar-error-when-using-dbscan
  - https://github.com/FreeDiscovery/FreeDiscovery/issues/126

cc @eugene-yang

**Comment by pv** [comment]
The correct fix would be to fix the casting logic, as integer scalars 
don't coerce.

**Comment by pv** [comment]
A better fix probably is to change all sparsetools integer scalars to 
npy_int64, it's a bit silly to cast the rows/cols arrays to bigger 
integer just to accommodate the nnz integer.

**Comment by rth** [comment]
> A better fix probably is to change all sparsetools integer scalars to
npy_int64, it's a bit silly to cast the rows/cols arrays to bigger
integer just to accommodate the nnz integer.

Thank you for your response! But wouldn't this use more memory (25% more in total) if row/cols arrays are always 64 bit?

**Comment by pv** [comment]
No, as only the nnz integer would be int64.
.
Basically, the task for someone interested would be to replace all 
integer scalar `I` by `npy_int64` in the sparsetools/*.h, scrap the 
now-unnecessary integer scalar type detection in sparsetools.cxx, and 
fix up the integer scalar type generation in `generate_sparsetools.py`.
.
This would have some impact on 32-bit platform performance, but I think 
those are not relevant any more.

**Comment by rth** [comment]
@pv Thanks for the suggestions. I will try to make a PR in the following days.

However if one needed to make this work with the currently installed version of scipy, could you suggest a fix? As far as I understand, the current issue is that [`coo_todense` expects a int32 for `nnz`](https://github.com/scipy/scipy/blob/2526df72e5d4ca8bad6e2f4b3cbdfbc33e805865/scipy/sparse/sparsetools/coo.h#L95)  and in the current version this cannot be fixed by writing some user methods in python, right ? Hence the `csr_to_array_fallback` attempt above that doesn't rely on `coo_todense` as a temporary fix. Unless I missed something? Thanks.

**Comment by perimosocordiae** [comment]
It might be worth giving your test case a try with the latest numpy master. gh-7081 added a new `csr_todense` function to sparsetools, which *might* solve the immediate problem. I can't say for sure though, because I don't have the RAM to run your example.

Fixing the int32 nnz issue is still worth doing, regardless.

**Comment by rth** [comment]
> It might be worth giving your test case a try with the latest numpy master. gh-7081 added a new csr_todense function to sparsetools, which might solve the immediate problem. 

Aww, that's great. Looks like that PR also addresses https://github.com/scikit-learn/scikit-learn/issues/516 ..

**Comment by rth** [comment]
> Basically, the task for someone interested would be to replace all
integer scalar `I` by `npy_int64` in the sparsetools/*.h, scrap the
now-unnecessary integer scalar type detection in sparsetools.cxx, and
fix up the integer scalar type generation in `generate_sparsetools.py`.

@pv I tried to look into it, but I'm must be misunderstanding something. Say we consider the [`csr_eliminate_zeros` function](https://github.com/scipy/scipy/blob/233c0ce63910f4eba6c31d95fa2a42ea0ac86e5b/scipy/sparse/sparsetools/csr.h#L1065)  do you mean that one should replace `const I n_row` by `const npy_int64 n_row` (as well as for `n_col`) but leave all the index arrays templated with the `I` dtype? But then if one also makes `nnz` `npy_int64` it does not make sense to keep `Ap` with a potential type `npy_int32`.

On the other hand, if one replaces all the `I` types by `npy_int64` (including for arrays) thus removing the `class I` templating, wouldn't it lead to more memory used to store the indices, possible performance cost, and breaking breaking compatibility for the Cython code relying on these functions? 

Generally, I don't understand why the above issue is happening with the current code. For instance `generate_sparsetools.py` currently generate the `csr_impl.h` below for the `csr_eliminate_zeros` function,
```c
static Py_ssize_t csr_eliminate_zeros_thunk(int I_typenum, int T_typenum, void **a)
{
    int j = get_thunk_case(I_typenum, T_typenum);
    switch (j) {
        // [..]
        case 13:
        (void)csr_eliminate_zeros<npy_int32,npy_double>(*(const npy_int32*)a[0], *(const npy_int32*)a[1], (npy_int32*)a[2], (npy_int32*)a[3], (npy_double*)a[4]);
        // [..]
        case 31:
        (void)csr_eliminate_zeros<npy_int64,npy_double>(*(const npy_int64*)a[0], *(const npy_int64*)a[1], (npy_int64*)a[2], (npy_int64*)a[3], (npy_double*)a[4]);
        // [..]
     }
}
```
I understand that case 13 could lead to overflows, but would the case 31  be equivalent to "replacing all
integer scalar `I` by `npy_int64` in the sparsetools/*.h"?  Thanks.

**Comment by romeric** [comment]
For what it is worth, changing the storage indices of the sparse matrix (i.e. `I` and `J`) to`npy_int64` would be silly as it dramatically increases (by a factor of 4 to be precise) the memory requirements for big sparse matrices. For example a sparse matrix which is `1GB` (which for finite element analyses is not that big at all) would require `4GB` of memory instead

**Comment by pv** [comment]
It's only necessary to change the scalars (nrows etc) to int64.

**Comment by rth** [comment]
> It's only necessary to change the scalars (nrows etc) to int64.

@pv Could you please illustrate this on an example?
Say we have,
```cpp
template <class I, class T>
void csr_diagonal(const I n_row,
                  const I n_col, 
	              const I Ap[], 
	              const I Aj[], 
	              const T Ax[],
	                    T Yx[])
{
    const I N = std::min(n_row, n_col);

    for(I i = 0; i < N; i++){
        const I row_start = Ap[i];
        const I row_end   = Ap[i+1];

        T diag = 0;
        for(I jj = row_start; jj < row_end; jj++){
            if (Aj[jj] == i)
                diag += Ax[jj];
        }

        Yx[i] = diag;
    }
}
```
Are you saying that one should convert `n_row`, `n_col`, `N`, `i`, `jj`, `row_start`, `row_end` to int64 while keeping `Ap`, `Ai` etc templated as `I` (i.e. int32 or int64)? But then the dtype of `row_start` is constrained  by `row_start = Ap[i]` which in turns constrains the loop index `jj`. Same thing for `Aj[jj] == i` which would lead to casting if they are not of the same dtype. So my point is that I don't see how can one change the scalars without changing the dtype of arrays containing indices (cf my [previous comment](https://github.com/scipy/scipy/issues/7230#issuecomment-294449019)).  Am I missing something? Thanks.

**Comment by perimosocordiae** [comment]
@rth The smallest fix would be to change the type of `nnz` from `I` to `int64` in `coo_todense` and `coo_matvec`. You'd need to update the local loop iteration variable type as well, but that's it.

**Comment by gokceneraslan** [comment]
@perimosocordiae This is I think the fix in #7435. It works quite nicely. Can you consider merging it then :)

**Comment by perimosocordiae** [comment]
Unfortunately that fix is still unverified (see the [comments starting here](https://github.com/scipy/scipy/pull/7435#issuecomment-304010955)), so we can't merge it yet.

**Comment by rgommers** [comment]
Some movement in gh-7435 would be great, but this is not critical for 1.0 so removing that milestone.
