### ISSUE TITLE
Add (reduced) magnetic flux quantum to constants

### ISSUE THREAD

**Issue by Phyks** [scipy/scipy#7235]
Hi,

What about adding the [magnetic flux quantum](https://en.wikipedia.org/wiki/Magnetic_flux_quantum) defined as `Phi_0 = scipy.constants.h / (2 * scipy.constants.e)` and the reduced magnetic flux quantum defined as `phi_0 = scipy.constants.hbar / (2 * scipy.constants.e)` to the list of available constants?

This values are very often when dealing with magnetic field and superconducting circuits (in quantum mechanical framework). I agree they are very easy to define from the available constants in Scipy, but one then needs to always have their expression in mind and start virtually every script by defining these constants.

It would be of great help to ease readability of such scripts. I can make a PR for this if it is worth it.

Thanks!

**Comment by rgommers** [comment]
Already present as ``constants.codata.value('mag. flux quantum')`` or ``constants.physical_constants['mag. flux quantum']``.

Not sure I like adding it as ``phi_0``, that's a very uninformative name and because it's a simple float you can't give it a docstring.

**Comment by Phyks** [comment]
I understand the point. Thanks for pointing out that it is already available, I missed it I guess.

In favor of `Phi_0`, this is a very common used symbol for this variable, although it may be used in a minority of fields. See e.g. [the dedicated Wikipedia page](https://en.wikipedia.org/wiki/Magnetic_flux_quantum) which makes use of this symbol.

**Comment by rgommers** [comment]
@Phyks maybe bring it up on the scipy-dev mailing list to get a decision?

**Comment by rgommers** [comment]
guess we're not doing this, closing.
