### ISSUE TITLE
genlaguerre poly1d-object doesn't respect 'monic' option at evaluation

### ISSUE THREAD

**Issue by oestfeldt** [scipy/scipy#7247]
Using Python 3.6 with Anaconda. Fresh install 2 weeks ago.

I'm using the funciton scipy.special.genlaguerre to generate the generalized laguerre polynomials. The function has the option 'monic' which scales the parameters, such that the leading parameter equals 1. 

The returned poly1d-object print correctly scaled, but evaluating the function does not correspond to the printed object. The default function (non-scaled) is always returned.

MWE:
`from scipy.special import genlaguerre`
` `
`gl1 = genlaguerre(1,1,monic=False)`
`gl2 = genlaguerre(1,1,monic=True)`
` `
`print(gl1)`
`print(gl2)`
` `
`print(gl1(0))`
`print(gl2(0))`

Output:
` ` 
`-1 x + 2`
 ` `
`1 x - 2`
`2.0`
`2.0`

**Comment by person142** [comment]
Problem is here:

https://github.com/scipy/scipy/blob/master/scipy/special/orthogonal.py#L130

In particular, in this block of code:

```python
        mu = sqrt(hn)
        if monic:
            evf = eval_func
            if evf:
                eval_func = lambda x: evf(x) / kn
            mu = mu / abs(kn)
            kn = 1.0
```

It scales `eval_func` by `kn`, which is correct--but then it redefines `kn = 1.0`, which undoes the scaling.
