### ISSUE TITLE
scipy.sparse.linalg.norm does not implement spectral norm

### ISSUE THREAD

**Issue by c-f-h** [scipy/scipy#7268]
It seems that this would be very easy to implement with a call to `svds` since the spectral norm is just the largest singular value. Are there any issues with this approach?

**Comment by rafalalgo** [comment]
Can I do it?

**Comment by rgommers** [comment]
@rafalalgo sure, no need to ask - if there's no comment from someone like "I'm working on this" or a linked PR, then you can always tackle an issue.
