### ISSUE TITLE
scipy.optimize.minimize BFGS method flattens unnecessarily?

### ISSUE THREAD

**Issue by mwaddoups** [scipy/scipy#7269]
I'm trying to use the scipy.optimize.minimize routine with column vectors instead of row vectors - minimal example below:

```
from scipy.optimize import minimize
import numpy as np

def func(x):
    return np.dot(x.T, x)

def jac(x):
    print "After processing: {}".format(x)
    return 2 * x

initial_value = np.ones((3, 1))
print "Initial {}".format(initial_value)
minimize(func, x0=initial_value, jac=jac)
```

This outputs:
```
Initial [[ 1.]
 [ 1.]
 [ 1.]]
After processing: [ 1.  1.  1.]
After processing: [-1. -1. -1.]
After processing: [  1.00000000e-04   1.00000000e-04   1.00000000e-04]
After processing: [  0.00000000e+00   0.00000000e+00   1.35525272e-20]
```

As you can see, the initial value vector is flattened in the code. This actually happens at  https://github.com/scipy/scipy/blob/v0.18.1/scipy/optimize/optimize.py#L903

This also leads to a requirement for your jacobian function to have flattened output as well.

Is there any reason we flatten here? If so, should the docs be clearer that only arrays rather than ndarrays should be passed? Otherwise this could be changed to work with column and row vectors.

As an addendum to my question -  if I wanted to test this change myself, I would fork, clone and build the scipy repo, make this change and then are there unit tests I can run? I'm solving a couple build issues atm as it's my first time so can't check this yet.

**Comment by mwaddoups** [comment]
I did manage to build and test this change and whilst all unit tests passed, my example script fails as this change in orientation effects a larger part of the routine - clear upon further inspection.

Perhaps the issue is simply coming from my mentality - when doing a lot of linear algebra with vectors I want everything to have dimension - e.g. (10, 1) vs (10, ). Is best practice in numpy/scipy to just work with (10,) and broadcast to row/column vectors if necessary? And will this take advantage of the benefits of vectorization as well?

**Comment by person142** [comment]
> Is best practice in numpy/scipy to just work with (10,) and broadcast to row/column vectors if necessary?

Generally yes, and just in my experience it's not necessary all that often. For example, we can write your code as:

```python
>>> from scipy.optimize import minimize
>>> import numpy as np
>>> def f(x):
...     return np.dot(x, x)
...
>>> def jac(x):
...     return 2*x
...
>>> minimize(f, x0=np.ones(3), jac=jac)
      fun: 2.7733391199176196e-32
 hess_inv: array([[ 0.83333333, -0.16666667, -0.16666667],
       [-0.16666667,  0.83333333, -0.16666667],
       [-0.16666667, -0.16666667,  0.83333333]])
      jac: array([ -2.22044605e-16,  -2.22044605e-16,  -1.11022302e-16])
  message: 'Optimization terminated successfully.'
     nfev: 3
      nit: 2
     njev: 3
   status: 0
  success: True
        x: array([ -1.11022302e-16,  -1.11022302e-16,  -5.55111512e-17])
```

**Comment by mwaddoups** [comment]
Yep, I think I agree just to stick with that practice. I rewrote my older code and as long as I remember that np.dot(X, y) where X is 2D and y is 1D is not necessarily the matrix product I do actually think it's more natural and rarely required.

I'm happy to close this as, at least based on what I can find, very few people seem to use these methods with 2D vectors.

Thanks for the response!
