### ISSUE TITLE
SCIPY installation trouble OSX 10.12.3

### ISSUE THREAD

**Issue by nanodots** [scipy/scipy#7270]
The package didn't install on OS X 10.12.3.
After looking around various web sources, the issue is something with Xcode command line tools.
From the terminal >xcode-select --install
this installed the command line tools and scipy eventually installed as the instructions.  

It would be nice to have this as a note or in a FAQ somewhere.

**Comment by matthew-brett** [comment]
This looks like the same problem as your report over at https://github.com/matplotlib/matplotlib/issues/8433 - did you try my suggestion there?

**Comment by nanodots** [comment]
Hi-
Yes, same issue.  the first response was to make this an issue with scipy , so I did.
I did try updating pip before I started.
 I eventually got the scipy  package to  install on my own and it was after doing the Xcode-select —install command. I mostly was just frustrated an annoyed and was hoping to save somebody else the same frustrations.
Best regards,
Randy


On Apr 6, 2017, at 9:45 AM, Matthew Brett <notifications@github.com<mailto:notifications@github.com>> wrote:


This looks like the same problem as your report over at matplotlib/matplotlib#8433<https://github.com/matplotlib/matplotlib/issues/8433> - did you try my suggestion there?

**Comment by matthew-brett** [comment]
Right - we are trying to understand why your problem happened, and hence reduce frustration of other users.

As you saw over at the the matplotlib version of this issue, the surprising thing was that you did not get a pre-compiled "wheel" package, that does not need the compilers in xcode, and we're trying to work out why, but we need you help.

Now you have upgraded pip, what do you now get for these commands:

```
pip --version
which python
python -c "import distutils.util; print(distutils.util.get_platform())"
```

**Comment by nanodots** [comment]
Ok, thanks.  I’ll try to help you debug stuff.

 pip --version
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)

 which python
/usr/local/bin/python

python -c "import distutils.util; print(distutils.util.get_platform())"
macosx-10.10-x86_64



On Apr 6, 2017, at 10:01 AM, Matthew Brett <notifications@github.com<mailto:notifications@github.com>> wrote:


Right - we are trying to understand why your problem happened, and hence reduce frustration of other users.

As you saw over at the the matplotlib version of this issue, the surprising thing was that you did not get a pre-compiled "wheel" package, that does not need the compilers in xcode, and we're trying to work out why, but we need you help.

Now you have upgraded pip, what do you now get for these commands:

pip --version
which python
python -c "import distutils.util; print(distutils.util.get_platform())"

**Comment by matthew-brett** [comment]
How odd.  

I guess you installed Python via homebrew?

Can you run this command:

```
pip install -vv --user --ignore-installed scipy > out.log
```

Let it run for about 20 seconds or so, then kill with Ctrl-C.  Then, can you post the `out.log` file somewhere where I can look at it - it will show the options that pip is trying and rejecting.

**Comment by nanodots** [comment]
Hi-
I’m pretty sure I just used the stock python with OS X.
I ran the command and put the out.log file on our cloud server:
https://cloud.nanofab.utah.edu/index.php/s/LJVSRxtk8F43hOQ
It’s about 206kb, let me know if you want this directly emailed.

-Randy



On Apr 6, 2017, at 10:25 AM, Matthew Brett <notifications@github.com<mailto:notifications@github.com>> wrote:


How odd.

I guess you installed Python via homebrew?

Can you run this command:

pip install -vv --user --ignore-installed scipy > out.log


Let it run for about 20 seconds or so, then kill with Ctrl-C. Then, can you post the out.log file somewhere where I can look at it - it will show the options that pip is trying and rejecting.

**Comment by matthew-brett** [comment]
The stock Python on OSX is in /usr/bin/python - so you're using something else.

The out.log file has these lines in:

```
  Using cached scipy-0.19.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
  Downloading from URL https://pypi.python.org/packages/72/eb/d398b9f63ee936575edc62520477d6c2353ed013bacd656bd0c8bc1d0fa7/scipy-0.19.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#md5=dde4d5d44a0274a5abb01be4a3cd486a (from https://pypi.python.org/simple/scipy/)
```

so the log file claims that it already downloaded, and presumably installed, scipy from a wheel (a binary package that does not need a compiler).

Also, I guess the command finished pretty quickly, because you can see at the end of the log that pip is installing from the binary wheel - otherwise you'd see signs of the compilation being set off.

I wonder whether the problem you had was with matplotlib, and not scipy.  For matplotlib, and Python 2.7, I believe you do need a compiler, because matplotlib depends on a package called subprocess32, that doesn't have any wheels built for it.  In fact, right at the end of your reported error message at https://github.com/matplotlib/matplotlib/issues/8433#issue-219737922 you can see that the error is coming from subprocess32.   So I think this is not a scipy install issue, but a matplotlib one.  Closing here, but please re-open if you disagree.

**Comment by nanodots** [comment]
Thanks for looking at this. I’m satisfied on my end.
Best,
Randy

On Apr 6, 2017, at 4:10 PM, Matthew Brett <notifications@github.com<mailto:notifications@github.com>> wrote:


The stock Python on OSX is in /usr/bin/python - so you're using something else.

The out.log file has these lines in:

  Using cached scipy-0.19.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
  Downloading from URL https://pypi.python.org/packages/72/eb/d398b9f63ee936575edc62520477d6c2353ed013bacd656bd0c8bc1d0fa7/scipy-0.19.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#md5=dde4d5d44a0274a5abb01be4a3cd486a (from https://pypi.python.org/simple/scipy/)


so the log file claims that it already downloaded, and presumably installed, scipy from a wheel (a binary package that does not need a compiler).

Also, I guess the command finished pretty quickly, because you can see at the end of the log that pip is installing from the binary wheel - otherwise you'd see signs of the compilation being set off.

I wonder whether the problem you had was with matplotlib, and not scipy. For matplotlib, and Python 2.7, I believe you do need a compiler, because matplotlib depends on a package called subprocess32, that doesn't have any wheels built for it. In fact, right at the end of your reported error message at matplotlib/matplotlib#8433 (comment)<https://github.com/matplotlib/matplotlib/issues/8433#issue-219737922> you can see that the error is coming from subprocess32. So I think this is not a scipy install issue, but a matplotlib one. Closing here, but please re-open if you disagree.
