### ISSUE TITLE
Interest in the adding the Daniell window to signal?

### ISSUE THREAD

**Issue by pwolfram** [scipy/scipy#7272]
Is there community interest in adding the Daniell window to `scipy.signal` (http://reference.wolfram.com/legacy/applications/timeseries/UsersGuideToTimeSeries/SpectralAnalysis/1.8.4.html)?

cc @vanroekel

**Comment by e-q** [comment]
Are you suggesting the addition of the window to the currently available window functions for spectral analysis, or windowing methods of smoothing Frequency- and time-domain data?

If the former, it seems that "Daniell" is another name for the rectangular, a.k.a. "boxcar", window, which is already available via `scipy.signal.boxcar`.

The latter I think could be useful; I've used code to this end in the past. (Usually, the [scipy-dev email list](scipy-dev@python.org) will get more responses about feature interest/requests)

**Comment by vanroekel** [comment]
I was not correct here on the window name.  The Daniell filter is indeed the boxcar window.  But for some time series spectral smoothing in earth science I am in need of a modified Daniell window, where the first and last weights in the window are reduced.  For example, in a five-point boxcar the weights would be
```
weights = [1/5, 1/5, 1/5, 1/5, 1/5]
```
In the modified Daniel filter the weights would be
```
weights = [1/8, 1/4, 1/4, 1/4, 1/8]
```
In my searching, this modified window is only used for power spectra smoothing in some earth science applications (e.g. NCL; https://www.ncl.ucar.edu/Document/Functions/Built-in/specx_anal.shtml).

Perhaps this window behavior could be mimicked with scipy.signal.tukey as well.

**Comment by rgommers** [comment]
New widely used window functions are welcome - a PR follow-up here could be nice. I will close this issue though, there's a huge amount of functionality we could add, and this is not high on our prio list. Thanks all.
