### ISSUE TITLE
scipy.interpolate._bspl.evaluate_spline gets wrong type

### ISSUE THREAD

**Issue by laborleben** [scipy/scipy#7273]
Full log message: 
> File "scipy/interpolate/_bspl.pyx", line 90, in scipy.interpolate._bspl.evaluate_spline (scipy\interpolate\_bspl.c:3017)
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'

The bug was triggered when a special case was added to the code in commit c07eb50. The origin of the bug is in the classmethod `construct_fast` in https://github.com/scipy/scipy/blob/0efe8d0a877a990c0adf059db67aa5d5b97c1849/scipy/interpolate/_bsplines.py#L219 which was added in commit 951eb6c9efc2338854f718e99de5f19b388c5a92.

The dtype of `self.t` is not checked and changed properly to np.double (see also https://github.com/scipy/scipy/blob/0efe8d0a877a990c0adf059db67aa5d5b97c1849/scipy/interpolate/_bsplines.py#L171). Probably dtypes of other values are not checked in this classmethod and similar classmethods.

**Comment by pv** [comment]
construct_fast by intent does not do any checking or casting of inputs, 
so the bug is in whatever calls construct_fast. Can you give a 
self-contained test case that exhibits this issue?

**Comment by laborleben** [comment]
Misbehavior can be triggered on all major platforms.

```PYTHON
import numpy as np
import matplotlib.pyplot as plt
from scipy import interpolate

def test():
    x = np.arange(0, 10)
    # x is converted to float32 and later not correctly converted to float64 (long)
    # which triggers the bug
    # comment the following line to make it work
    x = x.astype(np.float32)
    y = np.exp(-x/3.0)
    # kind='slinear' to select case where construct_fast is used
    f = interpolate.interp1d(x, y, kind='slinear', bounds_error=False, fill_value=0)
    xnew = np.arange(0, 9, 0.1)
    ynew = f(xnew)   # use interpolation function returned by `interp1d`
    plt.plot(x, y, 'o', xnew, ynew, '-')
    plt.show()

if __name__ == "__main__":
    test()
```

**Comment by ev-br** [comment]
The problem is in https://github.com/scipy/scipy/blob/master/scipy/interpolate/_bsplines.py#L504:

```
def _as_float_array(x, check_finite=False):
    """Convert the input into a C contiguous float array."""
    x = np.ascontiguousarray(x)
    if not np.issubdtype(x.dtype, np.inexact):
        x = x.astype(float) 
``` 

passes `np.float32` unchanged, while Cython code is only templated on C double and double_complex. 

The solution is to either upcast C floats to C doubles (ditto for np.float16) or bloat the low-level evaluations to also have an `np.float32`  specialization. I'd rather upcast, however for interp1d this is strictly speaking a backcompat break.

**Comment by ev-br** [comment]
For the reference, here's what the dtypes are in scipy 0.18.1, where `interp1d(..., kind='slinear')` delegates to `splmake`:

```
In [36]: for dt in (np.float16, np.float32, np.float64): 
    ...:        for ddt in (np.float16, np.float32, np.float64):
    ...:            ii = interp1d(x.astype(dt), x.astype(dt))       # linear
    ...:            r = ii(ddt(1.0))
    ...:            print(dt, ddt, r.dtype)
    ...:        print(" ")
    ...:
<class 'numpy.float16'> <class 'numpy.float16'> float16
<class 'numpy.float16'> <class 'numpy.float32'> float32
<class 'numpy.float16'> <class 'numpy.float64'> float64

<class 'numpy.float32'> <class 'numpy.float16'> float32
<class 'numpy.float32'> <class 'numpy.float32'> float32
<class 'numpy.float32'> <class 'numpy.float64'> float64

<class 'numpy.float64'> <class 'numpy.float16'> float64
<class 'numpy.float64'> <class 'numpy.float32'> float64
<class 'numpy.float64'> <class 'numpy.float64'> float64


In [37]: for dt in (np.float16, np.float32, np.float64):
    ...:        for ddt in (np.float16, np.float32, np.float64):
    ...:            ii = interp1d(x.astype(dt), x.astype(dt), kind='slinear')   # slinear
    ...:            r = ii(ddt(1.0))
    ...:            print(dt, ddt, r.dtype)
    ...:        print(" ")
    ...:
<class 'numpy.float16'> <class 'numpy.float16'> float16
<class 'numpy.float16'> <class 'numpy.float32'> float16
<class 'numpy.float16'> <class 'numpy.float64'> float16

<class 'numpy.float32'> <class 'numpy.float16'> float32
<class 'numpy.float32'> <class 'numpy.float32'> float32
<class 'numpy.float32'> <class 'numpy.float64'> float32

<class 'numpy.float64'> <class 'numpy.float16'> float64
<class 'numpy.float64'> <class 'numpy.float32'> float64
<class 'numpy.float64'> <class 'numpy.float64'> float64
``` 

So, `linear` tries to find a common dtype (`np.result_type`?), while `slinear` simply casts the argument to the dtype it was constructed with.
Meanwhile, `np.interp` simply upcasts everything to python `float` (scalars) / `np.float64` (array_like)

(It feels a bit silly to have three routines for linear interpolation, but that's beside the point)

Thoughts?

**Comment by laszukdawid** [comment]
Any reason why there's use of float64 by default in many interpolations? Shouldn't it be handled with the same precision that comes in?
For example conversion [1] breaks using Akima (after fixing few things in Akima's constructor).

[1] https://github.com/scipy/scipy/blob/29dbc361056df93fe659dcb7362fa2c0e647a14b/scipy/interpolate/interpolate.py#L656

**Comment by rgommers** [comment]
The ``'slinear'`` behavior makes more sense to me than the ``'linear'`` behavior. Upcasting to ``float64 always seems simpler though, and the consistency with ``PPoly`` and ``np.interp`` pointed out in gh-7279 is nice. I'm okay with either gh-7279 or the 0.18.1 ``'slinear'`` behavior, no strong preference.

> Any reason why there's use of float64 by default in many interpolations? Shouldn't it be handled with the same precision that comes in?

Because it's precise? Support for lower-precision dtypes can make sense (like memory critical calculations that don't lose a lot of precision internally), but in many cases in scipy it doesn't.

**Comment by laszukdawid** [comment]
> Because it's precise? Support for lower-precision dtypes can make sense (like memory critical calculations that don't lose a lot of precision internally), but in many cases in scipy it doesn't.

@rgommers Well, it's more precise, but still not precise. Besides in many calculations I doubt whether it makes much difference to have that extra digits after 6th decimal point. I've proven that in mine they don't matter and it would be beneficial to get use smaller precision, as I'm calculating splines hundreds/thousands times and any speed gain is much appreciated.

**Comment by rgommers** [comment]
> Besides in many calculations I doubt whether it makes much difference to have that extra digits after 6th decimal point.

6 decimals, that strongly depends on the application. In Scipy there are a lot of places where ``float32`` input to a function returns ``float32`` output, but intermediate calculations are done in ``float64`` for various reasons (including precision loss). Such a solution wouldn't really help with your desire for speed gain.

**Comment by rgommers** [comment]
Other opinions? Would like this resolved to merge (or change) gh-7279, which is tagged to go into 0.19.1

**Comment by PaulKuin** [comment]
Regardless of the choice, I do not check all the types I use all the time. My aim is to get a result, so I cut corners and I find the dropping of sanity checks in the software of concern.  I would suggest always upcasting for sanity reasons, though I suppose there will be an impact of users who are stuck to 32-bit machines (like there are in many developing countries).

**Comment by charris** [comment]
Back in the days of the VAX, single precision was about 4x faster than double, but these days it can be slower unless cache effects or AVX are in play. That probably probably isn't the case for interpolation.

**Comment by stefanv** [comment]
It looks like there is a route for working around the issue right now, by casting float32 to float64, without introducing any major concerns.  I'd vote to go in that direction.

**Comment by rgommers** [comment]
Thanks for the input all, looks like we're merging gh-7279 as is.

**Comment by laszukdawid** [comment]
Eh. Now I regret leaving PC for few days... and missed to veto by minutes.

In general I agree that default should be upcasting, but there should be also an option to preserve whatever type comes in. If someone doesn't care about the type of results, give them the best precision you have. But, if it is explicitly asked for float16, then why upcast, calculate and downcast? Bit of waste, isn't it?
I'd suggest (in future):
```python
def spline(x, preserve=False)
    dtype = x.dtype if preseve else np.float64
    return calculate_spline(x.astype(dtype))
```

**Comment by rgommers** [comment]
> But, if it is explicitly asked for float16, then why upcast, calculate and downcast? Bit of waste, isn't it?

I suspect we won't consider ``float16`` at all, but may consider ``float32``. There's only so many type specializations we can add to the templated Cython code. If it's important then we can still add the ``preserve`` option you suggest in a future release. For now we needed to fix the regression though, and in general upcasting is a sensible thing to do.
