### ISSUE TITLE
optimize.OptimizeResult AttributeError: 'maxcv'

### ISSUE THREAD

**Issue by tomaso909** [scipy/scipy#7281]
I am using scipy v0.18.

I run optimize.minimize with 'SLSQP' method using bounds and constrains. After the minimization is completed successfully, I try to access the 'maxcv' property of the OptimizeResult object and I get AttributeError. I am able to access the rest of attributes though.

**Comment by tomaso909** [comment]
I have checked the source code of slsqp.py and it does not pass a maxcv argument to OptimizeResult:

`    return OptimizeResult(x=x, fun=fx, jac=g, nit=int(majiter), nfev=feval[0],
                          njev=geval[0], status=int(mode),
                          message=exit_modes[int(mode)], success=(mode == 0))`

Other methods, like COBYLA, do pass a value:

`    return OptimizeResult(x=xopt,
                          status=int(info[0]),
                          success=info[0] == 1,
                          message={1: 'Optimization terminated successfully.',
                                   2: 'Maximum number of function evaluations has '
                                      'been exceeded.',
                                   3: 'Rounding errors are becoming damaging in '
                                      'COBYLA subroutine.',
                                   4: 'Did not converge to a solution satisfying '
                                      'the constraints. See `maxcv` for magnitude '
                                      'of violation.'
                                   }.get(info[0], 'Unknown exit status.'),
                          nfev=int(info[1]),
                          fun=info[2],
                          maxcv=info[3])`

So I guess, that is the issue. I will see if it makes sense to pass a maxcv property with the slsqp method and contribute with it.

**Comment by awa5114** [comment]
Has this been fixed? what's the status...

**Comment by iffanh** [comment]
This attribute is still not available for SLSQP. I am still getting this attribute error.

**Comment by mdhaber** [comment]
The problem is that the documentation of `OptimizeResult` suggests that all of the outputs it lists will be present. That is not supposed to be the case. For instance, solvers that don't use gradients won't report the gradients. I will clarify this.

One could ask for `maxcv` to be reported by SLSQP (and presumably all solvers that supports any kind of constant), but that would be a separate issue.
