### ISSUE TITLE
optimize.minimize(method='SLSQP') constrain violation

### ISSUE THREAD

**Issue by tomaso909** [scipy/scipy#7282]
I have tried to run a multivariate, constrained and bounded optimization with both, optimize.minimize(method='SLSQP') and optimize.fmin_slsqp(). Indeed I get the same result:

For some initial guess for the independent variables x0, I get a converged solution where my equality constraints are satisfied (all equal to 0). However, for some initial guess values x0 I also get a converged solution ( 0 : Optimization terminated successfully) but when I check the equality constraints, they are not zero.

**Comment by pv** [comment]
The constraints are satisfied only up to some numerical tolerance, given
as a parameter to the algorithm. Is that the issue?

**Comment by pv** [comment]
As always, providing a self-contained example eliminates unnecessary back-and-forth:
http://sscce.org/

**Comment by tomaso909** [comment]
The constrain residuals are [-4098.2, -17809.9, -47707.2].
My code is quite complex but I am preparing a self contained case right now.

**Comment by tomaso909** [comment]
I save the residuals (equality constraints function result) in a global variable at each evaluation. I check this variable at the end of the optimization process to check if the constraints are actually met. This workaround is ok for me.

**Comment by pv** [comment]
Reopening (workaround should not be necessary)

**Comment by pv** [comment]
A reproducible test case would still be useful (there's not much that can be done with the information at hand).

**Comment by pv** [comment]
No reply, closing.

**Comment by pv** [comment]
No follow-up, and some SLSQP bugs have been fixed, so closing.
