### ISSUE TITLE
fsolve docs should say it doesn't handle over- or under-determined problems

### ISSUE THREAD

**Issue by vanzandtj** [scipy/scipy#7291]
I have a MATLAB program that uses fsolve() from the optimization
toolbox.  I found that scipy offers a similar function.  I spent a fair
amount of time translating my program into Python, only to discover that
the scipy implementation (unlike the MATLAB one) requires that the
number of functions and the number of variables be equal.  The
documentation for the underlying minpack programs (hybrd and hybrj)
makes this clear, but the scipy documentation does not.  It should.  I
suggest the following patch.  (Please view the original text.  The site insists on adding bullets.)

(It might also be a good idea to mention leastsq, which can
handle an over- or under-determined problem.)

```
  --- scipy/optimize/minpack.py-prev	2017-04-10 20:10:35.252918140 -0400
  +++ scipy/optimize/minpack.py	2017-04-10 20:11:32.605216345 -0400
  @@ -56,9 +56,10 @@
   
       Parameters
       ----------
       func : callable ``f(x, *args)``
  -        A function that takes at least one (possibly vector) argument.
  +        A function that takes at least one (possibly vector) argument,
  +        and returns a value of the same length.
       x0 : ndarray
           The starting estimate for the roots of ``func(x) = 0``.
       args : tuple, optional
           Any extra arguments to `func`.
```

**Comment by rgommers** [comment]
> The site insists on adding bullets.

Either a 4 space indentation or using enclosing triple backticks fixes that.

Patch and suggestion seem fine to me. It would be helpful though to submit this as a pull request; otherwise it could take a while for anyone to do that for you.

**Comment by sudheerachary** [comment]
I submitted a PR [#8618](https://github.com/scipy/scipy/pull/8618) with given changes please review for any further changes. Thanks.

**Comment by ev-br** [comment]
fixed by https://github.com/scipy/scipy/pull/8618
