### ISSUE TITLE
Scipy.io.loadmat loads matrices as int16 or uint16 by default. 

### ISSUE THREAD

**Issue by gtm2122** [scipy/scipy#7298]
I was trying to load matrices (raw images) into ndarray using scipy.io.loadmat(), I thought by default all variables undergo 64 bit floating point operations, but it looks like scipy.io.loadmat() loads .mat arrays by default to uint16 or int16, I was wondering if this is a problem with me ?

**Comment by matthew-brett** [comment]
Yes, MATLAB loads the variables that way, but Python, by default, loads the numbers as they were saved by MATLAB.    If you want the MATLAB behavior, use the `mat_dtype` kwarg to `loadmat`.

**Comment by sethtroisi** [comment]
Closing old issue with workaround for issue
