### ISSUE TITLE
stats.describe with nan_policy=omit returns matrix-wide minmax instead of column-wide

### ISSUE THREAD

**Issue by 1kastner** [scipy/scipy#7303]
from scipy import stats
    import numpy as np
    b = [[3, 4, np.nan], [5, 6, 7]]
    stats.describe(b, nan_policy="omit")

The DescribeResult response shows 3 as minimum and 7 as maximum, even though all other statistics are reported column-wise, e.g. the means are 4, 5, 7 and the variance is 2, 2, -. 

The scipy version at hand is 0.19.0 and numpy is 1.11.3.

**Comment by WarrenWeckesser** [comment]
A simple fix is in https://github.com/scipy/scipy/pull/13184

**Comment by 1kastner** [comment]
Oh, this thing is still alive... Let's hope some fix will be accepted soon.
