### ISSUE TITLE
Have eigh check for hermitian/symmetric

### ISSUE THREAD

**Issue by pdhorn** [scipy/scipy#7308]
A colleague had a bug in her program that we finally traced down to her call of `linalg.eigh`. If your input is not symmetric/Hermitian, `eigh` will return incorrect eigenstuff.

I'd suggest having `eigh` check that the input is symmetric/Hermitian.  Seems easy to accomplish, here's a suggestion for the beginning of `eigh`:

`if not numpy.allclose(a, numpy.asmatrix(a).H):`
`    raise ValueError('expected symmetric or Hermitian matrix,\`
`                         try using numpy.linalg.eig instead')`

(sorry about the indentation!)

I tried contributing but got bogged down in installing Fortran, missing packages, etc.  Would greatly appreciate if someone would take this up. Thanks!

**Comment by adivijaykumar** [comment]
If not an error, it would be nice if it threw a warning at least. I faced the same problem a few months ago.

**Comment by ilayn** [comment]
This might be a documentation issue but the behavior is consistent. It is standard LAPACK behavior and the `lower` keyword is actually used to pick up the part of interest. As an example, you can pack two symmetric matrices in one array by just selecting upper/lower parts.

**Comment by adivijaykumar** [comment]
Okay, but at first glance (and for a novice user), the documentation says 

> Solve an ordinary or generalized eigenvalue problem for a complex Hermitian or real symmetric matrix

I think there should be something in the documentation that explains what happens when anything other than Hermitian Matrix is passed.

**Comment by perimosocordiae** [comment]
I agree that this should be a documentation fix. Most users aren't very familiar with LAPACK.
