### ISSUE TITLE
io.FortranFile write_record assumes all items in iterable have same size

### ISSUE THREAD

**Issue by gauteh** [scipy/scipy#7318]
Hi,

the `FortranFile.write_record` method assumes that all members of an iterable have the same size, so that if you want to write say `[np.float32(a), np.float32(b), np.int32(c)]` they will no longer be read correctly by Fortran as if they had been written with `WRITE (...) A,B,C`. The following code is a suggestion for how to correctly calculate the size of the array and write the elements correctly.

> the `isinstance (s, collections.Iterable)` might not catch all `__getitem__` capable containers.

```
    def _write_record (s):
      import collections

      hdt = fd._header_dtype
      if isinstance (s, np.ndarray) or not isinstance (s, collections.Iterable):
        s  = np.array(s, order = 'F')
        nb = np.array([s.nbytes], dtype = hdt)

        nb.tofile (fd._fp)
        s.tofile (fd._fp)
        nb.tofile (fd._fp)

      else:
        s  = [np.array(e, order = 'F') for e in s]
        nb = np.array([np.sum ((e.nbytes) for e in s)], dtype = hdt)

        nb.tofile (fd._fp)

        for e in s:
          e.tofile (fd._fp)

        nb.tofile (fd._fp)

```

**Comment by pv** [comment]
gh-7753
