### ISSUE TITLE
scipy.misc.imread rotates image taken from iPhone (in its JPG format) 90 degrees CCW

### ISSUE THREAD

**Issue by rfrapp** [scipy/scipy#7322]
Observe the following image (which was taken by an iPhone 6S Plus): 
![image](https://cloud.githubusercontent.com/assets/5246523/25213664/b44ed51c-2557-11e7-9314-13fa9edcb290.png)

When loaded with `scipy.misc.imread(name=filename, flatten=True)`, I get the following image: 
![image](https://cloud.githubusercontent.com/assets/5246523/25213699/e281694a-2557-11e7-9f96-5927426e5d8c.png)

When I convert the (already JPG) image to a JPG using PhotoShop, I get
![image](https://cloud.githubusercontent.com/assets/5246523/25213735/24e602fa-2558-11e7-916c-2c5c718eb0e7.png)

Here's the matplotlib code that displayed the two images above:

    
    fig = plt.figure()

    ax0 = fig.add_subplot(111)
    # ax0.axis('off')
    ax0.imshow(imgdata, cmap='gray', origin=None)
    plt.tight_layout()`

Not sure what's going on here. Is this a problem with Apple's JPG encoding? Or is this an issue with `imread()`?

**Comment by Eric89GXL** [comment]
The JPG probably has EXIF information about how to rotate the image.

But `misc.imread` just wraps to PIL to read the image, so it's probably better to open the bug with the upstream library.

**Comment by rgommers** [comment]
closing, not a scipy issue
