### ISSUE TITLE
Scipy.minimize reports success when it should fail

### ISSUE THREAD

**Issue by adrianbutscher** [scipy/scipy#7323]
Hi,

I seem to have found a bug in the SLSQP option of scipy.minimize.  I give scipy.minimize the trivially infeasible minimization problem in R^2:

minimize 0.5*|| x ||^2

subject to x_0 >= 1 and x_0 <= 0.

This shouldn't succeed of course.  But the minimize function reports success except for the occasional choice of initial vector, in which case it reports failure with error code is 9 -- iterations exceeded -- and the function value is NAN.  Can someone explain what is going wrong?  Thanks.  Apologies in advance if I've done something stupid...  Here is my code:

import numpy as np
from scipy.optimize import minimize
obj = lambda x: np.dot(x, x)
Dobj = lambda x: x
con_m = lambda x: x[0] - 1
con_p = lambda x: -x[0]
Dcon_m = lambda x: np.array([1,0])
Dcon_p = lambda x: np.array([-1,0])
x0 = np.random.random(2)
res = minimize(obj, x0, method='SLSQP', jac=Dobj, 
                         constraints=({'type':'ineq', 'fun':con_p, 'jac':Dcon_p}, 
                         {'type':'ineq', 'fun':con_m, 'jac':Dcon_m}))
print(res.success) # usually True
print("x[0] = {}".format(res.x[0])) # usually between 0 and 1

**Comment by jaimefrio** [comment]
If you pass those simple single variable bounds using the `bounds=` kwarg, it will correctly fail with status 4, 'Inequality constraints incompatible'.

Even for a more complicated set of infeasible constraints like `x < 0, y < 0, x + y > 1`, it is able to detect the 'Inequality constraints incompatible' **if** the first two constraints afre provided in the `bounds=` kwarg, but not if all three are given using `constraints=`.

Not sure if this can be fixed in the SLSQP implementation  itself. At the very least we could add a final check that the solution fulfills all the provided constraints and raise an error if not.

**Comment by adrianbutscher** [comment]
It is strange behaviour indeed.  The bounds= kwarg does indeed perform as expected.  But I discovered the above behaviour by debugging a non-linear inequality constraint function where the Jacobian was singular (linearly dependent rows) at the solution.  I was getting success, but the subsequent processing I did to the solution of the problem was wrong.  I ended up deducing by repeated trials that the problem could be demonstrated in the simple example above.

I don't know what the algorithm is doing when there are linearly dependent rows in the Jacobian of the constraint.  Is the algorithm written up in a paper or textbook somewhere?

Thanks for looking into this for me.

Adrian

**Comment by pv** [comment]
The Kraft's SLSQP paper can be found via google scholar and it's cited in the documentation --- not sure if it's easy to get hold of though.

**Comment by pv** [comment]
The source code itself is readable to some degree: https://github.com/scipy/scipy/blob/master/scipy/optimize/slsqp/slsqp_optmz.f

**Comment by edmundus** [comment]
I think checking for feasibility would definitely help. Message and success of the return dictionary are very misleading!
The problem also appears with equality constraints.

**Comment by pv** [comment]
An SLSQP bug related to this was fixed some time ago in the master branch, so it's not clear this issue is there any more.

**Comment by pv** [comment]
Indeed, I think this was fixed by gh-8986
