### ISSUE TITLE
[feature request] expose introselect functionality in numpy.partition

### ISSUE THREAD

**Issue by changhe3** [scipy/scipy#7326]
a.k.a. 
add a function
numpy.select(a, kth)
that simply returns the value of the element in kth position is in the position it would be in a sorted array.
Sometimes it is just too clumsy to use numpy.partition() directly.
Thanks

**Comment by person142** [comment]
I think you want the NumPy bug tracker:

https://github.com/numpy/numpy/issues

**Comment by changhe3** [comment]
Oops sorry:P
