### ISSUE TITLE
interpolate.ndgriddata.griddata causes Python to crash rather than raise QhullError

### ISSUE THREAD

**Issue by bobert123** [scipy/scipy#7327]
Hi,
Just wanted to let you know that since I've updated scipy to v0.18 (at work) and v0.19 (at home) on my windows computer it causes python to crash completly when using interpolate.ndgriddata.griddata. 
Whilst using the same script previously, but with scipy v0.17 it raised a QHullError which I could catch. Since the upgrade however, python just crashes completely.
![image](https://cloud.githubusercontent.com/assets/27856163/25277359/e7aec28a-26d0-11e7-9c82-8fce58b5c3b9.png)

**Comment by pv** [comment]
Please provide a self-contained script (e.g. runnably by "python
myscript.py") that causes such a crash.

**Comment by bobert123** [comment]
[griddata_issue.zip](https://github.com/scipy/scipy/files/948745/griddata_issue.zip)
Hi, please find attached. The data is included in the zip file. Sorry it is a bit large, but when I tried to use the first and second half of the input points separately, the problem did not occur.

**Comment by pv** [comment]
Thanks, can confirm that that indeed crashes, so this is possible to investigate.

**Comment by pv** [comment]
This is a Qhull bug. `zcat bad-points.txt.gz | qdelaunay Qz` also segfaults.

[bad-points.txt.gz](https://github.com/scipy/scipy/files/948757/bad-points.txt.gz)

**Comment by pv** [comment]
Forwarded issue to qhull devs

**Comment by pv** [comment]
Was fixed in Qhull 2019.1, so fixed by upgrading (#10413)
