### ISSUE TITLE
scipy.sparse.linalg.spilu crashes ipython 2.7 kernel

### ISSUE THREAD

**Issue by kingaj12** [scipy/scipy#7330]
The following code crashes my Python 2.7 iPython kernel

`import numpy as np`
`import scipy.sparse.linalg as spla`
`A = np.array([[ 0.4445,  0.4444, -0.2222],
              [ 0.4444,  0.4445, -0.2222],
              [-0.2222, -0.2222,  0.1112]])`
`b = np.array([[ 0.6667], 
              [ 0.6667], 
              [-0.3332]])`
`M2 = spla.spilu(A)`

The funny thing is that this was just working a minute ago, and I can't get it to run again.

**Comment by pv** [comment]
That code example is not runnable (maybe you meant to use LinearOperator somewhere?)

**Comment by kingaj12** [comment]
Sorry, this is the code
`import numpy as np`
`import scipy.sparse.linalg as spla`
`import scipy.sparse as sp`
`A = np.array([[ 0.4445,  0.4444, -0.2222],
              [ 0.4444,  0.4445, -0.2222],
              [-0.2222, -0.2222,  0.1112]])`
`spA = sp.csc_matrix(A)`
`M2 = spla.spilu(spA)`

**Comment by kingaj12** [comment]
sorry -- it is just the spilu that crashes.  I removed the other lines from
the code.


-------------------------------------------------------
Alan King, PhD
Mathematical Sciences
IBM Thomas J. Watson Research Center
914 945 1236 (o)  914 260 9888 (m)
kingaj@us.ibm.com

**Comment by rgommers** [comment]
That code works fine for me. A crash shouldn't have anything to do with IPython here anyway. A traceback would be helpful.

**Comment by kingaj12** [comment]
Still crashes my Python 3 kernel.  Any suggestions on how to get a traceback?

**Comment by sethtroisi** [comment]
Code sample runs in Colab and locally; issue was never reproduced by a 2nd person and is 3 years old.
