### ISSUE TITLE
Failed on installed scipy in python2.7

### ISSUE THREAD

**Issue by Sophie521** [scipy/scipy#7331]
I can`t install scipy successfully and I don`t know why. Please help me ,thank you very much!
I input "pip install scipy " on  cmd, but it doesn`t work. 

Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\admini~1\\appdata\\local\\temp\\pip-build-2kas1x\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\admini~1\appdata\local\temp\pip-r2b3of-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\admini~1\appdata\local\temp\pip-build-2kas1x\scipy\

**Comment by pv** [comment]
Pip on windows is not supported.
