### ISSUE TITLE
Many SciPy ndimage filters accept both size and footprint

### ISSUE THREAD

**Issue by jakirkham** [scipy/scipy#7334]
Appears that many of the filters in `scipy.ndimage.filters` will accept both a `size` and a ` footprint` specified at the same time. Even if they are contradictory (e.g. smaller `size` than dims of `footprint`), this doesn't seem to raise an error. Checked and verified this problem with the ordering filters (`minimum_filter`, `median_filter`, `maximum_filter`, `rank_filter`, and `percentile_filter`), but this may extend to other filters that take `size` and ` footprint` (e.g. `generic_filter`). In these cases, it seems more appropriate to error and explain to the user that they must either set `size` or `footprint`, but not both. Example of this problem is shown below. Tested this with SciPy 0.19.0.

```python
In [1]: import numpy

In [2]: import numpy as np

In [3]: import scipy

In [4]: import scipy.ndimage

In [5]: import scipy.ndimage.filters

In [6]: import scipy.ndimage as spnd

In [7]: spnd.filters.median_filter(a, size=1, footprint=np.ones((2,2), dtype=bool))
Out[7]: 
array([[  0.,   1.,   2.,   3.,   4.,   5.],
       [  6.,   6.,   7.,   8.,   9.,  10.],
       [ 12.,  12.,  13.,  14.,  15.,  16.],
       [ 18.,  18.,  19.,  20.,  21.,  22.],
       [ 24.,  24.,  25.,  26.,  27.,  28.]])
```

**Comment by jaimefrio** [comment]
For the record, the typical behaviour is to ignore the size if the footprint is provided.

**Comment by adbugger** [comment]
What would the resolution of this look like? Since the typical behaviour is to ignore the size, I think a warning should be enough.

**Comment by rgommers** [comment]
Yes, `UserWarning` seems right to me. Documentation looks correct already.
