### ISSUE TITLE
linalg.eigh is slow

### ISSUE THREAD

**Issue by yaroslavvb** [scipy/scipy#7339]
In the benchmark below I get 5x faster performance from linalg.svd than linalg.eigh (using version I get with `conda install scipy` on `conda 4.2.13`, Ubuntu 14.04 ). One thing I notice is that `svd` is peaking at 20 cores, whereas `eigh` only uses 1. My theory is that `linalg.svd` uses MKL gesvd, whereas linalg.eigh is using something else (Lapack?). Could this be solved by integrating https://software.intel.com/en-us/articles/introduction-to-the-intel-mkl-extended-eigensolver ?

```
# Xeon(R) CPU E5-2630 v4 @ 2.20GHz
# n=1000 Times: min: 126.04, median: 132.48
# n=2000 Times: min: 573.03, median: 621.49
# n=4096 Times: min: 5586.02, median: 6032.16
# n=4096 do_symmetric: Times: min: 27758.34, median: 28883.69
import util
from scipy import linalg  # for svd
import numpy as np

do_symmetric = True

n=4096
x = np.random.randn(n*n).reshape((n,n)).astype(dtype=np.float32)
x = x @ x.T
util.record_time()
for i in range(10):
  if do_symmetric:
    result = linalg.eigh(x)
  else:
    result = linalg.svd(x)
  util.record_time()
util.summarize_time()

```

**Comment by pv** [comment]
If it's linked against MKL, also eigh uses MKL --- that's the only place 
where the implementation can come from. However, perhaps the specific 
routine used is not well-optimized in MKL.

**Comment by rgommers** [comment]
question here seems answered, and gh-9212 has more details about `eig`/`eigh` performance and a suggested fix. so closing this as a duplicate. thanks all
