### ISSUE TITLE
Documentation error: script.stats.skew

### ISSUE THREAD

**Issue by sesd7** [scipy/scipy#7341]
In the following quote from the documentation for script.stats.skew, shouldn't the inequality sign be the flipped the other way around?

"A skewness value > 0 means that there is more weight in the left tail of the distribution."

Webpage:  https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.skew.html

SciPy v0.14.0

**Comment by josef-pkt** [comment]
Yes the sign or the side of the tail is flipped

also there should be a qualifier "for unimodal continuous distribution"
The statement is not true in general.

https://en.wikipedia.org/wiki/Skewness

**Comment by WinstonPoh** [comment]
From wikipedia: "positive skew: The right tail is longer; the **mass of the distribution is concentrated on the left of the figure**" 
I think this is synonymous to "skewness value > 0 means that there is more weight in the left tail of the distribution"

**Comment by rgommers** [comment]
> I think this is synonymous to "skewness value > 0 means that there is more weight in the left tail of the distribution"

Not quite I think. From the same page: *Conversely, positive skew indicates that the tail on the right side is longer or fatter than the left side. In cases where one tail is long but the other tail is fat, skewness does not obey a simple rule.*

The change in gh-7415 looks like an improvement to me. There's probably no good way to explain it even clearer without resorting to drawing figures (which we won't do).
