### ISSUE TITLE
New complex192 not supported test error

### ISSUE THREAD

**Issue by matthew-brett** [scipy/scipy#7348]
Getting errors for the 32-bit builds of scipy:

```
======================================================================
ERROR: test_convolve_method (test_signaltools.TestConvolve)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venv/local/lib/python2.7/site-packages/scipy/signal/tests/test_signaltools.py", line 186, in test_convolve_method
    for key in ['fft', 'direct']}
  File "/venv/local/lib/python2.7/site-packages/scipy/signal/tests/test_signaltools.py", line 186, in <dictcomp>
    for key in ['fft', 'direct']}
  File "/venv/local/lib/python2.7/site-packages/scipy/signal/signaltools.py", line 789, in convolve
    out = fftconvolve(volume, kernel, mode=mode)
  File "/venv/local/lib/python2.7/site-packages/scipy/signal/signaltools.py", line 403, in fftconvolve
    sp2 = fftpack.fftn(in2, fshape)
  File "/venv/local/lib/python2.7/site-packages/scipy/fftpack/basic.py", line 622, in fftn
    return _raw_fftn_dispatch(x, shape, axes, overwrite_x, 1)
  File "/venv/local/lib/python2.7/site-packages/scipy/fftpack/basic.py", line 631, in _raw_fftn_dispatch
    raise ValueError("type %s is not supported" % tmp.dtype)
ValueError: type complex192 is not supported
```

https://travis-ci.org/MacPython/scipy-wheels/jobs/226731274

I guess this is from 760a369 - @stsievert - any thoughts?

**Comment by stsievert** [comment]
Thanks for the report. It seems this bug is present because we're looping over all dtypes and never check to see if FFT convolution is supported. In `test_convolve_method` I would guess we're missing

``` python
# inside double for loop over dtypes in `test_convolve_method`
if not _fftconvolve_valid(x1, x2):
    continue
```

I presume I can fix this bug quickly but how should I test to verify that I've actually fixed it? The scipy travis tests don't run 32 bit tests (the tests for #7211 all passed). @e-q or @Eric89GXL might know more on this.

**Comment by matthew-brett** [comment]
Just to check - should complex192 be supported on i386?  I'm guessing it should, if complex256 is supported on x86_64.

To test on a machine with docker:

```
cd scipy  # where your scipy repo is
git checkout master  # or whatever branch you're using
git pull
docker pull matthewbrett/trusty:32  # get 32-bit Ubuntu Trusty image for testing
docker run --rm -ti -e PYTHON_VERSION=2.7 -v $PWD:/io matthewbrett/trusty:32 /bin/bash
```

Then in the docker container:

```
apt-get install -y liblapack-dev libblas-dev gfortran
pip install Cython numpy nose
cd /io  # now in scipy directory from host
pip install -e .
```

The scipy install takes a long time, but you should be able to run the tests in the container after that:

```
nosetests scipy/signal/tests/test_signaltools.py:TestConvolve
```

Do these instructions work for you?  If so, I'll put them up on the wiki.

**Comment by stsievert** [comment]
@matthew-brett thanks for that! That made testing (a pain point for me) a lot simpler. The instructions exactly worked.

I've put in a PR for this issue.
