### ISSUE TITLE
If a mutable (like a numpy array) is passed as window to resample_poly, it is modified

### ISSUE THREAD

**Issue by jthiem** [scipy/scipy#7375]
When passing a pre-computed FIR filter in a numpy array to resample_poly, it is multiplied by `up`.  This scaling happens in-place, and is very undesired behaviour if the same filter is supposed to be used again (which is very likely).

Proposed fix: in line 2368 (or thereabouts) of signaltools.py change `h = window` to `h = array(window)`, ensuring `h` is a copy of `window`.

### Reproducing code example:
```
import numpy
from scipy.signal import resample_poly

impulse = numpy.array([0, 0, 0, 0, 1.0, 0, 0, 0, 0 ])
fake_LPF = numpy.array([.1, .2, .3, .4, .5, .4, .3, .2, .1])

out = resample_poly(impulse, 5, 3, window=fake_LPF)
print(fake_LPF)
```
### Scipy/Numpy/Python version information:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
@jthiem, thanks for reporting the problem.  I can confirm that the problem still exists in the master branch.

**Comment by WarrenWeckesser** [comment]
Ping @e-q, @Eric89GXL: can either of you take a look?

**Comment by Eric89GXL** [comment]
I can take a look in the next few days.
