### ISSUE TITLE
Krogh interpolation fails to produce derivatives for complex functions

### ISSUE THREAD

**Issue by G-van-Straaten** [scipy/scipy#7381]
When a polinomial is constructed using the KroghInterpolator() function from scipy.interpolate with some of the entries being complex, the resulting polinomial is complex. This works fine. However, attempting to retrieve the derivatives of this complex polinomial using the derivatives() function results in an error.

### Reproducing code example:

import numpy as np
import scipy as sc
from scipy import interpolate
import sys

print(sc.__version__, np.__version__, sys.version_info)

function_real = interpolate.KroghInterpolator(np.array([-1, -1, 0, 1, 1]), np.array([1, 1, 0, -1, 1]))
function_complex = interpolate.KroghInterpolator(np.array([-1, -1, 0, 1, 1]), np.array([1, 1.0j, 0, -1, 1.0j]))

print function_real.derivatives(0)
print function_complex.derivatives(0)

### Error message:

Traceback (most recent call last):
  File "C:\Juelich\Papers\Attenuation effects in NIXSW\SIM\Fit 2\bug report test
.py", line 12, in <module>
    print function_complex.derivatives(0)
  File "C:\Python27\lib\site-packages\scipy\interpolate\polyint.py", line 178, i
n derivatives
    y = self._evaluate_derivatives(x, der)
  File "C:\Python27\lib\site-packages\scipy\interpolate\polyint.py", line 338, i
n _evaluate_derivatives
    p += self.c[0,np.newaxis,:]
TypeError: Cannot cast ufunc add output from dtype('complex128') to dtype('float
64') with casting rule 'same_kind'

### Scipy/Numpy/Python version information:

('0.19.0', '1.12.1', sys.version_info(major=2, minor=7, micro=10, releaselevel='
final', serial=0))

**Comment by ev-br** [comment]
Thanks for the report. https://github.com/scipy/scipy/pull/7383 should fix it.
