### ISSUE TITLE
scipy.interpolate.UnivariateSpline returns a data exception when i fit a set of curves

### ISSUE THREAD

**Issue by CherryRum** [scipy/scipy#7386]
A few days ago i made a few motor experiments.
In China,i need to write a thick experimental report,when i fit the experimental
data .This set of data have a problem,When i am generated x axis,through this function(scipy.interpolate.UnivariateSpline).i cant's get the correct data for the y axis.
I don't know if my method is wrong,My previous data is also this method.Is it possible that there is a function exception.I am a bit desperate,Who can help me. My English is very poor.Please forgive me. 
My python version is 2.7
The part of the data returned is Nan
  
# coding:utf-8
import numpy as np
import matplotlib.pyplot as plt
from scipy import interpolate
n_2 = np.array([1410,1450,1490,1530,1570,1610,1650],dtype=float)
n_i = np.array([111,99,91,85,79,74,71],dtype=float)
plt.figure(2)
plt.title(r'$n = f(I_f)$')
plt.xlabel(r'$I/A$')
plt.ylabel(r'$n(r/min)$')
xinterp1 =np.linspace(70,112, 100)
yinterp1 = interpolate.UnivariateSpline(n_i,n_2,check_finite =1)(xinterp1)#there
print xinterp1
print yinterp1
plt.plot(n_i,n_2,'.r')
plt.plot(xinterp1, yinterp1, 'c', linewidth=1)
plt.show()
![22222222](https://cloud.githubusercontent.com/assets/24296698/25782897/3124064e-3385-11e7-8e83-7315f149ce41.png)
![3](https://cloud.githubusercontent.com/assets/24296698/25782901/3ee9cc5a-3385-11e7-9ed9-2b957c81f194.png)

**Comment by ev-br** [comment]
UnivariateSpline et al requires the `x` array to be ordered in the increasing order. Your `n_i` array is not.

In general, usage questions are better asked at StackOverflow or scipy-user mailing list.

**Comment by CherryRum** [comment]
thanks
