### ISSUE TITLE
ndimage.geometric_transform endianness-linked bug when affine is 1d

### ISSUE THREAD

**Issue by lesteve** [scipy/scipy#7388]
Results are byteswapped when `out` is passed into `ndimage.affine_transform` and `out` has a non-native endianness.

This is a similar issue as https://github.com/scipy/scipy/issues/4127 when the affine transformation is given as a 1d array (in #4127, which was fixed in 0.15, the affine transformation was given as a 2d array).

### Reproducing code example
```py
import numpy as np
from scipy import ndimage

data = np.ones((2, 2))
out = np.empty_like(data, dtype='>f8')
ndimage.affine_transform(data, np.array([1., 1.]), output=out, order=0)
print(out)
```

### Expected behaviour
The affine I am passing is the identity so I expect to have `(out == data).all()`, i.e. `out` should contain only ones.

### Actual behaviour
`out` is:
```
[[  3.03865194e-319   3.03865194e-319]
 [  3.03865194e-319   3.03865194e-319]]
```

### Other comments
The fix should be very similar to https://github.com/scipy/scipy/pull/4150, i.e. you need to call `.byteswap` when `output.dtype.isnative` is `False`. I am guessing the code path for the 1d affine is slightly different than the one for the 2d affine, hence it was missed in the original fix. This bug has been present in scipy for a while (I tried as far back as 0.14).

**Comment by cdouglass** [comment]
I would like to have a go at fixing this.

**Comment by rgommers** [comment]
@cdouglass that would be great, go for it!

**Comment by jaimefrio** [comment]
As Loïc suspected, for 1D transformation matrices it is `zoom_shift`, not `geometric_transform`, that gets called, see here:

https://github.com/scipy/scipy/blob/master/scipy/ndimage/interpolation.py#L490

**Comment by cdouglass** [comment]
Thanks @jaimefrio! I have a test + fix locally and will make a PR once I've read the Contributing guide properly and made sure I'm doing it right.

**Comment by jaimefrio** [comment]
Feel free to send your PR sooner than later, and have a reviewer help you with getting it to fit the guidelines. People are genuinely nice around here.

**Comment by jaimefrio** [comment]
On a separate note, this seems to be happening everywhere in `ndimage`, e.g.:

```
>>> a = np.random.rand(100, 100)
>>> b = np.empty((100, 100), dtype='>f8')

>>> ndimage.filters.gaussian_filter1d(a, 3)[:2, :2]
array([[ 0.73052361,  0.7155322 ],
       [ 0.72614243,  0.71361152]])

>>> ndimage.filters.gaussian_filter1d(a, 3, output=b)
>>> b[:2, :2]
array([[ -7.08769601e-245,   1.49275726e-024],
       [  1.13307793e+059,  -3.91978641e+167]])

>>> b.view('<f8')[:2, :2]
array([[ 0.73052361,  0.7155322 ],
       [ 0.72614243,  0.71361152]])
```

The functions using the line iterator could perhaps be fixed at the C level, probably by making `NI_LineBufferToArray` be aware of endianess:

https://github.com/scipy/scipy/blob/master/scipy/ndimage/src/ni_support.c#L402

But in the general case I'm thinking that perhaps we could generalize the fix into a decorator that checks the `output=` kwarg and byteswaps it if needed? There are tricky cases, e.g. separable filters that call their 1D filters several times and reuse the output array in between calls, but I think it's worth exploring.

**Comment by cdouglass** [comment]
I noticed a similar problem for when a `dtype` instead of an `ndarray` is passed in as the `output` parameter, and am including a fix for that. I have not looked at other `ndimage` functions yet.
