### ISSUE TITLE
include PeakUtils in scipy.signal

### ISSUE THREAD

**Issue by arsenovic** [scipy/scipy#7393]
[peakutils](http://pythonhosted.org/PeakUtils/index.html) is a nice library for peak detection. it would be good to have it in scipy. the current peak detection algorithm [fine_peak_cwt](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.signal.find_peaks_cwt.html) is more exotic, and does not take expected parameters or provide functionality of a simple peak detector. 

this blog post gives a good overview of available peak detection in python

http://pythonhosted.org/PeakUtils/tutorial_a.html

i have contacted author, and he would be willing to help.

**Comment by Eric89GXL** [comment]
It looks like potentially useful functionality to me. But one thing I'm not knowledgeable enough to know -- are there standard methods for peak detection, and are those what are implemented in PeakUtils and proposed for inclusion here? Ideally things included in SciPy would be published/established/known algorithms. (I'm actually not sure if `find_peaks_cwt` even fits that description.)

**Comment by arsenovic** [comment]
i am not an expert in this field either. 
this guy wrote  a good overview, using matlab's function  as a reference. 
https://blog.ytotech.com/2015/11/01/findpeaks-in-python/

**Comment by Eric89GXL** [comment]
From reading that, my sense is that implementing something analogous to MATLAB/Octave `findpeaks`, which seems like it's already available in `peakutils.indexes` and `detect_peaks.detect_peaks`, would be a good start. That has apparently been in MATLAB since (at least) 2008 so I assume it's fairly well established. But it would be good to hear from some other folks who might know.

@e-q @endolith any experience here?

**Comment by carlodri** [comment]
This would be a __great__ thing! I'm not a great pythonista, but I'm be glad to help if I'm able to.

**Comment by lagru** [comment]
Potentially, this issue can be considered solved now with #8264. Otherwise it might be useful to discuss what functionality from peakutils is still missing.

**Comment by larsoner** [comment]
Closing for now, let's open new issues for more targeted requirements as they show up
