### ISSUE TITLE
splprep segfaults if fixed knots are specified

### ISSUE THREAD

**Issue by mythsmith** [scipy/scipy#7395]
interpolate.splprep causes random python segfault if task=-1 and fixed knots are specified, apparently near _fitpack._parcur call.

### Reproducing code example:
```
import numpy as np
from scipy.interpolate import splprep
N = 1000
x = np.arange(N)
# Sinusoid 0-100
y = 100*np.sin(x/30.)
# Add 0-10 random noise
y += np.random.randint(0,10,N)
u = np.arange(N)
# Free knots
resp = splprep([x, y], full_output=True, task=0, k=3, s=15000., u=u)
(tck, u1), err, ier, msg = resp
# Use the obtained knots as fixed:
resp = splprep([x, y], full_output=True, task=-1, k=3, u=u, t=tck[0])
(tck, u1), err, ier, msg = resp
```
If it does not fail immediately, it will if you repeat the calculation in a for loop (eg: 10 times). The behaviour seems quite random.
More detailed explanation here:
https://gist.github.com/mythsmith/9951a8d04092bd11aadbd8a4ef680e22

### Error message:
```
*** Error in `python': free(): invalid pointer: .... ****
```

### Scipy/Numpy/Python version information:
Both:
```
0.18.1 1.11.3 sys.version_info(major=3, minor=6, micro=0, releaselevel='final', serial=0)
'0.17.1', '1.11.1', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0)
```
The first one was on my local Anaconda3 installation. The second on SageMathCloud.

**Comment by rgommers** [comment]
Confirmed, that segfaults for me.

**Comment by pambros** [comment]
I have the same problem. I may have identified a memory leak in the C "fitpack_parcur" function but anyway after recompilation it doesn't seem to solve the segfault problem.

I don't know exactly how works the PyArrayObject but in "scipy/interpolate/src/_fitpackmodule.c", in the function fitpack_parcur on line 457, a new PyArrayObject address is stored in ap_t without releasing/freeing/Py_XDECREF the previous PyArrayObject (from line 429). This happens only when iopt != 0 (i.e here in our case when task == -1).
We can see in the next function fitpack_curfit which is quite similar that a "if (!iopt) {" has been added when ap_t will be stored by a new PyArrayObject address.

So I did the same for fitpack_parcur and modified the code around line 457 to:

`
    if (!iopt) {
        dims[0] = n;
        ap_t = (PyArrayObject *)PyArray_SimpleNew(1, dims, NPY_DOUBLE);
        if (ap_t == NULL) {
            goto fail;
        }
    }
    dims[0] = lc;
    ap_c = (PyArrayObject *)PyArray_SimpleNew(1, dims, NPY_DOUBLE);
    if (ap_c == NULL) {
        goto fail;
    }
`

I'm not very familiar with C python API so maybe it's wrong. What do you think?

**Comment by sethtroisi** [comment]
Fixed by https://github.com/scipy/scipy/pull/11126

**Comment by pv** [comment]
Still segfaults on master for me. (It's not unusual for segfaults to not be 100% reproducible.)
