### ISSUE TITLE
scipy.sparse.todense() different behaviour in python 2.7 and python 3.6

### ISSUE THREAD

**Issue by joachimwolff** [scipy/scipy#7403]
The function todense() in the scipy.sparse module behaves different in python 2.7 and python 3.6. In python 2.7 only the matrix is returned, in python 3.6 the datatype is given too.

### Reproducing code example:
```
from scipy.sparse import csr_matrix
import numpy as np
A = csr_matrix(np.array([[12,5,3,2,0],[0,11,4,1,1],[0,0,9,6,0], [0,0,0,10,0], [0,0,0,0,0]]))
A.todense()
```

### Output:
This returns in Python 2.7: 
```
matrix([[12,  5,  3,  2,  0],
        [ 0, 11,  4,  1,  1],
        [ 0,  0,  9,  6,  0],
        [ 0,  0,  0, 10,  0],
        [ 0,  0,  0,  0,  0]])
```
But in Python 3.6:
```
matrix([[12,  5,  3,  2,  0],
        [ 0, 11,  4,  1,  1],
        [ 0,  0,  9,  6,  0],
        [ 0,  0,  0, 10,  0],
        [ 0,  0,  0,  0,  0]], dtype=int64)
```

### Scipy/Numpy/Python version information:
Python 2.7:
```
('0.19.0', '1.12.0', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0))
```

Python 3.6:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
The difference is probably only in how such matrices print out, as
``A.dtype == np.int64` in both cases.

**Comment by pv** [comment]
The underlying reason is that on 64-bit platforms, numpy has two 
equivalent 64-bit wide integer types. For computational purposes they 
are exactly identical.

**Comment by joachimwolff** [comment]
@pv I agree with you. It would be nice if the print out behaviour could be the same in both versions. It makes it easier to write test cases which should run for both Python versions.

**Comment by pv** [comment]
That they print differently is probably a numpy issue.

**Comment by eric-wieser** [comment]
Can you print out `A.todense().dtype` and `A.todense().dtype.char` in both cases?

**Comment by joachimwolff** [comment]
Python 2.7:
```
>>> A.todense().dtype
dtype('int64')
```

```
>>> A.todense().dtype.char
'q'
```

Python 3.6:
```
>>> A.todense().dtype
dtype('int64')
```

```
>>> A.todense().dtype.char
'q'
```

**Comment by pv** [comment]
Repro without scipy:
```
 >>> a = np.array([0], dtype='q')
 >>> b = np.array([0], dtype='l')
 >>> a.dtype == np.int64
True
 >>> b.dtype == np.int64
True
 >>> a
array([0], dtype=int64)
 >>> b
array([0])
``

**Comment by rgommers** [comment]
numpy issue was opened, so closing this one
