### ISSUE TITLE
scipy.stats.binom.ppf returns nan for q between 0 and 1 if n == 0

### ISSUE THREAD

**Issue by abukaj** [scipy/scipy#7406]
`scipy.stats.binom.ppf(q, n, p)` returns nan for q between 0 and 1 if `n == 0`

It works fine for `q in (0, 1)`:
```
>>> ss.binom.ppf(0, 0, 0.5)
-1.0
>>> ss.binom.ppf(1, 0, 0.5)
0.0
```

Since CDF is defined for 0 and -1 
```
>>> ss.binom.cdf(0, 0, 0.5)
1.0

>>> ss.binom.cdf(-1, 0, 0.5)
0.0
```
according to https://docs.scipy.org/doc/scipy/reference/tutorial/stats.html#specific-points-for-discrete-distributions `ppf()` should return 0.

The issue may be connected to https://github.com/scipy/scipy/issues/5122

### Reproducing code example:
```
>>> import scipy.stats as ss
>>> ss.binom.ppf(0.5, 0, 0.5)
nan
```

### Scipy/Numpy/Python version information:
```
('0.19.0', '1.11.3', sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0))
```

**Comment by mdhaber** [comment]
@mckib2 I wonder if Boost handles this corner case (i.e. `binom.ppf(0.5, 0, 0.5)`) properly?

Also, I'm curious what it does for `q = 0` and `q = 1`. Another one for the list!
