### ISSUE TITLE
scipy.special.polygamma(1,double) and other functions return array(double) with shape (), not double or array with shape (1,)

### ISSUE THREAD

**Issue by ssllmit** [scipy/scipy#7411]
`scipy.special.polygamma(1,x)` returns `np.ndarray(double)` of size zero, not a double or array with shape `(1,)`. This prevents indexing and accessing the result.

There are other `scipy.special` functions with this issue.

### Reproducing code example:
```python
import scipy.special as sps

y = sps.polygamma(1,1)
y.shape
y[0]
```

### Error
```
y[0]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-158-898a238e141c> in <module>()
----> 1 y[0]

IndexError: too many indices for array
```

### Scipy/Numpy/Python version information:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=4, micro=6, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
That is the correct broadcasting behavior, so works as intended.

**Comment by WarrenWeckesser** [comment]
Ideally, `polygamma()` would return a *scalar* (not a 0-d array) when given scalar.  This would be consistent with actual ufuncs, such as `xlogy()`:

```
In [6]: from scipy.special import polygamma, xlogy

In [7]: polygamma(1, 2)
Out[7]: array(0.6449340668482266)

In [8]: xlogy(1, 2)
Out[8]: 0.69314718055994529
```
See also https://github.com/scipy/scipy/issues/7400.
