### ISSUE TITLE
Why fixing scale parameter to 1 not work for a given data?

### ISSUE THREAD

**Issue by yananchen1989** [scipy/scipy#7417]
I have a data which are the interval days of customers purchasing products in furniture category. I try to estimate the shape and scale params by scipy.stat.weibull_min function for my data. This fits a three-parameter Weibull, with the usual shape and scale and a shift (location) parameter.

First, I tried fixing shape parameter to be 1 as input (set f0=1) and we shall get the scale parameter in condition of shape=1. From the output below we can find that it works since the shape parameter estimated is 1.

```
shape, loc, scale = scipy.stats.weibull_min.fit(data,floc=1, f0=1) 
#constrain shape to be 1  
loc:1    shape:1  scale:90.85
```
However, when I try to constrain the scale parameter to be 1 in order to get shape parameter in condition of scale=1, it does not work(the output scale parameter is ~75 instead of 1). So I am confused why it doesn't work.

```
shape, loc, scale = scipy.stats.weibull_min.fit(data,floc=1,scale=1)
#constrain scale to be 1  
loc:1    shape:0.7318249351  scale:75.22852953
```
In the scipy.stats official document, scale=1 as input seems default setting. https://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.stats.weibull_min.html

**Comment by ev-br** [comment]
To fix the scale, you need `fscale`, not `scale`:

```
In [8]: xx = stats.weibull_min.rvs(c=3, size=50, scale=8)

In [9]: stats.weibull_min.fit(xx)
Out[9]: (2.3943772796406684, 1.262457946769429, 6.5967459875397125)

In [10]: stats.weibull_min.fit(xx, fscale=8)
Out[10]: (2.9675877032827525, 0.031569131824693022, 8)
```

It's unfortunate that the `.fit` method silently ignores unrecognised parameters, and parsing of arguments of `.fit` can certainly be improved (also https://github.com/scipy/scipy/issues/5362).
