### ISSUE TITLE
scipy.stats.arcsine().pdf and scipy.stats.beta(0.5, 0.5).pdf disagree at the two endpoints 0 and 1

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#7421]
The arcsine distribution is the same as one of the beta distributions, arcsine = beta(0.5, 0.5).  
The CDF is well defined on the whole interval [0, 1].  The PDF becomes infinite at two endpoints. However `arcsine.pdf(0)` returns 0, `beta(0.5, 0.5).pdf(0)` returns inf.

```
>>> arcsine, beta = scipy.stats.arcsine(), scipy.stats.beta(0.5, 0.5)
>>> for x in np.linspace(0, 1, 5, endpoint=True):
...     print('%.2f  %6f  %6f' % (x, arcsine.pdf(x), beta.pdf(x)))
... 
0.00  0.000000     inf
0.25  0.735105  0.735105
0.50  0.636620  0.636620
0.75  0.735105  0.735105
1.00  0.000000     inf
```
The PDFs do appear to agree within tolerances at other values in the domain.

Ideally `arcsine.pdf()` should return the same infinite values at the two endpoints as the beta distribution does.

The `arcsine._pdf()` code appears that it would compute the correct value `1.0/np.pi/np.sqrt(x*(1-x))` if it were passed x=0 or x=1.  But the `arcsine` initializer sets `_support_mask = rv_continuous._open_support_mask` and hence the two endpoints (0.0 and 1.0) get masked out and do not get sent to `arcsine._pdf()`.  Contrast this with the initializer for `beta`, which leaves `_support_mask = rv_generic._support_mask` and hence does allow the endpoints to get sent to `beta._pdf()`.
 
### Reproducing code example:
```
import numpy as np
import scipy.stats
print(scipy.stats.arcsine.pdf([0, 1]), scipy.stats.beta(0.5, 0.5).pdf([0, 1]))
# [ 0.  0.] [ inf  inf]
```

### Scipy/Numpy/Python version information:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by ev-br** [comment]
This looks like an `arcsine` bug. Would you be interested in sending a PR with the fix?

**Comment by pvanmulbregt** [comment]
I created a PR #7431, which then ran the testing but failed the "Python: 2.7 TESTMODE=FULL ..."  sub-test due to "The job exceeded the maximum time limit for jobs, and has been terminated."  Anything further to do?

**Comment by pv** [comment]
The time limit excession looks spurious, the tests themselves ran fine.

**Comment by ev-br** [comment]
Fixed by gh-7431, closing
