### ISSUE TITLE
FFT bug

### ISSUE THREAD

**Issue by nyctalope** [scipy/scipy#7428]
Below is my script to calculate FFT.
Please note that the frequency range is from 0 to L-1, instead of 0 to L/2 conventionally.
The magnitude of the second period is only half of the first. I tried to plot in Matlab while Matlab is correct, but neither numpy nor scipy is correct. Please take a look and correct the bug if it is.

###############################################################

import numpy as np
import scipy as sp
from scipy.fftpack import fft, ifft
from scipy.signal import convolve
from matplotlib.pyplot import *

Fs = 1000; # Sampling frequency
T = 1/Fs; # Sampling period
L = 1500; # Length of signal
t = linspace(0,L-1,L)*T; # Time vector

S = 0.7sin(2pi50t) + sin(2pi120t);
X = S + 2randn(size(t));

figure(1)
subplot(2,1,1)
plot(1000*t[1:50],X[1:50])
title('Signal Corrupted with Zero-Mean Random Noise')
xlabel('t (milliseconds)'); ylabel('X(t)');

Y = fft(X);

P2 = abs(Y/L);
P1 = P2[0:L/2];
P1[1:-1-1] = 2*P1[1:-1-1];

f = Fs*linspace(0,L-1,L)/L;
subplot(2,1,2)
plot(f,abs(P2))
title('Single-Sided Amplitude Spectrum of X(t)')
xlabel('f (Hz)'); ylabel('|P1(f)|');

####################################################################

**Comment by Eric89GXL** [comment]
I think your understanding of the frequency axis is incorrect. Here is a corrected version:
```

import numpy as np
import scipy as sp
from scipy.fftpack import fft, ifft, fftfreq
from scipy.signal import convolve
from matplotlib.pyplot import *

Fs = 1000; # Sampling frequency
T = 1./Fs; # Sampling period
L = 1500; # Length of signal
t = np.linspace(0,L-1,L)*T; # Time vector

S = 0.7*np.sin(2*np.pi*50*t) + np.sin(2*np.pi*120*t);
X = S + 2*np.random.randn(L);

figure(1)
subplot(2,1,1)
plot(1000*t[1:50],X[1:50])
title('Signal Corrupted with Zero-Mean Random Noise')
xlabel('t (milliseconds)'); ylabel('X(t)');

subplot(2, 1, 2)
Y = fft(X);
f = fftfreq(L, d=T)
plot(f,abs(Y))
title('Single-Sided Amplitude Spectrum of X(t)')
xlabel('f (Hz)'); ylabel('|P1(f)|');
```
Also note that your code could make use of `np.fft.rfft` or `scipy.fftpack.rfft` for a speed boost since your signals are real.

In the future please try to make it so your example can immediately be run by copy-paste. There were several bugs and missed imports that prevented me from doing it.

**Comment by nyctalope** [comment]
Hi Eric
The code I referred is from Matlab website
https://cn.mathworks.com/help/matlab/ref/fft.html

The original python code should be run by paste-copy. Looks there are some
of * missing due to some unknown reason and hence you have to spend time to
debug. I am sorry.

This night I tried to plot the same data, shown below in red.
I would expected subplot(3,1,2) and subplot(3,1,3) should be the same, but
they are different in fact.
This made me confused because I did not change P2.

Fs = 1000;
T = 1/Fs;
L = 1500;
t = linspace(0,L-1,L)*T;

S = 0.7*sin(2*pi*50*t) + sin(2*pi*120*t);
X = S + 2*randn(size(t));

figure(1)

subplot(3,1,1)
plot(1000*t[1:50],X[1:50])

Y = fft(X);
f = Fs*linspace(0,L-1,L)/L;
P2 = abs(Y/L);

subplot(3,1,2)
plot(f,abs(P2))

P1 = P2[0:L/2];
P1[1:-1-1] = 2*P1[1:-1-1];
subplot(3,1,3)
plot(f,abs(P2))

thanks for your great effort
-Long

**Comment by Eric89GXL** [comment]
MATLAB and SciPy do not define the frequency axes the same way. Look at how I constructed the frequencies using `fftfreq` and how you did -- they do not match. To replicate the MATLAB example, some things will need to change.
