### ISSUE TITLE
Doc: scipy/blob/master/HACKING.rst.txt contains link to nonexistent scipy/blob/master/doc/MAINTAINERS.rst.txt

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#7430]
The "Contributing to SciPy" document https://github.com/scipy/scipy/blob/master/HACKING.rst.txt contains a link 
SciPy maintainers -> https://github.com/scipy/scipy/blob/master/doc/MAINTAINERS.rst.txt
which doesn't exist.  
### Error message:
Opening the URL in a browser displays the usual 404 error message "This is not the web page you are looking for".

**Comment by Eric89GXL** [comment]
We dropped that page some time ago. Do you have time to make a PR to remove it?

**Comment by pvanmulbregt** [comment]
The use of \`maintainers\`_ occurs three times in the document. 
The third occurs in the end-of-rst-doc listing of the URLs used and can be easily removed. 
The second is in a list of useful SciPy documents and is also easy to remove.  
But the first usage is inside a policy paragraph.

"... Aiming for consensus in the discussion is important -- SciPy is a project by and for the scientific Python community.  In those rare cases that agreement cannot be reached, the \`maintainers\`_ of the module in question can decide the issue."

What is the new policy?

**Comment by cdouglass** [comment]
The [commit](https://github.com/scipy/scipy/pull/5424/commits/946ee9a1c4ae55fd9270e7263a000127049b3f2c) that removed the page has a message noting that the formal maintainer concept wasn't very useful, so my PR just removes the second and third occurrences and de-linkifies the first.
