### ISSUE TITLE
Testing of scipy.stats continuous distributions misses 25 distributions

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#7434]
Only some of the scipy.stats distributions in file scipy/stats/tests/test_distributions.py appear to be tested.  Are all the omissions intentional?

 The list of distributions tested is a hard-coded list at lines 31-45
```
# Generate test cases to test cdf and distribution consistency.
# Note that this list does not include all distributions.
dists = ['uniform', 'norm', 'lognorm', 'expon', 'beta',
         'powerlaw', 'bradford', 'burr', 'fisk', 'cauchy', 'halfcauchy',
         'foldcauchy', 'gamma', 'gengamma', 'loggamma',
         'alpha', 'anglit', 'arcsine', 'betaprime', 'dgamma',
         'exponnorm', 'exponweib', 'exponpow', 'frechet_l', 'frechet_r',
         'gilbrat', 'f', 'ncf', 'chi2', 'chi', 'nakagami', 'genpareto',
         'genextreme', 'genhalflogistic', 'pareto', 'lomax', 'halfnorm',
         'halflogistic', 'fatiguelife', 'foldnorm', 'ncx2', 't', 'nct',
         'weibull_min', 'weibull_max', 'dweibull', 'maxwell', 'rayleigh',
         'genlogistic', 'logistic', 'gumbel_l', 'gumbel_r', 'gompertz',
         'hypsecant', 'laplace', 'reciprocal', 'trapz', 'triang', 'tukeylambda',
         'vonmises', 'vonmises_line', 'pearson3', 'gennorm', 'halfgennorm',
         'rice', 'kappa4', 'kappa3', 'truncnorm', 'argus']
```

This list contains 69 distributions, but there are at least 95 now available, so it misses 26:
`burr12 cosine erlang gausshyper genexpon invgamma invgauss invweibull johnsonsb johnsonsu ksone kstwobign levy levy_l loglaplace mielke powerlognorm powernorm rdist recipinvgauss semicircular skewnorm truncexpon wald wrapcauchy levy_stable`
The code comment indicates that not all distributions are tested, but doesn't provide the reason. 
I understand why `levy_stable` is not tested for its cdf, as it only produces random variates, but that still leaves 25 others.  Are these 25 intentionally not tested?  
Should newly added distributions be automatically discovered and tested, unless appearing in an explicit exclusion list (needed to exclude `levy_stable`)?

A similar question arises for the testing of open support.  `test_support()` calls `check_open_support()` for 17 explicitly listed distributions at test_distributions.py:138-141 , but it doesn't test `fisk`.  `fisk` is a specialization of `burr`, so presumably needs testing also.  
Should newly added distributions with open support be automatically discovered and tested, unless appearing in an explicit exclusion list?

### Reproducing code example:
```
import scipy.stats
# copied from test_distributions.py:33-45
dists = ['uniform', 'norm', 'lognorm', 'expon', 'beta',
         'powerlaw', 'bradford', 'burr', 'fisk', 'cauchy', 'halfcauchy',
         'foldcauchy', 'gamma', 'gengamma', 'loggamma',
         'alpha', 'anglit', 'arcsine', 'betaprime', 'dgamma',
         'exponnorm', 'exponweib', 'exponpow', 'frechet_l', 'frechet_r',
         'gilbrat', 'f', 'ncf', 'chi2', 'chi', 'nakagami', 'genpareto',
         'genextreme', 'genhalflogistic', 'pareto', 'lomax', 'halfnorm',
         'halflogistic', 'fatiguelife', 'foldnorm', 'ncx2', 't', 'nct',
         'weibull_min', 'weibull_max', 'dweibull', 'maxwell', 'rayleigh',
         'genlogistic', 'logistic', 'gumbel_l', 'gumbel_r', 'gompertz',
         'hypsecant', 'laplace', 'reciprocal', 'trapz', 'triang', 'tukeylambda',
         'vonmises', 'vonmises_line', 'pearson3', 'gennorm', 'halfgennorm',
         'rice', 'kappa4', 'kappa3', 'truncnorm', 'argus']
_dists_from_scipystats = sorted(
     [k for k in scipy.stats._continuous_distns.__all__ if not (
         (k.startswith('rv_') or k.endswith('_gen') or (k == 'levy_stable') ))])
print(sorted(set(_dists_from_scipystats) - set(dists)))

# copied from test_distributions.py:138-141
dists = ['alpha', 'arcsine', 'betaprime', 'burr', 'burr12',
        'fatiguelife', 'invgamma', 'invgauss', 'invweibull',
        'johnsonsb', 'levy', 'levy_l', 'lognorm', 'gilbrat',
        'powerlognorm', 'rayleigh', 'wald']
# See if the _support_mask method has been changed
print(sorted(set([dst for dst in _dists_from_scipystats if 
        getattr(scipy.stats, dst)._support_mask.__func__ != scipy.stats.rv_continuous._support_mask
        ]) - set(dists)))
```

### Scipy/Numpy/Python version information:
```
1.0.0.dev0+a8b83d6 1.14.0.dev0+d1ff805 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by josef-pkt** [comment]
I tried to look at the history, but didn't see any comments for this.
The important list is https://github.com/scipy/scipy/blob/master/scipy/stats/_distr_params.py which tests all the methods.  
The list in `test_distributions.py` is AFAIR and AFAICS only used for the ks_test Monte Carlo check. There are additional tests for specific distributions in that module.

I had use something like the Monte Carlo ks_test with larger sample sizes to check the random number generation mainly those that are used from numpy in around 2009. 

I don't know if there is still a large value added by these Monte Carlo ks_tests. The main difference is that test_distribution ks_test uses random parameters, while all newer tests use fixed parameters.

One reason to exclude some distribution from the ks_test is that they use the generic random number generation and not a distribution specific code. For example if only pdf is defined, then the random numbers are created by integrating the pdf to get the cdf, and then inverting the cdf to get the ppf, which is used in transforming uniform random variables. This is very slow, and would just add an additional test for the generic method. This is most likely not worth the additional testing time, as long as the generic approach is used for one/some distributions. Consistency between ppf and other methods is tested in the other tests, although just for the fixed parameters, plus whatever special cases are added separately after fixing bugs or improving corner cases.

**Comment by rgommers** [comment]
I think improving the code comments and test names to make clear that it's only about ``ks_test`` would be useful.

> Should newly added distributions with open support be automatically discovered and tested, unless appearing in an explicit exclusion list?

A test that checks the number of continuous and discrete distributions and compares to the length of the lists in https://github.com/scipy/scipy/blob/master/scipy/stats/_distr_params.py would be useful too.

**Comment by chrisb83** [comment]
I noted that in `stats/tests/test_continuous_basic.py`, the test `test_cont_basic` is run for all distributions except the ones in the list `dist_slow` using the parameters specified in `_distr_params.py`. The test runs `check_distribution_rvs` that performs a `kstest` with `N=1000`.

It looks like the test in `stats/tests/test_distributions.py` performs a similar test using randomly generated parameters. There is a substantial overlap of the distributions not tested in both files: the main reason seems to be that rvs and / or cdf are slow as Josef said above. 

> I don't know if there is still a large value added by these Monte Carlo ks_tests. 

I agree, 
- One could also add further test cases by appending them to the list in `stats/tests/test_continuous_basic.py`. 
- Focussing on "difficult" parameters might be more relevant than checking random parameters
- What happens to the distributions like `norm` that do not take any shape parameters? In that case, the tests in `test_distributions.py` seem redundant.

**Comment by chrisb83** [comment]
@pvanmulbregt Hi Paul, do you think one could remove the tests in `scipy/stats/tests/test_distributions.py` given that there are already tests in `stats/tests/test_continuous_basic.py`?

**Comment by pvanmulbregt** [comment]
@chrisb83 
> do you think one could remove the tests in scipy/stats/tests/test_distributions.py ... ?

Which tests are you referring to?

**Comment by chrisb83** [comment]
I was refering to the ks tests in test_distributions.py which checks all the distributions in the list `dists` you stated above. A ks test is already performed in test_continuous_basic.py. See Josef's and my comment above for details.

**Comment by pvanmulbregt** [comment]
It does appear that `scipy/stats/tests/test_distributions.py:check_distribution()` `scipy/stats/tests/test_continuous_basic.py:check_distribution_rvs()` cover a lot of the same ground.
Differences:    
1. `test_distributions.py:check_distribution()` generates RVs, whereas `test_continuous_basic.py:check_distribution_rvs()` reuses RVs already generated.   
1. `check_distribution_rvs()` tests all continuous distributions, but `check_distribution()` misses `burr12, cosine, erlang, gausshyper, genexpon, invgamma, invgauss, invweibull, johnsonsb, johnsonsu, ksone, kstwobign, levy, levy_l, levy_stable, loglaplace, mielke, norminvgauss, powerlognorm, powernorm, rdist, recipinvgauss, semicircular, skewnorm, truncexpon, wald, wrapcauchy`
1. `check_distribution()` checks 2 additional shapes of `vonmises`.
1. `check_distribution()` uses a different value of `alpha` for `fatiguelife`.

While it isn't stated explicitly, it does appear that `test_continuous_basic.py` is designed to test generic features for all continuous distributions, whereas `test_distributions.py` is intended to test distribution-specific behaviors.  
If we were to stick to that, then the functionality in `test_distributions.py:check_distribution()`should instead be in `test_continuous_basic.py` except that it is already there (modulo the 2 `vonmises` and 1 `fatiguelife` test).  
Additionally, `test_retrieving_support()` and `test_docstrings()` also belong in  `test_continuous_basic.py` with this reasoning.

**Comment by josef-pkt** [comment]
I'm not sure about the current content, so some historical notes

I think running `test_distributions.py:check_distribution()` as a unit test is obsolete.
`cases_test_all_distributions` was used with random parameters to test the relevant distributions before I had any idea what parameter space the various distributions use.

Because we have the list of parameters for the distributions to check "known" cases, and many contributors/maintainers worked and work on edge cases, using random parameters in the unit tests is obsolete.

One main purpose of the original script was bug hunting to find where in the parameter space there might be problems or where the code did not specify the correct limits of the parameter space.
(It might still be useful to have something like that as a non-unittest function, when we just want to check whether the distribution looks ok over some random parameter space.)

The original `test_distributions.py` contained these random parameter tests and a few explicit distribution specific test. The ks_test part with loop over most distributions was extended and added in the additional test modules. The `check_distribution` part is just a left over in terms of location from that time.
I thought of `test_distributions` to have unit tests written for a specific distribution with the specific information to verify that case, while all other tests were distribution independent and tested generic properties of distributions.

**Comment by chrisb83** [comment]
Thanks for your feedback.

> If we were to stick to that, then the functionality in test_distributions.py:check_distribution()should instead be in test_continuous_basic.py except that it is already there (modulo the 2 vonmises and 1 fatiguelife test).
Additionally, test_retrieving_support() and test_docstrings() also belong in test_continuous_basic.py with this reasoning.

I agree. Looks like Josef also supports the removal of test_distributions.py:check_distribution(). if i find some time, I will create a PR

**Comment by chrisb83** [comment]
Similar discussion is in #1795
