### ISSUE TITLE
 discrete Lyapunov equation 

### ISSUE THREAD

**Issue by HermanKoe** [scipy/scipy#7436]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

Hello, I just realized that there is a contradiction between the python function "scipy.linalg.solve_discrete_lyapunov" and matlab function "dlyap()".
In scipy, the "scipy.linalg.solve_discrete_lyapunov(a,q)" is described for solving A'XA-X=-Q and on the other hand, "dlyap(a,q)" is described as a solver of AXA' − X + Q = 0. Therefore the result I obtain from scipy, that is "scipy.linalg.solve_discrete_lyapunov(a,q)" should exactly the same with matlab is if I transpose the matrix a, that is, "dlyap(a',q)". However I cannot get the same result unless I use scipy.linalg.solve_discrete_lyapunov(a',q). Is there any mistake in the function? Thank you so much.

### Reproducing code example:
```
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```

### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```

**Comment by ilayn** [comment]
@HermanKoe Which version of SciPy or SciPy documentation are you using? You can check it with https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.solve_discrete_lyapunov.html 
And also can you add your matrix too for testing? It might be a documentation problem, a bug or a misunderstanding and an example helps greatly to figure it out. 

You can remove the parts of the SciPy issue template if you are not using them by the way.

**Comment by HermanKoe** [comment]
Thank you. I think I got the problem. Now I am using v0.19.0 and everything goes well.
