### ISSUE TITLE
ENH: add skewed Cauchy distribution to stats

### ISSUE THREAD

**Issue by hiccup7** [scipy/scipy#7437]
I recently had a need for the skewed Cauchy distribution described here:
https://en.wikipedia.org/wiki/Skewed_generalized_t_distribution#skewed_Cauchy_distribution
Especially important to me is the fit() method for this distribution.
I don't have the skill to implement this, but I wanted to request adding the distribution to `stats`.

There are some other skewed distributions not in `stats` in the same Wikipedia article that may be of use to SciPy users.

**Comment by josef-pkt** [comment]
just a generic comment on names:

AFAIK, there are many "skew" extensions to various distributions. In statistics I think the best known skew-t version is by Azzalini.  
Distribution names will need to be chosen to disambiguate between different versions.

**Comment by adivijaykumar** [comment]
Do people think this is a good/useful enough feature to add? I can work on this.

**Comment by ev-br** [comment]
Go for it @adivijaykumar !
