### ISSUE TITLE
type of inequality constraints in scipy.optimize.minimize docstring

### ISSUE THREAD

**Issue by godaygo** [scipy/scipy#7439]
In docstring for `scipy.optimize.minimize` it is said 

> In general, the optimization problems are of the form:

    minimize f(x) subject to

    g_i(x) >= 0,  i = 1,...,m
    h_j(x)  = 0,  j = 1,...,p

Which in **general** is not true. The classical form is `g_i(x) <= 0,  i = 1,...,m`. As I see the issue comes from the fact that the only solver for constrained optimization problem is SLSQP, which uses this form.

**Comment by rkern** [comment]
It's just a convention. No generality is lost by making this choice of convention because constraints following one form can be trivially converted to the other form. The fact that they *can* be expressed in the other form (and even often *are*) doesn't reduce the generality.

**Comment by godaygo** [comment]
@rkern, I totally agree with you. It is the question of how you define the Lagrange function, but if you say **general** you should follow some convention to be in agreement with other world:). Also  `linprog` docstring is in accordance with **general** linear programming problem formulation, and no matter that for simplex method you should transform it to canonical form.

**Comment by rkern** [comment]
The way that we use the term in the docstring is in accord with my experience with the usage of the term in (English, at least) mathematics. It's claiming that the general class of problems that can be solved with this solver can be expressed in this form (and that this is the form that the solver is expecting). It is not claiming that most people use this convention in other contexts.

**Comment by rgommers** [comment]
There doesn't seem to be a bug here, so I'm going to close this issue.
