### ISSUE TITLE
[feature request]  use specific fit to scipy.stats.fit

### ISSUE THREAD

**Issue by DonBeo** [scipy/scipy#7443]
Distribution fitting in scipy is defined as a minimization process.   For many distribution this seems to be not a robust approach.  

I am wondering if we can override fit in some distributions. For example in the Gaussian Distribution we can simply estimate the mean and the variance. This is probably more efficient and more robust.

**Comment by WarrenWeckesser** [comment]
The `fit` method of `scipy.stats.norm` already uses the explicit formula for the maximum likelihood estimate, so yes, we can do that.

**Comment by pv** [comment]
To be clear --- fitting is not defined as minimization. It is the 
fallback method for distributions where a specialized method is not 
implemented.

**Comment by DonBeo** [comment]
ok thanks is a closed formula used for pareto?   I can not find the code where they are defined

**Comment by pv** [comment]
See _continuous_distns.py. pareto (and many other distributions) do not 
have specialized fitting, so certainly things could be improved here.

**Comment by DonBeo** [comment]
ok thanks that clear. If I have time I'll may do a pull request to add a custom pareto fit. Unfortunately I can not promise.

**Comment by DonBeo** [comment]
May I ask you what's the relationship between the current pareto fit and the "standard" parameter estimation as reported on wikipedia? 

The estimated distribution seems to have a different mean and std.  I'm wondering if I'm missing something.

```
import scipy as sp
import scipy.stats
import numpy as np
import matplotlib.pyplot as plt



x = 1 +  np.random.pareto(2, 1000)
n = len(x) * 1.0

'''
In [68]: x.mean()
Out[68]: 2.2603146810851475

In [69]: x.std()
Out[69]: 7.3893806656783285
'''


xm = x.min()
hat_alpha = n / np.sum( np.log(x) - np.log(xm))

'''
In [70]: xm
Out[70]: 1.0000494339408836

In [71]: hat_alpha
Out[71]: 1.9818425361737522
'''



floc = xm
params = sp.stats.pareto.fit(x, floc=floc, fscale=1)
alpha, loc, scale = params
xr = sp.stats.pareto(alpha, loc=loc, scale=scale).rvs(100)

'''
In [73]: alpha
Out[73]: 1.2343750000000007

In [74]: loc
Out[74]: 1.0000494339408836

In [75]: scale
Out[75]: 1

In [83]: xr.mean()
Out[83]: 3.8440256081564366

In [84]: xr.std()
Out[84]: 4.976118402015981

'''


floc = xm
params = sp.stats.pareto.fit(x, floc=floc, fscale=x.std())
alpha, loc, scale = params
xr = sp.stats.pareto(alpha, loc=loc, scale=scale).rvs(100)

'''
In [77]: alpha
Out[77]: 1.2331054687500007

In [78]: loc
Out[78]: 1.0000494339408836

In [79]: scale
Out[79]: 7.3893806656783285

In [86]: xr.mean()
Out[86]: 6.0520753945373169

In [87]: xr.std()
Out[87]: 4.9802092289331421

'''
```

**Comment by pv** [comment]
You probably wanted to use `floc=0, fscale=1` in the fit. See the 
scipy.stats.pareto documentation on how the location and scale are defined.

**Comment by DonBeo** [comment]
How can I replicate the result obtained using `loc=x.min()` with a close formula?
as for example:

```
alpha0 = 3                                                                                                                                                                                                         
x = 1 +  np.random.pareto(alpha0, 1000)                                                                                                                                                                            
n = len(x) * 1.0                                                                                                                                                                                                   
                                                                                                                                                                                                                   
                                                                                                                                                                                                                   
floc = x.min()                                                                                                                                                                                                     
params = sp.stats.pareto.fit(x, floc=floc, fscale=1)                                                                                                                                                               
alpha1, loc, scale = params                                                                                                                                                                                        
                                                                                                                                                                                                                   
x = x - x.min()                                                                                                                                                                                                    
xm = x.min()                                                                                                                                                                                                       
alpha2 = n / np.sum( np.log(x) - np.log(xm))                                                                                                                                                                       
                                                                                                                                                                                                                   
# I would like alpha1 == alpha2                                                                                                                                                                                    
print(alpha0, alpha1, alpha2)                      
```

**Comment by pv** [comment]
You seem to be confusing the location parameter with the starting point 
of the support of the distribution?

**Comment by WarrenWeckesser** [comment]
The parameterization used in the wikipedia article does not include a location parameter.  The mapping between wikipedia and scipy for the shape and scale parameters is

                  wikipedia    scipy
    shape           alpha        b
    scale            xm        scale

Here's an example that shows how to get `scipy.stats.pareto.fit()` to give the same result as the formulas shown in the wikipedia article.

First, the sample:

```
In [133]: x = np.array([2.5, 3, 3.5, 9, 10, 11, 14, 23])
```

Use the formulas to compute the maximum likelihood estimation:

```
In [134]: lnx = np.log(x)

In [135]: xmhat = x.min()

In [136]: xmhat  # Scale parameter estimate
Out[136]: 2.5

In [137]: alphahat = len(x)/(lnx - np.log(xmhat)).sum()

In [138]: alphahat  # Shape parameter estimate
Out[138]: 0.92919568135062869
```

Now use `scipy.stats.pareto.fit()` to do the estimation.  To match the above calculation, we must use `floc=0` so the `fit()` method doesn't include the location parameter in the fitting:

```
In [139]: fit_shape, fit_loc, fit_scale = pareto.fit(x, floc=0)
/Users/warren/miniconda3scipy/lib/python3.5/site-packages/scipy-1.0.0.dev0+8457a0f-py3.5-macosx-10.6-x86_64.egg/scipy/stats/_distn_infrastructure.py:2303: RuntimeWarning: invalid value encountered in double_scalars
  Lhat = muhat - Shat*mu

In [140]: fit_shape
Out[140]: 0.92918653928692263

In [141]: fit_scale
Out[141]: 2.4999999993431192
```

Given the default tolerances of the numerical  optimizer, those values match the results from the formulas.

**Comment by DonBeo** [comment]
ok I understand. So I run the fit method of a pareto with `loc = x.min()` . This means that I tried to fit a pareto to a set of samples `y=x-x.min()`.   

As a consequence I was fitting a pareto to a set of samples that started from 0. Given that the pareto has positive probability only for values `y>1` , it would have been reasonable to receive an error or a warning message.

**Comment by rgommers** [comment]
We can use improvements to `fit()` for many of the continuous distributions (and this is on our roadmap). PR's always welcome. No reason to keep this specific one open I think, all concrete questions were answered. So closing.
