### ISSUE TITLE
Doc: stats.dirichlet.var output description is wrong

### ISSUE THREAD

**Issue by PikalaxALT** [scipy/scipy#7444]
The output of `scipy.stats.dirichlet.var` is reported in the docstring as "scalar".  However, the output is actually an array of the same shape as `alpha`

**Comment by rgommers** [comment]
Thanks, good catch.

**Comment by cdouglass** [comment]
@rgommers Can this be closed?

**Comment by rgommers** [comment]
Yes, thanks @cdouglass!
