### ISSUE TITLE
manylinux1 py 3.5 & 3.6 wheels compiled against too new numpy version

### ISSUE THREAD

**Issue by letmaik** [scipy/scipy#7445]
The following fails on Python 3.5 and 3.6 (tested on x64 only) on Linux:

```sh
$ python -m venv test_scipy
$ source test_scipy/bin/activate
$ pip install numpy~=1.7.2 scipy~=0.18.1
...Downloading numpy-1.7.2.zip
...Downloading scipy-0.18.1-cp35-cp35m-manylinux1_x86_64.whl
$ python -c "from scipy.fftpack import ifftshift"
# for Python 3.5:
RuntimeError: module compiled against API version 9 but this version of numpy is 7
# for Python 3.6:
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x7
```

Since scipy 0.18.1 requires numpy >=1.7.1 it must be possible to use numpy down to that version. This is definitely a packaging/build problem when producing the wheels. My assumption is that in the CI builds simply the latest numpy version is installed, instead of installing 1.7.1 and then building against that version.

I consider this a quite bad bug as this undermines part of the usefulness of wheels. If I would build from source I wouldn't have those problems, but since pip picks up the binary wheels I'm left in the situation where the pip install itself was successful and only at runtime I get this dramatic failure.

**Comment by matthew-brett** [comment]
That was deliberate - see : https://github.com/MacPython/scipy-wheels/blob/master/.travis.yml#L60

As I remember, numpy doesn't pass its own tests on Python 3.5 before 1.9.0, and there are no numpy wheels for Python 3.5 < 1.9.0.    Python 3.5 was released on September 13, 2015 and numpy 1.9 was released on September 7 2014, so it seemed a bit unlikely to me (the packager) that anyone installing on Python 3.5 would be installing numpy > 1.9.

Can you say more about why you need it to work with numpy 1.7?

**Comment by letmaik** [comment]
I see, that all makes sense. Thanks for the details! I don't need to use numpy 1.7, my goal was just to make my own binary wheels as compatible as possible, so I just picked the minimum numpy version that was listed in the version specifiers of scipy. I will follow the same strategy then and install different numpy versions depending on the Python version. What a mess... it's really not easy to create binary wheels with numpy (and libraries depending on numpy like scipy) as dependency.

Since the version specifier is still kind of wrong, couldn't that at least be made more accuracte by using pip 6's [environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) and providing different numpy version identifiers for different python versions? Seems to be [supported by setuptools](https://stackoverflow.com/a/33451105) as well.

**Comment by matthew-brett** [comment]
To rephrase your problem - you have a package A that depends on numpy and scipy.  You're setting up a build environment to build wheels.  The numpy version that you need is, in practice, the minimum numpy version satisfying all your dependencies.  Your life is made more complicated by the fact that the practical dependencies are encoded in the wheel builds of the packages, like scipy, that depend on numpy.

The environment marker idea sounds reasonable - although I'm not sure how much it's going to help you.  For example, if you've installed numpy 1.7.1 and the environment marker for scipy says 1.9.0, then I'm guessing that, if the environment marker works, it will result in the install of the latest numpy, after the system recognizes that the existing numpy version is too old.

**Comment by matthew-brett** [comment]
I should also say that the dependencies you need to satisfy are only the build time dependencies.  So, for example, unless you import scipy during your setup.py script, you can get away with installing the minimum numpy that you need at build time, and then you can install another numpy for the tests.

**Comment by letmaik** [comment]
You're right, the environment marker wouldn't help me much in automating things, but at least I would be aware of the fact that it's trying to install a newer version, which I then could manually fix by setting the correct version for a specific python version. So, I think it would help all in all. Does scipy have the same numpy dependencies across OSes? If so, then it would be fairly easy to add those markers. If not, well, then it's an opportunity for aligning the wheels to provide more uniformity.

**Comment by letmaik** [comment]
Hm, so I followed your advice and installed my preferred numpy version at build time and then install the test dependencies later on. I do a `pip install scipy` which installs 0.19.0 via wheel, however this does not update the already installed numpy version and in turn leads again to "RuntimeError: module compiled against API version 9 but this version of numpy is 7". Shouldn't numpy be listed as install_requires with version for wheels?

**Comment by rgommers** [comment]
> Does scipy have the same numpy dependencies across OSes?

Yes

> and in turn leads again to "RuntimeError: module compiled against API version 9 but this version of numpy is 7".

Which version did you install exactly? 

There should be version markers in wheels now: https://github.com/scipy/scipy/blob/master/setup.py#L361. The commit that changed that behavior is in scipy 0.19.0: https://github.com/scipy/scipy/commit/edc4d6c43a08e29b8e510b9a347d5bc0a523e27d

**Comment by rgommers** [comment]
There doesn't seem to be anything left to do here, so closing.
