### ISSUE TITLE
binary_opening/binary_closing missing arguments

### ISSUE THREAD

**Issue by jakirkham** [scipy/scipy#7453]
As a comparison, [`binary_dilation`]( https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.ndimage.binary_dilation.html#scipy.ndimage.binary_dilation ) provides `mask`, `border_value`, and `brute_force`. While the purpose of `brute_force` is unclear ( https://github.com/scipy/scipy/issues/4586 ), the other two have clear meanings and value for these operations.

**Comment by adbugger** [comment]
I'd like to take this up and work on it. Looking at the code and the docs, it seems simple enough. The basic erosion and dilation operations are being called with default values for `mask`, `border_value`, and `brute_force`. Arguments can be added to the function definition with these default values.
