### ISSUE TITLE
imshow: use xdg-open instead of see

### ISSUE THREAD

**Issue by sedrubal** [scipy/scipy#7458]
[`scipy.misc.imshow`](https://github.com/scipy/scipy/blob/master/scipy/misc/pilutil.py#L418) uses `see` as default program to display an image unless you set the environment variable `SCIPY_PIL_IMAGE_VIEWER`. But `see` is not a common program (I don't even know how I could install it). On common linux desktops there is a program called [`xdg-open`](https://www.freedesktop.org/wiki/Software/xdg-utils/) to open files with their default application.

One problem is, that xdg-open does not wait until the program closes.

### Reproducing code example:
```py
from scipy.misc import imshow
import numpy as np

a = np.array([(1,2,3),(4,5,6)])
imshow(a)
```

### Error message:
```py
sh: see: command not found
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.6/site-packages/scipy/misc/pilutil.py", line 443, in imshow
    raise RuntimeError('Could not execute image viewer.')
RuntimeError: Could not execute image viewer.
```

### Scipy/Numpy/Python version information:
```
0.18.0 1.12.1 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
That sounds fine, however we're likely going to get rid of ``imshow`` completely soonish (see https://github.com/scipy/scipy/issues/6242#issuecomment-225424612, https://github.com/scipy/scipy/blob/master/doc/ROADMAP.rst.txt#misc). So may not be worth the effort to put in a PR now.

**Comment by rgommers** [comment]
``imshow`` is deprecated in gh-7869 so closing this issue. Thanks @sedrubal
