### ISSUE TITLE
(E.g.) cosine() should work for sparse matrices

### ISSUE THREAD

**Issue by DavidNemeskey** [scipy/scipy#7466]
Since sparse matrices were introduced in _scipy_, one would expect that all functions in _scipy_ would work for them. However, this is not the case. One example is `scipy.spatial.distance.cosine`, which doesn't work for sparse matrices. I find it very strange that if I use a simple data structure defined in another library, the function works, but if I want to mix in the data types defined in this very library, it does not. Granted, the situation with sparse matrices might be a bit more complex, but this is exactly the reason why _scipy_ should do the heavy lifting, and not leave it to the user.

### Reproducing code example:
```
from scipy.sparse import csr_matrix
from scipy.spatial import distance
csr = csr_matrix([[1, 2], [3, 4]], dtype=float)
distance.cosine(csr[0], csr[1])
```

### Error message:
```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    distance.cosine(csr[0], csr[1])
  File "/usr/local/lib/python2.7/dist-packages/scipy/spatial/distance.py", line 296, in cosine
    dist = 1.0 - np.dot(u, v) / (norm(u) * norm(v))
  File "/usr/local/lib/python2.7/dist-packages/scipy/sparse/base.py", line 317, in __mul__
    raise ValueError('dimension mismatch')
ValueError: dimension mismatch
```

### Scipy/Numpy/Python version information:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
It's not a bit more complex, it's a lot more complex. Sparse matrices do not conform to the ``ndarray`` interface, so most functions won't work with them out of the box. Also, it's a deliberate design decision to not convert sparse matrices to dense matrices or arrays, because that can easily blow up memory usage.

For future reference: asking why things are the way they are is usually a better approach than telling people how things should be:)

**Comment by DavidNemeskey** [comment]
In that case, one could imagine a `scipy.dot` or a `scipy.sparse.dot` function, which would work on both sparse and dense matrices (e.g. by making sure the sparse matrix is the one whose `.dot()` method is called), and then that could be used instead of `numpy.dot`. So, following your advice: why is it not so?

**Comment by rgommers** [comment]
Yes, a ``dot`` would be nice. It would be even nicer to have ``numpy.dot`` do the right thing with sparse matrices, which was actually implemented in a GSoC project a few years ago:
https://docs.scipy.org/doc/numpy-dev/neps/ufunc-overrides.html#demo. However, ``__numpy_ufunc__`` was then removed again from ``numpy`` (long story), and has just been re-added in a different form. So good question, and lots of history there - we may yet get there in the near future.
