### ISSUE TITLE
todense(), toarray() should be a module-level function and handle numpy.matrix

### ISSUE THREAD

**Issue by DavidNemeskey** [scipy/scipy#7467]
In order to facilitate duck typing, `scipy.sparse.XXX_matrix.todense()` should really be a module-level function, as `scipy.sparse.todense()`. I do not ask for the removal of `spmatrix.todense()`, as that would affect current code rather seriously, only the addition of the module-level function that also works on `numpy.matrix` objects (i.e. returning them as-is). A use-case (for matrix printing) is given below.

Same with `toarray()` and probably other functions.

I understand and agree that the kind of duck typing proposed in #5038 (adding `scipy.sparse` functions to `numpy.matrix`) is not necessarily felicitous, as _numpy_ is the "base" library and _scipy_ is the higher-level one, and also the one to introduce sparse matrices. However, the change I propose here would have similar benefits without polluting _numpy_ with extraneous components.

### Reproducing code example:

With
```python
>>> import numpy as np
>>> from scipy.sparse import csr_matrix, issparse  # , todense
>>> M = np.matrix([[1, 2], [3, 4]])
>>> C = csr_matrix(M)
```
, these are the hoops one must jump through now:
```python
def print_matrix(A):
    if issparse(A):
        print(A.todense())
    else:
        print(A)

print_matrix(M)
print_matrix(C)
```
, when it could simply be:
```python
print(todense(M))
print(todense(C))
```

### Scipy/Numpy/Python version information:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
```
, but any version, really.

**Comment by perimosocordiae** [comment]
I have two reservations about this proposal:
 1. The function's implementation seems pretty trivial. If you really need a function that does `foo = foo.todense() if issparse(foo) else foo`, it shouldn't be too burdensome to just write one where needed.
 2. Much of the sparse matrix API was designed to force the user to handle sparse matrices explicitly. For example, sparse methods (almost) never silently return a dense result, because we don't want to accidentally eat all available memory without you knowing it. (This is why `np.sin(x)` is allowed, but `np.cos(x)` is not.) In that vein, I think it might be detrimental to allow users to more easily say "I don't care if this is sparse or dense".

**Comment by ev-br** [comment]
+1 to what CJ said. These functions belong to the user code IMO.

**Comment by DavidNemeskey** [comment]
@perimosocordiae 

1. It is not as simple, as `todense()` returns a matrix and `toarray()` an array, right? So the function needs at least one more if-else level, which is just enough to make it impoossible to "inline" manually.
1. I understand the sentiment, and fully agree that such accidents should be avoided at all cost. However, with the two functions I am proposing, the user not only knows, but expects that a dense objects is created, so no accident is involved. As with the current `todense()`/`toarray()` functions.

**Comment by perimosocordiae** [comment]
I'm not sure what you mean with the extra if-else. Do you mean something like:
```python
foo = foo.toarray() if issparse(foo) else np.array(foo)
```
That would convert any of sparse/matrix/array to array.

**Comment by DavidNemeskey** [comment]
@perimosocordiae But that copies `foo` if it is an array, doesn't it? At least on my system, `A.data is np.array(A).data` returns `False`. I meant an if-else to prevent that.

**Comment by perimosocordiae** [comment]
Ah, in that case you can use `np.asarray(foo)`, or `np.array(foo, copy=False)`.

**Comment by DavidNemeskey** [comment]
@perimosocordiae True. Well, we have all said what we wanted to say, so the decision is up to you guys.
