### ISSUE TITLE
Parameter amax in scalar_search_wolfe2 is not used

### ISSUE THREAD

**Issue by PhilippWacker** [scipy/scipy#7475]
The line search method  scipy.optimize.linesearch.scalar_search_wolfe2 (which is used for scipy.optimize.linesearch.line_search_wolfe2) has the following header:

def scalar_search_wolfe2(phi, derphi=None, phi0=None,
                         old_phi0=None, derphi0=None,
                         c1=1e-4, c2=0.9, amax=50)

It allows a parameter amax which is the Maximum step size allowed but this parameter is nowhere used in the definition of the function (and I have a concrete function that I would like to minimize where I need this functionality).

As I am no expert in line search methods, I don't know how this bounding of the step size could be implemented without destroying the convergence property of the line search method.

**Comment by cdouglass** [comment]
@PhilippWacker In the Fortran-using version of this function, `scipy.optimize.linesearch.scalar_search_wolfe1`, it appears to me that if the step size reaches `amax` *and* this is still too small to meet the [strong Wolfe conditions](https://en.wikipedia.org/wiki/Wolfe_conditions), the function will give up on converging and return a step size of `None`. As far as I know this is the only way to use a max step size with this particular line search algorithm.

Thinking about alternatives, I think `scipy.optimize.linesearch.line_search_armijo` tries step sizes *decreasing* from the supplied `alpha_0` to find one that gives sufficient decrease in the objective function. The lack of a curvature requirement means it should to be guaranteed to converge on some step size under `alpha_0` (unless a too-large `amin` is somehow supplied to `scalar_search_armijo`). Would that work for your problem?

**Comment by PhilippWacker** [comment]
I circumvented the issue by scaling the cost function: My problem was that the line search didn't try small enough steps (and the cost function was always np.nan), so I scaled the input of the cost function such that it did find finite values. Thanks!

**Comment by cdouglass** [comment]
I've been poking at this function and am most of the way towards making a PR that fixes some documentation, uses the parameter, adds a few tests, and simplifies some of the code.

**Comment by rainwoodman** [comment]
@cdouglass, would you please make maxiter of the wolfe2 a parameter too? In some cases that number may be too restrictive. 

I encounter a case when the wolfe2 search returns None though a simple backtrace worked fine. It appears if the initial point is too far from the minimum, wolfe2 has either exhausted maxiter or amax.
