### ISSUE TITLE
wrong condition in rv_continuos.fit for initial parameters estimation

### ISSUE THREAD

**Issue by DonBeo** [scipy/scipy#7476]
in `rv_continuos.fit ` if `loc` and `scale` are not in kwds the `self._fitstart` method is called.
Here `loc` and `scale` are fitted  as `loc, scale = self._fit_loc_scale_support(data, *args)`. 

Now my understanding is that  `loc` and `scale` should not be fitted if `floc` are `fscale` are in kwds. 

I'm wondering if in the code below, taken from `rv_continuos.fit ` should check for `floc` and `fscale` in kwds rather than `loc` and `scale`. 

```
      Narg = len(args)
        if Narg > self.numargs:
            raise TypeError("Too many input arguments.")

        start = [None]*2
        if (Narg < self.numargs) or not ('loc' in kwds and
                                         'scale' in kwds):
            # get distribution specific starting locations
            start = self._fitstart(data)
```

I do not know if this is a bug or if I am misunderstanding the algorithm but I have the feeling that `loc` and `scale` are computed with no reason.

**Comment by josef-pkt** [comment]
If you don't have a failing example, then the code is correct. I haven't heard of a case where it doesn't work in a long time. 
AFAIR, the fixed parameter are handled separately, and that code is quite tricky and took several rounds of bug fixes.

Computing loc, scale is a redundant computation, but then all `_fitstart` need extra keywords and need to be written to handle floc and scale.

**Comment by DonBeo** [comment]
Thanks. So I understood correctly that `_fitstart` is a redundant computation which results are actually never used (if floc and fscale are passed as arguments).

I have raised this issue for 2 reasons. 
1) it's making the code slower
2) In my code `_fitstart` raises a warning.  I had to spend a lot of time investigating for the cause to discover that it was in "redundant" code not effecting the overall result.

**Comment by josef-pkt** [comment]
(I don't really have time to look at the details.)

Can you provide an example to illustrate the problem?

It is possible to add more arguments and options to `_fitstart`, but it's quite a bit of work because it needs to be changed in the generic code and all subclasses.
And most likely, the use of extra keyworks in the  call to `_fitstart` will have to be `try ... except TypeError` protected for backwards compatibility with user distributions.

**Comment by sethtroisi** [comment]
Closing old issue with no code sample provided and no follow up
