### ISSUE TITLE
Strange dimension of input in signal

### ISSUE THREAD

**Issue by aleksey-sinos** [scipy/scipy#7477]
Hi,
I'm just started with scipy.signal and I was a bit confused by the input dimension in e.g. dlsim function.
U (input) should have an [p\*t] size in order that B[n\*p]\*U[p\*t\_i] = [n\*1]. But in scipy.signal opposite to linear algebra and Matlab, U have [t\*p] size thus different inputs are columns, not rows as it should be.

Could anyone explain why it is like that?
Thank you!

**Comment by rgommers** [comment]
It's just a convention, and the docstring does explain it:

    u : array_like
        An input array describing the input at each time `t` (interpolation is
        assumed between given times).  If there are multiple inputs, then each
        column of the rank-2 array represents an input.

The code does a transpose internally.
