### ISSUE TITLE
Many additional FAIL/ERROR with build/test using '-g' flag, (MacOS 10.12, MacBookPro)

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#7487]
Lots of additional errors appeared when using '-g' during `runtests.py` testing, as did one python malloc error. 
[H/W MacBookPro (late 2016) running MacOS 10.12.5]

I observed lots of errors when running tests with '-g'.  There are 4 possible combinations of building and running tests with this flag, and 3 are described below.
setup.py build with/without '-g'.
runtests.py with/without -g.

1. No '-g' flag in either build or test.
FAILED (KNOWNFAIL=90, SKIP=1895, errors=8, failures=45)  
2. Build with '-g', runtests.py with '-g'.
FAILED (KNOWNFAIL=90, SKIP=1895, errors=175, failures=124)
3. Build with '-g', runtests.py without it.
runtests.py dies during test_arpack after reporting a malloc error

Details:
1. No '-g' flag in either build or test.
FAILED (KNOWNFAIL=90, SKIP=1895, errors=8, failures=45)  
Errors/Failures by type:
   1 test_basic.TestMatrixNorms.test_matrix_norms
   1 test_basic.TestVectorNorms.test_overflow
   1 test_asum
   1 test_dot
   1 test_nrm2
   1 test_slamch
   1 test_lange
   5 test_arpack.test_symmetric_modes
   3 test_arpack.test_real_nonsymmetric_modes
  38 test_iterative.test_convergence

2. Build with '-g', runtests.py with '-g'.
FAILED (KNOWNFAIL=90, SKIP=1895, errors=175, failures=124)
Errors/Failures by type:
   1 test_basic.TestMatrixNorms.test_matrix_norms
   1 test_basic.TestVectorNorms.test_overflow
   1 test_asum
   1 test_dot
   1 test_nrm2
   1 test_complex_args
   1 test_lange
  76 test_arpack.test_symmetric_modes
  48 test_arpack.test_hermitian_modes
   5 test_arpack.test_symmetric_starting_vector
  53 test_arpack.test_real_nonsymmetric_modes
  54 test_arpack.test_complex_nonsymmetric_modes
   8 test_arpack.test_standard_nonsymmetric_starting_vector
   8 test_arpack.test_general_nonsymmetric_starting_vector
   1 test_arpack.test_svd_linop
  38 test_iterative.test_convergence

The bulk of the additional '-g' errors/failures involved test_arpack.

3. Build with '-g", runtests.py without it.
runtests.py dies during test_arpack after reporting a malloc error
python(47504,0x7fffef7623c0) malloc: *** error for object 0x7ff1bb99c9e8: incorrect checksum for freed object - object was probably modified after being freed.

Expected behavior? 

### Reproducing shell example:
python setup.py build -v -f
pip install -v .
python runtests.py -n -v -j3 > runtests.log 2>&1
pip uninstall scipy

python setup.py build -v -g -f
pip install -v .
python runtests.py -n -v -j3 > runtests.g.log 2>&1
python runtests.py -n -g -v -j3 > runtests.g2.log 2>&1

### Scipy/Numpy/Python version information:
```
1.0.0.dev0+3c1b095 1.13.0 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
Not expected on osx. Looks like the BLAS/LAPACK is broken in your build.
.
Note that `setup.py build` and `pip install` should not be necessary, 
runtests.py should be fine by itself.
.
Try to see if it works in a clean rebuild; do `rm -rf build` etc. If 
not, attach the build log (for a clean rebuild) or post it at 
gist.github.com.

**Comment by pv** [comment]
It appears you are using intel MKL on OSX. The test failures look like 
it's linking in a version of this library with the wrong fortran ABI.

**Comment by pvanmulbregt** [comment]
Thanks.  I'm using Anaconda as a base for the Python environment.  All the .so files built by SciPy seem to use libgfortran.4.dylib.
```
$ find  build/lib.macosx-10.7-x86_64-3.6/scipy -regex ".*\.so" | xargs otool -L | fgrep fortran
    /usr/local/opt/gcc/lib/gcc/7/libgfortran.4.dylib (compatibility version 5.0.0, current version 5.0.0)
    ...
```

The fortran compiler appears to be  /usr/local/bin/gfortran, installed by homebrew.
``` 
$ /usr/local/bin/gfortran --version
GNU Fortran (Homebrew GCC 7.1.0) 7.1.0`.
```

Env variables are
```
export CC=clang
export CXX=clang++
export LDFLAGS="$LDFLAGS -undefined dynamic_lookup -bundle"
export FFLAGS=-ff2c
```
(set after reading https://www.scipy.org/scipylib/building/macosx.html) The first 3 seem necessary. I rebuilt just now without the FFLAGS and it didn't change any of the errors.


Is it possible to specify which version of the library to link in? 
Or specify how to build scipy in a manner compatible with the installed libraries?

**Comment by pv** [comment]
Those instructions are probably out of date. AFAIK, it should build out of the box, but on the other hand I don't use osx. FFLAGS should not be necessary (although it likely doesn't affect anything).

Read site.cfg.example if you want to build with MKL. Information about which library has which fortran ABI is probably found in intel MKL documentation. You want the g77 one. However, I'm not sure if building against intel MKL obtained from anaconda is actually possible, or whether you need openblas etc.

**Comment by rgommers** [comment]
> Those instructions are probably out of date.

They are. Things on OS X build fine for current master with no env vars set.

> $ /usr/local/bin/gfortran --version
> GNU Fortran (Homebrew GCC 7.1.0) 7.1.0`.

Not sure that has been tested before, it's brand new. I've used ``GNU Fortran (Homebrew gcc 4.9.1) 4.9.1`` for a long time.

**Comment by mdhaber** [comment]
I'm doing a survey of the open issues in support of the CZ grant opportunity, and I'm trying to understand what would be required to close this issue. If I were to successfully build with MKL on a Mac (and update the build instructions if any notes were needed) with a recent version of Homebrew's GCC, would that close the issue?

**Comment by pvanmulbregt** [comment]
This was quite some time ago.  I'm running again to see if the failures still exist.

**Comment by mdhaber** [comment]
Thank you!

**Comment by pvanmulbregt** [comment]
Currently in my environment I see the same 15 failures with or without `-g`, in build/or test.
```
TestVectorNorms.test_overflow
TestMatrixNorms.test_matrix_norms
TestFBLAS1Simple.test_asum
TestFBLAS1Simple.test_dot
TestFBLAS1Simple.test_nrm2
TestWfuncPointers.test_complex_args
TestFlapackSimple.test_lange
test_symmetric_modes
test_hermitian_modes
test_symmetric_starting_vector
test_real_nonsymmetric_modes
test_complex_nonsymmetric_modes
test_standard_nonsymmetric_starting_vector
test_general_nonsymmetric_starting_vector
test_svd_linop
```

I'm presuming it is something to do with whatever BLAS/LAPACK is installed on my machine, but certainly the differences due to use of `-g` are gone, so I'll close out this Issue.

**Comment by dimpase** [comment]
How does one build scipy so that Fortran is called without `-g` flag, is it configurable somehow?
(I'd like to use flang, which has problems with `COMMON` blocks if `-g` is used)
