### ISSUE TITLE
DOC: tutorial/stats/continuous_beta.rst: Is there an extraneous term in the PDF formula?

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#7488]
The tutorial file `doc/source/tutorial/stats/continuous_beta.rst` lists the probability density function formula for the beta distribution as:
`f\left(x;a,b\right) & = & \frac{\Gamma\left(a+b\right)}{\Gamma\left(a\right)\Gamma\left(b\right)} x^{a-1} \left(1-x\right)^{b-1} I_{\left(0,1\right)}\left(x\right)`

Is the last term `I_{\left(0,1\right)}\left(x\right)` required?  The formula appears to be correct without it (e.g. https://en.wikipedia.org/wiki/Beta_distribution) and the term is not defined on this page, so perhaps it is no longer needed?

### Scipy/Numpy/Python version information:
1.0.0.dev0+9597f6a 1.14.0.dev0+d93a5dd sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)

**Comment by josef-pkt** [comment]
It's essentially redundant. The support is the open interval (0, 1), but at the end of the page it uses closed interval [0,1]

I spot checked a few distributions and they don't use the indicator function for the support.

**Comment by pvanmulbregt** [comment]
Thanks for the explanation.  As you point out the indicator functions don't appear to be used often and having them requires checking consistency with text elsewhere on the page.

**Comment by chrisb83** [comment]
This was fixed in #9953
