### ISSUE TITLE
stats.ttest_ind() and stats.mannwhitneyu() return different shaped arrays for same shaped arrays

### ISSUE THREAD

**Issue by swdrsk** [scipy/scipy#7489]
stats.ttest_ind() and stats.mannwhitneyu() return different shaped arrays for same shaped arrays.
These may be inconvenient. Is there inevitable reason for that?

### Reproducing code example:
```
a = np.random.normal(0,1,size=[100,10])
b = np.random.normal(0.5,1,size=[100,10])
stats.ttest_ind(a,b).pvalue
```
> array([  8.51249223e-05,   1.20024906e-04])
```
a = np.random.normal(0,1,size=[100,10])
b = np.random.normal(0.5,1,size=[100,10])
stats.mannwhitneyu(a,b).pvalue
```
> 4.6889421198857571e-29
>> "array([  *,   *])" may be ideal.
 
### Scipy/Numpy/Python version information:
```
('0.19.0', '1.13.0', sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0))
```

thanks

**Comment by sethtroisi** [comment]
Closing old bug report.

`ttest_ind` by default uses `axis=0` and returns an array the size of the remaining dimensions. I suspect you passed something of shape [X, 2] to get 2 return values. 

`mannwhitneyu` only takes a 1d input `x, y: Array of samples, should be one-dimensional.`
