### ISSUE TITLE
Memory leak scipy.integrate.dblquad

### ISSUE THREAD

**Issue by ZGCDDoo** [scipy/scipy#7490]
<<There seems to be a memory leak in dblquad in python3.6.1 and newest scipy versions. Versions are below. Run code and look at memory in both versions before "enter". Problems reproduced on Windows and linux. Sorry for poor formatting not used to writing issues.>>

### Reproducing code example:
```
<<
from scipy.integrate import dblquad


def y1(x):
    return -1.10


def y2(x):
    return 1.10


def fct(x, y):
    return (np.exp(-x*y) + 1.0 + x*np.cos(x*y) )


if __name__ == "__main__":

    for i in range(10000):
        tmp = dblquad(fct, -1.1, 1.1, y1, y2)

    tmp = input("Finished!")>>
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)':
Problematic: 0.19.0, 1.12.1, sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
Ok:          0.18.1m 1.11.3, sys.version_info(major=3, minor=6, micro=0, releaselevel='final', serial=0)

>>
```

**Comment by rgommers** [comment]
Thanks @ZGCDDoo. This was fixed in gh-7216, so closing. A 0.19.1 release with the fix included should be released shortly.
