### ISSUE TITLE
Several scipy.stats distributions (fisk, burr, burr12, f) return incorrect pdf at left endpoint

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#7491]
Several statistics distributions (`fisk`, `burr`, `burr12`,`f`) return incorrect values for the `pdf()` at the left endpoint.

The value of `pdf(0)` is dependent on the shape parameters used when creating the frozen distribution. (All the cases below have x=0 as the left end point. )  For some values of the shape parameters, the true pdf is 0 at the left endpoint, others times it is `\infty`, and other times it is a value in between.  However, `pdf(0)` always returns 0 for `fisk/burr/burr12`.

For the F distribution with `dfn=2`, the value of `scipy.stats.f(2,dfd).pdf(0)` should always be 1, regardless of the value of `dfd`, but it returns `nan`.

The code below shows the distribution and its parameters, the value returned by `pdf(0)`, the theoretically correct value, as well as the pdf(x) for a sequence of x approaching 0 (x=0.1, 0.01, 0.001,...). These latter pdf values appear to be approaching the correct value, but a sudden jump/discontinuity occurs at x=0.
### Reproducing code example:
```
import numpy as np
import scipy.stats
# Show the pdf at the left endpoint dst.a, and at x-values approaching the endpoint
for f, args, correct in [[scipy.stats.fisk, (1,), 1], 
               [scipy.stats.burr, (0.5, 2), 1],
               [scipy.stats.burr, (1, 1), 1],
               [scipy.stats.burr, (2, 0.5), 1],
               [scipy.stats.burr12, (1, 0.5), 0.5],
               [scipy.stats.burr12, (1, 1), 1.0],
               [scipy.stats.burr12, (1, 2), 2.0],
               [scipy.stats.f, (2, 1), 1.0],
               ]:
    dst = f(*args)
    print('%-15s' % (dst.dist.name + str(args)), 'pdf(0)=', dst.pdf(dst.a),
        'correct= %-3.1f' % correct, 'pdf([0.1, 0.01,...])=', dst.pdf(dst.a + 0.1**np.arange(1,5)))
```

### Error message:
```
fisk(1,)        pdf(0)= 0.0 correct= 1.0 pdf([0.1, 0.01,...])= [ 0.82644628  0.98029605  0.998003    0.99980003]
burr(0.5, 2)    pdf(0)= 0.0 correct= 1.0 pdf([0.1, 0.01,...])= [ 0.43853762  0.7513148   0.91082981  0.97059015]
burr(1, 1)      pdf(0)= 0.0 correct= 1.0 pdf([0.1, 0.01,...])= [ 0.82644628  0.98029605  0.998003    0.99980003]
burr(2, 0.5)    pdf(0)= 0.0 correct= 1.0 pdf([0.1, 0.01,...])= [ 0.98518534  0.99985002  0.9999985   0.99999999]
burr12(1, 0.5)  pdf(0)= 0.0 correct= 0.5 pdf([0.1, 0.01,...])= [ 0.43339209  0.49259267  0.49925094  0.49992501]
burr12(1, 1)    pdf(0)= 0.0 correct= 1.0 pdf([0.1, 0.01,...])= [ 0.82644628  0.98029605  0.998003    0.99980003]
burr12(1, 2)    pdf(0)= 0.0 correct= 2.0 pdf([0.1, 0.01,...])= [ 1.5026296   1.9411803   1.99401198  1.99940012]
f(2, 1)         pdf(0)= nan correct= 1.0 pdf([0.1, 0.01,...])= [ 0.76072577  0.97073289  0.99700748  0.99970007]
```

### Scipy/Numpy/Python version information:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
It's continuous distribution, so I think the point values of pdf are strictly speaking not defined uniquely.
Of course, it should be fixed nevertheless to give continuous result.

**Comment by pvanmulbregt** [comment]
I think this might be a result #6246, which added a _support_mask to class rv_generic, in order to solve an issue with fit() #6167.   It appears to apply this to the x-values inside the `pdf/logpdf/nnlf` and `_nnlf_and_penalty()` methods.

I think there may be some unforeseen implications with the _open_support_mask concept as implemented.
```
    def _open_support_mask(self, x):
        return (self.a < x) & (x < self.b)
```

1. It doesn't distinguish between the left and right endpoints.   Some distributions have different behavior at the two endpoints (0 vs finite vs infinite).
2. It doesn't allow for different behavior based on the shape parameters.
3. #6167 refers to "support of the distribution".  Isn't that the closure of the interval, hence would always include the endpoints?

What was the exact problem in #6167?  Did a pdf() of 0 (or infinity) arise, and give problems for a likelihood calculation?
 
[The PDF is well-defined in these cases, throughout the whole of the interval.  The CDF is a nice function, differentiable everywhere inside the interval. The derivative of the CDF has a finite limit at the endpoints, hence the PDF is just the derivative of the CDF.]

**Comment by pvanmulbregt** [comment]
The PR #6246 added `_support_mask` and used it in several methods of rv_continuous (`pdf`, `logpdf`, `nnlf`, `_nnlf_and_penalty`) to replace `(self.a <= x) & (x <= self.b)` with `self._support_mask(x)`.  It also replaced `(x > self.a) & (x < self.b)` with `self._open_support_mask(x)` in (`cdf`, `logcdf`, `sf`, `logsf`).  
 
The change in behavior was that in addition to the above, a distribution could set its `_support_mask = rv_continuous._open_support_mask`, and then the first four methods above (`pdf`, `logpdf`, `nnlf`, `_nnlf_and_penalty`) would not be asked to compute values at the endpoints. 

This had a side-effect. If a distribution sets its `_support_mask`, then the `pdf()` method returns incorrect values at the endpoints. 
For `cdf`, `sf` etc, not computing at the endpoints is fine, because `cdf(self.a)=0`, `cdf(self.b)=1`, and these values are naturally being placed in the output, either with the output's creation via `zeroes(..)`, or a 1 is placed there afterwards.
For the `pdf(self.a), pdf(self.b)` at the endpoints, that's not the case.  The correct value could be 0, infinity, or somewhere in between, and only the distribution knows.

@pbrod, @zym1010 or @josef-pkt:  Can you say more on what required the change to occur in the `pdf/logpdf/nnlf` methods, and not just the `nnlf_and_penalty` method which is the one obviously used in `fit()`?

**Comment by zym1010** [comment]
@pvanmulbregt regarding <https://github.com/scipy/scipy/issues/7491#issuecomment-308538089>

> What was the exact problem in #6167? Did a pdf() of 0 (or infinity) arise, and give problems for a likelihood calculation?

the problem was that, `rv_continuous.fit` at that time simply will treat values equal to the boundaries as invalid fit, and would return infinity. Didn't try computing `pdf` before.

**Comment by pvanmulbregt** [comment]
It appears that the current `rv_continuous.fit` calls `self._nnlf_and_penalty(x)` which 
1. calls `self._support_mask(x)` to exclude x values outside the range, and also possibly exclude the endpoints,
2. calls `self._logpdf()` on the remaining x values to get neg-log-probs;
3. removes any neg-log-prob values which aren't finite,
4. incurs a penalty for each excluded neg-log-prob

Does this mean that the `_open_support_mask` is having no longer needed for the operation of `fit`? 
I.e. If the endpoints weren't excluded at step 1, but still had an infinite logprob, then wouldn't they be removed anyway?

**Comment by chrisb83** [comment]
`gausshyper` and `mielke` are other examples where the continuity at the endpoints depends on the shape parameters
