### ISSUE TITLE
scipy.special.kolmogorov(x)/kolmogi(p) inefficient, inaccurate near x=0, p=1

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#7492]
K1. `scipy.special.kolmogorov(x)` is inefficient near x=0
K2. `scipy.special.kolmogi(p)` is inefficient often, but especially near p=1.  
K3. `scipy.special.kolmogi(p)` is not accurate for p close to 1

K1. `scipy.special.kolmogorov(x)` calculates the probability that a gap at least size x will occur.  It does so by calculating the sum over all integers of `(-1)**k exp(-2k**2 x**2)`, terminating when the individual terms become small.  For x close to 0, there are a lot of such terms to sum, on the order of `4/x`.  (For x=0.01 it takes more than 400 terms:  `0.9998 - 0.9992 + 0.9982 - 0.9968 ...= 0.5`)

K2. `scipy.special.kolmogi()` is inefficient near p=1 for several reasons. 
It uses the first term of the above series to generate a starting estimate for some iterations of Newton-Raphson root-finding. This is great for large x (small p) , but not so useful for small x (large p). 
It uses the first term in that same series to approximate the derivative.  Great for large x, not for small x.  The result is that many iterations of N-R can occur before the function returns, sometimes more than 100.
The third reason is that every time `kolmogi()` calls `kolmogorov(x)` for small x, the latter needs many terms in that series. I.e. Many iterations, each iteration making many calls to exp.  I've observed it evaluating ~2000 exponentials.

K3. The accuracy problem occurs because the approximated derivative is too big, so the steps taken by each N-R iteration are too small, and `kolmogi()` thinks it must be done.  The smallest value returned by `kolmogi(p)` is about 0.32733, much bigger than x=0.
So the convergence is not quadratic for p close to 1, and even when it does converge the answer might not be close to the true value.

The code below shows the accuracy issue K3, as it evaluates `kolmogi(1.0-epsilon)` for `epsilon=0.1, 0.01, ..., 1e-13`. The returned x-values bottom out at  0.32733602, even though they should keep going down to ~0.1948.  And the errors start to get bigger in the round trip `kolmogorov(kolmogi(1.0-epsilon))`, which should be the identity.

### Reproducing code example:
```
import numpy as np
import scipy.special
epsilon = 0.1**np.arange(1,14)
x = scipy.special.kolmogi(1-epsilon)
print('s.s.kolmogorov(p) returned x=')
print(x)
# Now compute the probabilities corresponding to these x's
p = scipy.special.kolmogorov(x)
print('1-s.s.kolmogorov(x) = (should be 0.1**n)')
print(1-p)
print('Relative errors in 1-p')
print((1-p-epsilon)/epsilon)
print()

print('Correct x=')
xtrue = np.array([0.571173265106, 0.441027698518, 0.374219690278, 0.331392659217,
                  0.300820537459, 0.277539353999, 0.259023494805, 0.243829561254,
                  0.231063086389, 0.220135543236, 0.210641372041, 0.202290283658,
                  0.19487060742])
print(xtrue)
p = scipy.special.kolmogorov(xtrue)
print('1-s.s.kolmogorov(xcorrect)= (should be 0.1**n)')
print(1-p)
print('Relative errors in 1-p')
print((1-p-epsilon)/epsilon)
print()
print('Absolute Errors in s.s.kolmogi(p) values:')
print(x-xtrue)
print('Relative Errors in s.s.kolmogi(p) values:')
print((x-xtrue)/xtrue)
```

### Error message:
```
s.s.kolmogorov(p) returned x=
[ 0.57117327  0.4410277   0.37422133  0.33682959  0.32838724  0.32744223
  0.32734665  0.32733709  0.32733613  0.32733603  0.32733602  0.32733602
  0.32733602]
1-s.s.kolmogorov(x) = (should be 0.1**n)
[  1.00000000e-01   1.00000001e-02   1.00007284e-03   1.40981476e-04
   8.20817737e-05   7.70510848e-05   7.65573687e-05   7.65080913e-05
   7.65031645e-05   7.65026718e-05   7.65026225e-05   7.65026176e-05
   7.65026171e-05]
Relative errors in 1-p
[  6.31735497e-10   9.28762692e-09   7.28417558e-05   4.09814756e-01
   7.20817737e+00   7.60510848e+01   7.64573687e+02   7.64980913e+03
   7.65021645e+04   7.65025718e+05   7.65026125e+06   7.65026166e+07
   7.65026170e+08]

Correct x=
[ 0.57117327  0.4410277   0.37421969  0.33139266  0.30082054  0.27753935
  0.25902349  0.24382956  0.23106309  0.22013554  0.21064137  0.20229028
  0.19487061]
1-s.s.kolmogorov(xcorrect)= (should be 0.1**n)
[  1.00000000e-01   1.00000000e-02   1.00000000e-03   1.00000000e-04
   1.00000000e-05   1.00000000e-06   9.99999998e-08   1.00000004e-08
   9.99999972e-10   9.99997862e-11   1.00003339e-11   9.99977878e-13
   9.99200722e-14]
Relative errors in 1-p
[ -3.91159327e-12   1.87697080e-12  -1.22118027e-11  -1.67636629e-11
   2.87554133e-11   1.39777589e-10  -1.63657922e-09   3.83314495e-08
  -2.82819319e-08  -2.13770568e-06   3.33894311e-05  -2.21217201e-05
  -7.99277837e-04]

Absolute Errors in s.s.kolmogi(p) values:
[  5.53184165e-11   3.50457108e-10   1.64015101e-06   5.43693365e-03
   2.75666999e-02   4.99028772e-02   6.83231588e-02   8.35075238e-02
   9.62730417e-02   1.07200489e-01   1.16694651e-01   1.25045738e-01
   1.32465414e-01]
Relative Errors in s.s.kolmogi(p) values:
[  9.68505004e-11   7.94637409e-10   4.38285599e-06   1.64063189e-02
   9.16383573e-02   1.79804689e-01   2.63772052e-01   3.42483181e-01
   4.16652626e-01   4.86974923e-01   5.53996822e-01   6.18149997e-01
   6.79760874e-01]
```

### Scipy/Numpy/Python version information:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by pvanmulbregt** [comment]
`kolmogorov(x)` is a Jacobi theta function.   Using one of the Jacobi identities provides an alternate series which can be used to evaluate `kolmogorov(x)`, and this alternate series is rapidly convergent near x=0. 
(See https://en.wikipedia.org/wiki/Kolmogorov–Smirnov_test and https://en.wikipedia.org/wiki/Theta_function#Jacobi_identities.)
I have an initial implementation of this which keeps the original series for large x, the new one for small x.  The hybrid approach bounds the max number of loop iterations to 6, with an average of 4.  It also typically has many more accurate digits.  (Addresses issue K1)
Modifications to the `kolmogi(p)` code make it both faster (~4x) and more accurate for p>0.5. The maximum number of N-R iterations observed is now about 10  (Addresses issues K2, K3)

**Comment by rgommers** [comment]
Looking a lot better after gh-8737:
```
s.s.kolmogorov(p) returned x=
[0.57117327 0.4410277  0.37421969 0.33139266 0.30082054 0.27753935
 0.25902349 0.24382956 0.23106309 0.22013554 0.21064136 0.20229046
 0.19487032]
1-s.s.kolmogorov(x) = (should be 0.1**n)
[1.00000000e-01 1.00000000e-02 1.00000000e-03 1.00000000e-04
 1.00000000e-05 1.00000000e-06 9.99999999e-08 1.00000001e-08
 9.99999972e-10 1.00000008e-10 1.00000008e-11 9.99977878e-13
 1.00031095e-13]
Relative errors in 1-p
[-2.77555756e-16  6.93889390e-16  6.50521303e-16 -1.10317571e-13
 -4.55127743e-12  2.87552863e-11 -5.26356200e-10  5.02475876e-09
 -2.82819319e-08  8.27403704e-08  8.27403704e-08 -2.21217201e-05
  3.10945187e-04]

Correct x=
[0.57117327 0.4410277  0.37421969 0.33139266 0.30082054 0.27753935
 0.25902349 0.24382956 0.23106309 0.22013554 0.21064137 0.20229028
 0.19487061]
1-s.s.kolmogorov(xcorrect)= (should be 0.1**n)
[1.00000000e-01 1.00000000e-02 1.00000000e-03 1.00000000e-04
 1.00000000e-05 1.00000000e-06 9.99999999e-08 1.00000001e-08
 9.99999972e-10 1.00000008e-10 1.00000008e-11 9.99977878e-13
 1.00031095e-13]
Relative errors in 1-p
[-3.90937283e-12  1.87697080e-12 -1.23228251e-11 -1.89841090e-11
  3.98576436e-11  2.87552863e-11 -5.26356200e-10  5.02475876e-09
 -2.82819319e-08  8.27403704e-08  8.27403704e-08 -2.21217201e-05
  3.10945187e-04]

Absolute Errors in s.s.kolmogi(p) values:
[ 3.40172335e-13 -7.06101844e-14  2.78388423e-13  2.89823721e-13
 -5.13034060e-13 -1.27176047e-13 -9.93927163e-13 -4.25703917e-12
 -1.69310954e-11 -3.41826484e-10 -1.60179922e-08  1.71652809e-07
 -2.87485252e-07]
Relative Errors in s.s.kolmogi(p) values:
[ 5.95567677e-13 -1.60103741e-13  7.43917091e-13  8.74562886e-13
 -1.70544892e-12 -4.58227079e-13 -3.83720853e-12 -1.74590773e-11
 -7.32747739e-11 -1.55280006e-09 -7.60439038e-08  8.48546979e-07
 -1.47526226e-06]
```
