### ISSUE TITLE
Fix for basinhopping unnecessary overflow warning

### ISSUE THREAD

**Issue by mvds314** [scipy/scipy#7495]
I am experiencing the following warning:
\scipy\optimize\_basinhopping.py:299: RuntimeWarning: overflow encountered in exp
`  w = min(1.0, np.exp(-(energy_new - energy_old) * self.beta))`

The warning is a bit annoying an unnecessary. I don't have an example to reproduce the warning, but the solution is simple. The statement effectively ensures that you only take the exp of a positive number. So, just use the following mathematically equivalent statement:
`w = np.exp(min(0, -(energy_new - energy_old) * self.beta))`

I am using scipy version 0.19.0

**Comment by andyfaff** [comment]
That seems reasonable to me. Could you prepare a PR for the change, with tests?

**Comment by mvds314** [comment]
I'm afraid my experience with git, testing and version to control is too limited to prepare a PR. At the moment, I cannot do more that submitting a bug or fix now and then.

**Comment by andyfaff** [comment]
I'll do this.
