### ISSUE TITLE
linalg.solve test failure on OS X with Accelerate

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#7500]
numpy 1.13.0, scipy 1.0.0.dev0+af8d8a, clang ``Apple LLVM version 8.1.0 (clang-802.0.42)``, OS X 10.12

    ======================================================================
    FAIL: test_all_type_size_routine_combinations (test_basic.TestSolve)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/rgommers/Code/scipy/scipy/linalg/tests/test_basic.py", line 777, in test_all_type_size_routine_combinations
        err_msg=err_msg)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/testing/utils.py", line 1395, in assert_allclose
        verbose=verbose, header=header, equal_nan=equal_nan)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/numpy/testing/utils.py", line 778, in assert_array_compare
        raise AssertionError(msg)
    AssertionError: 
    Not equal to tolerance rtol=0.001, atol=0.001
    Failed for size: 1000, assume_a: gen,dtype: <class 'numpy.float32'>
    (mismatch 99.0%)
     x: array([ -6.714335e+03,  -1.028524e+04,   5.493511e+03,  -1.711655e+04,
             1.501354e+03,  -4.972360e+03,   1.454109e+04,   2.557593e+03,
            -2.108792e+03,   1.014837e+04,  -6.180545e+03,  -1.128914e+04,...
     y: array([  1.107730e+00,  -1.649878e+00,  -4.139251e-01,   1.680367e+00,
            -2.301190e-01,   1.760759e+00,  -3.823581e-01,  -7.982016e-01,
             2.277969e+00,  -9.161606e-02,  -2.823512e-01,   1.916860e+00,...

**Comment by ilayn** [comment]
Unfortunately, I can't replicate this on any Windows 10, 7, Ubuntu 16.04 or Mint. Would you please add the version of LAPACK?

**Comment by rgommers** [comment]
> Would you please add the version of LAPACK?

It's the version of Accelerate that is shipped as part of OS X 10.12. Will likely be specific to that lib. I'll find some time later to investigate - it's not super urgent, just needs to be tackled before the next release.

**Comment by rgommers** [comment]
Test skipped for 1.0.0, a more structural fix is for 1.1.0

**Comment by ilayn** [comment]
@rgommers Do you still have the setup to replicate this?

**Comment by rgommers** [comment]
With `clang 9.0.0` and the Accelerate version that ships with macOS 10.13, all tests pass. Cannot reproduce this anymore. Let's close this, can always be reopened in case someone else runs into it. Most people upgrade macOS though to the latest version when available, so won't be common.
