### ISSUE TITLE
TST: Clean up "ignore" warnings

### ISSUE THREAD

**Issue by seberg** [scipy/scipy#7524]
gh-5796 has a start (and example) for avoiding "ignore" warning filters, especially in the test suit. They are problematic due to a python issue (actually limited to python <3.4 or so), which means that ignoring them in one test, can sometimes lead to ignoring them in other places as well. Which is mostly annoying if you want to test for the same warning elsewhere (one thing where it bit me in numpy especially was `DeprecationWarnings`).

This is pretty straight forward, look at what gh-5796 does, then:

 1. Check for ignores, for example with `git grep "warn.*ignore"`
 2. Choose some file, and remove the filters (if you want, you can do the testing step here, to make sure they were actually needed, but sometimes it is system dependend
 3. Run the test suit  (EDIT: Warnings should now be errors in development versions, so nothing special needed).
 4. Clean up any new errors, new errors are not untypical, at least on python 2 (on python 3.5 or so I am not quite sure, maybe here they are already printed and will show up in 3. from the start).
     * I would suggest to try to be more specific then what they where, i.e. do not just use `DeprecationWarning`, add a bit of the warning message, so that one realizes new deprecation warnings affecting the same test (EDIT: Plus it might allow grepping for it in the future, etc.)
 5. Start again from 1. :)

Once scipy is all clean, I have a code test in numpy (that were based on some scipy stuff I think), to check that no new "ignore" filters are added. You could do similar things here.

**Comment by rgommers** [comment]
Thanks @seberg!

**Comment by rgommers** [comment]
Labelled as easy-fix because it is indeed a straightforward task. It's quite a large one, but no need to tackle all of SciPy at once: if you want to do just one file or module, that'd be very welcome too.

**Comment by seberg** [comment]
Ooops, this should not have been closed.

**Comment by seberg** [comment]
OK, so this is all done within tests. There are still two in signaltools (which I have a PR open to remove), and one in `optimize/optimize.py` which looks like it could be avoided with a small code refactor. The benchmarks do not matter.

Adding a test is still a good idea probably.

**Comment by seberg** [comment]
While the optimize thing can be avoided with a small refactor probably, frankly I am too confused as to when the warning is supposed to be given at all to actually try it myself right now.

**Comment by Tejaswgupta** [comment]
Does this still need contribution?
if yes, then would be wiling to help.

**Comment by seberg** [comment]
Doubt it is still very relevant with Python 2.7 being end of life, so I will close this.

In general, changing the filters in library code is still often not good, because warning filtering is not thread-safe (it should be fine in testing). So that is still something that you could have a look at.
