### ISSUE TITLE
spatial.Voronoi does not properly deallocate memory

### ISSUE THREAD

**Issue by tverho** [scipy/scipy#7530]
Running Voronoi with a large number of points will use a lot of memory, and only a part of it seems to become available when all python objects are removed. In the following example the algorithm will use ~1.7GB of memory, and almost 1GB will remain used after the voronoi object is removed.

### Reproducing code example:
```
import numpy as np
import scipy.spatial
import psutil

p = psutil.Process()
X = np.random.random((1000000, 2))
print(p.memory_info())
vor = scipy.spatial.Voronoi(X)
print(p.memory_info())
del vor
print(p.memory_info())
```
### Output:
```
pmem(rss=73945088, vms=500535296, shared=24264704, text=4116480, lib=0, data=194260992, dirty=0)
pmem(rss=1717280768, vms=2145259520, shared=24653824, text=4116480, lib=0, data=1838985216, dirty=0)
pmem(rss=943403008, vms=1369575424, shared=24653824, text=4116480, lib=0, data=1063301120, dirty=0)
```

### Scipy/Numpy/Python version information:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
If you run that in a `while True:` loop, you can see that the memory 
usage does not grow in time.
.
This can mean two things: the C allocator cannot return the memory to 
the system in this case. In particular, it is not guaranteed that a 
process returns freed memory back to the system.
.
Alternatively, the internal allocator of qhull does not release the 
memory, although it's supposed to.

**Comment by pv** [comment]
I don't think qhull has global state that would be shared across 
while:True loops, so if it was qhull allocator issue, it would show up 
as a real memory leak.
.
So it's probably just normal behavior of libc allocator. You probably 
get the same issue if replacing `vor = scipy.spatial.Voronoi(X)` with
```
vor = []
for j in range(50000):
     vor.append(np.random.rand(1000))
```

**Comment by tverho** [comment]
You seem to be right. Numpy appears to sometimes keep the memory reserved even if it's no longer used. So no fault in the Qhull code.
