### ISSUE TITLE
BUG: scipy.sparse.csc_matrix: matrix multiplication with nan

### ISSUE THREAD

**Issue by jor-** [scipy/scipy#7532]
At the matrix multiplication with `scipy.sparse.csc_matrix` matrices, `nan * 0` results in `0` and not in `nan` as in the dense case.

Look at this short example:
```
A = scipy.sparse.csc_matrix([[np.nan, 1], [2, 3]])
B = scipy.sparse.csc_matrix([[0, 0], [0, 1]])
```
Here
```
(A @ B).todense()
```
results in 
```
matrix([[ 0.,  1.],
        [ 0.,  3.]])
```
and
```
A.todense() @ B.todense()
```
results in 
```
matrix([[ nan,  nan],
        [  0.,   3.]])
```
I used SciPy 0.19.1 with Python 3.6.

Maybe other sparse matrix formats like for example ``csr_matrix`` are also affected

**Comment by perimosocordiae** [comment]
This is a side-effect of the efficient sparse multiplication routine. Remember that the zeros in B are structural zeros, so we are assuming <anything> * <zero> = 0.

Breaking down the 2x2 matrix multiply and noting the structural zeros with <zero>, we get:
```
C = A @ B
C[0,0] = sum(A[0] * B[:,0]) = sum(<nonzeros> * <zeros>) = <zero>
C[0,1] = sum(A[0] * B[:,1]) = nan * <zero> + 1 * 1 = 1
C[1,0] = sum(A[1] * B[:,0]) = sum(<nonzeros> * <zeros>) = <zero>
C[1,1] = sum(A[1] * B[:,1]) = 2 * <zero> + 3 * 1 = 3
```

**Comment by jor-** [comment]
Thank you for the quick explanation. So this behaviour is desired? Then this issue can be closed.

**Comment by perimosocordiae** [comment]
If you do need the full NaN-propagated result without multiplying dense matrices, it's pretty easy to compute which rows/columns of the result need to be NaN: any NaN in A makes a corresponding all-NaN row in C, and likewise for NaNs in B making the corresponding column of C all NaN. This is likely to destroy the sparsity of C, however, so you'd probably want to densify C first.
