### ISSUE TITLE
Q: Why doesn't von mises distributions wrap around [-pi, pi]?

### ISSUE THREAD

**Issue by kingjr** [scipy/scipy#7533]
I am trying to get a Von Mises probability density function whose mean is set parametrically (The ultimate aim is to build a kernel density estimation).

It seems that scipy's Von Mises pdf does not wrap around [pi, pi] if `loc` is different from 0. E.g.

```python
import matplotlib.pyplot as plt
from scipy.stats import vonmises
x = np.linspace(-np.pi, np.pi)
mean = 2.  # abritrary mean parameter
y = vonmises(kappa=1., loc=mean).pdf(x)
plt.plot(x, y)
```

![image](https://user-images.githubusercontent.com/4881164/27591182-363220f0-5b51-11e7-94a9-7c93f537ce4e.png)

Is this expected? If so, how I can retrieve the pdf that wraps in the expected range [-pi, pi]?

Thanks
cc @ev-br

**Comment by rgommers** [comment]
Looks like this is the same issue or at least related to gh-4598.

**Comment by rgommers** [comment]
A structural solution is needed, likely the ``rv_circular`` class discussed at https://github.com/scipy/scipy/issues/4598#issuecomment-206548297

**Comment by rgommers** [comment]
That issue does have some discussion on how to fix your problem manually, can you have a look at that?

**Comment by kingjr** [comment]
You're right, it's a duplicate. 

However, I didn't understand the possibles fixes, so I just re-implemented the equation with numpy:

```python
from scipy.special import i0
vonmises = lambda x, mu, kappa: np.exp(kappa*np.cos(x-mu))/(2*np.pi*i0(kappa))
```

**Comment by Eric89GXL** [comment]
Closing as dup, thanks for looking into it @kingjr
