### ISSUE TITLE
boxcox fails unpredictably

### ISSUE THREAD

**Issue by trvrm** [scipy/scipy#7534]
`scipy.stats.boxcox` fails on some arrays, whilst succeeding on very similar ones.

### Reproducing code example:
```
from scipy.stats import boxcox

# This works fine:
print(boxcox([198, 233, 333, 391]))

# This nearly identical list causes boxcox to give divide-by-zero warnings, 
# It returns a completely different value for `lmbda` than the previous example
# The list it returns contains four identical values, which can't be right.
print(boxcox([198, 233, 333, 392]))

```

### Error message:
```
(array([ 5.46270445,  5.63650356,  6.01901337,  6.19154588]), 0.01220805659774476)
/usr/local/lib/python3.5/dist-packages/scipy/stats/morestats.py:901: RuntimeWarning: divide by zero encountered in log
  llf -= N / 2.0 * np.log(np.sum((y - y_mean)**2. / N, axis=0))
/usr/local/lib/python3.5/dist-packages/scipy/optimize/optimize.py:2189: RuntimeWarning: invalid value encountered in double_scalars
  w = xb - ((xb - xc) * tmp2 - (xb - xa) * tmp1) / denom
/usr/local/lib/python3.5/dist-packages/scipy/optimize/optimize.py:1849: RuntimeWarning: invalid value encountered in double_scalars
  tmp1 = (x - w) * (fx - fv)
/usr/local/lib/python3.5/dist-packages/scipy/optimize/optimize.py:1850: RuntimeWarning: invalid value encountered in double_scalars
  tmp2 = (x - v) * (fx - fw)
/usr/local/lib/python3.5/dist-packages/scipy/optimize/optimize.py:1855: RuntimeWarning: invalid value encountered in absolute
  tmp2 = numpy.abs(tmp2)
```

### Scipy/Numpy/Python version information:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=5, micro=3, releaselevel='final', serial=0)

```

**Comment by rgommers** [comment]
Hmm, looks bad. Getting a traceback with

    with np.errstate(invalid='raise'):
        x = [198, 233, 333, 392]
        print(stats.boxcox(x))

gives

    Traceback (most recent call last):
      File "tmp.py", line 13, in <module>
        print(stats.boxcox(x))
      File "/home/rgommers/Code/scipy/scipy/stats/morestats.py", line 1043, in boxcox
        lmax = boxcox_normmax(x, method='mle')
      File "/home/rgommers/Code/scipy/scipy/stats/morestats.py", line 1157, in boxcox_normmax
        return optimfunc(x, brack)
      File "/home/rgommers/Code/scipy/scipy/stats/morestats.py", line 1142, in _mle
        return optimize.brent(_eval_mle, brack=brack, args=(x,))
      File "/home/rgommers/Code/scipy/scipy/optimize/optimize.py", line 2050, in brent
        res = _minimize_scalar_brent(func, brack, args, **options)
      File "/home/rgommers/Code/scipy/scipy/optimize/optimize.py", line 2082, in _minimize_scalar_brent
        brent.optimize()
      File "/home/rgommers/Code/scipy/scipy/optimize/optimize.py", line 1888, in optimize
        xa, xb, xc, fa, fb, fc, funcalls = self.get_bracket_info()
      File "/home/rgommers/Code/scipy/scipy/optimize/optimize.py", line 1865, in get_bracket_info
        xb=brack[1], args=args)
      File "/home/rgommers/Code/scipy/scipy/optimize/optimize.py", line 2251, in bracket
        fc = func(*((xc,) + args))
      File "/home/rgommers/Code/scipy/scipy/stats/morestats.py", line 1140, in _eval_mle
        return -boxcox_llf(lmb, data)
      File "/home/rgommers/Code/scipy/scipy/stats/morestats.py", line 902, in boxcox_llf
        llf -= N / 2.0 * np.log(np.sum((y - y_mean)**2. / N, axis=0))
    FloatingPointError: divide by zero encountered in log

Somewhere in the scalar minimization with ``optimize.brent`` the Box-Cox parameter ``lmbda`` becomes large negative, when the crash happens it's ~-8. Not clear why. 4 samples may not be enough to do something reasonable.

**Comment by trvrm** [comment]
I can provide examples with more samples if it would help.

E.g.

`boxcox([198, 227, 233, 235, 271, 331, 333, 333, 333, 342, 359, 369, 378, 387, 404, 556])`

fails, whereas the nearly identical

`boxcox([198, 227, 233, 235, 271, 331, 333, 333, 333, 342, 359, 369, 378, 387, 404, 555])`

succeeds.

Unfortunately I don't know enough about the algorithm or the implementation to be able to help much more at this point.

**Comment by rgommers** [comment]
@trvrm thanks, that's helpful.

Looks like this issue will require a serious debugging session. I don't have the time to dig in more now, so if anyone feels like puzzling - go for it!

**Comment by WarrenWeckesser** [comment]
@trvm Thanks for reporting the problem.  The same problems was reported in https://github.com/scipy/scipy/issues/6873, so I'm closing this issus as a duplicate.
