### ISSUE TITLE
DOC: stats tutorials Gamma vs gamma 

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#7540]
Many of the stats tutorials report the distribution's CDF using `\Gamma(s, x)` and I'm wondering if `\gamma(s,x)` is in fact what was meant?

[The lowercase gamma is the "lower incomplete gamma function" `\gamma(s, x) = \int_0^x t^{s-1} exp(-t) dt`, the uppercase is the "upper incomplete gamma function" `\Gamma(s, x) = \int_x^\infty t^{s-1} exp(-t) dt`and they are related by `\gamma(s, x) + \Gamma(s, x) = \Gamma(s) = (s-1)!`.
As `x -> \infty`, `\Gamma(s, x) -> 0`, and `\gamma(s, x) -> \Gamma(s)`. E.g. https://en.wikipedia.org/wiki/Incomplete_gamma_function]

Question: The tutorials for chi-squared, gamma, dgamma, gengamma, loggamma, nakagami all use `\Gamma(s, x)` when I would have expected `\gamma(s, x)`.  Is this just due to a different definition for `\Gamma(s, x)`? Or should they all be the lower incomplete gamma function `\gamma(s, x)`?

Examples:
The Gamma distribution https://docs.scipy.org/doc/scipy/reference/tutorial/stats/continuous_gamma.html lists the CDF as 
`\Gamma(a, x)`.  Except that this function goes to 0 as `x -> \infty`.  [It also hasn't been normalized - it needs to be divided by `\Gamma(a)`.]

The Generalized Gamma distribution https://docs.scipy.org/doc/scipy/reference/tutorial/stats/continuous_gengamma.html lists the CDF as 
`\Gamma(a, x^c)` for c>0.  Again this function goes to 0 as `x -> \infty`.
For c<0, the listed CDF is `1-\Gamma(a, x^c)/\Gamma(a)`, which goes to 0 as `x -> \infty`.  
[This also disagrees with the CDF for the Inverted Gamma distribution https://docs.scipy.org/doc/scipy/reference/tutorial/stats/continuous_invgamma.html, which is the special case c=-1 of gen gamma.  There the CDF is listed as 
`\Gamma(a, x^c)/\Gamma(a)` and this actually has the correct behavior as `x -> \infty`.]

I did find some usage of `\gamma`, the gennorm distribution uses it (correctly), so both \gamma and \Gamma do appear in the tutorials.

[One side note, the tutorials often use symbols for functions without defining them, and the meaning is not always obvious from the context.]
 
### Scipy/Numpy/Python version information:
```
1.0.0.dev0+e5a0cd7 1.14.0.dev0+d93a5dd sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```
<img width="528" alt="gammagamma" src="https://user-images.githubusercontent.com/23403152/27695136-0fdbae3c-5cbc-11e7-8a88-25d78de03f95.png">

**Comment by rgommers** [comment]
I strongly suspect that these are mistakes, and not due to a different definition. 

May be due to "the gamma function" being ``\Gamma(s)``, so if one is not aware of the differences between the two incomplete gamma functions, writing it capitalized makes sense.

> One side note, the tutorials often use symbols for functions without defining them, and the meaning is not always obvious from the context.

Indeed. And it's often quite a bit of work to match the ``scipy.stats`` formulations with what one finds on Wikipedia for example. The way ``loc`` and ``scale`` works is powerful, but doesn't help when trying to match things up.

I guess just due to historical reasons and fixing this stuff being a lot of work. The docs have improved immensely over the past 5 years, but SciPy is a big beast....

**Comment by pvanmulbregt** [comment]
I noticed that recent addition http://scipy.github.io/devdocs/tutorial/stats/continuous_gennorm.html 
 has more structure than the previous tutorials files (perhaps because due to other's genesis as a single file with all distributions being later split into one file per distribution.)  The use of "Functions", "Moments", "Special Cases" and "Sources" helped me understand why other docs had the multiple :math: blocks with different alignments - they were the same blocks as in gennorm, just without the block labels.
Would an effort to standardize the format of the tutorial docs along those lines be welcome? Along with any corrections discovered along the way.  Perhaps even a single place for the definition of the all the notation for the special functions used multiple times (incomplete gamma/Gamma, incomplete beta, modified bessel, digamma/polygamma, ,...) to save repeating every place of use?

**Comment by josef-pkt** [comment]
Iwonder whether upper case, lower case distinction is anythin standard. I didn't know about upper incomplete gamma and remember only seeing upper case gamma for lower incomplete gamma in applied papers. 
For some of the distributions the notation depends on the reference which at least in some cases is not always the same, AFAIR.

I think any improvement and correction of formatting would be welcome given that most of the distributions tutorial descriptions were never individually checked after auto conversion.

**Comment by pvanmulbregt** [comment]
I did a quick search for lower and upper case gamma.
1. Whittaker & Watson's "A course of modern analysis"   https://www.archive.org/stream/courseofmodernan00whit?ref=ol#page/340/mode/2up/search/incomplete+gamma  uses `\gamma` for the lower incomplete gamma function, but they don't define upper-case `\Gamma`.
2. Abramowitz & Stegun define `\gamma` as the lower incomplete gamma function, `\Gamma` as the upper incomplete gamma function, `P(a, z)= \gamma(a, z) / \Gamma(a)` to be the regularized lower incomplete gamma function, and `\gamma*(a, x) = P(a, x)/x^a` (useful in some situations as no singularities)
3. Wolfram Mathworld has the Regularized Gamma Function P(a, z).
4. MATLAB has a single function `gammainc` with 3 arguments
`Y = gammainc(X, A, 'lower' | 'upper' )`, 'lower' being the default, but the function is actually the regularized incomplete gamma `P(a, z)`.

5. scipy  https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.gammainc.html  partly avoids the issue by explicitly listing the integrals but not using the terms  `\Gamma` or `\gamma`.  Though the reference given is Maddock et. al., “Incomplete Gamma Functions”, http://www.boost.org/doc/libs/1_61_0/libs/math/doc/html/math_toolkit/sf_gamma/igamma.html which uses `\gamma` for lower incomplete and `\Gamma` for upper incomplete.

On the other hand, 
6. the Gnu Scientific Library has `gsl_sf_gamma_inc(a, x)` and the documentation:

> "These functions compute the unnormalized incomplete Gamma Function \Gamma(a,x) = \int_x^\infty dt t^{(a-1)} \exp(-t) for a real and x \ge 0."

and `gsl_sf_gamma_inc_P(a, x)` with doc

> "These routines compute the complementary normalized incomplete Gamma Function P(a,x) = 1 - Q(a,x) = 1/\Gamma(a) \int_0^x dt t^{(a-1)} \exp(-t) for a > 0, x \ge 0.
> Note that Abramowitz & Stegun call P(a,x) the incomplete gamma function (section 6.5)."

GSL doesn't use `\gamma(a, x)`, only `\Gamma(a,x)`, and it uses `\Gamma(a,x)` in the opposite sense of Abramowitz and Stegun, even though it is the main reference for GSL's special functions.



`P(a, x)` is the function that is most useful in these stats tutorial pages, but notation doesn't seem widespread.  Defining `\Gamma(a, x)` as the upper incomplete gamma function seems the more common definition, but it is not universal.

Perhaps the approach to take is to use the same definitions in the stats tutorials as used in scipy's special functions reference and be very explicit about the source to avoid any confusion.

**Comment by ev-br** [comment]
> Perhaps the approach to take is to use the same definitions in the stats tutorials as used in scipy's special functions reference and be very explicit about the source to avoid any confusion.

+1
That would be truly great

**Comment by mdhaber** [comment]
This appears to have been fixed in gh-9953; this issue just wasn't referenced.

> Perhaps even a single place for the definition of the all the notation for the special functions used multiple times (incomplete gamma/Gamma, incomplete beta, modified bessel, digamma/polygamma, ,...) to save repeating every place of use?

Now:
![image](https://user-images.githubusercontent.com/6570539/162645766-b5b54c4f-d046-45e0-9799-58c0647d318d.png)

> The tutorials for chi-squared, gamma, dgamma, gengamma, loggamma, nakagami all use \Gamma(s, x) when I would have expected \gamma(s, x)

For chi-squared:
![image](https://user-images.githubusercontent.com/6570539/162645886-b3c7ab3d-7977-4c31-a597-553a8335cb8b.png)
![image](https://user-images.githubusercontent.com/6570539/162646002-c1587717-414c-4367-979c-41894c2d7284.png)

which is the same as Wikipedia:
![image](https://user-images.githubusercontent.com/6570539/162645866-029bedb5-fc62-4acc-9aba-6cd32f391378.png)

and all the others mentioned both have `\gamma` and `\Gamma` now (presumably because these are the regularized lower gamma function).

Closing, but LMK if I've missed something @pvanmulbregt.
