### ISSUE TITLE
DOC: stats tutorials: Questions on arcsine and Student t formulae

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#7542]
Some stats tutorials use terms whose meaning is not immediately obvious. 

Q1: Arcsine distribution: (http://scipy.github.io/devdocs/tutorial/stats/continuous_arcsine.html) 
The moment generating function is listed as 
M(t)=E^{t/2}I_{0}(\frac{t}{2})  

 ![arcsine mgf](https://user-images.githubusercontent.com/23403152/27738509-831f140c-5d79-11e7-9b17-a3d40b6e2eb3.png)
What is this supposed to mean? 
It differs quite a lot in form from the Wikipedia MGF (https://en.wikipedia.org/wiki/Arcsine_distribution)

Q2: Student t distribution. (http://scipy.github.io/devdocs/tutorial/stats/continuous_t.html )
The entropy for the Student t distribution uses the symbol `c` which isn't defined in the page.  
![studentt entropy](https://user-images.githubusercontent.com/23403152/27738529-92c44ddc-5d79-11e7-90ae-416e3655831b.png)
Perhaps it is meant to be `\nu`?  If so, it bears some similarity to the Entropy on the Wikipedia page (https://en.wikipedia.org/wiki/Student%27s_t-distribution) but isn't obviously reconcilable with it.  Is there a (online) reference for this formula? 

### Scipy/Numpy/Python version information:
```1.0.0.dev0+e5a0cd7 1.14.0.dev0+d93a5dd sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)```

**Comment by rgommers** [comment]
Re ``arcsine``: no idea, that comes out of nowhere. It refers to "JKB definition", which I'd guess is a book. The abbreviation is used in five tutorial pages, but I can't find what it refers to. The answer may be in there. 

Probably a good idea to just update the formula to the one from Wikipedia - I can find that definition in various other places, and the ``arcsine`` implementation for all implemented methods is clearly in line with Wikipedia.

**Comment by rgommers** [comment]
Re ``t``: trying to figure that one out just gave me a headache. Again the formula has very little to do with the implementation, there's no ``_entropy`` method and no ``c`` parameters. 

Also suggest just bringing in line with Wikipedia.

**Comment by pvanmulbregt** [comment]
The following entry occurs in the References section of http://scipy.github.io/devdocs/tutorial/stats/continuous.html

> Norman Johnson, Samuel Kotz, and N. Balakrishnan Continuous Univariate Distributions, second edition, Volumes I and II, Wiley & Sons, 1994

and I'd guess that "JKB" refers to those two volumes.
