### ISSUE TITLE
DOC: signal tutorial: Typo in explanation of convolution

### ISSUE THREAD

**Issue by fridewald** [scipy/scipy#7550]
In the section for convolution it says, that you have to limit both sequences that are convoluted. 
The sequence is set `y[n] = 0` for `n>K+1` and `x[n]=0` is set for `n>M+1`.

But shouldn't it be `x[n] = 0` for `n>K+1` and `h[n]=0` for `n>M+1`?

I also wonder if the greater symbol is right here.
Isn't a greater equal symbol right here, as the sequence would otherwise be `K+2(M+2)` elements long?

**Comment by Eric89GXL** [comment]
> But shouldn't it be x[n] = 0 for n>K+1 and h[n]=0 for n>M+1?

Yes I agree it should be `h` not `y`.

> I also wonder if the greater symbol is right here.

Yeah greater-equal would be good, or just `n > K` and `n > M`.

Do you have time to make a PR?
