### ISSUE TITLE
Error in scipy.signal.periodogram example

### ISSUE THREAD

**Issue by thuehlinger** [scipy/scipy#7557]
The example code for sciipy.signal.periodogram at https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.signal.periodogram.html contains an error:

According to the text
```
>>> np.mean(Pxx_den[256:])
0.0018156616014838548
```
Should return the noise power of the signal, i.e. 0.001. This is not the case because in ```Pxx_den[256:]``` the signal peak at 1234 Hz is included. Correctly, the statement should be something like

```
>>> np.mean(Pxx_den[10000:])
0.00099830549215597321
```

### Reproducing code example:
```
np.mean(Pxx_den[256:])
```

### Scipy/Numpy/Python version information:
```
('0.18.1', '1.11.3', sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0))
```

**Comment by Eric89GXL** [comment]
Do you have time to make a PR @thuehlinger?

**Comment by rgommers** [comment]
The suggested ``np.mean(Pxx_den[10000:])`` converges to 0.002 not 0.001 (both for me locally and in gh-7557). So a factor 2 is missing in the explanation.

**Comment by rgommers** [comment]
fixed by gh-7610
