### ISSUE TITLE
Should RegularGridInterpolator support length 1 dimensions?

### ISSUE THREAD

**Issue by RutgerK** [scipy/scipy#7560]
The documentation for the [RegularGridInterpolator](https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.interpolate.RegularGridInterpolator.html) states that if the `bounds_error` is set to False the `fill_value` is used. And if the `fill_value` is None, the values are extrapolated. 

However, in the case of a dimensions with length 1, this doesn't seem to apply. Interpolating and extrapolating with 1 value is certainly an edge case. But based on the documentation i would expect (correct me if i'm wrong), that extrapolating or interpolating with 1 value will yield that same value. 

The current implementation results in `nan` values. The difficulty is that if you cant be sure that all data dimensions are n>1, you have to check this and slice out those dimensions, and change the call to the `Interpolator` to exclude those parameters.

### Reproducing code example:
This doesnt work:
```python
from scipy.interpolate import RegularGridInterpolator
import numpy as np

def f(x,y):    
    return (y+1) * x

x = np.array([0, 5., 10])
y = np.array([0.])

data = f(*np.meshgrid(x,y, indexing='ij', sparse=True))
# data = array([[  0.], [  5.], [ 10.]])

my_interp = RegularGridInterpolator((x, y), data, fill_value=None, bounds_error=False)
my_interp((5.0, 0.))

output[4]: array(nan)
```
But adding a value to `y` makes it work:
```python
y = np.array([0., 1.0])

data = f(*np.meshgrid(x,y, indexing='ij', sparse=True))
# data = array([[  0.,   0.], [  5.,  10.], [ 10.,  20.]])

my_interp = RegularGridInterpolator((x, y), data, fill_value=None, bounds_error=False)
my_interp([5.0, 0.])

output[5]: array([ 5.])
``` 

### Error message:
```
C:\Miniconda3\envs\py36\lib\site-packages\scipy\interpolate\interpolate.py:2467: RuntimeWarning: invalid value encountered in true_divide
  (grid[i + 1] - grid[i]))
```

### Scipy/Numpy/Python version information:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
The function should extrapolate, but it doesn't say how in the docs. I'm guessing linear extrapolation from a quick browse of the code, which doesn't work with 1 value. Could clarify this in the docs, or make it use constant extrapolation.
