### ISSUE TITLE
Randomized algorithms for partial matrix factorizations

### ISSUE THREAD

**Issue by dseuss** [scipy/scipy#7561]
For my own work, I had to implement a partial singular value and a partial eigenvalue decomposition using the randomized algorithms from [1] [here](https://github.com/dseuss/pyscgm/blob/master/pyscgm/linalg.py). The interfaces are very similar to the existing `svds` and `eigsh` functions in `scipy.sparse.linalg`. I haven't compared them in detail to the existing work, but my feeling is that they might be faster if the desired precision is not too high. 

My question is if there is any interest in adding these functions to scipy -- I would be willing to create a pull request and maybe add some more features (e.g. specialists faster strategies for dense matrices or higher precision for the eigenvalue decomposition of a positive semidefinite matrix. 

Note that some of these strategies are available in a different [package](https://github.com/facebook/fbpca), which doesn't abide to the scipy interface.

[1]  Halko, N., Martinsson, P.-G., & TroJ. A. (2009). Finding structure with randomness: Probabilistic algorithms for constructing approximate matrix decompositions.

**Comment by rgommers** [comment]
Hi @dseuss, thanks for asking. I suggest asking on the scipy-dev mailing list to reach a broader audience, since this is a quite specialized topic.

**Comment by rgommers** [comment]
we have some randomized algorithms in `linalg/_sketches.py` and `linalg.interpolative`. No further follow-up, so closing.
