### ISSUE TITLE
pdist and sparse matrices

### ISSUE THREAD

**Issue by urigoren** [scipy/scipy#7565]
pdist seem not to work on sparse matrices.
If this is by-design, the error message should be informative.

I personally, see no reason why pdist wouldn't work (at least for certain metrics) on sparce matrices/

See StackOverflow question here:
https://stackoverflow.com/questions/44936494/pairwise-distance-fails-on-a-sparse-matrix-with-an-uninformative-error-message/44936719#44936719

### Reproducing code example:
```
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from scipy.spatial import distance

X = CountVectorizer().fit_transform(docs)
X = TfidfTransformer(use_idf=False).fit_transform(X)
print (X.shape) #prints (100, 1760)
distance.pdist(X, metric='cosine')
```

### Error message:
```
ValueError: A 2-dimensional array must be passed.
```

### Scipy/Numpy/Python version information:
```
0.18.0 1.11.1 sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
```

**Comment by sethtroisi** [comment]
#7566 fixes this

```
from scipy.spatial import distance
from scipy import sparse

X = scipy.sparse.random(100, 1760)
print (X.shape) #prints (100, 1760)
distance.pdist(X, metric='cosine')
```
Now prints
`ValueError: Sparse matrices are not supported by this function. Perhaps one of the scipy.sparse.linalg functions would work instead.`
