### ISSUE TITLE
The dependence to LAPACK/BLAS headers should be referenced

### ISSUE THREAD

**Issue by HorlogeSkynet** [scipy/scipy#7579]
Hey,

I was trying to compile SciPy from scratch, but for whose are running Debian / Ubuntu, it looks like we have to install `liblapack-dev` and `libblas-dev` packages.
Should this not be referenced within the _HACKING.rst_'s guiding instructions ? 🤔

### Reproducing code example:
```
$ git clone git@github.com:YOURUSERNAME/scipy.git scipy
$ cd scipy
$ git remote add upstream git://github.com/scipy/scipy.git
$ pip3 install Numpy Cython Nose
$ python3 runtests.py -v
```

### Error message:
```
numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
```

Thanks bye 👋

**Comment by rgommers** [comment]
Hi @HorlogeSkynet, ``HACKING.rst`` is about contributing not building. We have detailed build instructions, and the dev headers you mention are documented: https://scipy.org/scipylib/building/linux.html#installation-from-source

**Comment by HorlogeSkynet** [comment]
Oh okay I didn't know this very page was available, thank you.
But, as there are several `HACKING.rst`'s sections about building a development environment, would it not be nice anyway to reference this documentation page you pointed out ?

Thx

**Comment by rgommers** [comment]
Fair comment, added link in gh-7586
