### ISSUE TITLE
Introduction on SLSQP method?

### ISSUE THREAD

**Issue by cqcn1991** [scipy/scipy#7585]
Hi, I'm not sure if this is the right place to ask. My master thesis (https://github.com/cqcn1991/Wind-Speed-Analysis), uses the SLSQP method [1-2] for optimization. And I want to give it a brief introduction on my paper. However, I don't have access to the original work of Dieter Kraft. 

I want to know where can I see a brief introduction of this method? i.e., its algorithim. 

[1] https://github.com/scipy/scipy/blob/master/scipy/optimize/slsqp.py
[2] https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fmin_slsqp.html

**Comment by pv** [comment]
If you cannot find a copy of Kraft's paper (which apparently is not easy 
to get hold of), you can read the Fortran source code under 
scipy/optimize/slsqp/

**Comment by cqcn1991** [comment]
@pv I'm reading it writing now, but I feel it's a bit of too detailed? I'm wondering ff there is something simpler or higher level? Something like the introduction we read on Wikipedia for describing normal distribution.

**Comment by rgommers** [comment]
@cqcn1991 apparently no one has a better reference at hand, so I'm closing this issue. If you end up finding one, would be nice if you could put a link here for the next people looking for it.

**Comment by rangelonline** [comment]
@cqcn1991 did you ever find any more documentation on SLSQP? I stumbled across it and am really satisfied but I hate using it as a black box and I'd like to at least have a high-level understanding. If you weren't able to find anything more, would you mind sharing the high-level explanation you said you'd put together? 

Thanks in advance!

**Comment by cqcn1991** [comment]
@rangelonline I don't have good understanding of it either.

**Comment by egor-bogomolov** [comment]
If someone wants to find the original work by Kraft, it seems to be available [here](http://degenerateconic.com/wp-content/uploads/2018/03/DFVLR_FB_88_28.pdf)
