### ISSUE TITLE
stats.truncnorm.rvs samples incorrect values

### ISSUE THREAD

**Issue by lynochka** [scipy/scipy#7591]
Hi, truncated normal distribution samples incorrect values.

### Reproducing code example:

```
from scipy import stats
print stats.truncnorm.rvs(-0.52,-0.25, scale = 0.19, loc = -0.14)
# which falls outside of the (-0.52,-0.25) interval
```

### Error message:
```
No error message.
```

### Scipy/Numpy/Python version information:

```
('0.18.1', '1.12.0', sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0))
```

**Comment by jaimefrio** [comment]
Thanks for reporting!

I think you have overlooked this comment in [the documentation](https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.stats.truncnorm.html):

>The standard form of this distribution is a standard normal truncated to the range [a, b] — notice that a and b are defined over the domain of the standard normal. To convert clip values for a specific mean and standard deviation, use:
> ```a, b = (myclip_a - my_mean) / my_std, (myclip_b - my_mean) / my_std```

You can check yourself it works:

```
import numpy as np
from scipy import stats

mu, sigma = -0.14, 0.19
a, b = (-0.52 - mu) / sigma, (-0.25 - mu) / sigma
values = stats.truncnorm.rvs(a, b, scale=sigma, loc=mu, size=1000)
assert np.all(values >= -0.52)
assert np.all(values <= -0.25)
```

I'm going to close the issue, but feel free to reopen or comment if anything is unclear.

**Comment by lynochka** [comment]
Hi  jaimefrio,

I believe the definition of stats.truncnormal is unfortunate and should be changed. Compared to the classic packages in R such as https://cran.r-project.org/web/packages/truncnorm/truncnorm.pdf, adjusting values a and b is confusing.

Regards,
Alina

**Comment by jaimefrio** [comment]
While I understand your frustration, there typically is a strict backwards compatibility policy: we don't change existing APIs, because there may be users depending on the existing behavior. The fact that the behavior is explicitly documented makes me think that is the most likely outcome, but I'm no expert on this particular module, maybe @josef-pkt has a more informed opinion on this particular issue.

In any case, if such a change was to be made, it would require discussion on [the mailing list](https://www.scipy.org/scipylib/mailing-lists.html), since that's read by many more people in the community than this issue tracker. Can you write an e-mail to scipy-dev explaining your issues with trucnorm?

**Comment by josef-pkt** [comment]
The "problem" is that this behavior is coming from the design of the continuous distributions as loc-scale families. So this is a "feature" that makes the parameterization of a few distribution non-standard, e.g. log-normal, and distribution where the support depends on parameters shifts with loc and scale.

There is no generic way out of this, the only option would be to explicitly add distributions with parameterization that don't follow the loc-scale pattern. But there is currently no structure for this, e.g. class hierarchy with methods that are be inherited are all defined for loc-scale parameterization.

loc, scale families are theoretically and computationally nice because they all have the same affine transformation, although that is not the common parameterization for several cases.
The strategy so far has been to provide better documentation, so that it should be easy for users to switch to the loc-scale parameterization.

**Comment by josef-pkt** [comment]
There is a python package (I don't remember the name right now) that wraps some of the scipy.stats.distributions to provide the more standard, commonly used parameterization.

**Comment by rgommers** [comment]
https://pymc-devs.github.io/pymc3/api/distributions.html ?

**Comment by ev-br** [comment]
https://github.com/phobson/paramnormal

**Comment by ZhaoQii** [comment]
Hi,

Seems an old topic but I just met with some weird behaviors of truncnorm.rvs:

Given my loc = 33, scale = 1, if I want myclip_a = -np.infty and myclip_b = 30, I run
`sp.stats.truncnorm.rvs(loc = 33, scale = 1, a = -np.infty, b = -3)`
and this works;

If I want myclip_b = 10 instead, I run
`sp.stats.truncnorm.rvs(loc = 33, scale = 1, a = -np.infty, b = -23)`
this also works;

But if I want myclip_b = 20, the same code doesn't work anymore
`sp.stats.truncnorm.rvs(loc = 33, scale = 1, a = -np.infty, b = -13)`

and the error message:
`---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-96-2a5578e47036> in <module>
----> 1 sp.stats.truncnorm.rvs(loc = 33, scale = 1, a = -np.infty, b = -13)

~/opt/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py in rvs(self, *args, **kwds)
    978         # by _rvs().
    979         self._size = size
--> 980         vals = self._rvs(*args)
    981 
    982         vals = vals * scale + loc

~/opt/anaconda3/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py in _rvs(self, *args)
    911         ## Use basic inverse cdf algorithm for RV generation as default.
    912         U = self._random_state.random_sample(self._size)
--> 913         Y = self._ppf(U, *args)
    914         return Y
    915 

~/opt/anaconda3/lib/python3.7/site-packages/scipy/stats/_continuous_distns.py in _ppf(self, q, a, b)
   7161 
   7162     def _ppf(self, q, a, b):
-> 7163         return _truncnorm_ppf(q, a, b)
   7164 
   7165     def _munp(self, n, a, b):

~/opt/anaconda3/lib/python3.7/site-packages/scipy/stats/_continuous_distns.py in vf_wrapper(*args)
   6931         @functools.wraps(f)
   6932         def vf_wrapper(*args):
-> 6933             return vf(*args)
   6934         return vf_wrapper
   6935     return vectorize_decorator

~/opt/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py in __call__(self, *args, **kwargs)
   2089             vargs.extend([kwargs[_n] for _n in names])
   2090 
-> 2091         return self._vectorize_call(func=func, args=vargs)
   2092 
   2093     def _get_ufunc_and_otypes(self, func, args):

~/opt/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py in _vectorize_call(self, func, args)
   2165                       for a in args]
   2166 
-> 2167             outputs = ufunc(*inputs)
   2168 
   2169             if ufunc.nout == 1:

~/opt/anaconda3/lib/python3.7/site-packages/scipy/stats/_continuous_distns.py in _truncnorm_ppf(q, a, b)
   7093         return x
   7094     elif np.isinf(a):
-> 7095         x = _norm_ilogcdf(np.log(q) + _norm_logcdf(b))
   7096         return x
   7097     if q <= 0.5:

~/opt/anaconda3/lib/python3.7/site-packages/scipy/stats/_continuous_distns.py in _norm_ilogcdf(y)
   7069     z = -np.sqrt(-2*(y + np.log(2*np.pi)/2))
   7070     for _ in range(3):
-> 7071         z = z - (_norm_logcdf(z) - y) / _norm_logcdfprime(z)
   7072     return z
   7073 

~/opt/anaconda3/lib/python3.7/site-packages/scipy/stats/_continuous_distns.py in _norm_logcdfprime(z)
   7048 def _norm_logcdfprime(z):
   7049     # derivative of special.log_ndtr
-> 7050     assert np.abs(z) > TRUNCNORM_TAIL_X/2
   7051     lhs = -z - 1/z
   7052     denom_cons = 1/z**2

AssertionError:
`
Thanks a lot for your help in advance.

I am using scipy 1.4.1

**Comment by tranhungnghiep** [comment]
> While I understand your frustration, there typically is a strict backwards compatibility policy: we don't change existing APIs, because there may be users depending on the existing behavior. The fact that the behavior is explicitly documented makes me think that is the most likely outcome, but I'm no expert on this particular module, maybe @josef-pkt has a more informed opinion on this particular issue.
> 
> In any case, if such a change was to be made, it would require discussion on [the mailing list](https://www.scipy.org/scipylib/mailing-lists.html), since that's read by many more people in the community than this issue tracker. Can you write an e-mail to scipy-dev explaining your issues with trucnorm?

@jaimefrio It is possible to change the behavior without breaking backwards compatibility. One such way is adding a default flag `truncnorm(..., auto_convert_range=False)`. Old codes will still run correctly, whereas new codes can turn the flag on to handle the conversion automatically. This will clear up many confusions and new codes.
