### ISSUE TITLE
BUG: scipy.sparse.linalg.linsolve() + scikits.umfpack 0.3.0 on win-amd64

### ISSUE THREAD

**Issue by rc** [scipy/scipy#7600]
scikits.umfpack 0.3.0 has many failures on win-amd64, caused by other bit-width chars for the same types than on linux - see https://github.com/scikit-umfpack/scikit-umfpack/issues/36. Some of the tests just call `scipy.sparse.linalg.linsolve()`, which has to be fixed in the same spirit as in the PR https://github.com/scikit-umfpack/scikit-umfpack/pull/37 (when it is finished). I will take care of that, as soon as I will have the fixes ready on the scikit-umfpack side.

**Comment by rgommers** [comment]
Sounds good. Marking this for the next release so we won't forget the fix for this.

**Comment by rgommers** [comment]
Looks like this won't be fixed before the beta release. Would be great though to get it done before ``1.0.0rc1`` which is planned for 27 Sep. Do you have any time for this @rc?

**Comment by rc** [comment]
@rgommers I would like to. I got some help with setting up a windows test machine, so hopefully I will fix/verify the related scikit-umfpack code soon.

**Comment by rgommers** [comment]
Awesome, thanks for the update

**Comment by pv** [comment]
For Windows testing, I've found the development VM images provided by 
microsoft useful (they in principle expire but apparently not really in 
practice): https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

You can install Python, MSVC (see 
https://wiki.python.org/moin/WindowsCompilers), and MSYS2+gfortran in 
them, and download the openblas libs mentioned in our appveyor config 
https://github.com/scipy/scipy/blob/master/appveyor.yml. After copying 
libopenblas*.a to Python\Libs\openblas.a, numpy (current master branch 
required to get the necessary numpy.distutils fixes) and scipy can be 
compiled and installed with `python setup.py` as on the other platforms, 
runtests.py works etc. It's still a bit of a PITA, but much closer to 
working "out of the box" than before.

After release of numpy 1.14, the windows build instructions on scipy.org 
should be updated.

**Comment by rc** [comment]
@pv, thanks for the tips!

**Comment by rc** [comment]
Update: still no luck installing suitesparse into W10 (will try harder).

**Comment by rc** [comment]
Nevertheless, I have just created #7939, to make things moving - it uses the same code I have used to fix the scikit-umfpack code, which was tested on win-amd64 platform by @cgohlke. I will keep trying to get suitesparse installed on my w10 test-box (advice welcome).

**Comment by rgommers** [comment]
Awesome, thanks @rc.

If SuiteSparse is so difficult to install on Windows we're not going to have a lot of users, so perhaps no feedback during release candidate testing (except perhaps from @cgohlke if he has a working SuiteSparse install). But patch is easy to review, so if it passes on all platforms we can test on then let's just merge it I'd say.

**Comment by rc** [comment]
Well, I do not know if it is really hard to install suitesparse, I am just completely lost in Windows :)

Note that the bug manifested only with scikit-umfpack 0.3.0 (and later) (where support for long matrix indices was added) on win-amd64 - I do not know how the CI configs in scipy handle the scikit-umfpack/suitesparse optional dependency.

**Comment by rgommers** [comment]
For ``conda-forge`` no one managed yet, and the one build config I did see for ``conda`` was quite hacky. So it must be nontrivial. Anything Fortran-based is on Windows:(

> I do not know how the CI configs in scipy handle the scikit-umfpack/suitesparse optional dependency.

They don't, I see it's missing. I'll see if I can send a PR tonight to add it to the TravisCI tests.

**Comment by rc** [comment]
AFAIK suitesparse is written in C.

**Comment by rgommers** [comment]
Ah yes, you're right. Hard for other reasons then:)

I tested this PR and scikit-umfpack master, both pass all tests on 32-bit Linux (which had issues with this before).

**Comment by rgommers** [comment]
Fixed by gh-7939, closing.
