### ISSUE TITLE
Add support for scipy.integrate.ode ODE solver return codes

### ISSUE THREAD

**Issue by suttonje** [scipy/scipy#7603]
Similar to #1801, the return codes generated by the underlying solvers VODE, ZVODE, and LSODE are unavailable to the user. However, these return codes are vital to allowing the user to intelligently decide how to handle any errors encountered by the ODE solver. If, for instance, the error was simply too much work done (the maximum number of allowed steps was reached), the user may wish to restart the integration. Other errors may indeed be fatal and should halt the program.

Currently, warning messages are printed to stderr if the integration fails. It may be possible with the Python warnings module to catch these return codes by redirecting stderr, but this is a sub-optimal workaround. It would be much better if the ode module directly exposes the return codes so that the user has the power to easily choose how to handle any errors that are present.

I have made some small modifications to the ode module (SciPy version 0.18) to permit this. The original source file and patch are included. For consistency, I also set a return code for the other ODE solvers (dopri53 and dop853).

**Comment by rgommers** [comment]
@suttonje Firefox NoScript complained about a cross-site scripting problem with your links, so I removed them. Please submit your changes as a pull request for easier review
