### ISSUE TITLE
SLSQP optimizer doesn't handle non-linear/linear constraints correctly

### ISSUE THREAD

**Issue by vermaven** [scipy/scipy#7618]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

I am trying to solve an engineering problem where I have a quadratic cost function and non linear equality and inequality constraints. I am using scipy SLSQP optimizer to get an optimum solution. The optimizer returns a solution saying the optimization terminated successfully. When I check the value of constraint equations at the optimum solution, I can clearly see that the constraints have not been satisfied; equality constraints are not equal to 0 (off by oder of integer) and some of the inequality constraints are less than zero (should have been greater than 0, again off by order of integer). 

This led me to test the SLSQP optimization with a simple linear cost function (doesn't matter even if I take a quadratic function) and linear inequality constraints. The SLSQP still returns a solution even though I made sure that the inequality constraints render the problem space infeasible i.e there is no common feasible region (values of the two variables that I used) for both the constraints. If the values of the inequality constraints are checked, one is ~0 and the other is ~ -1 (which is what should not have been if the optimizer is reporting an optimum solution successfully). 

Just to test the same toy problem with other scipy libraries, I used '**linprog**' to optimize the same cost function and same constraints. The 'linprog' reports an error: "**Optimization failed. Unable to find a feasible starting point.**"

I wasn't able to see a similar issue reported here and therefore I am reporting it.

It would be really appreciated if someone could help me understand what is happening here.

### Reproducing code example:
```
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>

from __future__ import division
import numpy as np
import math
from scipy.optimize import minimize


def cost(x):
    return -1 * x[0]  + 4 * x[1]

def ineqcons1(x):
    return x[1] - x[0] -1

def ineqcons2(x):
    return  x[0] - x[1]

x0 = (1,5)
bnds = ((-5,5), (-5,5))
con = ({'type':'ineq', 'fun': ineqcons1},{'type':'ineq', 'fun': ineqcons2})
res = minimize(cost, x0, method='SLSQP',  bounds = bnds, constraints=con, options={'maxiter' : 10000, 'ftol':0.0001 })
print "optimization result",res

for cons in con:
    print "constraints values for optimized variables", cons['fun'], cons['fun'](res.x), cons['type']
```

### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>

optimization result      fun: -11.000000016144568
     jac: array([-1.,  4.,  0.])
 message: 'Optimization terminated successfully.'
    nfev: 16
     nit: 8
    njev: 4
  status: 0
 success: True
       x: array([-5., -4.])
constraints values for optimized variables <function ineqcons1 at 0x112825938> -4.03614208722e-09 ineq
constraints values for optimized variables <function ineqcons2 at 0x1128259b0> -0.999999995964 ineq
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
('0.18.1', '1.12.0', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0))

```

**Comment by pv** [comment]
This sounds similar to gh-6859, where SLSQP produces garbage with 
initial guess outside bounds. It is as if the algorithm assumes the 
initial guess is feasible, and returns garbage otherwise.
.
The FORTRAN code of the optimizer however supposedly has return codes 
for infeasibility, and does not mention such issue:
.
https://github.com/scipy/scipy/blob/master/scipy/optimize/slsqp/slsqp_optmz.f
.
The solution to this probably requires someone to audit what goes wrong 
in there.

**Comment by pv** [comment]
Are the issues with a feasible initial guess within numerical precision 
of the algorithm? I suspect the algorithm decides the solution is "good 
enough" vs. the constraint, if the residual value of the constraint is 
of the order of the gradient of the constraint function multiplied by 
the desired accuracy in the solution.

**Comment by vermaven** [comment]
Hi, 
Thanks for such a quick response!
The problem does not seem to be with the initial guess. To begin with they are placed well within the bounds. 
The residual value of the constraints become secondary because there is no feasible region for the optimizer to operate in, in the toy problem that I uploaded.
In the problem, I gave a cost function : 4y -x
and the 2 inequality constraints that I gave are:
x -y >= 0 .  and
y -x -1 >=0.

So, if we see the two constraints, we can easily figure out that there is no set of x and y which can satisfy both the constraints. Therefore, I think the optimizer should have been able to report this!!

Also, correct me if I am interpreting your comment  about the residual value of the constraint wrongly. I think the gradient of the constraint wrt either of the two variables would be +/- 1. If that is multiplied with the tolerance (0.0001), that does not yield the residual value reported by the optimizer(-0.99)

**Comment by pv** [comment]
What I mean with the comment on residual values is the following:
The question is whether the failure mode here is something occurring 
only with an infeasible initial guess, which is demonstrated by the 
example case here, or more general.
.
The question about precision is regarding your comment that the failure 
mode is more general --- but were issues with residual constraint 
accuracy ruled out (ftol should denote relative tolerance)? Would be 
useful to have a test case that fails with feasible initial value.

**Comment by pv** [comment]
What I mean with the comment on residual values is the following:
The question is whether the failure mode here is something occurring 
only with an infeasible initial guess, which is demonstrated by the 
example case here, or more general (for which there's no explicit 
demonstration listed).
.
The question about precision is regarding your comment that the failure 
mode is more general --- were issues with residual constraint accuracy 
ruled out (ftol should denote relative tolerance)?

**Comment by mdhaber** [comment]
@vermaven I have encountered similar issues with SLSQP not respecting constraints yet reporting successful termination. 
I can't offer a fix for it, but if you can post the details of the problem, we'd love to make sure that a new solver (in development) can handle it. 
And it seems like you are happy that `linprog` appeared to find the problem infeasible, but note that sometimes this simplex implementation fails to find a feasible starting point even when the solution exists (see #6139). I'm not saying that's the case here; just a caution for the future.

**Comment by vermaven** [comment]
@mdhaber Thanks for the info on linprog. 
The problem i am trying to solve involves 5 variables (3 states: x,y,z, 2 controls: a,b) at each time step, for 20 steps. At each time step, I have some equality constraints and some inequality constraints to be satisfied. 
Equality constraints are of the form: x(k+1) - x(k) - a* cos(z)
### k denotes the time step

**the inequality constraints at each step are of the form:
_(a(k+1) - a(k))^2 + (a*b)^2 <= some positive constant_**
**(this inequality is most probably leading to strange behavior of the optimizer. If i remove these inequality constraints, the optimizer solution seems reasonable )**
There are other inequality bounds also but they are trivial. 

Apart from this I also have bounds on each of the 5 variables for all 20 time steps

**Comment by vermaven** [comment]
@mdhaber Thanks for the info on linprog.
The problem i am trying to solve involves 5 variables (3 states: x,y,z, 2 controls: a,b) at each time step, for 20 steps. At each time step, I have some equality constraints and some inequality constraints to be satisfied.

Equality constraints are of the form: 
**x(k+1) - x(k) - a* cos(z(k))** .             (k denotes the time step)

The Inequality constraints at each step are of the form:
**(a(k+1) - a(k))^2 + (a*b)^2 <= some positive constant
(this inequality is most probably leading to strange behavior of the optimizer. If i remove these inequality constraints, the optimizer solution seems reasonable )**
There are other inequality bounds also but they are trivial.

Apart from this I also have bounds on each of the 5 variables for all 20 time steps

**Comment by mdhaber** [comment]
@vermaven Thanks, and if you'd be willing to send the complete problem setup we'd love to test with it. If not, I have some large, very nonlinear optimal control examples we will test with.

**Comment by OzzyXu** [comment]
Did you try some smaller fun_tol for your problem? Based on my experience, sometimes SLSQP will converge too soon if the fun_tol was not set appropriately. This may cause problem. I am not sure whether this would help.

**Comment by OzzyXu** [comment]
When I use fun_tol = 10**-12, the optimal result is:
optimization result      fun: -11.000000016144568
     jac: array([-1.,  4.,  0.])
 message: 'Positive directional derivative for linesearch'
    nfev: 16
     nit: 8
    njev: 4
  status: 8
 success: False
       x: array([-5., -4.])

Same result, different message and is not success anymore.

**Comment by OzzyXu** [comment]
Hey All,

After checking the Fortran code of SLSQP, I found something:

Based on the subroutine slsqpb Line 340 to Line 375, if mode is set to 6 after calling lsq()(Line 336) and n(number of variables) == meq(number of equality constraints)(Line 341), then mode is assigned the value of 4. And set mode to 4 is the sufficient condition to end whole algorithm with mode 4. 

In subroutine lsq() Line 735, subroutine lsei() is called. And in Line 831 of lsei(), mode is set to 6. But Line 833 has to be satisfied to end the subroutine immediately. Otherwise, mode would be assigned some other values. 

If mode == 4, based on Line 368, we know that lsq has to be called five times and mode should stay at 4 during those calls, this can only be done if Line 1047 of subrountine ldp() is not executed and Line 1049 is executed. 

In summary, several things are critical to end the algorithm with mode 4: 
Line 341 of slsqpb(): IF (n.EQ.meq) 
Line 831 of lsei(): IF(ABS(c(i,i)).LT.epmach) and
Line 1049 of ldp(): IF(rnorm.LE.ZERO).

Since I can't find Dr. Kraft's paper(I have tried Google scholar, but it's unable to download anymore), I don't know what those means. But I have some concerns about the logic of Line 341. Because if we change the constraints of @vermaven 's problem to 
con = ({'type':'eq', 'fun': ineqcons1},{'type':'eq', 'fun': ineqcons2}),
the result is:
optimization result      fun: 1.000000000001961
     jac: array([-1.,  4.])
 message: 'Inequality constraints incompatible'
    nfev: 17
     nit: 4
    njev: 4
  status: 4
 success: False
       x: array([-5., -1.])

I don't know whether these information would provide any help to debug this problem. I am really not good at Fortran and it's a disaster to read code without that paper... @pv @vermaven

**Comment by pv** [comment]
Yes, it looks as if there's some issue in the logic of the algorithm at 
the "augmented problem for inconsistent linearization" part. I would 
expect the algorithm here follows some well known SQP recipe, so this 
part can maybe be understood without Kraft's paper (which any of us 
don't seem to have access to). Googling for "sequential linear least 
squares inconsistent linearization augmented problem" brings up e.g. 
Sec. 7 here 
https://web.cse.ohio-state.edu/~parent.1/classes/788/Au10/OptimizationPapers/SQP/actaSqp.pdf 
--- not sure if it's related though.

**Comment by pv** [comment]
If the problem is just that the augmented SQP problem doesn't guarantee the constraints are satisfied, this can be addressed just by not terminating with success on iterations where the augmented problem was used --- like so: https://github.com/scipy/scipy/compare/master...pv:slsqp-incons-fix.patch
This seems to fix at least the simple example cases above.

I'm not sure that this is the actual fix, since I don't know exactly what the algorithm is doing here.
If someone wants to dig, this seems like the right place to start digging deeper.

**Comment by OzzyXu** [comment]
I will test this issue with some other larger scale problems later once the package get updated.

**Comment by pv** [comment]
Testing would be most useful before actually releasing packages with the changes.

**Comment by OzzyXu** [comment]
Sorry that I don't know how to test the change you supposed. Where can I find the slsqp_optmz.f file on my computer? Or what things should I edit on my PC? Can you give me some guidance?

**Comment by felixlen** [comment]
I agree that it makes most sense first to understand how to infeasibility handling works and the best thing might be to get hold of the original paper. It is supposed to be in the library of a university close to me, so I try to get a scan next time I'm there.

**Comment by WarrenWeckesser** [comment]
The question ["Scipy optimize.minimize exits successfully when constraints aren't satisfied"](https://stackoverflow.com/questions/51110277/scipy-optimize-minimize-exits-successfully-when-constraints-arent-satisfied) on stackoverflow appears to report the same bug.

Here's a slight variation of the code from that question:

```
from scipy import optimize


def f(x):
    return x**2 - 4*x

def x_constraint1(x):
    return x - 5

def x_constraint2(x):
    return -x

# subject to x >= 5 and x<=0 (not possible)
constraints = [{'type': 'ineq', 'fun': x_constraint1},
               {'type': 'ineq', 'fun': x_constraint2}]

optimize.minimize(f, x0=3, constraints=constraints)

# Result is:
#     fun: -3.0
#     jac: array([ 2.])
# message: 'Optimization terminated successfully.'
#    nfev: 3
#     nit: 5
#    njev: 1
#  status: 0
# success: True
#       x: array([ 3.])
```

The solution `x` depends on `x0`, but in all the cases that I've tried, the function incorrectly reports that it has succeeded.

The above call results in the method `'SLSQP'` being used--that is the default when `method` is not specified and the `constraints` argument is given.

**Comment by pv** [comment]
PR gh-8986 applies my patch above. It's probably safe in the sense that it shouldn't cause false positive exits. But some problems that previously could be solved might theoretically start to fail, or take more iterations. I don't know any such problems though.

**Comment by DongqinZhou** [comment]
> Hey All,
> 
> After checking the Fortran code of SLSQP, I found something:
> 
> Based on the subroutine slsqpb Line 340 to Line 375, if mode is set to 6 after calling lsq()(Line 336) and n(number of variables) == meq(number of equality constraints)(Line 341), then mode is assigned the value of 4. And set mode to 4 is the sufficient condition to end whole algorithm with mode 4.
> 
> In subroutine lsq() Line 735, subroutine lsei() is called. And in Line 831 of lsei(), mode is set to 6. But Line 833 has to be satisfied to end the subroutine immediately. Otherwise, mode would be assigned some other values.
> 
> If mode == 4, based on Line 368, we know that lsq has to be called five times and mode should stay at 4 during those calls, this can only be done if Line 1047 of subrountine ldp() is not executed and Line 1049 is executed.
> 
> In summary, several things are critical to end the algorithm with mode 4:
> Line 341 of slsqpb(): IF (n.EQ.meq)
> Line 833 of lsei(): IF(ABS(c(i,i)).LT.epmach) and
> Line 1049 of ldp(): IF(rnorm.LE.ZERO).
> 
> Since I can't find Dr. Kraft's paper(I have tried Google scholar, but it's unable to download anymore), I don't know what those means. But I have some concerns about the logic of Line 341. Because if we change the constraints of @vermaven 's problem to
> con = ({'type':'eq', 'fun': ineqcons1},{'type':'eq', 'fun': ineqcons2}),
> the result is:
> optimization result fun: 1.000000000001961
> jac: array([-1., 4.])
> message: 'Inequality constraints incompatible'
> nfev: 17
> nit: 4
> njev: 4
> status: 4
> success: False
> x: array([-5., -1.])
> 
> I don't know whether these information would provide any help to debug this problem. I am really not good at Fortran and it's a disaster to read code without that paper... @pv @vermaven

Here is the paper: http://degenerateconic.com/wp-content/uploads/2018/03/DFVLR_FB_88_28.pdf
