### ISSUE TITLE
Can optimize.minimize(obj_func, x0) handle an x0 which is a dictionary ?

### ISSUE THREAD

**Issue by NikoZHAI** [scipy/scipy#7620]
This is not a bug report.
As indicated in the title, is it possible to enter a hashtable of parameters to optimize ? If not, could you please kindly tell me if you know some other packages can handle this ?

### Like:
```
<<x0 = {'i': 1, 'j': 2, 'k': 3}
new_x = optimize.minimize(obj_fun, x0, method ='L-BFGS-B', bounds=x_b,
                           tol=tol)>>
```
Regards,
Niko

**Comment by andyfaff** [comment]
The lmfit package might meet your needs. But you'll need to convert your dict to a Parameters instance first.
