### ISSUE TITLE
gmres() issues

### ISSUE THREAD

**Issue by rc** [scipy/scipy#7623]
The docstring of the sparse iterative solver `scipy.sparse.linalg.isolve.gmres()` has the following issues:
- the `callback` argument: rk is in fact not the residual vector, but the residual norm (cf. #6198).
- the `tol` argument: it seems, that  STOPTEST2() fortran function uses only a relative test w.r.t. the right-hand side norm. Moreover, it seems that a preconditioned residual is used for the test (might be related to  #2694).

The call to `gmres()` sometimes (for a small maxiter?) does not return the found solution, e.g. when the `maxiter=10`, it seems to return the initial guess, while for  `maxiter=20` it does return the found solution. For example: (the residual norm is printed using a callback, no preconditioning):

- `maxiter=10`
```
sfepy: nls: iter: 0, residual: 1.200000e+01 (rel: 1.000000e+00)
sfepy: iterative-s: iteration 1: |Ax-b| = 6.952609e-01
<snip>
sfepy: iterative-s: iteration 10: |Ax-b| = 2.070826e-01
sfepy: iterative-s: gmres convergence: 10 (number of iterations)
sfepy: nls: iter: 1, residual: 1.200000e+01 (rel: 1.000000e+00)
```
  - here the last line reports the new residual norm, which is the same as in the first line

- `maxiter=20`
```
sfepy: nls: iter: 0, residual: 1.200000e+01 (rel: 1.000000e+00)
sfepy: iterative-s: iteration 1: |Ax-b| = 6.952609e-01
<snip>
sfepy: iterative-s: iteration 20: |Ax-b| = 1.121924e-01
sfepy: iterative-s: gmres convergence: 20 (number of iterations)
sfepy: nls: iter: 1, residual: 1.346308e+00 (rel: 1.121924e-01)
```

Tested with scipy 0.18.1, as for some reason I am unable to compile the master branch. (`build/src.linux-x86_64-2.7/scipy/optimize/cobyla/_cobylamodule.c:400:109: error: ‘NPY_FARRAY’ undeclared (first use in this function)`)

**Comment by rc** [comment]
Update: the solution vector is updated _only_ in iterations that are divisible by `restart` value.

**Comment by pv** [comment]
These were fixed. The strange callback_type='legacy' behavior however is unfortunately baked in, but now it's possible to avoid it.
