### ISSUE TITLE
allow setting both absolute and relative tolerance of sparse iterative solvers

### ISSUE THREAD

**Issue by rc** [scipy/scipy#7624]
Currently a single tolerance (`tol` argument) is used, which is impractical, when using an iterative solver as a preconditioner. In that case it is desirable to set a relative tolerance to some not-so-small value (e.g. 1e-2), without caring about the absolute tolerance. The current behaviour prevents that, as something like setting `tol=1e-2` often leads to absolute convergence in iteration zero of the preconditioner, hence no preconditioning done at all.

This behaviour breaks the IMHO very good `lgmres` solver. For example, the following happens when using `lgmres` with `cg` (`tol=1e-2`) as a preconditioner for symmetric positive definite diagonal blocks:

```
<snip>
sfepy: cg-s: iteration 1
sfepy: cg-s: iteration 2
sfepy: cg-s: iteration 3
sfepy: cg-s: iteration 4
sfepy: cg-s: iteration 5
sfepy: cg-s: iteration 6
sfepy: cg-s: cg convergence: 0 (successful exit)
rhs norm: 8.751133e-02, solution norm: 4.484927e+00
sfepy: iterative-s: iteration 4: |Ax-b| = 2.323006e-03
sfepy: cg-s: iteration 1
sfepy: cg-s: cg convergence: 0 (successful exit)
rhs norm: 4.101975e-04, solution norm: 0.000000e+00
sfepy: cg-s: iteration 1
sfepy: cg-s: cg convergence: 0 (successful exit)
rhs norm: 2.286502e-03, solution norm: 0.000000e+00
Traceback (most recent call last):
<snip>
  File "....local/lib/python2.7/site-packages/scipy/sparse/linalg/isolve/lgmres.py", line 145, in lgmres
    "|v| ~ %.1g, |M v| = 0" % rnorm)
RuntimeError: Preconditioner returned a zero vector; |v| ~ 0.002, |M v| = 0
```

This happened because the rhs norm was 2.286502e-03 < 1e-2 (see the line above the traceback), so no solution was attempted.

So I propose having both `rtol` and `atol` arguments (or allow `tol` to be a tuple), and possibly adding a `tol_mode` argument - either 'and' or 'or', defaulting to 'or', that tell whether both tolerances have to be met ('and' mode) or a single one is enough.

I can make a PR implementing this for `lgmres`, as it is written in Python. I am not sure if I am brave enough to dive into the legacy fortran of the other solvers.

**Comment by person142** [comment]
When a similar issue came up with `differential_evolution` we kept `tol` for relative tolerance and added an `atol` for absolute tolerance:

https://github.com/scipy/scipy/pull/6449#issuecomment-239268592

Seems like doing the same thing here would be appropriate.

**Comment by pv** [comment]
This has been on the todo list forever, so it's good if you want to fix 
it finally...
.
For backward compat: I would add new arguments rtol and atol. The `tol` 
argument sets both to the same value, and an error is raised if the user 
gives both `tol` and `rtol` or `atol`. We might also want to issue a 
DeprecationWarning if the user sets the `tol` argument.
.
The second question is what to do with left-preconditioning. I'm not 
sure applying an absolute tolerance to preconditioned residuals is very 
sensible --- this is just a surprise waiting to happen.
.
Note that there's some refactoring of LGMRES here 
https://github.com/scipy/scipy/pull/5910, plus some minor fixes.

**Comment by pv** [comment]
(Btw, review of gh-5910 would be appreciated in case you're interested 
in the topic ;)

**Comment by rc** [comment]
Yes, leaving tol and adding rtol, atol was another option I considered :). I will give it a shot after I resolve my compilation issues with the scipy master.

**Comment by rc** [comment]
The fortran-based solvers seem all to use the relative-only test (contrary to what the docstrings say), as defined in  STOPTEST2.f.src, which is equivalent to `r_norm <= tol * b_norm`.

The python-based solvers (lgmres, and gcrotmk) use both the relative and absolute test.

So the PR should
- modify STOPTEST2.f.src for RTOL, ATOL
- update iterative.py for rtol, atol
- update lgmres (and gcrotmk) for rtol, atol

Now the condition above measures |r_k| / |r_0| only for the zero initial guess. Does it make sense to use |b - A x0| instead of |b|? I guess no - I have just checked that petsc uses also just |b|, so it is what people probably expect, but what do you think?

I would also like to introduce the  `tol_mode` argument (described above) - do you agree?

**Comment by pv** [comment]
The fortran solvers also do absolute termination checks, iirc, but this 
is elsewhere in the code than in STOPTEST2. The extra check may also in 
some cases be done only for the first step.

**Comment by rc** [comment]
Yes, I can see the absolute test for the first step, e.g. in CG. Thanks!

**Comment by rc** [comment]
Heretical thought: having the fortran solvers rewritten in Python, following the examples of lgmres and gcrotmk, would be much more maintainable.

**Comment by person142** [comment]
> Heretical thought: having the fortran solvers rewritten in Python, following the examples of lgmres > and gcrotmk, would be much more maintainable.

Doesn't seem heretical to me (I've wished for the same thing in fact), though Cython might be even better. I'd guess that the issue here is just someone having time to do it.

**Comment by person142** [comment]
As a fun side-effect it would also make the solvers reentrant.

**Comment by rc** [comment]
Would Cython help here? IMHO the solvers spend most of the time for non-tiny problems in blas/matvec calls, that are compiled anyway. But I did not measure that :)

**Comment by person142** [comment]
> Would Cython help here?

I doubt it would speed things up much. IMO the benefit would come from possibly exposing the Cython interface directly in addition to a Python interface.

**Comment by rc** [comment]
Well, there is [1] - a ready python implementation with MIT license and compatible function arguments. I guess we should not reinvent wheels :)

[1] https://github.com/pyamg/pyamg/tree/master/pyamg/krylov

**Comment by pv** [comment]
@rc: did you manage to make headway with fixing the tolerances?

**Comment by rc** [comment]
@pv not yet - I have been a bit afraid of diving into the fortran sources. :(  (And holidays interference in the meantime.) The fortran code seems to have some tolerance related issues/discrepancies (like https://github.com/scipy/scipy/issues/7623), which I did not analyse properly.

I was exploring a bit the Krylov solvers available through PyAMG, as a potential candidate for replacing the fortran code in scipy, but even those seem to have some discrepancies in how the error is measured among the methods and between the implementation and docstrings (see e.g. https://github.com/pyamg/pyamg/issues/203, where a possible better stopping criterion is also discussed). It might be that the pyamg implementation was inspired by the same source as the scipy one. In any case, the PyAMG Krylov solvers are way more readable (for me). What do you think about contacting the PyAMG team in the respect of using their solvers in scipy? But I guess this would not be for the 1.0 milestone, while I can still try to hack the fortran functions in time.

**Comment by perimosocordiae** [comment]
No open PRs yet, so I'm pushing this back to the 1.1 milestone.

**Comment by pv** [comment]
Suggested fix in gh-8400

**Comment by rc** [comment]
Thanks @pv! I will try the preconditioning use with the https://github.com/scipy/scipy/pull/8400 branch.

**Comment by pv** [comment]
Now that you mention preconditioning...

I now realize that the fortran code termination conditions actually use 
the *left preconditioned residual*. So gh-8400 needs still further work.

**Comment by pv** [comment]
Ok, preconditioner issues should now be fixed in gh-8400.

In the end, this only affects `gmres` and `lgmres`, because only they have an inner loop stoptest that looks at the preconditioned residual.

Because for preconditioned problems the preconditioned residual and actual residual may behave differently, I had to add an adaptive tolerance adjustment that ensures the inner loop tolerance is reduced if the preconditioned residual check passes, but the actual residual check not. This is somewhat different from a "traditional" GMRES implementation that only deals with relative tolerance of the preconditioned residual, however.
