### ISSUE TITLE
scipy.linalg.cho_factor trouble with empty nparray

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#7631]
In #7123 (Interior Point Method for `linprog`) TravisCI jobs X.3-X.6 with verbose output, the following occurred:
```
test_linprog.TestLinprogIP.test_unbounded_below_no_presolve ... 

Primal Feasibility  Dual Feasibility    Duality Gap         Step                Path Parameter      Objective          
0.0                 0.0                 1.0                 -                   1.0                 0.0                 
 ** On entry to DPOTRF parameter number  4 had an illegal value

travis_time:end:0866793a:start=1500403878367062329,finish=1500404444732519125,duration=566365456796
[0K
[32;1mThe command "python -u $OPTIMIZE runtests.py -g -m $TESTMODE $COVERAGE $USE_WHEEL_BUILD |& tee runtests.log" exited with 0.[0m
travis_time:start:005bf86c
[0K$ tools/validate_runtests_log.py $TESTMODE < runtests.log
*** Test runner validation errored: did the run really finish?

travis_time:end:005bf86c:start=1500404444739032504,finish=1500404444793625359,duration=54592855
[0K
[31;1mThe command "tools/validate_runtests_log.py $TESTMODE < runtests.log" exited with 255.[0m
travis_time:start:04b5985c
[0K$ if [ "${REFGUIDE_CHECK}" == "1" ]; then python runtests.py -g --refguide-check; fi

travis_time:end:04b5985c:start=1500404444800632628,finish=1500404444806269233,duration=5636605
[0K
[32;1mThe command "if [ "${REFGUIDE_CHECK}" == "1" ]; then python runtests.py -g --refguide-check; fi" exited with 0.[0m
travis_fold:start:cache.2
```

As @ilayn expected, this was traced to a call to `cho_factor` acting on an empty `ndarray` with shape `(0,0)`. 

### Reproducing code example:
```
import numpy as np
from scipy.linalg import cho_factor
cho_factor(np.empty((0,0)))
```

### Error message:
This does not simply cause the test to fail. It halts the testing altogether.

On my machines, however, the call above produces a `ValueError`:
```
Traceback (most recent call last):

  File "<ipython-input-14-e4b1c49a19b3>", line 1, in <module>
    cho_factor(np.array([]).reshape(0,0))

  File "/Users/matthaberland/Desktop/ScipyDev/scipy/scipy/linalg/decomp_cholesky.py", line 132, in cho_factor
    check_finite=check_finite)

  File "/Users/matthaberland/Desktop/ScipyDev/scipy/scipy/linalg/decomp_cholesky.py", line 33, in _cholesky
    % -info)

ValueError: illegal value in 4-th argument of internal potrf
```
The unit test doesn't even _fail_ locally because the offending line is within a `try` block, and is handled appropriately. This problem was only identified in TravisCI testing.

### Scipy/Numpy/Python version information:
```
1.0.0.dev0+c29306e 1.12.0 sys.version_info(major=3, minor=6, micro=0, releaselevel='final', serial=0)
```
Issue discovered in #7123 unit tests; more information may be available there.

**Comment by rgommers** [comment]
Guess that needs an explicit check within ``cho_factor``, and then directly raise a ``LinAlgError`` (or return empty arrays of the same shape?).

**Comment by ilayn** [comment]
I think there are two issues: one is what @rgommers mentioned that zero sized matrix shouldn't have survived up to the lapack call and the second is why ?POTRF is dying instead of gracefully returning back with -4 error code. 


![image](https://user-images.githubusercontent.com/1303842/28362380-81fb231a-6c7c-11e7-8603-8a7fc6b401f3.png)

but on Windows command prompt

![image](https://user-images.githubusercontent.com/1303842/28362479-d5a10d9a-6c7c-11e7-9b41-613a8ea731f4.png)

I believe there is something fishy about the wrapper too.
