### ISSUE TITLE
it's not possible to tell the `optimize.least_squares` solver to never terminate on xtol

### ISSUE THREAD

**Issue by greysAcademicCode** [scipy/scipy#7632]
Other trf solvers I've used support this by allowing the user to set xtol=0

**Comment by rgommers** [comment]
``xtol=None`` would be more idiomatic, but other than that sounds reasonable. @nmayorov ?

**Comment by nmayorov** [comment]
Our lower bound is machine epsilon for each of the tolerance. For `xtol` it means that we should distinguish between nearby points using double precision numbers.  It seems to me is that `x` didn't change (in floating point numbers) after an iteration then it makes sense to terminate the algorithm.

@greysAcademicCode does it have any benefits to disable it?

**Comment by greyltc** [comment]
@nmayorov, say `x` is a five element vector, and I have `xtol = np.finfo(float).eps`. Does the algorithm terminate when any element of `x` stops changing or when all elements stop?
If one of the fit parameters can trigger premature termination, I'd say that's a bad thing.

In general though, when I'm working on getting a good fit for a new problem, I like to probe how the fit goes when I change the termination conditions. I learn a lot about the system experimenting that way. That's really why I'd like the option of switching on and off each of the termination conditions here (xtol, gtol, ftol, max_nfev).

**Comment by nmayorov** [comment]
The exact condition is `norm(dx) < xtol * (xtol + norm(x))` and `norm` is Euclidean norm. The ideas behind these limits were a) to ensure that the algorithm always terminates b) guide users to realistic tolerances. 

I believe disabling some of the checks is not a bad thing, but I don't know what is "the best" approach here. I think the current approach is fine, but we can consider changing it.

**Comment by nmayorov** [comment]
So @greyltc do you really demand this change?

**Comment by greyltc** [comment]
__Demand__ is certainly not the word I'd use.

I would find it _very_ helpful (and I believe others would too) if there was a way to disable the xtol, gtol and ftol termination conditions individually, for example by setting them to zero. Maybe a warning could be issued in that case.

**Comment by nmayorov** [comment]
OK, I understand you. Would you send a pull request for that? I think a warning for each tolerance that "setting < tol > below `eps` effectively disables the check" (something along those lines) would be sufficient.

**Comment by emmanueliarussi** [comment]
Hello, I'm interested in disabling xtol too. Is there a way to do it yet? Thanks!

**Comment by mccullerlp** [comment]
I have an issue with xtol in that it uses the norm of x to decide tolerances for all elements (at least in TRF it does). If one of the parameters is much larger than the others, then to fitter can fail to make progress as the largest parameter sets the scaling.

If I could disable it, that would be great. Otherwise perhaps an additional option flag or a callback to decide how best to compute it for the given problem. There could be standard callbacks for the current method, one for the maximum relative change of all parameters, and a callback which disables the computation.

**Comment by nmayorov** [comment]
@mccullerlp this is a valid point. Now as I look at it I don't understand why exactly I decided to use unscaled `x` for tolerance determination. MINPACK uses scaled `x` and it makes more sense. I will think about it. Maybe we should change the criteria first.

**Comment by petergthatsme** [comment]
Was wondering if there has been a decision on making `xtol=None` (along with maybe the other termination conditions) available?

**Comment by masta-g3** [comment]
I would also like to bring up this topic again, and ask if there are any plans to either allow no termination based on xtol, or at least implement the scaled `x` version. I would also be happy to help with the implementation if that's possible, as this is a vital functionality for large scale optimization.

**Comment by mayou36** [comment]
@nmayorov is there any progress or branch active regarding this issue?

+1 for `xtol=None` and/or scaled criteria
