### ISSUE TITLE
cKDTree is compiled twice on build and install 

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#7641]
```
$ git clean -xdf
$ python setup.py build
... long clean compilation/build
$ python setup.py install
... 
building 'scipy.spatial.ckdtree' extension
compiling C++ sources
C compiler: g++ -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O3 -Wall -fPIC
...
```

Other C++ extensions are not recompiled (e.g., sparsetools). While this is obviously minor and can be solved with ccache, I wonder if there's something in the build setup of scipy.spatial which can be fixed.

**Comment by sethtroisi** [comment]
I was unable to reproduce this.
There have been 30+ changes to setup.py since Jul 2017. 

I believe this was the one that fixed it: https://github.com/scipy/scipy/pull/7728
