### ISSUE TITLE
Use ccache on travis for OSX.

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#7646]
Now that we have testing for OSX on travis we should aim to use ccache to speed up the build. This issue continues the discussion from #7640.

**Comment by andyfaff** [comment]
[It may be working](https://travis-ci.org/andyfaff/scipy/builds/256742311).  Amended the file [slightly](https://travis-ci.org/andyfaff/scipy/builds/256747575) to to see if we get a speedup.

@pv, did you want me to remove the `USE_SDIST=1` for OSX at the same time?

**Comment by andyfaff** [comment]
Apparently the two commits I tried (in previous comment) had exactly the same run time. Not sure if that's an artefact or if travis is doing anything behind the scenes.

**Comment by andyfaff** [comment]
See #7647 for PR enabling ccache

**Comment by pv** [comment]
If you can remove the USE_SDIST=1 that's ok, but it may be useful to do 
it separately in case this needs debugging...

**Comment by pv** [comment]
was vixed
