### ISSUE TITLE
`scipy.linalg.matrix_balance` doctest failures on Travis

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#7652]
The doctest for `scipy.linalg.matrix_balance` sometimes fails, presumably depending on the platform--most likely it is dependent on LAPACK.

From the logs of  https://github.com/scipy/scipy/pull/7628

```
scipy.linalg.matrix_balance
---------------------------
File "build/testenv/lib/python2.7/site-packages/scipy/linalg/basic.py", line 1466, in matrix_balance
Failed example:
    np.abs(y).sum(axis=0) / np.abs(y).sum(axis=1) # 1-norms approx. equal
Expected:
    array([ 1.10625   ,  0.90547703,  1.00011878])
Got:
    array([ 1.2       ,  1.27041742,  0.92658316])
File "build/testenv/lib/python2.7/site-packages/scipy/linalg/basic.py", line 1469, in matrix_balance
Failed example:
    permscale  # only powers of 2 (0.5 == 2^(-1))
Expected:
    array([[  0.5,   0. ,   0. ],
           [  0. ,   1. ,   0. ],
           [  0. ,   0. ,  16. ]])
Got:
    array([[ 0.5,  0. ,  0. ],
           [ 0. ,  1. ,  0. ],
           [ 0. ,  0. ,  1. ]])
ERROR: refguide or doctests have errors
```

The same problem occurred in https://github.com/scipy/scipy/pull/7650

In the Travis logs where the doctest failed, the operating system is Ubuntu "Trusty", and the LAPACK version is 3.5.0.:

```
Get:20 http://archive.ubuntu.com/ubuntu trusty/main amd64 liblapack3 amd64 3.5.0-2ubuntu1 [1,730 kB]
Get:21 http://archive.ubuntu.com/ubuntu trusty/main amd64 liblapack-dev amd64 3.5.0-2ubuntu1 [1,740 kB]
```

**Comment by pv** [comment]
Ok yes now I remember the balancing change, there's no "right" result here and both are sensible. 
I think it can be changed to reflect the latest lapack, and then add ` # may vary` to the end so that the checker doesn't try to check the result.

**Comment by ilayn** [comment]
Same issue has happened within LAPACK test code too. I'll check what they are using and use the same "safe" example.  Bug report on LAPACK repo : https://github.com/Reference-LAPACK/lapack/issues/42

**Comment by WarrenWeckesser** [comment]
FYI: The results that I get on a Mac using the "nomkl" version of numpy from Anaconda (i.e. using Accelerate) match the values produced in the Trusty environment, not the docstring.

**Comment by ilayn** [comment]
Yes, that's right. We were using 3.5.0 when this was rolled out. Then things have changed apparently.

**Comment by pv** [comment]
Then there's some mystery why it worked previously on travis and not on trusty, because wasn't the lapack in both cases <= 3.5?

**Comment by pv** [comment]
Ok, no, the comment from the lapack dev in the other thread seems wrong --- the release notes say 3.5.0 is the first release with the new xgebal. Maybe Apple has backported stuff silently.

**Comment by ilayn** [comment]
Does anyone have access to LAPACK pre-3.6.0 version environment? 

Could you please check if this is the same ? 
```
>>> y, p = sp.linalg.matrix_balance(np.array([[100],[1],[0.01]]) * np.array([1,2,3]))
>>> y
array([[  1.00000000e+02,   1.25000000e+01,   2.34375000e+00],
       [  1.60000000e+01,   2.00000000e+00,   3.75000000e-01],
       [  1.28000000e+00,   1.60000000e-01,   3.00000000e-02]])
>>> p
array([[ 2.      ,  0.      ,  0.      ],
       [ 0.      ,  0.125   ,  0.      ],
       [ 0.      ,  0.      ,  0.015625]])
```
If it is possible somewhere online you can just point to me and I can also figure out an example

**Comment by pv** [comment]
The version previously in the docstring probably is the < 3.5.0 one if it worked on precise (where lapack=3.3.1).

**Comment by ilayn** [comment]
Indeed, so I'm trying to come up with an example that has similar 1- and 2- norms such that the scaling matrices match.

**Comment by pv** [comment]
That could be nice, but probably not a priority if you can't easily get it to work...

**Comment by ev-br** [comment]
```
In [3]: y, p = matrix_balance(np.array([[100],[1],[0.01]]) * np.array([1,2,3]))

In [4]: y
Out[4]: 
array([[  1.00000000e+02,   1.25000000e+01,   2.34375000e+00],
       [  1.60000000e+01,   2.00000000e+00,   3.75000000e-01],
       [  1.28000000e+00,   1.60000000e-01,   3.00000000e-02]])

In [5]: p
Out[5]: 
array([[ 16.   ,   0.   ,   0.   ],
       [  0.   ,   1.   ,   0.   ],
       [  0.   ,   0.   ,   0.125]])
```

This is on 
```
$ uname -a
Linux duneyrr 3.13.0-68-generic #111~precise1-Ubuntu SMP Fri Nov 6 18:17:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
with stock ATLAS.

**Comment by ilayn** [comment]
OK this means it's not that straightforward. I'll try to come up with an alternative docstring example to avoid this completely.

**Comment by pv** [comment]
Why do you need to avoid it? Most users will be on new lapack, and the ones that are not can see the notice that the result may vary?

**Comment by ilayn** [comment]
Wouldn't this cause problems on PRs every time?

**Comment by pv** [comment]
The `# may vary` marker turns off the checking for that specific output.

**Comment by ilayn** [comment]
This is handled in #7655 and I think can be closed.
