### ISSUE TITLE
scipy.odr.ODR.run documentation should indicate that full_output=1

### ISSUE THREAD

**Issue by thunderfish24** [scipy/scipy#7654]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

I think it would be helpful to know from [the documentation](https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.odr.ODR.run.html#scipy.odr.ODR.run
) that scipy.odr.ODR.run is defaulted to have full_output=1. (It is not clear to me if this setting can be overridden.)

Also, the `sum_sqare` attribute is misspelled in the Output class documentation [here](https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.odr.Output.html#scipy.odr.Output).

### Reproducing code example:
N/A

### Error message:
N/A

### Scipy/Numpy/Python version information:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
``run`` doesn't have any parameters, so no cannot be overridden. Linking to  ``odr.Output`` in the ``run`` docstring may be useful indeed. PR welcome I'd say.

**Comment by thunderfish24** [comment]
Closing. See PR #7664

**Comment by person142** [comment]
Reopening for now--we usually keep issues open until the PR is merged.

**Comment by rgommers** [comment]
fixed by gh-7664
