### ISSUE TITLE
optimize.BenchGlobal broken

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#7658]
As reported on the mailing list, ``optimize.BenchGlobal`` benchmarks are broken currently:

```
python runtests.py --bench optimize.BenchGlobal --> fails on both my modified version (to add stochasticBB testing) and on the original scipy repository (errors described in the pastebin above)

python runtests.py --bench optimize.BenchLeastSquares --> works flawlessly

python runtests.py --bench optimize.BenchSmoothUnbounded --> works flawlessly
```

Traceback:

    =============== =============== ==================== ============= ==================
    --                                       result type / solver                        
    --------------- ---------------------------------------------------------------------
     test function   success% / DE   success% / basinh.   <nfev> / DE   <nfev> / basinh. 
    =============== =============== ==================== ============= ==================
          AMGM           failed            failed            failed          failed      
    =============== =============== ==================== ============= ==================

    [100.00%] ····· 
     
     For parameters: 'AMGM', 'success%', 'DE'
     Traceback (most recent call last):
       File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/asv/benchmark.py", line 773, in <module>
         commands[mode](args)
       File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/asv/benchmark.py", line 744, in main_run
         skip = benchmark.do_setup()
       File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/asv/benchmark.py", line 325, in do_setup
         setup(*self._current_params)
     TypeError: setup() takes 4 positional arguments but 5 were given
     ...

Version information:

Python 3.5
numpy 1.13.0
scipy 1.0.0.dev0+32d8e9e (current master)
asv 0.3.dev1123+32d09e76 (current master)

The problem seems to be that an extra parameter is passed from somewhere: ``setup() takes 4 positional arguments but 5 were given``. Checking those params shows that what's passed is ``name, ret_value, solver, None``. Unclear where the ``None`` is produced exactly. The ``BenchGlobal`` constructor which does not call ``super(BenchGlobal, self).__init__`` seems fragile.

Changing the signature of setup by appending a ``none`` parameter fixes things, but that doesn't look quite right. Last time this was modified is in gh-6400. @andyfaff what do you think?

**Comment by pv** [comment]
iirc the extra parameter is the return value from `setup_cache`, cf. asv 
documentation.

**Comment by rgommers** [comment]
Ah okay, will check that and submit that fix as a PR

**Comment by pv** [comment]
Iow, `return {}` should be `return`
