### ISSUE TITLE
scipy.odr lack support for multi-variable regression

### ISSUE THREAD

**Issue by Rigel7** [scipy/scipy#7666]
While odrpack have the support of multi-variable regression, i.e. regression whose dimension of the explanatory variable is more than one, scipy.odr.data only supports input of x as a one-dimensional array.

I really hope this can be implemented in scipy.odr, as the multi-variable version of orthogonal distance regression is very useful in many cases.

**Comment by ev-br** [comment]
This could be useful indeed. Scipy.odr is not very actively developed though. Would you be intetested in working on this @Rigel7 ?

**Comment by Rigel7** [comment]
Hi @ev-br thank you for your reply. Unfortunately, I do not have any experiences with developing Python modules. I notice that @thunderfish24 opened an issue #7107 about upgrading scipy.odr to ODRPACK95, I guess this can be implemented when upgrading?

I will also see what I can help, if possible.

**Comment by rkern** [comment]
It ought to; I've done it before. Can you show an example that fails?

**Comment by thunderfish24** [comment]
FYI: My current plan is to gain some scipy and cython experience with a
simpler problem, then see if I want to try the bigger ODR update. -Mark
Campanelli (thunderfish24)

**Comment by rkern** [comment]
Example:

```
[~]
|21> import numpy as np
...> from scipy import odr
...> true_beta = np.array([1.0, 2.0, 3.0])
...> x = np.random.randn(2, 10)
...> y = np.random.normal(odr.models.multilinear.fcn(true_beta, x), 0.1)
...> data = odr.RealData(x=x, y=y, sx=0.01, sy=0.1)
...> o = odr.ODR(data, odr.models.multilinear)
...> out = o.run()
...> out.beta
...>
array([ 1.05441156,  1.99242875,  2.98673707])
```

Note the shape of the `x`. Each column is an observation, not each row. I recognize that this is a somewhat odd convention, but I originally wrote this code in ignorance of f2py (or maybe it didn't handle callbacks back then; I don't remember), so I wrote the FORTRAN wrapper manually. It was somewhat more natural to expect the arrays be laid out in memory like FORTRAN expected than to copy the data. It can also make the implementations of the model functions a little more natural when you have to split up the multidimensional `x` to use each component separately.
