### ISSUE TITLE
scipy.sparse.linalg.eigs segmentation fault on complex matrix input

### ISSUE THREAD

**Issue by mgscheer** [scipy/scipy#7667]
When I run scipy.sparse.linalg.eigs on a matrix with all real entries it produces a result without error, but when I run it on a matrix with complex entries it produces a segmentation fault. I've tried running this code snippet with each of the seven sparse matrix classes available in scipy.sparse and I get the same result for all of them.

### Reproducing code example:
```
import numpy as np
import scipy.sparse as sparse
from scipy.sparse import linalg

mat = np.array([[1,1j,1+1j],
                [-1j, 2, 0],
                [1-1j, 0, 3]])
print np.linalg.eig(mat)[0]
print linalg.eigs(sparse.dok_matrix(mat, dtype=complex), 1)```

### Error message:
```
[-0.11490754 +1.35212033e-17j  3.86080585 -2.05623954e-16j
2.25410169 -2.99418538e-17j]
Segmentation fault (core dumped)
```

### Scipy/Numpy/Python version information:
```
('0.19.1', '1.11.1', sys.version_info(major=2, minor=7, micro=11, releaselevel='final', serial=0))
```

**Comment by pv** [comment]
Not reproducible. Reason most likely is that you scipy installation is 
broken in some way. Platform / where did you install it from?

**Comment by mgscheer** [comment]
I'm running lubuntu on an Oracle VM Virtualbox and my python installation is 2.7 from anaconda.
pip show scipy gives:

`Name: scipy
Version: 0.19.1
Summary: SciPy: Scientific Library for Python
Home-page: https://www.scipy.org
Author: SciPy Developers
Author-email: scipy-dev@scipy.org
License: BSD
Location: /home/michael/anaconda2/lib/python2.7/site-packages
Requires: numpy`

How would you recommend installing python/scipy on linux? Thanks for your help!

**Comment by pv** [comment]
Anaconda should be fine in general. Since the problem appears specific 
to the binaries+platform configuration, you may want to take this up 
with anaconda. The upstream scipy project cannot fix it.

**Comment by mgscheer** [comment]
Alright, that makes sense. Nonetheless, would you be willing to tell me the platform/install that you have on which this code does not produce a seg fault? I might be able to redo my installation to be more like yours.

**Comment by ilayn** [comment]
@mgscheer Both works on 

Windows 10, Python 3.6.2, NumPy 1.13.1, SciPy 0.19.1 
Ubuntu 16.04 Python 3.6.1, NumPy 1.12 Scipy 0.19

On Windows wheel install, on Ubuntu built directly.

**Comment by mgscheer** [comment]
Thanks a lot to both of you!
