### ISSUE TITLE
nan result from multivariate_normal.cdf

### ISSUE THREAD

**Issue by bookcold** [scipy/scipy#7669]
The cdf function of multivariate_normal may not have the correct results when the dimension is **2**. I run the similar test in matlab and have a numerical result instead of nan. 

### Reproducing code example:
```
import numpy as np
from scipy.stats import multivariate_normal
x=np.random.randn(2)
mean=np.random.randn(2)
cov=np.abs(np.random.randn(2))
d=multivariate_normal.cdf(x, mean, cov)

```

### Error message:
```
d=nan
```

### Scipy/Numpy/Python version information:
```
('1.0.0.dev0+a8fe705', '1.13.1', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0))
```

**Comment by WarrenWeckesser** [comment]
Something is definitely wrong.  `pdf()` method works, but `cdf()` returns `nan`:

```
In [19]: scipy.__version__
Out[19]: '1.0.0.dev0+2651b14'

In [20]: from scipy.stats import multivariate_normal

In [21]: multivariate_normal.pdf([[0.25, 1]], [0,0], np.eye(2))
Out[21]: 0.093562364371238188

In [22]: multivariate_normal.cdf([[0.25, 1]], [0,0], np.eye(2))
Out[22]: nan
```

**Comment by WarrenWeckesser** [comment]
It appears to work with higher dimensions:

```
In [36]: multivariate_normal.cdf([[0.1, 0.2, 0.3]], [0, 0, 0], np.eye(3))
Out[36]: 0.19322122066473132
```

**Comment by WarrenWeckesser** [comment]
I see that the CDF method was added in https://github.com/scipy/scipy/pull/7017.

@asnelt: Could you take a look at this issue?

**Comment by asnelt** [comment]
Thanks for reporting this issue.
I looked into the problem and confirm that `cdf()` returns `nan` for bivariate input.
The problem appears to originate in the `mvnun` Fortran code by Alan Genz. The code uses a dedicated function to handle the bivariate case and causes problems when called with negative infinity as the lower bound. A quick and dirty fix would be to replace negative infinity with a number on line 451 in `_multivariate.py`:
Replace
```python
lower = np.full(mean.shape, -np.inf)
```
with e.g.
```python
lower = np.full(mean.shape, -1e100)
```

I am now working on a clean fix using `mvn.mvndst` instead on `mvn.mvnun`.
