### ISSUE TITLE
Scipy wav file format not understood error 

### ISSUE THREAD

**Issue by saurabhvyas** [scipy/scipy#7677]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

I had 2 wav files , that I had been using since the past , and they work perfectly with scipy wave read function , but when I added a new file , it threw following error 

```
Traceback (most recent call last):
  File "multidata.py", line 83, in <module>
    fs[i], audio[i] = wav.read(audio_filename[i])
  File "/home/saurabh/anaconda3/envs/py27/lib/python2.7/site-packages/scipy/io/wavfile.py", line 236, in read
    file_size, is_big_endian = _read_riff_chunk(fid)
  File "/home/saurabh/anaconda3/envs/py27/lib/python2.7/site-packages/scipy/io/wavfile.py", line 168, in _read_riff_chunk
    "understood.".format(repr(str1)))
ValueError: File format '<htm'... not understood.

```
I have tried recording with sox , arecord and audacity , also made sure there is no metadata , I have also tried all possible settings like mono , 16 bit , 16000 hertz etc , It doesn't work , even the settings matching with two wav files which the function is able to read 

### Reproducing code example:
```
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```
for i,j in enumerate(wav_files):
        print (i,j)
	audio_filename[i] = maybe_download(j + '.wav')
	print ( audio_filename[i])
	#print (audio_filename)
	target_filename[i] = maybe_download(j + '.txt')
	fs[i], audio[i] = wav.read(audio_filename[i])
	#print (audio[i])
# maybe_download is a function that checks if file exists locally , otherwise downloads it

### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```

**Comment by WarrenWeckesser** [comment]
From the error message `ValueError: File format '<htm'... not understood.`, I strongly suspect your file is *not* a WAV file, and is likely an HTML file.  Have you looked at the contents of the file?  Try viewing it in an editor.

**Comment by saurabhvyas** [comment]
I have played the .wav file in my audio player , it works fine

**Comment by saurabhvyas** [comment]
and yes , I have examined the contents of the file , they look perfectly fine , here is the header of the file causing problem 
```
RIFF<\D8\00\00WAVEfmt \00\00\00\
```
Also , please note that problem persists if I use .wav file from standard speech recognition datasets like AN4 dataset , so the problem is definitely not the source creating .wav file

**Comment by saurabhvyas** [comment]
some internal function was causing conflict , in other words , It's my own mistake , closing this

**Comment by WarrenWeckesser** [comment]
OK, thanks for following up.

**Comment by GreatJiweix** [comment]
I have also encountered this problem recently. Can you tell me how this problem is solved?

**Comment by saurabhvyas** [comment]
@GreatJiweix the file was corrupt, size was 0 bytes or something.

**Comment by BourAbdelhadi** [comment]
I have the same issue :(

**Comment by energyflowprogram** [comment]
I have the same issue. I did check the file size and it 557 Bytes

**Comment by ScarletMcLearn** [comment]
same issue

**Comment by AIGyan** [comment]
I am getting "ValueError: Unknown wave file format"

**Comment by Aliktk** [comment]
how to convert wav file into simple png ? I am trying librosa but not succesfull
