### ISSUE TITLE
"doc/sphinxext" is bumped when sphinx is updated

### ISSUE THREAD

**Issue by ilayn** [scipy/scipy#7685]
If sphinx package is updated independent from SciPy by some other package dependence, then this shows up as an unstaged file change in the repository

For example, my system got an update to 1.6.3 and since then I'm seeing the following after rebase on upstream.

![image](https://user-images.githubusercontent.com/1303842/28753974-8c4cee0c-753c-11e7-9b68-496590222edb.png)

in the `/doc/sphinxext`. Do we have a version dependency in the submodule?  

I'm just opening this issue for later reference. It can be closed right away.

**Comment by pv** [comment]
I think that must be something else, I don't see a way that it can occur because of system software updates.

You can do `git submodule update` to reset the submodule content to the commit it's supposed to be at.

**Comment by pv** [comment]
The actual issue is probably then the git rebase.
It won't update the submodule content automatically, so you need to follow it up with git submodule update.

**Comment by ilayn** [comment]
Ah, just came to post the same. Thanks.
