### ISSUE TITLE
Documentation error: scipy.special.ncfdtrinc docs list inputs in wrong order

### ISSUE THREAD

**Issue by alasdair-macleod** [scipy/scipy#7693]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
The function scipy.special.ncfdtrinc is described in the scipy docs ( https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.ncfdtrinc.html )
as: 

scipy.special.ncfdtrinc(p, f, dfn, dfd) = <ufunc 'ncfdtrinc'>
Calculate non-centrality parameter for non-central F distribution.
See ncfdtr for more details.

however, the c wrapper has the definition as:
double cdffnc5_wrap(double dfn, double dfd, double p, double f) 

the example at: https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.ncfdtr.html#scipy.special.ncfdtr

uses the values as described in the c wrapper.

### Reproducing code example:
```
import scipy.special as sp
sp.ncfdtrinc(0.5, 10, 10, 10)
nan
sp.ncfdtrinc(10, 10, 0.5, 10)
84.642032967908492
```

### Error message:
N/A

### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
0.19.1 1.13.1 sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
Pull request with a fix:  https://github.com/scipy/scipy/pull/7703
