### ISSUE TITLE
SuperLU does not respect perm_c="NATURAL" 

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#7700]
According to 2.5.1 of the SuperLU user's guide, the `ColPerm` option (set via `scipy.sparse.linalg.splu`'s `permc_spec` parameter) should accept the value:
`NATURAL`: use natural ordering (i.e., Pc = I).
According to this description, I would expect that the returned SuperLU object's `perm_c` array to list the indices of the columns in increasing order (i.e. identical to `np.arange(m)`, where `m` is the number of columns). Sometimes this is the case, but it does not hard to find situations for which this option does not appear to be respected. Note that the order produced is different from the produced using the other options; but it is not the "natural" ordering.

Really, I'd like to use `permc_spec="MY_PERMC"` , which appears to be a valid value, but the parameter for actually specifying `perm_c` does not appear to be exposed.
 
### Reproducing code example:
```python
np.random.seed(1)
m = 1000
p = 0.01
A = scipy.sparse.random(m,m,p)
f = splu(A, permc_spec = "NATURAL")
# f = splu(A, options={"ColPerm":"NATURAL"}) # no difference
print(np.allclose(f.perm_c,np.arange(m)))
print(f.perm_c[:10])
```

### Error message:
Output from code above:
```
False
[21 22  5 17  8 23 15 24  6 20]
```

### Scipy/Numpy/Python version information:
```
('0.19.0', '1.11.3', sys.version_info(major=2, minor=7, micro=11, releaselevel='final', serial=0))
```

**Comment by mdhaber** [comment]
I have been working with SuperLU and sparse matrices in general quite a bit lately and have many suggestions, one of which would be to remove the restriction:
```python
M, N = A.shape
if (M != N):
    raise ValueError("can only factor square matrices")  # is this true?
```
as the first paragraph of the introduction to the SuperLU user's guide states:
"The LU factorization routines can handle non-square matrices."
Should I propose these as enhancements?
Should I refrain from suggestions about sparse matrices themselves? (like add the sparse equivalent for `np.allclose()`?)

**Comment by pv** [comment]
Suggestions for enhancements are welcome (as always, with the understanding that it all runs on volunteer effort). Please file separate tickets, though.

**Comment by pv** [comment]
The arguments are parsed correctly. The question is then reading this code here:
https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/dsolve/_superluobject.c#L737
and comparing with the SuperLU manual. It's not clear it does the expected thing.

The input parameters with just the ColPerm option are
```
options  = {Fact = DOFACT, Equil = YES, ColPerm = NATURAL, Trans = NOTRANS, IterRefine = NOREFINE, 
  DiagPivotThresh = 1, SymmetricMode = NO, PivotGrowth = NO, ConditionNumber = NO, 
  RowPerm = NOROWPERM, ILU_DropRule = 1, ILU_DropTol = 0, 
  ILU_FillFactor = 4.6355710338275721e-310, ILU_Norm = (unknown: 10000), 
  ILU_FillTol = 6.9533558071986478e-310, ILU_MILU = 1000, 
  ILU_MILU_Dim = 6.9533558071946952e-310, ParSymbFact = (YES | unknown: 3859408010), 
  ReplaceTinyPivot = (YES | unknown: 32766), SolveInitialized = (unknown: 1441640144), 
  RefineInitialized = (YES | unknown: 21844), PrintStat = YES, nnzL = 21845, nnzU = 0, 
  num_lookaheads = 0, lookahead_etree = YES, SymPattern = NO}
```

**Comment by kevinrichardgreen** [comment]
I have a fix to this (workaround, really). Simply call
```python
f = splu(A, permc_spec = "NATURAL", diag_pivot_thresh=0, options={"SymmetricMode":True})
```
From 2.6 of SuperLU docs (http://crd-legacy.lbl.gov/~xiaoye/SuperLU/ug.pdf), `SymmetricMode` "prefers" the diagonal pivot, but since it's not specific as to how strongly it prefers this, setting `diag_pivot_thresh=0` as well should guarantee that no pivoting is done.

(Note it is strange that setting `diag_pivot_thresh=0` alone is not enough)
