### ISSUE TITLE
odeint documentation refers to t0 instead of t

### ISSUE THREAD

**Issue by raybsmith** [scipy/scipy#7724]
The ode integrator `scipy.odeint` should solve the equation
`dy/dt = f(y, t)`
according to the [tutorial](https://docs.scipy.org/doc/scipy/reference/tutorial/integrate.html#ordinary-differential-equations-odeint). However, the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.odeint.html#scipy.integrate.odeint) indicates that it is solving
`dy/dt = f(y, t0)`.
the `scipy.ode` function [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.ode.html#scipy.integrate.ode) correctly states that it is solving the first equation.

### Scipy/Numpy/Python version information:
```
0.19.1 1.11.3 sys.version_info(major=3, minor=6, micro=0, releaselevel='final', serial=0)
```

**Comment by Scapogo** [comment]
Hi,

 i can take care of this one if you want.

 Function has def odeint(func, y0, t, ...) so it migh be good to make documentation like dy/dt = func(y0, t, ...), right?
