### ISSUE TITLE
scipy.signal.kaiserord input args do not make sense as documented

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [scipy/scipy#7725]
Here's what the documentation says:

> scipy.signal.kaiserord(ripple, width)[source]
> 
> <snip>
>    ripple : float
> 
>    Positive number specifying maximum ripple in passband (dB) and minimum ripple in stopband.

When designing a lowpass digital filter, one normally specifies the maximum ripple in the passband and the minimum rejection in the stopband.  With this function, there is no way to specify how much rejection one gets in the stopband, and the filter design code is also apparently trying to limit stopband
ripple, which is something that no engineer would care about.  The documentation can't just be badly worded, because there would have to be another parameter to specify the stopband rejection.

**Comment by WarrenWeckesser** [comment]
Phillip, thanks for bringing this up.

I think there are two issues here:
* The documentation of `kaiserord()` is too terse.
* SciPy doesn't have a function for designing a FIR filter (including the automatic selection of the order of the filter) based on the desired pass band ripple and stop band rejection.

I'll address the first item here.  The second is an enhancement request, so I'll create a second github issue for that.

It looks like the explanation of the `ripple` argument of the function `kaiserord` needs some work.   The function `kaiserord` implements the empirical FIR filter design formulas developed by Kaiser in the late 60's and early 70's.  (The reference that I have handy is Sections 7.5.3 and 7.6 of the text "Discrete-Time Signal Processing" (3rd ed.) by Oppenheim and Schafer.)

For reference, here's a typical diagram of the design specification for a lowpass filter.

![figure_1](https://user-images.githubusercontent.com/321463/29256407-2f424102-8078-11e7-85d9-36789ba93673.png)

The graph of the magnitude of the frequency response of the filter must not enter the shaded area.  Ideally, a design method allows both δ<sub>p</sub> and δ<sub>s</sub> to be specified, as shown in the diagram.

In Kaiser's method, there is only one parameter that controls the passband ripple *and* the stopband rejection.  That is, Kaiser's method assumes  δ<sub>p</sub> = δ<sub>s</sub>. Let δ be that common value.  The stop band rejection in dB is -20*log<sub>10</sub>(δ).  This value (in dB) is the first argument of the function `kaiserord`.   One can interpret the argument `ripple` as the maximum deviation (expressed in dB) allowed in |A(ω) - D(ω)|, where A(ω) is the magnitude of the actual frequency response of the filter and D(ω) is the desired frequency response.  (That is, in the pass band, D(ω) = 1, and in the stop band, D(ω) = 0.)  In the script below, |A(ω) - D(ω)| is plotted in the third plot.

Kaiser developed an expression for β (the Kaiser window parameter) that depends on the stop band rejection, and also a formula for the filter order in terms of the stop band rejection and Δω, where Δω is the transition width between the pass and stop bands.

The Kaiser window design method, then, is to determine the length of the filter and the Kaiser window parameter β using Kaiser's formula (implemented in `scipy.signal.kaiserord`), and then design the filter using the window method with a Kaiser window (using, for example, `scipy.signal.firwin`):

    numtaps, beta = kaiserord(ripple, width)
    taps = firwin(numtaps, cutoff, window=('kaiser', beta), [other args as needed])

Adding a good example to the docstring of `kaiserord()` is on the SciPy to-do list (https://github.com/scipy/scipy/issues/7168).  In the meantime, here is a self-contained script that demonstrates the Kaiser method for a lowpass filter.  (I sent a similar script to the mailing list.)  I'll work on updating the docstring of `kaiserord()` to explain its arguments better and to include an example.  (And maybe I'll add a version of these comments and this code to the tutorial section of the SciPy documentation.)

```
import numpy as np
from scipy.signal import kaiserord, firwin
import matplotlib.pyplot as plt


def kaiser_lowpass(stop_db, cutoff, width, fs=1):
    """
    Design a lowpass filter using the Kaiser window method.
    """
    stop_db = np.abs(stop_db)

    # Convert to normalized frequencies
    nyq = 0.5*fs
    cutoff = cutoff / nyq
    width = width / nyq

    # Design the parameters for the Kaiser window FIR filter.
    N, beta = kaiserord(stop_db, width)
    N |= 1  # Ensure a Type I FIR filter.

    taps = firwin(N, cutoff, window=('kaiser', beta), scale=False)

    return taps, beta


# User inputs...
# Values in Hz
sample_rate = 1000.0
cutoff = 200.0
width = 25.0
stop_db = 60.0

# Filter design...
taps, beta = kaiser_lowpass(stop_db, cutoff, width, sample_rate)

# Compute and plot the frequency response...
n = 16384
h = np.fft.rfft(taps, n)
w = np.fft.rfftfreq(n, 1/sample_rate)

delta = 10**(-stop_db/20)

plt.subplot(3, 1, 1)
plt.plot(w, 20*np.log10(np.abs(h)))
upper_ripple = 20*np.log10(1 + delta)
lower_ripple = 20*np.log10(1 - delta)
lower_trans = cutoff - 0.5*width
upper_trans = cutoff + 0.5*width
plt.plot([0, lower_trans], [upper_ripple, upper_ripple], 'r',
         linewidth=1, alpha=0.4)
plt.plot([0, lower_trans], [lower_ripple, lower_ripple], 'r',
         linewidth=1, alpha=0.4)
plt.plot([upper_trans, 0.5*sample_rate], [-stop_db, -stop_db], 'r',
         linewidth=1, alpha=0.4)
plt.plot([lower_trans, lower_trans], [-stop_db, upper_ripple], color='r',
         linewidth=1, alpha=0.4)
plt.plot([upper_trans, upper_trans], [-stop_db, upper_ripple], color='r',
         linewidth=1, alpha=0.4)

plt.ylim(-1.5*stop_db, 10)
plt.ylabel('Gain (dB)')
plt.title(('Kaiser Window Filter Design\n'
           'Inputs: width %g Hz, stop band rejection %.1f dB  '
           '(δ = %g)\n'
           'Kaiser design: N = %d, $\\beta$ = %.3f') %
          (width, stop_db, delta, len(taps), beta),
          fontsize=10)
plt.grid(alpha=0.25)

plt.subplot(3, 1, 2)
plt.plot(w, 20*np.log10(np.abs(h)))
upper_ripple = 20*np.log10(1 + delta)
lower_ripple = 20*np.log10(1 - delta)
plt.plot([0, lower_trans], [upper_ripple, upper_ripple], 'r',
         linewidth=1, alpha=0.4)
plt.plot([0, lower_trans], [lower_ripple, lower_ripple], 'r',
         linewidth=1, alpha=0.4)
plt.plot([upper_trans, 1], [-stop_db, -stop_db], 'r', linewidth=1, alpha=0.4)
plt.plot([lower_trans, lower_trans], [-stop_db, upper_ripple], color='r',
         linewidth=1, alpha=0.4)
plt.plot([upper_trans, upper_trans], [-stop_db, upper_ripple], color='r',
         linewidth=1, alpha=0.4)

plt.ylim(2*lower_ripple, 2*upper_ripple)
plt.ylabel('Gain (dB)')
plt.xlim(0, cutoff)
plt.grid(alpha=0.25)

plt.subplot(3, 1, 3)
desired = w < cutoff
deviation = np.abs(np.abs(h) - desired)
deviation[(w >= cutoff-0.5*width) & (w <= cutoff + 0.5*width)] = np.nan
plt.plot(w, deviation)
plt.plot([0, 0.5*sample_rate], [delta, delta], 'r', linewidth=1, alpha=0.4)
plt.ylabel('|A(ω) - D(ω)|')
plt.grid(alpha=0.25)

plt.xlabel('Frequency (Hz)')
plt.tight_layout()
plt.show()
```
Here is the plot generated by the script.  Note that the filter violates the design requirement near the right end of the pass band.  (I don't think this is unusual for the Kaiser method.)

![figure_1](https://user-images.githubusercontent.com/321463/29257362-5fa23710-807f-11e7-9216-16088f174ce4.png)

**Comment by WarrenWeckesser** [comment]
@pmfeldman I created a pull request to update the documentation of `kaiserord` here: https://github.com/scipy/scipy/pull/7734.  Comment there if you have any suggestions to improve it.

**Comment by pmfeldman** [comment]
Hello Warren,

Thanks so much for this beautiful explanation!

I had not understood that Kaiser's method ties the passband ripple and
stopband rejection together.  I suspect that in most applications, a user
of this method will be overspecifying one to avoid underspecifying the
other, and that the length of the resulting filter will consequently be
somewhat greater than the minimum achievable with other, more modern design
methods.

I will review the proposed documentation and comment within the next few
days.

Yours,

Phillip

**Comment by WarrenWeckesser** [comment]
@pmfeldman wrote

>  I suspect that in most applications, a user of this method will be overspecifying one to avoid underspecifying the other, and that the length of the resulting filter will consequently be somewhat greater than the minimum achievable with other, more modern design methods.

Right, the method does *not* create an optimal filter.  In some tests that I ran, the length of the optimal filter was typically about 90% that of the Kaiser design, and in some cases it was down to almost 80%.

The method was an important contribution to DSP at the time, but computers have improved quite a bit in the last 50 years. :)  Designing an optimal filter is much easier now (though SciPy could use improvement in this area), so the Kaiser method is probably not as important as it once was.
