### ISSUE TITLE
[Not an issue but a question] Optimization improvement

### ISSUE THREAD

**Issue by roya0045** [scipy/scipy#7744]
I know that the minimize function output an array/vector to a function, but to optimize a function that takes in keyword args on top of the basic input(array or not) I made small function to implement that functionality that unpact and repact the dict. Would this be an useful addition to improve the usability of the optimisation process?

Thanks for all the hard work devs!

**Comment by rkern** [comment]
I recommend adding it to the SciPy Cookbook, at least:

https://scipy-cookbook.readthedocs.io/
https://github.com/scipy/scipy-cookbook

**Comment by roya0045** [comment]
Very well, I'll see what I can do!

**Comment by roya0045** [comment]
Pull request is pending, if anyone of you guys find it somewhat interesting, I'd be willing to implement it in scipy given some feedback/guidance.

**Comment by rgommers** [comment]
Link to PR: https://github.com/scipy/scipy-cookbook/pull/18
Rendered version: https://github.com/roya0045/scipy-cookbook/blob/e8f221c4a7da7fb8a5f49103aeb64ba812a4c06e/ipython/Kwarg%20optimization%20wrapper.ipynb

Imho it's fine for the cookbook, but not really suitable for integration into scipy itself.

**Comment by roya0045** [comment]
Understood!

**Comment by pv** [comment]
was added in the cookbook so closing
