### ISSUE TITLE
annoying pytest warnings showing up

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#7755]
On every test run:

    $ python -c "import scipy; scipy.test()"
    ========================================= test session starts ==========================================
    platform linux2 -- Python 2.7.6, pytest-3.1.3, py-1.4.34, pluggy-0.4.0
    rootdir: /home/rgommers/Code/tmp, inifile:
    plugins: xdist-1.13.1, timeout-0.5, cov-2.5.1, capturelog-0.7
    ...
    =========================================== warnings summary ===========================================
    :68
      'pytest_runtest_protocol' hook uses deprecated __multicall__ argument

    :171
      'pytest_runtest_makereport' hook uses deprecated __multicall__ argument

    None
      pytest_funcarg__caplog: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @pytest.fixture decorator instead.
      pytest_funcarg__capturelog: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @pytest.fixture decorator instead.

    -- Docs: http://doc.pytest.org/en/latest/warnings.html

Searching leads me to https://github.com/pytest-dev/pytest/issues/1684, but the info related to ``pytest-cov`` there is useless. 

On TravisCI this doesn't show up. Anyone else seeing this?

**Comment by pv** [comment]
I don't see those. Can you try upgrading to pytest 3.2.0?

**Comment by pv** [comment]
Also, maybe those come from the capturelog extension you have?

**Comment by rgommers** [comment]
Pytest 3.2.0 doesn't make a difference. Removing ``pytest-capturelog`` takes care of ``pytest_funcarg__caplog``. Unclear where other warning came from, but it was gone when I removed all other pytest extensions (some of which I'm pretty sure I didn't explicitly install).
