### ISSUE TITLE
tests require `nose`

### ISSUE THREAD

**Issue by ev-br** [scipy/scipy#7776]
Running scipy tests currently requires *both* pytest and nose due to the use of `np.testing.assert_raises`, which is literally

```
In [5]: print(inspect.getsource(assert_raises))
def assert_raises(*args, **kwargs):
   # snip docstring
     __tracebackhide__ = True  # Hide traceback for py.test
    nose = import_nose()
    return nose.tools.assert_raises(*args,**kwargs)
```
 
To reproduce:
```
$ pip uninstall nose
$ python runtests.py
```

To fix this, we need to either have a compat shim, or globally search-and-replace `assert_raises` to `pytest.raises`

**Comment by pv** [comment]
Thanks. It's indeed best to avoid compat shims.
