### ISSUE TITLE
Dendrogram doc typo

### ISSUE THREAD

**Issue by tmelorc** [scipy/scipy#7785]
From documentation of [scipy.cluster.hierarchy](https://github.com/scipy/scipy/blob/v0.14.0/scipy/cluster/hierarchy.py#L1894) sometimes is used `icoords` but I think that should be `icoord`. 

Also, the explanation for both `icoord` and `dcoord` are the same!

**Comment by vrishank97** [comment]
So all instances of icoords and dcoord should be replaced with icoord?

**Comment by tmelorc** [comment]
I think should be singular, not plural. So `icoord` and `dcoord`.

**Comment by rgommers** [comment]
@tmelorc you're linking to a very old version, 0.14.0. I missed that when labeling this issue. I think you mean that [here](https://github.com/scipy/scipy/blob/v0.14.0/scipy/cluster/hierarchy.py#L2086) the returned dict is documented as having a key ``icoords`` while actually it returns [icoord](https://github.com/scipy/scipy/blob/v0.14.0/scipy/cluster/hierarchy.py#L2156).

This has been fixed already in master.

**Comment by tmelorc** [comment]
So, the correct should be singular? Here
https://github.com/scipy/scipy/blob/master/scipy/cluster/hierarchy.py#L1951
it is also in plural. I'm not sure if I'm checking it correctly. If not, sorry.

Thanks for helping.

2017-09-22 20:16 GMT-03:00, Ralf Gommers <notifications@github.com>:
> @tmelorc you're linking to a very old version, 0.14.0. I missed that when
> labeling this issue. I think you mean that
> [here](https://github.com/scipy/scipy/blob/v0.14.0/scipy/cluster/hierarchy.py#L2086)
> the returned dict is documented as having a key ``icoords`` while actually
> it returns
> [icoord](https://github.com/scipy/scipy/blob/v0.14.0/scipy/cluster/hierarchy.py#L2156).
>
> This has been fixed already in master.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/scipy/scipy/issues/7785#issuecomment-331581249


-- 
Thiago de Melo

**Comment by perimosocordiae** [comment]
The name of the variables isn't important here, as long as the documentation matches the returned value. This was fixed, so I'm closing the issue.

**Comment by tmelorc** [comment]
Thanks a lot. I am glad I could help even with such small typo.
Regards.

Em 23/09/2017 12:16, "CJ Carey" <notifications@github.com> escreveu:
