### ISSUE TITLE
hosa(High Order Spectral Analysis) toolbox or package

### ISSUE THREAD

**Issue by ardeal** [scipy/scipy#7786]
Hi,

As we know, there is a famous toolbox in matlab:
hosa(High Order Spectral Analysis),

Is there a similiar toolbox/package in Scipy? or is it contained in any other Python package?

Thanks and Best Regards,
Ardeal

**Comment by rgommers** [comment]
Hi @ardeal, I suspect there's no direct equivalent in Python, certainly not in SciPy. 

Note that these kinds of usage questions are better asked on StackOverflow. Closing this issue because not a scipy bug.

**Comment by pv** [comment]
Searching on stackoverflow, google, and python package index is likely the best bet.
