### ISSUE TITLE
Using towncrier for release notes?

### ISSUE THREAD

**Issue by pv** [scipy/scipy#7793]
How about using https://pypi.python.org/pypi/towncrier for release notes?

In this approach, we add `doc/release/changes/<submodule>` folders, into which each PR that implements a feature adds a new file of format `<pr-number>.<suffix>` where `<suffix>` is `bugfix`, `trivial`, `feature`, ... etc.

At release time, these files are concatenated (with a jinja template) to form the release notes, and removed.

The good thing is that this eliminates merge conflicts in release notes, and perhaps reduces the work for the release manager when the burden of writing the content is pushed mainly to PR authors.

The approach is used e.g. by pytest.

**Comment by charris** [comment]
Worth exploring. Branches might be a problem as we would want have branch specific notes. I keep toying with the idea of making the release note directly part of the PR, perhaps in the description or somewhere in the comment threads, where they could be parsed out. That way they would be easily available for editing. Currently it is also possible to have a change referenced in several sections, which becomes more difficult with separate files because they need to be tagged ahead of time, so the release notes may come to more resemble the current changelog, which in numpy is now the contributors and PR links, rather than the current news summary.

Is there a way to add new sections to the github template for PRs? Is it a bad thing to become more github dependent?

**Comment by charris** [comment]
Oh, and would it make sense for the release notes to be in markdown rather than rst?

**Comment by pv** [comment]
I think it's possible to add new sections to the towncrier template, they're specified in the pyproject.toml file and correspond to subdirectories of the changes folder.

I'm not sure if branches are a problem --- when backporting etc., you can backport the `changes/` files at the same time. Forward porting file deletions is maybe more annoying, but maybe you can cherry-pick the commit that merged the files to do it more easily.

It's possible to add generation of `.. _gh-<number>:` link anchors to the template, so that you can link to items in the changelog from other items via standard format.

I kind of like the more low-tech approach, rather than parsing stuff from github based on their API.
iirc, github renders rst so you can also check the formatting there.

I don't have a strict preference for rst vs md, but I think there would need to be some reason why to change.

**Comment by ev-br** [comment]
FWIW, I'd worry about the entry barrier. We have lots of first-time and on-and-off contributors with non-SE backgrounds. There's at least anecdotal evidence that for many of them, setting up the dev environment etc takes more effort then a contribution itself. Efforts needed for learning git, figuring out the branching model and our git/github workflow can be justified as being of general use; this is more difficult to justify for a bespoke tool, even if it's used by pytest, or cpython (blurb) or even openstack (reno). These all still fall under "too localized" category. 

If we go this route, I quite strongly suspect we'll often end up needing to help contributors, not unlike we often need to help with rebases etc.

All that said, I can totally see how merge conflicts in the release notes can become a bottleneck in a project of CPython's size. I just don't think we are large enough, and that benefits do not outweigh the costs.

**Comment by pv** [comment]
The "parse github pull requests" suggestion is in https://github.com/scipy/scipy/pull/7794

**Comment by rgommers** [comment]
Thoughts:

- I'm not worried about the effort required for the release manager. He/she anyway needs to go through the contents and double check. Small amount of work in the grand scheme of things.
- A way to reduce merge conflicts would be helpful.
- Not sure about these many files to add and then merge back. Plus a file with the PR number has the practical annoyance that you don't know that PR number when writing the contents of the PR.

An alternative is to simply open an issue per release and collect release note fragments there.

**Comment by xoviat** [comment]
> If we go this route, I quite strongly suspect we'll often end up needing to help contributors, not unlike we often need to help with rebases etc.

It's not the end of the world if maintainers allow the scipy developers to write to their branch (which is enabled by default).

**Comment by rgommers** [comment]
> It's not the end of the world if maintainers allow the scipy developers to write to their branch (which is enabled by default).

It's not the end of the world, but it's still overhead for maintainers that I'd like to avoid.

**Comment by rgommers** [comment]
@pv's suggestion in gh-7794 is a lot better than the Towncrier solution, so no matter what we decide on gh-7794 I suggest we close this.

**Comment by rgommers** [comment]
Decision in https://github.com/scipy/scipy/pull/7794#issuecomment-329409333, closing this. Thanks all.
