### ISSUE TITLE
About scipy.optimize linprog

### ISSUE THREAD

**Issue by smlucasyoo** [scipy/scipy#7806]
I don't know why when using scipy.optimize linprog, the optimal solution of linear programming problem has negative solution even though I didn't use any boundary condition of variable.

for example, 

```python
res = linprog(c, A_eq = A_equation, b_eq = B_equation, method = 'Simplex', options = {"disp": True})
print(res.x)
```
gives the negative solution(default condition of bound is positive condition, as I know)

Also, I want to solve the above problem. So I wanted to use 'interior-point' method but the output is 

```
  File "C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\_linprog.py", line 995, in linprog
    raise ValueError('Unknown solver %s' % method)

ValueError: Unknown solver interior-point
```

What is the problem?

### Scipy/Numpy/Python version information:

My numpy version is 1.12.1-py36_0 and scipy version is 0.19.1.

**Comment by WarrenWeckesser** [comment]
@smlucasyoo wrote

> gives the negative solution ...

Can you create a runnable example that demonstrates the problem?  Without, we can only guess at the cause.


> So I wanted to use 'interior-point' method ...

The interior point method is new in scipy 1.0.0, which is not released yet.

**Comment by WarrenWeckesser** [comment]
Also, be sure you check that `res.success` is True before you try to use `res.x`.  That is, your code should do something like

    res = linprog(...)
    if res.success:
        print("Solution:", res.x)
    else:
        print("linprog failed:", res.message)

**Comment by smlucasyoo** [comment]
@WarrenWeckesser 

hmm 

okay , I'm writing the example. the comma "," will be missing in the example because I'm pasting it with the variables in Spyder Variable explorer. And this result has the True result with res.success.

c = [
-3.6659781990428217
-3.324637794200559
-3.053310569928337
-2.0108995424675524
-1.4711299677738399
-1.4016290103336762
-1.2982422527413497
-1.104728276095225
-1.0588530845331452
-1.02056397300811
-0.9620280758944858
-0.8626997818517789
-0.8414107427704896
-0.8408157485107669
]

A_equation = [
[-0.11487067588163154	-1.6467796909484775	-1.0324348194139048	-0.6068483719641149	1.5062521369214679	0.018301040466744356	-0.0688658728068457	-0.24919918575782277	0.7174803588746376	-0.17393315313301652	-0.08401213631876056	-0.6973687244855641	0.03246871335692403	-0.43784567917723977
0.7688991770876715	0.6667896660691858	-0.6568087823724723	0.5555461739044719	-1.8670886522590278	-1.6193765049748359	0.23786486450965494	-1.3215689198498186	-0.883760463177599	1.1154060478003989	-0.5693709442579135	0.05176359508782915	-0.6012143308388523	0.003009159781494939
-0.37584009538694774	-0.475476666724747	-0.4253153897675574	-0.07480150248927513	-0.0910590056938708	0.018769139356244458	-0.12224410949292178	0.15015329172677322	0.18131590551710197	0.13698144810130963	0.018181248173326767	-0.3453862790878447	-0.11570969551946006	-0.23859486375193026],
[0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0],
[0.0	0.0	1.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0],
[0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	1.0],
[0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	1.0	0.0	0.0	0.0],
[0.0	0.0	0.0	0.0	0.0	1.0	1.0	1.0	0.0	0.0	0.0	0.0	0.0	0.0],
[0.0	0.0	0.0	1.0	0.0	0.0	0.0	0.0	1.0	0.0	0.0	0.0	1.0	0.0],
[1.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0],
[0.0	1.0	0.0	0.0	1.0	0.0	0.0	0.0	0.0	1.0	0.0	1.0	0.0	0.0],
[0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0],
[0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0],
[1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0	1.0]]

B_equation = 
[-0.20268971859054316
-0.2942792795349866
-0.12564475535998562
0.0
0.07142857142857142
0.07142857142857142
0.07142857142857142
0.21428571428571427
0.21428571428571427
0.07142857142857142
0.2857142857142857
0.0
0.0
0.9999999999999997]

res = linprog(c, A_eq = A_equation, b_eq = B_equation, method = 'Simplex', options = {"disp": True})

res.x made the result(this res.success is True)

0.071429
-0.534693
0.071429
1.500000
0.579714
0.598710
-0.384425
0.000000
-1.285714
0.240693
0.071429
0.000000
0.000000
0.071429

**Comment by smlucasyoo** [comment]
@mdhaber can you help me? I'm really in emergency

**Comment by smlucasyoo** [comment]
@WarrenWeckesser 

I put all the "," above. Can you check the problem?

**Comment by pv** [comment]
Why is it expected that res.x[i]>=0 for all I?

29.8.2017 9.50 "smlucasyoo" <notifications@github.com> kirjoitti:

**Comment by WarrenWeckesser** [comment]
The last equality is redundant:

```
In [18]: A_equation[-1]
Out[18]: array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [19]: B_equation[-1]
Out[19]: 0.99999999999999967

In [20]: A_equation[3:-1].sum(axis=0)
Out[20]: array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [21]: B_equation[3:-1].sum()
Out[21]: 0.99999999999999989
```
Apparently the difference in the right-hand-side is enough to confuse `linprog`.

Remove the last row of `A_equation` and the last value of `B_equation`.

**Comment by WarrenWeckesser** [comment]
@pv wrote

> Why is it expected that res.x[i]>=0 for all I?

That is a default constraint of `linprog`.  You have to set the `bounds` argument to change that.

**Comment by smlucasyoo** [comment]
@WarrenWeckesser 

Wow thanks, I think it's working right now. Do I have to exclude every redundant rows when I solve LP via linprog?

**Comment by WarrenWeckesser** [comment]
I don't know.  The trivial equations in your rows 3, 11 and 12 don't seem to cause a problem, but the solver might use a preprocessor that identifies and removes those.  There are several open issues related to `linprog`: https://github.com/scipy/scipy/search?q=linprog&type=Issues&utf8=%E2%9C%93

**Comment by pv** [comment]
It may be some condition number issue, that singular constraints give large
error to results unless the error component on rhs is exactly zero.

29.8.2017 10.25 "Warren Weckesser" <notifications@github.com> kirjoitti:

**Comment by WarrenWeckesser** [comment]
@pv, yes, in fact if the interior point method is used, a warning is generated: `_linprog_ip.py:623: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.`

Here's the call in an ipython session:
```
In [4]: res = linprog(c, A_eq = A_equation, b_eq = B_equation, method = 'interior-point', options = {"disp": True})
/Users/warren/miniconda3scipy/lib/python3.5/site-packages/scipy-1.0.0.dev0+ab5ef39-py3.5-macosx-10.6-x86_64.egg/scipy/optimize/_linprog_ip.py:623: OptimizeWarning: A_eq does not appear to be of full row rank. To improve performance, check the problem formulation for redundant equality constraints.
  warn(redundancy_warning, OptimizeWarning)
Primal Feasibility  Dual Feasibility    Duality Gap         Step             Path Parameter      Objective          
1.0                 1.0                 1.0                 -                1.0                 -15.00351818245     
0.1736296567578     0.1736296567578     0.1736296567578     0.8349465751524  0.1736296567578     -5.393835444585     
0.02627879108882    0.02627879108882    0.02627879108882    0.8722612088149  0.02627879108882    -2.04911247856      
0.003814497113424   0.003814497113408   0.003814497113408   0.8632615900529  0.0038144971134     -1.888795282713     
7.371471518225e-05  7.371471546866e-05  7.371471546881e-05  0.9847850570502  7.371471508707e-05  -1.863578712557     
4.634049683517e-09  4.634050519902e-09  4.634050653311e-09  0.9999376829388  4.634050419005e-09  -1.863070291754     
2.321486574918e-13  2.314806881237e-13  2.314139796568e-13  0.9999500540431  2.317025089237e-13  -1.86307026024      
Optimization terminated successfully.
```
The answer matches (to within expected error tolerances) the result when the simplex method is used and the last redundant equality constraint is not included.

**Comment by mdhaber** [comment]
Thanks for your patience @smlucasyoo and for your quick responses @WarrenWeckesser, @pv. It sounds like your problem is resolved, @smlucasyoo?

As you've found, SciPy's simplex implementation tends to have trouble with redundant inequality constraints. The interior-point implementation would, too, but it has a routine to eliminate them in presolve. (That's where the `OptimizeWarning` mentioned by @WarrenWeckesser comes from.) Until the interior-point method becomes available with SciPy 1.0, there are a few things you can try if simplex fails.

- Look for redundancy by comparing the rank of `A_eq` with the number of rows. For small problems that have only a few redundancies, a simple way of identifying them is to look at a left singular vector corresponding with a singular value of 0. This singular vector provides a linear combination of rows that yields a zero row. This implies that any one of the rows with a corresponding nonzero entry in the singular vector can be eliminated from `A_eq` without affecting the optimal solution to the problem. (Repeat this procedure, removing only one row per SVD, until there are no more zero singular values. See the function _remove_redundancy [here](https://github.com/scipy/scipy/pull/7123/files#diff-095046bc6d3c8941bb0d7a3a1439d8c6) for an implementation.)
- Try setting the option `'bland':True`. This fixed the problem in #5400, which did not appear to be caused by a redundant equality constraint.
- You can also try [this](https://www.dropbox.com/sh/m7aaq3t2hvncz6h/AACxqAFe44a47nQ_apSMoTasa?dl=0) stand-alone version of the interior-point solver.

**Comment by AntonisKoutounids** [comment]
mdhaber I love you and whoever created the stand-alone version from the bottom of my heart. wish you the best bro. 
-An almost crazy (after searching my code for mistakes that were not there, but SIMPLEX wouldnt solve) person

**Comment by ilayn** [comment]
I'm putting a happy ending to this <strike>tale</strike>issue then since SciPy 1.0 is out

**Comment by mdhaber** [comment]
Haha thanks! Glad they were useful.

On Tue, Nov 28, 2017 at 9:34 AM, AntonisKoutounids <notifications@github.com
