### ISSUE TITLE
Suggestion: Give least_squares ability to fix variables

### ISSUE THREAD

**Issue by LindyBalboa** [scipy/scipy#7812]
So presently it is possible to pass `x0` (parameter guessing) and `bounds` to least squares. This works really great, unless you want to maintain a fixed value for a specific variable. Currently the options to combat this are to set the bounds to your desired values +- a very small deviation, or currying the function to pre-pass the variable. 

The first method is trustworthy, but cumbersome and verbose. The second method is much slicker, but changes the variables returned as `popt`. 

I suggest a sister array named `x0_fixed` which takes a a list of booleans and decides whether to treat the value in `x0` as fixed, or allow the bounds to behave as normal.

This does mean that you will still have to provide bounds for the fixed values. However, what this does allow is easy switching back in forth testing which parameters to fit, while leaving the true bounds, should you want to actually fit that parameter, intact.

**Comment by mirca** [comment]
Maybe one possible solution is to use lambda expressions?
For example, suppose ``fun`` takes three parameters, but you want to fix one and optimize for the others, then you could do something like:

```
my_func = lambda x1, x2: fun(x1, x2, x3=0) 
```

cheers

**Comment by rgommers** [comment]
Hi @LindyBalboa, thanks for the suggestion. We won't add a ``x0_fixed`` keyword to ``least_squares``. There are too many fitting functions which all behave similarly, so adding it just to ``least_squares`` would be very odd. More importantly, this would be a feature that's not often needed and has better alternatives (like a small wrapper with ``partial``).

**Comment by LindyBalboa** [comment]
As I said, in my case using partial was not an acceptable solution. Something that may be more reasonable for the fitting functions which maybe could have helped in my case was returning `popt` as a dictionary instead of a list.

At any rate, since posting this I stumbled upon the library [lmfit](https://lmfit.github.io/lmfit-py/) which suits my needs perfectly. Should anyone else be looking for higher level fitting (and also a very nice reporting function), this library is the way to go.

**Comment by andyfaff** [comment]
> More importantly, this would be a feature that's not often needed

This kind of thing is frequently required in curve fitting, along with a rich parameter handling capability. `lmfit` does pretty well in that regard.

**Comment by rgommers** [comment]
> This kind of thing is frequently required in curve fitting

I meant relative to amount of usage. Especially if you want to fix multiple parameters in turn and a one-liner with ``partial`` doesn't cut it, that is quite rare. Impossible to know for sure, but far below 1% of usage I bet.

**Comment by jbandstra** [comment]
I may well represent the "far below 1% of usage" for this, but I do find the topic useful and worked out what seems like a pretty simple solution. I don't see the issue addressed much online so I'll post my approach here. Perhaps the other handful of people in the far below 1% will find this of use.

Suppose that a function fun(x) is suitable for input to least_squares. Then define a new function as

`def hold_fun(var_x, hold_x, hold_bool):
    all_x = np.zeros_like(hold_bool, dtype=float)
    np.place(all_x, hold_bool, hold_x)
    np.place(all_x, ~hold_bool, var_x)
    return fun(all_x)
`

Then hold_fun can be pased to least_squares with hold_x and hold_bool as optional args. 

As a simple example, consider a linear regression problem (where, obviously, one wouldn't actually need to use least_squares). The original function, fun, could be:
`def fun(coefs, x_data, y_data):
   m, b = coefs
   y_model = m*x_data + b
   return y_model - y_data`

The function to hold either m or b could then be:
`def hold_fun(var_coefs, hold_coefs, hold_bool, x_data, y_data):
    all_coefs = np.zeros_like(hold_bool, dtype=float)
    np.place(all_coefs, hold_bool, hold_coefs)
    np.place(all_coefs, ~hold_bool, var_coefs)
    return fun(all_coefs, x_data, y_data)`

To run least squares with b held at zero (and an initial guess on the slope of 1.5) one could do
`hold_bool = np.array([False, True])
coefs_0 = np.array([1.5,0])
least_squares(hold_fun, coefs_0[~hold_bool], args=(coefs_0[hold_bool], x_data, y_data)`

I've found this approach to work well for some fairly complex "shared parameter" fitting exercises that become unwieldy with curve_fit or lmfit. It's also an advantageous approach for utilizing some of the other minimizer algorithms in scipy.optimize.

**Comment by ev-br** [comment]
@jbandstra thanks for sharing!
 it might be good to add your trick as a doc recipe somewhere in the scipy docs.
