### ISSUE TITLE
Build scipy documentation (Sphinx)

### ISSUE THREAD

**Issue by jomsdev** [scipy/scipy#7817]
I have been implementing some Randomized Numerical Linear Algebra methods for scipy  (#7122).

I have a production-ready implementation of the Clarkson-Woodruff Transformation and I have already integrated it in the scipy library. However, the pull request #7809  is failing because of some errors building the documentation. I already localizated the problem, it is in the documentation of the function because of the math mode. I have never used it before but I guess that I should follow the instructions of this page [Math support in Sphinx](http://www.sphinx-doc.org/en/stable/ext/math.html)

On one hand, I wonder if there is some particular problem with the scipy sphinx or the official documentation of sphinx will work. On the other hand, which is the command for building the documentation in my computer? (it will save a lot of commits 👍 )

Thanks

**Comment by larsoner** [comment]
CircleCI and the REFGUIDE_CHECK Travis build are both happy in #7809...?

But in any case, you can use `./runtests.py --refguide-check` to check the REFGUIDE stuff.

For the docs, as shown on the [CircleCI run page](https://circleci.com/gh/scipy/scipy/4101?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) and the [circle.yml](https://github.com/scipy/scipy/blob/master/circle.yml#L12) file that the command it uses is:
```
$ python -u runtests.py -g --shell -- -c 'make -C doc PYTHON=python html-scipyorg'
```

**Comment by rgommers** [comment]
Closing this, let's continue on gh-7809 if needed.
