### ISSUE TITLE
Scipy mmwrite incorrectly writes the zeros for skew-symmetric, array matrices

### ISSUE THREAD

**Issue by william-dawson** [scipy/scipy#7836]
When you have a dense, skew-symmetric matrix, and you write it to file using scipy.io.mmwrite and specify that it is a skew-symmetric matrix, the resulting file incorrectly lists the zeros on the diagonal. According to the [matrix market format documentation](http://math.nist.gov/MatrixMarket/formats.html#MMformat), page 9:

> Only entries below the main diagonal
> are stored in the file. The entries on the main diagonal are zero and 
> those above the main diagonal are known by symmetry. 

### Reproducing code example:
```
from scipy.io import mmwrite
matrix = [[0, 1], [-1, 0]]
mmwrite("test.txt", matrix, symmetry="skew-symmetric")
```

### Error message:
The resulting matrix is:
```
%%MatrixMarket matrix array integer skew-symmetric
%
2 2
0
-1
0
```

### Scipy/Numpy/Python version information:
```
0.19.1 1.13.1 sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)
```

**Comment by Tokixix** [comment]
@ilayn Can I (or should I) fix this?

**Comment by ilayn** [comment]
If nobody has mentioned a clear interest you can pick up any issue without asking @tokixix 

 Thank you for effort and interest on the issues so far by the way.

**Comment by Tokixix** [comment]
No problem @ilayn ! As You can see, I've just created PR for this one.

**Comment by pv** [comment]
Interestingly, the matlab codes here https://math.nist.gov/MatrixMarket/mmio/matlab/mmiomatlab.html have the same issue, but the fortran code https://math.nist.gov/MatrixMarket/mmio/f/mmiof77.html not.

Merged the PR, assuming the behavior of the fortran code is the one intended in the spec.
