### ISSUE TITLE
Help with hypergeometric test

### ISSUE THREAD

**Issue by zfrenchee** [scipy/scipy#7837]
I'd like to use `stats.hypergeom` to implement a hypergeometric test for significance. However, using the recommended way, I'm getting an odd result. 

Say I have a bag with 19275 balls, 4 of which are red, the rest of which are black, and I draw 2880 balls without replacement. I happen to draw all 4 red balls. 

```
from scipy.stats import hypergeom
hypergeom.sf(4, 19275, 4, 2880)
--> 0.0
hypergeom.cdf(4, 19275, 4, 2880)
--> 1.0
```

This doesn't make sense, since although you've collected all 4 red balls, there's a probability you collect them by chance. Using an [online hypergeometric test utility](https://www.geneprof.org/GeneProf/tools/hypergeometric.jsp),  I arrive instead at: 

> Probability of drawing 4 successes or more from a sample of 2880:
> **P(X >= 4) = 0.0004975336447094944.**
> Probability of drawing exactly 4 successes from a sample of 2880:
> **P(X = 4) = 0.0004975336447094944.**

There doesn't seem to be much documentation online about how to implement a hypergeometric test using this library, and what I've found is occasionally inconsistent, so an authoritative, conclusive answer, perhaps in the hypergeom docs, would probably be helpful. 

This might also just be an issue of precision (though I doubt it). However if that's the case, might any of the functions related to hypergeom in [`scipy.special`](https://docs.scipy.org/doc/scipy/reference/special.html#hypergeometric-functions) help with this? No clue, just a thought. 

@ev-br hoping you're willing to take a look at this since you were involved in #6840

**Comment by WarrenWeckesser** [comment]
The inequality in the definition of the survival function is a strict inequality, and with only 4 red balls, P(X > 4) is 0, as expected.

**Comment by pv** [comment]
>>> hypergeom.sf(3, 19275, 4, 2880)
0.00049753364470522961
Iow, looks as expected.

**Comment by zfrenchee** [comment]
Thanks!
