### ISSUE TITLE
p-values in scipy.stats.pearson

### ISSUE THREAD

**Issue by CommonClimate** [scipy/scipy#7840]
`scipy.stats.pearson` returns  p-values that are often suspiciously low (e.g., 1e^{-34}). I would argue that on a computer with numerical precision `eps` it is meaningless to quote numbers below `eps`. 
Second, most people only care about p-values being below some threshold, say 1e^{-3}. Would it be possible to return more meaningful p-values, e.g. the actual value until that threshold, and "p < threshold" below that? By default I recommend the threshold to be 1e^{-3}, though it should be customizable. Thanks for considering.

**Comment by ilayn** [comment]
You can use `np.max(values, threshold)` for this functionality.

**Comment by josef-pkt** [comment]
Truncating the precision is a display issue, and there is no reason at all for a computational library to truncate the values. (I think also R and other packages truncate for the print/summary, but keep the full precision internally.)

Distribution that defined a sf properly, like normal and many others, do have large precision in the upper tail. For other distribution the threshold or precision will be limited by the numerical implementation, e.g. if 1-cdf is used.

In cases with large multiple testing correction these small p-values are needed. (The correlation matrix for 5000 variables would have more than 12 million p-values.)

**Comment by CommonClimate** [comment]
I fully understand the need to keep numerical precision intact. The idea was to restrict the display precision, but I suppose the SciPy mindset is to assume that users know what they are doing (sometimes a rather optimistic mindset).  I'm quite capable of truncating myself, but was wondering if any thought should be put into the default reporting of the p-values. Apparently not! Thanks for your time.

**Comment by josef-pkt** [comment]
I think in scipy the main issue for this is that there is no "reporting". In most or all cases the result is shown with whatever default precision has been set, eg. for displaying numpy arrays or python floats.
The choice of display/print precision would be relevant if specific `__str__` or `__repr__` are defined.

(Even then, personally I don't like truncated p-values. In statsmodels `summary` we have a low display precision at a few decimals but still show the g notation for very small values, like 1.7e-13, which I find more informative than "<0.001" or similar thresholds.)
