### ISSUE TITLE
Agree on and merge a SciPy Code of Conduct 

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#7845]
First attempt (closed) in gh-7764.

Start of mailing list thread: https://mail.python.org/pipermail/scipy-dev/2017-August/022044.html

Next steps: 
- continue discussion on mailing list
- introduce a new draft based on feedback received so far
- hold a public call as an extra venue for people to give input
- iterate on document and merge.

This is a blocker for SciPy 1.0

**Comment by xoviat** [comment]
I would highly recommend the [pypa code of conduct](https://www.pypa.io/en/latest/code-of-conduct/). It's direct and to-the-point.

**Comment by matthew-brett** [comment]
@xoviat - PyPA's code of conduct is basically the same as the Contributors Covenant 1.2 - see mailing list for more discussion.

**Comment by rgommers** [comment]
Update:

- there was agreement between participants on the mailing list to start from the Apache CoC and add on more specific reporting/enforcement guidelines at the end (based on the Jupyter CoC & Contributor Covenant).
- PR for that is gh-7963
