### ISSUE TITLE
why still random after set minit?

### ISSUE THREAD

**Issue by hoyeunglee** [scipy/scipy#7846]
kmeans2(testing1,5, minit='points')

after set init as points, it still different in every run
why still random after set minit?

**Comment by rkern** [comment]
```
minit : str, optional
    Method for initialization. Available methods are 'random',
    'points', and 'matrix':
...
    'points': choose k observations (rows) at random from data for
    the initial centroids.
```

It's still randomized, just pulled randomly from the data. If you want a non-random method, use `method='matrix'` and specify `k` as the specific non-random array of points.

**Comment by rgommers** [comment]
Question answered, so closing this issue. Thanks @rkern.
