### ISSUE TITLE
Unable to Install Scipy Package in my machine

### ISSUE THREAD

**Issue by anilkumarmavooru** [scipy/scipy#7849]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
In Python GUI when we enter pip install scipy, It displays error message as "Unable to install the SciPy Package.
 We have downloaded the package from Sourceforge site and when are installing the package it is saying Python 3.4 code is missing and when we click on ok it is asking enter python directory path.

Please help me to resolve this issue

### Reproducing code example:
```
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```

### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```

**Comment by rgommers** [comment]
@anilkumarmavooru your question is a bit unclear. What GUI, and what did you download from SourceForge?

Note that SourceForge is not used anymore, you can get the latest version for all Python and OS versions from PyPI. ``pip install scipy`` should work out of the box. If not, please provide the full output of running that command.

Not a scipy issue, so closing this.
