### ISSUE TITLE
sparse indexing regression for Sage Integers

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#7860]
As reported by @jdemeyer on gh-6936. Due to https://github.com/numpy/numpy/pull/9691.

@jdemeyer is there a Sage bug report to link to?

And when you say "broke Sage", is it one test failure or a major issue?

**Comment by jdemeyer** [comment]
> And when you say "broke Sage", is it one test failure or a major issue?

OK, "broke Sage" is a big exaggeration. In fact, nothing in Sage itself is broken. What is broken is user code using SciPy `lil_matrix()` (and possibly other functions) with Sage Integers.

Downstream: https://trac.sagemath.org/ticket/23572#comment:12

**Comment by jdemeyer** [comment]
I made a specific downstream bug report: https://trac.sagemath.org/ticket/23867

**Comment by rgommers** [comment]
Thanks, that helps. We should still fix that, but if it misses 1.0.0 and ends up in 1.0.1 then that's not the end of the world it seems.

**Comment by jdemeyer** [comment]
Fix what? Fix it in SciPy or NumPy? I consider it a bug in `np.isscalar()`, that's why I submitted https://github.com/numpy/numpy/pull/9691

**Comment by rgommers** [comment]
The numpy PR looks fine, but scipy supports numpy versions back to 1.8.2. So if this is an important use case for you, then it may make sense to put the fixed ``isscalar`` into ``scipy._lib._numpy_compat.py``.

**Comment by jdemeyer** [comment]
Honestly, this backwards compatibility with older NumPy versions is not important for Sage. So, add the backported code to SciPy if you want, but it's fine if you don't.

**Comment by rgommers** [comment]
Okay, in that case let's make it easy for ourselves and close this again.
