### ISSUE TITLE
AttributeError: 'module' object has no attribute 'signal'

### ISSUE THREAD

**Issue by caibojun** [scipy/scipy#7873]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

### Reproducing code example:
```
import scipy as sp
import numpy as np
import cv2
image=cv2.imread('image.jpg',0)
psf=np.array([[1,2,3],[4,5,6],[7,8,9]])
convolved=np.uint8(sp.signal.convolve(image,psf))
```

### Error message:
```
AttributeError: 'module' object has no attribute 'signal'
```

### Scipy/Numpy/Python version information:
```
('0.17.0', '1.11.0', sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0))
```
I can't use the code `sp.signal.convolve` after I killed the terminal of my Ubuntu System once before,then I uninstall scipy and install it again,it didn't work.But with run the code 'sp.test()', `signal.convolve` can work perfectly,however, `sp.test()` really costs my time!

**Comment by rgommers** [comment]
You need to import like this:

    from scipy import signal
    signal.convolve(...)
