### ISSUE TITLE
linalg.svd output is non-deterministic on Windows 32bit

### ISSUE THREAD

**Issue by johny-c** [scipy/scipy#7878]
Hi, I'm writing a PR for scikit-learn and from time to time I get a failure on Windows 32bit. The only potential cause of failure is the `scipy.linalg.svd` calls used in `sklearn.decomposition.pca`. And indeed I find a very strange behavior coming from `scipy.linalg.svd` : I wrote a test (see [https://github.com/johny-c/scikit-learn/blob/win32/sklearn/neighbors/tests/test_win32.py](url)) that calls `svd` two times consecutively on the exact same input and compares the resulting decompostion matrices. Most of the time they are equal as they should. But every now and then - I still cannot find any pattern on the frequency - they are not. See [https://github.com/johny-c/scikit-learn/blob/win32/sklearn/neighbors/tests/test_win32_digits.out](url) and [https://github.com/johny-c/scikit-learn/blob/win32/sklearn/neighbors/tests/test_win32_iris.out](url). It seems like the output of the LAPACK `dgesdd` routine is not 100% deterministic in Windows 32 bit.

### Reproducing code example:

```
import numpy as np
from sklearn.utils.validation import check_X_y
from sklearn.utils.testing import assert_allclose
from sklearn.utils.testing import assert_array_equal
from sklearn import datasets
from scipy import linalg
from sklearn.utils.extmath import svd_flip

rng = np.random.RandomState(0)
digits = datasets.load_digits()
perm = rng.permutation(digits.target.size)
digits.data = digits.data[perm]
digits.target = digits.target[perm]

def test_scipy_svd():
    X_init = digits.data
    y_init = digits.target

    # X_init = iris.data
    # y_init = iris.target
    X, y = check_X_y(X_init, y_init, ensure_min_samples=2)
    U1, S1, V1 = linalg.svd(X, full_matrices=False)
    # flip eigenvectors' sign to enforce deterministic output
    U1, V1 = svd_flip(U1, V1)

    U2, S2, V2 = linalg.svd(X, full_matrices=False)
    U2, V2 = svd_flip(U2, V2)

    assert_allclose(S1, S2)
    assert_allclose(U1, U2)
    assert_allclose(V1, V2)
```

### Error message:

Traceback (most recent call last):
  File "C:\Users\Joe\Anaconda2\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\Joe\projects\python2\scikit-learn\sklearn\neighbors\tests\test_win32.py", line 30, in test_scipy_svd
    assert_allclose(U1, U2)
  File "C:\Users\Joe\Anaconda2\lib\site-packages\numpy\testing\utils.py", line 1411, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "C:\Users\Joe\Anaconda2\lib\site-packages\numpy\testing\utils.py", line 796, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 3.12413049527%)
 x: array([[  3.209578e-02,   2.183222e-02,  -2.281640e-02, ...,
          0.000000e+00,   0.000000e+00,   9.931736e-01],
       [  2.288146e-02,   2.978713e-03,  -1.959516e-02, ...,...
 y: array([[  3.209578e-02,   2.183222e-02,  -2.281640e-02, ...,
         -0.000000e+00,   0.000000e+00,   9.931736e-01],
       [  2.288146e-02,   2.978713e-03,  -1.959516e-02, ...,...

### Scipy/Numpy/Python version information:

0.19.1, 1.12.1, 2.7.13
and 
0.16.0, 1.9.3, 2.7.13
and
0.16.0, 1.9.3, 3.5.3

**Comment by pv** [comment]
Floating-point reproducibility is generally not guaranteed (see e.g. intel compiler manuals) on any platform, even for code in the same program can give different results due to e.g. data alignment, unless you take special care with library and compiler options, as it depends on things such as compiler optimizations. This is not generally considered a bug, and correct code should not assume it. It is a speed/precision tradeoff, and official binaries provided by scipy project do not ensure 100% fp reproducibility.

I don't know which binaries you are using, but it's possible e.g. with MKL it's possible to toggle a high-precision mode.

**Comment by larsoner** [comment]
For others who might run into GESDD problems (which could possibly be related to this) -- I have had reproducibility problems with GESDD and MKL on Linux (and confirmed by others on Linux and OSX) depending on CPU architecture, where it can raise LinAlgError on valid (finite) matrices:

https://github.com/ContinuumIO/anaconda-issues/issues/695
https://software.intel.com/en-us/comment/1869912

The problem can at least sometimes be mitigated by changing the number of threads MKL uses. However, unlike this bug -- which seems to fit in the numerical precision category -- solving the SVD vs raising a LinAlgError is beyond numerical precision, so it's an MKL bug.

However, more recently I have begun to suspect that MKL's `gesdd` *might* produce incorrect (i.e., sometimes beyond numerical precision incorrect) results *without* producing LinAlgError:

https://github.com/mne-tools/mne-python/issues/4922#issuecomment-368920709

Still need to isolate a single call, though, to make sure that it's not just numerical inaccuracies being magnified by subsequent processes.
