### ISSUE TITLE
cKDTree.query_ball_tree returns different results than KDTree.query_ball_tree with extreme outliers

### ISSUE THREAD

**Issue by beckernick** [scipy/scipy#7883]
Hi Scipy Team,

The Cython implementation of `query_ball_tree` seems to behave unexpectedly with arrays that include extreme outlier data. The output for the first block of code is the same using both the cKDTree and KDTree implementations. The output in the second block of code (in which an extreme outlier is introduced) returns different output for the two implementations. The output from  `cKDTree.query_ball_tree` appears to violate the maximum distance requirement set by `r` for output indices. 

In the Cython implementation example, changing `array1[10000]` to `np.array([1e7, 1e7])` displays unexpected behavior. A few additional tests suggest the outlier threshold that causes unexpected behavior may depend on the range and/or distribution of the data in the arrays.

### Reproducing code example:
```
# Expected behavior

import numpy as np
from scipy.spatial import KDTree, cKDTree

np.random.seed(12)
rowcount = 25000

lat1 = np.random.uniform(41,42, rowcount)
long1 = np.random.uniform(-85,-88, rowcount)
lat2 = np.random.uniform(41,42, rowcount)
long2 = np.random.uniform(-85,-88, rowcount)

array1 = np.array(list(zip(lat1, long1)))
array2 = np.array(list(zip(lat2, long2)))

tree_c1 = cKDTree(array1)
tree_c2 = cKDTree(array2)

results_c = tree_c2.query_ball_tree(tree_c1, r=.0001,p=2, eps=0)
nonzero_indices_c = np.nonzero(results_c)[0]
print(nonzero_indices_c)
print(np.array(results_c)[nonzero_indices_c])

tree_1 = KDTree(array1)
tree_2 = KDTree(array2)

results = tree_2.query_ball_tree(tree_1, r=.0001,p=2, eps=0)
nonzero_indices = np.nonzero(results)[0]
print(nonzero_indices)
print(np.array(results)[nonzero_indices])


# Unexpected Behavior

array1 = np.array(list(zip(lat1, long1)))
array2 = np.array(list(zip(lat2, long2)))

array1[1000] = [1e7, 1e7]
tree_c1 = cKDTree(array1)
tree_c2 = cKDTree(array2)

results_c = tree_c2.query_ball_tree(tree_c1, r=.0001,p=2, eps=0)

nonzero_indices_c = np.nonzero(results_c)[0]
print(nonzero_indices_c)
print(np.array(results_c)[nonzero_indices_c])

tree_1 = KDTree(array1)
tree_2 = KDTree(array2)

results = tree_2.query_ball_tree(tree_1, r=.0001,p=2, eps=0)
nonzero_indices = np.nonzero(results)[0]
print(nonzero_indices)
print(np.array(results)[nonzero_indices])

```

### Scipy/Numpy/Python version information:
```
0.19.1 1.13.1 sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)
```

**Comment by peterbell10** [comment]
This doesn't reproduce on the latest master. Digging though the history led to gh-9892 which improved accuracy in case of such outliers. Running the example before and after that commit confirmed the issue was fixed there.
