### ISSUE TITLE
doc unclear at https://docs.scipy.org/doc/numpy/reference/generated/numpy.interp.html

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#7884]
"Returns the one-dimensional piecewise linear interpolant to a function" doesn't look right - I think it should be "Returns the one-dimensional piecewise linear interpolant to a function, evaluated at x".

Also, "The x-coordinates of the interpolated values" should be "The x-coordinates of the points at which to calculate the interpolated values".

**Comment by pv** [comment]
Please report this to numpy's issue tracker: 
https://github.com/numpy/numpy/issues
