### ISSUE TITLE
Scipy 1.0.0b1 prints spurious DVODE/ZVODE/lsoda messages

### ISSUE THREAD

**Issue by certik** [scipy/scipy#7888]
I tested the scipy 1.0.0b1 release and everything seems to work, all tests pass. But when I exited the interpreter, it printed spurious messages into the terminal. That seems like a bug. I don't know if they should not be printed at all, or printed when they happened, but the current solution seems confusing.

### Reproducing code example:
```
>>> import scipy
>>> scipy.test()
...
ext/miniconda2/envs/scipy_test/lib/python3.6/site-packages/scipy/stats/tests/test_rank.py ............
ext/miniconda2/envs/scipy_test/lib/python3.6/site-packages/scipy/stats/tests/test_stats.py ................................................................................................................x....................................................................................................................................................
ext/miniconda2/envs/scipy_test/lib/python3.6/site-packages/scipy/stats/tests/test_tukeylambda_stats.py ...

============================= 577 tests deselected =============================
 12061 passed, 1373 skipped, 577 deselected, 73 xfailed, 5 xpassed in 520.78 seconds 
True
>>> 
```
Everything looks good. Then I pressed Ctrl-D and it printed:
```
 DVODE--  At current T (=R1), MXSTEP (=I1) steps   
       taken on this call before reaching TOUT     
      In above message,  I1 =         1
      In above message,  R1 =  0.2569611864708D-12
 ZVODE--  At current T (=R1), MXSTEP (=I1) steps   
       taken on this call before reaching TOUT     
      In above message,  I1 =         1
      In above message,  R1 =  0.2569611864708D-12
 lsoda--  at current t (=r1), mxstep (=i1) steps   
       taken on this call before reaching tout     
      in above message,  i1 =         1
      in above message,  r1 =  0.9999999999999D-09
```

That's confusing and it shouldn't be printed by default.

I am using Ubuntu 16.04 and a conda environment with `python=3.6` and `numpy` installed.

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.0.0b1 1.13.1 sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)
```

**Comment by matthew-brett** [comment]
@njsmith - I seem to remember us hitting something similar when testing OpenBLAS in BIDS one day - do you remember the details?

**Comment by pv** [comment]
I think those are printed directly out from Fortran code (maybe only when disp=True or somesuch).

Is this using the manylinux wheels? I think pytest normally suppresses also C stdout, but the manylinux wheels ship their own libgfortran and maybe that's an issue.

**Comment by certik** [comment]
@pv, yes I pip installed it, and it installed the binary wheels.

**Comment by njsmith** [comment]
@matthew-brett Sorry, I don't remember this at all :-)

**Comment by andyfaff** [comment]
This was happening for me on macOS.

**Comment by matthew-brett** [comment]
@njsmith - I was thinking of this numpy issue : https://github.com/numpy/numpy/issues/7545 - I'm afraid I didn't read it closely ...

**Comment by rgommers** [comment]
> I think those are printed directly out from Fortran code (maybe only when disp=True or somesuch).

Yes. Here's one, from [lsoda.f](https://github.com/scipy/scipy/blob/master/scipy/integrate/odepack/lsoda.f#L1460):

    c-----------------------------------------------------------------------
    c block h.
    c the following block handles all unsuccessful returns other than
    c those for illegal input.  first the error message routine is called.
    c if there was an error test or convergence test failure, imxer is set.
    c then y is loaded from yh, t is set to tn, and the illegal input
    c counter illin is set to 0.  the optional outputs are loaded into
    c the work arrays before returning.
    c-----------------------------------------------------------------------
    c the maximum number of steps was taken before reaching tout. ----------
     500  call xerrwv('lsoda--  at current t (=r1), mxstep (=i1) steps   ',
         1   50, 201, 0, 0, 0, 0, 0, 0.0d0, 0.0d0)
          call xerrwv('      taken on this call before reaching tout     ',
         1   50, 201, 0, 1, mxstep, 0, 1, tn, 0.0d0)

Tests are passing though, so we should be able to silence this (unlike some of the messages that are coming out of ATLAS).

**Comment by rgommers** [comment]
Same on 32-bit Linux + Python 2.7.

**Comment by WarrenWeckesser** [comment]
It is the test [`ODECheckParameterUse.test_warns_on_failure`](https://github.com/scipy/scipy/blob/e499e5fdebc8c145c4423e313d5b7e6362df3475/scipy/integrate/tests/test_integrate.py#L614-L620) in [`scipy/integrate/tests/test_integrate.py`](https://github.com/scipy/scipy/blob/master/scipy/integrate/tests/test_integrate.py) that triggers the spurious output.  When I comment out that test, I don't get the spurious output when leaving the interactive python shell after running `scipy.test()`.

I haven't looked any further into why the output occurs.  It seems strange that I don't get the spurious output when I run `import scipy.integrate; scipy.integrate.test()` instead of running the full `scipy` test suite.

**Comment by rgommers** [comment]
I'm intending to just skip this test on 1.0.x if we don't get around to fixing things within the next 3 days. Tests should be silent, but this is not critical to resolve properly for 1.0.0.

**Comment by rgommers** [comment]
Had a look at this, and it's a bit puzzling why the warning only shows up with the 1.0.0b1 wheels, it should always be there. Reasoning:

- ``test_warns_on_failure`` is the cause.
- ``assert_warns(UserWarning, solver.integrate, pi)`` passes, so warning from the Python code are being emitted. See [here](https://github.com/scipy/scipy/blob/master/scipy/integrate/_ode.py#L1263) for lsoda for example.
- That means ``istate = -1`` for ``lsoda`` (checked from the error message caught by ``assert_warns``). 
- ``istate = -1`` is set in the place I linked above in ``lsoda.f``. It does ``call xerrwv('lsoda--  at current t ...`` etc right before setting ``istate``. 
- So ``xerrwv`` is always called, but somehow the way the 1.0.0b1 manylinux wheels are compiled makes it show up now.

All the warnings in the Fortran code should simply be removed - the Python code calling it already emits ``UserWarning``s with the correct message. I'm not sure I want to backport that change though, just skipping the test on 1.0.x seems harmless.

**Comment by rgommers** [comment]
Test skipped for 1.0.x in gh-7938
