### ISSUE TITLE
Is it relative precision or error?

### ISSUE THREAD

**Issue by FrancisYizhang** [scipy/scipy#7892]
In scipy.linalg.interpolative, the statement of line 831 and line 852 is opposite. Which one is correct? Could you unify the meanning of eps_or_k in all of SVD.

**Comment by rgommers** [comment]
The SVD can be computed to any relative precision or rank (depending on the
    value of `eps_or_k`).

and

    eps_or_k : float or int
        Relative error (if `eps_or_k < 1`) or rank (if `eps_or_k >= 1`) of
        approximation.

I don't see those as opposite. Can you explain your question in more detail?

**Comment by FrancisYizhang** [comment]
Dear @rgommers 

  Please read scipy.linalg.interpolative line 851 and scipy.linalg._interpolative_backend line 452, the same value, however, it is opposite statement.

**Comment by pv** [comment]
"Relative error" and "Relative precision" mean the same thing.

**Comment by rgommers** [comment]
Line 452 in ``_interpolative_backend.py``:

    :param eps:
        Relative precision.

(it would be helpful to include code, line numbers change over time and saves us work)

Those do mean the same thing. There's no issue, so closing.
