### ISSUE TITLE
DOC: Window functions

### ISSUE THREAD

**Issue by larsoner** [scipy/scipy#7898]
It sounds like we have converged on a plan to move the window functions from `scipy.signal` to `scipy.signal.windows`. Should we do something about this for 1.0?

My proposal is to start moving toward deprecation in the `signal` namespace by changing the `windows` section of the [refguide](http://scipy.github.io/devdocs/signal.html) to make it clear all window functions live in the `scipy.signal.windows` namespace. We can either do this with a note at the top of the `Windows` section, or by prepending `windows.` to everything like `windows.hamming`. I don't like the latter but I think the former might be missed by people.

We could also deprecate direct access to e.g. `signal.hamming` with a DeprecationWarning if we want. But that might be a bigger project better targeted for 1.1.0.

**Comment by larsoner** [comment]
From the mailing list: https://mail.python.org/pipermail/scipy-dev/2017-January/021654.html

**Comment by rgommers** [comment]
> We could also deprecate direct access to e.g. signal.hamming with a DeprecationWarning if we want. But that might be a bigger project better targeted for 1.1.0.

I think we shouldn't use ``DeprecationWarning``s, just deprecate in docstrings. Impact is too big and gain to small.

**Comment by rgommers** [comment]
Prepending ``windows.`` I think is a good idea
