### ISSUE TITLE
Wrong result from scipy.interpolate.UnivariateSpline.integral for out-of-bounds

### ISSUE THREAD

**Issue by dgarrett622** [scipy/scipy#7906]
When using the integral method with an interpolant created using InterpolatedUnivariateSpline and ext=1, a nonzero value is returned when the bounds of integration are outside the interpolation domain. This also occurs with the integral method for RectBivariateSpline.

### Reproducing code example:
```
import numpy as np
import scipy.interpolate as interpolate

x = np.linspace(0.,1.,20)
f = interpolate.InterpolatedUnivariateSpline(x,x,ext=1)
# integral from 2. to 5. should return 0
print(f.integral(2.,5.))
```

### Error message:
None

### Scipy/Numpy/Python version information:
```
scipy.__version__ = 0.19.1
numpy.__version__ = 1.12.1
sys.version_info = sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0)
```

**Comment by mefergus** [comment]
I ran into a similar issue using ext=3, where out-of-range values should be the endpoint values.  The interpolation is as expected, but the integral is not.

## Reproducing code example
import numpy
import scipy.interpolate as interpolate

x = range(1, 5)
y = numpy.array([1. for i in x])
x = numpy.array(x)
f = interpolate.InterpolatedUnivariateSpline(x, y, ext=3)
# Interpolated values "outside" of interpolated range
# Should be 1.
print(f(0.5))
# integral from 0. to 2. should return 2
print(f.integral(0., 2.))
`
## Output
`
1.0
1.0
`
## Error message:
None

## Scipy/Numpy/Python version information:
`
scipy.__version__ = 1.0.0
numpy.__version__ = 1.13.3
sys.version_info = sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0)
`

**Comment by ev-br** [comment]
Fix in gh-10633.

For the second example, with `ext=3`, it does not integrate the extrapolating part. It's documented to assume the integrand to be zero outside of the interpolation range (https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.UnivariateSpline.integral.html#scipy.interpolate.UnivariateSpline.integral)

While this might be suboptimal, I think it's too late to change this.
