### ISSUE TITLE
bessel kv function in 0 is nan 

### ISSUE THREAD

**Issue by tfabbri** [scipy/scipy#7909]
I am translating some code from a Matlab implementation to Python using Scipy/Numpy. 
During such process I've faced the following problem about the value of the  Modified Bessel function of the second kind of real order v `kv` corresponding to the function `besselk` in Matlab. 
The value reported by such function in 0 is equal to nan for different values of the order k. 
I am not aware too much of Bessel functions but from a close research I can see that such function tends to be asymptotically infinite for values close to zero. 

Maybe a `inf` as output value is more suitable. 

Reproducing code:
```
from scipy.special import kv
kv(3/2, 0)
```

Scipy/Numpy/Python version information:
```
Sys Version: major 3, minor=4, micro=3, releaselevel='final', serial=0
Numpy Version: 1.12.1
Scipy Version: 0.19.0
```

**Comment by person142** [comment]
This happens because under the hood `kv(3/2, 0)` is actually calling the complex implementation with zero imaginary part. Relevant function is here:

https://github.com/person142/scipy/blob/master/scipy/special/amos_wrappers.c#L636

To fix it add an extra check to that function for the `z = 0` case

**Comment by tfabbri** [comment]
Maybe mentioning this in the documentation could avoid some headache to future users.

**Comment by person142** [comment]
Well it's a bug and should be fixed. Fixing it will take about the same amount of time as changing the docs.

**Comment by tfabbri** [comment]
Ok. I thought that was not considered as a bug/defect.
