### ISSUE TITLE
TravisCI not failing when it should for -OO run

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#7914]
See https://github.com/scipy/scipy/pull/7900#pullrequestreview-64708732. The PR had code that should be failing with ``-OO`` (use of ``__doc__`` without checking ``if __doc__ is not None``), but it didn't. Needs investigating. Could be a 2.7 vs. 3.x thing perhaps.

**Comment by pv** [comment]
I think the issue was that the PR added the line
```
assert 'signal.hann is deprecated' in dep_hann.__doc__
```
Such assert statements are however nor run when python is run with `-OO`.

**Comment by rgommers** [comment]
> Such assert statements however have no effect when python is run with -OO, and pytest doesn't (nowadays?) try to do evil magick to get around that.

It tells me that it does:

    WARNING: assertions not in test modules or plugins will be ignored because assert 
    statements are not executed by the underlying Python interpreter (are you using python -O?)

And that it is failing with Python 2.7 shows that ``pytest`` is actually doing this.
