### ISSUE TITLE
interpolate.spline crash on empty lists

### ISSUE THREAD

**Issue by researchNox** [scipy/scipy#7926]
Program crashes with exit code 0xC0000374 after a few calls to interpolate.spline with an empty list.

### Reproducing code example:
```
import numpy as np
from scipy import interpolate

for i in range(123456):
    try:
        res = interpolate.spline(np.array([]), np.array([]), xnew=np.linspace(0, 300, 2048), order=3)
    except Exception:
        print(i)
```

### Error message:
```
0
1
2
3
4
5
6

Process finished with exit code -1073740940 (0xC0000374)
```

### Scipy/Numpy/Python version information:
```
0.19.1 1.13.1 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
Thanks for the report @researchNox. I can reproduce that.

**Comment by ev-br** [comment]
Did not manage to reproduce it. Anyway, `spline` is semi-deprecated. Recommended replacements are `splrep/splev` or `make_interp_spline/`, both of which raise.

**Comment by pv** [comment]
`spline` is actually deprecated since 0.19.0

**Comment by ev-br** [comment]
`spline` has been removed in https://github.com/scipy/scipy/pull/9325 for scipy 1.3.0. So this issue can be closed.
