### ISSUE TITLE
Internal work array size computation failed

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [scipy/scipy#7930]
Hello,

I was trying to run python code from Matlab 2017(a/b) and I am not able to use linear algebra routines (everything else works fine). The following code is matlab code that call numpy/scipy routines.

Do you have any idea why I am getting these errors ?

In some environment matlab just crash with a segfault and in some other environment I get the following errors.

Thank you for your help 

### Reproducing code example:
```
matrix = py.numpy.ones(int32([3 3]))
py.scipy.linalg.eig(matrix)
```

### Error message:
```
Error using lapack>_compute_lwork (line 528)
Python Error: ValueError: Internal work array size computation failed: -13

Error in decomp>eig (line 201)
                           compute_vr=compute_vr)
```

### Scipy/Numpy/Python version information:
```
('0.19.1', '1.13.1', sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0))
```

I have the same error with python 3.6 on another machine

**Comment by ilayn** [comment]
Can you please type 

```
version -blas
version -lapack 
```
 in matlab and also `sp.linalg.lapack.ilaver()` in Python? It looks like it is picking up the wrong lapack lib. On my quite standard laptop I get 

```
ans = 

  Python tuple with no properties.

    (array([  3.00000000e+00+0.j,   6.16297582e-33+0.j,  -7.50963641e-17+0.j]), 
     array([[  5.77350269e-01,  -6.51147040e-17,   6.09781659e-01],
            [  5.77350269e-01,  -7.07106781e-01,  -7.75129861e-01],
            [  5.77350269e-01,   7.07106781e-01,   1.65348202e-01]]))
```

**Comment by GuillaumeLeclerc** [comment]
I will check tonight. I also found that it works on windows machine. Are
you running windows by any chance ?

**Comment by ilayn** [comment]
Yes it's Win 10 machine and also works on my Win 7 machine.

**Comment by GuillaumeLeclerc** [comment]
**Matlab**

```
>> version -blas

ans =

    'Intel(R) Math Kernel Library Version 11.3.1 Product Build 20151021 for Intel(R) 64 architecture applications, CNR branch AVX2
     '

>> version -lapack

ans =

    'Intel(R) Math Kernel Library Version 11.3.1 Product Build 20151021 for Intel(R) 64 architecture applications, CNR branch AVX2
     Linear Algebra PACKage Version 3.5.0
     '
```

**Python**

```
In [4]: sp.linalg.lapack.ilaver()
Out[4]: (3, 7, 0)
```

**Scipy inside matlab**

```
>> py.scipy.linalg.lapack.ilaver()
Python Error: SystemError: <fortran object> returned NULL without setting an error
```

It seems you are right they do not seem to be the same. Is there a way to force it somehow ?

Thank you very much for your help. You are thousands of time more helpful than the Matlab support team.

**Comment by ilayn** [comment]
They shouldn't be necessarily the same but they should be accessible and up to date. These version numbers are the same on my Windows machines. Somehow, your matlab cannot translate the data types back and forth as far as I understand but I am out of ideas why this should be the case. 

Maybe it is an MKL vs. OpenBLAS installation of NumPy that is causing the problem.

**Comment by GuillaumeLeclerc** [comment]
I tried with the normal python and a conda environment. Is there a way I can switch between MKL and OpenBLAS as you suggest. Isn't strange that matlab is not able to display the version number ? Is there anyone able to make this work on linux ?

Thank you

**Comment by GuillaumeLeclerc** [comment]
Problem was solved through that thread if anyone needs helps in the future:

https://www.mathworks.com/matlabcentral/answers/358233-matlab-python-interface-broken?s_tid=email_ans_new_ans_ans_h#answer_283353
