### ISSUE TITLE
Error in scipy.special.j_roots documentation: beta > 0

### ISSUE THREAD

**Issue by estansifer** [scipy/scipy#7935]
The [documentation of scipy.special.j_roots](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.special.j_roots.html) says one must have beta > 0. However the source code only checks beta > -1, which is in agreement with the Wikipedia article on Gauss-Jacobi quadrature. I believe the documentation should read "beta > -1" instead. Thanks.

scipy 0.18.1

**Comment by estansifer** [comment]
I was mistakenly looking at an older version of scipy. In 0.19.1 the function is now called [scipy.special.roots_jacobi](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.roots_jacobi.html) (and the beta > 0 mistake is still present).

**Comment by person142** [comment]
Yup that's a mistake. Interested in a PR?

**Comment by estansifer** [comment]
Ok, it was my first time making a pull request so it took me a while to figure out what to do. In the future for small errors like this where the fix is obvious, should I jump directly to creating a pull request?

**Comment by person142** [comment]
Yes, that's fine.

**Comment by person142** [comment]
Fixed in https://github.com/scipy/scipy/pull/7936.
