### ISSUE TITLE
pdist and cdist disagree on kwarg order

### ISSUE THREAD

**Issue by jakirkham** [scipy/scipy#7950]
Would be nice if [`cdist`]( https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.spatial.distance.cdist.html#scipy.spatial.distance.cdist ) and [`pdist`]( https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.spatial.distance.pdist.html#scipy.spatial.distance.pdist ) agreed on keyword argument order. Then again this may constitute a breaking change. For reference...

```
scipy.spatial.distance.cdist(XA, XB, metric='euclidean', p=None, V=None, VI=None, w=None)

scipy.spatial.distance.pdist(X, metric='euclidean', p=None, w=None, V=None, VI=None)
```

So it basically comes down to where `w` is positioned.

**Comment by apbard** [comment]
This was a longstanding "issue" and has been solved in version 1.1
Now the usage of positional args is deprecated...so you should always specify the arg name. 
Also the signatures has been changed to keep retro-compatibility

    cdist(XA, XB, metric='euclidean', *args, **kwargs)
    pdist(XA, XB, metric='euclidean', *args, **kwargs)

but will probably become 

    cdist(XA, XB, metric='euclidean', out=None, **kwargs)
    pdist(XA, XB, metric='euclidean', out=None, **kwargs)

in a future version of scipy

**Comment by jakirkham** [comment]
Is there a branch for `1.1.x` already or is this just in `master`?

**Comment by larsoner** [comment]
It's just `master`

**Comment by jakirkham** [comment]
Cool. Thanks for the info. Closing as this was resolved by PR ( https://github.com/scipy/scipy/pull/7629 ).
