### ISSUE TITLE
linalg.solve ill-condition warning

### ISSUE THREAD

**Issue by ilayn** [scipy/scipy#7951]
For the `linalg.solve`, since version 19.1, we have the capability of printing the warning the ill conditioning of the matrix. However the result is not quite pretty due to the traceback inclusion. For example: 

![image](https://user-images.githubusercontent.com/1303842/31029627-c0784a14-a552-11e7-8787-c4484766dbd8.png)

I think the story got a bit uglier with our latest change that also prints the reported dlamch machine precision since now we actually have to look for the correct number. 

![image](https://user-images.githubusercontent.com/1303842/31029713-1a406e46-a553-11e7-893b-ee26ceefda35.png)

I think it's best if we print the truncated versions of those numbers anyhow. But should we switch to a warning printing scheme instead? I don't know yet any way to raise a warning without printing the traceback. 

One use case I'd like to retain is that if a user is solving iteratively a lot of equations s/he should still be able to catch a warning if the problem is ill-conditioned (which was the reason to emit a warning in the first place). Or we can emit a warning directly and then do a custom printing. Such that there is a clear distinction between the traceback and the actual warning message.

**Comment by larsoner** [comment]
Can we set the `stacklevel` so that it's in the calling function? Then the traceback is much more useful.

**Comment by pv** [comment]
In general, all uses of `warnings.warn` should have stacklevel set.

**Comment by ilayn** [comment]
I don't know actually. If it is too deep, let's say (I'm just making it up) something is computing a filter coefficient for conversion from state space to transfer function, to get the frequency response to draw Bode plot, which function should be the source the deepest or the calling function?

**Comment by larsoner** [comment]
>  If it is too deep,

This is a problem for the caller, whether it is a user or a library. In other words, in your example, it's a problem for the state space -> transfer function code; and we should improve our filter code so that it does the right thing with this warning (avoids it or catches it). So I'd say just go up however many stacklevels (2?) to get to the one that called e.g. `scipy.linalg.solve`.

**Comment by ilayn** [comment]
I've played around with this a bit more and it turns out that setting the right value to the `stacklevel` is trickier. I've also [asked in SO](https://stackoverflow.com/q/46555075/4950339) to see whether someone teaches me more about it. Essentially there are two problems : 
```
from warnings import warn, formatwarning


def _warning_on_one_line(message, category, filename, lineno,
                         file=None, line=None):
    return ' %s:%s: %s:%s' % (filename, lineno, category.__name__, message)


def inner():
    formatwarning = _warning_on_one_line
    warn('Some warning', RuntimeWarning, stacklevel=3)
    return


def middle():
    return inner()


def outer():
    return middle()


outer()
```

As you play with `stacklevel` argument you can basically cause the warning to report different lines in this code. But if you overdo it you start getting IPython's caller stack all the way up to 26 where it finally starts to say `sys.1: RuntimeWarning` so detecting the correct caller doesn't seem obvious to me. And I agree that I think we have to be a bit more systematic when including a potentially warning emitting code inside a function. Such that we can catch the warning and emit a more meaningful message. So it seems to me that we are stuck with `stacklevel=1` for now. 

Second problem is how to format the warning message but that is kind how it is done as given in the above code.

Do you have a way to overcome this issue?

**Comment by larsoner** [comment]
My idea is/was:

> So I'd say just go up however many stacklevels (2?) to get to the one that called e.g. scipy.linalg.solve.

If we know where the warning is emitted, and we know the codepath to get there from `scipy.linalg.solve`, we can do this, right?

**Comment by larsoner** [comment]
... in other words, in your example, if `scipy.linalg.solve` (in our codebase) is `inner`, you'd use `stacklevel=1`, if it's `middle` you'd use `stacklevel=2`, and if it's `outer` you'd use `stacklevel=3` (maybe +/-1 to all of these, can't remember the level details).

**Comment by larsoner** [comment]
> So it seems to me that we are stuck with stacklevel=1 for now.

If you're saying that the warning is currently emitted in `scipy.linalg.solve`, then yeah I agree `stacklevel=1` (assuming that's the one that shows `scipy.linalg.solve`'s caller) is the right thing to do.

**Comment by pv** [comment]
The stacktrace indicates the point in the *calling* code where the 
warning is emitted. The stacklevel must correspond to the innermost 
public API function. This is what Numpy does, and it is sensible behavior.

For a public API function, we write
```
def public_api_func():
     warnings.warn("some warning", stacklevel=2)
```
For an internal function for which we know the distance to the API function:
```
def _helper_func():
     warnings.warn("some warning", stacklevel=3)

def public_api_func():
     _helper_func()
```

**Comment by ilayn** [comment]
> If we know where the warning is emitted, and we know the codepath to get there from scipy.linalg.solve, we can do this, right?

Yes indeed but depending on platform we might go too far and start addressing irrelevant parts of the current stack, that's what I meant by the 26 argument. For example if I use stacklevel=9

```
runfile('C:/Users/Ilhan Polat/Documents/pydump/warning_exp.py', wdir='C:/Users/Ilhan Polat/Documents/pydump')
c:\users\ilhan polat\appdata\local\programs\python\python36\lib\site-packages\IPython\core\interactiveshell.py:2808: RuntimeWarning: Some warning
  if self.run_code(code, result):
```

which is related to IPython internals So _give me the top of the stack_ kind of argument won't be accurate to get the actual code path.

**Comment by ilayn** [comment]
>The stacktrace indicates the point in the *calling* code where the warning is emitted. The stacklevel must correspond to the innermost public API function. This is what Numpy does, and it is sensible behavior. 

Ah OK now I get your arguments.

**Comment by pv** [comment]
Warnings emitted inside Scipy code (e.g. due to calling solve() on a 
singular matrix in the implementation of some routine) are probably 
implementation defect on our side, although usually probably minor one.

Either we e.g. know the algorithm works correctly despite such 
singularity (in which case we should ensure somehow the warning doesn't 
get emitted), or the singularity implies a failure of the algorithm (in 
which case an error or a more specific warning would be more appropriate 
in the perfect world).

**Comment by ilayn** [comment]
I agree but now I'm a bit confused how to detect an ill-conditioned array. Because if we remove the warning, then it goes unnoticed. This is known to matlab users a lot with its silent exception handling and only blowing up when the algorithm cannot move any forward. If we emit the warning only pointing to where linalg.solve is called then we have the current situation where the warning seems to be unrelated to the current caller.

Silencing the warning if it is not related is easy. Modifying the warning message is also doable by catching the warning. However I don't know what should be the way to go with this.

**Comment by larsoner** [comment]
> Because if we remove the warning, then it goes unnoticed

IIUC the propsal is to:

1. Always emit the warning in the `scipy.linalg.solve` code when ill conditioned matrices are detected.
2. In places in SciPy where we internally use `scipy.linalg.solve`, we should "do the right thing". In other words, we should deal with the warning safely so that no warning is ever emitted. This could mean "catch the warning and raise an error" in cases where rank deficiency is bad, or it could mean "catch the warning, and then use linalg.lstsq instead, because rank-deficiency is fine but we'd like the speed of solve if possible".

Point (2) is something we need to decide / do on a case-by-case basis as it comes up, so I don't think we need to worry about it right now.

**Comment by ilayn** [comment]
OK, I'll just try to make the warning message a bit more structured then and leave the decision part for later then.
