### ISSUE TITLE
Using cdist with wminkowski disagrees with wminkowski

### ISSUE THREAD

**Issue by jakirkham** [scipy/scipy#7953]
It appears that running `cdist` using the `wminkowski` metric reports inaccurate results that disagree with running `wminkowski` on each vector combination individually. The issue goes away if the absolute value of `w` is taken before giving it to `cdist`. However this is done for the user in `wminkowski` matching the equation in the docs. Hence the disagreement. Below is an example of this behavior with details about how to install a `conda` environment that will reproduce the issue.

Example:

<details>

```python
In [1]: import numpy as np

In [2]: import scipy.spatial.distance as spdist

In [3]: np.random.seed(0)

In [4]: a_u = 2 * np.random.random((7, 6)) - 1

In [5]: a_v = 2 * np.random.random((3, 6)) - 1

In [6]: p = 1.6

In [7]: w = 2 * np.random.random(a_u.shape[-1:]) - 1

In [8]: spdist.cdist(a_u, a_v, metric="wminkowski", p=p, w=w)
Out[8]: 
array([[ nan,  nan,  nan],
       [ nan,  nan,  nan],
       [ nan,  nan,  nan],
       [ nan,  nan,  nan],
       [ nan,  nan,  nan],
       [ nan,  nan,  nan],
       [ nan,  nan,  nan]])

In [9]: d = np.empty((len(a_u), len(a_v)), dtype=float)
   ...: for i in range(len(a_u)):
   ...:     for j in range(len(a_v)):
   ...:         d[i, j] = spdist.wminkowski(a_u[i], a_v[j], p=p, w=w)
   ...:         

In [10]: d
Out[10]: 
array([[ 1.24606122,  1.16395049,  1.25037412],
       [ 1.84842639,  1.06442873,  1.44461084],
       [ 1.96393331,  1.98499393,  1.75982539],
       [ 1.51823304,  1.68759411,  1.87569175],
       [ 1.63240776,  1.32480509,  1.47219684],
       [ 1.50025279,  1.54607896,  1.40125501],
       [ 1.0061864 ,  1.26567631,  1.31885044]])

In [11]: spdist.cdist(a_u, a_v, metric="wminkowski", p=p, w=abs(w))
Out[11]: 
array([[ 1.24606122,  1.16395049,  1.25037412],
       [ 1.84842639,  1.06442873,  1.44461084],
       [ 1.96393331,  1.98499393,  1.75982539],
       [ 1.51823304,  1.68759411,  1.87569175],
       [ 1.63240776,  1.32480509,  1.47219684],
       [ 1.50025279,  1.54607896,  1.40125501],
       [ 1.0061864 ,  1.26567631,  1.31885044]])
```

</details>

<br>
Environment:
<br>
<br>

<details>

```yaml
name: test
channels:
- conda-forge
- defaults
dependencies:
- appnope=0.1.0=py36_0
- blas=1.1=openblas
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py36_0
- decorator=4.1.2=py36_0
- ipython=6.2.0=py36_0
- ipython_genutils=0.2.0=py36_0
- jedi=0.10.2=py36_0
- libgfortran=3.0.0=0
- ncurses=5.9=10
- numpy=1.13.1=py36_blas_openblas_200
- openblas=0.2.19=2
- openssl=1.0.2l=0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_0
- prompt_toolkit=1.0.15=py36_0
- ptyprocess=0.5.2=py36_0
- pygments=2.2.0=py36_0
- python=3.6.2=0
- readline=6.2=0
- scipy=0.19.1=py36_blas_openblas_202
- setuptools=36.3.0=py36_0
- simplegeneric=0.8.1=py36_0
- six=1.11.0=py36_1
- sqlite=3.13.0=1
- tk=8.5.19=2
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.30.0=py_1
- xz=5.2.3=0
- zlib=1.2.11=0
```

<details>

**Comment by jakirkham** [comment]
FWICT looks like the weight isn't inside the `abs` function call.

https://github.com/scipy/scipy/blob/676da8f65d38cd62c89799aec7444df227424e04/scipy/spatial/src/distance_impl.h#L358

**Comment by rgommers** [comment]
With recent master (676da8f) that gives me ``ValueError: array must not contain infs or NaNs`` for ``In [8]: spdist.cdist...``. We've made a recent fix to it because of backwards compat issues - what version are you using?

**Comment by jakirkham** [comment]
Interesting. Using 0.19.1. If this is meant to be an error raising case, it seems that the error should be updated to explicitly mention negative weights are not allowed.

**Comment by rgommers** [comment]
Negative weights raising an informative error sounds right to me. It is a change from previous versions, but I doubt that allowing negative weights was ever a conscious decision.

@apbard thoughts?

**Comment by apbard** [comment]
> I doubt that allowing negative weights was ever a conscious decision.

Totally agree, probably just an overlooked different behaviour from C code and linalg.norm.

In scipy 1.0, the `dist = norm(w * (u - v), ord=p)` has been translated into [norm(np.sqrt(w) * (u - v), ord=p)](https://github.com/scipy/scipy/blob/master/scipy/spatial/distance.py#L491),  thus we should get the NaNs also with the python weighted version of `minkowski`. 

I suspect that all new metrics version would be somehow affected by negative weights. To solve this I think we the most straightforward solution is to force all weights to be positive.
Actually, there are some weird corner cases where negative weights might be meaningful...We could normalise the weights so that they sum up to 1 (with the only constraint that the sum is >0) and solve "sqrt" issues metric by metric...but it is probably not worth the effort.

**Comment by rgommers** [comment]
> thus we should get the NaNs also with the python weighted version of minkowski.

NaN's or the ValueError we get right now in master? I'd prefer the latter I think. Would be good to have a check for that for all metrics.

**Comment by apbard** [comment]
yes, I just meant that we have the same behaviour also in other metrics. Totally agree that is best to forbid negative weights then return NaNs values.
I can make a PR implementing this.
Then, we can decide whether is worth or not relaxing the constraint of all positive weights.

**Comment by apbard** [comment]
@rgommers Done. please have a look.

**Comment by jakirkham** [comment]
Thanks all.
