### ISSUE TITLE
scipy.integrate.ode(): inaccurate error message

### ISSUE THREAD

**Issue by kevmo314** [scipy/scipy#7956]
Hi, currently `scipy.integrate.ode()` returns an error message indicating that the function returned a tuple when it returns an array of non-matching length. The true error message is buried above the raised `ValueError` [here](https://github.com/scipy/scipy/blob/03b1092cf0e0bdebcbe98a44d289208a1e597416/scipy/integrate/_ode.py#L411), which is misleading, as the function is not returning a tuple.

Could a better error message be surfaced?

### Reproducing code example:

```
import scipy.integrate

def f(t, y):
    return [y[0]]

scipy.integrate.ode(f).set_initial_value([1, 1]).integrate(1)
```

### Error message:
```
unexpected array size: new_size=2, got array with arr_size=1
rv_cb_arr is NULL
Call-back cb_f_in_dvode__user__routines failed.
Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\scipy\integrate\_ode.py", line 408, in integrate
    self.f_params, self.jac_params)
  File "C:\Miniconda3\lib\site-packages\scipy\integrate\_ode.py", line 865, in run
    y1, t, istate = self.runner(*args)
SystemError: <fortran object> returned NULL without setting an error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    scipy.integrate.ode(f).set_initial_value([1, 1]).integrate(1)
  File "C:\Miniconda3\lib\site-packages\scipy\integrate\_ode.py", line 411, in integrate
    raise ValueError('Function to integrate must not return a tuple.')
ValueError: Function to integrate must not return a tuple.
```

### Scipy/Numpy/Python version information:

```
0.19.1 1.13.1 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by Juanlu001** [comment]
Duplicated of https://github.com/scipy/scipy/issues/7956?

**Comment by XtremeGood** [comment]
Hey what is going on? Can't you comment on atleast one? Both posts are marked duplicate.

**Comment by tylerjereddy** [comment]
> Hey what is going on? Can't you comment on at least one? Both posts are marked duplicate.

As far as I can tell the claim of duplication above is pointing to the same issue (this one)! Anyway, I've added the maintenance label--if there's a way to improve an error message that would typically not be too controversial, I think.

**Comment by tylerjereddy** [comment]
0.19.1 is a bit older though, so probably good to confirm this still happens on latest master

**Comment by WarrenWeckesser** [comment]
This is actual an `f2py` issue.  In some cases,  `f2py` would print an error message instead of raising an exception.  This behavior was changed in https://github.com/numpy/numpy/pull/9306, and I think that change is in numpy 1.14.0.

Here's the error generated by the above code with the master branch of SciPy and numpy 1.17.2:

```
rv_cb_arr is NULL
Call-back cb_f_in_dvode__user__routines failed.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-5b6d3c982c41> in <module>
      4     return [y[0]]
      5 
----> 6 scipy.integrate.ode(f).set_initial_value([1, 1]).integrate(1)

~/mc37scipy/lib/python3.7/site-packages/scipy-1.4.0.dev0+4dcf606-py3.7-macosx-10.7-x86_64.egg/scipy/integrate/_ode.py in integrate(self, t, step, relax)
    430             self._y, self.t = mth(self.f, self.jac or (lambda: None),
    431                                   self._y, self.t, t,
--> 432                                   self.f_params, self.jac_params)
    433         except SystemError:
    434             # f2py issue with tuple returns, see ticket 1187.

~/mc37scipy/lib/python3.7/site-packages/scipy-1.4.0.dev0+4dcf606-py3.7-macosx-10.7-x86_64.egg/scipy/integrate/_ode.py in run(self, f, jac, y0, t0, t1, f_params, jac_params)
   1002         args = ((f, jac, y0, t0, t1) + tuple(self.call_args) +
   1003                 (f_params, jac_params))
-> 1004         y1, t, istate = self.runner(*args)
   1005         self.istate = istate
   1006         if istate < 0:

ValueError: unexpected array size: new_size=2, got array with arr_size=1
```
Note that the message in the `ValueError` is the same message that used to be printed to the terminal.  The message isn't quite as nice as, say "The right-hand-side function returned a array with length 1, but an array with length 2 was expected", but it is much better than the old error message.

`f2py` is still printing stuff that it shouldn't.  The output
```
rv_cb_arr is NULL
Call-back cb_f_in_dvode__user__routines failed.
```
is noise from f2py.  It shouldn't print that, but that's an upstream issue.

I think the new behavior is sufficiently improved that we can close this issue.
