### ISSUE TITLE
integrate.quad could use better error messages when given bad options

### ISSUE THREAD

**Issue by jcalbert** [scipy/scipy#7958]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
I noticed that a few input errors to `scipy.integrate.quad` produce the same cryptic error
```ValueError: The input is invalid.```

It might be nice to add some sanity-checking in `quad()` and output more descriptive errors.

### Reproducing code example:
```
from scipy.integrate import quad
import numpy as np
```

points out of range:
```
quad(np.sqrt, 0, 1, points=[1.1])
ValueError: The input is invalid.
```

more points than subintervals:
```
quad(np.sqrt, 0, 1, limit=2, points=[.2, .3])
ValueError: The input is invalid.
```

too few cycles for 'sin' weight:
```
quad(np.sqrt, 1, np.inf, weight='sin', wvar=1.0, limlst=2)
ValueError: The input is invalid.
```

**Comment by rgommers** [comment]
Thanks @jcalbert, good idea.

**Comment by jcalbert** [comment]
I can PR it if you'd like.

**Comment by rgommers** [comment]
That would be great, please do

**Comment by pv** [comment]
pr was merged, so probably fixed for the most part
