### ISSUE TITLE
Wrong value for hyp2f1(k, -n, -n, z) with k,n positive integers

### ISSUE THREAD

**Issue by pv** [scipy/scipy#7961]
The following values are wrong
```
from scipy.special import hyp2f1
print(hyp2f1(2, -1, -1, 0.7)) # -> 11.1111111111  (should be 2.4)
print(hyp2f1(2, -2, -2, 0.7)) # -> 11.1111111111  (should be 3.87)
```
These were previously calculated wrong also by mpmath, but that's fixed in mpmath-1.0.0.
As a consequence, the test `scipy.special.tests.test_mpmath::test_hyp2f1_strange_points` fails with the fixed mpmath (marked as xfail in gh-7962).

### Scipy/Numpy/Python version information:
```
1.0.0rc1 1.13.1 sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)
```

**Comment by aviral1701** [comment]
I would like to work on this one.New here,so some help would be appreciated.

**Comment by pv** [comment]
The relevant routine is here: https://github.com/scipy/scipy/blob/b6fd544a631f727bcf53f089ba511dce06d3861d/scipy/special/cephes/hyp2f1.c#L87

**Comment by aviral1701** [comment]
@pv Thanks.I will look into and revert back asap.

**Comment by person142** [comment]
@aviral1701 just a heads up that this is probably not an easy first issue to work on.

**Comment by aviral1701** [comment]
ok, I realised this @person142 , :p this issue is open for someone else to take up.

**Comment by xoviat** [comment]
For reference, we need to reapply https://github.com/fredrik-johansson/mpmath/commit/b406dae230dc6fb8ee3b483b1f15d339e3a6fc01 to the c source.

**Comment by xoviat** [comment]
If it's not done by this weekend, I may have a look.

**Comment by person142** [comment]
> For reference, we need to reapply fredrik-johansson/mpmath@b406dae to the c source.

It's not evident that the arbitrary precision approach is applicable here (in double precision)? It's summing a series which can suffer from cancellation.

**Comment by xoviat** [comment]
I looked at this further, and the function is branching on the following:

https://github.com/scipy/scipy/blob/b6fd544a631f727bcf53f089ba511dce06d3861d/scipy/special/cephes/hyp2f1.c#L133

Which essentially expands to `(1.0 - 0.7)^(-2)`

It also has this comment:

https://github.com/scipy/scipy/blob/b6fd544a631f727bcf53f089ba511dce06d3861d/scipy/special/cephes/hyp2f1.c#L131

This essentially defines the maximum scope of this bug: when the second two numbers are equal and `|x| < 1.0`. Let me plot this on wolfram and see where the functions diverge...

**Comment by xoviat** [comment]
That's interesting. The approximation fails for all negative integers `|b| < 100` (it's limit behavior where the approximation continues to grow closer). Maybe we can bail out of the approximation if and only if b is one of those numbers? Also, 100 should be tuned to a "good enough" standard, and there may be bad behavior lurking near the integers.

**Comment by person142** [comment]
> The approximation fails

It's not an approximation: `2F1(a, b; b, z)` is exactly equal to `(1 - z)^(-a)` (Taylor expand the latter function around `z = 0`.)

**Comment by xoviat** [comment]
I [asked](https://math.stackexchange.com/questions/2457831/hypergeometric-expansion-approximation) on the mathematics stackexchange and was told that this cannot possibly happen.

**Comment by pv** [comment]
This exact issue appears to be discussed in DLMF: http://dlmf.nist.gov/15.2
Generally, the properties of hypergeometric functions are well known, the only problem is to find the correct place in references.

**Comment by xoviat** [comment]
Wolfram seems to expand the Taylor series around 1 rather than 0.

With respect to DLMF, is Equation 15.2.2 valid for negative integers? I couldn't tell whether the integer restriction was applied to 15.2.1 only.

**Comment by xoviat** [comment]
I actually received an excellent answer on math stackexchange. We just need to implement this:

![image](https://user-images.githubusercontent.com/15351036/31198979-ab90cce4-a91b-11e7-8e0f-6d5b3721501e.png)
