### ISSUE TITLE
scipy.integrate API should not require a "while" loop

### ISSUE THREAD

**Issue by xoviat** [scipy/scipy#7965]
The documentation gives the following example for scipy.integrate:

```python
while r.successful() and r.t < t1:
    print(r.t+dt, r.integrate(r.t+dt)
```

This API is unnecessarily complex for two reasons:
1. It requires the user to set the step size. Integration methods could potentially set the step size automatically.
2. It requires the user to store the results. IMHO scipy should store the results into two ndarrays and return them (like MATLAB does with ode45).

Proposal: allow a new override to `ode.integrate` that takes a maximum t with `max=tmax`. The new override would automatically determine the step size (some reasonable linspace between two bounds or automatically determined by the integration method). Results are stored in two ndarrays (first one is 1D and second one is 2D).

I can implement this if others think it is okay.

**Comment by ewmoore** [comment]
Does the newer [`solve_ivp`](http://scipy.github.io/devdocs/generated/scipy.integrate.solve_ivp.html#scipy.integrate.solve_ivp) interface do more what you're looking for?

**Comment by xoviat** [comment]
Actually that is perfect. [The documentation](https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html#general-purpose-equivalents) should probably be updated.
