### ISSUE TITLE
ENH: matching return dtype for loggamma/gammaln 

### ISSUE THREAD

**Issue by josef-pkt** [scipy/scipy#7970]
In 1.0 gammaln does not allow complex input anymore https://github.com/scipy/scipy/pull/7153
However, loggamma always returns complex dtype even if input is float

So, AFAICS, there is of lngamma function in 1.0 anymore where the output dtype matches the input dtype. Is it possible to get back a function that has return dtype matching the input dtype?

We need this in statsmodels where functions that included gammaln were sometimes run with complex and sometimes with real arguments.
Using complex return when we need float breaks other things, e.g. some of the scipy.special distribution functions.

The main usecase for us was complex step numerical derivatives, although we currently have only a single case left because we use mostly analytical derivatives
https://github.com/statsmodels/statsmodels/pull/3964

**Comment by person142** [comment]
So `gammaln(x) = log(abs(gamma(x))` and `loggamma` is the analytic continuation of `log(gamma(x))` for `x > 0`. They don't agree except on the positive real axis. (I imagine those numerical derivatives were being taken at positive arguments only? Also why use numerical derivatives instead of the digamma function?)

I think Julia took the route of keeping the functionality of `gammaln` and `loggamma` in a single function. I guess we could do that too.

**Comment by josef-pkt** [comment]
Note, I don't understand the math background and what it means to have complex loggamma.

about the usecase and why using matching including is important including for whatever loggamma/gammaln is used inside scipy (e.g. scipy.stats):

> Also why use numerical derivatives instead of the digamma function?

We do use analytical derivatives (with digamma and polygamma in this case) in statsmodels, but it's a lot of work, e.g.
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/discrete/discrete_model.py#L2510 Maybe around a third of a GSOC project last summer was spend on writing and debugging first and second derivatives.

However, sometimes we don't have the time, it's too difficult, we need numerical derivatives for debugging or for quick prototyping.
Complex step derivatives evaluate the function for the derivative with an underlying real argument using the real argument plus a small (epsilon) imaginary value. The first derivative is very accurate (error < 1e-13, IIRC). 
If complex step derivatives don't work because the functions cannot handle it, then we need to fall back on forward differences which are less accurate. 
(example scipy.stats.distribution makes or made heavy use of gammaln, which I guess now don't work for complex arguments, That's for the underlying `._xxx` methods, the wrapper, main methods forces float.)

My guess would be that gammaln could dispatch to the loggamma for complex arguments. That's what we will have to do in statsmodels, if scipy doesn't do it for us.

**Comment by person142** [comment]
> My guess would be that gammaln could dispatch to the loggamma for complex arguments

Right, it could. And I don't want to sound like I'm against that! I just want to make sure it's clear that this isn't exactly the same thing as having e.g. a real and complex dispatch for `sine` because there will be things like this:

```python
>>> sc.loggamma(-5.5)
(-4.517832174007741-18.849555921538759j)
>>> sc.gammaln(-5.5)
-4.5178321740077418
```

which is why I originally kept them separate.

But so long as people are aware of that and still want them combined, so be it.

**Comment by pv** [comment]
afaik, for the complex differentiation uses in stats it would be enough to have `loggamma(x) -> nan` for `gamma(x)<0` on the real line.

**Comment by person142** [comment]
You would have to return `nan` for all `x < 0`, but yeah that should work. I wonder if @josef-pkt can comment on whether that would help his use cases?

**Comment by josef-pkt** [comment]
I didn't see the importance of **positive**

as far as I understand this now:

In scipy stats we switched to gammaln as numerically more robust way of computing and working with factorials, Similar in statsmodels, it's either a replacement for factorial or the continuous extension.
Always >0.
For complex step derivatives we only want small complex parts, so that should also satisfy that abs(x) > 0. (There might be a corner problem as x -> 0, but similar things need explicit workarounds in our code anyway.)

So based on this we should be in the range where the old gammaln and loggamma agree (except for the dtype)

```
>>> from scipy import special
>>> special.loggamma( 5+1e-6j)
(3.1780538303478352+1.5061176684318089e-06j)
>>> special.loggamma( 5+1e-14j)
(3.1780538303479489+1.5061176684318001e-14j)
>>> special.loggamma( 5+0j)
(3.1780538303479489+0j)
>>> special.loggamma( 5-6j)
(-0.08110790539571866-10.266688988334671j)
>>> special.loggamma( -5-6j)
(-18.986007881820335+6.136012555811007j)
>>> special.gammaln( 5-6j)
(-0.081107905395725766-10.266688988334669j)
>>> special.gammaln( 5+1e-6j)
(3.1780538303478356+1.5061176684318087e-06j)
```

**Comment by josef-pkt** [comment]
> return nan for all x < 0

Sounds fine with me. From what I understand we should not have abs(x) < 0 except with bugs or maybe at a corner case.

Given that ufuncs cannot make the return type conditional on the value, AFAIU, this sounds like the best solution for us and related scipy.stats functions.

**Comment by person142** [comment]
Sounds good; will send a PR later today.
