### ISSUE TITLE
BUG: _get_mem_available fails on Ubuntu

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [scipy/scipy#7972]
Testing SciPy 1.0.0rc build on Ubuntu, both with Python 2.7 and Python 3.6, reveals `test__mem_available` failure due to exception `KeyError: 'memcached'` raised, see [_lib/_testutils.py#L126](https://github.com/scipy/scipy/blob/master/scipy/_lib/_testutils.py#L126).

On Ubuntu, `/proc/meminfo` does not have 'memcached' entry, but has 'cached' entry (see this [SU question](https://superuser.com/questions/521551/cat-proc-meminfo-what-do-all-those-numbers-mean)).

I suppose the code was mimicked [after meminfo.c#L99](https://github.com/troglobit/watchdogd/blob/master/src/meminfo.c#L99), but the field corresponding to `MEMCACHED` is fed from 'Cached:' line on `/proc/meminfo' (see [meminfo.c#L49](https://github.com/troglobit/watchdogd/blob/master/src/meminfo.c#L49)).

### Reproducing code example:
```
from scipy._lib._testutils import import _get_mem_available
_get_mem_available()
```

### Error message:
```
>>> from scipy._lib._testutils import _get_mem_available
>>> _get_mem_available()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/localdisk/work/conda-build/scipy_1507041215546/_t_env/lib/python3.6/site-packages/scipy/_lib/_testutils.py", line 126, in _get_mem_available
    return info['memfree'] + info['memcached']
KeyError: 'memcached'
>>> 
```

### Scipy/Numpy/Python version information:
```
>>> scipy.version.full_version
'1.0.0rc1'
>>> numpy.version.full_version
'1.13.3'
```

**Comment by pv** [comment]
thanks, merged.
