### ISSUE TITLE
Bump minimum Cython version to 0.25?

### ISSUE THREAD

**Issue by person142** [scipy/scipy#7987]
I believe the current minimum required version is 0.23.4:

https://github.com/scipy/scipy/blob/ab5ef39601b17b204f32c787644bb516350b1a76/pyproject.toml#L5

The current version is 0.27. My primary interest in bumping to 0.25 is that it fixes a complex division bug:

https://github.com/cython/cython/blob/master/CHANGES.rst#significant-bugs-fixed

which we have an ugly workaround for in `special`. (Implementing Smith's algorithm ourselves.)

**Comment by rgommers** [comment]
Sounds fine to me.
