### ISSUE TITLE
`lfilter` segfaults for integer inputs

### ISSUE THREAD

**Issue by pezcore** [scipy/scipy#7991]
`scipy.signal.lfilter` segfaults when the inputs are integer type

### Reproducing code example:
```python
lfilter([2,3], [4,5], [1,2,3,4,5])
```

Same thing with using `numpy.ndarrays` with integer `dtype`s:

```python
>>> a = np.array([1,2,3])
>>> b = np.array([5,6,7])
>>> x = np.array([8,19,7,6])
>>> np.who()

Name            Shape            Bytes            Type
===========================================================

a               3                24               int64
b               3                24               int64
x               4                32               int64

Upper bound on total bytes  =       80

>>> lfilter(b, a, x)
```

### Error message:
```
segmentation fault (core dumped)  ipython
```

### Scipy/Numpy/Python version information:
```
0.19.1 1.13.1 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
I can reproduce this with the master branch, and with scipy 0.18.1.

**Comment by xoviat** [comment]
Actually, [according to the test suite](https://travis-ci.org/scipy/scipy/jobs/286098451), this should have raised `NotImplemented`. So why did it not?

**Comment by larsoner** [comment]
Maybe your changes make it so it gives `NotImplementedError` whereas on `master` it would segfault?

**Comment by xoviat** [comment]
That makes no sense. The CXX is functionally equivalent to what we had before (the assembly should be exactly the same).

**Comment by xoviat** [comment]
Also, the check is in Python. The CXX code is private.

**Comment by xoviat** [comment]
[Actually we do get a crash here](https://travis-ci.org/scipy/scipy/jobs/286098457#L4594). So the problem is that the Python code is not checking the dtype correctly.
