### ISSUE TITLE
Errors importing scipy during TravisCI builds

### ISSUE THREAD

**Issue by brian-rose** [scipy/scipy#7992]
Recently all the builds of my [climlab package](https://github.com/brian-rose/climlab) on TravisCI are failing upon trying to import scipy routines. 

This is probably not the best place to report this, since I doubt this is actually a scipy issue, but suggestions are very welcome!

### Error message:
This is an excerpt from a build log at <https://travis-ci.org/brian-rose/climlab>

```
climlab/radiation/radiation.py:77: in <module>
    from scipy.interpolate import interp1d, interp2d
../../../miniconda/envs/test-environment/lib/python2.7/site-packages/scipy/interpolate/__init__.py:176: in <module>
    from .interpolate import *
../../../miniconda/envs/test-environment/lib/python2.7/site-packages/scipy/interpolate/interpolate.py:21: in <module>
    import scipy.special as spec
../../../miniconda/envs/test-environment/lib/python2.7/site-packages/scipy/special/__init__.py:644: in <module>
    from . import specfun
E   ImportError: cannot import name specfun
```

**Comment by pv** [comment]
You're using conda and are having problems with the scipy packaged by them, so they are probably more able to answer the question.
