### ISSUE TITLE
Broken source links on docs.scipy.org

### ISSUE THREAD

**Issue by jondo** [scipy/scipy#8002]
The page https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Delaunay.html contains the following link for the example source code: https://docs.scipy.org/doc/scipy/reference/generated/scipy-spatial-Delaunay-1.py .

This source code link is broken, showing
> 404 Not Found
> -----------------
> The requested URL /doc/scipy/reference/generated/scipy-spatial-Delaunay-1.py was not found on this server.

Maybe all source code links are broken?
At least the ones [here](https://docs.scipy.org/doc/scipy/reference/tutorial/spatial.html) and [here](https://docs.scipy.org/doc/scipy/reference/tutorial/stats.html) are, too.

**Comment by person142** [comment]
This will be corrected in future versions of the documentation, e.g.

https://scipy.github.io/devdocs/generated/scipy.spatial.Delaunay.html.

Fixes were made in https://github.com/scipy/scipy/pull/7691.
