### ISSUE TITLE
There is no OS X wheel for 3.5 with the 1.0.0rc1 release

### ISSUE THREAD

**Issue by dhermes** [scipy/scipy#8007]
Since there is a 3.4 wheel in the [list][1], I assume this is an oversight? Though maybe the [`numpy==1.13.2`][2] caused by Cython are an explanation for why a wheel isn't possible? 

I was surprised by this when my build timed out on installing dependencies.

[1]: https://pypi.org/project/scipy/1.0.0rc1/#files
[2]: https://github.com/numpy/numpy/issues/9786

**Comment by xoviat** [comment]
It's not a coincidence. The 3.5 wheel [wasn't built](https://travis-ci.org/MacPython/scipy-wheels/builds/280352594?utm_source=github_status&utm_medium=notification).

**Comment by dhermes** [comment]
Looks like Cython is the culprit. Are there any plans to add it, or that will wait until an rc2 or later?

**Comment by xoviat** [comment]
Not  my call.

**Comment by rgommers** [comment]
> Are there any plans to add it, or that will wait until an rc2 or later?

Not any more, rc2 will be out soon and we'll add it then.
