### ISSUE TITLE
When using arrays of length longer than max int32 X.sort_indices segfaults

### ISSUE THREAD

**Issue by soluwalana** [scipy/scipy#8017]
https://github.com/scipy/scipy/blob/03b1092cf0e0bdebcbe98a44d289208a1e597416/scipy/sparse/sputils.py#L153

The line linked will cause a segfault if you pass in uint32 data type arrays as indices and indptr.

```python
>>> import numpy as np
>>> np.ones(4, dtype='uint32')
>>> x = np.ones(4, dtype='uint32')
>>> x.dtype > np.int32
False
>>>
```

```python
# segfault.py
import numpy as np
from scipy.sparse import csc_matrix

data = np.ones(2212191192, dtype='float32')
indices = np.random.random_integers(65793, size=(2212191192,)).astype(np.uint32)
indptr = np.zeros(65794, dtype='uint32')
for i in range(1, 65793):
    indptr[i] = 33623 * i
indptr[-1] = 2212191192
X = csc_matrix((data, indices, indptr), dtype='float32')
X.sort_indices()

# python3 segfault.py
[1]    55277 segmentation fault  python3 segfault.py
```

Expected outcome is to upgrade the uint32 arrays to int64 and proceed without segmentation fault.

Alternatively it would be nice if uint32 could be used as the backing datatype for the arrays so that we can store the 2+ billion integers with half of the space overhead.

**Comment by pv** [comment]
The check probably should use `np.can_cast` and not `>`

**Comment by soluwalana** [comment]
Yeah :) I was making a PR for it

**Comment by soluwalana** [comment]
Just waiting on the tests to pass
