### ISSUE TITLE
In Delaunay docs, plotting can be simplified a little

### ISSUE THREAD

**Issue by jondo** [scipy/scipy#8020]
In [two](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Delaunay.html) [places](https://docs.scipy.org/doc/scipy/reference/tutorial/spatial.html) of the docs, when a Delaunay triangulation is plotted, the simplices are copied:
```python
plt.triplot(points[:,0], points[:,1], tri.simplices.copy())
```
In my tests with version 0.19.0, it seems that this `.copy()` is unnecessary, so it should be removed.
~~If not, the copying should be done inside `triplot`, since a plotting function should leave the state of its arguments untouched.~~
**Update:** Copying _is_ done inside since 2012, see my comment below.

**Comment by pv** [comment]
It's not unnecessary, because matplotlib at least formerly had a bug 
where triplot modified the inputs.

**Comment by jondo** [comment]
You mean https://github.com/matplotlib/matplotlib/issues/1584? It is fixed since 2012. See [this commit](https://github.com/matplotlib/matplotlib/pull/1576/commits/68388341b0a25867ac2c6ff5a59775b59fdba720), which added the internal copying. I guess Scipy does not need to support Matplotlib versions older than that.

**Comment by pv** [comment]
Ok, yes I did not recall fixing it. If major linux distributions have 
switched to new enough matplotlib where it's not a problem, I think we 
can simplify the docs.

**Comment by jondo** [comment]
Ok, I'll try a pull request.
