### ISSUE TITLE
lambertw is not reliable

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#8022]
The docs for lambertw say "The evaluation can become inaccurate very close to the branch point at -1/e. In some corner cases, lambertw might currently fail to converge, or can end up on the wrong branch".

Actually, it is worse than this.   For complex arguments with magnitude around 1e-6, the result seems to randomly jump between branches.

I have put a C code which does not have this problem at http://keithbriggs.info/software/LambertW_complex_00.c.    It could serve as a replacement.

**Comment by person142** [comment]
(1) It would be good to provide some concrete examples of incorrect results from the Lambert W function. (Not that I doubt you; just would be helpful.)
(2) Is the C++ code referenced in your implementation license compatible?

Note that a priori I would prefer to patch the Cython code.

**Comment by person142** [comment]
Note also that we cannot use C99 complex numbers.

**Comment by keithbriggs** [comment]
In this table, the first number is the argument z, and the second is the result of my code for W(z,1), which I believe to be correct, and the third the result from scipy lambertw(z,1).


I don't know about the conditions on the C++ code, but mine is virtually a complete rewrite, and I release it for any use.


Keith


(-16.661456183635597-5.834628726021062j) (-16.6614561836-5.83462872602j)
(-7.249999999988568e-07-7.250010512511432e-07j)

(-7.24999999999e-07-7.25001051251e-07j) (-16.601264899596167+0.8356949403202577j)(-16.6012648996+0.83569494032j)
(-7.25e-07-7.25e-07j) (-16.601264899596167+0.8356949403202577j) (-16.6012648996+0.83569494032j)
(-2.050609665440988e-06-2.050609665440988e-06j) (-15.492630358654822+0.8395344954892698j) (-15.5618798228-5.85780212589j)
(-8.10574641843674e-06-8.10574641843674e-06j) (-14.018562205934419+0.8456486453183345j) (-14.103246614-5.89362110574j)
(-2.2926513036220752e-05-2.2926513036220752e-05j) (-12.895712108737715+0.8513181084866528j) (-12.9957053593-5.92559073097j)
(-6.484597134749391e-05-6.484597134749391e-05j) (-11.764677492261448+0.8582178709378433j) (-11.8844164661-5.96282136365j)
(-0.0002563262081801235-0.0002563262081801235j) (-10.253712994351385+0.8700473272495205j) (-10.2537129944+0.87004732725j)
(-1.45e-06-1.45e-06j) (-15.862740499815922+0.8381891928106647j) (-15.9287577946-5.84974075727j)
(-4.101219330881976e-06-4.101219330881976e-06j) (-14.750562127334796+0.8424492097739875j) (-14.8270215412-5.87504725963j)
(-1.621149283687348e-05-1.621149283687348e-05j) (-13.270828527883186+0.8493092088215657j) (-13.3652955116-5.91440283169j)
(-4.5853026072441504e-05-4.5853026072441504e-05j) (-12.142701257307456+0.8557568298232214j) (-12.255269012-5.94975590883j)
(-0.00012969194269498783-0.00012969194269498783j) (-11.005214542234283+0.8637204529664044j) (-11.1414425948-5.99116671492j)
(-0.000512652416360247-0.000512652416360247j) (-9.483116690064243+0.8776879317039217j) (-9.48311669006+0.877687931704j)
(-3.625e-06-3.625e-06j) (-14.88289253830408+0.8419066929432933j) (-14.9579889978-5.87186056213j)
(-1.025304832720494e-05-1.025304832720494e-05j) (-13.765409547847678+0.8468401603327513j) (-13.853236013-5.90044110891j)
(-4.052873209218369e-05-4.052873209218369e-05j) (-12.277078495236957+0.8549215155338199j) (-12.3872434578-5.94526711178j)
(-0.00011463256518110375-0.00011463256518110375j) (-11.140808952748497+0.8626780065020536j) (-11.2738683654-5.98588908176j)
(-0.00032422985673746953-0.00032422985673746953j) (-9.993184470945565+0.8724853741466488j) (-9.99318447095+0.872485374147j)
(-0.0012816310409006174-0.0012816310409006174j) (-8.453097436045459+0.8903380918625741j) (-8.45309743605+0.890338091863j)


________________________________

**Comment by keithbriggs** [comment]
What kind of complex numbers can you use?


K
________________________________

**Comment by person142** [comment]
Thanks for the data!

> mine is virtually a complete rewrite, and I release it for any use. 

Unfortunately this could still be an issue if you read an incompatible code and then wrote yours; https://en.wikipedia.org/wiki/Clean_room_design. The Lambert W function is well understood, however, so it should not be hard to fix the issues based purely on the literature.

> What kind of complex numbers can you use?

Cython, C++, or Fortran. Cython is preferred these days because it's more readable for developers who don't know the latter two languages.

**Comment by keithbriggs** [comment]
Ok.  The two main issues are:

1. getting a good enough initial value before starting the Halley iteration; a Padé approximant seems to be essential for the 0 and -1 branches (at least - it might be an advantage in other branches too)

2. getting an appropriate stopping condition for the Halley iteration

**Comment by person142** [comment]
I see; looks like Corless et al. mention that this is done in the Maple implementation but it wasn't put into the SciPy code.

**Comment by person142** [comment]
> (-16.661456183635597-5.834628726021062j) (-16.6614561836-5.83462872602j) (-7.249999999988568e-07-7.250010512511432e-07j)

Maybe there is a bug in your data? I get:

```
>>> import scipy; print(scipy.__version__)
1.1.0.dev0+ee65304
>>> import scipy.special as sc
>>> import mpmath
>>> z = -16.661456183635597-5.834628726021062j
>>> sc.lambertw(z, 1)
(1.7508890166305466+2.515669686600404j)
>>> mpmath.lambertw(z, 1)
mpc(real='1.7508890166305464', imag='2.515669686600404')
```

Also: https://www.wolframalpha.com/input/?i=LambertW%5B1,+-16.661456183635597-5.834628726021062I%5D

**Comment by person142** [comment]
Ah, this makes more sense:

```
>>> mpmath.lambertw(-7.249999999988568e-07-7.250010512511432e-07j, 1)
mpc(real='-16.601264130740653', imag='0.83569571414112731')
>>> sc.lambertw(-7.249999999988568e-07-7.250010512511432e-07j, 1)
(-16.601264130740653+0.83569571414112742j)
```

https://www.wolframalpha.com/input/?i=LambertW%5B1,+7.249999999988568e-07-7.250010512511432e-07i%5D

Though there is little agreement between the data points...

**Comment by person142** [comment]
Ok, `z = -2.050609665440988e-06-2.050609665440988e-06j` is quite a good demo:

```
>>> z = -2.050609665440988e-06-2.050609665440988e-06j
>>> mpmath.lambertw(z, 1)
mpc(real='-15.492630358654822', imag='0.83953449548926995')
>>> sc.lambertw(z, 1)
(-15.56187982278745-5.8578021258881581j)
```

https://www.wolframalpha.com/input/?i=LambertW%5B1,+-2.050609665440988e-06-2.050609665440988e-06I%5D

showing `sc.lambertw` quite clearly in disagreement with mpmath and Mathematica.

**Comment by person142** [comment]
Ok, there's https://github.com/scipy/scipy/pull/8028 which starts fixing `lambertw`. I haven't got to improving the initial guess yet because there turned out to be more problems which needed fixing first.

**Comment by pv** [comment]
gh-8028 was merged some years back --- did it fix this?

**Comment by person142** [comment]
IIRC improvements still need to be make for `W(z, 1)`, which has been on my todo list I guess several years now.

**Comment by mdhaber** [comment]
SciPy agrees with `mpmath` for all examples here.

<details>

```python3
import numpy as np
from scipy import special

from mpmath import mp
mp.dps = 50

x = [
    (-16.661456183635597-5.834628726021062j),
    -7.24999999999e-07 - 7.25001051251e-07j,
    -7.25e-07 - 7.25e-07j,
    -2.050609665440988e-06 - 2.050609665440988e-06j,
    -8.10574641843674e-06 - 8.10574641843674e-06j,
    -2.2926513036220752e-05 - 2.2926513036220752e-05j,
    -6.484597134749391e-05 - 6.484597134749391e-05j,
    -0.0002563262081801235 - 0.0002563262081801235j,
    -1.45e-06 - 1.45e-06j,
    -4.101219330881976e-06 - 4.101219330881976e-06j,
    -1.621149283687348e-05 - 1.621149283687348e-05j,
    -4.5853026072441504e-05 - 4.5853026072441504e-05j,
    -0.00012969194269498783 - 0.00012969194269498783j,
    -0.000512652416360247 - 0.000512652416360247j,
    -3.625e-06 - 3.625e-06j,
    -1.025304832720494e-05 - 1.025304832720494e-05j,
    -4.052873209218369e-05 - 4.052873209218369e-05j,
    -0.00011463256518110375 - 0.00011463256518110375j,
    -0.00032422985673746953 - 0.00032422985673746953j,
    -0.0012816310409006174 - 0.0012816310409006174j,
    -2.050609665440988e-06-2.050609665440988e-06j
]

@np.vectorize
def lambertw_mp(x, k):
    return complex(mp.lambertw(x, k))

res = special.lambertw(x, 1)
ref = lambertw_mp(x, 1)

np.testing.assert_allclose(res.real, ref.real, rtol=5e-16)
np.testing.assert_allclose(res.imag, ref.imag, rtol=5e-16)
```

</details>

so I think this can be closed.
