### ISSUE TITLE
Suggestions for orthogonal polynomials; recurrence relation, evaluation

### ISSUE THREAD

**Issue by nschloe** [scipy/scipy#8025]
Right now, orthogonal polynomials in scipy are just that: polynomials. A prototypical use case is
```python
import scipy.special                          
poly = scipy.special.jacobi(5, 0, 0)
```
which returns a `scipy.special.orthogonal.orthopoly1d` object that prints as
```
       5        3             2
7.875 x - 8.75 x - 4.372e-16 x + 1.875 x
```
i.e., it is probably stored in terms of its polynomial coefficients. Likewise, this object can be used to evaluate the polynomial like
```python
import numpy
val = numpy.polyval(poly, 0.5)
```
With `n=5`, everything is fine, but there are problems of accuracy when `n` grows a bit larger:
```python
val = numpy.polyval(scipy.special.jacobi(80, 0, 0), 0.5)
```
gives `-0.0379483858698` when the actual value is `-0.0246497171653565` – an error of over 50%. Indeed, the coefficients of the ordinary representation vary from 10^{-16} to 10^28. In fact, it is known that evaluating the polynomial like this is numerically unstable. For example, [Gautschi says](https://doi.org/10.1137/0903018):

>  Knowing the coefficients alpha_k, beta_k it is easy to compute the polynomials pi_r and their derivatives recursively by (1.2) and the relations obtained from (1.2) by differentiation, for any fixed within or without the spectrum of dA. The procedure is not only straightforward, but also quite stable, much in contrast to the evaluation of pi_r in terms of its coefficients.

This leads to the insight that representing orthogonal polynomials in terms of their polynomial coefficients is not appropriate. A better approach is to represent the polynomials by their recurrence coefficients. In fact, I'm not aware of literature that uses a different representation than that.

I would argue that scipy should adopt that in its implementation, and perhaps optionally provide a function like `get_polynomial_coefficients()` for whoever really wants those. In most cases, people probably just want to evaluate polynomials at certain points, for which case there should be a simple method using the recurrence.

(See [orthopy](https://github.com/nschloe/orthopy/blob/master/orthopy/tools.py#L79), a small package of mine.)

**Comment by nschloe** [comment]
I just found `scipy.special.eval_*` which does what I described. Never mind then! :smile:

**Comment by person142** [comment]
Just a note that yes, the orthogonal polynomials are in some sense legacy in that everyone knows there are problems with them, but we haven't yet been able to figure out the right replacement. (If you search around you can find several discussions, like e.g. https://github.com/scipy/scipy/pull/6591.)
