### ISSUE TITLE
linalg.expm raises overflowerror for some inputs

### ISSUE THREAD

**Issue by ucyo** [scipy/scipy#8029]
I'm calculating the Pascal matrix according to [this formula].(https://en.wikipedia.org/wiki/Pascal_matrix#Construction)
linalg.expm gives me the wrong results.

### Reproducing code example:
```
depth = 9
linalg.expm3(np.diag(np.arange(1,depth),-1)).astype(int)
```

### Expected result:
```
array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  2,  1,  0,  0,  0,  0,  0,  0],
       [ 1,  3,  3,  1,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  4,  1,  0,  0,  0,  0],
       [ 1,  5, 10, 10,  5,  1,  0,  0,  0],
       [ 1,  6, 15, 20, 15,  6,  1,  0,  0],
       [ 1,  7, 21, 35, 35, 21,  7,  1,  0],
       [ 1,  8, 28, 56, 70, 56, 28,  8,  1]])
```
### Result:
```
array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  3,  1,  0,  0,  0,  0,  0],
       [ 0,  4,  6,  4,  1,  0,  0,  0,  0],
       [ 0,  5, 10, 10,  5,  1,  0,  0,  0],
       [ 0,  6, 15, 20, 15,  6,  1,  0,  0],
       [ 0,  7, 21, 35, 35, 21,  7,  1,  0],
       [ 0,  8, 27, 55, 70, 55, 28,  8,  1]])
```
### Additional remarks:

- It is strange that the the ones are missing in the first column
- Changing `depth` to `7` or `8` will give a zero division error:

```
RuntimeWarning: divide by zero encountered in log2
  s = max(int(np.ceil(np.log2(eta_5 / theta_13))), 0)
```
- `linalg.expm3` works flawless

### Scipy/Numpy/Python version information:
```
0.19.1 1.13.1 sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
Use linalg.expm, not expm3 (which is deprecated), and ensure input 
arrays are float:
```
 >>> linalg.expm(np.diag(np.arange(1.0, depth),-1)).astype(int)
array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  2,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  3,  2,  1,  0,  0,  0,  0,  0],
        [ 0,  3,  5,  3,  1,  0,  0,  0,  0],
        [ 0,  4, 10, 10,  5,  0,  0,  0,  0],
        [ 0,  6, 15, 20, 15,  5,  0,  0,  0],
        [ 0,  7, 21, 35, 35, 21,  7,  1,  0],
        [ 0,  7, 28, 56, 70, 56, 28,  8,  1]])
```

**Comment by pv** [comment]
Also note that `.astype(int)` rounds down, not to nearest integer, so 
you probably want `np.round(...).astype(int)`

**Comment by pv** [comment]
The overflowerror for depth=6,7 however remain present in 1.0.0rc1.

**Comment by pv** [comment]
`ndarray.astype(int)` always rounds down, so e.g. `0.99999999999999922` 
which appears in the matrix becomes 0. The are then correct, and the 
issue is just the estimation of the scaling parameter s.

**Comment by ucyo** [comment]
@pv Thank you very much. `np.round()` solved my problem. So I guess `expm3` changed the default behaviour on purpose and `expm` just accepted the default. The overflowerror still seems weird.

Regarding rounding: It appears that `astype(int)` doesn't round at all. It just clips the fractional part.
