### ISSUE TITLE
Add standard filter types to firwin to set pass_zero intuitively (feature request)

### ISSUE THREAD

**Issue by berndporr** [scipy/scipy#8033]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

In order to create standard filter responses with firwin one needs to undestand the pass_zero parameter. The parameter is internally very useful to set the frequency response at DC but from the outside it's pretty diabolical as it even switches between True/False depending on the number of arguments. I had to have a look at the code of firwin to make sense of it.

For example:
h = firtest.firwin(999,f2*2,pass_zero=False) gives me a highpass whereas
h = firtest.firwin(999,f2*2) gives me a lowpass because pass_zero is True here by default.
which becomes only clear after understanding the parameter pass_zero.
It's even more confusing when looking at:
h = firtest.firwin(999,[f1*2,f2*2])
which gives a bandstop because pass_zero is now False (!) by default.
I'm sure there is a reason behind this but it's not very userfriendly.

Feature request:
Add a parameter called "filtertype" which sets pass_zero and the number of parameters expected as a sanity check:

```
    type2args = { 'lp':[1,True], 'lowpass':[1,True],
                  'hp':[1,False], 'highpass':[1,False],
                  'bs':[2,True], 'bandstop':[2,True],
                  'bp':[2,False], 'bandpass':[2,False] }

    if filtertype is not None:
        ncutoff,pass_zero = type2args[filtertype]
        if ncutoff != cutoff.size:
            raise ValueError("Number of cutoff freq expected:",ncutoff)


```

Essentially just an associative array which keeps the keywords and the expected parameters.

![figure_1](https://user-images.githubusercontent.com/1679394/31583971-ce40b932-b19c-11e7-94a2-0ca66b4e6774.png)
[firwin_fr2.zip](https://github.com/scipy/scipy/files/1385359/firwin_fr2.zip)

I've attached a file containing the original firwin command, a new version with that array in it and the diff. 

I'd be happy to do a pull request if people here like that idea!

Best,
/Bernd Porr

PS: that's a clip I made about this command as part of my teaching which would be much neater with standard parameters for high/low/bs/bp: https://www.youtube.com/watch?v=GpiL9vqQqlE

**Comment by larsoner** [comment]
I agree the `pass_dc` is probably not as intuitive as specifying the filter type, but this function is 7 years old so removing that argument would be difficult from a backward compatibility / deprecation perspective. We could consider adding a `ftype`-like argument and ensuring only one of these two is specified, along the lines of what you suggest, which could be useful. I'm +0 on this because I don't find the `pass_dc` too difficult to work with.

@WarrenWeckesser looks like you worked on this at least 7 years ago. Thoughts on changing the API?

**Comment by berndporr** [comment]
Thanks for the quick comment. As you say it needs to be 100% backwards compatible. The pass_dc parameter is great for geeks like us or people who want to do multiple notches etc. 
I'm thinking of the casual user who just quickly needs a high/low/etc pass.
Indeed. That's what I thought that these arguments then are mutually exclusive and won't break any existing python code using this command.
