### ISSUE TITLE
Deprecating Python 2.7 on windows

### ISSUE THREAD

**Issue by xoviat** [scipy/scipy#8037]
The Python 2.7 EOL is 2020. That is three years away. It may seem like a long time, but consider: if we deprecate Python 2.7 immediately, the message won't actually be released until scipy 1.1, which is likely in six months at least.

**But why only on windows?**

Python's windows ABI "system" means that Python 2.7 on windows is stuck with MSVC 2008. In 2020, when the EOL arrives, Python 2.7 will be using a compiler that is 12 years old. The problems that might crop up over time from supporting this compiler are currently unknown but they could be significant.

**But why now?**

I'm not proposing that Python 2.7 on windows is dropped now. What I'm proposing is a simple message when scipy is imported on Python 2.7 on windows:

`WARNING: Python 2.7 support on Windows is deprecated. Please migrate to a newer Python version`

I am proposing that we put this message into `master` now and have it roll into the next release. People will still be able to use scipy, but letting people know about this now will avoid a potential emergency with MSVC 2008 later.

**Comment by rgommers** [comment]
We're not doing any deprecation warnings for changes to supported versions of Python/NumPy/etc. so no action needed now. The process will be:
1. decide on mailing list when we're dropping 2.7 (for all OSes at once)
2. Update docs, release notes, ``pyproject.toml``, ``__init__.py`` etc.

**Comment by rgommers** [comment]
No action needed, so I'm closing this issue.

**Comment by xoviat** [comment]
I think dropping 2.7 on Windows is significantly more urgent than other operating systems. 2.7/windows is pinning the lapack version and some C libraries.

**Comment by rgommers** [comment]
That's true, but that urgency only determines the date we drop it. There's only extra confusion and complications to be gained from supporting 2.7 on other platforms for longer.

**Comment by pv** [comment]
2020 is only in three years, so I think the chances that MSVC2008 will 
become unsupportable don't look so critical (unless you have something 
specific in mind). Problems that turn up will likely also affect CPython 
so there will be more manpower to find solutions. Of course, it will be 
annoying if Appveyor drops the compiler.

**Comment by pv** [comment]
Also, I think Windows is not pinning the lapack version --- we are using 
mingw64 toolchain for that --- OSX is the problematic platform for that 
due to use of Accelerate.

**Comment by charris** [comment]
One argument for dropping 2.7 is the ability to rely on C99 support, which may allow improvements in the handling of complex numbers among other things. We would also need to drop Python 3.4, but hopefully that isn't too far off in any case.

**Comment by xoviat** [comment]
Yes it is. Especially when building with the Intel stack some users complained about raising the Lapack version.

**Comment by xoviat** [comment]
> Problems that turn up will likely also affect CPython
so there will be more manpower to find solutions

The solution that people have come up with this to fork Python 2.7 into a project called tauthon. People have already had significant issues with using C++ 11 libraries on Python 2.7 that remain unresolved.

**Comment by xoviat** [comment]
Yes but dropping Python 3.4 is not that controversial and I expect that it will happen. Python 2.7 is a different story because it's kind of a zombie.

**Comment by pv** [comment]
The openblas build that we use for Python 2.7 afaik ships with lapack 
3.7. So as long as MSVC is capable of linking to DLLs then I think it 
will not be a problem for us.

**Comment by xoviat** [comment]
@pv @clgohike complained because he couldn't use MKL.

**Comment by charris** [comment]
My own current thinking is to drop both 2.7 and 3.4 from NumPy at the end of 2018, maybe with a commitment to another year of bug fix support for the last version supporting 2.7. That would make the drop somewhere around NumPy 1.16 or 1.17. I know that that is somewhat controversial, but NumPy is already pretty decent and Python 3 is coming on strong.

The other option might be to drop in the first half of 2020, which would be consistent with Fedora making Python 3 the default in Fedora 32. I think we could make an exception for windows and drop earlier as supporting 2.7 on windows sticks us with an obsolete compiler and windows seems ahead of the Python 3 curve in any case.

**Comment by xoviat** [comment]
That's incidentally why I don't think we should drop support across the board (on all operating systems). Maintaining 2.7 on Linux is not so much of a problem because, unlike Windows, linux has decent compiler support for that Python. Also unlike Windows, RHEL users may not be using a newer Python while on Windows its much easier to get one. My thinking is there will be much less pushback for Windows and for that, significantly more maintenance will be saved.

**Comment by rgommers** [comment]
> Maintaining 2.7 on Linux is not so much of a problem because

That throws away most of the benefits though. If we're dropping 2.7 then being able to use things like the ``@`` operator would be really really nice.

Plus it makes the story more confusing for users, and complicates things for packages depending on scipy.

**Comment by xoviat** [comment]
Well if everyone is on board to drop support at the end of 2018 then I have no problems. But ultimately, compiler issues are much more serious then having to use ugly syntax.
