### ISSUE TITLE
In ConvexHull docs, an unnecessary point is plotted

### ISSUE THREAD

**Issue by jondo** [scipy/scipy#8039]
In the example of https://scipy.github.io/devdocs/generated/scipy.spatial.ConvexHull.html, I see no reason for additionally plotting the first hull point (in red). So I think that the code line
```python
plt.plot(points[hull.vertices[0],0], points[hull.vertices[0],1], 'ro')
```
should be removed for more clarity.

**Comment by pv** [comment]
If you don't plot it, how do you see that the hull points are ordered 
counterclockwise?

**Comment by jondo** [comment]
How do you see it from this single point? For this, it would make sense to additionally plot the second point, in a different color.

**Comment by pv** [comment]
Follow the dotted line.

**Comment by jondo** [comment]
Ah! Sorry for not noticing the gap in the line.
