### ISSUE TITLE
welch method unexpected results for low frequency

### ISSUE THREAD

**Issue by AlexS12** [scipy/scipy#8045]
When computing the PSD of the synthetic signal below using welch method I obtain an unexpected peak near 0 Hz with no physical meaning. The equivalent MATLAB code produces different results for that region.

### Python code example:
```
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import welch, hanning

x = np.linspace(0, 10, 100001)
dt = x[1] - x[0]
fs = 1 / dt

a1 = 1
f1 = 500

a2 = 10
f2 = 2000

y = a1 * np.sin(2*np.pi*f1*x) + a2 * np.sin(2*np.pi*f2*x)

datos = y

nblock = 1024
overlap = 128
win = hanning(nblock, True)

f, Pxxf = welch(datos, fs, window=win, noverlap=overlap, nfft=nblock, return_onesided=True)

plt.semilogy(f, Pxxf, '-o')

plt.grid()
plt.show()
```

### MATLAB code example
```
x = linspace(0, 10, 100001);
dt = x(2) - x(1);
Fs = 1 / dt;
a1 = 1;
f1 = 500;
a2 = 10;
f2 = 2000;
y = a1 * sin(2*pi*f1*x) + a2 * sin(2*pi*f2*x);

nblock=1024;
overlap=128;
windowsel=hann(nblock);
[Pxx,f]=pwelch(y,windowsel,overlap,nblock,Fs,'onesided');
figure()
semilogy(f,Pxx, '-o')
```

### Scipy/Numpy/Python version information:
```
Scipy 0.19.1
NumPy 1.13.1
Python 3.6.2 final (serial 0)
```
Matlab:
![MATLAB results](https://i.stack.imgur.com/zZUPi.png)
Python
![PYTHON results](https://i.stack.imgur.com/l3jFr.png)

**Comment by larsoner** [comment]
I can reproduce with simplified scripts that only process a single window and shorter signals:
```
fs = 10.
n_samp = 32
t = np.arange(n_samp) / fs
y = np.sin(2*np.pi*2*t)
win = windows.hann(n_samp, False)
f, Pxxf = welch(y, fs, window=win, noverlap=0, nfft=n_samp,
                return_onesided=True)
plt.semilogy(f, Pxxf, '-o')
plt.xlim([0, 5])
plt.ylim([1e-7, 1])
plt.show()
```
![figure_3](https://user-images.githubusercontent.com/2365790/31680680-00ef9680-b343-11e7-9cea-2490080d2a1d.png)

MATLAB:
```
clear all; close all; home;
fs = 10;
n_samp = 32;
x = (0:n_samp-1) / fs;
y = sin(2*pi*2*x);
overlap=0;
windowsel=hann(n_samp);
[Pxx,f]=pwelch(y,windowsel,overlap,n_samp,fs,'onesided');
figure();
semilogy(f,Pxx, '-o');
```
![untitled](https://user-images.githubusercontent.com/2365790/31680686-0a398106-b343-11e7-84cf-5d9a72212803.png)

But Octave at least agrees with our output:
![octave](https://user-images.githubusercontent.com/2365790/31681324-edbea536-b344-11e7-9935-52f64cf3aa47.png)

I'm not sure what MATLAB is doing to change/correct these values.

**Comment by AlexS12** [comment]
I will have a look at the implementation of scipy and try to figure out where this behaviour might be coming from. Do you have any suggestion on that?

**Comment by AlexS12** [comment]
I have also found this matlab example that might be relevant: https://es.mathworks.com/matlabcentral/answers/33653-psd-estimation-fft-vs-welch
It compares results obtained using FFT with results using PSD and both show the same behaviour near 0 Hz. It may be a good starting point.

**Comment by ewmoore** [comment]
Try using `detrend=False`.  `signal.welch` defaults to subtracting the mean of the data (`detrend='constant'`) which seems to be giving you this DC artifact.

**Comment by larsoner** [comment]
Thanks @ewmoore I can confirm `detrend=False` fixes it.

**Comment by AlexS12** [comment]
Awesome! Thank you!

**Comment by akukuq** [comment]
It occurred to me that the root cause of this low-frequency energy showing up in the estimated PSD is that detrending takes place _before_ windowing (check `_fft_helper()`). This means that the DC component of the windowed frame is not zero even though it has been detrended to have zero mean!

To illustrate, I modified the example provided by @larsoner:
```
fs = 10.
n_samp = 32
t = np.arange(n_samp) / fs
y = np.sin(2*np.pi*2*t)
win = windows.hann(n_samp, False)
windowed_y = y*win  # apply window already now
f, Pxxf = welch(windowed_y , fs, window='boxcar', noverlap=0)  # do not apply it here
plt.semilogy(f, Pxxf, '-o')
plt.xlim([0, 5])
plt.ylim([1e-7, 1])
plt.show()
```
This results in:
![image](https://github.com/scipy/scipy/assets/25489199/b48dc9f1-a8cc-4f46-81c5-944d983cf3be)
Which has zero energy at DC, as expected given the default detrending method.

@larsoner, do you think this qualifies as a bug that should be reported?

Sorry for adding a comment years after this issue was marked as closed.

**Comment by lucascolley** [comment]
(as a procedural note, feel free to open a new issue in case this doesn't receive a response)
