### ISSUE TITLE
MAINT: stats: `ks_2samp` assigns variable without use

### ISSUE THREAD

**Issue by rspadim** [scipy/scipy#8046]
https://github.com/scipy/scipy/blob/v0.14.0/scipy/stats/stats.py#L3873

    data1, data2 = map(asarray, (data1, data2))
    n1 = data1.shape[0]   <- hello n1? shouldn't remove this?
    n2 = data2.shape[0]   <- shouldn't remove this?
    n1 = len(data1)   <- hello n1?
    n2 = len(data2)   <- shouldn't remove this?

**Comment by pv** [comment]
https://github.com/scipy/scipy/blob/master/scipy/stats/stats.py#L4755
