### ISSUE TITLE
Bug in sympy.physics.wigner 

### ISSUE THREAD

**Issue by Kenny3141** [scipy/scipy#8047]
When using the package wigner_9j from sympy.physics.wigner it gives wrong results for some specific wigner 9j symbols. The example given below does in fact only have integer or half-integer input and furthermore fulfills the triangle rule, yet it still returns an error. I cross checked with the module given on the webpage from Anthony Stone ( http://www-stone.ch.cam.ac.uk/cgi-bin/wigner.cgi?symbol=9j&a=1%2F2&b=1%2F2&c=0&d=1%2F2&e=3%2F2&f=1&g=0&h=1&i=1 ) where you can see that the correct result should be 1/6. I also intrinsically found the same result when comparing with contact matrix elements for the scattering in hadronic molecules.  Since the code is rather complicated I could not find the bug myself.

### Reproducing code example:
```
from sympy.physics.wigner import wigner_9j

wigner_9j(1/2,1/2,0, 1/2,3/2,1, 0,1,1 ,prec=16) 

```

### Error message:
```
    raise ValueError("j values must be integer or half integer and fulfill the triangle relation")

ValueError: j values must be integer or half integer and fulfill the triangle relation
```

**Comment by pv** [comment]
Note: wrong bug tracker.
