### ISSUE TITLE
FreeBSD regression in 0.18 (scipy.spatial.Voronoi - qhull?)

### ISSUE THREAD

**Issue by dimpase** [scipy/scipy#8051]
In 0.18 (or 0.18.1) a FreeBSD-specific regression was introduced: the following worked on
0.17.1:
```
>>> import numpy as np
>>> points = np.array([[0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1, 2],[2, 0], [2, 1], [2, 2]])
>>> from scipy.spatial import Voronoi
>>> Voronoi(points)
```
but gives a Segmentation fault (Python crashes) with 0.18.1 and with 0.19.1.

```
Python 2.7.14 (default, Oct 17 2017, 22:14:53) 
[GCC 4.2.1 Compatible Clang 6.0.0 ] on freebsd11
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
('0.18.1', '1.12.1', sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0))
```
It does not matter whether it is built with clang 6, or clang 3.9, or clang 5, or gcc 6.3, so this. The coredumps point to `qhull.so`.

What exactly has happened between these versions? A qhull update, a qhull interface update?

**Comment by pv** [comment]
Git log will tell what changed

**Comment by xoviat** [comment]
Github can also display the diff: https://github.com/scipy/scipy/compare/maintenance/0.18.x...scipy:maintenance/0.17.x

I can't see changes to qhull.

**Comment by pv** [comment]
Looks like both qhull update and interface changes. Why freebsd-specific is unclear; does it work with gcc on freebsd?

**Comment by dimpase** [comment]
It turns out that, unlike in the setup I work on i.e. [Sage port to FreeBSD](https://trac.sagemath.org/ticket/22679), using system Python 2.7.14 with the scipy 0.18.1 (or with the master) does not reproduce the error (not sure why ATM). Thus it's almost certainly not something to do with scipy.  

Sorry for noise.

**Comment by rgommers** [comment]
@dimpase can you comment here instead of at https://github.com/scipy/scipy/commit/e1f15525e2d8df591017d6d557e297cddfcafbcc#commitcomment-31472199? Should we reopen this issue? Sounds like perhaps the default build config on OpenBSD is the problem? If multiple other builds on OpenBSD are fine and this doesn't happen on other platforms, then it sounds like perhaps what `numpy.distutils` does for a basic `python setup.py install` is not quite right.
