### ISSUE TITLE
Random variate distribution random_state set after init does not carry over to frozen distribution

### ISSUE THREAD

**Issue by ahrenberg** [scipy/scipy#8053]
If I update the random_state attribute of a distribution and then freezes the same, I would intuitively expect the random_state of the new frozen RV to be the same as the one I just set in the original. 
This does not seem to be the case, instead the frozen distribution has random_state set to np.random.mtrand._rand. 

On the other hand, if the state is set when creating the rv object, using the seed parameter, it is copied.

Theese two behaviours is somewhat at odds. I would expect the state to be transferred to the frozen distribution no matter if it is set at creation or using the attribute.

In practical terms, this means that when using random seeds with a frozen version of an existing distributions in scipy.stats, a random_state must be provided explicitly when calling methods (using the optional seed parameter). It is not possible to freeze a distribution with a specific seed. However as the seed of the general distribution can be set before freezing, it is easy to introduce unexpected behaviour.

I believe that this is a bug, but if the current behaviour is indeed as intended, it might be better not exposing the random_seed attribute of the object, allowing only the seed parameter to methods in both frozen and unfrozen distributions.

However, the best solution in my opinion would be to having the frozen object copy random_state from the distribution. I believe this is the behaviour most would expect, and would allow for efficient seeding.

### Reproducing code example:
```
import numpy as np
import scipy.stats

# Make a random state
rs = np.random.RandomState(1)

# Create basic RV object with default seed. 
# Could also have been one of the existing distributions, eg. stats.norm
rand_var_f = scipy.stats.rv_continuous()

# Then set the attribute.
rand_var_f.random_state = rs
# Check that it has been set.
assert(rand_var_f.random_state == rs) # Works

# Freeze
rv_frozen_f = rand_var_f()
# Check if match.
assert(rv_frozen_f.random_state == rs) # Fail.

```

State above is actually the same as in np.random.mtrand, so the following would pass
```
# State is actually the same as np.random.mtrand
assert(rv_frozen_f.random_state == np.random.mtrand._rand) # Works
```

### Working example, state set at creation
Setting the state when the rv_continious object is created will cause random_state to be transfered however.
```
import numpy as np
import scipy.stats

# Make a random state
rs = np.random.RandomState(1)

# Create RV with seed as init parameter
# This works as expected.
rand_var_s = scipy.stats.rv_continuous(seed=rs)
# Tests
assert(rand_var_s.random_state == rs) # Works
rv_frozen_s = rand_var_s()
assert(rv_frozen_s.random_state == rs) # Works.
```

### Scipy/Numpy/Python version information:
```
0.19.1 1.13.3 sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)
```

**Comment by ev-br** [comment]
Maybe freezing a distribution should grow an optional random_state parameter (with a default of None to preserve backwards compatibility). A PR is welcome, I'd say.
