### ISSUE TITLE
Gauss Hypergeometric function (hyp2f1) diverges in two small regions of the complex plane

### ISSUE THREAD

**Issue by FormerPhysicist** [scipy/scipy#8054]
There are two narrow wedges in the complex plane where gauss's hypergeometric function (hyp2f1) gives implausibly large values when the function there is well defined.  In polar coordinates these wedges are approximately given by:

0.9 < r < 1.0
pi/3 < theta < pi/2

0.9 < r < 1.0
-pi/2 < theta < -pi/3

When I looked at the source code (the subroutine HYGFZ in scipy/special/specfun/specfun.f), I noticed that in the half annulus defined by 0.9 < |z| < 1.0 and real(z)>0, HYGFZ attempts to use the "1-z" transformation (see [eq 15.8.4](http://dlmf.nist.gov/15.8)) to evaluate the hypergeometric function. However the series associated with this transformation only converges when |1-z|<1. In the wedge regions given above, |1-z|>1 and so the method fails. 

### Reproducing code example:
```
>>> import numpy as np
>>> from scipy.special import hyp2f1
>>> theta=np.linspace(np.pi/3.0,np.pi/2.0,10,dtype=np.float)
>>> z=0.95*np.exp(1.j*theta)
>>> hyp2f1(1.54,1.67,5.21,z)
array([ -2.14630605e+03 +6.71599145e+03j,
        -2.31991069e+14 +1.69689842e+14j,
        -2.50252397e+24 -3.16737713e+23j,
        -2.97640356e+33 -4.56037250e+33j,
         1.21082099e+42 -3.00909950e+42j,
         5.82402044e+50 -8.54809272e+49j,
         2.01184470e+58 +2.92349095e+58j,
        -4.16032387e+65 +6.43973917e+65j,
        -6.17050365e+72 -1.47233313e+72j,  -1.20089983e+78 -2.12896064e+79j])
```
In contrast, the first value in the z array should be (according to mpmath):
```
>>> import mpmath
>>> mpmath.hyp2f1(1.54,1.67,5.21,z[0])
mpc(real='0.9894407614789662', imag='0.52327754379886682')
```

### Scipy/Numpy/Python version information:
scipy, numpy, sys versions
```
>>> print sc.__version__,np.__version__,sys.version_info
1.0.0.dev0+b579459 1.13.1 sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
```

**Comment by xoviat** [comment]
The routine in `specfun.f` is probably dead code. `hyp2f1` sources are here:

https://github.com/scipy/scipy/blob/59d44488320cca317cee802f80e29af6eb77b731/scipy/special/cephes/hyp2f1.c#L89

**Comment by FormerPhysicist** [comment]
I'd like to emphasize that this issue isn't just something I saw when looking at the source code, but is something that is reproducible; see my example above in "Reproducing code example."

Also I'm pretty sure that specfun.f is the source code for hyp2f1 when z is *complex*.
The source code for hyp2f1 with real argument z is given in [/scipy/special/cephes/hyp2f1.c](https://github.com/scipy/scipy/blob/59d44488320cca317cee802f80e29af6eb77b731/scipy/special/cephes/hyp2f1.c).  

At least that is what I gathered when looking at the python script [_generate_pyx.py](https://github.com/scipy/scipy/blob/59d44488320cca317cee802f80e29af6eb77b731/scipy/special/_generate_pyx.py) which generates the cython code that links the hyp2f1 ufunc with the source files of hyp2f1.c and [specfun_wrappers.c](https://github.com/scipy/scipy/blob/59d44488320cca317cee802f80e29af6eb77b731/scipy/special/specfun_wrappers.c)--the later of which is the c wrapper for the Fortran library of special functions in specfun.f.

**Comment by xoviat** [comment]
That's correct and it is in fact why I deleted my comment.

**Comment by xoviat** [comment]
@FormerPhysicist Do you have a computable approximation that we can use for those parameters?

**Comment by FormerPhysicist** [comment]
I've been using [mpmath](http://mpmath.org/doc/1.0.0/functions/hypergeometric.html)'s version to benchmark scipy's implementation. So for example when I evaluate hyp2f1 at z=0.95 exp(pi/3 j) using *mpmath* I get the following:
```
>>> mpmath.hyp2f1(1.54,1.67,5.21,z[0])
mpc(real='0.9894407614789662', imag='0.52327754379886682')
```
In contrast, scipy's version of hyp2f1 gives the following (from my example above):
```
array([ -2.14630605e+03 +6.71599145e+03j,
```
Assuming mpmath is right, this means scipy is about 3 orders of magnitude off...

**Comment by xoviat** [comment]
mpmath is probably correct. `hyp2f1` is just a bunch of specific cases that need to be handled. Ultimately, someone will need to come up with a formula for the r and theta values. I was simply wondering whether you knew what the formula would be.

**Comment by FormerPhysicist** [comment]
Oh I see what you mean; the exact region in the complex plane where hyp2f1 fails are those points z that satisfy the following:

0.9 < |z| < 1.0 and real(z)>0 and |z-1|>1.0

There is an analytic continuation formula that contains these regions; I've actually am thinking about submitting a PR to fix this issue.  I've emailed the scipy-dev email list with my idea to see what they think. An excerpt of my email:

> My PR would basically implement the analytic continuation formula given in this paper: ([Buhring, An Analytic Continuation of the Hypergeometric Series](http://epubs.siam.org/doi/10.1137/0518066)). I've already implemented this series in some prototype code written in Fortran and it agrees well with the values returned by mpmath's implementation of hyp2f1.
