### ISSUE TITLE
Subclass of scipy.stats.rv_discrete initiated with values throws an AttributeError on pmf method

### ISSUE THREAD

**Issue by antshk** [scipy/scipy#8057]
Subclass of `scipy.stats.rv_discrete` initiated with values (i.e `rv_sample`) throws an error if `pmf `method is called. The same without subclassing works fine.

### Reproducing code example:
```
from scipy import stats 

class subc_rv_discrete(stats.rv_discrete):
    pass

xk = (0,1,2,3)
pk = (0.1, 0.2, 0.3, 0.4)

inst = subc_rv_discrete(values=(xk, pk))
inst.pmf(xk)
```
### Error message:
```
Traceback (most recent call last):

  File "<ipython-input-48-129655c38e6a>", line 10, in <module>
    inst.pmf(xk)

  File "C:\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 2832, in pmf
    args, loc, _ = self._parse_args(*args, **kwds)

AttributeError: 'rv_sample' object has no attribute '_parse_args'
```
### Scipy/Numpy/Python version information:
```
0.19.0 1.12.1 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by ev-br** [comment]
Can you share a use case where you need such a subclass?

**Comment by josef-pkt** [comment]
trying this out a bit
going through the regular subclassing creates a rv_sample class and doesn't __init__ the correct class

the following works for me with 0.18.1 (which I have open right now)

```
from scipy.stats._distn_infrastructure import rv_sample


class subc_rv_discrete(rv_sample):


    def __new__(cls, *args, **kwds):
        return super(subc_rv_discrete, cls).__new__(cls)


xk = [0,1,2,3]
pk = [0.1, 0.2, 0.3, 0.4]

inst = subc_rv_discrete(values=(xk, pk))
print(inst.pmf(xk))
print(inst.__class__)
```

**Comment by ev-br** [comment]
Ok, indeed, in general, subclassing is the way to go. Unless you hit this ugly corner :-). The dispatch in `__new__` is ugly and I'm not sure it can be made to play with subclassing. Like, try giving your class both __init__ and __new__? Maybe the correct thing to do is to subclassing rv_sample direcyly

**Comment by antshk** [comment]
@josef-pkt indeed this does the job. To spread the word, can you please answer the corresponding [stackoverflow](https://stackoverflow.com/questions/46635803/instance-of-scipy-stats-rv-discrete-subclass-throws-error-on-pmf-method) question and I will accept it.

Should the issue be closed or maybe a pull request be made?

**Comment by josef-pkt** [comment]
We need a PR with at least putting `rv_sample` in the `stats` and `stats.distributions` namespace.

@ev-br AFAICS, we could deprecate the `values` keyword in `rv_discrete` and then we could remove the `__new__` delegation to the rv_sample subclass in two versions or so. Users can use the `rv_sample` class directly.
That will need some adjustments to the unit tests, I guess.

**Comment by scottshambaugh** [comment]
Commenting to link in [another stackoverflow question](https://stackoverflow.com/questions/60981879/creating-scipy-stats-random-variable-subclass-does-not-result-in-expected-object) where this issue has popped up.

**Comment by mdhaber** [comment]
When `rv_sample` is made public, it would be good to tweak the logic that detects whether an argument is within the support or not. As discussed in gh-15932, 
floating point errors make exact equality comparison too unreliable when, say, `loc != 0`.

**Comment by mdhaber** [comment]
In-between `integrate` PRs sometime, would exposing `rv_sample` and deprecating that use of `rv_discrete` be something you're interested in doing? I'd be happy to review.

**Comment by ev-br** [comment]
@mdhaber yup, ok, am adding it to my todo list

**Comment by ev-br** [comment]
Reopen because of gh-17471
