### ISSUE TITLE
Zero padding for Periodogram when nfft > signal length?

### ISSUE THREAD

**Issue by Scoodood** [scipy/scipy#8060]
Perhaps an Improvement Suggestion?

Referring to [line 269-275](https://github.com/scipy/scipy/blob/master/scipy/signal/spectral.py#L269) on spicy/signal/spectral.py
```
    if nfft is None:
        nperseg = x.shape[axis]      # <-- ok make sense
    elif nfft == x.shape[axis]:
        nperseg = nfft
    elif nfft > x.shape[axis]:
        nperseg = x.shape[axis]       # <-- confusing features, should zero pad instead?
    elif nfft < x.shape[axis]:
    ...
```

When user doesn't care about nfft, he won't specify nfft as input parameter, so it is ok to set nperseg = signal length

But when the user specifies nfft as input parameter, that means he cares about the bin frequency resolution on the output. So when the input signal length is < nfft, would it be better to zero pad the input signal so that the segment length become nfft? It makes more sense to me this way.

**Comment by e-q** [comment]
It's not very obvious, but zero padding is indeed what is happening in this case, eventually within the `_fft_helper` function. The value of `nfft` is not being changed, so `periodogram` ends up calling `welch(x,..., nperseg=x.shape[axis], nfft=nfft)`, returning the FFT resolution implied by `nfft`.

```python
In [1]: x = np.random.randn(10)

In [2]: f, p = sig.periodogram(x, nfft=100)

In [3]: f.shape
Out[3]: (51,)
```
[`nperseg` controls the number of data points from the input signal are used, while `nfft` controls the FFT resolution by setting the `n=nfft` keyword argument in the call to the FFT function (which internally takes care of the zero-padding).]
