### ISSUE TITLE
AppVeyor builds appear to be stuck

### ISSUE THREAD

**Issue by person142** [scipy/scipy#8062]
AppVeyor appears to be stuck on cancelling a build:

https://ci.appveyor.com/project/scipy/scipy/history

This seems to be a known problem:

http://help.appveyor.com/discussions/problems/5896-build-stuck-on-cancelling-disallowing-further-builds

Does anyone know of a way to fix it or are we going to have to contact them?

**Comment by xoviat** [comment]
Open an issue in the appveyor/ci repository. they usually fix the problems quickly.

**Comment by xoviat** [comment]
Fixed.
