### ISSUE TITLE
Use JSON in `special/_generate_pyx.py`?

### ISSUE THREAD

**Issue by person142** [scipy/scipy#8080]
Currently the signatures of the special functions are listed in a big string, whose entries look like this:

```
eval_laguerre --    eval_laguerre[double]: dd->d,     eval_laguerre[double complex]: dD->D,     eval_laguerre_l:ld->d -- orthogonal_eval.pxd
```

As the functions gain more dispatches this becomes hard to read. Are there objections to instead putting the signatures in a JSON file, where the previous string would become something like this:

```
"eval_laguerre": {
    "orthogonal_eval.pxd": {
	"eval_laguerre[double]: dd->d",
	"eval_laguerre[double complex]: dD->D",
	"eval_laguerre_l: ld->d"
    }
}
```

**Comment by ilayn** [comment]
Maybe leave the verbose version as a comment too for quick glance-through?

**Comment by rgommers** [comment]
Seems fine to me
