### ISSUE TITLE
special.hyp2f1 returns the wrong values when c-a-b is an integer (for 0.9<|z|<1.0)

### ISSUE THREAD

**Issue by FormerPhysicist** [scipy/scipy#8083]
The hypergeometric function hyp2f1(a,b,c,z) gets the wrong values when c-a-b=integer and z is in the region of the complex plane given by:

0.9<|z|<1.0 and real(z)>0

The source code for hyp2f1 can definitely handle the case of integer differences between the a,b,c parameters, but in this case the code doesn't correctly calculate the integer corresponding to c-a-b.
Specifically, this bug is caused by a couple of lines in specfun.f in which the integer is determined by the expression
```
M=INT(C-A-B)
```
For some values of a,b,c this might be 3.9999 which gets cast to the integer *3* instead of *4*.  Using a conversion of the form 
```
M=INT(C-A-B+EPS*DSIGN(1.0D0,C-A-B))
```
where EPS is a small value like 1e-8 or 1e-15 should fix this issue (this is at least what specfun.f does elsewhere in HYGFZ when determining an integer from real values). 

### Reproducing code example:
```
>>> import numpy as np
>>> from scipy.special import hyp2f1 
>>> import mpmath
>>> a=1.45
>>> b=0.6
>>> c=6.05
>>> c-a-b
3.9999999999999996
>>> z=0.9*np.exp(1.j*(-0.2*np.pi))
>>> hyp2f1(a,b,c,z)
(5.670408102465732-0.76807186486958579j)
>>> mpmath.hyp2f1(a,b,c,z)
mpc(real='1.1053555735636691', imag='-0.11840327506397474')
```
In the above test case, HYGFZ is using *3* instead of *4* for c-a-b which is why it gets the wrong answer as compared with mpmath.

### Scipy/Numpy/Python version information:
```
>>> print scipy.__version__,np.__version__,sys.version_info
1.0.0.dev0+b579459 1.13.1 sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
```

**Comment by FormerPhysicist** [comment]
Since this only requires a few lines of changes, I will fix this issue in my PR fixing issue #8054

**Comment by ilayn** [comment]
@steppi did you already solve this with #14706 ?

**Comment by steppi** [comment]
> @steppi did you already solve this with #14706 ?

Not yet. I didn't get to the 0.9 < |z| < 1.0 case yet. I'll fix it when I translate _hyp2f1.pxd to C++ next week..
