### ISSUE TITLE
Row of a subclass of scipy.sparse.csr_matrix returns a scipy.sparse.csr_matrix

### ISSUE THREAD

**Issue by nvauquie** [scipy/scipy#8084]
When subclassing `scipy.sparse.csr_matrix`, getting a row of the subclass matrix doesn't work in v1.0.0 like it used to in v0.19.1. 

v0.19.1 : getting a row or a column of the matrix returns an object of the **same type as the matrix**
v1.0.0 : getting a row of the matrix returns a **scipy.sparse.csr.csr_matrix** (but getting a column still returns an object of the same type as the matrix)

### Reproducing code example:
```python
import scipy.sparse

class MyCsr(scipy.sparse.csr_matrix):
    pass

csr_matrix = scipy.sparse.random(10, 10, density=0.25, format='csr')
my_csr_matrix = MyCsr(csr_matrix)

print(type(my_csr_matrix), type(my_csr_matrix[2,:]), type(my_csr_matrix[:,2]))
```

#### with scipy 0.19.1
```
<class '__main__.MyCsr'> <class '__main__.MyCsr'> <class '__main__.MyCsr'>
```

#### with scipy 1.0.0
```
<class '__main__.MyCsr'> <class 'scipy.sparse.csr.csr_matrix'> <class '__main__.MyCsr'>
```

### Numpy/Python version information:
```
numpy = 1.13.3
python = sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
Hmm, subclassing a sparse matrix class isn't really tested AFAIK, nor am I sure that we designed for that.

Would still be good to not change such behavior of course.

**Comment by perimosocordiae** [comment]
Looks like this changed in gh-7070, when I did some optimization of _get_row_slice: https://github.com/scipy/scipy/pull/7070/files#diff-e014e9d401e10c269b6fbbf4201a40dfR390

I'll second the comment that subclassing sparse matrix classes isn't tested or recommended. This case should be simple to fix by using `self.__class__()` as the constructor, though.

**Comment by sethtroisi** [comment]
Per numerous comments in #9977 subclassing is discouraged and anything might happen; hence this is not surprising.
