### ISSUE TITLE
Small typo in docs

### ISSUE THREAD

**Issue by pietromarchesi** [scipy/scipy#8087]
There's a typo I believe in the docstring for [Spearman r](https://github.com/scipy/scipy/blob/v0.14.0/scipy/stats/stats.py#L2637). It should be change to 'if axis=1, the relationship is transposed...'.

**Comment by JoshKarpel** [comment]
The typo existed back in 0.14.0, but has since been fixed ([1.0.0 docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.spearmanr.html#scipy.stats.spearmanr)).

**Comment by person142** [comment]
Thanks for checking @JoshKarpel.
