### ISSUE TITLE
optimize.minimize's _minimize_newtoncg's internal terminate function references unbound variable gfk

### ISSUE THREAD

**Issue by dakoner** [scipy/scipy#8100]
Some of our code calls optimize.minimize like this:

```
res = optimize.minimize(
        _log_like(df),
        start,
        method='Newton-CG',
        jac=_log_like_der(df),
        hess=_log_like_hess(df),
        options={'disp': True,
                 'maxiter': 30})
```

and fails.

Code here:
https://github.com/scipy/scipy/blob/master/scipy/optimize/optimize.py#L1538

references an unbound local variable, 'gfk'.  When the terminate method is called, it dies with an exception:
```
File "scipy/optimize/optimize.py", line 1519, in terminate
    result = OptimizeResult(fun=fval, jac=gfk, nfev=fcalls[0],
NameError: free variable 'gfk' referenced before assignment in enclosing scope
```

### Reproducing code example:

Any simple example that calls minimize_cg and terminates at the max iterations will cause the problem.

### Scipy/Numpy/Python version information:

The problem is at scipy HEAD and also in scipy version 1.0.0.

**Comment by pv** [comment]
The failure occurs if the inner loop hits in `cg_maxiter`; gfk is set at https://github.com/scipy/scipy/blob/master/scipy/optimize/optimize.py#L1621

**Comment by dakoner** [comment]
It wasn't clear to me: does that still mean there's a bug in scipy (that's how I read it)?

**Comment by pv** [comment]
It should terminate with error status, not raise NameError.

Also after fixing this, the solver will not give you successful 
convergence. Instead it will say "CG iteration did not converge --- 
hessian not pos. def". I don't know if your problem is such that 
convergence is expected.

**Comment by dakoner** [comment]
Agreed- I do think the underlying code that calls this has a bug that was exposed when we updated to scipy 1.0.0, but I wanted to make sure there was a scipy bug as well.

**Comment by andyfaff** [comment]
I think this is fixed now. In be7496a2b32ec7bfa5c8924df98fa0313fb51c16 `gfk` is created before this, meaning that the minimize should terminate with the correct error status. If this isn't the case then please reopen.
