### ISSUE TITLE
import issue with scipy v1.0

### ISSUE THREAD

**Issue by apiszcz** [scipy/scipy#8102]
Traceback (most recent call last):
  File "lib\_test\test.py", line 99, in <module>
    import seaborn as sns; sns.set()
  File "C:\g\app\lib\seaborn\__init__.py", line 6, in <module>
    from .rcmod import *
  File "C:\g\app\lib\seaborn\rcmod.py", line 8, in <module>
    from . import palettes, _orig_rc_params
  File "C:\g\app\lib\seaborn\palettes.py", line 12, in <module>
    from .utils import desaturate, set_hls_values, get_color_cycle
  File "C:\g\app\lib\seaborn\utils.py", line 7, in <module>
    from scipy import stats
  File "C:\g\app\lib\scipy\__init__.py", line 118, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "C:\g\app\lib\scipy\_lib\_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: cannot import name '_ccallback_c'
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```

**Comment by rgommers** [comment]
> File "C:\g\app\lib\scipy_init.py"

I don't know what that file is. How did you install scipy? And can you reproduce the issue with only ``from scipy import stats``?

**Comment by apiszcz** [comment]
1. Using .whl unzip'd in a folder. Did not have any issues for years, until
1.0.
2. _ccallback appears to be scipy/lib

**Comment by rgommers** [comment]
> 1. Using .whl unzip'd in a folder. Did not have any issues for years, until 1.0.

That is technically possible for most packages, but not a good idea. E.g. for packages that install command line utilities, they won't go into the right place. Better to use pip.

This also doesn't explain where ``scipy_init.py`` came from. Did you add that yourself?

**Comment by apiszcz** [comment]
1. Install from https://www.lfd.uci.edu/~gohlke/pythonlibs/#scipy fails
2. Install from https://pypi.python.org/pypi/scipy works.

**Comment by apiszcz** [comment]
I did not add scipy_init.py ... I'll let the provider of #1 know.

**Comment by cgohlke** [comment]
Can't reproduce this issue with the 3rd party binaries. Probably a manual installation gone wrong.

**Comment by apiszcz** [comment]
cgohlke must be right, retested with his release and all is happy. blame it on me :)
