### ISSUE TITLE
Need to clean up 'generate_ufuncs.py' code comments in scipy.special module

### ISSUE THREAD

**Issue by FormerPhysicist** [scipy/scipy#8106]
Within scipy's 'special' module, there are several code comments that refer to the obsolete python script 'generate_ufuncs.py'.  Since this file no longer exists (it's been replaced with _generate_pyx.py), these code comments should be changed.

### Reproducing code example:
When I grep 'generate_ufuncs.py' in scipy/scipy/special, I get:
```
(scipy-dev) adam@adam-P7xxDM-G:~/scipy-dev/scipy/scipy/special$ grep -r -i 'generate_ufuncs.py'
add_newdocs.py:# generate_ufuncs.py to generate the docstrings for the ufuncs in
add_newdocs.py:# such as : GEN: special: run generate_ufuncs.py
_generate_pyx.py:# This file is automatically generated by generate_ufuncs.py.
_generate_pyx.py:# This file is automatically generated by generate_ufuncs.py.
_generate_pyx.py:# This file is automatically generated by generate_ufuncs.py.
```

### Scipy/Numpy/Python version information:
```
>>> print scipy.__version__,np.__version__,sys.version_info
1.1.0.dev0+05452d0 1.13.1 sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
```

**Comment by FormerPhysicist** [comment]
I'm going to do a quick PR later today that changes 'generate_ufuncs.py' -> '_generate_pyx.py'

**Comment by FormerPhysicist** [comment]
The comment header for 'add_newdocs.py' also states:

```
# Note : After editing this file and committing changes, please run
# generate_funcs.py and commit the changes as a separate commit with a comment
# such as : GEN: special: run generate_ufuncs.py
```
Should I delete this part of the code comments entirely?  I've made edits to add_newdocs.py and running '_generate_pyx.py' doesn't add* my new docstring to special.hyp2f1.

(*When I rebuild scipy, my new docstring does appear)

**Comment by pv** [comment]
Yes, all comments telling to run `generate_ufuncs` etc. manually can be removed.

**Comment by FormerPhysicist** [comment]
Okay I'll do that.
