### ISSUE TITLE
DOC: Link CodeofConduct.md 

### ISSUE THREAD

**Issue by ilayn** [scipy/scipy#8115]
Gina Helfrich from NumFocus pointed out that our code of conduct is not linked to the [Community page ](https://github.com/scipy/scipy/community). It's current location is [here](https://github.com/scipy/scipy/tree/master/doc/source/dev/conduct).

Should we relocate the current file to `/docs` and rename [as described here](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/#adding-a-code-of-conduct-manually) or duplicate it in the repo root under `/docs`? Or maybe include a link to the existing location inside generic dummy file redirecting it to the actual CoC?

**Comment by pv** [comment]
We can probably just add a `.github/CODE_OF_CONDUCT.md` file that contains a link to the actual file.
