### ISSUE TITLE
Difference between n_it and actual function execution in optimize

### ISSUE THREAD

**Issue by mcocdawc** [scipy/scipy#8125]
Hello,

I try to use your BFGS algorithm for an optimisation problem, where
each function execution is quite costly.
The problem is that it seems that the first iteration step is performed twice
I assume this is for testing determinedness?
Can I switch it off?

Besides the number of iteration in the optimized result instance differs from the number of actual iterations. Is this due to not counting line searches?

### Reproducing code example:
```python
def f(v):
    x, y = v
    return x ** 2 + y ** 2

def grad_f(v):
    x, y = v
    return np.array([2 * x, 2 * y])

def combined(v, times_executed=[0]):
    times_executed[0] += 1
    print('Function was actually executed {} times'.format(times_executed[0]))
    return f(v), grad_f(v)

result = minimize(combined, x0=np.array([1, 1]), jac=True, method='BFGS')
print('Scipy says {}'.format(result.nit))

STDOUT:
Function was actually executed 1 times
Function was actually executed 2 times
Function was actually executed 3 times
Function was actually executed 4 times
Scipy says 2
```

### Scipy/Numpy/Python version information:
```
0.19.1 1.13.3 sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)
```

**Comment by andyfaff** [comment]
What you need to look at is `result.nfev`.

Consider the following examples:

```
import numpy as np
from scipy.optimize import minimize, rosen, rosen_der
class fun(object):
    def __init__(self):
        self.calls = 0
        self.jcalls = 0
        
    def combined(self, x):
        self.calls += 1
        self.jcalls += 1
        return rosen(x), rosen_der(x)

    def indiv(self, x):
        self.calls += 1
        return rosen(x)

    def jac(self, x):
        self.jcalls += 1
        return rosen_der(x)

f = fun()
res = minimize(f.indiv, x0=np.random.random(10), jac=False, method='BFGS')
print(f.calls, res.nfev)

f = fun()
res = minimize(f.combined, x0=np.random.random(10), jac=True, method='BFGS')
print(f.calls, f.jcalls, res.nfev, res.njev)

f = fun()
res = minimize(f.indiv, x0=np.random.random(10), jac=f.jac, method='BFGS')
print(f.calls, f.jcalls, res.nfev, res.njev)
```

gives:
```
588 588
52 52 51 51
42 42 42 42
```

1. If you don't provide `minimize` with a Jacobian then `res.nfev` is correct.
2. If you provide a combined function returning (fun, jac) then an extra function evaluation is required to make sure the returned value from the function is indeed the fun and jac.
3. If you provide a callable to the `jac` kwd then `res.nfev` and `res.njev` are correct.

**Comment by mcocdawc** [comment]
Thank you very much for your answer. From this logic I would expect the result to be:
(If it is just one additional function evaluation).
```
588 588
43 43 42 42
42 42 42 42
```
But in any way, this should be made more clear in the documentation.
Our minimization problems for example are near the the minimum and require around 20 iteration steps but have very costly single point calculations. So already one additional iteration step is quite bad for performance reasons.

I can make a PR for the documentation.
