### ISSUE TITLE
scipy.special.psi(x) very slow for some values of x

### ISSUE THREAD

**Issue by rmalouf** [scipy/scipy#8127]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

`scipy.special.psi(x)` uses different algorithms for different ranges of x.  The special cases appear to be intended as optimizations (?) but actually can be orders of magnitude slower than the general case:

```
In [58]: x = np.random.rand(100000) + 0.97

In [59]: timeit y = scipy.special.psi(x)
493 ms ± 3.67 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [60]: x = np.random.rand(100000) + 2.0

In [61]: timeit y = scipy.special.psi(x)
2.15 ms ± 2.88 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Is there a good reason that `scipy.special.psi()` doesn't just use the Cephes implementation as is?

### Reproducing code example:
```
N/A
```

### Error message:
```
N/A
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>

In [62]: import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
0.19.1 1.13.3 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

**Comment by person142** [comment]
Yes. Cephes is inaccurate around the positive zero of the digamma function.

**Comment by person142** [comment]
Given the proximity to the pole at 0, a rational approximation around the zero is likely more appropriate than the Taylor expansion currently being used (and might speed up that code path). I believe this is what Boost does.

**Comment by person142** [comment]
For a simpler fix, one should just precompute the coefficients of the Taylor series and use Horner's method to evaluate the Taylor polynomial. (Not sure why I didn't do that originally.)
