### ISSUE TITLE
BUG: geometric_transform wrap mode possible bug

### ISSUE THREAD

**Issue by mmxmb** [scipy/scipy#8131]
Expect output `array([3, 4, 5, 1, 2])` for the example below instead of `array([2, 3, 4, 1, 2])`. 

The mode functionality is not very well documented, so I am not sure whether this is expected behavior or not. To me output `array([3, 4, 5, 1, 2])`  makes more sense intuitively. The [example analogy](https://github.com/scipy/scipy/blob/master/scipy/ndimage/src/ni_support.c#L219) in the source also seem to support me on this one.

I can try fixing this if someone confirms that this is a bug. 

### Reproducing code example:
```
>>> import numpy as np
>>> from scipy.ndimage import geometric_transform
>>> def shift(coords):
...     return (coords[0] - 3,)
...
>>> geometric_transform([1, 2, 3, 4, 5], shift, mode='wrap')
array([2, 3, 4, 1, 2])
```
### Error message:

No error message.

### Scipy/Numpy/Python version information:
```
0.19.1 1.13.3 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
Seems to be a bug. It's sometimes hard to tell with some of these `ndimage` things though, sometimes someone comes back later with an explanation of why it made sense after all. Pinging @stefanv and @jni for a sanity check.

**Comment by jni** [comment]
I agree that it's a bug. I would think the output should match padding the array appropriately and then cropping again:

```python
In [44]: def shift(coord):
    ...:     return (coord[0] - 3,)
    ...:

In [45]: ndi.geometric_transform(list(range(6)), shift, mode='wrap')
Out[45]: array([2, 3, 4, 0, 1, 2])

In [46]: ndi.geometric_transform(np.pad(list(range(6)), 3, mode='wrap'), shift)[3:-3]
Out[46]: array([3, 4, 5, 0, 1, 2])
```

**Comment by jni** [comment]
Having said that I have close to zero knowledge of the ndimage internals...!
