### ISSUE TITLE
Multibuild discussion

### ISSUE THREAD

**Issue by xoviat** [scipy/scipy#8136]
Ref #8134
Ref #8134 

Ref matthew-brett/multibuild#71
Ref matthew-brett/multibuild#70
Ref matthew-brett/multibuild#58

**Comment by xoviat** [comment]
Sorry about this guys.

**Comment by pv** [comment]
We should just pin the multibuild version to a known-good commit hash.

**Comment by andyfaff** [comment]
In my understanding the reasons for using multibuild are:

- it can install different python.org versions
- multibuild is used to build lots of scipy wheels for OSX. 

Just throwing it out here - the first issue could be tackled by using miniconda in the travisCI for OSX.

**Comment by xoviat** [comment]
There's actually no need to use multibuild in this case because brew can install Python. I'll reopen that PR.

**Comment by xoviat** [comment]
That's #8134. Merge if you agree with the concept and it works. Otherwise, just close it.

**Comment by xoviat** [comment]
Well, it did pass the tests: https://travis-ci.org/scipy/scipy/jobs/299298821

**Comment by andyfaff** [comment]
> There's actually no need to use multibuild in this case because brew can install Python. I'll reopen that PR.

I don't think you can specify which version of Python to install with brew, you can with multibuild and conda.

pv's suggestion to use a specific commit seems reasonable.

**Comment by xoviat** [comment]
> I don't think you can specify which version of Python to install with brew, you can with multibuild and conda.

Correct, but we're not testing that.

**Comment by andyfaff** [comment]
> Correct, but we're not testing that.

At the moment.

**Comment by xoviat** [comment]
I don't think we would test that in the future either, esp. considering the Travis CI mac situation.

**Comment by andyfaff** [comment]
This is where the multibuild aspect has it's advantages. We're dogfooding, the CI tests are using the same kinds of processes that we use to build the scipy wheels.

**Comment by xoviat** [comment]
That's actually a valid concern. I'm not sure this would have been caught otherwise.

**Comment by xoviat** [comment]
And on that point, pinning to a specific commit maybe isn't a good idea; numpy causes test failures sometimes.

**Comment by xoviat** [comment]
Possibly setting the branch to master would help though. That's one option.

**Comment by matthew-brett** [comment]
That's certainly the safer option.

**Comment by xoviat** [comment]
@matthew-brett Any idea what caused the failures?
