### ISSUE TITLE
[feature request] For sparse.linalg.eigsh, when I set k=1 but  got 0 vectors converged, am I still able to extract the not so well converged vector ?

### ISSUE THREAD

**Issue by chiwhalee** [scipy/scipy#8139]
Hi everyone, 

Is it possible to extract at least one not converged  eigenvector from the eigsh program,  even if the maxiter has been reached while the tolerence of  error is not satisfied?   I know that  if  only k' of k  (k'<k) eigenvectors are converged,   an ArpackNoConvergence  error will be raised,  still those k' converged ones can be extracted from the error msg . However, in the example below I have already set k=1, and 0 converged, and noting can be done. 

In my situation, I need to have the args like maxiter and tol fixed, but be able to  extract whatever the eigenvector it generates, which maybe still of value.  This is very critical  for the performance of some iterative optimization algorithms. As far as I know, it is not supported yet.  But could you please make it support this feature ?  Or give me some guidance to do a hack on the source code?  

Exactly the same question has been asked on [stackoverflow](https://stackoverflow.com/questions/33452383/python-scipy-eigs-return-eigenvector-after-maximum-number-of-iterations-whatev) by someone else, but not satisfied answered yet. 

### Reproducing code example:

1.  import numpy  as np
2. from scipy.sparse.linalg import eigsh
3. 
4. n = 2000
5. np.random.seed(0)
6. A = np.random.random((n, n))
7. A = A + A.T
8. val, vec=eigsh(A, k=1, maxiter=20, which='SA')
9. print val

### Error message:
```
 Traceback (most recent call last):
  File "aaa.py", line 9, in <module>
    val, vec=eigsh(A, k=1, maxiter=20, which='SA')
  File "C:\Users\zhihua\Anaconda2\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 1605, in eigsh
    params.iterate()
  File "C:\Users\zhihua\Anaconda2\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 569, in iterate
    self._raise_no_convergence()
  File "C:\Users\zhihua\Anaconda2\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 375, in _raise_no_convergence
    raise ArpackNoConvergence(msg % (num_iter, k_ok, self.k), ev, vec)
scipy.sparse.linalg.eigen.arpack.arpack.ArpackNoConvergence: ARPACK error -1: No convergence (21 iterations, 0/1 eigenvectors converged)
```

### Scipy/Numpy/Python version information:
 '0.18.1'

**Comment by ilayn** [comment]
In the regular use case of this algorithm, this will not make too much sense in the case of failure but if you want to use the "expert" version of it, you can use the mechanism inside `eigsh`. The intermediate vectors and other variables are continuously returned at this part of the code you can check the fortran files for their explanations in `dsaupd.f` for double precision: 

https://github.com/scipy/scipy/blob/6273626f06f5a53ef3e0a840a6ba0e8cab3e45c3/scipy/sparse/linalg/_eigen/arpack/arpack.py#L536-L541

So if you want you can basically interject your own code there but for general use cases this would not be useful in general.
