### ISSUE TITLE
BUG: ndimage geometric_transform and zoom using deprecated NumPy calls

### ISSUE THREAD

**Issue by larsoner** [scipy/scipy#8145]
I'm experiencing an unrelated [Travis failure](https://travis-ci.org/scipy/scipy/jobs/300367861#L1076) over on #8144 related to `ndimage` using deprecated NumPy functionality:
```
        _nd_image.geometric_transform(filtered, None, coordinates, None, None,
>                                     output, order, mode, cval, None, None)
E       DeprecationWarning: NPY_ARRAY_UPDATEIFCOPY, NPY_ARRAY_INOUT_ARRAY, and NPY_ARRAY_INOUT_FARRAY are deprecated, use NPY_WRITEBACKIFCOPY, NPY_ARRAY_INOUT_ARRAY2, or NPY_ARRAY_INOUT_FARRAY2 respectively instead, and call PyArray_ResolveWritebackIfCopy before the array is deallocated, i.e. before the last call to Py_DECREF.
```
And then later:
```
            _nd_image.zoom_shift(filtered, matrix, offset/matrix, output, order,
>                                mode, cval)
E           DeprecationWarning: NPY_ARRAY_UPDATEIFCOPY, NPY_ARRAY_INOUT_ARRAY, and NPY_ARRAY_INOUT_FARRAY are deprecated, use NPY_WRITEBACKIFCOPY, NPY_ARRAY_INOUT_ARRAY2, or NPY_ARRAY_INOUT_FARRAY2 respectively instead, and call PyArray_ResolveWritebackIfCopy before the array is deallocated, i.e. before the last call to Py_DECREF.
```
Any `ndimage` folks have time to look?

**Comment by xoviat** [comment]
I reviewed this PR (that's causing the deprecation). I'll see if I can give this a quick fix.

**Comment by xoviat** [comment]
So the plan is to switch to `WRITEBACKIFCOPY` and then add `PyArray_ResolveWritebackIfCopy ` before all of the `Py_XDECREF(output)`. However, I don't know how to proceed because these APIs are unreleased. How is this normally done (SciPy compiles against a numpy that doesn't have these APIs but numpy will issue a deprecation warning if they aren't compiled in)?

**Comment by xoviat** [comment]
Just from a quick look through the C code, the situation appears unprecedented. I do know that it's possible in theory to adjust the runtime code path, but that's not so simple.

**Comment by xoviat** [comment]
Pending a fix for numpy/numpy#10012.

**Comment by xoviat** [comment]
Also, let me jot this down:

```

    #if NPY_API_VERSION >= 0x0000000b
        int flags = NPY_ARRAY_BEHAVED_NS | NPY_ARRAY_UPDATEIFCOPY;
    #else
        int flags = NPY_ARRAY_BEHAVED_NS | NPY_ARRAY_WRITEBACKIFCOPY;
    #endif
```

**Comment by xoviat** [comment]
Also, pending numpy/numpy#10013.
