### ISSUE TITLE
ValueError: cannot reshape array of size 0 into shape ()

### ISSUE THREAD

**Issue by ignatenkobrain** [scipy/scipy#8153]
Originally coming from https://github.com/nipy/nibabel/issues/579, as author of nibabel says it seems some bug in scipy.

### Reproducing code example:
```
curl -L https://github.com/nipy/nibabel/blob/master/nibabel/tests/data/minc1-no-att.mnc?raw=true > minc1-no-att.mnc
python -c 'import scipy.io as sio; sio.netcdf_file("minc1-no-att.mnc")'
```

### Error message:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.6/site-packages/scipy/io/netcdf.py", line 266, in __init__
    self._read()
  File "/usr/lib64/python3.6/site-packages/scipy/io/netcdf.py", line 593, in _read
    self._read_var_array()
  File "/usr/lib64/python3.6/site-packages/scipy/io/netcdf.py", line 677, in _read_var_array
    data.shape = shape
ValueError: cannot reshape array of size 0 into shape ()
```

### Scipy/Numpy/Python version information:
```
1.0.0 1.13.3 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

**Comment by ignatenkobrain** [comment]
Any news here? It's blocking me from updating few libraries in Fedora.

**Comment by WarrenWeckesser** [comment]
For what it's worth...

According to the data in the file, the file offset of the data for the 32 bit integer variable `study` is 6872.  But the length of the file is 6872.  So when the code tries to slice the four bytes that make up the integer value, the slice is empty, resulting in an array with length 0.  The code then tries to set the shape of this array to `()`, and that trigger the error.

I don't know the details of the netcdf4 file specification.  Is there some convention that applies in this case, such that if the offset for the location of the data is at the end of the file, the implied value is 0?

**Comment by sanjayankur31** [comment]
This still persists. Unfortunately my knowledge if the netcdf4 specification is also quite poor. Would someone have any ideas on how this should be debugged? Should another upstream be requested to look into it, for example?

**Comment by sanjayankur31** [comment]
So I did some digging in, and also [reached out to the netcdf folks](https://www.unidata.ucar.edu/mailing_lists/archives/netcdfgroup/2018/msg00050.html). Here's the situation:

- the file is a corrupt netcdf file as far as the official netcdf tools are concerned. As you see from the thread, most tools are unable to read it.
- the file is an [MINC format file](https://en.wikibooks.org/wiki/MINC/SoftwareDevelopment/MINC2.0_File_Format_Reference), and nibabel have [included custom code to handle these](https://github.com/nipy/nibabel/pull/493). The code review even has a [comment](https://github.com/nipy/nibabel/pull/493/commits/8ea59d6f4b46597da0bcfdcb6638dbcfbfd87a3d) that goes, "This is a generic issue with this NetCDF library, in that a NetCDF variable can have a data offset pointing to the end of the file...".

Now, the question is whether these customisations should also be added to the scipy netcdf bit to enable reading the MNIC files? I guess that it's OK to include them as long as they don't change the way standard netcdf files are read? Comments?

**Comment by ignatenkobrain** [comment]
@sanjayankur13, would you mind sending PR to add behavior for reading MINC files? I would like to patch fedora build temporarily because it blocks me from building nibabel.

**Comment by sanjayankur31** [comment]
@ignatenkobrain I'm going to be travelling for work all this month, so  I won't be able to look into this until next month at the earliest I'm afraid. :/

**Comment by Dave-Allured** [comment]
Hello from netcdf-land.  This problem is due to a malformed MINC1 file in the nibabel test suite, and nothing more.  In nipy/nibabel#579 I explain and offer a repaired test file.  This should fix the related build errors.

Note that MINC1 is netcdf-3 internally, and MINC2 is HDF5.  I strongly recommend against patches to force read success from malformed MINC1/MINC2/netcdf-3/netcdf-4/HDF5 files.  Such attempts may be dangerous and result in hidden data corruption.

**Comment by WarrenWeckesser** [comment]
Thanks, @Dave-Allured, that's what I suspected.  I'm closing this issue, as there is nothing for us to do.
