### ISSUE TITLE
signal.fftconvolve 10× slower than custom real convolution

### ISSUE THREAD

**Issue by aurelienpierre** [scipy/scipy#8154]
Hi, 

not really an issue but, playing with convolution and PyFFTW, I came to this test in a Jupyter notebook 

### Reproducing code example:
```
from pyfftw.builders import rfft2, irfft2
size = (6000, 4000)
kern = 25
c = np.ones((kern, kern)).astype(np.float32)
a = np.ascontiguousarray(np.empty(size), dtype=np.float32)
```
```
%%timeit
CPU = 1
b = rfft2(a, s=size, threads=CPU).output_array
d = rfft2(c, s=size, threads=CPU).output_array
e = b * d
f = irfft2(e, s=size, threads=CPU).output_array
```
317 ms ± 4.12 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

```
import scipy.signal
```

```
%%timeit
f_2 = scipy.signal.fftconvolve(a, c)
```
3.61 s ± 82.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

A quick check to validate the outputs :
```
f_2.all() == f.all()
```
True

I know `fftconvolve` does some checking and prepping in the background, but is this expected ?

### Scipy/Numpy/Python version information:
```
<<import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
0.19.0 1.13.3 sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)>>
```

**Comment by pv** [comment]
fftconvolve doesn't use pyfftw but fftpack which is less optimized.

**Comment by pv** [comment]
And the reason why fftconvolve doesn't use fftw, is because fftw is not 
license compatible.

**Comment by ilayn** [comment]
Since there is not much we can do, closing this.
