### ISSUE TITLE
Inplace flag overwrite_a in dsyr not working

### ISSUE THREAD

**Issue by pgmoren** [scipy/scipy#8155]
Setting the flag "overwrite_a=True" in scipy.linalg.blas.dsyr does not  perform the rank-1 update in-place .

### Reproducing code example:
```
import numpy as np
from scipy.linalg import lapack, blas
A = np.arange(9).reshape((3,3))
b = np.ones(3)
A_orig = A
A = blas.dsyr(lower=0, x=b, a=A, alpha=2.0, overwrite_a=True)
assert id(A)==id(A_orig)
```

### Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
```

### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.0.0 1.13.3 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment]
Hi @pgmoren the IDs hardly ever match. There are many sources online that explains this behavior. You have to look at the contents of the A for your test as the final result to see that it actually is modified but not in-place.

```
import numpy as np
from scipy.linalg import lapack, blas
A = np.asfortranarray(np.arange(9).reshape((3,3)))
b = np.ones(3)
A_orig = A.copy()
A = blas.dsyr(lower=0, x=b, a=A, alpha=2.0, overwrite_a=True)
print(A)
print(A_orig)

```

Even then it is not guaranteed that the overwrite will be succesful. The data type and the memory order should also be **exactly** as required by `f2py`

For example
```
import numpy as np
from scipy.linalg import lapack, blas
A = np.asfortranarray(np.arange(9).reshape((3,3)), dtype=float)
b = np.ones(3)
A_orig = A
A = blas.dsyr(lower=0, x=b, a=A, alpha=2.0, overwrite_a=True)
print(id(A)==id(A_orig))
```

**Comment by ilayn** [comment]
Based on the linked discussion closing this but please feel free to reopen if there is still an issue.
