### ISSUE TITLE
BUG: romb print output requires correction

### ISSUE THREAD

**Issue by jankoslavic** [scipy/scipy#8158]
The option `show=True` results into a wrongly formatted output

### Reproducing code example:
```
x9v, h9v = np.linspace(1, 2, 9, retstep=True)  # korak h9v = 0.125 (9 vozlišč)
y9v = x9v * np.sin(x9v)
romb(y9v, dx=h9v, show=True)
```
See figure:
![image](https://user-images.githubusercontent.com/5072664/32768516-66150cbc-c918-11e7-872e-fe282592e94e.png)

### Scipy/Numpy/Python version information:
```
1.0.0 1.13.3 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

**Comment by Tokixix** [comment]
@ilayn I know how to solve it(adding "\n" in one place ;p). Can I PR this?

**Comment by Tokixix** [comment]
@ilayn Will do, thanks!

**Comment by andyfaff** [comment]
I've verified that the correct formatting is produced.
