### ISSUE TITLE
Error "ValueError: The condensed distance matrix must contain only finite values."

### ISSUE THREAD

**Issue by asanchez126** [scipy/scipy#8161]
After loading a big corpus with many words I have this error message: ValueError: The condensed distance matrix must contain only finite values.
I am receiving the below error while I try to process a big corpus with many words, using for this 'cosine' affinity. i want to compare with some other kind of linkages to see which is better:

        for union in ['ward', 'average', 'complete']:
            if union in 'ward':
                affinity = ['euclidean']
            else:
                affinity = ['cosine']
            for index, afinidad in enumerate(affinity):
                clustering = AgglomerativeClustering(n_clusters=numCluster, affinity=afinidad,
                                            linkage=union).fit_predict(matrizDist.toarray())

It gives the error when the affinity is cosine, it is, in the average and complete linkages. I am not sure this could be a bug of sklearn function. Could you give me any idea? 

My steps in the code are:
1. I calculate the TF IDF matrix using this function:
vectorizerTfidf = TfidfVectorizer(tokenizer=self.tokenizaTraduce, max_features=maxFeatures, smooth_idf=True)
matriz = vectorizerTfidf.fit_transform(texto) ---> This is raw text.
2. with this matrix, I calculate the agglomerative clustering. 

Current Output:
After making the processing of the data in the corpus, it gave the error showed before.

Expected Output:
I expect to calculate the Agglomerative Clustering successfully, giving one valid number of cluster. it is making it fine using euclidean linkage.

### Reproducing code example:
This is part of my code, it is not correct, because I have deleted some lines that wasn't useful to detect the problem. The code that is giving the error with high values of words in the corpus is:
`from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import AgglomerativeClustering
class words():    
    def calculaMatrizTfidf(self,texto,numFeatures):
        maxFeatures = 2*numFeatures                              
        vectorizerTfidf = TfidfVectorizer(tokenizer=self.tokenizaTraduce, max_features=maxFeatures, smooth_idf=True)
        return matriz

class hierarchicalCluster():
    def realizaCluster(self, matrizDist, numFicheros):
        numCluster = ceil(log2(numFicheros)) + 1               
        for union in ['ward', 'average', 'complete']:
            if union in 'ward':
                affinity = ['euclidean']
            else:
                affinity = ['cosine']
            for index, afinidad in enumerate(affinity):
                clustering = AgglomerativeClustering(n_clusters=numCluster, affinity=afinidad,
                                            linkage=union).fit_predict(matrizDist.toarray())`

### Error message:
Traceback (most recent call last):
  File "C:/Proyecto/WePNaD/proyecto.py", line 16, in <module>
    main()
  File "C:/Proyecto/WePNaD/proyecto.py", line 12, in main
    hierarchicalClust.realizaCluster(matrizTfidf,datosFichEntrada.contFicheros)
  File "C:\Proyecto\WePNaD\cluster.py", line 78, in realizaCluster
    linkage=union).fit_predict(matrizDist.toarray())
  File "C:...\Anaconda3\lib\site-packages\sklearn\base.py", line 410, in fit_predict
    self.fit(X)
  File "C:....\Anaconda3\lib\site-packages\sklearn\cluster\hierarchical.py", line 734, in fit
    **kwargs)
  File "C:...\Anaconda3\lib\site-packages\sklearn\externals\joblib\memory.py", line 283, in __call__
    return self.func(*args, **kwargs)
  File "C:...\Anaconda3\lib\site-packages\sklearn\cluster\hierarchical.py", line 524, in _average_linkage
    return linkage_tree(*args, **kwargs)
  File "C:...\Anaconda3\lib\site-packages\sklearn\cluster\hierarchical.py", line 410, in linkage_tree
    out = hierarchy.linkage(X, method=linkage, metric=affinity)
  File "C:..\Anaconda3\lib\site-packages\scipy\cluster\hierarchy.py.", line 676, in linkage
    raise ValueError("The condensed distance matrix must contain only finite values.")
ValueError: The condensed distance matrix must contain only finite values.

### Scipy/Numpy/Python version information:
0.19.0 1.12.1 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)

I want to know if there is one bug with it that makes it divide by zero with some values. Thanks.

**Comment by pv** [comment]
I'd suggest filing this to the sklearn issue tracker, not clear if the 
issue is there.

**Comment by asanchez126** [comment]
Thanks, I will close the issue and post it in scikit.
