### ISSUE TITLE
Special functions list in docs fails to flag some non-ufuncs

### ISSUE THREAD

**Issue by kyleaoman** [scipy/scipy#8167]
The page here http://docs.scipy.org/doc/scipy/reference/special.html claims to flag any functions which are not ufuncs, but the flagging is incomplete. So far I have noticed (there may be others):
```python
spherical_jn
spherical_yn
spherical_in
spherical_kn
jvp
yvp
kvp
ivp
h1vp
h2vp
```

**Comment by person142** [comment]
It's true that those functions are not ufuncs, though they do follow broadcasting rules except in the `derivative` (for spherical Bessel) and `n` arguments (for Bessel function derivatives). Do you want to pass arrays for those arguments, or are you doing something like a `reduce`?

(Trying to understand the use-case because the right fix depends on what you want to do.)

**Comment by kyleaoman** [comment]
Neither, I was trying to write some code which adds extra handling specifically for ufuncs. One of my tests automatically compiles a list of all the ufuncs to check that each one has an extra handler. I was surprised to find that I'd written handlers for functions that were not ufuncs, because these are not flagged as non-ufuncs in the docs (http://docs.scipy.org/doc/scipy/reference/special.html), although they promise to do such flagging.

**Comment by person142** [comment]
Hm... I'd say the goal of the documentation is to distinguish behavior like

```
>>> sc.lmbda(1, [1, 2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/scipy/special/basic.py", line 1750, in lmbda
    raise ValueError("arguments must be scalars.")
ValueError: arguments must be scalars.
```

from behavior like

```
>>> sc.jvp(1, [1, 2])
array([ 0.3251471 , -0.06447162])
```

From that perspective `jvp` et al. are "ufunc-like" and telling users that they aren't really ufuncs runs the risk of confusion. But I guess now that caused confusion for your use case.

An aside: what's the reason for not using

```
>>> type(sc.jvp)
<type 'function'>
>>> type(sc.jv)
<type 'numpy.ufunc'>
```

to get your list?

**Comment by kyleaoman** [comment]
That is how I get my list for automated testing. I was just also making use of the docs as a convenient, hyperlinked list for easy access to information (which I think is the intended purpose ;) and was surprised when the automated list didn't match with what I expected from the docs.
