### ISSUE TITLE
`scipy.stats.ortho_group` produces all negative determinants for O(2)

### ISSUE THREAD

**Issue by yingted** [scipy/scipy#8173]
`scipy.stats.ortho_group.rvs(2)` seems to return only matrices with determinant -1.
This doesn't happen with, for example, O(3).

Also, I also noticed that if `size > 1` and `random_seed` is given, all the generated matrices are the same.

### Reproducing code example:
```python
import scipy.stats
import numpy as np
import collections

o2_dets = collections.Counter()
o3_dets = collections.Counter()

for i in xrange(1000):
    q = scipy.stats.ortho_group.rvs(dim=2, random_state=i)
    o2_dets[np.round(np.linalg.det(q), decimals=3)] += 1

    q = scipy.stats.ortho_group.rvs(dim=3, random_state=i)
    o3_dets[np.round(np.linalg.det(q), decimals=3)] += 1

print '1000 determinants from O(2)', o2_dets
print '1000 determinants from O(3)', o3_dets
```

### Output:
```
1000 determinants from O(2) Counter({-1.0: 1000})
1000 determinants from O(3) Counter({-1.0: 506, 1.0: 494})
```

### Scipy/Numpy/Python version information:
```
('0.19.0', '1.13.0', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0))
```

**Comment by pv** [comment]
@philipdeboer: ping

**Comment by pv** [comment]
The solution to the second issue is simple, random_state = self._get_random_state(random_state) should be before the recursive call

**Comment by philipdeboer** [comment]
Thanks for raising this, Ted. It is good to know someone is running the code! I have reproduced the issue and will try to get a patch out soon.

**Comment by philipdeboer** [comment]
I've put a patch in https://github.com/philipdeboer/scipy/tree/bugfix. Ted, do you agree this fixes the issues you raised?

I'll submit a pull request and work it through the process.

**Comment by yingted** [comment]
👍, but I'm not really convinced that the test can detect other issues.

**Comment by philipdeboer** [comment]
Sure, can you suggest better tests?

I will try to update the patch next week.

**Comment by yingted** [comment]
Hmm, I'm not sure if this is a better test, but here's one that doesn't rely on rotation invariance.
Here's a test to check the distribution of pairwise distances between the matrices. For dimensions 2, 3, 4, and 5, the shapes are very different.
See: https://github.com/yingted/scipy/tree/stats-ortho-group-pairwise-distances-test
Take a look at the distribution shape:
![Distribution of squared pairwise distances](https://user-images.githubusercontent.com/3887435/34152150-95e90366-e47b-11e7-86c5-bcd0f34ca52c.png)

**Comment by philipdeboer** [comment]
Thanks, a reference implementation was certainly a good idea!

**Comment by pv** [comment]
Fixed in gh-8187
