### ISSUE TITLE
optimize.minimize should provide a way to return the cost function value on each generation

### ISSUE THREAD

**Issue by brandondube** [scipy/scipy#8176]
Often when using nonlinear optimization as a sub-routine of a larger software stack, you may wish to benchmark the optimizer for a new type of problem.  In these situations it is useful to track the parameter vector, as well as the cost function, as a function of iteration or generation.

Currently, minimize lacks the ability to do this.  options.return_all, available for some methods, gives you the parameter vector vs generation, but not the cost function.

As a user, you can make the callback re-compute the cost function, but this is inefficient.  It would be ideal to have a way to have the optimizer return the cost function vs generation, similar to return_all above.

**Comment by andyfaff** [comment]
minimize does a really good job of wrapping a diverse range of solvers to present a uniform interface to the user.  There was discussion in #4384 about this kind of thing.
I think the approach would be that the callback would be given an intermediate `OptimizeResult`, which would contain the information you require. Raising an Exception within the callback would halt the minimisation, with the Exception being appended into the OptimizeResult.

However, this is a fair amount of work and tricky to get right for all the minimizers. It also requires that all callback functions be modified to accept an OptimizeResult. I'm not sure how that depreciation/adaptation is supposed to be dealt with.

**Comment by brandondube** [comment]
I don't think it's difficult in Python to solve that problem.  The code could be as simple as making the signature as follows:

`scipy.optimize.minimize(fun, x0, method, cost_all, callback)`.

if `cost_all` is True, an intermediate OptimizeResult object is given to the callback in addition or substitution to the parameter vector.  If it's false, then the callback works just as it always has.

**Comment by eric-wieser** [comment]
Is there a reason you can't just push results into a list within the function call? Or would that produce extra elements?

**Comment by jaimefrio** [comment]
Many methods do a line search, where they will evaluate the function a few times before deciding they have found a suitable next iteration point. You typically only want to keep these values, not the intermediate evaluation ones.

**Comment by TizianoGC** [comment]
Is there any progress on this issue? This feature is really helpful to assess the progress of an optimiser (I'm using differential_evolution).
At the moment I'm using this [workaround](https://stackoverflow.com/questions/47381835/scipy-minimize-get-cost-function-vs-iteration)

**Comment by brandondube** [comment]
@TizianoGC I ended up creating my own wrapper around L-BFGS-B that has a different interface to facilitate logging like this.  If you are interested, I could open source it this weekend.  DE would have to be wrapped in the same manner...

FWIW, that workaround is also mine!

**Comment by TizianoGC** [comment]
@brandondube Thanks for your kind offer (and for posting your script on Stackoverflow!), but your workaround is working well for the data I need to save.
