### ISSUE TITLE
special.spherical_jn(1, 0, derivative=True) yields 0 instead of 1/3

### ISSUE THREAD

**Issue by trettberg** [scipy/scipy#8184]
The derivative of the spherical Bessel function of order 1 at zero yields
```Python
In [16]: special.spherical_jn(1, 0, derivative=True)
Out[16]: 0.0
```
To my understanding this is wrong. It should be 1/3 instead. 

Compare e.g. the numerical value for a small argument:
```Python
In [17]: special.spherical_jn(1, 1e-10, derivative=True)
Out[17]: 0.33333333333333537
```
or the graph of j1 in Fig.1 at http://dlmf.nist.gov/10.48

### Scipy/Numpy/Python version information:
```
In [18]:  print(scipy.__version__, numpy.__version__, sys.version_info)
0.19.1 1.13.1 sys.version_info(major=3, minor=6, micro=0, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
Indeed,
```
 >>> special.spherical_jn(1, 1e-200, derivative=True)
0.33333333333333925
```
seems to be limited to the exact z=0 value.

**Comment by person142** [comment]
From http://dlmf.nist.gov/10.51#E1 the correct value should be `0` for every `n != 0, 1`. The `n = 0` case is already handled correctly in the code, so returning `1/3` when `n = 1` and `x = 0` should fix the problem.

**Comment by person142** [comment]
Hah, there's even an existing test for this case but the exact value it provides is wrong...
