### ISSUE TITLE
ValueError: negative row index found

### ISSUE THREAD

**Issue by superrui0810** [scipy/scipy#8189]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
ValueError: negative row index found
 File "D:\Anaconda3-5\lib\site-packages\scipy\sparse\coo.py", line 234, in _check
    raise ValueError('negative row index found')

### Reproducing code example:
```
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```

### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```

**Comment by ilayn** [comment]
@superrui0810 without further details, there is not much we can do about this.

**Comment by superrui0810** [comment]
Here is the code：
 data['user'] = data['user'].astype("category")
    data['artist'] = data['artist'].astype("category")

    # create a sparse matrix of all the users/plays
    plays = coo_matrix((data['plays'].astype(numpy.float32),
                       (data['artist'].cat.codes.copy(),
                        data['user'].cat.codes.copy())))
the len（data['artist']）=17,559,530  the len（data['user']）=17,559,530
Is the data too large？？？？

**Comment by superrui0810** [comment]
my scipy version is 0.19.1

**Comment by superrui0810** [comment]
@ilayn  
Here is the code：
data['user'] = data['user'].astype("category")
data['artist'] = data['artist'].astype("category")

# create a sparse matrix of all the users/plays
plays = coo_matrix((data['plays'].astype(numpy.float32),
                   (data['artist'].cat.codes.copy(),
                    data['user'].cat.codes.copy())))
the len（data['artist']）=17,559,530 the len（data['user']）=17,559,530
Is the data too large？？？？
my scipy version is 0.19.1

**Comment by ilayn** [comment]
The error tells you that you have negative numbers in your row indices which in your case the array `data['artist'].cat.codes`.

**Comment by superrui0810** [comment]
but   array  data['artist'].cat.codes have no negative numbers ，how to deal with it

**Comment by ilayn** [comment]
Without any data, I can't see what the problem is but if you are also downcasting the artist cat code, there might be an integer overflow problem. Please try to narrow your problem to a manageable size provide a reproducible standalone example. Otherwise we will just keep on guessing which is not efficient.

**Comment by superrui0810** [comment]
I wil try ，Thanks

**Comment by perimosocordiae** [comment]
It's unlikely that the data size is too large, unless you're using a very memory-constrained computer.

As a quick test, try:
```python
assert np.all(data['artist'].cat.codes >= 0)
```

It might also be useful to check the dtype of each array. Make sure the rows and columns are either `np.int32` or `np.int64` to avoid surprises.

**Comment by pangeran-bottor** [comment]
Just want to share for people with this same problem (on the same data/tutorial) in the future. The user most likely read the same code as what I came across https://github.com/ihongChen/PlayRecommendSystem/blob/master/lastfm_calculate_similar.py

It's nothing to do with too large data. The `artist` categorical codes has negative value since some rows on `data` contains `Null` value. To fix this:

    # create a sparse matrix of all the users/plays
    data.dropna(inplace=True)
    plays = coo_matrix((data['plays'].astype(numpy.float32),
                   (data['artist'].cat.codes.copy(),
                    data['user'].cat.codes.copy())))

**Comment by sethtroisi** [comment]
Closing old issue without followup and plausible explanation as a user problem
