### ISSUE TITLE
OSX builds failing

### ISSUE THREAD

**Issue by xoviat** [scipy/scipy#8192]
xref travis-ci/travis-ci#8826

**Comment by andyfaff** [comment]
As far as I remember we need to use brew to get gfortran. (Not sure about
other things it gives us - ccache?).
Is there another way of obtaining gfortran on Travis?

**Comment by xoviat** [comment]
There is. However, homebrew should be the most widely tested option. Let's wait and see what the homebrew maintainers have to say.

**Comment by andyfaff** [comment]
Arbitrary precision math?

**Comment by xoviat** [comment]
What?

**Comment by andyfaff** [comment]
Possibility for using conda gfortran.

**Comment by andyfaff** [comment]
Libmpc is a library for arbitrary precision maths which is also installed
by brew.

On 30 Nov 2017 3:28 pm, "Andrew Nelson" <andyfaff@gmail.com> wrote:

Possibility for using conda gfortran.

**Comment by xoviat** [comment]
Yes, that was introduced in #3681.

**Comment by andyfaff** [comment]
So removing oclint seems to get a bit further down the line. It also seems that `pushd` and `popd` aren't working for some reason on OSX.
xref https://github.com/travis-ci/travis-ci/issues/8854

**Comment by matthew-brett** [comment]
Could this be the problem that I hit before with `cd` on xcode 8.3 on travis?

https://github.com/travis-ci/travis-ci/issues/8703#issuecomment-347881274

**Comment by andyfaff** [comment]
`cd` works. Pushd and popd don't. From looking at your link it's likely that it's the same issue. @xoviat I'll make another fix

**Comment by andyfaff** [comment]
Fix made, `unset -f pushd`+`unset -f popd`.

@xoviat I replaced the cd by `pushd` and `popd` in xoviat/scipy#6
