### ISSUE TITLE
DEP: Add sparray / remove spmatrix

### ISSUE THREAD

**Issue by xoviat** [scipy/scipy#8195]
As `numpy.matrix` [will be removed](https://github.com/numpy/numpy/pull/10142), we should remove SciPy's dependency in 1.1.0:

- [ ] Add `sparray`:
  - [ ] bsr_array
  - [ ] coo_array
  - [ ] csc_array
  - [ ] csr_array
  - [ ] dia_array
  - [ ] dok_array
  - [ ] lil_array
  - [ ] sparray
- [ ] Deprecate `spmatrix`.

**Comment by perimosocordiae** [comment]
We can't stop using `np.matrix` until we deprecate `scipy.sparse.spmatrix`, at the very least.

**Comment by xoviat** [comment]
How about going ahead and emitting a PendingDeprecationWarning in the
spmatrix constructor? That way, we can start letting people know about this
ASAP.

**Comment by josef-pkt** [comment]
Is there a summary somewhere about where np.matrix is used in the API, i.e. user facing?
and which would affect users in a backwards incompatible way when switching.

I never worked much with sparse, but in those cases I did, I only used arrays on the numpy/dense side.

**Comment by ilayn** [comment]
In the NumPy issue initialization of a `np.matrix` will already emit a warning so before anything it has to be silenced wherever it is used otherwise every invocation of a matrix would repeat the warning. Then `spmatrix` can emit its own warning if needed. 

I have the feeling that we won't be able to make it to NumPy schedule for the deprecation so SciPy 1.1 might be too early for that. We can start deprecating `spmatrix` though.

**Comment by ilayn** [comment]
By the way `PendingDeprecationWarning` will be added to NumPy v1.15 so there is quite some time ahead.

**Comment by xoviat** [comment]
Yes it is some time ahead, but it's better to give people as much notice as
possible. I tried emitting a pendingdeprecationwarning on spmatrix, but it
looks like that would kill the whole of scipy.sparse. Is that what we want?
Shouldn't we just subclass from ndarray instead?

**Comment by perimosocordiae** [comment]
We should probably have at least provisional support for sparray (or whatever the ndarray-like spmatrix code will be called) in place before throwing deprecation warnings for spmatrix.

**Comment by xoviat** [comment]
Revised the original post indicate the actionable items. Does someone want to label the issue?

**Comment by xoviat** [comment]
Sorry, duplicate of #8162.
