### ISSUE TITLE
gaussian_filter seg faults on float16 numpy arrays

### ISSUE THREAD

**Issue by arngorf** [scipy/scipy#8207]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

Using gaussian_filter from scipy.ndimage.filters on numpy arrays with dtype=np.float16 causes a segmentation fault.

### Reproducing code example:
>> from scipy.ndimage.filters import gaussian_filter
>> import numpy as np
>> gaussian_filter(np.array([1],dtype=np.float16), 1)

### Error message:
Segmentation fault (core dumped)

### Scipy/Numpy/Python version information:
('1.0.0', '1.13.3', sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0))
1.0.0 1.13.3 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)

**Comment by WarrenWeckesser** [comment]
Confirmed with master (version `'1.1.0.dev0+4019b40'`).

I have optimistically added this issue to the 1.0.1 milestone.  Seg. faults are nasty, so I hope someone can work on this for the next point release.

**Comment by oleksandr-pavlyk** [comment]
@WarrenWeckesser Who is an appropriate person to ping for a review please? Thanks.

**Comment by WarrenWeckesser** [comment]
It looks like @jaimefrio was the last person to do significant work in `ndimage`, so he might be able to comment; Jaime, consider yourself pinged. :)  Got a few spare cycles for a review?
