### ISSUE TITLE
Why should I choose order > 1 for scipy.ndimage.zoom?

### ISSUE THREAD

**Issue by MartinThoma** [scipy/scipy#8210]
Why should one choose different orders? Higher orders seem to be more gray-ish.

**Comment by jaimefrio** [comment]
I think the gray-ishness [here](https://4957-1460385-gh.circle-artifacts.com/0/home/ubuntu/scipy/doc/build/html-scipyorg/generated/scipy.ndimage.zoom.html#scipy.ndimage.zoom) is a matplotlib artifact. Zooming into an image and then displaying it the same size as the original is not a very helpful example.

That said, when zooming into an image some artifacts are to be expected. Say you have a hard transition from a large red  patch to a large green one. After you zoom-in 3x these same transition is going to be spread over three pixels:
 * if you use an order 0 spline, the transition is going to be nearest neighbor like, so you will keep a hard transition,
 * if you use an order 1 spline, the transition will be linear, so the red will transition to yellow then to green.
 * if you use higher order splines, the transition will be continuous both in values and in higher order derivatives, which will probably mean that the higher the order, the steeper the transition from one patch to another, although the interpolant is still going to want to put some yellow halfway through the transition.

**Comment by pv** [comment]
It's grayish because
```
 >>> result.min(), result.max()
(-40, 302)
```
The example should probably be adjusted to point out that spline 
interpolation can have overshooting/ringing.
