### ISSUE TITLE
Why is rv.continuous generating a pdf that is peaked at the edge of the given interval? 

### ISSUE THREAD

**Issue by fspano** [scipy/scipy#8221]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

=== The basis===
I am trying to define a continuous distribution from which to draw variates and fil a histogram that reproduces that distribution. I want to sum a Landau to a Gaussian and I want the histogram to exist on a given interval.
I started with generating the Gaussian.Given that I am going to give it a small weight in tHe sum  I define the distribution in this way
0.0001*(1./(np.power(2.*math.pi,0.5)*sig))*np.exp(-np.power((x - mu)/sig, 2.)/2)
  
You notice that if one takes away the 0.0001 value the distribution is normalised  to 1over the (-inf, inf) interval.

== The problem==
Now I use  cvs to generate 1000 variates with a  Gaussian  distributionwhose mean is 936. and with a standard deviation of 622 in  the interval (-2100., b=3900.)

I see that all the events peak to the upper edge of the interval .
Notice that if I take 0.0001 away form the definition , I see a nicely peaked distribution at 936 with the standard deviation I want.

I want to ask:
1) if this problem is understood 
2) what I need to change to have Gaussian distribution (if possible) with an arbitrary normalisation
3) I am also planning to us https://github.com/ndawe/landau to have the following function
     0.113*pylandau.get_landau_pdf(x, 500, 131)+0.0317*gaussian(x,936,622)
   (with the Gaussian being defined without the 0.0001 factor)
    if I get help on 2 it will allow me to be confident that it is working on the rest

### Reproducing code example:

--The code the I run is the following--

== Start of code ====
import numpy as np
import scipy.stats as st
import math

def gaussian(x, mu, sig):
    return  0.0001*(1./(np.power(2.*math.pi,0.5)*sig))*np.exp(-np.power((x - mu)/sig, 2.)/2)
class fallingSpectrum(st.rv_continuous):
    def _pdf(self,x):
        return gaussian(x,936.,622.)

my_fallingspectrum=fallingSpectrum(a=-2100., b=3900., name='fallingSpectrum')
theSpectrum=my_fallingspectrum.rvs(size=1000)
theMean=my_fallingspectrum.mean()
theMedian=my_fallingspectrum.median()
theStandardDev=my_fallingspectrum.std()
print 'theMean is', theMean,'the standard deviation is ',theStandardDev,' and the median is',theMedian
print theSpectrum

=== end of Code===

### Scipy/Numpy/Python version information:
I am running
Python 2.7.13 |Anaconda custom (x86_64)| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
and  If I run 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'

I get:

>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
('1.0.0', '1.13.3', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0))

**Comment by fspano** [comment]
Hello, does anyone have an answer to my question above?

**Comment by josef-pkt** [comment]
That's a usage question that would fit better on stackoverflow.

AFAICS, your pdf does not integrate to one, i.e. the coefficient to multiply the pdf is NOT arbitrary

you can also check the cdf and ppf that is generated and they should be far from (cumulative) probability 1 for any finite large values.

**Comment by ev-br** [comment]
No follow-up, closing.
