### ISSUE TITLE
simps integrater does allos unordered x without warning

### ISSUE THREAD

**Issue by juergspaak** [scipy/scipy#8230]
The simpson integrater does allow unorderd x, however there's no warning that these are not handled correctly.

`from scipy.integrate import simps

print(simps([1,3,2], [1,3,2]))
print(simps([1,2,3], [1,2,3]))`

These give two different results, while according to (my interpretation of the) description they should agrre. So please either change the description and/or throw an error/warning or handle this appropriately (with probably throwing an additional warning).

**Comment by andyfaff** [comment]
This is another situation where it's worth having a small util function somewhere to see if an array is (strictly) monotonic

**Comment by APwhitehat** [comment]
Where should the util function be placed ?

**Comment by andyfaff** [comment]
The fix for this should be an addition to the doc string that one should consider the order of data points. I asked a question over on the numpy repo about numpy.trapz and it was pointed out that one might want to use unordered points to do parametric integration.

**Comment by andyfaff** [comment]
Closing, see numpy/numpy#10428 for a rationale in keeping current behaviour.
