### ISSUE TITLE
Scipy 018 - linalg.cholesky wrong computation

### ISSUE THREAD

**Issue by japanstar** [scipy/scipy#8233]
Scipy linalg.cholesky is giving wrong results. This can be checked in two ways:
1- if I multipy the correlation matrix resulting from linalg.cholesky, for itself transposed, I should expect to obtain the input correlation matrix. This is not the case.
2- I also double checked the result with what numpy.linalg.cholesky returns. The Numpy result is correct and matches what reported in point 1 above.

### Reproducing code example:
```
import numpy
from scipy import linalg

corr_matrix = numpy.array([
                            [1.0,0.60,0.54],
                            [0.60,1.0,0.75],
                            [0.54,0.75,1.0]
                            ])

L = linalg.cholesky(corr_matrix)
print numpy.dot(L,L.T.conj())

L = numpy.linalg.cholesky(corr_matrix)
print numpy.dot(L,L.T.conj()) 
```

### Error message:
```
No error message as such. However the above code gives as a result:
[[ 1.6516      0.76755     0.35197221]
 [ 0.76755     0.92355625  0.34708371]
 [ 0.35197221  0.34708371  0.42484375]]
[[ 1.    0.6   0.54]
 [ 0.6   1.    0.75]
 [ 0.54  0.75  1.  ]]

while the two resulting matrix (from scipy and numpy) should be the same. As it can be seen the second matrix (returned from numpy.linalg.cholesky) is correct and matches corr_matrix provided in input.
```

### Scipy/Numpy/Python version information:
```
('0.18.0', '1.11.1', sys.version_info(major=2, minor=7, micro=10, releaselevel='final', serial=0))
```

**Comment by pv** [comment]
The result is correct. The default value for the `lower=False/True` flag 
is different in numpy vs scipy.

**Comment by ilayn** [comment]
There seems to be no issue hence closing.
