### ISSUE TITLE
`scipy.optimize.linprog` `interior-point` presolve bug with trivial bounds

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#8234]
`linprog` with option `interior-point` can report incorrect solution when bounds trivially constrain problem to be infeasible. When solution is finished in presolve, it should be checking for infeasibility/unboundedness but I guess this one slipped through the cracks.

### Reproducing code example:
```
from scipy.optimize import linprog
c = [-4, 1];
A_ub = [[7, -2], [0, 1], [2, -2]]
b_ub = [14, 3, 3]
bounds= [(2, 2), (0,0)]
sol = linprog(c, A_ub = A_ub, b_ub = b_ub, bounds = bounds, method = "interior-point")
print sol
```

### Output:
```
     con: array([], dtype=float64)
     fun: -8.0
 message: 'The solution was determined in presolve as there areno non-trivial constraints.'
     nit: 0
   slack: array([ 0.,  3., -1.])
  status: 0
 success: True
       x: array([ 2.,  0.])
```
But this is incorrect; it violates the third constraint.

### Scipy/Numpy/Python version information:
```
('1.0.0', '1.13.1', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0))
```

**Comment by Tokixix** [comment]
@mdhaber Hi! As I see this issue is still open, wasn't the bug fixed? If not, can I try to work on it?

**Comment by ilayn** [comment]
Hi @Tokixix if you follow the link above to the Pull Request you can see how it is fixed. Once that is merged this issue will be closed.
