### ISSUE TITLE
scipy.stats multinomial pmf return nan

### ISSUE THREAD

**Issue by rfire01** [scipy/scipy#8235]
I'm trying to use the multinominal.pmf function from scipy.stats.

When I use this function where all probabilities in the input bigger than zero, it work fine. The problem is when I want to use the function when one of the probabilities is zero.

### Reproducing code example:

In [18]: multinomial.pmf([3, 3, 0], 6, [1/3.0, 1/3.0, 1/3.0])
Out[18]: 0.027434842249657095

In [19]: multinomial.pmf([3, 3, 0], 6, [2/3.0, 1/3.0, 0])
Out[19]: nan

As can be seen, in the first time where all probabilities > 0 there is no problem to use the function. However when I change one of the probabilities to zero, the function return nan, even through the function should return 0.21948.

### Scipy/Numpy/Python version information:
('1.0.0', '1.13.1', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0))

**Comment by jagaudin** [comment]
In scipy/_multivariate.py, line 2950:

    `pcond = np.any(p <= 0, axis=-1)`

should be:

   `pcond = np.any(p < 0, axis=-1)`

**Comment by WarrenWeckesser** [comment]
@rfire01, thanks for reporting the issue, and @jagaudin thanks for tracking down the culprit.

**Comment by WarrenWeckesser** [comment]
The issue was first [reported on stackoverflow](https://stackoverflow.com/questions/47894446/scipy-multinomial-pmf-return-nan) where @jagaudin gave an answer with more details about the bug.

**Comment by ilayn** [comment]
@jagaudin do you mind submitting a fix PR for this too?

**Comment by jagaudin** [comment]
Not at all. I need some dinner now, but will do ASAP.

**Comment by jagaudin** [comment]
All done, the PR is [here](https://github.com/scipy/scipy/pull/8236). I have added a test in `stats/tests/test_multivariate` to cover this issue. Let me know if anything else is required.

**Comment by jagaudin** [comment]
Oops, I put the test in the wrong method!

**Comment by jagaudin** [comment]
The test should be in the right location now.

**Comment by guomingjin** [comment]
This bug happened again, which version can i use?

**Comment by mdhaber** [comment]
Any modern version of SciPy after 1.0 would include this fix. Can you post your example of the bug?

**Comment by guomingjin** [comment]
When I test it with a small dataset, it works fine. but with a large dataset that has mostly zeroes, it gives NAN. I am not sure how to share the code and dataset.

**Comment by guomingjin** [comment]
> pX_z = multinomial.pmf(x=X, n=L, p=F[z])
        print('=========== X ============')
        print(X.shape)
        print(X)
        print('=========== L ============')
        print(L.shape)
        print(L)
        print('=========== F[z] ============')
        print(F[z].shape)
        print(F[z])
        print('=========== pX_z ============')
        print(pX_z)

result:

> =========== X ============
(1849, 2760)
[[1. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 2. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 1.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 1.]]
=========== L ============
(1849,)
[22. 37. 33. ... 21.  7. 17.]
=========== F[z] ============
(2760,)
[0.         0.         0.05555556 ... 0.         0.         0.        ]
=========== pX_z ============
[nan nan nan ... nan nan nan]
=========== X ============
(1849, 2760)
[[1. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 2. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 1.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 1.]]
=========== L ============
(1849,)
[22. 37. 33. ... 21.  7. 17.]
=========== F[z] ============
(2760,)
[0.         0.07692308 0.         ... 0.         0.         0.        ]
=========== pX_z ============
[nan nan nan ... nan nan nan]

**Comment by mdhaber** [comment]
Unfortunately, I can't really help unless you can provide code that I can execute to reproduce the error.

**Comment by WarrenWeckesser** [comment]
> This bug happened again, which version can i use?

Which version are you using now?  If you don't know, you can check with

    import scipy
    print(scipy.__version__)

**Comment by guomingjin** [comment]
> 

1.7.3
