### ISSUE TITLE
Make csgraph importable again via `from scipy.sparse import*`

### ISSUE THREAD

**Issue by cielavenir** [scipy/scipy#8243]
In https://github.com/scipy/scipy/commit/0d173ca0ec85ae5366351382a8afc56b30ae0889#diff-8d4b6341c98c33c3eaf1d8c7e769cf5d, csgraph releated import was removed. This removed csgraph from `dir()` and broke codes such as `from scipy.sparse import*;csgraph.dijkstra(...)`. This affects few people, but this is still a breaking change.
(Otherwise, this should be written in release notes.)

### Reproducing code example:
```
from scipy.sparse import*;print(csgraph)
```

This code does work on SciPy 0.19.1.

### Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'csgraph' is not defined
```

### Scipy/Numpy/Python version information:
```
1.0.0 1.11.2 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by xoviat** [comment]
This function has been deprecated for five years (since #119). Do you think the deprecation period should be longer?

**Comment by xoviat** [comment]
Note: I am certainly sympathetic if code was written six years ago that used this functionality and then broke. But if code was written after this function was deprecated, then it's simply a lesson not to write new code that uses deprecated functions.

**Comment by ilayn** [comment]
@xoviat It's actually a bit more strange. Because of the relative import the namespace of csgraph was elevated to `scipy.sparse` which in my opinion should have never happened. But because the import is gone together with the deprecated func. Now star import doesn't do this. I would say this is a bug fix but I guess this is another example of xkcd's ctrl+spacebar episode.

**Comment by rkern** [comment]
> Because of the relative import the namespace of csgraph was elevated to `scipy.sparse` which in my opinion should have never happened.

There isn't much we can do about it. It's just the way Python packages work. Unless if you meant that Python should never have implemented packages that way…

But in any case, yes, the automatic presence of `csgraph` in the `scipy.sparse` namespace was an unintentional side effect, not a public API. Users should not have relied upon the happenstance even when the `cs_graph_components` function was not deprecated. If you want `csgraph`, you should import it explicitly.

**Comment by pv** [comment]
On the other hand, this is a relatively harmless quirk that is probably 
not necessary to clean up, and we can just reintroduce the import in 
`__init__.py` (with a code comment stating it's for backward compat).
