### ISSUE TITLE
Adding Jensen Shannon Divergence

### ISSUE THREAD

**Issue by Eight1911** [scipy/scipy#8244]
Can we add Jensen-Shannon divergence to `scipy.spatial.distance`? [here's the link](https://en.wikipedia.org/wiki/Jensen%E2%80%93Shannon_divergence). It's very simple to calculate and is very nice for embedding probability distributions into two/three dimensional space for visualization since (1) it is symmetric and (2) is always finite (and even bounded).

If moderators give me the green light, I would like to add it to the library, but might need some guidance since this is my first time contributing to scipy.

**Comment by xoviat** [comment]
Would you mind posting a quick Cython implementation here?

**Comment by Eight1911** [comment]
I'm not very familiar with Cython, so here's a numpy implementation. `p` and `q` are probability vectors.
```python
def js(p, q):
    p /= p.sum()
    q /= q.sum()
    m = (p + q) / 2
    return (scipy.stats.entropy(p, m) + scipy.stats.entropy(q, m)) / 2
```

**Comment by bhavika** [comment]
Is it better to implement this in Cython or are we okay with @Eight1911's numpy implementation above? 
I could take this up if we need it in Cython.

**Comment by xoviat** [comment]
There's no loop, so the Python implementation is fine. In addition, Cython only makes sense if all of the code under you is either Cython or some other lower-level language, such as Fortran, which isn't the case here. I think this is just waiting on a PR.

**Comment by sethtroisi** [comment]
PR is merged, closing
