### ISSUE TITLE
linprog ignores equality constraints

### ISSUE THREAD

**Issue by LibourelLab** [scipy/scipy#8249]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
I wrote very simple lp test code and noticed that Aeq.x=b is ignored without reason for one of the three constraints. The solver finishes without an error message.
 
### Reproducing code example:
```<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```
from scipy.optimize import linprog
import numpy as np

Aeq=np.matrix([[-1,-1,0,1,1,0,0],
              [1,0,-1,-1,0,1,0],
              [0,1,1,0,-1,-1,-1]])

bq=np.array([0,0,0])
Ai=np.mat(np.eye(7)*-1)
Ai=np.vstack((Ai,(Aeq<0)*1))

bi=np.array([0]*10)
bi[7]=bi[8]=bi[9]=1

obj=[0,0,0,0,0,0,-1]

print(Aeq)
print(Ai)
print(bi)
print(bq)

res=linprog(obj, A_ub=Ai, b_ub=bi, A_eq=Aeq, b_eq=bq, options={"disp": True,"bland":True})
print(res)

print(Aeq.dot(res.x))

### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>
```
output:
[[-1 -1  0  1  1  0  0]
 [ 1  0 -1 -1  0  1  0]
 [ 0  1  1  0 -1 -1 -1]]
[[-1. -0. -0. -0. -0. -0. -0.]
 [-0. -1. -0. -0. -0. -0. -0.]
 [-0. -0. -1. -0. -0. -0. -0.]
 [-0. -0. -0. -1. -0. -0. -0.]
 [-0. -0. -0. -0. -1. -0. -0.]
 [-0. -0. -0. -0. -0. -1. -0.]
 [-0. -0. -0. -0. -0. -0. -1.]
 [ 1.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  1.]]
[0 0 0 0 0 0 0 1 1 1]
[0 0 0]
Optimization terminated successfully.
         Current function value: -1.000000   
         Iterations: 1
  status: 0
   slack: array([ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.])
 success: True
     fun: -1.0
       x: array([ 0.,  0.,  0.,  0.,  0.,  0.,  1.])
 message: 'Optimization terminated successfully.'
     nit: 1
[[ 0.  0. -1.]]

### Scipy/Numpy/Python version information: scipy 0.15.1, numpy 1.9, python 2.7
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```

**Comment by sschnug** [comment]
Your scipy-version 0.15.1 is the one of **January 2015!**. Update it!

While linprog is pretty broken in general (my opinion), it's not failing for this one in scipy's current version!

**Comment by LibourelLab** [comment]
With your help I have small examples working. Currently trying to get either solver to behave with a larger problem. May have to resort to cplex though.
