### ISSUE TITLE
Why is brute force optimization limited to 40 variables?

### ISSUE THREAD

**Issue by kgeis** [scipy/scipy#8252]
I am trying to brute-force optimize a function over more than 40 variables. I get an error. There is nothing in the documentation about this. I don't see a reason to arbitrarily cut off at 40 variables. If it is a performance issue, this should be the judgment of the caller. If not, more explanation should be provided like a related issue number for the cause of the limit.

### Reproducing code example:
```
output = brute(fitness, ranges)
```

### Error message:
```
ValueError: Brute Force not possible with more than 40 variables.
```

### Scipy/Numpy/Python version information:
```
('0.17.1', '1.11.1')
sys is blacklisted in this environment, but version is 2.7.xx.
```

**Comment by antonior92** [comment]
It seems like **a very bad idea** to try to use brute-force optimization for any problem with more than 40 variables!! Brute force creates a grid of points. For 40 variables, if you include only two points in each dimensions (which will probably give you a very bad result) this will result in ``2^40=1,099,511,627,776`` functions evaluations.  Which is unfeasible.

So if you is trying brute force optimization in more than 40 variables you are doing something very wrong. So, while arbitrary, this error is trying to warn the user that he is doing something that will *definitely* not work.

Have you tried to use other global optimization algorithms from scipy instead?

**Comment by kgeis** [comment]
Thank you for responding.

Wow. I was surprised to find `brute` to be very inefficient at much simpler problems. The following (as I see it) attempts to minimize a degenerate function over 7 binary variables. After running for half an hour on my laptop, it gets killed for running out of memory.

```
from scipy.optimize import brute

def func(x):
    return 0

ranges = tuple(map(lambda x: [0, 1], range(7)))

brute(func, ranges)
```

Increasing the number of variables in the example, I get the following errors:
`MemoryError`
`ValueError: array is too big.`
`ValueError: sequence too large; cannot be greater than 32`

The 40-variable catch tries to show a meaningful error but cases with less than 40 variables throw less meaningful errors. I think it might be best for programmer usability not to check for 40 variables but instead to catch these last two errors and throw a more qualitative (i.e. not referencing an exact 40 variable limit) message that the problem is too big.

**Comment by antonior92** [comment]
I agree with you there. Although, It doesn't seems to be a very urgent modification.

**Comment by andyfaff** [comment]
@kgeis, is the approach taken in #8255 sufficient do you think?

**Comment by kgeis** [comment]
@andyfaff, yes, I think this is sufficient. Thank you.
