### ISSUE TITLE
When given string inputs, scipy.stats.itemfreq returns counts as strings too.  

### ISSUE THREAD

**Issue by anntzer** [scipy/scipy#8268]
When given string inputs, scipy.stats.itemfreq returns counts as strings too.  While this may be more generally due to problematic handling of char arrays by numpy, it may make sense to instead return an object array (where the first column are the string objects and the second column the counts, as *integers*).

Originally noted on the matplotlib gitter channel re: categorical data handling by matplotlib.

### Reproducing code example:
```
In [1]: import scipy.stats; scipy.stats.itemfreq(["a", "b"])
Out[1]: 
array([['a', '1'],
       ['b', '1']],
      dtype='<U21')

```
Note that the counts are now strings.

### Error message:
N/A (see explanation above)

### Scipy/Numpy/Python version information:
```
1.0.0 1.13.3 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
This is the complete code for `itemfreq`:

    def itemfreq(a):
        items, inv = np.unique(a, return_inverse=True)
        freq = np.bincount(inv)
        return np.array([items, freq]).T

We had a discussion about `itemfreq` over four years ago (https://github.com/scipy/scipy/issues/599), and at the time, we were close to deprecating it.  Now that `numpy.unique` has the option `return_counts`, `itemfreq` could be simplified further to

    def itemfreq(a):
        items, freq = np.unique(a, return_counts=True)
        return np.array([items, freq]).T

So I'm now even more inclined to simply deprecate `itemfreq`, and point users to the equivalent functionality in`numpy.unique`in the deprecation message.

**Comment by anntzer** [comment]
I'm fine with that option too.
