### ISSUE TITLE
Smooth factor in doc of LSQBivariateSpline

### ISSUE THREAD

**Issue by BLaunet** [scipy/scipy#8275]
Small typo : despite what's written in the doc, there is no keyword 's' (smooth factor) when initializing a LSQBivariateSpline

### Scipy/Numpy/Python version information:
```
('1.0.0', '1.13.3', sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0))
```

Cheers !
Barth

**Comment by APwhitehat** [comment]
@BLaunet It may be possible that the doc in question is not the latest i.e. scipy v1.0.0 [LSQBivariateSpline](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.LSQBivariateSpline.html)
Could you please confirm ?

**Comment by BLaunet** [comment]
Looks like it was indeed the case, the doc is correct in the v1.0.0 !
Thanks 😉
