### ISSUE TITLE
./build_openblas.sh  cygpath: can't convert empty path

### ISSUE THREAD

**Issue by JaneShenYY** [scipy/scipy#8284]
I followed [the instructions](http://scipy.github.io/devdocs/building/windows.html#building-the-released-scipy) to the step of running "export OPENBLAS_COMMIT=5f998ef
export OPENBLAS_ROOT="C:\\opt" export BUILD_BITS=64". But after running it, I couldn't find a folder named opt under C drive. So I created another folder named _OpenBlasROOT_ under a directory and run "export OPENBLAS_ROOT="C:\***\***\OpenBlasROOT". Then ran "./build_openblas.sh", but got the errors as follows.

### Reproducing code example:
```
$ ./build_openblas.sh

```

### Error message:
```
cygpath: can't convert empty path
cygpath: can't convert empty path
HEAD is now at 5f998efd Merge pull request #1247 from martin-frbg/revert-cgroups-pr
rm: it is dangerous to operate recursively on '/'
rm: use --no-preserve-root to override this failsafe
./build_openblas.sh: line 36: gcc: command not found
make: gcc: Command not found
make: *** [Makefile.prebuild:54: getarch] Error 127
Makefile.system:958: Makefile.: No such file or directory
make: *** No rule to make target 'Makefile.'.  Stop.
make: gcc: Command not found
make: *** [Makefile.prebuild:54: getarch] Error 127
Makefile.system:958: Makefile.: No such file or directory
make: *** No rule to make target 'Makefile.'.  Stop.
./build_openblas.sh: line 48: cd: /lib: No such file or directory
cp: cannot stat './OpenBLAS/exports/libopenblas.def': No such file or directory
./build_openblas.sh: line 53: /bin/lib.exe: No such file or directory
./build_openblas.sh: line 63: zip: command not found
cp: cannot stat 'openblas-_gcc_win.zip': No such file or directory
```

### Scipy/Numpy/Python version information:
```
python2.7
```

**Comment by ilayn** [comment]
Can you please run those instruction line by line and see which one breaks down? if you type `export` you should see the whole list of settings. 

If everything goes OK, C:\\opt is going to be created by the build so you don't need to create it.

**Comment by JaneShenYY** [comment]
Thank you ilayn. I'm going to do it step by step again. Will come back to you soon.

**Comment by JaneShenYY** [comment]
I ran the three export one by one and there is no error for anyone and nothing else appeared. There is no folder named "opt" created.
`yshen@wt135-467wsw MSYS /c/Users/yshen/Github/build-openblas
$ export OPENBLAS_COMMIT=5f998ef

yshen@wt135-467wsw MSYS /c/Users/yshen/Github/build-openblas
$ export OPENBLAS_ROOT="C:\\opt"

yshen@wt135-467wsw MSYS /c/Users/yshen/Github/build-openblas
$ export BUILD_BITS=64
`

**Comment by JaneShenYY** [comment]
I repeated the previous steps and copies the results here:
`yshen@wt135-467wsw MSYS /c/Users/yshen/Github
$ make
make: *** No targets specified and no makefile found.  Stop.

yshen@wt135-467wsw MSYS /c/Users/yshen/Github
$ gfortran
bash: gfortran: command not found

yshen@wt135-467wsw MSYS /c/Users/yshen/Github
$ gcc
bash: gcc: command not found
`
All these outputs are what they should be?

**Comment by ilayn** [comment]
That looks like you haven't installed gcc and gfortran yet.
