### ISSUE TITLE
Should tests be written for scipy.sparse.linalg.isolve.minres ?

### ISSUE THREAD

**Issue by APwhitehat** [scipy/scipy#8288]
`minres` has been in scipy for quite some time now. Is there any reason for it to have no tests? 

I was looking into it, I have come up with a proposal for tests.
Some input from devs would be very helpful.

- [x] test_random_matrices:
       create random valued sparse matrix
       solve with minres (check convergence)
       assert_almost_equal with lsqr 
 - [x] test with well conditioned problem:
        test_shift, test_tol, test_x0 (should fail because of #6843)
        test asymmetric matrix fails with check=True
- [x] test with preconditioner: match with `M=None`
- [x] test callback
#### Corner cases 
- [ ] test_denormals
- [x] test_singular_matrix

### Scipy/Numpy/Python version information:
```
('1.1.0.dev0+b646ff4', '1.14.0', sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0))```

**Comment by rgommers** [comment]
`minres` does have tests, here: https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/isolve/tests/test_iterative.py#L40

It has 5 tests currently, and looks like those don't cover some things you suggest. Extra tests are welcome I'd say.
