### ISSUE TITLE
clang warning: dcopy_to_ucol.c:77:21: note: place parentheses around the assignment to silence this warning

### ISSUE THREAD

**Issue by yurivict** [scipy/scipy#8290]
Could you please build with clang, and fix all warnings, including this one:
```
scipy/sparse/linalg/dsolve/SuperLU/SRC/dcopy_to_ucol.c:77:21: note: place parentheses around the assignment to silence this warning
                    if (mem_error = dLUMemXpand(jcol, nextu, UCOL, &nzumax, Glu))
                                  ^
                        (                                                       )
```

**Comment by rgommers** [comment]
That would be nice, the clang builds are very noisy. Is there a reason beyond readable build logs for you @yurivict? It definitely would be good, but isn't very high prio unfortunately.

**Comment by yurivict** [comment]
This particular line looks like it could be meant to be a comparison. Maybe some of them are actually confused?
This is why this caught my eye. -) Some bad problems might be hiding among these innocent-looking warnings.

**Comment by ilayn** [comment]
They are also mostly coming from third party libraries and when the compilers (or corresponding flags) are different than what the original authors had in mind.

**Comment by rgommers** [comment]
I'm going to close this. We solve relevant build warnings on an ongoing basis. This isn't one of them though, SuperLU is vendored so we want to not modify our copy of it unless absolutely essential. Simple things like build warnings should be solved upstream.
