### ISSUE TITLE
 Broken links on scipy API web page

### ISSUE THREAD

**Issue by emmanuelle** [scipy/scipy#8298]
In the API definition page https://docs.scipy.org/doc/scipy/reference/api.html#api-definition, submodules are listed in plain text, without hyperkinks. I guess there should be hyperlinks linking to modules APIs. Did something go wrong with sphinx configuration?
![screenshot from 2018-01-15 13-05-38](https://user-images.githubusercontent.com/263366/34941659-f51a8ff6-f9f4-11e7-8666-293b9f43bda9.png)

**Comment by ilayn** [comment]
I think that is just a list. They have hyperlinks in the previous page. https://docs.scipy.org/doc/scipy/reference/index.html

**Comment by pv** [comment]
They're plain text in the source
https://raw.githubusercontent.com/scipy/scipy/master/doc/API.rst.txt
could be hyperlinked though

**Comment by emmanuelle** [comment]
Thanks for your answers. So I was looking at the wrong API page; I don't know how frequent this mistake is, though. If I find the time I'll add the hyperlinks.

**Comment by rgommers** [comment]
@emmanuelle done already in gh-8301. thanks for reporting!

**Comment by emmanuelle** [comment]
Thanks @rgommers :-)
