### ISSUE TITLE
tocsr()  MemoryError

### ISSUE THREAD

**Issue by blancyin** [scipy/scipy#8299]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
I used a very large coo matrix <30,000,000 * 5,000,000>, about 3,000,000,000 point in matrix
where i tried:
interactions.tocsr()
error happend.
The machine is 256GB.

### Reproducing code example:
```
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```

### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>
```
File "model_train.py", line 349, in <module>
    model.fit_partial(matrain,epochs=10,item_features=features,num_threads=48,verbose=True)
  File "build/bdist.linux-x86_64/egg/lightfm/lightfm.py", line 473, in fit_partial
  File "build/bdist.linux-x86_64/egg/lightfm/lightfm.py", line 243, in _get_positives_lookup_matrix
  File "/usr/local/lib/python2.7/site-packages/scipy/sparse/coo.py", line 337, in tocsr
    row = self.row.astype(idx_dtype, copy=False)
MemoryError

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```

**Comment by pv** [comment]
The error is telling you that you don't have enough memory to do the 
conversion, which may indeed be the case. To prove otherwise, you need 
to provide the nnz of the matrix.

**Comment by pv** [comment]
No reply, closing.
