### ISSUE TITLE
broken links in numpy.interp() documentation

### ISSUE THREAD

**Issue by harmv** [scipy/scipy#8303]
I found some broken links in `numpy.interp()` documentation.

Not sure if these type of broken links are in more docs, or just in `numpy.interp()`

### Reproducing code example:

Go to https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.interp.html

After the example there are 3 links: (Source code, png, pdf)

Click on any of those links

### Error message:
You get a 404 on 
* https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy-interp-1.py
* https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy-interp-1_00_00.png
* https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy-interp-1_00_00.pdf

### Scipy/Numpy/Python version information:

https://docs.scipy.org/doc/numpy-1.13.0/

**Comment by andyfaff** [comment]
@harmv, thanks for taking the time to submit this report. However, this issue needs to be reported on the numpy issue tracker, not the scipy issue tracker.
https://github.com/numpy/numpy/issues
