### ISSUE TITLE
Matrix (scipy sparse) - Matrix (dense; numpy array) multiplication efficiency

### ISSUE THREAD

**Issue by sgkang** [scipy/scipy#8310]
Hello Scipy developers, 

We are developing open source geophysical inversion packages called [SimPEG](https://github.com/simpeg/simpeg), 
and it requires computing large matrix-vector multiplication. I found potential place to be improved in scipy, and curious what do you guys think.

Can we add `axpy` in `csr_matvec` routine (BLAS) as it is in `csr_matvecs`? 

https://github.com/scipy/scipy/blob/233c0ce63910f4eba6c31d95fa2a42ea0ac86e5b/scipy/sparse/sparsetools/csr.h#L1114

See below for details. 

https://stackoverflow.com/questions/43546372/matrix-scipy-sparse-matrix-dense-numpy-array-multiplication-efficiency

**Comment by ilayn** [comment]
Did you try with the version with call to `axpy` ? It would really nice to see whether this slowdown is indeed due to the raw loop vs. BLAS or it is just the overhead.

**Comment by sgkang** [comment]
Thanks @ilayn it seems not. I tried with 
```
template <class I, class T>
void csr_matvec(const I n_row,
                const I n_col,
                const I Ap[],
                const I Aj[],
                const T Ax[],
                const T Xx[],
                      T Yx[])
{
    for(I i = 0; i < n_row; i++){
        T * y = Yx + (npy_intp)1 * i;
        for(I jj = Ap[i]; jj < Ap[i+1]; jj++){
            const I j = Aj[jj];
            const T a = Ax[jj];
            const T * x = Xx + (npy_intp)1 * j;
            axpy(1, a, x, y);
        }
    }
}
```
but, it does not help. 

I am not sure why, but here is a temporary solution that I have found. 
```
import numpy as np
import scipy.sparse as sp
n = int(1e6)
m = int(100)
e = np.ones(n)
A = sp.spdiags(np.vstack((e, e, e)), np.array([-1, 0, 1]), n, n)
A = A.tocsr()
u = np.random.randn(n,m)
# %timeit rhs = A*s
%timeit rhs = A*u[:,0]
#10 loops, best of 3: 22 ms per loop    
%timeit rhs = A*u[:,:10]
#10 loops, best of 3: 98.4 ms per loop
%timeit rhs = A*u
#1 loop, best of 3: 570 ms per loop

u_copy = u[:,0].copy()
u10_copy = u[:,:10].copy()
# %timeit rhs = A*s
%timeit rhs = A*u_copy
#100 loops, best of 3: 7.38 ms per loop
%timeit rhs = A*u10_copy
#10 loops, best of 3: 50.2 ms per loop
%timeit rhs = A*u
#1 loop, best of 3: 525 ms per loop
```
do you have any idea why `numpy.copy()` help?

**Comment by ewmoore** [comment]
@jakevdp's answer on stackoverflow is incorrect.  The `csr_matvecs` routine does not call out to the BLAS.  It's actually calling the `axpy` function in [/scipy/sparse/sparsetools/dense.h#L12]([https://github.com/scipy/scipy/blob/233c0ce63910f4eba6c31d95fa2a42ea0ac86e5b/scipy/sparse/sparsetools/dense.h#L12)

There isn't a trivial way to speed up `csr_matvec` using this approach because you only have a single value from the vector, whereas in in `csr_matvecs` you have one value from each column.

**Comment by ilayn** [comment]
Based on Eric's input, closing this.
