### ISSUE TITLE
Bewildered by wrong values in sparse matrix data

### ISSUE THREAD

**Issue by jrounds** [scipy/scipy#8314]
Hi,

I messed with this for a few hours thinking surely I am doing something wrong.   I still think I might just because it is such a show-stopper, so I present this "issue" humbly thinking I must not understand something.

I am loading a coo_sparse matrix and after any operation that converts it to dense or to csr or to array the data is corrupted.  I tried to fix it it on my development laptop by  upgrading packages.  After that didn't fix it, I ssh'd into a remote system I have used, and I got the same result (which I did not expect).  At that point I came here with it.  It is strange and I don't understand it.

### Reproducing code example:
```
import numpy as np
from scipy import sparse
np.random.seed(1)
r = np.random.choice(range(24000), 141213)
c = np.random.choice(range(360),141213)

new_value = np.repeat(0.5, repeats=len(r))
tuple = (new_value, (r,c))
ret_mat = sparse.csr_matrix(tuple) 
np.argwhere(ret_mat.data > 1.0001)
np.sum(ret_mat > 1.0001)

```
I expect the sum to be 0 and the argwhere to be empty list, but it is not.  It has 5 entries.
```
>>> import numpy as np
>>> from scipy import sparse
>>> np.random.seed(1)
>>> r = np.random.choice(range(24000), 141213)
>>> c = np.random.choice(range(360),141213)
>>> 
>>> new_value = np.repeat(0.5, repeats=len(r))
>>> tuple = (new_value, (r,c))
>>> ret_mat = sparse.csr_matrix(tuple) 
>>> np.argwhere(ret_mat.data > 1.0001)
array([[  8034],
       [ 14717],
       [ 38641],
       [ 96270],
       [121449]])
>>> np.sum(ret_mat > 1.0001)
5
>>> 
```

The call to csr_matrix is not the direct issue.  Doing coo_matrix and then tocsr (or todense or most anything does the same thing.  For example this is more like how I was trying to use the code:
```
>>> import numpy as np
>>> from scipy import sparse
>>> np.random.seed(1)
>>> r = np.random.choice(range(24000), 141213)
>>> c = np.random.choice(range(360),141213)
>>> 
>>> new_value = np.repeat(0.5, repeats=len(r))
>>> tuple = (new_value, (r,c))
>>> ret_mat = sparse.coo_matrix(tuple) 
>>> np.sum(ret_mat.data > 1.0)  #<-- GOOD
0
>>> np.sum(ret_mat.tocsr().data > 1.0)  #<-- BAD?
5
>>> np.sum(ret_mat > 1.0)
5
>>> np.sum(ret_mat.todense() > 1.0)
5

```

### Scipy/Numpy/Python version information:
```
#MAC Laptop
 import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
('1.0.0', '1.14.0', sys.version_info(major=2, minor=7, micro=10, releaselevel='final', serial=0))
#Linux Remote System
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
('0.18.1', '1.12.1', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0))

```

**Comment by pv** [comment]
Duplicate values are *summed together*. See the last example in
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html

**Comment by jrounds** [comment]
I understand.  Thank you.
