### ISSUE TITLE
prefer scipy.fftpack FFTs over numpy.fft ones where possible?

### ISSUE THREAD

**Issue by grlee77** [scipy/scipy#8324]
A user over at pyFFTW pointed out that recent scipy uses `numpy.fft.rfftn` and `numpy.fft.irfftn` in `fftconvolve` when the arrays are real-valued (pyFFTW/pyFFTW#205).  This means that naively monkeypatching `scipy.fftpack` with the pyFFTW interfaces would not provide a speedup for this case.  `scipy.fftpack` does not provide its own `rfftn` or `irfftn`, thus the use of `numpy.fft` is justified in this case.

However, I did a quick grep to see where else functions from `numpy.fft` get used and found two additional files in `scipy.signal`:

 ~- scipy/signal/spectral.py~ 
 - scipy/signal/fir_filter_design.py

For those two files, it appears to be 1D `rfft`, `irfft`, `fft` and/or `ifft` that are used which all also exist in `scipy.fftpack`.  Is there a good reason not to switch to `scipy.fftpack` variants in these two files?

If it sounds acceptable, I am willing to make a small PR to update `scipy.signal` to use the `fftpack` variants where possible.

**edit:** numpy.fft is no longer used in `spectral.py` as of current master.  I had looked at an outdated version of that file.  So I think it is really just the import at the top of scipy/signal/fir_filter_design.py that is at issue.

**Comment by larsoner** [comment]
The outputs of NumPy rfft are complex coefficients (and in some cases such
as frequency domain multiplication easier to work with), SciPy's are float
with real and imaginary parts of each coefficient as separate entries. The
selection of one versus the other may be intentional to take advantage of
the differing representations.

**Comment by grlee77** [comment]
Thanks.  I had forgotten that those were using different conventions.  I see that the usage with symmetric complex-valued data in `fir_filter_design` is more suited to the numpy implementation.  Thanks for the quick feedback.
