### ISSUE TITLE
Bug with filters? Filter seems to be returning NaN output

### ISSUE THREAD

**Issue by anfractuosity** [scipy/scipy#8339]
I seem to be getting NaN outputs using the butter filter. 

I've written a small test case which also produce NaN values in the output.  I was under the impression a filter should only produce NaN values, if the input data contains NaN values?  Please forgive me if that's not the case.

In my real-world program I am using audio data though.

### Reproducing code example:
```
#!/usr/bin/python3
import numpy as np

samp = 44000. 
from scipy.signal import butter, lfilter

def butter_bandpass(lowcut, highcut, fs, order=5):
    nyq = 0.5 * fs
    low = lowcut / nyq
    high = highcut / nyq
    b, a = butter(order, [low,high], btype='bandpass')
    return b, a

def butter_bandpass_filter(data, lowcut, highcut, fs, order=5):
    b, a = butter_bandpass(lowcut, highcut, fs, order=order)
    y = lfilter(b, a, data)
    return y

data = []
for i in range(44000*3):
    data.append(0.5)

dat = np.array(data)
print("in isnan",np.isnan(dat).any())
print("in isinf",np.isinf(dat).any())

dat = butter_bandpass_filter(dat,49.,51.,samp,5)

print("out isnan",np.isnan(dat).any())
print("out isinf",np.isinf(dat).any())
```

### Error message:

Output from running test case:

```
in isnan False
in isinf False
out isnan True
out isinf True
```

### Scipy/Numpy/Python version information:
```
0.18.1 1.12.1 sys.version_info(major=3, minor=5, micro=3, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
Your sampling frequency is 44000 Hz, and you are trying to create a bandpass filter where the pass band is from 0.49 Hz to 0.51 Hz.  There is no way to you'll get a useful order 5 Butterworth filter for such a tight bandwidth.  Are you sure that's what you want to do?   Look at those convenience functions again, and take a look at the stackoverflow answer where I first wrote them: https://stackoverflow.com/questions/12093594/how-to-implement-band-pass-butterworth-filter-with-scipy-signal-butter/12233959#12233959.  The arguments `lowcut` and `highcut` must be expressed in the same units as `fs` (typically Hz).

You are getting nans because the filter created by `butter` is actually unstable, and the filtered signal blows up.

**Comment by anfractuosity** [comment]
Thanks a lot for your reply.  It's very helpful!

Is the pass band not 49Hz to 51Hz, or am I mistaken there?

I am trying to filter 49 to 51Hz to replicate results from the paper below:

"band pass filtering - The frequencies of interest are around 50 Hz, so the decimated audio file is
digitally band pass filtered from 49.5 Hz to 50.5 Hz to isolate the ENF." - https://www.forensic.to/ENF%20processed.pdf

**Comment by WarrenWeckesser** [comment]
Sorry, I just noticed my mistake: your values are 49 and 51, not .49 and .51.  That is still a pretty small bandwidth for an order 5 Butterworth filter.

At the moment, I'm experimenting with a filter in SOS format to see how much better it performs.

**Comment by WarrenWeckesser** [comment]
Thanks for the reference.  I wasn't aware of this technique for determining the time of recording of a signal.  Pretty cool.

In the bullet above the one about band pass filtering, the paper describes another important step:

* *Signal decimation* – Many digital audio recordings are recorded at high sampling frequencies –
e.g.,   44100   Hz.   To   detect   the   ENF,   which   is   approximately   50   Hz,   much   lower   sampling
frequencies   are   allowed.   The   audio   file   is   thus   decimated   to   a   sampling   frequency   of   300   Hz,
which significantly reduces computational time.

Decimating the signal before applying the bandpass filter makes sense--then the relative bandwidth isn't so small.

**Comment by anfractuosity** [comment]
Thanks a lot for the pointer, I'll look into doing that.
I'll close this issue now.

Cheers!
