### ISSUE TITLE
proposal: in scipy.optimize allow fprime to be returned as second argument of func

### ISSUE THREAD

**Issue by mikofski** [scipy/scipy#8345]
There are several algorithms in `scipy.optimize` that take `fprime` as an argument. However, there are often similar calculations in both `func` and `fprime`. Perhaps repeat calculations could be simplified by combining them into the same function by letting `fprime` be an optional secondary output of `func`. This API would similar to the MATLAB optimization toolbox, _e.g._: [`fsolve`](https://www.mathworks.com/help/optim/ug/fsolve.html#inputarg_fun).

Example: [solar-cell 1-diode analog using Shockley's diode equation](https://en.wikipedia.org/wiki/Theory_of_solar_cells)
```
# residual
f = il - io * (exp((v + i * rs) / vt) - 1.0) - (v + i * rs) / rsh - i

# df/di, assuming v is constant
fprime = -io * exp((v + i * rs) / vt) * rs / vt - rs / rsh - 1.0
```

### Reproducing code example:
If defined separately, `exp((v + i * rs) / vt)` is repeated in both `func` and `f_prime`. I propose that instead of returning these separately, they are returned from a single function:
```python
import numpy as np
from scipy.optimize import newton

ARGS = (0.5, 6.06, 1.0e-9, 0.001, 10, 0.026)  # v, il, io, rs, rsh, vt
X0 = 5.7

# current way:
def residual(i, v, il, io, rs, rsh, vt):
    """residual for calculating ``i`` from ``v``"""
    return il - io * (np.exp((v + i * rs) / vt) - 1.0) -  (v + i * rs) / rsh - i


def f_prime(i, v, il, io, rs, rsh, vt):
    """df/di assuming v is constant"""
    return -io * np.exp((v + i * rs) / vt) * rs / vt - rs / rsh - 1.0


i = newton(func=residual, fprime=f_prime, x0=X0, args=ARGS)
# 5.7291966066593423

# proposed way
def f_fprime(i, v, il, io, rs, rsh, vt):
    """
    residual, ``f``, for calculating ``i`` from ``v``
    :returns: the residual and it's derivative as a tuple
    """
    vd = v + i * rs  # diode voltage
    id_ = io * np.exp(vd / vt)  # diode current, sort of
    f = il - id_ + io - vd / rsh - i  # residual
    fprime = -id_ * rs / vt - rs / rsh - 1.0  # df/di, assuming v is constant
    return f, fprime


i = proposed_newton(func=f_fprime, x0=X0, args=ARGS, f_prime=True)
# if f_prime is true then func returns a sequence: (f, fprime)
```

### Error message:
```
FeatureNotImplementedError: The feature has not been implemented. Please create an issue and send a PR.
```

### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
0.19.1 1.13.3 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

**Comment by mikofski** [comment]
I am a fool: [this _is_ already implemented as the `jac` parameter in the `minimize` interface](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize). So Sorry!

**Comment by andyfaff** [comment]
Please be reassured that this wasn't a silly question. scipy is always on the lookout for potential improvements, including documentation contributions. It's just that in this case what you had in mind was already covered. If you feel that documentation can be improved in this area, feel welcome to suggest and implement changes.
