### ISSUE TITLE
Avoidable overflow in scipy.special.binom(n, k)

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#8346]
`scipy.special.binom(n, k) overflows in some situations when it can be avoided.

For large values of n, k `binom(n, k)`  is evaluated as `'1/beta(1+n-k, 1+k)/(n+1)`.
If `beta(1+n-k, 1+k)` is small, then overflow can occur before the division has a chance to bring it back into range.
 
### Reproducing code example:
```
import numpy as np
import scipy, scipy.special
k = np.arange(500, 520)
n=2*k
bn = scipy.special.binom(n,k)
bt = scipy.special.beta(1 + n-k, 1 + k)
print(np.column_stack([bn, 1/(n+1)/bt]))
```

The output is (first column is binom(n, k), the second an alternate computation)
```
[[  2.70288241e+299   2.70288241e+299]
 [  1.08007397e+300   1.08007397e+300]
 [  4.31599279e+300   4.31599279e+300]
 [  1.72468102e+301   1.72468102e+301]
 [  6.89188009e+301   6.89188009e+301]
 [  2.75402258e+302   2.75402258e+302]
 [  1.10052049e+303   1.10052049e+303]
 [  4.39774064e+303   4.39774064e+303]
 [  1.75736486e+304   1.75736486e+304]
 [  7.02255428e+304   7.02255428e+304]
 [              inf   2.80626777e+305]
 [              inf   1.12140876e+306]
 [              inf   4.48125455e+306]
 [              inf   1.79075474e+307]
 [              inf   7.15605105e+307]
 [              inf               inf]
 [              inf               inf]
 [              inf               inf]
 [              inf               inf]
 [              inf               inf]]
```

Computing instead as `1/(n+1)/beta(1+n-k, 1+k)` (the right hand column above) would allow a finite result to be returned.
The values returned by `scipy.special.beta` are potentially denormalized, so the result may have some lost some accuracy.  However these values have likely been generated by `scipy.special.betaln`, hence have already lost ~10 bits.

### Scipy/Numpy/Python version information:
```
1.1.0.dev0+bf4fa24 1.13.1 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

**Comment by ev-br** [comment]
Fixed by gh-8347
