### ISSUE TITLE
stats.multivariate_normal gives wrong result after reassigning covariance matrix

### ISSUE THREAD

**Issue by vinaym815** [scipy/scipy#8349]
If the covariance matrix is redefined, the pdf gives a wrong result

### Reproducing code example:
```
from scipy import stats
import numpy as np

samp = np.array([0.19, 0.26])
mu = np.array([0.88, 0.91])
cov = np.array([[0.50, 0.44],
 [0.44, 0.45]])

Dummymu = np.array([1, 2])
Dummycov = np.array([[1, 0.44], [0.44, 0.25]])

vin = stats.multivariate_normal(mean=mu, cov=cov)
print(vin.mean, '\n', vin.cov)
print(vin.pdf(samp))

a = stats.multivariate_normal(mean=mu, cov=Dummycov)

#a.mean = mu
a.cov = cov

print(a.mean, '\n' ,a.cov)
print(a.pdf(samp))

### Scipy/Numpy/Python version information:
```
>>> scipy.__version__
'1.0.0'
>>> numpy.__version__
'1.14.0'
>>> sys.version_info
sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
>>> 
```

**Comment by rkern** [comment]
The `.cov` attribute is not intended to be modifiable. Values derived from the `cov` input to the constructor are cached and are what are actually used to do most of the computations. When you assign just to `.cov`, those derived values are not updated.
