### ISSUE TITLE
SciPy Dev Install Videos

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#8353]
I drafted a [SciPy dev install video](https://youtu.be/28SvHp7yVes) last night. Written instructions are important, but a video avoids the potential ambiguity of written instructions and highlights when something is going wrong.

I have several questions:

- After installing Apple Developer Tools, did I need to install gcc with Homebrew?   It sounds like Apple Developer Tools include gcc.
- Is the Mac system Python install always called `python`? Then, is it safe to assume (on a fresh machine) that if we install `python3` with Homebrew, then calling `python3` (and `pip3`) will use the Homebrew installation?
- The SciPy instructions recommend using the Anaconda distribution of Python - shall I make a separate video about that? Am I correct that the differences should be to install Anaconda Python instead of Homebrew Python, make a virtual environment for development work, and remove the Anaconda SciPy install before replacing it with the from-source install?  
- Is the upgrade of `pip`, `setuptools`, and `wheel` important, or will they happen automatically as needed? 
- For the dependency installs, I know the overlay says PIP not PIP3; I'll fix that. 
- I'd love to make the code shown in the video lowercase... if someone can tell me whether that's possible in iMovie (insane, right?) I'd appreciate it.
- I thought SciPy 1.0 switched from `nose` to `pytest`, so I didn't install `nose`. Is it still needed?
- Any other dependencies to include / remove? Is `matplotlib` necessary?
- Why were 570 tests deselected? 

Other comments about the video and the description, which lists the commands and provides brief commentary, are welcome. 

If reviews are generally favorable, I'll finish the video I shot on setting up PyCharm and look toward making videos for an install that plays well with Anaconda/Spyder, basic git usage, and maybe testing and benchmarking. I'd also be happy to make similar videos for Windows when there's a process that works for me (please see #7140).

**Comment by person142** [comment]
> After installing Apple Developer Tools, did I need to install gcc with Homebrew

They include Clang, which builds SciPy just fine.

> Then, is it safe to assume... calling python3 (and pip3) will use the Homebrew installation?

Yes. Note that calling python and pip will still use the Homebrew python2/pip if you have them installed because they are earlier on your PATH.

> I thought SciPy 1.0 switched from nose to pytest, so I didn't install nose. Is it still needed?

No.

> Is matplotlib necessary?

Only for a very small subset of functionality (e.g. dendrograms).

> Why were 570 tests deselected?

There are optional test dependencies on (at least) `mpmath` and `sympy`, so it was probably those.

**Comment by jaimefrio** [comment]
I am writing this from a brand new Mac that I have just finished setting up. I don't recall having had to do this three years ago, when I did the same setup on another Mac, but the latest version of the command line tools does not include a Fortran compiler, and I have had to install gfortran from here:

http://gcc.gnu.org/wiki/GFortranBinaries#MacOS

**Comment by mdhaber** [comment]
@jaimefrio Do I understand that you disagree with the answer of @person142 that "They include Clang, which builds SciPy just fine."?

**Comment by jaimefrio** [comment]
Yes, that's my experience from yesterday and today. I don't recall having had this problem the last time I did the same setup, so it may be that Apple's command line tools have changed in recent versions?

**Comment by matthew-brett** [comment]
A long time ago, Apple installed gcc rather than clang with the developer tools.  I guess that may have included GFortran?

**Comment by jaimefrio** [comment]
Either that or it never was there and I forgot having had to install it... The page I linked above, where I got my gfortran binaries, does say something about it providing a full gcc installation, not just gfortran, so that would make sense.

**Comment by mdhaber** [comment]
@jaimefrio @matthew-brett Thank you for your comments. So given the current version of Apple Developer Tools, [scipy's instructions](http://scipy.github.io/devdocs/building/macosx.html) to install `gfortran` are appropriate.

I will just add a note to the video that it is not necessary to install _all_ of `gcc` as I did, that `brew install gcc` should be sufficient.

**Comment by person142** [comment]
Sorry for the confusion, I only meant to imply (as you have inferred already) that installing gfortran is sufficient.

**Comment by mdhaber** [comment]
Drafted [Part II: Setting up PyCharm](https://youtu.be/zRSfxJJZaUQ). I've always used Spyder, personally, but the on-the-fly PEP8 checker is making me consider switching.

New question: in the videos I did an in-place install, then I added that directory to the interpreter path. Is this what others typically do?  Or do you install to the default location, make the changes there, and set up git to work from there, too? (If so, how?)

Being able to change files, immediately test the results, and push to GitHub (all from the same local location) was probably the hardest part to figure out when I first started. I see there is some [documentation for NumPy](https://docs.scipy.org/doc/numpy-dev/dev/development_environment.html), but the bit about in-place install wasn't there when I first started, and I never was able to modify the PYTHONPATH correctly.

**Comment by ilayn** [comment]
FWIW, I am using Spyder real-time PEP8 checker and it's pretty OK.

**Comment by mdhaber** [comment]
I meant to look for that recently. In the past I guess I assumed that if the default was to do things like maintaining indents on empty lines and leave trailing spaces it wouldn't have an option to do the sane thing. And I did look in the past for [auto line-wrapping at 80 characters](https://github.com/spyder-ide/spyder/issues/4622), but that doesn't seem to be an option? 
Anyway, thanks. I'll be sure to test it out.

**Comment by ilayn** [comment]
The reason I like Spyder more is first its footprint is much less than PyCharm which is more like a development environment. Scientific users usually prefer scratchpad like environments rather than code- -compile-test cycle environments. For the line wrapping issue I actually keep the right margin at the 80 characters line so it wraps due to that. 

But anyways. editor preferences are always flamewar topics so let's not go down that path 😄 PyCharm is used worldwide so apparently there is a lot to it. 

More relevant to the subject is that PEP8 checks can be done  via `pep8` Python package before submitting a PR if the editor is not PEP8 check compatible. I guess that can be mentioned.

**Comment by perimosocordiae** [comment]
@mdhaber regarding [your comment](https://github.com/scipy/scipy/issues/8353#issuecomment-362787441) about install locations:

I do the following, though there may be a better / easier way:

1. Clone my fork of the scipy repo to a local directory under my homedir somewhere
2. Add a remote to the scipy/scipy repo called "upstream"
3. Make sure my master branch is up to date with `git pull upstream master`
4. Install from the local code, but not in-place, with `pip install .`

Then, when I want to make some changes:

1. Make a new branch: `git checkout -B my-bugfix`
2. Make my changes, committing as needed
3. Test the changes with `python runtests.py`, often with the `-i` flag to get me an interpreter
4. Push the branch to GitHub and open a PR from the web UI

This keeps my in-development branches from screwing up the installed version on the PYTHONPATH, which always points to some commit of scipy/scipy master.

**Comment by ev-br** [comment]
Just as a data point, I do the same as CJ, only instead of

> `git pull upstream master`

I do `git fetch upstream`, `git rebase upstream/master`

Also it's IMO worth recommending that everything is done is a separate virtualenv.

**Comment by mdhaber** [comment]
@perimosocordiae @ev-br Thanks for the suggestions. I understand that it is important to have a remote to the SciPy repo. I should have shown that in the first video, but I can probably add it if/when I make a video about basic git usage in the context of SciPy development.

Let's say that the directory to which you've cloned your fork is called `SciPyDev`; this is not in `site-packages` where modules are installed by default.

- When you do `pip install .` from `SciPyDev`, it builds SciPy in `site-packages`. This is always on the Python path by default.
- When you run `python runtests.py` from `SciPyDev`, it builds SciPy in `SciPyDev` and then runs the tests.  So isn't this essentially the same as `python setup.py build_ext --inplace`? Both build in-place; neither actually makes this version of SciPy available on the Python path.
- `runtests.py` is smart enough so that when you do `python runtests.py` _again_ it does not do a complete rebuild. But the _first_ time you execute `python runtests.py`, it takes just as long to build as when you did `pip install .`, yes? 
- If you've done the above then write a script using SciPy and run from `SciPyDev`, it will use the `SciPyDev` version of SciPy. Since you've already executed `python runtests.py`, it works because everything has already been built in `SciPyDev`, and the current working directory takes precedence over the rest of the Python path (including `site-packages`).
- If you put that same script anywhere else on the computer and run it from there, it will use the `site-packages` version of SciPy.
- You can add `SciPyDev` to the Python path temporarily with `export PYTHONPATH=$PWD`, but this is only useful inside the current terminal instance (and may not take precedence over the version in `site-packages`?), and you probably don't _want_ to add  `SciPyDev` to the path permanently while you have another version in `site-packages`.

Thanks for your patience. This is really helping me refine my mental model. 

I think one of the points of confusion is the distinction between the words "build" and "install". _Install_ tends to mean _build in a location that is on the Python path_ (or to build and then add the build location to the Python path).

**Comment by rgommers** [comment]
nice videos, thanks @mdhaber!

> Either that or it never was there and I forgot having had to install it...

`gfortran` was never there. It used to be hard to find, only an installer made by the R community was non-broken. Now the gcc wiki link above works, and the Homebrew one too.

**Comment by perimosocordiae** [comment]
On the *build* vs *install* distinction:

Building is the process of generating compiled modules (.pyc, .so / .dll files). This can happen in-place (in the same directory as the source [.py, .pyx] files), or in a separate build directory (typically at the top-level of the repository).

Installing is the process of adding the built module(s) to the python path, either by adding a new path entry or by moving the files to an existing location on the path (like site-packages).

**Comment by mdhaber** [comment]
@perimosocordiae Thanks; I agree that the distinction should be so clear. There is little ambiguity about the use of __build__ in the documentation, but __install__ seems to be used more loosely. The whole process really is very simple now; hopefully our improvements to the "getting started" documentation will save others a lot of headaches.

**Comment by mdhaber** [comment]
[Another video](https://youtu.be/1rPOSNd0ULI) based on the Anaconda distribution of Python and using Spyder as the IDE. The next video will follow up on this approach to create a SciPy dev virtual environment with `conda` and, for GUI fans like me, icons on the desktop that can be used to launch Spyder using this virtual environment or the default.

I think this video/approach is better for several reasons, one of which is that it shows how the development version of SciPy can be added after an existing Python/SciPy install.

**Comment by mdhaber** [comment]
And the [final dev setup video](https://youtu.be/Faz29u5xIZc) I planned to do (as described in yesterday's post).

Next, I'll try to find a (simple but) real issue to use as an example for how to create a branch, make and test changes, commit and push them, and start a PR.
