### ISSUE TITLE
gaussian_filter (correlate1d) segfaults when output array is complex

### ISSUE THREAD

**Issue by jcalbert** [scipy/scipy#8361]
(may be related to #8207)

### Reproducing code example:
```
import numpy as np
from scipy.ndimage import correlate1d

real_array = np.ones(10, dtype=np.float)
imag_array = np.ones(10, dtype=np.complex)

correlate1d(real_array, real_array, output=imag_array)
```

### Error message:
```
31748 segmentation fault  python /tmp/gauss.py
```

### Scipy/Numpy/Python version information:
```
('1.0.0', '1.14.0', sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0))
```

**Comment by jcalbert** [comment]
On closer examination, the problem lies in `correlate1d`

```
import numpy as np
from scipy.ndimage import correlate1d

real_array = np.ones(10, dtype=np.float)
imag_array = np.ones(10, dtype=np.complex)

correlate1d(real_array, real_array, output=imag_array)
```
produces the same error

**Comment by jaimefrio** [comment]
ndimage doesn't in general support complex arrays, as it converts everything to `double` internally before actually crunching the numbers.

Of course that doesn't justify the segmentation fault, but when this get fixed it will most likely be by raising an error about the output array being of an unsupported type: getting it to actually work with complex numbers would be a very major rehaul of ndimage.

**Comment by jcalbert** [comment]
Testing various dtypes with correlate1d:
```
import numpy as np
from scipy.ndimage import correlate1d
import sys

def corr_dtypes(d_in, d_out):
    a = np.ones( 10, dtype = d_in)
    b = np.ones( 10, dtype = d_out)
    try:
        correlate1d(a, a, output=b)
    except Exception as e:
        print "Exception: " + str(e)
        sys.exit(-1)

d_in, d_out = sys.argv[-2:]
corr_dtypes(d_in, d_out)
```

and

```
from itertools import product
dtypes = 'f2 f4 f8 f16 c8 c16 i2 i4 i8 u2 u4 u8'.split()

for dts in product(dtypes, dtypes):
    proc = subprocess.Popen('python /tmp/gauss.py'.split() + list(dts))
    res = proc.communicate()
    if proc.returncode != 0:
       print dts
```
gives caught exceptions for:
input = c8, c16

segfaults for:
input = f2, f16
output = f2, f16, c8, c16

return code 0 for:
others

**Comment by jcalbert** [comment]
@jaimefrio 
> but when this get fixed it will most likely be by raising an error about the output array being of an unsupported type.

Agreed - an Exception is preferable.

**Comment by pv** [comment]
in gh-8215

**Comment by jaimefrio** [comment]
Does gh-8215 really fix the issues with the dtype of the output array? It seems to only be checking the input array's type.

**Comment by pv** [comment]
I think it checks also output. None of the code examples above crashes any more.

**Comment by jaimefrio** [comment]
Cool, thanks for checking!

**Comment by jcalbert** [comment]
Great, thanks.
