### ISSUE TITLE
A possible bug in the calculation of power spectrum (NOT DENSITY)

### ISSUE THREAD

**Issue by billtau** [scipy/scipy#8368]
When calculating the power spectrum, the normalization (scaling) used with a non-boxcar window function seems to be wrong. 

### Reproducing code example:
```
import numpy as np
from scipy.signal import welch

np.random.seed(1234)
fs = 10e3
N = 1e5
amp = 2*np.sqrt(2)
freq = 1234.0
noise_power = 0.001 * fs / 2
time = np.arange(N) / fs
x = amp*np.sin(2*np.pi*freq*time)
x += np.random.normal(scale=np.sqrt(noise_power), size=time.shape)

f, ps = welch(x, fs, scaling='spectrum')
fd, psd = welch(x, fs)
fb, psb = welch(x, fs, window='boxcar', scaling='spectrum')

print(ps.sum(), np.mean(x**2), psd.sum()*(fd[1]-fd[0]), psb.sum())

```

### Error message:
```
13.576791320648404 9.05592607517666 9.051194213765603 9.037877166996639

```

### Scipy/Numpy/Python version information:
```
1.0.0 1.14.0 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)

```
### Why I think this is a bug.

By definition of the power spectrum density (PSD), for a given input signal x(t), we should have 

  PSD.sum()*df ~ np.mean(x**2)

If what we calculated is the power spectrum (PS), what we should have is then, 
  
   PS.sum() ~ np.mean(x**2)
 
This is satisfied only when we use the 'boxcar' window function. For the default window function ('hann'),  PS.sum is not close to np.mean(x**2). 

The reason for this strange behavior of the power spectrum, I believe is related to the following lines in spectral.py: (Lines 1618-1623)

    if scaling == 'density':
        scale = 1.0 / (fs * (win*win).sum())
    elif scaling == 'spectrum':
        scale = 1.0 / win.sum()**2
    else:
        raise ValueError('Unknown scaling: %r' % scaling)

I do not understand why the scaling is 1.0/win.sum()^2 instead of 1.0/(win^2).sum() as in the case when scaling is 'density'.   From Numerical Recipes, I think using (win^2).sum() is the correct way to calculate power spectrum.

**Comment by e-q** [comment]
An important difference between a "power spectrum" and "power spectral density" is that the the power spectrum of gaussian noise is not invariant under FFT length; instead it preserves the peak heights of sinusoidal signals. If you care about RMS noise power, the spectral density keeps that invariant across FFT length. You can find more detail than you probably care about here: [Spectrum and spectral density estimation by the Discrete Fourier transform (DFT)](https://holometer.fnal.gov/GH_FFT.pdf)

You can also see that these invariants are tested in `test_window_correction` in [`scipy/signal/tests/test_spectral.py`](https://github.com/scipy/scipy/blob/7a7b4bdd9cb826afe14f2ea2bb3fd2cd4f6c715d/scipy/signal/tests/test_spectral.py#L487).
