### ISSUE TITLE
License-compatibility: Apache 2.0? Conflicting docs

### ISSUE THREAD

**Issue by sschnug** [scipy/scipy#8370]
I'm trying to find out if it's possible to incorporate code into scipy which is licensed under **Apache 2.0**.

While [this](https://softwareengineering.stackexchange.com/questions/40561/is-bsd-license-compatible-with-apache) *softwareengineering.stackexchange* answer doubt somewhat it's possible (in regards to re-licensing, which i assume is needed; not an expert), the docs are not that clear:

[Current docs: Scipy Developer Guide](http://scipy.github.io/devdocs/dev/index.html):

> Scipy is distributed under the modified (3-clause) BSD license. All code, documentation and other files added to Scipy by contributors is licensed under this license, unless another license is explicitly specified in the source code. Contributors keep the copyright for code they wrote and submit for inclusion to Scipy.

> Other licenses that are compatible with the modified BSD license that Scipy uses are 2-clause BSD, MIT and PSF. **Incompatible licenses are GPL, Apache** and custom licenses that require attribution/citation or prohibit use for commercial purposes.

(annotations by me)

[Current docs: Contributing to SciPy](http://scipy.github.io/devdocs/hacking.html)

FAQ:

>I based my code on existing Matlab/R/... code I found online, is this OK?

> It depends. SciPy is distributed under a BSD license, so **if the code that you based your code on is also BSD licensed or has a BSD-compatible license (MIT, Apache, ...) then it’s OK**. Code which is GPL-licensed, has no clear license, requires citation or is free for academic use only can’t be included in SciPy. Therefore if you copied existing code with such a license or made a direct translation to Python of it, your code can’t be included. See also license compatibility.

(annotations by be; i'm interpreting *Apache* as it would include *Apache 2.0* here)

**To me: this is a contradiction!**

The linked [old-wiki entry](https://scipy.github.io/old-wiki/pages/License_Compatibility.html) does not help here and is linked despite being *marked* as *This is an archival dump of old wiki content --- see scipy.org for current material*

The only other kind of information i found is [issue: #3606](https://github.com/scipy/scipy/issues/3606), where it's said:

> METIS is under Apache License 2.0, which seems non-problematic for BSD compatibility.

(no definitive answer of course)

So:

- is there a definitive answer to the question: **can i add code licensed under Apache 2.0 to scipy** (without interaction / asking for allowance)?
  - this subsumes somewhat alternative approaches (if there are any;)
    - e.g. matplotlib's: *Non-BSD compatible licenses are acceptable in matplotlib toolkits* which i don't think is pursued in scipy (in any way)

**Comment by rkern** [comment]
The first reference is still correct, I think, though we may want to revisit that policy. We have not allowed Apache 2.0-licensed code because it is GPLv2-incompatible, and we have wanted scipy to be usable in GPLv2 software. There were significant GPLv2 projects in our community that did not want to upgrade to GPLv3 (that is, they deliberately chose not to allow the upgrade option). Specifically, the [Sage project](http://doc.sagemath.org/html/en/reference/history_and_license/index.html), but it looks like they have updated their GPLv2 code to allow the GPLv3 upgrade. So maybe it's time to revisit our policy and only worry about GPLv3 compatibility.

**Comment by rgommers** [comment]
Thanks @sschnug for pointing that out, and @rkern for the historical perspective. The inconsistency is my fault, fixed in gh-8426.

I think it's fine to keep things as is for the time being. It's not like there's huge amount of Apache licensed code that we'd like to incorporate. So keeping GPL v2 compatibility for now sounds right to me.

@sschnug for the code you're interested in, you could ask the original author to relicense under MIT or BSD license for inclusion in SciPy

**Comment by sschnug** [comment]
@rgommers 
Relicensing might work for smaller projects, but i don't think larger ones would like that. But that's just a guess (from someone not that familiar).

I did not implement anything (in this regard), but an example for interesting Apache-software would be:

Google's ortools LP-solver [glop](https://github.com/google/or-tools/tree/master/ortools/glop) which is now even featured in [Mittelmann's benchmarks](http://plato.asu.edu/ftp/lpsimp.html). It's the only quality-solver i know of not being (L)GPL. (Coin Clp, GLPK, lpsolve, ...). (maybe it would also be a good base for a small branch-and-bound engine; but who knows...)

I think i commented on scipy's Simplex-solver a few times here (other issues) and it's state is alarming (imho). This includes functionality, bugs and especially maintainment (seems nobody is touching it).

**Comment by rgommers** [comment]
> Relicensing might work for smaller projects, but i don't think larger ones would like that. But that's just a guess (from someone not that familiar).

Indeed. I just didn't know what code you were thinking about.

>  think i commented on scipy's Simplex-solver a few times here (other issues) and it's state is alarming (imho).

Yes. The `interior-point` method to `linprog` is much better, so if no one is going to look at fixing up `simplex` then we should probably get rid of it. But that's a discussion for another thread.

> Google's ortools LP-solver glop which is now even featured in Mittelmann's benchmarks. It's the only quality-solver i know of not being (L)GPL. (Coin Clp, GLPK, lpsolve, ...). (maybe it would also be a good base for a small branch-and-bound engine; but who knows...)

that does look interesting
