### ISSUE TITLE
Is it safe to run scipy from multithreaded code when it's using multithreaded OpenBLAS?

### ISSUE THREAD

**Issue by augray** [scipy/scipy#8380]
I'm building OpenBLAS on my machine and letting scipy use that version of BLAS. Reading through the [usage for OpenBLAS](https://github.com/xianyi/OpenBLAS/blob/develop/USAGE.md), I found the following:

> **How can I use OpenBLAS in multi-threaded applications?**
>
> If your application is already multi-threaded, it will conflict with OpenBLAS multi-threading. Thus, > you must set OpenBLAS to use single thread in any of the following ways...

This surprised me because my build of OpenBLAS is multithreaded, and I'm using scipy from multithreaded code. Things have been running fine for me, even when I'm definitely using scipy + BLAS from multiple threads at once. Am I just lucky and destined to run into some threading issue eventually, or is it actually safe to continue on in the same way?

**Note**: I notice that the wheels on pypi come packaged with a binary for OpenBLAS. I'd be curious to know whether that build of OpenBLAS is set to be multithreaded or not. Bonus points if you can tell me what `NUM_THREADS` was for the build (see [OpenBLAS usage](https://github.com/xianyi/OpenBLAS/blob/develop/USAGE.md#usage) again)

**Comment by xoviat** [comment]
[Here](https://github.com/MacPython/openblas-libs) is the OpenBLAS library that we are using.

**Comment by u55** [comment]
@xoviat So if I understand correctly, the answer is that you are using [NUM_THREADS=64](https://github.com/MacPython/openblas-libs/blob/0055935978521e258e75220e631e798bd3b8987c/build_steps.sh#L60)?

**Comment by rgommers** [comment]
The answer here is: please use https://github.com/joblib/threadpoolctl.

I'll close this, since there's nothing to do here. Thanks all.
