### ISSUE TITLE
collections.OrderedDict in test_mio.py

### ISSUE THREAD

**Issue by atombrella** [scipy/scipy#8382]
in `test_mio.py`, the `try/except` is unnecessary, as the code is only tested on Python 2.7. The chunk is 6 years old, which probably explains the fallback.

```    
try:
        from collections import OrderedDict
    except ImportError:
        pass
    else:
dict_types += ((OrderedDict, True),)
```

**Comment by larsoner** [comment]
Indeed it looks like a historical relic, do you have time to make a quick PR to simplify this?
