### ISSUE TITLE
fix pep8/pycodestyle E305 expected 2 blank lines after class or function definition

### ISSUE THREAD

**Issue by peterjc** [scipy/scipy#8388]
See discussion on #8384 - Running pycodestyle v2.3.1 currently reports 257 cases of ``E305 expected 2 blank lines after class or function definition``.

These are simple whitespace style changes.

Assuming #8384 or similar is merged, then as part of fixing this whitespace, the style checker settings in ``tox.ini`` should be updated to stop ignoring E305.

**Comment by peterjc** [comment]
I'm going to work on this now - it looks like ``autopep8`` will work nicely...

**Comment by py-ranoid** [comment]
Hey. 
I'd like to start contributing to scipy with this. 
What's the status on this issue and how can I help ?

**Comment by andyfaff** [comment]
Thank you but this is already being tackled.
