### ISSUE TITLE
fix pep8/pycodestyle E741 do not use variables named ‘l’, ‘O’, or ‘I’

### ISSUE THREAD

**Issue by peterjc** [scipy/scipy#8389]
See discussion on #8384 - Running pycodestyle v2.3.1 currently reports 81 cases of ``E741`` which is one of a set of three style checks to avoid ambiguous single letter names which look like numbers:

* E741 do not use variables named ‘l’, ‘O’, or ‘I’
* E742 do not define classes named ‘l’, ‘O’, or ‘I’
* E743 do not define functions named ‘l’, ‘O’, or ‘I’

See https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes

The reasoning being in many fonts:

* Upper case eye looks like the digit one (``I`` vs ``1``)
* Upper case oh looks like the digit zero (``O`` vs ``0``)
* Upper case el looks like the digit one (``L`` vs ``1``)

Assuming #8384 or similar is merged, then as part of fixing this whitespace, the style checker settings in tox.ini should be updated to stop ignoring E741.

**Comment by person142** [comment]
I'm conflicted about `I`. IMO it's reasonable to call an identity matrix `I` and doing something else would be more confusing. Didn't check to see whether that was any of the 81 uses though.

**Comment by peterjc** [comment]
You can see the current output here, from the pre-ignore Travis run on #8384,

https://travis-ci.org/scipy/scipy/jobs/339050427

To give a breakdown:

45 x ``E741 ambiguous variable name 'l'``

2 x ``E741 ambiguous variable name 'O'`` (both in ``scipy/io/matlab/mio4.py`` which also uses ``I``)

34 x ``E741 ambiguous variable name 'L'``

**Comment by perimosocordiae** [comment]
Here's the complete list of E741 errors:

Variable named `I` (as in **I**dentity):

- [ ] scipy/integrate/_ivp/bdf.py:20:5
- [ ] scipy/integrate/_ivp/bdf.py:208:13
- [ ] scipy/integrate/_ivp/bdf.py:217:13
- [ ] scipy/integrate/_ivp/bdf.py:221:14
- [ ] scipy/integrate/_ivp/radau.py:310:13
- [ ] scipy/integrate/_ivp/radau.py:319:13
- [ ] scipy/integrate/_ivp/radau.py:323:14
- [ ] scipy/interpolate/tests/test_interpolate.py:1225:9
- [ ] scipy/interpolate/tests/test_interpolate.py:1652:9
- [ ] scipy/interpolate/tests/test_interpolate.py:36:9
- [ ] scipy/interpolate/tests/test_interpolate.py:47:9
- [ ] scipy/io/matlab/mio4.py:258:9
- [ ] scipy/io/matlab/mio4.py:260:9
- [ ] scipy/io/mmio.py:572:13
- [ ] scipy/io/mmio.py:606:13
- [ ] scipy/io/mmio.py:610:25
- [ ] scipy/io/mmio.py:615:17
- [ ] scipy/io/tests/test_mmio.py:532:9
- [ ] scipy/io/tests/test_mmio.py:556:9
- [ ] scipy/io/tests/test_mmio.py:574:9
- [ ] scipy/io/tests/test_mmio.py:589:9
- [ ] scipy/io/tests/test_mmio.py:607:9
- [ ] scipy/linalg/tests/test_decomp.py:2256:9
- [ ] scipy/linalg/tests/test_decomp.py:306:9
- [ ] scipy/linalg/tests/test_special_matrices.py:320:13
- [ ] scipy/odr/odrpack.py:127:9
- [ ] scipy/optimize/lbfgsb.py:459:9
- [ ] scipy/optimize/optimize.py:965:5
- [ ] scipy/optimize/tests/test_hungarian.py:64:5
- [ ] scipy/optimize/tests/test_hungarian.py:72:5
- [ ] scipy/sparse/dok.py:474:9
- [ ] scipy/sparse/linalg/matfuncs.py:73:5
- [ ] scipy/sparse/tests/test_base.py:2839:9
- [ ] scipy/sparse/tests/test_base.py:2861:9
- [ ] scipy/sparse/tests/test_base.py:2870:9
- [ ] scipy/sparse/tests/test_base.py:3107:9
- [ ] scipy/sparse/tests/test_base.py:3158:9
- [ ] scipy/sparse/tests/test_base.py:3186:9
- [ ] scipy/sparse/tests/test_base.py:3691:9
- [ ] scipy/sparse/tests/test_base.py:3893:9
- [ ] scipy/sparse/tests/test_construct.py:232:9
- [ ] scipy/sparse/tests/test_construct.py:237:13
- [ ] scipy/sparse/tests/test_construct.py:260:9
- [ ] scipy/sparse/tests/test_construct.py:265:13
- [ ] scipy/stats/mstats_extras.py:356:9

Variable named `l` (as in **l**ength):

- [ ] scipy/cluster/hierarchy.py:225:5
- [ ] scipy/integrate/quadrature.py:204:5
- [ ] scipy/interpolate/_bsplines.py:353:13
- [ ] scipy/interpolate/_bsplines.py:354:13
- [ ] scipy/interpolate/interpolate.py:891:13
- [ ] scipy/interpolate/interpolate.py:892:13
- [ ] scipy/io/harwell_boeing/tests/test_hb.py:49:5
- [ ] scipy/io/mmio.py:544:17
- [ ] scipy/io/mmio.py:591:17
- [ ] scipy/_lib/_numpy_compat.py:42:54
- [ ] scipy/linalg/basic.py:449:8
- [ ] scipy/linalg/_generate_pyx.py:634:36
- [ ] scipy/ndimage/measurements.py:409:16
- [ ] scipy/optimize/lbfgsb.py:269:24
- [ ] scipy/optimize/lbfgsb.py:300:13
- [ ] scipy/optimize/_lsq/common.py:360:5
- [ ] scipy/optimize/_remove_redundancy.py:101:5
- [ ] scipy/signal/filter_design.py:1745:28
- [ ] scipy/signal/filter_design.py:1754:28
- [ ] scipy/signal/signaltools.py:1824:16
- [ ] scipy/signal/signaltools.py:1903:16
- [ ] scipy/signal/signaltools.py:1995:16
- [ ] scipy/signal/signaltools.py:2090:16
- [ ] scipy/sparse/tests/test_base.py:4103:9
- [ ] scipy/spatial/tests/test_kdtree.py:279:9
- [ ] scipy/spatial/tests/test_kdtree.py:285:9
- [ ] scipy/spatial/tests/test_kdtree.py:333:9
- [ ] scipy/spatial/tests/test_kdtree.py:336:9
- [ ] scipy/spatial/tests/test_kdtree.py:342:9
- [ ] scipy/spatial/tests/test_kdtree.py:346:9
- [ ] scipy/special/utils/convert.py:126:5
- [ ] scipy/stats/_continuous_distns.py:916:9
- [ ] scipy/stats/_discrete_distns.py:576:9

Variable named `O` (as in **O**bject):

- [ ] scipy/io/matlab/mio4.py:120:12
- [ ] scipy/io/matlab/mio4.py:480:9

**Comment by WarrenWeckesser** [comment]
While some of these uses are fairly innocuous, overall this would be an improvement, so +1.  In fact, I'll start working on a pull request for the changes in `linalg`, `signal` and `stats`.  If someone has already started working on these, let me know so we don't duplicate our efforts.

**Comment by ilayn** [comment]
I started briefly but didn't go much far. So I would gladly leave it to you. Are you planning on all PEP items or only the bare except ones?

**Comment by WarrenWeckesser** [comment]
I'm replacing the single letter variables mentioned in this pull request (and doing some general PEP 8 clean up while I have the files open).  I haven't looked at the bare exceptions.

**Comment by pv** [comment]
Perhaps I'm a bit late to the party, but to be honest, I'm generally -0 
on pep8 cleanup PRs. These can conflict existing PRs, and clutter up the 
git annotate history.  Minor coding style inconsistencies that exist in 
the codebase probably probably don't matter so much for understanding, 
and I wouldn't like to introduce new changes only because they were 
added in a style checking tool.

**Comment by samyak0210** [comment]
Referring to https://github.com/scipy/scipy/pull/8454
I can't find why continuous integration build is failing. The changes I have made are just changing variables. Can someone tell me how can I check remotely on my pc where the main error is.

**Comment by andyfaff** [comment]
The CI tests are fixed by #8279

**Comment by samyak0210** [comment]
Can someone please run the Travis Build CI for this pull request https://github.com/scipy/scipy/pull/8454

**Comment by peterjc** [comment]
@samyak0210 why not comment over on #8484? Re-running the build will fail in the same way as it would use the same merge against the broken master branch. You need to update the pull request to trying a rebuild against the current working master (e.g. something like ``git rebase origin/master`` then ``git push samyak0210 issue8389 --force`` should do it).

**Comment by rgommers** [comment]
gh-8454 tried to address part of this; it turns out most SciPy devs are -0 or -1 on pure PEP8 cleanups. On balance the code churn isn't justified by pure PEP8 cleanups. I'll send a PR updating http://scipy.github.io/devdocs/hacking.html to close this issue.

**Comment by peterjc** [comment]
Similes don't work nicely on a mobile - that is a positive resolution 👍

**Comment by danky78** [comment]
why stop in single letter variable and not go with all variables that you can't know the character used by context?
For example Io/lo lds/Ids T0/TO, and a infinity of cases where a user that uses a FONT NOT SUITABLE FOR CODING can have trouble..

I think that the font used for programming is not coding style. I'ts a user preference. I found this pep annoying, I will still use "l" as ldap client for small scripts, as every example on internet is using.
