### ISSUE TITLE
brentq returns solutions outside of the bounds

### ISSUE THREAD

**Issue by Mark531** [scipy/scipy#8394]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

The root-finding brentq function sometimes returns solutions outside of the bracketing interval, which is unexpected.

### Reproducing code example:
```
from scipy.special import pbdv
from scipy.optimize import brentq

def f(x):
    z = 10 * (100 - x)
    d1 = pbdv(-1.0002, z)[0]
    d2 = pbdv(-0.0002, z)[0]
    return 0.002 * (x - 0.01) * d1 - d2

print(brentq(f, 100, 130))
```

### Error message:
```
print(brentq(f, 100, 130)) returns 65.0 while 65.0 does not belong to [100, 130].
```

### Scipy/Numpy/Python version information:
```
0.18.1 1.11.2 sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
```

**Comment by charris** [comment]
I see
```
In [5]: print(brentq(f, 100, 130))
/home/charris/.local/bin/ipython:5: RuntimeWarning: invalid value encountered in double_scalars
  start_ipython()
65.0
```
Which makes me suspicious :)

**Comment by charris** [comment]
Maybe we should error in that circumstance.

**Comment by Mark531** [comment]
I don't see that warning...
In fact, f(130) is a NaN, so I guess that is what confuses the algorithm. I guess a simple bound-check should be performed.

**Comment by charris** [comment]
There is a bounds check, but it won't work with nan :(
```
    if (fpre*fcur > 0) {
        params->error_num = SIGNERR;
        return 0.;
    }
```
I suppose we change that to  `if (!(fpre*fcur <= 0)) {`

**Comment by Mark531** [comment]
I know that working with NaNs is painful in python. It's nice if you found a way to get around this problem.
In that case, NaN just signals that the function is very high, but it still admits a root.

**Comment by josef-pkt** [comment]
related issue #3089
