### ISSUE TITLE
Does Brute try all possible combinations?

### ISSUE THREAD

**Issue by tjdurant** [scipy/scipy#8395]
Hello,

I have a set of parameters. 

A: 5,10,15,20,25,30,35,40,45,50,55,65,70
B: 135,140,145,150 
C: 105,100,95,90
D: 122,124,126,128
E: 118,116,114,112

An experiment would take one from each. E.g.: [5,135,105,122,118]

Does Brute try every possible combination of these? 

Any insight will be greatly appreciated,
Thanks!
Tommy

**Comment by jcalbert** [comment]
Brute doesn't work with lists of values like you've mentioned, it checks the function at points on an evenly-spaced grid (e.g. `f( [0,0,0] ), f([0,0,1]), f([0,0,2]), f([0,1,0])`... )

A quick-and-dirty way of doing what you've asked for would be
```
def example_function(vals):
    return sum(vals) / ( max(vals) - min(vals) )

from itertools import product
a = [5,10,15,20,25,30,35,40,45,50,55,65,70]
b = [135,140,145,150]
c = [105,100,95,90]
d = [122,124,126,128]
e = [118,116,114,112]

min_value, min_args = min( (example_function(x), x) for x in product(a,b,c,d,e) )
```

**Comment by tjdurant** [comment]
@jcalbert 

Sorry, I should have been more clear. The list of parameters are put into a function, as it looks like you are describing in your first paragraph. 

With examples from my actual script:

```
def objective(x, *params):
    [....]
    return min_obj

a = slice(5, 70, 5)
b = slice(105, 130, 5)
c = slice(75, 100, 5)
d = slice(2, 10, 2)

rranges = (a,b,c,d)

brute_result = brute(
    func=objective,
    args=params,
    ranges=rranges,
    full_output=True,
    disp=True,
    finish=None
)
```

So when I run it, I get 1,300 iterations (e.g. (len(a) * len(b) * len(c) * len(d) * len(e)) which would represent all possible combinations of these, correct? 

When I do this with itertools.product: 

```
def objective(x, *params):
    [....]
    return min_obj

a = range(5, 70, 5)
b = range(105, 130, 5)
c = range(75, 100, 5)
d = range(2, 10, 2)

for x in product(a,b,c,d):
    objective(x, *params)
```

When I run this, I also get 1,300 iterations. The results of the function look the same.

Are they doing the same thing?

**Comment by jcalbert** [comment]
Ah, I didn't realize that A,B,C,D,E actually _were_ equispaced ranges.  In that case, yes, they should be equivalent.

**Comment by andyfaff** [comment]
Seems to have been solved.
