### ISSUE TITLE
Precision of CDFLIB too low

### ISSUE THREAD

**Issue by samuelstjean** [scipy/scipy#8398]
Hello, 
I was trying to get some function running, but the precision somehow seems to be less than it should be. I'm wondering if as scipy special is mainly a huge wrapper for old C/fortran, it tries to return the same types for everything while the underlying calls may not support the same precision overall. Most specifically, a small example from scipy special

### Reproducing code example:
```
from scipy.special import *
>>> chndtr(30,20,10)
0.53729263090336321
>>> type(chndtr(30,20,10))
<class 'numpy.float64'>
```
The same thing from R

```
options(digits=15)
pchisq(30,20,10,TRUE)
[1] 0.53729299061242
```

And if you look at their difference it is around 1e-7. Asking the same thing from wolfram alpha indicates R as a precision of around 1e-15 and scipy 1e-7, while scipy still returns a double though.

For R
https://www.wolframalpha.com/input/?i=CDF%5BNoncentralChiSquareDistribution%5B20,+10%5D,+30%5D+-+0.53729299061242

for scipy 
https://www.wolframalpha.com/input/?i=CDF%5BNoncentralChiSquareDistribution%5B20,+10%5D,+30%5D+-+0.53729263090336321

While that may seems not much, we are dealing with probabilities, and in the long run for my (not these numbers but something else), case it makes the whole thing unprecise at around 3 digits unfortunately when comparing from R to scipy, which is not enough for my applied case.

Now for the weird part, if one follows the wrappers, the scipy part is written in fortran and using a bunch of C wrappers around it, but everything seems to be in double

https://github.com/scipy/scipy/blob/master/scipy/special/cdf_wrappers.c
https://github.com/scipy/scipy/blob/master/scipy/special/cdflib/cdfchn.f

Are the underlying methods just not precise or there is some double wrapping missing somewhere? That part unfortunately goes over my knowledge of stuff as of now.

I'm still on 0.19.1 from anaconda though, so ahem, it may have been fixed in more recent versions.

**Comment by person142** [comment]
> Are the underlying methods just not precise

It's this one. A good place to start investigating would be here

https://github.com/scipy/scipy/blob/master/scipy/special/cdflib/cdfchn.f#L97

where the tolerances

```fortran
      DOUBLE PRECISION tol
      PARAMETER (tol=1.0D-8)
      DOUBLE PRECISION atol
      PARAMETER (atol=1.0D-50)
```

are set. If we assume that your example is being limited by `tol`, then you would get the accuracy you are reporting. You might try tightening that and seeing what happens.

**Comment by pv** [comment]
If the issue is just that the default tolerance 1e-8 in the CDFLIB
routines, it should be easy to fix just by a blindly changing them to
smaller numbers. Whether and how that works in different cases may need
looking into how the inversion is implemented in `dinvr.f`

**Comment by samuelstjean** [comment]
Ah well that was simple to find. Now for the real question though, was that set up in the default cdflib since more precision would just take forever to converge(if even...), or it was forgotten from the float to double overall conversion.

Problem is changing all these thing blindly is a recipe for impossible to debug disasters in a few years, but if it may be the only thing (and place) I can edit it, see fi the whole testing would run with relaxed precision, and hope it works without taking hours to compute. If it suffer from 'slow' convergence, having everybody mainstream stuff go slower would be horrible though.

**Comment by pv** [comment]
@samuelstjean: are you now talking about hyp1f1 or cdflib? Let's only talk about CDFLIB in this thread. If you have issues with hyp1f1, please file a separate issue for it.

**Comment by samuelstjean** [comment]
nah, I meant there are still issues with hyp1f1 (although I'm not even sure the theory is well developed for th problematic cases), I would not want to create issues with this part of cdflib by mistake like it happened to the other one. 

But yes that is something for another day anyway, unless I'm mistaken I thought a few people participated to that issue some time ago (including you, or I have a terrible memory), but I doubt anything can be done with the currently wrapped version as of now, it did end up on the roadmap to 1.0 with the possibility of shipping ti with arbitrary precision for computation though, but that is far from th issue here anyway.


So ahem, if it could work, I can try to edit the fortran stuff to say get the tolerance to 1e-15 and cross fingers it still works, not accumulating errors in unknown ways by doing that which would not be covered by the currently checked test (which might also need a relaxation)

**Comment by pv** [comment]
Those tolerance parameters in cdflib iiuc control a root finder, so in principle there should not be problem in reducing them, and it's less likely they cause side effects.

**Comment by sethtroisi** [comment]
@WarrenWeckesser It seems after your PR #8673 resolved this.

Error on the provided sample (as well as a two other random tests) is no  ~1e-12 instead of  ~1e-7
