### ISSUE TITLE
Does scipy.linalg need a rcond() or cond()? 

### ISSUE THREAD

**Issue by ilayn** [scipy/scipy#8406]
Currently, [numpy.linalg.cond](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.cond.html) is a bit underperforming. (See https://github.com/numpy/numpy/issues/6364, https://github.com/numpy/numpy/issues/7907, https://github.com/numpy/numpy/issues/8090). There doesn't seem much initiative for the resolution to those issues. But for typical linalg operations this is a frequently used command in other software tools. I tried but failed to get into the NumPy code to fix them myself.

Also, in both libraries a quick and decisive `rcond` with respect to inversion is missing. We have already injected some `rcond` machinery already in `scipy.linalg.solve` to emit ill-conditioning warnings. 

Thus, is it a valid function to be included in SciPy or somehow the NumPy version should be addressed first for `cond()`. 

And how do people feel about a separate `rcond()` function in the name space (possibly with a less annoying name)?

**Comment by pv** [comment]
I would think the best option would be to fix `numpy.linalg.cond`. The best way to go about it is probably to (i) decide how to do it with lapack routines, (ii) see if it can be done with routines in [lapack_lite](https://github.com/numpy/numpy/tree/master/numpy/linalg/lapack_lite) or if you need to add some there, (iii) write a gufunc implementation similar to `det`:
https://github.com/numpy/numpy/blob/master/numpy/linalg/umath_linalg.c.src#L1172
That's probably a day's work if you are familiar with how the above stuff works, multiplied by some number not necessarily of order 1 if you need to learn how to do it.

**Comment by ilayn** [comment]
(i) is known, (ii) unfortunately needs additions, (iii) is beyond my C-fu hence the question. But as far as I can see NumPy side doesn't have the interest and/or capacity to fix this so simply pinging these issues probably won't work.

**Comment by pv** [comment]
Well, I guess the issues you link to could also be solved with pure python.
I'm sure it's possible to get fixes merged by sending PRs to the numpy repository.

**Comment by pv** [comment]
https://github.com/numpy/numpy/pull/10571 comments welcome

**Comment by ilayn** [comment]
I couldn't make it to the review stage but thanks for addressing this @pv

**Comment by pv** [comment]
I guess the remaining thing would be adding `*gecon` et al. for 
approximative but faster computations. This would maybe need a new 
keyword, `cond(x, exact=False)`...
