### ISSUE TITLE
undefined/undesired sideeffects of optimize.root

### ISSUE THREAD

**Issue by Stomachion** [scipy/scipy#8415]
Executing the code below results in following Output:
....
x =  [ 5.00000005]
id x =  458960368       (id and value of the member m_x in the last call of func)

Cont_x =  [ 100.00000191]
after id x =  458960368        (id and value of the member m_x after root)

The id of m_x hasn't changed, so it should be still the same object. Apparently,  it's not. So, root manipulatied the member m_x afterwards?
I code with Python for only a few month now (several years in C/C++), so maybe I made an error I don't understand. But I don't think so since this "error" only occurs using the hybr or lm solver. With all the others (broyden, anderson...) it shows the expected behaviour (same id, same value).
 

### Reproducing code example:
class TC:

    def __init__(self, x):
        self.m_x = x

    def func(self, x):
        self.m_x = x
        print("     x = ", self.m_x)
        print(" id x = ", id(self.m_x))
        print()
        return self.m_x ** 2.0

    def find_zero(self):
        res = scipy.optimize.root(self.func, 10.0, tol=2., method='hybr')
        #  print("Res = ", res)
        print()
        print("Cont_x = ", self.m_x)
        print("after id x = ", id(self.m_x))

print()
ti = TC(200.0)
ti.find_zero()

### Scipy/Numpy/Python version information:
```
1.0.0 1.13.3 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

**Comment by andyfaff** [comment]
```
class TC:

    def __init__(self, x):
        self.m_x = x

    def func(self, x):
        self.m_x = x
        print("     x = ", self.m_x, type(self.m_x))
        print(" id x = ", id(self.m_x))
        print()
        return self.m_x ** 2.0


    def find_zero(self):
        res = scipy.optimize.root(self.func, 10.0, tol=2., method='hybr')
        #  print("Res = ", res)
        print()
        print("Cont_x = ", self.m_x, type(self.m_x))
        print("after id x = ", id(self.m_x))

ti = TC(200.0)
print(type(ti.m_x))
ti.find_zero()
```
```<class 'float'>
     x =  [10.] <class 'numpy.ndarray'>
 id x =  4633431616

     x =  [10.] <class 'numpy.ndarray'>
 id x =  4633430576

     x =  [10.] <class 'numpy.ndarray'>
 id x =  4633646544

     x =  [10.00000015] <class 'numpy.ndarray'>
 id x =  4633645344

     x =  [5.00000005] <class 'numpy.ndarray'>
 id x =  4633551616


Cont_x =  [100.00000191] <class 'numpy.ndarray'>
after id x =  4633551616
```

When the object is constructed it's a float. On subsequent calls the solver is providing a numpy array (all its internal workings are done with arrays). *Arrays are passed by reference*, so their contents can change even if their id doesn't.
