### ISSUE TITLE
some optimize.minimize methods modify the parameter vector in-place

### ISSUE THREAD

**Issue by brandondube** [scipy/scipy#8419]
Among them, L-BFGS-B, investigated below.

### Background

I am developing a nonlinear optimization based program.  This includes designing an effective cost function of orthogonal parameters.  I wish to be able to play back the optimization history, and use the callback to grab the parameter vector on each iteration.  I also scrape the function value from the disp option for L-BFGS-B.

### Data

A sample L-BFGS-B print output
```
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            4     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  2.75370D+01    |proj g|=  1.06893D+02

At iterate    1    f=  2.27149D+01    |proj g|=  1.76623D+02

At iterate    2    f=  1.20196D+01    |proj g|=  1.20733D+02

At iterate    3    f=  8.05081D+00    |proj g|=  8.74848D+01

At iterate    4    f=  5.00344D+00    |proj g|=  8.42253D+01

At iterate    5    f=  3.70940D+00    |proj g|=  1.01991D+02

At iterate    6    f=  1.57818D+00    |proj g|=  7.10948D+01

At iterate    7    f=  4.81956D-01    |proj g|=  3.76945D+01

At iterate    8    f=  6.81301D-02    |proj g|=  2.20645D+01

At iterate    9    f=  1.34639D-02    |proj g|=  8.79078D+00

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    4      9     12      1     0     0   8.791D+00   1.346D-02
  F =  1.346394518877836E-002

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH             

 Cauchy                time 0.000E+00 seconds.
 Subspace minimization time 0.000E+00 seconds.
 Line search           time 0.000E+00 seconds.

 Total User time 0.000E+00 seconds.
```
A callback:
```python
param_vectors = []
def callback(x):
    param_vectors.append(x)
```

Calling code:
```
guess = (0,0,0,0)
param_vectors.append(np.array(guess))
result = optimize.minimize(fun, guess, method='L-BFGS-B', options={'disp': True})
```
The value of param_vectors after optimization:
```python
[array([ 0.,  0.,  0.,  0.]),
  array([-0.00144057,  0.12278377, -0.00124594, -0.00264166]),
  array([-0.00144057,  0.12278377, -0.00124594, -0.00264166]),
  array([-0.00144057,  0.12278377, -0.00124594, -0.00264166]),
  array([-0.00144057,  0.12278377, -0.00124594, -0.00264166]),
  array([-0.00144057,  0.12278377, -0.00124594, -0.00264166]),
  array([-0.00144057,  0.12278377, -0.00124594, -0.00264166]),
  array([-0.00144057,  0.12278377, -0.00124594, -0.00264166]),
  array([-0.00144057,  0.12278377, -0.00124594, -0.00264166]),
  array([-0.00144057,  0.12278377, -0.00124594, -0.00264166])]
```
Note that all values except the first, which was manually added, are identical.

Parameter vector, function value pairs written to a logfile by the optimization function:
```
00. params = [ 0.  0.  0.  0.] 	 f(x) = 27.5369873872

01. params = [  1.00000000e-08   0.00000000e+00   0.00000000e+00   0.00000000e+00] 	 f(x) = 27.5369884562

02. params = [  0.00000000e+00   1.00000000e-08   0.00000000e+00   0.00000000e+00] 	 f(x) = 27.5369867324

03. params = [  0.00000000e+00   0.00000000e+00   1.00000000e-08   0.00000000e+00] 	 f(x) = 27.5369870096

04. params = [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e-08] 	 f(x) = 27.5369875808

05. params = [-0.80769268  0.49476373  0.28537275 -0.14630029] 	 f(x) = 86.4418490547

06. params = [-0.80769267  0.49476373  0.28537275 -0.14630029] 	 f(x) = 86.4418490135

07. params = [-0.80769268  0.49476374  0.28537275 -0.14630029] 	 f(x) = 86.441849366

08. params = [-0.80769268  0.49476373  0.28537276 -0.14630029] 	 f(x) = 86.4418499781

09. params = [-0.80769268  0.49476373  0.28537275 -0.14630028] 	 f(x) = 86.4418482602

10. params = [-0.16406864  0.1005026   0.05796848 -0.02971834] 	 f(x) = 22.714940612

11. params = [-0.16406863  0.1005026   0.05796848 -0.02971834] 	 f(x) = 22.7149388457

12. params = [-0.16406864  0.10050261  0.05796848 -0.02971834] 	 f(x) = 22.7149405671

13. params = [-0.16406864  0.1005026   0.05796849 -0.02971834] 	 f(x) = 22.7149404753

14. params = [-0.16406864  0.1005026   0.05796848 -0.02971833] 	 f(x) = 22.7149421094

15. params = [-0.10087717  0.09158391  0.05575493 -0.06632038] 	 f(x) = 12.0195875306

16. params = [-0.10087716  0.09158391  0.05575493 -0.06632038] 	 f(x) = 12.0195863232

17. params = [-0.10087717  0.09158392  0.05575493 -0.06632038] 	 f(x) = 12.0195878653

18. params = [-0.10087717  0.09158391  0.05575494 -0.06632038] 	 f(x) = 12.0195883001

19. params = [-0.10087717  0.09158391  0.05575493 -0.06632037] 	 f(x) = 12.0195867159

20. params = [ 0.15842029 -0.01548538 -0.01632799 -0.07159999] 	 f(x) = 48.7174210299

21. params = [ 0.1584203  -0.01548538 -0.01632799 -0.07159999] 	 f(x) = 48.7174233933

22. params = [ 0.15842029 -0.01548537 -0.01632799 -0.07159999] 	 f(x) = 48.717421743

23. params = [ 0.15842029 -0.01548538 -0.01632798 -0.07159999] 	 f(x) = 48.7174193993

24. params = [ 0.15842029 -0.01548538 -0.01632799 -0.07159998] 	 f(x) = 48.7174245544

25. params = [-0.05512618  0.07269238  0.04303647 -0.06725192] 	 f(x) = 8.05081234605

26. params = [-0.05512617  0.07269238  0.04303647 -0.06725192] 	 f(x) = 8.05081192026

27. params = [-0.05512618  0.07269239  0.04303647 -0.06725192] 	 f(x) = 8.0508114712

28. params = [-0.05512618  0.07269238  0.04303648 -0.06725192] 	 f(x) = 8.05081281076

29. params = [-0.05512618  0.07269238  0.04303647 -0.06725191] 	 f(x) = 8.05081206742

30. params = [-0.02149653  0.09172596  0.0267816  -0.06652566] 	 f(x) = 5.0034401551

31. params = [-0.02149652  0.09172596  0.0267816  -0.06652566] 	 f(x) = 5.00344002938

32. params = [-0.02149653  0.09172597  0.0267816  -0.06652566] 	 f(x) = 5.00343999403

33. params = [-0.02149653  0.09172596  0.02678161 -0.06652566] 	 f(x) = 5.00344079846

34. params = [-0.02149653  0.09172596  0.0267816  -0.06652565] 	 f(x) = 5.00343931285

35. params = [ 0.03012534  0.12108955 -0.01347029 -0.04719621] 	 f(x) = 3.70939759272

36. params = [ 0.03012535  0.12108955 -0.01347029 -0.04719621] 	 f(x) = 3.70939819132

37. params = [ 0.03012534  0.12108956 -0.01347029 -0.04719621] 	 f(x) = 3.70939842652

38. params = [ 0.03012534  0.12108955 -0.01347028 -0.04719621] 	 f(x) = 3.70939740919

39. params = [ 0.03012534  0.12108955 -0.01347029 -0.0471962 ] 	 f(x) = 3.70939657281

40. params = [ 0.00300894  0.11308784  0.00337076 -0.03858502] 	 f(x) = 1.57818376805

41. params = [ 0.00300895  0.11308784  0.00337076 -0.03858502] 	 f(x) = 1.578184007

42. params = [ 0.00300894  0.11308785  0.00337076 -0.03858502] 	 f(x) = 1.57818379941

43. params = [ 0.00300894  0.11308784  0.00337077 -0.03858502] 	 f(x) = 1.57818414645

44. params = [ 0.00300894  0.11308784  0.00337076 -0.03858501] 	 f(x) = 1.5781830571

45. params = [-0.01561316  0.12143126  0.00100096 -0.01330919] 	 f(x) = 0.481955650202

46. params = [-0.01561315  0.12143126  0.00100096 -0.01330919] 	 f(x) = 0.481955273258

47. params = [-0.01561316  0.12143127  0.00100096 -0.01330919] 	 f(x) = 0.481955840221

48. params = [-0.01561316  0.12143126  0.00100097 -0.01330919] 	 f(x) = 0.481955839908

49. params = [-0.01561316  0.12143126  0.00100096 -0.01330918] 	 f(x) = 0.481955373719

50. params = [-0.00041042  0.12401147 -0.00485423  0.00207093] 	 f(x) = 0.0681301442419

51. params = [-0.00041041  0.12401147 -0.00485423  0.00207093] 	 f(x) = 0.0681301690496

52. params = [-0.00041042  0.12401148 -0.00485423  0.00207093] 	 f(x) = 0.0681301089522

53. params = [-0.00041042  0.12401147 -0.00485422  0.00207093] 	 f(x) = 0.0681299235971

54. params = [-0.00041042  0.12401147 -0.00485423  0.00207094] 	 f(x) = 0.0681302701249

55. params = [-0.00144057  0.12278377 -0.00124594 -0.00264166] 	 f(x) = 0.0134639451888

56. params = [-0.00144056  0.12278377 -0.00124594 -0.00264166] 	 f(x) = 0.0134639411113

57. params = [-0.00144057  0.12278378 -0.00124594 -0.00264166] 	 f(x) = 0.0134638572809

58. params = [-0.00144057  0.12278377 -0.00124593 -0.00264166] 	 f(x) = 0.0134639506651

59. params = [-0.00144057  0.12278377 -0.00124594 -0.00264165] 	 f(x) = 0.0134639172132
```
Line 0 is the guess.  Lines 0-4 are a line search that proved not fruitfull.  Lines 5-09 are another failed line search.  Lines 10-14 are another line search, with line 14 corresponding to iterate 1 from L-BFGS-B output.  This pattern repeats for the rest of the output, down to line 59, the accepted value.

## A workaround

If the callback is modified to copy the array, the bug goes away
```
param_vectors = []
def callback(x):
    param_vectors.append(x.copy()))
```
This implies `x` is cast to an array, then fed to lbfgsb.f which modifies it in place.

## Potential fixes, work required

A potential bandaid to prevent this unexpected behavior would be to pass a copy of `x` to the callback inside scipy.  This has potential speed implications, but they should be very small compared to the cost of the cost function.  Numpy copying an array has a small overhead of a few microseconds for function calls, followed by the time to read and write `len(x)` doubles.  This is on the order of microseconds if not nanoseconds as well.

A check should be done on the behavior of all methods to see if they present this issue.  The ideal solution is to not have the optimizers mutate x, but this may be impossible with e.g. lbfgsb.f which is code written by a third party.

**Comment by brandondube** [comment]
This is bug 3/3 extracted from #8373

**Comment by brandondube** [comment]
This gist,
https://gist.github.com/brandondube/2c319727bbc794e97c0806a3abd213ba

has a context manager to redirect stdout for L-BFGS-B and a scraper function to extract cost function values from `disp`, which may be of some use here.

**Comment by andyfaff** [comment]
`guess` is converted to a numpy array [internally](https://github.com/scipy/scipy/blob/master/scipy/optimize/lbfgsb.py#L261), lets call it the best solution vector, [`x`](https://github.com/scipy/scipy/blob/master/scipy/optimize/lbfgsb.py#L309).
We have to do this because duck typing allows the function to accept lists, tuples, numpy arrays, etc. All that input needs to be converted to numpy arrays because it allows us to do maths on them, such as adding one to all values, or taking dot products, etc.
numpy arrays (and all Python containers) are passed by reference, so values in them can change, even if the object id doesn't. The values in `x` are modified by lbfgsb.f in place. This is why the values in successive objects in `param_vector` are modified.
Thus, when a function receives a container (list/array/dict) it might expect that it be subject to change in the future, and if it wants to  ensure no changes of its values, then it should make a copy.
The behaviour you wish to change might be being depended on by someone else, so I'm probably going to err on keeping the status quo.

**Comment by brandondube** [comment]
What is a scenario in which the user would want to use the callback to mutate `x` and redirect the optimizer?  That seems like a very error prone thing to do.

**Comment by andyfaff** [comment]
That may be one of the uses. For example, the user could also change the contents of args whilst the optimisation is underway, that may also change the direction.

**Comment by brandondube** [comment]
What is the relation between modifying x and args?

**Comment by andyfaff** [comment]
I was trying to indicate that the user can change any of `x`, `args`, and indeed the internals of `func` if they wish to redirect the optimizer in someway.

**Comment by brandondube** [comment]
Ok.  But if lbfgsb.f is mutating `x` internally, that is something the user has no prior warning about and can have severe side effects (such as washing away the parameter history).  Surely scipy could pass a copy of the parameter vector to lbfgsb.f to avoid it causing side effects?

**Comment by andyfaff** [comment]
> Ok. But if lbfgsb.f is mutating x internally, that is something the user has no prior warning about and can have severe side effects (such as washing away the parameter history)

Yes, all the values in the param_vectors can be modified as it's written. But your scenario should be picked up fairly quickly.

**Comment by brandondube** [comment]
I must be quite stupid then, to have not realized it was happening for two months.

**Comment by rkern** [comment]
Only some of the `minimize()` methods continue to mutate the parameter vector that it passes to the callback. `Nelder-Mead`, for instance, does not. There is no documentation in `fmin_l_bfgs_b()` that mentions anything about letting the callback feed back information by modifying the parameter vector. I have to conclude that the fact that it passes the parameter vector object that it continues to mutate is just an implementation detail and not an actual designed-for use case of the callback functionality.

**Comment by andyfaff** [comment]
Perhaps I provided a silly example.
I guess it boils down to who should be responsible for doing the copying.

**Comment by rkern** [comment]
I'm firmly of the view that it's the minimizers' responsibility. The primary use case of the `callback` is for monitoring, and recording by appending to a list is an obvious thing to do that should just work. There aren't significant performance disadvantages to always passing a copy (or at least, passing an array that won't be further mutated).

**Comment by josef-pkt** [comment]
IMO, returning a mutating array and mentioning this in the docstring is fine. In statsmodels we are just monitoring the optimization in some cases to check that we don't have an edge case that wouldn't converge, and the history is irrelevant. 
(Using a callback is expert usage, so users should understand the difference between a copy and an mutating intermediate result, at least that's what I assume in similar cases in statsmodels.)

**Comment by brandondube** [comment]
I disagree that passing a mutating array is fine.  It defies the goal of unifying the solvers under minimize (this behavior is nonuniform among them) and can trip a user, who has no reason to anticipate this behavior.

**Comment by rkern** [comment]
If there were a sizable performance degradation or somesuch for the minimizer to ensure a copy, I'd be okay with just documenting it, but there isn't. There's no good reason to deliberately keep things the way they are. Someone just needs to make the PR to do it. @brandondube If you're up for it, please proceed.

**Comment by rgommers** [comment]
FWIW, I agree with @brandondube and @rkern here. Helping users not shoot themselves in the foot and harmonizing things between the different minimizers seems like the way to go.
