### ISSUE TITLE
Missing numpy import in scipy.signal.spectrogram doc

### ISSUE THREAD

**Issue by jdespraz** [scipy/scipy#8434]
Hello,

Not sure if this is the correct place to report this but I realized there is a little error in the documentation associated with the scipy.signal.spectrogram documentation, url:
https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.signal.spectrogram.html
as well as in the downloadable script:
https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy-signal-spectrogram-1.py

In both examples the line `import numpy as np` is missing.

Thanks!

**Comment by pv** [comment]
By convention:
https://docs.scipy.org/doc/scipy-1.0.0/reference/tutorial/general.html

**Comment by jdespraz** [comment]
Alright thanks!
I guess I'll close this issue then.
