### ISSUE TITLE
scipy.integrate.solve_ip() gives divide by zero runtimewarning with trivial ODE

### ISSUE THREAD

**Issue by dmlorenzetti** [scipy/scipy#8438]
Asking `solve_ip()` to solve the trivial ODE dy/dt = 0 produces a "divide by zero" warning.

The warning seems to come from an error estimation step, and does not seem to affect the quality of the computed solution.

### Reproducing code example:

Here is some *working* code, taken almost exactly from the documentation page (https://scipy.github.io/devdocs/generated/scipy.integrate.solve_ivp.html):

```
from scipy.integrate import solve_ivp
def exponential_decay(t, y): return -0.5 * y
sol = solve_ivp(exponential_decay, [0, 10], [1])
```

Now change the decay rate to 0:

```
def exponential_decay(t, y): return 0.0 * y
sol = solve_ivp(exponential_decay, [0, 10], [1])
```

This sets the derivative to a constant value 0 (multiplying by `y` just gives the result the expected array-like structure).  Therefore the solution should be trivial -- the state variable should stay fixed at 1.  And in fact it does so, if you inspect `sol.y`.

However, the solver also gives a runtime warning:

```
/usr/local/lib/python3.6/site-packages/scipy/integrate/_ivp/rk.py:145: RuntimeWarning: divide by zero encountered in double_scalars
  max(1, SAFETY * error_norm ** (-1 / (order + 1))))
```

Similarly, running with the BDF solver:

```
def exponential_decay(t, y): return 0.0 * y
sol = solve_ivp(exponential_decay, [0, 10], [1], method='BDF')

/usr/local/lib/python3.6/site-packages/scipy/integrate/_ivp/bdf.py:417: RuntimeWarning: divide by zero encountered in power
  factors = error_norms ** (-1 / np.arange(order, order + 3))
```

### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)

1.0.0 1.14.0 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
Thanks for reporting the problem.  This issue was also reported in December (https://github.com/scipy/scipy/issues/8238) and has already been fixed (https://github.com/scipy/scipy/pull/8239).

**Comment by dmlorenzetti** [comment]
Thank you.

Filling out the issue report made me realize I don't have the latest
`scipy`.  That surprised me since I do `pip3 list -o` once a week, and
always keep things updated.  Obviously the upgrade path isn't as
straightforward as I had assumed.  But that is my problem to deal with.

-Dave

**Comment by WarrenWeckesser** [comment]
According to the information that you provided above, you have version 1.0.0.  That is the latest released version.  There hasn't yet been a release that includes the fix for this issue.

**Comment by dmlorenzetti** [comment]
Thanks!  Good to know.

Many thanks for: (1) your fast response on all this; and (2) the excellent,
excellent tools made available in scipy.

-Dave
