### ISSUE TITLE
Deprecate `hyp2f0`, `hyp1f2`, and `hyp3f0`?

### ISSUE THREAD

**Issue by person142** [scipy/scipy#8443]
The functions `special.hyp2f0`, `special.hyp1f2`, and `special.hyp3f0` come from Cephes. As far as I can tell they were originally intended to be internal helper routines for computing the confluent hypergeometric function of the second kind and Struve functions. As such, their implementations are incomplete; for example `hyp2f0` only contains an asymptotic expansion. It looks like they were included in `special` essentially by accident.

These functions come up occasionally ([wiki](https://en.wikipedia.org/wiki/Generalized_hypergeometric_function) page), but probably not enough that it's actually important to have them in `special`. I doubt anyone will ever feel inspired to complete their implementations. Seeing as there are already enough problem functions in `special`, I think we should just cut them loose. Thoughts?

**Note**: I am *not* proposing that we deprecate the important and frequently used `hyp0f1`, `hyperu`, `hyp1f1`, and `hyp2f1`.

**Comment by rgommers** [comment]
Sounds reasonable to me. Propose it on the mailing list as well please, that's where we should put all deprecations up for discussion.

**Comment by pv** [comment]
Ok with me. We should ideally not ship routines that are not useful. At
minimum known deficiencies would need to be stated in the
documentation, but if it's only asymptotic expansion in some regimes,
then it may as well be best to remove them.

**Comment by rainwoodman** [comment]
My collaborator just figured the result of  hyp1f2 and diverges. We do want to use hyp1f2 -- any recommendation on where to find a useable implementation?

**Comment by vhaasteren** [comment]
And then scientists come here to find out why the function they rely on has been removed from scipy, only to find that there is not really an alternative.

I understand the reasoning stated above, but without another way to calculate this function I feel like this was a wrong decision

**Comment by vhaasteren** [comment]
If anyone is every interested, I packaged two of the deprecated functions that I needed here:

https://github.com/vhaasteren/scipydepr
