### ISSUE TITLE
Idea: Add routine for simultaneous diagonalization of matrices

### ISSUE THREAD

**Issue by kevinsung** [scipy/scipy#8445]
I think it would be nice to have in `scipy.linalg` a routine that takes in two commuting normal matrices `A` and `B` and outputs a unitary matrix `U` that simultaneously diagonalizes them. I can't find such a function in Scipy and it looks like this issue has never been raised even though this is an important numerical procedure.

Is this a reasonable thing to contribute to Scipy?

**Comment by czgdp1807** [comment]
I think your idea is good but it has a limitation since the routines will work only when matrices A and B commute. So, the routines should have that feature before being included in scipy.linalg

**Comment by kevinsung** [comment]
I think the routine should check that `A` and `B` are normal and commute, and otherwise raise an error. Do you think that's okay?

**Comment by czgdp1807** [comment]
Yes, that would surely work. By the way, I would appreciate your observation regarding this missing routine.

**Comment by ilayn** [comment]
This has a rather specialized use case. For the generic use QZ and ordered QZ is available.

Do you have any examples elsewhere for this?

**Comment by kevinsung** [comment]
My motivation comes from quantum mechanics, where A and B would be observables which also commute with the Hamiltonian. Often, when we do a quantum simulation, we want the starting state to be a simultaneous eigenvector of A and B with specified eigenvalues, which we could use this routine to compute.

**Comment by ilayn** [comment]
What I meant is that numerically this is a necessarily fragile function (commutativity tolerance and so on) and I don't know any software actually implements this, on the other hand I know a lot of numerical computing articles investigating this problem with hermitian case. 

As far as I know, (which is not an expert opinion), the results are not fully satisfactory yet to be included in a package and the jury is still out. I think QuTiP is a natural place to have this so I would suggest making a business case there.

**Comment by kevinsung** [comment]
Ah, I see what you mean. The main reason I brought it up here is that I want a function that does not have any dependencies outside of Numpy/Scipy. I have not looked too deeply into the numerical implementation; I will need to think more about that.

**Comment by ilayn** [comment]
I'm closing this one before it slides back to ether but feel free to address this if you would like to discuss further
