### ISSUE TITLE
SciPy-dev Mailing List request not being accepted 

### ISSUE THREAD

**Issue by czgdp1807** [scipy/scipy#8449]
I want to participate in GSoC 2018. My dream organization is SciPy. I have a new idea and I want to share it with the mentors. For the same, I have sent a request to become a member of SciPy-dev community. It has not been accepted and more than two days have been passed. Please help me out as soon as possible.

**Comment by pv** [comment]
There's no manual filtering of the mailing list subscriptions, all 
requests are automatically accepted. However, check that you used the 
correct subscription form:
https://mail.python.org/mailman/listinfo/scipy-dev

**Comment by czgdp1807** [comment]
Yes I have used the same form as given in the link. I have not received any confirmation mail from the SciPy-dev community.

**Comment by pv** [comment]
Can you try again now?

**Comment by czgdp1807** [comment]
I have sent another request, using the email-id as "gdp.1807@gmail.com" and name as "Gagandeep Singh". I have used the same credentials earlier, hoping that it doesn't creates a problem.

**Comment by pv** [comment]
Be sure to check your spam folder and in case problems continue, read 
the advice here: https://mail.python.org/mailman/listinfo  The lists are 
managed by python.org, and we cannot help you directly with using them.

**Comment by czgdp1807** [comment]
It worked and I have been subscribed to the SciPy-dev mailing list. Thank you for your help.
