### ISSUE TITLE
ARPACK tutorial has two conflicting equations

### ISSUE THREAD

**Issue by hameerabbasi** [scipy/scipy#8452]
The [ARPACK tutorial](https://docs.scipy.org/doc/scipy/reference/tutorial/arpack.html) has two conflicting equations. At one place there is `\nu = \frac{1}{\lambda - \sigma}` (in the section [Shift-Invert Mode](https://docs.scipy.org/doc/scipy/reference/tutorial/arpack.html#shift-invert-mode)) and at another place, there is `\nu = 1 / (\sigma - \lambda)` (in the [examples](https://docs.scipy.org/doc/scipy/reference/tutorial/arpack.html#examples), just before the second-to-last example).

This is an inconsistency. The documentation doesn't give references to literature for this, so I don't know which is the correct one here.

**Comment by pv** [comment]
The ARPACK user guide may give the correct definition (I guess 
1/(lambda-sigma) makes more sense).

**Comment by leotrs** [comment]
Please see https://github.com/scipy/scipy/pull/9356

**Comment by hameerabbasi** [comment]
Fixed by #9356?

**Comment by ilayn** [comment]
Yes, it was merged into another issue so github got confused, closing.
