### ISSUE TITLE
Precision of the p-value in stats.kendalltau() for small n and the tails + suggestion

### ISSUE THREAD

**Issue by Konrad0** [scipy/scipy#8456]
Hi all,

since stats.kendalltau() uses a normal approximation to calculate p-values, it comes as no surprise that the precision for small n and the outer tails is rather limited. A couple of examples for very small n (n=5) and moderate n (n=15), the latter in the extreme case of full correlation: 

### Reproducing code example 1:
```
from scipy import stats
n = 5
x = list(range(n))
y = [3,2,0,4,1]
stats.kendalltau(x, y)
```

### Output:
```
KendalltauResult(correlation=-0.19999999999999998, pvalue=0.624206114766406)
```
Using R (cor.test(x, y, method="kendall", exact=1)) we can find the correct p-value: 0.8167.

### Reproducing code example 2:
```
from scipy import stats
n = 15
x = list(range(n))
y = list(range(n))
stats.kendalltau(x, y)
```

### Output:
```
KendalltauResult(correlation=1.0, pvalue=2.034554614544436e-07)
```
Again using R we find the correct p-value: 1.529e-12.

For the simple case of no ties, the p-values can be computed exactly (see Maurice G. Kendall, "Rank Correlation Methods" (4th Edition), Charles Griffin & Co., 1970.), but this method is slow (O(n*c) where c is the number of concordances/discordances, worst case O(n**3)). Nonetheless I wanted to suggest it as an option for small n (R uses it for n<50) and cases with very few concordances/discordances. Please find below a suggestion that could be called from stats.kendalltau() to calculate the (one-sided) p-values and let me know if you think this would be a useful addition, then I'd work it out properly and test it.

### Suggestion:
```
from math import factorial
#from math import gamma
def kendallp(n, c):
    if n <= 0:
        raise ValueError
    elif c < 0 or 2*c > n*(n-1):
        raise ValueError
    elif n == 1:
        return 1.0
    elif n == 2:
        return 0.5
    elif c == 0:
        return 1.0/factorial(n)
        #return 1.0/gamma(n+1)
    elif 2*c == n*(n-1):
        return 1.0
    elif c == 1:
        return 1.0/(factorial(n-1))
        #return 1.0/(gamma(n))
    
    flip = False
    if 4*c > n*(n-1):
        flip = True
        c = int(n*(n-1)/2 - c - 1)
    if c == 0:
        return 1.0 - 1.0/(factorial(n))
        #return 1.0 - 1.0/(gamma(n+1))
    old = [0.0]*(c+1)
    new = [0.0]*(c+1)
    new[0] = 1.0
    new[1] = 1.0
    for j in range(3,n+1):
        old = new[:]
        for k in range(1,min(j,c+1)):
            new[k] += new[k-1]
        for k in range(j,c+1):
            new[k] += new[k-1] - old[k-j]
    return 1.0 - sum(new)/factorial(n) if flip else sum(new)/factorial(n)
    #return 1.0 - sum(new)/gamma(n+1) if flip else sum(new)/gamma(n+1)
```

### Scipy version information:
```
1.0.0
```

**Comment by chrisb83** [comment]
I think it is a good idea to use the exact distribution for small samples. In any case, the documentation should mention that how the p-value is computed (one can only see it in the source code right now), potentially even display a warning if n is small (?).

**Comment by Konrad0** [comment]
I agree that the precision issues should definitely be mentioned in the documentation, but this is a bit more complicated than just advising against using the method for low n. Even at moderately large orders the p-values are off: for n=100 and full correlation (as in example 2 above), our scipy routine computes 3.48e-49, while the correct p-value is 2.14e-158. (Of course both numbers are probably below any confidence limit used in real life.)
Even for large n, the normal approximation only works reasonably well around the center of the distribution, but I don't know how to quantify this behavior. Anyway, for 0 or 1 concordances/discordances the issue can be circumvented since the exact p-value is computed by just one factorial, but for more concordances/discordances I'm not sure how to implement a feasible, precise solution for large n.

**Comment by josef-pkt** [comment]
I think it's good to add the exact option, but IMO we should keep the current asymptotic p-values as the default. One of the main reason is that often we (e.g. pandas) are only interested in the correlation coefficient itself, and costly p-value computation would just be a waste of time.
(Also, because it's only for the no-tie case, it is not possible to only condition on the number of observations.)

The "inaccuracy" of p-values is a similar problem for all hypothesis tests. and usually it only makes sense to **interpret** them at low precision. i.e. whether a p-value is 0.9 or 0.95 or is 1e-20 or 2e-100 shouldn't make any practical difference.

(It's still important to get good p-values especially for small sample. I never looked at the details for this case, but for proportions there are a large number of methods all with different advantages or disadvantages. e.g. Fisher exact can be very conservative, and is not recommended by most statisticians based on the references that I read.)

**Comment by Konrad0** [comment]
I like the idea of introducing an optional flag "exact". My suggestion would be this: if the flag is given as True, the exact calculation is performed, if it is given as False, the approximation is computed, and if the flag is not given, it defaults to None and the exact p-value is calculated only if n is very small or there are <=1 concordances/discordances. Regarding your efficiency considerations one could also introduce a flag that prevents the p-value calculation altogether.
(Btw. of course the numbers given in my last example do not have of any practical meaning, I was merely exemplifying the numerical precision. As you correctly point out, the interpretation of such tests does not depend on the last digit of the p-value. This is quite similar to the rather pointless argument that there is no evidence for a measured effect if it has a significance of 2.99 sigma, but the result is significant as soon as it reaches the 3 sigma threshold...)

**Comment by josef-pkt** [comment]
@Konrad0   Do you know if there are other possible ways to compute the p-value?

The question is whether to use a "trivariate boolean" `exact` or an open ended `method` keyword.
(As I mentioned, I needed to add several `method` choices for proportion p-values,in statsmodels. Boolean keywords have a tendency to become a restriction for future changes under backwards compatibility considerations.)

> introduce a flag that prevents the p-value calculation altogether.

returning a variable number of returns is not a good design and, AFAIK, is only used if there is a large advantage to it, which, I think, is not the case with asymptotic p-values.

**Comment by Konrad0** [comment]
Well, I'm not aware of any other methods to compute these p-values, but that doesn't mean they don't exist ;-)
So if there are no major disadvantages I have overlooked, maybe we should go with the `method` keyword you suggested, just to be safe for possible future improvements.

**Comment by Konrad0** [comment]
Hi,
as you can see above, I've created a pull request. The documentation still needs to be updated, but I wanted to give you all a chance to review the code already. The exact method is now available in the stats and stats.mstats modules. If you have any suggestion, just let me know!
BTW one test fails on my machine, but it's not due to the Kendall test (scipy/linalg/tests/test_basic.py:790: AssertionError).

**Comment by rgommers** [comment]
seems all resolved now, closing. thanks all
