### ISSUE TITLE
scipy.interpolate.CubicSpline.integrate: documentation incomplete

### ISSUE THREAD

**Issue by Dagda47** [scipy/scipy#8459]
scipy.interpolate.CubicSpline.integrate requires the following as stated in the code:
` def integrate(self, a, b, extrapolate=None):`

In the documentation however (https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.CubicSpline.integrate.html) the piecewise polynomial isn't requested or rather there isn't the possibility to input the piecewise polynomial:
`CubicSpline.integrate(a, b, extrapolate=None)`

**Comment by pv** [comment]
See https://www.programiz.com/article/python-self-why
