### ISSUE TITLE
gaussian_kde has no rvs() method

### ISSUE THREAD

**Issue by angellandros** [scipy/scipy#8466]
The distributions `scipy.stats.gaussian_kde` has no `rvs` method, hence cannot be used in many different circumstances, _e.g._ `sklearn.model_selection.RandomizedSearchCV`.

I have implemented the `rvs` function BTW, and wanted to know if you would like me to add it.

**Comment by josef-pkt** [comment]
It's call `resample`, gaussian_kde does not follow the same pattern as the parametric distributions
https://github.com/scipy/scipy/blob/master/scipy/stats/kde.py#L399
