### ISSUE TITLE
scipy.integrate.quad()

### ISSUE THREAD

**Issue by czgdp1807** [scipy/scipy#8478]
In scipy.integrate.quad(), the problem is it returns the error with value of the definite integral. I think the error is unimportant to report, since, the value returned by the method is itself an approximation and reporting error in that is redundant.
For example the following code,

import scipy.integrate, numpy
f=lamda x:numpy.sin(x)
print(scipy.integrate.quad(f,0,2*numpy.pi)

, gives the following output,
(2.221501482512777e-16, 4.3998892617845996e-14)

Here, the absolute error reported is higher than the value. It questions the reporting of error with approximated value.

**Comment by pv** [comment]
The estimated error is sometimes important to know. Moreover, the  current behavior cannot be changed, to preserve backward compatibility.

The error estimate in the example you give also looks competely correct, in view of the numerical problem being solved.

**Comment by WarrenWeckesser** [comment]
>  I think the error is unimportant to report, since, the value returned by the method is itself an approximation and reporting error in that is redundant.

I don't understand that comment.  The error estimate is important precisely because the integral is an approximation.  The error estimate lets you know had good or bad the approximation is.
