### ISSUE TITLE
freqz() output for fifth order butterworth bandpass  (low cut off frequencies, high sampling rate) 

### ISSUE THREAD

**Issue by abdelwahed** [scipy/scipy#8485]
![butterworth_order_5](https://user-images.githubusercontent.com/971634/36656313-e6f34556-1b1b-11e8-8aab-a0eb71e1fe82.png)

I am using a slightly modified code form [scipy-cookbook here](http://scipy-cookbook.readthedocs.io/items/ButterworthBandpass.html). The parameters are the default ones in the code below (fs = 200,lowcut = 1.0,highcut = 2.0) . I am wondering if the "order-5" curve is correct?!

### Reproducing code example:
```
from scipy.signal import butter, lfilter

def butter_bandpass(lowcut, highcut, fs, order=5):
    nyq = 0.5 * fs
    low = lowcut / nyq
    high = highcut / nyq
    b, a = butter(order, [low, high], btype='band')
    return b, a


def butter_bandpass_filter(data, lowcut, highcut, fs, order=5):
    b, a = butter_bandpass(lowcut, highcut, fs, order=order)
    y = lfilter(b, a, data)
    return y

def get_freqz(fs = 200,lowcut = 1.0,highcut = 2.0, order = [1,2,3,4,5]):
    import numpy as np
    import matplotlib.pyplot as plt
    from scipy.signal import freqz,freqs
    plt.style.use('bmh')

    plt.figure(figsize=(4,4),dpi = 150)
    
    for o in order:
        b, a = butter_bandpass(lowcut, highcut, fs, order=o)
        w, h = freqz(b, a, worN=2000)
   
        plt.plot((fs * 0.5 / np.pi) * w, abs(h), linewidth=1,label="order = %d" % o)
        plt.xlim((0,3))

        plt.xlabel('Frequency (Hz)')
        plt.ylabel('Gain')
        plt.legend(loc='best')
        
    plt.show()


    
get_freqz()   
```

### Scipy/Numpy/Python version information:
```

scipy.__version__ = '0.19.1'
numpy.__version__ = '1.13.1'
sys.version_info = sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0)
```

**Comment by larsoner** [comment]
Yes it might actually be correct, `b, a` / TF representations of high order IIR filters can be unstable. Can you check if the second-order sections representation gives you what you'd expect?

**Comment by WarrenWeckesser** [comment]
Well, I wouldn't call it *correct*.   For those parameter values, `butter` appears to produce an unstable filter.  But that is because of floating point numerical errors that occurs in scipy's implementation; it is not a "correct" filter.  If the filter was implemented with much higher precision floating point values, e.g. with`mpmath`, the frequency response would work as expected, even using the transfer function representation.

In this case, @larsoner's suggestion to use the SOS format is a good one.  It is less susceptible to numerical errors.

Here's a variation of your script.  I modified it to use the SOS format for the filters (along with a few other tweaks):

```
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import butter, sosfilt, sosfreqz


def butter_bandpass(lowcut, highcut, fs, order=5):
    nyq = 0.5 * fs
    low = lowcut / nyq
    high = highcut / nyq
    sos = butter(order, [low, high], btype='band', output='sos')
    return sos


def butter_bandpass_filter(data, lowcut, highcut, fs, order=5):
    sos = butter_bandpass(lowcut, highcut, fs, order=order)
    y = sosfilt(b, a, data)
    return y


def get_freqz(fs=200, lowcut=1.0, highcut=2.0, order=[1, 2, 3, 4, 5]):
    plt.style.use('bmh')
    plt.figure(figsize=(4, 4), dpi=150)
    
    for o in order:
        sos = butter_bandpass(lowcut, highcut, fs, order=o)
        w, h = sosfreqz(sos, worN=5000)
   
        plt.plot((fs * 0.5 / np.pi) * w, abs(h),
                 linewidth=1,
                 label="order = %d" % o)
        plt.xlim((0, 3))
        plt.xlabel('Frequency (Hz)')
        plt.ylabel('Gain')
        plt.legend(loc='best')
        
    plt.axhline(np.sqrt(2)/2,
                linestyle='--', linewidth=1, color='k', alpha=0.5)
    plt.show()

 
get_freqz()   
```

Here's the plot that it generates:
![figure_1](https://user-images.githubusercontent.com/321463/36698018-be6e911c-1b16-11e8-8025-e5d5e62bae21.png)

**Comment by larsoner** [comment]
@abdelwahed okay to close? Or is there somewhere we could have warned about this limitation of `b, a` representations that would have helped?

**Comment by abdelwahed** [comment]
@WarrenWeckesser  Thanks for your updating the code/methodology . 
@larsoner a warning about this limitation would really help (what could be general rule for issuing this warning ? ). I investigated into freqz() output visually only after I observed that filtering results doesn't seem to be correct.

**Comment by larsoner** [comment]
> what could be general rule for issuing this warning ?

We could try to inspect the outputs to see if they are reasonable, but we might still miss some cases. I'm more thinking that maybe a documentation update to the `Notes` or the `output` keyword argument would be appropriate. Would something like this have helped?

```
.. warning:: Designing high-order IIR filters in TF form can result in unstable
    or incorrect filtering due to numerical precision issues. Consider inspecting
    output filter characteristics `freqz` or designing the filters with second-order
    sections via ``output='sos'``.
```
We might want to add something like this to our IIR design functions. It might even be common enough a problem to add a Sphinx directive to take care of it :)

**Comment by u55** [comment]
In the warning, can we be more precise about what constitutes "high-order"? I would have naively not expected 5th-order to be considered high. Is anything larger than second-order considered numerically unstable?

**Comment by WarrenWeckesser** [comment]
@u55: That's a great idea.  Unfortunately, the numerical sensitivity depends on the width of the passband of the requested filter.   A filter with order 9 and a wide passband might have no problems, while one with order 5 and a very narrow passband (like the one in this issue) might result in instability.

**Comment by musteng** [comment]
Is it possible that I can work on this issue and open a PR?

**Comment by larsoner** [comment]
Sure, a documentation update here would be good!

**Comment by musteng** [comment]
Thank you for reply. Could I start to work on this from now on?

**Comment by melissawm** [comment]
@musteng feel free - please check out our [contributing guide](https://docs.scipy.org/doc/scipy/dev/contributor/contributor_toc.html) and feel free to reach out if you have questions 😄

**Comment by musteng** [comment]
Thank you so much @melissawm, I think I should open a pull request and link this issue and work 😁. If anything comes up I will reach out!

**Comment by melissawm** [comment]
@musteng I believe the suggestion above was to add this comment to the docstring of the [butter function](https://scipy.github.io/devdocs/reference/generated/scipy.signal.butter.html). This is defined here: https://github.com/scipy/scipy/blob/e6c27e50f3f98a68768291af274d783749ffdf15/scipy/signal/_filter_design.py#L2980
