### ISSUE TITLE
[Bug] '_<...> LinearOperator' object has no attribute '_transpose'

### ISSUE THREAD

**Issue by homocomputeris** [scipy/scipy#8486]
As far as I understand, `sparse.LinearOperator` creates some instance of `CustomLinearOperator` when it is called by `aslinearoperator()` or when passed `matvec=`.
But neither `CustomLinearOperator`, nor, e.g., `SumLinearOperator` have `transpose()`.

And the [docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.LinearOperator.html) do not say much about how `transpose()` should be used or implemented.

### Reproducing code example:
```
import numpy as np
import scipy as sp
import scipy.sparse.linalg as sla


dim = 8
shp = (dim, dim)

I = np.eye(*shp)

x0 = -sp.pi
xf = sp.pi
x = np.linspace(x0, xf, dim, endpoint=False)
# this is a vector representation of an operator with diagonal matrix
ref = (1-np.exp(-x))**2


def mv(y):
    # multiply this diag matrix by vector
    vv = ref
    return vv*y


LO = sla.LinearOperator(shp, matvec=mv)
(LO+LO).T

# not ever if a matrix was passed
M = sla.aslinearoperator(I)
M.transpose()
```

### Error message:
```
'_CustomLinearOperator' object has no attribute '_transpose'
```

### Scipy/Numpy/Python version information:
```
1.0.0 1.14.0 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
```

**Comment by Tokixix** [comment]
@ilayn I have an idea to create a _transpose method behaving in the following way: Having some Linop, we can multiply it by Identity Matrix to have its matrix representation and then we can just return MatrixLinearOperator on the transposition of this matrix. Is it okay, or do You think it should be done differently?
