### ISSUE TITLE
scipy.special.hermitenorm doc issue

### ISSUE THREAD

**Issue by Blasche** [scipy/scipy#8487]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
Hi,
I believe in https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.special.hermitenorm.html the weigh function is exp(-x**2 /2).
Regards
Christian

**Comment by pv** [comment]
It's correct in current documentation: https://docs.scipy.org/doc/scipy
/reference/generated/scipy.special.hermitenorm.html

**Comment by Blasche** [comment]
Any reference to prove it?

**Comment by pv** [comment]
Note that you are not reading the current version of the documentation, but something from many years ago.

**Comment by Blasche** [comment]
All right - my bad. Thanks
