### ISSUE TITLE
Missing documentation for `brute_force` parameter in scipy.ndimage.morphology

### ISSUE THREAD

**Issue by jhlegarreta** [scipy/scipy#8492]
Documentation is missing for the `brute_force` parameter in the math morphology methods available in Scipy:
- [binary_dilation](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.ndimage.morphology.binary_dilation.html)
- [binary_erosion](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.ndimage.morphology.binary_erosion.html)

This includes the internal methods in the [morphology.py](https://github.com/scipy/scipy/blob/master/scipy/ndimage/morphology.py) file.

### Reproducing code example:
Not applicable.

### Error message:
Not applicable.

### Scipy/Numpy/Python version information:
```
1.0.0 1.14.0 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
```

I've been looking at the code but could not find a feasible explanation for the parameter. **If you post here its meaning I can submit a PR to add the missing documentation.**

**Comment by ilayn** [comment]
Seems to me like a flag to control the recursion but I don't know why it is exposed in the public API.

**Comment by jaimefrio** [comment]
Both erosion and dilation can be run repeatedly until there is no change in the image. The default behaviour (`brute_force=False`) keeps track of what points changed in the last iteration, and chooses which pixels it should try to erode or dilate in some clever fashion based on that. If you set `brute_force=True`, it tries to erode or dilate every pixel of the image in every iteration, regardless of what happened in the previous one.

**Comment by jhlegarreta** [comment]
OK @jaimefrio . Thanks, I'll submit a PR with this, then we'll refine the docstring.

**Comment by jaimefrio** [comment]
That'd be great!

**Comment by jhlegarreta** [comment]
Although I submitted a PR, I had a closer look at the algorithm, and IMHO other conditions also apply (e.g. whether the center of the structuring element is true), and thus may be further explanations are required?. Also, from its description, one can think that the `brute_force` condition clashes with the `iterations` being `<1`.

But if things are to be kept simple, I think the PR is enough.
