### ISSUE TITLE
[Improvement] Allow parameters in solve_ivp

### ISSUE THREAD

**Issue by mileslucas** [scipy/scipy#8494]
I am curious why `solve_ivp` does not support argument passing to the passed function. A lot of the other solvers in scipy allow parameter passing like in `minimize`, for instance. 

### Code Example
I have a system of differential equations described with a factor that changes one of the parameters:
```
def helium_usage(t, y, f=1):
    X4, X12, X16, X20 = y
    
    rho = 1e4
    T9 = 0.15
    Na2_3a = 1.48e-18
    Na_a12 = 3.03e-17 * f
    Na_a16 = 1.05e-22
    
    dX4 =  -rho**2 / 32 * Na2_3a * X4**3 - rho / 12 * Na_a12 * X4 * X12 - rho / 16 * Na_a16 * X4 * X16
    dX12 = rho**2 / 32 * Na2_3a * X4**3 - rho / 4 * Na_a12 * X4 * X12
    dX16 = rho / 3 * Na_a12 * X4 * X12 - rho / 4 * Na_a16 * X4 * X16
    dX20 = 5 * rho / 16 * Na_a16 * X4 * X16
    
    # Convert from seconds to years
    time_conversion = 60 * 60 * 24 * 365 
    return np.multiply([dX4, dX12, dX16, dX20], time_conversion)
```
I want to be able to run `solve_ivp` in a way like:
```
results = [solve_ivp(helium_usage, params={'f':fi}, t_span=(1, 1e6), y0=(1, 0, 0, 0))  for fi in [1, 1.3, 2]]
```
### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
1.0.0 1.12.1 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
Use lambda, that is the intended way that works everywhere.

**Comment by WarrenWeckesser** [comment]
The `args` argument has always seemed intuitive to me, so I've never understood why some people think it is "not Pythonic".  It doesn't require the user to wrap their function in another callable, which makes code simpler.  From my experience teaching Python, beginners have no trouble grasping the `args` argument, so it certainly isn't an API that is too complicated or confusing.    I suspect I'm in the minority among the SciPy developers, but I'm in favor of the `args` argument.  Having said that, this comment is probably about as much effort as I'll put into the battle for it, so if most of the SciPy developers don't like it, so be it.

**Comment by mileslucas** [comment]
Lambda is not producing intended results, then.

### Code
Define a function that, given a list of functions, performs the solving and plots relevant part of output
```
def calc_and_plot(sigs):
    span = (1, 1e7)
    t = np.linspace(*span, 100)
    results = [solve_ivp(sig, t_span=span, y0=(1, 0, 0, 0), t_eval=t) for sig in sigs]
    cycle = (cycler('color', ['k']) * cycler('linestyle', ['-', '-.', ':', '--']))
    plt.gca().set_prop_cycle(cycle)
    for res, val in zip(results, perc):
        plt.semilogx(res.t, res.y[2], 'k', label=f'f={val}')

    plt.grid()
    plt.title('Carbon generation')
    plt.xlabel('t (yr)')
    plt.ylabel('$\chi_{12}$')
    plt.legend()
```
Then, define two lists using different methods
```
perc = [1.0, 1.3, 0.7]
def sig1(t, y):
    return helium_usage(t, y, perc[0])
def sig2(t, y):
    return helium_usage(t, y, perc[1])
def sig3(t, y):
    return helium_usage(t, y, perc[2])

sigs1 = [sig1, sig2, sig3]   
# Using Lambda
sigs2 = [lambda t,y: helium_usage(t, y, fi) for fi in perc]
```
And here is the relevant output:
```
calc_and_plot(sigs1)
```
![sigs1](https://user-images.githubusercontent.com/14099459/36761279-ee825352-1be3-11e8-98d6-407d62147f13.png)

```
calc_and_plot(sigs2)
```
![sigs2](https://user-images.githubusercontent.com/14099459/36761281-f2510b40-1be3-11e8-90da-9c168de5cf79.png)
