### ISSUE TITLE
Query Regarding threshold variable in clarkson_woodruff_transform

### ISSUE THREAD

**Issue by kdhingra307** [scipy/scipy#8498]
Abstract:
There is a threshold variable 0.1 in the clarkson_woodruff_transform demo and in the documentation, which according to my overall understanding should not be there because it has never been used in the calculations as such.

Details:
I found clarkson_woodruff_transform through GSOC18 and started going through the research paper as well as the code present in the scipy.
There was a threshold variable, which confused me because we are setting threshold and sketch_size on our own(it's because the sense in which threshold is mentioned is confusing). Because According to my understanding of the whole algorithm, threshold depends on sketch_size and no relation has been calculated for those.

 ```
from scipy import linalg
 n_rows, n_columns, sketch_n_rows = (2000, 100, 100)
 threshold = 0.1
 tmp = np.random.normal(0, 0.1, n_rows*n_columns)
A = np.reshape(tmp, (n_rows, n_columns))
sketch = linalg.clarkson_woodruff_transform(A, sketch_n_rows)
sketch.shape
(100, 100)
normA = linalg.norm(A)
norm_sketch = linalg.norm(sketch)
```

Can anyone please help clearing this confusion??

**Comment by kdhingra307** [comment]
also this example will not pass the test case, written for clarkson transform

for that alpha has to be reduced from 0.1 to around 0.01 (somewhat near to that)

if u need that test case, i can share (i didnt share because it was very big)

**Comment by ilayn** [comment]
pinging @jomsdev

**Comment by jomsdev** [comment]
thanks for pinging me @ilayn 

@kdhingra307 I am not actually at home, I will replay tomorrow :)

**Comment by kdhingra307** [comment]
@jomsdev thanks

no issues

**Comment by jomsdev** [comment]
Hello @kdhingra307 I am glad to see that you are interested in contributing to improve the randomized numerical linear algebra methods in scipy.

If I am not wrong you are talking about the tests for the Clarkson transform (CWT). As you may have seen in the paper, there are two related  terms in the transformation: the size of the sketch and the error.

In a real world application you would have to first calculate the size of the sketch given the error bound that you want to have. However, for testing it, we decided to fix the size of the matrices, and put a threshold that is big enough to don't fail (knowing that our matrices are random.normal with mu=0, sigma=0.01) if the transformation is performed correctly.

```python
# Big dense matrix dimensions
n_matrix_rows = 2000
n_matrix_columns = 100

# Sketch matrix dimensions
n_sketch_rows = 100

# Error threshold
threshold = 0.1
```

The API does not let you yet get the right size given a desired error, neither the error given a size of the sketch but it is something that would be nice.

Not sure if this is what you were asking for, let me know if I can help you clarifying anything else.

**Comment by kdhingra307** [comment]
@jomsdev that's what I wanted to know

because it was little misleading initially and in the docs(not in test cases), the threshold variable needs to be changed a little bit (based on my calculations)

It was written in the docs about threshold and sketch size but I didn't find any code to find good sketch size (that's why I put this query)

should I add on to this, because I feel its important to find the right sketch size

**Comment by jomsdev** [comment]
@kdhingra307 it would be a good contribution.

I have a proposal for this GSoC for implementing Blendenpik and one of the sub tasks is to implement a method for this.

If you want to learn more about sketching errors, scikit has two implementatios of random projections.
In it's documentation you can find some useful links for the [The Johnson-Lindenstrauss lemma](http://scikit-learn.org/stable/modules/random_projection.html)

And other interesting contribution could be having two different sketch methods implemented the CWT (adapted to sparse matrices) and the Fast Johnson-Lindenstrauss trasnformation for dense ones. Then our algorithms (low rank, square solvers etc) could take advantage of each algorithm.

**Comment by kdhingra307** [comment]
@jomsdev Are u mentoring GSoC project for Sketches?? Because I got to know about Clarkson Woodruff transformation from there only.

thanks for scikit-learn link, I will go through those.

I did read the research paper about Johnson-Lindenstrauss transformation but shouldn't we sparsify clarkson woodruf transform first??

**Comment by jomsdev** [comment]
I am  not mentoring but applying as student too (I am currently finishing my master in discrete mathematics so this was my last chance for participating to GSoC :D)

As you said, one of the main advantages of CWT is that you **could** compute the sketch in nnz(A), where nnz is the number of non zeroes entries in the matrix. CWT was my first contribution to Scipy and given that I wasn't sure about how much support sicpy has for sparse matrix I decided to go step by step.

There is no problem in having both methods: CWT and FJLT implemented only for dense matrices and then improve the support of CWT for sparse matrices or do it in inverse order, first have CWT for sparse matrices and then implement the FJLT.

**Comment by kdhingra307** [comment]
@jomsdev same here, I am in the final year too :P

I think, we should go by implementation in the inverse order, because then for FJLT we don't have to sparsify too. We can then have direct sparsify implementation of FJLT.
plus also I think, if we implement algorithm for dense matrix first, then it would be redo of some of the work later on.

What do you say?

**Comment by jomsdev** [comment]
Well, FJLT can be used for dense and CWT for dense and sparse.  This is how it should look like after everything is implemented. From there, I do not see a a huge advantage about having the sparse version first because even without it we could implement Blendenpik and other algorithms on top of it but not taking advantage of sparsity.

But yes, I don't see any problem in having CWT for dense and sparse before FJLT.

**Comment by kdhingra307** [comment]
Let's go with the sparsity of CWT first and finish this to a good point, then we should go for FJLT.

**Comment by jomsdev** [comment]
@kdhingra307 time for writing the proposals, do you still being interested in RNLA? I am glad to help in finding something interesting/useful. 

In fact, we may end up doing something complementary :) 

Let me know if you need something.

**Comment by kdhingra307** [comment]
@jomsdev yaa I am, I have studied whole CWT and majority of FJLT in the meantime.

I was not available last week due to a minor surgery.😅😅

We will surely, 

Of course, I will start adding stuff now, related to CWT and its sparsity.

**Comment by kdhingra307** [comment]
I have created a pr with #8579

Also, I will also share my proposal and proposed workflow during the GSoC timeline

**Comment by rgommers** [comment]
@cdipaolo, @jomsdev  just checking, can we close this issue or is there something of interest left here?

**Comment by cdipaolo** [comment]
@rgommers Yes I believe this issue can be closed since the reference to a threshold in tests has been removed in #9884. Also, we provide some guidance on what an actual threshold should be in the docstring now.

That said I think it would be reasonable looking forward to add methods into `scipy.linalg` or `scipy.sparse.linalg` which use sketching under the hood to perform routine numerical linear algebra tasks like solving least squares problems approximately [[1](https://arxiv.org/abs/1411.4357)] or finding approximate low rank factorizations [[1](https://arxiv.org/abs/1411.4357),[2](http://users.cms.caltech.edu/~jtropp/papers/HMT11-Finding-Structure-SIREV.pdf)]. If/when these methods do get added (which is also worthy of discussion) it will be very important to include correct tolerance/threshold parameters. This could require some relatively extensive empirical investigation to get right, since many upper bounds in the theory don't give correct constant factors (and sometimes even asymptotics) as far as I'm aware. A recent paper by Dobriban and Liu [[3](https://arxiv.org/abs/1810.06089)] looks like it might be useful here though.

**Comment by rgommers** [comment]
> That said I think it would be reasonable looking forward to add methods into scipy.linalg or scipy.sparse.linalg which use sketching under the hood to perform routine numerical linear algebra tasks like solving least squares problems approximately [1] or finding approximate low rank factorizations [1,2]. 

@cdipaolo yes I think so.

> If/when these methods do get added (which is also worthy of discussion) it will be very important to include correct tolerance/threshold parameters. This could require some relatively extensive empirical investigation to get right, since many upper bounds in the theory don't give correct constant factors (and sometimes even asymptotics) as far as I'm aware. A recent paper by Dobriban and Liu [3] looks like it might be useful here though.

What would also be very useful is an overview of what is available. E.g. there's some randomized low-rank approximation methods in `scipy.linalg.interpolative`, and there's https://ristretto.readthedocs.io/en/latest/ which includes some sketching methods. It's pretty hard for non-experts to figure out what they need here, or the relative performance of the options.

**Comment by rgommers** [comment]
closing since this issue was addressed
