### ISSUE TITLE
Q: Cephes library refines log1p as cephes_log1p.  What's the intent?

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#8505]
scipy/special/cephes/cephes_names.h contains defines for the cephes functions
```
#define airy cephes_airy
#define bdtrc cephes_bdtrc
...
#define log1p cephes_log1p
#define expm1 cephes_expm1
...
```

In particular, `exp1m` and `log1p` get defined to be the functions in the cephes  library, not the ones in the stdlib math library.  This has some consequences.
1.  C code in the cephes module which calls `log1p` can generate different results from that generated by Python or numpy code, because they are using different implementations of `log1p`.
2. H files which contain macros/inline functions with references to `log1p/exp1m` will get different outcomes depending on whether `cephes_names.h` was included or not.  Similarly for C code.
Most current code appears to include `cephes_names.h` as a side-effect of including 
`scipy/special/cephes/mconf.h`, so is not even aware of its inclusion.
3. Some algorithms expect `log` and `log1p` to be "consistent" (as well as `exp` and `expm1`) and that doesn't occur here, as they are independent implementations.

Questions:
1. Why does cephes have its own version of `log1p/exp1m`?  It doesn't have its own `exp/log`.  Are the cephes implementations in some way "different/better" than the stdlib implementations?  Does the cephes library depend on the difference?
2. What is the need for the defines?  Is it to ensure cephes uses its versions of functions?  Or to ensure that other code doesn't use cephes versions of functions?
It appears that `erf`, `erfc`,`exp2`, `exp1m`,  `log1p`, `round` all get defined in this manner.
[The first commit of cephes_names.h contains an oblique reference to an issue with round()
https://github.com/scipy/scipy/commit/73aca75650cd9b1f0f175d6f9e68d76216c1bc7f]
3. For new C code, which `log1p` should the code use, the one in cephes, or the one in stdlib?

### Scipy/Numpy/Python version information:
```
1.1.0.dev0+a002bca 1.13.1 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

**Comment by person142** [comment]
> Why does cephes have its own version of log1p/exp1m

The stdlib versions are C99 additions, which we can't rely on having (Windows).

> What is the need for the defines? Is it to ensure cephes uses its versions of functions?

Tried to get rid of them here: https://github.com/scipy/scipy/pull/8401. In the end it wasn't worth dealing with the symbol conflicts. The answer is essentially to prevent namespace conflicts.

> For new C code, which log1p should the code use, the one in cephes

Until we can use C99 (should happen when Python 2 support is over), yes.

**Comment by pv** [comment]
If you want consistency with numpy, use `npy_log1p` from `npy_math.h`.

**Comment by person142** [comment]
Closing since I think the questions have been answered, though discussion can of course continue.

**Comment by pvanmulbregt** [comment]
Predictability perhaps more than numpy consistency. 
I didn't realize until this conversation that scipy.log1p and scipy.special.log1p were different functions.
[The difference between outputs appears to be +/-1ULP about 25% of the time on my machine.]
Implementing an algorithm in: Python, numpy Python, stand-alone C code, SciPy C code inside cephes; and the first 3 agree but the 4th is different can be a puzzling situation.  Now its clearer how that that can happen.
