### ISSUE TITLE
Why i can't install Tensorflow on my mac

### ISSUE THREAD

**Issue by geforcesong** [scipy/scipy#8508]
When i run this command pip3 install **tensorflow**, i got the following erros,

Failed building wheel for grpcio
  Running setup.py clean for grpcio
Failed to build grpcio
Installing collected packages: grpcio, tensorflow
  Running setup.py install for grpcio ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/3f/w96rrcpd2sg_dkyqsxnxhg940000gn/T/pip-build-32brj5tm/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/3f/w96rrcpd2sg_dkyqsxnxhg940000gn/T/pip-gqg2hxrt-record/install-record.txt --single-version-externally-managed --compile:
    Found cython-generated files...
    running install
    running build
    running build_py
    running build_project_metadata
    creating python_build
    creating python_build/lib.macosx-10.7-intel-3.6
    creating python_build/lib.macosx-10.7-intel-3.6/grpc
    copying src/python/grpcio/grpc/_channel.py -> python_build/lib.macosx-10.7-intel-3.6/grpc
    copying src/python/grpcio/grpc/_common.py -> python_build/lib.macosx-10.7-intel-3.6/grpc
    copying src/python/grpcio/grpc/__init__.py -> python_build/lib.macosx-10.7-intel-3.6/grpc
    copying src/python/grpcio/grpc/_utilities.py -> python_build/lib.macosx-10.7-intel-3.6/grpc
    copying src/python/grpcio/grpc/_plugin_wrapping.py -> python_build/lib.macosx-10.7-intel-3.6/grpc
    copying src/python/grpcio/grpc/_interceptor.py -> python_build/lib.macosx-10.7-intel-3.6/grpc
    copying src/python/grpcio/grpc/_grpcio_metadata.py -> python_build/lib.macosx-10.7-intel-3.6/grpc
    copying src/python/grpcio/grpc/_server.py -> python_build/lib.macosx-10.7-intel-3.6/grpc
    copying src/python/grpcio/grpc/_auth.py -> python_build/lib.macosx-10.7-intel-3.6/grpc
    creating python_build/lib.macosx-10.7-intel-3.6/grpc/beta
    copying src/python/grpcio/grpc/beta/_server_adaptations.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/beta
    copying src/python/grpcio/grpc/beta/interfaces.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/beta
    copying src/python/grpcio/grpc/beta/_metadata.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/beta
    copying src/python/grpcio/grpc/beta/__init__.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/beta
    copying src/python/grpcio/grpc/beta/utilities.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/beta
    copying src/python/grpcio/grpc/beta/implementations.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/beta
    copying src/python/grpcio/grpc/beta/_client_adaptations.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/beta
    creating python_build/lib.macosx-10.7-intel-3.6/grpc/framework
    copying src/python/grpcio/grpc/framework/__init__.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/framework
    creating python_build/lib.macosx-10.7-intel-3.6/grpc/_cython
    copying src/python/grpcio/grpc/_cython/__init__.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/_cython
    creating python_build/lib.macosx-10.7-intel-3.6/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/callable_util.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/abandonment.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/__init__.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/stream.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/stream_util.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/future.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/logging_pool.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/framework/foundation
    creating python_build/lib.macosx-10.7-intel-3.6/grpc/framework/common
    copying src/python/grpcio/grpc/framework/common/style.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/framework/common
    copying src/python/grpcio/grpc/framework/common/cardinality.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/framework/common
    copying src/python/grpcio/grpc/framework/common/__init__.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/framework/common
    creating python_build/lib.macosx-10.7-intel-3.6/grpc/framework/interfaces
    copying src/python/grpcio/grpc/framework/interfaces/__init__.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/framework/interfaces
    creating python_build/lib.macosx-10.7-intel-3.6/grpc/framework/interfaces/face
    copying src/python/grpcio/grpc/framework/interfaces/face/__init__.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/framework/interfaces/face
    copying src/python/grpcio/grpc/framework/interfaces/face/utilities.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/framework/interfaces/face
    copying src/python/grpcio/grpc/framework/interfaces/face/face.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/framework/interfaces/face
    creating python_build/lib.macosx-10.7-intel-3.6/grpc/framework/interfaces/base
    copying src/python/grpcio/grpc/framework/interfaces/base/__init__.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/framework/interfaces/base
    copying src/python/grpcio/grpc/framework/interfaces/base/utilities.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/framework/interfaces/base
    copying src/python/grpcio/grpc/framework/interfaces/base/base.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/framework/interfaces/base
    creating python_build/lib.macosx-10.7-intel-3.6/grpc/_cython/_cygrpc
    copying src/python/grpcio/grpc/_cython/_cygrpc/__init__.py -> python_build/lib.macosx-10.7-intel-3.6/grpc/_cython/_cygrpc
    creating python_build/lib.macosx-10.7-intel-3.6/grpc/_cython/_credentials
    copying src/python/grpcio/grpc/_cython/_credentials/roots.pem -> python_build/lib.macosx-10.7-intel-3.6/grpc/_cython/_credentials
    running build_ext
    b'[C]       Compiling src/boringssl/err_data.c\n'
    b"make: Circular /private/var/folders/3f/w96rrcpd2sg_dkyqsxnxhg940000gn/T/pip-build-32brj5tm/grpcio/libs/opt/libares.a <- /private/var/folders/3f/w96rrcpd2sg_dkyqsxnxhg940000gn/T/pip-build-32brj5tm/grpcio/libs/opt/libz.a dependency dropped.\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:115:\n/usr/local/include/openssl/e_os2.h:276:11: error: 'OPENSSL_EXPORT' macro redefined [-Werror,-Wmacro-redefined]\n#  define OPENSSL_EXPORT extern\n          ^\nthird_party/boringssl/include/openssl/base.h:178:9: note: previous definition is here\n#define OPENSSL_EXPORT\n        ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:122:\n/usr/local/include/openssl/ossl_typ.h:83:31: error: redefinition of typedef 'ASN1_INTEGER' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_INTEGER;\n                              ^\nthird_party/boringssl/include/openssl/base.h:253:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_INTEGER;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:122:\n/usr/local/include/openssl/ossl_typ.h:84:31: error: redefinition of typedef 'ASN1_ENUMERATED' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_ENUMERATED;\n                              ^\nthird_party/boringssl/include/openssl/base.h:249:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_ENUMERATED;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:122:\n/usr/local/include/openssl/ossl_typ.h:85:31: error: redefinition of typedef 'ASN1_BIT_STRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_BIT_STRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:247:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_BIT_STRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:122:\n/usr/local/include/openssl/ossl_typ.h:86:31: error: redefinition of typedef 'ASN1_OCTET_STRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_OCTET_STRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:254:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_OCTET_STRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:122:\n/usr/local/include/openssl/ossl_typ.h:87:31: error: redefinition of typedef 'ASN1_PRINTABLESTRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_PRINTABLESTRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:255:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_PRINTABLESTRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:122:\n/usr/local/include/openssl/ossl_typ.h:88:31: error: redefinition of typedef 'ASN1_T61STRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_T61STRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:257:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_T61STRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:122:\n/usr/local/include/openssl/ossl_typ.h:89:31: error: redefinition of typedef 'ASN1_IA5STRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_IA5STRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:252:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_IA5STRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:122:\n/usr/local/include/openssl/ossl_typ.h:90:31: error: redefinition of typedef 'ASN1_GENERALSTRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_GENERALSTRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:251:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_GENERALSTRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:122:\n/usr/local/include/openssl/ossl_typ.h:91:31: error: redefinition of typedef 'ASN1_UNIVERSALSTRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_UNIVERSALSTRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:259:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_UNIVERSALSTRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:122:\n/usr/local/include/openssl/ossl_typ.h:92:31: error: redefinition of typedef 'ASN1_BMPSTRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_BMPSTRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:248:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_BMPSTRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:122:\n/usr/local/include/openssl/ossl_typ.h:93:31: error: redefinition of typedef 'ASN1_UTCTIME' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_UTCTIME;\n                              ^\nthird_party/boringssl/include/openssl/base.h:260:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_UTCTIME;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:122:\n/usr/local/include/openssl/ossl_typ.h:94:31: error: redefinition of typedef 'ASN1_TIME' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_TIME;\n                              ^\nthird_party/boringssl/include/openssl/base.h:258:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_TIME;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:122:\n/usr/local/include/openssl/ossl_typ.h:95:31: error: redefinition of typedef 'ASN1_GENERALIZEDTIME' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_GENERALIZEDTIME;\n                              ^\nthird_party/boringssl/include/openssl/base.h:250:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_GENERALIZEDTIME;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:122:\n/usr/local/include/openssl/ossl_typ.h:96:31: error: redefinition of typedef 'ASN1_VISIBLESTRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_VISIBLESTRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:262:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_VISIBLESTRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:122:\n/usr/local/include/openssl/ossl_typ.h:97:31: error: redefinition of typedef 'ASN1_UTF8STRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_UTF8STRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:261:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_UTF8STRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:122:\n/usr/local/include/openssl/ossl_typ.h:98:31: error: redefinition of typedef 'ASN1_STRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_STRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:256:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_STRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:122:\n/usr/local/include/openssl/ossl_typ.h:99:13: error: redefinition of typedef 'ASN1_BOOLEAN' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef int ASN1_BOOLEAN;\n            ^\nthird_party/boringssl/include/openssl/base.h:242:13: note: previous definition is here\ntypedef int ASN1_BOOLEAN;\n            ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/include/openssl/err.h:122:\n/usr/local/include/openssl/ossl_typ.h:100:13: error: redefinition of typedef 'ASN1_NULL' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef int ASN1_NULL;\n            ^\nthird_party/boringssl/include/openssl/base.h:243:13: note: previous definition is here\ntypedef int ASN1_NULL;\n            ^\nfatal error: too many errors emitted, stopping now [-ferror-limit=]\n20 errors generated.\nmake: *** [/private/var/folders/3f/w96rrcpd2sg_dkyqsxnxhg940000gn/T/pip-build-32brj5tm/grpcio/objs/opt/src/boringssl/err_data.o] Error 1\n"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3f/w96rrcpd2sg_dkyqsxnxhg940000gn/T/pip-build-32brj5tm/grpcio/setup.py", line 311, in <module>
        cmdclass=COMMAND_CLASS,
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/private/var/folders/3f/w96rrcpd2sg_dkyqsxnxhg940000gn/T/pip-build-32brj5tm/grpcio/src/python/grpcio/commands.py", line 278, in build_extensions
        raise Exception("make command failed!")
    Exception: make command failed!

    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/3f/w96rrcpd2sg_dkyqsxnxhg940000gn/T/pip-build-32brj5tm/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/3f/w96rrcpd2sg_dkyqsxnxhg940000gn/T/pip-gqg2hxrt-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/3f/w96rrcpd2sg_dkyqsxnxhg940000gn/T/pip-build-32brj5tm/grpcio/

**Comment by andyfaff** [comment]
I don't think this isn't a scipy issue, it looks like a problem installing a package called `grpcio`.

**Comment by geforcesong** [comment]
Yeah, i tried this pip3 install --upgrade grpcio
It is reporting the exactly same error. What is that?

**Comment by andyfaff** [comment]
Unfortunately I have no idea. This is the issue board for the scipy package, grpcio is not related to scipy. You would be better served contacting the grpcio project for more help.
