### ISSUE TITLE
Full test suite too slow for Travis CI again

### ISSUE THREAD

**Issue by person142** [scipy/scipy#8518]
Recently we are fairly consistently getting timeouts when running the full test suite on Travis, so it's probably time to speed up some tests. Pytest says that the 20 slowest tests are:

```
===================================== slowest 20 test durations =====================================
49.00s call     scipy/stats/tests/test_fit.py::test_cont_fit[crystalball-arg13]
34.97s call     scipy/special/tests/test_cdflib.py::TestCDFlib::test_chndtrix
29.06s call     scipy/spatial/tests/test_qhull.py::TestUtilities::test_more_barycentric_transforms
20.36s call     scipy/spatial/tests/test_distance.py::TestPdist::test_pdist_correlation_iris_nonC
19.86s call     scipy/stats/tests/test_continuous_basic.py::test_cont_basic[genexpon-arg30]
19.67s call     scipy/special/tests/test_mpmath.py::TestSystematic::test_gegenbauer_int
18.58s call     scipy/spatial/tests/test_distance.py::TestPdist::test_pdist_correlation_iris
18.33s call     scipy/spatial/tests/test_distance.py::TestPdist::test_pdist_correlation_iris_float32
16.71s call     scipy/stats/tests/test_continuous_basic.py::test_moments[genexpon-arg30-True-True-False]
15.94s call     scipy/special/tests/test_mpmath.py::TestSystematic::test_erfc_complex
15.45s call     scipy/special/tests/test_mpmath.py::TestSystematic::test_e1_complex
14.88s call     scipy/special/tests/test_mpmath.py::test_spence_circle
14.83s call     scipy/stats/tests/test_continuous_basic.py::test_moments[kappa4-arg52-True-True-False]
14.53s call     scipy/linalg/tests/test_decomp_ldl.py::test_ldl_type_size_combinations
14.17s call     scipy/_build_utils/tests/test_circular_imports.py::test_importing_submodules
13.72s call     scipy/stats/tests/test_continuous_basic.py::test_moments[vonmises-arg98-False-False-False]
13.69s call     scipy/special/tests/test_mpmath.py::TestSystematic::test_bessely_complex
13.40s setup    scipy/_lib/tests/test_warnings.py::test_warning_calls_stacklevels
13.40s call     scipy/spatial/tests/test_distance.py::TestPdist::test_pdist_cosine_iris_nonC
13.31s call     scipy/stats/tests/test_continuous_basic.py::test_moments[kappa4-arg54-True-True-False]
```

**Comment by ilayn** [comment]
Could you please let me know what to run for the timings? I'll change the sizes a bit to get the `test_basic` and `test_decomp_ldl` out of the slow list. Essentially they don't do anything important to be on that list.

**Comment by pv** [comment]
`python3 runtests.py -- --durations=1000` --- you can add any pytest arguments after the `--` on the command line, see `python3 -mpytest --help` for a complete list.

**Comment by Lodomir** [comment]
I just want to mention that `mpmath` uses a fairly slow Python implementation of arbitrary precision floats if `gmpy2` is not installed. But I do not know what is installed/used on the testing system and apologize if this is not any help.

```
$ python runtests.py -v -m full -t scipy.special.tests.test_mpmath::TestSystematic::test_gegenbauer_int
> 1 passed in 8.49 seconds
$ conda install gmpy2
$ python runtests.py -v -m full -t scipy.special.tests.test_mpmath::TestSystematic::test_gegenbauer_int
> 1 passed in 5.50 seconds
```

**Comment by andyfaff** [comment]
Those 20 tests come to something like 6 mins. Whilst knocking off some of them would undoubtedly shrink run time, I wonder if there's another way? For example, how long does the setup/build phase take? Is there possibility to shave time there?

**Comment by ilayn** [comment]
Building is about 5 minutes on Travis plus a minute or so for the environment setup.

**Comment by person142** [comment]
> I just want to mention that mpmath uses a fairly slow Python implementation of arbitrary precision floats if gmpy2 is not installed

We do use `gmpy` for testing; it was done in https://github.com/scipy/scipy/pull/6427.

Anyway, build/test times have stopped being a problem since I created this issue. It seems that Travis had a real slowdown a couple of weeks ago which has gotten better now. The price we pay for using a free service I guess.
