### ISSUE TITLE
Wrong documentation for scipy.signal.firls. Hazardous behavior of the function

### ISSUE THREAD

**Issue by micdestefano** [scipy/scipy#8524]
The documentation of scipy.signal.firls is partly wrong.

It says that 

> "`weight` has to be half the size of `bands`".

Looking at the code you can verify that this is not true, because `if len(weight) != len(desired):` an exception is raised.

Furthermore, I think that the behavior promised by the documentation should be implemented, and not what it is in the code right now, because the algorithm is assuming a constant weight for each band, but the user is not prevented from providing different weights in correspondence of band edges (remember that the code right now works only if `len(weights) == len(bands)`).

You should really modify the code so that it behaves like promised by the documentation.

**Comment by ilayn** [comment]
Notice that the arrays are reshaped with `(-1,2)` and `len` for 2D arrays are the row numbers hence it is as mentioned.

**Comment by micdestefano** [comment]
You are right. My apologies.
Best regards.
