### ISSUE TITLE
ode.get_return_code is poorly documented

### ISSUE THREAD

**Issue by rjrosati** [scipy/scipy#8526]
The [documentation page](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.ode.get_return_code.html#scipy.integrate.ode.get_return_code) for the function is a stub. There's no indication what different return values mean.

At the least, I'd propose including the blurb I found [here](https://github.com/scipy/scipy/blob/v1.0.0/scipy/integrate/_ode.py) (line 693). 

>  istate > 0 means success, istate < 0 means failure

**Comment by homocomputeris** [comment]
I'd like to note that the  new `Integrate` part is poorly documented overall.

**Comment by sudheerachary** [comment]
I would like to improve the documentation of the `ode.get_return_code` method. where would i get the information and functionality of the `ode.get_return_code`. please guide me. thanks

**Comment by sethtroisi** [comment]
PR #8612 merged which adds documentation
