### ISSUE TITLE
scipy.sparse.csgraph.reverse_cuthill_mckee : response function of the size of the matrix

### ISSUE THREAD

**Issue by pkrezel** [scipy/scipy#8531]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

For a small matrix (NxN) with N=20, the result is correct but for larger matrix the result is flipped like with numpy.flip !

### Reproducing code example:
```
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```

### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```

**Comment by pv** [comment]
Please provide explicit example.

**Comment by rgommers** [comment]
no response, closing
