### ISSUE TITLE
bound by two integer value

### ISSUE THREAD

**Issue by MahdiDoost** [scipy/scipy#8545]
In the name of Allah
Hello,

I want to bound x1bnds, x2bnds, alpha1bnds, alpha2bnds, alpha3bnds, alpha4bnds by 0 or 1 not between 0 and 1.
Please help me.
Thank you

```
`x2bnds = (0, 1)
Rbnds = (0, 1)
alpha1bnds= [0, 1]
alpha2bnds= [0, 1]
alpha3bnds= [0, 1]
alpha4bnds= np.array([0,2], dtype=int)
bnds = (x1bnds, x2bnds, Rbnds, alpha1bnds, alpha2bnds, alpha3bnds, alpha4bnds)`
```

**Comment by ilayn** [comment]
Hi @MahdiDoost 

I can't say that I have really understood your question but it looks like you are trying to come up with a code specific to your use case. You can use https://www.stackoverflow.com for generic code questions. This issue reporting tool is about the issues over functionality of SciPy itself so we won't be able to help you.

**Comment by sschnug** [comment]
I'm pretty sure he is asking for support of mixed-integer optimization (which is completely missing from scipy).

**Comment by rgommers** [comment]
> I'm pretty sure he is asking for support of mixed-integer optimization (which is completely missing from scipy).

I'd say MIP is out of scope, at least developing it from scratch. And there are no suitably licensed open source solvers out there AFAIK - everything semi-decent is GPL/CPL/academic.

**Comment by andyfaff** [comment]
You might get somewhere with `differential_evolution`. It doesn't use gradients, so you can cast floats to integers without issue. I'm not sure that's technically correct, but it's worth a go.
