### ISSUE TITLE
[Bug?] Example of Bland's Rule for optimize.linprog (simplex) cycling/preventing termination

### ISSUE THREAD

**Issue by mikkelmk** [scipy/scipy#8561]
Forcing Bland's Rule with the "bland":True options seems to prevent the code example below from terminating, while the purpose of Bland's Rule is to make sure it terminates. The problem is solved quickly when not forcing Bland's Rule, giving an optimal value of -6.044533469014448.

By "not terminating" i mean that it's still running after running for a couple of hours on a MacBook Pro, while my own implementation of Bland's Rule finds it in seconds.

### Reproducing code example:
```
import numpy as np
import scipy.optimize as opt
import sys

np.random.seed(4)
m = int(np.round(10 * np.exp(np.log(50) * np.random.rand())))
n = int(np.round(10 * np.exp(np.log(50) * np.random.rand())))
c, A, b = np.round(10*np.random.randn(n)),np.round(10*np.random.randn(m,n)),np.round(10*np.abs(np.random.randn(m)))
opt.linprog(-1*c, A, b, options={"maxiter": sys.maxsize, "bland": True})
```

### Scipy/Numpy/Python version information:
1.0.0 1.14.0 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)

**Comment by rgommers** [comment]
Looks like a clear bug, thanks for reporting @mikkelmk

**Comment by mikkelmk** [comment]
I found a potential issue and a possible fix! 

The problem is not when choosing the entering variable/pivot column, but when choosing the leaving variable/pivot row. Both has be chosen according to Bland's Rule.

When more than one pivot row is possible, _pivot_row simply chooses the left-most choice:
_linprog.py, 209: `return True, np.ma.where(q == q.min())[0][0]`

This approach works for choosing the pivot column, as the choices are sorted by variable index. It does not work for choosing the pivot row, however, since the basis is not sorted by variable index.

Instead, something like this is required:
```
    candidates = np.ma.where(q == q.min())[0]
    return True, candidates[np.argmin(np.take(basis, candidates))]
```
With the above change, the problem is solved quickly with the "bland":True option and thus seems to fix the issue.

This of course requires _solve_simplex to send basis as a parameter and also the bland boolean if the change should only be used when bland == True.

I will try my hand at including this in my first ever pull request later today.
