### ISSUE TITLE
CI: Appveyor builds fail because it can't import ConvexHull from spatial.qhull

### ISSUE THREAD

**Issue by ilayn** [scipy/scipy#8562]
The PRs are all poisoned with the same failing 87 tests. I've built locally on a few Windows machines and can't replicate it. 

Is it possible that the cache we use to share between different architectures in Appveyor got poisoned ?

**Comment by pv** [comment]
The cache only contains pip packages, so why it fails is unclear.

Maybe Cython 0.28 release has something to do with this?

**Comment by pv** [comment]
Indeed, the last successful build used Cython 0.27.3, and the first
failing one uses Cython 0.28.

Tasks:

- Pin the Cython version to 0.27.3 in the appveyor config
- Point the bug out to Cython devs

**Comment by ilayn** [comment]
That requires a change in the requirements.txt since we use -U flag for pip. Should we downgrade cython version after that manually?

**Comment by charris** [comment]
This is only on appveyor/windows? Cython 0.28.0 seems to work fine for NumPy on travis.

**Comment by pv** [comment]
Only Windows, and seemingly related to some specific code, cf. 
https://github.com/cython/cython/issues/2154

**Comment by rgommers** [comment]
Reopening, CI is fixed but the issue not.

**Comment by ilayn** [comment]
@pv Indeed it is just one line that is seemingly causing the trouble. I'll check for an alternative 

(by the way  I've opened that Cython issue anyways 😃 )
