### ISSUE TITLE
Arguments swapped in scipy.spatial.procrustes and scipy.linalg.orthogonal_procrustes

### ISSUE THREAD

**Issue by zdavid0123** [scipy/scipy#8574]
I am using `scipy.spatial.procrustes` and `scipy.linalg.orthogonal_procrustes` for my program and just took a look into the source codes. I noticed that `procrustes(A, B)` calls `orthogonal_procrustes(A, B)` in its definition. (I'm ignoring the standardization of `A` and `B` for now.)

However, while `procrustes(A, B)` looks for a transformation from `B` to `A`, `orthogonal_procrustes(A, B)` looks for a transformation from `A` to `B`, as written in the documentations of the two functions. 

Is this reversing of the arguments intended or made by mistake?

**Comment by zdavid0123** [comment]
NVM, I just realized that the transformation matrix `R` given by `orthogonal_procrustes` is used as `R.T` in `procrustes`. The transpose cancels the effect of reversing the two matrices.

**Comment by seralouk** [comment]
@daviddaiweizhang I came across the same observation. Can you elaborate more on why the transpose cancels the effect of reversing the two matrices? 

Instead of `mtx2 = np.dot(mtx2, R.T) * s` I would expect `mtx1 = np.dot(mtx1, R) * s`
