### ISSUE TITLE
Documentation: how to contribute mixed-language code (build; deployment)?

### ISSUE THREAD

**Issue by sschnug** [scipy/scipy#8575]
Hi,

is there any documentation about contributing new code, which is not pure python?

There is [devdocs/hacking.html](http://scipy.github.io/devdocs/hacking.html) which says:

> Can I use a programming language other than Python to speed up my code?

> Yes. The languages used in SciPy are Python, Cython, C, C++ and Fortran. All of these have their pros and cons. If Python really doesn’t offer enough performance, one of those languages can be used. Important concerns when using compiled languages are maintainability and portability. For maintainability, Cython is clearly preferred over C/C++/Fortran. Cython and C are more portable than C++/Fortran. A lot of the existing C and Fortran code in SciPy is older, battle-tested code that was only wrapped in (but not specifically written for) Python/SciPy. Therefore the basic advice is: use Cython. If there’s specific reasons why C/C++/Fortran should be preferred, please discuss those reasons first.

*I'm missing any documentation on how incorporation of external-languages actually would work in terms of building / deployment.* How cython or let's say C++ would be made ready to be compiled (when calling setup.py)? And what needs to be assumed about deployment on all those targets (Win, Linux, OS X)? (small [docs-entry](http://scipy.github.io/devdocs/dev/index.html#building-binary-installers))

It seems something is done for example in [tools/cythonize.py](https://github.com/scipy/scipy/blob/master/tools/cythonize.py), but it's hard to grasp rules from that.

Would there be a good part of scipy to look at? Maybe *sparsetools* or *cluster*? Are there mixed-language code-parts considered *best-practice* and ones which are somewhat *less-modern* (maybe a lot of wrapping in optimize).

Am i right, that [weave](https://docs.scipy.org/doc/scipy-0.18.1/reference/weave.html) is dead?

And i'm probably right about scipy not supporting [pybind11](https://github.com/pybind/pybind11) for the near-future (due to C+11 dependency or keeping less dependencies in general)?

For now this is a theoretical question (no code yet) which maybe would lead to some work in the future (no guarantees).

(Sorry for the somewhat unstructured text)

**Comment by lagru** [comment]
> I'm missing any documentation on how incorporation of external-languages actually would work in terms of building / deployment.

Source files from C, C++ and Cython are usually compiled while building the package from source. This should be done automatically if you use the guidelines found [here](http://scipy.github.io/devdocs/building/index.html). Depending on your platform you'll need to install the right compilers which shouldn't be a problem on most Linux distributions.

For the actual integration of a new source file that needs to be compiled you need to add it to the correct places so it gets picked up during build. Have a look at the changes in #8350. Notice how the new new PYX file (source file for Cython) was added to the `signal/setup.py` and `signal/bento.info` files?
Your best bet is to l look at how existing files are integrated. Pick a source file and search for its name in SciPy's code base. That should give you an overview of the involved places.

**Comment by lagru** [comment]
Another tip: If want to perform an in-place build that can be run from the source folder you can use `python setup.py build_ext --inplace`. Afterwards you can import the SciPy from the source directory itself.

**Comment by sschnug** [comment]
That's helping (the last thing mentioned i already saw  @ either scipy's or sklearn's docs and Matt's dev-install videos). I think i will dig through the code somewhat. The idea of checking pull-requests is good! 

I did not expect to see so many ```setup.py``` files, all tailored to one module (if that's the right word). So i think a cython-based low-complexity / 1-file addition is covered (although not tried yet).

sparsetools on the other hand looks somewhat more complex (probably due to C++ instead of cython), e.g. [generate_sparsetools.py](https://github.com/scipy/scipy/blob/master/scipy/sparse/generate_sparsetools.py).

**Comment by sschnug** [comment]
A follow-up question:

**What are the assumptions on the build-system of the supported target systems?**

From unordered sources/discussions i gathered:

- no support for openMP
- no heavy wrapper-tools like pybind11 and co.
- no cmake

But what about the C++ standard supported? I assume there is no support for C++11 and co (with all the downsides like no simple portable [isnan](http://www.cplusplus.com/reference/cmath/isnan/))?

Additionally it looks like: no assumption about the availability of *boost*?`

On compiler-side: gcc/g++, clang(?), Intel and Visual Studio, or something more?

Is there any documentation about that (to not need to go through all continuous-integration scripts)?

(In the hope of not spamming: let's ping: @rgommers / @pv )

**Comment by mdhaber** [comment]
@sschnug btw this is something I've been interested in making one of those videos about (but first i need to learn how). If you get this figured out and think a video would be helpful to others, let me know!

**Comment by sschnug** [comment]
After preparing (given my above assumptions; not yet confirmed) my sources to drop usage of cmake, openMP and providing some needed parts (as i needed to downgrade C++11-based code) from boost manually (headers), i'm now having trouble to prepare the automatic setup in scipy's build-system. 

Trying to learn from scipy.spatial and scipy.optimize (maybe scipy.sparse later), i can make scipy to prepare my shared-lib, but i'm unable to load it using ctypes. 

Sadly, ctypes does not seem to be widely used (not used at all) and every other wrapper uses cython.

I described my approach and asked a question at [StackOverflow](https://stackoverflow.com/questions/50139483/scipy-ctypes-build-config-how-to-load-lib)

**Comment by rgommers** [comment]
> Would there be a good part of scipy to look at? Maybe sparsetools or cluster? Are there mixed-language code-parts considered best-practice and ones which are somewhat less-modern (maybe a lot of wrapping in optimize).

- For Cython most code is fine, just contained in one or more `.pyx` files. E.g. `sparse/csgraph/*.pyx`.
- For C++ code I would suggest `spatial/ckdtree.*`.
- For C and Fortran code: best not to write that from scratch. If you have a C or Fortran library you want to wrap and integrate, maybe discuss the specific case on the mailing list (there are a lot of ways to do that, and the preferred one may depend on size of library).

> sparsetools on the other hand looks somewhat more complex

yes, there's a couple of files like `generate_sparsetools.py` floating around, but those scripts all have specific reasons and are not a pattern to follow.

> - no support for openMP
> - no heavy wrapper-tools like pybind11 and co.
> - no cmake

Correct. OpenMP and `pybind11` are not desirable from the point of view of portability and keeping dependencies to a minimum. CMake is a build system, we simply don't use it.

> But what about the C++ standard supported? I assume there is no support for C++11 and co (with all the downsides like no simple portable isnan)?

Correct, no C++11 yet. I'm actually not sure what constraints need to be fulfilled to be able to accept C++11 code. 

> Additionally it looks like: no assumption about the availability of `boost`?

Correct, no `boost`.

> On compiler-side: gcc/g++, clang(?), Intel and Visual Studio, or something more?

There are more compilers supported by `numpy.distutils`, e.g. for building on platforms like AIX, Raspberry Pi, etc. There's nothing specific to keep in mind for those though. The best thing to focus on is to write clean C code. At the moment there are still a few issues with C99 on Windows (older Visual Studio versions don't support it), at the point where we drop Python 2.7 and 3.4 we will have full C99 support.

> But now i got problems while loading the functions using ctypes and opened up a new question with some information [here](https://stackoverflow.com/questions/50144595/scipy-numpy-distutils-based-setup-py-ctypes-undefined-symbol).

AFAIK `ctypes` support for C++ is not good, so not sure you want to go down that path. For the rest of that post, `config.add_extension` means building a *Python* extension. I think you want to use `add_library` instead.

> Is there any documentation about that (to not need to go through all continuous-integration scripts)?

Not well organized, scattered throughout issues like this one. Let's take this issue as the opportunity to add something to the developer guide.

**Comment by sschnug** [comment]
I do understand, that it's desirable to stick to cython or C99, but it's hard to read out how to prepare already-implemented projects using C++.

This boils down to:

- **A**: the wrapping-howto (Cython, Ctypes, ...)
- **B**: the assumptions on OS/Compilers/Build-tools and co.

I do think, there are some C++ projects, which look very interesting from scipy's point-of-view.

Let's look at an example:

- ```scipy.linprog(method='simplex')``` is in a very sad state
  - more or less unmaintained
  - technically pretty limited / basic (dense vs. sparse, tableau vs. revised, primal vs. dual, presolve, API: duals, ...)
  - buggy (i'm aware about numerical-issues and that there will always be trouble-cases):
    - wrong solutions with valid output-state
      - at some points negative slacks are returned (!!!) and there is no check for that
    - somtimes failing to provide solutions for feasible problems (phase-1 problem)
  - ```scipy.linprog(method='interior-point')``` is quite nice, but it's not an simplex-method
  - (i do have much respect for all that work which was done to implement this code; writing a good Simplex-solver is a tedious task!)

Now i have some working prototype wrapper (scipy-patch) adding [https://github.com/ERGO-Code/HiGHS](https://github.com/ERGO-Code/HiGHS), which is:

- MIT licensed
- C++ (recent additions towards C++11)
- Some external non-MIT code 
- High-quality Dual-Revised Simplex with Presolve and Parallelization
  - (non-scientific: it's in serial-mode probably at least an order of magnitude faster than both alternatives; even without presolve) and more stable/robust
- (more research-like code)
  - not really documented
  - there is a lot to improve:
    - one can see it's code which was written by someone (dissertation; this one is now at FICO working on Xpress) and is now being modified by other people
    - while the core-stuff looks pretty clean, there is a lot of commented / dead-code
    - but performance in terms of speed and robustness is far ahead of the alternatives (imho)
- (future MIP-support indicated; presolve somewhat work in progress)

My scipy-patch can be described as:

- Remove some unneeded stuff:
  - remove external dependencies
  - add some boost-stuff (headers)
  - remove need for Cmake
  - port it down to be compiled with (default) C++ (whatever that means)

So now it's:
- fully incorporated in terms of:
  - solves instances when called with ```linprog(method='revised-simplex)'```
  - automatic build through scipy's setup.py (tested on Ubuntu)
    - core-problem **A** was tackled by cython, as ctypes did not get me far!
- (not ready to merge as some basic stuff still missing and some non-trivial design-decisions)

So ignoring those yet-to-do design-decisions (there are many! as: strip away all openMP code-parts; strip away MPS-reader, clean-up code, ...), there is now the question: what is needed to make it portable? And that's something i can't answer right now (AIX and Raspberry Pi support probably do not make this easier).

Additionally there is one design-decision highly linked to being portable:

- the C++ code uses int's
- without modern C++/Boost, the size of those int's is probably dependent on OS/Compiler (32bit, 64bit)
- the cython-wrapper surely should be careful providing the data (int32 vs. int64)
  - cython-part probably needs introspection (what is int on my machine)
  - or (design-decision): modify the whole code to make int int32 (using Boost)

I do understand the above is somewhat unstructured, but i'm trying to speak out for some documentation collecting hidden (or in worst-case: unspecified) things for people thinking about adding external C++ code.

While the current code, as mentioned, is some valuable reference (somewhat made my prototype work in terms of cython + buildtools), there are still some open issues.

**Comment by rgommers** [comment]
> Now i have some working prototype wrapper (scipy-patch) adding https://github.com/ERGO-Code/HiGHS, which is:

That does look useful indeed.

> Some external non-MIT code

Is it license compatible, and if not, can it be removed?

> So ignoring those yet-to-do design-decisions (there are many! as: strip away all openMP code-parts; strip away MPS-reader, clean-up code, ...),

Best to modify as little as possible, because all patches you make will need to be re-applied every time we upgrade to a new version of that library. E.g. OpenMP support can be disabled with a compile flag, so probably best to just leave it all in.

> there is now the question: what is needed to make it portable? And that's something i can't answer right now (AIX and Raspberry Pi support probably do not make this easier).

I looked a bit more into C++11 support on exotic platforms, and it seems to be fine. GCC >= 4.7, Clang >= 3.1 and MSVC >=2012 are all okay. Things like `xlc` (AIX compiler) are fine too. Looks like the only annoyance will be MSVC 2008, which we will drop within a year when Python 2.7 goes away. Developing PRs now already anticipating no py27 seems fine to me.

Re int32/int64 stuff, this may be useful: https://github.com/scikit-learn/scikit-learn/wiki/C-integer-types:-the-missing-manual

**Comment by mdhaber** [comment]
Started writing some documentation about Cythonizing code.
https://github.com/scipy/scipy/wiki/Adding-Cython-to-SciPy
It's not really ready to be reviewed, as I have written based on a fading memory of my experience a few months ago. I'll refresh my memory and continue/correct the document soon.

**Comment by mdhaber** [comment]
This issue is partially addressed by #10286, but information about using Cython as a bridge to other compiled code should be added.

**Comment by rgommers** [comment]
I propose we close this. It's more a general skills question rather than something we can address with a targeted bit of documentation. 

Note that http://scipy.github.io/devdocs/dev/toolchain.html now documents exactly what is an isn't supported in terms of compilers, language standards and build-time dependencies.
