### ISSUE TITLE
stats.percentileofscore performance

### ISSUE THREAD

**Issue by Yomguithereal** [scipy/scipy#8582]
Hello scipy team. I just read the code for `stats.percentileofscore` and wondered if we could boost its performance slightly by using binary search instead of linear search when attempting to find the score's index in the array.

Here: https://github.com/scipy/scipy/blob/master/scipy/stats/stats.py#L1789
And here: https://github.com/scipy/scipy/blob/master/scipy/stats/stats.py#L1796-L1797

Sorry if this is irrelevant because numpy's underlying implementation is doing some magic or if I overlooked something.

Thanks for your work.

**Comment by Yomguithereal** [comment]
After a second examination, I might overlooked some things:

1) since you sort the array, maybe you consider that the sorting complexity (unless you use some kind of linear time sorting algorithm) makes the point a bit moot, performance-wise.
2) since you append the item to the array if not found through linear search, and since you don't want to sort twice, you don't want to binary search the second time to avoid complexity. Though, I feel that by retrieving the lower bound of the searched item in the sorted array, we can still get the percentile by dividing by `n + 1` rather than just `n` if item at lower bound is not the searched one, thus preventing the need for appending the item in the first place.

**Comment by pvanmulbregt** [comment]
The "rank" path does indeed search for the `score` in the unsorted `a` array.   Reordering so the sort precedes the searching for the `score` element would enable a binary search.
But if you are seeing a performance hit, that unsorted searching may not be the reason.  Instead look to the fact that it makes 3 copies of the `a` array during its processing (copy, append, sort) plus it creates another array (`a_len`) of the same length. 
[I actually suspect that the whole computation can be done without any sorting or copying at all.]
Do you have an example exhibiting unexpected slowness?

**Comment by Yomguithereal** [comment]
The method I propose only requires to sort the array (thus copying it only one time) and does not need to create the `a_len` array to work.

> I actually suspect that the whole computation can be done without any sorting or copying at all.

I don't know about a method that would avoid sorting or at least selecting (using quickselect) for instance. What do you have in mind?

> Do you have an example exhibiting unexpected slowness?

No, my interest in the performance of this function is completely theoretical, I did not open the issue because of some performance issue on my end. I just read the code and wondered if it indeed was the best way to compute this information. To add some context, I was perusing several code bases like scipy's to be able to implement the `quantileRank` function of the JS `simple-statistics` library (code [here](https://github.com/simple-statistics/simple-statistics/blob/master/src/quantile_rank_sorted.js)).
