### ISSUE TITLE
Q: Using `assert` vs `numpy.testing.assert_` in testing

### ISSUE THREAD

**Issue by larsoner** [scipy/scipy#8583]
A few times the idea of using direct `assert ` statements in tests rather than `assert_` from `numpy.testing` has come up. IIUC `pytest` guarantees that `assert ` statements are executed.

Some advantages of `assert `:

1. Simplicity. No need for imports.
2. Improved tracebacks. `pytest` has put work into making `assert` error messages readable for diagnosing problems.
3. Long-term consistency (?). I have seen a proliferation of `assert ` statements in other packages, so that seems to be the zeitgeist.
4. Lowering contribution/review burden. Given the increasing use of `assert `, the probability of contributors using it assuming it's acceptable increases, and allowing its use is one fewer thing we have to nitpick.

Some advantages of `numpy.testing.assert_`

1. Internal consistency (near-/medium-term). We have historically used `assert_` and have 1561 of instances according to `git grep "assert_(" | wc -l`.
2. Guaranteed support. `numpy.testing` can be guaranteed to work as long as `numpy` does, whereas `assert ` relies on `pytest` maintenance and/or `pytest`-compatible `assert ` support by any future testing framework.

There are probably others, feel free to comment and/or edit this top comment to keep track.

My +1 is for allowing `assert ` if people want to use it. I have begun moving a few of my other repos to follow this pattern and so far have found it beneficial.

**Comment by charris** [comment]
Seems pytest rewrites the `assert`s on import, so I guess it's like auto generated `assert_` ;)

**Comment by tylerjereddy** [comment]
+1 for plain `assert`, which pytest replaces with more detailed low-level stuff to provide detailed error reports; also guarantees protection against removal by the Python optimization flag. 

One point of potential hesitation -- I was wondering if we had scenarios where we'd still want to support the (now deprecated / dying?) nose as a runner to some extent -- the plain asserts moving forward might reduce that support to some extent (if there's an obscure scenario where someone is using nose and -O flag).

Looks like you're proposing to *allow* plain assert, but not necessarily any kind of mass migration of what's currently in the code base, which is perhaps a relevant distinction.

**Comment by charris** [comment]
Without some small maintenance for the import of abstract classes, nose will not work with Python 3.8, I already needed to patch it locally for 3.7 due to the deprecation warning turning into an error. Nothing major, but it is starting to bit rot.

**Comment by pv** [comment]
I think at the moment there is no need to ensure nose compatibility.

**Comment by andyfaff** [comment]
Scipy uses pytest as a runner now, not nose

**Comment by larsoner** [comment]
> I was wondering if we had scenarios where we'd still want to support the (now deprecated / dying?) nose as a runner to some extent

> I think at the moment there is no need to ensure nose compatibility.

Agreed from my end.

> Looks like you're proposing to allow plain assert, but not necessarily any kind of mass migration of what's currently in the code base, which is perhaps a relevant distinction.

Yep, that's what I'm thinking.

**Comment by rgommers** [comment]
After some playing it seems that ``assert`` and ``assert_`` are still pretty much identical, and `nose` compat is indeed irrelevant now. So fine with me to allow `assert`, saves some review comments.

Note that both functions are still fairly useless in pointing out actual problems, because you still just get `AssertionError` instead of getting shown the mismatch like with any other `numpy.testing` function - so both should be used sparingly.

**Comment by larsoner** [comment]
> Note that both functions are still fairly useless in pointing out actual problems, because you still just get AssertionError instead of getting shown the mismatch like with any other numpy.testing function

How do you mean? This is an example output of a 1-line test function `pytest test.py`:
```
    def test_list():
>       assert ['a', 'b'] == ['a', 'c']
E       AssertionError: assert ['a', 'b'] == ['a', 'c']
E         At index 1 diff: 'b' != 'c'
E         Use -v to get the full diff

test.py:4: AssertionError

 test.py ⨯                                                                                                                                                           100% ██████████

Results (0.07s):
       1 failed
         - test.py:3 test_list
```
So for built-in types it should tell you a bit about where the problem is.

**Comment by larsoner** [comment]
... and by contrast, the NumPy variant for completeness (which does exhibit the "fairly useless" property you mention):
```
    def test_list():
>       numpy.testing.assert_(['a', 'b'] == ['a', 'c'])
E       AssertionError

test.py:5: AssertionError

 test.py ⨯
```

**Comment by larsoner** [comment]
FWIW the pattern that I have found most useful is to use `numpy.testing` functions (e.g., `numpy.testing.assert_allclose`) for `ndarray` and `assert ` for built-in Python types.

**Comment by rgommers** [comment]
> So for built-in types it should tell you a bit about where the problem is.

Right, thanks - I had tested scalars, arrays and custom structures, not lists/tuples.

**Comment by rgommers** [comment]
It looks like there are no objections after 5 days, so let's call it good!

**Comment by hickmanw** [comment]
FYI, SciPy [Testing Guidelines](https://docs.scipy.org/doc/numpy/reference/testing.html) currently state "Note that the Python builtin `assert` should not be used, because it is stripped during compilation with -O."

**Comment by larsoner** [comment]
I think that's probably outdated advice from when nose was used instead of pytest, and that we should update it. `assert` should not be used in library code but should be fine (or even preferred) in tests as far as I can tell.
