### ISSUE TITLE
Spearman correlation without p-values

### ISSUE THREAD

**Issue by dojeda** [scipy/scipy#8585]
I am currently doing an analysis where the Spearman correlation is calculated a relatively large number of times (>10000) on 2D matrices that are n_observations=40, n_variables~=200. I was suprised to find, after some profiling, that more than half of the time of the execution time is spent while calculating the p-value of the Spearman correlation. Unfortunately, we don't really use this value. In fact, the documentation is clear: _The p-values are not entirely reliable but are probably reasonable for datasets larger than 500 or so._

So I thought it would be useful to modify the `scipy.stats.spearman_r` function to add a kwarg `p_value=None`  (or something else) so that this calculation remains optional.

I would be happy to create a PR if this is of interest for the scipy community.

Moreover, there is a possible improvement to the Spearman calculation that can be used if there are no ties on the rank of the variables. I am currently wrapping our Spearman correlation method to (unfortunately) repeat what `scipy.stats.spearman_r` does, without some checks:

```python
def some_func(x, y):
    ...
    # Verify if can use _spearman_fast_unique,
    # which only works with when all observations are unique
    x_unique = np.apply_along_axis(lambda col: len(set(col)), 0, X)
    y_unique = len(set(y))
    if np.all(x_unique == y.shape[0]) and y_unique == y.shape[0]:
        func = _spearman_fast_unique
    else:
        msg = (
            'Not all observations are unique, using the '
            '_spearman_fast function that is slight slower '
            '(but still fast!)'
        )
        warnings.warn(msg, UserWarning, stacklevel=2)
        func = _spearman_fast
    ...
    return func(numpy.c_[y, x])


def _spearman_fast(yx):
    """ A faster Spearman correlation """
    # This is basically a rewrite of scipy.stats.spearmanr that does not
    # do any checks (we have to ensure the data is on the correct shape)
    # and does not calculate the p-value of the R statistic (which is costly
    # and we do not need)
    ar = np.apply_along_axis(stats.rankdata, 0, yx)
    rs = np.corrcoef(ar, None, rowvar=False)
    return rs[0, 1:]


def _spearman_fast_unique(yx):
    """ A faster Spearman correlation that needs the data to be unique """
    ar = np.apply_along_axis(stats.rankdata, 0, yx)
    # d = rg_xi - rg_yi
    d = ar - ar[:, 0, np.newaxis]
    n = d.shape[0]
    # R = 1 -  6 \sum_i d_i^2 / (n*(n^2-1))
    rs = 1 - 6 * np.sum(d*d, axis=0) / (n*(n*n-1))
    return rs[1:]
```

The gain is not large (about 0.5x), but useful for my case.
I think this could be generalized (since we are only interested in the correlation with respect to column 0), but I would only invest some time if there is an interest for this as well.

So if there is interest for this kind of PR, please let us discuss it. I would certainly prefer to add this to scipy in case there is some improvements on the scipy.stats module that my team could benefit from (which I would miss because we are rewriting part of the function)

**Comment by rgommers** [comment]
Hi @dojeda, thanks for the idea. In general speeding up functions is very welcome, however in this case making the API more clunky for a 2x speedup doesn't seem like the right trade-off to me. So I'd prefer not to see a new keyword skipping part of the calculations.

**Comment by rgommers** [comment]
After wading through the mess that was `spearmanr` and `mstats.spearmanr` and making them match R and pandas, I'm more convinced that this is undesired. Note that `pandas.DataFrame.corr` has a `spearmanr` method and is written in Cython; didn't benchmark but it's probably faster than the `scipy.stats` version.
