### ISSUE TITLE
ENH: increase readability of scalar newton moethod

### ISSUE THREAD

**Issue by mikofski** [scipy/scipy#8589]
In response to [a comment](../pull/8357#pullrequestreview-105961211) @jaimefrio there are some the lines that could be refactored in [`newton`](../blob/v1.0.0/scipy/optimize/zeros.py#L199) and consequently the array newton PR #8357 to make them more readable

### Reproducing code example:
* This happens twice here and then again on L213
```
q1 = func(*((p1,) + args))
# could be just
q1 = func(p1, *args)
```

* similarly in newton and halleys `(*myargs)` replaces `(x0, *args)`, but is it necessary?

* Also since #8489 was merged, [`fder=0` on L165](../blob/1da95f6/scipy/optimize/zeros.py#L165) can safely be removed.

* Finally, I'd like to understand why for the [halley and newton methods](../blob/1da95f6120188a12e56f269c4f820f3cb6122214/scipy/optimize/zeros.py#L162-L164), there's ...
```
        # Multiply by 1.0 to convert to floating point.  We don't use float(x0)
        # so it still works if x0 is complex.
        p0 = 1.0 * x0
``` 
... but for [secant](../blob/1da95f6120188a12e56f269c4f820f3cb6122214/scipy/optimize/zeros.py#L187) there's just `p0 = x0` - seems like we could just put this once somewhere before [the conditions on L160 for both methods](../blob/1da95f6/scipy/optimize/zeros.py#L160)

### Scipy/Numpy/Python version information:
SciPy-1.0.0

**Comment by sudheerachary** [comment]
I would like to take up on this issue, are these the only changes need to be made ?

**Comment by mikofski** [comment]
Sounds great! There may be other issues. Maybe start a discussion on the [SciPy-Dev mailing list](https://mail.python.org/mailman/listinfo/scipy-dev)? Thanks!

**Comment by rgommers** [comment]
This is fairly detailed, probably best discussed here rather than on the mailing list.

@sudheerachary if you feel comfortable tackling this, go for it!
