### ISSUE TITLE
benchmarks/benchmarks/test_go_benchmark_functions.py seems misplaced

### ISSUE THREAD

**Issue by charris** [scipy/scipy#8592]
This is a test module and has outdated dependencies `run_module_suite`, etc. Not sure where it should go, but it looks misplaced  

### Reproducing code example:
```
NA
```

### Error message:
```
NA
```

### Scipy/Numpy/Python version information:
```
master as of c10dc2153
```

**Comment by rgommers** [comment]
Yeah looks odd. Only tests `rosen` it seems. A number of the functions in there are used in `benchmarks/optimize.py` though. So it looks like the file just needs a rename. Actually both `test_functions.py` and `test_go_benchmark_functions.py`, plus removing the `nose` specific things.

**Comment by charris** [comment]
Actually, `test_go_benchmark_functions.py` was the one I meant :)

**Comment by andyfaff** [comment]
I was wondering where to put this when I wrote it. It's useful to have, but I don't know where it should go.
