### ISSUE TITLE
Missing methods in multivariate_normal_frozen

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [scipy/scipy#8593]
Unlike stated in the documentation frozen multivariate gaussians do not have the same method, some of them are missing.

Either the documentation should be updated or the methods should be avaialble.

### Reproducing code example:
```
from scipy.stats import multivariate_normal
model = multivariate_normal([1, 6], [[1, 0], [0, 1]])
print(model.cdf([0, 0]))
```

### Error message:
```
AttributeError: 'multivariate_normal_frozen' object has no attribute 'cdf'
```

### Scipy/Numpy/Python version information:
```
0.19.1 1.13.1 sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)
```

**Comment by GuillaumeLeclerc** [comment]
Sorry, I was behind master. I thought this method would be the first thing to be implemented but it seems to be a very recent addition.

**Comment by WarrenWeckesser** [comment]
You reported using scipy 0.19.1.  The `cdf` (and `logcdf`) methods were added in scipy 1.0.0.  You'll have to upgrade to 1.0.0 to use `cdf`.
