### ISSUE TITLE
BENCH: Benchmarks for find_peaks, peak_prominences & peak_widths

### ISSUE THREAD

**Issue by lagru** [scipy/scipy#8601]
As suggested in #8594 it might be worthwhile to add asv benchmarks for the recently added functions

- [ ] [find_peaks](https://scipy.github.io/devdocs/generated/scipy.signal.find_peaks.html)
- [ ] [peak_prominences](https://scipy.github.io/devdocs/generated/scipy.signal.peak_prominences.html)
- [ ] [peak_widths](https://scipy.github.io/devdocs/generated/scipy.signal.peak_widths.html)

introduced with #8264. This may act as a reminder and place of discussion until I or someone else takes this up in a PR or it is resolved by other means.

See also: #8541, #8523

**Comment by lagru** [comment]
Ping @tylerjereddy (I don't now if GitHub informes about references automatically)

**Comment by tylerjereddy** [comment]
@lagru Thanks!
