### ISSUE TITLE
document argrelmax, argrelmin and argrelextrema flaws

### ISSUE THREAD

**Issue by KOLANICH** [scipy/scipy#8602]
Raw data and smoothed with `scipy.signal.medfilt` with `kernel_size=5` one give completely different results: tue result obtained on smoothed data lacks peaks and 2 unneeded peaks appeared where they mustn't be (valleys), even though the unsmoothed and smoothed curves are very similar. The data is TEM Laue diffractogram crossection (unfortunately I have left ia and the program at work).

**Comment by lagru** [comment]
It would be useful if you could provide more information when you can. E.g. a plot of smoothed vs raw data and a small code snippet showing your usage of `medfilt` and `argrelmax`. Without knowing more background information it's hard to judge what's going wrong... but it might be possible that you ran into a known gotcha. `argrelmax` can't detect maxima that are more than one sample wide (see #6848) which might explain some of the unexpected behavior.

**Comment by KOLANICH** [comment]
>it might be possible that you ran into a known gotcha. argrelmax can't detect maxima that are more than one sample wide (see #6848) which might explain some of the unexpected behavior.

Yes, it is exactly this. Thank you. I guess this behavior snould  be documented (with links to better functions).

**Comment by lagru** [comment]
You're welcome.

> I guess this behavior snould be documented (with links to better functions).

Agreed and will be included in the next release of with #8264. You can already see the changes live in the [development version of the documentation](https://scipy.github.io/devdocs/generated/scipy.signal.argrelmax.html).
