### ISSUE TITLE
Testing guideline page is linked to GitHub instead of being build with other docs

### ISSUE THREAD

**Issue by madphysicist** [scipy/scipy#8606]
The section on unit tests under the "Contributing New Code" section of the "Contributing to SciPy" page (http://scipy.github.io/devdocs/hacking.html#contributing-new-code) has a link to the "testing guidelines". This link points to a page on github (https://github.com/numpy/numpy/blob/master/doc/TESTS.rst.txt) instead of being compiled in with the other doc pages.

**Comment by rgommers** [comment]
That's because we link to documentation outside the SciPy docs; we don't really want to copy that over because then we have the same info in two places. The rendered reST also doesn't look bad. So I don't think there's any problem here?

**Comment by madphysicist** [comment]
Would it make sense to open this in numpy? Is there a reason the page is not part of the generated docs? It just seems a bit out of place.

**Comment by rgommers** [comment]
History mostly I think. Would need some reorganisation of the docs there, and multiple other pages would need to be included as well (C style guide, HOWTO_BUILD/DOCUMENT/RELEASE). Would all need to go into the devguide there. Go ahead and open an issue there I'd say.
