### ISSUE TITLE
scipy.sparse.linalg.eigs() requires way too large memory

### ISSUE THREAD

**Issue by iagyonwu** [scipy/scipy#8623]
i have a generalized eigenValue problem from linear stability analysis, which end up with solving Aq=wBq. 
Here the following is an example of how the matrix A and B look like, a typical size of A &B is 50000x50000, and can be even larger.
Matrix A:
![image](https://user-images.githubusercontent.com/33458610/37972938-afc3e1ba-31d9-11e8-972e-67661fdbb14c.png)
Matrix B:
![image](https://user-images.githubusercontent.com/33458610/37972968-c027a9a6-31d9-11e8-8905-305b9f1ba799.png)

Both Matrix A and B are not symmetric.  Therefore, I converted my equation into inv(B)Aq=wq.  Say, L0 = inv(B)A. I get L0  with scipy.sparse.linalg(B,A). Then the eigenvalue is computed with the following code:
`OMEGA, eigVecs = sp.linalg.eigsh(L0, k= 20, sigma=SIGMA, v0=options_v0, tol=arnoldiTol)`

Since my matrix sometimes can be very large, I would end with the following error:

> Not enough memory to perform factorization.
Traceback (most recent call last):
File "init_Re620eta1_40X_2Z_omega10.py", line 158, in <module>
exec_stabDiagBatchFFfollow_2D(geometry,baseFlowFolder,baseFlowVarb,baseFlowMethod,h,y_max_factor_EVP,Ny_EVP,Nz_EVP,x_p_stabDiag,x_p_orig,eigSolver,noEigs2solv,noEigs2save,SIGMA0,arnoldiTol,OmegaTol,disc_y,disc_z,y_i_factor_EVP,z_i_factor_EVP,periodicZ,BC_top,customComment,BETA,ALPHA_min,ALPHA_max,noALPHA,ALPHA_start,xp_start,u_0,nu_0,y_cut,ParallelFlowA,comm,rank,RESTART,saveJobStep,saveResultFormat)
File "/lustre/cray/ws8/ws/iagyonwu-Re620eta1/omega10DNS_wTS_icoPerbFoam/LST_functions_linstab2D_Temperal_mpi_multiTracking4.py", line 3893, in exec_stabDiagBatchFFfollow_2D
OMEGA, eigVecs = sp.linalg.eigs(L0, k=noEigs2solv, sigma=SIGMA, v0=options_v0, tol=arnoldiTol)
File "/opt/python/3.6.1.1/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 1288, in eigs
symmetric=False, tol=tol)
File "/opt/python/3.6.1.1/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 1046, in get_OPinv_matvec
return SpLuInv(A.tocsc()).matvec
File "/opt/python/3.6.1.1/lib/python3.6/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 907, in __init__
self.M_lu = splu(M)
File "/opt/python/3.6.1.1/lib/python3.6/site-packages/scipy/sparse/linalg/dsolve/linsolve.py", line 267, in splu
ilu=False, options=_options)
MemoryError

it seems the splu would require very large memory. Considering I am running the code on cluster with 128GB memory, I believe it should be enough for my problem. If any one knows how I can work  around this memory issue? 

I also tried to provide a oprator OPinv, but it seems the flowing eigs will take forever. 
`OP = A - SIGMA*B `
`opinv = LinearOperator(matvec=lambda v: cg(OP, v, tol=1e-5)[0], shape=Shape, dtype=LHS.dtype)`

**Comment by bojin665821** [comment]
I've encountered the same problem. I solved it by using umfpack solver and changing the data type of matrix indices (int32 to int64). I tried to apply the same change while using SuperLU but encountered an error "rowind and colptr must be of type cint". It seems SuperLU are not able to identify data type: numpy.int64

**Comment by lobpcg** [comment]
1. ARPACK with the sigma=SIGMA option factorizes the matrix, effectively destroying the matrix sparsity. That is why it needs so much memory. This is normal.

2. ARPACK is not a parallel code, i.e., cannot take advantage of distributed memory. 

Try using SLEPc in PETSc instead. 

I suggest that the issue can be closed. This is normal expected behavior of ARPACK.

**Comment by OulanB** [comment]
There is a bug in SuperLU used in eigs to solve repeatedly a linear system. It seems to be related to the use of 32bits integer as matrix indexes. I had the same problem with somewhat dense sparse systems of size 300000x300000. I solved the problem by patching eigs to use another solver. In my case I use a MUMPS 5.1.2 with a patched PyMumps. Changing the solver used in eigs is relatively easy, just look in PYTHON/lib/python3.X/site-packages/scipy-X.X/scipy/sparse/linalg/eigen/arpack arrack.py file.

**Comment by pv** [comment]
For reference, it's not necessary to patch eigs code --- you need to specify the `Minv` and `OPinv` linear operators to use a different solver.
