### ISSUE TITLE
should hankel function at 0 return nan or -1j * inf?

### ISSUE THREAD

**Issue by nedlrichards** [scipy/scipy#8624]
This is not a serious concern, except it is inconsistent with the connection formula:

hankel1(v, x) = jv(x) + 1j * yv(x)

since yv(0) returns -inf.

Likewise, k0(0) returns inf, so the definition in the scipy documentation also implies the result should be (nan-infj).

### Reproducing code example:
```
from scipy.special import hankel1, y0, k0
print(hankel1(0, 0))
print(y0(0))
print(k0(0))
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
1.0.0 1.14.1 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
```

**Comment by nedlrichards** [comment]
As a related issue, numerical limitations in the function lead to NaN values instead of Inf values in the y(n, x) function. I assume that there are similar issues in related functions.

```
from scipy.special import yn
print(yn(50, 0.001))  # a very large negative number
print(yn(50, 0.000001))  # a NaN
print(yn(50, 0))  # value returned at singularity
```

**Comment by person142** [comment]
I believe the current behavior is correct. For real arguments IEEE is essentially modeling the two-point compactification of the real line, i.e. `[-oo, oo]`. Doing something similar for complex arguments would require a circle of infinities, which is not available. So instead the reasonable interpretation of complex infinity should be the point at infinity for the one-point compactification of the complex plane, i.e. the north pole of the Riemann sphere. With this interpretation, a function should return complex infinity at a pole only if the limit is the same for all sequences converging to the pole, which is not the case with Hankel functions, e.g.

```
>>> sc.hankel1(0, 1e-6)
(0.99999999999974998-8.8690314816594444j)
>>> sc.hankel1(0, -1e-6)
(-0.99999999999974998-8.8690314816594444j)
```

**Comment by person142** [comment]
Though to be honest this is just what I've always thought to myself-I would love to have a reference to a paper discussing this. (The real case is documented, but I'm not sure about the complex case.)

**Comment by nedlrichards** [comment]
Thanks for the reply, I had been thinking about this problem entirely from the real axis. I think that the difference between the k0 and the kv function makes the source of my confusion clear. I'll close this thread, and if the behaviour in the second comment is important that can become a separate issue.

'
\>>> sc.k0(0)
inf
\>>> sc.kv(0,0)
nan
'
