### ISSUE TITLE
scipy 1.0.1 no longer allows overwriting variables in netcdf files opened with mode='a'

### ISSUE THREAD

**Issue by shoyer** [scipy/scipy#8625]
The following example passes without error on scipy 1.0.0, but errors with scipy 1.0.1 installed:
```
import scipy.io

f = scipy.io.netcdf_file('testing123.nc', mode='w')
f.createDimension('x', 2)
f.createVariable('x', float, ('x',))
f.variables['x'][...] = 1
f.close()

f = scipy.io.netcdf_file('testing123.nc', mode='a')
f.variables['x'][...] = 2
f.close()
```
```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-e0dd6e681544> in <module>()
      8
      9 f = scipy.io.netcdf_file('testing123.nc', mode='a')
---> 10 f.variables['x'][...] = 2
     11 f.close()

~/miniconda3/envs/xarray-py36/lib/python3.6/site-packages/scipy/io/netcdf.py in __setitem__(self, index, data)
    994                 except ValueError:
    995                     self.__dict__['data'] = np.resize(self.data, shape).astype(self.data.dtype)
--> 996         self.data[index] = data
    997
    998     def _get_missing_value(self):

ValueError: assignment destination is read-only
```

This manifested itself in failures in the xarray test suite: https://github.com/pydata/xarray/issues/2019

**Comment by rgommers** [comment]
That fails on master too. Most likely the offending commit is a923628e8dd7de

**Comment by rgommers** [comment]
Yep, that's the commit. That looked harmless enough. Different behavior between `fromstring` and `frombuffer`, guess that fix should have forced returning a copy instead of a view.

**Comment by rgommers** [comment]
May require a 1.0.2 ... :(

**Comment by shoyer** [comment]
Yeah, `frombuffer` returning a readonly view instead of a copy is a subtle difference. The NumPy deprecation warning should possible add some sort of note about that, as well.

I'll leave it up to your judgement on whether this requires a 1.0.2 release. My guess is that this breaks only a few users. Overriding data in existing files is certainly somewhat rare compared to creating new files -- especially because scipy's netcdf writer always rewrites the file scratch. Generally I would recommend using the netCDF4 library instead of scipy for this use case anyways because it avoids the rewriting issue.

**Comment by rgommers** [comment]
All right, will wait for a bit whether anything else shows up that would require a 1.0.2. Otherwise maybe let it wait till 1.1.0, which should be out in just over a month.

**Comment by rgommers** [comment]
fix in gh-8633
