### ISSUE TITLE
Sigma clipping on data with the same value

### ISSUE THREAD

**Issue by domoritz** [scipy/scipy#8632]
When I use sigma clipping with an array where all values are the same, everything gets clipped. 

```python
import scipy
scipy.stats.sigmaclip([2,2,2])[0]
```

This is especially problematic if there is one outlier and all other values are the same.

```python
import scipy
scipy.stats.sigmaclip([2]*20+[3])[0]
```

In both examples, I end up with an empty list.

**Comment by domoritz** [comment]
Astropy doesn't have this problem

```
> from astropy.stats import sigma_clip
> sigma_clip([2]*20+[3])
masked_array(data=[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                   2, 2, --],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False,  True],
       fill_value=999999)
```

**Comment by chrisb83** [comment]
According to the documentation, "The output array contains only those elements of the input array c that satisfy the conditions `mean(c) - std(c)*low < c < mean(c) + std(c)*high` "

If `std(c) = 0`, there is no such element, so it is technically correct, but still not what you expect.

One could change strict inequality to `<=` (Looks like this is what astropy does, see Notes here http://docs.astropy.org/en/stable/api/astropy.stats.sigma_clip.html)

**Comment by domoritz** [comment]
Thank you @chrisb83 for the quick fix!
