### ISSUE TITLE
Scaling for Welch method

### ISSUE THREAD

**Issue by moppymopperson** [scipy/scipy#8651]
I'm struggling to use the `signal.welch` method. I'm not sure if it is a bug, my own lack of understanding, or just missing documentation.

I expect the code below to produce a properly scaled PSD, but changing the `nperseg` parameter changes the magnitude of the output. I presumed the welch function is meant to internally handle complexities like window length and zero padding. Is this not the case, or is this a bug? The documentation does not hint anywhere that manual scaling of the result is required or what it should be.

### Reproducing code example:
```python
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import welch, periodogram

# Create a simple sine wave
amp = 3.
freq = 50.
fs = 200.
T = 10
N = T * fs
t = np.arange(N) / fs
x = amp*np.sin(2*np.pi*freq*t)

# Compare periodogram with Welch method using different nperseg (window lengths)
f, Sxx = periodogram(x, fs=fs, window="boxcar")
f1, Sxx1 = welch(x, fs=fs, window="boxcar", nperseg=100)
f2, Sxx2 = welch(x, fs=fs, window="boxcar", nperseg=200)

# If the sine wave's frequency does not land precisely on a frequency bin we cannot expect the results to match
assert freq in f, "{} not precisely on a frequency bin".format(freq)
assert freq in f1, "{} not precisely on a frequency bin".format(freq)
assert freq in f2, "{} not precisely on a frequency bin".format(freq)

# Plot the results for visual inspection
plt.plot(f, Sxx, label="Sxx")
plt.plot(f1, Sxx1, label="Sxx1")
plt.plot(f2, Sxx2, label="Sxx2")
plt.xlabel("Hz")
plt.ylabel("$\mathrm{Units}^2 / \mathrm{Hz}$")
plt.legend()
plt.show()

# My understanding is that the peaks in each spectrum should be approximately equal
assert Sxx.max() == Sxx1.max() == Sxx2.max(), "All results are not equivalent"
```

### Error message:
```
N/A
```

### Scipy/Numpy/Python version information:
```
1.0.0 1.13.3 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

**Comment by ewmoore** [comment]
What are the units that you are expecting the spectrum to have?  Given your expectations, it sounds like you want `scaling='spectrum'`, where the units are `V**2` if the input is in `V`.  These routine default to `scaling='density'`, where the units are `V**2/Hz`, where the area under the curve is preserved.

**Comment by moppymopperson** [comment]
@ewmoore  Thanks for such a quick response.

I am trying to compare results of data I measured to previous results taken at a different sampling frequency and for a different duration. I'm interested in how the manitudes compare. Based on your response, it sounds like the only valid way to make that comparison would be by comparing the power spectrum in units `V**2`, not the spectral density in units `V**2/Hz`. Is that correct?

**Comment by ewmoore** [comment]
If you want to compare the magnitude of your spectra, you should use `scaling='spectrum'`.  If you compare integrals over a bandwidth, you should use `scaling='density'`.  

I don't know what your application is, so I can't say if this is really what you should be doing.

I'm going to close this as there is no bug or feature request here, discussion can, of course, continue, but this may not be the best forum.

**Comment by moppymopperson** [comment]
@ewmoore Thanks for clearing up my misconception. I agree that it working as described.
