### ISSUE TITLE
Division by zero in _trustregion.py when x0 is exactly equal to the minimum.

### ISSUE THREAD

**Issue by rudolfbyker** [scipy/scipy#8686]
When using the `trust_ncg` minimisation algorithm with analytic solutions for the first (`jac`) and second (`hess`) order derivatives, and the initial guess `x0` is exactly equal to the minimum, then `jac_mag` is zero at that point, which causes an unhandled division by zero in `get_boundaries_intersections` in`BaseQuadraticSubproblem` in `_trustregion.py`.

It happens rarely, since the probability of two floating point numbers being exactly equal is low.

Here's a screenshot of my debugger when it happens:

![image](https://user-images.githubusercontent.com/10025342/38453271-1de5fa58-3a53-11e8-84d9-4f3557dea1cd.png)

### Reproducing code example & error message

```
import scipy.optimize
import numpy as np


def fun(x):
    return x * x


def jac(x):
    return 2 * x


def hess(x):
    return 2


results = scipy.optimize.minimize(fun=fun, x0=0, method='trust-ncg', jac=jac, hess=hess, options={
    # 'disp': True,
    # 'gtol': gtol,
    # 'max_trust_radius': 1.,
    # 'initial_trust_radius': 0.5,
})

print results

```

If you change `x0` from `0` to `x0=0 + np.finfo(float).eps`, the output is as expected:
```
     fun: array([0.])
    hess: 2
     jac: array([0.])
 message: 'Optimization terminated successfully.'
    nfev: 2
    nhev: 1
     nit: 1
    njev: 2
  status: 0
 success: True
       x: array([0.])

```

Otherwise, we get:

```
/home/dolf/anaconda2/lib/python2.7/site-packages/scipy/optimize/_trustregion.py:93: RuntimeWarning: invalid value encountered in double_scalars
  ta = -aux / (2*a)
/home/dolf/anaconda2/lib/python2.7/site-packages/scipy/optimize/_trustregion.py:94: RuntimeWarning: divide by zero encountered in double_scalars
  tb = -2*c / aux
/home/dolf/anaconda2/lib/python2.7/site-packages/scipy/optimize/_trustregion_ncg.py:100: RuntimeWarning: invalid value encountered in multiply
  pb = z + tb * d
     fun: array([0.])
    hess: 2
     jac: array([0.])
 message: 'Optimization terminated successfully.'
    nfev: 2
    nhev: 1
     nit: 1
    njev: 1
  status: 0
 success: True
       x: array([0.])
```

Which is still the correct answer, but I think the special case should be handled internally by scipy, without giving a warning to the user.

### Scipy/Numpy/Python version information:
```
('1.0.0', '1.14.0', sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0))
```

**Comment by antonior92** [comment]
Thank you a lot for reporting the error.

I will try to take a look at it when I have some time. It seems to be something easy to fix.
