### ISSUE TITLE
Structured arrays documentation error

### ISSUE THREAD

**Issue by PhilippeDoucette** [scipy/scipy#8701]
In the documentation page...
https://docs.scipy.org/doc/numpy-1.14.0/user/basics.rec.html#structured-arrays

The page reads reads:

>>> y = x['bar']
>>> y[:] = 10
>>> x
array([(10, 5.), (10, 5.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

The last line should be:

array([(10, 10.), (10, 10.)], dtype=[('foo', '<i8'), ('bar', '<f4')])

**Comment by ilayn** [comment]
This needs to be reported on NumPy repository https://github.com/numpy/numpy
