### ISSUE TITLE
getrow / getcol of dok_matrix do not return 'real sparse' dok matrices

### ISSUE THREAD

**Issue by jpmjpmjpm** [scipy/scipy#8717]
`getrow` or `getcol` of `dok_matrix` return as expected a row or a vector matrix of `dok_matrix` type. However, the zero coefficients are created in the dictionary . I would expect to get a row or column with dictionaries "just extracted" from the original dok_matrix.

### Reproducing code example:
```
from scipy.sparse import dok_matrix

sparse_matrix = dok_matrix((6, 5))
sparse_matrix[1,0] = sparse_matrix[1, 3] = 1.
row = sparse_matrix.getrow(1)
print row

```

### Current output:
```
  (0, 1)	0.0
  (0, 3)	1.0
  (0, 0)	1.0
  (0, 2)	0.0
  (0, 4)	0.0
```

### Expected output:
```
  (0, 3)	1.0
  (0, 0)	1.0
```

### Scipy/Numpy/Python version information:
```
(scypy, numpy, sys) = ('1.0.0', '1.14.0', sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0))
```

### Comments:

I don't know if current returned `dok_matrix` are done on purpose or not. If yes, I imagine that the main intent is performance. However, this is inducing some complexity in my scripts. If not, I'll be happy to volunteer to fix the issue.

**Comment by pv** [comment]
You can write `sparse_matrix[1,:]` instead of `getrow(1)`.

**Comment by pv** [comment]
In principle, `getrow` and `getcel` could be replaced with 
`return self[j,:]` and `return self[:,j]`, or equivalent refactoring
for the slice case.

**Comment by perimosocordiae** [comment]
I'm a bit surprised this wasn't already addressed in my indexing overhaul PR (gh-7827). I'll fix it there.

**Comment by sethtroisi** [comment]
Code passes at head, seems PR #7827 fixed this.
