### ISSUE TITLE
Q: scipy.stats.norminvgauss documentation question

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#8719]
The doc for norminvgauss in scipy/stats/_continuous_distns.py describes has this description:
```
 A normal inverse Gaussian random variable with parameters `a` and `b` can
    be expressed  as `X = b * V + sqrt(V) * X` where `X` is `norm(0,1)`
    and `V` is `invgauss(mu=1/sqrt(a**2 - b**2))`. 
```

`X` occurs on both sides of the equation and appears to mean different things in the two usages. What should the equation be?

### Scipy/Numpy/Python version information:
```
1.1.0.dev0+512ac81 1.14.2 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

**Comment by chrisb83** [comment]
It should be
`b * V + sqrt(V) * X` is `norminvgauss(a, b)` where `X` is `norm(0,1)` and `V` is...

**Comment by pvanmulbregt** [comment]
Closed by gh-8750
