### ISSUE TITLE
cannot import name 'imresize'

### ISSUE THREAD

**Issue by DebarshiDatta** [scipy/scipy#8721]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

ImportError                               Traceback (most recent call last)
<ipython-input-36-86a6528cb948> in <module>()
      1 # Code (adapted) from https://github.com/ageron/handson-ml
      2 
----> 3 from scipy.misc import imresize
      4 #from keras.preprocessing.image import ImageDataGenerator
      5 

ImportError: cannot import name 'imresize'

### Reproducing code example:
```
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```

### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```

**Comment by pv** [comment]
These functions are available only when Pillow is installed.

**Comment by DebarshiDatta** [comment]
Thank you. How to install Pillow. If you please share the codes

**Comment by pvanmulbregt** [comment]
For Pillow installation see: https://pillow.readthedocs.io/en/5.1.x/installation.html.  
`pip install Pillow`
works in many platforms/environments.
