### ISSUE TITLE
Enable pip build isolation

### ISSUE THREAD

**Issue by pv** [scipy/scipy#8734]
pip 10 added support for build isolation, configured in `pyproject.toml`:
https://pip.pypa.io/en/stable/reference/pip/#pep-518-support

Unfortunately, it is a partial implementation, and missing two features our current `pyproject.toml` uses:

- [x] using packages without available wheels as dependencies (https://github.com/pypa/pip/issues/5229) --- **added in** https://github.com/pypa/pip/pull/5336
- [x] support for environment markers (https://github.com/pypa/pip/issues/5230) --- added in pip 18

The first is needed since we'd want to build against Numpy 1.8.2, which has no wheels available.
The second is for making the Numpy version to depend on the Python version.

Install etc. can made to work by giving `--no-build-isolation` flag to pip, however.

Two options what we can do:

- Remove `pyproject.toml`, and re-add after PyPa has fixed the implementation in pip.
- Bump the numpy dependency in `pyproject.toml`  to the earliest Numpy version that has wheels on all platforms on all supported Python versions, Numpy 1.13.1. Environment markers will IIUC be supported <s>in next pip bugfix release (10.0.1)</s> in some future pip release, after which the version requirements can be made basically Numpy 1.11.3.

I'll take the first one for Scipy 1.1.0.

Before pip 10.x.y fixes its stuff the second option doesn't look viable, 1.13.1 is too new.
However, maybe we could bump Numpy dependency to 1.11.3 for Scipy 1.2.x once pip 10.x.y is out.

### Reproducing code example:
```
$ git show HEAD  # current master
commit 13d8ada4fccc729fa0fd927eae9e5aa8d68ed705
$ ./env/bin/pip --version
pip 10.0.0 from /home/pauli/prj/scipy/scipy/env/lib64/python3.6/site-packages/pip (python 3.6)
$ ./env/bin/pip wheel .
Processing /home/pauli/prj/scipy/scipy
  Could not find a version that satisfies the requirement numpy==1.8.2 (from versions: 1.11.3, 1.12.0rc2, 1.12.0, 1.12.1rc1, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2)
No matching distribution found for numpy==1.8.2
$ ./env/bin/pip install .
Processing /home/pauli/prj/scipy/scipy
  Could not find a version that satisfies the requirement numpy==1.8.2 (from versions: 1.11.3, 1.12.0rc2, 1.12.0, 1.12.1rc1, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2)
No matching distribution found for numpy==1.8.2
$ ./env/bin/pip install --no-build-isolation .
... ## <- this one works!
```

**Comment by Juanlu001** [comment]
Environment markers have been added in pip master 🎉

**Comment by matthew-brett** [comment]
Cross link to long discussion about build requirements, environment markers: https://github.com/pypa/pip/issues/4582

**Comment by rgommers** [comment]
the PR where env markers were added is https://github.com/pypa/pip/pull/5286. for clarity: that didn't end up in pip 10.0

**Comment by pv** [comment]
pip 18 afaics has what's needed.

**Comment by tylerjereddy** [comment]
Do we want to enable this build isolation now? Just need to add a file back?

**Comment by rgommers** [comment]
I suggest to add `pyproject.toml` back after the 1.2.x branch. This is stuff that you don't want to be debugging last-minute.
