### ISSUE TITLE
Segfault when running linalg.eigsh on matrix larger than 4075000x4075000

### ISSUE THREAD

**Issue by kpws** [scipy/scipy#8741]
I consistently get a segfault in linalg.eigsh, see code below. lil_matrix, csc_matrix also give segfaults. k=2 also gives a segfault. The time until the segfault occurs varies a bit, sometimes a few seconds, sometimes half a minute.

For n=4050000 or smaller the code below doesn't crash.
If I set OMP_NUM_THREADS=1 before running the program, then it also does not crash.

Possibly related to: https://github.com/scipy/scipy/issues/4937

### Reproducing code example:
```
from scipy import sparse
from scipy.sparse import linalg
n=4075000
linalg.eigsh(sparse.coo_matrix((n,n)), k=1)
```

### Error message:
```
Segmentation fault (core dumped)
```

### Scipy/Numpy/Python version information:
```
('1.0.1', '1.14.2', sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0))
```

**Comment by pv** [comment]
Can you give more information on which BLAS/LAPACK Scipy is linked
with? Maybe OpenBLAS if the openmp flags affects it. You may want to
see if it also happens with a different blas/lapack library.

Since it cannot be reproduced on typical machines due to the large
memory requirement, it's best if you can do debugging yourself. Can you
get the traceback showing where it crashes by running under gdb?

**Comment by kpws** [comment]
Alright,
Indeed I use openblas, libopenblasp-r0-39a31c03.2.18.so:
```
>>> import numpy
>>> numpy.show_config()
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blis_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
lapack_mkl_info:
  NOT AVAILABLE
blas_mkl_info:
  NOT AVAILABLE
```

```
$ ldd /usr/local/lib/python3.5/dist-packages/numpy/core/multiarray.cpython-35m-x86_64-linux-gnu.so
	linux-vdso.so.1 =>  (0x00007ffccddc0000)
	libopenblasp-r0-39a31c03.2.18.so => /usr/local/lib/python3.5/dist-packages/numpy/core/../.libs/libopenblasp-r0-39a31c03.2.18.so (0x00007fa2087de000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa20849e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa20827e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa207eae000)
	/lib64/ld-linux-x86-64.so.2 (0x00005592c5b12000)
	libgfortran-ed201abd.so.3.0.0 => /usr/local/lib/python3.5/dist-packages/numpy/core/../.libs/libgfortran-ed201abd.so.3.0.0 (0x00007fa207bae000)
```

Debugger output (bug.py being the code I posted):
```
$ gdb -ex r --args python bug.py
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...(no debugging symbols found)...done.
Starting program: /usr/bin/python bug.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3eb9700 (LWP 58804)]
[New Thread 0x7ffff36b8700 (LWP 58805)]
[New Thread 0x7fffeeeb7700 (LWP 58806)]
[New Thread 0x7fffee6b6700 (LWP 58807)]
[New Thread 0x7fffebeb5700 (LWP 58808)]
[New Thread 0x7fffe96b4700 (LWP 58809)]
[New Thread 0x7fffe6eb3700 (LWP 58810)]
[New Thread 0x7fffe26b2700 (LWP 58811)]
[New Thread 0x7fffdfeb1700 (LWP 58812)]
[New Thread 0x7fffdf6b0700 (LWP 58813)]
[New Thread 0x7fffdeeaf700 (LWP 58814)]
[New Thread 0x7fffda6ae700 (LWP 58815)]
[New Thread 0x7fffd5ead700 (LWP 58816)]
[New Thread 0x7fffd36ac700 (LWP 58817)]
[New Thread 0x7fffd0eab700 (LWP 58818)]
[New Thread 0x7fffce6aa700 (LWP 58819)]
[New Thread 0x7fffcbea9700 (LWP 58820)]
[New Thread 0x7fffc96a8700 (LWP 58821)]
[New Thread 0x7fffc8ea7700 (LWP 58822)]
[New Thread 0x7fffc46a6700 (LWP 58823)]
[New Thread 0x7fffc1ea5700 (LWP 58824)]
[New Thread 0x7fffbf6a4700 (LWP 58825)]
[New Thread 0x7fffbcea3700 (LWP 58826)]
[New Thread 0x7fffbc6a2700 (LWP 58827)]
[New Thread 0x7fffb7ea1700 (LWP 58828)]
[New Thread 0x7fffb76a0700 (LWP 58829)]
[New Thread 0x7fffb2e9f700 (LWP 58830)]
[New Thread 0x7fffb069e700 (LWP 58831)]
[New Thread 0x7fffafe9d700 (LWP 58832)]
[New Thread 0x7fffab69c700 (LWP 58833)]
[New Thread 0x7fffaae9b700 (LWP 58834)]
[New Thread 0x7fffa869a700 (LWP 58835)]
[New Thread 0x7fffa3e99700 (LWP 58836)]
[New Thread 0x7fffa1698700 (LWP 58837)]
[New Thread 0x7fffa0e97700 (LWP 58838)]
[New Thread 0x7fff9c696700 (LWP 58839)]
[New Thread 0x7fff99e95700 (LWP 58840)]
[New Thread 0x7fff97694700 (LWP 58841)]
[New Thread 0x7fff96e93700 (LWP 58842)]
[New Thread 0x7fff92692700 (LWP 58843)]
[New Thread 0x7fff8fe91700 (LWP 58844)]
[New Thread 0x7fff8d690700 (LWP 58845)]
[New Thread 0x7fff8ae8f700 (LWP 58846)]
[New Thread 0x7fff8868e700 (LWP 58847)]
[New Thread 0x7fff85e8d700 (LWP 58848)]
[New Thread 0x7fff8368c700 (LWP 58849)]
[New Thread 0x7fff82e8b700 (LWP 58850)]
[New Thread 0x7fff7e68a700 (LWP 58851)]
[New Thread 0x7fff7be89700 (LWP 58852)]
[New Thread 0x7fff79688700 (LWP 58853)]
[New Thread 0x7fff76e87700 (LWP 58854)]
[New Thread 0x7fff74686700 (LWP 58855)]
[New Thread 0x7fff71e85700 (LWP 58856)]
[New Thread 0x7fff6f684700 (LWP 58857)]
[New Thread 0x7fff6ce83700 (LWP 58858)]
[New Thread 0x7fff6a682700 (LWP 58859)]
[New Thread 0x7fff67e81700 (LWP 58860)]
[New Thread 0x7fff65680700 (LWP 58861)]
[New Thread 0x7fff62e7f700 (LWP 58862)]
[New Thread 0x7fff6067e700 (LWP 58863)]
[New Thread 0x7fff5de7d700 (LWP 58864)]
[New Thread 0x7fff5b67c700 (LWP 58865)]
[New Thread 0x7fff58e7b700 (LWP 58866)]

Thread 2 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff3eb9700 (LWP 58804)]
0x00007ffff55c3320 in dgemv_t_PILEDRIVER () from /usr/local/lib/python2.7/dist-packages/numpy/core/../.libs/libopenblasp-r0-39a31c03.2.18.so
```
```
(gdb) bt
#0  0x00007ffff55c3320 in dgemv_t_PILEDRIVER () from /usr/local/lib/python2.7/dist-packages/numpy/core/../.libs/libopenblasp-r0-39a31c03.2.18.so
#1  0x0000000000000000 in ?? ()
```

Just a question so I don't make a fool out of myself, if eigsh runs out of memory (I don't think it is likely if it uses Lanczos), then how would I notice? Does it throw an exception or can I expect a segfault?

**Comment by kpws** [comment]
> You may want to
see if it also happens with a different blas/lapack library.

Since the sparse matrix is empty it doesn't use much memory. I can run the code on a basic laptop. I did this with the same version of openblas as above. Judging from htop it also ran in parallel. On this machine it doesn't give a segfault.

To make sure it is not just an issue for a large number of cpus I set OMP_NUM_THREADS=2 and it still crashes on the machine of my original report.

**Comment by pv** [comment]
Ok, sorry, I missed that you have a simpler testcase instead of the
lattice stuff. It doesn't crash for me (Ubuntu 17.10).

You may get a more informative traceback by using scipy recompiled with
debug symbols enabled:
```
python -mpip install numpy Cython Tempita
git clone https://github.com/scipy/scipy.git scipy
cd scipy
git checkout v1.0.1
OPT="-O0 -ggdb" python setup.py bdist_wheel
python -mpip install dist/scipy*.whl
```
(Note that python package index seems to have some problems at the
moment https://status.python.org/incidents/1y1f44q6srh2 so you may need
to download cython/etc manually...)

ARPACK doesn't do allocations inside fortran code, so it should fail
gracefully with Python error, not segfault.

Openblas may allocate some memory, and if that fails, it will probably
terminate the program.

**Comment by kpws** [comment]
I already have numpy and cython installed and skipped Tempita, what is it for? It seems like everything compiles anyways, with lots of warnings.
What does the -mpip flag do? I could not find it in the python man page. I would like to avoid installing anything non-standard outside of my home directory since others are using the same machine. After scipy is setup, is there a way to import it directly from my python script instead of installing it?

**Comment by pv** [comment]
https://docs.python.org/3/tutorial/venv.html
(if using python 2: https://virtualenv.pypa.io/en/stable/)

**Comment by lobpcg** [comment]
I suspect that you simply run out of memory.  

`eigsh` is an interface to ARPACK. The way you call it  `linalg.eigsh(sparse.coo_matrix((n,n)), k=1)` runs indeed the simple Lanczos method without shift-and-invert. However, ARPACK uses sophisticated internal operations (for stability reasons) with ncv=20 (in your case by default) vectors involved, even though you request to compute only one eigenvector, see https://github.com/scipy/scipy/blob/v1.1.0/scipy/sparse/linalg/eigen/arpack/arpack.py 

You may want to compare your
 
from scipy import sparse
from scipy.sparse import linalg
n=4075000
A= sparse.coo_matrix((n,n))
linalg.eigsh(A, k=1)

with 

import numpy as np
X = np.random.rand(n, 1)
eigs, vecs = linalg.lobpcg(-A, X)

which in this case should use only 6 vectors internally, I believe. I put `-A` here so that LOBPCG computes the smallest eigenvalue of -A, which is just negative to the largest eigenvalue of A computed by default in linalg.eigsh . I would strongly recommend testing linalg.lobpcg to check if it outperforms linalg.eigsh 

I suggest that this issue can be closed, since this is a normal expected behavior for ARPACK to run out of memory in such a test.

**Comment by ev-br** [comment]
Does not segfault for me with

```
In [3]: numpy.show_config()
openblas_lapack_info:
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    library_dirs = ['/usr/local/lib']
    libraries = ['openblas', 'openblas']
blas_mkl_info:
  NOT AVAILABLE
blas_opt_info:
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    library_dirs = ['/usr/local/lib']
    libraries = ['openblas', 'openblas']
blis_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
lapack_opt_info:
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    library_dirs = ['/usr/local/lib']
    libraries = ['openblas', 'openblas']
openblas_info:
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    library_dirs = ['/usr/local/lib']
    libraries = ['openblas', 'openblas']
```
and

```
$ ldd /home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-x86_64-linux-gnu.so 
	linux-vdso.so.1 =>  (0x00007ffded7ec000)
	libopenblasp-r0-8dca6697.3.0.dev.so => /home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/numpy/core/../.libs/libopenblasp-r0-8dca6697.3.0.dev.so (0x00007f4d385d2000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4d382c9000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4d380ac000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4d37ce2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4d3b0e7000)
	libgfortran-ed201abd.so.3.0.0 => /home/br/virtualenvs/scipy_py35/lib/python3.5/site-packages/numpy/core/../.libs/libgfortran-ed201abd.so.3.0.0 (0x00007f4d379e8000)
```

Did you have a chance to debug it further @kpws ? It seems that you're the only one who can repro this. I'm going to close, as suggested in https://github.com/scipy/scipy/issues/8741#issuecomment-421600652, please reopen if the issue persists.
