### ISSUE TITLE
scipy.ndimage.fourier.fourier_gaussian changed from versions 0.19.1 to 1.0.1

### ISSUE THREAD

**Issue by wd15** [scipy/scipy#8747]
`fourier_gaussian` output has changed from version 0.19.1 to 1.0.1.

Running the following code produces a zero value for version 1.0.1

    fourier_gaussian(numpy.ones([1, 1]), 1)

but a value of one for older versions of Scipy (0.19.1 and earlier).

### Reproducing code example:

```
from scipy.ndimage.fourier import fourier_gaussian
import numpy
import scipy

print('numpy version:', numpy.__version__)
print('scipy version:', scipy.__version__)
print('fourier_gaussian:', fourier_gaussian(numpy.ones([1, 1]), 1))
```

### Scipy/Numpy/Python version information:

New version:

    1.0.1 1.14.2 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)

Old version:

    0.19.1 1.13.1 sys.version_info(major=3, minor=6, micro=2, releaselevel='final', serial=0)

### Builds

This was tested with both Conda and Nix builds. The scripts to build the Nix environments are [here](https://github.com/wd15/nixes/tree/master/scipy-bug).

**Comment by rgommers** [comment]
@jaimefrio do you remember if this was on purpose?

**Comment by rgommers** [comment]
this was fixed/reverted at some point:
```
numpy version: 1.16.4
scipy version: 1.4.0.dev0+90be8ae
fourier_gaussian: [[1.]]

```
