### ISSUE TITLE
UserWarning: endian-ness of dtype and endian kwarg do not match, using endian kwarg

### ISSUE THREAD

**Issue by AgilentGCMS** [scipy/scipy#8767]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
The `createVariable` method of netCDF4.Dataset seems to have a problem with numpy arrays having dtype `<f8`. I discovered this when in my code I saved a `float64` array to an HDF5 file, read it back to an array, then tried saving it to a netcdf file. The MWE below requires h5py to be installed.

### Reproducing code example:
```
import numpy as np
import h5py
from netCDF4 import Dataset

a = np.float64(np.random.standard_normal((12,7)))

# save this to a HDF5 file
with h5py.File('demo.h5', 'w') as fid:
    _ = fid.create_dataset('emission_data', data=a)

# read the HDF5 file
with h5py.File('demo.h5', 'r') as fid:
    b = fid['emission_data'][:]

# now save them to a netcdf file
with Dataset('demo.nc', 'w') as fid:
    fid.createDimension('dim1', a.shape[0])
    fid.createDimension('dim2', a.shape[1])
    v = fid.createVariable('data_a', a.dtype, ('dim1','dim2'))
    v[:] = a
    v = fid.createVariable('data_b', b.dtype, ('dim1','dim2'))
    v[:] = b

```

### Error message:
```
netcdf-python-problem.py:21: UserWarning: endian-ness of dtype and endian kwarg do not match, using endian kwarg
  v = fid.createVariable('data_b', b.dtype, ('dim1','dim2'))
```

### Scipy/Numpy/Python version information:
```
In [2]: import netCDF4
In [3]: netCDF4.__version__
Out[3]: '1.3.1'
In [4]: import numpy as np
In [5]: np.__version__
Out[5]: '1.14.2'
In [6]: import h5py
In [7]: h5py.__version__
Out[7]: '2.8.0rc1'
```

This is on python 2.7.14. It can be verified that `a.dtype` gives `dtype('float64')`, while `b.dtype` gives `dtype('<f8')`, and `createVariable` seems to have a problem with the latter.

**Comment by ilayn** [comment]
You might want to report this to NumPy repository for a more suitable audience. https://github.com/numpy/numpy/issues
