### ISSUE TITLE
ValueError: The condensed distance matrix must contain only finite values.

### ISSUE THREAD

**Issue by shuchitagupta** [scipy/scipy#8770]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
I am trying to run CMT tracking code and continuously getting raiseValue error.

### Reproducing code example:
```
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```

### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>
 linkage = scipy.cluster.hierarchy.linkage(pdist)
  File "/home/shuchita/.virtualenvs/cv3/lib/python3.5/site-packages/scipy/cluster/hierarchy.py", line 713, in linkage
    raise ValueError("The condensed distance matrix must contain only "
ValueError: The condensed distance matrix must contain only finite values.
```
### Scipy/Numpy/Python version information:
``` 
Version - 1.0.1
```

**Comment by rgommers** [comment]
not a bug, something is wrong with the inputs to the function.

if you're really convinced it's a bug, please provide a reproducible example
