### ISSUE TITLE
does cdist perform a copy of the input arrays?

### ISSUE THREAD

**Issue by agenoves** [scipy/scipy#8771]
https://github.com/scipy/scipy/blob/11509c4a98edded6c59423ac44ca1b7f28fba1fd/scipy/spatial/distance.py#L2060-L2452

while using cdist with multiprocessing, jobs are all *reading only* from a global numpy array then perform a cdist. When the array is big, memory grows so much that I concluded that cdist must perform a copy of the original arrays somehow. Can you confirm it? If this is the case wouldn't it be possible to optionaly not do this ?

**Comment by perimosocordiae** [comment]
It's possible that a copy is happening, depending on some properties of `XA` and `XB`:

 - do they have compatible dtypes? For most metrics, that's going to be `np.float64`. Any other dtype will trigger a copy.
 - are they contiguous and C-ordered? If not, expect a copy.
 - are they views of a parent array? (That is, is `XA.base` or `XB.base` not `None`?) If so, expect a copy.

**Comment by apbard** [comment]
Also, are you using `out` option? If not, is it possible that you are seeing multiple allocation of out matrix?

**Comment by rgommers** [comment]
question is answered, so closing. thanks all
