### ISSUE TITLE
erroneous moment values for t-distribution

### ISSUE THREAD

**Issue by tcrensink** [scipy/scipy#8786]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

Moments of the t-distribution return incorrect values.  See: https://en.wikipedia.org/wiki/Student%27s_t-distribution
- for df <= 1, the mean should be undefined
- for df < 1, the variance should be undefined 

Example:
```
from scipy import stats
X = stats.t(df=0.8)
X.mean() # returns 0
X.var() # returns inf
```

### Scipy/Numpy/Python version information:
`1.0.0 1.14.0 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)`

**Comment by josef-pkt** [comment]
AFAIK, the variance is inf and not undefined.
kurtosis is undefined because it divides by var (inf / inf)

**Comment by josef-pkt** [comment]
I take this back
because the mean is undefined for df <= 1, the var also has to be undefined
