### ISSUE TITLE
`stats.pearsonr` documentation needs more information

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#8789]
This issue is inspired by [a question on stackoverflow](https://stackoverflow.com/questions/50092490/how-scipy-calculates-the-p-value-in-pearsonr-function).  There are two important pieces of information missing from the docstring of `scipy.stats.pearsonr`:

1. How is the p value calculated?  (Answer: the t-distribution is used, as explained, for example, in [the wikipedia page on Student's t-distribution](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient#Testing_using_Student's_t-distribution).)
2. What is the source of the statement *"The p-values are not entirely reliable but are probably reasonable for datasets larger than 500 or so."*? The source should be cited with a reference in the docstring.

I have tagged this issue as a "good first issue".  No coding is required to fix this,  but it might require digging into references or standard texts to find a source for the quote about the size of the datasets.  If we can't find a source for the number 500, than we should replace that statement with something similar for which we *can* provide a reference.

**Comment by singhai0** [comment]
I could not find any sources that agreed with the idea that the Pearson correlation values are _reasonable_ for datasets with n>500.

What I did find was a [paper](https://link.springer.com/article/10.1007/BF02294183) which talks about setting up sample size requirements when using correlation estimators. The paper cites a [1938 text](https://books.google.com/books/about/Tables_of_the_ordinates_and_probability.html?id=oCa2AAAAIAAJ) that says, "David (1938) recommends the use of (2) for Pearson correlations only if n >= 25."

David's text might offer more information, but I do not have access to it. I have placed a request for it through my library's interlibrary loan service, and will post a comment once I get my hands on it.

cc @WarrenWeckesser 

disclaimer: I'm a beginner in statistics, having just worked through some textbooks on the subject, so I'm not entirely sure what my interpretation of the literature will achieve. I hope I'm not creating noise by poking nose in topics I know little about. Please let me know if that is the case. Thanks. 🙇

**Comment by WarrenWeckesser** [comment]
Thanks for looking into this.  Let us know what else you find.

**Comment by mvinoba** [comment]
@singhai0  I've found a recent paper on this subject: [Practical Issues in Sample Size Determination for Correlation Coefficient Inference](http://smjournals.com/biometrics-and-biostatistics/download.php?file=fulltext/smjbb-v3-1027.pdf). Even though I'm not a statistics expert, given the complexity of determining a fixed minimum sample size addressed on the paper, I wonder if it's of any use at all to provide this information on the docstring.

**Comment by grassknoted** [comment]
Hey, could I work on this issue if you feel the docstring needs to be updated?

**Comment by chrisb83** [comment]
I think the statement "The p-values are not entirely reliable but are probably reasonable for datasets larger than 500 or so." should be removed. 

While in general, the test appears to be relatively robust to non-normal data (conclusion of many early papers on this), it does not hold for data that deviates strongly from normality (and even for large sample sizes do not help much in this case), see Kowalski (this paper gives a good overview of the literature), also Duncan and Layard. 

C.J. Kowalski: On the Effects of Non-Normality on the Distribution of the Sample Product-Moment Correlation Coefficient.Journal of the Royal Statistical Society. Series C (Applied Statistics) 
Vol. 21, No. 1 (1972), pp. 1-12 

Duncan, G. T., & Layard, M. W. J. (1973). A Monte-Carlo study of asymptotically robust tests for correlation coefficients. Biometrika, 60, 551-558. 

Other references: 
Bishara, A. J., & Hittner, J. B. (2012). Testing the significance of a correlation with non-normal data: Comparison of Pearson, Spearman, transformation, and resampling approaches. Psychological Methods, 17, 399-417

PhD thesis: 
Yi-Ju Chen: ROBUSTNESS PROPERTIES OF GENERALIZED CORRELATION COEFFICIENTS, WITH APPLICATIONS TO CROSS-OVER DESIGNS

**Comment by WarrenWeckesser** [comment]
@chrisb83 wrote

> I think the statement "The p-values are not entirely reliable but are probably reasonable for datasets larger than 500 or so." should be removed.

I agree.  While it is nice to include some advice about the applicability of a function in its docstring, it is certainly not necessary, and we definitely should not be giving unsubstantiated adivce.  If we don't have a specific reference for that claim, let's just take it out.

**Comment by chrisb83** [comment]
Closed in 9562

**Comment by bradknox** [comment]
Hi. I found this conversation after a ton of confusion from that line in the docs. It appears to [still be there in master](https://github.com/scipy/scipy/blob/master/scipy/stats/stats.py) (commit d92e048) and in the [online docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.spearmanr.html).

Also, the assertion is ambiguously written, as [this questioner points out on stackoverflow](https://stats.stackexchange.com/questions/294586/reliability-of-p-value-in-scipy-stats-spearman). We took it to mean that <=500 is unreliable and >500 are "probably reasonable". But perhaps it was supposed to mean that <=500 is reliable and >500 is "not entirely reliable but are probably reasonable". Those are very different interpretations in terms of what use cases they recommend.
