### ISSUE TITLE
Documentation building is not well documented

### ISSUE THREAD

**Issue by adbugger** [scipy/scipy#8794]
I recently tried to build the docs locally with sphinx for my GSoC 2018 project and I ran into a couple of issues:
1. Sphinx is not listed as a dependency anywhere. It would be good if it was listed along with Numpy, Cython, and pytest in HACKING.rst.txt.

2. The scipy setup instructions do not contain the `git submodule init` step which is required to initialise the `numpydoc` sub-directory under `scipy/doc/sphinxext`. It is unclear from the online instructions, but `numpydoc` need not be installed in the host environment, it is always run from this sub-directory.

3. I couldn't find any document online which said that `python3` is required for building the docs. Further, the Makefile tries to find the correct python binary by simply appending `PYVERS` variable with `python`. That may not always work since people often work in virtual environments. For example, I was running `python3.5.2` under the binding `python`, or `python3` so simply doing `PYVERS=3.5` was looking for the binary outside of the local environment. Using the `PYTHON` Makefile variable solved this issue. I believe this could also be better documented.

4. The version of `numpydoc` shipping with the main scipy repo has a faulty import line in `line 32` of file `/scipy/doc/sphinxext/numpydoc/numpydoc.py`. That issue is described below.

### Reproducing code example:
Descend into the doc directory `/scipy/doc/` and try building the docs with:
```
make html-scipyorg PYTHON=/home/aditya/scipy-dev/bin/python3
```

### Error message:
```
mkdir -p build/html build/doctrees
LANG=C /home/aditya/scipy-dev/bin/python3 /home/aditya/scipy-dev/bin/sphinx-build -t scipyorg -b html -d build/doctrees   source build/html-scipyorg 
Running Sphinx v1.7.4
Scipy (VERSION 1.2.0.dev0+e0effe7)

Extension error:
Could not import extension numpydoc (exception: cannot import name 'Directive')
Makefile:107: recipe for target 'html-scipyorg' failed
make: *** [html-scipyorg] Error 2

```

### Scipy/Numpy/Python version information:
```
scipy.__version__ : 1.2.0.dev0+e0effe7
numpy.__version__ : 1.14.3
sys.version_info : sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
```

That issue was resolved with changing the faulty import line from
```
from sphinx.util.compat import Directive 
```
to 
```
from docutils.parsers.rst import Directive
```

Also note that the latest pip version of numpydoc does not have this faulty import line.

**Comment by adbugger** [comment]
Mentioning @rgommers as per the email

**Comment by larsoner** [comment]
Assigning to @rgommers so we don't forget to take care of it. But @adbugger do you have time to make a PR to fix some or all of these issues?

Regarding the `numpydoc` one, the best thing to do is probably to update the version of `numpydoc` we use.

**Comment by adbugger** [comment]
@larsoner sure, I have time to try to fix the issues. I was thinking of adding a section for building the documentation. Could you point me to the right place for such modifications?

For updating the version of numpydoc, I can see that the `.gitmodules` file has no version number in it, just a url. How would I update the numpydoc version?

**Comment by larsoner** [comment]
I don't know, haven't worked with `git submodule` much. Can you do some reading about `git submodule` and try some things to see if you can get it to work?

**Comment by ilayn** [comment]
Typically you do `git submodule update --init` but I'm not sure why you would need it.

**Comment by adbugger** [comment]
I tried `git submodule update --init` but that did not work. I'll keep looking into it.

**Comment by adbugger** [comment]
So it appears that `git submodule update` checks out the commit specified in the index of the super-project (in this case scipy). To update the submodule to _its_ latest version, we need to do:

- `cd doc/sphinxext`
- `git checkout master` : This checks out branch `master` from the `numpydoc.git` remote source
- `git pull origin master` : This updates the submodule directory
- `git commit -m "Updated submodule"` : To commit the submodule version to parent super-project. After this, all `git submodule update`s will check out this version of `sphinxext`

With these changes I'm able to build the docs successfully without any modifications and `python runtests -v` also seems fine:
`13067 passed, 1290 skipped, 585 deselected, 84 xfailed, 8 xpassed in 408.86 seconds`

@rgommers, since there are no source code modifications, does this require a pull request or can you make the changes in the main repo yourself and the rest of us can pull the updates?

**Comment by larsoner** [comment]
If you modify your instructions:

...
- `git pull origin master`
- `cd ..` : get to doc/ directory
- `git commit -am "Updated submodule"` : commit to scipy repo (note the addition of "a")
- `git push origin ...` push changes
- open PR

Then @adbugger I think that you should be able to make a PR yourself, and we can see how the CIs handle it.
