### ISSUE TITLE
Problems with odeint and 

### ISSUE THREAD

**Issue by LuisPaAl** [scipy/scipy#8796]
Hello everybody,

 0
down vote
favorite

I have been working with odeint and boundary conditions. Basically what I am trying to do is to solve the differential equations given in this figure 
![difeq](https://user-images.githubusercontent.com/31632132/39567304-29ef6344-4e84-11e8-82c2-de8ede426b16.png)

where in my code R=R, ph = Phi, al = alpha, a = a, m = m, l = l and om = omega. The initial conditions that I am trying to implement are R(0)=O(r^l); Phi(0)=O(r^{l-1}) if l/=0 and Phi(0)=O(r) if l=0; a(0) = 1 and a(inf)=1/alpha(inf) (additionally I need that R(inf)=0). I tried to applied the shooting method in order to find initial conditions for alpha that best matches with my boundary conditions. I also need to find the omega that best matches the boundary conditions for R at infinity. The code that I wrote is the following:

    import numpy as np
    import matplotlib.pyplot as plt
    from scipy.integrate import odeint
    import time
    
    def system_DE(IC,r,l,m,om):    
        R = IC[0]
        ph = IC[1]
        a = IC[2]
        al = IC[3]
        
        dR_dr = ph
        da_dr = a*((2*l+1)*r/2*(om**2*a**2*R**2/al**2+ph**2+l*(l+1)*a**2*R**2/r**2+m**2*a**2*R**2)-(a**2-1)/(2*r))
        dal_dr = al*(da_dr/a-l*(l+1)*(2*l+1)*a**2*R**2/r-(2*l+1)*m**2*a**2*r*R**2+(a**2-1)/r)
        dph_dr = -2*ph/r-dal_dr*ph/al+da_dr*ph/a-om**2*a**2*R/al**2+l*(l+1)*a**2*R/r**2+m**2*a**2*R
        
        return [dR_dr,dph_dr,da_dr,dal_dr]
    
    def init(u,p,r):
        if p==0:
            return np.array([1.,r,1.,u])
        else:
            return np.array([r**p,l*r**(p-1),1,u])
    
     
    l = 0.
    m = 1.
    ep = 0.2
    n_om = 30  
    omega = np.linspace(m-ep,m+ep,n_om)
    r = np.linspace(0.001, 100, 1000)
    
    
    niter = 1000
    tol = 0.01
    ustep = 0.01
     
    for j in range(len(omega)):
        print('trying with $omega =$',omega[j])
        p = (l,m,omega[j])
        u = 0.001
        for i in range(niter):
            u += ustep
            ini = init(u,p[0],r[0])
            Y, info = odeint(system_DE, ini,r,args=(p),mxstep=500000,full_output = True)
            if abs(Y[len(Y)-1,2]-1/Y[len(Y)-1,3]) < tol:
                break
        if abs(Y[len(Y)-1,0]) < tol and abs(Y[len(Y)-1,2]-1/Y[len(Y)-1,3]) < tol:
            print(j,'times iterations in omega')
            print(i,'times iterations')
            print("R'(inf)) = ", Y[len(Y)-1,0])        
            print("alpha(0)) = ", Y[0,3])
            print("\omega",omega[j])
            break
    
    plt.subplot(2,1,1)
    plt.plot(r,Y[:,0],'r',label = '$R$')
    plt.plot(r,Y[:,1],'b',label = '$d R /dr$')
    plt.xlim([0,10])
    plt.legend()
    plt.subplot(2,1,2)
    plt.plot(r,Y[:,2],'r',label = 'a')
    plt.plot(r,Y[:,3],'b', label = '$alpha$')
    plt.xlim([0,10])
    plt.legend()
    plt.show()

But when I run it I am obtaining this:

`lsoda--  warning..internal t (=r1) and h (=r2) are
   such that in the machine, t + h = t on the next step  
   (h = step size). solver will continue anyway
  in above,  r1 =  0.1243782486482D+01   r2 =  0.8727680448722D-16`

I have to say that the code can solve the system and it can give me the plots that I am plotting. I also can see that the conditions at infinity are fulfilled for the solutions that I am obtaining. However, I suppose that the warning that I am obtaining (several time) is not normal and then my solutions are not correct. Then, could some one help me to solve the problem? 

Another question that I have is if is there a way to know how accurate is my solution? Is there a way to know how big the errors of my solution are? Could you recommend me the best way to solve my system of differential equations?

Thank you very much for the help.

Regards,

Luis Padilla.

**Comment by ev-br** [comment]
Indeed, it seems that LSODA has issues with the step size underflow. You may want to check how `solve_ivp` fares on your problem. This seems to be a usage question, which is best asked on StackOverflow / Comp Sci Stackexchange or the scipy-user mailing list: way more eyes will see your question.
