### ISSUE TITLE
basic.py: RuntimeWarning: invalid value encountered in cdouble_scalars

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#8798]
I am getting this error when using Bessel functions with the latest scipy.    I can't find any simple way to debug it.   The inputs to the function look valid.

```
/usr/local/lib/python3.4/dist-packages/scipy/special/basic.py:428: RuntimeWarning: 
invalid value encountered in cdouble_scalars
  s += p*L(v-n + i*2, z)
```

**Comment by ilayn** [comment]
Unfortunately, without the actual code this is not informative for us to understand the problem. We can at best guess which is not the most productive way to debug.

You might try to record the variables that causes the problem and figuring out which function is emitting this.
