### ISSUE TITLE
stats.stats.uniform not an instance of stats.rv_continuous

### ISSUE THREAD

**Issue by stsievert** [scipy/scipy#8807]
I would expect `stats.uniform` to be an instance of `stats.rv_continuous`. The [docstring of stats.uniform] supports this:

> As an instance of the rv_continuous class ...

[docstring of stats.uniform]:https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.uniform.html#scipy.stats.uniform

However,

``` python
>>> isinstance(stats.uniform(0, 1), stats.rv_continuous)
False
```

How can I get `isinstance` functionality?

Version info:

* SciPy version: 1.0.1
* NumPy version: 1.14.2
* Python version: 3.6.3

**Comment by andyfaff** [comment]
`stats.uniform(0, 1)` creates an `rv_frozen` object. `stats.uniform` is the `rv_continuous` subclass.

```
>>> isinstance(stats.uniform, stats.continuous)
True
```

**Comment by andyfaff** [comment]
The documentation states that the `stats.uniform` object is an instance of the `rv_continuous` class. It then goes onto say that:

```
Alternatively, the distribution object can be called (as a function) to fix the shape, location and scale parameters. This returns a “frozen” RV object holding the given parameters fixed.
```

This is what you've done by calling `stats.uniform` as a function. So the uniform object is a subclass of `rv_continuous`, but when you call the object it returns an `rv_frozen`.

From my interpretation I think the documentation is correct here.

**Comment by stsievert** [comment]
This came up because `stats.uniform(a, b)` is user specified, and I'm receiving this value inside some function.

The solution to this is to call `type` on a dummy `rv_frozen` variable:

``` python
u = stats.uniform(0, 1)
isinstance(stats.uniform(a, b), type(u))
```

The explicit call to `type` avoids the underscore in `type(u)`, which is `scipy.stats._distn_infrastructure.rv_frozen` in v1.0.1.

The docs are accurate, but not concise. I'll add a paragraph.
