### ISSUE TITLE
[BUG] GMRES: number of iteration is only increased if callback is provided

### ISSUE THREAD

**Issue by georgh** [scipy/scipy#8815]
GMRES behaves different if you provide a callback or not. This shouldn't be the case, callback is only for debug purpose.
Reson for the difference is 
```
if resid_ready and callback is not None:
                callback(presid / bnrm2)
                resid_ready = False
                iter_num = iter_num+1
```
(See https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/isolve/iterative.py#L566-L569)
iter_num is only increased if callback is not None.
If  you do not provide a callback, the parameter maxiter has no effect and GMRES will only stop if it converges or breaks down (which may take a lot more then maxiter iterations).

If I find the time I might create a pr, but I failed to build scipy on my system - might take some time until I get that right. If you have the time please do it :)

Note: callback does report the norm of the residual not the vector, as noted at #7623. 
Documentation should be changed accordingly. 

### Scipy/Numpy/Python version information:
```
Observed with 1.0.1 and 1.1 but error is in the Code in master, as linked above
```

**Comment by georgh** [comment]
Thank you for your reply. Sorry I overlocked that. (https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/isolve/iterative.py#L539 for anyone wondering)
Nevertheless, is the behaviour fastly different for me, if I set a callback or not. 
So I guess fortran doesn't care, even if the value is set?

**Comment by pv** [comment]
Do you have an example case that does not converge at all without `callback`? Note that without `callback=` given, the `maxiter` counts the number of *outer* GMRES iterations, so it's `restart` times more iterations (the default is `restart=20`)?

(Asking, because https://github.com/scipy/scipy/issues/1255 that fixed this wrong 10 years ago seems to also claim it does not terminate, but without example.)

**Comment by pierreXVI** [comment]
Hi! I hope reporting what I found will help, even if this thread is quite old.

It seems that if a ``callback`` is given, ``maxiter`` is the maximum number of iterations, but if ``callback`` is not given, ``maxiter`` is the maximum number of restart cycles, and the maximum number of iterations is then ``maxiter * restart``.

The documentation is not really clear about which one it should be : _``maxiter`` : Maximum number of iterations (restart cycles)_.

Anyhow, I don't think the meaning of this parameter should depend on whether or not a ``callback`` is given.
This script is a good illustration :
```
import numpy as np
from scipy.sparse.linalg import gmres

def foo_function(a, b, maxiter, restart):
    def callback(rk):
        pass
    x1, _ = gmres(a, b, restart=restart, maxiter=maxiter, callback=callback)
    x2, _ = gmres(a, b, restart=restart, maxiter=maxiter / restart)
    print("x1 == x2 :", (x1 == x2).all())


if __name__ == '__main__':
    A = ...
    n, _ = A.shape
    B = A.dot(np.ones((n,)))
    maxiter, restart = ..., ...
    foo_function(A, B, maxiter, restart)
```
where in my case ``A`` is a large sparse matrix read from a binary file.
I've tried for some values of ``maxiter`` and ``restart``, and I always get :
```
x1 == x2 : True
```

**Scipy/Numpy/Python version information:**

```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.3.0 1.16.3 sys.version_info(major=3, minor=5, micro=7, releaselevel='final', serial=0)
```
