### ISSUE TITLE
v1.1 psi(0) == -inf, while v1.0 psi(0) == inf

### ISSUE THREAD

**Issue by DickJC123** [scipy/scipy#8819]
psi(0) could be thought of as being +inf or -inf (or consequently undefined?).  The question raised with this issue is whether scipy wants to return a consistent value across versions, or at least document changes in behavior.

So right before submitting this, I found the PR https://github.com/scipy/scipy/pull/3902.  Despite the complete discussion of the matter, I decided to create the issue anyway to suggest that perhaps the documentation should mention this change in behavior across versions?

### Reproducing code example:
```
$ python -c "import numpy; print(numpy.__version__)"
1.14.3
$ python -c "import scipy; print(scipy.__version__)"
1.0.0
$ python -c "import scipy.special; print(scipy.special.psi(0))"
inf

$ sudo pip install scipy==1.1 --force-reinstall
$ python -c "import numpy; print(numpy.__version__)"
1.14.3
$ python -c "import scipy; print(scipy.__version__)"
1.1.0
$ python -c "import scipy.special; print(scipy.special.psi(0))"
-inf             <------------  Note minus inf, different than with scipy v1.0

```

### Scipy/Numpy/Python version information:
```
$ python -c 'import sys; print(sys.version_info)'
sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
```

**Comment by DickJC123** [comment]
To help make psi() more consistent, or at least document the change in behavior, I explored the psi() return values for inputs around 0, -1, -2 and -3. It might be nice if the known relation  psi(z+1) = psi(z) + 1/z holds for psi()'s return values.  Psi() under v1.0 for arguments 0, -1, -2 and -3 returns a consistent +inf, the value approached from the left on the negative real axis.  Psi() under v1.1 returns nan for inputs -1, -2 and -3, and returns -inf for an input of 0, where by the formula you'd expect possibly:
```
psi(0) = psi(-1) - 1 = nan - 1 = nan
```
On scipy 1.0:
```
$ python
>>> import scipy.special
>>> scipy.special.psi([[0 - 1e-5, 0, 0 + 1e-5],
...                    [-1 - 1e-5, -1, -1 + 1e-5],
...                    [-2 - 1e-5, -2, -2 + 1e-5],
...                    [-3 - 1e-5, -3, -3 + 1e-5]])
array([[  99999.42276789,              inf, -100000.57719922],
       [ 100000.42275723,              inf,  -99999.57718967],
       [ 100000.92275473,              inf,  -99999.07718606],
       [ 100001.25608695,              inf,  -99998.74385162]])
>>> 
```
And on scipy 1.1:
```
python
>>> import scipy.special
>>> scipy.special.psi([[0 - 1e-5, 0, 0 + 1e-5],
...                    [-1 - 1e-5, -1, -1 + 1e-5], 
...                    [-2 - 1e-5, -2, -2 + 1e-5],
...                    [-3 - 1e-5, -3, -3 + 1e-5]])
array([[  99999.42276789,             -inf, -100000.57719922],
       [ 100000.42275723,              nan,  -99999.57718923],
       [ 100000.92275473,              nan,  -99999.07718531],
       [ 100001.25608695,              nan,  -99998.74385087]])
>>> 
```

**Comment by person142** [comment]
>  The question raised with this issue is whether scipy wants to return a consistent value across versions, or at least document changes in behavior.

I see the change in values as a bugfix in this particular case. Documenting things never hurts though; I'd happily merge a PR documenting the changes.

> It might be nice if the known relation psi(z+1) = psi(z) + 1/z holds for psi()'s return values

The current implementation is based on right/left limits, so we have

```
>>> sc.psi(0.0)
-inf
>>> sc.psi(-0.0)
inf
```

We only have one representation for negative integers and the limits don't agree, so we have to return NaN. I believe this is the "standard" way of doing things.

**Comment by person142** [comment]
Closing-I probably should have noted the change in the release notes, but that ship has sailed now.
