### ISSUE TITLE
Initialization of coo matrix with non-float arguments yields float index error

### ISSUE THREAD

**Issue by AetherUnbound** [scipy/scipy#8823]
When initiating a sparse coordinate matrix with 3 `uint64` arrays (with the 3rd instantiation as defined [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html)), the `coo_matrix` call fails with a `numpy.float64` indexing error. The issue does **not** happen for `uint32` and below. 

I've pinned this down to some potentially unexpected behavior (I might need to escalate this to numpy? not sure) in `coo.py`, specifically where the `M` and `N` are calculated: https://github.com/scipy/scipy/blob/master/scipy/sparse/coo.py#L148

```
>>> s = np.ones(200).astype(np.uint32)
>>> np.max(s)
1
>>> np.max(s) + 1
2
>>> s = np.ones(200).astype(np.uint64)
>>> np.max(s)
1
>>> np.max(s) + 1
'2.0'
```

The way arithmetic operations are done on a `max(<uint64>)` appear to cast the return value as not only a float, but a float within a string. 

### Reproducing code example:
```
>>> import scipy.sparse as sp
>>> import numpy as np
>>> a = np.ones(200).astype(np.uint64)
>>> b = np.ones(200).astype(np.uint64)
>>> obj = np.ones(len(a), dtype=np.uint64)
>>> sp.coo_matrix((obj, (a, b)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aether/programs/anaconda3/envs/cp3testnp14-3/lib/python2.7/site-packages/scipy/sparse/coo.py", line 150, in __init__
    self._shape = check_shape((M, N))
  File "/home/aether/programs/anaconda3/envs/cp3testnp14-3/lib/python2.7/site-packages/scipy/sparse/sputils.py", line 281, in check_shape
    new_shape = tuple(operator.index(arg) for arg in args)
  File "/home/aether/programs/anaconda3/envs/cp3testnp14-3/lib/python2.7/site-packages/scipy/sparse/sputils.py", line 281, in <genexpr>
    new_shape = tuple(operator.index(arg) for arg in args)
TypeError: 'numpy.float64' object cannot be interpreted as an index
```

### Error message:
```
TypeError: 'numpy.float64' object cannot be interpreted as an index
```

### Scipy/Numpy/Python version information:
```
('1.1.0', '1.14.3', sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0))
```

**Comment by AetherUnbound** [comment]
What would you suggest changing about the shape check?

**Comment by v0dro** [comment]
The following code passes on the current main branch (macOS):
``` python

        a = np.ones(200).astype(np.uint64)
        b = np.ones(200).astype(np.uint64)
        obj = np.ones(len(a), dtype=np.uint64)
        coo_matrix((obj, (a, b)))
```

@rgommers should we close this?

**Comment by rgommers** [comment]
This is indeed all fixed. The second part of the issue description now gives a float (`2.0`) rather than a string with that value:
```python
>>> s = np.ones(200).astype(np.uint64)
>>> np.max(s)
1
>>> np.max(s) + 1
2.0
```

Closing. Thanks for the detailed report @AetherUnbound, and for looking into it @pv and @v0dro.
