### ISSUE TITLE
How does the function scipy.stats.trapz.rvs work?

### ISSUE THREAD

**Issue by ndkator** [scipy/scipy#8824]
I can not find the function code rvs. Please, help!

That's what I know. The function is called as follows: rvs (c, d, loc = 0, scale = 1, size = 1, random_state = None), where loc, scale are the offset and scale parameters, respectively. Also from the documentation I read that trapz takes c and d as shape parameters.

Here's what help does:
rvs (self, * args, ** kwds)
| | Random variates of given type.
| |
| | Parameters
| | ----------
| | arg1, arg2, arg3, ...: array_like
| | The shape parameter (s) for the distribution (see docstring of the
| | instance object for more information).
| | loc: array_like, optional
| | Location parameter (default = 0).
| | scale: array_like, optional
| | Scale parameter (default = 1).
| | size: int or tuple of ints, optional
| | Defining the number of random variates (default is 1).
| | random_state: None or int or `` np.random.RandomState`` instance, optional
| | If int or RandomState, use it for drawing the random variates.
| | If None, rely on `` self.random_state``.
| | Default is None.
| |
| | Returns
| | -------
| | rvs: ndarray or scalar
| | Random variates of given `size`.

But where is the specific code of this function ?!

**Comment by andyfaff** [comment]
The code for `trapz` is [here](https://github.com/scipy/scipy/blob/master/scipy/stats/_continuous_distns.py#L5606)
The `rvs` method is provided by the superclass, and is used to sample random variates. I think the code for that is [here](https://github.com/scipy/scipy/blob/master/scipy/stats/_distn_infrastructure.py#L879).
Do you have a specific issue (bug) with the code (usage questions are better directed to the scipy user ML)?
