### ISSUE TITLE
Second query about scipy.stats.trapz.rvs

### ISSUE THREAD

**Issue by ndkator** [scipy/scipy#8825]
I'm sorry, but I'm definitely upset!
Even after reading the documentation given [here](https://github.com/scipy/scipy/issues/8824), I did not understand how the rvs function works!

What kind of magic happens when filling out a list of values?
I would like to see a flowchart if possible!

My code:
`print('\nTrapezoidal distribution')
N = 150000
INTERVAL = 50
scale = 1 
c, d = 0.1, 0.7
r = trapz.rvs(c, d, loc, scale-loc, size = N)
print(r)

plt.hist(r, INTERVAL, histtype='bar', rwidth=0.8)
plt.xlabel('Intervals')
plt.ylabel('Values')
plt.title('Hist')
plt.show()`

**Comment by pv** [comment]
This is not a bug report. You can ask questions of this type on the mailing lists or on stackoverflow.

**Comment by WarrenWeckesser** [comment]
@ndkator Thanks for your interest in the code!  There is no need to open another issue with the same question.  @pv has given a couple good suggestions for your query.  You can also continue the discussion in the original issue (https://github.com/scipy/scipy/issues/8824).  When we close an issue, it doesn't mean further comments there will be ignored.

**Comment by ndkator** [comment]
Thx!
