### ISSUE TITLE
Facing problem during Scrapy's installation :(  

### ISSUE THREAD

**Issue by muhammadhammadlatif** [scipy/scipy#8831]
**error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools**

i'm getting this error while installing scrapy on my pc.. i've tried virtualenv and direct installation but getting the same error. 

**details that was given to me at the end after this error is as follows:**

Command "c:\users\hadi\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\hadi\\AppData\\Local\\Temp\\pip-install-lqv3uuc1\\Twisted\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\hadi\AppData\Local\Temp\pip-record-7_q2wpop\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\hadi\AppData\Local\Temp\pip-install-lqv3uuc1\Twisted\

please help me to sort this thing out. will be grateful. Thanks

**Comment by ilayn** [comment]
This doesn't look like anything related to SciPy. You might want to ask Twisted people about this. https://github.com/twisted/twisted
