### ISSUE TITLE
segmentation fault for LU decomposition of large matrices

### ISSUE THREAD

**Issue by sebvel** [scipy/scipy#8841]
Hi,
I want to solve a very large, sparse and unsymmetric system of linear equations (corresponding matrix size is >10^7 times 10^7 with around 10 entries per row). Therefore I use either the direct LU decomposition  with scipy.sparse.linalg.spsolve (if the problem size is 10^6 times 10^6), or, for very large problems, a bicgstab procedure with incomplete LU decomposition as preconditioner with scipy.sparse.linalg.spilu and subsequently scipy.sparse.linalg.bicgstab. With a certain problemsize of 9*10^6 I get the error message "segmentation fault". The problem occurs even if I do the calculation via ssh on a compute with 250 Gb Ram at the same problem size, so does not seem to be the case, that working memory is at its limit.
I also tried to use the c++ package 'Eigen' that yields similar problem at the same problem size.

Furthermore I would like to reduce the number of threads used for an incomplete LU decomposition, because the algorithm takes all without an advantage in calculation time. If I just add the option nprocs as described in the SuperLU manual in th epart where the SuperLU function is called it gives me an error.

Has anyone an idea how this might be fixes?

### Error message:
For the direct LU decomposition 
(' P=sci.linalg.spsolve(L,np.zeros(N)+1,use_umfpack=False)')
I obtain the Following error if N>9*10^6
<<Not enough memory to perform factorization.
Segmentation fault (core dumped)>>

For the incomplete LU decomposition 
P=sci.linalg.spilu(L)
I obtain for the same problem size
<<File "/home/sebastian/anaconda3/lib/python3.5/site-packages/scipy/sparse/linalg/dsolve/linsolve.py", line 386, in spilu
    ilu=True, options=_options)
RuntimeError: SUPERLU_MALLOC fails for buf in intCalloc() at line 159 in file scipy/sparse/linalg/dsolve/SuperLU/SRC/memory.c>>

### Scipy/Numpy/Python version information:
```
1.1.0 1.12.1 sys.version_info(major=3, minor=5, micro=4, releaselevel='final', serial=0)
```
Thanks in advance,
Sebastian

**Comment by pv** [comment]
spsolve produces a complete factorization of the matrix. In the worst
case it's close to full, and so takes 10^6 * 10^6 * sizeof(double) 
~ 8 TB, which is too much for most today's computers.
.
The incomplete decomposition would then need to be quite sparse, so you
may have success by adjusting the superlu drop tolerance etc. options.
.
In principle these routines shouldn't segfault but raise errors, but
the error handling in the SuperLU library is probably not completely
bug-free.

**Comment by sebvel** [comment]
Thank you very much for your quick answer. 10^6 times 10^6 yields absolutely no problem with spsolve. also 8.99*10^6 is fine and requires only 40 GB Ram for my problem.
Thanks for the hint, I try to reduce the drop tolerance.

**Comment by ilayn** [comment]
I think this is a case that we can't do much about as it is highly specialized and memory dependent. Hence closing.
