### ISSUE TITLE
Change parametrization of truncexpon 

### ISSUE THREAD

**Issue by getzze** [scipy/scipy#8842]
According to documentation, the parameter `b` is the upper boundary of the support. However, when the scale is different from 1.0, say 2.0, the distribution is defined until `scale*b` which is not very intuitive.
The problem is when performing a fit on a constant support. Fixing the scale means that the slope of the exponential is set also. And fixing `b` is not working because the support depends on scale also.

One idea would be to do like for `uniform`, define the support between 0 and 1, which translate to [loc, loc+scale], and use a `l` parameter for the shape inside the exponential:
```
def pdf(x, l):
    return l*np.exp(-l*x)/(-sc.expm1(-l))
```
I created a custom distribution with such a pdf and I can fit an histogram on a fixed support (defining floc and fscale). Behavior at small `l` should be looked more closely though.

Example:
```
import numpy as np
import scipy
x = np.linspace(0,2,500)
y0 = scipy.stats.truncexpon(x, 1, 0, 1)
y2 = scipy.stats.truncexpon(x, 2, 0, 1)  # in [0,2]
y1 = scipy.stats.truncexpon(x, 1, 0, 2)  # in [0,2] instead of [0,1]
```
### Scipy/Numpy/Python version information:
python=3.6.5
numpy=1.14.3
scipy=1.0.1

**Comment by ev-br** [comment]
We cannot just change parametrizations because of the backwards compatibility. Might want to try the `paramnormal` project (not sure how active it is). Explanations are most welcome in the Notes section of the docstring.

**Comment by josef-pkt** [comment]
AFAIU, this is not a reparameterization in the loc scale family, i.e. scale always shifts the support of the distribution if a support point is not zero or inf. So, I guess paranormal wouldn't be able to help it.

If we want to change scale in truncated distributions separately from the truncation points, then we would need an extra shape parameter. (The individual distribution need to be defined without loc and scale information.)
However, for fixed parameters, the user can compensate by adjusting the truncation point for loc and scale to compensate for the generic shifting and scaling of the support bounds. 

So this is only relevant in fit. I don't see a way to handle this there without an extra argument.

(It's a bit similar to the recent vonmises/vonmises_line discussion where we cannot change loc and scale and keep the support interval fixed.)
