### ISSUE TITLE
imresize cannot be deprecated just yet

### ISSUE THREAD

**Issue by Atcold** [scipy/scipy#8843]
Using `imresize` I get the following warning
```
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
```
`skimage.transform.resize` and `.scale` do not have any interpolation option, so it is **not** a viable replacement for `imresize`. Now I'm not sure I should open an issue at `skimage` or here. I start here because your routine is actually more versatile than `skimage`'s.

**Comment by pv** [comment]
imresize is just thin wrapper for Pillow.Image.resize, so the resizing
code is not "ours".

**Comment by Atcold** [comment]
Fine, then what about pointing that out in the warning message?
`skimage.transform.resize` is way too limited.

**Comment by ev-br** [comment]
@Atcold care to submit a PR with an enhancement to the deprecation message?

**Comment by Atcold** [comment]
Yes, I can. I'll do it later, this week.

**Comment by Atcold** [comment]
Done here #8971
I hope it's fine.

**Comment by ev-br** [comment]
Closed by https://github.com/scipy/scipy/pull/8971
