### ISSUE TITLE
scipy.optimize.fmin_cobyla should communicate non-convergence or other problem via return

### ISSUE THREAD

**Issue by ssiegel95** [scipy/scipy#8853]
Currently scipy.optimize.fmin_cobyla will warn to stdout about non-convergence or constraint violations but still returns a result. There should be some way to know (via the return) that there was an issue with the solution. In my case, scipy.optimize.fmin_cobyla is running as part of a REST service and it's impossible to catch this condition to communicate it back to the client. Perhaps an option can be added to the call to return None if any issues (constraint violations exceed their max tolerance, non-convergence, etc.) occur.

**Comment by pv** [comment]
Use scipy.optimize.minimize instead.

**Comment by ssiegel95** [comment]
Ah yes, that would do it. Thank you.
