### ISSUE TITLE
_flapack.so linked to two separate gfortran versions

### ISSUE THREAD

**Issue by perimosocordiae** [scipy/scipy#8855]
I'm not sure how this happened or if it's a problem, but it does cause a local test failure. After a fresh clone of the repository and a run of `python runtests.py`:

```
~/scipy$ ldd build/lib.linux-x86_64-3.6/scipy/linalg/_flapack.cpython-36m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffc3b18b000)
	libopenblas.so.0 => /usr/lib/x86_64-linux-gnu/libopenblas.so.0 (0x00007f27f418b000)
	libgfortran.so.4 => /usr/lib/x86_64-linux-gnu/libgfortran.so.4 (0x00007f27f3db7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f27f3ab3000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f27f389b000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f27f365b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f27f32bc000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f27f309f000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f27f2d79000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f27f2b5f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f27f67a0000)
```

Note that it's somehow linking to both `libgfortran.so.3` and `libgfortran.so.4`.
This causes the `TestF77Mismatch.test_lapack` test to fail:

```
E       AssertionError: Both g77 and gfortran runtimes linked in scipy.linalg.flapack ! This is
E       likely to cause random crashes and wrong results. See numpy INSTALL.rst.txt for
E       more information.

deps       = [b'libgfortran', b'libgfortran']
```

Checking my `/usr/lib` shows both versions installed:

```
~/scipy$ ls -1 /usr/lib/x86_64-linux-gnu/libgfortran.so.*
/usr/lib/x86_64-linux-gnu/libgfortran.so.3
/usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0
/usr/lib/x86_64-linux-gnu/libgfortran.so.4
/usr/lib/x86_64-linux-gnu/libgfortran.so.4.0.0
```

**Comment by pv** [comment]
The usual questions: what platform, can you compile even normal Fortran
programs?

**Comment by pv** [comment]
... os compile normal programs linked with the BLAS/LAPACK used here

**Comment by perimosocordiae** [comment]
Debian-based linux, and scipy builds and runs correctly. So far it doesn't seem to be causing any issues.

**Comment by pv** [comment]
Right, but what do you need to do to get the same issue to appear
outside numpy.distutils builds?

**Comment by perimosocordiae** [comment]
I didn't get to do much investigation today, but I did find this suspicious gfortran invocation in the build log (slightly cleaned up for display here):

```
/usr/bin/gfortran -Wall -g -Wall -g -shared $various_obj_files \
 -L/usr/lib/x86_64-linux-gnu -Lbuild/temp.linux-x86_64-3.6 \
 -lopenblas -lopenblas -lgfortran \
 -o build/lib.linux-x86_64-3.6/scipy/linalg/_flapack.cpython-36m-x86_64-linux-gnu.so \
 -Wl,--version-script=build/temp.linux-x86_64-3.6/link-version-scipy.linalg._flapack.map
```

I'll see if I can find a self-contained repro tomorrow.

**Comment by pv** [comment]
The link command itself looks OK to me. What could maybe happen is that
 the `libgfortran.so` symlink you have does not match the `gfortran`
version used to do the compilation.

**Comment by rgommers** [comment]
I haven't seen this ever with a `numpy.distutils` based build, and it certainly won't happen anymore with Meson. Either way, I have recently fixed some Fortran linkage related bugs in `numpy.distutils`, so I'll assume this has been fixed by now. Hence I'll close it - thanks @perimosocordiae and @pv.
