### ISSUE TITLE
Loging the DE optimisation f(x) in function of steps. 

### ISSUE THREAD

**Issue by raedbsili1991** [scipy/scipy#8857]
Hello,

During a 4-dimensional heavy optimization problem in which args are used to pass parametric information, I am willing to plot the population energy over generations, is there a way to do this from the simplest point of view ? I know that the energy of a population is stacked into _.population_energy_ vector and could be accessed once the optimization is terminated, however, as the optimization process takes too much time to converge, I want to access the f(x) values in every step of the optimization.

At the moment, what I am doing, is that I am manually monitoring the energy and appending it to a dynamic array then exporting it to a .csv file for visualization: 

```
def f_isotropy_evo(P,*data):

       LL1,LL2,LL3,ALPHA = P[0],P[1],P[2],P[3]
       filename,Input,N,iThetaL,iThetaR = data
       dataP = (LL1,LL2,LL3,ALPHA)
       global fx_array, NoG_array, NumberOfGeneration 
       some code for computation 
        if Residual < np.min(fx_array): 
           print("New optimum found!")
           NumberOfGeneration +=1 
        
           fx_array.append(Residual)
           NoG_array.append(NumberOfGeneration)
        
           df = pd.DataFrame(data = {'N° Generation [-]':NoG_array,
                                  'f-Residual [-]':fx_array
                             })

           df.to_csv('fResidualsData/'+filename+str(Input))

```

And for the solver: 

```
Bnds = [(np.radians(2),np.radians(85)),(np.radians(2),np.radians(85)),
       (np.radians(2),np.radians(85)),(np.radians(2),np.radians(85))]

Input = 80
iThetaL,iThetaR = Generate_Input(Input,50)
filename = '5_f_Residuals_'
data = (filename,Input,50,np.radians(iThetaL),np.radians(iThetaR))

fx_array,NoG_array,NumberOfGeneration = array('d'),array('d'),1

fx_array.append(1)
NoG_array.append(1)

solver  = differential_evolution(f_isotropy_evo,bounds=Bnds,args=data,
                              polish=True,
                              init='latinhypercube',
                              strategy = 'best2bin',
                              popsize = 8,
                              mutation = (1.7,1.9),
                              recombination = 0.2,
                              maxiter = 2,
                              disp=True)
```

However, this isn't the consistent way to log f(x) in function of DE steps. 

Does anybody can give an idea how to do that ? 

Thanks

**Comment by andyfaff** [comment]
Usage questions are best directed towards the `scipy-user` mailing list.  With the `differential_evolution` function you can use the `callback` option to receive the 'best solution' and the 'convergence' value at the end of each iteration. This will allow you to track the best cost at each iteration.
However, if you want the entire population/population energies there is no *public* API (at the moment) to do that. This is related to #8414 and #8259, which would make the underlying `DifferentialEvolutionSolver` available as part of the public API. 
You can achieve what you want to do by using this class.

```
maxiter = 100
solver = DifferentialEvolutionSolver(f_isotropy_evo, bounds=Bnds)
for nit in range(maxiter):
    x, cost = next(solver)
   # introspect the population
   energies = solver.population_energies
```

However, you have to be aware that because it's not part of the public API at the moment that behaviour might change in future releases. Backwards compatibility focusses on the parts of the API that are public.
If you have a better idea on how to detect convergence I'd be interested.

**Comment by raedbsili1991** [comment]
Hello @andyfaff  

Thanks for the feedback. 
Actually I was thinking to use Callbacks, however, it does not provides me with the needed information (or maybe I am not using it properly ?): 

```
 def CallB_ISO(Pk,convergence): 
    global fx_array, NoG_array, NumberOfGeneration 
    
    NumberOfGeneration +=1 
    print("Calledback -> [NoG, Emergy] = ", [NumberOfGeneration,  convergence])
    
    return 
```
Outputing: 

_differential_evolution step 1: f(x)= 0.44904
Calledback -> [NoG, Emergy] =  [6, nan]_

And I am intending to get  = [1 , 0.44] . . . 

The use of the DifferentialEvolutionSolver seems interesting! however, I don't see a way to import/use it as I am running the codes on Anaconda Jupyter and I am not allowed to install/update/modify any packages for some administrative reasons . . . 

An idea of doing this could be done by taking the Pk in the callback function and feed it to another function that re-compute the residual for that Pk but: 
- This takes too much time as, in my case, computing the residual of a single candidate takes about 20 seconds, and speeding up the convergence of the optimizer is a priority for me at the moment. 
- Looks like callback doesn't log the proper iteration number. 

Let me know as well if you have any other suggestions . . 

Cheers, 
R

**Comment by andyfaff** [comment]
The code is working as expected on my machine:
```
from scipy.optimize import differential_evolution

class Callback(object):
    def __init__(self):
        self.nit = 0
        
    def __call__(self, x, convergence=None):
        self.nit += 1
        
def ackley(x):
    arg1 = -0.2 * np.sqrt(0.5 * (x[0] ** 2 + x[1] ** 2))
    arg2 = 0.5 * (np.cos(2. * np.pi * x[0]) + np.cos(2. * np.pi * x[1]))
    return -20. * np.exp(arg1) - np.exp(arg2) + 20. + np.e
bounds = [(-5, 5), (-5, 5)]

c = Callback()
res = differential_evolution(ackley, bounds, callback=c)
print(c.nit, res.nit)
```
gives:
```
88 88
```
The first argument to `callback` is the current best solution, not the iteration number. The convergence number represents the variability in the population energies. Once the variability drops below a threshold the optimisation stops.

You would import the DifferentialEvolutionSolver as
```
from scipy.optimize._differentialevolution import DifferentialEvolutionSolver
```

you can then have access to the DES solver object on every iteration:

```
from scipy.optimize._differentialevolution import DifferentialEvolutionSolver as DES
solver = DES(ackley, bounds)
for i in range(100):
   x, e = next(solver)
   # access the energies
   solver.population_energies
```
As I said before just bear in mind that the DifferentialEvolutionSolver is not part of the public API so could be subject to changes in the future (e.g. renaming).
