### ISSUE TITLE
DOC/BUG: stats: Incomplete assignment statement in the frechet_l and frechet_r docstrings.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#8875]
In the "Examples" section of the docstrings for `scipy.stats.frechet_l` and `scipy.stats.frechet_r`, we have

```
>>> c =
>>> mean, var, skew, kurt = frechet_r.stats(c, moments='mvsk')
```

Obviously, that's not a very good example. 😦 

This causes an error when building the reference guide, but it doesn't stop the build from completing.  I only noticed the errors related to this because I was investigating the build logs for a pull request that failed for a different reason.

This probably started happening with the change in https://github.com/scipy/scipy/pull/7838.  That was my PR, so I'll add this issue to my "to do" list. I probably won't get to it soon, though, so if anyone wants to tackle this, go for it.  Be prepared to spend some time trying to wrap your head around the docstring build process for the distributions.  It's a bit convoluted.

Note that `frechet_l` and `frechet_r` are deprecated, so this issue probably has lower priority than normal.  I now notice that, while the methods of these distributions have deprecation warnings, the docstrings of the distributions do not state that they are deprecated.  E.g. the first line of the docstring at [`scipy.stats.frechet_r`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.frechet_r.html#scipy.stats.frechet_r) should have a deprecation message similar to the ones used in the methods.

**Comment by pv** [comment]
Seems to have been fixed.
