### ISSUE TITLE
scipy.linalg.block_diag is slow in comparison with np.kron

### ISSUE THREAD

**Issue by Prokhozhijj** [scipy/scipy#8877]
scipy.linalg.block_diag is slow in comparison with np.kron

### Reproducing code example:
```
import numpy as np
from scipy.linalg import block_diag

a = np.array([[5, 7], 
              [6, 3]])

n = 3

%timeit np.kron(np.eye(n), a)
12.4 µs ± 95.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

%timeit block_diag(*([a] * n))
19.2 µs ± 34.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

### Error message:
```
There is no error message
```

### Scipy/Numpy/Python version information:
```
1.1.0 1.14.3 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment]
That's just a coincidence. Kronecker product knows array end result so it can allocate the memory and fill it up on one go performing only elementwise multiplication. Blockdiag needs to know the sizes before start inserting them hence there will always be speed difference.

**Comment by Prokhozhijj** [comment]
So should I use np.kron always instead of block_diag when I need diagonal matrix constructed from another one?

**Comment by ilayn** [comment]
If you are after those tiny differences then yes. You can also do this manually but this is then beyond a scipy issue. You can ask for optimization in http://stackoverflow.com

**Comment by Prokhozhijj** [comment]
Well, for n = 300 the difference is much bigger.

```
%timeit np.kron(np.eye(300), a)
4.82 ms ± 67.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit block_diag(*([a] * 300))
1.08 ms ± 20.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

**Comment by ilayn** [comment]
They are not the same function. Their output can match occasionally but you can't derive a result out of block_diag if you want to have the result of `kron([[1,2], [3,4]], [5,6,7])`. One of them uses array, scalar multiplication the other one fills the block diagonal of the array. There is no point in comparing them just because for diagonal matrices in np.kron matches the output of linalg.block_diag

**Comment by ilayn** [comment]
If the array scalar multiplication takes more time then block_diag wins if array creation takes more time then kron wins. It's a matter of different arguments.

**Comment by Prokhozhijj** [comment]
Ok, thanks.
