### ISSUE TITLE
The sparse methods lgmres, factorize and others considerably slower in 1.1 compared to 0.19

### ISSUE THREAD

**Issue by chrisgmorton** [scipy/scipy#8892]
I noticed overall slowdowns in performance when first trying Scipy 1.0. Here is some code profiling of a test that shows slowdowns across the board for various calls. Unfortunately part of the contribution here is that an increase in the number of outer loop iterations of lgmres increases the number of calls to csc_matvec (3999 vs 1467), for some reason, so we have to look at the percall info in this case.

The overall execution time is considerably slower in 1.1.0 vs 0.19.0 : 246.6s vs 168.7s. The problem and size is exactly the same and the same answer is reached (to a high precision). Part of this issue is that lgmres goes through more outer loop iterations in the 1.1.0 code stream as already mentioned. However, percall time for csc_matvec is considerably slower (0.014s vs 0.01s). We also see a slowdown of superlu.gstrf (33.3s vs 26.9s cumtime). Other calls are also slower such as csc_matmat_pass1,2.

**Scipy 1.1.0**
```
         14982185 function calls (14972897 primitive calls) in 246.612 seconds

   Ordered by: internal time
   List reduced from 1034 to 50 due to restriction <50>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     3999   54.714    0.014   54.714    0.014 {built-in method scipy.sparse._sparsetools.csc_matvec}
     1291   45.753    0.035   45.753    0.035 {method 'solve' of 'SuperLU' objects}
       67   33.314    0.497   33.314    0.497 {built-in method scipy.sparse.linalg.dsolve._superlu.gstrf}
      150   23.632    0.158   23.632    0.158 {built-in method scipy.sparse._sparsetools.csc_matmat_pass2}
      150    6.167    0.041    6.167    0.041 {built-in method scipy.sparse._sparsetools.csc_matmat_pass1}
  1107178    5.154    0.000    6.628    0.000 ctypeslib.py:196(from_param)
       30    3.962    0.132    3.962    0.132 {method 'nonzero' of 'numpy.ndarray' objects}
   391125    3.698    0.000    3.698    0.000 {built-in method numpy.core.multiarray.array}
       67    3.541    0.053   95.856    1.431 _gcrotmk.py:17(_fgmres)
       30    3.110    0.104    3.110    0.104 {built-in method scipy.sparse._sparsetools.csc_minus_csc}
     1977    3.099    0.002    3.099    0.002 {built-in method scipy.sparse._sparsetools.csc_plus_csc}
   519681    1.989    0.000    1.989    0.000 {built-in method scipy.sparse._csparsetools.lil_insert}
     5655    1.817    0.000    1.817    0.000 {method 'repeat' of 'numpy.ndarray' objects}
   519681    1.684    0.000    4.171    0.000 lil.py:310(__setitem__)
```
**Scipy 1.0.0**
```
        15727572 function calls (15718234 primitive calls) in 245.853 seconds

   Ordered by: internal time
   List reduced from 1029 to 50 due to restriction <50>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     3978   53.953    0.014   53.953    0.014 {built-in method scipy.sparse._sparsetools.csc_matvec}
     1294   45.920    0.035   45.920    0.035 {method 'solve' of 'SuperLU' objects}
       67   33.218    0.496   33.218    0.496 {built-in method scipy.sparse.linalg.dsolve._superlu.gstrf}
      150   24.130    0.161   24.130    0.161 {built-in method scipy.sparse._sparsetools.csc_matmat_pass2}
      150    6.156    0.041    6.156    0.041 {built-in method scipy.sparse._sparsetools.csc_matmat_pass1}
  1107178    5.196    0.000    6.729    0.000 ctypeslib.py:196(from_param)
       30    3.953    0.132    3.953    0.132 {method 'nonzero' of 'numpy.ndarray' objects}
   392071    3.680    0.000    3.680    0.000 {built-in method numpy.core.multiarray.array}
       65    3.398    0.052   93.860    1.444 _gcrotmk.py:16(_fgmres)
       30    3.115    0.104    3.115    0.104 {built-in method scipy.sparse._sparsetools.csc_minus_csc}
     1977    2.985    0.002    2.985    0.002 {built-in method scipy.sparse._sparsetools.csc_plus_csc}
   519681    2.072    0.000    2.072    0.000 {built-in method scipy.sparse._csparsetools.lil_insert}
   519681    1.731    0.000    4.315    0.000 lil.py:333(__setitem__)
     5655    1.682    0.000    1.682    0.000 {method 'repeat' of 'numpy.ndarray' objects}

```
**Scipy 0.19.0**
```
         15450034 function calls (15440883 primitive calls) in 168.677 seconds

   Ordered by: internal time
   List reduced from 970 to 50 due to restriction <50>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       67   26.911    0.402   26.911    0.402 {built-in method scipy.sparse.linalg.dsolve._superlu.gstrf}
      150   21.048    0.140   21.048    0.140 {built-in method scipy.sparse._sparsetools.csc_matmat_pass2}
     1467   14.041    0.010   14.041    0.010 {built-in method scipy.sparse._sparsetools.csc_matvec}
      457   12.964    0.028   12.964    0.028 {method 'solve' of 'SuperLU' objects}
  1107178    7.072    0.000    8.638    0.000 ctypeslib.py:196(from_param)
      150    5.764    0.038    5.764    0.038 {built-in method scipy.sparse._sparsetools.csc_matmat_pass1}
     3508    5.654    0.002    5.654    0.002 {built-in method numpy.core.multiarray.lexsort}
     3538    4.273    0.001    4.273    0.001 {method 'nonzero' of 'numpy.ndarray' objects}
   386051    3.155    0.000    3.155    0.000 {built-in method numpy.core.multiarray.array}
       30    2.831    0.094    2.831    0.094 {built-in method scipy.sparse._sparsetools.csc_minus_csc}
     1881    2.694    0.001    2.694    0.001 {built-in method scipy.sparse._sparsetools.csc_plus_csc}
   519681    1.759    0.000    1.759    0.000 {built-in method scipy.sparse._csparsetools.lil_insert}
     5655    1.701    0.000    1.701    0.000 {method 'repeat' of 'numpy.ndarray' objects}
   519681    1.606    0.000    3.750    0.000 lil.py:333(__setitem__)
```
### Reproducing code example:
Call to create preconditioner:
```
self.func = sp.linalg.factorized(self.dF)

def SpectralMx(self, F):  
      return self.GN*self.func(self.GNm1*F)
```
Call for the preconditioner linear operator assembly:
```
LM = splinalg.LinearOperator((size,size), self.SpectralMx)
```
Call to lgmres solve.
```
dX,status = sp.linalg.lgmres(self.dF, -self.F, x0=self.X, tol=tol, maxiter=20, M=LM, callback=counter, inner_m=50)
```
### Error message:
No error or warning messages are reported.

### Scipy/Numpy/Python version information:
```
1.1.0 1.14.3 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)

OSX 10.13.4

Numpy/Scipy build with MKL 2018 update3 using gcc/g++/gfortran 7.1.0

```

**Comment by pv** [comment]
Please compare also to Scipy 1.0.0.

**Comment by pv** [comment]
Also try using the option `prepend_outer_v=True` in 1.x.0 --- the default value for it was changed from False to True, in order to match the original LGMRES paper. There is some freedom in the algorithm in choosing at what stage to insert the augmentation vectors --- this can have an effect on the matvec count, but whether it's an increase or decrease is problem-dependent.

**Comment by pv** [comment]
Regarding speed of SuperLU.solve and factorized() --- there are no code changes between 0.19.0 and 1.1.0 in the sparse LU code, so differences are likely due to either benchmarking methodology or different compiler used.

**Comment by chrisgmorton** [comment]
I've added the profile for 1.0.0 although there's not a significant difference to that of 1.1.0.

The addition of prepend_outer_v=True had no appreciable effect on the result.

**Comment by chrisgmorton** [comment]
Note I made a mistake in referring to 0.19.0 when the version I am using is 0.19.1 (now corrected above).
I rebuilt 0.19.1 with Numpy 1.14.3 and running, linked to MKL 2018 update3--after checking, I believe the 0.19.1 profile was carried out using Numpy 1.13.1 and MKL 2018 update1. Now we see similar results for the superLU cases. The slowdown, from a Scipy point-of-view, is due to the increased number of lgmres outer iterations done in the latest code versus the 0.19.1 release. I'm seeing 4 iterations versus 3 in general for my test case. Perhaps there's a way to tweak options to improve convergence of the linear solver.

**Comment by pv** [comment]
The change is then probably due to changes in the inner loop tolerance control, which is not really exact science with left preconditioning. My expectation is that whether this improved or decreased the number of outer iterations is problem-dependent. Probably `ptol -> 0.1*ptol` might not hurt however, as it may be generally cheaper to run inner loop for a few more iterations than start a new outer loop.

**Comment by chrisgmorton** [comment]
After playing with the setting on lgmres I've been able to get similar performance to 0.19.1. Closing.
