### ISSUE TITLE
v1.1.0 `ndi.rotate` documentation – reused parameters not filled in

### ISSUE THREAD

**Issue by kne42** [scipy/scipy#8895]
In the [v1.1.0 docs for `ndimage.rotate`](https://docs.scipy.org/doc/scipy-1.1.0/reference/generated/scipy.ndimage.rotate.html#scipy.ndimage.rotate), the "reused"/predefined parameters have not been replaced with their actual definitions; they still read as follows:
```
%(input)s
angle : float
    The rotation angle in degrees.
axes : tuple of 2 ints, optional
    The two axes that define the plane of rotation. Default is the first
    two axes.
reshape : bool, optional
    If `reshape` is true, the output shape is adapted so that the input
    array is contained completely in the output. Default is True.
%(output)s
order : int, optional
    The order of the spline interpolation, default is 3.
    The order has to be in the range 0-5.
%(mode)s
%(cval)s
%(prefilter)s
```

**Comment by rgommers** [comment]
Thanks @kne42. Looks like a clear oversight, a ``@_ni_docstrings.docfiller`` got misplaced somewhere.

I've marked this as a good first issue for a new contributor - example of how it should be is ``ndimage.shift``.

**Comment by rgommers** [comment]
fixed in gh-8938
