### ISSUE TITLE
Multiplying two sparse matrices with dtype of float16 returns dtype float32

### ISSUE THREAD

**Issue by dhimmel** [scipy/scipy#8903]
Taking the dot product of two scipy.sparse matrices with dtype=float16 returns a new matrix with dtype=float32. The expected behavior (and how numpy performs) is to return float16. This also applies to elementwise multiplication. Here is code illustrating the issue:

```python
import numpy
import scipy.sparse

array = numpy.arange(5, dtype='float16').reshape((1,5))
sparse_matrix = scipy.sparse.csr_matrix(array)

# Returns an array with dtype of float16
array @ array.transpose()

# Returns an array with dtype of float32
sparse_matrix @ sparse_matrix.transpose()
```

Perhaps this is related to https://github.com/scipy/scipy/issues/7408?

CCing @zietzm since this is the reason I believe [one of our builds failed](https://travis-ci.org/greenelab/hetmech/builds/388008326#L788).

**Comment by pv** [comment]
Essentially duplicate of gh-7408, the sparse matrices don't support float16
