### ISSUE TITLE
solve_banded erroneously special-cases 1x1 matrices

### ISSUE THREAD

**Issue by MattShannon** [scipy/scipy#8906]
The new version of solve_banded special-cases 1x1 matrices. However it does so incorrectly. The line here:

https://github.com/scipy/scipy/blob/272b2edc4d44d854b7fa75729da248bb1f934c0a/scipy/linalg/basic.py#L447

is only correct if u is 1. Typically u will be 0 (since the upper bands lie outside the 1x1 matrix), but arbitrary u should be supported just as for the rest of the code. I believe changing a[1, 0] to a[u, 0] should be sufficient.

**Comment by ilayn** [comment]
I think I don't understand. A 1x1 banded matrix is still a scalar. And in the packed format this the `[1, 0]` element. What exactly is the problem? Can you give a small example to demonstrate it?

**Comment by ilayn** [comment]
Ah scratch that, it is `[u, 0]` indeed. My bad. Care to submit a PR for the fix?

**Comment by ilayn** [comment]
Ah scratch that again, I need more coffee apparently. Come to think of it, if the matrix is 1x1 then `u` cannot be any number so I would consider it as a wrong argument.

**Comment by MattShannon** [comment]
Yeah, it wouldn't be entirely unreasonable to use a[0, 0] and raise an exception if u is anything other than 0.

However iirc that's inconsistent with the behavior of the rest of the function (which allows u or l to be larger than the total number of upper or lower diagonals in the corresponding full matrix), and there's no reason to disallow l and u having larger values than could possibly affect the entries in the full matrix. So I think the best thing is just to change it to a[u, 0].

Happy to have a go at a PR, but it won't be right away.

**Comment by ilayn** [comment]
That makes sense. I will think about this whenever I have the chance. And hopefully others would chime in too in particular  @larsoner and @ewmoore might be interested.

**Comment by mdhaber** [comment]
> However iirc that's inconsistent with the behavior of the rest of the function (which allows u or l to be larger than the total number of upper or lower diagonals in the corresponding full matrix), and there's no reason to disallow l and u having larger values than could possibly affect the entries in the full matrix.

Since the issue number will appear in the unit test of gh-21321, I thought I'd document this: yes, in the rest of the function (which covers `ab.shape[-1] > 1`), `u + l + 1` is allowed to be greater than the number of rows/cols in the original matrix.

For example, consider this case:
```python3
import numpy as np
from scipy import linalg

A = [[1, 2], [3, 4]]
b = [5, 6]
ref = linalg.solve(A, b)
```

There is one upper diagonal and one lower diagonal, so typically `solve_banded` would be called like:
```python3
l, u = 1, 1
ab = [[0, 2],
      [1, 4],
      [3, 0]]
res = linalg.solve_banded((l, u), ab, b)
np.testing.assert_allclose(res, ref)
```

But if we're feeling spicy, we can increase `u` and add corresponding rows to the `ab` matrix:
```python3
l, u = 1, 3
ab = [[10, 20],  # garbage
      [30, 40],  # not referenced, apparently
      [0, 2],
      [1, 4],
      [3, 0]]
res = linalg.solve_banded((l, u), ab, b)
np.testing.assert_allclose(res, ref)
```

So we could add an error for unusual input like this, but in the meantime we should make the specal case of `ab.shape[-1] = 1` work with this sort of input, too.

**Comment by mdhaber** [comment]
Closed by gh-21321.
