### ISSUE TITLE
Reshaping COO sparse matrices fails if the matrix has 2^31 or more elements

### ISSUE THREAD

**Issue by drhagen** [scipy/scipy#8912]
The [`coo_matrix.reshape` method](https://github.com/scipy/scipy/blob/master/scipy/sparse/coo.py#L194-L224) computes the linear index of each nonzero element (variable `flat_indexes` in the code) as an intermediate step. If there are more than 2^31 elements, the linear index overflows to negative and then the construction of the new matrix blows up. (This is the number of elements in the abstract matrix, not the number of nonzero elements in the sparse representation.)

This is particularly problematic because COO reshape is the default reshape method for sparse matrices so it affect CSC, CSR, and others.

What do you think the best solution is?

The obvious path is to do nothing and require that users supply the indexes as int64 if they want correct reshape behavior even if int32 is sufficient for the row and column indexes. However, this is very painful. Constructing CSR and CSC matrices with int64 indexes is not possible. If the user provides the rows and columns or indices and indptr as int64, the indexes and indptr get lowered to int32 anyway.

There are a couple of conservative solutions to the problem:

1. Raise the dtype to np.int64 for the linear index calculation.
2. Raise the dtype to np.int64 for the linear index calculation only when then number of elements is 2^31 or greater.

In the first two cases, we would have to decide under what circumstances we should lower the dtype back down to int32. 

It might be possible to rewrite the index calculation so that it simply does not overflow, but it is not obvious to me how to do that.

**Comment by jaimefrio** [comment]
If you want to experiment with alternative calculation methods, you have an expression of the form `divmod(a * b + c, d)`. If we rewrite `a = a0 * d + a1`, `b = b0 * d + b1` and `c = c0 * d + c1` we have `divmod((a0 * b0 * d + a1 * b0 + a0 * b1 + c0) * d + a1 * b1 + c1, d)`, which is very striaghtforward to calculate. So at the cost of replacing one division with 3, maybe 4:

```
rows, cols = self.shape
new_rows, new_cols = shape
cols_quot, cols_rem = divmod(cols, new_cols)
row_quot, row_rem = divmod(self.row, new_cols)
col_quot, col_rem = divmod(self.col, new_cols)

new_row = (cols_quot * row_quot * new_cols + cols_rem * row_quot +
           cols_quot * row_rem + col_quot)
new_col = cols_rem * row_rem + col_rem

if np.any(new_col > new_cols):
    row_delta, new_col = divmod(new_col, new_cols)
    new_row += row_delta
```

**Comment by drhagen** [comment]
I am trying @jaimefrio's solution. I think that 

> `if np.any(new_col > new_cols):`

needs to be 

`if np.any(new_col >= new_cols):`

**Comment by jaimefrio** [comment]
Yup, I think you are right, have edited my answer to not trip future readers.

**Comment by drhagen** [comment]
I am planning on making a pull request soon for this. I think this is the full chunk of code that needs to be added:

```
        if self.size == 0:
            # Special case an empty matrix to avoid divide by zero error
            new_row = []
            new_col = []
        elif order == 'C':
            ncols_quot, ncols_rem = divmod(ncols, new_ncols)
            row_quot, row_rem = divmod(self.row, new_ncols)
            col_quot, col_rem = divmod(self.col, new_ncols)

            new_row = (ncols_quot * row_quot * new_ncols + ncols_quot * row_rem +
                       ncols_rem * row_quot + col_quot)
            new_col = ncols_rem * row_rem + col_rem

            if np.any(new_col >= new_ncols):
                row_delta, new_col = divmod(new_col, new_ncols)
                new_row += row_delta
        elif order == 'F':
            nrows_quot, nrows_rem = divmod(nrows, new_nrows)
            col_quot, col_rem = divmod(self.col, new_nrows)
            row_quot, row_rem = divmod(self.row, new_nrows)

            new_col = (nrows_quot * col_quot * new_ncols + nrows_quot * col_rem +
                       nrows_rem * col_quot + row_quot)
            new_row = nrows_rem * col_rem + row_rem

            if np.any(new_row >= new_nrows):
                col_delta, new_row = divmod(new_row, new_nrows)
                new_col += col_delta
```

One question I have is: is that `if np.any(new_col >= new_ncols)` check worth it? As far as I can tell, this doesn't change the behavior of the method at all; it merely avoids an integer division when the quotient would be zero anyway. Is this to improve performance? This will trigger pretty much anytime the number of columns shrinks and this logical comparison will have been for naught.

Another question is should this new method only be triggered when the size will overflow, and it should follow the original path for small matrices?

**Comment by drhagen** [comment]
I can't seem to get this approach to work reliably. For example, this operation fails:

```
mat1 = coo_matrix(([1], ([3000000], [1000])), (3000001, 1001))
mat2 = mat1.reshape((1001, 3000001), order='C')
```

It happens because `ncols_rem * row_rem + col_rem` which is `1001 * 300000 + 1000` which overflows. This happens because the new columns do not go evenly into the current rows, which is probably a rare use case anyway.

**Comment by drhagen** [comment]
I've changed my opinion about this issue. Fundamentally, the origin of the problem lies with `scipy.sparse.sputils.get_index_dtype`. This function looks at the maximum values of the index arrays and returns `numpy.int32` if all the indices will fit in 32 bits, otherwise it returns `numpy.int64`. This dtype is then passed to `numpy.asarray` in multiple sparse matrix constructors. I am beginning to suspect that this is a flawed approach. For one, it is rather complicated given that this is what `asarray` dose by default (`asarray([2**30])` has dtype int32 while `asarray([2**31])` has dtype int64). Furthermore, if you know that `dtype=int32` is not large enough to work in intermediate calculations (like this issue) and pass in an array with `dtype=int64`, all the sparse matrix constructors downcast it to `dtype=int32`.

I am fine with having to upgrade my index arrays to int64 manually in order for them to work. I just want the constructor to not downgrade them anyway.

Would there be a drawback I am not thinking of to abolish `get_index_dtype` and just use `asarray`?
