### ISSUE TITLE
need to fix macOS build against older numpy versions

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#8915]
After the change to LAPACK 3.4.0, the macOS builds against numpy <1.11.3 don't work anymore. In https://github.com/MacPython/scipy-wheels/pull/32 a copy of a recent `numpy.distutils` is put into `scipy/_build_utils/`. We should do this in scipy itself, so macOS users can build SciPy themselves against an older NumPy.

**Comment by tylerjereddy** [comment]
I don't see any PRs linking in on this -- going to have to bump it to 1.3.0?

**Comment by rgommers** [comment]
Let's make a decision here whether we care enough about numpy <1.11.3 or not. If so, we can still fix this after the 1.2.x branch. If not, we can bump the minimum requirement on macOS for source builds. I'm inclined to go with the latter, and bump to 1.11.3 unconditionally for 1.3.0

**Comment by rgommers** [comment]
Okay, thought about it some more - I don't care enough to do this. People should just upgrade to >=1.11.3. macOS users are good at upgrading anyway. And it only affects whoever builds from source, wheels are fine. 

Leaving this open because technically it is a real bug (we claim to support >=1.8.2), let's fix it for the next release by bumping up the minimum NumPy version.

**Comment by rgommers** [comment]
fixed by now by requiring numpy >= 1.13.3, closing
