### ISSUE TITLE
Ambiguous docstring in `scipy.stats.probplot()`.

### ISSUE THREAD

**Issue by abukaj** [scipy/scipy#8921]
The issue has been raised in this SO question: https://stackoverflow.com/questions/48108582/how-to-interpret-scipy-stats-probplot-results#

[The documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.probplot.html#scipy.stats.probplot) says:

> **Generates a probability plot** of sample data against the quantiles of a specified theoretical distribution (the normal distribution by default).

> probplot generates **a probability plot, which should not be confused with a Q-Q or a P-P plot**. 

[According to Wikipedia, Q-Q plot](https://en.wikipedia.org/wiki/Q%E2%80%93Q_plot) is exactly what `scipy.stats.probplot()` plots.

### Scipy/Numpy/Python version information:
```
1.1.0 1.12.1 sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
Please read the first paragraph of that wikipedia - a Q-Q plot has *quantiles* on both axis. `probplot` has *sample data* on the vertical axis.
