### ISSUE TITLE
Bug in Solve_ivp with BDF and Radau solvers and numpy arrays

### ISSUE THREAD

**Issue by TUCMath** [scipy/scipy#8922]
It seems Scipy integration module **solve_ivp** when used with **BDF** and **Radau** solvers appends rounded numbers to the array. This will then cause an error of inconsistent dimensional further on in my code.
I wrote a simple example of a system with (2,1)-dimensional state (i.e. a second order system), which prints the state _y_ as it runs in the function _f(t,y)_, at one point, it appends the rounded number and gave me

```
[[ 13.67999979  13.67999999]
 [-15.99       -15.98999976]]
```

The second column is unnecessary and these added numbers will cause error in my original code.

### Reproducing code example:
```
from numpy import array, matmul
from scipy.integrate import solve_ivp
from numpy import size
def sys(t,x,A,xeq,matmul,size):
    if size(x)==4:
        print(x)
    xdot=matmul(A,x-xeq)
    return xdot

T=10
A=array([[-1,2],[-2,-6]])
x0=array([13.67999999,-15.989999999])
xeq=array([[0.99999999],[2.999999999]])
fun=lambda t, x: sys(t,x,A,xeq,matmul,size)
sol=solve_ivp(fun,[0,T],x0,method='BDF',vectorized=True)
```

### The output is:
```
[[ 13.67999979  13.67999999]
 [-15.99       -15.98999976]]
```

### Scipy/Numpy/Python version information:
```
1.1.0 1.14.4 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
@sajad-872797 does't look like any of `A, x0, xeq` are added to:
```
...
[[ 13.67999979  13.67999999]
 [-15.99       -15.98999976]]

In [11]: x0
Out[11]: array([ 13.67999999, -15.99      ])

In [12]: A
Out[12]: 
array([[-1,  2],
       [-2, -6]])

In [13]: xeq
Out[13]: 
array([[0.99999999],
       [3.        ]])
```

**Comment by WarrenWeckesser** [comment]
`x0` is an array with shape (2,), so `x` in `fun` will (normally) have shape (2,) also. `xeq` has shape (2,1), so `x - xeq` will will have shape (2, 2) (because of numpy's broadcasting).  Is that what you intended?
 
I suspect the case where `x.size` is 4 has something to do with your use of the option `vectorized=True`.  The docstring says `vectorized` means "Whether `fun` is implemented in a vectorized fashion. Default is False.", but I'm not really sure what that means.  I haven't dug into the code, but that might mean that the solver calls your function with an array of `x` vectors.   This option needs better user documentation.

Try solving the problem using `vectorized=False` in `solve_ivp`, taking into account my comment above about the shape of `x - xeq`.

**Comment by sajad-872797** [comment]
@rgommers @WarrenWeckesser 
Please note that `vectorized=True` is mean to able us to do matrix multiplication and write the system as natural as possible. Also, `x0` has to be an array of shape `(2,)`, and `x0` is not going to be directly inserted into `f(t,y)`. The latter gets a `(2,1)` and yields a `(2,1)` array. In addition, if you just change *BDF* to any of *RK45* or *RK23* the code works just fine.

**Comment by WarrenWeckesser** [comment]
I think this works the way you expect.  I made the changes I suggested above, and also removed some arguments from `sys` and tweaked the whitespace (sorry, can't help it).

```
from numpy import array, matmul
from scipy.integrate import solve_ivp
from numpy import size


def sys(t, x, A, xeq):
    if size(x)==4:
        print(t)
        print(x)
    xdot = matmul(A, x - xeq)
    return xdot

T = 10
A = array([[-1, 2],
           [-2, -6]])
x0 = array([13.67999999, -15.989999999])
xeq = array([0.99999999, 2.999999999])
fun = lambda t, x: sys(t, x, A, xeq)
sol = solve_ivp(fun, [0, T], x0, method='BDF')
```

**Comment by WarrenWeckesser** [comment]
Apparently `vectorized=True` can result in the `x` argument being shape `(2, 2)`.  I assume this is meant to be interpreted as multiple `x` vectors.  When `vectorized=False`, the argument `x` is always just a *single* vector.

**Comment by sajad-872797** [comment]
@WarrenWeckesser 
For this simple example, it does not matter `matmul(A,x-xeq)` is a row vector or a column vector. But I can imagine for an involved example, we need to reshape `x` for calculations. Anyway, this is perhaps a minor bug which can be avoided just by not using vectorized when *BDF* and *Radau* solvers are being selected.

**Comment by WarrenWeckesser** [comment]
I'm not convinced it is a bug at all.  It might just be a misunderstanding of the `vectorized` argument (not surprising, given that it isn't really explained in the docstring), combined with attempting to treat arrays with shape (2,) and (2,1) as being the same.  `solve_ivp` expects your state vector to have shape (2,), not (2, 1).   As I noted above, your `xeq`, has shape (2, 1), so the subtraction `x - xeq` results in shape (2, 2) (i.e. it is no longer something you would consider a "vector").  Then `matmul(A, x - xeq)` has shape (2, 2), which I think is not what you want.

**Comment by sajad-872797** [comment]
It is bug. Forget about `xeq`. Run the code with `matmul(A,x)` you will get the same result. As I said, the solver append the rounded state to the state and adds to its dimension.

**Comment by WarrenWeckesser** [comment]
> As I said, the solver appends the rounded state to the state and adds to its dimension.

And as I said, that appears to be a consequence of using `vectorized=True`; it is passing two state vectors at which you are to evaluate the system.

@nmayorov, could you describe (in a little more detail than what is in the current docstring) how the `vectorized` option is supposed to be handled by the user's code?  (Even better, could you update the docstring in a pull request, perhaps expanding on how and why to use `vectorized` in the Notes section?)

**Comment by nmayorov** [comment]
Hey guys, sorry for the confusion.

What `vectorized` means is explained for `fun`:

>Right-hand side of the system. The calling signature is ``fun(t, y)``.
Here ``t`` is a scalar, and there are two options for the ndarray ``y``:
It can either have shape (n,); then ``fun`` must return array_like with
shape (n,). **Alternatively it can have shape (n, k); then ``fun``
must return an array_like with shape (n, k), i.e. each column
corresponds to a single column in ``y``.** The choice between the two
options is determined by `vectorized` argument (see below). The
vectorized implementation allows a faster approximation of the Jacobian
by finite differences (required for stiff solvers).

(Not sure where did `;` come from).

So yes, `vectorized` means that that you need to compute multiple `f` for multiple `y` (useful for faster finite difference).

I guess we should add reference to `fun` in `vectorized` description. Will it be sufficient?

**Comment by WarrenWeckesser** [comment]
Thanks!  Sorry I didn't notice that explanation under `fun`.

@sajad-872797, that explains it.  When `vectorized` is True, your function might be passed an array of vectors.

**Comment by drewzeewoozee** [comment]
I believe this bug is bigger than appending rounded numbers to the array. I'm working with a very large system of ODEs (1000+ equations), and have found that when I use the `vectorized=True` option for `solve_ivp` the solver will attempt to pass a (n,n) matrix into the right-hand-side function, where n is the number of variables (n=1180 for the ODE system I'm working with). 

I also agree that the documentation for the "vectorized" option is entirely unclear.

**Comment by TejasAvinashShetty** [comment]
> Why should there be a difference in the way _BDF_ and _Radau_ implemented with that of _RK45_ and _RK23_. Users should be able to easily change the method to observe speed, convergence, and accuracy of each method. Nonetheless, if there is difference, it should be explicitly stated. I will try to design a simple system of ODEs for which switching from _RK45_ to _BDF_ yields an error of inconsistent dimension.

Any progress on this?

**Comment by waveletrider** [comment]
@TejasAvinashShetty and @sajad-872797 : The difference is that RK23 and RK45 are explicit methods, there never arises the need to evaluate the ODE function at multiple state vectors at the same time point. All that `vectorized` does is change the type of the state from (n,) to (n,1), that is, from array to proper column vector. 

On the other hand, BDF and Radau are implicit methods that use a Newton-like iteration to solve the resulting non-linear system. From time to time this method needs to compute or refresh the Jacobian, if that is done via divided differences then the ODE function needs to be evaluated at n slight variations of the current state, which can be done "in parallel". 

If this is properly implemented, one call with all of these vectors at once and using the numpy methods for matrix multiplications and simultaneous column operations can be substantially faster than a loop over all these state vectors separately. It might be questionable if this gives much of a speed-up in total when taken together with all the other steps without update of the Jacobian.

**Comment by mdhaber** [comment]
It seems that this was always a documentation issue. Please see if gh-17836 would have prevented the misunderstanding.

A related feature request is for `solve_ivp` to allow multidimensional `x0` (e.g. shape `(2, 1)` in this case). I wrote about how that feature can be accomplished in gh-13348. It really is closely related even though the use case there appears different. (The user wants to "vectorize"  in the sense of solving several problems in parallel.) I'll open a feature request for that and probably submit a PR, since I've had that need before and apparently others have, too.
