### ISSUE TITLE
Q: How to add new Cython files?  __pyx_capi__ error loading pxd.

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#8926]
What is/are the recommended ways to add Cython code?

I didn't find any Cython-specific doc, but there are some examples in `scipy/special`
[Filename: line from file, or description of relevant lines in file.].   

`lambertw(z, k)`:
`lambertw.pxd`: `cdef inline double complex lambertw_scalar(double complex z, long k) nogil:...`
`functions.json`: `"_lambertw" { "lambertw.pxd": {"lambertw_scalar": "Dld->D"}}`
`add_newdocs.py`:  [dummy "Do not use" docs for `_lambertw`]
`lambertw.py` : `from ._ufuncs import _lambertw; def lambertw(z, k=0,):…`
`__init__.py`: `from .lambertw import lambertw`

`spence(x)`:
`_spence.pxd` : `cdef inline double complex cspence(double complex z) nogil:`
`functions.json`:  `"spence": { "_spence.pxd": { "cspence": "D-> D"},"cephes.h": { "spence": "d->d" } }`
`add_newdocs.py`: [real docs for `spence`]

```
spherical_jn(n, z):
_spherical_bessel.pxd:
    cdef inline double complex spherical_jn_complex(long n, double complex z) nogil:...
    cdef inline double spherical_jn_real(long n, double x) nogil: ...
functions.json: "_spherical_jn": { "_spherical_bessel.pxd": { "spherical_jn_complex": "lD->D", "spherical_jn_real": "ld->d"}}
add_newdocs.py:  [dummy "Do not use" docs for _spherical_jn]
_spherical_bessel.py: 
    from ._ufuncs import (_spherical_jn, _spherical_yn, …)
    def spherical_jn(n, z, derivative=False):
        return _spherical_jn(n, z)
```

Based on those examples the rules for creating new`cyfunc` seem to be something like:
1. Create a Cython implementation of the function and place it in a pxd file. (E.g. `cyfunc_complex(z)`, `_cyfunc.pxd`
2. Create an entry in `functions.json` mapping a SciPy internal name to the .pxd file, along with the function name in the pxd file and the signature (or multiple function names/signatures pairs)
E.g. `"_cyfunc" : {"_cyfunc.pxd" : { "cyfunc_complex" : "DD->D"}}`
3. Add an entry in `add_newdocs.py`, dummy entries warning not to use for the internal names
4. Add a .py file which loads the internal function(s) from` ._funcs`, and calls it.
E.g. `_cyfunc.py`
```
from ._ufuncs import _cyfunc
def cyfunc(z):
    # Check arguments...
    return _cyfunc(z)
```
5. Add an import to `__init__.py`

Is that right?  Are there extra steps or naming rules?

I attempted to follow that procedure with a Python function `jtheta(z, tau)` writing the Cython `_jtheta_complex(z, tau)`.
I developed/debugged `_jtheta_complex(z, tau)` inside a Jupiter notebook using `%%cython` and then tried to make it stand-alone.
[`jtheta()` is the public function name, `_jtheta_complex()` is the Cython function, `_jthetac` the internal name in what follows.]

```
_jtheta.pxd: cdef inline double_complex _jtheta_complex(double_complex z, double_complex tau) nogil:
functions.json: "_jthetac": { "_jtheta.pxd": { "_jtheta_complex": "DD->D" } }
add_newdocs.py: [Added dummy "Do not use" docs for `_jthetac`]
_jtheta.py:  
    from ._ufuncs import _jthetac
    def jtheta(z, tau):`
__init__.py`: `from ._jtheta import jtheta`

It compiles and builds but fails immediately when running tests, with a message that the module `scipy.special._jtheta has no attribute '__pyx_capi__'`

What step am I missing? Or step not doing correctly?


### Error message:
```
/Users/Paul/anaconda/envs/py36scipydev/lib/python3.6/site-packages/py/_path/local.py:662: in pyimport
    __import__(modname)
../../scipy/special/__init__.py:641: in <module>
    from ._ufuncs import *
_ufuncs.pyx:1: in init scipy.special._ufuncs
    ???
E   AttributeError: module 'scipy.special._jtheta' has no attribute '__pyx_capi__'
_____________________________________________________________________________________________________ ERROR collecting scipy/special/tests/test_boxcox.py ______________________________________________________________________________________________________
```

### Scipy/Numpy/Python version information:
```
1.2.0.dev0+193e55b 1.14.2 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

**Comment by ev-br** [comment]
Do you have a branch somewhere we can grab? 
(My knowledge might be outdated) your step 4 looks dubious. I'm surprised there's a need for a python wrapper.
As a shot in the dark, try `git clean -xdf` (this deletes anything not git-committed!) and rebuild?

**Comment by person142** [comment]
Related: we need to update

https://scipy.github.io/devdocs/dev/index.html#scipy-special

again since the build process changed.

**Comment by pvanmulbregt** [comment]
1. The branch can be seen at https://github.com/pvanmulbregt/scipy/tree/jtheta.  A clean build didn't fix it for me.
2. I don't think there is a _requirement_ for a Python wrapper. `spence` doesn't have one for instance.  The wrapper can be used to 
a) decide which variant to use, based on optional arguments such as `derivative` for `spherical_jn`; or 
b) check arguments and raise Exceptions, as that is more work inside the pxd, though `sf_error.{h,c,py,pxd}` makes this easier; or
c) provide the doc for the function (E.g. `lambertw`)

**Comment by rgommers** [comment]
> What is/are the recommended ways to add Cython code?

I think the question here is specific to `special`, because of `cython_special`. Normally there's no need for a `.pxd` file, `functions.json` or `add_newdoc` (see e.g. `stats/_stats.pyx`, just needs `.pyx` plus a one-liner in `stats/setup.py`). `add_newdoc` is for C/C++ functions, and doesn't seem needed here (just edit the docstring in the Cython sources).

For the rest @person142 will probably have a better answer than I can come up with based on a quick browse.

**Comment by person142** [comment]
I know I've ran into this issue before. If I recall correctly (maybe a 50/50 chance here, it has been a while), your issue is trying to declare a static array in a `.pxd` file here: 

https://github.com/pvanmulbregt/scipy/commit/84de00353f4eff3daf49e14934b8b0603c09f56f#diff-2bdf6fb3e0818b4108dd27d96c5a4110R45

Try declaring it in the function body. There's also a variable `_MAX_EXPABLE` defined above; it would be better to declare that as a macro using `DEF _MAX_EXPABLE` (see e.g. `_loggamma.pxd` for some examples).

> I don't think there is a requirement for a Python wrapper. spence doesn't have one for instance. The wrapper can be used to...

Out of the (a), (b), and (c) reasons I'd say (a) is the only one that should cause writing a Python wrapper.

>  Functions whose name starts with "_" are treated differently (i.e. skipped) by _generate_pyx.py

They are only skipped for `cython_special`; note that this works:

```
>>> from scipy.special._ufuncs import _sinpi
```

**Comment by pvanmulbregt** [comment]
Thanks @person142. Some notes on getting the Cython code to compile.

1. On static arrays.

Moving the static array `cdef int JS2Mod8 = [0, 1, 0, -1, 0, -1, 0, 1]` inside the function failed because it now needs the `gil`.
```
Error compiling Cython file:
------------------------------------------------------------
...
    cdef int JS2Mod8[8]
    JS2Mod8 = [0, 1, 0, -1, 0, -1, 0, 1]  # Or JS2Mod8[:] = [0, ...]
   ^
------------------------------------------------------------

_jtheta.pxd:55:4: Slicing Python object not allowed without gil
```
I did find a thread https://groups.google.com/forum/#!topic/cython-users/cq0y7A4GEYI discussing the issue.  Moving it inside the function declaration and changing the type to a C pointer let Cython complete and `special` now imports. 

```
cdef inline int jacobi_symbol(long a, long b) nogil:
    cdef int *JS2Mod8 = [0, 1, 0, -1, 0, -1, 0, 1]
   ...
```

2. On making `_MAX_EXPABLE` a DEF:

I effectively want ` _MAX_EXPABLE = log(np.finfo(float).max)`, I.e. `log` of whatever the maximum double is at runtime.
`DEF _MAX_EXPABLE = log(DBL_MAX)` doesn't work as `log` is not known at compile time.
`DEF _MAX_EXPABLE = DBL_MAX_EXP * 0.6931471805599453` didn't work either as `DBL_MAX_EXP` is also not known at compile time.

But moving it inside the function did work
```
from libc.float cimport DBL_MAX_EXP
DEF LOG2 = 0.6931471805599453 # log(2)

cdef inline double_complex _jtheta(...) nogil:
    cdef double _MAX_EXPABLE = DBL_MAX_EXP * LOG2
...
```

**Comment by pvanmulbregt** [comment]
I found 3 ways to create Cython files suitable for inclusion in `scipy/special` and I'll describe them here.
1. `_jtheta.pxd`, with companion `_jtheta.py` file
2. `_jtheta.pxd` standalone
3. `_jtheta.pyx`.

Inside `special/special`, every `.pxd` file is processed by `scipy/special/_generate_pyx.py` which has some implications.
- Functions exported from a `.pxd` file need a doc string in `add_newdocs.py`.
- Functions exported from a `.pxd` file need an entry in `functions.json`.
- Functions exported from a `.pxd` file need to have the `nogil` attribute. [`_generate_pyx.py`generates `ufunc` versions of the exported functions, and it assumes that all are `nogil` functions when it generates prototypes.]
- If a function wants to raise a ValueError say, during checking of arguments, that requires the `gil`, hence split the code into a body/wrapper `.pxd/.py` pair, with a dummy entry in `add_newdocs.py`.

On the other hand, `.pyx` files do not get processed by `_generate_pyx.py`.
- Lines need to be added to `special/__init__.py` and `special/setup.py` to ensure compilation and visibility.
- Functions exported from `.pyx` files don't get automatically promoted to `ufuncs` and need to do their own broadcasting to handle arguments which are arrays.

**Comment by pvanmulbregt** [comment]
Closing as the question is answered and documented.
