### ISSUE TITLE
BUG: scipy.stats.norm wrong expected value of function when loc is large

### ISSUE THREAD

**Issue by zhangzsv** [scipy/scipy#8928]
The expected value of a normal distribution should be the center of the distribution, but scipy gives wrong results when loc/scale is large.
### Reproducing code example:
```
>>> import scipy.stats as stats
>>> stats.norm.expect(loc=10, scale=1)
10.000000000000004
>>> stats.norm.expect(loc=20, scale=1)
20.0
>>> stats.norm.expect(loc=30, scale=1)
30.0
>>> stats.norm.expect(loc=36, scale=1)
3.3637320653305685e-10
>>> stats.norm.expect(loc=40, scale=1)
1.5746385460369797e-26
>>> stats.norm.expect(loc=10, scale=0.1)
2.3378433179863228e-37
```

### Scipy/Numpy/Python version information:
```
Scipy 1.1.0
Numpy 1.14.3
```

**Comment by WarrenWeckesser** [comment]
The `expect` method is implemented with `scipy.integrate.quad`.  When `func` is not given, it is assumed that `func(x) = x`.  `quad` is used to numerically integrate `func(x)*pdf(x)` over the support of the distribution.  For the normal distribution, the integral is over [-inf, inf].  Apparently this use of `quad` isn't robust enough to handle large `loc`.

The problem also occurs with other distributions.  For example,

```
In [52]: from scipy.stats import gamma, logistic

In [53]: gamma.expect(args=(145,))
Out[53]: 145.00000000000045

In [54]: gamma.expect(args=(148,))  # Result should be 148.
Out[54]: 5.607236961785617e-09

In [55]: logistic.expect(loc=80)
Out[55]: 80.00000000000004

In [56]: logistic.expect(loc=85)  # Result should be 85.
Out[56]: 6.13219419324224e-09
```

Perhaps it could fixed by integrating over multiple intervals:  a finite interval [c, d] where c and d are based on the given values of `loc`, `scale` and the shape parameters (for distributions that have them), plus integrals over [a, c] and [d, b], where [a, b] is the support of the distribution (e.g. a = -inf and b = inf for the normal distribution).

Or, perhaps the variable of integration could be changed to `z = (x - loc)/scale`.

**Comment by WarrenWeckesser** [comment]
Note that the correct value can be computed by manually setting the integration limits:

```
In [73]: norm.expect(loc=50, scale=1)  # Bad result.
Out[73]: 9.38568238272931e-98

In [74]: norm.expect(loc=50, scale=1, lb=-50, ub=150)
Out[74]: 50.0

In [75]: gamma.expect(args=(148,))  # Bad result.
Out[75]: 5.607236961785617e-09

In [76]: gamma.expect(args=(148,), lb=0, ub=400)
Out[76]: 148.000000000001

In [77]: logistic.expect(loc=85)  # Bad result.
Out[77]: 6.13219419324224e-09

In [78]: logistic.expect(loc=85, lb=-50, ub=250)
Out[78]: 84.99999999999999
```

**Comment by adeharo9** [comment]
Could there be a way of throwing a warning or similar when this kind of inconsistencies occur? At least users would be aware that there might be problems with the obtained results.

**Comment by lovis-heindrich** [comment]
The same issue also occurs when using a small loc and a large upper or lower bound: 

```
>>> norm.expect(loc=1, scale=1, ub=10, conditional=True)
0.9999999999982133

>>> norm.expect(loc=1, scale=1, ub=20, conditional=True)
0.9999999999999999

>>> norm.expect(loc=1, scale=1, ub=30, conditional=True)
1.0

>>> norm.expect(loc=1, scale=1, ub=40, conditional=True)
3.4007656189526604e-22

>>> norm.expect(loc=1, scale=1, ub=50, conditional=True)
8.381344573482554e-89
```

**Comment by shuetyang** [comment]
do we have any update on the bug fixes?

**Comment by mdhaber** [comment]
Wow, actually, this tends to speed things up, at least on average among the test cases:
```python3

import scipy.stats as stats
from scipy.stats import gamma, logistic

def f():
    a = stats.norm.expect(loc=10, scale=1)
    b = stats.norm.expect(loc=20, scale=1)
    c = stats.norm.expect(loc=30, scale=1)
    d = stats.norm.expect(loc=36, scale=1)
    e = stats.norm.expect(loc=40, scale=1)
    f = stats.norm.expect(loc=10, scale=0.1)
    g = gamma.expect(args=(145,))
    h = gamma.expect(args=(148,))  # Result should be 148.
    i = logistic.expect(loc=80)
    j = logistic.expect(loc=85)  # Result should be 85.
    return a, b, c, d, e, f, g, h, i, j

print(f())  # half incorrect in main, all correct in PR
%timeit f()  # 362ms in main, 207 ms in PR
```

Surprisingly, it even speeds things up for the problems that `main` currently gets correct.

```python3
def f():
    a = stats.norm.expect(loc=10, scale=1)
    b = stats.norm.expect(loc=20, scale=1)
    c = stats.norm.expect(loc=30, scale=1)
    # d = stats.norm.expect(loc=36, scale=1)
    # e = stats.norm.expect(loc=40, scale=1)
    # f = stats.norm.expect(loc=10, scale=0.1)
    g = gamma.expect(args=(145,))
    # h = gamma.expect(args=(148,))  # Result should be 148.
    i = logistic.expect(loc=80)
    # j = logistic.expect(loc=85)  # Result should be 85.
    # return a, b, c, d, e, f, g, h, i, j
    return a, b, c, g, i

%timeit f()  # 322 ms in main, 101 ms in PR
```

So I take back what I wrote; I'm in favor of a fix like this. I'll see if I can speed it up more with `point` and a single call to `ppf`.

**Comment by mdhaber** [comment]
`points` won't work for functions with infinite support.
```ValueError: Infinity inputs cannot be used with break points.```
