### ISSUE TITLE
`scipy.fftpack.fftn` raises a new warning with pre-release of numpy

### ISSUE THREAD

**Issue by arokem** [scipy/scipy#8941]
In the course of our work on https://github.com/nipy/dipy, we've noticed a new warning with prerelease versions of scipy and numpy (see logs here: https://travis-ci.org/nipy/dipy/jobs/391291194)

See also: https://github.com/nipy/dipy/issues/1565

### Reproducing code example:
```
import numpy as np
from scipy.fftpack import fftn
fftn(np.random.randn(128))
```

### Error message:
```
/Users/arokem/.virtualenvs/scipy_fft/lib/python3.6/site-packages/scipy/fftpack/basic.py:160: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  z[index] = x
```

### Scipy/Numpy/Python version information:
```
1.2.0.dev0+b37d068 1.16.0.dev0+44cfca8 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
```

**Comment by larsoner** [comment]
Looks like a dup of #8879, right?

**Comment by arokem** [comment]
Yeah  - seems so. Thanks for making the connection. Closing.
