### ISSUE TITLE
scipy.optimize.minimize() stuck in infinite loop and ignores 'maxiter' option

### ISSUE THREAD

**Issue by Maikewng** [scipy/scipy#8948]
Hello everyone.
I developed a minimization problem which apparently sticks the minimize function in an infine loop, even if I set a maximum number of iterations.
The problem is modeled after the examples proposed in the documentation, which all correctly work and respect the given options.

My minimization problem works by creating an object which is then manipulated through an internal method which requires around 5 seconds to complete. Interestingly enough, if I don't execute that method and "fake" the result, the minimize function works correctly and respects the maxiter option. Somehow it looks like that method of my class messes up with the minimize function.

I am relatively new to python and object oriented programming, but I don't think a possibly wrong implementation of my problem is the cause, as the 'maxiter' option should be respected either way.

Let me know how I can help.

### Reproducing code example:
```
https://tdd1.ddns.net/nextcloud/s/qcLcjRgo2dsSF4o
```

### Error message:
```
None, stuck in infinite loop
```

### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.0.1 1.14.2 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```

**Comment by andyfaff** [comment]
https://gist.github.com/andyfaff/b087d570461cff3211bb399e5e019f6f

**Comment by andyfaff** [comment]
You are using a `root` finder, which by default uses the `hybr` method to find the roots of a vector valued function. With the `hybr` method there is no `maxiter` option. However your code did try to specify the maximum number of function evaluations, `maxfev`, which is allowed.
When I tried the example in the `root` docstring it takes 10 function evaluations (if I don't supply the `jac` keyword). If I set `options={'maxfev':1}` then the solver stops early, but has still done `nfev=4`. The external [MINPACK](https://github.com/scipy/scipy/blob/master/scipy/optimize/minpack.py#L224) solver code is responsible for halting after the number of function evaluations has been exceeded. However, in that code there will be a minimum number of function evaluations per iteration to evaluate a Jacobian, etc, with checks being done every iteration (possibly at the end) to see if maxfev has been exceeded. Therefore it's possible that maxfev will be exceeded by a few, but the solver will still stop as soon as it does the check. The documentation could possibly improved in that regard.

I cannot see from your example where you used `minimize`.

**Comment by Maikewng** [comment]
I'm sorry @andyfaff, I accidentally edited the file while shared from my local cloud. I wanted to verify if restructuring the problem in a root finding one would do any better.
I uploaded the correct code at https://gist.github.com/Maikewng/e8acd72b0dd86d9b029e153712c80235
Please have a look. Even if I specified options={'disp':True,'maxiter':1,'maxfev':1} the loop goes on indefinitely on my machine.
Thanks for your answers so far!
