### ISSUE TITLE
Kendall Tau correlation coefficient for similar list incorrect

### ISSUE THREAD

**Issue by prashast** [scipy/scipy#8949]
I have two lists with long integers which I wanted to compute the kendall-tau correlation
for. The two lists are identical but still I get a kendall-tau of `0.99999` as opposed to `1.0`.
This issue does not manifest itself if I am using lists of integers instead of long

### Reproducing code example:

```
from scipy import stats
long_list_1 = [1439200473L, 2750770398L, 3329411142L, 3142701992L, 3767465483L, 3010105389L]
long_list_2 = long_list_1
tau, p_value = stats.kendalltau(long_list_1, long_list_2)
print tau 
```

### Scipy/Numpy/Python version information:
```
('1.1.0', '1.14.5', sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0))
```

**Comment by ilayn** [comment]
Just for comparison, in Python 3, NumPy 1.14.4 and SciPy 1.2.0+dev version,  I get `0.9999999999999999`.

**Comment by sethtroisi** [comment]
@rgommers this no longer produces and the python2 is suspected in this, can this be optimistically closed?

**Comment by rgommers** [comment]
makes sense, thanks
