### ISSUE TITLE
stats.ks_2samp: reference?

### ISSUE THREAD

**Issue by chrisb83** [scipy/scipy#8961]
I noted that there is no reference for the KS 2-sample test. The p-value is computed as

```
d = np.max(np.absolute(cdf1 - cdf2))
en = np.sqrt(n1 * n2 / float(n1 + n2))
prob = distributions.kstwobign.sf((en + 0.12 + 0.11 / en) * d)
```

The term `en` is standard, but I wonder where `0.12 + 0.11 / en` comes from.
https://en.wikipedia.org/wiki/Kolmogorov–Smirnov_test

Does anyone have a reference? (Maybe @pvanmulbregt who worked lot on that test)

**Comment by josef-pkt** [comment]
see https://github.com/scipy/scipy/issues/8341#issuecomment-362315548

**Comment by chrisb83** [comment]
Thanks for the reference. I close this issue as it is a "sub-issue" of 8341.
