### ISSUE TITLE
numpy.quad relative and absolute errors 

### ISSUE THREAD

**Issue by manconi** [scipy/scipy#8964]
I wonder why the default numpy.quad is setting both the epsabs and epsrel value for performing the integral, as described in 
https://www.gnu.org/software/gsl/manual/html_node/Numerical-Integration-Introduction.html

In my opinion, it would be safer to set as default just one of the two. Many Python users are not checking this fact, and are not aware about the possibility of working at fixed absolute or relative error.  
 I verified that this is not important for smooth integrals, but it becomes important (both for the reliability of the result and for the speed) as soon as the integrand is non-standard.

**Comment by pv** [comment]
Default epsrel is required for results with large magnitude, and epsabs with results that are zero.
Having default value for both is quite typical, e.g. Matlab, Octave, R, ... do it similarly.

Changing this would have backward compatibility effects, and would need stronger reasoning than an opinion.

**Comment by manconi** [comment]
Thank you for your reply and explanation.  You are absolutely right about my opinion, but it was a starting point to discuss an issue I wanted to underline. 
I would recommend to clarify this fact at least in the documentation.
