### ISSUE TITLE
Flatten function does nothing for sparse matrix

### ISSUE THREAD

**Issue by twolodzko** [scipy/scipy#8974]
Below I show a code example where flatten() function have no effect on sparse matrix unless converting to array explicitly. This is confusing, at minimum it should be documented or produce some kind of warning.

### Reproducing code example:
```
>>> from scipy.sparse import csr_matrix
>>> mtx = csr_matrix(([1,2,3], ([1,8,12], [5,2,32])))
>>> mtx[[2,5], [12,13]]
matrix([[0, 0]], dtype=int64)  
>>> mtx[[2,5], [12,13]].flatten() # does nothing...
matrix([[0, 0]], dtype=int64)
>>> mtx[[2,5], [12,13]].A.flatten()
array([0, 0], dtype=int64)
```

### Scipy/Numpy/Python version information:
```
1.0.0 1.14.1 sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
It is because indexing etc. of sparse matrices produces `numpy.matrix`
objects instead of arrays. `flatten()` of `matrix()` class converts
inputs to a row vector (because matrices are always 2d):
```
>>> np.matrix([[1,2], [3,4]]).flatten()
matrix([[1, 2, 3, 4]])
```

**Comment by twolodzko** [comment]
OK, I understand, but still it does not produce the output one could expect...

**Comment by ev-br** [comment]
Sparse matrices are likely stuck with the np.matrix API. Sparse arrays are being developed separately. Closing. Thanks @twolodzko
