### ISSUE TITLE
scipy.linalg.expm does not give the expected result

### ISSUE THREAD

**Issue by mkhoshle** [scipy/scipy#8981]
Hi all, 

I have the following example and it gives the correct results when my matrix elements are not integers, however it does not work when they are integers:

### Reproducing code example:
```
import numpy as np
import scipy

Q = np.array([[-500,500,0,0],[0,-550,360,190],[0,630,-630,0],[0,0,0,0]])   # Rate Matrix
pi = scipy.linalg.expm(Q*10) 

np.sum(pi,axis=1)
array([-0.63612061, -0.2620967 , -0.53480159,  1.        ])
```
But it works for the following case:
```
Q = np.array([[-500,500,0,0],[0,-550,360,190],[0,630,-630,0],[0,0,0,0]])   # Rate Matrix
pi = scipy.linalg.expm(Q*10.5) 

np.sum(pi,axis=1)
array([1., 1., 1., 1.])
```

### Error message:
I do not get any error but the results are wrong.

### Scipy/Numpy/Python version information:
```
scipy.__version__
'1.1.0'
```

Does anyone know why this is the case and why I am getting this error?

**Comment by ilayn** [comment]
I don't see this in the dev version. Probably fixed already?

**Comment by pv** [comment]
I don't think so (reproduces on master).

**Comment by pv** [comment]
Fix in gh-8984 (just cast any integer input matrices to float).

**Comment by ilayn** [comment]
Strange. I can't replicate it on `1.2.0.dev0+c79b48d`
