### ISSUE TITLE
Please provide Python 3.7 wheels

### ISSUE THREAD

**Issue by hugovk** [scipy/scipy#8987]
Please provide wheels for Python 3.7.0 ([released 2018-06-27](https://www.python.org/dev/peps/pep-0537/#schedule)) on PyPI. This would allow consumers of SciPy to test their code faster with 3.7, and without the need for a Fortran compiler or other dependencies such as BLAS/LAPACK libraries.

Thank you.

**Comment by matthew-brett** [comment]
Wheels are up now - please let me know if you have any problems.

**Comment by jakevdp** [comment]
Thanks for your quick response on this @matthew-brett !

**Comment by rgommers** [comment]
awesome, thanks Matthew
