### ISSUE TITLE
Overflow when using multivariate_normal.pdf in high dimensions

### ISSUE THREAD

**Issue by RPrudden** [scipy/scipy#8999]
I find that `sp.stats.multivariate_normal.pdf` works fine in relatively small dimensions, but causes an overflow when used for several hundred dimensions.

### Reproducing code example:
```
import GPy
import numpy as np
import scipy as sp

sdim = 22
ker1 = GPy.kern.Matern52(2, lengthscale=4)
xx, yy = np.mgrid[1:sdim+1, 0:sdim]
X = np.vstack((xx.flatten(), yy.flatten())).T
C = ker1.K(X)
sp.stats.multivariate_normal.pdf(np.zeros(sdim**2), mean=None, cov=C)
```

### Error message:
```
 /opt/conda/lib/python3.6/site-packages/scipy/stats/_multivariate.py:513: RuntimeWarning:overflow encountered in exp
```

### Scipy/Numpy/Python version information:
```
1.0.0 1.12.1 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
```

**Comment by mdhaber** [comment]
@RPrudden Can you give a numerical covariance matrix so we can try to reproduce this issue?

**Comment by mdhaber** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/Multivariate_normal_distribution), this is the multivariate normal PDF:
![image](https://user-images.githubusercontent.com/6570539/201588011-48018b75-b4d8-40bc-974b-75f663061518.png)

Inside the $\exp$ is all zero, so the log of this is 

$-\frac{1}{2} \left( k \log(2 \pi) + \log(|\Sigma|) \right).$

In your example, $k=484$ and `np.linalg.slogdet(C)[1]  # -2386.456843123006)`, so we have 

$-\frac{1}{2} \left( 484 \log(2 \pi) - 2386.46 \right) = 748.46$, which agrees with
```python3
stats.multivariate_normal.logpdf(x, mean=None, cov=C)  # 748.4621714904414
```
When this gets exponentiated it overflows, but there was nothing wrong with the calculation. The number is just too big to be represented with `float64`.
