### ISSUE TITLE
Usage of Mathieu functions

### ISSUE THREAD

**Issue by vipuljoshi92** [scipy/scipy#9000]
I understand that I should raise issues related to the code; however; please forgive me for asking about the usage of mathieu functions to solve mathieu differential equation.
Can you please elaborate with a numerical example on how to use Scipy special functions for solving differential equations,
Thanks

**Comment by ilayn** [comment]
You would actually get a much faster answer if you ask this on either math.stackexchange.com or stackoverflow.com since both have a wider technical and specialized audience.
