### ISSUE TITLE
relative error argument for scipy.special.wofz

### ISSUE THREAD

**Issue by ghost** [scipy/scipy#9006]
I'm trying to speed up a script that is bottlenecked by calls to the scipy.special.wofz ufunc.  I see a potential for significant speedup at the cost of reduced precision in the underlying c code through the "relerr" argument built into the algorithm.  Ideally, I would simply write:

```
from scipy.special import wofz
fast_output = wofz(input_arr, relerr=0.001)
```

Unfortunately, the scipy wofz wrapper function excludes an option for changing the native default value (relerr=0) set in scipy/special/Faddeeva.hh, so I'm stuck with:

```
#note, no keyword arg for relerr
#native code defaults to relerr=DLB_PRECISION
slow_output = wofz(input_arr)
```

**Is this loss of functionality in the scipy wrapper a necessary condition of being a ufunc?**

**What is the best way around this issue (in general or as a private hack)?**  I am thinking about loading the native Faddeeva function using the CFFI module, but I can barely read c code, so that would take a bit of effort.  Perhaps it is also possible to change a couple lines in the signature for wofz in the scipy/special/functions.json file and recompile something (again, this is outside my comfort zone).

**Comment by person142** [comment]
Closing-the original assessment of the author here:

> Is this loss of functionality in the scipy wrapper a necessary condition of being a ufunc?

is essentially correct. We don't want to go adding keyword arguments to things because that will de-ufunc them.
