### ISSUE TITLE
scipy.optimize.curve_fit would benefit from an option to use only monotonic functions

### ISSUE THREAD

**Issue by Tarskin** [scipy/scipy#9011]
I would like to know if it is possible to get an option added to curve_fit that forces it to stick to monotonic functions (i.e. I am trying to get the best fitting monotonic polynomial for a given set of data).

**Comment by pv** [comment]
curve_fit fits parameters in user-defined functions, and it does not
know anything about the structure of the function or meaning of the
parameters. What you ask is outside the scope of the routine (at least
in the problem formulation in the question above).

To do monotonic fitting, the responsibility of providing a suitable
parameterized function (possibly under specified bound constraints)
rests on the user.

**Comment by ev-br** [comment]
I'm going to close this, but the discussion can continue of course.
