### ISSUE TITLE
Bring back scipy.stats.threshold

### ISSUE THREAD

**Issue by wkeithvan** [scipy/scipy#9012]
This function is very useful in image segmentation. In my application, I need to perform a connected component labeling on the output of a convolutional neural network. In a perfect network, the output array would have 0 as the background and 1 as a mask for the detected item, however, as this is a neural network, there are many tiny non-zero values in the background and the detected item has values usually above 0.5.

To perform a proper connected component labeling, I need to replace all values below 0.5 in the array with 0 and then use `scipy.ndimage.measurements.label` on the resulting array since `label` considers all non-zero values. Currently, I am using numpy to perform thresholding with `arr[arr < 0.5] = 0` (See [StackOverflow](https://stackoverflow.com/a/1623939/2922676) for how this works and note the answer [below](https://stackoverflow.com/a/22291243/2922676) referencing `scipy.stats.threshold`), however, using `scipy.stats.threshold(arr, threshmin=0.5)` is much cleaner and more clear.

If this is not a feature that is ever going to be revived, please let me know if there is a better or clearer alternative to `arr[arr < 0.5] = 0`.

**Comment by perimosocordiae** [comment]
How about `np.round(arr)`?

Also, this question may get a better response rate on the [scipy-dev mailing list](https://mail.python.org/mailman/listinfo/scipy-dev): scipy-dev@python.org

**Comment by rgommers** [comment]
>  Currently, I am using numpy to perform thresholding with `arr[arr < 0.5] = 0` .... however, using `scipy.stats.threshold(arr, threshmin=0.5)` is much cleaner and more clear.

This is an opinion that most people won't share. The numpy expression is completely clear, while for `stats.threshold` one would have to look at its documentation to figure out exactly what that line of code is doing.

> If this is not a feature that is ever going to be revived, please let me know if there is a better or clearer alternative to `arr[arr < 0.5] = 0`.

The feature will not be revived.  `arr[arr < 0.5] = 0` is the most idiomatic way of expressing what you want. Just add a comment if it's not clear enough to you or other people using your code I'd say.
