### ISSUE TITLE
Fix the phase skew in STFT (introduce zero-phase zero padding)

### ISSUE THREAD

**Issue by susnak** [scipy/scipy#9026]
Dear maintainers,

please consider introducing compensation of the phase skew in STFT introduced by the window. Essentially, just perform half-window length circular shift of the windowed (and possibly zero-padded) piece of signal just before doing FFT. The circshift should move the position of the window peak to the zero-th position of the fft buffer and the left tail gets periodically wrapped.
ISTFT should do the converse.
 
[Here](https://ccrma.stanford.edu/~jos/sasp/Zero_Phase_Zero_Padding.html) is a nice explanation.

The whole point is that the phase factor caused by the window "delay" will be removed (if it is whole point symmetric; such as in e.g. signal.hann(16,False)).

Note this will only affect the phase of the STFT coefficients. The magnitude (spectrogram) will stay the same.

Thank you very much.
Zdenek

P.S.: Also please merge #8870 as soon as possible.

**Comment by larsoner** [comment]
We would need to do this by a new keyword argument to the STFT and ISTFT functions to maintain backward compatibility. Any ideas? Maybe `phase='linear' | 'zero'`, where current behavior is `'linear'` and what you propose is `'zero'`? Or maybe `phase_shift=False | True`?

**Comment by susnak** [comment]
Either option is fine with me. The phase='zero' might be a bit misleading since it is not zero for half-point symmetric and asymmetric windows. 
And to be pedantic, the phase is not guaranteed to be exactly zero everywhere even for whole-point symmetric windows since the symmetry only assures that the FFT is real, but it can still be negative somewhere.

Since the new convention is most well known in connection with the phase vocoder, how about
introducing something like phase_convention = 'skewed' | 'phasevocoder'?
A nice reference would be Chapter 8.3.2 and Figure 8.5 in Zölzer: DAFX: Digital Audio Effects, 2nd Edition
(only shown for the case when the window length is equal to the FFT length).

**Comment by larsoner** [comment]
To be shorter how about `phase='skewed' | 'vocoder'`?

**Comment by susnak** [comment]
Sounds good.

**Comment by larsoner** [comment]
Can you make a PR for this?

**Comment by susnak** [comment]
Sorry for the delay. I can do that. Any guidelines I should follow?

**Comment by larsoner** [comment]
https://github.com/scipy/scipy/blob/master/CONTRIBUTING.rst

**Comment by larsoner** [comment]
@susnak any interest in coming back to this?
