### ISSUE TITLE
scipy.linalg.eig or eigh problem

### ISSUE THREAD

**Issue by taoxuewen** [scipy/scipy#9027]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
the eigvectors of this matrix calculated scipy.linalg.eig or eigh is not the same with the result calculated by matlab(the matrix is in the file below).
[Rsum.zip](https://github.com/scipy/scipy/files/2191091/Rsum.zip)

### Reproducing code example:
```
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```

### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>

**Comment by rgommers** [comment]
@taoxuewen that is not a bug. The eigenvectors will still be correct ones. We cannot guarantee to always match Matlab, and your code shouldn't rely on such matching.

For future reference, it is always helpful to provide a self-contained example that demonstrates a bug (as the issue template requests).

**Comment by taoxuewen** [comment]
Thank you very much for your reply.
