### ISSUE TITLE
Duplicated code in stats.ks_2samp

### ISSUE THREAD

**Issue by Vayel** [scipy/scipy#9028]
Is it on purpose that these lines are duplicates? If so, a comment to explain why would be welcome.

* https://github.com/scipy/scipy/blob/v0.14.0/scipy/stats/stats.py#L3873
* https://github.com/scipy/scipy/blob/v0.14.0/scipy/stats/stats.py#L3875

**Comment by rgommers** [comment]
You're looking at a very old version (0.14.0), it's fixed in master: https://github.com/scipy/scipy/blob/master/scipy/stats/stats.py#L4846

Thanks for the report anyway @Vayel

**Comment by Vayel** [comment]
@rgommers Oups sorry. This is the version linked in the docs ("source" link).

**Comment by pv** [comment]
It's the link given in the documentation only if you are reading the
documentation for the old 0.14.0 version.

**Comment by ilayn** [comment]
![image](https://user-images.githubusercontent.com/1303842/42700494-31796ca4-86c4-11e8-9304-4fe3f349d089.png)

You probably end up on that page through a search engine. If you look at the top of the documentation page you can see which version docs you are looking at. If you click on `Docs` you can go back to all versions of the documentation.
