### ISSUE TITLE
scipy.stats.normaltest sometimes gives incorrect returns b/c of bug in scipy.stats.kurtosis.test

### ISSUE THREAD

**Issue by anthonybishara** [scipy/scipy#9033]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
The function scipy.stats.normaltest is intended to compute the D'Agostino K^2 ombinus test of normality.  However, it occasionally gives incorrect results due handling of a cube-root of negative numbers in scipy.stats.kurtosis.test
This issue originally came from: https://stats.stackexchange.com/questions/353756/normality-test-giving-confusing-results

### Reproducing code example:
```

#A detailed example is here: https://stats.stackexchange.com/questions/353756/normality-test-giving-confusing-results

#A possible fix for scipy.stats.kurtosistest
#(Please forgive the messiness - I'm a long-time R user but 1st-time Python user)
#Several lines of code in the function, then...
term1 = 1 - 2/(9 * A)

#New code begins here to address cube-roots of possibly negative numbers
def cubroot(y):
    from math import copysign
    return copysign(abs(y)**(1/3),y)
term2 = cubroot((1 - 2/A)/(1 + x * np.sqrt(2/(A - 4))))
Z= (term1 - term2)/ np.sqrt(2/(9.0*A)) # [1]_ Eq. 5
if Z.ndim == 0:
    Z = Z[()]
return KurtosistestResult(Z, 2 * distributions.norm.sf(np.abs(Z)))
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```

### Error message:
```
#No error message, just inaccurate results
<<Full error message, if any (starting from line Traceback: ...)>>
```

### Scipy/Numpy/Python version information:
```
1.1.0 1.14.3 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```

**Comment by chrisb83** [comment]
Thanks for pointing it out. So you have an example where the test returns a wrong result. It would be good to have it as a test case once fixed ans to understand the issue better (i did not check it yet, i understand that the sign of the cubic root is wrong).

I did not loo

**Comment by anthonybishara** [comment]
Just to add for clarity, the relevant equation is (19) on pg. 318 of D'Agostino et al. (1990) https://www.jstor.org/stable/pdf/2684359.pdf
When fixed, the results for the example (the "a" object in https://stats.stackexchange.com/questions/353756/normality-test-giving-confusing-results) should be something along the lines z.skew=-0.2300619, z.kurt=46.98108, chisq= 2207.275, and p of approximately 0.

**Comment by chrisb83** [comment]
yes, i agree that the implementation does not look correct. I could not Access the reference you gave but the following one worked:

> F. J. Anscombe, W. J. Glynn, “Distribution of the kurtosis statistic b2 for normal samples”, Biometrika, vol. 70, pp. 227-234, 1983.

In the end, the term `(1 - 2/A)/(1 + x * np.sqrt(2/(A - 4)))` can become negative and then `(...)**(1/3)` should simply be the cube root of it (again negative), right? Currently, the code sets the value to 0 and there is  comment on this in the documenttion:

> The Z-score is set to 0 for bad entries. 

(https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kurtosistest.html)

The current code is
```
denom = 1 + x*np.sqrt(2/(A-4.0))
denom = np.where(denom < 0, 99, denom)
term2 = np.where(denom < 0, term1, np.power((1-2.0/A)/denom, 1/3.0))
Z = (term1 - term2) / np.sqrt(2/(9.0*A))  # [1]_ Eq. 5
Z = np.where(denom == 99, 0, Z)
```

I think it should be (same as in your answer):

```
denom = 1 + x*np.sqrt(2/(A-4.0))
term2 = np.where(denom < 0, -np.power(-(1-2.0/A)/denom, 1/3.0), np.power((1-2.0/A)/denom, 1/3.0))
Z = (term1 - term2) / np.sqrt(2/(9.0*A))  # [1]_ Eq. 5
```

Using git blame, the last time this code line with term2 was edited in cd4e901d6a6f38b9a843acc7dac6077bd568cc6b. If I have more time, I can check the history in more detail.

**Comment by anthonybishara** [comment]
I like it.  It looks cleaner than my copysign solution, and  I think it will work so long as the numerator is always positive (so only the sign of denom matters).  It looks like the numerator will always be positive because "As n ranges from 4 upwards, A is smallest when n = 24, and then it is just over 18".  So that suggests 1-2/A is at lowest when 1-2/18 > 0, so the numerator is always positive.  Let me know if you'd like me to run some simulations to verify the accuracy, but just glancing at it, your suggested change looks right.

**Comment by chrisb83** [comment]
thanks, i tested the case `x = np.hstack([np.full(c, i) for i, c in enumerate([128, 0, 58, 7, 0, 41, 16, 0, 0, 167])])` from the stackexchange thread and the p-value is 0.0 with the above implementation.

Probably one needs to take care of the case `denom == 0`. And the test needs to be fixed in `mstats` as well.
