### ISSUE TITLE
applying type hint(PEP 484) for scipy

### ISSUE THREAD

**Issue by akahard2dj** [scipy/scipy#9038]
Hello, scipy contributors and users.
Since [PEP 484](https://www.python.org/dev/peps/pep-0484/) was announced, type hint has been very helpful for a large-scale development to recognize variables in a variety of functions.

scipy is a very huge numerical libraries. when we develop/analysis a problem, it is confused by the type of incoming parameters and returns. Of course, the doc string and example is very useful for that problem.

But if we apply type hint for the development, IDE(for example, pycharm) could help us.

So I suggest that when we develop a scipy, how about the PEP 484 into the scipy?

**Comment by ilayn** [comment]
That would be really helpful on the surface but we have exceedingly many options for most function arguments. Just the simple case of `array_like`, `numpy.array` and `numpy.matrix` for any array sometimes accepting scalars sometimes explicitly requiring a 2D array makes this impossible to implement.

On top of that, For example, NumPy broadcasting rules make this type annotation even more complicated.

**Comment by pv** [comment]
If it is to be done, it probably should be done following Numpy: 
https://github.com/numpy/numpy-stubs

As noted above, this is a somewhat more complicated problem, as also
the question of how numpy arrays are represented appears to be not
fully settled. For those who are interested to see this happen, I'd
recommend to check the progress of "numpy-stubs", and simply start
working on a similar "scipy-stubs" prototype themselves --- if it looks
like progress can be made, we can move the repository under the scipy
org and make it "official" after the fact (and give necessary commit
permissions to continue working on it).

(For scipy core development, the annotations are in my opinion low
priority, as there's no shortage of other things to do.)

**Comment by akahard2dj** [comment]
I fully understand that this issue is related to scipy itselt and numpy arrays.
Depending on the @pv commentary, the annotations issue is seems to be developed in near future.

I also check and read the "scipy-stubs".
Thanks to @pv and @ilayn for valuable discussion.

**Comment by dpinol** [comment]
What's the status of type hints? I don't see any in stats and mypy complains with
```

error: Cannot find
implementation or library stub for module named "scipy.stats._stats_py" 
[import-not-found]

```

**Comment by lucascolley** [comment]
see https://github.com/scipy/scipy/issues?q=label%3A%22static+typing%22 - typing coverage is limited at the moment but PRs to add type stubs are welcome

**Comment by mdhaber** [comment]
Alternatively, it may be more time-efficient to improve information about types in docstrings. I saw a demo of https://github.com/scientific-python/docstub on SciPy's docs and was very impressed. If our docstrings are reasonably consistent and correct - as they should be - it promises to generate type stubs automatically. Besides the benefit of the docstubs, it helps us improve our docs - even though it can be fairly flexible about the grammar we use, it's not a bad idea to have some consistency throughout the project. 

@lagru is there anything we can do right now? For instance, are there any subpackages where the docstrings look close to generating correct docstrings with the tool? Can the tool provide some output about what it's having a hard time understanding?

**Comment by lagru** [comment]
Hey, I hope to get proper reporting done over the next week. Right now, docstub's logging is helpful but could use more context to know precisely where something isn't up to the spec. Once that's done, I'll get back to you about how SciPy looks in terms of consistency and submodules.

Right now, it would be useful to know, what kind of "human readable" types SciPy wants to support. E.g. how do you want to specify the shape and dtype of arrays? E.g. scikit-image uses `(SHAPE, ..., 2) uint8 array` while scikit-learn uses `array of dtype int and shape (N, M)` from what I can see.

How do you specify additional information that won't be included in the type itself. Stuff like setting `func` as an alias for `callable` is already supported and should be easy to customize.

**Comment by lucascolley** [comment]
x-ref https://github.com/numpy/numpydoc/pull/423. I'm definitely a fan of having `shape` included rather than just `(N, M)`. This isn't standard across SciPy at all atm.

**Comment by mdhaber** [comment]
Oh man if I hadn't been so ticked about backticks, that would have been a great thing to work on at the summit!
