### ISSUE TITLE
Using Python security alerts

### ISSUE THREAD

**Issue by JakobJakobson** [scipy/scipy#9041]
Dear developers,

as I read the following news on the GitHub blog [Security vulnerability for Python](https://blog.github.com/2018-07-12-security-vulnerability-alerts-for-python/) I got curious if you want to use it for scipy?

Regards,
Jakob

**Comment by rgommers** [comment]
Thanks for the question @JakobJakobson. Let's do that discussion in one place though: https://github.com/numpy/numpy/issues/11576. Closing this, likely not relevant for SciPy but we can follow NumPy's lead in this if that makes sense.
