### ISSUE TITLE
optimize: Incorrect statement about `jac` in the `minimize` docstring.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#9042]
In the description of the `jac` argument, the docstring for `scipy.optimize.minimize` says

    Alternatively, the keywords {'2-point', '3-point', 'cs'} select a finite
    difference scheme for numerical estimation of the gradient.

and

    If False, the gradient will be estimated using '2-point' finite difference estimation.

Those descriptions are not correct when `method` is `'Newton-CG'` or `trust-ncg` (and maybe others--I haven't checked).  For example,

```
In [156]: def func(x):
     ...:     return ((x-1)**2).sum()
     ...: 

In [157]: from scipy.optimize import minimize
```

Try `'Newton-CG'` with `jac=False`:

```
In [158]: minimize(func, [1.1, 1.2], method='Newton-CG', jac=False)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-158-94c7580e9508> in <module>()
----> 1 minimize(func, [1.1, 1.2], method='Newton-CG', jac=False)

~/miniconda3scipy/lib/python3.5/site-packages/scipy-1.2.0.dev0+6d455f3-py3.5-macosx-10.6-x86_64.egg/scipy/optimize/_minimize.py in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    600     elif meth == 'newton-cg':
    601         return _minimize_newtoncg(fun, x0, args, jac, hess, hessp, callback,
--> 602                                   **options)
    603     elif meth == 'l-bfgs-b':
    604         return _minimize_lbfgsb(fun, x0, args, jac, bounds,

~/miniconda3scipy/lib/python3.5/site-packages/scipy-1.2.0.dev0+6d455f3-py3.5-macosx-10.6-x86_64.egg/scipy/optimize/optimize.py in _minimize_newtoncg(fun, x0, args, jac, hess, hessp, callback, xtol, eps, maxiter, disp, return_all, **unknown_options)
   1494     _check_unknown_options(unknown_options)
   1495     if jac is None:
-> 1496         raise ValueError('Jacobian is required for Newton-CG method')
   1497     f = fun
   1498     fprime = jac

ValueError: Jacobian is required for Newton-CG method
```

Try `'trust-ncg'` with `jac=False`:

```
In [159]: minimize(func, [1.1, 1.2], method='trust-ncg', jac=False)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-159-0e8fe542e188> in <module>()
----> 1 minimize(func, [1.1, 1.2], method='trust-ncg', jac=False)

~/miniconda3scipy/lib/python3.5/site-packages/scipy-1.2.0.dev0+6d455f3-py3.5-macosx-10.6-x86_64.egg/scipy/optimize/_minimize.py in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    621     elif meth == 'trust-ncg':
    622         return _minimize_trust_ncg(fun, x0, args, jac, hess, hessp,
--> 623                                    callback=callback, **options)
    624     elif meth == 'trust-krylov':
    625         return _minimize_trust_krylov(fun, x0, args, jac, hess, hessp,

~/miniconda3scipy/lib/python3.5/site-packages/scipy-1.2.0.dev0+6d455f3-py3.5-macosx-10.6-x86_64.egg/scipy/optimize/_trustregion_ncg.py in _minimize_trust_ncg(fun, x0, args, jac, hess, hessp, **trust_region_options)
     32     """
     33     if jac is None:
---> 34         raise ValueError('Jacobian is required for Newton-CG trust-region '
     35                          'minimization')
     36     if hess is None and hessp is None:

ValueError: Jacobian is required for Newton-CG trust-region minimization
```

Apparently a Jacobian *function* is required for these methods.  The `minimize` docstring should be updated to make this clear.  Or, if it is feasible, the methods should be fixed to behave as documented.

If users happen to follow the references to the additional documentation about the [`'Newton-CG` method](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-newtoncg.html#optimize-minimize-newtoncg), they'll see the note that says "Note that the jac parameter (Jacobian) is required."  That's too well hidden, and still not explicit.  Does it mean providing the argument `jac='3-point'` is sufficient?  If an implementation of the Jacobian function (i.e. a callable) is required, it should say so explicitly, and that information should be in the `minimize` docstring.

See https://stackoverflow.com/questions/33926357/jacobian-is-required-for-newton-cg-method-when-doing-a-approximation-to-a-jaco and https://stackoverflow.com/questions/51369984/jacobian-is-required-for-newton-cg-method-issue-still-exists-for-trust-ncg for cases where the current documentation leads to confusion.

**Comment by pv** [comment]
It would be really nice if the special values were the same for all solvers --- for this there's probably no big obstacle in principle.

**Comment by andyfaff** [comment]
I hope both this and #9044 would be helped with class inheritance with the SciPEP from #8414, #8552.

**Comment by battaglia01** [comment]
It looks like Jacobian estimation is disabled for the Newton-CG minimization method, even though the documentation says it's there. Is there any way to correct this?

**Comment by CatNofishing** [comment]
The problem still eists，please figure it😂
