### ISSUE TITLE
Bound constraint specifications in minimize() - harmonize trust-constr

### ISSUE THREAD

**Issue by pv** [scipy/scipy#9043]
In `optimize.minimize`, the solver `trust-constr` accepts a different way to specify bound constraints than the other solvers. This goes somewhat against the design of the `minimize` interface --- you should be able to swap the solver just by changing the `methods=` value.

Two things would need to be implemented:

- [x] Automatic conversion of the "old-style" dict constraint and bounds specifications to the "new" format
- [x] Automatic conversion from "new-style" to "old-style" (or raise error if it's not possible)

**Comment by mdhaber** [comment]
@antonior92 @nmayorov I could take a look at this if you'd like? I know you two already put a lot of work into the interface.

**Comment by antonior92** [comment]
Thank you a lot Matt for taking care of this. I will help reviewing your PR

**Comment by mdhaber** [comment]
Thanks, @antonior92. Your input on Jacobians and tests would be helpful, so please take a look at the PR when you get a chance. I was asking whether the derivative approximation methods from your VectorFunction class should be used with SLSQP when the user doesn't specify a callable.

**Comment by mdhaber** [comment]
@pv do you think this was resolved by gh-9112? There were a few issues with conversion of constraint jacobian specification that we discussed; not sure if this should be left open or another issue needs to be raised?

**Comment by andyfaff** [comment]
@pv, @mdhaber should this be closable now?
The issue was being able to supply either new-style or old-style constraints to `minimize` (being agnostic of method).
I think this is being done [here](https://github.com/scipy/scipy/blob/master/scipy/optimize/_minimize.py#L594):
```
    if constraints is not None:
        constraints = standardize_constraints(constraints, x0, meth)
```

**Comment by mdhaber** [comment]
Yes, that bit was part of gh-9112, and most of this was addressed. But I think we still wanted constraint Jacobian and `keep_feasible` old <-> new translation, so if this issue is closed a new one would need to be created for those features. Especially considering recent work on related issues (e.g. gh-10648, gh-10673), it makes sense for those items to remain on the to-do list.

**Comment by andyfaff** [comment]
`keep_feasible` is only used for `trust-constr` though, SLSQP doesn't use that feature.
Also, isn't the constraint Jacobian taken care of in the conversion process?

**Comment by mdhaber** [comment]
> `keep_feasible` is only used for `trust-constr` though

Maybe at the time I didn't check whether any of the old solvers could support it.

> Also, isn't the constraint Jacobian taken care of in the conversion process?

I don't remember offhand, and I'm not sure what has happened since then, but according to the comments here and in gh-10648, no.
