### ISSUE TITLE
wilcoxon() rejection direction is unclear for one-sided test

### ISSUE THREAD

**Issue by jkokatjuhha** [scipy/scipy#9046]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
As mentioned [here](https://github.com/scipy/scipy/issues/2625) by @abhinavkgp :

> ... it is still not possible to determine one-sided result (whether x-y>0 or y-x>0) using this two-sided statistic, due to the following:
> 
> Code:
> T = min(r_plus, r_minus)
> r_plus = np.sum((d > 0) * r, axis=0) #Always positive
> r_minus = np.sum((d < 0) * r, axis=0) #Always positive
> 
> Reasoning:
> So, if you swap x and y, T will still be the same, z statistics will still be the same
> 
> Final Thoughts:
> We should also aim to return in some way that whether r_plus was used or r_minus was used (through a flag maybe) in order to know the result of a one-sided tailed test

### Reproducing code example:
```
A = [10,10,10,10,15,11]
B = [30,30,30,30,31,32]

wilcoxon(A, B) == wilcoxon(B,A)
```

### Scipy/Numpy/Python version information:
```
1.0.1 1.14.3 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```

**Comment by chrisb83** [comment]
The test only returns the two-sided p-value, so the order of x and y does not matter. I don't think there is a bug.

Is this a feature request to have a one-sided test?

**Comment by jkokatjuhha** [comment]
Once could transform the p-value directly into a one-sided p-value by diving by 2. So, yes, it is either a feature request or a request for providing a flag for rejection direction in case of a one-sided test.
