### ISSUE TITLE
wassertein distance and energy distance analysis

### ISSUE THREAD

**Issue by rtmatx** [scipy/scipy#9057]
@CharlesMasson I have used your code to calculate wasserstein distance and energy distance. I am comparing how these distances stack up against `ks test` for two tags which have different spread. 

In the picture attached below, I am surprised that wasserstein or energy distance is low for the plot on the right when compared to the plot on the left. The plots on the left and right are for different tags. Does it have to do with the spread. If so, how can we negate the effect of spread on the score. Also, is there any good way to compare scores across different variables to identify which distribution is more different than the other.

Scores for left plot 
```
Konglomorov distance 	 	0.57961
Energy distance 	 		46.30263
wasserstein distance 	 	2723.99741
```

Scores for right plot 
```
Konglomorov distance 	 	1.0
Energy distance 	 		39.10564
wasserstein distance 	 	793.78945
```

![Comparing the distance on two different tags](https://user-images.githubusercontent.com/23462596/42903471-8a5c60a2-8a97-11e8-9cab-35b1169f9a3d.jpg)

Thanks

**Comment by ilayn** [comment]
Can you provide some code and data for this? 

Is there any issue related to SciPy or is this a data question?

**Comment by rtmatx** [comment]
Unfortunately I can't provide data. But I will provide the code that I have used for the analysis. This question is related to the recent #7563 that is merged. I didn't receive any errors but the computation results are something that I am not expecting. Hence I have tagged, Charles, who have written code for this. 

```
    ks_results = stats.ks_2samp(x1, x2).statistic
    wst_results = stats.wasserstein_distance(x1, x2)
    esdt_results = stats.energy_distance(x1, x2)
```

**Comment by CharlesMasson** [comment]
@rtmatx It's a bit hard to assess without the actual data, but looking at the distributions on the right, the distances match what I would expect. If we consider two distributions that have all their weights in single points, let's say _a_ and _b_, the Wasserstein distance between them would be |_a_-_b_| and the energy distance between them would be sqrt(2 |_a_-_b_|). If we very roughly approximate the distributions on the right as two distributions that have all their weight in 50 and 850 respectively, the Wasserstein distance should be 800 and the energy distance should be 40. This seems in line with the values that you get.

Contrary to KS, the Wasserstein and the energy distances depend on the scale of the data, so I'm not surprised that they are lower for the plot on the right. To get something that is scale-invariant, the distances need to be normalized somehow.

**Comment by rtmatx** [comment]
@CharlesMasson Thanks for the reply. I can see if I can provide a simulated data with similar distributions. May be a stupid question, but isn't the energy distance is based on the cumulative distribution like KS-test and not on the provided values ? I am under the impression that energy distance, find cdf first and then uses the distance over several quantile and add it up in the end?

I can think of normalizing the distance by `max-min` or quantile values like `q95-q5` etc. I am not considering standard scaling as that can affect the values especially if there are two modes of operation for the same variable.

**Comment by CharlesMasson** [comment]
@rtmatx In the one-dimensional case, the energy distance is equal to the non-distribution-free Cramér distance, and therefore, it can be computed from the cumulative distribution functions. In practice, the function first computes the (empirical) cumulative distribution functions from the provided values and weights, and then computes the integral of the squared difference between the cumulative distribution functions.

Depending on the use-case, using the [mean absolute difference](https://en.wikipedia.org/wiki/Mean_absolute_difference) to normalize might also give interesting results.

**Comment by chrisb83** [comment]
It looks like this issue can be closed, otherwise feel free to reopen it.
