### ISSUE TITLE
scipy.signal.bode different results between TransferFunction and ZeroPolesGain input

### ISSUE THREAD

**Issue by jmwilson** [scipy/scipy#9058]
The plotted Bode gain factor when using a `ZeroPolesGain` input appears off.

### Reproducing code example:
Imagine a single-pole filter with pole frequency at 1000 Hz and unity gain.
The transfer function should be 1/(1 + s/w), where w = 2 * pi * 1000. The single pole is at s = -2 * pi * 1000.

Express this filter in `TransferFunction` form, and then `ZeroPolesGain` form, and then compared the plotted `signal.bode` plot.

```
import math
import matplotlib.pyplot as plt
import numpy
import scipy.signal

def transfer_plot(system):
    freq = numpy.logspace(1, 6, 10000)
    fig, ax = plt.subplots(constrained_layout=True)
    two_pi = 2*math.pi

    w, mag, phase = system.bode(two_pi*freq)
    ax.set_title('Transfer function')
    ax.set_xlabel('frequency (Hz)')
    ax.set_ylabel('gain (dB)')
    ax.semilogx(w/two_pi, mag)
    ax.grid(True, which='both', axis='x', color='xkcd:light grey')
    phase_ax = ax.twinx()
    phase_ax.set_ylabel('phase (deg)')
    phase_ax.semilogx(w/two_pi, phase, linestyle='dashed')

    return fig

system1 = scipy.signal.lti(
    [1],
    [1/(2*math.pi*1000), 1]
)
system2 = scipy.signal.lti(
    [],
    [-1000*2*math.pi],
    1
)
transfer_plot(system1)
transfer_plot(system2)
plt.show()
```

### Error message:
When I examine the plots, the first one (using `TransferFunction`) shows the expected low frequency gain of 0 dB. The second one (using `ZeroPolesGain`) ought to be identical. Its shape is the same, but the low-frequency gain is about -76 dB.

### Scipy/Numpy/Python version information:
```
1.1.0 1.14.5 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
Take a look at the 'repr' of `system1`:

```
In [39]: from scipy.signal import lti

In [40]: system1 = lti([1], [1/(2*np.pi*1000), 1])

In [41]: system1
Out[41]: 
TransferFunctionContinuous(
array([6283.18530718]),
array([1.00000000e+00, 6.28318531e+03]),
dt: None
)
```
`lti` has divided the numerator and denominator of the transfer function by the coefficient of *s* in the denominator, so the transfer function is

```
          2000π
H(s) = ----------
        s + 2000π
```

From that form, it is clear that the system has no (finite) zeros and a pole at s=-2000π.

The general form for the ZPK format is

```
          (s - z1)(s - z2) ... (s - zm)
H(s) = K -------------------------------
          (s - p1)(s - p2) ... (s - pn)
```
Expressing your H(s) in this form gives
```
                     1
H(s) = 2000π ----------------
              (s - (-2000π))
```
So K is 2000π.  You used K=1 when you created `system2`.

You can also get this result by using the `to_zpk()` method of `system1`:

```
In [44]: system1.to_zpk()
Out[44]: 
ZerosPolesGainContinuous(
array([], dtype=float64),
array([-6283.18530718]),
6283.185307179586,
dt: None
)
```

I'm closing the issue, but don't hesitate to ask if you have any questions.
