### ISSUE TITLE
Multiple unrelated PRs failing linalg & optimize Travis Py27 test

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#9063]
Multiple PRs from multiple authors (gh-9062, gh-9059, gh-9055, gh-8737, ...) fail the 2nd Travis-ci test:
Python 2.7: `TESTMODE=fast COVERAGE= NUMPYSPEC="--pre --upgrade --timeout=60 -f $PRE_WHEELS numpy`
E.g. https://travis-ci.org/scipy/scipy/jobs/406046820 from gh-9059.
All the other subtests pass on Travis and AppVeyor and circleci.

Three of these four PRs are purely documentation changes: one of them adds a single line to `README.rst` so presumably shouldn't trigger failures in `linalg` or `optimize`.

Is this a Travis issue or a SciPy issue?  (I'm assuming the independence of the PRs implies it is not due to any changes in the PRs themselves.)

### Error message:
```
=========================== short test summary info ============================
FAIL scipy/linalg/tests/test_decomp.py::TestRQ::()::test_random_complex_economic
FAIL scipy/linalg/tests/test_decomp_ldl.py::test_ldl_type_size_combinations
FAIL scipy/optimize/tests/test_linprog.py::TestLinprogIPSpecific::()::test_alternate_initial_point
FAIL scipy/optimize/tests/test_linprog.py::TestLinprogIPSpecific::()::test_cholesky
FAIL scipy/optimize/tests/test_linprog.py::TestLinprogIPSpecific::()::test_disp
FAIL scipy/optimize/tests/test_linprog.py::TestLinprogIPSpecific::()::test_maxiter
FAIL scipy/optimize/tests/test_linprog.py::TestLinprogIPDense::()::test_large_problem
XPASS scipy/linalg/tests/test_matfuncs.py::TestFractionalMatrixPower::()::test_singular Too unstable across LAPACKs.
XPASS scipy/ndimage/tests/test_datatypes.py::test_uint64_max runs only on darwin
XPASS scipy/optimize/tests/test_linprog.py::TestLinprogIPSparse::()::test_bug_6690 Fails with ATLAS, see gh-7877
XPASS scipy/optimize/tests/test_linprog.py::TestLinprogIPSparsePresolve::()::test_bug_6690 Fails with ATLAS, see gh-7877
XPASS scipy/special/tests/test_basic.py::TestCephes::()::test_fdtri_mysterious_failure Returns nan on i686.
XPASS scipy/stats/tests/test_distributions.py::TestF::()::test_stats_broadcast f stats does not properly broadcast
 7 failed, 13186 passed, 1297 skipped, 85 xfailed, 6 xpassed in 733.66 seconds =
```

**Comment by pv** [comment]
Since the failures only affect the Python 2.7 build using Numpy prerelease, it's likely it's an issue in the corresponding Numpy wheels.

The last "good" build in master is using wheel `numpy-1.16.0.dev0+20180713182412_7598437-cp27-cp27mu-manylinux1_x86_64.whl` on July 13, 2018 21:49:42. https://travis-ci.org/scipy/scipy/jobs/403739331

The first "bad" build in master is using wheel `numpy-1.16.0.dev0+20180716140353_f07359b-cp27-cp27mu-manylinux1_x86_64.whl ` on July 16, 2018 21:58:42. https://travis-ci.org/scipy/scipy/jobs/404630473

If it's an Numpy issue with numpy wheels, something has been changed between the two commits in Numpy, or during that time in the numpy-wheels wheel builder repository. (This can be checked also locally by installing a wheel from the prerelease index and seeing if failures reproduce.)

**Comment by pv** [comment]
Looks like the failures can be reproduced locally if you install latest numpy prerelease wheels from
https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com

**Comment by pvanmulbregt** [comment]
Thanks for figuring it out.  In particular, the problem isn't with SciPy or Travis but a 3rd party I hadn't listed, namely NumPy....   Plus now I know where to look (https://travis-ci.org/scipy/scipy/builds) to find the build history.

**Comment by charris** [comment]
I'll guess that the failures are not Python 2.7 specific? The 3.5 failures look different.

**Comment by pv** [comment]
Only 2.7 build uses the prerelease wheels. I repro'd locally on 3.6.

**Comment by charris** [comment]
Restarted a failed test and it passes after going back to OpenBLAS 0.3.0 for the wheels.

**Comment by pvanmulbregt** [comment]
With the revert of MacPython/numpy-wheels the master build passes again, as do the affected subtest in the PRs above.

**Comment by rgommers** [comment]
Thanks all!

Guess we'll have to deal with this at some point; did anyone open an OpenBLAS issue?
