### ISSUE TITLE
Implementing sparse + scalar

### ISSUE THREAD

**Issue by ericmjl** [scipy/scipy#9070]
Hello! I was wondering what would it take to implement sparse matrix + scalar, such that its behaviour matches what we get with numpy? It appears that this is [currently not supported](https://github.com/scipy/scipy/blob/master/scipy/sparse/base.py#L409). If given high-level guidance on what it would take, I am happy to take on the responsibility of putting in a PR.

**Comment by WarrenWeckesser** [comment]
Eric, thanks for  volunteering to do some development!  However, I don't think this is a desired feature.

The primary reason for representing a matrix in sparse format is that most of the values in the matrix are 0.  For a large matrix with low sparsity, a sparse matrix representation is much more efficient than a dense representation (i.e. a regular numpy array), in terms of both memory use and the performance of a wide range of elementary operations.

When a nonzero scalar is added to a sparse matrix, most of the values in the result are nonzero.  That is, the result is not sparse.  The sparse representation of a matrix that is not actually sparse is *very inefficient*.  So the result of adding a scalar to sparse matrix should really be a dense matrix.  But for many users, that would be a surprising result.  A general principle that we try to follow in scipy is to never automatically "densify" a sparse matrix.  In many applications, the memory required to do so would exceed the available memory.

Adding a scalar to a sparse matrix is intentionally not implemented, and I think it is better if we leave it that way.  This requires the user to explicitly convert their sparse matrix to a numpy array or matrix before adding a scalar to it.  Then no one is surprised or runs out of memory unexpectedly when the operation is performed.

**Comment by ilayn** [comment]
@hameerabbasi is working on this if I remember correctly in https://github.com/pydata/sparse . 

this = sparse array with a constant offset

**Comment by ericmjl** [comment]
@WarrenWeckesser thank you for getting back! Yes, that is right, I had completely forgotten that the current implementation would require adding the scalar to all the zero-elements in the sparse matrix. Thank you for the reminder! Also thank you @ilayn for pointing out sparse that this is being worked on in sparse. :smile:

Closing!

**Comment by hameerabbasi** [comment]
@ericmjl This has already been implemented on pydata/sparse#165. Go ahead and give it a try!
