### ISSUE TITLE
doc/linalg: add cho_solve_banded to see also of cholesky_banded

### ISSUE THREAD

**Issue by ewmoore** [scipy/scipy#9071]
See title. Maybe also improve the example in `linalg.cholesky_banded`.

 I'd just submit a PR, but I don't have git available right now.

**Comment by souravsingh** [comment]
I am willing to take a stab at this

**Comment by ilayn** [comment]
@souravsingh Go for it.

**Comment by shashvatshahi1998** [comment]
I am new to open source contribution but I also want to contribute to this.

**Comment by ilayn** [comment]
@shashvatshahi1998 Thanks for your interest. We don't really assign issues to individuals. You can send a pull request directly if noone else sent already. 

By the way, we have more in #7168 for grabs in case you feel like it.
