### ISSUE TITLE
Large array with "eig_banded" leads to illegal lwork value error in "sbevd"

### ISSUE THREAD

**Issue by fermat618** [scipy/scipy#9073]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

`scipy.linalg.eig_banded` failed when computing the eigenvalue and eigenvector of a large array of about the size 500x50000

### Reproducing code example:
```
import numpy as np
from scipy.linalg import eig_banded

A = np.random.random((500,50000))
eig_banded(A)
```

### Error message:
```
Intel MKL ERROR: Parameter 11 was incorrect on entry to DSBEVD.
Traceback (most recent call last):
  File "banded_eig_minimal.py", line 9, in <module>
    eig_banded(A)
  File "/home/bob/anaconda3.5/lib/python3.6/site-packages/scipy/linalg/decomp.py", line 626, in eig_banded
    _check_info(info, internal_name)
  File "/home/bob/anaconda3.5/lib/python3.6/site-packages/scipy/linalg/decomp.py", line 1074, in _check_info
    % (-info, driver))
ValueError: illegal value in argument 11 of internal sbevd
```

### Scipy/Numpy/Python version information:
```
1.0.0 1.14.0 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment]
For any routine that uses divide and conquer algorithm, the workspace size is quite large. Here the required WORK array has to have a size in the order of `O(2*n**2) > 2 500 000 000` and that number exceeds the max value of `2**31` (`2 147 483 648`) that is stored in `LWORK` 32bit integer variable.

Similar problem is also reported in [LAPACK forum for `?GESDD`](http://icl.cs.utk.edu/lapack-forum/viewtopic.php?f=2&t=1418) which also uses a divide-and-conquer algorithm. Thus, we can't do anything about this on SciPy side and unless LAPACK switches to 64-bit integers they won't be able to do anything either.

Even the storage required for the eigenvector matrix (`n x n`) is >20 GB. So you probably would have been hit with a MemoryError anyways . You can try to get selected eigenvalues by using the `select` key given in the documentation.

**Comment by fermat618** [comment]
Lapack use default size integers to represent to size of arrays. Long ago I use Fortran to call these functions,  linking to `libmkl_intel_ilp64.so' which is compiled with 64-bit integers. Recently I decided to use the scipy interface, which is much more convenient than the Fortran code. But I've never thought it is still a 32-bit interface, considering I am using 64-bit platform for such a long time.

The bit size of function should conform to the bit size of the platform. Since the Lapack is dealing with float numbers, integers are mainly used to represent the size of array or to present error code, it's reasonable to force numpy/scipy linked to 64-bit default integer size Lapack interfaces. If there's problems to make these function 64-bit, at least warnings should appear on the documentation page,  so that people who want large array support can quit quickly after checking the documentation.

**Comment by ilayn** [comment]
@fermat618 You might want to take this discussion over to https://github.com/Reference-LAPACK/lapack 

We don't have any control over this.

**Comment by fermat618** [comment]
You do have control over the documentation. When the platform is 64-bit but the high level function is actually a 32-bit one, there should be a warning.

**Comment by ilayn** [comment]
You can have 64-bit integers on 32-bit platforms. They are not related to the platform they run on. It is a choice and actually a very esoteric choice. Because if you increase the default integer size, then all routines will be affected by this. In particular, you would be wasting huge amount of memory on every WORK and IWORK array allocation. That is not something to be warned about because that is actually the standard (good or bad is a different discussion).

None of the systems would warn you about this because it is expected from any LAPACK/BLAS implementation. See the LAPACK forum page above.
