### ISSUE TITLE
eigenvalue sorting in scipy.sparse.linalg.eigsh

### ISSUE THREAD

**Issue by gauthe** [scipy/scipy#9082]
Hello,

I am using [scipy.sparse.linalg.eigsh](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigsh.html) to compute eigenvalues of a symmetric matrix. When largest in magnitude eigenvalues are computed (default), the order of the output eigenvalues change depending on the value of the parameter return_eigenvectors.

When return_eigenvectors=True (default), eigenvalues are sorted by algebraic value.
When return_eigenvectors=False, eigenvalues are sorted by magnitude value.

Note that both conventions are fine, and that the documentation does not specify any sorting. But returning a different order according to a non-linked parameter is highly unexpected.

### Reproducing code example:
```
import numpy as np
from scipy.sparse.linalg import eigsh

M = np.diag([2.]*100 + [-2.]*100 + [3.] + [-3.] + [1.]*1000)

print(eigsh(M,k=10,which='LM')[0])
print(eigsh(M,k=10,which='LM',return_eigenvectors=False))
```

### Output:
```
[-3., -2., -2., -2., -2.,  2.,  2.,  2.,  2.,  3.]
[ 2., -2.,  2., -2.,  2., -2.,  2.,  2.,  3., -3.]
```

### Scipy/Numpy/Python version information:
python 3.6.3
numpy version 1.14.3
scipy version 1.0.1

**Comment by akahard2dj** [comment]
Hello @gauthe,

I documented what you mentioned, `scipy.sparse.linalg.eigsh`.
Could you check the edited part?

**Comment by gauthe** [comment]
Thank for your answer,

I think the best would be to always sort with the same convention, but I understand the choice to update only the documentation.

In any case, after further tests the tricky part is that the sorting also depends on which.
- For which=LM (default, most common) or SA, it is as the commit says:
If `return_eigenvectors` is True, eigenvalues are sorted by algebraic value.
If `return_eigenvectors` is False, eigenvalues are sorted by absolute value.

- For which=BE or LA, the sorting is **always** by algebraic value
- For which=SM,
If `return_eigenvectors` is True, eigenvalues are sorted by algebraic value.
If `return_eigenvectors` is False, eigenvalues are sorted by **decreasing** absolute value.

So unfortunately the current version is inaccurate.

**Comment by akahard2dj** [comment]
I only though about the 'LM' case, but my thoughts were short.
I will revise each case you mentioned.
Thanks for you explanations. @gauthe

**Comment by gauthe** [comment]
Ok this seems correct.

I think it would be more intuitive to put these details into the `which` section instead of the `return_eigenvectors` one. Maybe be also add 'see notes in which for sorting convention' in the description of `w`.

**Comment by gauthe** [comment]
I looked at other part of the documentation.

- in the parameters, A is described as a real symmetric matrix, it can also be complex hermitian according to the function general description.

- in the example, the use of `id` is clumsy, since it is also a function (same for scipy.sparse.linalg.eigs)
- the result of the exemple is inaccurate: the result of eigsh is real, in the current version `vals` prints `array([ 1.,  1.,  1.,  1.,  1.,  1.])`

**Comment by akahard2dj** [comment]
@gauteh Yes, I also know that the example in this section, `scipy.sparse.linalg.eigsh`, very simple.
First of all, I will document the example in detail.
I will also more careful about parameter `A` before I revise the document.
Thanks.

**Comment by akahard2dj** [comment]
And also @gauthe, How about listening to the opinions of others and making decisions for put `return_eigenvectors` details into the `which` section?
The type of the order in which eigenvalues are sorted is affcted by `which` parameter. 
But I think it is correct to describe it in the `return_eigenvectors` part, as the result actually changes 
according to the value of `return_eigenvectors`.
What do you think about this @gauthe ?

**Comment by gauthe** [comment]
The discussion on return order can be either in the `which` section or in the `return_eigenvectors` section; since both kwargs change the result.

I personnally think the `which` section is more suited, since it always depends on `which`while it depends on `return_eigenvectors` only for LM, SM or SA. But this is mainly a matter of taste.

**Comment by rgommers** [comment]
Documented in gh-9134, closing.

**Comment by dooleysh** [comment]
Hi,

Possibly another complication in the ordering of eigenvalues in scipy.sparse.linalg.eigsh. The ordering seems to be different depending on whether the matrix dtype is real or complex.

Example:
```python
import numpy as np
from scipy.sparse import diags
from scipy.sparse.linalg import eigsh

M_1 = diags([1,2,3,4], dtype = float)
M_2 = diags([1,2,3,4], dtype = complex)

print(spla.eigsh(M_1, k=2, which='LA', return_eigenvectors=True)[0])
print(spla.eigsh(M_2, k=2, which='LA', return_eigenvectors=True)[0])
```

Output:
```python
[ 3.  4.]
[ 4.  3.]
```
