### ISSUE TITLE
savgol_filter _arraytools.py FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated

### ISSUE THREAD

**Issue by tvgebhardt** [scipy/scipy#9083]
In Python 3.6 & 3.7, running the below code generates the following error.  Do not see this problem <=Python 3.5

### Reproducing code example:

**from scipy.signal import savgol_filter
z_ary = [1,2,3,4,5]
savgol_result = savgol_filter(x=z_ary, window_length=3, polyorder=1, deriv = 1)**

### Error message:

**/usr/local/lib/python3.6/site-packages/scipy/signal/_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[a_slice]**

### Scipy/Numpy/Python version information:
scipy.__version__ = 1.1.0
numpy.__version__ = 1.15.0
sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)

**Comment by andreaschandra** [comment]
any update on this>

**Comment by larsoner** [comment]
These errors should be fixed in current `master` and will be released with 1.2.0

**Comment by jakirkham** [comment]
FWIW one can get a similar issue with `scipy.signal.correlate`. Was that solved as well?
