### ISSUE TITLE
`scipy.optimize.minimize` steps above upper bound, regardless of Bounds(keep_feasible=True)

### ISSUE THREAD

**Issue by ruaridhw** [scipy/scipy#9098]
Given a constrained optimisation problem, the `L-BFGS-B` routine (and perhaps others) step outside the prescribed bounds to estimate the gradient despite `keep_feasible = True`. Is this the correct usage of this parameter in `Bounds`?

Reprex below of a function where `ub + eps` results in an exception. I would have thought that when estimating the gradient at the upper bound, this should be done *below* the bound rather than always *adding* `eps`?

The workaround would be to manually specify `eps` as per this example and then redefine the bounds as `Bounds(lb, ub - eps)` however I wouldn't have thought this is ideal?

### Reproducing code example:
```python
import numpy as np
from math import log
from scipy.optimize import minimize, Bounds

eps = 1e-8

def f(x):
    print(x)
    return log(1 + eps - x)

f(0)
f(1)

x0 = np.array([0])
x_bounds = Bounds(np.array([0.]), np.array([1.]), keep_feasible = True)
res = minimize(fun = f, x0 = x0, method = 'L-BFGS-B', bounds = x_bounds, options = {'eps': eps})
```

### Error message:
```
0
1
[0.]
[1.e-08] # lb + eps
[1.]
[1.00000001] # ub + eps is infeasible
Traceback ... in f
    return log(1 + eps - x)
ValueError: math domain error
```

### Scipy/Numpy/Python version information:
```
1.1.0 1.14.5 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
IIRC, only the `trust-constr` solver respects that option.
However, either L-BFGS-B should respect the feasibility requirement, or fail with error immediately if the flag is set.

**Comment by andyfaff** [comment]
Issue is present in scipy 1.4.1, but is fixed in master. Probably by #10673
