### ISSUE TITLE
resample_poly returns float64 output for float32 input

### ISSUE THREAD

**Issue by pijyoi** [scipy/scipy#9104]
The resample_poly() function returns float64 output even when both the input array and the window array are float32.
The underlying call to upfirdn, on the other hand, does return float32 output for float32 inputs.

If we replace the following line in resample_poly() 
```
h = np.concatenate((np.zeros(n_pre_pad), h, np.zeros(n_post_pad)))
```
with
```
h = np.concatenate((np.zeros(n_pre_pad, dtype=h.dtype), h, np.zeros(n_post_pad, dtype=h.dtype)))
```
then resample_poly() will return float32 output for float32 inputs.

### Reproducing code example:
```
import numpy as np
from scipy import signal

x = np.arange(10, dtype=np.float32)
h = np.array([1,1,1], dtype=np.float32)
y1 = signal.resample_poly(x, 1, 2, window=h)
y2 = signal.upfirdn(h, x, 1, 2)
print(y1.dtype, y2.dtype)     # float64 float32
```

### Scipy/Numpy/Python version information:
```
1.0.1 1.13.3 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```
This behaviour is also present in the master branch:
https://github.com/scipy/scipy/blob/master/scipy/signal/signaltools.py#L2376

**Comment by larsoner** [comment]
That sounds like a good fix, can you make a PR?
