### ISSUE TITLE
Scipy build on OS X assumes that "c++" will get it Clang, even when it won't

### ISSUE THREAD

**Issue by interfect** [scipy/scipy#9107]
I am on OS X 10.13, with these compilers installed as `cc` and `c++`:

```
Vyoma:toil-vg anovak$ cc --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Vyoma:toil-vg anovak$ c++ --version
c++ (MacPorts gcc7 7.2.0_0) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

In a Python 2.7 virtualenv with numpy installed, doing `pip2.7 install scipy` produces a very long log, ending with something like:

```
    creating /var/folders/ws/t7b9wm2j2b7fy4_xyq0n5vh00000gn/T/tmpJVbgID/var
    creating /var/folders/ws/t7b9wm2j2b7fy4_xyq0n5vh00000gn/T/tmpJVbgID/var/folders
    creating /var/folders/ws/t7b9wm2j2b7fy4_xyq0n5vh00000gn/T/tmpJVbgID/var/folders/ws
    creating /var/folders/ws/t7b9wm2j2b7fy4_xyq0n5vh00000gn/T/tmpJVbgID/var/folders/ws/t7b9wm2j2b7fy4_xyq0n5vh00000gn
    creating /var/folders/ws/t7b9wm2j2b7fy4_xyq0n5vh00000gn/T/tmpJVbgID/var/folders/ws/t7b9wm2j2b7fy4_xyq0n5vh00000gn/T
    creating /var/folders/ws/t7b9wm2j2b7fy4_xyq0n5vh00000gn/T/tmpJVbgID/var/folders/ws/t7b9wm2j2b7fy4_xyq0n5vh00000gn/T/tmpJVbgID
    compile options: '-MMD -MF /var/folders/ws/t7b9wm2j2b7fy4_xyq0n5vh00000gn/T/tmpJVbgID/file.c.d -c'
    cc: /var/folders/ws/t7b9wm2j2b7fy4_xyq0n5vh00000gn/T/tmpJVbgID/file.c
    customize UnixCCompiler using build_ext
    get_default_fcompiler: matching types: '['gnu95', 'nag', 'absoft', 'ibm', 'intel', 'gnu', 'g95', 'pg']'
    customize Gnu95FCompiler
    customize Gnu95FCompiler
    customize Gnu95FCompiler using build_ext
    building 'scipy.interpolate._interpolate' extension
    compiling C++ sources
    C compiler: c++ -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe
    
    compile options: '-Iscipy/interpolate/src -I/Users/anovak/Documents/Workspace/toil-vg/.venv/lib/python2.7/site-packages/numpy/core/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c'
    c++: scipy/interpolate/src/_interpolate.cpp
    c++: warning: x86_64 conflicts with i386 (arch flags ignored)
    c++: error: unrecognized command line option '-Wshorten-64-to-32'
    c++: warning: x86_64 conflicts with i386 (arch flags ignored)
    c++: error: unrecognized command line option '-Wshorten-64-to-32'
    error: Command "c++ -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iscipy/interpolate/src -I/Users/anovak/Documents/Workspace/toil-vg/.venv/lib/python2.7/site-packages/numpy/core/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c scipy/interpolate/src/_interpolate.cpp -o build/temp.macosx-10.13-intel-2.7/scipy/interpolate/src/_interpolate.o -MMD -MF build/temp.macosx-10.13-intel-2.7/scipy/interpolate/src/_interpolate.o.d" failed with exit status 1
```

It looks like the build is passing `-Wshorten-64-to-32` to `c++` on the assumption that it is Clang.

If the build needs Clang specifically when building on Mac, shouldn't the build be invoking `clang` and not `c++`? If the build doesn't rely on Clang, but can work with GCC on OS X, shouldn't it be able to work out which compiler it has actually got? Does the build assume that `cc` and `c++` both point to "the same" compiler? (Because selecting MacPorts GCC [hasn't ever and doesn't want to](https://trac.macports.org/ticket/30434) set `cc`, but does set `c++`.)

If this is an upstream issue (i.e. the scipy build is just using whatever compiler and options it was handed), which package should I report the issue to, and how would I describe it? It looks like https://stackoverflow.com/a/46610651 suggests that "Python2.7 on Mac OS X is compiled with the alias "cc""; is this behavior somehow attributable to a bug in the Python binary?

I can work around the problem by doing `CC=/usr/bin/clang CXX=/usr/bin/clang++ pip2.7 install scipy`, but really the build should be clever enough to invoke the compiler it is written for by itself.

**Comment by rgommers** [comment]
> If the build needs Clang specifically when building on Mac

It doesn't. Any sane compiler works, hence you can set `CC` and `CXX` to gcc as you found out.

> If this is an upstream issue (i.e. the scipy build is just using whatever compiler and options it was handed), which package should I report the issue to

This is `numpy.distutils` behavior. I wouldn't call this a bug though; MacPorts setting `c++` but not `cc` is quite unusual. No one has reported such an issue before as far as I can remember.

> but really the build should be clever enough to invoke the compiler it is written for by itself.

Not really. `numpy.distutils` supports many compilers. If none is explicitly specified by the user, either via `CC/CXX` or via `python setup.py --config ...`, it just tries to grab a default one. 

Unless I'm missing something in my explanation, I think this is a wontfix.

I'll close the issue because it's not a SciPy one, but feel free to keep discussing.
