### ISSUE TITLE
documentation: scipy.spatial.KDTree vs. scipy.spatial.cKDTree

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#9108]
It seems to be not documented that scipy.spatial.KDTree accepts complex arrays, but scipy.spatial.cKDTree doesn't.

The docs seem to imply that they are equivalent.

**Comment by rgommers** [comment]
Thanks @keithbriggs, I wasn't aware of that. There seem to be zero tests for complex dtypes, so I'm not sure if it works on purpose or by accident. And if it e.g. works with all values for `p` of the minkowski distance. If you could supply a self-contained example that can be used as a test, that would be useful.

**Comment by peterbell10** [comment]
Looking at the `KDTree` code, the `minkowski_distance` does work for complex. But I don't think any of the tree building a querying code will work correctly. There's nothing that suggests to me that it was written with complex in mind.

Fundamentally, a KDTree relies on an ordering of points along each dimension, but no such ordering exists for complex numbers. The only reason it accepts complex numbers at all is a quirk in NumPy which uses lexicographic comparison of the real and imaginary components. 

Also, the helper class `Rectangle` discards the imaginary component:
https://github.com/scipy/scipy/blob/a49e96058264eab8b220da8ee7b64ab1c4a62a07/scipy/spatial/kdtree.py#L90
That means at least: `query_ball_point`, `query_ball_tree`, `query_pairs`, `count_neighbours` and `sparse_distance_matrix` are all completely broken.

For completeness, here's a counterexample for `KDTree`:
```python
In [1]: import numpy as np
In [2]: from scipy.spatial import KDTree, minkowski_distance
In [3]: coords = np.random.rand(1000, 2).view(complex)
In [4]: t = KDTree(coords)
In [5]: point = np.array([0 + 1j])
In [6]: np.count_nonzero(minkowski_distance(point, c) < 1) # Brute force query
Out[6]: 802

In [7]: t.query_ball_point(point, r=1)
/home/pbell/git/scipy/build/testenv/lib/python3.7/site-packages/scipy/spatial/kdtree.py:90: ComplexWarning: Casting complex values to real discards the imaginary part
  self.maxes = np.maximum(maxes,mins).astype(float)
/home/pbell/git/scipy/build/testenv/lib/python3.7/site-packages/scipy/spatial/kdtree.py:91: ComplexWarning: Casting complex values to real discards the imaginary part
  self.mins = np.minimum(maxes,mins).astype(float)
Out[7]: []

```

That said, I can imagine a complex `KDTree` would be possible. It would essentially be a `2K` dimensional tree which is split on imaginary and real components separately. Only the metric functions would need to be specifically aware of the complex numbers. Unless there's a very good reason to add this feature though, I'm inclined to just add an error to `KDTree` if any of the inputs are complex.

**Comment by keithbriggs** [comment]
Ok, thanks for checking. I agree it should report an error if the results aren't going to be meaningful.

**Comment by sturlamolden** [comment]
Yes, it should split on the real an complex parts separately, which means that all we need to do for this to work correctly is to view n x k complex array as n x 2k real data.
