### ISSUE TITLE
find_peaks errors out for constant "peaks" when prominence and wlen is specified

### ISSUE THREAD

**Issue by nateyoder** [scipy/scipy#9110]
When "peaks" are found among places with constant values

### Reproducing code example:
```
import numpy as np
from scipy.signal import find_peaks
data = np.ones(7)
data[0] = 0
data[-1] = 0
find_peaks(data, height=0.2, prominence=0.1, wlen=2)
```

### Error message:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-247ee153a6e8> in <module>()
      3 data[0] = 0
      4 data[-1] = 0
----> 5 find_peaks(data, height=0.2, prominence=0.1, wlen=2)

/home/ubuntu/src/anaconda2/envs/checkengine/lib/python2.7/site-packages/scipy/signal/_peak_finding.pyc in find_peaks(x, height, threshold, distance, prominence, width, wlen, rel_height)
    908         properties.update(zip(
    909             ['prominences', 'left_bases', 'right_bases'],
--> 910             peak_prominences(x, peaks, wlen=wlen)
    911         ))
    912 

/home/ubuntu/src/anaconda2/envs/checkengine/lib/python2.7/site-packages/scipy/signal/_peak_finding.pyc in peak_prominences(x, peaks, wlen)
    405         raise ValueError('`wlen` must be at larger than 1, was ' + str(wlen))
    406 
--> 407     return _peak_prominences(x, peaks, wlen)
    408 
    409 

_peak_finding_utils.pyx in scipy.signal._peak_finding_utils._peak_prominences()

ValueError: 3 is not a valid peak
```

### Scipy/Numpy/Python version information:
```
('1.1.0', '1.14.2', sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0))
```

**Comment by larsoner** [comment]
@lagru do you have time to look?

**Comment by lagru** [comment]
@nateyoder Thanks for the bug report!
@larsoner Yeah, I'll definitely have look.

**Comment by nateyoder** [comment]
@lagru thanks for looking at this so quickly!  My initial expectations were that those peaks would have a 0 prominence within the window I specified so they would be filtered out and no peaks would be returned.  I realize you need to think about a large set of potential use cases, but in my particular case I'd prefer to not have an error raised so that I can still get any other potential peaks. This is because I believe this happens anytime you have a plateau that is larger than the window size even if you have another "real" peak.

**Comment by lagru** [comment]
So it would be ideal if we could cover these two demands:

* Make it possible to find peaks, even if part of the specified peaks aren't valid at all / have a prominence of 0.
* But still notify the user if a prominence of 0 is calculated because this hints (for most use cases) at unintended behavior or faulty usage. 

Sounds like the perfect use case for a warning. Furthermore the function should be able to handle non-peaks just fine. This would require changing / expanding unit tests as well. 
@larsoner What do you think? If you agree I would  be willing to submit a PR for this in a couple of days.

**Comment by larsoner** [comment]
Sounds reasonable to me.
