### ISSUE TITLE
istft doc and code for 

### ISSUE THREAD

**Issue by bliep** [scipy/scipy#9113]
According to the signal.istft doc:

    This function implements the iSTFT via the least-squares esimation
    algorithm detailed in [2]_, which produces a signal that minimizes
    the mean squared error between the STFT of the returned signal and
    the modified STFT.
    .. versionadded:: 0.19.0
    References
    .. [1] Oppenheim, Alan V., Ronald W. Schafer, John R. Buck
           "Discrete-Time Signal Processing", Prentice Hall, 1999.
    .. [2] Daniel W. Griffin, Jae S. Limdt "Signal Estimation from
           Modified Short Fourier Transform", IEEE 1984,
           10.1109/TASSP.1984.1164317

However, performing phase estimation by LMS / Griffin&Lim is not reflected in code (AFAIK).
Am I missing something?

### Reproducing code example:
-
### Error message:
-
### Scipy/Numpy/Python version information:
1.1.0

**Comment by rgommers** [comment]
> However, performing phase estimation by LMS / Griffin&Lim is not reflected in code (AFAIK). Am I missing something?

That indeed seems to be missing. Probably was intended to be added but fell out of the initial PR. For now at least a doc update seems needed. @e-q could you comment on this?

**Comment by susnak** [comment]
If I may comment on this (not being involved in the development in any way). 
The Griffin-Lim reference also contains a formula for computing an optimal synthesis window for synthesis from the modified _complex-valued_ STFT.

**Comment by e-q** [comment]
The inclusion of the reference is referring to the fact that the `istft` code uses what is called "LSEE-MSTFT" (equation 6) in the reference to produce the signal from the *complex-valued* STFT.  

The following section of the reference develops the iterative LSEE-MSTFT**M** algorithm which estimates a signal given only the *magnitude* of the STFT (i.e. the spectrogram). `istft` was not written to perform this computation. This is not to say that we could or should not have functions to do so within scipy, however.

I will mark this as closed, but that does not preclude a PR/feature request.
