### ISSUE TITLE
Feature request: print estimated remaining computation time in scipy.interpolate.griddata()

### ISSUE THREAD

**Issue by Ethunxxx** [scipy/scipy#9117]
Would it be possible to have an option in scipy.interpolate.griddata() which allows one to print the estimated remaining computation time? 

I had the idea while I ran a big interpolation task with griddata(). It took quite some time and at some point I wasn't sure if the computation would take an hour (in which case I would've let it go on) or a week (in which case I would've aborted it). 

Since interpolation tasks can be very demanding in terms of computation I think this feature would be very useful for users to estimate whether using griddata() for a specific task makes sense or not.

**Comment by rgommers** [comment]
@Ethunxxx no I don't think so, sorry. There's no good way to reliably estimate that, and there's no precedent for such functionality.  I'd recommend that you benchmark your problem on a smaller dataset, and then from that estimate the timing.
