### ISSUE TITLE
documentation issues of functions in scipy.stats.mstats

### ISSUE THREAD

**Issue by chrisb83** [scipy/scipy#9119]
There is no documentation of the following functions in `mstats`:

- [ ] `sen_seasonal_slopes` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mstats.sen_seasonal_slopes.html)
- [x] `trimmed_var` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mstats.trimmed_var.html)
- [x] `trimmed_std` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mstats.trimmed_std.html)
- [x] `trimmed_mean`(https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mstats.trimmed_mean.html)

In general, there is little Information on the functions (references, examples), see e.g. https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mstats.mjci.html

Links to the functions in `stats` don't work: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.mstats.theilslopes.html#scipy.stats.mstats.theilslopes

**Comment by ilayn** [comment]
related #7168

**Comment by pv** [comment]
trimmed_var, trimmed_std, trimmed_mean fixed

**Comment by rgommers** [comment]
The only undocumented function left is `sen_seasonal_slopes`. Would be nice to give it a decent docstring, that would close this issue.

It's https://en.wikipedia.org/wiki/Theil%E2%80%93Sen_estimator (search for "seasonal" on that page). There are other "slopes" functions above it.

**Comment by yungchidanielcho** [comment]
Hi I joined pycon US mentored sprint and I’d like to provide the documentation for sen_seasonal_slopes function.

**Comment by ilayn** [comment]
That's great @yungchidanielcho let us know if you need any help.

**Comment by tylerjereddy** [comment]
Although we can't look at R source code because of licensing, I'm pretty sure they don't get a monopoly on the primary literature sources they cite, so those may help a bit, maybe 1 or 2 could be used in the "references" section.

If any of those are of use, but paywalled, let me know and I will try to retrieve it for you.

> Hipel, K.W. and McLeod, A.I. (1994), Time Series Modelling of Water Resources and Environmental Systems. New York: Elsevier Science.

> Hirsch, R., J. Slack, R. Smith (1982), T echniques of Trend Analysis for Monthly Water Quality Data. Water Resources Research 18, 107-121.

> Sen, P.K. (1968), Estimates of the regression coefficient based on Kendall's tau, Journal of the American Statistical Association 63, 1379–1389.

**Comment by mdhaber** [comment]
@yungchidanielcho Did you plan on adding the `sen_seasonal_slopes` documentation?

I'm going to go ahead and resolve the link rendering issue so it doesn't slip through the cracks.
