### ISSUE TITLE
Typo on scipy minimization tutorial

### ISSUE THREAD

**Issue by Quetzalcohuatl** [scipy/scipy#9122]
On this page https://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html#tutorial-sqlsp and many others where it is reproduced, there is a typo.

For the part that says:

> Sequential Least SQuares Programming (SLSQP) Algorithm 

The code says

```
ineq_cons = {'type': 'ineq',
             'fun' : lambda x: np.array([1 - x[0] - 2*x[1],
                                         1 - x[0]**2 - x[1],
                                         1 - x[0]**2 + x[1]]),
             'jac' : lambda x: np.array([[1.0, 2.0],
                                         [-2*x[0], -1.0],
                                         [-2*x[0], 1.0]])}
```

The first Jacobian is wrong, though. It forgot negative signs I believe. It should be 

```
ineq_cons = {'type': 'ineq',
             'fun' : lambda x: np.array([1 - x[0] - 2*x[1],
                                         1 - x[0]**2 - x[1],
                                         1 - x[0]**2 + x[1]]),
             'jac' : lambda x: np.array([[-1.0, -2.0],
                                         [-2*x[0], -1.0],
                                         [-2*x[0], 1.0]])}
```

I don't know where to submit typo request, so I am posting it here.

**Comment by akahard2dj** [comment]
It is seems to be right your comment. The jacobian has a partial derivative of a function.
That means the partial derivative of `1 -x[0] -2*x[1]` is `[-1, -2]`.
Should I take the this issue ?
I will commit and PR.

**Comment by akahard2dj** [comment]
#9128
