### ISSUE TITLE
doc error in scipy.integrate.dblquad

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#9124]
scipy.integrate.dblquad says gfun and hfun can be floats:

  gfun : callable or float
      The lower boundary curve in y which is a function taking a single floating point argument (x) and   returning a floating point result or a float indicating a constant boundary curve.
  hfun : callable or float
    The upper boundary curve in y (same requirements as gfun).

However:

>>> from scipy import integrate
>>> f = lambda y, x: x*y**2
>>> integrate.dblquad(f, 0, 2, lambda x: 0, lambda x: 1)
(0.6666666666666667, 7.401486830834377e-15)
>>> integrate.dblquad(f, 0, 2, gfun=0.0, hfun=1.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
 ...
  File "/usr/local/lib/python3.4/dist-packages/scipy/integrate/quadpack.py", line 504, in temp_ranges
    return [gfun(args[0]), hfun(args[0])]
TypeError: 'float' object is not callable

**Comment by ilayn** [comment]
I can't reproduce this too. 

What is the version of scipy you are using and which version of the docs you are looking at?

**Comment by keithbriggs** [comment]
1.0.1 and 1.1.0.


________________________________

**Comment by ilayn** [comment]
Indeed if you look at the [1.0.1 docs](https://docs.scipy.org/doc/scipy-1.0.0/reference/generated/scipy.integrate.dblquad.html#scipy.integrate.dblquad) `gfun` is only allowed to be a callable and added in version 1.1.0.

So if you update your scipy version, it would work.
