### ISSUE TITLE
doc error at https://docs.scipy.org/doc/scipy/reference/tutorial/stats/discrete_poisson.html

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#9135]
> in it’s own right

should be 

in its own right

**Comment by keithbriggs** [comment]
Also

> “sparsity “constraints.

should be

“sparsity“ constraints.

**Comment by matthew-brett** [comment]
Thanks - I made  pull request with the changes - have a look at #9137 ?

**Comment by keithbriggs** [comment]
Thanks - looks good now!


K
________________________________
