### ISSUE TITLE
doc error at https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.poisson.html

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#9136]
In the displayed formula, $mu^k$ should be $\mu^k$.

**Comment by matthew-brett** [comment]
Good spot - luckily this one was fixed a couple of months ago, in commit 9817c391a .  I guess we need a new build of the docs.

**Comment by ilayn** [comment]
Indeed, the dev version shows the correct formula http://scipy.github.io/devdocs/generated/scipy.stats.poisson.html#scipy.stats.poisson . Fixed in #8940
