### ISSUE TITLE
Document of `scipy.stats.pearsonr` is not right.

### ISSUE THREAD

**Issue by yarcowang** [scipy/scipy#9142]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
The document is not right:  
The formula of Pearson, lost another $\sum$ in sqrt.
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html#scipy.stats.pearsonr

Source: https://github.com/scipy/scipy/blob/v1.1.0/scipy/stats/stats.py#L2940
```
                  }{\sqrt{\sum (x - m_x)^2 (y - m_y)^2}}
```

**Comment by matthew-brett** [comment]
Yes, you're right - see #9143.

**Comment by chrisb83** [comment]
Closed in #9143
