### ISSUE TITLE
Solve for non-linear equation but minimise the difference vs initial input

### ISSUE THREAD

**Issue by lxsus** [scipy/scipy#9147]
hello,

I am looking to find the values for x and y given the below formula (portfolio risk). The code gives me a result however it is possible to have more than one solution for this problem i.e. different combinations of x and y can give me the same result.
However the solution that I am after is one that is least away from my initial x0 input. Therefore, x0 = 0.45 and there are solutions that exist for x = 0.40 and x = 0.35 I want the solver to return x =0.40. In effect I want a solution that minimises the difference between x and x0 ([minimise absolute (x-x0)]

```
from scipy.optimize import fsolve

def f(x) :
        port_risk = 0.06
        sd_EQ = 0.25
        sd_FI = 0.07
        Cor = -0.1
        return ((sd_EQ**2)*(x**2) + (sd_FI**2)*(y**2) + 2*Cor*sd_EQ*sd_FI*x*y)**0.5 - port_risk

x0 = 0.45354
x = fsolve(f, x0)

print ("x = ", x)
print ("y = ", y)
print ("f(x) =", f(x))
```

**Comment by ilayn** [comment]
Hi @lxsus 

This issue list is about the issues about the SciPy code itself. For usage questions you can try asking on Stackoverflow or related stackexchange sites such as [CompSci.SE](https://scicomp.stackexchange.com/)
