### ISSUE TITLE
replace_notes_in_docstring assumes docstrings exist

### ISSUE THREAD

**Issue by ddebrunner** [scipy/scipy#9150]
We hit a strange bug due to `cls_docstring` being `None` at this line.

https://github.com/scipy/scipy/blob/master/scipy/misc/doccer.py#L159

This was during the single use of the decorator `replace_notes_in_docstring` at:
https://github.com/scipy/scipy/blob/master/scipy/stats/_continuous_distns.py#L173

Now this was running with CPython embedded in our own framework and setting `PYTHONOPTIMIZE=2` as an environment variable before calling `Py_Initialize()`. This **removes docstrings**.

Not setting `PYTHONOPTIMIZE` made the issue go away.

However, I can't seem to reproduce it using the `python` command line with  `-OO` or the environment variable.

So I guess the bug is should the decorator be more defensive against the situation when docstrings do not exist?

### Reproducing code example:

See above - don't have a simple repo.

### Error message:
```
'NoneType' object has no attribute 'find'
```

### Scipy/Numpy/Python version information:
```
Python 3.5 with scipy 1.0.0
```

**Comment by ilayn** [comment]
Do you have a link to the CI error or can you please post the full the stack trace?

**Comment by rgommers** [comment]
Both `extend_notes_in_docstring` and `replace_notes_in_docstring` look indeed incorrect, they should handle the case where `cls_docstring` is None.

The difference between `PYTHONOPTIMIZE=` and `python -OO` is a bit odd, but not very interesting here I think. We just need to insert some `if cls_docstring is not None:` clauses.

**Comment by rlucas7** [comment]
Did this commit:
https://github.com/scipy/scipy/commit/baec434c9807d3ea17cf1896b14e9c37f05992e1
fix this issue?

**Comment by ilayn** [comment]
Yes #9385 fixed this. Test is already running on Travis matrix as a job with PYTHONOPTIMIZE=2 set.
