### ISSUE TITLE
linprog in python does not work properly?

### ISSUE THREAD

**Issue by mumtaz23** [scipy/scipy#9151]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

### Reproducing code example:
```
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```

### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```

**Comment by mdhaber** [comment]
@mumtaz23 There are several known bugs, many of which will be fixed in the next release. In the meantime, try `method='interior-point'`.
