### ISSUE TITLE
Geometric standard deviation

### ISSUE THREAD

**Issue by kalekundert** [scipy/scipy#9154]
Small issue, but I wonder if it would make sense to add a geometric standard deviation function (e.g.
 ``scipy.stats.gstd()``) to go along with the geometric mean function (``scipy.stats.gmean()``).  I'd be willing to make a PR if there's interest.

**Comment by chrisb83** [comment]
I haven't used geometric mean / std, but it makes sense to have gstd as an additional to gmean in my view.

**Comment by Kai-Striega** [comment]
@kalekundert Do you still want to add this? If not I'll take a look at it over the next few day.

**Comment by kalekundert** [comment]
Go for it; I clearly haven't made any progress in the last few months. :-)
