### ISSUE TITLE
documentation of pearson3 in scipy.stats unclear

### ISSUE THREAD

**Issue by chrisb83** [scipy/scipy#9168]
The documentation of distribution `stats.pearson3` is confusing. The density only has a single shape parameter, but it is defined implicitly in terms of loc, skew and stdev. It is not clear what the standard form is.

Scipy Version 1.1.0:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearson3.html#scipy.stats.pearson3

**Comment by josef-pkt** [comment]
I don't remember anything about this #336
(my comment there says it's just generalized gamma that allows for "negative scale", i.e. a linear transformation of gamma)

**Comment by chrisb83** [comment]
This reference looks helpful and mentions some relation of the parameters to the skewness as in the docstring: http://www.tc.faa.gov/its/worldpac/techrpt/ar03-62.pdf
In the standard form, it should just be a one-parameter distribution.

The implementation looks quite strange, see the `_preprocess` step and the comments therein:

```
def _preprocess(self, x, skew):
        # The real 'loc' and 'scale' are handled in the calling pdf(...). The
        # local variables 'loc' and 'scale' within pearson3._pdf are set to
        # the defaults just to keep them as part of the equations for
        # documentation.
        loc = 0.0
        scale = 1.0

        # If skew is small, return _norm_pdf. The divide between pearson3
        # and norm was found by brute force and is approximately a skew of
        # 0.000016.  No one, I hope, would actually use a skew value even
        # close to this small.
        norm2pearson_transition = 0.000016

        ans, x, skew = np.broadcast_arrays([1.0], x, skew)
        ans = ans.copy()

        # mask is True where skew is small enough to use the normal approx.
        mask = np.absolute(skew) < norm2pearson_transition
        invmask = ~mask

        beta = 2.0 / (skew[invmask] * scale)
        alpha = (scale * beta)**2
        zeta = loc - alpha / beta

        transx = beta * (x[invmask] - zeta)
        return ans, x, transx, mask, invmask, beta, alpha, zeta

    def _argcheck(self, skew):
        # The _argcheck function in rv_continuous only allows positive
        # arguments.  The skew argument for pearson3 can be zero (which I want
        # to handle inside pearson3._pdf) or negative.  So just return True
        # for all skew args.
        return np.ones(np.shape(skew), dtype=bool)

```

**Comment by akahard2dj** [comment]
This `pearson3` is seems to be confusing to use.
In my opinion, this function first needs to decide whether to use only the 'skew' value 
or the value containing 'loc' and 'scale'.
From `_preprocess`, it seems that it computes the generalized parameter,x, defined by loc=0, scal=1.0.
So we need to specify this part of the document.

**Comment by WarrenWeckesser** [comment]
`pearson3` is a reparameterization of the three parameter gamma (i.e. gamma with shape, location and scale parameters).  Most of the papers that talk about the Pearson 3 distribution state this within the first couple paragraphs.

The connection is demonstrated with this code, in which the two PDF plots are exactly the same:

```
import numpy as np
from scipy.stats import gamma, pearson3
import matplotlib.pyplot as plt


# Pearson 3 parameters:
skew = .75
loc = 0
scale = 1.5

# Parameters for the equivalent gamma distribution:
beta = 2.0 / (skew*scale)
alpha = (scale * beta)**2
zeta = loc - alpha/beta


x = np.linspace(-5, 10, 500)

plt.plot(x, pearson3.pdf(x, skew, loc=loc, scale=scale),
         color='k', ls='--', label='pearson3')
plt.plot(x, gamma.pdf(x, alpha, loc=zeta, scale=1/beta),
         color='g', lw=4, alpha=0.3, label='gamma')

plt.xlabel('x')
plt.ylabel('PDF(x)')
plt.grid()
plt.legend(loc='best', shadow=True)
plt.show()
```

Plot:

![Figure_1](https://user-images.githubusercontent.com/321463/70769137-4027a180-1d36-11ea-8bdc-b8c8a6767732.png)

**Comment by mdhaber** [comment]
The documentation is written for a Pearson3 PDF that takes three parameters: skew, loc, and scale; it's really like f(x, skew, loc, scale).

Consider g(x, skew) = f(x, skew, loc=0, scale=1).
If you plug through the math, you find that g( (x - loc) / scale , skew) / scale = f(x, skew, loc, scale). 

I adjusted the documentation accordingly.
