### ISSUE TITLE
does scipy.interpolate.UnivariateSpline.derivative(n=2)(x) mean the 2-order derivative at x?

### ISSUE THREAD

**Issue by retsyo** [scipy/scipy#9179]
I am using scipy 1.1.0 and numpy 1.12.1 which are supplied by `anaconda python` latest.

As we know, `dsin(x)/dx = cos(x)` and `d2sin(x)/dx2 = -sin(x)`

In the following example, I first interpolate discreted sine curve and get spline `s1`. The figure proves that `s1` is nearly the cosine curve.

As [doc](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.UnivariateSpline.derivative.html) says, `s1.derivative(n=2)` returns a new spline representing the 2-order derivative of this spline, so I think `s1.derivative(n=2)(x)` should be `-sin(x)`. But the result shows that `s1.derivative(n=2)(x)` is almost a straight line. Why? Did I misunderstand the document?

```python
import scipy.interpolate as inter
import numpy as np
import pylab as plt

import scipy

print(scipy.__version__)
print(np.__version__)

x = np.arange(0, 2*np.pi, 0.1)
y = np.sin(x)

s1 = inter.UnivariateSpline (x, y)

plt.plot (x, y, 'bo', label='Data')

plt.plot (x, s1(x), 'k--', label='Spline, s=default')

plt.minorticks_on()

plt.plot(x, s1.derivative(1)(x), 'd', label='df/ds')
plt.plot(x, s1.derivative(n=2)(x), 'p', label='d2f/ds2')

plt.legend()
plt.xlabel('x')
plt.ylabel('y')
plt.show()
```
thanks

![figure_1](https://user-images.githubusercontent.com/7960913/44626537-b28c2c80-a90d-11e8-972f-69d2707a9394.png)

**Comment by ev-br** [comment]
UnivariateSpline constructs, essentially, a piecewise cubic polynomial. The second derivative of a cubic parabola is indeed a linear function, so it's all consistent.

**Comment by WarrenWeckesser** [comment]
@retsyo, your code will work as you expected if you tell `UnivarateSpline` to use no smoothing.  That is, create `s1` with the option `s=0`:

    s1 = inter.UnivariateSpline (x, y, s=0)

Here's the plot that is generated after making that change:

![figure_1](https://user-images.githubusercontent.com/321463/44627883-d34f8480-a903-11e8-8dca-0ae611d32cba.png)
