### ISSUE TITLE
No complex arguments in scipy.special.zeta or scipy.special.zetac

### ISSUE THREAD

**Issue by sohambhattacharyya** [scipy/scipy#9182]
This is a feature request. Complex numbers are not supported by the scipy.special.zeta and scipy.special.zetac functions.

### Reproducing code example:
```
zeta(2+1j)
```

### Error message:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-07480cb9365e> in <module>()
----> 1 zeta(2+1j)

/usr/local/lib/python3.6/dist-packages/scipy/special/basic.py in zeta(x, q, out)
   2461     if q is None:
   2462         q = 1
-> 2463     return _zeta(x, q, out)
   2464 

TypeError: ufunc '_zeta' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

### Scipy/Numpy/Python version information:
```
0.19.1 1.14.5 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

**Comment by akahard2dj** [comment]
Looking at the documentation of [`scipy.special.zeta`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.zeta.html#scipy.special.zeta), the input parameter `x` must be an real.
```
Parameters:   x : array_like of floatInput data, must be real
```

**Comment by sohambhattacharyya** [comment]
Hmm I see. It's supposed to take complex arguments though. It's doable manually. Didn't try on the [cephes/zeta.c](https://github.com/scipy/scipy/blob/master/scipy/special/cephes/zeta.c) file.

**Comment by person142** [comment]
@sohambhattacharyya an important question here is what application you have in mind when requesting complex arguments. The "standard" application for complex arguments of the Riemann zeta function is of course investigating the zeros along the critical strip, and this is not at all a procedure for which SciPy is suitable. Our special functions typically only accept double precision arguments, and properly investigating zeros requires using arbitrary precision. Arbitrary precision arguments are, at least for now, out of scope for SciPy.

**Comment by rgommers** [comment]
Okay looks like that's a no to the feature request for the time being. So closing.
