### ISSUE TITLE
Discrete Distribution Yule-Simon support

### ISSUE THREAD

**Issue by rlucas7** [scipy/scipy#9183]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
I am what some might call a domain expert in statistics (my PhD is in statistics). I've derived some results on the yule simon distribution and would like to implement them in the scipy library. 

I'm willing to implement the distribution myself and do a pull request. However, I want to confirm support for the distribution with the core developer team before I begin the work of coding. Can someone confirm (or deny)? 

Here is [the link to the paper](https://arxiv.org/pdf/1710.08511.pdf) 

where we derive the variance of the estimator, and give a new framework to think about the procedure for estimation (same algorithm was derived in a previous paper via a maximum likelihood argument, we derive via an em algorithm which gives a variance estimate and a convergence proof for a subset of the values of the parameter)

here are some related papers on [yule simon](https://scholar.google.com/scholar?q=related:F6IAd0FjgsUJ:scholar.google.com/&hl=en&as_sdt=0,33)

and [a paper by Devroye](http://luc.devroye.org/digammapaper.ps) to simulate the random variable (yule simon as a special case of some more general random variate):

In the meantime I'm more than happy to do one of the "good first issue" issues in the scipy repo to get started contributing. 
### Reproducing code example:
```
<<A short code example that reproduces the problem. It should be self-contained, i.e., possible to run as-is via 'python myproblem.py'>>
```

### Error message:
```
<<Full error message, if any (starting from line Traceback: ...)>>
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
```

**Comment by rlucas7** [comment]
@rgommers,  Thanks for your encouragement! we'll start working on the implementation.

**Comment by rlucas7** [comment]
@rgommers, I've been hacking away on my forked repo: 
I think the code is working as intended and I'm thinking about unit tests. 
This came up as I poked around the api:

Lucass-MacBook:tests rlucas$ python -V
Python 3.6.6 :: Anaconda, Inc.
Lucass-MacBook:tests rlucas$ python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy.stats import cauchy
>>> cauchy(0).mean()
nan
>>> cauchy(0).expect()
0.0

The issue would arise w/Yule-Simon as well if the Yule-Simon parameter \alpha is such that 0 < \alpha < 1 where the mean in infinite. The expect() method defaults to numeric integration w/o checking the result of mean()-if there is an implementation that overrides the expect(). Do you think this expected behavior or should I open an issue? 

I've been trying to send this email to the scipy-dev@python.org email list but my email keeps getting returned as undeliverable.

**Comment by rgommers** [comment]
> I've been trying to send this email to the scipy-dev@python.org email list but my email keeps getting returned as undeliverable.

Did you sign up successfully? Can be done at https://mail.python.org/mailman/listinfo/scipy-dev. I'm not aware of issues with that recently.

**Comment by rgommers** [comment]
> cauchy(0).mean()
> nan

Well, the mean for cauchy is undefined (see e.g. https://en.wikipedia.org/wiki/Cauchy_distribution). The `0` in there does nothing (it's equivalent to `cauchy(loc=0)` which is the default value for `loc`). So that looks right to me.

And the Cauchy distribution is symmetric, so `0` looks also like the right answer to me for `cauchy.expect()`.

Am I missing something?

**Comment by rlucas7** [comment]
@WarrenWeckesser, yes, also any r.v. with an mean() of inf as return value has the same issue. 
it sounds like this is an issue.  I'll open an issue and put this context in the issue. 

I was confused about whether there was a specific use case where a numeric value was needed even if the expected value is inf or nan. After reading your reply, I'm clear that this is a conceptual issue. If a numeric value is needed another method (not mean() or expect() ) should be used.

**Comment by rlucas7** [comment]
Been working on this over here:
https://github.com/rlucas7/scipy/tree/yule_simon_dev

given the issue with the infinite variances I've taken the `.stats()` method out of the distribution and inherited the default. I've got unit tests and documentation (including doc strings).  

I think I'm ready for the pull request, anything obvious I'm missing?

**Comment by rlucas7** [comment]
pull request to close the issue

https://github.com/scipy/scipy/pull/9309
