### ISSUE TITLE
Mann-Whitney implementation wrong?

### ISSUE THREAD

**Issue by Canas** [scipy/scipy#9184]
Mann-Whitney test U values are defined as follows, according to various sources I found:

![image](https://user-images.githubusercontent.com/2435560/44748283-c9857700-aae5-11e8-9162-431624c688fc.png)
where
![image](https://user-images.githubusercontent.com/2435560/44748334-ef128080-aae5-11e8-8a0c-82f906d1c86b.png)
![image](https://user-images.githubusercontent.com/2435560/44748354-f9347f00-aae5-11e8-8c2f-e72804e258e3.png)

yet on [scipy's definition](https://github.com/scipy/scipy/blob/master/scipy/stats/stats.py), I see that u1 and u2 are defined as:
```
u1 = n1*n2 + (n1*(n1+1))/2.0 - np.sum(rankx, axis=0)  # calc U for x
u2 = n1*n2 - u1  # remainder is U for y
```

which according to the above definitions is the same as doing `u1 = u1 + u2 - u1 = u2`, effectively reversing u1 and u2 when doing the rest of the calculations. Am I missing something? Thanks

My Scipy version is 1.1.0.

**Comment by chrisb83** [comment]
It looks like u1 and u2 are indeed reversed in the Implementation compared to the definition in Wikipedia that ist in line with the one above. For the two-sided test, it does not matter since the minimum of u1 and u2 is taken. I haven't checked if this is a problem for the one-sided test.

**Comment by rgommers** [comment]
Probably useful: gh-4933 is a mostly complete but stalled PR to deprecate `mannwhitneyu` (IIRC it had multiple issues) and replace it with something better under a different name.

**Comment by Canas** [comment]
@chrisb83 : Yes, results won't matter when you take the min, but [the docs explicitly state](https://github.com/scipy/scipy/blob/v1.1.0/scipy/stats/stats.py#L4855-L4960) that when not using the min, the U value returned is for the second array (y), which is not correct since the reversed implementation is actually returning the U for the first array (x).

@rgommers : It seems it will take a while to see any changes regarding that. Maybe I could submit a PR fixing the reversed output to have consistent docs at least?

**Comment by chrisb83** [comment]
```
import sys, scipy, numpy; 
print(scipy.__version__, numpy.__version__, sys.version_info)
1.0.0 1.14.1 sys.version_info(major=3, minor=5, micro=4, releaselevel='final', serial=0)

x = (0.80, 0.83, 1.89, 1.04, 1.45, 1.38, 1.91, 1.64, 0.73, 1.46)
y = (1.15, 0.88, 0.90, 0.74, 1.21)
mannwhitneyu(x, y, alternative='less') # 35.0, p=0.9008
mannwhitneyu(x, y, alternative='greater') # 35.0, p=0.1223
mannwhitneyu(x, y, alternative='two-sided') # 35.0, p=0.2446
```

With R version 3.4.1, I get exactly the same:
```
x <- c(0.80, 0.83, 1.89, 1.04, 1.45, 1.38, 1.91, 1.64, 0.73, 1.46)
y <- c(1.15, 0.88, 0.90, 0.74, 1.21)
wilcox.test(x, y, alternative = "less", exact = FALSE) # W = 35, p = 0.9008
wilcox.test(x, y, alternative = "greater", exact = FALSE) # W = 35, p = 0.1223
wilcox.test(x, y, alternative = "two.sided", exact = FALSE) # W = 35, p = 0.2446
```

I took the example from https://stat.ethz.ch/R-manual/R-devel/library/stats/html/wilcox.test.html. (wilcox.test is the same test as Mann-Whitney if `paired = FALSE`, the default), so at least the implementation looks ok in that case, so it seems to be a documentation error only. 

```
n1 = len(x)
n2 = len(y)
ranked = rankdata(np.concatenate((x, y)))
rankx = ranked[0:n1]
u1 = sum(rankx) - n1*(n1+1)/2 # 35.0, this is u1 according to Wikipedia / initial comment; u2 in scipy
```

**Comment by mdhaber** [comment]
Summary: the comments in the code for `u1` and `u2` are reversed; `u2` actually is the test statistic corresponding with the first input `x`. The `u2` statistic is returned for all of the valid alternatives, so the behavior is not consistent with the documentation, which states that the returned statistic is `U for y`. I'll make sure this is correct in the new code.

**Comment by syoui000** [comment]
I can get why u = u1.  However, as we know the smaller u would be used for z, p, but bigu = max(u1, u2) is used in the code of scipy.stats.mannwhitneyu. I am so confused why take this choice. Anyone can help explain where I misunderstanded?
![微信截图_20240521190559](https://github.com/scipy/scipy/assets/109398962/2428e6af-c793-4987-91d0-2a14bf1480a7)

**Comment by mdhaber** [comment]
This repo is for bug reports and enhancement requests, whereas this looks like a question better suited for a Stack Exchange site. I'd be happy to answer there if I see it.
