### ISSUE TITLE
fourier_gaussian returning strange result

### ISSUE THREAD

**Issue by jakirkham** [scipy/scipy#9194]
When running `fourier_gaussian` from SciPy's `ndimage`, seem to be getting an inaccurate result with SciPy 1.0.0+. The problem is not present in SciPy pre-1.0.0 (e.g. 0.19.1).

### Reproducing code example:

From SciPy 0.19.0:

```python
In [1]: import numpy as np

In [2]: import scipy.ndimage as spimg

In [3]: spimg.fourier_gaussian(np.arange(5, dtype=float), 1)
Out[3]: array([ 0.        ,  0.45404074,  0.08499811,  0.12749717,  1.81616295])
```

From SciPy 1.1.0:

```python
In [1]: import numpy as np

In [2]: import scipy.ndimage as spimg

In [3]: spimg.fourier_gaussian(np.arange(5, dtype=float), 1)
Out[3]: 
array([0.00000000e+000, 5.21447985e-315, 5.11268236e-315, 5.14003652e-315,
       5.29737031e-315])
```

### Scipy/Numpy/Python version information:
```
1.1.0 1.15.1 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

**Comment by jakirkham** [comment]
Interestingly this problem does not exist for `np.float32`.

**Comment by WarrenWeckesser** [comment]
Not surprisingly, this is the same bug as https://github.com/scipy/scipy/issues/9195.  I closed that one, since this one was created first.

**Comment by WarrenWeckesser** [comment]
Ostensibly, the fix is trivial.  In the line https://github.com/scipy/scipy/blob/master/scipy/ndimage/src/ni_fourier.c#L427, change `npy_float` to `npy_double`.  This will fix the problem that currently exists for `fourier_gaussian`, `fourier_uniform` and `fourier_ellipsoid`.  The change will need unit tests for these functions.  I'm not familiar with the precise semantics of these function (e.g. I'm not sure why, even when the inputs are real, the outputs are not complex) nor the implementations.

@jaimefrio, could you take a look?  For inputs such as `fourier_gaussian(np.arange(5.0), 1)` or `fourier_uniform(np.arange(5.0), 1)`, how would one create the expected result "by hand"?  For example, `fourier_uniform` says the input is multiplied by the Fourier transform of a box of the given size.  I haven't found the right interpretation of that statement to generate the same output as `fourier_uniform(np.arange(5.0), 1)`.

**Comment by jakirkham** [comment]
The Fourier transforms of a Gaussian or a Uniform filter are both defined completely in real space. So it makes sense to have them support real numbers and even return only real types when provided real types. Otherwise one is needlessly doubling the size of the data to make it complex type (while the complex portion is merely zero).

**Comment by WarrenWeckesser** [comment]
> The Fourier transforms of a Gaussian or a Uniform filter are both defined completely in real space. 

OK, if you correctly choose the phase of, for example, the "box" used for the uniform filter, a real output should be expected (and I expect that's how `fourier_uniform` would work).

Are you able to generate such an output that matches (the old, presumabley correct) `fourier_uniform(np.arange(5.0), 1)` by multiplying `np.arange(5.0)` by the transform of  "a box of the given size"?

**Comment by jakirkham** [comment]
Not sure I follow. What do you mean by phase of the box? Also is there a corresponding option for this in `fourier_uniform`?

Yes, that's how I ran into this bug in the first place.

**Comment by WarrenWeckesser** [comment]
> What do you mean by phase of the box?

The sequences [1, 1, 0, 0, 0] and [0, 0, 1, 1, 0] can both be called "boxes" of length 2 within a sequence of length 5.  By "phase", I just mean the position of the box in the sequence.  Of the five possible positions, it is only [0, 0, 1, 1, 0] that has a discrete Fourier transform with coefficients that are real.

(By the way, I know I'm being lazy by not just digging into the source to see what it does.  That's not something I want to spend time on at the moment.  I had hoped the description of the function provided in the docstring would be sufficient to create some simple test cases by hand.)

**Comment by jakirkham** [comment]
Sure that makes sense. Though I don't see an option in `fourier_gaussian` or `fourier_uniform` for this behavior.

This [code]( https://github.com/dask/dask-image/blob/126d0a6a4ed70c0fed199978eee7668eef75dcbe/dask_image/ndfourier/__init__.py#L194-L205 ) does an equivalent thing to what the old SciPy code does. Basically build a grid using `fftfreq` ( as described in issue https://github.com/numpy/numpy/issues/9094 ), multiplies by box size, calls `sinc`, and takes the product due to each dimension of the box.

**Comment by jakirkham** [comment]
Added PR ( https://github.com/scipy/scipy/pull/9229 ). Probably could use a pointer on where to add a test.
