### ISSUE TITLE
solve_ivp RK45 can evaluate the function at times later than t_span[1]

### ISSUE THREAD

**Issue by grodstein** [scipy/scipy#9198]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>
When I call scipy.integrate.solve_ivp (fun, [100,200], y0), it proceeds to evaluate fun(234). Since 234 is out of the range [100,200], this causes fun (which is my code, not in scipy) to crash. One might argue that this is not a bug (since I see nowhere in the documentation where this behavior is explicitly disallowed) -- but I would argue that it is certainly not expected behavior.
I narrowed it down to the function select_initial_step() in common.py. This function calculates f1 = fun(t0 + h0 * direction, y1); in my case t0=100, h0=134 and direction=1. I would argue that you really should be doing something like f1 = fun(min (t1, t0 + h0 * direction), y1) instead. However, t1 is not even a parameter to this function, unfortunately.

### Reproducing code example:
See the .zip archive below, and run oscillators.py

### Error message:
N/A; the error is coming from my own code, which gets confused at being passed an out-of-range value.

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
1.0.1 1.14.2 sys.version_info(major=3, minor=4, micro=2, releaselevel='final', serial=0)

[x1.zip](https://github.com/scipy/scipy/files/2340359/x1.zip)

**Comment by MatthewFlamm** [comment]
Does setting max_step=10, for example, solve this issue?

Do you have a minimal example of this behavior? Your attached code is quite complex to parse.

**Comment by grodstein** [comment]
Good thought... but setting max_step doesn't seem to help. I guess that's not surprising -- the function select_initial_step() in common.py doesn't even use max_step.

As far as simplifying the calling environment, certainly I could do that with enough work, but would that really help much? The issue has (I believe) already been isolated to a specific function inside of common.py. All people really have to is instantiate the calling environment (which is hopefully easy), rather than understand it (which I agree is harder). Anyway, I'll start cutting down some of the low-hanging fruit and update the thread when I've got that done. /Joel

**Comment by MatthewFlamm** [comment]
I'm not dismissing that this isn't an actual problem,  just trying to get to root cause here. I'm using scipy 1.1.0.

I can see that the first step of the code on my system is <<1 after it first calls select_initial_step.   In fact, the error doesn't appear until t=100 or the step before t=100, so it seems to me like is some logical error in your delay function or implementation somehow.

**Comment by MatthewFlamm** [comment]
PS -  If I'm interpreting your code correctly, I would consider using a dedicated delay differential equation solver rather than implementing a delay function this way.  Unfortunately, I do not have any experience with any in Python to recommend.

**Comment by grodstein** [comment]
Agreed that the issue does not arise until the second call to solve_ivp(). However, unless you're suggesting that solve_ivp() has global state from call to call, and furthermore that the first call to solve_ivp() has somehow corrupted that state from inside of my user function, it's hard for me to see how the issue could be on my end.

I'll try to simplify the calling code further, but that will take considerably more effort.

**Comment by grodstein** [comment]
You are indeed interpreting it correctly, and I had considered using a
dedicated delay-differential-equation solver. However, I had vetoed that,
since (a) like yourself, I have little experience with those, (b) the use
of delay differential equations rather than ODEs is only a very occasional
requirement in my code anyway, and (c) I was thus more concerned with
keeping the mainline code simple rather than making the delay-line code
efficient.
Thanks for the suggestion, nonetheless.

**Comment by grodstein** [comment]
OK, I've simplified it *very* substantially. Sorry for not succeeding at doing this sooner. The remaining code is all of 20 lines long (of which maybe 1/3 of them are blank lines or error checkers). It only calls solve_ivp() once, which quickly exhibits the issue.
[oscillators .py.gz](https://github.com/scipy/scipy/files/2376080/oscillators.py.gz)

**Comment by WarrenWeckesser** [comment]
There is nothing in the `solve_ivp` API documentation that says `solve_ivp` won't evaluate the given function at times later than `t_span[1]`.

In general, it is normal for ODE solvers to do so.  For example, the CVODE solve in the [SUNDIALS](https://computation.llnl.gov/projects/sundials) suite (a C library) has a specific [option to control this](https://computation.llnl.gov/projects/sundials/usage-notes); when the solver's mode is `NORMAL`, the solver will generally evaluate the function at times past the last requested value.  One has to specifically use the mode `NORMAL_TSTOP` to prevent the solver from doing so.  `solve_ivp` does not have such an option.  So while this is not a bug in `solve_ivp`, it can certainly be considered an enhancement request.

**Comment by WarrenWeckesser** [comment]
... and, as usual, I forgot to say this first:  @grodstein, thanks for reporting this, and for taking the time to create a simplified example of the issue!

**Comment by MatthewFlamm** [comment]
Thanks for the clarification @WarrenWeckesser  and simplified code @grodstein.  I would also say that this case is still unexpected (possibly a bug) since a max_step was specified.  My reading of the CVODE usage notes is that it can evaluate at times later than t_span[1], but those times would _still_ be subject to the constraints of the integrator options.  In this case, I would expect that each step could not be larger than max_step, yet this is seemingly violated here.  Note that even if this were addressed, the function could still evaluate at a time greater than t_span[1], but it would be a more expected result.  As it stands, max_step=100, yet the first step attempt evaluates at t=134.  It would be more expected if max_step=60, for example, and the solution steps from t=0 to 60 to 120 seconds.

I would also note that the integrator reduces the time step to satisfy max_step, but only after select_initial_step violates this constraint.  It isn't clear to me how to incorporate this into select_initial_step without reading the referenced material in the docstring.

A workaround for this application is to log a warning rather than an error in your code.  The actual first step should satisfy your max_step constraint.

**Comment by grodstein** [comment]
@MatthewFlamm: I agree that, while solve_ivp() is eventually picking a step that satisfies the max_step constraint, it is first evaluating at a time that would eventually violate that constraint. Your workaround doesn't work for me, though -- the error that the code logs is merely to highlight the issue as simply as possible. In the real example, the out-of-bounds function evaluation eventually caused a crash.

**Comment by MatthewFlamm** [comment]
As far as I can tell, the out-of-bounds function evaluation should not affect the solution at all.  It merely is used to select the initial step size.  It is not saved or used subsequently.  The integrator chooses the first step with max_step as a constraint, which will be the first saved value in the solution.  Now, it is still possible that the integrator will evaluate past t_span[1] later as was pointed out.  You could also try lowering your tolerances which may force a lower time step selection.

I should also say that I only investigated the behavior in rk.py with regards to the above, which is the method being utilized in your example.  My experience with delay differential equations is that they are tricky to implement in the fashion you are choosing.

**Comment by grodstein** [comment]
Does anyone have useful instructions on how to add the "enhancement" label to this issue? I've read the documentation on doing so three times already -- it seems to just be incorrect.

Location of the documentation: https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/
What the documentation says:
1. On GitHub, navigate to the main page of the repository. # Done; went to https://github.com/scipy/scipy/
2. Under your repository name, click  Issues or  Pull requests.  # Done, albeit with some ambiguity. There are two buttons, both labeled "Issues". I've tried both
3. Select the checkbox next to the items you want to apply a label to. # THERE ARE NO SUCH CHECKBOXES
4. In the upper-right corner, click Label,  # AGAIN, NO SUCH BUTTON SEEMS TO EXIST.

So unless somebody jumps in to clarify the documentation, that's the end of this thread.
/Joel

**Comment by drhagen** [comment]
> There is nothing in the `solve_ivp` API documentation that says `solve_ivp` won't evaluate the given function at times later than `t_span[1]`.

While the documentation may not specifically say so, it was intended that all solvers not evaluate the function outside of `t_span` for the reason given in the original post: the function may not be defined there. This is why [`t_bound`](https://github.com/scipy/scipy/blob/8dba340293fe20e62e173bdf2c10ae208286692f/scipy/integrate/_ivp/base.py#L79-L81) is an argument to the base ODE solver class.  I consider this a bug in `select_initial_step`.

**Comment by homocomputeris** [comment]
I reported a similar bug: #8672
