### ISSUE TITLE
Proposal: faster distance calculations in 'bounded' scenarios

### ISSUE THREAD

**Issue by kodonnell** [scipy/scipy#9205]
In some scenarios, I believe we can significantly speed up distance calculations (assuming scipy behaves as I think, and doesn't e.g. already do this, or do something even smarter). They all stem from the idea of 'bounding' the distance function: e.g. if the distance between `x` and `y` is greater that `delta` we don't care about it. This effectively means we can bail out of the full calculation early (i.e. not calculate all of the dimensions of `x` and `y`), which can save *lot* of compute with higher dimensions. For example, with the euclidian distance, we already know that `x=[0,1,2,...]` and `y=[3,4,5,...]` are going to be more than `5` apart, after only the first 3 elements - so there's no need to look at all the rest (i.e. the `...`). If `x` and `y` were e.g. of a large dimension, this can be a considerable saving.

FYI: we implemented this at work for the speedup - I can't remember the exact numbers, but it was orders of magnitude if I remember correctly (though that's highly dependent on your data etc.).

Some examples where this can be useful:

### Example 1: find all points in my database of points `{y}` that are within `delta` of point `x`

This is a common-ish problem in e.g. machine learning. An example would be using embeddings for e.g. for facial recognition - I know (from how I've trained my model) that if `x` and `y` are within e.g. `0.1`, then they're the 'same'. So, when I get a new embedding `x` (e.g. a new face), and I want to 'identify' it, I compare it with all the `y` (existing faces) in my database. I don't care about the distance to all the `y` when it's `> 0.1`, and only care about those `<= 0.1` (i.e. possible face matches). 

Note that this could also apply to many pairwise distance matrices - generally there can be a reasonable limit above which you don't care (especially if the purpose of the matrix is to find points that are close).

### Example 2: find the closest point (or it's distance) in my database of points `{y}` to the point `x`

This relaxes the requirement for a bound `delta` to be specified directly, and is (I think) quite general - e.g. many clustering algorithms predict a point `x` to be the 'same' as the nearest clusters (i.e. `y`). Anyway, we can follow the pseudocode below to still get some easy performance gains by bailing out early:

```
min_distance = float('Inf')
closest = -1
for yi, y in enumerate(ys):
    distance = bounded_euclidean_distance(x, y, min_distance)
    if distance < min_distance:
        min_distance = distance
        closest = yi
return closest, min_distance
```

where `bounded_euclidean_distance` is the function described above that bails out early. The trick here is that `delta` (i.e. `min_distance`) decreases as we progress through the `ys` (assuming the not-worst-case ordering), and hence we can bail earlier and earlier. Put more concretely, if the distance between `x` and `y0` is `0.1` then this can be our bound for all further `{y_i}` (but presumably the `0.1` will decrease as we go through them - e.g. the distance between `x` and `y99` might be `0.01` in which case we can use this as our bound for the remaining `{y_i}` ... and so on).

### **Other things to note:**

- this clearly has no use in e.g. creating distance matrices, when you want every number exactly, so can't 'bail out' early.
- this only applies to calculations where the contribution of each `x_i, y_i` is guaranteed to increase the distance (and hence we can 'bail out' early if the distance has already been exceeded). This seems to hold true for many of the distance metrics which are sums of positive values.
- the performance of this depends a lot on your data. In some scenarios (e.g. where the distance between `x` and all the `y` is very similar) this may even slow things down, as you're adding a some additional work (e.g. checking `distance < min_distance`). It'd be pretty easy to test this out - I know it's worked really well for us before though.

### Questions (before I proceed with a PR)

- Am I missing something obvious? This seems too good to be true ...
- Are there already some standard performance regression tests I can compare with?
- Would this be useful to add to scipy? Does scipy have any functions which would benefit from it? I know that e.g. sckit-learn does (e.g. [here](https://github.com/scikit-learn/scikit-learn/blob/a7e17117bb15eb3f51ebccc1bd53e42fcb4e6cd8/sklearn/neighbors/nearest_centroid.py#L193-L194) where they compute the full pairwise distance matrix just to find the smallest). On that note, is this more suited as a PR for scikit-learn? (There seems to be a bit of overlap between scipy and sckit-learn in this area ...)
- I'm hoping this will largely be implemented as `def distance(x, y)` -> `def distance(x, y, upper_bound=None)` so no breaking changes etc. We can then create a separate PR to update any scipy functions that might benefit from using it internally. Does that sound reasonable?

**Comment by rgommers** [comment]
> Am I missing something obvious? This seems too good to be true ...

Nothing really obvious comes to mind.

> Are there already some standard performance regression tests I can compare with?

There are benchmarks [here](https://github.com/scipy/scipy/blob/master/benchmarks/benchmarks/spatial.py#L230). They just use random numbers though, so not very representative of the types of real-world use cases you're interested in.

>  Does scipy have any functions which would benefit from it?

The only ones that come to mind are in `cluster`, e.g. [cluster_dist](https://github.com/scipy/scipy/blob/master/scipy/cluster/_hierarchy.pyx#L81).

> Would this be useful to add to scipy?... I know that e.g. sckit-learn does (e.g. here where they compute the full pairwise distance matrix just to find the smallest). On that note, is this more suited as a PR for scikit-learn? (There seems to be a bit of overlap between scipy and sckit-learn in this area ...)

I haven't followed `scikit-learn`'s distance functionality closely, would be good to check what they still use from `scipy.spatial.distance`. I know our functionality has been performance critical in a lot of places, so if we can speed up some use cases a lot without negatively affecting other ones, then that would be quite welcome.

> We can then create a separate PR to update any scipy functions that might benefit from using it internally. Does that sound reasonable?

Yes it does. It may make sense to do some benchmarking on one or a couple of the more popular metrics first, using both the benchmarks I linked and a couple you come up with where this would really help.

**Comment by kodonnell** [comment]
Excellent - thanks for the constructive feedback. Unless others disagree, based on this my plan shall be:

1. add the above functionality in the basic functions and leave implementations (e.g. `cluster`), and any automated choosing of this method (or not), until later.
2. run the benchmarks - and possibly add my own with different data distributions to illustrate the strengths/weaknesses of this approach.
3. if positive, submit a PR, otherwise report back here with the findings.

Re `scikit-learn` - I'll post an issue there and see what their opinion is.

**Comment by kodonnell** [comment]
Closing as per discussion in scipy-dev mailing list - it seems to make more sense to implement this (among other things) in a separate package.
