### ISSUE TITLE
scipy.linalg.solve_triangular speed after scipy.linalg.lu_factor

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#9207]
This probably isn't a bug so much as a feature suggestion.

I'm aware that `lu_solve` is typically used to perform forward/backward substitution after `lu_factor`. However, I have been implementing a rank-one update to the PLU factorization, that is, efficiently updating the factorization after replacing a single column of the matrix. To solve the system after the update, I need to use `solve_triangular` to do forward and backward substitution separately because some elementary row operations are needed in-between.

I noticed that my that triangular solve with the updated U matrix, e.g.
`solve_triangular(U, y, lower=False)`
was taking at least 10x-40x times longer than triangular solve with my L matrix, e.g.
`solve_triangular(L, b, lower=True)`
Just for kicks, I tried 
`solve_triangular(U.T, y, trans=True, lower=True)`
to get the same result in a different way.
Lo and behold, this took only as long as triangular solve with L.

I've played around with this a bit and I see that it's the fact that I had to create a copy of U that made this happen. Without creating a copy of U, regular triangular solve on U is just as fast as triangular solve on L, and all the transpose stuff slows things down. 

If I'm interpreting it correctly, evidence suggests that the LU array returned by `lu_factor` is a transposed view of the underlying array. Whatever is going on under the hood, I wonder if it's possible for `solve_triangular` to detect which of the two versions (with and without the transpose) would be faster (based on properties of the view / the actual structure of the array in memory, presumably) and do the appropriate thing. That is, can:
`solve_triangular(U, y, lower=False)`
and 
`solve_triangular(U.T, y, trans=True, lower=True)`
solve in exactly the same way, depending on which (if either) would be faster?

### Reproducing code example:
```
import numpy as np
import time
from scipy.linalg import lu_factor, solve_triangular, norm

n = 5000
A = np.random.rand(n,n) # matrix doesn't matter
b = np.random.rand(n) # doesn't matter what I'm solving for

plu = lu_factor(A)
L = plu[0]
U = plu[0].copy() # I modify a copy of U to avoid modifying L

# actually modifying U doesn't affect times, so that's omitted

t0 = time.clock()
xa = solve_triangular(L, b, lower=True)
t1 = time.clock()
print("Triangular solve L: " + str(t1 - t0))

t0 = time.clock()
xa = solve_triangular(U, b, lower=False)
t1 = time.clock()
print("Triangular solve U normally: " + str(t1 - t0))

t0 = time.clock()
xb = solve_triangular(U.T, b, lower=True, trans=True)
t1 = time.clock()
print("Triangular solve U unintuitively: " + str(t1 - t0))

print("Numerical Error: " + str(norm(xb-xa)))
```

### Output:
```
Triangular solve L: 0.08268643657811481
Triangular solve U normally: 0.8241290733158166
Triangular solve U unintuitively: 0.1080854340661972
Numerical Error: 0.0
```
### Scipy/Numpy/Python version information:
```
1.1.0 1.14.0 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment]
I think when you perform a copy you convert it to a C-aligned contiguous array. If you write `U = plu[0].copy(order='F')` it should switch places in terms of timing.

**Comment by ilayn** [comment]
The resulting array is prepared to be passed to `lu_solve`. In my opinion the best way to experiment with these is to call the underlying LAPACK routines. `lu_factor` uses `linalg.lapack.dgetrf`, `lu_solve` uses `dgetrs` and triangular solver is `dtrtrs`.

**Comment by pv** [comment]
As an optimization, should `solve_triangular` transpose as necessary to get input to Fortran order?

**Comment by mdhaber** [comment]
@ilayn yup! changing the `order` of the copy made it faster without the transpose.
@pv I think that would be a welcome optimization considering that `solve_triangular` is a public function and many users (like me) are not aware of such things. 
Thanks for the answers! Glad to learn something.
