### ISSUE TITLE
SunOS fix

### ISSUE THREAD

**Issue by 0-wiz-0** [scipy/scipy#9214]
@jperkin added a patch to the pkgsrc package for scipy with the commit message:
````
Apply a couple of patches to fix SunOS.
````
I can't evaluate the patch or know details about the problem. Here's the patch:
````
--- scipy/special/_round.h.orig 2018-05-05 17:10:11.000000000 +0000
+++ scipy/special/_round.h
@@ -9,6 +9,10 @@
 #include "_c99compat.h"
 #include "cephes/dd_idefs.h"
 
+#if defined(__cplusplus)
+using std::isinf;
+using std::isnan;
+#endif
 
 double add_round_up(double a, double b)
 {
````

**Comment by pvanmulbregt** [comment]
Is there a URL for the discussion/patch?

**Comment by 0-wiz-0** [comment]
That's the original commit, yes. The `HAVE_OPEN_MEMSTREAM` part looks like it's solved already.

**Comment by rgommers** [comment]
I think that if we want to apply this patch, the correct place to tweak things is in `scipy/_lib/_c99compat.h` and not in one of the multiple files that uses `sc_isnan`. It would also be good to know why this is only needed on NetBSD.

@jperkin or @0-wiz-0 a PR would be very welcome. We can't apply this as is though, so I'll close this issue.

**Comment by rgommers** [comment]
actually this is a duplicate with gh-9214, which has more discussion.
