### ISSUE TITLE
BUG: ImportError: cannot import name 'ellipkm1' with numpy-dev

### ISSUE THREAD

**Issue by astrofrog** [scipy/scipy#9220]
I'm seeing the following error with scipy 1.1.0 when used with the latest developer version of Numpy:

```python
>>> from scipy.special import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tom/miniconda3/envs/numpy-dev/lib/python3.6/site-packages/scipy/special/__init__.py", line 642, in <module>
    from .basic import *
  File "/Users/tom/miniconda3/envs/numpy-dev/lib/python3.6/site-packages/scipy/special/basic.py", line 15, in <module>
    from ._ufuncs import (ellipkm1, mathieu_a, mathieu_b, iv, jv, gamma,
ImportError: cannot import name 'ellipkm1'
```

**Comment by rgommers** [comment]
We test against numpy master on TravisCI, so this is likely a build issue specific to your setup. Did you rebuild scipy or only built numpy locally?

**Comment by astrofrog** [comment]
I noticed this on Travis CI starting a few days ago (I also run nightly tests against numpy-dev):

https://travis-ci.org/glue-viz/glue/jobs/424286292

I also see the issue locally when creating a fresh conda environment with Python 3.6, and installing Numpy dev from the repository and scipy 1.1.0 from pip. The fact I see it on both Travis and locally suggests that this might be a real issue?

**Comment by rgommers** [comment]
Okay, that's really broken (as is our CI setup apparently). Looks like https://github.com/numpy/numpy/pull/10915 (will verify) - @mattip looks like we need at least some import shims ....

```
In [1]: np.__version__
Out[1]: '1.16.0.dev0+058851c'

In [2]: from scipy import special
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
__init__.pxd in numpy.import_ufunc()

AttributeError: _UFUNC_API not found

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-2-5ad56e6855d2> in <module>()
----> 1 from scipy import special

~/Code/scipy/scipy/special/__init__.py in <module>()
    639 from .sf_error import SpecialFunctionWarning, SpecialFunctionError
    640 
--> 641 from ._ufuncs import *
    642 
    643 from .basic import *

_ufuncs.pyx in init scipy.special._ufuncs()

_ufuncs_extra_code_common.pxi in init scipy.special._ufuncs_cxx()

__init__.pxd in numpy.import_ufunc()

ImportError: numpy.core.umath failed to import
```

**Comment by rgommers** [comment]
> as is our CI setup apparently

oh no, that must be because we're rebuilding scipy itself, we're not testing previous releases.

**Comment by rgommers** [comment]
Yep, rebuilding scipy against numpy master fixes it.

**Comment by rgommers** [comment]
I had a look at how we generate `cython_special`; we don't seem to do anything strange there that relies on private implementation details. It fails on `np.import_ufunc`, which does seem to have an issue (does `_import_umath`): https://github.com/cython/cython/blob/master/Cython/Includes/numpy/__init__.pxd#L1046.

**Comment by rgommers** [comment]
Looks like either a numpy ABI break or Cython relying on private parts of numpy. In the latter case, the discussion on moving the numpy support for Cython into numpy itself seems timely. That's it from me for now. 

@mattip probably best to create a new numpy issue for this?

**Comment by charris** [comment]
I'm not seeing this locally with SciPy `runtests.py`, there is a precision error with `def test_hilbert(self)`, but that is it. This was after deleting all my local installs of numpy and reinstalling latest master. Cython version was 0.28.5 and both Python 2.7 and 3.6. There have been reported problems with outdated cached data, so that might play a role.

**Comment by charris** [comment]
Are you running from NumPy wheels?

**Comment by astrofrog** [comment]
@charris - in my case I'm just installing Numpy directly from the git repository, then installing the SciPy wheel

**Comment by charris** [comment]
Hmm, so the SciPy wheel was probably built against an earlier version of NumPy...

**Comment by charris** [comment]
So just to be sure, the problem comes from scipy built against numpy versions prior to the code rearrangements?

**Comment by charris** [comment]
So the relevant change in `_import_math` is
```
-  PyObject *numpy = PyImport_ImportModule("numpy.core.umath");
+  PyObject *numpy = PyImport_ImportModule("numpy.core._multiarray_umath");
```

**Comment by charris** [comment]
Looks like reverting that change would fix the problem, but the question becomes how to make that change in the future.

**Comment by charris** [comment]
So probably a `try... except` fallback is the way to go until scipy drops support for numpy < 1.16.

**Comment by charris** [comment]
Also fix `_import_array`.

**Comment by rgommers** [comment]
> OK, fix works. I have a question about back compatibility, should scipy compiled against NumPy 1.6 work when run with earlier NumPy versions? 

What SciPy version would that be? IIRC we've been compiling against 1.7 for Python 2.7 and 1.9 for Python 3.x for a long time. So I'd say it's at least 5 SciPy versions ago, at which point it's a "don't care much".

But just to double check: how likely is it that other packages rely on this same import?

**Comment by charris** [comment]
@rgommers Oops, I meant 1.16. The NumPy API cversion hasn't changed since 1.14, but with 1.16 the private API used by Cython has changed. I could make it back compatible if desired.

**Comment by rgommers** [comment]
> OK, fix works. I have a question about back compatibility, should scipy compiled against NumPy 1.6 work when run with earlier NumPy versions?
> @rgommers Oops, I meant 1.16. The NumPy API cversion hasn't changed since 1.14, but with 1.16 the private API used by Cython has changed. I could make it back compatible if desired.

That would be forward rather than backward compatibility (Ithink, depending on how you'd define it given that the API number didn't change). 1.16 isn't out yet, so I'd suggest bumping the API number anyway - no harm in that.

**Comment by rgommers** [comment]
fixed now, thanks all!
