### ISSUE TITLE
infinite loop in stats.fisher_exact

### ISSUE THREAD

**Issue by burcakotlu** [scipy/scipy#9231]
I'm using scipy version 1.0.0.

```
import scipy as sp
import scipy.stats
x = [[5829225, 5692693], [5760959, 5760959]]
sp.stats.fisher_exact(x)

```
For the values above scipy does not return anything but waits. What can be the reason for that? How can I fix it?

However in R it returns a p-value almost immediately.

```
a = matrix(c(5829225,5692693,5760959,5760959), nrow=2)
fisher.test(a)
```

Thanks in advance, 
Burcak

**Comment by ilayn** [comment]
Looks like a bug. It gets stuck at the `while` loop here

https://github.com/scipy/scipy/blob/10233db/scipy/stats/stats.py#L3170-L3171

The values compared are 
```
0.0 7.182425487416777e-180
0.0 7.182425487416777e-180
0.0 7.182425487416777e-180
0.0 7.182425487416777e-180
0.0 7.182425487416777e-180
0.0 7.182425487416777e-180
0.0 7.182425487416777e-180
```

**Comment by akahard2dj** [comment]
In this case, how about setting the max_iteration value ?
For example, if the loop is stopped at the `guess` value of 1000, the results is the same as that of R.

scipy results
```
(1.0239837279122552, 3.0631061987484285e-178)
```

R results
```
        Fisher's Exact Test for Count Data

data:  a
p-value < 2.2e-16
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 1.022285 1.025680
sample estimates:
odds ratio 
  1.023992 
```

**Comment by josef-pkt** [comment]
AFAIU:
`guess` is limited by `n`, i.e. the last argument is the number of draws and for we cannot draw more of type I than this.
So, the loop should `break` at  `guess >= n` or add to `while guess < n`
The subtraction path includes the boundary condition `guess > 0`

I'm not sure what should happen at guess == n. AFAICS the final guess needs to be also `n`

**Comment by akahard2dj** [comment]
@josef-pkt yes, `guess` is limited and controlled by `n`. the problem is `n` is so huge.
In this issue, `n` is `11590184`. this number is too big to iterate a loop.

The loop stopped at `guess=5760958`. the running time was roughly 30 minute in my laptop.
the result is `1.02389837279122552`.

In this case, the iteration number seem to be wasted. 
I think we need a separate condition to exit the loop.

**Comment by ilayn** [comment]
If a bisection algorithm is meant by binary search, there is a much faster way of doing this.

**Comment by akahard2dj** [comment]
I present a new method. @ilayn, @josef-pkt please review this idea.
`n` value is proportional to the input number, 
in that case `x = [[5829225, 5692693], [5760959, 5760959]]`.
So I applied an adaptive iter_unit.
```python
while hypergeom.pmf(guess, n1 + n2, n1, n) < pexact * epsilon:
    max_order_digit = np.int(np.log10(np.max([n1, n1+n2, n])))
    if max_order_digit <= 3:
        iter_unit = 1
    else:
        iter_unit = np.power(10, max_order_digit-3)
    guess += iter_unit
```
the result is `(1.0239837279122552, 6.126212397496855e-178)`
and running time is 4 sec(current version 30 minutes).

Of course, a more sophisticated process is needed to determine the value of `iter_unit`.
However, applying a variable `iter_unit` can have a tremendous benefit in computation time.

**Comment by ilayn** [comment]
Those tricks usually play well if there is a logarithmic relationship on the size estimation. I don't think it is the case here. 

I am not familiar with `hypergeom.pmf` but if it is a monotone function and bounded by `n` then the obvious choice is implementing smaller binary search inside those branches. Then we can combine `lower` and `upper` and simplify things.

**Comment by akahard2dj** [comment]
Okay. @ilayn 
I also am not familiar with `hypergeom.pmf`. As far as i know, this function is monotonous.
I will think and design using your suggestion of combining `lower` and `upper` .

**Comment by akahard2dj** [comment]
How about this process @ilayn ?
previously, regardless of the range of the interval, `guess` is alway increased by 1.
In the new process, i changed the `guess` increase amount not to 1 but to the 
intermediate value of `upper` and `lower`.

I confirmed that applying the new method converges to the results with 21 iteration(in that case).

the previous 30-minute calculation was reduced to about 3 sec.
this is 600x speed up.

```python
while hypergeom.pmf(guess, n1 + n2, n1, n) < pexact * epsilon:
    iter_unit = (np.min([n1, n, n1+n2])//2 + guess) // 2
    guess = iter_unit + 1
```

```bash
iter_index n n1 n2 iter_unit guess hypergeom.pmf pexact
0 11590184 11521918 11521918 2880480 1 0.0 7.183143801796957e-180
1 11590184 11521918 11521918 4320720 2880481 0.0 7.183143801796957e-180
2 11590184 11521918 11521918 5040840 4320721 0.0 7.183143801796957e-180
3 11590184 11521918 11521918 5400900 5040841 0.0 7.183143801796957e-180
4 11590184 11521918 11521918 5580930 5400901 0.0 7.183143801796957e-180
5 11590184 11521918 11521918 5670945 5580931 0.0 7.183143801796957e-180
6 11590184 11521918 11521918 5715952 5670946 0.0 7.183143801796957e-180
7 11590184 11521918 11521918 5738456 5715953 0.0 7.183143801796957e-180
8 11590184 11521918 11521918 5749708 5738457 0.0 7.183143801796957e-180
9 11590184 11521918 11521918 5755334 5749709 9.460732495e-315 7.183143801796957e-180
10 11590184 11521918 11521918 5758147 5755335 1.581289453283023e-242 7.183143801796957e-180
11 11590184 11521918 11521918 5759553 5758148 5.383907224495671e-210 7.183143801796957e-180
12 11590184 11521918 11521918 5760256 5759554 1.2500431856035085e-194 7.183143801796957e-180
13 11590184 11521918 11521918 5760608 5760257 3.5998486997551737e-187 7.183143801796957e-180
14 11590184 11521918 11521918 5760784 5760609 1.7189952961060262e-183 7.183143801796957e-180
15 11590184 11521918 11521918 5760872 5760785 1.1501593175993004e-181 7.183143801796957e-180
16 11590184 11521918 11521918 5760916 5760873 9.332472063069392e-181 7.183143801796957e-180
17 11590184 11521918 11521918 5760938 5760917 2.6530186231704e-180 7.183143801796957e-180
18 11590184 11521918 11521918 5760949 5760939 4.470881558334984e-180 7.183143801796957e-180
19 11590184 11521918 11521918 5760954 5760950 5.803164239342002e-180 7.183143801796957e-180
20 11590184 11521918 11521918 5760957 5760955 6.533410382778032e-180 7.183143801796957e-180
21 11590184 11521918 11521918 5760958 5760958 7.0148979096678186e-180 7.183143801796957e-180
(1.0239837279122552, 6.126212397496855e-178)

real    0m3.077s
user    0m2.296s
sys     0m0.796s

```

**Comment by akahard2dj** [comment]
I opened #9291 PR.

**Comment by ilayn** [comment]
@akahard2dj Thanks. If you add "Fixes" or "Closes" clause, they are linked automatically.

**Comment by IandJMSmith** [comment]
The real problem is that the initial guess is so bad. It is quite easy to make a very accurate guess.
However far c[0,0] is from the expected value (rowsum* colsum/total), the initial guess for the other bound should be as far away the other side of the expected value. You won't be out by much at all.
