### ISSUE TITLE
Likely bug in sputils.get_sum_dtype

### ISSUE THREAD

**Issue by eric-wieser** [scipy/scipy#9240]
This code looks wrong to me:

https://github.com/scipy/scipy/blob/9a94b31da02764111cb51a5e825e1048e0760db6/scipy/sparse/sputils.py#L173-L181

`issubdtype(t, np.float_)` is the same as `t == np.float_`, in which case the if statement is pointless - I think the intent _might_ have been `issubdtype(t, np.floating)`

**Comment by Gotham13121997** [comment]
Removing the first check is causing one test to fail on travis as no output is returned. Maybe the check was there for some other reason.

**Comment by eric-wieser** [comment]
That failure from travis is a problem with travis, not a problem with your patch

**Comment by perimosocordiae** [comment]
Fixed by gh-9280.
