### ISSUE TITLE
Wrong return type in nunmpy.argmax documentation

### ISSUE THREAD

**Issue by ClementWalter** [scipy/scipy#9244]
Not a real bug but the [documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html#numpy.argmax) is wrong in the return type. It states:
> index_array : ndarray of ints
Array of indices into the array. It has the same shape as a.shape with the dimension along axis removed

However, as stated in the example, `argmax` over the whole array it returns an int:
```
a = np.arange(6).reshape(2,3)
np.argmax(a)
# 5
```

It makes static inspection of the code crash. It should be something like:
> index_array : ndarray of ints or single int
Array of indices into the array. It has the same shape as a.shape with the dimension along axis removed. Argmax taken over an array without specifying axis returns a single int.

**Comment by ilayn** [comment]
Superpedantically, if remove the dimension along the axis for 1D arrays you are left with a scalar but I agree it is a bit confusing. 

I think a better fix is to mention this corner case instead

```markdown
    index_array : ndarray, int
        Array of indices into the array. It has the same shape as ``a.shape``
        with the dimension along ``axis`` removed and thus, for 1D arrays,
        an integer is returned.
```

**Comment by ilayn** [comment]
Closing this since it has to be fixed on the NumPy side.
