### ISSUE TITLE
running scipy.interpolate.tests.test_fitpack::test_bisplev_integer_overflow on 32 bit with debug python segfaults

### ISSUE THREAD

**Issue by mwhudson** [scipy/scipy#9245]
This is a bit obscure, but it (amongst other things) is currently blocking scipy 1.1 from being part of the next release of Ubuntu.

### Reproducing code example:

On Ubuntu Cosmic, at least:

```
python3-dbg runtests.py -v -t scipy.interpolate.tests.test_fitpack::test_bisplev_integer_overflow
```

### Error message:
```
scipy/interpolate/tests/test_fitpack.py::test_bisplev_integer_overflow Segmentation fault (core dumped)
```

### Scipy/Numpy/Python version information:
```
1.2.0.dev0+641bc92 1.14.5 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

As all the other problems I'm having are on architectures other than amd64/x86_64, I feel I should ask: what is the status of scipy support on other architectures? If I file bugs is there anyone who can/will help me with debugging them?

**Comment by rgommers** [comment]
> As all the other problems I'm having are on architectures other than amd64/x86_64, I feel I should ask: what is the status of scipy support on other architectures? If I file bugs is there anyone who can/will help me with debugging them?

We aim to support all of them, however it's less "official". Meaning that we don't have CI for anything but 32/64-bit (i686/amd64) on Windows/Linux/macOS, and therefore support is on a best-effort basis as issues are reported. Due to the lack of CI, regressions and build issues tend to show up at the time when Ubuntu or another distro wants to incorporate a new SciPy version. 

We'll do our best to help debug. We don't have access to hardware though, so usually it's a lot easier for a Ubuntu/Debian dev to send patches for us to review/incorporate.

**Comment by rgommers** [comment]
We don't have a `python-dbg` TravisCI build matrix entry, looks like we should add one. NumPy does have one that works, we can steal that.

**Comment by mwhudson** [comment]
> We aim to support all of them, however it's less "official". Meaning that we don't have CI for anything but 32/64-bit (i686/amd64) on Windows/Linux/macOS, and therefore support is on a best-effort basis as issues are reported. Due to the lack of CI, regressions and build issues tend to show up at the time when Ubuntu or another distro wants to incorporate a new SciPy version.

That all makes sense.

That said I've been seeing failures on 32-bit intel too... the full log is here: https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-cosmic/cosmic/i386/p/python-scipy/20180828_024711_548a2@/log.gz but it's fairly incomprehensible, I should try to reproduce the failures individually with current git and report a bug for each one I guess.

Do you actually run 32 bit Python in CI anywhere? I had a poke but couldn't find a run. (I also think given scipy's scope, dropping 32 bit support would be totally justifiable).

> We'll do our best to help debug. We don't have access to hardware though, so usually it's a lot easier for a Ubuntu/Debian dev to send patches for us to review/incorporate.

Well it might have to be a bit more iterative than that, i.e. I paste a failure, someone tells me where to poke and then I have a look and come back with a patch? :)

**Comment by rgommers** [comment]
>  I should try to reproduce the failures individually with current git and report a bug for each one I guess.

yes, thanks for the ones you already sent

**Comment by rgommers** [comment]
> Do you actually run 32 bit Python in CI anywhere? I had a poke but couldn't find a run. (I also think given scipy's scope, dropping 32 bit support would be totally justifiable).

No we don't, forgot about that - we really should. Will open a new issue for that. Numpy has a 32-bit TravisCI build config that we can steal.

**Comment by RizzerOnGitHub** [comment]
I've reactivated build-time testing on Debian builds.  It's not CI testing, but binary rebuilds do happen from time to time. It catches the bisplev segfaults on all 32 bit arches (test failures at build time are currently ignored so the builds continue to completion, which is probably a build configuration bug but convenient for this scipy issue).  https://buildd.debian.org/status/package.php?p=python-scipy

The problem will also show up in Debian build reproducibility tests once 1.2.2-4 starts building on the 32 bit arches there. So this can be considered as CI.
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/i386/python-scipy.html
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/armhf/python-scipy.html
