### ISSUE TITLE
add 32-bit build on TravisCI

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#9251]
It's missing, see https://github.com/scipy/scipy/issues/9245#issuecomment-420077358 for a report of an issue (there were more).

NumPy's 32-bit build config: https://github.com/numpy/numpy/blob/master/tools/travis-test.sh#L216

**Comment by rgommers** [comment]
Note that in practice this was never a problem before, because my dev setup was 32-bit. I've recently switched however, and apparently quite a few test failures crept in already.

**Comment by rgommers** [comment]
gh-9245 also reports a failure with a debug build - maybe we should add a 64-bit debug build as well. preferably by replacing another build matrix entry, not adding more.

**Comment by pv** [comment]
There's 32-bit CI that runs regularly here: https://travis-ci.org/MacPython/scipy-wheels

**Comment by rgommers** [comment]
Good point. We seem to be pretty good at ignoring failures there though, having our CI on PRs turn red is more of an incentive to fix things....

**Comment by matthew-brett** [comment]
I do my best to report failure on the issue tracker, but it's true, they often don't get fixed quickly.

**Comment by rgommers** [comment]
@matthew-brett yes that's much appreciated. the problem is that they go on a 1000+ high pile of open issues. CI on PRs turning red is simply more urgent to fix.

**Comment by Kai-Striega** [comment]
I've found a similar bug (#10388) and I'd be happy to add a debug build. If applicable I can add/modify a 32-bit build too. (i.e. add a single new build and modify one)

Quickly looking over .travis.yml the simplest change would be to combine the two existing python3.6 builds. One checks the optimized build (``-OO``) and the other runs the benchmarks (``asv``). As an aside wouldn't it make sense to benchmark the optimized build?

@pv @rgommers

**Comment by rgommers** [comment]
Thanks @Kai-Striega. 
If the benchmarks run fast enough to be tacked onto that `-OO` test run, then that sounds like a good idea to me. Benchmarking results here shouldn't really be affected by `-OO`, and anyway we don't use those benchmarking results, it's just a check we didn't break anything.

+1 for a 32-bit build on Azure Pipelines. NumPy has one, config can probably be copied.

**Comment by tylerjereddy** [comment]
> +1 for a 32-bit build on Azure Pipelines. 

We have one, I added it after adding the one for NumPy. Perhaps you mean for debug builds of some sort or a platform other than Linux.

**Comment by Kai-Striega** [comment]
@tylerjereddy I think @rgommers meant a 32-bit Travis build. 

> Perhaps you mean for debug builds of some sort or a platform other than Linux.

I'm more concerned about us (not) having a debug build. It's common to both #9245 and #10388 and, as far as I can tell, isn't tested anywhere in our CI. 

NumPy builds their debug build with both python-dbg and cython-dbg, should we copy their method and use debug versions of all requirements (numpy, cython, pybind).

> If the benchmarks run fast enough to be tacked onto that -OO test run,

Looking at the most recent build ([18274.4](https://travis-ci.org/scipy/scipy/builds/558370144)) the benchmarks took 2.29 seconds so it shouldn't be a problem anyway.

**Comment by Kai-Striega** [comment]
@rgommers I've been working on this, but, it looks like travis-ci doesn't support a 32bit build ([gh-5770](https://github.com/travis-ci/travis-ci/issues/5770) and has no plans to do so. They mention the best way forward is to use a 32-bit docker image. I'm not sure if we have an image setup somewhere, or if it's worth the time/maintenance to set one up, especially as we already have the tests on Azure.

**Comment by pv** [comment]
If there's already a 32-bit build on some CI, then I don't see a reason to add one on Travis specifically.
The initial issue talks about TravisCI probably because for a long time it was the only CI available.

**Comment by pv** [comment]
Also, the benchmarks are not run on Travis, only checked for validity (i.e. asv check instead of asv run).

**Comment by rgommers** [comment]
as pointed out, we have 32-bit CI on Azure now, so this issue is solved.
