### ISSUE TITLE
Using fftconvolve in scipy.ndimage.binary_<operation> ?

### ISSUE THREAD

**Issue by jgostick** [scipy/scipy#9258]
It's possible to do binary_opening/closing/erosion/dilaton (and possibly more) using `scipy.signal.fftconvolve`.  I find this to be about 10x faster than the implementations in `ndimage`.  I'm wondering why this isn't used already since it seems pretty easy to change?  I suspect there is some higher reason that I'm not aware, but I thought I'd check just in case.  

I should mention that my 10x speedup is achieved using the anaconda distribution which I believe has special high-performance versions of ffts (something to do with being compiled against MKL, etc).  

Also, I'm interested in doing 3D images (tomography), which actually cause memory errors with the normal `sp.ndimage.binary_<operation>` functions.  The 10x speed-up I show below is for a 2D image, and I can't even compare to 3D.

### Reproducing code example:
The following reproduces `sp.ndimage.binary_opening`:
```
import scipy as sp
import scipy.ndimage as spim
from skimage.morphology import disk, ball

strel = disk(25)
# Generate small image to test on
im = sp.rand(500, 500) < 0.95


def binary_opening_fft(input, structure):
    f = 0.1  # Some small number of help threshold the numerical noise of fft
    # The array must be padded with 0's so it works correctly at edges
    temp = sp.pad(array=im, pad_width=1, mode='constant', constant_values=0)
    # Perform erosion
    seeds = sp.signal.fftconvolve(temp, strel, mode='same') > (strel.sum() - f)
    # Perform dilation
    fft_result = sp.signal.fftconvolve(seeds, strel, mode='same') > f
    # Remove padding from resulting image
    if im.ndim == 2:
        fft_result = fft_result[1:-1, 1:-1]
    elif im.ndim == 3:
        fft_result = fft_result[1:-1, 1:-1, 1:-1]
    return fft_result


# Use the new function
fft_result = binary_opening_fft(input=im, structure=strel)

# Now repeat with sp.ndimage.binary_opening
sp_result = spim.binary_opening(input=im, structure=strel)

# Finally, check for any differences between images
assert sp.any(fft_result ^ sp_result) == False

```

Using %timeit, the fft_binary_opening takes 51. ms, while the sp.ndimage version takes 720 ms...more than 10x.  The amount of speed depends a lot on the size of strel.  When the disk is only 5 pixels the speed up is only 2x, but still worthwhile.

### Scipy/Numpy/Python version information:
```
1.1.0 1.14.3 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```

**Comment by ev-br** [comment]
From 10000 feet, I suspect it's easier to cook up your small(-ish) library with an ndimage/scikit-image compatible API and distribute it on PyPI.

**Comment by jgostick** [comment]
Indeed, I'm already [doing that](https://github.com/PMEAL/porespy) :-)  I was just wondering if moving to a 10x faster version was appealing, or if there was some higher reason why it wasn't done the fast way.  I will certainly add `binary_<operation>_fft` to my package, but if you're interested, I would love the chance to contribute to scipy!

**Comment by rgommers** [comment]
Well, if it's a consistent speedup also without `mkl-fft` and the accuracy is fine, then we can replace the implementation of the existing function(s) I'd say. The memory use sounds interesting too. Would be good to benchmark with `scipy.fftpack`.
