### ISSUE TITLE
ndimage rank_filters (median_filter) don't work with a sequence of modes

### ISSUE THREAD

**Issue by lorenzo-rossini** [scipy/scipy#9266]
rank_filters like median_filter or percentile filter raise a RunTimeError if a sequence of modes with the same length of the dimensions of the input array is passed.
Documentation does not report this limitation for any of these filters:

> mode : str or sequence, optional
> The mode parameter determines how the input array is extended when the filter overlaps a border. By passing a sequence of modes with length equal to the number of dimensions of the input array, different modes can be specified along each axis. Default value is ‘reflect’.

### Reproducing code example:
```
import numpy as np
from scipy.ndimage import median_filter

a = np.ones((10, 10, 10))
b = median_filter(a, size=(5, 3, 3), mode=('nearest','nearest','wrap'))
```

### Error message:
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    b = median_filter(a, size=(5, 3, 3), mode=('nearest','nearest','wrap'))
  File "/home/lorenzo/dev/test/env/lib/python3.6/site-packages/scipy/ndimage/filters.py", line 1224, in median_filter
    origin, 'median')
  File "/home/lorenzo/dev/test/env/lib/python3.6/site-packages/scipy/ndimage/filters.py", line 1143, in _rank_filter
    mode = _ni_support._extend_mode_to_code(mode)
  File "/home/lorenzo/dev/test/env/lib/python3.6/site-packages/scipy/ndimage/_ni_support.py", line 52, in _extend_mode_to_code
    raise RuntimeError('boundary mode not supported')
RuntimeError: boundary mode not supported
```

### Scipy/Numpy/Python version information:
```
1.1.0 1.15.1 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

**Comment by grlee77** [comment]
closed by #11284 (docstring was fixed: median_filter is non-separable and does not support a series of modes)
