### ISSUE TITLE
new feature: adding LOBPCG solver in svds in addition to ARPACK

### ISSUE THREAD

**Issue by lobpcg** [scipy/scipy#9275]
### Reproducing code example:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.svds.html is a 

> naive implementation using ARPACK as an eigensolver on A.H * A or A * A.H, depending on which one is more efficient.

It is simple and beneficial to add an alternative to ARPACK solver https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.lobpcg.html again just on A.H * A or A * A.H, depending on which one is more efficient. It is demonstrated in MATLAB that LOBPCG may outperform ARPACK for such a use, see comments at https://www.mathworks.com/matlabcentral/fileexchange/48-lobpcg-m

### Error message:
N/A

### Scipy/Numpy/Python version information:
N/A

**Comment by lobpcg** [comment]
@rc @pvanmulbregt 
This is now done in scikit-learn and can probably be just mostly copy/pasted from https://github.com/lobpcg/scikit-learn/blob/lobpcg_svd/sklearn/utils/extmath.py to scipy... 
It works well for dense truncated_svd too.

**Comment by ilayn** [comment]
@lobpcg You can also open a PR which might be a bit more focused.

**Comment by rc** [comment]
@lobpcg Let's see how the scikit-learn version review goes. I will not be of much use during the weekend anyway...

**Comment by lobpcg** [comment]
@rc would you like to take the lead on this one as PR https://github.com/scipy/scipy/pull/9650 is near completion?

**Comment by rc** [comment]
@lobpcg I will be mostly offline till the end of the week, but afterwards it could be possible. To refresh my memory, it will be mostly copying code from the sklearn version, right?

**Comment by lobpcg** [comment]
PR #9650 is now merged to the master

**Comment by rgommers** [comment]
Thanks @lobpcg, all. Closing.

**Comment by lobpcg** [comment]
@rgommers you closed the wrong PR! Please reopen this one and close PR #9650

**Comment by lobpcg** [comment]
@rgommers as well as the  [1.3.0](/scipy/scipy/milestone/37) milestone...

**Comment by rgommers** [comment]
Don't think so - this is an issue, not a PR. PR gh-9650 is merged (which is its final status, it doesn't need closing) and will be present in the next release. This issue is about the same thing right, and gh-9650 implements what is suggested in this issue? Hence this one can be closed (or is there anything left to do?).

**Comment by lobpcg** [comment]
Sorry for the confusion. PR [gh-9650](https://github.com/scipy/scipy/pull/9650) does not address any open issues - it is just a bug-fix release of lobpcg for eigenvalue problems. There was no issue to close with it now added to the master - I was incorrect in this respect.

The present issue is to add lobpcg as a new SVD solver. It depends on   PR [gh-9650](https://github.com/scipy/scipy/pull/9650) but the work is not yet even started. Could you please reopen it and remove it from the [1.3.0](/scipy/scipy/milestone/37) milestone, to play it safe?

**Comment by rgommers** [comment]
Ah okay, got it - thanks @lobpcg, reopening:)

**Comment by lobpcg** [comment]
Here is how this was done in https://github.com/scikit-learn/scikit-learn/pull/12319/ :
```
def lobpcg_svd(M, n_components, n_oversamples=10, n_iter='auto',
               transpose='auto', flip_sign=True, random_state=0,
               tol=None, explicitNormalMatrix=None):
    """Computes a truncated SVD using LOBPCG to accelerate the randomized SVD.
    Compared to 'randomised', the 'lobpcg' option gives more accurate
    approximations, with the same n_iter, n_components, and n_oversamples,
    at the slightly increased costs, allows setting the tolerance, and can
    output the accuracy. tol = None or tol = .0 in 'lobpcg' is ignored and
    substituted by a local default in LOBPCG.
    Parameters
    ----------
    M : ndarray or sparse matrix
        Matrix to decompose, real or complex.
    n_components : int
        Number of singular values and vectors to extract.
    n_oversamples : int (default is 10)
        Additional number of random vectors to sample the range of M so as
        to ensure proper conditioning. The total number of random vectors
        used to find the range of M is n_components + n_oversamples. Smaller
        number can improve speed but can negatively impact the quality of
        approximation of singular vectors and singular values.
    n_iter : int or 'auto' (default is 'auto')
        Number of lobpcg iterations. It can be used to deal with very noisy
        problems. When 'auto', it is set to 4, unless `n_components` is small
        (< .1 * min(X.shape)) `n_iter` in which case is set to 7.
        This improves precision with few components.
    transpose : True, False or 'auto' (default)
        Whether the algorithm should be applied to M.T instead of M. The
        result should approximately be the same. The 'auto' mode will
        trigger the transposition if M.shape[0] > M.shape[1] since this
        leads to the normal matrix of the smaller size and thus runs faster.
    flip_sign : boolean, (True by default)
        The output of a singular value decomposition is only unique up to a
        permutation of the signs of the singular vectors. If `flip_sign` is
        set to `True`, the sign ambiguity is resolved by making the largest
        loadings for each component in the left singular vectors positive.
    random_state : int, RandomState instance or None, optional (default=None)
        The seed of the pseudo random number generator to use when shuffling
        the data.  If int, random_state is the seed used by the random number
        generator; If RandomState instance, random_state is the random number
        generator; If None, the random number generator is the RandomState
        instance used by `np.random`.
    tol : scalar, (default=None)
        Optional solver tolerance (stopping criterion), if large enough, may
        overwrite n_iter. If None, lobpcg sets is internally.
    explicitNormalMatrix : boolean, (default=None)
        Optional parameter that determines if the normal matrix used by lobpcg
        is computed explicitly or implicitly via LinearOperator performing
        multiplication of the normal matrix and a vector. The latter may be
        faster for data matrices M of large sizes or sparse.
    Notes
    -----
    LOBPCG solver may become numerically unstable if the requested tolerance
    is unreasonably small and the maximal number of iterations is large.
    References
    ----------
    Toward the Optimal Preconditioned Eigensolver: Locally Optimal Block
    Preconditioned Conjugate Gradient Method, Andrew V. Knyazev (2001)
    https://doi.org/10.1137%2FS1064827500366124
    """
    if isinstance(M, (sparse.lil_matrix, sparse.dok_matrix)):
        warnings.warn("Calculating SVD of a {} is expensive. "
                      "csr_matrix is more efficient.".format(
                          type(M).__name__),
                      sparse.SparseEfficiencyWarning)

    random_state = check_random_state(random_state)
    n_random = n_components + n_oversamples
    n_samples, n_features = M.shape

    if n_iter == 'auto':
        # Checks if the number of iterations is explicitly specified
        # Adjust n_iter. 7 was found a good compromise for PCA. See #5299
        n_iter = 7 if n_components < .1 * min(M.shape) else 4

    if transpose == 'auto':
        # Make the normal matrix A with the smallest size
        transpose = n_samples > n_features
    if transpose:
        M = M.T.conj()

    Q = random_state.normal(size=(M.shape[0], n_random))
    if M.dtype.kind == 'f':
        # Ensure f32 is preserved as f32
        Q = Q.astype(M.dtype, copy=False)

    # The values are chosen experimentally
    if explicitNormalMatrix is None:
        if sparse.issparse(M):
            explicitNormalMatrix = False
        elif min(M.shape) > 4000 or min(M.shape)/max(M.shape) > 0.5:
            explicitNormalMatrix = False
        else:
            # Rectangular and small-size data matrix M
            explicitNormalMatrix = True

    # Determine the normal matrix
    if explicitNormalMatrix:
        A = safe_sparse_dot(M, M.T.conj())
    else:
        MLO = aslinearoperator(M)

        if hasattr(MLO, 'H'):

            def _matvec(V):
                return MLO(MLO.H(V))

        else:  # Old SciPy versions.
            MTLO = aslinearoperator(M.T.conj())

            def _matvec(V):
                return MLO(MTLO(V))

        Ms0 = M.shape[0]
        A = LinearOperator(dtype=M.dtype, shape=(Ms0, Ms0),
                           matvec=_matvec, matmat=_matvec)

    # For lobpcg debugging, use verbosityLevel = 1
    lobpcgVerbosityLevel = 0
    # lobpcg computes largest, be default, eigenvalues of the normal matrix
    # A, given implicitly via LinearOperator or explicitly as dense or sparse
    _, Q = lobpcg(A, Q, maxiter=n_iter,
                  verbosityLevel=lobpcgVerbosityLevel, tol=tol)
    del A

    # Project M to the (k + p) dimensional space using the basis vectors
    B = safe_sparse_dot(Q.T.conj(), M)

    # Compute the SVD on the thin matrix: (k + p) wide
    Uhat, s, V = linalg.svd(B, full_matrices=False)

    del B
    U = np.dot(Q, Uhat)

    if flip_sign:
        if not transpose:
            U, V = svd_flip(U, V)
        else:
            # In case of transpose u_based_decision=false
            # to actually flip based on u and not v.
            U, V = svd_flip(U, V, u_based_decision=False)

    if transpose:
        # Transpose back the results according to the input convention
        return (V[:n_components, :].T.conj(), s[:n_components],
                U[:, :n_components].T.conj())
    else:
        return U[:, :n_components], s[:n_components], V[:n_components, :]
```

**Comment by clementkng** [comment]
> I do not have a setup for contributing to SciPy

Hi @lobpcg, if the above is still the case, I'm interested in trying to add in the new feature! I do have a local scipy setup and am definitely interested in trying this out.

**Comment by lobpcg** [comment]
> 
> 
> > I do not have a setup for contributing to SciPy
> 
> Hi @lobpcg, if the above is still the case, I'm interested in trying to add in the new feature! I do have a local scipy setup and am definitely interested in trying this out.

@clementkng Of course, please feel free. It is actually involved, not just copy/paste.

**Comment by clementkng** [comment]
@lobpcg Has something changed since when you commented it was mainly copy/paste code and tests? What else do we need to consider?

**Comment by clementkng** [comment]
@lobpcg Has something changed since when you commented it was mainly copy/paste code and tests? What else do we need to consider?

**Comment by lobpcg** [comment]
Nothing has changed: copy/paste, tests, and edit to make everything (input/output, tolerance, tests) is compatible with other SVD solvers. There may be many tests for SVD solvers there - I have not checked how many. And update the documentation to reflect the changes.

**Comment by clementkng** [comment]
@lobpcg Is the current Scipy [LOBPCG solver](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.lobpcg.html) reliable to use? I'm confused since you mention I have to copy/paste from the scikit-learn implementation, but if the solver already exists in Scipy, then we would use that, right?

**Comment by lobpcg** [comment]
Copy/paste the SVD interface https://github.com/scipy/scipy/issues/9275#issuecomment-504673772 , to the current Scipy LOBPCG eigenvalue solver.

**Comment by clementkng** [comment]
@lobpcg I've currently pasted the implementation as well as the [test](https://github.com/scikit-learn/scikit-learn/blob/6ef8dadd4cb19c4fd39ae4e98904846528a9a28e/sklearn/utils/tests/test_extmath.py#L88) in scikit-learn that are relevant to the solver. I'm getting a couple of mismatch errors that I'm currently trying to fix, but looking through the version there and the interface you provided, I noticed that all the matrix transposes in the scikit-learn PR additionally have calls to `.conj()` attached to them in this version. Is there a reason for this distinction?

**Comment by lobpcg** [comment]
> 
> 
> @lobpcg I've currently pasted the implementation as well as the [test](https://github.com/scikit-learn/scikit-learn/blob/6ef8dadd4cb19c4fd39ae4e98904846528a9a28e/sklearn/utils/tests/test_extmath.py#L88) in scikit-learn that are relevant to the solver. I'm getting a couple of mismatch errors that I'm currently trying to fix, but looking through the version there and the interface you provided, I noticed that all the matrix transposes in the scikit-learn PR additionally have calls to `.conj()` attached to them in this version. Is there a reason for this distinction?

 `.conj()` is a must to have in this code in scipy to handle complex-valued input, which is necessary in scipy; and should come with a unit test where the input matrix is complex-valued. However, scikit-learn simply does not support complex numbers. For real-valued numbers,  `.conj()` has no effect and does not hurt, but scikit-learn maintainers still have removed it recently for better style and consistency with scikit-learn.

**Comment by clementkng** [comment]
@lobpcg To make everything work w/ existing SVD solvers, we need to make sure the interface to both functions is the same. To do that, we would need to pick defaults for arguments specific to LOBPCG i.e. `n_oversamples`, and figure out how to add existing arguments not supported in LOBPCG but elsewhere i.e. `ncv` in the `arpack` solver. Does this sound like a good plan? I can push what I have after trying to fiddle w/ the tests if this isn't clear. 

Regarding the first point, is there a good way to determine those argument defaults?

**Comment by lobpcg** [comment]
Consistent doesn't mean identical.

I recommend defaulting n_oversamples = 10 which to my recollection  is the choice in scikit-learn. Rename n_oversamples into ncv, if you want having the same names.

-------- Original message --------

**Comment by clementkng** [comment]
How important would you consider adding support for the other arguments currently not supported by the LOBPCG solver i.e. `which`, `v0`, and `return_singular_vectors`? Some of these should be easy to implement, but others will require some thought.

**Comment by lobpcg** [comment]
@clementkng Sorry, I do not have time to go other the functions to understand the meaning of the arguments that you mention. May be you can try to see yourself how the corresponding scikit-learn functions are set up and mimic this setup? scikit-learn supports basically the same solvers, e.g., arpack, as scipy. 

This is what I have meant by " actually involved, not just copy/paste."

**Comment by lobpcg** [comment]
This issue will be fixed by https://github.com/scipy/scipy/pull/10830

**Comment by ilayn** [comment]
I've added the autoclosing phrase to the PR.
