### ISSUE TITLE
How to translate find_peaks to C++?

### ISSUE THREAD

**Issue by ucasiggcas** [scipy/scipy#9304]
Dear,
how to get version C ++ of find_peaks in python scipy.signal?
Help,
Thx

**Comment by ucasiggcas** [comment]
> Isn't this a duplicate of #9274 ?

But can't solve the problem !!

**Comment by ilayn** [comment]
Unfortunately, what you are asking is a nontrivial programming request. As I mentioned on the other issue, you might ask it on Stackoverflow for better advice on how to code in C/C++ for this particular task or how to translate code automatically as the linked answers suggest. 

Here we are only collecting issues about SciPy codebase hence that's the only help we can offer.

**Comment by giladroyz** [comment]
You can check this out: https://github.com/giladroyz/FindPeaks

**Comment by ev-br** [comment]
Thanks for sharing! 
Posting a comment on a years old issue is sadly not an efficient way of advertising though. Not many people will see it (I only got the notification by accident, for example).

Depending on what you are planning for your project, consider sending a pull request with an update to the `find_peaks` documentation; I think we can carry a link to your project. Or if you are willing to contribute it back to scipy, the first step is to open an RFC issue.
