### ISSUE TITLE
t test calculation is not accurate

### ISSUE THREAD

**Issue by Sreekumar-R-Pillai** [scipy/scipy#9312]
When independent 't' test  is calculated using ' ttest_ind '  the value obtained  is much higher than the acutal t value(calculated manually or using other statistical packages). This error in calculation may be due to calculating  mean and standard deviation as a single group in scipy  instead of treating two separate  groups( t test is only for two groups) separately and proceed the test. In addition, the code doesnot specify the order of entering the dichotomous variable and continuous variable or donot specify any separation codes between these two. 
 It is a serious issue for those use independen t test for their academic, marketing or other research purposes.

The code is given below:
ttest_ind(var1,var2,axis=0,equal_var=True,nan_policy='propagate')

Thank you 

Sreekumar Radhakrishna Pillai,PhD

**Comment by ilayn** [comment]
Hi @Sreekumar-R-Pillai Thanks for taking the time to report it. 

Can you include a copy/pastable code snippet and what the output is that you expected/got from other software?

**Comment by Sreekumar-R-Pillai** [comment]
Thank you Ilayn. I will do it now.

**Comment by Sreekumar-R-Pillai** [comment]
Here is a sample data:
group= 1,1,1,1,2,1,1,2,1,1,2,1.2,2,1,1,1,1,1,1,2,2,2,1
marks= 81, 67, 38, 22, 80, 59, 29, 31, 82, 47, 17, 72, 40, 76, 31, 73, 44, 87, 51, 74, 77, 73 ,29, 48

The scipy t- test calucuation:
data=pd.read_csv('C:\Demodata1.csv')
Here the order of the variable is group- marks:

ttest_ind(data.group,data.marks,axis=0,equal_var=True,nan_policy='propagate')

Out[58]: Ttest_indResult(statistic=-11.966503275415564, pvalue=1.000510120905294e-15)

If we change the order as given below, we will get the same result:
ttest_ind(data.marks,data.group,axis=0,equal_var=True,nan_policy='propagate')
Out[59]: Ttest_indResult(statistic=11.966503275415564, pvalue=1.000510120905294e-15)

Here we can see that in both ways t value is 11.9665 and it is wrong. 

The accurate result of the t-test for group wise difference in marks using one of the popular packages is given below:
t value= 0.378 (equal variance assumed) , df=22, sig(2-tailed=0.709)

here  you can see that in scipy ttest_ind , even if we change the order of the variables , the results doesnot change. As you know, t test is done for testing the singificance of differnce between two group means and therefore we cannot do the analysis in both ways. We can only do group wise (two groups:) analysis for the continuous variable -Marks. The reverse is not possible. But here in scipy ttest_ind, both ways are possible and the result is the same. This is the issue that i would like to bring to your attention. 

Thank you 

Sreekumar Radhakrishna Pillai

**Comment by josef-pkt** [comment]
AFAICS you are misinterpreting the arguments in the test.
ttest_ind takes two samples and not a combined sample and a group indicator.

i.e. split the marks by group and then call `ttest_ind(marks1, marks1)`
see docstring

**Comment by rlucas7** [comment]
@pv would this be an enhancement opportunity? (could be either a separate function an option in ttest_ind)
