### ISSUE TITLE
geometric distribution stats.geom returns negative values if p is very small

### ISSUE THREAD

**Issue by chrisb83** [scipy/scipy#9313]
For very small success probability `p`, `stats.geom` returns negative numbers.

### Reproducing code example:
```
from scipy import stats
import numpy as np

np.random.seed(1234)
stats.geom(np.exp(-20)).rvs(size=5) # ok, large positive numbers
stats.geom(np.exp(-25)).rvs(size=5) # all equal to -2147483648
stats.geom(np.exp(-30)).rvs(size=5) # all equal to -2147483648

np.random.seed(1367)
stats.geom(np.exp(-25)).rvs(size=5) # all equal to -2147483648, except the last 1670264715
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>
1.0.0 1.14.1 sys.version_info(major=3, minor=5, micro=4, releaselevel='final', serial=0)
```

**Comment by ev-br** [comment]
https://github.com/scipy/scipy/blob/v1.1.0/scipy/stats/_discrete_distns.py#L262 : 
` vals = ceil(log(1.0-q)/log(1-p))` should probably use `log1p(-q) / log1p(-p)`

**Comment by josef-pkt** [comment]
this looks like integer overflow in numpy.random

```
>>> np.random.geometric(np.exp(-25), size=5)
array([-2147483648, -2147483648,   998287931, -2147483648, -2147483648])
```

**Comment by akahard2dj** [comment]
In my case, there is no negative returns.
```
>>> print(stats.geom(np.exp(-20)).rvs(size=5))
[103145472 472137975 279343132 746565655 734548744]

>>> print(stats.geom(np.exp(-25)).rvs(size=5))
[ 22916984606  23301258086 116565064309 228501876872 150269801017]

>>> print(stats.geom(np.exp(-30)).rvs(size=5))
[ 4732063972898  7427353758982 12290766111979 13326331530112
  4940962322382]
```

numpy verseion is 1.14.5 and scipy version is '1.2.0.dev0+b7865dd'

**Comment by josef-pkt** [comment]
I guess this is one of the int32/int64 cases that are platform specific that Robert Kern mentioned in the numpy random refactoring and enhancement discussion.

**Comment by akahard2dj** [comment]
When I checked what you said, my result was `int64`.
@chrisb83 In your case, what is the result of `int32/int64`?

**Comment by ilayn** [comment]
I can replicate the overflow in 1.14.4 and 1.15.2 Win10 but cannot on 1.14.5 and 1.15.2 on Ubuntu 18.04.

**Comment by rlucas7** [comment]
on python 2.7 it looks ok on my box (non dev env):
>>> import numpy as np
>>> np.random.seed(1234)
>>> stats.geom(np.exp(-20)).rvs(size=5) # ok, large positive numbers
array([103145472, 472137975, 279343132, 746565655, 734548744])
>>> stats.geom(np.exp(-25)).rvs(size=5) # all equal to -2147483648
array([ 22916984606,  23301258086, 116565064309, 228501876872,
       150269801017])
>>> stats.geom(np.exp(-30)).rvs(size=5) # all equal to -2147483648
array([ 4732063972898,  7427353758982, 12290766111979, 13326331530112,
        4940962322382])
>>> 
>>> 
Lucass-MacBook:~ rlucas$ python -V
Python 2.7.15

and python3 also looks ok:

Lucass-MacBook:~ rlucas$ python3 
Python 3.7.0 (default, Jun 29 2018, 20:13:13) 
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy import stats
>>> import numpy as np
>>> 
>>> np.random.seed(1234)
>>> stats.geom(np.exp(-20)).rvs(size=5) # ok, large positive numbers
array([103145472, 472137975, 279343132, 746565655, 734548744])
>>> stats.geom(np.exp(-25)).rvs(size=5) # all equal to -2147483648
array([ 22916984606,  23301258086, 116565064309, 228501876872,
       150269801017])
>>> stats.geom(np.exp(-30)).rvs(size=5) # all equal to -2147483648
array([ 4732063972898,  7427353758982, 12290766111979, 13326331530112,
        4940962322382])
>>> 
>>> np.random.seed(1367)
>>> stats.geom(np.exp(-25)).rvs(size=5) # all equal to -2147483648, except the last 1670264715
array([156454800182,   3369070642,  78276839855,  42746029743,
         1670264715])
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.15.1 sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)

**Comment by rlucas7** [comment]
@akahard2dj, @ev-br, I investigated a little more in the process of addressing requested changes from @chrisb83 on PR #9309 I b/c the negative values will still show up on int64 by for a smaller value of the probability. I also tried the switch to log1p() method, and you do still get some negative values from under/overflow issues:

(scipy-dev) Lucass-MacBook:stats rlucas$ python 
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, scipy, numpy; print(scipy.version, numpy.version, sys.version_info)
<module 'scipy.version' from '/Users/rlucas/scipy-dev/scipy/scipy/version.py'> <module 'numpy.version' from '/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/numpy/version.py'> sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
>>> from scipy.stats import geom
>>> import numpy as np
>>> stats.geom(np.exp(-25)).rvs(size=5) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'stats' is not defined
>>> geom(np.exp(-25)).rvs(size=5) 
array([ 50135883991, 114412509483,  54405822703, 181680037352,
        32707250124])
>>> geom(np.exp(-50)).rvs(size=5) 
array([-9223372036854775808, -9223372036854775808, -9223372036854775808,
       -9223372036854775808, -9223372036854775808])
>>> type(geom(np.exp(-50)).rvs(size=1)[0]) 
<class 'numpy.int64'>

**Comment by akahard2dj** [comment]
@ev-br 
if I change `vals = ceil(log(1.0-q)/log(1-p))` to `vals = ceil(log1p(1.0-q)/log1p(1-p))`, test is failed.
```
self = <scipy.stats.tests.test_distributions.TestGeom object at 0x6fff6673550>

    def test_ppf(self):
        vals = stats.geom.ppf([0.5, 0.75, 0.875], 0.5)
        expected = array([1.0, 2.0, 3.0])
>       assert_array_almost_equal(vals, expected)
E       AssertionError:
E       Arrays are not almost equal to 6 decimals
E
E       (mismatch 66.66666666666666%)
E        x: array([1., 1., 1.])
E        y: array([1., 2., 3.])

expected   = array([1., 2., 3.])
self       = <scipy.stats.tests.test_distributions.TestGeom object at 0x6fff6673550>
vals       = array([1., 1., 1.])
```

I am figuring out this problem. I will put the PR.

**Comment by ev-br** [comment]
@akahard2dj The alternative for `log(1-x)` is `log1p(-x)`, not `log1p(1-x)` (which is `log(1 + 1 - x)`)

**Comment by mdhaber** [comment]
The implementation `stats.geom.rvs` is now:
```python3
    def _rvs(self, p, size=None, random_state=None):
        return random_state.geometric(p, size=size)
```
and it has relied on NumPy to generate random variates since 2013 (at least), so the discussion above about `ppf` was a separate issue that seems to have been fixed in gh-9320.

There are two problems here, only one of which is SciPy.

If `RandomState` is used to generate the random variates, we have a problem that we can't fix in SciPy.

```python3
np.random.seed(0)
np.random.geometric(np.exp(-25))  # -2147483648
type(np.random.geometric(np.exp(-25))) # int
np.random.geometric(np.exp(-25), size=5).dtype # dtype('int32')
```

If `Generator` is used to generate the random variates, NumPy is fine:
```python3
rng = np.random.default_rng(0)
rng.geometric(np.exp(-35))  # 1078381146351774
type(rng.geometric(np.exp(-35))) # int
rng.geometric(np.exp(-35), size=5).dtype # dtype('int64')
```

but SciPy converts it to `int32` when `size != ()`, at least on some platforms:
```python3
stats.geom.rvs(np.exp(-25), size=5, random_state=rng).dtype # dtype('int32')
```

The relevant code is:
https://github.com/scipy/scipy/blob/7abf27f2fe9046814a0eb6e618ad310bd29a15c4/scipy/stats/_distn_infrastructure.py#L1104-L1111

I think it is undesirable for the `dtype` behavior to be platform specific, so I think we should consider SciPy's conversion to int32 a bug and just fix it by specifying `np.int64` instead of `int`. With that one change, the problem is fixed, and all tests pass. (If we think that `np.int32` is preferred in some cases, then it seems that we should start with asking NumPy to offer `dtype` as a parameter for all `Generator` rvs methods. I don't think we should just "fix" NumPy's choice here.)

I'll submit a PR.
