### ISSUE TITLE
SLSQP fails in nested optimization

### ISSUE THREAD

**Issue by GeneraalFandaal** [scipy/scipy#9316]
The slsqp method fails (in various ways) when used in nested optimization problems where the objective function itself makes a call to the slsqp algorithm. I discovered the issue with a large and complicated optimization process that uses the minimize method. At some stage the objective function was evaluated with an array of NaNs, with only "sensible" input generated throughout the process.

Although I have not found a way to reproduce the NaNs simply, the following code also illustrates the problem.

### Reproducing code example:
```
import scipy.optimize as opt

def F_outer(x):
    # Inner optimization
    result = opt.minimize(F_inner, (3, 4), method="SLSQP")
    y = x[0]**2 + x[1]**2 + x[2]**2
    return y

def F_inner(x):
    y = x[0]**2 + x[1]**2
    return y

if __name__ == "__main__":
    # Outer optimization
    result = opt.minimize(F_outer, (5, 5, 5), method="SLSQP")
    print(result)
```

### Error message:
```
The code fails to terminate.
```

### Scipy/Numpy/Python version information:
```
I tested this with the current scipy master (1.2.0.dev0+ad00a9e), numpy 1.14.0, python 3.6.5, openSUSE.
```

I really wanted this to work, so I did some digging... I found that the slsqpb subroutine in slsqp_optmz.f makes use of variables with the SAVE attribute. These are not passed in as parameters to slsqp. When nested calls to minimize are made, the correct state of the outer optimization process is not restored when the inner optimization terminates.

I suspect that fmin_slsqp will have the same problem.

I have managed to fix the issue on my side, will submit a pull request shortly.

**Comment by pv** [comment]
gh-9317 was merged.
