### ISSUE TITLE
Sparse matrix addition/subtraction eliminates explicit zeros

### ISSUE THREAD

**Issue by santiagoropb** [scipy/scipy#9318]
<<Please describe the issue in detail here, and for bug reports fill in the fields below.>>

Addition of sparse matrices removes explicit zeros. While the result is correct the structure of the resulting sparse matrix ignores the explicit zeros that come from the original matrices. This might be a problem for subroutines that rely on the structure of the linear system (e.g sparse linear solver).  

I believe the issue can be corrected by modifying the _cs_matrix._binopt(other, '_plus_') subroutine 

### Reproducing code example:
```python
from scipy.sparse import coo_matrix
import numpy as np

row  = np.array([0, 3, 1, 0])
col  = np.array([0, 3, 1, 2])
data = np.array([0, 5, 7, 9])
m = coo_matrix((data, (row, col)), shape=(4, 4))
print(m.nnz) # output = 4
mm = m + m
print(mm.nnz)  # output = 3
```

### Scipy/Numpy/Python version information:
```python
# scipy.__version__ = '1.1.0'
# numpy.__version__ = '1.15.1'
# sys.version_info(major=3, minor=5, micro=5, releaselevel='final', serial=0)
```

**Comment by santiagoropb** [comment]
Any comments on this?

**Comment by pv** [comment]
The design decision iirc as per previous discussions was to preserve explicit zeros.
So now it's up for someone to roll their sleeves to fix it.

**Comment by santiagoropb** [comment]
Has someone had the time to fix this?
