### ISSUE TITLE
Clarify docs that affine_transform works 'backwards'?

### ISSUE THREAD

**Issue by takluyver** [scipy/scipy#9328]
I spent a while the other day struggling to make `affine_transform` do what I want. Perhaps this was just me being dense, but the general descriptions I was reading of affine transformations all talk about applying the matrix to the *input* coordinates to translate them to the output coordinates. It took me quite a while to understand that the function in scipy applies the transformation to the *output* coordinates to find where it should look in the input for the pixels.

The docs do, in fact, say this:

> Given an output image pixel index vector o, the pixel value is determined from the input image at position np.dot(matrix, o) + offset.
> ...
> The given matrix and offset are used to find for each point in the output the corresponding coordinates in the input by an affine transformation. 

But in trying to understand the underlying mathematics at the same time, and flipping between a few different tabs, I overlooked this. I wonder if it's worth making this more explicit, along the lines of:

> This is the *opposite* of how an affine transformation is typically described: the matrix for `affine_transform()` transforms the output space onto the input array to find the data to interpolate. If you have a matrix to transform the input space to the output, you can use its inverse (`numpy.linalg.inv`) for the transformation required here.

(I had a similar conceptual difficulty with `geometric_transform` and `map_coordinates`: I'm thinking in terms of input->output, whereas all these functions work the other way around. But with those I realised from the docs that they weren't what I wanted before I tried to use them.)

**Comment by matthew-brett** [comment]
Yes, sorry, this is a fairly typical source of confusion for the resampling beginner.   I'm afraid I'm not an expert, but this output -> input direction is called "pull" resampling.  As you can imagine, doing it the other way round (input -> output, "push" resampling) is a much odder thing, in that you now have to work out what to do with this value that corresponds to a non-integer point in the new (output) image.

https://bic-berkeley.github.io/psych-214-fall-2016/resampling_with_ndimage.html#reampling-pull-push

**Comment by takluyver** [comment]
Thanks, the terms 'pull' and 'push' help make it clearer. It makes sense in terms of what's happening computationally, it's just a mental leap when you're thinking about transforming an image in a more abstract way.

If it's OK, I'll make a PR to try to clarify this in the docstring.
