### ISSUE TITLE
Importing linalg causes different outputs of multivariate_normal

### ISSUE THREAD

**Issue by sabrina-ar** [scipy/scipy#9335]
For some N the sample script results in different outputs depending on whether scipy.linalg is imported or not and whether running the script with the pycharm console or the terminal.

For N=1, 2, 3:
- Same outputs with pycharm console and terminal both for "import scipy.linalg" being turned on and commented out

For N=4, 5, 6, ...:
- if "import scipy.linalg" is turned off: running by pycharm console and terminal have same result
- if "import scipy.linalg" is turned on:
  - running by pycharm console has different results compared to scipy.linalg not being imported
  - running by terminal has also different results compared to scipy.linalg not being imported and also divergent to the outputs of the pycharm console

### Reproducing code example:
```
import sys
import numpy as np
import scipy
# import scipy.linalg

print np.__version__
print scipy.__version__


if __name__ == '__main__':
    np.random.seed(10)
    N = 4
    cov = np.zeros((N, N))
    cov[:] = .2
    cov[range(N), range(N)] = 1.
    print cov
    print cov.shape

    data_field = np.random.multivariate_normal(mean=np.zeros(N), cov=cov, size=3)

    print data_field
    sys.exit(0)
```

### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)

PyCharm console:
('0.17.0', '1.10.0', sys.version_info(major=2, minor=7, micro=15, releaselevel='final', serial=0))

Terminal:
('0.17.1', '1.10.0', sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0))

```

**Comment by ilayn** [comment]
I can't replicate this with Python 3, Scipy 1.1.0, NumPy 1.15.0

**Comment by sabrina-ar** [comment]
> I can't replicate this with Python 3, Scipy 1.1.0, NumPy 1.15.0

For compliance with other necessary packages, I need to use Python 2.7 and depending on whether using Scipy 0.17.0 or 0.17.1 I get different outputs of np.random.multivariate_normal.

**Comment by rgommers** [comment]
we dropped Python 2.7 and the report is for a very old SciPy version. Since this doesn't replicate, I think we'll close it. Thanks all.
