### ISSUE TITLE
scipy.signal.find_peaks key typo in documentation

### ISSUE THREAD

**Issue by atpage** [scipy/scipy#9337]
There is no 'peak_prominences' in the properties dict returned by find_peaks().  The correct key is just 'prominences'.  Typo is here:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html

### Reproducing code example:

    import scipy
    peaks, props = scipy.signal.find_peaks([1,2,5,2,1],prominence=2)
    props['peak_prominences']
    props['prominences']

### Error message:

KeyError: 'peak_prominences'

### Scipy/Numpy/Python version information:

1.1.0 1.15.1 sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)

**Comment by larsoner** [comment]
@atpage can you open a PR to fix the documentation?

**Comment by atpage** [comment]
Done.  https://github.com/scipy/scipy/pull/9340

**Comment by Kai-Striega** [comment]
Closing as merged PR resolves issue.
