### ISSUE TITLE
Incorrect output length from scipy.signal.dlsim

### ISSUE THREAD

**Issue by EdwardMcCants** [scipy/scipy#9342]
I created a discrete transfer function with a dt of 0.025.  I provided an x-vector of length 38,733 and a time vector created externally from 0 to 968.3.  The output data and time vectors that I got back had 38,732 elements instead of 38,733.  The problem went away when I did not input the time vector.

I believe that the error was introduced via the else section of this block of code (lines 3302-3307 in ltisys.py):
```
    if t is None:
        out_samples = len(u)
        stoptime = (out_samples - 1) * system.dt
    else:
        stoptime = t[-1]
        out_samples = int(np.floor(stoptime / system.dt)) + 1
```

What seems to happen is that 968.3/0.025 = 38731.99999999999, which floors to 38731 instead of 38732.  I recommend changing np.floor() to a function that rounds to the nearest integer instead.

**Comment by rgommers** [comment]
@EdwardMcCants thanks for the report, that looks like a bug indeed. It would be helpful to have a small self-contained code example that demonstrates the issue. Could you please provide one.

**Comment by rgommers** [comment]
Looking at this again, can't reproduce it either. The issue seems to simply be a misunderstanding about how `np.arange` works (the `stop` argument is typically not included in the produced array).

**Comment by arun-aks** [comment]
I can replicate this with the following code:

```python
import numpy as np
import scipy.signal as signal

FS = 128e8;
n = 49

system = ([1, 0], [1, 0], 1/FS)
tmp, resp = signal.dimpulse(system, n=n);
print(n, tmp.shape, resp[0].shape)


system1 = signal.dlti(*system[:-1], dt=system[-1])._as_ss()
t = np.linspace(0, n * system1.dt, n, endpoint=False)
u = np.zeros((n,))
one_output = signal.dlsim(system1, u, t=t, x0=None)

print(n, one_output[0].shape, one_output[1].shape)
```

The output I get with scipy version 1.4.1 is 
```
49 (48,) (48, 1)
49 (48,) (48, 1)
```

What is expected is
```
49 (49,) (49, 1)
49 (49,) (49, 1)
```
