### ISSUE TITLE
Maybe a problem in docstring

### ISSUE THREAD

**Issue by DanKatzuv** [scipy/scipy#9347]
https://github.com/scipy/scipy/blob/f238270111976d00615686395df0986847c25132/scipy/interpolate/interpolate.py#L3003-L3004
Is that supposed to be `Don't know`?
Thank you!

**Comment by ev-br** [comment]
So it's been there for at least six years and no one noticed. Huh. At any rate, the function's deprecated, so not worth using in new code or spending time on.

**Comment by DanKatzuv** [comment]
Well, I guess I could be proud noticing it 😜. I just wanted to see if it possible to have a quintic spline for using in auto drive for my FRC team.
Anyway, where is it written that this function is deprecated?

**Comment by DanKatzuv** [comment]
> what you linked is a fairly old snapshot, have a look at what's in master
Yeah, now I see. I jumped into the source file from the API and did not realize it was not master.

**Comment by ev-br** [comment]
Ok, I'll close this. If something does not work with recommended ways of working with quintuc splines, please open a separate issue.
