### ISSUE TITLE
Wrong values from scipy.special.erf  (erf(x) != -erf(-x))

### ISSUE THREAD

**Issue by chrisrosner** [scipy/scipy#9348]
We are seeing incorrect values returned from scipy.special.erf

We have some equations that depend on the symmetry of the erf function, but scipy violates this assumption.

Mathematically, for reals, erf(x) == -erf(-x), but scipy.special.erf does not seem to honor this property.

The difference from expectation seems to be beyond a simple floating point representation problem.

### Reproducing code example:
```
# succeeds
import math
difference = math.erf(5.905732037710919)+math.erf(-5.905732037710919)
assert abs(difference) == 0.0

# fails, difference should be 0.0, difference is actually -1.1102230246251565e-16
import scipy.special
difference = scipy.special.erf(5.905732037710919)+scipy.special.erf(-5.905732037710919)
assert abs(difference) == 0.0
```

### Error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
```

### Scipy/Numpy/Python version information:
```
1.1.0 1.14.0 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)

(Older versions of scipy affected as well)
```

**Comment by ilayn** [comment]
That difference is smaller than the machine precision for floats

**Comment by chrisrosner** [comment]
What is the machine precision,

**Comment by ilayn** [comment]
The smallest increment between two consecutive numbers for 64bit floats. Type `np.spacing(1.)` or `np.finfo(float).eps` in your terminal

**Comment by chrisrosner** [comment]
So, yes, it is possible that the value is within machine precision, but why would the function not be symmetrical around 0?  

x and -x are able to both be represented in floating points via the sign bit. I don't see why numerical precision is the explanation for this behavior, especially in the face of math.erf behaving differently.

**Comment by chrisrosner** [comment]
I did some more testing:

In this region of floats (near 5.905732037710919), the positive inputs to erf agree with math.erf, but the negative values always disagree.

import numpy
import math
import scipy.special

numpy.nextafter(0,1)

positive_differences = 0
negative_differences = 0


x = 5.905732037710919
for i in range(1,10000000):
    if x == abs(-1.0*x):
        if math.erf(x) != scipy.special.erf(x):
            positive_differences += 1
        if math.erf(-x) != scipy.special.erf(-x):
            negative_differences += 1
        x = numpy.nextafter(x, +math.inf)
        if i % 100000 == 0:
            print(x, i, positive_differences, negative_differences)

print(positive_differences, negative_differences)

**Comment by ilayn** [comment]
That's probably because negatives are rounded up but I still didn't understand the problem.

**Comment by ilayn** [comment]
It's actually not rounding up but actually the cut-off of scipy (cdflib) version is set at 5.8. 

https://github.com/scipy/scipy/blob/master/scipy/special/cdflib/erf.f

**Comment by person142** [comment]
>  cut-off of scipy (cdflib)

We use Cephes `erf`, not cdflib.

**Comment by pv** [comment]
Computing results to exact bit-perfect floating point precision is not a design criterion for these functions, so they generally do not do that. Retaining bit-perfect symmetries would be nice, and for this case would be easy to guarantee.

The answer for "why" in this case is that `erf(x) = 1 - erfc(x)`.

**Comment by ev-br** [comment]
(just had an open environment and a bit of time to spare) It seems easiest to throw gh-9351 over the wall and forget.
