### ISSUE TITLE
request for clarification in documentation

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [scipy/scipy#9349]
From examination of the code that is wrapped by `scipy.interpolate.LSQSphereBivariateSpline`, I discovered that this method fits a bivariate cubic spline.  It would be helpful if the documentation were updated to indicate that the order of the spline is 3 (cubic or bicubic).

**Comment by ev-br** [comment]
PR welcome.

**Comment by abhinuvpitale** [comment]
taking this up!
