### ISSUE TITLE
scipy.stats.pearsonr returns r=1 if r_num/r_den = inf

### ISSUE THREAD

**Issue by aaronHydro** [scipy/scipy#9353]
This relates to the scipy.stats.pearsonr function: 

    # x and y should have same length.
    x = np.asarray(x)
    y = np.asarray(y)
    n = len(x)
    mx = x.mean()
    my = y.mean()
    xm, ym = x - mx, y - my
    r_num = np.add.reduce(xm * ym)
    r_den = np.sqrt(_sum_of_squares(xm) * _sum_of_squares(ym))
    r = r_num / r_den
    print(r)
    # Presumably, if abs(r) > 1, then it is only some small artifact of
    # floating point arithmetic.
    r = max(min(r, 1.0), -1.0)
    df = n - 2
    if abs(r) == 1.0:
        prob = 0.0
    else:
        t_squared = r**2 * (df / ((1.0 - r) * (1.0 + r)))
        prob = _betai(0.5*df, 0.5, df/(df+t_squared))

    return r, prob

If one of the input datasets is comprised of very small numbers, it is possible for r_num to be a non-zero value whilst r_den is 0 due to the _sum_of_squares function returning values <2^-1022. Therefore, r is calculated to be inf 

Due to these lines: 

    # Presumably, if abs(r) > 1, then it is only some small artifact of
    # floating point arithmetic.
    r = max(min(r, 1.0), -1.0)

The inf value of r is changed to a value of 1, which is the final value returned from the function. This erroneously indicates perfect correlation between the two input datasets. So perhaps there is a need for an alternative check to determine whether artifacts of floating point arithmetic lead to values of r > 1, or otherwise allow Inf as an output?

Here is a brief example, with the pearsonr function modified to print the original and output r values: 
```
In [17]: y = [2.48e-188,7.41e-181,4.09e-208,2.08e-223,2.66e-245]

In [18]: x = [0.004434375,0.004756007,0.003911996,0.0038005,0.003409971]

In [19]: scipy.stats.pearsonr(x,y)
Orignal r = inf
Output r = 1.0
```

### Scipy/Numpy/Python version information:
```
<<Output from 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'>>

('1.0.0', '1.14.0', sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0))

```

**Comment by chrisb83** [comment]
related issue is #8980
