### ISSUE TITLE
Why does sparse.linalg.svds not expose ARPACK's shift-invert mode like sparse.linalg.eigsh does?

### ISSUE THREAD

**Issue by leotrs** [scipy/scipy#9357]
`sparse.linalg.eigsh` exposes shift-invert mode through the keyword parameter `sigma` (see documentation for [sigma](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigsh.html#scipy.sparse.linalg.eigsh) and [shift-invert](https://docs.scipy.org/doc/scipy/reference/tutorial/arpack.html)). However, [svds](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.svds.html) does not expose this functionality, even though it depends on the same underlying ARPACK routines. This could be helpful when computing internal (small) singular values.

**Comment by lobpcg** [comment]
The smallest singular values are currently already supported in svds.
  
Internal (not largest or smallest) singular values are rarely needed in practice. Moreover, the shift-invert mode for singular values would require the explicit computation of the normal matrix, while the current implementation only accesses the original matrix via matvec and rmatvec LinearOperator calls, i.e., does not compute the normal matrix.

**Comment by tylerjereddy** [comment]
Can maybe be closed now that we have expert response to a query?
