### ISSUE TITLE
Planck distribution is a geometric distribution

### ISSUE THREAD

**Issue by chrisb83** [scipy/scipy#9359]
`stats.planck` is just a geometric distribution `stats.geom` with `p = 1 - exp(-lambda)`. I am not aware that Planck distribution is a known name for it.

Currently, `planck` is incorrectly defined for negative `lambda` as well (see #9358).

Should `planck` be deprecated?

**Comment by LuckyPigeon** [comment]
In the scipy docs, geom.pmf(k) = (1 - p) ^ (k - 1) * p and planck.pmf(k) = (1 - exp(-lambda)) * exp(-lambda * k) = (1 - (1  - exp(-lambda)) ^ ( k - 1) * (exp(-lambda)) * (1 - exp(-lambda)), so it's just not simple as p = 1 - exp(-lambda), so I think we shouldn't deprecated stats.planck. Thanks!

**Comment by chrisb83** [comment]
OK, but `geom.pmf(k, 1-exp(-a)) == planck.pmf(k-1, a)`, so difference is a shift by one (which can be achieved with the parameter loc). Did i overlook sth?

**Comment by LuckyPigeon** [comment]
Your second parameter is `(1 - exp(-a))`, but planck is more than geom with `exp(-a)`, so it can not solve by shift by one.

**Comment by chrisb83** [comment]
Numerical "proof":
```
import numpy as np
from scipy.stats import planck, geom

a = 0.5
k = np.arange(20)
sum(abs(geom.pmf(k, 1-np.exp(-a)) - planck.pmf(k-1, a))) # 1.30e-18
```
