### ISSUE TITLE
Does scipy.interpolate.griddata(method="cubic") performs natural neighbor interpolation?

### ISSUE THREAD

**Issue by DayuanJiang** [scipy/scipy#9365]
In [scipy cookbook](https://scipy-cookbook.readthedocs.io/items/Matplotlib_Gridding_irregularly_spaced_data.html), it writes:

>  It performs "natural neighbor interpolation" of irregularly spaced data a regular grid, which you can then plot with contour, imshow or pcolor.

with the code below: 
`zi = griddata((x, y), z, (xi[None,:], yi[:,None]), method='cubic')`

But I have read the [griddata page](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.griddata.html), and the [CloughTocher2DInterpolator page](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.CloughTocher2DInterpolator.html#scipy.interpolate.CloughTocher2DInterpolator), and I could not find any words about "natural neighbor interpolation".

So, does scipy.interpolate.griddata(method="cubic") performs natural neighbor interpolation? Any help would be appreciated.

**Comment by pv** [comment]
The answer is no.

If you read the cookbook page carefully, it talks about matplotlib.griddata when discussing nat. neighbors.
