### ISSUE TITLE
scipy.integrate.cumtrapz issue

### ISSUE THREAD

**Issue by nickpoerio** [scipy/scipy#9368]
Cumtrapz not working correctly with the dx argument (x=None). Output should be multiplied by 2

### Reproducing code example:

dx=.05
scipy.integrate.cumtrapz(y,x=None,dx=dx)

```
Sample code to reproduce the problem
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

**Comment by nickpoerio** [comment]
Hi @ilayn,

I discovered a subtle issue in my code, the function is working correctly. Sorry for the setback and thanks for your time. N.

**Comment by ilayn** [comment]
No problem. Thanks for reporting anyways.
