### ISSUE TITLE
SciPy fix for AIX installation

### ISSUE THREAD

**Issue by TeejIBM** [scipy/scipy#9375]
Please review the following page:

https://www.ibm.com/developerworks/community/forums/html/topic?id=10b1cba0-ff19-49b2-b2cd-2e924ffda12a#repliesPg=0

Two steps are required in order to make this package work on AIX:

1.  Invocation of LDFLAGS="-lpthread" during installation -- this should be added as part of the initial check.

2.  Modification of the following code -scipy/special/cephes/dd_real.h:108 from:

#if defined(__STDC__) && defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L) && defined(NAN)

to:

#if defined(__STDC__) && defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L) && defined(NAN) && !(defined(_AIX))

Once done, AIX installation works for us for AIX 7.1.

Thanks!

**Comment by rgommers** [comment]
This was fixed by gh-9374, closing
