### ISSUE TITLE
Error in Non-Central Chi-Squared Distribution Documentation

### ISSUE THREAD

**Issue by AbhilashG6** [scipy/scipy#9378]
My issue is about a minute error in the documentation for the non-central chi-squared distribution. The probability density function has the incorrect term 'exp(-(nc+df)/2)'. This should instead have been 'exp(-(nc+x)/2)'. Ref: https://en.wikipedia.org/wiki/Noncentral_chi-squared_distribution#Definition
Error is at : https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.ncx2.html

**Comment by ilayn** [comment]
Thanks for taking time to report @AbhilashG6 this has been fixed in the new versions of the documentation. What you are looking at is the version 0.14 documentation. The new versions starting from 0.15 has the correct terms.
