### ISSUE TITLE
linregress should warn user in 2x2 array case

### ISSUE THREAD

**Issue by kstacer** [scipy/scipy#9381]
The heuristic for splitting an array into x and y inside linregress is ambiguous for 2x2 arrays.  I discovered this ambiguity when I called linregress with a 2x2 array where x and y were oriented as columns (a common case when working with pandas dataframes) and got an unexpected result.

### Reproducing code example:

```
Sample code to reproduce the problem:
#A simple numpy array that is 2x2 where each row is the x, y values. 
from scipy.stats import linregress
import numpy as np 
arr = np.array([[30,31], [50,50]])
slope, intercept, r_value, p_value, std_err = linregress(arr)
#slope = 1.0
# intercept =20.0
# r_value = 1.0
# p_value = 0.0
#std_err = 0.0

#Visualize with plot
import matplotlib.pyplot as plt
x = arr[:,0]
y = arr[:,1]
plt.plot(x, y, 'o', label='original data')
plt.plot(x, intercept + slope*x, 'r', label='fitted line')
plt.legend()
plt.show()
print(r_value**2)

#Tranposing the array gives the expected result:
slope, intercept, r_value, p_value, std_err = linregress(arr.T)
#slope = 1.0
#intercept = 1.0
#r_value = 1.0
#p_value = 0.0
#std_err = 0.0

x = arr[:,0]
y = arr[:,1]
plt.plot(x, y, 'o', label='original data')
plt.plot(x, intercept + slope*x, 'r', label='fitted line')
plt.legend()
plt.show()
print(r_value**2)
```

### Desired Resolution:
 In this case, no error message is detected; however, the ambiguity of the 2x2 case invites some additional documentation and perhaps a RunTime warning message when this corner case is detected. At the least, a clear description of this heuristic in the documentation is desired explaining how x and y are created internally.

### Scipy/Numpy/Python version information:

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
('1.0.0', '1.13.3', sys.version_info(major=2, minor=7, micro=14, releaselevel='final', serial=0))
```

**Comment by ev-br** [comment]
I think it's best to add a note to the documentation, either in the Notes section, or under Examples. Pull request welcome, I'd say.

**Comment by ludcila** [comment]
Hi, I would like to take this up to get some practice :grinning: 

I noticed that there is already a Notes section which is not written directly in the docstring, but appended somewhere else. In order to keep things simple, do you think it would be enough to expand the Parameters description:

```
        Two sets of measurements.  Both arrays should have the same length.
        If only x is given (and y=None), then it must be a two-dimensional
        array where one dimension has length 2.  The two sets of measurements
        are then found by splitting the array along the length-2 dimension.
```
with
```
        In the case where y=None and x is a 2x2 array, the splitting will be
        done along the rows, resulting in the sets x[0] and x[1].
```
?

**Comment by ilayn** [comment]
@ludcila Thanks for taking the time. The situation is a bit awkward indeed. The extra part comes from this part 

https://github.com/scipy/scipy/blob/701b9ac6c451e68a0a5659a6186c1f4d847a0be1/scipy/stats/mstats_basic.py#L59-L65

Then further down the file there is the part 

https://github.com/scipy/scipy/blob/701b9ac6c451e68a0a5659a6186c1f4d847a0be1/scipy/stats/mstats_basic.py#L840-L841

I think this was meant as a generic machinery however only lingress is using it hence I think we can take it back to its original docstring by cleaning these up.

**Comment by ludcila** [comment]
Hi @ilayn, I can take care of putting the notes in the docstring and cleaning that up. Do you think what I wrote is enough to clarify the 2x2 case? If so, should it be added to the parameters section or to the notes? :smiley:

**Comment by rgommers** [comment]
Fixed by gh-9423, so closing. Thanks all!

> Do you think what I wrote is enough to clarify the 2x2 case?

yes, it was clear:)
