### ISSUE TITLE
freeing non-valid pointer in ndimage.rank_filter

### ISSUE THREAD

**Issue by jakirkham** [scipy/scipy#9388]
Python crashing due to SciPy freeing a pointer that does not point to allocated memory.

### Reproducing code example:

```python
$ ipython
Python 3.5.5 | packaged by conda-forge | (default, Apr  6 2018, 13:43:56) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np

In [2]: import scipy.ndimage as spimg

In [3]: a = np.random.random((10, 20, 30))

In [4]: r_1 = spimg.rank_filter(a, 0.5, footprint=np.ones((1, 1, 10), dtype=bool))
python(79733,0x7fff78c69000) malloc: *** error for object 0x7fdf9b146468: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

### Error message:

```gdb
python(79733,0x7fff78c69000) malloc: *** error for object 0x7fdf9b146468: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

### Scipy/Numpy/Python version information:

```python
In [1]: import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.15.1 sys.version_info(major=3, minor=5, micro=5, releaselevel='final', serial=0)
```

**Comment by ilayn** [comment]
Does it happen also when you use an integer for rank and either size or footprint ?

**Comment by anjugeethanair** [comment]
> Sure. Happy to. This should be a good problem for learning (or becoming more familiar with) some low level debugging tools if that is interesting to you. Are you familiar with `gdb` or `valgrind`?

Yes, I have used both. As per my understanding to debug a C program, we need the debug symbols and the executable. So should I expect both to be available in some location after I install with "python setup.py install"?

**Comment by anjugeethanair** [comment]
> Sure. Happy to. This should be a good problem for learning (or becoming more familiar with) some low level debugging tools if that is interesting to you. 

Thank you very much! Yes, I am interested to learn some debugging tools.

**Comment by jakirkham** [comment]
Right, so this likely requires a debug build of Python to be installed. I'm not sure how SciPy handles debug symbols (maybe a core dev can chime in), but you will want to make sure that the appropriate compiler flags are passed (i.e. `-DNDEBUG` should not be in the compiler flags, also `-g` should be present on `gcc` or similar flag for other compilers).

Valgrind can be reasonably effective even without debug symbols. Given it is a memory issue, it's also a good choice for this problem. GDB can be used to further isolate the line if Valgrind doesn't already point you to the fix. So would probably start by running a short reproducer script with Valgrind and see what information it gives.

**Comment by ilayn** [comment]
Before we jump to the internals, this function should not allow nonintegers to be passed to lower levels since 1.5 rank is not meaningful. 

Don't take it as a discouraging comment please you can still work on it but we need a quick exit strategy anyways against floats regardless of what is happening at the C level.

**Comment by anjugeethanair** [comment]
Thank you for jumping in @ilayn , So the function _rank_filter in filters.py should have an error message return of rank is not integer? I am happy to make that fix :)

**Comment by anjugeethanair** [comment]
I created a pull request-
https://github.com/scipy/scipy/pull/9392
