### ISSUE TITLE
range of truncnorm.logpdf could be extended

### ISSUE THREAD

**Issue by boeseMilch** [scipy/scipy#9403]
When calling the truncated normal distribution with an interval far away from zero, the logpdf seems to exhibit a numerical underflow even though it would be well defined.

```
from scipy.stats import truncnorm
print(truncnorm.logpdf(-39.9, -40, -39)) # should be around -40, but is inf 
```
There are applications for values so far from the truncation interval, for example when doing mean regression with a truncated Gaussian likelihood, where the initial guess for the mean might be far of.

### Scipy/Numpy/Python version information:
1.1.0 1.14.2 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)

**Comment by rlucas7** [comment]
Possibly a related solution by Zdravko Botev and Pierre L'Ecuyer 
https://www.iro.umontreal.ca/~lecuyer/myftp/papers/truncated-normal-book-chapter.pdf

**Comment by rgommers** [comment]
fixed by gh-10104
