### ISSUE TITLE
ndimage.interpolation.geometric_transform hangs without error if return value of mapping is not tuple

### ISSUE THREAD

**Issue by clemisch** [scipy/scipy#9404]
`scipy.ndimage.interpolation.geometric_transform` hangs indefinitely without CPU usage if the mapping function supplied does not return a tuple. 

### Reproducing code example:

```python
import numpy as np
import scipy.ndimage as nd
import scipy.misc as misc

img = misc.ascent()

def mapping(coord):
    return np.array(coord, dtype=int)

img_transform = nd.interpolation.geometric_transform(img, mapping)
```

This hangs and does not use CPU.

### Scipy/Numpy/Python version information:

```
('1.1.0', '1.15.2', sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0))
```

**Comment by ilayn** [comment]
With the current master I get 

```Shell
Traceback (most recent call last):

  File "<ipython-input-1-64fa954c3731>", line 9, in <module>
    img_transform = nd.interpolation.geometric_transform(img, mapping)

  File "c:\...\appdata\local\programs\python\python36\lib\site-packages\scipy-1.2.0.dev0+209e1c6-py3.6-win-amd64.egg\scipy\ndimage\interpolation.py", line 240, in geometric_transform
    extra_keywords)

TypeError: bad argument type for built-in operation
```

**Comment by clemisch** [comment]
An error message is okay. I'm only annoyed by the _silent_ hang-up. 

I installed `scipy` via `pip`, all updated. That should be a fairly recent version right?

**Comment by ilayn** [comment]
It means something is already changed in the `master` branch and fails. If that is the case it would be available with the next release 1.2.0.

**Comment by clemisch** [comment]
If the code is so keen on tuples, wouldn't a simple 

```python
if type(mapping_out) is not tuple:
    raise ValueError
```

be sufficient? Otherwise, it should work with all iterables, since a tuple is arguably the most limited one.

**Comment by sethtroisi** [comment]
SciPy now throws an error `TypeError: bad argument type for built-in operation` and no additional followup for 1.5 years
