### ISSUE TITLE
Error in docstring of show_options ?

### ISSUE THREAD

**Issue by johannfaouzi** [scipy/scipy#9407]
Hi,

My issue is about the docstring of the [show_options](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.show_options.html#scipy.optimize.show_options) function. Here is the piece of code of interest:
https://github.com/scipy/scipy/blob/14142ff70d84a6ce74044a27919c850e893648f7/scipy/optimize/optimize.py#L2900-L2906

I think that the text in Returns should be:
`Either None (for disp=True) or the text string (disp=False)`
since the message is printed if disp=True and returned if disp=False:

https://github.com/scipy/scipy/blob/14142ff70d84a6ce74044a27919c850e893648f7/scipy/optimize/optimize.py#L3034-L3038

Or am I getting something wrong?

Best regards,
Johann

**Comment by rgommers** [comment]
thanks for the report @johannfaouzi
