### ISSUE TITLE
extend stats.bartlett/levene to 2-D arrays

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#9409]
Follow-up to gh-9252, see in particular https://github.com/scipy/scipy/issues/9252#issuecomment-421125680 and https://github.com/scipy/scipy/pull/9281#issuecomment-426799477. Currently an exception is raised for >1-D input, could be extended to 2-D with axis=0.

**Comment by wattai** [comment]
I have a question to confirm your suggestion.
Did you mean of the behaviour like this?
```
X = np.random.randn(100, 2)
x0 = X[:, 0]
x1 = X[:, 1]
result_1d = bartlett(x0, x1)
result_2d = bartlett(X, axis=0)
flag = (reuslt_1d == result_2d)
```
as the result, `flag == True`.
If this behaviour is correct, I would like to contribute.

**Comment by josef-pkt** [comment]
broadcasting two arrays would be like the following, e.g. comparing two samples with a control

X = np.random.randn(100, 2)
Y = np.random.randn(100, 1)

result_1d = bartlett(X[:. 0], y.squeeze(Y))
result_2d = bartlett(X, Y, axis=0)
flag = (result_1d == result_2d[0][0])

**Comment by wattai** [comment]
I see...
You also mean like below?
```
X = np.random.randn(100, 2)
Y = np.random.randn(102, 1)
Z = np.random.randn(105, 3)

result_1d = bartlett(X[:, 0], Y.squeeze())
result_2d = bartlett(X, Y, axis=0)
flag1 = (result_1d[0] == result_2d[0, 0])

result_1d_3arrs = bartlett(X[:, 1], Y[0, :], Z[:, 2])
result_2d_3arrs = bartlett(X, Y, Z, axis=0)
flag2 = (result_1d_3arrs[0] == result_2d_3arrs[1, 0, 2])
```

**Comment by josef-pkt** [comment]
Yes, AFAICS

you can also compare with ttest_ind which should be vectorized with axis=0

```
>>> x, y = np.random.randn(100,2), np.random.randn(100)

>>> stats.ttest_ind(x, y)
Ttest_indResult(statistic=array([ 0.08451546,  0.07431104]), pvalue=array([ 0.932732  ,  0.94083791]))

>>> stats.ttest_ind(x[:, 0], y)
Ttest_indResult(statistic=0.08451546142509421, pvalue=0.93273200170921411)
>>> stats.ttest_ind(x[:, 1], y)
Ttest_indResult(statistic=0.07431103948025708, pvalue=0.94083791423681407)
```

**Comment by wattai** [comment]
Can I use `itertools`?

**Comment by wattai** [comment]
Please check above PR.

**Comment by mdhaber** [comment]
gh-14651 tracks progress toward this for all stats functions.
