### ISSUE TITLE
scipy 1.1.0 optimize.brute doesn't show progress values

### ISSUE THREAD

**Issue by tsando** [scipy/scipy#9410]
It was possible before to show the optimisation progress of `optimize.brute` by setting `disp=True` but now (scipy 1.1.0) it only outputs information at the end of the minimization -- no the progress of the algorithm or intermediate values. Is this now the default or is there a way to go back to previous behaviour? I would like to see the progress of the optimisation. Thanks.

**Comment by andyfaff** [comment]
As far as I can tell `optimize.brute` never reported the progress of the grid search. At the moment `disp=True` only displays the convergence message from the `finish` callable that is used to polish the final solution. Thus the final printed output will depend on what `finish` does with the `disp` keyword.
Is you think this is in error can you let me know the scipy version when a different behaviour was followed?

**Comment by wattai** [comment]
Aha, I forgot it.
Originally, we have no way to know the end of the optimization.
So we can not to display the progress bar or something.
I think this issue is bit strange...

**Comment by andyfaff** [comment]
It's unclear as to what kind of progress information is required here. `brute` performs a grid search, and the number of evaluation points is more or less known beforehand. Having a callback to inform how many points of the grid have been searched is less valuable for this minimiser than for a minimiser where it's not known how many iterations will be required.
`brute` never had a callback option. As for printed messages the documentation says:

> disp: bool, optional
Set to `True` to print convergence messages from the `finish` callable.

If `disp` is `True`, but `finish` is `None`, then no messages will be printed.
If you would like to see the results of the final output then a simple `print` from your code should suffice.
