### ISSUE TITLE
Callback return value erroneously ignored in minimize

### ISSUE THREAD

**Issue by bash0** [scipy/scipy#9412]
Scipy.optimize.minimize takes a **callback** function. According to the [documentation](https://docs.scipy.org/doc/scipy-1.1.0/reference/generated/scipy.optimize.minimize.html), "_If callback returns True the algorithm execution is terminated._". However, the return value of the callback function is actually ignored by all optimization routines, and the execution is not terminated upon a True return value. Implementation of this proclaimed feature would be very useful, for instance to terminate the optimization when the function value enters a certain range.

I'd like to note further, that the callback function
`callback(xk, OptimizeResult state) -> bool`
only takes the argument `state` for the ‘trust-constr’ optimization method, but this parameter would be very useful for most of the other routines as well.

### Reproducing code example:
When the callback returns True, the optimization should halt immediately. Yet in this example it iterates 79 times:
```
from scipy import optimize

def cb(x):
    return True

print optimize.minimize(optimize.rosen, x0=(0,0), method='Nelder-Mead', callback=cb)
```

### Scipy/Numpy/Python version information:
```
('0.14.0', '1.8.2', sys.version_info(major=2, minor=7, micro=9, releaselevel='final', serial=0))
```
The issue persists in version 1.1: https://github.com/scipy/scipy/blob/14142ff70d84a6ce74044a27919c850e893648f7/scipy/optimize/optimize.py#L616

**Comment by andyfaff** [comment]
The relevant documentation:

```
    callback : callable, optional
        Called after each iteration. For 'trust-constr' it is a callable with
        the signature:

            ``callback(xk, OptimizeResult state) -> bool``

        where ``xk`` is the current parameter vector. and ``state``
        is an `OptimizeResult` object, with the same fields
        as the ones from the return.  If callback returns True
        the algorithm execution is terminated.
        For all the other methods, the signature is:

            ``callback(xk)``

        where ``xk`` is the current parameter vector.
```

Only `trust-constr` terminates if the callback returns `True`, the others don't. 

I did open a PR for doing this for all methods, #4384. However, this got stalled. From that PR it seemed like the best way of terminating was for the callback to raise an Exception. The minimizer would then create an `OptimizeResult` with the results so far, the Exception would be added to the result, and the "intermediate" result returned.

**Comment by rainwoodman** [comment]
Like, raising a StopIteration?

**Comment by aaronsnoswell** [comment]
Hello! I was coming here to post an issue that Nelder-Mead doesn't respect the return value of the callback, then I found this bug and realised that the documentation says this is only for trust-constr.

+1 for the idea of adding this functionality to all optimizers, or perhaps clarifying the documentation in the interim!

**Comment by aaronsnoswell** [comment]
If someone points me to the code and wherever tests need to be added I'm happy to attempt a PR to add this functionality.
