### ISSUE TITLE
add dual_annealing to optimize benchmarks 

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#9415]
gh-9306 added `optimize.dual_annealing`, and it has a very extensive set of benchmarks (also non-SciPy algorithms) at https://github.com/sgubianpm/GOBench. The PR did not add `dual_annealing` to https://github.com/scipy/scipy/tree/master/benchmarks/benchmarks/go_benchmark_functions however, this should still be done so we have an up-to-date benchmark suite within the repo.

**Comment by sgubianpm** [comment]
@rgommers, thanks a lot for taking some time playing with GOBench, for the merging and also for this task. I will address that today.

**Comment by rgommers** [comment]
gh-9431 is merged, closing
