### ISSUE TITLE
dual_annealing off by one in the number of iterations

### ISSUE THREAD

**Issue by andyfaff** [scipy/scipy#9419]
@sgubianpm @rgommers I think the number of iterations is off by one in `dual_annealing`.
Lets say `maxiter=1`, at [L636](https://github.com/scipy/scipy/blob/master/scipy/optimize/_dual_annealing.py#L636) `maxiter` will be 1 and `iteration` will be 1, so the break will happen immediately and not one iteration will be done.

I think the fixes should be fairly straightforward, but it'll need doing before the branch. This will be a blocker.

**Comment by sgubianpm** [comment]
@andyfaff , thanks. I will adjust that in a PR and also @js850 suggestions today.

**Comment by sgubianpm** [comment]
Bug fixed in PR #9424. @andyfaff, @rgommers , could you please merge before branching?

**Comment by rgommers** [comment]
fix merged. good catch @andyfaff
