### ISSUE TITLE
Yeo-Johnson Transform formulation correct?

### ISSUE THREAD

**Issue by tmcken** [scipy/scipy#9420]
Are the two lines of the annotated code below correct? Take the first one for example. According to YJ definition, it should be lmbda !=0. As lmbda can take on both positive and negative values, lmbda<1e-19 is a very poor substitute for lmbda!=0, is it not?

Perhaps these two lines should instead read as follows?
abs(lmda)<1e-19
abs(lmda-2)<1e-19

Am I missing something?

    def _yeo_johnson_transform(self, x, lmbda):
        out = np.zeros(shape=x.shape, dtype=x.dtype)
        pos = x >= 0  # binary mask
        # when x >= 0
        if lmbda < 1e-19:  # <------- is this correct???
            out[pos] = np.log(x[pos] + 1)
        else:  # lmbda != 0
            out[pos] = (np.power(x[pos] + 1, lmbda) - 1) / lmbda
        # when x < 0
        if lmbda < 2 - 1e-19:  # <------- is this correct???
            out[~pos] = -(np.power(-x[~pos] + 1, 2 - lmbda) - 1) / (2 - lmbda)
        else:  # lmbda == 2
            out[~pos] = -np.log(-x[~pos] + 1)

_Originally posted by @tmcken in https://github.com/scipy/scipy/issue_comments#issuecomment-434552323_

**Comment by chrisb83** [comment]
This function is not yet in a release, it is under development in #9305, but the code there does have `abs(...)`

**Comment by NicolasHug** [comment]
This code is from scikit-learn, right?

Yes, I noticed a few errors I made while re-implementing yeo-johnson in scipy. I was planning to propose a fix + add some moretests in scikit learn (no problem if you want to do it) but it'd be best to wait before #9305 gets merged I think
