### ISSUE TITLE
Cannot import name 'moduleTNC' on windows with conda

### ISSUE THREAD

**Issue by slamer59** [scipy/scipy#9425]
Hello, 
I open another issue on this subject https://github.com/scipy/scipy/issues/6188

I use scipy on windows machine, python2.7 and conda installed it like: https://github.com/scipy/scipy/issues/6188#issuecomment-221669131

This doesnot solve the issue.

I rename **moduletnc.pyd** to **moduleTNC.pyd** and it works like https://github.com/scipy/scipy/issues/6188#issuecomment-338697754

I look at tarballs and seems OK. 

It might be a conda problem.

**Comment by ilayn** [comment]
Hi @slamer59. Thanks for reporting This is already mentioned in the linked issue and in the SO question. This looks like a conda issue so you might want to take is to them. We can't do anything about this.
