### ISSUE TITLE
gaussian_kde not working with numpy matrix

### ISSUE THREAD

**Issue by AsafBanana** [scipy/scipy#9429]
It seems gaussian_kde doesn't work with numpy matrix but only failes when you try to use evalute.

I think it should either work with np.matrix or refuse to accept it when fitting. It took me forever to understand whats wrong :(

### Reproducing code example:

```
from scipy import stats

def measure(n):

    "Measurement model, return two coupled measurements."
    m1 = np.random.normal(size=n)
    m2 = np.random.normal(scale=0.5, size=n)
    return m1+m2, m1-m2

m1, m2 = measure(2000)
xmin = m1.min()
xmax = m1.max()
ymin = m2.min()
ymax = m2.max()

X, Y = np.mgrid[xmin:xmax:100j, ymin:ymax:100j]
positions = np.vstack([X.ravel(), Y.ravel()])
values = np.vstack([m1, m2])
kernel = stats.gaussian_kde(np.matrix(values))
kernel.evaluate(np.matrix(values))

```

### Error message:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 20, in <module>
  File "/usr/local/lib/python3.5/dist-packages/scipy/stats/kde.py", line 214, in evaluate
    energy = sum(diff*tdiff,axis=0) / 2.0
  File "/home/asaf/.local/lib/python3.5/site-packages/numpy/matrixlib/defmatrix.py", line 215, in __mul__
    return N.dot(self, asmatrix(other))
ValueError: shapes (2,2000) and (2,2000) not aligned: 2000 (dim 1) != 2 (dim 0)
```

**Comment by rgommers** [comment]
Not really a bug because the docs say "array". However easy to make more user-friendly by adding `asarray` to ``__init__` and `evaluate` methods. Now it uses `atleast_2d`, which is needed as well but doesn't convert `matrix` input to `ndarray`.

**Comment by cldssty** [comment]
Hi, can I work on this?

**Comment by rgommers** [comment]
hi @cldssty, sure. 

I would suggest to not add a test (unusual, I know). We don't want to introduce new `np.matrix` usage in tests. And otherwise you'd have to introduce some wrappers like [sparse.sputils.matrix](https://github.com/scipy/scipy/blob/master/scipy/sparse/sputils.py#L345)

just a minimal patch that makes the example in this issue test is fine I think
