### ISSUE TITLE
Equation written incorrectly in scipy.stats.pearsonr documentation

### ISSUE THREAD

**Issue by lgloege** [scipy/scipy#9432]
This is a very minor issue, but I just wanted to bring it to your attention. 

The equation in scipy.stats.pearsonr is written incorrectly in the [documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html) 

The summation needs to be in front of both terms in the denominator:
\sqrt{ \sum (x-m_x)^2 \sum (y-m_y)^2 }

This is a minor issue, as the correct equation is coded.

**Comment by ilayn** [comment]
@lgloege Thanks for reporting. Do you mind sending in a pull request for this?

**Comment by chrisb83** [comment]
this has been fixed in #9143 already.

**Comment by chrisb83** [comment]
(not yet released)
