### ISSUE TITLE
Add shgo to optimize benchmarks

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#9451]
In gh-8098 we added `optimize.shgo` as a new optimizer. There are a lot of benchmark results linked in the description of gh-8098, but we still need to add `shgo` to the SciPy benchmark suite. Should be straightforward, similar to gh-9431

**Comment by andyfaff** [comment]
The `shgo` minimisation is deterministic, so for a fixed set of bounds and the same kwds, then you're only ever going to get the same answer. This means it doesn't make sense to run more than 1 iteration.
If there was a way to change `best_x` or `best_fun` by a transform (the former is probably what would be required), then it may make sense to have more than 1 iteration.

**Comment by mdhaber** [comment]
It looks like this was added in gh-16357. Thanks @dschmitz89!
