### ISSUE TITLE
AIX build - ld issue in 64 bit mode

### ISSUE THREAD

**Issue by TeejIBM** [scipy/scipy#9452]
We are using SciPy 1.1.0 main branch source code release on AIX 7.1 using AIX Toolkit packages for GCC and related packages - (https://www.ibm.com/developerworks/aix/library/aix-toolbox/alpha.html).

We have to use the AIX's linker (ld) as GCC's linker is not compatible with AIX at this time.  There is a limitation with AIX linker that causes an issue with the build when compiling in 64 bit mode (using Python_64 2.7.15, and -maix64 flags).

The settings I provided are:

```
# export CC='gcc -lpthread -lm -lgcc -lgomp -lgfortran -maix64'
# export LDFLAGS='-lpthread -lm -lgcc -lgomp -lgfortran -maix64'
# export PATH=/opt/freeware/bin:$PATH
```

Once I run `python_64 setup.py install`, it would throw the following error message:

```
ld: 0706-012 The -p flag is not recognized.
ld: 0706-012 The -a flag is not recognized.
ld: 0706-012 The -t flag is not recognized.
ld: 0706-012 The -h flag is not recognized.
ld: 0706-012 The -= flag is not recognized.
ld: 0706-012 The -/ flag is not recognized.
collect2: error: ld returned 255 exit status
```

This is because within this command:  `/opt/freeware/lib64/python2.7/config/ld_so_aix /opt/freeware/bin/gfortran -Wall -maix64 -g -bI:/opt/freeware/lib64/python2.7/config/python.exp -lpthread -lm -lgcc -lgomp -lgfortran -maix64 build/temp.aix-7.1-2.7/scipy/integrate/_quadpackmodule.o -L/opt/OpenBLAS/lib -L/opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/6.3.0/ppc64 -L/opt/freeware/lib64 -Lbuild/temp.aix-7.1-2.7 -Wl,-rpath="/opt/OpenBLAS/lib" -lquadpack -lmach -lopenblas -lopenblas -lgfortran -o build/lib.aix-7.1-2.7/scipy/integrate/_quadpack.so`, the specific flag - `-Wl,-rpath="/opt/OpenBLAS/lib"` is not valid for AIX's `ld_so_aix` program.

I needed to include all the library flags in order for the linker to recognize the libraries for OpenBLAS among other packages.

Please let me know if you need the full run log.

I will continue to investigate on how we can eliminate this particular flag without breaking anything else.

Special thanks to the AIX Toolkit's team to help narrow this down a bit - https://www.ibm.com/developerworks/community/forums/html/topic?id=28814b7c-93a3-4cd3-9f42-94f36620013f#547a941b-11c6-4f5b-aa6c-b8208b7b86bb

Update:  Added LDFLAGS as I forgot to include that -- required for AIX to recognize gomp and other packages when linking.

**Comment by TeejIBM** [comment]
To clarify, the following command:

```
/opt/freeware/lib64/python2.7/config/ld_so_aix /opt/freeware/bin/gfortran -Wall -maix64 -g -bI:/opt/freeware/lib64/python2.7/config/python.exp -lpthread -lm -lgcc -lgomp -lgfortran -maix64 build/temp.aix-7.1-2.7/scipy/integrate/_quadpackmodule.o -L/opt/OpenBLAS/lib -L/opt/freeware/lib/gcc/powerpc-ibm-aix7.1.0.0/6.3.0/ppc64 -L/opt/freeware/lib64 -Lbuild/temp.aix-7.1-2.7 -lquadpack -lmach -lopenblas -lopenblas -lgfortran -o build/lib.aix-7.1-2.7/scipy/integrate/_quadpack.so
```

Returns:

```
ld: 0711-224 WARNING: Duplicate symbol: __itab
ld: 0711-224 WARNING: Duplicate symbol: __tab
ld: 0711-224 WARNING: Duplicate symbol: guesses
ld: 0711-224 WARNING: Duplicate symbol: tantab
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
ld: 0711-224 WARNING: Duplicate symbol: __itab
ld: 0711-224 WARNING: Duplicate symbol: __tab
ld: 0711-224 WARNING: Duplicate symbol: guesses
ld: 0711-224 WARNING: Duplicate symbol: tantab
ld: 0711-224 WARNING: Duplicate symbol: global destructors keyed to 65535_0___dso_handle
ld: 0711-224 WARNING: Duplicate symbol: .global destructors keyed to 65535_0___dso_handle
ld: 0711-224 WARNING: Duplicate symbol: __dso_handle
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
```

So it's definite that `-Wl,-rpath="/opt/OpenBLAS/lib"` is the issue.

**Comment by TeejIBM** [comment]
I think I found the core functionality that caused this, and I made the following change:

/opt/freeware/lib64/python2.7/distutils/ccompiler.py:1071-1077
```
    """for dir in runtime_library_dirs:
        opt = compiler.runtime_library_dir_option(dir)
        if isinstance(opt, list):
            lib_opts.extend(opt)
        else:
            lib_opts.append(opt)
    """
```

The reason I chose this - I did not want this to call Numpy's fcompiler function `runtime_library_dir_option()` which explicitly does this:

```    
def runtime_library_dir_option(self, dir):
        sep = ',' if sys.platform == 'darwin' else '='
        return '-Wl,-rpath%s"%s"' % (sep, dir)
```

Which is explicitly not supported on AIX, according to @ayappanec 

The installation succeeded with that change, along with the other changes I made (i.e. `scipy/special/cephes/dd_real.h:108` in defect and the settings I have chosen.  I will try again tomorrow with a clean installation on a different platform to confirm that I covered all of the required changes.

Please help me better improve this particular issue.  What is the best way to modify NumPy to get this to properly evaluate the AIX platform so that SciPy works properly?

Thank you.

**Comment by rgommers** [comment]
So `rpath` isn't supprted at all? If we'd change that NumPy bit of code from `if sys.platform == 'darwin'` to include AIX, that would solve it? If so, what does `sys.platform` give on AIX?

**Comment by ayappanec** [comment]
Yes. AIX ld won't support "rpath". sys.platform gives "aix6" in AIX 6.1 . Traditionally, sys.platform[:3] == "aix" is used check for AIX.

**Comment by rgommers** [comment]
I've made a PR to update `numpy.distutils` at https://github.com/numpy/numpy/pull/12363. If you could confirm that that fixes things for you, that would be much appreciated.

**Comment by rgommers** [comment]
Closing this now, because it's anyway a numpy rather than a scipy issue.

**Comment by charris** [comment]
OK, waiting on confirmation to merge https://github.com/numpy/numpy/pull/12363. I might merge it even if it doesn't completely fix the current problem because it looks like the right thing to do.

**Comment by TeejIBM** [comment]
Okay, this does not address the issue with SciPy.  It does throw an error, but that is not the goal of this -- the goal is to bypass this function entirely when compiling in 64 bit mode for AIX.

**Comment by rgommers** [comment]
Hmm. It should be catching that, we have the exact same construct in several places. Just to make sure: you don't have a `site.cfg` file in your build dir, or a `~/.numpy-site.cfg`? That would explain why this is triggered; if not I have to debug in more detail.

**Comment by rgommers** [comment]
Okay, I now have access to AIX 7.1 and 7.2 systems, and perhaps some time to improve the situation here. Config of the systems is as follows:

AIX 7.2:
```
$ xlc -qversion
IBM XL C/C++ for AIX, V13.1.3 (5725-C72, 5765-J07)
Version: 13.01.0003.0004

$ gcc --version
gcc (GCC) 7.2.0

$ python -c "import sys; print(sys.version)"
2.7.11 (default, Jul 28 2016, 16:59:15) [C]

$ python3 -c "import sys; print(sys.version)"
3.5.1 (default, Aug 11 2016, 16:16:52) [C]


$ python_64 -c "import sys; print(sys.version)"
2.7.11 (default, Jul 28 2016, 16:45:41) [C]

$ python3_64 -c "import sys; print(sys.version)"
3.5.1 (default, Aug 11 2016, 16:14:23) [C]

$ ldd python
python needs:
         /opt/freeware/lib/libpython2.7.so
         /usr/lib/libC.a(shr.o)
         /usr/lib/libC.a(ansi_32.o)
         /usr/lib/libpthreads.a(shr_xpg5.o)
         /usr/lib/threads/libc.a(shr.o)
         /usr/lib/librtl.a(shr.o)
         /usr/lib/libpthreads.a(shr_comm.o)
         /usr/lib/libC.a(shrcore.o)
         /usr/lib/libC.a(ansicore_32.o)
         /unix
         /usr/lib/libcrypt.a(shr.o)
```

AIX 7.1:

```
$ xlc -qversion
IBM XL C/C++ for AIX, V12.1 (5765-J02, 5725-C72)
Version: 12.01.0000.0000

$ gcc --version
gcc (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ which gcc
/opt/freeware/bin/gcc

$ python -c "import sys; print(sys.version)"
2.7.5 (default, Jun 15 2013, 04:47:21)

$ python_64 -c "import sys; print(sys.version)"
2.6.7 (r267:88850, Nov 22 2011, 20:53:54) [C]

$ python3
ksh: python3:  not found.

$ ldd $(which python)
/opt/freeware/bin/python needs:
         /usr/lib/libc.a(shr.o)
         /usr/lib/libpthreads.a(shr_xpg5.o)
         /usr/lib/libpthreads.a(shr_comm.o)
         /usr/lib/libdl.a(shr.o)
         /unix
         /usr/lib/libcrypt.a(shr.o)
```

The 7.1-installed Pythons are too old, so I definitely won't bother with those. Let's start with 7.2. @TeejIBM and @ayappanec can you indicate from an AIX user perspective what the most relevant Python installs are? The default Pythons are all built with xlC, but you seem to prefer GCC. So do you build Python itself from source, or do you get it from somewhere? Is the xlC-built Python also of interest still?

Also, if there are standard package repos or build recipes that scientific users on AIX use, please point me towards those.

**Comment by ayappanec** [comment]
@rgommers I am from AIX Toolbox development team. We have a good amount of Opensource packages ported to AIX (in rpm format) at AIX Toolbox site --> https://www.ibm.com/developerworks/aix/library/aix-toolbox/alpha.html
In the URL link above, it has a small tip about how to setup the yum repo. Basically you need to run the yum.sh script which will install the latest rpm.rte fileset , yum and it's dependencies. Once that is done, you can do yum update to keep all the packages to current level. 
And one more thing, only openssl comes from a different site (AIX web download pack programs) --> https://www-01.ibm.com/marketing/iwm/iwm/web/dispatcher.do?source=aixbp and in a different format ( rte fileset).  One has to install the latest openssl available from here before installing python 2.7.15 & python 3.7.1 through yum. 
Since openssl comes in as a rte fileset, one has to run this custom made script in AIX "updtvpkg" to update the rpm database about the libraries it provides. Need to do this before installing python.

**Comment by ayappanec** [comment]
Useful links
https://developer.ibm.com/articles/configure-yum-on-aix/
ftp://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/                --> ftp URL to rpm packages

Note: Most of the packages we build only in AIX 6.1. And that will work in AIX 7.1 & 7.2 as well.
Some packages like gcc, g++ compilers are very OS specific so we build them separately in each AIX version (6.1, 7.1, 7.2)

**Comment by rgommers** [comment]
Thanks @ayappanec, that is very helpful. It looks like https://www.ibm.com/developerworks/aix/library/aix-toolbox/alpha.html has Python and Python development headers, and no scientific packages. So I will build Cython, NumPy and SciPy against that Python.
