### ISSUE TITLE
TST: test_eigs_consistency() doesn't have consistent results

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#9453]
` test_eigs_consistency` added in #9352 is stochastically failing on Windows / Appveyor for some Python versions -- see i.e., https://ci.appveyor.com/project/scipy/scipy/builds/20106920

I keep seeing `array([4.+0.j, 5.+0.j])` compared with `array([5., 4.])`. Is it something related to complex numbers, and only happening on Windows / subset of Python versions? Are we even expecting complex numbers here?

Pinning the random seed in #9449 didn't seem to alleviate the issue.

cc @rc & @lobpcg

**Comment by tylerjereddy** [comment]
Closing for now, maybe this is ok after all -- the Appveyor result shows the seed Ralf added but I don't see his commit in my rebase so I'll reopen after if it persists. Not sure how that happens though.

**Comment by lobpcg** [comment]
> I keep seeing `array([4.+0.j, 5.+0.j])` compared with `array([5., 4.])`. Is it something related to complex numbers, and only happening on Windows / subset of Python versions? Are we even expecting complex numbers here?

 `array([4.+0.j, 5.+0.j])` is mathematically the same as `array([5., 4.])` 
I suppose that this array represents eigenvalues. Eigenvalues can in general be complex. lobpcg does support complex matrices, so it can in principle output complex eigenvalues, with small or zero imaginary parts. The output format may indeed change between different revisions. 

The simple fix may be to allow both `array([4.+0.j, 5.+0.j])` and `array([5., 4.]) as valid answers.

**Comment by ilayn** [comment]
20 and 100 are a bit too small for testing a function on sparse library for my taste but I'll let others decide on this.

**Comment by rc** [comment]
This should not happen - I would suspect eigh(), that is used internally in lobpcg(), returns complex instead of real results. A quick fix would be to retype its returns. Maybe there is an old scipy version?

**Comment by ilayn** [comment]
I haven't check but I think sym/her eigensolvers always return floats as eigenvalues since realness guaranteed mathematically.

**Comment by ilayn** [comment]
Now I've looked at it, and the problem is that the order is reversed. Otherwise complex and real arrays are taken as the same. That is 
```python
assert_allclose(np.array([4.+0.j, 5.+0.j]), np.array([4., 5.]))
```
passes the condition. So probably sorting can guarantee the pass.

**Comment by tylerjereddy** [comment]
Interesting, and it is not just Windows anymore as I observe the failure on linux too now after rebasing on latest master in #7827.

**Comment by rc** [comment]
@rgommers, @tylerjereddy: In #9352 I have introduced the test to specifically test the correct ordering, compatible with the ARPACK-based eigs() - the #9352 already introduced code to do that sorting inside lobpcg() (see _get_indx() and explicitly reversing the order for largest=True in lobpcg()), and the tests did not fail at the time of merging. So I wonder what changed

- does eigs() now returns the eigenvalues in a different order with default options?
- the returned eigenvalues should have a real dtype - why they have the complex dtype now?

**Comment by lobpcg** [comment]
In #7827, which introduced this problem, @perimosocordiae comments: "This PR doesn't have special handling for symmetric sparse matrices, because in general we don't do any special handling for symmetry."

I am now wondering if  #7827 in some cases breaks the symmetry of the sparse matrix. E.g., swapping two matrix rows could break the matrix symmetry, but would not change the eigenvalues (only the eigenvectors). Since the matrix is now non-symmetric, the ARPACK-based eigs() should use a different algorithm that produces complex eigenvalues and their default order should probably also change, as observed in these tests. 

If true, this could be a serious issue in #7827. To debug, just dump one of the matrices that causes the check to fail and see if it is symmetric. May be attach the matrix here for everybody to look at.

**Comment by ilayn** [comment]
The symmetric matrix 
```
[[1, 0, 1],
 [0, 1, 0],
 [1, 0, 1]]
```
and the row swapped version
```
[[0, 1, 0],
 [1, 0, 1],
 [1, 0, 1]]
```
have significantly different eigenvalues if that's what you mean.

**Comment by lobpcg** [comment]
> have significantly different eigenvalues if that's what you mean.

Great point, sorry! My claim was wrong even for 2x2 diagonal matrices... True for 1x1 :-) 

I have edited my original comment.

**Comment by tylerjereddy** [comment]
> In #7827, which introduced this problem,

How is #7827 causing issues in master branch if it is not merged?

**Comment by tylerjereddy** [comment]
The debug strategy here is probably to roll back to the commit where the `lobpcg` changes / additional tests were introduced, run the problematic test 500-1000 times to confirm the issue really didn't exist at the time of merge, and if it didn't then do a `git bisect` analysis to identify the first problematic commit & go from there.

**Comment by tylerjereddy** [comment]
I guess I'll try to do this now

**Comment by tylerjereddy** [comment]
Those failures showed up on master though, so probably the observation in #7827 is related to merging into a broken master (merge commit tests) rather than breaking master as a result of merging.

**Comment by lobpcg** [comment]
Whether or not #7827 is related, the failures are apparently due to the changed, for no known reason,  behavior of ARPACK eigs, according to @rc .
