### ISSUE TITLE
scipy.sparse.linalg.eigsh requires at least 20 iterations to converge no matter what

### ISSUE THREAD

**Issue by aki-nishimura** [scipy/scipy#9470]
scipy.sparse.linalg.eigsh requires 20 iterations to find the largest eigenvalue even if I give the exact top eigenvector as the initial vector (the code below).

This is an issue for me because every matrix-vector operation counts in my problem. A bit more context on why I noticed this issue: 

I have an application in which 1) I need to repeatedly find the largest eigenvalue of a positive definite matrix, 2) I have a very good estimate of the top eigenvector every time, and 3) I only need relatively low accuracy e.g. 10% relative error. I was confident that the Lanczos / Arnoldi iterations should converge very quickly, say in less than 10 iterations or so, but I noticed that every time it always takes exactly 20 iterations.

### Reproducing code example:

<img width="740" alt="screen shot 2018-11-12 at 7 23 22 pm" src="https://user-images.githubusercontent.com/12732968/48389589-06a7e100-e6b3-11e8-9631-2d866a9d7591.png">

```
import numpy as np
import scipy as sp
import scipy.sparse
import scipy.sparse.linalg

size = 10 ** 4
D = np.ones(size)

info = {'n_iter': 0}
def matvec(v):
    info['n_iter'] += 1
    return D * v

linear_op = sp.sparse.linalg.LinearOperator((size, size), matvec=matvec)

info['n_iter'] = 0
v0 = np.random.randn(size)
eigval, eigvec = sp.sparse.linalg.eigsh(linear_op, k=1, v0=v0)
print("{:d} iterations until convergence.".format(info['n_iter']))

info['n_iter'] = 0
v0 = np.zeros(size)
v0[0] = 1
eigval, eigvec = sp.sparse.linalg.eigsh(linear_op, k=1, v0=v0)
print("{:d} iterations until convergence.".format(info['n_iter']))
```

### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.15.4 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```

**Comment by ewmoore** [comment]
Try setting the `ncv` parameter to something smaller than 20.  The default is `min(n, max(2*k + 1, 20))` which for your example comes out as 20.

**Comment by aki-nishimura** [comment]
Ah, I missed the `ncv` parameter. Thanks! Yes, changing `ncv` does make convergence possible with fewer iterations.

**Comment by JanElias3141** [comment]
What if I need to compute more eigenvalues. Let's say I already have 5 but need another 5. The documentation always speaks only about v0 as a vector of length size. But now I need to pass 10 such vectors. First five are already known, the second five are to be determined. But I cannot feed five known vectors to v0, only 1 of them.

**Comment by lucascolley** [comment]
you may be best off opening a new issue @JanElias3141

**Comment by ilayn** [comment]
Also `eigsh` currently does not support "warm start" hence the only way is to do everything for 10 from scratch.

**Comment by JanElias3141** [comment]
That is a real shame. I thought the initial vector is included specifically because of this functionality. As I understand it, users can now guess only one vector, not more. Is there any plan to extend it? I might be ignorant but is seems to me as a straightforward option with not much work and potentially extremely useful application. As I see it, users typically do not know how many eigenvalues they need. So they compute some, check quality of the approximation of the linear system, and possibly compute more. 
I am really glad scipy has this function and will use it anyway.

**Comment by ilayn** [comment]
Initial vector is to start the process better, not to get things take off where its left off internally. But at least it can make the convergence much faster so not everything is lost.

**Comment by ilayn** [comment]
We are in the process of rewriting ARPACK but what you ask is to provide exceeding amount of information to resume the process. It is far from straightforward unfortunately from today's point of view, maybe we would find a way at the end

**Comment by JanElias3141** [comment]
Thank you for your explanation. Good luck with rewriting the code. You are providing an excellent service to the community.
