### ISSUE TITLE
TST: Azure CI for Windows testing

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#9471]
Since our Appveyor runs are rather slow I've been working on getting Azure CI working for SciPy Windows testing.

To reduce noise / CI burden I've been doing this in a [PR in my fork](https://github.com/tylerjereddy/scipy/pull/20), where you can see the current diff & Azure CI results.

I've struggled for several hours trying to get openblas to work properly--I note that [our instructions for installing openblas](https://scipy.github.io/devdocs/building/windows.html#installing-openblas) point to a `FOUND` output with `language = c`, while `language = f77` in current appveyor builds, but I see `c` in my current build attempts on Azure (and the library name gets duplicated in the list on Azure too).

There are also apparent differences in the files / static libraries used for our master branch appveyor runs vs. macpython wheel building on appveyor & I've tried copying the static libraries from both URLs without full success yet.

The other question is whether the pre-installed mingw / gfortran on the Azure images is compatible with this "just copy the static library(ies)" from openblas workflow.

The Appveyor file suggests that we should `install OpenBLAS.dll to MINGW\bin`, but actually doesn't appear to do this in our master branch CI.

I'm also not entirely clear on why we need to replace NumPy distutils in our builds using the master branch--is this still true / helpful? Presumably the changes to distutils will eventually show up in a release and we can remove that stuff?

**Comment by tylerjereddy** [comment]
ping @matthew-brett for suggestions maybe

**Comment by tylerjereddy** [comment]
Maybe an explicit `-L/directory/of/the/library` could be fed to `gfortran`, although I don't think we've normally had to do that

**Comment by tylerjereddy** [comment]
As discussed in the NumPy call today it may also be useful to have Matthew's compilation workflow for openblas documented somehow so we can move forward with openblas-related issues more easily.

**Comment by matthew-brett** [comment]
Hi Tyler - did y'all find : https://github.com/MacPython/openblas-libs ?

**Comment by tylerjereddy** [comment]
A persistent problem that I can reproduce locally for Windows source builds after openblas is detected by distutils is this mingw gfortran (linking?) issue:

`C:\Users\treddy\windows_dev_work\github_projects\scipy/scipy/integrate/quadpack/dqc25f.f:293: undefined reference to 'dgtsv_'`

[There's a line](https://github.com/scipy/scipy/blob/master/appveyor.yml#L104) in our master branch appveyor config that suggest that the opeblas dll may simply be copied into the mingw gfortran `bin` path, but this seems to have no effect for me (same for copying various lib/ and include/ files over to corresponding mingw paths). I've even tried messing around with the gcc and gfortran `specs` for lib path searching.
