### ISSUE TITLE
Is the permutation test removed?

### ISSUE THREAD

**Issue by pimmen** [scipy/scipy#9474]
I was looking for ways to do [permutation tests](https://en.wikipedia.org/wiki/Resampling_(statistics)#Permutation_tests) in scipy and found that the issue had already been raised, and that [this post](https://github.com/scipy/scipy/issues/4399#issuecomment-230980049) claimed it was resolved but when I look at [the docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html) and the [source code](https://github.com/scipy/scipy/blob/v1.1.0/scipy/stats/stats.py#L3970-L4092) the `permutations` parameter seems to have been removed. Has the feature been moved somewhere else or removed? I can't seem to find it. I hope it's not me searching poorly.

**Comment by pv** [comment]
The work was *started* in the PR the comment you link to points to, but it appears to not have ever been finished. That's why #4440 is still open.

**Comment by mdhaber** [comment]
@pimmen In case you're still interested, a `permutation_test` function will be available in SciPy 1.8.0, which should release in the next month or so. See gh-13899.
