### ISSUE TITLE
scipy.signal.firwin2 documentation (non-linear phase filters)

### ISSUE THREAD

**Issue by katrinamo** [scipy/scipy#9475]
Hello, my name is Katie and I'm somewhat of a newbie to scipy. I noticed that the documentation for scipy.signal.firwin2 states that it can only create filters "with linear phase". However, I have been using it for non-linear phase filter design as an alternative to Matlab's fir2. Not sure if this is intended behavior, but if so it would be awesome if the documentation was updated (it would also settle some arguments I have at work). Thanks!

### Reproducing code example:

```
import numpy as np
import scipy.signal as signal
import matplotlib.pyplot as plt

x = np.linspace(0,10,1024)

# non linear phase        
phase = x ** 2

# unity gain
gain = np.ones(1024)

# gain and phase to IQ (put phase in radians)
iq = 10 ** (gain / 20) * np.exp(1j * phase * np.pi / 180 )

plt.plot(x, np.unwrap(np.angle(iq)) * 180 / np.pi)
plt.show()

# normalize frequencies
freq = (x - x[0]) / np.max(x - x[0])

# generate coefficients
coefs = signal.firwin2(21, freq, iq, 1024)

# plot freq response
w, h = signal.freqz(coefs)
plt.plot(np.unwrap(np.angle(h)) * 180 / np.pi)
plt.show()

```

### Error message:

N/A

### Scipy/Numpy/Python version information:

```
1.1.0 1.14.3 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```

**Comment by larsoner** [comment]
Running your code I get:

![figure_1](https://user-images.githubusercontent.com/2365790/48581190-190e5e80-e8ef-11e8-9e7d-60e582201efd.png)

The orange is the second plot, which is of the unwrapped phase. That looks linear to me?

And modifying the plotting code a bit to respect the effective sampling rate:
```
w, h = signal.freqz(coefs, worN=x, fs=1. / (x[1] - x[0]))
fig, ax = plt.subplots(2)
ax[0].plot(x, np.unwrap(np.angle(iq)) * 180 / np.pi, color='b')
ax[0].plot(w, np.unwrap(np.angle(h)) * 180 / np.pi, color='orange')
ax[1].plot(coefs, color='orange')
```
You can see that the intended/design phase (blue) is not preserved, and becomes linear (orange).

![figure_2](https://user-images.githubusercontent.com/2365790/48581698-81aa0b00-e8f0-11e8-8962-9b949acdcc4b.png)

**Comment by katrinamo** [comment]
The updated code below may shed some more light on how I am seeing non linearity. I subtract the response of an allpass filter from that of the coefficients. 

```import numpy as np
import scipy.signal as signal
import matplotlib.pyplot as plt

x = np.linspace(0,10,1024)

# non linear phase        
phase = x ** 2

# unity gain
gain = np.ones(1024)

# gain and phase to IQ (put phase in radians)
iq = 10 ** (gain / 20) * np.exp(1j * phase * np.pi / 180 )

plt.plot(x, np.unwrap(np.angle(iq)) * 180 / np.pi)
plt.show()

# normalize frequencies
freq = (x - x[0]) / np.max(x - x[0])

# generate coefficients (21 for type I)
coefs = signal.firwin2(21, freq, iq, 1024)

# plot freq response
w, h = signal.freqz(coefs)
fig,ax = plt.subplots(3)

# Plot the iq/coef phase
ax[0].plot(x, np.unwrap(np.angle(iq)) * 180/np.pi, color='orange')
ax[0].plot(w, np.unwrap(np.angle(h)) * 180/np.pi) 

# Subtract the allpass filter phase response from the coefficients' response
w1, h1 =signal.freqz([ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
diff = np.unwrap(np.angle(h))*180/np.pi - np.unwrap(np.angle(h1))*180/np.pi

# plot the resulting difference which is piecewise linear...
ax[1].plot(diff)
ax[1].set_title('Allpass - Coefs')

# plot the phase of the filter
ax[2].plot(np.unwrap(np.angle(h1))*180/np.pi)
ax[2].set_title('Allpass Phase')

plt.tight_layout()

plt.show()
```

![figure_1](https://user-images.githubusercontent.com/9113510/48584379-94740e00-e8f7-11e8-81e5-084110a98b60.png)

However, upon further inspection is seems the result is _piece-wise_ linear. This may make my issue irrelevant.

**Comment by katrinamo** [comment]
please note that the middle graph above should be titled Coefs - Allpass, I got the title backwards.

**Comment by katrinamo** [comment]
Just pinging again to see if anyone on thread thinks this is worth a PR. I will make one if so! :)

**Comment by larsoner** [comment]
I'm still not sure this shows that the `firwin2` result is not linear phase. Let's start with a simpler script. It seems to show linearity:
```
import numpy as np
import scipy.signal as signal
import matplotlib.pyplot as plt

x = np.linspace(0,10,1024)
phase = x ** 2
gain = np.ones(1024)
iq = 10 ** (gain / 20) * np.exp(1j * phase * np.pi / 180 )
freq = (x - x[0]) / np.max(x - x[0])
coefs = signal.firwin2(21, freq, iq, 1024)
w, h = signal.freqz(coefs)
fig, ax = plt.subplots(1)
ax.plot(w, np.unwrap(np.angle(h)) * 180/np.pi)
```

![screenshot from 2019-01-10 09-21-43](https://user-images.githubusercontent.com/2365790/50974455-445d9600-14b9-11e9-89a5-2fb99d49a125.png)

So perhaps something in your script is mis-representing the filter?

**Comment by katrinamo** [comment]
Here is an example that I believe is convincing. Using a similarly simple example, we create a non-linear phase signal and its inverse. Then, using firwin2, we generate the coefficients for the inverse signal. 

If firwin2 is truly capable of non-linear phase filters, applying the inverse filter to the original signal should result in a linear phase response (in this example ideally at zero degrees). Otherwise, we should just see some weird output as the result of the linear phase being applied to the sine wave phase.
 
```python
import numpy as np
import scipy.signal as signal
import matplotlib.pyplot as plt

x = np.linspace(0, 10, 1024)
phase = np.sin(x)
gain = np.ones(1024)
iq = 10**(gain / 20) * np.exp(1j * phase * np.pi / 180)
freq = (x - x[0]) / np.max(x - x[0])

# generate the coefficients for plotting
coefs = signal.firwin2(21, freq, iq, 1024) 

# create the inverse signal and coefficients
inverse_iq = 1/iq
inverse_coefs = signal.firwin2(21, freq, inverse_iq)

# filter the original signal with the inverse coefficients
filtered = signal.lfilter(inverse_coefs, 1.0, iq)

# use freqz for plotting frequency response
w_ic,h_ic = signal.freqz(inverse_coefs)

# Plot all the things
fig, ax = plt.subplots(3)

ax[0].set_title("Original Signal")
ax[0].plot(x, phase)
ax[0].plot(x, gain)

ax[1].set_title("Inverse Signal")
ax[1].plot(w_ic/(2*np.pi) * 2 * 10, (np.unwrap(np.angle(h_ic))) * 180/np.pi)
ax[1].plot(w_ic/(2*np.pi) * 2 * 10, 20*np.log10(h_ic))

ax[2].set_title("Filtered")
ax[2].plot(np.unwrap(np.angle(filtered)) * 180/np.pi)
ax[2].plot(20*np.log10(filtered))

plt.tight_layout()
plt.show()
```

![image](https://user-images.githubusercontent.com/9113510/51194408-ff6ea080-18b8-11e9-87b0-26c575d0e5e9.png)

As you can see above, the result is a flat phase response. Therefore, unless I am missing something, the coefficients generated by firwin2 _must_ have non-linear phase. Though why the phase isn't centered at zero degrees I do not know.

The inverse signal _appears_ to be linear, but if you were to subtract the phase response of a 21 tap allpass filter with a 1 in the middle position, such as in my first code example on this thread, you would see the inverse sine wave.

**Comment by larsoner** [comment]
You agree that in the second subplot that the phase of the filter is linear, right? If so, this is a hint that something else is probably wrong elsewhere.

In this case, it looks like there is some confusion over frequency and time domain. Your `inverse_coefs` are a time-domain signal. You convolve these with `iq`, which is a frequency-domain signal. You also in plot (3) show the phase (and amplitude) of `filtered`, which is (I think?) meant to be a time-domain signal, rather than the result of `freqz(filtered)`, i.e., the frequency-domain signal. (You probably also want to plot the magnitude using `np.log10(np.abs(...))` rather than `np.log10(...)`, but this is not the problem with the phase calculations.)

**Comment by katrinamo** [comment]
Hm... yeah, you are totally right on my confusion with the filtered signal. I mean for it to be a time-domain signal but I see now that it isn't.

I need to think on this some more, because this _appears_ to be working on the FPGA based DSP system I use at work. This might take me a while to figure out though (if it's even doing filter correctly, which now I have some doubts)...

Should I keep this issue open or is it better to just close and reopen if I find something? Thank you for your help :)

**Comment by larsoner** [comment]
I'll close for now since I think there is no SciPy bug (the firwin2 outputs are linear phase). For further clarification you might want to lean on https://dsp.stackexchange.com/ for expertise
