### ISSUE TITLE
Invalid index in signal.medfilt2d's QUICK_SELECT

### ISSUE THREAD

**Issue by J3ronimo** [scipy/scipy#9476]
Hi guys,

I was fiddling around with scipy's 2D median filter in order to maybe find a way to make it run a little faster. Finally I re-translated the C code found [here](https://github.com/scipy/scipy/blob/master/scipy/signal/medianfilter.c) to Python to see if I could maybe put that into numba / LLVM.

The Python code didn't run though, giving me an index error inside the QUICK_SELECT function, and it turned out that this must be same in C, only that the here the index error passes silently after reading some more data outside of the actual array.

Inside QUICK_SELECT, you'll find:

```                      
        /* Nibble from each end towards middle, swapping misordered items */ \
        piv = arr[lo];                                                  \
        for (ll = lo+1, hh = hi;; ll++, hh--) {                         \
	    while (arr[ll] < piv) ll++;					\
	    while (arr[hh] > piv) hh--;					\
	    if (hh < ll) break;						\
	    ELEM_SWAP(TYPE, arr, ll, hh);				\
        }     
```

If now hh == ll, the loop won't break, which in my case happened while both hh and ll were at the last index of the array. You can reproduce with any input like `arr = [X, 0, 0, ..., 0, 0, X]`, or basically anything else were the maximum value of the array is present exactly twice at the left and the right end of the array.

In the result, another run of `ll++` and `hh--` happens, effectively starting with `ll` outside of the array, incrementing it until whatever found there is bigger than `piv`.

As a fix in my Python code I replaced the break condition `(hh < ll)` with `(hh <= ll)`, which also saves the swap of a pair of equal elements.

BTW: Is the GIL released during the execution of medfilt2d, and if not, are there reasons against doing so?

**Comment by rgommers** [comment]
@J3ronimo sorry you didn't get a reply. `medfilt` and `medfilt2d` have some issues IIRC, so you're likely right in your analysis, changing this to "defect".
