### ISSUE TITLE
Why expm(2*A) != expm(A) @ expm(A)

### ISSUE THREAD

**Issue by kuzand** [scipy/scipy#9482]
Please have a look at this issue: https://stackoverflow.com/questions/53212497/why-expm2a-expma-expma

There is a problem with `scipy.linalg.expm` function.
Computing `expm(2*A)` and `expm(A) @ expm(A)`, for e.g. `A = np.arange(1,17).reshape(4,4)`, gives two different results, with the first one completely wrong due to overflow. However, there is no overflow when computing  `expm(A)`, but only  `expm(2*A)` . 

I was wondering why is this happening? Where can I find the source code of the expm to see what's going on? 

### Scipy/Numpy/Python version information:

1.1.0 1.15.3 sys.version_info(major=3, minor=6, micro=4, releaselevel='final', serial=0)

**Comment by pv** [comment]
Not reproducible:
```
>>> import scipy
>>> scipy.__version__
'1.1.0'
>>> A = np.arange(1,17).reshape(4,4)
>>> expm(A) @ expm(A)
array([[1.87271812e+30, 2.12068329e+30, 2.36864847e+30, 2.61661365e+30],
       [4.32685647e+30, 4.89977224e+30, 5.47268800e+30, 6.04560377e+30],
       [6.78099483e+30, 7.67886118e+30, 8.57672753e+30, 9.47459389e+30],
       [9.23513318e+30, 1.04579501e+31, 1.16807671e+31, 1.29035840e+31]])
>>> expm(2 * A)
array([[1.87271812e+30, 2.12068329e+30, 2.36864847e+30, 2.61661365e+30],
       [4.32685647e+30, 4.89977224e+30, 5.47268800e+30, 6.04560377e+30],
       [6.78099483e+30, 7.67886118e+30, 8.57672753e+30, 9.47459389e+30],
       [9.23513318e+30, 1.04579501e+31, 1.16807671e+31, 1.29035840e+31]])
```

**Comment by pv** [comment]
With `A = A.astype(np.int32)` as noted by Warren Weckesser in a comment the issue is already fixed.

**Comment by kuzand** [comment]
No it's not fixed with `A = A.astype(np.int32)` and the problem is reproducible by other people. So why did you close the issue?

 "I reproduced the problem using A = np.arange(1,17).reshape(4,4).astype(np.int32) in SciPy 1.1.0"

**Comment by kuzand** [comment]
> 
> 
> Not reproducible, works fine for me:
> 
> ```
> >>> import scipy
> >>> scipy.__version__
> '1.1.0'
> >>> A = np.arange(1,17).reshape(4,4)
> >>> expm(A) @ expm(A)
> array([[1.87271812e+30, 2.12068329e+30, 2.36864847e+30, 2.61661365e+30],
>        [4.32685647e+30, 4.89977224e+30, 5.47268800e+30, 6.04560377e+30],
>        [6.78099483e+30, 7.67886118e+30, 8.57672753e+30, 9.47459389e+30],
>        [9.23513318e+30, 1.04579501e+31, 1.16807671e+31, 1.29035840e+31]])
> >>> expm(2 * A)
> array([[1.87271812e+30, 2.12068329e+30, 2.36864847e+30, 2.61661365e+30],
>        [4.32685647e+30, 4.89977224e+30, 5.47268800e+30, 6.04560377e+30],
>        [6.78099483e+30, 7.67886118e+30, 8.57672753e+30, 9.47459389e+30],
>        [9.23513318e+30, 1.04579501e+31, 1.16807671e+31, 1.29035840e+31]])
> ```

What version of numpy do you have?

**Comment by ilayn** [comment]
It's a windows issue. On linux it should be working fine as noted in the comments of SO question. Change the datatype of A to float and it should work

**Comment by kuzand** [comment]
> 
> 
> It's a windows issue. On linux it should be working fine as noted in the comments of SO question. Change the datatype of A to float and it should work

Yes, but that's a bug. Hopefully in the next release it gets fixed.
