### ISSUE TITLE
build problem (can't install MSYS)

### ISSUE THREAD

**Issue by neyuru** [scipy/scipy#9487]
I'm following the instructions at: https://scipy.github.io/devdocs/building/windows.html
and, reporting back here.

There is a problem with gcc and gfortran because when issuing the commands:

gfortran
gcc

(as suggested) the MSYS2 terminal spits: 

bash: gfortran: command not found
bash: gcc: command not found

in the instructions at the webpage:

"**These commands should give errors as we have not provided any arguments to them. However an error also implies that they are accessible on the path.**"

but, if they are not accessible on the path, there is no suggested action to take!, so I am in a stalemate. I have installed, updated, and reinstalled and re-updated MSYS being careful to follow the instructions and I can't advance further, except for one thing:

I am using x64 architecture, downloaded msys2-x86_64-20180531.exe  from (http://repo.msys2.org/distrib/x86_64/) and executed it. The instructions at (https://github.com/msys2/msys2/wiki/MSYS2-installation) say to execute **msys2_shell.cmd** but... from where? from a terminal? from windows+R? none of them work. The program msys2.exe was installed correctly and I don't see how executing **msys2_shell.cmd** would make a difference.

**Comment by neyuru** [comment]
Thank you for your very fast response! I downloaded the precompiled versions from sourceforge (https://sourceforge.net/projects/openblas/files/) but then again, I will have to compile them and don't know how. 

Is there another alternative? like using MKL instead of openblas? How about an openblas binary? - My objective is scipy, not openblas, so could I skip the compilation of openblas alltogether? or is it a strictly necessary step?

I say that my objective is scipy because later I would want to install it on my pgo-optimized python build. (otherwise using pip would install non-optimized scipy, correct?)

**Comment by rgommers** [comment]
> Is there another alternative? like using MKL instead of openblas?

Yes, MKL + MSVC + Intel Fortran is the easiest thing to build on Windows, if you have all of those. See https://software.intel.com/en-us/articles/building-numpyscipy-with-intel-mkl-and-intel-fortran-on-windows. I see somehow we lost the link to that page from our own docs.

> How about an openblas binary? 

The mailing list post I linked above explains how to grab an OpenBLAS binary.

**Comment by rgommers** [comment]
> pgo-optimized python build. (otherwise using pip would install non-optimized scipy, correct?)

correct. not sure if there's any performance gain though. can't remember any discussion/report on PGO

**Comment by ilayn** [comment]
We probably didn't do a good job mentioning that you have to open a mingw64 terminal of the msys2 terminals (you should see three of those). The gcc and gfortran becomes available there and probably not in the native msys2 terminal. I remember specifically writing this down in that page but couldn't find it.

But I would also keep following Ralf's recommendation. Just wanted to mention that detail

**Comment by neyuru** [comment]
> 
> 
> We probably didn't do a good job mentioning that you have to open a mingw64 terminal of the msys2 terminals (you should see three of those). The gcc and gfortran becomes available there and probably not in the native msys2 terminal. I remember specifically writing this down in that page but couldn't find it.
> 
> But I would also keep following Ralf's recommendation. Just wanted to mention that detail

That did the job, I can now access the compilers. Before I was using msys2.exe. But now I have delved into Intel's implementation and if that doesn't work out, I'll try again using OpenBLAS, thanks!
