### ISSUE TITLE
l-bfgs-b cannot evaluate objective without also evaluating gradient

### ISSUE THREAD

**Issue by rkeane2** [scipy/scipy#9490]
In the bfgs algorithm, the gradient is evaluated once per iteration. The objective function may be evaluated several times per iteration, during the line search. In scipy's implementation, every time the objective function is evaluated, the gradient is also evaluated. This leads to an excessive amount of wasted time in problems where calculating the gradient is very expensive compared to evaluating the objective. 

For example, consider this use case: 
gradient evaluation time: ~5 seconds
objective evaluation time: ~.1 seconds
number of objective evaluations by bfgs: ~300
number of iterations: ~25
This is the scenario I find myself in, and 90% of the computation time is wasted due to this inefficiency. (Time needed is 300*(5+.1) when it should be 300*.1+25*5)

I have included a short example which shows that the gradient is being evaluated too many times. It prints out every time the gradient is called, and you can see the number of gradient calls is equal to 'nfev'  when it should be equal to 'nit'

### Reproducing code example:

```
import numpy 
import scipy.optimize as sc

def rosen(x): #rosenbrock function
    x = numpy.asarray(x)
    r = numpy.sum(100.0 * (x[1:] - x[:-1]**2.0)**2.0 + (1 - x[:-1])**2.0,
                  axis=0)
    return r

def rosen_der(x):
    print('this is a gradient evaluation')
    x = numpy.asarray(x)
    xm = x[1:-1]
    xm_m1 = x[:-2]
    xm_p1 = x[2:]
    der = numpy.zeros_like(x)
    der[1:-1] = (200 * (xm - xm_m1**2) -
                 400 * (xm_p1 - xm**2) * xm - 2 * (1 - xm))
    der[0] = -400 * x[0] * (x[1] - x[0]**2) - 2 * (1 - x[0])
    der[-1] = 200 * (x[-1] - x[-2]**2)
    return der


test = sc.minimize(rosen,[1,.9],(),'l-bfgs-b',rosen_der)
```
edit: To clarify, whether or not the gradient is used during the line search depends on what line search procedure is being used. 

### Scipy/Numpy/Python version information:
1.1.0 / 1.15.4 / 3.6.4

**Comment by david-cortes** [comment]
Disclaimer: I'm not a SciPy developer, this is just my perspective as a user who sometimes checks the source code.
As you might know, the L-BFGS-B optimizer is a wrapper over Nocedals's FORTRAN code:
http://users.iems.northwestern.edu/~nocedal/lbfgs.html

Putting there a different line search strategy would imply pretty much rewritting the algorithm, and also changing the termination test:
```fortran
C     OBTAIN THE ONE-DIMENSIONAL MINIMIZER OF THE FUNCTION 
C     BY USING THE LINE SEARCH ROUTINE MCSRCH
C     ----------------------------------------------------
 165  NFEV=0
      STP=ONE
      IF (ITER.EQ.1) STP=STP1
      DO 170 I=1,N
 170  W(I)=G(I)
 172  CONTINUE
      CALL MCSRCH(N,X,F,G,W(ISPT+POINT*N+1),STP,FTOL,
     *            XTOL,MAXFEV,INFO,NFEV,DIAG)
      IF (INFO .EQ. -1) THEN
        IFLAG=1
        RETURN
      ENDIF
      IF (INFO .NE. 1) GO TO 190
      NFUN= NFUN + NFEV
C
C     COMPUTE THE NEW STEP AND GRADIENT CHANGE 
C     -----------------------------------------
C
      NPT=POINT*N
      DO 175 I=1,N
      W(ISPT+NPT+I)= STP*W(ISPT+NPT+I)
 175  W(IYPT+NPT+I)= G(I)-W(I)
      POINT=POINT+1
      IF (POINT.EQ.M)POINT=0
C
C     TERMINATION TEST
C     ----------------
C
      GNORM= DSQRT(DDOT(N,G,1,G,1))
      XNORM= DSQRT(DDOT(N,X,1,X,1))
      XNORM= DMAX1(1.0D0,XNORM)
      IF (GNORM/XNORM .LE. EPS) FINISH=.TRUE.
C
      IF(IPRINT(1).GE.0) CALL LB1(IPRINT,ITER,NFUN,
     *               GNORM,N,M,X,F,G,STP,FINISH)
      IF (FINISH) THEN
         IFLAG=0
         RETURN
      ENDIF
      GO TO 80
```
I think that's not trivial work at all.

**Comment by rkeane2** [comment]
It's not true it would require rewriting the entire algorithm. The termination conditions would be exactly the same: norm of gradient is very close to zero, relative reduction in the objection function is below the tolerance, or more function evaluations/iterations than allowed. All you would have to do is switch out mcsrch (which uses the strong wolfe conditions) with something that does backtracking line search instead. When doing the backtracking line search, you don't have the curvature condition which requires the gradient to be evaluated again.

**Comment by rkeane2** [comment]
I believe the l-bfgs-b code already has the ability to do backtracking line search. If you call l-bfgs-b without giving it a gradient (in which case it uses automatic numerical differentiation to calculate the gradient), you can tell from the number of objective evaluations that it does not use the curvature condition in the line search. 

In other words, whatever linesearch routine l-bfgs-b does when you don't pass in a gradient, is the linesearch I want to use when I DO pass in the gradient. Unfortunately I don't understand how all this "wrapper" business works or even where/how to view the fortran code that python supposedly calls.

**Comment by david-cortes** [comment]
The fortran code is here: https://github.com/scipy/scipy/blob/master/scipy/optimize/lbfgsb_src/lbfgsb.f
The wrapper is here: https://github.com/scipy/scipy/blob/master/scipy/optimize/lbfgsb_src/lbfgsb.pyf
And is called from here: https://github.com/scipy/scipy/blob/master/scipy/optimize/lbfgsb.py

You'd need to add an additional input parameter to the code to choose whether to perform a different type of line search, add that parameter to the wrapper, and call it with that one extra parameter from `minimize` - note the lines with `def func_and_grad(x)` (and of course, implement your desired line search strategy in the fortran code).

**Comment by melissawm** [comment]
I'm not sure this would be a good idea. From the [original paper](http://users.iems.northwestern.edu/~nocedal/lbfgsb.html),

> "The first implementation of our algorithm used a backtracking line search, but we found that this approach has a drawback. On several problems the backtracking line search generated steplengths for which the updating condition (3.9) did not hold, and the BFGS update had to be skipped. This resulted in very poor performance in some problems. (...) Our results suggest that backtracking line searches can significantly degrade the performance of BFGS, and that satisfying the Wolfe conditions as often as possible is important in practice."

So it looks like the code should be as it is.

**Comment by david-cortes** [comment]
> I'm not sure this would be a good idea. From the [original paper](http://users.iems.northwestern.edu/~nocedal/lbfgsb.html),
> 
> > "The first implementation of our algorithm used a backtracking line search, but we found that this approach has a drawback. On several problems the backtracking line search generated steplengths for which the updating condition (3.9) did not hold, and the BFGS update had to be skipped. This resulted in very poor performance in some problems. (...) Our results suggest that backtracking line searches can significantly degrade the performance of BFGS, and that satisfying the Wolfe conditions as often as possible is important in practice."
> 
> So it looks like the code should be as it is.

Can also confirm that I implemented part of an LBFGS routine on my own, and it produced very bad results with a regular backtracking Armijo condition.

**Comment by rgommers** [comment]
Thanks so much for all the digging @melissawm and @david-cortes. It sounds like we should close this as wontfix. I'll leave this open for now to give other `scipy.optimize` experts a chance to weigh in. Will close in a couple of days if there are no more comments.

**Comment by rkeane2** [comment]
If you implement the default backtracking linesearch it won't work very well, including a part of the code that uses interpolation to find the next step length (as well as including safeguards on the interpolation) is very important to the performance. Another thing I have found to help  backtracking linesearch alot is to use a nonmonotone search.

My reference for the (weak/strong) wolfe linesearch is "Numerical Optimization" by Nocedal and Wright, the linesearch/zoom code on pg. 60-61. If you include the cubic interpolation and safeguards I believe you get the same linesearch code which is in scipy.optimize.line_search; or at least I remember testing it in the past and getting the same result on the rosenbrock function. 

For a nonmonotone backtracking linesearch my reference is "Nonmonotone Spectral Projected Gradient methods on Convex Sets" by Birgin et al. I have found the nonmonotone backtracking to be better than the strong or weak wolfe on some problems. 

If anyone is interested in testing the nonmonotone backtracking I've included my python implementation of the algorithm. You'll need to combine it with a optimization algorithm to use it. 

`def nmbacktrack(p,d,obj,fnc,fnc_objder, grad, args, iters, bounds, past, pastp, t, *fargs, c1=1e-4, alo = .1, ahi = .9, gamma = .5, proj_type = 0, maxLSiter = 40, **kwargs):
    ##inputs
    #p - parameters for initial guess 
    #d - search direction (may not be same as gradient due to projection)
    #obj - objective function value 
    #fnc - function to evalate objective
    #fnc_objder - function to evaluate both objective and gradient
    #grad - gradient of objective w.r.t. current parameters
    #args - extra arguments to pass to objective/gradeint function
    #iters - numbers of iterations of optimization alg so far
    #bounds - bounds for parameters, list of tuple for each parameter with lower and upper bounds
    #past - past values of the objective (need this for nonmonotone part)
    #pastp - past values of the parameters
    #t - maximum number of iterations we can go without a sufficient decrease - if this is zero then this is just regular backtracking
    #*fargs  - any extra arguments that may be passed in (this is for other routines since they might have different inputs; in this code it is not used)
    #c1 - parameter controls sufficient decrease, if c1 is smaller, required decrease is also smaller. typically 1e-4 is used 
    #alo - minimum safeguard for interpolated step size, can usually leave as .1
    #ahi - maximum safeguard for interpolated step size, can usually leave as .9 
    #gamma - this is the modification to the step size in case the interpolation fails (typically left as .5)
    #proj_type = 0 - if proj type is zero we project every iteration in optimization algorithm (project search direction), otherwise everytime we get a new step size we will project (proj_type = 1)
    #maxLSiter = 40 - maximum number of iterations of linesearch algorithm before we return the best found value, typically this should find the step in ~2-3 iterations and if you get past 10 or 20 
    #it might mean the search direction has a problem
    
    #outputs
    #pn - new parameter values
    #objn - new objective value
    #gradn - new gradient value (false if not computed)
    #hessn - new hessian value (false if not computed)
    #objeval - number of objective evaluations 
    #gradeval - number of gradient evaluations
    
    #initialization 
    if proj_type ==0: #projection happens in optimization algorithm
        pn = p + d
        da = d
    else: #need to project every iteration in line search 
        pn = projection(p+d,bounds) 
        da = pn-p 
    
    dirder = np.matmul(grad,da) #directional derivative
#    cdirder = c1*dirder
    objn = fnc(pn,*args)
    objeval = 1
    gradeval = 0 
    a = 1
    if iters < t:
        maxobj = obj
    else: 
        maxobj = max(past)
    #backtracking procedure
    while objn > maxobj + c1*dirder: #if sufficient decrease condition is not met
        #gamma is the current modifier to the step length
        #a is the total modifier
        #dirder is the current directional derivative times the step length. 
        #objb is the previous objective value, objn is the current objective value 
        gamman = -dirder*a/(2*(objn-obj-dirder)) #quadratic interpolation
        #safeguards 
#        if gamman < alo: #this is one way to safeguard
#            gamman = alo
#        elif gamman > ahi:
#            gamman = ahi
        if gamman < alo or gamman > ahi:  #this is how the paper recommends to safeguard
#        if True: #deubgging purposes 
            gamman = gamma
        a = gamman*a #modify current step length
        d = gamman*d #modify current direction 
        #get new step if proj_type == 0 
        if proj_type ==0:
            dirder = gamman*dirder
            pn = p+d
        else: 
            pn = projection(p+d,bounds) #project onto feasible set
            da = pn - p #new search direction
            dirder = np.matmul(grad,da) #directional derivative
        
        objn = fnc(pn,*args)
        objeval += 1
        
        #need a way to terminate the linesearch if needed. 
        if objeval > maxLSiter: 
            print('linesearch failed to find a step of sufficient decrease')
            if objn >= obj: #if current objective is worse than original 
                pn = p #return original 
                objn = obj
            break
        
        
    if iters < t:
        past.append(objn) #add the value to the past
        pastp.append(pn)
    else: 
        past.pop(0) #remove the first value
        past.append(objn) #add the new value at the end 
        pastp.pop(0)
        pastp.append(pn)
    gradn = [None]
    hessn = [None]  
    
    return pn, objn, gradn, hessn, objeval, gradeval

def projection(p, bounds):
    n = len(p)
    for i in range(n):
        if p[i] < bounds[i][0]:
            p[i] = bounds[i][0]
        elif p[i] > bounds[i][1]:
            p[i] = bounds[i][1]
    return p
`

**Comment by andyfaff** [comment]
Looks like this is a won't fix.
