### ISSUE TITLE
_pytest.warning_types.RemovedInPytest4Warning: MarkInfo objects are deprecated in scipy.test() with SciPy 1.1.0 on Python 3.7.1

### ISSUE THREAD

**Issue by novosirj** [scipy/scipy#9491]
I have recently built Python 3.7.1 and build NumPy/SciPy with the Intel Composer XE 2018 update 4 (18.0.5) compiler suite and Intel MKL. I also enabled -O3 optimizations for SciPy, which it said might generate a test error in a corner case that was known about. I wanted to confirm that this was still a problem before using less sophisticated optimizations. However, The test only returned one error, and it doesn't seem like it could have anything to do with that (though I've not found confirmation of what the corner case actually is). Is this a bug, or is there potentially something else I'm doing wrong?

### Reproducing code example:

```
import scipy
scipy.test()
```

### Error message:

-->

```
>>> import scipy
>>> scipy.test()
============================================== test session starts ===============================================
platform linux -- Python 3.7.1, pytest-4.0.0, py-1.7.0, pluggy-0.8.0
rootdir: /cache/home/novosirj, inifile:
collected 10179 items / 1 errors / 585 deselected                                                                

===================================================== ERRORS =====================================================
___________________________________ ERROR collecting sparse/tests/test_base.py ___________________________________
/opt/sw/packages/gcc-4_8/python/3.7.1/lib/python3.7/site-packages/pluggy/hooks.py:284: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
/opt/sw/packages/gcc-4_8/python/3.7.1/lib/python3.7/site-packages/pluggy/manager.py:67: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/opt/sw/packages/gcc-4_8/python/3.7.1/lib/python3.7/site-packages/pluggy/manager.py:61: in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
/opt/sw/packages/gcc-4_8/python/3.7.1/lib/python3.7/site-packages/_pytest/python.py:224: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
/opt/sw/packages/gcc-4_8/python/3.7.1/lib/python3.7/site-packages/_pytest/python.py:432: in _genfunctions
    originalname=name,
/opt/sw/packages/gcc-4_8/python/3.7.1/lib/python3.7/site-packages/_pytest/python.py:1382: in __init__
    self.keywords[mark.name] = mark
/opt/sw/packages/gcc-4_8/python/3.7.1/lib/python3.7/site-packages/_pytest/mark/structures.py:25: in warned
    warnings.warn(warning, stacklevel=2)
E   _pytest.warning_types.RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
E   Please use node.get_closest_marker(name) or node.iter_markers(name).
E   Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
```

### Scipy/Numpy/Python version information:

```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
```

**Comment by pv** [comment]
You'll probably need to downgrade to `pytest<4.0.0` to run the tests.

**Comment by novosirj** [comment]
Oh. seems like not -- it just fails to run the complete tests appropriately. There are actually _more_ failures on 3.10.1, but I'll look through them and see if they make more sense/are not about deprecation. Thanks for the tip.

**Comment by novosirj** [comment]
I'm not totally sure if these are serious or not. I guess I'll try recompiling with -O1 for SciPy Fortran and see if it makes any difference, unless anyone knows otherwise.

[scipy-errors.txt](https://github.com/scipy/scipy/files/2590786/scipy-errors.txt)

**Comment by rgommers** [comment]
The `suppress_warnings` ones are weird, not related to compiler optimization flags. Just ignore I'd say, not a real issue. The three tests with precision issues could be a problem, differences look large. So if you use the functions that it's failing for, use `-O1`.

**Comment by rgommers** [comment]
This is no longer relevant due to age - things work fine with latest Pytest. So I'll close this - thanks all.
