### ISSUE TITLE
python runtests.py -v fails on master branch w/sha 79dae16990d6d17398a372cae22a291bf23de980 

### ISSUE THREAD

**Issue by rlucas7** [scipy/scipy#9496]
My issue is about the runtests.py file fails when run on mast recent commit. 

### Reproducing code example:

```
python runtests.py -v 
```

### Error message:

```
Building, see build.log...
Build OK (0:00:05.539618 elapsed)
================================================================================ test session starts ================================================================================
platform darwin -- Python 3.6.6, pytest-3.7.3, py-1.5.4, pluggy-0.7.1 -- /Users/rlucas/anaconda3/envs/scipy-dev/bin/python
cachedir: .pytest_cache
rootdir: /Users/rlucas/scipy-dev/scipy, inifile: pytest.ini
collected 16664 items / 1 errors / 1223 deselected                                                                                                                                  

====================================================================================== ERRORS =======================================================================================
_________________________________ ERROR collecting build/testenv/lib/python3.6/site-packages/scipy/optimize/tests/test__linprog_ip_clean_inputs.py __________________________________
ImportError while importing test module '/Users/rlucas/scipy-dev/scipy/build/testenv/lib/python3.6/site-packages/scipy/optimize/tests/test__linprog_ip_clean_inputs.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
scipy/optimize/tests/test__linprog_ip_clean_inputs.py:9: in <module>
    from scipy.optimize._linprog_ip import _clean_inputs
E   ImportError: cannot import name '_clean_inputs'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================================================== 1223 deselected, 1 error in 11.46 seconds =====================================================================
```

### Scipy/Numpy/Python version information:

I updated my local repo master branch with master from github/scipy (was about 130 commits behind prior to the last release). Working on getting things back to a useable state as before. The docs all build in sphinx successfully. I was also able to run (and pass) all tests in the `stats` submodule (where I've mostly been contributing. I also got passing tests on the following submodules `[stats, special, spatial, sparse]`.  Also, 88 tests failed on the signal submodule e.g. `python runtests.py -v -s signal`.

**Comment by ilayn** [comment]
Did you first run `git clean -xdf` and then build it from scratch with `python setup.py build` ?

**Comment by rlucas7** [comment]
I did not. Should I be doing a clean on every git pull from the scipy/scipy upstream? 
That appears to fix the issue w/the test in optimize submodiule but I'm still getting all the failures in the signal submodule?

**Comment by ilayn** [comment]
I'm not sure anymore because I can't keep up with the dependency updates hence I'm just doing it anyways. But that's out of ignorance. Someone might know better why and when.

**Comment by rgommers** [comment]
> I did not. Should I be doing a clean on every git pull from the scipy/scipy upstream?

No, in principle rebuilds should take care of this. However, it sometimes messes up, `setuptools` tracking isn't great so it could pick up outdated build artifacts. I use `git clean -xdf` a lot; if you don't have a fast build machine then not cleaning and only using `git clean -xdf` when you see weird failures  can also be a good strategy.

**Comment by rlucas7** [comment]
ugh, this was b/c I hadnt updated my virtual environment when I pulled in the new release. 
`conda update --all` then `git clean -xdf` then `python runtests.py -v` builds fine now. Thanks @rgommers + @ilayn appreciate the help.
