### ISSUE TITLE
Relational attributes in loadarff

### ISSUE THREAD

**Issue by vnmabus** [scipy/scipy#9518]
I was trying to load a dataset in arff format that have a relational attribute. However, it seems that scipy can not handle them nowadays:

https://github.com/scipy/scipy/blob/c2ec858d63ac143e6da4c4f48005c30f5185b95b/scipy/io/arff/arffread.py#L284

Are there any plans for adding this feature?

**Comment by ilayn** [comment]
Hi @vnmabus, if somebody steps up for a PR that would be great. Otherwise we need to wait for a volunteer.

**Comment by tylerjereddy** [comment]
The cross-linked PR has been merged & this has been tagged with the appropriate milestone now, so closing.
