### ISSUE TITLE
FutureWarning for non-tuple sequence (another)

### ISSUE THREAD

**Issue by gandroz** [scipy/scipy#9519]
Linked to [PR8944](https://github.com/scipy/scipy/pull/8944), I got warning message:

```scipy/signal/_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[a_slice]```

I tried to apply the same fix as in the PR but the warning still pops

**Comment by dankal444** [comment]
same is with `signaltools.resample` function
all lines containing `sl` indices, e.g. `Y[sl] = X[s]`

**Comment by ilayn** [comment]
You can install the SciPy v.1.2.0 Release Candidate 2 from [here](https://github.com/scipy/scipy/releases/tag/v1.2.0rc2) and see whether the issue is gone for good.

**Comment by dankal444** [comment]
@ilayn Tried it and those warnings are missing. Thanks!
