### ISSUE TITLE
`nonlin_solve()` in `nonlin.py` raises AttributeError when passing a function for the jacobian

### ISSUE THREAD

**Issue by chanshing** [scipy/scipy#9521]
When I use `scipy.optimize.nonlin.nonlin_solve` and pass a callable to `jacobian` argument that returns the jacobian matrix, it raises an `AttributeError: 'Jac' object has no attribute 'x'`. A code to reproduce it:

```python
import numpy
import scipy.optimize

def jac(x):
    return numpy.eye(3)

def res(x):
    return x * numpy.ones(3)

print scipy.optimize.nonlin.nonlin_solve(res, 999 * numpy.ones(3), jacobian='krylov')  # works
print scipy.optimize.nonlin.nonlin_solve(res, 999 * numpy.ones(3), jacobian=jac)  # raises AttributeError
```

I looked into the source code and `jacobian` is wrapped using `asjacobian(jacobian)` which turns it into a `Jac` object. The problem is that the `jacobian.solve` method is called shortly after, which requires `jacobian.x` to be defined. I think that the possible cause is that the `setup` method is checking the object instance against `Jacobian` instead of `Jac`?

In the meantime, a quick solution is to wrap the function myself and instantiate `x`, before passing it to `nonlin_solve`:
```python
jac2 = scipy.optimize.nonlin.asjacobian(jac)
jac2.x = numpy.array([1,2,3])
print scipy.optimize.nonlin.nonlin_solve(res, 999 * numpy.ones(3), jacobian=jac2)  # now it works
```

**Comment by pv** [comment]
scipy.optimize.nonlin.nonlin_solve is not a public function (as noticeable from the fact that it is not in the documentation).

**Comment by rgommers** [comment]
`optimize.nonlin` isn't public, and we set `currentmodule` correctly in its docstring, but we do make things confusing by including `nonlin` in the html docs: https://docs.scipy.org/doc/scipy/reference/optimize.nonlin.html

should we move it to `_nonlin`?

**Comment by chanshing** [comment]
> `optimize.nonlin` isn't public, and we set `currentmodule` correctly in its docstring, but we do make things confusing by including `nonlin` in the html docs: https://docs.scipy.org/doc/scipy/reference/optimize.nonlin.html
> 
> should we move it to `_nonlin`?

**Comment by chanshing** [comment]
> scipy.optimize.nonlin.nonlin_solve is not a public function (as noticeable from the fact that it is not in the documentation).

I see, but it probably should still work for the example above. This is the documented comment for the jacobian argument:

```
    jacobian : Jacobian
        A Jacobian approximation: `Jacobian` object or something that
        `asjacobian` can transform to one. Alternatively, a string specifying
        which of the builtin Jacobian approximations to use:
            krylov, broyden1, broyden2, anderson
            diagbroyden, linearmixing, excitingmixing
```

As per the comment, it seems to suggest that we can pass a callable.

Side question: What can I use instead of `nonlin_solve`? I would like to perform simple Newton's method but multivariate, where I have the exact jacobian. Thank you.

**Comment by rgommers** [comment]
> I see, but it should probably still work for the example above.

not too familiar with this functionality, but you're probably right (or we should update the comment at least). To decide, it would be helpful though to know if this affects one of the public functions that use `nonlin_solve`.

> What can I use instead of `nonlin_solve`? I would like to perform simple Newton's method but with N inputs and N outputs, with N very large and where I have the exact jacobian which is sparse.

Would `optimize.least_squares` with the `jac_sparsity` option (or `sparse.linalg.lsmr` directly) fit that?

**Comment by chanshing** [comment]
> Would `optimize.least_squares` with the `jac_sparsity` option (or `sparse.linalg.lsmr` directly) fit that?

Aham... I will give it a try. Thank you for your time.
