### ISSUE TITLE
Incorrect test for parallelity in sparse/linalg/_onenormest.py suggests performance improvement

### ISSUE THREAD

**Issue by SuperFluffy** [scipy/scipy#9528]
This issue regards latest master, (right now at commit 3c46ac1fcadc0b202c7bebeb88db9ec2fceb653c; that commit is unrelated to this issue), but exists probably since the inception of the function discussed below. This is a minor issue, because the likelihood of it occurring is very slim (but see below). It does however suggest a performance  improvement.

# Problem description

I have been studying scipy's implementation of `linalg.expm`, which is an implementation of [Algorithm 2.4 by Higham & Tisseur], and I believe that the test for two vectors being parallel in `_onenormest` is wrong, specifically this line in the function `vectors_are_parallel`: https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/_onenormest.py#L190, which reads:

```python
def vectors_are_parallel(v, w):
    # Columns are considered parallel when they are equal or negative.
    # Entries are required to be in {-1, 1},
    # which guarantees that the magnitudes of the vectors are identical.
    if v.ndim != 1 or v.shape != w.shape:
        raise ValueError('expected conformant vectors with entries in {-1,1}')
    n = v.shape[0]
    return np.dot(v, w) == n
```

This function assumes that two vectors are parallel if their dot product is equal to their mutual number of rows. This is true if and only if they are vectors filled with `+/- 1`. Counter example:

```
x = np.array([1,1,1,1])
y = 0.5 * x
n_rows = x.shape[0] # 4
product = np.dot(x, y) # 0.5 * ||x||
n == product # false
```

The vectors `x` and `y` fulfill the condition of being in the range `[-1, 1]` and are clearly parallel, since `y` is a `x` scaled by 1/2. According to this algorithm, they are not parallel.

# Discussion

The reason why this hasn't popped up as an issue yet is twofold:

1. When initializing the starting matrix `X` in Algorithm 2.4, on [line 392](https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/_onenormest.py#L392) in the code, the first column has entries `1 / n_rows`, while all other entries are sampled from `x ~ Uniform(-1, +1)`. The likelihood of two columns having exactly the same entries (up to the last bit in 64 bit floating point) is extremely slim, but not zero (but can be treated as 0 for all intents and purposes).
2. When calculating the sign matrix and then checking for parallelity of its column, steps and (2) and (3) in Algorithm 2.4, or [Lines 423 to 434](https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/_onenormest.py#L423-L434), the sign matrix is indeed at first only populated with `+/- 1`, so the check would yield `n_rows` if two columns are parallel. When repopulating a parallel column though the same holds as in 1): there is a extremely small but non-zero chance that one can get two randomly generated columns, where one is an exact multiple of the other.

# Possible steps

1. Leave the check as it is. The probability of a random number generator creating two columns where all corresponding elements are the exact same multiple of each other is almost zero (in particular for large matrices).
2. Change the check for parallelity: the entries of the vector `u = v / w` (where `/` is element-wise division) have to be all the same (considering we are also dealing with floating point precision, this seems *very* unlikely to actually ever work).

## Performance improvement

If one chooses to leave everything as is, running `vectors_are_parallel` on randomly generated columns becomes redundant, because even if two parallel vectors would by chance be generated, the function wouldn't yield a correct result anyways. In particular, one can:

+ Remove https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/_onenormest.py#L393-L396
+ Change https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/_onenormest.py#L432-L434, so that only those columns are checked for parallelity, which are freshly calculated in https://github.com/scipy/scipy/blob/master/scipy/sparse/linalg/_onenormest.py#L283 and not yet resampled (in case they are found to be parallel to another column). All columns in `S` and `S_old` which have been randomly generated need neither be tested nor tested against. This requires keeping track of those column indices which have been resampled.

[Algorithm 2.4 by Higham & Tisseur]: http://eprints.ma.man.ac.uk/321/1/covered/MIMS_ep2006_145.pdf

**Comment by rgommers** [comment]
@SuperFluffy now that you understand this potential problem, is it possible for you to construct an example that does show the issue? And when I say example, I mean using a function that's in the public API of `sparse.linalg` (because `vectors_are_parallel` itself is not public).

**Comment by SuperFluffy** [comment]
Sorry for the late reply. My thinking was wrong. Had I paid more attention, I would have realized that the resampled columns are random vectors filled with `-1, +1`, as becomes evident from `def resample_column`.

Nothing should be changed in regards to `_onenormest_core`.
