### ISSUE TITLE
On PyPy `test_random_data_multidim_axes` crashing

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#9530]
The CircleCI PyPy run result ([example](https://circleci.com/gh/scipy/scipy/10088?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification)):
```
[gw1] linux -- Python 3.5.3 /usr/local/bin/pypy3
Worker 'gw1' crashed while running 'build/testenv/site-packages/scipy/signal/tests
/test_signaltools.py::TestFFTConvolve::test_random_data_multidim_axes[axes4]'
```

The test:
```
    @pytest.mark.parametrize('axes', [[1, 4],
                                      [4, 1],
                                      [1, -1],
                                      [-1, 1],
                                      [-4, 4],
                                      [4, -4],
                                      [-4, -1],
                                      [-1, -4]])
    def test_random_data_multidim_axes(self, axes):
        np.random.seed(1234)
        a = np.random.rand(123, 222) + 1j * np.random.rand(123, 222)
        b = np.random.rand(132, 111) + 1j * np.random.rand(132, 111)
        expected = convolve2d(a, b, 'full')

        a = a[:, :, None, None, None]
        b = b[:, :, None, None, None]
        expected = expected[:, :, None, None, None]

        a = np.rollaxis(a.swapaxes(0, 2), 1, 5)
        b = np.rollaxis(b.swapaxes(0, 2), 1, 5)
        expected = np.rollaxis(expected.swapaxes(0, 2), 1, 5)

        # use 1 for dimension 2 in a and 3 in b to test broadcasting
        a = np.tile(a, [2, 1, 3, 1, 1])
        b = np.tile(b, [2, 1, 1, 4, 1])
        expected = np.tile(expected, [2, 1, 3, 4, 1])

        out = fftconvolve(a, b, 'full', axes=axes)
        assert_(np.allclose(out, expected, rtol=1e-10))
```

**Comment by ilayn** [comment]
As much as I would love to keep the PyPy run, I think this is a bit too much for us to maintain. Seemingly random fails are quite common from again random places (of course there is an underlying reason probably somewhere).

**Comment by ilayn** [comment]
Xref #9508

**Comment by rgommers** [comment]
We added `pypy3` ourselves to CI in gh-8783, under the assumption that it would not be much work. These failures do seem consistent, I get the same ones repeatedly (CircleCI sends nice "build failed" emails post-merge). So points towards real bugs in PyPy, perhaps in combination with changes in NumPy that now trigger the crashes. 

@mattip how would you suggest to deal with these? Report to PyPy and skip perhaps?

**Comment by ilayn** [comment]
Ah what I meant by random is that when we fix one, another fail pops up but not simultaneously.

**Comment by rgommers** [comment]
Ah yes, because of the crashes - hard to tell how many are left for tests that are now never executed. That would require someone to reproduce these locally, indeed not much point skipping tests one by one.

**Comment by mattip** [comment]
Runnine the circleCI pypy3 test setup locally does not crash on my Ubuntu 18.04, even when running with `-n4`. Did the CI check once run successfully and suddenly stop doing so? Perhaps the circleci is using a different BLAS than mine which has some issues with threading, and PyPy hits that issue more consistently?

**Comment by rgommers** [comment]
The SciPy build uses ATLAS (https://github.com/scipy/scipy/blob/master/.circleci/config.yml#L110) while NumPy is installed from a wheel so should be using OpenBLAS. I suspect OpenBLAS will be the issue. I'll have a look at the history, maybe there's a correlation with OpenBLAS version.

**Comment by rgommers** [comment]
Okay, the original PR was pre numpy 1.15.0, and used numpy master because there were some pypy3 fixes in there that were needed. Then we switched to >=1.15.0, so it means we switched from a numpy source build which would have picked up ATLAS to now 1.15.4 which uses OpenBLAS 0.3.0.

@mattip why do you specifically say "issues with threading"?

**Comment by mattip** [comment]
It seems OpenBlas is not really thread safe, there are various open issues around it in NumPy. PyPy may be more aggressively or even improperly releasing the GIL in its C-API compatibility layer. Could we run the CI with whatever environment variable signals to BLAS to run single threaded, or will that make it run too slow?

**Comment by mattip** [comment]
Assuming my leap of faith is correct and threading is the issue, and not some GC related kerfuffel. Strange it doesn't show up locally, even when following the CI recipe.

**Comment by rgommers** [comment]
Failures still occurring: https://circleci.com/gh/scipy/scipy/10272?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification. It seems non-deterministic. Still have the impression that `OPENBLAS_NUM_THREADS=1` helped, but didn't fix it all.

**Comment by tylerjereddy** [comment]
This is definitely still crashing in a number of recent PRs.

**Comment by mattip** [comment]
It might be a OOM crash caused by the 4GB machine limit when running `pytest -n3`. When I set `ulimit -m 990` and run the tests in a single instance (without the `-n3`), I can reproduce the crash. Setting `PYPY_GC_MAX=900MB` to force the GC to be more aggresive about collecting memory seems to solve it locally. I am still investigating the root cause, but would it be acceptable to add that environment variable, and remove the `OPENBLAS_NUM_THREADS=1`?

**Comment by rgommers** [comment]
that sounds fine to me

**Comment by larsoner** [comment]
I think this one has stabilized with the `PYPY_GC_MAX` fix, so I'll close. Let's reopen again if necessary.
