### ISSUE TITLE
burr gives wrong mean() and expect()

### ISSUE THREAD

**Issue by rlucas7** [scipy/scipy#9544]
My issue is about ...
The `burr` distribution does not produce the correct mean() and expect() values. 

### Reproducing code example:

```
>>> from scipy.stats import burr
>>> f_burr = burr(0.94839, 4.382028)
>>> f_burr.mean()
-90.8450580569245
>>> f_burr.expect()
/Users/rlucas/anaconda3/envs/scipy-dev/lib/python3.6/site-packages/scipy-1.2.0.dev0+6683b5f-py3.6-macosx-10.7-x86_64.egg/scipy/integrate/quadpack.py:385: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  warnings.warn(msg, IntegrationWarning)
-90.8450580500504
```

### Error message:
In my dev environment, the first time the `.expect()` is called I get
```
IntegrationWarning: ...
```

### Scipy/Numpy/Python version information:

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.0.dev0+6683b5f 1.15.4 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
```

This may be a known issue given that these parameter values are in the source code. 
at `tests/test_continuous_basic.py` LIC 45. Does anyone know or remember anything about this issue?

**Comment by rlucas7** [comment]
the `var()` method also gives non-sensical results

 f_burr.var()
-7997.5681215257

**Comment by rlucas7** [comment]
cdf appears to be fine:
>>> f_burr.cdf(0)
0.0
>>> import numpy as np
>>> f_burr.cdf(np.inf)
1.0
>>> f_burr.cdf(10)
0.6264828708111116
>>> f_burr.cdf(1)
0.04795988467974732
>>> f_burr.cdf(3)
0.2660479841928383
>>> f_burr.cdf(50)
0.8994637244282145
>>> f_burr.cdf(500)
0.9880109529403922
>>> f_burr.cdf(50000)
0.9998468284412179
>>> f_burr.cdf(5000000)
0.9999980571535964
>>> f_burr.cdf(5000000000)
0.9999999972249616

**Comment by WarrenWeckesser** [comment]
For `c <= 1`, the mean of the Burr Type III distribution doesn't exist.  The distribution is also known as the Dagum distribution, and you can see the formula for the mean on the [Dagum distribution wikipedia page](https://en.wikipedia.org/wiki/Dagum_distribution).  (The parameter `a` on the wikipedia page is the parameter `c` in the SciPy implementation.)

This leads to a natural enhancement request for `burr`: use the explicit formula for the mean when computing the default value of `expect()`.  (And as long as someone is editing that part of the code: make a note in the `burr` docstring that the distribution is also known as the Dagum distribution.)

**Comment by WarrenWeckesser** [comment]
> that is is a special case of Dagum (w/b=1

`b` is the scale, and `burr` has a scale parameter, so technically, the Dagum distribution on the wikipedia page is a special case of `burr` with `loc=0`. 😃 

>  `expect()` is numerical approximation whereas mean() is exact.

But when `func` is not given to `expect()`, it computes the mean.  Since we *know* we are computing the mean in that case, and we have an explicit formula for it, it is silly to not use it.  I don't see any problem with adding a note explaining this in the `expect()` docstring, and implementing it wherever we can.  (I'm not saying you have to do this if you create a pull request to enhance the implementation of `burr`, but it would be nice if eventually such an enhancement to `expect` is made to `burr` and other distributions where appropriate.)

**Comment by josef-pkt** [comment]
just in general about parameter values like `burr(0.94839, 4.382028)`.

The parameters in the unit tests where initially created by random numbers until I found some that "worked". There was not enough time and often no (accessible) references to check each individual distribution specifically. 

It would be better if those are replaced by "good" parameters, if they are still the old random parameters, and have, for example, infinite or non-existent moments.

**Comment by rlucas7** [comment]
Thanks for the info @josef-pkt super helpful. I'm working on a PR, should be out within another day or 2, I'll add you and Warren to the PR.

**Comment by rlucas7** [comment]
https://github.com/scipy/scipy/pull/10381 was merged and that incorporated a changeset that addressed the issue(s) mentioned here, therefore closing. Thanks @pvanmulbregt @josef-pkt @WarrenWeckesser @ev-br
