### ISSUE TITLE
Is there any way to get the stats.norm methods to use a right tail?

### ISSUE THREAD

**Issue by retiform** [scipy/scipy#9545]
Methods like scipy.stats.norm seem to only work with left tails. Am I just misunderstanding this, or is it a limitation of the code.  If it is a limitation of the code, can this be fixed?  This works great for people only using percentiles, but is not great if you want to find percentages of upper bounds. 

Ex:

``` 
scipy.stats.norm.cdf(3) # finds percent bellow z score of 3
```
Returns only
```
0.9986501019683699
```

And has no option to return a right tail value  (0.0013498980316300933) aside from just making the number negative.  This is a bit more annoying on some other methods.

**Comment by josef-pkt** [comment]
use `sf` and the corresponding `isf` which is in many cases numerically more precise in the upper tail

**Comment by WarrenWeckesser** [comment]
I think you are looking for the [survival function](https://en.wikipedia.org/wiki/Survival_function), which is implemented in the SciPy distributions as the method `sf`:

```
In [112]: from scipy.stats import norm

In [113]: norm.sf(3)
Out[113]: 0.0013498980316300933
```

**Comment by retiform** [comment]
alright thanks!
