### ISSUE TITLE
signature of dual_annealing doesn't match other optimizers

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#9547]
Hi all, can't believe I missed this in the review, but there's an issue with the `dual_annealing` signature. Compare these:

    basinhopping(func, x0, ...
    differential_evolution(func, bounds, args=(), ...
    shgo(func, bounds, args=(), ...
    dual_annealing(func, x0, bounds, args=(), ...

The `x0` shouldn't be there, so the 3 best global optimizers have matching signatures. The `dual_annealing` docstring even talks about that it's fine to pass `None` for `x0`, in which case it generates a starting point. So clearly `x0` should be either removed or optional. Making it a keyword is probably the easiest thing to do.

There's still time to fix this before the release (even though we had an RC). @sgubianpm thoughts?

**Comment by andyfaff** [comment]
Oops. That definitely needs to be changed before the release

**Comment by sgubianpm** [comment]
@rgommers , @andyfaff 
I would agree with @rgommers, the idea was to let the user input an initial starting point as an initial guess and have a similar signature as basinhopping (if ``None`` is provided, it is generated). Maybe the best thing would be to make it optional then.

**Comment by tylerjereddy** [comment]
The cognate PR has been merged -- closing.
