### ISSUE TITLE
ndimage routines behave badly when output has memory overlap with inputs

### ISSUE THREAD

**Issue by yuracpp** [scipy/scipy#9553]
Maybe the problem is following
...
_tmp = grey_erosion(tmp, size, footprint, structure, output, mode, cval, origin)_ 
tmp and input is the same now
so
_numpy.subtract(tmp, input, out=tmp)_
gives zero

Thank you

**Comment by ilayn** [comment]
@yuracpp Do you mind adding a reproducable code snippet that we can copy and paste to see the problem for ourselves? 

It is not easy for us to understand anything from this.

**Comment by yuracpp** [comment]
import numpy as np
import scipy.ndimage as ndi

a = np.ones((3,3))
a[1,1] = 0
ndi.black_tophat(a, size=3)
array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]])
ndi.black_tophat(a, size=3, output=a)
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Comment by akahard2dj** [comment]
>https://github.com/scipy/scipy/blob/14142ff70d84a6ce74044a27919c850e893648f7/scipy/ndimage/morphology.py#L1794

in this part, when `output` variable gets in `grey_erosion()`, `input` data is changed.
if `output` in `grey_erosion()` is None, the problem is seems to be fixed.

```python
    if (size is not None) and (footprint is not None):
        warnings.warn("ignoring size because footprint is set", UserWarning, stacklevel=2)
    tmp = grey_dilation(input, size, footprint, structure, None, mode,
                        cval, origin)
    print('input_grey_dilation', input)
    # before code
    # tmp = grey_erosion(tmp, size, footprint, structure, output, mode,
    #                   cval, origin)
    tmp = grey_erosion(tmp, size, footprint, structure, None, mode,
                       cval, origin)
    print('input_grey_erosion', input)

    if tmp is None:
        tmp = output

    if input.dtype == numpy.bool_ and tmp.dtype == numpy.bool_:
        numpy.bitwise_xor(tmp, input, out=tmp)
    else:
        numpy.subtract(tmp, input, out=tmp)
    return tmp
```

issue script file
```python
import numpy as np
import scipy.ndimage as ndi

a = np.ones((3,3))
a[1,1] = 0
a=ndi.black_tophat(a, size=3, output=a)
print(a)
```

results
```
input_grey_dilation
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
input_grey_erosion
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
result
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]

```

**Comment by akahard2dj** [comment]
In this part, when `output` variable gets in `grey_erosion()`, `input` data is always changed.
But, problem was the case of `input` = `output`.
I have designed the solution by comparing `input` and `output`.

the results are always same.

```python
    if numpy.array_equal(input, output):
        tmp = grey_erosion(tmp, size, footprint, structure, None, mode,
                          cval, origin)
    else:
        tmp = grey_erosion(tmp, size, footprint, structure, output, mode,
                           cval, origin)
```
issue reproduce code
```python
import numpy as np
import scipy.ndimage as ndi

a = np.ones((3,3))
a[1,1] = 0
a=ndi.black_tophat(a, size=3)
print('result1')
print(a)

a = np.ones((3,3))
a[1,1] = 0
a=ndi.black_tophat(a, size=3, output=a)
print('result2')
print(a)

a = np.ones((3,3))
a[1,1] = 0
b=np.ones((3,3))
a=ndi.black_tophat(a, size=3, output=b)
print('result3')
print(a)
print(b)
```

results
```
result1
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]

result2
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]

result3
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]

```

**Comment by yuracpp** [comment]
thanks, the output is correct with this fix. 
BTW white_tophat has symmetric issue 

a = np.zeros((3,3))
a[1,1] = 1
print(ndi.white_tophat(a, size=3))
# [[0. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 0.]]
print(ndi.white_tophat(a, size=3, output=a))
# [[0. 0. 0.]
#  [0. 0. 0.]
#  [0. 0. 0.]]

**Comment by akahard2dj** [comment]
Yes, `white_tophat()` function has same problem.
I will fix them and PR.

**Comment by pv** [comment]
The problem is that these routines do not check if the output array overlaps in memory with the inputs. The right fix is `if np.may_share_memory(output, input): input = input.copy()` --- or some equivalent --- in these functions.
