### ISSUE TITLE
How can i use the ward method with the metric of correlation distance?

### ISSUE THREAD

**Issue by rickwith** [scipy/scipy#9569]
Hi,guys 
I am trying to using hierarchical clustering on fmri data, and i choose the correlation distance as metric, but i found that the ward method only accept Euclidearn distance, so can anyone give me an example to learn how to do this?

**Comment by rgommers** [comment]
@rickwith such usage questions are best asked on StackOverflow, or on the scipy-user mailing list. not a bug, so closing.

related question is gh-9585. it seems to me that we can extend Ward to squared Euclidean, but not sure beyond that - it's defined normally as using one of those two distance metrics.

**Comment by rickwith** [comment]
Ok, thanks a lot!
