### ISSUE TITLE
PPoly.from_spline not accepting new style spline

### ISSUE THREAD

**Issue by edwintye** [scipy/scipy#9571]
As documented, `PPoly.from_spline` takes a spline from either `splrrep` or a `BSpline` object. The issue is that splrep has been superseeded by the object-oriented classes based on `UnivariateSpline`.  Idealy, I would like the following to work (from the examples)

```python
from scipy.interpolate import LSQUnivariateSpline, PPoly
import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(-3, 3, 50)
y = np.exp(-x**2) + 0.1 * np.random.randn(50)
t = [-1, 0, 1]
spl = LSQUnivariateSpline(x, y, t)
PPoly.from_spline(spl)
```

yet I receive the following error

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-9c93321c4f9c> in <module>
----> 1 PPoly.from_spline(spl)

---> in from_spline(cls, tck, extrapolate)
   1288                 extrapolate = tck.extrapolate
   1289         else:
-> 1290             t, c, k = tck
   1291 
   1292         cvals = np.empty((k + 1, len(t)-1), dtype=c.dtype)

TypeError: 'LSQUnivariateSpline' object is not iterable
```

I think this is an easy fix because the data already exists in the object returned by the fit `spl._data[8]`, `spl._data[9]`, and `spl._data[5] for the knots and coefficients respectively.  So a defensive line like at the top of the function

```python
if isinstance(tck, scipy.interpolate.UnivariateSpline):
    tck = (tck._data[8], tck._data[9], tck._data[5])
``` 

should do the trick.

**Comment by ev-br** [comment]
> splrep has been superseeded by the object-oriented classes based on UnivariateSpline.

Not quite. `UnivariateSpline` is not recommended for use in new code, the recommendation is `BSpline`/`make_interp_spline` for interpolation, and `splrep` for fitting/smoothing.

**Comment by ev-br** [comment]
OK, two weeks, no follow-up or further comments. 
IMO this `if isinstance(tck, scipy.interpolate.UnivariateSpline)` dance belongs to the user code, and we should not add it. I fail to see a reason for mixing `UnivariateSplines` and `BSplines` in new code (and old code cannot have BSplines).  
I'm going to close this as a wontfix, feel free to reopen if needed.

**Comment by ev-br** [comment]
Good catch. That line is indeed misleading, both FITPACK interfaces are well into the "been there forever" territory. Care to submit a pull request with a clarification?

**Comment by edwintye** [comment]
Yup I can do that and check through the rest of the linked documentation. Will take a while though.
