### ISSUE TITLE
noprefix.h removal causing wheel build failures

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#9574]
gh-9561 removed the use of numpy's `noprefix.h` from master. It was then backported and caused wheel build failures: https://travis-ci.org/MacPython/scipy-wheels/builds/463460018. gh-9572 then reverted the change in `maintenance/1.2.x`. So current status is that master passes regular CI, but is breaking the wheel builds. We need to:
- figure out the problem and fix it
- understand why wheel build issues were not picked up in our regular CI.

**Comment by tylerjereddy** [comment]
Appveyor is [all-green](https://ci.appveyor.com/project/scipy/scipy-wheels/builds/20766366) for the problematic case and doesn't seem to use anything older than NumPy `1.10.4`.

Travis seems to fail around specific NumPy versions (and also can have different build vs. test NumPy versions, presumably for wheel install?; so max listed below):

Travis Failure NumPy max Versions: 1.8.2, 1.82., 1.8.2, 1.8.2, 1.8.2, 1.8.2, 1.8.2, 1.9.3, 1.8.2, 1.9.3, 1.9.3
Travis Success NumPy max Versions: 1.11.3, 1.11.3, 1.14.5, 1.14.5, 1.11.3, 1.14.5

**Comment by rgommers** [comment]
Yes I noticed that as well just now. Given that we're dropping older version in master, I'm tempted to do that first and then see if the problem is gone.

**Comment by akahard2dj** [comment]
I have read all view log.
The failure case(older verion of numpy) always shows that improper variable name included a broken unicode.

**Comment by mattip** [comment]
The file `npy_common.h` is missing [`#include <Python.h>`](https://github.com/numpy/numpy/blob/v1.15.4/numpy/core/include/numpy/npy_common.h#L11) in numpy before commit 6a61be6b67, which is contained in versions 1.11.0 and up. I could modify the PR to include `Python.h` before numpy stuff, which should fix it.

**Comment by rgommers** [comment]
Thanks for finding the cause Matti!

> I could modify the PR to include Python.h before numpy stuff, which should fix it.

Probably not useful at this point, because we've already decided to drop NumPy < 1.13.3 and there's a PR ready to actually do that.

**Comment by rgommers** [comment]
this was indeed fixed by gh-9561, closing
