### ISSUE TITLE
Request: Method to list parameters of distributions

### ISSUE THREAD

**Issue by adam-erickson** [scipy/scipy#9575]
I would like to request a generic method to list the parameters of distributions. In R, this is possible with this:

`formals(stats::rbeta)`

This is helpful for user interfaces that wrap the distributions.

**Comment by adam-erickson** [comment]
Thank you, Warren! That would make a nice built-in convenience method.

**Comment by WarrenWeckesser** [comment]
You are not the first to ask for this: [Getting the parameter names of scipy.stats distributions](https://stackoverflow.com/questions/30453097/getting-the-parameter-names-of-scipy-stats-distributions)

**Comment by adam-erickson** [comment]
Yes, I'm the one that upvoted the answer at that link : ) There is only one issue with your solution, which is that discrete distributions do not have a scale parameter. So, one would need to add a check to see whether the distribution name is in `scipy.stats._discrete_distns._distn_names` or `scipy.stats._continuous_distns._distn_names` and conditionally return an answer. I will add that now.

**Comment by rgommers** [comment]
Given that the target audience is very narrow ("user interfaces that wrap the distributions") and there's now a documented solution here and on StackOverflow, I don't think it's warranted to add this to our public API.

**Comment by mdhaber** [comment]
Although there is some interest in having a function like this, it looks like it is not yet strong enough to add to our public API. If this changes in the future, we can certainly reconsider. In the meantime, the solution posted here and on SO will suffice. Thanks for the suggestion, @adam-erickson; it looks like your post on SO has helped others.
