### ISSUE TITLE
incorrect behavior of rank_filter 

### ISSUE THREAD

**Issue by yuracpp** [scipy/scipy#9578]
It is similar to issue #9553. rank_filter function gives wrong result if input and output parameters are the same.

### Reproducing code example:
```
import numpy as np
import scipy.ndimage as ndi

a = np.zeros((3,3))
a[:,0] = 1
print(ndi.rank_filter(a, rank=6, size=3, mode='constant'))
print(ndi.rank_filter(a, rank=6, size=3, mode='constant', output=a))

[[0. 0. 0.]
 [1. 1. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
```

### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
In general: don't do that. A safety for preventing this would be useful, but it's pretty clear why this fails.

**Comment by yuracpp** [comment]
i thought, that it is logical for a large data to optimize memory allocation (where it possible) like
numpy.maximum(x1, x2, out=x1)
instead of
x1 = numpy.maximum(x1, x2)
maybe in case of rank_filter such optimization is not possible but still user has right to hope on miracle and to use an output equal to input

**Comment by akahard2dj** [comment]
This issue is same behavior #9567.
The main problem #9567 is all of variables (result(return value), `output`, `input`) is same environment.
@rgommers already mentioned above, In general this is not safety for using. 
How about dealing with this problem?

**Comment by yuracpp** [comment]
here is an example that demonstrate efficiency of using input as output in grey_dilation function

import numpy as np
import scipy.ndimage as ndi

data = np.zeros((1000,1000,1000), np.double)
ndi.grey_dilation(data, size=3, output=data)
del(data)
data = np.zeros((1000,1000,1000), np.double)
data = ndi.grey_dilation(data, size=3)

![mem](https://user-images.githubusercontent.com/33983807/49748155-3ee81280-fca5-11e8-8559-21442eb7e8b7.png)

**Comment by pv** [comment]
Closing as duplicate of #9553 --- these are the same problem, which probably is in most ndimage functions.
