### ISSUE TITLE
scipy.sparse.random using large amount of memory generating matricies

### ISSUE THREAD

**Issue by leecball** [scipy/scipy#9583]
Hello Scipy team!

When creating random sparse matrices, Python seems to run out of memory, even when there seems to be more than enough memory available to initialize the matrix. For example:

### Reproducing code example:

```python3
from scipy import sparse

def main():
    n = 10000
    m = n
    matrix = sparse.random(n, m, density=0.2, format='csr').astype('bool')

    mem = str(sparse_memory_usage(matrix))
    print(mem + ' bytes used by csr matrix')


# Credit for this function to: https://stackoverflow.com/a/43682143/2873090
def sparse_memory_usage(mat):
    try:
        return mat.data.nbytes + mat.indptr.nbytes + mat.indices.nbytes
    except AttributeError:
        return -1


main()
```

### Error message:
At `n = 10,000` Python can finish, although it takes a while and the CSR matrix uses 100mb. If scipy is using C bools weighing in at 1 byte each, shouldn't this matrix be much much smaller?

```
~/workspace/sealab/src$ free -h; time python3 main.py
              total        used        free      shared  buff/cache   available
Mem:           11Gi       3.3Gi       1.9Gi       412Mi       6.4Gi       7.7Gi
Swap:            0B          0B          0B
100040004 bytes used by csr matrix

real    0m39.423s
user    0m38.779s
sys     0m1.388s
```

At `n = 100,000` the interpreter throws a memory error while generating the sparse matrix:

```
~/workspace/sealab/src$ free -h; time python3 main.py
              total        used        free      shared  buff/cache   available
Mem:           11Gi       3.1Gi       2.0Gi       580Mi       6.6Gi       7.7Gi
Swap:            0B          0B          0B
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    main()
  File "main.py", line 10, in main
    matrix = sparse.random(n, m, density=0.2, format='csr').astype('bool')
  File "/home/cat/workspace/sealab/.env/lib/python3.6/site-packages/scipy/sparse/construct.py", line 779, in random
    ind = np.empty(k, dtype=tp)
MemoryError

real    0m0.172s
user    0m0.324s
sys     0m0.510s
```

With many gigabytes of memory free, even if random is storing this as a COO of floats that are casted to bools, should it still be hitting a memory error? Or is there more expensive things happening the background I'm not considering?

### Scipy/Numpy/Python version information:
```
1.1.0 1.15.4 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
```

### System info:
```
$ uname -a
Linux rextop 4.18.0-10-generic #11-Ubuntu SMP Thu Oct 11 15:13:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic

$ python3 --version
Python 3.6.7
```

Please let me know if you need any further info, or if there's any way I should further debug this issue! :woman_technologist: Thank you! :smiley:

**Comment by zerothi** [comment]
This is perhaps not so surprising.

To repeat what you have already stated:
`scipy.sparse` first creates the random matrix with (default) `numpy.float64` data-type. I.e. you are trying to allocate `1e5**2 * 0.2 * 8 / 1024 ** 3 = 14.9` GB of memory before changing to the boolean data-type. Secondly, `sparse.random` starts by creating the matrix in `coo` format (which is a bit heavier in terms of memory requirements. So there are multiple things against you.

If you want to generate these large matrices you would be better of copying the `random` method and implement your `bool` random generator in an iterative manner.

**Comment by leecball** [comment]
@zerothi ah, I understand, thanks for helping explain why that uses the amount of memory it does! That makes sense now.

I'll close this issue. If I can find a little spare time, I might try to implement support for the bool data type in that. scipy.sprase.random function. 👩‍💻 

Thank you again, and happy holidays! ☃️
