### ISSUE TITLE
Outdated value for scipy.constants.au

### ISSUE THREAD

**Issue by japagetw** [scipy/scipy#9587]
My issue is about an outdated value for scipy.constants.au.
The value returned is 149597870691.0.  The correct value
is 149597870700.0.  See IAU 2012 Resolution B2 and
https://www.iau.org/public/themes/measuring/ .

### Reproducing code example:

```
from scipy.constants import au
print(au)
```

### Scipy/Numpy/Python version information:
 1.2.0rc2 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)

**Comment by rgommers** [comment]
Thanks for the report @japagetw. Value updated in gh-9588

**Comment by japagetw** [comment]
Ralf,

Thanks!

-- Jim Paget
