### ISSUE TITLE
scipy.interpolate.interp1d with kind=“previous” doesn't extrapolate as expected

### ISSUE THREAD

**Issue by JulienBERNU** [scipy/scipy#9591]
````
import numpy as np
from scipy.interpolate import interp1d

a = np.arange(10)
b = a + 100

iterp = interp1d(a, b, kind="previous", bounds_error=False)
print(iterp([-1,-2,5,8,12,25]))
# [nan nan  105.  108. nan nan]
````
First two `nan` values makes sense, but last two don't since a previous value is available.

Now if I use extrapolate:
````
iterp = interp1d(a, b, kind="previous", fill_value="extrapolate")
print(iterp([-1,-2,5,8,12,25]))
# [100. 100. 105. 108. 109. 109.]
````
The last two `109.` make sense but the first two `100.` don't since there is no previous value.

I believe the result should be the intuitive `[nan  nan  105.  108.  109.  109.]`

Issue reported on stackoverflow too, if anyone wants to add comments there...
https://stackoverflow.com/questions/53753562/scipy-interpolate-interp1d-with-kind-previous-doesnt-extrapolate-as-expected

### Scipy/Numpy/Python version information:

1.1.0 1.15.0 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)

**Comment by XtremeGood** [comment]
Sorry if I 'm wrong but to what I understand interpolation can only be done for a point in [0,9] which is the range of a.Rest is extrapolation beyond this range.

**Comment by XtremeGood** [comment]
I 'm interested in fixing this bug .I would definitely try to remove this bug if I can understand what you want.To what I understand previous is  your nearest neighbor extrapolation/interpolation in which nearest neighbor is checked(therefore beyond your [0,9] is 12 or 25 which first of all cannot be interpolated so result goes to nan which is your fillvalue and talking about extrapolate it is giving you the value of nearest neighbor of -1,-2 which correspond to a=0 and is b =100) .If I 'm wrong please tell what your desired output is so that I can add a code which would act accordingly.I think it's  badly termed.

**Comment by JulienBERNU** [comment]
I just think if you use "previous" for interpolation, it should use "previous" for extrapolation too, not "nearest". Now here there is no previous value to extrapolate so instead of silently defaulting back to "nearest" it should either extrapolate to `nan` or `-inf` (or raise an exception).

**Comment by XtremeGood** [comment]
That is why I wrote badly named.

**Comment by XtremeGood** [comment]
Thanks:)

**Comment by AtsushiSakai** [comment]
I confirmed this issue still exists in the latest v1.5.2

**Comment by AtsushiSakai** [comment]
I've been trying to fix this problem for the past week, I think I can fix it.
But I am not sure if I should fix it as has been suggested now...

Current implementation just fill requested points outside of the data range with `fill_value` whichever `kind` is used.
And, if `fill_value` is "extrapolate", it just fill requested points outside of the data range with first and last value of `y` whichever `kind` is used.
This strategy looks straightforward for me.
I think if I change the `fill_value` behaviors based on which `kind` is used, that might make some users be confused and break backward compatibilities.

So, I think we should update docstring or add notes to explain this strategy and workarounds for it.
(For example, there is a workaround for the first issue:
```
axis = -1
iterp = interp1d(a, b, kind="previous", axis=axis,
                 bounds_error=False, fill_value=(np.nan, b.max(axis=axis)))
print(iterp([-1,-2,5,8,12,25]))
# [ nan  nan 105. 108. 109. 109.]
```)

Does someone have any comments for this?

**Comment by ev-br** [comment]
Apologies for this slipping under the radar @AtsushiSakai . I think your workaround is great! 
Maybe the right thing to do is to actually implement your workaround as the strategy for `kind="previous"` and `fill_value="extrapolate"` and change the internal state of the extrapolation switch in the constructor.

A likely similar issue exists for `kind="previous".`
