### ISSUE TITLE
column slicing of csc_matrix is two times slower than that of csr_matrix.

### ISSUE THREAD

**Issue by hasoya** [scipy/scipy#9604]
[Official document](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html) says the csc_matrix performs column slicing efficiently. However, in my experiment, column slicing of csc_matrix is two times slower than that of csr_matrix. Why does it happen? Thank you.

### Reproducing code example:

This is my experiment result.

![image](https://user-images.githubusercontent.com/20637498/50064402-59197780-01f4-11e9-9051-ed2e50e643f4.png)

And, this is the code.

```python
import scipy.sparse as sp

a = sp.random(100, 10000)

a_csr = a.tocsr(copy=True)
a_csc = a.tocsc(copy=True)

print(type(a_csr), type(a_csc))

%timeit -n 10000 a_csc[:, 10]
%timeit -n 10000 a_csr[:, 10]
```

### Scipy/Numpy/Python version information:
 1.1.0 1.15.3 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)

**Comment by perimosocordiae** [comment]
This is a quirk of our current code for handling CSC slicing, which essentially does: `mat.T[slices].T`

This allows us to share code with the CSR implementation, but does come with the cost of two transpose operations.

I have a PR that should fix this to some degree at gh-7827.

**Comment by hasoya** [comment]
Thank you for your answer and PR. As your PR seems to be merged, I close this issue.

Thank you so much.

**Comment by perimosocordiae** [comment]
With current master, the results are indeed more in line with our expectations:

```python
In [1]: import scipy

In [2]: scipy.__version__
Out[2]: '1.3.0.dev0+47976a8'

In [3]: import scipy.sparse as sp

In [4]: a = sp.random(100, 10000)

In [5]: a_csr = a.tocsr(copy=True)

In [6]: a_csc = a.tocsc(copy=True)

In [7]: %timeit a_csr[:, 10]
64.9 µs ± 1.82 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [8]: %timeit a_csc[:, 10]
57.2 µs ± 2.54 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
