### ISSUE TITLE
SyntaxError: Non-ASCII character '\xe2' in file scipy/stats/_continuous_distns.py on line 3346, but no encoding declared

### ISSUE THREAD

**Issue by dimrozakis** [scipy/scipy#9606]
I get syntax errors due to source code encodings when importing scipy 1.2.0. The error only seems to occur if `pyc` files are missing.

The issue originates from https://github.com/scipy/scipy/blob/v1.2.0/scipy/stats/_continuous_distns.py#L3345. The dash/hyphen used there isn't a regular dash/hyphen, but instead the line reads as `'    pp. 1\xe2\x80\x9313, 1997.\n'`

### Reproducing code example:

```Dockerfile
FROM python:2.7

RUN pip install --no-cache-dir scipy

# Without the following line, I can't reproduce the problem.
RUN find /usr/local/lib/python2.7/site-packages/scipy/ -name '*.pyc' -delete

RUN python -c "import scipy.stats"
```

### Error message:

```
Step 1/4 : FROM python:2.7
 ---> f67e752245d6
Step 2/4 : RUN pip install --no-cache-dir scipy
 ---> Using cache
 ---> e8adb88b0f15
Step 3/4 : RUN find /usr/local/lib/python2.7/site-packages/scipy/ -name '*.pyc' -delete
 ---> Running in 6e46e320f24d
Removing intermediate container 6e46e320f24d
 ---> ed5be7afd25a
Step 4/4 : RUN python -c "import scipy.stats"
 ---> Running in 8c8ea36e3284
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/scipy/stats/__init__.py", line 367, in <module>
    from .stats import *
  File "/usr/local/lib/python2.7/site-packages/scipy/stats/stats.py", line 173, in <module>
    from . import distributions
  File "/usr/local/lib/python2.7/site-packages/scipy/stats/distributions.py", line 13, in <module>
    from . import _continuous_distns
  File "/usr/local/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py", line 3345
SyntaxError: Non-ASCII character '\xe2' in file /usr/local/lib/python2.7/site-packages/scipy/stats/_continuous_distns.py on line 3346, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
('1.2.0', '1.15.4', sys.version_info(major=2, minor=7, micro=15, releaselevel='final', serial=0))
```

**Comment by rgommers** [comment]
Grr, this is the second time this happened. We really need a structural fix to our CI to catch this.

Thanks for the report @dimrozakis.

@tylerjereddy guess we'll need a 1.2.1 (after the CI fix) .... :(

**Comment by andyfaff** [comment]
What would be the test for this?

**Comment by larsoner** [comment]
Use `grep` or some other `bash` util to get a list of py files with non-ascii chars; get a list of files with `# -*- coding: utf-8 -*-` at the top; take the first list minus the second and you have the problematic ones? This or something similar should be `bash`-able on one of the Travis builds. I can take a stab at it if nobody sees a cleaner way.

**Comment by ev-br** [comment]
If the error shows up at import time for users, can we trigger it on CI?

**Comment by larsoner** [comment]
> If the error shows up at import time for users, can we trigger it on CI?

I suspect it will only happen on 2.7, which we don't test now. (We should probably still fix it, though.) I wrote a little BASH solution, will open a PR to see the output.

**Comment by rodriguezsergio** [comment]
Thank you for working on this so quickly. I was going to create the same issue.

**Comment by MuellerSeb** [comment]
There is even a second one:

    with open("_continuous_distns.py") as fp:
        for i, line in enumerate(fp):
            if "\xe2" in line:
                print i, repr(line)
`
Gives:

    3344 '    pp. 1\xe2\x80\x9313, 1997.\n'
    4006 "                              'evaluations. Use Zolotarev\xe2\x80\x99s method instead).',\n"

The first problem is a EN DASH (– - \xe2\x80\x93) and the second one is a U+2019 RIGHT SINGLE QUOTATION MARK. Both could be replaced with "-" and "'" resp.

**Comment by larsoner** [comment]
@dimrozakis @MuellerSeb I implemented fixes in #9615, feel free to give it a try

**Comment by yerzhik** [comment]
SyntaxError: Non-ASCII character '\xc3' in file /usr/local/lib/python2.7/dist-packages/scipy/stats/_continuous_distns.py on line 3383, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

python -c "
with open('/usr/local/lib/python2.7/dist-packages/scipy/stats/_continuous_distns.py') as fp:
    for i, line in enumerate(fp):
        if '\xc3' in line:
            print i, repr(line)
"
3381 '    This distribution is also known as the Fr\xc3\xa9chet distribution or the\n'

**Comment by rgommers** [comment]
@yerzhik that was already fixed, hence this issue was closed 6 days ago. the fix will be included in scipy 1.2.1

**Comment by yerzhik** [comment]
> @yerzhik that was already fixed, hence this issue was closed 6 days ago. the fix will be included in scipy 1.2.1

Oh, now I see, it will be included next version, thank you!

**Comment by victorteran93** [comment]
Hi, I am having this problem in a pre production enviroment, some idea to fix and deploy today?

**Comment by victorteran93** [comment]
I commit the file without the - in that line and works for me, then using the console i use 
```heroku run cp script.py /path/to/script.py```

**Comment by loisaidasam** [comment]
Alternatively you can checkout the repo at tag `1.2.0` and cherry-pick the relevant commits from this PR https://github.com/scipy/scipy/pull/9615:

```
git clone git@github.com:scipy/scipy.git
cd scipy
git checkout v1.2.0
git cherry-pick 4a8a35f2c27be9f209cfc6f347e7a57a4a62e693
git cherry-pick e87cd85f440f02aca4d75fcccfb4b3d3782ca301
```

I think there were a few conflicts I had to manually resolve, but it seems to be working OK.

**Comment by rasputin1917** [comment]
Hi, do you know if that error exists in previous versions of scipy, for python 2.7?

**Comment by loisaidasam** [comment]
@rasputin1917 it does for me (I'm on `2.7`)
