### ISSUE TITLE
document policy for numpy/python version support

### ISSUE THREAD

**Issue by rgommers** [scipy/scipy#9610]
In addition to documenting what SciPy does now, it would be very useful to try to align this between core packages as @tacaswell pointed out in his comments on gh-9582. See that PR for initial discussions.

The documentation part is actually mostly being done right now by @pvanmulbregt in gh-9500. We can extend that a little bit further. The aligning with other packages should be moved to the mailing list (or multiple ...).

**Comment by tacaswell** [comment]
A very short version: I am advocating for a time-based criteria for dropping python + numpy support. ex "We will support all minor releases initially released in the N months before our intended release date".   

The biggest advantage of this is that there is no ambiguity or judgement to implement which makes it easy to implement and plan against. 

The downside of this is that we will eventually run ahead of the 'stable' linux distributions, I think that is mitigated by user-space python.  I would also like to generalize the arguments in https://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html to argue against pinning upstream support to what versions are in down-stream distributions.

**Comment by rgommers** [comment]
Thanks @tacaswell. I like the argument made in that blog post. We will burden some users more, however we gain in not having maintainers do boring work. There will be some objections I think, but I see the advantage.

The time periods for Python and NumPy probably should be different, given that Python releases a minor version every 1.5 years on average, and NumPy every 6 months. Looking at now for example, we cannot really drop Python 3.5 yet (3.25 years old), but did drop 3.4 (4.5 yrs old) which is fine. Python is also a little harder to upgrade.

So reasonable times probably would be:
- Python: 4 years
- NumPy: 2 or 2.5 years

**Comment by tacaswell** [comment]
We should schedule something at scipy to talk about this.  I will be there from tutorials to sprints.

**Comment by rgommers** [comment]
Good idea @tacaswell.  I haven't made a detailed plan yet, but pretty sure I am there as well. We could make it a BoF.

**Comment by asmeurer** [comment]
FWIW for SymPy we drop Python versions when they reach their EOL, that is, CPython itself stops supporting them. https://github.com/sympy/sympy/wiki/Python-version-support-policy. Though this apparently has meant we drop Python 2 later than everyone else.  According to https://devguide.python.org/#status-of-python-branches, Python versions reach EOL 5 years after their first release date.

If anything this is should be an upper bound for any project. No one can reasonably argue that a library should continue to support a Python version after that version of Python itself doesn't even receive security updates.

**Comment by sethtroisi** [comment]
@rgommers is the documentation in #9500 and [NEP 29 - Recommend Python and Numpy version support](https://numpy.org/neps/nep-0029-deprecation_policy.html) sufficient to close this? Is there open work in this issue?

**Comment by rgommers** [comment]
Yes, thanks - we're all good here, closing.
