### ISSUE TITLE
cdist doesn't align DataFrame columns

### ISSUE THREAD

**Issue by MaxGhenis** [scipy/scipy#9616]
`cdist` currently treats `DataFrame`s as arrays, ignoring column names. If passing `DataFrame`s with the same columns but in a different order, this will cause unexpected results. Aligning the columns would be more intuitive IMO.

```
from scipy.spatial.distance import cdist
df = pd.DataFrame({'a': [0, 0],
                   'b': [1, 1]})
# Zero distance from df to itself.
cdist(df, df)
# array([[0., 0.],
#        [0., 0.]])
# But switching the columns creates distance.
df2 = df[['b', 'a']]
cdist(df, df2)
# array([[1.41421356, 1.41421356],
#        [1.41421356, 1.41421356]])
```

### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.15.4 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
Hi @MaxGhenis, SciPy doesn't know anything about pandas dataframes. Many functions may work because they accept `array_like`, but it's up to the user to deal with putting data in in the right format if their format is out of order. We will not add special handling for pandas here.

**Comment by MaxGhenis** [comment]
Thanks for the quick response. I'm surprised about the lack of integration given pandas is featured on scipy.org. 
![image](https://user-images.githubusercontent.com/6076111/50269181-5bd9bf80-03e2-11e9-89e0-28512119e400.png)

Would a note about this be worthwhile on the `cdist` page? This took me a good while to figure out when my distances looked off.

**Comment by rgommers** [comment]
Note that scipy.org is not the website for SciPy the library, but for SciPy the ecosystem. A subpage (http://scipy.org/scipylib/) is about this library.

> Would a note about this be worthwhile on the cdist page?

I'm afraid not. We have about 1600 functions, and people could try passing in pandas data structures to all of them. 

Adding a note on pandas would be appropriate in some tutorials perhaps, not sure what the best place for that would be. Maybe http://scipy.github.io/devdocs/tutorial/general.html should explain what `array_like` means, and what that implies for pandas/dask/... arrays. Most users won't see it before running into this, but then at least we have somewhere to point to. Or we point to the NumPy docs; this may be helpful: https://stackoverflow.com/questions/40378427/numpy-formal-definition-of-array-like-objects
