### ISSUE TITLE
siegelslopes is not available on Windows. 

### ISSUE THREAD

**Issue by tg12** [scipy/scipy#9631]
My issue is about ...siegelslopes is not available on Windows. Same code runs fine on Ubuntu. 

### Reproducing code example:

```
Sample code to reproduce the problem
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```
module 'scipy.stats.mstats' has no attribute 'siegelslopes'
Traceback (most recent call last):
  File ".\<<REMOVED>>.py", line 584, in main_trade_function
    low_prices_slope, low_prices_intercept = stats.mstats.siegelslopes(
AttributeError: module 'scipy.stats.mstats' has no attribute 'siegelslopes'

<class 'AttributeError'>

### Scipy/Numpy/Python version information:

Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
>>>

**Comment by ilayn** [comment]
Hi @tg12 can you try importing it as a standalone object via 

```python
from scipy.stats.mstats import siegelslopes
```

**Comment by tg12** [comment]
from scipy.stats.mstats import siegelslopes
ImportError: cannot import name 'siegelslopes' from 'scipy.stats.mstats' (C:\Users\Barry\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\stats\mstats.py)

Same error. The same code works fine on Ubuntu.

**Comment by ilayn** [comment]
Then probably something went wrong with your windows installation. If you can please reinstall by first removing and then make sure that your ubuntu installation version is also up to date.

**Comment by tg12** [comment]
Sure, It's all at the very latest code. I installed both using pip.

**Comment by rgommers** [comment]
doesn't look like a pip issue, but like being in the wrong environment or something. `siegelslopes` is in 1.2.0, and `pip install scipy --upgrade` will install 1.2.0. So closing this. 

@tg12 feel free to keep commenting here if you need help sorting out your install issue (we'll need more details on how you installed Python, and if you install with pip add the `-v` flag for verbose output to see what's happening).
