### ISSUE TITLE
Add median absolute deviation to scipy.stats

### ISSUE THREAD

**Issue by Kitchi** [scipy/scipy#9635]
I would be willing to contribute a median absolute deviation function to scipy.stats, if there is a broader interest. There are other robust measures of variance (`tvar` and `iqr`) and I think the `mad` function would complement these nicely.

**Comment by rgommers** [comment]
Thanks @Kitchi. Did you notice that this exists in statsmodels: https://www.statsmodels.org/dev/generated/statsmodels.robust.scale.mad.html ? In general we prefer not to have duplication between `scipy.stats` and `statsmodels`.

**Comment by josef-pkt** [comment]
IMO, `mad` is a basic statistic that would fit in scipy.stats to join `iqr` in spite of any duplication.

as background: mad in statsmodels was initially a supporting function for RLM, but then converted to standalone usage after users wanted to use it directly. I have seen packages, AFAIR, that only used `mad`  out of all functionality in statsmodels.robust, so there is likely a wider demand just for this function. 
statsmodels `mad` does not have (yet) a nan/missing option, which is not needed when used in support of RLM and similar.

I guess duplication would go too far if we want to add more of those robust statistics to scipy.stats, e.g. statsmodels has also measures for robust skewness and kurtosis, and other, optimization based robust mean and variance estimators.

**Comment by Kitchi** [comment]
Yeah I was of the same mind as @josef-pkt - I've needed the `mad` function many times in my code, and so far that's the only function I've repeatedly needed from statsmodels. So I figured since all the other "common" statistical estimators can be found in either SciPy or NumPy, this would also belong there.

**Comment by rgommers** [comment]
Okay, fair enough. 

> statsmodels mad does not have (yet) a nan/missing option,

good point, would be useful for `mad` to have a `nan_policy` keyword

**Comment by Kitchi** [comment]
I've submitted the PR, but I'm not sure how to deal with the axis selection. The "naive" way to do it (by just passing on the axis selection to `np.median`) will only work for square arrays, or where every axis is the same length. I'm unable to think of a way to get it working for the general case at the moment.

**Comment by rgommers** [comment]
Thanks @Kitchi, I'll have a look at your PR. Let's continue the discussion there.

**Comment by rlucas7** [comment]
@rgommers This issue can be closed, PR was merged.

**Comment by rgommers** [comment]
thanks, closing
