### ISSUE TITLE
CSR matrix row slicing produces different result on master comparing with 1.2.0

### ISSUE THREAD

**Issue by qinhanmin2014** [scipy/scipy#9639]
```
import numpy as np
import scipy.sparse as sp
X = sp.csr_matrix(np.ones((3, 3)))
print(X.indices)
# [0 1 2 0 1 2 0 1 2]
Xt = X[np.arange(3)]
print(Xt.indices)
# scipy 1.2.0 [2 1 0 2 1 0 2 1 0]
# scipy master [0 1 2 0 1 2 0 1 2]
```
Not sure this is an issue but it causes the CI failure in scikit-learn (https://github.com/scikit-learn/scikit-learn/issues/12882), and I'm unable to find related doc about the change.

**Comment by rgommers** [comment]
I'm getting `[2 1 0 2 1 0 2 1 0]` for both master, 1.2.0 and 1.1.0. can someone else try?

**Comment by ilayn** [comment]
I get `[0 1 2 0 1 2 0 1 2]` from master.

**Comment by perimosocordiae** [comment]
Yeah, it's almost certainly that PR. Typically we don't guarantee a consistent ordering for sparse matrix internals, so long as the resulting matrix is equivalent, so I'm not sure this is a bug.

That said, I'm not sure why the ordering would be non-deterministic. That may be worth looking into a bit further.

**Comment by ilayn** [comment]
might be a numpy change too

**Comment by qinhanmin2014** [comment]
Thanks, I'll provide my version info here.
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
# 1.3.0.dev0+5539300 1.17.0.dev0+3abb5f8 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
```
I'm using Ubuntu 18.04.1 LTS
```
platform.platform()
# 'Linux-4.15.0-43-generic-x86_64-with-debian-buster-sid'
```

> Yeah, it's almost certainly that PR. Typically we don't guarantee a consistent ordering for sparse matrix internals, so long as the resulting matrix is equivalent, so I'm not sure this is a bug.

I agree that this might be a misuse from scikit-learn (i.e., we use row slicing to scramble the indices in our test). We'll try to fix it in scikit-learn if you think this change is reasonable (there's already a PR https://github.com/scikit-learn/scikit-learn/pull/12890).

**Comment by ilayn** [comment]
Ah nice. Then I'll bet on a C/Fortran ordering/reshaping since it is suspiciously backwards.

**Comment by sethtroisi** [comment]
Was this fixed by https://github.com/scipy/scipy/pull/11265?

**Comment by perimosocordiae** [comment]
Not fixed by that PR, but I agree that this can be closed. The scikit-learn issue has been resolved on their end, and the consensus seems to be that the scipy behavior isn't a bug.
