### ISSUE TITLE
arpack returns singular values in ascending order

### ISSUE THREAD

**Issue by gykovacs** [scipy/scipy#9643]
My issue is about documentation: arpack based svds routine returns singular values in ascending order which is not indicated in the documentation, but is an important issue as many conventional techniques return eigenvalues and singular values in descending order and one assumes this behavior by default. arpack documentation clearly states that ascending order is implemented:

https://www.caam.rice.edu/software/ARPACK/UG/node136.html#SECTION001210000000000000000

My proposal is adding some remark to the documentation highlighting the ascending order.

### Reproducing code example:

```
size=(8, 7)
_, s, _= svds(np.random.normal(size= size), k= 5)
print(s)
```

output

```
[1.18808116 2.08272636 2.29151233 2.89423407 5.0980869 ]
```

### Scipy/Numpy/Python version information:

1.1.0 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)

**Comment by gykovacs** [comment]
If anyone confirms that updating the documentation is reasonable, I'm happy to take and do this.

**Comment by ilayn** [comment]
If the ordering is strictly reversed then we should return the inverse orders of the lists instead of documenting this. It would be in accordance with the dense versions. 

It shouldn't be too much of a work to switch the index ordering but I am not sure if this is a compatibility breaking change. @rgommers @perimosocordiae thoughts?

**Comment by gykovacs** [comment]
@mdhaber Yes, the same is true about eigs and eigsh, basically every eigen/singular value call made to arpack.

@ilayn Yeah, I agree, reversing the results would be better, but I'm afraid it is a decent change. On the other hand, the reason why I looked into this is that a bug in sklearn was found: sklearn relied on scipy svds returning singular values in descending order, which was false. It can happen that there are further bugous codes built on the svds and eigs calls assuming the descending order but not yet recognized.

Anyways, if someone confirms that reversing the output or documenting the current status is the proper solution, I'm happy to implement it.

**Comment by perimosocordiae** [comment]
I'd much rather have the docs note that the order of eigenvalues is not guaranteed. This gives us more flexibility to choose different underlying implementations in the future, but also reflects the current state of things:

```python
In [14]: svds(x, k=5)[1]
Out[14]: array([1.26379016, 1.72120995, 2.25597658, 2.81876515, 5.46984484])

In [15]: svds(x * 1j, k=5)[1]
Out[15]: array([5.46984484, 2.81876515, 2.25597658, 1.72120995, 1.26379016])
```

**Comment by gykovacs** [comment]
@perimosocordiae Absolutely makes sense. Shall I start put the note (and maybe some examples like yours) in the docs?

**Comment by lobpcg** [comment]
I added the comment in https://github.com/scipy/scipy/pull/10830 to resolve this issue
