### ISSUE TITLE
pearson correlation formula is incorrectly expressed

### ISSUE THREAD

**Issue by spenot09** [scipy/scipy#9655]
The denominator in:
![image](https://user-images.githubusercontent.com/34069273/50704572-c4b27000-104f-11e9-868a-53dad26b9806.png)

is not equivalent to the denominator in the referenced website:
![image](https://user-images.githubusercontent.com/34069273/50704599-deec4e00-104f-11e9-8ef7-828fcc92ffef.png)

**Comment by matthew-brett** [comment]
Sorry - it's been a long day - where is the difference?

**Comment by ev-br** [comment]
In the docs for scipy 1.2.0, https://docs.scipy.org/doc/scipy-1.2.0/reference/generated/scipy.stats.pearsonr.html
which is the current released version, the formula is correct, as it has two summation symbols in the denominator.

So, apparently, the issue has been fixed. Thanks for reporting it anyway, @spenot09

**Comment by spenot09** [comment]
Ah perfect, my apologies and thank you!
