### ISSUE TITLE
Version 1.2.0: undefined symbol: ztpqrt2_ on RedHat-6

### ISSUE THREAD

**Issue by UnitedMarsupials** [scipy/scipy#9657]
### Reproducing code example:

```
from scipy import linalg
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/prod/pfe/local/lib/python3.6/site-packages/scipy/linalg/__init__.py", line 207, in <module>
    from ._decomp_update import *
  File "_decomp_update.pyx", line 1, in init scipy.linalg._decomp_update
ImportError: /prod/pfe/local/lib/python3.6/site-packages/scipy/linalg/cython_lapack.cpython-36-x86_64-linux-gnu.so: undefined symbol: ztpqrt2_
```

### Scipy/Numpy/Python version information:
```
1.2.0 1.15.4 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
```

With scipy-1.1.0 things work fine. Presumably, the new problem is due to overly old lapack (atlas-3.8.4), which does not provide the `ztpqrt2_`.

However, that's the last version available on RedHat-6.

Also, the module compiled (by pip) and installed. Perhaps, it should not fail from the missing symbol -- unless something actually tries to use it?

**Comment by ilayn** [comment]
Hi @UnitedMarsupials in this case something is actually trying to use it which is `qr` update functions upon import since otherwise linalg module can't be imported.

We recently and finally bumped our minimum required LAPACK version to something mildy newer 3.4.1 (also from 2012, about a year later than atlas 3.8.4). Hence unfortunately you should get a newer vanilla version of BLAS/LAPACK libraries.

**Comment by tylerjereddy** [comment]
I've made a note that we may want to backport if we get a fix at compile time?

**Comment by rgommers** [comment]
> I've made a note that we may want to backport if we get a fix at compile time?

Possibly. Such things are usually tricky to make very robust, so let's see after we have one. I'll open a new issue for it.

**Comment by UnitedMarsupials** [comment]
> Hi @UnitedMarsupials in this case something is actually trying to use it which is qr update functions upon import since otherwise linalg module can't be imported.

This is not, what I meant. And you know, that it is not, what I meant...

**Comment by ilayn** [comment]
I don't know what you meant.

**Comment by UnitedMarsupials** [comment]
Unless a Python script calls the ztpqrt2-function - and it is a [rather obscure one](http://www.netlib.org/lapack/explore-html/da/dce/ztpqrt2_8f.html) - it should not fail to load the whole package.

**Comment by rgommers** [comment]
> Unless a Python script calls the ztpqrt2-function - and it is a rather obscure one - it should not fail to load the whole package.

We don't really want to go that way. We have some requirements for building SciPy, and if they aren't met then you cannot use SciPy. We should just fail in a more obvious way, i.e. not complete the build at all. Supporting outdated libraries by moving imports around is fragile and not worth the effort.
