### ISSUE TITLE
`scipy.optimize.minimize(method='COBYLA')` not threadsafe

### ISSUE THREAD

**Issue by achimgaedke** [scipy/scipy#9658]
I tried to run multiple optimisations with the cobyla method at the same time. Due to the asyncio based  communication with the modelling/calculation framework, I decided to use a multithreaded approach.

Platform/Distribution
* Python3.7.2/scipy-1.1.0  via conda on Debian testing
* Python3.7.2/scipy-1.1.0 via apt on Debian testing

In order to showcase my problems, I slimmed down the code to this example:
```
import concurrent.futures
import time
import scipy.optimize

def objective1(x):
    print(x, "1")
    time.sleep(0.1)
    return x[0]**2

def objective2(x):
    print(x, "2")
    time.sleep(0.1)
    return (x[0]-1)**2

min_method = "COBYLA"

def minimizer1():
    return scipy.optimize.minimize(objective1,
                                   [0.0],
                                   method=min_method)

def minimizer2():
    return scipy.optimize.minimize(objective2,
                                   [0.0],
                                   method=min_method)

with concurrent.futures.ThreadPoolExecutor() as pool:
    tasks = []
    tasks.append(pool.submit(minimizer1))
    tasks.append(pool.submit(minimizer2))

    for t in tasks:
        print(t.result())
```
(Yes, the original code used `args`, but I wanted to simplify it even more).

This code's output reads:
```
[0.] 1
[0.] 2
[1.] 2
[1.] 2
[0.125] 2
[2.] 2
[-0.25] 2
[1.5] 2
[0.125] 2
[0.75] 2
[-0.0625] 2
[1.125] 2
[0.03125] 2
[0.9375] 2
[-0.015625] 2
[1.03125] 2
[0.0078125] 2
[0.984375] 2
[-0.00390625] 2
[1.0078125] 2
[0.00195312] 2
[0.99609375] 2
[-0.00097656] 2
[1.00195312] 2
[0.00048828] 2
[0.99902344] 2
[-0.00024414] 2
[1.00048828] 2
[0.0001] 2
[0.99975586] 2
[-0.0001] 2
[1.0001] 2
     fun: 1.00020001
   maxcv: 0.0
 message: 'Optimization terminated successfully.'
    nfev: 16
  status: 1
 success: True
       x: array([-0.0001])
Call-back cb_calcfc_in__cobyla__user__routines failed.
Segmentation fault
```

(Obviously) The segmentation fault is unexpected, but also looking at the sequence of values - features 32 lines and roughly alternating objective values from objective 1 and 2, but only objective 2 seems to be evaluated.

The stack trace is:
```
#0  0x00007f5e94d24dc0 in f2py_rout.cobyla_minimize () from /home/XXXX/lib/python3.7/site-packages/scipy/optimize/_cobyla.cpython-37m-x86_64-linux-gnu.so
#1  0x000055b6ce95146b in _PyObject_FastCallKeywords (callable=0x7f5e94d73670, stack=0x7f5e88001680, nargs=1, kwnames=0x7f5e94d74a08) at /tmp/build/80754af9/python_1546061345851/work/Objects/call.c:199
#2  0x000055b6ce9ac378 in call_function (kwnames=0x7f5e94d74a08, oparg=<optimized out>, pp_stack=<synthetic pointer>) at /tmp/build/80754af9/python_1546061345851/work/Python/ceval.c:4619
[....]
```

There are two ways to avoid the problems above:
* use a ProcessPoolExecutor
* use the minimizer SLSQP

Here the output for the ProcessPoolExecutor:
```
[0.] 1
[0.] 2
[1.] 1
[1.] 2
[2.] 2
[-1.] 1
[-0.5] 1
[1.5] 2
[0.25] 1
[0.75] 2
[1.125] 2
[-0.125] 1
[0.9375] 2
[0.0625] 1
[-0.03125] 1
[1.03125] 2
[0.015625] 1
[0.984375] 2
[1.0078125] 2
[-0.0078125] 1
[0.99609375] 2
[0.00390625] 1
[-0.00195312] 1
[1.00195312] 2
[0.00097656] 1
[0.99902344] 2
[-0.00048828] 1
[1.00048828] 2
[0.00024414] 1
[0.99975586] 2
[1.0001] 2
[-1.e-04] 1
[0.0001] 1
[0.9999] 2
     fun: 1e-08
   maxcv: 0.0
 message: 'Optimization terminated successfully.'
    nfev: 17
  status: 1
 success: True
       x: array([0.0001])
     fun: 9.999999999997797e-09
   maxcv: 0.0
 message: 'Optimization terminated successfully.'
    nfev: 17
  status: 1
 success: True
       x: array([0.9999])
```
This output looks like I expect it.

I had a quick look at the Fortran/Python interface - sadly, I don't know enough about f2py to pin point the problem in the repository/code.

**Comment by achimgaedke** [comment]
same with scipy-1.2.0 (python 3.7 on debian testing - pip install)

**Comment by sturlamolden** [comment]
Fortran functions and subroutines are not reentrant unless tagges with the attribute ```recursive```. This is because the compiler is free to set any local variables static. The attribute ```save``` will ensure that a variable is static, but its absence will not guarrantee the opposite. What will actually happen is compiler dependent. However, this might be more of a theoretical issue, as we do assume that LAPACK subroutines are reentrant, even though this is stricty speaking not permissible. I would rather assume that there are one or several ```save``` or ```data``` statements in the Fortran code.

**Comment by mhellmeier** [comment]
Problem still exists in Python and scipy version 1.4.1.

Is there any workaround or plan for a fix?

**Comment by sturlamolden** [comment]
The evaluation of only ```objective2``` is as expected, due to the GIL.

It seems the segfault happens when there is a context switch between the threads.

**Comment by sturlamolden** [comment]
I think this might be an f2py issue.

**Comment by sturlamolden** [comment]
The pyf-file is autogenerated and there is no handwritten C in the wrapper. The GIL is not released so it is not an issue with Fortran not being reentrant. I am thinking it might be indicative of a bug in f2py. @pv

**Comment by sturlamolden** [comment]
f2py belongs to NumPy so the only thing we can do for now is to force single-threaded access to cobyla.

**Comment by sturlamolden** [comment]
There is upstream fix in https://github.com/numpy/numpy/pull/16519 but it requires that SciPy be built against NumPy version 1.19 or later.
