### ISSUE TITLE
Value of digamma(-10) changes between 1.0 and 1.1

### ISSUE THREAD

**Issue by tdhopper** [scipy/scipy#9663]
My issue is about the value of `scipy.special.digamma(-10)`. For <=1.0, `digamma(-10)==inf`, but for 1.1 and 1.2, `digamma(-10)==nan`. I can't see that this is documented anywhere.

### Reproducing code example:

Tox.ini file to reproduce:

```
[tox]
envlist = py27-scipy{1.2,1.1,1.0,.19,.18,.17}
skipsdist=True

[testenv]
deps =
    scipy1.2: scipy>=1.2,<1.3
    scipy1.1: scipy>=1.1,<1.2
    scipy1.0: scipy>=1.0,<1.1
    scipy.19: scipy==0.19.1
    scipy.18: scipy==0.18.1
    scipy.17: scipy==0.17.1
    numpy
commands =
  python -c "from scipy.special import digamma; from numpy import isinf; assert isinf(digamma(-10))"
```

### Error message:

```
ERROR:   py27-scipy1.2: commands failed
ERROR:   py27-scipy1.1: commands failed
  py27-scipy1.0: commands succeeded
  py27-scipy.19: commands succeeded
  py27-scipy.18: commands succeeded
  py27-scipy.17: commands succeeded
```

### Scipy/Numpy/Python version information:

Python 2.7.15

**Comment by person142** [comment]
Yes, the value was changed. Since the right/left limits of `digamma` at negative integers do not agree `nan` is a more appropriate value. I did not document the change since I thought of it as a bugfix, but perhaps I should have (apologies).

**Comment by person142** [comment]
Relevant PR is here: https://github.com/scipy/scipy/pull/8129.

**Comment by tdhopper** [comment]
Thanks.

Seems worth mentioning somewhere.

**Comment by mdhaber** [comment]
@tdhopper should we leave this open until it gets added to the documentation? Thanks for reporting it!

**Comment by mdhaber** [comment]
@tdhopper if so, can you suggest how it (presumably https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.digamma.html) should be modified?

**Comment by person142** [comment]
@mdhaber it should have been mentioned in the release notes, but I'm not sure the documentation is the right place for this. (It is "standard" behavior, and we don't want to e.g. say this over and over again for the many functions it would effect.)

Not sure if we should retroactively add something to release notes.

**Comment by mdhaber** [comment]
OK!

**Comment by tdhopper** [comment]
I would agree that release notes is the place for this.
