### ISSUE TITLE
DOC: scipy.integrate.solve_ivp

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#9666]
> You can assign attributes like event.terminal = True to any function in Python. If None (default), events won’t be tracked.

That's very confusing.    It's not the attribute **event.terminal** which is set to None for no tracking, but the argument **events**.

**Comment by MatthewFlamm** [comment]
I don't know what that sentence is trying to say either.  Maybe, it is supposed to mean that events won't be tracked for terminal status, i.e. a type of zero crossing.

**Comment by keithbriggs** [comment]
The last sentence should have been near the top, like this:

    Types of events to track. **If None (default), events won’t be tracked**. Each is defined by a continuous function of time and state that becomes zero value in case of an event. Each function must have the signature event(t, y) and return a float. The solver will find an accurate value of t at which event(t, y(t)) = 0 using a root-finding algorithm. Additionally each event function might have the following attributes:

            terminal: bool, whether to terminate integration if this event occurs. Implicitly False if not assigned.
            direction: float, direction of a zero crossing. If direction is positive, event must go from negative to positive, and vice versa if direction is negative. If 0, then either direction will count. Implicitly 0 if not assigned.

    You can assign attributes like event.terminal = True to any function in Python.
