### ISSUE TITLE
DOC: scipy.integrate.solve_ivp example

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#9667]
This example looks wrong.  Shouldn't it be
> def hit_ground(t, y): return y[0]
if you want to stop when position is 0?

Also, I get this warning from this example:
> /usr/local/lib/python3.4/dist-packages/scipy/integrate/_ivp/rk.py:145: RuntimeWarning: divide by zero encountered in double_scalars  max(1, SAFETY * error_norm ** (-1 / (order + 1))))

>Cannon fired upward with terminal event upon impact. The terminal and direction fields of an event are >applied by monkey patching a function. Here y[0] is position and y[1] is velocity. The projectile starts at >position 0 with velocity +10. Note that the integration never reaches t=100 because the event is terminal.
>>> def upward_cannon(t, y): return [y[1], -0.5]
>>> def hit_ground(t, y): return y[1]

**Comment by MatthewFlamm** [comment]
Can you retry on scipy 1.1.0 or higher?  I have no issues with version
1.1.0, but 1.2.0 is now available.

**Comment by keithbriggs** [comment]
Will try later, but meanwhile the example can be fixed.
