### ISSUE TITLE
DOC: matthew-brett/build-openblas has been retired

### ISSUE THREAD

**Issue by bbbbbbbbba** [scipy/scipy#9669]
The [Windows building docs](https://github.com/scipy/scipy/blob/master/doc/source/building/windows.rst) depends on the repo https://github.com/matthew-brett/build-openblas, which has been retired. The "alternative" suggested in the README.md there doesn't work either. The last commit in that repo before retiring was for OpenBLAS version 0.3.1.

**Comment by rgommers** [comment]
Should be https://github.com/MacPython/openblas-libs

**Comment by matthew-brett** [comment]
Fixed in build-openblas retired README, thanks.

**Comment by matthew-brett** [comment]
Windows build instructions still need fixing though ...

**Comment by ilayn** [comment]
@matthew-brett Currently the `build_openblas.sh` is not executable as is since, probably, it is tailored for appveyor. 

Should I open a PR for a new file or should we explain creating a custom shell script for building OpenBLAS in the documentation?
