### ISSUE TITLE
Three little questions about "minimize"

### ISSUE THREAD

**Issue by Abraxas2071** [scipy/scipy#9677]
```python
np.random.seed(113)
x = np.random.normal(loc=0, scale=2, size=((400, 1)))
beta = np.array((2, -2, 3, 4, 4, 5))
tmp_c = np.array((-2 ** 0.5, 2 ** 0.5))
x_1, x_2, x_3 = x[x < tmp_c[0]], x[(x < tmp_c[1]) & (x >= tmp_c[0])], x[x >= tmp_c[1]]
y_1, y_2, y_3 = x_1 * beta[1] + beta[0], x_2 * beta[3] + beta[2], x_3 * beta[5] + beta[4]
y = np.concatenate((y_1, y_2, y_3)).reshape((-1, 1)) + np.random.randn()
x = np.concatenate((x_1, x_2, x_3)).reshape((-1, 1))
x = np.concatenate((np.ones((400, 1)), x), axis=1)
tmp_h = np.log(400) / 400 * 2  # 窗宽
tmp_len = x.shape[1]
tmp_lam = 0.5
tmp_z = x[:, 1].reshape((-1, 1))

def loss(param):
    first_M_MSE = y - np.dot(x, param[:tmp_len])
    other_M_MSE, scad = 0, 0
    M_c = np.array(param[-(tmp_c.shape[0] + 1):-1], ndmin=1)

    for idx, c in enumerate(M_c):
        nor_distri_x = (tmp_z - c) / tmp_h
        nor_distri_CDF = st.norm.cdf(nor_distri_x)  # 光滑示性函数
        other_M_MSE += np.dot(x, param[tmp_len * (idx + 1):tmp_len * (idx + 2)]) * nor_distri_CDF
        beta_param = np.sum(np.abs(param[tmp_len * (idx + 1):tmp_len * (idx + 2)]))
        if beta_param < tmp_lam:
            scad += tmp_lam ** 2 - (beta_param - tmp_lam) ** 2
        else:
            scad += tmp_lam ** 2
    MSE = 0.5 * np.average((first_M_MSE - other_M_MSE) ** 2) + scad
    return MSE

s = np.append(np.ones([tmp_len * 3, 1]), np.array([x[:, 1].mean(), x[:, 1].std(ddof=1)]))
result = minimize(fun=loss, x0=np.squeeze(s), method='BFGS', tol=1e-6)
```

====================================================
Q1：How does "minimize"  take its derivative？？
Q2：Code can be work，But the results are inconsistent with stata's calculations（Stata is an econometric software）
Q3："result.hess" will be error

>

> Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\envs\untitled_0\lib\site-packages\scipy\optimize\optimize.py", line 114, in __getattr__
    return self[name]
KeyError: 'hess'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "F:/Code_Work/reg_analysis.py", line 160, in <module>
    print(result.x, result.hess, sep='\n')
  File "D:\ProgramData\Miniconda3\envs\untitled_0\lib\site-packages\scipy\optimize\optimize.py", line 116, in __getattr__
    raise AttributeError(name)
AttributeError: hess

**Comment by ilayn** [comment]
Hi @Abraxas2071. Could you please make your question a bit more self-contained by adding some context? The code snippet is also not self-contained for example `tmp` variables are not defined etc.

**Comment by Abraxas2071** [comment]
@ilayn 
Our Dear ilayn~help me~
I added context

**Comment by pkofod** [comment]
Maybe show what you do in stata also?

**Comment by Abraxas2071** [comment]
@pkofod 
Our Dear Patrick~
I tried in Python to implement the least squares estimate with the SCAD penalty function——The model is threshold regression
Stata have this command, so compare the results

>SCAD：http://www.personal.psu.edu/ril4/research/penlike.pdf
Smoothed Least Squares：http://eprints.lse.ac.uk/4434/1/A_Smoothed_Least_Squares_Estimator_For_Threshold_Regression_Models.pdf
Threshold Regression：http://www.doc88.com/p-2089722981617.html

**Comment by rgommers** [comment]
closing this, not further actionable. @Abraxas2071 user questions are better asked on StackOverflow in the future, this issue tracker is for development related things (issues, new feature discussions, ...)
