### ISSUE TITLE
ndimage.median_filter vs signal.medfilt

### ISSUE THREAD

**Issue by skjerns** [scipy/scipy#9680]
I just discovered that there are two different functions for median computation within Scipy.
`medfilter` from the `signal` module and
`median_filter` from the `ndimage` module which is much faster.

### Reproducing code example:
```Python
import numpy as np
from scipy.signal import medfilt
from scipy.ndimage.filters import median_filter

from timeit import Timer

sig = np.random.random(2**17)

t_signal = Timer(lambda: medfilt(sig ,9))
t_ndimage = Timer(lambda: median_filter(sig, 9, mode='constant'))
print (t_signal.timeit(number=100))
print (t_ndimage.timeit(number=100))

# both give the same result
print(np.allclose(medfilt(sig ,9),median_filter(sig, 9, mode='constant')))
```

```Python
signal: 6.517080050130517 seconds
ndimage: 1.648757460273032 seconds
```
Is there a reason why these two implementations are used, while one of them is clearly faster and produces same results? Both of them are running on one thread.

As far as I see it, the `ndimage` implementation should be even more general than the `signal` one.

Would it not make sense to use only the faster implementation or are there special cases when not?
In any case, this should be mentioned in the docs of either function.

**Comment by larsoner** [comment]
Probably just historical accident.

Merging them might prove difficult, as you have to make sure that all combinations of inputs are indeed identical from one to the other. A simpler solution would be to add to the `Notes` of the slower one mentioning the faster one might be preferable for speed purposes.

**Comment by skjerns** [comment]
I've created a small PR with some doc changes.
