### ISSUE TITLE
'eliminate_zeros' does not do anything on a 'bsr_matrix' entirely of zeros

### ISSUE THREAD

**Issue by ExpHP** [scipy/scipy#9687]
### Summary

If the dense representation of a `bsr_matrix` is all zeros, `eliminate_zeros` becomes a no-op rather than removing the explicit zeros.

### Reproduction

```py3
import numpy as np
import scipy.sparse as sp
np.random.seed(0xcafebabe)

m = sp.bsr_matrix(np.random.random((27, 27)), blocksize=(3,3))
print(m.nnz, len(m.data))

# eliminate some blocks
m.data[np.absolute(m.data) < 0.8] = 0
m.eliminate_zeros()
print(m.nnz, len(m.data))

# eliminate all blocks
m.data[...] = 0
m.eliminate_zeros()
print(m.nnz, len(m.data))
```

**Output:**
```
729 81
603 67
603 67
```

**Expected output:**

I expect that everything should be truncated from the last matrix, like it is with `csr_matrix`.
```
729 81
603 67
0 0
```

### Scipy/Numpy/Python version information:

```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.0 1.15.4 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)
```

### Other notes

This looks suspicious:

https://github.com/scipy/scipy/blob/95029ad1452495bf3acfc7daa973cfd12e298064/scipy/sparse/bsr.py#L552-L553

**Comment by perimosocordiae** [comment]
Yep, looks like a bug to me. Impressively, it wasn't discovered for the 11 years since it was added by 8529b5b89ac17930222cc86787b72a8e8eb5b6a2.

If you want to send a PR with a fix, I'll be happy to take a look. We should add a test case as well, to prevent regressions.

**Comment by ExpHP** [comment]
Heh.  I noticed it when I was testing out the effect of different truncation thresholds on matrix density.

I'm curious about what that fast path is even intended to achieve, and am tempted to simply remove it.  (or I guess I could replace it with `if not self.data.size`, which seems more sensible...)
