### ISSUE TITLE
Incorrect sign in scipy.spatial.transform.Slerp for orientation quaternions

### ISSUE THREAD

**Issue by solarjoe** [scipy/scipy#9688]
Maybe I am just not getting Quaternions, but I think there is an incorrect sign when using Slerp with orientation quaternions (w=0). 

I am trying to interpolate positions between two vectors (vector part in orientation quaternions) and get the fractions of the shortest rotation between them.

I compared the results to [mathutils ](https://docs.blender.org/api/master/mathutils.html#mathutils.Quaternion.slerp) and gohlke's [transformations.py](https://www.lfd.uci.edu/~gohlke/code/transformations.py.html)

This code shows the results for the three packages. Scipy uses scalar-last, the others use scalar-first notation.

```
import transformations as tf
import mathutils
from scipy.spatial.transform import Rotation
import numpy as np
from scipy.spatial.transform import Slerp

def xyzw_to_wxyz(q):
    
    return np.array([q[3], q[0], q[1], q[2]])

# scipy : scalar-last format
quat0 = np.array([1.0, 0.0, 0.0, 0.0]) # x-axis
quat1 = np.array([0.0, 1.0, 0.0, 0.0]) # y-axis

key_rots = Rotation.from_quat([quat0, quat1])
slerp = Slerp([0, 1], key_rots)
times = [0.0, 0.25, 0.5, 0.75, 1.0]

for fraction in times:

    s1 = tf.quaternion_slerp(xyzw_to_wxyz(quat0), xyzw_to_wxyz(quat1), fraction)

    quat_a = mathutils.Quaternion(xyzw_to_wxyz(quat0))
    quat_b = mathutils.Quaternion(xyzw_to_wxyz(quat1))

    print()
    print(fraction)
    print('transformations.py', s1)
    print('mathutils', quat_a.slerp(quat_b, fraction))
    print('scipy', slerp([fraction]).as_quat())
```

Output is 

```
fraction 0.0
transformations.py [0. 1. 0. 0.]
mathutils Quaternion((0.0, 1.0, 0.0, 0.0))
scipy [[1. 0. 0. 0.]]

fraction 0.25
transformations.py [0.         0.92387953 0.38268343 0.        ]
mathutils Quaternion((0.0, 0.9238795042037964, 0.3826834559440613, 0.0))
scipy [[ 0.92387953 -0.38268343  0.          0.        ]]

fraction 0.5
transformations.py [0.         0.70710678 0.70710678 0.        ]
mathutils Quaternion((0.0, 0.7071067690849304, 0.7071067690849304, 0.0))
scipy [[ 0.70710678 -0.70710678  0.          0.        ]]

fraction 0.75
transformations.py [0.         0.38268343 0.92387953 0.        ]
mathutils Quaternion((0.0, 0.3826834559440613, 0.9238795042037964, 0.0))
scipy [[ 0.38268343 -0.92387953  0.          0.        ]]

fraction 1.0
transformations.py [0. 0. 1. 0.]
mathutils Quaternion((0.0, 0.0, 1.0, 0.0))
scipy [[ 6.123234e-17 -1.000000e+00  0.000000e+00  0.000000e+00]]

```

You can see that mathutils and transformations.py arrive at `y` for fraction 1.0. But scipy has a flipped sign and returns `-y`

### Scipy/Numpy/Python version information:
```
1.2.0 1.15.2 sys.version_info(major=3, minor=5, micro=5, releaselevel='final', serial=0)
```

**Comment by solarjoe** [comment]
Or am I using it in the wrong way? Do I have to interpolate between an identity Quaternion `[0.0, 0.0, 0.0, 1.0]` and a Quaternion that rotates around the z-axis `[0.0, 0.0, 0.7071, 0.7071]` and apply the fractional Quaternions to the starting vector myself?

Is such a thing like an orientation quaternion or position quaternion `p` only valid when applying the rotation to it as `p_new = q p q*` ?

**Comment by nmayorov** [comment]
> I am trying to interpolate positions between two vectors (vector part in orientation quaternions) and get the fractions of the shortest rotation between them.

Can't be sure on that, but it seems to me you are using the wrong tool to solve your problem. 

Quaternions to represent rotations have the sign ambiguity (i.e. `q` and `-q` represent the same rotation) and we don't try to maintain any sign conventions inside `Rotation`, because it doesn't have a strong meaning and would only complicate the code. 

Looks like `geometric_slerp` from #10380 is the right tool to interpolate unit vectors in 3D. You can use dev version of scipy to get it right now.

It might sound a bit unsatisfactory, but it's sort of complicated to achieve what you are asking for in `Slerp` and doesn't make a lot of sense from the `Rotation` design perspective.
