### ISSUE TITLE
bounds parameter of minimize should take a list of tuple instead a tuple of tuple 

### ISSUE THREAD

**Issue by Senhaji-Rhazi-Hamza** [scipy/scipy#9692]
My issue is about the parameter bounds in scipy, the documentation specify to use a tuple, but i have a bug when i use a function that take an array of dimension 1, and that bug is due to scipy when it tries to compare the shape of the array (1,) with the shape of the tuple for example ((0,1)) has a shape of 2 instead of 1

I know that minimize_scalar exist, but for some purpose of generic programming, i want to use minimize 
here is an example that illustrate my situation : 

### Reproducing code example:

```
from scipy.optimize import minimize_scalar, minimize
def fun(param):
    return np.linalg.norm(param)
minimize(fun, np.array([1]),bounds = ((0,4)))
```

### Error message:

```
ValueError                                Traceback (most recent call last)
<ipython-input-8-4639f9204ecf> in <module>
      2 def fun(param):
      3     return np.linalg.norm(param)
----> 4 minimize(fun, np.array([1]),bounds = ((0,4)))

/usr/local/lib/python3.6/dist-packages/scipy/optimize/_minimize.py in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    601     elif meth == 'l-bfgs-b':
    602         return _minimize_lbfgsb(fun, x0, args, jac, bounds,
--> 603                                 callback=callback, **options)
    604     elif meth == 'tnc':
    605         return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,

/usr/local/lib/python3.6/dist-packages/scipy/optimize/lbfgsb.py in _minimize_lbfgsb(fun, x0, args, jac, bounds, disp, maxcor, ftol, gtol, eps, maxfun, maxiter, iprint, callback, maxls, **unknown_options)
    265         bounds = [(None, None)] * n
    266     if len(bounds) != n:
--> 267         raise ValueError('length of x0 != length of bounds')
    268     # unbounded variables must use None, not +-inf, for optimizer to work properly
    269     bounds = [(None if l == -np.inf else l, None if u == np.inf else u) for l, u in bounds]

ValueError: length of x0 != length of bounds

  ...
```
The solution found was the following 

```
from scipy.optimize import minimize_scalar, minimize
def fun(param):
    return np.linalg.norm(param)
minimize(fun, np.array([1]),bounds = [(0,4)])
```
### Scipy/Numpy/Python version information:
```
1.1.0 1.15.4 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)```

**Comment by WarrenWeckesser** [comment]
The problem with using `bounds = ((0,4))` is that `((0, 4))` is equivalent to `(0,4)`.  To create a tuple with a single element, you must include the trailing comma: `bounds=((0, 4),)`:

    minimize(fun, np.array([1]), bounds=((0, 4),))

Do a search for terms such as `python tuple single element comma` to find many discussions of this quirk of the Python syntax.

This is not a problem with SciPy, so I'm closing the issue.
