### ISSUE TITLE
Potential BUG in Scipy Optimize

### ISSUE THREAD

**Issue by coldani** [scipy/scipy#9696]
Hi! I have encountered an issue with scipy.optimize.minimize, which returns the following error: 

> ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()

It seems to me that the issue is within the method itself, however I am not experienced enough to understand what is exactly causing it. I'll now describe what I was doing, and I'll provide below a reproducible example.

I was maximising the LogLikelihood of an ARMA model, using the scipy.optimize.minimize package and using the BFGS method (the error persist with other methods as well however), without giving the Jacobian and Hessian matrices. The function I was optimizing returns the correct output, i.e. the log likelihood of a specified ARMA model.

The given traceback is as follows:

    
    /......../.py in fit_ARMA(data, p, q)
        150     optim_args=(data, p, q)
        151
    --> 152     fitted_params = minimize(minus_ll_ARMA, x0=init_params, args=optim_args, method='BFGS')
        153
        154     return fitted_params.x
    
    /anaconda3/lib/python3.6/site-packages/scipy/optimize/_minimize.py in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
        595         return _minimize_cg(fun, x0, args, jac, callback, **options)
        596     elif meth == 'bfgs':
    --> 597         return _minimize_bfgs(fun, x0, args, jac, callback, **options)
        598     elif meth == 'newton-cg':
        599         return _minimize_newtoncg(fun, x0, args, jac, hess, hessp, callback,
    
    /anaconda3/lib/python3.6/site-packages/scipy/optimize/optimize.py in _minimize_bfgs(fun, x0, args, jac, callback, gtol, norm, eps, maxiter, disp, return_all, **unknown_options)
        981             alpha_k, fc, gc, old_fval, old_old_fval, gfkp1 = \
        982                      _line_search_wolfe12(f, myfprime, xk, pk, gfk,
    --> 983                                           old_fval, old_old_fval, amin=1e-100, amax=1e100)
        984         except _LineSearchError:
        985             # Line search failed to find a better solution.
    
    /anaconda3/lib/python3.6/site-packages/scipy/optimize/optimize.py in _line_search_wolfe12(f, fprime, xk, pk, gfk, old_fval, old_old_fval, **kwargs)
        801     ret = line_search_wolfe1(f, fprime, xk, pk, gfk,
        802                              old_fval, old_old_fval,
    --> 803                              **kwargs)
        804
        805     if ret[0] is not None and extra_condition is not None:
    
    /anaconda3/lib/python3.6/site-packages/scipy/optimize/linesearch.py in line_search_wolfe1(f, fprime, xk, pk, gfk, old_fval, old_old_fval, args, c1, c2, amax, amin, xtol)
         99     stp, fval, old_fval = scalar_search_wolfe1(
        100             phi, derphi, old_fval, old_old_fval, derphi0,
    --> 101             c1=c1, c2=c2, amax=amax, amin=amin, xtol=xtol)
        102
        103     return stp, fc[0], gc[0], fval, old_fval, gval[0]
    
    /anaconda3/lib/python3.6/site-packages/scipy/optimize/linesearch.py in scalar_search_wolfe1(phi, derphi, phi0, old_phi0, derphi0, c1, c2, amax, amin, xtol)
        153
        154     if old_phi0 is not None and derphi0 != 0:
    --> 155         alpha1 = min(1.0, 1.01*2*(phi0 - old_phi0)/derphi0)
        156         if alpha1 < 0:
        157             alpha1 = 1.0
    
    /anaconda3/lib/python3.6/site-packages/pandas/core/generic.py in __nonzero__(self)
       1574         raise ValueError("The truth value of a {0} is ambiguous. "
       1575                          "Use a.empty, a.bool(), a.item(), a.any() or a.all()."
    -> 1576                          .format(self.__class__.__name__))
       1577
       1578     __bool__ = __nonzero__
    
    ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Here is a workable example, that reproduces the issue (please see also all imports with their version)

```
import pandas as pd # version 0.23.4
import numpy as np # version 1.15.4
from scipy.optimize import minimize   # version 1.1.0

 # the two functions used are as follows
 def ll_ARMA(params, data, p, q):
    '''Returns the log-likelihood of the ARMA model.
    p= # coeff. AR
    q= # coeff MA'''

    n = data.shape[0]

    if p>0:
        lagged_data = data.shift(1).copy()
        for i in range(1,p):
            lagged_data = pd.concat([lagged_data, data.shift(i+1)], axis=1)

    else:
        lagged_data = pd.DataFrame(index = data.index, columns=[i+1 for i in range(p)])

    errors_index = pd.Index([i for i in range(q)]).append(data.index)
    errors = pd.DataFrame(np.zeros(shape=(n+q,1)),index=errors_index)
    for i in range(q, n+q):
        a = data.iloc[i-q,:] - params[0] - np.sum(np.dot(lagged_data, params[1:p+1])) - \
            np.dot(params[p+1:], np.asarray([errors.iloc[i-j,:] for j in range(1, q+1)]))
        errors.iloc[i,:] =  a.item()   

    errors = errors[q:] # gets rid of initial q values set at 0
    var = np.var(errors)
    log_likelihood = np.log(2*np.pi*var)*(-1/2) + (-1/2)*(errors**2)/var

    return np.sum(log_likelihood)

  def fit_ARMA(data, p, q):
        '''Returns the fitted parameters of an ARMA model (including the constant).
        Order is -constant -p AR coeff -q MA coeff
        Data must be a 1-column DF.
        p is the parameter of the AR, q of the MA'''
    
    init_params = np.random.random(p+q+1)

    def minus_ll_ARMA(params, data, p, q):
        return -1*ll_ARMA(params, data, p, q)

    optim_args=(data, p, q)
    
    #this generates the error!
    fitted_params = minimize(minus_ll_ARMA, x0=init_params, args=optim_args, method='BFGS')

    return fitted_params.x

# These last two lines call the functions above and return the error

  data = pd.DataFrame(np.random.random(500)*0.4-0.2, index = [i for i in range(1,501)]) # randomly generates returns in a sensible range
  parameters = fit_ARMA(data, 2, 3) # this returns the error

```

**Comment by ev-br** [comment]
An MWE without pandas would be helpful here.

**Comment by coldani** [comment]
To be fair, the error may arise only if using pandas: I tried producing a similar example using numpy arrays and it worked fine. It is still an issue though, or is it just wrong to use pandas and scipy together?

**Comment by ilayn** [comment]
It is an issue because you are using a Series object in a place where you want to have an array. It is a bit tedious to backtrack things in your example but at some point you need to use `data.values` to extract the array instead of passing it around and finally ending up in `minimize` function

**Comment by coldani** [comment]
Thank you. I have tried that and it works perfectly. Very much appreciated your help guys.
