### ISSUE TITLE
Import Error: cannot import name 'sparse'

### ISSUE THREAD

**Issue by Shwetago** [scipy/scipy#9702]
### Import error: 
sparse module in spicy
```
import pandas as pd
import spicy
from spicy import sparse
import numpy as np
```
### Error:
```
ImportError                               Traceback (most recent call last)
<ipython-input-6-f0e7ad99bd02> in <module>
      1 import pandas as pd
      2 import spicy
----> 3 from spicy import sparse
      4 import numpy as np

ImportError: cannot import name 'sparse'

```
### Scipy/Numpy/Python version information:
Scipy version: 1.2.0
Numpy version: 1.15.4
Python version: 3.6.5
Windows10

**Comment by ilayn** [comment]
Hi @Shwetago I have almost exact versions and cannot reproduce this. Can you clarify how you installed it or can you remove and reinstall SciPy if possible?

**Comment by Shwetago** [comment]
@perimosocordiae Thank you so much. I am sorry for the typo.

**Comment by Shwetago** [comment]
@perimosocordiae Since you are a member. Could you please delete this issue if possible. Thanks again!!
