### ISSUE TITLE
scipy.spatial.ConvexHull: Need to obtain visible facets (feature request)

### ISSUE THREAD

**Issue by rtshort** [scipy/scipy#9703]
This is a feature request, and if there is any interest I have a patch that works.

I am trying to use ConvexHull to find the facets of the convex hull that are visible from a point.

My data set is a pyramidal shape with all 4 points on the surface of a sphere, plus point zero is the origin (this is a qhull format file):

3
5
 0.           0.           0.        
 0.90029516  -0.39187448   0.18948093
 0.4867642   -0.72627633   0.48536925
 0.5765153   -0.81179274  -0.09285832
 0.67846893  -0.71119562   0.1840671 

If I run qhull from the command line:

> qhull i QG0  Qt < spheredata
1
3 1 2
> qhull i QG-0 Qt < spheredata
3
1 4 2
4 3 2
3 4 1

So that the facet [3 1 2] is visible from the origin and the remaining facets are not.

If I run the python script

import numpy
from scipy.spatial import ConvexHull

# Read the qhull file.
filename = 'spheredata'
hullfile = open(filename)
ndim    = int(hullfile.readline())
npoints = int(hullfile.readline())
points = numpy.zeros((npoints,ndim))
for npt in range(npoints):
    points[npt] = numpy.fromstring(hullfile.readline(), sep=' ')

# Compute the visible and invisible facets.
hull = ConvexHull(points, qhull_options=b"QG0")
print(hull.simplices)

hull = ConvexHull(points, qhull_options=b"QG-0")
print(hull.simplices)

The result is
[[3 1 2]
 [4 1 2]
 [4 3 2]
 [4 3 1]]
[[3 1 2]
 [4 1 2]
 [4 3 2]
 [4 3 1]]

So that the correct facets are computed, but the "good" facets and the "bad" facets are being printed.

As I said, I made a patch that works.  I simply used the "good" flag from the facet structure to create a "good" array inside the class.  By indexing into the facets with this array the correct facets are returned.

If there is any interest I will provide the code.  I am still working up tests and have not tried this with python2.7 but it would be good to have somebody that actually understands qhull and cython to look at this.

**Comment by tylerjereddy** [comment]
Is there a literature citation for the visibility algorithm? I can probably review the code, but we will probably need a fair number of test cases & a reasonable citation to convince reviewers it is robust.

**Comment by tylerjereddy** [comment]
Might be a cool feature to have!

I'm curious -- is it obvious why we can't use the documented `qhull_options` directly to get this information?

> QGn - good facet if visible from point n, -n for not visible

Is there a problem because we don't have easy Python-level access for specification of point `n`?  Or will that just index into the provided generators?

> With option 'QGn', a facet is good (see 'Qg' and 'Pg') if it is visible from point n. If n < 0, a facet is good if it is not visible from point n. Point n is not added to the hull (unless 'TCn' or 'TPn').

So, our ConvexHull wrapper is not sensitive to the value of `n` --  making it negative has no effect?

**Comment by tylerjereddy** [comment]
It might be interesting to see your proposed adjustments in a PR so people can comment. It is fine to have a WIP (work in progress) PR open that gets chipped away at.

My initial intuition is that a relatively minor adjustment that allows us to leverage more Qhull features is probably useful. I'm assuming we don't have to vendor a newer version of Qhull or anything like that to leverage the feature if I understand correctly--just need some more flexibility in our interface to Qhull?

**Comment by rtshort** [comment]
I don't think this is a new feature in qhull.  I will look at that a little.  I am using debian stable and that is always way behind the update curve.  This really just exposes a qhull interface that isn't currently utilized.  Also, if someone thinks there is a better API, I really don't care.  I just need the feature.  

Like I say I can do the leg work, but comments and advice make it possible for me to do the legwork.  This is strictly hobby stuff so it doesn't go quickly.

I assume PR means pull request (I am fairly new to github as a working environment).  I have done pull requests in my work environment but that is a place that I have more control than I really care for given my ignorance.  I don't know how to do that on this repo but I am pretty sure it isn't hard.  BTW, I really don't have the ability to test in Windows

I was planning to build some test cases this weekend.  I can probably do a pull request tomorrow.  I also wrote some kind of cool code to do some testing.  Not really suitable for part of scipy, but I will post it on a github repo.  It makes it a lot easier to see what is going on.

**Comment by tylerjereddy** [comment]
Linking to a github repo is also helpful if that's easier to start. The [official docs for creating a pull request](https://help.github.com/articles/creating-a-pull-request/) are pretty nice.

Probably a bit more likely to get feedback on a pull request, but whatever is easier for you at this stage!

**Comment by rtshort** [comment]
I will do a pull request.  Thanks for the link.

I will also do some supplementary stuff on a separate github repo, but that is totally ancillary to this.

**Comment by tylerjereddy** [comment]
This feature was added in #9721, and there's a nice visibility example in the docs: https://scipy.github.io/devdocs/generated/scipy.spatial.ConvexHull.html?highlight=convexhull#scipy.spatial.ConvexHull

So, closing

**Comment by tylerjereddy** [comment]
Available in `1.3.x` series.
