### ISSUE TITLE
RectSphereBivariateSpline fails for negative longitude

### ISSUE THREAD

**Issue by jorgsk** [scipy/scipy#9704]
The RectSphereBivariateSpline interpolation function cannot be evaluated for negative degrees longitude, which is actually supported by the underlying interpolation library. The cause is that SphereBivariateSpline, the baseclass to RectSphereBivariateSpline, raises ValueErrors for negative lon-values. This is appropriate for the two other classes that subclass SphereBivariateSpline, but not RectSphereBivariateSpline.

One solution could be to create call methods for the two other Sphere-classes and move the checks on lat/lon from SphereBivariateSpline into these.

If that seems viable I could create a pull-request.

### Reproducing code example:

```
from scipy.interpolate import RectSphereBivariateSpline
import numpy as np

lats = np.array([25, 30, 35, 40, 45])
lons = np.array([-90, -85, -80, -75, -70])

mesh = np.meshgrid(lats, lons)
data = mesh[0] + mesh[1] # lon + lat value

lat_r = np.radians(lats)
lon_r = np.radians(lons)

interpolator = RectSphereBivariateSpline(lat_r, lon_r, data)

query_lat = np.radians(np.array([35, 37.5]))
query_lon = np.radians(np.array([-80, -77.5]))

data_interp = interpolator(query_lat, query_lon)
```

### Error message:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-49ec0a78db0b> in <module>()
     16 query_lon = np.radians(np.array([-80, -77.5]))
     17 
---> 18 data_interp = interpolator(query_lat, query_lon)

~/anaconda3/lib/python3.6/site-packages/scipy/interpolate/fitpack2.py in __call__(self, theta, phi, dtheta, dphi, grid)
   1263             raise ValueError("requested theta out of bounds.")
   1264         if phi.size > 0 and (phi.min() < 0. or phi.max() > 2. * np.pi):
-> 1265             raise ValueError("requested phi out of bounds.")
   1266 
   1267         return _BivariateSplineBase.__call__(self, theta, phi,

ValueError: requested phi out of bounds.
```

### Scipy/Numpy/Python version information:
1.1.0 1.14.3 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)

**Comment by yaofuzhou** [comment]
@jorgsk 
Hey, I just found the same issue myself.
I think it works if the \phi angle is understood to be within [0,2pi), which you may have figured out via trial and error yourself.
Before I found your post I posted the same issue and suggested them the check the consistence of the domains of the angular arguments everywhere.
Cheers!
