### ISSUE TITLE
scipy.stats.gaussian_kde normalizes the weights keyword argument externally.

### ISSUE THREAD

**Issue by ymareth** [scipy/scipy#9709]
scipy.stats.gaussian_kde takes a keyword argument weights. Internally the weights are normalized, but it is not copied first. The upshot being that if a numpy array of values are passed in these will be normalized as a side effect...

```
import scipy.stats as sts
import numpy as np

values = np.random.lognormal(size=1000)
weights = np.random.choice([1.0,10.0,100.0], size=len(values))
sum(weights)
```
Sum of weights will be about 40,000, but after executing...

```
kde_pdf = sts.kde.gaussian_kde(np.log10(values), weights=weights)
```

Sum of weights will be very close to if not exactly 1.0.

Tested on scipy 1.2.0.

**Comment by ev-br** [comment]
Would you be interested in aubmitting a PR with a fix?

**Comment by ev-br** [comment]
@tylerjereddy Am tentatively labelling this for the milestone 1.2.1 since weighted KDE is new in scipy 1.2. This is a nice-to-fix IMO, but not a blocker, so it's your call to keep the milestone or kick it down the road.

**Comment by WarrenWeckesser** [comment]
Another problem that can be fixed at the same time: the function raises an exception if `weights` is an integer array:

```
In [18]: from scipy.stats.kde import gaussian_kde

In [19]: values = [0.2, 13.5, 21.0, 75.0, 99.0]

In [20]: weights = np.array([1, 2, 4, 8, 16])  # An integer array

In [21]: kde_pdf = gaussian_kde(values, weights=weights)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-74c79aa6e879> in <module>()
----> 1 kde_pdf = gaussian_kde(values, weights=weights)

~/miniconda36/lib/python3.6/site-packages/scipy-1.3.0.dev0+aa23ee6-py3.6-macosx-10.7-x86_64.egg/scipy/stats/kde.py in __init__(self, dataset, bw_method, weights)
    199         if weights is not None:
    200             self._weights = atleast_1d(weights)
--> 201             self._weights /= sum(self._weights)
    202             if self.weights.ndim != 1:
    203                 raise ValueError("`weights` input should be one-dimensional.")

TypeError: No loop matching the specified signature and casting
was found for ufunc true_divide
```

**Comment by tylerjereddy** [comment]
Ok, I've made a note of this -- I guess it is an excuse for me to avoid spending time on the release process right away :)

I may not want to wait super long though with the 2.7 source build broken.

**Comment by ev-br** [comment]
fix in https://github.com/scipy/scipy/pull/9720
