### ISSUE TITLE
stats.weightedtau([1], [1.0]) SEGFAULTs

### ISSUE THREAD

**Issue by ddrcoder** [scipy/scipy#9710]
`stats.weightedtau` SEGFAULTs when used with arrays of different types with `len == 1`. I suspect this is due to an [uninitialized variable `i` in its helper, `_toint64()`](https://github.com/scipy/scipy/blob/90534919e139d2a81c24bf08341734ff41a3db12/scipy/stats/_stats.pyx#L141,L161).

### Reproducing code example:

```
from scipy.stats import weightedtau
# In my tests, this only repros in optimized builds after calling the function twice.
weightedtau([1], [1.0])
weightedtau([1], [1.0])
```

### Error message:

```
Segmentation fault
```

### Scipy/Numpy/Python version information:
- SciPy 1.1.0
- NumPy 1.15.1
- Python 3.6.3

**Comment by ev-br** [comment]
@evgenyzhurko would you be interested in send a pull request?

**Comment by Intellagent** [comment]
Just found this because after I was able to isolate this issue.
`
stats.weightedtau([np.nan],  [52])
`
will also segfaults.

(base) [mr85p01ad-hadoop408 ~]$ pip freeze | grep scipy
scipy==1.4.1
