### ISSUE TITLE
`binned_statistic_2d` does not accept `values.dtype==complex`

### ISSUE THREAD

**Issue by ToBeckmann** [scipy/scipy#9712]
scipy.stats.binned_statistic_2d does not handle complex values, even with custom callables.

The cause seems to be in https://github.com/scipy/scipy/blob/master/scipy/stats/_binned_statistic.py#L546, where the result accumulator gets initialized with a hardcoded float: `result = np.empty([Vdim, nbin.prod()], float)`

### Reproducing code example:
```
import numpy
import scipy.stats

xx = [0.6, 0.7, 1.1]
yy = [.5, .5, .5]
vv = [1j, 1+.3j, 1]
bin_edges = [0, 1, 2]

my_mean = lambda list: numpy.average(list)

binned, _, _, _ = scipy.stats.binned_statistic_2d(xx, yy, vv, statistic='mean', bins=bin_edges)

print(binned)
```

### Error message:
```
Traceback (most recent call last):
  File "scipy_binnedstats_demo.py", line 21, in <module>
    binned, _, _, _ = scipy.stats.binned_statistic_2d(xx, yy, vv, statistic='mean', bins=bin_edges)
  File "\lib\site-packages\scipy\stats\_binned_statistic.py", line 344, in binned_statistic_2d
    expand_binnumbers=expand_binnumbers)
  File "\lib\site-packages\scipy\stats\_binned_statistic.py", line 553, in binned_statistic_dd
    flatsum = np.bincount(binnumbers, values[vv])
TypeError: Cannot cast array data from dtype('complex128') to dtype('float64') according to the rule 'safe'
```
when passing `statistic=my_mean` instead, execution finished, but the result is wrong:
`[[ 0.5  nan] [ 1.   nan]]` - and there is a corresponding `ComplexWarning` as the complex numbers gets cast to real.

### Scipy/Numpy/Python version information:
```
1.0.0 1.13.3 sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)
```
...but the initialization is still present in ad0b7a1  on Oct 12, 2018

### Partial Fix:
Changing 
```result = np.empty([Vdim, nbin.prod()], float)```
to
```result = np.empty([Vdim, nbin.prod()], values.dtype)``` 
in `binned_statistic_dd()` would fix part of the problem - now, using the custom callable gives the correct results.

I have not submitted this change as a pull request of my own because I came across a problem that requires more thought by someone more familiar with scipy than myself:

It breaks usage with `values.dtype==int` and `statistic='mean'` - which is probably a more common use-case than complex values. Here, an accumulator initialized with `float` is the right choice.

**Comment by rgommers** [comment]
How about this?

    if np.iscomplexobj(values):
        result = np.empty([Vdim, nbin.prod()], values.dtype)
    else:
        # Use a float64 accumulator to avoid integer overflow
        result = np.empty([Vdim, nbin.prod()], float)

This feature is a bit tricky though. Using a 2-D histogram for a 1-D array of complex values makes sense I think, but shapes are going to be different, and there may be other issues. An n-D histogram for an n-D array doesn't make much sense probably. See e.g. https://stats.stackexchange.com/questions/33582/calculating-and-comparing-histograms-of-complex-numbers. So while we could support this, I don't think we should advertise it.

**Comment by ToBeckmann** [comment]
`np.iscomplexobj` appears to be the right tool - it wasn't part of my numpy vocabulary so far, thanks for bringing it to my attention.

Re: feature trickiness - the function is named `binned_statistic_2d`. It is not "histogram", although that is probably a common use case. More importantly, `statistic='count'` is defined just fine. My question is about: `(x: real, y: real, values: complex)` - you can count/bin any type of data on a 2D (real) grid. If I understand your comment (and the link) correctly, the issue is with complex-valued bin edges. My issue is with real bins containing complex data.

Going through the values for `statistic=` as per documentation:
* The default is `statistic=mean`, which, like `sum`, is unambiguous for complex values. 
* `count` should work, see above.
* `min` and `max` give problems (the clumsy `argmin(abs(z))` is probably the most useful). 
* `median` makes little sense. I have some use-cases for `argmedian(angle(z))`, but they may be rather domain-specific.
* user-defined 'function's require users to think about their data anyways.

To me, enabling complex use with `mean`, `sum` and `function` feels like fixing something. (Re-reading the documentation, I cannot find and hint that the function should not accept complex values Putting a warning in place for use with the sorting functions is probably a good idea, though.

**Comment by rgommers** [comment]
Good points, thanks @ToBeckmann. I agree it would be good to improve support for complex. If you could send a PR, that would be great.
