### ISSUE TITLE
Excuse me，Is there an optimization algorithm for carrying SCAD in Scipy？

### ISSUE THREAD

**Issue by Abraxas2071** [scipy/scipy#9714]
SCAD：http://www.personal.psu.edu/ril4/research/penlike.pdf

I try to do it on my own and it's always not right

**Comment by josef-pkt** [comment]
I added it to statsmodels, but it's currently mainly the framework with Mixin class and no direct user facing class yet. In unit tests and examples I just use a subclass that does not specify anything extra.
https://github.com/statsmodels/statsmodels/pull/4576
https://github.com/statsmodels/statsmodels/pull/4683
Scad itself is implemented as separate Penalty class, together with a few other ones.
We also have a new, not yet merged PR to add SCAD to GEE which works directly with the estimating equations and thresholding.

The penalized mixin class in statsmodels just defines the penalized likelihood function and similar, the optimization in fit uses the usual scipy optimizers.

**Comment by Abraxas2071** [comment]
> I added it to statsmodels, but it's currently mainly the framework with Mixin class and no direct user facing class yet. In unit tests and examples I just use a subclass that does not specify anything extra.
> [statsmodels/statsmodels#4576](https://github.com/statsmodels/statsmodels/pull/4576)
> [statsmodels/statsmodels#4683](https://github.com/statsmodels/statsmodels/pull/4683)
> Scad itself is implemented as separate Penalty class, together with a few other ones.
> We also have a new, not yet merged PR to add SCAD to GEE which works directly with the estimating equations and thresholding.
> 
> The penalized mixin class in statsmodels just defines the penalized likelihood function and similar, the optimization in fit uses the usual scipy optimizers.

@josef-pkt 
So it can't be used now?

**Comment by josef-pkt** [comment]
It's in statsmodels master. The current and most reliable documentation is looking at the unit test examples
https://github.com/statsmodels/statsmodels/blob/master/statsmodels/base/tests/test_penalized.py

It's newly merged code (even though it was mostly written in 2015), so still not matured and subject to change.
I have a generalized additive model, GAM, PR that should be merged within a few days and is the first official subclass of PenalizedMixin. This PR includes some changes to the generic classes https://github.com/statsmodels/statsmodels/pull/5370/files but also provides unit tests against GAM models in R.

**Comment by Abraxas2071** [comment]
@josef-pkt 
d(´ω｀*)~ So the question is, why are you so good ~o(￣▽￣)ｄ

**Comment by rgommers** [comment]
SCAD is not easily searchable, so in case the pdf link (which is to the original Fan & Li paper) disappears: it stands for "smoothly clipped absolute deviation".

Question is answered and a solution is available in `statsmodels`, so this can be closed.
