### ISSUE TITLE
scipy.optimize.minimize(f, [array_of_length_1], method="Powell").x.shape is ()

### ISSUE THREAD

**Issue by gyu-don** [scipy/scipy#9715]
When minimize single parameter function like `lambda x: x*x` with `scipy.optimize.minimize`, 
Only Powell method returns zero-dimensions array. (Other methods return one-dimension array)

I wrote test code to check all methods which described in [SciPy v1.2.0 Reference Guide](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html).
Code is https://github.com/gyu-don/scipy/commit/e0d698d8e0bfd5862a2245174e462e8c3ed468c9
All methods except Powell are returns one-dimension array.

### Reproducing code example:

```
import numpy as np
import scipy.optimize

def fun(x):
    return x*x

res = scipy.optimize.minimize(fun, [0.1], method="Nelder-Mead")
print("Nelder-Mead:")
print("Optimized:", res.x, "Shape:", res.x.shape)
res = scipy.optimize.minimize(fun, [0.1], method="COBYLA")
print("COBYLA:")
print("Optimized:", res.x, "Shape:", res.x.shape)
res = scipy.optimize.minimize(fun, [0.1], method="Powell")
print("Powell:")
print("Optimized:", res.x, "Shape:", res.x.shape)
```

Above code uses only 3 methods.
pytest code is available here.
https://github.com/gyu-don/scipy/commit/e0d698d8e0bfd5862a2245174e462e8c3ed468c9

### Output:

```
Nelder-Mead:
Optimized: [1.94289029e-16] Shape: (1,)
COBYLA:
Optimized: [0.00010234] Shape: (1,)
Powell:
Optimized: 4.163336342344337e-17 Shape: ()
```

### Scipy/Numpy/Python version information:

```
1.3.0.dev0+e0d698d 1.16.0 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)
```

### Solution?
Remove the line `x = np.squeeze(x)` in scipy/optimize/optimize.py, then, Powell returns one-dimention array. https://github.com/gyu-don/scipy/commit/763da791f6836c10186be278251735a41582b84a
If this solution is acceptable, I will submit pull request.

**Comment by rgommers** [comment]
thanks @gyu-don, it looks to me like this could be considered a bug. it would be good for `minimize(..., method='Powell')` to be consistent with the other methods. We would like to not change `fmin_powell` behavior though I think, for backwards compatibiliy reasons. So perhaps the `squeeze(x)` can be moved from `_minimize_powell` to `fmin_powell`.

that's also not optimal, but probably the best choice here.

**Comment by gyu-don** [comment]
thanks @rgommers.
> So perhaps the `squeeze(x)` can be moved from `_minimize_powell` to `fmin_powell`.
It went well. I submitted a PR.

**Comment by cyberspace1988** [comment]
Finding them
