### ISSUE TITLE
DOC: docstring inconsistency in RectBivariateSpline

### ISSUE THREAD

**Issue by mirca** [scipy/scipy#9718]
The docstring of the smoothing factor `s` of the class `RectBivariateSpline` mentions the vector `w` as part of the estimation condition:
https://github.com/scipy/scipy/blob/90534919e139d2a81c24bf08341734ff41a3db12/scipy/interpolate/fitpack2.py#L1152

However, it looks like the class `RectBivariateSpline` doesn't take `w` as input. I believe this is an inconsistency in the docstring?

**Comment by erheron** [comment]
Hi! I'm looking into this one now, and I've got a feeling that someone, long ago has copied this line from documentation of I don't know, `UnivariateSpline` class (just my guess), and now it's completely nonsense. I can't see `w` initialized or used nowhere  up to root of inheritance. One more thing is that `s` is used only in one place:
```
https://github.com/scipy/scipy/blob/ce0e23ecd77a772d56f4ab2252f9c4d25be30013/scipy/interpolate/fitpack2.py#L1187
```
and I literally can't find what does `regrid_smth` do. This `w` there is bug for sure

**Comment by rgommers** [comment]
Closing in favor of gh-11756. Thanks @mirca and @erheron
