### ISSUE TITLE
in constrained optimization eqp_kktfact bug and not used

### ISSUE THREAD

**Issue by szat** [scipy/scipy#9727]
Hello,
I was just looking into 
https://github.com/scipy/scipy/tree/master/scipy/optimize/_trustregion_constr
eqp_kktfact in qp_subproblem.py does not seem to be used anywhere and there is a dimension mismatch. 
Just saying, 
Adrian

**Comment by rgommers** [comment]
@szat do you have a standalone code example that shows an issue? It is used in the tests, and the comment above it says
```
# For comparison with the projected CG
```
so this does not seem like a valid bug report.
