### ISSUE TITLE
DOC: scipy.integrate.solve_ivp

### ISSUE THREAD

**Issue by keithbriggs** [scipy/scipy#9728]
https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html

This omits a crucial piece of information: does vectorized=True correspond to the first option for fun, or the second?

**Comment by MatthewFlamm** [comment]
Are you referring to `t` and `y` in `fun`?  According to [fun](https://github.com/scipy/scipy/blob/v1.2.0/scipy/integrate/_ivp/ivp.py#L181-L190) documentation,  `vectorized` only changes the behavior of `y`, and `t` is always a scalar.  If this isn't true, then this is a mistake in the documentation.

```
    fun : callable
        Right-hand side of the system. The calling signature is ``fun(t, y)``.
        Here ``t`` is a scalar, and there are two options for the ndarray ``y``:
        It can either have shape (n,); then ``fun`` must return array_like with
        shape (n,). Alternatively it can have shape (n, k); then ``fun``
        must return an array_like with shape (n, k), i.e. each column
        corresponds to a single column in ``y``. The choice between the two
        options is determined by `vectorized` argument (see below). The
        vectorized implementation allows a faster approximation of the Jacobian
        by finite differences (required for stiff solvers).
```

**Comment by keithbriggs** [comment]
Yes, that's what I'm referring to.   The point is that the documentation neglects to say whether vectorized=True is the (n,) shape or the (n,k) shape.  I guess it's the latter, but documentation is supposed to be explicit.  New users should not have to guess.

**Comment by MatthewFlamm** [comment]
Now it is clear to me what you are referring to.  I agree that it should be made explicit.
