### ISSUE TITLE
Error in CG solver

### ISSUE THREAD

**Issue by colehawkins** [scipy/scipy#9745]
It seems like there's an error in the conjugate gradient solver. The system below has a simple solution x=[0,1,1] but the cg solver doesn't find it for me. Instead it prints (array([-0.48101216,  2.14430745,  2.14430745]), 30). I tested a few other scipy solvers that work fine.

```
import numpy as np
import scipy 
from scipy import sparse
from scipy.sparse import linalg
A = np.eye(3)
A[0,1] = 1
b = np.ones(3)
print(sparse.linalg.cg(A,b))
```

**Comment by pv** [comment]
CG only works for hermitian matrices.
