### ISSUE TITLE
lfilter and sosfilt should be optimized

### ISSUE THREAD

**Issue by larsoner** [scipy/scipy#9750]
From @sturlamolden in https://github.com/scipy/scipy/pull/9711#issuecomment-460055116:

> ...  looking at the lfilter and sosfilt codebase I am shocked. First let me start with lfilter: How is it possible to have such an enormous overhead for a simple task like this? The work it does in Python and C, before doing any computation, is almost ridiculous. Then sosfilter is calling lfilter repeatedly even though (1) the overhead is insane and (2) we know that the filter sections are second order. As for the latter issue, it would be much more efficient to manually unroll the loop of the second order filters. Add to this that we are now releasing and aquiring the GIL for each lfilter call... Seriously, we have to clean this up, both lfilter and sosfilter.
>
> lfilter needs to have its overhead drastically reduced. Move the whole damn thing to Cython?
>
> sosfilt needs to have the cascading filter sections called in C, not by calling lfilter from Python, and the filter kernel should be unrolled so the compiler can vectorize it.

As I mentioned over there, I might take a stab at Cythonizing one or both of `lfilter` and `sosfilt`, unless someone is keen on doing it.

**Comment by sturlamolden** [comment]
Cythonizing the compute kernels for ```lfilter``` and ```sosfilt``` is what we need to do. That is, the code which is now in ```sigtools._linear_filter```. We need one kernel for each, so ```sosfilt```can avoid a lot of overhead. After this we can just remove lfilter.c.src.

**Comment by larsoner** [comment]
Makes sense, I'll close this in favor of #4669. @sturlamolden if you think there are still areas of improvement for `lfilter`, let's continue to discuss and possibly reopen this.
