### ISSUE TITLE
Why doesn't “beta.fit” come out right？Please take a look at it for me

### ISSUE THREAD

**Issue by Abraxas2071** [scipy/scipy#9754]
```python
distribution_type = getattr(stats, 'beta')  # 共轭分布为beta分布，参考《Introduction to Empirical Bayes》
observed = pd.read_excel('retention.xlsx')
print(observed['and_retention'].values)
a, b = distribution_type.fit(observed['and_retention'].values)[:2]
print(a, b, sep='\n')
ax = plt.subplot(111)
ax.plot(np.linspace(0, 1, 100), stats.beta.pdf(np.linspace(0, 1, 100), a, b))
ax.hist(observed['and_retention'].values, alpha=0.75, color='green', bins=104)
plt.show()
```

“print” out：
> [0.294  0.2955 0.235  0.2536 0.2423 0.2844 0.2099 0.2355 0.2946 0.3388
 0.2202 0.2523 0.2209 0.2707 0.1885 0.2414 0.2846 0.328  0.2265 0.2563
 0.2345 0.2845 0.1787 0.2392 0.2777 0.3076 0.2108 0.2477 0.234  0.2696
 0.1839 0.2344 0.2872 0.3224 0.2152 0.2593 0.2295 0.2702 0.1876 0.2331
 0.2809 0.3316 0.2099 0.2814 0.2174 0.2516 0.2029 0.2282 0.2697 0.3424
 0.2259 0.2626 0.2187 0.2502 0.2161 0.2194 0.2628 0.3296 0.2323 0.2557
 0.2215 0.2383 0.2166 0.2315 0.2757 0.3163 0.2311 0.2479 0.2199 0.2418
 0.1938 0.2394 0.2718 0.3297 0.2346 0.2523 0.2262 0.2481 0.2118 0.241
 0.271  0.3525 0.2323 0.2513 0.2313 0.2476 0.232  0.2295 0.2645 0.3386
 0.2334 0.2631 0.226  0.2603 0.2334 0.2375 0.2744 0.3491 0.2052 0.2473
 0.228  0.2448 0.2189 0.2149]
6.056697373013153
409078.57804704335

The α and β  is out of whack（α=6.056697373013153，β=409078.57804704335）
The fitting image is also unreasonable. The fitted beta distribution is almost the same as the straight line

**Comment by ilayn** [comment]
Hi @abraxas2071. If your code is not self-compilable, it is not possible for us to help you. But also you might want to ask such usage questions on stackoverflow to increase your chances of getting better answers. We are mostly interested in issues related to SciPy code on this repository.

**Comment by Abraxas2071** [comment]
> Hi @Abraxas2071. If your code is not self-compilable, it is not possible for us to help you. But also you might want to ask such usage questions on stackoverflow to increase your chances of getting better answers. We are mostly interested in issues related to SciPy code on this repository.

@ilayn 
Our Dear llhan~

> [0.294 0.2955 0.235 0.2536 0.2423 0.2844 0.2099 0.2355 0.2946 0.3388
0.2202 0.2523 0.2209 0.2707 0.1885 0.2414 0.2846 0.328 0.2265 0.2563
0.2345 0.2845 0.1787 0.2392 0.2777 0.3076 0.2108 0.2477 0.234 0.2696
0.1839 0.2344 0.2872 0.3224 0.2152 0.2593 0.2295 0.2702 0.1876 0.2331
0.2809 0.3316 0.2099 0.2814 0.2174 0.2516 0.2029 0.2282 0.2697 0.3424
0.2259 0.2626 0.2187 0.2502 0.2161 0.2194 0.2628 0.3296 0.2323 0.2557
0.2215 0.2383 0.2166 0.2315 0.2757 0.3163 0.2311 0.2479 0.2199 0.2418
0.1938 0.2394 0.2718 0.3297 0.2346 0.2523 0.2262 0.2481 0.2118 0.241
0.271 0.3525 0.2323 0.2513 0.2313 0.2476 0.232 0.2295 0.2645 0.3386
0.2334 0.2631 0.226 0.2603 0.2334 0.2375 0.2744 0.3491 0.2052 0.2473
0.228 0.2448 0.2189 0.2149]

These are the data, and you can try the code to fit them

**Comment by ilayn** [comment]
Could you edit your question and make the code self-containing please such that we can copy paste directly?

**Comment by Abraxas2071** [comment]
````python
distribution_type = getattr(stats, 'beta')  # 共轭分布为beta分布，参考《Introduction to Empirical Bayes》
observed = [0.294 0.2955 0.235 0.2536 0.2423 0.2844 0.2099 0.2355 0.2946 0.3388
0.2202 0.2523 0.2209 0.2707 0.1885 0.2414 0.2846 0.328 0.2265 0.2563
0.2345 0.2845 0.1787 0.2392 0.2777 0.3076 0.2108 0.2477 0.234 0.2696
0.1839 0.2344 0.2872 0.3224 0.2152 0.2593 0.2295 0.2702 0.1876 0.2331
0.2809 0.3316 0.2099 0.2814 0.2174 0.2516 0.2029 0.2282 0.2697 0.3424
0.2259 0.2626 0.2187 0.2502 0.2161 0.2194 0.2628 0.3296 0.2323 0.2557
0.2215 0.2383 0.2166 0.2315 0.2757 0.3163 0.2311 0.2479 0.2199 0.2418
0.1938 0.2394 0.2718 0.3297 0.2346 0.2523 0.2262 0.2481 0.2118 0.241
0.271 0.3525 0.2323 0.2513 0.2313 0.2476 0.232 0.2295 0.2645 0.3386
0.2334 0.2631 0.226 0.2603 0.2334 0.2375 0.2744 0.3491 0.2052 0.2473
0.228 0.2448 0.2189 0.2149]
a, b = distribution_type.fit(observed)[:2]
ax = plt.subplot(111)
ax.plot(np.linspace(0, 1, 100), stats.beta.pdf(np.linspace(0, 1, 100), a, b))
ax.hist(observed, alpha=0.75, color='green', bins=104)
plt.show()
````
I don't know how to make you copy and paste, is that right?

**Comment by ilayn** [comment]
If I copy your code and paste into my editor it doesn't compile. That's the only thing needed to replicate your problem.

**Comment by Abraxas2071** [comment]
> If I copy your code and paste into my editor it doesn't compile. That's the only thing needed to replicate your problem.

@ilayn 
Our Dear llhan~
I've put commas on the data

**Comment by WarrenWeckesser** [comment]
The `beta` distribution has *four* parameters: alpha, beta, location and scale.  In the line

    a, b = distribution_type.fit(observed['and_retention'].values)[:2]

you discarded the location and scale parameters.  When you computed the PDF with the expression

    stats.beta.pdf(np.linspace(0, 1, 100), a, b)

you did not specify the location and scale parameters, so the default values of 0 and 1 (respectively) were used.  So it is no surprise that the plot of the PDF does not match the histogram.

Try changing the `fit` call to 

    a, b, loc, scale = distribution_type.fit(observed['and_retention'].values)

and then change the computation of the PDF to use

    stats.beta.pdf(np.linspace(0, 1, 100), a, b, loc, scale)

A separate problem is that, in order for the histogram's vertical scale to match the PDF, you need to use the argument `density=True`:

    ax.hist(observed, alpha=0.75, color='green', bins=104, density=True)

**Comment by Abraxas2071** [comment]
> The `beta` distribution has _four_ parameters: alpha, beta, location and scale. In the line
> 
> ```
> a, b = distribution_type.fit(observed['and_retention'].values)[:2]
> ```
> you discarded the location and scale parameters. When you computed the PDF with the expression
> 
> ```
> stats.beta.pdf(np.linspace(0, 1, 100), a, b)
> ```
> you did not specify the location and scale parameters, so the default values of 0 and 1 (respectively) were used. So it is no surprise that the plot of the PDF does not match the histogram.
> 
> Try changing the `fit` call to
> 
> ```
> a, b, loc, scale = distribution_type.fit(observed['and_retention'].values)
> ```
> and then change the computation of the PDF to use
> 
> ```
> stats.beta.pdf(np.linspace(0, 1, 100), a, b, loc, scale)
> ```
> A separate problem is that, in order for the histogram's vertical scale to match the PDF, you need to use the argument `density=True`:
> 
> ```
> ax.hist(observed, alpha=0.75, color='green', bins=104, density=True)
> ```

Our Dear Warren！Thank you！Thank you！
Indeed, your response led me to plot a Beta distribution that is not a straight line

But don't you think alpha and beta are strange?Calculated according to the expected value of beta distribution, 6.05/(6.05+409078.57)=1.47891162469e-05。This seems counterintuitive
The data of average is about 0.25

**Comment by WarrenWeckesser** [comment]
The formula for the mean α/(α+β) is only valid for loc=0 and scale=1.  Here's the mean for all four parameters computed using your data:

    In [22]: beta.mean(a, b, loc, scale)
    Out[22]: 0.25147521075116097

As you expected, the value is about 0.25.

**Comment by WarrenWeckesser** [comment]
I suspect you'll want to follow the alternative suggestion that I made in my second comment: use the standard beta distribution with location 0 and scale 1.  Here's a modified version of your script that does that:


	import numpy as np
	from scipy import stats
	import matplotlib.pyplot as plt


	observed = [0.294, 0.2955, 0.235, 0.2536, 0.2423, 0.2844, 0.2099, 0.2355, 0.2946, 0.3388,
	            0.2202, 0.2523, 0.2209, 0.2707, 0.1885, 0.2414, 0.2846, 0.328, 0.2265, 0.2563,
	            0.2345, 0.2845, 0.1787, 0.2392, 0.2777, 0.3076, 0.2108, 0.2477, 0.234, 0.2696,
	            0.1839, 0.2344, 0.2872, 0.3224, 0.2152, 0.2593, 0.2295, 0.2702, 0.1876, 0.2331,
	            0.2809, 0.3316, 0.2099, 0.2814, 0.2174, 0.2516, 0.2029, 0.2282, 0.2697, 0.3424,
	            0.2259, 0.2626, 0.2187, 0.2502, 0.2161, 0.2194, 0.2628, 0.3296, 0.2323, 0.2557,
	            0.2215, 0.2383, 0.2166, 0.2315, 0.2757, 0.3163, 0.2311, 0.2479, 0.2199, 0.2418,
	            0.1938, 0.2394, 0.2718, 0.3297, 0.2346, 0.2523, 0.2262, 0.2481, 0.2118, 0.241,
	            0.271, 0.3525, 0.2323, 0.2513, 0.2313, 0.2476, 0.232, 0.2295, 0.2645, 0.3386,
	            0.2334, 0.2631, 0.226, 0.2603, 0.2334, 0.2375, 0.2744, 0.3491, 0.2052, 0.2473,
	            0.228, 0.2448, 0.2189, 0.2149]

	a, b = stats.beta.fit(observed, floc=0, fscale=1)[:2]

    print("a =", a, "  b =", b)

	ax = plt.subplot(111)
	ax.plot(np.linspace(0, 1, 100), stats.beta.pdf(np.linspace(0, 1, 100), a, b), 'k')
	ax.hist(observed, alpha=0.75, color='green', bins=104, density=True)
	plt.show()

The script prints

    a = 33.26401059422594   b = 99.0180817184922

and generates the following plot:

![figure_1](https://user-images.githubusercontent.com/321463/52200246-40156600-2836-11e9-9755-e082f75f638f.png)

**Comment by Abraxas2071** [comment]
> I suspect you'll want to follow the alternative suggestion that I made in my second comment: use the standard beta distribution with location 0 and scale 1. Here's a modified version of your script that does that:
> 
> ```
> import numpy as np
> from scipy import stats
> import matplotlib.pyplot as plt
> 
> 
> observed = [0.294, 0.2955, 0.235, 0.2536, 0.2423, 0.2844, 0.2099, 0.2355, 0.2946, 0.3388,
>             0.2202, 0.2523, 0.2209, 0.2707, 0.1885, 0.2414, 0.2846, 0.328, 0.2265, 0.2563,
>             0.2345, 0.2845, 0.1787, 0.2392, 0.2777, 0.3076, 0.2108, 0.2477, 0.234, 0.2696,
>             0.1839, 0.2344, 0.2872, 0.3224, 0.2152, 0.2593, 0.2295, 0.2702, 0.1876, 0.2331,
>             0.2809, 0.3316, 0.2099, 0.2814, 0.2174, 0.2516, 0.2029, 0.2282, 0.2697, 0.3424,
>             0.2259, 0.2626, 0.2187, 0.2502, 0.2161, 0.2194, 0.2628, 0.3296, 0.2323, 0.2557,
>             0.2215, 0.2383, 0.2166, 0.2315, 0.2757, 0.3163, 0.2311, 0.2479, 0.2199, 0.2418,
>             0.1938, 0.2394, 0.2718, 0.3297, 0.2346, 0.2523, 0.2262, 0.2481, 0.2118, 0.241,
>             0.271, 0.3525, 0.2323, 0.2513, 0.2313, 0.2476, 0.232, 0.2295, 0.2645, 0.3386,
>             0.2334, 0.2631, 0.226, 0.2603, 0.2334, 0.2375, 0.2744, 0.3491, 0.2052, 0.2473,
>             0.228, 0.2448, 0.2189, 0.2149]
> 
> a, b = stats.beta.fit(observed, floc=0, fscale=1)[:2]
> 
> print("a =", a, "  b =", b)
> 
> ax = plt.subplot(111)
> ax.plot(np.linspace(0, 1, 100), stats.beta.pdf(np.linspace(0, 1, 100), a, b), 'k')
> ax.hist(observed, alpha=0.75, color='green', bins=104, density=True)
> plt.show()
> ```
> The script prints
> 
> ```
> a = 33.26401059422594   b = 99.0180817184922
> ```
> and generates the following plot:
> 
> ![figure_1](https://user-images.githubusercontent.com/321463/52200246-40156600-2836-11e9-9755-e082f75f638f.png)

Thank you！Thank you！Our Dear Warren~
I drew the same graph as you, and as I said the Y-axis height is different, does that mean the fitting is bad?Or am I doing something wrong?

Sorry，I'm Chinese，English is not my forte，please forgive me。

**Comment by Abraxas2071** [comment]
> > I drew the same graph as you, and as I said the Y-axis height is different,
> 
> Sorry, I don't understand the problem that you still have. In my plot, the PDF is plotted as a black curve, and the (normalized) histogram is plotted with green bars. The green bars do not agree _exactly_ with the PDF, which is normal. Modelling the data with a beta distribution is just an approximation, and even if the data was known to come from an beta distribution, it is just one sample, so it won't match the PDF exactly.

Uh huh~

**Comment by mdhaber** [comment]
@Abraxas2071 I think you are not seeing as good agreement as in the example you sent because:

- The number of bins in your histogram is too high
- You don't have as many data points as in the example you sent

Eliminating `bins=104` so that the default takes over, I get very reasonable agreement:
![image](https://user-images.githubusercontent.com/6570539/100723766-0997cc00-3377-11eb-9ae3-070be1b8e1d6.png)

I'll go ahead and close this. If you think there is a bug in SciPy, or if there was a feature request that I missed, please re-open.
