### ISSUE TITLE
linalg.svd fails with a normal np.ndarray

### ISSUE THREAD

**Issue by ribes96** [scipy/scipy#9758]
A while ago I submited #9620. I overtook that problem by installing Anaconda, since it was a problem about a linked library from PyPI, and with the Anaconda installation it did not fail.
Well, now I came across with another another ndarray for which svd fails. Again, it does not contain NaNs. It is this one:
[problematic_array.zip](https://github.com/scipy/scipy/files/2828944/problematic_array.zip)

For the previous issue I found it did not fail in all machines, even when I installed from PyPI.
It fails with with the scipy and the numpy versions of svd

### Reproducing code example:

```
import numpy as np
from numpy.linalg import svd as numpy_svd
from scipy.linalg import svd as scipy_svd

path = 'problematic_array.npy'
X = np.load(path)

print(np.isnan(X).any())
# False

scipy_svd(X)
# Fails

numpy_svd(X)
# Fails
```

### Error message:

```
---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
<ipython-input-9-2829ad873ab1> in <module>
      9 # False
     10 
---> 11 scipy_svd(X)
     12 # Fails
     13 

~/anaconda3/lib/python3.7/site-packages/scipy/linalg/decomp_svd.py in svd(a, full_matrices, compute_uv, overwrite_a, check_finite, lapack_driver)
    130 
    131     if info > 0:
--> 132         raise LinAlgError("SVD did not converge")
    133     if info < 0:
    134         raise ValueError('illegal value in %d-th argument of internal gesdd'

LinAlgError: SVD did not converge
```

### Scipy/Numpy/Python version information:

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
```

I'm not sure if it would be better to comment on the previous issue. It seems to be a different problem, since it fails in a different ndarray

**Comment by larsoner** [comment]
One more, thing, what is `np.show_config()`?

**Comment by larsoner** [comment]
... and does it work with `scipy.linalg.svd(x, lapack_driver='gesvd')`?

**Comment by larsoner** [comment]
I ask because if you are on Intel hardware running MKL, it could be related to https://github.com/scipy/scipy/pull/5994, https://github.com/ContinuumIO/anaconda-issues/issues/695, and https://software.intel.com/en-us/comment/1869912.

FWIW I cannot reproduce on Linux x86_64 built with Ubuntu system OpenBLAS.

**Comment by ribes96** [comment]
> One more, thing, what is np.show_config()?

```
>>> np.show_config()
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/hobber/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/hobber/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/hobber/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/hobber/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/hobber/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/hobber/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/hobber/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/hobber/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/hobber/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/hobber/anaconda3/include']
```
> ... and does it work with scipy.linalg.svd(x, lapack_driver='gesvd')?

Yes, it does work with that driver. However, numpy version doen't have that option

BTW, I'm also in Ubuntu
```
$ uname -a
Linux hal 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by larsoner** [comment]
Can you try the `.npy` arrays I posted in the Intel issue, and if some of them fail, report so there? It would be good for them to know that other people have this problem, too. Feel free to also give them a link to your failing `npy` file.

In the meantime I'll close since this seems to be an MKL `gesdd` issue.

**Comment by ribes96** [comment]
I could not reproduce in ANY of the arrays, neither in the Intel issue nor in the Anaconda issue. I don't know if it is supposed to be fixed or not, but svd worked perfectly with all of them.
Maybe this issue is not related.
I tested this one in a different machine (also Intel and Anaconda) with Windows 10, and svd worked fine.
@larsoner, do you still think it is a good idea to submit that matrix in Intel issue? It would be good to find more people who can reproduce this issue.

**Comment by larsoner** [comment]
Oh I remember there was a workaround -- try running Python with `OMP_NUM_THREADS=1 python` and see if it works. If it does, then it's probably the same bug, just manifesting differently on different hardware. (I got the error on different arrays with different CPUs.)

**Comment by ribes96** [comment]
With `OMP_NUM_THREADS=1 python` it worked fine. I'll submit it then

**Comment by ribes96** [comment]
Now I have a real problem, since OpenBlas fails with #9620 and MKL fails with this one. It fails in a long process in Scikit-learn which doesn't give me direct access to svd, so I can not use `lapack_driver='gesvd'`. Also, it is a costly process about Machine Learning, and so I guess using `OMP_NUM_THREADS=1 python` will increase a lot the computation time.
Would you advice me on what to do?

**Comment by ilayn** [comment]
For confirmation, I don't have any problems with the recent OpenBlas Win 10, SciPy dev, NumPy dev versions with either of the issues. Both give me sensible numerical results (didn't check their correctness),

**Comment by ribes96** [comment]
In fact, I was updating to NumPy 1.16 when it came to my mind switching to Anaconda. As it seemed to work, I forgot about NumPy 1.16. It does work with the current version, so I'll come back.
Only problem is that scipy version doesn't work yet, and scikit-learn uses the that version. Maybe the idea is to update OpenBlas for the next release. In the meantime, I guess I will have to modify scikit's .py file to use the NumPy version of svd
