### ISSUE TITLE
scipy.stats.poisson.interval gives the wrong result

### ISSUE THREAD

**Issue by harmbuisman** [scipy/scipy#9762]
scipy.stats.poisson.interval gives the wrong result
for the example below it gives (1,14), whereas (0,14) is expected

The interval (1,14) does not cover at least 0.99 of the distribution, as can be checked using the cdf method, hence the answer is wrong.

### Reproducing code example:

```
import scipy
print(scipy.__version__)
from scipy.stats import poisson

alpha = 0.99
expected = 6.298487833
pint = poisson.interval(alpha,expected)
covered = poisson.cdf(pint[1],expected)-poisson.cdf(pint[0],expected)

print(pint)
print(covered)
print("Correct" if covered >= alpha else "Incorrect: {} is less than {}".format(covered, alpha))

# in this case I would expect (0, 14) as the interval:
poisson.cdf(14,expected)-poisson.cdf(0,expected)
```
Output:
```
1.2.0
(1.0, 14.0)
0.9843652848169578
Incorrect: 0.9843652848169578 is less than 0.99
0.9959487309808245
```

### Scipy/Numpy/Python version information:

```
1.2.0 1.15.4 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)
```

**Comment by josef-pkt** [comment]
AFAIR, the interval points are inclusive

i.e. for discrete the lower tail probability is cdf(low - 1) and not cdf(low) which puts the low point in the tail and outside the interval

**Comment by harmbuisman** [comment]
> AFAIR, the interval points are inclusive
> 
> i.e. for discrete the lower tail probability is cdf(low - 1) and not cdf(low) which puts the low point in the tail and outside the interval

Ah yes, indeed, thanks for your reply. Closed
