### ISSUE TITLE
TST: Minimum NumPy version is not being CI tested

### ISSUE THREAD

**Issue by tylerjereddy** [scipy/scipy#9784]
Although we have a Travis job labelled as testing the lowest-supported NumPy version for master (`1.13.3`), when I check its logs I see `1.13.3` being removed and `1.16` being added because of the build idiosynacracies.

If we're going to support `1.13.3`, we need the test suite genuinely running on it in CI, and I can tell you right now it does not pass based on my bisection efforts in #9777.

**Comment by tylerjereddy** [comment]
sample log from the `1.13.3` Travis job in a recent PR: https://api.travis-ci.org/v3/job/490293220/log.txt

**Comment by tylerjereddy** [comment]
See #9777 for identification of the pertinent `f2py`-related commit in NumPy.

**Comment by rgommers** [comment]
hmm, that's annoying. let's deal with v1.2.1 first I suggest, but if you've figured out the build issue and it's easy to fix the problem in a PR so we see all current issues with 1.13.3 + master, that would be useful

**Comment by tylerjereddy** [comment]
This has been resolved in master & will likely soon be resolved on the LTS branch too.
