### ISSUE TITLE
Master Tracker for some Kolmogorov-Smirnov test Issues

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#9797]
There are a number of Issues relating to Kolmogorov-Smirnov computations, and a number of open/merged PRs dealing with the Issues. The correspondence is not 1-1, so here is a table to track the correspondence, and may provide greater context to the 3-PR sequence #9719, #9753 and a future ~~"PR3"~~ #11710.

Issue  | description                                                                         | PRs
----- | ----------------------------------------------------------------------------------- | ---
#9786 | `stats.ks_2samp()` misleading for small data sets.                                    | #9753
#8748 | `scipy.stats.kstest` for same distribution: p-values nonuniform            | #8737, #9719, ~~PR3?~~ #11710
#8341 | `scipy.stats.ks_2samp` for masked and unmasked data give different results            | #9719, ~~PR3?~~ #11710
#7492, #7456, #7455, #7426 | `scipy.special.{kolmogorov,kolmogi}`,  `scipy.special.{smirnov,smirnovi}`  and `scipy.stats.ksone(n).pdf` inefficient and/or inaccurate | #8737
#2765 | bugs stats entropy                                                                  | #8737, #9661 (for `ksone`, `kstwobign`)

#9719, #9753 and ~~"PR3"~~ #11710 should address open Issues from the list.  There are additional open Issues, some dating back as far as 2013, which I'm also looking at to understand if still relevant, or if they would be impacted by these PRs

### Scipy/Numpy/Python version information:
```
1.3.0.dev0+f013b27 1.16.0 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

**Comment by chrisb83** [comment]
Good idea to create an overview of all the issues. 

(I still have doubts whether #8748 is really an issue.)

**Comment by pvanmulbregt** [comment]
@chrisb83 I've decided that gh-8748 is indeed a real issue.  I've redone the computations using the 3 PRs (#9719, #9753 and PR3), and the results are much better, not showing the idiosyncracies exhibited in the Issue's plots.
