### ISSUE TITLE
LOBPCG produces incorrect results for symmetric matrices

### ISSUE THREAD

**Issue by prohle** [scipy/scipy#9809]
My issue is about using lobpcg. Setting largest= True or False produces the same result starting from a symmetric matrix of size 5x5 and above

### Reproducing code example:
``

```
import numpy as np
n = 5
# construct a random symmetric matrix
sample_random = np.random.rand(n, n)
symmetric_matrix = sample_random + sample_random.T

# construct a random vector
rand_vec = np.random.rand(n, 1)

# calculate the largest eigenvalue
largest_, _ = lobpcg(symmetric_mat, rand_vec, largest=True)

# calcualte the smallest eigenvalue
smallest_, _ = lobpcg(symmetric_mat, rand_vec, largest=False)
print(largest_, smallest_)

assert largest_ == smallest_
```

### Scipy/Numpy/Python version information:
1.1.0 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)

**Comment by tylerjereddy** [comment]
cc @lobpcg @rc 

There have been some changes for `1.2.1` & perhaps even more fixes on the way in master, but I'll let the experts comment on whether this report is related, from version `1.1.0`.

**Comment by rc** [comment]
This should be fixed in the new code, #9650: It gives for me:
```
In [14]: largest_, _ = lobpcg(symmetric_mat, rand_vec, largest=True)
In [15]: largest_
Out[15]: array([ 5.79999264])
In [16]: smallest_, _ = lobpcg(symmetric_mat, rand_vec, largest=False)
In [17]: smallest_
Out[17]: array([-0.72404404])

```

**Comment by tylerjereddy** [comment]
Ok, so should be fixed on master / by 1.3.0 release then.

**Comment by prohle** [comment]
Thanks for following up on this. I upgraded to 
1.2.1 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)

The problem appears to be fixed now.

**Comment by prohle** [comment]
Thanks for following up on this. I upgraded to 
1.2.1 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)

The problem appears to be fixed now.
