### ISSUE TITLE
stats.mode's nan_policy 'propagate' not working?

### ISSUE THREAD

**Issue by mcara** [scipy/scipy#9815]
I am not sure whether my issue is a bug or a mis-understanding of how `nan_policy='propagate'` setting in `scipy.stats.mode()` is supposed to work. Specifically, in the documentation it says:

> [`nan_policy`] Defines how to handle when input contains `nan`. `'propagate'` returns `nan` ...

However, I do not get `nan`. Why?

### Reproducing code example:
```
>>> import numpy as np
>>> from scipy import stats
>>> stats.mode([1., 1., 2., 3., 3., 3., np.nan], nan_policy='propagate').mode
array([3.])
>>> stats.mode([np.nan, np.nan, np.nan, 1., 1., 2., 3., 3., 3., np.nan],
...            nan_policy='propagate').mode
array([3.])
```

### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy
>>> print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.0 1.15.4 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

**Comment by chrisb83** [comment]
Hi, 

I think it just returns the most frequent value which is 3. You would get NaN If that is the most common value. This is arguably a reasonable behaviour (i.e. propagate means keep NaN and See what happens), but not in line with the documentation.

Code:

```
def _mode1D(a):
        vals, cnts = np.unique(a, return_counts=True)
        return vals[cnts.argmax()], cnts.max()
```

**Comment by mcara** [comment]
@chrisb83 
> I think it just returns the most frequent value which is 3.

My second example in the original post has `np.nan` as the most frequent value and `stats.mode` still returns `3.0`.

**Comment by chrisb83** [comment]
You are right, I did not see the second example.

It seems to be related to the nan-handling of `np.unique`, i.e. nan values are not grouped:

```
a = [np.nan, np.nan, np.nan, 1., 1., 2., 3., 3., 3., np.nan]
vals, cnts = np.unique(a, return_counts=True)
vals # array([ 1.,  2.,  3., nan, nan, nan, nan])
cnts # array([2, 1, 3, 1, 1, 1, 1], dtype=int64)
```

**Comment by Kai-Striega** [comment]
@chrisb83 I agree that this shouldn't be a defect in the code, but, a case of poor documentation. `nan_policy='propogate'` seems poorly documented in general. 

The documentation of `propagate` sounds like it should return nan *anytime* a nan value occurs. This does not seem right to me. Do you think cleaning up the documentation and providing the above example would make this more obvious?

**Comment by mcara** [comment]
@Kai-Striega wrote:

> The documentation of `propagate` sounds like it **should return nan _anytime_** a nan value occurs. **This does not seem right to me.**

1. It is not clear what documentation says but it is definitely _not_ that `mode()` would return `nan` _"anytime a `nan` value occurs"_ (i.e., even when one `nan` is in the input list).

2. What would be the right thing to do?

Let's look at three scenarios: 1) only one value in a larger data set is `nan`; 2) the majority of values in a data set are `nan`; 3) **all** values are `nan`.

_Currently_, `mode()` returns `nan` in the third scenario effectively behaving like `'omit'` except `0` in the returned array is replaced with `nan`. Personally, I do not find this to be a very useful feature. For example, if what I needed was third scenario, I could simply have something like `mode = np.nan if np.all(np.isnan(x)) else scipy.stats.mode(x)`. Similarly, if I wanted the first scenario, I could modify previous code by replacing `np.all->np.any`. I do not need `'propagate'` for this. The second scenario is the most difficult to do "by myself" (well, as a simple one-liner). Possibly my question is about the original intention for the `'propagate'` option.

**Comment by chrisb83** [comment]
> Do you think cleaning up the documentation and providing the above example would make this more obvious?

yes, I think a clarification in the doc and an example would be sufficient.

I think the behaviour of the function is fine: for me, propagate means to keep NaN values, then perform the calculation and see what happens. Often this results in NaN (e.g. if the calculation involves adding the elements), but in the case of `mode`, every NaN is simply counted as a single occurence (of course, this needs to be clearly stated).

**Comment by Kai-Striega** [comment]
@mcara sorry, I don't think I came across as clearly as I could have.

> It is not clear what documentation says but it is definitely _not_ that `mode()` would return `nan`

From the documentation of propagate:

https://github.com/scipy/scipy/blob/be3bcf99042f46344007621b006ff90258fed914/scipy/stats/stats.py#L408-L409

to me `'propagate' returns nan` implies `nan_policy='propagate'` should return, well, `nan`. Yes, even when one `nan` is in the input list. I'm not saying this is the best way, but what the documentation says should happen. This also seems to be the behaviour you were expecting in the original post ("However, I do not get `nan`. Why?").

> Possibly my question is about the original intention for the `'propagate'` option.

As @chrisb83 says above:

> propagate means keep NaN and see what happens

An example of the *usual* behaviour is `sem` (standard error of the mean) where, in any axis effected by a `nan` value, a `nan` value is returned:

    >>> import numpy as np
    >>> from scipy.stats import sem
    >>> a = np.arange(16, dtype=np.float64).reshape((4, 4))
    >>> sem(a) #sem with no nan values
    array([2.5819889, 2.5819889, 2.5819889, 2.5819889])
    >>> a[1, 1] = np.nan
    >>> sem(a, nan_policy='propagate')
    array([2.5819889,       nan, 2.5819889, 2.5819889])

However, as you have pointed out, `mode` does not follow this pattern. `mode` calls `np.unique` which (as shown above) treats all `nan` values as a unique element.

    >>> import numpy as np
    >>> from scipy.stats import mode
    >>> a = np.array([[1, 1, 2, 3], [1, 2, 2, np.nan], [1, 1, 1, np.nan]])
    >>> a
    array([[ 1.,  1.,  2.,  3.],
           [ 1.,  2.,  2.,  nan.],
           [ 1.,  1.,  1., nan]])
    >>> mode(a, nan_policy='propagate')
    ModeResult(mode=array([[1., 1., 2., 3.]]), count=array([[3, 2, 2, 1]]))

...which is not what you would expect based on the documented behaviour (return `nan`).

>     2. What would be the right thing to do?

As @chrisb83 said the behaviour seems reasonable (given his definition of propagate) but does not align with what is documented. The `nan` value is still propagated, but the behaviour is unusual. Enough so to warrant further explanation/examples.

**Comment by mcara** [comment]
@Kai-Striega Thank you very much for detailed and clear explanation.

**Comment by Kai-Striega** [comment]
As a follow-up, do you think these changes will be enough to clarify the behaviour?

 - [ ] Update documentation of `nan_policy='propagate'` to better describe the behaviour
 - [ ] Add an example to `mode` as the results differs from what usually occurs.

@mcara @chrisb83

**Comment by mcara** [comment]
My initial reaction was that proposed course of action should be enough. However, upon reading `sem` example from #9947, I do not think I would agree with some points expressed there.

From #9947:

> According to the docstrings, propagate should return nan if any nan values occur. **However**, the usual behaviour (as demonstrated by sem) is to perform the calculations, including nans, and see what happens. This will usually result in a nan value.

I guess I am confused about "However" because it sounds as if `sem()` is a counter-example of "should return nan if any nan values occur". I do not see it like that. IMO `sem()` actually illustrates that a `nan` is usually (should always be?) returned. In your example in https://github.com/scipy/scipy/issues/9947#issue-421770410 `sem` acts along axis 0 but if you modify your call as `sem(a, nan_policy='propagate', axis=None)` a `nan` will be returned. When a computation is performed along an axis, IMO it is "natural" to expect that computations along other axes are independent of one another.

Returning to the issue of `mode()`, I (almost) can't see when the mode would return a `nan`. For example, even when all values are unique, `nan` is never returned:

```python
>>> scipy.stats.mode([np.nan, -1, 0, 1])                                                                
ModeResult(mode=array([-1.]), count=array([1]))

>>> scipy.stats.mode([np.nan, -1, 0, 1, np.inf])                                                        
ModeResult(mode=array([-1.]), count=array([1]))
```

Only by adding **negative** infinity to the mix one can get `mode()` to return `np.nan`:

```python
>>> scipy.stats.mode([np.nan, -1, 0, 1, np.inf])                                                        
ModeResult(mode=array([-1.]), count=array([1]))
```

**Comment by mcara** [comment]
This leads to the question: what is the meaning of `nan_policy='propagate'` when applied to `mode()`? Therefore, maybe this is not only an issue of documentation but also of revisiting what it actually means (and maybe even dropping this option for `mode()` if it does not make any sense for it?)

**Comment by Kai-Striega** [comment]
> I guess I am confused about "However" because it sounds as if sem() is a counter-example of "should return nan if any nan values occur".

@mcara Yes, you're correct, the "However" should probably have been left out as it is confusing. I wanted to highlight what usually happens.

> When a computation is performed along an axis, IMO it is "natural" to expect that computations along other axes are independent of one another.

The documentation should make this explicit. A "natural" expectation may be different from person to person. e.g. ``returns nan`` could be interpreted as:

1. Returns a single nan value.
2. Returns an array of nans with the expected output's shape.
3. Returns an array with nans *only* where the calculation is affected.

Option 3 makes the most sense to me, but, if this is what should actually be happening, it should be explicitly stated in the documentation.

> Returning to the issue of mode(), I can't see when the mode would return a nan

I can't either. And is definitely **not** what should occur according to the (current) documentation.  IF we define propagate as *"propagate means keep NaN and see what happens"* this behaviour isn't **wrong**, only unusual.

> This leads to the question: what is the meaning of nan_policy='propagate' when applied to mode()? 

I was hoping #9947 would lead to some discussion about this. Based on the discussion here I agree with @chrisb83. The behaviour of `mode` is fine, BUT, the documentation should reflect the behaviour (as is happening in #9948).

**Comment by rgommers** [comment]
> Option 3 makes the most sense to me, but, if this is what should actually be happening, it should be explicitly stated in the documentation.

this is definitely what's intended to happen.

> Returning to the issue of mode(), I can't see when the mode would return a nan

When there are more `nan`s present than any other value I'd think?

**Comment by mcara** [comment]
> When there are more `nan`s present than any other value I'd think?

I was thinking the same but that is not what code does: currently all `nan`s are regarded as different and `mode()` _never_ returns `nan` (except when _all data values are `nan`). If the code is not changed, I think the `'propagate'` option should be removed as it is effectively equivalent to `'omit'` and its existence is confusing. In order to make `'propagate'` distinct from `'omit'`, I think one approach would be to consider all `nan` as a single value (i.e., all `nan`s are equal) though this would go against IEEE. I do not know what is the best approach, but from the usefulness point of view, I would personally prefer either to:

1. view all `nan`s as one value and return `nan` when most input values are `nan`;
2. make `nan` contaminate the result and thus return an `nan` even when one `nan` is present.

In the current approach, under most frequent situations, `'propagate'` is equivalent to `'omit'`.

By the way, `'omit'` itself is very weird in the sense that I do not get "naturally" (at least for me) expected results:

```python
>>> stats.mode([])                                                                                                                                                                                                                                                                                                                                       
ModeResult(mode=array([], dtype=float64), count=array([], dtype=float64))
```
However,
```python
>>> stats.mode([np.nan], nan_policy='omit')                                                                                                                                                                                                                                                                                                              
ModeResult(mode=array([0]), count=array([0]))
```
I would expect to get the first result because I would expect the code to drop all `nan`s (probably used by many to flag/mask "bad" data) before proceeding. Where did `0` in the answer come from?

**Comment by rgommers** [comment]
> > Returning to the issue of mode(), I can't see when the mode would return a nan

> I can't either. And is definitely not what should occur according to the (current) documentation. IF we define propagate as "propagate means keep NaN and see what happens" this behaviour isn't wrong, only unusual.

Yeah, the current implementation is odd. `mode` is a bit trickier than normal. For most functions it's easy to see what "propagating nans" means. Here the end result is implementation-specific, which isn't really desired. I think `stats.mode([2, np.nan, 1, np.nan])` should return `nan`, not `1`. If we had implemented it by counting nans with `np.isnan(a).sum()`, then the result would be (to me) more intuitive.

**Comment by WarrenWeckesser** [comment]
@chrisb83 wrote

> for me, propagate means to keep NaN values, then perform the calculation and see what happens.

I think that might be how the behavior of `'propagate'` was originally envisioned, but my impression is that experience with `nan_policy` is showing that approach to be a mistake.  These days, I suggest that when we add `nan_policy` to a function, we think carefully about how `nan` should be propagated (just like folks are doing in this pull request!), and then implement that behavior.  Otherwise, `nan` handling tends to be implementation-dependent, and the behavior could change if the implementation changes.  (See, for example, the surprising effect of propagating `nan` in `ndimage.uniform_filter` reported in https://github.com/scipy/scipy/issues/7818.  We don't have `nan_policy` implemented there, but if we did, I think we would still consider the existing behavior of that function undesired.)  In many cases, we can probably just let the `nan`s pass through to the regular calculation, so a special implementation is not required, and the only extra work involved is some up-front thinking about how `propagate` should behave, and then documenting it and providing some unit tests for it.

Another issue to consider is that there is not just one bit pattern that corresponds to `nan`. In the IEEE floating point representation of `nan`, the exponent bits are all one, but the sign bit can be 0 or 1, and the significand can have *any* nonzero value.  So there are many bit patterns that are interpreted as `nan`. Should `mode` treat `nan`s with different bit patterns as distinct values?  I don't have a strong opinion about this, and I suspect it will rarely come up in practice.  But whatever the preferred behavior, it should be specified in the docstring and tested in the unit tests.

**Comment by WarrenWeckesser** [comment]
@mcara wrote

> By the way, 'omit' itself is very weird in the sense that I do not get "naturally expected" (at least for me) results:

    >>> stats.mode([])                                                                                                                                                                                                                                                                                                                                       
    ModeResult(mode=array([], dtype=float64), count=array([], dtype=float64))

> However,

    >>> stats.mode([np.nan], nan_policy='omit')                                                                                                                                                                                                                                                                                                              
    ModeResult(mode=array([0]), count=array([0]))


That looks like a bug to me.  By the meaning of `'omit'`, those two calls should create the same result.  Note, however, that in the second example, `count` is `array([0])`.  So the function is saying that 0 is the mode, and it occurs 0 times.  I agree with you: that's just weird.

**Comment by mcara** [comment]
@WarrenWeckesser Thank you for confirming weird `'omit'` behavior. With regard to `'propagate'` I _personally_ prefer https://github.com/scipy/scipy/issues/9815#issuecomment-474128763 approach/suggested behavior (=all `nan`s are the same) but in the end the consistency and clarity is the most important for me: I can implement myself the desired behavior once I know how `mode()` behaves.

**Comment by mcara** [comment]
Should I open a separate issue for `'omit'` behavior or it can be handled here?

**Comment by WarrenWeckesser** [comment]
> Should I open a separate issue for 'omit' behavior [...]?

Yes, that's a good idea.  After I wrote my comment above, I realized that there is at least one case where the handling of `'omit'` requires doing something weird or slightly unexpected.  It would be better to continue the discussion in a separate issue.

**Comment by rgommers** [comment]
> Another issue to consider is that there is not just one bit pattern that corresponds to nan. In the IEEE floating point representation of nan, the exponent bits are all one, but the sign bit can be 0 or 1, and the significand can have any nonzero value. So there are many bit patterns that are interpreted as nan. Should mode treat nans with different bit patterns as distinct values?

This is why `np.unique` currently returns every `nan` as a distinct value. I think that's really not very relevant here though - from a statistics point of view I'd expect `count_number_of_values([nan, nan])` to return 2, not 1.

**Comment by mcara** [comment]
Opened 'omit' issue in https://github.com/scipy/scipy/issues/9955

**Comment by rgommers** [comment]
>  I think `stats.mode([2, np.nan, 1, np.nan])` should return `nan`, not `1`. If we had implemented it by counting nans with `np.isnan(a).sum()`, then the result would be (to me) more intuitive.

@Kai-Striega and @chrisb83 could you say what your preferred behavior is?

**Comment by Kai-Striega** [comment]
I agree returning `nan` is the more intuitive (and useful) solution. Given that `mode` is defined in a statistics module, most users would expect this behaviour regardless of the IEEE-754 standard.

**Comment by chrisb83** [comment]
Initially I considered it a documentation issue but following the discussion here, I think changing the behaviour of the function to actually count nan is better. This is what users expect and with the current behaviour, I don't see a use case for `propagate` (and `omit` already covers the behaviour as mcara stated above)

**Comment by mdhaber** [comment]
The consensus here seems to be that this is the desired behavior:
```
>>> stats.mode([2, np.nan, 1, np.nan])
ModeResult(mode=array([nan]), count=array([2]))
```
In fact, that _is_ the behavior is `main`; probably due to a change in `np.unique`.
```python3
a = [np.nan, np.nan, np.nan, 1., 1., 2., 3., 3., 3., np.nan]
vals, cnts = np.unique(a, return_counts=True)
vals  # array([ 1.,  2.,  3., nan])
cnts # array([2, 1, 3, 4], dtype=int64)
```

Unfortunately, there is still a problem when the input is an object array because `np.unique` is not used:
```python3
>>> stats.mode(np.array([2, np.nan, 1, np.nan], dtype='object'))
ModeResult(mode=array([1], dtype=object), count=array([1]))
```
The comment in the code:
> `# Fall back to a slower method since np.unique does not work with NaN`

Is not correct (currently, at least). Really, `np.unique` does not work for object arrays with mixed types when `<` is not supported. For instance,

```python3
a = np.array([10, True, 'hello', 10], dtype='object')
stats.mode(a)
```
has no NaNs but we get a `TypeError: '<' not supported between instances of 'str' and 'int'` because the alternate algorithm is not triggered.

Unfortunately, `np.isnan` doesn't work on object arrays, so the most obvious (to me) fix to the alternate algorithm doesn't work.

**Comment by mdhaber** [comment]
A good solution seems to be to remove the existing alternate algorithm and do:
```python3
    if a.dtype == object:
        def _mode1D(a):
            cntr = Counter(a)
            mode = max(cntr, key=lambda x: cntr[x])
            return mode, cntr[mode]
    else:
        def _mode1D(a):
            vals, cnts = np.unique(a, return_counts=True)
            return vals[cnts.argmax()], cnts.max()
```
In a test:
```python3
x = np.array(np.random.rand(10, 11, 12, 13), dtype='object')
stats.mode(x, axis=1)
```
the old algorithm for object arrays took 7 seconds on my machine. With this change, it takes about 20ms, and it treats object arrays with mixed types, including NaNs, as we would expect. (Incidentally, it is 4x faster than when `x = x.astype(float)` and `np.unique` is used instead of `Counter`. Presumably `np.unique` will win at some point?)

I'll fix this after gh-15423 merges.
