### ISSUE TITLE
Taking Advantage of Sparsity in CWT Sketch

### ISSUE THREAD

**Issue by cdipaolo** [scipy/scipy#9816]
Hi everyone! I'm wondering if there has been any further interest in taking advantage of sparsity into the CWT sketching method `scipy.linalg.clarkson_woodruff_transform(input_matrix, sketch_size, seed=None)`. It seems as if #8498 discussed this a year ago, resulting in PR #8579, but nothing was merged into master.

Would it be possible to integrate something like the example below into the `scipy` package in order to make the use of sketching methods practical? As seen below, if we implement the sketch using a sparse representation it performs better for both dense _and_ sparse matrices (in the specific example below, at least). Comments and critique are wholeheartedly welcome :)... I'd be willing to implement this if people are on board with that.

### Reproducing code example:

I ran a simple test which compared the performance of an exact least squares solver `numpy.linalg.lstsq(a, b, rcond=None)`, a sketched solution using the CWT which takes advantage of sparsity, and the same method but using the scipy CWT transform which does not take advantage of sparsity. The input dataset I used was generated from [the UCI bikesharing dataset](https://archive.ics.uci.edu/ml/datasets/Bike+Sharing+Dataset) in such a way that we have n=17379 samples and p=36 dimensional data. I can detail how this specifically produced the `A` and `b` arrays below if needed but I'll ignore that for now -- they are both dense `np.array`s to start.

```python
def sketch(k=10,n=100):
    '''sketch
    Implemenents Clarkson Woodruff sketch matrix
    as a scipy.coo sparse matrix.

    :param k: Sketching dimension. (int)
    :param n: Height of data matrix to be sketched. (int)
    :returns: scipy.coo_matrix representing a CWT transform.
    '''
    i = np.random.randint(0,k,n)
    j = list(range(n))
    data = np.random.binomial(1,0.5,n)*2 - 1
    return sparse.coo_matrix((data,(i,j)),shape=(k,n))

n = A.shape[0]
def sketched_obj(k=10):
    S  = sketch(k=k,n=n)
    SA = S @ A
    Sb = S @ b
    x_ = np.linalg.lstsq(SA,Sb,rcond=None)[0]
    return np.linalg.norm(A@x_ - b)

def sketched_obj_scipy(k=10):
    SAb  = scipy.linalg.clarkson_woodruff_transform(np.hstack((A,b.reshape(-1,1))), sketch_size=k)
    SA = SAb[:,:-1]
    Sb = SAb[:,-1]
    x_ = np.linalg.lstsq(SA,Sb,rcond=None)[0]
    return np.linalg.norm(A@x_ - b)

%timeit np.linalg.lstsq(A,b,rcond=None)[0]
%timeit sketch_solve(k=50)
%timeit sketch_solve(k=100)
%timeit sketch_solve(k=150)
%timeit sketch_solve(k=250)
%timeit sketch_solve_scipy(k=250)
%timeit sketch_solve_sparse(k=250)
```

This code gives the following results (which are noisy of course, but the rankings and relative improvement remains steady across runs). Note that even at k=250 (which has a median 1.226 and mean 1.231 approximation ratio over the exact solution, computed using 1000 samples), the sparse CWT-based least squares solver gives a ~35% speedup over an exact solver, while the current `scipy` implementation is ~178% _slower_ than the exact solver which does not take advantage of sparsity.

```
Exact Solver: 13.3 ms ± 863 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Sparse CWT Solver (k=50): 8.29 ms ± 198 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Sparse CWT Solver (k=100): 8.46 ms ± 228 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Sparse CWT Solver (k=150): 8.16 ms ± 108 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Sparse CWT Solver (k=250): 8.73 ms ± 87.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
Scipy  CWT Solver (k=250): 37 ms ± 342 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

We can make further gains by converting `A` and `b` into their sparse representations:

```python
# try if we make A sparse
Asp = sparse.csr_matrix(A) # 18% nonzero matrix
bsp = sparse.csr_matrix(b).T

def sketch_solve_sparse(k=10):
    S  = sketch(k=k,n=n)
    SA = (S @ Asp).todense()
    Sb = (S @ bsp).todense()
    x_ = np.linalg.lstsq(SA,Sb,rcond=None)[0]

%timeit sketch_solve(k=250)
%timeit sketch_solve_sparse(k=250)
```
results in the following performance. Note that when `A` is sparse we get another ~37% speedup. I didn't try to play around with which sparse matrix format to use (in this case, the `S` and `A` matrices are different types; perhaps that slows things down a bit) but could be ground for future optimization.
```
Sparse CWT Solver (k=250): 10.4 ms ± 1.4 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
Sparse Solver Sparse A (k=250): 6.51 ms ± 198 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

### Scipy/Numpy/Python version information:

```python
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.0 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
done in gh-9884, closing
