### ISSUE TITLE
Large coo matrix to csr conversion (despite large RAM)

### ISSUE THREAD

**Issue by sidak** [scipy/scipy#9819]
My issue is about converting a large coo matrix (stored as npz) to csr format. The number of entries (including duplicates) in the coo matrix is 16,940,976,557. I tried converting it, but everytime it goes out of memory, despite the fact that I have 500 GB of memory in my machine. 

```
import scipy.sparse as sp
coomat = sp.load_npz(input_file)
sp.save_npz(output_file, coomat.to_csr())
```

```
Done loading coomat in 1138.3824996530311 seconds
Traceback (most recent call last):
  File "coo_to_csr.py", line 16, in <module>
    sp.save_npz(output_file, coomat.tocsr())
  File "/home/sidak/.conda/envs/myenv/lib/python3.6/site-packages/scipy/sparse/coo.py", line 392, in tocsr
    indices = np.empty_like(col, dtype=idx_dtype)
MemoryError
```

```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.15.1 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```
The coo matrix gets loaded in memory, but converting to csr, it creates another copy and then goes out of memory. Is there some more efficient way of doing this? or if I can in some way split the matrix in parts and combine?

It would be great if you can help me out on this. Thanks a lot! 😄

**Comment by perimosocordiae** [comment]
What's the shape of your matrix? And what version of scipy are you using?

**Comment by perimosocordiae** [comment]
Ah, I missed the version info you provided, nevermind about that part.

**Comment by LinXiLuo** [comment]
When I use scipy.cluster.vq.vq(), the process MemoryError too.
But I only feed about 500M matrix, and I have 64GB in my machine.
So weird. 
The implement of vq is encapsulated, so I don't know why the computation of scipy occupied so many memory.

ubuntu 16.04

scipy 1.1.0

>     x = cluster.vq.whiten(x, check_finite=True)  # [n, d]
    code, _ = cluster.vq.vq(x, centroids, check_finite=True)

>   File "/home/user/miniconda3/envs/py3.6/lib/python3.6/site-packages/scipy/cluster/vq.py", line 211, in vq
    return _vq.vq(c_obs, c_code_book)
  File "_vq.pyx", line 235, in scipy.cluster._vq.vq
  File "_vq.pyx", line 101, in scipy.cluster._vq._vq
MemoryError

**Comment by fcharras** [comment]
Before `1.0.1`, I've had repeated issues for operations on sparse matrices, like `.sum` and `.tolil`, on matrices that weight no more than a few GB those operations suddenly takes up to tens of gigabytes of data which results in memory errors. One would expect at most twice the RAM usage of the original matrix (else the interest of sparsity is lost). Now i'm using `1.0.1`, the `tolil` issue still persists (and I haven't checked for the others). I think most of those issues are related to the C++ `sparsetools` utilities.

In those cases it happens to be more efficient (for ram usage, but surprisingly also speed wise) to re-implement those operations using only vectorized numpy operations (although the code can sometimes look convoluted).  

However there are very few reports of this, has it been adressed in more recent versions ?

**Comment by aksarkar** [comment]
I am running into the same problem in scipy 1.2.1, loading a 58,347 x 782,859 COO matrix with 619,309,024 non-zero entries.

The memory usage in GB (reported by sys.getsizeof) of the COO data is

    row     2.307106
    col     2.307106
    data    4.614212

I get a memory error when converting to CSR on a node with 32GB of memory available.

The relevant part of my conda environment:

  - python=3.6.8=h0371630_0
  - numpy=1.16.2=py36h7e9f1db_0
  - scipy=1.2.1=py36h7c811a0_0

**Comment by perimosocordiae** [comment]
@aksarkar the COO `tocsr()` method is pretty short: https://github.com/scipy/scipy/blob/75fa5f1e418487a8239800f25363a0fb2b0e415a/scipy/sparse/coo.py#L368

Could you try running these steps manually and report back with a more precise culprit?

**Comment by smola** [comment]
@aksarkar @LinXiLuo Do your COO matrices have a lot of duplicates? That may be one source for extra copies. Another may be conversion of indices between 32 and 64 bits, but it shouldn't be the case with the shape and nnz values that were mentioned above.

**Comment by aksarkar** [comment]
My example now works in scipy 1.5.0, and uses the expected amount of memory.

@smola My example has no duplicates, and is already in column-major order.
