### ISSUE TITLE
NumPy/SciPy faqs have broken chaco link

### ISSUE THREAD

**Issue by jakobjakobson18** [scipy/scipy#9825]
Dear delevopers,

the [SciPy/NumPy faqs](https://scipy.org/scipylib/faq.html#how-do-i-make-plots-using-numpy-scipy) have an outdated link within the section `how-do-i-make-plots-using-numpy-scipy`.
The link has either to be adapted to 'http://docs.enthought.com/chaco/index.html' or to a different toolkit as the current link results in a [404 Not Found](http://code.enthought.com/projects/chaco/) page.

Regards

**Comment by rgommers** [comment]
thanks for the report @jakobjakobson18. that FAQ needs some more fixes, content is a bit outdated.

for now I'll leave this issue open; for future reference, the issue tracker for scipy.org is at https://github.com/scipy/scipy.org/

**Comment by jakobjakobson18** [comment]
Sorry for filing the bug at the wrong place.I guess I'll spare me and you the time to file the report at [https://github.com/scipy/scipy.org/](https://github.com/scipy/scipy.org/) and leave it with that.

**Comment by rgommers** [comment]
yeah no worries, it happens more often - indeed, no need to open another issue, we'll use this one

**Comment by rgommers** [comment]
okay PR sent: https://github.com/scipy/scipy.org/pull/283
