### ISSUE TITLE
scipy.signal.firls seems to be inefficient versus MATLAB firls

### ISSUE THREAD

**Issue by DrewTNBD** [scipy/scipy#9835]
Hi everyone,
I've been porting some code over from MATLAB to Python, and I have run into an issue with scipy.signal.firls. It doesn't seem to be as fast/efficient as the MATLAB equivalent. I don't know if I'm using it wrong, but I wanted to report this and maybe get some guidance if I am indeed using it wrong.

Here is how I am executing the code in MATLAB. I've hard-coded the variables here for illustration purposes:
`firls(23220, [0, 0.000861326442721792, 0.000861326442721792, 1], [1 1 0 0]);`

This takes less than a couple of seconds to process.

Now in Python I do the following:
`scipy.signal.firls(23221, [0, 0.000861326442721792, 0.000861326442721792, 1], [1, 1, 0, 0])`

First thing you'll see is that argument 1 needs to have 1 added to it to make it an odd number. This I am guessing is related to the differences between Python and Matlab indexing functionality.

But when I run this, it takes over 5 minutes to process. I am guessing it's because of the large number of taps I am looking to process. 

Now if I sit and let it process it does give me the same output as MATLAB, roughly speaking. Which makes me think that for my purposes I'm not doing anything wrong. But can you spot anything here?

FWIW - I'm porting across a MATLAB library, which required me to also port across the MATLAB Resample class, and within that sits this firls line that is very slow in Python.

Any thoughts on how I can get past this?

**Comment by DrewTNBD** [comment]
The MATLAB documentation for their firls implementation states:

> b = firls(n,f,a) returns row vector b containing the n+1 coefficients of the order n FIR filter whose frequency-amplitude characteristics approximately match those given by vectors f and a. The output filter coefficients, or “taps,” in b obey the symmetry relation.

So is 'n' in their implementation equivalent to scipy.signal.firls(numtaps) parameter?

**Comment by larsoner** [comment]
Can you see if #9838 solves your problem? And yes MATLAB does `n+1` and requires `n` to be odd, we instead have `ntaps` odd, and you get a `ntaps` length filter back.

**Comment by DrewTNBD** [comment]
@larsoner 

UBER thanks for responding so quicky. That solved MUCH quicker, and on the face of it, it looks like I am getting the correct values. However the complex numbers returned are slightly different in some cases.

For example, the return array begins with in MATLAB:

> -3.35759847762220e-20 
Which resolves to 0.

But in your solution it begins with:

> 7.632048298997159e-20 
Which resolves to -0.

I don't know if that is a problem necessarily? 

Here are the first 10 numbers in case you wanted to check them on your end. I wont spam you with the entire matrix!!

MATLAB:
> -3.35759847762220e-20	-7.41946241368262e-08	-1.48401488327497e-07	-2.22620052386448e-07	-2.96849775949765e-07	-3.71090118479317e-07	-4.45340539266368e-07	-5.19600497435580e-07	-5.93869451949603e-07	-6.68146861611719e-07

Python:

> 7.63204830e-20 -7.41946241e-08 -1.48401488e-07 -2.22620052e-07
 -2.96849776e-07 -3.71090118e-07 -4.45340539e-07 -5.19600497e-07
 -5.93869452e-07 -6.68146862e-07

The numbers are slightly different because of precision differences between MATLAB and Python, but I'm not so worried about that.

I've patched my local Scipy.signal.fir_filter_design.py file. Should I leave it like that? Will your fix make it to the next official release?

Thanks again!

**Comment by larsoner** [comment]
I could not get `octave` and SciPy outputs to match. But I did check that the properties of the returned filters matched those of the design criteria. Can you check to see if they satisfy yours using `freqz`?

**Comment by larsoner** [comment]
(and yes assuming the PR is merged before 1.3.0 branching date, it will be in that release)

**Comment by DrewTNBD** [comment]
The formatting of the complex numbers looks a bit different, but if I whack them into Complex Number Calculator, then what I see in MATLAB's 'freqz' result is the same as what I'm seeing in Python. I *think*.

Again, here are some reference numbers. The first 10 results in each.

Matlab:
>1160.99999999999 + 0.00000000000000i
0.00931142233356466 + 0.0151114824035457i
0.0123139146781979 - 0.0244635468636103i
0.0190376493996473 - 0.00163942434520292i
0.00327291561885030 + 0.00441301585403953i
0.00111064687613271 - 0.00277725458056106i
0.00460084848837975 - 0.000798322943340352i
0.00141683250770980 + 0.00160231810952528i
0.000256602799033961 - 0.000845906063621180i
0.00196579592028704 - 0.000518124162136642i

Python:
>1.16100000e+03+0.00000000e+00j  9.31142233e-03+1.51114824e-02j
  1.23139147e-02-2.44635469e-02j  1.90376494e-02-1.63942435e-03j
  3.27291562e-03+4.41301585e-03j  1.11064688e-03-2.77725458e-03j
  4.60084849e-03-7.98322943e-04j  1.41683251e-03+1.60231811e-03j
  2.56602799e-04-8.45906064e-04j  1.96579592e-03-5.18124162e-04j

You can see the formatting is a bit different, but the resolved numbers are the same.
