### ISSUE TITLE
CI pypy3 failing TestZlibInputStream::test_seek 

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#9837]
Multiple PRs (gh-9810, gh-9829, gh-9830, gh-9831, gh-9834) are showing failure of a pypy3 test `TestZlibInputStream::test_seek` and all the PRs seem unrelated to the functionality  of the failing test.

### Error message:
```
[gw0] [ 10%] PASSED scipy/io/matlab/tests/test_streams.py::TestZlibInputStream::test_read 
scipy/io/matlab/tests/test_streams.py::TestZlibInputStream::test_seek 
[gw0] node down: Not properly terminated
[gw0] [ 10%] FAILED scipy/io/matlab/tests/test_streams.py::TestZlibInputStream::test_seek 
Replacing crashed worker gw0
```
### Scipy/Numpy/Python version information:
```
1.3.0.dev0+12175d2 1.16.0 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

**Comment by larsoner** [comment]
@mattip can you take a look? Here is an example

https://circleci.com/gh/scipy/scipy/11465

**Comment by mattip** [comment]
this was due to using a HEAD version of pypy, rather than pinning to a released version. Thanks for the ping
