### ISSUE TITLE
scipy.signal.upfirdn gives different length matrix versus MATLAB upfirdn

### ISSUE THREAD

**Issue by DrewTNBD** [scipy/scipy#9844]
This is something I am not sure is a bug, a mistake in my code, or just a difference in design or implementation.

Now everything before my call to upfirdn looks to be the same in both languages, floating point precision notwithstanding. So I get to this call:

MATLAB:
>y = upfirdn(x,h,p,q);

Python:
>y = upfirdn(h, x, p, q)

x, h, p, q, are the same across both files.
MATLAB upfirdn gives me a matrix of 1x647.
SciPy upfirdn gives me a matrix of 1x651.

Here are the first and last ten values from MATLAB:

> 0	-0.000199467579547424	-0.000728046369939899	-0.00110566784707238	-0.000996359004971441	-0.000228970643181423	0.000615489415076301	0.00126315546064305	0.00142874951087505	0.000908693634358364
>.....
>4.03845240072376e-06	1.87473690616758e-05	2.31142819067192e-05	1.71887339187862e-05	5.37933346930270e-06	-9.91074437326740e-06	-1.88844901213745e-05	-1.71623305506084e-05	-9.10662941865632e-06	-5.37239384457409e-07

Now here are the first ten values from Python:
>0.00000000e+00 -1.97601366e-04 -7.21234789e-04 -1.09532325e-03
  -9.87037098e-04 -2.26828400e-04  6.09910612e-04  1.25175809e-03
   1.41591478e-03  9.00565745e-04

Now I think the differences there are due to floating point precision. 
Here are the last 14 of values from Python:
>4.03214296e-06  1.87159549e-05  2.30728961e-05
   1.71559510e-05  5.36843263e-06 -9.88322175e-06 -1.88320470e-05
  -1.71146699e-05 -9.08133986e-06 -5.35747444e-07  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00

So you can see that the first value in the last 14 values in Python... it matches up roughly with the last 10 values in MATLAB. Except I have four extra zeros being added to the end of the list. So basically my SciPy upfirdn is adding padding at the end.

Now is this just me misunderstanding the differences in implementation or is there something more at play here?

Could someone explain to me the differences between the MATLAB implementation and the SciPy one??

Also - bonus question... should I be worried by the differences in the output values regardless of this padding issue?

Thank you!

**Comment by DrewTNBD** [comment]
So right now I'm just deleting those trailing zeros. It seems like in all the cases I've tried, I always get four of them. I don't know where they're coming from, but I'm using np.delete to remove them. Best I've got right now. I'd love to understand why there are differences between the Scipy and MATLAB methods.

**Comment by larsoner** [comment]
I would plot the two results, it's possible `matlab` and `scipy.signal` are making different assumptions about what the output mode should be, e.g. output should be the same length as the input if `p=q`, or it should be the full length `len(x) + len(h) - 1`, etc. Then you can check the MATLAB source to see how it computes the output size. In SciPy you can check to see how it's computed here

https://github.com/scipy/scipy/blob/v1.2.1/scipy/signal/_upfirdn_apply.pyx#L62-L74

**Comment by larsoner** [comment]
@DrewTNBD did you end up figuring out where the differences come from? Is the difference acceptable?

**Comment by grlee77** [comment]
According to the online Matlab documentation, the output size returned by their `upfirdn` is:
`ceil(((len(x) - 1) * p + len(h)) / q)` where `p` is the upsampling factor and `q` the downsampling factor.

I tried a range of up/down factors and signal/filter lengths and this often gives the same length as SciPy, but sometimes the Matlab length is slightly shorter than the SciPy one.

**Comment by grlee77** [comment]
The length used in SciPy's case is equivalent to:
`ceil((len(x) * p + len(h) - 1) / q)`
while Matlab's is:
`ceil(((len(x) - 1) * p + len(h)) / q)`

So the difference is where the `- 1` is located in the above formula.

**Comment by larsoner** [comment]
> The length used in SciPy's case is equivalent to:
> ceil((len(x) * p + len(h) - 1) / q)
> while Matlab's is:
> ceil(((len(x) - 1) * p + len(h)) / q)

It looks like we probably should have the ` - 1` in there. @sirtom67 do you agree?

**Comment by sirtom67** [comment]
Sorry for the late response. Thanks for tagging me Eric. I'll give it some thought. I think we need to be careful about doing it just because MATLAB does it. But it might be the right thing to do.

**Comment by sirtom67** [comment]
OK I rederived things and since Scipy's upfirdn is always starting at sample 0, I agree with the MATLAB expression for the output length.  HOWEVER I think it should be floor, not ceil.
Specifically, I think it should be 
  floor(((len(x) - 1) * p + len(h)) / q)

**Comment by sirtom67** [comment]
Actually, seeing something strange for length(x)=1:
In [28]: upfirdn([1,1],[1],1,1)
Out[28]: array([ 1.,  0.])

In [29]: upfirdn([1,1],[0,1],1,1)
Out[29]: array([ 0.,  1.,  1.])

**Comment by larsoner** [comment]
So it looks like there are two bugs to be fixed:

1. Behavior at short lengths (`upfirdn([1, 1], [1], 1, 1)` should be `[1, 1]` but we get `[0, 1, 1]`)
2. Length calculation is off and should use `floor(((len(x) - 1) * p + len(h)) / q)`

One question -- why prefer `floor` to `ceil` here? It would be nice to be consistent with MATLAB (`ceil`) but if their formula is less accurate then it makes sense to deviate (`floor`).

@sirtom67 do you want to look into the code? If not I (or someone else) can find time at some point.

**Comment by rgommers** [comment]
bumping the milestone on this, since it still needs investigation
