### ISSUE TITLE
The example code provided for scipy.signal.lsim is incorrect and does not work as intended

### ISSUE THREAD

**Issue by hbina** [scipy/scipy#9848]
My issue is about the scipy.signal.lsim documentation on the website. Specifically, the example code provided is incorrect.

### Reproducing code example:

The following is the exact copy of the code currently used in the example for scipy.signal.lsim

```
from scipy import signal
system = signal.lti([[0., 1.], [0., 0.]], [[0.], [1.]], [[1., 0.]], 0.)
t = np.linspace(0, 5)
u = np.ones_like(t)
tout, y, x = signal.lsim(system, u, t)
import matplotlib.pyplot as plt
plt.plot(t, y)
```

### Error message:

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    t = np.linspace(0, 5)
NameError: name 'np' is not defined
```

The graph will also not be displayed because the call to ```plt.show()``` is never made.
### Scipy/Numpy/Python version information:

```
1.2.1 1.16.1 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
Hi @hbina, thanks for trying to help improve scipy. There isn't anything wrong here, so I'll close this issue.

The line `import numpy as np` is assumed in every single code example in scipy, we don't want to repeat that 1000+ times.

And the plot is shown in the docs: http://scipy.github.io/devdocs/generated/scipy.signal.lsim.html#scipy.signal.lsim

So all good as is.
