### ISSUE TITLE
how scipy.misc.toimage work?

### ISSUE THREAD

**Issue by alirezaomrani** [scipy/scipy#9859]
there's a code that I've been working on and I saw a code that I don't Understand, I really appreciate someone explains it to me how it works.

the first code will normalize it in [0,1] but in the third code, it makes it in e.g [2,89] (it depends on input image), 1- my question is on code 3, how it makes it to the new domain? 2- if I want to take it back on [0,255] how to undo code 3 (e.g I normalized it and then take it back to the first image)?

### the code:

```
img = img.astype(np.float32)/255.0
sc = np.power(np.power(2.0, -3), 0.5)
img=scipy.misc.toimage(sc*np.squeeze(img), cmin=0.0, cmax=1.0)
img=np.asarray(img)
```

**Comment by ilayn** [comment]
Hi @alirezaomrani . First thing to notice that `misc.toimage` function is deprecated and will be removed. So you better follow the instructions mentioned at the top of the [documentation for `toimage`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.toimage.html#scipy.misc.toimage). Regarding your question have a look at the `bytescale` code to make sense of the cmin and cmax arguments.
