### ISSUE TITLE
`scipy.spatial.transform` documentation?

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [scipy/scipy#9863]
When I look at https://docs.scipy.org/doc/scipy/reference/spatial.html, I don't see anything on `scipy.spatial.transform`, although I understand that this functionality is in SciPy version 1.2.

**Comment by tylerjereddy** [comment]
It is the first thing I see at the top of the link you provide:

![image](https://user-images.githubusercontent.com/7903078/53210022-43a83b80-35f1-11e9-948c-ce0e47e78350.png)

**Comment by Phillip-M-Feldman** [comment]
I will have to get my eyes examined.  My apologies for the false alarm!
