### ISSUE TITLE
Scipy optimize brenth - RuntimeError: Unable to parse arguments

### ISSUE THREAD

**Issue by MorningGlory747** [scipy/scipy#9867]
I am currently using the scipy.optimize.brenth algorithm to solve x for a complex heat budget problem. The purpose of the code is to compute flower temperature based off a radiative budget. For individual inputs, the algorithm works without error, however, when trying to input a pandas dataframe instead, I get an error. The code actually originates from a model that was made to compute leaf temperature instead of flower temperature, but the developper who made it no longer works at the facility. It seems like what the developper initially had in mind was to compute the leaf temperature for one input at the time. I want to see if it can be done for multiple outputs such as in a pandas dataframe. 

Here are the key components for the code
```
import numpy as np
from scipy import optimize
import pandas as pd

#Key variables 
#Tair = air temperature dataframe
#Ray = solar radiation dataframe
#CC = cloud cover dataframe
#Eair = water vapor pressure dataframe
#Esat(x) = function that returns water vapor saturation dataframe
#gapfrac(LAI) = function that returns the fraction of the canopy that can block out the sun. 
#beta, sigma, psychro_et, emissivite ,cpair,rhoair,rH = constants
#TFlower = desired flower temperature

def TFlower(x, rH):
    beta = cpair * rhoair / rH
    IRcoef = 1.

    TempFlower = (1. - albedo) * Ray * gapfrac(LAI) + \
               emissivite * ((9.35 * 1e-6 *(Tair+273.15).pow(2) * sigma * (Tair+273.15).pow(4)) + \
                             (60. * CC * gapfrac(LAI))) - \
               emissivite * sigma * ((x + 273.15) ** 4.) + \
               2. * beta * (Tair - x) + (beta / psychro_et) * (Eair - Esat(x)) # based on Wittich,1995

    return TempFlower

TFlower = scipy.optimize.brenth(TFlower, Tair - 20, Tair + 25, maxiter=5000) - 0.8# Brent Algorithm # -0.8 added to compensate for resistance to water vapor

```
### Error message
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2\helpers\pydev\_pydev_bundle\pydev_umd.py", line 194, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/***/PycharmProjects/FlowerBudget/Computing_Flower_Temperature_TestOn2016-17-18.py", line 110, in <module>
    TFlower = scipy.optimize.brenth(Tlea, Tair - 20, Tair + 25, maxiter=5000) - 0.8# Brent Algorithm # -0.8 added to compensate for resistance to water vapor
  File "C:\Users\***\PycharmProjects\FlowerBudget\lib\site-packages\scipy\optimize\zeros.py", line 611, in brenth
    r = _zeros._brenth(f,a, b, xtol, rtol, maxiter, args, full_output, disp)
RuntimeError: Unable to parse arguments
```

### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.1.0 1.15.1 sys.version_info(major=3, minor=7, micro=0, releaselevel='final', serial=0)
```

Can the algorithm be used with pandas or even numpy arrays for that matter or should I just simply make a loop that goes through every row of the dataframe?

Thank you

**Comment by pvanmulbregt** [comment]
`_brenth` is a C function, which parses the `PyObject* args` looking for a callable 
Python function, and two doubles for the bracketing interval's endpoints.
https://github.com/scipy/scipy/blob/446cf4470b679b124870a69095ec58d313d8618c/scipy/optimize/zeros.c#L73-L74

As such, `_brenth` does not support passing in Iterables of any type.  

Making a loop to iterate over the rows of the pandas DataFrame would work.  It may also be possible to call pandas' `apply()` on the DataFrame to handle the iteration over the elements of each row.  Perhaps something similar to 
```
def _TFlower(x):
    return TFlower(x, rH)
def _solveOne(x):
     return scipy.optimize.brenth(_TFlower, x-20, x+25, maxiter=5000)
def _solveOneRow(row):
    return row.apply(_solveOne)
Tair.apply(_solveOneRow, axis=1) - 0.8
```

Other possibilities you may consider include: using the array variant of `newton`; or using Cython as in gh-8431.

**Comment by ev-br** [comment]
Does not seem to be a scipy bug, so closing. Thank @MorningGlory747, @pvanmulbregt anyway
