### ISSUE TITLE
dct, idct become very slow in dealing with large array with odd number shape value

### ISSUE THREAD

**Issue by MarcYin** [scipy/scipy#9868]
My issue is about ...

dct, and idct become very slow in dealing with array shape of odd numbers

### Reproducing code example:

```python
import numpy as np
from scipy.fftpack import dct
da = np.random.rand(10979,10980)
%time dct(da, axis=1)
%time dct(da, axis=0) # this is almost impossible to finish
```

**Comment by rgommers** [comment]
Hi @MarcYin, this is a known limitation of fftpack. try padding your array to a length of `2**N`.

**Comment by rgommers** [comment]
see eg gh-1476 for an older discussion with background

**Comment by grlee77** [comment]
I want to also recommend using [next_fast_len](https://docs.scipy.org/doc/scipy/reference/generated/scipy.fftpack.next_fast_len.html) to determine the next largest size that should give a reasonable transform speed.

For your signal
```python
scipy.fftpack.next_fast_len(10979)
```
gives 11250 which is substantially smaller than the next power of two (16384).

**Comment by MarcYin** [comment]
@grlee77 @rgommers Thanks for the answers and I will try to adapt my codes according to your suggestions.
