### ISSUE TITLE
scipy.ndimage.label: Minor documentation issue

### ISSUE THREAD

**Issue by Grumpulus** [scipy/scipy#9869]
The current documentation for scipy.ndimage.label(input, structure=None, output=None) states that the *structure* parameter must be "symmetric".

It should say "centrosymmetric". There is a difference. This can be shown with the following code fragment:

### Reproducing code example:

```
import numpy as np
from scipy import ndimage as ndi
y = np.around(np.random.uniform(size=(10,10))) # Any 2-D array will do here
z = np.array([[1,1,0],[1,1,0],[0,0,1]])
np.array_equal(z,z.T)
x = ndi.label(y, structure=z)
```
The call to np.array_equal returns True. This shows that 'z' has to be a symmetric matrix, because it is equal to its own transpose. That is the definition of a symmetric matrix. However, the subsequent call to ndi.label will throw a "Structure element is not symmetric" error. The reason for the error is that 'z' is not centrosymmetric.

Further, if we replace the definition of 'z' above with

z = np.array([[0,0,0],[1,1,1],[0,0,0]])

which is centrosymmetric but *not* symmetric, then ndi.label will run fine with the expected behaviour.

There are two Wikipedia articles titled "Symmetric matrix" and "Centrosymmetric matrix". These show the difference graphically, which is probably the easiest way to understand the problem.

This really is a minor nitpicking issue -- but I tripped over it, so others may as well.

Cheers
Grump

**Comment by rgommers** [comment]
thanks for the report @Grumpulus, fixed now
