### ISSUE TITLE
integrate.solve_ivp could optionally save y values at events

### ISSUE THREAD

**Issue by StanczakDominik** [scipy/scipy#9870]
At the moment, `scipy.integrate.solve_ivp` (which is a great addition!) solves a system of equations with the independent variable `t` for a vector `y` of variables with possible event detection. It collects values of `t` at those events. What I'm curious about, is... would it be possible to add an optional flag to also return the values of `y` at those events? I haven't been able to find a way to do that besides [implementing a hack in the event-defining function](https://stanczakdominik.github.io/posts/scipyintegratesolve_ivp-and-makeshift-poincare-sections-of-the-rossler-attractor/#Poincar%C3%A9-section-of-the-Rossler-attractor). Would you be open to a PR accomplishing that, if it's possible?

**Comment by MatthewFlamm** [comment]
There is no need for a hack.  You can use `dense_output` to calculate `y` at `t=t_event`.  Check out the docstring in the master branch as it has an example.

**Comment by StanczakDominik** [comment]
Oh holy wow, that option's amazing! I had missed that due to reading the [HTML version](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html) which is lagging a bit behind master. Thanks a ton for pointing that out! I suppose `y_event` is unnecessary, given that the currently returned `OdeSolution` is way more general.

**Comment by MatthewFlamm** [comment]
There was no way to know unless you were using a development version or browsing the master branch here.  I also found the docstring to be opaque on the usefulness of `dense_output` before, so hopefully the new example is enough to shed light on it.
