### ISSUE TITLE
scipy.signal.convolve is slower when vectorized

### ISSUE THREAD

**Issue by dniku** [scipy/scipy#9872]
This is a crosspost from https://stackoverflow.com/a/54790908/1214547.

The following code (which uses Python `for` loop)

```python
C = np.stack([
    scipy.signal.convolve(
        A[i, :, :],
        B,
        mode='same'
    )
    for i in range(N)
], axis=0)
```

is significantly faster than a vectorized version:

```python
C = scipy.signal.convolve(
    A,
    B[np.newaxis, ...],
    mode='same'
)
```

![plot-comparison](https://i.stack.imgur.com/efiXr.png)

### Reproducing code example:

The following is supposed to be run in a Jupyter notebook, as it uses the `%timeit` magic:

```python
import numpy as np
import scipy.signal

import pandas as pd
import seaborn as sns

H, W = 84, 84
h, w = 13, 13

def benchmark(N):
    A = np.random.normal(size=(N, H, W))
    B = np.random.normal(size=(h, w))

    t1 = %timeit -qo np.stack([scipy.signal.convolve(A[i, :, :], B, mode='same') for i in range(N)])
    t2 = %timeit -qo scipy.signal.convolve(A, B[np.newaxis, ...], mode='same')

    return t1.timings, t2.timings

Ns = (10**np.linspace(1, 4, 16)).round().astype(int)

results = [benchmark(N) for N in Ns]

ns = []
timings = []
run_type = []

for N, (t1_timings, t2_timings) in zip(Ns, results):
    cnt = len(t1_timings)
    ns.extend([N] * cnt)
    timings.extend(t1_timings)
    run_type.extend(['stack'] * cnt)

    cnt = len(t2_timings)
    ns.extend([N] * cnt)
    timings.extend(t2_timings)
    run_type.extend(['vectorized'] * cnt)

df = pd.DataFrame({'N': ns, 'timings': timings, 'type': run_type})
sns.lineplot(x='N', y='timings', hue='type', data=df)
```

### Scipy/Numpy/Python version information:

```python
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.1 1.16.1 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)
```

**Comment by e-q** [comment]
I'm not sure if it was #10517 and #10518 in particular, but on my machine, the code above results in vectorized calls winning now. 
![Unknown](https://user-images.githubusercontent.com/6894112/68237170-a0f3e980-ffd4-11e9-98d9-2d3ac84d7f4a.png)

**Comment by rgommers** [comment]
I get this on current master, doesn't seem fixed:

<img width="558" alt="image" src="https://user-images.githubusercontent.com/98330/68644414-c5b2fa00-04c9-11ea-9012-448348efad53.png">

**Comment by rgommers** [comment]
bumping the milestone, just a minor performance issue - shouldn't be blocking

**Comment by larsoner** [comment]
For me it does appear fixed:

![download](https://user-images.githubusercontent.com/2365790/81421390-6a339300-911f-11ea-962e-a1e74859794b.png)

I'll close since we have two reports showing vectorized is better, and one (@rgommers) showing it was even at least roughly even, but we can reopen if need be

**Comment by dniku** [comment]
Here is what I am getting now:

![image](https://user-images.githubusercontent.com/1315874/81429751-ed2c0c00-9166-11ea-953c-b45fd380d63b.png)

Versions:

```python
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.4.1 1.18.4 sys.version_info(major=3, minor=8, micro=2, releaselevel='final', serial=0)
```

So yeah, probably fixed.
