### ISSUE TITLE
cross compile using buildroot

### ISSUE THREAD

**Issue by arm-neosem** [scipy/scipy#9875]
I am trying to cross compile scipy version 1.2.1 for ARM7. The build root 
can compile the numpy version 1.15.1,
I compiled the openblas as needed by scipy.  With the buildroot the compile fails during the import of numpy in set.py 

I see there is a issue gh-8571 that seems to be unanswered and also for  Yocto.

Thanks

Ajay

Error during the compile

### Error message:
touch /home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/build/python-scipy-1.2.1/.stamp_patched
^[[7m>>> python-scipy 1.2.1 Configuring^[[27m
rm -f /home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/build/python-scipy-1.2.1/scipy/setup.py
cp -f ~/change2/setup.py /home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/build/python-scipy-1.2.1/scipy/setup.py
echo "[DEFAULT]" >> /home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/build/python-scipy-1.2.1/site.cfg
echo "library_dirs = /home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/lib" >> /home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/build/python-scipy-1.2.1/site.cfg
echo "include_dirs = /home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/host/usr/arm-buildroot-linux-gnueabi/sysroot/usr/include" >> /home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/build/python-scipy-1.2.1/site.cfg
echo "libraries =" blas,lapack >> /home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/build/python-scipy-1.2.1/site.cfg
touch /home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/build/python-scipy-1.2.1/.stamp_configured
^[[7m>>> python-scipy 1.2.1 Building^[[27m
(cd /home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/build/python-scipy-1.2.1//; PATH="/home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/host/bin:/home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/host/sbin:/home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/host/usr/bin:/home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/host/usr/sbin:/home/local/TNSU-AUS/ajaym/perl5/bin:/home/local/TNSU-AUS/ajaym/perl5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games" PYTHONPATH="/home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/target/usr/lib/python2.7/sysconfigdata/:/home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/target/usr/lib/python2.7/site-packages/" _python_sysroot=/home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/host/usr/arm-buildroot-linux-gnueabi/sysroot _python_prefix=/usr _python_exec_prefix=/usr  /home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/host/usr/bin/python setup.py build  --fcompiler=None --compiler=unix)
Traceback (most recent call last):
  File "setup.py", line 492, in <module>
    setup_package()
  File "setup.py", line 468, in setup_package
    from numpy.distutils.core import setup
  File "/home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/target/usr/lib/python2.7/site-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/target/usr/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/target/usr/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/target/usr/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/target/usr/lib/python2.7/site-packages/numpy/core/__init__.py", line 6, in <module>
    from . import multiarray
ImportError: /home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/target/usr/lib/python2.7/site-packages/numpy/core/multiarray.so: wrong ELF class: ELFCLASS32
make: *** [/home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/build/python-scipy-1.2.1/.stamp_built] Error 1

**Comment by rgommers** [comment]
> ImportError: /home/local/TNSU-AUS/ajaym/linux/linux-3.14.52/buildroot/buildroot-2016.05/output/target/usr/lib/python2.7/site-packages/numpy/core/multiarray.so: wrong ELF class: ELFCLASS32

You're picking up a wrong architecture binary somehow.

There are build recipes linked here that got people much further: https://github.com/scipy/scipy/issues/8571#issuecomment-423455891. Please try those. 

We can't help with cross-compiling, not officially supported nor debuggable for us, so I'm closing this. If you get to the same point or further as the other people commenting in gh-8571, I suggest you continue the discussion there.

**Comment by gwbres** [comment]
@rgommers  @arm-neosem,
just for information, scipy is now officially supported by Buildroot, current revision is 1.8.1

**Comment by rgommers** [comment]
Thanks @gwbres! I'm curious, do you have a link to how that's done?

**Comment by gwbres** [comment]
> Thanks @gwbres! I'm curious, do you have a link to how that's done?

@rgommers ,
see my reply [on this page](https://github.com/scipy/scipy/issues/14812)
