### ISSUE TITLE
SciPy: Error in Computing Standard Deviation.

### ISSUE THREAD

**Issue by nsrinivasan80** [scipy/scipy#9877]
My issue is about ...

### Reproducing code example:

```
Sample code to reproduce the problem
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

**Comment by nsrinivasan80** [comment]
New submission from N. Srinivasan <nisthesecond@verizon.net>:

"""
Construct  normal probability plot

"""
import math
import scipy.stats as ss
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import prettytable
from random import seed
seed(100)
################
mu = 0.0
sigma = 1.0
x = np.linspace(mu - 5*sigma, mu + 5*sigma, 10)
norm_pdf_x= ss.norm.pdf(x,mu,sigma)
plt.plot(x,norm_pdf_x)
print("The Std. Dev. of normally Dist. x =", np.std(norm_pdf_x))
print()
###########################################
Produces a wrong Result for sigma:
The Std. Dev. of normally Dist. x = 0.13142071847657633
Should be 1.0

**Comment by nsrinivasan80** [comment]
"""
Construct  normal probability plot

"""
import math
import scipy.stats as ss
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import prettytable
from random import seed
seed(100)
################
mu = 0.0
sigma = 1.0
x = np.linspace(mu - 5*sigma, mu + 5*sigma, 10)
norm_pdf_x= ss.norm.pdf(x,mu,sigma)
plt.plot(x,norm_pdf_x)
print("The Std. Dev. of normally Dist. x =", np.std(norm_pdf_x))
print()

**Comment by nsrinivasan80** [comment]
"""
Construct  normal probability plot

"""
import math
import scipy.stats as ss
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import prettytable
from random import seed
seed(100)
################
mu = 0.0
sigma = 1.0
x = np.linspace(mu - 5*sigma, mu + 5*sigma, 10)
norm_pdf_x= ss.norm.pdf(x,mu,sigma)
plt.plot(x,norm_pdf_x)
print("The Std. Dev. of normally Dist. x =", np.std(norm_pdf_x))
print()

**Comment by andyfaff** [comment]
The plot shows a normal distribution. But the norm_pdf_x values are not normally distributed. Try doing:

```
v = ss.norm.rvs(1000)
print (np.std(v))
```

**Comment by nsrinivasan80** [comment]
Dear Mr. Wilson,

Thanks for taking the time to reply.
This is the code I have:
import math
import scipy.stats as ss
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import prettytable
from random import seed
seed(100)
################
mu = 0.0
sigma = 1.0
n= 100
x = np.linspace(mu - 5*sigma, mu + 5*sigma, n)
norm_pdf_x= ss.norm.pdf(x,mu,sigma)
plt.plot(x,norm_pdf_x)
print("The Std. Dev. of normally Dist. x =", np.std(norm_pdf_x))
print()
v = ss.norm.rvs(1000)
print ("The Std. Dev. of v =", np.std(v))

This is what I get:
The Std. Dev. of normally Dist. x = 0.13463429327862472

The Std. Dev. of v = 0.0       #  Result as per your code.

Best Regards,
Nick
