### ISSUE TITLE
Error : attempted relative import in non-package

### ISSUE THREAD

**Issue by Ayude** [scipy/scipy#9878]
hii...i am new to python....i want to know that how can i import ._peak_finding_utils in python...i am getting error attempted relative import in non-package....pls help....thanks in adv

### Reproducing code example:

```
Sample code to reproduce the problem
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Traceback (most recent call last):
  File "gajanan1.py", line 14, in <module>
    from ._peak_finding_utils import (
ValueError: Attempted relative import in non-package

  ...
```

**Comment by larsoner** [comment]
In general it is a bad idea to import private functions and modules. There is no guaranteed API stability so their names, arguments, etc. can change at any time without notice. (The entire `_peak_finding_utils` namespace could disappear, for example.)

If you aren't dissuaded from doing so, you probably want `from scipy.signal import _peak_finding_utils` or something similar.
