### ISSUE TITLE
format at the wrong paranthesis in scipy.spatial.transform

### ISSUE THREAD

**Issue by hildensia** [scipy/scipy#9882]
https://github.com/scipy/scipy/blob/a74f77fc2e0f0ee4e19b3da175772475564b5fec/scipy/spatial/transform/rotation.py#L829

The `.format` needs to be one parenthesis more in.

**Comment by WarrenWeckesser** [comment]
Thanks for reporting the issue.  If you have the time and interest, a pull request with the fix would be welcome!
