### ISSUE TITLE
Unexpected behaviour for non-strictly monotonic values in scipy.interpolate.interp1d 

### ISSUE THREAD

**Issue by euronion** [scipy/scipy#9886]
I am having an issue with some unexpected behaviour with the `scipy.interpolate.interp1d` method for the following kinds:
* `kind= ['nearest','linear', 'previous' and 'next']` (i.e. kinds not involving spline interpolation according to the doc)

When providing non-strictly monotonic `x` values, unexpected results are returned rather than the method failing:

### Reproducing code example:
```
import numpy as np
from scipy.interpolate import interp1d

x = np.array([0, 1, 1])
y = np.array([0, 1, 0])

for kind in ['nearest', 'linear', 'previous', 'next']:
    f = interp1d(x,y,kind=kind)
    print("{k}: ".format(k=kind), f(x))
```

### Output
```
nearest:  [0. 1. 1.]
linear:  [0. 1. 1.]
previous:  [0. 0. 0.]
next:  [0. 1. 1.]
```

### Error message:
For `kind='cubic'` it fails in a similar matter as I would expect it to for the others:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-30-064ad468e798> in <module>
----> 1 f = interp1d(x,y,kind='cubic')
      2 f(x)

C:\anaconda\envs\atlite\lib\site-packages\scipy\interpolate\interpolate.py in __init__(***failed resolving arguments***)
    533 
    534             self._spline = make_interp_spline(xx, yy, k=order,
--> 535                                               check_finite=False)
    536             if rewrite_nan:
    537                 self._call = self.__class__._call_nan_spline

C:\anaconda\envs\atlite\lib\site-packages\scipy\interpolate\_bsplines.py in make_interp_spline(x, y, k, t, bc_type, axis, check_finite)
    797 
    798     if x.ndim != 1 or np.any(x[1:] <= x[:-1]):
--> 799         raise ValueError("Expect x to be a 1-D sorted array_like.")
    800     if k < 0:
    801         raise ValueError("Expect non-negative k.")

ValueError: Expect x to be a 1-D sorted array_like.
```

### Scipy/Numpy/Python version information:
```
[1]: import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.1 1.15.4 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)

```

**Comment by rgommers** [comment]
We have the right checks, but there's a subtle error in them somewhere. If I change your example to `x = np.array([0, 1, 2])` instead of `x = np.array([0, 1., 1.])` then things work fine.

**Comment by euronion** [comment]
The thing is with `x = np.array([0, 1, 2])` we are again back to using a (strictly) monotonic `x` with which I don't have any issues :) . It's just about this border case of a monotonic but not strictly monotonic `x` where there is no error for _some_ of the possible `kind` parameters.

**Comment by rgommers** [comment]
@euronion sorry I tried a bunch of things and my comment was incomplete. Also `x = np.array([0, 2, 1])` gives consistent results, it's just `[0, 1, 1]` with two identical elements that does't. The sorting of indices looks right; there's something special for duplicate x-values here.

**Comment by ev-br** [comment]
With duplicate `x` values, the procedure is not well-defined. In the OP, what would the rwsult be at x=1: zero or one? Erroring out could be a reasonable choice: this would produce an error when it did nit before, but what it does now is really an implemenration detail (likely, what np.searchsorted does)

**Comment by rgommers** [comment]
> With duplicate `x` values, the procedure is not well-defined

Hmm, I think `x` has a float dtype most of the time, so comparing for exact equality seems wrong. I'm fine with adding a test case and doing whatever `argsort` does now.

**Comment by ev-br** [comment]
Other interpolation kinds do

```
 if x.ndim != 1 or np.any(x[1:] <= x[:-1]):
         raise ValueError("Expect x to be a 1-D sorted array_like.")
```
regardless of x.dtype. In floating point, sure, equality checks are dubious. I think we can just use the same check here and forget about this whole issue :-).

**Comment by rgommers** [comment]
okay, fair enough - copying is easier than redesiging:)

**Comment by euronion** [comment]
That is just the check and error I would have loved to see. I also think that sufficient. :)

**Comment by ev-br** [comment]
Fix in gh-9887.
The check had to be made a trifle trickier because `assume_sorted=True` apparently allows monotonically decreasing values.

**Comment by coroa** [comment]
Note that the result is correct under the assumption that you are trying to interpolate right-continuous functions. For example,
```python
f = sp.interpolate.interp1d(np.array([0., 1., 1., 2.]), np.array([1., 2., 0., 1.]), kind='linear')
g = sp.interpolate.interp1d(np.array([0., 1., 1., 2.]), np.array([1., 2., 0., 1.]), kind='nearest')
x = plt.linspace(0, 2, 500)
plt.plot(x, f(x), label="f(x)")
plt.plot(x, g(x), label="g(x)")
plt.legend()
```
correctly gives
![mwe](https://user-images.githubusercontent.com/2552981/53665643-51526680-3c6c-11e9-8024-f12999658ba6.png)

For the discontinuity you have lim_{x\to 1} f(x) = 2 and f(1) = 0, which is perfectly fine; see for example a [right-continuous step function](https://en.wikipedia.org/wiki/Step_function).

**Comment by coroa** [comment]
Actually, there is a subtle inconsistency:
```python
f = sp.interpolate.interp1d(np.array([0., 1., 1., 2.]), np.array([1., 2., 0., 1.]), kind='linear')
g = sp.interpolate.interp1d(np.array([0, 1, 1, 2]), np.array([1., 2., 0., 1.]), kind='linear')
print(f"f(1) = {f(1)}, g(1) = {g(1)}")
```
prints
`f(1) = 0.0, g(1) = 2.0`

**Comment by euronion** [comment]
Hm, I didn't expect to wake so many sleeping dogs.
With the comments in https://github.com/scipy/scipy/pull/9887#issuecomment-468649810 , maybe an update to the doc might be more appropriate?

**Comment by ev-br** [comment]
@euronion possibly yes, a doc update could be an alternative. 
Touching `interp1d` is always fraught with backwards compat issues :-(.

**Comment by ev-br** [comment]
With gh-9887 rejected, this turns into a request for improving the docs. Would you be intetested in sending a PR @euronion ?

**Comment by ev-br** [comment]
OK, the conclusion seems to be that `interp1d` should keep doing whatever it was doing, even if it is not very consistent. I think we're open to accepting a pull request to clarify the documentation, otherwise there's not much to do here. Closing, thanks @euronion , all.
