### ISSUE TITLE
scipy.signal.find_peaks minor documentation issue

### ISSUE THREAD

**Issue by gtorelly** [scipy/scipy#9889]
My issue is about a minor error in the documentation of the scipy.signal.find_peaks function. In the description of the width parameter, where it says "required prominence" in the last line, it should actually say "required width".

### The issue as displayed in the source code:
```
    width : number or ndarray or sequence, optional
        Required width of peaks in samples. Either a number, ``None``, an array
        matching `x` or a 2-element sequence of the former. The first
        element is always interpreted as the  minimal and the second, if
        supplied, as the maximal required prominence.
```
You can find it in line 763: [https://github.com/scipy/scipy/blob/v1.2.1/scipy/signal/_peak_finding.py#L726-L1006](https://github.com/scipy/scipy/blob/v1.2.1/scipy/signal/_peak_finding.py#L726-L1006)

It's an easy fix, but I'm not sure how to submit a pull request correctly and would rather avoid messing up the code because of a documentation error.

**Comment by ilayn** [comment]
Closed in #9894
