### ISSUE TITLE
Minkowski p-norm Issues in cKDTree For Values Other Than 2 Or Inf

### ISSUE THREAD

**Issue by Wikilicious** [scipy/scipy#9890]
**c**KDTree gives wrong results when the Minkowski p-norm is something other than 2 or inf.
Normalizing with infinity should have the most neighbors but I'm getting more neighbors with p=15 than with p=inf. If you look at the distances you'll see the results can't be. The behavior of p-norm in the regular KDTree is working fine.

### Reproducing code example:

```
import numpy as np
import scipy.spatial

np.random.seed(123)
xy = np.ndarray((1000, 2), dtype=np.float64)
xy[:, 0] = np.random.randint(100, 1000, 1000)
xy[:, 1] = np.random.randint(100, 1000, 1000)
ct = scipy.spatial.cKDTree(xy)

r1 = ct.query_ball_point(xy, 10, p=2)
r2 = ct.query_ball_point(xy, 10, p=15)
r3 = ct.query_ball_point(xy, 10, p=np.inf)

print('cKDTree pnorm=2 max results:', max([len(_) for _ in r1]))
print('cKDTree pnorm=15 max results:', max([len(_) for _ in r2]))
print('cKDTree pnorm=inf max results:', max([len(_) for _ in r3]))

t = scipy.spatial.KDTree(xy)
r1 = t.query_ball_point(xy, 10, p=2)
r2 = t.query_ball_point(xy, 10, p=15)
r3 = t.query_ball_point(xy, 10, p=np.inf)

print('pnorm=2 max results:', max([len(_) for _ in r1]))
print('pnorm=15 max results:', max([len(_) for _ in r2]))
print('pnorm=inf max results:', max([len(_) for _ in r3]))
```
The results I get:
cKDTree pnorm=2 max results: 4
cKDTree pnorm=15 max results: 16
cKDTree pnorm=inf max results: 5
pnorm=2 max results: 4
pnorm=15 max results: 5
pnorm=inf max results: 5

### Scipy/Numpy/Python version information:
```
1.1.0 1.16.1 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)
```

**Comment by sturlamolden** [comment]
I concur. Minkowski distance with p-norm = 16 should never generate more hits than the Chebychev distance. This seems like a bug.

https://en.wikipedia.org/wiki/Minkowski_distance

**Comment by sturlamolden** [comment]
@rainwoodman @rgommers

**Comment by sturlamolden** [comment]
Since Euclidian and Chebychev distances produce identical results, I suspect ```query_ball_point``` are errorneously calling the special case for Euclidian distances.

**Comment by rainwoodman** [comment]
This is strange. I will take a look at this. The very top level file looks fine. So it has to be something more hideous.

**Comment by rainwoodman** [comment]
I found it. A PR will be filed.

**Comment by rainwoodman** [comment]
@Wikilicious I had a very similar test case where 9892 passes.

I am not exactly confident the heuristics invented there is the best one. Could you take a look if it fixes your problem?

**Comment by Wikilicious** [comment]
@rainwoodman I cloned your branch https://github.com/rainwoodman/scipy/tree/fix-9890/scipy and the test `Test_random_ball_compiled_largep_issue9890()` passes on `1.3.0.dev0+8f4b655` and fails on 1.1.0 so it looks like something was fixed.

However, my example above still fails.
Also, if I set `p=10000` in that test case... it fails.

**Comment by rainwoodman** [comment]
Thanks for the update.

The p=10000 case is a bit too difficult, since max of double is `10^308`. We shall probably raise an error for such large p. I think everything should have failed for such large p.

I don't know of a way of dealing with such large numbers; since we also need to add these numbers.  Any suggestions? Perhaps we can convert them to a common base?

**Comment by Wikilicious** [comment]
Was the `p=13.2` value (in the test case) chosen for a reason? Just curious.

I have two different views on large p.
1) Raise an error.
2) If the dtype precision of the xy points makes it indistinguishable for p=large VS p=np.inf then use p=np.inf

**Comment by rainwoodman** [comment]
I added a better heuristics for detecting round-off errors, and implemented option 1. 
@Wikilicious 
I updated the tests to include exactly your test, and it seems to work all the way to p=100.
If you change this to p=139, then it reraises an exception about the overflow.

**Comment by Wikilicious** [comment]
I tested the snippet in the latest branch `0abf5bb` and am getting correct results now.
And I get the ValueError for large p.  
I'm not a fan of the error message though.
`ValueError: floating point overlow error. The value of p is too high for this dataset.`
Other than the missing "f" in overflow... I think it may deter someone from using `p=np.inf`  
I would like the error message to include something along the lines of: "Hint: For such a large p, try the special case of p=np.inf instead"
