### ISSUE TITLE
The problem of integrating with scipy

### ISSUE THREAD

**Issue by Abraxas2071** [scipy/scipy#9895]
![1](https://user-images.githubusercontent.com/38712030/53693216-56342900-3dd8-11e9-98e8-9ca9699a9712.jpg)

I try to implement an empirical bayesian ML-II（Maximum likelihood estimation Type II） method for estimating prior distribution parameters from historical data

Where：
1】π(θ)  is an expression for the prior distribution
2】p(x|θ) is is an expression for the data distribution
3】m(x) is an expression for the marginal distribution

According to the steps, I need to first integrate to find the expression of the marginal distribution, and then find the extreme value of this expression to estimate the parameters of the prior distribution
Extreme values can be achieved using methods such as scipy optimize. So the question is how do we integrate this?

**Comment by ev-br** [comment]
This tracker is intended for bug reports and feature requests. 
Usage questions are best asked on Stackoverflow or scipy-user mailing lists.
