### ISSUE TITLE
lsoda fails to detect stiff problem when called from solve_ivp

### ISSUE THREAD

**Issue by m-oliver** [scipy/scipy#9901]
Both the `ode` and the `solve_ivp` solver interfaces wrap the venerable lsoda solver.  As far as I can see, `solve_ivp` even internally calls the `ode` wrapper.  Strangely enough, when tested on a stiff problem, lsoda when called through `ode` handles stiffness just fine.  However, when called through `solve_ivp`, it behaves as if using the non-stiff solver.  The only parameter difference I can spot is the reduced default `atol` and `rtol` parameter, however, even setting them to the `ode` defaults will not change the behavior of `solve_ivp`.  (Off-topic comment: I find the default tolerances for `solve_ivp` unnecessarily poor, especially given that any other blackbox solver I know, including the two older Scipy APIs, have stricter defaults.  I would strongly recommend using common defaults across Scipy, otherwise an already confusing situation is made more confusing and less robust.)

### Reproducing code example:

```python
#!/usr/bin/python3

from pylab import *
from scipy.integrate import solve_ivp
from scipy.integrate import ode
import time
    
mu = 1000
y0 = r_[0.5, 0.5]
T = 500
tt = linspace(T/200,T,200)

def van_der_pol(t, y):
    return r_[y[1], mu*(1.0-y[0]**2)*y[1]-y[0]]

c1 = time.process_time()
sol1 = solve_ivp(van_der_pol, [0,T], y0, t_eval=tt,
                 method = 'LSODA', rtol=1e-6, atol=1e-12)

c2 = time.process_time()
r2 = ode(van_der_pol).set_integrator('lsoda')
r2.set_initial_value(y0)
sol2 = array([r2.integrate(T) for T in tt])

c3 = time.process_time() 
print ("Time for LSODA (solve_ivp): " + str(c2-c1))
print ("Time for lsoda (ode):       " + str(c3-c2))

figure()
plot(sol1.t, sol1.y[0,:], label='LSODA (solve_ivp)')
plot(tt, sol2[:,0], label='lsoda (ode)')
legend()
show()
```
This yields the following output (graphical output is qualitatively OK with both cases being very close):

```
Time for LSODA (solve_ivp): 35.811249636000014
Time for lsoda (ode):       0.024488598000004913
```
So there is more than a factor 1000 performance difference, these numbers indicates that in the ill-performing case, `lsoda` has not switched to using a BDF method.

I tried to find any substantial differences in the code paths of the two wrappers, without success.  

### Scipy/Numpy/Python version information:

1.1.0 1.15.1 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)

**Comment by MatthewFlamm** [comment]
Your `ode` example might have much smaller max time steps.  What happens if you use `max_step=T/200` in `solve_ivp`?  You can also check `nlu` and `njev` to assess whether it is switching to an implicit method.

**Comment by MatthewFlamm** [comment]
I tested my suggestion and it makes no difference.  As a further wrinkle,, `odeint` performs nearly identically to `ode`.  There are **significantly more** jacobian evaluations in `solve_ivp` compared to `odeint`.  This would point me to some other factor causing this, but I'm not sure what.
 
```
from pylab import * 
...: from scipy.integrate import solve_ivp 
...: from scipy.integrate import ode, odeint 
...: import time 
...: mu = 1000 
...: y0 = r_[0.5, 0.5] 
...: T = 500 
...: tt = linspace(T/200,T,200) 
...: def van_der_pol(t, y): 
...:         return r_[y[1], mu*(1.0-y[0]**2)*y[1]-y[0]] 
...:          
...: c1 = time.process_time() 
...: sol1 = solve_ivp(van_der_pol, [0,T], y0, t_eval=tt, 
...:                  method = 'LSODA', rtol=1e-6, atol=1e-12) 
...: c2 = time.process_time() 
...: r2 = ode(van_der_pol).set_integrator('lsoda') 
...: r2.set_initial_value(y0) 
...: sol2 = array([r2.integrate(T) for T in tt]) 
...: c3 = time.process_time()  
...: sol3 = odeint(van_der_pol, y0, tt, tfirst=True, full_output=True) 
...: c4 = time.process_time() 
...: print ("Time for LSODA (solve_ivp): " + str(c2-c1)) 
...: print ("Time for lsoda (ode):       " + str(c3-c2)) 
...: print ("Time for lsoda (odeint):       " + str(c4-c3)) 
...:  
...: print ("solve_ivp jacobian evaluations: " + str(sol1.njev)) 
...: print ("odeint jacobian evaluations: " + str(sol3[1]['nje'][-1]))
```

```
Time for LSODA (solve_ivp): 101.24764199000003
Time for lsoda (ode):       0.07786113399993155
Time for lsoda (odeint):       0.08001487700005327

solve_ivp jacobian evaluations: 348567
odeint jacobian evaluations:    63
```

**Comment by drhagen** [comment]
I noticed degraded performance on the LSODA as well. It [used to perform](https://github.com/drhagen/scipy_ode/blob/master/performance_tests/comparison.png) about as well `odeint` and `ode` with `lsoda` (because they are wrappers of the same thing). I have tracked the problem down to [this commit](https://github.com/drhagen/scipy_ode/commit/82019445feaf3ffa76cc90a478c982e322e19849). In particular, lsoda really does not [these lines ](https://github.com/scipy/scipy/blob/master/scipy/integrate/_ivp/lsoda.py#L128-L130)where the Jacobian passed in as `def jac(): None` rather than just `None`. This seems to tell it that the Jacobian cannot be computed (and therefore can only use the nonstiff solver) rather than it should compute the Jacobian itself with finite differences. @nmayorov Is it ok if this lines are reverted.

**Comment by MatthewFlamm** [comment]
Kudos for running this down!  It works great.
