### ISSUE TITLE
scipy.stats.truncnorm second moment may be wrong

### ISSUE THREAD

**Issue by wittawatj** [scipy/scipy#9902]
I have an issue with the implementation of the second moment (or variance) of `scipy.stats.truncnorm` when only one tail is truncated. I assume that this is allowed. I do not find any problems when two tails are truncated.

### Reproducing code example:

```
import scipy.stats as stats
import numpy as np

mean = 2.0
std = 2.0
# only truncating the left tail
lower = 0
# not truncating the right tail
upper = np.inf

a = (lower - mean)/std
b = (upper - mean)/std

# distribution object
dist = stats.truncnorm(a, b, loc=mean, scale=std)

# Computation of v is not correct. This will produce a warning
m, v = dist.stats(moments='mv')
```

### Error message:

```
/some/path/anaconda3/envs/.../lib/python3.7/site-packages/scipy/stats/_continuous_distns.py:6372: RuntimeWarning: invalid value encountered in multiply
  mu2 = 1 + (a*pA - b*pB) / d - mu*mu
```

### Scipy/Numpy/Python version information:
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
# 1.2.1 1.16.2 sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)
```

Looking at the implementation in the master branch (https://github.com/scipy/scipy/blob/be58c3021ca63d8a9758dc67fa73b784cc0317de/scipy/stats/_continuous_distns.py#L6408), my understanding is that it does not implement the case where only one tail is truncated. The formula ` mu2 = 1 + (a*pA - b*pB) / d - mu*mu` is only valid for two-tailed truncation. See https://en.wikipedia.org/wiki/Truncated_normal_distribution#Moments More specifically `b` in the above code will be `np.inf` thus making `mu2 == np.nan`. If `upper` is set to a finite number, then there is no problem. Thanks.

**Comment by wittawatj** [comment]
One workaround for now is to use, say, `1e9` instead of `np.inf`.l

**Comment by heisenbuug** [comment]
Hey can you just get me the output where both are being truncated as I am even getting an error there.

**Comment by wittawatj** [comment]
Same code as above except `upper=5.0`. Then `dist.stats(moments='mv')` outputs `(array(2.29037489), array(1.66274002))`. No warning message. If `upper = np.inf`, then the second value in the output tuple is `array(nan)`.

**Comment by heisenbuug** [comment]
So what we need is if we make `upper=np.nan` then we should get a warning message

**Comment by heisenbuug** [comment]
ohk, after the changes I have made following will occur
```
import scipy.stats as stats
import numpy as np

mean = 2.0
std = 2.0
# only truncating the left tail
lower = 0
# not truncating the right tail
upper = np.inf

a = (lower - mean)/std
b = (upper - mean)/std

# distribution object
dist = stats.truncnorm(a, b, loc=mean, scale=std)

# Computation of v is not correct. This will produce a warning
m, v = dist.stats(moments='mv')
```
When we will write this code we will get this as output

![error](https://user-images.githubusercontent.com/32970979/53810125-4ce3c180-3f7c-11e9-8397-c38e9cf5e679.PNG)

Will this be fine?

**Comment by wittawatj** [comment]
I am confused. Are you trying to say that one-sided truncation is not allowed? Then, perhaps the use of `scipy.stats.truncnorm` will be limited. I think a proper way to implement it is to handle the one-sided truncation (two case: left or right truncation) as discussed in the Wiki page https://en.wikipedia.org/wiki/Truncated_normal_distribution#Moments But I do not know what scipy team wants. If the consensus is really to disallow one-sided truncation, I would already raise an exception at the line `dist = stats.truncnorm(a, b, loc=mean, scale=std)`. Better fail early.

**Comment by chrisb83** [comment]
yes, this is a bug, it should be able to handle infinite endpoints. one would need to slightly adjust the code to handle infinite endpoints.

The probelm is the multiplication in `a*pA - b*pB`.

**Comment by rgommers** [comment]
> I am confused. Are you trying to say that one-sided truncation is not allowed?

No, I don't see any indication in the code that one-sided truncation is not allowed. I think that the implementation of `truncnorm_gen._stats` is simply incomplete.

Looking through old issues and pull requests, I don't see a mention of one-sided truncation being disallowed. gh-2494 (from 2013) was the last interesting PR to touch `truncnorm`.

@josef-pkt any memory of this, and would you agree that one-sided truncation should be allowed?

@heisenbuug your comments were missing the point a bit. I appreciate you trying to help, but it's probably best to try and tackle an older issue that you're sure you understand.

**Comment by josef-pkt** [comment]
AFAIR this never came up because we usually just pick some large finite bounds for normal.
So far one sided truncation is neither allowed nor explicitly disallowed it's just not supported. I think the current assumption is that both bounds are finite.

There are two one-sided variations on the normal distribution, halfnorm and foldnorm. 
halfnorm could also be extended to the more general case.

I would allow one-sided truncation if the code doesn't get too complicated, especially if the truncation limits would be or would get vectorized.
In general I think allowing an infinite bound would be a useful extension. But that opens up also the case when both bounds are set to inf by the user, i.e. normal as special case of truncnorm where truncnorm is not just a finite truncated approximation.

**Comment by rgommers** [comment]
fixed by gh-10104
