### ISSUE TITLE
Wrong error message about vector length in scipy.signal.filtfilt 

### ISSUE THREAD

**Issue by piecot** [scipy/scipy#9907]
I think that the message of the ValueError raised by `scipy.signal.filtfilt` if the input array has the same length of the padding is wrong.

### Reproducing code example:

```
import numpy as np
from scipy import signal

# create coefficients for the filter
order = 4
critical_frequecy = 0.02
b, a = signal.butter(order, critical_frequecy)

# computing the padlen
padlen = 100

# Creating a vector with the same length as padlen
data = np.random.random(padlen)

# The next instruction will raise the error:
# ValueError: The length of the input vector x must be at least padlen, which is 15.
signal.filtfilt(b, a, data, padlen=padlen)
```

### Error message:

This is the error produced by the previous code:
```
Traceback (most recent call last):
  File "/tmp/example_filltfilt.py", line 17, in <module>
    signal.filtfilt(b, a, data, padlen=padlen)
  File "/tmp/lib/python3.6/site-packages/scipy/signal/signaltools.py", line 3126, in filtfilt
    ntaps=max(len(a), len(b)))
  File "/tmp/lib/python3.6/site-packages/scipy/signal/signaltools.py", line 3176, in _validate_pad
    "padlen, which is %d." % edge)
ValueError: The length of the input vector x must be at least padlen, which is 100.
```
The error states that the input vector **must be at least** (>=) `padlen`, while it must be greater (>) than `padlen`. Indeed, the [comment preceeding](https://github.com/scipy/scipy/blob/c3fa90dcfcaef71658744c73578e9e7d915c81e9/scipy/signal/signaltools.py#L3173) the correspondent check in the `_validate_pad`  used in `filtfilt` implementation says:

>     # x's 'axis' dimension must be bigger than edge.
and the condition of the `if` on the following line confirms this:
```if x.shape[axis] <= edge:```

Thus the error text message should be changed to: 
```ValueError: The length of the input vector x must be greater than padlen, which is 100.```

The same behaviour is shared by all the filters using `_validate_pad`.

### Scipy/Numpy/Python version information:

```
1.2.1 1.16.2 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

**Comment by larsoner** [comment]
@piecot this sounds right, can you open a PR to fix it?

**Comment by piecot** [comment]
Yes, no problem
