### ISSUE TITLE
scipy.stats.lognorm

### ISSUE THREAD

**Issue by banzr** [scipy/scipy#9908]
My issue is about ...

### Reproducing code example:

Scipy has trouble with computing probability of lognormal for x values [0,1].

```
scipy.stats.lognorm(1,1).pdf(.5)
```

### Error message:

```
 returns 0
```

True value is 0.190298

### Scipy/Numpy/Python version information:

```
1.1.0 1.15.4 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
```

**Comment by chrisb83** [comment]
Hi,

there are different ways to parametrize the distribution. 

`loc=1` shifts the support to [1, inf), so `pdf(0.5)` is zero.

I think you want to use `stats.lognorm(1, scale=np.exp(1)).pdf(.5)` which gives 0.19029780481010564. 

see the brief description on `loc` and `scale` here: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.lognorm.html

**Comment by chrisb83** [comment]
I close this issue, feel free to reopen it if I missed sth in my explanation

**Comment by banzr** [comment]
Thank you! It helped.
