### ISSUE TITLE
binary_dilation/erosion/closing crashes when iterations is float

### ISSUE THREAD

**Issue by my-tien** [scipy/scipy#9909]
In the scipy documentation it says:

> iterations : {int, float}, optional
The dilation is repeated iterations times (one, by default). If iterations is less than 1, the dilation is repeated until the result does not change anymore.

I used that in the code below:
```
import numpy as np
from scipy.ndimage import morphology as morph
morph.binary_dilation(np.array([0, 0, 1, 0, 0]), iterations=0.5)
```

### Error message:

```
free(): invalid size
Aborted (core dumped)
```
Same error message appears, when replacing `binary_dilation` above with `binary_erosion`. When using `binary_closing`, the error becomes 

```
double free or corruption (out)
Aborted (core dumped)
``` 

### Scipy/Numpy/Python version information:
I’m using Anaconda.
```
In [1]: import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)                          
1.1.0 1.14.2 sys.version_info(major=3, minor=6, micro=7, releaselevel='final', serial=0)
```

**Comment by rgommers** [comment]
Yes that's a bug, thanks for reporting. `iterations` should be only `int`, and we should implement a check to avoid the segfault.

**Comment by rgommers** [comment]
This is a duplicate of gh-9905 opened 2 days ago, probably not a coincidence? Closing, continued in gh-9905.
