### ISSUE TITLE
scipy.stats.stats._cdf_distance doesn't handle p=np.inf

### ISSUE THREAD

**Issue by Jwink3101** [scipy/scipy#9916]
My issue is about `scipy.stats.stats._cdf_distance` and `p = np.inf`

Mathematically, `p = np.inf` is the same as the "Kolmogorov-Smirnov statistic" (`ks_2samp`) and should handle it according

### Reproducing code example:

```
import numpy as np
import scipy.stats

np.random.seed(1)
A = np.random.uniform(size=100000)
B = np.random.uniform(size=len(A)-1) # Just to demonstrate they need not be the same size

a = scipy.stats.stats._cdf_distance(np.inf,A,B)
b = scipy.stats.stats.ks_2samp(A,B)[0]
print(a,b)
```

returns `1.0 0.004296157861578664` which is incorrect

### Scipy/Numpy/Python version information:
```
>>> import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
1.2.1 1.16.2 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

### Proposed fix:

Very easy to fix and add a test. Just as there is a special case considered for `p=1` and `p=2` (for performance, not correctness), the same should be considered for `~isfinite(p)`

**Comment by mradazoury** [comment]
I am trying to fix this issue, it is my first time fixing an issue so excuse any "easy" question...
I added the condition :
    if p == np.inf:
        return ks_2samp(u_values, v_values)
but i dont really know how to add a test for it since there are no tests for the ( p=1 , p=2) cases
any help would be appreciated

**Comment by mdhaber** [comment]
@mradazoury Are you still interested in contributing a fix? I can help.

**Comment by mdhaber** [comment]
@Jwink3101 I just took a closer look, and `_cdf_distance` is a private function, so I don't think this will be added unless we have a use for calling `_cdf_distance` with `p=np.inf` within SciPy.  I agree that the request is simple to implement in principle, but each change we make needs to be thought through carefully, unit tested, and reviewed by other maintainers, and there are many other bug reports and feature requests for public function that we need to get to first! If you would like to submit a PR with unit tests, and if you can find places where this should be used within SciPy, I'd be happy to take a look. Alternatively, if you'd like to submit a feature request for a public `cdf_distance` or `ks_distance` function, let us know. In the meantime, I'm going to go ahead and close this.

@mradazoury Thanks for your interest! Let me know if you're looking for a good first issue to tackle.
