### ISSUE TITLE
BUG: `coo_matrix` does not validate the `shape` argument.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#9919]
In a [stackoverflow question,](https://stackoverflow.com/questions/55060950/sparse-matrix-hstack-getting-error-regarding-subscriptability) a user created a `coo_matrix` as follows:

    a = coo_matrix([0, 11, 22, 33], ([0, 1, 2, 3], [0, 0, 0, 0]))

Apparently they neglected to put the values and indices into a tuple, and instead of creating an array with shape `(4, 1)`, they got an array with shape `(1, 4)`:

```
In [4]: a = coo_matrix([0, 11, 22, 33], ([0, 1, 2, 3], [0, 0, 0, 0]))

In [5]: a.shape
Out[5]: (1, 4)

In [6]: a.A
Out[6]: array([[ 0, 11, 22, 33]])
```

The problem is that the call shown above is equivalent to

    a = coo_matrix(arg1=[0, 11, 22, 33], shape=([0, 1, 2, 3], [0, 0, 0, 0]))

and clearly that `shape` value is not valid.  The call should generate a `ValueError` instead of silently ignoring the `shape` argument.  Note that the shape is completely ignored--the following does not generate an error:

    b = coo_matrix([[0, 1], [2, 3]], shape='foo')

-----

SciPy version is the master branch:

```
In [9]: import scipy

In [10]: scipy.__version__
Out[10]: '1.3.0.dev0+5539300'
```

**Comment by perimosocordiae** [comment]
Thanks for reporting this, Warren. Thankfully it's an easy fix, see gh-9920.
