### ISSUE TITLE
stats.multivariate_normal.pdf() slow, suboptimal

### ISSUE THREAD

**Issue by pezcore** [scipy/scipy#9921]
### `stats.multivariate_normal.pdf()` may be sub-optimally implemented

Why is `stats.multivariate_normal.pdf()` so slow ? Docs, suggest that this function only evaluates the density function of a multivariate normal distribution. Can this evaluation not be replaced by a simpler, faster, straightforward direct evaluation of the PDF expression like something along the lines of:

```python
from numpy.linalg import det, inv

def mvnormpdf_candidate(x, μ, Σ):
    k = x.shape[-1]
    den = np.sqrt((2 * np.pi) ** k * det(Σ))
    x = x - μ
    return np.squeeze(np.exp(-x[..., None, :] @ inv(Σ) @ x[..., None] / 2)) / den
```
? On my machine, `mvnormpdf_candidate()` is over 2 times faster for huge `x` arrays and almost 8 times faster for single valued `x` and it still correctly handles arbitrary input dimensions the same way `multivariate_normal.pdf()` does and returns correct numbers. 

There may be some minor checks and overhead missing from `mvnormpdf_candidate()` that would be needed before its a full fledged replacement for `multivariate_normal.pdf()`, but I don't imagine it requires overhead that slows it down by a factor of 2 or more. Is there some reason why a direct calculation method can't be leveraged to increase the performance of `multivariate_normal.pdf()` ?

### Scipy/Numpy/Python version information:

```
1.1.0 1.15.4 sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
```

**Comment by sturlamolden** [comment]
“Direct” computation using inv() and det() has stability issues when the covariance is singular or severely ill-conditioned. That is why we use pseudo-inverse by SVD, which is a bit slower. Numerical correctness is more important than speed.

**Comment by sturlamolden** [comment]
Though looking at the way the code, it seems it is implemented in a very inefficient manner. For example it does a pseudo-inverse everytime a loglikelihood is computed. Instead of using the pseudo-inverse to obtain the loglikelihood, it calls some non-lapack Fortran code to do a Cholesky, effectively inverting the covariance matrix all over again. It should suffice to do a pseudo-inverse once, upon constructing the probability distribution. Thereafter we could just reuse the pseudo-inverse and determinant for obtaining likelihoods and random deviates, in the manner you have done above.

**Comment by sturlamolden** [comment]
So yeah, there are things we can do here, but avoid ```inv()``` and ```det()```.

**Comment by siddhantwahal** [comment]
> It should suffice to do a pseudo-inverse once, upon constructing the probability distribution. Thereafter we could just reuse the pseudo-inverse and determinant for obtaining likelihoods and random deviates, in the manner you have done above.

FYI, https://github.com/scipy/scipy/pull/12184/files is an old attempt to address this.

**Comment by mdhaber** [comment]
@siddhantwahal do you agree that this has been addressed by the new `Covariance` class?

**Comment by tirthasheshpatel** [comment]
Yes, `Covariance` should address this. Closing. Feel free to reopen if you have more comments @siddhantwahal @pezcore @mdhaber!

**Comment by sturlamolden** [comment]
It does not seem like Covariance actually stores the inverse or pseudoinverse, which it should for efficiency.

**Comment by mdhaber** [comment]
Right, because most of them don't use the inverse at all.

**Comment by mdhaber** [comment]
Feel free to write a `Covariance` class that does what you'd like. There is already one that accepts the inverse of the matrix and works with that, but not a pseudoinverse matrix.
