### ISSUE TITLE
dia_matrix offsets datatype matches numpy.int32 but type_num does not.

### ISSUE THREAD

**Issue by weinbe58** [scipy/scipy#9925]
I'm trying to parse the type_num of arrays in some C++ code with the numpy C-API using arrays coming from a scipy.sparse dia_matrix. The problem is that for some reason the `offsets` array has a weird type_num on Windows 10 64-bit with python 3.6. I have not tested this on Linux or OS-X with python 3.6 but this does not happen with python 2.7 on OS-X or Linux.

You can see this with a simple example

### Reproducing code example:

```
from scipy.sparse import identity
import numpy as np

import sys, scipy, numpy; 

print(scipy.__version__, numpy.__version__, sys.version_info)

I = identity(10).todia()

a = np.array([1],dtype=np.int32)
print(I.offsets.dtype==a.dtype,I.offsets.dtype,a.dtype,I.offsets.dtype.num,a.dtype.num)
```

### outputs:

```
1.2.1 1.16.2 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
True int32 int32 5 7
```
This is quite bad for my C++ code as the enumerated type `NPY_INT32` is 7.

**Comment by weinbe58** [comment]
NOTE: I just checked this for over sparse matrices I am working with:

```
from scipy.sparse import identity
import numpy as np

import sys, scipy, numpy; 

print(scipy.__version__, numpy.__version__, sys.version_info)

a = np.array([1],dtype=np.int32)
for fmt in ["dia","csr","csc"]:

	I = identity(10).asformat(fmt)

	try:
		print(fmt,I.offsets.dtype==a.dtype,I.offsets.dtype,a.dtype,I.offsets.dtype.num,a.dtype.num)
	except AttributeError:
		print(fmt,I.indices.dtype==a.dtype,I.indices.dtype,a.dtype,I.indices.dtype.num,a.dtype.num)

```

output:

```
1.2.1 1.16.2 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
dia True int32 int32 5 7
csr True int32 int32 5 7
csc True int32 int32 7 7
```

**Comment by weinbe58** [comment]
I guess I need to just handle this in my C++ code the conversions between types to deal with the Numpy C-API.

**Comment by ewmoore** [comment]
@weinbe58, the issue you are seeing is that on Windows a C int and a C long are both 32 bit.  The default numpy integer type is a C long (typenum = 7).    

This shows up within python too if one looks at how arrays are printed on windows.
```
In [37]: arr_int = np.array([10], 'i')

In [38]: arr_long = np.array([10], 'l')

In [39]: (arr_int, arr_int.dtype.name, arr_int.dtype.char, arr_int.dtype.num)
Out[39]: (array([10], dtype=int32), 'int32', 'i', 5)

In [40]: (arr_long, arr_long.dtype.name, arr_long.dtype.char, arr_long.dtype.num)
Out[40]: (array([10]), 'int32', 'l', 7)

In [41]: arr_int.dtype == arr_long.dtype
Out[41]: True
```
Unfortunately, you just have to deal with this if you want to ensure that copies are not made in all circumstances.

I don't have access to a linux system to check right now, but I think this also is true between C long (numpy 'l') and C long long (numpy 'q').

**Comment by weinbe58** [comment]
@ewmoore Thanks, yes I figured this out when I closed it, I am using the numpy-API function EquivTypenum function to take care of this which works for cross platform applications.
