### ISSUE TITLE
REV: Seemingly orphaned branch on upstream codebase

### ISSUE THREAD

**Issue by ilayn** [scipy/scipy#9926]
@Kai-Striega Is it possible that you have created a branch on the upstream Scipy codebase instead of your fork with named `revert-9263-linprog_rs`? I see that you have a single commit with "ENH: optimize: added "revised simplex" for scipy.optimize.linprog" message from January. 

I did this mistake a couple of times before too but I'd like to ask you before we take action if it was indeed a mistake or I missed the context for it.

**Comment by Kai-Striega** [comment]
This looks like a mistake. Linprog-rs should stay as it is.

**Comment by mdhaber** [comment]
Must have been me? Revised simplex is me. We don't want to revert 9263.
