### ISSUE TITLE
incompatibility of numpy in ubuntu 18 and scipy

### ISSUE THREAD

**Issue by lindseypeng** [scipy/scipy#9929]
the issue started when i tried to import cluster module from sklearn
error occursed in scipy/linalg/__init__.py file which provoked error while trying to import numpy.dual
with the following code "ModuleNotFoundError: No module named 'numpy.dual'"
the fix was to downgrade numpy back to 1.14, it seems like numpy 1.15 also had similar issues
(another bug was found in sklearn files from similar problems of incompatibilities that i will reporting on their website)

### Reproducing code example:

```
import sklearn.cluster as cluster
```

### Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
```

**Comment by pvanmulbregt** [comment]
Please edit and add the version information for the failing configuration to your initial report.  I.e. The output of
```
import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)
```

**Comment by rgommers** [comment]
`numpy.dual` still exists, so this is an install or upgrade of numpy gone wrong somehow. seems you got it to work @lindseypeng, but if you want to upgrade it may help to first repeatedly do `pip uninstall numpy` and `conda uninstall numpy` before reinstalling. and note that if you use Anaconda, please use `conda` to install numpy.
