### ISSUE TITLE
interp1d bounds_error is redundant

### ISSUE THREAD

**Issue by vkk800** [scipy/scipy#9930]
The `bounds_error` argument of `interp1d` seems to be completely redundant. The extrapolation behaviour of the function could be controlled with just the `fill_value` argument using the following logic:

* If `fill_value` is a tuple, ndarray, or `'extrapolate'`, the behaviour is as it is now except no error would be raised.

* If `fill_value = None` (or possibly `False`?), error is raised when trying to extrapolate (this would be new behaviour)

Even though the current behaviour of the function is documented well, it is counter-intuitive that two separate arguments need to be set when the user wants to use a constant fill value. 

Perhaps another way to refactor the current behaviour would be to replace both of the arguments with one `extrapolate` argument which can be a `bool` or an `ndarray`-like. If The argument is set to `True`, the values are extrapolated; if `False`, an error is raised; if `ndarray`, then those values are used as constant fill values.

**Comment by ev-br** [comment]
The interface of interp1d is *very* constrained by backwards compatibility. Essentially any tweak is bound to break something downstream.

New code should indeed use `extrapolate=` argument, but for `interp1d` specifically, I'd rather keep the status quo.

**Comment by ev-br** [comment]
No follow-up for over a month, closing.
