### ISSUE TITLE
documentation for `scipy.interpolate.RectBivariateSpline` is unclear

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [scipy/scipy#9944]
The documentation for `scipy.interpolate.RectBivariateSpline` is unclear re. the following:

(1) What happens when the coordinates passed to `__call__` exceed the limits of the input code?  Is extrapolation being done?

(2) The documentation says that the default `bbox` is `[min(x,tx),max(x,tx), min(y,ty),max(y,ty)]`, but `tx` and `ty` are not defined.

**Comment by jtboing** [comment]
Hello. I'd like to help with this issue.

**Comment by AtsushiSakai** [comment]
Second point was already solved in #12463
