### ISSUE TITLE
SciPy Development Documentation

### ISSUE THREAD

**Issue by mdhaber** [scipy/scipy#9951]
[Contributing to SciPy](http://scipy.github.io/devdocs/hacking.html) is mostly comprehensive, but coming to SciPy without a development background, I needed a little more help getting started. Now that I have more experience, I wish that links to key information were all listed in one place rather than within the narrative. 

I envision a table something like:

* Development environment - how to set up and maintain a development environment, including installing compilers and SciPy dependencies, creating a personal fork of the SciPy repository on GitHub, using git to manage a local repository with development branches, performing an in-place build of SciPy, and creating a virtual environment that adds this development version of SciPy to the Python path
* Editing SciPy - how to edit SciPy Python code, with tips on finding which module contains SciPy functionality to be edited, adding new modules to SciPy, and complying with PEP8 style standards
* Unit tests - how to write and run unit tests for SciPy with the pytest framework
* Documentation - how to write reStructuredText documentation that complies with docstring standards, build documentation locally, and view documentation built during continuous integration checks
* Pull requests - how to push a local branch to a personal fork of SciPy on GitHub, create a "Pull Request" to have commits "pulled" into the master branch of SciPy, and interpret the results of continuous integration checks
* Benchmarks - how to benchmark code with AirSpeed Velocity
* Cython - how to add fast, compiled code to SciPy

Each headline would have a link to a separate document that is simple enough for a beginner to understand yet detailed enough for core developers to use for reference.  These landing pages would be new, but they would of course draw from and/or link to existing documentation. I'd also like to make videos on the topics I haven't already covered (see #8353).

Initially I'd include this table in a separate document to be linked from [Contributing to SciPy](http://scipy.github.io/devdocs/hacking.html). Depending on how it turns out, we could consider integrating it into [Contributing to SciPy](http://scipy.github.io/devdocs/hacking.html) itself.

The purpose of this issue is to discuss whether this could be useful and, if so, collect feedback on what this documentation would include.

**Comment by charris** [comment]
@jakevdp Has said good things about the [astropy](http://docs.astropy.org/en/stable/development/workflow/development_workflow.html) development docs. It would probably be worthwhile do see how they set things up.

**Comment by mdhaber** [comment]
@charris Yes, at a glance I can already see some things there that I would have found helpful. Thanks!

**Comment by mdhaber** [comment]
A few thoughts on why such a table would be useful:

- I can't find a link to [ASV benchmarking documentation](https://github.com/scipy/scipy/tree/master/benchmarks) from any of the development documentation
- I can't find any official documentation about building documentation with Sphinx or generating a publicly accessible link to documentation built by CircleCI (i.e. https://circle-artifacts.com/gh/scipy/scipy/WXYZ/artifacts/0/html-scipyorg/index.html where "WXYZ" is the number in the link to ci/circleci: build_docs). This observation is supported by #8966.
- I can't find any official documentation about adding Cython code. This observation is supported by #8575.
- Information about setting up a development environment and using it should be presented in the order it is likely to be needed. [Recommended Development Setup](http://scipy.github.io/devdocs/hacking.html#recommended-development-setup) begins with a warning to make sure compilers and "Python development headers" are installed, but doesn't give any other information there. At the end of the section, this appears: 
```Note: if you run into a build issue, more detailed build documentation can be found in :doc:`building/index` and at https://github.com/scipy/scipy/tree/master/doc/source/building```, but that's really needed at the beginning of the section, the first link needs to be fixed, and the second link should go to a document rather than a directory listing. The provided code snippets would benefit from individual explanations to educate the beginner. Very useful information about installing in a virtual environment and in-place builds should be brought in from the FAQ.  All the information is there to be found, but I want to make it easier for a beginner to piece together.
- The [git workflow document](https://docs.scipy.org/doc/numpy/dev/gitwash/) mentions only NumPy. The changes required to work with SciPy are trivial, but a beginner doesn't know that.
- The SciPy structure documentation hints at some really important information, but it may be difficult for beginners to interpret. I would like to provide more explicit instructions rather than referring the beginner to "See the existing Scipy submodules for guidance." I suggest that we make the definition of "module" consistent with that in the Python documentation.

I would like to try to fix these issues if others agree that they may confuse the intended audience.

**Comment by matthew-brett** [comment]
Fixing those issues would be a big improvement - I would be very glad to see those fixes.

**Comment by mdhaber** [comment]
I started creating a table of links:
https://github.com/scipy/scipy/wiki/SciPy-Development-Table-of-Contents

I started some additional documentation on `runtests.py` that I thought new users would find more informative than the lists of commands in [Recommended Development Setup](http://scipy.github.io/devdocs/hacking.html#recommended-development-setup), more comprehensive than the [NumPy/SciPy Testing Guidelines](https://github.com/numpy/numpy/blob/master/doc/TESTS.rst.txt), and more convenient than reading `runtests.py` source.
https://github.com/scipy/scipy/wiki/Running-SciPy-Tests-Locally
Some questions:
- [ ] When I try `python runtests.py --coverage`, I get an error:
```
ERROR: usage: runtests.py [options] [file_or_dir] [file_or_dir] [...]
runtests.py: error: unrecognized arguments: --cov-report=html:/Users/matthaberland/Desktop/scipydev/scipy/build/coverage --cov=/Users/matthaberland/Desktop/scipydev/scipy/build/testenv/lib/python3.6/site-packages/scipy
  inifile: /Users/matthaberland/Desktop/scipydev/scipy/pytest.ini
  rootdir: /Users/matthaberland/Desktop/scipydev/scipy
```
_UPDATE: Fixed by installing `pytest-cov`_
- [ ] Referring to the `--debug`/`-g` option of `runtests.py`: what is a debug build? Is this an essential part of the command suggested in the FAQ for running the full test suite `python runtests.py -g -m full`?
- [ ] Where does `runtests.py` build SciPy? It seems to perform an in-place build for me.

**Comment by rgommers** [comment]
> https://github.com/scipy/scipy/wiki/Adding-Cython-to-SciPy

This is an aside but: I've actually become less and less convinced over time about writing code in Cython. There's a reason it's not popular, and people are much more enthusiastic about Numba. And that `scipy.spatial.cKDTree` got moved away from Cython to C++. Perhaps we should tweak our recommendation. Cython is great for bindings, not so much for the more complex algorithmic code.

**Comment by rgommers** [comment]
> Does anyone know offhand whether installing Apple Developer Tools can be skipped by installing git via conda? Can we build SciPy using gcc from conda instead of Homebrew? I intend to test these out, but thought I'd check first.

IIRC you can install Git via Homebrew. Woudn't do it via conda.

> Can we build SciPy using gcc from conda instead of Homebrew? I intend to test these out, but thought I'd check first.

That's not recommended yet. It's completely broken with NumPy 1.16.0-1.16.2 for example. And with 1.16.3 it still requires setting extra environment variables to deal with the conda compilers being set up for cross-compiling. See https://github.com/numpy/numpy/issues/13280

**Comment by rgommers** [comment]
> Referring to the --debug/-g option of runtests.py: what is a debug build? Is this an essential part of the command suggested in the FAQ for running the full test suite python runtests.py -g -m full?

No not essential, rarely needed. Debug build means adding debug symbols for compiled code so you can effectively use `gdb`.

> Where does runtests.py build SciPy? It seems to perform an in-place build for me.

No it should create a local virtualenv to build in, IIRC under `build` (but not 100% sure). It then sets PYTHONPATH to pick up that installed build. So it's different from in-place.

**Comment by charris** [comment]
> Cython is great for bindings, not so much for the more complex algorithmic code.

It's hard to beat C for C code :)

**Comment by mdhaber** [comment]
> This is an aside but: I've actually become less and less convinced over time about writing code in Cython. There's a reason it's not popular, and people are much more enthusiastic about Numba. And that `scipy.spatial.cKDTree` got moved away from Cython to C++. Perhaps we should tweak our recommendation. Cython is great for bindings, not so much for the more complex algorithmic code.

Numba is still not approved for use in ScIPy, right? And it's easier to convert from Python to Cython than Python to C/C++. So I hope there is still some place for Cython, as I just wrote `LU` and `BGLU` this winter.

- When Numba is OK for SciPy, I'll write a similar guide about that, and perhaps that will replace this one.
- I'd be happy to mention that writing in C/C++ is preferred over Cython, but that's not what it currently says in the SciPy 1.0 paper. In my revisions, I haven't changed the language preference order I first read: Python, Cython, C, C++, Fortran.
- I'd love to include something about bindings here if someone can recommend a very simple case I can learn from.

**Comment by mdhaber** [comment]
> No it should create a local virtualenv to build in, IIRC under `build` (but not 100% sure). It then sets PYTHONPATH to pick up that installed build. So it's different from in-place.

Does it remove it from the PYTHONPATH when the tests are done?

To check my understanding, would you mind thinking through my scenario?

I perform SciPy development in a virtual environment managed by `conda`. SciPy was built in-place and the root is automatically added to PYTHONPATH when the virtual environment is activated.

Let's say I change my Cython code for `BGLU` and call `runtest.py`. The code will be re-compiled and the tests will run with the recently updated `BGLU`.

But if (right after that) I simply import `BGLU` in a Python console and start using it, I will not be using the recently updated `BGLU`? I would need to perform a separate in-place build to see the changes?

**Comment by mdhaber** [comment]
Re: installing `git` and compilers with `conda`
I'll leave the instructions as they are, then: `git` is installed with Apple Developer Tools, and compilers are installed with Homebrew.

**Comment by tylerjereddy** [comment]
>  I would need to perform a separate in-place build to see the changes?

Not sure if I followed your scenario perfectly, but in practice I do indeed repeat a build outside / after `runtests.py` if I want to test with i.e., a quick script I wrote or something like that. My experience has been that you don't need to rebuild from scratch though. I can do `python setup.py install --user` after runtests.py & it will basically just install the build to another location suitable for import / testing it seems.

**Comment by rgommers** [comment]
this is why I personally don't use `runtests.py` - it takes a few more steps to do a local in-place build, and the test/benchmark interface isn't as nicely integrated as in `runtests.py`, but if you know what you're doing it's nicer imho

**Comment by ev-br** [comment]
As a data point, I prefer `$ python runtests.py --shell` followed by `make html-scipyorg`. This way, the dev virtualenv does not have an installed scipy et all anywhere on the path, thus less chance of picking a wrong version.
IIRC I had to clean up the site-packages directory manually a couple of times when doing what Tyler suggested.

**Comment by mdhaber** [comment]
Preparing for making a video on benchmarking. 
It doesn't look like, but worth asking - do we have a central repository to which we should contribute our local benchmark results? 
Is there any automated, periodic benchmarking except for https://pv.github.io/scipy-bench/?

**Comment by tylerjereddy** [comment]
> do we have a central repository to which we should contribute our local benchmark results?

I don't think so & I think the main automated performance tracker is indeed the one you link.

I work on some projects that have mechanisms for contributing / uploading benchmark results and integrating them. Never seems that heavily used compared to an automated machine though.

**Comment by rgommers** [comment]
>> do we have a central repository to which we should contribute our local benchmark results?

> I don't think so & I think the main automated performance tracker is indeed the one you link.

indeed

**Comment by mdhaber** [comment]
Good to know. Thanks!
