### ISSUE TITLE
Rotate array from a desired point 

### ISSUE THREAD

**Issue by Nirajkandpal** [scipy/scipy#9959]
I have an issue regarding rotation with scipy.ndimage.rotate . The problem is that scipy.ndimage just rotates the array from the center . I want to rotate it from a desired point or location . In the code below  i call my boolean array as mask which is an ellipsoid in 3D . I want to rotate my ellipsoid  from a fixed point other than center but scipy.ndimage.rotate seems just rotate the ellipsoid from the center.

` import numpy as np
  import scipy
  from scipy import ndimage
  import skimage
  from skimage import draw

  mask = skimage.draw.ellipsoid(10,12,16)

  rotated_mask = scipy.ndimage.rotate(mask, 60 , axes =(0,2))`

**Comment by ev-br** [comment]
I'm pretty sure it can be done with ndimage.shift and rotate. Anyway, usage questions are better asked on Stackoverflow or the scipy-user mailing list.

**Comment by Nirajkandpal** [comment]
Thank you for the reply  yes it was possible to do with scipy.ndimage.rotate. I got some solutions from Stackoverflow. Also I had to use numpy padding with my data. So the issue is resolved now.
