### ISSUE TITLE
optimize.newton : overwrites x0 argument when it is a numpy array

### ISSUE THREAD

**Issue by pfalloon** [scipy/scipy#9964]
My issue is about the `x0` argument of the `optimize.newton` function. It seems that when this argument is a numpy array, it is overwritten during evaluation.

I believe the origin of the bug (if this behavior is considered a bug) is inside the `_array_newton` helper function (c. line 356) where an internal variable `p` is defined in terms of `x0` using the `np.asarray` function. This does not result in a copy and so `p` references the same array as `x0`. 

I think the fix would be to modify the call to `np.asarray` by appending the `.copy()` method.

### Reproducing code example:

```
import numpy as np
import scipy.optimize as so

x0 = np.array([0.1, 3.0])
print(x0) # x0 is [0.1 3. ]
so.newton(np.sin, x0, np.cos, tol=1e-6)
print(x0) # x0 is now [0.         3.14159265]
```

### Scipy/Numpy/Python version information:

```
1.2.1 1.16.2 sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
```

**Comment by Kai-Striega** [comment]
@pfalloon Yes, this should be considered a bug. We're having a similar issue in #9793. I don't think appending ``.copy()`` is the best solution. ``np.asarray(...)`` copies an array iff the array is not a numpy array. Having a ``.copy()`` will *always* cause another copy, even if the array is already copied.

One possible solution would be to first test if the passed array is already a numpy array, if it is, explicitly make a copy before calling ``np.asarray()``.
