### ISSUE TITLE
special.comb(exact=False) returns inf unnecessarily

### ISSUE THREAD

**Issue by jameysharp** [scipy/scipy#9967]
`scipy.special.comb(..., exact=False)` can return `inf` for large inputs, but, since `comb(n, k)` is by definition equal to `comb(n, n - k)`, evaluating `comb(n, min(k, n - k))` keeps the inputs small enough to be computed within floating point precision on twice as many inputs as SciPy supports today.

I suggest that this function's results would be surprising less often if it transparently chose the smaller value of `k` without requiring the caller to do it. I expect that the cost of the extra floating-point compare should be swamped by the cost of the rest of the computation and so I expect this to be an improvement in basically all applications.

### Scipy/Numpy/Python version information:

```
1.1.0 1.15.1 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

**Comment by ev-br** [comment]
Pull requests welcome

**Comment by pv** [comment]
Examples please, it should already do that.

**Comment by jameysharp** [comment]
Oops, @pv, you're right, it does already do that. I got confused by intermediate versions of my tests for #9968.
