### ISSUE TITLE
wishlist: approximation of log(comb(n, k, exact=False))

### ISSUE THREAD

**Issue by jameysharp** [scipy/scipy#9968]
When computing expressions involving large binomial coefficients, sometimes the log of the expression may fit in floating point precision where the original expression does not. In that case, it would be nice to have a `logcomb` function which returns the natural log of the value which `comb` would return on the same arguments, but works over a larger domain.

There's an approximation for this function, based on Stirling's approximation, which works well when `n` is significantly larger than `k`. (As in #9967, setting `k` to be `min(k, n-k)` helps by putting most combinations of `n` and `k` into the `n>>k` realm).

https://en.wikipedia.org/wiki/Binomial_coefficient#n_much_larger_than_k

### Reproducing code example:

Here's the implementation I tested on my data set; I'm betting you have a better idea of what values of `n` and `k` are interesting to validate this on than I do, so I'll leave that to you.

```
def logcomb(n, k):
    # Get SciPy's opinion on what this should evaluate to, before we mangle any
    # of the inputs.
    reference = comb(n, k)
    
    # comb(n, k) == comb(n, n - k), and we're using an approximation that's
    # only valid if k << n, so pick the smaller equivalent value of k.
    k = numpy.minimum(k, n - k)
    
    assert numpy.all(n > k)
    assert numpy.all(k >= 0)
    
    # When k is 0, the correct result is log(1) == 0, but division by k and log
    # of k both evaluate to NaN in that case. Compute a wrong answer which
    # doesn't involve any undefined operations first, and then fix the result
    # afterward.
    empty = (k == 0)
    k[empty] = 1
    result = k * numpy.log(n / k - 0.5) + k - 0.5 * numpy.log(k) - 0.5 * numpy.log(2 * numpy.pi)
    result[empty] = 0

    assert numpy.all(numpy.isfinite(result))

    # check against scipy, when that returns a finite value
    valid = numpy.isfinite(reference)
    num_valid = numpy.count_nonzero(valid)
    if num_valid:
        percentiles = [0, 90, 100]
        stats = numpy.percentile(numpy.abs(result[valid] - numpy.log(reference[valid])), percentiles, overwrite_input=True)
        print("in {} samples, {}".format(
            num_valid,
            ", ".join("{}% <= {}".format(p, v) for p, v in zip(percentiles, stats)),
        ), file=sys.stderr)

    return result
```

On my data set, I got these results:

```
in 4989467 samples, 0% <= 0.0, 90% <= 0.09219069666911306, 100% <= 7.820686244896592
in 4146740 samples, 0% <= 0.0, 90% <= 0.0412938147289843, 100% <= 0.08103820205420575
in 4100333 samples, 0% <= 1.066886278522361e-05, 90% <= 0.04129416809684372, 100% <= 0.08103820313665189
in 4984833 samples, 0% <= 1.066886278522361e-05, 90% <= 0.08103820313665189, 100% <= 0.08103820313665189
```

Note that these are in natural-log scale units, so that extreme value of 7.8 is a multiplicative factor of about 2,500 difference between the two. I suspect that was a case where `n` was very small, so it might make sense to return `log(comb(...))` if that is finite, and fall back to this approximation otherwise?

### Scipy/Numpy/Python version information:

```
1.1.0 1.15.1 sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
```

**Comment by WarrenWeckesser** [comment]
Here's a fairly simple implementation of `logcomb(n, k)` that uses [`scipy.special.gammaln`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.gammaln.html):

    def logcomb(n, k):
        return gammaln(n + 1) - gammaln(k + 1) - gammaln(n - k + 1)

**Comment by jameysharp** [comment]
Nice, that works great, thanks @WarrenWeckesser! I still think this would be worth including in `scipy.special`. I guess it could be called `combln` by analogy with `gammaln`, `betaln`, etc, but there's also `loggamma`, `logsf` in `scipy.stats`, etc, so I don't know...

**Comment by pv** [comment]
I'd maybe recommend definition via betaln instead --- there's a
theoretical chance of loss of precision.

**Comment by person142** [comment]
I'd agree with @pv about using `betaln`. I don't think we should add an extra function to the API, but I'd happily accept a PR adding an entry to "functions not in `scipy.special`" part of the tutorial

https://docs.scipy.org/doc/scipy/reference/tutorial/special.html#functions-not-in-scipy-special

explaining how to implement it.

**Comment by stippingerm** [comment]
@pv @person142 the naive solution with `scipy.special.betaln` would be
```
def combln(n, k):
    return -betaln(n-k+1, k+1) - np.log(n+1)
```
But I think loss of precision may occur here too. If the two terms are close enough we get:
```
np.exp(combln(1000, 999))
# 1000.0000000009057
np.exp(combln(1000, 1000))
# 0.9999999999999112
```
Other grouping of those terms, e.g., `-betaln(n - k + 1, k) - np.log(k)` did not help either. Note, in the latter case one has to handle the valid `k==0` case separately, on an conditional branch.

**Comment by SZGraph** [comment]
```
lnfact = lambda n:n*np.log(n)-n+np.log(2*np.pi*n)/2
lncomb = lambda n,k:lnfact(n)-lnfact(k)-lnfact(n-k)
lncomb(10000,5000)
```
> 6926.640844060821
