### ISSUE TITLE
scipy.stats.gengamma: generate skewed and kurtosis normal distribution given skewness and kurtosis

### ISSUE THREAD

**Issue by yl-hz** [scipy/scipy#9972]
Hi! I am trying to generate a series of skewed and kurt normal data using scipy.stats.gengamma given a certain level of skewness and kurtosis. According to scipy documents, the pdf for gengamma in python is:
![image](https://user-images.githubusercontent.com/48391886/54758376-7169ab80-4bc2-11e9-9da8-91acc2f7eb36.png)
However, according to Wikipedia, the common pdf we use for gamma distribution and the corresponding skewness and kurtosis are as follows:
![image](https://user-images.githubusercontent.com/48391886/54758426-86463f00-4bc2-11e9-8130-b740b22e8a0e.png)

But I have no idea how does the two parameters 'a', 'c' in gengamma relate to alpha and beta (or k and theta) mathematically. I wonder if anyone can help me with this so that I can match 'a' 'c' to skewness and kurtosis. Thanks a lot!

**Comment by chrisb83** [comment]
`gengamma` ist the generalized gamma distribution, your Wikipedia article relates to the Gamma distribution i think

**Comment by yl-hz** [comment]
> `gengamma` ist the generalized gamma distribution, your Wikipedia article relates to the Gamma distribution i think

Oh right! Thanks for pointing out!! Then that makes sense to me!
