### ISSUE TITLE
stats.kruskal : add a warning for an input with 2 or more columns

### ISSUE THREAD

**Issue by iryna1** [scipy/scipy#9981]
if a dataframe  has two columns, results are weird. For instance let the dataframe x be (first column = indices):
         counts  group
3803673      31      0
3800421      24      0
3800446      21      0
3804785      11      0
3801989      31      0
3801364      15      0
3804710      12      0
3800049      20      0
3801342      11      0
3804642       4      0

```stats.kruskal(x, x)```
gives this result: 
KruskalResult(statistic=205.08158702862053, pvalue=1.6254869278866505e-46)

I expect a warning message that the test is only suited for a series or a dataframe with one column.

**Comment by mdhaber** [comment]
I can confirm that the behavior is strange. When a 2D array goes in, it's not doing any of the things I might expect:
```
import numpy as np
from scipy.stats import kruskal
x = np.random.rand(10, 2)

print(kruskal(x, x))  # this is not the same as any of the following
print(kruskal(x.ravel(), x.ravel()))
print(kruskal(*x))
print(kruskal(*x, *x))
print(kruskal(*x.T))
print(kruskal(*x.T, *x.T))
```
```
KruskalResult(statistic=178.30023630504832, pvalue=1.1390878583388253e-40)
KruskalResult(statistic=1.4237566848125315e-14, pvalue=0.9999999047953962)
KruskalResult(statistic=6.857142857142861, pvalue=0.6519900104245908)
KruskalResult(statistic=14.075187969924825, pvalue=0.7792907302420939)
KruskalResult(statistic=0.02285714285714846, pvalue=0.8798291600118151)
KruskalResult(statistic=0.04691729323309699, pvalue=0.9973348991169523)
```
