### ISSUE TITLE
lsq_linear hangs/infinite loop with 'trf' method

### ISSUE THREAD

**Issue by taranu** [scipy/scipy#9982]
I have found several cases where scipy.optimize.lsq_linear with non-negative bounds (i.e. (0, numpy.Inf)) hangs, seemingly stuck in an infinite loop in some C code (LAPACK?) that can't be terminated via ctrl+c. It ran for at least two days the first time I noticed it. The non-default 'bvls' method and scipy.optimize.nnls() both work on the same data, one example of which I have attached:
[x.txt](https://github.com/scipy/scipy/files/3010094/x.txt)
[y.txt](https://github.com/scipy/scipy/files/3010095/y.txt)

### Reproducing code example:

```
import numpy as np; import scipy.optimize as spopt
x = np.loadtxt('x.txt')
y = np.loadtxt('y.txt')
print(spopt.nnls(x,y))
print(spopt.lsq_linear(x, y, bounds=(0, np.Inf), method='bvls'))
print(spopt.lsq_linear(x, y, bounds=(0, np.Inf), method='trf', verbose=2))
```

### Output:

```
In [1]: import numpy as np; import scipy.optimize as spopt
   ...: x = np.loadtxt('x.txt')
   ...: y = np.loadtxt('y.txt')
   ...: print(spopt.nnls(x,y))
   ...: print(spopt.lsq_linear(x, y, bounds=(0, np.Inf), method='bvls'))
   ...: print(spopt.lsq_linear(x, y, bounds=(0, np.Inf), method='trf', verbose=2))
   ...: 
(array([ 2.09932938,  0.        ,  0.        , 14.74758632]), 1.1295995521670104)
 active_mask: array([ 0., -1., -1.,  0.])
        cost: 0.6379975741279486
         fun: array([-0.003566  , -0.00431135, -0.00317054, ...,  0.00151165,
        0.00256816,  0.00488628])
     message: 'The first-order optimality measure is less than `tol`.'
         nit: 3
  optimality: 4.209012793594848e-15
      status: 1
     success: True
           x: array([ 2.09932938,  0.        ,  0.        , 14.74758632])
   Iteration        Cost      Cost reduction    Step norm     Optimality   
       0         5.9926e+01                                    6.86e+01    
       1         9.5818e+00      5.03e+01       2.39e+00       1.62e+01    
       2         1.5210e+00      8.06e+00       1.07e+00       3.26e+00    
       3         8.3612e-01      6.85e-01       3.31e-01       3.94e-01    
       4         7.9232e-01      4.38e-02       6.33e-01       7.22e-02    
       5         6.9727e-01      9.51e-02       9.96e+00       4.75e-02    
       6         6.9645e-01      8.16e-04       1.43e-02       7.09e-02    
/software/lsstsw/stack_20181012/python/miniconda3-4.5.4/envs/lsst-scipipe/lib/python3.6/site-packages/scipy/optimize/_lsq/common.py:321: RuntimeWarning: invalid value encountered in add
  y = a * t**2 + b * t + c
/software/lsstsw/stack_20181012/python/miniconda3-4.5.4/envs/lsst-scipipe/lib/python3.6/site-packages/scipy/optimize/_lsq/common.py:362: RuntimeWarning: invalid value encountered in double_scalars
  return 0.5 * q + l
       7             inf            nan            inf            inf      
```

### Scipy/Numpy/Python version information:

```
1.1.0 1.14.5 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```
I have also reproduced this on a different machine with 1.0.0 and 1.2.1.

**Comment by rgommers** [comment]
I can reproduce this as well. `x` has magnitudes in the range (1e-192, 0.65) while `y` in range (1.4e-7, 1.64). So this is pretty pathological. Still, infinite loops should never happen.

**Comment by nmayorov** [comment]
@taranu thanks for finding this bug!

I quickly checked your example and found that the (final) reason it failed was returning a position of `nan` when calling `np.argmin`. After I changed this call to `np.nanargmin` it converged to the same solution. However, I want to investigate whether such case is handled correctly at all. Getting `nan`s is not a good thing generally.

**Comment by isaiahpantelis** [comment]
I don't know if it is of interest, but the same behaviour persists with ill-conditioned matrices. For example, consider the following:

A = np.array([[0.8854232310355122, 0.0365312146937765, 0.0365312146836789],
 [0.3742460132129041, 0.0130523214078376, 0.0130523214077873],
 [0.9680633871281361, 0.0319366128718639, 0.0319366128718388]]),

b = np.array([0.0055029366538097, 0.0026677442422208, 0.0066612514782381]), and

bounds = (np.array([0.0, 0.0, -np.inf]), np.array([np.inf, np.inf, np.inf])),

where the 2nd and the 3rd column of A are practically collinear.

Then lsq_linear(A=A, b=b, bounds=bounds) never returns.

If, however, you round the entries of A and b to 8 digits beyond the decimal point, then lsq_linear succeeds.

Thank you for implementing lsq_linear. It has been a life saver. The issue I describe above can be avoided in client code by checking A's condition number before calling lsq_linear.

Best regards.

**Comment by nmayorov** [comment]
@isaiahpantelis 

Thanks for this test! I'm going to check that after the latest fix it is solvable by `lsq_linear`.

**Comment by nmayorov** [comment]
So the results.

Using `bvls`:

```
   Iteration        Cost      Cost reduction    Step norm     Optimality   
       0         3.2528e+13                                    1.09e+07    
       1         1.0162e-08      3.25e+13       1.61e+08       3.83e-18    
The first-order optimality measure is less than `tol`.
Number of iterations 2, initial cost 3.2528e+13, final cost 1.0162e-08, first-order optimality 3.83e-18.
 active_mask: array([ 0., -1.,  0.])
        cost: 1.0162165864391485e-08
         fun: array([ 1.31158645e-05, -1.36031441e-04,  4.05925211e-05])
     message: 'The first-order optimality measure is less than `tol`.'
         nit: 2
  optimality: 3.828413007130446e-18
      status: 1
     success: True
           x: array([ 0.00968836,  0.        , -0.08382538])
```

---------------

Using `trf`:
```
   Iteration        Cost      Cost reduction    Step norm     Optimality   
       0         1.3011e+14                                    1.30e+14    
       1         7.5081e-05      1.30e+14       3.21e+08       1.81e-04    
       2         1.6610e-06      7.34e-05       2.42e+09       3.40e-06    
       3         4.0532e-07      1.26e-06       1.46e+09       8.42e-02    
       4         3.9860e-07      6.71e-09       9.36e+03       1.80e-01    
       5         3.9860e-07      4.12e-12       4.45e+03       7.59e-10    
       6         1.0162e-08      3.88e-07       1.19e+09       8.64e-11    
The first-order optimality measure is less than `tol`.
Number of iterations 7, initial cost 1.3011e+14, final cost 1.0162e-08, first-order optimality 8.64e-11.
 active_mask: array([0, 0, 0])
        cost: 1.0162165948984031e-08
         fun: array([ 1.31157643e-05, -1.36030700e-04,  4.05950391e-05])
     message: 'The first-order optimality measure is less than `tol`.'
         nit: 7
  optimality: 8.643008744116252e-11
      status: 1
     success: True
           x: array([ 0.00968837,  0.64085948, -0.72468519])
```

The solution points differ somewhat, but as you can see the final costs are very cost. For small number of variables using `bvls` is perhaps preferable because it clearly reveals active constraints.

I'm going to add your example as a test.

**Comment by isaiahpantelis** [comment]
Great, thanks for the prompt response.
