### ISSUE TITLE
Should find_peaks' distance argument take edges into consideration

### ISSUE THREAD

**Issue by lagru** [scipy/scipy#9985]
Currently [scipy.signal.find_peaks](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html) calculates the distance between peaks as the distance between the center of plateaus thus not taking plateau edges into consideration. 

I imagine that this is irrelevant for most use-cases but might be unexpected and confusing for certain edge cases. So I'd recommend two approaches:
- leave it as is but add a note explicitly detailing that behavior (its only implied right now)
- or adapt the underlying function [`_select_by_distance`](https://github.com/scipy/scipy/blob/c3fa90dcfcaef71658744c73578e9e7d915c81e9/scipy/signal/_peak_finding_utils.pyx#L90-L157) to take edges into consideration. These are calculated since version 1.2.0 in any case so there shouldn't be a noticeable performance loss.

I'd be happy to make a PR for either approach. 

### Reproducing code example:

E.g.:
```python
>>> from scipy.signal import find_peaks
>>> x = [0, 1, 1, 1, 1, 1, 0, 2, 2, 2, 2, 2, 0]
>>> peaks, properties = find_peaks(x, distance=5, plateau_size=0)
>>> peaks
array([3, 9])
>>> properties
{'plateau_sizes': array([5, 5]),
 'left_edges': array([1, 7]),
 'right_edges': array([ 5, 11])}
```

### Scipy version information:

Applies to Scipy 1.1.0 and above.

**Comment by larsoner** [comment]
I'm fine with either solution, though the second one is backward incompatible so should only be done if we add a new `kwarg` to select between the center-based and edge-based behavior. And either way we need to preserve and document the current behavior, so I see the first solution as a prerequisite for the second anyway. So perhaps start with the first, and if people want the distance-by-edge support we can add it later. (Or if you already want it, or expect people to want it, feel free to add it as well.)
