### ISSUE TITLE
BUG: sparse: reshape method allows a shape containing an arbitrary number of 1s.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#9994]
The `reshape` method of the sparse matrix classes allows shapes with more than two dimensions if some of the lengths are 1.  For example,

```
In [24]: from scipy.sparse import csr_matrix                                                                                   

In [25]: a = csr_matrix(np.eye(4))                                                                                             

In [26]: a.reshape(2, 1, 8, 1, 1)                                                                                              
Out[26]: 
<2x8 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in COOrdinate format>
```

That should raise an error.  Those 1s should not be silently ignored.

This was checked for the current master branch:

```
In [27]: import scipy                                                                                                          

In [28]: scipy.__version__                                                                                                     
Out[28]: '1.3.0.dev0+4fd82c0'
```

**Comment by WarrenWeckesser** [comment]
The issue was originally reported in a stackoverflow question: https://stackoverflow.com/questions/55425718/reshape-sparse-matrix

**Comment by larsoner** [comment]
Agreed this is a bug

**Comment by perimosocordiae** [comment]
This behavior was added in gh-7945. Reading back over the comments, I don't think we discussed the code in question, and certainly we didn't add tests for it.

I'm +1 to merge gh-9998 and remove it, though we should make a release note explaining the backwards-incompatibilty.

**Comment by pv** [comment]
gh-9998 merged
