### ISSUE TITLE
DOC: Not all stats distributions have tutorials

### ISSUE THREAD

**Issue by pvanmulbregt** [scipy/scipy#9997]
Not all stats distributions have tutorials.   Here's a list of missing ones.  [Since the terms `frechet_l` and `frechet_r` are deprecated, they don't need a tutorial, but the others probably do.]

```
python -c "import operator, scipy.stats; print(' '.join(['doc/source/tutorial/stats/continuous_' + dst + '.rst' for dst in sorted(set(map(operator.itemgetter(0), scipy.stats._distr_params.distcont)))]))" | xargs ls -1 2>&1 | fgrep "No such" |   awk '{print $2}'

doc/source/tutorial/stats/continuous_argus.rst:
doc/source/tutorial/stats/continuous_crystalball.rst:
doc/source/tutorial/stats/continuous_exponnorm.rst:
doc/source/tutorial/stats/continuous_frechet_l.rst:
doc/source/tutorial/stats/continuous_frechet_r.rst:
doc/source/tutorial/stats/continuous_halfgennorm.rst:
doc/source/tutorial/stats/continuous_kappa3.rst:
doc/source/tutorial/stats/continuous_kappa4.rst:
doc/source/tutorial/stats/continuous_levy_stable.rst:
doc/source/tutorial/stats/continuous_moyal.rst:
doc/source/tutorial/stats/continuous_pearson3.rst:
doc/source/tutorial/stats/continuous_skewnorm.rst:
doc/source/tutorial/stats/continuous_vonmises_line.rst:
```

### Scipy/Numpy/Python version information:
```
1.3.0.dev0+f89a187 1.16.0 sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)
```

**Comment by rlucas7** [comment]
@pvanmulbregt there are also discrete distributions that do not have tutorial pages either. 

```
(scipy-dev) Lucass-MacBook:stats rlucas$ python -c "import operator, scipy.stats; print(' '.join(['doc/source/tutorial/stats/discrete_' + dst + '.rst' for dst in sorted(set(map(operator.itemgetter(0), scipy.stats._distr_params.distdiscrete)))]))" | xargs ls -1 2>&1 | fgrep "No such" |   awk '{print $2}'
doc/source/tutorial/stats/discrete_bernoulli.rst:
doc/source/tutorial/stats/discrete_binom.rst:
doc/source/tutorial/stats/discrete_boltzmann.rst:
doc/source/tutorial/stats/discrete_dlaplace.rst:
doc/source/tutorial/stats/discrete_geom.rst:
doc/source/tutorial/stats/discrete_hypergeom.rst:
doc/source/tutorial/stats/discrete_logser.rst:
doc/source/tutorial/stats/discrete_nbinom.rst:
doc/source/tutorial/stats/discrete_planck.rst:
doc/source/tutorial/stats/discrete_poisson.rst:
doc/source/tutorial/stats/discrete_randint.rst:
doc/source/tutorial/stats/discrete_skellam.rst:
doc/source/tutorial/stats/discrete_yulesimon.rst:
doc/source/tutorial/stats/discrete_zipf.rst:
```

Also, I am the author of `yulesimon` so I should be blamed (and will add) for that lack of doc.

**Comment by pvanmulbregt** [comment]
@chrisb83 I understand your point.  I do think there is value to them, in that they
* explicitly state the distribution (which may be referred to with other names, or have a different meaning to some other uses of the same name)
* explicitly state the parameterization used
* do so in a consistent manner
* provide the information in a static location, independent of book references such as JKB which are not so easily used today.

**Comment by pvanmulbregt** [comment]
@rlucas7 It's *very* easy to skip this tutorial step, not even realizing it is a thing.  There are at least 7 steps to add a new distribution, some of which are enumerated in gh-7212.

**Comment by chrisb83** [comment]
Probably it is a good idea to summarize some of the points that are expected to explained in the tutorial file when adding a distribution. I would argue that most of the points you mentioned above should be added to the API description. 
Describing alternative parametrizations might be the most important point, for instance, involving the scale parameter. Here a tutorial that explains the details would be nice. At the moment, it looks like a collection of formulae for cdf, pdf, moments etc

**Comment by chrisb83** [comment]
Related discussion: #7191
