### ISSUE TITLE
BUG: malloc() calls in Cython and C that are not checked for failure.

### ISSUE THREAD

**Issue by WarrenWeckesser** [scipy/scipy#9999]
The C function `malloc()` returns NULL (i.e. 0) if it fails to allocate memory.  The return value of a `malloc()` call must be checked for this value before attempting to use the result.  Here are places in the scipy code where this check is not made.  If any of these calls fails, the result is likely to be a segmentation fault.

**Cython**

- [x] `cluster`
       In the file `_optimal_leaf_ordering.pyx`, in the function `identify_swaps`
- [x] `interpolate`
      In the file `_ppoly.pyx`, in the functions `real_roots`, `croots_poly1` and `_croots_poly1`
- [x] `spatial`
      In `setlist.pxd`, in the function `init`, in the statement `setlists.sets[j] = ...`
- [x] `sparse.csgraph`
      File `_shortest_path.pyx`, in the code that creates `nodes` in the functions `_dijkstra_directed`, `_dijkstra_directed_multi`, `_dijkstra_undirected`, `_dijkstra_undirected_multi`
- [x] `_lib`
       In the file `_ccallback_c.pyx`, the result of `strdup` is used without checking for NULL.  `strdup` can fail to allocate memory for the duplicated string.  In that case, it returns NULL.  (Note: this might be harmless.  I haven't checked to see if the pointer is ever dereferenced while the capsule is in use.)

**C**

- [x] `fftpack`
      In the file `fftpack.h`, the macro `GEN_CACHE` is defined.  It is used in the files `convolve.c`, `drfft.c`, `zfft.c`,`zfftnd.c`
- [x] `ndimage`
      In the file `src/ni_morphology.c`, at line 624 (at the time of this writing): `temp->coordinates = malloc(...)`
- [x] `signal`
    File `sigtoolsmodule.c`, lines 914--927 (8 unchecked calls to malloc) and line 1096

-----

We have vendored code in `sparse` and `spatial` that use `malloc`:

* The SuperLU code in `linalg/dsolve/SuperLU/SRC` has its own memory management code. I didn't spend time trying to figure out the memory management here.  The file `cmemory.c` is the most relevant, and there appear to be calls to `intMalloc()` and `user_malloc()` that do not check for failure, but I didn't dig deeper to see if those functions check for failure before returning.  
* `spatial` provides a wrapper for QHull.  I didn't look very deeply into how the qhull code manages memory. It looks like the function `qh_memalloc()` in `mem_r.c` will print an error and exit if it fails.

We should be aware of these vendored packages using malloc, but I think a thorough review of their memory management is not required.  Someone can do a deep dive into either of these libraries in the future if there is ever a suspicion that they are leaking memory.

**Comment by rgommers** [comment]
Nice @WarrenWeckesser, very useful to systematically check for common errors like this, way better than fixing them one by one after users report crashes.

**Comment by WarrenWeckesser** [comment]
#10027 contains a fix for the function `identify_swaps()` in the `cluster` package.

I have no immediate plans to work on the rest of the unchecked uses of malloc(), so if anyone wants to work on this, please do!  Make a note here indicating which one you are working on.

**Comment by makeroflight** [comment]
#10035 should now contain valid fixes for
`real_roots`, `croots_poly1`, and `_croots_poly1` in `_ppoly.pyx`,
`init` in `setlist.pxd`,
and `_dijkstra_directed`, `_dijkstra_directed_multi`, `_dijkstra_undirected`, and `_dijkstra_undirected_multi` in `_shortest_path.pyx`.

**Comment by clementkng** [comment]
@WarrenWeckesser I'm going to try to pick up the `fftpack`, `ndimage`, and `signal` mallocs. A quick question, for the `fftpack`, once we recognize that a call to malloc failed, could we call the provided `destroy_##name##_cache` in the `fftpack.h` to cleanly deallocate memory? I'm not familiar w/ Fortran code, so just wanted to check my understanding.

**Comment by WarrenWeckesser** [comment]
The issues in `morphology.c` in `ndimage` was fixed in https://github.com/scipy/scipy/pull/10443

**Comment by mreineck** [comment]
@clementkng Maybe it would be good to postpone your work on `fftpack`. With a bit of luck, most of that code could be removed soon.

**Comment by peterbell10** [comment]
I've ticked off fftpack since `GEN_CACHE` no longer exists (gh-10507).

**Comment by rgommers** [comment]
@sethtroisi maybe this is something you'd be interested in tackling? 

There's stalled work in gh-10035, and other modules that haven't been started yet.

**Comment by sethtroisi** [comment]
@rgommers I'm happy to take a look at #10035 this weekend. Seems like the sort of issue I can make headway on.

**Comment by WarrenWeckesser** [comment]
@sethtroisi fixed the Cython code in `interpolate`, `spatial` and `sparse.csgraph` in https://github.com/scipy/scipy/pull/12077.

**Comment by WarrenWeckesser** [comment]
After taking a closer look at `_ccallback_c.pyx`, I marked the `_lib` item as checked.  The result of `strdup` is passed to `PyCapsule_New`, and that function allows the pointer to be NULL.  Also, the memory allocated by `strdup` (if it succeeds) is freed in the capsule destructor callback `raw_capsule_destructor` (and calling `free(name)` is a no-op when `name` is NULL), so it all looks OK.

**Comment by tylerjereddy** [comment]
This may get split over 1.7.0 and 1.8.0 I suppose, I guess I'll bump the milestone for the overall issue.

**Comment by WarrenWeckesser** [comment]
I don't think we need to keep this issue open waiting for a review of the memory management in SuperLU and QHull.  Those are vendored libraries; until we have evidence suggesting otherwise, I think we should trust their authors.  I updated the description of the issue accordingly.  A thorough review of their memory management would be more appropriately done upstream rather than in SciPy's copies.

**Comment by rgommers** [comment]
FYI, I had this on a list of issues to finish off. I think it's still useful to do, especially SuperLU - and then upstream and needed changes. Fine to leave the issue closed, but it may get done anyway.

**Comment by WarrenWeckesser** [comment]
That would be great!  Feel free reopen the issue and revert my edit of the description if you want to restore the checklist items.
